### ISSUE TITLE
Adaptive Authentication Script is disabled when configured using Console Application

### ISSUE THREAD

**Issue by HimashiRathnayake** [wso2/product-is#10000]
**Describe the issue:**

When trying to configure adaptive authentication in an application created using the `Console` application, it doesn't work as expected. When checking it with the `management console` it says that the script is disabled.

According to an already reported [issue](https://github.com/wso2/product-is/issues/8602), when configuring adaptive authentication through the [Application Management REST API](https://is.docs.wso2.com/en/latest/develop/application-rest-api/#/Applications/createApplication), the same issue seems to be happening which can be related since `Console` consumes the REST API for application creation.

NOTE: The flow works fine when an application is created using the Management Console.

**How to reproduce:**

1. Go the console application (https://localhost:9443/console).
2. Create an application.
3. Configure an adaptive authentication script.
4. Open the management console and check whether the script is disabled.

![oie_VtZuDoEB6cEc](https://user-images.githubusercontent.com/47143221/96721214-6fcd1e80-13c9-11eb-8d42-a8fbc912e8d7.png)

**Expected behavior:**

The configured script should work as expected and shouldn't be disabled.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 - BETA
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

**Comment by somindatommy** [comment]
Same issue is reeported in https://github.com/wso2/product-is/issues/8602

**Comment by rksk** [comment]
As per my understanding, this happens only when we create an app with a script that causes a warning. In the carbon console, we can skip the warning. But not from APIs.

example; (when there is no 3rd step)
```
var onLoginRequest = function(context) {   executeStep(3);};
```
