### ISSUE TITLE
One time password claim is not getting populated in the SCIM2 response

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#10008]
**Describe the issue:**
When we trigger an offline password reset flow by setting the claim http://wso2.org/claims/identity/adminForcedPasswordReset to true for a particular user through SCIM2/users API, ideally if you have enabled password reset the one-time password claim should get updated with a temporary password. But when you trigger an offline password reset flow the one time password claim is not populated with a temporary password value it returns a boolean instead.

**How to reproduce:**

1. Add two external claims urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:forcePasswordReset and urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:oneTimePassword and map them to http://wso2.org/claims/identity/adminForcedPasswordReset and http://wso2.org/claims/oneTimePassword respectively.
2. Set forcePasswordReset to true through SCIM2 REST api.

**Sample Request:** 

**URL:** https://localhost:9443/scim2/users/{user_id}
**Method:** PATCH

**Payload:**

```
{
    "Operations": [
        {
            "op": "add",
            "value": {
                "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                    "forcePasswordReset": true
                }
            }
        }
    ],
    "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"]
}

```

3. Request the oneTimePassword claim for the same user.

**Sample Request:**

**URL:** https://localhost:9443/scim2/Users/b00427ce-fe7e-4857-8e8d-c0be1ab3ab3f?attributes=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.oneTimePassword
**Method:** GET

**Expected behavior:**

Ideally, one time password value should be returned in the response as given below. (Please note that one-time password value is populated in the management console user profile)

```
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "id": "b00427ce-fe7e-4857-8e8d-c0be1ab3ab3f",
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
        "oneTimePassword": "ABCDE"
    }
} 
```

**Comment by janakamarasena** [comment]
This was due to a configuration issue scim2 extension schema config.

**Comment by janakamarasena** [comment]
@jpierson-at-riis as I remember it was a issue with how the claims were added for the claims mentioned in "How to reproduce" section of the issue. I cannot remember what the exact misconfiguration was. However from Identity Server 5.11.0 onwards these two claims are already configured. It should be added as [1] in the scim2-schema-extension.config file apart from it being mapped through the UI. 

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/297/files
