### ISSUE TITLE
Exception is thrown when Response Signing is enabled in SAML web application

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10011]
**Describe the issue:**
"SAML2 Assertion signing is enabled, but signature element not found in SAML2 Assertion element" exception is thrown when Sign SAML Response is enabled in the console. Response signing was set to true in the sso.properties file for saml2-web-app-pickup-dispatch sample app as well. 

```
org.wso2.carbon.identity.sso.agent.exception.SSOAgentException: SAML2 Assertion signing is enabled, but signature element not found in SAML2 Assertion element
	org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.validateSignature(SAML2SSOManager.java:902)
	org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.processSSOResponse(SAML2SSOManager.java:581)
	org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.processSSOResponse(SAML2SSOManager.java:525)
	org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.processResponse(SAML2SSOManager.java:358)
	org.wso2.carbon.identity.sso.agent.SAML2SSOAgentFilter.doFilter(SAML2SSOAgentFilter.java:98)
```

**How to reproduce:**

1. Access https://localhost:9443/console
2. Login as super admin
3. Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4. When the application is created navigate to the Access tab > SAML
5. Do manual configuration according to the docs[1].
      - "Enable Response signing" is "Sign SAML Responses" in the console
      - "Enable Signature Validation..." is "Enable request signature validation" in the console  
6. Update the changes
7. Setup the saml2-web-app-pickup-dispatch.com[2]
7. Try to login to the saml2-web-app-pickup-dispatch.com sample app

[1] - (https://is.docs.wso2.com/en/5.11.0/learn/configuring-saml2-web-single-sign-on/)
[2] - (https://is.docs.wso2.com/en/5.11.0/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp)

**Environment information:**
 - Product Version: IS 5.11.0-beta3-SNAPSHOT
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

**Comment by sachiniWettasinghe** [comment]
Tested with a `wso2is-5.11.0-beta4-SNAPSHOT` and the issue was not reproduced. Hence closing the issue.
