### ISSUE TITLE
[consoleApp] Couldn't edit audience of ws trust sp

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10026]
**Describe the issue:**
Once added a service provider with WS trust protocol couldn't able to edit the audience value.

**How to reproduce:**
1. Add ws trust protocol sp
2. Configure audience and certificate.
3. Try to edit the audience value

**Expected behavior:**
Should be able to edit the audience value.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by thivi** [comment]
WS Trust has been removed with an update to opensaml-3.0. So, this was removed from the UI by https://github.com/wso2/identity-apps/pull/1282
