### ISSUE TITLE
[consoleApp] Unable to remove the selected HTTP Post or HTTP Redirect methods under single sign on profile of a saml web application.

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10027]
**Describe the issue:**
Unable to remove the selected HTTP Post and HTTP Redirect methods under single sign on profile of a saml web application.

**How to reproduce:**

Access https://localhost:9443/console
1. Login as super admin
2. Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
3. When the application is created navigate to the Access tab > SAML > Single sign on profile
4. Try to remove the HTTP Post or HTTP Redirect methods from the check box option 
5. Update

**Observation**
Even though it says updated successfully. Does not get removed either of these options

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thivi** [comment]
This seems like a backend issue. Though a `PUT` request to the `api/server/v1/applications/{id}/saml` endpoint succeeds, a `GET` request sent after the `PUT` request doesn't return the updated bindings.

The `PUT` request sent. Note that the `bindings` attribute has only one element.
![image](https://user-images.githubusercontent.com/20745428/97225894-4103dd80-17f9-11eb-9def-4f5ff712d2ef.png)


The `GET` request sent to obtain the application details. Note that the `bindings` attribute has two elements.
![image](https://user-images.githubusercontent.com/20745428/97226081-82948880-17f9-11eb-8860-c2d9c3732d68.png)

**Comment by somindatommy** [comment]
Currently, we do not support this behavior. Therefore, these two options should be enabled and read-only by default. The solution here would be to make this read-only on the UI side and from the API side, we can return a client error.

**Comment by IsuraD** [comment]
@somindatommy reopened due to UI read-only fix is required. 
@thivi
