### ISSUE TITLE
[consoleApp] Even after deleting ws trust protocol config still showing in the UI

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10028]
**Describe the issue:**
Even after deleting ws trust protocol config still showing in the UI as below.
![1](https://user-images.githubusercontent.com/20336761/96956890-df045900-1516-11eb-8b1b-86827837b1c7.png)

**How to reproduce:**
1. Create an sp with ws trust protocol.
2. Delete the inbound config
3. Still you can see the inbound config with ws trust
4. Once go to list of aplications and select the sp and check, it is not there

**Expected behavior:**
WS trust config shouldn't be shown

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by brionmario** [comment]
WS Trust was removed from the protocols section with PR https://github.com/wso2/identity-apps/pull/1282 since it was removed with opensaml-3.0 update[1]

[1] https://github.com/wso2/product-is/issues/10043#issuecomment-717799111
