### ISSUE TITLE
[consoleAPP] If there is an error while deleting an idp the error messages not displayed properly

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10025]
**Describe the issue:**
When deleting an idp, if the idp is already used by an sp then there is an error message as below.
![1](https://user-images.githubusercontent.com/20336761/96955965-8cc23880-1514-11eb-87d5-e59f42f1315f.png)

Here error messages are quickly disappearing before reading it and also couldn't see full message.

**How to reproduce:**
1. Create a sp and idp
2. Configure the idp as one of the steps for the sp
3. Try to delete the idp

**Expected behavior:**
Clear error message should be displayed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC
---

**Comment by DimalChandrasiri** [comment]
Current notification implementation structure has a limitation where the notifications are no persisted to any place and the users have no way to look into old or session related notification. Ideally there should be a notification centre UI to view the notifications in detail. 

As a work around we could implement a notification persisting logic to persist the notifications to the browser storage. The limitation is this will only be limited to per tab and if the use switches or opens a new tab all the notifications will be lost. To overcome this we will need to add backend support to persist and retrieve notifications related to a user.

**Comment by DimalChandrasiri** [comment]
Since the notification persistence is yet to be implemented, we have improved the current notification structure according to the issue [here](https://github.com/wso2-enterprise/asgardeo-product/issues/2699)

**Comment by nilasini** [comment]
Couldn't reproduce the issue with wso2is-alpha17 pack as the behaviour got changed.
<img width="603" alt="Screenshot 2022-03-30 at 17 00 34" src="https://user-images.githubusercontent.com/20336761/160824931-f7adc698-0a88-46ac-b698-c55836006b4a.png">
