### ISSUE TITLE
[consoleApp] Unable to add single page app as a new protocol from a created saml web application as it navigates for a blank page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10034]
**Describe the issue:**
Unable to add single page app as a new protocol from a created saml web applications access tab

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for Access tab
5. Click on + New protocol
6. Select Quick setup > single page app
7. Click Next

**Observation**
Configurations are not getting loaded. Navigating for a blank page. 

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

![console13](https://user-images.githubusercontent.com/31848014/96963233-eaab4c00-1525-11eb-839b-1ec18644dd44.png)

**Comment by brionmario** [comment]
@ShanikaWickramasinghe This issue seems to be fixed with https://github.com/wso2/identity-apps/pull/1268

![Oct-29-2020 13-50-36](https://user-images.githubusercontent.com/25959096/97543308-0fa03300-19ee-11eb-9d1d-1bcc32df123d.gif)

Hence closing the issue.
