### ISSUE TITLE
Setting two primary emails are possible via SCIM API

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#10033]
When registering a user with SCIM API, it is possible to have two primary emails by setting the primary flag as true. But neither of the emails gets updated in the console and the email field is left as empty.

**How to reproduce:**
Send a HTTP Request as follow
```
curl --location --request POST 'https://localhost:9443/wso2/scim/Users' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "schemas": [],
    "name": {
        "familyName": "Peiris",
        "givenName": "Suresh"
    },
    "userName": "wso2.org/sureshp",
    "password": "suresh",
    "emails": [
        {
            "primary": true,
            "value": "tsmpmail@gmail.com",
            "type": "home"
        },
        {
            "primary": true,
            "value": "sureshp@wso2.com",
            "type": "work"
        }
    ]
}'
```

**Expected behavior:**
It should give a warning or an error.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: 5.11.0 Beta2 SNAPSHOT
OS: Ubuntu 18.04
Database: MySQL
Primary User store: JDBC
Secondary User store: Embedded LDAP

**Comment by ShanikaWickramasinghe** [comment]
@tsuresh the EP needs to be scim2 as /scim2/Users please verify with scim2 EP.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
