### ISSUE TITLE
Validate functionality of IS Analytics with the compatible environments of IS

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#10045]
**Is your suggestion related to an experience ? Please describe.**
IS Product is tested and supported to deploy on environments mentioned in doc [1].
IS Analytics ideally should be able to deploy in same environment.

So IS Analytics should have the tested for the same list of environments and if there are any mismatches better to mention those explicitly.

[1] https://is.docs.wso2.com/en/latest/setup/environment-compatibility/#environment-compatibility

**Comment by inthirakumaaran** [comment]
For IS analytics we can support oracle 19c as well. This DBMS is tested while doing fix for https://github.com/wso2/product-is/issues/10187

**Comment by sumedhe** [comment]
Tested the compatibility of IS Analytics 5.8.0 in following environments

OS:
* macOS Catalina 10.15.7
* Ubuntu 20.04
* Ubuntu 18.04
* Windows 10
* openSUSE Tumbleweed 20201114

Database:
* MySQL 8.0
* MySQL 5.7
* Oracle 12.2.0.1
* Microsoft SQL Server 2019
* Postgres 11
* Postgres 10.5

Java:
* OpenJDK 8
* Oracle JDK 8
* AdoptOpenJDK 8

Note: JDK 11 is not supported

**Comment by sumedhe** [comment]
@sherenewso2 @gomathyk FYI

**Comment by rksk** [comment]
This information needs to be added to 5.9.0 and 5.10.0 docs too.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
