### ISSUE TITLE
[consoleApp] Unable to add manual setup openid connect as a new protocol from a created saml web applications access tab

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10042]
**Describe the issue:**
Unable to add manual setup openid connect as a new protocol from a created saml web applications access tab

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for Access tab
5. Click on + New protocol
6. Select Manual setup > Openid connect
7. Click Next

**Observation**
Configurations are not getting loaded. Navigating for a blank page.

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by brionmario** [comment]
@ShanikaWickramasinghe This issue seems to be fixed with https://github.com/wso2/identity-apps/pull/1268

![Oct-29-2020 14-01-21](https://user-images.githubusercontent.com/25959096/97544193-43c82380-19ef-11eb-8af2-dc9daf4a9f4c.gif)

Hence closing the issue.
