### ISSUE TITLE
API version for api/identity/auth is incorrect

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10048]
**Description:**
The API version in the following document and its samples is v1.2. But the actual version in the WSO2 IS 5.10.0 is v1.1

```
curl -k -v -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/api/identity/auth/v1.1/authenticate"
```
```
curl -k -v -X POST -H "Content-Type: application/json" -d '{ "username": "admin","password": "admin"}' "https://localhost:9443/api/identity/auth/v1.1/authenticate"
```

[1] https://docs.wso2.com/display/IS510/apidocs/Authentication-framework-apis/index.html

**Comment by LahiruLS** [comment]
After 2 years you saved mine too.

**Comment by rksk** [comment]
This is fixed. But doc locations also have been changed by now.

https://is.docs.wso2.com/en/5.10.0/develop/using-the-authentication-rest-apis/
https://api-docs.wso2.com/apidocs/is/is510/Authentication-framework-apis
