### ISSUE TITLE
[consoleApp] When adding WS Trust as a new protocol for a saml web application configurations does not get loaded

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10043]
**Describe the issue:**
Unable to add manual setup WS Trust as a new protocol from a created saml web applications access tab

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for Access tab
5. Click on + New protocol
6. Select Manual setup > WS Trust
7. Click Next

**Observation**
Configurations are not getting loaded. It keeps loading and a configuration page does not get loaded
![console14](https://user-images.githubusercontent.com/31848014/96973844-12a2ab80-1536-11eb-91d9-1881043cf4c2.png)

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thivi** [comment]
The request to the `api/server/v1/applications/meta/inbound-protocols/ws-trust` endpoint returns the following error:
```json
code: "APP-60504"
description: "STS admin service is unavailable at the moment."
message: "WS-Trust protocol is not supported."
traceId: "29631f59-3fba-4070-a9f1-308f844d28d6"
```

**Comment by thanujalk** [comment]
@thivi this is removed with opensaml-3.0 update, we can remove the ws-trust from this window.

**Comment by portilloga** [comment]
Good morning.

  Team, this time I am trying to create a Service Provider (application) on WSO2 Is 5.11.0 using APIS following instructions from official documentation, But I received a message with 404 Bad request status code.


The response is:
{
    "code": "APP-60001",
    "message": "Invalid Request.",
    "description": "STS admin service is unavailable at the moment.",
    "traceId": "2a244ec6-1589-478c-a805-12a0bbb1a01c"
}

This is the wso2carbon.log entrance:

[2021-09-15 10:07:04,785] [a0536ef4-4439-4f0e-8738-7f4eaf2590d9]  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} - An instance of org.wso2.carbon.identity.oauth2.token.OauthTokenIssuerImpl is created for Identity OAuth token generation.
[2021-09-15 10:07:04,851] [a0536ef4-4439-4f0e-8738-7f4eaf2590d9]  INFO {org.opensaml.core.config.InitializationService} - Initializing OpenSAML using the Java Services API
[2021-09-15 10:07:08,366] [a0536ef4-4439-4f0e-8738-7f4eaf2590d9]  INFO {org.opensaml.core.config.InitializationService} - Initializing OpenSAML using the Java Services API


I Enabled on deployment.toml the admin web services access:
[admin_service.wsdl]
enable= true 

Machine feautres:
S.O: Ubuntu 18.04
JVM: Java 1.8.0_281

Here is my api call:

curl -X POST "https://localhost:9443/t/carbon.super/api/server/v1/applications" -H  "accept: */*" -H  "Content-Type: application/json" -d request.json

Where request.json contains:
{
  "name": "FirstTry",
  "description": "This is the configuration for Pickup application.",
  "imageUrl": "https://example.com/logo/my-logo.png",
  "accessUrl": "https://example.com/login",
  "templateId": "980b8tester24c64a8a09a0d80abf8c337bd2555",
  "claimConfiguration": {
    "dialect": "LOCAL",
    "claimMappings": [
      {
        "applicationClaim": "firstname",
        "localClaim": {
          "uri": "http://wso2.org/claims/username"
        }
      }
    ],
    "requestedClaims": [
      {
        "claim": {
          "uri": "http://wso2.org/claims/username"
        },
        "mandatory": false
      }
    ],
    "subject": {
      "claim": {
        "uri": "http://wso2.org/claims/username"
      },
      "includeUserDomain": false,
      "includeTenantDomain": false,
      "useMappedLocalSubject": false
    },
    "role": {
      "mappings": [
        {
          "localRole": "admin",
          "applicationRole": "Administrator"
        }
      ],
      "includeUserDomain": true,
      "claim": {
        "uri": "http://wso2.org/claims/username"
      }
    }
  },
  "inboundProtocolConfiguration": {
    "saml": {
      "metadataFile": "ICA8bWQ6RW50aXR5RGVzY3JpcHRvciBlbnRpdHlJRD0iaHR0cHM6Ly9zc28uZXhhbXBsZS5jb20vcG9ydGFsIiB2YWxpZFVudGlsPSIyMDE3LTA4LTMwVDE5OjEwOjI5WiIKICAgIHhtbG5zOm1kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bWV0YWRhdGEiCiAgICB4bWxuczpzYW1sPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIgogICAgeG1sbnM6bWRycGk9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOm1ldGFkYXRhOnJwaSIKICAgIHhtbG5zOm1kYXR0cj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6bWV0YWRhdGE6YXR0cmlidXRlIgogICAgeG1sbnM6bWR1aT0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6bWV0YWRhdGE6dWkiCiAgICB4bWxuczppZHBkaXNjPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDpwcm9maWxlczpTU086aWRwLWRpc2NvdmVyeS1wcm90b2NvbCIKICAgIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4KICAgIDwhLS0gaW5zZXJ0IGRzOlNpZ25hdHVyZSBlbGVtZW50IChvbWl0dGVkKSAtLT4KICAgIDxtZDpFeHRlbnNpb25zPgogICAgICA8bWRycGk6UmVnaXN0cmF0aW9uSW5mbyByZWdpc3RyYXRpb25BdXRob3JpdHk9Imh0dHBzOi8vcmVnaXN0cmFyLmV4YW1wbGUubmV0Ii8+CiAgICAgIDxtZHJwaTpQdWJsaWNhdGlvbkluZm8gY3JlYXRpb25JbnN0YW50PSIyMDE3LTA4LTE2VDE5OjEwOjI5WiIgcHVibGlzaGVyPSJodHRwczovL3JlZ2lzdHJhci5leGFtcGxlLm5ldCIvPgogICAgICA8bWRhdHRyOkVudGl0eUF0dHJpYnV0ZXM+CiAgICAgICAgPHNhbWw6QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9yZWdpc3RyYXIuZXhhbXBsZS5uZXQvZW50aXR5LWNhdGVnb3J5IiBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXR0cm5hbWUtZm9ybWF0OnVyaSI+CiAgICAgICAgICA8c2FtbDpBdHRyaWJ1dGVWYWx1ZT5odHRwczovL3JlZ2lzdHJhci5leGFtcGxlLm5ldC9jYXRlZ29yeS9zZWxmLWNlcnRpZmllZDwvc2FtbDpBdHRyaWJ1dGVWYWx1ZT4KICAgICAgICA8L3NhbWw6QXR0cmlidXRlPgogICAgICA8L21kYXR0cjpFbnRpdHlBdHRyaWJ1dGVzPgogICAgPC9tZDpFeHRlbnNpb25zPgogICAgPG1kOlNQU1NPRGVzY3JpcHRvciBXYW50QXNzZXJ0aW9uc1NpZ25lZD0idHJ1ZSIgcHJvdG9jb2xTdXBwb3J0RW51bWVyYXRpb249InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCI+CiAgICAgIDxtZDpFeHRlbnNpb25zPgogICAgICAgIDxtZHVpOlVJSW5mbz4KICAgICAgICAgIDxtZHVpOkRpc3BsYXlOYW1lIHhtbDpsYW5nPSJlbiI+RXhhbXBsZS5jb20gVmVuZG9yIFNlcnZpY2U8L21kdWk6RGlzcGxheU5hbWU+CiAgICAgICAgICA8bWR1aTpJbmZvcm1hdGlvblVSTCB4bWw6bGFuZz0iZW4iPmh0dHBzOi8vc2VydmljZS5leGFtcGxlLmNvbS9hYm91dC5odG1sPC9tZHVpOkluZm9ybWF0aW9uVVJMPgogICAgICAgICAgPG1kdWk6UHJpdmFjeVN0YXRlbWVudFVSTCB4bWw6bGFuZz0iZW4iPmh0dHBzOi8vc2VydmljZS5leGFtcGxlLmNvbS9wcml2YWN5Lmh0bWw8L21kdWk6UHJpdmFjeVN0YXRlbWVudFVSTD4KICAgICAgICAgIDxtZHVpOkxvZ28gaGVpZ2h0PSIzMiIgd2lkdGg9IjMyIiB4bWw6bGFuZz0iZW4iPmh0dHBzOi8vc2VydmljZS5leGFtcGxlLmNvbS9teWljb24ucG5nPC9tZHVpOkxvZ28+CiAgICAgICAgPC9tZHVpOlVJSW5mbz4KICAgICAgICA8aWRwZGlzYzpEaXNjb3ZlcnlSZXNwb25zZSBpbmRleD0iMCIgQmluZGluZz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6cHJvZmlsZXM6U1NPOmlkcC1kaXNjb3ZlcnktcHJvdG9jb2wiIExvY2F0aW9uPSJodHRwczovL3NlcnZpY2UuZXhhbXBsZS5jb20vU0FNTDIvTG9naW4iLz4KICAgICAgPC9tZDpFeHRlbnNpb25zPgogICAgICA8bWQ6S2V5RGVzY3JpcHRvciB1c2U9ImVuY3J5cHRpb24iPgogICAgICAgIDxkczpLZXlJbmZvPi4uLjwvZHM6S2V5SW5mbz4KICAgICAgPC9tZDpLZXlEZXNjcmlwdG9yPgogICAgICA8bWQ6TmFtZUlERm9ybWF0PnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OnRyYW5zaWVudDwvbWQ6TmFtZUlERm9ybWF0PgogICAgICA8bWQ6QXNzZXJ0aW9uQ29uc3VtZXJTZXJ2aWNlIGluZGV4PSIwIiBCaW5kaW5nPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YmluZGluZ3M6SFRUUC1QT1NUIiAgTG9jYXRpb249Imh0dHBzOi8vc2VydmljZS5leGFtcGxlLmNvbS9TQU1MMi9TU08vUE9TVCIvPgogICAgICA8bWQ6QXR0cmlidXRlQ29uc3VtaW5nU2VydmljZSBpbmRleD0iMCI+CiAgICAgICAgPG1kOlNlcnZpY2VOYW1lIHhtbDpsYW5nPSJlbiI+RXhhbXBsZS5jb20gRW1wbG95ZWUgUG9ydGFsPC9tZDpTZXJ2aWNlTmFtZT4KICAgICAgICA8bWQ6UmVxdWVzdGVkQXR0cmlidXRlIGlzUmVxdWlyZWQ9InRydWUiCiAgICAgICAgICBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXR0cm5hbWUtZm9ybWF0OnVyaSIKICAgICAgICAgIE5hbWU9InVybjpvaWQ6MS4zLjYuMS40LjEuNTkyMy4xLjEuMS4xMyIgRnJpZW5kbHlOYW1lPSJlZHVQZXJzb25VbmlxdWVJZCIvPgogICAgICAgIDxtZDpSZXF1ZXN0ZWRBdHRyaWJ1dGUKICAgICAgICAgIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6dXJpIgogICAgICAgICAgTmFtZT0idXJuOm9pZDowLjkuMjM0Mi4xOTIwMDMwMC4xMDAuMS4zIiBGcmllbmRseU5hbWU9Im1haWwiLz4KICAgICAgPC9tZDpBdHRyaWJ1dGVDb25zdW1pbmdTZXJ2aWNlPgogICAgPC9tZDpTUFNTT0Rlc2NyaXB0b3I+CiAgICA8bWQ6T3JnYW5pemF0aW9uPgogICAgICA8bWQ6T3JnYW5pemF0aW9uTmFtZSB4bWw6bGFuZz0iZW4iPkV4YW1wbGUuY29tIEluYy48L21kOk9yZ2FuaXphdGlvbk5hbWU+CiAgICAgIDxtZDpPcmdhbml6YXRpb25EaXNwbGF5TmFtZSB4bWw6bGFuZz0iZW4iPkV4YW1wbGUuY29tPC9tZDpPcmdhbml6YXRpb25EaXNwbGF5TmFtZT4KICAgICAgPG1kOk9yZ2FuaXphdGlvblVSTCB4bWw6bGFuZz0iZW4iPmh0dHBzOi8vd3d3LmV4YW1wbGUuY29tLzwvbWQ6T3JnYW5pemF0aW9uVVJMPgogICAgPC9tZDpPcmdhbml6YXRpb24+CiAgICA8bWQ6Q29udGFjdFBlcnNvbiBjb250YWN0VHlwZT0idGVjaG5pY2FsIj4KICAgICAgPG1kOlN1ck5hbWU+U0FNTCBUZWNobmljYWwgU3VwcG9ydDwvbWQ6U3VyTmFtZT4KICAgICAgPG1kOkVtYWlsQWRkcmVzcz5tYWlsdG86dGVjaG5pY2FsLXN1cHBvcnRAZXhhbXBsZS5jb208L21kOkVtYWlsQWRkcmVzcz4KICAgIDwvbWQ6Q29udGFjdFBlcnNvbj4KICA8L21kOkVudGl0eURlc2NyaXB0b3I+Cg",
      "metadataURL": "https://example.com/samlsso/meta",
      "manualConfiguration": {
        "issuer": "string",
        "serviceProviderQualifier": "string",
        "assertionConsumerUrls": [
          "string"
        ],
        "defaultAssertionConsumerUrl": "string",
        "idpEntityIdAlias": "string",
        "singleSignOnProfile": {
          "bindings": [
            "HTTP_POST"
          ],
          "enableSignatureValidationForArtifactBinding": false,
          "enableIdpInitiatedSingleSignOn": false,
          "assertion": {
            "nameIdFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
            "audiences": [
              "https://app.example.com/saml"
            ],
            "recipients": [
              "https://app.example.com/saml"
            ],
            "digestAlgorithm": "http://www.w3.org/2000/09/xmldsig#sha1",
            "encryption": {
              "enabled": false,
              "assertionEncryptionAlgorithm": "string",
              "keyEncryptionAlgorithm": "string"
            }
          }
        },
        "attributeProfile": {
          "enabled": false,
          "alwaysIncludeAttributesInResponse": false
        },
        "singleLogoutProfile": {
          "enabled": true,
          "logoutRequestUrl": "string",
          "logoutResponseUrl": "string",
          "logoutMethod": "BACKCHANNEL",
          "idpInitiatedSingleLogout": {
            "enabled": false,
            "returnToUrls": [
              "string"
            ]
          }
        },
        "requestValidation": {
          "enableSignatureValidation": true,
          "signatureValidationCertAlias": "string"
        },
        "responseSigning": {
          "enabled": true,
          "signingAlgorithm": "string"
        },
        "enableAssertionQueryProfile": false
      }
    },
    "oidc": {
      "clientId": "string",
      "clientSecret": "string",
      "grantTypes": [
        "authorization_code",
        "password"
      ],
      "callbackURLs": [
        "regexp=(https://app.example.com/callback1|https://app.example.com/callback2)"
      ],
      "allowedOrigins": [
        "https://app.example.com"
      ],
      "publicClient": false,
      "pkce": {
        "mandatory": false,
        "supportPlainTransformAlgorithm": true
      },
      "accessToken": {
        "type": "JWT",
        "userAccessTokenExpiryInSeconds": 3600,
        "applicationAccessTokenExpiryInSeconds": 3600,
        "bindingType": "cookie",
        "revokeTokensWhenIDPSessionTerminated": true,
        "validateTokenBinding": true
      },
      "refreshToken": {
        "expiryInSeconds": 86400,
        "renewRefreshToken": true
      },
      "idToken": {
        "expiryInSeconds": 3600,
        "audience": [
          "http://idp.xyz.com",
          "http://idp.abc.com"
        ],
        "encryption": {
          "enabled": false,
          "algorithm": "RSA-OAEP",
          "method": "A128CBC+HS256"
        }
      },
      "logout": {
        "backChannelLogoutUrl": "https://app.example.com/backchannel/callback",
        "frontChannelLogoutUrl": "https://app.example.com/frontchannel/callback"
      },
      "validateRequestObjectSignature": false,
      "scopeValidators": [
        "Role based scope validator",
        "XACML Scope Validator"
      ]
    },
    "passiveSts": {
      "realm": "string",
      "replyTo": "string"
    },
    "wsTrust": {
      "audience": "https://wstrust.endpoint.com",
      "certificateAlias": "wso2carbon"
    },
    "custom": [
      {
        "name": "cas",
        "configName": "cas",
        "properties": [
          {
            "key": "app-identifier",
            "value": "http://app.wso2.com/employeeApp",
            "friendlyName": "Application Identifier"
          }
        ]
      }
    ]
  },
  "authenticationSequence": {
    "type": "DEFAULT",
    "steps": [
      {
        "id": 1,
        "options": [
          {
            "idp": "LOCAL",
            "authenticator": "basic"
          }
        ]
      }
    ],
    "requestPathAuthenticators": [
      "string"
    ],
    "script": "string",
    "subjectStepId": 1,
    "attributeStepId": 1
  },
  "advancedConfigurations": {
    "saas": false,
    "discoverableByEndUsers": false,
    "certificate": {
      "type": "JWKS",
      "value": "string"
    },
    "skipLoginConsent": false,
    "skipLogoutConsent": false,
    "returnAuthenticatedIdpList": false,
    "enableAuthorization": true
  },
  "provisioningConfigurations": {
    "inboundProvisioning": {
      "proxyMode": false,
      "provisioningUserstoreDomain": "PRIMARY"
    },
    "outboundProvisioningIdps": [
      {
        "idp": "Google",
        "connector": "googleapps",
        "blocking": false,
        "rules": false,
        "jit": false
      }
    ]
  }
}
