### ISSUE TITLE
[Console App]Couldn't add claim mapping for  federated idp with console app

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10053]
**Describe the issue:**

Couldn't add claim mapping for federated IDP with console app. Once selected the attribute mappings and click update, always getting "cannot perform update Need to configure all the mandatory properties.". But with management console could able to add successfully

**How to reproduce:**
1. Create an IDP
2. Configure attribute mapping
3. Click update

**Expected behavior:**
Successfully updated.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by thivi** [comment]
The issue is caused by the role attribute and the subject attribute not being filled. However, the user wouldn't know that these are mandatory fields because the fields haven't been set to required and a validation error message is not being shown.
