### ISSUE TITLE
Adjust/Remove 5.10.0 WUM content in 5.11.0 

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#10052]
**Describe the improvement**
- Remove references to 5.10.0 wum updates in the docs 
- Some instructions related to wum update features need to change/be removed

**Comment by pulasthi7** [comment]
@sherenewso2 is this issue fixed with the above PR. Can we close this issue if there are no other such references?

**Comment by sherenewso2** [comment]
> @sherenewso2 is this issue fixed with the above PR. Can we close this issue if there are no other such references?

There are a few more. Will send a PR to fix those as well
