### ISSUE TITLE
[ConsoleApp][Windows] User roles are not getting update according to the assigned group role permissions

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10071]
**Describe the issue:**
Created user role permission are not getting update once the user added to a User group which having different role permission in the group.  

**How to reproduce:**

- Log in to the console app
- Create a User with few role permissions (ex: admin, system) and save
- Create User Group and assign the user which create in #2 step.
- Add the group role permission (which are different from the given user permission) and save
- Check the Created User role permissions

**Expected behavior:**
User role permission should be updated according to the assigned group role permission

**Environment information** 
 - Product Version: 5.11.0 beta3 Snapshot
 - OS: Widnows
 - Database: H2
 - Userstore: LDAP

**Suggested labels:**
Severity/Critical
Priority/High
console

**Comment by thanujalk** [comment]
Assuming the explained issue as,

Admin can't get the cumulative role list which is directly assigned and inherited from groups in the user edit view.

This seems to be an improvement, but there is a performance concern while building the cumulative role list.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
