### ISSUE TITLE
[consoleApp] Updating Role Mapping via the Attributes tab for a saml web application fails with Error something went wrong message

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10073]
**Describe the issue:**
Updating Role Mapping via the Attributes tab for a saml web application fails

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for Attributes tab
5. Role Mapping section
6. Add local role as admin from the suggested drop down list and add a application role as test
7. Click Update

**Observation**
UI error is getting  displayed and update is not successfull

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console15](https://user-images.githubusercontent.com/31848014/97147316-5ba16c80-178f-11eb-8d45-bd4c01218038.png)

**Comment by thivi** [comment]
The request returns the following error
```json
code: "APP-60001"
description: "Invalid application configuration for application: 'Sample' of tenantDomain: carbon.super. Local Role Sample is not available in the server."
message: "Error patching application with id: 8f2da1c6-6977-4952-baba-118954c042a0"
traceId: "76728755-e50f-4f27-8f07-0c96ec74ff02"
```
But the local role Sample is available.
