### ISSUE TITLE
[ConsoleApp][Windows] User details are not getting updated

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10072]
**Describe the issue:**
Created user details are not getting update once its update and save. PATCH API call is getting pending for a long time and not returning back call. 

<img width="492" alt="Screen Shot 2020-10-26 at 12 20 54 PM" src="https://user-images.githubusercontent.com/40847371/97141950-bcc44280-1785-11eb-8557-0bb192057315.png">

**How to reproduce:**
- Login into console App
- Create a user and Save
- Update the user details and click save

**Expected behavior:**
Updated details should be reflected. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 Beta3
 - OS: Windows
 - Database: H2
 - Userstore: LDAP

**Suggested labels:**
Severity/Critical
Priority/High
console

**Comment by thanujalk** [comment]
@RidmiR is there a stack trace in carbon logs?

**Comment by thivi** [comment]
I am not able to reproduce this issue. 

This issue is most likely due to a slow connection between the console app and the server or due to the server being unresponsive.

**Comment by jeradrutnam** [comment]
Tested with wso2is-5.11.0-beta5 pack on Windows 10. Couldn't reproduce.
