### ISSUE TITLE
[consoleApp] Adding basic auth as a local authenticator for a new authenticator step via sign on method of a saml web app fails

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10076]
**Describe the issue:**
Updating sign on method by adding another authenticator step as step and adding basic auth local authenticator for step 2 fails

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for sign on method tab
5. Click + New authenticator se
6. Drag and drop basic auth local authenticator for step 2
7. Click Update

**Observation**
UI error is getting displayed and update is not successfull

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 
ubuntu 16.04
Chrome Version 85.0.4183.121

![console16](https://user-images.githubusercontent.com/31848014/97152416-de79f580-1796-11eb-80a7-94b2fdd241ff.png)

**Comment by thivi** [comment]
The request returns the following error.
```json
code: "APP-60001"
description: "Invalid application configuration for application: 'Sample' of tenantDomain: carbon.super. Authenticator BasicAuthRequestPathAuthenticator is not available in the server."
message: "Error patching application with id: 8f2da1c6-6977-4952-baba-118954c042a0"
traceId: "8af0b7ee-a346-439b-b3a2-0e7170d11265"
```
