### ISSUE TITLE
[consoleApp] Adding oauth bearer as a new authenticator step via a sign on method tab of a saml web app fails

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10077]
**Describe the issue:**
Updating sign on method by adding another authenticator step as step and adding oauth bearer local authenticator for step 2 fails

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for sign on method tab
5. Click + New authenticator step
6. Drag and drop oauth bearer authenticator for step 2
7. Click Update

**Observation**
UI error is getting displayed and update is not successfull

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thivi** [comment]
The following error is returned by the request. 
```json
code: "APP-60001"
description: "Invalid application configuration for application: 'Sample' of tenantDomain: carbon.super. Authenticator OAuthRequestPathAuthenticator is not available in the server."
message: "Error patching application with id: 8f2da1c6-6977-4952-baba-118954c042a0"
traceId: "65065308-26c3-4653-825a-82c744b463d3"
```

**Comment by thanujalk** [comment]
@ShanikaWickramasinghe @thivi basic-auth and oauth-bearer are request-path authenticators and need to be removed from the step configuration. They have a separate section at the end of the page. Basically, any request path authenticator should not appear in the step configuration section.
