### ISSUE TITLE
Console app calling wrong endpoint to get Role permissions

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10079]
In the console app when we go to the Roles -> Permissions 
It is calling the `Groups` endpoint to get the permission data. Instead, it should call the `Roles` endpoint.

**Comment by thivi** [comment]
The endpoint issue has been resolved by https://github.com/wso2/identity-apps/pull/1282.
However, the endpoint throws an error when a `PATCH` request is sent to update permissions. This issue is tracked here: https://github.com/wso2/product-is/issues/10103
