### ISSUE TITLE
When secure vault is enabled, [secrets] should be the last section in config file

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#10081]
This is related to the issue
https://github.com/wso2/product-is/issues/9421

Until that get fixed properly, we need to mention that the `[secrets]` section should be the very last section in the deployment.toml

**Comment by sherenewso2** [comment]
This is mentioned in [1] (that's the only place in docs where we instruct to add the `[secrets]` section to the toml file). 

[1] https://is.docs.wso2.com/en/5.11.0/setup/encrypting-passwords-with-cipher-tool/#encrypting-passwords
