### ISSUE TITLE
Need a Response Body for Revoke OAuth2 Authorization Grant Request 

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#10082]
When we try to revoke authorization grants, access tokens will be revoked with 200 OK response states. But there is no response body. And also when we send an invalid parameters, there is no error response.

Request:
 **curl -X POST --basic -u "<client id>:<client secret>" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "token=<token to revoke>&token_type_hint=access_token" https://localhost:9443/oauth2/revoke -i**
 
Response: 
**HTTP/1.1 200 
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-store
Pragma: no-cache
RevokedAccessToken: 16127193-bfe1-30cb-9875-d82768634b2d
AuthorizedUser: admin@carbon.super
RevokedRefreshToken: ccc81505-ace6-3c6e-ac20-3c96a8e7c505
Date: Mon, 26 Oct 2020 10:27:56 GMT
Content-Type: text/html
Content-Length: 0
Server: WSO2 Carbon Server**

**Comment by pulasthi7** [comment]
As per the spec [1], it's expected to return 200 even for an invalid token. And the response body is ignored.

Hence closing the issue.

[1] https://tools.ietf.org/html/rfc7009#section-2.2
