### ISSUE TITLE
Performance tests with common features/connectors

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#10097]
At the moment, performance tests are conducted with default features and connectors enabled OOTB. However, there are some features and connectors enabled in most of the deployments, and by doing so performance numbers can vary. We need to identify such common features and connectors and run the performance tests with those features and connectors enabled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
