### ISSUE TITLE
No input validations while creating a new connector on Expert mode IDP

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#10099]
**Describe the issue:**
There are no input validations while creating OutBound Provisioning Connectors for an IDP created with Expert Mode in console. 

**How to reproduce:**
1. Access https://localhost:9443/console
2. Login as super admin
3. Navigate to Develop > Identity Providers > New Identity Providers > Expert mode (Under Manual Setup)
4. Create a new IDP with Expert Mode providing the mandatory attributes
5. Navigate to OutBound Provisioning > New Connector
6. Try to create a new connector with any type providing invalid input types

**Expected behavior:**
Input types as domain and email should be validated before creating the connector.

**Environment information :**
 - Product Version: 5.11.0 Beta3
 - OS: Ubuntu 18.04 LTS
 - Database: Maria DB 10.4
 - Userstore: JDBC

**Comment by thanujalk** [comment]
@JeethJJ what is the connector type?

**Comment by JeethJJ** [comment]
As, I've mentioned in **"How to reproduce > 6 "**, none of the connector types have validations.

**Comment by thanujalk** [comment]
@thivi these regex values need to return from the meta API. If not, let's create a separate issue for that.

Also, in the salesforce connector fix following,
<img width="329" alt="Screenshot 2020-10-28 at 14 09 49" src="https://user-images.githubusercontent.com/1498339/97412305-642cab00-1927-11eb-97dc-9770b2c82e80.png">

**Comment by thivi** [comment]
This PR implements the logic to validate the properties using the provided regex. https://github.com/wso2/identity-apps/pull/1282

The relevant backend issue to get the right regex from the backend is tracked here. https://github.com/wso2/product-is/issues/10150
