### ISSUE TITLE
[consoleApp] Adding a Openid Web application Certificate does not have a certificate upload option

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10095]
**Describe the issue:**
Current implementation supports to input the certificate only in the PEM format. It is better to have a certificate upload option as we had in the management console
**How to reproduce:**

1. Access https://localhost:9443/console
2. Login as super admin
3. Navigate to Develop > Applications > New Application > Web Application > OpenID Connect
4. Register the SP
5. Will get direct to the edit view of the application
6. Go to General tab
7. In the Certificates > provide certificate section

**Observation**

Current imlementation supports to input the certificate only in the PEM format. It is better to have a cerificate upload option as we had in the management console

**Expected behavior:**
The image should be loaded as the application image
Environment information

Mssql 2019
uniqueid jdbc
IS 5.11.0 beta3 
ubuntu 16.04
Chrome Version 85.0.4183.121

![console19](https://user-images.githubusercontent.com/31848014/97271756-fb75fd80-1856-11eb-9e9a-56896b81caad.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
