### ISSUE TITLE
Create automated performance test scripts for scim

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#10096]
At the moment authentication and SSO related performance test scripts are created and test results are published. However automated performance test scripts are not available for the below scenarios and need to be created.

- [ ] Create user
- [ ] Get user
- [ ] Modify claim
- [ ] Modify role

Additionally, all the other critical scenarios needs to be identified and scripts need to be created.

Effort BE::20

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
