### ISSUE TITLE
Summary page while creating a new IDP with Expert Mode

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#10100]
**Is your suggestion related to an experience ? Please describe.**
Usually, while creating a new IDP through console, it has a few stages and at the end it views a page of summary. While creating a new IDP with Expert mode, it doesn't have a summary page. This also could be due to minimum configurations. 

**Describe the improvement**
A summary page will improve consistency.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
