### ISSUE TITLE
[consoleApp]Updating Role Mapping via the Attributes tab for a OpenID web application does not update the mapping

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10109]
**Describe the issue:**
Updating Role Mapping via the Attributes tab for a OpenID web application fails

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > openid and add a openid application
4.In the edit view go for Attributes tab
5. Role Mapping section
6. Add local role as admin from the suggested drop down list and add a application role as test
7. Click Update

**Observation**
UI says as updated successfully. But the role mapping which was added is not available in the console 

Related https://github.com/wso2/product-is/issues/10073

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thanujalk** [comment]
@ShanikaWickramasinghe you need to click on the "+" at the end and then update... Can you please try that?

**Comment by ShanikaWickramasinghe** [comment]
@thanujalk Eventhogh clicked on the + icon getting the error attached in the image

![console25](https://user-images.githubusercontent.com/31848014/97407170-4d368a80-1920-11eb-883a-98afe4e180e8.png)

**Comment by thanujalk** [comment]
@ShanikaWickramasinghe yes.. saw the same issue when adding multiple.

**Comment by thivi** [comment]
This issue is caused by an API issue. The relevant API issue is tracked here. https://github.com/wso2/product-is/issues/10144

**Comment by piraveena** [comment]
Reopen this issue since it is a UI issue. Refer to this comment for the information https://github.com/wso2/product-is/issues/10144#issuecomment-721531170
