### ISSUE TITLE
[consoleApp] Redirect Urls and allowed orgin urls will accept a url eventhough the url does not have the correct format

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10102]
**Describe the issue:**
The current implementation will accept the urls and get it listed under the specific urls section as shown in below image and when click on update it says its a bad orgin. It would be better to validate the format when a user enter the url without displaying it as a correct url in the list.

**How to reproduce:**

1. Access https://localhost:9443/console
2. Login as super admin
3. Navigate to Develop > Applications > New Application > Web Application > OpenID Connect
4. Register the SP
5. Will get direct to the edit view of the application
6. Go to Access tab
7. Input values for redirect urls and allowed orgins fields with urls which are not according to the right format (http:test)

**Observation**

The current implementation will accept the allowed origin url and get it listed under the specific urls section as shown in below image and when click on update it says its a bad orgin. It would be better to validate the format when a user enter the url without displaying it as a correct url in the list.
Related to redirect url even though it doent has proper format it allows to save successfully as well.

**Environment information**

Mssql 2019
uniqueid jdbc
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console20](https://user-images.githubusercontent.com/31848014/97280666-958f7300-1862-11eb-9ddd-87cac039d338.png)

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-apps/pull/1308
