### ISSUE TITLE
[consoleApp] Unable to remove the last url under allowed origin and redirect url sections of a oidc web application

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10105]
**Describe the issue:**
Unable to remove the last url under allowed origin and redirect url sections of a oidc web application

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > oidc and add application
4. When the application is created navigate to the Access tab > oidc
5. Add multiple(4) urls for allowed orgins and redirect urls sections
6.Click update
7.Go back to access tab and try to remove the urls which is listed as the last(if theres 4 urls listed most down 1). only the 1st urls can be removed. cannot remove the last one

**Observation**
Try to remove the urls which is listed as the last(if theres 4 urls listed most down 1). only the 1st urls in the list can be removed. cannot remove the last one

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 
ubuntu 16.04
Chrome Version 85.0.4183.121

![console21](https://user-images.githubusercontent.com/31848014/97285263-01c0a580-1868-11eb-91bf-4d9df29020b2.png)

**Comment by thivi** [comment]
SImilar issue https://github.com/wso2/product-is/issues/10012
Fixed by https://github.com/wso2/identity-apps/pull/1271
