### ISSUE TITLE
No notification is being sent to user after resetting password

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#10114]
**Is your suggestion related to an experience ? Please describe.**
When the user successfully resets the password, no notification is being sent to the user. 

**Describe the improvement**
Please send an email notification when the password is successfully being reset

**Additional context**
Testing with 5.11.0 Beta 3

**Comment by ShanikaWickramasinghe** [comment]
Have you configured Email sending with your setup

**Comment by tsuresh** [comment]
@ShanikaWickramasinghe Yes, I'm successfully receiving the password reset link via email as well

**Comment by brionmario** [comment]
Seems like the `Notify when recovery success` checkbox in `Resident IDP -> Account Management -> Account Recovery` is not properly ticked.

<img width="1624" alt="Screen Shot 2020-10-29 at 1 13 04 PM" src="https://user-images.githubusercontent.com/25959096/97539845-aff35900-19e8-11eb-9882-3fd9b8e2e5c5.png">

@tsuresh Was this step documented in the docs? If not, we better do so.

**Comment by tsuresh** [comment]
@brionmario Yes. I'll open a new issue for that
