### ISSUE TITLE
Add login link and message to password reset screen

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#10113]
**Is your suggestion related to an experience ? Please describe.**
On clicking ‘OK’ button after adding correct and same data in both ‘New Password’ and ‘Confirm Password’ fields, a pop-up message for ‘Password successfully changed and now log in again’ doesn't appear. And the login link is missing too.

**Describe the improvement**
Please display the message and the 'log in again' link after resetting the password successfully 

**Additional context**
Testing with 5.11.0 Beta 3

**Comment by thivi** [comment]
Once the password is reset, the following modal is shown and the user is redirected to the login page on clicking the `Close` button.

Tested in 5.11.0-Beta5-SNAPHSOT

![image](https://user-images.githubusercontent.com/20745428/98171808-5b833880-1f16-11eb-83fa-2eb59fd490e5.png)

**Comment by tsuresh** [comment]
@thivi Can we rename the button to "Login again"?

**Comment by thivi** [comment]
I think it is better to just take the user directly to the login page and show a message saying that the process is successful.
![image](https://user-images.githubusercontent.com/20745428/98214627-bcd5f680-1f6c-11eb-8de8-6a0d38eaf168.png)
