### ISSUE TITLE
[consoleApp] Adding basic auth and oauth bearer as local authenticators fails for a openid web application

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10128]
**Describe the issue:**
Updating sign on method by adding another authenticator step as step and adding basic auth and oauth bearer as local authenticators for step 2 fails

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > openid and add a openid application
4.In the edit view go for sign on method tab
5. Click + New authenticator step
6. Drag and drop basic auth or oauth bearer local authenticator for step 2
7. Click Update

**Observation**
UI error is getting displayed and update is not successful

Related https://github.com/wso2/product-is/issues/10076

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thanujalk** [comment]
The problem here is having request path authenticators in this view... We can remove them from there as they have a different view at the end of that page.
