### ISSUE TITLE
Refactoring pagination logic in SCIM filtering and listing

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10123]
In a flow in SCIM user listing and filtering, pagination is done in the following manner [1] when an operation needs to be run across all available domains. The approach in [1] was implemented since there was no method to get the count matching for that operation.
The current operation seems to be costly and seems to have bugs. This needs to be improved. Ideally, there should be an API to get the count and the limits should be resolved according to that.

[1] - https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/a93995f6cac0ca06d7b40e02d8a99cbaa7763162/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L1363

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
