### ISSUE TITLE
SCIM filtering and listing based on the count parameter

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10122]
In the current implementation, we are using the legacy kernel API based on having `count` param in the user listing and user filtering requests. Example [1] is such an instance. Due to this, there are differences in the request when the count param is present in the request and when its not. Most of the time bugs can be seen when there is no count param in the SCIM request.

This behavior is added to maintain backward compatibility. It would be better if we can send a pre-defined count param.

[1] - https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L491

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
