### ISSUE TITLE
[consoleApp] Single Page Application Registration needs to have a proper validation for redirect url to deny incorrect urls

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10135]
**Describe the issue:**
As redirect url of a single page application is a mandatory field if a user just input the url and does not adhere to the correct url format still application registration gets succesful.

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Single Page Application
4.In the edit view
5. Input a application name
6. Input a Redirect URL which is not upto correct format (http:test)
7. Click on Register

**Observation**
Application registration gets succesful

**Expected Behaviour**
Requested url should need to have a proper validation 

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thanujalk** [comment]
Need to follow the format suggested in https://tools.ietf.org/html/rfc3986#section-4.3
(Note: As these are OAuth apps.. consider the native redirection URLs as well)
