### ISSUE TITLE
Only numeric names for IDP and Applications 

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#10134]
**Is your suggestion related to an experience ? Please describe.**
While creating a new IDP using Expert mode through console, it allows the IDP name to be totally numeric. 
While creating a new application through console, it allows the application name to be completely numeric.

**Describe the improvement**
Only numeric values for an IDP or Application name will not be convenient. A validation step would be better.

**Comment by pulasthi7** [comment]
There have been some cases where customers specifically wanted these to be numeric. Mostly for workarounds and as part of solutions for complex use cases. So, IMO, we should not enforce this unless we have some internal limitation (such as special characters)
