### ISSUE TITLE
[consoleApp] Updating a single page applications access details cannot be done without giving a value for the field allowed origins which is marked as not mandotory

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10137]
**Describe the issue:**
In a Single Page Application allowed origin field is not marked as a mandatory field but cannot update the applications access tab details without giving a value for allowed origins

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Single Page Application
4.In the edit view
5. Go to Access tab
6. Without updating anything click on Update

**Observation**
It will ask to input a value for allowed origins but this field is not marked as mandatory

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console24](https://user-images.githubusercontent.com/31848014/97404837-b9af8a80-191c-11eb-827d-656236157301.png)

**Comment by thivi** [comment]
Duplicate issue https://github.com/wso2/product-is/issues/10098
Fixed by https://github.com/wso2/identity-apps/pull/1282
