### ISSUE TITLE
[consoleApp] Single Page Application registration gets successful even though a user does not click on the add value icon of mandatory field requested url

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10133]
**Describe the issue:**
As redirect url of a single page application is a mandatory field if a user just input the url and does not click on + add value application registration should fail giving a proper error message.

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Single Page Application
4.In the edit view
5. Input a application name
6. Input a Redirect URL but dont click on the + icon(add value) to add that URL
7. Click on Register

**Observation**
Redirect url is a mandotory field. Even though we dont click on + icon to add value and click on register it will add the application successfully and will navigate for the edit view

**Expected Behaviour**
As redirect url is a mandatory field if a user just input the url and does not click on + add value application registration should fail giving a proper error message.

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console22](https://user-images.githubusercontent.com/31848014/97400639-769de900-1915-11eb-9231-a97aa1cac4be.png)

**Comment by brionmario** [comment]
@ShanikaWickramasinghe If the user doesn't click on the `+` button after entering the URL, the value in the input field will be automatically added to the request in the background. This was done to improve the UX for users with less familiarity with the portals. Hence closing the issue.
