### ISSUE TITLE
Console UI allows admin users to set admin permissions for roles

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#10138]
**Describe the issue:**
When using the Console as an admin user, it is possible to set admin permissions to new/existing roles. This should not be possible. The current implementation of the SCIM2 API only allows the super (super) admin to carry out such functionalities. 

**How to reproduce:**
1. Login as super admin
2. Create a user and give admin permissions (`internal/admin`) and `application/console` role.
3. Login to Console as the new user.
4. Create a role. In the role creation wizard, admin permission settings are offered.

<img src="https://user-images.githubusercontent.com/25567263/97412562-b8378f80-1927-11eb-8e27-0fd9bafbd7a0.png" width=600>

**Expected behavior:**
Admin permission settings should not be offered to console users other than the super admin.

**Environment information:**
 - Product Version: IS-5.11.0-beta4

**Comment by DimalChandrasiri** [comment]
The backend improvement is tracked with this issue https://github.com/wso2/product-is/issues/10702
