### ISSUE TITLE
Issue of returning the revoked refresh token in encrypted format when the access token is revoked

### ISSUE THREAD

**Issue by Dinushi** [wso2/product-is#10145]
**Describe the issue:**

This issue was observed when the EncryptionDecryptionPersistenceProcessor is configured as the TokenPersistenceProcessor.

When a token revocation request is sent to the **/oauth2/revoke** endpoint, the token details are retrieved from the database once a cache miss is found. In this case, when the **access token** is sent as the token-to-revoke (the token identifier is the access token), the response contains the revoked refresh token header in encrypted format.

**How to reproduce:**
1. Generate an access token
2. Wait untill the token cache expires
3. Call /oauth2/revoke by passing the access token as the token identifier.

**Expected behavior:**
The revokedRefreshToken response header should be be in the plain-text format.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 -  Product Version: [IS 5.7]
 -  OS: [Linux]
 -  Database: [ MySQL]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by janakamarasena** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1485
