### ISSUE TITLE
Nexmo SMS Gateway Setup for OTP is outdated in the doc

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#10147]
**Is your suggestion related to a missing or misleading document? Please describe.**
Nexmo SMS gateway has been rebranded as 'Vonage' now. And the steps which need to be followed are outdated in the documentation. 

https://is.docs.wso2.com/en/5.11.0/learn/configuring-sms-otp/

**Describe the improvement**
Please update the doc with the latest steps that need to be followed to set up the Nexmo SMS Gateway

**Comment by ShanikaWickramasinghe** [comment]
Can we move this issue to https://github.com/wso2/docs-is/issues

**Comment by tsuresh** [comment]
@ShanikaWickramasinghe Unable to open the issue in the above repository; it redirects to the product-is repo
