### ISSUE TITLE
No input validations for Redirect URLs while creating new application 

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#10141]
**Is your suggestion related to an experience ? Please describe.**
While creating a new application using the console, there is a validation when adding a redirect URL. If we add a invalid URL it views a message saying, 
_"The entered URL neither HTTP nor HTTPS. Please proceed with caution."_
But still it approves the invalid URL as a Redirect URL. Even though, there are no valid redirect URLs, the application can be created. 

**Describe the improvement**
Invalid URLs should not be allowed. Since the redirect URL is a mandatory field, without a valid URL, the application should not be allowed to be created.

**Comment by ShanikaWickramasinghe** [comment]
related https://github.com/wso2/product-is/issues/10135

**Comment by JeethJJ** [comment]
Still experiencing the same behavior in Beta 5 Snapshot. It views a error message, but still allows to create the application.

![Screenshot from 2020-11-04 11-03-04](https://user-images.githubusercontent.com/50905371/98073003-59c16280-1e8d-11eb-81e1-e7bd8f1d0392.png)

This error message is being viewed for all vendor integrations apps and Single page applications in General applications.

For other general applications (Web, Desktop, Mobile), it allows to create without the error message.
