### ISSUE TITLE
Improve authentication portal extensions

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10140]
**Is your suggestion related to an experience ? Please describe.**
The authentication portal allows header, footer, etc. to be extended by placing customized files in the extensions directory,. The portal app checks for the presence of the extension directory during every page load. This can be an expensive process and leads to unnecessary input/output operations per second. 

**Describe the improvement**
Create a class to extend the app and cache the results for a few minutes. This way too many I/O operations can be avoided,

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
