### ISSUE TITLE
hard coded alias value in identity provider > Advanced Tab

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10142]
**Describe the issue:**
There is a hardcoded alias value in identity provider > Advanced Tab in OpenID connect Identity Provider
the value: "https://localhost:9444/oauth2/token"
when startup server with any offset

**How to reproduce:**
Login to console > Develop
Create Identity Server
Create new OpenID connect IDP
provide necessary inputs
Validate created IDP Advanced tab

**Environment information** 
 - Product Version:5.11 Beta3
 - OS: [e.g., Windows, Mac
 - Database: Oracle, DB2, H2
 - Userstore: LDAP, JDBC

---

![image](https://user-images.githubusercontent.com/39120228/97418324-b3c2a500-192e-11eb-9b47-fbaa8d2159c8.png)

**Comment by NilukaSripalim** [comment]
This value display in the Management console :
![image](https://user-images.githubusercontent.com/39120228/97485485-345dc180-1980-11eb-9599-f61acdce4cf8.png)

**Comment by brionmario** [comment]
This seems like an issue with the backend. When the port offset is set to `2`, following is the response from https://localhost:9445/api/server/v1/identity-providers/90cf8f9c-62ef-409a-a419-53fc2f717c05

```json
{
...
"alias":"https://localhost:9444/oauth2/token",
...
}
```

**Comment by thanujalk** [comment]
This is not related to the port offset of the Identity Server. But we can improve the UI.

**Comment by GoushiRam** [comment]
This is available in the current console as well for social connections:

<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/c97575d9-52e7-4031-9ebc-c2520deb9b2b">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
