### ISSUE TITLE
The outbound provisioning connector's properties' regex attribute should be properly configured

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10150]
**Is your feature request related to a problem? Please describe.**
Since the connector properties are dynamically obtained from the API, we need the properties' regex attribute to provide the regex to validate the properties.

However, the regex attribute of all the properties has the `.*` pattern which would allow any value. To validate these properties, the right regex pattern should be returned from the backend.

Concerned endpoint: `api/server/v1/identity-providers/meta/outbound-provisioning-connectors/{id}`

Sample response:
![image](https://user-images.githubusercontent.com/20745428/97448208-69551e80-1956-11eb-99d9-cb65cbcfb44e.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
