### ISSUE TITLE
Improve deep equality checks in useEffect hook dependencies

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10157]
**Is your suggestion related to an experience ? Please describe.**
The `useEffect` hook doesn't perform a deep equality check. Right now, we are either JSON stringifying the objects or converting the arrays to string to turn the comparison into a shallow one. A better way needs to be found to resolve this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
