### ISSUE TITLE
[consoleApp] [Manage] Secondary userstore Enable Default auto commit and Default Read Only through console manage doesnt work

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10168]
Describe the issue:
Secondary userstore Enable Default auto commit and Default Read Only through console manage doesnt work

How to reproduce:

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Manage > Userstores > New Userstore > JDBC
4. Add a maria db Userstore as a secondary userstore by giving the necessary details
4.Save
5. Go to added userstore edit view > Enable Userstore
6. Update
7. User store > Connection tab
8. Enable Default auto commit and Default Read Only through console manage
9. Update

Observation
UI says it updated successfully. Go back for another tab and come back and see the connection tab. Enabled 2 configs shows as disabled

Environment information
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thivi** [comment]
The right request is being sent by the frontend app but the backend isn't properly updating the values.
![image](https://user-images.githubusercontent.com/20745428/97915300-46bc6e80-1d77-11eb-95dd-7a7fe3620fa0.png)

**Comment by janakamarasena** [comment]
Does the update happen after sometime? can be related to https://github.com/wso2/product-is/issues/8231
