### ISSUE TITLE
[consoleApp] [Manage] Enabling a jdbc secondary user store via Console Manage doesn't work

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10163]
**Describe the issue:**
Enabling a jdbc secondary user store via Console Manage doesn't work

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Manage > Userstores > New Userstore > JDBC
4. Add a maria db Userstore as a secondary userstore by giving the necessary details
4.Save
5. Go to added userstore edit view > Enable Userstore
6. Update

**Observation**
UI says update is succesful. Login to the management console and check the status of the userstore. It will show as disabled. Also in the console if we log back and see enable option is not updated it shows as disabled

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3
ubuntu 16.04
Chrome Version 85.0.4183.121

![console26](https://user-images.githubusercontent.com/31848014/97528580-191ca180-19d4-11eb-9d45-d03dc6330209.png)
![console27](https://user-images.githubusercontent.com/31848014/97529121-3d2cb280-19d5-11eb-8248-316f6d8d4c6b.png)

**Comment by ShanikaWickramasinghe** [comment]
Related https://github.com/wso2/product-is/issues/10316

**Comment by thivi** [comment]
Related issue: https://github.com/wso2/product-is/issues/9879
This was resolved by https://github.com/wso2/identity-apps/pull/1250
