### ISSUE TITLE
Configuring OAuth/OpenID Connect via SOAP API does not save the grantTypes

### ISSUE THREAD

**Issue by MihStVita** [wso2/product-is#1016]
The SOAPAction "registerOAuthApplicationData" against the OAuthAdminService does not save the grantTypes.

Steps to Reproduce:
```
# Download
wget https://github.com/wso2/product-is/releases/download/v5.3.0-rc3/wso2is-5.3.0-rc3.zip
# Unzip
unzip wso2is-5.3.0-rc3.zip
cd wso2is-5.3.0
# Start
bin/wso2server.sh 
# Switch Console---
# Register the OAuthApplication
curl -k -X POST -H "Content-Type: text/xml" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "SOAPAction: registerOAuthApplicationData" --data "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://org.apache.axis2/xsd\" xmlns:xsd1=\"http://dto.oauth.identity.carbon.wso2.org/xsd\"><soapenv:Header/><soapenv:Body><xsd:registerOAuthApplicationData><xsd:application><xsd1:OAuthVersion>Oauth-2.0</xsd1:OAuthVersion><xsd1:applicationName>TestApp</xsd1:applicationName><xsd1:callbackUrl>http://localhost:8080/essTournamentSystem/auth</xsd1:callbackUrl><xsd1:grantTypes>refresh_token urn:ietf:params:oauth:grant-type:saml2-bearer implicit password iwa:ntlm client_credentials authorization_code </xsd1:grantTypes></xsd:application></xsd:registerOAuthApplicationData></soapenv:Body></soapenv:Envelope>" https://localhost:9443/services/OAuthAdminService
# Get the OAuthApplication
curl -k -X POST -H "Content-Type: text/xml" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "SOAPAction: getOAuthApplicationDataByAppName" --data "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://org.apache.axis2/xsd\"><soapenv:Header/><soapenv:Body><xsd:getOAuthApplicationDataByAppName><xsd:appName>TestApp</xsd:appName></xsd:getOAuthApplicationDataByAppName></soapenv:Body></soapenv:Envelope>" https://localhost:9443/services/OAuthAdminService > getOAuthApplicationDataByAppNameResponse.xml
# View the Rsponse:
vi getOAuthApplicationDataByAppNameResponse.xml

```

See Documentation: https://docs.wso2.com/display/IS530/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by Orfen-0** [comment]
I can confirm i have the same issue. Also, after registering the oauth application data, editing the oauth/openid configuration from the identity server management portal doesn't display the usual options.

**Comment by Pushpalanka** [comment]
The provided screen-cast is not accessible. I could check the functionality using a 5.3.0 GA pack and it worked fine. If you are creating the OAuth service provider via SOAP services, in order to have it properly populated in UI, there are few steps to follow as described at [1]. Just calling the 'registerOAuthApplicationData' method in OAuthAdminService does not populate all the details required by the UI.

[1] - [http://blog.lasindu.com/2014/12/wso2-identity-server-provision-service.html](http://blog.lasindu.com/2014/12/wso2-identity-server-provision-service.html)

**Comment by Orfen-0** [comment]
@Pushpalanka Thank you for your answer. I haven't described fully the flow that i am following, but it should be correct. In either case, the grant types are not saved anywhere. 

I have been following the following flow: 

1)Create Service Provider via the ApplicationManagementService createApplication method.

2)Create the OAuth application via the OauthAdminService

3)Update the Service Provider configuration via the updateApplication method of the ApplicationManagementService with the newly created Oauth application

This results in what i described in my previous comment. By using the SOAP service i can get all the relevant information correctly(except grant types which do not persist) but trying to access the OAuth2/OpenIDConnect configuration via the UI results in what appears on the screenshot.

**Comment by dewniMW** [comment]
I've tested the aforementioned scenario on wso2is 5.8.0 pack and I was able to view the grant types via the UI. Please refer [1] to check if you have missed any steps.

[1] https://medium.com/@dewni.matheesha/admin-services-for-service-provider-configurations-in-wso2-identity-server-7530f04d974e
