### ISSUE TITLE
Integrate HashiCorp secure vault

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#10170]
**Is your suggestion related to an experience ? Please describe.**

HashiCorp Vault is a secrets management tool and it can be used to encrypt and store the secrets such as passwords, access tokens, encryption keys. Currently, the Secure Vault which is providing with the Identity Server stores the encrypted passwords/secrets in a file. If we can integrate the HashiCorp Vault as an external vault, the Identity Server will be able to fetch the secrets/passwords which are stored in a HashiCorp Vault.

**Describe the improvement**

* We can customize the existing secure vault to connect to HashiCorp Vault. For that, we can create a new Custom Secret Repository and a Secret Repository Provider to fetch the data from the HashiCorp Vault when needed.
* We can implement this as a connector that integrates HashiCorp Vault with WSO2 Identity Server.

**References**

[Customizing Secure Vault](https://is.docs.wso2.com/en/latest/setup/customizing-secure-vault/)
[HashiCorp Vault homepage](https://www.vaultproject.io/
)

**Comment by pulasthi7** [comment]
@sumedhe Can you please link the relevant PRs and docs here and close this?
