### ISSUE TITLE
Unexpected behaviour in User-Store Management REST API, test connection endpoint for H2 databases

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#10176]
**Describe the issue:**
When the test connection endpoint is invoked for **non-existing H2 databases**, it was observed that when the **"username": "wso2automation"** and **"connectionPassword": "wso2automation"** combination is used the response returned is always true.

**How to reproduce:**

Sample request:
```
curl --location --request POST 'https://localhost:9443/t/carbon.super/api/server/v1/userstores/test-connection' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer bea59347-ac43-331d-8d57-c438f1f25a61' \
--header 'Cookie: opbs=32e5034a-0efc-471c-987c-6f7c1d662095; commonAuthId=58cc2302-614c-4f5e-a574-02844441dd2b' \
--data-raw '{
  "driverName": "org.h2.Driver",
  "connectionURL": "jdbc:h2:./repository/database/non-existing",
  "username": "wso2automation",
  "connectionPassword": "wso2automation"
}'
```
Response: **200 OK**
```
{
    "connection": true
}
```
**Expected behavior:**
Connection status must be false

### Optional Fields

**Related issues:**
Moved from https://github.com/wso2/product-is/issues/9561

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
