### ISSUE TITLE
[5.8.0] [Analytics] Generated SQL queries are not working properly with Oracle DB

### ISSUE THREAD

**Issue by darsham3** [wso2/product-is#10188]
**Describe the issue:**

While testing IS Analytics 5.8.0 with Oracle DB, we found that the following statistics are not populated:

1. Over All Login Attempts (widget: IsAnalyticsSummary)
2. Login Attempts Over Time (widget: IsAnalyticsAttemptsOverTime)
 
The Siddhi query used to over all login stats is:
```
from AuthStatAgg within {{from}}L, {{to}}L per \"{{per}}s\" select sum(authFailureCount) as authFailureCount, sum(authSuccessCount) as authSuccessCount"
```
The query generated to retrieve the overall login attempt is given below:
```
SELECT * FROM AuthStatAgg_MONTHS WHERE (((1595947364190 <= AuthStatAgg_MONTHS.AGG_EVENT_TIMESTAMP
)AND (AuthStatAgg_MONTHS.AGG_EVENT_TIMESTAMP < 1603896164191 ))AND 1 
```

It has an expression -  AND 1 in where clause which is not supported by Oracle. I have tested it with Oracle 19c, 12c and 11g.

**But these scenarios are working fine with a fresh Identity Analytics 5.8.0 pack,  where generated SQL queries does not have expression AND 1 in where clause**
 

**Environment information** 
 - Product Version: Identity Analytics 5.8.0
- WUM: 1602171727351
 - Database: Oracle

**Comment by inthirakumaaran** [comment]
This issue is already addressed in the master branch[1]. PR[2] related to IS 5.8.0

[1]https://github.com/wso2/product-sp/issues/1021
[2]https://github.com/wso2-support/siddhi/pull/74
