### ISSUE TITLE
Increase the default expected length for the columns in the registry database

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10197]
If the length of the values storing when creating the tenant is being longer than the default expected length for the columns in the registry database; It will throw an error specific to the DB vendor. 
For MSSQL
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to add properties to the resource /_system/governance/repository/security/key-stores/wso2-com.jks. String or binary data would be truncated.

To mitigate we have to increase the default expected length for the columns in the registry database.

```
ALTER TABLE REG_LOG alter column REG_USER_ID VARCHAR(100);
ALTER TABLE REG_RESOURCE alter column REG_CREATOR VARCHAR(100);
ALTER TABLE REG_RESOURCE alter column REG_LAST_UPDATOR VARCHAR(100);
ALTER TABLE REG_RESOURCE_HISTORY alter column REG_CREATOR VARCHAR(100); 
ALTER TABLE REG_RESOURCE_HISTORY alter column REG_LAST_UPDATOR VARCHAR(100);
ALTER TABLE REG_COMMENT alter column REG_USER_ID VARCHAR(100);
ALTER TABLE REG_RATING alter column REG_USER_ID VARCHAR(100);
ALTER TABLE REG_TAG alter column REG_USER_ID VARCHAR(100);
ALTER TABLE REG_PROPERTY alter column REG_VALUE VARCHAR(2000);
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
