### ISSUE TITLE
Rule based outbound SCIM provisioning not working in WSO2IS-KM 5.3.0

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#10199]
1. Download the latest wum version of wso2is-km-5.3.0
2. Configure a new Identity provider 'scim-test', configure the scim towards a dummy API 
3. Configure the resident SP outbound provisioning to provision towards this identity provider
4. Enable Rules
5. configure a new policy with the result "Permit" for every one
6. dd a new user with username "test"
7. Debug the code evaluateXACMLResponse method in XACMLBasedRuleHandler
8. observe XACML result can't be extracted as "Permit"

If we remove the  "Saxon-HE-9.4.jar" library which is used in /lib/endorsed directory, the issue won't occur (so can't see this issue in IS pack &  only IS-KM version)
This is fixed in the master branch as we are not using the XPATH.  We can backport that fix easily.

**Comment by ShanChathusanda93** [comment]
* Public fix : https://github.com/wso2/carbon-identity-framework/pull/1229
* Related other fixes : https://github.com/wso2/carbon-identity-framework/pull/923
