### ISSUE TITLE
Unable to list Roles via console with Oracle19c

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10194]
**Describe the issue:**
Role list will be empty with Oracle19c, in Console > Manage > Roles

**How to reproduce:**
1. Configure Oracle as Primary user store 
2. Login to console with superuser credentials
3. View roles (Manage)

**Expected behavior:**
Added roles should be display properly
**Environment information** 
 - Product Version: 5.11 Beta 3
 - OS: Windows
 - Database:  Oracle 19c
 - Userstore: JDBC

---

![image](https://user-images.githubusercontent.com/39120228/97624915-c8e22580-1a4d-11eb-855e-ad31d858df04.png)

![image](https://user-images.githubusercontent.com/39120228/97625177-2fffda00-1a4e-11eb-9664-0a8bc91ad6a3.png)

**Comment by thanujalk** [comment]
@NilukaSripalim were you able to get the group list?

Also, are you using Oracle for the identity_db as well?
