### ISSUE TITLE
Developer Portal Outbound Provisioning SCIM Connector configuration template does not get loaded

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10207]
**Environment**
5.11.0 M26 pack

**Steps to Reproduce**
1. Create a tenant
2. Login to developer portal as the tenant created in step 2 
https://localhost:9443/t/iam.com/developer-portal

3. Navigate to Identity Provider component
4. Add Facebook as a IDP
5. Navigate to created IDPs Outbound Provisioning Wizard
6. From New Connector option Add Google as a New connector
7. After adding Google as a connector when its available in the system now try to add SCIM as another new Connector

**Observation**
When one connector is added (Google) and trying to add another (SCIM). It wont be loading the SCIM connectors configuration wizard. Will give a blank page as below

![ux2](https://user-images.githubusercontent.com/31848014/86735953-ca2bb480-c050-11ea-904e-c81e2b9b43ab.png)

**Comment by thanujalk** [comment]
This is fixed now.
