### ISSUE TITLE
SLO has stopped working in Console & My Account

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10203]
**Describe the issue:**
OpenID Connect session management implementation in Console & MyAccount has stopped working.
And due to recent improvements, it's impossible to debug the session management logic.(Webpack is used to bunddle the script)

**How to reproduce:**
1. Login to Console (https://localhost:9443/console)
2. Login to MyAccount (https://localhost:9443/myaccount)
3. Logout from Console.
5. Observe that MyAccount hasn't been automatically logged out and it's giving errors when navigation to pages due to inactive session.

**Expected behavior:**
1. Session should be synced across apps.
2. Session management scripts should be copied to the distribution for easy debugging purposes.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-beta-4-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by brionmario** [comment]
Seems to be working with `IS 5.11.0-beta-4` release pack. Need to validate.

**Comment by jeradrutnam** [comment]
Can be reproduce on incognito window. Tried on chrome. 

Normal window it works fine. with IS 5.11.0-beta-4

**Comment by brionmario** [comment]
With IS `5.11.0-beta-5`, SLO works on chrome normal mode and not in incognito. SLO doesn't work at all on Safari & Firefox. Due to Safari security restrictions, having issues there is understandable but need to investigate the reasons for not working on Firefox & Chrome incognito.

Recent changes done to bundle the iframe logic using webpack could be a culprit.

**Comment by jeradrutnam** [comment]
Tested with 5.11.0-beta-5. Still this can reproducible in chrome as above.
