### ISSUE TITLE
Getting 404 Error when try to add New Protocol for added Application

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10208]
Add a new "Passive STS web application" and provide the necessary information.
2. Try to edit the application 
3. Move to Access Tab, click Add new Protocol
4. Select WS TRUST from Manual Setup list
5. click next and see an error

**Comment by NipuniBhagya** [comment]
This issue is not reproduced in the 5.11.0-beta4 pack as we have removed the Passive STS web application template. But adding the WS TRUST protocol in the edit section works without issues. Therefore closing this issue @NilukaSripalim.
