### ISSUE TITLE
Suggestions for data sync tool

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10204]
**Describe the improvement**

The following are some suggestions for the data sync tool which is used for zero downtime migrations [1].

1. Implement a standalone and not dependent on the WSO2 IS to startup. This is probably simple for an experienced person on WSO2 stack to do but for a DBA who supports multiple applications, it is asking for a lot. 

2. Present benchmarks on what it can support. For example, how many updates an hour running under what configuration. 

3. Consider rollback. If an upgrade from 5.8 to 5.10 causes reissuing of existing tokens on cutover then it will be difficult to roll back to the previous stack as you have just recreated most of your tokens and the valid ones are on the new stack. 

[1] https://is.docs.wso2.com/en/5.11.0/setup/migrating-preparing-for-migration/#zero-down-time-migration

**Comment by ruwanta** [comment]
1. Usually any software migration do not offer rollback. 
The correct strategy is that do some dry run on a copy of a live data, test everything works ok, do rehearsal for several times. Then only do the live migration. 
There can be rare case where still the system has to be rolled back. Then the new tokens has to be handled case by case. Usually it will be no problem for the user to as re-login, as there will be very few users who has re-issued tokens at the time of migration.

**Comment by ruwanta** [comment]
2. Standalone approach is a good suggestion.
This is something on the discussion stage, where we have a separate command line option to do DB schema change. and the real data migrator.

However Blue-Green migration itself means there are two clusters accepting traffic at the same time. The green cluster accepts all new traffic and Blue cluster accepts some limited Read-only traffic like token validations and any reporting. Hence the two clusters will be normal servers.

**Comment by ruwanta** [comment]
3. Provide a benchmark is out of the product migrator as it is highly dependent on the current data and system resources the system has.
It needs to be reiterated that any migration has to be rehearsed with recent copy of live data. This is the time where the respective benchmark can be obtained on the system based. Any benchmark obtained on one setup is only valid for that setup. Also it is worth noting that even this is valid for the same setup only for limited timeframe.  For example, the benchmark done last years migration on the one installation is not valid a year later as the dataset would have been changed, grown , and new services are onboarded.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
