### ISSUE TITLE
Cannot delete a Outbound Provisioning Connector added for Facebook IDP

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10206]
Environment
5.11.0 M26 pack

**Steps to Reproduce**

1. Create a tenant

2. Login to developer portal as the tenant created in step 2
https://localhost:9443/t/iam.com/developer-portal

3. Navigate to Identity Provider component

4. Add Facebook as a IDP

5. Navigate to created IDPs Outbound Provisioning Wizard

6. From New Connector option Add Google as a New connector

7. After adding Google as a connector try to delete the added connector

**Observation**
Cannot delete the added connector and delete operation fails

**Comment by thanujalk** [comment]
The issue can be reproduced in the 5.11.0-beta4 pack. This is needed to fix at the API level. Failed with error `{"code":"UE-10000","message":"Invalid Request","description":"Property defaultConnectorId cannot be null.","traceId":"c23e9b6e-fbe7-4281-8225-f59ba6329a01"}`

**Comment by ayshsandu** [comment]
This issue happens whenever the default authenticator is trying to be deleted from the authenticator list of the IDP. Isn't it expected to prevent deleting the default authenticator. 
IMO, we should disable the delete button from the default authenticator or should give a warning to the user asking to change the default authenticator before deleting proceeding.

**Comment by ayshsandu** [comment]
Created https://github.com/wso2/product-is/issues/10586 to track UI improvement to remove delete and disable options for the default authenticator.
