### ISSUE TITLE
Generate password button issue

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#10210]
**Describe the Issue:**
Admin portal user creations password generate button doesn't work properly.  

**How To Reproduce:**
Step 01. Login to admin portal
Step 02. Navigate to user page 
Step 03. Click add new user button
Step 04. Fill user profile details except include password fields
Step 05. Clear password fields only (both new password and confirm password fields)
Step 06. Click password generate button

**Expected behavior:**
Password fields should update with the generated new password

**Actual behavior:**
Password  fields not update and remain empty 

**Device Information** (_Please complete the following information_) **:**

 - OS: [e.g. Windows, Android, iOS]
 - Browser + Version  chrome, Firefox

**Comment by thanujalk** [comment]
This is fixed now.
