### ISSUE TITLE
Unable to create new application via DEV - Portal.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10213]
I tried to create a new application through the DEV portal but could not finish any application type. (with the latest implementation)

Step to reproduce:
Login to developer portal:
2. Application > Add new Application
3. Select any application Type 
4. In Wizard, provide mandatory information,
5. Click on Finish, in the Summary section.
*** Status code -500

![image](https://user-images.githubusercontent.com/39120228/85252440-62367500-b479-11ea-9a9b-24359d86d360.png)

**Comment by NipuniBhagya** [comment]
This issue is not reproduced in the 5.11.0-beta4 pack. Therefore closing this issue. @NilukaSripalim Please reopen this if you are able to reproduce this in the latest pack.
