### ISSUE TITLE
"&quot" are included in the developer portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10215]
Steps :
1. Log in to the developer -portal
2. Access Applications > New Application
3. Select SAML web application, & create SAML web application with required fields.
4. Edit SAML web application, 
5. Navigate to Access Tab Expand SAML protocol,

![image](https://user-images.githubusercontent.com/39120228/84931685-c3182300-b0f0-11ea-853a-aa57a490f98d.png)

**Comment by NipuniBhagya** [comment]
This issue is not reproduced in the 5.11.0-beta4 pack. Therefore closing this issue. @NilukaSripalim Please reopen this if you are able to reproduce this in the latest pack.
