### ISSUE TITLE
Cannot edit email templates with the admin portal

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10211]
**Describe the Issue:**
When trying to edit an email template, the cursor automatically moves to the end of the template after a few letters are typed in.

![image](https://user-images.githubusercontent.com/5237653/85424781-f8f85400-b595-11ea-8a31-6e10e33a0011.png)

**How To Reproduce:**
- Edit an email template from admin portal

**Comment by thanujalk** [comment]
The issue is available in 5.11.0-beta4 pack
