### ISSUE TITLE
Observing an empty page when trying to add a certificate [Developer-portal]

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10216]
With the latest implementation;
Step to reproduce: 
Login to developer portal:
2. Identity Providers > Add new Identity Provider
3. Select any Identity Provider Type (EX: Google)
4.In Wizard, General settings > Certificates 
5.select provide certificate > Add a certificate ,

![image](https://user-images.githubusercontent.com/39120228/84930500-040f3800-b0ef-11ea-9f56-b3b837b720c4.png)

**Comment by thanujalk** [comment]
This is resolved now.
