### ISSUE TITLE
After adding a IDP certificate when coming back to the edit screen it shows jwks

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10219]
**Describe the Issue:**
In an Identity Provider after configuring a certificate (this gets successfully added) go back to the overview page and come back again to that Identity Provider and go to the "Advanced" tab. It will show "Use JWKS Endpoint" as selected.

This appears to be a UI bug as the API send the certificate in the response.

**Comment by thivi** [comment]
This cannot be reproduced in 5.11.0-Beta3-SNAPSHOT
