### ISSUE TITLE
Getting an empty page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10218]
latest product-is

Followed below steps:
1. Login to Developer portal with proper tenant admin user credentials
2. Click on user-avatar icon
3. Click 'My Account'
4. Then it will navigate to User portal with new Tab 
5.  Click on user-avatar icon in user portal 
6. Click on Personal Info , 
7. Do some update (it is not manadatory)
8. Logout from user portal,
9. within the same tab try login to the developer portal

Getting empty page
![image](https://user-images.githubusercontent.com/39120228/83747033-a5bd7080-a67d-11ea-8681-e76674e4a408.png)

**Comment by NipuniBhagya** [comment]
This issue is not reproduced in the 5.11.0-beta4 pack. Therefore closing this issue. @NilukaSripalim Please reopen this if you are able to reproduce this in the latest pack.
