### ISSUE TITLE
CallBack-URL must be defined as mandatory-(UI-DEV-Portal-Applications)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10212]
While creating, New OIDC Web application,
In application creation wizard can not complete application creation without providing Call back URL.
But the input field does not define as mandatory.
Step to reproduced: 
1. Login to Dev - portal
2. Select application > new application 
3. select OIDC Web Application
4. Provide necessary General inputs in the Application Creation wizard
5. Click on  "Next"
6. Click on Next in "Protocol Configuration" without providing Callback url

![image](https://user-images.githubusercontent.com/39120228/85408079-b036a000-b581-11ea-9015-74aa16747fd6.png)

**Comment by thanujalk** [comment]
This issue is fixed now.
