### ISSUE TITLE
Manage consents widget displays application's description instead of application name

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10225]
**Describe the Issue:**
During login, if the application requests for consent, then a user gives consent and that will be shown under the "Manage consents" section

![image](https://user-images.githubusercontent.com/5237653/82730927-1a5cea80-9d21-11ea-91ee-775d432d3aed.png)

However, the consent receipt shown contains the application's description as the display value. This is not UX friendly.

Now that we support UI friendly display names for applications, during consent recipient creation we should add the application's name instead of it's description.

A sample response from consents API

```
[
    {
        "consentReceiptID": "f99b2f84-8fa1-4ca5-b163-ecaf2855a72b",
        "language": "us_EN",
        "piiPrincipalId": "admin",
        "tenantDomain": "carbon.super",
        "state": "REVOKED",
        "spDisplayName": "This is the developer portal application.",
        "spDescription": "This is the developer portal application."
    },
    {
        "consentReceiptID": "11ce21e1-5bfd-4258-a0f0-174d99507d94",
        "language": "us_EN",
        "piiPrincipalId": "admin",
        "tenantDomain": "carbon.super",
        "state": "ACTIVE",
        "spDisplayName": "This is the developer portal application.",
        "spDescription": "This is the developer portal application."
    }
]
```

As we can see the 'spDisplayName' is the application's description :)

**How To Reproduce:**
- Create an application
- Add a description to the application
- Enabled consent
- Login to the application and approve consent

- Login to the user portal and view the consents

**Expected behavior:**
- Consent list should show the application name.

**Comment by thanujalk** [comment]
This is resolved now.
