### ISSUE TITLE
Typo in "Advance" configuration section of an application 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10228]
![sp-typo-advanced](https://user-images.githubusercontent.com/5061791/82456160-7b8e7f00-9ad1-11ea-8a4e-8b2b60a07ea2.png)

1.  Typo as highlighted in above
2. Can we improve the descriptions in this view?  For example, `User consent will be skipped during login flows.` can be `Once enabled, page prompt for obtaining user consent will be skipped for this application during the authentication flow.`
 Just a sample, but I feel most of these fields can be improved.

**Comment by thanujalk** [comment]
This issue is there in the 5.11.0-beta4.
