### ISSUE TITLE
OIDC front channel logout URL configuration is inconsistent with the management console

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#10223]
**Describe the Issue:**

<img width="663" alt="Screen Shot 2020-05-25 at 12 41 19 PM" src="https://user-images.githubusercontent.com/1498339/82796954-fcfc5d80-9e93-11ea-81f5-5eb5c524d0c4.png">

We configuration element for front-channel logout URL in the developer portal for OIDC applications. If we configure only that value (without having a value for backchannel logout URL) it will be displayed as front-channel logout URL in the management console. Also if we configure both from the developer portal it will only show the backchannel logout URL in the management console.

**How To Reproduce:**
Create an OIDC application from the developer portal and OIDC configuration under Access.

**Expected behavior:**
Verify the front channel feature availability and fix the UI. Also, it is enough to provide only one configuration.

**Comment by piraveena** [comment]
This feature needs few improvements https://github.com/wso2/product-is/issues/9118

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
