### ISSUE TITLE
Unable to directly access dev portal with reduced permissions

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10229]
**Describe the Issue:**
A User with less, but required permissions to access some of the permissions required to login to dev-portal is unable to login.

**How To Reproduce:**

1. Create a new user "userA"
2. Create a new role "testRole"
3. Assign `login` and `user management` permissions to the "testRole"
4. Assign "testRole" to  "userA"
5. User is unable to access the portal and endup in, 404, `Page Not Found`
6. This maybe because, app is tying to direct the user to /applications page, where user doesm't have access.
7. If I manually enter 'https://<host>/t/coffee.com/developer-portal/users' then able to view this page.

**Expected behaviour:**
user need to be directed to a page which is available for him.

**Device Information** (_Please complete the following information_) **:**
- chrome 

---

**Comment by thanujalk** [comment]
Can be reproduced with 5.11.0-beta4 as well.
