### ISSUE TITLE
Unable to edit "Request validation certificate alias" -DEVELOPER_PORTAL

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10226]
Version: wso2is-5.11.0-m19

**Describe the Issue:**
Try to create new SAML web application with required fields,
and while trying to edit "Request validation certificate alias" field in created application, this field is unable to edit

**How To Reproduce:**
Navigate to https://localhost:9443/t/tenant-domain/developer-portal/
Create new SAML Web Application
Try to edit created application (ACCESS TAB)

![image](https://user-images.githubusercontent.com/39120228/82686994-52f2ba80-9c74-11ea-81d7-d8c40c4ac874.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
