### ISSUE TITLE
Attribute name is shown instead of URI when adding a mapped local attribute

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10224]
**Describe the Issue:**
In a custom attribute dialect when adding or editing a mapped local attribute, the local attribute name is displayed instead of the attribute URI.

<img width="1101" alt="Screen Shot 2020-05-25 at 12 32 52 PM" src="https://user-images.githubusercontent.com/11583571/82787519-37f69500-9e84-11ea-9b39-0ea3383513e0.png">

<img width="1633" alt="Screen Shot 2020-05-25 at 12 29 53 PM" src="https://user-images.githubusercontent.com/11583571/82787540-3f1da300-9e84-11ea-8c0d-55743fc9dbee.png">

**Expected behavior:**
Ideally, both attribute name and URI should be shown.

**IS Version**
5.11.0 M20

**Comment by thanujalk** [comment]
This is resolved now.
