### ISSUE TITLE
Incorrect application count in dev-portal Overview screen

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10222]
**Describe the Issue:**
In the developer-portal overview screen, the application count is displayed incorrectly. It is always the available applications + 1

IS Version: 5.11.0 M20

<img width="1203" alt="Screen Shot 2020-05-25 at 3 20 54 PM" src="https://user-images.githubusercontent.com/11583571/82802104-fa056b00-9e9b-11ea-8dca-f29304e39ee6.png">

**Comment by NipuniBhagya** [comment]
This issue is not reproduced in the latest pack as we have removed the above-mentioned overview page and therefore closing this issue.
