### ISSUE TITLE
Service Provider Claim Dialect is missing in the latest dev portal

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#10220]
When using the SAML eIDAS Feature it is needed to use 'Service Provider Claim Dialect' and this section is missing in the latest dev portal. Please consider adding it.

Effort::FE: 10

Backend API implementation is captured in https://github.com/wso2/product-is/issues/10344

**Comment by thanujalk** [comment]
This is not there in the IS 5.11.0-beta4 as well.

**Comment by thivi** [comment]
The application API currently doesn't support this. The relevant API issue is tracked here: https://github.com/wso2/product-is/issues/10344

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
