### ISSUE TITLE
Two add new template buttons

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10234]
**Describe the Issue:**
There are two add new template buttons in a newly created email template type.

<img width="968" alt="Screenshot 2020-05-11 at 23 11 38" src="https://user-images.githubusercontent.com/11191791/81593329-e6a6ca00-93dc-11ea-8096-2b6f8b1770b1.png">

**How To Reproduce:**
Create a new template type.

**Comment by thanujalk** [comment]
This is resolved now.
