### ISSUE TITLE
Portals do not validate issuer value returned in the .well-known/openid-configuration response

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10230]
**Describe the Issue:**
Currently, the portal makes use of OIDC discovery to gather the endpoint information related to the authorization server.

The OIDC discovery is done by calling the discovery endpoint as 
{issuer}/.well-known/openid-configuration where the part before .well-known/openid-configuration is considered as the issuer value.

According to the spec, a client must validate whether the {issuer} value matches with the "issuer" element sent in the OIDC discovery response. Additionally the "issuer" value must be equal to the "iss" claim of the id_token
(https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation)

Currently, the portal does not seem to validate these.

The OIDC Discovery calls goes to, 
https://localhost:9443/t/wso2.com/oauth2/oidcdiscovery/.well-known/openid-configuration
issuer = https://localhost:9443/t/wso2.com/oauth2/oidcdiscovery

but the OIDC discovery response returns https://localhost:9443/t/wso2.com/oauth2/token as the issuer value. Also in the id_token 'iss' claim has https://localhost:9443/t/wso2.com/oauth2/token

**How To Reproduce:**
- Access the User portal or dev portal and check the network trace for the OIDC discovery call and inspect its response
- Check the id_token iss claim.

**Expected behavior:**
Possible fix,

1. Call the OIDC discovery URL as https://localhost:9443/t/wso2.com/oauth2/token/.well-known/openid-configuration
ie. the issuer value should be https://localhost:9443/t/wso2.com/oauth2/token

2. Add validation to verify issuer returned in response
3. Validate 'iss' claim of id_token

**Comment by thanujalk** [comment]
Now the issuer value in the https://localhost:9443/oauth2/token/.well-known/openid-configuration come as `"issuer": "https://localhost:9443/oauth2/token"`

@thivi please verify whether issuer value is validated.
