### ISSUE TITLE
Dark mode switch UI update improvement

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#10237]
**Describe the Issue:**
When switching between the light and dark mode in the "Script based configuration" in the application "Sign-on Method", the text that says "Dark mode" doesn't change. 

<img width="729" alt="Screenshot 2020-04-27 at 10 50 52" src="https://user-images.githubusercontent.com/14804283/80336463-f8cd2800-8874-11ea-9c2e-d9f7ce4c31ca.png">

<img width="735" alt="Screenshot 2020-04-27 at 10 51 16" src="https://user-images.githubusercontent.com/14804283/80336493-071b4400-8875-11ea-904f-c5e2a65567ef.png">

**How To Reproduce:**
1. Login to the admin-portal.
2. Click on "Applications" in the sidebar and click the drawing pen at the right side of an existing application to edit it (eg - User portal).
3. Go to "Sign-on Method" tab.
4. Switch dark mode toggle button in "Script based configuration". 

**Expected behavior:**
When the mode is changed using the toggle button, the text should also be changed between **Dark mode** and **Light Mode**. 

**Device Information** (_Please complete the following information_) **:**
 - Device: MacBook Pro (Retina, 15-inch, Mid 2015)
 - OS: macOS Catalina 10.15.4 (19E287)
 - Browser + Version: Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by thanujalk** [comment]
It says dark mode enabled or not.
