### ISSUE TITLE
[User] - When changing the user store, blank page

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10236]
**Describe the Issue:**
If changed to a user store with no users in the user store, the users page goes blank as shown in the following image.

<img width="1680" alt="Screenshot 2020-05-03 at 18 41 21" src="https://user-images.githubusercontent.com/11191791/80915128-b5d7ec80-8d6d-11ea-9481-5e6ba1e79fc6.png">

**How To Reproduce:**
Create a new user store
Switch to that user store in users listing page

**Expected behavior:**
Should be able to add new users.

**Comment by NipuniBhagya** [comment]
Closing this issue as it is fixed in the latest pack.
