### ISSUE TITLE
Unable to update IDP advanced configuration

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10233]
**Describe the Issue:**
Unable to update IDP advanced configuration. When clicking update an error occurred message is displayed.
Looking at the network call the following error is shown.
`
{"code":"UE-10000","message":"Invalid Request.","description":"Provided request body content is not in the expected format.","traceId":"27692e26-6431-46b1-b09c-5b0a3c4aa79b"}
`

**How To Reproduce:**

1. Create an IDP
1. Go to edit > advance tab
1. Click update (no changes needed)

**Expected behavior:**
A success message should be displayed and the configuration should be updated.

**Comment by thanujalk** [comment]
Can be reproduced with IS 5.11.0-beta4
