### ISSUE TITLE
Can add one invalid url in OIDC application

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10232]
**Describe the Issue:**
Can add the **first call back** url as an invalid URL in an OIDC application. Found this can be done in the creating wizard and the editing screen.

**How To Reproduce:**
Give an invalid URL as the callback URL in a OIDC application. 

**Expected behaviour:**
The invalid URL should not be accepted.

**Comment by thanujalk** [comment]
The issue can be reproduced with IS 5.11.0-beta4
