### ISSUE TITLE
Local user associate fails when tenant domain is not added to the username input

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10231]
**Describe the Issue:**
In the user portal, we can link local accounts using the link account widget.

Let's say I logged into the user portal with the URL https://localhost:9443/t/authello.com/user-portal where my tenant is authello.com

Now when I try to link another local account as below an error is thrown when the username **does not contain** the tenant domain

![image](https://user-images.githubusercontent.com/5237653/81779813-16f08480-9513-11ea-8960-997c55e78c4f.png)

I was able to see the error message

```
{"code":"UAA-8540","message":"Error while adding associations of user: farasath","description":"Cross tenant association is not allowed","traceId":"415afc30-f95c-4eed-af96-9d3c6f7ba6a8"}
```

When I append the tenant domain and associate as farasatha@authello.com it works as expected.

But this breaks the UX since at no point in the user portal before the user had to enter the tenant domain (Even during login). Having to enter the tenant domain here doesn't feel right.

**How To Reproduce:**
As explained above.

**Expected behavior:**
A user should be able to associate accounts within his tenant without having to specify tenant domain in the username

**Comment by thanujalk** [comment]
The issue can be reproduced with IS 5.11.0-beta4. As a solution, we can display the "@tenanat-domain" part as a fixed part at the end of the text box or as a label after the text box.
