### ISSUE TITLE
Roles & Permission Management - Add permission categories

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10249]
**Feature Description**
Ability to add permission categories.

**Component**
Roles & Permission Management

**Comment by ayshsandu** [comment]
@DimalChandrasiri can you elaborate more on the requirement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
