### ISSUE TITLE
[Error Handling] Errors returned by the APIs are not properly handled.

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10245]
**Describe the Issue:**
Some API's return the error descriptions under the attribute `detail` and some return them under `description`.

**How To Reproduce:**
1. Navigate to the user portal in tenant mode.
2. Try to associate a user from a different domain.
3. An alert will be shown with a generic error message. i.e. "error occurred while adding the linked account".

**Expected behavior:**
The error returned from the API request should be displayed.

**Screenshots:**

Error returned by the API.

<img width="618" alt="Screen Shot 2020-03-11 at 2 24 38 PM" src="https://user-images.githubusercontent.com/25959096/76412314-69011680-63b9-11ea-9b25-30d242cba13a.png">

Alert shown on the UI.

<img width="418" alt="Screen Shot 2020-03-11 at 4 47 58 PM" src="https://user-images.githubusercontent.com/25959096/76412342-73bbab80-63b9-11ea-8d25-e958539c0ed4.png">

**Device Information** **:**
 - Device: PC
 - OS: MacOS Mojave 10.14.6
 - Browser + Version Chrome 79.0.3945.130

**Comment by thanujalk** [comment]
This is fixed now.
