### ISSUE TITLE
[Console] Suggestions for few UX improvements

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10241]
There are a few UX improvements I would like to suggest in the dev portal.

![image](https://user-images.githubusercontent.com/5237653/78057577-96cbf080-73a4-11ea-9adc-b17a130ebdfe.png)

1. I feel the **regenerate client secret** option should go inside "Access" section where the client_id and client secret are shown. The idea of the regenerate client secret option is to change the client secret. So having it near client_secret allows a user to quickly validate the result of his action

2. The **revoke the application** puts the application in the 'INACTIVE' state making it unavailable for authentication requests etc. It would be better if we could represent this visually in the dev portal. May be displaying a status or greying out the application :)

3. When an application is revoked, a user needs to regenerate the secret to make the application active. It would be great if we could guide the user on this action. Maybe we can simply explain this in the option itself.

**Comment by thanujalk** [comment]
**Update:**

Regenerate and Rovoked options moved under Access.

When app is revoked, we need to improve the UI to show it as revoked and inorder to make it active regenerate the credentials.

**Comment by brionmario** [comment]
**Update:**

`Scenario 2` is addressed through https://github.com/wso2/identity-apps/pull/1333. Ideally the status should be shown in the listing view as well, but the listing API doesn't provide the state ATM. For now, a status bulb is shown to the users at the edit page notifying them of the application's state. 

<img width="1003" alt="Screen Shot 2020-11-05 at 6 02 29 AM" src="https://user-images.githubusercontent.com/25959096/98183665-ae68ea00-1f2e-11eb-823e-68d26cb17b7e.png">
<img width="1002" alt="Screen Shot 2020-11-05 at 6 02 11 AM" src="https://user-images.githubusercontent.com/25959096/98183671-b032ad80-1f2e-11eb-8279-553ef25cf509.png">
<img width="1001" alt="Screen Shot 2020-11-05 at 6 01 49 AM" src="https://user-images.githubusercontent.com/25959096/98183675-b32d9e00-1f2e-11eb-9839-b8db687a9ec7.png">

`Scenario 3` is addressed with https://github.com/wso2/identity-apps/pull/1322. Once the application is revoked, a message will be shown to the users informing that the application can be reactivated by regenerating the client secret.

<img width="1577" alt="Screen Shot 2020-11-04 at 2 46 57 PM" src="https://user-images.githubusercontent.com/25959096/98092399-a2d4df00-1eac-11eb-8692-b0f9cd60b739.png">

**Comment by brionmario** [comment]
**Update:**

`Scenario 3` is addressed with https://github.com/wso2/identity-apps/pull/1322. Once the application is revoked, a message will be shown to the users informing that the application can be reactivated by regenerating the client secret.

<img width="1577" alt="Screen Shot 2020-11-04 at 2 46 57 PM" src="https://user-images.githubusercontent.com/25959096/98092399-a2d4df00-1eac-11eb-8692-b0f9cd60b739.png">
