### ISSUE TITLE
Query Parameters Element doesn't set initial values to state

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#10240]
**Describe the Issue:**
If we didn't edit the query params element, it submits empty when the form submits. The initial values get lost on the way.

![Peek 2020-04-21 13-01](https://user-images.githubusercontent.com/9441136/79838800-317e8480-83d1-11ea-94fa-0c4503e1a61e.gif)

**Comment by thivi** [comment]
This issue has been resolved in 5.11.0-Beta3 SNAPSHOT.
