### ISSUE TITLE
[Suggestion]Instead of displaying an error message, it is best to use a method to enter values ​​for missed mandatory claims.This will enable the user to get their work done easier.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10250]
Affected version: wso2is-5.10.0-alpha3-SNAPSHOT
Identity - app: 0.9.11-SNAPSHOT

**Describe the bug**
The current behavior of, Consent Management with Single-Sign-On flow
The consent screen appears only if the user has already entered values for the mandatory claims. If any of these values is missing ((e.g., if Email is a mandatory claim, but the user has not yet provided an email address), the User portal display an error message, with the content "Authentication attempt failed.
Error while handling missing mandatory claims"

So then the user has to go back admin portal, must enter those values.
But it is better, if we can appear a screen where the user must enter those values before the consent screen will appear.

Step to reproduce:
1. Configure the following service provider claims  additionally and update. 
http://<claim_dialect>/claims/fullname (mandatory claim)
http://<claim_dialect>/claims/email (mandatory claim)
2. Enter the user credentials and click Submit via user portal. 
3. Getting an error,
![image](https://user-images.githubusercontent.com/39120228/73155096-9b9fca00-40ff-11ea-9627-a0fe957c2436.png)

**Comment by ayshsandu** [comment]
Now, editing the `Myaccount` application configuration is not enabled by default. 
None of the attributes is mandatory in the default configuration. Hence, this issue is no longer valid.
