### ISSUE TITLE
Document information coming in events

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10256]
**Is your suggestion related to a missing or misleading document? Please describe.**
In https://is.docs.wso2.com/en/latest/develop/writing-a-custom-event-handler/ we explain how to write event handlers, for example, let's take the event `PRE_ADD_USER `. 

For a developer to be able to write a useful event handler he/she should know the information passed in the event. Otherwise, the only way to find out is by writing a dummy event handler and debugging the event. This is not developer-friendly.

**Describe the improvement**
Capture the event information in the docs for each documented event.

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
