### ISSUE TITLE
Couldn't self sign up user for tenants with myaccount

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10259]
**Describe the issue:**
Couldn't self sign up user for tenants with myaccount (even with tenant qualified url same behaviour)

**How to reproduce:**
1. Go to myaccount url and click on create account
2. Give a username with tenant domain
3. Always user is created in the super tenant.

**Expected behavior:**
User should be created in tenant.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by somindatommy** [comment]
Will be resolved from https://github.com/wso2/identity-apps/pull/1313
