### ISSUE TITLE
[Myaccount] Wrong error message when self registration disabled in tenant mode

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10258]
**Describe the issue:**
When trying to create an account with a tenant domain, the error message still saying "Self registration is disabled for tenant - carbon.super "

**How to reproduce:**
1. Navigate to my account 
2. click on create account
3. Give nama as nilasini@wso2.com (wso2.com is a valid tenant domain)
4. Get error message as "Self registration is disabled for tenant - carbon.super "

**Expected behavior:**
Error message should be "Self registration is disabled for tenant - wso2.com "

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

Related to https://github.com/wso2/product-is/issues/10259

**Comment by somindatommy** [comment]
Will be resolved from https://github.com/wso2/identity-apps/pull/1313
