### ISSUE TITLE
"Setting up carbon_home" image is misleading

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10255]
**Description:**
Change the image in https://is.docs.wso2.com/en/latest/setup/installing-as-a-windows-service/#setting-up-carbon_home into 
<img width="469" alt="Capture" src="https://user-images.githubusercontent.com/25483865/88487527-b5995880-cf3a-11ea-937d-f91754eb595c.PNG">
If the variable name is set to CARBON_HOME instead of carbon_home,
`java.lang.ClassNotFoundException: org.wso2.carbon.bootstrap.Bootstrap` error will be getting when starting the wrapper in console mode.

**Affected Product Version:**
IS: WSO2-IS- 5.10.0
OS: Windows 10

**Comment by sherenewso2** [comment]
Closing this as it has been fixed with https://github.com/wso2/docs-is/pull/2165
