### ISSUE TITLE
"Create Account" displayed on the login page even when user self-registration is disabled.

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10252]
**Describe the bug**
The "Create Account" link is displayed on the login page even when user self-registration is not enabled. Once the link is clicked, the user is allowed to specify a user name and a message saying that user self-registration is disabled is shown only when the user proceeds further. 

**To Reproduce**
Go to the login page and click on the "Create Account" link. 

**Expected behavior**
The "Create Account" link should not be shown if the user self-registration is disabled. 

**Screenshots**
<img width="507" alt="Screenshot 2020-01-22 at 11 48 58" src="https://user-images.githubusercontent.com/20745428/72870175-66653780-3d0d-11ea-9db5-ce38edcb006b.png">
<img width="506" alt="Screenshot 2020-01-22 at 11 48 50" src="https://user-images.githubusercontent.com/20745428/72870186-70873600-3d0d-11ea-9407-f6a9b133c7be.png">

Depends on: https://github.com/wso2/product-is/issues/9717

**Comment by inthirakumaaran** [comment]
Tracked in https://github.com/wso2/product-is/issues/9717
