### ISSUE TITLE
Cannot login once a user tries to login with no privileges

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10251]
**Describe the Issue:**
A user with admin privileges cannot login once a user with no login privileges tries to login to the system. It redirects to `you don't have privileges to login` page and continue to do so even if tries to login again.

**How To Reproduce:**
- Create a new user with a password without roles or groups.
- Try to login with the new user.
- After `You are not authorized` page try to login with an admin user.

**Expected behavior:**
While unauthorized user can login, authorized user should be able to login.

**Comment by thivi** [comment]
This is no longer reproducible in 5.11.0-Beta3-SNAPSHOT.
