### ISSUE TITLE
[Myaccount]Button click doesn't do anything when click on back button and proceed

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10261]
**Describe the issue:**
Button click doesn't do anything when click on the back button and proceed during self registration

**How to reproduce:**
1. Go to myaccount login page
2. Click on create account
3. Give a username name and click on proceed
4. Once landed to the signup page click on the back button
5, Try to change the username and click on proceed. Could able to click the button but nothing happens

**Expected behavior:**
Should able to edit the username and proceed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by IsuraD** [comment]
Could reproduce only in firefox.
