### ISSUE TITLE
[Myaccount]Button click doesn't do anything when click on cancel button and proceed

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10260]
**Describe the issue:**
When creating an account and give an invalid username (username with two letters) there is a warning, once press cancel and change the name and proceed, nothing happening.

**How to reproduce:**
1. Go to myaccount login page
2. Click on createaccount
3. Enter the username as "kl" and click on proceed
![1](https://user-images.githubusercontent.com/20336761/97860404-13062800-1d28-11eb-8e6d-8143f752a0e9.png)

4. Then press cancel and give a correct name and click on proceed
![2](https://user-images.githubusercontent.com/20336761/97860460-2dd89c80-1d28-11eb-844d-16ef8452845a.png)

**Expected behavior:**
Successful registration

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Related Issues**

https://github.com/wso2/product-is/issues/10261

**Comment by IsuraD** [comment]
Cannot reproduce this in the 5.11.0-beta4. 

@nilasini Please reopen if you still encounter the issue.

**Comment by IsuraD** [comment]
reopen since could reproduce on firefox.
