### ISSUE TITLE
Text fields not validated in user self registration form

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10266]
**Describe the issue:**

A number of text fields in the user self-registration form allow text of over 255 characters to be entered. The text fields are;
    

- First name
- Last name
- Email address (validates only the email domain)
- Organization
- Telephone (allows non-numerical inputs as well)
- IM
- Country
- Mobile (allows non-numerical inputs as well)
- URL (allows any string to be entered/doesn't validate URL)

**How to reproduce:**
1. Login to the Console as admin
2. Go to Manage > User Onboarding > Self Registration
3. Enable "User self registration" and disable "Lock user account on creation"
4. Press update and log out
5. Go to My Account (https://localhost:9443/myaccount)
6. Click "Create Account" on the login form
7. Enter a username and click Proceed to self-register
8. Fill all the text fields (except the password fields) with over 255 characters
9. Fill password fields with the proper length (5-30 characters)
10. Email address can be over 255 characters but should end with a domain (eg: @wso2.com)
11. Accept privacy policy and click register

**Observation:**
User registration is allowed and can be accessed by logging into my account with the registered user

**Expected behavior:**
Text fields should be validated accordingly 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-beta4
 - OS: Mac
 - Database: MySQL 8
 - Userstore: JDBC

**deployment.toml config**
```
[user_store]
type = "database_unique_id"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated

[tenant_mgt]
tenant_idle_timeout=2

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/mydb?useSSL=false"
username = "root"
password = "root"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/mydb?useSSL=false"
username = "root"
password = "root"

[database.user]
url = "jdbc:mysql://localhost:3306/mydb?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"

[realm_manager]
data_source = "WSO2USER_DB"
```

---

### Optional Fields

**Suggested labels:**
UX

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
