### ISSUE TITLE
Issue with SCIM outbound provisioning

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#10279]
**Describe the issue:**
when user is added to internal IS, user is not creating in external IS when using SCIM service provider but user is creating in external IS when using SCIM residential service provider.

**How to reproduce:**
Configure Internal IS as SCIM outbound provisioning IDP and service provider as SCIM outbound provisioning SP.

**Expected behavior:**
when user is added in internal IS the same user should also be created in external IS.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 beta 3
 - OS:  Linux
 - Database:  H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kiwinesian** [comment]
I think the `localhost` check is still enabled by default.
Probably want to address this in the next release? Otherwise, one will have to host it with a proper `https` TLS certificate from a CA
