### ISSUE TITLE
reCaptcha for Security-Question Based Password Recovery NOT WORKING

### ISSUE THREAD

**Issue by SupunSPWithana** [wso2/product-is#10277]
**Describe the issue:**
reCaptcha(v2) for Security-Question Based Password Recovery NOT WORKING
![image](https://user-images.githubusercontent.com/26740844/97955159-8f9e1280-1dcb-11eb-85f2-b5b0102b3c15.png)

**How to reproduce:**

1. Create a user with Login permission and security questions in Management Console
2. Go to Myaccount and Forget password option.
3. Give username and Recover with Security Questions option
4. This page should display reCaptcha if answers is incorrect

**Expected behavior:**
![image](https://user-images.githubusercontent.com/26740844/97954282-143b6180-1dc9-11eb-9267-5b7a5377b8e9.png)

**Environment information**
 - Product Version: IS 5.11.0-Beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

**Comment by janakamarasena** [comment]
For Recaptcha to work in security question-based password recovery we need to enable account locking. This is the current expectation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
