### ISSUE TITLE
Password strength not validated in user self registration form

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10272]
**Describe the issue:**
The strength of the password to be used by a new user is not validated in the self registration form like when a user is created by an admin account through the console.

**How to reproduce:**

1. Login to the Console as admin
2. Go to Manage > User Onboarding > Self Registration
3. Enable "User self registration" and disable "Lock user account on creation"
4. Press update and log out
5. Go to My Account (https://localhost:9443/myaccount)
6. Click "Create Account" on the login form
7. Enter a username and click Proceed to self-register
8. Fill in the first name, last name and email address (mandatory fields)
9. Type "admin" as the password in both required fields
10. Accept privacy policy and click register

**Expected behavior:**
The password strength validation should be done similar to the console and should not allow weak passwords.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta4
 - OS: Mac
 - Database: MySQL 8
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/10266

**Suggested labels:**
UX

**Comment by IsuraD** [comment]
This is not a bug. If you have defined tenant wise or user store wise password polices, those policies will be validated.

**Comment by IsuraD** [comment]
<img width="799" alt="Screenshot 2020-11-04 at 00 53 25" src="https://user-images.githubusercontent.com/8455535/98031211-2dc7c200-1e38-11eb-852f-46646a5739c6.png">

Real-time validations can be implemented as an improvement.
