### ISSUE TITLE
[consoleApp] [Manage] Updating any field available in the connection tab of jdbc secondary userstore fails

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10285]
**Describe the issue:**
Secondary jdbc userstore cannot update any of the  field available under connection tab

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Manage > Userstores > New Userstore > JDBC
4. Add a maria db Userstore as a secondary userstore by giving the necessary details
4.Save
5. Go to added userstore edit view > Connection tab 
6. Try To update some of the fields as listed below
Test on Return
Test on Borrow
Access to undelying connection allowed
Remove abondened
Log abondened
Alternate username allowed
commit on return
rollback on return

Check for the other field as well 

**Observation**
UI says it updated successfully. Go back for another tab and come back and see the updated fields updates are not available

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta4
ubuntu 16.04
Chrome Version 85.0.4183.121

![us2](https://user-images.githubusercontent.com/31848014/97967184-e236f900-1de2-11eb-88a1-6bf75ddb99a6.png)

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-api-server/pull/223
