### ISSUE TITLE
[consoleApp] [Manage] Cannot update jdbc userstore Description

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10282]
**Describe the issue:**
Secondary jdbc userstore cannot update its description

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Manage > Userstores > New Userstore > JDBC
4. Add a maria db Userstore as a secondary userstore by giving the necessary details
4.Save
5. Go to added userstore edit view > Update Description
6. Update

**Observation**
UI says it updated successfully. Go back for another tab and come back and see the updated description is not available

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta4
ubuntu 16.04
Chrome Version 85.0.4183.121

![us1](https://user-images.githubusercontent.com/31848014/97964215-69ce3900-1dde-11eb-9d41-82a0269d62de.png)

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-api-server/pull/223
