### ISSUE TITLE
[consoleApp] [Manage] Secondary jdbc userstore cannot update any of the fields available under user and groups tabs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10286]
**Describe the issue:**
Secondary jdbc userstore cannot update any of the field available under user and groups tabs

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Manage > Userstores > New Userstore > JDBC
4. Add a maria db Userstore as a secondary userstore by giving the necessary details
4.Save
5. Go to added userstore edit view > Users Tab and Groups Tab 
6. Try To update any of the fields listed below
Users tab

Is bulk import supported
make username unique across tenants
caseinsensitive username

Groups tab
Maximum group list length

Check for the other field as well

**Observation**
UI says it updated successfully. Go back for another tab and come back and see the updated fields updates are not available

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta4
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by thivi** [comment]
This has been resolved by https://github.com/wso2/identity-api-server/pull/223
