### ISSUE TITLE
Git integration Rest Endpoint permission scopes

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10283]
**Describe the issue:**
This issue will track the following tasks related to git integration. Initial feature tasks were tracked with this [issue.](https://github.com/wso2/product-is/issues/8278)

- [ ]  Permission and Scope creation for Rest end points.
- [ ]  Integration Test with product IS.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
