### ISSUE TITLE
Terminate all active IDP sessions in My Account doesn't logout the user from the devices

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10291]
**Describe the issue:**
Selecting the option of terminating all the active IDP sessions from the My Account app, only terminates the sessions and doesn't logout the user from all the logged-in devices. The user can visit the 3 pages on the app and is logged out only when the page is refreshed/reloaded. 

**How to reproduce:**
1. Login to My Account from Device A (normal web browser) with a user
2. Login to My Account from Device B (another web browser/incognito window) with the same user
3. Login to My Account from more devices with the same user if required
4. Go to My Account > Security > Active IDP Sessions in one of the devices
5. Press Terminate all and confirm the termination 

**Observation:**
- All the active sessions get terminated but the user isn't logged out from any of the devices and has the capability to go to the other sections of My Account
- The user gets logged out only if the browser tab is refreshed/reloaded

**Expected behavior:**
User should be logged out from all the devices (web browsers) that the same user was logged in from

**Environment information:**
 - Product Version: IS 5.11.0-Beta4
 - OS: Mac
 - Browsers: Chrome/Safari 
 - Database: MySQL 8
 - Userstore: JDBC

---

### Optional Fields

**Suggested labels:**
myaccount

**Comment by janakamarasena** [comment]
The reason for this is the current logout mechanisms has no way of sending the signal to logout when a session termination happens. This is a limitation in the current implementation.

**Comment by brionmario** [comment]
Related https://github.com/wso2/product-is/issues/8700

**Comment by piraveena** [comment]
Refer to this comment https://github.com/wso2/product-is/issues/8700#issuecomment-742271957. This also sorted in for console app and myaccount since we do the commonnauthId cookie validity in SSOSessionBasedTokenBinder

**Comment by piraveena** [comment]
This improvement https://github.com/wso2/product-is/issues/10481 will resolve this issue as well irrespective of binding. Token will be revoked upon session termination event after this issue is fixed https://github.com/wso2/product-is/issues/10481. Hence closing this issue
