### ISSUE TITLE
Better user interface checkboxes are not displayed wherever possible in user registration page

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10290]
**Describe the issue:**
With my account user registration for account locking in the user registration page text field is shown instead of a checkbox. Need to handle it.

**How to reproduce:**
1. Go to myaccount login page
2. Click on create account
3. Enable account lock as supported by default claim through management console.
3. Check the account lock field in the user creation age of myaccount

**Expected behavior:**
Check box should appear

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
