### ISSUE TITLE
Date field is not validate in self registration

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10294]
**Describe the issue:**
The date field is not validated in self-registration.

**How to reproduce:**
1. Make data of birth claim as support by default
2. Go to myaccount login page
3. Create account
4. Enter any text in date of birth field
5. Click on register
6. Successfully reigstered

**Expected behavior:**
only valid dates format should be alloweed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by ayshsandu** [comment]
Ideally, the date format is an organization preferred format. When the regex value of the date of birth claim is updated, the input will be validated against it at the self-registration and account update.

Solution: Update the value of the **Regular Expression** field of the 
![image](https://user-images.githubusercontent.com/5061791/102329841-e09a4c80-3fae-11eb-907d-7130538864fa.png)

sample regex for `yyyy-mm-dd` format = `^(19|20)\d\d[- \.](0[1-9]|1[012])[- \.](0[1-9]|[12][0-9]|3[01])$`
