### ISSUE TITLE
Temporary claim value cannot be set as the sub claim in the ID token, however, it is set it in the self-contained access token.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#10297]
**Describe the issue:**
Using adaptive authentication, temporary claim values can be set for a claim as shown below(useful when userstore is readonly),

```
user.claims['http://wso2.org/claims/im'] = "test123";
```
This temporary claim value cannot be set as the sub claim in the ID token, however, it is being set in the self-contained access token.

**How to reproduce:**

- Get a WUM updated IS-5.10.0 pack, Setup an OIDC service provider with the token issuer JWT.
- In the requested claims add the http://wso2.org/claims/im as a requested claim.
- As the Subject Claim URI add http://wso2.org/claims/im.
- Add the following adaptive script.
```
 var onLoginRequest = function(context) {
     executeStep(1, {
         onSuccess: function (context) {
                       var user = context.currentKnownSubject;
                       user.claims['http://wso2.org/claims/im'] = "test123";
                       Log.info("claim"+ user.claims['http://wso2.org/claims/im']);
         }
     });
 };
 ```
- Initiate a request to get an access token and id token(grant types tried implicit, code). Check the difference in the sub value in the tokens.

Even though a temp value for the subject claim is set, the value for the claim is being retrieved from the user store. In code[1], we try to get it from a cache, however, there is seems to be no subject stored in the cache.

**Expected behavior:**
The temporary value which is set for the claim should be set as the sub in the id token, like in the self-contained access token to be consistent. 

**Environment information** **:**
 - Product Version: [IS 5.10.0]

[1]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java#L326

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
