### ISSUE TITLE
Allow admins to configure password strength validation

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10301]
**Is your suggestion related to an experience? Please describe.**
The Console app and My Account app show a password meter. However, password strength is not validated. Ideally, an admin should be able to configure what the minimum strength allowed for a password is and the apps should validate passwords based on that configuration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
