### ISSUE TITLE
Possible to navigate My Account after user session has expired

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10300]
**Describe the issue:**
It's possible to navigate the My Account app by clicking the links on the page even after the user session has expired. The login screen is prompted only when the page is refreshed. 

**How to reproduce:**
1. Login to the management console (https://localhost:9443/carbon)
2. Go to "Resident" under identity providers
3. Change the value of "Idle Session Timeout" to 1 (To limit the user session to 1 minute)
4. Press update and logout from the management console
5. Login to the My Account app
6. Leave it idle until the user session expires (1 min as set in step 3)
7. Click Personal Info and then click Security
8. Refresh the page

**Expected behavior:**
The login page should be prompted when Personal Info is clicked in step 7

**Environment information:**
 - Product Version: IS 5.11.0-Beta4
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Suggested labels:**
myaccount

**Comment by kushanb** [comment]
The sessions for My Account are not handled by the above mentioned configuration. The proper configuration should be done by editing the "session" object found in `<IS_HOME>/repository/deployment/server/webapps/myaccount/deployment.config.json`

**Comment by ShanikaWickramasinghe** [comment]
Closing the Issue based on the above comment
