### ISSUE TITLE
Document configuring captcha support for SSO login with custom authenticators

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#10306]
**Is your suggestion related to a missing or misleading document? Please describe.**

When configuring captcha for SSO login, if a custom authenticator is used and secondary userstores are involved, the custom authenticator should have `AuthMechanism` parameter set to `basic` defined under `<AuthenticatorConfig>` in `<CARBON_HOME>/repository/conf/identity/application-authentication.xml`. The relevant docs need to be updated with this information.

More context : https://github.com/wso2/product-is/issues/9975

**Configuration for 5.7**
Following configuration should be added under `<AuthenticatorConfigs>` in `<CARBON_HOME>/repository/conf/identity/application-authentication.xml` file. (For a sample custom authenticator named `CustomBasicAuthenticator`)
```
<AuthenticatorConfig name="CustomBasicAuthenticator" enabled="true">
        <Parameter name="AuthMechanism">basic</Parameter>
</AuthenticatorConfig>
```
**Configuration for 5.10 and latest**
The following configuration should be added to `<CARBON_HOME>/repository/conf/deployment.toml` file and set `AuthMechanism` of the custom authenticator to `basic`. (For a sample custom authenticator named `CustomBasicAuthenticator`)
```
[[authentication.custom_authenticator]]
name = "SampleCustomAuthenticatorName"
[authentication.custom_authenticator.parameters]
AuthMechanism = "basic"
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
