### ISSUE TITLE
XACML policies are not available for tenants

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10310]
**Describe the issue:**
XACML policies are not available for tenants

**How to reproduce:**
1. Create a tenant
2. Login to management console in tenant mode
3. Go to Policy administration
4. No policies are there
![1](https://user-images.githubusercontent.com/20336761/98080781-fbe84700-1e9b-11eb-8200-b6f02c7f2118.png)

**Expected behavior:**
XACML policies should be available for tenant users.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version: IS-5.11.0-beta4
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by nilasini** [comment]
Since this is a known limitation reducing the severity

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
