### ISSUE TITLE
Not directing to salesforce login page when configured with Logging in to Salesforce using the Identity Server

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#10312]
**Describe the issue:**
Not directing to Salesforce login page when configured with Logging in to Salesforce using the Identity Server, except that provisioning users to Salesforce working properly.
 
**How to reproduce:**
referred to  
(https://medium.com/@dewni.matheesha/jit-provisioning-to-salesforce-using-wso2-identity-server-during-saml-sso-login-41df1827b6d6)

01) created domain in saleforce 
02)Download SAML metadata from WSO2 Identity Server
03)Configuring SSO settings in Salesforce
![sso1](https://user-images.githubusercontent.com/31467146/98077814-efadbb00-1e96-11eb-8d8f-a677cd68bf6d.png)
![sso2](https://user-images.githubusercontent.com/31467146/98077886-081dd580-1e97-11eb-8a31-1324d45a51ac.png)

04)Configuring WSO2 Identity Server as an Authentication Service for Salesforce
05) Adding Salesforce as a SAML SSO service provider in WSO2 Identity Server
![sp1](https://user-images.githubusercontent.com/31467146/98086120-4968b200-1ea4-11eb-9340-66f93188b74f.png)
![sp2](https://user-images.githubusercontent.com/31467146/98086135-4f5e9300-1ea4-11eb-9370-6cf0a4c03589.png)

06 - Add a new claim to track the Salesforce username
07 - Claim configuration in the service provider
08 - Add role mappings
09 - Add users

**Expected behavior:**
Directed to Salesforce login page of the created domain and provide the option of login with wso2 identity provider.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 beta 4
 - OS:  Linux
 - Database:  H2
 - Userstore:  LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by thanujalk** [comment]
You have configured Identity Server as the IdP in this case. So the test is invalid.
