### ISSUE TITLE
SCIM2 REST API docs need to be more detailed

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#10313]
**Describe the improvement**
Currently, the docs do not provide detailed descriptions of every possible operation that can be done with the different requests.
For example, a `patch` request allows three types of operations [1]. The example provided only shows one operation. The other operations cannot be performed in similar manner as they require a body of a different format. Refer https://github.com/wso2/product-is/issues/10263#issuecomment-721581108. Also, the model is not verbose enough to understand the required formats intuitively. This is applicable for the other endpoints as well (Groups, Users, Bulk).

[1] https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Roles%20Endpoint/patchRole

**Comment by sherenewso2** [comment]
Need to fix this as well:

The sample curl commands that get generated are wrong. The base URL gets picked up as `https://is.docs.wso2.com/t/{tenant-domain}/scim2/` instead of `https://localhost:9443/scim2`

**Comment by nilminiwso2** [comment]
Should be fixed for IS 6 andIS 5.11. Please reopen if anything is missing.

- https://is.docs.wso2.com/en/latest/apis/scim2-rest-apis/
- https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/
