### ISSUE TITLE
OpenID Connect Discovery document is not clear and has several URL's which are wrong.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#10322]
**Is your suggestion related to a missing or misleading document? Please describe.**
OpenID Connect Discovery document[1] is not clear and has several URL's which are wrong. 

**Describe the improvement**
1) At the start of the document it says that the OpenID Connect discovery endpoint is as follows:
```
https://localhost:9443/.well-known/oidcdiscovery
```
This is in fact wrong. it should be corrected to:
```
https://localhost:9443/oauth2/oidcdiscovery
```
The Web finger Endpoint URL to which the OpenID Provider Issuer discovery request should be sent is
```
https://localhost:9443/.well-known/webfinger
```
2) ```In WSO2 Identity Server, the default OpenID Provider Issuer location path is set to oidcdiscovery/.well-known/openid-configuration .```
This is wrong, it should be: ```In WSO2 Identity Server, by default the OpenID Provider Configuration Information is located at https://<HOST>:<PORT>/oauth2/oidcdiscovery/.well-known/openid-configuration  if the "use_entityid_as_issuer_in_oidc_discovery" is set to false.```

3) Also, the following is wrong ```To move the OpenID provider issuer location path to the root <issuer>/.well-known/openid-configuration, add the following configuration to the <IS_HOME>/repository/conf/deployment.toml file.```
it should be: ```To move the OpenID Provider Configuration Information to https://<HOST>:<PORT>/oauth2/token/.well-known/openid-configuration, add the following configuration to the <IS_HOME>/repository/conf/deployment.toml file.```

4) The following part is confusing.
```
OpenID Provider Issuer URL format
 <Host>/oauth2/{issuer}
<Host>: The host number of WSO2 Identity Server (e.g., https://localhost:9443 )
{issuer}: The issuer path component. This value can be either ‘token’ or ‘oidcdiscovery’.
````
Issuer URL format should not have an {issuer} inside it. it would be better to change it.

[1]https://is.docs.wso2.com/en/5.11.0/learn/openid-connect-discovery/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
