### ISSUE TITLE
Change the color combination of "Permission required" section in swagger files

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10328]
**Is your suggestion related to a missing or misleading document? Please describe.**
The section which mentions required permissions for the API endpoint causes poor readability due to the low color contrast. Purple lettering on the black back background doesn't contrast well. This should be fixed in all swagger files if it has been applied.
eg:
![permission-section not readble](https://user-images.githubusercontent.com/25483865/98107532-a5413400-1ec0-11eb-9aba-46f9a9452fb9.png)

https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Roles%20Endpoint/patchRole

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
