### ISSUE TITLE
Add configurations to enable application role permission to view the OAuth app in DCRM

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#10321]
**Description**
The following configuration added to enable application role permission to view the OAuth app in DCRM needs to be documented.
```
[oauth.dcrm]
application_role_permission_required_to_view = false
```
Related PR: https://github.com/wso2/carbon-identity-framework/pull/2933
Related issue: https://github.com/wso2/product-is/issues/8213

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
