### ISSUE TITLE
[Performance] 5.11.0 Beta 3 Performance Numbers has reduction more than 20% in some scenarios when compared to 5.10 WUM

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#10339]
**Describe the issue:**

Scenario Name | Concurrent Users | Comparison With 5.9.0 GA | Comparison With 5.10.0 GA | Comparison With 5.10.0 WUM
-- | -- | -- | -- | --
Authenticate Super Tenant User | 300 | 25.57 | 3.62 | -147.4
Authenticate Super Tenant User | 500 | -17.8 | -33.27 | -259.81
Auth Code Grant Redirect With Consent | 50 | 29.45 | 35.24 | -23.11
Auth Code Grant Redirect With Consent | 50 | 29.44 | 35.22 | -23.14
Auth Code Grant Redirect With Consent | 50 | 29.43 | 35.22 | -23.1
Auth Code Grant Redirect With Consent | 50 | 29.42 | 35.22 | -23.11
OIDC Auth Code Grant Redirect With Consent | 50 | 22.65 | 23.21 | -26.52
OIDC Auth Code Grant Redirect With Consent | 50 | 22.67 | 23.22 | -26.52
OIDC Auth Code Grant Redirect With Consent | 50 | 22.63 | 23.19 | -26.52
OIDC Auth Code Grant Redirect With Consent | 50 | 22.64 | 23.2 | -26.52

**Comment by piraveena** [comment]
Related to this https://github.com/wso2/product-is/issues/14373
