### ISSUE TITLE
Unable to register a git repo with (-) in the repo folder with remote repository fetch option 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10343]
**Describe the issue:**
Cannot input a folder directory available in git with - (dash) 

**How to reproduce:**

1.Access  https://localhost:9443/carbon/
2.Login as super admin
3.Navigate to Main > Remote Repository Fetch > Add
4. When input the directory which is available in a repo with (-) its unable to register the git repo

Cannot do the same via console > manage > remote configurations option

![err1](https://user-images.githubusercontent.com/31848014/98226653-535de400-1f7c-11eb-97c5-7d015aa7ac9e.png)

**Environment information**
mssql2019
uniqueid jdbc primary US
IS 5.11.0 beta5 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
