### ISSUE TITLE
Add the ability to adjust the placement of profile image added through a URL

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10349]
**Is your suggestion related to an experience ? Please describe.**
When changing the profile picture for a user from the console or my account using a URL from a 3rd party host, wider images get cropped and display the area in the center. If the best area to be displayed is not centered it tends to get cropped. 

**Describe the improvement**
The ability to select the area of the image that is displayed in the profile picture from a wider image added through a url would let users focus on the most suitable area to be displayed. 

**Additional context**

Example for a badly positioned profile picture from a wide image

<img width="53" alt="Screenshot 2020-11-05 at 18 13 23" src="https://user-images.githubusercontent.com/19253380/98242506-99be3d80-1f92-11eb-946e-69e7ffe5d516.png">

**Suggested labels**
console, myaccount

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
