### ISSUE TITLE
The request body of the application creation API should provide an attribute to specify the Service Provider Claim Dialect

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10344]
**Is your feature request related to a problem? Please describe.**
Right now, developers can't specify the Service Provider Claim Dialect through the Console app since the API doesn't support this attribute as of yet. The API should support this attribute if this is to be allowed through the Console app. 

Related https://github.com/wso2/product-is/issues/10220

Effort::BE: 10

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
