### ISSUE TITLE
Typo in Application->Advanced UI

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#10359]
**Describe the issue:**

See below image 
<img width="1440" alt="Screen Shot 2020-11-05 at 3 28 21 PM" src="https://user-images.githubusercontent.com/525801/98307945-d0d52480-1f7b-11eb-8581-2ffd8bf20aa7.png">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0 Beta5
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by thivi** [comment]
This has been fixed in 5.11.0-Beta6-SNAPSHOT
![Uploading image.png…]()
