### ISSUE TITLE
Show/hide account recovery options on UI based on configuration

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10357]
**Is your suggestion related to an experience ? Please describe.**
Even we have disabled certain account recovery options, all the options are visible to users and we only show a message once user tries to use it.

**Describe the improvement**
It is required to hide disabled recovery options based on the configuration of each tenant.

**Comment by abhi4u1947** [comment]
Problem #1
 

Goto Resident IDP, "Account Management Policies" -> "Account Recovery"
Then set "Enable Security Question Based Password Recovery" to "False (UnChecked)"
Then try login to User-Portal and from login page click on "Forgot Password".
This will open the "Recover Password" page with 2 option for recovery ("Recover with Mail" and "Recover with Security Questions").
 Why user is seeing the "Recover with Security Questions" option, even if its disable in settings and the worst part is if user click on it then as a result, user sees the following error, which is very weird user experience.

Error!
Security questions based recovery is not enabled

 

 

Problem #2
Goto Resident IDP, "Account Management Policies" -> "Account Recovery"
Then set "Enable Username Recovery" to "False (UnChecked)"
Then try login to User-Portal and from login page click on "Forgot Username".
This will open the "Recover Username" page with some user input fields to fill.
 

 Once user fills all fields and click submit, then it gives following error:

Error!
Username recovery is not enabled

(!)Why user is seeing the "Recover Username" option, even if its disable in settings and the worst part is if user click on it, fill everything as submit then as a result, user sees the error, which is very weird user experience.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
