### ISSUE TITLE
Make SP name javascript regex configurable.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#10353]
**Describe the issue:**
Currently the product offers the capability to define the java regex pattern for service provider name with the below given config.
```
[service_provider]
sp_name_regex= '^[a-zA-Z0-9._-]+(?: [a-zA-Z0-9._-]+)*$'
```
However, the javascript regex pattern is read from [1] where the pattern is hardcoded. This regex pattern will not work when we have Unicode characters in the service provider name.

**How to reproduce:**
Create a service provider with a name containing unicode characters.
<img width="834" alt="Screenshot 2020-11-05 at 21 16 42" src="https://user-images.githubusercontent.com/24982871/98263054-57a1f580-1fac-11eb-97b4-9ccbe6181375.png">

**Expected behavior:**
Make javascript regex pattern for service provider name configurable.

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/add-service-provider.jsp#L208

**Comment by emswbandara** [comment]
@pamodaaw let's re-open this until doc impact is captured.

You have to;
- add a comment explaining the doc impact
- add doc label to this issue
- send PR to doc-is to capture doc improvement and close this issue once those PRs are merged

**Comment by pamodaaw** [comment]
Docs PR for 5.10.0 - https://github.com/wso2/docs-is/pull/2395
