### ISSUE TITLE
Password Expiry Enforcing authenticator UI page needs to fixed for consistency

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10350]
**Describe the issue:**
When trying out the Password Reset Enforcer noticed that the password reset page looks to be inconsistent with the new theme.

![image](https://user-images.githubusercontent.com/5237653/98251178-671a4200-1f9e-11eb-9f4e-59c6e570dadd.png)

**How to reproduce:**
Follow steps in https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md

**Expected behavior:**
The Password Reset page needs to be consistent with the new theme in other UI pages

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Mac

**Comment by brionmario** [comment]
There's an already pending PR https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/pull/36.

@mefarazath Would you be able to review it?
