### ISSUE TITLE
[POST] SCIM 2.0 user response  contains the role , "internal / everyone" but does not assign / display the role to the user in the console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10369]
**Describe the issue:**
[POST] SCIM 2.0 user response  contains the default role as "internal / everyone" but does not assign / display the role to the user in the console

sample curl
```
curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9445/t/wso2.com/scim2/Users
```

response 

```
{
    "emails": [
        {
            "type": "home",
            "value": "kim.jacksonprimary@gmail.com"
        }
    ],
    "meta": {
        "created": "2020-11-06T13:22:27.977941Z",
        "location": "https://localhost:9445/t/wso2.com/scim2/Users/06e837ba-67af-4326-8dd4-1a8bde79fe67",
        "lastModified": "2020-11-06T13:22:27.977941Z",
        "resourceType": "User"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    **"roles": [
        {
            "type": "default",
            "value": "Internal/everyone"
        }**
    ],
    "name": {
        "givenName": "kim",
        "familyName": "jackson"
    },
    "id": "06e837ba-67af-4326-8dd4-1a8bde79fe67",
    "userName": "kim"
}
```
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Beta5 Snapshot
 - OS: Mac
 - Database: H2, DB2 
 - Userstore: LDAP, JDBC

---

**Comment by NipuniBhagya** [comment]
@NilukaSripalim The role Internal/everyone is not returned when fetching the roles list from SCIM2/Roles endpoint (when groups and roles separation is enabled) or SCIM2/Groups endpoint (when groups and roles separation is disabled).

Related issue: https://github.com/wso2/product-is/issues/10444

**Comment by ashendes** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/309, https://github.com/wso2/carbon-identity-framework/pull/3245
