### ISSUE TITLE
[FIDO] Incorrect response in FIDO usernameless device registration API 

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10364]
**Is your suggestion related to a missing or misleading document? Please describe.**
In FIDO [documentation](https://is.docs.wso2.com/en/5.11.0/develop/fido-rest-api/#/)  **start-usernameless-registration** API call response is incorrect.

**Describe the improvement**
start-usernameless-registration API call it returns a new response which added a new set of keys,

**"authenticatorSelection":{
      "requireResidentKey":true,
      "userVerification":"preferred"},**

The complete response is shown below. 

```
{
  "requestId": "02DuswNbjS0UauLRKANdLSGwuhVCdCpxnSt3S1DglkY",
  "publicKeyCredentialCreationOptions": {
    "rp": {
      "name": "WSO2 Identity Server",
      "id": "localhost"
      },
      "user":{
         "name":"test@xyz.com",
         "displayName":"test",
         "id":"quDDpT-SPwU5tuUL1oLAKPSoGc66eKeJn0R7Z5hCveg"
      },
      "challenge":"ylejAMWjpQ_yG-R3qngg-o8sB_GpHP0WJ2KoW5aQUuc",
      "pubKeyCredParams":[
         {
            "alg":-7,
            "type":"public-key"
         },
         {
         "alg":-257,
        "type":"public-key"
      }
    ],
    "excludeCredentials": [],
    "authenticatorSelection":{
      "requireResidentKey":true,
      "userVerification":"preferred"},
      "attestation":"none",
    "extensions": {}
  }
}

```

**Suggested labels:**
Doc, 5.11.0

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2-extensions/identity-local-auth-fido/pull/57 and https://github.com/wso2/docs-is/pull/2268.
