### ISSUE TITLE
Signature validation failed for SAML Response

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#10366]
**Describe the issue:**
Signature validation failed for SAML Response when configuring SCIM inbound provisioning while federated authentication.

**How to reproduce:**
1) add Identity provider to primary IS and do the following configurations under federated authenticators  ---> SAML2 web SSO configuration
![saml2 sso](https://user-images.githubusercontent.com/31467146/98342744-dfccdd00-2036-11eb-918f-79b23b4d4f63.png)

2) add service provider as travelocity and configure in primary IS
i) Inbound authentication configuration ---> SAML2 web SSO configuration
![saml2 sp sso](https://user-images.githubusercontent.com/31467146/98343275-98931c00-2037-11eb-8a0e-7dabb6c0f58a.png)

ii) under local and outbound authentication configuration ---> advanced configuration
![saml sso adv](https://user-images.githubusercontent.com/31467146/98343581-093a3880-2038-11eb-8ad3-27bf6a8f402c.png)

3) add service provider to 2nd IS and do the following configuration under inbound authentication configuration --> SAML2 web SSO configuration
![smal sso in sp 2nd IS](https://user-images.githubusercontent.com/31467146/98345378-9a121380-203a-11eb-8039-ca4a753fc7a8.png)

4) add IDP to 2nd IS and do the following configs under outbound provisioning connectors ---> SCIM provisioning configuration
![outbound provision](https://user-images.githubusercontent.com/31467146/98345743-13aa0180-203b-11eb-9218-602685f420cc.png) 

**Expected behavior:**
Federated user in the 2nd IS should be authenticated using travelocity app and should be  provisioned user into 1st IS

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 beta 4
 - OS:  Linux
 - Database: H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asgardeotestuser** [comment]
@ShehanDinuka can you try https://stackoverflow.com/a/54852419. It worked for me.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
