### ISSUE TITLE
Documented format of filter parameter is misleading

### ISSUE THREAD

**Issue by anusharp** [wso2/product-is#10374]
**Is your suggestion related to a missing or misleading document? Please describe.**
According to the documentation [1] , the filter parameter value is 'name+operator+<name_value>'. but if this format uses for client ex: swagger-codegen-maven-plugin using java, filter request is failing with incorrect filter pattern (Tested with swagger-codegen-maven-plugin from JAVA Implementation) . The documented filter pattern should be encoded value of the filter pattern 'name operator <value>'. Therefore it is better to mention the actual pattern as 'name operator <value>',  and mentioned filter format is encoded value it.

**Describe the improvement**

Update the filter pattern as  'name operator <name_value>' and mentioned the existing one is encoded filter value.

### Optional Fields

**Additional context**

**Related Issues:**

[1] https://is.docs.wso2.com/en/5.10.0/develop/application-rest-api/#/Applications/getAllApplications

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
