### ISSUE TITLE
Invalid resource access controls for SCIM endpoints 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10378]
**Describe the issue:**

1. `POST` request to `{{base_url}}/scim2/Users/.search endpoint` is used to search users, but in this request matches with the following resource access config in identity.xml.
Even the IS doc says "/permission/admin/manage/identity/usermgt/create" permission is required to do users search using this endpoint(https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Users%20Endpoint/getUsersByPost). I think this should be corrected by adding another resource config for POST request on {{base_url}}/scim2/Users/.search URL as it requires `/permission/admin/manage/identity/usermgt/list` permission and `internal_user_mgt_list` scope. Same thing is applicable for `{{base_url}}/scim2/Groups/.search` and `{{base_url}}/scim2/Roles/.search`

 ```
<Resource context="(.*)/scim2/Users(.*)" secured="true" http-method="POST">
    <Permissions>/permission/admin/manage/identity/usermgt/create</Permissions>
    <Scopes>internal_user_mgt_create</Scopes>
 </Resource>
```

2. The following config is used to define the resource access level of `scim2/Bulk` endpoint. The bulk endpoint can be used *not only* for multiple user resource operations, but also for multiple operations on group/role resources too. So this permission and scopes are not valid. However, this permission/ scope validation might not be done at the authorization valve level because actual operation paths are defined in the body.
 
```
<Resource context="(.*)/scim2/Bulk(.*)" secured="true"  http-method="all">
    <Permissions>/permission/admin/manage/identity/usermgt</Permissions>
    <Scopes>internal_user_mgt_create</Scopes>
    <Scopes>internal_user_mgt_view</Scopes>
    <Scopes>internal_user_mgt_list</Scopes>
    <Scopes>internal_user_mgt_delete</Scopes>
</Resource>
```

**How to reproduce:**
**First ISSUE:**
1. Create a user, Create a role named `User_View` and assign that role to the newly created user. Also assign /permission/admin/manage/identity/usermgt/list` and  `/permission/admin/manage/identity/usermgt/view` permissions to the `User_View` role.
2. Perform a user search operation using  `POST` request to `{{base_url}}/scim2/Users/.search endpoint` authenticating by the created user(who is assigned to  `User_View` eole)
https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Users%20Endpoint/getUsersByPost
3. Response will be 403 forbidden.
4. Assign `/permission/admin/manage/identity/usermgt/create` permission to the `User_View` role and perform the same operation. It will be successful and return 200 OK with the result.
Tryout similarly for Groups and Roles endpoints.

**SECOND ISSUE:**
1. Create a user, Create a role named `BulkOperationRole` and assign that role to the newly created user. Also assign `permission/admin/manage/identity/usermgt` permissions to the `BulkOperationRole` role.
2. Perform a bulk group creation operation using  `POST` request to `{{base_url}/scim2/Bulk` endpoint authenticating by the created user(who is assigned to  `BulkOperationRole`). It will create two groups, but actually the user who perform the operation doesn't have `/permission/admin/manage/identity/rolemgt/create` permissions.
request body:
```
 {
    "schemas": ["urn:ietf:params:scim:api:messages:2.0:BulkRequest"],
    "Operations": [
       {
            "method": "POST",
            "path": "/Groups",
            "bulkId": "ytrewq",
            "data": {
                "schemas": ["urn:ietf:params:scim:schemas:core:2.0:Group"],
                "displayName": "TourGuides"
            }
        },
        {
            "method": "POST",
            "path": "/Groups",
            "bulkId": "ytrewq",
            "data": {
                "schemas": ["urn:ietf:params:scim:schemas:core:2.0:Group"],
                "displayName": "SLTourGuides"
            }
        }
     ]
}
```
 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta6
 - OS:  Linux
 - Database: H2
 - Userstore: LDAP

**Comment by IsuraD** [comment]
https://github.com/wso2/carbon-identity-framework/pull/3244 will address the first part of the issue. In order to support the second part, it is required a major architectural change in rest valve.

**Comment by IsuraD** [comment]
reopened since the second part needs to be addressed

**Comment by ivantha** [comment]
Seems this was closed accidentally.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
