### ISSUE TITLE
User Portal profile update errors are not shown to user

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10379]
**Describe the issue:**
When updating the profile in the user-portal, it displays a message for success flows only. When the SCIM API returns 400 or 500 response code, it does not show anything to the user.

The following errors can be seen in the browser console.
```
main.js?bbc0bab029ee8e943212:2 PATCH https://localhost:9443/scim2/Me 400

main.js?bbc0bab029ee8e943212:2 Uncaught (in promise) Error: Request failed with status code 400
    at createError (main.js?bbc0bab029ee8e943212:2)
    at settle (main.js?bbc0bab029ee8e943212:2)
    at XMLHttpRequest.handleLoad (main.js?bbc0bab029ee8e943212:2)
```

**How to reproduce:**
Log into user-portal and try to update the profile with a scenario where SCIM API returns 500 or 400 status code.

**Expected behavior:**
User should be informed with an error message

**Environment information**
 - Product Version: IS 5.10.0 (This seems to be fixed in 5.11 beta releases with https://github.com/wso2/identity-apps/pull/1136/commits/3620c7a444a47c3f05bc2dfecf96804678cb9545)

**Comment by emswbandara** [comment]
@ShanChathusanda93 please close the issue if already fixed in public. If not. add the milestones

**Comment by ShanChathusanda93** [comment]
Public commit : https://github.com/wso2/identity-apps/commit/3620c7a444a47c3f05bc2dfecf96804678cb9545
