### ISSUE TITLE
Update Dependencies in Identity Apps

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10370]
**Description**
Some of the dependencies that are used in Identity Apps will have to be updated to newer versions. This issue can be used to track the progress of dependency update tasks.

**Tasks**
- [ ] Update to React `v17` (`React 17` has been released and apparently has no breaking changes)
- [ ] Update React Semantic UI to `> v1.x.x` (Current version `^0.87.3` has deprecated hooks which will break in `React 17`)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
