### ISSUE TITLE
Console header refers product version as Beta for version 5.11 Beta 6 SNAPSHOT

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10381]
**Describe the issue:**
Console header refers product version as "Beta" but for the same product /the same user in myaccount as product version it refers "5.11 beta6"

Console:
![image](https://user-images.githubusercontent.com/39120228/98481885-955c8380-2223-11eb-8f1d-d995e9311956.png)

My Account
![image](https://user-images.githubusercontent.com/39120228/98481898-ab6a4400-2223-11eb-95c5-d6220d82cea6.png)

**Expected behavior:**
Bothe My account & Console should refer to the same pattern.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Beta6 SNAPSHOT
 - OS:Mac
 - Database: H2
 - Userstore: LDAP

---

**Comment by brionmario** [comment]
@NilukaSripalim With IS 5.11.0, the Console application will be available as a public beta. Hence the above change was done intentionally.

Relevant  Task - https://github.com/wso2/product-is/issues/10195

**Comment by thanujalk** [comment]
Closing the issue as this is an intentional change we have done as we packing the console as Beta for 5.11.0 release... 
FYI - my account will have the product version
