### ISSUE TITLE
proxy_context_path does not work as expected

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10380]
**Describe the issue:**
The configuration "proxy_context_path" which is toml equivalent for "ProxyContextPath" in XML based configs; is not working as expected. The carbon management console does not work due to a hardcoded CSRF guard javascript path. All the react web apps are not working because they have not taken this config into account.

**Steps to reproduce**
IS configs
```
[server]
hostname = "idp.wso2.com"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}"
proxy_context_path = "auth"

[transport.https.properties]
proxyPort = 443 
```

Nginx configs
```
server {
	listen 443;
	server_name idp.wso2.com;
	client_max_body_size 100M;

	root /usr/share/nginx/www;
	index index.html index.htm;

	ssl on;
	ssl_certificate /etc/nginx/ssl/server.crt;
	ssl_certificate_key /etc/nginx/ssl/server.key;

	location /auth/ {
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_read_timeout 5m;
		proxy_send_timeout 5m;

		proxy_pass https://127.0.0.1:9443/;
		proxy_cookie_path / /auth;
		proxy_redirect https://idp.wso2.com/ https://idp.wso2.com/auth/;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
```
Generate certificates by following "Create SSL certificates" topic of https://docs.wso2.com/display/CLUSTER44x/Configuring+NGINX

Try logging into any of followings using the base URL as https://idp.wso2.com/auth/
- carbon
- user-portal (5.10.0)
- myaccount (5.11.0)
- console (5.11.0)

**Environment information**
 - Product Version:  IS 5.10.0, IS 5.11.0 beta4

**Related**
According to the mail "Deprecating WebContextRoot configuration from WSO2 Identity Server" in dev mailing list, we are going to depreciate WebContextRoot and continue with ProxyContextPath.

**Comment by rksk** [comment]
Additionally, we need to document this once all fixed.

**Comment by IakimLynnyk-TomTom** [comment]
Hi! Is there any chance for it to be implemented in products-is 5.0.11.0?

**Comment by rksk** [comment]
> Hi! Is there any chance for it to be implemented in products-is 5.0.11.0?

These fixes are not shipped with 5.11.0 release, but if you are a subscription holder, you can raise a support case and request. Otherwise you will have to use 6.0 release.

**Comment by rksk** [comment]
Re-opening due to pending items
- myaccount and console fixes
- documentation

**Comment by rksk** [comment]
Pending action items will be tracked in https://github.com/wso2/product-is/issues/15864

**Comment by DInuwan97** [comment]
After nginx 1.10, the `ssl on` is deprected. Hence you can use the following configuration. 

```
server {
	listen 443 ssl;
	server_name idp.wso2.com;
	client_max_body_size 100M;

	root /usr/share/nginx/www;
	index index.html index.htm;

	ssl_certificate /etc/nginx/ssl/server1.crt;
	ssl_certificate_key /etc/nginx/ssl/server1.key;
	
	location /auth/ {
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_read_timeout 5m;
		proxy_send_timeout 5m;

		proxy_pass https://127.0.0.1:9443/;
		proxy_cookie_path / /auth;
		proxy_redirect https://idp.wso2.com/ https://idp.wso2.com/auth/;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
```
