### ISSUE TITLE
[consoleApp] [Manage] Updating permissions of Internal/admin Role via console fails with Error occured while adding permissions error

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10392]
**Describe the issue:**
Updating permissions of Internal/Role fails with error
**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as the tenant admin
3.Go to Manage > Roles > Internal/admin > edit option > permissions tab > 
4. It allows to update the permissions
4. Click on Update

**Observation**
Update fails and gets the below error

Backend console gives below error

`[2020-11-09 13:49:19,089] [d9735c8f-97c6-41fb-a46a-0c8d04801407] ERROR {org.wso2.carbon.user.mgt.UserRealmProxy} - UI permissions of Admin is not allowed to change`

**Environment**
IS 5.11.0 BETA6 SNAPSHOT
mssql 2019 uniqueidjdbc primary db
tenant mode
seondary userstore mariadb 10.4

![permissions1](https://user-images.githubusercontent.com/31848014/98515418-0ede8b00-2291-11eb-8439-b5e2e9e06414.png)

**Comment by kushanb** [comment]
The issue was produced in the below environment as well

**Environment:**
 - Product version: IS 5.11.0 Beta6 Snapshot
 - OS: Mac
 - Database: MySQL 8
 - Userstore: JDBC
 - Tenant mode

**Comment by janakamarasena** [comment]
In the current management console, we don't have an option to change the permissions of the Internal/Admin role. IMO the console application also should align with it.
