### ISSUE TITLE
[consoleApp] [Manage] Updating Groups tab of the role Internal/Admin doesnt reflect the added changes

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10394]
**Describe the issue:**
Updating permissions of Internal/admin fails with error

**How to reproduce:**

1.Access https://localhost:9443/console and create a tenant
2.Login as the tenant admin
3.Go to Manage > Roles > Internal/admin > edit option > Groups tab  > Edit option
4. From the edit view it allows to select the primary/admin from right hand side box .
5. Click on button < 
4. Save

**Observation**
UI says changes updated successfully. If you go back and see it haven't updated.

**Environment**
IS 5.11.0 BETA6 SNAPSHOT
mssql 2019 uniqueidjdbc primary db
tenant mode
seondary userstore mariadb 10.4

![permssions2](https://user-images.githubusercontent.com/31848014/98517009-4cdcae80-2293-11eb-9f4c-639e50eb005b.png)

**Comment by thivi** [comment]
This seems like an API issue. The same issue can be reproduced for any group added to a role. 

Additionally, when a role is removed for a group, all the groups added to that role get removed.

**Comment by tsuresh** [comment]
I was able to reproduce the issue as supertent admin user as well

**Comment by janakamarasena** [comment]
This is a common issue. The API call that is currently sent has a body like this
```
{
    "Operations": [
        {
            "data": {
                "Operations": [
                    {
                        "op": "remove",
                        "path": "roles"
                    }
                ]
            },
            "method": "PATCH",
            "path": "/Groups/7a59b4b6-85e3-4312-a92b-d1b6c6076be6"
        }
    ],
    "failOnErrors": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:BulkRequest"
    ]
}
```

This need to be changed to the following format. 
**[IMPORTANT]Note** This same change needs to be done to the API call that is used to **Remove a role from a group.** It will solve the second issue mentioned [here](https://github.com/wso2/product-is/issues/10394#issuecomment-723921319)

```
{
    "Operations": [
        {
            "data": {
                "Operations": [
                    {
                        "op": "remove",
                        "path": "groups[value eq <value(id) of the group to be removed>]"
                    }
                ]
            },
            "method": "PATCH",
            "path": "/Roles/<id of the role>"
        }
    ],
    "failOnErrors": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:BulkRequest"
    ]
}
```

example:
```
{
    "Operations": [
        {
            "data": {
                "Operations": [
                    {
                        "op": "remove",
                        "path": "groups[value eq c178ef5e-e138-40f8-bac4-d1ca448a927c]"
                    }
                ]
            },
            "method": "PATCH",
            "path": "/Roles/bb40c393-415f-4844-9552-5d661be66ecd"
        }
    ],
    "failOnErrors": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:BulkRequest"
    ]
}
```
