### ISSUE TITLE
The console cannot be accessed if the assigned role only has login/Human Tasks > View Task List /Workflow Management > BPS Profiles >View permissions

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10396]
**Describe the issue:**
Create user and assign role which has login permission, and then try to login to console, getting an error that "unauthorized"

Tested with :
Create the user and assign roles with the following permissions.
Login
Human Tasks > View Task List
Workflow Management > BPS Profiles >View
That user also unable to access console
**How to reproduce:**
Create user 
Add new role with permission Login
Assign role for the created user
Try to login to console 

![image](https://user-images.githubusercontent.com/39120228/98520070-94fdd000-2297-11eb-8d91-9b34c0818335.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Beta6 Snapshot
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by kushanb** [comment]
I also faced the same issue 

**Environment:**
 - Product version: IS 5.11.0 Beta6 Snapshot
 - OS: Mac
 - Database: MySQL 8
 - Userstore: JDBC
 - Tenant mode

**Comment by brionmario** [comment]
Related https://github.com/wso2/product-is/issues/10229
