### ISSUE TITLE
Add auth_time to ID token

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#10391]
**Is your suggestion related to an experience ? Please describe.**
The id token returned in the OIDC code flow doesn't contain the auth_time value if it isn't explicitly requested.

**Describe the improvement**
Add auth_time value to id token

**Specification:**
 https://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
