### ISSUE TITLE
[consoleApp] [Manage] Updating permissions of the Role Internal/System via console fails

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10395]
**Describe the issue:**
Updating permissions of Internal/system fails.

**How to reproduce:**

1.Access https://localhost:9443/console and create a tenant
2.Login as the tenant admin
3.Go to Manage > Roles > Internal/system > edit option > Permissions tab > Select some permisions > Update

![permissions3](https://user-images.githubusercontent.com/31848014/98519493-d80b7380-2296-11eb-8c70-012141435f7c.png)

**Observation**
UI says changes updated successfully. If you go back and see updated permissions are not available.

Environment
IS 5.11.0 BETA6 SNAPSHOT
mssql 2019 uniqueidjdbc primary db
tenant mode
seondary userstore mariadb 10.4

**Comment by thivi** [comment]
Related issue https://github.com/wso2/product-is/issues/10103

**Comment by kushanb** [comment]
I also faced the same issue 

**Environment:**
 - Product version: IS 5.11.0 Beta6 Snapshot
 - OS: Mac
 - Database: MySQL 8
 - Userstore: JDBC
 - Tenant mode

**Comment by ashendes** [comment]
@ShanikaWickramasinghe Is this specific to only this role? Was it possible to set permissions for other roles?

**Comment by ShanikaWickramasinghe** [comment]
@ashendes It was not updating the permissions for a newly created role as well

**Comment by ashendes** [comment]
This issue has been fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/300 and https://github.com/wso2/charon/pull/293. The fix is not included in the BETA6 pack.

**Comment by ashendes** [comment]
This seems to be a UX bug. When all permissions are assigned, unticking a child permission doesn't change the tick of the parent permission checkbox. Have to explicitly untick the parent checkbox to change the child permissions.
