### ISSUE TITLE
Authorization requests with 'response_type=id_token token' fail

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#10407]
**Describe the issue:**
authorization requests to /authorization endpoint with response_type set to `id_token token` fail.

responce: invalid_request, Bad request content type. Expecting: application/x-www-form-urlencoded or application/json 

**How to reproduce:**
send a get request to /authorization endpoint with responce_type=id_token token

**Expected behavior:**
a successful response with an Access Token, an Access Token Type, and an id_token is expected
https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

**Environment information:**
 - Product Version: IS 5.11.0beta5
 - OS: Linux

**Comment by mefarazath** [comment]
@Yasasr1 Can you add the request you used to reproduce this issue?

**Comment by Yasasr1** [comment]
Request : https://localhost:9443/oauth2/authorize?client_id=aHsM3OMaWiJGBnczJBtw0bmEFfka&redirect_uri=https://localhost:8080&scope=openid&state=test&nonce=X3Tp9p6NH3&response_type=id_token%20token
