### ISSUE TITLE
Support backchannel logout mechanism when doing session termination

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10409]
When session termination is done via the session termination API a logout call should go to any apps that support backchannel logout mechanisms.

Related to https://github.com/wso2/product-is/issues/8700

**Comment by LahiruLS** [comment]
Hi Team,
I have created this #10419 for the same. Did some analysis and updated the findings.

**Comment by piraveena** [comment]
It is fixed with https://github.com/wso2/product-is/issues/10419
