### ISSUE TITLE
Could not list roles , in  "Adding a new workflow definition"> "Workflow template: multi-step user / role approval".

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10402]
**Describe the issue:**
unable to list role in Workflow Definition >  "Add Approval Step.", 
If select Domain as "ALL_USER_STORE_DOMAINS" & search it displaying "Internal/admin" only., even if there are roles available in Primary user store -a role with required permissions. 
Tested with tenant and super user

**How to reproduce:**
1. Login to Management console
2. Create 2 roles 
2. 1 Role1 > All permissions
2.2 Role2 > Login
Human Tasks > View Task List
Workflow Management > BPS Profiles >View Permisstions 
3. Add a New Workflow Definition
4. Provide a name for a New Workflow Definition
5. Set the required approval levels. 
6. add an approval level, click Add Approval Step.
7. search a user role in a specific user store, select the Search Roles radio button. or Enter the role name and click Search Roles.
8. roles are not displaying

Roles with required permissions in Primary user store
![image](https://user-images.githubusercontent.com/39120228/98529401-90d7af80-22a3-11eb-98d7-62768e5b1834.png)

Only display when select "ALL_USER_STORE_DOMAINS"
![image](https://user-images.githubusercontent.com/39120228/98529584-ce3c3d00-22a3-11eb-8891-b4bd9f863744.png)

When select Primary User store
![image](https://user-images.githubusercontent.com/39120228/98529741-02176280-22a4-11eb-8a2d-dedeb35993b6.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Beta6 Snapshot
 - OS:  Mac
 - Database:H2
 - Userstore: LDAP

**Comment by IsuraD** [comment]
I think this is expected. @ashensw can you confirm? Don't we support groups here? 

I think we need to track this in the migration client. @Buddhimah

**Comment by Buddhimah** [comment]
As per the issue description, it seems here @NilukaSripalim has created groups not roles. So I think it's expected to not show them when Search roles in the Add workflow path. If we create a role by using internal domain that is getting listed properly in add workflow. So @IsuraD as it seems it does not support groups here.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
