### ISSUE TITLE
[consoleApp] [Manage] Updating permissions of newly created roles via console fails

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10412]
**Describe the issue:**
Updating permissions of newly created roles via console fails

**How to reproduce:**
1. Access https://localhost:9443/console as the super tenant admin
2. Go to Manage > Roles  and create a new Role
3. Go to Manage > Roles > {New Role Name} > edit option > Permissions tab > Select some permissions > Update
4. Go to another tab and return

**Observation:**
UI says changes updated successfully. If you go back and see updated permissions are not available.

**Environment information:**
 - Product Version: IS 5.11.0-Beta6-SNAPSHOT
 - OS: Mac
 - Database: MySQL 8
 - Userstore: JDBC

**Comment by JeethJJ** [comment]
The same behavior was experienced in the following environment as well :

- Product Version: IS 5.11.0-Beta6-SNAPSHOT

- OS: Ubuntu 18.04 LTS

- Database: Maria DB 10.4

- Userstore: JDBC

**Comment by thivi** [comment]
Related to https://github.com/wso2/product-is/issues/10103

**Comment by ashendes** [comment]
This issue has been fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/300 and https://github.com/wso2/charon/pull/293. The fix is not included in the BETA6 pack.

**Comment by NipuniBhagya** [comment]
Closing this as this is fixed in the latest 5.11.0-beta6-SNAPSHOT pack.
