### ISSUE TITLE
[consoleApp] [Manage] A role can't be created with the same name as an existing group

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10416]
**Describe the issue:**
A role cant be created with the same name as a group that has already been created

**How to reproduce:**
1. Login to the console as super tenant admin
2. Go to Console > Manage > Groups  and create a new group (eg: mobile)
3. Go to Console > Manage > Roles and try to create a new role with the same name as the group created in step 2 (eg: mobile)

**Observation:**
Displays the error "A Role already exists with the given Role name"

<img width="726" alt="Screenshot 2020-11-09 at 20 04 24" src="https://user-images.githubusercontent.com/19253380/98555030-70215100-22c7-11eb-84c3-ed0d9673c49d.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 Beta6 Snapshot
 - OS: Mac
 - Database: MySQL 8/ MySQL 5.7
 - Userstore: JDBC

**Comment by janakamarasena** [comment]
The search for the role name existence is being done using the groups search API.

The same request should be done using the Roles search API,

```
https://localhost:9443/scim2/Roles/.search
```

**Comment by thivi** [comment]
Requests to the above endpoint fail with a 500 error. Teh issue is tracked here: https://github.com/wso2/product-is/issues/10439
