### ISSUE TITLE
When user session is terminated from the API there should be mechanisms to alert the relevant apps

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10410]
Currently, when the user session is terminated via the session termination API the relevant apps doesn't get alerted. 
There should be mechanisms available for the app to know that the session is terminated.
Currently, this can only be done via periodic passive auth requests.

Possible solutions to look at

- Providing this capability when backchannel logout is available for applications capable of exposing an endpoint(https://github.com/wso2/product-is/issues/10409)
- Possible use of websockets.

**Comment by piraveena** [comment]
If the applications uses back-channel logouts (saml/ oidc), logout request will be sent for the applications when session termination happens. this is addressed with this issue https://github.com/wso2/product-is/issues/10419

**Comment by piraveena** [comment]
This improvement will resolve this issue as well https://github.com/wso2/product-is/issues/10481. Token will be revoked upon session termination even after this fix https://github.com/wso2/product-is/issues/10481. Hence closing this issue
