### ISSUE TITLE
Improve the product to use admin force password reset scenarios severa at once

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10423]
In the identity server, we can enforce the user to change the password via the admin force password reset. Here we have three methods,
1. Offline method,
2. Via an OTP
3. Via email link

However, we can not use several scenarios at once. For example, even if we enable all three of the above from the resident identity provider the reset via email is getting honored.  We need to improve the flow in a way where it supports multiple methods at once.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
