### ISSUE TITLE
Exception at OIDC application submition

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#10420]
**Describe the issue:**
 Following Error observed at OIDC web application creation

![Selection_999(1153)](https://user-images.githubusercontent.com/39077751/98566586-ef695180-22d4-11eb-8594-c0feb8947933.png)

**Comment by thivi** [comment]
This issue has been fixed in 5.11.0-Beta6-SNAPSHOT
![image](https://user-images.githubusercontent.com/20745428/98589978-24d16780-22f4-11eb-8bc2-6adc5ca24904.png)
