### ISSUE TITLE
Login screen for applications doesn't load when token binding type is set to None from console

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10431]
**Describe the issue:**
**Issue 01**
The login screen for applications doesn't load when the token binding type is set to "None" from console. An exception gets thrown in the terminal. [1]
It works when the binding type is changed using the management console

**Issue 02**
The change of binding type to none done from the console doesn't get displayed in the management console.
The change of binding type to none done from the management console doesn't get displayed in the console. 

**How to reproduce:**

**Issue 01:**
1. Login to console as admin
2. Go to Develop > Applications > My Account > Access > OIDC
3. Scroll down to Access token and change the Token binding type to none
4. Logout and try to login to My Account (https://localhost:9443/myaccount)

**Issue 02:**

5. Login to management console as admin
6. Go to Home > Identity > Service Providers > List and click edit on My Account
7. Go to Inbound Authentication Configuration > OAuth/OpenID Connect configuration and click edit
8. Scroll down to Access token binding type and observe issue 02
9. Change type to none and update
10. Retry step 4
11. Redo steps 1 and 2 and scroll down to Access token and observe the Token binding type

**Observation:**
 - The screen is left blank and step 4 and an exception is thrown [1]
 - Successfully logs in to My Account at step 10 when the token binding type is set at the management console
 - None of the radio buttons are selected at step 8 and step 11 [2][3]

**Stack Trace:**
[1] - Exception thrown

```
[2020-11-10 12:13:14,454] [417550ce-3356-42b8-8f74-376e5c854c11] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : MY_ACCOUNT, User ID null, Scope : [] and Grant Type : authorization_code org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Token binder for the binding type: None is not registered.
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.handleTokenBinding(AccessTokenIssuer.java:422)
```

**Screenshots for Issue 02:**
[2] - At step 8

<img width="753" alt="Screenshot 2020-11-10 at 13 39 10" src="https://user-images.githubusercontent.com/19253380/98646990-33526a00-235a-11eb-847b-396773ba4bf3.png">

[3] - At step 11

<img width="684" alt="Screenshot 2020-11-10 at 13 38 12" src="https://user-images.githubusercontent.com/19253380/98647010-3baaa500-235a-11eb-8e68-05d1de74802c.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta6 Snapshot
 - OS: Mac
 - Database: MySQL8
 - Userstore: JDBC

**Comment by brionmario** [comment]
This happens due to the `Console` setting binding type to `None` which is not a valid type. `bindingType` attribute should be dropped altogether when `none` is selected.
