### ISSUE TITLE
Instruction for using sample playground App for testing authorization code grant is missing in the documentation

### ISSUE THREAD

**Issue by neethuvv** [wso2/product-is#10430]
**Is your suggestion related to a missing or misleading document? Please describe.**
I could not test the authorization code grant type of oauth2 since the instructions for setting up sample playground application was missing from the documentation.
**Describe the improvement**

 Add the instructions for using the sample playground webapp for testing authorization code grant and implicit grant. 

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
