### ISSUE TITLE
Login screen for applications not loading when browser cookies are blocked 

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10435]
**Describe the issue:**
The login screen doesn't load and stays blank for My Account and Console when browser cookies are blocked in Chrome. The issue is possibly caused by the SDK being unable to access the session storage. 

**How to reproduce:**
1. Go to Settings > Privacy and Security > Cookies and other site data in Chrome
2. Scroll down to the bottom and add the URL of the IS (https://localhost:9443/) to "Sites that can never use cookies"
3. Try to login to My Account

Alternatively, do the following before step 1 if the issue isn't reproduced:
 1. Login to Management Console as admin user
 2. Go to Home > Identity > Service Providers > List and click edit on My Account
 3. Go to Inbound Authentication Configuration > OAuth/OpenID Connect configuration and click edit
 4. Scroll down to Access token binding type and change the type to "None" and update
 5. Do the original 3 steps

**Observation:**
The below errors are logged in the developer tools console in Chrome

<img width="554" alt="Screenshot 2020-11-10 at 12 56 26" src="https://user-images.githubusercontent.com/19253380/98656199-6d296d80-2366-11eb-8bc7-8df09812c6fd.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta6 Snapshot
 - OS: Mac
 - Browser: Chrome
 - Database: MySQL8
 - Userstore: JDBC

**Comment by thivi** [comment]
Disabling third-party cookies in Chrome disables both the session storage and local storage.
https://stackoverflow.com/a/31155355/12551025
