### ISSUE TITLE
Add Country attribute to SCIM2 user core dialect

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#10434]
**Describe the issue:**
At the moment even though we have the attribute http://wso2.org/claims/country in the local dialect we don't have a SCIM attribute aligned with it. So it's better to add a new SCIM attribute and map it to the local attribute.

**Comment by janakamarasena** [comment]
Resolved with 

- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/310
- https://github.com/wso2/carbon-identity-framework/pull/3246

example
```
"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
        "country": "Sri Lanka"
    }
```
