### ISSUE TITLE
Need to update google provisioning doc with recent Gsuite dashboard changes

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#10438]
**Is your suggestion related to a missing or misleading document? Please describe.**
Gsuite dashboard has changed  it dashboard view now. Need to update this https://is.docs.wso2.com/en/5.11.0/learn/outbound-provisioning-with-google/#configuring-google doc with the recent changes

**Comment by tsuresh** [comment]
I've added the instructions on adding new scopes to API clients in the new GSuite console.
Please check issue #10405

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
