### ISSUE TITLE
Unable to view profile of PRIMARY users if a secondary userstore is having a connectivity issue

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10447]
### **Description**
When we request attributes, it searches through all the user stores with the given user id. If one of the userstores is having some issue, the users on other user stores even won't work. This might be addressed by gracefully handling errors than breaking the full iterative search.

### **How to reproduce:**
* Configure JDBC primary userstore as `database_unique_id` and a secondary userstore with `read_write_ldap_unique_id`.
* Shutdown the secondary LDAP userstore.
* Create a user in the PRIMARY userstore.
* Try to view the user profile of the newly created user on the primary userstore from the management console.
* It will show an error on the UI and carbon logs will show the connectivity error to LDAP.
* Also, try listing users across all domain or try adding a new user to the primary userstore via SCIM. It will give an Internal Server error.
* Disable the secondary user store and try again. The all the above steps will work without any issues.

### Cause
Not having an entry in the `UM_UUID_DOMAIN_MAPPER` table.

### **Environment information**
 - Product Version: IS 5.11.0 RC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
