### ISSUE TITLE
Identity Provider Management API Not working

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#10448]
**Describe the issue:**

The API getIDPs [1] is not working when the identity server is configured with a oracle database.

This is causing due the missing fields of the SQL defined here [2]. In the outer SQLs there were three fields (IMAGE_URL, UUID, TENANT_ID ) select or use in the where clause. However those are not return from the inner SQL.

**Faulty.**
`
public static final String GET_IDP_BY_TENANT_ORACLE = "SELECT NAME, IS_PRIMARY, HOME_REALM_ID, DESCRIPTION," +
" IS_FEDERATION_HUB, IS_LOCAL_CLAIM_DIALECT, IS_ENABLED, DISPLAY_NAME, ID, IMAGE_URL, UUID FROM " +
"(SELECT ID, NAME, IMAGE_URL, UUID, IS_PRIMARY, HOME_REALM_ID, DESCRIPTION, IS_FEDERATION_HUB, " +
"IS_LOCAL_CLAIM_DIALECT, IS_ENABLED, DISPLAY_NAME, ROWNUM AS rnum FROM (SELECT ID, NAME, IS_PRIMARY," +
" HOME_REALM_ID, DESCRIPTION, IS_FEDERATION_HUB, IS_LOCAL_CLAIM_DIALECT, IS_ENABLED, DISPLAY_NAME FROM " +
"IDP ORDER BY %s) WHERE ";
`

**Corrected.**
`
public static final String GET_IDP_BY_TENANT_ORACLE = "SELECT NAME, IS_PRIMARY, HOME_REALM_ID, DESCRIPTION," +
" IS_FEDERATION_HUB, IS_LOCAL_CLAIM_DIALECT, IS_ENABLED, DISPLAY_NAME, ID, IMAGE_URL, UUID FROM " +
"(SELECT ID, NAME, IMAGE_URL, UUID, IS_PRIMARY, HOME_REALM_ID, DESCRIPTION, IS_FEDERATION_HUB, " +
"IS_LOCAL_CLAIM_DIALECT, IS_ENABLED, DISPLAY_NAME, ROWNUM AS rnum FROM (SELECT ID, NAME, IMAGE_URL, UUID, IS_PRIMARY," +
" HOME_REALM_ID, DESCRIPTION, IS_FEDERATION_HUB, IS_LOCAL_CLAIM_DIALECT, IS_ENABLED, DISPLAY_NAME, TENANT_ID  FROM " +
"IDP ORDER BY %s) WHERE ";
`

**How to reproduce:**

Configure the IS 5.10 pack with Oracle database and make the get request to list the IDPs using the API [1]

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - OS: [Windows, Linux, Mac]
 - Database: [Oracle]
 - Userstore: [N/A]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

---
[1] https://is.docs.wso2.com/en/5.10.0/develop/idp-rest-api/#/Identity%20Providers/getIDPs
[2] https://github.com/wso2/carbon-identity-framework/blob/527dba704487431b95c34461656cdb7496a0f0cc/components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/util/IdPManagementConstants.java#L84https://github.com/wso2/carbon-identity-framework/blob/527dba704487431b95c34461656cdb7496a0f0cc/components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/util/IdPManagementConstants.java#L84

**Comment by emswbandara** [comment]
Fixed in public via https://github.com/wso2/carbon-identity-framework/pull/2821
