### ISSUE TITLE
[IS 5.11] update documentation on new auth claim for introspection validation response

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-is#10457]
**Is your suggestion related to a missing or misleading document? Please describe.**

**Describe the improvement**
A new standard claim `aut` is added for introspection endpoint response for both opaque and JWT tokens. `aut` is the authorized user type which could either be `APPLICATION` or `APPLICATION_USER`.

Need to update the sample token validation responses in https://is.docs.wso2.com/en/5.11.0/learn/invoke-the-oauth-introspection-endpoint/ docs 

Related to https://github.com/wso2/product-is/issues/9366

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
