### ISSUE TITLE
Integrating OIDC compliance suite with IS build

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10450]
**Is your feature request related to a problem? Please describe.**
OpenID Connect is an identity layer that is built on top of Oauth 2.0. It enables the clients to identify their users depending on the authentication carried out by an identity server, also it allows them to obtain basic profile information about the users.

[OpenID Connect Compliance Test Suite](https://gitlab.com/openid/conformance-suite) is intended to validate deployments of products or services which implement certain conformance profiles of OpenID Connect protocol. 

The purpose of this project is to integrate and run the OIDC compliance suite during Identity Server build time so that we can detect any spec violations as early as possible.

Currently IS is compliant with basic, implicit, and hybrid profiles.

**Describe the solution you would prefer**
Integrate running OIDC compliance to IS build pipeline

Sub Tasks

- [x] [Run conformance suite manually against the latest milestone and identify any failures](https://github.com/wso2/product-is/issues/8301)
- [ ] [Fix identified issues](https://github.com/wso2/product-is/issues/10408)
- [x] Automate conformance suite run
- [x] Automate conformance suite run after milestone releases
- [x] Enable notifications for conformance suite runs (chat or email)
- [ ] Integrate conformance suite as a pre-release step

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
