### ISSUE TITLE
User Session persistence with a scalable, highly available data store

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#10453]
Data records like sessions have limited lifespan, need reliable storage, tend to grow exponentially and need to be efficiently accessible as it's an integral part of the authentication flow. Currently the Identity Server session implementation is backed by RDBMS, but with large scale deployments its better to research on $subject have alternate option.

There are existing in-memory, non-volatile data storage solutions like Redis. Such technologies should be evaluated, and pick the best fit would be used to implement a session storage solution for Identity Server.

**Comment by sthenusan** [comment]
- The session data store is implemented as pluggable with the changes done with the [feature branch](https://github.com/wso2/carbon-identity-framework/tree/feature-decouple-session-data-layer-without-redis). 
- Redis based SessionDataStore Incubator is implemented in the [identity-session-data-store-redis](https://github.com/wso2-incubator/identity-session-data-store-redis).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
