### ISSUE TITLE
UX issue in console app role permission tree

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10469]
When permission is added it cannot be easily removed.

![cK8BK3YhOA](https://user-images.githubusercontent.com/11583571/98830973-02a92800-2461-11eb-9548-32530647d4d2.gif)

**Comment by DimalChandrasiri** [comment]
The current tree implementation has limitations which leads to unexpected behaviour. ( i.e the above issue ) Since this, we will be implementing a newer plugin with much more functionality. 

Plugin to be used : [RC-Tree](https://www.npmjs.com/package/rc-tree)
