### ISSUE TITLE
Login error displayed when the number of allowed failed attempts exceeds should be changed

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10467]
**Is your suggestion related to an experience ? Please describe.**

The error message displayed when the account is locked after the number of failed login attempts has exceeded is the same as for entering incorrect credentials (even when the correct username and password are given)

<img width="480" alt="Screenshot 2020-11-11 at 19 42 51" src="https://user-images.githubusercontent.com/19253380/98821860-18652000-2456-11eb-8763-f33688d73e10.png">

**Describe the improvement**

An error stating that the account is locked due to the number of allowed failed attempts exceeding can be displayed instead

**Comment by janakamarasena** [comment]
This could be done by purpose so username enumeration is not possible.

**Comment by IsuraD** [comment]
We can enable showAuthFailure reason to get the account lock reason and customize authentication endpoint webapp to cater to different error messages if needed.
