### ISSUE TITLE
Modifying service provider application owner when the owner is deleted from IS.

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#10466]
**Describe the issue:**
When creating a service provider in IS, the creating user is set as the service provider entity's owner. If the user who owns a service provider is deleted, there should be a way to update the owner of the service provider applications owned by that deleted user. When updating the service provider, we check whether the owner exists [1]. As a temporary fix, when updating the service provider, if the owner does not exist, the tenant admin is set as the service provider owner[2]. However, a proper implementation to address this scenario should be in place.
Related to : https://github.com/wso2/product-is/issues/6639

[1] https://github.com/wso2/carbon-identity-framework/blob/8e59b42eaddf55921f566f2b73884c1985072118/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java#L686
[2] https://github.com/wso2/carbon-identity-framework/pull/3247

**How to reproduce:**
1. Create a service provider with userA
2. Assign new application role to userB
3. Delete userA (application owner)

**Expected behavior:**
The owner of the service provider should be updated to an exiting user with the application role of the SP.

**Comment by pandukakarunasena** [comment]
Updating the IDN_OAUTH_CONSUMER_APPS should be fixed in IS 5.11.0-latest
