### ISSUE TITLE
[DOC] Update REST API docs of user functionality 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10474]
The yaml was changed by https://github.com/wso2/identity-api-user/pull/115. Therefore, the docs need to be updated.

**Comment by sherenewso2** [comment]
The swagger doc for this yaml is generated by directly pulling the yaml from the identity-api-user repo. Therefore, any changes to the yaml will be automatically reflected in the doc space. 

[1] https://is.docs.wso2.com/en/5.11.0/develop/user-functionality-mgt-rest-api/#/
