### ISSUE TITLE
Properly handle less privileged users inside Console features

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10473]
**Is your suggestion related to an experience ? Please describe.**
Graceful navigation had been implemented for Console features with https://github.com/wso2/identity-apps/pull/1373. But some features rely on each other and the access should be handled properly for those.

Ex: Users features requires proper permissions for Groups, Roles & User Sessions to access the relevant APIs.

**Describe the improvement**
Do the proper access validation from inside the features and hide the relevant views based on the permission levels.

**Comment by DimalChandrasiri** [comment]
Currently the fine grain permission checking is not yet implemented. As suggested by @IsuraD @ayshsandu we will need to implement in-depth permission/scope checking for each action/UI feature individually.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
