### ISSUE TITLE
Deleted user auto logged as Admin in myaccount

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10480]
**Describe the issue:**
If a user already logged in to myaccount and got deleted from console will automatically logging as Admin in myaccount. This happens because once the user got delete also the browser keeps its session.
 
**How to reproduce:**

1. Go to the console as Admin and create a User
2. Log in to myaccount from the created user in console
3. While user logged into myaccount go to console and delete the user
4. Check the myaccount. User auto-logged as Admin.

**Expected behavior:**
Once the User deletes from the console, the user should be redirected to the sign-in page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0-beta6-Snapshot
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Suggested labels:**
Priority/Normal
Severity/Minor

**Comment by ayshsandu** [comment]
In the above step 2, when myaccount is accessed in the same browser, admin should be logged in via SSO. If that's not the behaviour need to check why SSO is not working.

**Comment by ayshsandu** [comment]
Tested the flow, SSO is working properly. If the user is deleted by an admin from a different device, he will be logged out from myaccount.
