### ISSUE TITLE
Need to add documentation on SameSite cookie handling

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#10489]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently WSO2 IS has support to handle SameSite cookies, but we don't have a proper documentation in our doc space related to SameSite cookie support in WSO2 IS.

** References **
[1] https://github.com/wso2/product-is/issues/7477
[2] https://wso2.com/blogs/thesource/2020/01/samesite-attribute-support-in-wso2-products/

**Comment by DMHP** [comment]
https://github.com/wso2/docs-is/pull/2246

**Comment by dewniMW** [comment]
the document needs to be added in IS 5.10.0 doc space as well.

**Comment by dewniMW** [comment]
@DMHP is the below provided configuration documented in IS. 5.11.0 doc space?

```
[catalina.valves.valve.properties]
className = "org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve"
```
I couldn't see any reference in [1] related to this.

[1] https://is.docs.wso2.com/en/5.11.0/administer/samesite-attribute-support/

**Comment by rksk** [comment]
This is not required for 5.12.0 doc space since the valve is added by default.

https://github.com/wso2/product-is/pull/11137/files
