### ISSUE TITLE
Endpoints with a basePath

### ISSUE THREAD

**Issue by giovanni-depalma** [wso2/product-is#10496]
Fronting with the Nginx load balancer it's complex without a dedicated domain for the identity server, where you have to write a specific configuration that exposes various endpoints

I followed the guide https://is.docs.wso2.com/en/5.9.0/setup/fronting-with-the-nginx-load-balancer/ but I observed 

- the endpoints in the guide are incomplete 
- the endpoints are too many, with easy collisions with other services 

For example my current configuration is: 

`

      location /oauth2/token {
        proxy_pass https://is.wso2/oauth2/token;
      }

      location /commonauth {
        proxy_pass https://is.wso2/commonauth;
      }

      location /logincontext {
        proxy_pass https://is.wso2/logincontext;
      }

      location /oauth2/authorize {
        proxy_pass https://is.wso2/oauth2/authorize;
      }

      location /authenticationendpoint/ {
        proxy_pass https://is.wso2/authenticationendpoint/;
      }

      location /oauth2/userinfo {
        proxy_pass https://is.wso2/oauth2/userinfo;
      }

      location /oauth2/jwks {
        proxy_pass https://is.wso2/oauth2/jwks;
      }

      location /oauth2/oidcdiscovery {
        proxy_pass https://is.wso2/oauth2/oidcdiscovery;
      }

      location /oidc {
        proxy_pass https://is.wso2/oidc;
      }

      location /carbon {
        proxy_pass https://is.wso2/carbon;
      }

      location /console {
        proxy_pass https://is.wso2/console;
      }

      location /myaccount {
        proxy_pass https://is.wso2/myaccount;
      }

      location /api/server {
        proxy_pass https://is.wso2/api/server;
      }

      location /api/users {
        proxy_pass https://is.wso2/api/users;
      }

      location /scim2 {
        proxy_pass https://is.wso2/scim2;
      }

      location /t {
        proxy_pass https://is.wso2/t;
      }
`

**Describe the solution you would prefer**
All endpoints could be have a basePath (optionally configurable), so the configuration could be

`

      location /wso2-is {
          proxy_pass https://is.wso2/wso2-is;
      }

`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
