### ISSUE TITLE
[ConsoleApp] Wrong error message displayed when accessing Approvals page without the required permission

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10495]
**Describe the issue:**

The Approvals page is visible even for users who don't have the permissions required for handling workflow operations. When accessing the page the error message "Something went wrong: Could not retrieve pending approvals" was displayed. 

**How to reproduce:**

1. Login to management console as admin of tenant
2. Go to Home > Identity > Users and Roles > Add > Add new role
3. Create a role "nonapproval" in the domain "internal"
4. Allow all the Admin permissions except the following and finish
      - Manage > Human Tasks > View tasks list
      - manage > Identity > Workflow management > BPS Profile
5. Create a new user with only the nonapproval role assigned
7. Setup a workflow according to the documentation [1][2]
6. Login to the console with the user created in step 5
7. Go to Manage > Approvals

[1] - https://is.docs.wso2.com/en/5.11.0/learn/adding-a-new-workflow-definition/
[2] - https://is.docs.wso2.com/en/5.11.0/learn/engaging-a-workflow-in-an-operation/

**Expected behavior:**

Either
 - A proper error explaining that the user doesn't have permission to access the page should be displayed or
 - Approvals page should not be visible to users without permission

**Observation:**

<img width="1440" alt="Screenshot 2020-11-12 at 14 29 43" src="https://user-images.githubusercontent.com/19253380/98932938-05aa2400-2506-11eb-895f-400f2a60568a.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta6 Snapshot
 - OS: Mac
 - Database: MySQL8
 - Userstore: JDBC
 - Tenant 

---

### Optional Fields

**Suggested labels:**

console

**Comment by brionmario** [comment]
Related https://github.com/wso2/product-is/issues/10229 & https://github.com/wso2/product-is/issues/10396

Fixed with the following PRs

Framework - wso2/carbon-identity-framework#3248
Identity Apps - https://github.com/wso2/identity-apps/pull/1373
