### ISSUE TITLE
Photo-view app doesn't return photo album.

### ISSUE THREAD

**Issue by katsonis** [wso2/product-is#10499]
I am trying to access photo-edit and photo-view apps with 'admin' credentials and with the suggested ones from here https://is.docs.wso2.com/en/5.11.0/learn/configuring-access-delegation-with-uma/. Sample apps both runs fine, album policy was created successfully, but in photo-view app there is no album after sharing. Any suggests?
I am using WSO2 IS 5.9.0 and Apache Tomcat 8.5.47.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
