### ISSUE TITLE
Self registered users via the REST API doesn't get redirected to the login page properly after confirmation

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#10504]
**Describe the issue:**
We need to update callback property value in the CURL command which is used to self-register a user as given below.

Page source: https://docs.wso2.com/display/IS510/apidocs/self-registration/#!/operations#SelfRegister#mePost

curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"user": {"username": "kim","realm": "PRIMARY", "password": "Password12!","claims": [{"uri": "http://wso2.org/claims/givenname","value": "kim" },{"uri": "http://wso2.org/claims/emailaddress","value": "kim.anderson@gmail.com"},{"uri": "http://wso2.org/claims/lastname","value": "Anderson"},{"uri": "http://wso2.org/claims/mobile","value": "+947721584558"} ] },"properties": [{"key":"callback","value": "**https://localhost:9443/myaccount/login**"}]}' "https://localhost:9443/api/identity/user/v1.0/me"

**Preview**
![image](https://user-images.githubusercontent.com/30111554/99049305-b2df7380-25bc-11eb-8853-503fb9d2f3f4.png)

**Expected behavior:**
The users should be successfully redirected to the login page after the account confirmation.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

**Comment by gomathyk** [comment]
Modified https://docs.wso2.com/display/IS511/apidocs/self-registration/#!/operations#SelfRegister#mePost.
