### ISSUE TITLE
Changing the offset of the IS from the deployment.toml doesn't get applied to Console and My Account

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10514]
**Describe the issue:**
Changing the port by changing the offset in the deployment.toml doesn't get applied to the Console and the My Account applications.

Possible cause: 
The port in the callback URLs for the apps and the resident identity provider not getting changed

**How to reproduce:**
1. Change the offset by adding the following config to the deployment.toml
```
[server]
offset=2
```
2. Start the server
3. Access the console app from https://localhost:9445/console
4. Access the my account app from https://localhost:9445/myaccount

**Observation:**
The following was displayed

<img width="1440" alt="Screenshot 2020-11-13 at 19 34 53" src="https://user-images.githubusercontent.com/19253380/99080419-4fb70680-25e7-11eb-82d9-26d6a014b85a.png">

**Steps to fix from the management console:**
1. Login to management console from https://localhost:9445/
2. Go to Home > Identity > Identity Providers > Resident > Inbound Authentication Configuration > OAuth2/OpenID Connect Configuration
3. Change the port number of "Identity Provider Entity ID" according to the offset (eg: https://localhost:9445/oauth2/token )
4. Go to Home > Identity > Service Providers > List > Console > Edit
5. Open Inbound Authentication Configuration > OAuth/OpenID Connect Configuration > Edit
6. Change the port of the callback URL similar to step 3 (eg: https://localhost:9445/console/login) and update
7. Similarly go to Home > Identity > Service Providers > List > My Account > Edit
8. Open Inbound Authentication Configuration > OAuth/OpenID Connect Configuration > Edit
9. Change the port of the callback URL similar to step 3 (eg: https://localhost:9445/myaccount/login) and update

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta6 Snapshot
 - OS: Mac
 - Database: MySQL8
 - Userstore: JDBC

**Comment by ayshsandu** [comment]
Fixed in following PRs:
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1518
- https://github.com/wso2/identity-apps/pull/1452

**Comment by ThaminduDilshan** [comment]
Should be covered with docs

**Comment by madurangasiriwardena** [comment]
I don't think asking anyone to go the management console is an option.
