### ISSUE TITLE
Getting an Error when click on Attribute Tab in "wso2carbon-local-sp"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10513]
**Describe the issue:**
Getting an Error when clicking on Attribute Tab in "wso2carbon-local-sp"
Tested with Tenant user
**How to reproduce:**
Login to Console 
Click on Attribute Tab in "wso2carbon-local-sp" Console > Applications

![image](https://user-images.githubusercontent.com/39120228/99082710-82163300-25ea-11eb-917c-e7c072fc3357.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Pre RC
 - OS:Mac
 - Database: Oracle19c , H2
 - Userstore:  LDAP, JDBC

---

**Comment by NipuniBhagya** [comment]
Ideally, the application REST API endpoint should not return the wso2carbon-local-sp. We have created an issue to track this. https://github.com/wso2/product-is/issues/9682

**Comment by ayshsandu** [comment]
With the fix provided for https://github.com/wso2/product-is/issues/9682, `wso2carbon-local-sp` is no longer retrieved in the Applications lists API. It is not displayed in the Console any more.
