### ISSUE TITLE
[Migration] Non Scim2 Role (5.3.0 )will be not be converted to group during Migration

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#10524]
**Describe the issue:**
When migrating from 5.3.0 to 5.11.0. If we havent enabled SCIM in 5.3.0 User store when we migrated to 5.11 We cannot list the roles. Hence there should be a UserGroupMigrator to get the roles from all user stores and then migrate them to IDN_SCIM_GROUP Table. 

---

**Comment by gomathyk** [comment]
https://is.docs.wso2.com/en/latest/setup/migrating-userstore-managers/
