### ISSUE TITLE
IS 5.10.0 documentation is not found

### ISSUE THREAD

**Issue by anusharp** [wso2/product-is#10526]
**Is your suggestion related to a missing or misleading document? Please describe.**
1. Link is missing  for 5.10.0 version in this page
https://is.docs.wso2.com/en/versions/
After clicking clicking the 5.10.0 documentation, it goes to blank page

2. documentation is not load for 5.10.0 for in the right corner drop down list in here ex: https://is.docs.wso2.com/en/5.11.0/learn/configuring-ws-federation-single-sign-on/#!

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2235.
