### ISSUE TITLE
Add custom domain origin support in Owasp.csrfGuard implementation and template configs.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#10523]
**Description:**
Need to implement custom domain origin support in Owasp.csrfGuard implementation. The fix [1] is already available within the master branch.  However, this implementation is not there in the git branch tag which is used in the product.

Also, it is required to template the following 2 configs in Owasp.csrfGuard.carbon.properties so that their values can be changed via deployment.toml
- org.owasp.csrfguard.JavascriptServlet.domainStrict
- org.owasp.csrfguard.JavascriptServlet.refererMatchDomain

**Related Issues:**
https://github.com/wso2/product-apim/issues/6871

**Comment by emswbandara** [comment]
@dewniMW is this a backport? if so, please link to the public PR/git issue

**Comment by dewniMW** [comment]
The public fix: https://github.com/wso2/WSO2-OWASP-CSRFGuard/commit/96920587b1c4b944e6e618cafaa0721642196a00
