### ISSUE TITLE
Invoking scim2/ResourceType with admin credentials gives unauthorized response

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#10529]
Invoke curl -v -k --user admin:admin https://localhost:9443/scim2/ResourceType

Results in  
HTTP/1.1 401 
< WWW-Authenticate: realm user=""

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
