### ISSUE TITLE
Inconsistency with the display-name in user-portal/myaccount

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10528]
**Describe the issue:**
When we login to the user-portal, we build the display-name to show the welcome message and top-right-corner buttons in the following logic at [1]. If the first one is empty, the username is used instead.

When we just login and got id_token
- DisplayName claim
- Username

After, it successfully invokes SCIM Me endpoint
- SCIM.FirstName + SCIM.LastName
- Username

Due to the above hard-coded logic [1], we have no way to control the derived display-name after the SCIM Me invocation. It is inconsistent because we use displayName claim from id_token but not from SCIM Me response.

**How to reproduce:**
- Create a user with firstName, lastName, and displayName claims filled
- Login to user-portal/myaccount
- When you just login, it will show the displayName in the welcome message
- But quickly it will be switched to firstName + lastName

**Expected behavior:**
The claims we pick to display the user logged in should be consistent across API calls. If it's the display name claims returned from id_token being used, the same claim from SCIM response should be used.

A few suggestions for the order. 
01
- displayName
- firstName + lastName
- username

02
- firstName + lastName
- displayName
- username

03
- firstName + lastName
- login identifier (when multi-attribute login is supported)

**Environment information**
 - Product Version: IS 5.10.0, IS 5.11.0 RC1

[1] https://github.com/wso2/identity-apps/blob/bbe025c16841aa7481c3ae3357fab2e3db1261ba/apps/myaccount/src/helpers/user.ts#L29

**Comment by malithie** [comment]
IMO, as we have a display name option now we can go with option 1 above.
Yet, in future, I don't think we should keep such additional attribute to relate the user. Rather first name and last name claims can be used. And we should move towards option 3

**Comment by ShanChathusanda93** [comment]
In order to maintain the backward compatibility we have introduced a configuration in the 5.10 fix. By setting this to true we can enable the profile displayName to be displayed in the user-portal.

**Comment by emswbandara** [comment]
Re-opened until doc PRs are merged

**Comment by ShanChathusanda93** [comment]
Doc PR is merged. Hence closing the issue.
