### ISSUE TITLE
Localization for messages returned from backend

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10522]
**Describe the issue:**
In the document [1], it has been mentioned that `Get the message "oauthErrorMsg" from URL and do URLDecode`. But it is not practical for a developer to find out all the possible error messages that might come in each different flows. Therefore, it is better to have a list of phrases that need to be translated and it should be improved with each new error message we add to the code.

Additionally, this process will be affected by the issue https://github.com/wso2/product-is/issues/3865 as well.

[1] https://is.docs.wso2.com/en/latest/develop/localization-support-in-identity-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
