### ISSUE TITLE
Identity Verification with EvidentID

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#10525]
**Is your feature request related to a problem? Please describe.**
Perform the required improvements to the existing Evident connector [1][2].

- [ ] Capability to define verification attributes from the management console. 
  - ATM, the connector asks to validate the US Drivers License of the user. This needs to be able to configurable from the UI. One approach to this would be having a drop-down list of verification attributes provided by Evident. There could be more user-friendly/efficient ways to get this done.
- [ ] Current connector pulls the name of the verified user from Evident and matches it with the name given to the WSO2 side. This should also be able to either change or enable/disable. Need to discuss further.
- [ ] Extend Evident connector use cases.
  - ATM, the connector can only be engaged in the self-registration flow. But there could be more use cases that we can use IDV.
 
[1] - https://store.wso2.com/store/assets/isconnector/details/1a85a226-177c-4a90-8da3-b142c46ae658
[2] - https://github.com/wso2-extensions/identity-verification-evident/tree/v1.0.0/docs
[3] - https://everything1know.wordpress.com/2020/06/03/identity-verification-with-wso2-identity-server-and-evident-id/

**Comment by EANimesha** [comment]
I'm working on this

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
