### ISSUE TITLE
Ability the user's to register their FIDO devices during the authentication

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10537]
During MFA with FIDO, It is nice to have an option for the end-users to register their FIDO devices during the authentication.
This is already available in the Email OTP and the SMS OTP. The user is able to fill in their email address or the mobile number during the authentication.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
