### ISSUE TITLE
"An Overview of Symmetric Encryption" Page should be Improved

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#10535]
**Describe the improvement**
- The page should be formatted accordingly.
- The content is a bit unclear, ex: A topic like "Follow the steps given below to enable symmetric encryption." is there. But it is mentioned the feature is enabled by default. So there is a conflict.

**Comment by gomathyk** [comment]
Modified https://is.docs.wso2.com/en/latest/administer/symmetric-overview/.
