### ISSUE TITLE
Issues in Governance Connectors UI in Console

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10549]
**Describe the issue:**
Governance connectors UI in the Console is implemented to be data driven. But currently, Governance API doesn't support any metadata regarding the fields hence some front end level decisions have been made in order to figure out the property field type etc.

The following logic determines if a toggle or input has to be rendered based on the property value.

```ts
const getFieldComponent = (property: ConnectorPropertyInterface) => {
    if (property.value === "true" || property.value === "false") {
        return RenderToggle;
    } else {
        return RenderInput;
    }
};
```

The problem with this is, if you enter `true` or `false` to any of the input fields, it'll convert to a toggle element and this is irreversible unless you change it to a value other than true or false using the API.

**How to reproduce:**
1. Go to Console -> Manage -> User Onboarding.
2. In `Lite User Registration`, Enter **true** for **Manage Lite-Sign-Up purposes** input field.
3. Observe that the UI element being transformed to a toggle.

<img width="496" alt="Screen Shot 2020-11-19 at 10 16 41 AM" src="https://user-images.githubusercontent.com/25959096/99628111-82378800-2a5b-11eb-8216-22c4552f3b34.png">

**Expected behavior:**
It should remain an input & API should provide necessary metadata regarding the type of the input field.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-RC1
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
