### ISSUE TITLE
Under using Google API for OTP.The file path "<IS_HOME>/repository/conf/identity/deployment.toml" you specified in section 14 does not exist.The only "deployment.toml" file i have is in the <IS_HOME>/repository/conf" directory

### ISSUE THREAD

**Issue by KwadwoObeng** [wso2/product-is#10543]
Location : https://is.docs.wso2.com/en/latest/learn/configuring-email-otp/

**Comment by sherenewso2** [comment]
Hi, this is a mistake in the documentation. We will fix this. 
The only deployment.toml file you need to use is the one in the `<IS_HOME>/repository/conf` directory.
