### ISSUE TITLE
Place holder is printed in the Account Confirmation email in Self Sign-up flow

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#10546]
**Describe the issue:**
In a user self registration with consent purposes flow, only the username, password and email is collected. In the Account Confirmation email, the place holder for the given name is printed. Please refer the screenshot below.
![image](https://user-images.githubusercontent.com/19262008/99620818-4d700480-2a4c-11eb-87d7-576a837c4c21.png)

**How to reproduce:**
Configure self registration with consent purposes[1] and try the flow.
[1] https://is.docs.wso2.com/en/latest/learn/self-registration-and-account-confirmation/#configuring-self-registration-consent-purposes

**Expected behavior:**
If the first name or last name is not present, then use the username for the place holder as a fall back.

**Environment information :**
 - Product Version: IS 5.11.0 RC
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
