### ISSUE TITLE
Add missing postman collections

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#10548]
**Is your suggestion related to a missing or misleading document? Please describe.**

The following REST API docs are missing postman collections:

- [ ] https://is.docs.wso2.com/en/latest/develop/email-templates-rest-api/

- [ ] https://is.docs.wso2.com/en/latest/develop/fido-rest-api/

- [ ] https://is.docs.wso2.com/en/latest/develop/permission-management-rest-api/

- [ ] https://is.docs.wso2.com/en/latest/develop/totp-rest-api/

- [ ] https://is.docs.wso2.com/en/latest/develop/authorized-apps-rest-api/

- [ ] https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
