### ISSUE TITLE
Links to the other pages are not properly linked in Console application

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#10545]
**Describe the issue:**
In the Console application the linked pages are not linked properly. Please refer the screenshots below.

* Manage Self-Sign-Up purposes (Manage -> User Onboarding -> Self Registration)
![image](https://user-images.githubusercontent.com/19262008/99619620-d89bcb00-2a49-11eb-915e-0f64432688ff.png)

* Manage Lite-Sign-Up purposes (Manage -> User Onboarding -> Lite User Registration)
![image](https://user-images.githubusercontent.com/19262008/99619665-fcf7a780-2a49-11eb-8627-e28324dd0c65.png)

* Manage JIT provisioning purposes (Manage -> User Onboarding -> Ask Password)
![image](https://user-images.githubusercontent.com/19262008/99619722-1993df80-2a4a-11eb-8d99-c22bf05d9db5.png)

**Expected behavior:**
These must be linked to the respective pages.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 RC
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
