### ISSUE TITLE
Minimum number of forced security questions to be answered is mandatory in Console application

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#10547]
**Describe the issue:**
In Account Recovery configurations, **Minimum number of forced security questions to be answered** config is mentioned as a mandatory one. Please refer the screenshot.

![image](https://user-images.githubusercontent.com/19262008/99622643-945ff900-2a50-11eb-80dd-6fc3f4f11ead.png)

Based on this behavior, user cannot change any other configuration in the same category without adding a value to this configuration. This is only happening in Console application. In Management Console, this is mentioned correctly. Please refer the below screenshot.

![image](https://user-images.githubusercontent.com/19262008/99622845-f15baf00-2a50-11eb-9560-51625b65dfeb.png)

**How to reproduce:**
1. Login to the Console application and go to Manage -> Account Management -> Account Recovery.
2. Enable **Notification based password recovery** and try to update the category.

**Expected behavior:**
It needs to be able to update the category without having a value to the **Minimum number of forced security questions to be answered** config.

**Environment information :**
 - Product Version: IS 5.11.0 RC
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by brionmario** [comment]
Governance connectors UI in the Console is implemented to be data driven. But currently, Governance API doesn't support any metadata regarding the fields hence all the input fields have been made mandatory by default. The API should provide more metadata regarding the `type`, `required` status etc. of the property fields.

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/13241
