### ISSUE TITLE
Add cors configs to use sample apps in 5.11.0 

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#10553]
**Is your suggestion related to a missing or misleading document? Please describe.**
In 5.11.0, the default cors configs is set to block all origins. For sample apps to work, we need to add cors configs to the deployment.toml file:

```
[cors]
allow_generic_http_requests = true
allow_any_origin = false
allowed_origins = [
    "http://localhost:8080"
]
allow_subdomains = false
supported_methods = [
    "GET",
    "POST",
    "HEAD",
    "OPTIONS"
]
support_any_header = true
supported_headers = []
exposed_headers = []
supports_credentials = true
max_age = 3600
tag_requests = false
```

This needs to be addressed in the docs.

**Comment by pulasthi7** [comment]
@gomathyk @sherenewso2 Can we close this?

**Comment by gomathyk** [comment]
No, we need to know for which samples we actually need this config and why. @sumedhe

**Comment by pulasthi7** [comment]
@ivantha can you help on this?

**Comment by sumedhe** [comment]
Only for the samples which are using SAML2 POST Binding requires CORS config setup. The reason for that is the HTTP POST requests which are coming form a different domain identifies as a CORS request.

The CORS filter is going to be updated for not to detect HTTP POST (Form submissions) requests as CORS requests. After that the CORS configs will not be required to setup for sample apps.

**Comment by gomathyk** [comment]
Will be resolved with https://github.com/wso2/docs-is/pull/2356.
