### ISSUE TITLE
Support creating SAML applications using SAML metadata in console app

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10565]
**Is your feature request related to a problem? Please describe.**
Currently, the console app supports creating SAML apps using manual configurations. The most popular for creating SAML apps is using SAML metadata.

**Describe the solution you would prefer**
- Support creating SAML application using SP metadata file
- Support creating SAML application using SP metadata URL (Some apps expose metadata URL)

**Additional context**
The Applications REST API supports this feature. So we just need to enable it from the UI

**Comment by inthirakumaaran** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2153
