### ISSUE TITLE
Move Privacy Policy text to a markup document inside the i18n module in the identity apps

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10575]
**Is your suggestion related to an experience ? Please describe.**
The privacy policy text currently exists in localized files. It should be moved to a separate markup document inside the i18n module like the help docs.

**Comment by svenzimmermann** [comment]
The privacy policies of the authenticationendpoint and myaccount should be able to be directed to the same file or URL.
Different privacy policies for all webapps are not useful at least for many usecases.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
