### ISSUE TITLE
[Migration] Behavioral change in display name selection order in user-portal/myaccount application

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#10571]
**Describe the issue:**
For issue [1] we have done a behavioral change in the order of the display name selection for the user portal. Previously this order was,
1. givenName + familyName
2. userName
3. displayName

From this new behavioral change the `diaplayName` check will be checked at the top of the conditional flow.
1. displayName
2. givenName + familyName
3. userName

To keep the backward compatibility, for IS 5.10.0 we have introduced a configuration to enable this new flow. That was documented in [2].

[1] https://github.com/wso2/product-is/issues/10528
[2] https://github.com/wso2/docs-is/pull/2249

**Comment by ayshsandu** [comment]
This may need to go to the migration docs when 5.12.0-GA is released.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
