### ISSUE TITLE
Assets of the help document should be localized and a fallback mechanism should be implemented

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#10576]
**Is your suggestion related to an experience ? Please describe.**
The help markup documents of the My Account all share a common assets directory across all localizations. However, since there can be language-specific assets, the assets directory should be localized as well. Additionally, a fallback mechanism should be set up to ensure there is a default image when an image for a certain language doesn't exist.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
