### ISSUE TITLE
Custom User Store is not listing in the Console/Mgt Console in 5.11 (working in 5.10)

### ISSUE THREAD

**Issue by nisho06** [wso2/product-is#10582]
**Describe the issue:**
I have written a custom user store manager for secondary jdbc userstores. Since 5.11 pack is only supporting for UniqueId managers, I have written the CustomUserStoreManager class by extending the `UniqueIDJDBCUserStoreManager` class. Bundle was activated properly and services were registered properly. But its not listing the custom userstore I have created. (Its listing in 5.10 pack but not in 5.11 pack)

**How to reproduce:**
follow this documentation. This documentation also have some faults. Check those and try
```
https://is.docs.wso2.com/en/5.11.0/setup/writing-a-custom-user-store-manager/
```

**Expected behavior:**
Created custom user store must have to be listed in the mgt console/console of 5.11 pack

**Solution:**
Try debugging `getAvailableUserStoreClasses()` method in `UserStoreConfigAdminService.java` class of `Identity-framework` repository. (Issue might be somewhere there in the methods residing in it)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0
 - OS: [ Windows, Linux, Mac]
 - Database: [MySQL]
 - Userstore: [JDBC]

**Comment by somindatommy** [comment]
Possible fix to add custom user stores to the allowed list. 

**Modify the Identity.xml.j2 as follows**
```
<!-- Allowed Userstores -->
{% if user_store_mgt.allowed_user_stores is defined %}
<AllowedUserstores>
    {% for allowed_user_store in user_store_mgt.allowed_user_stores %}
    <AllowedUserstore>{{allowed_user_store}}</AllowedUserstore>
    {% endfor %}
    {% if user_store_mgt.custom_userstores is defined %}
    {% for custom_userstore in user_store_mgt.custom_userstores %}
    <AllowedUserstore>{{custom_userstore}}</AllowedUserstore>
    {% endfor %}
    {% endif %}
</AllowedUserstores>
{% endif %}
```

**Deployment.toml config**
```
[user_store_mgt]
custom_userstores=["org.sample1.custom.UniqueIDJDBCUserStoreManager", "org.sample2.custom.UniqueIDJDBCUserStoreManager"]
```

**Comment by pamodaaw** [comment]
Doc fix: https://github.com/wso2/docs-is/pull/2386 
Migration issue: https://github.com/wso2/product-is/issues/10948
