### ISSUE TITLE
Missing document for lite user registration

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#10585]
**Is your suggestion related to a missing or misleading document? Please describe.**
IS 5.11.0 RC distribution has a new feature as "Lite user registration" in Identity Providers -> Resident IdP -> User Onboarding section, which is not documented

**Describe the improvement**
Feature use case, configurations, applicability, and limitations should be clearly documented.

**Comment by sherenewso2** [comment]
https://docs.google.com/document/d/1XJONjuh1qtofH8QjMVtHd_qha_O-jU9FXohECknPmW8/edit
