### ISSUE TITLE
Lite user registration confirmation gives 504 

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#10589]
**Describe the issue:**
After the user is signed up using the Lite user self-registration when clicking the confirmation URL in the email 504 was observed

The root cause seems to be around this. - https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/client/api/LiteRegisterApi.java#L87-L88

failing URL
`https://<is-domain>:9443/api/identity/user/v1.0/introspect-code`

But IS pack is proxy port applied.

**Expected behavior:**
User registration confirmation should be successful

**Environment information:**
 - Product Version: IS 5.12.0-m1-SNAPSHOT
 - OS: Linux

**Comment by ayshsandu** [comment]
With the fix introduced in https://github.com/wso2/product-is/issues/8878, the `internal_hostname` needs to be changed to `localhost`. By default, if we don't define a value for the `internal_hostname` in the deployment.toml, `localhost` will be the default value.
