### ISSUE TITLE
SCIM user list operation uses a different method when pagination params are not defined

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#10580]
**Describe the issue:**
SCIM user list call is using two different user store methods when pagination parameters are present in the request vs when not.

**Describe the improvement**
When pagination parameters are not given in the request, should use the user store's default maximum user list length as the **count** and stick to the same API.

**Steps to debug**
1. Send request without pagination parameters and it will use the legacy APIs.
`curl -X GET "https://localhost:9443/scim2/Users" -H "accept: application/scim+json" -k -v -H "Authorization: Basic YWRtaW46YWRtaW4="`
[Calling API](https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L2976)
2. Send the request with pagination parameters and it will use an overloaded method.
`curl -X GET "https://localhost:9443/scim2/Users?count=10&startIndex=0" -H "accept: application/scim+json" -k -v -H "Authorization: Basic YWRtaW46YWRtaW4="`
[Calling API](https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L14606)
3. [SCIMUserManager class decision point](https://github.com/wso2-support/identity-inbound-provisioning-scim2/blob/44a247cf3a86a75505a867ad3579c1ddb626d5d7/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L986)

**Environment information**
IS-5.10.0
Latest WUM as at 23rd of Nov 2020

**Comment by rksk** [comment]
Related to https://github.com/wso2/product-is/issues/4943

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
