### ISSUE TITLE
Advance Search placeholders are not consistent in the console components

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10588]
**Describe the issue:**
$Subject is observed when trying advanced search in different views of the console.

**How to reproduce:**
1. Application Search: Placeholder is not visible completely
![app-serach-placeholder](https://user-images.githubusercontent.com/5061791/100072186-f1e5b280-2e61-11eb-826c-738b322f71d2.png)

2. Group Search: Has the different placeholder than other pages

![group-serach](https://user-images.githubusercontent.com/5061791/100072234-fe6a0b00-2e61-11eb-903c-acf7564813c8.png)

**Expected behavior:**
Have a uniqueness in the advanced search of multiple components.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0-RC]
 - OS: [Mac]
 - Database: [H2]

**Comment by Thumimku** [comment]
> Application Search: Placeholder is not visible completely

The above sub Issue was not reproducible in **wso2is-5.12.0-m5-SNAPSHOT.**

![Application](https://user-images.githubusercontent.com/25488962/104345333-387f9100-5524-11eb-873b-f4201e85190e.png)

> Group Search: Has the different placeholder than other pages

IMO, It's consistent through manage configurations (Users, Roles, Groups)

Users
![users](https://user-images.githubusercontent.com/25488962/104345723-acba3480-5524-11eb-8157-bdc14c88e896.png)

Roles
![roles](https://user-images.githubusercontent.com/25488962/104345736-b0e65200-5524-11eb-8170-913556e01723.png)

Groups
![groups](https://user-images.githubusercontent.com/25488962/104345763-b6439c80-5524-11eb-83bb-16effbbdf6f9.png)

FYI, Develop configurations have customized place holders (Applications, IdP)

Applications
![ApplicationPL](https://user-images.githubusercontent.com/25488962/104346029-f4d95700-5524-11eb-9fcc-c8ba40c9e7c4.png)

IdPs
![IDP](https://user-images.githubusercontent.com/25488962/104346055-fe62bf00-5524-11eb-9d9b-9e0b57139328.png)

WDYT?
