### ISSUE TITLE
Update Doc for Email/Mobile Verification Update 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#10593]
Recently we encountrerd the issue, https://github.com/wso2/product-is/issues/10358
and we fixed the solution in https://github.com/wso2-extensions/identity-governance/pull/453

This issue is to track the fix to doc update.

**Comment by rksk** [comment]
We need to provide steps for the claim configuration

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
