### ISSUE TITLE
Make buildRequestedAuthnContext(),  isForceAuthenticate() and encodeRequestMessage() methods protected in DefaultSAML2SSOManager

### ISSUE THREAD

**Issue by kalanika** [wso2/product-is#10596]
There was a requirement to add default authentication contexts  in the outbound SAML request which will be sent to federated Identity server.

We can extend the default identity server functionalities by extending DefaultSAML2SSOManager and  new custom SAML2SSOManager class can be registered in the application-authentication.xml file located in the <IS_HOME>/repository/conf/identity/ directory under the SAMLSSOAuthenticator config.

But We need to duplicate lot of methods since some important methods in the DefaultSAML2SSOManager class is private.

Can we make buildRequestedAuthnContext(),  isForceAuthenticate() and encodeRequestMessage() methods  protected so we can extend the new functionalities by overriding the existing methods  and we can reduce the code duplication ?

**Comment by ayshsandu** [comment]
+1 to add this change. @kalanika can you verify whether we are good close this issue when the above PR is merged. Whether your customizations worked as expected with the changes.
