### ISSUE TITLE
Upgrade rc-tree to stable released version

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#10599]
**Describe the issue:**
The plugin `rc-tree` is currently under version [4.0.0 beta 2 public](https://www.npmjs.com/package/rc-tree) release. This issue is to track the upgrade to 4.0.0 once it is released.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
