### ISSUE TITLE
Self Registration Auto Login

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#10603]
**Is your suggestion related to an experience ? Please describe.**
In self registration, after user is verified using email, user is asked to re enter password credentials 

**Describe the improvement**
After user is verified by clicking the verification mail, user gets auto login 

**Additional context**
Application can be configured to auto login or re enter password credentials after self registration account verification

**Product Version
Wso2 IS 5.10.0

**How to reproduce
1) Identity -> Identity Providers and then click Resident
2) Expand the Account Management Policies section, and then expand the User Self Registration section
3) enable self registration auto login

**Related Issues**
#8634

**Comment by senthalan** [comment]
Backend improvements are done with https://github.com/wso2-extensions/identity-governance/pull/476, https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/86, https://github.com/wso2/carbon-identity-framework/pull/3348 and https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1531. 

The identity-apps needs to improved to handle this

**Comment by AnuradhaSK** [comment]
closing the issue since public all PRs are merged. @ShehanDinuka please get the support PRs merged ASAP

**Comment by nilasini** [comment]
Do we have any doc reference for this improvement?

**Comment by nilminiwso2** [comment]
Shall we create a doc issue for this?
@bhagyasakalanka
