### ISSUE TITLE
Move OOTB Connectors to plugins directory

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#10612]
Ideally dropins directory should be used to configure new features / external artifacts. We need to move the set of connectors that are shipped in the OOTB product from dropins to plugins directory.

- [x] [TOTP](https://github.com/wso2/product-is/issues/10998)
- [x] [Email OTP](https://github.com/wso2/product-is/issues/11176)
- [ ] SMS OTP
- [ ] Social Login Connectors
- [ ] Basic authenticator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
