### ISSUE TITLE
Should we support infinite(maximum) expiry access tokens?

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10610]
**Describe the issue:**

In the past, we have supported issuing tokens with a maximum expiry time (or rather an infinite expiry time). Although we claim it's infinite internally we set the expiry to be equal MAX value of int.

The way to indicate that an application needs a maximum expiry was by configuring -1 or any negative value as the expiry value. 

However, there are a few concerns related to this approach.

1. Using a negative value for expiry is not intuitive and is confusing to the users
2. access_token is meant to have a finite/short expiry and can expire and be revoked. When we allow their maximum expiry tokens it leads to encourages users to disregard handling expiry in their apps as their expectation is that the tokens will practically never expire.
3. In the UI, we have restricted creating apps with -1 or any negative value as expiry. However, we still have enabled this through APIs. There is an inconsistency here that needs to be addressed.

The suggestion is to revisit this feature to allow these maximum expiry tokens and make things consistent.

**Comment by IsuraD** [comment]
+1 to implement this. @mefarazath how do we support backward compatibility? What happens to the users who already set -1?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
