### ISSUE TITLE
Empty response when using identity claims to filter users with getUserList method in RemoteUserStoreManagerService

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#10616]
**Describe the issue:**
When using identity claims to filter users using getUserList method in RemoteUserStoreManagerService it returns and empty list when we do not specify a user store domain value with the claim value.

**How to reproduce:**
Install wso2is-5.10.0 latest wum.
Enable SOAP by adding the following to depoyment.toml
`[admin_service.wsdl]
enable= true`

Set up test user and lock

    Start IS, log in as { {admin}
    Edit claim http://wso2.org/claims/identity/accountLocked to set Supported by Default to true
    Create a new user in the PRIMARY user store
    Edit the new user with default users and set Account Locked to checked and update.

Invoke RemoteUserStoreManagerService using SoapUI with
 
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ser="http://service.ws.um.carbon.wso2.org">
   <soap:Header/>
   <soap:Body>
      <ser:getUserList>
         
         <ser:claimUri>http://wso2.org/claims/identity/accountLocked</ser:claimUri>
         
         <ser:claimValue>true</ser:claimValue>
         
         <ser:profile>http://service.ws.um.carbon.wso2.org</ser:profile>
      </ser:getUserList>
   </soap:Body>
</soap:Envelope>`

Response : 

`<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
   <soapenv:Body>
      <ns:getUserListResponse xmlns:ns="http://service.ws.um.carbon.wso2.org" xmlns:ax2727="http://common.mgt.user.carbon.wso2.org/xsd" xmlns:ax2718="http://core.user.carbon.wso2.org/xsd" xmlns:ax2719="http://api.user.carbon.wso2.org/xsd" xmlns:ax2722="http://tenant.core.user.carbon.wso2.org/xsd" xmlns:ax2725="http://dao.service.ws.um.carbon.wso2.org/xsd"/>
   </soapenv:Body>
</soapenv:Envelope>`

When further debugging this behavior could find that the returnUsersList value is returned as null in doPreGetUserListWithID() method in carbon-identity-framework/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/listener/IdentityUserNameResolverListener.java class. Please refer the below screenshot for further clarification.
<img width="1018" alt="Screenshot 2020-11-27 at 1 04 24 AM" src="https://user-images.githubusercontent.com/47654317/100386911-afcc9480-304c-11eb-90c7-505ac349129e.png">

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Arshardh** [comment]
Why isn't this fix added to 4.6.x public?
