### ISSUE TITLE
Driver Name Error with MySQL 8 

### ISSUE THREAD

**Issue by nisho06** [wso2/product-is#10624]
**Is your feature request related to a problem? Please describe.**
When trying to change the h2 database with mysql, we should have to configure it in deployment.toml file. Like this..
```
[database.identity_db]
type = "mysql"
hostname = "localhost"
name = "regdb"
username = "regadmin"
password = "regadmin"
port = "3306"
```
Since you are not configuring the driver name, system will take the default driver name as `com.mysql.jdbc.Driver`

But if you are using MySQL 8, the default driver name is not working... 

**Describe the solution you would prefer**
you should have to configure the driver name in deployment.toml configurations as `com.mysql.cj.jdbc.Driver`....

Better if you configure the driver name `com.mysql.cj.jdbc.Driver` as a default for MySQL 8

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
