### ISSUE TITLE
Debian package - 5.10.0 version

### ISSUE THREAD

**Issue by bpnx** [wso2/product-is#10625]
**Describe the issue:**
I've downloaded the debian package from your site. Under Debian buster it's not possibile to install the package:
# dpkg -i wso2is-linux-installer-x64-5.10.0.deb 
(Reading database ... 187316 files and directories currently installed.)
Preparing to unpack wso2is-linux-installer-x64-5.10.0.deb ...
Creating wso2 user and group...
addgroup: The group `wso2' already exists as a system group. Exiting.
useradd: user 'wso2' already exists
Unpacking wso2is-5.10.0 (5.10.0) ...
dpkg-deb (subprocess): cannot copy archive member from 'wso2is-linux-installer-x64-5.10.0.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive wso2is-linux-installer-x64-5.10.0.deb (--install):
 cannot copy extracted data for './usr/lib/wso2/wso2is/5.10.0/repository/components/plugins/spring.framework_3.2.9.wso2v2.jar' to '/usr/lib/wso2/wso2is/5.10.0/repository/components/plugins/spring.framework_3.2.9.wso2v2.jar.dpkg-new': unexpected end of file or stream
Processing triggers for systemd (241-7~deb10u4) ...
Errors were encountered while processing:
 wso2is-linux-installer-x64-5.10.0.deb

**How to reproduce:**
Just download and try to install

**Expected behavior:**
Install successfully

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux (Debian10.6)
 - Database: N/A
 - Userstore: N/A

---

**Comment by RidmiR** [comment]
Hi @bpnx, 
We have tried to install the WSO2 IS 5.10.0 Ubuntu installer which hosted in wso2 website and we were unable to reproduce the issue. Could you please try to install it with "sudo" command?

   ` sudo dpkg -i wso2is-linux-installer-x64-5.10.0.deb `

And also you can try to install the .deb package using apt. Please follow the below set of commands,
```
1. apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "379CE192D401AB61"
2. echo "deb https://dl.bintray.com/wso2/deb is_5100 release" | sudo tee -a /etc/apt/sources.list
3. sudo apt-get update
4. sudo apt-get install wso2is-5.10.0
```

Please get back to us if you are still encounting any issues while installing the WSO2 IS 5.10.0 installer.

**Comment by bpnx** [comment]
Hi @RidmiR, did you use a debian buster ? To reproduce the problem it's enough to download the "Linux installer deb" and
install; you can see the problem without installing, using the command
dpkg-deb -R wso2is-linux-installer-x64-5.10.0.deb /tmp/extracted
The error is the same, about lzma 
This happens on clean debian buster; same on ubuntu 20.04.1
md5sum of the deb package downloaded is:
45ba6367e97c21261ffdca92b9ba1560  wso2is-linux-installer-x64-5.10.0.deb
However your colleague wrote me about a new version: I just downloaded the 5.11.0 version and the problem has disappeared
Thank you

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
