### ISSUE TITLE
yajsw12.15 with java 15

### ISSUE THREAD

**Issue by sudareddy** [wso2/product-is#10628]
We are using java 15 and latest version of yajsw and getting the following exception

[null - INFO] 20-11-26 17:17:23 Error in createScript ..\scripts\trayMessage.gv 
Exception in org.rzo.yajsw.log.MyLogger: groovy/lang/GroovyClassLoader 
  org.rzo.yajsw.script.ScriptFactory.createScript(ScriptFactory.java:56)
  org.rzo.yajsw.wrapper.AbstractWrappedProcess.getTriggerScript(AbstractWrappedProcess.java:2175)
  org.rzo.yajsw.wrapper.AbstractWrappedProcess.getTriggerActions(AbstractWrappedProcess.java:2053)
  org.rzo.yajsw.wrapper.AbstractWrappedProcess.startInternal(AbstractWrappedProcess.java:1285)
  org.rzo.yajsw.wrapper.AbstractWrappedProcess.start(AbstractWrappedProcess.java:1154)
  org.rzo.yajsw.wrapper.WrappedProcessList.startAll(WrappedProcessList.java:26)
  org.rzo.yajsw.app.WrapperMainServiceWin$1.run(WrapperMainServiceWin.java:194)
  java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base/java.lang.Thread.run(Thread.java:832)
  Caused by: groovy.lang.GroovyClassLoader
    java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
    java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    org.rzo.yajsw.boot.WrapperClassLoader.findClass(WrapperClassLoader.java:82)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    org.rzo.yajsw.script.ScriptFactory.createScript(ScriptFactory.java:56)
    org.rzo.yajsw.wrapper.AbstractWrappedProcess.getTriggerScript(AbstractWrappedProcess.java:2175)
    org.rzo.yajsw.wrapper.AbstractWrappedProcess.getTriggerActions(AbstractWrappedProcess.java:2053)
    org.rzo.yajsw.wrapper.AbstractWrappedProcess.startInternal(AbstractWrappedProcess.java:1285)
    org.rzo.yajsw.wrapper.AbstractWrappedProcess.start(AbstractWrappedProcess.java:1154)
    org.rzo.yajsw.wrapper.WrappedProcessList.startAll(WrappedProcessList.java:26)
    org.rzo.yajsw.app.WrapperMainServiceWin$1.run(WrapperMainServiceWin.java:194)
    java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    java.base/java.lang.Thread.run(Thread.java:832)
 INFO|wrapper|Service |20-11-26 17:17:23|error initializing script ..\scripts\trayMessage.gv

As i had updated the groovy jar with latest version(3.0.6)

**Comment by ruwanta** [comment]
Java 15 has known limitations as of present, as there are few core libraries are being removed or changed on Java 15
Hence please stay on Java 11, or 14 until Java 15 (full) compatible release is done.

**Comment by sudareddy** [comment]
As you mentioned above java 11 and java 14 will give support for yajsw 12.15. Can I know the above groovy exception will be resolved ?

**Comment by ruwanta** [comment]
WSO2 Identity Server does not use Groovy. Hence it is unlikely that throws above exception.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
