### ISSUE TITLE
Two error messages shown during self registration flow

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#10639]
**Describe the issue:**
The user portal shows two error messages when a user attempts to login with an already registered email address first and afterwards with an invalid email address.

**How to reproduce:**
_Prerequisites:_ Enable email as username and enable self registration feature in resident idp configs.
1. Go to user portal login page.
2. Click on Create Account hyperlink.
3. On the create new account page, input a valid email address, which already exists as a username in the system, and click Next/Continue button. 
4. When the button is clicked, WSO2 checks in the background if the user already exists with the provided email, and returns error `"<email address> already exists. Please try a different email address."`
5. On the same page, input an invalid email address (username without @ symbol) and click Next/Continue button.
6. Now two error messages are shown. One is from step 3 and the other one for the validation of the email address.

<img width="510" alt="Screenshot 2020-11-30 at 16 43 41" src="https://user-images.githubusercontent.com/24982871/100604047-00cdd880-332c-11eb-9dbd-ba42dd179c5d.png">

- Expected result: The backend error message should disappear when a new UI validation error is shown.
- Actual result: Shows the previous error message along with the latest error message

**Comment by ChamathNS** [comment]
This issue is not reproducible in 5.12.0-M2.
