### ISSUE TITLE
Error when adding "Middle Name" claim value

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#10638]
**Describe the issue:**
When trying to add a value to "Middle Name" claim in user profile through management console following error is returned

![image](https://user-images.githubusercontent.com/36619815/100598595-f65c1080-3324-11eb-9a07-9865c17c0713.png)

[https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/features/org.wso2.carbon.identity.oauth.server.feature/resources/oauth-scope-bindings.xml](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/features/org.wso2.carbon.identity.oauth.server.feature/resources/oauth-scope-bindings.xml)

**How to reproduce:**

- Set supported by default to true for claim Middle Name in http://wso2.org/claims
- Navigate to update profile screen of one of the users
- Add a value to Middle Name field and click update

**Environment information:**
 - Product Version: IS 5.11.0 rc1
 - OS: Linux

**Comment by IsuraD** [comment]
This is happening due to middleName Attribute is not supported in default objectClasses in the embedded ldap. As an alternative can use a different mapped attribute which is supported in the ldap.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
