### ISSUE TITLE
AWS cognito connector support for identity server 5.10.0 version

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10634]
Currently, we do not have a compatible version for the 5.10.0 version.  If we put the older version to 5.10.0 it gave an OSGi error on bundle activation. We need to do a connector release for this.
https://store.wso2.com/store/assets/isconnector/details/b998e79f-cfe0-44a7-9af4-0525945aca2b
https://github.com/wso2-extensions/identity-outbound-auth-cognito/issues

**Comment by emswbandara** [comment]
Connector store has been updated with a compatible version
