### ISSUE TITLE
HttpAdminServices configuration in carbon.xml is not templated.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#10633]
**Describe the issue:**
HttpAdminServices configuration is used to expose all AdminServices in HTTP transport. The Axis2Config —> HttpAdminServices configuration in carbon.xml is not templated, hence cannot be configured from the deployment.toml. 

**Expected behavior:**
This config should be configurable through the deployment.toml

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by IsuraD** [comment]
Hi @tharakawijekoon , 

What is the requirement to expose all AdminServices in HTTP transport? Can you explain the requirement?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
