### ISSUE TITLE
Configurable claim for username in SCIM 2.0 response

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#10631]
**Describe the issue:**
In SCIM 2.0 get user method, currently we are setting org.wso2.carbon.user.core.common.User.getUserName() for the urn:ietf:params:scim:schemas:core:2.0:User:userName attribute.

If we have a  requirement to get the value in another claim to the urn:ietf:params:scim:schemas:core:2.0:User:userName in scim response, that is not possible.
If we want to rename the username, also having a sperate claim to store the human readable username is helpful.
So, when creating the user, we should generate a unique user id and pass it as the immutable identifire to the user core, while passing the configurable claim with the human readable username.

We can define, a configuration as a primary login identifier, and give  a preferred claim for that.
Ex:
```
<LoginIdentiFiers>
<Enable>true</Enable>
<PrimaryLoginIdentifier>http://wso2.org/claims/userType</PrimaryLoginIdentifier>
</LoginIdentiFiers>
```

In the scim component, check for this configuration, and if available, generate a UUID and provide it as the immutable username and pass this claim in the claims set.

In the get user part of the scim component, when the above configuration is enabled, the human readable scim username can be set by retrieving the value of the above defined claim.

**Comment by mevan-karu** [comment]
This will be a sub task of issue https://github.com/wso2/product-is/issues/8899

**Comment by rksk** [comment]
This is not working when patching groups. The value passed in the `display` attribute is being searched on the userstore against the http://wso2.org/claims/username yet.

**Comment by rksk** [comment]
Btw, the originally reported issue is not yet fixed in master.
