### ISSUE TITLE
RP-initiated federated logout does not honour user consent.

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#10636]
**Describe the issue:**
During the RP-initiated logout flow with using the OIDC authenticator, the secondary IS prompts the user for logout consent.
When the user denies the logout consent, the user gets redirected to the landing page of the app. Note that the user was not prompted for logout consent from the primary IS.
The following network trace was observed in the error scenario.

![logout_consent](https://user-images.githubusercontent.com/25428696/100581583-f3095a80-330d-11eb-826e-a0557ae8f141.png)

In the error scenario, upon denying logout consent for the federated_IdP, the user gets redirected to the landing page of the app. When the user clicks on login, user is then prompted for authentication meaning the authenticated session has been cleared from the federated_IdP despite denying the logout consent.

**How to reproduce:**

1. Configure two identity servers as primary_IdP and federated_IdP.
2. Configure federated_IdP as a OAuth2/OIDC federated authenticator to primary_IdP.
3. Add an user to the federated_IdP and configure an app in primary_IdP to use the federated_IdP as the federated authenticator.
4. Login to app.
5. Logout from the app.
6. Deny logout consent prompt from the federated_IdP.

**Comment by Migara-Pramod** [comment]
I will work on this

**Comment by Migara-Pramod** [comment]
I will look into this issue

**Comment by Migara-Pramod** [comment]
Recreate the bug. Setup is as follows.

- Client application - saml2-web-app-pickup-manager
- Two Wso2 IS with a port offset (Packs are generated using 5.12-m9-SNAPSHOT)

**Comment by Migara-Pramod** [comment]
In the above recreate scenario, I have used same hostname (localhost) for both primary and federated IS. And I have tried to recreate the same scenario with different hostname. When the hostnames are different, couldn't be able to recreate the issue. The logout deny flow works fine.

**Comment by Migara-Pramod** [comment]
https://user-images.githubusercontent.com/75773531/106728151-321b9b00-6632-11eb-9e9c-7e39ae6000d2.mp4

**Comment by Migara-Pramod** [comment]
Error Scenario

- IS1 - localhost:9443
- IS2 - localhost:9444 (Federated)

https://user-images.githubusercontent.com/75773531/106731275-4f059d80-6635-11eb-8eba-bc346a837d75.mp4

**Comment by Migara-Pramod** [comment]
Success Scenario (with different host names)

- IS1 - localhost:9443
- IS2 - wso2.is:9444 (Federated)

https://user-images.githubusercontent.com/75773531/106731398-70ff2000-6635-11eb-8189-a45d97724d01.mp4

**Comment by Migara-Pramod** [comment]
Is this issue need to be fix @mefarazath, @pulasthi7 , @IsuraD, @ayshsandu

**Comment by Migara-Pramod** [comment]
**Reason behind the issue**

When user makes a logout request from client app, primary idp clears the commonAuthId in session cookie for the hostname (eg - localhost) before redirecting to the federated idp logout url. Therefore, whether or not user deny logout consent in federated idp, session is already cleared for the same hostname by primary idp.
