### ISSUE TITLE
Make appending carbon.super configurable for super tenant

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#10637]
In the password recovery flow, once the user submits the username, a message similar to below will be displayed.
```
Password recovery information has been sent to the email registered with the account   user1@mail.com@carbon.super
```
However, carbon.super appended to the username (or the email, if the email as username is enabled) should be configurable to prevent appending it.
```
Password recovery information has been sent to the email registered with the account   user1@mail.com
```

**Comment by mifrazmurthaja** [comment]
This should also be considered in the user registration page (Error message displayed when an already existing username is entered) and all other scenarios wherever the username is appended with @carbon.super.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
