### ISSUE TITLE
ID token validation fails when accessing /console and /myaccount with proxy port 443

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#10645]
**Describe the issue:**
When we add the config

```
[transport.https.properties]
proxyPort = "443"
```

The resident idp entity id also appends that port. But the oauth sdk does not expect this port in the issuer URL[1] 

[1].https://github.com/asgardio/asgardio-js-oidc-sdk/blob/master/packages/oidc-js/src/utils/sign-in.ts#L218

**How to reproduce:**

Add the config to deployment toml
```
 [transport.https.properties]
proxyPort = "443"

```

Try accessing the /conole or /myaccount id token validation will fail following error can be observed from the browser console

`[Error] Unhandled Promise Rejection: Invalid id_token in the token response: eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l
`

**Comment by gkaran** [comment]
Is there a way around this until we get to upgrade to 5.12.0?

**Comment by Buddhimah** [comment]
@gkaran https://is.docs.wso2.com/en/latest/learn/adding-and-configuring-an-identity-provider/#configuring-a-resident-identity-provider Go to resident idp configuration click OAuth2/OpenID Connect Configuration. under  resident idp entity id change the host name and port as the .well-known endpoint host and port

**Comment by gkaran** [comment]
@Buddhimah I hope someday I will be able to buy you a beer!! Cheers!

**Comment by waqasalirazzaq** [comment]
@Buddhimah I am facing same issue. I changed the resident idp entity id but still getting same error.
![image](https://user-images.githubusercontent.com/30646233/122525676-c43ca280-d019-11eb-8650-9640fcff03f5.png)

![image](https://user-images.githubusercontent.com/30646233/122525834-f0f0ba00-d019-11eb-8842-9284e44ff568.png)

![image](https://user-images.githubusercontent.com/30646233/122526047-2bf2ed80-d01a-11eb-8352-ddffd2bf6d9f.png)

**Comment by waqasalirazzaq** [comment]
Below are the screenshots.

![image](https://user-images.githubusercontent.com/30646233/122527116-55f8df80-d01b-11eb-841c-0431dc6fc3d2.png)


![image](https://user-images.githubusercontent.com/30646233/122526235-5c3a8c00-d01a-11eb-9ce2-b0df60e92c0b.png)

![image](https://user-images.githubusercontent.com/30646233/122526275-68bee480-d01a-11eb-9d86-6c02de590916.png)

**Comment by yairhdz** [comment]
Hi @Buddhimah 
I have the same issue even if I change the idp entity id. What else could be causing this error?

**Comment by yairhdz** [comment]
Hi @Buddhimah 
I have the same issue even if I change the idp entity id. What else could be causing this error?

**Comment by vordimous** [comment]
@waqasalirazzaq @yairhdz the `:443` needs to be removed from IDP entity id. It should look like this:

`https://*****.com/oauth2/token`

**Comment by thivi** [comment]
I tried to explain this issue and the possible remedial actions in this blog. I hope it might be useful.
https://thivi.medium.com/fix-invalid-id-token-issue-in-wso2-identity-server-5-11-0-6bd9f7dc5db6

**Comment by diregraph** [comment]
@thivi well explained. Thank you.
