### ISSUE TITLE
[Migration] [Doc] Keystore Passsword Migration

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#10643]
**Describe the issue:**

For migrations from earlier versions to 5.10.0 

transformToSymmetric Property in the KeyStorePasswordMigrator migration-config.yaml should be false. For all the migrations to 5.11.0 This property should be true. 

https://github.com/wso2-extensions/identity-migration-resources/pull/167

**Comment by DMHP** [comment]
As the property value is 'true' in 5.11.0 migration client this information should be added to older versions than 5.11.0.
