### ISSUE TITLE
Support customer-specific client authentication

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-is#10647]
**Is your feature request related to a problem? Please describe.**

According to [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-2.3), it has specified that the client and the authorization server should establish a client authentication method suitable for the security requirements of the authorisation server.

Which indicates that the client is given an option for choosing the authentication method. Additionally, the ID token signing algorithm request object signing algorithm and token endpoint auth signing algorithm should be restricted per client. 

According to the OpenID specification, it has mentioned the set of client authentication methods used by clients to authenticate to the authorization server when using the token endpoint. During the client registration, the client can register the authentication method, if no method is registered, the default method is client_secret_basic [[Link](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)].

The client registration can happen in two ways,

1. Dynamic Client Registration (DCR)
> According to the Auth 2.0 DCR specification [[Link](https://tools.ietf.org/html/rfc7591#section-2)], the registered client has a set of metadata values associated with their client identifiers. In which “token_endpoint_auth_method” specifies the client authentication method. If this value is unspecified then the default is set to "client_secret_basic"

2. Manual Client Registration
> Currently, we do not support this feature in IAM.

**Describe the solution you would prefer**

1. Dynamic Client Registration (DCR)
> Currently, the client can specify the authentication mechanism in the token_endpoint_auth_method metadata and this method is used for client authentication in the DCR flow. ID token signing should be restricted with the id_token_signed_response_alg request_object_signing_alg, token_endpoint_auth_signing_alg values.

2. Manual Client Registration
> The user should be allowed to select their authentication method through the user interface. Ping currently provides an interface to select one of the supported client authentication methods from the authentication server to proceed with the authentication flow. The ID token signing algorithm, request object signing algorithm and token endpoint auth signing algorithm should be able to be selected during service provider creation.

These claims/selections then need to be ensured during the token flow 

**Additional context**
[Ping](https://images.pingidentity.com/image/upload/f_auto,q_auto,w_700,c_scale/ping_dam/content/dam/ping-6-2-assets/blogs/2018/images/open-banking-tpp-client-authentication-5.png) has currently provided options to select the client authentication mechanism.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
