### ISSUE TITLE
MTLS certificate enforcement

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-is#10648]
**Is your feature request related to a problem? Please describe.**
Binding the MTLS cert adds an extra layer of security regardless of the client authentication used. Since the MTLS happens in the APIM layer the certificate can be passed as a header or it can be passed through the MTLS message context. This then needs to be ensured during the token call.

**Describe the solution you would prefer**
For every token call, we need to ensure that the TLS certificate is passed regardless of the client authentication method (MTLS or PKJWT)

During registration, a client should be able to enable MTLS enforcement.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
