### ISSUE TITLE
cross-tenant="true" parameter usage and facts to consider

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#10646]
**Is your suggestion related to a missing or misleading document? Please describe.**
We have an undocumented parameter named 'cross-tenant="true' which governs if the API can be called by privileged users in cross tenant manner.
This needs to documented with the recommendations on the usage and if any precautions to be taken.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
