### ISSUE TITLE
[Migration] Move 'UM_HYBRID_GROUP_ROLE' table to migration client

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#10649]
When migrating to IS 5.11.0, 'UM_HYBRID_GROUP_ROLE' table should be added for the 'Groups and Roles Migration' before executing the migration client. As it affects the user experience, we need to get rid of this additional step.

The approach discussed:

- Make addAdmin property 'false' and start the migration process.
- From the migration client create and assign the relevant admin role to the admin user and the admin group (If it is not already assigned)

**Comment by DMHP** [comment]
We need to update the documentation with following
Under 'Groups and Roles Migration' of [1]
remove 'To enable this feature, execute the relevant DB script given below before starting the migration process' and the DB scripts
Before the migration, we need to make 'create_admin_account = false' in deployement.toml
[1] https://is.docs.wso2.com/en/5.11.0/setup/migrating-preparing-for-migration/

**Comment by ashendes** [comment]
Closing this as it has already been resolved.
