### ISSUE TITLE
Improve DCR API to support custom validations and attributes mentioned in the OIDC specification

### ISSUE THREAD

**Issue by SachiniSiriwardene** [wso2/product-is#10652]
**Is your feature request related to a problem? Please describe.**
The existing DCR API only supports the attributes mentioned [here](https://docs.wso2.com/display/IS511/apidocs/OAuth2-dynamic-client-registration/#!/models#RegistrationRequest) in the request. In addition to the attributes mentioned, need the ability to support other attributes mentioned in OIDC specification as well any additional custom attributes to be validated during the registration process.

**Describe the solution you would prefer**

- Add support for the attributes mentioned in the [Oauth2](https://tools.ietf.org/html/rfc7591) and [OIDC](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata) DCR specifications.
- Add the validations mentioned in the OIDC DCR specification to the IS DCR implementation.
- Add support to receive additional custom attributes related to client
- Add support to perform custom validations on those attributes. (Provide an extension point such as a listener which can be overridden to implement the validations)
- Add support to store either transport and/or signing certificates / JWKS URL / JWK set for the Service Provider.

- Add support to store tls certificate client subject dn claim to facilitate validation during mutual-TLS OAuth client authentication [Client Registration Metadata
](https://tools.ietf.org/html/rfc8705#section-2.1.2)

- Add support to store all client meta data sent in the DCR request and send them in the response.

**Additional context**
The following additional attributes need to be supported in the DCR endpoint.
Attributes mentioned in OIDC spec (https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata) :

- [ ] aud
- [ ] token_endpoint_auth_method ex: private_key_jwt / tls_client_auth
- [ ] token_endpoint_auth_signing_alg ex: PS256
- [ ] application_type ex: web/mobile
- [ ] id_token_signed_response_alg ex: PS256
- [ ] id_token_encrypted_response_alg ex: RSA-OAEP/ RSA-OAEP-256
- [ ] id_token_encrypted_response_enc ex : ex : A256GCM / A128CBC-HS256
- [ ] request_object_signing_alg ex: PS256
- [ ] software_statement (encoded and signed JWT token with client details)
- [ ] software_id ex: 740C368F-ECF9-4D29-A2EA-0514A66B0CDE
- [ ] scope ex: bank:accounts.basic:read

Attributes mentioned in the CIBA spec (https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0-ID1.html#registration) :

- [ ] backchannel_token_delivery_mode ex: poll/ ping
- [ ] backchannel_client_notification_endpoint ex: This value MUST be specified iff the grant_types includes urn:openid:params:grant-type:ciba and backchannel_token_delivery_mode is not poll. This must be a valid HTTPS URL
- [ ] backchannel_authentication_request_signing_alg ex: PS256
- [ ] backchannel_user_code_parameter_supported ex: This value MUST be specified only if the grant_types includes urn:openid:params:grant-type:ciba. If specified, it MUST be set to false.

Additonal attribute mentioned in the  Oauth2 mutual TLS client authentication specification (https://tools.ietf.org/html/rfc8705#section-2.1.2)

- [ ] tls_client_auth_subject_dn :  A string representation -- as defined in [RFC4514] -- of the expected subject distinguished name of the certificate that the OAuth client will use in mutual-TLS authentication.

 

It is also mentioned in the [OIDC](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata) specification that 
> Additional Client Metadata parameters MAY also be used.

Some of the relevant validations mentioned in the OIDC specification : 

- Signature validation for the SSA
- Check whether all host names of the URIs are same

> The Authorization Server SHOULD check to see if the logo_uri and policy_uri have the same host as the hosts defined in the array of redirect_uris.

- Check whether the client, policy and tos URIs point to a valid web page

> policy_uri
OPTIONAL. URL that the Relying Party Client provides to the End-User to read about the how the profile data will be used. The value of this field MUST point to a valid web page.

Need extension point to perform validations such as restricting the allowed grant types, response types, signature algorithms etc. that can be registered.
Issue created for validations in DCR endpoint : https://github.com/wso2/product-is/issues/10977

**Comment by emswbandara** [comment]
@yasasr will look into this

**Comment by emswbandara** [comment]
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1578 introduces support to fetch token_endpoint_auth_method. However the auth_methods are currently hard-coded in the implementation. It should be improved to either make it configurable or dynamically capture when client authenticators are registered.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
