### ISSUE TITLE
Console shows delete option for super admins when email username is enabled

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10650]
**Describe the issue:**
In the console, there is a hardcoded check to figure out if the user is super admin [1]. This will fail if email username is enabled and also if the super admin username is changed from the `deployment.toml`.

Also it would be best to avoid danger actions for the currently logged in user to avoid unexpected problems.

[1] https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/users/components/users-list.tsx#L305

**How to reproduce:**
1. Enable email username.
2. Login to console.
3. Go the users list.
4. Super admin will have the delete option in the listing and other danger actions in the edit page.

<img width="1618" alt="Screen Shot 2020-12-01 at 2 37 16 PM" src="https://user-images.githubusercontent.com/25959096/100720022-6cbf4800-33e3-11eb-808d-39a0d14bc826.png">

**Expected behavior:**
Logged in user should not have the delete and other danger actions enabled.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-RC1
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ayshsandu** [comment]
Super-admin name should come from an API. Preferably in [Server Configurations API](https://is.docs.wso2.com/en/latest/develop/configs-rest-api/#/Server%20Configs/getConfigs)

**Comment by DimalChandrasiri** [comment]
Let's use this issue https://github.com/wso2/product-is/issues/10702 to track the API progress of the `super-admin` retrieval.
