### ISSUE TITLE
Unable to log in to user portal by using user name with UTF-8 characters

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#10655]
**Describe the issue:**
Log in to the user portal by using a user name with UTF-8 characters results in a blank page.

**How to reproduce:**

- Configure the db connected to the identity server to support Unicode international characters.
- Enable email as username.
- Create a user with the username as `a例vb例@mii.com`
- Log in to the user portal as this newly created user.
- Then a blank page will be displayed.

In the browser console, the following error was observed.

<img width="689" alt="Screenshot 2020-12-01 at 20 18 57" src="https://user-images.githubusercontent.com/24982871/100755853-a2c7f080-3412-11eb-8420-7d9f854dd3b2.png">

This error is due to missing null check at [1].
After fixing this it was identified that the actual error is occurring at [2].

The root cause for the above behaviour is due to atob() javascript method is used to decode a base-64 encoded string.  However, the id token at [2] is in base-64 url encoded format. With base-64 url encoding the encoding is technically identical to base-64 encoding, except for the 62nd and 63rd alphabet character.

character number | base64 encoded | base64 url encoded
-- | -- | --
62 | + | - (minus)
63 | / | _ (underline)

Refer [3] and [4] for more details.

Therefore when the id token payload contains the characters - or _ the atob() function identifies the string to be decoded is not correctly encoded.

**Expected behavior:**
Properly handle decoding of the base64 URL encoded id token payload.

**Environment information:**
 - Product Version: IS 5.10.0

[1] https://github.com/wso2/identity-apps/blob/v1.0.72/apps/user-portal/src/store/actions/authenticate.ts#L226
[2] https://github.com/wso2/identity-apps/blob/v1.0.72/modules/authentication/src/actions/sign-in.ts#L301
[3] https://tools.ietf.org/html/rfc4648#section-4
[4] https://tools.ietf.org/html/rfc4648#section-5

**Comment by inthirakumaaran** [comment]
This issue is tracked & fixed in https://github.com/asgardeo/asgardio-js-oidc-sdk/issues/74

**Comment by tharakawijekoon** [comment]
The  crypto js also has normal base64 decoding[1], @inthirakumaaran FYA

[1]https://github.com/brix/crypto-js/blob/3.3.0/enc-base64.js#L114

**Comment by emswbandara** [comment]
Effort FE::2 days

**Comment by nilasini** [comment]
@Kanapriya can we close this issue?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
