### ISSUE TITLE
Multiple database calls inside this[1] synchronized block.

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10659]
We have found a possibility of a deadlock situation while using the JWT bearer grant flow. Due to this, the identity server can be stalled. We have found the cause and fix it in the JWT bearer grant flow. However, having this[1] synchronized block and calling multiple database calls facilitated the deadlock situation. 

As a general practice, we should not call external calls inside a synchronized block to avoid thread starvation.

After a discussion with @ruwanta, This was created to record these findings.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/242d7814f01b5eacb6880f8de12e41fe4fdbf62b/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/AbstractAuthorizationGrantHandler.java#L134

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
