### ISSUE TITLE
Doc Feedback:typo in the image 

### ISSUE THREAD

**Issue by isharac** [wso2/product-is#10666]
Location : https://is.docs.wso2.com/en/5.9.0/setup/setting-up-separate-databases-for-clustering/

typo in the image CONSECT_MGT_DB

**Comment by gomathyk** [comment]
Image replaced in 
https://is.docs.wso2.com/en/5.9.0/setup/setting-up-separate-databases-for-clustering
https://is.docs.wso2.com/en/5.10.0/setup/setting-up-separate-databases-for-clustering
https://is.docs.wso2.com/en/latest/setup/setting-up-separate-databases-for-clustering
