### ISSUE TITLE
ID Token pairwise subject identifier calculation modification

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-is#10664]
**Is your feature request related to a problem? Please describe.**
According to the [OpenID specification](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes), there are two subject identifier types used,

Public
> Same subject value is provided for all the clients. If the discovery document does not mention subject_types_supported element default is set to public.

Pairwise 
> Each client receives a different subject value, this will enable clients to correlate the End-User's activities without permission.

According to the discovery endpoint, WSO2 supports pairwise subject identifier [[Link](https://is.docs.wso2.com/en/5.9.0/learn/openid-connect-discovery/#openid-connect-discovery)]. 

**Describe the solution you would prefer**
As per the  [OpenID specification](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes) specification, there are different methods specified in which this subject identifier can be calculated.

Currently, there’s no way we can set the subject claim when building the ID token [[Link](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java)].

**Comment by mefarazath** [comment]
@DivyaPremanantha We have [two methods](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/b165b131758fd3df6f96b8c611c833972f31d7c7/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java#L310-L350) in the DefaultIDTokenBuilder which you can use to set the sub claim to the id_token?

Will this extension point fulfill your requirement?

**Comment by DivyaPremanantha** [comment]
> two methods

@mefarazath are these methods used to set a different subject claim because the naming convention (getSubjectClaim()) is misleading. In our current implementation, we override the [first method](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/b165b131758fd3df6f96b8c611c833972f31d7c7/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java#L310-L329) to set the subject claim. Is that the expected way to set a different subject claim?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
