### ISSUE TITLE
OSGi logs are persisted to a different directory rather than <IS-HOME>/repository/logs 

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10661]
Especially In the case of a containerized deployment/docker deployment, we should keep a centralized single location to keep the server log files. However, the OSGi logs are persisted in <IS-HOME>/repository/components/default/configuration directory. Which is not align with the containerized deployment industry best practices.  

This may be managed <IS-HOME>/repository/conf/etc/osgi-debug.options

![image](https://user-images.githubusercontent.com/19922157/100823067-8b701e00-3479-11eb-8f19-9b3363bbf33b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
