### ISSUE TITLE
Identity server won't start if the <IS-HOME>/repository/components/default/configuration/config.ini file was deleted mistakenly  

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10660]
If the <IS-HOME>/repository/components/default/configuration/config.ini file was deleted mistakenly, the identity server will not start and there are no any informative logs to indicate this. The behavior is once we execute the startup script, it prints the environmental details and stay still. No other logs. It is nice if we can have a record of this or improve logging.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
