### ISSUE TITLE
MTLS authentication using subject value

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-is#10665]
**Is your feature request related to a problem? Please describe.**
According to [OAuth 2.0.0](https://tools.ietf.org/html/rfc8705#section-2.1) specification, it has mentioned the subject values that need to be authenticated.

**Describe the solution you would prefer**
Currently, certificate thumbprint is used for MTLS client authentication whereas the spec specifies that the authentication can happen using the subject DN, SAN DNS, SAN URI, SAN IP or SAN email. 

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
