### ISSUE TITLE
Certificate bound access tokens for private key JWT

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-is#10663]
**Is your suggestion related to an experience ? Please describe.**
Certificate bound access tokens prevent the number of attacks on the access token by unauthorized parties. According to [rfc7800](https://tools.ietf.org/html/rfc7800) it describes how the proof of possession (PoP) where the presenter (the holder of the JWT) possess a PoP key and the recipient can cryptographically confirm the key by the presenter. 

The implementation for MTLS authenticator is currently available [[Link](https://is.docs.wso2.com/en/5.11.0/learn/mutual-tls-client-auth/#configuring-mutual-tls-client-authentication-and-certificate-bound-access-tokens)]

Issue: https://github.com/wso2/product-is/issues/8007
PR: https://github.com/wso2-extensions/identity-oauth-addons/pull/56

**Describe the improvement**
But according to [OAuth 2.0](https://tools.ietf.org/html/rfc8705) spec,

> Mutual-TLS OAuth client authentication and certificate-bound access tokens can be used independently of each other.  Use of certificate-bound access tokens without mutual-TLS OAuth client authentication, for example, is possible in support of binding access tokens to a TLS client certificate for public clients (those without authentication credentials associated with the "client_id")

So we need this implemented to be implemented in PKJWT authentication as well. Also, this support should be extended to JWTs as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
