### ISSUE TITLE
Searching by Claim URI http://wso2.org/claims/identity/accountLocked works for an individual domain but not across ALL-USER-STORE-DOMAINS

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#10673]
**Describe the issue:**
Currently in management console we can search for users using the claim url and claim value. When trying to filter users using http://wso2.org/claims/identity/accountLocked claim and value = true. This will only gives results if we specify a single user store domain and not when selected "All User Store Domains."
**How to reproduce:**
1 - Create secondary user store in WSO2IS.
2- Set account lock claim as default and set the value as true.
3 - Try to filter users with account locked claim and claim value as true. 

When select a user store domain it gives proper results. And when selected all user store domains it given null values.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0]
 
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by GANGANI** [comment]
This issue is not reproducible in the **wso2is-5.12.0-m6-SNAPSHOT** and latest WUM updated IS-5.10.0. Hence closing this issue.
