### ISSUE TITLE
Unexpected `defaultConnectorId` required to update/delete specific connectors.

### ISSUE THREAD

**Issue by yasinmiran** [wso2/product-is#10682]
## Describe the issue
Unable to delete `outbound provisioning connectors` after initial creation. When trying to `delete` or `update` a specific connector the server returns the following error. Server expect the `defaultConnectorId` not to be `null` even when the connectors aren't `enabled`.

*Error Response:*
```json
{
    "data": {
        "code": "UE-10000",
        "message": "Invalid Request",
        "description": "Property defaultConnectorId cannot be null.",
        "traceId": "2dcd1c00-5e3f-49b7-862f-f14336920211"
    },
    "status": 400,
    "statusText": "",
    "headers": {
        "content-type": "application/json"
    },
    "config": {},
    "request": {}
}
```

## Steps to reproduce

> ### Step 1
> Create an Identity Provider via **POST** `{{protocol}}://{{origin}}:{{port}}/api/server/{{version}}/identity-providers`
> 
> ### Step 2
> Create any of the two connectors via **PUT** `{{protocol}}://{{origin}}:{{port}}/api/server/{{version}}/identity-providers/:identityProviderID/provisioning/outbound-connectors/:connectorId`
> 
> ### Step 3
> Now try to delete a connector by just sending a request to **PUT** `{{protocol}}://{{origin}}:{{port}}/api/server/{{version}}/identity-providers/:identityProviderID/provisioning/outbound-connectors` with the body (without the `defaultConnectorId`) as follows: -
> ```json
> {
>     "connectors": [
>         {
>             "connectorId": "Z29vZ2xlYXBwcw",
>             "name": "googleapps",
>             "isEnabled": false,
>             "isDefault": false,
>             "blockingEnabled": false,
>             "rulesEnabled": false,
>             "properties": [
>                 {
>                     "key": "prop1",
>                     "value": "val1"
>                 }
>             ]
>         }
 >    ]
> }
> ```

### Current Workaround
The `Console` application currently sends a empty string for the `defaultConnectorId` when requesting for any updates.

### How does this affects the `Console` app?
Technically, we are able to handle this in the UI but it does not make sense to parse and attach fields (`isDefault`, `defaultConnectorId`) that irrelevant for a specific model and it can easily mislead in feature developments.

![outbound](https://user-images.githubusercontent.com/25561152/101177449-cfc40f80-366d-11eb-8003-cfc4226882c5.gif)

### Expected behavior
If there's no use-case for pretaining the `default` status of a outbound connector it should remove all the unnecessary fields and should not expect the `defaultConnectorId`.

### Environment information
 - Product Version: IS 5.11.0
 - OS: MacOS Catalina

---

### Related issues
- https://github.com/wso2/product-is/issues/9415

**Comment by yasinmiran** [comment]
Hello @emswbandara we need your input on this :)

**Comment by IsuraD** [comment]
We can make the **defaultConnectorId** as not required in the idp.yaml

```
OutboundProvisioningRequest:
      type: object
      required:
        - defaultConnectorId
      properties:
        defaultConnectorId:
          type: string
          example: U0NJTQ
        connectors:
          type: array
          items:
            $ref: '#/components/schemas/OutboundConnector'
```


This needs to be changed as follows and generate the source code. 

```
OutboundProvisioningRequest:
      type: object
      properties:
        defaultConnectorId:
          type: string
          example: U0NJTQ
        connectors:
          type: array
          items:
            $ref: '#/components/schemas/OutboundConnector'
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
