### ISSUE TITLE
Issue in adding certificate to OpenId Connect IdP in Console

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10691]
**Describe the issue:**
Unable to add or upload .pem format certificate to OpenId Connect IdP in Console. There is no error log also for this. Can't proceed after adding or upload .pem certificates. 

**How to reproduce:**
1) Login into Console and Click on **Develop** tab
2) Create "OpenId Connect" IdP
3) Click on Update icon in the created IdP
4) Select "Provide certificate" under certificate section
5) Click on "New Certificate"  and upload a certificate (ex:.pem )
6) Click on Finish

**Expected behavior:**
User should be able to successfully add or upload certificates

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0- M1
 - OS: Mac
 - Database: MySQL
 - Browser: Safari - 14.0v

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
