### ISSUE TITLE
Help panel display as empty for IdPs in Console

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10695]
**Describe the issue:**
Help panel for IdPs shows as empty.
<img width="1425" alt="Screenshot 2020-12-07 at 18 05 10" src="https://user-images.githubusercontent.com/40847371/101351563-c4aff000-38b6-11eb-8d39-3a025d01b84c.png">

**How to reproduce:**
1) Log in to the Console and click on Develop tab
2) Click on "Identity Providers"
3) Click on "New Identity Provider" and select "OpenID Connect"
4) Provide the required details and create an IdP
5) Click on Update icon in the created IdP
6) Click on the arrow which resides in upper left corner

**Expected behavior:**
Help panel should be displayed with the relevant help document list

**Environment information**
 - Product Version: 5.12.0.-M1
 - OS: Mac
 - Database: MySQL-5.7
 - Browser: Safari-14v

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
