### ISSUE TITLE
Default OutBound Provisioning Connector should be marked as "Default" in console 

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10694]
**Describe the issue:**
OutBound Provisioning Connector which wants to mark as Default won't change the text into "Default" once it marked.

<img width="1382" alt="Screenshot 2020-12-07 at 16 31 14" src="https://user-images.githubusercontent.com/40847371/101348069-105f9b00-38b1-11eb-8c95-8408a97de887.png">

**How to reproduce:**

1) Log in to the Console and click on Develop tab
2) Click on "Identity Providers"
3) Click on "New Identity Provider" and select "OpenID Connect"
4) Provide the required details and create an IdP
5) Click on Update icon in the created IdP
6) Go to "Outbound Provisioning" tab and create multiple Outbound Provisioning connectors with required details
7) Click on "Make Default" check box in any created connector 

**Expected behavior:**
<img width="1374" alt="Screenshot 2020-12-07 at 16 34 45" src="https://user-images.githubusercontent.com/40847371/101348057-0b9ae700-38b1-11eb-882b-b9bf148fc631.png">

**Environment information**
 - Product Version: 5.12.0.-M1
 - OS: Mac
 - Database: MySQL-5.7
 - Browser: Safari-14v

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
