### ISSUE TITLE
No Option to browse and attach Private Key in Google IdP configurations in Console

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10703]
**Describe the issue:**
When configuring Google IdP we need to attach a Private Key file in the provisioning configurations. But there is no option to browse and attach a Private key file.

<img width="650" alt="Screenshot 2020-12-08 at 14 38 07" src="https://user-images.githubusercontent.com/40847371/101466628-5ecf7100-3967-11eb-9ca8-15141c0d8042.png">

**How to reproduce:**
1) Log in to the Console and click on Develop tab
2) Click on "Identity Providers"
3) Click on "New Identity Provider" and select "Google"
4) Fill the General settings and click Next

**Expected behavior:**
There should be a button any method to browse and attach the private key file

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL-5.7
 - Browser: Safari-14v

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
