### ISSUE TITLE
Authentication Session Persistence must be enabled through deployment.toml or it has been already enabled in IS 5.10.0 ?

### ISSUE THREAD

**Issue by lakshithakasun** [wso2/product-is#10709]
Identity Server version : 5.10.0
Document : https://is.docs.wso2.com/en/5.10.0/learn/authentication-session-persistence

In above document it says 

> 

enable_persistence | This enables the persistence of session data. Therefore, this must be configured to true if you wish to enable session persistence.
-- | --

But it seems like this session persistence support is being already enabled after IS 5.1.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
