### ISSUE TITLE
Intermittently observing no sign-in option for Incorrect credentials in console

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10708]
**Describe the issue:**
When a user enters the wrong credentials to log in to the Console, it doesn't show any option to go to the sign-in page and enter valid credentials. This is observed intermittently.

<img width="500" alt="Screenshot 2020-12-09 at 10 29 14" src="https://user-images.githubusercontent.com/40847371/101588184-cdfea100-3a0b-11eb-9344-515c317c528e.png">

**How to reproduce:**
1) Log in to the Console with wrong credentials

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL-5.7
 - Browser: Safari 14v

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
