### ISSUE TITLE
Events for Email and SMS OTP related scenarios.

### ISSUE THREAD

**Issue by lakshani** [wso2/product-is#10706]
**Describe the improvement**

Add different events for SMS OTP and Email OTP scenarios. Need to include the below information in the event for OTP generation. 

1. **post OTP generation event**

- token value
- username
- created time
- client-related information(such as client IP, user agent, etc)
- Token validity period
- Application name
- A correlation identifier

2. **Event of OTP usage(this can be post OTP usage success and failure events)**

- used token value
- username
- used time
- client-related information(such as client IP, user agent, etc)
- A correlation identifier

**Comment by mefarazath** [comment]
@dewniMW Can we close this issue?
