### ISSUE TITLE
There is no any warning or restriction to enable account lock when the user accounts that are assigned with the Internal/system user role 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10707]
**Describe the issue:**
There are no warnings or restrictions on activating the account lock on user accounts assigned with the internal / system user role

**How to reproduce:**
Login to Console/Manage with admin credentials
2. Enable claims for account locking
3. Create a new user and assign  internal / system user role
4. Try to enable account lock
 
**Expected behavior:**
The user accounts that are assigned with the Internal/system user role cannot be locked.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12 M2
 - OS: Mac
 - Database: Oracle 19c
 - Userstore:  JDBC

---

**Comment by ayshsandu** [comment]
Intentionally the warnings or error messages are excepted for these users.

**Comment by ayshsandu** [comment]
This is the expected behaviour. It is intended to skip locking scenarios to user's who has the system role to prevent certain attacks and end user's are not required to be aware of the particulars of the occurrence.
