### ISSUE TITLE
"Locality" claim does not appear in Console User profile

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10717]
**Describe the issue:**
The "Locality" field does not appear on the User Edit page on the console, when select "Locality claim" and Support by default.

**How to reproduce:**
1. Click on List under Attribute Dialect and select http://wso2.org/claims.(Local Attributes)
2. Select the Locality claim and click Edit. Select the Supported by Default checkbox and click Update. 

**Expected behavior:**
Locality field should be display in Console/Manage/User Edit

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12 M2
 - OS: [e.g., Windows, Linux, Mac]
 - Database: Oracle 19c
 - Userstore: JDBC
- Tested Browser: Firefox

---

**Comment by IsuraD** [comment]
Use **http://wso2.org/claims/addresses.locality** claim instead of http://wso2.org/claims/locality  claim.

**Comment by IsuraD** [comment]
It is a duplicate to have both claims. Will keep it as it is, due to the backward compatibility.
