### ISSUE TITLE
[Console] Error message should display in the General settings page when creating an IdP with existing name

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10715]
**Describe the issue:**
At the moment this error message getting display when the time user clicks finish button in the IdP creation process. It should display the message when the user clicks the Next button in the "General setting" page.

<img width="500" alt="Screenshot 2020-12-09 at 14 38 58" src="https://user-images.githubusercontent.com/40847371/101609524-0fec0f00-3a2d-11eb-8fa8-d7c4de9578d9.png">

**How to reproduce:**
1) Log in to the Console and click on Develop tab
2) Click on "Identity Providers"
3) Click on "New Identity Provider" and select any IdP
4) Give the existing IdP name and proceed with the summary page
5) Click Finish button

**Expected behavior:**
The error message should display when the user clicks the Next button in the "General setting" page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL-5.7

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
