### ISSUE TITLE
Administrator's Email not validated in Google Idp

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10711]
**Describe the issue:**
Google IdP administrator's Email should properly validate. User can add any string and proceed with IdP creation.

**How to reproduce:**
1) Log in to the Console and click on Develop tab
2) Click on "Identity Providers"
3) Click on "New Identity Provider" and select "Google"
4) Add "General settings" and click Next

**Expected behavior:**
User should not be able to add an invalid format email address. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL-5.7

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
