### ISSUE TITLE
Implement a specific authenticator for Yandex federated authentication

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#10713]
**Is your feature request related to a problem? Please describe.**
Since Yandex is no longer supporting for OpenIDConnect.[1] It cannot be integrated using the default OIDC connector.

**Describe the solution you would prefer**
A specific connector for Yandex extending OAuth2 Generic Authenticator.  

**Additional context**
[1] - https://yandex.com/dev/passport/doc/dg/concepts/openid-migrate.html

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
