### ISSUE TITLE
The SCIM2 Group endpoint need to be updated with the new configurable claim for username

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#10723]
**Describe the issue:**
Related to https://github.com/wso2/product-is/issues/10631.
When primary login identifier is enabled,
adding mebenrs to SCIM2 Group or GET/Update Groups with members return the uuid(immutable identifier) of the user in the scim response.

The response should have the human readable username of the user.

**Comment by emswbandara** [comment]
@dewniMW @denuwanthi is this already fixed in public? can we close this issue?

**Comment by dewniMW** [comment]
@sathya this issue is related to [1]. Therefore the public PRs for [1] needs to be merged first.

@denuwanthi are there any more pending PRs for [1] other than ones linked to the issue?

[1] #10631
