### ISSUE TITLE
Response for search user ID by username is wrong

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10720]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the document [1] we have mentioned the request and response for search user ID by username. But the following request gives 501 not implemented as the response.

`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json"  "https://localhost:9443/api/identity/user/v1.0/pi-info?username=admin" -v -k
`

[1] https://docs.wso2.com/display/IS510/apidocs/self-registration/#!/operations#UserExport#searchUserByName

Since we are going to implement this in the future we should add the response of the search user ID by username as 501 for IS-5.10.0 and IS-5.11.0 documents.

**Describe the improvement**
The response should be "HTTP/1.1 501 Not Implemented"

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
