### ISSUE TITLE
Handle an encrpyted logout token during OIDC federated idp initiated back-channel logout

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#10726]
**Describe the improvement**

- WSO2 IS must have the capability to handle an encrypted `logout token` coming from a federated idp, if the OIDC federated idp initiated back channel logout is enabled. 
- If the `id token` encryption is negotiated during the registration, IS should decrypt the `logout token` using the specified key and algorithms during that registration. But, if the `logout token` is not encrypted even though the `id token` encryption is negotiated at the registration, IS should reject the `logout token`.

Part of Improvement identified in https://github.com/wso2/product-is/issues/9254 

**Additional context**

In the OpenID Connect Specification, they state that upon receiving a logout request, as the first step, the RP (in this case, the WSO2 IS)  MUST validate the `Logout Token` as follows,

>  If the Logout Token is encrypted, decrypt it using the keys and algorithms that the Client specified during Registration that the OP was to use to encrypt ID Tokens. If ID Token encryption was negotiated with the OP at Registration time and the Logout Token is not encrypted, the RP SHOULD reject it. 

OIDC Specification - https://openid.net/specs/openid-connect-backchannel-1_0.html

**Comment by mefarazath** [comment]
From the implementation PoV, we have to,

1. Support at option at the application configuration level to enable encrypted logout tokens
2. Support an option at the IDP configuration level to say that we will be receiving encrypted logout tokens from a federated IDP
3. Support issuing encrypted logout tokens during backchannel logout
4. Support handling encrypted logout tokens during federated IDP initiated logout

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
