### ISSUE TITLE
Issue with how MyAccount pick URLs for API calls

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#10729]
At the moment the myaccount application pick API Call URLs from the redux store. Example: https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/api/applications.ts#L53

If the server origin was changed dynamically, these URLs are not updated. We'd have to re-initialize the store using the below code.
```
store.dispatch(setServiceResourceEndpoints<ServiceResourceEndpointsInterface>(
                Config.getServiceResourceEndpoints()));
```

If we can change how the URLs are picked to below, we can overcome this issue.
`url: Config.getServiceResourceEndpoints().applications`

**Comment by brionmario** [comment]
+1

Let's do this for the `Console` as well.

/cc @DimalChandrasiri

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
