### ISSUE TITLE
[Console] Facebook IdP outbound provisioning connector details edit page fields are not visible 

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10722]
**Describe the issue:**
Outbound provisioning connectors details page fields are not visible for any of the connectors. 
And also **OutBound** should correct as **Outbound**

<img width="500" alt="Screenshot 2020-12-09 at 21 03 49" src="https://user-images.githubusercontent.com/40847371/101651538-32991a80-3a63-11eb-9473-e9b04f1847c2.png">

**How to reproduce:**
1) Log in to the Console and click on Develop tab
2) Click on "Identity Providers"
3) Click on "New Identity Provider" and select "Facebook"
4) Provide the required details and create an IdP
5) Click on Update icon in the created IdP
6) Go to "Outbound Provisioning" tab and click on "New connector"

**Expected behavior:**
Required connector detail fields should display.

  **Environment information**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL 5.7
 - Browser: Safari - 14v

**Comment by savindi7** [comment]
This issue will be closed as it is not reproducible in the product version mentioned.
