### ISSUE TITLE
Send encrypted logout token during OIDC back-channel logout

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#10727]
### Describe the improvement

- WSO2 IS must have the capability to send an encrypted logout token to a RP, if the OIDC back channel logout is enabled.
- If the id token encryption is negotiated during the registration, IS should encrypt the logout token using the specified key and algorithms during that registration, before sending it to the back-channel logout URI.

### Additional context

In the OpenID Connect Specification, they state that upon receiving a logout request, as the first step, the RP MUST validate the Logout Token as follows,

> If the Logout Token is encrypted, decrypt it using the keys and algorithms that the Client specified during Registration that the OP was to use to encrypt ID Tokens. If ID Token encryption was negotiated with the OP at Registration time and the Logout Token is not encrypted, the RP SHOULD reject it.

OIDC Specification - https://openid.net/specs/openid-connect-backchannel-1_0.html

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
