### ISSUE TITLE
Properly display the final version of selected role permission

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10737]
**Is your suggestion related to a experience ? Please describe.**
I have experience difficulties when checking the added role permission set at final wizard as mentioned below.  

![Selection_999(1194)](https://user-images.githubusercontent.com/39077751/100723562-ebb67f80-33e7-11eb-84a1-8a533389cad5.png)

![Selection_999(1195)](https://user-images.githubusercontent.com/39077751/100723578-f113ca00-33e7-11eb-957f-2b165ca59155.png)

**Describe the improvement**
Request to improve the above display which shows the selected permissions. This not user friendly since it's difficult to identify the added set of permission and their hierarchy. 
Better to display as a hierarchy.

**Comment by DimalChandrasiri** [comment]
Since the tree view is used to select permissions, the ideal way is to show a read only tree view in the summary as well.
