### ISSUE TITLE
Change required permission/scopes for POST /Users/.search, /Groups/.search, /Roles/.search REST APIs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10734]
**Is your suggestion related to a missing or misleading document? Please describe.**
Following details should be changed in IS 5.11.0 Docs, due to changes of https://github.com/wso2/carbon-identity-framework/pull/3244/.

- POST /Users/.search  (https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Users%20Endpoint/getUsersByPost)
**Permission required:**
`/permission/admin/manage/identity/usermgt/list`
**Scope required:**
`internal_user_mgt_list`
![image](https://user-images.githubusercontent.com/25483865/101854574-d380f600-3b87-11eb-99e1-11645ca5cc81.png)

- POST /Groups/.search (https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Groups%20Endpoint/getGroupsByPost)
**Permission required:**
`/permission/admin/manage/identity/rolemgt/view`
**Scope required:**
`internal_role_mgt_view` (No change required here. Doc has the correct scope)

- POST /Roles/.search (https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Roles%20Endpoint/getRolesByPost)
**Permission required:**
`/permission/admin/manage/identity/rolemgt/view`
**Scope required:**
`internal_role_mgt_view`

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2331.
