### ISSUE TITLE
OneTimePassword - Lack of information on its use

### ISSUE THREAD

**Issue by marcoranica94** [wso2/product-is#10730]
**Is your suggestion related to an experience ? Please describe.**

Hello, I'm using wso2 identity server to manage the administration. It is a very useful manager and now I am trying to use the OneTimePassword for the reset.

**Describe the improvement**

I noticed that once used, the onetimepassword information remains in the user's information and there is no way of knowing if it has been used.

Is there a particular reason why the one time password remains in the profile information? Wouldn't it be better to whiten it once used?

Maybe this possibility already exists and you need to enable it somehow in the configuration files. I couldn't find it

**Additional context**

Thanks a lot.
Bye

**Comment by ruwanta** [comment]
Thanks reporting.
This seems a bug.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
