### ISSUE TITLE
Duplicate of DOM Elemental Identity - Application > Certificates

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10745]
**Describe the Issue:**
We already define a unique id for each dom element for the test automation purpose.
Identified 2 data-testid's are duplicated.

Application > Edit > Certificate > 
2 radio buttons, 

both ekements has same data-testid
"data-testid="application-edit-general-settings-form-certificate-type-radio-group"

Please refer attached screenshot : 

![93014388-5bc61e00-f5ce-11ea-82c4-829a97559829](https://user-images.githubusercontent.com/25959096/101872846-f02f2500-3bab-11eb-98a2-e7a83ca64dd4.png)
![93014388-5bc61e00-f5ce-11ea-82c4-829a97559829 (1)](https://user-images.githubusercontent.com/25959096/101872850-f1f8e880-3bab-11eb-9694-a65691c61525.png)

**Comment by brionmario** [comment]
@NilukaSripalim 
Since this is a radio group and ATM, the form module doesn't allow to pass a data attribute to the child nodes[1], Shall we go with the following approach as a workaround. WDYT?

```ts
cy.dataTestId("application-edit-general-settings-form-certificate-type-radio-group")
            .within(() => {
                cy.get("input[value=\"JWKS\"]");
            });
```

[1] https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/applications/components/forms/general-details-form.tsx#L396
[2]  https://github.com/wso2/identity-apps/blob/master/tests/integration/applications/page-objects/application-edit-page.ts#L171

**Comment by NilukaSripalim** [comment]
can work with the proposed method as an alternative method. So we can close the issue
