### ISSUE TITLE
Created Custom UserStore Manager is not listing properly in the console UI of 5.11 IS

### ISSUE THREAD

**Issue by nisho06** [wso2/product-is#10746]
**Describe the issue:**
Custom user store manager which I create is listing properly in the mgt console, but not in the console. It is showing a blank UI with cogwheels image in it.

**How to reproduce:**
- Create a custom user store manager by extending the `UniqueIDJDBCUserStoreManager` class in 5.11 pack.
- Check this for configuring in deployment.toml config [https://github.com/wso2/product-is/issues/10582#issue-748957485](url)
- Check the drop down list of user store managers in mgt consoel using `User store -> add`... You can able to see the list properly
- Check the list of user store managers in console using `Manage -> User stores -> show more`... The UI will not be clearly visible

**Expected behavior:**
console UI of created custom user store manager should be clearly visible according to the properties of created user store manager.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.11.0]
 - OS: [ Windows, Linux, Mac]
 - Database: [MySQL]
 - Userstore: [JDBC]

**Comment by ayshsandu** [comment]
The custom user store option is not rendered properly in the console UI. Refer below image.
![custom-userstore](https://user-images.githubusercontent.com/5061791/102764742-a6132400-43a1-11eb-9099-05a706295a84.png)

There is a mapping for the UI labels for userstores at https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/userstores/constants/user-store-constants.ts#L42

When a custom usersore implementation is added, as there is no fallback mechanism implemented, the UI is not properly rendered. 

Need to implement a fallback logic for UI labels.
