### ISSUE TITLE
Secondary userstore password is not available

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10742]
**Describe the Issue:**
The secondary userstore password is not visible when already added userstore is listed from the new console. Therefore, in order to test the connection, the user has to enter the password again

**How To Reproduce:**

1. Add a userstore.
2. Navigate to the userstore listing view.
3. Select the added userstore and navigate to the `Connection` tab.
Notice that the userstore password is not there.
![Screenshot 2020-12-11 at 09 45 56](https://user-images.githubusercontent.com/39567992/101861668-9cfea780-3b96-11eb-9644-9d8a8390f2a6.png)
4. Try clicking on the `Test Connection` button and notice that there is an error.

**Expected behavior:**
Password should be displayed in masked format.

**Comment by DimalChandrasiri** [comment]
Closing this issue due to duplication. 

Original issue - https://github.com/wso2/product-is/issues/9540
