### ISSUE TITLE
After migrating from 5.7.0 to 5.10.0 tenant users can not login to the user-portal.

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10752]
In the migration logs below error is observed.
[stack.log](https://github.com/wso2/product-is/files/5680413/stack.log)

**How to reproduce:**
1. Start a 5.7.0 pack and create several tenants.
2. Do the migration as in docs.
3. Now you will see the above error. 
4. Tenant users can not log in to the system

**Expected behavior:**
Even after the migration, all should work smoothly.

**Comment by emswbandara** [comment]
@mevan-karu shall we close this issue?
