### ISSUE TITLE
Need to have samples on user create with extended SCIM 2.0 schema

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10750]
We have information on how to extend SCIM 2.0 schema to support custom attributes in https://is.docs.wso2.com/en/5.9.0/develop/extending-scim2-user-schemas/.

This also includes a sample to update the custom attribute. But this lacks a sample to create a user with the custom attribute

A sample with a body as below would be useful for a user to understand,

```
{
    "schemas": [],
    "name": {
        "familyName": "test",
        "givenName": "omindu"
    },
    "userName": "omindutest",
    "password": "test123",
    "mail": "omindu@mail.com",
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
        "customAttribute": "hgjgjhg378373637"
    }
}
```

**Comment by JKAUSHALYA** [comment]
Needs to have better samples here[1]. Currently, we have a sample for only the very basic scenario. But better to have multiple samples explaining each scenario like how to update a basic attribute, how to update an extended attribute etc... 

[1] https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/#/Me%20Endpoint/patchUserMe

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
