### ISSUE TITLE
Publish the Event Type inside the meta data for Authentication and Session event publishers.

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#10768]
**Describe the improvement**
Publish the EventType inside the metadata for the Authentication and Session event publishers. ELK integration and other third-party integrations can be benefitted from this. 

**Additional context**
Having the EventType inside the payload itself can help to prevent,
1. Custom header param for Event Type in HTTP adapter.
1. Issues with identifying the Event Type when Docker log publishing to ELK via LOGGER event adapter.

Event stream configuration should be like,

..."metaData": [
    {
      "name": "tenantId",
      "type": "INT"
    },
    _**{
      "name": "eventType",
      "type": "STRING"
    }**_
  ],
  "payloadData": [
    {
      "name": "contextId",
      "type": "STRING"
    }...

**Comment by inthirakumaaran** [comment]
We can introduce this custom header by changing the eventpublisher.xml
```
<eventPublisher name="LoggerOutputEventAdapter" statistics="disable" trace="disable" xmlns="http://wso2.org/carbon/eventpublisher">
  ....................
  <to eventAdapterType="logger">
    <property name="uniqueId">log_id</property>
  </to>
</eventPublisher>
```
Docker integration has an issue due to Docker log appends timestamps as prefix to each line and this can be handled on docker side.
