### ISSUE TITLE
Performance issue with "Active Session Count"

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#10767]
**Describe the issue:**
Visible performance drop when enabling "Active session count" with the session event publisher.

**Test conditions**
1. 10 minutes
1. 150 concurrent users
1. LOGGER and HTTP event adapter types.

**Results**

Analytics | Session Count | Event Publisher (Adapter)|Duration | Concurrent Users | Throughput (Requests/sec) | Average Response Time (ms)
-- | -- | -- | --|-- | -- | --
NO | NO | NONE | 10 mins | 150 | 182.33 | 821.97
YES | NO | HTTP | 10 mins | 150 | 176.37 | 849.85
YES | NO | LOGGER | 10 mins | 150 | 161.24 | 929.76
YES | YES | HTTP | 10 mins | 150 | 24.85 | 6015.59
YES | YES | LOGGER | 10 mins | 150 | 24.74 | 6038.08

**Related query**

[org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SQLQueries.java](https://github.com/wso2/carbon-identity-framework/blob/d528bd750acd769deeb3f468652cdf341930824e/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SQLQueries.java#L127)

`public static final String SQL_GET_ACTIVE_SESSION_COUNT_BY_TENANT =
            "SELECT COUNT( DISTINCT IDN_AUTH_SESSION_META_DATA.SESSION_ID) " +
                    "FROM IDN_AUTH_SESSION_META_DATA INNER JOIN IDN_AUTH_USER_SESSION_MAPPING " +
                    "ON IDN_AUTH_SESSION_META_DATA.SESSION_ID = IDN_AUTH_USER_SESSION_MAPPING.SESSION_ID " +
                    "INNER JOIN IDN_AUTH_SESSION_STORE " +
                    "ON IDN_AUTH_USER_SESSION_MAPPING.SESSION_ID = IDN_AUTH_SESSION_STORE.SESSION_ID " +
                    "WHERE IDN_AUTH_SESSION_META_DATA.PROPERTY_TYPE = ? AND IDN_AUTH_SESSION_META_DATA.VALUE " +
                    "BETWEEN ? AND ? AND IDN_AUTH_SESSION_STORE.TENANT_ID = ? ";`

**Environment information**
 - Product Version: IS 5.9.0 (Tested) and UP
 - OS: Ubuntu 18.04 LTS
 - Database: H2
 - Userstore: read_write_ldap_unique_id

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
