### ISSUE TITLE
Improving the account recovery claims modifications

### ISSUE THREAD

**Issue by yasinmiran** [wso2/product-is#10761]
## Is your suggestion related to an experience? Please describe.
Once a user sets the recovery email and configures 2 security questions, the same user can update the sensitive claims without verifying `it’s the user who is initiating` this change request. This applies for the email recovery field as well. In the below GIF it shows how an authenticated user can modify previously configured account’s recovery options easily without verifying.

![Problem](https://user-images.githubusercontent.com/25561152/102051841-3209d680-3e0b-11eb-8bd8-e5ae8b863bfe.gif)

## Describe the improvement
Set a `precondition` to reauthenticate when adding/modifying `security questions` or when changing the `recovery email`.

![Recovery Flow](https://user-images.githubusercontent.com/25561152/102051817-274f4180-3e0b-11eb-9bd3-438793a3ec25.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
