### ISSUE TITLE
[Console] No option to select and add User Lite-Sign-Up purposes

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10775]
**Describe the issue:**
There are no options to select and add Lite-Sign-Up new purposes in Lite User registration.

<img width="600" alt="Screenshot 2020-12-15 at 13 39 54" src="https://user-images.githubusercontent.com/40847371/102189603-e7588f00-3edc-11eb-9453-b471c0d1f4a0.png">

**How to reproduce:**

1. Log in to the console
2. Click on Manage Tab
3. Click on User Onboarding and click on Lite User Registration

**Expected behavior:**
How it implemented in Mgt console

<img width="600" alt="Screenshot 2020-12-15 at 13 54 46" src="https://user-images.githubusercontent.com/40847371/102189892-52a26100-3edd-11eb-8365-6294b8f291d6.png">

<img width="600" alt="Screenshot 2020-12-15 at 13 54 30" src="https://user-images.githubusercontent.com/40847371/102189909-5635e800-3edd-11eb-9942-4bff453bd616.png">

 **Environment information**
 - Product Version: 5.12.0-M1
 - OS: Mac
 - Database: MySQL 5.7
 - Browser: Safari - 14v

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
