### ISSUE TITLE
custom local Attributes are not displayed in  the user profile.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#10776]
**Describe the issue:**
Even, enabled "Show this attribute on user profile and user registration page", 
attributes are not displayed in the user profile.(console /Manage)

**How to reproduce:**

1. click on Attribute Dialects in Console/Manage Left side panel
2. Click Add Local Dialect
3. Click Add New Local Attribute
4. add a new Attribute Ex: nationality
5. Fill the required information in the form and tick the "Show this attribute on user profile and user registration page" check-box
6. Add Attribute ID http://wso2.org/claims/nationality
7. Map Attributes, ex Mapped Attributes: country
8. view user profile

**Expected behavior:**
this attribute should be displayed on the user profile

**Environment information** 
 - Product Version: IS 5.12 M2
 - OS: Mac
 - Database: Oracle 19c
 - Userstore: JDBC

---

**Comment by ayshsandu** [comment]
Whenever you add a new local claim you need to add it to the relevant external claim dialects. In that case, this custom claim needs to be added to `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` dialect in-order it to be reflected in the user account.
