### ISSUE TITLE
Check WSO2 IS compatibility with Java on Arm

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#10771]
**Is your feature request related to a problem? Please describe.**

AWS EC2 instances support Graviton Processor. Need to check the compatibility of WSO2 Identity Server with ARM JVM.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
