### ISSUE TITLE
[Doc] Update userstore configuration REST API

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#10798]
**Describe the improvement**
Need to update https://is.docs.wso2.com/en/latest/develop/userstore-rest-api once https://github.com/wso2/identity-api-server/pull/250 is merged as it brings changes to the REST api.

**Related Issues:**
https://github.com/wso2/product-is/issues/10670

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
