### ISSUE TITLE
Investigate the reason for the cypress integration test failures in build time

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#10799]
**Describe the issue:**
All the identity apps cypress integration tests passed locally within the identity-apps repo. But some of the test cases fail when it's integrated with the identity server build time. Needs to further investigate the root cause for this failure.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
