### ISSUE TITLE
Confirmation code gets invalidate during an error in the ChannelVerifiedTenantsApi flow

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10797]
**Describe the issue:**
According to the implementation of the `ChannelVerifiedTenantsApiService`, we are invalidating the confirmation code even before we create the tenant. So if an error occurred while creating the tenant (Eg: Existing tenant domain name), the user does not get a chance to re-try again.

**How to reproduce:**
**NOTE:** email username needs to be configured.
1. Create a tenant domain.  Eg: test1.com
2. Enable lite user registration and register a user.
3. Navigate to the email and copy the confirmation code in the confirmation code.
4. Open ChannelVerifiedTenantsApiService, create tenant API.
5. Add the received confirmation code and provide the same tenant domain as before. Notice that you will get an error.
6. Now try with a different tenant domain name.

**Expected behavior:**
The user should be able to retry with the same code since there is no way to get another confirmation code.

**Environment informatio:n** 
 - Product Version: 5.12.0

**Comment by Maliesha** [comment]
According to [1], we can use the following curl command to resend the confirmation code in Lite User Registration. 
```
curl --location --request POST 'https://localhost:9443/t/carbon.super/api/identity/user/v1.0/resend-code' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "user": {
        "username": "malieshakalutota@gmail.com",
        "realm": "PRIMARY"
    },
    "properties": [
        {
            "key": "RecoveryScenario",
            "value": "LITE_SIGN_UP"
        }
    ]
}'
```
So we can use the above curl command to get a new confirmation code if the confirmation code gets invalidated during an error in the ChannelVerifiedTenantsApi flow.

[1] [https://github.com/wso2/product-is/issues/13468](https://github.com/wso2/product-is/issues/13468)
