### ISSUE TITLE
Unable to add user with ask password option from the console app

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#10792]
**Describe the issue:**

Adding a user with the ask password option from the new console app fails.
<img width="1439" alt="Screen Shot 2020-12-16 at 1 32 23 PM" src="https://user-images.githubusercontent.com/525801/102410639-ac6e5e00-3fa5-11eb-875a-b0b0e4251585.png">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-5.11.0
 - OS: Mac
 - Database: H2
 - Userstore: Default

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ayshsandu** [comment]
A related issue: https://github.com/wso2/product-is/issues/10597
