### ISSUE TITLE
Add missing Userstore configurations in Console

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10809]
**Describe the issue:**
There are few configuration level fields are missing in the console UI. Needs to add support for those configurations in Console.  

1. User DN Pattern
2. Display name attribute

**Related issues:**
https://github.com/wso2/product-is/issues/9820

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
