### ISSUE TITLE
Missing configuration level fields in Resident Identity Provider

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10807]
**Describe the issue:**
There are two configurations level fields in Resident Identity Provider are missing in the current console.

1. Idle Session Time Out
2. Remember Me Period

<img width="600" alt="Screenshot 2020-12-18 at 10 15 40" src="https://user-images.githubusercontent.com/40847371/102575795-0a23b700-411a-11eb-8185-df21a2291470.png">

**Related issues:**
https://github.com/wso2/product-is/issues/9820

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
