### ISSUE TITLE
Add Adaptive function library support

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10803]
**Describe the issue:**
In the current implementation of the console, there is no feature to add Adaptive function libraries.  We need to add that feature from the Management console to console.

**Related issues:**
https://github.com/wso2/product-is/issues/9820

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
