### ISSUE TITLE
Add support for Consent Purpose Management 

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10808]
**Describe the issue:**
We need to add support for consent purposes in the console. Currently, consent purpose can be defined through the management console. 

<img width="600" alt="Screenshot 2020-12-18 at 10 33 33" src="https://user-images.githubusercontent.com/40847371/102577361-eb272400-411d-11eb-8434-1730f15e27d0.png">

**Related issues:**
https://github.com/wso2/product-is/issues/9820

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
