### ISSUE TITLE
Add support to export XML as a file for Applications

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10806]
**Describe the issue:**
Currently, we do not support to export the created Applications as an XML file in Console. We needs to add support for that. 

<img width="600" alt="Screenshot 2020-12-18 at 10 06 36" src="https://user-images.githubusercontent.com/40847371/102575304-e0b65b80-4118-11eb-86d7-e415ff3f5506.png">

**Related issues:**
https://github.com/wso2/product-is/issues/9820

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
