### ISSUE TITLE
Ability to configure the order of a tomcat valve in the Identity Server

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10805]
As in the topic, it would be nice to have a way to configure the order of the tomcat valves we have configured in the catalina-server.xml file

**Comment by sachiniWettasinghe** [comment]
Certain default tomcat valve configurations in the `catalina-server.xml` file have to be in the same order as they are already configured, and hence it is not recommended to have a way to configure the order of these tomcat valves. 

While analysing the above it was identified that `org.apache.catalina.valves.RemoteIpValve` [1] has to be added to the valve list of `catalina-server.xml`. This is addressed by the PR in [2].

[1] https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html
[2] https://github.com/wso2/product-is/pull/10990

**Comment by emswbandara** [comment]
@sachiniWettasinghe , since deprecating getClientIpAddress util method is an independent task, let's close this issue.
