### ISSUE TITLE
Remove application owner from client credential OAuth tokens

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10810]
Current when a client credential OAuth token is generated the application owner is set as the user of the token. The token will also receive the privileges of the user. The application owner associated with the token should be removed. This needs to be done with backward compatibility as this capability could be being used.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
