### ISSUE TITLE
Callback url of the system portal needs to be updated with the tenant qaualified callbacks

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#10813]
With https://github.com/wso2/product-is/issues/10780, we have changed the system portal default post logout redirect URL to be tenant qualified. So the application callback URL has to include the tenant qualified URL

When migrating to 5.12.0, we need to add the tenant qualified console and myaccount login page as the redirect URL in those application oAuth configurations.

```
regexp=(https://<hostname>/console/login|https://<hostname>/t/(.*)/console/login)
```

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
