### ISSUE TITLE
[Console] Login page redirecting to an intermediate page

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-is#10812]
**Describe the issue:**
After entering valid credentials to log in to console, it's redirecting to intermediate UI and then show the console dashboard. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/40847371/102610390-1e37da80-4153-11eb-8724-412f2e5b8f57.gif)

**How to reproduce:**
1. Go to the Console
2. Add credentials
3. Click continue

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-M4
 - OS: Mac
 - Database: H2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
