### ISSUE TITLE
External Vault Support for Carbon Configurations

### ISSUE THREAD

**Issue by sanduniNagahage** [wso2/product-is#10822]
**Describe the improvement**
This is intended to provide the support to extend the existing Secure Vault capabilities to cater for the cloud secure vault services such as AWS Secret Manager, Azure Key vault and HashiCorp Vault and Hardware Security Modules etc. As the existing implementation cannot be extended to cater for this requirement. 

**Link to the Document**
https://docs.google.com/document/d/1BF0h8RD8ikCQ8Octovhz2b0PGOPJLTkXae7xAnbPXOM/edit?usp=sharing

**Related Issues:**
[Core support for external Vault Support for Carbon Configurations](https://github.com/wso2/product-is/issues/9149)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
