### ISSUE TITLE
Lite User Registration configs are not available in the j2 templates

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10825]
The PR https://github.com/wso2-extensions/identity-governance/pull/397 introduces a new feature to perform lite user registration. Currently, we can enable this feature via the UI, but the j2 template configs are missing. Need to add config [1] to the templates and default files. 
NOTE: By default, this needs to be set to `false`.

[1] - https://github.com/wso2-extensions/identity-governance/pull/397/files#diff-3040477809cbb5d4423ab760bacc6699f38ac48ad66cf64e7612cb5f1fd4176dR431

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/9422
