### ISSUE TITLE
Rename Asgardio Authentication SDKs to Asgardeo SDKs

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10824]
Following actions needs to be done in-oder to complete the renaming.
**.NET**
- [ ] Rename Repo
- [ ] Rename Code components
- [ ] Fix documentation
- [ ] Configure builder workflows
- [ ] Deprication strategy
- [ ] Rename releases/release commits
- [ ] Rename Nuget Organiztion and user

**Android** 
- [ ] Rename Repo
- [ ] Rename Code components
- [ ] Fix documentation
- [ ] Configure builder workflows
- [ ] Deprication strategy
- [ ] Rename releases/release commits
- [ ] Rename Bintray Organiztion and user

 
**Java-SAML**   
- [ ] Rename Repo
- [ ] Change components
- [ ] Rename releases/release commits
- [ ] Remove/Deprecate Old packages

 
**Java-SAML-Tomcat-Agent**
- [ ] Rename Repo
- [ ] Change components
- [ ] Fix documentation
- [ ] Rename DockerHub Organiztion and user
- [ ] Remove previous Docker images
- [ ] Rename jenkins bot
- [ ] Rename releases/release commits

 
**Java-OIDC**   
- [ ] Rename Repo
- [ ] Change components
- [ ] Rename releases/release commits

 
**Java-OIDC-Tomcat-Agent**   
- [ ] Rename Repo
- [ ] Fix documentation
- [ ] Change components
- [ ] Rename releases
- [ ] Remove previous Docker images
- [ ] Rename jenkins bot
- [ ] Rename releases/release commits
 

Effort:: 5

**Comment by piraveena** [comment]
@ayshsandu Do we have anything pending in this task? Can we close this issue?

**Comment by ayshsandu** [comment]
This is now completed. Hence, closing.
