### ISSUE TITLE
New function for adaptive authentication to retrieve claims of associated user

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#10821]
**Description**
When a user is authenticated using a federated authentication flow and mapped to a local user account by user account association through adaptive authentication, we can't get the associated user claims as identity server is not expecting that there is an association at this point since the association is handled through post auth handlers. 

Therefore to get the associate user claim values, a custom adaptive authentication function needs to be implemented. Since this is a valid requirement, it would be better if we can introduce a new JS function for adaptive authentication to retrieve the associate user claims.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
