### ISSUE TITLE
ReadOnly Userstores are listed in the allowed userstores list in user creation page.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10842]
**Describe the issue:**
In the new console app, when adding a new user, we can see the read-only user stores in the dropdown. But in the management console, this is handled.

**How to reproduce:**
1. Create a secondary user store and make it read-only.
2. Navigate to the management console and click on add user. Notice that in the domains drop-down we cannot see the read-only user store domain name.
3. Now navigate to the new console app, navigate to the Manage section, and click on `+New User`. Notice that the read-only user store is also visible.

**Expected behavior:**
ReadOnly users store should not be listed in the new console application.

**Environment information** 
 - Product Version: 5.12.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
