### ISSUE TITLE
Improvements required for the Session Extender endpoint

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#10856]
1. The client initiating the session extension request needs to be identified and tracked in logs and events fired.
2. A unique 'isk' value needs to be issued for each application.

###### Related issues:
https://github.com/wso2/product-is/issues/10560

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
