### ISSUE TITLE
Generic error logged in audit logs due to %s missing in the ERROR_CODE_ERROR_WHILE_AUTHENTICATION message

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#10854]
**Describe the issue:**
A Generic error is logged in audit logs every time in case of authentication failure due to %s missing in the ERROR_CODE_ERROR_WHILE_AUTHENTICATION message[1].

```
ERROR_CODE_ERROR_WHILE_AUTHENTICATION("31001", "Un-expected error while authenticating"),
```

During authentication failures, we adding the exception message using String.format() as shown below.

```
String.format(ErrorMessages.ERROR_CODE_ERROR_WHILE_AUTHENTICATION.getMessage(), e.getMessage())
```
However, since the %s is missing we are not getting the exception message.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

[1]https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/constants/UserCoreErrorConstants.java#L58

**Comment by emswbandara** [comment]
@ShanChathusanda93 shall we merge the public PR and close this issue?

**Comment by ShanChathusanda93** [comment]
Closing the issue since the public PR is merged.
