### ISSUE TITLE
Behaviour of SSOService.SLOSAMLSOAPBindingEnabled config is unknown

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10851]
**Describe the issue:**
In the SAML inbound [code](https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/0ccfaaa853f30e700884c5bf5f47111b91724531/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/logout/LogoutRequestSender.java#L159-L168), we have a configuration check for SSOService.SLOSAMLSOAPBindingEnabled value and based on the value we decide whether the SLO Request to the SAML participants needs to be wrapped in a SOAP message.

But it seems the default value of SSOService.SLOSAMLSOAPBindingEnabled is false. ie. This configuration is not to be seen in the identity.xml or in the templated identity.xml.j2 file.

According to this [spec](http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#5.3.2.SP-Initiated%20Single%20Logout%20with%20Multiple%20SPs|outline) section 5.3.2,

> Having determined that other service providers are also participants in the web SSO session, the identity provider similar sends a <LogoutRequest> message to those providers. In this example, there is one other service provider, sp2.example.edu. The <LogoutRequest> message is sent using the SOAP over HTTP Binding.

It looks like the default behaviour should be sending the LogoutRequests as a SOAP message.

So there are few things we need to clarify/fix,

1. Do we need a configuration to determine this behaviour or should it always be as a SOAP message?
2. Template the configuration (We might need to do it for the sake of backward compatibility)

**Expected behaviour:**
Determine the purpose of the configuration and keep the expected behaviour to be the default

**Comment by mefarazath** [comment]
The PR adding this config was done to fix https://wso2.org/jira/browse/IDENTITY-3578

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
