### ISSUE TITLE
Need a document on customizing governance connectors

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10852]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently, we don't have a central place where we are mentioning all the governance connectors and the procedure to customize them. We should create a document for that and include the confidential property introduced in [1]

[1] https://github.com/wso2/product-is/issues/10620

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
