### ISSUE TITLE
[Doc]Missing configurations in MFA integration for WSO2 IS Management Console

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#10850]
**Is your suggestion related to a missing or misleading document? Please describe.**
There're few configurations missing in the "Configuring Multi-factor Authentication for WSO2 Identity Server's Management Console"[1] document. 
 
**Describe the improvement**
In addition to exiting configurations in the document, the following configurations need to be added to the deployment.toml.  
```
[admin_console.authenticator.saml_sso_authenticator]
assertion_consumer_service_url = "https://localhost:9443/acs"
identity_provider_sso_service_url = "https://localhost:9443/samlsso"
```

---
[1]https://is.docs.wso2.com/en/5.10.0/learn/multi-factor-authentication-for-wso2-is-management-console/

**Comment by rksk** [comment]
Related https://github.com/wso2/product-is/issues/11809
