### ISSUE TITLE
Support capability to configure customMapping of SMSPublisher.xml via deployment.toml

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10859]
**Describe the issue:**

This issue is created to track the improvement mentioned in https://github.com/wso2-extensions/identity-event-handler-notification/pull/137#discussion_r547682892 (Improvement to: https://github.com/wso2-extensions/identity-event-handler-notification/pull/137/)

When Adding the feature of tenant wise email and SMS provider configuration support, we introduced a SMSPublisher.xml file that doesn't contain an inline body. The user has to replace the inline body according to the selected SMS provider's (Vonage. Twillio, etc) SMS send API body.

Instead of manipulating the SMSPublisher.xml file, we need to add the capability to configure the inline body of the SMS event publisher by taking the inputs via deployment.toml.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
