### ISSUE TITLE
[QSG] Unable to work when IS is hosted on a separate server

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10865]
**Describe the issue:**

Even we configure "wso2is.host.domain" in <IS_SAMPLE_DISTR>/IS-QSG/conf/server.properties file, the web app uses localhost as the IdPURL. The only option seems to be repacking the web after extracting and changing sso.properties of each war.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
