### ISSUE TITLE
Configuration guidelines for some membership schemes are missing

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10862]
In the document [1], it has mentioned multiple membership schemes as following.

WSO2 supports the following membership schemes for clustering 
- Well-known address (WKA) 
- Multicast membership 
- AWS membership 
- AWS ECS membership 
- Kubernetes membership

But only `WKA` and `AWS ECS` are described in the configurations section.

**Affected versions**
IS 5.9.0 upwards

**Additional info**
Documents on the Kubernetes membership scheme & AWS membership scheme for the previous configuration model can be found at [2] & [3].

[1] https://is.docs.wso2.com/en/latest/setup/deployment-guide/#clustering-related-configurations
[2] https://docs.wso2.com/display/CLUSTER44x/Setting+Up+a+Cluster+in+Kubernetes+Mode
[3] https://docs.wso2.com/display/CLUSTER44x/Setting+Up+a+Cluster+in+AWS+Mode

**Comment by isuruirj** [comment]
In addition to the above, in the document [1], Kubernetes membership is missing from the list of available membership schemes.

[1] - https://is.docs.wso2.com/en/latest/administer/clustering-overview/#about-membership-schemes

**Comment by rksk** [comment]
Current status
- [x] Well-known address (WKA) 
- [ ] Multicast membership 
- [ ] AWS membership 
- [x] AWS ECS membership 
- [x] Kubernetes membership

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
