### ISSUE TITLE
Unusual drop of throughput in 'Authenticate Super Tenant User' performance test in multiple concurrencies that occurs intermittently

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#10869]
**Describe the issue:**
When running the performance tests for WSO2 IS 5.11 GA in a 2 node cluster (for both 2 core, and 4 core instances), it can be observed that the number of samples/average throughput is unusually dropped for one or more concurrencies (number of concurrent users). The concurrencies in which this drop occurs vary from run to run (Out of the test runs performed, this drop mostly happened to 100, 500 concurrencies). The following is the results of one such run. The sample count of concurrency 100 and 500 are unusually low compared to other concurrencies.

Scenario Name | Concurrent Users | # Samples | Throughput (Requests/sec) | Average Response Time (ms)
-- | -- | -- | -- | --
Authenticate Super Tenant User | 50 | 857838 | 1787.25 | 27.79
Authenticate Super Tenant User | 100 | **329873** | **687.06** | **145.4**
Authenticate Super Tenant User | 150 | 847491 | 1765.59 | 84.76
Authenticate Super Tenant User | 300 | 849685 | 1769.97 | 169.32
Authenticate Super Tenant User | 500 | **314547** | **654.22** | **760.28**

- Out of the 3 full performance test runs (ran all test scenarios), this issue was observed in all 3 runs.
- Out of the 3 times where I tried to run only the authentication scenarios (for all concurrencies in one run), this issue occurred in all 3 times. 
- When trying to run a single concurrency only in a single run, this issue occurred only for the case where the concurrent user count was 300. When trying to run the same test again for 300, the issue was not observed.
- All above 3 observations are for 4 core IS instances.
- Also ran one full performance test and one test with only the authentication scenario set in a 2 node cluster of 2 core IS instances, and the issue was observed in both those runs.
- This issue seem to be occurring intermittently, but the frequency of happening this is high.

**How to reproduce:**
Run the 'Authenticate Super Tenant User' performance test and observe the results for all concurrencies.

**Expected behavior:**
There should not be an unusual drop in sample counts for random concurrencies,

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11 GA
 - In AWS stack where we usually run performance tests.
 - For both 2 core (c5.large) and 4 core (c5.xlarge) instances in a 2 node cluster

---

**Comment by DinikaSen** [comment]
After analyzing the issue further, the root cause for this issue was found. It was observed that the issue only occurs in a clustered environment when the concurrent thread count is considerably high. The reason for the issue is as follows.

- During the admin user authorization part of the 'Authenticate Super Tenant User' test case, the authorization cache is checked first to see if the user is authorized to access the particular resource. 
- If the user is not in the authorization cache, the role list of user is retrieved to check whether the user is authorized. There, the user role cache is checked first and then the DB is queried to get the role list of user.
- Since there is a large number of concurrent threads, more than one thread miss the authorization cache and the user role cache. Hence, all those threads query the DB concurrently, retrieve the user role list, and update the user role cache with the same value again and again. 
- Since the cache is distributed in the clustered setup, when the user role cache is updated, one node sends the role cache update information to the other node and vise versa.
- This results in the user role cache being invalidated again and again. When the user role cache is invalidated, the authorization cache is invalidated too. Hence, the incoming threads also miss authorization and user role caches, and they also access the DB to get user roles and try to update the user role cache.
- This continues resulting in thousands of DB calls querying the same SQL command -  `SELECT UM_ROLE_NAME FROM UM_HYBRID_USER_ROLE, UM_HYBRID_ROLE WHERE UM_USER_NAME='admin' AND UM_HYBRID_USER_ROLE.UM_ROLE_ID=UM_HYBRID_ROLE.UM_ID AND UM_HYBRID_USER_ROLE.UM_TENANT_ID=-1234 AND UM_HYBRID_ROLE.UM_TENANT_ID=-1234 AND UM_HYBRID_USER_ROLE.UM_DOMAIN_ID=(SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE UM_TENANT_ID=-1234 AND UM_DOMAIN_NAME='PRIMARY').`
- It results in database CPU hitting 100%, ultimately reducing the throughput by more than 50%.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
