### ISSUE TITLE
Need to improve "Configuring My Account Application" content

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#10860]
**Is your suggestion related to a missing or misleading document? Please describe.**
https://is.docs.wso2.com/en/5.11.0/develop/configure-my-account/

Here it is mentioned to edit the `deployment.config.json` file to customize the my account application. Where it has not mentioned that it is required to edit only if the application will be hosted externally, and if it is to change value on the application which shipped in the Identity Server product by default and keep hosted in the Identity Server as it is, it is required to edit the `deployment.toml` file instead. Where it will persist the changes on server restart.

**Describe the improvement**
Improve the doc as mentioned above.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
