### ISSUE TITLE
Username renaming feature related docs are not available 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10863]
**Is your suggestion related to a missing or misleading document? Please describe.**
The configurations related to username renaming is not found in the WSO2 documentation.

Docs related to https://github.com/wso2/product-is/issues/10631

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
