### ISSUE TITLE
Google outbound provisioning connector wizard's inputs are not descriptive

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10875]
**Is your suggestion related to an experience ? Please describe.**
When creating a google outbound provisioning connector using the given template via the console, input fields are confusing.

**Describe the improvement**
![google-prov-claim](https://user-images.githubusercontent.com/5061791/103523599-1a6dbd00-4ea2-11eb-8372-1814b5817305.png)

- Give placeholder or sample values. 
- populate from existing claims dropdown. 
- Refer management console as a reference
![google-prov-mgt-console](https://user-images.githubusercontent.com/5061791/103529708-265e7c80-4eac-11eb-888c-2902976211a4.png)

- 
**Additional context**
- Improve the descriptions to more meaningful ones to explain what the purpose of each field.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
