### ISSUE TITLE
Error codes have to be changed accordingly in token endpoint response in device auth code grant flow

### ISSUE THREAD

**Issue by SupunSPWithana** [wso2/product-is#10884]
**Describe the issue:**
The error codes showing currently are not RFC matching in token endpoint response in Device auth code grant flow.

**How to reproduce:**
Can be changed accordingly to the RFC standard through the code level.

**Expected behavior:**
(According to the RFC)
https://tools.ietf.org/html/rfc8628

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

**Related issues:**
https://github.com/wso2/product-is/issues/9060

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
