### ISSUE TITLE
Rule based application discovery in myaccount portal 

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#10880]
**Is your feature request related to a problem? Please describe.**

Right now all the applications which are marked as discoverable are visible in the `myaccount` portal but there are usecases where there is a need to filter apps based on roles, tenant, etc

**Describe the solution you would prefer**

**Additional context**

**Comment by svenzimmermann** [comment]
Especially if you use role-based PDP policies like we do, apps that are discoverable by all are unfavorable. This leads us again and again to level 1 support requests. From my point of view this would be a very important feature!

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
