### ISSUE TITLE
Incorrect Postman Collection in the claims REST API

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10885]
The claims management [REST API document ](https://is.docs.wso2.com/en/5.10.0/develop/claim-management-rest-api/) contains invalid postman collection which has the samples for `WSO2 Identity Server - User's Challenge Questions and Answers API Definition. `

It needs to point to claim management postman collection.

**Comment by AnuradhaSK** [comment]
duplicate https://github.com/wso2/product-is/issues/9737
