### ISSUE TITLE
[Migration] Need to change IDN_OAUTH2_TOKEN_BINDING table

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#10883]
**Description:**
With this https://github.com/wso2/product-is/issues/10481, we changed IDN_OAUTH2_TOKEN_BINDING table structure. This addresses the DB changes. https://github.com/wso2/carbon-identity-framework/pull/3303/files

We need to 
1. Drop `PRIMARY KEY (TOKEN_ID)` column
2. Add a new unique key as `UNIQUE (TOKEN_ID,TOKEN_BINDING_TYPE,TOKEN_BINDING_VALUE)`

**Comment by ashendes** [comment]
Migration is currently failing in this step in a Postgres env.
