### ISSUE TITLE
Lite User Registration can't be turned on by default. 

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#10896]
**Describe the issue:**
I need to turn on Lite User Registration by default when the pack starts up through a config. This is not possible with existing configs 

[identity_mgt]
events.schemes.liteUserRegistration.properties.enable = true

This is not getting affected.

**How to reproduce:**
Add the above config to deployment.toml and start a fresh pack. Still the lite user registration is not enabled in resident idp configs when look after logging into admin console. 

**Expected behavior:**

It should be enabled when the server is started freshly

**Comment by ayshsandu** [comment]
@hasinthaindrajee can you try the below configuration,

```
[identity_mgt.events.schemes."liteUserRegistration".properties]
"enable"=true
```

**Comment by IsuraD** [comment]
That configuration is read from the identity.xml [1] which is not templated. We need to template it. 

[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/connector/LiteRegistrationConfigImpl.java#L143

**Comment by AnuradhaSK** [comment]
Use the following config to enable the lite user registration via deployment.toml config
```
[identity_mgt]
lite_user_registration.enable=true
```
