### ISSUE TITLE
SCIM2 List users result count is incorrect

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#10898]
**Describe the issue:**

There is an issue regarding the incorrect result count in the SCIM2 list users API if there are duplicate usernames in the user store. As an example below,

```
GET https://localhost:9443/scim2/Users?startIndex=0&count=100

The total result is 97.
```

As for the analysis, we noticed that 100 users were retrieved from their user store correctly. But there are few duplicate users, within the first 100 results. 

So from our SCIM2 implementation, we have used a TreeSet to sort the users [1].
```
TreeSet<User> scimUserSet = new TreeSet<>(Comparator.comparing(User::getUsername));
scimUserSet.addAll(scimUsers);
return scimUserSet;
```

Due to this, it will drop the duplicate usernames from the total result, and the final user count becomes a lesser number. 

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3573

There are multiple places we have used the same implementation in SCIMUserManager.  We need to consider all of them when fixing.

**Comment by emswbandara** [comment]
@ChamathNS please update docs as well regarding the config we introduced
