### ISSUE TITLE
Script not getting saved properly via the Sign On Method tab for Applications in the Console

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#10893]
**Describe the issue:**
The script for adaptive authentication is not getting saved properly when adding a Sign On Method for Applications in the (Asgardeo) Console app.

The following screenshot shows the script the in the editor before updating the application.
![Screenshot from 2021-01-05 19-19-11](https://user-images.githubusercontent.com/25567263/103655251-fb982500-4f8c-11eb-9f3d-c546500daad0.png)

The screenshot below shows the script that is being actually being saved.
![Screenshot from 2021-01-05 19-20-07](https://user-images.githubusercontent.com/25567263/103655317-11a5e580-4f8d-11eb-918b-dfc5815ce5c4.png)

The script is being saved as a single string.

**How to reproduce:**
1. Login to (Asgardeo) Console.
2. Create an application.
3. Go the Application configuration -> Sign On Method tab.
4. Click update.
5. Observe script in the Management Console.

**Expected behavior:**
Script should be saved as it is.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Asgardeo [IS version - 5.12.0-m4]

**Related Issues:**
https://github.com/wso2-enterprise/asgardeo-product/issues/628

**Comment by DimalChandrasiri** [comment]
This issue was mentioned here https://github.com/wso2/product-is/issues/10550 and is fixed by this PR https://github.com/wso2/identity-apps/pull/1464. The fix will be available along with the `m5` release.
