### ISSUE TITLE
Improve the solution to navigate back to multi option page after selecting a multi option

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10905]
**Describe the issue:**
Current approach:

Currently, the flow is, when we land on the multi-option login page we capture that particular URL (URL of the multi-option display page). We pass this as a query param to an authenticator(multi-option selection) selected.

The authenticators use this query param to navigate back from their respective input pages.

- If I take TOTP as an example when someone selects TOTP as an option, we pass &multiOptionURI= to the TOTP authenticator.
- When TOTP redirects to its input page, it makes use of the URL sent in multiOptionURI to allow a user to navigate back to the multi-login page.

![image](https://user-images.githubusercontent.com/5237653/103780593-3072ad80-505b-11eb-80d5-e12aea005712.png)

I feel this is approach isn't optimal and would result in duplicate logic in each authenticator.

The suggestion is to improve this so that the solution is easily applicable to any authenticator without the involvement of capturing URLs and passing them around in query params.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
