### ISSUE TITLE
Bulk User Import with Multiple User Roles

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#10909]
**Is your suggestion related to a missing or misleading document? Please describe.**
Bulk user import with multiple user roles using csv file is missing.

**Describe the improvement**
Bulk user import with multiple roles can be achieved by using colon as the multi value separator. Below is the sample entry.

> UserName,Password,Claims
name8@gmail.com,Password1,http://wso2.org/claims/givenname=Test,http://wso2.org/claims/lastname=France,http://wso2.org/claims/role=IID-AGENT:Investor

---

### Optional Fields

**Additional context**
https://github.com/wso2-attic/carbon-identity/blob/master/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/bulkimport/CSVUserBulkImport.java#L171

**Comment by Vaevictus** [comment]
Sorry, but it's a bit silly to have such a bulk import feature yet not be able to assign roles at the same time. How many use cases must exist where you would want to do this yet *Not* assign any roles?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
