### ISSUE TITLE
Ability to configure a custom output event adatpor configuration from the deployment.toml file.

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10904]
Most of the time clients use organization-specific notification sending mechanisms to send emails etc. Since the WSO2 identity server implementation allowed us to implement a custom event adaptor to cater to this requirement. We can configure them from the output-event-adaptor.xml file previously. So It would be great if we can make the custom output event adaptors configurable from the Toml config file as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
