### ISSUE TITLE
Session expires while user is actively working in the console

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#10913]
Describe the Issue:
User's session expired and the user is directed to the login page while working for about 15mins in the app. All unsaved changes are discarded without any warning. Apparently the refresh token fails.

How To Reproduce:

Log in to  console
Keep interacting with the app for about 15mins (exact duration could not be measured)
At one point the session terminates and the user is directed back to the login page
Browser console:
Request URL: 
'https://<console_URL>/oauth2/token Request Method: POST Status Code: 400'

CURL
`curl 'https://<console_URL>/oauth2/token' \ -H 'sec-fetch-mode: cors' \ -H 'origin: https://<console_URL>' \ -H 'accept-language: en-US,en;q=0.9' \ -H 'sec-fetch-dest: empty' \ -H 'cookie: sessionNonceCookie-2f9e6bb0-c494-4d8e-a575-1a199c01f7ac=bc8b86a0-edcc-4256-bffd-6213f68fd21e; sessionNonceCookie-4975a46b-f022-4823-abc5-927e9b4c05aa=4ed331be-c1c7-4c49-a0d6-9db01ad41a80; sessionNonceCookie-dbf0dad3-2f37-48ef-bbc9-4da621b59375=94efd956-97fe-4913-b3fb-1311a3294bbc; sessionNonceCookie-714984ac-6f7c-4ba0-987b-b5a3b8761712=aaa69d83-0cc3-416a-bb64-dc4406bf8319; sessionNonceCookie-f3cb673e-0187-4566-be8b-4d1215822fa8=fa89b6ef-9fed-43d6-915f-e2bdb6fdcc78; sessionNonceCookie-4d246e72-4ebd-4a55-aab9-108344669880=cc9fe522-8b9f-432b-b55c-c347fc1f6d24; JSESSIONID=98578E285F60DAE20A125A18A90049EA; commonAuthId=feda1c4b-6972-462a-9e0d-e0c4dc9c0294; opbs=7f870c01-f47b-484f-b1b8-4b1aecf98d76; AWSALB=7Xg5IJNFzA99oOuidm+RtuPR3rKf5XnL1qM3uoQdqx+/SSe7AKN9xhwRmwDUNPSEVBBbAy7lv6pkxXUWpuZ79yz9F5x10dFDK0p3e0BD3ClozBckEKYDXjPqO9F0; AWSALBCORS=7Xg5IJNFzA99oOuidm+RtuPR3rKf5XnL1qM3uoQdqx+/SSe7AKN9xhwRmwDUNPSEVBBbAy7lv6pkxXUWpuZ79yz9F5x10dFDK0p3e0BD3ClozBckEKYDXjPqO9F0' \ -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' \ -H 'content-type: application/x-www-form-urlencoded' \ -H 'accept: application/json' \ -H 'authority: <console_URL>' \ -H 'sec-fetch-site: same-origin' \ -H 'dnt: 1' \ --data-raw 'client_id=CONSOLE&refresh_token=87e25227-d5e8-3b01-b8b8-0234e8d1f591&grant_type=refresh_token' \ --compressed`

Expected behavior:
User's session should only expire after a given idle time, not while he is active on the app.

Device Information:

Device: dev env
OS: Local PC - Ubuntu 20.04
Browser + Version Chrome 87.0.4280.88

**Comment by ayshsandu** [comment]
This issue will be tracked in the https://github.com/wso2/product-is/issues/10936, as the same issue is reported in https://github.com/wso2/product-is/issues/10936
