### ISSUE TITLE
Support legacy browsers that misinterpret SameSite=None cookie property

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10910]
Due to a bug on iOS12 [1], `SameSite=None` property set from the SameSiteCookieValve is misinterpreted on certain devices.

```
Versions of Safari and embedded browsers on MacOS 10.14 and all browsers on iOS 12. These versions will 
erroneously treat cookies marked with `SameSite=None` as if they were marked `SameSite=Strict`. This bug 
has been fixed on newer versions of iOS and MacOS.
```

**Describe the solution you would prefer**
The SameSiteCookieValve should avoid setting `SameSite=None` for a given set of browsers to avoid breaking authentication flows for these legacy browsers. A possible suggestion is to allow configuring a regex to detect these browsers by their user-agent.

**How to reproduce:**
- Login to a service provider from an iOS 12 device
- Try to SSO to an app on a different hostname from WSO2 IS
- SSO will not work since session cookies are treated as `SameSite=Strict` and not passed to WSO2 IS

[1] https://bugs.webkit.org/show_bug.cgi?id=198181

**Comment by dewniMW** [comment]
the documentation aspect is tracked with https://github.com/wso2/product-is/issues/10968

**Comment by rksk** [comment]
The same site cookie valve is added by default now. Hence, the new property needs to be templated.

[1] https://github.com/wso2/product-is/blob/6c1fb02f9a63e07e3ba1b73121ab53963c305ed7/modules/distribution/src/repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2#L100

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
