### ISSUE TITLE
Per-claim multi attribute separator

### ISSUE THREAD

**Issue by sevmonster** [wso2/product-is#10917]
**Is your feature request related to a problem? Please describe.**
In our environment, we use Active Directory to populate our user store, and there are commas in the `cn` and `displayName` attributes. When attempting to use these values in a SAML claim, they are broken into two claim attributes due to the `multiAttributeSeparator`. I have scoured the docs and checked the source and as far as I can see the separator is only configurable on user store level, not per claim. The result of this is our users' names are split into two attributes in the SAML response, and a vendor we are working with is only using the first value, meaning only half of the user's full name is included. We _do_ want this separation for e.g. roles and other multi-valued strings, so we are not able to disable this feature on the user store level.

**Describe the solution you would prefer**
The ability to disable `multiAttributeSeparator` parsing per-claim without affecting other multi-valued claims.

**Additional context**
https://github.com/wso2/carbon-identity-framework/blob/d17b1f4649587dc4882ccda56d6783d69fcbddb4/components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/pip/DefaultAttributeFinder.java#L173-L191

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by sevmonster** [comment]
Still an issue, but I no longer work with the affected system, so doesn't bother me 🎉
