### ISSUE TITLE
Support JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10916]
The JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens specification[1] defines how a JWT based access token should be formed and the related validations that should be done when using it. The specification has many similarities to the JWT AT produced using the jwt token issuer coming in the WSO2 Identity Server. 

A comparison of the token profile in the spec and the JWT AT currently available in the WSO2 Identity Server can be found here [2].

[1] - https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt
[2] - https://docs.google.com/document/d/1K2pRUq87sz9ZwXdTYf1cLUbxx89Yr7vcc2CP9DJ7hu0/edit?usp=sharing

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
