### ISSUE TITLE
Need to have trace logs to troubleshoot OIDC federation flow

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#10918]
**Is your suggestion related to an experience ? Please describe.**
During OIDC federation flow+JIT provisioning, the locally created user could be missing claim values coming from the federated IdP which we were expecting. In this scenario, it is hard to locate whether the actual response from federated IdP missed them since claim values are obtained via backchannel token calls by JIT provisioning. The only way is to enable debug logs and monitor them.

**Describe the improvement**
There should be trace logs related to this flow. Especially, to have the trace logs in a separate log file.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
