### ISSUE TITLE
Support extendability for UI components in My Account

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10926]
**Is your suggestion related to an experience ? Please describe.**

Currently, the extendability for UI components is supported by the Console app, but it's not supported in the My Account app. 

**Describe the improvement**

The below extensions should be supported in My Account

- [ ] extending menu items
- [ ] extending components (widgets)
- [ ] overriding components
- [ ] show/hide components

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
