### ISSUE TITLE
Endpoint to extend authentication context expiry time

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10927]
As of now, we don't have a way to extend the authentication context without going for workarounds like initiating another authentication flow.

If a user stays idle for a longer time, our current approach is to get the app URL and redirect the user to that URL expecting the app to initiate a new authentication request. But there are difficulties when it comes to non-web applications since their behavior changes from platform to platform.

Eg: 
- Some desktop apps start an HTTP listener on a random available port and create the OAuth callback URL, so they are unable to have a permanent app URL
- Universal Windows Platform UWP) applications show a confirmation dialog before opening the app, so the user has to accept it multiple times if the authn context got expired
- Native mobile apps open system browser for login. If we are to re-initiate an authentication flow, the app has to be opened again and open the browser back where it is moving through multiple screens
- and also new app types are being introduced over time

Due to these reasons, redirecting back to the client app when the authn context is expired seems to be not the ideal solution.

If we have an endpoint to extend the authentication context, we could keep extending the session as long as the user stays on the login page and avoid depending on the client app to re-initiate an authentication flow. Still bookmarked login page scenario can not be solved and we will have to depend on the app URL for that.

A similar endpoint has been developed in https://github.com/wso2/product-is/issues/10560 for extending authenticated sessions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
