### ISSUE TITLE
[Migration] Behavioural Change in SCIM2 Users Endpoint.

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#10920]
**Describe the issue:**
In the IS-5.11.0, SCIM2 users response does not contain duplicate user entries due to sorting done at the SCIM level. This also causes inconsistencies when listing users as outlined in https://github.com/wso2/product-is/issues/10897.

This has been fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/323 and a new configuration has been added to toggle this behaviour. Removing duplicate user entries is enabled by default and to switch to the legacy behaviour, the following configuration should be added to the deployment.toml.

```
[scim2]
remove_duplicate_users_in_users_response = true 
```

**Environment information:**
 - Product Version: IS-5.12.0

**Related PRs:**
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/323
https://github.com/wso2/carbon-identity-framework/pull/3316

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
