### ISSUE TITLE
samlssoTokenId cookie does not clear when browser close

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#10934]
**Describe the issue:**
samlssoTokenId cookie doesn't get cleared when a browser session is closed.

**How to reproduce:**

1. Configure a SAML app in WSO2 IS(appA).
2. Configure session idle timeout as 15min.
3. User A logs in to appA.
4. Check the samlssoTokenId cookie value and copy it.(Let's consider it as samlssoTokenId=xxxy).
5. Close the browser.
6. Open a new browser and login to app A y user B.
7. User B will be prompted with the login page. Enter the login credentials and login to the app.
8. Check the samlssoTokenId cookie value in the browser. The same cookie that you copied in step 4 will be there (samlssoTokenId=xxxy).

**Expected behavior:**
User  B shouldn't get the same samlssoTokenId cookie. The samlssoTokenId cookie should be cleared when the browser session is terminated.

**Comment by piraveena** [comment]
Minoli will be working on this

**Comment by sumedhe** [comment]
Closing as it is fixed.
