### ISSUE TITLE
Update cypress base modules

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#10941]
**Describe the issue:**
Update the cypress base[1] module structure to import from sub module level, commands, page-objects, utils and constants
ex: import level,
import "@wso2/identity-cypress-test-base/ui/commands"

[1] https://github.com/wso2/identity-cypress-test-base

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
