### ISSUE TITLE
Provide hyperlink to clicked to user from listed user.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#10945]
**Is your suggestion related to an experience ? Please describe.**
This suggestion is related to UX.

In roles currently, we can see the list of users
![roleToUsers](https://user-images.githubusercontent.com/25488962/104343056-8050e900-5521-11eb-93fe-47b1aa150a8d.jpg)

Here User list frame is blank, But we can add a hyperlink such that when the admin clinks the user frame He can be redirected to the corresponding user.
![admin](https://user-images.githubusercontent.com/25488962/104342808-3e27a780-5521-11eb-8ba7-f8655edfe3d5.png)

This improvement may be applicable for Groups, Roles, Users.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
