### ISSUE TITLE
All static strings must be referred from the i18n module and should have a ideal way to override product specific strings.

### ISSUE THREAD

**Issue by yasinmiran** [wso2/product-is#10952]
**Describe the issue:**
Currently, the console application contains some static strings which do not have i18n translations and contains product-specific strings, for example, WSO2 Identity Server.

**How to reproduce:**
As an example, you can refer to the specific component in `identity-apps` https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/applications/components/forms/inbound-oidc-form.tsx

**Expected behaviour:**
Throughout the application, all of the static strings should have proper i18n translations for supported languages and should also have a mechanism to incorporate product/brand specific strings.

For overriding product-specific strings:
- Read it from configurations and conditionally render strings.
- Extend i18n and override the specific strings.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
