### ISSUE TITLE
Improve cache clearing logic during token revocation

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#10959]
**Describe the issue:**
Need to address the improvement mentioned in \[1]

\[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1526#discussion_r556424304

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
