### ISSUE TITLE
Improve SAML config mode in new protocol selection tab in Console

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10954]
**Is your suggestion related to an experience ? Please describe.**
An improvement was made to application protocol selection recently(https://github.com/wso2/identity-apps/pull/1493) and with that, the add protocol wizard was removed. This wizard had the option to select the SAML config mode [1].

Note: Also there was an bug in the previous flow when selecting metadata file option. [2][3] 

**Describe the improvement**
Integrate SAML config mode to the existing design.

**Additional context**
[1]
<img width="912" alt="Screen Shot 2021-01-12 at 11 49 31 PM" src="https://user-images.githubusercontent.com/25959096/104413614-9f3c9300-5594-11eb-89a5-2bd50648c09f.png">

[2]
<img width="1205" alt="Screen Shot 2021-01-12 at 11 49 56 PM" src="https://user-images.githubusercontent.com/25959096/104413771-f3477780-5594-11eb-99eb-d82d5b34dbeb.png">

[3]
<img width="669" alt="Screen Shot 2021-01-12 at 11 49 49 PM" src="https://user-images.githubusercontent.com/25959096/104413769-f17db400-5594-11eb-98fc-1f8178671d4f.png">

**Comment by piraveena** [comment]
SAML App integration works fine now in the COnsole. @brionmario is this issue existing now?

**Comment by brionmario** [comment]
> SAML App integration works fine now in the COnsole. @brionmario is this issue existing now? <img alt="Screenshot 2022-03-30 at 12 20 01" width="681" src="https://user-images.githubusercontent.com/17597293/160769216-0d7bb6bb-942c-4c81-8a24-fb457eff2f48.png">

This is now fixed. We can close the issue.
