### ISSUE TITLE
Add new REST endpoint to disable consent purposes

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#10967]
Consent purposes are not flexible. Once a consent purpose has been created and at least one user has provided consent for that purpose, the purpose cannot be deleted.

Consent purposes need to be retirable/disableable through a RESTful call. Existing consents will be retained but the related purpose won't be displayed on the self-care portal. 

- [x] User-portal needs no update. We still want to display Consent Receipts even if a certain purpose had been disabled
- [x] Disabled Purposes should not appear on the self-signup page
- [x] Disabled purposes need to be altered during the disabling process (we are appending a UUID after the name) to allow for the same name of the purpose to be reused (there is a unique constraint on the name field) - This UUID solution needs to be revisited bc it's bad UX; the user-portal is going to display this name+UUID combo. @LahiruLS @rksk 
- [x] The existing getPurposes endpoint needs to be updated to accept a 'disabled' parameter if the user wants to list the INACTIVE purposes only. 
- [x] The admin portal should not display disabled purposes
- [x] Create a new REST endpoint for the disabling feature (it is /consents/purposes/disable/{purposeId} HTTP DELETE, tentatively) @LahiruLS @rksk 
- [ ] Create a new git issue for the migration-client (there has been a schema change in the CM_PURPOSE table)

**Additional context**
carbon-consent-management module

![purpose_state](https://user-images.githubusercontent.com/2381693/108535176-44cfda00-7298-11eb-8899-9d922929d1bc.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
