### ISSUE TITLE
[Doc] Using multiple forced password reset methods

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10965]
As mentioned in the doc [1], we have three options for forced password reset and it is possible to enable more than one at a time since they are checkboxes.
1. Password Reset via Recovery Email
2. Password Reset via OTP
3. Offline Password Reset 

Above 2 and 3 can be used together since both are using the same mechanism for password recovery. But **it is not possible to use the first one with any of the other two** because it will show an error message "Password reset is required. A password reset link has been sent to your registered email address, please check your inbox." when the user tries to login with provided OTP until the user clicks on the link in recovery email and reset the password.

[1] https://docs.wso2.com/display/IS530/Forced+Password+Reset

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
