### ISSUE TITLE
Logo svg is not visible on cookie_policy and privacy_policy pages

### ISSUE THREAD

**Issue by kanchanagodage** [wso2/product-is#10969]
**Describe the issue:**
Logo SVG is not visible on Cookie_Policy and Privacy_Policy pages

<img width="1918" alt="Screen Shot 2021-01-15 at 11 27 34 AM" src="https://user-images.githubusercontent.com/29212717/104687820-eefe9400-5725-11eb-9c1a-b375ef63592e.png">

**Comment by DinikaSen** [comment]
This issue has been resolved with https://github.com/wso2/identity-apps/pull/1515
