### ISSUE TITLE
"All Permissions" is not displayed for sub-tenant admin user

### ISSUE THREAD

**Issue by Madhu-NEC** [wso2/product-is#10975]
**Describe the issue:**
"**All Permissions**" is not displayed under permission list for sub-tenant admin until token is generated for the first time.

**How to reproduce:**
1. Setup components mentioned in [Environment information]
2. Login to management console of IS with primary tenant admin
3. Create a new sub-tenant test.com
4. Login to management console of IS with sub-tenant admin
5. While creating new role, under permission list only "**Admin Permissions**" is listed as per the below screenshot1.png
![screenshot1](https://user-images.githubusercontent.com/47887616/104707738-cdf86c00-5742-11eb-81a9-b2dc4768e53c.PNG)
6. Login to store of WSO2APIM with sub-tenant admin.
7. Generate access token for Production.
8. Again login to management console of IS with sub-tenant admin
9. While creating new role, under permission list "All Permissions" is listed as per the below screenshot2.png
![screenshot2](https://user-images.githubusercontent.com/47887616/104708233-6ee72700-5743-11eb-9a01-c820a86ed5ef.PNG)

**Expected behavior:**
"**All Permissions**" should be displayed (as displayed for primary tenant admin) regardless of the access token generation.

**Environment information:** 
 - WSO2IS as Key Manager 5.7.0, WSO2APIM 2.6.0
 - OS: Linux
 - Database: MySQL 5.7
 - Userstore: LDAP

**Comment by ayshsandu** [comment]
Going forward role permissions will be managed by the `Console` app. In the console, the permission tree is rendered in a unified way for all the tenants.
![image](https://user-images.githubusercontent.com/5061791/104817459-68da6e80-5847-11eb-8eb3-a4a5ab95eb7b.png)

**Comment by Madhu-NEC** [comment]
> Going forward role permissions will be managed by the `Console` app. In the console, the permission tree is rendered in a unified way for all the tenants.

Hi @ayshsandu ,
Thank you for sharing the information. I have understood it.

I have query regarding displaying permission tree with and without token generation:
Case1 : Permission Tree before token generation
Only **Admin Permissions** is displayed.
Case 2 : Permission Tree after token generation
In addition to **Admin Permissions**, **Applications** and their parent **All Permissions** is also displayed. As mentioned in screenshots [here](https://github.com/wso2/product-is/issues/10975#issue-786851398)

As per my understanding, the expected behaviour is **All Permissions** should be displayed regardless of token generation.
Please let me know if my understanding regarding expected behaviour is not correct.
