### ISSUE TITLE
[SCIM2] type sub-attribute of member attribute is not validated when creating a Group with members

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#10972]
**Describe the issue:**
As specified in the [1] "type" sub-attribute of the "members" attribute needs canonical values as User, Group but the existing implementation accepts any value as "type" without validation when sending a post request to Groups endpoint.
![Screenshot from 2021-01-15 14-12-05](https://user-images.githubusercontent.com/38417165/104703395-48be8880-573d-11eb-9cb0-d6bf4461a9bf.png)

**How to reproduce:**
1.Create 2 users with userName 'samindra' and 'lawyers-new9'.
2.Create a group using the below data and send a post request to https://localhost:9443/scim2/Groups API. 

```
{
  "displayName": "lawyers-new16",
  "members": [
    {
      "display": "lawyers-new9",
      "type":"UnsupporteedType"
    },{
        "display":"samindra",
        "value": "17712b98-3957-48cd-bc49-c4559df817b3"
    }
  ]
}
```

**Expected behavior:**
If a unsupported type provided in the request body other than the specified canonical types '400 - Unsupported "type" provided' should be given as the response.

**Environment information:** 
 - Product Version: IS 5.11.0
 - OS: Linux
 
**References:**
[1]https://tools.ietf.org/html/rfc7643#page-26

**Comment by AnuradhaSK** [comment]
Nipun Thilakshan will work on this

**Comment by nipunthilakshan** [comment]
I'll be working on this
