### ISSUE TITLE
[Doc] Document how to enable commonAuthCallerPath Validation

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#10974]
We have introduced a new UI element to SP configurations to register a return to URL or a regEx during IdP logout. The commonAuthCallerPath in the logout request is validated against this registered value. 

Need to update the WSO2 IS 5.1.0 docs and master docs based on the changes.

- https://github.com/wso2/carbon-identity-framework/pull/3267
- https://github.com/wso2-support/carbon-identity/pull/351

**Comment by pamodaaw** [comment]
This feature is available from wso2 is version 6.0..0 onwards and we have backported it for several previous versions as well (5.1.0, 5.3.0, 5.10.0)
The documentations of these versions need to be updated.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
