### ISSUE TITLE
Improve DCR API to support extra validations

### ISSUE THREAD

**Issue by SachiniSiriwardene** [wso2/product-is#10977]
**Is your feature request related to a problem? Please describe.**
In addition to the validations currently done in the DCR endpoint, need to support validations mentioned in the OIDC specification as well as support to do custom validations.
**Describe the solution you would prefer**
The following validations are mentioned in the OIDC DCR specification and should be supported by the DCR endpoint.
- Validate signature of SSA (https://tools.ietf.org/html/rfc7591#section-2.3)
- Validate whether the redirect URI does not have HTTP or localhost
- Check whether all host names of the URIs are same (Logo and Policy URI)
- Check whether the client, policy and tos URIs point to a valid web page

Additional validations not mentioned in OIDC specification:
- Validate whether mandatory params exist depending on the speicification
- Validate whether the TLS certificate is issued by a trusted party
- Check SSA revocation
- Validate token endpoint authentication method
- Validate whether the issuer for the JWT is equal to the software id
- Validate whether the redirect URIs are a subset of that given in the SSA
- Check application type (only web is allowed in CDS open banking specification )
- Check grant Type is allowed (restricted in FAPI)
- Check response types are allowed (restricted in FAPI)
- Check whether valid signing algorithm (restricted in FAPI)

These validations should be done in both POST and PUT requests.

In addition to the above-mentioned requirements, when providing the response for the POST, PUT and GET API calls, all the client registration data sent in the request should be sent back.
These responses formats differ in the Open Banking UK spec and the CDS spec for Australia. In the CDS spec, attributes sent in the SSA are also returned back in the response in addition to the original attributes sent in the request.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
