### ISSUE TITLE
[SCIM2] Specification violations in implementation according to RFC 7643

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#10984]
**Describe the issue:**
1. ResourceTypes  id considered as optional [1] but it considered as required in Charon core.
2. Schemas roles attribute needs required definition true as in [2] and it's missing in core definition.

**How to reproduce:**
1. Send a POST request to https://localhost:9443/scim2/ResourceTypes
2. Send a POST request to https://localhost:9443/scim2/Schemas and inspect roles attribute and it's definitions.

**Expected behavior:**
Behavior should be comply with RFC7643

**Environment information** 
 - Product Version: IS 5.11.0
 - OS: Linux

**References:**
[1]https://tools.ietf.org/html/rfc7643#page-29
[2]https://tools.ietf.org/html/rfc7643#page-66

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
