### ISSUE TITLE
Inconsistent behaviour in opaque tokens and JWT tokens issued by SaaS service providers after enabling "enable_jwt_token_validation_during_introspection"

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#10988]
**Describe the issue:**
Inconsistent behaviour in opaque tokens and JWT tokens issued by SaaS service providers after enabling "enable_jwt_token_validation_during_introspection". 

```
[oauth]
enable_jwt_token_validation_during_introspection = true
```

After enabling the above configuration, the opaque tokens and JWT tokens issued by SaaS service providers behave differently. The JWT token issued cannot be used to call the user's tenant API, whereas the opaque tokens can be used for the same.

**How to reproduce:**
- Register a SaaS service provider in the "carbon.super" tenant, and add another tenant "tenant1.com" where "testuser" exists. 
- For SaaS service providers it is recommended to use sp tenant key for signing access tokens so enable the following configuration.
```
[oauth.access_token]
generate_with_sp_tenant_domain = true
```
- Obtain an opaque token and JWT token from the SaaS service provider that is registered in the "carbon.super" tenant, using the "testuser" user in tenant "tenant1.com". 
- With the tokens obtained, call the user's tenant consent management API to retrieve consent receipt(/t/tenant1.com/api/identity/consent-mgt/v1.0/consents/receipts/5e96f66f-276b-4c90-b0f3-5473d0267e8c). Both opaque token and JWT token can be used.
```
curl -k -X GET "https://localhost:9443/t/tenant1.com/api/identity/consent-mgt/v1.0/consents/receipts/7effbe54-51c2-4210-a282-ea4e50488dcd" -H "Authorization: Bearer cc6b2736-42d1-48e2-8a5d-6177d6b77d48" -H "accept: application/json"

curl -k -X GET "https://localhost:9443/t/tenant1.com/api/identity/consent-mgt/v1.0/consents/receipts/7effbe54-51c2-4210-a282-ea4e50488dcd" -H "Authorization: Bearer eyJ4NXQiOiJNell4T......." -H "accept: application/json"
```
- Now, add the EnableJWTTokenValidationDuringIntrospection cofiguration
```
[oauth]
enable_jwt_token_validation_during_introspection = true
```
The opaque token can still be used to call the above API however the JWT token cannot be used(signature validation would fail).

**Expected behavior:**
The behaviour should be consistent for both the opaque tokens and JWT tokens.

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
