### ISSUE TITLE
Simplify the "Allow CORS" action in application create wizard

### ISSUE THREAD

**Issue by yasinmiran** [wso2/product-is#10983]
## Is your suggestion related to an experience? Please describe.
Currently when we are adding values to `Allowed Redirect URLs` field, if the corresponding URL is **not** marked as `CORS Allowed` then we present the option to enable it via a pop-up like illustrated below.

![Screenshot from 2021-01-18 12-35-07](https://user-images.githubusercontent.com/25561152/104882855-c7a80100-5989-11eb-9a5d-2fe23b0b636d.png)

## Describe the improvement
The suggested change is provided by @brionmario and @jeradrutnam is to change the rendering logic of the above approach and make it similar to below.

> V1
![Group 1](https://user-images.githubusercontent.com/25561152/104883602-07231d00-598b-11eb-8108-9ed45bfc2b0d.png)

> Design Update V2
<img width="447" alt="Screenshot 2021-01-20 at 13 40 26" src="https://user-images.githubusercontent.com/25561152/105146233-c27fb900-5b25-11eb-986c-de4b76664342.png">

## Additional context
1. It should have the red strikethrough text (for non-TLS protocols) (only `protocol`) instead of the circle clickable label.
2. It should allow the user to directly allow a particular URL by simply clicking on `Allow CORS` text button.

**Comment by DimalChandrasiri** [comment]
The information shown in the application creation wizard should be updated with the suggested comment. 

- Text prominence should be fixed.
- Change the button to only `allow` text without making the entire text a button.
