### ISSUE TITLE
Support tenant wise configurations for Local and Multi-factor authenticators

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10986]
**Is your feature request related to a problem? Please describe.**
Current for local authenticators such as TOTP and for authenticator we are defining certain configuration at the server level using the application-authentication.xml

For example, in TOTP we have,
```
[authentication.authenticator.totp.parameters]
authenticationMandatory=true
enrolUserInAuthenticationFlow=true
TOTPAuthenticationEndpointURL="totpauthenticationendpoint/totp.jsp"
TOTPAuthenticationEndpointErrorPage="totpauthenticationendpoint/totpError.jsp"
TOTPAuthenticationEndpointEnableTOTPPage="totpauthenticationendpoint/enableTOTP.jsp"
Issuer="WSO2"
UseCommonIssuer=true
```

Some of these params such as enrolUserInAuthenticationFlow need to decided tenant-wise. Currently, we do not have a way to do so generally. Noticed that in several connectors (TOTP, Email OTP) we have a mechanism to add key-value pairs to the registry to define these tenant-wise. But since we are moving away from the registry this might not be ideal.

**Describe the solution you would prefer**
- One possible solution would be to make use of the [IdentityConnectorConfig](https://github.com/wso2/carbon-identity-framework/blob/834cd821af5a609ea2e846769077a26364629069/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/ConnectorConfig.java#L25) interface and approach we have taken to store and retrieve governance connector configurations. This will enable us to define configurations of tenants for these authenticators and retrieve them.

Additional Considerations
- Need to evaluate whether we need to allow uses to define/override these configurations at the SP level too?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
