### ISSUE TITLE
Refactor TOTP dependent js files

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10997]
**Is your feature request related to a problem? Please describe.**
With https://github.com/wso2/identity-apps/pull/1518/files we moved the TOTP pages to the authentication portal. While doing this we noted that there are certain js files that need to be refactored to remove unnecessary code.

For example gadget.js file (authentication-portal/src/main/webapp/js/gadget.js)

This issue is to track the refactoring effort.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
