### ISSUE TITLE
Enroll mobile device for TOTP without a computer

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10993]
**Is your suggestion related to an experience ? Please describe.**
When you are on a mobile device and trying to enroll the same device for TOTP, you will have to find a mirror to scan the screen of the same device :)

To address this complexity, most of the providers are providing a code to configure the TOTP app manually by entering that code. We can add this improvement into both totp endpoint and myaccount. 

![Screenshot from 2021-01-19 02-47-27](https://user-images.githubusercontent.com/719073/104963738-33798080-5a01-11eb-8cd7-b5647c637cc6.png)

**Comment by rksk** [comment]
The same is reported in https://github.com/wso2/product-is/issues/9519

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
