### ISSUE TITLE
Check the possibility to deprecate getClientIpAddress util method 

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#10991]
**Is your suggestion related to an experience ? Please describe.**
Related to https://github.com/wso2/product-is/issues/10805

**Describe the improvement**
With the improvement in https://github.com/wso2/product-is/pull/10990, `org.apache.catalina.valves.RemoteIpValve` is added to the catalina-server.xml file such that the real client IP addresses can be added to request headers instead of IP addresses presented by a proxy or a load balancer. The implementation in [1], was also introduced in earlier versions of IS to achieve the same. 

It is required to check whether `org.apache.catalina.valves.RemoteIpValve` could replace the implementation in [1] and if so, it is required to deprecate [1] and make `org.apache.catalina.valves.RemoteIpValve` a default configuration in IS tomcat valves. 

[1] https://github.com/wso2/carbon-identity-framework/blob/f003eee8d40d5c0dfe9ab9dbac0f0c78889b7dec/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java#L1056

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
