### ISSUE TITLE
Move DefaultProvisioningHandler out from the identity-framework

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11004]
**Is your suggestion related to an experience ? Please describe.**

- The proper fix for the issue https://github.com/wso2/product-is/issues/10961 is, prompt an error if the user entered password is not matching with the password policy and give a chance to re-enter the password.

- For that, an error validation should be added similar to https://github.com/wso2-extensions/identity-governance/blob/c579fea49208010e85ddc81f9d5b205d2412cd61/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/password/NotificationPasswordRecoveryManager.java#L584-L589.

- It needs to add a governance dependency to the framework, which causes a cyclic dependency,

- thus, DefaultProvisioningHandler should be moved out from the carbon-identity framework.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
