### ISSUE TITLE
Unable to see the popup error message comes behind the Overlay

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#11009]
**Is your suggestion related to an experience ? Please describe.**
When a user wants to delete a local attribute that maps to an external claim, the user can't see the error unless he closes the overlay.
![beforeOverlay](https://user-images.githubusercontent.com/25488962/105128172-8427d100-5b08-11eb-9d91-79593af71047.png)

How To Reproduce:

- Navigate to local attributes listing.
- Delete an attribute that has associations.

**Sub Issues**
- [ ] https://github.com/wso2/product-is/issues/11087

**Comment by nilasini** [comment]
Couldn't reproduce the issue with wso2is-5.12.0-alpha17
![Uploading Screenshot 2022-03-30 at 14.41.56.png…]()
