### ISSUE TITLE
Improve tenant preference api integration to UI

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#11007]
**Is your suggestion related to an experience ? Please describe.**
we can improve tenant preference API integration in the following aspects

1. Reduce network calls in the Authentication & Recovery portal
2. Reduce  network calls in the Myaccount
3. Introduce caching in server-side 

**Describe the improvement**
Following are possible ways to achieve them

- To reduce network calls in the Authentication & Recovery portal:  Get all the connector(self-sign-up, recovery) configs in a single call.
- To reduce network calls in the Myaccount:  Introduce redux store to save the preference api call.
- To Introduce caching in server-side:  introduce caching in preference API [1] side

[1]https://is.docs.wso2.com/en/5.12.0/develop/identity-governance-rest-api/#/

**Additional context**
Related issues https://github.com/wso2/product-is/issues/10915, https://github.com/wso2/product-is/issues/10935, https://github.com/wso2/product-is/issues/9717

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
