### ISSUE TITLE
Identified Improvements for TOTP authenticator

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11006]
- Change the artifact ID to remove "connector" in the name as it is shipped with the product in plugins now
- Change the feature ID to remove "connector" in the feature id 
- https://github.com/wso2/product-is/issues/10997
- Improve UX of totp input page (https://github.com/wso2/product-is/issues/11045)
- Enroll mobile device for TOTP without a computer (https://github.com/wso2/product-is/issues/10993)
- TOTP issue for SaaS applications https://github.com/wso2/product-is/issues/11172

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
