### ISSUE TITLE
Explain defaultAutoCommit=true property more clearly in docs

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#11002]
**Describe the improvement**

Need to make it clear that `defaultAutoCommit=true` is the default and recommended config and `commitOnReturn="true"` is recommended for most of the cases where `defaultAutoCommit="false"`. This can be explained more clearly using example use cases as well. 

[1] https://is.docs.wso2.com/en/5.10.0/setup/changing-to-mssql/

Refer to the descriptions below for further clarification: 
defaultAutoCommit - if this is set to true the, the tomcat will make sure that each and every sql statement will be committed soon as it is executed. However in the code level we also tries to execute set os SQL as a transaction and tries to commit them at the end of the block, In such cases since the default auto commit is set to true, and if we try to commit the same from the code block as well, there is a high possibility that you will get the exception as below since the such queries would be already committed. Hence the recommendation is to set it to false.

org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled

commitOnReturn - This parameter will make sure that when the particular connection return back to the pool, it will be added to the pool followed by a commit, this is required since we do not commit all the queries thats executed from our code base such as SELECT queries..
In general the SELECT do not need to be committed, However with specific to the postgreSQL what we have seen is that every SELECT has to be committed before it returns to the pool, otherwise postgreSQL will holding Access Share level lock to the connection. Hence the recommendation is to set it to true. 

rollbackOnReturn - This parameter will make sure that when the particular connection return back to the pool , it will be added to the pool followed by a rollback, This is not required. However if this is set to true the parameter commitOnReturn will be not effective. Hence the recommendation is to set it to false.

**Comment by nilminiwso2** [comment]
Closing this issue. We will handle this with [1].
[1] https://github.com/wso2/product-is/issues/14521
