### ISSUE TITLE
Read Idle Session Timeout from Server Configurations API in MyAccount & Console

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#11000]
**Is your suggestion related to an experience ? Please describe.**
Currently, we are reading the values from deployment.toml.json to set the idleSessionTimeout in MyAccount & Console portals. However, the admin has the capability the change the Idle Session Timeout value for the backend server in runtime via console which will lead to backend & portals have different idleSessionTimeout periods. Thus we need to reflect the changed idleSessionTimeout in the portals.

**Describe the improvement**
Use *Server Configurations API* [1] to retrieve idle session timeout from the server.

[1]https://is.docs.wso2.com/en/latest/develop/configs-rest-api/#/Server%20Configs/getConfigs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
