### ISSUE TITLE
Add default uneditable placeholders for inline PEM prefix and postfix

### ISSUE THREAD

**Issue by yasinmiran** [wso2/product-is#11010]
**Is your suggestion related to an experience? Please describe.**
Currently, in the `protocol > certificate > inline PEM` form section field does not provide default placeholders for prefix `-----BEGIN CERTIFICATE-----` and postfix `-----END CERTIFICATE-----` format. Instead, it only provides an editable text which is injected as the default value to the `textarea` field.

![qq](https://user-images.githubusercontent.com/25561152/105131018-21d1cf00-5b0e-11eb-8f75-80713b72f6de.png)

**Describe the improvement**
Make the PEM `prefix` and `postfix` uneditable and expect only the `Certificate Key` from the user.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
