### ISSUE TITLE
ACS URL is not being highighted as a required field.

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#11019]
**Describe the issue:**

In the application protocol configuration page, if the required fields are empty when updating, the expected behavior is that it prompts the user with a highlighted text saying `This is a required field.`
Currently, this is not happening with the `Assertion consumer URLs` field, despite it being a required field.

![required_filed](https://user-images.githubusercontent.com/25428696/105147471-3ec6cc00-5b27-11eb-8339-5df216b5789a.png)

**How to reproduce:**

1. Login to the `Console` app.
2. Go to `+ new application`.
3. Select `Custom Application`.
4. Give a name and register.
5. In the application's protocol section, select on `SAML`.
6. Without filling any fields, click on `update` at the bottom of the page.

**Expected behavior:**
All the required fields should be highlighted with a prompt to enter values.

**Environment information:**
 - Product Version: IS-5.11.0-M6

**Comment by nilasini** [comment]
Couldn't reproduce with wso2is-5.12.0-alpha16 pack.
