### ISSUE TITLE
 [Migration] UI change in the signature validation certificate alias option.

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#11014]
**Describe the issue:**
In the IS-5.11.0 console, under the SAML application configurations, there are two ways which the user can provide the application certificate. With allowing the user to upload the certificate through the UI, selecting the certificate alias by adding it separately to the key store has become redundant.

Hence, by default, we are disabling the signature validation certificate alias option in the console UI. The users can switch to the legacy behavior (enable the option in the console UI) by adding the following configuration to the deployment.toml file.

```
[console.applications.ui]
certificate_alias_enabled = true
```

Related to https://github.com/wso2/product-is/issues/11003.

**Related PRs:**
https://github.com/wso2/identity-apps/pull/1526
https://github.com/wso2/identity-apps/pull/1533
https://github.com/wso2/carbon-identity-framework/pull/3332

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
