### ISSUE TITLE
TokenExpiryTime for SMS OTP

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11020]
**Is your suggestion related to a missing or misleading document? Please describe.**
`TokenExpiryTime` config property is not described in the doc [1]. It can be defined in the same way other properties defined. The unit is `seconds`.

Additionally, the following block has a typo. It has to be `authentication.authenticator.sms_otp.parameters`. `s` is missing.
```
[authentication.authenticator.sms_otp.parameter] 
<Property-name> = <Property-value> 
```

[1] https://is.docs.wso2.com/en/5.10.0/learn/configuring-sms-otp/#sms-otp-configuration-properties

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
