### ISSUE TITLE
Scripts to schedule clean up tasks for MSSQL database

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#11021]
**Is your feature request related to a problem? Please describe.**

Database scripts to schedule the execution of the following two stored procedures for MSSQL database need to be formed.

- [ ] Session data clean up task
- [ ] Token clean up task

**Comment by Pushpalanka** [comment]
@DinikaSen 
Can you please add the current status of this issue?

**Comment by DinikaSen** [comment]
This requirement was for Asgardeo to execute the clean up scripts using scheduler tasks. Due to an inherent limitation in the underlying database type, it is not possible to use scheduled tasks for the purpose. The clean up scripts are now executed using cron jobs and hence these scripts are not required anymore. Therefore, this issue can be closed.
