### ISSUE TITLE
CORS warning shown even after adding the URL as a trusted origin

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11038]
**Describe the issue:**

In the current console app, when creating a SPA app using the template we have given the option of omitting the redirect URI

![image](https://user-images.githubusercontent.com/5237653/105320162-da217500-5beb-11eb-9f70-ca9bfc3cbbe6.png)
----

As a result, after the app is added, we are adding a callback "http://localhost:3000"
Although this app is added as an allowed origin too, we are seeing a warning as shown below

![image](https://user-images.githubusercontent.com/5237653/105320067-bceca680-5beb-11eb-89c2-8d412fcebb72.png)

-----
![image](https://user-images.githubusercontent.com/5237653/105320882-be6a9e80-5bec-11eb-920e-c9e331b6e379.png)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
Couldn't reproduce the issue with wso2is-5.12.0-alpha16. Currently the value for redirect URI is mandatory.
