### ISSUE TITLE
Default dialects URI shouldn't be able to change.

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#11032]
**Describe the issue:**
The dialect URI should be not editable for the user since it will result in unintended consequences.

![Screenshot 2021-01-21 at 10 52 48](https://user-images.githubusercontent.com/11191791/105283714-08e12080-5bd7-11eb-8549-867b6cd4f1f7.png)

**Comment by nipunthilakshan** [comment]
I will work on this
