### ISSUE TITLE
Document allow_sending_verification_code_by_email property of TOTP

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11035]
**Is your suggestion related to a missing or misleading document? Please describe.**
Document configuration introduced in https://github.com/wso2/product-is/issues/11017

`

**Comment by divyaamunugama** [comment]
Fixed by: https://github.com/wso2/docs-is/pull/3184

![image](https://user-images.githubusercontent.com/84217321/184593040-fb6cd5ed-e88a-4b85-ae40-4cdd361e2869.png)
