### ISSUE TITLE
[SCIM2] Incorrect location attribute in response when patching groups using bulk post

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#11034]
**Describe the issue:**
When trying to add a member to a group using bulk post with PATCH method, in the given response body location attribute shows a wrong URI(https://localhost:9443/scim2/Users/9f0a52b9-d306-49ad-8d4b-99ccfed9ebcf) . Highlighted in the attached image.

Instead of `Users`, the URL path should include `Groups`.
![Screenshot from 2021-01-20 16-26-26](https://user-images.githubusercontent.com/38417165/105292529-e5ba6f00-5bde-11eb-9bee-5f20c18a7d40.png)

**How to reproduce:**
1. Create a group and extract id.
2. Create a user and extract id.
3. Send a post request using below code snippet to https://localhost:9443/scim2/Bulk.

```
{ 
    "schemas": [ "urn:ietf:params:scim:api:messages:2.0:BulkRequest" ], 
    "Operations": [
{
           "method": "PATCH",
           "path": "/Groups/9f0a52b9-d306-49ad-8d4b-99ccfed9ebcf",
           "data": {
               "Operations": [
                   {
                       "op": "add",
                       "value": {"members":[{
                           "display":"anjana",
                           "value":"e9b8278a-0607-4432-ac3d-978b8b12bde6"
                       }]}
                   }
               ]
           }
       }
    ] 
}
```

**Expected behavior:**
Location attribute in response body should provide https://localhost:9443/scim2/Groups/9f0a52b9-d306-49ad-8d4b-99ccfed9ebcf.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Linux

**Comment by ashans** [comment]
I will work on this
