### ISSUE TITLE
Improve OAuth SPA application create flow

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11039]
**Is your suggestion related to an experience ? Please describe.**

Currently, in the console app, we have the below UX when creating a SPA using the template.
![image](https://user-images.githubusercontent.com/5237653/105321177-24efbc80-5bed-11eb-89d7-1a9ab573477c.png)

There are few improvements we can do,

- Keep the redirect URI mandatory
- Display the notice saying that if you are trying out quickly, that we will be adding some default value "X" as the callback URL or we can get rid of adding the default callback URL completely.

**Comment by mefarazath** [comment]
@NipuniBhagya

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
