### ISSUE TITLE
Do a major version bump for identity-apps repo

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11031]
**Is your feature request related to a problem? Please describe.**

For IS 5.12.0 we have plans to move the OOTB authenticator app pages to the authentication portal. With this change we will be removing source of individual web apps. 

Since this is a major change we need a major version bump before the release (alpha, beta)

**Comment by piraveena** [comment]
The master has bumped to 1.3.x version now

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
