### ISSUE TITLE
Improve TOTP login/input page UX

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11045]
Our current TOTP login page looks like below,
![image](https://user-images.githubusercontent.com/5237653/105332525-bb76aa80-5bfa-11eb-83b4-b6b7c33ab76e.png)

TOTP is a 6 digit number code, so instead of a text box we can show a number box

A sample,
![image](https://user-images.githubusercontent.com/5237653/105341818-90de1f00-5c05-11eb-8c0f-40060b44286b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
