### ISSUE TITLE
Update the TOTP related docs with the latest changes.

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#11042]
**Is your feature request related to a problem? Please describe.**
The TOTP flow was changed in My Account and in the authentication portal. These changes can be found in the following PRs:
1. https://github.com/wso2/identity-apps/pull/1546
2. https://github.com/wso2/identity-apps/pull/1534
3. https://github.com/wso2/carbon-identity-framework/pull/3334
4. https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/84

The relevant documents should be updated to accommodate the changes introduced through the above PRs.

Related issue: https://github.com/wso2/product-is/issues/11017

**Comment by divyaamunugama** [comment]
Updates done
1. Screenshots updated according to https://github.com/wso2/identity-apps/pull/1546
2. Added Additional configurations according to https://github.com/wso2/carbon-identity-framework/pull/3334

Related PRs: 
- https://github.com/wso2/docs-is/pull/3184
- https://github.com/wso2/docs-is/pull/3164

Moving the issue to Milestone 6.1.0-checkpoint to complete the other tasks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
