### ISSUE TITLE
Application creation doesn't fall-back if there is a failure in the CORS configurations in the API request

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#11048]
**Describe the issue:**
When an application is created via REST API with incorrect input for the CORS config, an error 

**How to reproduce:**
API request:
```
{"name":"testTrad","advancedConfigurations":{"discoverableByEndUsers":false},"authenticationSequence":{"type":"DEFAULT","steps":[{"id":1,"options":[{"idp":"LOCAL","authenticator":"basic"}]}]},"inboundProtocolConfiguration":{"oidc":{"grantTypes":["authorization_code"],"publicClient":false,"callbackURLs":["https://mydomain.com"],"allowedOrigins":["https:://mydomain.com"]}},"templateId":"b9c5e11e-fc78-484b-9bec-015d247561b8"}
```
**Refer `::` in allowedOrigins":["https:://mydomain.com"]}}**

API returns 400, but the application is created.

**Expected behavior:**
The application should not be created.

**Comment by mefarazath** [comment]
Analysis:

- CORS origins of an application are added in a separate transaction outside of the application creation.
- When the CORS origin addition fails, we are not currently rolling back the created application or its metadata.
- This leads to an error when we correct the payload and retry, as the application data (application name) still remains from the previous failure.

Short term solution
- Implement the rollback at the REST API layer

Idea/Long term Solution
- Do the CORS addition in the same transaction as the application creation so the rollback will automatically be handled.

**Comment by sumedhe** [comment]
The short-term solution is done.
The long-term solution is tracked by wso2/product-is#11131

**Comment by sumedhe** [comment]
We can close this with the above comment.
