### ISSUE TITLE
No Audit logs printed for application delete action

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11049]
**Describe the issue:**
When we create an application we get an audit log,
```
TID: [1] [2021-01-22 01:01:21,355] [3a8df668-e80d-4f11-9e4a-aaf7b479e783]  INFO {AUDIT_LOG} - Initiator : admin@authello.com | Action : create | Target : 58 | Data : { New App } | Result : Success
```

When we update an application we have an audit log,
```
TID: [1] [2021-01-22 00:59:58,676] [46398c13-1f6c-41f0-b0cb-b33271fa26b1]  INFO {AUDIT_LOG} - Initiator : admin@authello.com | Action : update | Target : 17 | Data : { testSPA } | Result : Success
```

But for an application delete, we do not have any audit logs.

**How to reproduce:**

- Delete an application and observe the audit logs

**Expected behavior:**
There should be an audit log for application delete.

**Analysis**
We do have an [audit logger listener](https://github.com/wso2/carbon-identity-framework/blob/e2f00757c86bde83424c41ed84166ee170c481a3/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationMgtAuditLogger.java#L80) for application delete.

But the method that is called from the service layer has been overriden at the abstract layer to simply return true. This particular method is not implemented in the audit logger listener

Method of the listener interface called by service layer: https://github.com/wso2/carbon-identity-framework/blob/e2f00757c86bde83424c41ed84166ee170c481a3/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationMgtListener.java#L139-L143

Same method overriden at Abstract Layer: https://github.com/wso2/carbon-identity-framework/blob/1c9ae2149d64b333abef12fc1123c55d60934b61/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/AbstractApplicationMgtListener.java#L420-L424

The method called by the service has been introduced recently. However, to avoid breaking existing listeners we are calling the old listener method from the newly introduced [method](https://github.com/wso2/carbon-identity-framework/blob/e2f00757c86bde83424c41ed84166ee170c481a3/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationMgtListener.java#L139-L143).

Since the Abstract layer overrides the behaviour of the interface we see this issues.

Possible fix: 
- Remove unnecessary override at the abstract layer ()

or

- Move the implementation in interface to the abstract layer.

**Comment by ashans** [comment]
I am working on this issue
