### ISSUE TITLE
Callback URL drops full path

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#11046]
**Describe the issue:**
When creating an application, while adding the callback URL, the full path is not taken and only takes the hostname only as the callback URL.[1]

After adding the callback URL, when viewing the protocol tab, the allowed Origin is taken as `localhost`[2]

[1] 
![Screenshot 2021-01-21 at 20 44 08](https://user-images.githubusercontent.com/11191791/105370777-f04e2600-5c29-11eb-9129-7e974963966c.png)

[2]
![Screenshot 2021-01-21 at 20 44 23](https://user-images.githubusercontent.com/11191791/105370799-f6dc9d80-5c29-11eb-98da-d62440e0b0ea.png)

**How to reproduce:**
1. Add an application with the following URL - `https://www.mywebsite.com/login`
2. Create the application
3. Go to protocol tab once application is created.

**Expected behavior:**
Should take the user entered URL without any manipulation .

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
