### ISSUE TITLE
CSRF logging is not templated

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11053]
**Describe the issue:**
It's required to enable the CSRF logging as follows in repository/conf/security/Owasp.CsrfGuard.Carbon.properties file to identify the issues related to CSRF.
```
org.owasp.csrfguard.Logger=org.owasp.csrfguard.log.ConsoleLogger
# org.owasp.csrfguard.Logger=org.owasp.csrfguard.log.JavaLogger
```
However, it's not templated in IS versions above 5.9 and hence the logging cannot be enabled to print in the console logger.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
