### ISSUE TITLE
Improve application management audit logs

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11054]
**Is your suggestion related to an experience ? Please describe.**

Currently our application management audit logs, do not contain sufficient information.
```
TID: [1] [2021-01-22 01:01:21,355] [3a8df668-e80d-4f11-9e4a-aaf7b479e783]  INFO {AUDIT_LOG} - Initiator : admin@authello.com | Action : create | Target : 58 | Data : { New App } | Result : Success
```
```
TID: [1] [2021-01-22 00:59:58,676] [46398c13-1f6c-41f0-b0cb-b33271fa26b1]  INFO {AUDIT_LOG} - Initiator : admin@authello.com | Action : update | Target : 17 | Data : { testSPA } | Result : Success
```

For example, we are missing the application resource id (the unique identifier of application) and still using the application ID which is an internal DB detail. 

**Describe the improvement**
Improve the audit logs to include application resource id and other useful attributes

**Comment by mefarazath** [comment]
Current application management audit logger implementation happens at https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationMgtAuditLogger.java

**Comment by DinikaSen** [comment]
Ashan Sarukkali will work on this

**Comment by malithie** [comment]
Is this done. Can we prioritize this issue.
In addition, can we also look at fixing https://github.com/wso2/product-is/issues/9557

We can work on based on a prioritized user story model

@IsuraD

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
