### ISSUE TITLE
The last internal scope is dropped when generating an access token with internal scopes

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11069]
**Describe the issue:**
The last internal scope is dropped when generating an access token with internal scopes.

**How to reproduce:**
-  Get the latest updated IS-5.10.0 pack, register a service provider.
- Obtain an access token using the password grant with the scopes `openid internal_user_mgt_create`
```
curl -u e7tO931p6hlcrx0SI76FEVKXASsa:vzu1E29zDqPIwQFEH49y9nD03hYa -k -d "grant_type=password&username=admin&password=admin&scope=openid internal_user_mgt_create" -H "Content-Type:application/x-www-form-urlencoded" "https://localhost:9443/oauth2/token"
```
An access token with scope `openid` would be generated(internal_user_mgt_create dropped)
- Obtain an access token using the password grant with the scopes `openid internal_user_mgt_create internal_user_mgt_list`
```
curl -u e7tO931p6hlcrx0SI76FEVKXASsa:vzu1E29zDqPIwQFEH49y9nD03hYa -k -d "grant_type=password&username=admin&password=admin&scope=openid internal_user_mgt_create internal_user_mgt_list" -H "Content-Type:application/x-www-form-urlencoded" "https://localhost:9443/oauth2/token"
```
An access token with scope `openid internal_user_mgt_create` would be generated(internal_user_mgt_list dropped)

**Expected behavior:**
scopes should not be dropped.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
