### ISSUE TITLE
Implement support for AuthenticationFlowStatus.SUCCESS_COMPLETED without any redirection

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#11065]
### Description
Currently, if we return AuthenticationFlowStatus.SUCCESS_COMPLETED  from an authenticator, the framework expects a redirection to happen in the authentication flow.
We need to refactor the flow to complete the authentication without expecting a redirection in the middle.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
