### ISSUE TITLE
Write Unit and Cypress Tests for JavaScript Auth SDKs

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#11060]
**Describe the issue:**
Unit and integration tests should be written for the following JavaScript SDKs.
1. Auth JS SDK
2. Auth SPA SDK
3. Auth React SDK

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
