### ISSUE TITLE
Changing the branding docs incomplete

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#11077]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the document [1], step 1 - method 2 instructions are incorrect

Given instructions in step 3 Build user-portal artifacts as below.

```
java
       npx lerna run build — scope @wso2is/user-portal
```

**Describe the improvement**
Instructions should be changed as below

```
npx lerna run build --scope @wso2is/user-portal
```

[1] - https://is.docs.wso2.com/en/5.10.0/develop/customizing-user-portal-ui/#step-2-changing-the-branding

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
