### ISSUE TITLE
Application Management error codes needs to be documented

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11074]
**Is your suggestion related to a missing or misleading document? Please describe.**
Need to do $subject in https://is.docs.wso2.com/en/5.12.0/references/error-catalog/#error-catalog

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
