### ISSUE TITLE
Admin force password reset documentation has some missing parts - Hence not working

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#11086]
**Is your suggestion related to a missing or misleading document? Please describe.**
When you follow the document https://is.docs.wso2.com/en/5.10.0/learn/forced-password-reset/#invoke-admin-force-password-reset -via SCIM2 API. - The feature does not work. There are some missing parts to be added as described below.

**Describe the improvement**
Below steps should be included in the part: https://is.docs.wso2.com/en/5.10.0/learn/forced-password-reset/#invoke-admin-force-password-reset (SCIM2 part)

Please follow the below steps if you haven't done it earlier.
1. Open the scim2-schema-extension.config file located in the <IS_HOME>/repository/conf/ folder.
2. Define the extension by adding attributes in the following format before the last element of the JSON array in the scim2-schema-extension.config file.

```
{
"attributeURI":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:adminForcedPasswordReset",
"attributeName":"adminForcedPasswordReset",
"dataType":"boolean",
"multiValued":"false",
"description":"Enable password change required notification in the user creation.",
"required":"false",
"caseExact":"false",
"mutability":"readwrite",
"returned":"default",
"uniqueness":"none",
"subAttributes":"null",
"canonicalValues":[],
"referenceTypes":[]
},
```

3. Add the attribute names of the attributes that you added to the scim2-schema-extension.config file as subAttributes of the wso2Extension attribute as seen in the code block below.

```
{
"attributeURI":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
"attributeName":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
"dataType":"complex",
"multiValued":"false",
"description":"Enterprise User",
"required":"false",
"caseExact":"false",
"mutability":"readWrite",
"returned":"default",
"uniqueness":"none",
"subAttributes":"verifyEmail askPassword employeeNumber costCenter organization division department manager adminForcedPasswordReset",
"canonicalValues":[],
"referenceTypes":["external"]
}
```

4. Restart the server
5. Add a new external claim under urn:ietf:params:scim:schemas:extension:enterprise:2.0:User dialect. Please note that the name you are giving in the External Claim URI should be equal to the one you have configured in step 2 attributeURI

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
