### ISSUE TITLE
Link hover state not implemented

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#11082]
**Describe the issue:**
The links not show hover states on hover on the getting started page.

**How to reproduce:**
1. Navigate to getting started page
2. hover over any link

**Expected behavior:**
Should indicate hover state for links

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
