### ISSUE TITLE
Callback URL dropping the ending slash at application creation

### ISSUE THREAD

**Issue by mihirukongahage** [wso2/product-is#11095]
**Describe the issue:**
Allowed Redirect URLs textbox in the IS Console removes the ending slash ( / ) after clicking the + button. 
Then it is not saved in the database as well.

![image](https://user-images.githubusercontent.com/34188669/105865788-456aad00-6019-11eb-8aad-c8e904ae0460.png)

**Expected behavior:**
Entered slash ( / ) should be there 
Eg : http://localhost:8080/pickup-manager/callback**/**

**Comment by Pushpalanka** [comment]
This validation is responsible for the above behavior, https://github.com/wso2/identity-apps/blob/master/modules/react-components/src/components/input/url-input.tsx#L178-L183, need to confirm if we can remove this validation.
