### ISSUE TITLE
Sample requests with extended SCIM shema

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11090]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the document [1], it provides a sample for PATCH operation only.

But most of the time users get confused with how to use those new attributes for filtering users and as requested attributes. 

```
/scim2/Users?filter=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager.displayName+eq+abc
```

For `attributes` and `excludedAttributes` as well it should accept the same format. But due to the issue https://github.com/wso2/product-is/issues/11092, it is accepting the following format (note the dot after `User`)
```
/scim2/Users?attributes=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.manager.displayName
```

[1] https://is.docs.wso2.com/en/latest/develop/extending-scim2-user-schemas/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
