### ISSUE TITLE
Improvements adaptive script editor in console

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11109]
**Is your suggestion related to an experience ? Please describe.**
Currently, as we add steps in the authentication sequence the adaptive script gets modified automatically.

However, If the auto-generated script is modified once (Let's say by adding a comment etc.), Thereafter it does not adjust with new steps or removal of steps.

It doesn't warn when there are missing executeStep() statements for steps added on a modified adaptive script.

For example, I might configure 3 steps but only have executeStep(1) and executeStep(2) in the script. The editor should warn me of the missing step. 

This happens in the management console editor

![image](https://user-images.githubusercontent.com/5237653/106004043-d0f74300-60d8-11eb-869f-4c5ae01ebff2.png)

**Describe the improvement**
- Show warnings for missed executeStep() statements.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
