### ISSUE TITLE
[SCIM2] Error code not returned in the response when password history is violated

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#11107]
**Is your suggestion related to an experience ? Please describe.**
In password policy violation we return the proper error code in the scim response but password history violation the error 
code is not returned.

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"This password has been used in recent history. Please choose a different password","status":"400"}`

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"36001 - Un-expected error during pre update credential by admin, Password length should be within 5 to 30 characters","status":"400"}`

**Describe the improvement**
Return the error code in the scim response body.

IS -5.10.0

**Comment by ashans** [comment]
I will be working on this

**Comment by Thumimku** [comment]
With this issue, we filtered history violation error in SCIM manager, https://github.com/wso2/product-is/issues/8299

we can add error with the message too

**Comment by asha15** [comment]
@Thumimku Shall we get this added to the doc as well ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
