### ISSUE TITLE
Modify ID token audience input field in Application protocol configuration page to take audiance inputs one by one

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#11118]
**Is your suggestion related to an experience ? Please describe.**

Currently, **Console > Application > Protocol > ID Token Audience** input filed takes audiences as a comma separated list. However, it will be better if we can modify the input filed to enter audiences one by one similar to the Audience input field in 

 Current **Console > Application > Protocol (OIDC) > ID Token Audience** input filed is this.
![image](https://user-images.githubusercontent.com/25479743/106093906-28d48f00-6157-11eb-808a-ea85c5499376.png)

The existing **Console > Application > Protocol (SAML) > Audience** input field takes in one audience at a time. We can do a similar improvement for the above field as well.
![image](https://user-images.githubusercontent.com/25479743/106094295-c5972c80-6157-11eb-9592-9ffabf600db4.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
