### ISSUE TITLE
Setting challenge questions with spaces at the end breaks the user portal 

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11123]
**Describe the issue:**
Setting challenge questions with spaces at the end breaks the user portal.

**How to reproduce:**

- Add a new challenge question[1] with space at the end, eg - "your nickname? "
- Log in to the user portal from a user account and set the answer for the challenge question added with the space.
- The following error would be observed after saving the answers.
<img width="1246" alt="Screenshot 2021-01-28 at 22 51 48" src="https://user-images.githubusercontent.com/47600906/106176580-7edc1d80-61bd-11eb-87b4-209bb93ae7db.png">

**Expected behavior:**
The above error should not be observed. If spaces are not trimmed when adding challenge questions, they need to be trimmed when getting them out.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by emswbandara** [comment]
Effort BE::1 day
