### ISSUE TITLE
User-portal missing translation for Email recovery description

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11124]
**Describe the issue:**

![image-2021-01-27-15-54-00-257](https://user-images.githubusercontent.com/719073/106190247-62e17780-61cf-11eb-99f3-a14b32f0ab95.png)

An incorrect namespace has been used at [1]. It has to be `views` instead of `userPortal`

**Environment information**
 - Product Version: IS 5.10.0 WUM (Not applicable to 5.10.0 GA or 5.11.0)

[1] https://github.com/wso2/identity-apps/blob/v1.0.72/apps/user-portal/src/components/account-recovery/options/email-recovery.tsx#L230-L233

**Comment by ChamathNS** [comment]
This issue is fixed in IS-5.10.0 WUM with https://github.com/wso2-support/identity-apps/pull/74.
