### ISSUE TITLE
"Fetching Failed" error when loading dashboard widgets - timeout of 10000ms exceeded.

### ISSUE THREAD

**Issue by Manasha11** [wso2/product-is#11125]
**Describe the issue:**
Getting a "Fetching Failed" error in the dashboard widgets when loading the widgets if there is a network delay.
Timeout of 10000ms exceeded.

**Affected Product Version:**
5.7.0

**Related issues:**
https://github.com/wso2/analytics-apim/issues/1369

![will1](https://user-images.githubusercontent.com/21274746/106224326-23d01800-6209-11eb-81ae-4421ff5f705d.png)
![will2](https://user-images.githubusercontent.com/21274746/106224332-26cb0880-6209-11eb-88a6-5e29ee4ed731.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
