### ISSUE TITLE
[SCIM] user filtering doesn't work without count param when using email as username

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11126]
**Describe the issue:**
Enable email as username and try the following request:
```
https://localhost:9443/scim2/users?filter=userName+eq+test125@gmail.com

```
Try to filter users without giving count param. The result is as follows, even there exists a user with username = test125@gmail.com

```
{
    "totalResults": 1,
    "startIndex": 1,
    "itemsPerPage": 0,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ]
}
```
**How to reproduce:**
1. Enable email as username (https://is.docs.wso2.com/en/latest/learn/using-email-address-as-the-username/#using-email-address-as-the-username)
2. create a user with username - test125@gmail.com
3. Try out the above request 

**Expected behavior:**
Filtering request should return the matching user object even without "count" param

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-m7
 - OS: Linux,
 - Database: H2
 - Userstore: LDAP

**Comment by mevan-karu** [comment]
This issue is not reproducable in the latest 5.12.0-M8-SNAPSHOT pack. Hence, closing this issue.
