### ISSUE TITLE
Move the logics which consists of multiple transactions from the API layer to the OSGI layer

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#11131]
**Is your suggestion related to an experience ? Please describe.**
There are some API level logics which require multiple calls with the OSGI layer. If any error occurred in the middle of the process then we have to handle the rollbacks in the API layer.

**Describe the improvement**
The multiple steps can be moved to the OSGI layer and they should be executed using a single call from the API layer.

Noted the following places to do the improvements:
* Creating OIDC apps consists of two main steps to create OIDC application and update CORS Origins. Ref: https://github.com/wso2/product-is/issues/11048#issuecomment-766538786

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
