### ISSUE TITLE
Research on the use of Storage Access API

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#11139]
**Is your feature request related to a problem? Please describe.**

The heavy browser restrictions imposed upon cookies, especially in third-party contexts bring many challenges. These are discussed with details here https://github.com/wso2/product-is/issues/10979.

However, there can be valid use cases that require access to cookies in 3rd party contexts such as some identity flows. The recommendation from Safari for these scenarios is to use the storage access API and request access to cookies in 3rd party contexts.

In the Identity server, there are many flows impacted by the heavy cookie restrictions in 3rd party contexts. More information is described in https://wso2.com/blogs/thesource/the-impact-of-blocked-third-party-cookies-on-wso2-identity-server/.

**Describe the solution you would prefer**
Explore storage access API and see how Identity server flows can benefit from it. At first, the use cases with storage access API should be understood and then need to check how to leverage it for impacted Identity Server flows.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
