### ISSUE TITLE
Two error messages shown in the password reset page

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11147]
**Describe the issue:**
Similar to the issue https://github.com/wso2/product-is/issues/10639. It is happening in the accountrecoveryendpoint/password-reset.jsp due to a missing div id property.

**How to reproduce:**
- Enable password history feature
- Goto password recovery flow and enter a previous password
- After you got the error message, enter two different values for the new password and confirm password

**Expected behavior:**
It should hide the backend generated the error before showing the UI validation error.

**Environment information** 
 - Product Version: IS 5.10.0

**Comment by emswbandara** [comment]
Effort BE::1 day
