### ISSUE TITLE
Check the impact with bounce tracking preventions in Safari

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#11140]
**Is your suggestion related to an experience ? Please describe.**

Safari's intelligent tracking prevention(ITP) algorithm introduced a bounce tracking prevention method[1] as part of an effort to enhance user privacy. 

However, this may negatively affect Identity Server flows especially with quick redirections made to the IdP.

[1] https://www.cookiestatus.com/safari/#other

**Describe the improvement**
Need to investigate whether Identity Server redirections are affected with Safari's bounce tracking prevention methods.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
