### ISSUE TITLE
Distributed claim and aggregate claim support for openid connect 

### ISSUE THREAD

**Issue by anusharp** [wso2/product-is#11146]
**Is your suggestion related to an experience ? Please describe.**

Azure AD B2C send some claims with reference for their userinfo endpoint response. In order to have complete claims from the WSO2 IS when federated authentication enabled, distribute claims feature should be implemented. 
As well as, user info response can contains aggregate claims as well according to OIDC spec. Therefore supporting aggregate claim also might be require to compliance with the spec.

**Describe the improvement**

According to OIDC spec it explains that user info response can be contained distribute claims and aggregate claims, then WSO2 IS should derive claim values based on the user info response correctly. This feature is not supported by the current implementation. 

**Additional context**

Reference : https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
