### ISSUE TITLE
[Console][UI/UX]Optimise Summary window of Create new Role

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#11149]
**Is your suggestion related to an experience ? Please describe.**
In our role creation in the console app, we can create Roles without any permission nor group, user mappings. This results following summary screen.

![NextIsse](https://user-images.githubusercontent.com/25488962/106413461-1f596880-6470-11eb-82f7-c7b343ec63e4.png)
This UI has a lot of empty screen, can we optimize that or can we remove this Summary screen cause the User can always go back and check the config.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
