### ISSUE TITLE
When username is configured as the subject URI, email is returned as the sub in ID_Token

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#11154]
**Describe the Issue:**

**How To Reproduce:**
1. Create a SPA app
2. Add requested attributes
3. Access the app and obtain a token (JS sample)
4. sub is set as email claim

Attribute config from console
![image](https://user-images.githubusercontent.com/5061791/106447961-20a68780-64a8-11eb-9a09-9dd3e80be3af.png)

Claim config as of management console
![image](https://user-images.githubusercontent.com/5061791/106448142-5cd9e800-64a8-11eb-9c44-99aff6ae1dd2.png)

 
**Expected behavior:**
Sub must be the username.

Note: Try this in JDBC user store

**Comment by IsuraD** [comment]
This is not reproducible in IS 5.12.0 m8. 

The issue can occur if the same mapped attribute is configured for email address and username claim URIs. 
In that case, if the email is changed the value of the username claim URI will also be changed. But the actual username will not be changed. Hence, an inconsistency will occur in the actual username and username claim URI. 

Thus. It is not recommended to use the same mapped attribute for username claim URI and email claim URI when using email as username.
