### ISSUE TITLE
Need to get rid of outdated libraries saaj-impl and stax-ex

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#11157]
**Describe the issue:**
With JDK 11 SAML2 Artifact Binding not working as mentioned in [1]

[1] https://github.com/wso2/product-is/issues/9195

As the current solution, we will be packing the relevant jars saaj-impl-1.5.0.jar, stax-ex-1.8.3.jar to the product but we need to get rid of outdated libraries as they may cause some other issues down the line.

**Expected behavior:**
Removing outdated jars

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
