### ISSUE TITLE
Workflows are not triggered properly for operations carried out against Internal Roles

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11155]
**Describe the issue:**
A Workflow is triggered and a workflow approval request is sent on "Update Roles of User" operation for Internal Roles, but the user is added to the Internal Role without needing approval

**How to reproduce:**

- Set user_roles_cache_enabled = false in deployment.toml file
- Set up a workflow for "Update Roles of User" operation.
- Assign/remove a role from a user, a workflow would be triggered however the Internal Role is added to the user without needing approval.

The issue occurs because the internal roles and groups are handled separately[1], the internal roles are removed from the role list and processed separately hence the listeners don't get the internal roles.

[1]https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L5469

**Environment information** **:**
 - Product Version: [ IS 5.11.0]

**Comment by emswbandara** [comment]
Effort BE::3

**Comment by nilasini** [comment]
While testing the fix for the above issue found the following bugs

1. Can't delete roles with workflows
2. Assigning secondary user store users to internal role fails

With the same PR fixed the above two issues as well.

**Comment by nilasini** [comment]
Found one more issue while testing.

With workflow, adding the roles with permission fails.

**Comment by nilasini** [comment]
Test should be added. Created an issue to track it

https://github.com/wso2/product-is/issues/11284
