### ISSUE TITLE
The configs doesn't follow the naming convention and need to follow the convention

### ISSUE THREAD

**Issue by nipunthilakshan** [wso2/product-is#11166]
**Describe the improvement**

https://github.com/wso2/identity-apps/blob/master/features/org.wso2.identity.apps.console.server.feature/resources/deployment.config.json.j2#L503   several values defined here need to follow the convention as  **console.ui.is_default_dialect_editing_enabled**

**Comment by nilasini** [comment]
@nipunthilakshan Is it fixed? Can we close the issue?

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/1633
