### ISSUE TITLE
[Console] Need to remove validation error when user enter correct input after  wrong input

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#11168]
**Describe the issue:**
While creating Group, the User can add a Group name, and if enters an invalid group name and click next he will get the following error.

But after he enters the correct value, unless he clicks outside the text field the error will show on the UI.
![Error](https://user-images.githubusercontent.com/25488962/106701742-2a95cb00-660d-11eb-8bd2-01b15be685f4.gif)

**Comment by Thumimku** [comment]
The reason for this issue is, validation method set to run in OnBlur [https://github.com/wso2/identity-apps/blob/d23b6f81de64e80472a9dbd75aac4873c06dfc8b/modules/forms/src/forms.tsx#L239](https://github.com/wso2/identity-apps/blob/d23b6f81de64e80472a9dbd75aac4873c06dfc8b/modules/forms/src/forms.tsx#L239)

We need to change to the OnChange method.

Then we will have a problem since we send groupnameValidationregex request and GroupName Search request in this validation request, User input will be slowed (not suitable for (UX)[https://github.com/wso2/identity-apps/blob/60c943bccbec9e98874d1988195cd88666d33cee/apps/console/src/features/groups/components/wizard/group-basics.tsx#L257](https://github.com/wso2/identity-apps/blob/60c943bccbec9e98874d1988195cd88666d33cee/apps/console/src/features/groups/components/wizard/group-basics.tsx#L257)

We can add a timeout for sending the request, but the validation will be updated as true after the request sent, cause it an await  method.

**Comment by nilasini** [comment]
Couldn't reproduce the issue with wso2is-5.12.0-alpha18
