### ISSUE TITLE
Insufficient information for enabling the Last login Time 

### ISSUE THREAD

**Issue by anusharp** [wso2/product-is#11162]
**Is your suggestion related to a missing or misleading document? Please describe.**

According to instruction in this [1], below [2] configuration will be enabled the last login time in the user profile similar to previous behavior. But it didn't work as per describe.

[1] https://is.docs.wso2.com/en/5.10.0/setup/migrating-what-has-changed/#handling-last-login-time-as-an-identity-claim

[2] 
        [identity_mgt_account_suspension]
        use_identity_claims = false

**Describe the improvement**

By following  below steps, functionality works fine, therefore updating these steps will be helpful.

1. Register new claim  to keep the value of lastLoginTime under wso2 claims
2. Enabled suspension notification from one of below approach
        2.1. [identity_mgt.events.schemes."suspension.notification".properties]
        enable = true 
        OR
        2.2. Go to Identity Provider --> Resident  --> Account Management Policies -->  Lock idle Accounts & check the Enable

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
