### ISSUE TITLE
Erroneous behaviour when reading temporary claim for user from the adaptive script.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#11164]
**Describe the issue:**
In adaptive authentication scripts there is a functionality [1] offered to set temporary claims for user which will be bound to the user's session. However, when testing this feature, it can be seen that there is an issue with reading temporary claims from the adaptive authentication script.

**How to reproduce:**
1. Send a SAML authentication request along with an additional query parameter called 'actingfunction'.
2. Persist the value present in 'actingfunction' as a temporary claim from the adaptive script.
3. Open a new browser tab and resend the SAML authentication request but this time without the additional query parameter.

**Expected behavior:**
During step 3 the temporary claim value (persisted in step 2) should be accessible via the adaptive script as it is the same user session. However currently, we can't access this temporary claim.

Tested IS version: IS 5.7.0 and IS 5.10.0

[1] https://github.com/wso2/product-is/issues/9293

**Comment by emswbandara** [comment]
Effort BE::1 day
