### ISSUE TITLE
Issue when assigning roles via the console app

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#11163]
**Describe the issue:**

### **How to reproduce:**
**Issue 1**
- Log in to the console and create a role and assign the following permission.
   ```
   /permission/protected/manage/modify/tenants
   ```
- When clicking `finish` notice that the role call sends permission as `/permission/protected/manage/modify`.
- Navigate to the management console and observer the permissions of the role. Notice that `/permission/protected/manage/modify` also selected.
- Now create another role with scim with same permission(`/permission/protected/manage/modify/tenants`).
- Now, navigate to the management console and observer the permissions of the role. Notice that `/permission/protected/manage/modify` is not selected compared to the previous role.

**Expected behavior:**
The UI should display the have the same behavior for both cases.

**Issue 2**
- Log in to the console and create a role and assign the following permission.
   ```
   /permission/protected/manage/modify/tenants
   ```
- View the permissions from the console.
- Now try to add `All Permissions>Super Admin Permissions>Manage>Monitor>Tenants>List` and notice we are losing the previous tenant permissions from the UI.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
