### ISSUE TITLE
Roles inherited from groups are not displayed

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#11171]
**Is your suggestion related to an experience? Please describe.**
I created a user named `jenny` and a group named `baseball-team`. Then created a role name `sports-room-admin` and assigned that role to the baseball-team group.

When I go to jenny's roles, `sports-room-admin` is not shown under the roles tab.

**Describe the improvement**
UI should show something like `sports-room-admin via baseball-team group ` under jenny's roles.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
