### ISSUE TITLE
Workflow and Approval Request not triggered when "Update Users of Role" of operation is carried out for an Internal Role

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11173]
**Describe the issue:**
Workflow and Approval Request not triggered when "Update Users of Role" of operation is carried out for an Internal Role

**How to reproduce:**
Set up a workflow definition and associate it with workflow engagement with "Update Users of Role" operation.
Add/update users of an Internal Role.
The workflow does not get triggered.

**Expected behavior:**
The workflow should get triggered when the user is added to the Internal Role.

**Environment information**  **:**
 - Product Version: [IS 5.11.0]

Related : https://github.com/wso2/product-is/issues/11155

**Comment by piraveena** [comment]
This is working fine in IS 6.0.0-alpha3 and closing this
