### ISSUE TITLE
Index values greater than unsigned short are set for the AttributeConsumingServiceIndex when registering a SAML service provider

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11180]
**Describe the issue:**
Index values greater than unsigned short are set for the AttributeConsumingServiceIndex when registering a SAML service provider. The saml-core document[1] states that the AttributeConsumingServiceIndex should be of type unsignedShort(Page 50).
<img width="762" alt="Screenshot 2021-02-04 at 15 06 50" src="https://user-images.githubusercontent.com/47600906/106873720-bf2a2700-66fa-11eb-9fd0-58babe4951b3.png">

In the code, we need to pass a unsigned short index value to setAttributeConsumingServiceIndex()[2].(Java does not have unsignedShort type)

[1]https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
[2]https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/admin/SAMLSSOConfigAdmin.java#L280

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
