### ISSUE TITLE
[SCIM2] Incorrect status code return for unsupported filter request

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#11182]
**Describe the issue:**
In SCIM Specification there are several filters we can use. If a request sent to a unsupported filter, it shows 500 internal 
error status code.
![Screenshot from 2021-02-04 22-17-39](https://user-images.githubusercontent.com/38417165/106926940-a429d800-6737-11eb-9c8d-d01d5300f077.png)

**How to reproduce:**
Send a request to https://localhost:9443/scim2/Users?filter=name.givenName+ne+kim (Here using unsupported filter ne)

**Expected behavior:**
Status code 501(not implemented) should be provided instead of 500. [1]

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Linux
 
**References:**
[1]https://tools.ietf.org/html/rfc7644#page-68

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
