### ISSUE TITLE
Authorization Code Grant returns error 500

### ISSUE THREAD

**Issue by akravets** [wso2/product-is#11183]
I am following tutorial for [Authorization Code Grant](https://docs.wso2.com/display/IS530/Try+Authorization+Code+Grant) when submitting form I am getting error from the sever instead of being redirected to login screen

**Authentication Error!
Something went wrong during the authentication process. Please try signing in again.**

And I see errors in the log

`[2021-02-04 11:30:43,609] [4331423f-a6f4-4f47-82fa-1f2ae1741010] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/authenticationendpoint].[oauth2_login.do]} - Allocate exception for servlet [oauth2_login.do] org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [25] in the jsp file: [/includes/localize.jsp]
Duplicate local variable BUNDLE
22: <%@ page import="java.nio.charset.StandardCharsets" %>
23: <%@page contentType="text/html; charset=UTF-8"%>
24: <%
25:     String BUNDLE = "org.wso2.carbon.identity.application.authentication.endpoint.i18n.Resources";
26:     ResourceBundle resourceBundle = ResourceBundle.getBundle(BUNDLE, request.getLocale(), new
27:             EncodedControl(StandardCharsets.UTF_8.toString()));
28: %>

An error occurred at line: [26] in the jsp file: [/includes/localize.jsp]
Duplicate local variable resourceBundle
23: <%@page contentType="text/html; charset=UTF-8"%>
24: <%
25:     String BUNDLE = "org.wso2.carbon.identity.application.authentication.endpoint.i18n.Resources";
26:     ResourceBundle resourceBundle = ResourceBundle.getBundle(BUNDLE, request.getLocale(), new
27:             EncodedControl(StandardCharsets.UTF_8.toString()));
28: %>
`
I tried Password Grant and it works fine

**Environment information:**
 - Product Version: IS 5.11
 - OS: Manjaro 20.2

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
