### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by office-elainetan** [wso2/product-is#11188]
Location : https://is.docs.wso2.com/en/latest/learn/self-registration-and-account-confirmation/,
after following the steps stated at the document above, then did testing and found below,
1. Document stated https://localhost:9443/user-portal/,  but the page not found (HTTP Error 401). Instead , I need to go to the https://localhost:9443/accountrecoveryendpoint/signup.do
![image](https://user-images.githubusercontent.com/78583320/106996590-3e336400-67bc-11eb-962b-9bcbd780593e.png)

2. After filling up the proper info at the signup page, then continue filling up info at Create New Account page , then click [Register], it hit the below errors. at https://localhost:9443/accountrecoveryendpoint/processregistration.do
error “invalid tenant domain : null”
![image](https://user-images.githubusercontent.com/78583320/106996539-2956d080-67bc-11eb-8b73-d42d1b52b89f.png)

**Comment by office-elainetan** [comment]
Hi,
the error "invalid tenant domain" is gone when i retried the self signed up by go to URL, https://localhost:9443/myaccount/login, fill up all necessary info ,then click [Register] and have got message : “Confirmation link has been sent to your email". 
After that, i checked my registered email, and did not receive any confirmation link from wso2. Please advise.
![test-wso2-selfsignedup](https://user-images.githubusercontent.com/78583320/107328428-a8fcdc00-6ae9-11eb-9804-7eb04e334911.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
