### ISSUE TITLE
Issue in user consent for OIDC app

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11191]
**Describe the issue:**
In an OIDC app when logging in the consent will be prompted. When giving consent only once by clicking "Allow" if the user logout and login again then consent should be re-prompted. But it does not happen.

**How to reproduce:**

1. Create an OIDC app
2. Add a required claim (ex: first name)
3. Trigger a login flow according to the OIDC protocol(ex: authz code)
4. After entering the credetials you will be prompted for consent. Click on "Allow" (DONT tick remember my consent).
5. Now logout and try to login again
6. The app should prompt for consent but it won't.

**Expected behavior:**
Consent should be prompted again as "remember my consent" was not ticked.

**Comment by ChanikaRuchini** [comment]
Tried the flow using wso2is-5.12.0-m33 and works as expected
