### ISSUE TITLE
JIT provisioning drops the roles which don't have a mapping

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11195]
**Describe the issue:**
We have a configuration called FederatedRoleManagement.ReturnOnlyMappedLocalRoles [1] to configure whether we need to get roles which has a mapping only during the federation flows. 

The same config was applicable for JIT provisioning flow as well.  We could set ReturnOnlyMappedLocalRoles to false and allow roles to be provisioned with the same name without adding the mappings manually.

But later, we have done a refactoring of the JIT flow [2] and moved it to a post-auth-handler. Since then, we have only taken the roles with a mapping and excluded others [3].

Now if somebody migrates from an older version to a newer version, the previous behavior changes. It will only provision the mapped roles.

We have a workaround to customize this logic by extending the JITProvisioningPostAuthenticationHandler [3], but we will have to duplicate the whole class since it has multiple private methods.

**Steps to reproduce**
- Configure an IDP with JIT provisioning
- Create roles locally with the same names as external IDP has
- Do not add IDP role mapping
- Try logging in, the roles will not be added to the provisioned user

**Expected behavior:**
It should allow JIT provisioning roles with do not have mappings created if the remote role and local role names are matching.

**Environment information** 
 - Product Version: IS 5.10.0

[1] https://github.com/wso2/carbon-identity-framework/pull/1560/files
[2] https://github.com/wso2/carbon-identity-framework/pull/1629
[3] https://github.com/wso2/carbon-identity-framework/blob/1d57e2e8fe95d99a56ad971a6ec2a56b5bb44eeb/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/JITProvisioningPostAuthenticationHandler.java#L678-L683

**Comment by rksk** [comment]
We need to make sure this does not break the experience of the new deployments because they were working with this behavior in new versions.

**Comment by emswbandara** [comment]
Effort BE::1 day
