### ISSUE TITLE
Inconsistency in enforcing mutability of claims

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#11194]
**Describe the issue:**

Currently, when the SCIM2 schemas endpoint (https://localhost:9443/scim2/Schemas) is called, the properties of the claims in `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` dialect are formed using the properties of the corresponding mapped local claim instead of the properties defined in <IS_HOME>/repository/conf/scim2-schema-extension.config file. 

For an example even though the `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:lockedReason` claim's mutability is defined as read-only in scim2-schema-extension.config, the SCIM2 schema endpoint returns the below attributes which correspondent to the mapped identity claim - `http://wso2.org/claims/identity/lockedReason` which states the claim's mutability is read-write.
```
            {
                "uniqueness": "NONE",
                "displayName": "Locked Reason",
                "name": "lockedReason",
                "displayOrder": "0",
                "description": "Locked Reason",
                "mutability": "READ_WRITE",
                "type": "STRING",
                "multiValued": false,
                "caseExact": false,
                "returned": "DEFAULT",
                "required": false
            },
```
In the Console/MyAccount applications, the schema endpoint is used to manage the user profile attributes. Hence, the user profile attributes returned as read-write by the schema endpoint are allowed to be edited in the Console/MyAccount. However, Charon component validates whether the updated enterprise schema attributes are read-only against the configuration defined in scim2-schema-extension.config [1]. If the claims are defined as read-only in the scim2-schema-extension.config, Charon throws an error and resulting in a error. 

[1] https://github.com/wso2/charon/blob/139c9170e1df0d56ce0e5db74bbf692eae915b6c/modules/charon-core/src/main/java/org/wso2/charon3/core/utils/PatchOperationUtil.java#L3564

**How to reproduce:**
1. Go to 'Attribute Dialects' in Console app.
2. Check 'Show this attribute on user profile and user registration page' in 'Locked Reason' claim and update. Do not tick 'Make this attribute read-only'.
3. Go to a user's profile in Console and try to update any detail (ex: Update mobile number).
4. When clicked on the update button following an error occurs as Charon throes an exception since 'Locked Reason' claim in the SCIM2 enterprise schema dialect is read only.

**Expected behavior:**
The mutability(or any other property) of the claims should be enforced using either the properties of the local claim or the properties of the corresponding enterprise schema claim, and that should be consistent in all the places. 
i.e. If Schema endpoint returns the properties of the mapped local claims, the validations done by Charon when updating the claims should be done using the same properties.

**Comment by DinikaSen** [comment]
On a side note, a claim can generally be one of the below types.
- claims which can be viewed and edited by the end user
- claims which can be viewed and edited by the admin
- claims which can be edited by the server only

For the first two types of the above claims, the admin should be able to define the properties of the claims such as the mutability. Hence, it is preferred if we can use the properties of the claims in local dialect to enforce the behaviour of the claims.

**Comment by nilasini** [comment]
We can change the http://wso2.org/claims/identity/lockedReason claim attribute through claim-config.xml file [1] as readonly so that we can avoid the issue. Likewise we can do this for all the claims which are having different values in claim-config and scim2-schema-extension.config file.

[1] https://github.com/wso2/carbon-identity-framework/blob/master/features/claim-mgt/org.wso2.carbon.claim.mgt.server.feature/resources/conf/claim-config.xml#L462

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
