### ISSUE TITLE
The 'aut' oidc claim value is misleading

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#11200]
**Describe the issue:**
When obtaining the JWT token for client credential grant type it returns 'APPLICATION' for the OIDC claim 'aut' to denote application tokens. For the other grant types, it returns 'APPLICATION_USER' to denote user tokens. The value 'APPLICATION_USER' is a bit misleading. Suggesting to change the value 'APPLICATION_USER' > 'USER'

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
