### ISSUE TITLE
Analytics Events are not Published When Analytics is Enabled

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#11202]
**Describe the issue:**

When the Analytics is enabled and login activities are performed the analytics dashboards are still empty. There is no sign of evens are published from IS.
**How to reproduce:**

1. Enable Analytics according to the official [doc](https://is.docs.wso2.com/en/latest/learn/prerequisites-to-publish-statistics/)
2.  Perform login activities
3.  Access the Analytics dashboard/portal app

The portal should be empty.

**Expected behavior:**

The portal should be populated with logins and session statistics.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ajanthan** [comment]
Further analysis revealed that the event publishers in the repository/conf/identity/identity-event.properties file are not enabled when the deployment.toml file is updated according to the doc. After updating the default values from the config template, the events are published to the analytics worker.

`repository/conf/identity/identity-event.properties`

```
< analyticsSessionDataPublisher.enable=false
---
> analyticsSessionDataPublisher.enable=true
< analyticsLoginDataPublisher.enable=false
---
> analyticsLoginDataPublisher.enable=true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
