### ISSUE TITLE
Improvement to SCIM user filtering with ge and le operations 

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#11214]
Currently, SCIM user filtering is supported with eq, sw, co and ew operations. With these operations, it is not possible to filter users for cases like filtering users by last password modified date. To support that it is required to introduce the following operations to the product.
- ge (greater than or equal)
- le (less than or equal)

**Comment by rksk** [comment]
The solution is not implemented in legacy flow. So `le`, `ge` filters will not work if pagination parameters are not defined.

Should be addressed with https://github.com/wso2/product-is/issues/4943 https://github.com/wso2/product-is/issues/10580
