### ISSUE TITLE
"Assert identity using mapped local subject identifier" property is not working for federated users

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#11216]
**Description**
The userstore domain does not append for JIT provisioned users, when the Assert identity using mapped local subject identifier property is enabled.

**How to reproduce:**
1. Configure federated Authenticator
2. Enable JIT provisioning
2. Enable "Assert identity using mapped local subject identifier" under the "Local and Outbound configuration" in the service provider configurations 
3. Use configured federated authenticator as the authentication type.
4. Log in to the application and check the sub value

**Expected behavior:**
Userstore domain needs to be appended to the sub claim value.

**Environment information** 
 - Product Version: IS-5.2.0

**Comment by emswbandara** [comment]
Effort BE::1 day

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
