### ISSUE TITLE
Behaviour change in OAuth/OIDC consent screen

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11218]
With the fix https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1540 done for https://github.com/wso2/product-is/issues/11207 the behaviour of the consent screen has changed.

Previous behaviour:
When using an OIDC app and request OIDC registered scopes(Ex: email, profile) these scopes where displayed under permissions requested part in the consent screen.

New behaviour:
Requested OIDC scopes will no longer be displayed under permission request scopes in the consent screen.

Explanation:
OIDC scopes are for claim request and are not related to permission request(which are OAuth scopes).

Note: There is no config to revert this change as it is not necessary.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
