### ISSUE TITLE
Improve Logging in user core

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#11215]
There are some place which swallows the original exceptions such as https://github.com/wso2/carbon-kernel/blob/release-4.4.35/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadWriteLDAPUserStoreManager.java and which leads to enable additional logs in production systems.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
