### ISSUE TITLE
Use UUID for the "sub" claim in the user attributes.

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#11225]
**Describe the issue:**

Currently, the subject claim can be selected by the user in the application user attribute section.
As per the spec [1], since the "sub" claim `unique and never reassigned identifier within the Issuer`, letting the user choose the `sub` claim is erroneous.
Hence, the user-defined sub-attribute should be deprecated and the sub-attribute should be set internally, ideally a UUID.
For this, we can make use of the Pairwise Pseudonymous Identifier (PPID) defined in [2] 

[1] https://openid.net/specs/openid-connect-core-1_0.html#IDToken
[2] https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
