### ISSUE TITLE
confirmation codes cleanup script is deleting everything

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11231]
**Describe the issue:**
The stored procedures (eg: [1]) written to cleanup old confirmation codes from the table IDN_RECOVERY_DATA (to address the issue https://github.com/wso2/product-is/issues/8509) is deleting all the records from the table without considering any logic. So, this would delete the active confirmation codes as well.

[1] https://github.com/wso2/carbon-identity-framework/blob/ad2d23217d741aa5563e407337d62d2b6aeb6e17/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mssql/confirmation-code-cleanup/mssql-confirmation-code-cleanup.sql

**Comment by sumedhe** [comment]
@DinikaSen has done this fix, with wso2/carbon-identity-framework#3371

**Comment by rksk** [comment]
> @DinikaSen has done this fix, with [wso2/carbon-identity-framework#3371](https://github.com/wso2/carbon-identity-framework/pull/3371)

I believe we need to fix this in all the DB types. Added a comment in the PR.

**Comment by rksk** [comment]
Now, this is fixed for MySQL and MSSQL. Keeping the issue open to track the fixes for other DB types.

**Comment by piraveena** [comment]
Confirmation code cleanup scripts are found for the following DBs. This task is already completed for MySQL and MsSQL.
- [ ] [Postgres11](https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/postgresql/postgre-11x/confirmation-code-cleanup)
- [ ] [Oracle](https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/oracle)
- [ ] [MySQL](https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mysql/confirmation-code-cleanup)
- [ ] [MsSQL](https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mssql/confirmation-code-cleanup)

**Comment by piraveena** [comment]
Fixed for the existing cleanup scripts
