### ISSUE TITLE
Disabled users still receive user account suspension notification

### ISSUE THREAD

**Issue by matt-maggiore-pointillist** [wso2/product-is#11243]
**Describe the issue:**
A user who has been manually disabled still receives the email notifications that their account will be suspended soon.

(referring to this feature here https://docs.wso2.com/display/IS530/User+Account+Suspension )

**How to reproduce:**
1. manually disable a user
2. wait for the User Account Suspension task to run

**Expected behavior:**
If the user is already disabled, they should not receive warnings that their account will be disabled in the future.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: WSO2 IS 5.3.0
 - OS: Linux
 - Database: MYSQL
 - Userstore: JDBC

---

If this issue is fixed in a later release, please let me know

**Comment by Sahilgandas1** [comment]
Like if a user is disabling its account manually , then user should get a authentication notification mentioning that if you choose disable then you will be disabled and will not receive any notification regarding suspension and if the user chooses agree button , user's account should be disabled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
