### ISSUE TITLE
[SCIM2] Unexpected status code when patching a non existing group

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#11248]
**Describe the issue:**
Patching a group with non existing group gives status code 500.
![Screenshot from 2021-02-11 14-36-17](https://user-images.githubusercontent.com/38417165/107622341-b9de5680-6c7d-11eb-82e3-ee541e5903e5.png)

**How to reproduce:**
Sent a PATCH request to https://localhost:9443/scim2/Groups/{id} with a non existing group id with the following request body.
```

{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [  
     {
      "op": "add",
      "value": {
        "members": [
          {
            "display": "samindra",
            "value":"17712b98-3957-48cd-bc49-c4559df817b3"
          }
        ]
      }
    }
  ]
}
```

**Expected behavior:**
For a non existing resource status code 404 should be given with the response.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Linux

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
