### ISSUE TITLE
Removing CORS Allowed Origins created with SPA creation

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#11241]
**Describe the issue:**
Currently it's not possible to delete them directly as those origins might be used in another SPA also. An SPA which is not configured CORS Origins but it is working as the CORS valve functioning with tenant level origins.

**How to reproduce:**
1. Open Console
2. Create an SPA, with configuring Allowed Origins.
3. Delete the SPA.
4. Create another SPA in the same domain but not configuring Allowed origins.
5. It will work without any issue

**Expected behavior:**
The second SPA should be blocked by CORS as it is not configured allowed origins.

### Optional Fields

**Suggested labels:**
bug

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
