### ISSUE TITLE
Primary roles deleted directly from the LDAP should not get listed in the SCIM2 Groups endpoint result.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#11249]
**Environment**
IS-5.10.0
WUM 2021 February
ApacheDS in-built LDAP

**Issue description**
Direct LDAP role deletions cause stale records in **IDN_SCIM_GROUPS** table. These stale records are returned in the SCIM Groups GET endpoint result as below.
`https://localhost:9443/scim2/Groups`
But if you try to filter for the deleted role, you won't get any results.
`https://localhost:9443/scim2/Groups?filter=displayName+eq+testrole`

**Expectation**
If a PRIMARY role isn't available in the LDAP(Direct deletion from the LDAP), Identity Server should not list that in the SCIM2 /Groups GET response. Identity Server should be able to gracefully handle the directly deleted primary roles in the SCIM2 Groups list endpoint.

**Reproducing steps**
1. Create a new PRIMARY role.
2. Connect to the LDAP and delete the newly created role from there.
3. Execute the `GET https://localhost:9443/scim2/Groups` request and make sure the deleted role is still included in the response.
4. Execute the filter request for the same role `GET https://localhost:9443/scim2/Groups?filter=displayName+eq+testrole` and observe the role is not listed in the response.
``

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
