### ISSUE TITLE
[Doc] Authorized App REST API doc is pointing to CORS API postman collection

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11258]
**Is your suggestion related to a missing or misleading document? Please describe.**
Authorized app https://is.docs.wso2.com/en/latest/develop/authorized-apps-v2-rest-api/ this postman collection is pointing to the CORS API postman collection

**Comment by somindatommy** [comment]
Here we do not require this collection. We need to remove the collection part from the documentation. We may need to update this in 5.11.0, 5.12.0 and master.

**Comment by somindatommy** [comment]
This is the link for the api definition
https://raw.githubusercontent.com/wso2/identity-api-user/master/components/org.wso2.carbon.identity.api.user.authorized.apps/org.wso2.carbon.identity.rest.api.user.authorized.apps.v2/src/main/resources/authorizedApps.yaml

**Comment by piraveena** [comment]
This is fixed with https://github.com/wso2/docs-is/pull/2441
