### ISSUE TITLE
One claim's value failure cause to re-enter all other claim values 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11252]
**Describe the issue:**
Consider the user is prompted to add mandatory claims requested for the application during the login flow. 
The application wants your dob and country claims.
If you provide the DoB as follows (not matching with the dob claim regex), the user will be prompted to reenter the claim values.
![Screenshot from 2021-02-11 20-24-45](https://user-images.githubusercontent.com/25483865/107657353-1c018080-6cab-11eb-8ca6-ef2c84364f4d.png)

Page to re-enter the claims:
![Screenshot from 2021-02-11 20-22-04](https://user-images.githubusercontent.com/25483865/107657834-8ca89d00-6cab-11eb-86b3-c734db433d24.png)

This affects UX negatively.
The next time user should be prompted to enter claims in which he made errors. Other claims should be refilled or should not get prompted.

**How to reproduce:**

- Configure a sample app
- Add Date of birth and country as mandatory claims
- Create a user and attempt to login.
- When prompted to give DOB attribute provider "18-11-11" or a value doesn't match with the configured regex and provide a country value(any string)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
