### ISSUE TITLE
Doc Feedback: Registry versioning disable instructions

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#11261]
Location : https://is.docs.wso2.com/en/5.10.0/setup/migrating-preparing-for-migration/

The following section says to turn off the registry versioning. But in real scenarios, it is not necessary to  turn off the registry versioning since we won't be using the same server again after the migration. Also, registry-versioning must be disabled or enabled at the initial server startup. So this doesn't make any sense.

"Therefore, when migrating to IS 5.10.0 it is required to turn off the registry versioning in your current Identity Server and run the below scripts against the database that is used by the registry."

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
