### ISSUE TITLE
Add config to hide the user store name from username in TOTP QR code url

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#11265]
**Is your suggestion related to a missing or misleading document? Please describe.**
Add the following configuration to the TOTP documentation https://is.docs.wso2.com/en/latest/learn/configuring-totp/#totp-configuration-properties

Feild : hide_user_store_from_display_name_in_qr_url
Description: If true, the user store name in the username of the QR code URL will be removed. This also removes the user store name from username displayed in TOTP authenticator after scanning QR. The default value is false.

Added to product https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/89

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
