### ISSUE TITLE
Improvements to claim/attribute dialect management

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11278]
This issue tracks the below improvements related to claim/attribute dialects management

- [ ] Provider a friendly way to define claim groups (eg:  Attributes collected during signup, attributes to show in self care portal user profile etc.) 
- [ ] Provider a better way for admin to mark a claim to be available in the user profile
- [ ] Provider a better way to order attributes/claims in user profile and other places.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
