### ISSUE TITLE
cnf claim not available in self contained(JWT) AT when using certificate bound token requests

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11273]
When using certificate bound access tokens[1] the cnf claim should be bound against the token. When using opaque tokens and introspecting this is seen working as the introspection results shows the cnf claim. 

But when using JWT based access tokens the cnf claim is not available. However, It is seen that the claim value is available as a scope(Note this is only happening for JWT based access tokens). 
It should be improved to remove the cnf claim coming as a scope and to make the cnf claim available as a claim in the JWT access token.

[1] - https://is.docs.wso2.com/en/latest/learn/mutual-tls-client-auth/#configuring-mutual-tls-client-authentication-and-certificate-bound-access-tokens

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
