### ISSUE TITLE
Error while loading user profile metadata with multiple user-stores

### ISSUE THREAD

**Issue by Navino16** [wso2/product-is#11289]
**Describe the issue:**
When adding multiple secondary Active-Directory user-stores (A, B and C for example) with exactly the same configuration for all user-stores but with a different `User Search Base` and same claims configurations for all user-stores, we can't see any user details from user-stores excepte for the last one loaded.

Error from web interface:
> Error while loading user profile metadata

Error from wso2carbon.log:
> TID: [-1234] [] [2021-02-16 15:06:10,133] [b1f238e2-d510-4e2f-9031-562703683f99] ERROR {org.wso2.carbon.identity.user.profile.ui.client.UserProfileCient} - org.wso2.carbon.identity.user.profile.stub.UserProfileMgtServiceUserProfileExceptionException: UserProfileMgtServiceUserProfileExceptionException

If we disable the last user-store (user-store C), user-store B work.

**How to reproduce:**
1. Install WSO2-IS 5.10.0
2. Create 3 user-stores (A, B and C) with exactly same configuration excepte for the `User Search Base`
3. Configure same claims for users-stores A, B and C
4. Go to user list (no problem, all user from all user-stores are here)
5. Go to user detail from user-store C: no problem
6. Go to user detail from user-store A or B: Error while loading user profile metadata
7. Disable user-store C
8. Go to user detail from user-store B: no problem

**Expected behavior:**
All user-stores should work without any issues

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux - Debian 10
 - Database: MariadB 10.3.27
 - Userstore:
   - Primary : JDBC 
   - Secondary : Active-Directory

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
