### ISSUE TITLE
Improve startup time on identity-event-handler-account-lock component

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#11280]
Remove unnecessary check. 
These has to be present as precondition(migration or at different level). Testing this available at the startup on each container is not needed.
Also it may cause concurrent startup issues on container environment.

```
try {
                UserStoreManager userStoreManager = AccountServiceDataHolder.getInstance().getRealmService()
                        .getBootstrapRealm().getUserStoreManager();
                if (!userStoreManager.isExistingRole(AccountConstants.ACCOUNT_LOCK_BYPASS_ROLE)) {
                    userStoreManager.addRole(AccountConstants.ACCOUNT_LOCK_BYPASS_ROLE, null, null, false);
                }
            } catch (org.wso2.carbon.user.api.UserStoreException e) {
                log.error(String.format("Error while adding role: %s .", AccountConstants.ACCOUNT_LOCK_BYPASS_ROLE), e);
            }
```

https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/b169839e3224e198f33bef3dfebde375f84739db/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/internal/AccountServiceComponent.java#L76

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
