### ISSUE TITLE
Need to write sceanrio test and unit test to capture saml artifact binding.

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#11285]
**Describe the issue:**
Scenario test and unit test should be added to capture saml artifact binding issue mentioned in [1]

[1] https://github.com/wso2/product-is/issues/9195

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
