### ISSUE TITLE
Appending tenant domain at the end of SAML issuer instead of `tenantDomain` query parameter does not work

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11298]
**Describe the issue:**
Due to some changes done in the thread-local tenant domain handling while fixing https://github.com/wso2/product-is/issues/5882, now it does not allow to define the tenant domain in the issuer name itself without defining the `tenantDomain` query parameter in SAML inbound flows.

**How to reproduce:**
- Create a tenant; abc.com
- Create a service provider and register a SAML app on the tenant (say issuer name is travelocity.com)
- Configure the SAML App with issuer name as; `travelocity.com@abc.com`
- Try logging in, IS will write the following log
```
WARN {org.wso2.carbon.identity.sso.saml.validators.SPInitSSOAuthnRequestValidator} -  A Service Provider with the Issuer 'travelocity.com@abc.com' is not registered. Service Provider should be registered in advance.
```
- This happens for both idp-init & sp-init flows and both flows need to be fixed

**Expected behavior:**
It should allow to login with SP on the tenant by appending the tenant domain to the SAML issuer name.

**Environment information**
 - Product Version: IS 5.2.0

**Comment by mevan-karu** [comment]
Fixed in the public with https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/250
