### ISSUE TITLE
Change groupID and artifactID of OOTB shipped connectors

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11291]
With https://github.com/wso2/product-is/issues/10612 we have moved few ootb shipped connectors to plugins. Along with this it would be ideal to change the groupid and artifactid of these connectors,

Specifically,
- Change the group ID, artifact ID to remove "connector", "extension" in the name as it is shipped with the product in plugins now
- Change the feature ID to remove "connector", "extension" in the feature id

Change of groupID requires changes on the nexus side as well.

Some suggestions, 

1. TOTP
  | groupId | artifactId
-- | -- | --
Existing | org.wso2.carbon.extension.identity.authenticator.outbound.totp | org.wso2.carbon.extension.identity.authenticator.totp.connector
Proposed | org.wso2.carbon.identity.application.auth.totp | org.wso2.carbon.identity.application.authenticator.totp

2. Email OTP

  | groupId | artifactId
-- | -- | --
Existing | org.wso2.carbon.extension.identity.authenticator.outbound.emailotp | org.wso2.carbon.extension.identity.authenticator.emailotp.connector
Proposed | org.wso2.carbon.identity.application.auth.emailotp | org.wso2.carbon.identity.application.authenticator.emailotp

We can also looking at a group id like org.wso2.carbon.identity.mfa for these authenticators

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
