### ISSUE TITLE
SCIM2 Groups list endpoint returning full list of groups takes too long

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#11297]
**Description**
SCIM2 GET /Groups endpoint returns full list of groups when invoked. If there are many roles in the system this would take considerable time to return the response.
`GET scim2/Groups`

**Improvement**
Please improve this endpoint to impose a maximum(configurable) hard limit for the returning number of groups in the response. So that the users can fine tune the filter if the expected is not returned.

**Environment**
WSO2-is-5.10.0
WUM - 2021 February
Userstore - LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
