### ISSUE TITLE
scim extended schema does not allow sub-attribute names to be re-used

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11294]
**Describe the issue:**

Assume a set of custom extended schema attributes are configured like below.
- vehicle
-- private
-- work
- wallet
-- private
-- work

`vehicle` and `wallet` are complex attributes and `work` and `private` are included as subattributes of each.

Now if we try to create a user by providing values like below, only two of the four values get persisted.
```
   "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{
      "vehicle":{
         "private":"abcd",
         "work":"pqrs"
      },
      "wallet":{
         "private":"mnop",
         "work":"xyz"
      }
   },
   ```

The issue https://github.com/wso2/product-is/issues/9548 is also caused by the same issue. More info can be found in the relevant PRs.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by Kanapriya** [comment]
This fix is available in public, hence close this issue.
