### ISSUE TITLE
SCIM2 Group's member listing via /Users endpoint returns a full list of members causing performance issues.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#11299]
**Description**
SCIM2 Groups endpoint doesn't support member pagination while listing the groups. Therefore, we use the **/Users** endpoint as below.
`GET https://localhost:9443/scim2/Users?filter=groups+eq+admin&startIndex=0&limit=2`
Even this endpoint doesn't honour pagination parameters if the filter contains **groups**. This again returns a full list of members causing performance issues if the given groups filter contains large amount of users.

**Improvement**
Introduce a configurable hard limit to throttle the number of members returned in the `GET https://localhost:9443/scim2/Users?filter=groups+eq+admin` request. (Not pagination, just a hard limit to throttle the number of users)

**Additional context**
WSO2is-.5.10.0
WUM - 2021 February

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
