### ISSUE TITLE
Doc Issue Regarading Token Hashing deployment.toml configs.

### ISSUE THREAD

**Issue by nisho06** [wso2/product-is#11304]
**Is your suggestion related to a missing or misleading document? Please describe.**
[https://is.docs.wso2.com/en/latest/learn/setting-up-oauth-token-hashing/#setting-up-oauth-token-hashing](url)
This particular doc is related to configure HashingPersistenceProcessor for WSO2 IS. HashingPersistenceProcessor is responsible for using hashing in tokens, Authorization code, Refresh token and Client Secret.

To configure this, deplotment.toml config regarding the doc was...
```
[oauth.extensions]
token_persistence_processor = "org.wso2.carbon.identity.oauth.tokenprocessor.HashingPersistenceProcessor"

[oauth]
hash_tokens_and_secrets = true
hash_token_algorithm = "SHA-256"
```
But it is wrong, here the `token_persistence_processor` is being used to define any new custom PersistenceProcessor.

**Describe the improvement**
The deployment.toml config should be..
```
[oauth]
token_storage_method = "hashed"
hash_token_algorithm = "SHA-256"
hash_tokens_and_secrets = true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
