### ISSUE TITLE
Remove SVN references from all versions 

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#11312]
These docs need to be modified for all versions. 
https://is.docs.wso2.com/en/latest/learn/logging-in-to-a-.net-application-using-the-identity-server/#logging-in-to-anet-application-using-the-identity-server
https://is.docs.wso2.com/en/latest/develop/writing-a-custom-federated-authenticator/#custom-authenticator-for-facebook
https://is.docs.wso2.com/en/latest/develop/writing-a-custom-federated-authenticator/#custom-authenticator-for-google

The new restructured version also needs to be modified. (Access through VPN)
https://is-staging.docs.wso2.com/en/staging/extend/access-control/write-a-custom-policy-info-point
https://is-staging.docs.wso2.com/en/staging/extend/federation/write-a-custom-federated-authenticator
https://is-staging.docs.wso2.com/en/staging/extend/rebranding/rebrand-login-pages-for-service-providers
https://is-staging.docs.wso2.com/en/staging/extend/user-mgt/user-store-listeners
https://is-staging.docs.wso2.com/en/staging/references/evolution-of-identity-federation-standards

**Comment by dewniMW** [comment]
"Writing a Custom Federated Authenticator" doc is updated for IS versions from 5.3.0 to 5.11.0.

**Comment by dewniMW** [comment]
"Logging in to a .NET application using the Identity Server" doc is updated for IS 5.11.0

**Comment by rksk** [comment]
https://is.docs.wso2.com/en/latest/develop/writing-a-custom-policy-info-point/

**Comment by rksk** [comment]
https://is.docs.wso2.com/en/latest/learn/working-with-mdp-requests-to-authorize-hierarchical-resources/  (as reported in https://github.com/wso2/product-is/issues/12786)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
