### ISSUE TITLE
Default CORS config changes

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#11310]
Previously by default allowed HTTP methods for CORS was GET, POST, HEAD, OPTIONS
this has been changed to allow the following HTTP methods  GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS

To change the COR configuration refer to https://is.docs.wso2.com/en/latest/learn/cors

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
