### ISSUE TITLE
Doc Feedback: Mention the Oracle db user needs to have "CREATE PROCEDURE" permissions

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#11324]
Location : https://is.docs.wso2.com/en/5.10.0/setup/migrating-to-5100/

In the Oracle and Oracle RAC database, the migration client is failing if the db-user doesn't have the permissions to "CREATE PROCEDURE" along with table, trigger related permissions. It would be better to include the required db permissions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
