### ISSUE TITLE
Behaviour change in subject claim URI consent prompting.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#11329]
The PR [1] removes prompting consent for subject claim URI and hence from 5.10.0 onwards, the subject claim URI consent will not be prompted whether it is configured as a requested claim or not. The behaviour prior to this fix was to prompt mandatory consent for subject claim URI regardless of having it configured as a requested claim or not.

From 5.12.0 onwards an improvement [2] has been done to prompt consent for the subject claim URI only if it is configured as a requested claim. This behaviour is enabled by default. If anyone wants the previous behaviour (subject claim URI consent will not be prompted whether it is configured as a requested claim or not [1]) the following configuration needs to be added.

```
[authentication.consent.subject]
prompt=false
```

[1] wso2/carbon-identity-framework#2745
[2] https://github.com/wso2/carbon-identity-framework/pull/3398

**Comment by ashendes** [comment]
https://is.docs.wso2.com/en/6.0.0/deploy/migrate/what-has-changed/#oidc-consent-updates
