### ISSUE TITLE
ProxyMode dumb?

### ISSUE THREAD

**Issue by JOravas** [wso2/product-is#11336]
**Describe the issue:**

The comments in
https://github.com/wso2/carbon-identity-framework/blob/master/features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/application-authentication.xml

state:

`
    <ProxyMode>smart</ProxyMode>
`
**How to reproduce:**

- SAML SSO
- One SP with only one federated IDP (Authentication Type: Federated Authentication)
- ProxyMode set to "dumb"
- Log into to SP -> prompt to enter Domain value

I'm just wondering why do I get the prompt? Where can I find documentation how this dumb -mode is supposed to be used?

**Expected behavior:**

With ProxyMode "smart" the above case works the way I expected "dumb" to do so with no prompt.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
