### ISSUE TITLE
Doc Feedback: Wrong claim-uri mentioned in the doc

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#11356]
Location : https://is.docs.wso2.com/en/latest/learn/configuring-active-directory-user-stores-for-scim-2.0-based-inbound-provisioning/

The document says to update http://wso2.org/claim uri. But it should be changed to scim2.0 uri.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
