### ISSUE TITLE
[Migration][Migration Doc] Enable conversion of original claims from assertions to OIDC dialect

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#11359]
**Describe the improvement**
For OAuth/OIDC application, default behavior of IS till 5.11.0 was to send the original claims sent from IDP as it is to the service provider without converting the claims OIDC dialect. From 5.12.0-M8 onwards, this behavior has been changed and claims sent from IDP is converted to OIDC dialect before sending to the service provider. This was done by setting the following configuration to `true` by default. 

During a migration, if this feature is not required add the following configuration to `deployment.toml` since this feature is enabled by default from 5.12.0-M8 onwards.

```
[oauth.oidc.claims]
enable_oidc_dialect = false
```

**Affected**
- 5.11.0 to 5.12.0-M7

**Suggested labels**
- Migration
- Migration doc.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
