### ISSUE TITLE
Doc Feedback: Document claim-uri is wrong

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#11355]
Location : https://is.docs.wso2.com/en/latest/learn/configuring-active-directory-user-stores-for-scim-1.1-based-inbound-provisioning/

The document says to update http://wso2.org/claim uri. But it should be changed to scim1.1 uri.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
