### ISSUE TITLE
Issues in Self Registration form

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-is#11357]
**Describe the issue:**
We came across the following issues while trying out the Self Registration form in API Manager.
- Email validation does not happen properly in the form. Email addresses with the format `someone@wso2` are recognised as valid emails even though `.com` part is missing. Even the regexp set in the management console for email claims doesn't seem to affect the validation in the form.

![Screenshot from 2021-02-24 11-50-52](https://user-images.githubusercontent.com/25485273/108991357-01250800-76be-11eb-950d-ed5dbef2dd28.png)

- The `Sign In` link in the form always redirect to `/myaccount`. There seems to be no configurations to change this URL and point to a different location in our product.

**Environment information:**
 - Product Version: APIM-3xx, APIM-4.0.0, IS versions parellel to those APIM versions
 - OS: Ubuntu 20.04 LTS
---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
