### ISSUE TITLE
Required a method for return user from unique userId to common.model.User

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11369]
**Is your suggestion related to an experience ? Please describe.**

There is a method in the  org.wso2.carbon.identity.application.common.model.User.class to  retrieve the user object from the username.  And it's not use in the implementation. 
However, it is better if there is a way to get the user from the unique user ID.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
