### ISSUE TITLE
OpenID Connect Discovery endpoint

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11364]
The endpoint URL at the very top of the document is invalid. 
```
https://localhost:9443/.well-known/oidcdiscovery
```

Also need to update the part states about `In future releases....`. Because we have done many releases so far and this should have done already.

[1] https://is.docs.wso2.com/en/latest/learn/openid-connect-discovery/

**Comment by rksk** [comment]
A few more issues were observed in this doc.

The config block for `oidc_discovery_url` has an invalid character at the end.

Extra backward slash: `\<Host>`

URLs mentioned in the CURs under the topic "Obtaining the OpenID Provider Issuer location" are also incorrect.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
