### ISSUE TITLE
Stale code related to checking existence of IDP_ID column

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11365]
**Is your suggestion related to an experience ? Please describe.**
Similar to the one explained in https://github.com/wso2/product-is/issues/8484, there is a lot of stale code to check `IDP_ID` column in the following tables and perform operations according to that.
- IDN_OAUTH2_ACCESS_TOKEN
- IDN_OAUTH2_AUTHORIZATION_CODE
- IDN_OAUTH2_ACCESS_TOKEN_AUDIT

Now since all the latest versions have this column the code and its usages seemed to be stale and could be cleaned up.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
