### ISSUE TITLE
Avoid enabling artifact synchronization for repository/deployment

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11367]
**Is your suggestion related to a missing or misleading document? Please describe.**
In some of the documents like [1], we have asked to enable artifact synchronization for the following two directories.
- <IS_HOME>/repository/deployment
- <IS_HOME>/repository/tenants

But it is not required to share the whole deployment directory since WSO2 IS is only having secondary user stores which required to be synced among nodes.  This could cause performance issues and lots of I/O usage due to webapps deployment. So, instead of the `<IS_HOME>/repository/deployment`, we need to share the `<IS_HOME>/repository/deployment/server/userstores` directory.

Summary; enable artifact synchronization for the following directories.
- <IS_HOME>/repository/deployment/server/userstores (if secondary userstores are used)
- <IS_HOME>/repository/tenants (if multi-tenany is used)

https://docs.wso2.com/display/IS570/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Enablingartifactsynchronization

**Comment by rksk** [comment]
Pending: Need to fix old docs space for previous versions.

**Comment by sherenewso2** [comment]
Fixed via for versions 5.9.0 - 5.12.0 

https://github.com/wso2/docs-is/pull/2450
https://github.com/wso2/docs-is/pull/2451
https://github.com/wso2/docs-is/pull/2452
https://github.com/wso2/docs-is/pull/2444

**Comment by rksk** [comment]
Pending: https://github.com/wso2/product-is/issues/11367#issuecomment-787511627

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
