### ISSUE TITLE
openid connect idtoken iss mismatch problem

### ISSUE THREAD

**Issue by gaord** [wso2/product-is#1136]
With WSO IS 5.3.0, reproducing steps as below:

1, create service provider with "Inbound Authentication Configuration"/"OAuth/OpenID Connect Configuration" to configure and have password granttype enabled.
2, in /opt/wso2/repository/conf/identity/identity.xml having this in OpenIDConnect element:
`<IDTokenIssuerID>${carbon.protocol}://${carbon.host}:${carbon.management.port}/oauth2/oidcdiscovery/</IDTokenIssuerID>` 
3, get idtoken by running:
`curl -H "Authorization: Basic X0FvMEozN2cxMlkzSEtiaU1tbWVYdHVvM2FFYTpCeVBZQUprQnZLWlNmOURHeDF0S2xvUTdKcGdh" -H "Content-Type: application/x-www-form-urlencoded" -k -d "grant_type=password&username=admin&password=admin&scope=openid" https://localhost:9443/oauth2/token`
4, returned idtoken is partially something as below decoded:
`{"exp":1487335376,"sub":"admin","azp":"Dibo_uMHzySCIxrf55uvMGWjGEUa","at_hash":"_8q5TmtJRsdEj4V_dL4-Zg","aud":["Dibo_uMHzySCIxrf55uvMGWjGEUa"],"iss":"https:\/\/localhost:9443\/oauth2\/token","iat":1487331776,"acr":"urn:mace:incommon:iap:silver"} `

By openid connect spec, iss should be https://localhost:9443/oauth2/oidcdiscovery/. The mismatch will make validation of idtoken fail.

**Comment by mefarazath** [comment]
@gaord the spec doesn't say it has to be the discovery endpoint. It just needs to be some identifier confirming to http://openid.net/specs/openid-connect-core-1_0.html#IDToken
