### ISSUE TITLE
Sample request in LiteUser Registration needs to be changed

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11373]
**Is your suggestion related to a missing or misleading document? Please describe.**
The lite user registration doc https://is.docs.wso2.com/en/latest/learn/lite-user-registration/ has below sample request.
 When we follow that request, it is not working. We need to modify **preferedChannel** to **preferredChannel**

```
curl -X POST -H "Authorization: Basic [Base64encode(Username>:<Password>)]=" -H "Content-Type: application/json" -d '{"email
": "<regsiter_email>","realm": "PRIMARY","preferedChannel":"Email","claims":[], "properties": []}' "https://localhost:9443/api/identity/user/v1.0/lite"
```

**The modified sample request body:**
```
{
    "email": "test@gmail.com",
    "realm": "PRIMARY",
    "preferredChannel": "Email",
    "claims": [],
    "properties": []
}
```

**Comment by inthirakumaaran** [comment]
I tried the suggested curl but it didn't work as well but successfully able to create the use by setting the email in the claim, example curl 
```
curl --location 'https://localhost:9443/api/identity/user/v1.0/lite' \
--header 'Authorization: Bearer <access token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "test@gmail.com",
    "realm": "PRIMARY",
    "claims": [
       {"uri": "http://wso2.org/claims/emailaddress","value": "test@gmail.com"}
    ],
    "properties": []
}'
```

**Comment by Shenali-SJ** [comment]
This issue was addressed in the PR [1].

[1] - https://github.com/wso2/docs-is/pull/3913

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
