### ISSUE TITLE
Sample request in 'Enable Email Account Verification for an Updated Email Address' doc need to be changed

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11370]
**Is your suggestion related to a missing or misleading document? Please describe.**
The sample scim2 request provided in this doc https://is.docs.wso2.com/en/5.11.0/develop/enable-email-account-verification-for-an-updated-email-address/ needs to be updated

In the doc it says,
`Sending the email verification email is skipped when updating the email address as long as the verifyEmail claim is not set to true.`

But the sample request does not contain verifyEmail claim. Running the below request will not work
```
curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
"Operations":[{"op":"replace","value":{"emails":[{"primary":true,"value":"kim.jackson.new@gmail.com"}]}}]}' 
--header "Content-Type:application/json" https://localhost:9443/scim2/Users/1e624046-520c-4628-a245-091e04b03f21
```

Need to update the above request to send verifyEmail claim as well.

**Sample request**
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "value": {
                "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                    "verifyEmail": "true"
                },
                    "emails": [
                    {
                        "primary": true,
                        "value": "testuser@gmail.com"
                    }
                ]
            }
        }
    ]
}

```

**Comment by isuruirj** [comment]
Under step2 in the same document it says, to enable this feature, navigate to Main > Identity Providers > Resident > Other Settings > User Claim Update.

This path should be corrected as Main > Identity Providers > Resident > Other Settings > User Claim Update

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
