### ISSUE TITLE
'ON DELETE CASCADE' can be added in several places of consent db script

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#11376]
**Describe the issue:**
Below options can be added in the foereign key references in below tables, unless there is some specific reason not to.

```
CM_RECEIPT_SP_ASSOC
CM_SP_PURPOSE_ASSOC
CM_SP_PURPOSE_PURPOSE_CAT_ASSC
CM_SP_PURPOSE_PII_CAT_ASSOC
CM_CONSENT_RECEIPT_PROPERTY

```
@IsuraD @omindu Please add if there are further rationale behind this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
