### ISSUE TITLE
Link provided in file customizing-login-pages-for-service-providers.md gives forbidden

### ISSUE THREAD

**Issue by jairo-fernandez** [wso2/product-is#11371]
**Is your suggestion related to a missing or misleading document? Please describe.**

There is a link provided in file [customizing-login-pages-for-service-providers.md](https://github.com/wso2/docs-is/blob/master/en/docs/develop/customizing-login-pages-for-service-providers.md) which should be pointing to someplace containing the file travelocity_login.jsp  but the link points to an svn repository that has restricted access to the public.
The link is the section **Using a JSP to redirect to SP relevant pages**, step 3.

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
