### ISSUE TITLE
TimestampSkew is not correctly handled in token generation flow

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11378]
**Describe the issue:**
Currently, the following happens if we have configured a positive value for TimestampSkew.

- Let's assume token validity is Tv and timestamp skew is Ts.
- First token issue issued with Tv
- Second time, the same token is issued with [Tv+Ts-time_elapsed] as the validity period.
- So, we issue a new token after Tv+Ts
- For token validation, we allow Tv+Ts amount of time

Before the fix done at https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/331, this was done in the other way, Ts was reduced from Tv for all cases.

**Expected behavior:**
- The token generation flow should not consider Ts at all.
- A new token should be issued after Tv.
- The token validation flow should consider Ts as well and mark the token as valid until Tv+Ts.

Because our ultimate goal should be having a tolerance on the token validity to avoid issuing tokens with 1s validity and failing them at the API invocation.

**Environment information** 
 - Product Version: IS 5.4.0 or later
 
 **Related issues**
 https://github.com/wso2/product-apim/issues/4912

**Comment by rksk** [comment]
We need to document this properly once this is fixed. Because current documentation about TimestampSkew in APIM does not make sense.

```
take the time stamp skew into account when configuring the expiration time. The timestamp skew is used to manage small time gaps in the system clocks of different servers. For example, let's say you have two Key Managers and you generate a token from the first one and authenticate with the other. If the second server's clock runs 300 seconds ahead, you can configure a 300s time stamp skew in the first server. When the first Key Manager generates a token (e.g., with the default life span, which is 3600 seconds), the time stamp skew is deducted from the token's life span. The new life span is 3300 seconds and the first server calls the second server after 3200 seconds.
```

https://apim.docs.wso2.com/en/latest/3.2.0/api-security/oauth2/token-expiration/

**Comment by nilasini** [comment]
@mevan-karu can we close this issue?
