### ISSUE TITLE
Extended class for CustomUserStoreManager and overridden methods needs to be changed

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11375]
The extended user store manager class and overridden methods in document [1][2] are as below and it's wrong.
`public class CustomUserStoreManager extends JDBCUserStoreManager { . . .`

`@Override
    public boolean doAuthenticate(String userName, Object credential)....`

IS 5.10.0 onwards, there're a new set of user store manager implementations. So, when writing a custom user store manager to change the default implementation it's required to extend one of those; listed below.

- UniqueIDJDBCUserStoreManager
- UniqueIDReadOnlyLDAPUserStoreManager
- UniqueIDReadWriteLDAPUserStoreManager
- UniqueIDActiveDirectoryUserStoreManager

`public class CustomJDBCUserStoreManager extends UniqueIDJDBCUserStoreManager {
.
.
.`

[1] - https://is.docs.wso2.com/en/5.10.0/setup/writing-a-custom-user-store-manager/#writing-a-custom-user-store-manager
[2] - https://is.docs.wso2.com/en/latest/setup/writing-a-custom-user-store-manager/#writing-a-custom-user-store-manager
[3] - https://medium.com/identity-beyond-borders/new-user-store-mangers-of-wso2-is-f5247abe3a80

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
