### ISSUE TITLE
reCaptcha doesn't work for authorization request without openid scope

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11372]
**Describe the issue:**
The reCaptcha for failed login attempt [1] doesn't work when the authorization request comes as below, (It won't prompt for the reCaptcha after the configured number of failed login attempts),
```https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=http://localhost&client_id=YRiNIKoR6qUNI2bZvp5lsafrNysa```
It works for the authorization request below.
```https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=http://localhost&client_id=YRiNIKoR6qUNI2bZvp5lsafrNysa&scope=openid```
This happens since, there is a logic in the authentication endpoint below, which treats the authorization request coming without openid scope differently when submitting the credentials.
```
String type = request.getParameter("type");
if ("samlsso".equals(type)) {
    loginFormActionURL = samlssoURL;
} else if ("oauth2".equals(type)){
    loginFormActionURL = oauth2AuthorizeURL;
} else {
    loginFormActionURL = commonauthURL;
}
```
Therefore, the password will be submitted to /oauth2/authorize instead of commonauth as per the above logic when the authorization request is made without the openid scope. However, the [CaptchaFilter](https://github.com/wso2-extensions/identity-governance/blob/v1.4.1/components/org.wso2.carbon.identity.captcha/src/main/java/org/wso2/carbon/identity/captcha/filter/CaptchaFilter.java#L60) is not getting involved when a request is made to /oauth2/authorize, though the endpoint is mapped to the said filter in web.xml (tomcat/carbon/WEB-INF).

Therefore, the oauth2/authorize endpoint should be included for the CaptchaFilter in oauth2 webapp and should be declared as [`SECURED_DESTINATIONS`](https://github.com/wso2-extensions/identity-governance/blob/v1.4.1/components/org.wso2.carbon.identity.captcha/src/main/java/org/wso2/carbon/identity/captcha/connector/recaptcha/SSOLoginReCaptchaConfig.java#L62) in order to handle this scenario.

**Related issues:**
#7457

[1] https://is.docs.wso2.com/en/5.10.0/learn/configuring-recaptcha-for-single-sign-on

**Comment by nipunthilakshan** [comment]
I'm working on this
