### ISSUE TITLE
"Action=Add-Role" not printed in audit logs for Internal roles 

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11388]
**Is your suggestion related to an experience ? Please describe.**

For Primary roles below log line is printed in the audit log file in role creation but it's not printed for the Internal roles.
`TID: [-1234] [2021-03-04 16:46:18,310] [fb94f9b1-b5bb-4a65-a8c5-e61a85df9922]  WARN {AUDIT_LOG} - Initiator=admin@carbon.super Action=Add-Role Target=manager Data={} Outcome=Success`

**Describe the improvement**

"Action=Add-Role" should be printed for Internal roles as well.

**Additional context**

Below implementation is already there in the UserManagementAuditLogger [1] to Primary roles.
<pre style="color:#000000;background:#ffffff;">    <span style="color:#808030; ">@</span>Override
    public boolean doPostAddRole<span style="color:#808030; ">(</span><span style="color:#603000; ">String</span> roleName<span style="color:#808030; ">,</span> <span style="color:#603000; ">String</span><span style="color:#808030; ">[</span><span style="color:#808030; ">]</span> userList<span style="color:#808030; ">,</span> Permission<span style="color:#808030; ">[</span><span style="color:#808030; ">]</span> permissions<span style="color:#808030; ">,</span>
            UserStoreManager userStoreManager<span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>

        <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>isEnable<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>
            JSONObject dataObject <span style="color:#808030; ">=</span> new JSONObject<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>ArrayUtils<span style="color:#808030; ">.</span>isNotEmpty<span style="color:#808030; ">(</span>userList<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>
                dataObject<span style="color:#808030; ">.</span>put<span style="color:#808030; ">(</span>ListenerUtils<span style="color:#808030; ">.</span>USERS_FIELD<span style="color:#808030; ">,</span> new JSONArray<span style="color:#808030; ">(</span>userList<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>
            <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>ArrayUtils<span style="color:#808030; ">.</span>isNotEmpty<span style="color:#808030; ">(</span>permissions<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>
                JSONArray permissionsArray <span style="color:#808030; ">=</span> new JSONArray<span style="color:#808030; ">(</span>permissions<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                dataObject<span style="color:#808030; ">.</span>put<span style="color:#808030; ">(</span>ListenerUtils<span style="color:#808030; ">.</span>PERMISSIONS_FIELD<span style="color:#808030; ">,</span> permissionsArray<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>
            audit<span style="color:#808030; ">.</span>warn<span style="color:#808030; ">(</span>createAuditMessage<span style="color:#808030; ">(</span>ListenerUtils<span style="color:#808030; ">.</span>ADD_ROLE_ACTION<span style="color:#808030; ">,</span>
                    ListenerUtils<span style="color:#808030; ">.</span>getEntityWithUserStoreDomain<span style="color:#808030; ">(</span>roleName<span style="color:#808030; ">,</span> userStoreManager<span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> dataObject<span style="color:#808030; ">,</span> SUCCESS<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
        <span style="color:#800080; ">}</span>
        <span style="color:#800000; font-weight:bold; ">return</span> true<span style="color:#800080; ">;</span>
    <span style="color:#800080; ">}</span>
</pre>

Needs to add below code clock in the same class to handle the Internal Roles.

<pre style="color:#000000;background:#ffffff;">    <span style="color:#808030; ">@</span>Override
    public boolean doPostAddInternalRoleWithID<span style="color:#808030; ">(</span><span style="color:#603000; ">String</span> roleName<span style="color:#808030; ">,</span> <span style="color:#603000; ">String</span><span style="color:#808030; ">[</span><span style="color:#808030; ">]</span> userIDs<span style="color:#808030; ">,</span> Permission<span style="color:#808030; ">[</span><span style="color:#808030; ">]</span> permissions<span style="color:#808030; ">,</span>
                                               UserStoreManager userStoreManager<span style="color:#808030; ">)</span><span style="color:#800080; ">{</span>

        <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>isEnable<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>
            JSONObject dataObject <span style="color:#808030; ">=</span> new JSONObject<span style="color:#808030; ">(</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>ArrayUtils<span style="color:#808030; ">.</span>isNotEmpty<span style="color:#808030; ">(</span>userIDs<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>
                dataObject<span style="color:#808030; ">.</span>put<span style="color:#808030; ">(</span>ListenerUtils<span style="color:#808030; ">.</span>USERS_FIELD<span style="color:#808030; ">,</span> new JSONArray<span style="color:#808030; ">(</span>userIDs<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>
            <span style="color:#800000; font-weight:bold; ">if</span> <span style="color:#808030; ">(</span>ArrayUtils<span style="color:#808030; ">.</span>isNotEmpty<span style="color:#808030; ">(</span>permissions<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> <span style="color:#800080; ">{</span>
                JSONArray permissionsArray <span style="color:#808030; ">=</span> new JSONArray<span style="color:#808030; ">(</span>permissions<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
                dataObject<span style="color:#808030; ">.</span>put<span style="color:#808030; ">(</span>ListenerUtils<span style="color:#808030; ">.</span>PERMISSIONS_FIELD<span style="color:#808030; ">,</span> permissionsArray<span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
            <span style="color:#800080; ">}</span>
            audit<span style="color:#808030; ">.</span>warn<span style="color:#808030; ">(</span>createAuditMessage<span style="color:#808030; ">(</span>ListenerUtils<span style="color:#808030; ">.</span>ADD_ROLE_ACTION<span style="color:#808030; ">,</span>
                    ListenerUtils<span style="color:#808030; ">.</span>getEntityWithUserStoreDomain<span style="color:#808030; ">(</span>roleName<span style="color:#808030; ">,</span> userStoreManager<span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> dataObject<span style="color:#808030; ">,</span> SUCCESS<span style="color:#808030; ">)</span><span style="color:#808030; ">)</span><span style="color:#800080; ">;</span>
        <span style="color:#800080; ">}</span>
        <span style="color:#800000; font-weight:bold; ">return</span> true<span style="color:#800080; ">;</span>
    <span style="color:#800080; ">}</span>
</pre>

It's required to implement the same in the failure scenario as well.

**Environment information** **:**
 - Product Version: [ IS 5.10.0]

[1] - https://github.com/wso2/carbon-identity-framework/blob/v5.7.5/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserManagementAuditLogger.java#L195

**Comment by rksk** [comment]
All the methods in UserManagementAuditLogger are referring to the old events (without ID), so I believe we need to keep the same style for the newly added one as well.
