### ISSUE TITLE
Incorrect configuration in doc https://is.docs.wso2.com/en/latest/setup/customizing-secure-vault/

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#11385]
Please fix the configuration here [1]. It is not working.

Currently, this must be configured in the secret-conf.properties, not in the deployment.toml

[1] https://is.docs.wso2.com/en/latest/setup/customizing-secure-vault/#step-1-creating-a-secret-callback-handler

**Comment by pandukakarunasena** [comment]
Any update on this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
