### ISSUE TITLE
Check and verify skip password policy validation in ask password enabled flow in identity-user-workflow 

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11383]
## Describe the issue:
This issue is related with this pull request: https://github.com/wso2-support/identity-governance/pull/318
According to the above PR the password policy validation will be skipped for ask-password enabled user registration.  
This was implemented on the identity-governance PasswordPolicyValidationHandler.

But need to make sure that whether it required on identity-user-workflow - UserStoreActionListener. 

## Product version
WSO2IS-5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
