### ISSUE TITLE
User 1 logged into application (Service Provider A) and was logged in as User 2...

### ISSUE THREAD

**Issue by tahir-khalid** [wso2/product-is#11395]
**Describe the issue:**
Hi as per the title we are currently using WSO2-IS version 5.3.0 (upgrade scheduled in near future) and we have some Service Providers configured with the SAML SSO part setup and Claims.  They all authenticate with AD via LDAP and for the most part everything looks fine however yesterday two users reported strange behaviour whereby User 1 logged into their application and they noticed they were logged in as User 2 - and user 2 logged in and noticed they were logged in as User 1!

I am not entirely sure how this is possible and what could have gone wrong but has this occurred before?

**How to reproduce:**
Difficult to reproduce locally however User 1 logged into App A (WordPress) and when they authenticated they were redirected to a Portal application (the .NET Core application that I am supporting which handles login for example, uses an SAML2 library called Sustainsys.Saml2 which is used in an WSO2 Library project to handle things like SAML SSO login.

User 1 reported that they saw not one but two users details i.e. their apps and profile information.

**Expected behavior:**
User authenticates against AD via WSO2 IS (Key Manager) and is logged into their respective application and only able to see their profile and their apps,

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.3.0
 - OS: Windows 2016 Server
 - Database: MSSQL Server
 - Userstore: LDAP AD (Windows 2016)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
