### ISSUE TITLE
DeleteMe scim2 endpoint permission needs to be changed.

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11396]
**Describe the issue:**

**How to reproduce:**

1. Create a user with internal/everyonne role (User should not have any permissions)
2. Try scim2Delete me operation.

`curl -v -k --user  [username]:[password] -X DELETE https://localhost:9443/scim2/Me`

We will observe 403 response. In the default.json, the default permission is configured as   `"resource_access_control.scim2_me_delete_method.permission": "/permission/admin/manage/identity/usermgt/delete",
`
Due to this, the user without any permission cannot delete himself.

**Workaround:**
Need to add below config in deployment.toml file
```
[resource_access_control.scim2_me_delete_method]
permission="none"
```

Since it deleteMe endpoint is supported for all users, permission `none` should be set as default permission in default.json.

Tested version: IS5.12.0-m11

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
