### ISSUE TITLE
Missing claims in id-token returned for the refresh grant

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11390]
**Describe the issue:**
Even though we have not added request claims, the claims of the selected Service Provider Claim Dialect are returned in the id-token. But if we invoke the refresh grant after the AuthorizationGrantCache for the previous token is expired, it does not return user claims.

During the authentication flow, we handle the requested claims at [1]. There we return the claims of the SP claim dialect even without any claims added to the requested claims. But during the id-token generation flow, if the AuthorizationGrantCache is not found, it just checks for `serviceProvider.getClaimConfig().getClaimMappings();`.

**How to reproduce:**
- Disable data persistence (this is to increase the chance of reproducing)
```
[session_data.persistence]
enable_persistence=false
```
- Create a service provider
- Don't add requested claims, but set "Service Provider Claim Dialect" as "http://wso2.org/oidc/claim"
- Set token expiry to 60s and refresh token expiry to 300
- Use jwt token generator
- Get an access token with openid scope using code grant (you will get all the claims in openid dialect)
- Now wait for the token to expire (say 100s) and invoke refresh grant with the previous refresh token
- The new id-token or access-token does not contain any user claims
- Following debug logs can be seen
```
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - Retrieving claims cached against access_token for user: admin@carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - No claims cached against the access_token for user: admin@carbon.super. Retrieving claims cached against the authorization code.
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - Retrieving claims cached against authorization_code for user: admin@carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - No claims found in authorization cache. Retrieving claims from attributes of user : admin@carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - No claims found in user in user attributes for user : admin@carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - Retrieving claims from previous access token of user : admin@carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - Retrieving user attributes cached against access token.
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - hasNonOIDCClaims is set to false for the access token of the user : admin@carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - User attributes not found in cache against the access token or authorization code. Retrieving claims for local user: admin@carbon.super from userstore.
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - Retrieving service provider for clientId: xxxxxxxxxx in tenantDomain: carbon.super
DEBUG {org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler} - No requested claims configured for service provider: sp1 of tenantDomain: carbon.super. No claims returned for user: admin@carbon.super
```

**Expected behavior:**
Even though we have not added request claims, the claims of the selected Service Provider Claim Dialect should return for the code grant as well as the refresh grant even after the cache expiry

**Environment information** 
 - Product Version: IS 5.10.0
 
 [1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java#L94-L99

**Comment by sachiniWettasinghe** [comment]
`Service Provider Claim Dialect` was introduced for the purpose of supporting eIDAS SAML Attribute Profile for IS [1]. In order to get specific claims in the id-token it is recommended to configure those claims as `requested claims`. 

However, the above issue is also not getting reproduced in the latest WUM updated IS 5.10.0 pack when following the above steps. And this behaviour was not seen when trying out the above flow using requested claims (instead of Service Provider Claim Dialect in step 3). Hence this issue will be closed. 

[1] https://is.docs.wso2.com/en/5.10.0/learn/eidas-saml-attribute-profile-support-via-wso2-identity-server/
