### ISSUE TITLE
Improve the default token generator

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#11405]
**Is your suggestion related to an experience ? Please describe.**
Access tokens, Authorization codes, and Refresh tokens in the fresh IS pack is generated via the Default Token Generator which is `org.apache.oltu.oauth2.as.issuer.UUIDValueGenerator`.

The above generator creates UUID-based opaque tokens. However, the strength of these opaque tokens can further be improved. For example, `OAuth2Util.generateRandomNumber()` method has much stronger token generation capability which is already used to generate client secrets.

**Describe the improvement**
Write a stronger token generator and replace the existing UUID-based generator. The same logic used to generate client secrets can be applied to this new token generator.

**Tasks**

- [ ] Write the new token generator and plug it in as the default token generator.
- [ ] Conduct a performance test and see the impact.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
