### ISSUE TITLE
SSO for Native iOS sample application is not working properly.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#11409]
**Describe the issue:**
The flow described in [1] was tested against the following simulators.
- iPhone 11 Pro Max with iOS 13.3
- iPhone 7 with iOS 10.3.1 

### Behaviour with iPhone 11 Pro Max with iOS 13.3
Sign-in fails as given below.
<img width="407" alt="Screenshot 2021-03-09 at 08 53 00" src="https://user-images.githubusercontent.com/24982871/110421225-112be700-80c3-11eb-854f-9d0cf1a52b1f.png">

### Behaviour with iPhone 7 with iOS 10.3.1
Sign-in is successful.
However, the logout fails. Screenshots of the logout flow are provided below.

<img width="374" alt="Screenshot 2021-03-09 at 08 45 16" src="https://user-images.githubusercontent.com/24982871/110421361-61a34480-80c3-11eb-8842-f9376a8dbbc7.png">

<img width="372" alt="Screenshot 2021-03-09 at 08 45 32" src="https://user-images.githubusercontent.com/24982871/110421373-67008f00-80c3-11eb-9e30-768952f1cc49.png">

<img width="374" alt="Screenshot 2021-03-09 at 08 46 37" src="https://user-images.githubusercontent.com/24982871/110422118-beebc580-80c4-11eb-919e-4c1a9414e873.png">

Similar behavior has been described at [2].

Also in [1], it is mentioned 

> The sample client application uses the dev-logout development branch of the AppAuth for iOS library due to several logout functionality issues in the main branch

As stated in [3] the implementation has been merged to master. Therefore the sample app should be changed and tested to import the standard AppAuth library from the main branch.

**Environment information:**
 - Product Version: wso2is-5.12.0-m11

**Additional Information:**
- [4] contains more information on the logout function of AppAuth library.
- To import a self-signed certificate to the iOS simulator, [5] was followed.

[1] https://is.docs.wso2.com/en/latest/learn/single-sign-on-for-native-ios-applications-with-wso2-identity-server/
[2] https://github.com/openid/AppAuth-iOS/issues/255#issuecomment-413815013
[3] https://github.com/openid/AppAuth-iOS/pull/259#issuecomment-500641074
[4] https://medium.com/@dileesha/add-single-sign-on-sso-to-your-ios-application-with-wso2-identity-server-in-easy-steps-cbbb6ef8d08
[5] https://stackoverflow.com/a/46121018/7842949

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
