### ISSUE TITLE
Authentication flow fails when logging into SimpleSAMLphp while response signing is enabled

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#11401]
**Describe the issue:**
I used the following tutorial to log into SimpleSAMLphp using identity server
[https://is.docs.wso2.com/en/latest/learn/logging-in-to-simplesamlphp-using-identity-server/](url)

Identity server returns an error when testing configured authentication source "wso2-sp" from SimpleSAMLphp
![image](https://user-images.githubusercontent.com/36619815/110297668-c30ed900-8019-11eb-971c-c0c13256d275.png)

```[http://localhost/simplesaml/module.php/core/authenticate.php?as]  WARN {org.wso2.carbon.identity.sso.saml.validators.SPInitSSOAuthnRequestValidator} - Signature validation for Authentication Request failed for the request of Issuer :simplesaml in tenantDomain:carbon.super```

Authentication works successfully after you disable signature validation in authentication requests for the registered simpleSAML service provider

**How to reproduce:**
1. Follow above mentioned tutorial to setup and configure SimpleSAMLphp and identity server
2. Go to http://localhost/simplesaml and pick Authentication -> Test configured authentication sources -> wso2
3. IS will redirect you to the error page

**Expected behavior:**
Authentication should succeed after enabling signature validation in authentication requests and making the configurations as mentioned in the tutorial

**Environment information:**
 - Product Version:IS 5.12.0-m11
 - OS: Linux

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
