### ISSUE TITLE
Empty page when accessing myaccount page 

### ISSUE THREAD

**Issue by MbonoV** [wso2/product-is#11417]
**Description:** When I try to access myaccount page on Firefox, Chrome and Edge, after entering username and password the page just go blank.

**Suggested Labels:** myaccount

**Affected Product Version:** 5.11.0

**Related Issues:**

![image](https://user-images.githubusercontent.com/35092405/110600576-c080c080-818c-11eb-8309-fa4ca78a47b5.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
