### ISSUE TITLE
Documentation needed for internationalization and localization support in 'My Account' portal

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#11415]
**Is your suggestion related to a missing or misleading document? Please describe.**
No documentation is available on how to internationalize or localize the 'My Account' portal

**Describe the improvement**
Documentation needed for internationalization and localization support in 'My Account' portal

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
