### ISSUE TITLE
Permission API implementation for group resource schema

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11427]
The fix done in https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/199 is available since 5.9.0. But not documented.  In 5.11.0, it seems to be changed. But still no clear swagger doc on permission management.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
