### ISSUE TITLE
Consent Management link doesn't work

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#11426]
**Is your suggestion related to a missing or misleading document? Please describe.**

Consent Management link doesn't work in [Consent Management with Single-Sign-On](https://is.docs.wso2.com/en/latest/learn/consent-management-with-single-sign-on/#consent-management-with-single-sign-on) Page.
![Screenshot_2021-03-12 Consent Management with Single-Sign-On - WSO2 Identity Server Documentation](https://user-images.githubusercontent.com/45028707/110893751-965e0880-831c-11eb-858b-0ca3da5f226d.png)

Once this link is clicked, the user is directed to `https://is.docs.wso2.com/en/latest/learn/user-portal/#consent-management` this page which doesn't exist.
![Screenshot_2021-03-12 WSO2 Identity Server Documentation](https://user-images.githubusercontent.com/45028707/110893762-9a8a2600-831c-11eb-852c-8f4b2b6a1fa9.png)

Docs version - 5.11.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
