### ISSUE TITLE
Group name update is disabled in the console

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#11421]
**Describe the issue:**
Group name update is disabled in the console(https://localhost:9443/console) as shown below.

Steps to reproduce
1. Log into the console
2. Add group and try to update the group name
3. Group name update button is disabled as shown below

![Screenshot from 2021-03-11 11-28-22](https://user-images.githubusercontent.com/25496816/110747521-84209380-8264-11eb-9cea-1ae03b778541.png)

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/12981
