### ISSUE TITLE
Two different flows for Authorization Request

### ISSUE THREAD

**Issue by nipunthilakshan** [wso2/product-is#11429]
**Describe the issue:**

When the authorization request comes as [1] request will follow the **authorize endpoint** and when it comes as [2] it will follow the **commonauth endpoint**. This happens since, there is a logic in the authentication endpoint [3], which treats the authorization request coming without oidc scope differently when submitting the credentials.

[1] https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=http://localhost&client_id=tXDWrT9k0GuF1ioaGl4tIGj_srIa

[2] https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=http://localhost&client_id=tXDWrT9k0GuF1ioaGl4tIGj_srIa&scope=openid

[3] https://github.com/wso2/identity-apps/blob/master/apps/authentication-portal/src/main/webapp/includes/init-loginform-action-url.jsp#L31

**How to reproduce:**
1) Create a service provider
2) Configure OAuth/OpenID under Inbound Authentication Configuration
3) Set the redirect url to http://localhost and get the client id
4) Try above 2 requests with that certain client id

Find network trace details : [trace](https://drive.google.com/drive/folders/1Sj1BRfef5DYGWLp52gsCNDn9NNc907AJ?usp=sharing)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0, IS 5.11.0
 - OS: Linux

**Related issues:**
https://github.com/wso2/product-is/issues/11372

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
