### ISSUE TITLE
Multi attribute login - select claim URI from drop-down and validate claim URI 

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11445]
Related with: https://github.com/wso2/product-is/issues/8899
**Is your suggestion related to an experience ? Please describe.**

Multi attribute login feature is now available on IS. Admins can set the list of claim URI  as multi attribute identifiers. There is a text box to add a list of claim URI which are allowed for multi attribute login.

![enable multi attribute login](https://user-images.githubusercontent.com/25544656/111277141-1dcdb380-865e-11eb-9a8f-2ad26e0e81cd.png)
In this case admin users need to add a claim URI as a comma separated list. And also there is no option to validate a claim URI whether it is available or not. So admins can enter any string as caim URI. 

**Describe the improvement**

1. Need a option to select claim URI from available claim list. 
     It's like a drop down menu of available claims in the tenant domain.

2. Need a proper validation for claims which allowed for multi attribute login. 
    need to validate regex pattern/ URI availability/  is already added etc

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
