### ISSUE TITLE
Sample request in 'Enable Mobile Number Verification for an Updated Mobile Number' doc need to be changed

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11441]
The sample scim2 request provided in this doc [1] needs to be updated.

Sending the SMS OTP verification is skipped when updating the mobile number as long as the verifyMobile claim is not set to true. So, it's mandatory to have this claim in the request but the sample request given in the doc [1] does not contain verifyMobile claim

<pre style="color:#000020;background:#f6f8ff;">curl <span style="color:#308080; ">-</span>v <span style="color:#308080; ">-</span>k <span style="color:#308080; ">-</span><span style="color:#308080; ">-</span>user admin<span style="color:#406080; ">:</span>admin <span style="color:#308080; ">-</span>X PATCH <span style="color:#308080; ">-</span>d '<span style="color:#406080; ">{</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">schemas</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#308080; ">[</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">urn:ietf:params:scim:api:messages:2.0:PatchOp</span><span style="color:#800000; ">"</span><span style="color:#308080; ">]</span><span style="color:#308080; ">,</span>
<span style="color:#800000; ">"</span><span style="color:#1060b6; ">Operations</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#308080; ">[</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">{</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">op</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">replace</span><span style="color:#800000; ">"</span><span style="color:#308080; ">,</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">value</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">{</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">urn:ietf:params:scim:schemas:extension:enterprise:2.0:User</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span> <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">{</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">verifyMobile</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span> <span style="color:#800000; ">"</span><span style="color:#1060b6; ">true</span><span style="color:#800000; ">"</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">}</span><span style="color:#308080; ">,</span>
 <span style="color:#800000; ">"</span><span style="color:#1060b6; ">phoneNumbers</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#308080; ">[</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">{</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">type</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">mobile</span><span style="color:#800000; ">"</span><span style="color:#308080; ">,</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">value</span><span style="color:#800000; ">"</span><span style="color:#406080; ">:</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">0112987323</span><span style="color:#800000; ">"</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">}</span><span style="color:#308080; ">]</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">}</span><span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">}</span><span style="color:#308080; ">]</span><span style="color:#406080; ">}</span>' <span style="color:#308080; ">-</span><span style="color:#308080; ">-</span>header <span style="color:#800000; ">"</span><span style="color:#1060b6; ">Content-Type:application/json</span><span style="color:#800000; ">"</span>
<span style="color:#e34adc; ">&nbsp;https:</span><span style="color:#595979; ">//localhost:9443/scim2/Users/acdfa4ee-bbe8-4865-8eab-9704d9783054</span>
</pre>

[1] - https://is.docs.wso2.com/en/5.11.0/develop/enable-verification-for-updated-mobile-number/

**Comment by nilminiwso2** [comment]
Closing this issue as per the above comment.
