### ISSUE TITLE
"MgtHostName" configuration is templated to take the "HostName" configuration

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#11459]
In carbon.xml file we have following configuration.

<MgtHostName>*****</MgtHostName>

This configuration has been templated in carbon.xml.j2 file as below to take the "HostName" by default.

`Host name to be used for the Carbon management console
   
     {%if server.hostname is defined %}
    <MgtHostName>{{server.hostname}}</MgtHostName>
     {% endif %}`

This becomes an issue when using a different hostname for management console. 

Version - WSO2IS-5.10.0

**Comment by nipunthilakshan** [comment]
I will work on this.
