### ISSUE TITLE
Remove the revoke option in the application protocol section.

### ISSUE THREAD

**Issue by ashans** [wso2/product-is#11453]
**Describe the issue:**
$subject until first-class support for application disabling is provided.

Along with that, we need to remove the <LabelWithPopup> component.

**Comment by mefarazath** [comment]
Have we tracked the story to implement the revoke/disable application at application level instead of OAuth protocol level?
If so can we link it here?

**Comment by ChamathNS** [comment]
@mefarazath The issue is tracked in product-is with https://github.com/wso2/product-is/issues/11456.
