### ISSUE TITLE
Improve portals UIs based on tenant level account management configuration preferences for username and password regex

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#11450]
**Describe the issue:**
Contains the remaining task of https://github.com/wso2/product-is/issues/9717

- [ ] Read regex from tenant level config for username & pwd validation for self registration in login portal. 
- [ ] Read regex from tenant level config for username & pwd validation in recovery portal.

**Comment by inthirakumaaran** [comment]
move to https://github.com/wso2-enterprise/asgardeo-product/issues/2705

**Comment by ayshsandu** [comment]
Additional to the tenant preferences, the user store configurations may also need to be considered at these validation points.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
