### ISSUE TITLE
Using + sign in the username

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#11464]
**Describe the issue:**
When using email as username, there can be email addresses as below,
user+123@gmail.com

As + sign is a special character, we need to confirm it does not cause any issues in the flows, specially when registry is involved.

**Expected Behavior**
A user can register with email with + sign and execute the flows without an issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
