### ISSUE TITLE
Skip consent page for 'prompt=consent' while skip login consent is set to true

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#11465]
**Describe the improvement**
Currently even when you set skip login consent to true for a service provider, the consent page is displayed when the authorization request contains 'prompt=consent'. 

Suggested to not display the consent page even if 'prompt=consent' is included in the request while skip login consent is set to true.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
