### ISSUE TITLE
[Migration][Migration-Doc] Application role will not be created and not validated in the latest product

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#11475]
The fix https://github.com/wso2/carbon-identity-framework/pull/3406 related to the issue https://github.com/wso2/product-is/issues/11337, removed the creation of application roles and validation availability of application roles in application management flows OOTB.

In previous IS versions, this was not possible. To remove this behavior the following config needs to be added to the toml.

```
[application_mgt]
enable_role_validation=true
```
By default, this value is set to `false`.

Disabling the role validation (setting the value to false) will provide the following behavior.
- Ignore validating the application role for the user who initiates application management flows.
- Application roles will not be created for newly created SPs and the application role will not be assigned to the app owner.
Ignore validating the application role for existing SPs.

When changing the configuration value from false to true, make sure to create application roles for the SPs who were created during the configuration false period and assign them to the application owners.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
