### ISSUE TITLE
Unable to add federated authenticators configured via management console, into service providers created in console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11472]
**Describe the issue:**
Google authenticator configured via the management console, can't be added into an authentication step of a SP created in the console.

**How to reproduce:**

- configure google authenticator via management console. https://is.docs.wso2.com/en/latest/learn/configuring-google/
- Create an SP via console.
- Go to `sign-on method` tab of the SP and try to drag and drop the google authenticator.
- The following error will be displayed and you can't drag and drop that authentiator.
![imageedit_2_6375037823](https://user-images.githubusercontent.com/25483865/111949336-85747a80-8b06-11eb-8dd8-74472ee8c01e.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.12.0-m13
 - OS:  Linux
 - Database: H2
 - Userstore: LDAP

**Comment by sumedhe** [comment]
The response of the IDPs created from Management Console contains the values of all the authenticators. But in carbon it expects for a one configured authenticator and checks only the first authenticator from the list.

As the fix, the improvement which make un-droppable the disabled authenticators will be removed from the identity apps and moved to the identity app extentions.

![image](https://user-images.githubusercontent.com/2020370/112985413-c65f3580-917d-11eb-9b04-461fc5eeb39d.png)

**Comment by nilasini** [comment]
Couldn't reproduce the issue with IS-5.12.0-alpha18
