### ISSUE TITLE
Improve content in application creation wizard.

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#11482]
**Describe the issue:**

The Authorized Redirect URLs description in the help panel is too lengthy.

![Screenshot(62)](https://user-images.githubusercontent.com/25428696/112102902-faab8280-8bce-11eb-8e74-6fa25b253a70.png)

**Comment by ShanikaWickramasinghe** [comment]
verified on stage with sprint 4 build and this is fixed
