### ISSUE TITLE
Registers an OAuth2 application for DCR endpoint fail with the 'token_endpoint_auth_method' optional parameter

### ISSUE THREAD

**Issue by anusharp** [wso2/product-is#11480]
**Describe the issue:**

The optional parameter "token_endpoint_auth_method" gives 400 Bad request error
**How to reproduce:**

According to the [spec](https://auth0.com/docs/applications/dynamic-client-registration), token_endpoint_auth_method is a optinal parameter for the Registers an OAuth2 application request. But it gives 400 Bad status code with  Unrecognized field 'token_endpoint_auth_method' when the that optional attribute is present in the request body

**Expected behavior:**

Request should be process successfully with the optional parameter as well
**Environment information** **:**
 - Product Version: Tested in IS 5.10.0

**Suggested labels:**
DCR, OAuth2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
