### ISSUE TITLE
Error when registering new application

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#11492]
**Describe the Issue:**

Encountered the following error when registering a new application.

![Screenshot(61)](https://user-images.githubusercontent.com/25428696/111787861-782c7580-88e5-11eb-84bb-1d9cd8abe2bb.png)

![Screenshot_20210319_185850](https://user-images.githubusercontent.com/25428696/111787940-91352680-88e5-11eb-89c3-eab67684504b.png)

It seems that we are sending the previously registered allowed origins as well when we create a new application.
With the new validations introduced for `AllowedOrigins` the older URLs sent in the request causes an error.

**Comment by NilukaSripalim** [comment]
Tested and Verified in Stage, Able to Register an application without an error
