### ISSUE TITLE
Filters with parentheses not working since 3.3.1

### ISSUE THREAD

**Issue by primesaber** [wso2/product-is#11490]
**Description:**
Filters with parentheses not working since 3.3.1. It last worked in 3.3.0.

**Affected Product Version:**
3.3.1 through at least 3.3.10

**OS, DB, other environment details and versions:**    
Tested on MacOS 10.14.6.

**Steps to reproduce:**

For example:

`GET /Users?filter=name.familyName eq "Mort" and (emails co "example.com")`

generated the following error response:

`{ "schemas" : [ "urn:ietf:params:scim:api:messages:2.0:Error" ], "scimType" : "invalidValue", "detail" : "Not a valid attribute name/uri", "status" : "400" }`

During step-by-step debugging, the issue is occurring in FilterTreeManager.java, when the code there is trying to find a matching attribute name for "(emails", instead of the expected "emails".

**Comment by AnuradhaSK** [comment]
Moved to  5.12.0-M15 since this fix is not yet moved to product-is. Need to bump the Charon version in scim component since the Charon is effected to product-is via the scim component

**Comment by RidmiR** [comment]
Verified in staging environmentt and this Issue is fixed.
