### ISSUE TITLE
Permissions/Scopes required for REST APIs with old API docs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11501]
**Is your suggestion related to a missing or misleading document? Please describe.**
All the API docs which are pointing to old swagger docs, do not mention the required permissions/scopes to invoke them.

Eg: https://is.docs.wso2.com/en/latest/develop/using-the-account-recovery-rest-apis/

Currently, the information has to be derived from the `ResourceAccessControl` section of the `identity.xml`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
