### ISSUE TITLE
[Doc] Demo notes 25 March 2021

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#11500]
- [ ] Content change: Download Identity server -> Download
![1](https://user-images.githubusercontent.com/25488962/112428225-dbdcf580-8d60-11eb-9f33-c895925ef9bf.png)

- [ ] Footer not get much attention usually, hence need some idea to get slack, community buttons more attention

- [ ] Content change: Privacy management -> Privacy
![2](https://user-images.githubusercontent.com/25488962/112428344-075fe000-8d61-11eb-922f-8c995ebc3e22.png)

- [ ] Card boxes should be named actionable like Start building with the identity server. Currently, we have API Security -> Securing APIs

![3](https://user-images.githubusercontent.com/25488962/112428410-23638180-8d61-11eb-9ef1-7dfaaf071bba.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
