### ISSUE TITLE
The IDPs created using Google template allows to add other social login authenticators such as facebook, twitter

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#11503]
**Describe the issue:**
The IDPs created using Google template allows to add other social media authenticators such as facebook, twitter. 

**How to reproduce:**
1. Start WSO2 Identity Server
2. Go to console (`https://localhost:9443/console`)
3. Select **Develop -> Identity Provides -> New Identity Provider -> Google**
4. Fill the basic information about the identity provider in each tab and click Finish.
5. Select and open settings of the newly created IDP
6. Select **Authentication -> New Authenticator**
7. Click **Facebook** or **Twitter** or any other social media authenticator
8. Click **Next** and fill the relevant configurations and click **Finish**

**Expected behavior:**
It should not allow to add other social login authenticators if it created using a Google template.

Note:
- Revise the 'Authenticator' term used in Application's sign-on methods page and the Identity Provider's Authenticator page as we are placing IDPs as authenticators in Application settings, and IDPs also contain authenticators.

**Environment information**:
 - Product Version: IS 5.12.0-m13

**Screenshots:**

![image](https://user-images.githubusercontent.com/2020370/112491425-4d8b6280-8da6-11eb-8b9a-c3593df41d35.png)

![image](https://user-images.githubusercontent.com/2020370/112491608-7c093d80-8da6-11eb-9e0a-3a6e54950037.png)

![image](https://user-images.githubusercontent.com/2020370/112487998-3139f680-8da3-11eb-99ea-60b03eb8f73c.png)

**Comment by nilasini** [comment]
Couldn't reproduce with IS-5.12.0-alpha18
