### ISSUE TITLE
Need a document for multi attribute login feature 

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11504]
Resolves: wso2/product-is#8899
Need to add a document for **Multi Attribute Login** feature.

This feature will be available since wso2-is 5.12.

**Comment by rksk** [comment]
This feature is available in both 5.10.0 and 5.11.0 with updates. Hence needs to be documented for those two versions as well. 

Additionally, [1] can be removed now.

[1] https://is.docs.wso2.com/en/latest/learn/managing-user-attributes/#authentication-using-multiple-attributes

**Comment by nilminiwso2** [comment]
@nilasini We can add this to the 5.12 project board yeah?
According to https://github.com/wso2/product-is/issues/8899, this seems to be an issue that is shipped with 5.12.

**Comment by nilasini** [comment]
@nilminiwso2 yes, done

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
