### ISSUE TITLE
Return userID along with the response in validateCode api and setPassword api

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11519]
**Is your suggestion related to an experience ? Please describe.**

In current IS versions return user object when user set password by /setPassword api and also account confirmation by /validateCode api. In these cases user object not return userID. 
**Describe the improvement**

So, It's better to return userId along with the response in above apis.

**Comment by nilasini** [comment]
@Chathurangap688 Isn't this issue reproducible in master?

**Comment by Chathurangap688** [comment]
> @Chathurangap688 Isn't this issue reproducible in master?

It is reproducible in master

**Comment by nilasini** [comment]
Did we fix do the fix for master?

**Comment by Chathurangap688** [comment]
> Did we fix do the fix for master?

This issue has been resolved by another issue. It is returning not only userId but also user object.
Issue: https://github.com/wso2/product-is/issues/10603
Related PR: https://github.com/wso2-extensions/identity-governance/pull/463

**Comment by nilasini** [comment]
@Chathurangap688 but seems the user object returned through the PR [1] doesn't have user id. Could you please confirm whether [1] fixes the issue mentioned in the description?

[1] https://github.com/wso2-extensions/identity-governance/pull/463

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
