### ISSUE TITLE
Some UI issues on certificates section

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#11513]
# Issue - 01 (Filter not working correctly on certificates section)

**Describe the Issue:**

Filter option did not work correctly when searching the content with space.

**How To Reproduce:**

1. Go to certificates section in the manage tab
2. Search the content with space

Filter not working correctly
![Screenshot from 2021-02-09 17-42-27](https://user-images.githubusercontent.com/47822500/107362146-65609d00-6afe-11eb-868c-c9c055218efc.png)

**Expected behavior :**
Based on the contain within a space result will return.
like
![Screenshot from 2021-02-09 17-37-21](https://user-images.githubusercontent.com/47822500/107361808-f1be9000-6afd-11eb-9275-1e9a82a075ac.png)

**Device Information :**
 - Device:  PC
 - OS: Ubuntu
 - Browser + Version : Firefox 85.0

# Issue - 02 (Error message not removed after the update)

**Describe the Issue:**
Error message not removed from UI after correcting the error.

**How To Reproduce:**

1. Go to the certificates section in the manage tab
2. Import certificate
3. Upload and Import already existing certificate : 
     It creates an error message “Unable to upload the certificate with alias: XXX to the Keystore. Provided alias 'XXX' is already available in the Keystore."
5. Then back to the previous page and upload a new certificate
6. Click Next button
The error message not removed, carry out this page also

https://user-images.githubusercontent.com/47822500/107331064-6383e300-6ad8-11eb-94b1-b7a92f4cffee.mp4

**Expected behavior:**
Not show the previous error message after updating new files.

**Device Information :**
 - Device:  PC
 - OS: Ubuntu
 - Browser + Version : firefox 85.0

# Issue - 03 (Sentence spacing inaccurate in tenant certificate section delete operation)

**Describe the Issue:**
Spaces unavailable in UI text after full-stops and commas in the tenant certificate section.

**How To Reproduce:**
1. Try to access Console->Manage->Configurations->Certificates.
2. Delete existing certificate.
3. Delete confirmation message has spacing issue.
![Screenshot from 2021-02-05 16-05-37](https://user-images.githubusercontent.com/10112625/107023812-2adcc480-67cd-11eb-826f-1c87ca8b291c.png)

4. Delete all tenant certificates.
5. Once deleted, the displayed text has the spacing issue.
![Screenshot from 2021-02-05 16-06-06](https://user-images.githubusercontent.com/10112625/107023836-303a0f00-67cd-11eb-951b-4622b1514943.png)

**Expected behavior:**

**Device Information** (_Please complete the following information_) **:**
Device: Laptop
OS: Linux
Browser + Version: Google Chrome Version 88.0.4324.146 (Official Build) (64-bit)

- [ ] Filter not working correctly on certificates section
- [ ] Error message not removed after the update
- [ ] Sentence spacing inaccurate in tenant certificate section delete operation

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
