### ISSUE TITLE
Return different error codes for PENDING_X locked account in the password recovery

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11515]
**Is your suggestion related to an experience ? Please describe.**

Currently IS returns only "_User account is locked_"  when PENDING_X locked user trying password recovery. But there are several reasons to lock accounts such as PENDING_AP/PENDING_SR. 

**Describe the improvement**

Depending on the status of the user account or the reason the user is locked in, it may be best to return different errors.

**Comment by nilasini** [comment]
@Chathurangap688 Isn't this issue reproducible in master?

**Comment by Chathurangap688** [comment]
> Isn't this issue reproducible in master?

It is reproducible in master

**Comment by nilasini** [comment]
Did we fix it in master?

**Comment by Chathurangap688** [comment]
> 

Here is the fix for master https://github.com/wso2-extensions/identity-governance/pull/578
