### ISSUE TITLE
Unnecessary delete operations on IDN_OIDC_REQ_OBJECT_REFERENCE table

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11528]
**Describe the issue:**
In the RequestObjectHandler [1], it is listening to a set of OAuth events and updating the IDN_OIDC_REQ_OBJECT_REFERENCE table.

There are two concerns on the delete operations done here.
- It is not required to delete them explicitly because it has foreign keys with `on delete cascade` and this table will be cleared once the parent record got cleared.
```
CREATE TABLE IF NOT EXISTS IDN_OIDC_REQ_OBJECT_REFERENCE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CONSUMER_KEY_ID INTEGER ,
  CODE_ID VARCHAR(255) ,
  TOKEN_ID VARCHAR(255) ,
  SESSION_DATA_KEY VARCHAR(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE,
  FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE,
  FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE
)
```
- These delete operations are performed even if we have disabled internal token cleanup causing extra write operations on the DB during the token generation flows.
```
[oauth.token_cleanup]
enable = false
```

**Environment information**
 - Product Version: IS 5.10.0
 
 [1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/3ca04e8fc0e4f3e3baa7c5c19a7db5f23e995708/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/handlers/RequestObjectHandler.java#L41

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
