### ISSUE TITLE
"Validate token bindings" and "Revoke tokens when the IDP session terminates" configurations are missing in SP management REST API endpoints

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11537]
**Describe the issue:**

Following endpoints don't support "Validate token bindings" and "Revoke tokens when the IDP session terminates" configurations, which are available under OIDC configurations in the management console.

`[POST] https://localhost:9443/t/carbon.super/api/server/v1/applications`
`[GET] https://localhost:9443/t/carbon.super/api/server/v1/applications/{app-id}/inbound-protocols/oidc`
`[PUT] https://localhost:9443/t/carbon.super/api/server/v1/applications/{app-id}/inbound-protocols/oidc`

<img width="747" alt="Screen Shot 2021-03-30 at 2 28 07 PM" src="https://user-images.githubusercontent.com/13187638/112963477-0a920c00-9165-11eb-8024-780151a0c9c2.png">

**Expected behavior:**
It should be able to create, update and retrieve "Validate token bindings" and "Revoke tokens when the IDP session terminates" configurations from the aforementioned endpoints.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by nilasini** [comment]
@sumedhe Is the issue reproducible in public? If not shall we close this issue?

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/identity-api-server/commit/457f2a6c37cfd63f43f7dd414e68b96aca7d8f53 and https://github.com/wso2/identity-api-server/commit/63322746b4ef3831ca892b883ac45bd0aaddc72f
