### ISSUE TITLE
Add integration test for multi attribute login feature 

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11530]
Resolves: https://github.com/wso2/product-is/issues/8899
**Is your suggestion related to an experience ? Please describe.**

Multi attribute login feature is now available on product-is. There are several unity tests available. But it seems like no integration tests are provided. 
**Describe the improvement**

It's better to implement integration tests for the multi attribute login feature.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
