### ISSUE TITLE
SCIM2 user creation updates the location claim with invalid SCIM2 ID

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#11540]
**Describe the issue:**

SCIM2 user creation set the location claim with the SCIM2 ID and return "**2f8449af-a6c3-412c-b41d-fc092416961d**"
![image](https://user-images.githubusercontent.com/20121821/113002371-53f75100-918f-11eb-9914-d600ee549bd1.png)

However users profile will contain a invalid SCIM2 ID as "**7077ccd1-8dab-4494-a0a5-8e9936db124e**"
![image](https://user-images.githubusercontent.com/20121821/113002661-a3d61800-918f-11eb-984c-f626257feb4d.png)

**How to reproduce:**

1. Enable location claim "Supported by Default" from the claims configurations.
2. create a user using the SCIM2 https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/#/Users%20Endpoint/createUser
3. The SCIM2 response location and the location claim value is differ

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashans** [comment]
I'm working on this.
