### ISSUE TITLE
No way to disable BPS schedules 

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11557]
**Describe the issue:**
WSO2 IS has some of the BPS features embedded and most of the users are not using this functionality. But the schedules related to these features are running in the background by default, consuming server resources. Eg: https://github.com/wso2/product-is/issues/9365

Hence, there should be a way to disable these tasks if somebody is not using them at all.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
