### ISSUE TITLE
Implement UI for docs landing page

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#11551]
We have come up with the following design for our 5.12.0 docs landing page. The UI for this needs to be implemented. 

![image](https://user-images.githubusercontent.com/45352240/113276714-be2e0400-92fd-11eb-8cc3-37c64ef91408.png)

**Comment by DonOmalVindula** [comment]
Following improvements to UI/UX were suggested during the discussion happened on 28/05/2021.
- Make the middle section (card section) less wordy
- Include live images other than icons as it makes the design more modern
- Using a single level navbar in header without having 2 levels of headers
- Including a direct link to API documentation
- Including the tech stack being used (using icons or any other method)
- Including a direct link to API documentation
