### ISSUE TITLE
deployment.config.json.j2 is out of sync

### ISSUE THREAD

**Issue by vordimous** [wso2/product-is#11556]
**Describe the issue:**
The deployment.config.json.j2 file is not up to date with the React app

**How to reproduce:**
Download the app

[Incorrectly formatted json object: deployment.config.json.j2](https://github.com/wso2/identity-apps/blob/master/features/org.wso2.identity.apps.myaccount.server.feature/resources/deployment.config.json.j2#L106)
[correct deployment.config.json file](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/public/deployment.config.json#L37)
[AppStore model](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/models/app-config.ts#L151)

**Expected behavior:**
the deployment.config.json file has the correct syntax for ui.authenticatorApp value

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by vinumaddumage** [comment]
According to the following, deployment.config.json.j2 should be updated include to the names and their corresponding link for authenticator apps that could be used for TOTP authentication.
https://github.com/wso2/identity-apps/blob/1bb061d44b7a4b5b759aeb86ca9e136ce5b2a8fa/apps/myaccount/src/models/app-config.ts#L126-L129

The following code section in the deployment.config.json.j2 should be altered to get the above config parameters of each authentication app to the `"authenticatorApp": []` array, from the deployment.toml (or default.json) file.
https://github.com/wso2/identity-apps/blob/1bb061d44b7a4b5b759aeb86ca9e136ce5b2a8fa/features/org.wso2.identity.apps.myaccount.server.feature/resources/deployment.config.json.j2#L105-L111

The following section of the default.json file from carbon-identity-framework should also be updated as required.
https://github.com/wso2/carbon-identity-framework/blob/701b413e3dd14426b562a7da999e0e4244fe695c/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json#L819

**Comment by piraveena** [comment]
Please reopen this issue if this is reproducible again
