### ISSUE TITLE
Allow integration with a preferred captcha implementation other tan reCAPTCHA

### ISSUE THREAD

**Issue by UmenR** [wso2/product-is#11565]
**Is your suggestion related to an experience? Please describe.**
Currently, during the flows where a user has to solve a captcha(SSO, Self Signup, PW recovery, Username Recovery), The only configurable mechanism is Google reCAPTCHA. Rather than being limited to using reCAPTCHA make the captcha implementation extensible so that any mechanism can be plugged into these flows.

**Describe the improvement**

1. Currently the rendering of the captcha implementation within the basicAuthenticator and the recovery applications are tightly coupled with rendering reCAPTCHA(adding recaptcha related headers) on the pages where a captcha needs to be rendered. This needs to be improved to render the captcha of other configured implementations, 

2. Furthermore the validation of the captcha hapens through the captchaFilter which also requires change in logic to execute the validation logic accordingly.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
