### ISSUE TITLE
MyAccount scope validation is not implemented properly

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11572]
**Describe the issue:**
The scope validation defined for the MyAccount in the deployment.toml as follows is not honored.
```
[myaccount.personal_info.scopes]
create =  ["internal_application_mgt_create"]
read = []
update = ["internal_application_mgt_update"]
delete = ["internal_application_mgt_delete"]
```
It's being written properly to the MyAccount deployment.config.json as follows.
```
...
"personalInfo": {
                "disabledFeatures": [
                    "profileInfo.mobileVerification"
                ],
                "enabled": true,
                "scopes": {
                    "read": [
                    ],
                    "update": [
                            "internal_application_mgt_update"
                    ],
                    "create": [
                            "internal_application_mgt_create"
                    ],
                    "delete": [
                            "internal_application_mgt_delete"
                    ]
                }
            },
...
```
As per the above configuration, only the users who're entitled to get the defined scope should be able to modify the user profile section. However, it's not honored and all the users can update their user profile.

**Expected behavior:**
1. If the above configuration is added, a new user without having any roles should not be able to update their user profile from MyAccount.
2. User should also be prevented from updating the profile picture.

**Environment information**
 - Product Version: IS 5.11.0

**Related issues:**
#11574

**Comment by brionmario** [comment]
There should be an additional validation in this [line](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/components/profile/profile.tsx#L699). For reference, take a look at [this implementation](https://github.com/wso2/identity-apps/blob/a217f1c9112bc5ee56d024356682502921d39181/apps/console/src/features/applications/components/settings/sign-on-methods/sign-on-methods.tsx#L331).
