### ISSUE TITLE
Update properties as a batch implementation does not supported with case insensitive Usernames

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11578]
**Describe the issue:**
http://wso2.org/claims/lastLoginTime claim is not updated once CaseInsensitiveUsername is set to true in the userstore configuration file.

Current implementation is [1] and it needs to be changed as below [2].

<pre style="color:#000020;background:#f6f8ff;">if (isCaseSensitiveUsername()) <span style="color:#406080; ">{</span>
    sqlStmt <span style="color:#308080; ">=</span> realmConfig<span style="color:#308080; ">.</span>getUserStoreProperty<span style="color:#308080; ">(</span>JDBCRealmConstants<span style="color:#308080; ">.</span>XXXX<span style="color:#308080; ">)</span><span style="color:#406080; ">;</span>
<span style="color:#406080; ">}</span> else <span style="color:#406080; ">{</span>
    sqlStmt <span style="color:#308080; ">=</span> realmConfig<span style="color:#308080; ">.</span>getUserStoreProperty<span style="color:#308080; ">(</span>JDBCCaseInsensitiveConstants<span style="color:#308080; ">.</span>XXXX<span style="color:#308080; ">)</span><span style="color:#406080; ">;</span>
<span style="color:#406080; ">}</span>
</pre>

**How to reproduce:**

- GET IS-5.9.0 pack.
- Configure case-sensitive DB as the secondary userstore.
- Set CaseInsensitiveUsername property to true in userstore configurations.
`<Property name="CaseInsensitiveUsername">true</Property>`
- Enable the Lock Idle Accounts feature (then only it'll update the lastLoginTime claim)
- Create a new user "john"
- Login with "John", it'll not update the lastLoginTime claim.
- Login with "john", the claim will be updated.

**Expected behavior:**
Case insensitive queries should be identified and claims should be updated by considering the CaseInsensitiveUsername property.

**Environment information** **:**
 - Product Version: [IS 5.9.0]
 - Userstore: [Postgres]

[1] - https://github.com/wso2/carbon-kernel/blob/v4.5.1/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L3318
[2] - https://github.com/wso2/carbon-kernel/blob/v4.5.1/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L2547

**Comment by nipunthilakshan** [comment]
I will work on this.

**Comment by nilasini** [comment]
Closing the issue since the fix has been done with https://github.com/wso2/carbon-kernel/pull/2975/files
