### ISSUE TITLE
Handle tenant domain properly for SaaS applications in WS-Trust

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#11571]
**Is your suggestion related to an experience? Please describe.**
Once https://github.com/wso2/product-is/issues/9483 is fixed, the STS service supports tenanted calls. However, if the user's tenant domain is not present in the request, the service will assume that the user belongs to the service tenant domain which is derived based on the sts service request URI. 

But ideally, we should do this assumption only for non-SaaS apps. For SaaS apps, we still need to mandate tenant domain in the user's username.

**Describe the improvement**
When the STS request comes, it includes the WS-trust audience URL in the request. This URL is added to the service provider configuration in WSO2 IS, therefore it should allow identifying the SP eventually allowing to figure out whether the targetted application is SaaS or not. If the app is SaaS, the tenant domain in the username is a must. Otherwise, the tenant domain is assumed as same as the service tenant domain, if it's not available in the username.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
