### ISSUE TITLE
Oracle RAC script doesn't run on the identity-component migration

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#11587]
**Describe the issue:**
When performing the identity-component migration on an Oracle RAC database, the migration client uses the "Oracle" db scripts instead on "Oracle RAC" scripts.

**How to reproduce:**
1. Run the identity-component migration on Oracle RAC setup.

**Expected behavior:**
Oracle RAC scripts should be executed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: Oracle RAC 12c

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
