### ISSUE TITLE
Password reset with challenge questions flow breaks when the auto login feature is enabled.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11580]
**Describe the issue:**
Password reset with challenge questions flow breaks when the auto-login feature is enabled.

**How to reproduce:**
Get the latest updated IS-5.10.0 server.
Enable password recovery with challenge questions along with the auto-login feature.
Reset the password by answering the challenge questions.
After successfully resetting the password the following error is observed.
<img width="1260" alt="Screen Shot 2021-04-08 at 4 33 46 PM" src="https://user-images.githubusercontent.com/47600906/114016324-57be5e00-9888-11eb-9628-2e3c1b074d68.png">

The following error is observed in the logs.
```
[2021-04-08 15:49:57,816] [cb802ddf-b021-4f23-ba90-2deeb8418673] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/accountrecoveryendpoint].[completepasswordreset.do]} - Servlet.service() for servlet [completepasswordreset.do] in context with path [/accountrecoveryendpoint] threw exception [An exception occurred processing [/password-reset-complete.jsp] at line [156]

153:                 String refererParams = referer.substring(referer.indexOf("?") + 1);
154:                 parameterList = refererParams.split("&");
155:                 for (String param : parameterList) {
156:                     String key = param.substring(0, param.indexOf("="));
157:                     String value = param.substring(param.indexOf("=") + 1);
158:                     queryMap.put(key, value);
159:                 }


Stacktrace:] with root cause java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.apache.jsp.password_002dreset_002dcomplete_jsp._jspService(password_002dreset_002dcomplete_jsp.java:343)
```
**Expected behavior:**
The above error should not be observed, the user should be logged in.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by RidmiR** [comment]
Password reset with challenge question is not available in Asgardeo. Hence unable to verify in Asgardeo.
