### ISSUE TITLE
Doc Feedback: Mention the token cleanup step in the documentation

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#11581]
Location : https://is.docs.wso2.com/en/5.10.0/setup/migrating-preparing-for-migration/

Not executing the token-cleanup scripts prior to running the migration would cause some issues if the token-cleanup is not enabled. So it would be better to mention it as in [1]

[1]. https://docs.wso2.com/display/IS580/Upgrading+from+the+Previous+Release#UpgradingfromthePreviousRelease-Preparingformigration

**Comment by ashendes** [comment]
Addressed in https://github.com/wso2/docs-is/pull/3232
