### ISSUE TITLE
Mobile number verification is not working when it's updated from user portal

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11595]
**Describe the issue:**
Mobile Number Verification for an Updated Mobile Number is not working when it's updated from the user portal.

**How to reproduce:**
- Get WUM updated IS-5.11.0 pack.
- Configure Mobile Number Verification for an Updated Mobile Number as described in [1].
- Try to update the mobile number from the user portal.
- The mobile number will be updated without prompting for any verification.

It was observed that `"verifyMobile": "true"` property is not sent to me patch user endpoint, and it causes this behavior. Below is the payload that's sent to me patch user endpoint from myaccount app.

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"Operations"</span><span style="color:#308080; ">:</span><span style="color:#308080; ">[</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"op"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"replace"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"value"</span><span style="color:#308080; ">:</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"phoneNumbers"</span><span style="color:#308080; ">:</span><span style="color:#308080; ">[</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"type"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"mobile"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"value"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"0112122123"</span><span style="color:#406080; ">}</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">""</span><span style="color:#308080; ">,</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"type"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"mobile"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"value"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"0112122123"</span><span style="color:#406080; ">}</span><span style="color:#308080; ">]</span><span style="color:#406080; ">}</span><span style="color:#406080; ">}</span><span style="color:#308080; ">]</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"schemas"</span><span style="color:#308080; ">:</span><span style="color:#308080; ">[</span><span style="color:#1060b6; ">"urn:ietf:params:scim:api:messages:2.0:PatchOp"</span><span style="color:#308080; ">]</span><span style="color:#406080; ">}</span>
</pre>

It needs to be corrected as below.

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"Operations"</span><span style="color:#308080; ">:</span><span style="color:#308080; ">[</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"op"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"replace"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"value"</span><span style="color:#308080; ">:</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"</span><span style="color:#308080; ">:</span> <span style="color:#406080; ">{</span><span style="color:#1060b6; ">"verifyMobile"</span><span style="color:#308080; ">:</span> <span style="color:#1060b6; ">"true"</span><span style="color:#406080; ">}</span><span style="color:#308080; ">,</span> <span style="color:#1060b6; ">"phoneNumbers"</span><span style="color:#308080; ">:</span><span style="color:#308080; ">[</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"type"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"mobile"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"value"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"0112122123"</span><span style="color:#406080; ">}</span><span style="color:#308080; ">]</span><span style="color:#406080; ">}</span><span style="color:#406080; ">}</span><span style="color:#308080; ">]</span><span style="color:#406080; ">}</span>
</pre>

**Expected behavior:**
New mobile number should be verified before updating the http://wso2.org/claims/mobile claim.

**Environment information** **:**
 - Product Version: [IS 5.11.0]

[1] - https://is.docs.wso2.com/en/latest/develop/enable-verification-for-updated-mobile-number/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
