### ISSUE TITLE
Active Session Limit Handler is not working for secondary user stores(ex: LDAP and AD)

### ISSUE THREAD

**Issue by SnehalC-22** [wso2/product-is#11609]
**Describe the issue:**
Not found any error in the console.

**How to reproduce:**
Configure secondary user store as Read-Only LDAP User Store.
Try to log in with an LDAP user on multiple browsers it allows us to have multiple sessions. The session handler page is not coming

**Expected behavior:**
The user should be able to successfully authenticate to the system for the first time and should be prompted to terminate the sessions once the maximum number of sessions is reached.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - OS: [Linux]
 - Userstore: [ LDAP]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
