### ISSUE TITLE
Have an application level config to enable/disable sid claim

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11629]
**Is your suggestion related to an experience ? Please describe.**
According to the back-channel logout spec https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken , sid claim is optional. If sid claim is not found, then application can terminate all the sessions of the user. So We need to have an application level config to enable/ disable sid claim

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
