### ISSUE TITLE
Add HSTS header support to IS Analytics server.

### ISSUE THREAD

**Issue by Manasha11** [wso2/product-is#11628]
**Describe the improvement**
we have already identified this issue [1] related to the HSTS and we have provided a patch [2] to support HSTS headers in APIM analytics 2.6.0. 
This fix has been provided to the "org.wso2.transport.http.netty_6.0.163.jar" and it has not been provided to the "org.wso2.transport.http.netty_6.0.289.jar" which is released with the IS-Analytics 5.8.0.  
Therefore we need to do the same fix in the latest version as well.

[1] https://github.com/wso2/product-sp/issues/1056
[2] https://github.com/wso2-support/transport-http/commit/1e56925a4bef094a73736b886887d22235433e2f

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
