### ISSUE TITLE
Improvements in OIDC Back-channel logout

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11630]
**Is your suggestion related to an experience ? Please describe.**
Inbound component:
https://github.com/wso2/product-is/issues/7681
https://github.com/wso2/product-is/issues/11629
https://github.com/wso2/product-is/issues/10727

Outbound component:
https://github.com/wso2/product-is/issues/10726

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
