### ISSUE TITLE
View Keystore -> Available Certificates are limited by 50 items. Can't view all certs using Mgt Console.

### ISSUE THREAD

**Issue by stapter** [wso2/product-is#11633]
**Describe the Issue:**
My **wso2carbon.jks** contains contains 93 entries.
But using Managment Console I can't view more then 50 certificates

**How to reproduce:**
Add  more than 50 certificates to **wso2carbon.jks** and try to view all of them using Managment Console.

![image](https://user-images.githubusercontent.com/2757145/115727899-b4437200-a38c-11eb-906b-8dc80a441e31.png)

**Environment information:**
 - Product Version: IS 5.11.0
 - OS: Windows
 - Database: MsSQL
 - Userstore: JDBC

**Comment by ruwanta** [comment]
A question is what is the purpose of having a large number of entries in servers primary JKS. It seems counter-intuitive.

**Comment by stapter** [comment]
I just added some certificates to default **wso2carbon.jks** keystore for test purpose. Default instalation keystore contains 88 entries that is also more than 50.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
