### ISSUE TITLE
Custom-grant throwing error

### ISSUE THREAD

**Issue by abhishekkandi** [wso2/product-is#11649]
Referred below attached documentation link to setup custom grant type :

1) Generated jar for custom-grant project included as zip file in documentation. Copied it to IS_HOME\repository\components\lib
2) Updated deployment.toml with custom grant type & Restarted  the server. 
[[oauth.custom_grant_type]]
name="mobile"
grant_handler="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrant"
grant_validator="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrantValidator"
[oauth.custom_grant_type.properties]
IdTokenAllowed=true
3) Selected "mobile" grant type fo one of service provider & tried to generate the access token(Attaching the curl request for the same). Got below error in carbon logs.

![image](https://user-images.githubusercontent.com/30003726/116078059-ca667080-a6b3-11eb-8f56-376633dac64a.png)
https://is.docs.wso2.com/en/5.10.0/learn/writing-a-custom-oauth-2.0-grant-type/#writing-a-custom-oauth-20-grant-type

Environment: 
 - Product Version: IS 5.10.0
 - OS: Windows 10
 - Userstore: LDAP
 
 CURL request: 
 curl --location --request POST 'https://localhost:9443/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic RWZwZkhwZlNSV0MxUzZGTmFSVUlFYWluYlhnYTpmRVdMdXNJeVZCRWF2aVV3REFETjJMbFMyVVFh' \
--data-urlencode 'grant_type=mobile' \
--data-urlencode 'mobileNumber=0333444' \
--data-urlencode 'username=priya@mailinator.com'

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
