### ISSUE TITLE
Unable to login to management console when proxy_context_path is set

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11657]
**Describe the issue:**
A part of https://github.com/wso2/product-is/issues/10380

As mentioned in https://github.com/wso2/product-is/issues/10380, when proxy_context_path is configured along with relevant proxy configurations, it does not allow to login to the carbon management console.

Even though we have configured the proxy_context_path, it tries to send the following request in to root path.
```
POST /carbon/admin/js/csrfPrevention.js
```

In the csrfPrevention.js, it has the following line which is initiating the above request.
```
xhr.open("POST", "/carbon/admin/js/csrfPrevention.js", false);
```

It seems the above path is referred from the following config in `repository/conf/tomcat/carbon/WEB-INF/web.xml`
```
    <!-- OWASP CSRFGuard servlet that serves dynamic token injection JavaScript-->
    <servlet>
        <servlet-name>JavaScriptServlet</servlet-name>
        <servlet-class>org.owasp.csrfguard.servlet.JavaScriptServlet</servlet-class>
    </servlet>

    <servlet-mapping>
        <servlet-name>bridgeservlet</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>
    <!--
       This is required if your application bundles expose JSPs.
     -->
    <servlet-mapping>
        <servlet-name>bridgeservlet</servlet-name>
        <url-pattern>*.jsp</url-pattern>
    </servlet-mapping>

    <servlet-mapping>
        <servlet-name>JavaScriptServlet</servlet-name>
        <url-pattern>/carbon/admin/js/csrfPrevention.js</url-pattern>
    </servlet-mapping>
    ```

**Comment by darshanasbg** [comment]
We need to consider proxy context path in the https://github.com/aramrami/OWASP-CSRFGuard/blob/master/csrfguard/src/main/java/org/owasp/csrfguard/servlet/JavaScriptServlet.java#L205

**Comment by rksk** [comment]
Addressed with https://github.com/wso2/WSO2-OWASP-CSRFGuard/pull/3
