### ISSUE TITLE
Implement a logger for Front End Apps

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#11650]
**Is your suggestion related to an experience ? Please describe.**
ATM, there is no logger available in the Identity Server front-end Apps (Login, Console & My Account). It would be better if there is one so we can set a log level in a configuration file to enable logs.

**Additional context**

Possible libraries.
**log4js**  - https://www.npmjs.com/package/log4js

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
