### ISSUE TITLE
samlssoTokenId cookie is not cleared upon logout when Front-Channel Logout Method is selected

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11665]
**Describe the issue:**
samlssoTokenId cookie is not cleared upon logout when Front-Channel Logout Method is selected. This results in the following behavior.

Consider a scenario where there are two applications, App A and App B. Login to App A and then log out from it. Thereafter login to App B and log out from it. Since the samlssoTokenId cookie is not cleared during the previous log out from App A, the Identity server tries to logout the App A first(however the user has already been logged out from App A)

**How to reproduce:**

- Set up a SAML service provider that supports the front channel logout[1].
- Login to the service provider and then log out.
- Notice the samlssoTokenId cookie is not cleared upon log out.

**Expected behavior:**
The samlssoTokenId cookie should be cleared in the above scenario upon logout.

**Environment information** **:**
 - Product Version: [IS-5.3.0,IS-5.10.0]

[1]https://dewni-matheesha.medium.com/saml-2-0-front-channel-logout-with-wso2-identity-server-8a72d1075cf5

**Comment by deshankoswatte** [comment]
This is done for the 5.10 milestones as well. Refer [here](https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/87734535d3a92bb273e9d5a2617918e68d34e78e/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/servlet/SAMLSSOProviderServlet.java#L928). @AnuradhaSK you can close this issue.
