### ISSUE TITLE
SCIM2 search filtering not working for secondary userstores custom claims

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#11668]
**Describe the issue:**
When using SCIM APIs to search user with custom claim from secondary userstore, if the custom claim is mapped to local claim in secondary userstore, it is working as expected but when custom claim is mapped in primary userstore and not mapped in the secondary user store, searching is not working for secondary userstore with that custom claim.

**How to reproduce:**

- Add scim custom claim configuration to scim2-schema-extension.config file
- Add custom claim to local claims only to Primary user store
- Add custom claim to External claims
- Send below request to search users

```
curl -v -k -X POST --user admin:admin --data '{"schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],"filter":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:entityID eq 11850","domain":"custom","startIndex": 1,"count": 10}' --header "Content-Type:application/scim+json"  'https://localhost:9443/scim2/Users/.search' 
```

- Will get the below error 

```
"detail":"Unsupported attribute: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:entityID"
```

- Add local custom claim mapping to secondary userstore and send the above request, that will give the search results

**Expected behavior:**
Even though, the custom local claim mapping is not presented in the secondary userstore, if it is presented in primary userstore domain, it should use the primary userstore domain claim configuration.

**Environment information** 
 - Product Version: [ KM 5.9.0]
 - OS: [ Linux]
 - Database: [ H2]
 - Userstore: [primary - LDAP, secondary - JDBC]

**Comment by nilasini** [comment]
@sumedhe Is it reproducible in master? Can we close this issue?

**Comment by sumedhe** [comment]
It's not reproducible in mater. We can close this.
