### ISSUE TITLE
Need to update Enabling Notifications for User Operations document

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#11673]
**Is your suggestion related to a missing or misleading document? Please describe.**

We have documented Enabling Notifications for User Operations feature in IS docs space, But if we need to make it work with the latest IS versions (After IS 5.6.0) we have to add the org.wso2.carbon.identity.notification.mgt.email-x.x.x.jar [1] to the  <PRODUCT_IS>/repository/components/dropins directory. Hence documentation needs to be updated accordingly once this jar is added to the IS connector store [2].
 
[1] https://github.com/wso2-extensions/identity-notification-email
[2] https://store.wso2.com/store/assets/isconnector/list?

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**
https://github.com/wso2/product-is/issues/11181

**Comment by Kanapriya** [comment]
@gomathyk , the particular jar gets uploaded in the connector store [1], can we get the docs updated with the store link.

[1] https://store.wso2.com/store/assets/isconnector/details/959b792a-efce-4b12-af9b-4744c650f6b2

**Comment by gomathyk** [comment]
The documents below have been updated. 

https://docs.wso2.com/display/IS570/Enabling+Notifications+for+User+Operations
https://docs.wso2.com/display/IS580/Enabling+Notifications+for+User+Operations
https://is.docs.wso2.com/en/5.9.0/learn/enabling-notifications-for-user-operations/
https://is.docs.wso2.com/en/5.10.0/learn/enabling-notifications-for-user-operations/
https://is.docs.wso2.com/en/latest/learn/enabling-notifications-for-user-operations/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
