### ISSUE TITLE
Console does not display descriptions when adding a new custom user store

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#11672]
### Describe the issue
In IS we can add a custom user store. After adding the artifacts, we create a new user store using the custom user store manager. When adding, the following page does not provide any information about the custom user store manager.

<img width="1629" alt="Screenshot 2021-04-29 at 14 44 49" src="https://user-images.githubusercontent.com/39567992/116528526-8ebce800-a8f9-11eb-943c-9933cd6183d9.png">

In here, we don't have any description of the custom user store manager.

### Expected behavior
We can get the user store manager type by using [https://localhost:9443/api/server/v1/userstores](https://localhost:9443/api/server/v1/userstores) API. We need to display the custom user store manager name (or type) and a general description.

### Steps to reproduce
- Add artifacts for a custom user store manager.
- Navigate to the new console and click on `New Userstore` button.

**Comment by savindi7** [comment]
This issue is fixed with the following PR - https://github.com/wso2/identity-apps/pull/3146
