### ISSUE TITLE
Issues in SCIM PATCH Request

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11678]
**Describe the issue:**
Following valid patch operation payloads doesn't support as expected.

- [ ] 1.

Operation:
```json
{
  "op": "add",
  "path": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager.value",
  "value": "Ruth"
}
```

output:
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "scimType": "noTarget",
    "detail": "According to SCIM specification max one sub attribute can be allowed for SCIM attribute. path: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager.value",
    "status": "400"
}
```

- [ ] 2. Simple Multivalued attribute add operation with the path param works as replace operation

Let assume `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:devices` has values ["D1", "D2", "D3"]. After the following patch operation, the value should be ["D1", "D2", "D3", "D4", "D5"]. But it will become ["D4", "D5"].
 
Operation:

```json
        {
            "op": "add",
            "path": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:devices",
            "value": ["D4", "D5"]
        }
```

but, the following request (without specifying the path) work as expected.
```json
        {
            "op": "add",
            "value": {
                "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                    "devices": [ "D4", "D5" ]
                }
            }
        }
```

- [ ] 3. Replacing a specific item in a multivalued simple attribute is not working,
Let assume `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:devices` has values ["D1", "D2", "D3"]. The following patch operation gives 500 Response
```json
{
            "op": "replace",
            "path": "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:devices[value eq \"D1\"]",
            "value": "D4"
 }
```
Response:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Error in performing the patch operation on user resource.",
    "status": "500"
}
```

**How to reproduce:**
Perform PATCH requests `{{baseUrl}}/scim2/Users/{{userId}}` including the mentioned operations.
```json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
       Add your operations here
    ]
}
```

- [ ] 4. Fail to replace specific attribute in the complex multi-valued attribute
Operation
```json
{
    "op": "replace",
    "path": "emails[type eq home]",
    "value": "qwerty@gmail.com"
}
```
Response:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Error in performing the patch operation on user resource.",
    "status": "500"
}
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-M18
 - OS: Linux
 - Database: H2
 - Userstore:LDAP,

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
