### ISSUE TITLE
Primary userName claim for SCIM 2.0 must be configurable in the Resident IdP for each Tenant

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#11688]
**Describe the improvement**
The configuration for primary userName claim for SCIM 2.0 should be moved from the config file to Resident IdP to be able to configure per tenant.

**Additional context**
Related to #10631.

**Comment by rksk** [comment]
It is good to test all the flows like adding users to a group with this config because the username is included in the patch request.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
This needs to be addressed with https://github.com/wso2-enterprise/iam-product-management/issues/72
