### ISSUE TITLE
Always reading captcha-config.properties from recovery endpoint API

### ISSUE THREAD

**Issue by ashans** [wso2/product-is#11699]
**Describe the issue:**
To get the captcha related configurations from `org.wso2.carbon.identity.api.user.recovery` API component, it is reading the `captcha-config.properties` file in each password recovery request.

https://github.com/wso2-extensions/identity-governance/blob/1646ff304832570923017a0571b98289377fad67/components/org.wso2.carbon.identity.api.user.recovery/src/main/java/org/wso2/carbon/identity/recovery/endpoint/impl/CaptchaApiServiceImpl.java#L56

**Expected behavior:**
Configurations should be cached/stored in memory and should not read the configuration file always.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
