### ISSUE TITLE
Roles are not getting listed for users from Active Directory User Store in the UI

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-is#11691]
**Describe the issue:**
When an AD user store is configured as a secondary user store, users cannot list their roles from the carbon management console.
If we check the roles and list their assigned users, users are getting listed.

**How to reproduce:**
1. Create an Active Directory user store with users assigned with some roles.
2. Configure the above as a secondary user store.
3. Login to the carbon management console and try to list the roles for a specific user.

**Environment information:**
 - Product Version: IS 5.9.0 / IS-KM 5.9.0

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by rksk** [comment]
Fixed with https://github.com/wso2-support/carbon-kernel/pull/1389
