### ISSUE TITLE
Login with OTP doesn't work because you are redirected to the wrong url

### ISSUE THREAD

**Issue by AndreaCaglio97** [wso2/product-is#11701]
**Describe the issue:**

The login using the OTP as password ends with an error.
On the browser we are redirected at the following url:

`https://dsotp-dev.digitalgrid.it/accountrecoveryendpoint/confirmrecovery.do?client_id=gVWBVK0pdX4pg2Yk3fFbBjKe1aUa&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&nonce=eMpRGZ2HmgHcXhvgavgzd-vxKDYeyTCNZOImNQjQemI&passiveAuth=false&redirect_uri=https%3A%2F%2Fdsotp-dev.digitalgrid.it%2Flogin%2Foauth2%2Fcode%2Fwso2&response_type=code&scope=openid&state=P7R0WCAAFN6erHiAOuDHCGpie2MRlAp7Z3Vl3Onyqm0%3D&tenantDomain=carbon.super&sessionDataKey=94e6cb26-faa5-47a4-a787-b7adbce9218b&relyingParty=gVWBVK0pdX4pg2Yk3fFbBjKe1aUa&type=oidc&sp=ng-dms-gateway&isSaaSApp=true&username=mario.rossi%40ngdms.com&tenantdomain=ngdms.com&confirmation=ZPSXNU&callback=%2Fauthenticationendpoint%2Flogin.do%3Fclient_id%3DgVWBVK0pdX4pg2Yk3fFbBjKe1aUa%26commonAuthCallerPath%3D%252Foauth2%252Fauthorize%26forceAuth%3Dfalse%26nonce%3DeMpRGZ2HmgHcXhvgavgzd-vxKDYeyTCNZOImNQjQemI%26passiveAuth%3Dfalse%26redirect_uri%3Dhttps%253A%252F%252Fdsotp-dev.digitalgrid.it%252Flogin%252Foauth2%252Fcode%252Fwso2%26response_type%3Dcode%26scope%3Dopenid%26state%3DP7R0WCAAFN6erHiAOuDHCGpie2MRlAp7Z3Vl3Onyqm0%253D%26tenantDomain%3Dcarbon.super%26sessionDataKey%3D94e6cb26-faa5-47a4-a787-b7adbce9218b%26relyingParty%3DgVWBVK0pdX4pg2Yk3fFbBjKe1aUa%26type%3Doidc%26sp%3Dng-dms-gateway%26isSaaSApp%3Dtrue%26authenticators%3DBasicAuthenticator%3ALOCAL&reason=ADMIN_FORCED_PASSWORD_RESET_VIA_OTP`

The following is the screenshot of the result obtained on the browser:
<img width="792" alt="ngdmsScreen" src="https://user-images.githubusercontent.com/31506485/117251544-19936a80-ae45-11eb-8c13-8ad0be90dec0.png">

Replacing in the url of the error page the tenant **carbon.super** with our custom tenant **ngdms.com**, the first login with OTP works and, as showed in the following screenshot, it's possible to set a new password:
<img width="522" alt="login" src="https://user-images.githubusercontent.com/31506485/117251681-49db0900-ae45-11eb-9eec-543da8911c55.png">

Why this replacing is necessary? I don't understand why **carbon.super** tenant is in the url instead of our custom tenant **ngdms.com** .
What can be done to fix it?

**How to reproduce:**

- Create a service provider on carbon.super tenant (SaaS);
- Create a custom tenant @ngdms.com;
- Create an user mario.rossi@ngdms.com in the custom tenant with OTP enabled;
- Generate an OTP for the user mario.rossi@ngdms.com;
- Login with the user mario.rossi@ngdms.com using the OTP.

**Expected behavior:**
The login using the OTP as password ends successful and then it's possible to create a new password.

**Environment information:**
 - Product Version: IS 5.11.0
 - OS: Mac
 - Database: PostgreSQL
 - Userstore: JPA

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/11555

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
