### ISSUE TITLE
Infinite loop of requests are being sent to the `authorize` endpoint when third-party cookies are disabled in the browser

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#11710]
**Describe the issue:**
When using the Auth SDKs with third-party cookies disabled in the browser, infinite requests are being sent to the `authorize` endpoint. This is because, when third-party cookies are disabled, the `obps` cookie is not being sent with the requests when checking if the session state is changed. 
Log in to one of the sample apps after disabling third-party cookies in the browser. 
**Expected behavior:**
When third-party cookies are disabled, checking session state should be disabled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
