### ISSUE TITLE
ReturnOnlyMappedLocalRoles property should drop unmapped on no role matches in SAML response

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#11714]
**Describe the issue:**
There are mappings defined in the IDP Role Configuration section, and when receiving federated SAML roles there is no match for any role mappings. All federated source roles make it through.  Does not work as expected (expect all roles to be dropped in this scenario, because none of them matched the mappings)

**How to reproduce:**
- get WUM updated IS-KM 5.7.0
- enable ReturnOnlyMappedLocalRoles in carbon.xml (`<FederatedRoleManagement>
        <ReturnOnlyMappedLocalRoles>true</ReturnOnlyMappedLocalRoles>
</FederatedRoleManagement>`)
- configure a SAML IDP, add role mappings, configure a SAML SP, add the federated IDP to SP, login to SAML SP using federated user 

**Expected behavior:**
There are mappings defined in the IDP Role Configuration section, and when receiving federated SAML roles there is at least one match for a role mapping.  Mapped role makes is through, other unmapped roles are dropped.  This scenario works as expected

When receiving federated SAML roles and there is no match for any role mappings, non-matching roles should not make it through to SP

**Environment information:**
 - Product Version: IS-KM 5.7.0

---

### Optional Fields
https://github.com/wso2/product-is/issues/3145

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
