### ISSUE TITLE
Operations carried out on the scim2/Roles endpoint are not logged in the audit logs.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11711]
**Describe the issue:**
Operations carried out on the scim2/Roles endpoint are not logged in the audit logs.

**How to reproduce:**
In an updated IS-5.11.0 pack, try out the following operations. There are no logs for these operations 

- Create/delete a new role.
- Add/remove a user from a role.
- Add/remove a role from a group.

Also for adding/removing roles from the user through scim2/Bulk endpoint do not log any audit logs.

**Expected behavior:**
Audit logs should be present for the scim2 role endpoint[1] operations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]

[1]https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Roles%20Endpoint

**Comment by rksk** [comment]
Please test all the user management operations such as adding/removing. a user to a role/group and adding a role/group to a user.
