### ISSUE TITLE
Configure adaptive scripts from file based service provider

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11721]
In the document [1], it describes adding a file-based service provider. But it has not mentioned about configuring an adaptive script.

It is possible to define the adaptive script inside a tag called `<AuthenticationScript>` inside the `<LocalAndOutBoundAuthenticationConfig>` tag like below.
```
<LocalAndOutBoundAuthenticationConfig>
    <AuthenticationScript enabled="true" language="application/javascript"><![CDATA[var onLoginRequest = function(context) {
    executeStep(1);
};
]]></AuthenticationScript>
```

[1] https://is.docs.wso2.com/en/latest/setup/configuring-a-sp-and-idp-using-configuration-files/#adding-a-service-provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
