### ISSUE TITLE
Users not recognize when appending the userStore domain to login identifier in multi attribute login. 

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#11729]
**Describe the issue:**

When we have two users with the same value for the same claim in different userstores, We cannot login any user account even if we append the userStore domain to the login identifier in multi attribute login flow. 
**How to reproduce:**

it should search users only for specific userStore when userStore domain appends with the loginidentifier. 
**Expected behavior:**

It should work as username behavior when disabling the multi attribute login feature.   
When the userStore domain appends with the login identifier, it will search users only the given userStore domain. 
If the userStore domain does not append to the login identifier, it will search users in all userStores. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: , IS 5.10.0
 - Userstore:  JDBC

---

### Optional Fields

**Related issues:**

https://github.com/wso2/product-is/issues/8899
**Suggested labels:**

**Comment by Dinithi-Hasanika** [comment]
This issue needs to be fixed for Identity server 5.11

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
