### ISSUE TITLE
Wrong Configuration to enable login data publisher 

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#11733]
**Is your suggestion related to a missing or misleading document? Please describe.**

The configuration given at https://is.docs.wso2.com/en/latest/learn/prerequisites-to-publish-statistics/#step-02-enable-analytics-in-wso2-is to enable login data publisher in wrong. 
![image](https://user-images.githubusercontent.com/11737221/117928361-16065480-b319-11eb-8b91-fbc6a87d0d10.png)

**Describe the improvement**

The correct configuration should be as,
```
[identity_mgt.analytics_login_data_publisher_v110]
enable=true
```

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
