### ISSUE TITLE
JWT header parameter "x5t" is having incorrect thumbprint value.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11736]
**Describe the issue:**
The "x5t" parameter of the JWT header generated by the identity server is having the SHA-256 thumbprint instead of the SHA-1 thumbprint. The following RFC[1] states that the x5t should be the SHA-1 thumbprint of the certificate.

**Expected behavior:**
"x5t" parameter in the JWT should be the SHA-1 thumbprint of the certificate.

**Environment information** **:**
 - Product Version: [IS 5.10.0, IS 5.11.0]

[1]https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.7

**Comment by nilasini** [comment]
Fix already available with https://github.com/wso2-extensions/identity-inbound-auth-oauth/blame/5a14d924ff269ee35baa1196666e14bf149c9c62/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authcontext/JWTTokenGenerator.java#L404-L413
