### ISSUE TITLE
MaxUserNameListLength is not considered in UniqueIDJDBCUserStoreManager

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11734]
**Describe the issue:**
In `getUserListFromProperties()` [1] of JDBCUserStoreManager it checks `MaxUserNameListLength` and limit the result list. But in `doGetUserListFromPropertiesWithID()` [2], it does not have such a limit and returns all the users on the userstore adding a high load to the WSO2IS as well as the DB.

**How to reproduce:**
- Configure UniqueIDJDBCUserStoreManager
- Create a large number of users  (eg: 10,000)
- Invoke `GET /scim2/Users` without a filter
- It will take a lot of time to return all the users or thread deaths will occur

**Expected behavior:**
It should not list more than 100 users

**Environment information** 
 - Product Version: IS 5.11.0

[1] https://github.com/wso2/carbon-kernel/blob/da05c14dda09db58954411f4c0b3fafc6ba34794/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L2992-L3080
[2] https://github.com/wso2/carbon-kernel/blob/da05c14dda09db58954411f4c0b3fafc6ba34794/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L2314-L2380

**Comment by rksk** [comment]
We have used UserCoreConstants.MAX_SEARCH_TIME as the default value for PROPERTY_MAX_USER_LIST in the above PR(s). Which needs to be updated with the correct constant.

**Comment by nilasini** [comment]
Reducing the severity level since the actual fix has been done

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
