### ISSUE TITLE
Add missing SCIM2 operations for Groups and Roles

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#11732]
**Is your suggestion related to a missing or misleading document? Please describe.**
Documentation for following SCIM2 operations is missing.

- PATCH Add/Remove/Replace Users to a Role
- PATCH Remove/Replace Groups to a Role
- PATCH Remove/Replace Members to a Group

**Describe the improvement**
Add the SCIM2 operations for the above cases.

**Version**
5.11.0

**Comment by Amlesh-NEC** [comment]
@sumedhe 

I would like to work on this issue. Could you please assign this issue to me?

**Comment by sumedhe** [comment]
Duplicate of #12127
