### ISSUE TITLE
Add unit tests for TypingDNA connector

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#11731]
**Is your suggestion related to an experience? Please describe.**

- Need to add unit tests for the TypingDNA [repo](https://github.com/wso2-extensions/identity-conditional-auth-typingdna). 

Effort BE::3

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
