### ISSUE TITLE
Issues encountered when creating OAuth app using Custom Application template with console

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#11755]
**Describe the issue:**
Encountered the below issues when trying to create an oauth app using the Custom Application template

- By default none of the grant types are selected (This could be an expected behaviour as it clearly shows an error if we try to update)
- Cannot create an application with Password and Refresh Grant selected (Browser trace shows 415 error)

**How to reproduce:**
- Try to create an oauth app with password and refresh grant in Custom Application template

**Comment by ChanikaRuchini** [comment]
Tested the flow with wso2is-5.12.0-alpha3. Works as expected.

https://user-images.githubusercontent.com/36252774/134151660-db7e6b3a-ddee-45a8-bc27-90335bf56ff2.mp4
