### ISSUE TITLE
[Doc] isMemberOfAnyOfGroups function definition is not added in docs

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#11756]
**Is your suggestion related to a missing or misleading document? Please describe.**

the definition of the `isMemberOfAnyOfGroups` conditional authentication JS function introduced with the PR https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/62 is not included in the latest "[Adaptive Authentication JS API Reference](https://github.com/wso2/docs-is/blob/master/en/docs/references/adaptive-authentication-js-api-reference.md)" documentation

**Comment by divyaamunugama** [comment]
Verified the updates in dev.
Closing the issue.
![image](https://user-images.githubusercontent.com/84217321/219260229-778af50d-45e4-429d-9285-16ec35a7b1fa.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
