### ISSUE TITLE
A sample using OpenSAML2 library is available in IS docs

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#11759]
From WSO2 IS 5.11.0, the OpenSAML version has been upgraded to OpenSAML3 from OpenSAML2 [1]. However, doc [2] contains a sample using OpenSAML2. Therefore a sample should be provided and tested using OpenSAML3.

[1] https://github.com/wso2/product-is/issues/8557
[2] https://is.docs.wso2.com/en/5.11.0/references/evolution-of-identity-federation-standards/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
