### ISSUE TITLE
[Doc] Verify the JS API references of conditional auth functions

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#11758]
Verify whether the JS API references of conditional auth functions are up to date.

Seems the parameter definitions of the `getCookieValue` and `setCookie` functions are incorrect
https://github.com/wso2/docs-is/blob/master/en/docs/references/adaptive-authentication-js-api-reference.md#getcookievaluerequest-name-properties

### Related issues
https://github.com/wso2/product-is/issues/11756

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
