### ISSUE TITLE
Update password expiry time documentation

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#11754]
Document [1] points to document [2] for enforcing password expiry time feature. The wording of the document [2] needs to be updated. Also the latest connector for IS 5.11 and 5.12 is not in the connector store.

[1] - https://is.docs.wso2.com/en/5.12.0/learn/password-expiry/
[2] - https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md

**Comment by SwatiNEC** [comment]
Hi @somindatommy 

Could you please elaborate on this issue as the required changes in document are not mentioned?

**Comment by somindatommy** [comment]
Our official documentation[1] points to [2] and some of the terms are not related to the latest IS.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
