### ISSUE TITLE
build failure in v1.0.72

### ISSUE THREAD

**Issue by yashwanth1796** [wso2/product-is#11768]
When I run npm run build 
getting the following issue

@wso2is/validation: > ..\..\node_modules\.bin\tsc -p tsconfig.json
@wso2is/theme: wso2-default.css generated.
@wso2is/theme: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
@wso2is/theme:     at Object.writeFileSync (fs.js:1460:5)
@wso2is/theme:     at writeFile (C:\Users\yashw\Desktop\identity-apps\modules\theme\scripts\build-theme.js:65:8)
@wso2is/theme:     at C:\Users\yashw\Desktop\identity-apps\modules\theme\scripts\build-theme.js:51:45
@wso2is/theme:     at Array.map (<anonymous>)
@wso2is/theme:     at C:\Users\yashw\Desktop\identity-apps\modules\theme\scripts\build-theme.js:51:32
@wso2is/theme:     at async Promise.all (index 0) {
@wso2is/theme:   code: 'ERR_INVALID_ARG_TYPE'
@wso2is/theme: }

Please suggest a solution

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
