### ISSUE TITLE
Unable to get local claims for the result from getUniqueUserWithClaimValues()

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11764]
**Describe the issue:**
The adaptive script function `getUniqueUserWithClaimValues()` is used to search for a user by providing a claim map. But it is not possible to get `localClaims` from the returned user object.
 
Sample adaptive authentication script.
```
var federatedUserName = context.currentKnownSubject.username;
var claimMap = {};
claimMap["http://wso2.org/claims/username"] = federatedUserName;
var mappedUser = getUniqueUserWithClaimValues(claimMap, context.tenantDomain);
if (mappedUser != null) {
    var isDisabled = mappedUser.localClaims["http://wso2.org/claims/identity/accountDisabled"];
}
```
 
It returns an NPE when trying to get the local claims through 'mappedUser.localClaims["http://wso2.org/claims/identity/accountDisabled"]'.

**Environment information** 
 - Product Version: IS 5.7.0

**Related issues**
As per @senthalan, this issue might be related to the fix done with https://github.com/wso2/product-is/issues/6079

**Comment by Thumimku** [comment]
Fixed in https://github.com/wso2/product-is/issues/11777
