### ISSUE TITLE
Need a way to zip and archive the log files in identity server

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#11761]
**Is your feature request related to a problem? Please describe.**
Currently, we perform the logging through log4j2. When we enable log types such as correlation it creates log files that has size upto 2GB depending on number of requests. Due to this machine IS is hosted gets its storage getting filled. We need a way to zip these files and archive them time to time.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
