### ISSUE TITLE
[Config]charon-config.xml is not templated

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11771]
**Is your suggestion related to an experience ? Please describe.**
Currently, we can't configure using deployment.toml file for the configs in `charon-config.xml `. 
That support is added in the scim side. https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/tree/master/features/org.wso2.carbon.identity.scim2.common.feature/resources. But it is not included in the product-is side.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
