### ISSUE TITLE
Skip current token from being revoked when updating the password

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11786]
**Is your suggestion related to an experience ? Please describe.**
In https://github.com/wso2/product-is/issues/9461, an improvement has been done to achieve the same. But it was referring to the user session and the access token bound to that session. Therefore, if the access token was generated using password grant, the token will still be revoked.

The proposed change will be,
1. At the REST API valve, currently we extract the sessionId and add it to the context. Now additionally we can store the tokenID of the accessToken presented as well in the context.
2. At the point of token revocation, instead of relying on sessionID set in context we use the tokenID from context to skip.

**Comment by nilasini** [comment]
@sumedhe Did we fix  this issue in master?

**Comment by sumedhe** [comment]
No. This is not added to the master.

**Comment by nilasini** [comment]
@sumedhe any specific reason to not to add in master?

**Comment by mefarazath** [comment]
> Therefore, if the access token was generated using password grant, the token will still be revoked.

@rksk isn't this the expected behaviour? 

Let's say when a user resets a password through a portal (X), the expectation of this feature was to skip revoking the session or token belonging to the logged in session of the X. All other tokens are expected to be revoked.

**Comment by rksk** [comment]
> > Therefore, if the access token was generated using password grant, the token will still be revoked.
> 
> @rksk isn't this the expected behaviour?
> 
> Let's say when a user resets a password through a portal (X), the expectation of this feature was to skip revoking the session or token belonging to the logged in session of the X. All other tokens are expected to be revoked.

Here, it is referring to first-party applications which are using the password grant. The requirement is to keep the user logged in to the application which initiates the password change though the user is logged out from other applications.
