### ISSUE TITLE
Improve the logic when cookie name is duplicated

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#11799]
**Describe the issue:**

In the [IdentityRequest.java](https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/inbound/IdentityRequest.java) file, `addCookie` method is updated to avoid the previous 500 server error when cookie names are the same. 

```
      public IdentityRequestBuilder addCookie(String name, Cookie value) {

            if (this.cookies.containsKey(name)) {
                // Temp-Fix: ignore the second value.
                return this;
            }
            this.cookies.put(name, value);
            return this;
        }
```

Latter we need to improve this logic to have multiple values and have respective components to select the relevant value among them.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
