### ISSUE TITLE
UUID returning in the Email OTP resend flow of the Password Reset flow

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#11792]
**Describe the issue:**
When resending the Email OTP for a password reset flow, the email is containing a UUID rather than a six character OTP. Please refer the screenshots attached below.

* First code when the admin forced the password reset.
<img src="https://user-images.githubusercontent.com/19262008/119259327-63bd6f80-bbeb-11eb-92e4-64c3f5e61b7c.png" width="400" height="300"></img>

* Second code when using a resend.
<img src="https://user-images.githubusercontent.com/19262008/119259495-37562300-bbec-11eb-8900-e5100f429bf3.png" width="400" height="300"></img>

**How to reproduce:**
1. Perform a `Password Reset via OTP` by following [1].
2. After receiving the email OTP then execute a resend flow from the following CURL.
```
curl --location --request POST 'https://localhost:9443/api/identity/user/v1.0/resend-code' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --header 'Content-Type: application/json' --data-raw '{
    "user": {
        "username": "<USERNAME>",
        "realm": "<USERSTORE_NAME>"
    },
    "properties": [
        {
            "key": "RecoveryScenario",
            "value": "ADMIN_FORCED_PASSWORD_RESET_VIA_OTP"
        }
    ]
}'
```

[1] https://is.docs.wso2.com/en/5.9.0/learn/forced-password-reset/#password-reset-via-otp

**Expected behavior:**
* Expecting a six character, shorter OTP.

**Environment information:**
 - Product Version: IS 5.12.0-m21
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by IsuraD** [comment]
Resending is not required for Admin initiated  Password Reset flow. Admin can re-initiate the force password reset flow instead of calling resending API.
