### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by MehradM** [wso2/product-is#11791]
Location : https://is.docs.wso2.com/en/latest/learn/user-managed-access-with-wso2-identity-server/
![Error](https://user-images.githubusercontent.com/52603836/119250471-8cc30d80-bbb5-11eb-9327-329a3c95986f.PNG)
![postman](https://user-images.githubusercontent.com/52603836/119250543-f8a57600-bbb5-11eb-9a08-c966606b0d71.PNG)
why do i get an internal server error

**Comment by dewniMW** [comment]
@MehradM were you able to resolve the aforementioned issue? If not can you provide the environment information and all the steps tried out in the UMA flow? Please also provide the backend error logs if there are any.
