### ISSUE TITLE
Doc Feedback: Can not access .net sample download url

### ISSUE THREAD

**Issue by MehradM** [wso2/product-is#11794]
Location : https://is.docs.wso2.com/en/latest/learn/logging-in-to-a-.net-application-using-the-identity-server/

![svn](https://user-images.githubusercontent.com/52603836/119304591-b5620a80-bc7c-11eb-8065-d89c2846d4bd.PNG)
![cant access](https://user-images.githubusercontent.com/52603836/119304602-ba26be80-bc7c-11eb-9caf-26da3ade0079.PNG)

**Comment by JKAUSHALYA** [comment]
We can use the sample provided here. https://github.com/asgardeo/asgardeo-dotnet-oidc-sdk/releases/tag/v0.1.1. 
Docs should be updated to point here. @gomathyk

**Comment by dewniMW** [comment]
The docs have been updated to refer to the new sample.
