### ISSUE TITLE
[Migration] Deprecating common introspection data provider enabling configuration

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#11806]
Upto IS 5.11, all the registered OAuth introspection data providers can be enabled/disabled with the following config. 
```
[oauth.grant_type.uma_ticket]
retrieve_uma_permission_info_through_introspection="true"
```
From 5.12.0-M18 onward, above configuration has been deprecated and **IntrospectionDataProviders** are registered as event listeners. Existing introspection data providers can be enabled using following configurations. 
```
[event.default_listener.is_introspection_data_provider]
enable=true

[event.default_listener.uma_introspection_data_provider]
enable=true
```
Related product issue : https://github.com/wso2/product-is/issues/11351
Doc improvement : https://github.com/wso2/docs-is/pull/2562

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
