### ISSUE TITLE
Doc Feedback: deployment.toml configuration need to update for MFA for Management console

### ISSUE THREAD

**Issue by nsivanoly** [wso2/product-is#11809]
Location : https://is.docs.wso2.com/en/5.11.0/learn/multi-factor-authentication-for-wso2-is-management-console/

Based on the github issues[1] the deployment.toml configuration has to be

[admin_console.authenticator.saml_sso_authenticator]
enable = true
login_page = "/carbon/admin/login.jsp"
assertion_consumer_service_url = "https://localhost:9443/acs"
identity_provider_sso_service_url = "https://localhost:9443/samlsso"

[1] https://github.com/wso2/product-is/issues/6691

**Comment by rksk** [comment]
`login_page` is not required since it is set in the `default.json`.
