### ISSUE TITLE
[Doc][5.10.0] Proper Resources are not Given for Writing a Custom Federated Authenticator

### ISSUE THREAD

**Issue by KasuniHemasika** [wso2/product-is#11816]
**Is your suggestion related to a missing or misleading document? Please describe.**

To get the sample source codes for building custom federated authenticators, the documents [1] & [2] still have references to the SVN repository which is no longer in use. 

And the pom file is not given for the custom-authenticator-for-facebook in the "Click here to view the source code" section in [1].

**Describe the improvement.**

- SVN links can be removed or the reference links to the source codes can be updated to link a working repository and the source codes should also be updated. 
- The pom file should be added in [1].

[1] - https://is.docs.wso2.com/en/5.10.0/develop/writing-a-custom-federated-authenticator/#custom-authenticator-for-facebook
[2] - https://is.docs.wso2.com/en/5.10.0/develop/writing-a-custom-federated-authenticator/#custom-authenticator-for-google

**Comment by dewniMW** [comment]
fixed with https://github.com/wso2/docs-is/pull/2745
