### ISSUE TITLE
Occurrence of primary key violations with persisted aggregation.

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-is#11818]
**Describe the issue:**
When the persisted aggregation is used instead of the default aggregation, the primary key violation was observed on top of the same dataset. 

Then the SQL query which was run on top of the persisted aggregation was observed and even with the SQL query, a similar primary key violation was observed.

**How to reproduce:**
This was reproducible on top of a specific dataset.

**Expected behavior:**
There should not be any primary key violations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-Analytics-5.8.0
 - OS: Mac

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
