### ISSUE TITLE
Back to first step in identifier first flow doesn't prompt other login options

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11812]
**Describe the issue:**

1. Configure a service provider with 
First step: Identifier First, and some other authenticators like Google, GitHub, etc
Second step: basic authenticator
(Note: The second step will be invoked only if Identifier First is selected as the first step. Need to handle in the adaptive script)
2. User initiates the login flow with identifier first, Enter the username and continue
3. Once the user is prompted for a password, click on the option to go back and change the account
4. The user will be prompted only identifier first option. Other login options won't be displayed

**Expected behavior:**
At step (4), the user should be directed to multi option login page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.12.0-m22
 - OS:Linux
 - Database:  H2
 - Userstore: LDAP

**Comment by RidmiR** [comment]
The issue is verifed and this is fixed.
