### ISSUE TITLE
Uable to setting up a Secondary User Store in Identity Server V5.11(Exception occurred while trying to invoke service method testRDBMSConnection)

### ISSUE THREAD

**Issue by Asifislam110** [wso2/product-is#11813]
I am unable to setup secondary user store JDBC. I am following the below tutorial 

https://shanikaw.medium.com/connecting-a-jdbc-mysql-user-store-as-a-secondary-user-store-for-wso2-identity-server-5-3-0-8bd17eb7d3bd and also doing WSO2 Identity Server Fundamentals - V5.11 Training.

MySql Version : 8.0.25

created userStore and run all database table script
Connector version : mysql-connector-java-8.0.25 copied in location (IS_HOME\5.11.0\repository\components\lib)

getting below error

Exception occurred while trying to invoke service method testRDBMSConnection

![image](https://user-images.githubusercontent.com/9161848/120072326-c1026680-c0ac-11eb-9a2d-773c138f0563.png)

**Comment by ruwanta** [comment]
What would the output on the logs related to this error ?

**Comment by Asifislam110** [comment]
@ruwanta thank you for you reply..

I try with different configuration , after uninstall MySQL Installer 8.0.25 and install MySQL Installer 5.7.34 try it with same configuration , working as expected.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
