### ISSUE TITLE
Multiple connections created when executing single flow

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#11820]
**Describe the issue:**
In the OIDC Auth Code grant with redirect flow in  updateRequestObjectReferenceCodeToToken method we create a new connection and in another method that being called under the above method( deleteRequestObjectReferenceforCode) we create another db connection. Due to this in a situation where db connections are limited in the pool this method occupies a high method execution time. Hence the initially created DB connection needs to be passed. 

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/dao/RequestObjectDAOImpl.java#L405

**Comment by senthalan** [comment]
Fixed with https://github.com/wso2/product-is/issues/11932
