### ISSUE TITLE
Slow performance in SCIM 2.0 PATCH /scim2/Groups/{{id}} endpoint

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11824]
The following property [1] was introduced to improve the SCIM Group Patch add operation.

`[scim2]`
`return_updated_group_in_group_patch_response=false`

With this configuration, we return an HTTP status code 204 instead of returning the entire resource in the response.

But still, there's a slowness while updating an Internal/ role. Even with the above configuration, the following SQL query is getting executed for each user in the group when a new user is added to the same group.

`SELECT UM_ATTR_NAME, UM_ATTR_VALUE FROM UM_USER_ATTRIBUTE, UM_USER WHERE UM_USER.UM_ID = UM_USER_ATTRIBUTE.UM_USER_ID AND UM_USER.UM_USER_ID=? AND UM_PROFILE_ID=? AND UM_USER_ATTRIBUTE.UM_TENANT_ID=? AND UM_USER.UM_TENANT_ID=?`

When the number of users in the Internal/ group is around 5000, adding a user to that group takes around 5 seconds (this is when the DB server and WSO2 IS resides in the same machine)

**Environment information**

Product Version: IS-KM:5.10.0 with a JDBC userstore.

[1] - https://github.com/wso2/product-is/issues/6918

**Comment by nilasini** [comment]
@sumedhe did we fix the issue in master?

**Comment by sumedhe** [comment]
Yes. This is already fixed in master. 
Ref: https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/280
