### ISSUE TITLE
Application sign-in methods allow to update without any authentication methods in the 1st step

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#11854]
**Describe the issue:**
When there are no authentication methods selected, it allows to click update button. Warn message says to remove the step, but it is not practical in the 1st step.

**Expected behavior:**
Disable "Update" button when there is only one authentication step and there are no authentication options selected in that step.

**Comment by RidmiR** [comment]
Verified and this is fixed.

**Comment by Rashmini** [comment]
> Verified and this is not fixed.

"Update" button was disabled when there are no authentication options selected in any authentication step.

**Comment by ShanikaWickramasinghe** [comment]
verified and this is fixed
