### ISSUE TITLE
Adding users to a group via SCIM2 does not work when PrimaryLoginIdentifier is different from the username claim

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11857]
**Describe the issue:**
With the config introduced in https://github.com/wso2/product-is/issues/10631, a specific claim can be configured as the `username` in SCIM2 responses. But if that username is used as the `display` attribute in a Group Patch request, the flow breaks. It is because  `display` value is being searched on the userstore against the http://wso2.org/claims/username yet. Ref [1].

**Environment information** 
 - Product Version: IS 5.10.0
 - Userstore: LDAP

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/067c9c7d81f6be35a7581a63832ef951d3ce02f3/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3573-L3577

**Comment by ChamathNS** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/364
