### ISSUE TITLE
Improvements for the SAML protocol section of the Console app

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#11859]
**The below changes should be made to the protocol section of the SAML application**

- [x] **Issuer** field
1. Hint should be improved.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120489008-e6f17900-c3d4-11eb-838b-ebf7343d805b.png)
Suggested : 
`This specifies the unique identifier of the application. This is also the _issuer_ value specified in the SAML authentication request issued by the application.`

- [x] **Assertion Consumer URLs** field
1. Should be renamed as `Assertion consumer service URLs`
2. Hint should be improved.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120490018-b100c480-c3d5-11eb-8e81-6c47a18f8f23.png)
Suggested : 
`The Assertion Consumer Service (ACS) URL determines where to send the SAML response.`

- [x] **Default assertion consumer URL** field
1. Should be renamed as `Default assertion consumer service URL` 
2. Hint should be improved.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120490646-37b5a180-c3d6-11eb-8fc7-7d932840792c.png)
Suggested : 
`If you have configured multiple ACS URLs, you must configure one as the default. In case a SAML request from your application does not specify the ACS URL, the response is sent to this URL.`

- [x] **Idp entityId alias** field
1. Should be renamed as `IdP entity ID alias` 
2. Hint should be improved.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120490666-3b492880-c3d6-11eb-8ed9-4cf4f250d022.png)
Suggested : 
`This value can override the default Identity Provider (IdP) entity ID (localhost). The IdP entity ID is used as the saml2:Issuer of the SAML response that is generated by WSO2 Identity Server.`

- [x] **Request Validation**
1. Change the hint
Current : 
![image](https://user-images.githubusercontent.com/25479743/120747281-62127680-c51e-11eb-8e70-8968f767f9c3.png)
Suggested : 
`This specifies whether WSO2 Identity Server must validate the signature of the SAML authentication request and the SAML logout request that are sent by the application.`

- [x] **Assertion/Response Signing** sub section
1. Rename **Assertion/Response Signing** to **Response Signing**
2. Bring **Sign SAML responses** checkbox to the top of the sub section.
3. Hint of **Sign SAML responses** should be improved.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120492422-b2cb8780-c3d7-11eb-993e-2e7aef78ff80.png)
Suggested : 
`This specifies whether the SAML responses generated by WSO2 Identity Server should be signed.`
4. If **Sign SAML responses** checkbox is not checked, disable editing the **Digest algorithm** and **Signing algorithm** sections.

- [x] **Single SignOn Profile** sub section
1. Rename **Single SignOn Profile** to **Single Sign-On Profile**
2. Hint of **Bindings** should be improved.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120492749-f4f4c900-c3d7-11eb-9289-6f5d70422113.png)
Suggested : 
`This specifies the mechanisms to transport SAML messages in communication protocols.`
3. If **Artifact** checkbox under **Bindings** is not checked, disable editing the **Enable signature validation for artifact binding** checkbox.
4. Hint of **Enable signature validation for artifact binding** should be changed.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120494333-59645800-c3d9-11eb-8cfe-f76eca3019f7.png)
Suggested : `This specifies whether the artifact resolve request signature should be validated against the application certificate. If you enable this option, make sure to provide the application certificate below.`
5. **Enable idP initiated SSO** should be renamed as **Enable IdP initiated SSO** and add a hint to it.
Suggested : 
`This specifies whether to initiate Single Sign-On (SSO) from the IdP instead of the application.`

- [x] Make **Assertion** a sub-section similar to Single SignOn Profile` sub-section and add subsequent fields under it.
1. Hint of **Name ID format** should be changed.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120603236-6cbf0400-c469-11eb-8d2a-4fbe55b7d9d3.png)
Suggested : 
`This specifies the name identifier format that is used to exchange information regarding the user in the SAML assertion`
2. Hint of **Audience** should be changed (Rename **Audience**  to **Audiences** ).
Current : 
![image](https://user-images.githubusercontent.com/25479743/120494481-7c8f0780-c3d9-11eb-877d-7fdc38cc0556.png)
Suggested : 
`This specifies the audiences of the SAML assertion. The issuer of the application will be added as the default audience.`
3. Hint of **Recipients** should be changed.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120494584-90d30480-c3d9-11eb-8b2c-43857dfc0c53.png)
`This specifies recipients of the SAML assertion`
4. Remove **Encryption** heading
5. Rename **Enable** under **Encryption** to **Enable encryption**

- [x] *Attribute Profile*
Even though we enable user attributes in the attributes tab, those information will not be sent to the SAML application unless we enable the attribute profile and tick `Always include attributes in response`. This is an additional overhead that is not in the OIDC flow.)
1. Aggregate **Enable** and **Always include attributes in response** into one field named **Enable attribute profile** and make in enabled by default.
2. Change hint of new  **Enable attribute profile** field:
Current : 
![image](https://user-images.githubusercontent.com/25479743/120745669-43f74700-c51b-11eb-95d3-542e911c762a.png)
Suggested : 
`This specifies whether to include the user’s attributes in the SAML assertions as part of the attribute statement.`

- [x] **Single Logout Profile** subsection
1. Rename **Single Logout Profile** checkbox label to **Enable SLO**.
Hint : `This specifies whether the application supports Single Logout (SLO) profile`
2. Add a hint for **Single logout response URL**
Suggested : `This specifies the endpoint of the application to where the single logout response should be sent. If you do not specify this URL, WSO2 Identity Server will use the ACS URL.`
3. Add a hint for **Single logout request URL**
Suggested : `This specifies the endpoint of the application to where the single logout request should be sent. If you do not specify this URL, WSO2 Identity Server will use the ACS URL`
4. Rename **Idp Initiated SingleLogout** to **IdP initiated single logout** and change the existing hint.
Current : 
![image](https://user-images.githubusercontent.com/25479743/120584210-278cd900-c44d-11eb-83b4-9c97a19764cd.png)
Suggested : 
`This specifies whether the application supports IdP initiated logout.`
5. Add a hint for **Return to URLs**
Suggested : `This specifies the URLs to which the user should be redirected after the logout.`

- [x] Change all `SAML2` references to `SAML`

**Comment by RidmiR** [comment]
This is verified in stage build and all the suggestion are added.
