### ISSUE TITLE
Deprecate LDAP based multi attribute login

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#11863]
Deprecate LDAP based multi attribute login in favour of new multi attribute login implementation.

**Comment by nilasini** [comment]
For 5.12.0 we should deprecate the LDAP based multi attribute login through documentation [1]

[1] https://is.docs.wso2.com/en/5.12.0/learn/managing-user-attributes/#authentication-using-multiple-attributes

**Comment by nilminiwso2** [comment]
Updated with: https://github.com/wso2/docs-is/pull/3278/files
