### ISSUE TITLE
Adaptive script for API based authentication flows

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11875]
**Is your feature request related to a problem? Please describe.**
Currently, the adaptive script gets involved only in the browse-based authentication flows. It's nice to have a solution similar to the adaptive script in API based authentication flows such as OAuth password grant and [Authentication APIs](https://docs.wso2.com/display/IS510/apidocs/Authentication-framework-apis/#!/operations#Authenticate#authenticatePost)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
