### ISSUE TITLE
Improvements to API docs

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#11884]
While working on the docs restructuring effort several issues were found out with API docs.

The following APIs are still in confluence docs and they need to be converted to Swagger-UI 

- /develop/apis/use-the-account-recovery-rest-apis/
- /develop/apis/use-the-authentication-rest-apis/
- /develop/apis/use-the-configuration-management-rest-apis/
- /develop/apis/use-the-consent-management-rest-apis/
- /develop/apis/use-the-openid-connect-dynamic-client-registration-rest-apis/
- /develop/apis/use-the-personal-information-export-rest-apis/
- /develop/apis/use-the-self-sign-up-rest-apis/

The following APIs don't have a postman collection

- /develop/apis/use-the-account-recovery-rest-apis/
- /develop/apis/use-the-authentication-rest-apis/
- /develop/apis/use-the-configuration-management-rest-apis/
- /develop/apis/use-the-consent-management-rest-apis/
- /develop/apis/entitlement-with-rest-apis/
- /develop/apis/use-the-openid-connect-dynamic-client-registration-rest-apis/
- /develop/apis/permission-management-rest-api/
- /develop/apis/use-the-personal-information-export-rest-apis/
- /develop/apis/scim2-rest-apis/ (a collection is found in https://github.com/darshanasbg/postman-collections/blob/master/scim2.postman_collection.json)
- /develop/apis/use-the-self-sign-up-rest-apis/
- /develop/apis/totp-rest-api/
- /develop/apis/workflow-engine-rest-api/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
