### ISSUE TITLE
scim2 users filtering by groups doesn't honor startIndex and count

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11889]
**Describe the issue:**
SCIM2 users filtering by groups doesn't honor startIndex and count parameters. It's returning all the matching users in the response without considering count and startIndex.

**How to reproduce:**
- Get updated IS-5.10.0 pack.
- Create multiple users and groups to check the filtering operation.
- Perform the following filtering operation.
<pre style="color:#000020;background:#f6f8ff;">curl <span style="color:#308080; ">-</span>X GET \
  <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">'https://localhost:9443/scim2/Users?count=2&amp;startIndex=5&amp;domain=Primary&amp;filter=groups+co+test_role'</span> \
  <span style="color:#308080; ">-</span>H <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">'Authorization: Basic YWRtaW46YWRtaW4='</span> \
</pre>
- Even though it should limit to the defined count, it's returing all the users in the response.

**Expected behavior:**
In the SCIM response, users should limit to the defined count in the query param.

**Environment information**  **:**
 - Product Version: [IS 5.10.0]

**Comment by ChamathNS** [comment]
Addressed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/364
