### ISSUE TITLE
scim2/Groups/{group_id}/permissions API throws 500 error, when assigning admin privileges to a role by non-super admin users

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#11887]
**Describe the issue:**

In WSO2 IS, only the super admin (mentioned in deployment.toml/user-mgt.xml) is allowed to create roles or assign roles to users with the root level permissions (Root "/permission", admin "/permission/admin" or super-admin "/permission/protected"). This is working as expected. 

But when we try to assign root level permissions to a role using a non-super admin user, it's throwing a 500 error as below.

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#595979; ">{</span>
<span style="color:#595979; ">&nbsp;&nbsp;&nbsp;&nbsp;"schemas": [</span>
<span style="color:#595979; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"urn:ietf:params:scim:api:messages:2.0:Error"</span>
<span style="color:#595979; ">&nbsp;&nbsp;&nbsp;&nbsp;],</span>
<span style="color:#595979; ">&nbsp;&nbsp;&nbsp;&nbsp;"detail": "Error occurred when getting the permissions from server",</span>
<span style="color:#595979; ">&nbsp;&nbsp;&nbsp;&nbsp;"status": "500"</span>
<span style="color:#595979; ">}</span>
</pre>

**How to reproduce:**

- Get an IS-5.10.0 pack.
- Create a group using SCIM.
<pre style="color:#000020;background:#f6f8ff;">curl <span style="color:#308080; ">-</span>v <span style="color:#308080; ">-</span>k <span style="color:#308080; ">-</span><span style="color:#308080; ">-</span>user admin<span style="color:#406080; ">:</span>admin <span style="color:#308080; ">-</span><span style="color:#308080; ">-</span>data <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">'{"displayName":"manager"}'</span> <span style="color:#308080; ">-</span><span style="color:#308080; ">-</span>header <span style="color:#800000; ">"</span><span style="color:#1060b6; ">Content-Type:application/json</span><span style="color:#800000; ">"</span> https<span style="color:#406080; ">:</span><span style="color:#595979; ">//localhost:9443/scim2/Groups</span>
</pre>
- Assing root level permissions to the above-created group as below using a non-super admin user.
<pre style="color:#000020;background:#f6f8ff;">curl <span style="color:#308080; ">-</span>X PUT \
<span style="color:#e34adc; ">&nbsp;&nbsp;https:</span><span style="color:#595979; ">//localhost:9443/scim2/Groups/8ddd9922-680b-45a2-8aca-faada3213d28/permissions \</span>
  <span style="color:#308080; ">-</span>H <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">'Authorization: Basic aXN1cnU6aXN1cnU='</span> \
  <span style="color:#308080; ">-</span>H <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">'Content-Type: application/json'</span> \
  <span style="color:#308080; ">-</span>d <span style="color:#ffffff; background:#dd9999; font-weight:bold; font-style:italic; ">'["/permission/protected"]'</span>
</pre>
- Instead of 500 error code it should throw a meaningful error code.

**Expected behavior:**
It should throw an error with a meaningful error code.

**Environment information****:**
 - Product Version: [IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
