### ISSUE TITLE
ID Token need to be signed before encryption

### ISSUE THREAD

**Issue by hasithakn** [wso2/product-is#11901]
### Problem Statement

- Based on [OpenID](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) spec, It's stated that, "If the ID Token is encrypted, it MUST be signed then encrypted, with the result being a Nested JWT, as defined in JWT."
- The problem is our current implementation does not sign the id token before encryption.
- And regards to selecting the encryption key from jwks url, we need to check the use = 'enc' jwk from jwks to encrypt the id token and, need to send the 'kid' of that key as a header parameter of encrypted id token ( [ietf](https://datatracker.ietf.org/doc/html/rfc7516#section-4.1.6) )

### Possible Solution

- Application will sign the id token before encryption from the server public key/certificate
- Signed id token then will encrypt using use = 'enc' jwk from jwks url. (this is for scenarios where jwks is configured in application)

**Comment by nilasini** [comment]
Tracking migration impacts through https://github.com/wso2/product-is/issues/13367
