### ISSUE TITLE
Issues in the Console Application's `user attribute` section

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#11912]
**Describe the issue:**
The following issues are identified in the user attribute section of the console's Application section.

- [ ] Button "Add user Attribute" not getting loaded when removing all the added attribute at SAML application.

![Selection_999(1874)](https://user-images.githubusercontent.com/39077751/121220155-fde70e00-c8a1-11eb-92cc-57c9a779bfa2.png)

https://user-images.githubusercontent.com/39077751/121219410-48b45600-c8a1-11eb-8e77-95560e2d792e.mp4

- [ ] Cannot delete mapped application attribute

https://user-images.githubusercontent.com/39077751/121245035-2fb99e00-c8bd-11eb-8805-35ff96d60d95.mp4

- [ ] Unable to select subject attribute when attribute mappings are available in SAML 2
![image](https://user-images.githubusercontent.com/5061791/120608537-eb6a7000-c46e-11eb-93e9-392b8e4f192c.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
