### ISSUE TITLE
Identity Provider listing API should support filter by category

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#11913]
**Is your suggestion related to an experience ? Please describe.**
ATM, there is no way to filter out the IDPs by their category. This is a required feature for the Console's sign-in methods view.

<img width="783" alt="Screen Shot 2021-06-11 at 9 05 56 PM" src="https://user-images.githubusercontent.com/25959096/121712016-d9d13a00-caf8-11eb-8448-78d5c0c6c87c.png">

**Describe the improvement**
Identity Provider listing API should support filtering the items by categories such as `Social`, `Multi-Factor` etc.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
