### ISSUE TITLE
SCIM2 user search should return case sensitive user names as well

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#11915]
**Describe the issue:**

Currently, when we search for a user using the **/scim2/User/.search** endpoint and we have existing users in the user store with mixed-case user names (e.g. John.Doe@test.com) the search comes back with no result, but the user exits in DB (see attachment, fig. 1):

![image](https://user-images.githubusercontent.com/2381693/121742708-70800580-cabd-11eb-8370-523f406c4256.png)

**How to reproduce:**

1. Create a user with user name in 'sentence' case (e.g. John.Doe@test.com)
2. Run a SCIM2 search (_<http_host>/scim2/Users/.search)_ using the following request body:

`{
   "schemas":[
      "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
   ],
   "attributes":[
      "userName"
   ],
   "filter":"userName eq John.Doe@test.com",
	 "startIndex": 0,
    "count": 10
}`

**Expected behavior:**

Search should result in one match (see attachment, fig. 2)

**Environment information:**
 - Product Version: IS 5.10.0, WUM level: 1616678320867
 - Userstore: Postgres

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
