### ISSUE TITLE
Improve LDAP - doUpdateRoleListOfUserWithID - add roles to user method when roles are in sub directory.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#11925]
**Describe the issue:**
Parent Issue : https://github.com/wso2/product-is/issues/11776

**Issue - Todo**

- We isolate the parent issue and added a fix via https://github.com/wso2/carbon-kernel/pull/2993
- But it seems for the method in $sub we need an additional check to resolve the probem.
- This issue to track the sub-issue and fix in near future.

**Reason we are postponing the fix**

- With current impl the groupResults from LDAP search should have any results (Roles yet to be assigned), so we can get the search result since its null and get the sub dir

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
