### ISSUE TITLE
Wso2-is : Error Eager Loading

### ISSUE THREAD

**Issue by marcoranica94** [wso2/product-is#11926]
**Describe the issue:**

I have a tenant called **test.com** , i would like the tenant to be a eager.
I followed this guide https://is.docs.wso2.com/en/latest/administer/configuring-the-tenant-loading-policy/#!
I did two test in deployment.toml
 
1.  `[tenant_mgt]
eager_loading_tenants = "*"`

2. `[tenant_mgt]
eager_loading_tenants = "test.com"`

**How to reproduce:**

1. Start wso2 
2. Do a login with tenant 
3. I let 30 minutes pass ( default time)
4. The following is logged:

`[2021-06-15 14:42:09,140] [] INFO {org.wso2.carbon.bpel.core.Axis2ConfigurationContextObserverImpl} - Unloading TenantProcessStore for tenant 2.
[2021-06-15 14:42:09,142] [] INFO {org.wso2.carbon.humantask.core.Axis2ConfigurationContextObserverImpl} - Unloading TenantTaskStore for tenant 2.
[2021-06-15 14:42:09,146] [] INFO {org.wso2.carbon.core.multitenancy.utils.TenantAxisUtils} - Cleaned up tenant test.com`

**Expected behavior:**
I expect the tenant to not expire.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.11.0]
 - OS: [Linux]
 - Database: [Postgres]

Thanks a lot

**Comment by ruwanta** [comment]
This seems a carry forward from old Carbon Servers. IS no longer requires this distinction of lazy vs eager loading the tenants.
Need to fix the documentation.

@marcolin94 , the info message is harmless. Your requests should be served immediately without any noticeable delay, except any cache misses due to LRU cache algorithm, which makes some DB reads to refresh cache.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
