### ISSUE TITLE
One NPE in ApplicationIdentityProviderMgtListener

### ISSUE THREAD

**Issue by containerAnalyzer** [wso2/product-is#11929]
Hello,
Our static analyzer found a following potential NPE in **carbon-identity-framework**. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.
Here is the bug trace.

1. Return **null** to caller [Code Link](https://github.com/wso2/carbon-identity-framework/blob/f2221c4b2cf5ba93931af1527ecf8eb6224e3411/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/ApplicationDAO.java#L165)
![image](https://user-images.githubusercontent.com/85693199/122152578-181d7f00-ce94-11eb-9917-9ca2e07576ea.png)

2. Function **getApplicationByResourceId** executes and stores the return value to **serviceProvider** (**serviceProvider** can be **null**) [Code Link](https://github.com/wso2/carbon-identity-framework/blob/f2221c4b2cf5ba93931af1527ecf8eb6224e3411/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationIdentityProviderMgtListener.java#L71)
![image](https://user-images.githubusercontent.com/85693199/122152755-54e97600-ce94-11eb-9352-db0fa5b05e08.png)

3. Function **add** executes and returns [Code Link](https://github.com/wso2/carbon-identity-framework/blob/f2221c4b2cf5ba93931af1527ecf8eb6224e3411/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationIdentityProviderMgtListener.java#L72)
![image](https://user-images.githubusercontent.com/85693199/122152858-777b8f00-ce94-11eb-927a-3fd5a085bd46.png)

4. Function **next** executes and stores the return value to **serviceProvider** (**serviceProvider** can be **null**) [Code Link](https://github.com/wso2/carbon-identity-framework/blob/f2221c4b2cf5ba93931af1527ecf8eb6224e3411/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationIdentityProviderMgtListener.java#L75)
![image](https://user-images.githubusercontent.com/85693199/122152908-8d894f80-ce94-11eb-8b03-7cb687c93199.png)

5. **serviceProvider** is passed as the **this** pointer to function **getLocalAndOutBoundAuthenticationConfig** (**serviceProvider** can be **null**), which will lead to null pointer dereference [Code Link](https://github.com/wso2/carbon-identity-framework/blob/f2221c4b2cf5ba93931af1527ecf8eb6224e3411/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationIdentityProviderMgtListener.java#L78)
![image](https://user-images.githubusercontent.com/85693199/122152972-aa258780-ce94-11eb-9b8a-05172ea343bf.png)

Commit: f2221c4b2cf5ba93931af1527ecf8eb6224e3411

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
