### ISSUE TITLE
CAS Inbound authenticator is not supported with a tenant user

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#11924]
**Is your suggestion related to an experience ? Please describe.**

- CAS inbound authenticator[1] only supports with super tenant. It is not supported with a tenant user.
- It's need to move identity-inbound-auth-cas Caches to the tenant space as well.

[1] https://github.com/wso2-extensions/identity-inbound-auth-cas

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
