### ISSUE TITLE
X509 authenticator does not support tenant-qualified URLs

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#11934]
**Is your suggestion related to an experience ? Please describe.**

- X509 authenticator does not support tenant-qualified URLs.[1]
- It's need to move CRLCache in identity-x509-commons[2] to the tenant space as well.

[1] https://github.com/wso2/product-is/issues/11408
[2] https://github.com/wso2-extensions/identity-x509-commons

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
