### ISSUE TITLE
Empty roles returned with ReturnOnlyMappedLocalRolesUnmappedExclusive when no role mappings defined

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11941]
**Steps to reproduce**
- Setup federated IDP setup with the following config added to the identity.xml file of the local IS.
```
<FederatedRoleManagement>
    <ReturnOnlyMappedLocalRoles>true</ReturnOnlyMappedLocalRoles>
    <ReturnOnlyMappedLocalRolesUnmappedExclusive>true</ReturnOnlyMappedLocalRolesUnmappedExclusive>
</FederatedRoleManagement>
```

**Describe the issue:**
Assume the IDP is having the following role mappings configured.
1. `role1` : `LocalRole1`
2. `role2` : `LocalRole2`

With the above role mappings,
1. `ReturnOnlyMappedLocalRoles`: Only the mapped roles will be returned to the SP. If matched roles are not found, **all the roles will be returned**.
    - If `role1` and `role3` are returned from the IDP, `LocalRole1` will be returned to the SP.
    - If `role3` and `role4` are returned from the IDP, `role3` and `role4` will be returned to the SP, since no matching roles are found.
2. `ReturnOnlyMappedLocalRoles` and `ReturnOnlyMappedLocalRolesUnmappedExclusive`: Only the mapped roles will be returned to the SP. If matched roles are not found, **none of the roles will be returned**.
    - If `role1` and `role3` are returned from the IDP, `LocalRole1` will be returned to the SP.
    - If `role3` and `role4` are returned from the IDP, none of the roles will be returned to the SP.

However, whilst the `ReturnOnlyMappedLocalRoles` and `ReturnOnlyMappedLocalRolesUnmappedExclusive` are in place, if **no role mappings are defined at all** in the IDP, it returns an empty role set to the SP.

**Expected behavior:**
When `ReturnOnlyMappedLocalRoles` and `ReturnOnlyMappedLocalRolesUnmappedExclusive` are defined and if the IDP is not having any role mappings, all the roles should be returned.

**Comment by nilasini** [comment]
@vihanga-liyanage can we close this issue?
