### ISSUE TITLE
Add support to convert Javascript regexes to Java 

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#11942]
**Is your suggestion related to an experience ? Please describe.**
In the user store section of the Console, we are hoping to expose only the Javascript regexes for the users to update which will require converting Javascript regexes to Java.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
