### ISSUE TITLE
Expose only front end regexes in the user store section

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#11943]
**Is your suggestion related to an experience ? Please describe.**
In the current implementation of the user store section of the console, we allow the users to update both Javascript and Java regexes. Since the users are not required to update the back-end regexes we should remove the option to update the Java regexes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
