### ISSUE TITLE
SCIM 2.0 User creation gives internal server error when approval workflows are associated

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#11949]
**Describe the issue:**
When creating users using 
https://localhost:9443/scim2/Users SCIM2.0 endpoint, it gave me an internal server error. 
At this time I had associated user creation approval workflow. 
When I check the Management console I can see the user is created with Approval workflow icon.

After I disable the approval workflow only,  I can execute the endpoint and create new users. 
I know the user created status code 201 is not the correct response when the user is in the pending stage. But we need to add another status code for the users who is in approval stage

**How to reproduce:**
Add user creation workflow definition with an approval step. and engage that workflow. here the workflow engine is embedded BPS. 
[1] https://is.docs.wso2.com/en/latest/learn/adding-a-new-workflow-definition/
[2] https://is.docs.wso2.com/en/latest/learn/engaging-a-workflow-in-an-operation/

Create a user using SCIM 2.0 POST Users operation

**Expected behavior:**
A response message with proper status code ( not 500-internal server error, not 201- created)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
 - OS:  Mac
 - Database:  embedded LDAP
 - Userstore:  embedded LDAP

---

**Suggested labels:**
SCIM 
User Onboarding
workflows

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
