### ISSUE TITLE
Unnecessary API calls in console

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#11946]
Unnecessary API calls noticed in console

Groups page
<img width="1673" alt="Screenshot 2021-06-18 at 11 50 18 AM" src="https://user-images.githubusercontent.com/1332991/122515969-cf98c980-d02b-11eb-9089-aa78dd401ab4.png">

Users page
<img width="1673" alt="Screenshot 2021-06-18 at 11 50 46 AM" src="https://user-images.githubusercontent.com/1332991/122515983-d3c4e700-d02b-11eb-8ed7-7e3e3cc1decf.png">

Roles page
<img width="1673" alt="Screenshot 2021-06-18 at 11 51 03 AM" src="https://user-images.githubusercontent.com/1332991/122516000-d7f10480-d02b-11eb-8510-dae25948da59.png">

**Comment by pavinduLakshan** [comment]
No longer reproducible.
