### ISSUE TITLE
Can't login as admin upon using an external JDBC user store (azure postgres).

### ISSUE THREAD

**Issue by sid-tm** [wso2/product-is#11971]
**Describe the issue:**

I am using wso2is-5.11.0. Here is my deployment.toml -
....
[bps_database.config]
url="jdbc:postgresql://postgreiamstage.postgres.database.azure.com:5432/0?sslmode=require" 
username = "e"
password = "C1"
driver = "org.postgresql.Driver"
...........
[user_store]
type = "database_unique_id"
user_name_attribute = "mail"
user_name_search_filter = "(&amp;(objectClass=person)(mail=?))"
user_name_list_filter = "(&amp;(objectClass=person)(!(sn=Service)))"
username_java_script_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
username_java_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'
TenantManager="org.wso2.carbon.user.core.tenant.JDBCTenantManager"
ReadOnly=false
ReadGroups=true
WriteGroups=true

[user_store.properties]
TenantManager = "org.wso2.carbon.user.core.tenant.JDBCTenantManager"
data_source = "WSO2USER_DB"
Disabled = false
MaxUserNameListLength = 100
MaxRoleNameListLength = 100
UserRolesCacheEnabled = true
PasswordDigest = "SHA-256"
ReadOnly = false
IsEmailUserName = true
DomainCalculation = "default"
StoreSaltedPassword = true
SCIMEnabled = true

[database.user]
type = "postgre"
url="jdbc:postgresql://p:432/1?sslmode=require" 
username = "postgre@postgreiamstage"
password = "C1"
driver = "org.postgresql.Driver"

[realm_manager]
data_source = "WSO2USER_DB"

[database.identity_db]
type = "postgre"
url="jdbc:postgresql://em:5432?sslmode=require" 
username = "@"
password = "C1"
driver = "org.postgresql.Driver"

[database.shared_db]
type = "postgre"
url="jdbc:postgresql://e:5432?sslmode=require" 
username = "e"
password = "C1"
driver = "org.postgresql.Driver"

[[datasource]]
id="WSO2CONSENT_DB"
url="jdbc:postgresql://e:5432?sslmode=require" 
username = "e"
password = "C1"
driver = "org.postgresql.Driver"
jmx_enable=false

**How to reproduce:**

Download the deployment.toml. And restart wso2 using this copy of deployment.toml
**Expected behavior:**

admin should be able to login to management console, using admin/admin
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - OS: [Linux]
 - Database: [Postgres]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

https://github.com/wso2/product-is/issues/9655
**Suggested labels:**

**Comment by ruwanta** [comment]
@starkx-24 , above file seems to contain some data related to you. I advice to remove the sensitive details, and change your credentials.

**Comment by starkx-24** [comment]
Hi. Thanks. The credentials were already changed

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
