### ISSUE TITLE
The migration to tenanted session feature

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#11973]
The tenanted session added to 5.12.0 with https://github.com/wso2/product-is/issues/8975. This feature is not available in the older versions.

If an existing customer wants to migrate to 5.12.0 and enable the tenanted session, we need to think through how to migrate the sessions to the tenanted path.

**Comment by IsuraD** [comment]
@senthalan Do we need this migration?  If the tenanted sessions are enabled, users have to reauthenticate. That should be fine IMO

**Comment by senthalan** [comment]
> @senthalan Do we need this migration? If the tenanted sessions are enabled, users have to reauthenticate. That should be fine IMO

yes, the users have to reauthenticate. But the issue will be we need to clear out the existing commonauthId cookie somehow. Let me explain why

We will have the existing commonauthId cookie (let's say cookie-A) in the root path when the authentication request goes to /t/<tenant-domain> cookie-A will be also sent. Then in the server, we will validate this cookie, which will be invalid (As we cleared the session tables), So the server will create a new session and add a new commonauthId cookie cookie-B to /t/<tenant-domain>. But here we won't be clearing the cookie-A. So after the user is authenticated, there will be two cookies. One cookie-A in root path and cookie-B in the /t/<tenant-domain> path. 

Then when the next authentication request sends to the server, that request will have both these cookies. Then depending on the cookie order, the server may pick cookie-A. If so, the SSO won't work. 

As a solution, we can have a new name for the commonauthId cookie (let's say commonauthId-v2) when the tenanted session is enabled. And forcefully delete the commonauthId cookie. The idea is commonauthId will be always non-tenanted (persisted in the root path) and  commonauthId-v2 will be in the tenanted (persisted in the tenanted path)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
