### ISSUE TITLE
doSignAssertions property is not populating with rest API service provider creation

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#11974]
**Describe the issue:**
doSignAssertions property of SAML2ServiceProvider is not populating in the apply method of ApiModelToSAMLSSOServiceProvider class(org.wso2.carbon.identity.api.server.application.management.v1.core.functions.application.inbound.saml) with rest API service provider creation. It is populating when SP is created through management console.

**How to reproduce:**
Create a SAML SP using this API (https://localhost:9443/t/carbon.super/api/server/v1/applications) endpoint. And check the doSignAssertions property value is set to false in the registry for particular SP. 

**Expected behavior:**
When creating SAML SP using REST API, doSignAssertions property value should be set to true in the registry.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by ChamathNS** [comment]
This issue is not reproducible in 5.12.0-M27
