### ISSUE TITLE
Invalid userstore domain identified in identifier first flow

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11977]
**Describe the issue:**
In the IdentifierFirst flow, it picks the invalid userstore domain from [`UserCoreUtil.getDomainFromThreadLocal()`](https://github.com/wso2-extensions/identity-local-auth-basicauth/blob/v6.3.0/components/org.wso2.carbon.identity.application.authentication.handler.identifier/src/main/java/org/wso2/carbon/identity/application/authentication/handler/identifier/IdentifierHandler.java#L360) (ThreadLocal) (The userstore domain of the previous user will be picked as it's not cleared).

**How to reproduce:**
1. Configure Identifier First as the first step and Basic as the second step.
2. Configure maxThreads to 2.
    ```
    [transport.https.properties]
    maxThreads = 2
    ```
3. Authenticate using the user who resides on a secondary userstore.
4. Authenticate using the user who resides in the primary userstore - This will be identified as the secondary userstore.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by ChamathNS** [comment]
This issue is not reproducible in the wso2is-5.12 M29
