### ISSUE TITLE
Picking UserStore Type in UI as LDAP even it is a JDBC secondary JDBC user store - IS 5.11.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-is#11982]
**Describe the issue:**

When migrating from IS 5.3.0 to IS 5.11.0, we can copy the JDBC secondary user store file from old to new environment and use it. In old version JDBC userstore class is "org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager" and IS 5.11.0 is using "org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager". 
If we copied that old JDBC secondary user store manager XML file in the IS 5.11.0, it is deploying successfully. However, if we update this through the UI, it failed to deploy and throw the below error.
```
[2021-06-20 20:05:12,089] [] ERROR {org.wso2.carbon.user.core.config.XMLProcessorUtils} - Required mandatory property ConnectionURL is not defined!
[2021-06-20 20:05:12,089] [] DEBUG {org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor} - Error while building user store manager from file org.wso2.carbon.user.core.UserStoreException: A required mandatory field is missing.
	at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.buildUserStoreConfiguration(UserStoreConfigXMLProcessor.java:178)
DEBUG {org.wso2.carbon.user.core.common.UserStoreDeploymentManager} - The deployment of test.xml is not valid. org.wso2.carbon.user.core.UserStoreException: Error while building user store manager from file
	at org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor.buildUserStoreConfigurationFromFile(UserStoreConfigXMLProcessor.java:148)
:
Caused by: org.wso2.carbon.user.core.UserStoreException: A required mandatory field is missing.

```
Reason is, in IS 5.11.0 doesn’t exist that "org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager" in the user store type list and by default it is picking the "org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager". Therefore the user store XML also update with that value and above error has thrown. 

**How to reproduce:**

1. copy a JDBC secondary user store file that used "org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager" to the IS 5.11.0 pack.
2. Start the server
3. Go to the carbon console and try to edit the secondary user store and update it. 
4. Then the error will recreate.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by vihanga-liyanage** [comment]
We can use the below config to mitigate this.

```
[user_store_mgt]
allowed_user_stores = [
	"org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager",
	"org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager",
	"org.wso2.carbon.user.core.ldap.UniqueIDActiveDirectoryUserStoreManager",
	"org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager",
	"org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager"
]
```
