### ISSUE TITLE
UsernameJavaRegEx is not considered when adding the super admin

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11981]
**Describe the issue:**
The super admin creation bypasses the username validation. Hence this could run into unexpected issues if the admin username was misconfigured.

**How to reproduce:**
- Start the server once
- Then set the super admin username to empty and start again
```
[super_admin]
username = ""
```
- A user with an empty username is created while UsernameJavaRegEx is set to `^[\S]{3,30}$`

**Expected behavior:**
It should error out saying username does not match with the regex

**Environment information** 
 - Product Version: IS 5.10.0
 - Database: H2
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
