### ISSUE TITLE
Tenant-wise email sender configuration will send emails twice if resource configuration created with different name

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#11997]
**Describe the issue:**
If an email resource created with a different name that does not match with the super tenant (EmailPublisher), both super tenant and subtenant email configurations will be loaded to Event Publisher configurations of the subtenant. This will cause sending emails twice from using both super tenant email-sender configurations and subtenant email-sender configurations.

**How to reproduce:**
1. Add email-sender configurations to the deployment.toml file [1].
2. Create a new tenant.
3. Follow steps 1 and 2 in tenant-wise email-sender configurations [2].
4. Create a new resource with a different name rather than EmailPublisher (CustomEmailPublisher)
```
curl -X POST -k "https://localhost:9443/t/{tenant-domain}/api/identity/config-mgt/v1.0/resource/Publisher" -H "accept: application/json" -H "Content-Type: application/json" -H 'Authorization: Basic YWRtaW46YWRtaW4=' -d "{ \"name\": \"CustomEmailPublisher\", \"attributes\": [ { \"key\": \"email\", \"value\": \"string\" } ]}"
```
5. Create an XML file with the event name CustomEmailPublisher
```
<?xml version="1.0" encoding="UTF-8"?>
<eventPublisher name="CustomEmailPublisher" statistics="disable"
  trace="disable" xmlns="http://wso2.org/carbon/eventpublisher">
  <from streamName="id_gov_notify_stream" version="1.0.0"/>
  <mapping customMapping="enable" type="text">
    <inline>{{body}}{{footer}}</inline>
  </mapping>
  <to eventAdapterType="email">
    <property name="email.address">{{send-to}}</property>
    <property name="email.type">{{content-type}}</property>
    <property name="email.subject">{{subject}}</property>
    <property name="mail.smtp.password">xxxxx</property>
    <property name="mail.smtp.from">resourcesiam@gmail.com</property>
    <property name="mail.smtp.user">resourcesiam</property>
  </to>
</eventPublisher>
```
6. Add the file with the name CustomEmailPublisher
```
curl -X POST -k "https://localhost:9443/t/{tenant-domain}/api/identity/config-mgt/v1.0/resource/Publisher/CustomEmailPublisher/file" -H "accept: application/json" -H "Content-Type: multipart/form-data" -H 'Authorization: Basic YWRtaW46YWRtaW4=' -F "resourceFile=@EmailPublisher.xml;type=text/xml" -F "fileName=CustomEmailPublisher"
```
7. Try a flow that will send an email to the user.
8. The same email will be sent twice using both super tenant configs and subtenant configs.

**Expected behavior:**
Only one email should be sent to the user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Linux

[1] - https://is.docs.wso2.com/en/latest/setup/configuring-email-sending/#configure-email-sending
[2] - https://is.docs.wso2.com/en/latest/learn/tenant-wise-email-sender-configuration/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
