### ISSUE TITLE
Deleting tenant wise created resource will not remove resource configurations from event publisher configurations for the tenant

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#11998]
**Describe the issue:**
If a tenant-wise resource is created and executed one time (loaded to the event publisher configurations), the configuration will be not removed even after deleting the resource. As an example, delete email-sender configurations will be used to send the email.

**How to reproduce:**
1. Follow the steps in #11997 to create a resource in the tenant.
2. Delete the publisher using following CURL.
```
curl -k -X DELETE -k 'https://localhost:9443/t/{tenant-domain}/api/identity/config-mgt/v1.0/resource/Publisher/{publisher-name}' -H "accept: application/json" -H 'Authorization: Basic YWRtaW46YWRtaW4='
```
3. Try a flow that will send emails to the user.
4. Same email will be sent to the user twice even after deleting the publisher resource

**Expected behavior:**
WSO2 IS should discard the tenant wise configurations, should use super tenant configurations and send only one email to the user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
