### ISSUE TITLE
Introduce a new API to revoke all the tokens issued for a given application

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#11993]
Currently there is no API to revoke all the tokens issued for a given application via a single API call.
OAuth2 Authorized Apps API[1] has APIs for the bellow combinations.

1. Per user per application
2. Per user all the applications

Therefore, This this new DELETE API can be introduced into the OAuth2 Authorized Apps API[1] as follows,

- /applications/{application-id}/tokens

[1]-https://is.docs.wso2.com/en/latest/develop/authorized-apps-rest-api/#/admin

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
