### ISSUE TITLE
Adding PRIMARY domain as the provisioning user store domain does not append the "PRIMARY/" to the group stored in IDN_SCIM_GROUP table  

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11999]
**Describe the issue:**
Adding PRIMARY domain as the provisioning user store domain does not append the "PRIMARY/" to the group stored in the IDN_SCIM_GROUP table[1]. This bug does not affect the server.

**How to reproduce:**
Set up the PRIMARY domain as the provisioning user store domain under resident IDP and create a group with a token.
The displayName is added without the "PRIMARY/" appended.

**Expected behavior:**
The "PRIMARY/" should be appended to displayName when adding to the IDN_SCIM_GROUP table. 

**Environment information** **:**
 - Product Version: [IS 5.3.0, 5,10.0]

[1]https://github.com/wso2-extensions/identity-inbound-provisioning-scim/blob/v5.2.0/components/org.wso2.carbon.identity.scim.provider/src/main/java/org/wso2/carbon/identity/scim/provider/impl/SCIMUserManager.java#L610

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
