### ISSUE TITLE
Doc Feedback: "not" missing from "note" section

### ISSUE THREAD

**Issue by gspadotto** [wso2/product-is#11995]
In the only "note" of the page (point 3), there is a "not" missing. 

"Note : It is recommended to throw errors from the Java methods to the authentication script. All the errors have to be handled by the method itself."

Location : https://is.docs.wso2.com/en/5.10.0/develop/writing-custom-functions-for-adaptive-authentication/

**Comment by mefarazath** [comment]
Good catch @gspadotto :)
https://github.com/wso2/docs-is/pull/2683/files should fix this.
