### ISSUE TITLE
Unable to add IDP Role Mapping.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#12020]
**Describe the issue:**
$Subject.

**How to reproduce:**
1. Add an external IDP.
2. Create a new role.
3. Try to add a role mapping in the IDP settings. The mapping doesn't get saved.

**Notes**
If we disable the group role separation, the role mappings can be added.
Use the below config to disable this.
```
[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false
```

**Expected behavior:**
If the local role exists, role mapping should be saved.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-m27
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by Thisara-Welmilla** [comment]
**Expected behavior for IDP role mapping:**
IdP role mappings do not support adding mappings with groups anymore, Only support for roles which have `Internal/` domain prefix.

For further information
Git issue: https://github.com/wso2/product-is/issues/11330
