### ISSUE TITLE
Governance Configurations are missing in Console (since 5.12.0-m18)

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12027]
**Describe the issue:**
In IS-5.12.0-m17 console's manage tab contains these governance configurations
![imageedit_2_2148844160](https://user-images.githubusercontent.com/25483865/124146032-f97dd180-daaa-11eb-9c2b-1da864ea170c.png)

from m18 -to m27 they are not visible in the console app
![Screenshot from 2021-07-01 19-54-04](https://user-images.githubusercontent.com/25483865/124146139-1b775400-daab-11eb-842d-365b9ab5c1ee.png)

**How to reproduce:**
Get 5.12.0-m18 or the latest pack
Log in to console and go to the Manage tab

**Comment by thivi** [comment]
This has been resolved by https://github.com/wso2/identity-apps/pull/2226
