### ISSUE TITLE
"Generate Password" button is not working

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12025]
**Describe the issue:**
The user creation page has an option to generate a password, but that button doesn't function properly. It doesn't generate a password 
![Screenshot from 2021-07-01 14-31-41](https://user-images.githubusercontent.com/25483865/124131497-7e61ee80-da9d-11eb-8e82-cb4dc8138339.png)

**How to reproduce:**

1. Log into console application
2. Go to Manage -> Users
3. Try to add a user with generating a password.
4. Generate Password button doesn't work

**Expected behavior:**
If password generation is supported, the button should function properly.
else, remove the password generation button.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.12.0-m27
 - OS:  Linux
 - Database:  H2
 - Browser - Chrome, Firefox

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/12320
