### ISSUE TITLE
Note on sticky sessions is misguiding

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12024]
In 5.9.0 doc it says following.
```
When clustering WSO2 Identity Server with a load balancer, you may need to enable sticky sessions. This is required for the management console and the dashboard to work and if we disable temporary session data persistence in the <IS_HOME>/repository/conf/deployment.toml file.
```
But the truth is that sticky sessions are mandatory for this to work despite having temporary session data persistence enabled/disabled.

In 5.10.0 doc it says following.
```
When clustering WSO2 Identity Server with a load balancer, you may need to enable sticky sessions. This is required for the management console and the user portal to work and if we disable temporary session data persistence in the <IS_HOME>/repository/conf/deployment.toml file.
```
But the truth is that sticky sessions are mandatory for the management console only and the user portal is not affected.

[1] https://is.docs.wso2.com/en/5.9.0/setup/fronting-with-the-nginx-load-balancer/
[2] https://is.docs.wso2.com/en/5.10.0/setup/fronting-with-the-nginx-load-balancer/

**Comment by rksk** [comment]
Additionally, password recovery and self signup flows require the sticky sessions to be enabled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
