### ISSUE TITLE
ID Token validation failure reason for My Account and Console application should be shown

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#12037]
**Is your suggestion related to an experience?**
There are multiple reasons for ID token validation failure in the My Account and Console application. However, the application is throwing the same error as below in the browser console.

```
Uncaught (in promise) Invalid id_token in the token response:
```

**Describe the improvement**
The exact reason for the validation error should be shown, either by directly showing it in the browser console or applying configurations to turn on debugging to isolate the fix the errors.

**Additional context**
#10645
#10644

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
