### ISSUE TITLE
Document Migration Impact on modifing openid scope claims

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#12034]
According to the OpenID protocol specifications, any user attributes must not send for the 'openID' scope.

The migration guide should track the following points relevant to this modification.

- 'openID' scope does not send any user attributes.
- This change will affect only for new tenant creations.
- The previous behaviour can be restored by modifying the oidc-scope-config.xml file.
```
<Scope id="openid" displayName="Open ID" description="Indicate the use of OpenID Connect protocol.">
     <Claim> 
         sub,email,email_verified,name,family_name,given_name,middle_name,nickname,preferred_username,upn,groups,profile,picture,website,gender,birthdate,zoneinfo,locale,updated_at,phone_number,phone_number_verified,address,street_address,country,formatted,postal_code,locality,region,roles 
    </Claim>
 </Scope>
```
- Following attributes are no longer send by any default OpenID scopes.
`upn, locality, region, postal_code, groups, roles, country, street_address, formatted`

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
