### ISSUE TITLE
Tenant Metadata is not cleared properly when calling  tenant metadata deletion api

### ISSUE THREAD

**Issue by bhagyasakalanka** [wso2/product-is#12032]
**IMPROVEMENT**

In the current implementation, when delete tenant metadata, only  UM_TENANT table records will be cleared. But we need to clear UM_DOMAIN table records as well. So we need to implement that

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
