### ISSUE TITLE
Conflict between JAVA_HOME and PATH in wso2server.bat

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12044]
**Describe the issue:**
If there are two java versions configured for PATH and JAVA_HOME directories, the version identification is done over the PATH variable while all other operations are done with the JAVA_HOME path.

At the following line, it appends the JAVA_HOME to PATH before executing the `java -fullversion` command. But if there is another java path added to the PAH variable already, the existing one will get priority over the path appended to the end.

```
PATH %PATH%;%JAVA_HOME%\bin\
for /f tokens^=2-5^ delims^=.-_^" %%j in ('java -fullversion 2^>^&1') do set "JAVA_VERSION=%%j%%k"
```

In all the other places, it uses the `%JAVA_HOME%\bin` directly without depending on the PATH variable. eg:
```
"%JAVA_HOME%\bin\java" %CMD_LINE_ARGS% org.wso2.carbon.bootstrap.Bootstrap %CMD%
```

**How to reproduce:**
- Install two JDK versions (eg: JDK 8 & 11) in a windows server
- Point JAVA_HOME to java11
- Add bin directory of jdk8 only in the PATH variable
- Following will be logged while trying to start the server
```
Starting WSO2 Carbon (in unsupported JDK)
[ERROR] CARBON is supported only between JDK 11 and JDK 17
```

**Expected behavior:**
It should always be using the JDK configured in JAVA_HOME.

**Environment information** 
 - Product Version: IS 6.0.0
 - OS: Windows

**Comment by Amlesh-NEC** [comment]
Hi @rksk,

I have analysis this issue but i am unable to reproduce it.
so, i request you, please elaborate this issue.

Thanks
Amlesh Singh

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
