### ISSUE TITLE
Error when adding a group via the new console UI

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#12043]
**Describe the issue:**
The following error can be seen in the console when adding a group from the new console.
<img width="773" alt="Screenshot 2021-07-05 at 14 54 28" src="https://user-images.githubusercontent.com/39567992/124449329-f9c6e700-dda0-11eb-82f6-049ac530163d.png">

**How to reproduce:**
1. Navigate to the new console.
2. Click on the add group button.

**Versions**
- M27 and M28

**Comment by nilasini** [comment]
Couldn't reproduce with 5.12.0-alpha16
