### ISSUE TITLE
Migrating getUniqueUserWithClaimValues Adaptive function signautre in 5.12.0

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#12056]
**Describe the issue:**
Because of this issue https://github.com/wso2/product-is/issues/11777 , we need to alter the method signature of adaptive function **getUniqueUserWithClaimValues**  , via https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/70

Modified Parameters can be found here : https://github.com/wso2/product-is/issues/5152#issuecomment-846831139
This Issue opened to track the Migration process

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
