### ISSUE TITLE
Possible grammar mistakes in QSG

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#12053]
**Is your suggestion related to a missing or misleading document? Please describe.**
There are some places where grammar seems to be incorrect. The places are highlighted as follows:

### **1st occurrence**
![image](https://user-images.githubusercontent.com/33062368/124601547-9793e200-de85-11eb-9b88-3b0647dafd1f.png)

### **2nd occurrence**
![image](https://user-images.githubusercontent.com/33062368/124601793-e04b9b00-de85-11eb-9817-b260041ffb64.png)

### **3rd occurrence**
![image](https://user-images.githubusercontent.com/33062368/124601909-fce7d300-de85-11eb-9bf3-e4ff31d90312.png)

**Describe the improvement**

- 1st occurrence: Change the highlighted statement to **_"This application helps to manage the overall operations at Pickup."_**.
- 2nd occurrence: Change the highlighted keyword to **_"SampleWebApplication"_**.
- 3rd occurrence: Change the highlighted phrase to _**"Rowan"**_

---

### Optional Fields

**Additional context**
Found these issues in both 5.10.0 and 5.11.0 docs.

**Related Issues:**
None

**Comment by Amlesh-NEC** [comment]
Hi @madurangasiriwardena,

I have also analysis this issue and i found that we can modify more Possible grammar mistakes in QSG.
And, this issue is merged in wso2-is v11.0 but there is no PR raised for wso2-is v10.0.
Still same or multiple possible grammar mistakes are available in wso2-s v10.0.
