### ISSUE TITLE
Log rotation and monitoring guide still refers to log4j

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12066]
**Is your suggestion related to a missing or misleading document? Please describe.**
Please note the $subject. It should refer to log4j2 instead.

[1] https://is.docs.wso2.com/en/latest/administer/product-level-security-guidelines/#log-rotation-and-monitoring

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
