### ISSUE TITLE
Add template to web.xml in accountrecoveryendpoint

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#12065]
**Is your suggestion related to an experience ? Please describe.**
Need to template web.xml in the accountrecoveryendpoint

**Describe the improvement**
Templating web.xml will help to change the value from the deployment.toml it self

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
