### ISSUE TITLE
Note for Tomcat compatibility issues for web app deployment using OIDC Configurations

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#12078]
**Describe the improvement**

The doc at [1] should be updated to include a note on the compatibility issues that arise when trying to configure Single Sign-On with OpenID Connect using Tomcat as the web container. No backend errors or authorization issues are observed when this occurs.

[1] - https://is.docs.wso2.com/en/latest/learn/configuring-single-sign-on-oidc/

---

### Optional Fields

**Additional context**

Certain versions of Tomcat cause the Pickup Dispatch application to redirect back to the login page upon successful sign-in after SSO-OpenID has been configured, instead of directing to the home page of the application.

![Peek 2021-07-09 14-39](https://user-images.githubusercontent.com/32578617/125054128-7fa9a180-e0c3-11eb-8e32-8ab667ed54c6.gif)

This issue was initially encountered when following the "**Single Sign-On (SSO) - OIDC**" practical exercise in the WSO2 LMS - IAM Fundamentals course and can be reproduced using the following configuration:

- WSO2 Identity Server version 5.11.0
- Tomcat server version 8.5.68
- Operating System - Ubuntu

**Comment by janakamarasena** [comment]
Can you attach the network trace from the browser as well.

**Comment by sanjulamadurapperuma** [comment]
> Can you attach the network trace from the browser as well.

Sure. The screenshot below shows an overview of the network trace.

![Selection_003](https://user-images.githubusercontent.com/32578617/125105944-ab954900-e0fc-11eb-9724-a65735414a14.png)

This is the HAR for the above: https://gist.github.com/sanjulamadurapperuma/1a3345d13b3e6ba5f705f2b2f28beca0

**Comment by sanjulamadurapperuma** [comment]
Closing this issue since it has been addressed with the merged PR [wso2/docs-is#2688](https://github.com/wso2/docs-is/pull/2688).
