### ISSUE TITLE
Recaptcha not working with multi option login

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#12104]
**Describe the issue:**
Recaptcha does not show up in the login page when recaptcha SSO is configured with multi option login.

**How to reproduce:**
- Configure OIDC App
- Configure Local & Outbound Authentication Configuration with multi option login
- Configure recaptcha using the docs [1][2]
- Access the OIDC application. Recaptcha doesn't show up in the login page.

[1] https://is.docs.wso2.com/en/latest/learn/setting-up-recaptcha/
[2] https://is.docs.wso2.com/en/latest/learn/configuring-recaptcha-for-single-sign-on/

**Expected behavior:**
When recaptcha SSO is configured, recaptcha should show up in the login page.  

**Environment information** 
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database:  H2
 - Userstore: LDAP

**Cause:**

- Captcha params are not added to the redirect URL of multi option login flow. 
- Captcha parameter adding is missing in the getRedirectUrl() method of DefaultStepHandler Class (org.wso2.carbon.identity.application.authentication.framework.handler.step.impl). 
- In the single option login flow, captcha parameters are added to redirect URL from the basic Authenticator. 
- But in the multi option login flow, redirections is happening in the handle() method. Hence, recaptcha params should add before redirection.

**Comment by ChamathNS** [comment]
This issue is not reproducible in 5.12.0-M31

**Comment by nilasini** [comment]
This issue is not reproducible in 5.12.0-M36
