### ISSUE TITLE
SAMLSignKeyStore Configuration is not templated in the J2 files

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12108]
**Describe the issue:**
The SAMLSignKeyStore Configuration which is used to configure a separate Keystore for SAML response/request signing is not templated in the J2 files.

The following configuration cannot be added to the carbon.xml file

```
<SAMLSignKeyStore>
          <Location>${carbon.home}/repository/resources/security/saml-keystore.jks</Location>
            <!-- Keystore type (JKS/PKCS12 etc.)-->
            <Type>JKS</Type>
            <!-- Keystore password-->
            <Password>wso2carbon</Password>
            <!-- Private Key alias-->
            <KeyAlias>wso2_local</KeyAlias>
            <!-- Private Key password-->
            <KeyPassword>wso2carbon</KeyPassword>
</SAMLSignKeyStore>
```

**Environment information**  **:**
 - Product Version: [IS 5.10.0]
 
---

**Comment by sanjulamadurapperuma** [comment]
This issue needs to be fixed in IS v5.11.0 as well.
