### ISSUE TITLE
Registered callback does not match with the provided url.

### ISSUE THREAD

**Issue by nejeoui** [wso2/product-is#12119]
**Describe the issue:**
After a fresh installation i tried to access the console at : https://myDomainName.com:9443/console

**How to reproduce:**
download WSO2 Identity Server Zip format and edit repository/conf/deployment.toml to change 
```
hostname = "myDomainName.com"
node_ip = "xxx.xxx.xxx.xxx"
```

**Expected behavior:**
get the Login page but i got the error message : 
```
Registered callback does not match with the provided url.
```

**Environment information**
 - Product Version: wso2is-5.11.0.46
 - OS: Ubuntu 20.04
 - Database: H2
 - Userstore: DEFAULT

**Comment by nejeoui** [comment]
<img width="515" alt="Screen Shot 2021-07-15 at 10 48 19 AM" src="https://user-images.githubusercontent.com/5574573/125767959-f624e050-d9d1-409f-9e32-b4140c499bd3.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
