### ISSUE TITLE
Migration docs should be re-organized in a centralized location

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12118]
## Is your suggestion related to a missing or misleading document? Please describe.

For a user migrating from an older version (let's say IS 5.2.0) to the latest version (IS 5.11.0), we have a migration tool that can do the migration in one go. However, there are certain instructions/configuration changes that need to be applied and are usually noted in our documentation. This document is currently limited to migration from a version to its immediate version. For example; in IS 5.11.0 we will only have instruction on what needs to be done if someone is migrating from IS 5.10.0 only.

Hence, docs for migration from a specific starting version(let's say IS 5.2.0) to target version(IS 5.11.0) are spread out, with some docs for the older versions still in the old docs site. 

Accessing the migration content would be a hassle for any user because they would have to search both docs sites and find the specific doc that relates to their specific migration starting-target version combination.

## Describe the improvement

All migration content should be hosted in a single location for users to access easily. 

We can follow a structure similar to that in APIM docs [1], but without having several pages for every older version, we can have all versions in a single page with fragment links at the top for the user to instantly scroll to whichever version they want to start at. 

The target version will always be the version for which the docs have been made [1], [2]. With this manner, maintenance would also become relatively easier, and for any new releases, only the previously latest page would have to be duplicated and edited with the new version instructions.

## Related Tasks
- Include `Disabling versioning in the registry configuration` step in 5.11.0 migration docs https://github.com/wso2/product-is/issues/12125

---
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-process/#!
[2] https://apim.docs.wso2.com/en/3.1.0/install-and-setup/upgrading-wso2-api-manager/upgrading-process/#!

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
