### ISSUE TITLE
Disabling versioning in the registry configuration step is missing in 5.11.0 migration doc

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12125]
**Is your suggestion related to a missing or misleading document? Please describe.**
If someone is migrating from an earlier version (<=5.9.0), the `Disabling versioning in the registry configuration` step [1] is mandatory, but it has been removed from 5.11.0 migration doc [2]. This could lead to unexpected issues during the migration as well as after the migration.

**Describe the improvement**
The `Disabling versioning in the registry configuration` step should be included in the 5.11.0 migration docs.

**Related Issues**
https://github.com/wso2/product-is/issues/12118

---
[1] https://is.docs.wso2.com/en/5.10.0/setup/migrating-preparing-for-migration/#disabling-versioning-in-the-registry-configuration
[2] https://is.docs.wso2.com/en/latest/setup/migrating-preparing-for-migration/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
