### ISSUE TITLE
Incomplete SCIM API docs

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12127]
**Is your suggestion related to a missing or misleading document? Please describe.**
Documentation for following SCIM2 operations is missing [1]. Docs provide information only of one specific type of operation.

- PATCH Add/Remove/Replace Users to a Role
- PATCH Remove/Replace Groups to a Role
- PATCH Remove/Replace Members to a Group

**Describe the improvement**
A comprehensive guide to all types of SCIM operations is required. 

---

[1] https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Groups%20Endpoint/patchGroup

**Comment by rksk** [comment]
Additionally, no samples for Bulk PATCH and PUT operations.

Ref: https://anuradha-15.medium.com/scim-2-0-bulk-operation-support-in-wso2-identity-server-5-10-0-8041577a4fe3

**Comment by AnuradhaSK** [comment]
User Groups and Role managing Reference: https://medium.com/identity-beyond-borders/manage-groups-and-roles-with-wso2-identity-server-5-11-0-onwards-93d42fe2f135

**Comment by nilasini** [comment]
@nilminiwso2

**Comment by nilminiwso2** [comment]
Please note that the following content is now addressed in the latest IS docs:

- PATCH Add/Remove/Replace Users to a Role
- PATCH Remove/Replace Groups to a Role
- PATCH Remove/Replace Members to a Group
- Bulk PATCH and PUT operations.

We've added two separate guides on Patch [1] and Bulk [2] operations.

[1] https://is.docs.wso2.com/en/latest/develop/scim2-patch-operations/
[2] https://is.docs.wso2.com/en/latest/develop/scim2-batch-operations/

**Comment by nilminiwso2** [comment]
Closing this issue. Will continue the remaining tasks with [1] and [2].

[1] https://is.docs.wso2.com/en/latest/develop/scim2-patch-operations/
[2] https://is.docs.wso2.com/en/latest/develop/scim2-batch-operations/
