### ISSUE TITLE
Document PBKDF2 feature

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#12124]
With [1], support for PBKDF2 is added for IS 5.12.0. It is required to document the added benefits and guidelines on how to use this new hashing algorithm for passwords in secondary JDBC user stores. 

[1] https://github.com/wso2/product-is/issues/11384

**Comment by dewniMW** [comment]
The support for PBKDF2 in primary JDBC user store will be addressed with https://github.com/wso2/product-is/issues/12418. Therefore this aspect also needs to be captured in the 5.12.0 docs.

**Comment by nilminiwso2** [comment]
Already fixed : https://is.docs.wso2.com/en/6.0.0/deploy/secure-userstore-using-pbkdf2/
