### ISSUE TITLE
 Port 10711 which is exposed by one of the internal thrift server is not documented

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12120]
In the "Default Ports of WSO2 Products" document[1], port 10711 which is exposed by one of the internal thrift servers is not documented.

[1]https://is.docs.wso2.com/en/latest/references/default-ports-of-wso2-products/#wso2-identity-server-ports

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
