### ISSUE TITLE
Bad linking for the Authentication options in the doc 

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#12130]
**Is your suggestion related to an experience ? Please describe.**
The option "Authentication" in the [Tutorials](https://is.docs.wso2.com/en/latest/learn/tutorials/) page is linked with the page [Logging in to your application via Identity Server using Facebook Credentials](https://is.docs.wso2.com/en/latest/learn/logging-in-to-your-application-via-identity-server-using-facebook-credentials/)

**Describe the improvement**
Have a landing page under "Authentication" drop down with the list of all the authentication option we have and link it in the [Tutorials](https://is.docs.wso2.com/en/latest/learn/tutorials/) page. 

**Additional context**
This would help to share all the authentication options we have with a single link.

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2692
