### ISSUE TITLE
Proper documentation needed on Audit Logs

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12146]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently, there is no documentation on the purpose and use of audit logs.

**Describe the improvement**
Public documentation required describing audit logs, its purpose and how it can be used.

Docs need to include examples like the following, or a log template with placeholder descriptions.
```
WARN {AUDIT_LOG} - Initiator=user1@carbon.super Action=Delete-User Target=user4 Data={"ServiceProviderName":"CIAM_Portal1"} Outcome=Success

INFO {AUDIT_LOG} - Initiator=user1@carbon.super Action=Get-User-Claim-Values Target=erick Data={"ServiceProviderName":"CIAM_Portal","Claims":{"http://wso2.org/claims/userid":"f50c1ef9-77b9-4e5b-8a1b"}} Outcome=Success

INFO {AUDIT_LOG} - Initiator=user1@carbon.super Action=Get-User-List Target=null Data={"ServiceProviderName":"CIAM_Portal","Claim Value":"f9287a48-a06b-4941-a07c-e40f91ef853a","Users":["user99"],"Claim":"http://wso2.org/claims/userid"} Outcome=Success

INFO {AUDIT_LOG} - Initiator : user101@carbon.super | Action : Login | Target : ApplicationAuthenticationFramework | Data : { "ContextIdentifier" : "c9e10864-7462-459f-9c09-4328cc51a13e","AuthenticatedUser" : "user101@carbon.super","AuthenticatedUserTenantDomain" : "null","ServiceProviderName" : "CIAM_Portal1","RequestType" : "oidc","RelyingParty" : "gUprDFxuzgIZO70jc9pN2Y","AuthenticatedIdPs" : "","User Agent" : "null","RemoteAddress" : "null","UserStoreDomain" : "PRIMARY" } | Result : Success
```

The doc also needs to specify the types of events that can be audited using these logs.
For example:
- Authentication (success and failure)
- Create/update/delete users
- Create/update/delete roles and groups
- Create/update/delete service providers
- Create/update/delete identity providers

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
