### ISSUE TITLE
Svn link is not accessible

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#12147]
**Is your suggestion related to a missing or misleading document? Please describe.**

In the given document, the sample in the SVN is not accessible.
[1] https://is.docs.wso2.com/en/5.10.0/learn/logging-in-to-a-.net-application-using-the-identity-server/#

**Describe the improvement**
Instead this SVN link, we need to use the sample https://github.com/asgardeo/asgardeo-dotnet-oidc-sdk#readme and update the content based on this sample

---

**Comment by dewniMW** [comment]
https://github.com/wso2/product-is/issues/11312#issuecomment-914828128
