### ISSUE TITLE
Datasource configuration does not pick for persisted aggregation.

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-is#12155]
**Describe the issue:**
When persisted aggregation is enabled in the IS-Analytics server, the database server type does not pick from the data source configuration.

**How to reproduce:**
Enable persisted aggregation and start the servers, below WARN log can be observed.

`WARN {org.wso2.siddhi.core.util.parser.AggregationParser} - Provided database type nullis not recognized as a supported database type for persisted incremental aggregation, using MySQL as default`

**Expected behavior:**
The Analytics server should pick the database server type according to the data source configuration.

**Environment information** 
-Not relevant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
