### ISSUE TITLE
Improve sample application experience

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#12153]
Observed following issues on this behavior,
1. Improve sample app user experience. Add notice regarding the granting permission on mandatory value.  Because following window mandatory values were default selected even user revoke them from myaccount

<img width="467" alt="Screenshot 2022-05-23 at 14 33 42" src="https://user-images.githubusercontent.com/39077751/169784328-148691e4-b456-4e37-a869-7f4c64a902f6.png">

2. Sample app "deny" button not working. It redirected to the same page.

3. Disable revoke mandatory claims from myaccount

Currently my account allow to disable mandatory values from the my account. But revoking the mandatory consents will unauthorized the application. Better user get notify on this or remove ability to revoke mandatory values from the myaccount

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
