### ISSUE TITLE
Inconsistent OIDC claim mapping for http://wso2.org/claims/locality claim

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#12163]
**Problem:** 

The localization functionality of email templates works with the language code given to the local claim "http://wso2.org/claims/locality" (which has been mapped to OIDC claim "locality")

The local claim "http://wso2.org/claims/locality" is being mapped to the OIDC claim "locality". But according to the OIDC specification [2] the purpose of this claim is to have an address of a city (example "Los Angeles").

**Possible solutions:**

1.  change OIDC to local mapping as below.
locale > http://wso2.org/claims/locality
locality > http://wso2.org/claims/local 

OR

locale > http://wso2.org/claims/locality
locality > http://wso2.org/claims/address.locality 

2. change the email localization implementation by considering local claim "http://wso2.org/claims/local" instead of "http://wso2.org/claims/locality

**Comment by emswbandara** [comment]
Need to update the docs as well.
https://is.docs.wso2.com/en/latest/learn/customizing-automated-emails/#updating-the-locale-of-a-user

**Comment by ravindudsilva** [comment]
> Need to update the docs as well.
> https://is.docs.wso2.com/en/latest/learn/customizing-automated-emails/#updating-the-locale-of-a-user

https://github.com/wso2/docs-is/pull/2726
