### ISSUE TITLE
Email template localization using local claims doesn't comply with OIDC specification.

### ISSUE THREAD

**Issue by lakshithakasun** [wso2/product-is#12164]
**Describe the issue:**
In WSO2 email template localization documentation[1] it says to add localization code (example fr_fr for French) to the "http://wso2.org/claims/locality" local claim in user's profile. 

The local claim "http://wso2.org/claims/locality" is being mapped to the OIDC claim "locality". But according to the OIDC specification [2] the purpose of this claim is to have an address of a city (example "Los Angeles").

The localization functionality of email templates works with the language code given to the local claim "http://wso2.org/claims/locality" (which has been mapped to OIDC claim "locality")

Hence it seems like this is an OIDC spec violation. Also both local claims "http://wso2.org/claims/local" and "http://wso2.org/claims/locality" are being mapped to the same mapped attribute "local" which should be handled properly.

**Expected behavior:**
Ideally the email template localization should work with local claim "http://wso2.org/claims/local" since that is the attribute given in OIDC specification to store localization code (fr_fr).

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

[1] - https://is.docs.wso2.com/en/latest/learn/customizing-automated-emails/#updating-the-locale-of-a-user
[2] - https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
