### ISSUE TITLE
Vertical misalignment of "Templates" items under "Script Based Adaptive Authentication".

### ISSUE THREAD

**Issue by Ruchira2k** [wso2/product-is#12161]
**Describe the issue:**
The contents within the **Templates** side panel under **Script Based Adaptive Authentication** appear to be vertically misaligned. [The item contents (ie: text and button controls) overlap into their successive neighboring spaces].

![image](https://user-images.githubusercontent.com/37577628/126588115-ff8c3186-8e38-479c-816a-e94827cd1128.png)
![image](https://user-images.githubusercontent.com/37577628/126588154-679db4e0-f109-4370-981c-0b983bb34708.png)

**How to reproduce:**
* Lauch Identity Server
* Go to Main> Identity> Service Providers> List> Click "Edit" on any of the SPs> Local & Outbound Authentication Configuration> Advanced Configuration> Script Based Adaptive Authentication> Templates

**Expected behavior:**
* All the contents related to each template item must stay within its allocated vertical space.

**Environment information :**
 - Product Version: IS 5.11.0, and IS 5.10.0
 - OS: Windows
---

**Comment by ShanChathusanda93** [comment]
This can be experienced in IS 6.0.0 as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
