### ISSUE TITLE
MySql Clustering scripts for NDB engine doesn't support replication and CASCADE on DELETE

### ISSUE THREAD

**Issue by lakshithakasun** [wso2/product-is#12167]
**Describe the issue:**
Current MySql scripts for clustering that ships with wso2is-5.11.0 doesn't work with replication setup.

The cause of above issue was having some tables without PRIMARY keys but in order to work with replication it is required to have PRIMARY keys for all the tables. 

Due to a fix applied on NDB engine[2][3], they have restricted the use of ON DELETE CASCADE in later versions where the child table contains one or more columns of any of the TEXT or BLOB types.

There are two tables we found in the mysql_cluster.sql scripts that matches with ON DELETE CASCADE problem mentioned above. Those tables are, 
IDP_PROV_CONFIG_PROPERTY
IDN_CONFIG_FILE

As a summery of the issue the default mysql cluster scripts shipped with IS 5.11.0 do not support for NDB engine due to the above mentioned cascade problem. Also those default scripts do not support replication due to the PRIMARY key issue mentioned above.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - Database: MySql with NDB version higher than 7.6.1

**Comment by nilasini** [comment]
@Yasara-Y can we close this issue?
