### ISSUE TITLE
Broken link: myaccount - add security device

### ISSUE THREAD

**Issue by jyoakum** [wso2/product-is#12168]
Location : https://is.docs.wso2.com/en/latest/learn/multi-factor-authentication-using-fido/

Link to add security device returns a 404 error.
https://is.docs.wso2.com/en/latest/learn/learn/user-portal.md#add-security-device
it should be pointed at
https://is.docs.wso2.com/en/latest/learn/my-account/#add-security-device

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
