### ISSUE TITLE
Improve SCIM2 Custom schema to support complex multi-valued attributes

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12177]
**Is your suggestion related to an experience ? Please describe.**
Currenly, SCIM2 custom schema added with https://github.com/wso2/product-is/issues/11705 does not support for complex multi-valued attributes. 

It only supports:

- simple attributes
- complex attributes
- simple multi-valued attributes

**Describe the improvement**
Improve the custom schema to support complex multi-valued attributes

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
