### ISSUE TITLE
Populate SAML Metadata without 'validUntil' attribute and formatting issue with Certificate Data

### ISSUE THREAD

**Issue by lakshithakasun** [wso2/product-is#12170]
**Describe the issue:**

Two problems with SAML metadata.

1. When trying to create a service provider/federated IDP by importing the SAML metadata file which we downloaded through resident IDP, we don't have a configuration to directly remove 'validUntil' attribute from resident IDP SAML metadata. 
2. Certificate under 'X509Certificate' tag is not well formatted, it has extra spaces in multiple places. Before importing the certificate, those characters should be removed manually.

**How to reproduce:**
1. Create a Service Provider/Federated IDP 
2. Download the SAML metadata file
3. Open the file and check for above problems.

**Expected behavior:**
1. There should be a configuration to remove "validUntil" attribute without manually removing from the metadata file.
2. Certificate should be well formatted.

**Environment information** 
 - Product Version: IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
