### ISSUE TITLE
UID of IS docker image needs to be changed.

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12181]
**Describe the issue:**
The default value of the UID of docker images needs to be changed to a higher value to ensure that host conflict is avoided [1].

[1] https://docs.bridgecrew.io/docs/bc_k8s_37

**Comment by ashendes** [comment]
The above mentioned issue is yet to be fixed for the next release. The PRs that have referred this issue are fixes done to existing versions.

**Comment by VivekVinushanth** [comment]
Since, the attached PRs refer to the comments and these comments are available in master and 6.0.x branches, we can close the issue.
