### ISSUE TITLE
Enable  invoking the introspect endpoint using client credentials.

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#12180]
Enable  invoking the introspect endpoint using client credentials.

**Suggesting Solution**
Introduce a new authentication BasicClientAuthenticationHandler which extend the AuthenticationHandler class to authenticate requests using client credentials. New authentication handler will not be available as a default handler, need to configure per endpoint from identity.xml to use it and has a high priority than the Basic authentication handler.

**Comment by somindatommy** [comment]
Closing this the fix is available in the public
