### ISSUE TITLE
Custom Brand login page WSO2 IS

### ISSUE THREAD

**Issue by camiloss1** [wso2/product-is#12195]
**Description:**
Hi someone has customized the WSO2 login page, i have a deploy in Kubernetes with helm but whenever I restart the server the files are deleted, i need do this configuration

**Suggested Labels:**
helm, custom, login, page

**Affected Product Version:**
5.11.0

**Comment by ruwanta** [comment]
From your short description It can be assumed that you are using default image provided, and somehow you copy custom themes into the running pods.
This will not work as you correctly experienced in K8s world, All customisations need to be built with your own image and deploy using your helm chart. The WSO2 helm chart will act as the base for developing your helm chart.

Better forum for this kind of queries would be asking on relevant slack channels
https://wso2.com/community/slack
