### ISSUE TITLE
/applications API does not create the app with specified access token type in the request

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#12192]
**Describe the issue:**
$subject.

**How to reproduce:**
1. Create an app (POST request https://{{server-url}}/{{tenant-domain}}/api/server/v1/applications) with the following body in the request:

```
{
  "name": "test-update-oidc-app-1",
  "inboundProtocolConfiguration": {
    "oidc": {
      "clientId": "newclientid",
      "clientSecret": "newclientsecret",
      "grantTypes": [
        "authorization_code",
        "password",
        "client_credentials"
      ],
      "callbackURLs": [
        "https://app.example.com/callback2"
      ],
      "publicClient": true,
      "pkce": {
        "mandatory": false,
        "supportPlainTransformAlgorithm": true
      },
      "accessToken": {
        "type": "JWT",
        "userAccessTokenExpiryInSeconds": 3600,
        "applicationAccessTokenExpiryInSeconds": 3600
      },
      "refreshToken": {
        "expiryInSeconds": 86400,
        "renewRefreshToken": true
      },
      "idToken": {
        "expiryInSeconds": 3600,
        "audience": [
          "http://idp.xyz.com",
          "http://idp.abc.com"
        ],
        "encryption": {
          "enabled": false,
          "algorithm": "RSA-OAEP",
          "method": "A128CBC+HS256"
        }
      },
      "validateRequestObjectSignature": false
    }
  }
}
```
Note that we are specifying the access token type as `JWT` in the request.

2. Get application inbound configurations for oidc (GET https://{{server-url}}/{{tenant-domain}}/api/server/v1//applications​/{applicationId}​/inbound-protocols​/oidc)

3. In the response, a `Type` under the `Access Token` tag does not exist.

**Expected behavior:**
The response of GET /applications​/{applicationId}​/inbound-protocols​/oidc should have the access Token type set to `JWT`.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0, IS 5.12.0-m30]

**Comment by jairo-fernandezr** [comment]
Hi folks, I was wondering if you've applied this fix to the Identity Server 5.11.0 as well.
I'm asking this because I can see that pull request #1665 mentioned above and merged commit 0555a6b into wso2-extensions:master on 30 Aug seems to be affecting the identity-inbound-auth-oauth version 6.7.x which is not used by Identity Server 5.11.0.
Any comments would be highly appreciated.

Thanks and regards
