### ISSUE TITLE
Claim URIs with special characters cause issues

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12190]
**How to reproduce:**
- Goto repository/conf/claim-config.xml and add a double quote to the claim URL of local claim.
eg:
```
<ClaimConfig>
	<Dialects>
		<Dialect dialectURI="http://wso2.org/claims">
			<Claim>
				<ClaimURI>http://wso2.org/claims/givenname"</ClaimURI>
				<DisplayName>First Name</DisplayName>
				<AttributeID>givenName</AttributeID>
				<Description>First Name</Description>
				<Required />
				<DisplayOrder>1</DisplayOrder>
				<SupportedByDefault />
			</Claim>
```
- Start Identity Server and try to add an IDP
![claim uri issue](https://user-images.githubusercontent.com/719073/127299492-175a7df4-099f-4dea-9435-725ae5e0dca3.png)

**Expected behavior:**
It should reject creating the claims with special characters (as it is disallowed from the management console UI). It is also good to fix the UI to avoid breaking everything due to an invalid claim URI, maybe encoding the value.

**Environment information** 
 - Product Version: IS 5.10.0, IS 5.11.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
