### ISSUE TITLE
Incorrect Email Templates are being used in Account Lock and Account Unlock by Administrator

### ISSUE THREAD

**Issue by chinthakarukshan** [wso2/product-is#12203]
**Describe the issue:**
In the account lock and unlock process incorrect email templates are being used inform the end users about the account lock and unlock status.

**How to reproduce:**
1. Download WSO2 IS 5.9 server with WUM timestamp 1590763777183
2.  Enable Account Lock Feature
3. Configure SMTP server to send emails
4. Configure AccountLockFailedAttempt, AccountLockAdmin and AccountUnlockAdmin email templates.
5. Decrease the thread pool size in WSO2 Identity Server.
6. Create Few Users in the Identity Server
7. Access the WSO2 IS dashboard and try to login with incorrect passwords. This will lock the user and send the email to the end user. Do it for couple of users and lock those users.
8. Login to the Carbon console with the admin user. Select some users who are not locked and lock them using admin console.
9. Observe the email messages sent to the user. AccountLockFailedAttempt template will be used for some users to send the email.

**Expected behavior:**
If the account is locked by admin user it should always use the AccountLockAdmin template to send the email.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - WSO2 Identity server 5.9 with WUM timestamp 1590763777183

**Comment by vihanga-liyanage** [comment]
Master is fixed with https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/61
