### ISSUE TITLE
Tenant ID not stored on SSO session DELETE operations

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#12210]
**Describe the issue:**
When a user logs out from a service provider app (or a while after the session has expired) a DELETE operation record is inserted into the IDN_AUTH_SESSION_STORE table. The SQL sentence used to insert this record does not include the TENANT_ID column so it takes a default value of `-1`.

With the introduction of improvements such as #12193 this behavior causes that when filtering active sessions for a given tenant the API returns invalid (closed) sessions.

**How to reproduce:**
1. Configure a service provider (you may use any of the pre-configured SPs if you prefer).
2. Configure a user (you may use default `admin` user if you prefer).
3. Log into your SP application with your user credentials.
4. Log out from your SP application.
5. Run this SQL query on your identity database:
```
SELECT * FROM IDN_AUTH_SESSION_STORE WHERE SESSION_TYPE = 'AppAuthFrameworkSessionContextCache' ORDER BY SESSION_ID
```
6. Validate that for a given session TENANT_ID column for the DELETE operation does not match TENANT_ID column for the STORE operation.

**Expected behavior:**
When inserting a DELETE operation into the IDN_AUTH_SESSION_STORE table it must include the actual tenant ID associated to the given session. 

**Environment information:**
 - Product Version: All versions

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
