### ISSUE TITLE
Missing page of add-security-device

### ISSUE THREAD

**Issue by av24december** [wso2/product-is#12221]
The below page is missing from the WSO2 document, could you please check it?

https://is.docs.wso2.com/en/latest/page-not-found/#add-security-device

**Comment by sumedhe** [comment]
Hi @av24december,
Can you please provide the page which contain the link you clicked?

And is this the page what you are looking for?
https://is.docs.wso2.com/en/latest/learn/my-account/#add-security-device

**Comment by av24december** [comment]
Hi @sumedhe,

This is the page where I found the missing page link: https://is.docs.wso2.com/en/latest/learn/multi-factor-authentication-using-fido/#configuring-mfa-using-fido.

I think this link(https://is.docs.wso2.com/en/latest/learn/my-account/#add-security-device) should be there on the above page
