### ISSUE TITLE
Support to get the user store type in the user stores endpoint

### ISSUE THREAD

**Issue by bhagyasakalanka** [wso2/product-is#12238]
**Is your feature request related to a problem? Please describe.**
In the current implementation of the user store listing [endpoint](https://is.docs.wso2.com/en/latest/develop/userstore-rest-api/#/User%20Store/getSecondaryUserStores) the user store type is not returned. It would be helpful if can get the user store type (local, remote) to distinguish the user stores in the user store listing page in the console.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
