### ISSUE TITLE
Artifact identity-server-parent version 5.11.0 missing in wso2-public

### ISSUE THREAD

**Issue by msche** [wso2/product-is#12232]
**Describe the issue:**

Maven Artifact

```
    <artifactId>identity-server-parent</artifactId>
    <packaging>pom</packaging>
    <version>5.11.0</version>
``` 

is not released to http://maven.wso2.org/nexus/content/groups/wso2-public/

**Expected behavior:**

Artifact deployed to http://maven.wso2.org/nexus/content/groups/wso2-public/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
