### ISSUE TITLE
IS docker-compose documetation doesn't say anything about creating an account and login to docker.wso2.com

### ISSUE THREAD

**Issue by wx-yz** [wso2/product-is#12237]
**Is your suggestion related to a missing or misleading document? Please describe.**
Docker compose try out steps should include clear instructions for login to docker.wso2.com. If you follow default instructions here https://wso2.com/identity-and-access-management/install/docker-compose/get-started/ you get following error,

```
wxyz@desktop ~/s/d/d/is (master)> docker-compose up
Creating network "is_default" with the default driver
Pulling mysql (mysql:5.7.29)...
5.7.29: Pulling from library/mysql
54fec2fa59d0: Pull complete
bcc6c6145912: Pull complete
951c3d959c9d: Pull complete
05de4d0e206e: Pull complete
319f0394ef42: Pull complete
d9185034607b: Pull complete
013a9c64dadc: Pull complete
58b7b840ebff: Pull complete
9b85c0abc43d: Pull complete
bdf022f63e85: Pull complete
35f7f707ce83: Pull complete
Digest: sha256:95b4bc7c1b111906fdb7a39cd990dd99f21c594722735d059769b80312eb57a7
Status: Downloaded newer image for mysql:5.7.29
Building identity-server
Sending build context to Docker daemon  3.072kB

Step 1/4 : FROM docker.wso2.com/wso2is:5.11.0.0
Head https://docker.wso2.com/v2/wso2is/manifests/5.11.0.0: unauthorized: authentication required
ERROR: Service 'identity-server' failed to build

```

**Describe the improvement**

Documentation should include steps of registering for a wso2.com account and using the credentials to login to docker.wso2.com prior to doing a docker-compose up

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
