### ISSUE TITLE
Error in configuring Recaptcha 'redirect_urls'

### ISSUE THREAD

**Issue by shankeerthan-kasilingam** [wso2/product-is#12241]
**Describe the issue:**
When the following configuration is set on IS, it throws an Exception when a user tried to log in.

[recaptcha] 
enabled = true 
api_ur = "https://www.google.com/recaptcha/api.js" 
verify_url = "https://www.google.com/recaptcha/api/sitever
site_key = "<your_site_key>"  
secret_key = "<your_site_secret>"
redirect_urls="external_login_url(APIM_URL)"

**Error**
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.wso2.carbon.identity.captcha.connector.recaptcha.SSOLoginReCaptchaConfig.getFailedUrlList(SSOLoginReCaptchaConfig.java:298)

**How to reproduce:**
[recaptcha] 
enabled = true 
api_ur = "https://www.google.com/recaptcha/api.js" 
verify_url = "https://www.google.com/recaptcha/api/sitever
site_key = "<your_site_key>"  
secret_key = "<your_site_secret>"
redirect_urls="https://localhost:9443/authenticationendpoint/login.do"

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: 
 - Database:
 - Userstore:

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by janakamarasena** [comment]
Closing this issue as this is resolved with https://github.com/wso2-extensions/identity-governance/pull/528
