### ISSUE TITLE
Error handling inconsistency in OAuth/OpenID authentication flow (Token issuance time) - IS 5.10.0

### ISSUE THREAD

**Issue by Rod-yan** [wso2/product-is#12258]
### **Description**:
In the context of identity-inbound-auth-oauth/org.wso2.carbon.identity.oauth.endpoint component of the support-6.4.2 branch, there seems to be an inconsistency in error handling on token issuance time, for password grant type OAuth authentication requests when SP's client id is not found (client secret irrelevant) [to be referred onwards as case A], compared to the same scenario, but with a valid client id and invalid client secret [case B].

The origin of this concern comes from the fact that, for case A, response headers should include WWW-Authenticate header as per OAuth 2 specification: https://datatracker.ietf.org/doc/html/rfc6749#section-5.2
This header is currently not being included when case A is executed.
It is included when case B is executed, although (expected for case A as well). Case B is a non-issue and is provided only as context information.

For case A:
An _org.wso2.carbon.identity.oauth.endpoint.exception.InvalidApplicationClientException_ is raised on the following line, on the OAuth2TokenEndpoint.java (ln 94) class;

> `OAuth2AccessTokenRespDTO oauth2AccessTokenResp = issueAccessToken(oauthRequest, httpRequest);` 

This is then picked up by the InvalidRequestExceptionMapper and passed on to buildErrorResponse(...) method
Bellow condition is skipped as exception is not an instance of TokenEndpointAccessDeniedException (ln 193), and therefore OAuthConstants.HTTP_RESP_HEADER_AUTHENTICATE (WWW-Authenticate) is not appended to the response headers.

> `
> if (exception instanceof TokenEndpointAccessDeniedException) {
>                 return Response.status(oAuthResponse.getResponseStatus())
>                         .header(OAuthConstants.HTTP_RESP_HEADER_AUTHENTICATE, EndpointUtil.getRealmInfo())
>                         .entity(oAuthResponse.getBody()).build();
>             }
> `

### **How to reproduce:**
Case A:
1. Execute a POST OAuth/OpenID token request (Password grant type flow) with an invalid client_id (non existant) directed to IS 5.10.0
2. Validate that WWW-Authenticate header is not present within the 401 HTTP response.

### **Expected behavior:**
WWW-Authenticate header should be present in the 401 HTTP error response for case A as well as per OAuth2 specification; https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

> [...] If the client attempted to authenticate via the "Authorization" request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code and include the "WWW-Authenticate" response header field matching the authentication scheme used by the client.

### **Environment information:**
 - Product Version: IS 5.10.0
 - OS: Tested under Windows 10
 - Database: Embedded H2
 - Userstore: Embedded H2

**Comment by piyarathnalakmali** [comment]
Closing as both support and public fixes are merged.
