### ISSUE TITLE
Document Migration Impact for inconsistent OIDC claim mapping for http://wso2.org/claims/locality claim

### ISSUE THREAD

**Issue by Ammoniya** [wso2/product-is#12266]
**Is your suggestion related to an experience? Please describe.**
In product-is,  local claim "http://wso2.org/claims/locality" is being mapped to the OIDC claim "locality". And the local claim "http://wso2.org/claims/local" is s being mapped to the OIDC claim "local"

According to the OIDC specification the purpose of the "http://wso2.org/claims/locality" claim is to have an address of a city (example "Los Angeles") But current implementation  "http://wso2.org/claims/locality" is being used to store localization code (example nl_nl for dutch Netherlands) which is used in localization functionality of email templates. 

Hence users should be able to store locality details on "http://wso2.org/claims/locality"  and localization information on "http://wso2.org/claims/local"  correctly without any OIDC specification violation.  As well as users should be able to keep the existing configuration without any break. 

**Describe the improvement**
users can use the following configuration in `deployment.toml` to use the existing legacy configuration or keep the new configuration.
```
[claims]
use_legacy_localization_claim="true"
```
* By keeping the `use_legacy_localization_claim="true"` will use  "http://wso2.org/claims/locality" to store the localization information as now.
* By keeping  `use_legacy_localization_claim="false"` or <b>not using this configuration</b>  by default use http://wso2.org/claims/local to store localization information.

***Attached issues***
Related issue - https://github.com/wso2/product-is/issues/12163

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
