### ISSUE TITLE
[Migration] New config to maintain admin forced password reset validity period.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#12267]
**Description:**
As stated in [1] a separate config [2] has been introduced to define the code validity period for admin forced password reset flow. Earlier the admin forced password reset code validity period was read from [3] which is used in other recovery flows such as forget password as well.

It is required to mention this configuration change in the 5.12.0 migration docs. If the user has changed the default value provided in [3] and requires the same value for admin forced password reset code validity period as well, then the following deployment.toml config needs to be added.

```
[identity_mgt.password_reset_by_admin]
code_validity_period=<time>
```

[1] https://github.com/wso2/product-is/issues/12233
[2] https://github.com/wso2/carbon-identity-framework/pull/3642
[3] https://github.com/wso2/carbon-identity-framework/blob/v5.20.141/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L849

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
