### ISSUE TITLE
 Setting 'Renew Refresh Token' to false does not work

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#12268]
Transfering original issue in https://github.com/wso2/product-is/issues/8150 to here.

**Describe the issue:**

After setting this property to "false" in the deployment.toml, a new refresh token is still issued after the refresh token is used to obtain an access token. 

```
[oauth.token_renewal]
renew_refresh_token= "false"
```

**How to reproduce:**

https://is.docs.wso2.com/en/latest/learn/refresh-token-grant/

**Expected behavior:**

After obtaining the access token, the same refresh token should be returned instead of a new one.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
