### ISSUE TITLE
Tenant based Secret Management store for WSO2 IS

### ISSUE THREAD

**Issue by ChanikaRuchini** [wso2/product-is#12264]
**Purpose**
An Identity Secret Manager is needed to manage secrets that are required to be stored as tenant-wise.
This will be a common place to store secrets in WSO2 Identity Server.

**Comment by ChanikaRuchini** [comment]
**Related PR**
1. Add Secret Management Core [#3630](https://github.com/wso2/carbon-identity-framework/pull/3630)

**Comment by nilasini** [comment]
@ChanikaRuchini can we close this issue? Is anything pending?
