### ISSUE TITLE
complexType attributes are missing from UserAdmin wsdl

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#12279]
**Describe the issue:**

According to WSDL [1], "changePasswordByUser" operation is expecting a complex type “changePasswordByUserResponse” in the output. However, this complex type is missing from the WSDL.

<pre style="color:#000020;background:#f6f8ff;">&lt;wsdl:operation name="changePasswordByUser"&gt;
    &lt;wsdl:input message="tns:changePasswordByUserRequest" wsaw:Action="urn:changePasswordByUser"/&gt;
    &lt;wsdl:output message="tns:changePasswordByUserResponse" wsaw:Action="urn:changePasswordByUserResponse"/&gt;
    &lt;wsdl:fault message="tns:UserAdminUserAdminException" name="UserAdminUserAdminException" wsaw:Action="urn:changePasswordByUserUserAdminUserAdminException"/&gt;
&lt;/wsdl:operation&gt;
</pre>

**Environment information**  **:**
 - Product Version: [IS 5.7.0]

[1] - https://localhost:9443/services/UserAdmin?wsdl

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
