### ISSUE TITLE
The content of resource sharing modes of tenant needs to be improved

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#12274]
We can support all modes specified in the section. 

Native multitenancy - this is the common mode used in the deployment. All other modes require other components and deployment models to achieve this resource sharing. 

These resource sharing modes are "theoretical" classification. We need some more research these modes.

Location : https://is.docs.wso2.com/en/latest/administer/introduction-to-multitenancy/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
