### ISSUE TITLE
Push notification based password recovery

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#12280]
Related to https://github.com/wso2/product-is/issues/9325

We need to support password reset flow with a push notification where user will get a push notification when the password reset flow is initiated. The user can approve the notification which will bring the user to a page where the user can set a new password.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
