### ISSUE TITLE
Intermittent failures of operations that require permissions if those permissions are given to an Application role.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12281]
**Describe the issue:**
Operations that require a certain permission fail, if the permissions are loaded from an Application role. 
Example scenario:
Not able to login to the management console or load any management UIs if the permissions for them are given to an Application role.

**How to reproduce:**

- Create an Application role assign all permissions to the application role.
- Now assign the Application role to a user who has no other roles and permissions.
- Restart the server to clear the caches.
- Try to log in to the management console with the user. 

**Expected behavior:**
Since the application role has all permissions and is assigned to the user, he/she should be able to log in.

This happens because when searching for the role with the permissions(eg /permission/admin/login) the application role is returned as 'APPLICATION/<ROLE_NAME>' however in the database the role is stored as 'Application/<ROLE_NAME>', so when trying to filter the roles for the user it is not found.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
