### ISSUE TITLE
No any error message comes up when import a service provider which is exported from a tenant into another tenant of same IS

### ISSUE THREAD

**Issue by lochanaEdirisinghe** [wso2/product-is#12295]
**Describe the issue:**
When a service provider is exported as a xml file from a one tenant, it is not allowed to import to another tenant in the same environment(Because of the same client Id). But the issue is that 'Add New Service Provider page' is displayed without any error message and no error log comes into the wso2carbon.log file.

**How to Reproduce:**
1. Create a new tenant from Super tenant
2. Create a service provider(with OAuth/OpenID connect config) in super tenant and export it as a xml file.
3. Try to import that xml file into the newly created tenant as a service provider. 

**Expected behavior:**
A meaning full error message should be displayed in management console.(like same client key or etc.)

**Comment by deshankoswatte** [comment]
@lochanaEdirisinghe please attach the error that's shown in the wso2carbon.log here as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
