### ISSUE TITLE
Session API GET /sessions responds with duplicated entries for federated users

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#12294]
**Describe the issue:**

For the federated users, session-related information is persisted under two user ids (improvement of https://github.com/wso2/product-is/issues/12169). So, it'll return duplicate results (same session-id with two different user ids) when we try to retrieve the sessions (GET /users/v1/sessions) [1].

**How to reproduce:**
- Get updated IS-5.10.0 pack (update level 65)
- Configure an identity provider, service provider and add Federated Authentication for the local and outbound authentication (with jit provisioning enabled).
- Login to the service provider using federated login.
- Get all the active sessions using session management API [1].
request: GET /users/v1/sessions

**Expected behavior:**
It should not return duplicated results.

**Environment information** **:**
 - Product Version: [ IS 5.10.0]
 - Database: [H2]
 - Userstore: [LDAP]

---

[1] - https://app.swaggerhub.com/apis/jcgarcia4/wso-2_identity_server_user_session_management_api_definition/v1

**Comment by ThaminduDilshan** [comment]
Trying out with the changes proposed in https://github.com/wso2/carbon-identity-framework/pull/3959, https://github.com/wso2/identity-api-user/pull/143;
wasn't able to reproduce this in public according to the steps.

![Screenshot from 2022-07-22 10-26-08](https://user-images.githubusercontent.com/35653110/180365727-ceba78d4-0f53-4090-9b92-ab69b916169a.png)

![Screenshot from 2022-07-22 10-13-32](https://user-images.githubusercontent.com/35653110/180365763-c86880de-d0b8-4515-9f3f-78dc233bfeee.png)

**Comment by ThaminduDilshan** [comment]
This is a regression caused by the original fix.
Not reproducible with https://github.com/wso2/carbon-identity-framework/pull/4185 or https://github.com/wso2/identity-api-user/pull/155 (yet to merge)
