### ISSUE TITLE
Improper concatenation of passwordReset parameter to the Access URL

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#12306]
**Describe the issue:**
In the email based password recovery flow, when the Access URL is set, a parameter is appended as &passwordReset=true without considering that there is no existing parameters.

`https://localhost:9443/myaccount&passwordReset=true
`
 
`http://localhost.com:8080/saml2-web-app-pickup-dispatch.com/home.jsp&passwordReset=true
`

**How to reproduce:**

1. Configure the SP Access URL as https://localhost:9443/myaccount 
2. Initiate a password recovery via mail.
3. Change the password through the link.

**Expected behavior:**

`https://localhost:9443/myaccount?passwordReset=true
`
 
`http://localhost.com:8080/saml2-web-app-pickup-dispatch.com/home.jsp?passwordReset=true
`

**Environment information** **:**
 - Product Version: IS 5.11.0

**Work around for now:**

Setting the "Access URL" field along with an opaque parameter:

`https://localhost:9443/myaccount?temp=true
`

**Comment by Amlesh-NEC** [comment]
Hi @isurusamarasekara san,

Could you please elaborate this issue more.

**Comment by Amlesh-NEC** [comment]
Hi @isurusamarasekara san,

I have investigated this issue but I am unable to reproduce it.
I have followed below steps:
1. I have successfully Configure the SP Access URL as https://localhost:9443/myaccount
Steps to configure password recovery email:
####
[event.default_listener.identity_mgt]
priority="50"
enable =false
[event.default_listener.governance_identity_mgt]
priority="95"
enable =true
[event.default_listener.governance_identity_store]
priority="97"
enable =true

##Configure email sending:
Shut down the server if it is running.
Add the following properties to the deployment.toml file in the IS_HOME/repository/conf folder to configure the email server.
####
[output_adapter.email]
from_address="amlesh5001@gmail.com"
username="New_User"
password="Test@123!"
hostname="smtp.gmail.com"
port=587
enable_start_tls=true
enable_authentication=true

**Note**: Enable Less secure app access.

2. But when i am trying to Initiate a password recovery via mail: 
    i am getting this information: **Password recovery information has been sent to the email registered with the account   New_User**==> I am not receiving reset password email in my mail Id.

In Console getting error information as:
[2021-08-23 16:37:26,233] [e174d8ff-e9b4-47ce-9609-f6e8d0394010] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Event dropped at Output Adapter '**EmailPublisher**' for tenant id '-1234', Error in message format, 535-5.7.8 **Username and Password not accepted.** Learn more at
535 5.7.8  https://support.google.com/mail/?p=**BadCredentials n14sm1834082pjm.5 - gsmtp**
javax.mail.AuthenticationFailedException: 535-5.7.8 **Username and Password not accepted**. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials n14sm1834082pjm.5 - gsmtp
        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)

I am also confused how could I use this tomcat port Expected URL: http://localhost.com:8080/saml2-web-app-pickup-dispatch.com/home.jsp&passwordReset=true
 
So, I request you Please elaborate this more and help me with suggestions.

Thanks
Amlesh Singh

**Comment by isurusamarasekara** [comment]
Hi @Amlesh-NEC ,
This can happen due to these reasons,
1. Either username and/or password you have configured in the deployment.toml is wrong (from_address is just the from field in the email and not one of the login credentials),
2. The google account has two factor authentication enabled.

Please check them again.

Regards,
Isuru
