### ISSUE TITLE
Document Impact on enabling to invoke the introspect endpoint using client credentials

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#12309]
Related to https://github.com/wso2/product-is/issues/12180

The migration guide should track the following points.

- A new authentication handler - `BasicClientAuthenticationHandler` is implemented extending the AuthenticationHandler class, to authenticate requests using client credentials.

- It is capable of authenticating requests with the `basic` auth header.

- The `BasicClientAuthentication` has a higher priority than the `BasicAuthenticationHandler` which utilizes the same auth header. Therefore, if both handlers are engaged to an endpoint, the authenticating process will perform with the new authenticator handler.

- AuthenticationHandlers can be configured per endpoint from `identity.xml` file.
```
allowed-auth-handlers="BasicClientAuthentication"
```
- Add the below configs to configure per endpoint from `deployment.toml` file.
```
[[resource.access_control]]
context="<endpoint>"
allowed_auth_handlers="BasicClientAuthentication"
```

**Comment by ashendes** [comment]
Closing this as these changes were not done for the default product.

**Comment by mefarazath** [comment]
> Closing this as these changes were not done for the default product.

These changes and feature is available in product-is as well. So shouldn't we be documenting this?

**Comment by rksk** [comment]
Also it is good to mention, using client credentials is preferred over basic authentication when it comes to performance.

**Comment by nilminiwso2** [comment]
Followed the following steps to get this tested.

1. Updated the deployment.toml file. Tried both options given below.
    
     - option 1

       ```
       [[resource.access_control]]
        context="(.*)/oauth2/introspect(.*)"
        allowed_auth_handlers="BasicClientAuthentication"
       ```

       - option 2

        ```
        [[resource.access_control]]
         context="(.*)/oauth2/introspect(.*)"
         allowed_auth_handlers="BasicClientAuthenticationHandler"
        ```

2.  Started WSO2 IS 6.1.0 and registered a service provider.

3.   To get an access token, the following command is used to successfully as per [1]:

       ```
       curl -v -X POST --basic -u <CLIENT_ID>:<CLIENT_SECRET> -H 'Content-Type: application/x-www-form- 
       urlencoded;charset=UTF-8' -k -d 'grant_type=client_credentials' https://localhost:9443/oauth2/token
       ```

4.    Validating the access token from the introspection endpoint: 

        ```
         curl -k -u <CLIENT_ID>:<CLIENT_SECRET> -H 'Content-Type: application/x-www-form-urlencoded' -X POST --data 
         'token=<ACCESS_TOKEN>' https://localhost:9443/oauth2/introspect
        ```

I get the following response:

```
"traceId": "893a637d-06d4-4cc6-8ba9-09a310e82beb",

  "code": 401,

  "description": "Authorization failure. Authorization information was invalid or missing from your request.",

  "message": "Unauthorized"

```

Any thoughts on this please?

**Comment by rksk** [comment]
Hi @nilminiwso2 ,

The following worked for me. `http_method` is a mandatory property.
```
[[resource.access_control]]
context="(.*)/oauth2/introspect(.*)"
http_method = "all"
secure = true
allowed_auth_handlers="BasicClientAuthentication"
```

**Comment by nilminiwso2** [comment]
Thank you for the response @rksk . It works fine with the config you provided.

However, I noticed that we also have the following statement in the doc:

```
To allow users with other permissions to send validation requests, add the permissions to the `<IS_HOME>/repository/conf/deployment.toml` file as shown below and restart the server.
    
        ``` toml
        [resource_access_control.introspect]
        permissions = ["/permission/admin/manage/identity/applicationmgt/view","/permission/admin/login"]
        ```
```

We seem to be providing two configs: `[[resource.access_control]]` and `[resource_access_control.introspect]`. I were suggesting here (by the second config) that the user's admin permissions should be checked before validating the access token for a user? 

Would appreciate it if someone can help me improve this section. To me, there seems to be some conflict in these statements which I am trying out.

**Comment by rksk** [comment]
The inconsistency has come with the following section in the identity.xml.j2
```
        <Resource context="(.*)/oauth2/introspect(.*)"
                secured="{{resource_access_control.introspect.secured}}"
                http-method="all">
            {% for permission in resource_access_control.introspect.permissions %}
            <Permissions>{{permission}}</Permissions>
            <Scopes>internal_application_mgt_view</Scopes>
            {% endfor %}
        </Resource>
```
This allows setting permission, etc for introspect endpoint, but not `allowed_auth_handlers`. That was the reason we had to add a separate `[[resource.access_control]]` section to override above default config.

Anyway, if we set `allowed_auth_handlers="BasicClientAuthentication"` with a  `[[resource.access_control]]` section, these permissions are not honored. Because there is no such with `BasicClientAuthentication` and other authentication options are not supported anyway.

The ideal solution is to support setting `allowed_auth_handlers` under `resource_access_control.introspect`.
```
[[resource.access_control]]
context="(.*)/oauth2/introspect(.*)"
http_method = "all"
secure = true
allowed_auth_handlers="BasicClientAuthentication"
```

Until then, if someone wants to allow other auth_handlers as well along with `BasicClientAuthentication` and set permissions/scopes for them (other auth handlers), those also has to be added under the new `[[resource.access_control]]` section like below.

```
[[resource.access_control]]
context="(.*)/oauth2/introspect(.*)"
http_method = "all"
secure = true
allowed_auth_handlers= ["BasicClientAuthentication", "OAuthAuthentication", "BasicAuthentication"]
permissions = ["/permission/admin/manage/identity/applicationmgt/view","/permission/admin/login"]
scopes = ["internal_application_mgt_view"]
```


@Thisara-Welmilla hope we can go for the ideal solution in the next release.

**Comment by madurangasiriwardena** [comment]
Hi @rksk, can you please open a new issue and close this one, if this problem needs to be tracked for the next product release?

**Comment by DMHP** [comment]
Enabling BasicClientAuthenticationHandler for using this feature is missing in the 7.0 /latest documents[1]. Hence re-opening this issue.

[1] https://is.docs.wso2.com/en/latest/guides/authentication/oidc/token-validation-resource-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
