### ISSUE TITLE
checkUsernameValidity method fails for secondary user stores

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#12326]
**Describe the issue:**
Validation fails for existing usernames of the secondary user stores in the self registration flow  

**How to reproduce:**
Try to self register with an existing username in the secondary userstore, it will navigate to user details filling page without giving validation error. (eg:- custom/user1)  

**Expected behavior:**
When existing username is entered, it should display validation error as username already taken. 

**Environment information** 
 - Product Version:IS 5.11.0
 - OS:  Linux
 - Database:  H2
 - Userstore: LDAP, JDBC(secondary)

---
**Cause**
In the checkUsernameValidity method of SelfRegistrationMgtClient class(Identity-framework repo), usersore domain is not prepended to username when setting to the userObject.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
