### ISSUE TITLE
Improve TOTP connector

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#12322]
**Is your suggestion related to an experience ? Please describe.**
Improve the TOTP connector to support Level of Assurance in API Level.

**Describe the improvement**
The TOTP endpoint can be improved to check the level of assurance on taking actions which requires higher level authentication (ex: 2FA).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
