### ISSUE TITLE
SMS OTP ReST API support

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#12328]
**Problem**
I have a mobile banking application where the initial authentication is done with WSO2 default OpenId Connect SSO mechanism. But when the user is ready to do a transaction, I want to elevate the authentication using SMS OTP, but without going through another login flow.
The current WSO2 SMS MFA implementation is highly coupled with the authentication flow and can't be used separately.

**Solution**
It would be nice to have set of ReST APIs to generate and validate SMS OTPs without initialising an authentication flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
