### ISSUE TITLE
Operations section is not visible in the MyAccount portal

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#12333]
**Describe the issue:**

https://is.docs.wso2.com/en/latest/develop/configure-my-account/#configure-basic-settings
As per above, the Operations tab should be visible by default in the MyAccount portal. But it is not. 
Even though I set enable to "false" it is not appearing

using IS 5.11.0

**Comment by Amlesh-NEC** [comment]
Hi @krishnilak,

I am investigating this issue  and I have reproduced it same. I am also facing same issue.
"ui":{
    "features":{
        "operations":{
            "enabled": true,
            "disabledFeatures": [],
            "scopes":{
                "create": [],         
                "read": [],
                "updated": [],
                "delete": []
            }
        }
    }
}
I observed above code is correct as per my understanding.
it need to look into source code and debug it.

My investigation in progress.

Thanks
Amlesh Singh

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
