### ISSUE TITLE
"Writing a Custom Local Authenticator" Document needs to be improved

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-is#12348]
**Is your suggestion related to a missing or misleading document? Please describe.**
This[1] document can be improved in several ways.

**Describe the improvement**

**1. Flow is not described completely.**

Even though the first diagram shows an overview of what is happening here, information that is mandatory to implement a custom federated authenticator is missing IMO. As an example, how to redirect back to IS side is missing. ( Not even in the sample authenticator code in GitHub). Nothing is mentioned about the /commonauth call, How to pass data between the custom UI and custom authenticator JAR, etc.

**2. Need to add sample implementation**

The expandable view just shows the plain interface with its methods. Instead of this, I think it is better to show a sample implementation similar to how we have shown sample implementation in Writing a Custom Local Authenticator[2] doc. Maybe we can reuse the Custom Federated Authenticator code[3] in the sample-is repo.

**3. Method Descriptions**

We have explained what needs to be implemented in each method defined from the interface. This is good. But If we could explain this with the flow, IMO that is better. As an example, we can explain how we should first implement the **initiateAuthenticationRequest** method with the required redirection at the end and how we should include additional required parameters as query params, etc, how to pass additional params in the **/commonauth** call, how to implement **canHandle** method to uniquely identify the authentication request, how then use the **/commonauth** parameters inside **processAuthenticationResponse** and how to set subject identifier, user claims in that method, etc. If additional methods are there, we could describe them in a table as we have already done here[2]. 

[1] - https://is.docs.wso2.com/en/latest/develop/writing-a-custom-federated-authenticator/
[2] - https://is.docs.wso2.com/en/latest/develop/writing-a-custom-local-authenticator/
[3] - https://github.com/wso2/samples-is/blob/master/authenticators/components/org.wso2.carbon.identity.sample.federated.authenticator/src/main/java/org/wso2/carbon/identity/custom/federated/authenticator/CustomFederatedAuthenticator.java#L209

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
