### ISSUE TITLE
Document missing error codes

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#12354]
**Is your suggestion related to a missing or misleading document? Please describe.**
The below error codes are missing in the documentation in https://is.docs.wso2.com/en/latest/develop/error-codes-and-descriptions/.

Missing error codes :
USER_ACCOUNT_NOT_CONFIRMED_ERROR_CODE = "17005";
ADMIN_FORCED_USER_PASSWORD_RESET_VIA_EMAIL_LINK_ERROR_CODE = "17006";
ADMIN_FORCED_USER_PASSWORD_RESET_VIA_OTP_ERROR_CODE = "17007";
ADMIN_FORCED_USER_PASSWORD_RESET_VIA_OTP_MISMATCHED_ERROR_CODE = "17008"

**Comment by lakshithakasun** [comment]
Another missing error code : USER_INVALID_CREDENTIALS = "17010";
