### ISSUE TITLE
The error message shown to user at login when admin has locked the account says account locked due to failed logins

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#12355]
**Describe the Issue:**
When the admin locks a user's account, the error message displayed to the user at the login is as below. The error message says the account is locked die to failed login attempts, but the actual reason is admin initiated account lock.

**How to reproduce:**
1. Add the below config to deployment.toml
```
[authentication.authenticator.basic.parameters]
showAuthFailureReason = true
showAuthFailureReasonOnLoginPage = true
```
2. Enable account lock on failed login attempts from the resident IDP configs
3. Lock a user by setting the account locked identity claim to true (Either via SCIM2 or from the management console)
4. Try to login to the locked user. The error message shown will be the below one, even though the account is not locked due to failed login attempts.

![image](https://user-images.githubusercontent.com/25479743/130596342-2a6fe64d-f502-4f39-99bf-6b9cb373c772.png)

**Expected behavior:**
The user should be informed that the account is locked and should be asked to contact the administrator.

**Comment by dewniMW** [comment]
@DinikaSen is this issue fixed now?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
