### ISSUE TITLE
A new doc for the JWT based SSO

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#12352]
**Describe the improvement**
Please create an official doc for the doc [3] https://mifrazmurthaja.medium.com/jwt-sso-with-wso2-identity-server-cf486ffba1bf

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
