### ISSUE TITLE
Update the 'Account Locking by Failed Login Attempts' documentation

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#12353]
**Is your suggestion related to a missing or misleading document? Please describe.**
With the changes introduced to address https://github.com/wso2/product-is/issues/12231, the existing account lock enable configuration is changed. Now account lock is by default enabled globally, and no additional configuration is required to enable account lock by updating the account lock claim. Hence the below changes are required in the specified docs.

Further, addressing https://github.com/wso2/product-is/issues/12111, a new config is introduced to support sending email notifications every time the account lock duration is incremented. Also the email sent to the user after account is locked now contains the locked duration as well.

1. In doc https://is.docs.wso2.com/en/latest/learn/locking-a-specific-user-account/ : In section `Configure WSO2 IS for account locking` (https://is.docs.wso2.com/en/latest/learn/locking-a-specific-user-account/#configure-wso2-is-for-account-locking) step 3,4,5,6 are no longer required for account locking by updating the `Account Lock` claim.
2. In doc https://is.docs.wso2.com/en/latest/learn/account-locking-by-failed-login-attempts : In section `Configuring WSO2 IS for account locking` (https://is.docs.wso2.com/en/latest/learn/account-locking-by-failed-login-attempts/#configuring-wso2-is-for-account-locking), the below configs are changed.

> 1. `Account Lock Enabled` config is renamed as `Lock user accounts on maximum failed attempts`
> 2. A new config is introduced as `Notify user when lock time is increased` to enable notifying the user when the account lock duration is increased due to continuous failed login attempts via email.

3. In the same doc https://is.docs.wso2.com/en/latest/learn/account-locking-by-failed-login-attempts : Sample email template `Account lock by Maximum Failed Login Attempts` should be updated. (Refer to PR https://github.com/wso2-extensions/identity-event-handler-notification/pull/147  for the new changes introduced to the template)

New config UI : 
![image](https://user-images.githubusercontent.com/25479743/130556987-1cb15d1d-f22c-4c0c-9232-ec73446a28c7.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
