### ISSUE TITLE
Last name is not updated in JIT provisioned user

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#12364]
Describe the Issue:
Tried it by removing the last name from Google account and try to log in again to the application. The last name is still there.

Expected behavior:
If the user removes the last name of his Google account in JIT provisioned user profile should be changed accordingly.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
