### ISSUE TITLE
Outdated documentation "Hosting Authentication Endpoint on a Different Server"

### ISSUE THREAD

**Issue by paweltest12** [wso2/product-is#12366]
Following article (Hosting Authentication Endpoint on a Different Server)
https://is.docs.wso2.com/en/latest/develop/hosting-authentication-endpoint-on-a-different-server/

seems to be outdated. Instructions provided leads to the runtime error in the tomcat server for the deployed application.
Tested with the latest (5.11.0) version of wso2is and with wso2is-5.12.0-m33
I've followed all steps from 'running the sample' section
https://is.docs.wso2.com/en/latest/develop/hosting-authentication-endpoint-on-a-different-server/#running-the-sample

authenticationendpoint initialization fails with following error:
Error:
25-Aug-2021 14:26:27.901 SEVERE [https-jsse-nio-8443-exec-3] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.application.authentication.endpoint.util.listener.AuthenticationEndpointContextListener]
        java.lang.NullPointerException
                at org.wso2.carbon.identity.core.util.IdentityUtil.fillURLPlaceholders(IdentityUtil.java:853)
...

accountrecoveryendpoint initialization fails with following error:
25-Aug-2021 15:09:05.145 SEVERE [https-jsse-nio-8443-exec-36] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.mgt.endpoint.util.listener.IdentityManagementEndpointContextListener]
        java.lang.NullPointerException
                at org.wso2.carbon.identity.core.util.IdentityUtil.getServicePath(IdentityUtil.java:521)
...

Please provide correct steps for running auth endpoints on separate server for the latest product version.

Thanks,
Pawel

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
