### ISSUE TITLE
Myaccount application documentation

### ISSUE THREAD

**Issue by paweltest12** [wso2/product-is#12367]
Followin article (https://is.docs.wso2.com/en/latest/develop/setting-up-my-account-in-a-dev-environment/) describes steps necessary to run myaccount in the development mode on the localhost machine. 

There is no documentation explaining how to run myaccount application successfully on the separate server in the production (not dev only) mode. 
Please provide documentation how to run myaccount application in the production mode on the separate server.

**Comment by paweltest12** [comment]
Please also note external build howto provided here: https://github.com/wso2/identity-apps#deployment
doesn't contain steps how to deploy on tomcat. Copying files to webapps does't work and application fails to start.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
