### ISSUE TITLE
Performance Tuning Recommendations doc should mention about LDAP connection pooling

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12375]
**Is your suggestion related to a missing or misleading document? Please describe.**

In the doc [1], it mentions LDAPS connection pooling only, But for that to work, the following property is also required. This should come first.

Primary
```
[user_store]
connection_pooling_enabled = true
```

Secondary
```
<Property name="ConnectionPoolingEnabled">true</Property>
```

[1] https://is.docs.wso2.com/en/latest/setup/performance-tuning-recommendations/#pooling-ldaps-connections

**Comment by rksk** [comment]
Also, it is required to mention that `To allow both plain and SSL connections to be pooled, set the "com.sun.jndi.ldap.connect.pool.protocol" system property to the string "plain ssl"`

Ref: https://docs.oracle.com/javase/jndi/tutorial/ldap/connect/pool.html

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
