### ISSUE TITLE
Minimize the steps to enable product observability

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12373]
**Is your suggestion related to an experience ? Please describe.**
The number of steps to enable product observability is many. If it is just a switch to make it true to enable the logs, that would be really simple to troubleshoot production issues. Because dev-ops are reluctant to perform multi-step procedures directly on production env.

It seems all the configs in log4j2.properties can be shipped OOTB and keep the `-DenableCorrelationLogs` to enable the logs.

[1] https://is.docs.wso2.com/en/latest/setup/working-with-product-observability/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
