### ISSUE TITLE
Disabled remove option for social signup Google&Github

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#12380]
**Describe the issue:**
`External Logins section` (or Linked Social Accounts) have disabled the **remove** option for **Google** and **Github** if they are the Authenticated IDP.

**Expected behavior:**
Remove option should be available. Remove the condition check for `Google/Github` that disables the **remove** option.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
