### ISSUE TITLE
Add password digest as a configurable property for primary JDBC user store.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#12394]
Doc [1] states to specify the password hashing algorithm, the primary user store property used is `password_hash_method` which is incorrect. From the fix for issue [2], a new config has been introduced for this. 

```
[user_store]
type = "database_unique_id"
password_digest="PBKDF2"
```

Doc [1] should be updated to reflect this change for IS 5.12.0

[1] https://is.docs.wso2.com/en/latest/setup/configuring-a-jdbc-user-store/#properties-used-in-jdbc-user-store-manager
[2] https://github.com/wso2/product-is/issues/12377

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
