### ISSUE TITLE
Receive a error page when try to set a JWKS endpoint 

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#12405]
Receive `Something went wrong` page when try to set a JWKS endpoint. (Reproduced in both dev and local pack)

![Screenshot from 2021-08-30 15-38-46](https://user-images.githubusercontent.com/82029070/131324062-b7d0c3f1-0fde-4000-a661-ff861df2c6a9.png)

Steps to reproduce

1. Create a new Traditional Web Application
2. Go to the protocol tab and select `Use JWKS endpoint` under `Certificate` section with any URL value
3. Update the changes.

**Comment by ChanikaRuchini** [comment]
Verified in dev
