### ISSUE TITLE
Unable to filter SCIM 2.0 Users with condition based on sub-attribute urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.accountState

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#12412]
**The issue:**
Incorrect response when issuing GET request **with filter condition** based on sub-attribute urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.**accountState** because if there is a result it should be displayed. Same issue persists even when tried with urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:**accountState** combination.

**How to reproduce:**
- Issue similar **GET /scim2/Users** request like the following with filter for urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.**accountState**:
`https://localhost:9443/t/carbon.super/scim2/Users?attributes=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.accountState&filter=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.accountState eq PENDING_AP`
- You will receive this response below for the filter (also without filter on same request, the response shows the **accountState** properly if its existing for user.)
```json
{
    "totalResults": 1,
    "startIndex": 1,
    "itemsPerPage": 0,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ]
}
```

**Expected behavior:**
Response should be something similar to this because such a filtered user exists:
```json
{
    "totalResults": 1,
    "startIndex": 1,
    "itemsPerPage": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "id": "46abc9aa-dcdd-4f32-a99e-ff0243499803",
            "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                "accountState": "PENDING_AP"
            }
        }
    ]
}
```

**Environment information:**
 - Product Version: [IS 5.11.0.61]
 - Test Tool: Postman

**Comment by ratnajothy** [comment]
Possible duplicate of https://github.com/wso2/product-is/issues/11766

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
