### ISSUE TITLE
Authenticators API should support pagination

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#12410]
**Is your suggestion related to an experience ? Please describe.**
ATM, Authenticators API only supports to retrieve 100 items. 

**Describe the improvement**
This API has to support  pagination.

**Related Issues**
- https://github.com/wso2/product-is/issues/11984

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
