### ISSUE TITLE
 Option to disable attribute syncing for JIT provisioned users

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#12414]
**Describe the issue:**
Need to have an option in IDP configs to disable attribute syncing from the federated IDP for JIT provisioned users.
Sub task of https://github.com/wso2/product-is/issues/12017

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
