### ISSUE TITLE
Update the "UserInfo Response Builder"

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#12435]
**Is your suggestion related to a missing or misleading document? Please describe.**
The server throw an error and stops If only the following code segment is added to the deployment.toml file.
```
[oauth.oidc.extensions]
user_info_response_builder = "full qualified class name of the userinfo response builder"
```

**Describe the improvement**
The deployment.toml file should have the following segment before adding the `[oauth.oidc.extensions]` (above).

```
[oauth.oidc]
user_info.response_type= "webtoken type (json/jwt)"
```
**Related Doc**
https://is.docs.wso2.com/en/latest/learn/extension-points-for-oauth/#userinfo-response-builder

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
