### ISSUE TITLE
Logs to help self-diagnostic and corrections for developers

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#12436]
The developers are interested in debugging the newly onboarded application flow. They want an easy way to see where the authentication flow goes wrong, where the clam transformation goes wrong etc. Therefore there is a requirement of having logs to help self-diagnostic and corrections for developers.

Issue related to capture requirement for IS components.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
