### ISSUE TITLE
Disable username based login when multi-attribute filtering is enabled and username claim is not configured

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#12437]
**Describe the issue:**
Disable username based login when multi-attribute filtering is enabled and username claim is not configured.

**How to reproduce:**
1. Enable multi-attribute login only for mobile claim ([Doc](https://is.docs.wso2.com/en/5.12.0/learn/multi-attribute-login/))
2. Go to https://localhost:9443/myaccount and try to login with username
3. You will get logged in even the username claim is not configured.

**Expected behavior:**
The user should no be able to login with the username.

**Environment informatio:**
 - Product Version: wso2is-5.12.0-m35

**Comment by ShehanDinuka** [comment]
Hi Team,

We need this feature in IS 5.11.0 as well.

**Comment by ThaminduDilshan** [comment]
Related issue with the fix:
- https://github.com/wso2/product-is/issues/18985
