### ISSUE TITLE
Catching general Exception and using specific error messages

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12444]
**Describe the issue:**
Following code, block exists in 15 places inside the carbon kernel (4.7.x branch too).  Also, we do catch `catch (Exception` in hundreds of places.
```
  } catch (Exception e) {
      String errorMessage = "Error occurred while getting database type from DB connection";
      if (log.isDebugEnabled()) {
          log.debug(errorMessage, e);
      }
      throw new UserStoreException(errorMessage, e);
  } 
 ```
 
 This will give misguiding error messages because it is not only caching exceptions related to connection creating but any exception thrown from other methods called inside the try block.
 
 For example, `doUpdateUserListOfRoleWithID()` [1] calls `DatabaseUtil.udpateUserRoleMappingInBatchMode()` and that method throws `UserStoreException`. But with the following implementation, the error message would be "Error occurred while getting database type from DB connection".
 
 ```
     public void doUpdateUserListOfRoleWithID(String roleName, String[] deletedUserIDs, String[] newUserIDs)
            throws UserStoreException {

        ...
        try {
            ...
            DatabaseUtil.udpateUserRoleMappingInBatchMode(dbConnection, sqlStmt1, roleName, tenantId,
             ...
        } catch (SQLException e) {
            DatabaseUtil.rollBack(dbConnection);
            String msg = "Database error occurred while updating user list of role : " + roleName;
            if (log.isDebugEnabled()) {
                log.debug(msg, e);
            }
            throw new UserStoreException(msg, e);
        } catch (Exception e) {
            String errorMessage = "Error occurred while getting database type from DB connection";
            if (log.isDebugEnabled()) {
                log.debug(errorMessage, e);
            }
            throw new UserStoreException(errorMessage, e);
        } finally {
            DatabaseUtil.closeAllConnections(dbConnection);
        }

    }
 ```
  
 [1] https://github.com/wso2/carbon-kernel/blob/22dc3a72d436c2cfb219b055d54e005c66f18add/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L1501-L1582

**Comment by rksk** [comment]
The `UserStoreException` thrown from `DatabaseUtil.udpateUserRoleMappingInBatchMode()` is not handled properly in any of the places. Some places are expecting the error code `ERROR_CODE_DUPLICATE_WHILE_WRITING_TO_DATABASE`, but the above method never throws this code, and also skipping the error in a duplicate error is not acceptable during a batch process, because a duplicate in a batch process means there was a single record which was duplicated.

Sample applied for `DatabaseUtil.udpateUserRoleMappingWithExactParams()` as well.

Also `DatabaseUtil.udpateUserRoleMappingInBatchMode()` tries to commit the transaction which is incorrect.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
