### ISSUE TITLE
Filtering with groups(hybrid roles) on the SCIM2 users endpoint does not work if the domain(Application/Internal) is appended.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12445]
**Describe the issue:**
Filtering with groups(hybrid roles) on the SCIM2 users endpoint does not work if the domain(Application/Internal) is appended.

**How to reproduce:**

- Create an Application role, eg - Application/testrole, and add a user to the role.

- Filter the users endpoint as follows.
With pagination params
  ```
  curl -v -k -u admin:admin "https://localhost:9443/scim2/Users?startIndex=1&count=10&filter=groups+eq+Application/testrole"
  ```
  Without pagination params(legacy API path).
  ```
  curl -v -k -u admin:admin "https://localhost:9443/scim2/Users?filter=groups+eq+Application/testrole"
  ```
  No results are returned for both requests.
  ```
  {"totalResults":0,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}
  ```
  **Expected behavior:**
  The expected result should be the same as when the result returned when the filter does not have the domain
  ```
  curl -v -k -u admin:admin "https://localhost:9443/scim2/Users?startIndex=1&count=10&filter=groups+eq+testrole"
  ```

It seems there is an issue with the case of the domain, In the database, the application role is stored as Application/testrole however when trying to filter the query searches for APPLICATION/testrole.

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.11.0]
 - Userstore: [JDBC]

**Comment by nilasini** [comment]
@Yasara-Y shall we close this issue?

**Comment by Yasara-Y** [comment]
Closing the issue since the fix is done to all relevant branches.
