### ISSUE TITLE
Need to update the documentation when changing the primary user store

### ISSUE THREAD

**Issue by Nirmal-De-Silva-99** [wso2/product-is#12449]
**Is your suggestion related to a missing or misleading document? Please describe.**

https://is.docs.wso2.com/en/latest/learn/configuring-the-bpm-profile-of-wso2-ei-as-a-workflow-engine/#!

According to the doc in the above link, if we changed the deployment.toml file here,

![image](https://user-images.githubusercontent.com/65043823/132165208-76eb35ab-c1fc-487c-a931-536725a119c9.png)

It will give "UserNotFound: User admin does not exist in: PRIMARY org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User admin does not exist in: PRIMARY" error in the console.

**Describe the improvement**

However the problem will be solved if changed like this instead,

[user_store]
type = "database_unique_id"

**Comment by nilminiwso2** [comment]
Need to add this to the workflow docs in IS 6.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
