### ISSUE TITLE
Support HTTP2.0 in IS

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12453]
**Is your suggestion related to an experience ? Please describe.**

Followed the steps below to configure HTTP2.0 in IS.

1. Use jdk 11. With jdk8, it didn’t work. There is a note in tomcat documentation [here](https://tomcat.apache.org/tomcat-9.0-doc/config/http.html#HTTP/2_Support). 

2. Add this configuration as given here in catalina-server.xml.j2 file https://readlearncode.com/configure-tomcat-9-for-http2/
 Finally it should look like this in catalina-server.xml file ,

```
<Connector protocol="org.apache.coyote.http11.Http11NioProtocol"
                  URIEncoding="UTF-8"
                  maxThreads="250"
                  bindOnInit="false"
                  SSLEnabled="true"
                  secure="true"
                  disableUploadTimeout="false"
                  connectionUploadTimeout="120000"
                  acceptCount="200"
                  compressibleMimeType="text/html,text/javascript,application/x-javascript,application/javascript,application/xml,text/css,application/xslt+xml,text/xsl,image/gif,image/jpg,image/jpeg"
                  maxKeepAliveRequests="200"
                  minSpareThreads="50"
                  noCompressionUserAgents="gozilla, traviata"
                  server="WSO2 Carbon Server"
                  enableLookups="false"
                  acceptorThreadCount="2"
                  compression="on"
                  compressionMinSize="2048"
                  scheme="https"
                  port="9443"
                  maxHttpHeaderSize="8192"
       >
	<UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol"/>
           <SSLHostConfig honorCipherOrder="false"
                                      protocols="+TLSv1,+TLSv1.1,+TLSv1.2"
                                      truststorePassword="wso2carbon"
                                      truststoreType="JKS"
                                      truststoreFile="${carbon.home}/repository/resources/security/client-truststore.jks"
                                      certificateVerification="want"
                                      sslProtocol="TLS"
                                      >
               <Certificate
                                                      certificateKeystorePassword="wso2carbon"
                                                      certificateKeystoreFile="${carbon.home}/repository/resources/security/wso2carbon.jks"
                                                      certificateKeyAlias="wso2carbon"
                                                      certificateKeystoreType="JKS"
                                                      certificateKeyPassword="wso2carbon"
                            />
           </SSLHostConfig>
       </Connector>
```
3. Add below CORS config in deployment.toml. Add your server origin as allowed origin
```
[cors]
allowed_origins = ["https://localhost:9443"]
supported_methods = [
    "GET",
    "HEAD",
    "POST",
    "OPTIONS",
]
exposed_headers = [ "Location" ]

```

4. Check the HTTP access logs by logging into the management console. Also you can check the network logs.
`127.0.0.1 - - [06/Sep/2021:17:14:24 +0530] GET /carbon/ HTTP/2.0 302 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0" 0.003`

**Issues found**
1. Can login to Management console, MyAccount and COnsole. But still some of js page loading happens via HTTP2.

Uses HTTP1.1 
<img width="1680" alt="Screenshot 2021-09-06 at 17 31 54" src="https://user-images.githubusercontent.com/17597293/132218999-81b2e7e0-5c37-4b0f-b0ee-99f2609c2c8b.png">

But this uses HTTP2
<img width="1674" alt="Screenshot 2021-09-06 at 17 32 04" src="https://user-images.githubusercontent.com/17597293/132219021-c6ecf9f0-b5df-44fb-a2e0-fae487036ea6.png">

2. We need to add cors config for the same host name as the allowed origin( Need this to login to ManagementConsole, new console and MyAccount. Otherwise it will prompt below error after submitting the credentials)
3. Not compatible with jdk8

**Describe the improvement**
Can include the HTTP2.0 support in IS in future

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
