### ISSUE TITLE
Tenant Creation does not work with UniqueIDActiveDirectoryUserStoreManager when IS generates the user id

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12455]
**Describe the issue:**
Tenant Creation does not work with UniqueIDActiveDirectoryUserStoreManager when the server is configured to generate the user id.

**How to reproduce:**

- Setup an AD as the primary userstore with UniqueIDActiveDirectoryUserStoreManager
- For userid attribute use an attribute other than objectGUID so that it would be populated by the Identity Server.
- Try to create a tenant.
- The tenant creation would fail because the userid is not added to the tenant admin user created.

**Expected behavior:**
userid generated by the server should be persisted when the tenant admin user is added.

**Environment information** **:**
 - Product Version: [IS 5.10.0]
 - Userstore: [AD]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
