### ISSUE TITLE
broken link in geolocation guide

### ISSUE THREAD

**Issue by olocin** [wso2/product-is#12465]
In the document [1] in the step 1 the link is broken. It points to https://is.docs.wso2.com/en/latest/learn/creating-geo-location-data-set/ that doesn't exist.

[1] https://is.docs.wso2.com/en/latest/learn/enabling-geolocation-based-statistics/

**Comment by dewniMW** [comment]
The link should be corrected as https://is.docs.wso2.com/en/latest/learn/creating-geo-location-dataset/

**Comment by nilminiwso2** [comment]
fixed
