### ISSUE TITLE
Remove the usage of JQuery from OOTB endpoints

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#12461]
**Description:**
JQuery is currently used in several webapps such as authenticationendpoint, accountrecoveryendpoint, etc. Going forward we need to remove JQuery from all webapps, (except Carbon UI). This needs to be captured with the restructuring effort of these apps. One possible approach that can be taken is to use simple JSP for authentication webapp, and use proper React libraries for all other webapps.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
