### ISSUE TITLE
Create docs for Custom Header Filter

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#12478]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently there is no docs for Custom Header Filter feature. There is a setup guide in the readme file but it's better to have it in doc space.

Info: https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/master/README.md

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
