### ISSUE TITLE
Update third party libraries

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#12479]
**Describe the issue:**
We need to update following libraries.

**net.minidev.accessors-smart_1.2.0.jar -> net.minidev.accessors-smart_2.4.7.jar
yubico-webauthn_1.3.0.wso2v4.jar -> yubico-webauthn_1.10.1.wso2v1.jar
net.minidev.json-smart_2.3.0.jar -> net.minidev.json-smart_2.4.7.jar 
org.objectweb.asm.all_5.2.0.jar  -> org.objectweb.asm_9.2.jar
net.sf.ehcache_2.10.4.jar -> net.sf.ehcache_2.10.9.2.jar**

When we updating yubico we are going to use the existing httpclient available in the pack rather than packing a seperate httpclient in to yubico \[1]. But yubico 1.10.1 needs latest httpclient-4.5.13. Therefore we need to update the product httpclient version from 4.3.6 to 4.5.13. In order to do that following changes needs to be done as below dependencies depending on each other.

**httpclient 4.3.6.wso2v2>4.5.13.wso2v1
http core 4.3.3.wso2v1 -> 4.4.14.wso2v1
httpmime 4.3.1.wso2v2 -> 4.5.13.wso2v1
openid4java  1.0.0.wso2v4->1.0.0.wso2v5**

Following details explaining the places where we are packing each libraries and the PRs to update the dependency version.

**httpclient**

When we update httpclient we need to update following places since httpclient is packed from below places. 

1.  repository/components/features/org.wso2.carbon.registry.contentsearch.server_4.7.33/feature.xml:15:  <plugin id="httpclient" unpack="false" version="4.3.6.wso2v2"/>
Fixed with https://github.com/wso2/carbon-registry/pull/369

2. repository/components/features/org.wso2.carbon.event.output.adapter.http.server_5.2.27/feature.xml:7:  <plugin id="httpclient" unpack="false" version="4.3.6.wso2v2"/> - 
Fix is already done need to update the analytics-common version 5.2.35 in the product.

3. repository/components/features/org.wso2.carbon.identity.sso.saml.ui_5.8.19/feature.xml:11:  <plugin id="httpclient" unpack="false" version="4.3.6.wso2v2"/
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/343

4. repository/components/features/org.wso2.carbon.databridge.agent.server_5.2.27/feature.xml:9:  <plugin id="httpclient" unpack="false" version="4.3.6.wso2v2"/>
Fix is already done need to update the analytics-common version 5.2.35 in the product.

**httpcore**

1. repository/components/features/org.wso2.carbon.databridge.agent.server_5.2.27/feature.xml:10:  <plugin id="httpcore" unpack="false" version="4.3.3.wso2v1"/>
Fix is already done need to update the analytics-common version 5.2.35 in the product.

2. repository/components/features/org.wso2.carbon.registry.contentsearch.server_4.7.33/feature.xml:16:  <plugin id="httpcore" unpack="false" version="4.3.3.wso2v1"/> 
Fixed with https://github.com/wso2/carbon-registry/pull/369

3. repository/components/features/org.wso2.carbon.core.common_4.6.1/feature.xml:44:  <plugin id="httpcore" unpack="false" version="4.3.3.wso2v1"/>  
Fixed with https://github.com/wso2/carbon-kernel/pull/3056

**httpmime**

repository/components/features/org.wso2.carbon.registry.contentsearch.server_4.7.33/feature.xml:6:  <plugin id="httpmime" unpack="false" version="4.3.1.wso2v2"/>

Fixed with https://github.com/wso2/carbon-registry/pull/369

**openid4java**

repository/components/features/org.wso2.carbon.identity.provider.server_5.6.0/feature.xml:10:  <plugin id="openid4java" unpack="false" version="1.0.0.wso2v4"/>

Fixed with https://github.com/wso2-extensions/identity-inbound-auth-openid/pull/74

**ehcache**

repository/components/features/org.wso2.carbon.ldap.server.server_6.2.5/feature.xml:6:  <plugin id="net.sf.ehcache" unpack="false" version="2.10.4"/>

Fixed with https://github.com/wso2-extensions/identity-userstore-ldap/pull/49

**json-smart, accessort-smart**

1. repository/components/features/org.wso2.carbon.identity.provider.server_5.6.0/feature.xml:11:  <plugin id="net.minidev.json-smart" unpack="false" version="2.3"/> 
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-openid/pull/74

2. repository/components/features/org.wso2.carbon.identity.provider.server_5.6.0/feature.xml:12:  <plugin id="net.minidev.accessors-smart" unpack="false" version="1.2"/> 
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-openid/pull/74

3. repository/components/features/org.wso2.carbon.identity.oauth.server_6.4.111/feature.xml:12:  <plugin id="net.minidev.json-smart" unpack="false" version="2.3"/> 
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1672

4. repository/components/features/org.wso2.carbon.identity.oauth.server_6.4.111/feature.xml:23:  <plugin id="net.minidev.accessors-smart" unpack="false" version="1.2"/> 
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1672

**asm**

1. repository/components/features/org.wso2.identity.utils_5.11.0/feature.xml:6:  <plugin id="org.objectweb.asm.all" unpack="false" version="5.2"/> 

2. repository/components/features/org.wso2.carbon.identity.oauth.server_6.4.111/feature.xml:7:  <plugin id="org.objectweb.asm.all" unpack="false" version="5.2"/> 
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1672

3. repository/components/features/org.wso2.carbon.humantask.server_4.5.37/feature.xml:13:    <import match="equivalent" plugin="org.objectweb.asm.all" version="5.2"/> 
Fixed with https://github.com/wso2/carbon-business-process/pull/635

4. repository/components/features/org.wso2.carbon.bpel.server_4.5.37/feature.xml:12:    <import match="equivalent" plugin="org.objectweb.asm.all" version="5.2"/>
Fixed with https://github.com/wso2/carbon-business-process/pull/635

5. repository/components/features/org.wso2.carbon.identity.provider.server_5.6.0/feature.xml:6:  <plugin id="org.objectweb.asm.all" unpack="false" version="5.2"/>
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-openid/pull/74

6. Need to change version range of asm in https://github.com/wso2/orbit/blob/master/membrane-soa-model/1.6.0.wso2v2/pom.xml#L60
Fixed with  https://github.com/wso2/orbit/pull/480
Fixed with https://github.com/wso2/carbon-business-process/pull/637

**yubico**
repository/components/features/org.wso2.carbon.identity.application.authenticator.fido2.server_5.2.8/feature.xml:7:  <plugin id="yubico-webauthn" unpack="false" version="1.3.0.wso2v3"/>

Fixed with https://github.com/wso2-extensions/identity-local-auth-fido/pull/70

\[1] https://github.com/wso2/orbit/blob/master/yubico-webauthn/1.10.1.wso2v1/pom.xml#L88-L91

Component versions update with https://github.com/wso2/product-is/pull/12480

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
