### ISSUE TITLE
Dependency Version Updates

### ISSUE THREAD

**Issue by bhagyasakalanka** [wso2/product-is#12485]
**Describe the issue:**
Need to update below dependencies to newer versions

- guava
- json-smart
- jackson-databind
- log4j-core
- jinjava
- jsoup
- groovy-all
- ehcache
- zookeeper
- xmlsec
- pax.logging
- wso2-orbit updates
- commons-io

**Comment by nilasini** [comment]
Related issue https://github.com/wso2/product-is/issues/12952

**Comment by nilasini** [comment]
@bhagyasakalanka Could you please update the status of the issue? Can we close the issue?

**Comment by bhagyasakalanka** [comment]
Initial planned dependency updates are done. But we need to keep our product up to date
