### ISSUE TITLE
E-mail regexps

### ISSUE THREAD

**Issue by stefannilsson** [wso2/product-is#1248]
Hi,
I believe some e-mail regexps' (at least in documentation) needs to be reviewed to allow new top-domains, more types of characters to the local-part of the email address. I also believe 30 max characters is a bit low?

https://docs.wso2.com/display/IS530/Using+Email+Address+as+the+Username
<Property name="UsernameJavaScriptRegEx">^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$</Property>
<Property name="UsernameJavaRegEx">a-zA-Z0-9@._-{3,30}$</Property>

**Comment by dewniMW** [comment]
Email regexps can be defined according to your preferences. The regex in the documentation is just given as an example. The 30 max character is no longer maintained (from 5.4.0 docs onwards). If we come across a more suitable regexp for email, we will update the docs accordingly.
