### ISSUE TITLE
DCR documentation in IS 5.5.0 uses v1.1, instead it should use v1.0

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12486]
**Is your suggestion related to a missing or misleading document? Please describe.**

In IS5.5.0, we are using DCRv1.0, https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v5.6.63/components/org.wso2.carbon.identity.oauth.dcr.endpoint/src/main/resources/api.identity.oauth.dcr.endpoint.yaml

But in the documentation, we have pointed to v1.1 https://docs.wso2.com/display/IS550/apidocs/OAuth2-dynamic-client-registration/#!/operations#OAuth2DCR#getApplication

If you try with some GET or PUT APIs which uses v1.0 as mentioned in the doc, it is not working.

**Describe the improvement**
Need to change the DCR API version. Seems like we are taking the same yaml file for all the versions of IS docs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
