### ISSUE TITLE
Issue with Git URL https://github.com/wso2/product-is.git 

### ISSUE THREAD

**Issue by skoyalada** [wso2/product-is#1249]
Getting below error

fatal: https://github.com/wso2/product-is.git/info/refs not valid: is this a git repository?
error: Could not fetch origin

While trying to check out the code

**Comment by omindu** [comment]
@skoyalada Did you experience this while cloning the repo? I just tried cloning the repo and it worked fine.

**Comment by skoyalada** [comment]
Issue is with my ssh keys. I recently moved to Windows 10 which wiped all my keys. closing the issue
