### ISSUE TITLE
IDP Management REST API patch operations are inconsistent

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12499]
**Describe the issue:**
The patch operations for some attributes are inconsistent. The responses and functionality is not uniform across certain operations.

For example,
1. JWKS URI update
    - PATCH REPLACE of non existent property returns 200 OK
    - PATCH ADD of existing property returns 400 and error code IDP-65005 - **this is expected**
    - PATCH REMOVE of non existent property returns 400 and error code IDP-65005

2. Certificate update
     - PATCH REPLACE of non existent property returns 400 and error code IDP-60025
     - PATCH REPLACE of existing property returns 200 - **this is expected**
     - PATCH REPLACE of existing property but of certificate index > 0 ("path":"/certificate/certificates/1") returns 400
     - PATCH ADD of existing property returns 200
     - PATCH ADD of certificate index > 1 ("path":"/certificate/certificates/2") returns 400 (i.e. it is not possible to add more than 2 certificates via the API)
     - PATCH REMOVE of certificate index > 0 returns 400

**Comment by ChanikaRuchini** [comment]
Following PATCH operations are work as expected.

- PATCH REPLACE of existing property but of certificate index > 0 ("path":"/certificate/certificates/1") returns 400
- PATCH ADD of certificate index > 1 ("path":"/certificate/certificates/2") returns 400 (i.e. it is not possible to add more than 2 certificates via the API)
- PATCH REMOVE of certificate index > 0 returns 400
