### ISSUE TITLE
Need proper backend support to identity URL fields

### ISSUE THREAD

**Issue by kayathiri4** [wso2/product-is#12501]
**Is your suggestion related to an experience ? Please describe.**
We need a proper backend support to identify the URL fields 
eg: `Callback URL`

**Describe the improvement**
Can get an additional attribute to verify the URL fields

**Additional context**
Currently the field is verified like:https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/identity-providers/components/forms/helpers/form-fields-helper.tsx#L500
**Current Response**
![Screenshot from 2021-09-13 12-14-07](https://user-images.githubusercontent.com/36656035/133036194-7ee5fbb4-3fd0-4017-b351-1ab5bf99a575.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
