### ISSUE TITLE
Need to add support for multi-attribute login when user store preference order extension is used

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12503]
**Describe the issue:**
The user store preference order is not considered when multi-attribute login is enabled.

**How to reproduce:**

- Enable multi-attribute login to use a claim like a mobile number.
- Add two secondary user stores, each having a user with the same mobile number.
- Configure the user store preference order extension[1] and bind one user store to a service provider.
- Try to log in using the mobile number to that service provider, the login would fail because during the user search by claim there are two users returned from each user store.

**Expected behavior:**
If the user store preference order is configured, the user store order should be taken into account.

**Environment information** **:**
 - Product Version: [IS 5.10.0, IS 5.11.0]
 
[1]https://medium.com/@nilasini/user-store-preference-order-per-service-provider-available-from-5-9-0-onwards-bcd7648a485c

**Comment by mpmadhavig** [comment]
Support for the case where we `allow when only the username is the only attribute allowed and the regex is not added`, should be added.
