### ISSUE TITLE
Integrate with external analytics solutions

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#12500]
**Is your suggestion related to a missing or misleading document? Please describe.**

- Need to document the $subject related to ELK stack.
- Also this should include a clear description on the data streams that we publish from the IS. 

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed: https://is.docs.wso2.com/en/latest/guides/elk-analytics/elk-analytics/
