### ISSUE TITLE
[RevocationEndpoint] Revocation endpoint returns 200 success response for revoked access tokens when client authentication is failed

### ISSUE THREAD

**Issue by Dinushi** [wso2/product-is#12510]
**Describe the issue:**

According to the [oauth2 Token Revocation specification: section 2.2](https://datatracker.ietf.org/doc/html/rfc7009#section-2.2), it is reasonable to respond with status code 200 for any revocation request with an already revoked/invalid token. But if a client authentication failure is detected, that authentication failure error should be returned to the user.  But currently, even if **the client authentication is failed**, the response is sent as 200 ok for revocation requests sent with a **revoked access token**.

**How to reproduce:**

1. Revoke a active access token -> verify the successful response as 200 and verify that the token is revoked by calling the introspection as well.
2. Revoke the same **access** token with a wrong 'aud' value in the client_assertion if private key jwt client authentication is engaged (invalid auth credentials if Basic Authentication is engaged ) -> verify the response with 200 status code.
(Please note that the token should always be a revoked access token. This is not reproducible to any active tokens or any revoked refresh tokens.)

**Expected behavior:**
If the client authentication is failed, even it is a **revoked access token** sent in the Revocation request, an error message indicating the client authentication failure should be returned.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
 - OS:  Linux
 - Database:  MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
