### ISSUE TITLE
Troubleshooting tip for Communications link failure  with MySQL

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12519]
**Is your suggestion related to a missing or misleading document? Please describe.**
If the following error was thrown in the WSO2 Identity Server even when the connection with the DB server is working fine,
```
Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

The following two properties in the MySQL connection URL could solve it.
```
autoReconnect=true
useSSL=false
```

The two properties can be added to each of the data sources and finally the connection URLs will look like below.
```
url = "jdbc:mysql://<hostname>:<port>/<db_name>?autoReconnect=true&amp;useSSL=false"
```

This can be added as a tip for troubleshooting in [1]. But this is only applicable when defining the `url` since these will be automatically added to the URL otherwise.

[1] https://is.docs.wso2.com/en/latest/setup/changing-to-mysql/

**Comment by nilminiwso2** [comment]
Need to move this content to the master branch and IS 6 branch.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
