### ISSUE TITLE
[RevocationEndpoint] The error responses thrown from Revocation Endpoint is having an invalid media-type

### ISSUE THREAD

**Issue by Dinushi** [wso2/product-is#12511]
**Describe the issue:**
In Token Revocation specification - [section 2.2.1. Error Response](https://datatracker.ietf.org/doc/html/rfc7009#section-2.2.1), the following is stated.

```
    The error presentation conforms to the definition in Section 5.2 of
    [RFC6749]. The following additional error code is defined for the
    token revocation endpoint:
```

Accordingly, any error response returned from the revocation endpoint should be adhered to the [Section 5.2](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2) of [RFC6749]. Here, it is mentioned that the reponse should be sent in "application/json" media type.

```
    The parameters are included in the entity-body of the HTTP response
    using the "application/json" media type as defined by [RFC4627].
```

But in the existing implementation, the error responses are returned in media type - **text/html**.

**How to reproduce:**

1. Send a token revocation request with invalid auth credentials and verify the content-Type header of the response as text/html.

**Expected behavior:**

The media type of errors should be **application/json**.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
