### ISSUE TITLE
Improve password hashing for JDBCUserStore

### ISSUE THREAD

**Issue by guiwoda** [wso2/product-is#1252]
[The docs](https://docs.wso2.com/display/IS530/Configuring+a+JDBC+User+Store) indicate that current hashing methods are `PLAIN_TEXT`, `MD5` and `SHA`. [All of these](http://plaintextoffenders.com/) [hashing methods](https://security.stackexchange.com/questions/19906/is-md5-considered-insecure) [are insecure](https://dusted.codes/sha-256-is-not-a-secure-password-hashing-algorithm) and should not be used to store passwords.

**Comment by soasecurity** [comment]
WSO2IS supports for salted hash with SHA-512.  Please find more details from [here](http://xacmlinfo.org/2015/06/10/user-password-hashing-with-wso2-identity-server-wso2is/)

**Comment by guiwoda** [comment]
SHA-512 is not secure either. Check [this link](https://dusted.codes/sha-256-is-not-a-secure-password-hashing-algorithm)

**Comment by santoshsas** [comment]
Does Wso2 provides bcrypt for hashing? As mentioned above SHA-512 is not secured.

**Comment by santoshsas** [comment]
we might endup not using WSO2 coz of this

**Comment by mohamednizar** [comment]
@pulasthi7 , @isharak , is this feature developed yet ? do you have an idea for implement this. I have a need for implement on this so I can contribute to this. Can you advice me to from where we can start ?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
