### ISSUE TITLE
IDP management REST API - Removing the certificate with index 0 with patch operation removes all the certificates of IDP

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12526]
**Describe the issue:**
Removing the certificate with index 0 with patch operation in IDP management REST API[1] removes all the certificates in IDP.

**How to reproduce:**

- Add a federated IDP and add the two certificates to the IDP. 
- Try to remove the certificate at index 0, "/certificate/certificates/0", The certificate at index 1 also gets removed.
- Alternatively, try to remove the certificate at index 1, " the following error is returned.

```
{"code":"IDP-60025","message":"Invalid input.","description":"One of the given inputs is invalid.","traceId":"358bec56-0a67-4b3e-a173-ba079cc624f2"}%
```

**Expected behavior:**
When the certificate at an index is removed, all certificates should not get removed. If there are other certificates after the index that is removed, they should be shifted to the left once so that the removed index is filled.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

[1]https://is.docs.wso2.com/en/5.10.0/develop/idp-rest-api/

**Comment by ashendes** [comment]
This issue was fixes with https://github.com/wso2/identity-api-server/pull/308.
Further improvements to these methods are coming with https://github.com/wso2/identity-api-server/pull/312
