### ISSUE TITLE
User portal change password does not work for tenant users

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12529]
**Describe the issue:**
User portal change password does not work for tenant users

**How to reproduce:**

- Add a new tenant and some users to the new tenant.
- Log in to the user portal of the tenant with a user added to the tenant and try to change the password.
- The call to the /t/<TENENT_DOMAIN>/api/identity/auth/v1.1/authenticate API fails as a result the password change fails.

**Fix :**
The "/api/identity/auth/v1.1/" path needs to be added as a TenantContextsToRewrite path.
```
    <TenantContextsToRewrite>
        <WebApp>
            <Context>/api/identity/user/v1.0/</Context>
            <Context>/api/identity/auth/v1.1/</Context>
            .......
            .......
```
The <IS_HOME>/repository/resources/conf/default.json should be updated to include the "/api/identity/auth/v1.1/" path.
```
  "tenant_context.rewrite.webapps": [
    "/api/identity/user/v1.0/",
     "/api/identity/auth/v1.1/",
      .......
      .......
  ],
```

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by GANGANI** [comment]
This is not reproducible in 5.11 or latest IS-pack. Hence closing the issue.
