### ISSUE TITLE
Password Reset - With Challenge page refers to the user-portal link

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#12532]
**Is your suggestion related to a missing or misleading document? Please describe.**
The [Password Reset - With Challenge](https://is.docs.wso2.com/en/latest/learn/configuring-password-reset-with-challenge/) page informs to move to the user portal link which is `https://localhost:9443/user-portal/` but if you visit this link with IS 5.11.0 you'll see an empty page.

**Describe the improvement**
The link should be changed to the myaccount link which is `https://localhost:9443/myaccount/`.

**Comment by deshankoswatte** [comment]
There are several other pages this has been used too, might have to fix all of them.

**Comment by nilminiwso2** [comment]
This seems to be fixed in the latest docs as well as IS 5.11. Therefore, closing the issue.
