### ISSUE TITLE
Improvement to TOTP Authenticator feature

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#12530]
This issue will be used to track efforts on improving the TOTP Authenticator feature to enhance on consumer experience. 

- [x] [Introduce **totpEnabled** claim to mark whether user has configured a TOTP Authenticator](https://github.com/wso2/carbon-identity-framework/pull/3731)
- [x] [Improve the TOTP key generator with this new claim](https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/111) 
- [x] [Introduce claim in scim configs](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/388)
- [ ] [Migration for introduced claim ()

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
