### ISSUE TITLE
OAuth2 DCR PUT Endpoint returns non-json error response when request payload is invalid

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#12544]
**Describe the issue:**
If the payload is incorrect/invalid for the OAuth2 DCR PUT endpoint [1], a non-json response will be returned (refer to the following example). The specification describes that the error should be a json response [2].

```
Unrecognized field "nothing" (class org.wso2.carbon.identity.oauth2.dcr.endpoint.dto.UpdateRequestDTO), not marked as ignorable (8 known properties: "token_type_extension", "client_secret", "grant_types", "redirect_uris", "client_name", "backchannel_logout_uri", "client_id", "backchannel_logout_session_required"])
 at [Source: (org.apache.cxf.transport.http.AbstractHTTPDestination$1); line: 2, column: 17] (through reference chain: org.wso2.carbon.identity.oauth2.dcr.endpoint.dto.UpdateRequestDTO["nothing"])
```

**How to reproduce:**

1. Create a request to the DCR endpoint with invalid/incorrect format.
```
curl --location --request PUT 'https://localhost:9443/api/identity/oauth2/dcr/v1.1/register/client_id' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --header 'Content-Type: application/json' --data-raw '{
    "nothing": ""
}'
```
2. Error response content type is text/plain instead of json.

**Expected behavior:**
A JSON error response should return when the payload is incorrect.

**Environment information:**
 - Product Version: IS 5.11.0

---

[1] - https://docs.wso2.com/display/IS511/apidocs/OAuth2-dynamic-client-registration/#!/operations#OAuth2DCR#updateApplication
[2] - https://datatracker.ietf.org/doc/html/rfc7591#section-3.2.2

**Comment by nilasini** [comment]
@ayeshajay do we have any config changes which needs to be send to public? Could you please link the PR?
