### ISSUE TITLE
Deleting all claims from an OIDC scope removes the scope from the list

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#12547]
**Describe the issue:**
When deleting all claims from an OIDC scope the scope disappears from the list, however the scope still exists on the database.

**How to reproduce:**
- On the Management Console go to _Manage > OIDC Scopes > List_
- Click _Update_ on the _openid_ scope
- Select all claims, click on _Remove_ and then click on _Finish_

**Expected behavior:**
When deleting all claims from an OIDC scope, the scope should remain on the list to give the user a chance to reconfigure it.

**Environment information:**
 - Product Version: IS 5.8.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
