### ISSUE TITLE
Same site cookie configurations are not mentioned in the offficial doc

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#12550]
**Is your suggestion related to a missing or misleading document? Please describe.**
Same site cookie configurations are not mentioned in the offficial doc https://is.docs.wso2.com/en/latest/administer/samesite-attribute-support/
But it is mentioned in this blog post https://wso2.com/blogs/thesource/2020/01/samesite-attribute-support-in-wso2-products/

[catalina.valves.valve.properties]
className = "org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve"

We need to update official documentations of 5.10.0, 5.11.0 etc
**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
