### ISSUE TITLE
Upgrade handlebars to latest version v4.7.7.js

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/product-is#12557]
**Description:**
Latest handlebars version has been released which is v4.7.7. Hence it is required to upgrade all occurrences of handlebars to the latest version.

Additionally, carbon-metrics which also has a handlebars dependency usage, has an older version of findbugs maven plugin  which results in repository build failure. hence need to upgrade it as well.

**Comment by nilasini** [comment]
@Yasara-Y Can we close this issue?
