### ISSUE TITLE
Multi attribute login not working for email 

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-is#12558]
**Describe the issue:**
 I followed the doc 
https://is.docs.wso2.com/en/5.12.0/learn/multi-attribute-login/#!

**How to reproduce:**
I was able to log in with the user name and phone number that I defined in the user's profile.
When I tried with email its failed.

 - Product Version: IS 5.11.0. 68
 - OS: Mac
 - Database: H2
 - Userstore: primary

**Comment by geve82** [comment]
Hi Laslo,

it is working for me but it is not user friendly. You need to add in your deployment toml :

`
[tenant_mgt]
enable_email_domain= true
`
and in the login form to add the domain after the email address name like : 

`
my.name@mycompany.com@super.tenant
`

**Comment by ShanikaWickramasinghe** [comment]
As mentioned in [1] "Using email address as the login attribute for super tenant users" you have to append carbon.super while you using multi attribute login with email address for super tenant. appending "carbon.super" will resolve the issue. Verified the flow with 5.12.0 alpha 16 pack and flow works as expected against latest 5.12.0 alpha 16 pack.

[1] https://is.docs.wso2.com/en/5.12.0/learn/multi-attribute-login/

**Comment by nilasini** [comment]
Closing the issue as per the above comment
