### ISSUE TITLE
Shouldn't consider `roles` attribute as a core attribute of Group resource

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12553]
**Describe the issue:**

IS consider  `roles` attribute as a core attribute of Group resource, but it should not be a core attribute as per https://datatracker.ietf.org/doc/html/rfc7643#section-4.2
`displayName` and `members` are the core attributes of `urn:ietf:params:scim:schemas:core:2.0:Group`
`roles` need to be considered as an attribute in an extended schema of Group resource.

**How to reproduce:**
1. Create a user
```
curl --location --request POST 'https://localhost:9443/scim2/Users' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "userName": "alex",
    "password": "alex123",
    "name": {
        "familyName": "Alex"
    }
}'
```

2. Create a group (replace the user id in the members section)
```
curl --location --request POST 'https://localhost:9443/scim2/Groups' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "displayName": "EngineeringTeam",
     "members": [
        {
            "value": "d7360199-f48e-45b5-8251-de4e5ea4b209"
        }
    ],
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ]
}'
```
3. Create a role, assigning that role to a group (Replace the group id)
```
curl --location --request POST 'https://localhost:9443/scim2/Roles' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "displayName": "Developer",
    "groups": [
        {
            "value": "fba64a51-5b6a-429f-89f3-1758a7ab836f"
        }
    ],
    "permissions": [
        "/permission/admin/login"
    ],
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:2.0:Role"
    ]
}'
```
4. Retrieve the created group in step 2 (change the group id accordingly)
```
curl --location --request GET 'https://localhost:9443/scim2/Groups/fba64a51-5b6a-429f-89f3-1758a7ab836f' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

The response of the Group is similar to the following:
```
{
    "displayName": "EngineeringTeam",
    "meta": {
        "created": "2021-09-21T19:57:23.972Z",
        "location": "https://localhost:9443/scim2/Groups/fba64a51-5b6a-429f-89f3-1758a7ab836f",
        "lastModified": "2021-09-21T19:57:23.972Z"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ],
    "members": [
        {
            "display": "alex",
            "value": "d7360199-f48e-45b5-8251-de4e5ea4b209",
            "$ref": "https://localhost:9443/scim2/Users/d7360199-f48e-45b5-8251-de4e5ea4b209"
        }
    ],
    "roles": [
        {
            "display": "Developer",
            "value": "e8258724-b7b4-430b-a7d5-49595c273b85",
            "$ref": "https://localhost:9443/scim2/Roles/e8258724-b7b4-430b-a7d5-49595c273b85"
        }
    ],
    "id": "fba64a51-5b6a-429f-89f3-1758a7ab836f"
}
```
As per the above response we are considering `roles` as a core attribute in Group Resource, but it's not as per the specification. https://datatracker.ietf.org/doc/html/rfc7643#section-4.2

`roles` need to be considered as an attribute in an extended schema of Group resource

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-alpha3
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
