### ISSUE TITLE
From 5.12.0 Auto login after password reset will work only if the access url is configured for the application.

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#12561]
**Describe the issue:**
Due to the session nonce cookie validation in the authentication flow, If someone starts an authentication flow from one browser and invoke the password reset. Then open then opens the password reset mail in a different browser and complete the password reset. Then when we redirect back to the login page of the application, the login flow can't be continued in the new browser. Because the session-nonce cookie is not present in the new browser. This is due to a security improvement to bind the authentication flow to a particular browser. 

Due to this, auto-login after password reset also will work. So we have enforced a requirement to have an access URL for the application if the auto-login after password reset is enabled.

**Comment by piraveena** [comment]
If the apps have access URLs, then autologin can work in cross-browsers as well. But if the apps don't have access URLs configured, then it won't work even if we enable auto login config. 

@senthalan  To fix this issue, if the apps have access URLs, then can do cross-browser auto logins, But if they don't configure and if the sessionData key is present in the callback URL, then the autologin can work. We introduced this with the PR https://github.com/wso2/identity-apps/pull/2881. If the auto-login is tried in the same browser, then the nonce-cookie issue will not be there.

**Comment by piraveena** [comment]
@ashendes @senthalan we don't need this migration issue now. We have added the previous behaviour back.

**Comment by ashendes** [comment]
Closing migration issue to the negation of migration impact made by later fixes.
