### ISSUE TITLE
Disabling IDP on the management console removes certificates

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#12566]
**Describe the issue:**
When creating an IDP with multiple certificates, only one certificate is kept after disabling the IDP.
This is the same behavior reported at #12421 but in that case the fix was only applied to the REST API.

**How to reproduce:**
- Create an IDP with two or more certificates (via management console).
- Disable the IDP (via management console).

**Expected behavior:**
Certificate information should remain the same when enabling/disabling the IDP.

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
