### ISSUE TITLE
Enterprise IDP login ends up with authentication error

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#12569]
How To Reproduce:

Create an enterprise IDP.
Setup an application and add the IDP to signin method
Try out a sample with that Application.
Please note - you may use either OIDC or SAML.

Expected behavior:
Users should be able to login without any failure.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
