### ISSUE TITLE
Account Disabling document contains redundant steps

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12563]
**Is your suggestion related to a missing or misleading document? Please describe.**
The following steps in the document [1] can be removed
- Step 1.a under setup (it is set by default)
- Step 2 under Try Out (login permission is not required to test this)

[1] https://is.docs.wso2.com/en/latest/learn/configuring-account-disabling/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
