### ISSUE TITLE
meta attribute is missing in the response of GET `/Roles/<role-id>?attributes=<attributes>` requests 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12575]
**Describe the issue:**

1. Create a role with users, groups, permissions
2. Get the role by id -> This contains the meta attribute (but some sub-attributes are missing https://github.com/wso2/product-is/issues/9177)
```
curl --location --request GET 'https://localhost:9443/scim2/Roles/e8258724-b7b4-430b-a7d5-49595c273b85' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

3. Get the role by id excluding some attributes -> This contains the meta attribute (but some sub-attributes are missing https://github.com/wso2/product-is/issues/9177)
```
curl --location --request GET 'https://localhost:9443/scim2/Roles/e8258724-b7b4-430b-a7d5-49595c273b85?excludedAttributes=permissions,users' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

:exclamation:  4. Get the role by id by specifying some attributes  -> The response **doesn't contain** the meta attribute 
```
curl --location --request GET 'https://localhost:9443/scim2/Roles/e8258724-b7b4-430b-a7d5-49595c273b85?attributes=permissions' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.12.0-alpha
 - OS:  Linux
 - Database: H2
 - Userstore:  LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
