### ISSUE TITLE
Application creation and deletion atomic

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#12579]
**Describe the issue:**
The current implementation of the application creation process is not atomic. Therefore, if an error occurs, there is a chance that the database gets updated partially. This needs to be fixed by making these flows atomic.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
