### ISSUE TITLE
Created users can not navigate to my account security section. Something went wrong

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#12583]
**Describe the issue:**
Created users can not navigate to my account security section. Something went wrong

![Selection_999(2269)](https://user-images.githubusercontent.com/39077751/134946698-9a341463-777e-41c7-90c4-21c17643d1ba.png)

**How to reproduce:**
1. Login to management console
2. Create user
3. Login to my account
4. Navigate to security page

**Expected behavior:**
User should be able to navigate to the security page successfully. 

Product version: https://wso2.org/jenkins/view/products/job/products/job/product-is/3735/

**Comment by sumedhe** [comment]
This issue is not reproducible after the identity-apps version `1.2.621`
