### ISSUE TITLE
Remove Shutdown/Restart option from the IS management console UI

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#12587]
**Is your suggestion related to an experience ? Please describe.**
- Remove Shutdown/Restart option from the IS management console UI
- The service also needs to be blocked 

![Screenshot 2021-09-13 at 17 57 15](https://user-images.githubusercontent.com/13478571/135098533-8e226ebd-f0ea-4235-b9f1-7040bec3b784.png)
![Screenshot 2021-09-13 at 17 58 38](https://user-images.githubusercontent.com/13478571/135098558-28da7ec3-a5ef-44d1-9287-8dea105d8331.png)

**Describe the improvement**

**Additional context**

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/product-is/pull/12637

**Comment by ashensw** [comment]
@nilasini we have disabled the UI from the above fix. Shall we also check whether this can be still done via a SOAP call? If possible we need to block that also.

**Comment by IsuraD** [comment]
Need to disbale SOAP API
