### ISSUE TITLE
IS Analytics dashboard not displaying data in real time

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#12594]
**Describe the issue:**
The dashboard of IS Analytics 5.8 is not showing data in real time. Data in the widgets is only updated when the dashboard is restarted.

**Environment information****:**
 - Product Version: IS Analytics 5.8.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
