### ISSUE TITLE
Support email login without appending tenant domain for non-SaaS apps

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#12601]
**Describe the issue:**
For the authentication requests going to the non-saas apps, it should not be mandatory to append the tenant domain to the login email address as the tenant domain can be resolved using the request service provider. Currently the basic authentication, and identifier first authentication flows are working as expected. The following flows also should be updated accordingly.

- [ ] OAuth Password grant
- [ ] Request path authenticator - OAuth
- [ ] Request path authenticator - Basic auth

**How to reproduce:**
1. Register an application without enabling SaaS.
2. Enable email as username (without enabling the flag `enable_email_domain = true`)
2. Try to send authentication requests using the mentioned flows with the email address without appending the tenant domain.
3. It will fail with detecting the email domain as the tenant domain.
   ```
    curl --location --request POST 'https://localhost:9443/oauth2/token' \
    --header 'Authorization: Basic QUluckJyZEZlSHEzMEcwU0h1VXhzNEkwT2ZrYTpLcTU5WmlaTGdKc2dJTVRvbFFQZGNTY1JiR3Nh' \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode 'grant_type=password' \
    --data-urlencode 'username=alice@wso2.com' \
    --data-urlencode 'password=admin' \
    --data-urlencode 'scope=openid internal_login'

    curl --location --request POST 'https://localhost:9443/oauth2/token' \
    --header 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
    --header 'Authorization: Basic QUluckJyZEZlSHEzMEcwU0h1VXhzNEkwT2ZrYTpLcTU5WmlaTGdKc2dJTVRvbFFQZGNTY1JiR3Nh' \
    --data-raw 'grant_type=password&username=alice@wso2.com&password=admin'

**Expected behavior:**
Those requests should be accepted as the tenant domain can be resolved with the app owner tenant.

**Comment by nilasini** [comment]
@sumedhe can we close this issue? Anything pending?

**Comment by sumedhe** [comment]
We can close this issue.
