### ISSUE TITLE
Writing a Custom User Store Manager doc needs to support UniqueID

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12607]
**Is your suggestion related to a missing or misleading document? Please describe.**
The document [1] describes writing a custom userstore manager is not up to date. It starts with old userstore methods and finally describes UniqueID classes. 

It needs to mentioned new userstore methods which need to be implemented or overridden.

[1] https://is.docs.wso2.com/en/latest/setup/writing-a-custom-user-store-manager/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
