### ISSUE TITLE
Incorrect configuration on 'Managing Claims with APIs' document

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#12605]
**Description:** 
Incorrect deployment.toml configuration for revealing WSDLs of hidden admin services:
- Managing Claims with APIs > Invoking the admin service [[1]](https://is.docs.wso2.com/en/latest/develop/managing-claims-with-apis/#invoking-the-admin-service)

**Describe the improvement**
Update the incorrect configuration from enable = false to enable = true

**Product versions:** 
- IS 5.9.0
- IS 5.10.0
- IS 5.11.0
- IS 5.12.0

Reference:
[1] https://is.docs.wso2.com/en/latest/develop/managing-claims-with-apis/#invoking-the-admin-service

**Comment by nilminiwso2** [comment]
For IS 6, we will address this using this issue [1].

[1] https://github.com/wso2/product-is/issues/14885
