### ISSUE TITLE
Improvements in OAuthCache

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12610]
**Is your suggestion related to an experience ? Please describe.**
**Improvements**

- [ ] Fix cache key - hash the string and store. Now we store it as a String object. (eg: MY_ACCOUNT:745d41a5-a974-44f3-849b-7de8148cffa2:internal_login openid:LOCAL:e4cea72f9bbfcbbbbcfb42a64911ec55  )
- [ ] Unnecessary cache keys clearing logic. We need to remove all the unnecessary logics that are not used
- [ ] Remove username and use userId in all OAuthCache flows
- [ ] Test for all grants (such as implicit, device code, ciba)  and all the flows involve around OAuthCache
- [ ] In the introspection flow, the token is not retrieved from OAuthCache when accessing tenant apis (on prem) since the tenant could not be resolved.

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
