### ISSUE TITLE
Issue while adding multiple tenant_context.rewrite.webapps and tenant_context.rewrite.custom_webapps

### ISSUE THREAD

**Issue by maneeshaindrachapa** [wso2/product-is#12626]
## **Issue**
In the current `<IS_HOME>/repository/resources/conf/templates/repository/conf/identity/identity.xml.j2` file , `TenantContextsToRewrite` template is described as below.

```
<TenantContextsToRewrite>
    <WebApp>
        {% for webapp in tenant_context.rewrite.webapps %}
        <Context>{{webapp}}</Context>
        {% endfor %}
        {% for webapp in tenant_context.rewrite.custom_webapps %}
        <Context>{{webapp}}</Context>
        {% endfor %}
    </WebApp>
    ....
</TenantContextsToRewrite>
```
And the values are mapped to the `identity.xml` from the `default.json` file which is also in the `<IS_HOME>/repository/resources/conf` directory.

The issue here is if when multiple `tenant_context.rewrite.webapps` or `tenant_context.rewrite.custom_webapps`` config is given in the `deployment.toml` file the values will not apply one by one.

## **How to reproduce**
1. Get the latest **WSO2IS-5.10.0** Pack.
2. Start the IS once and make note of the configs in the `TenantContextsToRewrite` tag in `identity.xml`.
3. Then add the following config to the `deployment.toml` file and restart the server and recheck the config in the `identity.xml`
```
[tenant_context.rewrite.webapps]
webapp=["/api/identity/example/v01", "/api/identity/example/v02"]


[tenant_context.rewrite.custom_webapps] 
webapp=["/api/identity/example/v03", "/api/identity/example/v04"]
```
4. The `identity.xml` will show the below changes.
```
<TenantContextsToRewrite>
        <WebApp>
            <Context>[/api/identity/example/v01, /api/identity/example/v02]</Context>
            <Context>[/api/identity/example/v03, /api/identity/example/v04]</Context>
        </WebApp>
        ....
</TenantContextsToRewrite>
```
5 . It needs to be in the below way.
```
<TenantContextsToRewrite>
        <WebApp>
            <Context>/api/identity/example/v01</Context>
            <Context>/api/identity/example/v02</Context>
            <Context>/api/identity/example/v03</Context>
            <Context>/api/identity/example/v04</Context>
        </WebApp>
        ....
</TenantContextsToRewrite>
```
## **Suggestions to fix**
Change the way read the configurations in `identity.xml.j2` file, to split by `,` and apply it to the `identity.xml` file.

**Comment by ShanChathusanda93** [comment]
Hi @maneeshaindrachapa,
The following config that you mentioned in the description is not in the correct format.
``` [tenant_context.rewrite.webapps]
webapp=["/api/identity/example/v01", "/api/identity/example/v02"] ```
Instead of that you can use the following config if you need.
``` [tenant_context.rewrite]
webapps=["/api/identity/example/v01", "/api/identity/example/v02"] ``` 
The reason is this is a config which renders an array.

Thanks,
Shan.
