### ISSUE TITLE
Issue in Setting claims of the request Object to OAuth2 parameters in Authorize endpoint

### ISSUE THREAD

**Issue by Ashi1993** [wso2/product-is#12631]
**Describe the issue:**
Claims object sent in the request object is not setting correctly to the OAuth2 parameters. As per current implementation, claims are retrieved from the request object as a string value but it is sent as object.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
