### ISSUE TITLE
Behavioral change with Maintaining the internal scopes system level

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#12635]
With Refer https://github.com/wso2/product-is/issues/12617 change, the internal scope permission binding will be managed at the server level as system data (in oauth-scope-bindings.xml file). All tenants will use this system data. We will consider all the bindings available in oauth-scope-bindings.xml as internal scope entry.

This change will be done by default from 5.12.0. If someone wants the previous behaviour, they can use the following config,
```
[oauth]
enable_system_level_internal_scope_management=false
```

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
