### ISSUE TITLE
Optional claims cannot be removed from introspection endpoint

### ISSUE THREAD

**Issue by Ashi1993** [wso2/product-is#12632]
**Describe the issue:**
Introspection response have mandatory and optional parameters according to [1]. But as per the current implementation, we cannot remove optional parameters from the response.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
