### ISSUE TITLE
Improvements to Secrets API

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#12643]
**Description:**
It was discussed to done several changes to the secret management API and Framework component. 
- Secrets type API will be removed and secret types will be stored in the framework.
- Secrets API definition will be changed.
- secret type `ADAPTIVE_AUTH_CALL_CHOREO` will be renamed to `ADAPTIVE_AUTH`

This issue will track the development tasks.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
