### ISSUE TITLE
Underscore in claim values considered wildcard

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#12649]
**Describe the issue:**
When a user is searched with the claim value, having an underscore, it's considered as a single character wildcard when querying from the DB, in [`getUserListFromProperties()`](https://github.com/wso2/carbon-kernel/blob/v4.4.40/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L2816) method, with the query configured for `GetUserLisForPropertySQL`.
Ex: Assume the givenName of a user is: `test_one`. When a user with `test_one` is searched, it returns users with the givenName values: `test_one`, `test1one`, `testxone`.

**How to reproduce:**
1. Create users as per the above example
2. Search with `test_one` from the management console for the particular claim.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
