### ISSUE TITLE
Console: Error creating new user

### ISSUE THREAD

**Issue by cannontechnology** [wso2/product-is#12667]
**Describe the issue:**
Clicking "New User" when logged in with restricted permissions throws the following error --> "An error occurred while retrieving governance connector."
![image](https://user-images.githubusercontent.com/3844488/136994988-8610be10-703a-4e30-a231-dd98ad6be2c2.png)

**How to reproduce:**
Create a user with minimum permissions to add a new user then login with that user and try to add a new user.

**Expected behavior:**
Expect the above to work

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0
 - OS: Windows and Linux
 - Database: Postgress 
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
Properly handle less privileged users inside Console features #10473

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
