### ISSUE TITLE
Console: Error when removing Account Management Permissions

### ISSUE THREAD

**Issue by cannontechnology** [wso2/product-is#12669]
**Describe the issue:**
The console does not work if account all management permissions are removed.  A minimum of view permission on account management is needed.

**How to reproduce:**
Remove all account management permissions to a role.  Assign that role to a user.  Log in as that user. 

**Expected behavior:**
Expect to log into the console with the "Manage" tab disabled or removed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0
 - OS: Windows & Linux
 - Database: Postgres
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
Properly handle less privileged users inside Console features #10473

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
