### ISSUE TITLE
`sf-password` & `sf-client-secret` property of Salesforce outbound provisioning connector needs to be confidential

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#12676]
**Is your suggestion related to an experience ? Please describe.**
When we get Salesforce outbound provisioning metadata using Identity Provider Management API, for `sf-password` & `sf-client-secret` properties we get it as a not confidential value.

**Describe the improvement**
Following properties of salesforce outbound provisioning connector needs to be confidential.

- [ ] sf-password
- [ ] sf-client-secret
- [ ] sf-password type also needs to be change.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
