### ISSUE TITLE
Doc Feedback: Link to OSGI sample project is not accessible.

### ISSUE THREAD

**Issue by rsea** [wso2/product-is#12670]
Location : https://is.docs.wso2.com/en/5.11.0/develop/user-store-listeners/

Link to the OSGI framework sample project is not accessible. (https://svn.wso2.org/repos/wso2/people/asela/user-mgt/custom-listener/)
Error is:
`Forbidden
You don't have permission to access /repos/wso2/people/asela/user-mgt/custom-listener/ on this server.`
Can you fix the link, please?

Thank you,
Ricardo

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
