### ISSUE TITLE
isUnique is not considered when multiple values are added for a claim

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#12683]
**Describe the issue:**
isUnique is not considered when multiple values are added for a claim. WSO2 Identity Server partially supports uniqueness in multi valued claims. For an example, “0123456789,9876543210” this multi valued claim set on a specific user could disallow other users from using values such as the following for that claim:
- 0123456789
- 9876543210

But it will allow the following values on other users without an error:
- 0123456789,9876543210
- 9876543210,0123456789

**How to reproduce:**
- Setup Multi Attribute Login [1] with Uniqueness Enabled [2].
- Configure telephone number as unique.
- Try to add the same two numbers for two users (Succeeds but it should actually fail).
- Login from telephone number and see the first user in the list gets authenticated without issue.

**Expected behavior:**
Uniqueness should be considered even if multiple values are added. Also authentication should fail when there are multiple users with the same claim values (when isUnique is true). Also need to look at the userstore type (This may change if JDBC is used).

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0
 - OS: Ubuntu 20.04.3 LTS
 - Database: H2
 - Userstore: LDAP

[1] - [https://is.docs.wso2.com/en/latest/learn/multi-attribute-login/#multi-attribute-login](https://is.docs.wso2.com/en/latest/learn/multi-attribute-login/#multi-attribute-login)
[2] - [https://is.docs.wso2.com/en/5.11.0/learn/configuring-uniqueness-of-claims/](https://is.docs.wso2.com/en/5.11.0/learn/configuring-uniqueness-of-claims/)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
