### ISSUE TITLE
Redirection issue when hosting TOTP Authentication Endpoint app on external server

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#12684]
**Describe the issue:**
When hosting the totpauthenticationendpoint app on a external server and setting TOTPAuthenticationEndpointURL, TOTPAuthenticationEndpointErrorPage and TOTPAuthenticationEndpointEnableTOTPPage properties on deployment.toml file to point to the external server, WSO2 IS appends the server hostname before the TOTP authentication endpoint URL.

**How to reproduce:**
- Add following lines to deployment.toml
```
[authentication.authenticator.totp.parameters]
TOTPAuthenticationEndpointURL="http://localhost:8080/totpauthenticationendpoint/totp.jsp"
TOTPAuthenticationEndpointErrorPage="http://localhost:8080/totpauthenticationendpoint/totpError.jsp"
TOTPAuthenticationEndpointEnableTOTPPage="http://localhost:8080/totpauthenticationendpoint/enableTOTP.jsp"
```
- Add or update a service provider and enable 2FA (basic & TOTP) for the SP.
- Add or update a user and enable TOTP for the user. To enable the TOTP authenticator:
  - Log into /myaccount portal with user's credentials.
  - On the security section go to multi-factor authentication, click on the Show the QR code action for via Authenticator App option.
  - Scan the QR code with an authenticator app.
- Login to the SP app with user's basic credentials. _At this step you'll be redirected to https://localhost:9443/http://localhost:8080/totpauthenticationendpoint/totp.jsp instead of http://localhost:8080/totpauthenticationendpoint/totp.jsp_

**Expected behavior:**
TOTP authenticator should validate whether endpoint URLs are absolute URLs and in such cases leave configured value as is.

**Environment information:**
 - Product Version: IS 5.11.0.75

**Comment by IsankaSR** [comment]
This is already fixed in the public branch.
