### ISSUE TITLE
Claims requested through scope parameter should not be available in the ID Token for flows issuing an Access Token

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#12696]
**Describe the issue:**
For requests where an access token is issued, the requested claims through the scope parameter are currently available in the id_token which is considered as an unintended exposure of user data by the OIDC Conformance Suite.  

According to the [OIDC Specification - Section 5.4](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims), the claims requested by the scope parameter are returned from the User info endpoint, when a response_type value is used that results in an Access Token being issued (All the flows except `id_token`). However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token because it is not possible to obtain them through the user info endpoint. 

**How to reproduce:**
1. Send an authorization request with `response_type=code id_token` and `scope=openid email`
Example request:
`https://localhost.com:9443/oauth2/authorize?client_id=qLczTJrGUomvnypu88RLoZbEX2Ia&redirect_uri=https://localhost.emobix.co.uk:8443/test/a/test/callback&scope=openid%20email&state=bGyRRmzjTQ&nonce=KKawgq6XTP&response_type=code%20id_token`
2. Login using admin admin credentials.
3. Extract the id_token from the response url.
4. Decode the ID Token using [jwt.io](jwt.io) and check the list of claims.

**Expected behavior:**
For the above response_type, since an authorization code is issued which can be used to obtain an access token, the requested claims can be obtained through the userinfo endpoint. Therefore email claim should not be returned through the id_token.

**Comment by DMHP** [comment]
@ImalshaG To get a better understanding, here we will get email in the id token as we have added the email as a scope is that the case? In that case if we map claims country and email for the scope email, the claims country and email will be added to the id token right? Can you please elaborate on this ?

**Comment by ImalshaG** [comment]
In this case, since the response_type is `code id_token`, we can obtain the email claim using the user info endpoint (using the code to get an access token and then using this access token to call the user info endpoint). Therefore we should not send the email claim inside the id_token here. If there is a possibility to call the user info endpoint, the requested claims should only the retrieved using that. These claims should be available in id_token only if we can't retrieve them through the user info endpoint (for response_type=id_token).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
