### ISSUE TITLE
Claims not found in id_token for Implicit requests with claims as essential

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#12695]
**Describe the issue:**
According to the [OIDC Specification - 5.5.1 Section](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.5.1), when a claim is requested through the 'claims' parameter as an Essential Claim inside the id_token, 
eg: `"claims": {
    "id_token": {
      "name": {
        "essential": true
      }
    }
  }`
 the requested claim should be available in the ID Token. But the decoded id_token does not have the requested claims. 

**How to reproduce:**
1. Send a request to the authorization server with `scope=openid`, `response_type=id_token` and `"claims": {
    "id_token": {
      "name": {
        "essential": true
      }
    }
  }`
Example request:
`https://localhost.com:9443/oauth2/authorize?client_id=H3WH3xR6zMT6PSPceYCSkSfZPJsa&redirect_uri=https://localhost.emobix.co.uk:8443/test/a/test/callback&scope=openid&state=q6XgeiUcrS&nonce=50GIbg19yt&response_type=id_token&claims=%7B%22id_token%22:%7B%22name%22:%7B%22essential%22:true%7D%7D%7D `

2. Extract the id_token from the response Url and decode the id_token using [jwt.io](jwt.io).
3. Check the returned claims.

**Expected behavior:**
'name' attribute should be available in the id_token

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
