### ISSUE TITLE
Doc Feedback: Error downloading example files

### ISSUE THREAD

**Issue by raipie** [wso2/product-is#12692]
Location : https://is.docs.wso2.com/en/5.10.0/learn/working-with-mdp-requests-to-authorize-hierarchical-resources/

When I try to download the web-filter-policy-for-resource-1.xml example file, I get this error:

Forbidden
You don't have permission to access /repos/wso2/people/asela/xacml/sample/web-filter/resources/hierarchical/web-filter-policy-for-resource-1.xml on this server.

What is the new location for this file ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
