### ISSUE TITLE
Removing unnecessary steps in "Changing the hostname" doc

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12702]
The document [1] is having a lot of steps related to certificates and internal_hostname. But with the fix for https://github.com/wso2/product-is/issues/12577, there is no need to include localhost as a SAN. Because internal_hostname is localhost by default and it will work without any certificate changes if the internal_hostname is not configured at all.  

Therefore, 5.11.0 and later documents can be made the same as 5.10.0 once https://github.com/wso2/product-is/issues/12577 is fixed.

Nevertheless, option 02 is incorrect in [1]. Because if the internal_hostname is configured as is.dev.wso2.com, it will try to connect to `is.dev.wso2.com:9443` all the time and will start to fail when there is a proxy configured unless a hosts entry is routing is.dev.wso2.com to local IP.

[1] https://is.docs.wso2.com/en/latest/setup/changing-the-hostname/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
