### ISSUE TITLE
Add relevant deployment.toml configs for `Configuring My Account Application` documentation

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12704]
**Is your suggestion related to a missing or misleading document? Please describe.**
Improve this documentation with relevant `deployment.toml` configurations
https://is.docs.wso2.com/en/5.11.0/develop/configure-my-account/

Questions raised based on this document:
https://wso2is.slack.com/archives/CDWPC5MUL/p1634931358012400

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
