### ISSUE TITLE
WSO2IS 5.10.0 Add new SP creates ORA-00918 in service provider list page in Management Console

### ISSUE THREAD

**Issue by robertociuccigiuliani** [wso2/product-is#12719]
**Describe the issue:**
I integrated Identity Server 5.10 with API Manager 3.1 in containerized environment of Openshift (Kubernetes) , like deployment pattern 2 old style: 2 instance is-as-km, 2 instance api gateway, 2 instance api mgtm pub/devportal/traffic-manager.
We have already created some SP definitions in the past and everything worked properly. One day, we add a new SP, after saving the SP list is empty and when refreshing the SP list page we receive (ORA-00918: column ambiguously defined).

**How to reproduce:**
I integrated Identity Server 5.10 with API Manager 3.1 for containerized environment.
Start Identity Server and API Manager 3.1
We have already created some SP definitions in the past and everything worked properly.
With random frequency , we add a new SP, after saving the SP list is empty and when refreshing the SP list page we receive (ORA-00918: column ambiguously defined).
Subsequently if slogged from system Identity Server and re-logged in the system with admin credentials,I see the complete list of service providers again, except the one I had created previously.

**Expected behavior:**
Create SP without problem or exception, and see the complete visible list of SPs after creating a new SP

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-AS-KM 5.10.0
 - OS: Ubuntu TLS (from image docker adoptopenjdk:11.0.7_10-jdk-hotspot-bionic)
 - Database: Oracle Database Enterprise Edition 12.1c
 - Userstore: [JDBC]
 - JDBC Driver: ojdbc8.jar
 - JDK & JRE: openjdk 11.0.7_10
 - Docker images: docker.wso2.com/wso2is-km:5.10.0
 - Docker distribution started: docker-apim from github version 3.1
---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/11498

**Suggested labels:**
APIM 3.1.0
IS-AS-KM 5.10.0
Type/Bug
docker-apim

![problema_cosole_is](https://user-images.githubusercontent.com/6186598/139086996-651ad227-e924-4756-81ea-b7ba8fdac151.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
