### ISSUE TITLE
SCIM2 'totalResults' response parameter value is limited by 'count' request parameter value

### ISSUE THREAD

**Issue by Rod-yan** [wso2/product-is#12717]
**Describe the issue:**
When attempting a SCIM2 object look-up using filters, 'totalResults' response payload's parameter value is as high as the 'count' parameter's value specified as an input on the look-up request itself. 

This has been observed on the following endpoints:
(a) HTTP POST: scim2/Users/.search
  - When the number of users that meet the filter's requirements is higher than the passed count parameter, response body (attribute totalResults) does not reflect total number of users who meet the filter's criteria. Instead, it limits the value to the same value that is passed on the count parameter.

(b) HTTP GET: scim2/Users?startIndex=1&count={...}&filter={...}
  - When 'filter' is passed as a query parameter, response shows the same issue as in case (a). When 'filter' is not appended, then the 'totalResults' value is correct (it reflects the total number of users without regard for the 'count' value that is passed onto the request).

**How to reproduce:**
1. Create 3 new users on the WSO2's IS default user-store
2. Attempt an user object lookup using endpoints detailed above (Use 'count' parameter value equals to 2)
3. Verify that 'totalResults' value is 2, when it should be 3 (the total amount of objects that pass the filter conditions, if any)

**Expected behavior:**
'totalResults' response parameter value should reflect the number of all records that pass the query filter, regardless of the 'count' parameter's value set on the HTTP request. This way any REST client that consumes these resources can effectively plan a pagination strategy based on the value provided by the former response parameter.

**Environment information:**
 - Product Versions: IS 5.11.0, IS 5.10.0
 - OS: Irrelevant
 - Database: Irrelevant
 - Userstore: Irrelevant

**Related screenshots:**
![PostRequest_boundless](https://user-images.githubusercontent.com/7266710/138964796-2128c58a-3159-4285-af5d-f3491f1fa991.png)
![PostRequest_count_limit](https://user-images.githubusercontent.com/7266710/138964804-bcc122ee-8971-4b8b-8685-73a98c9b0469.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
