### ISSUE TITLE
client_origin is not retrieved when multiple callbacks are configured in SP configs 

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#12716]
**Describe the issue:**
variable client_origin of the response is not retrieved when multiple callbacks are configured in SP configs for the oidc/checksession request. 

**How to reproduce:**
Configure multiple callback URLs in the SP configs using regexp=() function and do GET request for oidc/checksession endpoint with the client_id as a parameter. Response would be as follows.

![client_origin_missing](https://user-images.githubusercontent.com/31467146/138955374-d0ed2c5e-046b-47f9-95bc-d06e8d418fa5.jpg)
**Expected behavior:**
For the client_origin variable it should return the domain name of the callback URL. 

**Environment information** 
 - Product Version:  IS 5.2.0
 - OS:  Linux
 - Database: H2
 - Userstore: LDAP

---

**Suggestions:**
When multiple callbacks are configured, it should select which URL to send as client_origin based on some criteria.

**Comment by IsankaSR** [comment]
This is already fixed in the public branch.
