### ISSUE TITLE
Management console, user search by claim returns all users matching filter with no limits causing memory issues.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12718]
**Describe the issue:**
The search menu in the management console returns all users matching the filter with no limits causing memory issues.

**How to reproduce:**
- Create a relatively large number of users(>300000). while creating the users add an email address claim such as user1@gmail.com, user2@gmail.com...
- From the management console search the users by the email claim(eg users who are using Gmail(eg filter - *gmail.com).
<img width="840" alt="Screen Shot 2021-10-27 at 6 52 52 PM" src="https://user-images.githubusercontent.com/47600906/139074340-3407f662-7666-425a-99db-0d2c07993879.png">

- All the users would be retrieved and sent as part of the listUserByClaimResponse[1], since the response size is large if there are multiple search requests issued memory issues would be observed.

**Expected behavior:**
The soap response size should be limited to avoid memory issues.

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0]
 - Userstore: [JDBC]

[1]https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/user-mgt.jsp#L286

**Comment by nilasini** [comment]
@ChanikaRuchini Can we close the issue?

**Comment by ChanikaRuchini** [comment]
This is alreday fixed. So closed the issue
