### ISSUE TITLE
Hybrid domains not saved in All-caps in the DB

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/product-is#12713]
**Is your suggestion related to an experience ? Please describe.**

Hybrid domains (Application/Internal) are not saved in all-caps but in PascalCase whereas other domains including PRIMARY are saved in all-caps in the DB. For consistency it is better to adhere to one case(all-caps) when saving all domains in the Database. 
When this improvement is being implemented, in-order to avoid any bug regressions in future it is required to revert the fix done in [1] which was done to fix the issue [2]. Because changing the Application domain from PascalCase to All-caps in the DB will automatically fix the issue in performing the DB search.

[1] https://github.com/wso2/carbon-kernel/pull/3105
[2] https://github.com/wso2/product-is/issues/12445

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
