### ISSUE TITLE
Custom location support for WSO2CARBON_DB missing for container-based deployments

### ISSUE THREAD

**Issue by danijelt** [wso2/product-is#12721]
Custom location support for WSO2CARBON_DB missing for container-based deployments

**Describe the issue**
This has been already discussed in #6355 and it was dismissed by @janakamarasena. This is valid for VM deployments, however, if we want to deploy IS in a container platform like Kubernetes or OpenShift, we can't specify a persistent storage location for WSO2CARBON_DB database, and the data in it is lost on each container restart.

Support for custom location is already present in API Manager and it is properly implemented in its Kubernetes and OpenShift samples with `database.local` setting. We need the same functionality in IS. [1] [2] [3] [4] [5]

Solution for IS is to modify `repository/resources/conf/templates/repository/conf/datasources/master-datasources.xml.j2`, changing:
```
<url>jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE</url>
```
to:
```
<url>{{database.local.url}}</url>
```

Then a custom location, where we mount PersistentVolume, can be specified in deployment.toml like this:
```
[database.local]
url = "jdbc:h2:/usr/lib/wso2/wso2is/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"
```

Also, a default value should be added in `repository/resources/conf/default.json` for standard deployments.

I would submit a pull request myself, but I can't locate the relevant repository which contains `master-datasources.xml.j2` for IS.

Links:
[1]  https://github.com/wso2/kubernetes-apim/blob/master/simple/am-single/templates/am/instance/wso2am-deployment.yaml#L113
[2] https://github.com/wso2/kubernetes-apim/blob/master/simple/am-single/templates/am/instance/wso2am-single-node-am-conf.yaml#L293
[3] https://github.com/wso2/openshift-apim/blob/master/openshift/am-pattern-1/Template.yaml#L2565
[4] https://github.com/wso2/openshift-apim/blob/master/openshift/am-pattern-1/Template.yaml#L4870
[5] https://github.com/wso2/openshift-apim/blob/master/openshift/am-pattern-1/Template.yaml#L5517

**Related issues:**
#6355

**Comment by nilminiwso2** [comment]
@danijelt We are working on improving the documentation related to this problem. Related git issue: https://github.com/wso2/product-is/issues/13332
