### ISSUE TITLE
Cleanup lint warnings in Front End Repos

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#12726]
**Is your suggestion related to a experience ? Please describe.**
Executing `npm run lint` shows a large number of lint warnings.

**Describe the improvement**

- [ ] Fix all possible warnings.
- [x] Integrate ESLint to PR builder Github Action. (PR https://github.com/wso2/identity-apps/pull/2058)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
