### ISSUE TITLE
Create documentation for Tenant Qualified URLs

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#12722]
**Is your suggestion related to a missing or misleading document? Please describe.**

Create documentation for the feature 'Tenant Qualified URLs' in WSO2 Identity Server. 

**Describe the improvement**
The documentation should include the following areas:

- Purpose of tenant qualified URLs
- How does it work?
- How to enable tenant qualified URLs
- Outline the components that are tenant qualified
- How to test out the feature

**Related Issues:**
https://github.com/wso2/product-is/issues/7902
https://github.com/wso2/product-is/issues/9051
https://github.com/wso2/product-is/issues/9068

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
