### ISSUE TITLE
Additional query params present in the logout URL after a successful OIDC logout

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#12723]
**Describe the issue:**
In a successful OIDC logout scenario, **sp** and **tenantDomain** get appended as query params to the logout URL.

```<Logout URL>/?sp={spname}&tenantDomain=carbon.super```

This seems to be introduced with the fix done for [issues:3266](https://github.com/wso2/product-is/issues/3266). It has added the service provider name and tenant domain as query parameters for the success flow as well in addition to the failure flows.

**How to reproduce:**

1. Create a service provider with inbound OIDC configurations [1]

   - SP Name : ```playground```
   - Callback URL : ```http://localhost:8080/playground2/oauth2client```

2. Configure OIDC logout URL [2]
   - Logout URL : ```http://localhost:8080/playground2/logout```

3. Retrieve  the authorization code
   - ```  https://localhost:9443/oauth2/authorize?response_type=code&scope=openid&client_id=<client_id>&redirect_uri=http://localhost:8080/playground2/oauth2client ```
4. Retrieve the id_token using the client id, client secret, and authorization code

   - ```  curl -k -v --user <client_id>:<client_secret> -d "grant_type=authorization_code&code=<authorization_code>&redirect_uri=http://localhost:8080/playground2/oauth2client" https://localhost:9443/oauth2/token```
5. Use the retrieved id_token in the following URL to logout
  - ```https://localhost:9443/oidc/logout?id_token_hint=<id_token>&post_logout_redirect_uri=http://localhost:8080/playground2/logout&state=state_1 ```

**Expected behavior:**
User will get redirected to :
```http://localhost:8080/playground2/logout/?state=state_1&sp=playground&tenantDomain=carbon.super```

**Environment information**  **:**
 - Product Version: IS 5.10.0
 - OS: Linux

---

### Optional Fields

**Related issues:**

- https://github.com/wso2/product-is/issues/12585

**Suggested labels:**

**Comment by piraveena** [comment]
To get this fix, we need to add below config in the deployment.toml file

[oauth]
oidc.allow_additional_params_from_post_logout_redirect_uri=false

**Comment by mefarazath** [comment]
> To get this fix, we need to add below config in the deployment.toml file
> 
> [oauth] oidc.allow_additional_params_from_post_logout_redirect_uri=false

If this is the expected behaviour according to spec, shouldn't this be the default behaviour?

**Comment by piraveena** [comment]
There are a few concerns on making this as default:
1. Multiple apps can use the same post_logout_redirect_uri and depends on sp param
2. tenantDomain and sp can use used for branding stuff too
