### ISSUE TITLE
Inconsistency in the way which isUnique is handled in LDAP.

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#12737]
**Describe the issue:**
There is an inconsistency when isUnique is considered for single value and multi valued attributes. It works for single valued attributes but it does not work for multivalued attribute since there is a issue with the search. Check [1] to see how data is stored for LDAP.

**How to reproduce:**
- Configure telephone number as unique.
- Try to add the same two numbers for two users (Succeeds but it should actually fail).

**Expected behavior:**
isUnique should work for both single and multi valued attributes without inconsistencies.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: 5.11.0
- OS: Ubuntu 20.04.3 LTS
- Database: H2
- Userstore: LDAP
---

### Optional Fields
**References:**
[1] - [https://is.docs.wso2.com/en/latest/learn/managing-user-attributes/#attributes-with-multiple-values](https://is.docs.wso2.com/en/latest/learn/managing-user-attributes/#attributes-with-multiple-values)

**Related issues:**
https://github.com/wso2/product-is/issues/12683

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
