### ISSUE TITLE
Revisit Error Handling in Oauth

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#12749]
**Is your suggestion related to an experience ? Please describe.**
The error responses for authorization requests needs to be handled in a consistent way.

**Describe the improvement**

- [ ]  Need to check whether errors are returned to client apps when applicable
- [ ]  Need to check whether form post mode is handled properly in all error scenarios
- [ ] Improve the logic that decides which URL to use to respond to (redirect URI or common error page). This logic is duplicate all over the place
- [ ] Make the error handling logic central so that we don't have to fix it again and again in future.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
