### ISSUE TITLE
Broken link in Writing a Custom Local Authenticator

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12748]
**Is your suggestion related to a missing or misleading document? Please describe.**
sample authenticator link is not working at 
4. Build the project using maven. (Click to see the sample project **here**).
https://is.docs.wso2.com/en/latest/develop/writing-a-custom-local-authenticator/#configurations

Doc improvement:

- Better to mention the folder structure in https://is.docs.wso2.com/en/latest/develop/writing-a-custom-local-authenticator/#configurations
- User will not understand the package structure just by package name in the java files and pom file

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
