### ISSUE TITLE
Internal_hostname or identity_server_service_url is not honored in resending account confirmation email flow

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#12741]
**Describe the issue:**
With the introduction of `Internal_hostname` configuration in IS 5.11, it's expected to use the hostname configured in `Internal_hostname` for every internal communication (ref: #11878). Further, if `identity_server_service_url` is configured, this should be prioritized and the request should be made to the hostname configured in `identity_server_service_url`. Neither of these configurations is honored in resending the account confirmation email flow.

**How to reproduce:**
1. Configure a separate `internal_hostname` other than the `hostname`.
2. Check the hostname used for the backend API requests made by the authentication endpoint in resending account confirmation email flow.
3. Configure a separate `identity_server_service_url` other than the hostname configured for `hostname`.
    ```
    [identity.auth_framework.endpoint]
    identity_server_service_url = "https://test.com:9443"
    ```
4. Check the hostname used for the backend API requests made by the authentication endpoint in resending account confirmation email flow.

**Expected behavior:**
- In the 2nd step above, the request is made to the hostname configured for `hostname` and it's expected to make the request to `internal_hostname`.
- In the 4th step above, the request is made to the hostname configured for `hostname` and it's expected to make the request to `identity_server_service_url`.

**Workaround**
Add the configuration below to configure the hostname to be used in the above flow.
```
[identity.auth_framework]
identity_server_origin = "https://localhost:9443"
```

**Environment information**
 - Product Version: IS 5.11.0

**Related issues:**
#11878
#8194

**Comment by nilasini** [comment]
@minolih are we good to resolve the issue? Did we fix it in master?

**Comment by minolih** [comment]
Yes. This has been fixed in master with https://github.com/wso2/identity-apps/pull/2746
