### ISSUE TITLE
Access Token generated for Authoraization Flows that do not require a token

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#12754]
**Describe the issue:**
An access token is generated for authorization calls that do not require the return of an access token. 
Ex: `code`, `id_token`, `code id_token` response types. 

**How to reproduce:**
Send an authorization request with response_type as `id_token`.

**Expected behavior:**
Since for these type of requests only an id_token is required , generating an access token is not necessary and also can have an impact on performance.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
