### ISSUE TITLE
Implement a new JWT Token Issuer 

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#12752]
The following rfc [1] supports for JWT tokens as OAuth2 access tokens. This task is to track and implement a new JWT Token Issuer based on that specification.

[1] https://datatracker.ietf.org/doc/html/rfc9068

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
