### ISSUE TITLE
SCIM2 filtering does not work when the filter value used is "OR" or "AND"

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12759]
**Describe the issue:**
SCIM2 filtering does not work when the filter value used is "OR" or "AND", Imagine a user having the last name "OR" or "AND", it would not be possible to filter the user.

**How to reproduce:**
Create a user having Lastname "OR" or "AND".
Try to filter the user from the last name.
Example:
```
curl -v -k --location --request GET 'https://localhost:9443/scim2/Users?filter=name.familyName+Eq+OR' --header 'Content-Type: application/scim+json' --header 'Authorization: Basic YWRtaW46YWRtaW4='
```
Example:

```
curl -v -k --location --request GET 'https://localhost:9443/scim2/Users?filter=name.givenName+Eq+testuser+and+name.familyName+Eq+OR' --header 'Content-Type: application/scim+json' --header 'Authorization: Basic YWRtaW46YWRtaW4='
```

**Expected behavior:**
When "OR" or "AND" are added as values, it should return the results.

**Environment information** **:**
 - Product Version: [IS 5.7.0]

**Comment by ruwanta** [comment]
OR and NOT is not really needed for any practical use case

**Comment by Rashmini** [comment]
Proper fix for this issue is to integrate a parser to validate the syntax.
Issue created to track this: [wso2/product-is#12868](https://github.com/wso2/product-is/issues/12868)
