### ISSUE TITLE
Special characters in the app.password cause issues in user portal

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#12761]
**Describe the issue:**
When the app.password carry special characters the password recovery flow from user portal get broken with below screen.
<img width="1179" alt="Screenshot 2021-11-08 at 15 08 54" src="https://user-images.githubusercontent.com/791850/140864940-ad72b98a-0178-446a-a4df-f7b1412e6ce5.png">

**How to reproduce:**
Follow the steps as in https://docs.wso2.com/display/Security/Security+Advisory+WSO2-2020-0864
Use an app.password with special characters. ($ , # , .)
Try the forgot password option for a user using user portal.

**Expected behavior:**
Flow should work smooth allowing to reset password.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Mac

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
