### ISSUE TITLE
Back button in MFA scenarios ignores user credentials entered on second attempt

### ISSUE THREAD

**Issue by Kktheoch** [wso2/product-is#12774]
**Describe the issue:**
Attempting to login with MFA (Multiple authenticator steps) seems to break the back button functionality. Eg. Suppose a two-step authentication using Local Basic Authenticator as first step and Password Reset Enforcer as second step. After successful authentication on step one pressing the back button on step two redirects you to the login page but it's irrelevant what credentials you may input the second time, you will still attempt to login with the user you registered earlier. I could reliably reproduce this using Local Basic Authenticator and Password Reset Enforcer steps but I suppose it's the same with SMS OTP/Email OTP etc.

**How to reproduce:**
1. Setup an MFA scenario. 
2. Login with user "A" on authenticationendpoint/login.do
3. You are redirected to authenticationendpoint/pwd-reset.jsp to reset password of user "A".
4. Press back button
5. You are redirected to authenticationendpoint/login.do
6. Login with user "B"
7. You are asked to reset password credentials of user "A"

**Expected behavior:**
You should be able to login with user "B" after back button

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.9.0
 - OS: Windows
 - Database: MySQL
 - Userstore: Custom JDBC extension
 - Service Provider is configured using SAML2 if that's relevant. 
 Advanced Authentication Configuration for SP (Step 2 is Federated SMS OTP which is disabled in this case)
![image](https://user-images.githubusercontent.com/61586175/141452332-f2f716a1-9353-4c3f-9a0d-77651fec14e7.png)
---

**Comment by Kktheoch** [comment]
Update: I ended up disabling back button functionality by using the following script on the password-reset page. Note that the user may still encounter the bug by attempting to visit the login page from his history, this was deployed as a temporary fix in hopes of a more permanent (and cleaner) solution. 

```
<script>
        (function (global) {
            if(typeof (global) === "undefined") {
                throw new Error("window is undefined");
            }
            var _hash = "!";
            var disableBack = function () {
                global.location.href += "#";
                global.setTimeout(function () {
                    global.location.href += "!";
                }, 50);
            };

            global.onhashchange = function () {
                if (global.location.hash !== _hash) {
                    global.location.hash = _hash;
                }
            };

            global.onload = function () {
                disableBack();
                document.body.onkeydown = function (e) {
                var elm = e.target.nodeName.toLowerCase();
                if (e.which === 8 && (elm !== 'input' && elm  !== 'textarea')) {
                    e.preventDefault();
                }
                e.stopPropagation();
                };
            };
        })(window);
</script>
```
The script is a courtesy of the answer mentioned [here](https://stackoverflow.com/questions/59983529/trying-to-disable-the-browsers-back-button) by user rajat.gite.

According to my tracing the issue seems to be caused by the context (aka session) already having an authenticated user which is not overwritten when the new credentials are submitted from the login page. Ideally user login session should be refreshed on submission of new client credentials

**Comment by piraveena** [comment]
Based on the current implementation, that is the current expected behaviour. Hence we are closing this issue
