### ISSUE TITLE
Session-Data-Store is not cleared complete by the cleanup script when the product level session clean up is disabled

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/product-is#12779]
**Describe the issue:**
After disabling the server-level session cleanup tasks and schedule stored procedures [1] in the database, the IDN_AUTH_SESSION_STORE table did not get cleaned well.

**How to reproduce:**

- Disable server-level session clean up as follows.
`[session_data.cleanup] `
`enable_expired_data_cleanup = false `
`clean_logged_out_sessions_at_immediate_cycle = false`
` enable_pre_session_data_cleanup = false `
`[oauth.token_cleanup]`
`enable = false`
- Configure the stored procedure [1].
- Do several refreshes in the portal.
- Temporary session data will not be deleted by the script as it is considering session data created time older than 14 days to delete according to the current logic in [1].
`SET @sessionCleanupTime = cast((DATEDIFF_BIG(millisecond, '1970-01-01 00:00:00', GETUTCDATE()) - (1209600000))AS DECIMAL) * 1000000`
`INSERT INTO IDN_AUTH_SESSION_STORE_TMP (SESSION_ID) SELECT TOP (@chunkLimit) SESSION_ID FROM IDN_AUTH_SESSION_STORE where TIME_CREATED < @sessionCleanupTime;
`

[1]  https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mssql/sessiondata-cleanup/mssql-session-data-cleanup.sql

**Comment by rksk** [comment]
Fixed with https://github.com/wso2/product-is/issues/14713
