### ISSUE TITLE
Update docs related to SSO Recaptcha

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#12775]
For the issue, https://github.com/wso2/product-is/issues/6848, the new configuration introduced for the "Captcha for SSO Login" of Resident Identity Provider in the Management Console was added to IS-5.5.0 and IS-5.6.0.

Therefore the documentations ([IS-5.5.0](https://docs.wso2.com/display/IS550/Configuring+reCaptcha+for+Single+Sign-On) and [IS-5.6.0](https://docs.wso2.com/display/IS560/Configuring+reCaptcha+for+Single+Sign-On)) need to be updated with the latest UI changes and configurations.

This will be the new UI,
![Screenshot from 2021-11-15 10-07-45](https://user-images.githubusercontent.com/36252940/141723703-a7ed9161-9f47-4788-9ea3-ba83caa29eb4.png)

The table in the step 5 (b) should include the modified options on enabling recaptcha. (Refer step 5 in https://is.docs.wso2.com/en/5.12.0/learn/configuring-recaptcha-for-single-sign-on/)

PRs related to the fix,
https://github.com/wso2-support/identity-governance/pull/411
https://github.com/wso2-support/identity-governance/pull/415
https://github.com/wso2-support/identity-local-auth-basicauth/pull/68

**Comment by Rashmini** [comment]
In IS-5.8.0, only the screenshot is updated. (https://docs.wso2.com/display/IS580/Configuring+reCaptcha+for+Single+Sign+On)
The content should be updated with the modified options.

Related issue: https://github.com/wso2/docs-is/issues/967

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
