### ISSUE TITLE
UI errors in user-portal and my-account when IdP sessions are terminated for the first time.

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#12770]
**Describe the issue:**
When the sessions are terminated for the first time (accessing the URL from beginning) through the user-portal (5.10.0) or my-account (5.11.0) there are UI level errors. This seems to be due to a delay in the APIs or a UI level issue in my-account/user-portal. Please refer to the gif attached herewith.
 
![Peek 2021-11-11 21-17](https://user-images.githubusercontent.com/33062368/141330512-4325497f-2cfc-4ab2-9015-13d9e45caae1.gif)

**How to reproduce:**
- Access the user-portal or my-account URL for the first time.
- Try to terminate the IdP sessions (The issue should be reproduced).
- Stay for a while and refresh (Then it logs out).
- Try to login again and perform the initial steps (You will not see the error anymore, it only occurs for the first time).

**Expected behavior:**
These errors should not be there even in the first time of accessing the user-portal or my-account

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.10.0, 5.11.0 (Both updated to the latest versions)
 - OS: Ubuntu 20.04.3 LTS 
 - Database: H2
 - Userstore: LDAP

---

**Comment by nilasini** [comment]
@ashendes are we good to close the issue? Did we fix it in master?

**Comment by ashendes** [comment]
Master already had the fix. Good to close.
