### ISSUE TITLE
Active User Session Limit Page, Browser is Detected as Chrome for Edge

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#12780]
**Describe the issue:**
In the limiting active user session feature, when it display the current active sessions it's showing browser family in the browser column.

![internet-explorer](https://user-images.githubusercontent.com/13187638/141736045-4c957005-05c8-49c0-b264-865bb6a0aa4d.png)

When we have a logged in session with Microsoft edge, it'll still show the browser as chrome because it's chromium browser. This is wrong and it should show the correct browser.

**How to reproduce:**

- configure the active session limit feature [1].
- login with Microsoft Edge browser until the allowed active session count exceeds.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

[1] - https://is.docs.wso2.com/en/5.10.0/learn/limiting-active-user-sessions-based-on-criteria/

**Comment by nilasini** [comment]
@ChanikaRuchini are we good to close this?

**Comment by ChanikaRuchini** [comment]
This issue is fixed. So closed the issue
