### ISSUE TITLE
Errors are not displayed in multi-option page

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#12785]
**Describe the issue:**
When a particular step is having the authenticators without basic, such as Email OTP, TOTP and FIDO, the error message is not shown on the multi-option page, when the URL contains the parameters: `authFailure=true&authFailureMsg=login.fail.message`.

**How to reproduce:**
If an authenticator is redirected to the multi-option page on failure, the user will be redirected to the multi-option page with the aforementioned URL parameters.

**Expected behavior:**
An error message for the authentication failure should be shown in the UI.

**Environment information**
 - Product Version: IS 5.11.0

**Related issues:**
#12784

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
