### ISSUE TITLE
Role-Based Access Control Using XACML not working on v3.2.0

### ISSUE THREAD

**Issue by manurag1234** [wso2/product-is#12793]
**Describe the issue:**
On enabling RBAC using the below link access control is not working and no user is able to access the API exposed via APIM.
https://apim.docs.wso2.com/en/3.2.0/learn/api-security/authorization/role-based-access-control-using-xacml/#enabling-role-based-access-control-using-xacml

**How to reproduce:**
Follow the steps provided in the above link and and expose an API using WSO2 APIM
Below error is faced when trying to access the exposed API:
Response code: 500
Response output: 
<am:fault xmlns:am="http://wso2.org/apimanager">
  <am:code>0</am:code>
  <am:type>Status report</am:type>
  <am:message>Runtime Error</am:message>
  <am:description>Error occurred while evaluating the policy</am:description>
</am:fault>

**Expected behavior:**
instead of resulting error code 500 request should be successful as user is granted with permission to access the API.

**Environment information** **:**
 - Product Version: 3.2.0
 - OS: Linux
 - Database: MySQL
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
