### ISSUE TITLE
Password Reset confirmationcode not invalidating after first use

### ISSUE THREAD

**Issue by CrimsonZ19** [wso2/product-is#12792]
**Describe the issue:**
We are able to use the same password reset email link to access the challenge questions and successfully reset user passwords multiple times before the 1440 minutes are up on its time expiration.

**How to reproduce:**
Step 1: Select 'Forgot Password?'
Step 2: Input email address
Step 3: Follow link in email to Change Password
![image](https://user-images.githubusercontent.com/83088902/142250383-07018f31-6050-4eea-8e8b-2aa53e696eb5.png)
Step 4: Correctly answer challenge questions and change password
Step 5: Click on same link which includes same confirmation code displayed in image above
Step 6: Correctly answer challenge questions and change password again

**Expected behavior:**
We expect that at Step 5 the confirmation code should have already been invalidated upon resetting the password in step 4 so the link should no longer allow you to change the password again

**Environment information:**
 - Product Version: ISKM 5.10.0
 - OS: RHEL 7.9
 - Database: postgres13
 - Userstore: JDBC

**Comment by minolih** [comment]
The above mentioned flow does not exist in the Identity Server 5.12.0. 
The flows available for password recovery are
1. Notification-based.
2. Challenge question based. 

Notification-based flow sends an email and the link in the email expires after resetting the password. And it does not require to answer challenge questions. 
Challenge question based flow does not send an email and displays the challenge questions on the browser window after selecting the option and entering the username. 
https://is.docs.wso2.com/en/latest/learn/password-recovery/

Therefore above mentioned flow or issue isn't available in 5.12.0 with a combination of email and challenge questions.
