### ISSUE TITLE
When creating new SAML SSO Authenticator to Identity Provider in Console app, selected values from Dropdown does not set

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#12797]
**Describe the issue:**

When creating a new SAML SSO Authenticator to a new Identity Provider in Console app, the selected values for Include Authentication Context, Authentication Context Class, Authentication Context Comparison Level by dropdown menus does not set to the selected value nor to the any value. Please refer to the GIF attached herewith.

https://user-images.githubusercontent.com/46222840/142603085-7f0651c3-1161-4d84-a2d6-7d3a29136155.mov

**How to reproduce:**

- Access the console app
- Create a new identity Provider
- Select SAML SSO as the authenticator
- Select Values for Include Authentication Context, Authentication Context Class, Authentication Context Comparison Level from the dropdown menus (You can see the selected Values are reset to null)

**Expected behavior:**

Values selected should be displayed in the dropdown menu until updating it and the window showing the included values should show the selected values for Include Authentication Context, Authentication Context Class, Authentication Context Comparison Level  properties

**Environment information**  **:**
 - Product Version: IS 5.11.0
 - OS:  Mac
 - Database:  H2
 - Userstore:  LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
In 5.12.0-alpah17 Console UI , there is no option to configure these fields

**Comment by savindi7** [comment]
> In 5.12.0-alpah17 Console UI , there is no option to configure these fields. In the current Console app, we have simplified these configs. We don't have these **Authentication Context Class, Authentication Context Comparison Level** config options now

Issue will be closed based on the above.
