### ISSUE TITLE
Wrong OIDC Back-Channel Logout event name URI

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#12801]
**Describe the issue:**
When implementing single logout in frontend applications using OIDC Back-Channel Logout, the logout token IS is sending to client applications looks like the following one:
```
{
   "sub": "*******",
   "aud": "*******",
   "iss": "*******",
   "exp": *******,
   "iat": *******,
   "jti": "*******",
   "events": {
      "http://schemas.openidnet/event/backchannel-logout": {}  
   },
   "sid": "*******"
}
```

**Expected behavior:**
As per the OIDC Back-Channel Logout specification [1], the event name should be:
```
"http://schemas.openid.net/event/backchannel-logout"
```

**Environment information:**
 - Product Version: IS 5.10.0

---
[1] https://openid.net/specs/openid-connect-backchannel-1_0.html#Validation

**Comment by ashensw** [comment]
This is already fixed in the public branch with the PR: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1559
