### ISSUE TITLE
Unique check for mobile number error message concatenate without space

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#12806]
**Is your suggestion related to an experience ? Please describe.**

In IS 5.11.0, when Uniqueness is set for mobile claim, in the registration page, duplicate value is entered for mobile number, it gives the correct error message. But claim name and the message is concatenate without space. Below is the error message.

The value defined for **Mobileis** already in use by different user!

**Describe the improvement**

Claim name "Mobile" and "is" should be separated from space.

**Comment by Rashmini** [comment]
This is already fixed in the public repository with https://github.com/wso2/carbon-identity-framework/pull/3525
