### ISSUE TITLE
Redirect the user to the application  once email confirmation is completed 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#12804]
**How to reproduce:**
- Enable self registration
- Add an access URL for a app
- Self-register 
- Click the confirmation link

**Expected behavior:**

- *Better to have an implementation to store the application Access URL against the confirmation code and retrieve it at the validation*

**Comment by ayshsandu** [comment]
Note: we can remove the {{callback}} from the email placeholder.

**Comment by kayathiri4** [comment]
Duplicate of https://github.com/wso2-enterprise/asgardeo-product/issues/8369
