### ISSUE TITLE
Users can be created with unsupported symbols for JDBC userstores

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#12808]
**Describe the issue:**
WSO2 IS documentation has mentioned unsupported special characters in usernames [1]. However, when a JDBC user store is configured, the default regex in the configuration allows these special characters in the username.

Regex in LDAP
`<Property name="UsernameJavaRegEx">[a-zA-Z0-9._\-|//]{3,30}$</Property>`

Regex in JDBC
`<Property name="UsernameJavaRegEx">^[\S]{3,30}$</Property>`

**How to reproduce:**

1. Configure JDBC user store as the primary user store using the following configuration in deployment.toml.
```
[user_store]
type = "database_unique_id"
```
2. Add a user from the management console with the username `test>100`.
3. User will be created successfully.

**Expected behavior:**
User should not be allowed create username with unsupported special characters.

**Environment information:** 
 - Product Version: IS 5.11.0
 - Userstore: JDBC

---

[1] - https://is.docs.wso2.com/en/latest/references/usernames-in-identity-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
