### ISSUE TITLE
Improve CIBA flow to support the requirements of the CIBA conformance suite and Open Banking CIBA flows

### ISSUE THREAD

**Issue by KalanaDananjaya** [wso2/product-is#12818]
**Is your suggestion related to an experience ? Please describe.**
There are some issues with passing CIBA conformance suite with the current implementation

**Describe the improvement**
Change the CIBA implementation to pass CIBA conformance suite and CIBA OB flows

**Comment by nilasini** [comment]
@KalanaDananjaya was this issue fixed in public?

**Comment by KalanaDananjaya** [comment]
@nilasini Yes.
Following are public PRs
Framework: https://github.com/wso2/carbon-identity-framework/pull/4127
Inbound Auth : https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1876
Addons: https://github.com/wso2-extensions/identity-oauth-addons/pull/88
