### ISSUE TITLE
SCIM returns faulty totalResults when the filter parameter is given with pagination parameters

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#12813]
**Describe the issue:**
As per wso2/docs-is#1495, the totalResults should have the total result count with pagination parameters in JDBC userstore. However, when the filter parameter is given along with pagination parameters as follows, the value of the totalResults is incorrect.
```
https://localhost:9443/scim2/Users?startindex=1&count=3&filter=meta.resourceType+eq+User
```
The said behavior occurs, since the totalResults logic is implemented at [1][2], but not considered at [3].

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.46/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L477
[2] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.46/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L518
[3] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.46/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L475

**Environment information**
 - Product Version: IS 5.11.0

**Related issues:**
#7320

**Comment by rksk** [comment]
With the fix, it is working fine until the totalResults <= 100. Later, the totalResults count is returned as 100 for all. The totalResults is capped with the max user list limit userstore configuration.

**Comment by isuruirj** [comment]
There's a behavior change with the recent changes in this fix. As per https://github.com/wso2/docs-is/issues/1495, the totalResults should have the results per a page count with pagination parameters in LDAP userstore. However, when the filter parameter is given along with pagination parameters as follows, the value of the totalResults is incorrect.

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?startIndex=1&count=10&filter=userName+sw+is'`

Product Version: IS-5.10.0
Userstore: LDAP

**Comment by tharakawijekoon** [comment]
We need to re-evaluate this fix, this is causing DB CPU to spike when scim2 APIs are called since the following query with the IKE '%'  is executed.
SELECT COUNT(UM_USER_NAME) AS RESULT FROM UM_USER WHERE UM_USER_NAME LIKE '%' AND UM_TENANT_ID = -1234

**Comment by tharakawijekoon** [comment]
https://github.com/wso2/product-is/issues/15598

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
