### ISSUE TITLE
Update Docs related to configuring access control policy for service provider

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#12810]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the [1], It describes how to add a xacml policy to a service provider, to authorise users based on the role. As the 'authenticate' is used as the action in the xacml policy, this is not working for the 'password grant' though it works fine for the other grant types. 

**Describe the improvement**
In the docs it should be mentioned that this policy is only working for grant types other than password grant. 

[1] https://is.docs.wso2.com/en/5.10.0/learn/configuring-access-control-policy-for-a-service-provider/

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
