### ISSUE TITLE
Case insensitive username not working when Multi-attribute Login enabled

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#12815]
**Describe the issue:**
Upon enabling Multi-attribute login, when the username is provided in uppercase during login, it results in a user not found error. Meaning, although the user store is configured as case insensitive, it checks as case sensitive.
**How to reproduce:**
1. Enable Multi-Attribute Login with telephone/email/username (either two).
2. Try out the login or Recovery flow with uppercase characters.
2. Results in user not found (carbon logs).

**Expected behavior:**
Upon providing username in uppercase, the user should be able to login when caseinsensitive configuration is added when Multi-attribute login is enabled.

**Environment information** 
 - Product Version: IS 5.10.0, 
 - Database: [PostgreSQL]
 - Userstore: [JDBC]

**Work around***
Configure the following query for GetUserLisForPropertyWithIDSQL user store property,
```GetUserLisForPropertyWithIDSQL = "SELECT DISTINCT UM_USER.UM_USER_ID FROM UM_USER, UM_USER_ATTRIBUTE WHERE UM_USER_ATTRIBUTE.UM_USER_ID = UM_USER.UM_ID AND UM_USER_ATTRIBUTE.UM_ATTR_NAME =? AND LOWER(UM_USER_ATTRIBUTE.UM_ATTR_VALUE) LIKE LOWER(?) AND UM_USER_ATTRIBUTE.UM_PROFILE_ID=? AND UM_USER_ATTRIBUTE.UM_TENANT_ID=? AND UM_USER.UM_TENANT_ID=?" ```

**Comment by mifrazmurthaja** [comment]
This should also be fixed for `GetUserListForClaimValueWithIDSQL`

**Comment by hwupathum** [comment]
This issue is not reproducible in IS 5.11.0 and IS 7.0.0 

> **Describe the issue:** Upon enabling Multi-attribute login, when the username is provided in uppercase during login, it results in a user not found error. Meaning, although the user store is configured as case insensitive, it checks as case sensitive. **How to reproduce:**
> 
> 1. Enable Multi-Attribute Login with telephone/email/username (either two).
> 2. Try out the login or Recovery flow with uppercase characters.
> 3. Results in user not found (carbon logs).
> 
> **Expected behavior:** Upon providing username in uppercase, the user should be able to login when caseinsensitive configuration is added when Multi-attribute login is enabled.
> 
> **Environment information**
> 
> * Product Version: IS 5.10.0,
> * Database: [PostgreSQL]
> * Userstore: [JDBC]
> 
> **Work around*** Configure the following query for GetUserLisForPropertyWithIDSQL user store property, `GetUserLisForPropertyWithIDSQL = "SELECT DISTINCT UM_USER.UM_USER_ID FROM UM_USER, UM_USER_ATTRIBUTE WHERE UM_USER_ATTRIBUTE.UM_USER_ID = UM_USER.UM_ID AND UM_USER_ATTRIBUTE.UM_ATTR_NAME =? AND LOWER(UM_USER_ATTRIBUTE.UM_ATTR_VALUE) LIKE LOWER(?) AND UM_USER_ATTRIBUTE.UM_PROFILE_ID=? AND UM_USER_ATTRIBUTE.UM_TENANT_ID=? AND UM_USER.UM_TENANT_ID=?" `
