### ISSUE TITLE
Custom key ID extension missing from WUM branch. 

### ISSUE THREAD

**Issue by hasoxy** [wso2/product-is#12820]
**Describe the issue:**
Custom Key ID extension is missing from the IS 5.10.0 wum branch. 
**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
@dimuthnc Is the fix available in master?

**Comment by nilasini** [comment]
Closing as it is fixed in master
