### ISSUE TITLE
Increase DB attribute size : IDP_AUTHENTICATOR_PROPERTY table PROPERTY_VALUE  

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#12828]
**Is your suggestion related to an experience ? Please describe.**

Multiple AuthnContextClassRefs are stored as comma separated string in IDP_AUTHENTICATOR_PROPERTY table as a PROPERTY_VALUE. Since it is a comma separated string if user include more AuthnContextClassRefs, the size of the PROPERTY_VALUE column will not be enough to store it.

**Describe the improvement**

Increase the maximum size of the string that can be stored by the attribute PROPERTY_VALUE in table IDP_AUTHENTICATOR_PROPERTY.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
