### ISSUE TITLE
Defining Attribute Types 

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#12844]
**Is your suggestion related to an experience ? Please describe.**

When attributes are added from console -> Manage -> Attributes -> Attributes -> New Attribute, the type of attribute ( ex :- boolean) cannot be declared. 

**Describe the improvement**

Being able to declare the type of attribute when defining them will be an advantage.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
