### ISSUE TITLE
All the new application created from now will not able to access the server management APIs by default.

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#12852]
**Describe the issue:**
With this https://github.com/wso2/carbon-identity-framework/pull/3839 improvement, there will a flag(`isManagementApp`) that needs to be set for all the new applications, if it is used to access the server management APIs using any OAuth grants. 

All the existing applications will not be affected by this change. They will be able to access the management APIs.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
