### ISSUE TITLE
Enable defaultAutoCommit for BPS datasource

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12855]
**Is your suggestion related to a missing or misleading document? Please describe.**

As mentioned in https://github.com/wso2/product-is/issues/10032, we recommend using auto-commit for Postgresql when used for BPS.

The config block provided in [1] needs to be updated to reflect it.

```
[bps_database.config.pool_options]
defaultAutoCommit=true
```

[1] https://is.docs.wso2.com/en/latest/setup/changing-datasource-bpsds/

**Comment by nilminiwso2** [comment]
The fix is available in IS 6 as well [1]. Hence closing this issue.

[1] https://is.docs.wso2.com/en/latest/deploy/change-datasource-bpsds/
