### ISSUE TITLE
Integrate ABNF parser to validate SCIM filter query in GET operation

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#12868]
In order to validate the filter syntax and use it, the proper way is to implement a parser for the filter query. So, we can easily validate the syntax without performing complex operations.

Refer: https://github.com/wso2/charon/pull/261

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
