### ISSUE TITLE
[Migration] Data type change in api.identity.oauth.dcr.endpoint.yaml swagger Application property

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#12871]
**Describe the issue:**
With this improvements [here](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1747), `client_secret_exp` [attribute](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/51b4b8863862aafb2a913323c6f901fcb349e34c/components/org.wso2.carbon.identity.api.server.dcr/src/main/resources/api.identity.oauth.dcr.endpoint.yaml#L345) will no longer be a string value. It has been converted from string to a long value. Any client created using this swagger must change according to this new change since this is not backward compatible.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
