### ISSUE TITLE
Official testing and documentation with AWS Aurora 

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#12873]
**Is your suggestion related to a missing or misleading document? Please describe.**
Since AWS Aurora is compatible with MySQL and PostgreSQL according to the official website at [1], it should work with the WSO2 Identity Server. However, there is no plan/roadmap on testing and documenting the process. This issue is made to track the required documentation improvement.

**Describe the improvement**
The documentation should be improved so that the testing plan and configuring details are mentioned in the documentation site.

---

**References:**
[1] - [https://aws.amazon.com/rds/aurora/?aurora-whats-new.sort-by=item.additionalFields.postDateTime&aurora-whats-new.sort-order=desc](https://aws.amazon.com/rds/aurora/?aurora-whats-new.sort-by=item.additionalFields.postDateTime&aurora-whats-new.sort-order=desc)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
