### ISSUE TITLE
Enable Email Account Verification for an Updated Email Address

### ISSUE THREAD

**Issue by jasmine0508** [wso2/product-is#12872]
The documentation at https://is.docs.wso2.com/en/latest/develop/enable-email-account-verification-for-an-updated-email-address/#step-01-configure-the-email-adapter-to-send-emails states that USER CLIAMS UPDATE should be here: Step 02 - Enable the feature in the management console¶ In the management console, navigate to Main > Identity Providers > Resident > Account Management Policies > User Claim Update.

But in the management console it is at Main > Identity Providers > Resident > Other Settings Kindly get this corrected.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
