### ISSUE TITLE
Actual content-type of the email templates are not reflected in the management console

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#12870]
**Describe the issue:**
Content-type of the email templates will always show as text/html in the management console regardless of the actual value.

**How to reproduce:**

1. Log into management console and go to email templates.
2. Select EmailOTP from the list.
3. Select content type as text/plain from the dropdown and click save.
4. Content type will still show as text/html.
5. Do a CURL to the WSO2 IS to get the actual value of the template as below
```
curl --location --request GET 'https://localhost:9443/t/carbon.super/api/server/v1/email/template-types/RW1haWxPVFA' --header 'Authorization: Basic YWRtaW46YWRtaW4='
```
6. Response will show the content type as text/plain.
```
{
    "displayName": "EmailOTP",
    "templates": [
        {
            "contentType": "text/plain; charset=UTF-8",
            "subject": "WSO2 - Email OTP for Sign In",
            ...
``` 

**Expected behavior:**
Actual content type of the email templates should be displayed in the management console.

**Environment information:**
 - Product Version: IS 5.10.0

---

**Related issues:**
#4849

**Comment by nilasini** [comment]
@Thumimku can we close this issue?

**Comment by Thumimku** [comment]
Yes we can
