### ISSUE TITLE
Missing configs in identity.xml.j2 template in IS 5.10.0 U2

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#12879]
**Describe the issue:**
There are several missing configs in identity.xml.j2 file in the latest update level of WSO2 IS 5.10.0. A set of configs was added in the update level 90 and the same has been removed in update level 95.

**Expected behavior:**
The latest config needs to be available in the identity.xml.j2 template.

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by bhagyasakalanka** [comment]
This is only releated to WSO2IS-5.10.0. No need to do any changes in master
