### ISSUE TITLE
Getting SQL Exceptions with Metrics DB when running forgetMe tool with H2 DB

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12877]
**Describe the issue:**
When running the forgetMe tool using the below command, I got the below SQL error logs

`sh $CARBON_HOME/repository/components/tools/forget-me/bin/forgetme.sh -U Sam -pu 123-456 -carbon $CARBON_HOME -d $CARBON_HOME/repository/components/tools/forget-me/conf`

```
[com.zaxxer.hikari.HikariDataSource] INFO : HikariPool-4 - is starting.
[com.zaxxer.hikari.pool.HikariPool] DEBUG : HikariPool-4 - Cannot acquire connection from data source
org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393)
	at org.h2.engine.Engine.openSession(Engine.java:53)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)

```

**How to reproduce:**
- Set the Carbon home as env variable
- Create a user SAM
- Delete the user SAM
- Run the forgetMe tool using the below command

`sh $CARBON_HOME/repository/components/tools/forget-me/bin/forgetme.sh -U Sam -pu 123-456 -carbon $CARBON_HOME -d $CARBON_HOME/repository/components/tools/forget-me/conf`

**Expected behavior:**
Tool should work withoud any errors

**Workaround:**
The above error happens due to the patch in the MetricDB. To fix the above issue, go to `<IS_HOME>/repository/conf/datasources/metrics-datasources.xml` file and rename the connection URL as `jdbc:h2:./repository/database/WSO2METRICS_DB`. Earlier it was as `jdbc:h2:repository/database/WSO2METRICS_DB`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0
 - OS: Mac
 - Database: H2
 - Userstore: Embedded LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Nirmal-De-Silva-99** [comment]
I will work on this

**Comment by nilasini** [comment]
@Nirmal-De-Silva-99 Did you start to work on this?

**Comment by Nirmal-De-Silva-99** [comment]
@nilasini Yes, still in progress

**Comment by nilasini** [comment]
@Nirmal-De-Silva-99 Could you please update the status of the issue? Also could you please share an ETA(estimated time) for the fix?

**Comment by Nirmal-De-Silva-99** [comment]
Could not finish it due to some blockers. Moved on to a new project.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
