### ISSUE TITLE
Doc Feedback: OPA array comparison is wrong

### ISSUE THREAD

**Issue by nsivanoly** [wso2/product-is#12884]
The Array comparison is Rego is wrong,

In docs:
`user == role[_]`

Correct way:
`user[_] == role[_]`

Location : https://is.docs.wso2.com/en/latest/learn/using-opa-policies-for-adaptive-auth/

reference: https://www.openpolicyagent.org/docs/latest/policy-language/#array-comprehensions

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
