### ISSUE TITLE
Impossible to remove claims through SCIM2 API when claim names start with "identity".

### ISSUE THREAD

**Issue by Manchiz** [wso2/product-is#12898]
**Describe the issue:**
Impossible to remove claims through SCIM2 API when claim names start with "identity".

When containing "identity" at the beginning of the claim name, it identified the claim as an immutable/identity claim [1]. 
Eg: "identityCardDate"  identify as an immutable/identity claim.

**How to reproduce:**
1.  Create a custom attribute [2] as claim name starting with "identity".
      Eg: "identityCardDate"

2. Try to remove custom claim using PATCH request.
    Eg: 
       curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations": 
       [{"op":"remove","path":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:identityCardDate"}]}' --header 
       "Content-Type:application/json" https://localhost:9443/scim2/Users/5df5f469-44db-449e-b3bb-7177dd28ff4b

3. Return the response status as "200 OK", but the claim does not remove from the user. 

**Expected behavior:**
All claims which are starting with "identity" are not identity claims.

**Environment information**
 - Product Version: IS 5.11.0

---

[1]. https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L4915

[2]. https://is.docs.wso2.com/en/latest/develop/extending-scim2-user-schemas/#extending-the-scim-20-api

**Comment by nilasini** [comment]
@AnuradhaSK Since we are already tracking the fix for public through [1] can we close this issue? 

[1] https://github.com/wso2/product-is/issues/12932
