### ISSUE TITLE
Improve caching layer of the configuration-mgt service

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#12899]
**Is your suggestion related to an experience ? Please describe.**

Current configuration-mgt caching layer haven't implemented cache support for some commonly using methods like, getFiles() & getFileById()

**Describe the improvement**
Need to have a caching mechanism for following commonly using queries.

- getFiles()
- getFileById()

**Comment by vihanga-liyanage** [comment]
Will be fixed by https://github.com/wso2-enterprise/asgardeo-product/issues/13395

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
