### ISSUE TITLE
Enabling Email Notification in Password Expiry Feature requires IS Analytics

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#12894]
**Describe the issue:**
In order to enable Sending Email Notification functionality in Password Expiry feature requires to install and run IS Analytics alongside WSO2 IS. This seems like an extra mile taken for users who are only using WSO2 IS as the product. As a result, these users would not be able to make use of the Email Notification functionality if they do not wish to maintain another product as well. 

**Expected behavior:**
Email Sending Notification should be available in the WSO2 IS without the need to install and run another entirely different product.

**Environment information:**
 - Product Version:  IS versions 5.6.0 and above
---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
