### ISSUE TITLE
Improve logic in post authentication handlers for back button scenarios

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#12901]
**Describe the issue:**
There are multiple incorrect behaviors in post-authentication handlers and back button scenarios.

1. If JIT provisioning is enabled with consent (Prompt for consent and Prompt for password and consent) and if the user clicks the back button when the consent is prompted and then tries to login with federated IdP user will be provisioned without the user's consent.
2. If a mandatory claim is set in the service provider configurations, and if the user clicks the back button on the mandatory claim prompt screen and tries to login `Mandatory missing claims are not found` error will be shown. This fix was added for #12773. If multi authentication options are configured, this error will be shown to all of them.

These two scenarios raise a user experience issue.

**How to reproduce:**
_Scenario 1_

1. Configure a federated IdP (tested with Google).
2. Enable JIT provisioning with the prompt for password and consent or prompt for consent.
3. Configure a service provider (tested with MyAccount) and set basic authenticator and federated authenticator (google) in the first step.
4. Login with federated IdP.
5. When the consent is prompt, click the back button.
6. Login with federated IdP again.
7. The user will be provisioned without the user's consent.

_Scenario 2_

1. Set a requested mandatory claim in the service provider configuration.
2. Log in to the application and when the mandatory claim is requested, click the back button.
3. Try to log in again.
4. `Mandatory missing claims are not found` error will be shown.

**Expected behavior:**
When a post-authentication handler screen is prompt to the user and if the user presses the back button, there should be a way to restart the authentication flow from the beginning.

**Environment information:**
 - Product Version: IS 5.11.0

**Comment by nilasini** [comment]
@mevan-karu Can we close this issue? ANything pending?
