### ISSUE TITLE
Read-only claims are editable using the SCIM API

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#12910]
**Describe the issue:**
When the read-only attribute is enabled for a claim, the end user should not be able to edit that claim by any means. But read-only enabled claims can be updated using the SCIM apis.
There are several claims that are set to read-only enabled by default such as the Created Time, User Id, etc. When restricting editing access of read-only claims, we should be able to identify the claims that can be updated only by the server and not by the end user. Restricting editing of all read-only claims will create problems when the server needs to update claims such as Created Time and Last Modified Time. 
According to https://github.com/wso2/product-is/issues/11194, the Charon component already contains a validation for the read-only attribute but uses the configurations defined in scim2-schema-extension.config. 

**How to reproduce:**
1. Go to the management console and set the `Read only` attribute of `http://wso2.org/claims/nickname` claim as true.
2. Use the following SCIM call to update the `nickName` claim of any user.
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "value": {
                "nickName": "Ken"
            }
        }
    ]
}
```

**Expected behavior:**
Since the `nickName` claim is set to read-only, the user should not be able to  update this claim using the SCIM API.

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/12837, https://github.com/wso2/product-is/issues/11194

**Comment by piraveena** [comment]
Similar to https://github.com/wso2/product-is/issues/5841

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
