### ISSUE TITLE
Configuring Email OTP with IS as the email OTP provider and registering as an IdP is not clear

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#12922]
**Is your suggestion related to a missing or misleading document? Please describe.**
Upon configuring Email OTP with IS as the email OTP provider, the section to register it as an IdP is not clear. Ideally, it is required to register an IdP for this scenario as well. The same steps mentioned in [1] should be followed except that the following section is misleading and confuses the reader at a glance as it is added in the same bullet point.
> If you are using Gmail or Sendgrid as the email OTP provider, provide values for Email API and Email fields as well.

**Describe the improvement**
 It would be much clearer if the above mentioned is added as a note underneath the bullet points instead of along with the bullet points. 

IS version: 5.11.0 documentation.

Thanks.

[1] https://is.docs.wso2.com/en/latest/learn/configuring-email-otp/#configure-the-identity-provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
