### ISSUE TITLE
Unique claims and JIT provisioning

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12920]
**Describe the issue:**
When a claim is configured as unique [1], the JIT provisioning flow does not handle the duplicate values properly.

**How to reproduce:**
- Configure the email address as unique
- Have a local user with a given email
- Try to JIT provision a new user with the same email

The user is not created due to claim uniqueness, but no error is shown to the user, and authentication is completed.

**Expected behavior:**
It should show a proper error message. Also should allow the user to fill another value in case if it was entered manually (when Prompt for password and consent scenario)

Need to handle all the scenarios. Because it is possible that email is sent from FIDP or user fills it on the consent page itself.
-  Prompt for username, password, and consent
-  Prompt for password and consent
-  Prompt for consent
-  Provision silently 

Note on "Provision silently "; this may be skipped if we are considering "no errors for silent provisioning", but the authentication flow is still completed and the consecutive flows might break since there is no local associated user.

**Environment information**
 - Product Version: 5.11.0

[1] https://is.docs.wso2.com/en/latest/learn/configuring-uniqueness-of-claims/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
