### ISSUE TITLE
Multitenancy Issue in WSO2 IS 5.11 as KM with APIM 4.0

### ISSUE THREAD

**Issue by soniavarshney** [wso2/product-is#12927]
Description:
We are using WSO2 IS 5.11 as KM with APIM 4.0 setup.
when we create tenant using IS carbon portal its created successfully but when try to login on APIM carbon portal its giving error
and using tenant credential we cant login on APIM devportal and publisher portal
and when I am creating tenant using APIM carbon portal we cant login on IS carbon portal

Error
[2021-12-28 12:25:31,353] ERROR - AuthenticationAdmin System error while Authenticating/Authorizing User : Error when handling event : PRE_AUTHENTICATION

Affected Product Version:
APIM -4.0
IS - 5.11

OS, DB, other environment details and versions:
openjdk 8
openjdk 11

Steps to reproduce:
when we create tenant using IS carbon portal its created successfully but when try to login on APIM carbon portal its giving error
and using tenant credential we cant login on APIM devportal and publisher portal
and when I am creating tenant using APIM carbon portal we cant login on IS carbon portal

**Comment by Jaluanda** [comment]
Having similar issue, wondering how to fix that.

**Comment by robertociuccigiuliani** [comment]
it is the same problem encountered, solution or fix needed

**Comment by ArqamFarooqui110719** [comment]
https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/#step-3-install-and-configure-the-databases
above link may resolve your issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
