### ISSUE TITLE
[Migration]Migrate non-identity claims stored in identity store into the respective user stores

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12932]
**Describe the issue:**

User claims which name starts with "identity" (eg: "http://wso2.org/claims/identityCard" ) currently stored in the identity store as mentioned in https://github.com/wso2/product-is/issues/12898

If the identity store is not an instance of UserstoreBase identity store,
We need to migrate these claims into the respective userstore. (Primary / secondary userstores)

Need this migration once these PRs are merged.
- [x] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/403/files
- [x] https://github.com/wso2-extensions/identity-governance/pull/561/files

**Comment by AnuradhaSK** [comment]
Need to merge these PRs once the migration is done.
- [ ] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/403/files
- [ ] https://github.com/wso2-extensions/identity-governance/pull/561/files

**Comment by AnuradhaSK** [comment]
For each tenant: (can use idn_claim table. Get the dialect id and check the claims)

1. Check the local claim list whether any non-identity claim exists with attribute name starting claims/identity.. (eg: identity card)

**If NO**: No migration required
**If YES**:

In the identified tenant: PRIMARY user store + Count secondary user stores 

1. If one of userstore is READ ONLY:
Notify the user to change the claim to identity claim
2. If ALL userstores are read/write:

- Check map attribute exists 
- **YES**: write to userstore and delete from identity store
- **NO**: get user input from the user for new claim mapping. Do the write

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
