### ISSUE TITLE
Upgrade datasources and commons-io version in forgetMe tool

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12933]
**Is your suggestion related to an experience ? Please describe.**
Related issue https://github.com/wso2/product-is/issues/12930. 
We should upgrade the data sources and commons-io version and test the forgetMe tool. It needs some effort. 

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
