### ISSUE TITLE
Invalid cookie header warnings are seen with the new version of the HttpClient library

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12945]
**Describe the issue:**
Invalid cookie header warnings are seen with the new version of the HttpClient library. The HttpClient seems to have been updated to a new version and as a result, the following warnings are seen whenever the HttpClient library is used and when the cookies do not match the CookieSpecs.DEFAULT policy.

/var/log/mps/wso2carbon.log:TID: [-1] [] [2021-12-30 15:53:44,195] [e6dc9b33-7ce0-46b0-b9f0-5ad8ae9836bb]  WARN {org.apache.http.client.protocol.ResponseProcessCookies} - Invalid cookie header: "Set-Cookie: AWSALBTG=IAdhCH/vJKI4TV3gniSK49gDgjvkbzsKhAPKPdvJRHlH/9JDBs+88QcC7PFnlObc6WW1xMfjqPUdVYSUSfVJ42VWAe51vDjO5Wkqw++mCyqDAXYou8pcaTEzeIa64sf9YFuvhf91ffWUNIAYbIuSiQJKWJWsOJ1dZd5vmpP+l+odzgOzMao=; Expires=Thu, 06 Jan 2022 15:53:44 GMT; Path=/". Invalid 'expires' attribute: Thu, 06 Jan 2022 15:53:44 GMT

In order to avoid the above warning when using the HttpClient, the CookieSpecs.STANDARD should be set as follows.

```
HttpClient httpClient = HttpClients.custom()
        .setDefaultRequestConfig(RequestConfig.custom()
                .setCookieSpec(CookieSpecs.STANDARD).build())
        .build();
```

Further, we could prevent the warning from getting printed in the wso2carbon log file by the below configurations.

1. Open log4j2.properties file from <IS-HOME>/repository/conf directory

2. Add the below section to the end of it.
```
logger.httpclient-cookie.name = org.apache.http.client.protocol.ResponseProcessCookies
logger.httpclient-cookie.level = ERROR
```

3. Now fetch for the "loggers" section in the same file and append "httpclient-cookie" part to the end of it with a comma as below.

```
loggers = AUDIT_LOG, trace-messages, org-apache-coyote, com-hazelcast, ..., ..., ..., httpclient-cookie
```
This warning log is harmless and can be ignored as well.

[1]https://issues.apache.org/jira/browse/HTTPCLIENT-1763

**Environment information** **:**
 - Product Version: [IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
