### ISSUE TITLE
[Migration] Intermediate certificate validation issue in SCIM2 endpoints

### ISSUE THREAD

**Issue by Maliesha** [wso2/product-is#12953]
Intermediate certificate validation is skipped for SCIM2 endpoints in 5.11 and older versions by default. 

With [https://github.com/wso2/carbon-identity-framework#3875](https://github.com/wso2/carbon-identity-framework/pull/3875) we have enabled the intermediate certificate validation for SCIM2 endpoints in the master branch.

It is required to mention this configuration change in the 5.12.0 migration docs. If the user want to skip the intermediate certificate validation for SCIM2 endpoints, then the following deployment.toml config needs to be added under [intermediate_cert_validation].
`exempt_contexts=[“scim2”]`

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
