### ISSUE TITLE
[UI] Text is not align properly in My account login page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#12950]
**Describe the issue:**
The text "Create Account" is not aligned, my account login page

**How to reproduce:**

1. Login to console
2. Enable self registration
3. access my account

**Expected behavior:**
Text should be aligned properly

**Environment information** 
 - Product Version: wso2is-5.12.0-alpha9
 - OS: Mac
 - Database: H2
 - Userstore: LDAP
 - Browser : Safari v15

---

<img width="349" alt="Screenshot 2022-01-07 at 23 29 43" src="https://user-images.githubusercontent.com/39120228/148587821-657742f8-4965-43d7-89f0-dc21aa3aecda.png">

**Comment by piraveena** [comment]
It is not reproducible now
<img width="799" alt="Screenshot 2022-08-02 at 18 03 55" src="https://user-images.githubusercontent.com/17597293/182375719-fbf97bf6-e6f8-4694-9cec-00ee886a5eb2.png">
