### ISSUE TITLE
Getting an errors in console when listing users and groups after creating a secondary user store

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#12965]
**Describe the issue:**
After adding a secondary user store Ldap Read/write or ReadOnly,
There are errors when listing users & groups in console
*No errors in the management console

**How to reproduce:**
1.Add new Ldap user store via management console / console 
2. Login to console and list users & groups

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0 alpha9
 - OS: [Mac
 - Database: Mysql
 - Userstore: JDBC -mysql Primary

---

Uploading issue.mp4…

**Comment by nilasini** [comment]
@NilukaSripalim mp4 which shows reproduce steps, is not uploaded properly. Could you please re upload it?

**Comment by NilukaSripalim** [comment]
Updated, 

https://user-images.githubusercontent.com/39120228/149073784-7909bb26-8f1f-4055-8901-2930bc61a059.mp4

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/3251
