### ISSUE TITLE
Getting an errors and unable to login to console with new tenant credentials.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#12963]
**Describe the issue:**
After adding a new tenant via the management console, with those credentials unable to login to console or My account

**How to reproduce:**
1. Add a new tenant via management console
2. Try to log in to console/myaccount with new tenant credentials

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]5.12.0 alpha9
 - OS: Mac
 - Database: Mysql 5.7
 - Userstore: JDBC

---

Uploading issue.mp4…

![Screenshot 2022-01-11 at 14 01 40](https://user-images.githubusercontent.com/39120228/148907735-b4534b6e-0f11-4e0e-af3b-4c86f704ef7e.png)

**Comment by ShanikaWickramasinghe** [comment]
Observing this issue with the 5.12.0 alpha 10 pack as well

https://user-images.githubusercontent.com/31848014/149891263-958fe66d-1bab-4751-b041-56afea2d1f81.mp4

**Comment by nilasini** [comment]
@Maliesha please verify whether [1] fixes this issue as well.
[1] https://github.com/wso2/identity-apps/pull/2863

**Comment by Maliesha** [comment]
This issue is resolved by [wso2/identity-apps#2863](https://github.com/wso2/identity-apps/pull/2863)
