### ISSUE TITLE
Generate Password Option is not working for a user trying to add to Primary Userstore with Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12969]
**How to reproduce:**
1. Setup postgres 11.5 as the primary db
2. User store store configured for database_unique_id
3. Having a disabled secondaory user store added to the system ( optional)
4. Access console 
5. Go to Users section and try to add a user to primary domain
6. Click on Generate Password

https://user-images.githubusercontent.com/31848014/149070286-162357f7-788a-4ba6-9011-da2d0c39f261.mp4

**Observation**
Password will not generate and UI will not respond once click on that button
NO backend error logs
NO browser errors when inspect 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by piraveena** [comment]
Generate button is not working in any of the infras, there are no any browser calls when clicking the Generate Password button

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/12320
