### ISSUE TITLE
Support account locking after max invalid SMS OTP attempts when validation is done via SMS OTP REST API

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12967]
**Describe the issue:**

- There is a newly introduced SMS OTP REST API, to generate and validate SMS OTPs without initializing an authentication flow. https://github.com/wso2/product-is/issues/12328
- SMS OTP validation via this API doesn't support the feature of account locking when max invalid SMS OTP attempts are reached.
- This feature is available in SMS OTP authenticator level : https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/96
- This account locking feature need to be supported in the REST API usage validation too

 Related issue: https://github.com/wso2/product-is/issues/8472. As mentioned here account locking feature should be separated and taken it into the framework level. Then same functionality can be reused in any authenticator/ REST APIs

- NOTE: same feature should be supported in email otp and totp REST APIs aswell

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
