### ISSUE TITLE
Cannot access Console due to Registered callback does not match with the provided url Error when port offset is changed for the server

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12961]
**How to reproduce:**
1. Setup postgres 11.5 as the primary db
2. User store store configured for database_unique_id
3. Go to deployment.toml and set port offset as 1

```
[server]
offset = "1"
```

4. Up the server and try to access console with https://localhost:9444/console

Getting below error in the UI
![Screenshot from 2022-01-11 12-39-41](https://user-images.githubusercontent.com/31848014/148897203-d613bc83-d601-4fb4-ba1a-080d2ce46570.png)

**Server warning**

`[2022-01-11 12:37:19,883] [8e6cbd57-33a3-44d9-99b1-828c531b0506]  WARN {org.wso2.carbon.identity.oauth2.OAuth2Service} - Provided Callback URL does not match with the provided one.
`
![Screenshot from 2022-01-11 12-42-35](https://user-images.githubusercontent.com/31848014/148897301-44d84f9d-ae89-4d82-8a57-d9f7b2f49144.png)

**Observation**
Login to manegement console > List sevice providers > check oauth callback url for application console
Even though port offset changed by 1 these call back urls does not get updated automatically. Hence getting this error

![Screenshot from 2022-01-11 12-44-33](https://user-images.githubusercontent.com/31848014/148897534-ca1efd3d-744b-40ec-8f1b-120f6f8bca58.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by test123sandushi** [comment]
@ShanikaWickramasinghe In 5.11 also, we need to change the callback URL manually. And it is not good to change the callback URL automatically . 

https://stackoverflow.com/questions/65353663/myaccount-and-console-apps-in-wso2is-5-11-0-are-not-working-when-the-server-star/65354774#65354774

**Comment by sandushi** [comment]
@ShanikaWickramasinghe In 5.11 also, we need to change the callback URL manually. And it is not good to change the callback URL automatically . 

https://stackoverflow.com/questions/65353663/myaccount-and-console-apps-in-wso2is-5-11-0-are-not-working-when-the-server-star/65354774#65354774
