### ISSUE TITLE
Getting "Something went wrong" Error when trying to add a attribute for a registered OIDC application

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12974]
**How to reproduce:**

1. Set up postgres 11.5 as primary db
2. Access Console
3. Register a OIDC application
4. Navigate to Attributes tab of the registered app
5. Try to edit and add a new attribute

**Observation**
Getting a something went wrong page

![Screenshot from 2022-01-12 13-09-24](https://user-images.githubusercontent.com/31848014/149084576-1c1db73c-8152-4fe1-8ef1-2765d1829857.png)

https://user-images.githubusercontent.com/31848014/149087846-57ef0e51-012e-4235-9332-735c62240ce8.mp4

**Environment information (Please complete the following information; remove any unnecessary fields) **
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2896
