### ISSUE TITLE
User sessions are not listed during JIT provisioning when assert identity using the local subject identifier config is enabled

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#12971]
**Describe the issue:**
1. Create an Oauth SP.
3. Enable "assert identity using the local subject identifier are enabled"
4. Set and Federated IDP as the authentication step.
5. Enable JIT provisioning in the IDP.
5. Try authentication flow
6. List out the user session for the authenticated user. This will return an empty list. **Expected: List out the existing sessions**

```
curl --location --request GET 'https://localhost:9443/api/users/v1/me/sessions/' \
--header 'accept: application/json' \
--header 'Authorization: Bearer 96c8bc1b-0061-306a-9f7c-b37481b7dd7c'
```
7. Once the above issue is fixed, session deletion should be work. Once the sessions deleted access tokens should be revoked
```
curl --location --request DELETE 'https://localhost:9443/api/users/v1/me/sessions/' \
--header 'accept: application/json' \
--header 'Authorization: Bearer 96c8bc1b-0061-306a-9f7c-b37481b7dd7c'
```
Related : https://github.com/wso2/product-is/issues/12730

**Comment by piraveena** [comment]
> Once the above issue is fixed, session deletion should be working. Once the sessions deleted access tokens should be revoked

@AnuradhaSK In IS 5.11.0, Tokens can be revoked via the session termination API only if the session-based token binding is enabled. Refer https://github.com/wso2-support/identity-inbound-auth-oauth/pull/847

From 5.12.0 onwards, Tokens can be revoked via the session termination API irrespective of app's binding type.
