### ISSUE TITLE
Getting an error - "Something went wrong" in my account while navigating to the security page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#12972]
**Describe the issue:**
$subject
 
**How to reproduce:**
1. User login to my account
2. navigate to the security page

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12 alpha9
 - OS: Mac
 - Database: MySql
 - Userstore: JDBC Mysql 5.7

---

![Screenshot 2022-01-12 at 12 17 52](https://user-images.githubusercontent.com/39120228/149079122-6169cb7e-a11b-479c-92ef-008817c12f73.png)

**Comment by anuragpathak21** [comment]
It's a blocker issue and open since October 2021 #12583
What is the plan to fix this ?

**Comment by nilasini** [comment]
@anuragpathak21 we are planning to fix this in the next milestone release.
Duplicates https://github.com/wso2/product-is/issues/12583
