### ISSUE TITLE
Update docs related to JIT provisioning user association

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#12975]
Association capability of JIT provisioned user with the local user having the same username is removed as a master fix of patch issue.

Note: Have not decide yet whether this should add to the is-docs or not.

Related PRs: 
- https://github.com/wso2-extensions/identity-governance/pull/546
- https://github.com/wso2-enterprise/asgardeo-app-extensions/pull/1477
- https://github.com/wso2/identity-apps/pull/2762
- https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/128

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
