### ISSUE TITLE
Cannot update the password of the admin via myaccount even though a strong password is entered

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12979]
**How to reproduce:**
1. Set up postgres 11.5 as the primary db
2. Access myaccount as admin:admin
3. Go to security > Change password
4. Try to update the password with a strong password

Even though I enter a strong password it doesnt allow to update the password. Getting a error message as password is not strong. Also theres no indicator for a user about the password pattern he needs to use to set a strong password.

![Screenshot from 2022-01-13 10-37-16](https://user-images.githubusercontent.com/31848014/149269751-6ab641d1-18bf-44e1-87cc-dcded297c88b.png)

https://user-images.githubusercontent.com/31848014/149269776-f6143d9b-0fae-428d-ae25-a4183c97b980.mp4

**Environment information** 
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by DMHP** [comment]
@ShanikaWickramasinghe The message says the current password is not correct. Did we provide the correct password?

**Comment by ShanikaWickramasinghe** [comment]
@DMHP Yes Current password was "admin" the default admin users password. This was the first try to change the admin users password. So yes I provided the correct password and it was "admin"

**Comment by sandushi** [comment]
I'm working on this
