### ISSUE TITLE
Configuring a Outbound Provisioning Connector with Google IDP fails with Something went wrong

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12973]
**How to reproduce:**
1. Set up postgres 11.5 as primary db
2. Access Console
3. Register Google as a IDP
4. Navigate to registered IDP outbound Provisioning tab
5. Add Google as the outbound provisioning connector

**Observation**
Getting a something went wrong page

![Screenshot from 2022-01-12 12-47-37](https://user-images.githubusercontent.com/31848014/149082117-5d0ffdde-d501-4e83-877b-5d4b86887b41.png)

https://user-images.githubusercontent.com/31848014/149082128-69d9efb4-1c98-4e6f-bd1f-3ca65319164e.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by piraveena** [comment]
Adding Outbound provisioning connector using Google, SCIM and Salesforce are also not working in the default pack too. Tried with H2 and postgres, and got the "Something Went wrong page"
<img width="1288" alt="Screen Shot 2022-03-14 at 10 59 55 AM" src="https://user-images.githubusercontent.com/17597293/158111010-e5d83932-b13c-4085-9dd6-d7b090635ccc.png">

Got below error logs in the browser console
`XML Parsing Error: not well-formed
Location: https://localhost:9443/console/resources/i18n/meta.ae017ca2.json
Line Number 1, Column 1: meta.ae017ca2.json:1:1
`

`TypeError: m is undefined
    y https://localhost:9443/console/static/js/main-d0f7163f.3368c2d8.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    sl https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Cu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    unstable_runWithPriority https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    $o https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Tu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    xu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    K https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    onmessage https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    42332 https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    57610 https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    65351 https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    40422 https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    99637 https://localhost:9443/console/static/js/main-102ff935.a278d631.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    <anonymous> https://localhost:9443/console/static/js/main-0a037d97.ac10fad0.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    O https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    <anonymous> https://localhost:9443/console/static/js/main-0a037d97.ac10fad0.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    t https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    <anonymous> https://localhost:9443/console/static/js/main-0a037d97.ac10fad0.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
6049.157d943c.js:2:155128
    al https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    callback https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    gi https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    fl https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    ku https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    unstable_runWithPriority https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    $o https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Su https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    cu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Jo https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    unstable_runWithPriority https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    $o https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Jo https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Xo https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Cu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    unstable_runWithPriority https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    $o https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    Tu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    xu https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    K https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    onmessage https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    (Async: EventHandlerNonNull)
    42332 https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    57610 https://localhost:9443/console/static/js/7878.345c8c12.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    65351 https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    40422 https://localhost:9443/console/static/js/6049.157d943c.js?dfcae3db66cf97bbc850 line 1 > srcScript:2
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    99637 https://localhost:9443/console/static/js/main-102ff935.a278d631.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    n https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    <anonymous> https://localhost:9443/console/static/js/main-0a037d97.ac10fad0.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    O https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    <anonymous> https://localhost:9443/console/static/js/main-0a037d97.ac10fad0.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
    t https://localhost:9443/console/static/js/single.c88e7f3b.js?dfcae3db66cf97bbc850:1
    <anonymous> https://localhost:9443/console/static/js/main-0a037d97.ac10fad0.js?dfcae3db66cf97bbc850 line 1 > srcScript:1
`
<img width="1649" alt="Screen Shot 2022-03-14 at 11 04 07 AM" src="https://user-images.githubusercontent.com/17597293/158111124-c5a2ae50-539b-442e-9196-27790e78916a.png">

**Comment by ShanikaWickramasinghe** [comment]
In the same section when update the outbound provisioning roles section that also doesn't get updated. Does the provided fix will be fixing that too @JayaShakthi97 

![Screenshot from 2022-03-24 14-00-24](https://user-images.githubusercontent.com/31848014/159875059-49e91dca-b944-4fcf-b829-7e49e07d1781.png)

**Comment by JayaShakthi97** [comment]
@ShanikaWickramasinghe No this issue is not fixed.

**Comment by nilasini** [comment]
Shall we create a new issue and track?

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2892
