### ISSUE TITLE
Provide the capability to lock the authentication mechanism

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#12977]
**Is your suggestion related to an experience ? Please describe.**
Say we have a setup where a user can log in through multiple mechanisms such as username/password authentication and multiple federated authentication options(google, facebook, etc) linked to the user's local account(federated login is configured to return the local account as well). If the user gets locked due to a password policy violation or an admin forced password reset, the whole account gets locked, even though login through the federated account is successful since it's configured to send back the local account the user account is locked and cannot proceed.

**Describe the improvement**

- Provide the capability to lock authentication mechanisms.
- Make this capability configurable so the admin can decide to lock the whole account or only to lock the authentication mechanism.

**Additional context**
In case the whole account should be locked that capability also should still be available.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
