### ISSUE TITLE
Cannot Update the Group Name of a newly added Group via Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12981]
**How to reproduce:**
1. Set up postges 11.5 as the primary db
2. Access console as super admin
3. Go to Manage > Groups
4. Add a new Group
5. Will land in registered group edit view
6. Try to update the Group name

THeres a update button avaable in the UI. BUt its disabled. Therefore cannot update the Group name

![Screenshot from 2022-01-13 11-04-52](https://user-images.githubusercontent.com/31848014/149272418-b7ac32f2-b8fa-47ad-82cb-15a4cc4c0460.png)

https://user-images.githubusercontent.com/31848014/149272435-16dab9ca-77d2-4abf-a1a2-456eadb91781.mp4

**Environment information** 

5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2916
