### ISSUE TITLE
Openid connect IDP doesnt validate the jwks endpoint config during the jwks update step and gives a error for jwks during certificate upload

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12986]
**How to reproduce:**
1. setup postgres 11.5 as primary db
2. Register identity provider > with protocol openid connect from console
3. Go to General tab and give a invalid jwks url
4. Click on update
5. It allows to update succcesfully and will get ipdate success message
6. THen change the tab to provide certificates and try to upload a certificate click on finish
7. During that step it gives a error saying cannot remove jwks as it doesnt exist

When updating the jwks url to a non existing value it allowed to update succesfully and later during certificate upload step only it gives the validation error. Better to handle this validation during jwks update step.
![Screenshot from 2022-01-13 16-11-05](https://user-images.githubusercontent.com/31848014/149316647-70259d2f-73ec-4203-9244-6c0b34e8f08e.png)

https://user-images.githubusercontent.com/31848014/149316611-363f92cc-8b0d-49ed-be44-4b59171a4a3b.mp4

**Environment information** 
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291

**Comment by piraveena** [comment]
similar issue is reported here https://github.com/wso2/product-is/issues/13314. Hence closing this
