### ISSUE TITLE
Needs to remove the helper texts that implies update is possible for Read only attributes in the myaccount

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12980]
**How to reproduce:**
1. Set up postgres 11.5 as primary db
2. Access myaccount as admin:admin
3. Go to personal info section
4. As theres a helper text mentioned as Enter your im tried to update the IM value. Then noted that theres no edit icon for that field. THis could be due to this field is read only. So for read only fields better to remove the helper texts that imply users to try to update this field
![test](https://user-images.githubusercontent.com/31848014/149271090-ae99bc54-cd26-4a62-93be-1a4ae4b73760.png)

https://user-images.githubusercontent.com/31848014/149271124-f447d20d-a25f-46fc-88a8-3fba10402a57.mp4

**Environment information**
5.12.0 alpha 9
postgres 11.5
chrome 65
jdk 1.8.0_291
Ubuntu 20.04.3 LTS

**Comment by piraveena** [comment]
Not reproducible in the 6.0.0-beta pack
