### ISSUE TITLE
Provide Crypto Agility for the Credentials

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#12983]
**Is your feature request related to a problem? Please describe.**
Whenever, we need to change the password hash algorithm due to security and compliancy reasons, the passwords immediately become unusable. We should have a migration effort which may require users to reset password with new algorithm.

**Describe the solution you would prefer**
Make the password hash self contain. In addition to the hash of the password, store the algorithm, and the associated settings of the algorithm (such as iteration count, length in PBKDF2) in a json format and store that. Whenever we need a change in those configs, we can validate the password with old configs (which are self contained) and upon success we can re-hash the password with the new configs and store

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
