### ISSUE TITLE
Application Tagging Support 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#12999]
**Is your feature request related to a problem? Please describe.**
In the current product, end-users can see the visible application in the myAccount. In the current view, there is no way to categorize the visible applications. This is not user-friendly. To improve the user experience there should be an option for the developers to select the tags when they create applications.

- [ ] UI improvement in the console for the developers.
- [ ] UI improvement in the MyAccount to display the tags and filter using them.
- [ ] New API to manage tags.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
