### ISSUE TITLE
When login for Management console it lands on the configure tab and not on the Main tab

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#12995]
**How to reproduce:**
1. Download 5.12.0 alpha10 pack
2. Unzip
3. Run sh wso2server.sh and start the pack
4. Access management console
5. Login as admin:admin

Will land on the configure tab (Tenant configuring tab) when login for the management console. Earlier when login for the management console we landed on Main tab. Is this a change done purposely ? If not we need to fix this

https://user-images.githubusercontent.com/31848014/149879545-25d71b85-c0d1-4f22-963e-1b0dfaf9023d.mp4

**Environment information**
5.12.0 alpha 10
H2 default pack
jdk 1.8

**Comment by piraveena** [comment]
Tested in 5.12.0-alpha18-SNAPSHOT pack, It is landing in the Main tab now. 
<img width="1666" alt="Screenshot 2022-03-25 at 13 52 47" src="https://user-images.githubusercontent.com/17597293/160082468-a3c5b2dc-a85e-427e-9511-b41ac17a5d76.png">
