### ISSUE TITLE
On IdP creation JIT Provisioning Configurations defaults to PRIMARY userstore

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#12996]
**Describe the issue:**
When creating an IDP (any kind of template) the JIT provision config always defaults to PRIMARY user store when we send it with a different user store.

**How To Reproduce:**

1. Create an IDP via the API. (Initially make `isEnabled` to `false`)
```
"provisioning": {
    "jit": {
      "isEnabled": false,
      "scheme": "PROVISION_SILENTLY",
      "userstore": "CUSTOMER-DEFAULT"
    },
```
2. Check the saved model from the request's response.
3. It has saved as `userstore: PRIMARY`

**Expected behavior:**
Should preserve `"userstore": "CUSTOMER-DEFAULT"`  when the model is created initially. It should not modify any subfields.

**Notes**
The `PUT` call of jit provisioning working as expected. But not the `POST` call

**Comment by nilasini** [comment]
@lashinijay Can we close this issue?
