### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by hidarraga** [wso2/product-is#12994]
Description:
When you look at the code in GitHub in the LICENSE file, you can see the Apache License provided for the Identity  Server, but when you download the latest released package and open the same LICENSE.txt file, you will find the "WSO2 SOFTWARE LICENSE AGREEMENT" license. Which one of those is the real license of the product?

Affected Product Version:
5.11.0, 5.10.0

Steps to reproduce:

Go to the GitHub tag page (code) of the identity server version 5.11.0
Open the LICENSE file and you will find the Apache License.
Download the official release package (zip file), version 5.11.0.
Decompress the zip file.
Open the LICENSE.txt file.
You will find another license (WSO2 SOFTWARE LICENSE AGREEMENT) and not the Apache License.

**Comment by nilasini** [comment]
If you download the Identity server from wso2 website[1] under "community" then you could see the Apache License.

[1] https://wso2.com/identity-server/#

<img width="1240" alt="Screenshot 2022-03-14 at 12 06 23" src="https://user-images.githubusercontent.com/20336761/158117938-0ec6c6f7-62e4-4891-869b-1159ed2f92ee.png">
