### ISSUE TITLE
Error When Accessing My Account of a Tenant User

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#13003]
**Describe the issue:**
Getting errors when trying to access myaccount of a tenant user. 
- At some occurrences, the UI will land into myaccount home page and give error popups. Also the UUID is shown in the home page instead of the username.

![Screenshot from 2022-01-19 11-11-53](https://user-images.githubusercontent.com/35653110/150073740-f80fdf84-2164-42db-bbc4-365043f85669.png)
![Screenshot from 2022-01-19 11-14-44](https://user-images.githubusercontent.com/35653110/150073795-8377188e-3cf9-4102-bc10-26834b155383.png)

- At some occurrences, the UI will give session expiration popup.

![Screenshot from 2022-01-18 22-03-51](https://user-images.githubusercontent.com/35653110/150073763-a8395c25-a548-4a30-be5f-2b48a5026299.png)

- Able to load the myaccount UI successfully by revisiting the tenanted myaccount path after getting the above errors.
  (having `identity.xml` config: `<EnableTenantQualifiedUrls>false</EnableTenantQualifiedUrls>`)

- After adding the below config to `deployment.toml` and visiting the tenanted myaccount path, browser will redirect to normal myaccount path (https://localhost:9443/myaccount/overview) and shows error messages on screen. This time it will show username instead of UUID. Able to login successfully after revising the tenanted myaccount path.

**How to reproduce:**
1. Login to super tenant management console and create a tenant.
  - tenant name: thamindudj.com
  - admin: thamindu@thamindudj.com
2. Login to myaccount of the newly added tenant admin using https://localhost:9443/myaccount/overview

**Expected behavior:**
Should be able to login to the myaccount of the tenant user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0.alpha 11 (reproduced in alpha 9 and 10 as well)
 - OS: Ubuntu

**Comment by Maliesha** [comment]
Fixed by [wso2/identity-apps#2863](https://github.com/wso2/identity-apps/pull/2863)

**Comment by Maliesha** [comment]
Deprecated the functionality of extracting tenant domain from the subject claim of the ID token in asgardeo-auth-js-sdk repo via [1] since we transferred that functionality to identity-apps repo.

[1] [asgardeo/asgardeo-auth-js-sdk#181](https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/181)
