### ISSUE TITLE
Permissions to entitlement management are ineffective

### ISSUE THREAD

**Issue by amemon** [wso2/product-is#1301]
Hi,

I have created a new regular (non admin) user and then a new role (entitlement-manager) with the following permissions and assigned it to the user.

![image](https://user-images.githubusercontent.com/694744/29217451-1dac817c-7eb2-11e7-9c01-c00fb3509442.png)

Despite of having a permission to create and remove policies, I didn't find a link to perform the functions being signed-in as another (entitlement-manager) user. 

![image](https://user-images.githubusercontent.com/694744/29217518-55399c10-7eb2-11e7-9be7-a90a70eb680f.png)

Above has been tested on wso2-is v5.3.0 

Any ideas?

Many thanks.

**Comment by omindu** [comment]
Hi @amemon,

Thanks for reporting this and this seems like a bug. I have created the JIRA [[1]](https://wso2.org/jira/browse/IDENTITY-6256) to track the issue.

[1] - https://wso2.org/jira/browse/IDENTITY-6256

**Comment by omindu** [comment]
Also, can you try giving the below permission to the role and see whether it caters your requirement ?

![image](https://user-images.githubusercontent.com/9883427/29232236-2bb6c2b8-7f08-11e7-9e0b-c3e1331dbc58.png)

**Comment by amemon** [comment]
Thanks @omindu granting the above permissions indeed helped.

**Comment by amemon** [comment]
Hi @omindu, 

Sorry for the late feedback, the provided approach helped little when restricted privileges are assigned. For example, if I have two roles, say policy-admin and policy-viewer - former works fine, if all the privileges of "Entitlement Management" are assigned. In case of policy-viewer, I intend to let user only view the policies which I did (see the following picture)

![image](https://user-images.githubusercontent.com/694744/30278002-d8b30f78-96f8-11e7-950f-878f83dc5107.png)

Now, if I sign-in as a user with the (aforementioned) policy-viewer privileges, I do not see the list of policies
![image](https://user-images.githubusercontent.com/694744/30278142-36868bfc-96f9-11e7-99e7-ef5d36854a21.png)

Any hints?

**Comment by omindu** [comment]
@amemon We have fixed this issue in IS 5.4.0-Alpha2.
