### ISSUE TITLE
Windows startup script deletes all files if the tmp directory is missing

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#13017]
**Describe the issue:**
The wso2server.bat startup script deletes all files in the pack if the <IS_HOMR>/tmp directory is missing or deleted. In the <IS_HOME>/bin/wso2server.bat file, during the startup, the tmp folder is removed, however, if it missing all of the files would be deleted. 
Please find the logic for the same extracted from a 5.10.0 pack

```
rem ------------------ Remove tmp folder on startup -----------------------------
set TMP_DIR=%CARBON_HOME%\tmp
cd "%TMP_DIR%"
del *.* /s /q > nul
FOR /d %%G in ("*.*") DO rmdir %%G /s /q

```
**How to reproduce:**

- Delete the <IS_HOMR>/tmp folder.
- Try to start the server with the wso2server.bat startup script.

**Expected behavior:**
If the tmp folder is missing, the script should not proceed.

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.11.0]

**Comment by rajithacharith** [comment]
Does it need to stop proceeding if the `tmp` folder is missing as mentioned in **Expected behavior**? @tharakawijekoon 

Checked with shell script (wso2server.sh) it checks for the directory and goes to delete step only if the directory exists. Otherwise script proceeds without any error.

**Comment by tharakawijekoon** [comment]
@rajithacharith Yes, the same should happen when using the wso2server.bat script in windows environments.
