### ISSUE TITLE
internal_login scope is confusing

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#13024]
**Describe the Issue:**
We need to request internal_login scope to be able to access product APIs such as scim/me which does not need higher permissions than being able to login.

But when it is requested the consent page looks like below.
<img width="534" alt="Screenshot 2022-01-24 at 12 29 09 PM" src="https://user-images.githubusercontent.com/32576163/150738703-d260d0fc-eca5-4e41-acbb-6cd2068febc8.png">

This message is confusing and doesn't convey the message properly.

To reproduce:
Send `internal_login` scope in the initial authorize request to the authorize endpoint.

According to the spec:
if someone doesn't request a scope ideally we have to issue a default (name can be anything) or reject it
The current behavior is kind of not the right one.

Need to revise the implementation properly.

How To Reproduce:
request `internal_login` scope in the authorized request.

**Comment by nilasini** [comment]
@sahandilshan Is this issue fixed?

**Comment by sahandilshan** [comment]
@nilasini, No, we still haven't come up with a proper solution to fix this issue. It is still under discussion.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
