### ISSUE TITLE
Support Service Provider specific email templates 

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#13020]
**Is your suggestion related to an experience ? Please describe.**
Currently, when sending email notifications we cannot trigger notification specific to the Service Provider that triggered the notification. This should be feasible. 

**Describe the improvement**
Improve notification handler component to support app-wise specific email notifications.

**Tasks**
- [ ] Add support to handle app-wise email notifications
- [ ] [Add support to send service provider info](https://github.com/wso2-enterprise/asgardeo-product/issues/8987) 
- [x] #13032

**Comment by gspadotto** [comment]
Hi, any news about this feature?
I had several use cases where it would have been handy.

Thank you

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
