### ISSUE TITLE
Cannot inject parameters as Environment Variables in datasource section of deployment.toml

### ISSUE THREAD

**Issue by mxm-tr** [wso2/product-is#13028]
**Describe the issue:**

Environment variable injection seems to not be taken into account in the `[[datastore]]` section of the deployment.toml.

An *Unauthorized* error occurs when accessing the *WSO2IS_CONSENT_DB*, while other databases such as the `[database.user]` work.

Replacing the `$env{MYSQL_PASSWORD}` placeholder with the actual content works. Could it be that the `[[datastore]]` section does not allow environment variables?

**How to reproduce:**

Configure the following in the deployment.toml, and set a value to the environment variable `MYSQL_PASSWORD`

```
[database.user]
    type = "mysql"
    url = "jdbc:mysql://mydb:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false&amp;allowPublicKeyRetrieval=true"
    username = "wso2carbon"
    password = "$env{MYSQL_PASSWORD}"

[[datasource]]
    id="WSO2CONSENT_DB"
    type = "mysql"
    url = "jdbc:mysql://mydb:3306/WSO2IS_CONSENT_DB?autoReconnect=true&amp;useSSL=false&amp;allowPublicKeyRetrieval=true"
    username = "wso2carbon"
    password = "$env{MYSQL_PASSWORD}"
```

The users database is accessible while the consent db is not.

**Expected behavior:**
The `$env{MYSQL_PASSWORD}` is replaced with the value of the environment variable, and the *WSO2IS_CONSENT_DB* is being accessed with its value.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
Could it be related to this issue? https://stackoverflow.com/questions/68257033/wso2-mi-injecting-parameters-as-environment-variables-in-xa-datasource-file-doe

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/product-is/issues/7781
