### ISSUE TITLE
Policies in the "Policy Editor" design view cannot be edited

### ISSUE THREAD

**Issue by amemon** [wso2/product-is#1302]
Hi,

As "admin" user I am not able to edit the policies under the policy editor's design view

![image](https://user-images.githubusercontent.com/694744/29219711-1d3250b2-7eb9-11e7-902b-86e9e8f04dcc.png)

even the context menu (according to the hint) upon right-click does not show any editing options. 
![image](https://user-images.githubusercontent.com/694744/29219918-c9c1927a-7eb9-11e7-956f-c32264fea5ae.png)

Is there anything I should have enabled/configured to achieve the editing?
 
Cheers

**Comment by omindu** [comment]
Hi @amemon,

Unfortunately the design view is not functioning at the moment and there's an ongoing effort to improve the editor.  We have not finalized the exact timeline which this improvement will be completed. However you can follow the discussion [[1]](http://wso2.markmail.org/search/list:org.wso2.architecture#query:list%3Aorg.wso2.architecture+page:1+mid:nqamtioyvr6o2mkv+state:results) related to the feature in WSO2 architecture mailing list. If you have any suggestions feel free to share them with us through the architecture mailing list [[2]](http://wso2.com/mail/).

[1] - http://wso2.markmail.org/search/list:org.wso2.architecture#query:list%3Aorg.wso2.architecture+page:1+mid:nqamtioyvr6o2mkv+state:results
[2] - http://wso2.com/mail/

Thank you!

**Comment by sagara-gunathunga** [comment]
ATM we don't have plans to attend this issue on the immediate release hence closing the issue, however these suggestions considered for the new admin-portal design.
