### ISSUE TITLE
Define Outbound provisioning flows based on the application type

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13040]
**Describe the issue:**
Outbound provisioning flows should work based on the application type.

**- Tenant specific Applications -**
  Outbound configuration of the application should be used.

**- SaaS Applications -**
  If the outbound configuration is enabled in the SaaS app, the same config is applicable for other tenants. 
  eg: 

1.  Assume **App A** a SaaS app created in Tenant carbon.super, and it has been configured for outbound provisioning
2. User management done via App A in carbon.super tenant will be provisioned to configured external systems
3. User management done via App A in in `Tenant foo` will be provisioned to configured external systems
4. `Tenant foo` admin can't manage(enable/disable) the outbound provisioning happening through App A

**- System applications - (eg: console)**
   The outbound provisioning configurations of a system app can be overlayed by other tenants.
  eg: 

1.  **Console app**  in Tenant carbon.super is considered as  a system app. it has been configured for outbound provisioning
2. User management done via console in carbon.super tenant will be provisioned to configured external systems based on the configs related to caron.super tenant's console app.
3. Admin in `Tenant foo` should be able to configure another set of external systems for outbound provisioning. (i.e outbound provisioning of a system app can be overlayed by other tenants) 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha 10

**Comment by AnuradhaSK** [comment]
Consider the changes done in https://github.com/wso2/product-is/issues/12993 when we revise the flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
