### ISSUE TITLE
Doc Feedback: Issue on Bulk Endpoint - BulkResponse object should contain a array of Operations instead of object

### ISSUE THREAD

**Issue by ciriantonio1986** [wso2/product-is#13046]
Location : https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/

The BulkResponse object should contain a array of Operations instead of object. 
https://www.rfc-editor.org/rfc/rfc7644.html#section-3.7 - page 54

**Comment by Anandi-K** [comment]
This issue is no longer reproducible.
Refer [1].

[1] https://github.com/wso2/docs-is/commit/5cdc78352b4ad67d4d61c470d655ce96d58c8632

**Comment by nilminiwso2** [comment]
Closing as per the previous comment.
