### ISSUE TITLE
CaseInsensitiveUsername is enabled by default in toml configurations

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#13055]
Until IS 5.8.0, the default value for `CaseInsensitiveUsername` was `false` (if not specified in user-mgt.xml). But with the new configuration model, it has been set to `true` (in default.json). 

Enabling this could lead to performance degradation when searching for users as the number of users increases if proper indexing has not been done. Therefore this needs to be mentioned in the changelog.

---

If you are migrating from an older version (<=5.8.0) of WSO2 IS and if you had not set a value for `CaseInsensitiveUsername` in the user-mgt.xml, it is required to set the following in the deployment.toml in order to preserve the previous behavior.

```
[user_store]
properties.CaseInsensitiveUsername = false
```
OR
```
[user_store.properties]
CaseInsensitiveUsername = false
```

Additionally, UseCaseSensitiveUsernameForCacheKeys also has to be false in order to avoid cache-related inconsistencies with MySQL and MSSQL DBs.

[1] https://docs.wso2.com/display/IS580/Configuring+a+JDBC+User+Store

**Comment by nilminiwso2** [comment]
Will address this through https://github.com/wso2/product-is/issues/14204
