### ISSUE TITLE
Support urn:ietf:params:scim:schemas:extension:enterprise:2.0:User dialect for User Portal UI

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#13058]
**Describe the issue:**
Claims configured to be supported by default and added to the scim2 schema extension [1] do not show in the User Portal personal info section. This has been fixed for the My Account application in #9654. This fix needs to be backported to the User Portal application.

**How to reproduce:**

1. Create a custom claim and configure it as `supported by default`.
2. Add a scim2 schema extension and a claim mapping to `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` dialect [1].
3. Log in to the user portal and go to the personal info section.
4. Custom claim does not appear in the personal info.

**Expected behavior:**
Claims configured as supported by default and added to the scim2 schema extension should be shown in the user portal.

**Environment information:**
 - Product Version: IS 5.10.0

---

### Optional Fields

[1] - https://is.docs.wso2.com/en/5.10.0/develop/extending-scim2-user-schemas/#extending-scim-20-user-schemas

**Comment by nilasini** [comment]
@kayathiri4 can we close the issue? Anything pendning?

**Comment by kayathiri4** [comment]
> @kayathiri4 can we close the issue? Anything pendning?

We can close this issue.
