### ISSUE TITLE
Environment variables are not resolved in custom datasource configurations

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#13050]
**Describe the issue:**
The environment variables are not resolved for custom datasource configurations as follows.
```
[[datasource]]
id = "CustomDS"
username = "$env{ENV1}"
password = "$env{ENV2}"
...
```
This happens, since the key and value of the above configuration will be read as follows,
```
datasource=[{pool_options.validationQuery=SELECT 1; COMMIT, password=$env{TEST4}, driver={{ DB_DRIVER }}, pool_options.jmxEnabled=false, pool_options.maxWait=60000, id=WSO2ConsentDS, pool_options.testOnBorrow=true, pool_options.maxActive=50, url=jdbc:postgresql://{{ DB_HOST }}:{{ DB_PORT }}/{{ CONSENT_MGT_DB }}, username=$env{TEST3}}]
```
and, hence, [`if (entry.getValue() instanceof String)`](https://github.com/wso2/config-mapper/blob/v1.0.2/src/main/java/org/wso2/config/mapper/ReferenceResolver.java#L173) will return false, as it's an instance of array.

**How to reproduce:**
Define the environment variables and configure the deployment.toml as above and observe whether the environment variables are resolved in master-datasources.xml file.

**Expected behavior:**
Environment variables should be resolved.

**Environment information**
 - Product Version: IS 5.11.0

**Comment by nilasini** [comment]
@rajithacharith Is this issue reproducible in public?

**Comment by rajithacharith** [comment]
> @rajithacharith Is this issue reproducible in public?

Master fix was done with https://github.com/wso2/product-is/issues/7781
Hence closing the issue
