### ISSUE TITLE
Improving integration tests with SAML2 artifact binding test cases

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#13052]
**Is your suggestion related to an experience ? Please describe.**
Currently for product-is there are no integration tests available in order to cover the SAML2 artifact binding scenarios. Because of that some issues can be occurred when updating third party classes and releasing them to live. Such case is occurred in [1]

[1] https://github.com/wso2/product-is/issues/13026

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
