### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by cannontechnology** [wso2/product-is#13057]
Location : https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/

Is there any reason why you cannot add groups to a user?  When creating a new user or editing one I would like to add/edit that persons groups.  The current api will not allow this on the user object.  Instead you have to add the user to the group.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
