### ISSUE TITLE
If IS has a PRIMARY userstore role with the same name of Internal role, internal role renaming reset the permissions of primary userstore role

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13078]
**Describe the issue:**
1. Check the UM_ROLE_PERMISSION table in the latest is-5.10.0 fresh pack. UM_ID = 1 to 5 records of this table contains the permissions of PRIMARY/admin role

![role-permissions-in-freshpack](https://user-images.githubusercontent.com/25483865/152684271-8c057100-42ef-4a0f-8af5-0ac41244b2d8.png)

2. Logged into the management console and add an internal role as Internal/admin with a set of permissions. Then checked the UM_ROLE_PERMISSION table. UM_ID = 15 to 19 are the permissions assigned to the Internal/admin.

![add-internal-admin-role-with-set-of-permissions](https://user-images.githubusercontent.com/25483865/152684283-200e3025-1a2a-400f-ad4b-bf4564d3387c.png)

3. Rename the Internal/admin to Internal/admin-test. This action updates the UM_ROLE_NAME column for records related to both PRIMARY/admin and Internal/admin
![rename-internal-admin-rolename](https://user-images.githubusercontent.com/25483865/152684309-968d71c6-d007-464e-a07f-eafa1602d8b3.png)

Reason:

- Internal role renaming goes into this method [1] which uses domain-free role names. So resetPermissionOnUpdateRole method invoked inside this method [2] updates the records related to the PRIMARY/admin role.
- After the above call, again resetPermissionOnUpdateRole is invoked with role names including the domain name[3]. This will update the Internal/admin related records
- Even though the role rename was succeeded for the Internal/admin role, this action removes the PRIMARY/admin role permissions. That's the reason for admin user was not being able to log in to mgt console/ became fully unfunctional.

4. When restarting the server, registration initialization happens. In that flow, addAuthorization method is invoked. If the adminRole doesn't have existing permissions this method[4] adds back the relevant permission to the role. So the PRIMARY/admin role gets the required permissions and becomes functional after the server restart.

![after-restart](https://user-images.githubusercontent.com/25483865/152684412-c0b6c9d2-993f-4fd1-aa9d-95d92c1f6e3e.png)

The above-mentioned bug is applicable for any INTERNAL role if the system has a role with the same name in the PRIMARY domain. Once the internal role is renamed, the corresponding role in the PRIMARY domain will lose all permissions. **Even though in the above case PRIMARY/admin role restores the permissions in the server startup, such restoring won't happen for other roles**.

[1] https://github.com/wso2/carbon-kernel/blob/b86a76b5f135b2928f19c27a2a3c833f9722a8e5/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L5783
[2] https://github.com/wso2/carbon-kernel/blob/b86a76b5f135b2928f19c27a2a3c833f9722a8e5/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/hybrid/HybridRoleManager.java#L934
[3] https://github.com/wso2/carbon-kernel/blob/b86a76b5f135b2928f19c27a2a3c833f9722a8e5/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L5791
[4] https://github.com/wso2/carbon-kernel/blob/b86a76b5f135b2928f19c27a2a3c833f9722a8e5/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/authorization/JDBCAuthorizationManager.java#L1127

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.1.0 to IS-5.10.0
 IS-5.11.0 doesn't;t affected due to group role separation, but still, the same logic is there.

**Comment by nilasini** [comment]
@ImalshaG Can we close the issue?

**Comment by mevan-karu** [comment]
Re-opening this issue to fix the above mentioned issue to other affected IS versions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
