### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings during WSO2 IS 5.6.0 startup

### ISSUE THREAD

**Issue by zidane28** [wso2/product-is#13077]
One of my WSO2 IS (Identity Server) went poof due to physical host error, and when I want to bring back up the IS service, it just hangs and won't start up right after these warning message:

> SLF4J: Class path contains multiple SLF4J bindings.
> 
> SLF4J: Found binding in [bundleresource://539.fwk120694604:1/org/slf4j/impl/StaticLoggerBinder.class]
> 
> SLF4J: Found binding in [jar:file:/usr/lib64/wso2/wso2is/5.6.0/repository/deployment/server/webapps/api%23identity%23entitlement/WEB-INF/lib/slf4j-simple-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]

Aside of IS process hanging, there is no logs generated as well, so as per the warning messages said, there are conflicting logging classes for WSO2 IS, but I can't find this class whereabout:

> bundleresource://539.fwk120694604:1/org/slf4j/impl/StaticLoggerBinder.class

My current WSO2 IS version is 5.6.0 and due to some restriction I can't upgrade the version and I don't think versioning is the issue here.

I had search all over the internet but mostly involve edit pom / maven kinda stuffs but WSO2 IS is supposed to be ready product right? Well, thus until now I still can't find any solution.

Can any kind soul help me with this issue?

Thank you.

 - Product Version: 5.6.0
 - OS: CentOS 7
 - Database: MySQL
 - Userstore: LDAP

**Comment by nilasini** [comment]
Did it[1] solve the issue?
[1] https://stackoverflow.com/a/71016245/6671627

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
