### ISSUE TITLE
username regex configuration is missing when using email as username

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#13079]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the userstore property configuration for email as username feature, provided username regex configuration property is incorrect.

**Describe the improvement**
When using email as username feature, it uses username regex value of following property when self registering the user through account recovery endpoint webapps.

[user_store.properties]
UsernameWithEmailJavaScriptRegEx = '^([A-Za-z0-9_\+\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$'

---

### Optional Fields

**Additional context**

Following code of checkUserNameValid method of UserSelfRegistrationManager class under org.wso2.carbon.identity.recovery.signup package will give more insights.

String regularExpression = 
                       realmConfig.getUserStoreProperty(UserCoreConstants.RealmConfig.PROPERTY_USER_NAME_JAVA_REG_EX);

        if (MultitenantUtils.isEmailUserName()) {
            regularExpression = realmConfig
                    .getUserStoreProperty(UserCoreConstants.RealmConfig.PROPERTY_USER_NAME_WITH_EMAIL_JS_REG_EX);
            if (regularExpression == null) {
                regularExpression = UserCoreConstants.RealmConfig.EMAIL_VALIDATION_REGEX;
            }
        }

**Comment by rksk** [comment]
Related to https://github.com/wso2/product-is/issues/9637

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
