### ISSUE TITLE
wso2carbon.jks with certificate expired

### ISSUE THREAD

**Issue by IgorSakaki** [wso2/product-is#13076]
**Describe the issue:**
wso2carbon certificate has expired, and generate erros with grant-type:jwt-bearer, old totp token and comunication with all products.

**How to reproduce:**
see wso2carbon.jks and client-truststore.jks.

**Expected behavior:**
a easy way to renew ou generate a new certificate

**Environment information**
 - All products in all versions.

**Comment by piraveena** [comment]
@IgorSakaki Thanks for reporting this issue. Certificates are updated in the 5.12.0-alpha product with this PR https://github.com/wso2/carbon-kernel/issues/3178. Hence closing this issue. Please reopen this issue if needed
