### ISSUE TITLE
Align authentication-framework error codes with support branch.

### ISSUE THREAD

**Issue by rajithacharith** [wso2/product-is#13080]
**Description:**
Currently [authentication framework](https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/) error codes are not aligned in public branch[[1](https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkErrorConstants.java)] and the support branch[[2](https://github.com/wso2-support/carbon-identity-framework/blob/support-5.17.5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkErrorConstants.java#L65-L70)]. Need to align error codes in those two branches. Need to check usages of this error codes and need to change the UI if this change affects the error messages.

**Comment by rajithacharith** [comment]
Identified inconsistancies in error codes while fixing https://github.com/wso2/product-is/issues/13018

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
