### ISSUE TITLE
Service Provider JWKS URL is not persisting after updating a SP

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-is#13086]
**Describe the issue:**
Service Provider JWKS URL is not persisting after updating a SP.

**How to reproduce:**
1. Start the Identity Server
2. Create a Service Provider
3. Add a JWKS URL for the Service Provider using the carbon console and click update
4. View the SP again to verify whether it is updated correctly. ( it is not)

**Expected behavior:**
Updated Service provider contains the JWKS URL provided

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0  5.10.0 IS 5.7.0
 - OS: every OS
 - Database: every DB
 - Userstore: N/A

**Comment by nilasini** [comment]
@dimuthnc Are we good to close this issue?
