### ISSUE TITLE
Link for Custom authenicator sample is broken

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#13083]
**Is your suggestion related to a missing or misleading document? Please describe.**
https://is.docs.wso2.com/en/5.10.0/develop/writing-a-custom-local-authenticator/
Here the link for custom local authenticator sample is broken

**Describe the improvement**
Should be able to directly download the sample from the link/ redirect properly.

---

### Optional Fields

**Additional context**
Broken for 5.10, 5.11

**Comment by nilminiwso2** [comment]
Will be fixed with https://github.com/wso2/product-is/issues/12748 for all versions.
