### ISSUE TITLE
TOTP endpoint returns 403 when invoked with access token

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#13090]
**Describe the issue:**
TOTP Endpoint returns a `403 Forbidden` response when invoked with an access token. This happens due to not properly clearing thread local variable added in the implementation done for the #12742.

**How to reproduce:**

1. Reduce the number of maxThreads in the server to a lower amount from deployment.toml file.
```
[transport.https.properties]
maxThreads=2
```
2. Invoke TOTP endpoint several times with basic auth.
```
curl --location --request POST 'https://localhost:9443/t/carbon.super/api/users/v1/me/totp' --header 'accept: application/json' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data-raw '{ "action": "VALIDATE", "verificationCode": "196301"}'
```
3. Generate a new access token with the `internal_login` scope.
4. Invoke TOTP endpoint with the access token.
```
curl --location --request POST 'https://localhost:9443/t/carbon.super/api/users/v1/me/totp' --header 'accept: application/json' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data-raw '{ "action": "VALIDATE", "verificationCode": "196301"}'
```
5. Endpoint will return a 403 error with the following response.
```
{
    "code": "OTP-10005",
    "message": "Access denied.",
    "description": "This method is blocked for the requests with basic authentication.",
    "traceId": "c3c44a84-ce27-4ce7-9679-75257b0bea27"
}
```

**Expected behavior:**
TOTP Endpoint should return a success response instead of `OTP-10005` when invoked with an access token.

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by rksk** [comment]
Cleaning the thread-local in the `OAuth2AccessTokenHandler` only would not be a complete fix since there are other authenticators too.
