### ISSUE TITLE
Incorrect URL in the self registration guide

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#13093]
**Describe the issue:**
We have the following URL in the self registration guide which we don't have. We have `https://localhost:9443/myaccount/overview` now.

```
https://localhost:9443/user-portal
```
[1] -https://is.docs.wso2.com/en/latest/learn/self-registration/

**Products:**
- 5.11 and master

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
