### ISSUE TITLE
wso2is-analytics-5.8.0 latest U2 updated pack is not starting properly

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13099]
**Describe the issue:**
Reproducible steps:

- Get wso2is-analytics-5.8.0+1602171727351 WUM pack and update to latest U2 level with Update 2.0
- Try to start ./worker.sh and ./dashboard.sh
- Set of packages are not activating due to unresolved dependency :
`Unresolved requirement: Import-Package: io.netty.internal.tcnative; version="[2.0.0,3.0.0)"`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: get wso2is-analytics-5.8.0+1602171727351 UWM pack and update to latest Update 2.0

**Comment by ShanChathusanda93** [comment]
Update released. Hense closing the issue.
