### ISSUE TITLE
wso2 is (container linux) Uncaught (in promise) Invalid id_token in the token response /myaccount

### ISSUE THREAD

**Issue by miguelampudia** [wso2/product-is#13108]
When you install wso2 is in its version 5.11 through docker in a virtual machine of azure S.O oracle linux 8. I am getting the following error Uncaught (in promise) Invalid id_token in the token response and it is intermittent when reloading /myaccount.

I don't have a proxy and it's the only node.

![image](https://user-images.githubusercontent.com/11429096/153696377-3b939e69-42f7-43c0-b1f8-138a324a9964.png)

![image](https://user-images.githubusercontent.com/11429096/153696384-744cdd98-c217-4ce4-b85a-c40ce45136b2.png)

![image](https://user-images.githubusercontent.com/11429096/153696389-569bcdb5-a87c-4a32-877d-67897f60b023.png)

configuration file deployment.toml

----------------------------
[server]
hostname = "xxxxxx.cloudapp.azure.com"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "xxxxxx"
create_admin_account = true

[user_store]
type = "read_write_ldap_unique_id"
connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated

[database.identity_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[cors]
allow_generic_http_requests = true
allow_any_origin = true
allow_subdomains = true
supported_methods = [
    "GET",
    "PUT",
    "POST",
    "HEAD",
    "OPTIONS"
]
support_any_header = true
supported_headers = []
exposed_headers = []
supports_credentials = true
max_age = 3600
tag_requests = false

-------------------------------

docker compouse

-----------------------------

version: "3.8"
services:
  xxxxx.cloudapp.azure.com:
    restart: always
    image: wso2/wso2is
    ports:
      - "9443:9443"
    volumes: 
      - ./conf:/home/wso2carbon/wso2-config-volume
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 1000M
            reservations:
              memory: 500M

-------------------------------

I appreciate any help you can give me

**Comment by nilasini** [comment]
@miguelampudia Could you please check on the blog [1]
[1] https://medium.com/identity-beyond-borders/fix-invalid-id-token-issue-in-wso2-identity-server-5-11-0-6bd9f7dc5db6

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
