### ISSUE TITLE
Document gaps in SCIM docs

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#13110]
**Is your suggestion related to a missing or misleading document? Please describe.**
In addition to the changes described in [1], document the following:

- Bulk role creation, update and remove

[1] https://github.com/wso2/product-is/issues/12127

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
