### ISSUE TITLE
unable to extract log4j-api-2.17.1.jar shipped in the 5.10.0 pack

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#13117]
**Describe the issue:**
unable to extract log4j-api-2.17.1.jar shipped in the 5.10.0 pack

**How to reproduce:**
Download a pack with update level 5.10.0.114
Try to extract the log4j-api-2.17.1.jar shipped inside it.

**Expected behavior:**
It should be possible to extract the log4j-api-2.17.1.jar file.

**Environment information** **:**
 - Product Version: [IS-5.10.0.114]

**Comment by piraveena** [comment]
Fixed it for IS-5.10.0.114

**Comment by jasmine0508** [comment]
From where can i download the fixed update for IS v5.11 in git releases
