### ISSUE TITLE
Missing documentation on setting up Active-Active and Active-Passive Identity Server clusters

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#13118]
Similar to APIM old docs[1] we too need to have some latest docs on configuring Identity Server clusters.
* Active/Active
* Active/Passive

[1] https://docs.wso2.com/display/AM200/Configuring+an+Active-Passive+Deployment

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
