### ISSUE TITLE
Unit tests and Testing dependencies are bundling in to the Distribution

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#13134]
**Describe the Issue:**
When I analyze the Console dist bundle I could see that the `unit tests` and testing dependencies are getting bundled.

Further digging showed that the extensions model is causing the issues[2]. And also it was causing some rendering issues as well (Tenant switch loaded as an extension is rendered multiple times) [3] 

[1]
<img width="1917" alt="Screen Shot 2022-02-18 at 8 06 31 PM" src="https://user-images.githubusercontent.com/25959096/154801771-f23b983d-621c-40e0-8de9-af35fa6a44ef.png">

[2]
<img width="969" alt="Screen Shot 2022-02-18 at 8 04 55 PM" src="https://user-images.githubusercontent.com/25959096/154801792-140da79c-1bfa-4083-98e3-e1b12027e5c4.png">

[3]
<img width="874" alt="Screen Shot 2022-02-18 at 8 04 29 PM" src="https://user-images.githubusercontent.com/25959096/154832938-a4f12de7-4204-42b6-800d-7d9275a4a809.png">

**How To Reproduce:**
1. Run the bundle analyzer in Console (https://github.com/wso2/identity-apps/blob/master/docs/write-code/README.md#analyze-for-console)

**Expected behavior:**
Tests and test dependencies should be left out of the bundle.

**Device Information:**
 - Device (e.g. PC, iPhone6):
 - OS (OSX, Android, iOS):
 - Browser + Version:

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
