### ISSUE TITLE
Error in scim user filtering when MySQL is the primary userstore

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13133]
**Describe the issue:**
User filtering SQL query is not generating correctly when multiple user claim conditions are present in the filter.
**How to reproduce:**
- Configure MySQL DB as a primary user store
- Create users :

1. Username: **john** , first name : **john**, Lastname: **wick**
2. Username: **john1** , first name : **john**, Lastname: **lennon**

- Execute the following scim requests. Ideally, the first request should return the first user, the second request should return the second user.
But both API responses have the same user.

https://localhost:9444/scim2/Users?filter=userName eq john and name.givenName eq john and name.familyName eq wick
https://localhost:9444/scim2/Users?filter=userName eq john1 and name.givenName eq john and name.familyName eq lennon

Refer:
https://wso2is.slack.com/archives/CDWPC5MUL/p1643997087203189

**Comment by piraveena** [comment]
It works in postgresDB

**Comment by Avarjana** [comment]
Closing since this works in wso2is-6.0.0-beta pack with MySQL as expected.
