### ISSUE TITLE
Specify deployment artifacts that needs to be synchronized

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#13144]
The following doc speaks about setting up deployment synchronization between nodes. Better if the doc can specify what are the exact files/directories that needs to be synced explicitly. Ex: workflows, user stores

 https://is.docs.wso2.com/en/latest/setup/configuring-rsync-for-deployment-synchronization/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
