### ISSUE TITLE
Deprecation the Security Manager in JDK 17

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#13143]
Java security manager will be deprecated with JDK 17[1] and removed in future releases. We need to analyse and check the impact of this to the wso2 identity server.

[1] - https://openjdk.java.net/jeps/411

**Comment by nilasini** [comment]
Track this with Java 17 support

**Comment by Thumimku** [comment]
Tested in 5.11 but this feature is not working as expected in 5.11 also. Hence before supporting JDK 17 for security manager, we need to run this feature in 5.12(I am not working on this.)

Issue Tracked Here: https://github.com/wso2/product-is/issues/14040

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
