### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by rajatKagrawal** [wso2/product-is#13149]
Location : https://is.docs.wso2.com/en/latest/learn/forced-password-reset/#using-scim-20-api

the endpoint to force admin password reset for user: `https://<host>:<port>/scim2/Users/<users-scim-id>` should be of method type: `PATCH` it is wrongly mentioned as method `POST` in the code snippet, were as in curl snippet it is correct.

**Comment by Anandi-K** [comment]
Duplicate issue https://github.com/wso2/product-is/issues/12865
