### ISSUE TITLE
[IS Start-up] Errors logged when starting IS pack, MyAccount and Console could not be accessed 

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13156]
**Describe the issue:**
Several errors were logged in the terminal when starting the IS alpha pack (see details in below in comments).
Even though the pack started and the Management Console can be accessed, MyAccount and Console cannot be accessed - getting 404 when trying to access the URLs. 

**How to reproduce:**
Test platform: Windows 10, JDK8, Firefox 97
Download and start the IS 5.12 alpha pack (checked with alpha 12 and 13)

**Expected behavior:**
- No errors are expected at startup
- MyAccount and Console should be available to access

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 alpha 12 and 13
 - OS: Windows 10
 - Database: H2 and MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

---
*Screenshots*
![image](https://user-images.githubusercontent.com/37894306/155472161-5184ef25-dcbd-47c6-b421-54e4fa62945e.png)

**Comment by nilasini** [comment]
@deshalw shall we remove the doc link and add the relevant details in the git issue shortly? Because the doc is not publicly available

**Comment by deshalw** [comment]
Error references: 

``` ERROR {org.wso2.carbon.webapp.mgt.loader.SharedClassLoaderFactory} - Error while creating class loader for CXF3 java.io.IOException: The filename, directory name, or volume label syntax is incorrect ```

``` ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/accountrecoveryendpoint]} - Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.mgt.endpoint.util.listener.IdentityManagementEndpointContextListener] java.lang.NoClassDefFoundError: org/apache/cxf/jaxrs/provider/json/JSONProvider  ```

``` ERROR {org.wso2.carbon.tomcat.internal.CarbonTomcat} - Cannot stop context org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_stop]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/accountrecoveryendpoint]] in state [DESTROYED] ```

**Comment by deshalw** [comment]
Workaround: https://github.com/wso2/product-is/issues/12767#issuecomment-982338215

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/12767
