### ISSUE TITLE
Multiple config properties to display user attributes on different UIs instead of common "Supported by Default"

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13153]
**Describe the issue:**

**Current behavior:**
For the local claims, we have metadata called "Supported by Default" with this description.
![Screenshot - 2022-02-20T210036 589](https://user-images.githubusercontent.com/25483865/155389295-ba959845-c448-4139-9ae3-b1aad2b406b5.png)

If this config is checked for a particular claim, it is displayed on :

- User profiles in the management console
- User profiles in the new beta console 
- User profile info section of MyAccount (In IS 5.10.0 user profile info of user-portal and prior to IS-5.10.0 user profile of dashboard)
- Self-registration page

**Expected behavior** 
 A claim config needs to have a set of properties, where each property can be used for different purposes on different UI.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
