### ISSUE TITLE
screenUserAttribute value is not displayed when the mobile number is not available in SMS OTP flow

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#13150]
**Describe the issue:**
The screenUserAttribute value in the SMS OTP flow is not displayed in a consistent way in the two different scenarios listed below.
1. The user is having a mobile number - When the user is prompted for SMS OTP code, the screenUserAttribute is shown as expected.
2. The user doesn't have a mobile number - Since the user doesn't have a mobile number, the user will be prompted to enter the mobile number first, and then the OTP code will be prompted. In this scenario, the screenUserAttribute value is not displayed.

This happens, since when the screenUserAttribute is prepared, the [screenUserAttributeValue](https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/v3.0.12/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L1437) is null, as the mobile number prompted by the user is not yet persisted in the user profile.

**How to reproduce:**
1. Configure SMS OTP with screenUserAttribute.
    ```
    [authentication.authenticator.sms_otp.parameters]
    ...
    noOfDigits = 3
    screenUserAttribute = "http://wso2.org/claims/mobile"
    ```
2. Try out the SMS OTP flow with a user who is having a mobile number claim value.
3. Try out the SMS OTP flow with a user who doesn't have a mobile number claim value.

**Expected behavior:**
The screenUserAttribute value should be displayed in a constant manner.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by nilasini** [comment]
@wenodpathirana Can we close this issue? Is there anything pending?

**Comment by wenodpathirana** [comment]
@nilasini yes, we can close the ticket.
