### ISSUE TITLE
Something went wrong page when trying out redirect to IS error page from adaptive script.

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#13159]
**Describe the issue:**
- We have an adaptive function ([sendError](https://is.docs.wso2.com/en/latest/references/adaptive-authentication-js-api-reference/#senderrorurlparameters)) to direct the user to IS error page with custom error messages. 

This has been broken in the latest versions due to a content spoofing fix. So as a solution, we need to store these error content to cache and retrieve back from the page and show it to the user.

**Comment by nilasini** [comment]
@senthalan are we good to close this issue?

**Comment by senthalan** [comment]
yes. this can be closed
