### ISSUE TITLE
[MyAccount] Security key registration - confirmation pop-up image overlaps with title

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13165]
**Describe the issue:**
The animated icon in confirmation pop-up which is displayed when registering a new security key in MyAccount > Security > Security Key/Biometrics overlaps with the title text

**How to reproduce:**
1. Go to MyAccount > Security
2. Register a new biometric
3. Check the confirmation pop-ups (pass and fail scenarios)

**Expected behavior:**
The image should not overlap with the text

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12 Alpha 13
 - OS: Windows 10/Firefox 97 - (resolutions: 1920x1080 and 2560x1440)
 - Database: MySQL 8.2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

--- 
*Screenshots:*
![MyAccount- securityKey - success](https://user-images.githubusercontent.com/37894306/155721316-4c46c2b8-c464-40c1-8151-dbf92492cb5c.png)
![MyAccount- securityKey - fail](https://user-images.githubusercontent.com/37894306/155721340-c3f3861d-3d78-44ab-ae4d-5a513c19d4c2.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
