### ISSUE TITLE
[MyAccount] "https://localhost:<port_number>/user-portal" cannot be accessed - getting 401

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13179]
**Describe the issue:**
Getting 401 when trying to access MyAccount via `https://localhost:<port_number>/user-portal` (Ref. [IS Documentation Link](https://is.docs.wso2.com/en/latest/learn/password-recovery/))

**How to reproduce:**
Try to access the URL mentioned above to recover a password as stated in the mentioned IS doc reference. 

**Expected behavior:**
User-portal should be available to access

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 Alpha 13
 - OS: Windows 10
 - Database: H2/ MySQL
 - User store: JDBC

Note:
- `https://localhost:<port_number>/MyAccount` can be accessed and used

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by deshalw** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/37894306/156019781-729fe8a7-dd19-4051-badf-4bc78a2abaf0.png)

**Comment by nilasini** [comment]
@deshalw this is a documentation issue. user-portal will not be accessible with latest releases. You have to use myaccount instead of user-portal. Please create documentation issue
