### ISSUE TITLE
Should not support regex pattern in SCIM2 filtering eq operator #8054

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#13171]
**Describe the Issue:**

We allow regex patterns in `eq` operator in SCIM2 filtering. But in the spec, it says, it should be identical. https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.2

```
 The attribute and operator values must be identical for a match.                
```

SCIM request: 
`https://api.asg.io/scim2/Users?filter=username+eq+test*&domain=ASGARDEO-USER
`

We get below response:

```
{
    "totalResults": 2,
    "startIndex": 1,
    "itemsPerPage": 2,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "emails": [
                "testasgardeotest1@gmail.com"
            ],
            "meta": {
                "created": "2021-10-11T04:07:34.902Z",
                "location": "https://api.asg.io/scim2/Users/e4d7fe58-b2ba-49f5-83ea-3dbe6a209e16",
                "lastModified": "2021-10-11T04:07:34.902Z",
                "resourceType": "User"
            },
            "roles": [
                {
                    "display": "everyone"
                }
            ],
            "id": "e4d7fe58-b2ba-49f5-83ea-3dbe6a209e16",
            "userName": "ASGARDEO-USER/testasgardeotest1@gmail.com"
        },
        {
            "emails": [
                "testasgardiotest@gmail.com"
            ],
            "meta": {
                "created": "2021-10-11T04:07:20.674Z",
                "location": "https://api.asg.io/scim2/Users/48af03b4-508c-4941-96c8-39312e961b1a",
                "lastModified": "2021-10-11T04:07:20.674Z",
                "resourceType": "User"
            },
            "roles": [
                {
                    "display": "everyone"
                }
            ],
            "id": "48af03b4-508c-4941-96c8-39312e961b1a",
            "userName": "ASGARDEO-USER/testasgardiotest@gmail.com"
        }
    ]
}
```
We need to check for other operators and see whether spec supports regex patterns.

**How To Reproduce:**
Invoke SCIM2 Get user filtering with `eq` operator
`https://api.asg.io/scim2/Users?filter=username+eq+test*&domain=ASGARDEO-USER
`

**Expected behavior:**
It should return 200 ok with 0 total results

```
{
    "totalResults": 0,
    "startIndex": 1,
    "itemsPerPage": 0,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ]
}
```

**Device Information:**
 - Device (e.g. PC, iPhone6):
 - OS (OSX, Android, iOS):
 - Browser + Version:

---
Also We need to check for other operators and see whether spec supports regex patterns.

Notes: Identified by @piraveena

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
