### ISSUE TITLE
Configuration to disable/enable special characters in SCIM2 endpoint

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#13174]
**Describe the issue:**
From our SCIM2 endpoints, we can add the special characters (JS tags such as <script>alert;</script>) to the user claims without an issue. However, this is not allowed in the management console and a message received saying special characters are not allowed due to security measures.

It would be really useful if a configuration exists to enable or disable accepting these special characters from the SCIM2 endpoint.

**How to reproduce:**
Try a patch request such as the following to the SCIM2 Users endpoint.
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "add",
            "value": {
                "nickName": "<script>alert(1)<\/script>"
            }
        }
    ]
}
```

**Expected behavior:**
Provide a backend validation to restrict (<>`\") characters, but based on a configuration because we need to support backward compatibility.

**Environment information**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

**Comment by rksk** [comment]
This is not yet documented!

**Comment by rksk** [comment]
> Adding user claim regex validation configuration wso2/carbon-identity-framework#3940

Will be tracked in https://github.com/wso2/product-is/issues/16399
