### ISSUE TITLE
[Password Recovery] "Mapped attribute cannot be found for claim" error when trying to recover password 

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13178]
**Describe the issue:**
When a user tries to recover password from console, `Mapped attribute cannot be found for claim` error is logged and the recovery email is not received

**How to reproduce:**
1. Setup email configs in deployment.toml and restart IS
2. Setup a valid email address in a user's profile (tried with admin and a new user)
3. Try 'Forgot password' option in the console login screen 

**Outcome:**
- $subject (refer comment-1 for error details)
- However, front-end shows a message which states the password recovery email has been sent

**Expected behavior:**
- The error is not expected, it has to be investigated and fixed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 Alpha 13
 - OS: Windows 10
 - Database: H2/ MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by deshalw** [comment]
Error log:
```[2f889543-64ef-4afa-b0ae-4f28fff5e358] ERROR {org.wso2.carbon.identity.recovery.password.NotificationPasswordRecoveryManager} - Error occurred while checking user's local credential availability. Error message: org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : http://wso2.org/claims/identity/localCredentialExists in user store : PRIMARY```

**Comment by piraveena** [comment]
I could able to receive emails. 
<img width="1065" alt="Screen Shot 2022-03-14 at 1 57 32 PM" src="https://user-images.githubusercontent.com/17597293/158133671-2e36c509-fadc-4ce1-96d5-93ea6ebfad37.png">


But could see below error logs in the backend 
`[2022-03-14 13:27:11,878] [16ed93c2-1449-4fa5-aa47-89c5beb2a990] ERROR {org.wso2.carbon.identity.recovery.password.NotificationPasswordRecoveryManager} - Error occurred while checking user's local credential availability. Error message: org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : http://wso2.org/claims/identity/localCredentialExists in user store : PRIMARY`


https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/password/NotificationPasswordRecoveryManager.java#L276

**Comment by deshalw** [comment]
Re-tested the scenario and the email was received as expected. Notifications from the original test execution were sent to the spam in Gmail.
