### ISSUE TITLE
Update the bundle name xmlbeans:xmlbeans jar

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#13183]
## Improvement

We have upgraded the xmlbeans version embedded inside the xmlbeans_2.3.0.wso2v1 jar. Since we have updated the version, the jar name also needs to be updated to the latest.

**Comment by nilasini** [comment]
Can you please specify the PR which changes the xmlbeans version? Did you check the xmlbeans version packed inside latest IS?

**Comment by piraveena** [comment]
Checked the xmlbeans version in the 5.12.0-alpha 18 snapshot pack and it is still embedding 2.3.0 xmlbeans version

**Comment by IsankaSR** [comment]
Related PRs: 
https://github.com/wso2/carbon-kernel/pull/3140 
https://github.com/wso2/orbit/pull/513/files

**Comment by nilasini** [comment]
@IsankaSR https://github.com/wso2/carbon-kernel/pull/3140 get closed without getting merged. Could you please check on that and do the necessary changes to update the xmlbeans jar and close this issue?

**Comment by IsankaSR** [comment]
> @IsankaSR [wso2/carbon-kernel#3140](https://github.com/wso2/carbon-kernel/pull/3140) get closed without getting merged. Could you please check on that and do the necessary changes to update the xmlbeans jar and close this issue?

Reopend and merged.
