### ISSUE TITLE
[Migration] Upgrading H2 DB Version

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#13182]
The H2 engine version is upgraded from 1.4.199 to 2.1.210 in the product IS. With this change, it will not be possible to interact with existing H2 databases which were created from the older H2 version. 

Even though it is not recommended to use H2 databases in the production environment, if a customer who wish to migrate from 5.11.0 to 5.12.0 is using the H2 DBs, they will have to migrate these databases to the new version. A H2 migration tool created for this migration is available at https://github.com/wso2/samples-is/tree/master/h2-migration-tool. 

It is required to provide the necessary instructions to use this migration tool if necessary, in the migration docs for 5.12.0. 

With this upgrade, the H2 console will be removed from the product IS, and it is required to mention the removal of the H2 console and the need for H2 DB migration in the 5.12 migration docs. The removal of the H2 console should be mentioned in the `What has Changed` page.

Related to: https://github.com/wso2/product-is/issues/13162

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
