### ISSUE TITLE
Create a new release of the samples-is compatible with IS 5.12

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#13194]
**Describe the issue:**
We need to create a samples-is release with the latest keystore changes [1], and test it with IS-5.12 and make it compatible.
We would need to update the sample app links in the 5.12 docs after this is released.

[1] - https://github.com/wso2/samples-is/pull/307

**Comment by ImalshaG** [comment]
Samples-is version 4.5.0 is released: https://github.com/wso2/samples-is/releases/tag/v4.5.0 which is compatible with IS 6.0.0.

**Comment by chamathns** [comment]
@ImalshaG, have we tracked updating the doc links for the sample apps v4.5.0?
