### ISSUE TITLE
TOML configuration for custom grant handler is not documented

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#13192]
**Describe the improvement**
The configuration below is not documented, which is used to change the default grant handler for the saml bearer grant in the documentation [1].
```
[oauth.grant_type.saml_bearer]
grant_handler = "com.hilton.wso2.carbon.apimgt.keymgt.handlers.HiltonExtendedSAML2BearerGrantHandler"
```

[1] https://is.docs.wso2.com/en/latest/learn/setting-up-a-saml2-bearer-assertion-profile-for-oauth-2.0/

**Comment by rksk** [comment]
Pending: to be added to master

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
