### ISSUE TITLE
Release connectors compatible with IS 6.0.0 and update the connector store

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#13193]
**Describe the issue:**
With the 6.0.0 release, we need to make sure the connectors are compatible with the product and need to update the connector store accordingly.

**Comment by asha15** [comment]
These connectors have been tested and updated in the connector store:

- [Email Notification Handler](https://store.wso2.com/store/assets/isconnector/details/959b792a-efce-4b12-af9b-4744c650f6b2)
- [CAS inbound authenticator ](https://store.wso2.com/store/assets/isconnector/details/593aac68-3139-425c-b9ca-f66a65a0917a)

**Comment by asha15** [comment]
These connectors were tested and updated in the connector store:

- [Email Notification Handler](https://store.wso2.com/store/assets/isconnector/details/959b792a-efce-4b12-af9b-4744c650f6b2)
- [CAS inbound authenticator ](https://store.wso2.com/store/assets/isconnector/details/593aac68-3139-425c-b9ca-f66a65a0917a)
- [Reddit](https://store.wso2.com/store/assets/isconnector/details/45092602-8b7b-4f29-9d66-cc5b39990907)
