### ISSUE TITLE
 Update xmlsec version to 2.1.7 in wss4j and rampart-core

### ISSUE THREAD

**Issue by minolih** [wso2/product-is#13205]
**Describe the issue:**

- [ ] Upgrade xmlsec version of wss4j from 1.5.2 to 2.1.7 to resolve dependency conflicts with STS Connector 5.6.5. 
- [ ] Resolve code-level errors due to version upgrade in wss4j. 
- [ ] Upgrade xmlsec version of rampart-core to 2.1.7.

**Comment by piraveena** [comment]
https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/124
