### ISSUE TITLE
OAuth client_id is case-insensitive with certain DB vendors

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#13203]
**Describe the issue:**
As per the OAuth specification, all parameters including client_id must be case sensitive (see https://tools.ietf.org/html/rfc6749#section-1.9). But the client id is searched on the DB and the DB does the comparison in a case-insensitive manner which will eventually allow completing the flow.

**How to reproduce:**
- Configure IS with a case-insensitive DB (MySQL or SQLServer)
- Create a service provider 
- Try to generate access tokens with any grant type by using the client id in a different case
- It will issue the token (except when you are using JWT issuer as explained in https://github.com/wso2/product-is/issues/13202)

**Expected behavior:**
All parameters used in OAuth including client_id must be case sensitive

**Related issues:**
https://github.com/wso2/product-is/issues/13202

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
