### ISSUE TITLE
Update keystores with renewed CA certs

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#13210]
**Describe the issue:**
The keystore  currently in the product-is contains outdated certificates. The keystore update done with https://github.com/wso2/carbon-kernel/pull/3224 to the 4.6.x branch includes updated certificates with the base keystore being extracted from JDK 17. 

**Approach:**
Port the fix https://github.com/wso2/carbon-kernel/pull/3224 to kernel 4.7.x branch

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/3179
