### ISSUE TITLE
When a User enters a invalid user code in OAuth Device Flow theres no proper indication for the user that the user code is invalid

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13213]
**Describe the issue:**
When a User enters a invalid user code in OAuth Device Flow theres no proper indication for the user

**How to reproduce:**
1. Follow https://github.com/wso2/docs-is/blob/master/en%2Fdocs%2Flearn%2Ftry-device-flow.md
2. Obtain a user code with the API
3. Access the verification uri https://localhost:9443/authenticationendpoint/device.do
4. Enter a invalid code in the user code pop up

**Actual behavior:**

There should be a indication for the user when the user code is invalid. UI just get cleared and only in the browser tab we can see that its a invalid request. There should be a proper UI error popup given fro the user indicating that the user code provided is invalid. This might result a bad user experience.

https://user-images.githubusercontent.com/31848014/157207878-ae2d4d43-2401-40ec-81f8-2c608f164903.mp4

![Screenshot from 2022-03-08 14-51-56](https://user-images.githubusercontent.com/31848014/157207899-4e792571-d6c5-4599-9f5f-b404413a4f41.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.11.0 alpha 14
H2

**Comment by senthalan** [comment]
The proposed change will look like this,
When the wrong code is entered, this error will be showed to the user

![image](https://user-images.githubusercontent.com/11584828/161957557-9c1992e5-9a69-438c-90ab-106ad32c6433.png)

**Comment by nilasini** [comment]
@senthalan can we close this issue?

**Comment by senthalan** [comment]
yeah. we can close this.
