### ISSUE TITLE
Product improvements to device flow

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#13216]
- Support unit resolving for device flow related configuration
- Fix the same token been issued for if one user login to multiple devices
- Add the device endpoint to the discovery response
- UI improvements for the User code input page

**Comment by ShanikaWickramasinghe** [comment]
@senthalan Shall we update the issue with more details. As we have concluded 1 test round for this feature with alpha 14 pack we can consider these improvements with alpha 15. Better to add screenshots or detailed steps on the improvements planned to do. If we have all the information in the issue that will help to complete the next round of testing with less time.

**Comment by nilasini** [comment]
@senthalan could you please update the status of the issue?

**Comment by nilasini** [comment]
While improving device flow please consider https://github.com/wso2/product-is/issues/13214

**Comment by ShanikaWickramasinghe** [comment]
@senthalan @nilasini Are these improvements are done and available in the latest released 5.12.0 Alpha 18 pack. Can you pls confirm ?

**Comment by senthalan** [comment]
The UI and other core improvements are available in the beta, We have identified some performance improvements, that will be added to the product with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1832
