### ISSUE TITLE
Getting a Unnecessary checkbox when updating a Service Provider Config

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13212]
**Describe the issue:**
Service Provider update success popup has a unnecessary checkbox
**How to reproduce:**
1. Register a service provider with oauth openid connect protocol
2. Navigate to Edit view to update the grant type
3. Untick a grant type and click on update

**Actual behavior:**

In the update success popup there is a unnecessary checkbox. You can click on that. Once click on that it gets filled with blue color. Attaching a video 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
5.11.0 Alpha 14
H2/Deafult

![1](https://user-images.githubusercontent.com/31848014/157189237-5cf9278f-0a16-4802-ba1e-e0b9abf339cf.png)

https://user-images.githubusercontent.com/31848014/157189073-9500c891-ee7a-4b71-a23e-fe888181c766.mp4

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
