### ISSUE TITLE
Duplicate Content in the API response when trying to obtain a access token with Device Flow using a expired device code

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13214]
**How to reproduce:**

1. Follow https://github.com/wso2/docs-is/blob/master/en%2Fdocs%2Flearn%2Ftry-device-flow.md
2. Obtain a user code with the API
3. Access the verification uri https://localhost:9443/authenticationendpoint/device.do
4. Enter a valid code in the user code pop up and authorize
5. Set up playground app as the sample app and try to obtain an access token using the device flow grant by passing a expired device code

`curl --location --request POST 'https://localhost:9443/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:device_code' \
--data-urlencode 'client_id=nNsuCn0CZztxTTl2KTXpluxCbmMa' \
--data-urlencode 'device_code=64bd7ab1-e129-4fe4-8cac-8618847389ea'`

**Actual Behaviour**

Duplicate content as **expired_token** for both the parameters in the response. Better to make the parameter values not duplicated

![Screenshot from 2022-03-08 15-33-24](https://user-images.githubusercontent.com/31848014/157214875-02148478-4c59-4562-b1f1-1c9a5a0a1948.png)

**Comment by senthalan** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1832
