### ISSUE TITLE
Changing the super admin password not getting affected

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#13215]
**Describe the issue:**
In a fresh setup, once we change the admin password through deployment.toml file and start the pack, couldn't able to login with the new password

**How to reproduce:**
1. Change admin password through deployment.toml file
2. Start the pack
3. Try to login to management console with new password

**Expected behavior:**
Admin user should be able to logged in with new password.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

**Comment by omindu** [comment]
If the admin user is already provisioned. You cannot change the password for the existing admin. That is the expected behavior.

**Comment by nilasini** [comment]
@omindu I have tried with fresh setup, haven't started the server at least one. In that case it should work right?

**Comment by omindu** [comment]
hmm, that means the admin user gets provisioned when the pack is getting created. Can you check the behavior in an older product ?

**Comment by asha15** [comment]
I have updated the admin’s password from deployment.toml and checked in JDBC userstore and it worked.

In the embedded LDAP we have ‘admin:admin’ as the default configuration. Therefore the admin user is already there during the first startup and the password cannot be changed for the already available user from deployment.toml file. However we can change the password if we use a different username for the admin in the embedded ldap.
