### ISSUE TITLE
Invalid error if same request_uri is used

### ISSUE THREAD

**Issue by hasithakn** [wso2/product-is#13218]
**Describe the issue:**
This issue is to track below case,

- If we try to use the same request_uri multiple times, we are getting an error with **invalid_request_object** but as specified in [1] we should get an error mentioning **invalid_request_uri** error. 

```
Sample URL fragment that we get:
#error_description=Invalid+request+URI&error=invalid_request_object
```
[1] https://datatracker.ietf.org/doc/html/rfc9101#section-7

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
