### ISSUE TITLE
Document sameSite attribute support in adaptive setCookie function

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#13222]
**Is your suggestion related to a missing or misleading document? Please describe.**

In adaptive scripts, when setting a cookie using the `setCookie` function, now developer can set the `sameSite` attribute of the cookie. This needs to be added to the documentation in [1]. 

[1] https://is.docs.wso2.com/en/latest/references/adaptive-authentication-js-api-reference/#setcookieresponse-name-value-properties

**Comment by rksk** [comment]
The document should include the accepted values, because it does not accept `None`, but `NONE`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
