### ISSUE TITLE
401 error when trying to access tenant qualified /identity/saml/slo endpoint

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#13224]
**Describe the issue:**
401 error when trying to access tenant qualified /identity/saml/slo url.

**How to reproduce:**
Try to access the tenant qualified /identity/saml/slo endpoint. eg - https://localhost:9443/t/app2.com/identity/saml/slo?SAMLRequest=tZLLasMwEEV%2FxWjvh2THcUViMA0FQ5qUpHTRTZElJRXYkquRIf372s6jaRbZdSfNXN05c9EMWFOTli7N3nRuI786Cc47NLUGemzNUWc1NQwUUM0aCdRxui2el5QEEW2tcYabGnmL%2FqHSzCmj5%2BjTuRZoGLK2JQE3DX1Ikjh0l3uohNROue9wGBJCbZBXLubog4usSrMkrSYpjjFLJe4P0yQTYjrFqeC9DKCTpQbHtJsjEhHiR7EfPbzihJKMTkgQZ9E78lbGrfXaFjsn7a0ujn91G8lgQL63ZT2mQzuQFnlv0sK4ZN9B%2BWxMiY5U9jq4%2B44Meq8hK%2BQ9Gdswd18%2BVJTwd6OUHqNDeSleiloxeDR6p%2FadlaJoWzwLr5HOgKveoVz8CyAO8C1gw1RdCGElAMqZaJQ%2BUx05TlQt3faKfkiphTzkklRcVLLyK55wP2E88SuSCZ9NSJViggnfkZPPzctL9c8%2Fzn8A&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=SxP4IdK9EJTVJf%2FzyfJOgN7pDLmDyPMVrSci9SwmaIT87D9b2PVrcd1dx5p61oBP3wZ6f6VJCQMbMZULzVonzHeximYzkp%2FdwAdn6MrgvqMMFhkYA6ivaAG3QBE72IbLjKkFlDVNT1YfL1H%2BmDkWtUcMKlb05QH1olwZoY%2BAIyn9laCSgSXfZV%2FbhGJeJByGAFuc3XODaaQKBGWRXsSRYhBBXPVt5pVXSsv%2F9QxLUf9DEOL3IAoK4OAQjgOzNi500YKN9A5mXUvPulQi2WHnQ487%2FYp9m%2BmHOjYzT5G3wWppbZzN6Z9i2dCL355KKE%2FPi8rsS%2Fzj%2FeAlVkdW9Jajyg%3D%3D

**Expected behavior:**
Tenant qualified  /identity/saml/slo url should be accessible if the fedetated logout requests are for a tenant in this scenario[1]

**Suggested fix:**
In the identity.xml.j2 file change the following line 
```
        <Resource context="/identity/saml/slo(.*)" secured="false" http-method="all"/>
```
to 
```
        <Resource context="(.*)/identity/saml/slo(.*)" secured="false" http-method="all"/>
```
Note: Even if there is an error thrown, this endpoint returns 401(its a separate issue).

**Environment information** **:**
 - Product Version: [IS 5.10.0]

[1]https://is.docs.wso2.com/en/latest/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**Comment by Yasara-Y** [comment]
This issue had already been fixed in public master with [1]

[1] [https://github.com/wso2/carbon-identity-framework/pull/2920/files#diff-1ece24b053d1b4af23eb3fdd3af75e2f8816c34a5685ece650c7882061dff696R1895](https://github.com/wso2/carbon-identity-framework/pull/2920/files#diff-1ece24b053d1b4af23eb3fdd3af75e2f8816c34a5685ece650c7882061dff696R1895)
