### ISSUE TITLE
[Migration][Doc] regex pattern validation for user claim input values

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#13228]
As stated in [1], BE regex pattern validation for user claim input values has been added when adding and updating user claim values. To support backward compatibility new configuration `enable_user_claim_input_regex_validation` also has been introduced. 

By default, this configuration is **enabled** and all the claim input values (except for the **mobile number** and **date of birth** claims - there are two specific default regex patterns defined for those two claims) will be validated against the **default regex pattern**  to exclude the special characters from the user claim input values.

- default regex pattern for mobile number claim : ^\\d{4}-\\d{2}-\\d{2}$
- default regex pattern for date of birth claim : ^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})?[-. )]*(\\d{3})?[-. ]*(\\d{4,6})(?: *x(\\d+))?\\s*$
- default regex pattern for all the other claims : [^<>\`"]+

If this regex pattern validation for user claims needs to be disabled following configuration needs to be added to `deployment.toml` file.  

```
[identity_mgt]
enable_user_claim_input_regex_validation = false
```

By adding the above configuration validation for the regex pattern in all the claims will be disabled.

If specific user claims need to be validated against different regex patterns, first it's needed to enable user claims input regex validation (can be done by removing the above configuration or setting its value to `true`) and then should configure specific regex patterns through user claim configuration. 

[1] - [wso2/product-is#13174](https://github.com/wso2/product-is/issues/13174)

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
