### ISSUE TITLE
[TypingDNA Integration] MFA options set by adaptive authentication script are skipped and no errors are thrown if TypingDNA is not setup correctly

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13223]
**Describe the issue:**
$RCS below

**How to reproduce:**
1. Setup MFA in an SP and add an adaptive script to use TypingDNA to conditionally enable 2nd step verification
> tested with basic auth for 1st step and TOTP for 2nd step

3. Disable TypingDNA from the IdP
> eg. go to `Identity Providers -> Resident -> Other settings -> TypingDNA Configuration` and uncheck `Enable TypingDNA`

4. Try logging in to the SP with different credential input patterns 
5. Verify how the validations work by analysing the log entries

**Actual behavior:**
- When the TypingDNA-based adaptive authentication script is added yet TypingDNA is disabled from the IdP, the second-factor (TOTP) was never prompted

**Expected behavior:**
- Better if the 2nd factor is prompted if TypingDNA related setup is not working/configured properly or communication fails

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 Alpha 14
 - OS: Windows 10
 - Database: MSSQL 2019
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
@deshalw could you please explain more on the first step and second step authenticators seems the description is confusing. Once place it is mentioned as "TypingDNA to check the 2nd step" and in other place it is mentioned as "the second-factor (TOTP) was never prompted".

**Comment by deshalw** [comment]
@nilasini - Updated the issue description to make the steps more clear. Please do let me know if any further info is required.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
