### ISSUE TITLE
When a user attempt to signin with a wrong attempt for myaccount with a multi attribute UI error doesnt get disappear during his next login attempt

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13229]
**Describe the issue:**
As per $

**How to reproduce:**
1. Configure Multi Attribute login with [1]
2. Access myaccount login URL 
3. Set Mobile number as the multi attribute claim to login
4. Set the mobile number value in super admins user profile
5. In myaccount login enter a wrong mobile number and click on login
6. There will be a error message in the UI
7. Try login credentials again. The error message prompted in the UI will not get disappear.

**Actual behavior:**
When theres a wrong attempt for signin for myaccount the error prompted in the UI will not get disappear from the UI when user tries another round to login

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 H2/Default
IS 5.11.0 alpha 14

![1](https://user-images.githubusercontent.com/31848014/157606446-e039f62a-6f86-4260-8f79-fdb294a5f614.png)

https://user-images.githubusercontent.com/31848014/157606482-a6409da0-1223-416d-9acc-92b34cc6d802.mp4

---

[1]. https://is.docs.wso2.com/en/5.12.0/learn/multi-attribute-login/

**Comment by ShanikaWickramasinghe** [comment]
This behavior is available when following the same steps with username as the login attribute too

**Comment by savindi7** [comment]
Keeping the error message when the user re-attempts to enter the login credentials should be the default behaviour. Making the message dissapear might confuse the user as if the error is not valid anymore. The same behaviour is also observed in login portals like Gmail (https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&flowEntry=ServiceLogin).
