### ISSUE TITLE
User's current Session will not get terminate when the multi attribute set as the login identifier is updated from myaccount

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13239]
**How to reproduce:**
Scenario
1. Enable Multi attribute login in super tenant flow for claim http://wso2.org/claims/mobile
2. Set mobile number in the user profile
3. Login to console as super admin providing the mobile number set in user profile
4. SSO to myaccount
5. Update the mobile number (login identifier)
6. Comeback to console tab and refresh
7. Still you will be logged in the console app

Scenario 2

1. Enable Multi attribute login in super tenant flow for claim http://wso2.org/claims/mobile
2. Set mobile number in the user profile
3. Login to console as super admin providing the mobile number set in user profile using firefox browser
4. Login to myaccount from chrome browser
5. Update the mobile number (login identifier) from chrome 
6. Comeback to console app opened in firefox and refresh the page
0713344556

**Actual Behavior**
Even though you have changed the login identifier still you can do any operation from your previously logged in session. Isn't it required to logout the users from their current sessions by taking their consent when the attribute set as the login identifier is updated.

https://user-images.githubusercontent.com/31848014/157819250-161d40df-b449-417a-8d8a-93df4a154175.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 15
Primary US - unique id ldap
H2 Default

**Comment by piraveena** [comment]
It is not a frequest operation. So we don't need to revoke the tokens or sessions
