### ISSUE TITLE
Myaccount and Console Apps keeps on loading after updating the callback URLs to a different offset 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13233]
**How to reproduce:**
1. Get IS 5.12.0 alpha 15 pack and up the server with 9444 port by setting a offset in deployment.toml (offset = 1)
2. Down the server
3. Remove the offset = 1 to in the deployment.toml
4. Up the server again
5. Try to access my account or console will get a error message as registered callback url in invalid
6. Then login to management console and try to update service providers console and myaccounts callback url to port 9443 as its not updated by default ( which should happen automatically when you offset the port but not happening)
7. Will get a error as cannot update the SP due to a permission issue
8. So down server and add below config to deployment.toml make the 2 apps editable

`[system_applications]
read_only_apps = []`
9. Then log back to management console and update the callback urls for myaccount and console to port 9443
10. Try to access myaccount or console from browser

**Actual Behavior**
Can access management console but after these steps myaccount and console keeps on loading and doesnt get loaded

https://user-images.githubusercontent.com/31848014/157638003-ff1a7894-4cbf-4092-a917-bf6b55ff4ea8.mp4

![Screenshot from 2022-03-10 15-55-33](https://user-images.githubusercontent.com/31848014/157642555-60466465-d69f-4041-98b4-8f6f7ec33ad8.png)

**Env**
IS 5.12.0 alpha 15

**Comment by Maliesha** [comment]
To load the myaccount and console properly, we also need to change the `Identity Provider Entity ID` in Identity Provider Entity ID on Main -> Identity Providers -> Resident -> Inbound Authentication Configuration -> OAuth2/OpenID Connect Configuration to port 9443.

Identity Provider Entity ID: https://localhost:9443/oauth2/token

That configuration is mentioned in the blog [1] as well.

[1] https://medium.com/identity-beyond-borders/fix-invalid-id-token-issue-in-wso2-identity-server-5-11-0-6bd9f7dc5db6

**Comment by ShanikaWickramasinghe** [comment]
@Maliesha Don't these configurations needs to get updated automatically in the relevant places when you do a port offset?
 If its not happening at the moment or we dont have a plan to fix it better to include all the places that a user needs to update in the wso2 docs as a blog is not a official document that a user might refer.

**Comment by Maliesha** [comment]
@ShanikaWickramasinghe It is not good due to the reason mentioned in the StackOverflow comment [1].

[1] https://stackoverflow.com/questions/65353663/myaccount-and-console-apps-in-wso2is-5-11-0-are-not-working-when-the-server-star/65354774#65354774

**Comment by robsoncombr** [comment]
How to fix this in 7+?
