### ISSUE TITLE
When assigning a group for a customer user via console 2 check boxes displayed even for the headings

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13240]
**How to reproduce:**
1. Login to console as super admin
2. Go to Manage > Users
3. Try to register a customer user
4. In Group assigning phase getting a UI as below. There a unnecessary checkbox is available for the the titles as well. When click on the group to be assigned 2 check-boxes are getting displayed
![a](https://user-images.githubusercontent.com/31848014/157835108-053c332b-9311-4ea0-869b-5c628bd669fa.png)

![Screenshot from 2022-03-11 14-31-09](https://user-images.githubusercontent.com/31848014/157835718-06b31638-46e9-4a39-8230-1cdd7c6121b1.png)

https://user-images.githubusercontent.com/31848014/157835156-d655ac3c-1100-44bc-8ef4-ffba5fddc44d.mp4

**Env**
IS 5.12.0 alpha 15
H2/Default

**Comment by piraveena** [comment]
That check box is used to select all the users or all the combinations.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
