### ISSUE TITLE
Formatting issue in "Configuring the Tenant Loading Policy"

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#13244]
In doc [1] the following sentence;
```
When a tenant receives a request, the particular tenant and all tenant-specific artifacts, except web applications and **axis2

Tenants (including the tenant-specific artifacts) are unloaded from memory if the tenant remains idle for a specified amount of time. 
```

should be corrected as given below:
When a tenant receives a request, the particular tenant and all tenant-specific artifacts, except **web applications** and **axis2 tenants** (including the tenant-specific artifacts) are **unloaded** from memory if the tenant remains idle for a specified amount of time. 

This should be fixed in all applicable doc versions (already fixed in the new restructure content). 

[1] https://is.docs.wso2.com/en/latest/administer/configuring-the-tenant-loading-policy/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
