### ISSUE TITLE
SAML bearer is not working with travellocity app

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#13256]
**Describe the issue:**
With latest IS version saml bearer is not working with travelocity app. We have to fix it.

**Expected behavior:**
SAML bearer should work with travelocity application without any issue.

**Comment by piraveena** [comment]
Could not reproduce this issue.
<img width="1115" alt="Screen Shot 2022-03-16 at 11 23 53 AM" src="https://user-images.githubusercontent.com/17597293/158525581-9456662b-e992-4fc0-b0ad-74ddf63c3eed.png">
