### ISSUE TITLE
Support for OIDC hybrid flow

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#1325]
**Description:**
As per fapi read-write API security profile spec[1],it requires to initiate the authorization flow as a hybrid flow.Check 3) step of 5.2.2 section in [1].Additionally this specification describes having the authorization flow for financial APIs will avoid the attacks of IdP Mix-up attacks[8.3.3],Authorization Response parameter injection attacks[8.4.3].
[1] http://openid.net/specs/openid-financial-api-part-2.html

**Suggested Labels:**
Type/Improvement, Severity/Major, Priority/High, Affected/5.3.0, Component/OIDC

**Suggested Assignees:**
@isharak @madurangasiriwardena @mefarazath 

**Affected Product Version:**
5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by emswbandara** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/commit/cd64dfa61f4065cdb800bc8ed6e0026c811801dc
