### ISSUE TITLE
The UI error popup given when listing users from a unavailable secondary userstore needs to be improved

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13257]
**How to reproduce:**
1. Register a secondory userstore in super tenant mode. (unique id jdbc userstore)
2. Add some users for the created userstore
3. Navigate to users from the management console
4. Down or make the registered secondory userstore unavailable (if its a docker you can down the docker)
5. List the users from userstore domain

**Actual behavior:**
Getting a error as **Error while listing users. Error: Error occurred while retrieving users for filter : % &amp; max Item limit : 100**

**Expected behavior**
The error message given implies like user listing is failing due to a max count problem. But its not the actual case. Better to give a valid reason in the error message for the user

![Screenshot from 2022-03-15 16-12-20](https://user-images.githubusercontent.com/31848014/158360652-722cebe6-6731-4b20-930f-1f4fceb27937.png)

Observed this issue in both tenant and super tenant modes. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 H2/Default
secondory userstore added with postgres 14 
IS 5.12.0 alpha 15

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
