### ISSUE TITLE
[Self-Registration] User is authenticated but not directed to the app landing page after self-registration complete

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13254]
**Describe the issue:**
It is expected to allow the user to auto-login to the app after clicking the link from the email in self-registration flow (ref: #10603)
However, when the user clicks the link, he is taken to the sign-in page. When the app link (eg. MyAccount) is accessed in the same browser after that, it appears the user have been authenticated, even though not directed to the app landing page)

**How to reproduce:**
1. Enable user self-registration from the console
2. Go to MyAccount login page, self-register a new user, wait for the email confirmation
3. Click the confirmation link in the email to complete registration Click the 'OK' button in the confirmation pop-up

**Expected behavior:**
- User should be authenticated and directed to the app landing page upon accessing the link and confirming

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 Alpha 15
 - OS: Windows 10
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by deshalw** [comment]
Screen capture:

https://user-images.githubusercontent.com/37894306/158317566-b2d39043-dfb9-4822-8b0f-b55aa6679d55.mp4

**Comment by piraveena** [comment]
If the autologin feature is enabled, User will be auto logged in to the app's **access URL** if the accessURL is configured as sp property. If the app does not have any access URL configure, then the issue mentioned here will occur.

Following flows also uses auto login.
- [ ] Self registration with verification
- [ ] Self registration without verification
- [ ] Password recovery

Need to cover this improvement in all the above places
