### ISSUE TITLE
"kid" JWT header parameter shouldn't be a hard coded value

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#1326]
**Description:**
"kid" value shouldn't be hard coded in implementation level (ex: DefaultIDTokenBuilder, JwksEndpoint). "kid" value should be generated based on certificate "thumbprint".

Mail thread: "[Dev] [IS] Usage of "kid" JWT header parameter"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by darshanasbg** [comment]
Tracking this issue through: https://wso2.org/jira/browse/IDENTITY-6311

Hence closing this issue
