### ISSUE TITLE
Getting a Error as Error occured while retrieving profile details when login to myaccount as a user in LDAP Userstore when multi attribute login is enabled

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13264]
**How to reproduce:**
1. Configure a secondary IS as a readwrite ldap userstore by setting the port offset for 1 with secondory IS pack. port 9444
2. Register it as a unique id readwrite LDAP in the primary IS
3. Login to the secondory IS and add a user and set a mobile number in the users profile
4. Login to primary IS and enable multiattribute login for mobile claim
5. Access myaccount with primary IS (https://localhost:9443/myaccount)
6. Login with the user credentails of the user registered in the secondory LDAP (mobile : password)

**Actual behavior:**

Getting a Error as **Error occurred while retrieving profile details** when login to myaccount
User profile details cannot be viewed from myaccount

![Screenshot from 2022-03-16 12-09-35](https://user-images.githubusercontent.com/31848014/158532636-80e3c0e4-3a61-4a85-a320-a51ad7ac2db5.png)

![Screenshot from 2022-03-16 12-10-59](https://user-images.githubusercontent.com/31848014/158532705-aa067953-5ca2-4307-bfd6-a755cfa302c4.png)

https://user-images.githubusercontent.com/31848014/158532728-7dfb6be1-fe77-4319-9160-d71dd1e24535.mp4

![Screenshot from 2022-03-16 15-49-03](https://user-images.githubusercontent.com/31848014/158568555-ac2b2289-a82f-4dee-86e8-77e213b23e2b.png)
![Screenshot from 2022-03-16 15-49-19](https://user-images.githubusercontent.com/31848014/158568577-dc1fa324-f524-477f-8441-fdb45020d859.png)
![Screenshot from 2022-03-16 15-49-26](https://user-images.githubusercontent.com/31848014/158568600-58faf400-761d-4958-9046-2befcc89ea42.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 H2/ Default
IS 5.12.0 alpha 15
Secondory Userstore Unique ID read write LDAP

**Comment by AnuradhaSK** [comment]
This issue is not reproducible in wso2is-5.12.0-alpha17-SNAPSHOT
Check the video.
Tested secondary userstore user login and primary userstore user login using mobile number. 

https://user-images.githubusercontent.com/25483865/159634666-0f3e9107-aad9-4347-aecd-2f1cb108eb03.mp4
