### ISSUE TITLE
Permission added to a service provider is not getting deleted.

### ISSUE THREAD

**Issue by rprudhvi9** [wso2/product-is#13263]
**Describe the issue:**
I have created service provider and added permission called roles and updated the service provider. After updating when i try to remove it from the service provider it's not deleting from the permission 

**How to reproduce:**
add permission to any service provider and try deleting it

**Expected behavior:**
Once it's added in permission when ever that permission is not required that should be removed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0
 - OS: ubuntu 20.4
 - Database: MySql
 - Userstore: AD

---

### Optional Fields

**Related issues:**

**Suggested labels:**

![image](https://user-images.githubusercontent.com/101692826/158524218-a3a37a63-e9f5-42d2-9c98-71baec0f0b61.png)

**Comment by hwupathum** [comment]
The error can be reproduced by 
1. Add one or more roles into a service provider and save it
2. Then delete all the roles and save again
3. None of the roles will be deleted
But if you do not delete all the roles, it will work correctly

**Comment by hwupathum** [comment]
I debugged the code and found that the issue occurs in line 4011 in ApplicationDAOImpl  in wos2.carbon.identity.application.mgt in identity-framework repo [https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java](url)
