### ISSUE TITLE
Password update successful notification gets overlapped in the Myaccount Login Page 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13278]
**How to reproduce:**
1. Enable multi attribute login for mobile claim
2. Update the regex for the mobile claim and set a value in the user profile for mobile matching for the updated claim
3. Enable password recovery
4. Access myaccount try to recover pw
5. Access the email received to recover pw
6. Update the pw 

![1](https://user-images.githubusercontent.com/31848014/159152226-e317c8d6-728b-4ee4-b651-6a52f83f0936.png)

https://user-images.githubusercontent.com/31848014/159152174-ab611ac9-58ce-46f1-a3f0-2293a1e93223.mp4

6a09-0eb1-46c5-aab4-cb7f2a2e6268.png)

**Actual behavior:**
You will end up in below page. Where updated successful notification is overlapped in the login page

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 16
H2/defaut

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
