### ISSUE TITLE
[OIDC]Support for a request object endpoint

### ISSUE THREAD

**Issue by lalaji** [wso2/product-is#1327]
**Description:**
As per the FAPI spec http://openid.net/specs/openid-financial-api-part-2.html#introduction-3,the requirement for this endpoint is as below.

In an OIDC flow,the client may not want to send the request object by value, either because it is too large, or because it contains sensitive data and the client doesn't want to encrypt the request object. In such cases it is possible to send the request object by reference using a request_uri.The request URI can be hosted by the client or by the authorization server. The advantage of the authorization server hosting the request object is that it doesn't have to support outbound requests to a client specified request URI nor rely on the entropy of the URI for the confidentiality of the request object.

**Suggested Labels:**
Type/New Feature, Severity/Major, Priority/High, Affected/5.3.0, Component/OIDC

**Suggested Assignees:**
@isharak @madurangasiriwardena @mefarazath

**Affected Product Version:**
5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by emswbandara** [comment]
Documentation: https://docs.wso2.com/pages/viewpage.action?pageId=80727736
