### ISSUE TITLE
Doc Feedback: Link Not Working

### ISSUE THREAD

**Issue by AmilaJ** [wso2/product-is#13288]
Location : https://is.docs.wso2.com/en/latest/compliance/electronic-identification-authentication-and-trust-services-regulation/

![image](https://user-images.githubusercontent.com/20240312/159258462-a4442bf4-c812-4476-b977-ce2fbb4bec01.png)

Link [eIDAS SAML Attribute Profile Support via WSO2 Identity Server](https://is.docs.wso2.com/en/latest/eidas-saml-attribute-profile-support-via-wso2-identity-server) Not working.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
