### ISSUE TITLE
OIDC Session Extending API doesnt output a Body in the API Response 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13286]
**How to reproduce:**
1. Setup playground app
2. Obtain ID Token using authorization grant type
3. Decode the ID token and obtain value for **isk**
4. Try out the below API as super admin 

```
curl --location --request GET 'https://localhost:9443/identity/extend-session?idpSessionKey=bb279c0da71249ad1d5679e05668067f5792d00bc488d97e2942c1377b4ad5d0' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```
**Actual Behavior**
Currently getting only the status code as 200

**Expected behavior:**
There should be a response body for the API response

![Screenshot from 2022-03-21 13-01-53](https://user-images.githubusercontent.com/31848014/159220373-f71cbc06-eb4f-4372-bb27-ae02965f8420.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 16

**Comment by piraveena** [comment]
Now we don't return anything in the API response. We return status code as 200 OK. We can additionally add some improvements to the response, like how long the session extended or expiry time. But we can track this for future.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
