### ISSUE TITLE
Gets automatically logged out from the pickup dispatch sample app when third party cookies blocked 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13299]
**How to reproduce:**
1. Setup pickup dispatch sample and deploy the war in tomcat
2. Set configs in dispatch.properties as below by enabling oidc session management

```
consumerKey=hwNrgH4ur_UOvPql_oafZ9d1Ylca
consumerSecret=6QQeakzq4D81ZfQb8TORf7TZFL8a

callBackUrl=http://localhost:8080/pickup-dispatch/oauth2client
scope=openid internal_application_mgt_view
authzGrantType=code

enableOIDCSessionManagement=true
enableOIDCBackchannelLogout=false
authzEndpoint=https://localhost:9443/oauth2/authorize
OIDC_LOGOUT_ENDPOINT=https://localhost:9443/oidc/logout
sessionIFrameEndpoint=https://localhost:9443/oidc/checksession
tokenEndpoint=https://localhost:9443/oauth2/token
claimManagementEndpoint=https://localhost:9443/services/ClaimMetadataManagementService

post_logout_redirect_uri=http://localhost:8080/pickup-dispatch/oauth2client
api_endpoint=http://localhost:39090/bookings

adminUsername=admin
adminPassword=admin
```

3. Register a OIDC SP with callback url http://localhost:8080/pickup-dispatch/oauth2client
4. Replace the client id and secret in the dispatch.properties file
5. Block third party cookies from chrome browser settings

![Screenshot from 2022-03-22 23-14-48](https://user-images.githubusercontent.com/31848014/159543062-63ce00ad-d2af-47bc-8fa5-793460e11581.png)

6. Access http://localhost:8080/pickup-dispatch/oauth2client
7. Login as admin:admin

Note - my IS and sample app both were on localhost and not on different domains

**Expected behavior:**
Should not get logout from the sample unless you click logout

**Actual Behavior**
After you login for the sample you will automatically gets logged out from the sample. Such a logout will not happen when the config is set as below 

```
enableOIDCSessionManagement=false
OIDCBackchannelLogout=true
```

Is this the expected behavior can't we use this sample with the config as enableOIDCSessionManagement=true
Usually if the IS and sample apps are on different domains then you need to go with enableOIDCBackchannelLogout=true. If not enableOIDCSessionManagement=true needs to work without any issues. You should not get logged out automatically

https://user-images.githubusercontent.com/31848014/159544229-9af0db1a-2235-42ce-b8e4-11d6c470828e.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 16
chrome 99

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
