### ISSUE TITLE
Cache doesn't work when using JWT Access Token

### ISSUE THREAD

**Issue by maron546** [wso2/product-is#13297]
**Describe the issue:**
We have a distribuited deployment that applies the deployment pattern 2 with the WSO2 Identity Server as Key Manager.
Each JWT token request generates a new one.

Is this related to the improvements listed in issue [5755](https://github.com/wso2/product-is/issues/5755)?
We also tried to apply the following [cache layers](https://is.docs.wso2.com/en/5.10.0/setup/configuring-cache-layers/#configuring-cache-layers):
- cache.oauth_cache
- cache.jwks_cache

but the behaviour didn't change.

**How to reproduce:**

1. Create a new Service Provider or an Application (through Developer Portal), with token type set to JWT.
2. Request for an access token, calling directly the Identity Server or via the Gateway.
3. Request for another access token.
4. The two tokens are different, even if  only in signature section.

**Expected behavior:**
Subsequent requests should return the same token as for opaque ones.

**Environment information**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: Oracle

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
