### ISSUE TITLE
Python SDK - Certificate error

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#13293]
**Describe the issue:**
The following error is shown when trying to run the python SDK :
```certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))```

I have tried adding the certificate of localhost manually to the cert directory, but this issue is still reproducible.

**How to reproduce:**
Prerequisite: Create a service provider on the management console
1. Download the Sample SDK
2. Create a virtual Python environment
3. Install the dependencies
4. Update the conf.py file
5. Run the python app

**Expected behavior:**
The SDK should run without any errors

**Environment information**
 - IS 5.12.0 - alpha 14

**Comment by ShanikaWickramasinghe** [comment]
@Sathiyakugan Can you have a look on this

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
