### ISSUE TITLE
Pickup dispatch sample app when logout option given as no it navigates back to samples login page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13298]
**How to reproduce:**
1. Set up pickup dispatch sample and deploy the war in tomcat
2. Register a oidc service provider with callback url http://localhost:8080/pickup-dispatch/oauth2client
3. Add the client id and secret to dispatch.properties file
4. Access http://localhost:8080/pickup-dispatch/oauth2client
5. Login as admin:admin or with a multi attribute login (mobile)
6. Click on Logout
7. From the popup to confirm logout select No

**Expected behavior:**
You should be landed back to home page

**Actual behavior**
You will get navigated back to login page

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 16

https://user-images.githubusercontent.com/31848014/159537854-3190fc32-a75f-40ba-aadf-2a049c73572e.mp4

**Comment by piraveena** [comment]
@ShanikaWickramasinghe , when the app initiates logout request, the app session gets invalidated. When the user denies the consent for logout, only the IdP session will not be terminated. so the user will be redirected to the post-logout-redirect-uri back. so this is expected.
