### ISSUE TITLE
Not support some valid  URL encoding character for URL in admin console

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#1329]
**Description:**
Like '%' are not allowed to put with the ACS URL.
Have to check each place where we do this validation.

**Suggested Labels:**
Type/Bug, Severity/Major, Priority/High, Affected/5.3.0, Component/OAuth

Suggested Assignees:

**Affected Product Version:**
5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
We can't have % char in ACS URL.

**Related Issues:**

**Comment by malithie** [comment]
We can validate only the pattern and accept. Then at the time of use as a URL/URI the value should be properly encoded

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
