### ISSUE TITLE
Behaviour change in Request Object Passed by value Flow

### ISSUE THREAD

**Issue by Maliesha** [wso2/product-is#13301]
With the fix [wso2-extensions/identity-inbound-auth-oauth#1623](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1623), the request object passed by value flow has changed. 

Previous behaviour (In 5.11.0 and older versions):
When we use `openid` as the scope, it returned the claims in the id token which we marked as essential:true under id_token in the request object payload.

New behaviour (In 5.12.0):
When we use `openid` as the scope, it won't return any claims in the id token which we marked as essential:true under id_token in the request object payload. 
To return the claims in the id token, we need to add those claims in a separate custom oidc scope and give that custom scope in the `scope` parameter in the API call.

Explanation:
With the change [wso2-extensions/identity-inbound-auth-oauth#1623](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1623), we are not returning any claims for openid scope.

**Comment by piraveena** [comment]
We don't send any claims in `openid ` scope in the default OIDC authentication flow in IS 5.12.0. We need to document that too. @Thisara-Welmilla

**Comment by Thisara-Welmilla** [comment]
Document migration issue: 
https://github.com/wso2/product-is/issues/12034

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
