### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rpalmarin** [wso2/product-is#13305]
Hi, in this page : https://is.docs.wso2.com/en/latest/develop/writing-a-custom-local-authenticator/
 the link https://is.docs.wso2.com/en/latest/assets/attachments/org.wso2.custom.authenticator.local.zip
 at paragraph number 4 is broken.

the right link is:
https://github.com/soasecurity/wso2/tree/master/authenticators/org.soasecurity.wso2.custom.authenticator.local

thanks
Roberto

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
