### ISSUE TITLE
Getting 400 for Me Endpoint with Error "Error occured while retrieving profile data" when login to Myaccount as a User in LDAP Secondory Userstore

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13306]
**How to reproduce:**
1. Port offset a pack with 9444 and register it as a secondary readwrite ldap in a primary IS 
2. Login to 9444 management console and register a user and assign role secondory/admin
3. Access myaccount with https://localhost:9443/myaccount
4. When login to myaccount getting error as below and user profile doesnt get loaded properly
5. In network tab observed theres a 400 going for Me endpoint

![Screenshot from 2022-03-23 13-50-36](https://user-images.githubusercontent.com/31848014/159655694-9f0bc150-59f9-484e-8897-7334cae6f6cd.png)

![Screenshot from 2022-03-23 13-52-57](https://user-images.githubusercontent.com/31848014/159655170-1cbb8293-7937-4999-83d1-e533afcc1923.png)
![Screenshot from 2022-03-23 13-53-18](https://user-images.githubusercontent.com/31848014/159655188-3a52f99f-2346-49e9-be91-07220409f5c1.png)

https://user-images.githubusercontent.com/31848014/159655342-7a86a7b6-49a6-484e-a7ba-186d722c458c.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 16

**Comment by nilasini** [comment]
Related issue https://github.com/wso2/product-is/issues/12965

**Comment by piraveena** [comment]
Unique ID support for groups is not implemented for ReadWrite LDAP yet. At the moment IS does not support retrieving existing groups of a ReadWrite LDAP user store through SCIM support. This feature needs to be implemented to plug any ReadWrite LDAP user store with groups with or without group-id.

Related Issues:
https://github.com/wso2/product-is/issues/7912
https://github.com/wso2/product-is/issues/7913

**Comment by piraveena** [comment]
We are not planning to support uniqueID feature for readwrite LDAP and JDBC userstore. THis PR https://github.com/wso2/carbon-kernel/pull/3251 will throw exception only if groupd id is not found for a userstore if uniqueID for group feature is enabled
