### ISSUE TITLE
Cache is not invalidated and previously issued authorization codes/acces tokens not getting invlaidated, when oauth app requested/subject claim get updated 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#1331]
**Description:**
Oauth Cache is not invalidated when oauth app requested/subject claim get updated, ID token is retrieved with previously configured claims
Previously issued authorization codes/access token also not getting invalidated when updating an oauth app.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
5.4.0 latest snapshot version

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by IndunilRathnayake** [comment]
Check the revocation of tokens and invalidation of cache in [1]
[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L89

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
