### ISSUE TITLE
Document required to new feature federated OIDC back channel logout 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13315]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently  document available for the new feature federated OIDC back channel logout  for Management Console and required to have same with Console. 
  

**Describe the improvement**
Required to have a document for the new feature federated OIDC back channel logout  for Console configuration
https://is.docs.wso2.com/en/5.12.0/learn/configuring-oidc-federated-idp-initiated-logout/

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed: https://is.docs.wso2.com/en/latest/guides/login/oidc-federated-idp-initiated-logout/
