### ISSUE TITLE
Cannot update User Attributes Include user domain,org name, mapped local subject fields of an Application with postgres 14

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13318]
**How to reproduce:**
1. Configure postgres 14 as the primary database

```
[user_store]
type = "database_unique_id"

[database.identity_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/alpha16db1"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/alpha16db1"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false
```

3. Login to Console (chrome 99)
4. Create a application > Mobile Application
5. Go to Attributes tab
6. Try to check the below check boxes and update

**Actual behavior:**
These fields are not getting updated even though you get a message as successfully updated

https://user-images.githubusercontent.com/31848014/159871856-53385df2-afb8-4b32-9693-f91e6e75854c.mp4

![1](https://user-images.githubusercontent.com/31848014/159871893-299d1968-ecc5-4446-a6cf-1b0b3a95a699.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 16
postgres 14

**Comment by nilasini** [comment]
Could able to reproduce with default h2 setup as well

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2948
