### ISSUE TITLE
Enable OIDC Backchannel Logout check box doesn't  exist in Console. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13313]
**Describe the issue:**
Enable OIDC Backchannel Logout check box doesn't  exist in Console.  This is exist on Management console. 

Console
<img width="609" alt="image" src="https://user-images.githubusercontent.com/39077751/159827008-55cfd95a-db06-4faa-885d-81a4bdcf0c4c.png">

Management Console.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/39077751/159827237-6d84748a-c852-4bd0-a677-dbc7414d545a.png">

**How to reproduce:**
1. Login to console and create OIDC application
2. Navigate to the Protocol section  try to enable the OIDC Backchannel Logout 

**Expected behavior:**
Enable button should be available. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] IS 5.12.0 alpha 16
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
We don't need that config to enable that flow. Adding the Back-channel logout URI is enough to enable the Back-channel logout.
