### ISSUE TITLE
Dynamically generated Governance Connector UIs have bad UX

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#13328]
**Issue**
Currently in product-is, the governance connectors are dynamically generated. 

- The input fields are displayed in the UI and values for those fields are required even though  the options are disabled.

**Suggessted  improvement**

- Create static governance connectors 
- Hide the input fields when the option is disable

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
