### ISSUE TITLE
Incorrect "kid" format mentioned in the  JWKS endpoint document

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#13329]
**Is your suggestion related to a missing or misleading document? Please describe.**

The kid parameter returned by the JWKS is a unique identifier that identifies the key being used. Its purpose is to signal a change of key.

Since the RFC states - "The structure of the "kid" value is unspecified"[1], the calculation/format of the kid is up to the authorization server, and in the identity server, the kid parameter would include the SHA-256 thumbprint of the certificate along with the algorithm appended.
```
"kid": "<SHA-256 thumbprint of the certificate>" + "_RS256",
```

The kid format mentioned in the  JWKS endpoint document[1] is incorrect and should be corrected.

[1]https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.4
[2]https://is.docs.wso2.com/en/5.10.0/learn/json-web-key-set-endpoint/#!

**Comment by nilminiwso2** [comment]
Closing as PRs are merged.
