### ISSUE TITLE
Changing the PRIMARY domain causes SCIM failures

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#13325]
**Describe the issue:**
The PRIMARY domain name can be changed, by adding the configuration below in deployment.toml file.
```
[user_store.properties]
DomainName = "TEST.COM"
```
However, regardless of the domain configured, the domain name will be taken as PRIMARY at [`getFilteredDomainName ()`](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.1/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L1000) when `enable_filtering_enhancements` or `filter_users_and_groups_from_primary_domain` is enabled.
```
[scim2]
enable_filtering_enhancements = true

[scim2]
filter_users_and_groups_from_primary_domain = true
```
This worked fine for SCIM requests regardless of the invalid domain. However, with [carbon-kernel/pull/2860](https://github.com/wso2/carbon-kernel/pull/2860), this has broken and the SCIM requests are failing with filtering parameters.

**How to reproduce:**
1. Change the PRIMARY domain and add any of the above configurations.
2. Invoke the SCIM request below in the latest update level of IS 5.10 (tested: 5.10.0.127).
    ```
    https://localhost:9443/scim2/Users?filter=username+eq+admin
    ```
3. It'll return with the status code: 500 with the response below.
    ```
    {
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Error while filtering the users for filter with attribute name: urn:ietf:params:scim:schemas:core:2.0:User:userName , filter operation: eq and attribute value: PRIMARY/admin. ",
    "status": "500"
    }
    ```

**Environment information**
 - Product Version: IS 5.10.0

**Comment by ShanChathusanda93** [comment]
Closing the issue since the public fix is done.
