### ISSUE TITLE
ERROR {org.wso2.carbon.user.core.internal.Activator} - Cannot start User Manager Core bundle org.wso2.carbon.user.core.UserStoreException: Cannot initialize the realm.

### ISSUE THREAD

**Issue by ghost** [wso2/product-is#13331]
**Describe the issue:**
New Install:
- Everything works out-of-box with H2 database
- Ubuntu 20.04 LTS
- wso2is-5.12.0-alpha18-SNAPSHOT.zip

**How to reproduce:**
Change two sections of deployment.toml as per: https://is.docs.wso2.com/en/latest/setup/changing-to-postgresql/

First Change:
[database.identity_db] (docs say url to localhost - but it is a JDBC connection?)
type = "postgre"
url = "jdbc:postgresql://127.0.0.1:5432/wso2_identity_db"
name = "wso2_identity_db" (shouldn't need but doesn't make a difference)
username = "xxxx"
password = "xxxx"
port = "5432"  (shouldn't need but doesn't make a difference)

Second Change
[database.shared_db] (docs say url to localhost - but it is a JDBC connection?)
type = "postgre"
url = "jdbc:postgresql://127.0.0.1:5432/wso2_shared_db"
name = "wso2_identity_db" (shouldn't need but doesn't make a difference)
username = "xxxx"
password = "xxxx"
port = "5432"  (shouldn't need but doesn't make a difference)

Note:
Changed [user_store] to type = "database_unique_id" - makes no difference.

**Expected behavior:**
Browse to https://localhost:9443 and watch it roar!

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-5.12.0-alpha18-SNAPSHOT
 - OS: Ubuntu 20.04 LTS
 - Database: Postgresql 12.9
 - Userstore: Both LDAP and JDBC seem exhibit same behavior

I understand that it is an alpha release...

**Comment by icjohnson** [comment]
Note:
I get the exact same behavior with: --branch=v5.11.0 and Ubuntu 20.04 LTS :(

**Comment by nilasini** [comment]
@icjohnson Could you please share the entire stack trace?

**Comment by matheusmatos221** [comment]
I'm having the same issue using APIM...

**Comment by matheusmatos221** [comment]
> I'm having the same issue using APIM...

I solve my problem on API Manager 4.1.0 on Docker using Ubuntu 20.04 LTS image.
Probably your problem solution will be similar.

You need check your JDBC url, user and password and host.
Check if you can connect on Database using DBeaver or PGadmin.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
