### ISSUE TITLE
Userinfo endpoint returns multi-valued parameters in a comma separated string

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#13339]
**Is your suggestion related to an experience ? Please describe.**
* In the id_token the multi-valued params are represented in an array like the below payload.
`{
  "at_hash": "47vILi6YOGCpkXPcQjaTUQ",
  "aud": "IGAehGzf90ueH0co6PSLATKK9fsa",
  "sub": "alex",
  "nbf": 1648443081,
  "azp": "IGAehGzf90ueH0co6PSLATKK9fsa",
  "amr": [
    "password"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "groups": [
    "finance-team",
    "Internal/everyone",
    "superuser"
  ],
  "exp": 1648446681,
  "given_name": "Alex",
  "iat": 1648443081,
  "email": "alex@gmail.com"
}`

* Let's take the `groups` as an example. If we check the `/userinfo` response it is like the following.
`{
    "sub": "alex",
    "groups": "finance-team,Internal/everyone,superuser",
    "given_name": "Alex",
    "email": "alex@gmail.com"
}`
Same `groups` param is returned as a comma separated JSON string.

* But as per the OIDC specification's[1] `5.3.2.  Successful UserInfo Response` section, 
> `the UserInfo Endpoint MUST return the JSON Serialization of the UserInfo Response as in [Section 13.3](https://openid.net/specs/openid-connect-core-1_0.html#JSONSerialization) in the HTTP response body`

* In the same spec[1], `13.3.  JSON Serialization` mentioned the following,
> `A parameter MAY have a JSON object or a JSON array as its value.`
As per the spec we can use the JSON array to the params which contains multi values rather having a comma separated JSON String.

Some OIDC supporting vendors may accept the multi-valued parameters as a JSON array. Faced a similar issue when configuring the ELK stack with IS 5.11.0. From the ELK side they request the `groups` param to be an array because it is a multi-valued param.

[1] https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse

**Describe the improvement**
* Move JSON String to JSON array for the multi-valued paramters

**Comment by piraveena** [comment]
@ShanChathusanda93 We have already fixed this in the master https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1637 and the fix should be availabe in the latest pack. Did you try this in the latest pack? 

The same issue is tracked here https://github.com/wso2/product-is/issues/6575 and fixed in the most of the IS versions

**Comment by ShanChathusanda93** [comment]
@piraveena thanks for the update. The fix is available for 5.11.0 as well. Since this was done to keep the backward compatible, shall we update the relevant docs with the config changes and so on? We can add the details here[1].

[1] https://is.docs.wso2.com/en/latest/learn/basic-client-profile-with-playground/

**Comment by piraveena** [comment]
@ShanChathusanda93 Docs and Migration doc issues are tracked here https://github.com/wso2/product-is/issues/12126.

**Comment by ShanChathusanda93** [comment]
@piraveena thanks for the update. Closing the issue since this is fixed.
