### ISSUE TITLE
Documentation - WSO2CARBON_DB does not need to be preserved between restarts

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#13332]
It is not explained anywhere in the documentation that WSO2CARBON_DB does not need to be preserved between restarts.

See https://github.com/wso2/product-is/issues/12721 for details of the problem.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
