### ISSUE TITLE
Resident IDP configurations are not getting updated in a cluster setup and cannot access myaccount and console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13338]
**How to reproduce:**
1. Set up a cluster setup
2. Try to access console, myaccount

**Expected behavior:**
Can access management console in the setup but cannot access console and myaccount

Cause for the problem is certain configurations are not getting updated in the resident IDP to suit with the changed host name 

![Screenshot from 2022-03-25 17-51-41](https://user-images.githubusercontent.com/31848014/160331240-a815d34d-e90a-4f74-8910-1c33214a862e.png)

IDP Entity ID value was updated as https://iscluster.qa.com:443/oauth2/token
When manually changes this value by removing port could access myaccount and console. This value needs to be updated automatically correctly

```
[server]
hostname = "iscluster.qa.com"
node_ip = "127.0.0.1"
```
cluster common name =  iscluster.qa.com ( in nginx cert)

**Comment by nilasini** [comment]
@ShanikaWickramasinghe Is there any stack trace while accessing console/myaccount?

**Comment by ShanikaWickramasinghe** [comment]
@nilasini There were no backend errors. when inspect the browser network logs there was a 404 as below .
![Screenshot from 2022-03-28 13-16-57](https://user-images.githubusercontent.com/31848014/160350985-97fd62f7-7c7c-429b-b9f2-72733058fcca.png)

https://user-images.githubusercontent.com/31848014/160351097-bd2e9ae6-9e6c-4438-a5f2-0275d42d32a7.mp4

IDP Entity ID value was updated as [https://iscluster.qa.com:443/oauth2/token](https://iscluster.qa.com/oauth2/token)
When manually changed this value by removing port could access myaccount and console. This value needs to be updated automatically correctly. There are some other configurations as well in the same section which shows with port 443 value as attached in issue description

**Comment by piraveena** [comment]
In older IS versions also, we have this behavior. We can change the idtoken issue ID by changing the `<IDTokenIssuerID>` config. Or we need to manually change the config from the UI.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
