### ISSUE TITLE
UI is not prompting for user consent when a new scope is added in the authorisation request in the "Approve_Always" flow

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#13334]
**Describe the issue:**
UI is not prompting for user consent when a new scope is added in the authorisation request in the "Approve_Always" flow

**How to reproduce:**
1. Initiate an authorisation request to user portal application passing a custom scope.
2. Select Approve Always option at the login.
3. Log out from the application.
4. Initiate a authorisation request again passing a new scope.
5. At the login it does not appear consent option to pass the consent for the new scope.

**Expected behavior:**
UI should prompt the consent to newly added scope.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0]

**Comment by lashinijay** [comment]
Public fix

-  [https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1548](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1548)
- [https://github.com/wso2/carbon-identity-framework/pull/3390](https://github.com/wso2/carbon-identity-framework/pull/3390)
- [https://github.com/wso2/carbon-identity-framework/pull/3394](https://github.com/wso2/carbon-identity-framework/pull/3394)
