### ISSUE TITLE
Claim added as an array in the JWT token when the claim value is with a comma at the end - "claimValue,"

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#13335]
**Describe the issue:**
Claim added as an array in the JWT token when the claim value is with a comma at the end - "claimValue,"

**How to reproduce:**
- Create a user and add a claim value with a comma at the end directly from the database. (It is not possible to add a claim value with a comma at the end through the UI, the claim would be added with the comma at the end removed).
- Or add it from the /services/RemoteUserStoreManagerService, setUserClaimValues operation.
- Create an OAuth service provider and add the claim as a requested claim.
- Login to the service provider and get check the ID token.
- The claim value would be included in the ID token as an array eg - 
```
   "Organization": [
      "claimValue"
   ],
```

**Expected behavior:**
Claims having value with just the comma at the end should not be treated as multi-valued. This is already been done in the claim addition flow from the UI and the SCIM2 APIs, however, if someone has directly changed the claim value from the database layer or through the SOAP APIs.
In the SAML flow, this works as expected because the claim value, after being split from the multi-attribute separator(default comma) is trimmed and length is checked before adding to the assertion[1], however, in the OIDC flow it is considered as an array[2].

[1]https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/builders/assertion/DefaultSAMLAssertionBuilder.java#L358
[2]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultOIDCClaimsCallbackHandler.java#L706

**Environment information** **:**
 - Product Version: [IS 5.10.0, 5.11.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
