### ISSUE TITLE
Document issues in Configuring OIDC Federated IdP Initiated Logout

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13333]
**Is your suggestion related to a missing or misleading document? Please describe.**
Document [1] required following updates,
[1]https://is.docs.wso2.com/en/5.12.0/learn/configuring-oidc-federated-idp-initiated-logout/

- [ ]  Add following missing section on document, [Configure Pickup Dispatch application in the Primary IS](https://is.docs.wso2.com/en/5.12.0/learn/configuring-oidc-federated-idp-initiated-logout/#configure-pickup-dispatch-application-in-the-primary-is)

Enable OIDC back channel logout and add back channel logout url http://localhost:8080/pickup-dispatch/bclogout

<img width="424" alt="image" src="https://user-images.githubusercontent.com/39077751/160244629-fcf8fe5a-2f8e-41b6-b0b1-31d29068dc78.png">

- [ ] Update in [Try out](https://is.docs.wso2.com/en/5.12.0/learn/configuring-oidc-federated-idp-initiated-logout/#try-it-out) section
In point number 4, It shoudl be correct as the same browser with different tab since this is a SLO scenarios

<img width="718" alt="image" src="https://user-images.githubusercontent.com/39077751/160244713-cc415d63-b958-4511-b45f-1e9d42cc8db1.png">

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed: https://is.docs.wso2.com/en/latest/guides/login/oidc-federated-idp-initiated-logout/
