### ISSUE TITLE
Uniqueness of Home Realm Identifier is not checked

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#13349]
**Describe the issue:**
It is allowed to create multiple identity providers with the same Home Realm Identifier value. But it should not be allowed to create/update an identity provider with a Home Realm Identifier which is used in another identity provider in the same tenant.

**Environment information** 
 - Product Version:  IS 5.11.0
 
 **Related Issues**
https://github.com/wso2/product-is/issues/13347

**Comment by rksk** [comment]
The previous PR had been reverted due to a build failure, https://github.com/wso2/carbon-identity-framework/pull/4280/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
