### ISSUE TITLE
Minor Updates in Docs

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#13341]
**Update the following docs.**
1. Update ```a user claims``` --> ```a user claim```
Doc Location: https://is.docs.wso2.com/en/latest/learn/self-contained-access-tokens/#self-contained-access-tokens
2.  Update ```Rotate refresh token``` --> ```Renew refresh token```
Related Issue: https://github.com/wso2/identity-apps/pull/2787

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
