### ISSUE TITLE
Disable domain name restriction

### ISSUE THREAD

**Issue by emilebui** [wso2/product-is#13348]
**Is your feature request related to a problem? Please describe.**
Currently, when adding a new tenant. The tenant name must be a domain and it must have an extension (E.g: .com, .org)

![wso2_feature_request](https://user-images.githubusercontent.com/33470772/160533979-e7d2712c-8da8-4553-8c0c-5a6cae6a493c.png)

Is there any settings that disable this restriction and let tenant name whatever user want to be? (For example: instead of "wso2.org", it could be "wso2" only)

**Describe the solution you would prefer**
There should be a config in `deployment.toml` to disable this restriction

**Comment by nilasini** [comment]
Already config is available 
```
[multi_tenancy.stratos]
public_cloud_setup=false
```
