### ISSUE TITLE
Suggesting to replace consumer key as client id in error prompts prompted during authenticating with JS SDK

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13355]
**How to reproduce:**
1. Set up a javascript SDK by downloading sample from https://github.com/asgardeo/asgardeo-auth-spa-sdk/releases/latest/download/asgardeo-html-js-app.zip and folloing guide https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit#
2. Up the sample
3. Replace the client id of the index.html with a invalid value ( which doesnt match with the registered SPA client id)
4. Access https://localhost:5000
5. Will get below UI error

Here as we are using the term client id in the index.html of the JS SDK (sample) and in all the other UIs related to JS > SPA in console and management console better to update the error message as client id without using the term consumer key

![a](https://user-images.githubusercontent.com/31848014/160580793-d176c3c7-b7dc-41ff-b865-edee7631752c.png)
![a](https://user-images.githubusercontent.com/31848014/160581325-bfd331b2-4133-4769-94fc-d15af9853fa4.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
