### ISSUE TITLE
WorkflowManagementServiceImpl class need two separate methods to add and update workflows.

### ISSUE THREAD

**Issue by IsharaSilva** [wso2/product-is#13354]
**Is your suggestion related to an experience ? Please describe.**

In WorkflowManagementServiceImpl class, both the add and update workflows are done through a single method called addWorkflow.

**Describe the improvement**

We should have two separate methods to add & update workflows.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
