### ISSUE TITLE
Helper text for the Enter Application field of Role Mappings section not fully visible in the UI for a SPA 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13352]
**How to reproduce:**
1. Register a SPA wth console
2. Go to User Attributes tab > Role Mappings section
3. Enter a Application helper text is not visible fully. Some letters has been cut off from the UI

![a](https://user-images.githubusercontent.com/31848014/160556491-b905da2a-58e9-487e-8f64-c5898acda2c9.png)

**Environment**
IS 5.12.0 alpha 17

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
