### ISSUE TITLE
In user account creation, the provided username is added as the last name in the profile

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#13368]
**Describe the issue:**
Refer - https://is.docs.wso2.com/en/latest/learn/configuring-user-name-recovery
When we create a user ***[from Identity > Users and Roles > Add]*** we provide a username (e.g. Alex). Then it will also be added as the last name of the user profile. But not even as the first name.

**How to reproduce:**
Shouldn't it be better if the username is not added as the first name instead of the last name.

**Expected behavior:**
Username is not added as the last name. Instead, provide a better solution.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - OS: [Linux]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**
N/A

**Suggested labels:**

**Comment by nilasini** [comment]
This will happen only for LDAP user store. SN is mandator and if it was not specified, usual practice is to use uid attribute for the lastname.
