### ISSUE TITLE
Missing step in the SDK documentation about config Public Client and user cannot authenticate using React SDK without it

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13363]
**How to reproduce:**
1. Follow the guide section **Try out a sample React SDK on Identity Server** and configure it with IS 5.12.0 alpha17 pack in https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit#
2. Access https://localhost:5000/

```
src/config.json

{
    "clientID": "tE3LOZJmfiVPbQ197Mvw9byx7n8a",
    "serverOrigin": "https://localhost:9443",
    "signInRedirectURL": "https://localhost:5000",
    "signOutRedirectURL": "https://localhost:5000",
    "scope": ["openid", "profile"]
}
```

**Actual behavior:**

Getting 2 windows to input login credentials for the user to login for the sample app

https://user-images.githubusercontent.com/31848014/160795750-07a6a2af-a77b-460d-946b-4553f29e5b91.mp4

![Screenshot from 2022-03-30 14-41-41](https://user-images.githubusercontent.com/31848014/160796205-a78ce1df-a1ab-4a00-a1df-2f6ea2ef6fe7.png)

![Screenshot from 2022-03-30 14-41-47](https://user-images.githubusercontent.com/31848014/160796235-c4be97a5-162e-4b49-ba97-a0dcb869ad58.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha17
postgres 14

**Comment by ShanikaWickramasinghe** [comment]
Needs to enable following config to authenticate successfully. Hence closing the issue

**Management console**

 Allow authentication without the client secret

![Screenshot from 2022-03-30 15-24-06](https://user-images.githubusercontent.com/31848014/160804879-5bf596b7-36b8-44df-81ec-5b4d6f948819.png)


**Console**

Public Client
![Screenshot from 2022-03-30 15-23-54](https://user-images.githubusercontent.com/31848014/160804840-1f2047a7-a9d8-46cd-a13b-d366aa4c72b9.png)

**Comment by ShanikaWickramasinghe** [comment]
As there is a chance that a fresh user might not no about this shall we include this as a note in the SDK documentation. @divyaamunugama Hence reopening the issue as a doc issue.

**Comment by divyaamunugama** [comment]
@ShanikaWickramasinghe will update docs with a note. Thank you
