### ISSUE TITLE
Selectively revoke tokens on role change

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#13361]
**Is your suggestion related to an experience ? Please describe.**
When a role gets updated or deleted, Currently we are revoking all the tokens of all the users who have that role. Rather revoking all the tokens, we should revoke only the set of tokens that were issued with that privilege of the role.

For an example, admin user has **admin** role and a *test* role (this does not have any permissions). If the test role gets updated or deleted, we are revoking all the tokens of the admin user. But when we revoke the tokens of a role, we should check the permissions associated and associated scopes. And we should revoke the tokens issued only with the associated scopes.

**Related Issue**
(https://github.com/wso2/product-is/issues/12957)

**Additional context**

**Comment by piraveena** [comment]
**Current behavior in IS 5.12.0**

**Deletion of roles**
- Tokens are revoked when deleting roles 
- Here we are revoking all the tokens of all the users who have that deleted roles from https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOauthEventHandler.java#L115. 
- This is done by listening to PRE_DELETE_ROLE_EVENT which is triggered by RoleManagementService in the framework.

**Deletion of groups**  - Need to be fixed
- Tokens are not revoked when deleting groups 
- Deleting a group will delete only the group. It will not remove the associated role or assigned a user to the role. Since removing the group does not impact the roles, the tokens are not revoked. 
- For group deletion time, we don't trigger PRE_DELETE_ROLE_EVENT. but we trigger PRE_DELETE_ROLE event https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.governance/src/main/java/org/wso2/carbon/identity/governance/listener/IdentityMgtEventListener.java#L522. 
- But from oauth side, we don't have any implementation for that PRE_DELETE_ROLE event
 
**Updating roles/groups**

**Removing users from roles**

- Tokens are revoked when updating roles by removing users (Go to Roles > Remove an existing user)
- Related to [Selectively revoke tokens on role change #13361](https://github.com/wso2/product-is/issues/13361). 
- We are revoking all the tokens of the user who have got removed from that role. https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOathEventListener.java#L221
- Instead of revoking all tokens, we should selectively revoke the tokens of based on the permissions. Roles -> Permissions ->Scopes ->Tokens
 
**Removing users from groups**
- Tokens are revoked when updating groups by removing the assigned users(current issue) (Go to Groups > Remove an existing user). 
- When we update a group, SCIMUsermanager calls userstore manager's updateUserListOfRoleWithID https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.6.7/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3532.
- This triggers event listeners related to role update and call doPostUpdateUserListOfRole method https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.7.137/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOathEventListener.java#L221 and revoke the respective tokens issued for the user
when removing users from groups, users will still have the roles assigned. https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOathEventListener.java#L221

**Updating permissions of roles**
Tokens are revoked when updating roles by changing permissions (Adding or removing permission revokes the tokens of the users who are assigned with the role) (go to roles > change permissions)





Related Git Issues
https://github.com/wso2/product-is/issues/13486
https://github.com/wso2/product-is/issues/13361
https://github.com/wso2/product-is/issues/12957

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
