### ISSUE TITLE
Getting Landed to a Authentication Error page when you select No for Logout Consent Prompt with React SDK

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13366]
**How to reproduce:**
1. Configure React SDK with IS 5.12.0 alpaha 17 pack by following the guide section **Try out a sample React SDK on Identity Server** in https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit#heading=h.y5d6rc170m0s
2. From management console enable config allow authenticate without client secret or public client config from console ( otherwise authentication will fail)
3. Access https://localhost:5000/
4. Login as admin:admin for the sample
5. Click Logout
6. From the prompt for are you sure to Logout select No
7. You will be redirected to Login page
8. Click again on Login will end up in a authentication error page

https://user-images.githubusercontent.com/31848014/160809207-401dab0f-7045-4f23-9222-52db3d44eeff.mp4

![Screenshot from 2022-03-30 15-43-03](https://user-images.githubusercontent.com/31848014/160809230-a8fb34be-a05a-47f3-b10b-da2cf7c8f003.png)

**Expected behavior:**

When you give No as Are you sure to Logout prompt you should not get navigated back to login page
Also once you click again on Login Button should not end up in a authentication error page

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 17
postgres 14

**Comment by Avarjana** [comment]
This has been addressed with the new developments in [React SDK sample app](https://github.com/asgardeo/asgardeo-auth-react-sdk/blob/main/samples/asgardeo-react-app/src/components/LogoutRequestDenied.tsx). Check the screenshot below,

![Screenshot 2022-08-02 at 10 27 33](https://user-images.githubusercontent.com/27714968/182343890-c1ff42a1-6204-4e0d-989c-98038f2f757a.png)
