### ISSUE TITLE
Navigating to a Something went wrong page when try user Lock Feature from Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13379]
**How to reproduce:**
1. Access Console
2. Create a user with Console
3. Try to Lock the user account 

**Expected behavior:**

Directing to a Something went Wrong Page

![Screenshot from 2022-04-01 10-59-56](https://user-images.githubusercontent.com/31848014/161200819-eb52fbc1-9745-41f8-a7db-24f47ffa3c19.png)

https://user-images.githubusercontent.com/31848014/161200092-edfd806a-ee41-468d-ad01-9211283e7291.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
5.12.0 Alpha 18
H2/Default

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2922
