### ISSUE TITLE
Login to Google using WSO2 Identity Server - Invalid ACS URL

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#13375]
https://is.docs.wso2.com/en/latest/learn/logging-in-to-workday-using-the-identity-server/

In the given document the Google ACS URL should be changed to https://www.google.com/a/{Google domain}/acs

**Comment by deshankoswatte** [comment]
@GDRDABARERA,

I think the documentation link should be https://is.docs.wso2.com/en/latest/learn/logging-in-to-google-using-the-identity-server/ instead of https://is.docs.wso2.com/en/latest/learn/logging-in-to-workday-using-the-identity-server/.
