### ISSUE TITLE
Refreshing Identity Providers page loads Applications

### ISSUE THREAD

**Issue by minolih** [wso2/product-is#13373]
**Describe the issue:**
A page refresh from Identity Providers page loads the Applications page in Product IS Console. 

**How to reproduce:**
1. Navigate to Identity Providers in Console.
2. Refresh page.

**Expected behavior:**
Identity Providers page should reload after refresh. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0 Alpha 17
 - OS: Ubuntu 20.04

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
