### ISSUE TITLE
Doc Issues - Blue-Green Data Encryption Key Rotation

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13380]
**Is your suggestion related to a missing or misleading document? Please describe.**

Document link: https://is.docs.wso2.com/en/5.12.0/administer/blue-green-data-encryption-keyrotation/
User guide : https://docs.google.com/document/d/14rWfFLZqfgwSh9qAnwY1hEwX8V-cIQGm-rqH6PIfRP0/edit?usp=sharing

- [ ]  Location refers to the <KEY_ROTATION_REPO>  is corrupted.  https://github.com/wso2/identity-tools/tree/master/components/org.wso2.carbon.identity.keyrotation

<img width="701" alt="Screenshot 2022-04-01 at 11 33 25" src="https://user-images.githubusercontent.com/39077751/161206465-e92abfbe-f4f6-4477-8e53-efd1d2b83c8c.png">

<img width="757" alt="Screenshot 2022-04-01 at 11 43 33" src="https://user-images.githubusercontent.com/39077751/161205601-e6c4850a-46e2-4098-9b37-7e06156b950c.png">

- [ ] Let's break down 3rd point for more clear the configurations. Add path to file properties.yaml and keyrotation.sh. 

<img width="748" alt="Screenshot 2022-04-01 at 11 34 54" src="https://user-images.githubusercontent.com/39077751/161206611-ad301b0a-c0d1-4f1b-9666-e0be74349dc3.png">

- [ ]  Content is not visible once expand these drop downs

<img width="709" alt="Screenshot 2022-04-01 at 11 37 25" src="https://user-images.githubusercontent.com/39077751/161207189-01eb868f-39c1-45ed-8101-03d4b08421c0.png">

- [ ] Shall we add the diagrams explain the process of this feature which available on email thread , Key Rotation Tool Configuration Encryption Keys/Run Time Data Encryption 

- [ ] No link available for the "here" phrases.
-

<img width="683" alt="image" src="https://user-images.githubusercontent.com/39077751/161482249-705d4c8c-1343-4b36-bac0-86fd336980ff.png">
 
 
- [ ] Better to add information regarding Configurations Related to Symmetric Key Encryption(https://is.docs.wso2.com/en/latest/administer/using-symmetric-encryption/#configurations-related-to-symmetric-key-encryption). This will help to update the properties.yaml file in <KEY_ROTATION_TOOL. 

- [ ]  Shall we add more details in verification section
 - "Check log file" --> shall we mention which log files
 -  "7 identity and registry database tables" --> Shall we mention the tables
 - "Check the log files to verify if transformation of the synced data happened successfully for the 4 tables."  --> Shall we mention the which tables are
 
![image](https://user-images.githubusercontent.com/39077751/162150955-bfc92bd7-8cad-4394-a694-8ef1df0b690d.png)

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
