### ISSUE TITLE
Angular SDK Login Page becomes not responsive until 2 Login Button Clicks after you Deny the Consents

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13389]
**How to reproduce:**
1. Set up Angular SDK by following guide in https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit# with 5.12.0 alpha 18 pack
2. Get a incognito browser window (chrome 99)
3. Access https://localhost:5000/
4. Provide credentials admin:admin
5. From the consent approve popup give input as Deny
6. You will be navigated back to Login page
7. Click on Login
8. Nothing will happen
9. Click again on Login
10. You will navigate back to consent page

https://user-images.githubusercontent.com/31848014/161476679-61daa16d-61e0-4a42-b7cb-2737042b1dff.mp4

**Expected behavior:**
If you Deny the consents one time then for the next Login You need to Click the Login Button Twice. There will be a non responding Login Screen during the 1st Login button Click

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 18 default
chrome99

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
