### ISSUE TITLE
[UX] Users screens UI changes

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#1339]
**Description:** 

1. Add New User screen - Should have a guideline about password requirements (should be x number of characters etc). This only appears if there is an error and its not there on the UI itself. 

2. Add New User screen - "Password repeat" field should be renamed to "Confirm Password". 
     -Once this is done, the error message if the "password and password repeat do not match" should 
       be also reworded to "password and confirm password does not match". 
     - This should also be changed in other places like the Change Password screen. 

3. Add New User screen - If you click Next without entering username, password etc the error message is "**Username pattern policy violated**". This can be reworded to "Enter all required fields".

4.  Add New User screen - When a username that is already existing in the system is entered, the error message is "Could not add user PRIMARY/minoli. Error is: UserAlreadyExisting:Username already exists in the system. Pick another username." 

Reword the error message to "Could not add user PRIMARY/minoli. The username already exists in the system. Enter another username". 

5. Search Users screen - This field (Enter user name pattern)  should be in title case and the word 'user name' should be one word. 

6. Change Password screen - "New Password Repeat" field should be renamed to "Confirm New Password". 

7. Change Password screen - When a wrong Current Password is entered, the error message is "Could not change password of admin. Error is: Error while updating password. Wrong old credential provided". This can be reworded to "Could not change the password of admin. The current password you entered is incorrect". 

8. Assign Roles screen - There is a section called "Unassigned Roles". This is empty if there are no unassigned roles. When this is empty, it should have a message saying "No unassigned roles found". 

9. Add new user screen - Step 2 - The main heading should be "Add New User" as it was in step 1. 

**Suggested Labels:**
UX

**Affected Product Version:**
5.4.0

**Comment by Minoli** [comment]
JIRA link - https://wso2.org/jira/browse/IDENTITY-6473

**Comment by sagara-gunathunga** [comment]
We will consider this for new admin portal redesign.
