### ISSUE TITLE
Missing Pre Requisite Steps in the python SDK guide when running Python SDK

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13399]
**How to reproduce:**

Followed Guide https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit# to configure python SDK. Faced some problems due to missing pre requisite steps. We may need to include a section in the docs for the required pre requisite installations.

- [x] Step 2 > a 

Related to this we may need to give some pre requisite steps for the users. to run this command initially you need to have pip installed in the machine. Ubuntu > apt install python3-pip

- [x] Step 2 > c

For this command too we requires a pre requisite step. Got Error as The virtual environment was not created successfully because ensurepip is not
available. On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command. Ubuntu > apt install python3.8-venv

- [x] Getting Error OSError: Could not find a suitable TLS CA certificate bundle, invalid path: samples/flask/cert/wso2.crt

- [x] In doc guide step 4 Update the conf.py file in the flask directory with your client ID and client secret . lets specify the correct full file path as samples/flask/conf.py

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
