### ISSUE TITLE
Issue in pom.xml

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#13392]
**Describe the issue:**

Refer -https://is.docs.wso2.com/en/latest/learn/querying-saml-assertions/#with-your-application
When running the sample application saml-query-profile-target (https://github.com/wso2/samples-is/tree/master/saml-query-profile-target)] an error is generated in the pom.xml file due to  outdated maven versions used in the application.

Product Version: [IS 5.11.0]
OS: [Linux]
Database: [H2]
Userstore: [LDAP]

**Comment by nilasini** [comment]
@asekawa Could you please add more details about the issue? Please add the error logs as well

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
