### ISSUE TITLE
Email OTP configurations not working properly

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#13405]
**Describe the issue:**
Refer - https://is.docs.wso2.com/en/latest/learn/configuring-email-otp/
Even when the user  disable the EMail OTP for Identity Server using following toml configuration, the OTP's are still sent sucesfully.

```
[authentication.authenticator.email_otp]
name ="EmailOTP"
enable=false
```

Moreover, 
![disable-email-otp](https://user-images.githubusercontent.com/40081059/161716971-90846b7b-ffec-4a2a-917b-9f2f42fa607b.png)

 When a user go to the profile and try to disable the Email OTP through the user profile , it shows a text field.
When we provide "true" for that field, t converts to checkbox. And if we provide something else other than "true", it will save it as a string value.

**How to reproduce:**

Debug the issue in the toml configurations related to disabling the Email OTP
Fix the issue in UI , when disabling the email OTP through the user profile.

**Expected behavior:**
The email OTP should not send when disabled through toml configurations.
Better to have a checkbox at the first place , when disabling the Email OTP through the user profile

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0]
 - OS: [Linux, ]
 - Database: [ H2]
 - Userstore: [ LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
