### ISSUE TITLE
Getting ERROR: Failed building wheel for auth-python-sdk when installing auth-python-sdk on Ubuntu 20

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13400]
**How to reproduce:**
1. Follow Guide in https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit# to setup Python SDK on ubuntu 20
2. When doing the step in guide step 3 , 2nd command pip3 install asgardeo-auth-python-sdk Getting below Error in the command prompt logs

![Screenshot from 2022-04-05 11-08-13](https://user-images.githubusercontent.com/31848014/161686348-9d589dcd-e892-40b9-8500-105763be929e.png)

```
ERROR: Command errored out with exit status 1:
   command: /home/shanika/WSO2/5.12.0/SDKs/Python/<>-auth-python-sdk/samples/flask/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b9e_gr0t/asgardeo-auth-python-sdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b9e_gr0t/asgardeo-auth-python-sdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ktdijeap
       cwd: /tmp/pip-install-b9e_gr0t/<as>-auth-python-sdk/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for <as>-auth-python-sdk


```

Attaching screenshots for the other pre requisite steps done
![Screenshot from 2022-04-05 10-53-36](https://user-images.githubusercontent.com/31848014/161686454-a3e418f5-3fda-4ef3-a637-78752c9193cf.png)

![Screenshot from 2022-04-05 10-54-41](https://user-images.githubusercontent.com/31848014/161686478-88c828d9-70a5-4795-ad8e-5c978abc3ccc.png)
![Screenshot from 2022-04-05 10-55-56](https://user-images.githubusercontent.com/31848014/161686498-31350f54-3dc6-484a-acf1-2a868955c162.png)
![Screenshot from 2022-04-05 11-03-00](https://user-images.githubusercontent.com/31848014/161686523-1cd6b556-54ff-4f42-a848-78c549479890.png)

![Screenshot from 2022-04-05 11-03-25](https://user-images.githubusercontent.com/31848014/161686550-50d9be1e-25fd-4a75-a71b-287f7a710008.png)

![Screenshot from 2022-04-05 11-05-02](https://user-images.githubusercontent.com/31848014/161686574-ab5cd7d9-b533-471c-8f13-c203dbe07ed2.png)
![Screenshot from 2022-04-05 11-05-05](https://user-images.githubusercontent.com/31848014/161686602-5a71b670-282a-4f61-998c-2e78ea16683a.png)

@thivi what could be the cause for this issue

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 18
Ubuntu 20

**Comment by ShanikaWickramasinghe** [comment]
After doing a bit of research on the error installed wheel as attached below. After that didnt get the above error. Pls verify whether the attached logs in the screenshots below verify that the issue is now sorted ( As I still couldnt get the sample up n running)

![Screenshot from 2022-04-05 14-38-57](https://user-images.githubusercontent.com/31848014/161720569-561ec1e9-9806-4111-9788-c1ec68d5e5bb.png)

![Screenshot from 2022-04-05 14-39-09](https://user-images.githubusercontent.com/31848014/161720604-dee95050-5baa-4972-a31a-dcd58869d22b.png)

**Comment by thivi** [comment]
I was also able to reproduce this issue but upgrading `pip` with `pip3 install --upgrade pip` resolved the issue in my case.

**Comment by ShanikaWickramasinghe** [comment]
Changing the issue to a doc issue. We may need to include about these dependencies in the docs may be in a troubleshooting section. cc @divyaamunugama

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
