### ISSUE TITLE
Handle migration impacts of changing JWT token signing default behavior

### ISSUE THREAD

**Issue by minolih** [wso2/product-is#13404]
**Describe the issue:**
Need to handle the migration introduced with [1]

[1]https://github.com/wso2/product-is/issues/13402 

With this behavioural change, we have identified the below impact areas. 

1. Customers who use SaaS applications.
Token validation at application level will be unsuccessful for new tokens obtained after the migration.
They can continue their existing behaviour of signing JWT tokens by the user's tenant by changing the configuration value to determine token signer, which will continue to successfully validate their new JWT tokens at application level. 
If they wish to migrate to sign by service provider, migration changes will be required at their application level.
2. Customers who have already obtained a JWT token signed with default behaviour. 
Customers who have already taken a JWT token can also choose to continue their current behaviour by changing the configuration value to determine token signer.
3. Customers who do not use SaaS applications. (No direct impact)
The behavioural change will not have a direct impact on validation as the service provider's tenant and the user's tenant will be the same in non-SaaS service providers. 
But if at application level, the validation has been implemented to use the user's tenant, they can choose to change the signature validation implementation or continue with the previous behaviour by changing the configuration.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
