### ISSUE TITLE
Configuring SMS OTP for Identity Server is not working properly

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#13403]
**Describe the issue:**
> Refer - https://is.docs.wso2.com/en/latest/learn/configuring-sms-otp/#disable-sms-otp
> When we disable the SMS OTP for Identity Server using following toml configuration, it still working.
```
[authentication.authenticator.sms_otp]
name ="SMSOTP"
enable=false
```
> And still go to the following page as well.
> ![Screenshot from 2022-04-05 12-51-09](https://user-images.githubusercontent.com/59449070/161700238-5d4f92af-15b7-4a0d-a930-2bb08737c584.png)

> When a user go to the profile and try to diable the SMS OTP, it shows a text field.
> ![disablesmsotp](https://user-images.githubusercontent.com/59449070/161700914-b68e9c09-06e2-4c2d-abb8-9c00f971c62f.png)
> When we provide "true" for that field, t converts to checkbox. And if we provide something else other than "true", it will save it as a string value.

**How to reproduce:**
> Check toml configuration which I have mentioned previously and do a debug on the issue.
> Check the UI changes for the SMS OTP disable field in the profile

**Expected behavior:**
> When the SMS OTP is disabled from toml configuration it should not work.
> For the profile it should show a check box at first place to disable or enable SMS OTP function 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - OS: [Linux]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

N/A

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
