### ISSUE TITLE
[UX] 'Roles' screens UI Changes

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#1340]
**Description:**
1. Add new role screen - When we leave the role name field empty and click next, the error message is "Entered role name is not conforming to policy. Please enter a role name, which adheres to policy." We can change this to "Enter all required fields". 

2. Add new role screen - Should have a guideline (help text) about role name policy ("cannot contain special characters by default", "should have xx number of characters" etc). 
        -When we enter a special character with the role name, the error message can be given as "The 
         role name you entered does not conform to the policy. Enter a valid role name." 

3. Add role screen - "Step 2: Select permissions to add to Role" should have "role" starting with simple r and should be reworded to "Select permissions to add to **the** role"

4. Assign Users screen - There is a section called "UnAssigned Users". The A in UnAssigned should be a simple letter. Also, this is empty if there are no unassigned users. When this is empty, it should have a message saying "No unassigned users found".

**Suggested Labels:**
UX

**Affected Product Version:**
5.4.0

**Comment by Minoli** [comment]
JIRA Link -  https://wso2.org/jira/browse/IDENTITY-6474

**Comment by sagara-gunathunga** [comment]
We will consider this for new admin portal redesign.
