### ISSUE TITLE
Create Account Button in the self registration page is not aligned in Console and Myaccount

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13417]
**How to reproduce:**
1. Access console as admin:admin
2. Enable self registration (Manage > User On boarding)
3. Enable auto login after self registration ( Mange > Account Management > Account Recovery)
4. Access Console and Myaccount self registration page

**Expected behavior:**
Will get a view as below where create account text is not aligned with the button

![b](https://user-images.githubusercontent.com/31848014/162134769-78978e40-51c3-4912-afdf-6c3df63397c5.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 18

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/12950
