### ISSUE TITLE
It Doesnt allow to enable auto login after self registration from console without filling Minimum number of forced security questions to be answered

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13414]
**How to reproduce:**
1. Access console as admin:admin
2. Go to Manage > Account Recovery
3. Try enabling and disabling the field auto login after self registration
4. Will get a UI error message as Minimum number of forced security questions to be answered a value is required for this field
5. But in configs I haven't enabled Security question based password recovery

When enabling this config UI should not prompt a error message as some other input is required for security questions. 

![a](https://user-images.githubusercontent.com/31848014/162128389-66156efb-c7f6-4fb0-8533-117821504ee3.png)

https://user-images.githubusercontent.com/31848014/162128434-66c9949f-0524-4f80-9007-6ee15f0ad541.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 5.12.0 alpha 18

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/13241
