### ISSUE TITLE
Theres no option to preview the password during a self registration flow in the self register form

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13418]
**How to reproduce:**
1. Access console as admin:admin
2. Enable self registration
3. Try out a self registration flow by accessing console 
4. In the self registration form password entering and confirming fields there is no preview icon to view the entered password. If a user wants to get confirmed what he has entered its unable to preview

![b](https://user-images.githubusercontent.com/31848014/162137933-3963499a-49fc-439a-b5f1-680116efe43a.png)

**Expected behavior:**
There should be a pw preview option

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 18

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
