### ISSUE TITLE
Support PAR Authorization requests without duplicate parameters

### ISSUE THREAD

**Issue by RivinduM** [wso2/product-is#13416]
**Describe the improvement**
As per the PAR specification[1], the PAR authorization request should be able to send only with the request_uri and the client_id. But with the current authorization flow, response_type and scope are mandatory parameters n the auth request.
In order to fix this, it was suggested to provide an extension point to the OAuthAuthzRequest and extend it in the OB side to handle PAR authorize flow. [2]

[1] https://datatracker.ietf.org/doc/html/rfc9126
[2] mail: Clarification of spec compliance for Pushed Authorization Requests (PAR)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
