### ISSUE TITLE
Configuring TOTP Authenticator for Identity Server is not working properly

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#13411]
**Describe the issue:**
> Refer - https://is.docs.wso2.com/en/latest/learn/configuring-totp/#disable-totp
> When we disable the TOTP for Identity Server using following toml configuration, it still working.
```
[authentication.authenticator.totp]
enable=false
```

> **UI Issue** - When a  user does not add a totp configuration for his/her account, the server will ask the user to enable the TOTP authenticator in the authentication flow. 
This can be enable by the following toml configuration.
```
[authentication.authenticator.totp.parameters]
enrolUserInAuthenticationFlow=true
```
> ![totp-ui-issue](https://user-images.githubusercontent.com/59449070/161943793-86fe5c44-23f5-4ab0-a11e-8b3822ba82b0.png)
> As you can see, it shows the "Enable TOTP" message twice.

**How to reproduce:**
> Check toml configuration which I have mentioned previously and do a debug on the issue.
> Check the UI changes for the TOTP authenticator in the authentication flow. 

**Expected behavior:**
> When the TOTP is disabled from toml configuration it should not work.
> The TOTP authenticator in the authentication flow should show the "Enable TOTP" message only once.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - OS: [Linux]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**
N/A

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
