### ISSUE TITLE
[UX] 'Claims' screens UI changes

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#1341]
**Description:**
1. Add Claim Dialect screen - add help text to explain the dialect URI "A unique URI identifying the dialect (for example, http://schema.openid.net/2007/05/claims)."

2. Add Local Claim screen - add help text for all the fields. Use the table in [1] as a guide. 
[1] https://docs.wso2.com/display/IS530/Adding+Claim+Mapping

3. Add Local Claim screen - The required fields have a black star. The star should be red. 

4. The breadcrumbs after clicking "Add Local Claim" or "Add claim dialect" go in this format: 'add.new.claim.dialect'.  The breadcrumb should instead be in this format: "Home>Identity>Claims>Add>Add New Claim Dialect".

5. Add External Claim screen- add help text for all the fields. Use the table in [1] as a guide. 
[1] https://docs.wso2.com/display/IS530/Adding+Claim+Mapping

**Suggested Labels:**
UX
**Affected Product Version:**
5.4.0

**Comment by Minoli** [comment]
JIRA link - https://wso2.org/jira/browse/IDENTITY-6475

**Comment by sagara-gunathunga** [comment]
We will consider this for new admin portal redesign.
