### ISSUE TITLE
Suggestion to remove the term "Information" from the Self Registration Confirmation popups 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13421]
**How to reproduce:**

1. Access console as admin:admin
2. Enable self registration
3. Try out a self registration flow by accessing console
4. When you proceed with self register there will be 2 notifications in the UI with 2 popups as below
5. Here the term Information is not much user friendly. Can we get rid of the term Information and use another suitable phrase there
![e](https://user-images.githubusercontent.com/31848014/162144892-587b1d5b-3650-407e-b68a-bdcd50f1702a.png)

![f](https://user-images.githubusercontent.com/31848014/162144934-031a5cd8-a49a-4e65-a3a4-0f25c258491e.png)

**Environment**
IS 5.12.0 alpha 18
chrome 99

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
