### ISSUE TITLE
UI Error message "Please confirm that you have read privacy policy" doesnt get cleared from UI when you agree on privacy policy

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13420]
**How to reproduce:**

1. Access console as admin:admin
2. Enable self registration
3. Try out a self registration flow by accessing console
4. In the self registration form without checking the box to agree on privacy policy try to self register
5. Will get a UI error message saying that you need to agree on privacy policy
6. Then select the checkbox to agree on privacy policy and keep another mandotory field (first name) as blank and try to self register
7. The UI error message which was given previously related to the privacy policy will remain in the UI and it will not get cleared from the UI when user try to do some other step

![d](https://user-images.githubusercontent.com/31848014/162144299-73d11b90-01ee-4684-ad29-e61898ef44e0.png)

**Environment**
Is 5.12.0 alpha 18
Chrome 99

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
