### ISSUE TITLE
[UX] Common UI changes in mgt console

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#1342]
**Description:**
1. All instances of the word "Uri" and "Url" should be changed to caps - **"URI"** and **"URL"**

2. Most error messages say "Error is: <and then description of the error>". Better not to put the "Error is:" part. For example "Could not add user PRIMARY/minoli. **Error is:** UserAlreadyExisting:Username already exists in the system. Please pick another username." 

3. Wherever we have mentioned "Step 1 : xxxx", "Step 2 : xxx", the space between the number and the colon should be removed. So it should be "Step 1: xxx" instead of "Step 1 : xxx". 

4. Wherever we have mentioned "select all on this page" and "unselect all on this page", the links can be shortened to "Select all" and "Unselect all"

**Suggested Labels:**
UX

**Affected Product Version:**
5.4.0

**Comment by Minoli** [comment]
JIRA link - https://wso2.org/jira/browse/IDENTITY-6476

**Comment by sagara-gunathunga** [comment]
We will consider this for new admin portal redesign.
