### ISSUE TITLE
When auto login is not enabled during self registration users should be notified in the UI popup message about access permitted portals

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13422]
**How to reproduce:**

1. Access console as admin:admin
2. Enable self registration from resident IDP
3. Try out a self registration flow by accessing console
4. You will get redirected to console and will get below attached page. Here better to suggest about the myaccount  if the user is not allowed to access console. We can give the user a hint about myaccount that he should access. Here we are not giving any indication for the user which portals he can access if console is denied for him. 

![h](https://user-images.githubusercontent.com/31848014/162146138-c272b01c-ea94-4622-a1fe-18613b6f4241.png)

**Environment**
IS 5.12.0 alpha 18
Chrome99

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
