### ISSUE TITLE
IS 5.11.0 windows installer has some issues 

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#13436]
**Describe the issue:**
- Running the server through start menu or manually through the `wso2server.bat` didn't work. Was able to run it through `wso2server.sh`
![image](https://user-images.githubusercontent.com/7569427/162415867-03a9beee-9edb-422c-bb66-9817122510df.png)

- Wrong enviroment varialble names created
![image](https://user-images.githubusercontent.com/7569427/162415589-4540501d-8513-44a4-b18f-f70acd581184.png)

- Check above belove doesnt work
![image](https://user-images.githubusercontent.com/7569427/162415042-87bc2109-1dc5-4170-aa30-725897db368b.png)

**How to reproduce:**
Download the 5.11.0 latest from here and run https://wso2.com/identity-server/

**Expected behavior:**
Run smoothly without above issues

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Windows 10
- JDK Version: jdk1.8.0_202

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
