### ISSUE TITLE
Search mechanism from management console for Workflow definitions & Workflow engagements 

### ISSUE THREAD

**Issue by lochanaEdirisinghe** [wso2/product-is#13434]
**Is your suggestion related to an experience ? Please describe.**
Search mechanism for Workflow definitions & Workflow engagements from management console should be provided as an improvement.

**Describe the improvement**
In existing product there is no feature to search workflow definitions and engagements from management console like searching service providers with a filter. To achieve this, new methods should be added to WorkflwoManagemetService class, improving DAO classes, generate stub, UI changes and etc. Also this search mechanism should have offset based pagination to navigate the search results.

Furthermore, when you search for some workflow engagements, and if multiple results come, and you enable/disable/delete one of them, it shouldn't re-direct to the home screens again. Rather it should be on the same page.

**Comment by LahiruLS** [comment]
https://github.com/wso2-support/product-is/pull/945

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
