### ISSUE TITLE
Cannot Update the Scope Validators for a SPA with Console 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13449]
**How to reproduce:**
1. Create a SPA
2. Go to Protocol tab
3. Try to update scope validators by checking Role based or xacml based validators
4. It doesn't reflect the updated change

https://user-images.githubusercontent.com/31848014/162699145-51e39f70-c44d-477c-9ecc-f6e366b645e5.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 19

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2951
