### ISSUE TITLE
Duplicate Entries observed in drop downs in Console and Myaccount Applications

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13448]
**How to reproduce:**
1. Access console and myaccount
2. Develop > List console & Myaccount (preview them)
3. Go to Application search operation

![b](https://user-images.githubusercontent.com/31848014/162691390-0aff4799-e8c8-4725-b8c7-30c5d440afd7.png)

4. Go to Provisioning tab of myaccount and console. Observing duplicate entries as attached
![a](https://user-images.githubusercontent.com/31848014/162691518-852f8607-75d3-44d3-91ec-fabf269e62d5.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 19

**Comment by nilasini** [comment]
Please refer the comment [1]

[1] https://github.com/wso2/product-is/issues/13444#issuecomment-1097688493
