### ISSUE TITLE
Console Application protocols section grant types has word references not matching for on prem 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13442]
**How to reproduce:**
1. Access console
2. Develop > Applications > Console (preview)
3. Go to Protocols tab
4. Click on Allowed grant types > Implicit and password
5. Read the hint provided. Hint has refered as Asgardeo. As this is on prem product we may need to change the wordings accordingly
![Screenshot from 2022-04-11 11-14-00](https://user-images.githubusercontent.com/31848014/162672601-e615582f-cc55-41d6-8dd5-95ddd8a2cc58.png)

![Screenshot from 2022-04-11 11-14-03](https://user-images.githubusercontent.com/31848014/162672610-0c14f662-f4a7-4c75-889f-0416b45b89e0.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

Is 5.12.0 alpha 19

**Comment by ShanikaWickramasinghe** [comment]
Observing the same issue in the Myaccount application as well
![Screenshot from 2022-04-11 13-16-57](https://user-images.githubusercontent.com/31848014/162689348-c5064759-ac4f-4f2e-8d3d-ed4937a21b2b.png)

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2956
