### ISSUE TITLE
Edit Role Mappings of a TWA editable field needs to be enabled only for the editable section and no delete confirmation before delete a role mapping

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13458]
**How to reproduce:**
1. Access console and register a traditional web application
2. Go to Attributes > Role Mappings section
3. Add a Role Mapping
4. Try to edit the added role mapping

- [x] When click on edit, edit view will suddenly makes the added local role disappear from the UI. We need to enable edit option only for the enter a application field

- [ ] When deleting a role mapping it will doesnt ask for a confirmation . It will suddenly delete the role when click on the delete icon. Better to have a confirmation

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 19

https://user-images.githubusercontent.com/31848014/162883864-4dc5420f-0e3b-4a0f-90b6-5c2351cb9bcf.mp4

![a](https://user-images.githubusercontent.com/31848014/162883914-fe929c7d-6510-4d42-9bf1-3f555b7dac70.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
