### ISSUE TITLE
Adding integration tests for IS-Analytics 5.8.0

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#13457]
**Is your suggestion related to an experience ? Please describe.**
We don't have integration tests to test server startup flows for IS-analytics 5.8.0, We need to implement that.

**Describe the improvement**

**Additional context**

**Comment by asha15** [comment]
I developed the integration test for analytics profiles to check the server startup. 

please find the PRs related to this issue: 
[1] https://github.com/wso2-support/analytics-is/pull/43
[2] https://github.com/wso2-support/analytics-is/pull/45

**Comment by asha15** [comment]
The issue is fixed in support branch, hence closing the issue.
