### ISSUE TITLE
In application sign in methods Request path authentication options comes as enabled eventhough select start with default configs 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13459]
**How to reproduce:**

1. Access console and register a traditional web application
2. Go to sign in methods
3. Select add totp as a second factor
4. Enable Request path authentication basic oauth and oauth bearer
5. Update
6. Click revert to default
7. Then click on start with default configurations
8. Check the request path authentication section

Even though I started with default configs the 2 options of request path authentication comes as enabled.

https://user-images.githubusercontent.com/31848014/162885401-df1a8e11-bc4d-4dc8-b580-001f139a5081.mp4

![b](https://user-images.githubusercontent.com/31848014/162885445-729441c5-b8cc-4544-bd1a-491090e8d5cd.png)

**Env**

IS 5.12.0 alpha 19

**Comment by brionmario** [comment]
IMO, `Start with Default` is intended to be for the `Authentication Sequence`, we should move `Request Path Authenticators` to somewhere else.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
