### ISSUE TITLE
Getting a Overlapped Attribute View When multiple attributes added via Attributes tab for a SPA

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13451]
**How to reproduce:**
1. Access console
2. Create a SPA
3. Go to Attributes tab
4. Add more than 7 attributes
5. You will get a overlapped view as below

![a](https://user-images.githubusercontent.com/31848014/162701949-d9b518ba-4ea4-4e8e-879b-b8c565629193.png)

https://user-images.githubusercontent.com/31848014/162702657-f1488423-7284-44a5-89d0-4582f3efa6ff.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 19

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2954
