### ISSUE TITLE
Duplicate entries observed in Application outbound provisioning section

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13461]
**How to reproduce:**
1. Access console and create a traditional web app
2. Create Google as a IDP
3. Go to created IDPs outbound provisioning tab and register a new connector (google) and enable it
4. Come back for Traditional web apps provisioning tab
5. Add a new provisioner from outbound provisioning section

observing below duplicate entries in the drop downs

https://user-images.githubusercontent.com/31848014/162917971-d0ba6060-a361-4cc1-9c0b-910ecf821ad7.mp4

![a](https://user-images.githubusercontent.com/31848014/162917719-f391109e-ada7-4b40-bed5-8bc8a37303a0.png)
![b](https://user-images.githubusercontent.com/31848014/162917723-90cde9bc-14bd-4d7c-b6e1-4d79b2021f30.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 Alpha 19

**Comment by nilasini** [comment]
Please refer the comment [1]
[1] https://github.com/wso2/product-is/issues/13444#issuecomment-1097688493
