### ISSUE TITLE
UI Improvements observed in SAML Application protocol section

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13462]
**How to reproduce:**
1. Access console > create a traditional web app with SAML
2. Go to protocols tab

- [ ] Duplicate entries observed in logout section

![Screenshot from 2022-04-12 14-48-49](https://user-images.githubusercontent.com/31848014/162927116-b7e84aa6-305f-4c6d-8a9f-24c699bce009.png)

- [ ] Duplicate entries observed in default assertion consumer url section

![Screenshot from 2022-04-12 14-42-42](https://user-images.githubusercontent.com/31848014/162927202-bed38bb0-3153-4769-95ad-efecea2f5afa.png)

- [ ] Checkboxes are displayed in 2 colurs grey and while. We need to have all the checkboxes colours same in all the places

![a](https://user-images.githubusercontent.com/31848014/162927491-18efab64-c5db-47cb-b008-d3a24ca81e3f.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 19

**Comment by nilasini** [comment]
Regarding the duplication issue please refer the comment [1]. Seems HTTP POST & HTTP redirect check boxes can't be editable hence showing in different color.

[1] https://github.com/wso2/product-is/issues/13444#issuecomment-1097688493
