### ISSUE TITLE
Missing Info related to resending confirmation code in Lite User Registration flow

### ISSUE THREAD

**Issue by Maliesha** [wso2/product-is#13468]
We can use the following curl command to resend the confirmation code in Lite User Registration.
```
curl --location --request POST 'https://localhost:9443/t/carbon.super/api/identity/user/v1.0/resend-code' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "user": {
        "username": "malieshakalutota@gmail.com",
        "realm": "PRIMARY"
    },
    "properties": [
        {
            "key": "RecoveryScenario",
            "value": "LITE_SIGN_UP"
        }
    ]
}'
```

But it's not mentioned in the doc [1].

[1] https://is.docs.wso2.com/en/latest/learn/resending-account-recovery-confirmation-emails/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
