### ISSUE TITLE
Attribute values duplicated in Saml Application

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13479]
**How to reproduce:**
1. Create a SAML SP from console
2. Go to attributes tab and add some attributes
3. Claim values are duplicated as below. same info (http://xxxxxx) available in 2 lines as duplicated

![a](https://user-images.githubusercontent.com/31848014/163759372-7ff844e8-821e-4732-99d5-9248d7b834a4.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 19

**Comment by nilasini** [comment]
Please check the comment https://github.com/wso2/product-is/issues/13444#issuecomment-1097688493

**Comment by ShanikaWickramasinghe** [comment]
@nilasini this is regarding having the same claim url twice in 2 lines (duplicated 2 times) in all the attributes. Not the issue reported in #13444
