### ISSUE TITLE
Change My Account Profile Attributes using userPortal.json

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#13471]
**Is your suggestion related to an experience? Please describe.**
Currently, we cannot change the user profile attributes in My Account using the userPortal.json file. To change the language we need to change the Display Name of the particular claim.

<img width="1336" alt="Screenshot 2022-04-15 at 20 51 45" src="https://user-images.githubusercontent.com/29885846/163589073-3b226a40-be44-44e2-aac3-55407b690638.png">

**Describe the improvement**

Improvement to change the My Account profile attribute names using the userPortal.json file.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
