### ISSUE TITLE
Information on how it works when there are multiple userstores configured

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#13473]
Doc Improvement:

In [1], it discusses general information on user stores, but this document can be improved with how it works when there are multiple user stores.

- How it searches through all the user stores in the tenant
- How the userstore order is set
- What happens to the older if a user store is updated when the server is running
- Also, the new extension point [2] can be mentioned

[1] https://is.docs.wso2.com/en/latest/setup/configuring-user-stores/
[2] https://medium.com/@nilasini/user-store-preference-order-per-service-provider-available-from-5-9-0-onwards-bcd7648a485c

**Comment by UdeshAthukorala** [comment]
Can also use this medium article also for the documentation.

[1] https://anuradha-15.medium.com/how-to-configure-your-preferred-user-stores-to-authenticate-users-for-a-service-provider-in-wso2-cdadf43f9366

**Comment by UdeshAthukorala** [comment]
Hi @divyaamunugama , @himeshsiriwardana ,

Shall we prioritize this. 

Thanks & Regards,
Udesh

**Comment by himeshsiriwardana** [comment]
ack. Will start work on this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
