### ISSUE TITLE
[5.12][5.11]Need to update Java Security Manager Doc

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#13480]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the doc of enabling [Java Security Manager](https://is.docs.wso2.com/en/latest/setup/enabling-java-security-manager/), we provided two sh files to sign Jars using self-sign certificates. But there are some Jars in the product that have already been signed using the Eclipse certificate.
So the following doc will sign those Jars twice. We need to identify and neglect those Jars.

### Error Message
``
Caused by: java.lang.SecurityException: invalid SHA1 signature file digest for org/eclipse/core/internal/content/XMLRootHandler$StopParsingException.class
``

### Optional Fields
Link: https://is.docs.wso2.com/en/latest/setup/enabling-java-security-manager/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
