### ISSUE TITLE
Remove added users for the group will end the user session

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13486]
**Describe the issue:**
Remove added users for the group will end the user session.

https://user-images.githubusercontent.com/39077751/163791859-37d24fba-aeac-41df-82f9-97a10f8a0dbe.mov

**How to reproduce:**
1. Create group and users
2. Navigate to group list and click edit
3. Select user tab and add users
4. Click edit button and remove the user

**Expected behavior:**
Users should be remove from the assigned group and session should not be expired.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12-alpha20
 - OS:  Mac
 - Database:  MSSQL
 -  Userstore:LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
When we update a group, SCIMUsermanager calls userstore manager's `updateUserListOfRoleWithID` https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.6.7/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3532.

This triggers event listeners related to role update and call `doPostUpdateUserListOfRole` method https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.7.137/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOathEventListener.java#L221 and revoke the respective tokens issued for the user

**Comment by piraveena** [comment]
Groups are assigned to roles. there can be groups that don't have roles. Those are exceptional. But if we think for the groups which have some set of roles, then revoking access tokens for the group update is needed. Need to revisit the token revocation logic on group and roles.

Few issues to revisit:
Tokens are not revoked when deleting groups 
Tokens are revoked when deleting roles
Tokens are revoked when updating roles (Related to https://github.com/wso2/product-is/issues/13361)
Tokens are revoked when updating groups (current issue)

**Comment by piraveena** [comment]
**Updating groups**
The expected way to use groups should be, users should be assigned to groups and roles are assigned to groups. Groups are used to denote the collection of users and the roles needs to be assigned to groups.

Groups without any assigned roles is an exceptional edge case.

1. Create user `testUser`
2. Create a role `testRole` and assign some permissions
3. Create a group `testGroup` and assign `testRole` to the group. 
All the users belonging to the `testGroup` will be assigned with `testRole`. If we remove `testUser` from the `testGroup`, the the user's permissions will be revoked. So it is expected to revoke tokens.

**Comment by piraveena** [comment]
Hence closing this issue.
