### ISSUE TITLE
Role Mappings not getting updated in a oauth 2.0 standard based app

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13482]
**How to reproduce:**
1. Create a standard based oauth 2.0 app
2. Go to attributes tab
3. Add a Role mapping
4. Click update
5. Go to a different tab
6. Come back and see 
7. Updated role mappings are not available

https://user-images.githubusercontent.com/31848014/163783722-5ff4317a-754e-46f4-9fa2-45baf4f98afd.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12,0 alpha 19

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2959
