### ISSUE TITLE
When "Using Email Address as the Username" and recovering, validation fails

### ISSUE THREAD

**Issue by mauroedv** [wso2/product-is#13498]
**Describe the issue:**

When "Using Email Address as the Username" is configured and using the [recovery notification API](https://docs.wso2.com/display/IS511/apidocs/account-recovery/#!/operations#Notification#recoverPasswordPost), the validation for the username ([Utils.validateEmailUsername(user.getUsername)](https://github.com/wso2-support/identity-governance/blob/1d3ed5f464d10bc2da364982dd8471db39906139/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/password/NotificationPasswordRecoveryManager.java#L99)) fails in the recovery notification API flow, if the username is not an email.

**How to reproduce:**

Apply the following configuration from the IS official documentation: [Using Email Address as the Username](https://is.docs.wso2.com/en/latest/learn/using-email-address-as-the-username/)

After that, create two users, one with email as username, another one with a regular username.

Then, enable "Notification based password recovery" in the carbon console, in Identity Providers -> Resident Identity Provider -> Account Recovery.

Then, use the [recovery notification API](https://docs.wso2.com/display/IS511/apidocs/account-recovery/#!/operations#Notification#recoverPasswordPost) to start the recovery flow. The user with an email as a username should see no error in the request, but the user with a regular username will have an error response with body:

```
"code": "PWR-10009",
"message": "Bad Request",
"description": "Invalid username! Username should be in email format."
```

**Expected behavior:**

If a user is allowed to input both an email or a regular username, then the recovery flow should be available for both with the API.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11 (tested both vanilla and latest)

**Comment by rksk** [comment]
This has a relation with https://github.com/wso2/product-is/issues/10760
