### ISSUE TITLE
Improvements for Remember Me functionality

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#1349]
**Description:**

Remember me functionality currently has been implemented for following user stores, but it should be available in all the UserStoreManager implementations.
- JDBCUserStoreManager
- ReadOnlyLDAPUserStoreManager

Remember me has to be handled in higher level than user store level and remember me cookies should be stored in database level, not in user store. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-is/issues/1347

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
