### ISSUE TITLE
When Edit Admi user profile and update a country from drop down there will be a cancel icon next to selected name

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13490]
**How to reproduce:**
1. Access console > Manage
2. List Users
3. Edit Default admin user
4. Select a country from the drop down
5. There will be a cross (cancel) icon when you pick a country

Cancel icon should not be there when you pick a country name drop down

![a](https://user-images.githubusercontent.com/31848014/163834760-b2dffb3b-1035-4950-b24c-b236f1550aa2.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
5.12.0 alpha 20

**Comment by Maliesha** [comment]
Country is not a mandatory claim. That means the users should be able to remove that value whenever they want. So that drop-down should be a clearable one. 
In react semantic UI, this is the default behavior of the clearable drop-down icon [1].
[1] https://react.semantic-ui.com/modules/dropdown/
