### ISSUE TITLE
Getting Something went wrong and Retrieval Error when trying to terminate admin user active session

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13502]
**How to reproduce:**
1. Access console
2. List admin user
3. Go to Active sessions tab
4. Click on Terminate session by listing the current session
5. There will be 2 alerts one as successful and 1 as a error in terminating session
6. Then try to list users or try to do any operation in the console
7. Will end up in something went wrong errors

![Screenshot from 2022-04-20 11-06-03](https://user-images.githubusercontent.com/31848014/164158180-7eb4f367-80cc-4ec9-b3b8-6fe2e690fb14.png)
![Screenshot from 2022-04-20 11-06-56](https://user-images.githubusercontent.com/31848014/164158190-46bba842-7cdc-482b-b7c4-36d38a5a4a5f.png)

https://user-images.githubusercontent.com/31848014/164158612-f82e296f-bc21-46f4-b319-6dba0d6cbd33.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 20

**Comment by piraveena** [comment]
when the session got terminated we need to show the "Your session has Expired". window and gracefully terminate the session. This error occurs since the tokens are revoked and the console app is active. So we need to gracefully termitate the app session

**Comment by ShanikaWickramasinghe** [comment]
@savindi7 Is this fix resolving the error given when clicking the Terminate All option.

https://user-images.githubusercontent.com/31848014/165279982-1ec8992b-39c7-464b-ba9a-cc66579ac4bf.mp4

![Screenshot from 2022-04-26 15-54-15](https://user-images.githubusercontent.com/31848014/165280068-1ec69aa4-a404-431c-bdb7-6a942919af35.png)

**Comment by savindi7** [comment]
The fix has resolved the initial issue of the session not getting gracefully terminated. So IMO this is happening due to another issue which we need to check. Shall we create a new github issue for this.

**Comment by ShanikaWickramasinghe** [comment]
Checked the 5.12.0 beta pack with myaccount and issue is not reproducible in the beta pack.

https://user-images.githubusercontent.com/31848014/165441187-137f87ca-9857-4c47-b6de-e467208f1193.mp4
