### ISSUE TITLE
Intermediate pages are visible for a short time in console when navigating among different UIs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13504]
**Describe the issue:**
Some intermediate unnecessary pages becomes visible for a short time during below navigations. Check the attached video

- [ ] Admin user > Roles tab > When view permissions > Edit permissions

A danger zone with a red button displays and get disappear

- [ ] Roles > admin role > move between Groups and users tab

Intermediate page is visible

https://user-images.githubusercontent.com/31848014/164166370-3009b8df-a25b-4a6d-8396-db066851d146.mp4

**Env**
IS 5.12.0 alpha 20

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
