### ISSUE TITLE
Something went wrong when updating admin users Groups

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13503]
**How to reproduce:**
1.  List admin user from console
2. Go to Groups tab
3. Try to remove assigned admin group

Will end up with below error
![Screenshot from 2022-04-20 11-43-28](https://user-images.githubusercontent.com/31848014/164162576-bfa659b7-fbe9-414b-b32b-55134ae5b3de.png)

IS 5.12.0 alpha 20

**Comment by nilasini** [comment]
Similar issue https://github.com/wso2/product-is/issues/13486
