### ISSUE TITLE
Role Creation Finish button is not getting highlighted compared to Next button

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13507]
**How to reproduce:**
1. Access console > manage > roles
2. Try to create a Role
3. The Finish button doesn't get highlighted when compared to Next button (Even though its a intermediate step it will be better to highlight the Finish operation)
![a](https://user-images.githubusercontent.com/31848014/164190597-20570294-8b54-4d58-b259-ef3fb2e6bde9.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 20

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
