### ISSUE TITLE
Unable to login to SAML sample application

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#13500]
**Describe the issue:**

Getting the following response in the browser when trying to login to the travelocity sample application with SAML.

```
{
  "traceId": "4ee7be5f-47af-4ce8-94fb-23e4f883b7f4",
  "code": 401,
  "description": "Authorization failure. Authorization information was invalid or missing from your request.",
  "message": "Unauthorized"
}
```

**How to reproduce:**

- Register a SAML sample application as a service provider
- Create a user
- Login to the sample application

**Expected behavior:**

Should be able to login to the sample application successfully

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Linux

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/367
