### ISSUE TITLE
Can not update SCIM Attribute Mapping in enterprise schema 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13509]
**Describe the issue:**

Can not update SCIM Attribute Mapping in enterprise schema. Drop down not display added external attribute. 

https://user-images.githubusercontent.com/39077751/164192960-dba02ecb-e2d6-4e6d-85f6-e289cd3a6618.mov

**How to reproduce:**
1. Login to console (JDBC user store)
2. Navigate to Manage-> Attribute
3. Click edit on Attribute pane
4. Create attribute by giving name, display name and description
5. Enable the 'Display this attribute in user profile' 
6. Select a order and complete the rest of the filed to create the external claim
7. Select the edit on SCIM dialect pane
8. Select enterprise schema  tab
9. Select add new attribute
10. Select drop down on SCIM Attribute

**Expected behavior:**
Drop down should display attribute to Map

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.alpha20
 - OS:  Mac
 - Database: MSSQL
 - Userstore:  JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
should be fixed with the issue https://github.com/wso2/carbon-identity-framework/pull/3998. This issue is fixed in the latest IS with the framework version `5.20.377`
