### ISSUE TITLE
Framework should provide support to call external protocol related validations and configurations

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#13511]
**Is your suggestion related to an experience ? Please describe.**

When sending an oauth request, the user is prompted to provide mandatory claims that are been configured at the service provider. These mandatory claims are requested regardless of the scope requested by the request. 

For example: 
If the country is set as a mandatory claim of the SP and a request is sent using the scope=openid, the user will be prompted to provide the country after login. Since the openid scope does not contain country claim, it will not be send in the response and therefore it is not necessary ask the user to enter the country value. 
Even though country is set as a mandatory attribute, it should be filtered based on the scope and should not be prompted for the user at login.

With the current implementation, prompting missing mandatory claims are handled by the framework and there is not way to incorporate scope based filtering during this flow since scope is specific to oauth protocol and scope based validations are handled separately by the identity-inboud-auth-oauth repo. 
 
**Describe the improvement**
There should be a way to add protocol specific configurations and validations to the framework if needed.

**Additional context**
Suggestions:

- scope based filtered claims can be added to the context from the post authentication handler and later be used in the missing claim handler. This method will do this filtering every time the user login, even when the missing claim handler will not be needed for most of the time.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
