### ISSUE TITLE
Error when adding attribute to SCIM user schema

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13510]
**Describe the issue:**
Error when adding attribute to SCIM user schema.

https://user-images.githubusercontent.com/39077751/164199542-1ac4e7c9-19da-4699-b2bb-5e9cec685c1a.mov

**How to reproduce:**
1. Login to console (JDBC user store)
2. Navigate to Manage-> Attribute
3. Click edit on Attribute pane
4. Create attribute by giving name, display name and description
5. Enable the 'Display this attribute in user profile'
6. Select a order and complete the rest of the filed to create the external claim
7. Select the edit on SCIM dialect pane
8. Select user schema tab
9. Click drop down on SCIM attribute and select one claim and map with the created claim
10. Click Add 

**Expected behavior:**
Claim should be added successfully. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Fixed with the https://github.com/wso2/carbon-identity-framework/pull/3998 in the latest IS. This issue is fixed in the latest IS with the framework version `5.20.377`
