### ISSUE TITLE
[Migration] Claims sent to applications are filtered by scope

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#13516]
In IS 5.11.0, if there are attributes configured at the service provider, these attributes will be sent to the application regardless of the scope set in the authorization request. But in 5.12.0, the claims configured in the service provider will be filtered by the scope and only the filtered claims will be sent to the application.

A config is available in 5.12.0 to disable this filtering: `enable_scope_based_claim_filtering`.
This config is set to `true` by default but if a user need to disable claim filtering based on scope, this config can be set to `false`.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
