### ISSUE TITLE
Single Logout is not working between myaccount and console apps

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13526]
**Describe the issue:**
1. Login to console
2. SSO for myaccount
3. Logout from console
4. Click on a tab open in console
5. Getting retrieval errors and console app doesnt get logged out

https://user-images.githubusercontent.com/31848014/164408055-6173ba74-ddb3-427b-9840-f6b73f43d9c8.mp4

![Screenshot from 2022-04-21 13-27-29](https://user-images.githubusercontent.com/31848014/164408112-cf3149ed-21f3-4601-83a7-187ab2591ee1.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 20

**Comment by ShanikaWickramasinghe** [comment]
Could be related https://github.com/wso2-enterprise/asgardeo-product/issues/10167

**Comment by piraveena** [comment]
SLO is working fine with sample apps pickup-dispatch and pickup-manager when enabling session management. Looks like this is a issue with the console and myaccount app

**Comment by piraveena** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2991
