### ISSUE TITLE
It Allows to create Scopes with the same name after a scope rename operation in console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13524]
**How to reproduce:**
1. Access console > manage > scopes
2. Create a scope with name as "test" and add Address as a attribute for that
3. Once the scope is created go to its edit view and update the scope name to "test1"
4. Now try to create another scope with name "test1"
5. It will allow to create the scope with the same existing name
6. System displays both the scopes created with the same name

This happens if you do a scope rename operation. If you try scope creation with the same name without rename operation then it will not allow to create the scopes with the same name. Same behavior should apply when a user do a rename too.
It should not allow to create scopes with the same name even after a scope rename operation
![a](https://user-images.githubusercontent.com/31848014/164387762-491d72bf-78fc-4c58-be91-fe283d75e4cc.png)

https://user-images.githubusercontent.com/31848014/164387773-fea46920-8a18-47c8-818e-3ffd075d4bac.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 20

**Comment by piraveena** [comment]
Names of scopes can't be modified in management console also. We can delete the scopes or update the attributes in scopes. But Renaming the scope name is not supported in the REST API also https://is.docs.wso2.com/en/latest/develop/oauth2-scope-management-rest-apis/#/Scope%20Management/updateScope

If you rename from the UI, it will change only the display name from the UI. It won't change the exact name of the scope. We don't have that support

**Comment by piraveena** [comment]
@ShanikaWickramasinghe It will update only the display name, not the name of the scope.
<img width="675" alt="Screenshot 2022-04-21 at 13 00 05" src="https://user-images.githubusercontent.com/17597293/164401465-5045a22a-0cba-4e65-ba93-f055958f4500.png">

**Comment by ShanikaWickramasinghe** [comment]
@piraveena So isnt it required the display name needs to be unique ?

**Comment by piraveena** [comment]
Yes. It can be done as an improvement to the product

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
