### ISSUE TITLE
multiple events published for single tenant user authentication

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#13520]
**Describe the issue:**
Identity server publishes multiple events to IS analytics server when single tenant user authentication. One event is for super tenant and another is for the particular tenant. 

**How to reproduce:**

- Enable statistics="enable" and trace="enable" for IsAnalytics-Publisher-wso2event-AuthenticationData.xml
- Create new tenant user and try to login to myaccount
- Two event traces can be found in the wso2carbon logs

**Expected behavior:**
User authentication event should be published into a particular tenant only.

**Environment information** 
 - Product Version: IS 5.11.0,
 - OS:  Linux
 - Database:  H2
 - Userstore: LDAP

---

**Suggestions**
When publishEvent method[1] is called, within the publishEvent method, it checks for publishingDomains in the authenticationData. For the publishingDomains, authenticationData object contains both super tenant and logged in user tenant. Therefore, two events are published for super tenant and particular tenant.
[1] https://github.com/wso2-extensions/identity-data-publisher-authentication/blob/5591450bb33133e552cfe642532ad5c3f2796da8/components/org.wso2.carbon.identity.data.publisher.authentication.analytics.login/src/main/java/org/wso2/carbon/identity/data/publisher/authentication/analytics/login/AnalyticsLoginDataPublishHandler.java#L148

**Comment by UdeshAthukorala** [comment]
**Proposed improvement:**

- When a tenant user logs in from a SaaS app, the expected default behavior is to publish two events for is-analytics, where one is for the service provider existing tenant and the other one is for the user existing tenant.
- If it is required to change the above default behavior, add below configuration in deployment.toml file to avoid publishing two login events. If the config is false, it will only publish a one login event for the SP existing tenant and if the config is true it will behave in the default manner.
   ```
   [identity_mgt.analytics_login_data_publisher]
   enableMultipleEventPublishingForSaasApps = false
   ```

- **NOTE**: The default value of the above configuration will be true.
