### ISSUE TITLE
Popping up error message when adding new OIDC attribute

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13521]
**Describe the issue:**
Intermittently error when list OIDC attribute.

https://user-images.githubusercontent.com/39077751/164359114-15a6301e-4a6f-49f6-8cdf-0be8bd1fa2d4.mov

<img width="1400" alt="Screenshot 2022-04-21 at 06 50 21" src="https://user-images.githubusercontent.com/39077751/164359019-da09ebd3-47b4-40fc-9f24-e492178430ca.png">

**How to reproduce:**
1. Login to console
2. Navigate to Manage->Attribute
3. Select Attribute pane and create attribute
4. Select OIDC dialect and click add new attribute

**Expected behavior:**
No errors should appear when navigate to the attribute page and click add new attribute button

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
The console app is calling an additional /schemas/config API and checks for the OpenID schema in the schema.xml file. 

```
curl 'https://localhost:9443/api/server/v1/configs/schemas/aHR0cDovL3dzbzIub3JnL29pZGMvY2xhaW0' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Authorization: Bearer 7eda7d92-0d0a-3f03-af81-0f4c2b31474b' -H 'Connection: keep-alive' -H 'Cookie: menuPanel=visible; menuPanelType=main; commonAuthId=7a374221-fb39-4fa8-ab3a-09a7ab4c763a; atbv=6000221a-d76c-4f34-8fee-5a8a56c725a5; opbs=4ce7c61b-27c6-432f-a8dc-5d0058cf4962'
```
This API call is an unnecessary call. Anyhow this does not affect the functionality of adding openid attributes

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2970
