### ISSUE TITLE
Need to remove hexify function from "x5t" calculation in OIDC ID Token

### ISSUE THREAD

**Issue by GayanM** [wso2/product-is#1353]
**Description:**
According to JWS specification [1] x5t value is 
   The "x5t" (X.509 certificate SHA-1 thumbprint) Header Parameter is a
   base64url-encoded SHA-1 thumbprint (a.k.a. digest) of the DER
   encoding of the X.509 certificate [RFC5280] corresponding to the key
   used to digitally sign the JWS.  Note that certificate thumbprints
   are also sometimes known as certificate fingerprints.  Use of this
   Header Parameter is OPTIONAL.
so we need to remove hexify from "x5t" calculation logic 

[1] https://tools.ietf.org/html/rfc7515#section-4.1.6
 
**Affected Product Version:**
5.3.0

**OS, DB, other environment details and versions:**

**Steps to reproduce:**
Check "x5t" value in JWT header 

**Related Issues:**
https://wso2.org/jira/browse/IDENTITY-4616

**Comment by DMHP** [comment]
When obtaining the certificate thumbprint it need to hexify the value.

What is the thumbprint of the certificate?
A certificate thumbprint is an hexadecimal string that uniquely identifies acertificate. A thumbprint is calculated from the content of the certificate using athumbprint algorithm. CES accepts Secure Hash Algorithm 1 (SHA-1) thumbprintsin the 40-digit hexadecimal string form without spaces.
