### ISSUE TITLE
Inconsistency  of approval task status

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13539]
**Describe the issue:**
When creating user from the console and when creating user from the management console, approval task status is inconsitance.
For console it shows set of claims and for management console its not shows claim section

User create from console

<img width="893" alt="Screenshot 2022-04-22 at 18 17 13" src="https://user-images.githubusercontent.com/39077751/164717661-b1675e4b-9746-4a66-920a-6ccda6333807.png">

User create from management console 
<img width="883" alt="image" src="https://user-images.githubusercontent.com/39077751/164717753-c7ea58de-5db4-462b-b041-b3c78a58fd40.png">

**How to reproduce:**
1. Create work flow for add users
2. Add user from management console
3. Add user from console
4. Login to console with approver
5. Compare the two status in approval list

**Expected behavior:**
Status should be same.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
