### ISSUE TITLE
Migrate hazelcast logging configurations from log4j to log4j2

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#13531]
**Describe the issue:**
As being the support for log4j has been stopped, log4j is removed from the latest pack and switched to log4j2. In Identity server cluster setup, hazelcast is used for distributed caching and log4j is configured explicitly in the deployment.toml file, to used as default logging mechanism. Therefore it is needed to switch for log4j2 logging if already configured to use log4j1.

**How to reproduce:**
[hazelcast]
"hazelcast.logging.type"= "log4j"

**Expected behavior:**
[hazelcast]
"hazelcast.logging.type"= "log4j2"

Also, hazelcast logging configuration can be removed entirely and it will lead to hazelcast to use JDK logging as its default logging mechanism.

**Comment by ashendes** [comment]
Added to docs with https://github.com/wso2/docs-is/pull/2991, https://github.com/wso2/docs-is/pull/2997
