### ISSUE TITLE
Getting a Authorization failure when try a saml flow with saml2-web-app-pickup-dispatch.com sample

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13542]
**How to reproduce:**

1. Get the saml2web app pickup distpatch or manager samples from https://github.com/wso2/samples-is/releases
2. Set up the sample as in https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp
3. Mode which tried the flow was super tenant
4. sso.properties file for super tenant mode

```
SAML2.SPEntityId=saml2-web-app-pickup-dispatch.com
IdPPublicCertAlias=wso2carbon
SAML2.AssertionConsumerURL=http://localhost:8080/saml2-web-app-pickup-dispatch.com/home.jsp

```
6. Access http://localhost:8080/saml2-web-app-pickup-dispatch.com/home.jsp

Getting below error page in the browser

![Screenshot from 2022-04-22 19-49-14](https://user-images.githubusercontent.com/31848014/164748336-25804404-bbf6-4c31-88ea-70f399835f7c.png)

Flow didnt worked in the tenant mode too. Tried with steps in https://piraveenaparalogarajah.medium.com/trying-out-saml2-pick-up-dispatch-app-with-wso2-identity-server-in-a-tenant-20626ac4865a

sso.properties file for tenant mode

```
SAML2.SPEntityId=saml2-web-app-pickup-dispatch.com
IdPPublicCertAlias=wso2.com
QueryParams=tenantDomain=wso2.com
SAML2.AssertionConsumerURL=http://localhost:8080/saml2-web-app-pickup-dispatch.com/home.jsp

```

Tried the same steps with a 5.11.0 U2 pack in super tenant mode. Then the flow worked successfully 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 alpha 20

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/13500
Already fixed with latest snapshot pack
