### ISSUE TITLE
Paginating with Single Attribute Filtering in JDBC user stores without providing a count only returns up to 100 results across pages.

### ISSUE THREAD

**Issue by BojithaPiyathilake** [wso2/product-is#13540]
**Describe the issue:**

When paginating with single attribute filtering in JDBC userstores, without providing a count value, the **_items per page decreases_** although there are more records available. 

**First request;**
![image](https://user-images.githubusercontent.com/64316053/164722993-595677d8-0c8f-433a-be41-37a263e9631f.png)
Total results which meet the filtering conditions: 1000.
Since a count isn't given, the max pagination size of the server (100) is taken, and 100 items per page are displayed - Intended behavior.

**Second request;**
![image](https://user-images.githubusercontent.com/64316053/164723251-ef55e96f-9110-4ee0-8d91-77b8fb09de2d.png)
When startIndex is increased to 50, the **items per page is reduced to 51**, although there should be 100 as the total results are 1000.

**Third request;**
![image](https://user-images.githubusercontent.com/64316053/164723510-839fbbdb-c567-46a7-b207-2f3223865bf2.png)
Items per page keep decreasing when the startIndex value is increased.

**Fourth request;**
![image](https://user-images.githubusercontent.com/64316053/164723596-a8e40213-33c7-4d8a-8593-a76feed8d70c.png)

**How to reproduce:**

1. Use a copy of "wso2is-5.12.0-alpha14-SNAPSHOT"
2. Using POSTMAN send a request with a single filter and a startIndex to a domain using a JDBC userstore.
![image](https://user-images.githubusercontent.com/64316053/164724729-c0fd9bc9-aee4-467c-a95f-1088ced46933.png)
3. Try subsequent requests with increasing startIndex values.

**Expected behavior:**

Even through the startIndex value increases, the results per page should be 100 until it reaches the max limit of 1000.

**Environment information** 
 - Product Version: wso2is-5.12.0-alpha14
 - OS: Ubuntu Linux
 - Database: MySQL
 - Userstore: JDBC

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
