### ISSUE TITLE
Self user registration is not working 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13549]
**Describe the issue:**
Self user registration is not working. This is working for super tenant (both myaccount and console)

https://user-images.githubusercontent.com/39077751/164767765-4b24903c-c4b8-4407-bd66-3a24dd23e10d.mov

**How to reproduce:**
1. Login to the console
2. Navigate to the Manage->User onboarding 
3. enable self user registration under self user registration 
4. Navigate to the my account https://localhost:9443/t/wso2.com/ 
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/39077751/165042705-dc031054-503c-4e38-a3a3-435942af5f33.png">

**Expected behavior:**
User self registration link should be available at the myaccount login page 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: [Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Could not reproduce this issue. Self registration should be enabled for the app's tenant

**Comment by piraveena** [comment]
Here the issue is, we enable self-registration from console in the tenant abc.com. But the self-registration is not enabled for the tenanted abc.com myaccount

**Comment by piraveena** [comment]
Need to check this behaviour with 5.11 pack too

**Comment by asha15** [comment]
I checked this in 6.0.0-m1 pack.

As @piraveena said since this is a SaaS app, if we disabled self registration from super tenant, it won't be available for other tenants as well. so the current behavior is correct.

**Comment by asha15** [comment]
In 5.11.0 pack:

If we disabled user self registration feature from super tenant, the self registration feature is still available in myaccount login page. It's a bug, I created a separate issue for that: https://github.com/wso2/product-is/issues/13743
