### ISSUE TITLE
IS Analytics Geo Location script not found in IS 11 and the found script does not account for an extra column

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#13541]
**Description:**
(1) DB scripts cannot be found at the documentation [1].
Documentation says,
`Create the database by executing one of the scripts in the Geolocation Data/dbscripts`
but the script is not found at [1].

(1.1) Even though analytics worker and dashboard, for the most part, creates schemas automatically when the database location is given, the transaction in the script found at the older APIM documentation [2] is not created automatically when the analytics worker is given the DB location. Hence the transaction found in the script at [2] or a script for object creation is necessary.

(2) Found the script at [2] (older apim version), in which the "LOCATION" table does not have "is_in_european_union" field at the end even though the dataset (GeoLite2-City-Locations-en.csv) pointed at [3], contains this field (Maxmind might have added the new column at a point). Either instructions to remove the said column before importing the csv file should be given or the column should be added to the script "LOCATION" table and the script should be given, which I assume would be the correct way.

[1] https://is.docs.wso2.com/en/latest/learn/enabling-geolocation-based-statistics/
[2] https://apim.docs.wso2.com/en/3.2.0/learn/analytics/analyzing-apim-statistics-with-batch-analytics/using-geo-location-based-statistics/configuring-geo-location-based-statistics/
[3] https://is.docs.wso2.com/en/latest/learn/creating-geo-location-dataset/

Affected Product Version:
IS Server 5.11 with IS Analytics 5.8

Steps to reproduce:
(1) refer [1],
(1.1) 
- Create a db named "geo_location_data" in a preferred RDBMS,
- Configure the data in the IS analytics worker deployment.yaml,
- Start the worker.sh,
- Try to import the CSV file to database.
(2) Check the columns against the location file header.

Expected behaviour:
(1) Either the script should be given, **or**
(1.1) IS Analytics Worker should execute the TRANSACTION (or create the schema altogether) in a preferred RDBMS, then when the CSV files are imported, the TRANSACTION is triggered and tables are created and the data will be imported.
(2) If having the new column in the geo database is not issue a problem (as I have tested), then when the script for transaction is given this column should be there in the table "LOCATION" schema as below,
```
CREATE TABLE LOCATION (
  geoname_id int NOT NULL,
  locale_code varchar(10) DEFAULT NULL,
  continent_code varchar(10) DEFAULT NULL,
  continent_name varchar(20) DEFAULT NULL,
  country_iso_code varchar(10) DEFAULT NULL,
  country_name varchar(45) DEFAULT NULL,
  subdivision_1_iso_code varchar(10) DEFAULT NULL,
  subdivision_1_name varchar(1000) DEFAULT NULL,
  subdivision_2_iso_code varchar(10) DEFAULT NULL,
  subdivision_2_name varchar(1000) DEFAULT NULL,
  city_name varchar(1000) DEFAULT NULL,
  metro_code int DEFAULT NULL,
  time_zone varchar(30) DEFAULT NULL,
  is_in_european_union int NOT NULL,
  PRIMARY KEY (geoname_id)
);
```

**Comment by isurusamarasekara** [comment]
Hi Team,

Any update on this ?
Still the IS docs for 5.9.0, 5.10.0, 5.11.0 [1] are not updated to include the dbscript as it includes [2].
Please note that the scripts should be updated as well mentioned in [3].

[1] https://is.docs.wso2.com/en/5.11.0/learn/enabling-geolocation-based-statistics/
[2] https://apim.docs.wso2.com/en/3.2.0/learn/analytics/analyzing-apim-statistics-with-batch-analytics/using-geo-location-based-statistics/configuring-geo-location-based-statistics/
[3] https://github.com/wso2/product-is/issues/13541

Thanks and regard,
Isuru Samarasekara.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
