### ISSUE TITLE
Can not edit existing SCIM attributes mapping

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13550]
**Describe the issue:**
Can not edit existing SCIM attributes mapping.

https://user-images.githubusercontent.com/39077751/164958462-63f93592-c88e-4de7-acc8-092a149d6840.mov

**How to reproduce:**
1. Login to console
2. Navigate to the Manage-> attribute-> SCIM attribute
3. Select enterprise schema 
4. Search for Lite User from existing list
5. Click edit 
6. Select some other claim to map and click update

**Expected behavior:**
Should be successfully update the existing attribute mapping. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Fixed "Something went wrong" issue with https://github.com/wso2/identity-apps/pull/2972
