### ISSUE TITLE
Password reset is not working

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13558]
**Describe the issue:**
Password reset is not working

https://user-images.githubusercontent.com/39077751/165075566-ad828bf5-8a90-4fa1-8f6d-30bf84795b94.mov

**How to reproduce:**
1. Login to console
2. Navigate to Manage-> Account Management 
3. Enable password reset via recovery e-mail in Password reset pane
4. Logout and validate the link to forget password available in the console login page
5. Navigate to my account login page and check the same
Reference document : https://is.docs.wso2.com/en/latest/learn/configuring-password-reset-with-email/

**Expected behavior:**
Forget password link should be available. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Need to enable account recovery config for password recovery

<img width="1182" alt="Screenshot 2022-04-25 at 17 11 34" src="https://user-images.githubusercontent.com/17597293/165082155-f5a2165e-1d33-4ce1-a0ef-8e38da014292.png">

Can you verify it?
