### ISSUE TITLE
Required to update the Ask password widget 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13554]
**Describe the issue:**
Currently Ask password widget contain two features. They are ask password and email verification. [1] [2]
[1] https://is.docs.wso2.com/en/latest/learn/creating-users-using-the-ask-password-option/#configuring-the-feature
[2]https://is.docs.wso2.com/en/latest/learn/user-registration-with-email-verification/

According to the document [2]  user creation with email verification can only do with SCIM API call. Document issue: https://github.com/wso2/product-is/issues/13557

<img width="781" alt="image" src="https://user-images.githubusercontent.com/39077751/165051296-186f1311-6bc8-4125-a27c-060cf41dd979.png">

**How to reproduce:**
1. Login to console
2. Navigate to the Manage -> User onboarding 

**Expected behavior:**
There should be explanation in Ask password header regarding bot function.  

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/13557

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
