### ISSUE TITLE
My account login gives 404 error

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13551]
**Describe the issue:**
When user login to the my account at first time it gives page not found 404 error. 
<img width="741" alt="Screenshot 2022-04-24 at 22 30 37" src="https://user-images.githubusercontent.com/39077751/164987783-441e4f8f-ec0d-434e-9c5a-c2ec47e0f462.png">

https://user-images.githubusercontent.com/39077751/164987798-0c5d6312-59fc-4452-b016-97d7a79a0d85.mov

**How to reproduce:**
1. Login to console
2. Create user
3. Navigate to my account login page 
4. Login to the myaccount with created new user

**Expected behavior:**
Logged user should direct to the myaccount overview page

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC
 - Browser: chrome/chromium

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
When logging to the system, we need to provide the tenant domain user@tenantDomain.com since this is a saas app

**Comment by aaujayasena** [comment]
Yes, Im adding tenant domain here. wso2.com is the tenant here. @piraveena

**Comment by piraveena** [comment]
Saw this logs
<img width="379" alt="Screenshot 2022-04-25 at 13 42 04" src="https://user-images.githubusercontent.com/17597293/165054176-9ce60e53-df7e-4e20-b4d4-7487b9c9fd64.png">
<img width="1085" alt="Screenshot 2022-04-25 at 13 41 59" src="https://user-images.githubusercontent.com/17597293/165054196-1c3f3118-8dd0-4a19-9d8f-ea676e00c50e.png">

**Comment by piraveena** [comment]
To reproduce the issue:
1. Login to tenant myaccount http://localhost:9443/t/abc.com/myaccount
2. Login as admin:admin
3. The above issue will be reproduced.

In the following scenarios, the flow will work.
1. Login to tenant myaccount http://localhost:9443/t/abc.com/myaccount
2. Login as **admin@abc.com**:admin
