### ISSUE TITLE
User registration email document missing the  SCIM API request

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13557]
**Is your suggestion related to a missing or misleading document? Please describe.**
User registration email document missing the  SCIM API request

<img width="794" alt="Screenshot 2022-04-25 at 14 14 28" src="https://user-images.githubusercontent.com/39077751/165066985-ad865a97-4541-45fc-ae94-991aba9d4b25.png">

https://is.docs.wso2.com/en/latest/learn/user-registration-with-email-verification/

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by aaujayasena** [comment]
This is resolve now. Hence we can close.
![image](https://user-images.githubusercontent.com/39077751/204979516-13c87f23-6421-46ee-af10-cfca02fbbe8c.png)
![image](https://user-images.githubusercontent.com/39077751/204979553-cf98ce03-44a0-418a-b93a-09eb8e4e0fad.png)

**Comment by divyaamunugama** [comment]
Closing the issue as this is fixed.
