### ISSUE TITLE
Can not register Touch Id fido key in Safari browser(Mac M1 chip)

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13568]
**Describe the issue:**
Can not register fido key in Safari browser.

https://user-images.githubusercontent.com/39077751/165265524-597ca5ae-7caf-4b67-820b-a3f272811b2f.mov

**How to reproduce:**
1. Login to myaccount
2. Navigate to the security page
3. Click add button in Security key/biometric section
4. Allow add touch ID
5. Insert fingerprint 

**Expected behavior:**
Device should be registered sucessfully.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
This is a known issue in the platform authenticators with Safari browser and MacOS with M1 chip. External USB keys are working fine. The original issue is reported here [1] and another discussion can be found in fido-dev mailing list [2]. As per comment [3] this will be fixed in a future release.

[1] https://bugs.webkit.org/show_bug.cgi?id=224042
[2] https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/BHYtIkLTZbM
[3] https://bugs.webkit.org/show_bug.cgi?id=224042#c8

**Comment by ashensw** [comment]
This is fixed with macOS Monterey‌‌‌ 12.3‌‌.1 update. Tested with macOS Monterey‌‌‌ 12.3‌‌.1 (M1 pro) and safari. Refer [1].

[1] https://bugs.webkit.org/show_bug.cgi?id=224042#c13

@aaujayasena can you also verify with M1 chip?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
