### ISSUE TITLE
Disabling SMS-OTP from user profile

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#13569]
**Describe the issue:**
When disabling the SMS-OTP through the user profile , user has to enter **True** in the Disable SMSOTP option  and update.
Its better to convert it into a checkbox rather than user entering texts.

![Screenshot from 2022-04-26 15-30-52](https://user-images.githubusercontent.com/40081059/165280021-5a86edb6-5e83-4250-91b5-00a945e14f6d.png)

**How to reproduce:**
Convert the Disable SMSOTP option into a checkbox.
>

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g.IS 5.12.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
