### ISSUE TITLE
Allow editing and mapping identity claims from Console UI

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#13561]
**Describe the issue:**
Currently, we have blocked the Console UI to not add any mapping to identity claims. We need to allow those mappings 

**How to reproduce:**
1. Go to Console
2. Go to Attributes > OpenID Connect
3. Try to map an identity claim to an oidc attribute
4. UI will not show any identity claims, since the UI filters the attributes

This is applicable for other attribute dialects too (OIDC/custom/SCIM)

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/2980
