### ISSUE TITLE
Authentication error  login with Fido when user has no device registered. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13567]
**Describe the issue:**
Authentication error when user attempt to login with Fido and user has no device registered. 

https://user-images.githubusercontent.com/39077751/165261773-9c3060a3-9ff4-4fdd-a32d-b7033f0995bb.mov

**How to reproduce:**
1. Login to management console.
2. Create application and select FIDO as second authentication option and basic as first optioon.
3.  Create user
4. Login to my account
5. Navigate to the security page
6. Click + mark on Security Key/Biometrics section
7. Register Fido
8. Login to sample app
9. Add basic authentication and click login

**Expected behavior:**
If user is not registered it should notify the user to registered a device.  

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-alpha20
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC
 - Browsers: Chrome and edge

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
@aaujayasena could you able to check whether we have any configs to enable this?
