### ISSUE TITLE
Wrong content in the docs related to Linked Social accounts

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13571]
**Is your suggestion related to a missing or misleading document? Please describe.**

Refer the doc in https://is.docs.wso2.com/en/latest/learn/associating-user-accounts/
![a](https://user-images.githubusercontent.com/31848014/165294963-8c7f086c-ab5b-405b-8706-d6c2a6a7dc00.png)

Added below config to deployment.toml 

```
[user.association]
enable_for_federated_users = true
```
Access myaccount > personel info > Linked social accounts

![Screenshot from 2022-04-26 17-28-49](https://user-images.githubusercontent.com/31848014/165295555-c3b01f85-6a7e-439f-88d8-bab389d21648.png)

As per the doc we cant do this association through myaccount. This can be done by rest apis or adaptive scripts. WE need to check and update this outdated content

pls refer https://medium.com/identity-beyond-borders/social-account-linking-with-wso2-identity-server-78b8a566e225

**Comment by piraveena** [comment]
Check this comment for linking federated accounts: https://github.com/wso2/product-is/issues/13573#issuecomment-1110852040

Check this comment for linking local account: https://github.com/wso2/product-is/issues/13573#issuecomment-1111732726

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
