### ISSUE TITLE
Showing a proper error message when trying add consent purpose with duplicated name.

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#13582]
**Description:**

Current behaviour.

When a user tries to add a consent purpose with an already existing purpose name the error message is shown as “Purpose: <name> adding failed”. 

Expected behaviour.

There should be a proper error message to indicate that the user is trying to duplicate the purpose name.

**Affected Product Version:**
IS 5.12 Alpha 20

**OS, DB, other environment details and versions:**    
  OS:maçOS Monterey 

**Steps to reproduce:**
Log into https://localhost:9443/carbon/
Navigate to the Identity Providers -> Resident -> User Onboarding -> Self Registration -> Manage Self-Sign-Up purposes 
Add a consent purpose with Purpose Name <name>

Try to add another consent purpose with the same name.

Then the following error message is shown.
![Screenshot 2022-04-27 at 09 17 13](https://user-images.githubusercontent.com/25563417/165459649-4e16b254-4fd7-4983-a923-451216c47d6d.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
