### ISSUE TITLE
Need to clearly mentioned about the reCaptcha prompt when user is locked

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#13589]
**My suggestion**
- reCaptcha is reuqired to prompt after `Lock user accounts on maximum failed attempts` and not required to prompt after `Prompt reCaptcha after max failed attempts` as after the max failed attempts the account is locked and users cannot login.
- But https://is.docs.wso2.com/en/latest/learn/setting-up-recaptcha/ documentation not clearly states that  there is no prompt of reCaptcha after `Prompt reCaptcha after max failed attempts`
- Need to add these information 

**Related issue**
https://github.com/wso2/product-is/issues/13195

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
