### ISSUE TITLE
Any deployable war files not compatible with Apache Tomcat server 10.x.x version

### ISSUE THREAD

**Issue by Chetan973** [wso2/product-is#13580]
Hi Team @ShanChathusanda93 ,
I would like to inform you , any deploy-able .war files like pickup-dispatch webapp, saml2-web-app-pickup-dispatch webapp, are not compatible with tomcat server 10.0.x versions, Tried lot of circus to resolve any internal , mistaken issues , but finally thought these files are not proper deploying with tomcat 10.0.x versions . Then I tried with 9.0.62.0 version , so its working fine.

![2022-04-25-23-23-55](https://user-images.githubusercontent.com/83531282/165447838-30ca8ed5-eda4-483f-aafd-74ad533039d0.png)

![2022-04-25-23-23-26](https://user-images.githubusercontent.com/83531282/165447913-0e7e73dc-32da-4d1e-a167-9f33c54970cc.png)

![2022-04-25-23-24-06](https://user-images.githubusercontent.com/83531282/165447963-dc6a6d0f-9f80-42da-b9a6-4d5b48911578.png)

![2022-04-25-23-16-42](https://user-images.githubusercontent.com/83531282/165448024-81e66121-aff1-4c14-9ffd-7283821b520d.png)

![2022-04-25-23-25-25](https://user-images.githubusercontent.com/83531282/165448062-96d3079a-9944-45f4-b5c5-54dcb04652de.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
