### ISSUE TITLE
Improve the implemented solution for warn the user on consent purpose related operations which may cause the self registration to not working properly.

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#13581]
**Improvement**

According to the issue in[1] the self registration flow breaks when the user enables User self registration  and  Lock user account on creation and defines consent purpose in one of the following ways.

1. A user has defined a consent purpose without adding Email Address as a PII category/user attribute.
2. A User has defined a consent purpose, adding Email Address as an optional PII category and does not provide a value to the email field at the self registration.
3. A user has defined a consent purpose, adds Email Address to the PII category as an optional attribute, provides email in the self registration flow and does not give the consent to share the email.

When the system tries to send the verification to the email provided by the user in the self registration flow, it throws an exception since the email address is not provided at self registration. Therefore the self registration flow breaks. 
 
As a fix; 
 
A warning message was introduced[2] to warn the user about a list of consent purposes which may lead to self registration flow interruption. Following are the actions that can cause a list consent purpose which may interrupt the flow. 
 
1. Add a consent purpose without adding  Email Address as a mandatory PII category and there are no previously defined consent purposes with Email Address as  a mandatory PII category.
 
2. Add a consent purpose with  Email Address as an optional PII category and there are no previously defined consent purposes with Email Address as a mandatory PII category.
 
3. Delete a consent purpose with Email Address as a mandatory PII category and there are no other consent purposes which contain the Email Address as mandatory PII category.
 
In the implementation to check the available PII categories in the already added (listed) consent purpose there was no API already implemented to get all the consent purposes and associated PII categories at once by passing a list of purpose IDs. Therefore, getPurpose[3] API has been used to get the required consent purpose details one by one. Since for each purpose API is called separately there will be an impact on the system's performance. 

As an improvement;

An API which can be used to get all the consent purposes and associated PII categories  using one API call by passing a list of consent purpose IDs should be implemented.

[1]https://github.com/wso2/product-is/issues/11958 
[2]https://github.com/wso2/carbon-consent-management/pull/208 
[3]https://github.com/LakshiAthapaththu/carbon-consent-management/blob/52f6e4d3d62bd40c9f86591bf4b06256fec57a16/components/org.wso2.carbon.consent.mgt.core/src/main/java/org/wso2/carbon/consent/mgt/core/ConsentManager.java#L53

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
