### ISSUE TITLE
Need to document the configurations for show "ActualAuthFailureReason"

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#13591]
**My suggestion**

- When the account is locked due to fail attempts, UI shows the "Login failed! Please check your username and password and try again" message even the actual error message is account locked. 

- We need to add some configurations as mentioned in https://github.com/wso2/product-is/issues/13195#issuecomment-1111722031 to show the actual auth failure reason.

- Suggest to document those information

**Related issues**
https://github.com/wso2/product-is/issues/13195

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
