### ISSUE TITLE
Improve Application Owner update flow when the current user is removed 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13590]
**Describe the issue:**
Application update flows always check the validity of the application owner. In other words, whether the user exists /or not.

If the application-created user got removed from the DB/user store, application editing and client credentials OAuth flow of the app (since it depends on the app owner privileges)get a break.

- We have added a temp fix of getting errors in application editing: https://github.com/wso2/product-is/issues/6639 (application edit flow, if the app owner doesn't exists set the tenant owner as admin)
- Still, https://github.com/wso2/product-is/issues/6639 fixes the problem of not functioning client credential grant for the app when the app owner doesn't exist. That issue is fixed by https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1809

The next issue is, that now the app owner will be updated only when doing app info editing. Util that client credential grant will not work.

- We have difficulties when changing the app owner at the point of time when deleting the current app owner. The difficulty is not having a low privileged default user with a user ID.

Pending Improvements:
**one of the following options should be done**:
1. If the app owner is deleted, move the application into a not working state (Need to remove https://github.com/wso2/product-is/issues/6639 fix), and in the UI/ application GET response should include that admin needs to change the app owner.
App owner change can be done via the new REST API introduced in https://github.com/wso2/product-is/issues/10466 (Need some improvement to remove current owner validation in this flow)

2. Introduce a low privileged user with a user ID to the userstores and use that user as the defaulted app owner when deleting the current app owner 

**How to reproduce:**
1. Create userA. Assign application creation role/admin role
2. Create a service provider by user A (use REST API if the user can't log into the console)
3. Configure app as an oauth app. Enable client credential grant type for created app
4. Delete user A
5. Try app editing and client credential grant 

Related Issues:

1. https://github.com/wso2/product-is/issues/6639
2. https://github.com/wso2/product-is/issues/10466

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.12.0,

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
