### ISSUE TITLE
Duplicate CORS Response Headers when calling Authentication API by a SPA

### ISSUE THREAD

**Issue by politis-sofoklis** [wso2/product-is#13592]
Identity Server appears to be duplicating CORS response headers as it appears in the following screenshot

**How to reproduce:**
![image](https://user-images.githubusercontent.com/33422958/165734955-2f29f54d-014e-420e-b984-9a6f0d8f83b7.png)
you can also check the CORS configuration on my deployment.toml
![image](https://user-images.githubusercontent.com/33422958/165735028-09a519fb-3939-48d8-b130-86566d619fc3.png)
Sample of the request bellow:

![image](https://user-images.githubusercontent.com/33422958/165736534-2b129b86-651a-4dfc-8378-70df9b77279c.png)

**Expected behavior:**
Access-Control-Allow-Credentials and Access-Controll-Allow-Origin Header should only appear once

**Environment information** 
 - Product Version: WSO Identity server 5.11.0
 - OS: Windows
 - Database: MSSQL
 - Userstore: default
---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
