### ISSUE TITLE
Admin force password reset using SCIM 2.0 API should be changed to a PATCH endpoint

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#13594]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the forced password reset documentation, the admin force password reset using SCIM 2.0 API is mentioned as a POST endpoint but it was a PATCH endpoint. 

![Screenshot 2022-04-28 at 16 18 09](https://user-images.githubusercontent.com/35717390/165750917-cc3a26f9-25c4-4ad7-b52c-d989dc80f0cb.png)

**Describe the improvement**
The example snippet should be updated accordingly

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
