### ISSUE TITLE
JavaScript SDK integration failing on Identity Server - Windows

### ISSUE THREAD

**Issue by Nirmal-De-Silva-99** [wso2/product-is#13597]
**Describe the issue:**
Followed by "[IS-Docs] Integrate SDK to Identity Server guide" the JavaScript sample app is not running in the localhost. However the Angular and React apps worked fine.

The output on cmd for `npm install && npm start`
![image](https://user-images.githubusercontent.com/65043823/165883526-08573020-e06e-4e24-9fe4-333d42f7d4e6.png)

The output on WSL for `npm install && npm start`
![image](https://user-images.githubusercontent.com/65043823/165883633-6053e863-78c9-4662-910f-926edff52ce9.png)

The output on https://localhost:5000/
![image](https://user-images.githubusercontent.com/65043823/165883728-ef1828f9-c495-46fd-b192-a628f2fb860c.png)

**How to reproduce:**
Steps to be followed can be found here [IS-Docs Integrate SDK to Identity Server](https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit#heading=h.8yabwcq40fop)

**Expected behavior:**
The sample JavaScript app should run without any exceptions

**Environment information:**
 - Product Version: [IS 5.12.0 Alpha20]
 - OS: [Windows]
 - Database: [PostgreSQL]

**Comment by piraveena** [comment]
@Nirmal-De-Silva-99 can you check localhost:3000 port? Recently team has changed the port of the sample apps to 3000 due to some conflicts in the 5000 port in MacOS. 
You can check these readMe  of following sdks, they ask to configure 3000 port
https://github.com/asgardeo/asgardeo-auth-js-sdk
https://github.com/asgardeo/asgardeo-auth-react-sdk

**Comment by Nirmal-De-Silva-99** [comment]
Tried with localhost:3000 port, still shows the same output.

**Comment by CommandoHuan** [comment]
I have the same problem.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
