### ISSUE TITLE
Issues with address claim in idtoken when using scope=address

### ISSUE THREAD

**Issue by ChanikaRuchini** [wso2/product-is#13600]
**Describe the Issue:**
issue 1. **Formatted, Country, postalcode, locality, region** are **missing** in address claim even though we prompts for consent
issue 2. Address claim response contain escape chars
issue 3. Address should be JSON object according to the spec. Here we send a JSON array.

We could see below address claim in the id token.
``` 
 "address": [
    "{\"street_address\":\"streetadress\"",
    "\"address\":\"hhhhh\"}"
  ],
```

**How To Reproduce:**
1. Add Formatted, Country, postalcode, locality, region, street_adress and address as mandatory claim
2. Request with `address` scope.
3. User will be prompted  to enter the missing mandatory claims
3. But Formatted, Country, postalcode, locality, region are not coming in the idtoken
4. Expected value should be as below: https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim

```
{
   "address": {
     "street_address": "1234 Hollywood Blvd.",
     "locality": "Los Angeles",
     "region": "CA",
     "postal_code": "90210",
     "country": "US"},
}
```

**Expected behavior:**

 The expected value should be as below: https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim

```
{
   "address": {
     "street_address": "1234 Hollywood Blvd.",
     "locality": "Los Angeles",
     "region": "CA",
     "postal_code": "90210",
     "country": "US"},
}
```

Related to https://github.com/wso2-enterprise/asgardeo-product/issues/5010

**Comment by ashendes** [comment]
Addressed in https://github.com/wso2/docs-is/pull/3232
