### ISSUE TITLE
Update Profile Picture with Gravatar based option is not available when try with postgres 13.2 in Myaccount

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13608]
**How to reproduce:**
1. Setup postgres 13.2 as the database and configure it as the primary db for IS

```
[user_store]
type = "database_unique_id"

[database.identity_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/twelvebeta"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/twelvebeta"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

```
2. Access myaccount as super admin user
3. Go to personal info
4. Click on profile image to update profile image

Gravatar based profile images are not visible
When check with a H2 default pack theses gravatars are visible

With postgres 13.2
![a](https://user-images.githubusercontent.com/31848014/166424079-104bd921-5563-470c-899c-199aef0089f1.png)

With H2 default pack

![Screenshot from 2022-05-03 13-51-16](https://user-images.githubusercontent.com/31848014/166424169-1c66df1f-3fc3-4f99-bf43-f37f8b1229d9.png)

https://user-images.githubusercontent.com/31848014/166424203-7735a184-7739-4344-b2be-76fee719e6cd.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.12.0 Beta
Postgres 13.2

**Comment by Anandi-K** [comment]
This behavior is due to there is no email address associated with super admin user. The logic is defined in [1]

This is defined in `embedded-ldap.xml`.
```
<PartitionAdmin>
<Property name="uid">admin</Property>
<Property name="lastName">Administrator</Property>
<Property name="email">admin@wso2.com</Property>
<Property name="password">admin</Property>
<Property name="passwordType">SHA</Property>
</PartitionAdmin>
```
Since we will be using a different user store in this scenario we will get the email value, hence according to [1] logic the gravitar options will not be visible.

[1] https://github.com/wso2/identity-apps/blob/a1baac52eab2d7c4c764aa5e5dd0543397b84949/modules/react-components/src/components/modal/edit-avatar-modal/edit-avatar-modal.tsx#L247
