### ISSUE TITLE
Give prominent to group role association in Console UI

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#13629]
**Is your suggestion related to an experience ? Please describe.**
After group-role separation, a group should be used to assign roles to a set of users. Admins should not be allowed to add roles to users directly. 

Instead, the expected flow should be
1. Create a role and assign permissions
2. Create user
3. Create group and add roles associated with the groups
4. Assign users to groups

Now we are allowing to assign users to roles directly from Console and roles to users directly. This needs to be fixed from Console. 
<img width="590" alt="Screenshot 2022-05-06 at 09 29 23" src="https://user-images.githubusercontent.com/17597293/167064707-14734e8b-83fa-42b2-8081-9b854335ba05.png">

<img width="664" alt="Screenshot 2022-05-06 at 09 29 33" src="https://user-images.githubusercontent.com/17597293/167064713-6c6f3d32-810f-4208-b1d3-835cf367d714.png">

The console should not allow assigning roles to users, instead should be able to assign roles to groups.

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
