### ISSUE TITLE
Syntax error in SQL statement "CREATE TABLE CM_PII_CATEGORY  in Consent Script against H2 2.1.210

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13636]
**How to reproduce:**
Trying to do a migration from IS 5.11.0 GA to IS 5.12.0 Beta2. While getting 5.11.0 GA H2 Consent script executed getting below errors and therefore unable to try out the migration against H2 latest (2.1.210).

1. Get a external H2 database configured with docker . Ref https://hub.docker.com/r/oscarfonts/h2

```
I. docker pull oscarfonts/h2

II. docker run -d -p 1521:1521 -p 81:81 -v /path/to/local/data_dir:/opt/h2-data -e H2_OPTIONS=-ifNotExists --name=MyH2Instance oscarfonts/h2

III. docker logs -f MyH2Instance

IV. Access http://<ip>:81
```
2. Give a database name in the UI browser console for the H2 (eg:- test2. So a new database will be created as test2 when you click on connect 
3. Get the 5.11.0 GA pack from git
4. Execute the script dbscripts/consent/H2.sql against the H2 server 

Getting below Errors
![Screenshot from 2022-05-07 10-51-14](https://user-images.githubusercontent.com/31848014/167239742-f7338527-3117-4c35-a511-2acdcd32fc65.png)
![Screenshot from 2022-05-07 10-51-32](https://user-images.githubusercontent.com/31848014/167239748-aa12367d-6a0d-45ee-aa97-d04ddff36698.png)
![Screenshot from 2022-05-07 10-51-37](https://user-images.githubusercontent.com/31848014/167239753-4a3df665-c4e2-4a1c-b1e8-c2d7baa6eba4.png)

![Screenshot from 2022-05-07 10-51-41](https://user-images.githubusercontent.com/31848014/167239758-953b6ebb-e761-4061-9f40-e30d53deef2f.png)
![Screenshot from 2022-05-07 10-51-47](https://user-images.githubusercontent.com/31848014/167239760-30205b73-6ca3-45a5-9e3a-7c671d2fc9f6.png)

```
Syntax error in SQL statement "CREATE TABLE CM_PII_CATEGORY (\000d\000a  ID           INTEGER AUTO_INCREMENT,\000d\000a  NAME         VARCHAR(255) NOT NULL,\000d\000a  DESCRIPTION  VARCHAR(1023),\000d\000a  DISPLAY_NAME VARCHAR(255),\000d\000a  IS_SENSITIVE INTEGER      NOT NULL,\000d\000a  TENANT_ID    INTEGER DEFAULT '-1234',\000d\000a  UNIQUE [*]KEY (NAME, TENANT_ID),\000d\000a  PRIMARY KEY (ID)\000d\000a)"; expected "("; SQL statement:
CREATE TABLE CM_PII_CATEGORY (
  ID           INTEGER AUTO_INCREMENT,
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(1023),
  DISPLAY_NAME VARCHAR(255),
  IS_SENSITIVE INTEGER      NOT NULL,
  TENANT_ID    INTEGER DEFAULT '-1234',
  UNIQUE KEY (NAME, TENANT_ID),
  PRIMARY KEY (ID)
) [42001-210] 42001/42001 [(Help)](https://h2database.com/javadoc/org/h2/api/ErrorCode.html#c42001)

```
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
H2 2.1.210
IS 5.11.0 GA

**Comment by ashendes** [comment]
This is happening because H2 1.4.xx was used in 5.11.0 GA, hence, those are not compatible with H2 2.1.210.
These tables are getting created without an issue in their compatible DB versions.
5.11.0 GA - H2 1.4.xx heavy_check_mark
5.11.0 U2 updated - H2 2.1.210 heavy_check_mark
