### ISSUE TITLE
"Building Identity Server from Source" link in readme File is not working

### ISSUE THREAD

**Issue by cdwijayarathna** [wso2/product-is#1364]
"Building Identity Server from Source" link in the readme file of master branch is forwarding to a non-working page.

**Comment by omindu** [comment]
@cdwijayarathna We have just changed the default branch of product-is to 5.x.x branch which is the current active branch. Master branch will not be active until we continue the IS 6.0.0 work

**Comment by cdwijayarathna** [comment]
But I believe we need to have a comprehensive readme file if anyone wants to try out or contribute to 6.x.x version. WDYT?
