### ISSUE TITLE
Improve the pre validation step of ReCaptcha validation flow.

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#13642]
### **Issue Description**

When the Captcha is enabled for SSO login and the failed limit count is exceeded, the users from the secondary userstore are able to log in when the provided username does not have the userstore domain prepended to it.

 1. Login username:  secondary/test > captcha verification works as expected.
 2. Login username: test > users can proceed to log in without captcha verification.

### **Analysis** 

When  “Enable captcha after the max failed attempts”  feature  is enabled and maximum failed attempts count is configured, the number of failed login attempts of each user is captured and stored. This information is stored in the user claim http://wso2.org/claims/identity/failedLoginAttempts. 

Before the user is getting authenticated this count is evaluated as a part of the recaptcha pre-validation step. In there, it is accessing the user store to get claim value. Since the user is not authenticated at the time domain information of the user is not available. Passing only the username instead of domain qualified user name results to get the user store evaluated to the primary user store. Therefore, for secondary user store users, the user not found exception is thrown and the method is not returning the correct values. 

As a fix to the existing flow, to find the required user claim value, the whole chain of userstores has to be iterated to find the userstore of the user[1]. 

### **Improvement suggestion** 

Ths initial fix for this issue has been done via [1]. This will resolve the initial issue, but this will have more complications.
- Performance impact.
- Unable to handle the same username of users in multiple userstores.

The improvement should be not to store the failed attempts in the userstore. The ideal approach should be to add them to a separate identity database. With this approach, the pre listeners/handlers/ valves will be able to get the failed attempt counts without accessing the userstore. Also ,we need to implement a cache to improve the performance.

[1] - https://github.com/wso2/product-is/issues/13644

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
