### ISSUE TITLE
Backport ability to set temporary claim for user from the adaptive script

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#13656]
**Describe the issue:**
The ability to set temporary claim for user from the adaptive script was introduced on IS-5.11.0 with #9293.
This feature is available on IS-5.7.0 & IS-5.10.0 via updates, but it's not available for versions in the middle, e.g. IS-5.8.0 & IS-5.9.0

**How to reproduce:**
- Edit the Local & Outbound Authentication Configuration of a service provider.
- Change the Authentication on the Type to Advanced Configuration.
- Add basic authentication as first step.
- Change the Script Based Authentication as indicated below.
- Log in to the service provider.

```
var idclaim = "http://wso2.org/claims/externalid";

function onLoginRequest(context) {
    executeStep(1, {
        onSuccess: function(context) {
            var user = context.currentKnownSubject;
            user.claims[idclaim] = user.username + "_test";
        }
    });
}
```

**Expected behavior:**
Given that this feature is available for version 5.7.0 should be available for later versions as well.

**Environment information:**
 - Product Version: IS 5.8.0, IS 5.9.0

**Comment by rksk** [comment]
Already done for the development branch with https://github.com/wso2/product-is/issues/9293
