### ISSUE TITLE
MFA fail with Fido And TOTP

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13663]
**Describe the issue:**
Multi factor authentication is fail when Fido as 1st factor and TOTP as second factor.  
Error at console:

`ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Can not find the authenticated user `

https://user-images.githubusercontent.com/39077751/167816117-c1cdfbe5-cef6-4038-b750-712a6215dcfd.mov

**How to reproduce:**
1. Login to Management console
2. Create user
3. Login to my account with created user and register Fido
4. Login to Management console
5. Create application
6. Configure Fido as 1st authentication step and TOTP as second authentication.
7. Click update
8. Navigate to the application login page
9. Complete the 1st authentication step Fido 

**Expected behavior:**
TOTP page should prompt to complete the second authentication.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-beta
 - OS: MAC
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashensw** [comment]
The scenario is not reproducible in the latest pack (wso2is-5.12.0-beta3-SNAPSHOT). The flow is working as expected.


https://user-images.githubusercontent.com/13478571/168013333-1393a603-17ed-46c6-9050-b5ddd65ccd3f.mov
