### ISSUE TITLE
Use app id in internal redirection instead of app name 

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#13661]
In the login flow we can see that identity server redirects to the login pages and consent pages. During these redirections, we can see the relevant application name is passed in params. Since the application id is available we need to update these places to use the application id.

In the redirection to the login we can see the app name in the `sp` param and in the consent page we can see the app name in the `application` params (it is also good to make the two params consistent). There can be other flows that are using the app name in the params, need to do an analysis on this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
