### ISSUE TITLE
Password recovery error message is not meaningful  when user email is not set

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13671]
**Describe the issue:**
Password recovery error message is not meaningful  when user email is not set.

<img width="827" alt="Screenshot 2022-05-12 at 13 42 48" src="https://user-images.githubusercontent.com/39077751/168024441-afb47743-f5af-4d6f-bf60-a558293a0df4.png">

https://user-images.githubusercontent.com/39077751/168024516-567d2dd3-df3a-4a69-86ec-fb798b5ddb6f.mov

**How to reproduce:**
1. Login to console and create user. (don't update the email at user profile)
2. Create application.
3. Navigate to the Identity providers ->Resident IDP -> account recovery and enable password recovery
4. Login to the application
5. Click forgot password
6.  Enter username and send. 

**Expected behavior:**
Since the user doesn't  have valid email error message should be meaningful.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.12.0-beta2
 - OS: MAC
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Anandi-K** [comment]
This issue was not reproducible in the following environment.
```
Product version: WSO2 Identity Server 6.0.0 Alpha
OS: Linux
```
![Screenshot from 2022-06-29 17-33-10](https://user-images.githubusercontent.com/95691934/176432756-b858c525-5989-43e3-bd9b-34814f281a7b.png)
