### ISSUE TITLE
Identity Providers search filter in management console (UI) applies inconsistent filtering mechanism

### ISSUE THREAD

**Issue by Rod-yan** [wso2/product-is#13676]
**Description**:
Searching for an Identity Provider using the search filter bar on the IS's Management console (within Identity Providers tab) appears to be mandated by filter expressions (e.g. 'description co test_idp_1') instead of regex-based filtering as observed in other element's search filter bars, such as Users or Service Providers.

Attempting to apply any other search string that doesn't comply with filtering expressions (as conditioned by [this](https://github.com/wso2/carbon-identity-framework/blob/b26f147535feca0747208752db7552932d7a9edf/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/model/FilterTreeBuilder.java#L180) structure) will result in an Exception being thrown at the log level (see Complementary information), as well as a not very descriptive error message on the UI level. This impacts UX as well.

**Steps to reproduce**:
*Pre-conditions*:
1. 'test_idp_1' is registered as an Identity Provider on the Identity Server.

*Basic task flow*:
1. User logs into the management console and accesses "Identity Providers" List option.
2. User inputs 'test_idp_1' on the search bar at the top of the list screen.
3. System informs that there is no matches for this search
4. User reattempts (2) with value 'test*' (as seen in sample_1 bellow) and an error message (as seen in sample_2 bellow) is shown on the screen, then (3).

![sample_1](https://user-images.githubusercontent.com/7266710/168178327-63abac59-19fa-4618-932f-5364fa632cde.png)
(sample_1)
![sample_2](https://user-images.githubusercontent.com/7266710/168178341-ff6c1e56-9881-4fab-add7-078fdb95287a.png)
(sample_2)

*Notes*:
- Regarding point (2) of the abovementioned basic task flow, it is irrelevant which value it is used for filtering as long as it doesn't comply with any filtering expression.
- Regarding point (3), there is a small UI correction to be made when there are no matching entries. Currently, the message displayed says "No Service Providers registered", while this should be "No _Identity_ Providers registered"

**Expected behavior**:
Search filtering mechanism should be homogeneous between all system elements. IMO, search filtering mechanism should be based around regex-based filtering (as seen in Users or Service Providers), unless a specific filtering expression is explicitly used.

**Environment information**:
 - Product Version: IS 5.11.0.X (Reproduced in 5.11.0.0 and 5.11.0.134)
 - OS: Irrelevant
 - Database: Irrelevant
 - Userstore: Irrelevant

**Complementary information**:
Appending wso2carbon.log's exception as per printed after reproducing the scenario; [idp_search_error.log](https://github.com/wso2/product-is/files/8682953/idp_search_error.log)

**Comment by rksk** [comment]
Another related issue was observed. 

- Search for IdPs with `test*`
- You will observe the errors in logs and not get any results on the UI
- Once any link on the management console is opened an error popup comes with `Error while loading Identity Providers`

The error popup was not visible when the error occurred originally. but later when another page was loaded.
