### ISSUE TITLE
2-Factor authentication fail with Email TOTP

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#13675]
**Describe the issue:**

In Configuring Email OTP for 2-Factor Authentication,
When we set the basic as 1st Factor and EmailOTP as the second factor , the authentication flow fails after the 1st Factor  by redirecting back to the login page .

https://user-images.githubusercontent.com/40081059/168143111-d77065dd-6c9c-46f7-9038-def96ea1df5d.mov

_Error at console:_
` ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication Failed: Authenticator Properties may be null `

**How to reproduce:**

1.Login to Management console
2.Create application
3.Configure basic as 1st authentication step and OTP as second authentication.
4.Navigate to the application login page
5.Complete the 1st authentication step

**Expected behavior:**

1.An OTP should be send to the user mail.
2.OTP page should be prompt to enter the verification code  and to  complete the second authentication step.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.12-beta2]
 - OS: [Mac]
 - Database: [MySQL]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mpmadhavig** [comment]
Couldn't reporduce locally. Expected behaviour can be seen.

Environment information:

-  Product Version: IS 6.10.0
- OS: Mac
- Database: Postgres
- Userstore: jdbc


https://user-images.githubusercontent.com/47152272/212799853-c776a795-4a3e-46f6-bbee-f665bac98c52.mov
