### ISSUE TITLE
Some IdP's are not listed in the Console App

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#13684]
**Describe the issue:**
When we go to Identity Providers in the Console App, we only get the following items:

<img width="1127" alt="Screenshot 2022-05-13 at 15 11 58" src="https://user-images.githubusercontent.com/21237558/168276212-47674d3f-c707-4666-8a6e-c40bf0fd0339.png">

Twitter, Yahoo, Microsoft, etc. (available in the management console) are missing.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12  beta
 - OS: Mac

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
