### ISSUE TITLE
Disable cross tenant token introspection

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#13683]
**Describe the issue:**

If a token request is made to a specific tenant, the received token can be validated using the introspection endpoint of another tenant.

**How to reproduce:**

1. Create two tenants (tenant1,tenant2)
2. Get a valid token. (using tenant1 token endpoint and tenant1 admin credentials)

 ```
curl -u AQHA6ryTuJnZKjXQg2acOVGhLK4a:xdL3edyBa4iIwjqpEr8M7rojHpMa -k -d "grant_type=password&username=[tenant1@tenant1.com](mailto:tenant1@tenant1.com)&password=tenant1123" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/t/tenant1.com/oauth2/token?scope=openid
```

3. Validate the token.(using  tenant2 introspect url and tenant2 admin credentials)
Request:
```
curl -k -u tenant2@tenant2.com:tenant2123 -H 'Content-Type: application/x-www-form-urlencoded' -X POST --data 'token=a39da5c6-214f-31e9-8093-071908ac33b9' https://localhost:9443/t/tenant2.com/oauth2/introspect
```

Response:
```
{"nbf":1627474660,"scope":"openid","active":true,"token_type":"Bearer",
"exp":1627478260,"iat":1627474660,"client_id":"AQHA6ryTuJnZKjXQg2acOVGhLK4a","username":"[tenant1@tenant1.com](mailto:tenant1@tenant1.com)"}
```

**Expected behavior:**

the token should only be validated using tenant introspect endpoint and tenant admin credentials which were used to create the token.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
