### ISSUE TITLE
Config super tenant name

### ISSUE THREAD

**Issue by emilebui** [wso2/product-is#13685]
**Is your suggestion related to an experience ? Please describe.**
Currently, is there any way to change the super tenant name (from carbon.super to something else)

**Describe the improvement**
There should be a config in deployment.toml to configure the default super tenant name.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
