### ISSUE TITLE
Is the governance/configuration registry needed for HA?

### ISSUE THREAD

**Issue by espressobeanies** [wso2/product-is#1368]
**Description:**
I'm trying to see if the governance/configuration registry are needed for achieving WSO2 HA and how to fail those over if the machine they use goes down.

https://docs.wso2.com/display/CLUSTER44x/Sharing+Databases

**Comment by omindu** [comment]
@espressobeanies You need to share the the governance and configuration registries among the IS Nodes for HA.

**Comment by espressobeanies** [comment]
Thanks Omindu
