### ISSUE TITLE
SAML application does not correctly return the configured user attributes when using GitHub login

### ISSUE THREAD

**Issue by kayathiri4** [wso2/product-is#13701]
**Describe the issue:**
When using GitHub login in a SAML application, server does not correctly return the attributes configured in User Attribute section.  It returns all the attributes back to the application if the `email` attribute is not in the requested attributes list.

**Expected behavior:**
It should return only the requested attributes if there are any attributes requested and can return all the attributes from the IdP if none of the attrbutes are requested.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
