### ISSUE TITLE
Cache entry not cleared when an IdP resource is deleted by its id containing trailing spaces

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#13707]
**Describe the issue:**
When doing a REST API call to delete an IdP by its id (id is sent as a path parameter)
ex: `api/server/v1/identity-providers/<id>`
the current behavior in IdP management API is: 
- If there is a leading space in the id, then the resource will not be deleted. 
- If there are trailing spaces in the id, then the resource will be deleted. At the db level, trailing spaces are ignored. Hence the resource gets deleted. However in this case, there can be cache clearing issues (if there is a cache maintained with the cache key as the id) as the cache key doesn't ignore the trailing spaces. Hence there will not be a cache entry found that should be cleared. For example, if you try to add back an IdP with the same name as the deleted IdP resource, a 409 error response will be displayed.

**Expected behavior:**
Such cache clearing issues should not occur.

**Environment information:**
 - Product Version: IS 5.12.0 beta
 - OS: Mac
 - Database: H2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
