### ISSUE TITLE
Won't publish onPostTokenRevocationBySystem event when re-using auth code

### ISSUE THREAD

**Issue by VimukthiRajapaksha** [wso2/product-is#13702]
**Is your suggestion related to an experience ? Please describe.**
When the authorization code is reused, the identity server revokes all relevant access tokens. Still the tokens are present in the gateway cache. In order to remove the tokens from cache, the APIM requires the access token value, hence need to publish an event with access token IDs.

**Describe the improvement**
publish onPostTokenRevocationBySystem event with token ID when re-using auth code

**Additional context**
https://support-internal.wso2.com/jira/browse/OBINTERNAL-881

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
