### ISSUE TITLE
Typo in ID token expiry time in console app

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#13700]
**Describe the issue:**
Typo in ID token expiry time in console app
<img width="624" alt="Screenshot 2022-05-18 at 09 59 41" src="https://user-images.githubusercontent.com/17597293/168957461-d12e37e4-8b96-47df-97e7-0b031845f6c5.png">

`Id Token expiry time` should be changed to `ID Token expiry time`

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
