### ISSUE TITLE
Proper error message should be thrown when invoking getChallengeQuestionsOfUser of UserIdentityManagementAdminService when no challenge questions are configured for the user

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#1370]
**Description:**
Following exception is thrown when trying to get challenge questions of a user through UserIdentityManagementAdminService, where no challenge questions are configured. But proper message should be thrown in IS as well as proper message should be thrown in SOAP response.

```
    TID: [0] [IS] [2017-08-25 20:46:30,516] ERROR

    {org.wso2.carbon.identity.mgt.util.Utils} - Unable to retrieve the claim for user : user1 {org.wso2.carbon.identity.mgt.util.Utils}

    org.wso2.carbon.user.core.UserStoreException: org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : in user store : PRIMARY
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by IndunilRathnayake** [comment]
Added JIRA in https://wso2.org/jira/browse/IDENTITY-6453

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
