### ISSUE TITLE
UI string update for certificates section.

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#13710]
**Describe the issue:**
The text in the certificates section of the console app mentions that users can create and manage certificates in the Keystore, but there is no method to create a new certificate.

![image](https://user-images.githubusercontent.com/84217321/169199096-695de5c7-1ead-43b2-8e96-de6693709334.png)

**How to reproduce:**
1. Login to the IS console app.
2. Navigate to **Manage > User attributes > Certificates**.

**Expected behavior:**

**Environment information** 
 - Product Version: IS 15.12.0 - beta3

**Comment by ShanikaWickramasinghe** [comment]
Checked in IS 5.12.0 beta3 and observed the same behavior. AS there is no create facility under the certificates section we may need to change the headings accordingly

![Screenshot from 2022-05-19 16-37-27](https://user-images.githubusercontent.com/31848014/169279991-509dc227-2d8d-4700-b692-be91fa97985c.png)
