### ISSUE TITLE
Document Configuration Management API Changes for IS 6.0.0

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#13713]
**Is your suggestion related to a missing or misleading document? Please describe.**
In an recent effort, we have removed capability to manipulate configuration management resource types for the tenanted paths. Reason for this change is that the resource types are available globally across tenants and manipulating a resource type in one tenant could affect the other tenants. This behavior is by design and is documented [here](https://is.docs.wso2.com/en/latest/develop/using-the-configuration-management-rest-apis/)

**Describe the improvement**
We need to document on the improvement done (Resource types can only be manipulated by super tenant credentials)

**Related PR:**
- https://github.com/wso2/carbon-identity-framework/pull/3946

**Comment by ashensw** [comment]
This doc https://is.docs.wso2.com/en/latest/deploy/configure-email-sending/#configure-the-email-sender-per-tenant is also affected by this change. Shall we get the sample requests updated accordingly? @himeshsiriwardana

**Comment by himeshsiriwardana** [comment]
> This doc https://is.docs.wso2.com/en/latest/deploy/configure-email-sending/#configure-the-email-sender-per-tenant is also affected by this change. Shall we get the sample requests updated accordingly? @himeshsiriwardana

ack.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
