### ISSUE TITLE
MySQL DB scripts for IS 6.0.0-m1 are failing when indexes are created.

### ISSUE THREAD

**Issue by wenodpathirana** [wso2/product-is#13718]
**Describe the issue:**
When creating the tables/indexes in MySQL for identity database, some of them are failing due to following error. Issue is found in the db scripts provided in IS `6.0.0-m1` after introducing the new constraints/indexes.

`ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes` 

**How to reproduce:**
Create a MySQL database and apply the db scripts provided for identity in `$IS_HOME/dbscripts/identity/mysql.sql` and `$IS_HOME/dbscripts/identity/uma/mysql.sql`.

**Expected behaviour:**
Provided scripts should be creating the tables and indexes without any errors.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - Database: MySQL

**Comment by ShanikaWickramasinghe** [comment]
@wenodpathirana If you use mysql 8 then you need to create the database , with charset latin1,to avoid errors while executing db scripts. Can you please confirm whether you did that step

`create database regdb character set latin1;
`

**Comment by wenodpathirana** [comment]
@ShanikaWickramasinghe It was the mysql version 8 and scripts worked without any error after setting the `character set` to `latin1`.
