### ISSUE TITLE
Getting 404 when try to visit Console Manage Section and few sections are missing in console app against MSSQL 2019 (5.11.0 U2 148)

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13712]
**Describe the issue:**
1. Get IS 5.11.0 pack and update it for latest U2 level 148.
2. Configure MSSQL 2019 as the database type
3. Up the pack
4. Access console as admin:admin

```
[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:sqlserver://localhost:1433;databaseName=twlvmigr1;SendStringParametersAsUnicode=false"
username = "sa"
password = "xxxxx"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.identity_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
url = "jdbc:sqlserver://localhost:1433;databaseName=twlvmigr1;SendStringParametersAsUnicode=false"
username = "sa"
password = "xxxxxxxxxx"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.shared_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false
```

Service providers section is missing in console
When try to visit manage section in console getting a 404
Some sections in the manage section are also not visible
If you create a new tenant and login to console then no issue

https://user-images.githubusercontent.com/31848014/169253605-08da3c20-07cf-4c68-8203-01aa8229bac7.mp4

**Environment**
7.11.0 U2 updated with 148 level
MSSQL 2019

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
