### ISSUE TITLE
Remove con app key constraint(application:user:scope:binding) in token table

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#13714]
**Is your feature request related to a problem? Please describe.**
In our token issue logic, we always check whether there was already a token issued for application:user:scope:binding and if an active token is available in the database, then we always return that token rather than generating a new token. We are handling it with synchronized blocks in code and unique key constraints in the database.

The possible reason to have this logic should be to reduce the growth of the token table when an application is not properly handling the token request logic. So it won't have many advantages in properly implemented applications. 

The downside of this logic are,

- Issue a new token per device - If the user logins to the same application with the same scope to different devices, then we will return the same token. So if the user logs out from one device (revoke the token), the other device will also log out. 

To solve this, we have asked for a workaround to send a random scope per request and to use a custom token binding implementation. Both these are not proper usage of scope or token binding concepts. 

-  Performance downgrade - When we are issuing a token, there needs to be a token lookup to check for already issued tokens and unique constraints during token insert. 

In our server, when we have token hashing enabled or JWT token type is used, we are not following this unique constraint and always generating a new token. Because we can't regenerate the already issued token. And most of the identity providers didn't have this constraint as well. They return a new token for each request. 

**Complexities**
There are complexities in the token revoke part when we remove this constraint. Because we now consider only one active token available for the user:app:scope:binding and revoke only that token. But with this change, we need to revoke all the tokens. So we need to have a major refactoring needed to those flows.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
