### ISSUE TITLE
Update missing property configurations in `SMSOTP` documentation

### ISSUE THREAD

**Issue by yasinmiran** [wso2/product-is#13719]
**Is your suggestion related to a missing or misleading document? Please describe.**
Authenticator `SMSOTP` related configurations are missing in our latest docs. For example: -
```xml
    <Parameter name="TokenExpiryTime">30</Parameter>
    <Parameter name="TokenLength">8</Parameter>
```

**Describe the improvement**
Synch the relevant [documentation section](https://is.docs.wso2.com/en/latest/learn/configuring-sms-otp/#) to match https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/master/docs/config.md

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
