### ISSUE TITLE
Configure issuer tenant wise in TOTP authenticator

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#13722]
As per the implementation of the getTOTPIssuerDisplayName [1] method which is used to set the issuer, if the issuer is not configured in the deployment.toml file, it will pick the tenant domain as the issuer.

If multiple separated environments have been deployed, and if the user is present on multiple env with the same name or if there is a tenant on every deployment with the same name, it might be problematic to find which TOTP code should be used for the particular env.
Therefore, Its is better if there's a way to configure addtional parameters for issuer
ex:-
Issuer=[domain_name][tenant_domain] (user name)

[1] -https://github.com/wso2-extensions/identity-outbound-auth-totp/blob/b08564766bef8c42b0123f19da7ab6dd16e75450/component/authenticator/src/main/java/org/wso2/carbon/identity/application/authenticator/totp/util/TOTPUtil.java#L99

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
