### ISSUE TITLE
WSO2 not start

### ISSUE THREAD

**Issue by faizanshah512** [wso2/product-is#13736]
**Describe the issue:**
before 6 month ago I installed wso2 identity server 5.11 in ubuntu machine and  migrates it is embedded database to oracle 
following this link https://is.docs.wso2.com/en/5.9.0/setup/changing-to-oracle/ every thing running is fine I insert 34,000 thousand unique users and create roles and permissions assign roles to permissions and also assign users to role in bulk using cronjob
but now I face the issue when I click the role management tab and want to see list of roles but the page showing empty page after checking the console the error is show like this so i restart the wso2 identity server the wso2carbon.log file show errors like this
[2022-05-24 14:24:57,608] [] FATAL {org.wso2.carbon.registry.core.session.UserRegistry} - Failed to add the root collection to the coreRegistry. org.wso2.carbon.registr                                                                     y.core.exceptions.RegistryException: Failed to get ID of the resource at path /. Table "REG_PATH" not found; SQL statement:
SELECT REG_PATH_ID FROM REG_PATH WHERE REG_PATH_VALUE=? AND REG_TENANT_ID=? [42102-199]
"i already created the table and dont know what is the reason behind this now  and also wso2 is not running ,before two or three days wso2 identity server running with this error but not running now, so i reboot it many times but wso2 identity server not running and i face the error above which i mention  "
"Please anybody help me"

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0]
 - OS: [e.g. Linux, Mac]
 - Database: [e.g., Oracle, H2]
 - Userstore: [e.g., Oracle, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Namjoofar** [comment]
I had same problem too. I had to delete wso2 IS and install again! I think this is a bug in wso2 IS 5.11.0.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
