### ISSUE TITLE
Enterprise Login Management

### ISSUE THREAD

**Issue by vinumaddumage** [wso2/product-is#13731]
**Description:**
With the B2B Organization Management(#13658) feature an organization should be capable of sharing applications with other organizations to provide B2B services. To provide this, organizations should have the option to share an application with another organization, allowing users of that organization to login to the application to benefit from the services it provides.

The ability to configure applications such that they can be shared with organizations and to authenticate users of organizations that the application has been shared with are requirements that need to be addressed to allow an application to be shared as a resource across organizations.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
