### ISSUE TITLE
Test and rewrite `branding` section in `Customizing MyAccount UI`

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#13730]
The content on customizing the My Account UI in WSO2 IS is as follows in IS 5.11 [1]. Note that we have removed the content on `changing the branding` that was available for 5.10 [2]. 

In 5.10, the branding changes can also be tested in the dev environment. However, this process needs to be investigated and the content needs to be rewritten for 5.11.0.

[1] https://is.docs.wso2.com/en/latest/develop/customizing-my-account-ui/
[2] https://is.docs.wso2.com/en/5.10.0/develop/customizing-user-portal-ui/#step-2-changing-the-branding

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
