### ISSUE TITLE
Apply XACML policies were failed 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13739]
**Describe the issue:**
Following behaviors can be observed in xacml policy scenarios.

**Issue 01:**
Given policy templated are not working in tryout but when create new policy and it work on tryout.

Try out with given policy
<img width="800" alt="Screenshot 2022-05-25 at 07 26 15" src="https://user-images.githubusercontent.com/39077751/170162970-6ad9b85c-b300-42a5-8b8b-2e2f0d8830e5.png">

https://user-images.githubusercontent.com/39077751/170163076-d177d806-9ce0-4456-961a-aaa6da45b725.mov

Tryout with new Policy created according to the document https://is.docs.wso2.com/en/latest/learn/fine-grained-authorization-with-xacml/
<img width="728" alt="image" src="https://user-images.githubusercontent.com/39077751/170164116-8cda3c64-1749-4e5b-9990-677b0b5e5bb3.png">
 

**Issue 02:**
Apply policy for application, failed the authentication. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/39077751/170173978-fafdda2e-21a0-4789-9035-7a8cd45b68dc.png">

**How to reproduce:**
Issue 01: 
1. Login to the management console
2. Navigate to policy administration and select the tryout in authn_time_based_policy_template
3. Add Resource as SP_NAME, Subject name as 10.00.00 and Action name as authenticate
4. Click test evaluate

Issue 02: 
1. Login to the management console
2. Navigate to policy administration and create policy according to the steps in document https://is.docs.wso2.com/en/latest/learn/fine-grained-authorization-with-xacml/
3.  select the tryout in created policy and tryout
4. Publish the policy
5. Create users and SP
6. Login to application with different permitted users

**Expected behavior:**
Issue 01:
According to the policy application authentication allows to time between 9.00.00-17.00.00. Hence 10.00.00 it should permit the authetication. 

Issue 02:
Permitted users should be authenticate and others should be deny. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Reason for the issue2:

We changed the role claim to `http://wso2.org/claims/roles`. But these are not changed in the XACML policy. Also for role-based authentication, the role should be an internal/role. Other PRIMARY roles created from management console are treated as groups underline.

**Comment by piraveena** [comment]
**Reason for issue1**

**Role-based authentication control XACML policy**

```
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"  PolicyId="authn_role_based_policy_template_group" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
   <Description>This policy template provides ability to authorize users to a given service provider(defined by SP_NAME) in the authentication flow based on the roles of the user (defined by ROLE_1 and ROLE_2). Users who have at least one of the given roles, will be allowed and any others will be denied.</Description>
   <Target>
      <AnyOf>
         <AllOf>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">saml2-web-app-pickup-dispatch.com</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/identity/sp/sp-name" Category="http://wso2.org/identity/sp" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false"></AttributeDesignator>
            </Match>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">authenticate</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/identity/identity-action/action-name" Category="http://wso2.org/identity/identity-action" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false"></AttributeDesignator>
            </Match>
         </AllOf>
      </AnyOf>
   </Target>
   <Rule Effect="Permit" RuleId="permit_by_roles">
      <Condition>
         <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:or">
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">ROLE_1</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/claims/groups" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"></AttributeDesignator>
            </Apply>
         </Apply>
      </Condition>
   </Rule>
   <Rule Effect="Deny" RuleId="deny_others"></Rule>
</Policy>        
```
When you click `Try`, the XACML request will be sent as given below:

```
<Request xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" CombinedDecision="false" ReturnPolicyIdList="false">
<Attributes Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource">
<Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">saml2-web-app-pickup-dispatch.com</AttributeValue>
</Attribute>
</Attributes>
<Attributes Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject">
<Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:subject:subject-id" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">user2_role2</AttributeValue>
</Attribute>
</Attributes>
<Attributes Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action">
<Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">authenticate</AttributeValue>
</Attribute>
</Attributes>
</Request> 
 ```

If you compare the Role-based authentication control XACML policy and the XACML request sent by the editor, you can see that the attribute catoegories are different. 
The `Try` it tool creates a XACML policy with resource, action and subject categories. But the Role-based authentication control XACML policy contains some custom attribute categories. So when the try it tools sends the request, XACML policy engine is not able to find any policies matching to that request in the PAP.

> Tryout with new Policy created according to the document https://is.docs.wso2.com/en/latest/learn/fine-grained-authorization-with-xacml/

This is becuase, we are creating a new XACML policy with contains resource, action and subject attribute categories. The Try it tools always create request with defined resource, action and subject categories. If we want to create XACML request with custom attribute categories such as `http://wso2.org/identity/sp`, you should use the editor and create the request manually.
