### ISSUE TITLE
Fine grained access conroles documents steps contains different users.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13738]
**Is your suggestion related to a missing or misleading document? Please describe.**
Fine grained access conroles [documents](https://is.docs.wso2.com/en/latest/learn/fine-grained-authorization-with-xacml/) users are different. At the beginning of the document it mentioned set of users and end of the steps it uses different set of users. This is confusing. 
Beginning of the doc
<img width="742" alt="image" src="https://user-images.githubusercontent.com/39077751/170152413-d27b93c1-229a-4d68-8483-8ffd22f010eb.png">

And at the ned uses, Jane, Richard, john
 

**Describe the improvement**
Use the same set of user name at the example and description

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
