### ISSUE TITLE
Access Token contains incorrect scopes wrt roles of the user

### ISSUE THREAD

**Issue by RekhaShivSan** [wso2/product-is#13734]
JWT access token does not contain required scopes wrt to the roles assigned to the user.
Role validation of the user is not happening during JWT token generation. All the scopes passed during token generation are been granted to the user without validating user roles.

When we generate JWT access token for a user say "operator" with only "view_role" by passing all the created scopes in the token api body like 'scope=openid,create_scope, view_scope, edit_scope'.
In token api response able to all the scopes which are passed during token generation.

The issue is seen only on a HA setup not on single node setup.

Token Api curl:
curl --location --request POST 'https://x.x.x.x/token'
--header 'Content-Type: application/x-www-form-urlencoded'
--data-urlencode 'grant_type=password'
--data-urlencode 'password=xyz@123'
--data-urlencode 'username=[abc@tenant.com](mailto:abc@tenant.com)'
--data-urlencode 'client_id=xxxxxx'
--data-urlencode 'client_secret=xxxxxx'
--data-urlencode 'scope=openid operator_access_scope admin_access_scope creater_access_scope adaptor_admin_access_scope

*Steps to reproduce:
Create different scopes associated with Roles(Ex: "create_scope" with "create" role associated, similarly edit_scope, view_scope) in publisher portal( APIM 3.2).
Create new user with only "view" role assigned.
Generate JWT access token by passing all the scopes in the body (scope = openid, create_scope edit_scope view_scope)
Notice that all the scopes passed during token generation are granted even though user has only "view" role and only view_scope has to granted for the user.

**Expected behavior:**
Only those scopes associated with the user roles should be granted in the generated JWT access token.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
 - OS:  CentOS Linux 7
 - Database: Postgres
 - Userstore: OpenLDAP

**Comment by RekhaShivSan** [comment]
Is this issue being checked? Is it a new issue or fixed in other version of identity server ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
