### ISSUE TITLE
ERROR in outbound provisioning with SCIM while updating or deleting the user in management console

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#13744]
**Describe the issue:**

**Issue 1**

When a user is provisioned to a SCIM supported system from a WSO2 Identity Server, updating the user profile in the identity server management console does not update the user details in secondary Identity server and results in error in logs

<img width="1512" alt="provision-issue" src="https://user-images.githubusercontent.com/59327626/170199396-850066a7-c6ce-443a-b0c8-a8e9089d3419.png">

https://user-images.githubusercontent.com/59327626/170199642-2c928c92-b945-40af-b249-b3349d6f550e.mov

**How to reproduce:**

1. Get IS 6.0.0-m1 pack and set up and configure outbound SCIM provisioning with following [steps](https://is.docs.wso2.com/en/latest/learn/outbound-provisioning-with-scim/#:~:text=This%20topic%20provides%20instructions%20on,%2C%20another%20Identity%20Server%2C%20etc.).
2. Get another similar IS pack (Secondary IS) and enable inbound scim provisioning via Management Console > Main > Service Providers > Resident > Inbound Provisioning Configuration > select PRIMARY > Update.
3. Add a user in the first IS
4. Update user's details via editing user profile in management console 

**Expected behavior:**

User details in secondary IS are updated without errors

**Issue 2**

<img width="1512" alt="delete user" src="https://user-images.githubusercontent.com/59327626/170202409-642ff5a9-160e-4a77-a3a5-474fff28b682.png">

https://user-images.githubusercontent.com/59327626/170202425-a27b7d37-0d38-4498-9cc3-c7af3ed74f78.mov

**How to reproduce:**

1. Add a user in the first IS
2. Delete the user in first IS in management console 

**Expected behavior:**

User is deleted in secondary IS without errors

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.4
 - JDK: Oracle JDK 11.0.15.1

---

**Comment by asha15** [comment]
Thanks for reporting. The above mentioned issue cannot be reproduced.

Please fellow the steps specified in the documentation: https://is.docs.wso2.com/en/latest/learn/outbound-provisioning-with-scim
