### ISSUE TITLE
User self registration is visible though it was disabled from super tenant

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#13743]
**Describe the issue:**
In 5.11.0 pack user self registration feature is still available in myaccount login page though it was disabled from super tenant. when a user tries to register it throws ‘self registration is disabled for tenant - carbon.super’ error.

https://user-images.githubusercontent.com/28682701/170188287-09e56f6d-4aa8-4206-be1c-beffb6f9faa2.mp4

**How to reproduce:**
1. Login to the admin console.
2. Navigate to the Manage->User onboarding.
3. Disable user self registration under self registration.
4. Navigate to the my account https://localhost:9443/myaccount 

**Expected behavior:**
Since the user self registration feature was disabled in super tenant, it shouldn’t be available in myaccount login page. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS:  Linux
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
