### ISSUE TITLE
Delete a secondary user store giving an invalid user store domain id 

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13746]
**Describe the issue:**
When try to delete a secondary user store using invalid user store domain id using REST API (https://localhost:9443/t/carbon.super/api/server/v1/userstores/{userstore-domain-id}) does not gives expected 404 as response. Instead gives 204 or 500.

<img width="1281" alt="Screenshot 2022-05-25 at 13 36 19" src="https://user-images.githubusercontent.com/38417165/170213180-4796e79c-a494-4575-a6a9-7dcea9df9e1e.png">

<img width="1281" alt="Screenshot 2022-05-25 at 13 38 09" src="https://user-images.githubusercontent.com/38417165/170213972-f487d37d-f622-4165-8fd6-17044b6d00b1.png">

**How to reproduce:**
1. Create a secondary user store.
2. Extract user store domain id.
3. Send a DELETE request to https://localhost:9443/t/carbon.super/api/server/v1/userstores/{userstore-domain-id}.

**Expected behavior:**
Delete a secondary user store giving an invalid user store domain id should give 404.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.1
 - JDK: Oracle JDK 11.0.15

**Comment by ShanikaWickramasinghe** [comment]
Please check asgardeo - product repository issue id 9266 when the fixing team addressing this issue.
