### ISSUE TITLE
Identity Providers search filter in management console

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#13742]
**Describe the improvement**

Searching for an Identity Provider using the search filter bar on the IS's Management console will only support the following types of regex and it will not support complex regex patterns `(ex:-My*idp*test)`.

The IDP that is named as `MyIdpNew` can get from the following search filters
- `MyIdp*`
- `*IdpNew`
- `*idp*`
- `MyIdpNew`

These supported regex needs to be properly documented.

Related issue: https://github.com/wso2/product-is/issues/13676

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
