### ISSUE TITLE
Error in SAML Single Log Out (POST Binding)

### ISSUE THREAD

**Issue by nirmal101** [wso2/product-is#13758]
**Describe the issue:**

- Single Log out with SAML not working for the 2 applications saml2-web-app-pickup-dispatch and saml2-web-app-pickup-manager even though Single Sign On works without issue. 
- Issue is common for users in both primary and secondary user stores.

**How to reproduce:**

1.  Log in to web app 1 (saml2-web-app-pickup-dispatch) app using the credentials of a user in primary or secondary user store.
2.  SSO will allow automatic signing in to the web app 2 (saml2-web-app-pickup-manager).
3.  Sign out of web app 1.
4. Go to web app 2 home page and refresh the page.
5. User will not be logged out of web app 2.

**Expected behavior:**

- User should be automatically logged out of web app 2 when he logged out of web app 1.

https://user-images.githubusercontent.com/43103902/170529674-cc958f4b-deed-4a79-8ea0-e98fa788733c.mov

**Environment information** 
 - Product Version: IS 6.0.0
 - OS: Mac OS 12.4
 - Database: MySQL 8.0.29
 - User store: Primary and Secondary
 - Browser: Firefox 91.0

---
PS:- Even though refreshing the web app 2 page won't log out the user, you can go to the login page manually using the URL. From there, user credentials will be requested again to sign in to the app.

**Comment by piraveena** [comment]
Since these are back-channel logouts, apps doesn't logout automatically. Becuase, back-channel logouts are received by the backend. Frontend needs to talk to back-end and logout the app. SAML pickup-dispatch and pickup-manager don't have the support for that yet. We can implement some polling mechanism and logout the app automatically.

If you try to go to index.jsp and click there, you will be prompted with login page when the other app is logged out.

**Comment by aaptl** [comment]
@piraveena do we have any example for corss protocal logout, i have checked pickup dispatch(OIDC) and pickup manager(smal) app with the wso2 6.0.0 , here also single logout not working.
Even though refreshing the app page won't log out the user.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
