### ISSUE TITLE
Input Params are Case Sensitive when Filtering Users from Secondary User Store with SCIM2 API

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13751]
**Describe the issue:**
Input parameter values are case sensitive when filtering users in secondary user store with SCIM2 API but they are not case sensitive when filtering users in primary user store with SCIM2 API.

Request 1:
`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=name.familyName+sw+K'`

Response 1:
`{
    "totalResults": 2,
    "startIndex": 1,
    "itemsPerPage": 2,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "meta": {
                "created": "2022-05-26T05:24:32.609Z",
                "location": "https://localhost:9443/scim2/Users/2311b828-012d-4734-b656-943a29f44307",
                "lastModified": "2022-05-26T05:24:32.609Z",
                "resourceType": "User"
            },
            "roles": [
                {
                    "display": "everyone"
                }
            ],
            "name": {
                "givenName": "tom",
                "familyName": "Kris"
            },
            "id": "2311b828-012d-4734-b656-943a29f44307",
            "userName": "POSTGRESQL/tom"
        },
        {
            "meta": {
                "created": "2022-05-24T08:58:53.475Z",
                "location": "https://localhost:9443/scim2/Users/a5548c4c-52af-4ebf-b08b-a90907240f8f",
                "lastModified": "2022-05-24T08:58:53.475Z",
                "resourceType": "User"
            },
            "roles": [
                {
                    "display": "everyone"
                }
            ],
            "name": {
                "familyName": "Kris"
            },
            "id": "a5548c4c-52af-4ebf-b08b-a90907240f8f",
            "userName": "Kris"
        }
    ]
}`

Request 2:
`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=name.familyName+sw+k'`

Response 2:
`{
    "totalResults": 1,
    "startIndex": 1,
    "itemsPerPage": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "meta": {
                "created": "2022-05-24T08:58:53.475Z",
                "location": "https://localhost:9443/scim2/Users/a5548c4c-52af-4ebf-b08b-a90907240f8f",
                "lastModified": "2022-05-24T08:58:53.475Z",
                "resourceType": "User"
            },
            "roles": [
                {
                    "display": "everyone"
                }
            ],
            "name": {
                "familyName": "Kris"
            },
            "id": "a5548c4c-52af-4ebf-b08b-a90907240f8f",
            "userName": "Kris"
        }
    ]
}`

**How to reproduce:**
1. Create a secondary user store
2. Create a new user in primary user store with familyName="Kris"
3. Create a new user in secondary user store with familyName="Kris"
4. Send a filter request to get all users whose familyName starts with simple 'k' trough a SCIM2 API call (https://localhost:9443/scim2/Users?filter=name.familyName+sw+k)

**Expected behavior:**
Both users with familyName="Kris" should be in the response but only the user stored in the primary user store will be retrieved.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: Primary user store is in LDAP and secondary user store is in PostgreSQL

**Comment by ImalshaG** [comment]
By default PostgreSQL and Oracle databases are case-sensitive while other databases are case-insensitive. Therefore above behaviour is seen when the userstores are configured using PostgreSQL or Oracle DBs. 
Case-sensitivity of search queries can be altered by changing the collation properties of the database as per the user requirement.

Since these databases are created and maintained by the users, if a user needs the search queries to be case-sensitive/insensitive they can alter the database properties as required. 

This does not require a fix from the product-is side and can be configured from database properties. Hence, closing the issue.
