### ISSUE TITLE
Update secondary user store by using it's domain id 

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13761]
**Describe the issue:**
When try to update a secondary user store using user store domain id using REST API ([https://localhost:9443/t/carbon.super/api/server/v1/userstores/{userstore-domain-id}](https://localhost:9443/t/carbon.super/api/server/v1/userstores/%7Buserstore-domain-id%7D))  gives expected 200 as response. 

<img width="1512" alt="Screenshot 2022-05-26 at 15 06 30" src="https://user-images.githubusercontent.com/38417165/170630449-2eaaa6bb-8fc2-45af-befc-8acb703c23aa.png">

But when tries to retrieve that updated store it's not there in the store list.

<img width="1512" alt="Screenshot 2022-05-26 at 15 06 59" src="https://user-images.githubusercontent.com/38417165/170630477-188a3078-4183-4811-b493-a30c988699e1.png">

**How to reproduce:**

1. Create a Secondary user store.
2. Extract user store domain id.
3. Send a PUT request to [https://localhost:9443/t/carbon.super/api/server/v1/userstores/{userstore-domain-id}](https://localhost:9443/t/carbon.super/api/server/v1/userstores/%7Buserstore-domain-id%7D).
4. Then send a GET request to [https://localhost:9443/t/carbon.super/api/server/v1/userstores](https://localhost:9443/t/carbon.super/api/server/v1/userstores) to check available stores.

**Expected behavior:**
Update secondary user store property by using it's domain id with an authorized user should succeed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.1
 - JDK: Oracle JDK 11.0.15

**Comment by ImalshaG** [comment]
Tested in the latest IS-6.0.0-m3 pack. The above issue is not reproducible. Hence, closing the issue.
