### ISSUE TITLE
Sub-Attributes of Complex Attributes Are Not Supported in SCIM2 User Creation

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13770]
**Describe the issue:**
User creation with SCIM 2.0 API doesn't store some sub-attributes of complex multi-valued attributes. As an example, it stores only _formatted_ and _type_ sub-attributes of _addresses_ attribute. But it doesn't store sub-attributes such as _country, postalCode, streetAddress, primary, locality, region_.

These sub-attributes of _addresses_ attribute are supported in SCIM2 as mentioned in [RFC 7643](https://datatracker.ietf.org/doc/html/rfc7643) and [RFC 7644](https://datatracker.ietf.org/doc/html/rfc7644).

Request:
`curl -v -k --user admin:admin --data '{"schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"], "name": { "familyName": "perera", "givenName": "ravindu" }, "userName": "ravinduperera", "password": "ravindu123", "emails": [ { "primary": true, "value": "sampleemail@gmail.com", "type": "home" }, { "value": "ravindur@wso2.com", "type": "work" } ], "addresses": [ { "type": "home", "country": "UK", "postalCode": "10511", "streetAddress": "221b Baker St", "locality": "London NW1 6XE", "region": "London", "formatted": "221b Baker St, London NW1 6XE, United Kingdom", "primary":true }, { "type": "work", "streetAddress": "20 Palm Grove", "region": "Colombo 3", "country": "Sri Lanka", "postalCode": "00300", "formatted": "20 Palm Grove, Colombo 03, Sri Lanka" } ]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

Response:
`{
    "emails": [
        {
            "type": "work",
            "value": "ravindur@wso2.com"
        },
        {
            "type": "home",
            "value": "sampleemail@gmail.com"
        }
    ],
    "addresses": [
        {
            "formatted": "20 Palm Grove, Colombo 03, Sri Lanka",
            "type": "work"
        },
        {
            "formatted": "221b Baker St, London NW1 6XE, United Kingdom",
            "type": "home"
        }
    ],
    "meta": {
        "created": "2022-05-30T04:18:06.795Z",
        "location": "https://localhost:9443/scim2/Users/61bd1d95-c344-483f-875d-72e2fe707855",
        "lastModified": "2022-05-30T04:18:06.795Z",
        "resourceType": "User"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        "urn:scim:wso2:schema"
    ],
    "roles": [
        {
            "display": "everyone"
        }
    ],
    "name": {
        "givenName": "ravindu",
        "familyName": "perera"
    },
    "id": "61bd1d95-c344-483f-875d-72e2fe707855",
    "userName": "ravinduperera"
}`

<img width="690" alt="Screenshot 2022-05-30 at 09 54 47" src="https://user-images.githubusercontent.com/12953762/170916905-370e3a0d-3d42-4841-952a-19fcfca81876.png">

**How to reproduce:**
1. Create a new user through SCIM2 API call with _addresses_ attribute including sub-attributes such as _country, postalCode, streetAddress, primary, locality, region_  and _primary_ 

**Expected behavior:**
The response should contain all the sub-attributes mentioned in the user creation request but it returns only _formatted_ and _type_ sub-attributes in the _addresses_ complex attribute.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: This issue happened when using the primary user store in LDAP as well as when using the secondary user store in PostgreSQL 14.

**Comment by Anandi-K** [comment]
This can be achieved by adding this configuration to `deployment.toml`.
```
[scim2]
enable_complex_multivalued_attribute_support="true"
```
And we need to manually create a list of claims as well. Please refer https://github.com/wso2-enterprise/asgardeo-product/pull/7093#issue-1005132787
