### ISSUE TITLE
Param Values of SCIM2 API Role Creation Requests Are Case Sensitive

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13775]
**Describe the issue:**
displayName param values are case sensitive as it allows to create 2 different roles with role names: 'testRole' and 'TestRole' through SCIM2 Role Creation API Endpoint.

**How to reproduce:**
1. Create a role with displayName="testRole"
2. Create a role with displayName="TestRole"

**Expected behavior:**
Expected to return 409 error as role is already existed but it creates a new role and returns 201 status code.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Related issues:**
There's a [previously reported issue](https://github.com/wso2/product-is/issues/9285) related to this issue and [a comment in that issue](https://github.com/wso2/product-is/issues/9285#issuecomment-694792633) says it should be case insensitive if we use embedded LDAP as the user store.

**Comment by Anandi-K** [comment]
This requirement is not valid. 
Unlike `groups`, `roles` are created in DB, not in user store. Therefore case sensitivity of the roles depend on the case sensitivity of the used DB. Here, as the used DB (PostgreSQL) is case sensitive, the role creation will also be case sensitive. The [mentioned comment](https://github.com/wso2/product-is/issues/9285#issuecomment-694792633) is referring to groups.
