### ISSUE TITLE
Add Run In Postman facility to all REST APIs

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13773]
**Is your suggestion related to a missing or misleading document? Please describe.**

**Run In Postman** is a facility provided in documentation to import REST APIs as a collection to Postman. This facility is only provided in some REST APIs only.

**Describe the improvement**

Below figure shows  **Run In Postman**  feature in claim management REST API guideline (https://is.docs.wso2.com/en/latest/develop/claim-management-rest-api/). Similar to it **Run In Postman** facility needs to be included in each REST APIs to increase the usability when using the documentation. 

<img width="1499" alt="Screenshot 2022-05-30 at 12 12 07" src="https://user-images.githubusercontent.com/38417165/170932478-4e8a309e-33a6-42f6-9153-e64a81fb2985.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
