### ISSUE TITLE
Deleting non-existing Email-template gives 204 as the status code

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13782]
**Describe the issue:**
When try to delete a Email-template type using non existing id with REST API ([https://localhost:9443/t/carbon.super/api/server/v1/email/template-types/{Invalid-template-type-id}](https://localhost:9443/t/carbon.super/api/server/v1/email/template-types/aWRsZUFjY291bnRSZW1pbmRlcgh)) does not gives expected 404 as response. Instead it gives 204.

<img width="1512" alt="Screenshot 2022-05-31 at 13 01 59" src="https://user-images.githubusercontent.com/38417165/171131222-bba963ff-0ecd-48ac-900a-e764fa8ca2be.png">

**How to reproduce:**

Send a DELETE request to  https://localhost:9443/t/carbon.super/api/server/v1/email/template-types/{Invalid-template-type-id}. Here replace invalid-template-type-id with dummy value.

**Expected behavior:**

Delete non existing Email-template type should give 404.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.1
 - JDK: Oracle JDK 11.0.15

**Comment by ashensw** [comment]
Hi @AnjanaSamindraPerera,

The APIs in IS are designed as below,

> First DELETE: resource is deleted -> 204
> 
> Subsequent DELETEs: resource is already deleted or does not exist -> 204.
> 
> Rationale: DELETE should be idempotent. If you return 404 on a second DELETE, your response is changing from a success code to an error code. The client program may take incorrect actions based on the assumption the DELETE failed.

Therefore we can consider this as the expected behavior.
