### ISSUE TITLE
DOM XSS Vulnerabilitty in login page

### ISSUE THREAD

**Issue by emilebui** [wso2/product-is#13789]
**Describe the issue:**
XSS vulnerability at /authenticationendpoint/login.do endpoint. the portal takes input in url params (tenantDomain, relyingParty or sessionDataKey) to generate javascript code. The attacker can use this to execute Javascript code in victim machine.

**How to reproduce:**
Go to url: https://localhost:9443/authenticationendpoint/login.do?tenantDomain=carbon%2esup
er%22%2balert%28123%29%2c%2f%2f379

An alert popup would show up (Javascript code executed)

**Expected behavior:**
Javascript code should not be executed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Windows
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
