### ISSUE TITLE
Role Management Feature for Organization Management

### ISSUE THREAD

**Issue by nipunaupeksha** [wso2/product-is#13787]
**Description:**
With the B2B Organization Management feature([#13658](https://github.com/wso2/product-is/issues/13658)) an organization should have roles that can be assigned to the users inside of an organization. To facilitate that, a role management feature is needed in the organization management.

**Comment by nipunaupeksha** [comment]
#url(https://github.com/wso2-extensions/identity-organization-management/pull/26)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
