### ISSUE TITLE
Attribute Consuming Service Index in SAML2 supported federated IDP does not get validated

### ISSUE THREAD

**Issue by yogyagamage** [wso2/product-is#13780]
**Describe the issue:**

Attribute Consuming Service Index in SAML2 supported federated IDP does not get validated.

**How to reproduce:**

- Configure a SAML2 supported federated IDP
- Add a number (any random number other than the correct index) as the Attribute Consuming Service Index 

<img width="938" alt="Screenshot 2022-05-31 at 10 46 06" src="https://user-images.githubusercontent.com/47789154/171097975-4f8b2483-a8e8-4bb3-b456-ac2ec4691403.png">

- SSO with identity federation will work without an error

**Expected behavior:**

Incorrect attribute consuming service indexes should throw an error.

**Environment information:** 
 - Product Version: IS 6.0.0
 - OS: Mac
 - Database:  H2

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
