### ISSUE TITLE
Unable to Create a Role in The Secondary User Store Through SCIM 2.0 API

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13781]
**Describe the issue:**
When a request to create a role in secondary user store is sent, it sends a response with 201 status code showing that the new role is created.

Request:
`curl --location --request POST 'https://localhost:9443/scim2/Roles' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "displayName": "POSTGRESQL/pm",
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:2.0:Role"
    ]
}'`

Response:
<img width="716" alt="Screenshot 2022-05-31 at 13 28 12" src="https://user-images.githubusercontent.com/12953762/171122763-724b909f-a3cd-416d-85ce-7ee76217d05e.png">

Although the response says that it has created a new role with displayName="POSTGRESQL/pm", it doesn't create a new row in the "um_role" table in the secondary user store database. _Note that my secondary US domain name is POSTGRESQL_.

The newly created role is shown in the management console, but when I try to delete it through management console, it shows the following error.
<img width="797" alt="Screenshot 2022-05-31 at 12 06 59" src="https://user-images.githubusercontent.com/12953762/171108267-ff9bd541-39d0-4c45-8c1b-1bf6e31e3a80.png">

**How to reproduce:**

1. Create a new role in secondary user store via SCIM 2.0 API
2. Check whether it's store in the "um_role" table in the secondary user store
3. Check whether the newly created role is shown in the management console
4. Delete the new role through management console

**Expected behavior:**
The newly created role should be appeared as a new row in the secondary user store but it's not saved in the secondary user store.
If the domain (user store) is invalid, it should prevent creating a new role via SCIM 2.0 API and it should not be listed in the management console.

**Environment information:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL1 14
 - Userstore: JDBC with POstgreSQL 14 DB

**Comment by ashensw** [comment]
There is no valid use case to create Roles in user stores. It will be grouped that you can create in userstores. In this case, another internal role will be created in IS with the given name. However, we need to check the error. @ravinduramesh can you please try the same flow using scim2/Groups API? FYI @aaujayasena

**Comment by ravinduramesh** [comment]
@ashensw it works well with scim2/groups api endpoints.

I think this misleading role creation flow can be avoided/fixed by just returning a response with an error when someone tries to create a role in a secondary user store through scim2/roles api endpoints.

**Comment by ashensw** [comment]
> @ashensw it works well with scim2/groups api endpoints.
> 
> I think this misleading role creation flow can be avoided/fixed by just returning a response with an error when someone tries to create a role in a secondary user store through scim2/roles api endpoints.

Great! Yes but the role endpoint does not have context about userstores. For Roles endpoint, it's another role name and it will consider domain separator (`/`) as another character. But it cannot be broken. If we don't allow that character in the role name we need to validate it properly at API level.
