### ISSUE TITLE
[Improvement] Add emailOTP verify API for emailOTP REST API

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#13788]
Related to https://github.com/wso2/product-is/issues/12484
## Problem:
We are using 2 options to set the password for ASK_PASSWORD users. 

1. confirmation code(IS product default flow)
2. emailOTP

In the confirmation code scenario, once a user clicks the set-password link the confirmation code will be verified in BE(api/identity/recovery/v0.9/validate-code) and then the user is able to set a new password. When a user submits the new password, the confirmation code will validate again and invalidate the code after the process(api/identity/recovery/v0.9/set-password). 
The problem is, we can not implement the above behavior in the emailOTP scenario. Once a user enters the emailOTP the OTP will invalidate and then we can not implement a secure method to set the password step(the next step). 
## Improvement suggestion
We can implement a new API for verifying emailOTP without invalidating it.
EX: api/identity/email-otp/v1/emailotp/verify

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
