### ISSUE TITLE
Clicking on the account confirmation link more than once displays wrong error message

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13799]
**Describe the issue:**
Once a user registered through self registration flow the user receives the account confirmation link to the email. Once clicked the user account is confirmed as expected. Once clicked on the link again displays "invalid password reset link" error message even though the link is not a password reset link.

First click
<img width="935" alt="Screenshot 2022-06-01 at 11 27 11" src="https://user-images.githubusercontent.com/42939752/171337476-c03d4f1b-b9ef-426d-b9b0-b0fe77e0dccf.png">

Second click
<img width="999" alt="Screenshot 2022-06-01 at 11 29 20" src="https://user-images.githubusercontent.com/42939752/171337754-beb3f45c-2a91-4c60-8f8a-d5bffe08424f.png">

**How to reproduce:**
Create a user using self registration flow
Confirm account using the account confirmation link in the account confirmation email
Click on the same link again

**Expected behavior:**
Displays account is already confirmed / or redirects to account page

**Environment information**

- Product Version: IS 6.0.0 M1
- OS: Windows 2019
- Database: PostgreSQL
- Userstore: JDBC

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
