### ISSUE TITLE
Spaces in tenant domain throws "Server failed to respond error" in Self Registration flow

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13798]
**Describe the issue:**
A self registering user entering the <tenant_domain> part of the username with spaces included in between, clicking on the Proceed to register displays "Server failed to respond error".   

**How to reproduce:**

1. Allow user self registration from the Management Console.
2. Go to URL <IAM_SERVER_HOST>/myaccount/
3. Click Create "Create Account"
4. Enter username with tenant_domain with space in between. eg: user@i<space>am.com"
5. Click "Proceed to self register"

<img width="516" alt="Screenshot 2022-06-01 at 11 12 21" src="https://user-images.githubusercontent.com/42939752/171335670-75874656-976e-443f-85b1-3858127e126f.png">

<img width="856" alt="Screenshot 2022-06-01 at 11 12 41" src="https://user-images.githubusercontent.com/42939752/171335708-2c603498-6e7c-4503-8356-c149b54e37f7.png">

**Expected behaviour:**
Does not let user continue to registration page and displays invalid username format warning.

**Environment information**
 - Product Version: IS 6.0.0 M1
 - OS: Windows 2019
 - Database: PostgreSQL
 - Userstore: JDBC

---

### Optional Fields

**Error log**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
