### ISSUE TITLE
Include expected patterns and tooltips in self registration forms

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13794]
**Is your suggestion related to an experience ? Please describe.**
In the self registration process, the username form and the registration form do not include any tool tips or examples for the patterns they are expecting in each input field. Considering a self registering user will not be an administrator, each end user having to go through the documentation to understand the expected patterns and inputs reduces the user experience. 
eg: 
- Invalid username entry gives, "Username pattern policy violated" error message. But The expecting pattern is not specified.
- Invalid phone number in registration gives "Please match requested format" warning. But the requested format in not specified in the form
- No example for IM field or URL field to understand what to input.

**Describe the improvement**
Include tooltips or placeholder examples where necessary

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
