### ISSUE TITLE
SAML SLO Error in front channel redirect binding

### ISSUE THREAD

**Issue by nirmal101** [wso2/product-is#13791]
**Describe the issue:**

- Internal server error occurs when trying to SLO with front channel redirect binding

**How to reproduce:**

1. Navigate to Main menu of the management console select List from Service Providers.
2. Under the listed service providers select Edit on your preferred service provider.
3. Go to Inbound Authentication Configuration>SAML2 Web SSO Configuration.
4. Tick **Enable Single Logout** and give **SLO Response URL** and **SLO Request URL**
5. Select **Front-Channel Logout (HTTP Redirect Binding)** 
6. Click **Update**.
7. Do the steps 1 to 7 for all the preferred service providers.
8. Sign in to service provider 1 and service provider 2.
9. Try to logout of one service provider.
10. Internal server error will occur.

<img width="907" alt="Screenshot 2022-06-01 at 8 56 51 AM" src="https://user-images.githubusercontent.com/43103902/171327875-87ab3381-8bb2-42e9-a357-5d0b25a0bf31.png">

![Screenshot 2022-05-27 at 8 58 38 AM](https://user-images.githubusercontent.com/43103902/171327718-b567fbb7-483f-4317-a08e-97464e63a716.png)

![Screenshot 2022-05-27 at 9 29 52 AM](https://user-images.githubusercontent.com/43103902/171327803-338e17a8-3f11-4936-a266-17ac6bc929fe.png)

![Screenshot 2022-06-01 at 10 01 36 AM](https://user-images.githubusercontent.com/43103902/171328191-c8462e28-297c-471e-ad4b-14a1392e0146.png)

![Screenshot 2022-06-01 at 9 57 00 AM](https://user-images.githubusercontent.com/43103902/171328219-86006b76-d9d2-47a6-bdfd-e51b20f61309.png)

**Expected behavior:**

- Logout without an issue.

**Environment information** 

- Product Version: IS 6.0.0
- OS: Mac OS 12.4
- Database: MySQL 8.0.29
- User store: Primary and Secondary
- Browser: Firefox 91.0

---

- Used the following article to configure front channel redirect binding.
[Configuring SAML2 Front-Channel Logout on WSO2 Identity Server](https://medium.com/identity-beyond-borders/configuring-saml2-front-channel-logout-on-wso2-identity-server-13ce4cf3dc38)

**Comment by piraveena** [comment]
@nirmal101 saml2-web-app-pickup-dispatch app or saml2-web-app-pickup-manager app do not support  Front-Channel Logout (HTTP Redirect Binding). Those apps support on back-channel logout and back-channel login only.

But IS supports  Front-Channel Logout (HTTP Redirect Binding). To try out Front-Channel Logout (HTTP Redirect Binding), you need to use **spring-security-saml2-sample2** and configure it as mentioned in these blogs
https://medium.com/identity-beyond-borders/configuring-saml2-front-channel-logout-on-wso2-identity-server-13ce4cf3dc38
https://dewni-matheesha.medium.com/saml-2-0-front-channel-logout-with-wso2-identity-server-8a72d1075cf5

**Comment by ShanikaWickramasinghe** [comment]
@piraveena Tested this usecase with IS 6.0.0 m5 pack with spring saml sample version 1.0.10 (https://repo.spring.io/ui/native/release/org/springframework/security/extensions/spring-security-saml/1.0.10.RELEASE/). Front channel logout worked without any issues. Attaching a screen recording as a reference

https://user-images.githubusercontent.com/31848014/174596634-d4f64f99-1c73-4757-b2f4-537356ac6dc9.mp4

Hence we can get this issue closed. During the testings conducted with spring security saml2 samples (sample1 and sample2 )Observed one issue which is not related to this flow. Will track it in a separate new issue
