### ISSUE TITLE
When a group is added instead of a role, role mappings of identity provider role configurations do not get updated and no error is shown

### ISSUE THREAD

**Issue by yogyagamage** [wso2/product-is#13804]
**Describe the issue:**

When a group is added instead of a role, role mappings of identity provider role configurations do not get updated and no error is shown.

**How to reproduce:**

- Add a user role with domain as PRIMARY.
- Configure an identity provider.
- Click Add Role Mapping under Role Configuration.
- Add an identity provider role and the local role.

<img width="1201" alt="Screenshot 2022-06-01 at 16 10 10" src="https://user-images.githubusercontent.com/47789154/171386246-22b9032c-b217-4c87-8f16-35c91f9cb01a.png">

- Click update.
- The added role mapping will not be visible and no error will be shown.

<img width="1121" alt="Screenshot 2022-06-01 at 11 57 29" src="https://user-images.githubusercontent.com/47789154/171375829-b8ef17ef-ac90-4efb-a98a-9a38876a35b8.png">

**Expected behavior:**

The added role mapping should be saved and visible in the UI after updating or an error should be shown.

**Environment information:**
 - Product Version: IS 6.0.0
 - OS: Mac 
 - Browser: Firefox 91.0

---
_If the domain is selected as internal when creating the user role and added it as the local role, then the user mappings get updated._

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
