### ISSUE TITLE
When the access token type changed to "self_contained" it does not change back

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#13806]
**Describe the issue:**
When the
```
[oauth.token_generation]
access_token_type= "self_contained"
```
is add to the deployment.toml file, the token type changes to self contained. But when that section was removed from the deployment.toml file, the access token type does not change.

**How to reproduce:**

- Deploy the travelocity.com webapp (https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-travelocity-webapp) (Keep access token expiry time around 3min)
- Add
```
[oauth.token_generation]
access_token_type= "self_contained"
```
to the deployment.toml file and restart the IS server
- Run travelocity webapp
- Acess travelocity.com site using tomcat8
- Click Click here to login with SAML from Identity Server (Post binding or Redirect Binding).
- Enter the username and password and click SIGN IN.
- Click Request OAuth2 Access Token to receive the access token. (Keep this open in one tab)
-  Remove
```
[oauth.token_generation]
access_token_type= "self_contained"
```
from the deployment.toml file and restart the IS server
- Request the OAuth2 Access token again

**Expected behavior:**

- When self_contained tag added the access token changes accordingly,
<img width="1798" alt="Screenshot 2022-06-01 at 16 04 56" src="https://user-images.githubusercontent.com/46097917/171392095-0749a51e-5c86-443e-a03a-7b0088919777.png">

- But when self_contained tag removed it still returns a self contained access token
<img width="1793" alt="Screenshot 2022-06-01 at 16 20 22" src="https://user-images.githubusercontent.com/46097917/171392245-656186f4-42d7-434c-a647-cbc31df309c9.png">

- But it should be something like this,
<img width="1032" alt="Screenshot 2022-06-01 at 16 19 09" src="https://user-images.githubusercontent.com/46097917/171392342-13358c00-cf7e-405e-b6f6-44febf739f39.png">

**Environment information** **:**
- IS 6.0.0
- Mac
- DB2 11.5
- JDBC
- Firefox 91.0
- Oracle JDK 11

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
