### ISSUE TITLE
Outdated Identity Server Documentation - "Logging in to Google using the Identity Server"

### ISSUE THREAD

**Issue by malshan1998** [wso2/product-is#13803]
**Is your suggestion related to a missing or misleading document? Please describe.**

Several steps in the IS doc "Logging in to Google using the Identity Server" need to be updated. Some are missing and some are outdated.

**Describe the improvement**

The document (<https://is.docs.wso2.com/en/latest/learn/logging-in-to-google-using-the-identity-server/#configuring-google>) has 3 issues that need to be handled.

1. Link on the 2nd step of "Try it out" section, returns a blank page. It should be updated to "mail.google.com".
2. 6th step of "Configuring the Service Provider" section - must include a step to Disable Signature Validation.
3. The first 4 steps of the "Configuring Google" section should be updated. The mentioned method is a bit outdated.
4. "Before You Begin" note - The reference link is outdated.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
