### ISSUE TITLE
Issue when requesting id token with openid scope using the access token received from SAML bearer grant 

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#13805]
**Describe the issue:**
When trying to request an id token with openid scope using the access token received from SAML bearer grant the process halts in midway. But this works in the previous WSO2 Identity Server version (5.11.0)

**How to reproduce:**
- add a country and email for the admin account in the IS
- Deploy the travelocity.com webapp (https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-travelocity-webapp)
- Use the following Callback URL when configuring OAuth: [https://curl-app/callback]
- Add emailaddress as "_Requested Claim_" and "_Mandatory Claim_". Also add country as Requested Claim. (Claim Configuration > Define Custom Claim Dialect, in the service provider of travelocity.com)
- Put tick mark to both "_Use tenant domain in local subject identifier_" and "_Use user store domain in local subject identifier_" (Local & Outbound Authentication Configuration, in the service provider of travelocity.com)
- Run travelocity webapp
- Acess travelocity.com site using tomcat8
- Click Click here to login with SAML from Identity Server (Post binding or Redirect Binding).
- Enter the username and password and click SIGN IN.
- Click Request OAuth2 Access Token to receive the access token.
- Use that access token and,
curl -v -X POST -H "Authorization: Bearer 7ee57bc28a3336ccb7818b499941e4e4" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "response_type=code&client_id=<CLIENT_ID>&redirect_uri=<REDIRECT_URI>&scope=openid"  https://localhost:9443/oauth2/authorize
- Copy the URL in the location tag,
![Screenshot 2022-06-01 at 15 27 30](https://user-images.githubusercontent.com/46097917/171378872-0a2b13d7-8c60-4c01-aace-0d3403732ade.png)
- Paste that link on a browser and go to the link

**Expected behavior:**
After that it should show a single tick box, but in the IS 6.0.0m1 version it prompts the user to enter the email address again which was already filled. 
<img width="514" alt="Screenshot 2022-06-01 at 12 16 11" src="https://user-images.githubusercontent.com/46097917/171379577-966e7ac5-37f9-4dc2-a061-ec8e10c96c9a.png">
After filling that field it prompts an error screen
<img width="514" alt="Screenshot 2022-06-01 at 12 16 29" src="https://user-images.githubusercontent.com/46097917/171380046-0230ef45-15d2-4f38-ae34-83617b767953.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - IS 6.0.0
- Mac
- DB2 11.5
- JDBC
- Firefox 91.0
- Oracle JDK 11

**More details**
https://is.docs.wso2.com/en/latest/learn/oauth-request-path-authentication/#using-the-authorization-header

**Comment by Achintha444** [comment]
The same error comes up when trying to Single Sign-On with SAML to an external Identity Provider and use SAML bearer grant for access delegation.

**How to Reporduce**
- Setup another IS server according the details given in the below article
   https://medium.com/identity-beyond-borders/configuring-saml-federated-identity-provider-initiated-logout-in-wso2- identity-server-f1bc7612b270

- Change the Authentication type to Federated Authentication and select the set (in the above step) identity provider.
- Try out the steps in the main text

**Comment by mpmadhavig** [comment]
### Update

When trying to reproduce the above issue, met with another issue where the  user id with username@<TENANT_DOMAIN> cannot be found. This error caused by [this](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1855/files) improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
