### ISSUE TITLE
SSO SAML2 Application authentication with artifact binding fails

### ISSUE THREAD

**Issue by nirmal101** [wso2/product-is#13809]
**Describe the issue:**

- Signing into web application with **SAML2 Artifact Binding** enabled, throws out an exception.

**How to reproduce:**

1. Navigate to Main menu of the management console select List from Service Providers.
2. Under the listed service providers select Edit on your preferred service provider.
3. Go to Inbound **Authentication Configuration**>**SAML2 Web SSO Configuration**.
4. Tick  **Enable SAML2 Artifact Binding** and **Enable Signature Validation in Artifact Resolve Request** 
5. Click update.
6. Insert the following lines to the sso.properties file in the web apps.

SAML2.ArtifactResolveUrl = https://localhost:9443/samlartresolve
SAML2.EnableArtifactResolveSigning=true

7. Save and restart the web apps.
8. Go to web app login page and try to sign in using any user credentials.

![Screenshot 2022-06-01 at 9 48 49 PM](https://user-images.githubusercontent.com/43103902/171452272-c4ad6fb3-ab9a-4856-8cc4-3579e3836a8b.png)

<img width="663" alt="Screenshot 2022-06-01 at 9 49 37 PM" src="https://user-images.githubusercontent.com/43103902/171452425-5a276803-f845-4dd9-b8eb-ebbb94822357.png">

![Screenshot 2022-05-27 at 8 58 38 AM](https://user-images.githubusercontent.com/43103902/171452533-7d923415-ea1d-4e6a-ae98-c2ede1cae6fb.png)

![login authentication](https://user-images.githubusercontent.com/43103902/171452781-c1c1a4d5-f561-472e-a845-97eba882204f.png)

![Artifact Binding](https://user-images.githubusercontent.com/43103902/171452812-ed89c346-5192-4d0d-95e3-c9afd9d49f65.png)

**Expected behavior:**

- Sign in without any issue.

**Environment information** 

- Product Version: IS 6.0.0
- OS: Mac OS 12.4
- Database: MySQL 8.0.29
- User store: Primary and Secondary
- Browser: Firefox 91.0

---
Reference Article - https://is.docs.wso2.com/en/latest/learn/configuring-saml-2.0-artifact-binding/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
