### ISSUE TITLE
Deleting a scope returns 200 as the status code

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13816]
**Describe the issue:**
When try to delete a scope in OAuth 2.0 with REST API [https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/{name}](https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/%7Bname%7D)
 does not gives expected 204 as response as mention in the [documentation](https://is.docs.wso2.com/en/6.0.0/apis/oauth2-scope-management-rest-apis/#/Scope%20Management/deleteScope). Instead it gives 200.

<img width="1512" alt="Screenshot 2022-06-02 at 12 28 57" src="https://user-images.githubusercontent.com/38417165/171588625-3720bd79-0d09-4086-92e5-7cb53b33080a.png">

**How to reproduce:**

1. Create a scope.
2. Send a DELETE request to  [https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/{name}](https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/%7Bname%7D). Here replace name with previously created scope name.

**Expected behavior:**

Delete a scope should give 204 as the status code.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.1
 - JDK: Oracle JDK 11.0.15

**Comment by ashanthamara** [comment]
Above scenario is reproducing in IS 7.0-beta6  as well.

- Super Tenant 
![image](https://github.com/wso2/product-is/assets/75057725/c6e7fa28-d968-473a-89f7-14d9d0fa8195)

- Custom Tenant 
![image](https://github.com/wso2/product-is/assets/75057725/e442def6-53c0-4353-8f81-a336b6733b3b)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
