### ISSUE TITLE
Validate the Scopes Prior to Consent

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#13811]
**Is your suggestion related to an experience ? Please describe.**
Currently we are validating the user allowed scopes and some other validation after we asking the consent from the user. But ideally we should do these validation before we ask the consent from the user.
The code block [1] should be moved before asking the consent. We need to check the possibility first and improve it properly.

**Describe the improvement**
W should not request user consent for scopes that user is not eligible for. 
![Screenshot from 2022-05-30 15-31-56](https://user-images.githubusercontent.com/48151886/171486211-84ac8d3a-cdf4-42d2-a586-03d8ec64b099.png)

**Additional context**
[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.7.93/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authz/AuthorizationHandlerManager.java#L126-L188

**Comment by Shaaali** [comment]
The `authorize` request sent after the user authentication contains the scopes requested by the user. Therefore, the scope validation could be performed before consent request. 

@sahandilshan has done the scope validation for internal scopes by addressing #12937 through https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1766.

The solution to this issue will effect several products.
Therefore, when this issue is started to address, a discussion should be started in the `engineering integration group` so that the impact to various teams could be discussed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
