### ISSUE TITLE
Tenant Level Configuration to decide the Default Locale

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#1381]
**Description:**

At the moment in many features like challenge questions, email templates we assume the default locale value to be en_US. This may not always be the case. So if a user wants to change default locale to something other than en_US there is no way to do so.

This improvement is to provide such a config to either decide the locale globally or per tenant.

**Affected Product Version:**
IS 5.3.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
