### ISSUE TITLE
Adding info logs to ReCaptcha flow

### ISSUE THREAD

**Issue by DonOmalVindula** [wso2/product-is#13813]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**
We will be adding some info logs to ReCaptcha flow to ensure that it's working as intended. Once the flow is verified, we will be removing the info logs and will revert it to its normal state.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
