### ISSUE TITLE
Creating user with "@" in username causes error while logging in

### ISSUE THREAD

**Issue by emilebui** [wso2/product-is#13820]
**Describe the issue:**
 The system allows to create user with "@" character in username, however, when logging in with that specific user account. The system display 500 error message

**How to reproduce:**
 - Create an user with "@" in the username
 - Login with that user
 - Receives 500 error

![Untitled99](https://user-images.githubusercontent.com/33470772/171777123-2097b23c-3791-4ed5-a9d7-c829bf3b4a9e.png)

**Expected behavior:**
Either not allowing to create user with "@" character or somehow allow that user to log in

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Windows
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
