### ISSUE TITLE
Getting an incorrect success alert (response) after self user registration.

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13827]
**Describe the issue:**
I added an incorrect password to the output_adapter.email configurations in deployment.toml file to fail the email sending process on purpose. Then I went through the user self-registration process. After completing the user self-registration process, it showed an alert that says "confirmation link has been sent to your email" but an email is not received. The terminal also shows that an error occurred due to the misconfiguration I purposely added to the deployment.toml file.

The alert should inform the self-registered user that an error occurred while sending the confirmation email and advise them to contact the system admin instead of saying "confirmation link has been sent to your email".

**How to reproduce:**
1. Add configuration for the _[output_adapter.email]_ section in deployment.toml file but with an incorrect password for the given email.
2. Add following configurations to the deployment.toml file
_[identity_mgt.user_onboarding]
enable_email_verification =true
lock_on_creation=true_
3. Enable self user registration in the resident identity provider
4. Go to the "My Account" page through [https://localhost:9443/myaccount](https://localhost:9443/myaccount)
5. Click on the "Create Account" button
6. Specify a username and click on the "Proceed to Self Register" button
7. Fill out the form and click on the "Register" button
8. Check the response that says "Confirmation link has been sent to your email" 
9. Check the terminal where the IS server is running to see that the email is not sent because of an error.
 

**Expected behavior:**
The alert should inform the self-registered user that an error occurred while sending the confirmation email and advise them to contact the system admin. But currently, the alert says "confirmation link has been sent to your email".

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Comment by piraveena** [comment]
IS fires the email notification to relevant email sending modules, and it may not know if something goes wrong there.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
