### ISSUE TITLE
Restrict access to the shared applications in organization management

### ISSUE THREAD

**Issue by wenodpathirana** [wso2/product-is#13824]
**Description:**

With the B2B Organization Management(https://github.com/wso2/product-is/issues/13658) feature an organization should be capable of sharing applications with other organizations to provide B2B services. After the application is shared, child organization should only be able to update certain details in the shared application such as local / outbound authentication steps.

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3228
