### ISSUE TITLE
Internal Role Count is Always 0 in The Management Console UI

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13826]
**Describe the issue:**
Although I have 7 roles in the INTERNAL domain, the internal role count is always equal to 0 in the management console UI.

<img width="772" alt="Screenshot 2022-06-03 at 10 15 36" src="https://user-images.githubusercontent.com/12953762/171788148-fc31526a-d9e4-4749-b76d-21e8e2855d33.png">

**How to reproduce:**
1. Create several roles (about 5 roles) by selecting domain as "INTERNAL"
2. Go to the management console list roles view (https://localhost:9443/carbon/role/role-mgt.jsp in locally running server)
3. Check the values in the "Count Roles" section.

**Expected behavior:**
The no of roles in the "internal" domain must be greater than 0 as we created few roles in the "internal" domain. But currently it shows 0 as the internal role count.

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Comment by sahandilshan** [comment]
Hi @ravinduramesh 

According to the documentation [here](https://is.docs.wso2.com/en/latest/develop/counting-users-and-roles-using-management-console-and-admin-services/#counting-users-and-user-roles), the counter is only supported for JDBC user stores. 
<img width="709" alt="Screenshot 2022-06-11 at 12 05 55 AM" src="https://user-images.githubusercontent.com/32576163/173129204-9269a8a3-d0a9-442f-bc62-e50b0643a3ed.png">

I have configured a Postgress user store and added two roles. The counter works as expected.

<img width="712" alt="Screenshot 2022-06-11 at 12 04 26 AM" src="https://user-images.githubusercontent.com/32576163/173129466-06aaa9a4-9e6b-4642-b84f-b348647a9fb1.png">

Would you be able to try out the same flow and verify whether the issue still exists? You can refer to [this](https://is.docs.wso2.com/en/latest/setup/configuring-a-jdbc-user-store/) documentation here to configure an external user store

**Comment by ravinduramesh** [comment]
Hi @sahandilshan 

Both the primary roles and internal roles are stored in LDAP. If counting is not supported for roles in LDAP, can we hide internal role count also from the UI as well as it already hide primary role count?

**Comment by sahandilshan** [comment]
Hi @ravinduramesh 

We have an option in the IS to configure a JDBC store as a primary user store [1]. If we use this option, then the counter will work as expected for both primary and internal roles as well. 

[1] - https://is.docs.wso2.com/en/latest/setup/configuring-a-jdbc-user-store/#configuring-the-internal-database-as-jdbc-user-store

**Comment by ravinduramesh** [comment]
Hi @sahandilshan 

Then why the primary role count is hidden in my 'roles' page? but the internal role count is visible there with 0 value (I have both primary and internal roles as shown in [image](https://user-images.githubusercontent.com/32576163/173129466-06aaa9a4-9e6b-4642-b84f-b348647a9fb1.png).

**Comment by sahandilshan** [comment]
Hi @ravinduramesh 

Here I have used a secondary user store. That's why it's not showing the primary role count (The primary role will be saved in the primary user store). You can follow this [documentation](https://is.docs.wso2.com/en/latest/setup/configuring-the-primary-user-store/) to set up a JDBC-based primary user store and try out the flow. It should show the role count

**Comment by ravinduramesh** [comment]
Closing the issue as LDAP US doesn't support the counter.
