### ISSUE TITLE
travelocity app of the samples-is release 4.4.1, not working properly.

### ISSUE THREAD

**Issue by malshan1998** [wso2/product-is#13822]
**Describe the issue:**

When the app is accessed through Tomcat 8.0.53 manager, it displays an error message instead of starting the app. This problem is not present in the release 4.3.0 travelocity app.

**How to reproduce:**

Deploy the app in Tomcat and start the Tomcat server. Then go to 'Manager App' and click on '\travelocity'. It will return a "HTTP Status 500 – Internal Server Error". 

**Expected behavior:**

The application should be deployed without an issue. 

**Environment information**
 - Product Version: [IS 6.0.0]
 - OS: [MacOS Monterey Version 12.4]
 - Database: [MYSQL]
 - Userstore: [DBC]

**Comment by ShanikaWickramasinghe** [comment]
@malshan1998 lets include release tag under which you got this issue. you can point the github link for the used artifact. Also under environment section include your java version and OS

**Comment by piraveena** [comment]
could be some permission issues. Can you attach the logs related to this deployment?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
