### ISSUE TITLE
Issues related to Workflow approvals in Console

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#13833]
**Describe the issue:**

Once a workflow approval task has been made, an eligible user can reserve (claim) that task. 

>Workflow definition in Carbon

<img width="1785" alt="Screenshot 2022-06-03 at 15 29 58" src="https://user-images.githubusercontent.com/67315176/171865395-e83b7896-be48-4642-bf3c-b4d15c36188a.png">

>Workflow task shown to admin user

<img width="1787" alt="Screenshot 2022-06-03 at 15 32 17" src="https://user-images.githubusercontent.com/67315176/171865467-aa0dbb1e-bd53-4ff9-a114-0dacfade3e65.png">

The following issues are observed in this feature; 
1. Currently, no information regarding the user who reserved (claimed) it is shown in the UI.
2. A user who is eligible to approve, but did not reserve it can still see the activated buttons to `Approve`, `Reject` and `Claim` the task. However, they will get an error message as follows once they try to peform any of those action.

<img width="1697" alt="Screenshot 2022-06-03 at 15 37 07" src="https://user-images.githubusercontent.com/67315176/171866148-58e0bed8-cac8-4650-99ce-86d92db38ca5.png">

In addition, the following issues can be observed;
3. When multiple users are eligible to approve a task per approval step, they are not displayed in the UI as the data from the API response gives only one user (unclear how this user is selected from the list of users who can approve the task).
4. If a workflow definition is updated to remove a user from approving an item after a workflow approval task has been created, the item is still visible and approveable by the user who was removed.

In order to improve the workflow approvals feature in the Console by avoiding confusions, we will need more data from the API such as who is eligible to approve and who has reserved it and address the above additional issues.

**How to reproduce:**
Refer steps in https://github.com/wso2/product-is/issues/13535

**Environment information:**

Product Version: IS 5.12.0-alpha20
OS: Mac
Database: MSSQL
Userstore: DBC

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/13535

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
