### ISSUE TITLE
ERROR in creating a new group via SCIM2 Groups endpoint

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#13839]
**Describe the issue:**

When an WSO2 identity server is provisioned with a Group via SCIM2 Groups endpoint without no users, 400 Bad Request is received

<img width="1102" alt="Screenshot 2022-06-06 at 11 16 39" src="https://user-images.githubusercontent.com/59327626/172102494-8d714663-723a-4870-903e-dfe98897c3c5.png">

Response:
`{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "scimType": "invalidValue",
    "detail": "One or more group members do not exist in the same user store. Hence, can not create the group: ProjectManager",
    "status": "400"
}`

**How to reproduce:**
1. Get IS 6.0.0-m1 pack and set up and enable inbound SCIM provisioning via Management Console > Main > Service Providers > Resident > Inbound Provisioning Configuration > select PRIMARY > Update.
2. Send a POST request to https://localhost:9443/scim2/Groups with the above body

**Expected behavior:**

The Group is added to the userstore and can be viewed in the management console

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS 6.0.0-m1
- OS: MacOS 12.4
- JDK: Oracle JDK 11.0.15.1

**Comment by ashensw** [comment]
Hi @shanggeeth, I tried the same in IS 6.0.0-m1 pack and the issue was not reproduced. 
<img width="914" alt="Screenshot 2022-06-06 at 11 46 28" src="https://user-images.githubusercontent.com/13478571/172109790-26dcb757-f4e2-4c71-821c-ed61013bc809.png">

Do you see any specific errors in the backend?

**Comment by shanggeeth** [comment]
Hi @ashensw There are no errors in the backend
I tried the flow again and noticed that this issue occurred only when created Group is a previously deleted group
