### ISSUE TITLE
Issue with outbound provisioning when creating a group in console while SCIM2 Outbound provisioning was setup in management console

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#13847]
**Describe the issue:**

When the outbound provisioning is configured with with an IDP in Management Console and a group is created via the Console app, outbound provisioning does not occur with no backend errors

https://user-images.githubusercontent.com/59327626/172119090-78da6e16-4228-4ce4-a34e-3b4158a38eb3.mov

**How to reproduce:**

1. Get IS 6.0.0-m1 pack and set up and configure outbound SCIM provisioning with following [steps](https://is.docs.wso2.com/en/latest/learn/outbound-provisioning-with-scim/#:~:text=This%20topic%20provides%20instructions%20on,%2C%20another%20Identity%20Server%2C%20etc.).
(Set he User Endpoint as https://localhost:9444/scim2/Users and Group Endpoint as https://localhost:9444/scim2/Groups)
2. Get another similar IS pack (Secondary IS) and enable inbound SCIM provisioning via Management Console > Main > Service Providers > Resident > Inbound Provisioning Configuration > select PRIMARY > Update.
3. Create a Group in Primary IS via Console App
4. Validate if secondary IS is provisioned with the group via Management Console

**Expected behavior:**

The created group is successfully provisioned to secondary Identity Server

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS 6.0.0-m1
- OS: MacOS 12.4
- JDK: Oracle JDK 11.0.15.1
- Database: PostgreSQL 13.2
- Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
