### ISSUE TITLE
SCIM2/me endpoint accepts empty string, escape characters, and all space strings for username

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13843]
**Describe the issue:**
When a POST request is sent to scim2/me endpoint with 
- an empty string
- string with all spaces
- string with all "\t" and "\r" escape characters 
as username, the user is created with empty username without returning an error. This user is not displayed in the management console. Multiple POST requests with empty usernames does not throw duplicate username error. 

**How to reproduce:**
Send "{{host}}/t/carbon.super/scim2/Me" endpoint post requests with empty string as username.

**Expected behavior:**
Bad request response with invalid username error  returned

**Environment information**
- Product Version: IS 6.0.0  M1
- OS: Windows 2019
- Database: PostgreSQL
- Userstore: JDBC

---

**Comment by mpmadhavig** [comment]
<img width="1082" alt="Screenshot 2023-01-12 at 10 20 40" src="https://user-images.githubusercontent.com/47152272/211979537-383e0d38-3ca8-4ab6-ba25-dad36620d70b.png">
<img width="1086" alt="Screenshot 2023-01-12 at 10 21 13" src="https://user-images.githubusercontent.com/47152272/211979584-cf6838a5-886d-4e46-b1e8-b08fa7aab7a3.png">
<img width="1089" alt="Screenshot 2023-01-12 at 10 21 56" src="https://user-images.githubusercontent.com/47152272/211979598-8de1b0eb-9cb3-40cb-9501-0506e1dddb7f.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
