### ISSUE TITLE
SCIM2/me endpoint ignores primary attribute in descriptive email format

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13842]
**Describe the issue:**
The emails marked as primary in the "emails" field of scim2/me post request are not recognised as primary emails. The following actions are allowed due to this issue
- multiple emails allowed to be marked as primary in the emails list
- users created with no primary email if no non-descriptive format email is included in the emails list

**How to reproduce:**
Create a user by sending a POST request to scim/me endpoint with descriptive emails that are marked as primary. 
eg : 
"curl --location --request POST 'https://localhost:9443/t/iam.com/scim2/Me' \
--header 'accept: application/scim+json' \
--header 'authorization: Basic YWRtaW5AaWFtLmNvbTpQYXNzQDEyMw==' \
--header 'Content-Type: application/scim+json' \
--data-raw '{
    ""userName"": ""kim1"",
    ""password"": ""abc123"",
    ""emails"": [
        {
            ""type"": ""home"",
            ""value"": ""kim1@gmail.com"",
            ""primary"": true
        },
        {
            ""type"": ""work"",
            ""value"": ""kim2@wso2.com""
        }
    ]
}'"

**Expected behavior:**
Emails marked as primary are recognised as primary emails. Multiple primary emails are not allowed. 

**Environment information**
- Product Version: IS 6.0.0 M1
- OS: Windows 2019
- Database: PostgreSQL
- Userstore: JDBC

---

**Other notes**
non-descriptive email format example: 
{
...,
emails: [ 
"user@gmail.com"
]
}

descriptive email format example: 
{
...,
emails: [ 
        {
            "type": "work",
            "value": "kim2wso2.com",
            "primary": true
        }
]
}

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
