### ISSUE TITLE
Deleting a non existing OpenID scope returns 204 as the status code 

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13846]
**Describe the issue:**
When try to delete a non existing scope in OpenID with REST API [https://localhost:9443/t/carbon.super/api/server/v1/oidc/scopes/{invalid-id}](https://localhost:9443/t/carbon.super/api/server/v1/oidc/scopes/%7Bid%7D)
 does not gives expected 404 as response. Instead it gives 204.

<img width="1512" alt="Screenshot 2022-06-06 at 09 30 27" src="https://user-images.githubusercontent.com/38417165/172111192-5f6af7b5-9ae1-4387-a97c-e14ce5933e6a.png">

**How to reproduce:**

Send a DELETE request to  [https://localhost:9443/t/carbon.super/api/server/v1/oidc/scopes/{invalid-id}](https://localhost:9443/t/carbon.super/api/server/v1/oidc/scopes/%7Binvalid-id%7D). Here replace invalid-id with a invalid scope name.

**Expected behavior:**

Delete a  non existing scope should give 404 as the status code.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.1
 - JDK: Oracle JDK 11.0.15

**Comment by ashensw** [comment]
Hi @AnjanaSamindraPerera,

The APIs in IS are designed as below,

> First DELETE: resource is deleted -> 204
> 
> Subsequent DELETEs: resource is already deleted or does not exist -> 204.
> 
> Rationale: DELETE should be idempotent. If you return 404 on a second DELETE, your response is changing from a success code to an error code. The client program may take incorrect actions based on the assumption the DELETE failed.

Therefore we can consider this as the expected behavior.
