### ISSUE TITLE
Emails not validated in SCIM2/me post request

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13845]
**Describe the issue:**
The emails entered in descriptive format are not validated in scim2/me requests. The users are created and updated with emails being saved as they are even when email fields are in incorrect format. 

**How to reproduce:**
Create a user using scim2/me API POST request. In the request include the emails that don't adhere with valid email address pattern, in descriptive format.
Use PATCH and PUT requests on the same user with invalid emails.
eg:
curl --location --request POST 'https://localhost:9443/t/carbon.super/scim2/Me' \
--header 'accept: application/scim+json' \
--header 'authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/scim+json' \
--data-raw '{
    "userName": "abdfd12",
    "password": "pass3",
    "emails":[
        "kim2@wso2.com",
        {
            "type": "home",
            "value": "kim1gmail.com",
            "primary": true
        },
        {
            "type": "work",
            "value": "kim2wso2.com",
            "primary": true
        }
    ]
}'

**Expected behavior:**
User is not created and invalid email pattern error message returned.

**Environment information**
- Product Version: IS 6.0.0 M1
- OS: Windows 2019
- Database: PostgreSQL
- Userstore: JDBC

---

**Other notes**
non-descriptive email format example: 
{
...,
emails: [ 
"user@gmail.com"
]
}

descriptive email format example: 
{
...,
emails: [ 
        {
            "type": "work",
            "value": "kim2wso2.com",
            "primary": true
        }
]
}

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
