### ISSUE TITLE
Incorrect password pattern in error message

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13844]
**Describe the issue:**
When creating a user with an invalid password pattern user is returned with error message: 
"30003 - Credential is not valid. Credential must be a non null string with following format, ^[\\S]{5,30}$"
The pattern implies only backward-slash and character 'S' is allowed in password, which is wrong.

**How to reproduce:**
Send a post request with all valid data except password. Enter an invalid password.
sample invalid password: "pass 123"

**Expected behavior:**
Error message contains the correct password pattern.

**Environment information**
- Product Version: IS 6.0.0 M1
- OS: Windows 2019
- Database: PostgreSQL
- Userstore: JDBC

---

**Comment by mpmadhavig** [comment]
<img width="1086" alt="Screenshot 2023-01-12 at 10 32 41" src="https://user-images.githubusercontent.com/47152272/211981631-fe30d7aa-3e44-4bf4-b3b0-79e3f679b322.png">

> The \s (lowercase s) matches a whitespace (blank, tab \t, and newline \r or \n). On the other hand, the \S+ (uppercase S) matches anything that is NOT matched by \s, i.e., non-whitespace. In regex, the uppercase metacharacter denotes the inverse of the lowercase counterpart, for example, \w for word character and \W for non-word character; \d for digit and \D or non-digit.

Reference: https://www3.ntu.edu.sg/home/ehchua/programming/howto/Regexe.html

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
