### ISSUE TITLE
Inconsistent username pattern use in SCIM2/me endpoint

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13841]
**Is your suggestion related to an experience ? Please describe.**
Even though user_store_domain/username@tenant_domain is the valid username pattern, embedding the tenant_domain section in the username (eg: user@carbon.super) for the post request of the scim2/me endpoint returns invalid value error. 
This is inconsistent since the endpoint allows embedding the user_store_domain in the username (eg: store2/user )  

**Describe the improvement**
Use user_store_domain as a separate field in the request

**Comment by mpmadhavig** [comment]
<img width="1089" alt="Screenshot 2023-01-12 at 10 10 01" src="https://user-images.githubusercontent.com/47152272/211977923-0b852900-0cdf-4695-a2dc-c2e92f729698.png">

**Comment by mpmadhavig** [comment]
<img width="1089" alt="Screenshot 2023-01-12 at 10 10 01" src="https://user-images.githubusercontent.com/47152272/211977923-0b852900-0cdf-4695-a2dc-c2e92f729698.png">
