### ISSUE TITLE
The List Roles Endpoint in SCIM 2.0 API Ignores 'excludedAttributes' Parameter

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13855]
**Describe the issue:**
It retrieves 'displayName', 'meta', and 'id' attributes of all roles although I sent a request to retrieve all roles without 'meta' values. Same behaviour happens for requests to retrieve all roles without 'id' values and for requests to retrieve all roles without 'displayName' values.

<img width="792" alt="Screenshot 2022-06-06 at 19 59 10" src="https://user-images.githubusercontent.com/12953762/172181759-5ca53ba7-877b-449a-aa05-5b24bebb6529.png">

<img width="792" alt="Screenshot 2022-06-06 at 20 00 03" src="https://user-images.githubusercontent.com/12953762/172181787-f391b783-a125-4618-8d24-72234f8257cb.png">

**How to reproduce:**
1. Create some roles (about 5) though SCIM 2.0 API
2. Send a GET request to https://localhost:9443/scim2/Roles?excludedAttributes=id
3. Send a GET request to https://localhost:9443/scim2/Roles?excludedAttributes=meta

**Expected behavior:**
When we send a GET request to https://localhost:9443/scim2/Roles?excludedAttributes=id, it should retrieve all roles in the system without 'id' values.
When we send a GET request to  https://localhost:9443/scim2/Roles?excludedAttributes=meta, it should retrieve all roles in the system without sub-attributes and values in the 'meta' attribute.

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Related issues:**
[https://github.com/wso2/product-is/issues/13853](https://github.com/wso2/product-is/issues/13853)

**Comment by mpmadhavig** [comment]
The [https://localhost:9443/scim2/Roles](https://localhost:9443/scim2/Roles) SCIM2 API does not support `excludedAttributes` query param at the moment.
