### ISSUE TITLE
The Response for Creating a Role Through SCIM 2.0 API Doesn't Contain Users, Groups and Permissions Attributes

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13850]
**Describe the issue:**
'users', 'groups', and 'permissions' attributes are missing in the response we get for creating a new role with those attributes although those attributes are saved in the backend.

Request:
```
curl --location --request POST 'https://localhost:9443/scim2/Roles' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "displayName": "lord",
    "permissions": [
        "/permission/admin/login"
    ],
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:2.0:Role"
    ],
    "users": [
        {
            "value": "5eedac1d-c381-480f-a64e-4732081f6147"
        }
    ],
    "groups": [
        {
            "values": "16ab48c7-d1ce-4381-8ded-dcc3c203e796"
        }
    ]
}'
```

Response:
```
{
    "meta": {
        "location": "https://localhost:9443/scim2/Roles/1701ce36-933b-40ee-9d4b-d655ca703ddb"
    },
    "displayName": "lord",
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:2.0:Role"
    ],
    "id": "1701ce36-933b-40ee-9d4b-d655ca703ddb"
}
```

**Expected behavior:**
The response should reflect all the saved details. Then the request sender can verify whether all the entered details are saved and can show them back in the client app.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Suggested labels:**
Improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
