### ISSUE TITLE
SAML inbound auth config storage optimization

### ISSUE THREAD

**Issue by Nuwan-Harshakumara-Piyarathna** [wso2/product-is#13852]
Following issues are identified regarding SAML inbound auth config storage.

- For now, metadata of the SAML2 web applications in the WSO2 Identity server, is stored in the Registry.This storage has to be moved to RDBMS because of reliability and performance issues with Registry.
- Currently, creating a Service Provider and creating SAML inbound authenticator happens in two separate transactions. Associating the Service Provider and SAML inbound authenticator happens in another transaction. We have to make the two operations for creating a service provider and saml inbound authenticator atomic.

Fixing this would require the following.

- Analyse the REST and SOAP api flows for managing SAML Service Providers and do the required changes to maintain atomicity.
- Move the storage for SAML metadata from registry to RDBMS. 
- Creating a data-migration mechanism.

**Comment by Nuwan-Harshakumara-Piyarathna** [comment]
Current progress was added in following PR s

- https://github.com/wso2/carbon-identity-framework/pull/4057
- https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/372
- https://github.com/wso2-extensions/identity-migration-resources/pull/226
- https://github.com/wso2/identity-api-server/pull/364/

**Comment by Nuwan-Harshakumara-Piyarathna** [comment]
Documentation about current progress and TODOs can find in [1].

[1][https://docs.google.com/document/d/14__uZaQ5905FxC-dtuzYssl7TGzuHe0tYCxoa6y8Ka4/edit?usp=sharing](https://docs.google.com/document/d/14__uZaQ5905FxC-dtuzYssl7TGzuHe0tYCxoa6y8Ka4/edit?usp=sharing)

**Comment by rksk** [comment]
Related effort https://github.com/wso2/product-is/issues/13852

The pending task after above effort is to bring SP update into a single DB transaction.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
