### ISSUE TITLE
Listing Roles Through SCIM 2.0 API Doesn't Retrieve Users, Groups and Permissions Attributes

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13851]
**Describe the issue:**
'users', 'groups', and 'permissions' attributes are missing in the response we get for listing roles through SCIM 2.0 API. But we get all related attributes instead of 'groups' when we retrieve a single role.

<img width="792" alt="Screenshot 2022-06-06 at 18 13 33" src="https://user-images.githubusercontent.com/12953762/172162905-3f99c6fb-9988-4e83-8fbb-860164a0e15e.png">

<img width="792" alt="Screenshot 2022-06-06 at 18 13 20" src="https://user-images.githubusercontent.com/12953762/172162933-631fd831-115f-4727-a186-ee1cd10cedca.png">

**How to reproduce:**
1. Create a role with 'users', 'permissions', and 'groups' attributes though SCIM 2.0 API
2. List all roles by sending a GET request to https://localhost:9443/scim2/Roles
3. Retrieve only the created role in step 1 by sending a GET request to https://localhost:9443/scim2/Roles/{role-id}

**Expected behavior:**
Listing roles via a SCIM2 API request should retrieve all roles with all related attributes if there's not 'attributes', or 'excludedAttributes' parameters are not defined in the request.

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Related issues:**
[https://github.com/wso2/product-is/issues/13850](https://github.com/wso2/product-is/issues/13850)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
