### ISSUE TITLE
Cannot Identify the FIDP From the ID Token for OpenIDConnectAuthenticator

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#13860]
**Is your suggestion related to a experience ? Please describe.**
It is impossible to identify the FIDP from the ID token.

**Describe the improvement**
We can configure the OpenIDConnectAuthenticator as Multiple FIDPs in our application and use them to authenticate the users.
But when doing so, we cannot destinctly identify the FIDP from the ID Token because, There's no claim in ID token that provides the name of the FIDP running on top of OpenIDConnectAuthenticator.
Although AMR has the authenticator type specified, this alone cannot be used to distinctively identify the FIDP when multiple FIDPs are configured using OpenIDConnectAuthenticator.

**Additional context**
This could be resolved by adding a claim to the id token that provides the name of the FIDP the user was authenticated with.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
