### ISSUE TITLE
Issue with getting challenge question answers

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13869]
**Describe the issue:**
When try to get challenge question answers using REST API https://localhost:9443/t/carbon.super/api/users/v1/me/challenge-answers show the below response.

<img width="1512" alt="Screenshot 2022-06-07 at 14 57 53" src="https://user-images.githubusercontent.com/38417165/172354681-9d696d66-ec87-4bff-b33f-0889ed4d7acb.png">

**How to reproduce:**
Sent a request to  https://localhost:9443/t/carbon.super/api/users/v1/me/challenge-answers.

**Expected behavior:**
Show challenge questions or show a proper error message. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.4
 - JDK: Oracle JDK 11.0.15

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
