### ISSUE TITLE
Unify the way we handle consent prompt

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#13866]
**Is your suggestion related to an experience? Please describe.**
In the current implementation, the consent prompt is handled differently on OAuth and other flows (small). This is because for OAuth consent means attribute and scope. But in other flows, we don't have the scope concept. So only during the OAuth flow, the framework will not handle the consent and create the session and gives the control to OAuth. Then OAuth itself will prompt the consent and complete the flow. 

**This causes the following problem,**

- It is hard to maintain the consent flow as there are two different ways it works. So all the improvements and bug fixes need to consider both flows. 

**Suggestion**

As a solution, we can provide extension ability in consent handling in the framework. So that OAuth will provide the needed consents (scope and attributes) to consent and then get the response from the user and process. With this, the consent prompt will be handled in one place and we can enforce consent to be handled before the session is being created.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
