### ISSUE TITLE
reCaptcha for password recovery not getting activated

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#13861]
**Describe the issue:**
After activating reCaptcha for password recovery in the resident identity provider from the management console, user is not prompt with reCaptcha in the password recovery process. Process continues as if reCaptcha is not activated. 

**How to reproduce:**
Enable notification based password recovery from the management console	
Enable reCaptcha for password recovery from the management console
Try following password recovery process by entering valid information

![Screenshot 2022-06-07 at 09 47 27](https://user-images.githubusercontent.com/42939752/172294958-e5edd62b-06e6-4f38-903b-381eb13ce340.png)
![Screenshot 2022-06-07 at 09 48 01](https://user-images.githubusercontent.com/42939752/172295007-24b042f3-ae8d-44fd-aa3e-e44af4811ccd.png)
![Screenshot 2022-06-07 at 09 48 25](https://user-images.githubusercontent.com/42939752/172295059-7a3a7e1f-fc20-4372-8844-e80ea7147d48.png)

**Expected behavior:**
reCaptcha challenge is prompt for the user and without the correct solution user cannot proceed with the recovery process. 

Environment information
- Product Version: IS 6.0.0 M1
- OS: Windows 2019
- Database: PostgreSQL
- Userstore: JDBC

---

**Related issues:**
https://github.com/wso2/product-is/issues/13862

**Comment by asha15** [comment]
Hi @RushanNanayakkara . Did you setup the ReCaptcha[1] before trying this?

[1] https://is.docs.wso2.com/en/latest/learn/setting-up-recaptcha/

**Comment by RushanNanayakkara** [comment]
@asha15  I had missed that step. That solved the issue. thanks
