### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by mancopuerco** [wso2/product-is#13874]
Location : https://is.docs.wso2.com/en/latest/develop/writing-a-custom-policy-info-point/

Hi, when I try to download the sample project, link: https://svn.wso2.org/repos/wso2/people/asela/xacml/pip/jdbc/; or the attribute finder class, link: https://svn.wso2.org/repos/wso2/people/asela/xacml/pip/jdbc/src/main/org/xacmlinfo/xacml/pip/jdbc/KMarketJDBCAttributeFinder.java

I allways receive the message:
Forbidden
You don't have permission to access this resource.

Do I need to register somewhere? or is it an error in your page?

I've tried other CustomPIP implementation guidelines, without success. Can you please help?

Thanks in advance.

Kind regards.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
