### ISSUE TITLE
Update IdentityUserMetadataMgtHandler to support managing last password update claim

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#13877]
**Is your suggestion related to an experience ? Please describe.**

> This relates to supporting the password expiry feature in password grant type.[1]

**Describe the improvement**

> This handler has only taken into consideration the POST_UPDATE_CREDENTIAL and POST_UPDATE_CREDENTIAL_BY_ADMIN events. But POST_ADD_USER event also need to be considered to support the password expiration feature in the password grant flow. 

- > Update the ‘IdentityUserMetadataMgtHandler’ by analyzing the password change handler

- > Subscribe to “Add user’ event as that also contributes to last password update time.

- > Default password expiry period should be configurable through the deployment.toml file

**Additional context**

[1] https://github.com/wso2/product-is/issues/13876

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
