### ISSUE TITLE
Bug on IWA authentication

### ISSUE THREAD

**Issue by oleksiybozhyk** [wso2/product-is#13873]
**Describe the issue:**

Randomly the IWA authentication doesn't work properly on front-end we get:
- Authentication Error! Something went wrong during the authentication proces. Please try signing in again.

And on back end we get 
- Nullpointer Exception (Exception in Authentication Framework java.lang.NullPointerException)

**How to reproduce:**

Install WOS2 IS and configure Kerberso Identity Provider
Configure Kerberos for authentication
Install Travelocity as the testing App ( Create SP for travelocity and configure autehntication with Kerberos )

**Expected behavior:**

Valid user should always be able to authenticate successfully 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.11.0]
 - Multi site configuration with 2 replicas each running on Kubernetes
 - Database: [MS SQL Server]
 - Userstore: [ LDAP ]

---
[kerberos_issue.log](https://github.com/wso2/product-is/files/8854606/kerberos_issue.log)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
