### ISSUE TITLE
The List Roles Endpoint in SCIM 2.0 API Ignores the 'Domain' Parameter

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13870]
**Describe the issue:**
It retrieves all roles in both the 'internal' domain and the 'application' domain although I sent a request to retrieve roles only in the 'application' domain. The same behavior happens for requests to retrieve roles only in the 'internal' domain also.

To retrieve roles in the 'application' domain, I passed all the following values as the value for the domain parameter. But each gave the same incorrect result.
1. Application
2. application
3. APPLICATION

<img width="799" alt="Screenshot 2022-06-07 at 15 54 34" src="https://user-images.githubusercontent.com/12953762/172357802-d1a72dc9-83e9-4fa1-a527-7663c7e06284.png">

**How to reproduce:**
1. Create some roles in the 'Internal' domain by using the IS management console.
2. Create some roles in the 'Application' domain by using the IS management console.
3. Send a GET request to https://localhost:9443/scim2/Roles?domain=Application
4. Send a GET request to https://localhost:9443/scim2/Roles?domain=Internal

**Expected behavior:**
When we send a GET request to https://localhost:9443/scim2/Roles?domain=Application, it should retrieve the roles only in the 'Application' domain. But currently, it retrieves all the roles in both the 'Application' domain and the 'Internal' domain.
When we send a GET request to https://localhost:9443/scim2/Roles?domain=Internal, it should retrieve the roles only in the 'Internal' domain. But currently, it retrieves all the roles in both the 'Application' domain and the 'Internal' domain.

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Comment by ashensw** [comment]
Hi @ravinduramesh, There is no domain support in the Roles API [1]. Please use the filter param for filtering. 

[1] https://is.docs.wso2.com/en/5.12.0/develop/scim2-rest-apis/#/Roles%20Endpoint/getRole

**Comment by ravinduramesh** [comment]
Closing the issue since the SCIM 2.0 API act as intended.
