### ISSUE TITLE
Logout issue in Playground2 web application

### ISSUE THREAD

**Issue by nirmal101** [wso2/product-is#13889]
**Describe the issue:**

- When you try to logout of the playground2 application the IdP will prompt a YES/NO dialog box for logging out. 
- If you select  No from the prompt, IdP will not redirect you to the home page of the web application. Instead it throws an authentication error.

**How to reproduce:**

1.  Sign in to the playground2 web application with proper user credentials. 
2. Press Logout button in the home page.
3. Select no from the IdP prompt
![image](https://user-images.githubusercontent.com/43103902/172667661-5c232c74-1d4c-4caf-914e-9ea8712d0ef4.png)
![image](https://user-images.githubusercontent.com/43103902/172667688-25a827a1-8ec4-4982-b490-7e32b5379884.png)
![image](https://user-images.githubusercontent.com/43103902/172667726-2e98f9cf-3d59-465d-9ab9-821b8fb31c94.png)
![image](https://user-images.githubusercontent.com/43103902/172667749-81336d22-431b-40a9-99d1-0be9834b5a66.png)
![image](https://user-images.githubusercontent.com/43103902/172667773-856a0f2f-e7d5-4931-bab1-d53ad67ea24c.png)

**Expected behavior:**

- Redirect user to the playground2 home page.

**Environment information** 

- Product Version: IS 6.0.0
- OS: Mac OS 12.4
- Database: MySQL 8.0.29
- User store: Primary and Secondary
- Browser: Firefox 91.0

---
PS: Can logout without any issue. Problem only occurs when you select No from the logout prompt.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
