### ISSUE TITLE
Deleting non-existing Oauth scope gives 404 as the status code 

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13881]
**Describe the issue:**
when deleting a  non-existing Oauth scope using REST API [https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/{nonexisting-name}](https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/%7Bname%7D) gives status code as 404 even though deleting non existing resources usually gives 204 in the product IS.

<img width="1512" alt="Screenshot 2022-06-08 at 12 25 30" src="https://user-images.githubusercontent.com/38417165/172551763-fa0e91d2-9f96-4ed5-97a0-1fa573e912a2.png">

**How to reproduce:**
Send a DELETE request to [https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/{nonexisting-name}](https://localhost:9443/api/identity/oauth2/v1.0/scopes/name/%7Bname%7D). Here replace nonexisting-name with a dummy value.

**Expected behavior:**
Receives 204 to keep consistency between REST API calls or check with the specification to confirm the behaviour is correct or not.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.1
 - JDK: Oracle JDK 11.0.15

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
