### ISSUE TITLE
Having localhost.com in URLs not user friendly

### ISSUE THREAD

**Issue by ramindu90** [wso2/product-is#13887]
When following the [tutorial](https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp), it asked to deploy the webapp in a server (eg: tomcat). And by default it will be served in "localhost:8080" and all the URLs in the documentation and the webapp sso.properties contains "localhost.com:8080"

It will be more user friendly if the documentation and the webapps will adhere to "localhost:8080" format

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
