### ISSUE TITLE
Many Input Fields in The "Resident Identity Provider" Page Are Not Validated

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13893]
**Describe the issue:**
The system doesn't validate the "Maximum failed login attempts" field, the "Initial account lock duration" field and the "Account lock duration increment factor" in "Account Lock" form.

<img width="1083" alt="Screenshot 2022-06-09 at 12 57 32" src="https://user-images.githubusercontent.com/12953762/172790837-f5c574a6-f0b9-492a-a8f9-f3b9be3fc7e3.png">

**How to reproduce:**
1. Open the IS management console.
2. Change values of t the "Maximum failed login attempts" field, the "Initial account lock duration" field and the "Account lock duration increment factor" in "Account Lock" section. (change them to strings in any pattern, any decimal values, or any minus integers).
3. Click on the "update" button and check the response alert.

**Expected behavior:**
Should raise a validation error for any invalid form inputs. But currently, it stores invalid form input values also.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Related issues:**
Another validation missing issue in the same page is mentioned in the [https://github.com/wso2/product-is/issues/13890](https://github.com/wso2/product-is/issues/13890) issue. Looks like many other collapsed input fields in the "Resident Identity Provider" page are not validated.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
