### ISSUE TITLE
Link to WSO2 IS Analytics Page doesn't work

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#13898]
**Is your suggestion related to a missing or misleading document? Please describe.**

Link to the WSO2 IS Analytics in [Prerequisites to Publish Statistics](https://is.docs.wso2.com/en/latest/learn/prerequisites-to-publish-statistics/) page redirects to the Identity Server page. 

<img width="724" alt="Screenshot 2022-06-10 at 09 32 41" src="https://user-images.githubusercontent.com/45028707/172987992-2f4f4150-cf0c-4e02-a728-23b21532c53d.png">

**Describe the improvement**

It should redirect to the IS Analytics download page.

**Comment by krishnakanthati** [comment]
Where is this document?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
