### ISSUE TITLE
Idle Account Suspension Configuration Form Is Not Validated

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13890]
**Describe the issue:**
The system doesn't validate the "Allowed idle time span in days" field and the "Alert sending time periods in day" field in "Idle Account Suspend" form.

<img width="1025" alt="Screenshot 2022-06-08 at 21 58 53" src="https://user-images.githubusercontent.com/12953762/172668973-9e0bd73e-c49c-4402-a3bd-9b6d2c28e979.png">

**How to reproduce:**
1. Open the IS management console.
2. Change values of the "Allowed idle time span in days" field and the "Alert sending time periods in day" field in the "Idle Account Suspend" section. (change them to strings in any pattern, any decimal values, or any minus integers).
3. Click on the "update" button and check the response alert.

**Expected behavior:**
Should raise a validation error for any invalid form inputs. But currently, it stores invalid form input values also.

**Environment information :**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
