### ISSUE TITLE
Need to document Supporting User store preference order during authentication

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#13894]
**Description:**
**Requirement**

1. AD and LDAP have configured for wrong password policies. AD and LDAP are having the same user(let's say the username is bob) with a different password.
2. Employees only can access SP1(service provider) and Employees details are stored in UserStore1(LDAP).
3. Customers only can access SP2 and Customers details are stored in UserStore2(AD).

Now if either employee or customer tries to log in to SP1 without specifying the userStoredomain then the user will be searched to both the user store domains
With 590 we can allow the users to search only through UserStore1 for SP1 application, allow the users to search only through UserStore2 by following the below steps.

 1. You need to implement the interface UserStorePreferenceOrderSupplier and write your own logic to retrieve the user store order (Example:- read from the registry). You could find the sample code in \[1]. 
2. Then extend CallBackHandlerFactory and create an object of your custom  UserStorePreferenceOrderSupplier. \[2]
3. Once you have done the above step configure the extended CallBackHandlerFactory in application-authentication.xml under the tag <ApplicationAuthentication>.<Extensions> as below.

```
<CallbackFactory>org.wso2.carbon.identity.custom.callback.userstore.CustomUserStoreOrderCallbackFactory</CallbackFactory>
```
Sample code can be found in \[3]

\[1] https://github.com/nilasini/user-store-order-callback-handler/blob/master/src/main/java/org/wso2/carbon/identity/custom/callback/userstore/RegistryBasedUserStoreOrderCallbackHandler.java
\[2] https://github.com/nilasini/user-store-order-callback-handler/blob/master/src/main/java/org/wso2/carbon/identity/custom/callback/userstore/CustomUserStoreOrderCallbackFactory.java
\[3] https://github.com/nilasini/user-store-order-callback-handler

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
