### ISSUE TITLE
Adding an already added certificate with the given alias gives 400 status code

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13897]
**Describe the issue:**
when adding an already added certificate using REST API [https://localhost:9443/t/wso2.com/api/server/v1/keystores/certs](https://localhost:9443/t/wso2.com/api/server/v1/keystores/certs?filter=alias+co+wso2) gives status code as 400 even though  usually gives 409 in the product IS.

<img width="1512" alt="Screenshot 2022-06-09 at 13 35 44" src="https://user-images.githubusercontent.com/38417165/172915915-36849722-f576-4b45-8bfd-12df27ef6dbf.png">

**How to reproduce:**
1.  Add a certificate using a tenant by sending a POST request to [https://localhost:9443/t/wso2.com/api/server/v1/keystores/certs](https://localhost:9443/t/wso2.com/api/server/v1/keystores/certs?filter=alias+co+wso2).
2.  Add the same certificate again.

**Expected behavior:**
Receives 409 to keep consistency between REST API calls.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: MacOS 12.4
 - JDK: Oracle JDK 11.0.15

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
