### ISSUE TITLE
Claim values cannot be obtained with an OIDC supported service provider or with an OIDC supported federated identity provider.

### ISSUE THREAD

**Issue by YogyaGamage** [wso2/product-is#13899]
**Describe the issue:**

Claim values cannot be obtained with an OIDC supported service provider or with an OIDC supported federated identity provider.

**How to reproduce:**

- [Configure an identity provider](https://is.docs.wso2.com/en/latest/learn/adding-and-configuring-an-identity-provider/).
- [Register an OIDC supported service provider](https://is.docs.wso2.com/en/latest/learn/adding-and-configuring-a-service-provider/#adding-a-service-provider). ([pickup-dispatch, pickup-manager or Playground2](https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/))
- Select federated authentication as authentication type of the service provider.
- [Configure claims for the service provider](https://is.docs.wso2.com/en/latest/learn/configuring-claims-for-a-service-provider/). 
- Add a user and update the user profile. 
- Sign-in to the service provider and check user information.

**Expected behavior:**

The added claims should be visible under user information. If the claims were marked as mandatory and if they already exist for the user they should be obtained without prompting the user again to add them. 
But the current behaviour is that the claims cannot be obtained and if they are marked as mandatory user has to enter them when signing in and the newly added values will be displayed under user info instead of original claim values which exist for the corresponding user. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 
 - OS: Mac
 - Browser: Firefox 91.0

---

**Related issues:**

The behaviour is same for other service providers ([saml2-web-app-pickup-manager](https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-manager-webapp)) with an OIDC supported federated IDP.

**Comment by ImalshaG** [comment]
This issue occurs only when address claims such as `country`, `locality`, `street_address`, `region`, `postal_code` and `address` are requested. Due to an issue of filtering according to user consent, the above mentioned claims are not added to the id_token unless the `address` claim is requested by the SP.

Related Issue: https://github.com/wso2/product-is/issues/13600
