### ISSUE TITLE
OIDC session iframe endpoint - error when parsing origin URL

### ISSUE THREAD

**Issue by sdamson-eventim** [wso2/product-is#1390]
We registered a service provider that uses OAuth/OpenID Connect for Inbound Authentication. The callback URL of the OIDC configuration uses a regular expression, e.g.:

`regexp=(https://www.mydomain.com/ols/[a-zA-Z0-9_-]+/[a-zA-Z_-]+/oauth/callback.*)`

The authentication works fine with a configured federated IdP, but the OIDC session iframe (/oidc/checksession?client_id=...) seems to have an issue with the regexp when it tries to get the origin URL from the callback URL registered for the client.

The WSO2 IS log shows the following error message:

`ERROR {org.wso2.carbon.identity.oidc.session.util.OIDCSessionManagementUtil} -  Error while parsing URL origin of regexp=(https://www.mydomain.com/ols/[a-zA-Z0-9_-]+/[a-zA-Z_-]+/oauth/callback.*). URL seems to be malformed.`

We would expect that the callback URL can be parsed, even if a regular expression is used.

**Comment by omindu** [comment]
Hi @sdamson-eventim 

This is a known limitation [[1]](https://wso2.org/jira/browse/IDENTITY-5424) with OIDC session management when a regex pattern is used as a callback URL. We will be fixing this in a future [WUM](http://wso2.com/wum) update for IS 5.3.0.

[1] - https://wso2.org/jira/browse/IDENTITY-5424

**Comment by sdamson-eventim** [comment]
Thanks for the quick respone :) Is there a rough estimate as to when this WUM Update might be released?

**Comment by omindu** [comment]
It shouldn't take more than 2 weeks.

**Comment by omindu** [comment]
The regex support is now available as a WUM update. You can also refer [[1]](https://wso2.org/jira/browse/IDENTITY-5424?focusedCommentId=137326&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-137326) on how to use the regexp with session management.

**Comment by sdamson-eventim** [comment]
Sorry to bother you again. Your last message stated that the Update should be available:
“The regex support is now available as a WUM update. You can also refer [1] on how to use the regexp with session management.”

I tried to update WSO2 IS via WUM, but it said there are no new updates available.

Nevertheless and just to be sure, I passed the redirect_uri with the same value used for the authorize request, as described in the linked JIRA issue https://wso2.org/jira/browse/IDENTITY-5424. But (as expected because WUM could not find any updates) the same error message “Error while parsing URL origin of …” still occurs.

At the moment during evaluation, I use WUM without an active subscription (has 83 days left for updates). Could that be an issue?

Best regards,
Stephan Damson


Von: Omindu Rathnaweera [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. Oktober 2017 18:39
An: wso2/product-is <product-is@noreply.github.com>
Cc: Damson, Stephan <Stephan.Damson@eventim.de>; Mention <mention@noreply.github.com>
Betreff: Re: [wso2/product-is] OIDC session iframe endpoint - error when parsing origin URL (#1390)


Closed #1390<https://github.com/wso2/product-is/issues/1390>.
