### ISSUE TITLE
Basic authentication is not supported in TOTP and FIDO

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13906]
**Is your suggestion related to a missing or misleading document? Please describe.**
Even though basic authentication is mentioned in the documents it's not supported with REST APIs calls to [FIDO](https://is.docs.wso2.com/en/latest/develop/fido-rest-api/) and [TOTP](https://is.docs.wso2.com/en/latest/develop/totp-rest-api/). 

<img width="1512" alt="Screenshot 2022-06-10 at 15 51 45" src="https://user-images.githubusercontent.com/38417165/173045527-490df9cf-a6b9-461c-a1c8-b58bfabedcdc.png">

**Describe the improvement**
Add necessary steps on using a token to invoke REST APIs calls to documentation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
