### ISSUE TITLE
Issue in Run in Postman functionality in Application Management Rest API Definition

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13903]
**Is your suggestion related to a missing or misleading document? Please describe.**
When trying to open Postman with _Run in Postman_ functionality in [Application Management Rest API Definition](https://is.docs.wso2.com/en/latest/develop/application-rest-api/) it redirected to a page shown in below figure instead of Postman.

<img width="1497" alt="Screenshot 2022-06-10 at 12 33 30" src="https://user-images.githubusercontent.com/38417165/173009331-ba291b10-0ec8-402a-97e7-efb6d9e8daed.png">

**Describe the improvement**
Add correct functionality to Run in Postman so that it can open API definitions in Postman.

**Comment by Anandi-K** [comment]
This issue is not reproducible.
The mentioned `Run in Postman functionality` is not available on [Application Management Rest API Definition](https://is.docs.wso2.com/en/latest/apis/application-rest-api/).

**Comment by nilminiwso2** [comment]
We will add postman collections to all API docs through this issue [1]. Therefore, let's close this one. 

[1] https://github.com/wso2/product-is/issues/13773
