### ISSUE TITLE
Unable to find Geo Location Data mentioned in the documentation

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#13900]
**Is your suggestion related to a missing or misleading document? Please describe.**

In [Enabling Geolocation Based Statistics](https://is.docs.wso2.com/en/latest/learn/enabling-geolocation-based-statistics/) section in the documentation, it mentions about `Geo Location Data/dbscripts` directory. But a link to download this is not given in the documentation.  

![Screenshot 2022-06-10 at 11 37 50](https://user-images.githubusercontent.com/45028707/173001347-da4d6efd-f5e2-47cc-a22a-7746d1c5cd08.png)

**Describe the improvement**

There should be a public link to download `Geo Location Data`. 

**Related Issues:**
https://github.com/wso2/analytics-is/issues/451

**Comment by nilminiwso2** [comment]
Will be addressed by https://github.com/wso2/product-is/issues/13541
