### ISSUE TITLE
Issue in Run in Postman functionality in OAuth2 Authorized Apps API Definition  

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#13904]
**Is your suggestion related to a missing or misleading document? Please describe.**
When trying to open Postman with _Run in Postman_ functionality in [OAuth2 Authorized Apps API Definition](https://is.docs.wso2.com/en/latest/develop/authorized-apps-v2-rest-api/) it redirected to different API definitions as shown in below figure in Postman.

<img width="1512" alt="Screenshot 2022-06-10 at 13 05 09" src="https://user-images.githubusercontent.com/38417165/173014793-3f864600-d2f0-4627-8bd6-a26a99531abc.png">

**Describe the improvement**
Add correct functionality to Run in Postman so that it can open API definitions in Postman.

**Comment by Anandi-K** [comment]
This issue is not reproducible.
The mentioned `Run in Postman` functionality is not available on [OAuth2 Authorized Apps API Definition - v2](https://is.docs.wso2.com/en/latest/apis/authorized-apps-v2-rest-api/).

**Comment by nilminiwso2** [comment]
We will add postman collections to all API docs through this issue [1]. Therefore, let's close this one. 

[1] https://github.com/wso2/product-is/issues/13773
