### ISSUE TITLE
Email Alerts for Idle Account Suspension Doesn't Work

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13918]
**Describe the issue:**
Warning email alerts that are sent after each predefined periods to the idle users are not working. It doesn't even send an alert after the allowed idle time span is over.

**How to reproduce:**
1. Configure the idle account suspension feature as documented in [https://is.docs.wso2.com/en/latest/learn/user-account-suspension](https://is.docs.wso2.com/en/latest/learn/user-account-suspension).
2. Set the 'allowed idle time span in days' and the 'alert sending time periods in days' for idle account suspensions through the IS management console as your preference.
3. Create a few user accounts in the primary user store and login to those accounts for the first time and logout to track the last active time.
4. Keep the server up and running to trigger account suspension alerts. 
5. At the suspension trigger time (default is 20:00:00), none of the users gets warning email alerts or account suspension email alerts.

**Expected behavior:**
Users that didn't login to their account should get warning email alerts and idle account suspension alerts .

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: Tested with both LDAP and JDBC with PostgreSQL 14

**Comment by ImalshaG** [comment]
Closing this issue as the flow is working fine and this issue is not reproducible based on https://github.com/wso2/product-is/issues/13919#issuecomment-1164300550.
