### ISSUE TITLE
Wrong/ Inadequate error message in Mutual TLS Client Authentication

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#13917]
**Describe the issue:**

When Mutual TLS Authenticator is configured and an authentication request is sent, the following error is received in server backend.
``ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} - Could not handle the request, could be due to the maxHttpHeaderSize limitation.``
However the maxHttpHeaderSize is 8192 Bytes and adequate for the request.

**How to reproduce:**

1. Download Identity Server
2. Configure Mutual TLS Authenticator following these [steps](https://is.docs.wso2.com/en/latest/learn/mutual-tls-client-auth/)
3. Send a request for client credentials grant type using the following curl command format
``curl -X POST \
https://localhost:9443/oauth2/token \
-H 'content-type: application/x-www-form-urlencoded' \
-H '<CERTIFICATE_HEADER_NAME>: <CLIENT_PUBLIC_CERTIFICATE>' \
-d 'grant_type=client_credentials&client_id=<CLIENT_ID>'``
4. The following error is received
``ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} - Could not handle the request, could be due to the maxHttpHeaderSize limitation.``

**Expected behavior:**

An access token is received with
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS 6.0.0-m1
- OS: MacOS 12.4
- JDK: Oracle JDK 11.0.15.1
- Database: PostgreSQL 13.2
- Userstore: JDBC

**Comment by asha15** [comment]
Tested on IS 6.0.0-m1. This issue cannot be reproduced.
