### ISSUE TITLE
IWA authentication + Basic authentication as failover

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#13912]
**Is your feature request related to a problem? Please describe.**

As per the current implementation of the IWA connector, users could only authenticate using a Kerberos token. This is controlled by the IWAServlet class by returning the `WWW-Authenticate: Negotiate` header on the initial `401 Unauthorized` response [1].

When users don't have a Kerberos token (e.g. client not enrolled in the domain) the authentication flow fails.

**Describe the solution you would prefer**

When users don't have a Kerberos token (e.g. client not enrolled in the domain) the browser could display a web form and allow users to login using their basic credentials (ergo, `Basic` as failover authentication). This could be achieved if the IWAServlet class returns both challenges on the `WWW-Authenticate` header and it can handle subsequent basic authentication requests (`Authorization: Basic` header).

**Additional context**

As per the HTTP Authentication specification [2], any of the following forms would be a valid response:
```
WWW-Authenticate: Negotiate
WWW-Authenticate: Basic
```
or,
```
WWW-Authenticate: Negotiate, Basic
```

---
[1] https://github.com/wso2-extensions/identity-local-auth-iwa-kerberos/blob/16fc9c0c30646eac24db9f290c3cc0c0680c786e/components/org.wso2.carbon.identity.application.authenticator.iwa/src/main/java/org/wso2/carbon/identity/application/authenticator/iwa/servlet/IWAServlet.java#L110
[2] https://datatracker.ietf.org/doc/html/rfc7235#section-4.1

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
