### ISSUE TITLE
Missing instructions in migration guide on migrating uniqueidjdbc userstore type 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13925]
**Describe the issue:**

When you are migrating for 5.11.0 or IS 6.0.0 from a older IS version which does not support unique id feature you need to follow below steps before the migration.

Assume you are migrating from IS 5.3.0 to IS 6.0.0

1. Configure IS 5.3.0 user store type for jdbc in user-mgt.xml
2. Configure userstore type as jdbc in the new IS pack deployment.toml

```
[user_store]
type = "database"
```
3. Run the migration client from IS new pack
4. After the migration completes succesfully if you want to switch to unique id jdbc type now you can get it configured in the new IS pack deployment.toml ( Before the migration we cant configure the userstore type for jdbc in the new IS pack if you are migrating from a unique id not supported version)

```
[user_store]
type = "database_unique_id"
```

Assume you are migrating from 5.11.0 to IS 6.0.0

As both the IS versions are supporting unique id feature you can point both the packs for unique id jdbc type before running the migration client.

```
[user_store]
type = "database_unique_id"
```

We need to get these information included in the migration guide in 5.11.0 and 6.0.0

https://is.docs.wso2.com/en/latest/setup/migrating-to-5110/

**Comment by ashendes** [comment]
Addressed in https://github.com/wso2/docs-is/pull/3232
