### ISSUE TITLE
Identity Verification with Evident - No secret key provided

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#13923]
**Describe the issue:**
When configuring the identity verification with Evident in the management console, we have to enter an API Key and API Secret.
However in the Evident account, they only provide an API Key.

When self-registering a user, the following error appears on the terminal. Here, only the API Key was set and the API secret field was kept empty.

```
[2022-06-13 10:08:00,340] [25ef0c90-af80-48c1-bcb6-7cb121e91b81]  WARN {org.wso2.carbon.identity.verification.evident.EvidentIDVHandler} - Evident identity verification is enabled but one or more required parameters are not provided
```

No email is received at the email address provided with registration process.

**How to reproduce:**
1. Configure the identitiy verification with Evident as mentioned [here](https://github.com/wso2-extensions/identity-verification-evident/blob/master/docs/README.md).
2. Self register a new user and try to login to the new account. 

**Expected behavior:**

**Environment information :**
 - Product Version: IS 6.0.0 - m1
 - OS: Mac OS 12.3.1
 - Database: Oracle12c
 - Userstore: JDBC

**Comment by asha15** [comment]
completed with https://github.com/wso2-extensions/identity-verification-evident/pull/4
