### ISSUE TITLE
Improve ELK analytic documentation

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13921]
**Describe the issue:**
Following should be improved in ELK analytic dashboard configuration documents. [1]
[1]  https://docs.google.com/document/d/134p-vnU8RU-Iu0HDJRGYgTOfb_ATcBgai8jvdx_JWuI/edit?usp=sharing

- [ ] Missing step: Update kibana.yml file according to [1]  [https://github.com/wso2-extensions/identity-elk-integration/blob/main/sso-oidc/kibana-with-oidc.yml#L41](https://www.google.com/url?q=https://github.com/wso2-extensions/identity-elk-integration/blob/main/sso-oidc/kibana-with-oidc.yml%23L41&sa=D&source=docs&ust=1655085240981932&usg=AOvVaw1KFK6usmcnB4ibB8ZxNf9T)

- [ ] Image is missing. And better we can add a sample  callback url.

`regexp=([http://localhost:5601/api/security/oidc/callback|http://localhost:5601/api/security/logout|http://localhost:5601/security/logged_out](http://localhost:5601/api/security/oidc/callback%7Chttp://localhost:5601/api/security/logout%7Chttp://localhost:5601/security/logged_out))`

![image](https://user-images.githubusercontent.com/39077751/173261364-e48dc285-3673-49a9-9a72-7926b371dd90.png)

- [ ] At role mapping configuration section it's better we can add note this Role Mapping option is enable for only platinum subscriptions.

- [ ] Add steps in Kibana configuration regarding key 
Errors without the keys
![image](https://user-images.githubusercontent.com/39077751/173264041-37f82316-88d6-41d4-99c3-8eb55f4ea033.png)

Added configuration

{KIBANA HOME}/bin/kibana-encryption-keys generate
![image](https://user-images.githubusercontent.com/39077751/173264195-ce8770eb-a753-4b34-8a6f-17c67bbb3fda.png)

- [ ]  This path [1] is difference in mac OS. Have to add suggested path for mac OS 

[1] https://github.com/wso2-extensions/identity-elk-integration/blob/main/filebeat/filebeat.yml#L13

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS-6.0.0-M4
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashensw** [comment]
@Avarjana
