### ISSUE TITLE
Errors in Kibana widgets 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13922]
**Describe the issue:**
Following errors are display on Kibana widgets 

![image](https://user-images.githubusercontent.com/39077751/173266949-58ac29d0-a746-44df-a888-8948fbf25e07.png)

![image](https://user-images.githubusercontent.com/39077751/173266969-585a0295-fe0f-4285-b6be-332252bc9476.png)

![image](https://user-images.githubusercontent.com/39077751/173267984-2894a505-0b05-4b70-bddb-4b555129f19b.png)

{```

   "statusCode":404,
   "error":"Not Found",
   "message":"No indices match \"wso2-iam-auth-raw*\"",
   "attributes":{
      "statusCode":404,
      "error":"Not Found",
      "message":"No indices match \"wso2-iam-auth-raw*\"",
      "code":"no_matching_indices"
   }
}
```


**How to reproduce:**
1. Configure Kibana [1]
2. Login to the kibana dashboards

[1] https://docs.google.com/document/d/134p-vnU8RU-Iu0HDJRGYgTOfb_ATcBgai8jvdx_JWuI/edit?usp=sharing


**Expected behavior:**
Widgets should display the data 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-6.0.0-M4
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
<!-- Any related issues from this/other repositories-->

**Suggested labels:**
<!-- Only to be used by non-members -->

**Comment by Avarjana** [comment]
I will look into it
