### ISSUE TITLE
Lock/Unlock Accounts in Secondary US Through remoteUserStoreManagerService Gives 403 Error After The First Successful Attempt

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13927]
**Describe the issue:**
Lock/unlock accounts in secondary US in a new tenant through remoteUserStoreManagerService works well in the first attempt but from the second attempt, it gives 403 forbidden error.

Scenarios tested:
1. Lock account using a SOAP request (successful) and unlock it using a SOAP request (gave 403 error)
2. Lock account using a SOAP request (successful), unlock account through management console (successful), and lock the account again using a SOAP request (gave 403 error)
3. Lock account through the management console, unlock it using a SOAP request (successful), and lock it again using a SOAP request (gave 403 error)
4. Lock account using a SOAP request (successful) and try to lock it again using a SOAP request (gave 403 error)

Please consider that 'POSTGRSQL' is my user store domain and 'pgadmin.com' is my tenant domain in following sample screenshots and curl requests. The authorization key in curl requests are created for username=pgadmin@pgspace.com and password=pgadmin

<img width="794" alt="Screenshot 2022-06-13 at 13 07 19" src="https://user-images.githubusercontent.com/12953762/173309158-f502eb7e-22d4-4414-ab20-ab569773b9f2.png">

SOAP request to lock account:
```
curl --location --request POST 'https://localhost:9443/t/pgspace.com/services/RemoteUserStoreManagerService?wsdl' \
--header 'Content-Type: text/xml' \
--header 'SOAPAction: #MethodName' \
--header 'Authorization: Basic cGdhZG1pbkBwZ3NwYWNlLmNvbTpwZ2FkbWlu' \
--header 'Cookie: JSESSIONID=E41A0AD3FFE7A765010E863AA95E7B9F' \
--data-raw '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org" xmlns:xsd="http://common.mgt.user.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:setUserClaimValues>
         <!--Optional:-->
         <ser:userName>POSTGRESQL/ravindu5</ser:userName>
         <!--Zero or more repetitions:-->
         <ser:claims>
            <!--Optional:-->
            <xsd:claimURI>http://wso2.org/claims/identity/accountLocked</xsd:claimURI>
            <!--Optional:-->
            <xsd:value>true</xsd:value>
         </ser:claims>
         <ser:profileName>default</ser:profileName>
      </ser:setUserClaimValues>
   </soapenv:Body>
</soapenv:Envelope>'
```
Sample request to unlock account:
```
curl --location --request POST 'https://localhost:9443/t/pgspace.com/services/RemoteUserStoreManagerService?wsdl' \
--header 'Content-Type: text/xml' \
--header 'SOAPAction: #MethodName' \
--header 'Authorization: Basic cGdhZG1pbkBwZ3NwYWNlLmNvbTpwZ2FkbWlu' \
--header 'Cookie: JSESSIONID=E41A0AD3FFE7A765010E863AA95E7B9F' \
--data-raw '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org" xmlns:xsd="http://common.mgt.user.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:setUserClaimValues>
         <!--Optional:-->
         <ser:userName>POSTGRESQL/ravindu5</ser:userName>
         <!--Zero or more repetitions:-->
         <ser:claims>
            <!--Optional:-->
            <xsd:claimURI>http://wso2.org/claims/identity/accountLocked</xsd:claimURI>
            <!--Optional:-->
            <xsd:value>false</xsd:value>
         </ser:claims>
         <ser:profileName>default</ser:profileName>
      </ser:setUserClaimValues>
   </soapenv:Body>
</soapenv:Envelope>'
```

**How to reproduce:**
1. Set the <HideAdminServiceWSDLs> element to false in <IS_HOME>/repository/conf/carbon.xml file.
6. Restart the IS server
7. Create a new tenant and log into that new tenant
8. Add a secondary user store in the new tenant (my secondary US is a JDBC with PostgreSQL 14)
9. Create a user in the secondary user store
10. Make the http://wso2.org/claims/identity/accountLocked claim to be supported by default
11. Send a SOAP request to https://localhost:9443/t/{tenant-domain}/services/RemoteUserStoreManagerService?wsdl in order to lock the account created in step 5 (this should give a successful response with 200 status code)
12. Send a SOAP request to https://localhost:9443/t/{tenant-domain}/services/RemoteUserStoreManagerService?wsdl in order to unlock the account created in step 5 (this gives the error 403 forbidden)

**Expected behavior:**
User account locking and unlocking SOAP requests should lock/unlock account successfully in the second attempt also. But currently it works for the first request but start to give a 403 error from the second request.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-m1
 - OS: Mac OS 12.3.1
 - Database: PostgreSQL 14
 - Userstore: JDBC with PostgreSQL 14

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
