### ISSUE TITLE
Refactor RefreshGrantHandler to reuse the AbstractAuthorizationGrantHandler issue method.

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#13929]
**Is your suggestion related to an experience ? Please describe.**
Currently the RefreshGrantHandler issue method has the same logic as AbstractAuthorizationGrantHandler. So the bug fixes and improvements have been missed to RefreshGrantHandler.  So it is better if we can reuse the logic.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
