### ISSUE TITLE
Cannot filter users via identity claims in IS 5.2.0

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#13932]
**Describe the issue:**
When identity claims are stored in the identity database - `IDN_IDENTITY_USER_DATA` table, filtering users via the identity claim results in an empty list.

This is due to the missing implementation of calling event listeners in `getUserList(String claim, String claimValue, String profileName)` method of `AbstractUserStoreManager` class [1]. Issue is already fixed for WSO2 IS 5.3.0 [2]

**How to reproduce:**

1. Configure JDBC database as the primary user store.
2. Enable `IdentityMgtEventListener` in <IS_HOME>/repository/conf/identity/identity.xml file.
```
<EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
name="org.wso2.carbon.identity.mgt.IdentityMgtEventListener" orderId="50" enable="true" />
```
3. Set `Supported by Default` value to `true` for accountLock claim (`http://wso2.org/claims/identity/accountLocked`)
4. Create a new user and change the accountLock claim value to true.
5. Go to management console -> List Users and filter users with accountLock.
- Enter user name pattern (* for all): `true`
- Select Claim Uri: `http://wso2.org/claims/identity/accountLocked`

**Expected behavior:**
The newly created user with accountLock claim true should be listed in the results.

**Environment information:**
 - Product Version: IS 5.2.0
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

[1] - https://github.com/wso2/carbon-kernel/blob/4a804d6ca25f8e51db11c1a8b557e518b995355a/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L740-L833
[2] - wso2/carbon-kernel/pull/1480

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
