### ISSUE TITLE
Search Applications by the ClientId in the Application Listing Page

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#13933]
**Is your suggestion related to an experience ? Please describe.**
On the client app side, we don't configure any app names because there is only the ClientId in OAuth/OIDC configuration cases. We have to open and view each app in the IS until the relevant ClientID is found when we need to find a relevant app config. Users should be able to filter the applications based on the clientID in the application listing page.

**Describe the improvement**
Add a feature to search applications by their ClientId.

**Comment by ravinduramesh** [comment]
Task Breakdown:
- [ ] Debug the relevant flows
- [ ] Analyze the DB performance with possible approaches
- [ ] Backend Implementation
- [ ] UI Implementation
- [ ] Unit testing
- [ ] Integration testing
- [ ] Documentation

**Comment by piraveena** [comment]
can we close this issue? @kayathiri4 @ravinduramesh
