### ISSUE TITLE
Doc Feedback: Link not working

### ISSUE THREAD

**Issue by AmilaJ** [wso2/product-is#13943]
Location : https://is.docs.wso2.com/en/5.11.0/develop/writing-a-custom-policy-info-point/

The following links not working.

"**This sample project can be downloaded [here](https://svn.wso2.org/repos/wso2/people/asela/xacml/pip/jdbc/)."**

**See [here](https://svn.wso2.org/repos/wso2/people/asela/xacml/pip/jdbc/resources/dbScript/testUserStore.sql) for a sample script that is used to create the tables.**

**Download the KMarketJDBCAttributeFinder class [here](https://svn.wso2.org/repos/wso2/people/asela/xacml/pip/jdbc/src/main/org/xacmlinfo/xacml/pip/jdbc/KMarketJDBCAttributeFinder.java) .**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
