### ISSUE TITLE
Record duplicate in ELK analytics 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13940]
**Describe the issue:**
Record duplicate in ELK analytics 

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/39077751/173772367-aefe2bd6-3e05-495f-a5a6-aefc3df18ad7.png">

**How to reproduce:**
1. Configure ELK analytic dashboard https://docs.google.com/document/d/134p-vnU8RU-Iu0HDJRGYgTOfb_ATcBgai8jvdx_JWuI/edit?usp=sharing
2.  Execute Authentication. (ex: Login to console or my account) 
3.  Access the ELK dashboard. (Session dashboard for Auth dashboard) 

**Expected behavior:**
One record should be there for authentication

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-M4
 - OS: Mac
 - Database: MSQL
 - Userstore: JDBC
 - Elasticsearch : 8.2.2
 - Logstash : 8.2.2
 - Filebeat : 8.2.2
 - Kibana : 8.2.2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Avarjana** [comment]
We can move this table visualisation to document table with [Kibana Enhanced Table](https://github.com/fbaligand/kibana-enhanced-table) plugin since they support ELK 8.X now.
