### ISSUE TITLE
Missing information on password recovery link expiry time

### ISSUE THREAD

**Issue by Pratheesha97** [wso2/product-is#13948]
In https://is.docs.wso2.com/en/latest/learn/configuring-password-reset-with-email, no documented information about the password recovery link expiration time which plays a vital role in the password recovery flow and according to the screenshot attached in the documentation (https://is.docs.wso2.com/en/latest/learn/configuring-password-reset-with-email/#:~:text=Select%20Notification%20Based%20Password%20Recovery%20check%20box), the default password recovery link expiry time is 1440 and it is not mentioned if it is in seconds or minutes. Therefore, it is essential to document the unit of time as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
