### ISSUE TITLE
Email OTP being asked for each service provider during the same session

### ISSUE THREAD

**Issue by josecu08** [wso2/product-is#13950]
**Describe the issue:**
Email OTP is being asked each time I access a service provider or the same one in other tab during the same user session

**How to reproduce:**
1. Configure email adapter and email otp on deployment.toml as per documentation
2. Configure Email OTP identity provider
3. Create 2 service providers (oauth2/openid) 
4. Configure advanced configuration for mfa with email otp
5. Access first service provider (oauth2 code flow) you'll be asked for email otp
6. Open another tab with the first service provider, you'll be asked again for email otp
7. Open second service provider in another tab, you'll be asked again for email otp

**Expected behavior:**
Email OTP should be asked once during the same session. Once you've authenticated with email otp in that session you shouldn't be asked again during that session (in IS 5.11.0 works as expected)

**Environment information**
 - Product Version: IS 6.0.0
 - OS: Mac
 - Database:  H2
 - Userstore: H2

---

**Suggested labels:**
Affected-6.0.0
Severity/Major

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
