### ISSUE TITLE
Supporting organization specific routing for structural organizations

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#13954]
**Description:**
As mentioned in https://github.com/wso2/product-is/issues/13953, organization specific routing capability is introduced. Currently this routing mechanism is only added for tenant type organizations.

We need to support the routing mechanism for structural organizations.

As for the current observation;

- For IdP management REST API there’s no actual use of supporting this path as this kind of resource management is needed only for tenant type organizations. 
- For organization management REST API this is required.
Eg: /o/{structural org domain}/api/identity/organization-mgt/v1.0/organizations -> should return the list of organizations under the structural organization.

Ideally a list of supported endpoints should be maintained to allow organization specific routing for structural organizations and block rest of the calls.

**Comment by sadilchamishka** [comment]
Tracked by - https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/47
