### ISSUE TITLE
Doc Feedback: Wrong document at this

### ISSUE THREAD

**Issue by hmh10098** [wso2/product-is#13957]
Location : https://is.docs.wso2.com/en/latest/learn/openid-connect-single-logout/
![image](https://user-images.githubusercontent.com/65597836/174211631-07eaff6e-085d-4e7f-9f99-b305c21f1970.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
