### ISSUE TITLE
Event occurrence at ELK analytic alerts take more time than expected. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#13967]
**Describe the issue:**
Event occurrence at ELK analytic alerts configure for 1 minutes but it take 5 minutes to update which is an affecting to the Alert analytic performance and accuracy.   

<img width="1433" alt="Screenshot 2022-06-17 at 15 24 40" src="https://user-images.githubusercontent.com/39077751/174295299-e5f41a17-b7e0-422b-8bdd-71a76e962032.png">

**How to reproduce:**
1. Configure ELK analytics and alert dashboard, long session (when creating rule make the time duration >2 min)
https://docs.google.com/document/d/134p-vnU8RU-Iu0HDJRGYgTOfb_ATcBgai8jvdx_JWuI/edit?usp=sharing
https://docs.google.com/document/d/1EYSZXiUmBtcfH4icqcU6Va9EZfp_3ZijRNFCxDrly74/edit?usp=sharing

<img width="567" alt="image" src="https://user-images.githubusercontent.com/39077751/174295935-b7da5d20-d97e-4ffe-a637-9e99d4830d51.png">

2. Do 3 invalid login attempt and one successful login to  console or my account
3. Navigate to any of alert dashboard and check the record update time period 

**Expected behavior:**
Record should with update within a minute in Alert dashboard, but it takes 5 minutes to update. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
@Avarjana
