### ISSUE TITLE
Get "Invalid Tenant Domain" error when using Password Reset Offline for other tenant

### ISSUE THREAD

**Issue by emilebui** [wso2/product-is#13963]
**Describe the issue:**

Password Reset Offline feature doesn't work for other tenant (it only works on carbon.super)

After enable Password Reset Offline for an user in other tenant, that user cannot login with One Time Password and always receives "Invalid Domain Error".

**How to reproduce:**
1. Create a new tenant
2. Log in to /carbon using that newly-created tenant admin
3. Enable Password Reset Offline for that tenant
4. Use Force Password Reset to an user in that tenant
5. Go to /myaccount and log in with that user
6. Get "Invalid Domain Error" 

![OTP bug](https://user-images.githubusercontent.com/33470772/174261877-435d8ae5-3328-4a26-838d-12ac8c11e531.png)

**Expected behavior:**

There shouldn't be any error and that user would be prompted to change the password right after. The feature works as expected in the master tenant (carbon.super) it should work the same for other tenant

![OTP_work](https://user-images.githubusercontent.com/33470772/174262534-7729f0f9-1c7f-4e28-86a9-c4295681c64a.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
I have tested this in 2 environment, both docker-linux and windows, using 5.11.0 version

 - Product Version: IS 5.11.0
 - OS: Window and Linux (docker)
 - Database: H2 and Postgres
 - Userstore: LDAP
---

**Comment by emilebui** [comment]
This issue also affects the Enable Password reset via email and Enable password reset via OTP features. Please take a look at those as well

**Comment by Manchiz** [comment]
Hi emilebui,

This is fixed in WSO2 IS 6.0. Please follow the documentation [1] for WSO2 IS 6.0

[1]. https://is.docs.wso2.com/en/5.11.0/learn/forced-password-reset/#offline-password-reset

Best Regards,
Sachith.
