### ISSUE TITLE
Setting up a SAML2 Bearer Assertion Profile for OAuth 2.0 - Page should be updated

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#13975]
**_Setting up a SAML2 Bearer Assertion Profile for OAuth 2.0_ document should be updated when the IS version is updated to v6.0.0**

_Link: https://is.docs.wso2.com/en/latest/learn/setting-up-a-saml2-bearer-assertion-profile-for-oauth-2.0/#setting-up-a-saml2-bearer-assertion-profile-for-oauth-20_

In this document some instructions will be out of date when the new version released. Those instruction are,
- The application should be a "**Management Application**" to be able to access the SCIM2/Users endpoint.
- In step 7, it shows SCIM1, which is now depreciated. It should be SCIM2
- Also, the default travelocity application is not working when the developer followed the given steps, the scope of that application should change to **scope=openid+SYSTEM**

**Related Issues:**
https://github.com/wso2/product-is/issues/13748

**Comment by mpmadhavig** [comment]
### Update
Even with the above given changes, the flow doesn't work as expected. Below is the response.
```
{
    "traceId": "da7d4c51-8b09-405b-845b-89f8458a6feb",
    "code": 403,
    "description": "Operation is not permitted. You do not have permissions to make this request.",
    "message": "Forbidden"
}

```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
