### ISSUE TITLE
Can not click to manage self-sign up consent purposes

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#13976]
**Describe the issue:**
In the beta console  as per the below image, it tells to click to manage self-sign up consent purposes. But it does not work

**How to reproduce:**
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/9637873/174573169-feeadf54-ba8c-46a5-bc72-8fbab0e0bc34.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
