### ISSUE TITLE
Doc Feedback: Incorrect field highlighted in self signup UI

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#13981]
**Is your suggestion related to a missing or misleading document? Please describe.**
It seems the highlighted field of the image given step 3 of this doc is incorrect.

https://is.docs.wso2.com/en/5.11.0/learn/self-registration-and-account-confirmation/#configuring-self-registration-consent-purposes

![image](https://user-images.githubusercontent.com/12439288/174723924-76927ffe-c939-4ba2-9ef9-49b037210ebc.png)

**Describe the improvement**
The *Manage self-sign-up purposes* field should be marked.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
