### ISSUE TITLE
Suggestion to add a Danger Zone for a Created secret to Delete a secret

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13994]
**Describe the issue:**
 In Console Secrets section after you create a secret theres no danger zone in the Edit tab to get a created secret deleted. If we check a IDP, SP in the list view also we can delete them using the delete icon if not in the edit view there is a danger zone to get it deleted. Suggesting to add a similar Danger Zoner for the secret edit window too

![Screenshot from 2022-06-22 13-09-21](https://user-images.githubusercontent.com/31848014/174972564-75f0e716-179e-4545-9ea7-99f4b5a3b977.png)

**Environment**
H2 defalut 
IS 6.0.0 M5

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
