### ISSUE TITLE
Getting 400 API response with UI error when select Magic Link Login from SPA sign in methods

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13991]
**How to reproduce:**

1. Create a SPA
2. Go to Sign in methods tab of the created SPA
3. Select Magic Link Login
4. Once you are navigated to the config page click Update button

Getting 400 API response and below UI error

![Screenshot from 2022-06-22 10-36-14](https://user-images.githubusercontent.com/31848014/174949943-4b002a14-28a0-41e3-a45e-392def14009b.png)
![Screenshot from 2022-06-22 10-36-29](https://user-images.githubusercontent.com/31848014/174949959-00ba2170-db9e-4dfc-afae-f836ec270adf.png)

We need to get remove the magic link login option if this is not supported in IS 6.0.0 M5

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
H2 default
IS 6.0.0 M5

**Comment by piraveena** [comment]
@savindi7 shall we close this issue if it is done?
