### ISSUE TITLE
Duplicated permissions in the permission assignment tree for Roles

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14009]
**Describe the issue:**
In the Roles creation window permissions assignment Monitor BPEL  is duplicated twice

![a](https://user-images.githubusercontent.com/31848014/175222932-0a07851d-d736-466d-9976-97789774c143.png)

**Environment information** 
IS 6.0.0 m5
h2 default

**Comment by savindi7** [comment]
The same display name `Monitor BPEL` is given for two permissions with different resource paths as follows. Ideally this needs to be fixed from the permission tree built and sent by the BE. 
Endpoint - https://is.docs.wso2.com/en/latest/develop/permission-management-rest-api/#/permissions/get_permission_management_permissions @piraveena shall we remove the UI labels?

<img width="1792" alt="Screenshot 2022-08-02 at 17 20 20" src="https://user-images.githubusercontent.com/67315176/182373750-d90a1efd-b653-475e-8f09-65869f2c6e66.png">

**Comment by Yoshani** [comment]
Fixed with https://github.com/wso2/carbon-business-process/pull/675
