### ISSUE TITLE
Retire the deprecated features from IS

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#14003]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**
Following features need to be retired from IS https://is.docs.wso2.com/en/5.11.0/setup/migrating-what-has-changed/#deprecated-features

- [ ] OpenID Connect Dynamic Client Registration (/identity/connect/register and identity/register)
- [ ] OAuth 1.0

<br class="Apple-interchange-newline">

**Describe the solution you would prefer**

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by nilasini** [comment]
Tracking through https://github.com/wso2/product-is/issues/21241
