### ISSUE TITLE
Missing steps in IS 5.11.0 migration doc

### ISSUE THREAD

**Issue by binodmx** [wso2/product-is#14011]
**Is your suggestion related to a missing or misleading document? Please describe.**
In https://is.docs.wso2.com/en/5.11.0/setup/migrating-to-5110/, there should be a note to convey the config changes to be done if it's IS-KM to IS migration. Add following content.

1. Set deployment.toml config
```
[database.shared_db.pool_options]
defaultAutoCommit = false
```
2. Ignore `GroupsAndRolesMigrator` error 
```
ERROR {org.wso2.carbon.is.migration.service.v5110.migrator.GroupsAndRolesMigrator} -  WSO2 Product Migration Service Task : Error while migrating external role permissions.
```
3. Run db queries
```
SELECT * FROM shareddb.UM_ROLE_PERMISSION WHERE (UM_DOMAIN_ID = <domain-id>) AND UM_ROLE_NAME = 'admin';
UPDATE shareddb.UM_HYBRID_ROLE SET UM_ROLE_NAME = 'admin-test' WHERE UM_ROLE_NAME = 'admin'; 
UPDATE shareddb.UM_ROLE_PERMISSION SET UM_ROLE_NAME = 'admin-test' WHERE UM_ROLE_NAME = 'admin' AND (UM_DOMAIN_ID = <domain-id>);
SELECT * FROM shareddb.UM_ROLE_PERMISSION WHERE (UM_DOMAIN_ID = <domain-id>) AND UM_ROLE_NAME = 'admin-test';
```

Also in step 10.d. `currentEncryptionAlgrithm` should be changed to `currentEncryptionAlgrithom`.

---

### Optional Fields

**Related Issues:**
https://github.com/wso2-enterprise/wso2-iam-internal/issues/19

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
