### ISSUE TITLE
Remove adding the "Organization" Attribute for the Self Registration form by default

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14015]
**How to reproduce:**
1. Access Console as super admin
2. Go to Manage > Account Management and enable self registration
3. Access Myaccount 
4. Click on Create Account

In the form that is displayed to self register there is a field as "organization". As there is a chance for a user to mis understand this as the tenant name suggesting to switch off the supported by default config for this attribute and not to display it in the self registration form.

![image (5)](https://user-images.githubusercontent.com/31848014/175258813-f9cd2308-7936-4830-9cf3-56994efc6d6b.png)

**Environment information**
IS 6.0.0 m5
H2 default

**Comment by savindi7** [comment]
The support for the fields`Organization` and `IM` to be displayed by default should be fixed in the BE @piraveena
