### ISSUE TITLE
Inconsistency in Passoword and Username hyperlinks when password & username recovery is enabled for console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14014]
**How to reproduce:**
1. Enable username and password recovery
2. Access console

Better to make P capital for the Password hyperlink as the U is also capital Username hyperlink. Or else we can make both simple

![a](https://user-images.githubusercontent.com/31848014/175243580-c8dc92bb-55f1-4543-96cf-e4f663e13e91.png)

**Environment information**
H2 default
IS 6.0.0 m5

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
