### ISSUE TITLE
Remove lite user registration from Console UI

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#14017]
**Is your suggestion related to an experience ? Please describe.**
Lite user registration is not yet marketed as a feature in IS. So that UI needs to be hidden from the Console app. 

**IS 6.0.0-alpha UI**
<img width="1157" alt="Screenshot 2022-06-23 at 15 51 38" src="https://user-images.githubusercontent.com/17597293/175277455-1c8d1879-a533-41b6-a1b9-790de83a416c.png">

But we have it in the management console UI in 5.11.0 as well
**IS 5.11.0 UI**

<img width="1200" alt="Screenshot 2022-06-24 at 09 50 10" src="https://user-images.githubusercontent.com/17597293/175461594-01f9968f-8dce-4700-bd59-a742ad6f35a7.png">
6-24 at 09.49.42.png…]()

Related issues:
https://github.com/wso2/product-is/issues/13468
https://github.com/wso2/product-is/issues/11373
**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
