### ISSUE TITLE
Revamp the Custom Local Authenticator Documentation 

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14039]
**Is your suggestion related to an experience ? Please describe.**
Current documentation for writing a custom local authenticator is found in https://is.docs.wso2.com/en/latest/develop/writing-a-custom-local-authenticator/ . This documentation needs to be revamped to make it more developer friendly. 

**Describe the improvement**
More descriptive explanations should be added to make docs more developer friendly and the methods to contribute custom local authenticator code should be added.

**Comment by nilminiwso2** [comment]
Closing this issue, as it will be addressed with https://github.com/wso2/product-is/issues/12348

Please reopen if you see any concerns.
