### ISSUE TITLE
Ability to iterate through user claim maps in adaptive script

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14038]
**Is your suggestion related to an experience? Please describe.**
Currently, it is a must to know the key to get a claim value from local and remote claim maps. But there are cases where the developer requires to know the available keys in the map in order to iterate through the map.

**Describe the improvement**
If the `keySet()` method [1] is implemented in the JsClaims[2] class, it is possible to iterate through clam maps easly like below.

```
Log.info("========= Remote claims ============");
var rmap = user.remoteClaims;
for (var key in rmap) {
    Log.info('Key: ' + key + '. Value: ' + rmap[key]);
}

Log.info("========= Local claims ============");
var lmap = user.localClaims;
for (var key2 in lmap) {
    Log.info('Key: ' + key2 + '. Value: ' + lmap[key2]);
}
```

[1] https://docs.oracle.com/javase/8/docs/jdk/api/nashorn/jdk/nashorn/api/scripting/AbstractJSObject.html#keySet--
[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/config/model/graph/js/JsClaims.java

**Comment by rksk** [comment]
The remote claim keyset can be returned like below. Need to implement the local claim list.

```
    @Override
    public Set<String> keySet() {
        if (authenticatedUser != null) {
            if (isRemoteClaimRequest) {
                Map<ClaimMapping, String> attributesMap = authenticatedUser.getUserAttributes();
                Map<String, String> remoteMapping = FrameworkUtils.getClaimMappings(attributesMap, false);
                return remoteMapping.keySet();
            } else {
                if (isFederatedIdP()) {
                    // Local mapped claim list of federated user
                } else {
                    // Local claim list of the local user
                }
            }
        }
        return Collections.emptySet();
    }
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
