### ISSUE TITLE
Adding config value to identity.xml.j2 to support Enable password expiry enforcement in Oauth API calls

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#14037]
**Is your suggestion related to an experience ? Please describe.**
Adding _oauth.enable_password_reset_enforcement_ value to identity.xml.j2 file

**Describe the improvement**
This config element enables password expiry enforcement for Oauth2 Password Grant flow

**Related Issues**
- https://github.com/wso2/product-is/issues/13877
- https://github.com/wso2/product-is/issues/13876

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
