### ISSUE TITLE
WSO2 IS 5.3.0 not loading taglib directive

### ISSUE THREAD

**Issue by halapastefan** [wso2/product-is#1403]
**Description**

We have some custom pages that are deployed on WSO2 is. In version 5.0.0 everything is working as it should, but when we upgraded to 5.3.0 there is problem loading with taglib directive.

**How problem manifests**

There is placeholder for value ${somevalue} and there is definition of that value <c:set var="somevalue" value="/some/path/" />. In places where this value has to be injected just ${somevalue} is present it is not replaced with defined value.

Version of tomcat: 7
Jstl on pages: 1.2
Servlet: 2.5
Old version of IS: 5.0.0
New version: 5.3.0

**Comment by sagara-gunathunga** [comment]
This should be fixed in IS 5.5.0, please test and reopen if it's not working.
