### ISSUE TITLE
Integration Test - SAML ART Resolve is not working for JAVA 11 and above

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#14041]
Test Case:
https://github.com/wso2/product-is/blob/master/modules/integration/tests-integration/tests-backend/src/test/resources/testng.xml#L121

Reason:

The app we are using (Tr\avelocity) currently uses javax libraries which are encapsulated in Java 11. Hence we get 500 errors. 
Since this repo(Identity agent SSO) moved to the attic we need to bump to Asgardeo SDKs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
