### ISSUE TITLE
Doc Feedback: deployment.toml doesnt have the setting specified

### ISSUE THREAD

**Issue by luisluix** [wso2/product-is#14044]
Location : https://is.docs.wso2.com/en/latest/learn/configuring-office-365-ws-federation-with-identity-server/

under Configuring Office 365 WS-Federation, step 10:
Add the following user store property to the <IS_HOME>/repository/conf/deployment.toml file.
`<Property name="transformObjectGUIDToUUID">false</Property>`

is that correct?, seems like a copy paste from  the older version https://docs.wso2.com/display/IS541/Configuring+Office+365+WS-Federation+with+Identity+Server. Except that in the older version the change was in user-mgt.xml not deployment.toml I dont think that change can happen in the deployment toml, unless there is new syntax.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
