### ISSUE TITLE
 Security Manager is not Working as expected - IS 5.11.0

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#14040]
Java security manager will be deprecated with JDK 17[1] and removed in future releases. We need to analyze and check the impact of this on the wso2 identity server.

I tested in 5.12-alpha and it's not working as expected.

I got 
```
Secure Connection Failed

An error occurred during a connection to localhost:9443. SSL peer was not expecting a handshake message it received.

Error code: SSL_ERROR_HANDSHAKE_UNEXPECTED_ALERT
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
