### ISSUE TITLE
Add recommended JDBC connection properties by default  

### ISSUE THREAD

**Issue by kasunbg** [wso2/product-is#1404]
For proper behavior of JDBC secondary userstore managers, following properties should be added to the userstore configuration. These are the minimum configuration needed. Without these configuration, there can be issues such as long-running idle connections.

As a further enhancement, it is vital to provide UI options to configure these as well. In case of tenants, the workaround of adding this via the file system is also not possible.

```
      <Property name="testWhileIdle">true</Property>
      <Property name="testOnBorrow">true</Property>
      <Property name="removeAbandonedTimeout">60</Property>
      <Property name="maxAge">50000</Property>
      <Property name="minEvictableIdleTimeMillis">30000</Property>
```

**Comment by IsuraD** [comment]
Added properties by default in secondary user store configs in https://github.com/wso2/carbon-kernel/pull/1921
