### ISSUE TITLE
[Migration] Remove SupportedByDefault config for some attributes

### ISSUE THREAD

**Issue by Anandi-K** [wso2/product-is#14059]
The attributes `Orgaization` and `IM` which were marked as `SupportedByDefault` will be removed from the `SupportedByDefault` config.

If a user wants to make those attributes as default, they can do it from management console.

### Related Issues
https://github.com/wso2/product-is/issues/14015

### Related PRs
https://github.com/wso2/carbon-identity-framework/pull/4091

**Comment by ashendes** [comment]
Changing existing claim configurations will affect the previously accepted user interfaces and experiences. Hence, this will not be included in the migration client.
