### ISSUE TITLE
Artefacts shared in practical-exercise-access-delegation-oauth-2 are not compatible with the IS 5.11.0

### ISSUE THREAD

**Issue by yumaniranaweera** [wso2/product-is#14058]
**Is your suggestion related to a missing or misleading document? Please describe.**
Noticed few updates needed for samples shared in https://lms.wso2.com/courses/take/wso2-identity-server-fundamentals-v5-11/pdfs/22647867-practical-exercise-access-delegation-oauth-2-0

**Describe the improvement**
1. Pickup-dispatch app does not support the latest IS because the sample was bundled with older security files.
As a quickie to proceed with the sample in the local env we replaced the wso2carbon.jks with that of the IS. But in the actual content, the samples needs to be rebuilt with compatible security files.

2. In the same sample the backend-service.jar gives a NoClassDefFoundError when been invoked. This was addressed by switching to jdk 8 from jdk11. Suggest we make a note of this in the materials and advice the trainee to export the relevant JAVA_HOME variable in the particular terminal OR stick to one jdk version as the product is supporting the version 11, why not samples also follow the same.

3. In the same scenario we get an error when we click to "Add" a booking with the "Backend-service" enabled. This was resolved by re-building the sample with the new wso2carbon.jks. Need to be fixed in training artefacts.

4. After resolving above when you try to add a booking it gives the below error [attached], which was resolved by adding [1] to the deployment.toml.  Please review and update the guidelines accordingly.
[1]:
```
[resource_access_control.introspect]
permissions = []
```

<img width="1124" alt="Screenshot 2022-06-29 at 12 03 50" src="https://user-images.githubusercontent.com/20108932/176368278-4621a17f-dd86-44f6-8c46-2d0bd60f9c74.png">

Have also described points in detail here:
 https://yumanimanodyaranaweera.medium.com/access-delegation-oauth-2-0-sample-wso2-4c5d893337c0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
