### ISSUE TITLE
Continue Logout Option given in the unauthorized access page is not working when a IDP is set for Console App

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14065]
**How to reproduce:**
1. Add below confi to deployment.toml to make console and myaccount apps editable

`[system_applications]
read_only_apps = []`

2. Login to console and register Google as a IDP
3. List the Console app from the Applications list
4. Go to Sign in methods tab
5. Select Google 
6. And update the configs to select Google as a IDP 
7. Try to logout from the console
8. Will get land to a authorized error page
9. Click the logout option avilable in that page

Logout will not get success and user will be kept landing to the same error page.
Dont we need to handle such a scenario in a more user friendly manner . If not we may block a user from configuring sign in methods option for the Console App from a IDP 
After trying this flow pack becomes un usable as the user cannot access the console again 

![a](https://user-images.githubusercontent.com/31848014/176614871-a4916ade-f3ae-46c7-8fce-5006b194182a.png)

https://user-images.githubusercontent.com/31848014/176614885-e70ec7f9-92b3-4f53-a870-6dc321f6743d.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 6.0.0 alpha
h2 default

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
