### ISSUE TITLE
Support ETag for resource versioning

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#14063]
### Describe the issue

Identity Server should fully support resource versioning as a part of the SCIM2 core specification https://datatracker.ietf.org/doc/html/rfc7644#section-3.14 IS already supports the meta object according to the
specification like the following: -

```
{
  "meta": {
    "resourceType": "User",
    "created": "2011-08-01T21:32:44.882Z",
    "lastModified": "2011-08-01T21:32:44.882Z",
    "location": "https://example.com/v2/Users/2819c223-7f76-453a-919d-413861904646",
    "version": "W/\"e180ee84f0671b1\"",
    ...rest
  }
}
```

 However, the meta.version is not supported as of yet, We need to fully support it.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
