### ISSUE TITLE
Return all the remote claims returned from the IDP in the adaptive script

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#14064]
**Is your suggestion related to an experience ? Please describe.**
In the current implementation, we can't list all the remote claims returned by the IDP in the adaptive script. Only available option was to use `context.currentKnownSubject.remoteClaims[<claim-url>]` which will give the value. But to invoke this we need to know the key (claim URL) returned by the IDP. 

So it would be a better developer experience if we have a way to get the claim URLs returned  by the IDP as a list, then we can loop through them and get the values. Or return claim URL and claim value as json or map.

**Comment by rksk** [comment]
Same https://github.com/wso2/product-is/issues/14038

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
