### ISSUE TITLE
Account recovery API properties are not documented

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#14076]
With regard to the [account-recovery](https://docs.wso2.com/display/IS590/apidocs/account-recovery/#!/operations#PasswordRecovery#recoverPasswordPost) APIs, the request is stated as follows (ex: recover-password)
```
curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"user": {"username": "[USERNAME]","realm": "[USER STORE NAME]","tenant-domain":"[TENANT DOMAIN NAME]"},"properties": []}' "https://localhost:9443/api/identity/recovery/v0.9/recover-password?type=email&notify=true"
```
However, the expected structure of the `properties` is not specified.
```
{
    "user": {
        "username": "user1"
    },
    "properties": [
        {
            "key": "KEY",
            "value": "VALUE"
        }
    ]
}
```
Moreover, the applicable values for the key are not listed either (Ex: callback).
```
"properties": [
        {
            "key": "callback",
            "value": "callBackURL"
        }
    ]
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
