### ISSUE TITLE
Adding social login support for MyAccount and Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14079]
**Is your feature request related to a problem? Please describe.**

At the moment we do not support social login option for Myacoount and Console in onprem product version IS 6.0.0. This issue is created to track this feature request

We need to cater following use cases and handle them properly when implementing this feature

- [ ] https://github.com/wso2/product-is/issues/14066
- [ ] https://github.com/wso2/product-is/issues/14065

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
