### ISSUE TITLE
Cannot remove a added IDP from the Sign in Tabs with the provided Cross mark to delete.

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14070]
**How to reproduce:**
1. Register a SPA
2. Register a IDP > Google
3. List the registered app from Console app
4. Go to Signin tabs
5. Select Google and Update
6. Now in the same window try to get the added IDP deleted from the displayed Cross mark
7. When navigate to the cross mark a popup comes covering the cross mark 

Due to this behavior even though there is a cross mark to get the IDP deleted that is not clickable

![a](https://user-images.githubusercontent.com/31848014/176632799-1115a976-b198-4891-9f9e-95eb95fcf5f4.png)

![Screenshot from 2022-06-30 13-31-56](https://user-images.githubusercontent.com/31848014/176631918-b80f7b79-ed40-4dd2-8818-c79678b59c96.png)

https://user-images.githubusercontent.com/31848014/176632247-42257266-46ae-444c-8295-18d6876f075c.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 H2 default
IS 6.0.0 alpha

**Comment by piraveena** [comment]
Couldn't reproduce this issue with 6.0.0 beta pack
