### ISSUE TITLE
Support Azure AD joined device authentication

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14078]
**Describe the improvement**

In order to provide support for [Azure AD joined device](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-ad-join) authentication with multi-tenancy, the following product improvements are required.

1. Multi-tenant support for STS service
2. Support both tenant-aware & tenant usernames in the UT token of the STS request
3. Mex endpoint multitenancy support
4. Add missing endpoints in mex endpoint that are required for this flow
5. WS-Trust response issuer name to be configured in a multi-tenanted way

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
