### ISSUE TITLE
Self Register API properties are not documented

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#14077]
With regard to the [self-registration](https://docs.wso2.com/display/IS511/apidocs/self-registration/#!/operations#SelfRegister#resendCodePost) APIs, the request is stated as follows (Ex: resend-code)
```
curl -X POST -H "Authorization: Basic <Base64Encoded_username:password>" -H "Content-Type: application/json" -d '{"user":{"username": "<username>","realm": "<user_store_name>"},"properties": []}' "https://localhost:9443/api/identity/user/v1.0/resend-code"
```
However, the expected structure of the `properties` is not specified.
```
"properties": [
        {
            "key": "KEY",
            "value": "VALUE"
        }
]
```
Moreover, the applicable values for the key and the values are not listed either (Ex: RecoveryScenario, NOTIFICATION_BASED_PW_RECOVERY).
```
"properties": [
        {
            "key": "RecoveryScenario",
            "value": "NOTIFICATION_BASED_PW_RECOVERY"
        }
    ]
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
