### ISSUE TITLE
Getting Something Went Wrong After a Permission Update operation for a newly added Role in Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14097]
**How to reproduce:**
1. Login to console as admin user
2. Go to Manage > Roles and add a new role
3. After Role is created will get landed on Role edit page
4. From there go to permissions tab
5. Untick the assigned permissions and click update
6. Now navigate to users tab and come back for permissions tab

Both the tabs will show as loading and will not get loaded
Click on Approvals Option from left side menu or some other menu getting something went wrongs after this operation

Refer the attached video

![Screenshot from 2022-07-04 10-50-25](https://user-images.githubusercontent.com/31848014/177086885-9eb2fcba-c1c1-4481-a0f3-94955a64aa2e.png)

https://user-images.githubusercontent.com/31848014/177086851-6a9c9ddd-a712-4529-a82e-78f1e9341e27.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

IS 6.0.0 alpha 2
H2 /default

**Comment by piraveena** [comment]
Initially, you assigned the user admin a new role, and then removed the permissions of that role. When there is a permission change happens to a role assigned, we will revoke all the tokens of that user by considering that as a permission change for that user.
