### ISSUE TITLE
Console Manage section Multi Factor Authenticators menu panel is not consistent with others

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14096]
**How to reproduce:**
1. Access console as admin
2. Go to Manage > Multi Factor Authenticators

When navigating for Multi Factor Authenticators the right hand side menu panel goes to the bottom of the page. If you click on a item in the panel then suddenly it will go for the upper section of the page. This behavior is not consistent with the other features in the console. Attaching a video
![a](https://user-images.githubusercontent.com/31848014/177085254-ffcb9452-80e7-4551-89b3-f32c59e24aff.png)

https://user-images.githubusercontent.com/31848014/177085267-d092f881-6190-481e-a50d-75b04d3eff92.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 6.0.0 alpha 2
H2 default

**Comment by pavinduLakshan** [comment]
Closing as this is not reproducible with the latest UI in IS 7.0
