### ISSUE TITLE
Maven build fails running unit tests from Identity Test Back-end Module.

### ISSUE THREAD

**Issue by jeffreyschultz** [wso2/product-is#1409]
I cloned the 5.3.0 branch of the repository and built it from the terminal.

`mvn install`

[INFO] Identity Test Back-end Module ...................... FAILURE [07:54 min]
[INFO] org.wso2.identity.integration.test ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:02 min
[INFO] Finished at: 2017-10-14T14:58:45-04:00
[INFO] Final Memory: 178M/1527M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project org.wso2.carbon.identity.integration.backend.test: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.wso2.carbon.identity.integration.backend.test

**Comment by jeffreyschultz** [comment]
Is anyone else experiencing this error when building from source?

**Comment by omindu** [comment]
Hi @jeffreyschultz 

Have you increased the memory in the MAVEN_OPTS ? Please refer [[1]] (https://wso2.github.io/using-maven.html) for configuring maven option for the build.

**Comment by jeffreyschultz** [comment]
I was not using those MAVEN_OPTS and have made the change to my environment variables. I will let you know how it goes.

Thank you!

**Comment by jeffreyschultz** [comment]
This resolved my issue. Thank you!
