### ISSUE TITLE
Unable to create/ update OAuth SP: Uncaught TypeError

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#14091]
**Describe the issue:**
In the latest update of IS 5.7 (1655531967629), if the refresh grant is removed from the list of supported grant types by removing the element below from identity.xml,
```
<SupportedGrantType>
    <GrantTypeName>refresh_token</GrantTypeName>
    <GrantTypeHandlerImplClass>org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler</GrantTypeHandlerImplClass>
</SupportedGrantType>
```
OAuth app creation and update gets failed in the management console, due to the line [if (!$(jQuery("#grant_refresh_token"))[0].checked) {](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.0.53/components/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/edit.jsp#L283) (since the grant_refresh_token element is not available), with the error below in the browser console.
```
add.jsp?spName=SP2:465 Uncaught TypeError: Cannot read properties of undefined (reading 'checked')
    at validate (add.jsp?spName=SP2:465:62)
    at onClickAdd (add.jsp?spName=SP2:416:29)
    at HTMLInputElement.onclick (add.jsp?spName=SP2:948:120)
```

**Comment by rajithacharith** [comment]
Closing the issue since IS 5.7 U2, WUM and Public PRs merged.
