### ISSUE TITLE
Validate the organization hierarchy in the organization management REST API

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#14100]
**Description:**
As mentioned in https://github.com/wso2/product-is/issues/13953, organization-specific routing capability is introduced and as stated in https://github.com/wso2/product-is/issues/13955, API calls that are invoked in the /o/{org domain} path are authorized based on the new permission model.

Let's consider the below given organization hierarchy

![v drawio](https://user-images.githubusercontent.com/24982871/177125229-fc17d0d3-f8c2-43a2-8bb3-d26153f52d3a.png)

The following organization management API calls:

- `https://localhost:9443/o/<org A id>/api/server/v1/organizations/<root org id>` -> root org is the parent of org A
- `https://localhost:9443/o/<org A id>/api/server/v1/organizations/<org B id>` -> both orgs are in the same level in the tree
- `https://localhost:9443/o/<org A id>/api/server/v1/organizations/<org B_1 id>` -> org B_1 is not a child of org A
- `https://localhost:9443/o/<root org id>/api/server/v1/organizations/<org B_1 id>` -> org org B_1 is not an immediate child of root org
- `https://localhost:9443/o/<org A id>/api/server/v1/organizations/<org A id>` -> same org

return successful results given that the authorization evaluation at the valve level is successful since the user has the relevant permissions for the organization domain (`o/<org domain>`)

However, these paths should be blocked to honor the hierarchy levels in the organization tree. 

Only the following request format should be supported:
`/o/<org domain>/api/server/v1/organizations/<immediate child of the org represented by the org domain>`

Probably this will need to be handled at the organization management service level, rather than at the authorization valve as this validation is only required for the organization management endpoints.

**Comment by sadilchamishka** [comment]
Tracked by - https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/30
