### ISSUE TITLE
Showing an error message popup when adding a new consent purpose

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#14102]
**Describe the issue:**
When adding a new consent purpose from the management console, an error message popup with the error `Error while loading claim info. Error: null` is shown for a very short time. The consent purpose gets successfully added and the success message is also shown. 

**How to reproduce:**

- Login to management console
- Click on the Add button under Consent Purposes in the Manage section in the Main tab
- Fill the required fields and click Finish (Close the warn log about not having email address as a PII category)

**Expected behavior:**
The error message should not be shown if the consent purpose is added successfully. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-alpha2
 - OS: Linux

https://user-images.githubusercontent.com/36252628/177149606-97b29f9a-adfe-41fd-9ac9-6919a3c2de6e.mp4

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
