### ISSUE TITLE
Enable enable_complex_multivalued_attribute_support Configuration by default

### ISSUE THREAD

**Issue by Anandi-K** [wso2/product-is#14110]
**Describe the improvement**
`enable_complex_multivalued_attribute_support` configuration is set to `false` by default. This should be set to `true` instead to support multi-valued complex attributes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
