### ISSUE TITLE
Service Provider Claim Dialect configuration field is misguiding

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14112]
**Describe the issue:**
The "Service Provider Claim Dialect" configuration field is misguiding. As mentioned in https://github.com/wso2/product-is/issues/11390#issuecomment-806419822, The expected use case of this configuration is eIDAS SAML Attribute Profile for IS [1]. 

This has to be mentioned in the UI itself without having a generic name. The doc issue is tracked in https://github.com/wso2/product-is/issues/4439.

**This has to be considered as a bug since the product has failed to explain the usage of this configuration.**

[1] https://is.docs.wso2.com/en/5.10.0/learn/eidas-saml-attribute-profile-support-via-wso2-identity-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
