### ISSUE TITLE
addresses.formatted SCIM attribute must be a combination of other sub-attributes of addresses

### ISSUE THREAD

**Issue by Anandi-K** [wso2/product-is#14111]
**Describe the improvement**

Since `urn:ietf:params:scim:schemas:core:2.0:User:addresses` is a complex multi value attribute, underlying there are multiple claims and sub attributes.

`urn:ietf:params:scim:schemas:core:2.0:User:addresses.formatted` SCIM attribute must be a properly ordered combination of following SCIM attributes
```
- urn:ietf:params:scim:schemas:core:2.0:User:addresses.region
- urn:ietf:params:scim:schemas:core:2.0:User:addresses.postalCode
- urn:ietf:params:scim:schemas:core:2.0:User:addresses.streetAddress
```
ATM we do not preserve above condition.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
