### ISSUE TITLE
admin Login failed

### ISSUE THREAD

**Issue by vialogic-admin** [wso2/product-is#14121]
**Describe the issue:**

When we start wso2 IS and try to access admin dashboard.Wso2 give an error ( Login failed! Please recheck the username and password and try again.)
**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
@vialogic-admin Thanks for reporting the issue. Can you give the IS version you tested and which app you are trying to log in?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
