### ISSUE TITLE
TOTP UI/UX improvement

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#14134]
In the existing implementation when viewing configured QR code, the modal shows a link to regenerate, a field to input TOTP and a button to Verify. Since this is not user friendly, suggestion is to show only the option to regenerate when view a configured QR code. Click on regenerate directs user to scan the new QR code and verify new TOTP.
Better to warn the user that regenerating QR code will invalidate the previous TOTP configuration.

Existing modal shown for both configure and view QR code:
![Existing Modal](https://user-images.githubusercontent.com/37938529/177569876-2adbfed2-e568-476d-8ab8-130157a3b1ef.png)

**Comment by JayaShakthi97** [comment]
**Improved UI designs**

1. Configure QR code modal:
![Configure QR code modal](https://user-images.githubusercontent.com/37938529/177570614-b2e97479-1f8a-4451-b3c5-a09257ced736.png)


2. View QR code modal:
![View QR code modal](https://user-images.githubusercontent.com/37938529/177571266-5c069ab1-d3ac-48c6-97d7-6d8b6fbde14a.png)


3. When clicked on Regenerate:
![When clicked on Regenerate](https://user-images.githubusercontent.com/37938529/177571426-6ddc6102-4953-46f9-b4d3-8cbd6ffbc2b8.png)

**Comment by piraveena** [comment]
@JayaShakthi97 can we close this issue if this is already done?
