### ISSUE TITLE
Create a Lite User - cURL command spelling error

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#14139]
**Is your suggestion related to a missing or misleading document? Please describe.**
The cURL command to create a lite user has a spelling error. It is mentioned "preferedChannel" where it should be mentioned as "preferredChannel". 

https://is.docs.wso2.com/en/latest/learn/lite-user-registration/#create-a-lite-user

**Describe the improvement**
"preferedChannel"   ->    "preferredChannel"

**Comment by DMHP** [comment]
In the current sample it has ' preferredChannel '. Hence closing the issue.
