### ISSUE TITLE
JWT Token with oauth implicit grant

### ISSUE THREAD

**Issue by csbrogi** [wso2/product-is#1413]
I have run into a problem while trying to use wso2is-5.4.0-alpha3 with oauth and implicit grant.
I have configured an identity provider and a service provider with inbound OAuth/OpenID Connect Configuration.
When I call this url:
https://localhost:9443/oauth2/authorize?client_id=1sza9L0xEFrzMzJaMOGyjUtBV9Ua&nonce=dgfhsdf&redirect_uri=https:%2F%2Flocalhost:9000%2Flogin&response_type=id_token+token&scope=urn:usrexp:subscription+sf:bpm+openid
the returned token is:
{
  "sub": "csbrogi",
  "aud": [
    "1sza9L0xEFrzMzJaMOGyjUtBV9Ua"
  ],
  "azp": "1sza9L0xEFrzMzJaMOGyjUtBV9Ua",
  "iss": "https://localhost:9443/oauth2/token",
  "given_name": "Clemens",
  "exp": 1508150101,
  "family_name": "Brogi",
  "iat": 1508150041,
  "jti": "6433906b-0d4c-4efd-8730-248a601f14ee"
}
As far as I understand, the Implicit flow of this token should contain the configured claim information, but it doesn't.
If I send the returned token to
https://localhost:9443/oauth2/introspect Interface
it produces this result:
{
  "sub": "csbrogi@carbon.super",
  "http://wso2.org/gateway/applicationname": "Smartfacts",
  "http://wso2.org/claims/dob": "19001010000000.0Z",
  "http://wso2.org/claims/role": [
    "MID.Test.Development",
   ...
    "smartfacts-bpm-all",
  ],
  "iss": "http://wso2.org/gateway",
  "http://wso2.org/claims/identity/verifyEmail": "c.brogi@somedomain",
  "http://wso2.org/claims/givenname": "Clemens",
  "http://wso2.org/gateway/subscriber": "csbrogi@carbon.super",
  "http://wso2.org/gateway/enduser": "csbrogi@carbon.super",
  "http://wso2.org/claims/displayName": "Clemens Brogi",
  "http://wso2.org/claims/fullname": "Clemens Brogi",
  "http://wso2.org/claims/emailaddress": "c.brogi@somedomain",
  "http://wso2.org/claims/postalcode": "...",
  "http://wso2.org/claims/lastname": "Brogi",
  "http://wso2.org/claims/streetaddress": "...",
  "exp": 1508226083,
  "iat": 1508225161
}
I would have expected the first token to contain this claim information, specifically only the information configured below "Service Providers/Claim Configuration".
Is this a bug or am I missing something?

**Comment by dewniMW** [comment]
Configured claim information can be obtained by using either of the 2 following methods.

1) By decoding the received ID token via a JWT decoder.

2) By using token introspection endpoint.

Send the request for token introspection as shown in the command below. Replace the token with the received access token. For required_claims put the claims you want to obtain.
curl -k -u admin:admin -H 'Content-Type: application/x-www-form-urlencoded' -X POST --data 'token=b3c1d947-0ae5-3620-b9da-b3ebefa6fb54&required_claims=http://wso2.org/claims/emailaddress,http://wso2.org/claims/country,' https://localhost:9443/oauth2/introspect

In the response you will receive a JWT. Decode this to get the requested claims.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
