### ISSUE TITLE
Updates required in Service Provider section

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#14133]
**Description:**

> http://127.0.0.1:8000/identity-and-access-management/guides/applications/service-provider-overview/
Update the document

> http://127.0.0.1:8000/guides/applications/register-sp/
Update the link for `Logging in to WSO2 Products via the Identity Server` under `Related Topics`.
Get approval for `Service provider configurations`

> http://127.0.0.1:8000/identity-and-access-management/guides/applications/inbound-auth-for-sp/
A doc reference is not available for `Kerberos`, `WS-Federation (Passive) Configuration`, and `OpenID` configurations.
Update the link for `Logging in to WSO2 Products via the Identity Server` under `Related Topics`.
Confirm the authenticator processes with a dev. `Request Processor` and `Response Builder`
Verify the reason for the ticks corresponding to certain protocols

> http://127.0.0.1:8000/identity-and-access-management/guides/applications/local-outbound-auth-for-sp/
Yahoo should be removed from the lists
Verify the updated configs for `Multi-step` and `multip-option`

> http://127.0.0.1:8000/identity-and-access-management/guides/applications/inbound-provisioning-for-sp/
There is no mention of `Enable Dumb mode`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
