### ISSUE TITLE
Hashing algorithm for certificate thumbprint generation is changed from SHA-1 to SHA-256

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14131]
**Is your suggestion related to a missing or misleading document? Please describe.**
With the change done in [1], the certificate thumbprint generation hashing algorithm is changed from SHA-1 to SHA-256. This affects all the OAuth flow including JWT tokens, JWKS endpoint, etc. Therefore, if someone is migrating to IS 5.10.0 or a later version from <=5.9.0, all the previously issued JWTs will not be validated against the new thumbprint included in the JWKS response of the new version.

This has to be documented in the change log.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1287

**Comment by divyaamunugama** [comment]
Hi Sajith, 

We added the following section to the `What had changed` document to solve this issue in both IS 5.10.0 and 6.0.0.

```
### Thumbprint certificate hashing algorithm		
From IS 5.10.0 onwards, the hashing algorithm used for thumbprint certificate generation is updated to `SHA-256`. For versions before IS 5.10.0, Identity Server used `SHA-1` as the hashing algorithm used for thumbprint certificate generation.
		
Therefore if a user is migrating from IS 5.9.0 or a lower version to IS 6.0.0, the previously issued JWTs will not be validated against the new thumbprint included in the JWKS response of the latest version.
```

We made minor changes to the content based on the IS versions.

Appreciate any feedback on this. 

Thank you, 
Divya
