### ISSUE TITLE
Adaptive Script Templates are displayed in Managemnt Console for Apps created from Console against OpenJDK 17.0.2.1

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14147]
**Describe the issue:**

**How to reproduce:**
1. Install openjdk 17.0.2.1 in windows 11
2. Set JAVA_HOME
3. Up the pack with bat file
4. Navigate to Console
5. Add a APP
6. Add a IDP
7. Go to Apps sign in tabs
8. Add the registered IDP
9. Click Update
10. Adaptive templates not visible in Console
11. Go to managemnt console and list the created apps outbound configs > advanced configs

Adaptive Templates are still displayed

The behaviour obsered on oracle JDK 17 and Openjdk 17 was bit different here. Against oracle JDK if you create a application from managemnt console adaptive templates will be displayed. But in openjdk if we create the app via managemnt console then adaptive templates were not displayed. Observed the problem when create apps from console and list from managemnt console
Pls check whather this is also due to the same root cause https://github.com/wso2/product-is/issues/14132

attaching video

https://user-images.githubusercontent.com/31848014/177800090-cc4dbab1-60f3-4a32-ab8a-e465907c2b5e.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 
openjdk 17.0.2.1
IS 6.0.0 alpha 3 snapshot
windows 11

**Comment by Thumimku** [comment]
We were unable to reproduce it on Linux.

.

**Comment by ShanikaWickramasinghe** [comment]
@Thumimku this issue was reproducing against windows as attached above screen recording. I think a fix you have done has now fixed the issue in the latest pack. Pls get it verified with the steps mentioned and close the issue if the issue is fixed in the latest pack now.

**Comment by nirmal101** [comment]
- Able to see in Windows 10, OpenJDK 17

![image](https://user-images.githubusercontent.com/43103902/178197518-33612e13-f53c-44c8-b07a-807e78124b8c.png)
