### ISSUE TITLE
Cannot start the pack with Open JDK 17 against Windows OS

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14143]
**How to reproduce:**

1. Get the pack alpha 3 snapshot
2. Install open jdk 17.0.2.1 on windows 11
3. Set Java_HOME
4. Try to up the pack

Getting below Error

![javaopenjdk](https://user-images.githubusercontent.com/31848014/177752030-16f8dd4c-5268-4c32-b134-3e500b0c2cbb.png)

When add a new environmental variable as CARBON_HOME for running packs IS-HOME path still getting below error.

![image (6)](https://user-images.githubusercontent.com/31848014/177752595-bfc6e932-d5f6-44c1-9404-c4991d4028ce.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

Open jdk 17.0.2
Windows 11

**Comment by Thumimku** [comment]
[wso2server.zip](https://github.com/wso2/product-is/files/9062761/wso2server.zip)
Above is a sample fix
