### ISSUE TITLE
Update Docs on enabling user account suspension on secondary user stores

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#14152]
**Is your suggestion related to an experience ? Please describe.**

The documentation [1] for idle user account suspension does not include configurations to enable the same for secondary user stores

**Describe the improvement**

Need to include the following details in the documentation [1]

Add property **NotificationReceiversRetrievalClass** to the XML file of the secondary user store resides in *<IS_HOME>/repository/deployment/server/userstores* directory for super tenant and *<IS_HOME>/repository/tenants/<tenantid>/userstores* directory for other tenants.

1. For LDAP user store 
*\<Property name="NotificationReceiversRetrievalClass">org.wso2.carbon.identity.account.suspension.notification.task.ldap.LDAPNotificationReceiversRetrieval\</Property>*

2. For JDBC user store
*\<Property name="NotificationReceiversRetrievalClass">org.wso2.carbon.identity.account.suspension.notification.task.jdbc.JDBCNotificationReceiversRetrieval\</Property>*

[1] - https://is.docs.wso2.com/en/latest/learn/user-account-suspension/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
