### ISSUE TITLE
Error thrown when adding claims to OIDC Scopes

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#14155]
**Describe the issue:**
Error is thrown when adding claims to OIDC Scopes in Identity Server v5.8.0 WUM updated pack when using Microsoft SQL Server as the database.

> ERROR {org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl} -  Error while fetching claims id.
> org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error fetching data for oidc scope: test
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.loadOIDCClaimId(ScopeClaimMappingDAOImpl.java:377)
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.lambda$null$11(ScopeClaimMappingDAOImpl.java:249)
>         at org.wso2.carbon.database.utils.jdbc.Template.doInternalBatchUpdate(Template.java:246)
>         at org.wso2.carbon.database.utils.jdbc.Template.executeBatchInsert(Template.java:100)
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.lambda$addClaimsByScope$12(ScopeClaimMappingDAOImpl.java:244)
>         at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:82)
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.addClaimsByScope(ScopeClaimMappingDAOImpl.java:243)
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.updateScope(ScopeClaimMappingDAOImpl.java:229)
>         at org.wso2.carbon.identity.openidconnect.dao.CacheBackedScopeClaimMappingDAOImpl.updateScope(CacheBackedScopeClaimMappingDAOImpl.java:86)
>         at org.wso2.carbon.identity.oauth.OAuthAdminService.updateScope(OAuthAdminService.java:543)
>         at sun.reflect.GeneratedMethodAccessor493.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
>         at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
>         at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
>         at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
>         at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
>         at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170)
>         at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82)
>         at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45)
>         at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77)
>         at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
>         at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
>         at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
>         at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
>         at org.wso2.carbon.identity.oauth.stub.OAuthAdminServiceStub.updateScope(OAuthAdminServiceStub.java:6503)
>         at org.wso2.carbon.identity.oauth.ui.client.OAuthAdminClient.updateScope(OAuthAdminClient.java:280)
>         at org.apache.jsp.oauth.add_002doidc_002dclaims_002dfinish_002dajaxprocessor_jsp._jspService(add_002doidc_002dclaims_002dfinish_002dajaxprocessor_jsp.java:157)
>         at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>         at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
>         at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
>         at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>         at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
>         at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>         at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
>         at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
>         at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
>         at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>         at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:742)
>         at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:484)
>         at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:409)
>         at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
>         at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:30)
>         at org.wso2.carbon.redirector.servlet.ui.filters.AllPagesFilter.doFilter(AllPagesFilter.java:156)
>         at org.eclipse.equinox.http.helper.FilterServletAdaptor.service(FilterServletAdaptor.java:37)
>         at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
>         at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
>         at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
>         at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
>         at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
>         at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
>         at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65)
>         at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
>         at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
>         at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:63)
>         at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
>         at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
>         at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:158)
>         at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
>         at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
>         at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
>         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.TransactionException: Could not commit the transaction.
>         at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:104)
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.loadOIDCClaimId(ScopeClaimMappingDAOImpl.java:361)
>         ... 100 more
> Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID FROM IDN_CLAIM WHERE CLAIM_URI = ? AND TENANT_ID = ?AND DIALECT_ID = (SELECT ID FROM IDN_CLAIM_DIALECT WHERE DIALECT_URI = ? AND TENANT_ID = ?)
>         at org.wso2.carbon.database.utils.jdbc.Template.fetchSingleRecord(Template.java:189)
>         at org.wso2.carbon.identity.openidconnect.dao.ScopeClaimMappingDAOImpl.lambda$loadOIDCClaimId$26(ScopeClaimMappingDAOImpl.java:362)
>         at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.withTransaction(JdbcTemplate.java:82)
>         ... 101 more
> Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Must declare the scalar variable "@P1AND".
>         at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
>         at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
>         at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
>         at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
>         at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
>         at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
>         at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
>         at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
>         at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
>         at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
>         at com.sun.proxy.$Proxy28.executeQuery(Unknown Source)
>         at org.wso2.carbon.database.utils.jdbc.Template.fetchSingleRecord(Template.java:174)
>         ... 103 more

**Expected behavior:**
To fix this, a space between the ? and the AND in the SQL query GET_OIDC_CLAIM_ID needs to be added. The PR which added this SQL query is given at [1].

Further changes have been made to this query [2], but this specific change has not been done.

[1] - https://github.com/wso2-support/identity-inbound-auth-oauth/pull/460/files#diff-7a33de96811a01d3d112e2951a9793ee2df129d9133ee2147403ebedb9a85a87R115
[2] - https://github.com/wso2-support/identity-inbound-auth-oauth/commit/8a5578dcee2f582af929afd0d19302503db84ab6

**Comment by ThaminduDilshan** [comment]
This issue is not available in [public branch](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/dao/SQLQueries.java#L144)
