### ISSUE TITLE
Can SAML 2.0 be configured as the default token type for WS-Federation/WS-Trust STS?

### ISSUE THREAD

**Issue by jeffreyschultz** [wso2/product-is#1415]
I am working with WSO2IS 5.3.0 using WIF 4.5 on the .NET platform and am having issues with WIF 4.5 when I specify a SAML 2.0 TokenType using a value of "http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0". When I do this WIF 4.5 encountered an XML issue and throws an exception. This seems to be a WIF-specific issue, and not WSO2IS.

So my question is how do I configure WSO2IS to default to using a SAML 2.0 assertion, rather than SAML 1.0, when no TokenType is provided in the RST?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
