### ISSUE TITLE
Add support for 'private_key_jwt' for client authentication.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#1417]
As per the section '9.  Client Authentication' of the specification [1], we need to support this client authentication mechanism.

[1] - http://openid.net/specs/openid-connect-core-1_0.html

**Comment by emswbandara** [comment]
This is supported since IS 5.5.0
https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
