### ISSUE TITLE
Successful  delete organization gives 204 response code.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14174]
**Describe the issue:**
Successful  delete organization gives 204 response code.

**How to reproduce:**
1. Setup the organization management feature https://docs.google.com/document/d/1MWf_rzJGuYObMtlLIyVOBHa8qpKIZ89ZJoPSWuHsaxQ/edit?usp=sharing
2. Create oraganization under root organization
3. Delete organization

Request:

```
curl --location --request DELETE 'https://localhost:9443/o/10084a8d-113f-4211-a0d5-efe36b082211/api/server/v1/organizations/ad16484e-05e8-472c-8a0a-af490287237e' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Cookie: JSESSIONID=1D0B039F53D753052520FB201B7839D1; requestedURI=../../815abb2b-9507-434d-a928-90606dd2bba2/api/server/v1/identity-providers'
```
Response
<img width="726" alt="image" src="https://user-images.githubusercontent.com/39077751/178151012-f94c8542-1b4d-4e8d-8694-94aa3fad1166.png">
 

**Expected behavior:**
Delete the oraganization and response code should be 202

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4139/ 
 - OS: mac
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
Returning 204 HTTP status code for the successful organization deletion request is the expected response.

HTTP status code 202 - Accepted is used if the server accepts the request but not deleted the resource until some workflow completion.

**Comment by AnuradhaSK** [comment]
@aaujayasena Shall we close this issue since there is nothing to fix? Refer https://github.com/wso2/product-is/issues/14174#issuecomment-1179770656
