### ISSUE TITLE
Few improvements on OAuth2GenericAuthenticator

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#14186]
**Is your suggestion related to an experience ? Please describe.**

 With this [changes](https://github.com/wso2/product-is/issues/14167), OAuth2GenericAuthenticator cannot be registered as an IdP. It can be used as a base extension for other OAuth2 supported authenticators.
- [ ] Since it is not a authenticator anymore, we can have it under [OIDCAuthenticator repo](https://github.com/wso2-extensions/identity-outbound-auth-oidc) and use it as the base authenticator for OIDCauthenticator
- [ ] Refactor other authenticators such as GitHub, Facebook to use OAuth2Generic Authenticator as the base extension

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
