### ISSUE TITLE
Can delete the ROOT oraganization.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14181]
**Describe the issue:**
Can delete the ROOT oraganization and no mechanism to create new root oraganization

**How to reproduce:**
1. Setup the organization management feature https://docs.google.com/document/d/1MWf_rzJGuYObMtlLIyVOBHa8qpKIZ89ZJoPSWuHsaxQ/edit?usp=sharing
2. Create oraganization under root organization
3. Delete organization

Request: 
```
curl --location --request DELETE 'https://localhost:9443/o/10084a8d-113f-4211-a0d5-efe36b082211/api/server/v1/organizations/10084a8d-113f-4211-a0d5-efe36b082211' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Cookie: JSESSIONID=1D0B039F53D753052520FB201B7839D1; requestedURI=../../815abb2b-9507-434d-a928-90606dd2bba2/api/server/v1/identity-providers'
```

**Expected behavior:**
ROOT organization should not allow to delete

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4139/
- OS: mac
- Database: H2
- Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
ROOT org deleting/ disabling is blocked - https://github.com/wso2-extensions/identity-organization-management/pull/85
ROOT org name renaming is blocked - https://github.com/wso2-extensions/identity-organization-management/pull/87
