### ISSUE TITLE
[Bug][Console-UI] Conditional Authentication set to off state after click update button.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#14190]
- Download IS6.0.0-alpha3 snapshot
- Download AA libraries using adaptive.sh script
- Go to Console 
- Create an app
- Go to sign-in method
- Click TOTP authentication
- Enable Conditional Authentication
- Add Role-based Conditional Authentication
- Click Update.

Actual Outcome: Conditional Authentication is off
Actual Outcome: Conditional Authentication should be on
![adaptiveIssue](https://user-images.githubusercontent.com/25488962/178304476-5d4606b8-6466-4827-8f19-f9faeddeba3a.gif)

**Comment by savindi7** [comment]
This issue is fixed now @piraveena @Thumimku
