### ISSUE TITLE
Primary roles are not getting added to the SCIM_GROUP table when using an external DB

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#14207]
**Describe the issue:**
$subject
In IS 5.3.0, Primary roles get added to the IDN_SCIM_GROUP table when using the embedded H2 database. But it does not happen when an external database is configured.

**How to reproduce:**
1. Setup external database and configure the connection in IS 5.3.0
2. Start the server
3. Create a new primary role
4. Analyse the IDN_SCIM_GROUP table.

**Expected behavior:**
Scim 1 IDs for primary roles should be present in the table.

**Environment information****:**
 - Product Version: IS 5.3.0
 - Database: MySQL, Postgres 
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
