### ISSUE TITLE
Update Organization login authenticator name and configurations

### ISSUE THREAD

**Issue by wenodpathirana** [wso2/product-is#14218]
**Describe the issue:**
Rename the authenticator allowing login to an application, from child org
Update the hint used for enable / default configuration of the authenticator.

![image](https://user-images.githubusercontent.com/6595027/178682240-9bd2a235-dc6a-4d3f-abd7-ce643e0f964b.png)

**Comment by dewniMW** [comment]
@wenodpathirana can we close this issue?
