### ISSUE TITLE
Metamask Decentralized IdP Authenticator

### ISSUE THREAD

**Issue by NimashaBandara** [wso2/product-is#14228]
**Is your feature request related to a problem? Please describe.**
With the introduction of web3.0 and also the increase of cyber-crime and fraud,  the need to store user information and authenticate users in a decentralized manner became evident globally in terms of digital identity.
When considering the WSO2 Identity Server, we currently do not have any decentralized identity mechanism integrated. And it was proposed to analyze and identify a suitable decentralized identity mechanism for the users of the WSO2 IS. 

**Describe the solution you would prefer**
Develop a decentralized authenticator with metamask digital wallet (identity-outbound-auth-metamask authenticator).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
