### ISSUE TITLE
During an auth failure redirection to retry.jsp fails

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#14221]
**Describe the issue:**

When a locked user tries to login after multiple incorrect login attempts, he should redirected to retry.jsp file on failure. But this is not working in this specific scenario where we have multiple authentication options and adaptive script in place.

**How to reproduce:**
- Get the latest IS-5.7.0 pack
- Configure an SP(SAML or OIDC)
- Under local & outbound config -> advance config ->  authentication step 1 -> configure both local authenticator (basic) and federated authenticator(can create a dummy idp as federated one)
- Add a simple adaptive auth script
```
function onLoginRequest(context) {
  executeStep(1, {
    onSuccess: function (context) {
      user = context.currentKnownSubject;
      Log.info(user.username);
    }
  });
}
```
-  Configure account locking by failed login attempts [1]
-  Under BasicAuthenticator configuration add the following two parameters(this needs a server restart),
```
<AuthenticatorConfig name="BasicAuthenticator" enabled="true">
	<!--Parameter name="UserNameAttributeClaimUri">http://wso2.org/claims/emailaddress</Parameter-->
	<Parameter name="showAuthFailureReason">true</Parameter>	
	<Parameter name="redirectToMultiOptionPageOnFailure">false</Parameter>
</AuthenticatorConfig>
```
- Login to the created SP using basic authentication with a wrong password until the account gets locked.

**Expected behavior:**
The user should be redirected to retry.jsp page on failure

**Environment information** **:**
 - Product Version: [IS 5.7.0]

[1] - https://docs.wso2.com/display/IS570/Account+Locking+by+Failed+Login+Attempts

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by jcgarciaa** [comment]
Reopening case as it does not work as expected in latest versions
