### ISSUE TITLE
[Migration] Deprecate the legacy identity/register DCR endpoint

### ISSUE THREAD

**Issue by Anandi-K** [wso2/product-is#14226]
The legacy `identity/register` DCR endpoint will be deprecated. The recommended API should be OAuth2.0 (`/identity/oauth2/dcr/v1.1`).

If the deprecated API needs to be enabled, add the following config to `deployment.toml` file.
```
[[legacy_feature]]
id = "identity/register"
enable = true
```

### Related Issues
https://github.com/wso2/product-is/issues/14198

### Related PRs
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1873

**Comment by ashendes** [comment]
Addressed in https://github.com/wso2/docs-is/pull/3232
