### ISSUE TITLE
Add java 11 and java 17 support

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#14224]
**Describe the improvement**
Adding JDK 11 and JDK 17 compilation support for  WSO2 IS repositories

Repositories which support only JDK 11 (Not JDK 17)

- [x] Identity-Framework

**Repository List, PR merged ✓**

- [X] [identity-governance](https://github.com/wso2-extensions/identity-governance/pull/607)
- [x] [identity-inbound-provisioning-scim2](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/431)
- [x] [identity-api-server](https://github.com/wso2/identity-api-server/pull/373)
- [x] [identity-outbound-auth-sms-otp](https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/140)
- [x] [identity-carbon-auth-rest](https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/191)
- [x] [identity-outbound-auth-totp](https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/130)
- [x] [identity-outbound-auth-samlsso](https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/146)
- [x] [identity-outbound-auth-saml](https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/378)
- [x] [identity-outbound-auth-oidc](https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/127)
- [x] [identity-api-user](https://github.com/wso2/identity-api-user/pull/158)
- [x] [identity-inbound-auth-oauth](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1955)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
