### ISSUE TITLE
Improve the organization list API to show 1st level organization in disjoint subtrees based on the permissions

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#14220]
Assume there is an organization hierarchy maintained as shown below. A user residing in the ROOT organization has organization management view permissions for the organizations depicted in green. 

![list3 drawio](https://user-images.githubusercontent.com/24982871/178727728-5b15bbc6-6333-413c-b0bd-ecbe60323402.png)

With the current organization listing API, we don't have a way to directly only derive the first level permitted organizations in the hierarchy (ORG_A_1, ORG_B_2_1, ORG_3_1_1_1) when the recursive query param is set to false.

To achieve $subject, the data model needs to be improved as explained below. 

The user should get a special permission for organizations marked in yellow (ORG_A, ORG_B, ORG_B_2, ORG_B_3, ORG_B_3_1). This new permission will be called the organization switching permission. The idea behind this is that the user should have an idea about the hierarchy to manage any organizations at disjoint levels in the tree. 

![list4 drawio](https://user-images.githubusercontent.com/24982871/178727701-cde4a88e-7f20-4dfa-9fce-a8c59d6da9c1.png)

Based on this, when the org listing API is called with recursive set param is set to false, it should return the first level organization management view permission or organization switch permission assigned organizations of the user in disjoint subtrees (ORG_A and ORG_B). If the user selects ORG_B, then in the next view ORG_B_2 and ORG_B_3 should be displayed. If ORG_B_2, then in the next view ORG_B_2_1 should be displayed. 

When a user gets organization view permissions to a certain organization, assume ORG_B_2_1, the user should be automatically assigned with organization switching permissions ORG_B and ORG_B_2.

**Comment by sadilchamishka** [comment]
Tracked by - https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/49
