### ISSUE TITLE
MagicLink Authenticator Throws NPE When the ContextId is Null.

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14236]
**Describe the issue:**
The MagicLink Authenticator throws an NPE when the ContextId is null, particularly from this code block[1].

[1] : https://github.com/wso2-extensions/identity-local-auth-magiclink/blob/8c847d59cde0996dd3302e3b6874b0f416f59505/components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/cache/MagicLinkAuthContextCacheKey.java#L59

**How to reproduce:**
Example scneario would be,
1. Configure the callback url as the commonauth endpoint of the server.
2. Fail adaptive authentication from the adaptive authentication script
3. An error log with an exception will be observed as follows.
```
TID: [-1234] Tenant: [carbon.super] [2022-07-09 00:12:06,009] [342ae9ec-34b2-4db8-9b1f-5cb43381958d] : iam-cloud-carbon : ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException: null| at org.wso2.carbon.identity.application.authenticator.magiclink.cache.MagicLinkAuthContextCacheKey.hashCode(MagicLinkAuthContextCacheKey.java:59) 
[org.wso2.carbon.identity.application.authenticator.magiclink-1.0.4.jar:?]| at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]|at org.wso2.carbon.caching.impl.CacheImpl.get(CacheImpl.java:224) ~[javax.cache.wso2_4.7.0.beta8.jar:?]|at.......
```

**Expected behavior:**
Exception shouldn't be thrown and instead, the context null scenario should be handled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
