### ISSUE TITLE
Remove Sign in with metamask button in metamask.jsp

### ISSUE THREAD

**Issue by NimashaBandara** [wso2/product-is#14231]
**Describe the issue:**
Currently user need to click sign in with metamask button in metamask login page[1]. This button click is redundant. Instead, the metamask login page needs to interact with metamask wallet after choose metamask authentication option from Identity server login portal without another button click in metamask login page.
[1] https://github.com/NimashaBandara/Custom-Federated-Metamask-Authenticator/blob/803e67b0cdcd5c03c0b2c90e8bfe26d6552793a5/Metamask-Login-Page/metamask.jsp#L65

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
