### ISSUE TITLE
Add identity-outbound-auth-metamask authenticator to as a connector

### ISSUE THREAD

**Issue by NimashaBandara** [wso2/product-is#14235]
**Is your suggestion related to an experience ? Please describe.**
It is suggested to use identity-outbound-auth-metamask authenticator as a connector.

**Describe the improvement**
Add resourcesof identity-outbound-auth-metamask authenticator to connector store and describe set up process in documentation

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
