### ISSUE TITLE
Add metamask onboarding library to metamask.jsp

### ISSUE THREAD

**Issue by NimashaBandara** [wso2/product-is#14232]
**Is your suggestion related to an experience ? Please describe.**
When the user does not have metamask extension installed, user can not use authenticate with metamask option.

**Describe the improvement**
Use metamask onboarding library or check browser type to direct users to  download metamask extension[1]. 

**Additional context**
https://docs.metamask.io/guide/onboarding-library.html

[1] https://github.com/NimashaBandara/Custom-Federated-Metamask-Authenticator/blob/803e67b0cdcd5c03c0b2c90e8bfe26d6552793a5/Metamask-Login-Page/metamask.jsp#L111

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
