### ISSUE TITLE
Remove cyclic dependency between oauth and org management components

### ISSUE THREAD

**Issue by wenodpathirana** [wso2/product-is#14243]
`identity-inbound-auth-oauth` and `identity-organization-management` repos has cyclic dependencies. `organization-authenticator` and `switch-grant` components have to be moved to separate repos.

**Comment by sadilchamishka** [comment]
- https://github.com/wso2-extensions/identity-oauth2-grant-organization-switch/pull/1
- https://github.com/wso2-extensions/identity-auth-organization-login/pull/1
