### ISSUE TITLE
Alert users about the Apple's client secret expiry policy

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#14248]
**Is your suggestion related to a missing or misleading document? Please describe.**

According to the Apple documentation [1], they expire the client secret after six months. This is not documented in the official documentation at [2] hence the end users might get confused when the federated authentication suddenly breaks down after six months.

**Describe the improvement**

The official documentation site should alert the end users saying that the client secret is expired after six months if apple is used for federated authentication.

[1] - https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens
[2] - https://is.docs.wso2.com/en/5.11.0/learn/configuring-apple/

---

**Comment by deshankoswatte** [comment]
Please note that a PR was not added to the master branch since the relevant documentation was not available in that branch.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
