### ISSUE TITLE
Validate Application Certificates Expiry Date From the Backend

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14241]
**Is your suggestion related to an experience ? Please describe.**
The certificates added to applications are not validated for expirty date from the backend.

**Describe the improvement**
The application certificates need to be validated for expiry date.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
