### ISSUE TITLE
Navigating to a 404 page when registering a application via Console App

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14247]
**How to reproduce:**
1. Get pack https://wso2.org/jenkins/job/products/job/product-is/4152/
2. Access Console
3. Register a SPA

Landing to a 404 page as attached below

https://user-images.githubusercontent.com/31848014/179187421-610bbfdf-42ce-44bf-b5d6-e3be9e2dc03c.mp4

![Screenshot from 2022-07-15 14-11-46](https://user-images.githubusercontent.com/31848014/179187395-728428d6-7dd0-4e4b-8637-bb1e970c4153.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 
IS 6.0.0 alpha 3 snapshot https://wso2.org/jenkins/job/products/job/product-is/4152/
H2 default

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-apps/pull/3163
