### ISSUE TITLE
Cannot start the server with installServer.bat in windows

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14252]
**How to reproduce:**

1. Get pack from https://wso2.org/jenkins/job/products/job/product-is/4152/
2. Follow running the server windows as a service https://is.docs.wso2.com/en/latest/setup/installing-as-a-windows-service/
3. Set carbon_home and JAVA_HOME as env variables
4. Copy the IS-pack wrapper.conf to YAJSW13.03/conf. wrapper.conf file was edited as per the comment in https://github.com/wso2/product-is/issues/14148#issuecomment-1178955108
5. Navigate to YAJSW13.03-home/bat
6. Run 
`runConsole.bat
`
9. Server will start successfully

Was able to get the server started successfully with the above command. When try to start the server with below commands was unable to get it started successfully. Reporting with a less severity as server can be started with step 6 command.

10. Then try the other option of running windows as a service with below commands
   
`installService.bat
`    
`startService.bat
`    
`stopService.bat

Server is not starting succesfully. Did we try these commands on windows 10 after we did the fixes for earlier fixed issues on windows. @Thumimku @ThumulaPerera 

Attaching used wrapper.conf

[wrapper.zip](https://github.com/wso2/product-is/files/9120483/wrapper.zip)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
H2 default
windows 11
YAJSW 13.03

**Comment by piraveena** [comment]
1. Need to check why we have multiple bat files to start as service
2. Need to remove if they are redundant
