### ISSUE TITLE
Improve the shown tenant list in management console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14259]
**Describe the issue:**
The tenant list shown in the management console contains

- the tenants created by the management console
- tenants created due to organization 

![Screenshot - 2022-07-17T110738 104](https://user-images.githubusercontent.com/25483865/179386183-84e367fa-3b63-4e00-8946-6d2a4e3a29d5.png)
In the image-> the tenant pointed out by a red arrow is a tenant created through the management console 

Then tenants marked in square bracket are tenants created due to organization creation **(These should be removed)**

This list should omit the tenants created in organization creation.

**How to reproduce:**
1. Go to the management console and create tenants
2. Add the following deployment.toml config (which required to use organization mgt feature)
```[multi_tenancy.stratos]
public_cloud_setup=false

[[organization_context.rewrite]]
base_path = "/api/"
sub_paths = ["/api/server/v1/identity-providers", "/api/server/v1/organizations", "/api/server/v1/applications"]
```
3. Create an organization using the following curl command.
```curl --location --request POST 'https://localhost:9443/api/server/v1/organizations/' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "orgA",
    "description": "A Hospital",
    "parentId": "ROOT",
    "type": "TENANT",
    "attributes": [
        {
            "key": "Country",
            "value": "Sri Lanka"
        },
        {
            "key": "Language",
            "value": "Sinhala"
        }
    ]
}'```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.0.0-beta

**Comment by sadilchamishka** [comment]
Tracked by - https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/45
