### ISSUE TITLE
Issue when trying to create a sub-organization with incorrect parentId

### ISSUE THREAD

**Issue by kavinda1995** [wso2/product-is#14265]
**Describe the issue:**
When creating sub-organization in organization management, if the given parentId is incorrect. We should have a way to identify that and give away some noticeable error from the backend. For now the error it gives is something like "This user can't perform the action since it don't have necessary permission for the given organization".

**How to reproduce:**
1. Use the API to create an organization (sub-organization) inside another organization
2. Set the parentId to something incorrect, or some organization id which is not the organization this request is sending

([swagger URL](https://app.swaggerhub.com/apis/dewni/organization_management_api_definition_main/v1))

**Expected behavior:**
This should give a clear error.

**Comment by dewniMW** [comment]
The aforementioned error specifically happens for the flow explained below.

Consider an org called orgA is created as an immediate child of root org.

Then a child org creation request is invoked as below.

curl --location --request POST 'https://localhost:9443/o/<orgA id>/api/server/v1/organizations' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AMTAwODRhOGQtMTEzZi00MjExLWEwZDUtZWZlMzZiMDgyMjExOmFkbWlu' \
--data-raw '{
  "name": "test",
  "description": "this is a construction company",
  "parentId": <root org id>
}'
