### ISSUE TITLE
Move the restrict token introspection from other tenants to service layer

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#14269]
**Describe the improvement**

- With the changes from https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1871, token introspection is blocked for other tenants when the below config is placed in the deployment.toml file.

```
[oauth.introspect]
allow_cross_tenant =false
```
- This logic is implemented in DAO level
   - Parse the value of the above config
   - Check that if the config is enabled or not
   - If the value is **true** --> allow to introspect tokens from other tenants 
   - If the value is **false** --> restrict ton introspect from other tenants by executing the sql queries that retrieve the token by tenant id also

- But **`need to move this blocking token introspection from other tenants to service level`** without coming to DAO level

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1919
