### ISSUE TITLE
A simple application patch request executes 30+ DB queries

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#14278]
When doing a simple patch request to an application in Asgardeo it executes about 30+ DB queries. The application dao layer(ApplicationDAOImpl[1]) is not written to handle patch type updates.
The following patch request resulted in 30+ queries being executed.

```
curl 'http://localhost:9443/api/server/v1/applications/32f3c130-4cf6-4a8c-90a0-d10387ec5d61' \
  -X 'PATCH' \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer <token>' \
  -H 'Content-Type: application/json' \
  --data-raw '{"advancedConfigurations":{"skipLoginConsent":true,"skipLogoutConsent":true}}' \
  --compressed
```

[1] - https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java

**Comment by ruwanta** [comment]
It is not clear why having 30+ db queries is a problem, and what is the expectation.
