### ISSUE TITLE
Share SAAS app to organization with basic auth failed when username with tenant id

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#14271]
**Describe the issue:**
When a SAAS app is shared with an organization, the user can be authenticated via basic authenticator by providing user's credentials. The username@org-id does not work properly.

<img width="1431" alt="Screenshot 2022-07-18 at 10 12 05" src="https://user-images.githubusercontent.com/35717390/179448969-85becdea-c661-4a87-a27f-b5bdd9f281f6.png">

**How to reproduce:**
1 - Create organization and SAAS app under root organization.
2 - Share SAAS app to sub organization with basic authenticator while providing user@org-id

**Expected behavior:**
The basic authenticator should support user@<org-id> where the org-id is user resides organization. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [wso2is-6.0.0-alpha3-SNAPSHOT]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [H2]

**Comment by dewniMW** [comment]
Could successfully share the application:

curl --location --request POST 'https://localhost:9443/o/10084a8d-113f-4211-a0d5-efe36b082211/api/server/v1/organizations/10084a8d-113f-4211-a0d5-efe36b082211/applications/893e6dba-8728-44d3-afb4-760c78b4c559/share' \
--header 'Authorization: Basic YWRtaW5AMTAwODRhOGQtMTEzZi00MjExLWEwZDUtZWZlMzZiMDgyMjExOmFkbWlu' \
--header 'Content-Type: application/json' \
--data-raw '["1f54d7d6-e16a-4904-a1e4-53696db63e17"]'

The above-reported behavior can happen if `o/<org_id>` is unavailable in the path. Hence it is not taken as an organization routing required path and will go through the old permission model where the validation happens directly against the tenant. The above error comes as there is no tenant with the name 10084a8d-113f-4211-a0d5-efe36b082211

Therefore this behaviour is not a bug in the organization management. Even if we pass a non existing tenant domain appended to the username for any other REST API, the same error should come.
