### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by fquillien** [wso2/product-is#14287]
Location : https://is.docs.wso2.com/en/latest/develop/customizing-login-pages-for-service-providers/
The link provided at the end of the documentation :
 https://svn.wso2.org/repos/wso2/people/malithim/samples/is-510/authenticationendpoint-customize-login-per-sp/
is getting a 403 Forbidden access :disappointed_relieved: Would it be possible to make this link being accessible publicly or to update with a new working pointer location.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
