### ISSUE TITLE
The SP Configs in the Console Application Keeps Continuously Loading After Receiving Error Response From Backend

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14280]
**Describe the issue:**

The SP Configs in the Console Application Keeps Continuously Loading After Receiving Error Response From Backend.

**How to reproduce:**
1. Do any change to the SP that results a failure from the backend.
2. Observe the error message
3. Observe the continuous loading state.

**Expected behavior:**

The loading state should stop and one of the following states should appear.
1. The original configs
2. The updated configs that we received an error from the backend.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
