### ISSUE TITLE
[Migration] Application Certificate Expiry Date Validation During Application Creation And Patch.

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14306]
**Describe the issue:**

As described in the issue https://github.com/wso2/product-is/issues/14241, the application certificates needs to be validated from the backend when creating and patching applications. 
Changes have been added through the PR : https://github.com/wso2/carbon-identity-framework/pull/4119 in order to fix this issue. 
Therefore, The behavior of APIs to create and update applications from the POST `/applications` endpoint and PATCH `/applications/{application-id}` has been changed.

With this change,
1. Creation of applications with expired certificates will no longer be possible.
2. Patching applications with expired application certificates will no longer be possible

**Comment by ashendes** [comment]
Addressed in https://github.com/wso2/docs-is/pull/3232
