### ISSUE TITLE
Remove server restart before running adaptive auth disable script on integration tests on windows

### ISSUE THREAD

**Issue by ThumulaPerera** [wso2/product-is#14301]
**Describe the issue:**
In order for update the integration tests for adaptive authentication to be compatible for windows (as a part of the effort for https://github.com/wso2/product-is/issues/13463) a PR https://github.com/wso2/product-is/pull/14302 is raised. 
In that, a server restart is done before the adaptive auth script (in disable mode) is run in order to release the locks on nashorn and asm-util jars in the dropins directory. This is only performed if the OS is windows and therefore does not affect the integration tests on other operating systems.

**Expected behavior:**
Remove the heavy operation of a server restart and use an alternative method to release the locks before running the adaptive auth script in disable mode in integration tests.

**Environment information**  **:**
 - OS: Windows

---

**Related issues:**
https://github.com/wso2/product-is/issues/13463

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
