### ISSUE TITLE
x509 Authenticator tenant domain retrieval issue if email-username is enabled

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/product-is#14307]
**Describe the issue:**
If email-as-username is enabled in IS, incorrect username and tenant domain is retrieved here[1]. 
 
**Related issues:**
https://github.com/wso2/product-is/issues/13381

**Expected behavior:**
If the username is sansa@ciamdomain.net in carbon super tenant and email-as-username is enabled, the tenant domain should be carbon.super not ciamdemo.net

**Suggested fix:**
```
if (!MultitenantUtils.isEmailUserName()) {
            if (subject.contains("@")) {
                userName = subject.substring(0, subject.lastIndexOf('@'));
                tenantDomain = subject.substring(subject.lastIndexOf('@') + 1);
            }
        }
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0

---
[1] https://github.com/wso2-extensions/identity-outbound-auth-x509/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/x509Certificate/X509CertificateUtil.java#L418-L420

**Comment by bhagyasakalanka** [comment]
Hi Yasara,

Instead of checking if email as username enabled and manually getting username and tenant domain, we can use util functions in MultitenantUtils class as below. 
  ```
 String userName = MultitenantUtils.getTenantAwareUsername(subject);
 String tenantDomain = MultitenantUtils.getTenantDomain(subject);
  ```

**Comment by Yasara-Y** [comment]
> Hi Yasara,
> 
> Instead of checking if email as username enabled and manually getting username and tenant domain, we can use util functions in MultitenantUtils class as below.
> 
> ```
> String userName = MultitenantUtils.getTenantAwareUsername(subject);
> String tenantDomain = MultitenantUtils.getTenantDomain(subject);
> ```

+1
