### ISSUE TITLE
Support for JWT Secured Authorization Response Mode for OAuth 2.0

### ISSUE THREAD

**Issue by SachiniSiriwardene** [wso2/product-is#14318]
**Is your feature request related to a problem? Please describe.**
Provide the ability to send a signed response for the authorization request as mentioned in https://openid.net/specs/openid-financial-api-jarm.html.

**Describe the solution you would prefer**
Introduce an extension point to build the authorization response based on registered/configured implemenations.

**Additional context**

**Comment by chamathns** [comment]
duplicate of https://github.com/wso2/product-is/issues/15527
