### ISSUE TITLE
Error type "abstime" does not exist with IS 5.3.0 latest wum BPS Scripts with Postgres 13.2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14327]
**How to reproduce:**
1. Get latest IS 5.3.0 wum (wso2is-5.3.0+1650694972746.full)
2. Create a db with postgres 13.2
3. Execute dbscipts/bps/create/postgresql.sql from db viewer

![Screenshot from 2022-07-20 16-01-43](https://user-images.githubusercontent.com/31848014/179989559-b125710f-7f78-484d-bbcf-085e3312e987.png)
![Screenshot from 2022-07-20 16-08-15](https://user-images.githubusercontent.com/31848014/179989585-8df0f36c-8d39-474f-b9fa-17ec7881b1d7.png)
![Screenshot from 2022-07-20 16-08-50](https://user-images.githubusercontent.com/31848014/179989614-8ef40830-7afa-4c95-9ab8-cdf84ff3af8c.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
postgres 13.2
pack wso2is-5.3.0+1650694972746.full

**Comment by ShanikaWickramasinghe** [comment]
Getting the same issue with wum update wso2is-5.3.0 -t 1601997504472 and U2 update the pack which is obtained from latest wum 
u2 level wso2is-5.3.0.25
![Screenshot from 2022-08-02 12-45-16](https://user-images.githubusercontent.com/31848014/182317352-57915103-c578-4c27-86ee-ab730302ce77.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
