### ISSUE TITLE
Ability to configure OIDC claims for all service providers

### ISSUE THREAD

**Issue by javiervazquezh** [wso2/product-is#1432]
I’ve been trying to return claims embedded in the “id_token” (JWT) but only works if I configure them in the Service Provider -> Claim Configuration section.

I would like to be able to have a centralized configuration that applies to all service providers.

**Comment by sagara-gunathunga** [comment]
As per current design of IS this is not possible via UI portal,  alternatively you can write a script to call admin API of IS.
