### ISSUE TITLE
SSO with console and myaccount is not working with organisation management feature

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14328]
**Describe the issue:**
Please refer to this screencast

https://user-images.githubusercontent.com/13362482/179996821-2a06b74d-7e60-49f0-a8f9-f69f3f7bab3f.mov

**How to reproduce:**

- Login to console as admin user - https://localhost:9443/console
- Click on the user avatar dropdown and click on myaccount
- You will redirect to myaccount, but you need to provide credentials to proceed further - SSO failed
- Once we provide credentials on myaccount side, the console gets logged out.

**Expected behavior:**
SSO should work as expected.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by IsuraD** [comment]
@Kanapriya can you check this with IS 6.0.0 beta

**Comment by Kanapriya** [comment]
Identified this issue when we do a test round against MSSQL 2019 on RC pack (wso2is-6.0.0-beta2-SNAPSHOT) with the organization management feature.

**Comment by dewniMW** [comment]
Issue is fixed in RC2 pack

**Comment by AnuradhaSK** [comment]
fixed by https://github.com/wso2-enterprise/identity-org-mgt-connector/pull/14
