### ISSUE TITLE
Once organization admin terminates his/her session, user is not get logged-out

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14339]
**Describe the issue:**
With the organization management feature, the user who has admin privileges can log in to the console. Once login to the console, the user can view his/her own active sessions and can terminate his/her session. Once the user terminates the session, the user should be logged out and redirected to the login page.

https://user-images.githubusercontent.com/13362482/180140135-87e083fd-fe54-4c3c-8487-8f6cbb8e06bc.mov

**How to reproduce:**
- Log in to the console (https://localhost:9443/console) as an admin user
- Create a user in a super organization and assign an admin role to the created user.
- Login to the console again with the created user with admin privileges
- Navigate to Manage -> Users and click on edit of logged in user's profile and terminate his session.

**Expected behavior:**
Users should automatically logged-out and see the login page.
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Maliesha** [comment]
This behaviour exists even before enabling the organization management feature and **this is not an issue**. 
This is the correct behaviour when an admin user terminates his/her session.

**Correct Behaviour:** 
Get a pop up window  [1] saying `Your session has Expired` to indicate that the session is invalid after termination. There's only one option that the user can perform, it is to click on the `Sign In` button. When the user clicks `Sign In` button, the user is redirected to the login page.

[1]
<img width="542" alt="Screenshot 2022-08-02 at 11 14 35 AM" src="https://user-images.githubusercontent.com/47919820/182300752-47d8ca0d-8ce0-4129-a487-34e603dbda9f.png">
