### ISSUE TITLE
Make org-creator a view only role in the organization

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14333]
**Describe the issue:**
![Screenshot - 2022-07-20T230419 692](https://user-images.githubusercontent.com/25483865/180046443-affd7e07-92d1-4af9-8569-1209250b5a10.png)

- We can remove the pencil icon and add an eye icon.
- Also disable input fields of the role

![Screenshot from 2022-07-20 23-07-06](https://user-images.githubusercontent.com/25483865/180046804-ee856f63-2421-4496-ab23-786edfac29c0.png)

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3203

**Comment by kavinda1995** [comment]
Reopened as this ticket closed by mistake
