### ISSUE TITLE
Search functionality with organization feature is not working as expected

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14347]
**Describe the issue:**
Please refer to the below screencast:

https://user-images.githubusercontent.com/13362482/180177756-f5c341ea-9d35-4d41-a838-4763ead38824.mov

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
This only happens in the following flow
1. User searches for something not in the list
2. Since the list is empty, user is getting an option to clear the search query
3. User clicks on it, and the search will get reset
4. If user search something afterwards, we get this issue

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3215
