### ISSUE TITLE
Cannot create organizations with the same organization name

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14341]
**Describe the issue:**
As I got to know, we can create organizations with the same name as there are no restrictions on the backend side. But when trying to create an organization with the same name under the sub-organization, it doesn't allow to create it. 

https://user-images.githubusercontent.com/13362482/180147737-2dcaffc8-5f87-4e88-b6d7-2c2e0aad7237.mov

**How to reproduce:**

- Log in to the console (https://localhost:9443/console) as an admin user
- Create an organization with the name 'Star'
- Create another organization called 'MedLife'
- Create a sub org under MedLife with the same name 'Star'
- Even though it's a child org of a sub-organization of MedLife, It won't allow the creation of an organization with the same name.
- It validates the case-sensitiveness when creating organizations.

**Expected behavior:**
There can be scenarios to have the same name when creating organizations. Hence users should be able to create organizations with the same name.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3204
