### ISSUE TITLE
404 error for permission management endpoint when creating a role in sub org

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#14340]
A 404 error was observed in the below view when calling the permission management endpoint as it is not an organization specific routing supported path.

<img width="1680" alt="Screen Shot 2022-07-21 at 11 19 02 AM" src="https://user-images.githubusercontent.com/24982871/180145047-dd2aae19-22a1-4025-8bd8-8cea54adff91.png">

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3197
