### ISSUE TITLE
Organization description limited to 32 characters

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14342]
**Describe the issue:**
When providing an organization description while creating an organization, it's limited to 32 characters. There can be a requirement to have a lengthy description. Better to add such capability.

https://user-images.githubusercontent.com/13362482/180151266-9df19f53-e380-406c-9fee-c8f05a26f3d1.mov

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3204
