### ISSUE TITLE
Improve the error view displayed when deleting an organization which has child organizations

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#14349]
https://user-images.githubusercontent.com/24982871/180181337-810c3f4a-2b2d-4114-b709-cdf22c8c014a.mov

- Create an org as testA.
- Create a sub org as testA_1 under testA.
- Try to delete testA.

The following view is displayed. The view shows the correct error message but having the confirm button to delete the organization in this view again is a bad user experience IMO.

<img width="504" alt="Screen Shot 2022-07-21 at 3 11 48 PM" src="https://user-images.githubusercontent.com/24982871/180183271-9d95611f-f40e-4936-96ea-975beac8b4e9.png">

**Comment by kavinda1995** [comment]
Agree. Will change accordingly

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3235
