### ISSUE TITLE
All IdP connection/ MFA option UIs are not visible in the Console UI

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#14357]
**Describe the issue:**
In the COnsole UI, all IdPs are not visibile. It shows only Google, FB anf Standard IdP

<img width="1476" alt="Screenshot 2022-07-22 at 08 35 20" src="https://user-images.githubusercontent.com/17597293/180353997-08a355a9-73a2-4c7b-9630-a54da7855e47.png">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Currently, we have the following list of IdPs on the management console and the I've ticked off the one's that are available in the console.

- [ ] SAML2 Web SSO Configuration
- [ ] OAuth2/OpenID Connect Configuration
- [ ] WS-Federation (Passive) Configuration
- [ ] Facebook Configuration
- [ ] Microsoft (Hotmail, MSN, Live) Configuration
- [ ] Google Configuration
- [ ] SMS OTP Configuration
- [ ] Twitter Configuration
- [ ] Email OTP Configuration
- [ ] IWA Kerberos Configuration
- [ ] Office365 Configuration
- [ ] EnterpriseIDP Configuration

**Comment by piraveena** [comment]
We need to onboard magic link authenticator as well
