### ISSUE TITLE
Secrets, Attributes, Account Management, Approvals, Use stores and some other sections are missing in the Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14356]
**How to reproduce:**

1. Get pack https://github.com/wso2/product-is/releases/tag/v6.0.0-alpha3
2. Extract the pack
3. Run the pack with sh wso2server.sh
4. Access console application
5. Login as admin
6. Navigate to Develop and Manage sections

Secrets section is missing in the console develop section
Lot of other sections are missing in the console manage section ( Attributes, Account Management etc..)

![Screenshot from 2022-07-22 00-47-42](https://user-images.githubusercontent.com/31848014/180298415-68b0bc69-679d-4104-9620-35e530533e93.png)

![Screenshot from 2022-07-22 00-47-46](https://user-images.githubusercontent.com/31848014/180298442-caef2cc5-f5cc-4073-9b36-97ce871c691b.png)

https://user-images.githubusercontent.com/31848014/180298516-4928543b-5769-401c-9fde-20f06e0a5ed6.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Jdk 11
ubuntu 20
h2 defalut
IS 6.0.0 alpha 3

**Comment by piraveena** [comment]
This is based on this change https://github.com/wso2/carbon-identity-framework/pull/4129. We need to enable relevant configs
