### ISSUE TITLE
sub attribute values  are resetting when updating one sub attribute value of same parent attribute from User Portal

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#14352]
**Describe the issue:**

When updating the sub-attribute(eg : work email address) value from the user portal profile section, all the other sub-attribute(home email address, other email address, primary email address) values are reset.  

**How to reproduce:**

1. Configure `http://wso2.org/claims/emails.other`, `http://wso2.org/claims/emails.work`, and `http://wso2.org/claims/emails.home`  claims as support by default from the management console.
2. Create a user (or use an existing user to log in for the user portal)
3. Add respective values to the "work email", "other email" and "home email" fields in the user profile from the management console. 
4. Login to user-portal with the created /existing user. 
5. Go to the personal info section. 
6. Update the work email address. You can see `other` and `home` email values are getting empty. If you check the scim2/Me endpoint response, you can see the `primary`, `other`, `home` email values are not there in the response. Also, the values are empty in the management console user profile. 

**Expected behavior:**
Other sub-attribute values should remain the same when updating one sub-attribute of the same parent attribute from the user portal.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - Application:  User Portal

**Comment by rajithacharith** [comment]
This behavior is fixed with https://github.com/wso2/product-is/issues/14351

https://user-images.githubusercontent.com/32898873/183338819-0725f48f-f8cd-418b-9970-f41c7f08b30b.mp4

**Comment by rajithacharith** [comment]
Tested in IS-6.0.0-beta2-SNAPSHOT. Not reproducible. Hence closing the issue.
