### ISSUE TITLE
Primary Email Address Not Display in the User Portal When Having Other Emails Configured in User Profile

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#14351]
**Describe the issue:**

When the user profile has "Email", "work email" and "other emai" values configured from the management console, only `work` and `other` email fields/values are showing in the user portal. The primary Email field/ value is not showing in the user portal.
If we don't configure the `http://wso2.org/claims/emails.other` and `http://wso2.org/claims/emails.work` claims to support by default, the primary email will be shown in the user-portal.

**How to reproduce:**

1. Configure `http://wso2.org/claims/emails.other` and `http://wso2.org/claims/emails.work` claims as support by default from the management console.
2. Create a user (or use an existing user to log in for the user portal)
3. Add respective values to the "work email" and "other email" fields in the user profile from the management console. 
4. Login to user-portal with the created /existing user. 
5. Go to the personal info section. You can see only `work` and `other` emails are there. The primary Email field/value is not there. 

![Screenshot 2022-07-21 at 15 39 48](https://user-images.githubusercontent.com/29885846/180189747-4f5b2b93-7e5b-4599-a332-c26481a8b658.png)

![Screenshot 2022-07-21 at 15 39 57](https://user-images.githubusercontent.com/29885846/180190307-b3af2c20-92ac-4549-9996-90d036947f62.png)

**Expected behavior:**
`Work`, `Other`, and `Primary` Email fields/values should be displayed in the User portal personal info section.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - Application:  User Portal

**References**

[1]https://github.com/wso2/identity-apps/blob/v1.0.72/apps/user-portal/src/components/profile/profile.tsx#L107-L116

**Comment by rajithacharith** [comment]
This issue is fixed from IS 5.11 onward with https://github.com/wso2/product-is/issues/10361
PR: https://github.com/wso2/identity-apps/pull/1356

**Comment by rajithacharith** [comment]
Closing since WUM, U2 PRs merged and Public was done with https://github.com/wso2/product-is/issues/10361
