### ISSUE TITLE
Organizations created with same name can't be distinguished in list view and org switcher 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14366]
**Describe the issue:**

- log in to the console application by admin credentials 
- Create multiple orgs with the same name. different descriptions
- The orgs can't be distinguished in the org list and org switcher 
![Screenshot - 2022-07-22T160426 029](https://user-images.githubusercontent.com/25483865/180425831-bed11368-f354-4904-9c05-e4296b698a5d.png)

Suggestion: 
Show the org id as well in these places
![Screenshot - 2022-07-22T163151 605](https://user-images.githubusercontent.com/25483865/180426112-ea16fbba-631e-460b-9782-9e8bc5604c05.png)

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3235
