### ISSUE TITLE
Organization patch request is sent twice in console

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#14364]
https://user-images.githubusercontent.com/24982871/180420908-7f8d38e1-07a7-40d4-b8b7-cb7fdddf980f.mov

**Environment information**:
Product Version: wso2is-6.0.0-alpha3
OS: Mac
Database: H2
Userstore: H2

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3235
