### ISSUE TITLE
Role creation in sub organization search role name availability in super org

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14367]
**Describe the issue:**
1. Log into console by admin
2. Create a sub-organization 
3. Switch to the created sub org
4. Go to roles and try to create a role name admin.
5. You will get an error saying name already exists  even though the role name does not exist in that org
Reason: `https://localhost:9443/scim2/Roles/.search` SCIM Roles API is invoked against super org. 
Expected: Invoke organization mgt role endpoint against the switched org

![Screenshot from 2022-07-22 17-34-40](https://user-images.githubusercontent.com/25483865/180436036-0d754a2c-6545-4679-ad44-6af6051c2f69.png)
![Screenshot from 2022-07-22 17-34-34](https://user-images.githubusercontent.com/25483865/180436056-710bedd6-17dc-4612-ac26-b96a9cc1eb60.png)

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3236
