### ISSUE TITLE
Always `/api/server/v1/remote-fetch` API is invoked against super org

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14368]
**Describe the issue:**
`/api/server/v1/remote-fetch` API is invoked when listing applications.
It is invoked against super org, even the user is logged into a sub org

![Screenshot from 2022-07-22 15-20-10](https://user-images.githubusercontent.com/25483865/180438655-ffb301cb-4737-4ae4-abb3-ee5aad04fb9c.png)

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-apps/pull/3232
