### ISSUE TITLE
Delete fragment applications when the business application is deleted.

### ISSUE THREAD

**Issue by wenodpathirana** [wso2/product-is#14375]
**Describe the issue:**
When a business application is deleted, if the application is shared with child organizations, fragment applications created in the child organizations has to be deleted.

**Comment by Kanapriya** [comment]
This needs to be fixed properly. In the latest snapshot pack observed the same behavior:

https://user-images.githubusercontent.com/13362482/180886037-a46db069-5c56-4d3b-9768-e2e6fbf350c5.mov

**Comment by wenodpathirana** [comment]
Added restrictions on deleting the application if the application is shared with other organization, to delete the application, first it should be unshared with other orgs and delete it.

**Comment by sadilchamishka** [comment]
- https://github.com/wso2-enterprise/identity-org-mgt-connector/pull/99
