### ISSUE TITLE
Permission Tree under Roles section doesn't select super admin permissions when select the all permissions

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14382]
**How to reproduce:**
1. Get https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/
2. Setup mysql 8.0.29 as the db type
3. Access console > manage > Roles

In the permission assignment window super admin permisiions and admin permissions are listed under all permissions.
If a user click the check box for all permissions then all the (super & admin) permissions should get selected according to how its displayed in the UI. But super admin permissions will not get selected when we select all permissions. Here we need to revisit the UI design and design and display it correctly . We may need to remove the super admin permissions for a different level if it doest belong to the checkbox displayed under all permissions

https://user-images.githubusercontent.com/31848014/180715684-1dd46877-c85f-45c8-adae-b1a89ee14ece.mp4

![a](https://user-images.githubusercontent.com/31848014/180715717-4a626cf8-3703-48be-8dcf-be388589b9bd.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

Mysql 8.0.29
orac;e jdk 17.0.3.1
ubuntu 20
pack https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
