### ISSUE TITLE
Observing a log in the back end which is referring the term tenant during a organization creation flow

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14381]
**How to reproduce:**
1. Set up mysql 8.0.29 as the db type
2. Get the pack from https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/
3. Access console > Manage > Organizations
4. Create a organization

Observing the below logs that says tenant is created. Dont we need to change these logs as organizations. As we are using the term organization in the new console

![Screenshot from 2022-07-25 11-42-08](https://user-images.githubusercontent.com/31848014/180710870-2d89ab25-f3e5-4598-83b5-da9d1152d547.png)

`[2022-07-25 11:35:48,113] [0533531c-bdae-4989-950a-18711e5f5775]  INFO {org.wso2.carbon.tenant.mgt.services.TenantMgtImpl} - Added the tenant '363185cc-da51-4921-9bc3-e359c654d65f [2]' by 'null'`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Oracle jdk 17.0.3.1
mysql 8.0.29
pack https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/
ubuntu  20

**Comment by sadilchamishka** [comment]
The organization management is backed by the tenant model. Tenants are created to manage the resources of the organizations. The info log has an improvement to be made to display the tenant created user name insteda of `null`.

**Comment by AnuradhaSK** [comment]
duplicate https://github.com/wso2-extensions/identity-organization-management/issues/60
