### ISSUE TITLE
[Migration] New database tables required for organization management feature from IS6.0.0

### ISSUE THREAD

**Issue by vinumaddumage** [wso2/product-is#14380]
### Describe the issue:
It is required to created a set of additional tables, in both Identity and Shared databases, to use the Organization Management feature. The following links direct to the database table creation queries that should be run on the corresponding database type

### Identity Database
Tables added:`SP_SHARED_APP `

- **DB2**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/db2.sql#L1720-L1743

- **H2**
https://github.com/wso2/carbon-identity-framework/blob/a86261eeb41adab8b90858e2005231997de1aba0/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/h2.sql#L1172-L1183

- **MsSQL**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mssql.sql#L1301-L1314
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mssql.sql#L1412-L1413

- **MySQL Cluster**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mysql-cluster.sql#L1339-L1350

- **MySQL**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mysql.sql#L1197-L1208

- **Oracle**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/oracle.sql#L1790-L1813

- **Oracle RAC**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/oracle_rac.sql#L1778-L1801

- **PostgreSQL**
https://github.com/wso2/carbon-identity-framework/blob/1bbcd706b7e1b97babab6534ae1f0b68fc6a8175/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/postgresql.sql#L1391-L1405

### Shared Database
Tables added: `UM_ORG `, `UM_ORG_ATTRIBUTE `, `UM_ORG_ROLE `, `UM_ORG_PERMISSION `, `UM_ORG_ROLE_USER `, `UM_ORG_ROLE_GROUP `, `UM_ORG_ROLE_PERMISSION `, `UM_ORG_HIERARCHY `

- **DB2**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/db2.sql#L964-L1063

- **H2**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/h2.sql#L501-L592

- **MsSQL**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/mssql.sql#L688-L784

- **MySQL Cluster**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/mysql_cluster.sql#L482-L557

- **MySQL**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/mysql_cluster.sql#L482-L557

- **Oracle**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/oracle.sql#L975-L1075

- **Oracle RAC**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/oracle_rac.sql#L963-L1063

- **PostgreSQL**
https://github.com/wso2/carbon-kernel/blob/d596bae109795d3cf3d31dca31741a29c8a5136c/distribution/kernel/carbon-home/dbscripts/postgresql.sql#L638-L727

**Comment by ashendes** [comment]
Changes made in https://github.com/wso2/carbon-kernel/pull/3375 need to be added to the migration client scripts.
