### ISSUE TITLE
Improvements on 'Share Applications to Sub Organizations' functionality

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14398]
**Describe the issue:**

- In the organization management feature, we have the capability to share applications between organizations, which will then be used by the shared organization users, IdPs and etc. 
- However, as per the current design, we can click on the 'Share Application' button and can select the required sub-organization to be shared with that particular business application. 
- But once we shared the applications with the sub-organization, there are no details available in the UI, that this application is already shared with some organizations or similar to something to convey that the particular application is already shared with some organizations. 
-  In the UI, it always shows the 'Share Application' button and when we click on it next time, its listed the already shared organization as well. IMO, at least we should list out the organizations that are not shared already with the application.
- And there is no option to un-share the applications between organizations. IMO this is a valid requirement as there are scenarios where an organization needs to un-share the application and wanted to share it among specific sub-organization.

https://user-images.githubusercontent.com/13362482/180882063-e53c75b4-d30e-4d46-8b62-3c84f7aea25e.mov

 
**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-alpha4-SNAPSHOT
 - OS: MAC
 - Database: H2
- JAVA Version: JDK 11

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
Fixed by https://github.com/wso2/identity-apps/pull/3325
