### ISSUE TITLE
Fetching i18n resources not handled properly when there is a timeout within an organization

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14399]
**Describe the issue:**
Please refer to the screenshot

https://user-images.githubusercontent.com/13362482/180884956-a6b23440-9915-4098-a737-34e7deb736e4.mov

**How to reproduce:**

- Login to console - https://localhost:9443/console
- Create a sub-organization under the root (super) organization
- Switch to the newly created organization and be inactive for some time
- Then go back to the console and you will see the below error message when fetching the applications inside the organizations.
<img width="494" alt="Screenshot 2022-07-22 at 17 18 12" src="https://user-images.githubusercontent.com/13362482/180885379-987034b7-83cb-4a54-b313-5843ea1b560a.png">

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-alpha4-SNAPSHOT
 - OS: MAC
 - Database: H2
- JAVA Version: JDK 11

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
