### ISSUE TITLE
Getting something went wrong when access and list the organizations section after login to console as a tenant 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14395]
**How to reproduce:**
1. Access managemnt console and create a tenant as wso2.com
2. Login to console using that tenant wso2.com
3. Navigate to Manage > organizations

Getting a error as somethig went wrong

![Screenshot from 2022-07-25 15-05-58](https://user-images.githubusercontent.com/31848014/180747066-b52824c2-55e3-437a-8ada-e4f4c9068dca.png)

![Screenshot from 2022-07-25 15-06-42](https://user-images.githubusercontent.com/31848014/180747358-158657d9-4fbb-4878-9fd5-9167ba090e8c.png)

https://user-images.githubusercontent.com/31848014/180747380-e0923985-6e5b-4d51-a902-10b9c5bfdd68.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
ubuntu 20
oracle jdk 17.0.3.1
mysql 8.0.29 pack https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/

**Comment by madurangasiriwardena** [comment]
Organization menu is not supposed to be visible for tenant login. @thivi can you check?

Since the tenant users does not have a requirement to see the organization menu, reducing the seviority to critical.
