### ISSUE TITLE
When deactivate a created organization from management console it gives a non matching error when trying to access it back from console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14394]
**How to reproduce:**
1. Login to console > manage > organizations
2. create a organization under the super tenant
3. Access managemnt console and list the tenants and deactivate the created org from the management console
4. Access console again and try to switch for the deactivated tennat
5. There will be a error printed as below.

Here than displaying as a invalid tenant we may need to commmunicate the exact error here as showing the error message for the user as this tenant is currently deactivated.

Also when login to managemnt console and try to activate and deactivate the organizations as the orgs are shown with a id , its not user friendly and not easy to identify which org that I deactivated. It would be better if we can display the org name too
![a](https://user-images.githubusercontent.com/31848014/180745550-7f8c1818-364a-400d-9456-973ca9632e76.png)

https://user-images.githubusercontent.com/31848014/180745630-d5b1aa32-50ff-4841-b97d-9916742e490c.mp4

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
mysql 8.0.29
pack https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
