### ISSUE TITLE
Organization delete operation should work with keyboard enter

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14393]
**How to reproduce:**
1. Access console and create a new organization
2. Try to delete the created organization

Keyboard enter should work when trying to confirm the delete operation
![Screenshot from 2022-07-25 14-45-45](https://user-images.githubusercontent.com/31848014/180743167-c8347548-4191-4a7f-93a9-b7256ca754b1.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Pack https://wso2.org/jenkins/view/products/job/products/job/product-is/4173/
mysql 8.0.29
oracle JDK 17

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
