### ISSUE TITLE
Add local user account filed tenant domain is undefined when switch the accounts

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14402]
**Describe the issue:**
Add local user account filed tenant domain is undefined when switch the accounts.

<img width="766" alt="Screenshot 2022-07-26 at 07 53 00" src="https://user-images.githubusercontent.com/39077751/180908957-68d71a20-7c60-4d21-bb2d-b82fbba61b90.png">

https://user-images.githubusercontent.com/39077751/180908896-e8b575a5-ec6a-4df7-8ed8-2d623c67540b.mov

**How to reproduce:**
1. Login to my account -> Profile infor
2. Click to add linked user and add linked user
3. Switch the account and try to add linked user again

**Expected behavior:**
Tenant domain should be available. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0- alpha4 https://wso2.org/jenkins/job/products/job/product-is/4174/
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Anandi-K** [comment]
We set the `tenantDomain` state correctly when signing in [(refer)](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/store/reducers/authenticate.ts#:~:text=tenantDomain%3A%20action.payload.tenantDomain%2C), but when switching the accounts it becomes undefined [(refer)](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/components/linked-accounts/linked-accounts-edit.tsx). 

Setting the `tenantDomain` usually happens before components are rendered. 
In the normal flow it happens in [here](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/protected-app.tsx#L180).
In the switching flow it happens in [here](https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/store/actions/authenticate.ts#L299).
