### ISSUE TITLE
My account country filed should improve

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14400]
**Describe the issue:**
My account country filed can add custom value as well. Gave successful message and when updating and filed is not update with given custom value. 

https://user-images.githubusercontent.com/39077751/180901875-f0620255-1b31-4877-b760-dbf5d36b9ab7.mov

**How to reproduce:**
1. Login to my account and navigate to the personal infor
2. Select country filed and add text value (invalid country) without selecting from the drop down
3. Click save

**Expected behavior:**
Since no result from the entered text it should not give the profile update success message. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: https://wso2.org/jenkins/job/products/job/product-is/4174/
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
