### ISSUE TITLE
Improve the error message for phone number filed for my account

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14401]
**Describe the issue:**
Add invalid mobile phone gave warning message as , "The format of the Mobile entered is incorrect". Better this message can improve with sample format.
<img width="635" alt="Screenshot 2022-07-26 at 07 08 10" src="https://user-images.githubusercontent.com/39077751/180904475-b887b491-e349-4c2e-a88a-216dd64bae65.png">

**How to reproduce:**
1. Login to my account -> Profile infor
2. Add invalid phone number and click save

**Expected behavior:**
Error message with sample format

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-alpha4 SNAPSHOT https://wso2.org/jenkins/job/products/job/product-is/4174/
 - OS: Mac
 - Database: Mssql
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
