### ISSUE TITLE
Add Custom Token Issuer related docs

### ISSUE THREAD

**Issue by dinzie95** [wso2/product-is#14419]
**Is your suggestion related to a missing or misleading document? Please describe.**
Custom token issuers are implemented in order to add an additional set of claims to the tokens than the already defined set of claims. There should be documentations regarding implementation of the custom token issuers for WSO2 Identity Server.

**Describe the improvement**
Add Custom Token Issuer related docs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
