### ISSUE TITLE
Improve the UX for retrieving user attributes in Facebook IdP configuration

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#14411]
In Identity Providers -> Federated Authenticators -> Facebook Configuration to retrieve profile attributes such as email, gender, birthday, etc. from Facebook, we have to configure two input fields: Scope and User Information Fields. 
For example to get the gender attribute:

1. Add the Facebook scope ```user_gender``` to Scope input field
2. Add ```gender``` to User Information Fields input field

After the client application user grants permission to the applied scope, then the scope value becomes redundant. With granted permission, irrespective of the scope field value, to retrieve the attributes they must be configured in the User Information Fields input field.

![image](https://user-images.githubusercontent.com/46979289/181014386-5386f379-eb85-4262-ba54-9a103f2d436f.png)

It will be better UX if retrieving attributes can be done using a single input field such as Scope.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
