### ISSUE TITLE
Missing null check is producing issues with OAuth2 custom grant type impl

### ISSUE THREAD

**Issue by Rod-yan** [wso2/product-is#14415]
Under certain implementation conditions for a OAuth2 custom grant type handler that extends from the AuthorizationCodeGrantHandler base abstract class, there is a cache clearing issue when the authz code that was issued to the resource owner was not generated by the WSO2's IS, but instead, by an external IDP.

Since the authz code was not issued by WSO2's IS, the product cannot obtain an existing authz code ID for the session, because it was not produced by it, hence resulting in a null value being obtained on the following method when the same is called passing the externally produced authz code as an argument: [[1]](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/12f2961da3e635eb68b0d94194ed3f143562f845/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/cache/AuthorizationGrantCache.java#L191)

This produces undesirable results when the following cache clearing routine is executed [[2]](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/12f2961da3e635eb68b0d94194ed3f143562f845/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/AccessTokenIssuer.java#L367), as it ends up attempting to execute the following SQL command [[3]](https://github.com/wso2/carbon-identity-framework/blob/b26f147535feca0747208752db7552932d7a9edf/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java#L562) with a null value for the 'key' attribute, which cannot be null as per data model restriction.

In this sense, we've identified that a quick solution can be applied by implementing a null check for the 'id' parameter on the following dependant method [[4]](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/12f2961da3e635eb68b0d94194ed3f143562f845/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/cache/AuthorizationGrantCache.java#L222).

Product version: 5.11.0

**Comment by rajithacharith** [comment]
Closing since U2, Hotfix and Public PRs merged
