### ISSUE TITLE
Inconsistency in the case used for self signup related config names in management console

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#14424]
**Describe the issue:**
Inconsistency in the case used for self signup related config names in management console. Sentence case is used for most on the config names in the management console. But some config names are in title case.

![annotely_image](https://user-images.githubusercontent.com/36252628/181232738-cf96137a-7442-43ca-87e3-0ceef368b030.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-alpha3-SNAPSHOT on Wednesday 20 July 2022

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
