### ISSUE TITLE
The allowed scopes are not included in the introspect response

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-is#14429]
**Describe the issue:**
The introspect response does not include the scopes which are defined as the allowed scopes.
**How to reproduce:**

- Add the below configuration in the deployment.toml file to define the allowed scopes.
```
[oauth]
allowed_scopes = ["internal_test", "test"]
```

- Invoke the token endpoint to generate a token against the allowed scopes as below,
```
curl -k -X POST https://localhost:9444/oauth2/token -d "grant_type=client_credentials&scope=internal_test test" -H"Authorization: Basic xxxxxx"
```
- The token response will contain both requested scopes.
```
{"access_token":"026fd505-ca4c-39d9-9997-9f484be691be","scope":"internal_test test","token_type":"Bearer","expires_in":3600}
```
- Invoke the introspect endpoint by parsing the generated token,
```
curl -X POST "https://localhost:9444/oauth2/introspect" -d "token=026fd505-ca4c-39d9-9997-9f484be691be" -H "accept: */*" -H "Authorization: Basic xxxxxxxx" -H "Content-Type: application/x-www-form-urlencoded" -k
```
- only the "default" scope will contain in the response.
```
{"aut":"APPLICATION","nbf":1658152285,"scope":"default","active":true,"token_type":"Bearer","exp":1658155885,"iat":1658152285,"client_id":"Af_Zj6qPfta9rwURiJo09vtSXfYa","username":"admin@carbon.super"}
```

**Expected behavior:**
It should be included the allowed scopes in the introspect response
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
