### ISSUE TITLE
[Improvement] Sort claim list when adding an external claim

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-is#1442]
The claim list that a user has to go through when mapping an external claim to a local claim is not sorted in alphabetical order in IS 5.3.0 (see attachment). Please sort the claim list in alphabetical order so that it will be easier for the user to pick a claim as the key board shortcuts don't work on the claim list either. 

UI Location:
Home > Identity > Claims > Add and click Add External claim

![screen shot 2017-11-15 at 1 20 20 pm](https://user-images.githubusercontent.com/5195851/32825302-8115f268-ca0a-11e7-812a-939609a0f5f1.png)

**Comment by Mariangela** [comment]
Minoli Perera suggested the following:
We can add a search-box along with the dropdown using select2 [1].  Also it has the ability to search by the claim name. See example in [2]

[1] https://select2.org/getting-started/basic-usage
[2] http://jsfiddle.net/4ad7A/780/

**Comment by gayashanbc** [comment]
I'm working on this issue.

**Comment by gayashanbc** [comment]
**Update**: The above mentioned issue has been already fixed.
However, I came across the following similar issues.

1. Claim dialect URI list is not sorted when adding a new external claim
<img width="1292" alt="Screen Shot 2019-07-17 at 10 59 58 AM" src="https://user-images.githubusercontent.com/15249242/61354239-5c123e80-a88f-11e9-82ba-4cbe736d35fc.png">

2. Claim dialect URI list is not sorted when listing existing external claims
<img width="1292" alt="Screen Shot 2019-07-17 at 11 01 10 AM" src="https://user-images.githubusercontent.com/15249242/61354420-c3c88980-a88f-11e9-9fd5-5721b863f56b.png">

3. Claim list is not sorted when listing existing external claims
<img width="1292" alt="Screen Shot 2019-07-17 at 11 01 34 AM" src="https://user-images.githubusercontent.com/15249242/61354505-f2defb00-a88f-11e9-99f2-7a551ba8ea4b.png">
