### ISSUE TITLE
Improve user attributes requested by default in a new OIDC application

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#14426]
Describe the issue:
In the console application, a newly created OIDC application will have username automatically added as a mandatory attribute. With this configuration, when logging in with an external identity provider using federated authentication it will always prompt for username if it is not received by default. It is not sent by default by many external identity providers.

Eg: If a client application is configured only with Google login, Google will not send username attribute after authentication. Therefore username will always be prompted to be manually entered by the application users.

How to reproduce:
1. Go to the console application and create a new OIDC application
2. Go to the created application User Attributes section and check the added attributes

Username attribute has been added as a mandatory attribute.
For better UX, the username attribute should only be a requested attribute, and not made mandatory.

**Comment by brionmario** [comment]
Related Issue: https://github.com/wso2/product-is/issues/14589

**Comment by mpmadhavig** [comment]
Closing the issue since https://github.com/wso2/identity-apps/pull/3331/ fixed this.
