### ISSUE TITLE
Improve the Hint For Access URL to Highlight the Need For Access URL

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14427]
**Is your suggestion related to an experience ? Please describe.**
$subject. 
We have multiple purposes of access URL.
1. It will be used in the application catalog and discovery flows
2.  If the login page times out, the user will be redirected to the client application via this URL.
3. If the login flow failed, this will be available to the user in the error page so that user can reinitiate the login flow
4. This will be used to redirect the user back to the application after password reset and account self sign up verification which is initiated from this application login page.

**Describe the improvement**
We need to highlight this need for developers.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
