### ISSUE TITLE
Intermediate page with empty box

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#14432]
**Is your suggestion related to an experience ? Please describe.**
When there is no IDPs added, due to slowness, this intermediate state is obvious. But the empty box looks bad. Better to improve.
![Screenshot from 2022-07-28 10-26-52](https://user-images.githubusercontent.com/32198547/181425210-7171e876-678e-4f96-9005-b91276665116.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
