### ISSUE TITLE
Organization creator can't create users since user creation permission can't be self assigned through console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14439]
**Describe the issue:**
1. Admin user create an organization 
2. Switch to that organization 
3. Create a role with user creation permission
4. Try to assign that role to the organization creator, but this user is not listed in the role assigning the user list

Collaborative users and organization creator (who is an outside org user) should be listed in the users to assign role

**Comment by sadilchamishka** [comment]
Moved the issue and tracked via https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/38
