### ISSUE TITLE
Attribute related issues of OIDC/SAML applications

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14446]
This issue contains issues and improvements related to **attribute configuration for OIDC/SAML applications creation process**. Identified issues are listed down below. 

### Issues

- [x] https://github.com/wso2/product-is/issues/14426
- [ ] https://github.com/wso2/product-is/issues/14441
- [ ] https://github.com/wso2/product-is/issues/14440#issue-1320971551

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
