### ISSUE TITLE
SAML application creation is different in management and application consoles

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14440]
### Problem

When fixing the issue https://github.com/wso2/product-is/issues/14426, found out that for SAML applications, the username field is taken as a mandatory field.

When a SAML web application is created from the console application, the username field will be made a mandatory field. The system doesn’t allow making it optional because the username is taken as the subject attribute by default. The subject attribute field is a required field in the application edit form. Only a requested attribute can be set as the subject attribute. 

<img width="1509" alt="Screenshot 2022-07-28 at 19 14 33" src="https://user-images.githubusercontent.com/47152272/181520499-a84affc5-5c47-4844-81c6-3755b8a38905.png">

The management console behavior is completely different from this. The username field is not taken as a mandatory field by default. Also the subject attribute field is optional. When a SAML application is created using the management console, if we do not specify a subject attribute, the user id is taken as the subject attribute. 

Two different behaviours can be scene in the two consoles.

## Console application behaviour:

1. Create SAML based application using the traditional web application template in the Console application.
2. Goto the user attributes tab and try changing the mandatory username field to an optional attribute. 
    - You will see the warning displayed as the above image.

## Management console behaviour:

1. Create another SAML based application using management console. 
2. Edit the application and see claim configurations. 
    - you will see username is not requested.
    - subject attribute is not selected
    - you can choose any attribute as the subject attribute

**Related issues**
- https://github.com/wso2/product-is/issues/14441

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
