### ISSUE TITLE
Improve federated IdP claim handling process

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#14445]
Regarding the claim handling process when logging in with an external IdP, several improvements/issues have been identified. This issue will track all the improvements/issues related to handling claims after federated authentication.

- [x]  https://github.com/wso2/product-is/issues/14845

- [x] https://github.com/wso2/product-is/issues/14426

- [ ] https://github.com/wso2/product-is/issues/14441

- [ ] https://github.com/wso2/product-is/issues/14411

- [ ] https://github.com/wso2/product-is/issues/14473

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
