### ISSUE TITLE
Improvements to user attribute sharing with SAML application

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14441]
**Problem**
- As mentioned in the $related issue, when a SAML application is created using console application, the newly created application will have username automatically added as a mandatory attribute. With this configuration, when logging in with an external idp using federated authentication it will always prompt for username if it is not received by default. It is not sent by default by many external identity providers.

**How to reproduce:**
1. create a SAML based application using the management console.
2. go to the attributes section and you will see username selected as a mandatory field.

**Expected behavior:**
- No attributed added as allowed attributes during application creation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
