### ISSUE TITLE
Organization SSO option still available in the UI

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14462]
**Describe the issue:**
1. Go to IDP creation flow from console

![a](https://user-images.githubusercontent.com/31848014/181772383-e1377ebb-6721-4110-9a66-c2a7cbccf8cf.png)

Used pack is https://wso2.org/jenkins/job/products/job/product-is/4190/artifact/modules/distribution/target/wso2is-6.0.0-alpha4-SNAPSHOT.zip

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3249
