### ISSUE TITLE
Application Share option is not removed from UI

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14460]
**How to reproduce:**
1. Create a SPA
2. Application share option is still visinble

![b](https://user-images.githubusercontent.com/31848014/181770992-d3e7a39b-c7fc-4c10-aa6a-a848a89bce34.png)

Used pack > https://wso2.org/jenkins/job/products/job/product-is/4190/artifact/modules/distribution/target/wso2is-6.0.0-alpha4-SNAPSHOT.zip

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3249
