### ISSUE TITLE
Dynamic application requested scopes for federated IdP login

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#14473]
Currently only a static set of scopes can be set when configuring an external IdP. Allowing the service provider to dynamically request different scopes is important when the IS has to work as a transparent federation hub connecting multiple SPs. In a scenario where a number of service providers are connecting through IS to one federated IdP, implementing pass-through application requested scopes becomes necessary if:

- Different service providers request different sets of scopes. 
- The same service provider dynamically requests a different set of scopes for different operations. 

In this case a static set of scopes configured in the IdP will not be adequate. 
If the scope dialect of the SPs and IdPs are the same, the requested scopes can be allowed to pass-through to the IdP without any modifications. Otherwise if the scope dialects are different between SPs and IdPs, then scope mappings may need to be implemented.

![Flowcharts (1)](https://user-images.githubusercontent.com/46979289/194495966-d945157c-d996-4c5c-a696-227e4480c817.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
