### ISSUE TITLE
Maximum number of Roles and Entitlement information that can be registered with WSO2IS console.

### ISSUE THREAD

**Issue by Ajaysamdyan** [wso2/product-is#14482]
**Environment information**
 - Product Version: [AM 2.6.0, IS 5.7.0]
 - OS: [ Linux]
 - Database: [MySQL]
 - Userstore: [LDAP]

**Describe the issue**
I have few queries regarding entitlement information such as:
1. How many maximum number of Roles that can be created on IS Management Console.
　
2. How many maximum number of Entitlement information that can be created by PAP on IS Management Console.
　・Rule
　・Policy
　・PolicySet
　・Policy, PolicySet that can be added to PolicySet
　
3. How many maximum number of Entitlement information that can be set to publish from PAP to MyPDP.
　・Rule
　・Policy
　・PolicySet
4. Is there maximum value impacted if we create the sub-tenants.
Kindly share your suggestion on above queries or any related official document for the reference if any.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
