### ISSUE TITLE
Remove the LogoutRequestDenied component of React SDK sample app

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#14489]
**Current state**
The current [LogoutRequestDenied](https://github.com/asgardeo/asgardeo-auth-react-sdk/blob/main/samples/asgardeo-react-app/src/components/LogoutRequestDenied.tsx) component looks as follows,

![Screenshot 2022-08-02 at 10 27 33](https://user-images.githubusercontent.com/27714968/182353398-031a3c85-f36d-41e1-85ca-5949abf8c498.png)

**Improvement**
This component will be redundant with the [change](https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/125) where user session exists only in IdP side at this point. Therefore, only the `Try Log in again` will have an effect. Suggestion is to remove this component and do a silent log in instead. 

**Additional context**
Follow [these steps](https://github.com/asgardeo/asgardeo-auth-react-sdk#try-out-the-sample-apps) to get the React SDK sample app up and running (Note: Enable the logout consent while configuring the SP). Login to the sample app and logout but press `No` when asked for the consent. You will see this screen after these steps.

**Related issues**
- https://github.com/wso2/product-is/issues/13366

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
