### ISSUE TITLE
Improve the UI of magic link notifications

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14488]
**Is your suggestion related to an experience ? Please describe.**
Currently UI of magic link notification shows following, and better to improve this UI.

![Screenshot 2022-08-02 at 12 54 46](https://user-images.githubusercontent.com/39077751/182345765-6b456e74-60c1-4827-999b-0d28e2105fc6.png)

**Describe the improvement**
1. Improve the UI with match with the product theame
2. Add for functionality will increase the user experience. 

- [ ] "Back" button to navigate again user name page
- [ ] Add link resend button
- [ ]  Add contact detail for support if any case user not receive the email
- [ ] Add link to log my account so user can update email there. 

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
