### ISSUE TITLE
Configuring Access Delegation with OAuth 2.0 document is outdated

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14485]
**Is your suggestion related to a missing or misleading document? Please describe.**
There are multiple issues while trying out the samples in [1]. A list of workaround to bypass the issues is listed in [2]. (But these are not the proper solutions)

[1] https://is.docs.wso2.com/en/latest/learn/configuring-access-delegation-with-oauth2/
[2] https://yumanimanodyaranaweera.medium.com/access-delegation-oauth-2-0-sample-wso2-4c5d893337c0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
