### ISSUE TITLE
Magic link button is not aligned  in multi option authentication windows. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14486]
**Describe the issue:**
Magic link button is not aligned  in multi option authentication windows. 

<img width="660" alt="Screenshot 2022-08-02 at 12 38 00" src="https://user-images.githubusercontent.com/39077751/182338428-444872ca-f912-41c1-b142-3d2f8c6a7152.png">

**How to reproduce:**
1. login to management console
2. Configure application
3. Configure Multi option authentication
4. Access the application

**Expected behavior:**
Login option UI button should be aligned properly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
This issue is fixed by the following PR - https://github.com/wso2/identity-apps/pull/3261
