### ISSUE TITLE
SQL syntax error while executing BPS scripta agianst mysql 8 with latest IS 5.3.0 U2 pack

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14484]
**Describe the issue:**

1. wum update  IS 5.3.0 with wum update wso2is-5.3.0 -t 1601997504472
2. Get the wum updated pack u2 update it (wso2is-5.3.0.25)
3. Execute bps/bpel/create/mysql.sql against mysql 8.029 (db viewer driver jar version 8.0.29)

![Screenshot from 2022-08-02 12-55-45](https://user-images.githubusercontent.com/31848014/182316779-94c25001-5356-4f4f-9c2a-2f010acc4344.png)

Getting below error

![Screenshot from 2022-08-02 12-49-11](https://user-images.githubusercontent.com/31848014/182316587-0b99487c-b59c-4512-b0e6-8112b2aa9d6f.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
