### ISSUE TITLE
Commonauth endpoint return CORS headers for simple POST request 

### ISSUE THREAD

**Issue by Manchiz** [wso2/product-is#14490]
**Describe the issue:**
Observed commonauth endpoint return CORS headers for all simple POST requests.

This behaviour seems to present after the release fix [1]

[1]. https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/139/files

**How to reproduce:**
Use the following sample request. Here, the Origin header is set as "https://test:9443/". But it is possible to notice CORS headers returned with the response.

```
curl --location --request POST 'https://localhost:9443/commonauth' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Origin: https://test:9443/' \
--header 'Referer: https://localhost:9443/authenticationendpoint/login.do?client_id=MY_ACCOUNT&code_challenge=aJEAI3Nyc191Dwp4RaJE1Rdj1ygX26EQ5T97JxY68qg&code_challenge_method=S256&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Fmyaccount%2Flogin&response_mode=form_post&response_type=code&scope=SYSTEM+openid&tenantDomain=carbon.super&sessionDataKey=3df6852a-177d-4626-a9c9-49933075c26d&relyingParty=MY_ACCOUNT&type=oidc&sp=My+Account&isSaaSApp=true&authenticators=BasicAuthenticator%3ALOCAL' \
--header 'Cookie: JSESSIONID=5F63F186D9D813547864BF277B1A11E1' \
--data-urlencode 'usernameUserInput=admin' \
--data-urlencode 'username=admin' \
--data-urlencode 'password=admin' \
--data-urlencode 'sessionDataKey=3df6852a-177d-4626-a9c9-49933075c26d'
```

**Expected behavior:**
Allowed CORS only for redirection (302 ) requests in order to support the federated authentication flow. Not required to allow CORS for all HTTP requests coming from another domain.

**Environment information**
 - Product Version:  wso2is-5.11.172
---

**Comment by WnsRKant** [comment]
I am really not able to understand the explanation. can  you please elaborate in  detail. As per the error its clearly mentioned that once request intercepted and pass some different value in domain wso2 is returning same in response also we have tried to put restrictions which not worked.
