### ISSUE TITLE
Magic link option is not available on Console

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14499]
**Describe the issue:**
Magic link option is not available on Sing on method options in Console

https://user-images.githubusercontent.com/39077751/182530709-a90ceb6a-7fb6-4ce4-b3f6-40a6ce4a89e0.mov

**How to reproduce:**
1. Login to console
2. Create application
3. Navigate to application edit -> Sign-on methods
4. Select identifier as first authentication steps
5. Add another authentication step
6. Click add authentication link and search for magic link option

**Expected behavior:**
Magic link option should be available on console sing  in option and should be configurable via console. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
This is fixed in the latest pack https://github.com/wso2/carbon-identity-framework/commit/892e9a8cab24e16b6d19c53b763f26eec7f16674
<img width="1082" alt="Screenshot 2022-08-03 at 12 02 34" src="https://user-images.githubusercontent.com/17597293/182540161-006ded4c-519f-4f43-8f23-b429fc3140bf.png">
