### ISSUE TITLE
Disable/enable accessing cross tenant token details based on a configuration documentation

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#14496]
**Is your suggestion related to a missing or misleading document? Please describe.**
cross-tenant token introspection will be allowed/blocked based on a configuration.

**Describe the improvement**

### In IS-6.0
By default cross-tenant token introspection will be disabled, by adding the following configuration to `<IS-HOME>/repository/conf/deployment.toml` cross-tenant token introspection can be enabled.

```
[oauth.introspect]
allow_cross_tenant = true
```
Migration Issue 

- [https://github.com/wso2/product-is/issues/14481](https://github.com/wso2/product-is/issues/14481)

### In the older versions (IS-5.11.0 to IS-5.6.0 )
By default cross-tenant token introspection will be enabled, by adding the following configuration to `<IS-HOME>/repository/conf/deployment.toml` cross-tenant token introspection can be disabled.

```
[oauth.introspect]
allow_cross_tenant = false
```
Related Issue: 

- [https://github.com/wso2/product-is/issues/13683](https://github.com/wso2/product-is/issues/13683)

**Comment by piraveena** [comment]
This is already fixed in public.
@lashinijay Any idea why we didn't fix the doc since this change is done as a patch?

**Comment by ImalshaG** [comment]
This config is diabled by default in IS 6.0.0 and the docs are added from the PR: https://github.com/wso2/docs-is/pull/3219

**Comment by nilasini** [comment]
@piraveena seems it has been missed to be updated in the older docs. We have updated it now.
