### ISSUE TITLE
[Improvement] Refactor code and create reusable code for identity-otp-integration-endpoints

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#14491]
**Is your suggestion related to an experience ? Please describe.**
There are two similar  APIs(/validate and /verify) that are using different methods in https://github.com/wso2-extensions/identity-otp-integration-endpoints

**Describe the improvement**
Better to update API permission and scope in here

        <b>Permission required:</b><br>
        * none<br>
        <b>Scope required:</b><br>
        * internal_login

Better to update the logic here(check for isValid 1st and then get the failure reason)

[main/java/org/wso2/carbon/identity/api/otp/service/emailotp/impl/EmailotpApiServiceImpl.java](https://github.com/wso2-extensions/identity-otp-integration-endpoints/pull/7/files/ff0a30012ef1111d0d97d89d656c439a79d91f91#diff-7abccf8ef16e86d486d2166e0fae4fed071cbf7246135d15934e66c46d5870de)

                    transactionId, userId, emailOtp);
            FailureReasonDTO failureReasonDTO = responseDTO.getFailureReason();
            OTPVerificationFailureReason failureReason = null;
            if (failureReasonDTO != null) {

Better to create common method for verify and validate api. (we can pass a parameter to identify the API call). the we can create reusable code blocks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
