### ISSUE TITLE
Suggestion to change the Signing Up term to Sign Up or Initiate Sign up in customization done self register page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14509]
**How to Reproduce**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4200/
2. Configure pack with customizable login portal feature https://docs.google.com/document/d/1_XUbmrokb1Yy7T1eZ8wpiq5i3eKwxEXxrwbBmX5xC4Q/edit
3. Login to managemnt console and enable self registration from account management
4. Access console
5. Click on Create account

In the self registration page word Signing up is not much meanigful. As dicussed with doc team to about the usage of this word we can  have either one of below

Sign Up
Initiate Sign Up

![d](https://user-images.githubusercontent.com/31848014/182617156-fafce87b-ff6f-4017-8040-960f6fcb53ab.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
h2 default

**Comment by DilshanSenarath** [comment]
Update the page with **Initiate Sign Up** text.
