### ISSUE TITLE
When generate a authentication error page with customize login portal changes enabled given error is not aligned in the page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14506]
**How to reproduce:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4200/
2. Configure pack with customizable login portal feature https://docs.google.com/document/d/1_XUbmrokb1Yy7T1eZ8wpiq5i3eKwxEXxrwbBmX5xC4Q/edit
3. Login to managemnt console
4. Enable multi attribute login for email address claim (add only this claim under claim list). https://is.docs.wso2.com/en/latest/learn/multi-attribute-login/#:~:text=Configuring%20WSO2%20IS%20for%20Multi%20Attribute%20Login,-Start%20WSO2%20Identity&text=Click%20Main%20%3E%20Identity%20Providers%20%3E%20Resident,regular%20expression%20for%20allowed%20claims.
5. Create a user and set a value for email address claim
6. Access console
7. Try to login to console with a incorrect user id value to get a error page generated

user id - shanikanishadhi1992@gmail.com ( correct value will be shanikanishadhi1992@gmail.com@carbon.super)
pw - shanika

Error page generated with authetication end point with customized login page, the error message is not aligned in the page. More white space towards bottom in the page

![b](https://user-images.githubusercontent.com/31848014/182596648-aa87f7fb-fef4-4f32-aba4-d6ddc46df41a.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 H2 default

**Comment by DilshanSenarath** [comment]
Error Message is aligned to middle
![Screenshot from 2022-08-04 20-27-28](https://user-images.githubusercontent.com/74205483/182879591-f3116738-8b1f-4353-8ac3-15189fbc71c4.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
