### ISSUE TITLE
Add identifier first as a option on sign on page 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14500]
**Is your suggestion related to an experience ? Please describe.**
It is not user-friendly when adding identifier first option in sing on method in console. 1st its required to select one option which available on below  UI and then remove it and add identifier first option. This is not a good user experience. 

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/39077751/182533657-d0fd76af-bd26-4ea2-8bb3-1d7030b9e700.png">

**Describe the improvement**
This is to propose to add identifier first as the  option for sign on method UI in below,
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/39077751/182533657-d0fd76af-bd26-4ea2-8bb3-1d7030b9e700.png">

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
