### ISSUE TITLE
Authentication Error page background color is not consistent with the dark mode

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14507]
**How to reproduce:**
1. Follow the steps in https://github.com/wso2/product-is/issues/14506 to get the issue reproduced
2. Change the mode to dark mode from toggle button

The error messages is shown with a light pink colour background which is not consistent with the dark mode

Is there any possibilty to change the background clour of this error page to get consistent with dark mode'
As we are planning to provide this sample as the code sample for customers can we change it to support by default

![c](https://user-images.githubusercontent.com/31848014/182600025-a3165c52-e3da-4f5a-abb5-82f243c5977a.png)

![Screenshot from 2022-08-04 10-34-41](https://user-images.githubusercontent.com/31848014/182767207-052bf7a0-145b-44ca-90ff-936b85869838.png)

What do you think if we can provide the error page in dark mode with similar background colurs like this which will not get highlighted in a sudden as above
Attaching a sample below

![Screenshot from 2022-08-03 17-22-39](https://user-images.githubusercontent.com/31848014/182601629-7cf06ad7-ae39-41ed-be04-8be05038e205.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 H2 / default

**Comment by DilshanSenarath** [comment]
New Message Box for Dark Mode

Success Message
![Screenshot from 2022-08-04 19-28-29](https://user-images.githubusercontent.com/74205483/182865796-d1ec4921-fe1e-4053-9814-d3dd96b3a322.png)

Error Message
![Screenshot from 2022-08-04 19-36-15](https://user-images.githubusercontent.com/74205483/182867336-f40de9a0-98df-4aa9-9ab1-3a074a3751dc.png)

Info Message
![Screenshot from 2022-08-04 19-37-26](https://user-images.githubusercontent.com/74205483/182867601-acf1d4a7-84c5-4e0e-b006-a906d83a4f82.png)

Warning Message
![Screenshot from 2022-08-04 19-35-06](https://user-images.githubusercontent.com/74205483/182867128-df960295-ba44-496e-bd4d-10749620d53c.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
