### ISSUE TITLE
Same link given for the different option for downloading google authenticator

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14514]
**Describe the issue:**
Following links contains the same link. 
<img width="544" alt="Screenshot 2022-08-03 at 20 31 53" src="https://user-images.githubusercontent.com/39077751/182668330-b444e3fc-80cf-4f81-99c9-815b01f2d473.png">

**How to reproduce:**
1. Login to My account
2. navigate to security page
3. Select Authenticate app option
4. Click links on bottom of the window

**Expected behavior:**
It should be two different links

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/3278
