### ISSUE TITLE
continuously display the TOTP setup error message 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14512]
**Describe the issue:**
Below error message which get after enter invalid  TOTP, keep getting display. 

<img width="519" alt="image" src="https://user-images.githubusercontent.com/39077751/182575848-ca329e9c-e79e-4536-bd82-e4b92268c418.png">

https://user-images.githubusercontent.com/39077751/182576252-c90b53cb-5622-4f90-8a36-b3f0ada6a43e.mov

**How to reproduce:**
1. Login to myaccount and navigate to  security page
2. Click Authenticator app and add invalid TOTP
3. Close the window and click again the Authenticator App

**Expected behavior:**
Error message should not be there when opening window again

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
This is expected behaviour according to the current implementation. We don't have a way to remove the error msgs coming as query param. this can be observed in other UIs as well
