### ISSUE TITLE
OOM caused by RegistryCleanUpService

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14516]
**Describe the issue:**
The RegistryCleanUpService which is run every 24 hours by default, is trying to load the registry of all these tenants [1]. This initializes caches for all the tenants and causes the server to go OOM when there is a large number of tenants available in the system (active or inactive).

This task is trying to cleanup confirmation codes stored in the registry (/repository/components/org.wso2.carbon.identity.mgt/data). But the confirmation codes are stored in the DB in the new implementation.

**How to reproduce:**
- Created around 100K tenants
- Keep all of them deactivated status (a large number of deactivated tenants is a practical scenario when tenancy-related tests are run)
- Keep the server running for 24 hours
- The server will go OOM

**Temporary solution:**
- Goto IS_HOME/repository/conf/identity/identity-mgt.properties file
- Set the value of the following line to `0`.
 `Identity.Mgt.Registry.CleanUpPeriod=1440`
- Then restart WSO2 IS

**Proposed solution:**
Set the above value by default in the product.

**Environment information**
 - Product Version: IS 5.11.0

[1] https://github.com/wso2/carbon-identity-framework/blob/bda310b09f6b5dc5f87826bb77b00dd81b3829b5/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/store/RegistryCleanUpService.java#L84-L100

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
