### ISSUE TITLE
[DOC] Improve DB advanced configuration documentations

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#14521]
**Is your suggestion related to a missing or misleading document? Please describe.**
From IS 5.10.0 onward, DB transaction committing and rollback is handled through the code and not needed to be configured through advanced DB configurations such as **defaultAutoCommit and commitOnReturn** [1]. Hence we need to advise users to turn-off these configurations for their deployments. 

Also regarding the documentation on [2], `ConnectionRollbackOnReturnInterceptor` is being removed from product with following fix [3]. Hence we need to remove `ConnectionRollbackOnReturnInterceptor` mentions in the doc.

[1] https://is.docs.wso2.com/en/latest/setup/changing-to-mysql/#changing-the-default-datasource
[2] https://is.docs.wso2.com/en/latest/setup/changing-to-mysql/#configuring-the-connection-pool-behavior-on-return
[3] https://github.com/wso2/carbon-kernel/pull/1805

**Comment by nilminiwso2** [comment]
Apply all fixes related to [1].

[1] https://github.com/wso2/product-is/issues/11002

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by vfraga** [comment]
Worth mentioning that, although this is currently closed, `ConnectionRollbackOnReturnInterceptor` was removed from the product 8 years ago and it's still being mentioned in the latest documentation.
