### ISSUE TITLE
SSO to myaccount from console is not working as expected

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14525]
**Describe the issue:**
The pack downloaded from the build https://wso2.org/jenkins/view/products/job/products/job/product-is/4203/, redirecting to the blank page when SSO to myaccount from the console.

https://user-images.githubusercontent.com/13362482/182828719-8600a825-38e1-413c-8d66-c793124ebad4.mov

**How to reproduce:**

- Obtain the latest snapshot pack from this build https://wso2.org/jenkins/view/products/job/products/job/product-is/4203/
- Login to console
- Try the login with myaccount from console.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Getting this exception
```
Uncaught SyntaxError: Unexpected token '*'
(index):58 Uncaught ReferenceError: AsgardeoAuth is not defined
    at (index):58:28
``` 
- When swtiching to MyAccount from Console
- When accessing `https://localhost:9443/console/`

**Comment by yathindrakodithuwakku** [comment]
SSO to the myaccount from console is now working

https://user-images.githubusercontent.com/32919513/182847879-a1f613ae-a38e-4986-95bd-7e49d446605d.mp4
