### ISSUE TITLE
No going back when select regenerate button at TOTP

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14523]
**Describe the issue:**
After selecting the regenerate button at TOTP no going back. This is not a good user experience. There should be cancel button or  close button to navigate to previous security page. Unless user have to reload the page.

<img width="864" alt="Screenshot 2022-08-04 at 14 39 12" src="https://user-images.githubusercontent.com/39077751/182810627-8baec67b-af0a-4621-8770-acda326be4f6.png">

**How to reproduce:**
1. Login to my account
2. Register TOTP
3. Click to regenerate the TOTP again
4. Check for going back or cancel

**Expected behavior:**
There should be mechanism to going back. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
