### ISSUE TITLE
Error in identity-governance call when login in to the console

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#14526]
**Describe the issue:**
There is an error shown in the UI when trying to login as a user with only the below permission
- Login
- Human Tasks 
- Workflow Management > BPS Profile

![Screenshot from 2022-08-04 14-53-08](https://user-images.githubusercontent.com/36092400/182828943-cfa4c918-40ae-41d4-be1d-3c67d8bf93cd.png)

**How to reproduce:**
1. start the IS 6.0.0 alpha 3 pack
2. login to the management console
3. create a role with below only below permissions
    -  Login
    - Human Tasks 
    - Workflow Management > BPS Profile  
4. Create a user and assigned the created role 
5. Login to the console using as the that created user

Identity-governance API call is failing due to not having permission for that and shown the above error message in UI

**Expected behavior:**
No need to show an error message to the user
![Screenshot from 2022-08-04 12-08-58](https://user-images.githubusercontent.com/36092400/182829601-2b3d43b3-b98e-4f9e-adc9-b580950c1404.png)

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
