### ISSUE TITLE
Changing directory attribute of AccessLogValve in catalina-server.xml.j2 

### ISSUE THREAD

**Issue by nipunaupeksha** [wso2/product-is#14534]
**Describe the improvement**
The directory attribute in _catalina-server.xml.j2_ template `AccessLogValve` should be configurable. 
Although the current .j2 template value for the directory attribute is `"${carbon.home}/repository/logs"`, if we need to change it to a separate directory which is not in IS Home(eg: `"extras/logs"`), it is not possible with the current implementation. Is it possible to configure it so that we can change the location using deployment.toml file?

**Comment by nilasini** [comment]
Consider the other properties which could be template as well. In [1] other properties also templated. so there is a chance to get a new requirement.

[1] https://github.com/wso2-support/product-apim/pull/607/files
