### ISSUE TITLE
Input fields are not properly aligned in 'Add User' section in sub-organization

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14530]
**Describe the issue:**
Please refer to this screencast

https://user-images.githubusercontent.com/13362482/182843703-3d387ec4-e7da-4011-a837-ad135c97a02e.mov

**How to reproduce:**

- Enable the org-mgt feature
- Login to console as admin user
- Create sub-organization
- Switch to the sub-organization and try to add a new user

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Kanapriya** [comment]
Identified this issue when we do a test round against MSSQL 2019 on RC pack (wso2is-6.0.0-beta2-SNAPSHOT) with organization management feature today.

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3328
