### ISSUE TITLE
[Migration] Restricting claims sent to the Application when SP Requested Claims are not Configured

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#14536]
**Describe the issue:**
During federated login flow if requested claims are not configured for a service provider, none of the user claims sent from the external IDP will be sent to the application through the id_token.

In 5.11.0 in the above scenario, all the claims sent from the external Idp will be sent to the application. 

If the previous behaviour is needed, the following configs can be added to the deployment.toml so that during the federated flow if no claims are configured for the SP, all the user claims sent from the federated IDP will be available in the id_token in the local dialect.

```
[authentication]
allow_sp_requested_fed_claims_only =false

[oauth.oidc.claims]
enable_oidc_dialect=false
```

Related issue: https://github.com/wso2/product-is/issues/14447

**Comment by ashendes** [comment]
Addressed in https://github.com/wso2/docs-is/pull/3232
