### ISSUE TITLE
UI loading continuously when view the assigned users in 'Roles' section in the sub-organization

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14531]
**Describe the issue:**
If the sub-organization doesn't have users initially and then if we view 'Users' in the 'Roles' section, it doesn't show the expected result. Please refer to this screencast.

https://user-images.githubusercontent.com/13362482/182848081-90b5aa68-b40c-450b-b428-dd58f5d91399.mov

It shows the expected output if at least one user available in the organization

https://user-images.githubusercontent.com/13362482/182849182-0519f4af-5dbe-40f9-9ae4-10f8c2a7331a.mov

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3286
