### ISSUE TITLE
Add a documentation on how to integrate well known external applications with the WSO2 IS for SSO

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#14535]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently, we do not have official documentation on how to integrate well known external applications with the WSO2 IS for SSO.

**Describe the improvement**
It would be great if there is official documentation on how to integrate well known external applications such as sentry.io with the WSO2 IS for SSO

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
