### ISSUE TITLE
Adaptive authentication script UI misaligned

### ISSUE THREAD

**Issue by nirmal101** [wso2/product-is#14532]
**Describe the issue:**

-  In the Advanced Adaptive authentication configuration section of a service provider, the add icons of the templates are not aligned with their description.

**How to reproduce:**

1.  Go to, Management Console>Edit Service Provider>Local & Outbound Authentication Configuration>Authentication Type>Advanced Configuration> Script Based Adaptive Authentication > Templates

![Screenshot_1](https://user-images.githubusercontent.com/43103902/182849432-582dd0d5-1fcc-42f0-b572-41ad166dc693.png)

**Environment information**
 - Product Version: wso2is-6.0.0-beta2-SNAPSHOT
 - OS: Windows 10
 - Browser: Google Chrome
 - Java version: Open JDK 17

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
could not reproduce this issue in JDK 11 and 17. Tried with both Chrome(103.0.5060.134) and Firefox.

<img width="413" alt="Screenshot 2022-08-05 at 15 04 06" src="https://user-images.githubusercontent.com/17597293/183050383-0c33a1a8-088f-4244-acbf-15c100622c62.png">
<img width="600" alt="Screenshot 2022-08-05 at 15 04 00" src="https://user-images.githubusercontent.com/17597293/183050389-ae31981e-bc0c-4fa0-bae9-2ae551ecf592.png">

**Comment by ShanikaWickramasinghe** [comment]
@nirmal101 this issue was specific for windows OS right ? pls confirm

**Comment by asekawa** [comment]
**Getting the same issue when executing in the Windows OS**

<img width="930" alt="Capture" src="https://user-images.githubusercontent.com/40081059/183258673-f2ae49b1-4c13-4b15-bdca-dbea5dd2acbb.PNG">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
