### ISSUE TITLE
Authentication Context Cache - Optimization 

### ISSUE THREAD

**Issue by Thananchseyan** [wso2/product-is#14549]
**Is your suggestion related to an experience ? Please describe.**

When we consider the temporary session data types,  the size of the Authentication Context Cache is large. Based on the analysis, we had some suggestions for the optimization of the authentication context cache. We have 

1. Some set of data that is defined in the server which are stored in the session objects. 
2. Entire Identity Provider and Service Provider objects which are also defined in the server.
3. Some repeated values in a few distinct places of authentication context. 

We can optimize the server level data by persisting only the reference of them instead of the entire object.

**Describe the improvement**

![Modified Diagram](https://user-images.githubusercontent.com/64280882/183045999-b9f1be19-96dd-49b5-a497-641e5a9f407b.jpeg)

Authentication Context Loader class was created to optimize the authentication context cache object and load the optimized authentication context cache object. We are going to optimize the authentication context object when the context object passes to the authentication context cache class using addToCache method. We introduced some attributes to store the reference in respective classes which have bulk objects and server level data. We are going to set the references in newly added attributes and set the bulk objects as null during the optimization. We are going to load the optimized object by using those references. 

**Additional context**

[https://github.com/wso2/carbon-identity-framework/pull/4059](https://github.com/wso2/carbon-identity-framework/pull/4059)

**Comment by senthalan** [comment]
Implemented with https://github.com/wso2/carbon-identity-framework/pull/4446
