### ISSUE TITLE
Some API endpoints are not provided access for the Organization Management Feature

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#14548]
# Describe the issue:
Following Organization Management APIs are not given permission [Unsupported organization-specific routing endpoint],

##  API 1

> In the adaptive authentication, there's an Auth Call to Choreo to retrieve the secrets. 
> https://localhost:9443/api/server/v1/secrets/ADAPTIVE_AUTH_CALL_CHOREO

https://user-images.githubusercontent.com/59449070/183009289-c590d0e3-0e84-4a68-8fe0-9058b5e5560c.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Create an application and share the application with created organizations or create an application in the sub-organization.
* Go to the Sign-in Method section of the application.
* End up with the following error

![Screenshot 2022-08-05 at 02 16 04](https://user-images.githubusercontent.com/59449070/183009616-7a2dfb6f-c68a-4798-9113-3b6b59f23ed9.png)

## API 2

> In the provisioning section of the application, there's an API Call to userstore. 
> https://localhost:9443/o/48d93108-bdf5-462a-bfef-359251630696/api/server/v1/userstores

https://user-images.githubusercontent.com/59449070/183010480-1dfce7f0-7ac0-44bb-b20b-9cac6b80f1aa.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Create a user providing access to create an application 
* Create an application and go to the **Provisioning** section of the application.
* End up with the following error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59449070/183010869-f69b69b4-0d80-4dd5-a7a2-54bb8c193bf2.png">

## API 3

> In the outbound provisioning section of the IdP, there's an API Call to Roles. 
> https://localhost:9443/scim2/Roles

https://user-images.githubusercontent.com/59449070/183011651-c74ba57c-86ca-46ed-9802-12071ae5043f.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Create a user providing access to create an IDP 
* Create an IdP and go to the **Outbound Provisioning** section of the application.
* End up with the following error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59449070/183011918-96c64782-e2d9-481f-af12-a5ea56370a9c.png">

## API 4

> In the just-in-time provisioning section of the IdP, there's an API Call to userstores. 
> https://localhost:9443/o/48d93108-bdf5-462a-bfef-359251630696/api/server/v1/userstores

https://user-images.githubusercontent.com/59449070/183051963-51ef6f6a-7bd6-4aab-8ec4-34c07435d61c.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Create a user providing access to create an IDP 
* Create an IdP and go to the **Just-in-Time Provisioning** section of the application.
* End up with the following error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59449070/183052438-03b2df9a-733e-4e24-9d9f-6c8a0ff369a5.png">

## API 5

> Create a user in the sub-organization assigning a role will call to scim2/Roles endpoint. 
> https://localhost:9443/o/48d93108-bdf5-462a-bfef-359251630696/scim2/Roles/fcbd5d8c-e9ba-4ff7-aa2c-d059581878b0

https://user-images.githubusercontent.com/59449070/183053704-b4300ce9-99cd-4475-8fd7-fbd7d41dd47c.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Create a user assigning a created role.
* End up with the following error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59449070/183054134-269aa98d-96bb-46d5-ad8c-2e74b93b9584.png">

## API 6

> Create a Group in the sub-organization assigning a role will call to scim2/Roles endpoint. 
> https://localhost:9443/o/48d93108-bdf5-462a-bfef-359251630696/scim2/Roles/fcbd5d8c-e9ba-4ff7-aa2c-d059581878b0

https://user-images.githubusercontent.com/59449070/183056617-4e4e2929-d4c4-418d-9e10-e5bafd14f53d.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Create a Group assigning a created role.
* End up with the following error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59449070/183056466-01cabf8f-585f-43f8-bbc6-340ccab5a6b1.png">

## API 7

> Start to create a Role in the sub-organization, will call to userstores endpoint. 
> https://localhost:9443/api/server/v1/userstores

https://user-images.githubusercontent.com/59449070/183057620-e9ea2876-a64f-46a0-901f-f7534e80572d.mov

**How to reproduce:**
* Login to console as admin user
* Create sub-organizations under the 'Super' organization
* Try to create a role.
* End up with the following error

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/59449070/183057574-01760297-0761-4388-8009-561c0e3df640.png">

# Expected behavior:
> Provide access to certain end points and remove the rest so that the flow will work properly.

# Environment information
 - Product Version: Latest Pack
     - 6.0.0-beta2-SNAPSHOT - Product-IS
     - <identity.org.mgt.version>1.0.75</identity.org.mgt.version>
     - <identity.apps.version>1.3.43</identity.apps.version>
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

---

**Comment by madurangasiriwardena** [comment]
In the User attributes section of an application, below APIs are invoked.

> https://localhost:9443/api/server/v1/claim-dialects/local/claims?exclude-identity-claims=false
> https://localhost:9443/api/server/v1/claim-dialects
> https://localhost:9443/api/server/v1/claim-dialects/local/claims
