### ISSUE TITLE
Improve the Claim Handling Behaviour in Federated Flow when No SP Attributes are Configured

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#14547]
**Is your suggestion related to an experience ? Please describe.**
The current claim handling behaviour in IS 6.0.0 during the federated flow is as follows:
- when no SP requested attributes are configured, no claims are returned in the id_token.
- when SP requested attributes are configured, the requested attributes are returned filtered by the scope.

**Describe the improvement**
This behaviour should be improved as follows:
- when no SP requested attributes are configured, the available user claims sent by the external Idp should be sent to the application filtered by the requested scope. Consent should be requested for the claims added to the id_token.
- when SP requested attributes are configured, the available user claims should be filtered by both configured SP requested attributes and the requested scope of the authorization request.

This is based on the decision taken to send all federated claims to the app when there are no configured SP requested attributes.
Email thread: "Different claim handling behaviour in IS versions for external IdP login"
Related issue: https://github.com/wso2/product-is/issues/14447

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
