### ISSUE TITLE
Extra comma and a fullstop available in the group delete confirmation content

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14557]
**Describe the issue:**
1. create a group via console
2. Try to delete the created group

In the delete confirmation messages there is a extra . and a , both
![Screenshot from 2022-08-06 09-19-10](https://user-images.githubusercontent.com/31848014/183232531-ac8b8918-b4f6-434e-9e6c-b38cba08e5fe.png)

pack https://drive.google.com/file/d/1wZVqkCT1GZNr_mjYbowH9q3MIq195tAm/view?usp=sharing
he default

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3300
