### ISSUE TITLE
Username Recovery Flow Mandatory fields are not marked in the username recovery form

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14563]
**Describe the issue:**
1. Configure a Username recovery Flow
2. Try to recover username 
3. All the fields shown as optional
4. Click Submit without filling any

Here we need to maek the mandotroy field in the UI with a asterik
![Screenshot from 2022-08-06 13-38-22](https://user-images.githubusercontent.com/31848014/183240613-00f68611-23e3-4c5c-a527-ebac705344fa.png)

pack https://drive.google.com/file/d/1h3ynCA_1kLKPovRahbDtrtGvFYxXkbvs/view

**Comment by hwupathum** [comment]
The same issue is in recover password flow as well
<img width="610" alt="Screenshot 2022-08-07 at 08 47 16" src="https://user-images.githubusercontent.com/46132469/183273485-f0136d50-5338-4ac4-b92f-2ca9bfc169e0.png">

**Comment by hwupathum** [comment]
Related to https://github.com/wso2/product-is/issues/14591
