### ISSUE TITLE
OpenID Configuration and WS-Federation (Passive) Configuration sections are marked as configured by default

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#14566]
**Describe the issue:**

**OpenID Configuration** and **WS-Federation (Passive) Configuration** sections  are marked as configured  by default  , even though its not configured yet by the user.

<img width="1480" alt="Screenshot 2022-08-06 at 14 57 05" src="https://user-images.githubusercontent.com/40081059/183243504-b319d3d8-c706-4574-84d0-71f9be8a4d5c.png">

**How to reproduce:**
1.Login
2.Create a service provider
3.Navigate to **Inbound Authentication Configuration** section

pack:https://drive.google.com/file/d/1h3ynCA_1kLKPovRahbDtrtGvFYxXkbvs/view

**Comment by ThumulaPerera** [comment]
Same behaviour was observed in IS 5.11 as well
