### ISSUE TITLE
Update Docs related to rename basic authenticator to username and password

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14560]
**Describe the issue:**
1. Create a SP
2. Go to advanced configs

Basic authenticator is now renamed as username and password. We need to update all the docs where this is used (Images etc

![Screenshot from 2022-08-06 12-47-22](https://user-images.githubusercontent.com/31848014/183239004-c7093879-9c6b-4c90-86b1-1c18b40d0e20.png)

pack https://drive.google.com/file/d/1h3ynCA_1kLKPovRahbDtrtGvFYxXkbvs/view

**Comment by piraveena** [comment]
THis is done via this changes https://github.com/wso2/product-is/pull/14487. @yasinmiran please update the docs

**Comment by mpmadhavig** [comment]
The local authentication type **fido** is also renamed as **Security Key/Biometrics**. Related docs need to be updated for this as well.

**Comment by divyaamunugama** [comment]
Closing the issue as it is completed through the following PRs

https://github.com/wso2/docs-is/pull/3288
https://github.com/wso2/docs-is/pull/3447
https://github.com/wso2/docs-is/pull/3446
