### ISSUE TITLE
Unable to Load Myaccount in safari 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#14574]
**Describe the issue:**
Getting an empty page when accessing My account via Safari

**How to reproduce:**
1. Start up the server 
2. Try to access my account via the safari browser
2.1 Direct access  https://localhost:9443/myaccount
2.2. Access the console and try to SSO to my account 

**Expected behavior:**
There shouldn't any issues when accessing my account via Safari

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-beta2-SNAPSHOT
 - OS: MACOS Monterey 12.4 (21F79)
 - Database: H2
-Browse - Safari Version 15.5 (17613.2.7.1.8)
java 11.0.14 2022-01-18 LTS
Apple M1 Pro

---

<img width="1724" alt="Screenshot 2022-08-06 at 19 03 27" src="https://user-images.githubusercontent.com/39120228/183251450-6ab3368b-83c4-4878-a428-a921b2cf7ea0.png">

**Comment by thivi** [comment]
I was not able to reproduce this issue in Safari.
![image](https://user-images.githubusercontent.com/20745428/183281893-a7d89d98-e98d-47bc-8065-95d8486f711f.png)
