### ISSUE TITLE
Confusing mandatory attribute(Display Name) when creating user store from Console app 

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#14573]
When creating a userstore from console app in the second page in the wizard (user related page) it asks for a mandatory input called "Display Name" what this is required for is very confusing. Coudn't locate a doc that explains that also. And when creating a userstore from the management console it doesn't ask for this attribute.
<img width="741" alt="Screenshot 2022-08-06 at 18 55 03" src="https://user-images.githubusercontent.com/11583571/183250873-7b0c9fac-a9a9-4e89-8fc0-1b16a03cae34.png">

**Comment by yathindrakodithuwakku** [comment]
The `/api/server/v1/userstores/meta/types/<id>` API endpoint respond `DisplayNameAttribute` with `required: true`, even though it is optional. In this case, the required attribute should be fixed and description should be refactored.

<img width="897" alt="Screenshot 2022-08-08 at 12 46 24" src="https://user-images.githubusercontent.com/32919513/183367482-b8332478-2cfd-4c3e-9f81-7c782b79ab08.png">

**Comment by pavinduLakshan** [comment]
Fixed with https://github.com/wso2/product-is/issues/19010
