### ISSUE TITLE
additional info icon in SCIM new attribute add wizard if no scim attribute is available for mapping

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14575]
**Describe the issue:**
Login to console -> navigate to Manage -> Attributes -> SCIM 2.0
Under Core  Schema, try to add by clicking + New Attribute
![Screenshot - 2022-08-06T191552 374](https://user-images.githubusercontent.com/25483865/183252007-36b03cd9-24b2-4fb5-b5a5-3406eea6c2e9.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.0.0-SNAPSHOT

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3300
