### ISSUE TITLE
Unable to filter Newly added Roles - when add new WorkFlow

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#14579]
**Describe the issue:**
Create the user roles with the following permissions Under Primary user store. 
Login
Human Tasks > View Task List
Workflow Management > BPS Profiles >View

1. When searching for a newly added role filtering will not occur with the exact role name/role name pattern (* to all), (no role will be filtered under the primary/all user storage domain.)
2. Admin doesn't even filter when searching for any role under the "primary" domain

**How to reproduce:**
1. Create the user roles with the following permissions Under Primary user store. 
Login
Human Tasks > View Task List
Workflow Management > BPS Profiles >View
3. In the Main tab of the Management Console, click Manage > Workflow Definition > Add.
4. Enter a workflow name and description and click Next.
5. click Add Approval Step.
6. Select the "Primary" Domain drop-down
7.  select the Search Roles radio button.
8.
<img width="1079" alt="Screenshot 2022-08-06 at 20 01 54" src="https://user-images.githubusercontent.com/39120228/183253617-9db9b10e-695f-49dd-84b2-5570f9c984af.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-beta2-SNAPSHOT
 - OS: MAC v12.4 (21F79) Apple M1 Pro
 - Database: H2
 - User Store- JDBC embedded H2 db type
- Browser - Chrome Version 104.0.5112.79 (Official Build) (arm64)

---

**Comment by piraveena** [comment]
From IS 5.11.0 onwards, we support only groups in userstore with the group role separations. But workflows support roles only. Roles(Eg: Internal/role1, Internal/admin) are not userstore specific. So searching the roles based on userstore is  not required now. 


The flow works when you search accross all the userstore and the role has `/permission/admin/manage/humantask/viewtasks`
