### ISSUE TITLE
Resource deletion modal should be consistent  

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14572]
**Describe the issue:**
User deletion modal has RED color and other resource deletion has Yellow color in the modal.

User deletion modal:

![Screenshot from 2022-08-06 18-33-03](https://user-images.githubusercontent.com/25483865/183250525-eb44277c-be6c-44f4-85f5-5bed818eb5cf.png)

Application deletion modal:
![Screenshot from 2022-08-06 18-33-58](https://user-images.githubusercontent.com/25483865/183250519-f20f83ae-1ef4-43ff-b671-89dc6f334715.png)

Group deletion modal:

![Screenshot from 2022-08-06 18-31-40](https://user-images.githubusercontent.com/25483865/183250529-2c34b63b-21aa-47f0-b881-59a27d98dd84.png)

**Expected behavior:**
All resource deletion modals should be consistent.
IMO it should be aligned with  user deletion modal

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.0.0-beta2-SNAPSHOT

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3300
