### ISSUE TITLE
Deny Consents when login to a SAML app will end the user in a dead end page where that page doesnt have a going back 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14588]
**Describe the issue:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/lastSuccessfulBuild/artifact/org.wso2.is/wso2is/6.0.0-beta2-SNAPSHOT/wso2is-6.0.0-beta2-SNAPSHOT.zip
2. Set up travelocity as the SP
3. Set up Google as the IDP
4. Access http://localhost:8080/travelocity.com/home.jsp
5. Input Username
6. In the next windows click cancel to deny consents
7. YOu will navigate to a authentication error page

This error page is like a dead end for the user. Theres no Retry option or going back for the sample applcation
![a](https://user-images.githubusercontent.com/31848014/183278748-9e60f08d-b5fa-438e-bc66-3f4cf9934523.png)

https://user-images.githubusercontent.com/31848014/183278749-36e356cd-1d97-4e21-ad53-52126e17b5f2.mp4

**Env**
mssql 2019

**Comment by sadilchamishka** [comment]
Will work on the issue based on capacity

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
