### ISSUE TITLE
MultiAttribute Login Identifier not showing in tenant flow Login UI with Console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14580]
**Describe the issue:**
1. Get Pack https://drive.google.com/file/d/1h3ynCA_1kLKPovRahbDtrtGvFYxXkbvs/view
2. Create a tenant
3. Enable Multi Attribute login for claim mobile under tenant configs
4. Access https://localhost:9443/t/wso2.com/console

Login identifier is not changed for mobile in the login form

Flow works as expected under super tenant

![Screenshot from 2022-08-06 20-19-53](https://user-images.githubusercontent.com/31848014/183254208-e0044cd0-501f-4547-bbd5-1e4be87a373e.png)
![Screenshot from 2022-08-06 20-20-02](https://user-images.githubusercontent.com/31848014/183254211-dd1b7181-7c5e-4411-947b-d933faea639a.png)

**Env**
h2 default

**Comment by ShanikaWickramasinghe** [comment]
@VivekVinushanth while checking this flow check multi attribute login flow by including a set of claims as comma separated values inside the allowed attribute claim list config https://is.docs.wso2.com/en/latest/learn/multi-attribute-login/#:~:text=Configuring%20WSO2%20IS%20for%20Multi%20Attribute%20Login,-Start%20WSO2%20Identity&text=Click%20Main%20%3E%20Identity%20Providers%20%3E%20Resident,regular%20expression%20for%20allowed%20claims.

**Comment by VivekVinushanth** [comment]
Please note that, for business apps in tenant, the user identifier is properly appearing. But since the console/myaccount saas apps are unable to resolve the tenant  from the tenant qualified url (in default pack), and only the domain appended at the user-identifier resolves the tenant, this is justifiable. There should be an improvement though

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
