### ISSUE TITLE
In Traditional web application creation, make username as a requested attribute. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#14589]
**Describe the issue:**
<img width="964" alt="Screenshot 2022-08-07 at 12 14 27" src="https://user-images.githubusercontent.com/8455535/183278899-2afc4a17-27f5-467e-8045-d92c6066d782.png">
In Traditional web application creation make username as a requested attribute. However, that should be userID. Verify the other flows related to the attribute mapping. Ex. SPA, SAML, OIDC, etc

<>

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 6.0.0]
 - OS: [e.g.,  Mac]
 - Database: [e.g., H2]
 - Userstore: [e.g., DBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by VivekVinushanth** [comment]
Related
- https://github.com/wso2/product-is/issues/14561

**Comment by VivekVinushanth** [comment]
Refering https://github.com/wso2/product-is/issues/14561#issuecomment-1207186653

`curl 'https://localhost:9443/api/server/v1/claim-dialects/%7B%7D/claims' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Access-Control-Allow-Origin: https://localhost:9443' -H 'Authorization: Bearer e9cd4d04-c421-3263-8560-e6125eac430b' -H 'Connection: keep-alive' -H 'Cookie: menuPanel=visible; menuPanelType=main; JSESSIONID=F343628DB921B97F22061343B915695D; atbv=492eb4e9-5cf2-4adb-80df-77c81e4f853e; current-breadcrumb=; requestedURI=../../carbon/admin/index.jsp; MSG16596118471050.0706825729849534=true; MSG16596118624330.7537068765946476=true; MSG16596118785040.7749237820961196=true; MSG16596118985490.877019379946138=true; MSG16596119129010.7647916899344912=true; MSG16596119999430.8156992988530211=true; MSG16596138531730.29097706227261433=true; MSG16596138841350.6163266218630801=true; MSG16596143641490.7039235775637004=true; MSG16596144038730.07760969951706365=true; MSG16596180182980.4507268516291716=true; MSG16596180283850.9893186009847007=true; MSG16596635549020.612514011522885=true; commonAuthId=d88ad8d1-ce98-444d-84cb-d62bc5c24cda; opbs=e6d60d55-817c-4a9a-af96-019699ed52a5' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin'`

**Comment by VivekVinushanth** [comment]
Obtaining 400 for the call : GET | https://localhost:9443/api/server/v1/claim-dialects/%7B%7D/claims

**Comment by VivekVinushanth** [comment]
As @piraveena suggested, can anyone from @DonOmalVindula @pavinduLakshan @JayaShakthi97 own this?

**Comment by piraveena** [comment]
We need to make userId as the manadatory attribute

**Comment by brionmario** [comment]
> No need to explicitly request `userId` attribute in Application Temaplates wso2/identity-apps#3331

After further discussions, it was decided that there's no need to explicitly request `userId` since its the fallback. Hence, removed in this PR https://github.com/wso2/identity-apps/pull/3331
