### ISSUE TITLE
Password policy is not working 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14594]
**Describe the issue:**
Configured password policy not applied.
![Screenshot 2022-08-07 at 15 05 29](https://user-images.githubusercontent.com/39077751/183285315-76f53220-ceb7-4ea4-a7ba-396f77b01260.png)

![Screenshot 2022-08-07 at 15 07 54](https://user-images.githubusercontent.com/39077751/183285319-abd6d819-01cc-459f-a867-ffd137c40a9f.png)

**How to reproduce:**
1.  Login to management console
2. Configure password policy. https://is.docs.wso2.com/en/latest/learn/password-patterns/
3. Create user and verify the policy is applied.

**Expected behavior:**
Password policy should be apply 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by IsuraD** [comment]
This happens due to user-store level password policy is enforced. 

```
<Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>

<Property name="PasswordJavaScriptRegEx">^[\S]{5,30}$</Property>
```

Both the user store + tenant level policies are applied.
