### ISSUE TITLE
Remove searching roles based on userstores in workflow approval template

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#14596]
**Describe the issue:**
With the group role separation, the roles are used accross the system. Only the groups are userstore specific.  Searching the roles based on userstore is not required when adding a new in workflow approval template
<img width="900" alt="Screenshot 2022-08-07 at 17 13 16" src="https://user-images.githubusercontent.com/17597293/183289388-61252b8a-79f9-45aa-a513-13c291a059dc.png">

**How to reproduce:**
1. In the Main tab of the Management Console, click Manage > Workflow Definition > Add.
2. Enter a workflow name and description and click Next.
3. click Add Approval Step.
4. Select the "Primary" Domain drop-down
5. select the Search Roles radio button.
None of the roles will be retrieved while searching based on userstores

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
