### ISSUE TITLE
Magic link is not working in Safari browser

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14600]
**Describe the issue:**
Magic link is not working in Safari browser.

https://user-images.githubusercontent.com/39077751/183301959-95b9dd10-4538-4555-b9e2-9befce96eacf.mov

**How to reproduce:**
1. Create application and  configure magic link
2. Authenticate with magic link

**Expected behavior:**
Authentication should be successful.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by IsuraD** [comment]
Tested magicLink on safari and it works as expected. If there is an issue, that should be in the sample side tested. Tested in both super tenant and tenented environments.

**Comment by IsuraD** [comment]
@aaujayasena please check and close the issue.

**Comment by piraveena** [comment]
@SujanSanjula96 please test this with Mac M1

**Comment by SujanSanjula96** [comment]
Tested this with Mac M1. Magic link works as expected in normal window. But it is not working in private window because browsing initiated in one tab 0f a private window is isolated from browsing initiated in another tab.

https://support.apple.com/en-lk/guide/safari/ibrw1069/mac

**Comment by SujanSanjula96** [comment]
Closing this issue since it is the expected behaviour in private windows for safari browser.

**Comment by aaujayasena** [comment]
@SujanSanjula96  Shall we update the reason for accept this on Safari private windows

**Comment by SujanSanjula96** [comment]
@aaujayasena  Mentioned the reason in https://github.com/wso2/product-is/issues/14600#issuecomment-1207705717

**Comment by aaujayasena** [comment]
Shall we create a doc issue https://github.com/wso2/product-is/issues/14600#issuecomment-1207705717 @SujanSanjula96

**Comment by aaujayasena** [comment]
Doc issue created https://github.com/wso2/product-is/issues/14644
