### ISSUE TITLE
Enabled/Disabled toggle button's text in Add JDBC User Store wizard is changed when toggling read-only button

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14604]
**Describe the issue:**

- Login to react based console
- Go to Manage->Userstores
- Click on + New userstore and select JDBC 
- Change the Read-Only toggle button multiple times. 
- It will change the text if Enabled/Disabled toggle button

https://user-images.githubusercontent.com/25483865/183304072-eafa7290-1caf-4903-bf52-39d59b199fba.mp4

**Expected behavior:**
Changing  Read-Only toggle button should not affect to the enable/ disable toggle button text

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.0.0-beta2-SNAPSHOT

**Comment by JayaShakthi97** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/3311
