### ISSUE TITLE
Something went wrong in console attribute  

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14603]
**Describe the issue:**
Something went wrong in console attribute.

https://user-images.githubusercontent.com/39077751/183303378-eadf340c-e62b-48f0-b434-7cff2ba922c1.mov

**How to reproduce:**
1. Login to console and create application
2. Navigate to application edit -> Attribute

**Expected behavior:**
No erros

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Duplicate of https://github.com/wso2/product-is/issues/14561. Hence closing
