### ISSUE TITLE
Something went wrong error when navigate to User Attributes section of an application

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14605]
**Describe the issue:**

1. Log into Console
2. Go to Develop -> Applciations.
3. Go inside Myaccount / console / create a new app and go inside it to application edit page
4. Click on User Attributes tab 
`https://localhost:9443/api/server/v1/claim-dialects/%7B%7D/claims` API returns 400 and UI shows something went wrong error message 

https://user-images.githubusercontent.com/25483865/183304579-2115b7dc-a38c-4697-90bc-ff230b8c2610.mp4

HAR file:
[app-attributes-view.zip](https://github.com/wso2/product-is/files/9277245/app-attributes-view.zip)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-6.0.0-beta2-SNAPSHOT

**Comment by VivekVinushanth** [comment]
Duplicate issue: https://github.com/wso2/product-is/issues/14561
