### ISSUE TITLE
Getting Registered Callback does not match error when try to access Console and Myaccount with Port offset against MSSQL

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14602]
**Describe the issue:**
1. Get the Pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/lastSuccessfulBuild/artifact/org.wso2.is/wso2is/6.0.0-beta2-SNAPSHOT/wso2is-6.0.0-beta2-SNAPSHOT.zip
2. Set the port offset of the pack to offset = "1"
3. Point mssql 2019 as the database
4. Up the pack
5. Try to access console

```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offset = "1"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:sqlserver://localhost:1433;databaseName=aug7;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.identity_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
url = "jdbc:sqlserver://localhost:1433;databaseName=aug7;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.shared_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[bps_database.config]
url = "jdbc:sqlserver://localhost:1433;databaseName=aug7;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"

```
Getting error as registered callback does not macth. But in default H2 pack if you offset the port and try to access console or myaccount then that works fine. Against MSSQL 2019 its giving below error

![Screenshot from 2022-08-07 22-53-20](https://user-images.githubusercontent.com/31848014/183303220-c290a5f2-0413-4567-aec5-934ab55f70d4.png)

**Comment by piraveena** [comment]
If you started the pack with 0 offset earlier, then you need to manually change the callback URLs to support port offset 2.

``` 
[system_applications]
read_only_apps = []
```
It should be available in the docs
