### ISSUE TITLE
Navigating to Groups section in the Console Loads the browser 2 times

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14616]
**Describe the issue:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/lastSuccessfulBuild/artifact/org.wso2.is/wso2is/6.0.0-beta2-SNAPSHOT/wso2is-6.0.0-beta2-SNAPSHOT.zip
2. Login to console as admin
3. Navigate to manage > groups section

Observe the browser loading tab. When navigating to groups section it will load for 2 times in the browser. 

https://user-images.githubusercontent.com/31848014/183346171-74e3b808-8ccd-4b35-8133-2105c528ac0e.mp4

Google Chrome 99.0.4844.82
Firefox 103.0

**Comment by DimalChandrasiri** [comment]
The loader which comes on top of the UI is due to API calls which will trigger the loader each time an API request is made. Since the groups view require loading userstores, the second loader is triggered. Hence this is expected.
