### ISSUE TITLE
Checkbox included for titles too in Group Creation windows

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14619]
**Describe the issue:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/lastSuccessfulBuild/artifact/org.wso2.is/wso2is/6.0.0-beta2-SNAPSHOT/wso2is-6.0.0-beta2-SNAPSHOT.zip
2. Access console > manage > groups
3. Try to create a group

In group creation windows check below windows, a checkbox is visible for the titles row as well
![a](https://user-images.githubusercontent.com/31848014/183352756-66f1138c-ce49-4331-a6b4-7516dc693b51.png)

**Comment by brionmario** [comment]
I think this is the `Select All` option. Better to represent it In a different way :)

**Comment by DimalChandrasiri** [comment]
The checkboxes indicate the select all functionality as @brionmario mentioned. We need to revisit the overall UX on denoting this functionality, hence could take multiple iterations to finalise a proper design. Since this doesn't break the user flow, will look into a possible improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
