### ISSUE TITLE
Fix claim endpoint urls to support sub-organization context

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#14612]
**Describe the issue:**
Since we have to revert the PR, https://github.com/wso2/identity-apps/pull/3291, since it has introduced a regression (refer [1],[2],[3]). We need to get the original issue fixed that we were planning to solve with the PR [#3291](https://github.com/wso2/identity-apps/pull/3291)

[1] https://github.com/wso2/product-is/issues/14561
[2] https://github.com/wso2/product-is/issues/14603
[3] https://github.com/wso2/product-is/issues/14605

FYI: @kavinda1995 @piraveena @IsuraD @madurangasiriwardena

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3339
