### ISSUE TITLE
Federated User + MFA is not working without Just-in-Time Provisioning

### ISSUE THREAD

**Issue by sumonwai-nextdc** [wso2/product-is#14614]
**Authentication failed exception! Authentication failed!. Cannot get the username from first step. if MFA is enabled for Federated Users without Just-in-Time Provisioning**

**How to reproduce:**
Enable Just-in-Time Provisioning in Identity Provider.
Enable Step 1) AD Identity Provider, Step 2) TOTP

It works and I can login with AD + MFA.

Then disable Just-in-Time Provisioning in Identity Provider

**Expected behavior:**
It should continue to work as User existed and already configured with TOTP.

**Actual behavior:**
Login failed with error in log
`
[2022-08-08 00:08:02,604] [8e211eab-4c9f-45a2-a114-69fbb1f009c8] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication failed!. Cannot get the username from first step.
`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-beta
 - OS: Linux
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/11988

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
