### ISSUE TITLE
Organization login IDP tag is shown when creating IDP when organization-managment feature is disabled

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#14613]
**Describe the issue:**
The tags in the IDP creation view help to filter default packed IDP templates. Though organization management is disabled, the organization login tag is shown. 

![Screenshot 2022-08-08 at 10 16 29](https://user-images.githubusercontent.com/35717390/183341628-161d0427-2c2c-4aef-8c43-9a428e89f324.png)

**How to reproduce:**
Log in to console and try to create IDP

**Expected behavior:**
The organization login tag should not be there.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.0.0-beta2]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [H2]

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3364
