### ISSUE TITLE
Unrequired Check box displayed in management console in user operations

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14615]
**Describe the issue:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/lastSuccessfulBuild/artifact/org.wso2.is/wso2is/6.0.0-beta2-SNAPSHOT/wso2is-6.0.0-beta2-SNAPSHOT.zip
2. Login to management console as admin
3. Create a User
4. In the success alert box theres a unrequired check box showing. Noticed this checkbox in lot of operations in management console

![a](https://user-images.githubusercontent.com/31848014/183344027-78fcb22a-f82f-4dba-a07b-64c1711e174a.png)

**Comment by melanisilva** [comment]
Closing this as this is fixed in the latest release.
