### ISSUE TITLE
Magic link docs does not mention about not supporting private windows of Safari browser

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#14621]
**Is your suggestion related to a missing or misleading document? Please describe.**
This is related to magic link authenticator is not supported in private windows of Safari browser.

**Describe the improvement**
Adding a note to magic link docs

**Comment by nilminiwso2** [comment]
Fixed by https://github.com/wso2/docs-is/pull/3235/files
Further improvement on the messaging (using the same tab instead of private windows) will be handled by https://github.com/wso2/product-is/issues/14644
