### ISSUE TITLE
[DOC] Documentation on how to `Trying out saml app with WSO2 Identity Server in a tenant`

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#14620]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently we don't have the information about how to trying out a saml app with a tenant in IS official documentations.[1]

**Describe the improvement**
There are some additional configurations we need to follow when trying out saml app with a tenant.
We can found out the steps from this blog. [2]
Need to document these steps in IS official documentations.

Ref:
[1] https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp
[2] https://piraveenaparalogarajah.medium.com/trying-out-saml2-pick-up-dispatch-app-with-wso2-identity-server-in-a-tenant-20626ac4865a

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
