### ISSUE TITLE
[IS 6.0.0] Naming of adaptive.sh

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#14626]
In https://is.docs.wso2.com/en/6.0.0/guides/adaptive-auth/configure-adaptive-auth/

it says, 

`For JDK 17 runtime - Adaptive Authentication is disabled by default. You need to run adaptive.sh (adaptive.bat for Windows) in [IS-HOME]/bin
`
commands need to be a verb or an action. rare case it can be a noun. "adaptive" is an adjective that does not qualify for any of the above.

Since we can perform 2 actions with the script (enable and disable), we can go with a noun eg: support-adaptive.sh

Action Items:

- [ ] Need to have wider audience consent
- [ ] Change the file name in the Product IS repository

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
