### ISSUE TITLE
Inbound Authentication Configuration of System apps can be editable even if they are read_only_apps

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14634]
**Describe the issue:**

1. Get the WSO2 is pack
2. start the server and login to the management console 
3. Go to Service Providers -> MyAccount ->Inbound Authentication Configuration -> OAuth/OpenID Connect Configuration -> Click on Edit
4. Do some modifications and click on the update button. Application update will be successful 
5. When you click on the Update button of the SP, that will give the error saying the system app can't be updated. but when you recheck the value has been updated

https://user-images.githubusercontent.com/25483865/183456597-2ba8024c-47a3-4dec-ba3a-0ec182edbdb5.mp4

**Expected behavior:**
System app configs can be updated only if is removed from read-only system app list 
```
[system_applications]
read_only_apps = []
```
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.0.0-beta2-SNAPSHOT

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
