### ISSUE TITLE
Add information related to Account Lock Handler disable property

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#14636]
**Is your suggestion related to a missing or misleading document? Please describe.**
Add docs related to https://github.com/wso2/carbon-identity-framework/pull/4208

**Describe the improvement**
* This config is used to disable the Account Lock Handler.
* By default this is not enabled or added.
* This should be only added when a performance enhancement is required and not using any feature related to account lock.
* Can be added using depoyment.toml
```
[authentication_policy]
disable_account_lock_handler = true
```

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
