### ISSUE TITLE
Configure email sending configurations in 2-Factor authentication with Email OTP

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14639]
When configuring the 2-Factor authentication with Email OTP, we can set either wso2 IS or Gmail as the email OTP provider. The 
email sending configurations should be set for both the email OTP provider options. But in the documentation, only in the wso2 IS as email OTP provider section has the email sending configuration link.

Step 1 in Option 1 should be added as the 1st step of the option 2 as well.

![Untitled Diagram drawio](https://user-images.githubusercontent.com/47152272/183482590-46cd0514-be8e-47d5-9250-a8a1ae837c83.png)

<img width="1512" alt="Screenshot 2022-08-08 at 23 28 07" src="https://user-images.githubusercontent.com/47152272/183483240-9392d1c8-1d96-4b22-a282-f43f30cdcfab.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
