### ISSUE TITLE
Couldn't view the role's permission when assigning a role to a newly created user in the sub-organization

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14649]
**Describe the issue:**
Please refer to the screencast.

https://user-images.githubusercontent.com/13362482/183576266-c84e5721-072f-4100-b2f1-cdbfdcdb1687.mov

**How to reproduce:**
- Enable org-mgt feature 
- Login to console and create different sub organizations
- switch to created new sub organization
- Create a new role
- Try the user creation and try to a view the permission of the role when assign the role while creating the user.

**Expected behavior:**
User should be able to view the permissions

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-beta2-SNAPSHOT
 - OS: Mac
 - Database: MSSQL 2019
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
@Kanapriya  @brionmario we've (temporary) removed roles section in both **Add User Flow** and **Edit User Flow** in sub-organization management context due to these reasons.
1. Organization Management doesn't support SCIM endpoints for Organization user management (https://github.com/wso2/product-is/issues/14267)
2. We don't have an ability to assign a **role** to a **user**, we only can assign **user** to a **role** ATM.

**Comment by brionmario** [comment]
> @Kanapriya  @brionmario we've (temporary) removed roles section in both **Add User Flow** and **Edit User Flow** in sub-organization management context due to these reasons.
> 
> 1. Organization Management doesn't support SCIM endpoints for Organization user management (https://github.com/wso2/product-is/issues/14267)
> 
> 2. We don't have an ability to assign a **role** to a **user**, we only can assign **user** to a **role** ATM.
> 
> 
> 
> In the recent development, we've removed the role assignment in the user creation flow too

Got it. I'll remove my assignment.

**Comment by dewniMW** [comment]
As mentioned above the role assignment in the user creation flow has been removed. hence closing this issue
