### ISSUE TITLE
Get super tenant domain and tenant prefix from the respective Java util methods in the My Account and Console app

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#14658]
Currently, the tenant prefix and super tenant domain are hardcoded in the `index.jsp` file. However, these values should be obtained from Java util methods. 

Relevant concern: https://github.com/wso2/identity-apps/pull/3319#discussion_r941016451
Tenant prefix: https://github.com/wso2/identity-apps/blob/ee0d9422e0ed80b21d847484995bcc2da5d24c7d/apps/console/webpack.config.js#L524
Super tenant domain: https://github.com/wso2/identity-apps/blob/ee0d9422e0ed80b21d847484995bcc2da5d24c7d/apps/console/webpack.config.js#L517

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
