### ISSUE TITLE
Tenant flow deleting a imported certification confirmation window having term "Organization"

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14650]
**Describe the issue:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-6.0.0.zip
2. Create a tenant
3. Login as tenant for the console
4. Go to Manage > certificates section and import a new certificate
5. Try to delete the imported certificate

When deleting the certificate it has the term "organization" in the confirmation box, dont we need to change it as tenant
![Screenshot from 2022-08-09 11-48-36](https://user-images.githubusercontent.com/31848014/183578753-92690ee2-63f3-4157-9fcf-902402548c2c.png)

**Comment by kavinda1995** [comment]
Fixed in https://github.com/wso2/identity-apps/pull/3328
