### ISSUE TITLE
How to perform entitlement operations via API method on identity server. 

### ISSUE THREAD

**Issue by Ajaysamdyan** [wso2/product-is#14651]
**Environment information** 
 - Product Version: [IS 5.7.0, AM 2.6.0]
 - OS: [Linux]
 - Database: [MySQL]
 - Userstore: [OpenLdap 2.4.4]

**Description:**
Hi All
Im using WSO2 IS 5.7.0 + WSO2 AM 2.6.0 with OpenLDAP 2.4.4 and MySQL.
I want to perform the some entitlement operation via API method on identity server. Will anybody help me to guide, how to perform the below operation via  "API" method if possible.
Operations:
1. How to create one Rule definition.
2. How to create one Policy definition.
3. How to create one Policy Set definition.
4. How to include Rule and Role to Policy.
5. How to include Policy and Policy Set to Policy Set.
Thanks in advance.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
