### ISSUE TITLE
Issue with naming in Configure ACR-based adaptive authentication flow

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#14659]
**Is your suggestion related to a missing or misleading document? Please describe.**
In [Configure ACR-based adaptive authentication](https://is.docs.wso2.com/en/6.0.0/guides/adaptive-auth/acr-based-adaptive-auth/#configure-acr-based-adaptive-authentication) use the playground2 app but in [Configure acr-based authentication section ](https://is.docs.wso2.com/en/6.0.0/guides/adaptive-auth/acr-based-adaptive-auth/#configure-acr-based-authentication)it changes to saml2-web-app-pickup-dispatch.com instead of playground2.

**Describe the improvement**
Use playground2 as the app name throughout the document flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
