### ISSUE TITLE
Console & My Account breaks on Safari when `Web Worker` is used as the storage strategy in the `@asgardeo/auth-react` SDK

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#14652]
**Describe the issue:**

When `webWorker` is used as the [storage strategy](https://github.com/asgardeo/asgardeo-auth-react-sdk#authreactconfig) in `@asgardeo/auth-react` SDK, the apps break with a stack exceeding error in Safari (v15.3 latest at the time of issue creation).

**How to reproduce:**
1. Revert https://github.com/wso2/identity-apps/pull/3322.
2. Run My Accont and Console in the local development mode. (https://github.com/wso2/identity-apps#run-in-dev-mode)
3. Experience the following behaviour.

**Expected behavior:**

The apps should work as normal.

**Related Issue**
- https://github.com/wso2/product-is/issues/14574

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0-BETA2
 - OS: Mac
 - Browser: Safaro 15.3
 - Database: H2
 - Userstore: LDAP

**Comment by brionmario** [comment]
A temporary fix was added to overcome the `Safari` issue by switching the storage mechanism to `sessionStorage` for Safari users.

- Temp Fix: https://github.com/wso2/product-is/issues/14574

**Comment by brionmario** [comment]
Added a temp workaround in https://github.com/wso2/identity-apps/pull/3322

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
