### ISSUE TITLE
User Self Registration Create Account is not visible via myaccount eventhouh self registration enabled for a tenant

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14663]
**Describe the issue:**
1. Get pack https://wso2.org/jenkins/view/products/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-6.0.0.zip
2. Create a tenant
3. Login as tenant and enable self registration for tennat
4. Access my account as https://localhost:9443/myaccount or https://localhost:9443/t/wso2.com/myaccount
5. Create button option is not visible to self register from myaccount
6. If we setup a sample application and try then self register button is visible via sample

https://user-images.githubusercontent.com/31848014/183614373-3290ca3b-73d7-480b-bea5-80aa00888612.mp4

![Screenshot from 2022-08-09 15-03-38](https://user-images.githubusercontent.com/31848014/183616078-9797a109-0e3a-4f07-870f-b40cb3bbd577.png)
![Screenshot from 2022-08-09 15-03-42](https://user-images.githubusercontent.com/31848014/183616105-43928567-1ca0-4fce-a5c4-48d1ed275fb0.png)

**Comment by ShanikaWickramasinghe** [comment]
As discussed with isura this is because myaccount app is a SAAS app. This will work for sample apps but when it comes for myaccount we need to enable self reg in super tenant too to get it worked with tenant flow

**Comment by piraveena** [comment]
This will work for sample apps in tenant flow.  but when it comes for myaccount we need to enable self reg in super tenant since the MyAccount is in super tenant.
