### ISSUE TITLE
Organization management configuration script fails with spaces in path

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#14661]
**Description:**
When there is a space in the IS_HOME path, it will lead to `configure.sh` failure. 
<pre>
Connector home is: /Users/avarjana/Documents/Work/WSO2IS/wso2is-6.0.0 2/wso2-org-mgt-connector-1.0.0-SNAPSHOT
Product home is: /Users/avarjana/Documents/Work/WSO2IS/wso2is-6.0.0 2

Valid carbon product path.

./configure.sh: line 42: ${WSO2_IS_HOME}/repository/conf/deployment.toml: ambiguous redirect
egrep: /Users/avarjana/Documents/Work/WSO2IS/wso2is-6.0.0: Is a directory
egrep: 2/repository/conf/identity/oauth-scope-bindings.xml: No such file or directory
sed: 2/wso2-org-mgt-connector-1.0.0-SNAPSHOT/conf/oauth-scope-bindings.xml: No such file or directory
mv: 2/repository/conf/identity/oauth-scope-bindings.xml is not a directory
================================================

Complete!
</pre>

**How to reproduce:**
- Get a fresh IS 6.0.0-rc1 pack and extract into a path with a space in it.
- Download the zip file “wso2-org-mgt-connector-1.0.0.zip” [here](https://drive.google.com/drive/folders/1O9ihpDu3ptaTPCJa0aMfY6ImA1O6AE2u?usp=sharing).
- Extract into the IS_HOME.
- cd into “wso2-org-mgt-connector-1.0.0/bin”.
- Run “merge.sh” and “configure.sh”.

**Expected behavior:**
- Execute both scripts successfully.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS6.0.0-rc1
 - OS: MacOS

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
