### ISSUE TITLE
Add new user / view user in sub-organization is not working as expected

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14662]
**Describe the issue:**
Please refer to this screencast:

https://user-images.githubusercontent.com/13362482/183611843-1b8a2d8e-eb11-416e-ad18-a8778cfb7766.mov

**How to reproduce:**
- Configure org-mgt feature in IS 6.0.0-RC1 pack (https://github.com/wso2/product-is/releases/tag/v6.0.0-rc1)
- Login to console and create sub-organization
- Switch to the sub-organization and try to add a new user/view the existing user
- You could see the blank page once you create new user or while viewing the existing user

**Expected behavior:**
Flow should be working properly without breaking in the middle.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-rc1
 - OS: Mac
 - Database: H2 and MSSQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
fixed with https://github.com/wso2/identity-apps/pull/3318

**Comment by Kanapriya** [comment]
This is fixed with the latest wso2is-6.0.0-rc2-snapshot pack. Hence closing this issue.
