### ISSUE TITLE
Misleading left menu name

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#14668]
**Is your suggestion related to a missing or misleading document? Please describe.**

Refer: https://is.docs.wso2.com/en/6.0.0/deploy/deployment-guide/

![image](https://user-images.githubusercontent.com/5237653/183632391-7d7fa5f1-8f1d-458b-9eff-bbd35cc9778f.png)

Actually the content is about deployment steps but the title suggests its about patterns.

**Describe the improvement**

Would be good to name it to a better title

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by mefarazath** [comment]
More over the document should have an easy follow flow. Currently in 6.0.0 the docs seems very scattered

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
