### ISSUE TITLE
Issue when adding concurrent-Session-Management template 

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#14665]
**Describe the issue:**
When you try to configure Concurrent-session-based adaptive authentication and try to add a already available template you get the following error message.

<img width="1204" alt="Screenshot 2022-08-09 at 14 48 36" src="https://user-images.githubusercontent.com/38417165/183613189-0001e803-866f-4a7a-a422-1cac1186e9a3.png">

**How to reproduce:**
Follow the steps in this [documentation](https://is.docs.wso2.com/en/6.0.0/guides/adaptive-auth/limiting-active-sessions-adaptive-auth/) and add a  concurrent-Session-Management template  and click update.

**Expected behavior:**
Add the authentication step similar to other templates to avoid the error message. We can manually add the authentication step to avoid the error but similar to other templates we can add the authentication step.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 RC1
 - OS: Mac
 - Database: MsSQL

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
