### ISSUE TITLE
Error when view the organisation list once logged-in to the sub- organisation with tenanted path

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14677]
**Describe the issue:**
Please refer to this screencast

https://user-images.githubusercontent.com/13362482/183658040-19361750-dd0d-412d-bc68-09436fce547d.mov

**How to reproduce:**
- Enable the organization management feature in IS 6.0.0 RC pack.
- Login to console as an admin user
- Create a sub-organization and switch into  created sub-organization
- Create a user and create a new role with all permissions
- Assign the created user to that role
- Login to console with tenanted path https://localhost:9443/o/{org-id}/console
- You could see the capability of switching between organizations (root and sub-organizations)
- Try to switch to the root organization and try to view the organizations' list.

**Expected behavior:**
Since the logged-in user is not besides in root organization, we should not list down the super organization in the list to switch between the root organization

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.0.0-rc2-snapshot
 - OS:  Mac
 - Database: H2, MSSQL 2019
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
BE changes related to this have already been completed - https://github.com/wso2/product-is/issues/14480

@thivi @kavinda1995 FYI
