### ISSUE TITLE
Remove the need to use tenant qualified username for self registration email resend and pwd reset with security questions

### ISSUE THREAD

**Issue by ThumulaPerera** [wso2/product-is#14675]
**Is your suggestion related to an experience ? Please describe.**

Currently, when a non SaaS application is configured under a tenant, most of its authentication related flows work properly with username without tenant qualifier (as the tenant domain is derived). However, the following 2 flows do not work with username without tenant qualifier. 
1. Resend email for self registered user
2. Password reset with security question

**Steps to try out current behaviour**

1. Configure email sending https://is.docs.wso2.com/en/latest/setup/configuring-email-sending/#! 
2. Create a tenant 
3. Configure an SP under that tenant https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-pickup-dispatch-webapp
4. Configure Resident Identity provider under that tenant as follows
    i.   Expand User Onboarding -> Self registration and enable
               - User self registration
               - Enable Account Confirmation On Creation
               - Send sign up confirmation email
  ii.  Expand Account Management -> Account Recovery and enable
               - Notification based password recovery
               - Security question based password recovery

5. Try out Resend email for self registered user6. 
- Navigate to the login page of the sample app (eg: http://localhost.com:8080/pickup-dispatch/home.jsp) and click login
- Click Create Account. And follow the self registration process. Use a valid accessible email.
- Login to the email and verify that WSO2 - Account Confirmation email is received. Do not click the verification button.
- Go back to the login page of the sample app (eg: http://localhost.com:8080/pickup-dispatch/home.jsp). Try to login with the newly created user (use username without tenant qualifier) . Account is unverified error message will be shown.
- Click Resend
- Error message with the text `Email sent fail.` will be displayed
- Retry login with the newly created user (use tenant qualified username. i.e. <user>@<tenant_domain>)
- Click Resend
- Success message will be displayed and email will be sent correctly

6. Try out Password reset with security question7. 
- Create a user in the tenant
- Update the security questions for that user by logging into my account
- Navigate to the login page of the sample app (eg: http://localhost.com:8080/pickup-dispatch/home.jsp) and click login
- Click `forgot password`
- use username without tenant qualifier and select `Recover with Security Questions` and submit
- Error message `Error! Security questions based recovery is not enabled` will be displayed
- Retry with tenant qualified username. i.e. <user>@<tenant_domain>.
- Security questions will be prompted as expected
 
**Describe the improvement**

The 2 flows mentioned above should also work without the tenant qualifier in the username

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
