### ISSUE TITLE
Creating a user from console under a primary or secondory US navigates to the admin users edit page after click Finish and undefined in URL

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14679]
**Describe the issue:**
1. Get Pack https://drive.google.com/file/d/1N2ymB2zv0cKlZ6j9ZMY5tHR61H3qlvyR/view?usp=sharing
2. Register a secondory Userstore (mysql)
3. Create a workflow for user add operation in the system  >> (mandotory)
4. Create a user under primary or secondory Userstore
5. After click Finish button in user creation from console it navigates for the edit page of the admin user and not for the created users edit page
![Screenshot from 2022-08-09 19-21-56](https://user-images.githubusercontent.com/31848014/183667579-4eb2d71d-e886-496b-b4b3-678107f45001.png)

Browser URL shows as undefined

https://user-images.githubusercontent.com/31848014/183667635-a4e5be3e-f96b-4a2e-a808-c0d321f8dacc.mp4

**Comment by NilukaSripalim** [comment]
Got the same behavior,

when there is WorkFlows Engagements with Operation name = Add user 
<img width="1435" alt="Screenshot 2022-08-09 at 20 48 05" src="https://user-images.githubusercontent.com/39120228/183689125-fd4688f4-26cb-4456-9817-60792864a8dc.png">

Then, after creating a new user (console) it will navigate to the Console Admin profile

**Comment by brionmario** [comment]
ATM, from inside the Console, there's no way to figure out if a workflow is engaged. 
cc:/ @AnuradhaSK

**Comment by Yoshani** [comment]
Fixed with: https://github.com/wso2/identity-apps/pull/3927
