### ISSUE TITLE
Email OTP and TOTP as the first authentication step in MFA

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14672]
**Describe the issue:**

When configuring the email OTP or TOTP as the first step of the MFA flow, the following error will appear.

`[2022-08-09 17:29:44,662] [c6e227d4-7fe9-4aa4-90ae-2dd7f5dd9049] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Can not find the authenticated user`

![Screenshot 2022-08-09 at 17 51 57](https://user-images.githubusercontent.com/47152272/183645689-e2d6ae03-e057-4627-b135-4776d6ba51ce.png)

**How to reproduce:**
1. Configure and OIDC sample app using management console.
2. Configure MFA using one or more steps and add email otp and totp as authetication options for the first step
3. Log into the sample app
4. Select Email OTP as the authetication method.
5. Login error pops as displayed in the above image

**Expected behavior:**
Email OTP and TOTP should not be able to allow to use as the first step of MFA

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 RC1
 - OS: macOS 12.5
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Yoshani** [comment]
Same issue exists for SMS OTP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
