### ISSUE TITLE
Application sharing failed when an application available in sub-organisation

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14684]
**Describe the issue:**
Consider the following scenario:
- Enable the organization management feature in IS 6.0.0 RC pack.
- Login to console as an admin user
- Create a sub-organization (E.g Star) and switch into created sub-organization.
- Create a child organization inside 'Star' organization
- Create a user and create a new role with all permissions
- Assign the created user to that role
- Login to console with tenanted path https://localhost:9443/o/{Star-org-id}/console
- Create an application in the organization (E.g Star)
- Again login to console  (https://localhost:9443/console) as an admin user
- Switch to the 'Star' organization
- And admin user could see the created application and can view the application
- When you view the application, you could see the 'Share Application' option
- Click on 'Share Application' and you could see the following error:
 
<img width="1440" alt="Screenshot 2022-08-09 at 9 43 42 PM" src="https://user-images.githubusercontent.com/13362482/183704073-b7bb2ab1-512a-444d-a9a3-3aa9f5cdf081.png">

https://user-images.githubusercontent.com/13362482/183704128-a4ab0247-5dab-4e71-a1ea-b9441103d345.mov

**How to reproduce:**

**Expected behavior:**
'Share Application' option should be disabled in this case.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
This was fixed in https://github.com/wso2/identity-apps/pull/3349
