### ISSUE TITLE
Minor issues in 6.0.0 SAML Applications docs

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#14681]
**Is your suggestion related to a missing or misleading document? Please describe.**

- [ ] In the [Configure CORS section in the SAML Applications doc](https://is.docs.wso2.com/en/6.0.0/guides/login/sso-for-saml/#configure-cors) toml configuration is not correctly formatted
- [ ] Signature validation is failing when using the linked sample webapps [saml2-web-app-pickup-manager.com.war](https://github.com/wso2/samples-is/releases/download/v4.3.0/saml2-web-app-pickup-manager.com.war) 
[saml2-web-app-pickup-dispatch.com.war](https://github.com/wso2/samples-is/releases/download/v4.3.0/saml2-web-app-pickup-dispatch.com.war) with IS 6.0.0. Need to update the certificates in the sample applications and link the fixed version of sample applications in docs.
- [ ] Mentioned sample application access URLs are inconsistent in the same doc. 
    - [ ] Ex: In the _Try-it_ section access url is mentioned as_http://wso2is.local:8080/saml2-web-app-pickup-dispatch.com_. But the assertion consumer urls for each application in _Register the service providers section_ contains the localhost:8080 URLs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
