### ISSUE TITLE
Console app  does not display device_code grant type 

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#14680]
**Describe the issue:**
he console can be used to view service providers and update the necessary configurations. The protocol section of the service provider only shows limited grant types for service provider applications. device_code grant type is not under allowed grant types (where as management console does list that)
![Screenshot from 2022-08-09 19-31-00](https://user-images.githubusercontent.com/32198547/183668920-5faf6f25-e469-45e3-bbc0-369b85eea56b.png)

**How to reproduce:**
Log into console app
Go to applications and select Console app.
View protocol section of the service provider app.

**Expected behavior:**
device_code should be listed under allowed grant_types

**Comment by VivekVinushanth** [comment]
Additionally, may be we should have a template for device flow or that kind of apps. @brionmario
FYI: @mefarazath

**Comment by kavinda1995** [comment]
Done the required Console App changes in https://github.com/wso2/identity-apps/pull/3327
