### ISSUE TITLE
Enabling multi-tenancy for account recovery endpoint is done by a .j2 file

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#14688]
As mentioned in the [6.0.0 docs](https://github.com/wso2/docs-is/blob/5b39dca2b7d09e0aaf92c4cddbef4eb3b518c31e/en/docs/guides/password-mgt/recaptcha-password-recovery.md), it needs to change `web.xml.` file in order to enable multi-tenancy for account recovery and password recovery. In the recent releases this file is edited by the template file `<IS_HOME>/repository/resources/conf/templates/repository/deployment/server/webapps/accountrecoveryendpoint/WEB-INF/web.xml` .

However it is not recommended to allow users to configure .j2 files and this configuration should be added to .toml file

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
