### ISSUE TITLE
Confusing configurations in the self registration configs

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#14694]
###  Issue
When we access the carbon console self-registration configuration following config options can be seen.
![Screenshot 2022-08-10 at 14 30 24](https://user-images.githubusercontent.com/39567992/183861378-fb2aea24-352e-4321-b819-141c43f3d4aa.png)

The above configurations are very confusing. Therefore it needs to be improved. Similar configs can be seen in the new developer console as well.
![Screenshot 2022-08-10 at 14 31 51](https://user-images.githubusercontent.com/39567992/183862172-62b5219f-c8e1-4b88-86a3-366de54f2a66.png)
![Screenshot 2022-08-10 at 14 32 00](https://user-images.githubusercontent.com/39567992/183862192-68b5336e-8ac4-4e74-88f7-f46c8d9fbc65.png)

###**Improvement**
- The configurations need to say which one has priority over the others. For example  if the `Send sign up confirmation email` is enabled, does it send the emails if the accounts are not locked on creation. Also, the descriptions and the config name need to be self-explanatory.
- Group the configurations that are similar in meaning. The overall experience seems to be very troubling since we have to scroll down to see more additional configs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
