### ISSUE TITLE
Implementing starts-with and and contains filtering methods in SCIM API

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-is#1469]
**Description**
At the moment we are supporting only equal method in group filtering. Contains and filtering methods needs to be implemented as in SCIM API specification.

**Suggested Labels:**
Improvement

**Comment by sarubi** [comment]
This is fixed with IS 5.7.0 onwards. Currently, we are supporting start-with, contains, end-with and "and"  logical operator.

**Comment by IsuraD** [comment]
Close the issue since this is already implemented.
