### ISSUE TITLE
Confusing configurations when trying to configure self registration

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#14697]
**Is your suggestion related to an experience ? Please describe.**
Notice the following configurations.
![Screenshot 2022-08-10 at 16 09 17](https://user-images.githubusercontent.com/39567992/183882216-2a8bd64d-c3d8-4927-aeb4-0297ae775f67.png)

When we do not add the `Send sign up confirmation email` config, we are still able to get the emails. This is very confusing since it says to receive confirmation notification. Currently, there is no clue on how to use and when to use this config.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
