### ISSUE TITLE
Spotted an UI diff in FIDO Security key authenticator button

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#14698]
**Describe the issue:**
1. Button is not properly displayed for FIDO security key authenticator.
2. Tool tip is duplicated for the fido login button.

![Screenshot from 2022-08-10 15-57-46](https://user-images.githubusercontent.com/35653110/183888938-13aabd91-f468-4dc0-898b-fc9692cf5fd2.png)

![Screenshot from 2022-08-10 15-57-53](https://user-images.githubusercontent.com/35653110/183888949-72f596ab-c798-4ab8-ae0d-50ca67ceba5b.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - OS: Ubuntu
 - Browser: Chrome, Firefox

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
