### ISSUE TITLE
Organization idp is not get updated immediately when switching to sign-in option for shared application

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#14700]
**Describe the issue:**
Please refer to this screencast

https://user-images.githubusercontent.com/13362482/183888964-23f33f3f-dd12-43ea-acc4-0d41e20193b2.mov

**How to reproduce:**
- Enable organization management feature
- Login to console as an admin user
- Create an organization
- Create the organization idp
- Create an application with default config and share the application with created organization
- Once you share the application switch to the sign-in option tap and see whether the organization IDP is added  as one of the sign-in option.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
This is fixed in https://github.com/wso2/identity-apps/pull/3325
