### ISSUE TITLE
Navigating to a 404 page after recover password for a new user with admin role from console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14707]
**Describe the issue:**
1. Enable email sending
```
[output_adapter.email]
from_address= "shanikaw@wso2.com"
username= "shanikaw@wso2.com"
password= "ccccccc"
hostname= "smtp.gmail.com"
port= 587
```
3. Enable passoword recovery
4. Create a user with admin role
5. Try to recover password for that user from console 
6. Will receive recover email
7. Click the link and setup a new pw
8. After pw reset you will get landed to a login page, from there try to login using new credentials

Getting below page

![Screenshot from 2022-08-12 09-52-30](https://user-images.githubusercontent.com/31848014/184284881-fa54b831-71e4-4191-bf24-b47143a7de9f.png)

https://user-images.githubusercontent.com/31848014/184284888-27685815-3190-4440-b686-89cd5270d978.mp4

**Env** 
IS 6.0.0 RC2 https://github.com/wso2/product-is/releases/download/v6.0.0-rc2/wso2is-6.0.0-rc2.zip
H2 default

**Comment by ThumulaPerera** [comment]
This was reproducible

**Comment by Yoshani** [comment]
Not reproducible in latest IS (tested on wso2is-6.2.0-m5-SNAPSHOT)
