### ISSUE TITLE
User image is not visible in header icon

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#14704]
**Describe the issue:**
The User icon is not loaded in the header icon even though the user has an icon selected. 

<img width="251" alt="Screenshot 2022-08-11 at 11 03 39" src="https://user-images.githubusercontent.com/11191791/184070148-7801d12f-44c0-4698-9955-2e24b611e446.png">

<img width="352" alt="Screenshot 2022-08-11 at 11 03 54" src="https://user-images.githubusercontent.com/11191791/184070168-62f94671-a1ae-4745-8198-a3bc5c78ed4a.png">

**How to reproduce:**
- Create a User with general details
- Before creating the user, select an image from the final step of the user wizard
- Login with the new user

**Expected behavior:**
The selected image should appear in the header icon

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 RC2
 - OS: MacOS

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
There is no way to select an image for an user.
