### ISSUE TITLE
Inconsistent dropdown used for userstore dropdown

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#14706]
**Describe the issue:**
The dropdown which opens when clicked on user stores has a red border where the rest doesn't making it inconsistent. 

<img width="218" alt="Screenshot 2022-08-11 at 11 13 05" src="https://user-images.githubusercontent.com/11191791/184071141-157ff077-993c-4c2c-9c9a-e49f529d9ad1.png">

<img width="395" alt="Screenshot 2022-08-11 at 11 13 13" src="https://user-images.githubusercontent.com/11191791/184071165-0a7d8d0b-7f47-41fa-b41f-fb28417f2b36.png">

**How to reproduce:**
- Navigate to users view
- Click on user store selection dropdown

**Expected behavior:**
Should be consistent with other UI similar UI elements

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Closing as this issue is not reproducible in the IS 7 console.
