### ISSUE TITLE
Session Context Cache - Optimization 

### ISSUE THREAD

**Issue by Thananchseyan** [wso2/product-is#14708]
**Is your suggestion related to an experience ? Please describe.**

When we consider the session data types which are stored in IDN_AUTH_SESSION_STORE, the size of the Session Context Cache is large. Based on the analysis, we had some suggestions for the optimization of the session context cache. We have

1. Some set of data that is defined in the server which are stored in the session objects.
2. Entire Identity Provider and Service Provider objects which are also defined in the server.

We can optimize the server level data by persisting only the reference of them instead of the entire object.

**Describe the improvement**
![Session Context Loader - modified diagram](https://user-images.githubusercontent.com/64280882/184295195-525ca4a5-dbdd-4438-9c27-9e1d6cfdd777.jpeg)

Session Context Loader class was created to optimize the session context cache object and load the optimized session context cache object to get the session context object. We are going to optimize the session context object when the context object passes to the session context cache class using addToCache method. As mentioned, Session Context object is not the temporary cache, So during the storing process, we will push the session context object into the queue and the persisting process will be handled by another thread. Therefore we cannot optimize and load the session object during the persisting process. It will affect the object in the cache also. Therefore we had to create a new model to hold the optimized attributes. We introduced a new attribute - optimizedSessionContext to store the optimized session context object in Session Context Cache Entry and during the optimization process, we are going to add the optimized session context in optimizedSessionContext and set the context object as the null. We are going to get the session context by using the optimized object.

**Additional context**

[https://github.com/wso2/carbon-identity-framework/pull/4211](https://github.com/wso2/carbon-identity-framework/pull/4211)

**Comment by senthalan** [comment]
Implemented with https://github.com/wso2/carbon-identity-framework/pull/4446
