### ISSUE TITLE
User view in groups detail is misaligned

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#14705]
**Describe the Issue:**
The user view for individual user in groups has a misalignment which makes the view crooked.

<img width="1200" alt="Screenshot 2022-08-11 at 11 07 48" src="https://user-images.githubusercontent.com/11191791/184070624-f35cc213-5aee-4a99-a9a4-1162ba800451.png">
  

**How To Reproduce:**
- Add a user to an existing group or a new group
- view the users in group detail view

**Expected behavior:**
Should properly align to edges

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
