### ISSUE TITLE
Required to check IS 6.0.0 compatibility

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14719]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**
- Ubuntun 2022 LTS and add ARM Architecture
- Temurin 17
 -MariaDB 10.4.13

**Describe the solution you would prefer**

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
