### ISSUE TITLE
Session Data Storage Optimization - Adding configuration 

### ISSUE THREAD

**Issue by Thananchseyan** [wso2/product-is#14722]
**Is your suggestion related to a missing or misleading document? Please describe.**

We have added a new configuration in identity.xml based on the Session Data Storage Optimization - Implementation. We can enable/ disable the optimization based the configuration. We need to add the info about the particular configuration under the "authentication-session-persistence". 

**Describe the improvement**

Session Data Storage Optimization is enabled by default. If we don't want to do the optimization then the configuration should be like this. 
```
[session_data.storage_optimization]
enable = false
```

---

**Comment by divyaamunugama** [comment]
Moving the issue to `On Hold` state as the feature needs more improvements.

**Comment by senthalan** [comment]
In a recent discussion, we decided not to provide an option to disable this configuration.  As this is been done as a performance improvement, and it won't be breaking any existing data (the improvement is done in away that the existing data will be also loaded and optimized in the next insert to the session store), so there in no real requirement to have this configuration.
