### ISSUE TITLE
Migrating from IS 5.3.0 to 6.0.0 using DB2: Error in Dry run

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#14721]
When running the dry-run from 5.3.0 to 6.0.0 migration (with DB2), there's an SQL exception occurring in [TokenBindingValidationMigrator](https://github.com/wso2-extensions/identity-migration-resources/blob/master/components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v5110/migrator/TokenBindingValidationMigrator.java) where a SELECT query for `IDN_OIDC_PROPERTY` table is executed.

However the table is not available until 5.5.0, and therefore the table is not found in the dry run

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
