### ISSUE TITLE
In a newly created SAML app subject attribute field shows an invalid value in console app

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14720]
**Describe the issue:**

By default the subject attribute field of SAML application is not set, the user_id will be taken. When viewing the subject attribute field of a newly created saml app from the console app, it says subject attribute=username. The persistant data record and the management console also says the subject attribute field is not set.

Update: It is the BE API that sends the username as subject attribute.

console app:
<img width="1507" alt="Screenshot 2022-08-15 at 15 22 01" src="https://user-images.githubusercontent.com/47152272/184614959-d0bf1136-618b-4d9a-9f06-9b6d91e44d16.png">

management console:
<img width="1508" alt="Screenshot 2022-08-15 at 15 22 28" src="https://user-images.githubusercontent.com/47152272/184614966-e1a69092-2e81-47b0-9f24-e07ab1cd1806.png">

**How to reproduce:**
1. create a new saml application from the console (any console) (do not set the subject attribute)
2. login to console app
3. view the newly created saml app
4. go to user attribute section
5. view subject attribute field

**Expected behavior:**
Should display its is not set.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - OS: macOS 12.5
 - Database: MSSQL, H2
 - Userstore: LDAP, JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
