### ISSUE TITLE
Verify the 2nd point content under disable groups and roles separation in the migration guide

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14734]
**Describe the issue:**
In the migration guide https://is.docs.wso2.com/en/6.0.0/deploy/migrate/prepare-for-migration/ > section "Disable Groups and Roles separation[¶](https://is.docs.wso2.com/en/6.0.0/deploy/migrate/prepare-for-migration/#disable-groups-and-roles-separation)" 2nd point is not required to do as a mandatory step. we may need to verify with the dev and validate whether this 2nd point is required to do here. As I got to know from the dev this 2nd step is not required to do 
If its not required we have to get it removed from the migration guide
![Screenshot from 2022-08-17 17-06-44](https://user-images.githubusercontent.com/31848014/185109459-b4bbf77c-39e2-45f9-a06c-06f088596ec6.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
