### ISSUE TITLE
Provide the ability to configure SAMLSSOAssertionBuilder per service provider

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#14735]
**Describe the improvement**
In OAuth applications, it is possible to define a token issuer per service provider, similarly in SAML as well we need to provide the capability to configure the SAMLSSOAssertionBuilder per service provider.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
