### ISSUE TITLE
Applications are shown duplicated in managment console and super tenant admin username not visible in console after migrating from 5.7.0 to 6.0.0 against oracle 19c

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14746]
1. Get IS 5.7.0 pack wum updated to latest wum (wso2is-5.7.0+1660491962474.full)
2. Get the wum updated 5.7.0 pack updated to latest U2 level (wso2is-5.7.0.70 level 70) get IS 6.0.0 pack from website https://wso2.com/identity-server/#
3. Point the data sources to oracle 19c
4. Create data in super tenant flow (users, roles, sp (oauth), sp (saml), scope, challenge question set, local claim, secondory userstore (jdbc, mysql 8), tenant, workflow with user add operation, idp google
5. Create data in tenant flow (sp (oauth & saml),role,user,scope)
6. Run the migration client sh wso2server.sh -Dmigrate -Dcomponent=identity
7. Change US type to database unique id in deployment toml and up the pack after migration

Migration client got executed without any issues

Login to managemnet console and console as super tenant in the migrated pack and list the applications
In the managment console same application is shows as 3 times duplicated but in console its shown correctly

https://user-images.githubusercontent.com/31848014/185396077-43126a74-601b-4413-b711-d1f9f1aeae9b.mp4

![Screenshot from 2022-08-18 18-02-55](https://user-images.githubusercontent.com/31848014/185396240-ca94e206-f925-482f-beb6-8e6175bf9a7d.png)

![Screenshot from 2022-08-18 17-44-40](https://user-images.githubusercontent.com/31848014/185396306-50890163-1c13-45b9-9223-c67b5a8e40c3.png)

https://github.com/wso2-extensions/identity-migration-resources/releases/tag/v1.0.213

**Comment by ShanikaWickramasinghe** [comment]
Also username of the super tenant admin is not shown in console from the migrated pack
![Screenshot from 2022-08-18 18-08-49](https://user-images.githubusercontent.com/31848014/185396804-423f4b1b-b5aa-4f20-b837-1909a83b2749.png)

**Comment by ashendes** [comment]
https://github.com/wso2/product-is/issues/14746#issue-1343039219 is tracked in https://github.com/wso2/product-is/issues/14726
https://github.com/wso2/product-is/issues/14746#issuecomment-1219443263 is tracked in https://github.com/wso2/product-is/issues/14775
