### ISSUE TITLE
Improve magic link authenticator to support "Sign in with MagicLink" experience.

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#14741]
**Is your suggestion related to an experience ? Please describe.**
Currently, Magic Link authenticator needs identifier first authenticator as the first step to get the user. Because of this behaviour , Magic Link depends on the identifier first. Also, we can't support "Sign in with MagicLink" experience with the current approach.

**Describe the improvement**
If there is no user authenticated before magic link authentication, redirecting to a prompt to get the username of the user in MagicLink authenticator itself.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
