### ISSUE TITLE
Docs need to mention that H2 migration from older versions have to be done in 2 steps.

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#14753]
**Is your suggestion related to a missing or misleading document? Please describe.**
H2 engine has been updated in 5.11.0 and up. Hence, the new H2 engine will not be able to run H2 queries in older migration steps as they've been written for the older H2 engine. These steps cannot be updated to work with the new engine as it would cause regressions if a migration to version <= 5.10.0 is needed to be done. 

**Describe the improvement**
Migration doc should mention that H2 migrations from version < 5.10.0 should be done in the following way.
1. Migrate to 5.10.0
2. Upgrade the H2 DB files using the H2 migration tool
3. Migrate to 6.0.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
