### ISSUE TITLE
Migration scripts for older versions contain incompatible syntax for H2 2.1.210

### ISSUE THREAD

**Issue by ThumulaPerera** [wso2/product-is#14758]
**Describe the issue:**

Migration scripts for older versions contain incompatible syntax for H2 2.1.210. For example, [this]( https://github.com/wso2-extensions/identity-migration-resources/blob/2a6017dab8278f84c85711720a49d5407468ec3d/components/org.wso2.is.migration/migration-resources/5.4.0/dbscripts/step1/identity/h2.sql#L5 ) contains `MODIFY` syntax which is not officially supported by H2 in default mode (https://github.com/h2database/h2database/issues/2404#issuecomment-575680811). 

![Screenshot 2022-08-22 at 10 06 02](https://user-images.githubusercontent.com/42399179/185840482-50845cc1-d400-4c16-af73-aa0a5ed31033.png)

**How to reproduce:**

Run a migration from IS 5.3.0 to 6.0.0 with embedded H2 configured as the primary userstore

**Possible workaround**

Running H2 in Oracle or MySQL [compatibility mode](http://www.h2database.com/html/features.html#compatibility) might be a possible workaround

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
