### ISSUE TITLE
Logic to select a locale when sending a SMS seems to be wrong

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#14751]
**Describe the issue:**
We are using `DefaultNotificationHandler`[1] to send SMS notifications from the code snippet[2]. In [2] the logic we are referring to is incorrect because we should not look for a different locale depending on the notification channel (SMS or EMAIL). Instead, we should take the locale in the user's profile.

**How to reproduce:**
1. Add a new template (password recovery SMS template) from another language.
2. Change the language to a language other than EN_us (same as the above template)
3. Try password or username recovery with SMS (other SMS flows won't go through this flow).

**Expected behavior:**
Send SMS from the specified locale in the user's profile.

**Possible fix**
Remove the code snippet [2] and replace it with the following block.
```
if (userClaims.containsKey(NotificationConstants.EmailNotification.CLAIM_URI_LOCALE)) {
    locale = userClaims.get(NotificationConstants.EmailNotification.CLAIM_URI_LOCALE);
}
```
**NOTE**: Better to rename the variables since DefaultNotificationHandler should have a general implementation.

---

[1] - https://github.com/wso2-extensions/identity-event-handler-notification/blob/master/components/event-handler-notification/org.wso2.carbon.identity.event.handler.notification/src/main/java/org/wso2/carbon/identity/event/handler/notification/DefaultNotificationHandler.java

[2] - https://github.com/wso2-extensions/identity-event-handler-notification/blob/master/components/event-handler-notification/org.wso2.carbon.identity.event.handler.notification/src/main/java/org/wso2/carbon/identity/event/handler/notification/DefaultNotificationHandler.java#L142-L152

**Comment by ChitharaKarunasekera** [comment]
I have tested this with IS 6.0.0 and seems like it is working as expected. Tested for password recovery and self-registration using SMS OTP. User's local is identified and uses default locale if local is not defined in the user profile.

If a user is specifying a locale, then there needs to be a template in the registry with that type. Otherwise it won't work

**Comment by somindatommy** [comment]
Closing this since the issue cannot be reproduced
