### ISSUE TITLE
Unable to get confirmation code when handling the account confirmation notification externally in SCIM Ask Password flow.

### ISSUE THREAD

**Issue by Manchiz** [wso2/product-is#14767]
**Describe the issue:**
Users can disable internal notification management [1] through the IS management console to use an external client for managing notifications. In the Ask Password flow also, users can disable internal notification management. But for an external client to send out the Ask Password request notification, the external client needs to know the confirmation code generated in the flow. For Ask Password flow invocations using SCIM 2 user API. However, there is no way to communicate the confirmation code to the external client. 

In the self-registration and recovery APIs, set the confirmation code with the API response if the internal notification management is disabled. It requires a similar approach for SCIM 2 Ask Password flow to communicate and get the confirmation code for the external client.

[1]
![image](https://user-images.githubusercontent.com/42811248/186077139-6887ba6e-05c1-43a7-860a-7f6c6eea0bfd.png)

**Environment information** 
 - Product Version:  wso2is-5.11.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
