### ISSUE TITLE
Resend OTP button is not available during the initial user interaction

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#14762]
**Is your suggestion related to an experience ? Please describe.**
The resend code button is not available for both SMS OTP and Email OTP in the first interaction. It will only be visible if the user puts an incorrect OTP value.

**Describe the improvement**
It would be great if the resend code button is available during the user's first interaction.

**Comment by amanda-ariyaratne** [comment]
This is fixed in IS 7.0
