### ISSUE TITLE
SAML Subject NameID Format set to emailAddress but UUID used as subject attribute

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#14768]
**Describe the issue:**
When a SAML SP is configured, the UUID is used as the subject attribute by default. But in the SAML assertion the default NameID Format is set to email address. The formats we can have are listed [here](http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#4.4.2.Assertion,%20Subject,%20and%20Statement%20Structure|outline). The default NameID Format and default subject attribute should match.

**How to reproduce:**
1. Register a standard SAML application in IS
2. Log in to the application
3. Using a tool such as SAML tracer, check the Subject of the SAML assertion 

**Result:**
An example SAML Subject:
```
<saml2:Subject>
    <saml2:NameID 
        Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">
            4a723102-93f8-4c3b-9e0c-8504ae0a4b6e
    </saml2:NameID>
    <saml2:SubjectConfirmation 
        Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml2:SubjectConfirmationData 
                InResponseTo="nobpjofloiidoodokmkadfhnmedcmbnoanimpofj"
                NotOnOrAfter="2022-08-23T03:35:30.712Z"
                Recipient="http://localhost:8080/saml2-web-app-pickup-dispatch.com/home.jsp"/>
    </saml2:SubjectConfirmation>
</saml2:Subject>
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
