### ISSUE TITLE
ldap_binary_attributes setting doesnt work for fields other than objectGUID

### ISSUE THREAD

**Issue by luisluix** [wso2/product-is#14765]
**Describe the issue:**
when setting ldap_binary_attributes to any attribute other than objectGUID that is also an octet string binary 16 byte attribute the value becomes null.

**How to reproduce:**
in deployment.toml set:
[user_store]
ldap_binary_attributes= "anotherobjectGUID objectGUID"

add claims to both fields
if you go to the userstore and look up the values anotherobjectGUID will be null.

**Expected behavior:**
anotherobjectGUID should display the correct value
OR if there is an error anywhere during the parse I should be notified anywhere what the issue is, instead I just get null with no errors even when tracing is set on the console.

Other info: my 2 binary attributes (objectGUID and anotherobjectGUID) that I been testing with have the same value. Only objectGUID works.

**Environment information** 
 - Product Version: IS 5.11
 - OS: Windows
 - Userstore: LDAP  active_directory

**Comment by luisluix** [comment]
Same issue happens in IS 6.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
