### ISSUE TITLE
[Migration] Enable account lock for totp authenticator

### ISSUE THREAD

**Issue by bhagyasakalanka** [wso2/product-is#14778]
**Describe the issue:**

With PR [1], we have enable account lock for invalid login attempts for TOTP authenticator. After this PR, previous behavior will be changed and if account lock is enabled, the user account will be locked if a user tries invalid codes higher than the configured max failed attempt count. 

If you wish to have the previous behavior where account lock is not enable for TOTP authenticator, you need to add following config to the deployment.toml file

```
[authentication.authenticator.totp.parameters]
EnableAccountLockingForFailedAttempts = false

```

This feature improvement is tracked in https://github.com/wso2/product-is/issues/14777

[1] https://github.com/wso2/carbon-identity-framework/pull/4234

**Comment by divyaamunugama** [comment]
Related doc PR: https://github.com/wso2-enterprise/migration-docs/pull/86

**Comment by nilminiwso2** [comment]
Closing the issue as the fix is done.
