### ISSUE TITLE
Active IdP Sessions Time in MyAccount not translated

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#14774]
**Describe the issue:**
The active IDP session time is represented in en-US in the myAccount console[2]. Ideally, it should change upon changing the language setting displayed in the myAccount application by the user. 
 As moment.js is used to display the time it is possible to change the locale as expected and achieve this requirement.

**How to reproduce:**
1. Start IS.
2. Navigate to Myaccount app 
3. Change language preferences located at the bottom
4. Navigate to Security -> Active IdP Sessions -> Show More -> Last Accessed info.

Last Accessed info is displayed in en-US instead of the preferred language.

**Expected behavior:**
The Last Accessed info should change based on the preferred language set in myaccount app.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0, IS 5.9.0, 5.11.0, 6.0.0.

**Comment by mevan-karu** [comment]
Similar improvement was done for console and My Account in IS 6.0.0 [1]. But this haven't fixed the IDP session time displaying issue mentioned in above.

@yathindrakodithuwakku FYI.

[1] https://github.com/wso2/identity-apps/pull/3332

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
