### ISSUE TITLE
Cannot use cross domain cookies for social authenticators - Google One Tap

### ISSUE THREAD

**Issue by indeewari** [wso2/product-is#14779]
**Describe the issue:**
Google One Tap uses CSRF cookies for integrity validation. The CSRF cookies is stamped under the domain accounts.asg.io since the One Tap UI appears at there. Authenticated callback goes to api.asg.io/commonauth and CSRF cookie is blocked due to domain mismatch. There is no configuration at Google side at the moment. Hence Google One Tap performs under configurable validation for CSRF. Once this issue is fixed, the existing configuration for CSRF validation should be removed at Google authenticator

**How to reproduce:**
Assumption :  CSRF validation is enabled 
   org.wso2.carbon.identity.application.authentication.framework.server.feature.default.json --> EnableCSRFValidationForGOT:true

1. Enable Google One Tap for Google authenticator at Asgardeo console
2. Add Google as a social authenticator for a configured service provider
3. Go to the login page of the service provider
4. Try to log in using Google One Tap
5. Cannot login
6. Check the blocked cookies loaded at commonauth request 
7. CSRF cookies is there under blocked cookies
8. Check the CSRF parameter at commonauth request

**Expected behavior:**
Commonauth request should contain CSRF cookie

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0 
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
