### ISSUE TITLE
Enable Account lock for TOTP and Backup code authenticators

### ISSUE THREAD

**Issue by bhagyasakalanka** [wso2/product-is#14777]
**Describe the improvement**
Currently, account lock for invalid login attempts is not working for TOTP and backup code authenticators. We need to enable account lock feature for these authenticators

- [ ] TOTP
- [ ] Backup Code Authenticator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
