### ISSUE TITLE
Duplicated EmailOTP email template on default configuration file

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#14788]
**Describe the issue:**
Since IS-5.10.0, there are two `EmailOTP` email templates configured in the file `email-admin-config.xml` located on the <IS_HOME>/repository/conf/email directory. This should be fixed to avoid any confusion on what is the actual email template picked up by the Identity Server.

**How to reproduce:**
N/A

**Expected behavior:**
The file `email-admin-config.xml` should contain only one `EmailOTP` email template.

**Environment information:**
 - Product Version: IS 5.10.0, IS 5.11.0, IS 6.0.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
