### ISSUE TITLE
Configure OTP format for Forced Password Reset

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#14794]
A way to configure the OTP format has been added with the introduction of the option to send OTP in the email to the other recovery/verification scenarios via [1].

As of the current implementation, there is no option to set the OTP format (such as which characters need to be in the OTP; uppercase, lowercase, or numerics) in the Forced Password Reset feature [2].

For the user experience, it is ideal to provide a configuration to change the OTP format in the Forced Password Reset flow as well.

[1] - https://github.com/wso2/product-is/issues/14808
[2] - https://is.docs.wso2.com/en/5.11.0//learn/forced-password-reset/#forced-password-reset

Related issues #10965 https://github.com/wso2/product-is/issues/14808

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
