### ISSUE TITLE
useEventHandlerBasedEmailSender property setting not defined under deployment.toml configurations

### ISSUE THREAD

**Issue by dinzie95** [wso2/product-is#14799]
**Describe the improvement**
In EmailOTP configurations it is required to set the following configuration in the deployment.toml file.

[authentication.authenticator.email_otp]
useEventHandlerBasedEmailSender = true

It is already mentioned in the document for setting email OTP for MFA in 5.11.0[1] but not available in the document for the latest 6.0.0 version[2]
[1]https://is.docs.wso2.com/en/5.11.0/learn/configuring-email-otp/
[2]https://is.docs.wso2.com/en/latest/guides/mfa/2fa-email-otp/

**Comment by rksk** [comment]
Related to https://github.com/wso2/product-is/issues/5334#issuecomment-497600360

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
