### ISSUE TITLE
Max allowed username length

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14797]
**Describe the issue:**
Generally, it is not expected to have longer usernames (>50 chars) since it is not practical for a human to remember such a long email address. But most of the flows are supported to have usernames with more characters (up to 230), and some tables do not accept lengthy usernames. Due to that reason flows are broken in the middle even though user creation is allowed. 

Therefore, it is required to adjust them to match other tables. Altering the following columns in respective tables to VARCHAR (255) should be sufficient

- SUBJECT of IDN_AUTH_SESSION_APP_INFO 
- USER_NAME of FIDO_DEVICE_STORE
- USER_NAME of FIDO2_DEVICE_STORE
- AUTHZ_USER of IDN_OAUTH2_ACCESS_TOKEN

Also, it is required to document on what is the officially allowed max username length.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
