### ISSUE TITLE
Re-enable Organization Management UI unit tests

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#14804]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**
The identity-apps unit test was failing after to the addition of [Organization management test suite](https://github.com/wso2/identity-apps/blob/be4f845bf15a854a7d7d688cefa70b81236c69ec/apps/console/src/features/organizations/__tests__/organization.test.tsx).

Hence, it was temporarily disabled in https://github.com/wso2/identity-apps/pull/3048/commits/be4f845bf15a854a7d7d688cefa70b81236c69ec.

**Describe the solution you would prefer**
Fix the mock issues and re-enable the suite.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
