### ISSUE TITLE
Invalid fidp for home real discovery redirects user to a confusing error page

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14806]
**Describe the issue:**
When the `fidp` param is defined in an authentication request for home realm discovery and if the defined `fidp` value does not belong to an idp which is added into the first step for the particular service provider, the user is redirected to the following confusing error page.

![domain unknown error](https://user-images.githubusercontent.com/719073/187085983-cf7a8e6f-d53d-4cf5-81cc-010eff3a5050.png)

**How to reproduce:**
- Create an OIDC service provider and initiate an authentication request with a random `fidp` value in the `/oauth2/authorize` request.
eg: https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Flocalhost&scope=openid+test1&client_id=lad1svgtko6WbDvZ9Z9gJv5_Dw0a&fidp=login
- User gets redirected to login.do with `authFailure=true&authFailureMsg=domain.unknown&hrd=true` query params

**Expected behavior:**
The error page should be clear on what went wrong.

**Environment information** 
 - Product Version: IS 5.11.0, IS 6.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
