### ISSUE TITLE
In a newly created SAML application, if subject attribute is set to username, the client application can use it without user consent

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#14809]
**Describe the issue:**

For a client application to use a user attribute, it first need the user's consent. 

With this PR: https://github.com/wso2/identity-apps/pull/3331/, the console application shows the username attribute is set as the subject attribute. (Which is wrong. For a newly created saml application, if no subject attribute is set, the userid will be taken as the default value). Issue created for this can be found from here -> https://github.com/wso2/product-is/issues/14720.

As mentioned in this issue, https://github.com/wso2/product-is/issues/14720 the displayed subject attribute value is set at the FE. If you by any chance save this particular user attribute configuration, the username will be set as the subject attribute at DB level. The problem with this approach is the client application then can access username value via subject attribute field, without the user consent.

https://user-images.githubusercontent.com/47152272/187116879-2a356f00-22f2-4543-9cf3-8cdcb292599f.mp4

**How to reproduce:**
1. Create a new web SAML application.
2. Go to protocol section and enable response sigining.
3. Go to user attribute section.
4. Save the configuration.
5. Login to the client application.

**Resultant behavior:**
You can proceed to the application, without giving any consent and you'll see username is being used for the profile name.

**Expected behavior:**
Ask user consent for the username attribute before entering to the application.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 6.0.0]
 - OS: [macOS 12.5.1]
 - Database: [H2]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/14720

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
