### ISSUE TITLE
Doc Feedback: Invalid content 

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#14807]
Location: https://is.docs.wso2.com/en/latest/references/concepts/authorization/jwt-bearer-grant-type/

There's invalid content at the end of the page.
`/quick-starts/saml2-bearer-assertion-profile`

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/12439288/187087620-b61da457-fbeb-4d91-9afb-00d96ba1696c.png">

**Comment by nilminiwso2** [comment]
Cannot reproduce.

<img width="1428" alt="Screenshot 2022-09-15 at 18 55 49" src="https://user-images.githubusercontent.com/21237558/190415683-be5dc7ef-2455-4770-bc9e-fad56cb695d0.png">

Please reopen if we missed anything.
