### ISSUE TITLE
Allow sending OTP for confirmation and recovery scenarios via email

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14808]
**Is your suggestion related to an experience ? Please describe.**
Currently, confirmation and recovery scenarios via email are done by sending a link that includes a link along with a confirmation code. But there are requirements to allow users to type an OTP instead of clicking a link. Currently, it is not allowed because the confirmation code sent in the email is a UUID and it is not user-friendly to type an UUID.

**Describe the improvement**
- A configuration to switch between OTP-based email confirmation or link-based email confirmation
- Another configuration to define the format of the OTP (length and characters to be included)
- An extension point to cater to more advanced customization requirements on the OTP (can extend the interface provided with https://github.com/wso2/product-is/issues/13817)
- The following flows to be covered
  - Self-registration with email confirmation
  - Lock on creation/Email verification on Add user
  - Lite User Registration
  - Password Recovery
  - Verify on Email Update
  - Resend code for all of above

Only the backend implementation will be done in the first phase and end-user UIs will be implemented in another phase.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
