### ISSUE TITLE
Where possible, remove mockito.ArgumentMatchers.nullable keyword in unit test cases

### ISSUE THREAD

**Issue by yogyagamage** [wso2/product-is#14810]
**Describe the improvement**

Remove mockito.ArgumentMatchers.nullable keyword in unit test cases where parameters are not specifically null.

**e.g.:**
_when(SAMLSSOUtil.isSAMLIssuerExists(x: anyString(), y: nullable(String.class))).thenReturn(shouldMakeIssuerExist);_
Here, if null is not a possible value for 'y', it should be replaced with anyString();

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
