### ISSUE TITLE
Remove elements with empty strings in the GET applications response for required attributes

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#14812]
**Is your suggestion related to an experience ? Please describe.**
For the following request, we get templateId, clientId, issuer as empty strings in each application because those values are empty in the DB.
```
curl --location --request GET 'https://<Server_URL>/t/<TENANT>/api/server/v1/applications?attributes=advancedConfigurations,templateId,clientId,issuer' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <TOKEN>' \
--header 'Cookie: paf=1661747620.163.42.5235|71acb898e1e9604d7bd8c41e308eb24e'
```

**Describe the improvement**
Better if the response doesn't contain empty strings for elements such as templateId, clientId, issuer although those elements are mentioned as required attributes in the API request.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
