### ISSUE TITLE
Setting temporary claims for user from the adaptive script feature is not working for implicit grant

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#14827]
**Describe the issue:**
Updating the user claims temporary(user. claims[“<claim_uri>”]) from the adaptive script[1] is not working properly for the Implicit grant. For the Authorization Code grant, it is working as expected[2].

In the Implicit grant, the values are getting directly from the user stores and not assigning the dynamic runtime claim values[3]. 

[1]https://github.com/wso2/product-is/issues/9293
[2]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/17410a57cce99b6a9899db3d84acfa7f45e13033/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultOIDCClaimsCallbackHandler.java#L142
[3]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/17410a57cce99b6a9899db3d84acfa7f45e13033/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultOIDCClaimsCallbackHandler.java#L344

**How to reproduce:**
1. Create a service provider with OAuth/OpenID Connect Protocol.
2. Select the "JWT" as the Token Issuer.
3. Add some claims(http://wso2.org/claims/fullname,http://wso2.org/claims/nickname) as the requested claims of the Service provider and set them Mandatory.
4. Add the above claims to the user profile by selecting "supported by default" and set some values from the user profile. 
5. Add the above claims to the OIDC scope if they are already not added.
6. Add "basic" as the first step authenticator and update the Adaptive script to set a claim value temporarily. 

```
var onLoginRequest = function(context) {
    executeStep(1, {
        onSuccess: function (context) {

                    user.claims["http://wso2.org/claims/fullname"] = "test full name";
                    user.claims["http://wso2.org/claims/nickname"] = "test nick name";
            
        }
    });
};
```
7. Initiate the Implicit grant flow and add the correct scopes which include the above claims.

```
https://localhost:9443/oauth2/authorize?response_type=token&client_id=<client_id>&redirect_uri=<redirect_uri>&scope=openid+<scope>
```
8. Authenticate with the user and retrieve the access_token from the network trace location response header.

```
Location: https://localhost:5000#access_token=**eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkEiLCJraWQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZ19SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhZG1pbiIsImF1dCI6IkFQUExJQ0FUSU9OX1VTRVIiLCJhdWQiOiI0MUN0TjQ1UHVDZ0V6MmpPWWxCMjJLaFROOHNhIiwibmJmIjoxNjYxOTQ2NTkwLCJhenAiOiI0MUN0TjQ1UHVDZ0V6MmpPWWxCMjJLaFROOHNhIiwic2NvcGUiOiJhZGRyZXNzIG9wZW5pZCBwcm9maWxlIiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwibmFtZSI6ImFkbWluIGFkbWluIiwibmlja25hbWUiOiJmZGFmYXNkZmFzIiwiZXhwIjoxNjYxOTUwMTkwLCJpYXQiOjE2NjE5NDY1OTAsImp0aSI6Ijg0NmY5NWUyLTdjZjQtNGNiNC1iNzhkLWQ1NTI4NjEwNmRlMCJ9.BSjtAxDvIuOR7nGYVMygYxOUaI156WL-6qgcdE1yEDb07YQN_Qrsy205BYBAs6p8a3eJDtcSgosvUDyNRiJ_X7TAgau40xhfinMIIXjkXYcivvnWFAXbwEGK-CXhFzuzCAkzqkQeGGEg1pK_DdiIBPhixLKX4glqD8Kp6ot5it_QATcqIuwqcLjCHCRQenIm-3hBwjEMBHRrR9cJgfdk30mZl_O8E60uHeAjRrnMSeU9cY6gXTXiJlqTBKD80jprYZrnHbDNQ9EPK9lF7RQ_5V23e4GX82a_O04kuoZoHOJ8xNUx8tH9cE97pJh52GKvzHVTAD2TnovsJ-9R_KzzXA**&token_type=Bearer&expires_in=3599&session_state=9b4426b10cebb9f33ad6e170949c304949fc76f1728878f03d18048a4ac97f27.92Zgj62K0rJz8Ndx9TYIBQ
```
9. decode the token(jwt.io) and observe the original value for the claims. The claim values are not updated.  If you check the ID token via the Authorization Code grant, you can see the values are updated.

**Expected behavior:**

The values that are assigned from the adaptive script should be available as the Access Token claim values. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0

**Comment by Shaaali** [comment]
var onLoginRequest = function(context) {
    executeStep(1, {
        onSuccess: function (context) {
                    var user = context.steps[1].subject;
                    //user.claims.full_name = "test full name";
                    //user.claims.nick_name = "test nick name";
            user.claims["http://wso2.org/claims/fullname"] = "test full name";
                    user.claims["http://wso2.org/claims/nickname"] = "test nick name";
        }
    });
};

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
