### ISSUE TITLE
[Migration] Need to change PROPERTY_KEY of existing audiences in IDN_OIDC_PROPERTY Table when migrating to 6.1.0

### ISSUE THREAD

**Issue by gershom96** [wso2/product-is#14820]
**Description:**

Changes made in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1902 require audiences to be stored separately in the DB. 

The PROPERTY_KEY values in the table IDN_OIDC_PROPERTY with the value 'audience' need to be duplicated as 'idTokenAudience' and 'accessTokenAudience' during migration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
