### ISSUE TITLE
[IS 5.11] Email Template Content type is set to text/html after doing a change in Email Template

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#14828]
**Describe the issue:**

After doing a small change in the email template from Management console > Manage > Email Templates, once the email template is saved the email template message content type is set to *text/html* replacing its actual value *text/plain*.

Also, git issue [1] is in the IS 5.11.

**How to reproduce:**

1. Change a selected email template to contentType to text/plain with the appropriate message body from Management console > Manage > Email Templates. Since git issue [1] is also there in IS 5.11 We can not check this from the Management console > Manage > Email Templates. We could check whether the contentType is properly set with the following curl command or by browsing the registry

Curl Command:
```curl --location --request GET 'https://localhost:9443/t/carbon.super/api/server/v1/email/template-types/[template-id]' --header 'Authorization: Basic YWRtaW46YWRtaW4='```

Browse Registry:
`_system/config/identity/email/accountenable/language` > Properties > emailContentType

2. Do a small change to the message body of the above email template from the Management console > Manage > Email Templates and save it 
3. Check the contentType and it has changed to text/html.

However, Changing email template body from the registry works as expected.

**Expected behavior:**

ContentType should not be changed after editing an email template
**Environment information** **:**
 - Product Version:  IS 5.11.0

---

### Optional Fields

**Related issues:**

[1] - https://github.com/wso2/product-is/issues/12870
**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
