### ISSUE TITLE
log4j version 2.12.0 used with release https://github.com/wso2/product-is/releases/tag/v5.11.0

### ISSUE THREAD

**Issue by jasmine0508** [wso2/product-is#14830]
Log4j vulnerable versions are being used in gitrelease for wso2 is v5.11
I downloaded the latest v5.11 from https://github.com/wso2/product-is/releases/tag/v5.11.0 and it has log4j vulnerability due to version 2.12 for log4j.

Please provide fix or updated release of v5.11 for the same

**Comment by rksk** [comment]
IS 6.0 release contains the required log4j upgrades.
