### ISSUE TITLE
Forced Password Reset feature uses the Manage Notification Sending Internally property of the Self Registration

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#14831]
**Describe the issue:**
When resending the verification e-mail for forced password reset[1], 'Manage notification sending internally' property of the Self Registration is being used[2]  for deciding whether to  handle notification internally. This is affecting below two recovery scenarios. 

1. ADMIN_FORCED_PASSWORD_RESET_VIA_EMAIL_LINK
2. ADMIN_FORCED_PASSWORD_RESET_VIA_OTP

**How to reproduce:**
1. Enable Force password reset.
2. Disable 'Manage notification sending internally' in the self registration section. 
3. Resend the e-mail link or e-mail OTP for a user using resend API. 
4. No email will be sent to the user. 

**Expected behavior:**
Resend verification e-mail to the user.

**Environment information**  **:**
 - Product Version: IS 5.11.0

---

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/resend-account-recovery-mail/
[2] https://github.com/wso2-extensions/identity-governance/blob/3599acf4026441eb4f71f228c8b723f58c5638ad/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/confirmation/ResendConfirmationManager.java#L571

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
