### ISSUE TITLE
Replace `promptId` value using `sessionDataKey` in Dynamic Prompt.

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#14842]
**Describe the improvement**

Replace the `promptId` value using `sessionDataKey` in https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/sequence/impl/GraphBasedSequenceHandler.java#L269. 

With the following improvement https://github.com/wso2/product-is/issues/14878 `sessionDataKey` parameter will be added to the redirect URL. Therefore `promptId` will be redundant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
