### ISSUE TITLE
Unnecessary exceptions in debug logs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14848]
**Describe the improvement**
`getMaxUserNameListLength` and `getSQLQueryTimeoutLimit` methods are writing long stack traces if the relevant userstore properties are not configured. It is Unnecessary to log such stack traces in the debug logs and also confuses the users who enable the debug logs.

[1] https://github.com/wso2/carbon-kernel/blob/91b8b66ab58a7c923e3668fc4f7e5d2cbcde561d/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L4766

**Comment by rksk** [comment]
Pending 6.0 fix

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
