### ISSUE TITLE
Add additional logs to improve the identity-inbound-auth-oauth extension.

### ISSUE THREAD

**Issue by nipunaupeksha** [wso2/product-is#14846]
**Is your suggestion related to an experience ? Please describe.**
When debugging noticed, in `private boolean getConnection()` method of the `org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator` class, we are lacking logs to identify the issues. Inside that method, in ` if (StringUtils.isNotEmpty(httpResponse)) {...}` conditional check, if we receive `httpResponse` and `httpConnection.getResponseCode()` similarly, the `if (httpResponse.trim().equals(String.valueOf(httpConnection.getResponseCode()))) {...}` makes sure to give info with logs. But if those two are different we don't have logs to identify that.

In addition, there is a spelling mistake with the word _receive_ in the log `log.debug("Code is successfully sent to the mobile and recieved expected response code : " +httpResponse);`

**Describe the improvement**
Add additional logs to improve code quality and to get more information on the smsotp.

**Comment by RushanNanayakkara** [comment]
Fix released
