### ISSUE TITLE
Issue with encoded callback URL in the Ask Password flow

### ISSUE THREAD

**Issue by lochanaEdirisinghe** [wso2/product-is#14876]
**Describe the issue:**
When setting the following authorize request as the callback URL during the Ask password flow.

`https://localhost:9443/oauth2/authorize?response_type=code&scope=openid internal_login&client_id=t7TMbfGeUqa11KsvVf7SiWfNigka&redirect_uri=http://localhost:8080/playground2/oauth2client`

We have to add the above URL in encoded format to the Ask Password email template and once a user is created, the password reset link which is sent via email contains that callback URL.

The encoded callback URL is as follows,

`https%3A%2F%2Flocalhost%3A9443%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26scope%3Dopenid%20internal_login%26client_id%3Dt7TMbfGeUqa11KsvVf7SiWfNigka%26redirect_uri%3Dhttp%3A%2F%2Flocalhost%3A8080%2Fplayground2%2Foauth2client`

Space between two scopes(openid internal_login) has been replaced with the %20.

Once the user clicks on the password reset link and submits the new password and clicks on proceed button, the /accountrecoveryendpoint/completepasswordreset.do endpoint is called and the spaces of the callback URL are replaced again with a plus(+) mark according to the logic in the password-reset-complete.jsp page.

Therefore the authorize request is going as follows,
`
https://localhost:9443/oauth2/authorize?response_type=code&scope=openid%2Binternal_login&client_id=SWh6kCNYEFESALgsITxbdzUBFA0a&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fplayground2%2Foauth2client`

Now the space between two scopes has been replaced with + mark and the encoded value of + mark is %2B. But it should not be replaced with + mark and it should be %20(encoded value of the space).

So that the scope is taken as a single scope like openid+internal_login and not the separate scopes. Therefore the application is not getting the id_token of the user.

**Expected behavior:**
The space between scopes should not be replaced with + mark. 

**Environment information**
 - Product Version: [IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
