### ISSUE TITLE
WSO2 identity server 6.0.0 SOAP APIs Replacement

### ISSUE THREAD

**Issue by HareeshYHY** [wso2/product-is#14875]
**Describe the issue:**
As part of WSO2 identity server 6.0.0, SOAP APIs are Deprecated and Recommended to use REST-based APIs. We are using RemoteUserStoreManagerService.wsdl and UserIdentityManagementAdminService.wsdl SOAP APIs in our project, want to replace the SOAP APIs with recommended REST APIs. Can you help us to find the list of REST APIs to replace RemoteUserStoreManagerService.wsdl and UserIdentityManagementAdminService.wsdl SOAP APIs. The APIs document is not clear.

Am referring the below document from wso2
https://is.docs.wso2.com/en/latest/references/about-this-release/#removed-features
https://is.docs.wso2.com/en/latest/apis/overview/

**How to reproduce:**

**Expected behavior:**
Can you help us to find the list of REST APIs to replace RemoteUserStoreManagerService.wsdl and UserIdentityManagementAdminService.wsdl SOAP APIs.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.0.0
 - OS: Windows

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
