### ISSUE TITLE
WSO2 identity server 6.0

### ISSUE THREAD

**Issue by KokkulaSamyuktha** [wso2/product-is#14872]
Describe the issue:
There are some deprecated features in WSO2 6.0 analysis where they are suggesting to use REST API's instead of SOAP API's. In our project, we are using two SOAP API's (RemoteUserStoreManagerService.wsdl and  UserIdentityManagementAdminService.wsdl). Are there any REST API's introduced in WSO2 6.0 for the replacement of these two SOAP API's so that we can use those REST API's in our project??

Environment information:
 - Product Version: [e.g., IS 6.0]
 - OS: [e.g., Windows]

**Comment by rksk** [comment]
User management can be done with the SCIM2 APIs. UserIdentityManagementAdminService has both user management and other identity related operations. There are feature specific APIs for them. You can find more information on the available APIs [here](https://is.docs.wso2.com/en/latest/apis/overview/).

In the future, please use [Stackoverflow](https://stackoverflow.com/questions/tagged/wso2-identity-server) or [WSO2 discord server](https://wso2.com/blogs/thesource/wso2-is-moving-from-slack-to-discord-in-october-2022/) to ask questions.
