### ISSUE TITLE
Consume used query parameters in the login page urls from context API

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#14878]
**Describe the improvement**
Login page URLs have a large number of query parameters. Using following API, it is possible to consume these query parameters from the backend.
https://is.docs.wso2.com/en/latest/apis/use-the-authentication-rest-apis/#/Authentication/getSensitiveParameters

With that, we can hide the query parameters used in the login portal as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
