### ISSUE TITLE
Extract the base components from carbon-identity-framework to new repo (s)

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#14886]
**Is your suggestion related to an experience ? Please describe.**
At the moment carbon-identity-framework repo contains a significant amount of components some of them does not have any real relationship to the other components in the repo. Few examples would be central-logger, identity-event and configuration-mgt. These are base components and can be reused in different occasions. However if the component that is going to use these base components needs to locate before the components in carbon-identity-framework in the dependency hierarchy, these cannot be reused.

**Describe the improvement**
If we can extract these components to different repo(s), this problem can be resolved and they can be reused more often.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
