### ISSUE TITLE
Adding account disabling server config to deployment.toml will overwrite tenant configs when it set to false

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#14889]
**Describe the issue:**
Account disabling handler should be enabled through resident IDP settings of each tenant or through the deployment.toml (for all tenants) as per the doc [1]. However below behavior is observed with the server config.
- if the deployment.toml config is true and an existing tenant has disabled it, disabling feature will be enabled for the tenant.
- if the deployment.toml config is false and an existing tenant has enabled it, disabling feature will keep enabled for the tenant.

Ideally adding the server level config should not affect the existing tenants.

**How to reproduce:**
1. Create one/ two tenants in the server.
2. Login to management console of one tenant and enable account disabling as mentioned in [1].
3. Login to management console of the other tenant and enable and then disable account disabling (This way we can assume resident IDP configs of the tenant is changed).
4. Add deployment.toml config and restart the server.
    ```
    [identity_mgt.account_disabling]
    enable_account_disabling=true
    ```
5. Login to management console and check for account disabling. It will be enabled for both tenants (Can you identity-governance APIs as well [2]).

**Expected behavior:**
Adding server config should not change governance configs of existing tenants.

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-account/#enable-account-disabling
[2] https://is.docs.wso2.com/en/latest/apis/identity-governance-rest-api/#/Management/patchConnector

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
