### ISSUE TITLE
Update documentation to provide information on update email templates specific to user invite flow

### ISSUE THREAD

**Issue by vinumaddumage** [wso2/product-is#14897]
**Description:**
For user onboarding through user invite, the administrative user should have the knowledge to update the relevant email templates to provide a way for the newly created user to direct themselves. The corresponding documentation [1] should be updated to provide this information on how to update the email templates used in this flow.

[1] https://is.docs.wso2.com/en/5.9.0/learn/creating-users-using-the-ask-password-option

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
