### ISSUE TITLE
Redirecting user in user invite flow after the setting password

### ISSUE THREAD

**Issue by vinumaddumage** [wso2/product-is#14896]
**Description**
If a new user is created through user invite flow, after the user sets the password using the link received through mail, the user is redirected to the login page of the My Account application to which they can login using their tenant qualified username.

The page that the user is redirected after registration may not always required to be the My Account login page. An administrative user should have the capability to set a redirection URL of their preference which may be service provider specific (depending on which application user invite flow was invoked).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
