### ISSUE TITLE
Merging PRs

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#14907]
**Is your suggestion related to a missing or misleading document? Please describe.**
Merge old PRs into the Master and 6.0.0 branches. 

The PR's are listed in the following excel sheet
https://docs.google.com/spreadsheets/d/1fB5msV2YcORM_IQctglX_hhEBbnpXs7hgVl5nV7B4vM/edit#gid=1744163804

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
