### ISSUE TITLE
Use a common claim for example in `Add regular expressions for allowed claims` and `Try it Out` in multi-attribute login docs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14924]
**Describe the issue:**
In multi-attribute login docs https://is.docs.wso2.com/en/latest/guides/login/multi-attribute-login/#enable-multi-attribute-login, 
better to add a screenshot of a claim which will be used in the try it out flow, under https://is.docs.wso2.com/en/latest/guides/login/multi-attribute-login/#add-regular-expressions-for-allowed-claims

`Add regular expressions for allowed claims` section has a telephone number claim configuration. but the tryout flow doesn't base on that. Instead, Try out has mobile claim regex config.

![Screenshot - 2022-09-22T142939 627](https://user-images.githubusercontent.com/25483865/191705934-56c49deb-e4b4-4bb7-8fe5-2b9f0504a795.png)

Better to use either mobile/telephone claim in both sections. The developer who follows the document will first go to telephone number claim and then he will not find a given sample regex for that claim in Try it Out section.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
