### ISSUE TITLE
Invalid Regex Patterns in Multi-Attribute Login docs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14923]
**Describe the issue:**
The regex patterns in this doc seem incorrect.https://is.docs.wso2.com/en/latest/guides/login/multi-attribute-login/#enable-multi-attribute-login (should be an escape character issue)
![Screenshot - 2022-09-22T143044 449](https://user-images.githubusercontent.com/25483865/191705084-caf9bec9-5569-43b8-a93e-1e97016d2292.png)

Need to update as follows. The Patterns in .md files are correct

| Claim URI                           | Example Regex pattern    |
|-------------------------------------|-----------------------------------------------------------------|
| http://wso2.org/claims/emailaddress | `^([a-zA-Z0–9_\.\-])+\@(([a-zA-Z0–9\-])+\.)+([a-zA-Z0–9]{2,4})+$` |
| http://wso2.org/claims/mobile       | `^(\+\d{1,2}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$` |
| http://wso2.org/claims/username     | `^[a-zA-Z0–9._-]{3,}$`                                            |

https://github.com/wso2/docs-is/edit/master/en/docs/guides/login/multi-attribute-login.md

**Comment by nilminiwso2** [comment]
Related issue: https://github.com/wso2/product-is/issues/14924

**Comment by nilminiwso2** [comment]
The regex is now rendering properly in the documentation with fix [1].
We will keep the issue open to revisit the solution that was used to fix it.

[1] https://github.com/wso2/docs-is/pull/3442

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
