### ISSUE TITLE
Configure HA IS Analytics - WSO2 IS Analytics 5.8.0

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#14920]
It was found that the following locations are not available in the IS Analytics according to the official documentation[1],

- /repository/conf/datasources/master-datasources.xml
- <IS_Analytics_HOME>/repository/components/lib
- /dbscripts/mysql.sql
- /repository/conf/analytics/analytics-conf.xml
- /repository/conf/user-mgt.xml
- /repository/conf/registry.xml
- <IS_Analytics_HOME>/repository/conf/axis2/axis2.xml
- /repository/conf/event-processor.xml

Therefore, this leads to difficulties in setting up a HA deployment for IS Analytics following the official documentation. This should be corrected to reflect the correct paths so that a user could follow the documentation and set the deployment with minimum assistance.

Appreciate your thoughts on this.

[1] https://docs.wso2.com/display/IS580/Setting+Up+Deployment+Pattern+2

**Comment by nilminiwso2** [comment]
Updated the documentation for IS 5.8.0 [1] after testing instructions in [2].

The relevant file paths are as follows:

<IS_ANLYTICS_HOME>/conf/worker/deployment.yaml
<IS_ANLYTICS_HOME>/lib
Also, please note that the instructions are tested with MySQL version 5.7.*.

Results:

The two Analytics were started in Active and Passive modes as specified in the doc.
When the Active node failed, the other node successfully changed to Active mode.
[1] https://docs.wso2.com/display/IS580/Setting+Up+Deployment+Pattern+2
[2] https://docs.wso2.com/display/SP440/Minimum+High+Availability+Deployment
