### ISSUE TITLE
WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'admin[-1234]'

### ISSUE THREAD

**Issue by shayan2121212121** [wso2/product-is#14925]
Affected version: wso2is-6.0.0.0
Operating System: Mac

Type: bug
Severity: Medium
Priority: High

Step to reproduced:

1.Server startup,
2.Navigate to https://localhost:9443/carbon/
3.Try to login with username admin and password admin (super_admin credentials)
4.getting warning log in wso2carbon log and an error popup on the browser console : "Login failed! Please recheck the username and password and try again.",

WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'admin[-1234]' at [2022-09-22 15:00:04,491+0530]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
