### ISSUE TITLE
Direct user in user invite flow to "User onboarding successful" page

### ISSUE THREAD

**Issue by vinumaddumage** [wso2/product-is#14935]
**Description:**
As the first iteration to address https://github.com/wso2/product-is/issues/14896 instead of redirecting user to My Account login page by default, the user after setting the password using the link received through mail in the user invite flow, can be directed to a general page which mentions that the user was successful onboarded.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
