### ISSUE TITLE
multi-attribute login feature enabled IS setup which has `[tenant_mgt] enable_email_domain= true` config, doesn't support multi-attribute login feature properly

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14930]
**Describe the issue:**
Having the following deployment.toml config (which is related to Using Email Address as the Username (https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/) overwrites the multi-attribute login configurations
```
[tenant_mgt]
enable_email_domain= true
```

**How to reproduce:**
1. Download IS-6.0.0
2. Create a user in IS, giving a username, email and mobile number
3. Go to https://localhost:9443/myaccount
4. Try login with username 
5. Login should be successful 
6. Notice the login portal
![Screenshot - 2022-09-22T233620 510](https://user-images.githubusercontent.com/25483865/191822608-8455bf46-7748-4d70-a68e-7279ebccc902.png)
7.  Then configure the multi-attribute login as mentioned in https://is.docs.wso2.com/en/latest/guides/login/multi-attribute-login/#enable-multi-attribute-login (configure [usernme, email and mobile claims](http://wso2.org/claims/username,http://wso2.org/claims/emailaddress,http://wso2.org/claims/mobile as Allowed Attribute Claim List. Configure regex patterns for those claims as well)
![Screenshot - 2022-09-22T233654 287](https://user-images.githubusercontent.com/25483865/191822644-d316da3e-57ee-4b0a-97fb-2ac363280157.png)

8. Then try login in to https://localhost:9443/myaccount using username, mobile, emailaddress@<tenantdomain> as login identifier. **Login will be successful** 
9. Notice the login identifier placeholder as well
![Screenshot - 2022-09-22T233718 293](https://user-images.githubusercontent.com/25483865/191822855-82bf8769-4e09-43c6-846a-7c944176caac.png)
10. add the following config to deployment.toml and restart the server (still multi-attribute login feature is enabled)
```
[tenant_mgt]
enable_email_domain= true
```
11. Then try login in to https://localhost:9443/myaccount using username, mobile, email address. User will be able to log in using email address only 
Also notice the login identifier placeholder 
![Screenshot - 2022-09-22T234219 226](https://user-images.githubusercontent.com/25483865/191823605-04303bd5-fe8b-4bce-a872-9b2e2515ce1d.png)

If the username or mobile is used "Invalid username! Username should be an E-Mail address." error will be shown

![Screenshot - 2022-09-22T235654 412](https://user-images.githubusercontent.com/25483865/191823623-eac283d2-ae06-4618-a4a6-ec1508e1607c.png)

**Expected behavior:**
Conflicting feature configs should be documented properly. Also need to analyse the IS flows if email as username feature is enabled and multi-attribute login feature is enabled.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0

**Comment by DinikaSen** [comment]
This issue can be resolved partially by adding the following config. This resolves not being able to login with mobile number and username. However, the placeholder in the login form will still be displayed as 'Email address'. Hence, the UI bug should be addressed and this config should be documented in the guide.

```
[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
