### ISSUE TITLE
[Improvement] [UI]when a application is revoked for a service provider the system should provide a UI label

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#1494]
when a application is revoked for a service provider the system should provide a UI label. With the current implementation it is not easy to track if the application was revoked or not

steps
1.for a created service provider click on the revoke button for a clientid/secret on OAuth/OpenID Connect Configuration

Note: the only way to figure this out is if we click on "Revoke" option again

![revoke](https://user-images.githubusercontent.com/6552100/33601040-129034b2-d9d1-11e7-8a6d-4dbee03b1c64.png)

**Comment by sagara-gunathunga** [comment]
We will consider this for new admin portal redesign.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
