### ISSUE TITLE
need a way to listen system events.

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-is#14943]
**Is your feature request related to a problem? Please describe.**
For APIM Deployments we need to have a standard way to retrieve user events from the IDP end.
1. User to role mapping change.
2. User token generation
3. Token revocation.
4. User deletion.
etc.

**Describe the solution you would prefer**
Need a model to subscribe to a type of event in the Identity server giving a web sub endpoint.

**Comment by mefarazath** [comment]
@tharindu1st how is this currently implemented?
Any resources to refer the current architecture of this solution

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
