### ISSUE TITLE
Remove workflow scenario from the QSG

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#14942]
**Describe the improvement**

Need to remove the workflow scenario from the quick start guide as decided.

- [x] Remove the workflow related parts from the qsg script in is-samples - Linux/macOS - https://github.com/wso2/samples-is/pull/361
- [ ] Remove the workflow related parts from the qsg script in is-samples - Windows
- [ ] #15133

**Comment by mevan-karu** [comment]
@piyarathnalakmali **Remove the workflow related parts from the qsg script in is-samples - Windows** please create a separate issue to track this improvement also and prioritize this.
