### ISSUE TITLE
JWT validation fails for older tokens issued before migration

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#14953]
**Describe the issue:**

In newer identity server versions the kid header parameter has the SHA-256 thumbprint instead of the SHA-1 thumbprint[1]. The calculation logic of the kid value is totally up to the authorization server, so this change has no issue.

However, when migrating from older versions of the identity server where the tokens were issued with SHA-1 thumbprint kid value to newer identity server versions(5.10.0, 5.11.0, 6.0.0) where the tokens are issued with the SHA-256 thumbprint kid value and the JWKS endpoint displays the SHA-256 thumbprint kid value, it is not possible to validate the older tokens using the JWKS endpoint since the old kid value is not returned.

[1]https://github.com/wso2/product-is/issues/14131

**Expected behavior:**
Provide an option to temporarily return both key sets from the JWKS so that both old and new tokens can be validated from the JWKS endpoint.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.0.0]

---

**Comment by rksk** [comment]
Following config can be added to get both new and old KID values in the JWKS response.

```
[oauth.jwks_endpoint]
add_previous_version_kid = true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
