### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#14956]
**Is your suggestion related to a missing or misleading document? Please describe.**
- Update the `Overview` page
- Update the grant type of APIs: `AuthorizationCode` -> `Password`

Related Issue: https://github.com/wso2/product-is/issues/14837

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
