### ISSUE TITLE
localhost will not be ignored in Hostname verification

### ISSUE THREAD

**Issue by leonardorobertolopez** [wso2/product-is#14954]
**Describe the issue:**
When the client login to an application using localhost, the following error appears:
[Error.txt](https://github.com/wso2/product-is/files/9666159/Error.txt)

**How to reproduce:**
Add the following line to the etc/hosts file:
127.0.0.1 localhost wso2.is.lb
*where wso2.is.lb is the hostname of the IS

Add the following configuration in the deployment.toml file
[deployment.txt](https://github.com/wso2/product-is/files/9666257/deployment.txt)

Generate the keystore a in the  security folder 
(IS_HOME\wso2is-6.0.0\repository\resources\security): 
[certificate.txt](https://github.com/wso2/product-is/files/9666279/certificate.txt)

Try the SAML authentication flow with an application (for ex pickup-dispatch).

There is an issue with the following functionalities when the ip localhost is being validated: 

->authenticationendpoint\plugins\basicauth-extensions.jsp 
    ->**checkTypingDNA** 
line:  isTypingDNAEnabledInTenant = preferenceRetrievalClient.checkTypingDNA(tenantDomain); 

-> authenticationendpoint\basicauth.jsp
         ->**checkMultiAttributeLogin**
line: isMultiAttributeLoginEnabledInTenant = preferenceRetrievalClient.checkMultiAttributeLogin(tenantDomain);
         **->self-sign-up**
line: isSelfSignUpEnabledInTenant = preferenceRetrievalClient.checkSelfRegistration(tenantDomain);
           **->account-recovery**
line: isUsernameRecoveryEnabledInTenant = preferenceRetrievalClient.checkUsernameRecovery(tenantDomain);
and line: isPasswordRecoveryEnabledInTenant = preferenceRetrievalClient.checkPasswordRecovery(tenantDomain);

**Expected behavior:**
The user should login normally into the application. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 6.0.0]
 - OS: [Windows]
 - Database: [H2]
 - Userstore: [LDAP]
- Tomcat 9.0
---

### Optional Fields

**Related issues:**
#12577  
CS0200105: This is the I take in consideration to create this case.

**Suggested la

bels:**

**Comment by tharakawijekoon** [comment]
duplicate https://github.com/wso2/product-is/issues/12577
