### ISSUE TITLE
[IS 6.0.0] Duplicate Service Provider Names listed when having multiple inbound authenticators configured

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#14950]
**Describe the issue:**
After creating the service provider with multiple inbound authentication configurations(saml, openid , passivests) service provider name is displayed in the list. IF  2 inbound authenticators are configured, the service provider name will be displayed two times. If the service provider has 3 inbound authenticators, the sp name will be there three times. 

According to our analysis, the data persistence part is working as expected, but when retrieving service provider names, it is using this query[1] in IS 6.0.0. This query retrieves the same service provider multiple times if it has more than one inbound authenticator in the SP_INBOUND_AUTH table.

In the 5.11.0 version, it is using[2] query to retrieve the service providers(which is working as expected).

**How to reproduce:**
1. Go to Management console -> Add new service provider
2. Configure SAML, openid, passivests  inbound authenticators 
3. Save the Service provider.
4. Observe the duplicate service provider names in the list. 

**Expected behavior:**
There should be one service provider listed even if it has multiple inbound authenticators configured

**Environment information:**
 - Product Version: IS 6.0.0

---

[1]https://github.com/wso2/carbon-identity-framework/blob/v5.23.8/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationMgtDBQueries.java#L79
[2]https://github.com/wso2/carbon-identity-framework/blob/v5.18.187/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtDBQueries.java#L92

**Comment by mifrazmurthaja** [comment]
This is not fixed in the pagination scenario (when there are more than 15 SPs are available)

**Comment by DMHP** [comment]
Removing the assignment as I may not check on this any soon.

**Comment by ashanthamara** [comment]
Closing the issue since the public fix is deployed in the product.
