### ISSUE TITLE
[5.6-5.8] Carbon Dashboard Throws Exception When Trying to View Login Info

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#14952]
**Describe the issue:**
carbon dashboards (local URL : https://localhost:9443/dashboard) throws an exception when clicked on `My Login Sessions` or `Monitor Users Login Sessions` options.

**How to reproduce:**
1. download IS 5.6 5.7 5.8 pack.
2. start the IS
3. access the dashboard through above URL and enter admin/admin credentials
4. try clicking on one of above options and observe logs in IS

**Expected behavior:**
Should be able to view login session information.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.6.0 through IS 5.8.0
---

### Optional Fields
 See logs produced in the comment below.

**Related issues:**

**Suggested labels:**

**Comment by Shaaali** [comment]
[logs.txt](https://github.com/wso2/product-is/files/9662892/logs.txt)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
