### ISSUE TITLE
Cross tenant introspection accessibility shouldn't depend on thread local based tenant domain

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#14966]
**Describe the issue:**
With[1] we are using a thread local based tenant domain to identify the tenant during the introspection. But it may lead to some issues if someone consumes this as a java class.  Need to find different approach to solve the issue.

**Expected behavior:**
Need to improve the logic in a way anyone can consume this as a java class.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/14269
https://github.com/wso2/product-is/issues/13683

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
