### ISSUE TITLE
Introduce an oauth-scope-bindings.xml.j2 file to add scope binding via deployment.toml file

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#14971]
**Describe the issue:**

- Up to IS-6.0.0 `oauth-scope-bindings.xml` file is not tempted (ie; doesn't have an oauth-scope-bindings.xml.j2 file)
- Therefore, the user should directly edit the `oauth-scope-bindings.xml` file, if he introduces new permissions with feature customization and he wants to add scope binding for each permission.
- If there is a templated j2 fie which supports adding new scope bindings via deployment.toml file would be easier.

**Comment by AnuradhaSK** [comment]
Need a migration issue for this. If anyone added more configs to `oauth-scope-bindings.xml` file manually, they need to add relevant deployment.toml configs with the introduction of `oauth-scope-bindings.xml.j2`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
