### ISSUE TITLE
The unique identifier of the user doesn’t seem to show the tenant domain

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#1497]
The unique identifier of the user doesn’t seem to show the tenant domain when the flow is tested using a tenants client id

preconditions
1.a tenant should be created :admin@test.com@abc.com
2.a service provider should be created from the tenant

setup
1.email as user name.
2.jdbc user store.
3.mssql data store.

1.Invoke the /authorize end point as a request object call we only pass "openid" as the scope with response_type=code%20id_token
2.decode the id_token using https://jwt.io/
3.The payload is shown as below
{
  "auth_time": 1512473886,
  "exp": 1512477491,
  "**sub**": "admin@test.com",
  "azp": "9nD9L4tr0JJ5FDmT2opch2mDffIa",
  "at_hash": "sldX-WmRyUoquJO2MrCOPA",
  "nonce": "n-0S6_WzA2Mj",
  "email": "admin@test.com",
  "address": "melbourne",
  "aud": [
    "9nD9L4tr0JJ5FDmT2opch2mDffIa"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "preferred_username": "abcd",
  "iat": 1512473891,
  "c_hash": "-drKf29BEt8GT4PiJo7Bhg"
}

Note: assume we have two tenant domains with the same email address we cant determine which tenant domain the sub is related to.

SUB: The unique identifier of the user.
https://auth0.com/docs/tokens/id-token

**Comment by mefarazath** [comment]
You can tell IS to append the tenant domain to the subject identifier by adding the below configuration in the Service Provider --> Local and Outbound Authentication Config

![selection_255](https://user-images.githubusercontent.com/5237653/33622659-7c7a946a-da14-11e7-829b-0c0f67e383cd.png)

**Comment by shavantha** [comment]
the config as explained solved the issue
