### ISSUE TITLE
Add integration tests to verify that we are not logging any sensitive information

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#14984]
**Is your suggestion related to a experience ? Please describe.**
We need to have a way of checking if our logs contain any sensitive information that would pose security vulnerabilities. 

**Describe the improvement**
We should collect all the user-sensitive information we have added for our integration test scenarios, and then, after all the test suites are run, we should check if any of that sensitive info is added to our logs. This would be a separate test suite that would be run at the end of the current test runs.
Here, we should be able to identify the flows in which we are logging PIIs and other sensitive info. We would need to evaluate whether such info is warranted for being logged, if yes, we should whitelist those entries from the test script, and if not, we should fix those logs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
