### ISSUE TITLE
Instructions for the Kubernetes membership scheme are not documented in 6.0 documentation

### ISSUE THREAD

**Issue by Manchiz** [wso2/product-is#14987]
Noticed that instructions for the Kubernetes membership scheme are missing in 6.0 documentation [1]. 

**Describe the improvement**
Document instructions for the Kubernetes membership scheme for 6.0 documentation, as documentation of 5.11 [2]

[1]. https://is.docs.wso2.com/en/latest/deploy/deployment-guide/#clustering-related-configurations

[2]. https://is.docs.wso2.com/en/5.11.0/setup/deployment-guide/#clustering-related-configurations

**Comment by Manchiz** [comment]
Hi Team,

Above mentioned configuration is also missing in IS 5.10 documentation. Could you please look into this as well?

Best Regards,
Sachith.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
