### ISSUE TITLE
client-truststore.jks has invalid/expired certificate for localhost

### ISSUE THREAD

**Issue by grmt** [wso2/product-is#14980]
**Describe the issue:**
Samples do not work using localhost

**How to reproduce:**
try https://localhost:9443/myaccount when running server built using maven

**Expected behavior:**
show login form

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-6.1.0-m1-SNAPSHOT
 - OS: Linux
 - Database: H2
 - Userstore: JDBC H2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by grmt** [comment]
to temporarily solve this issue, make client-truststore.jks a copy of wso2carbon.jks 

cd ./repository/resources/security 
mv client-truststore.jks client-truststore.jks_old
cp wso2carbon.jks client-truststore.jks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
