### ISSUE TITLE
Custom scope validators should not be allowed to filter OIDC scopes 

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#14996]
**Describe the issue:**
In the current scope validation behavior, custom scope validators are allowed to filter OIDC scopes.

**How to reproduce:**

- Write a custom scope validator which will filter all the scopes that is being requested.
- Request `openid` scope.
- OIDC scopes will be filtered by the custom scope validator and IS won't return the id token.

**Expected behavior:**

Custom scope validators shouldn't be able to filter OIDC scopes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
