### ISSUE TITLE
Bring all installation options into the documentation

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#14991]
Currently, some of the installation options such as [1] are currently in the website. 
Suggestion to bring them to the official documentation.

[1] https://wso2.com/identity-and-access-management/install/docker/get-started/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
