### ISSUE TITLE
Link installation instructions from guides

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#15004]
In IS 6 documentation, the guides [1] need a prerequisite pointing users to the installation instructions in the Get Started section.

[1] https://is.docs.wso2.com/en/latest/guides/before-you-start/
[2] https://is.docs.wso2.com/en/latest/get-started/sample-use-cases/set-up/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
