### ISSUE TITLE
Point to official docs from the SDK repos

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#15002]
As discussed in mail thread [1], need to point to the official documentation (in Asgardeo and WSO2 IS) from the SDK repos.

[1] "[Discussion] SDK docs for IS 5.12.0 release"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
