### ISSUE TITLE
[Doc] Rotated refresh token must not extend initial lifetime

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15018]
**Is your suggestion related to a missing or misleading document? Please describe.**
The functionality introduced with https://github.com/wso2/product-is/issues/8312 has to be added into docs. The relevant configuration is mentioned in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1490.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
