### ISSUE TITLE
[Testing] Guides on verification for updated user attributes

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#15014]
The two guides related to enabling verification for updated user attributes [1] should be tested.

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-account-verification-for-an-updated-email-address/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
