### ISSUE TITLE
[Migration] Disable WWW-Authenticate header with realm user field for REST API errors

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#15022]
**Describe the issue:**
With the following PRs we have disabled `WWW-Authenticate` header with `realm user` field for REST API errors.
- https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/212
- https://github.com/wso2/carbon-identity-framework/pull/4285
- https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/214

If you wish to have the previous behaviour where any REST API errors return `WWW-Authenticate` header with `realm user` field, you can enable this by adding this config to deployment.toml file.
```
[rest_api_authentication]
add_realm_user_to_error = true
```

However this will not send the `realm user` field for 401 errors as before to adhere to [1]

[1] https://httpwg.org/specs/rfc9110.html#rfc.section.11.6.1

**Comment by divyaamunugama** [comment]
Related doc PR: https://github.com/wso2-enterprise/migration-docs/pull/86

**Comment by nilminiwso2** [comment]
closing as the docs are added.
