### ISSUE TITLE
Instagram authenticator fails with no valid scope requested error

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#15025]
**Describe the issue:**

Instagram connector returns ‘No valid scopes requested’ error when generating a token.

![Screenshot from 2022-10-12 08-11-42](https://user-images.githubusercontent.com/28682701/195237351-484a8a6b-4c0d-4419-b52a-dfd254577146.png)

**How to reproduce:**
 - Follow the instructions in the [documentation](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Instagram+Authenticator). 

**Expected behavior:**
 - Retrieving the token without any issues. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - Connector version: 1.0.1
 - OS: Linux

---

**Comment by sdnccu** [comment]
I am still getting {"error_type": "OAuthException", "code": 400, "error_message": "No valid scopes requested"}
What exactly the solution?
