### ISSUE TITLE
Issue in Myaccount webapp Spanish translation

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15026]
When we change the locale to `es-ES` the last access time is not translated.
Going further, if the locale is changed to `fr-FR` (which is an OOTB provided locale) the last access time is not translated either.
This seems to be a problem while loading the locale's configuration files.

**Comment by ruwanta** [comment]
It is ok, if this only related to UI level translation. All API, and Storage has to be done in ISO and UTC time.
