### ISSUE TITLE
Template RemoteIpValve in catalina-server.xml.j2 file for IS 5.10.0

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15020]
**Describe the issue:**
`org.apache.catalina.valves.RemoteIpValve` [1] can only be added as a custom valve in the deployment.toml file in WSO2 IS 5.10.0. `RemoteIpValve` needs to be added to the valve list of catalina-server.xml.j2 file to maintain the order [2].

**Expected behavior:**
`RemoteIpValve` should be templated in catalina-server.xml.j2 file.

**Environment information:**
 - Product Version: IS 5.10.0

---

### Optional Fields

**Related issues:**
[1] - https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html
[2] - https://github.com/wso2/product-is/issues/10805
[3] - https://github.com/wso2/product-is/pull/10990
[4] - https://github.com/wso2/product-is/issues/13350

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
