### ISSUE TITLE
Unable to Login Admin Portal when WSO2 identity server instance count is more than 1

### ISSUE THREAD

**Issue by KrishnaRIG** [wso2/product-is#15030]
**Describe the issue:**
We have configured WSO2  Identity server with PostgreSQL database in Azure Kubernetes cluster. Earlier it was working fine with single pod, but recently it started consuming high CPU without any much load. 

So we increased the replicas count by 2 to distribute the load between pods in order to decrease CPU usage. After scaling, the application performance increased as expected. But when we are try to login into wso2 admin portal it is not working. It is redirecting to Login page only.

**Note**: We have integrated WSO2 identity server in our application. Application login functionality is working fine. But when we try to do Signup or forget password operations it is not working because of this wso2 issue. With single pod everything working fine without any issues.

**How to reproduce:**
1. Scale up Kubernetes deployment replicas count by 2.
2. Try to login into WSO2 Admin console. 
3. Signup new user from Web Application.
4. Do forget password from Web Application

**Expected behavior:**
The user will be able to login into Admin portal without any issues.
We are able to perform signup and forget password operations without any issues.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
 - OS: WSO2 container
 - Database: Postgresql 10.4
 - Userstore: JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by rksk** [comment]
The management console (`/carbon`) and account recovery/signup flows uses sessions which are not distributed among the nodes. Therefore. it is required to enable `sticky session` on the load balancer to avoid this issue. It is not a bug, but how the product is implemented at the moment.

Ref: https://is.docs.wso2.com/en/5.10.0/setup/fronting-with-the-nginx-load-balancer/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
