### ISSUE TITLE
Add missing docs on Username and Password recovery 

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#15035]
**Is your suggestion related to a missing or misleading document? Please describe.**
Add the following doc to IS 5.11.0 and 6.0.0 doc space

https://docs.wso2.com/display/IS570/Extending+Username+and+Password+Recovery

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
