### ISSUE TITLE
Map local claim to multiple External OIDC Claims using SOAP Endpoint

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#15038]
**Describe the issue:**
Upon creating external claims using SOAP APIs, it doesn't validate whether the specific local claim is already mapped to an external OIDC claim. This leads to certain inconsistencies in the token retrieved. However, this behaviour is handled as expected in the Management console [1].

**How to reproduce:**
1. Enable admin services.
2. Start the IS.
3. Create an external claim mapping under the OIDC claim dialect to a local claim.
5. Invoke the `https://localhost:9443/services/ClaimMetadataManagementService` SOAP endpoint with `addExternalClaim` action to create another external claim under the OIDC claim dialect to the same local claim,
``` <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://dto.mgt.metadata.claim.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:addExternalClaim>
         <!--Optional:-->
         <xsd:externalClaim>
            <!--Zero or more repetitions:-->
            <xsd1:claimProperties>
               <!--Optional:-->
               <xsd1:propertyName>?</xsd1:propertyName>
               <!--Optional:-->
               <xsd1:propertyValue>?</xsd1:propertyValue>
            </xsd1:claimProperties>
            <!--Optional:-->
            <xsd1:externalClaimDialectURI>http://wso2.org/oidc/claim</xsd1:externalClaimDialectURI>
            <!--Optional:-->
            <xsd1:externalClaimURI>title2</xsd1:externalClaimURI>
            <!--Optional:-->
            <xsd1:mappedLocalClaimURI>http://wso2.org/claims/title</xsd1:mappedLocalClaimURI>
         </xsd:externalClaim>
      </xsd:addExternalClaim>
   </soapenv:Body>
</soapenv:Envelope> 
```

The above returns successful,
``` <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns:addExternalClaimResponse xmlns:ns="http://org.apache.axis2/xsd">
         <ns:return xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
      </ns:addExternalClaimResponse>
   </soapenv:Body>
</soapenv:Envelope> 
```
The same local claim is now mapped to two different external OIDC claims.
<img width="574" alt="claimMapping" src="https://user-images.githubusercontent.com/44939231/195722550-d612ab47-c6da-42a9-902e-d2a31db5e4e5.png">

**Expected behaviour:**
External claim mapping should be validated similar to the Management console [1] to restrict the mapping of the same local claim to multiple external OIDC claims.

**Environment information**
 - Product Version: IS 5.9.0

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt.ui/src/main/resources/web/identity-claim-mgt/add-external-claim.jsp#L83

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
