### ISSUE TITLE
Issues in DB2 Session Data CleanUp Script

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#15033]
**Describe the issue:**

The below issues are identified in the DB2 session data cleanup script[1].

1. @deletedFederatedSessionMappings and @deletedOperationalFederatedSessionMappings variables are not declared. This issue is occurring when creating the procedure.
2. Data type of @Sleeptime variable is VARCHAR(8) and we are passing that variable into dbms_alert.waitone procedure[2]. It is expecting the INT value as the fourth parameter. This issue is occurring when calling the procedure.

**How to reproduce:**
- Setup a DB2 11.5 instance 
- Create Identity DB tables using DB script
- Execute the DB2 session data cleanup script[1]
- Observe the variable declaration missing errors.
- After adding the below missing variable declarations try again to create the stored procedure.
```
 DECLARE @deletedFederatedSessionMappings INT;
 DECLARE @deletedOperationalFederatedSessionMappings INT;
 ```
- Call the Stored procedure and observe the error[2]

```
call SESSION_CLEANUP_SP();
```

**Expected behavior:**
should be able to create and call the DB2 session data cleanup procedure without any issues.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Database: DB2 11.5

[1]https://github.com/wso2/carbon-identity-framework/blob/72595862d0cc0139ba29abaaa27a7ef72f494789/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/db2/sessiondata-cleanup/db2-session-data-cleanup.sql
[2]https://www.ibm.com/docs/en/db2/11.5?topic=module-waitone-procedure-wait-specified-alert
[3]SQL Error [22018]: Invalid character found in a character string argument of the function "INTEGER".. SQLCODE=-420, SQLSTATE=22018, DRIVER=4.26.14
  Invalid character found in a character string argument of the function "INTEGER".. SQLCODE=-420, SQLSTATE=22018, DRIVER=4.26.14
  Invalid character found in a character string argument of the function "INTEGER".. SQLCODE=-420, SQLSTATE=22018, DRIVER=4.26.14

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
