### ISSUE TITLE
Incorrect error messages for locked accounts

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#15040]
**Describe the issue:**
The pop-up that appears when the user account should be updated to provide a meaningful message to the user. 

Currently, the same message is used when the account is locked and when the user enters the wrong password. 

The message displayed when the user account is locked:
![image](https://user-images.githubusercontent.com/84217321/195758409-df74ca6f-b686-48be-95cf-996e9ee9633e.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
