### ISSUE TITLE
UserID is shown in Active Sessions instead of username

### ISSUE THREAD

**Issue by kavinda1995** [wso2/product-is#15049]
**Describe the issue:**
In the user's active sessions view, user id is shown instead of username on last `Active Applications` section. This value is not human readable and better to be changed into show username rather than userId.

<img width="1525" alt="Screenshot 2022-10-17 at 11 34 35" src="https://user-images.githubusercontent.com/19621533/196101998-3d7bd15d-56bd-4f56-8787-076eb203ec5d.png">

**How to reproduce:**
1. Login to console
2. Go to Manage -> Users and select one of the user
3. Go to **Active Sessions** tab
4. Open one of the sessions
5. Check **Active Applications** section

**Expected behavior:**
Username should be shown rather than userID

**Environment information:
 - Product Version: IS 6.0
 - OS: Mac
 - Browser: Microsoft Edge (Chromium)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
