### ISSUE TITLE
  PASTR cookies filling up browser

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15057]
Hi Team,

This issue was observed when using APIM 2.6.0 and the WSO2 IS-KM 5.7.0 as the IDP for SAML2 SSO for client applications. Implicit grant type used generate the token in their client application.

During testing, we observed that the browser keeps the pastr cookies and resends them in each token request. 

We have tested with our test app in the documentation. [1](Playground app) We can reproduce the issue in both scenarios. The step followed are as below.

- Deploy the playground application
- Create an application in the store portal
- Login to the carbon portal and open the "Service Provider" related to the application
- And select code grant in the "Allowed Grant Types" list
- Configure Call back URL: "http://localhost:8080/playground2/oauth2client"
- Save the changes.
- Access the playground application in the browser and fill out the fields as below.
URL: http://localhost:8080/playground2/oauth2.jsp

<img width="1056" alt="194033087-6f0041e7-82d8-4dad-97c8-22c5c80bd345" src="https://user-images.githubusercontent.com/73546297/195407549-d370aa64-40b0-441a-8414-32ce7d283cb7.png">

- Then click on the "Authorize" button
- After that keep opening new tabs in the browser and try accessing the below URL
- https://localhost:8243/authorize?response_type=code&client_id=H6ncaYcnX4skUHd3E_t8YNgtl3Ua&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fplayground2%2Foauth2client
- Then you will be able to see per each new tab there will be one PASTR cookie created
<img width="1056" alt="194033774-daa9e253-9f70-4f50-ac0b-3c6117fd4349" src="https://user-images.githubusercontent.com/73546297/195407612-8773d9b2-b845-44df-afc7-b0c93f22f87b.png">

[1] - https://is.docs.wso2.com/en/5.11.0/learn/deploying-the-sample-app/#deploying-the-playground2-webapp
[2] https://github.com/wso2-enterprise/wso2-apim-internal/issues/749

As a fix we can,

- set a configurable parameter for past cookie max-age
OR
- Remove PASTR and use Session nonce cookie

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
