### ISSUE TITLE
Trying to resolving runtime claim values from userstore/ identity store failed to retrieve values 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#15056]
**Describe the issue:**

- Claims starting with "http://wso2.org/claims/runtime/" prefix which is known as runtime claims are used to populate values in the runtime and use as required,
- But those runtime claim values will not be stored in the userstore/ identity store.

If an application requests a runtime claim and it needs to be added to the id token:

- let's say authorization code grant type is used, the populated runtime claim value is stored in the cache entry of created against the authz code
- Then, use the value from the cache when adding it to the id token https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/eb32bd9e119833ac54334bc5de4a17d28cad6a7d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultOIDCClaimsCallbackHandler.java#L150

If it failed to get attributes from the cache, we check on the user's attribute of userstore. https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/eb32bd9e119833ac54334bc5de4a17d28cad6a7d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultOIDCClaimsCallbackHandler.java#L452
but runtime claim URIs in the requested claim list of SP should not searched from userstore/ identity store. Anyway we don't persists a value for them

More improvements:

- Improve the way we store user attributes and runtime attributes in the cache

**Comment by AnuradhaSK** [comment]
Part of the fix: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1931

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
