### ISSUE TITLE
Support max_age parameter according to OIDC spec completely

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#1505]
Support oidc max_age parameter based on
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

ie. To attempt to reauthenticate if the session is stale for more than max_age value.

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by ppozeti** [comment]
Is it possible to request the auth_time? How?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
