### ISSUE TITLE
Revamp images on IS 6.0.0 doc space

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#15062]
**Is your suggestion related to a missing or misleading document? Please describe.**
Redo the images on the following docs

- https://is.docs.wso2.com/en/5.11.0/learn/configuring-the-policy-administration-point/
- http://127.0.0.1:8000/references/extend/user-mgt/user-store-listeners/
- http://127.0.0.1:8000/guides/identity-lifecycles/self-register-verification/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
