### ISSUE TITLE
Basic authentication fails for secondary userstore users when account locking is enabled

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15070]
**Describe the issue:**
After the fix done for https://github.com/wso2/product-is/issues/14928, basic authentication is failing for the secondary userstore users when account locking is enabled.

A new method has been introduced for the fix to set the failed locked count and user claims are being retrieved in it [1]. However, the user store passed to this method is always the primary user store, hence flow breaks with the user not found error when secondary user store users try to log in without giving a domain name.

**How to reproduce:**

1. Update WSO2 IS 5.11.0 to update level 193.
2. Add a secondary user store.
3. Enable account locking [2].
4. Try to log in to an SP using a secondary user store user without giving the domain name.

**Expected behavior:**
Secondary user store users should be able to log in successfully.

**Environment information:**
 - Product Version: 5.11.0.193

---

[1] - [1] - https://github.com/wso2-support/identity-local-auth-basicauth/blob/support-6.3.11.x-full/components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java#L937-L939
[2] - https://is.docs.wso2.com/en/5.11.0/learn/account-locking-by-failed-login-attempts/#configuring-wso2-is-for-account-locking

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
