### ISSUE TITLE
Configurable Password Expiry time when importing bulk users (eg : CSV import)

### ISSUE THREAD

**Issue by ksankeerth** [wso2/product-is#15071]
**Is your suggestion related to an experience ? Please describe.**
Currently, If we import users using CSV, the password will be valid only for 24hr

**Describe the improvement**

it needs to set the password-active-time at the user creation. Default can be 24 hours, while import tool(and SCIM) can set it to different value.
The code at JDBCUserStoreManager need to be moved to AbstractUserStore manager, and handle the time duration from the request, if not then at the user store config, if not then handle with server config, and at last the hard-coded default (24h)

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
