### ISSUE TITLE
[My Account] Issue with Email Account Verification when Updating Email Address from Security Tab

### ISSUE THREAD

**Issue by IsankaSR** [wso2/product-is#15079]
**Describe the issue:**
`"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"verifyEmail":true}` is missing in the PATCH request payload when updating email address from security secion in My Account.

We can try the email verification function from both **Personal Info** and **Security** sections. Following are respective request payloads,

**Personal Info section**
{"Operations":[{"op":"replace","value":{"emails":["abc@gmail.com"],"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"verifyEmail":true}}}],"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"]}

**Security section**
{"Operations":[{"op":"replace","value":{"emails":["shd@gmail.com"]}}],"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"]}

We can see the `"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"verifyEmail":true}` is missing when updating email address from security secion.

**How to reproduce:**
Doc: https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-account-verification-for-an-updated-email-address/

**Expected behavior:**
`"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"verifyEmail":true}`  should included in the PATCH request payload in both scenarios.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: [Linux]
 - Database: [H2]

**Comment by ravinduramesh** [comment]
Closing the issue as the fix is released.
