### ISSUE TITLE
lastLoginTime is updated if the account is locked

### ISSUE THREAD

**Issue by DumbravaRobert** [wso2/product-is#15072]
**Describe the issue:**
 If an account is locked and the user tries to login using the correct credentials, the "lastLoginTime" is updated but the login fails because the account is locked.

**Affected Product Version:**
          - WSO2 Identity Server 5.11.0
    
**Steps to reproduce:**
 1. The user's account is locked
 2. A login is performed using the correct username and password, but the login will fail because the account is locked
 3. The value of the "lastLoginTime" claim is checked.
 
**Expected behavior:**
 The value should not be updated as the login attempt has failed.

**Comment by DumbravaRobert** [comment]
We've tested the same scenario on wso2 identity server 6.0.0 and we can observe the same issue. Is this planned to be fixed?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
