### ISSUE TITLE
OIDC Dynamic Client Registration API to register applications includes two unrecognized fields

### ISSUE THREAD

**Issue by ChitharaKarunasekera** [wso2/product-is#15089]
**OIDC Dynamic Client Registration API to register applications [1] includes two unrecognized fields**

The OIDC Dynamic Client Registration API [POST] /register API request is not accepted with the two parameters "client_id" and "client_secret" in the request body.

[1]. https://is.docs.wso2.com/en/latest/apis/use-the-openid-connect-dynamic-client-registration-rest-apis/#/OAuth2%20DCR/registerApplication

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
