### ISSUE TITLE
[Epic] Improve the deployment docs

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#15117]
The deployment docs [1] need to be improved;
- Add an Overview page
- Copy editing/rewriting
- Test and review

[1] https://is.docs.wso2.com/en/latest/deploy/get-started/install/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
