### ISSUE TITLE
Remove unnecessary Resources.properties file that exisits in the webapps endpoints

### ISSUE THREAD

**Issue by UpekshaGalappaththi** [wso2/product-is#15111]
**Describe the issue:**

In the Identity Server files there are two Resources.properties files that exist in each webapp in the following locations.

<IS_HOME>/repository/deployment/server/webapps/../WEB-INF/classes/org/wso2/carbon/..../endpoint/i18n 
<IS_HOME>/repository/deployment/server/webapps/../org/wso2/carbon/..../endpoint/i18n 

It seems the file that is actually being used is the one in the WEB-INF folder. Could we remove the unused file?

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: All versions

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
