### ISSUE TITLE
 AuthorizationGrantCache is cleared when the service provider is updated 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15127]
Hi Team,

As mentioned in the title of this git issue, whenever we update a service provider the AuthorizationGrantCache gets cleared[1][2]. In a scenario where a federated user login into the Identity server the user attributes are stored against the token in the AuthorizationGrantCache. If the service provider is updated and thereafter the refresh grant is used, the resulting token would not have any user attributes.

Is there any reason for clearing the AuthorizationGrantCache when the service provider is updated? If not I believe we need to keep these cache entries.

There can be cases like disabling the OAuth app, removing the OAuth config, changing the claims configurations, etc. According to those scenarios, clearing  AuthorizationGrantCache behavior is correct. What we need to improve is the fact we keep the user attributes only in the cache. The cache should not have additional data than what we persist (except for transactional data). Here we have missed using the cache for storage purposes. We can improve the user attributes store process rather than keeping these cache entries.

[1]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L135
[2]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L452

**Comment by ravinduramesh** [comment]
Closing this issue since the 5.10 update is released and the public fix is merged.
