### ISSUE TITLE
Social login failing with NPE

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#15120]
**Describe the issue:**
Social Login is failing with NPE, for the implicit grant type flow.

**How To Reproduce:**
1. Create an OIDC app in the console.
2. Enable implicit grant type
3. Send the authorize request with the request type, `id_token`
4. Use the Sign in with Google option
5. It will be redirected to the error page with following error
   `Error occurred when processing the authorization request. Returning an error back to client.` 

**Expected behavior:**
The social login flow should work for the implicit grant type also without any issue.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
