### ISSUE TITLE
Possible empty username in createLocalAuthenticatedUserFromSubjectIdentifier method

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#15138]
**Describe the issue:**
The [`createLocalAuthenticatedUserFromSubjectIdentifier`](https://github.com/wso2/carbon-identity-framework/blob/v5.23.8/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/model/AuthenticatedUser.java#L132-L165) method returns incomplete `authenticatedUser` object in few scenarios, such as mentioned in #15137, since the negation of [`UserCoreUtil.getDomainFromThreadLocal().equalsIgnoreCase(subjectIdentifierSplits[0])`](https://github.com/wso2/carbon-identity-framework/blob/v5.23.8/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/model/AuthenticatedUser.java#L147-L149) is not handled.

Another step to reproduce this would be,
1. Add the configuration below, in order to reproduce the issue with a minimum number of threads (This happens in high-load environments, however, in order to reproduce this locally, reducing the number of threads would help).
    ```
    [transport.https.properties]
    maxThreads = 2
    ```
3. Initiate the authorization request for an SP configured with an IDP (with the adaptive script provided in #15137).
2. Invoke the SCIM API with a user residing in the secondary user store: US2.
3. Provide the credentials of a user in the userstore: US1. At this stage, `getAssociatedLocalUser(fedUser).username` will be null, since when the `getAssociatedLocalUser` invokes the `createLocalAuthenticatedUserFromSubjectIdentifier` to prepare the `authenticatedUser` object, it returns the `authenticatedUser` without the username due to the reason explained above.

**Environment information**
 - Product Version: IS 5.11.0, IS 6.0

**Related issues:**
#15137

**Comment by mifrazmurthaja** [comment]
The fix for this git issue should also fix the flow mentioned in #15137

**Comment by DInuwan97** [comment]
Related to : https://github.com/wso2/product-is/issues/11977

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
