### ISSUE TITLE
Adding sp cert into truststore is not required in the private key jwt authenticator

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#15132]
**Is your suggestion related to a missing or misleading document? Please describe.**
In this documentation, https://is.docs.wso2.com/en/latest/guides/access-delegation/private-key-jwt-client-authentication-for-oidc/ we are adding sp cert into the truststore. But it is not required if the sp's cert is uploaded or if the SP has  jwks endpoint configured.  

We initially had to upload sp certs into the trustore. So we kept that behavior for backward compatibility https://github.com/wso2-extensions/identity-oauth-addons/blob/master/component/client-handler/src/main/java/org/wso2/carbon/identity/oauth2/token/handler/clientauth/jwt/validator/JWTValidator.java#L407

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
