### ISSUE TITLE
getAssociatedLocalUser returns empty username due to incorrect usage of threadlocal variable

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#15137]
**Describe the issue:**
getAssociatedLocalUser returns an empty username due to incorrect usage of threadlocal variable in the scenario below.

2 Tenants: dom1.com and dom2.com

- dom1.com: OAuth SP (with the adaptive script)--> OAuth IDP, user1 is in secondary userstore: US1, having an associated account: user1 in IDP1 (created the federated association manually).
- dom2.com: testuser in secondary userstore: US2

**How to reproduce:**
1. Add the configuration below, in order to reproduce the issue with a minimum number of threads (This happens in high-load environments, however, in order to reproduce this locally, reducing the number of threads would help).
      ```
      [transport.https.properties]
      maxThreads = 2
      ```
2. Initiate the authorization request for OAuth SP in dom1.com and stay on the login page of IDP.
3. Try to create a user in dom2.com, with a caller in US2: testuser (not required to be an admin), using SCIM API.
Provide the credentials. At this stage, the userstore domain: US2 will be stored in the threadlocal variable at [1].
      ```
      curl --location --request POST 'https://localhost:9443/t/dom2.com/scim2/Users' \
      --header 'Content-Type: application/json' \
      --user 'US2/testuser@dom2.com:pa$$w0rd' \
      --data-raw '{
          "schemas": [],
          "name": {
              "familyName": "familyName",
              "givenName": "givenName"
          },
          "userName": "US2/mjtest1",
          "password": "password",
          "emails": [
              {
                  "primary": true,
                  "value": "mifraz@wso2.com"
              }
          ]
      }'
4. Provide the credentials of user1 on the login page of IDP. At this stage, the userstore domain stored in the threadlocal: `UserCoreUtil.getDomainFromThreadLocal()` will not be equal to the userstore domain received in the `authenticatedSubjectIdentifier` at [2]. Therefore, since the `else` section is not available for [2], the username and the userstore domain will not be set for the `authenticatedUser`. Therefore, getAssociatedLocalUser(fedUser).username will be null, with the adaptive script below.

```
var onLoginRequest = function onLoginRequest(context) {
    executeStep(1,
        {
            onSuccess: function(context) {
            var fedUser = context.currentKnownSubject;
            var currentIdp = context.currentStep.idp;

            Log.info("IDP=" + currentIdp);
            Log.info("FedUser name=" + fedUser.username);
            Log.info("FedUser tenantDomain=" + fedUser.tenantDomain);
            Log.info("FedUser userStoreDomain=" + fedUser.userStoreDomain);

            if (currentIdp == "IDP1") {

                var assocUser = getAssociatedLocalUser(fedUser);

                if (assocUser != null) {
                    Log.info("assocUser name=" + assocUser.username);
                    Log.info("assocUser tenantDomain=" + assocUser.tenantDomain);
                    Log.info("assocUser userStoreDomain=" + assocUser.userStoreDomain);
                } else {
                    Log.info("assocUser is null");
                }
            }
        }
    });
};
```

**Expected behavior:**
`assocUser.username` should return the associated local username.

**Environment information**
 - Product Version: IS 6.0

[1] https://github.com/wso2/carbon-kernel/blob/v4.7.1/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/util/UserCoreUtil.java#L451
[2] https://github.com/wso2/carbon-identity-framework/blob/v5.23.8/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/model/AuthenticatedUser.java#L147

**Comment by mifrazmurthaja** [comment]
Simplified steps are provided in #15138 and fixing #15138 should fix this as well.

**Comment by DInuwan97** [comment]
Related to : https://github.com/wso2/product-is/issues/11977
