### ISSUE TITLE
QSG is not working as expected when trying with steps given in product documentation

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#15136]
**Describe the issue:**

Following scenarios in the QSG [1] are not working as expected when trying with the steps provided in product documentation.
- Federated authentication - When trying the scenario getting `Suspicious login attempt` error page.
- Multi-factor authentication - When trying the scenario getting `Suspicious login attempt` error page.
- Workflows - My account login failure due to ID token validation failure. There's a separate task for removing the workflows from the QSG [2]

**How to reproduce:**
- Federated authentication scenario - Tryout the [Federated authentication scenario](https://is.docs.wso2.com/en/latest/get-started/sample-use-cases/federated-authentication/)
- Multi-Factor authentication scenario - 
   1. Update sample application configurations to set IS endpoints in `localhost.com` domain.
   2. Tryout the [Multi-Factor authentication scenario](https://is.docs.wso2.com/en/latest/get-started/sample-use-cases/multi-factor-authentication/)

**Causes for the failures**
- Federated authentication scenario - Due to SAML sample apps configurations point to IS with `localhost` domain. But google callback is provided in `localhost.com` domain. Due to missing cookies flow ends up in `Suspicious login attemp` error page. This can be fixed by updating sample app. configurations to set IS endpoints in `localhost.com` domain.
- Multi-Factor authentication scenario - Due to 2nd factor authenticator is being served from `localhost` domain.

**Additional Note**
- Root cause for all of the above failures is not properly configuring the IS in `localhost.com` [3] and trying out scenarios expecting IS is hosted in `localhost.com` domain.

**Possible fix**
- Automate IS hostname update to `localhost.com` through QSG script.
- Change IS endpoint configurations in sample applications to `localhost.com` domain.

[1] https://is.docs.wso2.com/en/latest/get-started/sample-use-cases/sample-scenario/
[2] https://github.com/wso2/product-is/issues/14942
[3] https://is.docs.wso2.com/en/latest/deploy/change-the-hostname/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
