### ISSUE TITLE
Some openId Scopes are not excluded for the id token disabled custom grant types

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#15149]
**Describe the issue:**

When obtaining a token from a custom grant type which has id token disabled, IS will only drop the OIDC scope instead of dropping all the OIDC scopes.

**How to reproduce:**

1. Add a new grant type following https://is.docs.wso2.com/en/latest/references/extend/oauth2/write-a-custom-oauth-2.0-grant-type/ and set `IdTokenAllowed=false`
2. Send a request to token endpoint with grant type as custom grant type and several OIDC scopes
3. Response will contain all requested OIDC scopes except for the `openid` scope.

**Expected behavior:**

If the id token is disabled for a grant type, it should drop all the OIDC scopes

**Possible Solution**

Update following code to drop all the registered OIDC scopes in the IS.
https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/44c9aefd44b9e5bcf3794b5797a30086a8c880b4/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/OIDCScopeHandler.java#L53-L61

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
