### ISSUE TITLE
Probably incorrect link at WSO2 Identity Server tutorial

### ISSUE THREAD

**Issue by Asyraaf1** [wso2/product-is#15144]
**Describe the issue:**

- Enable Single Sign-On for an OIDC Web Application: some of the link displayed in the tutorial cannot be used.

**How to reproduce:**

- Tried "8. Enter http://wso2is.local:8080/pickup-dispatch/oauth2client as the Callback Url.". Didn't worked
- When the link changed to http://localhost.com:8080/pickup-dispatch/oauth2client, as like in edited host file, it worked. Same goes to any link contained "wso2is.local" in the tutorial

**Link**
- https://is.docs.wso2.com/en/latest/guides/login/sso-for-oidc/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
