### ISSUE TITLE
Populating UM_USER_ID in UM_USER table is not correct

### ISSUE THREAD

**Issue by DInuwan97** [wso2/product-is#15156]
**The issue in brief**
This issue is regarding the user store type migration. According to the documentation shared below, the SQL query given at 3rd point under the Populating UserIds for the user stories is not correct.

**Background context**
```
ALTER TABLE UM_USER ADD COLUMN UM_USER_ID CHAR(36) NOT NULL DEFAULT 'NONE';
ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID, UM_TENANT_ID);
```
If there is more than one user with one tenant, from the 2nd line onward query, will fail. The reason is from the 1st line, by default the value for the `UM_USER_ID` column is set as `NONE`. Form the 2nd line it is altering the table with a UNIQUE constraint. But if there is more than one user from a tenant, this UNIQUE constraint would violate. From 2nd line onwards query will not be executed.

**Solution**
In order to add the UNIQUE ID feature to the `UM_USER` table the following query would work. Also in the `UM_USER_ATTRIBUTE` table, this query would alter the raws by updating the unique id as the `scimId` attribute.
```
INSERT INTO
UM_USER_ATTRIBUTE (UM_ATTR_NAME, UM_ATTR_VALUE, UM_PROFILE_ID, UM_USER_ID, UM_TENANT_ID)
SELECT 'scimId', UUID(), "default", UM_ID, UM_TENANT_ID
FROM
UM_USER T1
WHERE
NOT EXISTS
(
SELECT 1 FROM
UM_USER_ATTRIBUTE T2
WHERE
T1.UM_ID = T2.UM_USER_ID
AND T2.UM_ATTR_NAME='scimId'
)
GROUP BY UM_ID, UM_TENANT_ID;


ALTER TABLE UM_USER ADD COLUMN UM_USER_ID CHAR(36) NOT NULL DEFAULT 'NONE';


UPDATE UM_USER T1
JOIN UM_USER_ATTRIBUTE T2
ON
T1.UM_ID=T2.UM_USER_ID
AND T2.UM_ATTR_NAME='scimId'
SET
T1.UM_USER_ID=T2.UM_ATTR_VALUE;


ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID, UM_TENANT_ID);
```
---
Instead of having the above hard-coded `scimId`, the following SQL query can append as an inner query into the above. This will ensure correct mapped, even if the mapped attribute has changed into another mapped attribute non-other than `scimId`.

```
SELECT DISTINCT t.ATTRIBUTE_NAME 
   FROM IDN_CLAIM_MAPPED_ATTRIBUTE t 
   WHERE t.LOCAL_CLAIM_ID IN(
   SELECT t2.MAPPED_LOCAL_CLAIM_ID
   FROM IDN_CLAIM_MAPPING t2 
   JOIN IDN_CLAIM t1
   ON t1.ID = t2.EXT_CLAIM_ID 
   WHERE t1.CLAIM_URI ='urn:ietf:params:scim:schemas:core:2.0:id' 
)
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
