### ISSUE TITLE
Util method to check database table presence returns true even if the database doesn't contain the table

### ISSUE THREAD

**Issue by RivinduM** [wso2/product-is#15155]
**Describe the issue:**

The util method `isTableExists` in the FrameworkUtils class[1]  is used throughout the code to check the existence of tables in the database.

But this method checks the entire db server instead of checking the presence of the table in the given db. The reason for the issue is not providing the catalog name or scheme name when searching the table.
 
**How to reproduce:**

1. Set up an IS pack with the previous db scripts which don't contain IDN_OAUTH2_USER_CONSENT and IDN_OAUTH2_USER_CONSENTED_SCOPES tables.
2. Create a temporary database in the same db server.
`CREATE database temp;`
3. Add the two new tables to the temp db.
```
CREATE TABLE IF NOT EXISTS IDN_OAUTH2_USER_CONSENT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    APP_ID CHAR(36) NOT NULL,
    TENANT_ID INTEGER NOT NULL DEFAULT -1,
    CONSENT_ID VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
    UNIQUE (USER_ID, APP_ID, TENANT_ID),
    UNIQUE (CONSENT_ID)
) ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_USER_CONSENTED_SCOPES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONSENT_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL DEFAULT -1,
    SCOPE VARCHAR(255) NOT NULL,
    CONSENT BOOLEAN NOT NULL DEFAULT 1,

    PRIMARY KEY (ID),
    FOREIGN KEY (CONSENT_ID) REFERENCES IDN_OAUTH2_USER_CONSENT(CONSENT_ID) ON DELETE CASCADE,
    UNIQUE (CONSENT_ID, SCOPE)
) ENGINE INNODB;
```
5. Try an authorization flow and verify the debug logs at [2].

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityDatabaseUtil.java#L201-L234
[2]  https://github.com/wso2-support/identity-inbound-auth-oauth/blob/c0e1ea05e388e273565e8c2e5012b109430ffdd5/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuth2ServiceComponent.java#L285-L286

**Expected behavior:**
The method should return false when the exact database doesn't contain a table with the given name.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - Database: MySQL 5.7

---

### Optional Fields

**Related issues:**
https://github.com/wso2-enterprise/wso2-iam-internal/issues/192

**Suggested labels:**

**Comment by mpmadhavig** [comment]
The same issue popped up in the isTableColumnExist[1] method as well.

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkUtils.java#L3215

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
