### ISSUE TITLE
Add new doc to configure SMS OTP provider

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#15153]
Add a doc similar to [1] for configuring SMS OTP provider on WSO2 IS

[1] https://is.docs.wso2.com/en/latest/deploy/configure-email-sending/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
