### ISSUE TITLE
ServiceProviderName gets printed in the audit log even without actions related to a Service Provider

### ISSUE THREAD

**Issue by UpekshaGalappaththi** [wso2/product-is#15166]
**Describe the issue:**
ServiceProviderName gets printed in the audit logs even without actions related to a Service Provider

**How to reproduce:**
Login to the management console, click user's list or or user profile. You will see similar audit logs similar to these.

```sh
TID: [-1234] [2022-11-13 18:29:00,511] [5ca0dff6-f706-4851-afb4-7caf31f82d2e]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:02,749] [fbcfa0da-c17d-4d3b-9c87-7e6f6dcaec83]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-List Target=null Data={"Users":["test1","admin","test2"]} Outcome=Success
TID: [-1234] [2022-11-13 18:29:03,662] [7febe14a-ca17-4874-b472-4b6cf2349e15]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test1 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test1"},"Profile":"default"} Outcome=Success
```

Then login to User Portal and go back to the management console and click a user's profile or list users. Did this multiple times randomly.

```sh
TID: [-1234] [2022-11-13 18:29:55,425] [0521d7c7-e7e8-407e-91e0-9ca259fb5bca]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"ServiceProviderName":"User Portal","Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:55,517] [2010dc34-0bd7-4bc4-93ae-aea962800ba2]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:56,438] [8969ea8c-484c-4ce3-8c52-db0f3d62edb4]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:56,518] [842e7b48-b351-4a50-bf42-fcd5c3868ca3]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-List Target=null Data={"Users":["test1","admin","test2"]} Outcome=Success
TID: [-1234] [2022-11-13 18:29:57,780] [50ee63a5-a8c0-471b-b043-60a2ff489d80]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test1 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test1"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:57,863] [aead9dd2-ed93-4ae9-9f43-533a53c3bb56]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test1 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test1"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:58,812] [852b708a-3f73-4b45-bbdb-61c490be7c85]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test1 Data={"Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test1"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-13 18:29:58,896] [52dc141b-e641-4478-aed2-e4d674e80dd5]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-List Target=null Data={"ServiceProviderName":"User Portal","Users":["test1","admin","test2"]} Outcome=Success
```

As visible in the log the 'ServiceProviderName' in the data section of the audit log message is inputted even without an action that related to an sp. For further testing logging in to another sp and got similar audit logs with both sps randomly and intermittently.

Note not only the user signed in will exhibit this behaviour when his profile viewed. Even the other user's profile view would contain an audit log with a service provider name sometimes. 
```sh
Ex-TID: [-1234] [2022-11-13 18:37:11,917] [1dd95797-e391-4db1-a0c9-07c3b31c9477]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"ServiceProviderName":"User Portal","Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
```

Did not sign in with test2 to an SP once the server started related to these logs. Kindly note no roles were configured and user's contain Internal/everyone role.

Overall this happens intermittently. if the IS is restarted the behaviour does not happen until a user signs in to an SP.
This is an issue with one or more threads containing the earlier accessed service provider name. Further tested with reducing the maxThreads value in the catalina-server.xml file and the issue was reproduced for every log. Refer below logs for the lowered maxThreads results.

```sh
TID: [-1234] [2022-11-14 14:41:53,697] [80f094c3-bb76-456c-b07f-83080331b5ef]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"ServiceProviderName":"User Portal","Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-14 14:41:53,757] [e00a7f4f-74f5-4193-a669-cbd5972b9f91]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"ServiceProviderName":"User Portal","Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
TID: [-1234] [2022-11-14 14:41:54,908] [3178bd18-8929-40e5-b49b-9165d9dac38e]  INFO {AUDIT_LOG} - Initiator=admin@carbon.super Action=Get-User-Claim-Values Target=test2 Data={"ServiceProviderName":"User Portal","Claims":{"http://wso2.org/claims/role":"Internal/everyone","http://wso2.org/claims/lastname":"test2"},"Profile":"default"} Outcome=Success
```

After analyzing the code this issue seems to be occurring at ContextualAuditParams[1]. Here when a user logs in to an SP or does anything with SP related the information will be added to the MDC class[2]. In the normal flow without an sp related behaviour this service provider value should not exist in the MDC class so it will be ignored in the JSON[3]. Intermittently this value exists so the JSON value will be added. This happens due to one or more threads retaining the sp name. That is why the behaviour was reproduced for every log once the thread count was lowered.

**Expected behavior:**
There should not be a 'ServiceProviderName' Data in the audit log Data JSON when a non SP related activity happens.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.10.0

[1] https://github.com/wso2/carbon-identity-framework/blob/v5.25.43/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserManagementAuditLogger.java#L477

[2] https://github.com/wso2/carbon-identity-framework/blob/v5.25.43/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultRequestCoordinator.java#L216

[3] https://github.com/wso2/carbon-identity-framework/blob/v5.25.43/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserManagementAuditLogger.java#L482

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
