### ISSUE TITLE
Resend confirmation email doesn't send an email for usernames with a plus character

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#15163]
**Describe the issue:**
When a username is having a plus character (+) in it, the resend confirmation email will not be sent, since + character will be considered as a space, when the user object is received at [`resendCodePost`](https://github.com/wso2-extensions/identity-governance/blob/v1.4.72/components/org.wso2.carbon.identity.user.endpoint/src/gen/java/org/wso2/carbon/identity/user/endpoint/ResendCodeApi.java#L43) API.

**How to reproduce:**
1. Enable self-registration and invoke the API below.
    ```
    curl --location --request POST 'https://localhost:9443/api/identity/user/v1.0/me' \
    --header 'Authorization: Basic YWRtaW46YWRtaW4=' \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "user": {
            "username": "user+1",
            "realm": "PRIMARY",
            "password": "pa$$w0rd",
            "claims": [
                {
                    "uri": "http://wso2.org/claims/givenname",
                    "value": "kim"
                },
                {
                    "uri": "http://wso2.org/claims/emailaddress",
                    "value": "mifrazmurthaja@gmail.com"
                }
            ]
        },
        "properties": [
            {
                "key": "callback",
                "value": "https://localhost:9443/myaccount/login"
            }
        ]
    }'
    ```
2. Try to login to an application and you'll be provided with an option to resend the confirmation email.
3. Click on the resend option and the message: Email sent successfully will be displayed. However, the email will not be received, since the [`userRecoveryData`](https://github.com/wso2-extensions/identity-governance/blob/v1.4.72/components/org.wso2.carbon.identity.user.endpoint/src/main/java/org/wso2/carbon/identity/user/endpoint/impl/ResendCodeApiServiceImpl.java#L101) will be null, as there is no such user with: `user 1`

**Expected behavior:**
user+1 should be considered as user+1 and the resend confirmation email should be sent.

**Environment information**
 - Product Version: IS 5.11.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
