### ISSUE TITLE
 IDN_OIDC_JTI Table is Growing 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15165]
We have an issue related to IDN_OIDC_JIT table is not getting cleared.

So as per our current implementation for private key JWT client auth, client has to send the JWT assertion to IS and IS stores the JIT of this token in the IDN_OIDC_JIT table [1] [2]. This contains the JWT_ID, EXP_TIME, DATE_CREATED and the JWT_ID is the primary key.

<img width="701" alt="Screenshot 2022-11-07 at 19 29 40" src="https://user-images.githubusercontent.com/113980488/200742880-dcb3285a-2b54-4817-9280-20b24185ef63.png">

And since the JWT_ID is unique, this table is growing each and every time [3]. And in this specific scenario the table has grown almost to 5GB. 

<table style="border-collapse: collapse; width: 604pt;" border="0" cellspacing="0" cellpadding="0" class="mce-item-table"><colgroup><col style="width: 209pt;" /><col style="width: 70pt;" /><col style="width: 47pt;" /><col style="width: 68pt;" /><col style="width: 71pt;" /><col style="width: 68pt;" /><col style="width: 71pt;" /></colgroup><tbody><tr style="height: 15.0pt;"><td style="width: 209pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">TableName</td><td style="width: 70pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">SchemaName</td><td style="width: 47pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">rows</td><td style="width: 68pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">TotalSpaceKB</td><td style="width: 71pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">TotalSpaceMB</td><td style="width: 68pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">UsedSpaceKB</td><td style="width: 71pt; padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">UsedSpaceMB</td></tr><tr style="height: 15.0pt;"><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;"><strong>IDN_OIDC_JTI</strong></td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">dbo</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right"><strong>48521973</strong></td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">4965968</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;"><strong>4849.58</strong></td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">4963912</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">4847.57</td></tr><tr style="height: 15.0pt;"><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">IDN_OAUTH2_ACCESS_TOKEN</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">dbo</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">2825</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">150608</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">147.08</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">53464</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">52.21</td></tr><tr style="height: 15.0pt;"><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">IDN_OAUTH2_AUTHORIZATION_CODE</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">dbo</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">2232</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">35808</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">34.97</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;" align="right">22864</td><td style="padding-top: 1px; padding-right: 1px; padding-left: 1px; color: black; font-size: 11pt; font-weight: 400; font-style: normal; font-family: Calibri, sans-serif; vertical-align: bottom; border: none; white-space: nowrap;">22.33</td></tr></tbody></table><p><br /></p>

And if we use this configuration 

```
[event_listener.properties]
preventTokenReuse= true 
```

If preventTokenReuse is set to true, the same jti cannot be reused regardless of the jwt expiry time. But if this config is set to false, the same jti can be reused once the jwt is expired [4]. 

So, I checked in our clean-up scripts and there is no mention of this table. Since it’s growing I believe we need to clear up this table once the JWTs expire by considering the preventTokenReuse condition.     

[1] https://github.com/wso2-extensions/identity-oauth-addons/blob/master/component/client-handler/src/main/java/org/wso2/carbon/identity/oauth2/token/handler/clientauth/jwt/dao/JWTStorageManager.java#L124
[2] https://docs.wso2.com/display/IS560/Private+Key+JWT+Client+Authentication+for+OIDC
[3] https://github.com/wso2/product-is/issues/7608
[4] https://github.com/wso2-extensions/identity-oauth-addons/blob/master/component/client-handler/src/main/java/org/wso2/carbon/identity/oauth2/token/handler/clientauth/jwt/validator/JWTValidator.java#L264_L284

**Comment by ravinduramesh** [comment]
Reopened the issue as we have to write the cleanup script for MySQL, PostgreSQL, DB2 and Oracle as an improvement.

**Comment by mpmadhavig** [comment]
In the [ReadME](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/README.MD) file the instructions are given as to run this script only if the `preventTokenReuse` config is set to true. 

As per the [specification](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) jti:

> JWT ID. A unique identifier for the token, which can be used to `prevent reuse of the token`. These tokens MUST only be used once, unless conditions for reuse were negotiated between the parties; any such negotiation is beyond the scope of this specification. 

Though the uniqueness of jti can be used to prevent the reuse of the token, to prevent replay attacks, the uniqueness should not be considered for expired tokens. Because when the token is expired whether or not the config `preventTokenReuse` is enabled, the replayed token will definitely by considered as invalid. Hence the jti values in expired token can be considered as allowed.

So as a conclusion, we should not consider the `preventTokenReuse` config to run the cleanup script.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
