### ISSUE TITLE
Wrong error message given for scim schema get by id when custom-user-schema-enabled is disabled 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#15179]
**Describe the issue:**
1 Open <IS_HOME>/repository/conf/identity/charon-config.xml file
2. Set custom-user-schema-enabled to false. `<Property name="custom-user-schema-enabled">false</Property>`
3. Copy the value in `custom-user-schema-uri`
4. Restart the identity server.
5. Execute the following curl command. Change the `urn:scim:wso2:schema` value to the one you have copied in step 3, if you have changed the default one.
```
curl --location --request GET 'https://localhost:9443/scim2/Schemas/urn:scim:wso2:schema' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```
6. The response is:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "only user, enterprise and custom schema are supported",
    "status": "501"
}
```
7. Then the message in "details" is misleading. If the custom-user-schema-enabled is false, the message should be `only user and enterprise schema are supported`. (even fort he custom schema URI/ any other wrong URI)

![Screenshot 2022-11-18 10:45:33](https://user-images.githubusercontent.com/25483865/202631158-1996ef14-5201-47e9-b9a2-2db9713e5491.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-6.0.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
