### ISSUE TITLE
Improvement on Self Sign Up Introspection Code flow

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15170]
**Self Sign Up Validation Code flow.**

In the validation flow, we call validateSelfRegistrationCode. Here we unlock the user. Then we invalidate the code.

**Self Sign Up  Introspection Code flow.**

In the Introspection flow(introduced via [1]), we call userSelfRegistrationManager’s introspectUserSelfRegistration method to introspect the request. There we are calling validateSelfRegistrationCode. Here we unlock the user. 

Here one difference between Validation code flow and Introspection Code flow is in validation Code flow, we will invalidate the code. But both flow unlocks the user.

The doc [2] mentions the points below.

    /validate-code: This API is used to validate the code used by self-registered users.

    /introspect-code: This API is used to validate the code used by self-registered users and retrieve the details.

/Introspection-Code endpoint introduced to validate the code. For example,
In forgot password scenario,

    The user gets a code via Email
    He/She enters the code
    He/She enters his/her new credentials.

Here we need to validate the code in the second step(checks for validity and expiry). Here we need an introspection endpoint.

/Validate-Code endpoint can be used in the self-registration flow.

Thus, unlocking users by sending code introspection endpoints needs to be changed.

[1] https://github.com/wso2-extensions/identity-governance/pull/402
[2] https://is.docs.wso2.com/en/latest/apis/use-the-self-sign-up-rest-apis/#/Self%20Register/post_validate_code

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
