### ISSUE TITLE
[OIDC Flow] Access token response modification

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-is#15180]
**Is your feature request related to a problem? Please describe.**
There is a specification called [SMART on FHIR app launch](https://build.fhir.org/ig/HL7/smart-app-launch/app-launch.html#top-level-steps-for-smart-app-launch) framework for FHIR implementations which defines how a third party app should interact with a FHIR server for end user authentication. This is built on top of openid connect flow with some modifications. 
![OH-SMART-OIDC-flow-2020-12-04-1523](https://user-images.githubusercontent.com/5234677/187898463-58e3487f-57f0-4a5b-8139-f4dbea2ae7c2.png)
In this flow, there is a requirement that access token response should have some contextual values(related to FHIR) as attributes of the access token response returned by the authz server. In this case the decision of whether to include [contextual attributes](https://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context.html#launch-context-arrives-with-your-access_token) is taken by the checking whether specific scopes(launch/patient,launch/encounter) present in the authorization request. Sample authorization request format is shown below.

> Location: https://ehr/authorize?
            response_type=code&
            client_id=app-client-id&
            redirect_uri=https%3A%2F%2Fapp%2Fafter-auth&
            scope=launch+patient%2FObservation.rs+patient%2FPatient.rs+openid+fhirUser&
            state=98wrghuwuogerg97

**Describe the solution you would prefer**
One way to solve this by having an extension point that can be engaged in the access token issue flow to modify the token response by adding additional attributes to the response

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
