### ISSUE TITLE
Missing prometheus metrics in wso2is-5.11

### ISSUE THREAD

**Issue by hari819** [wso2/product-is#15189]
Hello Team,

we have noticed that below metrics which were seen in the 5.10 version of wso2is kubernetes pod are missing in the 5.11 version , even though we can see them in the documentation. Please could you clarify if we can use an alternate metrics for this purpose ,  

**org_wso2_carbon_serviceadmin_numberofactiveservices
org_wso2_carbon_serviceadmin_numberofinactiveservices
org_wso2_carbon_serviceadmin_numberoffaultyservices**

[https://is.docs.wso2.com/en/5.11.0/setup/jmx-based-monitoring/#using-the-serviceadmin-mbean](url)

we use the above metrics in the grafana panel for alerts if wso2is application health is fine or not?
Please could you help,

Thanks,

**Comment by hari819** [comment]
@team, 

please will it be possible to have a look and suggest an alternative ?

Thanks,

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
