### ISSUE TITLE
maskUserNotExistsErrorCode does not work with multiple authentication options

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15187]
**Describe the issue:**
The functionality introduced with https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/63 to mask the UserNotExistsErrorCode (17001), does not work when there are multiple authentication options in the relevant authentication step.  

The fix is applied to the `initiateAuthenticationRequest()` method of the basic authenticator. But when there are multiple options in the given step, `initiateAuthenticationRequest()` method of the authenticator is not executed and identity framework handles the login page URL generation part. Therefore, this `maskUserNotExistsErrorCode` config has to be considered at [[1]](https://github.com/wso2/carbon-identity-framework/blob/d5faf996f01568308810256c4a14932b700e322e/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/step/impl/DefaultStepHandler.java#L919) as well.

**How to reproduce:**
- Add followings to deployment.toml
```
[authentication.authenticator.basic.parameters] 
showAuthFailureReason = true
maskUserNotExistsErrorCode = true
```
- Add basic authenticator and any other local/federated authenticator to the first step
- Try to login with a non-existing username
- The error code 17001 is sent to the login page

**Expected behavior:**
The error code 17001 should be masked and 17002 should be used instead

**Environment information** 
 - Product Version:  IS 5.11.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
