### ISSUE TITLE
When starting the server opensaml http client gets registered instead of apache commons http client

### ISSUE THREAD

**Issue by Bhashinee** [wso2/product-is#1518]
Affected Version : WSO2 EI 6.1.1

Because of bootstrapping OpenSAML library in [1] , it is overriding http client implementation. Hence it is registering OpenSAML http client in a server start up, but the client that should be registered must be org.apache.commons.httpclient. 

[1] https://github.com/wso2-support/wso2-rampart/commit/8e624a5435e0d7be0be5494db9b499e677b1ccba#diff-ced16c6496574ca0f7b5bcaf522251a7R46

Related issues 
https://github.com/wso2/product-ei/issues/1501

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
