### ISSUE TITLE
Users are unable to authenticate via TOTP when the users did not scan and verify after refreshing the QR code

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15199]
Users are unable to authenticate via totp when the users did not scan and verify after refreshing the QR code.

**Steps to reproduce:**
1. Create a user
2. Create a service provider and configure TOTP as the second step
3. Log in to myAccount and scan the QR code and Verify the  TOTP code
4. Again try to configure TOTP via myAccount 
5. Click on "Generate a new code"
6. Click on the cancel button without scanning the QR code
7. Try to log in to the service provider with the token generated for the Previous QR code

**Actual Result:**
Authentication fails

**Expected Behaviour:**
The user should be able to authenticate with the token generated for the previous QR code

After step 5, http://wso2.org/claims/identity/secretkey claim is updated with a new secret and the token generated for the secret key will be invalidated during authentication.
However, we can avoid this behaviour if we update the secret after validating the token.

Product: wso2is-5.11.0

**Comment by inthirakumaaran** [comment]
Tracked in https://github.com/wso2/product-is/issues/15197
