### ISSUE TITLE
Mobile Number Verification for an Updated Mobile Number works without setting verifyMobile claim to true

### ISSUE THREAD

**Issue by dinzie95** [wso2/product-is#15190]
**Is your suggestion related to a missing or misleading document? Please describe.**
Enable Mobile Number Verification for an Updated Mobile Number[1] feature is enabled for users to validate mobile numbers upon updating them in the user profile. This mentions that sending the SMS OTP is skipped when The verifyMobile claim is not set to true in the SCIM 2.0 request. But when this feature is enabled, and a user tries to update the mobile number via user-portal, an SMS OTP is sent to the new number even though verifyMobile parameter is **not sent** in the request body. Therefore a user cannot update the mobile number unless it is validated using the SCIM call, as OTP validation is not implemented at the UI level.

Currently, this feature is only implemented to be supported via APIs (Mobile verification UI is not implemented). Therefore to prevent sending SMS OTP when updated via user-portal, the following config should be added to the deployment.toml file

[identity_mgt.user_claim_update]
use_verify_claim = true

It should be specified that the feature is only implemented via the SCIM APIs. And the above configuration need to be provided in order to prevent breaking the mobile number update functionality in user-portal when the feature is enabled.

---

[1] https://is.docs.wso2.com/en/5.10.0/develop/enable-mobile-verification-for-an-updated-mobile-number/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
