### ISSUE TITLE
SCIM2/Me patch call fails due user search among all the userstores 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15203]
Hi Team,

The SCIM2/Me patch request is failing when there are multiple userstores and some of them are slow. SCIM2 endpoint called with bearer access token. However, the user does not exist in that particular LDAP user store but in a JDBCUserStoreManger and it's trying to iterate the user store manager to get the user claim values.

In the SCIMUserManager component, it is called the `getUserClaimValuesWithID` method with user id. In this method, it will try to get the user using the User ID with the user store domain null. Since the user store domain is null, the abstract user store manager will try to search for the user in all the user stores and eventually will break the flow if one of the user stores fails.

Since the SCIM2/Me endpoint is authorized using the bearer access token and the user is already known at the SCIM2 component, iterating all the user stores to find the user should not happen. It is also wasting resources.

**Steps to reproduce**

 1. Create 2 or more user stores including a JDBCUSerStoreManager and erroneous user store (LDAP with an incorrect password, etc.)
 2. Restart the server.
 3. Create a user in the JDBCUSerStoreManager and get an access token for that user.
 ```
 curl --location --request POST 'https://localhost:9443/oauth2/token' --header 'Content-Type: application/x-www-form-urlencoded' --header 'Authorization: Basic WHBhZDlqTU5NQU1ObURKc01CUFJicHI5dVlRYTo5ZmVYN3dDUmplUkNOcEJJYjZlZGRTSHl0R3dh' --data-urlencode 'grant_type=password' --data-urlencode 'username=john2' --data-urlencode 'password=admin' --data-urlencode 'scope=internal_login'
 ```
 4. Try to invoke the SCIM2/Me patch endpoint (If the user was searched in the erroneous user store first, it will throw a 500 error).  
 ```
 curl --location --request PATCH 'https://localhost:9443/scim2/Me' --header 'Authorization: Bearer aa9b0295-4d4e-3be3-b99b-263a7042e079' --header 'Content-Type: application/json' --data-raw '{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "value": {
        "password": "admin"
      }
    }
  ]
}'
```

**Comment by rksk** [comment]
This issue still occurs for the first time when calling scim/Me patch since the user id to domain mapping is not populated during the authentication, but during password update.

The fix https://github.com/wso2/carbon-kernel/pull/3639 solves this. With this PR, it is persisting this mapping at a point where the domain of a user is known, thereby preventing the iteration through all userstores in search of that user's domain.
