### ISSUE TITLE
Performance improvements to SCIM Roles Patch groups and SCIM Roles GET

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#15207]
**Description**

**Issue 01:**
As mentioned in https://github.com/wso2/product-is/issues/15154, the same performance issue is there for the SCIM Roles GET request when there is a huge amount of users assigned for that role. 

**Issue 02:**
Similar to https://github.com/wso2/product-is/issues/15154, there can be the same performance issue if there is a huge number of groups assigned to a Role. Eventhough this is a highly unlikely scenario, we can improve the performance in this flow as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
