### ISSUE TITLE
Missing index in the UM_USER_ATTRIBUTE table is causing a slowness in the SCIM DELETE operation

### ISSUE THREAD

**Issue by pabasara-mahindapala** [wso2/product-is#15209]
Hi Team,

A missing index in the UM_USER_ATTRIBUTE table is causing a slowness in executing the following query while using the DELETE scim2/Users endpoint.

    DELETE FROM UM_USER WHERE UM_USER_ID = ? AND UM_TENANT_ID=?

It was observed that in a userstore with 6.6 million rows in the UM_USER table and 90 million rows in the UM_USER_ATTRIBUTE table, the SCIM DELETE operation took 15+ seconds. Performance of the query was improved after adding the following index.

    CREATE NONCLUSTERED INDEX [NCIX_UM_USER_ATTRIBUTE_UM_TENANT_ID_UM_USER_ID] ON [dbo].[UM_USER_ATTRIBUTE]
    ([UM_USER_ID] ASC,
    [UM_TENANT_ID] ASC)

This is the query execution plan before adding the index.

![no-index](https://user-images.githubusercontent.com/42961797/203713226-47b618bd-b9a0-40d4-9e28-a78a19043065.png)

Query execution plan after adding the index is shown below.

![index](https://user-images.githubusercontent.com/42961797/203713313-e8cb5b42-6745-4767-a356-77071e1c933f.png)

It seems that this happens because the DBMS does a lookup using UM_USER_ID and UM_TENANT_ID columns in the referencing table UM_USER_ATTRIBUTE. Can we add this index to the product?

**How to reproduce:**
Perform a SCIM DELETE operation for a user in a JDBC userstore

**Expected behavior:**
DELETE query performs faster

**Environment information**
 - Product Version: IS-KM 5.10.0
 - Database: MSSQL
 - Userstore: JDBC

Thanks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
