### ISSUE TITLE
Migration client needs to support Registry and Primary JDBC userstore datastores separately

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#15214]
**Describe the issue:**
Currently, the migration client cannot support two separate DBs for the registry and primary userstore. It can only support separate datasources for IDENTITY, UM, CONSENT, and UMA databases [1], where the UM datasource handles both the registry and userstore entities.

The migration client should be able to support migration of registry and primary JDBC userstores separate, i.e., the migration client should provide configurations for a Registry datasource and Primary JDBC userstore datasources and handle their migrations separately.

 [1] https://github.com/wso2-extensions/identity-migration-resources/blob/69ebaf40700b916693fcc9d8e69d1b48df9824c8/components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/DataSourceManager.java#L88-L96

**Comment by HiranyaKavishani** [comment]
Hi @VivekVinushanth,

Can we get this to merge soon if the fix is verified? once this is merged, We need to port the fix in to [1]  to start migration testing in APIM side.

[1] https://github.com/wso2-extensions/apim-identity-migration-resources/

Thanks!
Hiranya

**Comment by VivekVinushanth** [comment]
The PR will be approved and merged asap.

**Comment by VivekVinushanth** [comment]
Closing this based on fix delivery, the test https://github.com/wso2/api-manager/issues/1213 and the doc change https://github.com/wso2-enterprise/migration-docs/pull/92 are done.
