### ISSUE TITLE
Getting 500 when listing the user list of roles

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#15217]
**Describe the issue:**
1. Connect to the secondary user store.
2. Add the secondary user store user as well as the primary user store user to an internal role.
3. Disconnect the secondary user store
4. Tried to invoke /roles/{role_id} API with the internal role id.
5. You will end up with 500 error code with error message as A user doesn't exist with name:XXXX.

**Comment by sangeethanan** [comment]
This issue is also applicable not just when being disconnected but also, when user is disabled in a secondary store of class `org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager` especially considering this is a read-only type at IS level.

**Comment by BimsaraBodaragama** [comment]
> This issue is also applicable not just when being disconnected but also, when user is disabled in a secondary store of class `org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager` especially considering this is a read-only type at IS level.

The fix in [[1]](https://github.com/wso2/carbon-identity-framework/pull/4349) covers this scenario as well. 

[1] https://github.com/wso2/carbon-identity-framework/pull/4349
