### ISSUE TITLE
 Issue in scope validation flow for not associated  federated users.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15211]
Hi All,

An issue was observed in the scope validation implementation for the federated users (Not associated user) when configuring IDP role mapping with roles which is contain domain names (Internal or User store). According to implementation, it tries to check if the user has the specified role but skips the domain name. In that case, the implementation of  is valid for the Primary role but not the roles that contain the domain name.

**Step to Reproduce**

1. Create an Internal role
2. Bind a new scope to a newly created role
3. Config the IDP, Add role mapping and use the new Internal role as the local role.
4. Try to authenticate a user in IDP with the new scope. 
5. Check the received access token. You may notice the requested scope is not available in the received scope list. 

Product : wso2is-5.10.0

**Comment by Manchiz** [comment]
Hi All,

I developed a custom scope validator, and the problem raised here is already solved there. I have added the fix [1] here for your reference. And if there is something that needs to improve or any other suggestion, please let me know.

[1]. https://github.com/Manchiz/custom-scope-validator/blob/master/src/main/java/org/wso2/custom/scope/validator/CustomScopeValidator.java#L288

Best Regards,
Sachith.
