### ISSUE TITLE
is server 6.0.0 - 403 occurred while using GET scim2/Users endpoint with scope internal_user_mgt_list

### ISSUE THREAD

**Issue by zakyshareef** [wso2/product-is#15212]
Location : https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/

Steps to Reproduce:
Get a access token using client_credentials grant with scope internal_user_mgt_list
Use it to call GET /Users, it returns following error message

{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Operation is not permitted. You do not have permissions to make this request.",
    "status": 403
}

Note : for all scim2 rest apis it returns same error message even with appropriate scope set. but it worked perfectly with basic auth

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
