### ISSUE TITLE
Unable to create user and send email through SCIM2 API when verifyEmail attribute is true

### ISSUE THREAD

**Issue by faizanprogrammer** [wso2/product-is#15210]
**Describe the issue:**
I want to verify the user email and i am trying to create user through SCIM2 API.
However i am getting following error.
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"Error in adding the user: faizan***@hotmail.com. Email address not found for email verification","status":"400"}`

When i don't set verifyEmail in request payload, User is created successfully.

**Note: I am able to create user from management console and email is being set successfully.**
**How to reproduce:**
Call this end point https://localhost:9443/t/carbon.super/scim2/Users as POST request.
Payload:` {"emails":[{"type":"work","value":"faizan***@hotmail.com","primary":true}],"password":"faizan","schemas":[],"name":{"givenName":"Faizan","familyName":"Ali"},"userName":"faizan***@hotmail.com","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"verifyEmail":true}}`

**Expected behavior:**
API should create a user and send verification email.

**Environment information** **:**
 - Product Version: IS 6.0.0
 - OS: Linux
 - Database: H2
 - Userstore: JDBC

---

**Note: `faizan***@hotmail.com` is dummy email and in actual request i am using my valid email.
I verified that claim `http://wso2.org/claims/emails.home` contain the value i am sending while user creation without verifyEmail**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
