### ISSUE TITLE
Unable to use spanish characters for the Service Provider name

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1523]
**Environement**
Standalone 5.4.0 GA pack
JDK - 1.8
DB - H2
OS - Ubuntu 15.10

**Steps to recreate the issue**
1. Register SP by providing the SP name with Spanish characters
ex: Janucá

**Observations**
Unable to user Spanish characters for the SP name
Provided error message is generic and does not reflect whether we support spanish characters or not

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
