### ISSUE TITLE
Refresh Token Call with Internal Scopes Failing

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#15233]
**Describe the issue:**
When we try to invoke a refresh token call with internal_<XXX> scopes, the server returns a 400 with "invalid scope" error message.

**How to reproduce:**
- Create an SP with password grant and refresh token grant enabled.
- Initial token request in password grant.
  ```
  curl -X POST 'https://localhost:9443/t/carbon.super/oauth2/token?grant_type=password&scope=email internal_login internal_role_mgt_view openid profile&username=admin&password=admin' -u <CLIENT_ID>:<CLEINT_SECRET>' ```
- Response
  ```
  {
      "access_token": "2cef26bb-0928-3a80-807e-baf0b84a480a",
      "refresh_token": "040dba25-d016-3627-8f8c-db2c6fe34db3",
      "scope": "email internal_login internal_role_mgt_view openid profile",
      "id_token": "....",
      "token_type": "Bearer",
      "expires_in": 2479
  }
  ```
- Refresh token call.
  ```
  curl -X POST 'https://localhost:9443/t/carbon.super/oauth2/token?grant_type=refresh_token&scope=profile openid internal_login&refresh_token=040dba25-d016-3627-8f8c-db2c6fe34db3' -u <CLIENT_ID>:<CLEINT_SECRET>' ```
- Response
  ```
  {
      "error_description": "Invalid Scope!",
      "error": "invalid_scope"
  }
  ```
- If we use any non-internal scopes sent in the initial request, the refresh token call works as expected. If we use any internal scope, this issue persists.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
