### ISSUE TITLE
Support 'Sign in with Ethereum' via login.xyz integration

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#15243]
**Is your feature request related to a problem? Please describe.**
Login with decentralized identifiers via digital wallets to application is a trend that is being discussed in the identity community forums and implemented by many applications.

https://login.xyz/ (Sign in with ETHEREUM) is a vendor that supports applications to allow users to sign in with their decentralized identifiers on Etherum blockchain. It is led by the Etherum foundation and is backend by a lot of wallet vendors such as metamask (other partners are listed in their website https://login.xyz/)

login.xyz supports standard OpenID connect for any RP to integrate with. This allows any OIDC RP to integrate with them.

**Describe the solution you would prefer**

- Test Sign in with Ethereum (login.xyz) with WSO2 Identity Server
- Document the integration setup
- Provider a dedicated template for login.xyz connection on the `WSO2 Identity Server Console`
- Get ourselves listed in https://docs.login.xyz/integrations as a support integration

**Additional context**
N/A

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
