### ISSUE TITLE
[Improvement] Add a configurable list of values that needs to be omitted from logs.

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#15244]
In the current implementation, we are maintaining a list of key values[1] that need to be omitted from printing in audit logs that are generated in the IDP flows.
As of now, these values are hard coded in the code and it will be an issue to maintain and update them with time. Therefore it would be better if we can make this list configurable.

The suggestion is to add a configurable list, so that can be read from the code and avoid printing them in audit logs.

**Related PR**

- [https://github.com/wso2/carbon-identity-framework/pull/4363](https://github.com/wso2/carbon-identity-framework/pull/4363)

[1] - [https://github.com/wso2/carbon-identity-framework/pull/4363/files#diff-4fed0949c030dd631be3d308dc083d59651dd0a8de20de57735a8961255f575aR47](https://github.com/wso2/carbon-identity-framework/pull/4363/files#diff-4fed0949c030dd631be3d308dc083d59651dd0a8de20de57735a8961255f575aR47)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
