### ISSUE TITLE
Please provide documentation on the callback url when configuring facebook as federated authenticator

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1524]
In [1] currently the value and the dependencies that should exist for callbackurl is not specified. Please include the information.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Facebook+Authenticator#ConfiguringFacebookAuthenticator-Configuringtheidentityprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
