### ISSUE TITLE
[Doc] Mention that a default role is created when creating an SP

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#1525]
When we create an SP a default role is getting added, This needs to be mentioned in the documentation. The included information doesn't clearly mention this.

https://docs.wso2.com/display/IS540/Configuring+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
