### ISSUE TITLE
Improve UI for authenticators

### ISSUE THREAD

**Issue by gershom96** [wso2/product-is#15259]
![Screenshot from 2022-12-06 16-17-29](https://user-images.githubusercontent.com/47293495/206389842-53dafe3b-91f9-4b0b-a041-f76e9c31bbb6.png)

The UI design in the TOTP authenticator where a box is bordered by another box seems odd. Also the continue button being aligned to the left seems a little odd.

The design with a box bordered by another box needs to be changed wherever it is reproduced.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
