### ISSUE TITLE
DB script for for MySQL v'5.7.37' throw an error 

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-is#15251]
**Describe the issue:**

Following the doc reference to set up the MySQL DB
https://is.docs.wso2.com/en/latest/deploy/change-to-mysql/#minimum-configurations-for-changing-default-datasource-to-mysql

when comes to the particular line 

CREATE TABLE IF NOT EXISTS UM_ORG ( 
UM_ID VARCHAR(36) NOT NULL,  
UM_ORG_NAME VARCHAR(255) NOT NULL,            
UM_ORG_DESCRIPTION VARCHAR(1024),             
UM_CREATED_TIME TIMESTAMP NOT NULL,             
UM_LAST_MODIFIED TIMESTAMP NOT NULL,         
UM_STATUS VARCHAR(255) DEFAULT 'ACTIVE' NOT NULL,           
UM_PARENT_ID VARCHAR(36),             
UM_ORG_TYPE VARCHAR(100) NOT NULL,           
PRIMARY KEY (UM_ID),            
FOREIGN KEY (UM_PARENT_ID) REFERENCES UM_ORG(UM_ID) ON DELETE CASCADE )ENGINE INNODB

**trow an error Error Code: 1067. Invalid default value for 'UM_LAST_MODIFIED'**	

the fix was to put the default version for TIMESTAMP fields.

like this 

CREATE TABLE IF NOT EXISTS UM_ORG (
            UM_ID VARCHAR(36) NOT NULL,
            UM_ORG_NAME VARCHAR(255) NOT NULL,
            UM_ORG_DESCRIPTION VARCHAR(1024),
            UM_CREATED_TIME TIMESTAMP NOT NULL **DEFAULT CURRENT_TIMESTAMP,**
            UM_LAST_MODIFIED TIMESTAMP NOT NULL **DEFAULT CURRENT_TIMESTAMP,**
            UM_STATUS VARCHAR(255) DEFAULT 'ACTIVE' NOT NULL,
            UM_PARENT_ID VARCHAR(36),
            UM_ORG_TYPE VARCHAR(100) NOT NULL,
            PRIMARY KEY (UM_ID),
            FOREIGN KEY (UM_PARENT_ID) REFERENCES UM_ORG(UM_ID) ON DELETE CASCADE
)ENGINE INNODB;

**How to reproduce:**
Execute the scripts in the <IS-HOME>/dbscripts/mysql.sql

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: , IS 6.0]
 - Mac
 - Database: MySql '5.7.37'

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
