### ISSUE TITLE
Cannot login to Travelocity when Yahoo is configured as the IDP 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1526]
**Environement**
Standalone 5.4.0 GA pack
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**
1. Run Standalone IS 5.4.0 GA pack
2. Configure Travelocity as a Service Provider using SAML SSO
3. Configure a Yahoo app as in [1] and take the client ID and the client secret
4. Input them under federated authenticator > yahoo configuration
5. Configure yahoo IDP as a Federated authenticator for Service provider
6. Access http://localhost:8080/travelocity.com
7.Click on SAML redirect Binding
8. Provide Yahoo login details
9. Error message will be shown as in [2]

[1]. https://docs.wso2.com/display/IS540/Configuring+Yahoo
[2]. yahoo.png
![yahoo](https://user-images.githubusercontent.com/31848014/33936556-fc7c7612-e025-11e7-8765-504e40852315.png)

**Observations**

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
