### ISSUE TITLE
Doc Feedback: Update the screenshot in setting JAVA_HOME section to show a supported JDK version

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#15264]
Location : https://is.docs.wso2.com/en/latest/deploy/get-started/install/#install-on-solaris

The screenshot that shows how to check whether JAVA_HOME is configured currently shows an unsupported Java version. It'd be better to update this screenshot to show a supported JDK version.

![Screenshot 2022-12-12 at 07 44 08](https://user-images.githubusercontent.com/41533942/206946613-ba5d9c53-71fa-44d1-9624-7ccc7c626e27.png)

**Comment by divyaamunugama** [comment]
To avoid similar issues in the future, we have updated the doc by removing the screenshot.

![image](https://github.com/wso2/product-is/assets/84217321/823e8b2b-312c-4687-8c6a-2ec61cdbf8e6)
