### ISSUE TITLE
Log in to Google using the Identity Server

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#15260]
The following [1] guide is failing.
In the docs, we are configuring email as username and expecting the username to be sent as the subject rather than the user's id.
So there seems to be a default behavioural change between the versions when it comes to the subject (username vs uuid) . In previous version the default subject seems to be username and the docs are written with that assumption.

As an immediate fix, let's update the docs to explicitly set email address or username as subject when configuring the app. 

[1] https://is.docs.wso2.com/en/latest/guides/login/log-into-google-using-is/#configure-google

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
