### ISSUE TITLE
Exclude OpenID connect scopes from scope validation logic

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#15278]
### Is your suggestion related to an experience ? Please describe.
---

Currently during scope validation logic [during authorization flow and token flow], all scopes requested are passed to the scope validation logic. 

However, we are omitting the internal scopes from being passed to the scope validation logic. Thinking behind this has been that internal_* scopes should not be validation/manipulated by scope validation. Thought there are still some ways a scope validator can modify this. We at least have way to separately identify request internal_* scope within the flow.

On the other hand, OpenID connect scopes are still passed to the scope validation logic and have a risk of being overridden or dropped by the scope validators unintentionally. This could cause functionality break in OpenID connect flows.

### Describe the improvement
---
Extract out and remove OIDC scopes from reaching scope validation logic

### Additional context
---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
