### ISSUE TITLE
Support adding multiple signing certificates from IdP SAML metadata

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15271]
**Describe the issue:**
There are identity providers which includes multiple signing certificates in their IdP metadata (to support certificate rotation use cases). Currently it is not supported to import such a metadata file into WSO2 IS since it only extracts the first certificate and ignores the rest.

While processing the IdP SAML metadata, it breaks the signing certificate extraction after one certificate is found at [1]. 

**How to reproduce:**
Upload a IdP SAML metadata file via the management console or REST API which contains multiple signing certificates. Only the first certificate is added to the identity provider and others are ignored.

**Expected behavior:**
All the signing certificates in IdP SAML metadata should be reflected in the created identity provider.

[1] https://github.com/wso2-extensions/identity-metadata-saml2/blob/4d945ccde55583081b2544718421526afbeb3317/components/org.wso2.carbon.identity.idp.metadata.saml2/src/main/java/org/wso2/carbon/identity/idp/metadata/saml2/util/SAML2SSOFederatedAuthenticatorConfigBuilder.java#L355

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
