### ISSUE TITLE
Document explanation for facebook authenticator options

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1527]
Currently in [1] Enable Facebook Authenticator and Default is asked to be checked when configuring. Please explain their behavior when they are on/off with the impact that might be on a particular flow when either on/off

E.g. When default is on, will multi login in federation hub work?

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Facebook+Authenticator#ConfiguringFacebookAuthenticator-Configuringtheidentityprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
