### ISSUE TITLE
Provide explanation on Service provider configuration options

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1529]
Please provide explanation to why we need the following options enabled in the service provider configuration in [1] 

- Enable Attribute Profile
- Include Attributes in the Response Always

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Facebook+Authenticator#ConfiguringFacebookAuthenticator-Configuringtheidentityprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
