### ISSUE TITLE
Organization level password validation management

### ISSUE THREAD

**Issue by kayathiri4** [wso2/product-is#15294]
**Is your feature request related to a problem? Please describe.**
Organization administrators should be able to configure password strength parameters and those should be enforced when the passwords are set by users.

**Describe the solution you would prefer**
Passwords should be of sufficient complexity and secrecy, making it impractical for an attacker to guess. The identity admins of an organization can decide the complexity they want to enforce on the users' passwords. Or else the users themselves can pick a password with strong complexity.
There can be various constraints like

- a minimum length
- contains uppercase and lowercase
- contains numbers
- contains special characters
- unique characters

**Comment by Thumimku** [comment]
tracking via https://github.com/wso2/product-is/issues/16323
