### ISSUE TITLE
Add an integration test to cover custom OIDC scopes features in product-is

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#15295]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**

Need an integration tests to cover the below,

1. Adding a custom OIDC scope in both super tenant and tenant
2. Add attributes to custom OIDC scope
3. Request the customer OIDC scope in authorization_code, implicit and a backchannel grant like password grant
4. Verify custom OIDC scope is returned and attribute assigned to custom scopes can also be obtained in the id_token and userinfo response

**Describe the solution you would prefer**

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
