### ISSUE TITLE
An option to disable the new CORS valve in IS 5.11.0

### ISSUE THREAD

**Issue by Pratheesha97** [wso2/product-is#15291]
**Describe the issue:**
Requesting an option to disable the new CORS valve in IS 5.11.0 when needed as the newly introduced CORS config tomcat valve in 5.11.0 doesn't allow Endpoint-wise CORS configurations.

**How to reproduce:**
Place the following configurations in **<IS_HOME>/repository/conf/deployment.toml**, restart the Server and try to invoke oauth2 endpoints from a different domain (eg: www.google.com).

```
 [[tomcat.filter]]
 name = "CORS"
 class = "com.thetransactioncompany.cors.CORSFilter"

 [tomcat.filter.init_params]
 "cors.allowOrigin"="*"
 "cors.supportedMethods"="GET, HEAD, POST, DELETE, OPTIONS, PATCH, PUT"
 "cors.exposedHeaders"="Location"

 [[tomcat.filter_mapping]]
 name = "CORS"
 url_pattern = "/oauth2/*"
 dispatchers=["FORWARD", "REQUEST"]
```

**Expected behavior:**
With the above configurations in place, it should allow any origin for endpoints with the url pattern "/oauth2/*" while other endpoints continue to block CORS requests.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
