### ISSUE TITLE
Remove the Usages of isTableExists check 

### ISSUE THREAD

**Issue by Anandi-K** [wso2/product-is#15301]
**Describe the issue:**
As suggested in [[1]](https://github.com/wso2-enterprise/wso2-iam-internal/issues/192#issuecomment-1325947693),  the usages of `isTableExists` check should be removed from the public code, as the correct tables should have been created upon setup or migration.

[1] https://github.com/wso2-enterprise/wso2-iam-internal/issues/192#issuecomment-1325947693

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
