### ISSUE TITLE
OIDC Scope Management API doc does not contain information about required scopes

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#15302]
**Is your suggestion related to a missing or misleading document? Please describe.**

The OIDC Scope Management API docs[1], does not contain any information about the required scopes to access each resource.

[1] https://is.docs.wso2.com/en/latest/apis/oidc-scope-management-rest-apis/#openid-connect-scope-management-rest-api-definition

**Describe the improvement**

Required scope for each resource needs to be documented.

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
