### ISSUE TITLE
Ability to provide an app Icon is missing

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#15308]
**Is your suggestion related to an experience ? Please describe.**

Ability to provide an app Icon is missing
![image](https://user-images.githubusercontent.com/37938529/209104216-83b7dc29-0a0b-405a-89d6-76c7ece78e51.png)

Suggested solution:
Need to enable configuring image URL for the application.

**Comment by JayaShakthi97** [comment]
Change is available in `identity-apps-1.6.154`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
