### ISSUE TITLE
Adding dynamic query param values from adaptive scripts for federated authentication

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15300]
**Is your suggestion related to a missing or misleading document? Please describe.**
The documentation for the improvements done with https://github.com/wso2/product-is/issues/8149 and https://github.com/wso2/product-is/issues/8552 are not added

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
