### ISSUE TITLE
[Migration] Enable old adaptive script cookies valid after migration

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#15319]
### Is your suggestion related to a missing or misleading document? Please describe.
- In the setCookie and getCookieValue method we are encrypting and decrypting the cookie values. 

- From this version, We changed the way of encrypting and decrypting to correctly encrypt and decrypt  the cookie values with special characters also. 

- But with this fix, **the cookies before migration will not valid after the migration**. So, the users have to prompt another step and set a new cookie and proceed.
    - Ex : If we use new device based script, after the migration it acts as a  new device ( because old cookies are not valid after migration) and users needs to do the all the steps for authentication. 
    
-  #### To keep the cookies before migration valid after the migration also, We can use the below configuration in the deployment.toml file ####
```
[system.parameter]
enableAdaptiveScriptCookieLegacyMode=true
```
**Note :**  
In IS 5.11.0 and IS 6.0.0, we can use a parameter `encryptWithoutDecoding : true` in the setCookie method and `decryptWithoutEncoding : true` in the getCookieValue method to use the values with special characters as the cookie values. 
If you are using above parameters in these methods with cookie values with special characters, **We should not use the `enableAdaptiveScriptCookieLegacyMode=true` config in the deployment.toml  when we are migrating from 5.11.0 or 6.0.0 to latest**.
-Otherwise, to keep the old cookies valid, We need to use the above configuration.

**Related PR:**
https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/121

**Comment by divyaamunugama** [comment]
Related doc PR: https://github.com/wso2-enterprise/migration-docs/pull/86

**Comment by nilminiwso2** [comment]
Closing this as the docs are added.
