### ISSUE TITLE
Inconsistency in compatible JDK versions

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#15315]
**Is your suggestion related to a missing or misleading document? Please describe.**
The deployment guide for Identity Server only mentions 1.8 JDK as the compatible Java version [1]. Although it is mentioned under Operating Systems Row, it could be missed. 

**Describe the improvement**
The compatible versions should be mentioned under the Java section or a similar link to that of the Operating Systems Row should be included. 

Thanks,
Supeshala

[1] https://is.docs.wso2.com/en/5.10.0/setup/deployment-guide/#environment-compatibility

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
