### ISSUE TITLE
Algoloa search provides two links to the same doc

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#15329]
**Is your suggestion related to a missing or misleading document? Please describe.**
$subject

Affected: IS 5.11.0 and earlier versions

![Screenshot from 2023-01-09 08-35-51](https://user-images.githubusercontent.com/84217321/211235136-2a7a32f7-4b0d-4d52-82df-23f0ee0a0811.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
