### ISSUE TITLE
Provide explanation on how to use the role claim uri in the claim mapping of identity provider

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1532]
In [1] when configuring the claims in IDP there is no indication on what to use for the role claim mapping. Please do provide this information as the user will want to know how to map roles configured in facebook with this.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Facebook+Authenticator#ConfiguringFacebookAuthenticator-Configuringtheidentityprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
