### ISSUE TITLE
User stores will not be created when there are spaces in the domain name

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1533]
Type: Bug
Priority: Highest
Severity: Critical
Release: 5.4.0

**Steps**
1. Create a user store with valid configurations, but the domain name should contain spaces.
eg: domain name = this is a test userstore

**Issue**
Successful message will appear saying the userstore has been created. But, the user store will not be shown/loaded in the management console.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
