### ISSUE TITLE
Make mobile masking regex pattern configurable

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#15338]
**Describe the issue:**
Currently, they are retrieving the recovery channels using this API[1] and this returns the masked mobile number as the Mobile channel value[2].
Make the masking regex pattern configurable via a new claim metadata property (as Additional Properties with the property name as MaskingRegEx) for the mobile claim.

1. Try out the Account Recovery flow with mobile option.

**Expected behavior:**
Similar behavior to same Email masking configuration feature[3] to 5.7.0?

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.7.0

**Related issues:**
https://github.com/wso2/product-is/issues/9036

[1] https://localhost:9443/api/users/v1/recovery/password/init
[2] https://github.com/wso2-support/identity-governance/blob/v1.1.37.11/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/internal/service/impl/UserAccountRecoveryManager.java#L351
[3] https://github.com/wso2/product-is/issues/9036

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
