### ISSUE TITLE
Empty list placeholder is not visible when filtering roles with domain

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15339]
**Describe the issue:**
When filtering roles with `Application Domain` the list of roles are empty. Hence there should be a empty list placeholder indicating the list is empty. Instead here and empty div is displayed.

This behaviour is not visible when filtering with both general search filter and domain filter at the same time.

**Proof**

https://user-images.githubusercontent.com/47152272/211482924-5cfa6603-adfd-4c14-95a1-5ad742476a17.mov

**How to reproduce:**
1. Log into console
2. Goto `Manage` -> `Roles`
3. From the domain filter on the right top corner choose `Application Domain`.
4. You will see the following GUI.

<img width="1512" alt="Screenshot 2023-01-10 at 12 37 13" src="https://user-images.githubusercontent.com/47152272/211484437-0bf1e47a-2327-4dba-9a8c-053a8c47a0d2.png">

**Expected behavior:**
Should display a placeholder which says the list is empty.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0-alpha2
 - OS: Mac
 - Database: Postgres
 - Userstore: jdbc

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
