### ISSUE TITLE
Content that claims WSO2 IS is openid certified should be removed from the docs for the IS versions above 5.4

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#15330]
**Is your suggestion related to a missing or misleading document? Please describe.**

According to OpenID, WSO2 IS 5.4 is a certified OpenID provider [1], but there's no mention about the higher versions. Therefore, it's not correct to say that versions above 5.4 are OpenID certified in the docs [2] 

[1] https://openid.net/certification/#OPs
[2] https://is.docs.wso2.com/en/latest/references/concepts/authentication/intro-oidc/

**Describe the improvement**

Content that claims WSO2 IS is openid certified should be removed from the docs for the is versions above 5.4

### Optional Fields

**Additional context**

![Screenshot 2023-01-09 at 08 46 01](https://user-images.githubusercontent.com/41533942/211235804-988c2b71-ff86-434e-8461-30ff3995b1e0.png)

**Related Issues:**
NA

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
