### ISSUE TITLE
qsg.bat error in Quick Start Guide - WSO2 Identity Server (latest version)

### ISSUE THREAD

**Issue by redcometlpb** [wso2/product-is#15344]
**Describe the issue:**

If you run qsg.bat and select "Scenario 3 - Configuring Multi-Factor Authentication", the actual "Scenario 4 - Configuring Twitter as a Federated Authenticator" will proceed.

**How to reproduce:**

1) execute \IS_SAMPLE_DISTR\IS-QSG\bin\qsg.bat file.

2) "Before running samples make sure the following                                "
"  * Added correct details to the server.properties                            "
"  * Your WSO2 IS and sample applications are running.                         "
"                                                                              "
" If okay to continue, Please press 'Y' else press 'N'                         "

Please enter your answer...y
"Please pick a scenario from the following."
"-----------------------------------------------------------------------------"
"|  Scenario 1 - Configuring Single-Sign-On with SAML2                       |"
"|  Scenario 2 - Configuring Single-Sign-On with OIDC                        |"
"|  Scenario 3 - Configuring Multi-Factor Authentication                     |"
"|  Scenario 4 - Configuring Twitter as a Federated Authenticator            |"
"|  Scenario 5 - Configuring Self-Signup                                     |"
"|  Scenario 6 - Creating a workflow                                         |"
"-----------------------------------------------------------------------------"
Enter the scenario number you selected.

3) input '3' and 'Enter'

4) Twitter-related test contents are printed as below.

Enter the scenario number you selected.3
"-------------------------------------------------------------------"
"|                                                                 |"
"|  We are configuring Twitter as the second authentication        |"
"|  factor. Therefore, you have to register an application         |"
"|  in https://apps.twitter.com/                                   |"
"|                                                                 |"
"|  So please make sure you have registered an application before  |"
"|  continuing the script.                                         |"
"|                                                                 |"
"|  Do you want to continue?                                       |"
"|                                                                 |"
"|  Press y - YES                                                  |"
"|  Press n - NO                                                   |"
"|                                                                 |"
"-------------------------------------------------------------------"
Please enter your answer...

**Expected behavior:**

![image](https://user-images.githubusercontent.com/84110105/211739128-6b09be47-d216-4c24-978d-c5121cbd1799.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by redcometlpb** [comment]
OS : Windows
Product Version IS latest (6.0)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
