### ISSUE TITLE
Missing Configs - Unable to configure and run the pack successfully against MySQL

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#15346]
**Describe the issue:**
On 
https://is.docs.wso2.com/en/latest/deploy/change-to-mysql/

The sample configurations given to configure the deployment.toml file does not work and leads to several errors since now it required to have the `useSSL` parameters in the URL.

**How to reproduce:**

Try to change the default database configurations to MySQL configurations according to the documentation with the given sample configs.
<img width="1498" alt="Screenshot 2023-01-10 at 23 02 56" src="https://user-images.githubusercontent.com/41188245/211741749-de132cdb-4980-453f-8e3a-001606f8c394.png">

**Expected behavior:**

Might need to update the sample configurations to have the `useSSL` parameter as well.
Following configurations were the combinations worked for me.

```
[database.identity_db]
type = "mysql"
hostname = "localhost"
name = "<db name>?useSSL=false"
port = "3306"
username = ""
password = ""
driver = "com.mysql.jdbc.Driver"
```
```
[database.identity_db]
url = "jdbc:mysql://localhost:3306/IS-alpha3?useSSL=false&amp;allowPublicKeyRetrieval=true"
username = ""
password = ""
driver = "com.mysql.jdbc.Driver"
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

 - Product Version:  IS 6.1.0
 - OS:Mac
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mpmadhavig** [comment]
Use the mentioned query params (`useSSL=false&amp;allowPublicKeyRetrieval=true`) only in the dev enviornment.

**Comment by mpmadhavig** [comment]
Tested locally with the above given configs (`useSSL=false&amp;allowPublicKeyRetrieval=true`) and worked fine.
