### ISSUE TITLE
No Audit logs when creating an internal role

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#1534]
There are no Audit logs when creating an internal role. There have to be audit logs for this.

**Comment by yasassri** [comment]
This is applicable to any role with a domain.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
