### ISSUE TITLE
[Doc] Need to Update the Logging in to Salesforce with Integrated Windows Authentication Page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1535]
[1] I was referring to [1] in order to configure Salesforce as the SP for Windows authenticators.
[2] In step 4 under Configuring salesforce, it should updated how to find the domain management section in the salesforce UI. 

We have to go through several steps in order to find the domain management. I have mentioned the steps and attached some screenshot for this.
       1) Login to the newly created salesforce account
       2) click on the setup link in as showed in the screenshot 
![setupsalesforce](https://user-images.githubusercontent.com/14923354/33937483-b631552a-e029-11e7-86e1-16641c36b38c.png)

      3) In the loaded window from above step, click on Settings->Company Settings-> MyDomain
 
![mydomainsetup](https://user-images.githubusercontent.com/14923354/33937610-24e2a906-e02a-11e7-9520-4fabf3e1cdc4.png)

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication

**Comment by shavidissa** [comment]
Hi Yasassri,

I followed the doc and you are able to find My Domain by following what is mentioned in docs.
1. Log in with your new credentials as a Salesforce developer. Do this by clicking the Login link in the top right-hand side of https://login.salesforce.com/.
2. Search for My Domain in the search bar that is on the left navigation panel.
3. Click My Domain.
4. In the page that appears, come up with a name for your domain. You can check if the domain is available by clicking the Check Availability button.

You don't have to click Set up. I guess that is one option too but this way reduces the number of steps :)

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication
