### ISSUE TITLE
SAML app with same issuer created in super tenant cannot be created inside a custom tenant

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15354]
**Describe the issue:**
An issuer used to create a SAML application in the super tenant enviornment cannot be used to create an app inside a custom tenant. But this behaviour is not visible across custom tenants.

**Case 1:**
Super tenant :  Create `saml2-web-app-pickup-dispatch.com` -> `Successful`
Tenant 1: Create `saml2-web-app-pickup-dispatch.com` -> `Not allowed`

**Case 2:**
Tenant 1 :  Create `saml2-web-app-pickup-dispatch.com` -> `Successful`
Tenant 2: Create `saml2-web-app-pickup-dispatch.com` -> `Successful`

<img width="494" alt="Screenshot 2023-01-13 at 14 31 14" src="https://user-images.githubusercontent.com/47152272/212285168-9e9d6b55-0a13-422e-aec0-f86b27af0546.png">

**How to reproduce:**
1. Create a SAML app with xxx.com issuer in the super tenant enviornment.
2. Create a SAML app with xxx.com issuer in the custom tenant enviornment.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - OS: Mac 
 - Database: Postgres
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
