### ISSUE TITLE
SMS OTP after EmailOTP in MFA

### ISSUE THREAD

**Issue by Binara-Sachin** [wso2/product-is#15367]
**Describe the issue:**
In a service provider, when Email OTP is configured as the 2nd factor and SMS OTP is configured as the 3rd factor,
- Skips SMS OTP authentication process if `SMSOTPMandatory` property in `deployment.toml` is set to `false`
- Gives the error `User not found in the directory. Cannot proceed further without SMS OTP authentication.` if `SMSOTPMandatory` property in `deployment.toml` is set to `true`

**How to reproduce:**

1. Setup deployment.toml and Identity Provider configurations for SMS OTP and Email OTP.
2. Create a new service provider and set up Inbound authentication configuration as needed.
3. In Local and Outbound Authentication configurations, set Basic Auth as the first factor, Email OTP as the second factor, and SMS OTP as the third factor.
4. Try to log in to the application.

**Expected behavior:**
The user should be prompted to enter the SMS OTP after entering the correct Email OTP in the login process.

**Environment information**
- Product Version: Tested in IS 5.10.0.197

---
**Cause:**

- As of [1] the user is identified using `username` property in the request.
- If the previous step is `Basic Auth` this does not cause a problem.
- However, if the previous step is Email OTP, which does not return `username` as a quarry parameter, this will cause the SMS OTP Authenticator to fail.

[1] https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/10ebdf7d8a47cb51b512b17704cf22d96e84f7cd/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L186

**Comment by Yoshani** [comment]
According to the existing logic, the username is resolved from the previous authenticator if the previously authenticated authenticator is a Local Authenticator. Otherwise it is resolved according to the Federated Authenticator flow which requires special configurations to work properly. In this case the previous authenticator is EmailOTP which is not a Local Authenticator. Therefore to make this scenario work, the below config should be applied in the `<IS_HOME>/repository/conf/deployment.toml` file.

```
usecase = "local"
secondaryUserstore = "primary"
```

**Comment by Yoshani** [comment]
In this scenario even though the previous authenticator is not a Local Authenticator, ideally the username should be resolved according to the subject attribute step, i.e. basic auth in this case, hence a local authenticator. This fix will be adopted with PR https://github.com/wso2-extensions/identity-extension-utils/pull/40

**Comment by Yoshani** [comment]
Fixed with https://github.com/wso2-extensions/identity-extension-utils/pull/40
