### ISSUE TITLE
Identifying WSO2 Specific Code

### ISSUE THREAD

**Issue by areebniyas** [wso2/product-is#15365]
**Description:**
Currently, we are using basic static analysis tools such as Checkstyle to analyze and identify bugs in our codebase. However, these tools do not cover our company's specific coding and security best practices. After conducting thorough research, we determined that a custom Sonar plugin is the most suitable static analysis tool to meet our needs and cover our custom use cases.

**Describe the solution you would prefer:**
With a custom sonar plugin, we will be able to write custom rules that can be used to detect common WSO2 specific violations and security guidelines. Developers can easily integrate Sonar into their workflow and ensure that their code adheres to WSO2’s coding standards before a code review session.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
