### ISSUE TITLE
[Migration] Documentation and migration client no longer available

### ISSUE THREAD

**Issue by ricardofago** [wso2/product-is#15360]
**Description:**
[Migration resources](https://github.com/wso2-extensions/apim-identity-migration-resources) seem to be missing, GitHub reports "Page not found", is the project gone? Also, most of the documentation from the public channels also seem to have been either removed or stripped down to some generic template, so the specific steps are no longer reachable. Can those resources be found elsewhere? We have been experimenting with updating IS-KM and APIM (from 2.6.0 to 5.11.0/4.1.0, according to the compatibiliy matrix). I have a backup of the documentation but not the tooling. 

![brave_yGORGPlEcf](https://user-images.githubusercontent.com/15381686/212582353-5471cdc1-c698-4588-9155-8491043b3a07.png)

![brave_SFFV4TmLTK](https://user-images.githubusercontent.com/15381686/212582604-359b826b-15f8-403c-8413-a39c4f198281.png)

![brave_nBvr7ag7Dg](https://user-images.githubusercontent.com/15381686/212582526-03783df1-2f09-4471-9b1a-8d3267ab14eb.png)

**Suggested Labels:**
Component/Migration

**Suggested Assignees:**

**Affected Product Version:** 
All from 3.0.0 to 6.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Look up upgrade instructions within setup section for any IS-KM/APIM release in the public documentation.

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
