### ISSUE TITLE
Missing XACML doc issues

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#15369]
**Is your suggestion related to a missing or misleading document? Please describe.**
Missing docs: https://is.docs.wso2.com/en/5.11.0/learn/configuring-access-control-policy-for-a-service-provider/#

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
