### ISSUE TITLE
[Doc] Provide sample input values in configuring passive STS as a service provider.

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1537]
Refer to link [1]. Please mention what are the input values need to be given for the following fields when configuring passive STS as a SP. Provide sample input values.
    Passive STS realm
    Passive STS Wreply URL

[1].https://docs.wso2.com/display/IS540/Configuring+Inbound+Authentication+for+a+Service+Provider#ConfiguringInboundAuthenticationforaServiceProvider-WS-Federation(Passive)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
