### ISSUE TITLE
Improve saml2-bearer-assertion-profile documentation

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15372]
**Describe the improvement**

1.  Add a separate section on how to use, userinfo endpoint when using SAML2 grant type. Also, fix this issue mentioned [here](https://github.com/wso2/product-is/issues/15368#issuecomment-1385613226).

2. To request userinfo using userinfo endpoint, the access token should be a [self-contained access token](https://is.docs.wso2.com/en/5.9.0/learn/self-contained-access-tokens/#!), so that it can contain scope infomation.

3. Client Application should include the needed scope in the token endpoing URL
    - `https://<HOST>:<PORT>/oauth2/token?scope=openid`

This improvement can be included in [saml2-bearer-assertion-profile](https://is.docs.wso2.com/en/latest/guides/access-delegation/saml2-bearer-assertion-profile/) page in a separate section.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
