### ISSUE TITLE
User authentication fails for non uniqueId store managers in IS 6.0.0

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15373]
**Describe the issue:**
User authentication fails for the users in non unique ID user store managers (org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager, org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager, etc.) in IS 6.0.

**How to reproduce:**

1. Start an Identity Server 5.11.0 or a previous version with an off-port configuration.

```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offport = 1
```

2. Add the following configurations to the deployment.toml file of IS 6.0 to enable older user store classes.

```
[user_store_mgt]
allowed_user_stores=["org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager", 
"org.wso2.carbon.user.core.ldap.UniqueIDActiveDirectoryUserStoreManager",
"org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager",
"org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager",
"org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager", 
"org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager", 
"org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager"]
```
3. Start IS 6.0 and connect the LDAP of IS 5.11.0 as a secondary org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager user store.
4. Create a user in the secondary user store and try the password grant.

**Expected behavior:**
User should get authenticated and should be able to get a access token.

**Environment information:**
 - Product Version: IS 6.0.0
 - Userstore: ReadWriteLDAPUserStoreManager, ActiveDirectoryUserStoreManager, JDBCUserStoreManager

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
