### ISSUE TITLE
Fix third-party dependency vulnerabilities for IS 6.1.0

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15376]
**Describe the issue:**
When running the trivy scan, third party dependency vulnerabilities are reported. Need to fix the vulnerabilities of following libraries.

- [x]  com.fasterxml.jackson.core:jackson-databind (kubernetes-membership-scheme-1.0.9.jar)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
