### ISSUE TITLE
An admin using google sign in to login to the console when JIT provisioning enabled.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#15378]
**Describe the issue:**
Since we do not support social logins in Onprem product version IS 6.1 we need to handle the below use case properly.

Where a user who already **has admin permission** tries to login to the console using google sign in where **JIT provisioning enabled.**
Now once the user selects the same email address on google sign in , The existing admin user roles will be updated to have only Internal user role and the user won't be able to login to the console since the permissions are overridden.

https://user-images.githubusercontent.com/41188245/213123243-c5d332ec-b518-469b-8034-5123e08913de.mov

**How to reproduce:**

1. Register Google as a IDP
2. Enable Just-in-Time (JIT) User Provisioning
3. List the available applications from console
4. Select Console
5. Select Google option and add Google as a IDP and click update
6. Logout from console
7. Try to login to an admin account using google sign in (or Google one tap)
8. You will get an error message saying You are not authorized (Note : User previously had Admin role assigned )
9. Try login to Console with via local authantiaction (Username and password)
10. Now again You will get an error message saying You are not authorized
11. Navigate to Management console and check user's Assigned roles
12. Now this user's roles are over ridden and updated to have only "Internal/everyone" role

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 6.1.0
 - OS: Mac
 - Database:  MySQL , H2

---

### Optional Fields

**Related issues:**
[Adding social login support for MyAccount and Console](https://github.com/wso2/product-is/issues/14079)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
