### ISSUE TITLE
Cannot create/update user stores when there are special characters in the domain name

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1538]
Type: Bug
Priority: Highest
Severity: Critical
Release: 5.4.0

**Steps**
1. Create a user store with valid configurations, but the domain name should contain special characters.
eg: domain name = #domain.com

**Issue**
Successful message will appear saying the userstore has been created. But, the user store will not be created/shown/loaded in the management console.

If an already created user store is updated with a special character in the domain name, it will be removed from the userstore list

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
