### ISSUE TITLE
Password reset via console is not working.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#15386]
**Describe the issue:**
Password reset via console application is not working properly in following 2 use-cases.

1. When password policies are enabled the password reset is not working.

https://user-images.githubusercontent.com/41188245/213606234-99bdf5e9-8af1-479f-9247-5d73a994eb0d.mov

2. When user resets both error and success messages will appear.(But the password will update in this scenario.)

![Screenshot 2023-01-20 at 08 59 36](https://user-images.githubusercontent.com/41188245/213611778-153ef51e-7383-47bb-8e81-aa725ca71e7a.png)

https://user-images.githubusercontent.com/41188245/213611320-86153bda-278e-4dcf-8422-78a5c27e303a.mov

**How to reproduce:**

1. Create a new user 
2. Log in to management console
3. Enable password pattern and password history
4. Log in to console and try to change password of the created user

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 6.1.0
 - OS:  Mac
 - Database: H2

---

**Comment by mpmadhavig** [comment]
### Case 1: When password policies are enabled the password reset is not working
- Password policy is not getting validated from the FE level.

Case 2: When user resets both error and success messages will appear.(But the password will update in this scenario.)

**Comment by mpmadhavig** [comment]
Fixed with: https://github.com/wso2/identity-apps/pull/3746

**Comment by mpmadhavig** [comment]
### Tested

https://user-images.githubusercontent.com/47152272/214764208-4f513225-1d14-4bc3-8c72-dc7356120b92.mov
