### ISSUE TITLE
Assigning a role to the user fails when the role exists outside the user search base

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15383]
**Describe the issue:**
Assigning roles to the user fails when the role (group) exists outside of the user search base. This is happening due to the improvement done for doUpdateRoleListOfUser method [1].

User search base: `OU=WSO2,OU=IAMCS,DC=wso2is,DC=local`
```
<Property name="UserSearchBase">OU=WSO2,OU=IAMCS,DC=wso2is,DC=local</Property>
```
User's DN: `CN=36416Isuru Hettiarachchi,OU=CS,OU=WSO2,OU=IAMCS,DC=wso2is,DC=local`

Group search base: `OU=IAMCS,DC=wso2is,DC=local`
```
<Property name="GroupSearchBase">OU=IAMCS,DC=wso2is,DC=local</Property>
```
Group DN: `cn=NotDP,OU=DEV,OU=IAMCS,DC=wso2is,DC=local`

![Screenshot from 2023-01-18 14-01-59](https://user-images.githubusercontent.com/22415272/213421453-4fd14c4f-83a6-4b59-be42-4478bd2f4a3a.png)

An LDAP error code 32 will be thrown when modifying the user entry.

```
[2023-01-18 13:55:42,963] [1947a47e-fde6-472e-96fd-b83adc08b040] DEBUG {org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager} - Error occurred while modifying user entry: CN=36416Isuru Hettiarachchi,OU=CS,OU=WSO2,OU=IAMCS,DC=wso2is,DC=local in LDAP role: cn=NotDP javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100288, problem 2001 (NO_OBJECT), data 0, best match of:
	'OU=IAMCS,DC=wso2is,DC=local'
]; remaining name 'cn=NotDP'
```

**How to reproduce:**

1. Configure an AD user store manager with search bases similar to those below.
```
<Property name="UserSearchBase">OU=WSO2,OU=IAMCS,DC=wso2is,DC=local</Property>
<Property name="GroupSearchBase">OU=IAMCS,DC=wso2is,DC=local</Property>
```
2. Create a user with a DN as below (from the AD side).
```
CN=36416Isuru Hettiarachchi,OU=CS,OU=WSO2,OU=IAMCS,DC=wso2is,DC=local
```
3. Create a group with a DN as below (from the AD side).
```
cn=NotDP,OU=DEV,OU=IAMCS,DC=wso2is,DC=local
```
4. Try to assign the role to the user (assigning a user to the role is working).

**Expected behavior:**
Role should be assigned to the user properly.

**Environment information**

 (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - Database: AD
 - Userstore: ActiveDirectoryUserStoreManager

---

### Optional Fields

**Related issues:**
[1] - https://github.com/wso2/product-is/issues/9078
[2] - https://github.com/wso2/carbon-kernel/blob/d15c77199ae1e2cd60549001abf1162e0e139039/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadWriteLDAPUserStoreManager.java#L1464-L1467

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
