### ISSUE TITLE
Post migration, The UM_USER_ID column data type is not consistent with SQL scripts shipped in the product

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#15388]
**Describe the issue:**
The UM_USER_ID column data type is not consistent with SQL scripts shipped in the product, post-migration.

From 5.10.0 onwards the UM_USER_ID column is added to the UM_USER table to store a uuid for a user, when migrating from an older IS version to 5.10.0 or newer version, the migration client alters the table to add this column, the data type used there is CHAR(36)[1].

If the database scripts are used to setup the databases the datatype for the UM_USER_ID column is VARCHAR(255) and is not consistent with the modification done by the migration client. 

NOTE: It is known that the difference between CHAR and VARCHAR is that the CHAR data type is fixed in length, while the VARCHAR data type supports variable-length columns of data. Even though the migration client adds the column with CHAR(36), it can safely hold the uuid that IS generated by the Identity server, so there are no operational issues because of this inconsistency.

**Expected behavior:**
The datatype should be consistent regardless of whether it is a migrated server or a newly created server.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - Database: [MySQL, MSSQL, .....]

[1]https://github.com/wso2-enterprise/identity-migration-resources/blob/master/components/org.wso2.is.migration/migration-resources/5.10.0/dbscripts/step2/um/mssql.sql#L4

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
