### ISSUE TITLE
Improve the log generated when a non administrator user login fails

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#1539]
*Steps*

1. Create a role with only login permission.
2. Create a user and assign the created role.
3. Now try to login to the console with a incorrect password.

*Issue* : Following log gets printed. Which is misleading. The user is not an Administrator. 
````
TID: [-1234] [] [2017-12-13 17:43:19,350]  WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  Failed Administrator login attempt 'chathura[-1234]' at [2017-12-13 17:43:19,350+0530] 
````

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
