### ISSUE TITLE
Remove Deprecated Utility Method from Kernel

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15391]
**Describe the improvement**
The `deployZipFile` of the Utils.java class in the carbon kernel was deprecated before [1] due to some security concerns.
This method should be removed from the code base since there is no further usage for this.

[1] https://github.com/wso2/carbon-kernel/pull/2449

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
