### ISSUE TITLE
Remove Legacy Codes that are not in use anymore

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15392]
**Describe the improvement**
Some legacy codes (i.e. [1] ), are not in use inside the IS anymore. But since these codes are packed inside the IS, it causes security scanners to detect security vulnerabilities related to them and will be reported as IS vulnerabilities even though they are not used anymore. Therefore such unused legacy code bases should be refactored.

[1] https://github.com/wso2/carbon-kernel/blob/4.9.x/core/org.wso2.carbon.ui/src/main/resources/web/editarea/edit_area_loader.js

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
