### ISSUE TITLE
The idp_role_management.return_only_mapped_local_roles configuration is not honoured in the JWT bearer grant flow.

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/product-is#15404]
**Describe the issue:**
The unmapped role in the identity provider configuration is still getting added to the ID token when using the JWT bearer grant type even though the below configuration has been defined in the IS deployment.toml. It should only include the mapped roles in the ID token since we have added the below configuration and it is working as expected in the SAML2 bearer grant flow.
```
[idp_role_management]
return_only_mapped_local_roles = true
return_only_mapped_local_roles_unmapped_exclusive = true
```
**How to reproduce:**

- Configure the WSO2 IS as the key manager by sharing the databases [1]. You can find the deployment.toml files for both the IS and APIM servers from the [Reproducing_Artifacts.zip](https://github.com/wso2/product-is/files/10484252/Reproducing_Artifacts.zip).

- Added the below configuration in the IS deployment.toml file.

```
[idp_role_management]
return_only_mapped_local_roles = true
return_only_mapped_local_roles_unmapped_exclusive = true
```

- Configure the identity provider for the JWT grant type as mentioned in the document [2]. Then added the role mapping to map the IDP role with the local role (We have created a new role called JWT_ROLE and used it as the local role). Please refer to the below screenshot for the identity provider configuration.
![211448027-7487324b-fba8-480e-a39a-c1c42db96a40](https://user-images.githubusercontent.com/73546297/214169123-1d3e860d-bbd2-4234-81fd-9c26bf61d1b8.jpg)

- Since we have added the above deployment.toml configuration, it should only include the mapped roles in the identity provider configuration to the ID token that generates via the JWT bearer grant.

- Then we have created two service providers as explained in the document [1].

- The service provider configuration for the client credential grant type which uses to generate the assertion token can be found from Reproducing_Artifacts.zip ( external_Oauth_client.xml ).

- The service provider configuration for the JWT bearer grant type can be found from the same Reproducing_Artifacts.zip file ( jwtSP.xml ).

The assertion token is generated by executing the below curl command.

```
curl -k -X POST https://localhost:9444/oauth2/token -u dJwbHsnR3VRV55G6l1RXBeNwJ7ga:a7oBIdAAfWd7FzOFxyXOoNVJiCka \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=openid'
```
- The below curl command is used to generate the ID token via the JWT bearer grant type.
```
curl --location --request POST 'https://localhost:9444/oauth2/token' \
-u nr7ik7BgQpZLrG3pl7ckx2CURxUa:RJPRr0xkwBTLBY4k8tkGEtdPlhMa \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'scope=openid' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer' \
--data-urlencode 'assertion= <Assertion_token>' -k
```

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/#step-1-download-and-install-wso2-is
[2] https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/jwt-grant/

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0
 - OS: Linux
 - Database: MySQL
 - Userstore: JDBC

---

**Comment by nipunsampath** [comment]
We are adding a new config `enable_role_mapping_for_jwt` to the support version of IS 5.11.0 in order to preserve backwards compatibility with this change.  `enable_role_mapping_for_jwt = false` will have the same behavior as before the change. 

However, we will not be adding this config to the master branch since it is redundant unless we need to support backwards compatibility.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
