### ISSUE TITLE
Challenge-answers Rest APIs fails with 500 Internal Server Error

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15403]
**Describe the issue:**
Rest API calls to [GET `/me/challenges`](https://is.docs.wso2.com/en/latest/apis/challenge-rest-api/#/me/getChallengesForLoggedInUser) and [GET `/me/challenge-answers`](https://is.docs.wso2.com/en/latest/apis/challenge-rest-api/#/me/getAnsweredChallengesOfLoggedInUser) fail with 500 Internal Server Error with the following backend log.
```
[2023-01-23 21:30:43,978] [ba4f24a1-2028-445d-b84e-ac9062418cec] ERROR {org.apache.cxf.jaxrs.utils.JAXRSUtils} - No message body writer has been found for class java.util.ArrayList, ContentType: */*
```

**How to reproduce:**

1. Setup challenge questions for admin user following [this](https://is.docs.wso2.com/en/latest/guides/password-mgt/challenge-question/#enable-password-reset-via-challenge-questions).
2. Send a postman GET request to `https://localhost:9443/api/users/v1/me/challenge-answers/` endpoint with Authorization set to `Basic Auth` and with admin, admin credentials.

A 500 Internal Server Error will be received with the following response body
```
No message body writer has been found for class java.util.ArrayList, ContentType: */*
```

**Expected behavior:**
The challenge question answers for the admin user should be received instead of the error.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
