### ISSUE TITLE
Warning message on user attribute info page need to get updated with SCIM2 enterprise schema tab URL

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15406]
**Describe the improvement**
After creating a user attribute, the user will get redirected to user attribute view page. There a warning message is displayed as below in order to let the user know that the created attribute will not be capable of get displayed in the user profile since it doesn't have a SCIM2 mapping. 

This warning message has a link where the user will get redirected to the `SCIM2.0` page `Core schema` tab to create this mapping. This is wrong, as the user need to be redirected to the `Enterprise Schema` tab, so that adding the mapping from here will add the user attribute to the SCIM2 object.

<img width="1512" alt="Screenshot 2023-01-24 at 12 05 27" src="https://user-images.githubusercontent.com/47152272/214227157-d12c2208-322b-4cea-9ca3-616f3d31d54b.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
