### ISSUE TITLE
Configuring queryToCorrelationIdMapping for RequestCorrelationIdValve

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15401]
With the PR https://github.com/wso2/product-is/pull/15400, `queryToCorrelationIdMapping` property of the `RequestCorrelationIdValve` can be configured.

Change the   `queryToCorrelationIdMapping`   in the `<IS_HOME>/repository/conf/deployment.toml` file to the value given
below.
```
[log_correlation]
query_config = "{'customQueryParam1':'Correlation-ID', 'customQueryParam2':'Second-Correlation-ID'}"
```

https://is.docs.wso2.com/en/latest/deploy/monitor/work-with-product-observability/#enable-observability

Related; https://github.com/wso2/product-is/issues/6695

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
