### ISSUE TITLE
[Query] Proceed with configuring a federation hub

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1540]
I am trying to implement solution 15 as given in [1]. Since there is no documentation is there for the particular scenario I have tried this locally with the help of the [2], [3], [4]. But currently I am facing a problem in getting the following implemented

"For all the service provider, the initial authentication will happen via the hub identity provider and once that is done, configure a connector to the 2nd step to do the account linking."

So far I have the following configured
1. IS as the external identity provider of APPM - Federation proxy [2]
2. Another IS as the trusted IDP of the federation proxy - Hub configuration[3]
3. Facebook as an authenticator in hub [4]

Please advice in getting the above given point configured.

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
[2] https://docs.wso2.com/display/APPM120/Configuring+with+an+External+Identity+Server
[3] https://docs.wso2.com/display/IS540/Log+in+to+the+Identity+Server+using+another+Identity+Server+-+SAML2
[4] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Facebook+Authenticator#ConfiguringFacebookAuthenticator-Configuringtheidentityprovider

**Comment by sagara-gunathunga** [comment]
@erandidesilva  This is a documentation issue, please apply the correct label for documentation issues. In GitHub issues it's vital to have proper labeling  because our monitoring is based on labels.

**Comment by erandidesilva** [comment]
@sagara-gunathunga: Actually i reported this issue as a query to get feedback on solving the problem I am having because there is a documentation gap and it's been addressed separately. AFAIK the label type of a question is raised when a user is having a question and wants to get it addressed by the team to proceed further.

**Comment by kavithasub** [comment]
@erandidesilva , 
AFAIU the solution, the problem analyzed in the last point is to having multiple federation authenticators & multiple accounts from those for same users. Which means we should have configured those multiple IDPs at federation hub to support authentication for user/s who try to login to various federation proxy, and further we should give option for user to login from their prefered account. I think you can follow the  multi option federation explained here [1] and federation user acocunt association here [2].
Could you able to tryout this?

[1] [https://docs.wso2.com/display/IS540/Multi-factor+Authentication+for+WSO2+IS#Multi-factorAuthenticationforWSO2IS-Configuringmulti-factorauthenticationforWSO2IdentityServer]
[2] [https://docs.wso2.com/display/IS540/Associating+User+Accounts#AssociatingUserAccounts-ManagingfederateduserIDs]

**Comment by erandidesilva** [comment]
@kavithasub 
Thank you for the information. In this particular sample, what I am trying to do is to let the user log in to a federation proxy using a authentication of his choice (facebook, google, etc...) and as I have already configured those as IDP and federated authenticators in hub. Now what I want to achieve is the following

User load app store -> chose login -> redirected to hub -> given multiple options to login -> choses as desired -> logged in (user should be provisioned to hub through JIT)

Since the federation proxy itself is a configured collection of app manager and wso2 is, I really cannot picture where to set in the above directed configs which uses a dashboard which can be any third party app because it's a customizable portal.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
