### ISSUE TITLE
Decouple password reset notification in recovery flow and account activation notification in ask password flow

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#15413]
**Describe the issue:**
As of now in the `Ask Password` flow when the new password is set for the user account, an email notification is being sent with the subject 'WSO2 - Password Reset Successful' if `Notify when recovery success ` is enabled under the `Account Recovery` Section.
From the improvements [1] and [2], a new email template was introduced for this flow. This new flow will work only if the email template is available in the system. 

However since keeping the backward compatibility, password reset success email will be sent to the user when the Notify when recovery success under the Account Recovery Section is enabled and if the newly introduced email template is available in the system.

Create this git issue to track the improvement to add this email template to the system and decouple the password set/reset email notfication from ask password flow and recovery flow based on the configurations enable/disable under the respective scenario.

**How to reproduce:**

- Enable ask password flow - Refer https://is.docs.wso2.com/en/5.11.0/learn/creating-users-using-the-ask-password-option/#on-boarding-with-ask-password
- Enable `Internal Notification Management` in ask password section
- Enable `Notify when recovery success` under account recovery section in resident idp configurations
- Create a user using ask password option and set the new password to activate the account
- You will receive the 'WSO2 - Password Reset Successful' email notification
- Then add the newly introduced email template - accountActivation
- If this template available, then the` Account Activation ` email will be sent when set the new password.

**Expected behavior:**
In upcoming releases better to decouple the password set/reset email notfication from ask password flow and recovery flow based on the configurations enable/disable under the respective scenario.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

- https://github.com/wso2/product-is/issues/15336
- https://github.com/wso2/product-is/issues/15167

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
