### ISSUE TITLE
[Configure Service Provider] Need to add information on finding mapped claims values

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1541]
**Documentation**: Configuring a Service Provider [1].

**Issue Identified**:  Under the section "Claim mapping", it has a detailed description of claims. But the user may get an issue, that how we are gonna check out values that mapped with claims. 

In Travelocity app, it may show values. But when we are going to use something different, it may cause an issue of finding values mapped with claims.

[1] https://docs.wso2.com/display/IS540/Configuring+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
