### ISSUE TITLE
Identifier first login with multiple attribute login does not work for tenants

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#15422]
**Describe the issue:**

Identifier first login with multi attribute login does not work for tenants when the multi attribute login feature is enabled for the super tenant.

**How to reproduce:**

- Add the following configs to the deployment.toml.

```[authentication.authenticator.user_identifier]
name = "IdentifierExecutor"
enable = true

[authentication.authenticator.user_identifier.parameters]
validate_username = true

[system_applications]
read_only_apps = []
```
- Login as as the super tenant admin and enable multi attribute login in the super tenant.

- Edit the myaccount application to have the first step as identifier first with the username/password as the second step.

- Create a tenant and log into the tenant.

- Enable multi attribute login in the tenant.

- Try to login to the myaccount application using the tenant admin or a tenant user. It fails in the identifier first step with the following error. 

![image](https://user-images.githubusercontent.com/33062368/214811978-d376f8b8-5b51-4c1b-895f-e8fffcbd4401.png)

As far as I saw, the a wrong tenant domain is provided from the context. So, even if we login as admin@abc.com, it takea the tenant domain as carbon.super in which the user cannot be found.

**Expected behavior:**

Identifier login should work without an issue with multi attribute login even if it is concurrently enabled in the super tenant.

**Environment information:**
 - Product Version: 6.1.0 RC1
 - OS: Ubuntu 20.04.3 LTS
 - Database: Default H2
 - Userstore: JDBC

---

**Comment by Yoshani** [comment]
Fixed by:
- PR https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/172
