### ISSUE TITLE
Make the Crypto Provider configurable

### ISSUE THREAD

**Issue by ChanikaRuchini** [wso2/product-is#15428]
**Describe the issue:**

Problem
FIPS (Federal Information Processing Standard) [1] is a standard created by the National Institute of Standards and Technology’s (NIST’s) Computer Security Division, FIPS established a data security and computer system standard that organizations must adhere to per the Federal Information Security Management Act of 2002 (FISMA).

When investigating the WSO2 products, it was identified that the Bouncy Castle JCE (Java Cryptographic Extension) provider which is not a FIPS compliant JCE provider is hard coded in most of the products and used as the crypto provider for various use cases. Apart from that, the BC is used as a third party dependency in few scenarios throughout WSO2 products such as certificate revocation (OCSP, CRL), Certificate generation and signing, etc.

As the first step of making the WSO2 products FIPS complaint it was decided to remove the hardcoded use cases of BC as a JCE provider and make it configurable through either a system property or a configuration.

[1] https://csrc.nist.gov/publications/detail/fips/140/2/final

Solution
The usages where the org.bouncycastle.jce.provider.BouncyCastleProvider is hardcoded should be configurable along with the "BC" string which is passed as the crypto provider for different usecases.

**Comment by melanisilva** [comment]
- [ ]  Is this document impacted?
- [ ]  Is the end-to-end (e2e) testing complete?
- [ ]  Are unit tests available?
- [ ]  Are integration tests available?
- [ ]  Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
- [ ]  Has the cloud readiness been verified?

@ChanikaRuchini Could we please have this checklist updated?

**Comment by ChanikaRuchini** [comment]
- [x] Is this document impacted?https://github.com/wso2/product-is/issues/15593

- [ ] Is the end-to-end (e2e) testing complete?  --> Not applicable for this feature

- [x] Are unit tests available? -->  Not applicable

- [ ] Are integration tests available? --> No. There are no integration tests available for enabling fips compliance.

- [x] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)

- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?

- [ ] Have demo sessions been completed? (If yes, please attach the recording link)

- [ ] Has the cloud readiness been verified?

**Comment by hwupathum** [comment]
There are hardcoded JCE provider usages in carbon-identity-framework that needs to fixed

1. https://github.com/wso2/carbon-identity-framework/blob/master/components/user-store/org.wso2.carbon.identity.user.store.configuration.deployer/src/main/java/org/wso2/carbon/identity/user/store/configuration/deployer/util/UserStoreUtil.java#L71
2. https://github.com/wso2/carbon-identity-framework/blob/master/components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/SecondaryUserStoreConfigurationUtil.java#L152
3. https://github.com/wso2/carbon-identity-framework/blob/master/components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/SecondaryUserStoreConfigurator.java#L97
