### ISSUE TITLE
For SaaS applications, identifier first authenticator is not working for tenanted users when multi-attribute login is enabled

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#15423]
**Describe the issue:**
Need to validate this scenario whether the identifier first authenticator is supposed to be used in SaaS applications for tenanted users.

**How to reproduce:**
Create a SaaS application in the super tenant. (You can update MyAccount as well)
Enable multi attribute login from the resident IDP configs.

Edit the authentication configuration as: 

step 1 - identifier first
step 2 - any

Now, create a tenant. (eg: abc.com)
Log in to the tenant and create a user in the tenant (kate)

Try to login to the SaaS application using kate@abc.com.

**Expected behavior:**
the tenanted user should be able to proceed to the second step of the authentication sequence.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-6.0.0, IS-6.1.0-RC1

**Comment by ashensw** [comment]
Duplicate https://github.com/wso2/product-is/issues/15422

**Comment by Yoshani** [comment]
Fixed by:
- PR https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/172
