### ISSUE TITLE
sendError() method is not used to display the UI error in tenants

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#15421]
**Describe the issue:**

In the adaptive authentication JS reference documentation at [1](https://is.docs.wso2.com/en/5.11.0/references/adaptive-authentication-js-api-reference/#senderrorurlparameters), the sendError() method takes in the status and statusMsg as parameters. However, these details are not shown in the UI error page for tenant applications.

**How to reproduce:**

- Create a tenant
- Login to the new tenant and add a SP with an inbound authentication mechanism.
- Go to Local & Outbound Authentication Configuration -> Advanced Configuration -> Add Authentication Step (Add basic authentication)
- Add the following script to the Script Based Adaptive Authentication section and click on Update.
```
var rolesToStepUp = ['admin', 'manager'];

var onLoginRequest = function(context) {
    executeStep(1, {
        onSuccess: function (context) {
            // Extracting authenticated subject from the first step
            var user = context.currentKnownSubject;
            // Checking if the user is assigned to one of the given roles
            var hasRole = hasAnyOfTheRoles(user, rolesToStepUp);
            if (!hasRole) {
                    sendError('',{'status':'000403','statusMsg':'You are not allowed to login to this app.'});
            }
        }
    });
};
```

- Now create a user without any roles mentioned in the above script.
- Login to the SP with the created user and you will be redirected to the retry.do page with the following message.
![error msg](https://user-images.githubusercontent.com/19262008/214486115-b65843f8-a9bf-4c61-9853-b6b6ae3bb9a4.png)

**Expected behavior:**

  Error page should display the error message configured in the adaptive script sendError() method.

**Environment information** 
 - Product Version: IS 5.11.0
 - OS: Linux
 - Database:  H2
 - Userstore: LDAP

---

### Optional Fields

Also you can see the following access log with 404 code.

`
127.0.0.1 - - [25/Jan/2023:10:50:06 +0530] GET /t/test.com/api/identity/auth/v1.1/data/AuthenticationError/51f0c518-db2c-4d62-9ea1-c5e3bcc73da3 HTTP/1.1 404 47 "-" "Java/11.0.2" 0.007
`

But if the same request is made to super tenant domain, we can get the expected error message.

**Related issues:**
[#13159](https://github.com/wso2/product-is/issues/13159)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
