### ISSUE TITLE
[Doc] Wrong information in "Logging in to Salesforce with Integrated Windows Authentication" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1542]
I'm referring [1] in order to configure salesforce with IWA authenticators.

There in Step 8 under configuring salesforce section,
You need to update the value of the **Entity Id** http://saml.salesforce.com into **https://saml.salesforce.com.**

If we add it as "http" ,when saving the values, it will show an error as below image

![httpscreenshot](https://user-images.githubusercontent.com/14923354/33940292-658ae540-e034-11e7-9a8a-14330d3704de.png)

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
