### ISSUE TITLE
Introduce the ability to dynamically register and use multiple login resolvers at the same time

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#15439]
**Is your suggestion related to an experience ? Please describe.**

With the introduction of the multi-attribute login feature [1], we have introduced a mechanism to resolve users based on a regex pattern [2]. This mechanism can be used to achieve custom use cases such as reducing the constant user store search process that happens when there are multiple user stores and etc.. However, this is restricted by both the back-end and front-end implementation. In the back-end implementation, it currently does not support plugging additional resolvers since the service is consumed with a 1..1 cardinality [3] and/or no configuration or priority concept is introduced. From the front-end point of view, the end user does not have the ability to configure the preferred login resolver of their choice in the resident identity provider configurations.  

**Describe the improvement**

Since there is an overlap between the concept of multi attribute login and login resolvers, the first step is to isolate the login resolver concept and make use of the existing regex based resolver to achieve the multi attribute login feature. The proposed package changes are as follows.

| Repository      | Old Package | Proposed New Package    |
| :---:        |    :----:   |          :---: |
| [carbon-identity-framework](https://github.com/wso2/carbon-identity-framework)      | org.wso2.carbon.identity.multi.attribute.login.mgt       | org.wso2.carbon.identity.login.resolver.mgt   |
| [identity-governance](https://github.com/wso2-extensions/identity-governance)   | org.wso2.carbon.identity.multi.attribute.login.resolver.regex        | org.wso2.carbon.identity.login.resolver.regex      |
| [identity-governance](https://github.com/wso2-extensions/identity-governance)   | org.wso2.carbon.identity.multi.attribute.login.service        | org.wso2.carbon.identity.login.resolver.service      |

_Note: The classes in the old packages should be made backward compatible and deprecated so that those can be removed in a future release._ 

Afterwards, a proper logic should be added to consume multiple login resolvers (an example source code section to achieve the requirement is provided below).

```
@Reference(
        name = "LoginResolver",
        service = LoginResolver.class,
        cardinality = ReferenceCardinality.MULTIPLE,
        policy = ReferencePolicy.DYNAMIC,
        unbind = "unsetLoginResolver"
)
protected void setLoginResolver(LoginResolver loginResolver) {

    LoginResolverServiceDataHolder.getInstance().addLoginResolver(loginResolver);
}

protected void unsetLoginResolver(LoginResolver loginResolver) {

    LoginResolverServiceDataHolder.getInstance().removeLoginResolver(loginResolver);
}
```

Even if the back-end implementation might be completed with the above changes, there should be an UI option that enables the end user to select login resolvers through the management console or the console application. This can be handled by adding proper configurations to the new handler class. A sample comparison of the UI before and after the proposed solution is added below.

_Before Proposed Change_

![image](https://user-images.githubusercontent.com/33062368/215729542-3c624c5f-c059-4e1c-855c-1033fa44526b.png)

_After Proposed Change_

![image](https://user-images.githubusercontent.com/33062368/215729807-e42bc2ba-3bec-40de-8578-d175dd83d546.png)

The final change is to pick the proper login resolver at runtime based on the user selection in the resident identity provider configurations. For that we can use a sample source code section such as the follows.

```
public static LoginResolver getSelectedLoginResolver(String tenantDomain) {

        String selectedLoginResolverClass = StringUtils.EMPTY;
        try {
            selectedLoginResolverClass = getConnectorConfig(LoginResolverServiceConstants.LOGIN_RESOLVER_CLASS,
                    tenantDomain);
        } catch (IdentityEventException e) {
            log.error("An error occurred while retrieving login resolver class property.", e);
        }

        List<LoginResolver> loginResolverList = LoginResolverServiceDataHolder.getInstance().getLoginResolverList();
        if (!loginResolverList.isEmpty()) {
            if (StringUtils.isBlank(selectedLoginResolverClass)) {
                selectedLoginResolverClass = LoginResolverServiceConstants.DEFAULT_LOGIN_RESOLVER_CLASS;
            }
            for (LoginResolver loginResolver : loginResolverList) {
                String loginResolverName = loginResolver.getClass().getCanonicalName();
                if (loginResolverName.equals(selectedLoginResolverClass)) {
                    return loginResolver;
                }
            }
        } else {
            if (log.isDebugEnabled()) {
                log.debug("There are no login resolvers registered to be used. This is an un-expected situation " +
                        "because even the default login resolver has not be registered.");
            }
            return null;
        }

        if (log.isDebugEnabled()) {
            log.debug(String.format("A login resolver with the provided login resolver class %s.",
                    replaceCRLFWithUnderscore(selectedLoginResolverClass)));
        }
        return null;
    }
```

With the above changes this improvement should be completed with success. However, the edge components mentioned below should be updated to use the new changes. Furthermore, the documentation should be updated to match the new implementation.

- https://github.com/wso2-extensions/identity-local-auth-basicauth
- https://github.com/wso2-extensions/identity-local-auth-api
- https://github.com/wso2-extensions/identity-outbound-auth-requestpath-basicauth
- https://github.com/wso2-extensions/identity-inbound-auth-oauth

[1] - https://is.docs.wso2.com/en/latest/guides/login/multi-attribute-login/
[2] - https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.multi.attribute.login/org.wso2.carbon.identity.multi.attribute.login.resolver.regex/src/main/java/org/wso2/carbon/identity/multi/attribute/login/resolver/regex/RegexResolver.java
[3] - https://github.com/wso2-extensions/identity-governance/blob/3c60f4a586579c38a8da135d942c5858d804dd51/components/org.wso2.carbon.identity.multi.attribute.login/org.wso2.carbon.identity.multi.attribute.login.service/src/main/java/org/wso2/carbon/identity/multi/attribute/login/internal/MultiAttributeLoginServiceComponent.java#L91-L106

**Additional context**

As an additional task, it would be great if we can add a custom login resolver for a certain use case such as reducing the constant user store search process that happens when there are multiple user stores since it is one of the demanding use cases among customer.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
