### ISSUE TITLE
Skip SMS OTP step if the user login steps are configured as Basic auth -> Email OTP -> SMS OTP

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#15431]
**Describe the issue:**
Configure a service provider with login options as follows.
step 1- basic
step 2 - email otp
step 3 - SMS otp
![Screenshot - 2023-01-28T161000 697](https://user-images.githubusercontent.com/25483865/215262253-7239fbd9-ff00-4427-b217-5abf3cd2ed8c.png)

try the user login flow. After basic auth and email otp options, user will be logged in. SMS OTP is skipped

**Comment by Yoshani** [comment]
Fixed with https://github.com/wso2-extensions/identity-extension-utils/pull/40

**Comment by asekawa** [comment]
@Yoshani 

- [ ] Is this document impacted?
- [ ] Is the end-to-end (e2e) testing complete?
- [ ] Are unit tests available?
- [ ] Are integration tests available?
- [ ] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ] Have demo sessions been completed? (If yes, please attach the recording link)
- [ ] Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?

**Comment by Yoshani** [comment]
> @Yoshani
> 
> * [ ]  Is this document impacted?
> * [ ]  Is the end-to-end (e2e) testing complete?
> * [ ]  Are unit tests available?
> * [ ]  Are integration tests available?
> * [x]  Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
> * [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
> * [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
> * [ ]  Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?

No docs impact.
Explicit tests were not added since this is not a basic usecase
Feature was tested.
No demo sessions since it is a bug fix
Impacts on-prem environment
