### ISSUE TITLE
Broken link in "Ensure assurance with authentication context class reference (ACR) and authentication method reference (AMR)" page

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#15430]
**Is your suggestion related to a missing or misleading document? Please describe.**

"Ensure assurance with authentication context class reference (ACR) and authentication method reference (AMR)" page's
https://is.docs.wso2.com/en/latest/guides/adaptive-auth/work-with-acr-amr/

TRY IT WITH SAMPLE links redirected to a page not found

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
