### ISSUE TITLE
Copy to clipboard option is not available for code blocks in IS docs

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#15435]
The following option should be enabled for the IS docs as well.

<img width="1126" alt="Screenshot 2023-01-31 at 07 53 44" src="https://user-images.githubusercontent.com/21237558/215644683-7c243c3c-e2f5-4639-8bc2-80b171c44177.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
