### ISSUE TITLE
Automatic token revocation for SAML federated users

### ISSUE THREAD

**Issue by pandukakarunasena** [wso2/product-is#15436]
**Describe the issue:**
Automatic token revocation is not happening for federated users.

**How to reproduce:**

1. Set up an OIDC service provider with a SAML-federated IDP.
2. Enable a token binding method in the service provider configurations and check the Revoke tokens when the IDP session terminates option OIDC service provider configurations.
3. Authenticate with a user to generate the tokens.
4. Logout and check for tokens in the IDN_OAUTH2_ACCESS_TOKEN table. The corresponding token is still in an active state.

**Expected behavior:**
The token should be revoked from the IDN_OAUTH2_ACCESS_TOKEN table.

**Environment information:**
 - Product Version: [IS 5.10.0.200]
 - OIDC service provider: User Portal
 - SAML federated IDP: secondary Identity Server 

---

### Optional Fields

**Related issues:**
#12730

**Additional Details:**

- When the SESSION TERMINATE event Is published in the logout flows the TokenBindingExpiryHandler is triggered and the AuthenticationContext is passed to the handler. Here the lastAuthenticatedUser object[1] is retrieved which has a null value for user store domain for the federated users.
- Then to revoke the token, first from IDN_OAUTH2_ACCESS_TOKEN the token with the correct binding reference is retrieved. For this, the SQL query needs username, tenantID, user store domain, and token binding reference values[2].
- As the user store domain is null for the federated user the SQL result is empty hence the token is not revoked.
- Adding FEDERATED as the user store domain for the federated users would solve this issue.

[1] (https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.4.179/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/handlers/TokenBindingExpiryEventHandler.java#L78)
[2] (https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.4.179/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AccessTokenDAOImpl.java#L2550)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
