### ISSUE TITLE
Develop a solution to overcome the process of constant user store search

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#15440]
**Is your feature request related to a problem? Please describe.**

With the current architecture of the WSO2 Identity Server, when a user tries to login to a system where there are multiple user stores, the user is authenticate in each of the user stores until the proper user store is found. Because of this, when a user in a user store that is at end of the user store chain tries to login, it takes a long time and if there is slowness in user stores the time is affected further. Currently, there is no solution for this and the most appropriate solution is to fix it from the kernel level itself. However, since it is a complex task, we need to have an alternate to achieve the same. 

**Describe the solution you would prefer**

With the introduction of the proposed changes from [1], there is a possibility to develop a login resolver solution with the following properties.

- Have a intermediate database table to store the user store domain against the username.
- If the username is in the table, resolve the user without searching in other user stores.
- If the username is not available in the intermediate database table, execute the search process in through the user store chain and store the correct record in the intermediate database table if authentication succeeds.
- If a user is removed from the user store mentioned in the intermediate database table, remove the record from the database table.
- Maintain a cache to avoid unnecessary database calls to the intermediate database table.

The following is a sample diagram representing the same with the components (diagram is based on the login scenario).

![architecture](https://user-images.githubusercontent.com/33062368/215757643-61d27088-18d9-40a6-8b5a-8a9cdfc4fb70.png)

_Note: One of the main drawbacks of this solution is that if the same username is present in multiple user stores, this can cause unexpected behaviors._  

[1] - https://github.com/wso2/product-is/issues/15439

**Additional context**

A note should be made to overcome this issue from the kernel level itself in a future WSO2 Identity Server release.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
