### ISSUE TITLE
Unable to update values of OAuth2/OpenID Connect Configuration when creating a identity provider

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#15448]
**Describe the issue:**

When a user tries to create an identity provider and update values of OAuth2/OpenID Connect Configurations , the values are not updated properly.

https://user-images.githubusercontent.com/40081059/215944941-af6a535c-80a1-4fe0-afa7-75475a186ee4.mov

**How to reproduce:**

1.Login
2.Navigate to the Main menu to access the Identity menu. 
3.Click Add under Identity Providers.
4.Expand the Federated Authenticators section and then the OAuth2/OpenID Connect Configuration form.
5.Insert the client id , client secret , url and click Update button

**Expected behavior:**

The inserted values should be updated properly.
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 6.1.0 Rc1]
 - OS: [e.g.,Mac]
 - Database: [e.g.,H2]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
