### ISSUE TITLE
Multi-region deployment to achieve regulatory compliance for WSO2 Identity Server

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15459]
An enterprise must adhere to regional regulatory compliance requirements, such as regionally hosted data and services. For example, GDPR has requirements for storing sensitive user information within the region the user is in.

1. Users log in to a domain-qualified application name and, based on that application, will route the traffic to the respective region and perform authentication.
2. Users should be able to register through a common domain into a specific region. The user should be able to log in from different regional applications other than the user who got registered. ( Ex. the User onboard through .com website and then user login into the .co.uk domain website)
3. Users should be able to register through a common domain into a specific region. The user should be able to log in from different physical regions other than the user got signup/registered (Assume we can process data in other regions)
> User onboard through common/shared Saas app to Germany
> User travel to the US and try to login to the SaaS app
> Saas App uses a discovery service to find the region and route to the respective region (German) for authentication

Need to validate the feasibility and provide a guide with the impact on the product scenarios, including any data loss information.

**Comment by Sachin-Mamoru** [comment]
Initial Design Document - [[OnPrem] [Design-outline] Multi-region deployment to achieve regulatory compliance for IS](https://docs.google.com/document/d/1BWP5fLKQoukjCPfxCE76TNH7uZ46KvV8M7ZyPNprkUA/edit?usp=sharing)

**Proposed Solution**
The following solutions were identified for resolving the user region during login:

1. Through user input - By getting the user resident region as user input.

<img width="402" alt="image" src="https://github.com/wso2/product-is/assets/59449070/5a379fe5-023d-4253-8c09-7a27577d17f7">

2. Through region resolver - Resolve the user region without user input.

<img width="403" alt="image" src="https://github.com/wso2/product-is/assets/59449070/2060aa25-e45c-428e-94b6-f2d1fb2a5a56">

**Comment by DMHP** [comment]
@ashendes Please update the progress here.

**Comment by ashendes** [comment]
@DMHP progress updates were moved to the iam-engineering issue.

**Comment by aaujayasena** [comment]
@ashendes  is this plan to deliver with the IS 7.0.0. If not shall we update this in new dashboard https://github.com/orgs/wso2/projects/97/views/1 with proper status.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
