### ISSUE TITLE
Disaster Recovery deployment for WSO2 Identity Server

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15456]
An enterprise needs to keep its systems and applications to withstand regional failures, effectively enabling part or all of the load to transition to an alternate region.

- Enterprises are OK to lose end user's logins/sessions and allow them to re-login
- Providing user experience without re-login won't be practical since switching to a passive data center will have downtime.
- Need to consider how to sync data and runtime artifacts, such as user stores and event publishers, between multiple data centers
- Here, the switch is done manually, which leads to a downtime
- Fewer resources needed might be running a warm environment in a secondary (DR) site, which leads to fewer costs
- Traffic accepted only by the primary site

Need to have a guide setting up DR with the impact on the product scenarios, including any data loss information.

**Comment by ashensw** [comment]
DR guide: https://docs.google.com/document/d/1geXM6EgXsDE4U7WKrF7n81cPrrmR-Tp-dmZqdj-K0NI/edit?usp=sharing

**Comment by ashendes** [comment]
### Update 17/10/2023

The official DR guide is in the works in [1]. 
The scope should be defined more to cater to a targeted audience (deployment experts). 
The document should outline methodologies with information more related towards IS and not other technologies.

Atleast one other pattern needs to be added to broaden the context.

[1] https://docs.google.com/document/d/1-vBM59XVp31SEvEpjogvlovU7Neu0EKglZwmvsB9KM0/edit?usp=sharing
