### ISSUE TITLE
[Doc] Identity monitoring doc is missing Some information

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#1545]
The monitoring Docs doesn't have information about the Matrices, SOAP Tracer, and workflow requests. https://docs.wso2.com/display/IS540/Monitoring+the+Identity+Server

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
