### ISSUE TITLE
Support multi region deployment use case in WSO2 Identity Server

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15455]
**Is your suggestion related to an experience? Please describe.**

> Support multi-region deployment use case in WSO2 Identity Server

- Proper architecture pattern recommendations need to be evaluated and documented for the multi-region deployment use cases.

- [x] #15456
- [x] #15457
- [x] #15458
- [x] #15459

**Comment by aaujayasena** [comment]
@DMHP @ashensw  is the milestone correct? if this is not include with IS 7.0.0 shall we move to new dashboard  https://github.com/orgs/wso2/projects/97/views/1 with proper status.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
