### ISSUE TITLE
Multi-region deployment to achieve better response time for WSO2 Identity Server

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15458]
The user's traffic should route to the closest data center based on where the user is accessing.

1. If users move from one region to another region, users should not experience any delay. Still, enterprises are OK with losing end users' logins/sessions and allowing them to re-login.
2. If users move from one region to another region, users should not experience any delay, and enterprises don’t want end users to re-login. Ex. Users first log in to an app from the EU and then travel to the US and try to access the application. (If a user from Germany goes to the US and tries to log in, the User needs to access the German site and authenticate. Then the user authenticates through the German data center but token validation through the US. The user gets some delay on authenticating, but the refresh token will be faster)

Need to validate the feasibility and provide a guide with the impact on the product scenarios, including any data loss information.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
