### ISSUE TITLE
High availability multi-region deployment for WSO2 Identity Server

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15457]
An enterprise needs to keep its systems and applications to withstand regional failures, effectively enabling part or all of the load to transition to an alternate region.

- Enterprises are OK to lose end user's logins/sessions and allow them to re-login
- There should be no downtime for this; optionally, users may not want to re-login, but not a hard requirement.
- Need to consider how to sync data and runtime artifacts, such as user stores and event publishers, between multiple data centers in real time.
- Here, the switch is done automatically from the LB, which should not lead to a downtime
- Traffic accepted only by a single site at a given time. The switch will happen during a regional failure. 

Need to validate the feasibility and provide a guide with the impact on the product scenarios, including any data loss information.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
