### ISSUE TITLE
Java 11 source compatibility for Identity Server 6.2

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#15469]
**Is your suggestion related to an experience ? Please describe.**
As of now, IS 6.1.0 is runtime compatible with Java 11 and 17. But, the source is still maintained at Java 8.
Since Java 8  has gone through the End of Public Updates process, we should look at upgrading the source level of our code base to Java 11.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
