### ISSUE TITLE
[Doc] Document permissions in Identity component

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#1546]
The permission list is as follows, But these permissions are not documents in https://docs.wso2.com/display/IS540/Role-based+Permissions. Even the names are not self-explanatory.

![wso2 management console 1](https://user-images.githubusercontent.com/7681361/33977820-ba2e2f10-e0c2-11e7-8688-4680fdac6f23.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
