### ISSUE TITLE
Providing CLI to propagate configurations across environments

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#15461]
**Is your feature request related to a problem? Please describe.**

With our current Identity Server, we need to manually propagate changes done in configurations such as SPs & IdPs from one environment to another. This is an error-prone approach & can cause difficulties in restoring the configurations. Therefore we need to provide integration capability to perform version controlling in IS configurations and facilitate seamless CI/CD in multiple environment scenarios. This facilitates migration use cases as well.

- Identify the configurations that need to be propagated through environments. 
- Research possible ways to export & import these configurations
- Research possible the version controlling mechanism and CI/CD 
- Implement the capability to import & export configurations
- Integrate and demonstrate the capability of performing version controlling using a standard CI/CD pipeline (Ex. Integrate with Git & Git actions.)

**Comment by ImalshaG** [comment]
It was decided to develop the current [IAM CLI tool](https://github.com/wso2-extensions/identity-tools-cli) to support export and import functionalities for a set of resources.
The following tasks were identified:

- [ ] Correct approach to update existing configurations of the target environment
- [ ] Decide on which resources to be transferred 
- [ ] Folder structure of the exported directory
- [ ] How environment specific configurations should be handled
- [ ] How to update the CLI - version track

Furthermore, the following modification should be done to the CLI tool:

- [ ] Remove unnecessary configuration steps (serverConfiguration step)
- [ ] Remove continuous display of IAM-CLI logo 
- [ ] Have support to export and import files in YAML format (json/xml formats can be supported later)

**Comment by ImalshaG** [comment]
Closing this as the feature is now complete and only a part of the documentation is left which will be handled by the docs team [1].

[1] https://github.com/wso2/product-is/issues/16393

**Comment by melanisilva** [comment]
- [ ] Is this document impacted?
- [ ]  Is the end-to-end (e2e) testing complete?
- [ ]  Are unit tests available?
- [ ]  Are integration tests available?
- [ ]  Has this feature been tested on the latest Jenkins build after the changes have been merged? (Please Attach Proof , Screenshots, Screen recordings)
- [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
- [ ]  Has the cloud readiness been verified?
