### ISSUE TITLE
Upgrade OSGi to latest

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#15470]
**Describe the task:**
In the effort of making the IS 6.2 source compatible with Java 11, we would need to upgrade the OSGi version of the product. The reason for this comes from the upgraded versions of mvn-compiler-plugin and mvn-bundle-plugins (which we would have to use for Java 11 release), adding OSGi related required capabilities to the bnd.bd which would only be avaliable in newer versions of OSGi containers. Hence, we would need to upgrade the OSGi version and then look at source code changes in the other repositories. 

**Related issues:**
https://github.com/wso2/product-is/issues/15469

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
