### ISSUE TITLE
Doc Feedback: UMA doesn't exist in the latest version of 6.1.0

### ISSUE THREAD

**Issue by siva538** [wso2/product-is#15475]
Location : https://is.docs.wso2.com/en/latest/deploy/change-to-mssql/

UMA folder does not exist in the latest version of IS. Please remove the references in the documentation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
