### ISSUE TITLE
Permissions for SP management are not working 

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#1547]
I want to restrict a user from deleting SPs. So I created a role with the following permissions. But SP management section is not visible without the parent permission checked. So what is the purpose of having child level permissions?

![wso2 management console 2](https://user-images.githubusercontent.com/7681361/33978133-25b48e86-e0c4-11e7-89a4-f8c38609226a.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
