### ISSUE TITLE
Configuring Claims does not work as expected when Twitter is configured as the IDP

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1548]
**Environment**
Standalone 5.4.0 GA pack
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**

1. Run Standalone IS 5.4.0 GA pack
2. Configure Travelocity as a Service Provider using inbound authenticator SAML SSO
3. Configure email using local claim dialect under SP claim configuration as in [1]
3. Configure Twitter as a IDP using federated authentication Twitter configuration [2] 
4. Configure email as a Claim for the Twitter IDP using custom claim dialect as in [3]
5. Configure Twitter IDP as a Federated authenticator under service provider Local and outbound authentication configuration
6. Access http://localhost:8080/travelocity.com
7. Click on SAML redirect binding
8. Input Twitter login credentials 
9. A set of mapped claim values will be displayed as in [4]

**Observation**
Even though the email address is mapped as a claim all the claim values mapped from the twitter side are displayed in the SP home page.

[1] sp-claim.png
[2] twitter-config.png
[3]. twitter-claim.png
[4]. issue.png

![sp-claim](https://user-images.githubusercontent.com/31848014/33978241-c9329aee-e0c4-11e7-9403-4926c1bfcee7.png)
![twitter-config](https://user-images.githubusercontent.com/31848014/33978249-d64a0be0-e0c4-11e7-93f0-14ac8dbd5987.png)
![twitter-claim](https://user-images.githubusercontent.com/31848014/33978267-e2cb752a-e0c4-11e7-944b-642bf61d2079.png)
![issue](https://user-images.githubusercontent.com/31848014/33978277-ef103b72-e0c4-11e7-8727-e6fc8485be5b.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
