### ISSUE TITLE
Disable JWT token revocation with new token requests even though token is not expired

### ISSUE THREAD

**Issue by lakshithagunasekara** [wso2/product-is#15484]
**Is your feature request related to a problem? Please describe.**
At a given time, IS is only allowing to keep one JWT token per application for the same scopes. Even though the previously issued token is not expired, a second call with the same clientID secret and scopes set will revoke the previous token. 

![215921321-d38c51a5-3c58-4b12-b85b-b892415e7750 (1)](https://user-images.githubusercontent.com/47380453/217733701-8184bbce-e9ef-47a0-944e-d1082514cb72.png)

Can we get this behavior fixed? 

**Describe the solution you would prefer**
Instead of revoking the previous token, it's better if IS can provide a limited number of tokens (Should be able to change the limit via a config) with token calls or provide the same token which is not expired yet similar to the opaque flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
