### ISSUE TITLE
Config to disable multi valued attribute separation when creating users in Active Directory user stores

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15489]
**Describe the issue:**
We have introduced an improvement/bug fix to separate multi-valued attributes when creating users in AD user store manager [1].

In the Active Directory, the manager is expecting a full DN of a user. If set the MultiAttributeSeparator as a comma character (, - the default value), and provide the claim value for the manager attribute with comma-separated DN, the user creation will fail with an LDAP error code 19.

i.e.: CN=Sachith UD. Udaraka,OU=CS,OU=IAMCS,DC=wso2is,DC=local

A sample user creation payload is given below. Claim http://wso2.org/claims/managercn is mapped to the manager attribute in claim configs.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org" xmlns:xsd="http://common.mgt.user.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:addUser>
         <!--Optional:-->
         <ser:userName>AD/SachithUd2</ser:userName>
         <!--Optional:-->
         <ser:credential>Admin1!</ser:credential>
         <!--Zero or more repetitions:-->
        <ser:claims>
            <!--Optional:-->
            <xsd:claimURI>http://wso2.org/claims/managercn</xsd:claimURI>
            <!--Optional:-->
            <xsd:value>CN=Sachith UD. Udaraka,OU=CS,OU=IAMCS,DC=wso2is,DC=local</xsd:value>
        </ser:claims>
         <!--Optional:-->
         <ser:profileName>null</ser:profileName>
         <!--Optional:-->
         <ser:requirePasswordChange>true</ser:requirePasswordChange>
      </ser:addUser>
   </soapenv:Body>
</soapenv:Envelope>
```

**Workaround:**
Set the MultiAttributeSeparator to a different value or provide the claim value with a different separator.

**How to reproduce:**

1. Configure a AD user store.
2. Create a claim (http://wso2.org/claims/managercn) and map AD attribute that does not accept multi values / has constraints (manager).
3. Create a user with a claim value containing commas. For the manager, we need to provide a DN of another user (CN=John Doe,OU=CS,OU=IAMCS,DC=wso2is,DC=local).
4. IS will throw an exception with LDAP error code 19.

**Expected behavior:**
User should be created without any exceptions.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - Userstore: AD

---

### Optional Fields

**Related issues:**
[1] - https://github.com/wso2/product-is/issues/9125

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
