### ISSUE TITLE
Add support to get local claims with associated external claims

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#15485]
**Is your suggestion related to an experience ? Please describe.**
Currently to confirm that whether a local claim is being associated with any external claims, there is no straight forward way. 
We have to fetch the claims from all external claim dialects and then do a search in all to see if there are any associated external claims for a local claim. The client or user has to write this logic. 

**Describe the improvement**
Provide BE support for this case where getLocalClaims will also fetch the associated external claims.

**Comment by VivekVinushanth** [comment]
Being fixed with
- https://github.com/wso2/carbon-identity-framework/pull/4442
- https://github.com/wso2/identity-api-server/pull/423

**Comment by VivekVinushanth** [comment]
Revert PRs
- https://github.com/wso2/carbon-identity-framework/pull/4453
- https://github.com/wso2/identity-api-server/pull/427

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
