### ISSUE TITLE
Service Provider - Mandatory claims are not working as expected

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1549]
**Operating System:** Ubuntu 16.04
**Java Version:** Oracle JDK 1.8.0_144
**Packs:** IS 5.4.0 GA
**Setup:** Standalone Pack

**Steps to reproduce:**
1. Implement scenario 17 [1] in this blog [2]. ( Simply this contains SP with OAuth 2.0 inbound authenticator)
2. Added few mandatory claims using Local Claim Dialect.
![claimsadded](https://user-images.githubusercontent.com/8134384/33977918-46648f88-e0c3-11e7-8e58-bfbbdd25316f.png)
3. Then tried to log in to SPA through the user. 

**Expected Result**
1. Initial login of the user, it should require all mandatory claims.

**Actual Result**
- Only asking about two claims as follows:

![claimsissue](https://user-images.githubusercontent.com/8134384/33977995-adb218ae-e0c3-11e7-819b-c18f6604172e.png)

As there are more mandatory claims, it should request from the user.

**More Issues identified with claims**
-  When we test out Travelocity app for other scenarios, it can be seen that it may ask that all mandatory claims not having previous sessions. But with this scenario, it may not gonna ask for mandatory claims whether there is no any session.
- With this solution IS gonna ask for different claims time to time. There is no any exact pattern. Sometime it may ask while sometimes not.  

Please verify the functionality of mandatory local claim used in this scenario. Discussion on this can be found in mail thread "[WSO2 IS] Clarification on Claim Configuration in Service Provider".

[1] https://github.com/Dilshani/identity-test-integration/tree/master/solution17
[2] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
