### ISSUE TITLE
Issue on Simplified Setup for deploying Kubernetes resources of WSO2 Identity Server

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#15493]
**Describe the issue:**
[A Simplified Setup for WSO2 Identity Server](https://github.com/wso2/kubernetes-is/blob/master/simple/README.md)
Once you set up the Kubernetes cluster and tried to log in to the server using the following URLs, only the management console is accessible.
* Management Console: https://\<NODE-IP\>:30443/carbon/
* Console: https://\<NODE-IP\>:30443/console/
* My Account: https://\<NODE-IP\>:30443/myaccount/

The issue is when we call the console URL through `https://\<NODE-IP\>:30443/console/`, the authorize call requested through the browser is `https://wso2is:9443/t/carbon.super/oauth2/authorize`.
Ideally, it should call the node port and then redirect to 9443.
Because of this issue, the console and the myaccount are not accessible.

**How to reproduce:**
1. Clone: https://github.com/wso2/kubernetes-is
2. Checkout: master Branch
3. Install [Minikube version: 1.7.3](https://github.com/kubernetes/minikube/releases/tag/v1.7.3)
4. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
5. Start the minikube kubernetes cluster with the following command.
```minikube
minikube start --vm-driver=virtualbox --cpus 4 --memory 8192
```
6. Deploy WSO2 Identity Server in your Kubernetes cluster.
Deployment Script: [wso2is-latest.sh](https://github.com/wso2/kubernetes-is/blob/master/simple/deployment-scripts/wso2is-latest.sh)
```bash
./wso2is-latest.sh --deploy
```
7. Use the following commands to check whether the pods are up or not.
> kubectl get pods -n wso2
8. Find the minikube IP using the following command.
```minikube
minikube ip
```
9. Try to access the console.
> Management Console: https://\<NODE-IP\>:30443/carbon/
> Console: https://\<NODE-IP\>:30443/console/
> My Account: https://\<NODE-IP\>:30443/myaccount/

**Expected behavior:**
Once the deployment is finished, should be able to access the console and my account properly.

**Quick Fixes:** To Try Out
> Change the Identity Server running port from `9443` to `30443`, which is the node port.
* Add a `21000` offset to the server port.
* Change the ports and target ports related to `9443` to `30443`.
> Add minikube IP to the `/etc/hosts` file.
* <MINIKUBE_IP> wso2is

Another fix would be changing the NODE_PORT from 30443 to 9443, but unfortunately the valid ports for minikube of type nodePort by default are 30000-32767 according to https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: WSO2 IS 6.1.0
 - OS: [Windows, Linux, Mac (For Mac m1 follow this [document](https://docs.google.com/document/d/18vtcg1Xv7pftW0sjNG6ejQWuE_pTyrs7LDXLQ-3PNtI/edit?usp=sharing))]
 - Database: MySQL
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
