### ISSUE TITLE
Cannot save "Revoke tokens upon user logout" settings

### ISSUE THREAD

**Issue by daoxxx** [wso2/product-is#15492]
**Describe the issue:**
In  Service Provice Oauth configuration the "Revoke tokens upon user logout" checkbox settings is not saved upon "Update".

**How to reproduce:**
Login to Carbon console. Open Service Provider/Inbound Authentication Configuration/OAuth/OpenID Connect Configuration.
Check the Revoke tokens upon user logout. 
Click on the "Update"
You'll see "Application updated successfully"
Open config again, "Revoke tokens upon user logout" is not set.

**Expected behavior:**
"Revoke tokens upon user logout" must be set after successul update.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0.
 - OS: Linux
 - Database: Postgresql
 - Userstore: JDBC
-

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
