### ISSUE TITLE
In IS 6 relyingPartyRedirectUrls resource in registry does not work when configured to redirect when the same session datakey is used.

### ISSUE THREAD

**Issue by UpekshaGalappaththi** [wso2/product-is#15497]
**Describe the issue:**
In the Identity Server, if the user has bookmarked a login page or presses the browser back button, it will throw an error when trying to login saying 'Authentication Error!Something went wrong during the authentication process. Please try signing in again.'
This happens because the same sessionDataKey is used in the request.

In order to avoid this error from occurring and redirect the user to the login page again we have a feature where in the registry from the management console you can configure a relyingPartyRedirectUrls resource with the client ID/ Issuer Name and with the url that the user needs to be redirected to[1]. This approach works with previous versions of the identity server but not with IS 6.0. I have tested this in the latest version of the IS 6.0.51 as well and the behaviour is the same. Furthermore MyAccount has this feature already enabled even though it was not as such in IS 5.11.

**How to reproduce:**
Please find the steps to reproduce this with a sample service provider.
Follow the documentation in[1] and create the relyingPartyRedirectUrls resource and add the sample service provider name and value. I have tried with the travelocity sample saml application. Then access the login page and before submitting credentials bookmark the page. Sign in and sign out. Again access the bookmarked login page and once you submit credentials you will see the error mentioned before.

**Expected behavior:**
When the previous login url is accessed it should be redirected to the configured url in the registry resource. This works as expected in earlier versions on the Identity Server.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0

---
[1] https://is.docs.wso2.com/en/6.0.0/references/extend/customize-the-authentication-endpoint/#handle-the-browser-back-button-and-bookmarked-login-page

**Comment by mifrazmurthaja** [comment]
Closing since this is a doc issue: #15500
