### ISSUE TITLE
Intermittent Front channel SLO issues in IS Cluster setup

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#15490]
**Describe the issue:**
In an IS cluster setup, when sticky sessions are disabled, following intermittent logout failures are observed

- SLO is not triggered for applications
- SLO is triggered twice for applications.

**How to reproduce:**

1. Download WSO2 IS 5.10 latest U2 update level
2. Setup a two node cluster
3. Setup a load balancer with sticky sessions disabled
4. Login to admin console and create a tenant(carbon.super can also be used).
5. Create three SPs with front channel logout enabled in the tenant and setup sample SAML applications to try out SLO flow(App-01, App-02, App-03). https://dewni-matheesha.medium.com/saml-2-0-front-channel-logout-with-wso2-identity-server-8a72d1075cf5

**SLO is not triggered for applications**

1. Login to App-01 first and then SSO to App-02.
2. Initiate SLO flow from App-01, intermittently the SLO would not get triggered to App-02.

**SLO is triggered twice for applications.**

1. Login to App-01 first and then SSO to App-02 and App-03.
2. Initiate SLO flow from App-01, intermittently the SLO would  get triggered to App-02 twice.

**Expected behavior:**
SLO requests should get triggered for the applications.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]

**Analysis**

SLO not triggered

- request from App-01 comes to node1, is added to the participant cache in memory, and persisted to the database. 
- request from App-02 comes to node 2, there is no participant cache for it in memory, retrieved from the database, and updated and persisted back.
- If the Logout request from App-01 comes to node1 since there is a cache entry, we will not query the DB again to get it[1][2][3], so node 1 would not know about the new entry added for the App-02 by the node2. The SLO would not be triggered to App-02.

(check the 5.10.0 source code for these methods)
[1]https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/servlet/SAMLSSOProviderServlet.java#L1241
[2]https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/util/SAMLSSOUtil.java#L2270
[3]https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/cache/SAMLSSOParticipantCache.java#L97

SLO triggered twice,

When the SLO response for a SLO request is received by the identity server, the participant is removed from the cache of the node but not persisted back again to the database in 5.10.0, this is fixed in the master[4][5]. So if there are multiple nodes and mulitple Apps that send SLO responses, some of the SPs would get the SLO request again because the caches in some nodes are not updated.

[4]https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/servlet/SAMLSSOProviderServlet.java#L526

[5]https://github.com/wso2/product-is/issues/12038

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/12038

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
