### ISSUE TITLE
domain is not supported in filtering scim users for 5.6.0

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#15507]
**Is your suggestion related to a missing or misleading document? Please describe.**
in https://docs.wso2.com/display/IS560/apidocs/SCIM2-endpoints/#!/operations#UsersEndpoint#getUser 

we don't support usestore domain as a parameter. This is only added to later versions as an improvement. Hence can we remove that from 5.6 docs ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
