### ISSUE TITLE
[Doc] Incorrect process given for handling the bookmarked login scenario

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#15500]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the [Handle the browser back button and bookmarked login page](https://is.docs.wso2.com/en/latest/references/extend/customize-the-authentication-endpoint/#handle-the-browser-back-button-and-bookmarked-login-page) document, it was instructed to configure registry values to handle the said scenario. However, the handling of this scenario is changed with [1], hence, instead of the registry values, the Access URL should be configured. 

**Describe the improvement**
Configuring an Access URL should be instructed to handle the said scenario.

[1] https://github.com/wso2/carbon-identity-framework/pull/3274

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
