### ISSUE TITLE
[Intermittent] Get 403 - Forbidden Error after session timeout

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1550]
**Operating System:** Ubuntu 16.04
**Java Version:** Oracle JDK 1.8.0_144
**Packs**: IS 5.4.0 GA
**Setup:** Standalone Pack

**Steps to reproduce**
1. Create an SP some configuration (Used scenario 17 [1, 2])
2. Update claim configurations.
3. While updating leave the server to few minutes to session out. (Changed Local claim Dialect to Custom claim dialect)

**Expected Result**
- Session timeout error should pop up.

**Actual Result**
- Get 403 - forbidden error in UI

Backend will log the error as follows;
{code}
TID: [-1234] [] [2017-12-14 06:33:23,927]  WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.7.120, method:POST, uri:/carbon/application/configure-service-provider-finish-ajaxprocessor.jsp, error:request token does not match session token) 
{code}

[1] https://github.com/Dilshani/identity-test-integration/tree/master/solution17
[2] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
