### ISSUE TITLE
Apple as an Identity Provider for Identity Server

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#15501]
**Is your feature request related to a problem? Please describe.**
Sign in with Apple follows the OAuth OIDC flow, but has some deviations from the traditional standards. Hence it would be ideal to implement a separate authenticator extending the OIDC authenticator. 

This task is to add Apple as a federated identity provider for WSO2 IS.

**Comment by ThaminduDilshan** [comment]
**Doc issue**
- https://github.com/wso2/product-is/issues/15536

**Comment by asekawa** [comment]
@ThaminduDilshan  can you please check on the following list
- [ ] Is unit / integration tests available
    (if not available mention the reason)
- [ ] Is the feature tested on the latest Jenkins build (after merging all the PRs)
   (if yes attache the relevant screenshots/screen recordings)
- [ ] Is Doc pr related to the changes available
- [ ] Is the demo recording for the feature available (If not mention the ETA for the demo)
- [ ] Has verified the cloud readiness
