### ISSUE TITLE
Users are not filtered by Domain in SCIM Get User requests

### ISSUE THREAD

**Issue by Binara-Sachin** [wso2/product-is#15504]
**Describe the issue:**
When performing SCIM Get User requests, users are not filtered by Domain name and results include uses from all domains which have SCIM enabled.

_Tested Requests:_

```curl
curl --location --request GET 'https://localhost:9443/t/carbon.super/scim2/Users?domain=PRIMARY' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

```curl
curl --location --request POST 'https://localhost:9443/scim2/Users/.search' \
--header 'Content-Type: application/scim+json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "attributes": [
        "name.familyName",
        "userName"
    ],
    "domain": "PRIMARY",
    "startIndex": 1,
    "count": 10
}'
```
Both above requests return results from secondary userstores as well.

The reason seems to be when requesting the user list from the UserstoreManager it passes a wildcard ("*") for claim value [1].
But needs further investigation.

**How to reproduce:**
1. Create a secondary userstore and enable SCIM for the userstore.
2. Create users in both primary and secondary userstores
3. Perform SCIM Get Users request, filtering either primary or secondary domain.

**Expected behavior:**
- Response should only contain users in the requested domain.

**Environment information**
 - Product Version: IS 5.6.0

---
[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.1.19/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L283

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
