### ISSUE TITLE
Roles are not displayed with separator on myaccount portal

### ISSUE THREAD

**Issue by MadhuNEC** [wso2/product-is#15503]
**Describe the issue:**
I am using WSO2IS 5.11.0. I have followed this https://is.docs.wso2.com/en/5.11.0/develop/extending-scim2-user-schemas/ to display Role on myaccount portal. But there is no separator in case of multipleValued Role.

**How to reproduce:**
1. Follow the link to add Role to SCIM claim https://is.docs.wso2.com/en/5.11.0/develop/extending-scim2-user-schemas/
2. Add below to repository/conf/scim2-schema-extension.config and add `role` to `subAttributes` of the `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`
```
"attributeURI":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:role",
"attributeName":"role",
"dataType":"string",
"multiValued":"true",
"description":"Role",
"required":"false",
"caseExact":"false",
"mutability":"readOnly",
"returned":"default",
"uniqueness":"none",
"subAttributes":"null",
"canonicalValues":[],
"referenceTypes":[]
},
```

**Expected behavior:**
Role should be displayed with separator in case of multi value on myaccount portal.
E.g.
**Role     Internal/admin,Application/Console,Internal/Everyone,Application/My Account,admin**

**Actual behavior:**
Roles are displayed without separator. 
![image](https://user-images.githubusercontent.com/105198424/218651573-8e16eb5a-5cb1-4020-8c9f-072e7ba8f138.png)
Additionally, I could see that /schemas respond with `"multiValued"="false"` for Role in network trace while logging into myaccount portal.
`[{"name":"User","description":"User Account","attributes":[{"uniqueness":"NONE","name":"roles","type":"COMPLEX","multiValued":true,"caseExact":false,"returned":"DEFAULT","subAttributes":[{"uniqueness":"NONE","displayName":"Role","name":"default","displayOrder":"12","description":"Role","mutability":"READ_ONLY","type":"STRING","multiValued":false,"caseExact":false,"returned":"DEFAULT","required":false}]},{"uniqueness":"NONE","displayName":"Account Disabled","name":"accountDisabled","displayOrder":"0","description":"Account Disabled","mutability":"READ_WRITE","type":"STRING","multiValued":false,"caseExact":false,"returned":"DEFAULT","required":false},{"uniqueness":"NONE","displayName":"Username","name":"userName","description":"Username","mutability":"READ_WRITE","type":"STRING","multiValued":false,"caseExact":false,"returned":"DEFAULT","required":false}],"id":"urn:ietf:params:scim:schemas:core:2.0:User"},{"name":"EnterpriseUser","description":"Enterprise User","attributes":[{"uniqueness":"NONE","displayName":"Role","name":"role","displayOrder":"12","description":"Role","mutability":"READ_ONLY","type":"STRING","multiValued":false,"caseExact":false,"returned":"DEFAULT","required":false},{"uniqueness":"NONE","displayName":"Account Disabled","name":"accountDisabled","displayOrder":"0","description":"Account Disabled","mutability":"READ_WRITE","type":"STRING","multiValued":false,"caseExact":false,"returned":"DEFAULT","required":false}],"id":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"}]`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - OS: [Windows, Linux]
 - Database: [H2]
 - Userstore: [LDAP]

**Comment by Yoshani** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/3932

**Comment by asekawa** [comment]
@Yoshani 

- [ ] Is this document impacted?
- [ ] Is any E2E affected with the fix?
- [ ] Are unit tests affected?
- [ ] Are integration tests affected?
- [ ] Has this fix been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ] Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?
