### ISSUE TITLE
Add proper description on parameters used in defining custom claims for SP

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1551]
**Documentation:** Configuring a Service Provider [1].

**Issue Identified**: Under the section "Claim mapping", it has a detailed description of claims. And there is a description how to define claims using Custom Claim Dialect. 

While we define custom claims, there are two values as "Requested Claims" and "Mandatory Claims". Please add the difference on them and describe examples on this.

Add the description of what is subject claim URI and role claim URI.

[1] https://docs.wso2.com/display/IS540/Configuring+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
