### ISSUE TITLE
Introduce a separate config to change UMA permission ticket validity period.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#15514]
**Description:**

The config which is used to increase the validity period of the authorization code validity period is used to increase the validity period of the UMA permission ticket too.
https://github.com/wso2-extensions/identity-oauth-uma/blob/master/docs/tryout.md#obtain-a-permission-ticket

Ideally, there should be a separate configuration to define the UMA permission ticket validity period.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
