### ISSUE TITLE
Configure wso2 IS as federated IDP for sharepoint web application

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15510]
### Problem

Current available documentation to achieve the above $subject need to be updated. You can find the documentation link from [here](https://is.docs.wso2.com/en/latest/guides/login/log-into-sharepoint-using-is/). 

### Describe

To configure wso2 IS as a federated IDP of a sharepoint web application, there are three protocols we can follow.
1. `WS federation (passive) STS`
2. `SAML`
3. `OIDC`

#### WS federation (passive) STS

The given documentation uses `WS federation (passive) STS` as the inbount authentication protocol when setting up wso2. When trying out the documentation fe issues were identified.
1. The `namespace` used to `AppliesTo` element was not recognised.
    - This can be fixed by changing the WS policy provided from the BE.
2. The SAMLAttribute elements were missing the Name tag.
    - Need to be fixed from the BE.
3. The provided issuer of the token is not a trusted issuer.
    - ATM nowhere to configure the issuer provided.

#### SAML and OIDC

Both SAML and OIDC are new protocols supported by Sharepoint. When configuring the authentication providers using these protocols, need to configure People Picker control to validate, resolve, search users and groups. When using People Picker, IS need an Active Directory configured as the Primary user store to smoothly configure the profile sync between the two platforms (WSO2 IS and Sharepoint). The downside of this method is that we can only support one type of user store.

Unless need to write a custom claim provider through C# to do the profile syncing. It was mentioned in the documentation that it is a bit time consuming. This can be considered as the most effective and scalable way as it can be written to configure as many types of userstores as possible.

### Conclusion

From the above mentioned 3 ways the effort of trying out the different methods should be carried out in the below order. (This order was decided based on the developer's effort.)
- Use `WS federation (passive) STS` and fixed the SAML token errors.
- Use either `SAML` or `OIDC` and use a Active directory user store.
- Use either `SAML` or `OIDC` and write the custom claim provider through C#.

**Comment by mpmadhavig** [comment]
### Update <17-02-2023> - Use WS federation (passive) STS

- The documentation for the steps followed so far can be found from [here](https://docs.google.com/document/d/1twxrwBmKlE0_z7fU-lxDsThtequcnPaDA8VHq2JJ41k/edit?usp=sharing).
- There are considerable changes are there in the set up process. All those are mentioned in the above document. Some of the key changes that needs special attension are listed below.
    - The SAML response sending from the wso2 identity server side need the below changes.
        - Changing ws-policy from http://www.w3.org/ns/ws-policy to http://schemas.xmlsoap.org/ws/2004/09/policy.
        - SAML attribute having the AttributeName value.
    - After creating the web application, for external users to access the site the site need be shared with the external users. Sharing option is not available in the onPrem version of Sharepoint. Hence need a micrsoft account with Office 365 subscription to access `Sharepoint online edition`.

**Comment by mpmadhavig** [comment]
### Update <17-02-2023> - Use OIDC
- The sharepoint official documentation is pretty straightforward on how to configure an OIDC external authenticator. You can find the documentation from [here](https://learn.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/oidc-1-0-authentication).
- The document I created can be found from [here](https://docs.google.com/document/d/1twxrwBmKlE0_z7fU-lxDsThtequcnPaDA8VHq2JJ41k/edit?usp=sharing).
- This approach need some heavy work as it needs syncing user profile between the external identity server and the sharepoint AD. As mentioned in the above description it either need a AD primary user store or custom claim validator written in c#.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
