### ISSUE TITLE
Support for JARM (JWT Secured Authorization Response Mode) for OAuth 2.0

### ISSUE THREAD

**Issue by anjuchamantha** [wso2/product-is#15527]
**Description:**

Provide the ability to send a signed response for the authorization request as mentioned in JARM Spec [1].

JARM specification defines a new JWT-based mode to encode OAuth authorization responses where clients are enabled to request the transmission of the authorization response parameters along with additional data in JWT format.

[1] https://openid.net/specs/openid-financial-api-jarm.html

Currently supported default response modes:
- query
- form_post
- fragment

New response modes introduced by JARM:
- query.jwt
- fragment.jwt
- form_post.jwt
- jwt (default)

**Affected Product Version:**
WSO2-IS-5.10

**Comment by chamathns** [comment]
closing this since all the PRs are merged

**Comment by asekawa** [comment]
@chamathns  can you please verify the below checklist

- [ ] Is unit / integration tests available
    (if not available mention the reason)
- [ ] Is the feature tested on the latest Jenkins build (after merging all the PRs)
   (if yes attache the relevant screenshots/screen recordings)
- [ ] Is Doc pr related to the changes available
- [ ] Is the demo recording for the feature available (If not mention the ETA for the demo)
- [ ] Has verified the cloud readiness
