### ISSUE TITLE
The AuthMechanism parameter note in newer IS version docs is not clear

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#15537]
**Is your suggestion related to a missing or misleading document? Please describe.**
We have introduced a configuration with the fix for the issue[1] and it has been documented properly in older IS docs[2]
<img width="1402" alt="Screenshot 2023-02-21 at 15 09 46" src="https://user-images.githubusercontent.com/47600906/220307402-a8d5f274-9049-46ea-96fe-82af0f26234f.png">

however in newer IS docs[3], the same is not conveyed. The following configurations need to be mentioned in the doc[3]

[authentication.authenticator.basic.parameters]
auth_mechanism="basic"

[authentication.authenticator.oauth_request_path.parameters]
AuthMechanism="basic"

[authentication.authenticator.basic_request_path.parameters]
AuthMechanism="basic"

[1]https://github.com/wso2/product-is/issues/3882
[2]https://docs.wso2.com/display/IS580/Basic+Auth+Request+Path+Authentication
[3]https://is.docs.wso2.com/en/5.9.0/learn/basic-auth-request-path-authentication/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
