### ISSUE TITLE
Update the response of /by-attrib endpoint in Entitlement APIs

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#15546]
**Is your suggestion related to a missing or misleading document? Please describe.**
In Entitlement REST API doc[1], the response of the `/by-attrib` is mentioned as a JSON payload. But that API is not supporting to JSON and only supports to XML. So we need to update the response according to that. Sample XML response is as follows.

```
<Response xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
<Result>
<Decision>Permit</Decision>
<Status><StatusCode Value="urn:oasis:names:tc:xacml:1.0:status:ok"/></Status>
</Result>
</Response>
```
Also we need to update the error responses accordinly.

[1] https://docs.wso2.com/display/IS570/Entitlement+with+REST+APIs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
