### ISSUE TITLE
Slowness displayed at Google One Tap UI loading

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#15545]
**Describe the issue:**
The login panel shows an unexpected empty space until the Google One Tap UI is displayed.

https://user-images.githubusercontent.com/37938529/220835259-fa95acc7-a729-4900-9a70-da945588592c.mov

**How to reproduce:**

**Expected behavior:**
Suggestion is to show a loading spinner until the One Tap UI is loaded. Better to improve the loading with a smooth animation.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
