### ISSUE TITLE
[Doc] Provide a direct link to download the latest version PassiveSTS.war

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1554]
Refer to doc [1]. Under deploying the sample on apache tomcat please provide a direct link to download the passiveSTS.war file as provided in Travelocity.

[1]. https://docs.wso2.com/display/IS540/Testing+Passive+STS

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
