### ISSUE TITLE
Add more details to the description of SOAP APIs

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#15544]
**Is your suggestion related to a missing or misleading document? Please describe.**
We have encountered that in the Managing Users and Roles SOAP APIs[1], the username parameter description does not say how we need to provide the username to the SOAP request. 

Ex : For `isExistingUser` SOAP API we need to send the userstore domain qualified username to search the user in the particular userstore. If we did not add the doamin qualified username it will only serch the user in the PRIMARY userstore. But in [2], there are no description about these details.

[1] https://is.docs.wso2.com/en/5.11.0/develop/managing-users-and-roles-with-apis/#managing-users-and-roles-with-apis
[2] https://is.docs.wso2.com/en/5.11.0/develop/managing-users-and-roles-with-apis/#isexistinguser

**Describe the improvement**
We need to update the description of the SOAP APIs with the proper details about how we need to send the params and what is the behavior of the corresponding SOAP API with those params.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
