### ISSUE TITLE
Improvement on performance-is to cater JWT grant type flow with JWKS endpoint

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#15542]
**Describe the issue:**
When we trigger the test build for JWT grant type flow using JWKS endpoint for signature validation, a slight error rate has occurred, let me explain the root cause for this

During the first token request,  call to IDPs’ JWKS endpoint will be made to obtain the certificate for validation, and cached it for other requests. As the cache implementation Identity server uses nimbus JWKSetCache which has the default lifespan of 5 minutes [1]. So after 5 minutes from the initial token call, the cached certificates will be expired, and the token calls after that would call the IDPs’ JWKS endpoint to obtain the certificate. Each of these tests runs for 10 minutes, so during this 5 minutes gap, we noticed that the request was invoked to the IDPs’ JWKS endpoint for a very short period of time.

In Asgardeo, we have rate limiting for the endpoint. So with higher concurrencies, the number of JWKS calls to the Asgardeo increases during that specific sort period of time. This leads to rate-limiting on the Asgardeo side. This is the root cause of the error count.

[1] https://www.javadoc.io/doc/com.nimbusds/nimbus-jose-jwt/7.9/com/nimbusds/jose/jwk/source/DefaultJWKSetCache.html

**How to reproduce:**
Run the JWT grant flow using Asgardeo as a trusted IDP in the performance build. Use the JWKS endpoint without uploading the certificate.

**Expected behavior:**
Provide results without any errors.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - OS: Linux
 - Database: MySQL
 - Userstore: JDBC

**Comment by aaujayasena** [comment]
Shall we update the issue status. If this is not ready with the IS 7.0.0-rc1, please update the milestone.  Ex: https://github.com/orgs/wso2/projects/97/views/1 board "backlog"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
