### ISSUE TITLE
HTML error response pages contain WSO2 license header

### ISSUE THREAD

**Issue by PasanT9** [wso2/product-is#15558]
Description :
To handle error responses we uses HTML error pages (error_500.html, error_400.html, ...). These pages contains the WSO2 license header. Since curl cannot sanitize HTML comments, if such a HTML page returns as a response to a curl request, the response will contain the license header as well.

Similar Issue: https://github.com/wso2/api-manager/issues/906

Product : wso2am-4.1.0
Update level : latest
WSO2 case id : N/A
Case number : N/A
Public Git Issue : N/A
Opened by : @PasanT9

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
