### ISSUE TITLE
Examples required for Role/permission in SP configuration

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1555]
**Documentation:** Configuring a Service Provider [1].

**Issue Identified**: Under the section "Click here for details on how to configure roles and permissions", it has a description of roles and permission. 

It is not clear what we should as roles and permissions. Shall we add some samples values with proper explanation?

[1] https://docs.wso2.com/display/IS540/Configuring+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
