### ISSUE TITLE
Suggestions for improving the BaseCache implementation

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#15553]
[BaseCache](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/cache/BaseCache.java) is the base used for all identity caches in the identity server. [L100-L102](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/cache/BaseCache.java#L100-L102) needs to be improved to properly handle the concurrency without using double checked locking.

Also, the default timeout set for the caches implemented using this BaseCache is set to -1 if the configurations are not defined at the identity.xml. This also needs to be improved to set a correct default timeout value.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
