### ISSUE TITLE
PreferenceRetrievalClient is making multiple API calls per each login page load

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15566]
**Describe the issue:**
[PreferenceRetrievalClient](https://github.com/wso2/carbon-identity-framework/blob/v5.25.121/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/client/PreferenceRetrievalClient.java) is making multiple API calls per each login page load. It does HTTP calls for each preference check in the same session, which is not required and a bulk request can be used to reduce the number of requests.

**How to reproduce:**
Initiate an authentication flow and observe the HTTP access logs. There will be 05 requests to following API for each login page load.
```
127.0.0.1 - - [28/Feb/2023:14:42:56 +1100] POST /api/server/v1/identity-governance/preferences HTTP/1.1 400 190 "-" "Apache-HttpClient/4.5.13 (Java/17.0.5)" 0.007
127.0.0.1 - - [28/Feb/2023:14:42:56 +1100] POST /api/server/v1/identity-governance/preferences HTTP/1.1 200 112 "-" "Apache-HttpClient/4.5.13 (Java/17.0.5)" 0.005
127.0.0.1 - - [28/Feb/2023:14:42:56 +1100] POST /api/server/v1/identity-governance/preferences HTTP/1.1 200 130 "-" "Apache-HttpClient/4.5.13 (Java/17.0.5)" 0.005
127.0.0.1 - - [28/Feb/2023:14:42:56 +1100] POST /api/server/v1/identity-governance/preferences HTTP/1.1 200 191 "-" "Apache-HttpClient/4.5.13 (Java/17.0.5)" 0.006
127.0.0.1 - - [28/Feb/2023:14:42:56 +1100] POST /api/server/v1/identity-governance/preferences HTTP/1.1 200 147 "-" "Apache-HttpClient/4.5.13 (Java/17.0.5)" 0.005
```

**Expected behaviour:**
It should fetch all the configurations in one API call to reduce the delay in loading the login page.

**Environment information** 
 - Product Version: IS 6.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
