### ISSUE TITLE
The SCIM multi-valued attributes with `primary:true` and defined `type` do not behave as the primary attribute

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#15560]
**Describe the issue:**
The improvement https://github.com/wso2/product-is/issues/3823 has given the capability to store `primary` sub-attribute of complex multi-valued properties such as 
[emails](https://www.rfc-editor.org/rfc/rfc7643.html#:~:text=bjensen%22%2C%0A%20%20%22emails%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22value%22%3A%20%22bjensen%40example.com%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22work%22%2C-,%22primary%22%3A%20true,-%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22value%22%3A%20%22babs%40jensen.org%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22home%22%0A%20%20%20%20%7D%0A%20%20%5D%2C%0A%20%20%22addresses%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22type),  
[addresses](https://www.rfc-editor.org/rfc/rfc7643.html#:~:text=CA%2091608%20USA%22%2C-,%22primary%22%3A%20true,-%7D%2C%0A%0A%0A%0A%0A%0A%0A%0A%0AHunt%2C%20et),
phoneNumbers, etc

But IS functionality wise, the attribute value marked as the primary:true won't get used.

**For example,** 
flows such as password recovery, all notification sending via emil the email address defined as "primary":true will not be taken into consideration. Instead, the email address available at http://wso2.org/claims/emailaddress will be used.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
