### ISSUE TITLE
AttributeName is missing in Passive STS responses

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15565]
**Describe the issue:**
The user Attributes retuned in the STS response have been missing the `AttributeName`. Therefore the client apps fail to extract the user claims.

The claim are set at https://github.com/wso2-extensions/identity-inbound-auth-sts/blob/d0c105551f190a3e947691e237d474174d36f088/components/org.wso2.carbon.identity.sts.passive/src/main/java/org/wso2/carbon/identity/sts/passive/custom/handler/CustomClaimsHandler.java#L51 and it seems to be populating the claim type only. There is no claim name in that interface.

**How to reproduce:**
If you add `http://wso2.org/claims/givenname` as a requested claim and try out the passive STS flow, you will get following inside the STS response.
```
<saml1:Attribute AttributeNamespace="http://wso2.org/claims/givenname"><saml1:AttributeValue xsi:type="xsd:string">admin@wso2.com</saml1:AttributeValue></saml1:Attribute>
```
Note the `AttributeName` is missing here and whole claim URI is inside the `AttributeNamespace`.

**Expected behavior:**
```
<saml1:Attribute AttributeName="givenname" AttributeNamespace="http://wso2.org/claims"><saml1:AttributeValue xsi:type=
"xsd:string">admin@wso2.com</saml1:AttributeValue></saml1:Attribute>
```
Note the claim URI is splitted between `AttributeNamespace` and `AttributeName`.

**Environment information**
 - Product Version: IS 6.0.0

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/8350

**Comment by Yoshani** [comment]
To set the attribute name in the response in IS 6.0, the below config should be set in deployment.toml file.
```
[passive_sts]
enable_attribute_name_in_response = true
```
