### ISSUE TITLE
Inconsistency in naming the log files

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1556]
Type: Improvement
Priority: Normal
Severity: Minor
Release: 5.4.0

In IS, some logs do not append the date as a post prefix to the name, but the access log does. It needs to be consistent

```
audit.log     - Today's log        
audit.log.2017-12-13      

wso2carbon.log   - Today's log      
wso2carbon.log.2017-12-13 

http_access_2017-12-14.log   - Today's log // inconsistent with the naming convention
http_access_2017-12-13.log  
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
