### ISSUE TITLE
Console UI shows a field with an unhandled object for "entitlements" attribute

### ISSUE THREAD

**Issue by ravinduramesh** [wso2/product-is#15568]
**Describe the issue:**
As shown in the below screenshot, the console UI shows a field with an unhandled object for `entitlements` attribute with a field to insert a string as `entitlements`.
![entitlements in product-is](https://user-images.githubusercontent.com/12953762/221835716-308994a7-e0c7-47c8-83be-b98d9afd8f48.png)

**How to reproduce:**
1. Login and go to https://localhost:9443/console/manage/attributes-and-mappings
2. Enable the "Display the attribute on the user profile" option for `entitlements` attribute
3. Go to https://localhost:9443/console/manage/users and view a user

**Expected behavior:**
A field with an unhandled object should not be shown and there should be a proper input field for `entitlements` as it's a complex multivalued attribute.

**Comment by melanisilva** [comment]
This will be solved with the new Asgardeo unification.
