### ISSUE TITLE
[DOCS]Provide a 5.4.0 version of Configuring Email OTP document

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1557]
Please provide the latest version of Configuring Email OTP doc. 
https://docs.wso2.com/display/IS530/Configuring+Email+OTP

**Comment by shavidissa** [comment]
Thank you! Added the content, updated it for 5.4, and test it end to end.

[1] https://docs.wso2.com/display/IS540/Configuring+Email+OTP
