### ISSUE TITLE
WSO2 Updates Information Portal - Links to Github

### ISSUE THREAD

**Issue by leonardorobertolopez** [wso2/product-is#15585]
**Is your suggestion related to an experience ? Please describe.**
In the WOS2 Updates information Portal the need is having links to github issues instead of raw text. 
For example:
Links with raw text:
![image](https://user-images.githubusercontent.com/102697473/222756135-7748fed1-67e9-44f0-8f5e-717a29b1c0d7.png)

**Describe the improvement**
In this case our client needs to jump from the updates portal to the Github issues just by clicking the link. Actually the client has to copy and paste the link in another browser tab.

**Comment by leonardorobertolopez** [comment]
I would like to ask if there a security constraint to do that and if it is possible.
Thank you very much

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
