### ISSUE TITLE
[Doc] Wrong endpoint urls were mentioned in advanced configs of SMS and EMAIL OTPs.

### ISSUE THREAD

**Issue by nisho06** [wso2/product-is#15589]
### Is your suggestion related to a missing or misleading document? Please describe.

The default configurations of endpoints provided under advanced configurations of SMS OTP[1] and EMAIL OTP[2] were wrong.  From IS 6.0.0 onwards, the `smsotpauthenticationendpoint` and `emailotpauthenticationendpoint` are deprecated. Instead, the sms otp and email otp endpoints have been changed to `authenticationendpoint`. 

**Note :-** This needs to be fixed in relevant docs of IS 6.0 and IS 6.1.

### Describe the improvement

Relevant endpoint urls of SMS OTP should be as follows,
```
SMSOTPAuthenticationEndpointURL = "/authenticationendpoint/sms_otp.do"
SMSOTPAuthenticationEndpointErrorPage = "/authenticationendpoint/sms_otp_error.do"
MobileNumberRegPage = "/authenticationendpoint/mobile.do"
```
Relevant endpoint urls of EMAIL OTP should be as follows,

```
EMAILOTPAuthenticationEndpointURL = "/authenticationendpoint/email_otp.do"
EmailOTPAuthenticationEndpointErrorPage = "/authenticationendpoint/email_otp_error.do"
EmailAddressRequestPage = "/authenticationendpoint/email_capture.do"
```

[1] - https://is.docs.wso2.com/en/latest/guides/mfa/sms-otp-config-advanced/
[2] - https://is.docs.wso2.com/en/latest/guides/mfa/email-otp-config-advanced/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
