### ISSUE TITLE
Provide multiple permission when adding role through admin service 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1558]
In [1] details should be added on how to give permission to a role and this should be addressed in the form of a real use case. E.g. How do i create a role with read permission to resource x and write permission to resource y. Here this should be mapped to a reference and all permissions that can be granted through the api should be documented.

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addRole()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
