### ISSUE TITLE
Indicate mandatory parameters in manager users and role admin service calls

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1559]
In [1] the table that carries the explanation for the parameters does not indicate what are the mandatory values and what are the optional values for the request. Please indicate the relevant information. This should not be resolved until all the operations are covered

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addRole()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
