### ISSUE TITLE
SCIM performance issue when getting user count

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#15598]
**Describe the issue:**

By default in IS 6.0.0 following property is set to false, but in IS 5.11.0 it's true (this value should be true by default in the IS 6.0.0 as well).
[scim2]
consider_max_limit_for_total_results = false

when GET scim2/Users filter request is used to get the users with **eq** operation, it will execute following SQL query[1] with LIKE operation even though filter operation is eq. This LIKE operation introduce huge performance impact on DB.

[1] SELECT COUNT(UM_USER_NAME) AS RESULT FROM UM_USER WHERE UM_USER_NAME LIKE $1 AND UM_TENANT_ID = $2

sample curl :- 
```
curl --location 'https://localhost:9443/scim2/Users?filter=userName+eq+shehan' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```
**How to reproduce:**

By default in IS 6.0.0 following property is set to false, but in IS 5.11.0 it's true.
[scim2]
consider_max_limit_for_total_results = false

1. If above property is true set it to false.
2. Setup JDBC userstore and enable correlation logs to observe DB queries executed.
3. Execute above sample GET scim2/Users filter request with eq operation.
4. It can be observed that DB query with LIKE operation was executed in the correlation logs for particular request.

**Expected behavior:**

Since scim2/Users filter request was done with eq operation, it should be searching the exactly matching usernames(UM_USER_NAME = operation) not with partial matching(LIKE operation).
 
**Environment information** 
 - Product Version: [ IS 6.0.0]
 - OS: [ Linux]
 - Database: [ H2]
 - Userstore: [ JDBC]

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
