### ISSUE TITLE
Passive STS based authentication for .net applications fail due to namespace issue in AppliesTo element

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15592]
**Describe the issue:**
With the changes done in https://github.com/wso2/product-is/issues/8350, the passive STS response includes the ResponseTo tag in it. But the .net application are not accpeting the namespace included with it. Those apps expect the old namespace and that namespace is still hardcoded in the .net framwork [1],[2]

Fails, new namespace [3] (>= IS 5.11.0)
```
        <wsp:AppliesTo xmlns:wsp="http://www.w3.org/ns/ws-policy">
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>http://localhost:8080</wsa:Address>
            </wsa:EndpointReference>
        </wsp:AppliesTo>
```

Works, old namespace (< IS 5.11.0)
```
        <wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address>http://localhost:8080</wsa:Address>
            </wsa:EndpointReference>
        </wsp:AppliesTo>
```

**How to reproduce:**
Implement a .net application to use WSO2 IS for authentication via passive STS using WSFederationAuthenticationModule. The authentication will fail with the following error.
```
"System.IdentityModel.Protocols.WSTrust.WSTrustSerializationException: ID3007: The element 'AppliesTo' with namespace 'http://www.w3.org/ns/ws-policy' is unrecognized"
```

**Expected behavior:**
.net framework should support the latest namespaces, but until then, the IDP has to make workarounds to keep supporting the .net applications.

However, the AppliesTo element is optional according to specification [4]. Therefore, this can be execluded in the responses.

[1] https://github.com/microsoft/referencesource/blob/master/System.IdentityModel/System/IdentityModel/Protocols/WSTrust/WSPolicyConstants.cs
[2] https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.IdentityModel/System/IdentityModel/Protocols/WSTrust/WSTrustSerializationHelper.cs#L108
[3] https://www.w3.org/ns/ws-policy
[4] http://docs.oasis-open.org/ws-sx/ws-trust/v1.4/errata01/os/ws-trust-1.4-errata01-os-complete.html#_Toc325658947:~:text=4.4.1-,wsp%3AAppliesTo%20in%20RST%20and%20RSTR,-Both%20the%20requestor

**Environment information** 
 - Product Version: IS 5.11 and later

**Comment by Yoshani** [comment]
The following config can be used to disable the AppliesTo element in the Passive STS response.
```
[passive_sts]
disable_applies_to_in_response = true
```
