### ISSUE TITLE
Improving the session storage and cleanup process for large scale deployments

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#15601]
**Is your suggestion related to an experience ? Please describe.**

When it comes to large scale deployments, the session storage table `IDN_AUTH_SESSION_STORE` can grow exponentially due to the session details. Normally the session cleanup script is executed at the time when transactions are low. But sometimes the database will not survive until the session cleanup script is been executed. 

**Describe the improvement**

As a solution we can improve the session data storage as the following.
- Persisting the authentication context data and the session data separately.
  - The authentication context data and the session data are stored separately when the internal cleanup is enabled on the tables IDN_AUTH_TEMP_SESSION_STORE and IDN_AUTH_SESSION_STORE respectively (default behavior) [1].
  - However, when it's disabled, all the data will be stored in IDN_AUTH_SESSION_STORE.
  - Therefore, it can be improved to store it separately even when the internal cleanup is disabled, in order to clean the data separately.

[1] https://github.com/wso2/carbon-identity-framework/blob/d32c5c7792a9cca139fa93866e953aeb7bbb55bf/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java#L702

**Comment by Thisara-Welmilla** [comment]
Fixed with https://github.com/wso2-support/carbon-identity-framework/pull/2640
