### ISSUE TITLE
[DOCS]EmailOTP configs in application-authentication.xml

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1560]
Document: [Configuring Email OTP](https://docs.wso2.com/display/IS530/Configuring+Email+OTP)
Section: Step 1 - Deploy the EmailOTP artifacts
Step 3

In IS5.4.0 pack -> application-authentication.xml file, there is already EmailOTP config which is as below. 
`  <AuthenticatorConfig name="EmailOTP" enabled="true">
            <Parameter name="GmailClientId">gmailClientIdValue</Parameter>
            <Parameter name="GmailClientSecret">gmailClientSecretValue</Parameter>
            <Parameter name="SendgridAPIKey">sendgridAPIKeyValue</Parameter>
            <Parameter name="GmailRefreshToken">gmailRefreshTokenValue</Parameter>
            <Parameter name="GmailEmailEndpoint">https://www.googleapis.com/gmail/v1/users/[userId]/messages/send</Parameter>
            <Parameter name="SendgridEmailEndpoint">https://api.sendgrid.com/api/mail.send.json</Parameter>
            <Parameter name="accessTokenRequiredAPIs">Gmail</Parameter>
            <Parameter name="apiKeyHeaderRequiredAPIs">Sendgrid</Parameter>
            <Parameter name="SendgridFormData">sendgridFormDataValue</Parameter>
            <Parameter name="SendgridURLParams">sendgridURLParamsValue</Parameter>
            <Parameter name="GmailAuthTokenType">Bearer</Parameter>
            <Parameter name="GmailTokenEndpoint">https://www.googleapis.com/oauth2/v3/token</Parameter>
            <Parameter name="SendgridAuthTokenType">Bearer</Parameter>
            <Parameter name="redirectToMultiOptionPageOnFailure">false</Parameter>
        </AuthenticatorConfig>
`

Please mention if this configuration needs to be replaced by given configuration in the doc.

**Comment by shavidissa** [comment]
Thank you! I have updated docs for 5.4 and tested it end to end.

[1] https://docs.wso2.com/display/IS540/Configuring+Email+OTP
