### ISSUE TITLE
Provide information on manager users and role in the secondary user store in the primary tenant

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1562]
In [1] there is no indication of managing users and roles to the secondary user store in the primary tenant. Please include the information. This issue should not be resolved until all the operations are covered in this perspective (unless its the same parameter to be passed)

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addRole()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
