### ISSUE TITLE
Provide information on manager users and role in tenant domain through admin service

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1563]
Please provide the $subject in [1] to cater the following and this issue should not be resolved until all the operations are covered available through admin services

1. Tenant - primary user store
2. Tenant - secondary user store

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addRole()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
