### ISSUE TITLE
Searching for users having an underscore in their username gives multiple results that are incorrect

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#15638]
**Describe the issue:**
Searching for users having an underscore in their username gives multiple results that are incorrect when there are similar usernames on the server with a different character for the underscore.

For example, if there are usernames test.user and test_user, searching for the test_user user would return both test_user and test.user. 

**How to reproduce:**

- Switch to unique id jdbc userstore by adding the following configuration.
- Create two users test.user and test_user(you might need to configure the username regexes to allow these usernames).
- Now search for the test_user from the management console search box, both users would be returned.
- Enable password recovery from the resident IDP
- Try to recover the password for the test_user, the user would not be able to recover their password. The following error would be shown
```There are multiple users with username: test_user in the system, please send the correct user-store domain along with the username.```

**Expected behavior:**
When the search is done in the management console only the matching user should by returned and the password recovery should work for the user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]
 - Userstore: [JDBC]

The issue occurs because the underscore character is considered a single-character wildcard in databases. The [UserFilterWithIDSQL and UserFilterWithIDSQLCaseInsensitive](https://github.com/wso2/carbon-kernel/blob/d0718639852a0d13c61eb5ea3f3ec6182f33c53c/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L192-L195) queries should be fixed to escape this character. The same issue seems to be fixed in the normal JDBC userstore manager[2] but not in the unique id userstore manager class.

---

### Optional Fields

**Related issues:**
[1]https://github.com/wso2/product-is/issues/12649
[2]https://github.com/wso2/product-is/issues/6354

**Comment by sadilchamishka** [comment]
- https://github.com/wso2/carbon-kernel/pull/3552
