### ISSUE TITLE
Making editable content i18n compatible

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15630]
**Is your suggestion related to an experience ? Please describe.**
When displaying user editable content, those content should be translatable according to the user's demand. The current identity-apps implementations does not support that.

**Describe the improvement**
There should be a separate effort on making the editable content i18n compatible to address the above mentioned issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
