### ISSUE TITLE
Document should clearly mention the behavior of XACML policy when SaaS is enabled

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1564]
This issue is regarding the behavior of XACML policies when the SaaS option is enabled.
According to this [1] document, it is mentioned the below statement.

"In a SaaS scenario, the XACMAL policies that were created in the tenant domain in which the service provider was created will only get executed."

I have a SP as travelocity.com and I have enabled SaaS option. I have created a policy only to allow users belong to a particular role. E.g., finance role

Next I have created a tenant names ushani.com and have defined a different policy to allow users belong to a different role. E.g., sales

But when you have enabled SaaS, it will only apply the policy configured in super tenant. Policy applied in tenant is not applied in here.

Mentioned statement does not clearly say it. Please fix the doc

[1] https://docs.wso2.com/display/IS540/Configuring+Access+Control+Policy+for+a+Service+Provider

**Comment by sherenewso2** [comment]
In 5.4.0, the XACML policy that is created within the tenant that contains the SP (regardless of whether it is a specific tenant or super tenant) is enforced. 

However, in 5.3.0, only the XACML policy configured in super tenant is applied across all tenants.
Therefore, I updated this doc [1] with this statement:
_"In a SaaS scenario, only the XACMAL policies created in the super tenant will be enforced across all tenants. "_

[1] https://docs.wso2.com/display/IS530/Configuring+Access+Control+Policy+for+a+Service+Provider
