### ISSUE TITLE
outbound passive sts not support correctly claims mapping

### ISSUE THREAD

**Issue by AVPavlov111** [wso2/product-is#15657]
**Describe the issue:**
The xml RequestSecurityTokenResponse is not being parsed correctly. The AttributeName attribute is not supported. Additionally, multi-valued attributes are not supported.

**How to reproduce:**
Configure an Identity Provider using the WS-Federation (Passive) protocol. Authenticate through this Identity Provider. An xml response will be received at /commonauth.

<t:RequestSecurityTokenResponse xmlns:t="http://schemas.xmlsoap.org/ws/2005/02/trust">
    <t:Lifetime>
        <wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            2023-03-27T06:05:05.433Z
        </wsu:Created>
        <wsu:Expires xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            2023-03-27T07:05:05.433Z
        </wsu:Expires>
    </t:Lifetime>
    <wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
            <wsa:Address>urn:wso2is-test2</wsa:Address>
        </wsa:EndpointReference>
    </wsp:AppliesTo>
    <t:RequestedSecurityToken>
        <saml:Assertion MajorVersion="1" MinorVersion="1" AssertionID="_9f324d1f-6468-439e-86e8-d054bbf7d21a"
                        Issuer="http://stsservice.local/services/trust" IssueInstant="2023-03-27T06:05:06.293Z"
                        xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion">
            <saml:Conditions NotBefore="2023-03-27T06:05:05.433Z" NotOnOrAfter="2023-03-27T07:05:05.433Z">
                <saml:AudienceRestrictionCondition>
                    <saml:Audience>urn:wso2is-test2</saml:Audience>
                </saml:AudienceRestrictionCondition>
            </saml:Conditions>
            <saml:AttributeStatement>
                <saml:Subject>
                    <saml:NameIdentifier>test_user</saml:NameIdentifier>
                    <saml:SubjectConfirmation>
                        <saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer</saml:ConfirmationMethod>
                    </saml:SubjectConfirmation>
                </saml:Subject>
                <saml:Attribute AttributeName="emailaddress"
                                AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims">
                    <saml:AttributeValue>jhvbad@kjhg.test</saml:AttributeValue>
                </saml:Attribute>
                <saml:Attribute AttributeName="upn"
                                AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims">
                    <saml:AttributeValue>user@test.test</saml:AttributeValue>
                </saml:Attribute>
                <saml:Attribute AttributeName="givenname"
                                AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims">
                    <saml:AttributeValue>givenname</saml:AttributeValue>
                </saml:Attribute>               
                <saml:Attribute AttributeName="role"
                                AttributeNamespace="http://schemas.microsoft.com/ws/2008/06/identity/claims">
                    <saml:AttributeValue>Users</saml:AttributeValue>
                    <saml:AttributeValue>Domain Users</saml:AttributeValue>
                    <saml:AttributeValue>AllAgreementParticipants</saml:AttributeValue>
                    <saml:AttributeValue>Role1</saml:AttributeValue>
                    <saml:AttributeValue>Role2</saml:AttributeValue>
                </saml:Attribute>
            </saml:AttributeStatement>
            <saml:AuthenticationStatement AuthenticationMethod="urn:oasis:names:tc:SAML:1.0:am:password"
                                          AuthenticationInstant="2023-03-27T06:05:05.355Z">
                <saml:Subject>
                    <saml:NameIdentifier>test_user</saml:NameIdentifier>
                    <saml:SubjectConfirmation>
                        <saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer</saml:ConfirmationMethod>
                    </saml:SubjectConfirmation>
                </saml:Subject>
            </saml:AuthenticationStatement>          
        </saml:Assertion>
    </t:RequestedSecurityToken>
    <t:TokenType>urn:oasis:names:tc:SAML:1.0:assertion</t:TokenType>
    <t:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</t:RequestType>
    <t:KeyType>http://schemas.xmlsoap.org/ws/2005/05/identity/NoProofKey</t:KeyType>
</t:RequestSecurityTokenResponse>

**Expected behavior:**
It is expected that the claims from the AttributeStatement section will be correctly mapped:
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress -> "jhvbad@kjhg.test"
http://schemas.microsoft.com/ws/2008/06/identity/claims/role -> "Users, Domain Users, AllAgreementParticipants, Role1, Role2".

But now it maps only by namespase and take last AttributeValue from Attribute

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
