### ISSUE TITLE
Local claim mapping does not work for WS-Federation (passive) configuration when PassiveSTS is used as SP

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1566]
**Environment**
Standalone 5.4.0 GA pack
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**

1. Run Standalone IS 5.4.0 GA pack
2. Configure PassiveSTS as a service provider using WS-Federation (passive) configuration [1]
3. Configure a Local claim dialect configuration as in [2]
4. Access http://localhost:8080/PassiveSTSSampleApp/index.jsp
5. Error message will be displayed as in [3]

**Observation**
When a claim is not configured / a custom claim mapping configuration is done for SP passive sts it works fine. But When a Local claim dialect configuration is done unable to login to Passive sts home page.

Following Error is thrown in the backend

[2017-12-14 15:24:51,037] ERROR {org.wso2.carbon.identity.sts.passive.PassiveSTSService} -  org.apache.rahas.TrustException: Error in creating a SAMLToken using Opensaml library

[1]. passivests-config.png
[2]. passivests-local.png
[3]. passivests-error.png

![passivests-config](https://user-images.githubusercontent.com/31848014/33985623-2c462756-e0e1-11e7-80fb-39b02ff55ffc.png)
![passivests-local](https://user-images.githubusercontent.com/31848014/33986116-9f1c7374-e0e2-11e7-8a8b-30baeacc7704.png)
![passivests-error](https://user-images.githubusercontent.com/31848014/33986132-ac3a53b4-e0e2-11e7-8c2e-3e7e27ab222c.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
