### ISSUE TITLE
Incomplete Configuration and Instructions for Enabling Syslog with Log4j2 in Identity Server

### ISSUE THREAD

**Issue by lochanaEdirisinghe** [wso2/product-is#15661]
**Describe the issue:**
Despite the Syslog configurations being enabled as mentioned in the documentation[1], the logs are not being submitted to the syslog server.

**How to reproduce:**

To reproduce the issue, please follow the steps outlined below. 

1. First, uncomment the following properties in the log4j2.properties file:

> appender.syslog.type = Syslog
> appender.syslog.name = Syslog
> appender.syslog.host = localhost
> appender.syslog.port = 514
> appender.syslog.layout.type = PatternLayout
> appender.syslog.layout.pattern = [%d] [%tenantId] %5p {%c} - %mm%ex%n
> appender.syslog.filter.threshold.type = ThresholdFilter
> appender.syslog.filter.threshold.level = DEBUG

2. Add the syslog to the Appenders.

3. Next, configure the syslog-ng by installing it and adding the following configurations to the /etc/syslog-ng/syslog-ng.conf file:

Under Sources:

> #enable syslog UDP server on port 514
> source s_net { udp(ip(127.0.0.1) port(514)); };

Under Destinations:

> #Create log destination
> destination d_wso2 { file("/var/log/wso2.log"); };

Under Log Paths:

> #log the message received to s_net to d_wso2 after filtering log facility
> log { source(s_net); filter(f_user); destination(d_wso2); };

4. Finally, restart the syslog-ng by running the following command:

> sudo systemctl restart syslog-ng

After completing the above steps, start the IS. Then no logs will be printed in the /var/log/wso2.log file. However syslog is properly functioning with IS-5.8.0 and earlier versions, which use log4j, but it is not functioning correctly with the log4j2 version used in newer versions of IS.

**Expected behavior:**
Logs should be submitted to the Syslog server.

**To get this working:**
Need to define the following property which is not available in the log4j2.properties file.

> appender.syslog.protocol=UDP

Need to uncomment bellow line to add Syslog appender to the root loggers and need to change the syslog to **S**yslog.

> rootLogger.appenderRef.syslog.ref = Syslog

Now it should work.

As such, it is necessary to rectify the log4j2.properties file with accurate configurations and instructions. Furthermore, it is required to update the relevant documentations to reflect these changes.

[1] - https://is.docs.wso2.com/en/5.11.0//references/default-ports-of-wso2-products/#random-ports

**Environment information** 
 - Product Version: [IS 5.9.0, IS 5.10.0, IS 5.11.0, IS 6.0.0, IS 6.1.0]
---

**Comment by Thisara-Welmilla** [comment]
Fixed with https://github.com/wso2/product-is/pull/15662
