### ISSUE TITLE
Keystore is loaded for each passive STS login

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15668]
**Describe the issue:**
According to the implementation at [1], it loads the keystore from the file system for each and every login. This could cause a high resource usage. The info log is moved to debug with https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/134, but a better solution to this needs to be implemented.

[1] https://github.com/wso2-extensions/identity-inbound-auth-sts/blob/6dde60db4049633f5cc341309d8eb40ee22660e4/components/org.wso2.carbon.identity.sts.passive/src/main/java/org/wso2/carbon/identity/sts/passive/custom/provider/CustomCryptoProvider.java#L70

**How to reproduce:**
Login to a passive STS application. The following log will be written for each login.
```
INFO {org.wso2.carbon.identity.sts.passive.custom.provider.CustomCryptoProvider} - Loading keystore...
```

**Expected behavior:**
It should load the keystore once and keep in the cache

**Environment information** 
 - Product Version: IS 5.11.0 and later

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
