### ISSUE TITLE
Bug in the webapps saml2-web-app-pickup-dispatch.com and saml2-web-app-pickup-manager.com

### ISSUE THREAD

**Issue by dsmohan** [wso2/product-is#15665]
**Describe the issue:**
There seems to be some bug in the existing webapps (saml2-web-app-pickup-dispatch and saml2-web-app-pickup-manager) shared in the documentation [1] and present at [2]. As after deploying and running the webapps, when trying to login, the authentication request fails due to signature verification failure. However, after deployment of the webapps and replacing the existing wso2carbon.jks file in the webapps folder with the WSO2 IS wso2carbon.jks file, the issue gets resolved and I am able to login to the apps.
[1]: https://is.docs.wso2.com/en/5.9.0/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp
[2]: https://github.com/wso2/samples-is/releases

**How to reproduce:**
1. Start WSO2 IS server.
2. Download the webapps saml2-web-app-pickup-dispatch.war and saml2-web-app-pickup-manager.war from https://github.com/wso2/samples-is/releases.
3. Copy the .war files into the Tomcat webapps folder. For example, <TOMCAT_HOME>/apache-tomcat-/webapps.
4. Start the Tomcat server.
5. Configure the service provider in WSO2 IS Management Console as given in the document https://is.docs.wso2.com/en/5.9.0/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp.
6. Now, on trying to access the webapps http://localhost:8080/saml2-web-app-pickup-dispatch.com/index.jsp and http://localhost:8080/saml2-web-app-pickup-manager.com/index.jsp, the pages open. But, on clicking login, it shows the below page with authentication request error.
![image](https://user-images.githubusercontent.com/66669898/228490658-4d8f1236-b3a7-4632-9b0d-fb9d9391e1ed.png)

![image](https://user-images.githubusercontent.com/66669898/228489146-78b48eea-a228-4cc5-8f45-1ee9d52631ee.png)
In WSO2 carbon logs, the below signature validation failure error can be seen.
 `{org.wso2.carbon.identity.sso.saml.validators.SPInitSSOAuthnRequestValidator} - Signature validation for Authentication Request failed for the request of Issuer :saml2-web-app-pickup-dispatch.com in tenantDomain:carbon.super
`

**Expected behavior:**
The expected behavior is when we click on login after the webapp page opens, it should redirect to WSO2 IS login page for authentication and authorization.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: WSO2 IS - 5.11.0
 - OS: WSO2 IS - 5.11.0
 - JDK: openjdk version "11.0.5"
 - Application Server: Apache Tomcat - 8.5.87

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
