### ISSUE TITLE
Enable sending headers with HTTP requests

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#15679]
**Is your suggestion related to an experience ? Please describe.**
Sending additional headers with HTTP requests in adaptive scripts is not supported currently. We need to improve HTTP methods to support this capability.

There's an already existing PR [1] which provides this capability. We need to finalize the implementation and get the PR merged.

[1] https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/107

**Comment by PasinduYeshan** [comment]
This issue is fixed.
Feature -  [PR](https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/140)
Docs - [PR](https://github.com/wso2/docs-is/pull/3903)
