### ISSUE TITLE
[APIM-3.1.0] LDAP authentication is not working when certain special characters are there in password

### ISSUE THREAD

**Issue by sujeetkv** [wso2/product-is#15675]
**Describe the issue:**
In APIM-3.1.0, when we use org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager as secondary user store, it is not able to authenticate users having special characters in password like '%' sign. In this case it simply returns invalid credentials response for login action.

**How to reproduce:**
N/A

**Expected behavior:**
LDAP authentication for passwords having special characters.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: APIM 3.1.0
 - OS: Windows
 - Database: MySQL, H2
 - Userstore: JDBC, LDAP

---

### Optional Fields

**Related issues:**
https://github.com/wso2/api-manager/issues/1693

**Suggested labels:**
APIM - 3.1.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
