### ISSUE TITLE
Include sample responses for user and role management through admin services for all operations

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1567]
Please include sample responses for all the operations with sample values in [1] . This is very useful for developers who will be using this in an application to continue the work flow

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-getUserList()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
