### ISSUE TITLE
DisableEmailUserNameValidation cannot be configured from the deployment.toml in IS-5.10.0

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#15678]
**Describe the issue:**
Methods reading the DisableEmailUserNameValidation in the carbon.xml file has been backported with a fix[1] for the 5.10.0 version, however, the  DisableEmailUserNameValidation cannot be configured from the deployment.toml in IS-5.10.0 like in newer versions

[tenant_mgt]
enable_email_domain= true
disable_email_domain_validation = true

The disable_email_domain_validation should be templated in the carbon.xml.j2 file.

    {% if tenant_mgt.disable_email_domain_validation is defined %}
      <DisableEmailUserNameValidation>{{tenant_mgt.disable_email_domain_validation}}</DisableEmailUserNameValidation>
    {% endif %}

**Expected behavior:**
The configuration should be set the configuration to true or false. when the email username is enabled, both email user name (bob@gmail.com) and non-email user names (alice)[2] can be used only when DisableEmailUserNameValidation is set to true.

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]

[1]https://github.com/wso2/product-is/issues/15327
[2]https://is.docs.wso2.com/en/5.10.0/learn/using-email-address-as-the-username/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
