### ISSUE TITLE
Doc Feedback: link missing for configuring adaptive authentication

### ISSUE THREAD

**Issue by Akila94** [wso2/product-is#15685]
Location : https://is.docs.wso2.com/en/5.9.0/learn/working-with-acr-and-amr/

Under the topic ```Using ACR with WSO2 Identity Server```, the link is missing for ```Configuring Adaptive Authentication```.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
