### ISSUE TITLE
API based authentication

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#15684]
**Is your feature request related to a problem? Please describe.**
When developing applications(especially native apps) developers look at implementing their login flows within apps itself where they target more on UX. This is especially in mobile development where the application authentication is not smooth with a browser interaction in the middle. Currently, IS does not have a complete api based authentication flow. While the oauth2 password grant is available for API based authentication it doesn’t fulfil the complete authentication needs such as using MFA, federated login, adaptive authentication, etc.

**Describe the solution you would prefer**
To cater for the above IS needs to provide an API based authentication capability in which it will provide the app developer the capability to embed a complete authentication capability within the application. This will support MFA, including adaptive authentication via APIs. And also support invoking federated authentication which, however, will need a browser-based flow due to its nature.

**Related issues**
Samples: https://github.com/wso2/product-is/issues/16373
SDKs: https://github.com/wso2/product-is/issues/16374

**Comment by Thumimku** [comment]
To enable API_Based_Authenication for an appilication, You have to update the application configuration.
Send a patch request to application management end point.
```
{
    "advancedConfigurations": {
        "enableAPIBasedAuthentication": true
      }
}
```
