### ISSUE TITLE
Doc Feedback: Encrypting passwords using cypher tool 

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#15689]
The below error is getting if we have the comments between the properties of the [secrets] section in the deployment.toml file. 

Configuration: 
```
[secrets]
java_keystore_password = "[wso2carbon]"
#comment
wso2_super_admin = "[admin]"

```

Error:

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.lang.String.concat(String.java:1937)
	at org.wso2.ciphertool.CipherTool.updateDeploymentConfigurationWithEncryptedKeys(CipherTool.java:394)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:75)
```

After getting the error, only the passwords that were added before the comment are encrypted and the others configurations are disappearing from the deployment.toml file. 

```
[secrets]
java_keystore_password  = "Xlz6exAOC/2/a+nUaquEPdE5onB2rAvJ8cr4qwRqKqqbiw3pd8ugbRk6MzW93NRpim8c5OVVH256VjTx+VfNqL40y2Lg6Q9B1iA7g/84QTrVSBsZyM7dbXkATg+MXYNCZdALpuO3mMnrcX0vr2pyfrI5HcBb5CrDd2x/6UhzSo6BgDeCOx1jIjGPc4AxdUIAkK2/qZdY/ULOtx1SPUvQwUCRRYcmEYfE1IZv5NFxdWYAa1GoTf35XmeTy1dZHZJnNGvnihB5vy81e241cAdPEWRLwZRqDRu0fq2vzEigSyGskM7bvntefedrbVtYWdFRevTdzqMStRaL+BaMtanUcw=="
<>
```

Can we document there shouldn't have any comments between the properties in the [secrets] section in deployment.toml file?

Related Git issue: https://github.com/wso2/cipher-tool/issues/60

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
