### ISSUE TITLE
Resend Email functionality is not working in the self registration flow.

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#15701]
THe resend email feature is not working in the self-registration email verification for tenants.

<img width="542" alt="Screenshot 2023-04-03 at 18 31 56" src="https://user-images.githubusercontent.com/29885846/229522422-c0b2c300-4e63-42bd-88c5-25c4f52b9f56.png">

This issue is in the self-registration flow for tenants. For the super tenant, this is working as expected.
Seems this issue is caused because we are invoking the super tenant's  "/api/identity/user/v1.0/resend-code" API even for the users in the tenant. When we use the tenanted API(/t/<tenant>/api/identity/user/v1.0/resend-code)  the resend email is working fine. 

In the authenticationendpoint/basicauth.jsp file the tenant domain is retrieving from [1] and it is returning the correct tenant name if we have entered the tenant name appended username from the UI. The Resend email is received if we enter the username which contains the tenantDomain.
Eg : testuser-22@tenant1.com

Other times it is not working.
Eg : testuser-22

[1]https://github.com/wso2/carbon-identity-framework/blob/v5.18.187/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/AuthenticationEndpointUtil.java#L115

Product : wso2is-5.11.0

**Comment by mpmadhavig** [comment]
### How to reproduce

1. Create a tenant
2. Enable self regsitration in the created tenant.
3. Create an OIDC application in the tenant and get the client id.
4. Goto a login page (say myaccount) and follow the create an account flow.
5. Do not click on the verification email URL.
6. Paste the following auth call in the broswer and replace, <CLIENT_ID> and <REDIRECT_URL> with your application values.

`https://localhost:9443/authenticationendpoi/login.do?client_id=T4I8EWc52TNesNJ7eSpaY1CfMKIa&commonAuthCallerPath=%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Flocalhost%3A3000&response_type=code&scope=openid+address+email+profile&tenantDomain=mad.com&sessionDataKey=0f1e578f-3d39-44d6-95da-c5239b02f2ac&relyingParty=T4I8EWc52TNesNJ7eSpaY1CfMKIa&type=oidc&sp=sample&isSaaSApp=false&authenticators=BasicAuthenticator%3ALOCAL`

7. Try adding the created (but not verified) user's credentials. Type the username without tenant domain. Click login.
8. You will get the above mentioned page with a warning saying that user account hasn't been verified. Then click on the Resend email option.
