### ISSUE TITLE
Scope required for scim2/Bulk for user creation are incomplete in documentation

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#15706]
**Is your suggestion related to a missing or misleading document? Please describe.**

In Identity server 5.11 scim2/Bulk api specification [1] includes required scopes as  *internal_user_mgt_create*

But it includes more scopes to create users in bulk using this endpoint.
**Describe the improvement**

Scope required:
* internal_user_mgt_create
* internal_user_mgt_list
* internal_user_mgt_view
* internal_user_mgt_delete
---

### Optional Fields

**Additional context**

[1] - https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Bulk%20Endpoint/createBulkUsers
**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
