### ISSUE TITLE
Document should mention that the policies defined in a particular tenant for a SP is applied for all the users across the same tenant

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1570]
1. User Admin creates XACML policy which allows to travelocity.com sp and users in finance role and deny for other roles
2. user1 logs in and creates a SP as travelocity.com.
3. Now a user from finance role logs in and can login to travelocity.com
4. Now a user from a other role logs in to travelocity.com and cannot login.

So the particular policy is applied users across the tenant.
Document [1] should clearly mention this. 

[1] https://docs.wso2.com/display/IS540/Configuring+Access+Control+Policy+for+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
