### ISSUE TITLE
Introduce partitioning to the token, session and scope tables

### ISSUE THREAD

**Issue by NishanthiWi** [wso2/product-is#15718]
**Is your suggestion related to an experience ? Please describe.**
_Performance degrade over the time in DB server due to the defragmentation. This requires the optimisation in DB server to resolve_

**Describe the improvement**
_Token, Session & scope tables are transactional tables. There is an expiry for the records & those records are not used in functional workflows after the expiry.  Right now we have two mechanisms to clear these records (programatically & using DB procedure) from the tables in order to improve the search performances by reducing row count to scan. But as per the delete operation in DB,  it does not reclaim the space for the particular record in the table and in the index. So this leads to the performance degrade due to the defragmentation of tables over the time._ 

_As per the information available, we can get rid of the defragmentation with partitioning as we can drop off the particular partition at once. and we have the opportunity of  gaining a performance improvement in the select queries as we need to do the row scan with in only the particular active partition_

**Additional context**
_There is a limitation in the mysql & lower versions than 12 of postgresql that table partitioning is not possible with Foreign Keys. Here are the transactional tables that customer is looking for.
idn_auth_session_store, idn_oauth2_access_token, idn_oauth2_access_token_scope_

_Token & Scope tables are with FKs._

This is to study the benefits & feasibility of applying the partition for transactional tables along with redesigning the particular tables by removing the FKs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
