### ISSUE TITLE
Inconsistency in IDP objects created through console and mgt console

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15713]
**Describe the issue:**
When an IdP is created through the mgt console, even if only 1 authenticator is enabled/configured db entries will be added for all available authenticator types with the enabled property false and empty property values. But if an IdP is created through the console, only the authenticators a user configure, will be added to the db.

<img width="606" alt="Screenshot 2023-04-11 at 12 13 13" src="https://user-images.githubusercontent.com/47671237/231077759-8a756b01-997a-4680-81d9-1445d1691b92.png">

In the above instance, IdP with ID 8 is the IdP created using the mgt console and the rest of the IdPs are created using the console.  Note that there are multiple entries with other authenticators for IdP 8 even though only facebook authenticator was configured and note that for other IDP IDs there are only a few authenticator entries that were intentionally configured.

**How to reproduce:**
1. Create an Expert Mode IdP using console.
2. Add an authenticator (Twitter).
3. Check available authenticators listed for that IdP in the Settings tab.
4. Log into the mgt console and create a new IdP.
5. Add an authenticator under Federated Authenticators (Twitter).
6. Log into the console and check the Settings sections of that IdP.

For the Idp created through the console, it can be noted that only Twitter will be available under settings. But for the idp created through the mgt console, all the authenticators will be listed under settings with empty values for their properties.

**Expected behavior:**
When creating an IdP through the mgt console, only the configured authenticator details should be added to the db.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 6.2.0-m1-SNAPSHOT
 - Database: H2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by melanisilva** [comment]
This is expected to be resolved with the management console depreciation in future
