### ISSUE TITLE
Update documentation on how to host Authentication and Recovery Endpoint on a Different Server.

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#15714]
The official doc on hosting both Authentication and Recovery Endpoint on a Different Server is outdated. Need to be updated them.
Also we need to update the 6.0 and 6.1 official documentations as well.

Please refer (contains only for authentication portal): https://imalsha-sg.medium.com/externally-hosting-wso2-identity-server-portals-36330e00d456

**Comment by sadilchamishka** [comment]
- https://github.com/wso2/product-is/issues/15721#issuecomment-1514961506
