### ISSUE TITLE
WS-Federation namespace missing in the claim name

### ISSUE THREAD

**Issue by isuru-udayanga** [wso2/product-is#15717]
**Describe the issue:**
In the RequestSecurityTokenResponse, namespace missing in the claim name

Response from the new stack (5.11.0):
```
<saml1:Attribute AttributeName="role" AttributeNamespace="http://wso2.org/claims">
     <saml1:AttributeValue xsi:type="xsd:string">Internal/everyone,role1,role2</saml1:AttributeValue>
</saml1:Attribute> 
```
**How to reproduce:**
Execute WS-Federation flow in IS 5.11.0 [1]

**Expected behavior:**
Response from the old stack (5.6.0):
```
<Attribute AttributeName="Role" AttributeNamespace="http://wso2.org/claims/role">
     <AttributeValue>Internal/everyone,role1,role2</AttributeValue>
</Attribute>
```

[1] - https://is.docs.wso2.com/en/5.11.0/develop/service-provider-configurations-used-with-apis/#configuring-ws-federation-passive

**Comment by ImalshaG** [comment]
Closing this issue as the fix is done by https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/132

**Comment by pamodaaw** [comment]
Master Fixes

https://github.com/wso2/carbon-identity-framework/pull/8173
https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/199
