### ISSUE TITLE
Implement extension management service

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#15725]
**Describe the improvement**
Currently the identity-provider and application templates are stored as files within the frontend codebase.

This improvement is to move those files to a backend service . Then we can fetch the resources like templates, metadata or other artifacts related to the extensions (applications, identity-providers etc).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
