### ISSUE TITLE
scope not getting retrieved for the getAuthorizationCodesByUserForOpenidScope method

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#15724]
**Describe the issue:**
Previously, the requested scopes are stored as a single string in the IDN_OAUTH2_AUTHORIZATION_CODE table. But since this is not scalable when a large number of scopes are requested, these are persisted in IDN_OAUTH2_AUTHZ_CODE_SCOPE table as an improvement through https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1201/files#diff-1d5bcbf2ee71e214ee17991683b7e86dcb24ccaffa6680872634728dd1a820f9L100.

However, at [`removeTokensFromCache`](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.4.111/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/listener/IdentityOathEventListener.java#L267), the auth codes related to the openid scopes are obtained using `SCOPE LIKE '%openid%'` as follows.
```
SELECT DISTINCT AUTHORIZATION_CODE, TIME_CREATED, VALIDITY_PERIOD, CODE_ID, SCOPE, IDN_OAUTH2_AUTHORIZATION_CODE.CALLBACK_URL, CONSUMER_KEY FROM IDN_OAUTH2_AUTHORIZATION_CODE JOIN IDN_OAUTH_CONSUMER_APPS ON IDN_OAUTH2_AUTHORIZATION_CODE.CONSUMER_KEY_ID=IDN_OAUTH_CONSUMER_APPS.ID WHERE AUTHZ_USER=? AND IDN_OAUTH2_AUTHORIZATION_CODE.TENANT_ID=? AND IDN_OAUTH2_AUTHORIZATION_CODE.USER_DOMAIN=? AND STATE=? AND SCOPE LIKE '%openid%'
```
This causes performance degradation due to the full table scan caused by the LIKE statement. Further, this will return an empty result due to the fix indicated above. Therefore, this query becomes invalid since the scopes are no longer added to IDN_OAUTH2_AUTHORIZATION_CODE table. Instead, we should do a JOIN of the two tables IDN_OAUTH2_AUTHORIZATION_CODE and IDN_OAUTH2_AUTHZ_CODE_SCOPE and filter any row with SCOPE='openid' to identify tokens issued for OpenID Connect flows.

We need to check for similar queries that refer to the SCOPE column of IDN_OAUTH2_AUTHORIZATION_CODE table and modify them to use the IDN_OAUTH2_AUTHZ_CODE_SCOPE table instead.

**How to reproduce:**
Trigger some events such as doPreSetUserClaimValue (you may enable the idle lock feature, which will update the last login claim during the authentication flow. If otherwise, you may update a user claim of any user, having an authorization code).

**Environment information**
 - Product Version: All the supported versions

**Comment by mpmadhavig** [comment]
### Update
The following SQL queries defined in the given repo are identified as problematics and need to be fixed as those queries retrieve the scope variable from the `IDN_OAUTH2_AUTHORIZATION_CODE` table.

1. `VALIDATE_AUTHZ_CODE_WITH_PKCE`
2. `VALIDATE_AUTHZ_CODE_WITH_PKCE_IDP_NAME`
3. `GET_OPEN_ID_AUTHORIZATION_CODE_DATA_BY_AUTHZUSER`
4. `LIST_LATEST_AUTHZ_CODES_IN_USER_DOMAIN`
5. `LIST_LATEST_AUTHZ_CODES_IN_USER_DOMAIN_IDP_NAME `
6. `LIST_LATEST_AUTHZ_CODES_IN_TENANT`
7. `LIST_LATEST_AUTHZ_CODES_IN_TENANT_IDP_NAME`
8. `GET_DETAILED_ACTIVE_AUTHORIZATION_CODES_FOR_CONSUMER_KEY`

The `IDN_OAUTH2_AUTHORIZATION_CODE` table has been used in several other queries but those does not cause any issues as the scope field is not getting retrieved.

**Comment by mpmadhavig** [comment]
### Affected product versions

- 5.10 and above
