### ISSUE TITLE
Generalized approach to handle user attributes of large user bases in RDBMs user stores

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#15720]
The current product architecture manages users attributes key value pairs and this is mainly to keep the user attribute schema as flexible as possible. However, when the user base is significantly large (in millions) and there are multiple attributes per user, the records in the user attribute table increases significantly. This will lead to performance issues high DB resource utilization, specially when performing search operations for users based on attribute. 

Therefore, for such cases, we need to provide recommendations on how to improve the user attribute storage to optimize the performance along with the corresponding changes to user store manager.

Some considerations

- Moving the the attributes to table columns instead of having key pairs (much suited when the attributes are static)
- Moving the static attributes to table columns and maintain dynamic attributes as key value pairs
- Storing attributes as JSON values using native JSON data type in the database

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
