### ISSUE TITLE
Configuring Single Sign-On should have a section on how to test this for tenants

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1572]
Configuring Single Sign-On doc [1] should have a section on how to test this for tenants. This is explained in this doc [2] under **Testing with tenants** section.
It would be better to put a special note in [1] and link to that section. Since this cannot be located quickly in documentation. 

[1] https://docs.wso2.com/display/IS540/Configuring+Single+Sign-On
[2] https://docs.wso2.com/display/IS540/Configuring+a+SP+and+IdP+Using+Configuration+Files

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
