### ISSUE TITLE
UnsupportedOperationException during user login using SMSAuthenticator

### ISSUE THREAD

**Issue by imesh94** [wso2/product-is#15728]
**Describe the issue:**
When SMSAuthenticator is configured as the second authentication step, an UnsupportedOperationException is thrown after the first authentication step.

This is due to trying to modify an immutable object in DefaultRequestCoordinator.

https://github.com/wso2-support/carbon-identity-framework/blob/support-5.23.8.x-full/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultRequestCoordinator.java#L267

https://github.com/wso2-support/carbon-identity-framework/blob/support-5.23.8.x-full/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/AbstractApplicationAuthenticator.java#L373

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0
 - OS: Mac
 - Database: MySql

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by imesh94** [comment]
Reopening to fix for IS 6.1.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
