### ISSUE TITLE
Integrate Identity Verification for Identity Server

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#15730]
## Description

Identity verification(IDV), is a crucial component of managing user access and verifying identities in systems and platforms, such as customer identity and access management (CIAM) and access management (AM). It enables organizations to confirm the identity of users through various authentication methods, such as by checking legal documents, like passports, national identification cards, and driver's licenses.

IDV is a critical aspect of security and risk management, as it helps to prevent identity fraud and ensures that only authorized individuals have access to sensitive systems and data. By implementing IDV, organizations can protect themselves from potential threats and enhance the overall security of their systems.

By integrating identity verification capabilities identity server should be able to support multiple integrations with identity verification providers. 

**This should enable triggering an IDV process at user registration or authentication flow of an application, managing verified identity attributes and sharing those with the application, and decide on access control decisions based on the verification**

Migration: https://github.com/wso2/product-is/issues/15950
Documentation: https://github.com/wso2/docs-is/pull/3813

**Comment by ashensw** [comment]
This is onhold until https://github.com/wso2/product-is/issues/15746 is completed.

**Comment by AfraHussaindeen** [comment]
Closing this as the feature delivery is completed both in Identity Server and Asgardeo
