### ISSUE TITLE
Provide sample profile value in getUserClaimValue() operation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1573]
In [1] it states an example profile value is not given. Please provide a sample value for the profile in the request

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-getUserClaimValue()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
