### ISSUE TITLE
Investigate on Usecase parameter in Advanced Email OTP configurations

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#15731]
In the  advanced configuration of Email OTP (https://is.docs.wso2.com/en/latest/guides/mfa/email-otp-config-advanced/) there is  `usecase` config and we need to re-analyse the purpose of `usecase` config.
The config usecase is introduced to tackle a different scenario https://github.com/wso2/product-is/issues/4242 which we need to validate again & check whether we need to improve. We also need to improve the documentation here https://is.docs.wso2.com/en/latest/guides/mfa/email-otp-config-advanced/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
