### ISSUE TITLE
Doc improvemrnt on usecase parameter in Advanced Email OTP configurations

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#15732]
In the advanced configurations of the email OTP, there is the`usecase` config. 
By default `usecase` config is empty by default and that's [recommended flow](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/33/files#diff-64287a507e2f28fd63b8a663df5180ba9e5091fc3209309f34dcaab1efdd52f6R178). But in advance configurations it's defined as local and said it is the default value, We need to fix the doc.
https://is.docs.wso2.com/en/latest/guides/mfa/email-otp-config-advanced/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
