### ISSUE TITLE
Allow non-email usernames when email as username is enabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15744]
**Is your suggestion related to a missing or misleading document? Please describe.**

The new configuration introduced with https://github.com/wso2/product-is/issues/10760#issuecomment-873862021 needs to be documented.

To get both username and email-username working, add the following configuration in the deployment.toml file.
```
[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true
```

Doc: https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
