### ISSUE TITLE
Identify different requests types while calling to token endpoint using different grant types

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1574]
**Documentation:** Setting Up Service Provider for Inbound Provisioning [1].

**Issue Identified:**
Under the "Testing the provisioning" topic, we have to identify, that request may vary depending on the grant type we used. 

Ex: Password grant type only gonna have the following request:

`curl -v -k --header "Authorization: Bearer 955fded39fc6cb08525b5f2a35b3e2e"  --data '{"schemas":[],"name":{"familyName":"fernando","givenName":"yohanna"},"userName":"yohanna","password":"yohanna","emails":[{"primary":true,"value":"yohanna@wso2.com"}]}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users`

[1] https://docs.wso2.com/display/IS540/Setting+Up+Service+Provider+for+Inbound+Provisioning

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
