### ISSUE TITLE
Incorrect Information in Email Address as the Username

### ISSUE THREAD

**Issue by Anandi-K** [wso2/product-is#15745]
### Description :
In the documentation [1] it states that
```
- With these configuration users can log in to super tenant with both email username (alex@gmail.com) or non-email usernames (larry). However, for tenants, only email usernames are allowed. (tod@gmail.com@wso2.com).
- You can configure email username without enabling the enable_email_domain property (step 5). Then users can log in to both the super tenant and the tenant using email and non-email usernames. However, super tenant users should always use @carbon.super at the end of usernames.
```
Regarding the first point, when the steps mentioned in the documentation are followed, adding users with non-email usernames manually via management console [2] and by self registration [3] is not allowed. Also, already existing users with non-email usernames (before adding the configurations) also cannot login to SPs [4].

When enable_email_domain property is not enabled (as mentioned in the second point), we still cannot add users with non-email usernames [2][3]. But already existing users with non-email usernames can login without adding @carbon.super at the end of the username, only email-usernames are required add the this.

This information has been there since IS 5.3.0. It is better to test the flow and update this information since it can be misleading.

### Relates Issues:
https://github.com/wso2-enterprise/wso2-iam-internal/issues/280

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/
[2] ![adduser](https://user-images.githubusercontent.com/95691934/214228970-54e69bb2-fbe1-4f23-93ce-905d22ab772a.png)
[3] 
![self](https://user-images.githubusercontent.com/95691934/214228910-60a5255c-19bd-4094-a4e2-1f0610e9b983.png)
[4]
![login](https://user-images.githubusercontent.com/95691934/214228861-f76de736-1a58-40f9-9c28-2c29b59f55f9.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
