### ISSUE TITLE
Improve FIDO documentation

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#15757]
**Is your suggestion related to a missing or misleading document? Please describe.**
Below improvements should be done for FIDO related documentations.
- Improve docs with WSO2 FIDO flow probably with a sequence diagram (How an application, WSO2 IS, browser Webauthn and FIDO device interacts).
- Document FIDO API related error codes and responses.
- FIDO device support matrix if possible.

**Describe the improvement**
Improve docs as per above facts.

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by adeesha-savinda** [comment]
Better if we can try to provide a sample demo application on the details of how to invoke FIDO APIs if possible. We can always share my account portal [1] with anyone who requests a reference. But, it will be too complex. A simple implementation of registering, listing all registered devices, and deleting a device would be sufficient.

[1] https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/components/multi-factor-authentication/authenticators/fido-authenticator.tsx

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
