### ISSUE TITLE
[Doc] Insufficent information in Login to Salesforce with Integrated Windows Authentication Page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1575]
I am referring [1] in order to SSO with Salesforce via IWA authenticators.

In this Document, we have to mention before doing the salesforce SSO configuration and IS service provider config, we need to configure the IWA in IS server.
In the Document, we just point out how to do the SSO with Identity server Using IWA as the related links.(not as a must)
But this should be added as pre step before doing the Salesforce configuration 

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
