### ISSUE TITLE
Capability to detect FIDO device registration during authentication flow

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#15755]
**Is your suggestion related to an experience ? Please describe.**
Currently there's no way to identify whether a user has registered FIDO devices prior to prompting FIDO authentication. The requirement is to prompt for another authentication method when a FIDO key is not registered.

If the IDF (Identifier First) is configured as step 1 and FIDO is configured as step 2, the FIDO connector itself detects for registered devices and redirects to a error page. However this is a backend redirection and hence not able to capture with the adaptive script failure block.

**Describe the improvement**
One option is to have direct support for this by providing with a preconfigured authenticator with a adaptive script. We should implement a adaptive authentication function to check user device availability by invoking the [FIDO2 WebAuthn service](https://github.com/wso2-extensions/identity-local-auth-fido/blob/82dafbac6b875c7026368c27f3f779e30892d2b5/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java#L502). Then could provide an adaptive authentication template to configure this flow easily.

Another option is to improve the backend code to fail the authentication without being redirected to a error page. Redirection should be handled from the frontend. However need to evaluate the possibility of this approach.

**Additional context**

**Comment by ThaminduDilshan** [comment]
A sample customization approach with a custom adaptive function
- https://medium.com/@thamindudilshan/writing-a-custom-adaptive-authentication-function-to-detect-fido2-device-registrations-87f9a9929731

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
