### ISSUE TITLE
Issue with Setting Headers in Different Flows

### ISSUE THREAD

**Issue by AwesomeNipun** [wso2/product-is#15753]
**Describe the issue:**

Currently, in the password-recovery and self-registration-with-verification JSPs (JavaServer Pages), the headers required for the request, such as for reCAPTCHA verification, are set directly in the JSPs. However, in flows like login, the request headers are set in the backend.
This inconsistency in setting headers poses a problem when there is a need to add a new header to the request in flows like login.

**Comment by AwesomeNipun** [comment]
Setting headers for the login flow was done using the BasicAuthenticator in the wso2-extensions/identity-local-auth-basicauth repo.

## Related PRs
- https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/174

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
