### ISSUE TITLE
[Doc] Need an alteration in page "Logging in to Salesforce with Integrated Windows Authentication"

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1577]
In signup page, we have the older salesforce UI. please update with following.

![salesforcesignup](https://user-images.githubusercontent.com/14923354/33992180-a0cd05d4-e0f7-11e7-8781-178e0bc695cc.png)

Likewise, please update all the older UI screeenshots in this page.

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
