### ISSUE TITLE
Update the defaultly provided callback url regex patterns in the product

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#15773]
### **Describe the issue:**
The default provided callback url regex patterns need to be updated with valid/working ones. Please find the list of callback URL regex configurable places I have found from the below list.

1. Self Regsitration
2. Lite User Registration
3. Account Recovery

Note: Apart from updating the default regex patterns, need to update the documentation as well.

### **How to reproduce:**
1. Configure one of the above flows and add an invalid URL `ex: google.com` for the callback url.
2. You will be redirected to this URL at the end of the flow without a problem.

### **Expected behavior:**
- An error page should be appear saying the URL is invalid when compared with the given regex.

### **Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Latest
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by mpmadhavig** [comment]
The agreed new default callback URL suggestion: `^https:\/\/localhost:9443\/.*`

**Comment by Shenali-SJ** [comment]
Could not reproduce the error in the lite user registration component as the flow is currently not working. Thus the regex pattern of the callback URL in lite user registration is not updated.
