### ISSUE TITLE
Unable to add the IDP role mappings after removing the existing roles

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1578]
**Environment**
Standalone
JDK -1.8
DB - H2
Browser  - Chrome Version 58.0.3029.96

**Steps to recreate the Issue**
1. Create an IDP
2. Go to Role mapping section and add few roles
![defineroles](https://user-images.githubusercontent.com/14962228/33992540-0ddf28c2-e0f9-11e7-966e-8cee8b0d5611.png)
3. Then remove the roles
![delete_roles](https://user-images.githubusercontent.com/14962228/33992557-1d51f550-e0f9-11e7-9e67-c835595f63ab.png)
4. Now Click the "Add Role Mapping" option to add another role name
![add_role](https://user-images.githubusercontent.com/14962228/33992588-40f51564-e0f9-11e7-9870-36f929ec4aa6.png)

**Observations**
Unable to add the role mapping to IDP (Need to restart or refresh the browser)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
