### ISSUE TITLE
The OP iframe response status descriptions are invaid 

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#15782]
The OP iframe response status(changed, unchanged) descriptions are invalid[1].

[1]https://is.docs.wso2.com/en/latest/references/concepts/authentication/session-management/#how-does-openid-connect-session-management-work

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
