### ISSUE TITLE
Workflow service externalization

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#15783]
**Description:**
For workflow-related operations, IS has an embedded BPEL server. BPEL has some drawbacks when it comes to its usage in IS such as runtime overhead, distribution size, and maintenance overhead. The IS should have the capability to fully externalize the workflow engine from the IS, and make any workflow engine pluggable and usable by IS.

**Comment by malithiperera** [comment]
**Generalize the workflow request payload and Call external workflow mediator** 
Generalize the workflow request payload which we send to the external workflow mediator and implement the call mediator service. To do that we implement a separate executor WorkflowMediatorRequestExecutor.java

PR Link:    https://github.com/wso2-extensions/identity-workflow-impl-bps/pull/70/files

**Comment by malithiperera** [comment]
##  carbon-identity-framework

### 01. Implement a method to retrieve External Workflow Id

The getExternalWorkflowId function retrieves the external workflow identifier associated with a given workflow id. This unique identifier corresponds to the deployed workflow id in an external BPS engine.

PR Link : https://github.com/wso2/carbon-identity-framework/pull/4519

### 02.  Provide API Key support to BPS Profile

Introduce new constants and change some database queries for add , retrieve update workflow profiles

PR Link :  https://github.com/wso2/carbon-identity-framework/pull/4555

### 03. Update template file 
Change the template-wf-wizard.jsp file to skip the validation of the newly added external workflow template form

PR Link :  https://github.com/wso2/carbon-identity-framework/pull/4520

**Comment by malithiperera** [comment]
## [identity-api-server](https://github.com/wso2/identity-api-server)

### Implement a new Rest end point for workflow management

PR Link : https://github.com/wso2/identity-api-server/pull/446

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
