### ISSUE TITLE
Email templates created from the Console application are not working

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#15794]
**Describe the issue:**
When a new email template with locale 'English (United States)' is created from the Identity Server Console application's 'Email Templates' section, the registry resource is created with the name 'en-us'. However, when an email template for the same locale is created from the Management Console, it is getting created with the name 'en_us'. Having an underscore (_) is the correct way and due to this reason, email templates created from the Console application cannot be used after creation. 

**How to reproduce:**
1. Create an email template type, and an email template under that type by selecting the locale - 'English (United States)'.
2. Go to the registry from the Management Console, go to path '/_system/config/identity/email', and check the newly created email template. The locale will be 'en-us' instead of 'en_us' which should be the correct one.

In the screenshot below, 'passwordreset_sp' is created from the Management Console, and 'passwordreset_sp1' is created from the Console app. The locales are names differently, and only 'passwordreset_sp' can be used as a custom template.

<img width="373" alt="Screenshot 2023-04-26 at 11 41 16" src="https://user-images.githubusercontent.com/25479743/234551375-2e8c79fb-fae2-4f61-88f8-6997b4acc974.png">

**Expected behavior:**
The payload of the email template creation API from Console should be updated to have the correct locale format. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Tested in 5.11.0 and 6.1.0 latest updated versions

**Comment by ImalshaG** [comment]
Closing the issue since the fix is merged and the doc change is an additional improvement.
