### ISSUE TITLE
[IS 6.0.0] Incorrect configuration in the Identity Server DocumentationConfigure Account Confirmation Methods for Self-Registration page

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#15797]
**Is your suggestion related to a missing or misleading document? Please describe.**

Below configurations are provided the the page[1] to configure default notification channel and to enable notification channel resolving. 

[identity_mgt.user_self_registration]
default_notification_channel = "<value>"
enable_resolve_notification_channel = true

**Describe the improvement**

Above tags are incorrect and should be corrected as below. 

[identity_mgt.**notification**]
default_notification_channel = "<value>"
**resolve_notification_channel**= true

[1] https://is.docs.wso2.com/en/6.0.0/guides/identity-lifecycles/self-register-verification/#!

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
