### ISSUE TITLE
[Doc] Need more information in "Logging in to Salesforce with Integrated Windows Authentication" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1579]
1) When I'm referring for Salesforce SSO with IWA, coudn't find the information on
      why we are using Entity ID
      How we get the value which doc mentioning
I just copy paste the value mentioned in the Doc.  Please add some more information to the Doc regarding this

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
