### ISSUE TITLE
Wrong error message for invalid account confirmation link

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#15795]
**Describe the issue:**
When an expired account confirmation link sent during the self-sign up is clicked, the error is shown as `Invalid password reset link.` This error message should be improved to provide the correct context to the user.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/12439288/234574543-b75aa56b-484c-493b-a56a-9b7f387ce12e.png">

**How to reproduce:**
1. Enable self signup
       <img width="1138" alt="image" src="https://user-images.githubusercontent.com/12439288/234576735-6eb42855-8bcd-403c-a7c5-654b103cc6d4.png">
3. Configure an application to log in with product-is
4. Initiate signup from the application. Then you will receive the account confirmation mail.
5. Click once to confirm the account
6. If you click again on the link, the redirected error page will be as above.

**Expected behavior:**
The error message should contain more context regarding the error.

**Environment information** 
 - Product Version: IS 6.1.0

**Comment by DMHP** [comment]
This common error message has been used for expired password expiry links, expired account confirmation links, and some other flows that use email-based confirmation links. From the BE it has thrown "ERROR_CODE_INVALID_CODE" for those scenarios with the error code 18008, and from the FE the above invalid error message is thrown. If we need to provide more specific error messages based on the scenario we may need to make several changes in the BE, hence throwing this generic error message which is common for all the flows.

**Comment by DMHP** [comment]
https://github.com/wso2/identity-apps/pull/3968

**Comment by DMHP** [comment]
In Asgardeo the error message is as follows.

![Image](https://github.com/wso2/product-is/assets/12690906/dc0e2a07-69fa-4766-a2ff-02e2038b2907)

Based on the source code this error can be thrown when the code is expired or invalid.
