### ISSUE TITLE
Should not be possible to remove or disable an IDP belong to another user

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1580]
**Environment**
2 node IS cluster setup fronted by nginx
JDK -1.8
DB - mysql

**Steps to recreate the Issue**
1. Create 2 users (UserA and UserB) with relevant permissions to manage IDPs
2. Log in using UserA
3. Create an IDP
4. Log in using UserB
5. Disable the IDP created by UserA

**Observations**
UserB can disable/Delete an IDP created by UserA

**Expected Results**
UserB should not be possible to remove the IDP created by userA

**Note** - SP created by UserA is not visible to any other user. Better to implement this logic to the IDP as well

**Comment by kavithasub** [comment]
@sashikamw , Please refer the mail thread [1] to understand SP, IDP with role permissions.
[1] "What is the correct way to display service providers and identity providers for different admin role users"

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
