### ISSUE TITLE
Redirect URI validation fails when defined as a regex to support multiple redirect URIs for an SP

### ISSUE THREAD

**Issue by aka4rKO** [wso2/product-is#15817]
**Describe the issue:**
When the `redirect_uri` parameter is made optional in the authorization request(PAR request flow), and when there is a `redirect_uri` defined for the SP as a regex pattern to accept multiple redirect URIs, the `redirect_uri` validation fails in the Authorization request.

**How to reproduce:**

- Create an SP with multiple redirect URIs.
- Do a PAR request.
- Do an authorization request with only `client_id` and `request_uri` parameters in the request.

**Expected behavior:**
Successfully validates the redirect URI

**Environment information**
 - Product Version: IS 5.11, IS 6.0

**Comment by ImalshaG** [comment]
Closing this since the fixes are gone to the master branch and the needed support branches.
