### ISSUE TITLE
Unclear information for claim mapping when there are multiple user stores

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1581]
The below document says the following.
```
However, for the default user store, you do not need to provide the domain name. As an example, if you have two user stores, one is the default and another one with domain “DEMO” then the pattern would be as follows for “http://wso2.org/claims/emailaddress".

email;DEMO/mail
```

However, from the "Mapped Attributes" drop down itself we can differentiate the user store. (which mapped attribute for which domain) Then, where does the above pattern apply? Please document the details clearly.

https://docs.wso2.com/display/IS540/Managing+User+Attributes#ManagingUserAttributes-Claimmappingwhenusingmultipleuserstores

**Comment by omindu** [comment]
This needs to be removed from the doc as it's no longer valid.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
