### ISSUE TITLE
ORA-01795 error for scim2/Users endpoint

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#15822]
**Describe the issue:**
WSO2 IS 5.7 gives an ORA-01795 error for the scim2/Users call when more than 1000 users are available in the primary user store. There will be no errors in the carbon log since there is no error log added where the exceptions are thrown but the end user will get a 500 error for the scim2/Users call.

Exception occurs at [2].

**How to reproduce:**

- Setup an Oracle database for the WSO2_CARBON_DB db in master-datasrouces.xml file.
- Change the primary user store to a JDBC from user-mgt.xml file.
- Create more than 1000 users (use the performance-is jmx script [1]).
- Call the scim2/Users GET endpoint.
- 500 error will be received without any errors in the log.

**Expected behavior:**
A success response should receive to the end user.

**Environment information:**
 - Product Version: IS 5.7.0
 - Database: Oracle
 - Userstore: JDBC

---

[1] - https://github.com/wso2/performance-is/blob/master/common/jmeter/scim2/SCIM2_Add_User.jmx
[2] - https://github.com/wso2/carbon-kernel/blob/f3e6b07bb339aaaecb69ce9a8e7811a786e9877f/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L2921-L2993

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
