### ISSUE TITLE
Preserve the domain name and description when changing the user store type when adding user stores

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1582]
Type: Improvement
Priority: High
Severity: Minor
Release: 5.4.0

**Steps**
1. Go to user store adding screen
2. Enter the domain name and description
3. Change the user store type (eg: AD to LDAP)

**Issue**
The page will be refreshed and the domain name and description configured will be lost. Then the user has to enter them again. This is a usability issue if the user suddenly remembers to change the user store type and has to re-enter the same details, specially when those details are common across all the user stores.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
