### ISSUE TITLE
Change the SAML response body for client errors by preserving the backward compatibility

### ISSUE THREAD

**Issue by AfraHussaindeen** [wso2/product-is#15821]
### Describe the issue:
The malformed SAML requests need to be  treated as client errors rather than identity provider errors. Therefore, the error response sent to the client should have a status code related to client errors, rather than using the identity provider error status code. This approach is more appropriate, as client errors are usually related to issues with the client request, while identity provider errors indicate issues with the identity provider itself. By using the appropriate status code for the error, clients can better understand the issue and take appropriate actions to address it.

### Related PRs : 
https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/392

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
