### ISSUE TITLE
[Doc] Incorrect configuration file for configuring My Account Application

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#15824]
The documentation page [1] needs to be updated in all related WSO2 Identity Server versions, including the latest ones, to reflect the _deployment.toml_ configurations that need to be added instead of the configurations in the _deployment.config.json_ file as any changes made to this file are overwritten at every server restart. An example _deployment.toml_ configuration is shown below.

```
[myaccount]
personal_info.enabled = false
overview.disabled_features = ["overview.accountActivity","overview.consents"]
security.disabled_features = ["security.accountRecovery","security.mfa", "security.activeSessions", "security.manageConsents"]
```

[1] - https://is.docs.wso2.com/en/5.11.0/develop/configure-my-account/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
