### ISSUE TITLE
[Improvement] get user list belonging to a specific role

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1583]
In [1] it states that for getUserListOfRole() all the user list if retrieved with a flag selected as true if the user is belonging to the specific role and selected as false if the user doesn't belong to that role.

But here the main objective of using this operation is to fetch the user list belonging to a specific role and the a developer should be able to retrieve those values with the minimum effort. Having a flag to process is extra line of code for the developer using this operation and ideally the operation itself should handle this filter.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
