### ISSUE TITLE
Adaptive script: HTTP POST request with 2D array in payload cannot be successfully done

### ISSUE THREAD

**Issue by pasandevin** [wso2/product-is#15834]
**Describe the issue:**
In adaptive authentication, a 2D array in payload is converted to an object format when doing a HTTP POST request with the `httpPost()` method. This throws `400` bad request from clients as the request payload is not recognized.

**How to reproduce:**
1. include a 2D array in a HTTP POST request payload in an adaptive authentication script.
ex - 
```
"context": {
    "ip": "211.96.77.55",
    "headers": [
        [
            "User-Agent",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
        ],
        [
            "Accept-Encoding",
            "gzip, deflate, br"
        ],
        [
            "Accept-Language",
            "en-us"
        ],
        [
            "Accept",
            "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8"
        ],
        [
            "Connection",
            "close"
        ],
        [
            "Host",
            "castle.io"
        ]
    ]
}
```

2. It will be converted to the following when the actual request is done.
```
"context":{
      "ip":"211.96.77.55",
      "headers":{
         "0":{
            "0":"User-Agent",
            "1":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/14.1.1 Safari\/605.1.15"
         },
         "1":{
            "0":"Accept-Encoding",
            "1":"gzip, deflate, br"
         },
         "2":{
            "0":"Accept-Language",
            "1":"en-us"
         },
         "3":{
            "0":"Accept",
            "1":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,\/;q=0.8"
         },
         "4":{
            "0":"Connection",
            "1":"close"
         },
         "5":{
            "0":"Host",
            "1":"castle.io"
         }
      }
   }
```

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
