### ISSUE TITLE
Provide information of whether multiple roles can be specified in getUserListOfRole()

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1584]
In [1] it doesn't indicate whether multiple roles can be specified. Please indicate that information as the request is having the structure as following where it gives multiple value set accepting impression
```
  <ser:getUserListOfRole>
         <!--Optional:-->
         <ser:roleName>Engineer</ser:roleName>
      </ser:getUserListOfRole>
```
[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-getUserListOfRole()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
