### ISSUE TITLE
Add Idp group configuration to identity provider

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#15845]
**Describe the issue:**

- federated groups provided by an IdP need to be stored in Identity Server
- IdP management API needs to be extended to manage IdP groups

**Comment by shanggeeth** [comment]
Related PRs
- https://github.com/wso2/carbon-identity-framework/pull/4497
- https://github.com/wso2/identity-api-server/pull/436

**Comment by ImalshaG** [comment]
Closing the issue since the feature is completed.
