### ISSUE TITLE
Add application role mapping configuration to identity server

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#15843]
**Describe the issue:**

- application role mapping configuration which specifies an SP-IDP combination will use application role mapping to federated groups of the IDP need to be stored in the Identity Server.

- Currently there is no way to store a property unique to a service provider and identity provider.
`SP_IDP_ATTR` table will be introduced to store this kind of configs.

**Comment by shanggeeth** [comment]
Related PRs:
https://github.com/wso2/carbon-identity-framework/pull/4473
https://github.com/wso2/identity-api-server/pull/432

**Comment by ImalshaG** [comment]
Closing the issue since the feature is completed.
