### ISSUE TITLE
[Query] What is the business use of getUserClaimValuesForClaims()

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1585]
In order to test the solution 26 mentioned in [1] I need to know the business use of getUserClaimValuesForClaims() operation. Can you please explain with a real world sample?

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
