### ISSUE TITLE
Error when editing an IDP through the Mgt Console

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15854]
**Describe the issue:**
An error can be seen when trying to edit a IDP created through the mgt console. The following error can be seen without a stacktrace when updating an existing IDP for the second time.
<img width="513" alt="image" src="https://github.com/wso2/product-is/assets/47671237/5c62467b-6428-4404-9ab2-9ac6f8bfe9a7">

**How to reproduce:**
1. Create an identity provider through the mgt console.
2. Edit it and click on update.
3. Edit it again and click on update for the second time.

The above error will be prompted.

**Expected behavior:**
We should be able to edit an existing IDP through the mgt console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.2.0-m1
 - OS: Mac

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by amanda-ariyaratne** [comment]
This error occurs due to a null pointer exception. 
Fixed with https://github.com/wso2/carbon-identity-framework/pull/4626
