### ISSUE TITLE
High number of SELECT queries on UM_USER_ATTRIBUTE table during token request

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#15850]
**Is your suggestion related to an experience ? Please describe.**

It was noticed that high number of SELECT queries (about ten) were executed during a one token generation when features like account lock, account disable and suspend idle account are enabled.

Two of these SELECT queries are intended for retrieving the user attributes for jwt token and id token generation. But rest of the SELECT queries are for retrieving the user claim values for the handlers like [AccountLockHandler[1]](https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/master/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java) and [AccountDisableHandler[2]](https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/master/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java).

**Describe the improvement**

During the analysis, we noticed that if we could optimise the code to reduce the number fo calls to the userStoreManager.getUserClaimValues() method for each time a claim value is required, we could greatly reduce the number of SELECT queries to the database.

**Comment by mpmadhavig** [comment]
The no of redundant DB calls used in [AccountDisableHandler.java](https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/master/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountDisableHandler.java) class not that significant to be refactored. 

Therefore continueing with only the [AccountLockHandler.java](https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/master/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java) changes.
