### ISSUE TITLE
Table lengths are not equal in h2 and mysql scripts

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#1586]
Table name | Column name | H2 data type / length | MySQL data type / length
------------ | ------------- | ------------ | -------------
IDN_OAUTH1A_REQUEST_TOKEN | REQUEST_TOKEN | VARCHAR (512) | VARCHAR (255)
IDN_OAUTH1A_ACCESS_TOKEN | ACCESS_TOKEN | VARCHAR (512) | VARCHAR (255)
IDN_STS_STORE | TOKEN_CONTENT | BLOB | BLOB (1024)
FIDO_DEVICE_STORE | DEVICE_DATA | LONGVARCHAR | VARCHAR (2048)
REG_LOG | REG_PATH | VARCHAR (2000) | VARCHAR (750)
REG_PATH | REG_PATH_VALUE | VARCHAR (2000) | VARCHAR(750)

And also below differences are there. 
- WF_BPS_PROFILE table has CALLBACK_USERNAME and CALLBACK_PASSWORD columns in MySQL but not in H2.
- UNIQUE (UM_PERMISSION_ID, UM_ROLE_NAME, UM_TENANT_ID, UM_DOMAIN_ID) for UM_ROLE_PERMISSION table is in MySQL script but not in H2.
- UNIQUE (UM_PERMISSION_ID, UM_USER_NAME, UM_TENANT_ID) for UM_USER_PERMISSION is in H2 but not in MySQL.

And please compare all the scripts and confirm they are identical.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
