### ISSUE TITLE
Blank Login Page received for Authorization Requests with the `ui_locales` parameter

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15862]
**Describe the issue:**
The OIDC conformance test suite has identified a OIDC specification violation in the IS 6.2.0 milestone releases related to test cases where ui_locales parameter is tested in the authorization request.

For the following authorization request after setting the ui_locales parameter, the following error is logged and a blank login page is recieved.
```
https://localhost:9443/oauth2/authorize?client_id=9QjH6MTbPnklsuXxsyxghANZFF0a&redirect_uri=https://localhost.emobix.co.uk:8443/test/a/test/callback&scope=openid&state=DnAi75FT8y&nonce=akPqoA7BNd&response_type=code&ui_locales=se
```
```
[2023-05-12 06:51:52,234] [cde57b61-8464-4b1a-bf97-887ff3256c3c] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/authenticationendpoint].[default]} - Servlet.service() for servlet [default] in context with path [/authenticationendpoint] threw exception [An exception occurred processing [includes/localize.jsp] at line [59]

56:     } else if (uiLocaleFromURL != null) {
57:         for (String localeStr : uiLocaleFromURL.split(" ")) {
58:             String langStr = localeStr.split("_")[0];
59:             String langLocale = localeStr.split("_")[1];
60:
61:             Locale tempLocale = new Locale(langStr, langLocale);
62:


Stacktrace:] with root cause java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.apache.jsp.login_jsp._jspService(login_jsp.java:424)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
```
According to the [OIDC specification](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1), our IS should support receiving ui_locales as a space-separated list of language tag values as defined in the [BCP 47 specification](https://www.rfc-editor.org/rfc/pdfrfc/rfc5646.txt.pdf). 
Example ui_locales value provided in the specification: `fr-CA fr en`

But our current implementation only supports a space seperated list of language tags of the format `tag_subtag`. 
Example: `fr_CA`

According to the specification, tags and subtags are separated by a hiphen and are in the format `tag-subtag`. Additionally we should also support ui_locales with only a tag. 
Example: should provide support for input such as `fr-CA fr en`

**How to reproduce:**
1. Create a service provider.
2. Add inbound authentication configurations with some dummy callback url.
3. Note the client id of the added auth configs.
4. Open a terminal and try the following request.

```
https://localhost:9443/oauth2/authorize?client_id=<client-id>&redirect_uri=<redirect-url>&scope=openid&state=DnAi75FT8y&nonce=akPqoA7BNd&response_type=code&ui_locales=fr-CA fr en
```
A blank login page will be received with the above error in the terminal.

**Expected behavior:**
ui_locales of the format as specified in the OIDC specification (`fr-CA fr en`) should be supported by the IS.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.2.0-m1, IS 6.2.0-m2
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kavinda1995** [comment]
This is fixed with https://github.com/wso2/identity-apps/pull/3917
