### ISSUE TITLE
[Query] How do a developer retrieve the role list of a secondary user store and of a tenant

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1587]
In [1] the getRoleNames() is retrieving all the role names in the system. 
**Questions**
1. How does a developer retrieve all the roles names in the secondary user store - if it's a different request, please do provide a sample
2. How does a developer retrieve all the roles names in the tenant primary and secondary user stores? - if it's a different request please do provide a sample

**Comment by erandidesilva** [comment]
The same information is needed for getAllProfiles operation

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
