### ISSUE TITLE
Doc Feedback: invokeOPA() function of adaptive authentication is not found 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#15877]
Hi,
Location : https://is.docs.wso2.com/en/5.11.0//learn/using-opa-policies-for-adaptive-auth/

invokeOPA() adaptive function is not supported out of the box in the Identity server. It seems we need to install the [connector](https://store.wso2.com/store/assets/isconnector/details/767617c4-1303-441b-83da-f21fb09a278a) from the store.

The above information is not mentioned in the documentation. can you please verify and add the above information in the doc space? Please consider the latest releases also.

Extension repository link: https://github.com/wso2-extensions/identity-application-authz-opa

thanks,
Thumi

**Comment by VivekVinushanth** [comment]
I have tried OPA and I too doubt we have OOTB support. We had to use HttpPost instead to communicate to OPA.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
