### ISSUE TITLE
UI issue in the SOAP message tracer

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1588]
Type: Bug
Priority: High
Severity: Major
Release: 5.4.0
Browser: Firefox Quantum 57.0.1 (64-bit)

**Steps**
1. Go to Monitor -> Soap tracer in the management console

**Issue**
Overlap messages as seen in the attached screen shot
![6](https://user-images.githubusercontent.com/1845370/34028343-645596b6-e188-11e7-9054-2e41a985b36d.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
