### ISSUE TITLE
Audit logs for resident identity events

### ISSUE THREAD

**Issue by MatiRamone7** [wso2/product-is#15882]
Taking into considerations improovements from issue #5037,

The audit logs don't cover the Resident identity Provider events, and to have them into a customization would involve to customize various listeners which is not optimal for the product.

To have the event logs in the audit logs would improve the tracing in this part of the product

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
