### ISSUE TITLE
Identifying and Documenting Unique Client Metadata Parameters in the WSO2 DCR Implementation

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#15887]
**Description:**

for the DCR endpoint, apart from the client metadata defined in the spec (RFC 7591), only the ones listed http://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#client-metadata should be added according to https://datatracker.ietf.org/doc/html/rfc7591#section-4.1. 
But in our implementation, we have added custom client metadata parameters that are not defined in either of these places. 

A summary of the parameters that are shared with the RFC and the metadata registry and the and the ones that are unique to us.

| Shared with RFC | Shared with Metadata Registry | Unique to WSO2-IS DCR |
| --- | --- | --- |
| redirect_uris | redirect_uris | url |
| client_name | client_name | ext_param_client_id |
| client_id | client_id | ext_param_client_secret |
| client_secret | client_secret | ext_param_sp_template |
| grant_types | grant_types | - |
| jwks_uri | jwks_uri | - |
| contacts | contacts | - |
| response_types | response_types | - |
| - | application_type | - |
| - | post_logout_redirect_uris | - |
| - | request_uris | - |
| - | backchannel_logout_uri | - |
| - | backchannel_logout_session_required | - |

Based on the above comparison, there are 4 unique parameters found in WSO2-IS DCR implementation that are not present in either the RFC or the Metadata Registry:

    url
    ext_param_client_id
    ext_param_client_secret
    ext_param_sp_template

It's also worth noting that the WSO2-IS DCR implementation does not include several parameters from both the RFC and the Metadata Registry, including but not limited to:

    token_endpoint_auth_method
    client_uri
    logo_uri
    scope
    tos_uri
    policy_uri
    software_id
    software_version
    client_id_issued_at
    client_secret_expires_at

As for the parameters present in the Metadata Registry but not in WSO2-IS DCR, there are several of them, such as:

    registration_access_token
    registration_client_uri
    sector_identifier_uri
    subject_type
    id_token_signed_response_alg
    id_token_encrypted_response_alg
    id_token_encrypted_response_enc
    userinfo_signed_response_alg
    userinfo_encrypted_response_alg
    userinfo_encrypted_response_enc
    request_object_signing_alg
    request_object_encryption_alg
    request_object_encryption_enc
    token_endpoint_auth_signing_alg
    default_max_age
    require_auth_time
    default_acr_values
    initiate_login_uri
    claims_redirect_uris
    nfv_token_signed_response_alg
    nfv_token_encrypted_response_alg
    nfv_token_encrypted_response_enc
    tls_client_certificate_bound_access_tokens
    tls_client_auth_subject_dn
    tls_client_auth_san_dns
    tls_client_auth_san_uri
    tls_client_auth_san_ip
    tls_client_auth_san_email
    require_signed_request_object
    require_pushed_authorization_requests
    introspection_signed_response_alg
    introspection_encrypted_response_alg
    introspection_encrypted_response_enc
    frontchannel_logout_uri
    frontchannel_logout_session_required
    authorization_details_types
    dpop_bound_access_tokens

However, in the OIDC DCR implementation that is now deprecated, we have used parameters from the metadata registry which are now not supported in our default implementation.

The following is a comparison of the WSO2-IS OAUTH DCR parameters, WSO2-IS OIDC DCR parameters, RFC parameters, and Metadata Registry parameters.

| Parameter | RFC | Metadata Registry | WSO2-IS OAUTH DCR | WSO2-IS OIDC DCR |
| --- | --- | --- | --- | --- |
| sector_identifier_uri | - | Yes | - | Yes |
| subject_type | - | Yes | - | Yes |
| id_token_signed_response_alg | - | Yes | - | Yes |
| id_token_encrypted_response_alg | - | Yes | - | Yes |
| id_token_encrypted_response_enc | - | Yes | - | Yes |
| userinfo_signed_response_alg | - | Yes | - | Yes |
| userinfo_encrypted_response_alg | - | Yes | - | Yes |
| userinfo_encrypted_response_enc | - | Yes | - | Yes |
| request_object_signing_alg | - | Yes | - | Yes |
| request_object_encryption_alg | - | Yes | - | Yes |
| request_object_encryption_enc | - | Yes | - | Yes |
| token_endpoint_auth_signing_alg | - | Yes | - | Yes |
| default_max_age | - | Yes | - | Yes |
| require_auth_time | - | Yes | - | Yes |
| default_acr_values | - | Yes | - | Yes |
| initiate_login_uri | - | Yes | - | Yes |
| request_uris | - | Yes | Yes | Yes |
| redirect_uris | Yes | Yes | Yes | - |
| client_name | Yes | Yes | Yes | - |
| client_id | Yes | Yes | Yes | - |
| client_secret | Yes | Yes | Yes | - |
| grant_types | Yes | Yes | Yes | - |
| application_type | - | Yes | Yes | - |
| jwks_uri | Yes | Yes | Yes | - |
| url | - | - | Yes | - |
| ext_param_client_id | - | - | Yes | - |
| ext_param_client_secret | - | - | Yes | - |
| contacts | Yes | Yes | Yes | - |
| post_logout_redirect_uris | - | Yes | Yes | - |
| response_types | Yes | Yes | Yes | - |
| ext_param_sp_template | - | - | Yes | - |
| backchannel_logout_uri | - | Yes | Yes | - |
| backchannel_logout_session_required | - | Yes | Yes | - |

From the table, we can see that the parameters used in WSO2-IS DCR and WSO2-IS OIDC DCR implementations are quite different. Only the 'request_uris' parameter is shared between the two WSO2 implementations, while the rest of the parameters are exclusive to each.

related: https://github.com/wso2/product-is/issues/14959

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
