### ISSUE TITLE
Add more steps to `Customize Login Pages Layout` Docs

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#15899]
**Is your suggestion related to a missing or misleading document? Please describe.**
Currently, following the steps in https://is.docs.wso2.com/en/latest/references/extend/rebranding/customizable-login-portal/ doc does not add the custom layout. We need to add the following steps to the Custom Login Pages Layout docs to make it work.

```
- Then copy the <IS_HOME>/repository/deployment/server/webapps/authenticationendpoint/extensions/layouts/custom directory and place it into the <IDENTITY-APPS-HOME>/components/login-portal-layouts/layouts directory.
- Then go to the <IDENTITY-APPS-HOME>/components/login-portal-layouts directory and run the “mvn clean install” command (Build should be succeeded for further steps).
- Then go to the <IDENTITY-APPS-HOME>/apps/authentication-portal/src/main/webapp/extensions/layouts directory and copy the “custom” folder (Compiled version of the layout source code) and paste it into the <IS_HOME>/repository/deployment/server/webapps/authenticationendpoint/extensions/layouts directory.

```

<img width="1435" alt="Screenshot 2023-05-22 at 07 51 57" src="https://github.com/wso2/product-is/assets/27746285/832e977d-e7f9-4aa8-8f34-ee4548207789">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
