### ISSUE TITLE
Support filtering trusted JWT Issuers in IdP API implementation

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#15897]
**Is your suggestion related to an experience ? Please describe.**
Support filtering trusted JWT issuers in the existing IdP API. 

**Describe the improvement**
Keep a IdP metadata to filter the trusted JWT issuers from the rest of the IdPs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
