### ISSUE TITLE
[DOC] Change the screen shot to make sense for the scenario "Associate federation user accounts"

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1589]
Please update for $subject at the documentation page [1], Step6 with selection for "Federated". See attached.

[1] [https://docs.wso2.com/display/IS540/Associating+User+Accounts]

![screen2](https://user-images.githubusercontent.com/15671620/34028461-4786d800-e189-11e7-87fc-8fe94f2cedd6.jpeg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
