### ISSUE TITLE
Required and other default form validations does not occur unless the form field was touched.

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#15900]
### Describe the issue:
The default validations on the input fields are only triggered if the form field is touched due to the conditional check in [1].

[1] https://github.com/wso2/identity-apps/blob/068b39e5b390d4e164bb445395b4c384c283feaa/modules/form/src/utils/validate.ts#L103

### How to reproduce:

1. Implement a form with a <Field.Input/> component of any type and set the required prop to `true`.
2. Submit the form without touching the input field.

### Expected behavior:
The form validations should be triggered even if the form was not touched.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
