### ISSUE TITLE
WSO2 max policy file size issue

### ISSUE THREAD

**Issue by devrimbaris** [wso2/product-is#15908]
**Describe the issue:**
The WSO2 PAP section does not allow to upload a policy file more than 1MB.

Secondly even if you upload it via XML editor and save it , you can not reopen it since the XMLPrettifier buffer is maxed up at 1MB.

**How to reproduce:**

Generate a policy file > 1MB and try to upload it.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
WSO2 6.1

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
