### ISSUE TITLE
Mismatch in "Configure Email Address as the Username" contents

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#15905]
**Is your suggestion related to a missing or misleading document? Please describe.**
The content of `Configure Email Address as the Username` in the [main page](https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/#configure-email-address-as-the-username) has updated content, but the same sections in [Salesforce with IWA](https://is.docs.wso2.com/en/latest/guides/login/log-into-salesforce-using-iwa/#configuring-email-address-as-the-user-name) and [Salesforce with Facebook](https://is.docs.wso2.com/en/latest/guides/login/log-into-salesforce-using-fb/) are not updated with latest content. 

**Describe the improvement**

The `Configure Email Address as the Username` sections of `Salesforce with IWA` and `Salesforce with Facebook` sections should be updated with the same content as in the main page.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
