### ISSUE TITLE
[DOCS]Explain why STS should be configured under the Resident Identity Provider

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1590]
Document: [Configuring WS-Trust Security Token Service](https://docs.wso2.com/display/IS540/Configuring+WS-Trust+Security+Token+Service)

Explain why STS should be configured under the Resident Identity Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
