### ISSUE TITLE
[Doc] Wrong file name specified for the log4j.properties file

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1591]
Type: Bug
Priority: High
Severity: Major
Release: 5.4.0

In the below doc, it says the log file can be found in the log4j.configuration.
https://docs.wso2.com/display/IS540/System+Logs#

`The location of the log files on the disk is specified in the log4j.configuration file`

**Issues**
1. The file name is incorrect. It should be log4j.properties file
2. Should mention the location/file path of the file for the user to locate the file

**Comment by ShirazAzad** [comment]
Updated the docs [1], [2], [3], and [4] by correcting the file name and the path. Also corrected some typos and formatting.
[1] https://docs.wso2.com/display/IS550/System+Logs
[2] https://docs.wso2.com/display/IS541/System+Logs
[3] https://docs.wso2.com/display/IS540/System+Logs
[4] https://docs.wso2.com/display/IS530/System+Logs
