### ISSUE TITLE
Add a new event listener to reinitiate organization login

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#15922]
**Describe the Issue:**
- The logic to prompt login for sub-organizations from organization login should be moved out of authentication framework (https://github.com/wso2/carbon-identity-framework/pull/4666)
- A new event listener should be added in authentication framework which can be implemented in the authenticator.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
