### ISSUE TITLE
Irrelevant information in the sign up help page

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1592]
**Environment**
IS standalone pack
JDK -1.8
DB - postgres sql 9.6

**Steps to recreate the Issue**
1. Start IS server
2. Go to login page and click "Sign-In" option

**Observations**
sign in user guide contains outdated information
![screenshot from 2017-12-15 11-14-32](https://user-images.githubusercontent.com/14962228/34028543-d64016a6-e189-11e7-9f39-158462b468f9.png)

**Expected Results**
The above highlighted outdated content and irrelevant content should be corrected

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
