### ISSUE TITLE
[DOC] There should be a note or tip saying about the config changes required to access enduser dashboard if hostname/port-offset changed

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1593]
In current doc page [1] , I couldn't see any note or tip for required config changes where if I have changed port offset or host name for IS sever and cannot access the end user dashboard. Please be update the page content in [1]

label: IS-5.4.0

[1] [https://docs.wso2.com/display/IS540/Using+the+End+User+Dashboard]

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
