### ISSUE TITLE
Incorrect information on IDP role mapping doc

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#15949]
**Is your suggestion related to a missing or misleading document? Please describe.**

Upward IS 6.0.0, adding groups in the role mapping section in Identity Providers is not supported[1][2]. But in the documentation for the IDP role mapping[3], it provides the steps for a role mapping using a group as an example.  

**Describe the improvement**

This should be corrected to use an example role instead of a group. Furthermore, it is better if we can include in the documentation that IS do not support adding group mapping from IS 6.0.0.  

---

[1] https://github.com/wso2/product-is/issues/12020#issuecomment-872939802
[2] https://github.com/wso2/product-is/issues/11330
[3] https://is.docs.wso2.com/en/6.0.0/guides/identity-federation/roles-idp/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
