### ISSUE TITLE
The Personal Info section is not completely disabled when configuring MyAccount

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#15946]
The Personal Info section is not completely disabled when the following _deployment.toml_ configuration has been added in WSO2 Identity Server v5.11.0.

```
[myaccount]
personal_info.enabled = false
```

The users are still able to access the Personal Info section via the dropdown from the user profile. This needs to be fixed.

**Comment by Shaaali** [comment]
PR to fix this : https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/394
