### ISSUE TITLE
Add Documentation for JARM for OAuth2 in 6.2 Release

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#15943]
**Describe the issue:**
As part of the 6.2 release, we need to include the documentation for JSON Web Token Response for OAuth2 (JARM) in the product documentation. This feature has been added to version 5.10.0 (https://is.docs.wso2.com/en/5.10.0/learn/jarm-for-oauth2/). Need to update the content and port the documentation to the 6.2 docs.

**Comment by nilminiwso2** [comment]
Related issue: https://github.com/wso2/product-is/issues/15527
