### ISSUE TITLE
[DOCS]The link redirects to an error page. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1594]
Document: [Running an STS Client](https://docs.wso2.com/display/IS540/Running+an+STS+Client)
Section: Running the STS client
Step 1

Downloading a sample link redirects to an error page.

**Comment by deshankoswatte** [comment]
Hi @isuruuy429,

This is fixed in [1] as shown in the screen cast below.

![Peek 2020-02-06 17-09](https://user-images.githubusercontent.com/33062368/73933906-754e0b80-4903-11ea-994a-c2eb93dec5eb.gif)

[1] - https://docs.wso2.com/display/IS540/Running+an+STS+Client
