### ISSUE TITLE
[DOCS][Login to Identity Server using another Identity Server - OAuth2 ]Screenshot is outdated

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1595]
Document: [Login to Identity Server using another Identity Server - OAuth2](https://docs.wso2.com/display/IS540/Login+to+Identity+Server+using+another+Identity+Server+-+OAuth2)
Step 2

The screenshot is outdated.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
