### ISSUE TITLE
Add ReCaptcha Validation to Identifier First Authentication

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#15952]
**Is your feature request related to a problem? Please describe.**

We currently don't have reCaptcha validation for idf. 

**Describe the solution you would prefer**

Add reCaptcha validation to idf authentication.  

**Additional context**

Need to find a generic solution, so that in future also, the solution to this problem could be easily utilized to add reCaptcha validation to other local authenticators that currently do not support reCaptcha validation.

**Comment by Shaaali** [comment]
The PRs :

[1] : https://github.com/wso2-extensions/identity-governance/pull/709/
[2] : https://github.com/wso2/carbon-identity-framework/pull/4664/
[3] : https://github.com/wso2/identity-apps/pull/3924/

Context :


The generic authenticator captcha connector class[1] added to the identity-governance is capable of doing basic captcha validation to any local authenticator. 
A new method is introduced in [2] to get a the properties of a local authenticator. 
Therefore, in the future, when adding captcha validation to another local authenticator, there won't be any changes required from the governance level or in authenticator level. 
Instead, a FE improvement should be done similar to [3] and add FE captcha validation. 

How to enable reCaptcha validation for IDF :

Add the following configuration to the deployment.toml

[authentication.authenticator.user_identifier.parameters]
enable_captcha_validation=true

A similar pattern should be followed when enabling captcha validation to any other local authenticator, once the FE support is added.

**Comment by Shaaali** [comment]
Doc Issue : https://github.com/wso2/product-is/issues/16015

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
