### ISSUE TITLE
[Migration] - Skip sending the query params in the default consent page

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#15956]
**Describe the issue:**

- with the changes from this PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2020, The query params are not sending in the default consent page url and the default behavior is changed.
- If some one have already done customizations with the values from the query params, this changes can be affect.
- So, the sake of that we introduced a new configuration as below to keep the backward compatibility. 
     -  https://github.com/wso2/carbon-identity-framework/pull/4622
     -  https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2075
- So, to keep the backward compatibility, we must need to add the below configuration to the deployment.toml file.
```

[authentication.endpoint.consent_page_redirect_params]
allow = true
```

**Comment by ImalshaG** [comment]
@sandushi Can you elaborate a bit more on what query params were sent earlier?

**Comment by dewniMW** [comment]
@sandushi better to state how this new behavior would be overridden if the user already has a config defined in deployment.toml to add a filter policy to exclude certain query params. 
Related issue: https://github.com/wso2/product-is/issues/16394

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
