### ISSUE TITLE
Redundant information in IS dashboard configurations for cluster deployment

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1596]
Incorrect configuration instructions into setup the IS dashboard

Doc [1], step 4, instruct to define the datasources to set up the dashboard. Whereas AFAIK there is no dependency on the dashboard to the data source. We have already documented the relevant data source configurations in the previous set, hence this is redundant information.

![screenshot from 2017-12-15 12-13-58](https://user-images.githubusercontent.com/14962228/34030164-d28343be-e191-11e7-9a2b-19612179e51f.png)

[1] https://docs.wso2.com/display/IS540/Clustered+Deployment

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
