### ISSUE TITLE
Remove `Mount the shared registry` section in the deployment guide

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15962]
`Mount the shared registry` section in the deployment guide [1] does not add any value since registry mounting is done automatically in the new config model.

Therefore, I would suggest to remove that section from the doc [1].

[1] https://is.docs.wso2.com/en/latest/deploy/deployment-guide/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
