### ISSUE TITLE
Management Console SSO breaks after update

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#15971]
**Describe the issue:**

After retrieving an update via the WSO2 Updates 2.0 tool from v5.10.0 update level 221 to 229, the carbon management console SSO flow breaks and continues on a redirection loop to the /carbon/admin/login.jsp endpoint. This needs to be fixed.

**How to reproduce:**

- Enable SSO for the management console [1]
- Update to update level 229
- Try accessing the carbon management console

[1] - https://is.docs.wso2.com/en/5.10.0/learn/multi-factor-authentication-for-wso2-is-management-console/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
