### ISSUE TITLE
[DOCS]Userinfo Endpoint URL is not included in the provided screenshot

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1597]
Document: [Login to Identity Server using another Identity Server - OAuth2](https://docs.wso2.com/display/IS540/Login+to+Identity+Server+using+another+Identity+Server+-+OAuth2)
Step 3

Userinfo Endpoint URL is not mentioned in this step or in the screenshot provided. 
It should be as below. 
![aa](https://user-images.githubusercontent.com/31693103/34030436-fced5a30-e192-11e7-8c88-5b40c75e1ef4.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
