### ISSUE TITLE
State parameter included twice in the Form Post Response Body

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#15973]
**Describe the issue:**
The response body received for a form post response mode authorization request contains the state parameter twice. 
<img width="722" alt="image" src="https://github.com/wso2/product-is/assets/47671237/114eb890-13d1-401d-ab9b-f34da0d457bd">

This issue was identified by the OIDC conformance test suite run against the IS-6.2.0-m5 pack.

This happens when building the response body for form post mode using the method [[1](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/responsemode/provider/impl/FormPostResponseModeProvider.java#L70)] where the `jsonPayLoad` already contains the state parameter and at [[2](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/responsemode/provider/impl/FormPostResponseModeProvider.java#L95)] the state parameter is added to the response again.

**How to reproduce:**
1. Send an authorization request in form post response mode.
```
Ex: https://localhost:9443/oauth2/authorize?client_id=5Q4qIUjhqFsk1YeRynFy4lk9SgYa&redirect_uri=https://oidcdebugger.com/debug&scope=openid%20offline_access&state=4WMtLOuy23&nonce=MtSTAuYusI&response_type=code&response_mode=form_post&prompt=consent
```
2. Check the parameters received in the response body.

**Expected behavior:**
The state parameter should be included only once.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-6.2.0-m5

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/responsemode/provider/impl/FormPostResponseModeProvider.java#L70
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/responsemode/provider/impl/FormPostResponseModeProvider.java#L95

**Comment by chamathns** [comment]
seems like this has been introduced with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2037
@anjuchamantha could you please send a fix?

**Comment by anjuchamantha** [comment]
sure, will check

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
