### ISSUE TITLE
Doc Feedback: Wso2IS 6.1.0 don't have source: <IS-HOME>/dbscripts/identity/uma/postgresql.sql

### ISSUE THREAD

**Issue by vqmanh** [wso2/product-is#15983]
Location : https://is.docs.wso2.com/en/latest/deploy/change-to-postgresql/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
