### ISSUE TITLE
Outdated sample HTTP Output Adapter xml configurations for Vonage SMS API request

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#15981]
Under the event publisher configuration to call a REST Service to send confirmation codes in our official documentation, we have provided a sample HTTP Output Event Adapter xml  file for Vonage sms API. However, The current Vonage SMS API request body format is differ from our official doc guide [1]. `=` must be replaced with the `:`  as follows.
```
      <inline>{"api_key":"4c9374",
            "api_secret":"FtqyPE93",
            "from":"NEXMO",
            "to":{{mobile}},
            "text":{{body}}
            }</inline>
```

Similar to: https://github.com/wso2/product-is/issues/15792

[1] https://is.docs.wso2.com/en/5.11.0/learn/password-recovery-via-user-preferred-notification-channel/#configuring-password-recovery

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
