### ISSUE TITLE
Creating a new role with a workflow defined for Add Role operation doesn't apply workflow in console

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#15994]
**Describe the issue:**
Even if a workflow is defined for adding a role, when a new role is created using the console app, the workflow is not applied. A new role is directly created without awaiting approval.

**How to reproduce:**
1. Get the latest IS pack
2. Create a workflow for role add operation in the system
3. Create a new role using the console
4. Navigate to the roles list page. The fully created role will be displayed. (can verify using management console that it is not pending approval)

![image](https://github.com/wso2/product-is/assets/46979289/7843271e-4f23-4cef-983b-375de5ed2f20)

Role `supervisor` was created using console app and role `supervisor2` was created using management console.
![image](https://github.com/wso2/product-is/assets/46979289/bd29434d-b6d3-4642-80dc-24f3d1d3fad0)

**Expected behavior:**
The role should not be created until approved as defined in the workflow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
