### ISSUE TITLE
Cannot change the password of the admin user from the user-mgt.xml file after server starts

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1599]
Type: Bug
Priority: Highest
Severity: Critical
Release: 5.4.0

**Steps**
1. Take a fresh IS pack and start the server
2. Go to user-mgt.xml file and change ONLY the password of the admin user
eg:
```
<AdminUser>
                <UserName>admin</UserName>
                <Password>Admin@123</Password>
</AdminUser>
```
3. Restart the server with -Dsetup
4. Login to the management console from the admin user

**Issue**
Login fails. According to the below document, we can change only the password of the admin user and start with -Dsetup to make the effect take place.

https://docs.wso2.com/display/IS540/Using+Email+Address+as+the+Username

```
If you changed the password of the admin user to something other than 'admin', start the WSO2 IS server using the -Dsetup parameter as seen in the command below.
sh wso2server.sh -Dsetup
```

**Note**: If both username and password are changed, a new user will be created and was able to login

**Comment by sagara-gunathunga** [comment]
-Dsetup is not production ready feature so we will get rid of this feature, please refer "[Dev] How to create database tables with -Dsetup in Carbon 5?" thread. Please reopen the issue if this error occur when connecting to manually created database without using -Dsetup option.
