### ISSUE TITLE
[Lazy loading] Tenant is not loading when creating a user store using /api/server/v1/userstores API

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#16005]
With the Identity server lazy loading, the tenants will be unloaded after configured tenant idle time. 

After the idle time, if we create a user store using [1], the user store will be created successfully. But when trying to retrieve the userstores using [2] recently created user-store will not be listed in the response.

It was identified that this is caused due to the tenant not loading when creating/getting the userstores using the API. 

**How to reproduce :** 

Create a tenant and wait until the tenant's idle time is passed(default 30 min)
After that, create a userstore using [1]
Then try to retrieve the userstores using [2].
Observe the newly created userstore is not present in the response.

**Expected behavior:**

Tenant should be loaded when creating the userstore using [1] and when retrieving the userstores using [2] all the userstores should be present.

IS version: 5.10.0

[1]https://is.docs.wso2.com/en/5.10.0/develop/userstore-rest-api/#/User%20Store/addUserStore
[2]https://is.docs.wso2.com/en/5.10.0/develop/userstore-rest-api/#/User%20Store/getSecondaryUserStores

**Comment by sachiniWettasinghe** [comment]
Closing since this is already fixed with https://github.com/wso2/carbon-identity-framework/pull/3181 from IS 5.11.0 onwards.
