### ISSUE TITLE
[Doc] No document found for IS 5.4.0 version related to Login to salesforce using idenity server

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1600]
Refer to link [1]. There is no document found for IS 5.4.0 latest version related to Login to Salesforce using identity server

[1]. https://docs.wso2.com/display/IS540/How+To%3A+Login+to+Salesforce+using+the+Identity+Server

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
