### ISSUE TITLE
Improvements to PAR implementation

### ISSUE THREAD

**Issue by ChitharaKarunasekera** [wso2/product-is#16013]
**Adds improvements to** 
- https://github.com/wso2/product-is/issues/9110

- [x] Address the comments of Add Pushed Authorization Request support for IS - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2050
- [x] Improve the architecture of PAR
- [x] Unit tests
- [x] Integration tests
- [x] Bridge gaps in IS and OB implementations

**Comment by chamathns** [comment]
doc issue: https://github.com/wso2/product-is/issues/16030

**Comment by Yoshani** [comment]
## Progress

- [ ] Address the comments of Add Pushed Authorization Request support for IS - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2050

 - [ ] Developer documentation

 - [ ] Public documentation

 - [ ] DB scripts for clearing
 
 - [ ] Unit tests

 - [ ] Integration tests

 - [ ] Parameters to be added to Discovery documentation

**Comment by Yoshani** [comment]
The remaining updates including documentation, DB cleanup scripts and adding the PAR endpoint URL to the discovery endpoint will be tracked with https://github.com/wso2/product-is/issues/16549

**Comment by melanisilva** [comment]
- [ ]  Is this document impacted?
- [ ]  Is the end-to-end (e2e) testing complete?
- [ ]  Are unit tests available?
- [ ]  Are integration tests available?
- [ ]  Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof , Screenshots, Screen recordings)
- [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
- [ ]  Has the cloud readiness been verified?

@Yoshani Could we please have this checklist updated?
