### ISSUE TITLE
Add Documentation Changes Regarding reCAPTCHA support for IDF 

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#16015]
**Describe the improvement**

1. Add the documentation to specify the method to enable reCAPTCHA validation for IDF to master branch, since from IS 6.2 onwards, the particular feature is available. 

2. Add notes for IS 6.0 and 6.1 docs regarding capability to add reCAPTCHA validation in IS version 6.0 and 6.1 from update level 75 and 32 onwards respectively. 

The feature introduced under : https://github.com/wso2/product-is/issues/15952

**Comment by Shaaali** [comment]
6.1 PR : https://github.com/wso2/docs-is/pull/3790/files

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
