### ISSUE TITLE
Getting an error message when redirecting to Protocol tab in a SPA.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16026]
**Describe the issue:**
After creating an application when redirecting to the `Protocol` tab an error message keeps coming.

https://github.com/wso2/product-is/assets/41188245/90aabfe5-1175-4e66-8442-e892df2466f2

![Screenshot 2023-06-09 at 14 25 49](https://github.com/wso2/product-is/assets/41188245/5525881f-25ff-4d56-88ce-062c91cc8e1e)

**How to reproduce:**

1. Create an SPA
2. Redirect to it's Protocol tab

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] - IS 6.2.0-alpha
 - OS: [e.g., Windows, Linux, Mac] - Mac
 - Database: [e.g., MySQL, H2] - H2 / MSSQL
 - Userstore: [e.g., LDAP, JDBC]

**Comment by sadilchamishka** [comment]
Did not reproduced in wso2is-6.2.0-alpha2-SNAPSHOT
https://github.com/wso2/product-is/assets/35717390/9ebc0fac-54ee-4a75-b81b-a6d691641253

**Comment by melanisilva** [comment]
This issue is still reproducible in the latest pack as well.
**Special Note :**  Created a SAML application in the same flow but it was working as expected

### Steps to Reproduce : 

1. log in to the Carbon console : [https://localhost:9443/carbon/](https://localhost:9443/carbon/)
2. From `Add new service provider` create a new OIDC application.
3. log in to the console app 
4. Navigate to the applications page and select the created OIDC app
5. Go to Protocol tab and you will be prompted with an error message 

FYI : @sadilchamishka

**Comment by DonOmalVindula** [comment]
Closing as it's fixed
