### ISSUE TITLE
[Doc] Update the given screenshots with latest in login to salesforce using identity server

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1602]
**Environment**
IS 5.2.0 
Refer to link [1]. Update the screenshots with latest as in [2]

[1]. https://docs.wso2.com/display/IS520/Logging+in+to+Salesforce+using+the+Identity+Server
[2]. https://docs.wso2.com/display/IS530/Logging+in+to+Salesforce+using+the+Identity+Server

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
