### ISSUE TITLE
Incorrect information on documentation for multi attribute login

### ISSUE THREAD

**Issue by DilshaniSH** [wso2/product-is#16023]
**Is your suggestion related to a missing or misleading document? Please describe.**

- In the IS 5.11.0 documentation for the "Multi Attribute Login"[1], second step mention to go to Identity Providers > Resident >  Login Policies > Multi attribute login[2]. 
- But there is no such section as "Login Policies" in the Management Console under the Resident Identity Provider. 

**Describe the improvement**

- Multi Attribute Login configurations are visible under the "Account management" section in the Resident IDP and the document should be corrected to include the correct path. 

---

[1] https://is.docs.wso2.com/en/5.11.0/learn/multi-attribute-login/
[2] https://is.docs.wso2.com/en/5.11.0/learn/multi-attribute-login/#:~:text=Click%20Main%20%3E,Attribute%20Login.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
