### ISSUE TITLE
The relevant migration tool versions is not mentioned in the migration docs

### ISSUE THREAD

**Issue by Akila94** [wso2/product-is#16022]
**Is your suggestion related to a missing or misleading document? Please describe.**

When we follow the migration docs, in the step which we need to use the migration tool to do the migraiton, the version of the migration tool which is needed for the particular migration is not mentioned in the docs.

For eg: If I'm doing the migration from [IS as KM 5.10 to IS 6.0 for APIM 3.1.0 to 4.2.0](https://github.com/wso2-enterprise/migration-docs/blob/main/api-manager/migration-docs/is-as-a-km/is-6.0.0/Upgrade%20IS%20KM%205.10.0%20to%20IS%206.0.0%20for%20APIM%203.1.0%20to%204.2.0.md), the step 2 under the topic "Step 3: Migrate the IS as KM Components" must mention which migration tool version I should use for this particular migration. 

But it is not mentioned and it makes it difficult to determine the correct version.

Related internal: https://github.com/wso2-enterprise/wso2-iam-internal/issues/563

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
