### ISSUE TITLE
Add docs for PAR feature

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16030]
**Describe the issue:**
Related to: https://github.com/wso2/product-is/issues/9110
With IS 6.2-alpha, the PAR specification was onboarded. This is to track the inclusion of documentation related to the feature.

**Comment by nilminiwso2** [comment]
Gdocs: 
- https://docs.google.com/document/d/1bLn3VhDkPHloXOzCaIRm_qP-DF4GZiOsVGFiSWeFu7c/edit
- https://docs.google.com/document/d/11eYSljNmNOa-o0MxP4Xl2-yz9shYOaksn7lk5b526q0/edit

**Comment by Rashmini** [comment]
PAR docs were added with

- https://github.com/wso2/docs-is/pull/4162
- https://github.com/wso2/docs-is/pull/4174
