### ISSUE TITLE
[Doc] Typo in Carbon Remote User Store Manager page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1603]
Type: Bug
Priority: Normal
Severity: Minor
Release: 5.4.0

Typo in the below page. (Give should be Given)
https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager

`Update other fields as required (description is give for each property) and click Add.`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
