### ISSUE TITLE
deployment.toml configuration to add custom tomcat connector is incorrect

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#16046]
**Is your suggestion related to a missing or misleading document? Please describe.**
The deployment.toml configuration to add custom tomcat connector is incorrect, The config mentioned in doc[1] has "n" missing in [custom_trasport.x509.properties].

**Describe the improvement**

 The configuration should be corrected as follows:

[custom_transport.x509.properties]

[1]https://is.docs.wso2.com/en/5.10.0/learn/x509certificate-authenticator/#configuring-the-x509-certificate-for-the-app:~:text=%5Bcustom_trasport.x509.properties%5D

**Comment by asha15** [comment]
Fixed with https://github.com/wso2/docs-is/pull/3822
