### ISSUE TITLE
Template identity.xml.j2 to config scopes for scim2/Me DELETE endpoint

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#16040]
**Describe the issue:**
Currently, it is possible to config the permissions for the scim2/Me DELETE operation from the deployment.toml file as below.

```
[resource_access_control]
scim2_me_delete_method.permission = "/permission/admin/login"
```
But it is not possible to config the scopes for the same resource.

**Expected behavior:**
Scopes for the scim2/Me DELETE operation should be configurable.

**Environment information**
 - Product Version: IS 5.10.0 and later versions

**Comment by Thumimku** [comment]
The public Issue fixed, Hence Ill close the issue
