### ISSUE TITLE
Doc impact on disabling internal clean up by default.

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#16047]
Internal clean up will be disable by default with the PR: https://github.com/wso2/carbon-identity-framework/pull/4724

Need to improve doc on this. Please note followings
- With the IS-6.2, the internal clean up will be disabled.
- To clean the session data, need to execute db scripts externally https://is.docs.wso2.com/en/latest/deploy/data-purging/
- To enable internal cleanup add following configs to the deployment,toml. However, enabling this is not production recommended.
```
[session_data.cleanup]
enable_expired_data_cleanup = true
clean_logged_out_sessions_at_immediate_cycle = true
enable_pre_session_data_cleanup = true
```
https://is.docs.wso2.com/en/latest/deploy/session-persistence/#session-cleanup-configurations

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
