### ISSUE TITLE
[Doc] Provide more information on syslog-ng when configuring system logs

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1604]
Type: Improvement
Priority: High
Severity: Major
Release: 5.4.0

In the below doc, it says,

```
The log files can be retrieved in two ways:
- If syslog-ng is configured, log files are taken from the remote location where the log files are hosted using the syslog-ng server. 
- If syslog-ng is not configured, log files are taken from the local file system (super-tenant or Stand alone apps).
```
https://docs.wso2.com/display/IS540/System+Logs

**Issue**
Some users might not know what syslog-ng is. So, put a hyperlink to their home page or git repo. Also, provide more information on how to configure and connect it with IS.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
