### ISSUE TITLE
Tracking user deletion feature does not work for the default file

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#16043]
**Describe the issue:**

The tracking user deletion feature [1] does not work with the default delete-event.log file in WSO2 Identity Server v5.10.0 as there are no logs being added to it. It works only if you configure a custom CSV file with the following configuration. This needs to be fixed.

[event.default_recorder.user_delete_event]
...
write_to_separate_csv.path = "${carbon.home}/repository/logs/delete-records.csv"

[1] - https://is.docs.wso2.com/en/5.10.0/learn/configuring-users/#tracking-user-deletion-on-deleting-a-user

**Environment information:**
 - Product Version: IS 5.10.0
 - OS: Linux

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
