### ISSUE TITLE
SQL syntax error in <IS-HOME>/dbscripts/mysql.sql file

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16057]
**Describe the issue:**

The SQL script (<IS-HOME>/dbscripts/mysql.sql) contains an SQL syntax error.

**Line (253)** -> `CREATE INDEX IF NOT EXISTS UM_TENANT_ORG_UUID ON UM_TENANT(UM_ORG_UUID);`

**Error ->**
```
Error occurred during SQL script execution

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds 
to your MySQL server version for the right syntax to use near 
'IF NOT EXISTS INDEX_UM_TENANT_ORG_UUID ON UM_TENANT(UM_ORG_UUID)' at line 1
```

<img width="1495" alt="Screenshot 2023-06-14 at 18 25 11" src="https://github.com/wso2/product-is/assets/41188245/4cbb47a8-aff0-4a19-a80a-c7ba95b17d87">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] - [WSO2 Identity Server 6.2.0 Alpha](https://github.com/wso2/product-is/releases/tag/v6.2.0-alpha)
 - OS: [e.g., Windows, Linux, Mac] - Mac
 - Database: [e.g., MySQL, H2] - MySQL
 - Userstore: [e.g., LDAP, JDBC] - Default

---

**Comment by chamathns** [comment]
fixed with https://github.com/wso2/carbon-kernel/pull/3585
