### ISSUE TITLE
[Doc] Mention the difference in using Assertion not encrypted option and self signed cert option 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1605]
Refer to doc [1]. Related to field Assertion Decryption Certificate mention what is the difference in using Assertion not encrypted option and self signed cert option which is available in the salesforce configuration side [2].

[1]. https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server
[2]. cert.png

![cert](https://user-images.githubusercontent.com/31848014/34032921-29fa2bec-e19e-11e7-8c09-b89bc99579c9.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
