### ISSUE TITLE
Missleading step in external IS as ISP using OAuth2 doc

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1606]
**Environment**
IS 5.4.0 and other versions as well

In the doc [1]  it is mentioned to set up playground sample. Is better to mention as use playground as  Service provider.

[1]https://docs.wso2.com/display/IS540/Login+to+Identity+Server+using+another+Identity+Server+-+OAuth2

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
