### ISSUE TITLE
Behaviour Change in Access Tokens issued for authenticated applications

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#16060]
**Describe the issue:**
Following two behavioural changes are done for the access tokens issuing for authenticated applications using a grant type like client credentials.

-  `sub` claim of the jwt tokens issued for authenticated application is set as client id of the authenticated application. (Previous behaviour -  `sub` claim is set as the user ID of the application owner)
- Username field is removed from the introspection response for access tokens issued for authenticated applications.

To keep the backward compatibility, we have introduced two configurations. Two configurations can be set to false for the previous behaviour.

```
[oauth]
use_client_id_as_sub_claim_for_app_tokens = false
remove_username_from_introspection_response_for_app_tokens = false
```

**Related issues:**
https://github.com/wso2/product-is/issues/14771

**Related PRs:**
https://github.com/wso2/carbon-identity-framework/pull/4633
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2088

**Comment by melanisilva** [comment]
### Verified 
IS Pack - [WSO2 Identity Server-7.0.0-m4-SNAPSHOT](https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m4-SNAPSHOT.zip)

<img width="1160" alt="Screenshot 2023-10-23 at 16 52 36" src="https://github.com/wso2/product-is/assets/41188245/ed721167-04d9-418c-9ead-d07be0c050de">
