### ISSUE TITLE
Adding Tenant Details to Session DB tables

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16069]
**Describe the issue:**
In IDN_AUTH_SESSION_STORE and IDN_AUTH_TEMP_SESSION_STORE tables there are records with tenant Id as -1. Further analysing into this, when populating the `IDN_AUTH_SESSION_STORE` table,  for session types such as `AuthorizationGrantCache` we do not add tenant details [1] and therefore at the db insert query we are setting the tenant Id with the default invalid (-1) id [2]. 

Even though this does not have any impact on current flows since in these session types the sessions are created using a key/id that is unique across all tenants, it is possible that not having the tenant details can cause issues at tenant specific session cleanup efforts. Therefore, as an improvement we should add the correct tenant Id when storing the session details in these tables.

Identified session types that do not store the tenant Id correctly:
- AuthorizationGrantCache
- OAuthSessionDataCache
- SAMLSSOSessionIndexCache
- CASServiceTicketCache
- FIDO2Cache
- TicketGrantingTicketCache
- SAMLSSOParticipantCache

**How to reproduce:**
1. Try out a basic login flow to the console or myaccount using super tenant or any other tenant.
2. Check tenant id of the IDN_AUTH_SESSION_STORE table for session type  `AuthorizationGrantCache`

The tenant Id for `AuthorizationGrantCache` would always be -1.

**Expected behavior:**
The correct tenant Id should be resolved and added to these db table.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/42184c33eaf6dd6157e49fe230a85c2275e75a62/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/cache/AuthorizationGrantCache.java#L274
[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java#L371

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
