### ISSUE TITLE
Deprecating IdentityPersistenceManager

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#16074]
New class is created for SAML SSO configs to replace IdentityPersistenceManager

### Related PRs
- https://github.com/wso2/carbon-identity-framework/pull/4727
- https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/395
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2099
- https://github.com/wso2-extensions/identity-tool-samlsso-validator/pull/41

**Comment by rksk** [comment]
Related https://github.com/wso2/product-is/issues/16162
