### ISSUE TITLE
IS 6.1.0 docs contain attributeSyncMethod config docs without the feature.

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16075]
**Is your suggestion related to a missing or misleading document? Please describe.**
IS 6.1.0 docs mentions `attributeSyncMethod` config at the IDP rest api docs [1].
<img width="641" alt="image" src="https://github.com/wso2/product-is/assets/47671237/c3f181cc-3f33-4453-8909-8ac0bfe31aa9">

But this feature was added to the product after the 6.1.0 release. Therefore 6.1.0 pack does not support this config.

**Describe the improvement**
The 6.1.0 docs should not mention this config.

[1] https://is.docs.wso2.com/en/latest/apis/idp-rest-api/#/Provisioning/getJITConfig

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
