### ISSUE TITLE
Large archived log files will be empty when downloaded

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1608]
Type: Bug
Priority: Normal
Severity: Major
Release: 5.4.0

**Steps**
1. Go to management console -> Monitor -> System Logs
2. Expand Show archived logs and download a log file which is greater than 400 MB in size

**Issue**
No content in the downloaded file. 

**Note**: Out of the below files, all other files will be successfully downloaded 
![8](https://user-images.githubusercontent.com/1845370/34036584-acec98c0-e1ab-11e7-856f-3f7424c5eb54.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
