### ISSUE TITLE
Add instructions to update deployment.toml configs when super admin password is changed

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#16081]
**Is your suggestion related to a missing or misleading document? Please describe.**
When super admin password is changed after first server startup, the deployment.toml should be updated with the below config in order to map them to the relevant RecoveryEndpointConfig.properties file. This template fix was added with [1], but doc has only included service_url template map. Doc should include the password map, possibly username map as well, so that when the super admin password is changed from the carbon console, the users can add the below config with the updated password to not come across [3].

```
[identity.auth_framework.endpoint]
password = "<new super admin password>"
```

**Describe the improvement**
Include username password config to map into relevant RecoveryEndpointConfig.properties file.

---

### Optional Fields

**Versions checked**
IS 6.1.0

**Related Issues:**

[1] https://github.com/wso2/carbon-identity-framework/pull/3207
[2] https://github.com/wso2/docs-is/pull/2234
[3] https://github.com/wso2/product-is/issues/12469

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
