### ISSUE TITLE
Notification should be provided when a null value passed as the domain name

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1609]
**Environment**
IS standalone pack
JDK -1.8
DB - postgres sql 9.6
ubuntu - 15.10

**Steps to recreate the Issue**
1. Create facebook and google as IDP
2. Create SP and authenticate via FB and Google
3. Access Travelocity Application
4. Since the fidp is not provided with an option will appear to provide the domain name
5. Keep the domain name blank and hit the submit option

**Observations**
1. No error message or notification message to indicate the domain cannot be null

![screenshot from 2017-12-15 15-25-46](https://user-images.githubusercontent.com/14962228/34036758-54860a08-e1ac-11e7-951c-c50f047b63ea.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
