### ISSUE TITLE
Issue in SCIM 2.0 REST API ULRs in User Roles

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16103]
**Is your suggestion related to a missing or misleading document? Please describe.**
In[ Use SCIM 2.0 REST API](https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/add-user-roles/#use-scim-20-rest-api) section of Add User Roles documentation, the request URL is given as https://{IS_IP}:{IS_PORT}/wso2/scim2/Groups and sample request URL is given as https://localhost:9443/wso2/scim2/Groups. 

1. The given URL is not working. The Working URL is https://{IS_IP}:{IS_PORT}/scim2/Groups. 
2. In 5.11 or above versions of Identity Server, Roles end point should be used for add user role operation instead of Groups end point. 

**Describe the improvement**
The URL should be updated to use correct URL with Roles end point instead of Groups end point.

**Comment by dinzie95** [comment]
Hi All,

In addition to the above, the statement _"In SCIM 2.0, creating a role is the same as creating a group."_ is also misleading.

Thanks & Regards.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
