### ISSUE TITLE
SCIM user bulk operation not returning specific error messages

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#16110]
SCIM user bulk operation does not return specific error messages when claim uniqueness is violated. This can be reproduced in WSO2 Identity Server v6.1.0.

**Steps to reproduce in WSO2 IS v6.1.0**

- Follow the prerequisite steps in [1].
- Apply configurations provided in [2].
- Perform SCIM user bulk API call, but with duplicate unique claim values.

The following generic message can be seen for the user that has not been added and it can be noted that a null value has been appended to the message where ideally the specific error message should be present. 

```
{
    "bulkId": "ytrewq",
    "method": "POST",
    "response": "{\"schemas\":[\"urn:ietf:params:scim:api:messages:2.0:Error\"],\"scimType\":\"invalidValue\",\"detail\":\"Error in adding the user: Russell. null\",\"status\":\"400\"}",
    "status": {
        "code": 400
    }
}
```
[1] - https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/bulk-import-users/
[2] - https://is.docs.wso2.com/en/latest/guides/dialects/configure-unique-claims/

**Comment by UdeshAthukorala** [comment]
This is already fixed in public branch via:
- https://github.com/wso2/carbon-kernel/pull/3573

The new error message contains the specific error message.

```
{
    "bulkId": "ytrewq",
    "method": "POST",
    "response": "{\"schemas\":[\"urn:ietf:params:scim:api:messages:2.0:Error\"],\"scimType\":\"invalidValue\",\"detail\":\"Error in adding the user: Udesh. The value defined for Mobile is already in use by different user!\",\"status\":\"400\"}",
    "status": {
         "code": 400
     }
}
```

**Comment by UdeshAthukorala** [comment]
Closing since this was fixed in master with : https://github.com/wso2/carbon-kernel/pull/3573
