### ISSUE TITLE
[Improvement] Need to improve the documentation about the default and Role based scope validation in IS

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#16115]
**Is your suggestion related to a missing or misleading document? Please describe.**

We have two different behaviors in IS server in terms of scope validation.

1. Default behavior - We use DefaultCallBackHandler to handle authz requests and there we are approving all requested scopes.
2. Enabling scope validators - Currently, we have 2 validators shipped with IS (Role based scope validators and XACML scope validators).

Currently, there is no documentation about Role based scope validation and said default behavior in IS. We need to improve the documentation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
