### ISSUE TITLE
Basic login page User name Input field Place holder issue.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16117]
**Describe the issue:**
 
<img width="1512" alt="Screenshot 2023-06-22 at 09 23 28" src="https://github.com/wso2/product-is/assets/41188245/8cdf75da-0e5a-44c3-81f8-78280927b00a">

**How to reproduce:**
1. Create a sample application 
2. try to login to the app

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: [e.g., IS 5.10.0, IS 5.9.0] - IS 6.2.0-alpha
- OS: [e.g., Windows, Linux, Mac] - Mac
- Database: [e.g., MySQL, H2] - H2 / MSSQL
- Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment]
This is not reproducible in alpha4-SNAPSHOT
