### ISSUE TITLE
Provide a sample use case for getHybridRoles() operation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1611]
In [1] there is no sample use case for getHybridRoles() operation. Please provide a sample as the current documentation does not illustrate the real use that the operation is exposing.

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-getHybridRoles()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
