### ISSUE TITLE
Improve Email Notification Section of Password Policy Connector Docs

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16113]
**Is your suggestion related to a missing or misleading document? Please describe.**
The password policy connector documentation [1] has a separate section on Enabling Email Notifications [2]. This email notification sending is not available for any IS version except for IS 5.6.0. Even though this limitation is mentioned in the docs, the structure and the way it is mentioned is not significant enough to convey that this is not supported in latest IS versions. Customers have mistakenly tried configuring this section as the `This feature is only supported for IS versions 5.6.0 .` part is not significant enough. Therefore we should highlight that fact.
<img width="1062" alt="image" src="https://github.com/wso2/product-is/assets/47671237/fb09436a-feb1-434d-b71a-b74c11567b78">

[1] https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md
[2] https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md

**Describe the improvement**
Highlight the section to inform that email notification sending feature is not supported in latest IS versions except for IS 5.6.0.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
