### ISSUE TITLE
Remove unsupported features from the UI for Password Policy Feature

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16112]
**Describe the issue:**
We do not support sending email notifications in the password policy feature now even though it was supported previously in the IS 5.6.0 version. But still we have the option to set `Prior Notice Time in Days` config for Password Expiry in the UI even though sending notification is not supported. This config should be removed from the UI.
<img width="757" alt="image" src="https://github.com/wso2/product-is/assets/47671237/4c673195-477e-42af-84e3-add82fd7166f">

**How to reproduce:**
1. Add the password policy connector to the IS and login through the mgt console.
2. Go to Resident Idp --> Password Policies --> Password Expiry

**Expected behavior:**
The UI should not provide the config `Prior Notice Time in Days`.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - Connector Version: 1.0.28
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
