### ISSUE TITLE
Getting configuration.error in authentication flow with Advanced Authentication Configuration 

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16119]
**Describe the issue:**
After configuring Advanced Authentication Configuration to use JWT Basic authenticator and Google Authentication (configured as a federated IDP) getting following error page when try to log into the sample application (Service provider). 

<img width="1420" alt="Screenshot 2023-06-22 at 14 49 29" src="https://github.com/wso2/product-is/assets/25563417/cad8e816-58e5-400b-934d-a8f35fcc568a">

**How to reproduce:**
1. Configure Google as an Identity provider by following https://is.docs.wso2.com/en/latest/guides/identity-federation/google/#register-an-identity-provider
2. Configure service provider and set authentication steps by following https://is.docs.wso2.com/en/latest/guides/identity-federation/google/#register-a-service-provider. 
Authenticators - JWT Basic and Google. 
<img width="1078" alt="Screenshot 2023-06-22 at 17 02 13" src="https://github.com/wso2/product-is/assets/25563417/d658be96-7c4e-4d8a-810c-9e255dd53d31">

3. Try to log into the sample application.

https://github.com/wso2/product-is/assets/25563417/575a417f-68d4-425e-88c7-be2ec57e7e58

**Expected behavior:**
User should be able to log into the sample application. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Since it is expected to send a JWT token with the authentication request when this authenticator is engaged, this problem can be expected. With the API based authentication feature in the IS 7, this capability is no longer required. Hence we will not be fixing this concern.
