### ISSUE TITLE
Provide Inline Form Field Validation Support to the IS Management Console

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#16116]
#### Is your suggestion related to an experience? Please describe.
We currently don't have inline form field validation support for the Management Console in Identity Server. For example, the input fields that expect URLs as inputs (like callback URL fields) allow URL unsafe or invalid characters like whitespace. This negatively impacts the user experience.

#### Describe the improvement
Provide the inline form field validation support so that fields like URL, client ids, and client secrets will be validated as the user enters them.

#### How to Reproduce

1. Create an IdP in the Management Console.
2. Go to the edit page of the created IdP and navigate to the created **Federated Authenticators** -> **Google Configuration**.
3. Update the `Callback URL` field with an invalid URL.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
