### ISSUE TITLE
Provide pagination support for IDP / SP pages

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1612]
**Environment**
IS standalone pack
JDK -1.8
DB - postgres sql 9.6

It would be better to provide **pagination support for IDP** list page as when there are around 100 IDPs it's difficult to scroll and search the required IDP.

![screenshot from 2017-12-15 15-35-01](https://user-images.githubusercontent.com/14962228/34037106-89a7c716-e1ad-11e7-92cf-51e407337a73.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
