### ISSUE TITLE
Getting Error when try to edit service provider after configuring and authenticate with Google IDP. 

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16123]
**Describe the issue:**
Getting **Error while reading Service Provider** when try to edit a service provider after configuring Google IDP in Federated Authentication or Advanced Configuration and login into the service provider.

**How to reproduce:**
1. Configure Google as an Identity provider by following https://is.docs.wso2.com/en/latest/guides/identity-federation/google/#register-an-identity-provider
2. Configure service provider and set authentication steps by following https://is.docs.wso2.com/en/latest/guides/identity-federation/google/#register-a-service-provider.
3. Configure Google authenticator in Federated Authentication or Advanced Configuration's authentication step.
4. Login into the service provider.
5. Go back to carbon console and try to edit the service provider.
6. Following error message is displayed. 
<img width="1468" alt="Screenshot 2023-06-22 at 14 50 24" src="https://github.com/wso2/product-is/assets/25563417/d3d42413-de60-4c21-94c2-5abee1481790">

https://github.com/wso2/product-is/assets/25563417/d7b03dff-5b4d-461e-83b7-c7a892a05617

https://github.com/wso2/product-is/assets/25563417/9bb6416a-a4f3-43d7-96f8-680f892600ed

https://github.com/wso2/product-is/assets/25563417/52ff4856-4f67-4037-8197-37e8920a3d8b

**Expected behavior:**

User should be able to edit service provider without any errors. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
 - OS: [e.g., Windows, Linux, Mac] - MAC
 - Database: [e.g., MySQL, H2] - H2
 - Userstore: [e.g., LDAP, JDBC]

**Comment by LakshiAthapaththu** [comment]
The following error is observed when try to update JIT provisioning configurations after setting up Google IPD in the sign in flow and login the service provider once. This could be related to the same issue reported above. Verify JIT provisioning feature after fixing the above. 

<img width="1492" alt="Screenshot 2023-06-23 at 15 34 29" src="https://github.com/wso2/product-is/assets/25563417/9dbd407c-b68c-4347-9f21-3b015529a41a">

> Stack trace : 
> [2023-06-23 15:34:12,992] [3dc009c3-901a-45b0-befb-cfb2b73144c3] ERROR {org.wso2.carbon.idp.mgt.ui.client.IdentityProviderMgtServiceClient} - Error in updating the Identity Provider for a given tenant org.wso2.carbon.idp.mgt.stub.IdentityProviderMgtServiceIdentityProviderManagementExceptionException: IdentityProviderMgtServiceIdentityProviderManagementExceptionException
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> 	at java.base/java.lang.Class.newInstance(Class.java:584)
> 	at org.wso2.carbon.idp.mgt.stub.IdentityProviderMgtServiceStub.updateIdP(IdentityProviderMgtServiceStub.java:3029)
> 	at org.wso2.carbon.idp.mgt.ui.client.IdentityProviderMgtServiceClient.updateIdP(IdentityProviderMgtServiceClient.java:320)
> 	at org.apache.jsp.idpmgt.idp_002dmgt_002dedit_002dfinish_002dajaxprocessor_jsp._jspService(idp_002dmgt_002dedit_002dfinish_002dajaxprocessor_jsp.java:199)
> 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
> 	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207)
> 	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
> 	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
> 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
> 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
> 	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
> 	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
> 	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
> 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:167)
> 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
> 	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
> 	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
>

**Comment by chamathns** [comment]
Closing since it's fixed with https://github.com/wso2/carbon-identity-framework/pull/4747
