### ISSUE TITLE
Cannot disable Google onetap feature from carbon console.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16128]
**Describe the issue:**
Once a Google IDP connection is created and google one tap is enabled from the carbon console, Getting an error message as below once we try to disable Google one-tap

```
Error while updating Identity Provider information. IdentityProviderMgtServiceIdentityProviderManagementExceptionException
```

<img width="1512" alt="Screenshot 2023-06-23 at 12 30 33" src="https://github.com/wso2/product-is/assets/41188245/bd4a92f6-0a2d-4fcc-a8b2-6966c05a60ac">

https://github.com/wso2/product-is/assets/41188245/0c3f956b-4e3d-450a-9520-feee34527fcc

**How to reproduce:**

1. Create a Google IDP and enable one tap. https://is.docs.wso2.com/en/latest/guides/identity-federation/google/#sign-in-with-google-one-tap
3. Create a service provider and add Google as an authentication step
4. Go to the Google IDP from the carbon console and try to uncheck the Google one-tap check box.
5. An error message will pop up.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: [e.g., IS 5.10.0, IS 5.9.0] - IS 6.2.0-alpha
- OS: [e.g., Windows, Linux, Mac] - Mac
- Database: [e.g., MySQL, H2] - H2 / MSSQL
- Userstore: [e.g., LDAP, JDBC]

---

**Comment by chamathns** [comment]
This is not reproducible in alpha4-SNAPSHOT
