### ISSUE TITLE
[Regression] Missing claims page always prompted for JIT provisioned users even though claims provided on first login

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#16133]
**Describe the issue:**
The missing claims page is always prompted for JIT-provisioned users even though missing claims are provided during the first login.

**How to reproduce:**
- Configure a federated IDP with silent JIT provisioning.
- Configure a service provider to use the federated IDP and select the "Assert identity using mapped local subject identifier" option under the "Local & Outbound Authentication Configuration"
- Add the country claim as requested for the service provider and mark it as mandatory.
- Login to the service provider, since the country claim is not returned from the federated IDP, the missing claim would be prompted.
- Enter the missing claim and proceed to log in. Verify the user is JIT provisioned and the claim has been added to the user.
- Logout and login again.
- The missing claims page would be prompted again.

**Expected behavior:**
The missing claims should not be prompted again because the JIT-provisioned user already has the claim present in the profile.

The same flow works fine in IS-5.10.0(tested in update level 234) without any issues.

**Analysis**
The issue occurs because the user is not found and claims for the local user cannot be retrieved from[1] in IS-6.0.0. Whereas in IS-5.10.0 this method[2] returns the claims for the user.

**Environment information** **:**
 - Product Version: [IS-6.0.0]
 
[1]https://github.com/wso2/carbon-identity-framework/blob/v5.23.8/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java#L645-L646
[2]https://github.com/wso2/carbon-identity-framework/blob/v5.17.5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java#L605-L606

---

**Comment by UdeshAthukorala** [comment]
Closing since this was fixed in reported versions and master branch.
Refer this for the fix: https://github.com/wso2/carbon-identity-framework/pull/4769
