### ISSUE TITLE
Provide a search option for IDP and SP list view

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1613]
**Environment**
IS standalone pack
JDK -1.8
DB - postgres sql 9.6

It would be better to provide searchability support for IDP/SP list page.

If a user has multiple Service Provider and IDPs configured in their environment it would be really useful to provide a **search option** so that user can search the required IDP or SP easily.

For example:

I have more than 100 IDPs in the setup, but as a user, there is no option for me to search and filter out the required IDP.

![screenshot from 2017-12-15 15-35-01](https://user-images.githubusercontent.com/14962228/34037288-42b3b3c8-e1ae-11e7-8ef3-503e0d14758e.png)

**Comment by SwatiNEC** [comment]
Please review the code for the same and serach option for SP list is already implemented.

**Comment by SwatiNEC** [comment]
Hi @sashikamw @pulasthi7 @isharak ,

Request you to plese review the code asap.
