### ISSUE TITLE
Server error when using device authorization grant with scopes

### ISSUE THREAD

**Issue by piyarathnalakmali** [wso2/product-is#16139]
**Describe the issue:**
Server error when using device code grant with scopes due to a NPE during authentication after the user code verification. Flow works as expected when scopes are not requested. 

**How to reproduce:**

1. Configure the device grant flow as mentioned in the document[1]
2. Send a request to the `device_authorize` endpoint with scopes

  Sample request
  ```
  curl -k -X POST -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 
  'client_id=e8nGclNZ0vCKMBXaFYPyv_JGK9sa' --data-urlencode 'scope=openid' https://localhost:9443/oauth2/device_authorize
  ```

3. Visit the `verification_uri_complete` and try to login 
4. A server error occurs due to a NPE 

**Expected behavior:**
User should be successfully logged in

**Environment information**
 - Product Version: IS 6.2.0-alpha2

[1] [https://is.docs.wso2.com/en/latest/guides/access-delegation/try-device-flow/#enable-the-device-authorization-grant](https://is.docs.wso2.com/en/latest/guides/access-delegation/try-device-flow/#enable-the-device-authorization-grant)

**Comment by Yoshani** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2109
