### ISSUE TITLE
identityUserMetadataMgtHandler to track last login time and last password update time

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16134]
This is to document the functionality added with https://github.com/wso2/product-is/issues/4515

Add the following config to <wso2is-home>/repository/conf/deployment.toml file to enable the identityUserMetadataMgtHandler event handler.
```
[identity_mgt.events.schemes.identityUserMetadataMgtHandler]
properties.enable=true
```

Once enabled, it will update the login timestamp in `http://wso2.org/claims/identity/lastLogonTime` claim and last password update timestamp into `http://wso2.org/claims/identity/lastPasswordUpdateTime` claim.

----

If you need to keep track of lastLogonTime only, the following line also can be added next to above configuration.
```
subscriptions = ["POST_AUTHENTICATION"]
```

If you need to keep track of lastPasswordUpdateTime only, the following line also can be added next to above configuration.
```
subscriptions = ["POST_UPDATE_CREDENTIAL", "POST_UPDATE_CREDENTIAL_BY_ADMIN"]
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
