### ISSUE TITLE
Change password prompt does not appear after passing the configured password expiry time

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16132]
**Describe the issue:**
After configuring password expiry feature in WSO2 Identity Server and setting expiry to n days (eg: 1 day), change password is not prompted even after passing n days (1 day). 

**How to reproduce:**
1. Set up password expiry feature by following https://is.docs.wso2.com/en/latest/guides/password-mgt/password-policies/#configure-password-expiry .
2. Set password expiry time to 1 day.
3. Create a user.
4. For the testing purpose set Last Password Update claim as a default claim in the profile (as described in https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md#testing-the-sample-app)  and edit the Last Password Update field to a more than 1 day back timestamp. 
Eg: if current date - Date and time (GMT): Friday, 23 June 2023 01:00:00 update 
       Last Password Update as Date and time (GMT): Thursday, 22 June 2023 00:00:00. 
5. Try to log into service with the created user.

https://github.com/wso2/product-is/assets/25563417/863b9267-7cc1-4f7b-b90c-06685cd0c3da

**Expected behavior:**
Password change should be prompted to user after passing the set up expiry time.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
 - OS: Mac
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

**Comment by dhaura** [comment]
In here, the password resetting is done with an added extra day to the `Password Expiry In Days`. That means the password resetting is enforced not just after `Password Expiry In Days` but `Password Expiry In Days + 1 Day`. The cause for this due to casting the day difference into ```int```.

**Comment by DMHP** [comment]
@hwupathum Please consider this in the unification process too.
