### ISSUE TITLE
Error page after canceling and navigating to My Account portal (through the given link) in FIDO

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16140]
**Describe the issue:**
Getting an error page after clicking on the **My Account** link appeared in the **Sign In with security key/biometrics interrupted popup** after canceling the Choose a passkey popup. 

**How to reproduce:**
1. Set up Passwordless login using FIDO2 by following https://is.docs.wso2.com/en/6.0.0/guides/passwordless/fido/#passwordless-login-using-fido2
2. Login into the Sample application.
3. In the Choose a passkey popup, click on cancel.
4. You will be navigated to the following page.
![Screenshot 2023-06-26 at 12 40 51](https://github.com/wso2/product-is/assets/25563417/c88cae0e-f024-4eff-9636-933bbae9dd66)
5. Click on My Account.
6. You will be navigated to the following error page.
![Screenshot 2023-06-26 at 12 41 58](https://github.com/wso2/product-is/assets/25563417/6c610641-1213-4680-b54c-ab3ff3018ccf)

https://github.com/wso2/product-is/assets/25563417/c33d40d0-9087-4359-ade5-53edbe9fb3ea

**Expected behavior:**
User should be navigated to the My Account portal of the corresponding tenant. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
OS: Mac
Database: H2
Userstore: [e.g., LDAP, JDBC]

**Comment by AfraHussaindeen** [comment]
Reopening this issue as the problem still persists when following the above-mentioned steps with the product version `IS 7.0.0-m4-SNAPSHOT`.  However, this time, the error page displayed is as follows:

<img width="1505" alt="Error Page" src="https://github.com/wso2/product-is/assets/47135592/fdc292d1-12a7-451c-beff-a38acf5f3cb7">

**Comment by lucagutierrezdev** [comment]
Hello Team, reopening this for a backport to 6.1.0, where the issue is still present.
