### ISSUE TITLE
[DOC] Information needs to be added for OAuth request path authentication where consent should skip by config changes

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1614]
Please improve the doc page [1] to incorporate the $subject. Please refer mail [2] for more details.
label: IS-5.4.0

[1] https://docs.wso2.com/display/IS540/OAuth+Request+Path+Authenticator
[2] [IS] [OAuth] Cannot be generated an authorization code using an active access token for "OAuthRequestPathAuthenticator"

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
