### ISSUE TITLE
TOTP authentication flow fails with an Exception

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16141]
**Describe the issue:**
Authenticating into a sample application using TOTP authentication flow fails with the following exception when,

- Entering the token taken from the authenticator application 
- Trying to get the token via an email.

> [2023-06-26 13:12:10,561] [6dcbd25d-7d50-43e3-a418-5d696283f974] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 32 alphabet but not a possible value. Expected the discarded bits to be zero.
> 	at org.apache.commons.codec.binary.Base32.validateCharacter(Base32.java:577)
> 	at org.apache.commons.codec.binary.Base32.decode(Base32.java:396)
> 	at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:482)
> 	at org.apache.commons.codec.binary.BaseNCodec.decode(BaseNCodec.java:465)
> 	at org.wso2.carbon.identity.application.authenticator.totp.util.TOTPAuthenticatorCredentials.decodeSecret(TOTPAuthenticatorCredentials.java:264)
> 	at org.wso2.carbon.identity.application.authenticator.totp.util.TOTPAuthenticatorCredentials.checkCode(TOTPAuthenticatorCredentials.java:230)
> 	at org.wso2.carbon.identity.application.authenticator.totp.util.TOTPAuthenticatorCredentials.authorize(TOTPAuthenticatorCredentials.java:352)
> 	at org.wso2.carbon.identity.application.authenticator.totp.util.TOTPAuthenticatorCredentials.authorize(TOTPAuthenticatorCredentials.java:331)
> 	at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.isValidTokenLocalUser(TOTPAuthenticator.java:692)
> 	at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.processAuthenticationResponse(TOTPAuthenticator.java:410)
> 	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:100)
> 	at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.process(TOTPAuthenticator.java:145)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:688)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:657)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:242)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:220)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:118)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:198)
> 	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:346)
> 	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doPost(CommonAuthenticationHandler.java:57)
> 	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doGet(CommonAuthenticationHandler.java:46)
> 	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:54)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
> 	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
> 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
> 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
> 	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
> 	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
> 	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
> 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:167)
> 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
> 	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
> 	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:829)

**How to reproduce:**
1. Set up TOTP authentication by following https://is.docs.wso2.com/en/latest/guides/mfa/2fa-totp/
3. Try to authenticate into the sample application by,

- Entering the generated token by authenticator application after scanning the QR code.
- Getting the token into user's email account.  

https://github.com/wso2/product-is/assets/25563417/988aae4e-d658-40f3-a0c1-e07c64fe0d9e

**Expected behavior:**
User should be able to authenticate into a sample application successfully using TOTP.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: [IS 6.2.0 Alpha 2](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha2/wso2is-6.2.0-alpha2.zip)
OS: Mac
Database: H2
Userstore: [e.g., LDAP, JDBC]

**Comment by Yoshani** [comment]
Could not reproduce in latest build.

Environment information (Please complete the following information; remove any unnecessary fields) :
Product Version: wso2is-6.2.0-alpha4-SNAPSHOT
OS: Mac
Database: H2
Userstore: [e.g., LDAP, JDBC]

https://github.com/wso2/product-is/assets/46979289/2ba0803f-66f9-4213-8a9a-cc3ab1599bad

**Comment by LakshiAthapaththu** [comment]
Not getting reproduced in the latest build.

Environment information:
Product Version: wso2is-6.2.0-alpha4-SNAPSHOT
OS: Mac
Database: H2
Userstore: JDBC
