### ISSUE TITLE
Move the logs management from the carbon kernel

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#16144]
**Is your feature request related to a problem? Please describe.**
Currently, any changes to our logs require a kernel release, which is not practical. By moving these logs to a dedicated repository, we can manage them more efficiently and make improvements more easily. 
This new repository will serve as a centralized location for managing and enhancing our logs across the identity server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
