### ISSUE TITLE
UI issues after viewing permissions of a role during user creation flow

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16148]
**Describe the issue:**
1. Go to new react console 
2. Go to Manage > Roles section
3. Create a few roles
4. Go to Manage > Users section
5. Start new user creation
6. During user creation, once you come to the role assignment view click on the view permission icon in one of the role
7. Once you go to the permissions view, click on `back to list` ( TODO: Beter to change this term to `Back to Role List` or a similar term
![Screenshot - 2023-06-26T235638 195](https://github.com/wso2/product-is/assets/25483865/282b936b-2c93-499e-896d-685f83c1da51)
8. When you come back to roles list, you don't see the NEXT button to proceed.
![Screenshot - 2023-06-26T235705 789](https://github.com/wso2/product-is/assets/25483865/45665cde-249d-4aea-9786-d691f9cf338f)

9. When you landed on a permissions list and click the `Previous` button to return back you will be prompted with the groups list. If you proceed there onwards, next time permission view is not working

[Screencast from 2023-06-26 23:54:17.webm](https://github.com/wso2/product-is/assets/25483865/5ff53662-584c-4c11-a30b-5c0e1f457256)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [6.2.0-alpha4-snaphot]
 - OS: [ Linux]
 - Database: [ H2]
 - Userstore: [ JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by melanisilva** [comment]
Expected to be resolved with the new console.
