### ISSUE TITLE
Uncaught exception when loading user store configuration blocks majority of tenant operations

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#16154]
**Describe the issue:**
It seems there's no try-catch statement when attempting to load a given user store configuration file which can break tenant-aware operations such as authentication. This issue was already fixed for WSO2 IS 5.11.0 and above [1], but we need to backport this to 5.10.0 [2] as it's affecting a customer.

**How to reproduce:**
1. Create a new database and apply the needed scripts for a secondary user store.
2. Create a new tenant.
3. Using the new tenant's management console, add the new secondary user store.
4. Encode the new tenant's admin username and password in Base64 to use in further requests.
5. Use `GET t/{New_Tenant_Domain}/api/server/v1/userstores` to get the userstore ID.
6. Use the ID on `GET t/{New_Tenant_Domain}/api/server/v1/userstores/{UserStore_Domain_ID}` to get full user store JSON data.
7. Keep only the required fields (`typeId`, `name`, `description`, and `properties`), and change `typeId` to something invalid. Example: `SW52YWxpZA==` which is `Invalid` in Base64.
8. Update the userstore with this faulty data on `PUT t/{New_Tenant_Domain}/api/server/v1/userstores/{UserStore_Domain_ID}`.
9. Attempt to use `GET t/{New_Tenant_Domain}/api/server/v1/userstores/{UserStore_Domain_ID}` to get userstore information again.
10. See `NullPointerException` in `wso2carbon.log` (Requires DEBUG logs on `user.core` and `identity.core`)

**Expected behavior:**
I'm not sure if a `typeId` validation was originally expected, but on IS 5.11.0 and above, even though there's an invalid userstore configuration file, other tenant-aware behaviours are not affected by this and proceed normally as the exception is caught and suppressed. Things like authentication, user management, etc, shouldn't care about a faulty configuration.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - Userstore: JDBC

---

[1] wso2/carbon-kernel#2807

[2] https://github.com/wso2/carbon-kernel/blob/v4.6.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/tenant/JDBCTenantManager.java#L779C17-L788C18

**Comment by UdeshAthukorala** [comment]
**Steps to Verify:**
1. Create a new database and apply the needed scripts for a secondary user store.
2. Create a new tenant.
3. Using the new tenant's management console, add the new secondary user store.
4. Encode the new tenant's admin username and password in Base64 to use in further requests.
5. Use `GET t/{New_Tenant_Domain}/api/server/v1/userstores` to get the userstore ID.
6. Use the ID on `GET t/{New_Tenant_Domain}/api/server/v1/userstores/{UserStore_Domain_ID}` to get full user store JSON data.
7. Keep only the required fields (`typeId`, `name`, `description`, and `properties`), and change `typeId` to something invalid. Example: `SW52YWxpZA==` which is `Invalid` in Base64.
8. Update the userstore with this faulty data on `PUT t/{New_Tenant_Domain}/api/server/v1/userstores/{UserStore_Domain_ID}`.
9. Attempt to use `GET t/{New_Tenant_Domain}/api/server/v1/userstores/{UserStore_Domain_ID}` to get userstore information again.
10. See `NullPointerException` in `wso2carbon.log` (Requires DEBUG logs on `user.core` and `identity.core`)
11. Try to log in to this tenant with admin credentials and should be able to login and access the tenant resources.
12. Try get the users of the tenant using scim2/Users api and should be able to retrieve. (ex: https://localhost:9443/t/{New_Tenant_Domain}/scim2/Users)
13. 12. Try get the applications  of the tenant using scim2/Users api and should be able to retrieve. (ex: https://localhost:9443/t/{New_Tenant_Domain}/api/server/v1/applications)

**Comment by UdeshAthukorala** [comment]
Closing since this was fixed in master branch and and in the reported product version.
- Fix : https://github.com/wso2/carbon-kernel/pull/2807

**Comment by UdeshAthukorala** [comment]
Closing since this was fixed in master branch and and in the reported product version.
- Fix : https://github.com/wso2/carbon-kernel/pull/2807
