### ISSUE TITLE
Illegal access attempt error logged even when the user is successfully authenticated

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1615]
Type: Bug
Priority: High
Severity: Major
Release: 5.4.0

**Steps**
1. Enable the admin services
2. Send a request with addUserStore operation in UserStoreConfigAdminService to create a user store with basic authorization

**Issue**
The following error will be logged saying it's an illegal attempt, but successfully authenticates the user and creates a user store
```
[2017-12-15 17:13:42,479] ERROR {AUDIT_LOG}-  Illegal access attempt at [2017-12-15 17:13:42,0476] from IP address 127.0.0.1 while trying to authenticate access to service UserStoreConfigAdminService 
[2017-12-15 17:13:42,755]  INFO {AUDIT_LOG}-  'admin@carbon.super [-1234]' logged in at [2017-12-15 17:13:42,755+0530] 
```

**Comment by omindu** [comment]
@dilinisg Have you set the 'Preemptive Authentication' option in SOAPUI ?

**Comment by dilinisg** [comment]
@omindu - Enabled 'Preemptive Authentication' and it was working fine. Thanks

@wso2/is-doc-team - This needs to be documented somewhere under the admin services

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
