### ISSUE TITLE
Rotate the OAuth client credentials without revoking the previous client credentials

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#16152]
With the current implementation of the product when we rotate the OAuth client credentials it will revoke the previous client credentials. This will fail the client invocations with the old client credentials.  Since it will take some time to update the client applications with the newly rotated client credentials by application owners. Shall we take a step to improve the feature to rotate the OAuth client credentials without revoking the previous client credentials?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
