### ISSUE TITLE
Support Recaptcha Enterprise for IS

### ISSUE THREAD

**Issue by AwesomeNipun** [wso2/product-is#16164]
**Describe the issue:**

Currently, Identity Server uses the non-paid version of ReCaptcha (v2 and v3), but new requirements necessitate the addition of ReCaptcha Enterprise (paid version of ReCaptcha Enterprise v3) support.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
