### ISSUE TITLE
DB2 Script execution error - syntax error in <IS-HOME>/dbscripts/identity/db2.sql file.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16161]
**Describe the issue:**
The DB2 script (/dbscripts/identity/db2.sql) contains an SQL syntax error.

**Error ->**

```

Error occurred during SQL script execution

Reason:
SQL Error [42831]: The column named "REQ_URI_REF" cannot be a column of a primary key or unique key constraint because it can contain null values.. SQLCODE=-542, SQLSTATE=42831, DRIVER=4.26.14
```
<img width="1512" alt="Screenshot 2023-06-28 at 15 22 20" src="https://github.com/wso2/product-is/assets/41188245/85bf3b79-34be-49e5-9b32-6456f68d8af3">

**How to reproduce:**
Try to execute DB2 script file in <IS-HOME>/dbscripts/identity/db2.sql location.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment]
@ChitharaKarunasekera we need to fix the DB2 script changes added for supporting PAR.

Needs to change to: 
CREATE TABLE IDN_OAUTH_PAR (
    REQ_URI_REF VARCHAR(255) PRIMARY KEY NOT NULL,
    CLIENT_ID VARCHAR(255),
    SCHEDULED_EXPIRY BIGINT,
    PARAMETERS CLOB(1M)
)
/

**Comment by chamathns** [comment]
closing since fixed
