### ISSUE TITLE
Remove carbon registry dependency

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#16162]
Carbon registry dependencies need to be removed from the Identity Server to improve performance.

First unnecessary registry dependencies will be removed

### Related PRs
- https://github.com/wso2/carbon-identity-framework/pull/4758
- https://github.com/wso2-extensions/identity-user-account-association/pull/48
- https://github.com/wso2/identity-apps/pull/3962
- https://github.com/wso2-extensions/identity-data-publisher-authentication/pull/115
- https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/135
- https://github.com/wso2-extensions/identity-user-ws/pull/58
- https://github.com/wso2-extensions/identity-outbound-provisioning-salesforce/pull/30
- https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/163
- https://github.com/wso2-extensions/identity-carbon-auth-saml2/pull/96
- https://github.com/wso2-extensions/identity-governance/pull/721
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2111
- https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/400

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
