### ISSUE TITLE
Support backend error description localization for MyAccount

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#16173]
**Is your suggestion related to an experience ? Please describe.**
Errors returned from REST APIs can not be localized in My Account. As an example, if the password history feature is enabled and the user submits a password that's been used recently, the error notification will show the description returned in the `scim2/Me`. This error description displays in English (language returns from the API) regardless of the language selected in My Account.
 
![Screenshot from 2023-06-30 16-08-53](https://github.com/wso2/product-is/assets/22415272/0e4e210d-a5eb-4ba5-9c7a-f962339c846a)

**Describe the improvement**
Provide a way to capture the internal error messages and translate them into the language selected in the My Account app in a similar way supporting localizing internal error messages in the authentication endpoint [1].

[1] - https://is.docs.wso2.com/en/5.11.0/develop/localization-support-in-identity-server/#configuring-localization-for-authentication-endpoints

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
