### ISSUE TITLE
Azure static webapp with WS02 as custom identity provider - redirect from ws02 to staticwebapp does not work after the 

### ISSUE THREAD

**Issue by dzidzedev** [wso2/product-is#16189]
**Describe the issue:**
Hi,
I have deployed an Azure static web app using WS02 with OIDC as custom identity provider. Unfortunately the logout process won't redirect back to Azure static web app.

Does someone have any experience using Azure static webapp with WS02 

Kindly regards
JB

**Comment by dzidzedev** [comment]
Hi,

Is there any updates?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
