### ISSUE TITLE
SMS OTP based user authentication (first factor)

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#16186]
## Epic

Enable the new user authentication by using SMS OTP as the first factor.

## Description

> Many modern applications have the feature of registering and authenticating users by using OTP, as the first factor of authentication. It is important to include that feature in CIAM. This epic focuses on the addition of SMS OTP-based authentication feature.

Authentication flow

1. Open the Application to Login.
2. Enter the username of the user.
3. User is redirected to the OTP entering page.
4. An SMS with OTP will be sent.
5. User enters the OTP into the OTP entering page and clicks "Continue".
6. User will be logged in.

**Comment by SujanSanjula96** [comment]
PRs 
- https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/178
- https://github.com/wso2-extensions/identity-governance/pull/759
