### ISSUE TITLE
The identity claims are not set properly in the lite user registration flow.

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#16187]
**Describe the issue:**

When identity claims are added to the claims parameter in the lite user registration request, it does not get persisted properly. Even the claim isLiteUser is not properly set in the flow.

**How to reproduce:**

- Setup lite user registration according to the official documentation at [1].
- Execute the following cURL request where the preferredChannel identity claim is set.

```
curl --location --request POST 'https://localhost:9443/api/identity/user/v1.0/lite' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "email": "test@wso2.com",
    "realm": "PRIMARY",
    "claims": [
        {
            "uri" : "http://wso2.org/claims/mobile",
            "value" : "+94123456789"
        },
        {
            "uri" : "http://wso2.org/claims/identity/preferredChannel",
            "value" : "EMAIL"
        },
        {
            "uri" : "http://wso2.org/claims/emailaddress",
            "value" : "test@wso2.com"
        }
    ],
    "properties": []
}'
```
- After creating the user, inspect the claims lite user and the preferred channel in the user's profile. None of the values are populated even if they are marked as read only false. However, the mobile and email claims are saved as expected. A screenshot of the user profile is as follows:

![image](https://github.com/wso2/product-is/assets/33062368/c99775e3-531b-4bcb-9b5e-fa902fcf523e)

This seems to occurring, when the user is added to through the user store manager [2] and it is working without an issue in WSO2 IS 5.11.0. 

[1] - https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/lite-user-registration/
[2] - https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/signup/UserSelfRegistrationManager.java#L1744

**Expected behavior:**

The claims should be properly saved into the user's profile.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - OS: Ubuntu 20.04.3 LTS
 - Database: MySQL
 - Userstore: JDBC

---

**Comment by shashimalcse** [comment]
Based on my observation, it seems that all the claims persist in the database. This issue might be caused by a issue in retrieving user attributes for the user profile. @deshankoswatte , have you checked this at the database level?

**Comment by chamathns** [comment]
yep, the user claims should be stored in the DB level. A scim users call will return the following for the above created user.

```json
{
            "emails": [
                "test@wso2.com"
            ],
            "meta": {
                "location": "https://localhost:9443/scim2/Users/4a4fdedc-f3d0-4c96-aab4-13183f4639f2",
                "lastModified": "2023-07-13T03:09:41.175448Z",
                "resourceType": "User"
            },
            "roles": [
                {
                    "display": "everyone"
                }
            ],
            "id": "4a4fdedc-f3d0-4c96-aab4-13183f4639f2",
            "userName": "test@wso2.com",
            "title": "true",
            "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                "accountLocked": true,
                "accountState": "PENDING_LR",
                "lockedReason": "ADMIN_INITIATED",
                "preferredChannel": "EMAIL",
                "isLiteUser": true
            },
            "phoneNumbers": [
                {
                    "type": "mobile",
                    "value": "+94123456789"
                }
            ]
        }
```

**Comment by deshankoswatte** [comment]
There an inconsistency in saving identity related claims. When you call the `addUser()` as in [1] method it gets saved in the `UM_USER_ATTRIBUTE` table. However, when the `setUserClaimValues()` method is called it is saved in the `IDN_IDENTITY_USER_DATA` table. If we have not enabled the property to save data in the user store we should not be saving identity claims to the `UM_USER_ATTRIBUTE` table.

[1] - https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/signup/UserSelfRegistrationManager.java#L1748C38-L1748C38

**Comment by Wathsara** [comment]
Kindly note that this issue is not a regression, and the older behavior can be achieved by using the following configuration. Therefore, the regression label has been removed from the issue.

Configuration:
```
[event.default_listener.governance_identity_store]
enable_hybrid_data_store=true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
