### ISSUE TITLE
[Doc] No details on UserStoreConfigAdminService in the docs

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1618]
Type: Improvement
Priority: High
Severity: Major
Release: 5.4.0

For some admin services there are information like what each method does and details of the properties etc.

Eg: 
https://docs.wso2.com/display/IS530/User+Information+Recovery+Service

But there are no details documented for UserStoreConfigAdminService

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
