### ISSUE TITLE
[Query] What is the difference of execution of updateCredentialByAdmin() and updateCredential()

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1619]
As per the descriptions provided in [1] both the updateCredentialByAdmin() and updateCredential() are updating credentials of a given user. And AFAIK, both needs authentication when invoking these operations and with this users can be distinguished. Hence I have a question in why we need the updateCredentialByAdmin() seperatly. Is there any business use case as to why these two different operations are needed?

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-updateCredentialByAdmin()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
