### ISSUE TITLE
IS 6.2.0 - Installing as a Windows service not supporting JDK 17. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16199]
**Describe the issue:**
When trying to Install Product IS as a Windows Service with JAVA 17 the server won't be starting.
(P.S. -> Tested the flow with JDK 11 and working as expected.)

JDK Version - JDK 17

**How to reproduce:**

1. Download Yet Another Java Service Wrapper (YAJSW) [version 13.10 (latest)](https://sourceforge.net/projects/yajsw/)

2. Copy and paste the configurations from wrapper.conf file which is located inside {wso2is-5.10.0_Home}/bin/yajsw to wrapper.conf file in {yajsw-Home} /conf.

3. Add a new system variable by providing
Variable name : carbon_home
Variable value: C:\wso2is-5.10.0 (path to the extracted Identity Server)

4. Use the Windows command prompt and go to the bat folder inside {yajsw-Home}

5. Start the wrapper in console mode
    ` runConsole.bat`

### IS Docs Link -> [https://is.docs.wso2.com/en/latest/deploy/get-started/install/#install-as-a-windows-service](https://is.docs.wso2.com/en/latest/deploy/get-started/install/#install-as-a-windows-service)

**Expected behavior:**
User should able to access the wso2 Identity Server by using the url "[https://localhost:{port}/carbon](https://localhost:%7Bport%7D/carbon)"

**Actual Result:**
An error, when starting the wrapper in console mode using runConsole.bat (Installing as a Windows Service)

Error log - 

```
C:\Program Files\yajsw-stable-13.10\bat>runConsole.bat

C:\Program Files\yajsw-stable-13.10\bat>pushd C:\Program Files\yajsw-stable-13.10\bat\

C:\Program Files\yajsw-stable-13.10\bat>call setenv.bat
"C:\Program Files\Java\jdk-17\bin\java" -Xmx30m -Dwrapper_home="C:\Program Files\yajsw-stable-13.10\bat\/.." -Djna_tmpdir="C:\Program Files\yajsw-stable-13.10\bat\/../tmp" -Djava.net.preferIPv4Stack=true -jar "C:\Program Files\yajsw-stable-13.10\bat\/../wrapper.jar" -c "C:\Program Files\yajsw-stable-13.10\bat\/../conf/wrapper.conf"
YAJSW: yajsw-stable-13.10
OS   : Windows 10/10.0/amd64
JVM  : Oracle Corporation/17/C:\Program Files\Java\jdk-17/64
Looking in classpath from org.rzo.yajsw.boot.WrapperClassLoader@3f99bd52 for /com/sun/jna/win32-x86-64/jnidispatch.dll
Found library resource at jar:file:/C:/Program%20Files/yajsw-stable-13.10/./lib/core/jna/jna-5.12.1.jar!/com/sun/jna/win32-x86-64/jnidispatch.dll
Extracting library to C:\Program Files\yajsw-stable-13.10\bat\..\tmp\jna7729326233399578443.dll
Trying C:\Program Files\yajsw-stable-13.10\bat\..\tmp\jna7729326233399578443.dll
Found jnidispatch at C:\Program Files\yajsw-stable-13.10\bat\..\tmp\jna7729326233399578443.dll
wrapper.logfile.umask -1
initOutputFiles: -1
open umask -1
WARNING|wrapper|WSO2 Carbon|23-07-06 13:07:39|YAJSW: yajsw-stable-13.10
WARNING|wrapper|WSO2 Carbon|23-07-06 13:07:39|OS   : Windows 10/10.0/amd64
WARNING|wrapper|WSO2 Carbon|23-07-06 13:07:39|JVM  : Oracle Corporation/17/C:\Program Files\Java\jdk-17/64
system.env 55
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:40|started process with pid 9872
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:41|restart internal RUNNING controller killed restart handler
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:41|stopping process with pid/timeout 9872 45000
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:41|process exit code: 1
system.env 55
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:47|started process with pid 13380
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:47|restart internal RUNNING controller killed restart handler
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:47|stopping process with pid/timeout 13380 45000
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:47|process exit code: 1
system.env 55
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:53|started process with pid 9144
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:53|restart internal RUNNING controller killed restart handler
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:53|stopping process with pid/timeout 9144 45000
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:54|process exit code: 1
system.env 55
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:59|started process with pid 13104
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:59|restart internal RUNNING controller killed restart handler
INFO|wrapper|WSO2 Carbon|23-07-06 13:07:59|stopping process with pid/timeout 13104 45000
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:00|process exit code: 1
system.env 55
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:05|started process with pid 18664
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:05|restart internal RUNNING controller killed restart handler
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:05|stopping process with pid/timeout 18664 45000
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:06|process exit code: 1
system.env 55
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:11|started process with pid 4404
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:11|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:11|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-07-06 13:08:11|Shutting down Wrapper 
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.2.0 Alpha3
 - OS: Windows
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by RushanNanayakkara** [comment]
## Findings
This was tested using the following JDK versions for IS 6.2.0 Alpha 3 release. 

#### JDK version setup procedure followed.
- Set Java version for Identity Server : 
Hard code relevant JAVA_HOME value to the wso2server.bat file.
- Set Java version for YAJSW : 
Set JAVA_HOME value in the console (this is used by YAJSW  setenv.bat file)

### Results
- Server starts up as expected on JDK 17.0.8 in Windows environment.
- Results with the YAJSW
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-fd9a76e5-7fff-2081-47d0-3cd25d90bb96"><div dir="ltr" style="margin-left:0pt;" align="left">

YAJSW Java Version | IS Java Version | Result
-- | -- | --
JDK 17.0.8 | JDK 17.0.8 | Fail
JDK 17.0.8 | JDK 11.0.15 | Fail
JDK 11.0.15 | JDK 17.0.8 | Pass
JDK 11.0.15 | JDK 11.0.15 | Pass

</div><br /></b>

### Notable observations
- The failure is dependent on the Java version used by the YAJSW and not the IS. 

### Conclusion
- Cause of failure is a compatibility issue on the YAJSW and not the IS.

**Comment by RushanNanayakkara** [comment]
Closing due to the issue not being related to implementation of the Identity Server.
