### ISSUE TITLE
Moving operations tab from My Account to Console is not updated in documentation.

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16196]
**Is your suggestion related to a missing or misleading document? Please describe.**
From IS 6.0.0 onwards, the operations tab is moved from my account to console. As a result operations tab is not seen in my account as mentioned in https://is.docs.wso2.com/en/6.0.0/guides/workflows/manage-human-tasks/. Further, only admin users can see the operations tabs as they can log into console. Therefore, example mentioned in https://is.docs.wso2.com/en/6.0.0/guides/workflows/add-a-new-workflow-definition/#add-a-new-workflow-definition should be updated accordingly. (A non admin user with Manager role will not be able to do approvals)

**Describe the improvement**
Update the IS 6.0.0 document to address the above change. 

**Additional context**

Further, currently workflow management IS documents are not fount in the navigation (after IS 6.0.0) but available in the doc space. Documents should be added to the navigation menu.  

Documentation for workflow operations. 

https://is.docs.wso2.com/en/6.0.0/guides/workflows/add-a-new-workflow-definition/  
https://is.docs.wso2.com/en/6.0.0/guides/workflows/engage-a-workflow-in-an-operation/ 
https://is.docs.wso2.com/en/6.0.0/guides/workflows/manage-human-tasks/ 
https://is.docs.wso2.com/en/6.0.0/guides/workflows/monitor-workflow-requests/

**Comment by divyaamunugama** [comment]
This option can only be found on the console app, as we have not documented the console app yet we need to decide on what should be done. 

Concerns:
- Won't we have the `Approvals` option in the management console?
- It's not nice to document the console app just here, as it's not documented anywhere in the public doc space.
