### ISSUE TITLE
User stores will be created without some mandatory properties via admin services

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1620]
Type: Bug
Priority: High
Severity: Major
Release: 5.4.0

Send a request as in the screen shot (without mandatory properties) to create a new store using the UserStoreConfigAdminService. 
![10](https://user-images.githubusercontent.com/1845370/34041951-758c1fee-e1c0-11e7-98e2-85a9a579d430.png)

**Issue**
The response does not have any errors, so the user might think the store has been successfully created. When you try creating the same user store again with the same domain name, it will say the user store already exists. But, the user store is not successfully created. 

Ideally mandatory parameters should be checked and an error should be returned to the user.

**Comment by danijelt** [comment]
Are there plans to fix this? It's still present in 5.10.0. I found that you can fix it (add the same domain again) by removing the xml file in repository/deployment/server/userstores.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
