### ISSUE TITLE
Need to log when multiple users are found for given claims in username recovery

### ISSUE THREAD

**Issue by pabasara-mahindapala** [wso2/product-is#16208]
**Describe the issue:**
When multiple users are found for the claims given in the username recovery flow, there should be a way to recognise it easily. If the following config is not added to the deployment.toml file, the error message is not shown to the end user. Unless debug logs are enabled, it will not be logged in wso2carbon logs as well.

```
[identity_mgt.recovery]
notify_user_existence = true
```

**How to reproduce:**
1. Enable username recovery in IS
2. Add two users with the same values for firstname and lastname
3. Try the username recovery providing firstname and lastname

**Expected behavior:**
A WARN log should be printed indicating that multiple users are found for the claims given in the triggered username recovery flow.

**Environment information:**
 - Product Version: IS 6.1.0.43
 - Database: H2
 - Userstore: H2

**Comment by lashinijay** [comment]
Closing this issue as the public fix is merged.
