### ISSUE TITLE
IWA NTLM Connector is not compatible with later IS Versions

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16204]
**Describe the issue:**
When configuring the IWA NTLM authentication with latest IS versions, we have come across multiple issues.

1. Enabling the iwa_ui_authenticator for carbon console authentication, will cause startup errors due to incompatibility of waffle-jna jar with latest IS versions [3]. The default waffle-jna jar is compatible with IS 5.3.0. Startup errors thrown for IS 5.11.0.
2. The jar obtained by building the master branch of the ntlm connector [2] is not compatible with the later IS versions (works for 5.3.0).  The following OSGI error is thrown since both org.wso2.carbon.identity.application.authenticator.iwa.ntlm.internal.IWAAuthenticatorServiceComponent and org.wso2.carbon.identity.application.authenticator.basicauth.internal.BasicAuthenticatorServiceComponent have same OSGI component name identity.application.authenticator.basicauth.component.
```
Found components with duplicated names
```
3. The connector will not be available in the local authenticator list without bumping the framework version of the connector.
4. Application authentication fails - Connector is incompatible with later IS versions (tested and authorization fails for 5.11.0 and 6.2.0-alpha versions) but sso works without any issue for IS 5.3.0. 401 error response is received when accessing the iwa-ntlm endpoint - can be fixed by explicitly allowing access to the "/iwa-ntlm" context by adding the following line to the <IS-HOME>/repository/conf/identity/identity.xml file.
```
<ResourceAccessControl default-access="deny">
        <Resource context="(.*)/iwa-ntlm(.*)" secured="false" http-method="all"/>
...
</ResourceAccessControl>
```
This should be either added to the identity.xml.j2 by default or properly documented.

**How to reproduce:**
Enabling the carbon UI authenticator:
1. Follow the instructions at [1].

Adding the ntlm connector for application authentication:
1. Build the ntlm connector from [2] repo.
2. Add the jar to the dropins folder.
3. The iwa-ntlm connector should be available as local authenticators.

**Expected behavior:**
**IWA NTLM as an application authenticator:**
- After adding the NTLM jar to the dropins folder, it will be available as a local authenticator with the name `iwa-ntlm`.
- When adding that as a local authenticator to a SP and try out the login flow, the user will be logged in without prompting for any credentials with the following backend log
```
[2023-07-07 06:55:17,228]  INFO {org.wso2.carbon.identity.application.authenticator.iwa.ntlm.servlet.IWAServlet} -  Successfully logged in user: <windows-username>
```

**IWA NTLM as the admin console authenticator:**
- As instructed at [1], adding the deployment.toml configs will enable the iwa_ui_authenticator.
- When accessing the management console, the user will be first authenticated by IWA and then prompted with the carbon login page.

[1] https://is.docs.wso2.com/en/5.11.0/learn/configuring-iwa-single-sign-on/
[2] https://github.com/wso2-extensions/identity-local-auth-iwa-ntlm
[3] https://github.com/wso2/product-is/issues/7718

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
