### ISSUE TITLE
Adding missing SAN element in the certificate to resolve federated authentication flow failure

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16215]
**Is your suggestion related to a missing or misleading document? Please describe.**
As reported in https://github.com/wso2/product-is/issues/16181, Federated authentication fails between two tenants in a host name changed IS. This is due to that if the certificate used for SSL communication has a cert, the hostname is checked in the defined SANs and newly defined hostname is not added into the SAN. 

If the `is.dev.wso2.com` also added as a SAN issue gets resolved.  Hence the document should be changed to add the `is.dev.wso2.com`also  as a SAN in,

``` Add localhost as SAN for the certificate (-ext SAN=dns:localhost) as the internal hostname is by default localhost. For that, navigate to the <IS_HOME>/repository/resources/security directory on the command prompt and use the following command to create a new keystore with CN=is.dev.wso2.com and localhost as SAN```

**Describe the improvement**
In https://is.docs.wso2.com/en/latest/deploy/change-the-hostname/#change-the-hostname options 1, the given command should be changed to add the `is.dev.wso2.com` as a SAN as below.

> keytool -genkey -alias <alias_name> -keyalg RSA -keysize 2048 -keystore <keystore_name>.jks -dname "CN=<hostname>, OU=<organizational_unit>,O=<organization>,L=<Locality>,S=<State/province>,C=<country_code>" -storepass <keystore_password> -keypass <confirm_keystore_password> -ext SAN=dns:localhost,dns:is.dev.wso2.com 

**Related Issues:**
https://github.com/wso2/product-is/issues/16181

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
