### ISSUE TITLE
XACML policy is not applied for a service provider created via tenant.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1621]
XACML policy is not applied for a service provider created via tenant.

1. Create a tenant. ushani.com
2. Download public key and import it in to wso2carbon.jks in travelocity side.
3. Configure travelocity.properties for a tenant. 
   - keytool -import -alias <key_alias> -file <download_file> -keystore wso2carbon.jks 
   - QueryParams=tenantDomain=tenant.domain
   - IdPPublicCertAlias=<alias>
4. Create a sp as travelocity.com
5. Create 2 roles. sales and finance and users belong to them. (sales -user1, finance - user2)
6. Restart the tomcat.
7 .Create a policy as below.

Allow travelocity.com sp and users belong to sales role and deny others

```
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" PolicyId="rolepolicySP11" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
   <Target>
      <AnyOf>
         <AllOf>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">travelocity.com</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/identity/sp/sp-name" Category="http://wso2.org/identity/sp" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
            </Match>
         </AllOf>
      </AnyOf>
   </Target>
   <Rule Effect="Permit" RuleId="permit">
      <Target>
         <AnyOf>
            <AllOf>
               <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                  <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">sales</AttributeValue>
                  <AttributeDesignator AttributeId="http://wso2.org/claims/role" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
               </Match>
            </AllOf>
         </AnyOf>
      </Target>
   </Rule>
   <Rule Effect="Deny" RuleId="denyothers"/>
</Policy>
```        

Users from any role can login. It should not allow to users belong to other roles.

![screenshot from 2017-12-15 18-07-11](https://user-images.githubusercontent.com/12966170/34042465-d74527ce-e1c2-11e7-8bc6-421459e834ec.png)

**Comment by darshanasbg** [comment]
@ushanib 
1. Have you enabled rule base authorization to travelocity sp?
2. Have you published the policy to PDP?

Thanks

**Comment by ashensw** [comment]
This cannot be reproduce in the IS 5.8.0-alpha5 pack. XACML policy is correctly applied in the tenant as well.
