### ISSUE TITLE
ReCaptcha fails to load due to invalid key error

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#16229]
**Describe the issue:**

After updating the product the captcha is not displayed correctly during login.

With update 221 the way the `g-recaptcha` object is rendered changed from:
```
if (reCaptchaEnabled) {
    String reCaptchaKey = CaptchaUtil.reCaptchaSiteKey();
...
    <div class="g-recaptcha"
        data-sitekey="<%=Encode.forHtmlContent(reCaptchaKey)%>"
    </div>
...
```
to:
```
if (reCaptchaEnabled) {
...
    <div class="g-recaptcha"
        data-sitekey="<%=Encode.forHtmlContent(request.getParameter("reCaptchaKey"))%>">
    </div>
...
```

Since the `reCaptchaKey` parameter is not present on the query string it takes a null value causing the mentioned error.

If the described change was intended, the `recaptcha.parameters_in_url_enabled` property should be set to `true` by default in the `default.json` file, so the `reCaptchaKey` will be sent by default. Otherwise the change should be reverted to continue getting the `reCaptchaKey` form the configuration files instead of from the query parameters.

**How to reproduce:**
1. Install a vanilla version of IS-5.10.0.
2. Set up ReCaptcha following the steps at [1].
3. Enable Captcha for SSO Login following the steps at [2].
4. Login to the user-portal application [3]. At this point the captcha should be rendered properly.
5. Update the server to U2 update level 221 or above.
6. Login to the user-portal application [3]. At this point the captcha fails to load due to an invalid key error.

**Expected behavior:**

ReCaptcha features should continue working seamless after updating the product.

**Environment information:**
 - Product Version: IS-5.10.0

---

[1] https://is.docs.wso2.com/en/5.10.0/learn/setting-up-recaptcha/
[2] https://is.docs.wso2.com/en/5.10.0/learn/configuring-recaptcha-for-single-sign-on/
[3] https://localhost:9443/user-portal

**Comment by ImalshaG** [comment]
Closing this issue since the fix is released.
