### ISSUE TITLE
Tenant domain is not validated in the password recovery flow

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#16228]
**Describe the issue:**
In the UI based password recovery flow, tenant domain is getting removed without validating when resolving the user. This cause inconsistent behaviors when in the password recovery flow.

When the user submit the username, an User object is getting created using `IdentityManagementServiceUtil.resolveUser` method by passing username provided by user, tenantDomain and isSaaSApp variable [1].

In the resolveUser method, tenantAwareUsername will be resolve by removing user store domain and removing the tenant domain [2].

As an example, if the user provides user input as `john@gmail.com`, this method will return the username as `john`.

If there are no users available in the IS with the username `john`, username recovery flow will fail. However, if there is a user available with the username `john`, an email will triggered to the user's email.

This cause inconsitencies in the password recovery flow.

i.e. Users will observe password recovery email is receiving to some emails (if the username and identifer part of the email is same) and not to others.

This inconsistency can be observed in the UI if the user existence is enabled.
```
[identity_mgt.recovery]
notify_user_existence = true
notify_recovery_email_existence = true
```

**How to reproduce:**
1. Configure SMTP conifiguration and enable password recovery from the resident identity provider.
2. Create a user named `john` and add a working email ('john@gmail.com').
3. Create a service provider and go to the login page.
4. Trigger password recovery flow and provide username as `john@wso2.com` (domain is different from the actual email address but it will work if provided the same email address `john@gmail.com` as well).
5. User will receive an email with password recovery link when there is no user with email address of `john@wso2.com` or tenant domain as `wso2.com`.
6. Same flow will break in the middle if the identifier part of the email address is different from the username (username -> `jane`, email -> `janesmith@gmail.com`)

**Expected behavior:**
Password recovery flow should validate the tenant domain when resolving the user.

**Environment information:**
 - Product Version: IS 6.1.0, 5.11.0

---

[1] - https://github.com/wso2/identity-apps/blob/7118200d6044efbfc4d3a0a670a87c221e24b2e4/apps/recovery-portal/src/main/webapp/password-recovery-notify.jsp#L47
[2] - https://github.com/wso2/carbon-identity-framework/blob/137f4a4e2c3ca23a732950e98029a8340a0d0632/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementServiceUtil.java#L261-L262

**Comment by rksk** [comment]
The same issue exists in the self signup flow as well. It omits the part after `@` and register the user when email username is not enabled. Best to test that flow too once fixed.

**Comment by rksk** [comment]
Suggested solution

```
-        if (isSaaSEnabled) {
+        if (isSaaSEnabled || !"carbon.super".equals(MultitenantUtils.getTenantDomain(username))) {
             user.setTenantDomain(MultitenantUtils.getTenantDomain(username));
         } else {
             user.setTenantDomain(tenantDomain);

```

https://github.com/wso2/carbon-identity-framework/blob/137f4a4e2c3ca23a732950e98029a8340a0d0632/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementServiceUtil.java#L263

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/4858
