### ISSUE TITLE
"Support Calls" does load super slow....and throws "infrastructure failed" error

### ISSUE THREAD

**Issue by brueggmann** [wso2/product-is#16224]
Since July 10th, around 1:00pm Berlin time i experienced a super slow section "support calls". I was showing the Sightcall-Empolis Integration to a prospect. As i know that the transmission of media material from a sight-call into Empolis may take a minute or two i prepared for the demo an hour before. I sent media material upfront to have something on the Empolis side in the "Support Calls" section to work with and convert it into a knowledge article. But i wasn't able to open these previous calls and work with the material due to "infrastructure failure". After 3-4 hours all the material was finally available in Empolis and i could finish the work without showing it to the prospect ... so nothing was lost or misconfigured obviously.

this is the support call i was demoing on (using th eolder account from a colleague, Jan Dreier, because my own account stopped working for some reason):

https://esc-eu-central-1.empolisservices.com/service-knowledge/app/#/external-content/remote-support/c620f80ceb669d9e/view/metadata

It was and is until now still super slow. Can't show this to prospects this way. Can you please check what is going on there. Kind regards, Matthias (from Sightcall) matthias.brueggmann@sightcall.com   
![image](https://github.com/wso2/product-is/assets/139210108/80c26b27-1edb-4bf1-b5ef-16881fb50a1b)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
