### ISSUE TITLE
XACML policy in Super tenant is not applied when SP is saas enabled in tenant

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1622]
XACML policy is not applied for a service provider created via tenant.

1.Create a tenant. ushani.com and login to tenant ushani.com
2.Download public key and import it in to wso2carbon.jks in travelocity side.
3.Configure travelocity.properties for a tenant.
keytool -import -alias <key_alias> -file <download_file> -keystore wso2carbon.jks
QueryParams=tenantDomain=tenant.domain
IdPPublicCertAlias=
4. Create a sp as travelocity.com and enable Saas
5. Logout from tenant and Login to Super tenant Create 2 roles. sales and finance and users belong to them. (sales -user1, finance - user2)
Restart the tomcat.
7 .Create a policy as below in Super tenant to allow the users belong to finance role only

![screenshot from 2017-12-15 18-38-36](https://user-images.githubusercontent.com/12966170/34043449-305825c4-e1c7-11e7-9df7-8fcd457e0547.png)

```
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" PolicyId="rolebasedplicy" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
   <Target>
      <AnyOf>
         <AllOf>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">travelocity.com</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/identity/sp/sp-name" Category="http://wso2.org/identity/sp" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
            </Match>
         </AllOf>
      </AnyOf>
   </Target>
   <Rule Effect="Permit" RuleId="permit">
      <Target>
         <AnyOf>
            <AllOf>
               <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                  <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">finance</AttributeValue>
                  <AttributeDesignator AttributeId="http://wso2.org/claims/role" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
               </Match>
            </AllOf>
         </AnyOf>
      </Target>
   </Rule>
   <Rule Effect="Deny" RuleId="denyothers"/>
</Policy>   
```     

Login via sales role user in super tenant. User should not be able to login since the policy in Super tenant should be applied. 
But all the users can login.

**Comment by madurangasiriwardena** [comment]
Relates to https://github.com/wso2/product-is/issues/1621

**Comment by ashensw** [comment]
The policy also should be published in the same tenant where the service provider exists. Hence this is not a valid scenario.
