### ISSUE TITLE
Java 21 support for WSO2 Identity Server

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#16230]
**Is your feature request related to a problem? Please describe.**
The upcoming LTS release of Java; Java 21 is scheduled for release on September 2023. As Identity Server is a downloadable product which will be used years after its releases, its important to plan for the latest LTS support for a upcoming release proactively.

**Describe the solution you would prefer**
Product should be able to run on the Java 21.

**Additional context**
Java 17 support added with https://github.com/wso2/product-is/issues/13463

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
