### ISSUE TITLE
The correct users are not listed when creating a group with a secondary user store.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16239]
**Describe the issue:**
When the user tries to create a new group with a secondary user store selected as the User store, The. correct Users are not listed in the `Assign Users` user list.
**Even though we can complete this flow with a JDBC user store without assigning any users to the group, This seems to be a blocker when trying with LDAP**. 

![Screenshot 2023-07-12 at 17 58 36](https://github.com/wso2/product-is/assets/41188245/7ffdf9dc-0d25-4d5d-a3b4-273ddc19d21f)

![Screenshot 2023-07-12 at 17 57 43](https://github.com/wso2/product-is/assets/41188245/c2b38155-7ced-4cfc-8fd3-192235cadff1)

**How to reproduce:**

1. Configure a secondary userstore using the management console. ([Doc](https://is.docs.wso2.com/en/latest/deploy/configure-secondary-user-stores/))
2. Log in to the console app 
3. Create a new group 
4. You can see that under `Assign users` the correct users are not listed but the Primary users

And if we try to select one from the listed users, we will get an error as expected because the cross-userstores user assigning is not supported.

https://github.com/wso2/product-is/assets/41188245/b8c4d60c-0784-47b0-9b83-0b3412da74d1

**Expected behavior:**
The relevant secondary users should be listed 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS 6.2.0 Alpha3
- OS: Windows
- Database: H2
- Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment]
This is a UI issue in the console level. The backend APIs retrieve the users of userstores,accurately. Furthermore, if you skip adding the users in the group creation modal, and later add the users from the manage menu, it would list the users correctly.
