### ISSUE TITLE
Username validation in the self signup flow

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16235]
**Describe the issue:**
When email as username is disabled and if the user tries to use an email address as the username during the self signup flow, it shows an error message saying invalid tenant domain. (The error will be shown only for SaaS service providers until https://github.com/wso2/product-is/issues/16228 is fixed)

**How to reproduce:**
- Start IS and enable self signup
- Open MyAccount and click `Create Account` on the login page
- Fill the username field with an email address and continue
- You will get an error saying invalid tenant domain

**Expected behavior:**
It should a clear message on this username pattern is not accepted. (The message can be read from `UsernameJavaRegExViolationErrorMsg` of userstore config.

**Environment information**
 - Product Version: IS 5.11.0

**Related issues:**
https://github.com/wso2/product-is/issues/16228

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
