### ISSUE TITLE
Multi attribute login is not working with magic link authenticator as first factor 

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#16242]
### Describe the issue:
Multi attribute login is not working as expected when magic link authenticator as the first factor

### How to reproduce:
1. Enable multi attribute login and define set of attributes as the login identifiers (add the mobile attribute as login identifier).
2. Create an application.
3. Set the magic link authenticator as the first factor.
4. Create an user and update the profile with mobile number.
5. Try to login to the application with the user.
6. Enter the mobile number as the user identifier.
7. Didn't receive any link to the email.

[Untitled_ Jul 13 2023 11_00 AM.webm](https://github.com/wso2/product-is/assets/36092400/88ff64d4-ca86-46e3-9659-62a3b51d2793)

### Expected behavior:
 T he link should be sent to the email address of the user.

### Environment information
 - Product Version: [IS 6.1.0]
 - OS: [Linux]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
