### ISSUE TITLE
Redundant select statements are getting executed in refresh grant flow

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-is#1624]
Following select statement is getting executed in refresh grant flow twice. This is the most time consuming query when you have large number of access tokens in DB.

SELECT ACCESS_TOKEN, AUTHZ_USER, ACCESS_TOKEN_SELECTED.TENANT_ID, USER_DOMAIN, TOKEN_SCOPE, 
TOKEN_STATE, REFRESH_TOKEN_TIME_CREATED, REFRESH_TOKEN_VALIDITY_PERIOD, ACCESS_TOKEN_SELECTED.TOKEN_ID, 
GRANT_TYPE, SUBJECT_IDENTIFIER FROM (SELECT TOP 1 ACCESS_TOKEN, AUTHZ_USER, TENANT_ID, USER_DOMAIN, 
TOKEN_STATE, REFRESH_TOKEN_TIME_CREATED, REFRESH_TOKEN_VALIDITY_PERIOD, TOKEN_ID, GRANT_TYPE, 
SUBJECT_IDENTIFIER FROM IDN_OAUTH2_ACCESS_TOKEN WHERE CONSUMER_KEY_ID = (SELECT ID FROM IDN_OAUTH_CONSUMER_APPS 
WHERE CONSUMER_KEY = 'xxxxx') AND REFRESH_TOKEN = 'yyyyy' 
ORDER BY TIME_CREATED DESC) ACCESS_TOKEN_SELECTED LEFT JOIN IDN_OAUTH2_ACCESS_TOKEN_SCOPE ON 
ACCESS_TOKEN_SELECTED.TOKEN_ID = IDN_OAUTH2_ACCESS_TOKEN_SCOPE.TOKEN_ID

Refer following commit which includes fix for that as well.

[1] https://github.com/dinusha-dilrukshi/identity-inbound-auth-oauth/commit/2db665b73e43f3588d2c40d3d58614abe06468d5

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
