### ISSUE TITLE
IWA NTLM Connector erroneous behaviour after configuring it as multi login option. 

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#16246]
**Describe the issue:**

When configuring an application with multi option login with iwa-ntlm connector and another authenticator, after choosing the IWA option it gets redirected to the commonauth endpoint with the parameter authenticator= IWAAuthenticator as follows

`https://localhost:9443/commonauth?idp=LOCAL&authenticator=IWAAuthenticator&sessionDataKey= ...`

But the authenticator name should be IwaNTLMAuthenticator instead of IWAAuthenticator as it has  defined the authenticator name at [1] in the login.jsp file as IWAAuthenticator instead of using the variable IWA_AUTHENTICATOR

[1] (https://github.com/wso2/identity-apps/blob/d50f388ed93857f8ef02bb01c1d2c1043920fe6a/java/apps/authentication-portal/src/main/webapp/login.jsp#L497)

**Related issues:**
[https://github.com/wso2/product-is/issues/16204](https://github.com/wso2/product-is/issues/16204)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-5.11.0
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

**Comment by UdeshAthukorala** [comment]
This will be fixed with the PR: https://github.com/wso2/identity-apps/pull/9509
