### ISSUE TITLE
Removing localhost from SAN in keystore generation command

### ISSUE THREAD

**Issue by LakshiAthapaththu** [wso2/product-is#16255]
**Is your suggestion related to a missing or misleading document? Please describe.**

As described in https://github.com/wso2/product-is/issues/16181, it is not required to have `localhost` as a SAN even in the flows which use internal hostname as `localhost` (eg: self registration).

But currently after removing the `localhost` from SAN self registration flow fails. This is due to a bug in the product and there is a effort to resolve in https://github.com/wso2/carbon-kernel/pull/3610 and https://github.com/wso2/carbon-identity-framework/pull/4794. **After fixing that issue** document should updated to have the `localhost` excluded SAN.

**Describe the improvement**

In https://is.docs.wso2.com/en/latest/deploy/change-the-hostname/#change-the-hostname options 1, the given command should not contain `localhost` as a SAN.

`keytool -genkey -alias <alias_name> -keyalg RSA -keysize 2048 -keystore <keystore_name>.jks -dname "CN=, OU=<organizational_unit>,O=,L=,S=<State/province>,C=<country_code>" -storepass <keystore_password> -keypass <confirm_keystore_password> -ext SAN=dns:localhost`

Should be updated as:
`keytool -genkey -alias <alias_name> -keyalg RSA -keysize 2048 -keystore <keystore_name>.jks -dname "CN=, OU=<organizational_unit>,O=,L=,S=<State/province>,C=<country_code>" -storepass <keystore_password> -keypass <confirm_keystore_password>`

**Related Issues:**

https://github.com/wso2/product-is/issues/16181

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
