### ISSUE TITLE
(Improvements) Externalize authentication endpoint

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-is#16253]
Related issue: https://github.com/wso2/product-is/issues/15714

As per the above issue:
"The official doc on hosting both Authentication and Recovery Endpoint on a Different Server is outdated. Need to be updated them. Also we need to update the 6.0 and 6.1 official documentations as well. Please refer (contains only for authentication portal): https://imalsha-sg.medium.com/externally-hosting-wso2-identity-server-portals-36330e00d456"

The above fix was done through PR [1]. However, the following improvement was noted:

"IS keystore location and tomcat keystore locations can be different - meaning two devices. Pointing tomcat's kestore as IS works fine if both deployed in same device. But if not, that given path is not an existing path. It make sense and we give the IS kestore location for the sake of simplicity. However, it feels that somehow the tomcat kestore should point to the IS kestore location."

[1] https://github.com/wso2/docs-is/pull/3704/files

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
