### ISSUE TITLE
Self registration confirm account link in a tenant does not confirm account and results in blank page

### ISSUE THREAD

**Issue by cuc2017** [wso2/product-is#1626]
In wso2is 5.4.0, enabling self registration in a tenant results in a blank page when the confirm account link is clicked in the email, the account is also not confirmed. See below for the page. This works fine for self registration in carbon.super but not in a tenant. This was working fine for us in wso2is 5.3.0.

This is the link in the email:
https://localhost:9443/accountrecoveryendpoint/confirmregistration.do?confirmation=0881dd36-5b05-49ba-b6c3-2b85da404fae&userstoredomain=PRIMARY&username=rob&tenantdomain=tenant1.com&callback=https%3A%2F%2Flocalhost%3A9443%2Fauthenticationendpoint%2Flogin.do%3Fclient_id%3DZGWkkPyp0mKdxAad0n_Kr85hYTca%26commonAuthCallerPath%3D%252Foauth2%252Fauthorize%26forceAuth%3Dfalse%26passiveAuth%3Dfalse%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%252Flogin%26response_type%3Dcode%26scope%3Dopenid%26state%3DxMptF4%26tenantDomain%3Dtenant1.com%26sessionDataKey%3Df4add7f2-2e12-425c-8f16-811aa5da6fc0%26relyingParty%3DZGWkkPyp0mKdxAad0n_Kr85hYTca%26type%3Doidc%26sp%3DApp1%26isSaaSApp%3Dfalse%26authenticators%3DBasicAuthenticator%3ALOCAL

![confirmaccount](https://user-images.githubusercontent.com/29401841/34059446-16276c60-e1ad-11e7-9bdc-44410ef6287f.png)

**Comment by DMHP** [comment]
This issue can not be reproduced in the master. Hence resolving the above issue.
