### ISSUE TITLE
When the challenge question string in the userstore does not match challenge question in the question set, the /myaccount/security breaks.

### ISSUE THREAD

**Issue by DumbravaRobert** [wso2/product-is#16267]
**Describe the issue:**
When the challenge question string saved in the user’s record does not match challenge question in the question set, the /myaccount/security breaks.
**How to reproduce:**

1.	The user has this attribute and value combination in the userstore: 
firstChallenge: Fathers middle name ?!YDA64iuZiGG847KPM+7BvnWKITyGyTwHbb6fVYwRx1I=

2.	Login with the user to My Account, go to the Security section. Notice the Challenge questions. The Security section works.
![image](https://github.com/wso2/product-is/assets/33093846/3147c730-16db-4ced-9ccf-616e021bbe6b)

 
3.	As an administrator, go to “Challenge Questions” in the Management Console and modify question2, adding some characters in the question.
 
![image](https://github.com/wso2/product-is/assets/33093846/4a3ac553-ae17-4660-a8cd-d8b88421f7ac)

4.	In My Account of the user click to Personal Info then to Security to refresh, or re-login and go to Security
![image](https://github.com/wso2/product-is/assets/33093846/96354496-e409-48b8-bb9c-2453c3d7afd9)

 
5.	Click “Refresh the page” and be prepared with the print screen button, to catch the split-second moment when something is displayed.
 
![image](https://github.com/wso2/product-is/assets/33093846/4232b037-09a5-4f96-b147-eb06012f3787)

**Expected behavior:**
 My Account should not compare the Challenge question string saved in the Userstore with the strings from the Challenge questions set. The question + hashed answer in the Userstore are used for password recovery so they are valid even if they might be outdated.
/myaccount/security should not crash, even if the challenge questions in the Challenge Questions Management did change in the meantime. If the user wants to modify something, the user should be able to select only from the valid questions from the set. 
**Environment information** **:**
- Product Version: [IS 6.0.0, IS 5.11.0]
- OS: Linux
- Database: PostgreSQL
- Userstore: openLDAP
 
---
 
**Related issues:**
 https://github.com/wso2/product-is/issues/11123
We found this to be just a particular case of the string mismatch problem, the space at the end is just an extra character. If also the user has this ending space in the attribute value, there is a string match and the /myaccount/security works.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
