### ISSUE TITLE
[Migration Docs] Add migration docs regarding the behavioral change of JIT provisioned users attribute sync process

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#16278]
**Is your suggestion related to a missing or misleading document? Please describe.**

Add migration docs regarding the behavioral change of JIT provisioned users attribute sync process from 5.11.0 to 6.0.0.

**Describe the improvement**

In Identity Server 5.11.0, It is keeping the claims of the JIT provisioned user after provisioning and not deleting the existing user claims that are not coming in the federated login after the provisioning. 

In Identity Server 6.0.0, this behavior has been changed. The JIT provisioned users attribute sync process was changed to delete the existing claim mappings which are not present in the IDP claim mapping. So this deletes the existing local claims that are not coming in the federated login after the provisioning. This is now the default behavior. 

If the previous behavior is required(To preserve locally added claims of JIT provisioned users ), add the following configuration to the deployment.toml file.

```
[authentication.jit_provisioning]
preserve_locally_added_claims = true
```

**Note:**
This configuration is available in IS 6.0.0 product from the update level 6.0.0.92
This configuration is available in IS 6.1.0 product from the update level 6.1.0.44
This configuration also available in the master branch too.

**Related Issues:**
- https://github.com/wso2/product-is/issues/16133

**Comment by UdeshAthukorala** [comment]
Related Docs PR for Migration Docs: https://github.com/wso2-enterprise/migration-docs/pull/144

**Comment by UdeshAthukorala** [comment]
Closing since this was added to the migration docs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
