### ISSUE TITLE
[XACML]Response code is not correct for invalid credentials on publishToPDP

### ISSUE THREAD

**Issue by chaminda** [wso2/product-is#1627]
Steps To Recreate:
1. Invoke the publishToPDP operation of the EntitlementPolicyAdminService[1] with invalid credentials(Authorization headers)
[1] https://localhost:9443/services/EntitlementPolicyAdminService

Actual Result:
The response message is returned with 500(Internal Server Error) HTTP response code.

Expected Result:
Correct HTTP response code(401) should be returned when credentials are not correct.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
