### ISSUE TITLE
Lite user registration process contains parameters that are not utilized in the source code

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#16275]
Description :

The lite user registration documentation at [1] and [2] contains parameters such as preferedChannel and mobile but they seem to be not used at all. This creates confusion in users. We should either properly use them.

[1] - https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/lite-user-registration/

**Describe the improvement**

- Try lite user registration with the following payload.

```
{
    "email": "test@wso2.com",
    "mobile": "+94123456789",
    "realm": "PRIMARY",
    "preferredChannel": "Email",
    "claims": [],
    "properties": []
}
```
The mobile claim and the preferred channel is not saved to the user because we drop them in the source code. We need to utilize those parameters properly to fix this issue.

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-extensions/identity-governance/pull/755
