### ISSUE TITLE
[Docs] Add docs regarding the configurations to preserve locally added claims of JIT provisioned users.

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#16281]
**Is your suggestion related to a missing or misleading document? Please describe.**

We have introduce a new configuration from WSO2 IS 6.0.0 onwards to  preserve locally added claims of JIT provisioned users. Need to add documentations regrading this config.

**Describe the improvement**

Identity server deletes the existing local claims of JIT provisioned users that are not coming in the federated login after the provisioning. 

You can change this default behavior to keep locally added claims of JIT provisioned users by  avoiding deleting the attributes that are not coming in the federated login after the provisioning.

To preserve locally added claims of JIT provisioned users, add the following configuration in the deployment.toml file.

```
[authentication.jit_provisioning]
preserve_locally_added_claims = true
```

**Note:**
This configuration is available in IS 6.0.0 product from the update level 6.0.0.92
This configuration is available in IS 6.1.0 product from the update level 6.1.0.44
This configuration also available in the master branch too.

**Related Issues:**
- https://github.com/wso2/product-is/issues/16133
- https://github.com/wso2/product-is/issues/16100

**Comment by UdeshAthukorala** [comment]
Docs PR for IS 6.0 & 6.10: https://github.com/wso2/docs-is/pull/4652

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
