### ISSUE TITLE
Super Admin permissions are not listed in the Permission Tree of the Cluster setup

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1628]
**Environment**
IS 5.4.0 Cluster setup (2 nodes) fronted by nginx
JDK - 1.8.0_45
DB - Mysql 5.6
Email as user enabled

**Steps to recreate the issue**
1. Create a role
2. Assign permission to the created role

**Observations**
'Super admin permission' is not listed on the permission tree
![cluster_permission](https://user-images.githubusercontent.com/14962228/34090038-3ddacc8c-e3da-11e7-8171-9ead03ca73e4.png)

Only 'admin' permission is available in the "/_system/governance/permission" path
![screenshot from 2017-12-18 10-00-30](https://user-images.githubusercontent.com/14962228/34090055-4ea6b3f0-e3da-11e7-9f1e-0cb12444fe06.png)

**Expected Behaviour**
Super admin permissions should be visible with the permission tree

**Note** - This behaviour only observed in the cluster setup. (Registry mounted and the carbon DB configured in H2)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
