### ISSUE TITLE
Update connection certification is failed

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#16289]
**Describe the issue:**
Update connection certification is failed. Once click the update button page get reload.

**How To Reproduce:**
1. login to the console
2. Navigate to Identity Providers -> Add a standard based IDP 
3. Edit the jwks endpoint 
4. Not able to update it.

**Expected behavior:**
User should be able to update the relevant endpoint successfully.

**Comment by melanisilva** [comment]
Expected to fix with the new console.
