### ISSUE TITLE
Add  Support to send login_hint in Authorize Request. 

### ISSUE THREAD

**Issue by Shaaali** [wso2/product-is#16282]
**Is your feature request related to a problem? Please describe.**

Currently, basic authenticator doesn't support sending login_hint as a query parameter. 

**Describe the solution you would prefer**

Add support to provide login_hint as a query parameter. 

**Additional context**

**Comment by Shaaali** [comment]
PRs to fix this : 

1. https://github.com/wso2/carbon-identity-framework/pull/4779
2. https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/145
3. https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/178
4. https://github.com/wso2/identity-apps/pull/3964

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
