### ISSUE TITLE
Incorrect Server URL appearing in the Home Page

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1629]
**Environment**
IS 5.4.0 Cluster setup (2 nodes) fronted by nginx
JDK - 1.8.0_45
DB - Mysql 5.6
OS - ubuntu 
Email as user enabled

**Steps to recreate the issue**
1. Configure IS server with hostname
2. Start the IS server and go to home page

**Observations**
Server URL not appearing correctly
![screenshot from 2017-12-18 10-12-34](https://user-images.githubusercontent.com/14962228/34090317-0d273ae2-e3dc-11e7-998d-1fab128c3659.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
