### ISSUE TITLE
[Regression] The multi-attribute login feature is not working properly 

### ISSUE THREAD

**Issue by Ushani-Athu** [wso2/product-is#16308]
There is an issue with the multi-attribute login functionality. The problem arises when attempting to use the custom claim for login, with three login identifiers: username, mobile, and customClaim.

**Describe the issue:**

The multi-attribute login is not functioning as expected when there are multiple claims configured in the "Allowed Attribute Claim List" with similar regex patterns. For instance, if we configure multiple claims (http://wso2.org/claims/mobile, http://wso2.org/claims/username, http://wso2.org/claims/customClaim) under the "Allowed Attribute Claim List," and we try to log in using the customNumber claim value (Eg: 1234567890), the login process fails.

**How to reproduce:**

1. Navigate to Identity Providers >> Resident >> Account Management >> Multi Attribute Login.
2. Configure multiple claims in the "Allowed Attribute Claim List" in Multi Attribute Login. For example: http://wso2.org/claims/mobile, http://wso2.org/claims/username, http://wso2.org/claims/customNumber.

3. Add regular expressions for allowed claims 

4. Attempt to login with the attribute value of http://wso2.org/claims/customNumber as the login identifier. For example: 1234567890.

5. Login fails with the error "Login failed! Please check your username and password and try again."

Analysis

According to [1], the login identifier value is matched against the given regex patterns of each claim by iterating through the allowed claim list. Once a value matches any claim regex, it invokes the setResolvedUserResult() method and breaks the loop.

               if (pattern.matcher(domainSeparateAttribute).matches()) {
                    setResolvedUserResult(userStoreManager, claimURI, loginAttribute, resolvedUserResult, claim);
                    break;
                }

For instance: The loop starts to find a match to the login identifier value 1234567890 by iterating through http://wso2.org/claims/mobile, http://wso2.org/claims/username, and http://wso2.org/claims/customNumber claims. If, in any case, it matches the "http://wso2.org/claims/mobile" claim regex, it will break the loop and choose the incorrect claim value instead of the customNumber claim value. Therefore, it will not iterate through the loop properly.

However, in the previous behavior [2], it iterates through the loop properly along with the getUserListWithID() method. Here, it validates the user list with the claimURI and loginAttribute. If such a user does not exist, it iterates through the loop without breaking the flow.

**Additional information:** 

There might be scenarios where two or more claims have the same value, leading to confusion about which claim should be selected for login. Therefore, it is essential to address such scenarios to ensure the multi-attribute login functionality works as intended.

**Environment information** : Product Version: [IS-6.1.0]

[1] - https://github.com/wso2-extensions/identity-governance/blob/v1.8.14/components/org.wso2.carbon.identity.multi.attribute.login/org.wso2.carbon.identity.multi.attribute.login.resolver.regex/src/main/java/org/wso2/carbon/identity/multi/attribute/login/resolver/regex/RegexResolver.java#L59-L74

[2] - https://github.com/wso2-extensions/identity-governance/pull/580

**Comment by lashinijay** [comment]
Closing as the this is fixed in master branch now.
