### ISSUE TITLE
Yahoo connector, in the authorize request, the scope parameter and nonce parameter is not being sent 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1630]
**Environement**
Standalone 5.4.0 GA pack
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**

1. Run Standalone IS 5.4.0 GA pack
2. Configure Travelocity as a Service Provider using SAML SSO
3. Configure a Yahoo app as in [1] and take the client ID and the client secret
4. Input them under federated authenticator > yahoo configuration
5. Configure yahoo IDP as a Federated authenticator for Service provider
6. Access http://localhost:8080/travelocity.com
7.Click on SAML redirect Binding
8.Provide Yahoo login details
9.Error message will be shown as in [2]

In Yahoo side configuration I didnt observe a place to give the callback URL(https://localhost:9443/commonauth). It asks only for a callback Domain where we can input localhost or another domain.
When it comes to the Yahoo connector, in the authorize request, the scope parameter and nonce parameter is not being sent which are required to be sent as in [3]

[1]. https://docs.wso2.com/display/IS540/Configuring+Yahoo
[2]. yahoo.png
[3]. https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html#getting-started-auth-code=

![yahoo](https://user-images.githubusercontent.com/31848014/34090331-285a8f12-e3dc-11e7-97ad-aa90b58723d6.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
