### ISSUE TITLE
Regenerate Secret button for OAuth/OpenID configuration deletes claims in Claim Configuration of an application

### ISSUE THREAD

**Issue by DumbravaRobert** [wso2/product-is#16307]
**Describe the issue:**

For an OAuth/OpenID application configured in WSO2IS, regenerating the secret in Inbound Authentication Configuration > OAuth OpenID Configuration will delete all claims in Claim Configuration, except the first one.

**How to reproduce:**

As an administrator, go to the admin GUI in /carbon/admin/index.jsp

Go to Service Providers > List

In the Service Providers list, click ‘Edit’ button for an OAuth/OIDC application.

Go to Claim Configuration and have multiple (more than one) claims defined as Custom Claim Dialect.

Update the SP, then come back.

Go To “Inbound Authentication Configuration > OAuth/OpenID Connect Configuration ad press the “Regenerate Secret” button. Agree with the dialogues. The secret changes.

Go to Claim Configuration and you will notice that only one claim exists in the list, the others disappeared.

**Expected behavior:**

 Regenerating the secret should not affect Claim Configuration.

 

**Environment information:**
- Product Version:  IS 6.0.0, IS 5.11.0
- OS: Linux
- Database: PostgreSQL
- Userstore: openLDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
