### ISSUE TITLE
[Doc][Query] What are the properties we should send when creating user stores via admin services

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1631]
Type: Query Doc issue
Priority: High
Severity: Major
Release: wso2is-5.4.0-update1 - 15/12/2017

I want to create different types of user stores (JDBC, LDAP etc) using admin services. We need to send properties such as connection url, password etc. to do so. Can you provide a list of properties for each user store in correct format?
```
<soapenv:Body>
      <xsd:addUserStore>
         <!--Optional:-->
         <xsd:userStoreDTO>
            <!--Optional:-->
            <xsd1:className>org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager</xsd1:className>
            <!--Optional:-->
            <xsd1:description>created with admin services</xsd1:description>
            <!--Optional:-->
            <xsd1:disabled>false</xsd1:disabled>
            <!--Optional:-->
            <xsd1:domainId>TEST9000</xsd1:domainId>
            <!--Zero or more repetitions:-->
            <xsd1:properties>
               <!--Optional:-->
               <xsd1:name>Connection URL</xsd1:name>
               <!--Optional:-->
               <xsd1:value>jdbc:mysql://localhost:3306/is520user</xsd1:value>
            </xsd1:properties>
         </xsd:userStoreDTO>
      </xsd:addUserStore>
   </soapenv:Body>
```

**Comment by dilinisg** [comment]
This information was found in [1]. But need to mention that the properties mentioned in the table are the ones we need to use in this scenario when invoking from admin services

[1] https://docs.wso2.com/display/IS540/Configuring+a+JDBC+User+Store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
