### ISSUE TITLE
Email OTP sent only for the user taken from the subject attribute step.

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#16317]
**Describe the issue:**

When email OTP configured as an authentication step, the current behaviour is to retrieve the user email from the user set to the step marked as the subject attribute step.
https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L247

If the subject attribute step has not yet been reached, and the current authenticated user has email address claim configured, then we get the following error.

<img width="798" alt="Screenshot 2023-07-25 at 13 44 27" src="https://github.com/wso2/product-is/assets/28347418/b7bcc159-9bf2-4361-a25f-f3beb331a4c6">

The official documentation does mention a requirement to pick the user attribute step.
https://is.docs.wso2.com/en/latest/guides/mfa/2fa-email-otp

**How to reproduce:**

1. Create a sample application.
2. Set basic authentication as first step and email OTP as second step.
3. Do not mark any step as the step to get user attributes. 
4. Try to sign in to the sample application.
5. Login should fail.

**Expected behavior:**

If there is no user to be retrieved from a subject attribute step and the current authenticated user has an email adress claim configured, they should receive the email the OTP.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
