### ISSUE TITLE
[Query] How to enable browser for multiple sso apps with IWA

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1632]
I have configured SSO for Salesforce and Management console with IWA authentication by following [1] and [2].
I have followed the steps mention in Document to enable the IWA from browser side.
But in firefox browser it allows me to register one url at a time. even we try with  both urls. SSO works only for one site in each time.
How we can enable the browser for  multiple sso sites ?

Further I have followed all the steps to enable IWA in IE browser. 
But it works only for management console. not for the Salesforce.  Do i need to follow additional steps in addition to the doc.
[1] https://docs.wso2.com/display/IS540/Configuring+IWA+Single-Sign-On

[2] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+with+Integrated+Windows+Authentication

Product - 5.4.0
Userstore- AD
Windows 2012
IE 9.0
Firefox 52.0.02

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
