### ISSUE TITLE
Improve frontend resolving of self contained Identifier First authenticators

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#16321]
**Is your suggestion related to an experience ? Please describe.**

Currently magic link and email otp authenticators support first factor login. That is through the self-contained IDF improvement. In there we have the user resolving logic at the particular authenticator (i.e. in magiclink or email otp) however the user identifier is retrieved using the Identifier first frontend code. This is done with the `authenticators` request parameter passed with the value of `IdentifierExecutor:LOCAL`. Due to this some flows recognize this as the IDF is in the authentication sequence and raise issues. This could lead to unexpected failures in the authentication flow.

**Describe the improvement**

Self contained identifier first approach should be improved in such a way that it doesn't affect other core functionalities.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
