### ISSUE TITLE
Re-issue Existing Confirmation Code in Resend-Activation Requests

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#16320]
**Is your suggestion related to an experience ? Please describe.**

A self registered user requests to resend account activation link due to expiration of the previous link. WSO2 Identity Server publishes an email that contains the link to activate the account. This link contains a confirmation code and other details.

When the email client is experiencing a delay and the email will be queued. The user waits a few minutes to receive the email. If the email is not received, the user will trigger an activation resend flow.

Now WSO2 Identity Server will check whether there are any confirmation codes already issued to the user. If so, those previous confirmation codes will be revoked and a new email will be published with a new confirmation code. The second email is also queued in the email client due to the delay.

Meanwhile, the email which was published in 1st attempt can be received by the user. The user will try to activate the account from that link, but the user is unable to activate it since the confirmation code in that email was already revoked/expired because of the second request. This can happen again and again based on the delay of the email client.

**Describe the improvement**

It’s better to resend the same account confirmation link(same confirmation code) when a user tries to resend the activation link multiple times within a specified time period. This activation link can be a PENDING_AP user activation link or a PENDING_SR user activation link.  I found a similar solution for the password reset flow[1]. 

[1] https://wso2.com/blogs/thesource/re-issue-existing-password-recovery-confirmation-code-in-followed-recovery-or-resend-requests/

**Additional context**

Product Version: ISKM 5.10

**Comment by SujanSanjula96** [comment]
Improvement PRs -
https://github.com/wso2-extensions/identity-governance/pull/749
https://github.com/wso2/carbon-identity-framework/pull/4877
