### ISSUE TITLE
showAuthFailureReason support for email otp and totp authenticators

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16333]
**Is your suggestion related to an experience ? Please describe.**
When showAuthFailureReason is enabled for basic authenticator and was showing respective error message to user since they get following parameters on the login page.
```
errorCode: 17003
lockedReason: MAX_ATTEMPTS_EXCEEDED
failedUsername: <username>
authFailure: true
authFailureMsg: login.fail.message
```

But if account locking is enabled for email otp and totp authenticators and requires the showAuthFailureReason support for them as well.

For TOTP, it is added in the master [1].

Moreover, showAuthFailureReason support is available for email OTP. But the parameters are not in the same pattern as basic auth.
```
authFailure: true
authFailureMsg: user.account.locked
```

It is good to return errorCode, lockedReason:, failedUsername parameters here as well to keep the consistency across the authenticators.

IS 5.11.0

[1] https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/135

**Comment by hwupathum** [comment]
Related issue https://github.com/wso2/product-is/issues/15525

**Comment by hwupathum** [comment]
Checked the current behaviour in 5.11

**Basicauth**

Before locked
```
errorCode: 17002
failedUsername: <username>
authFailure: true
authFailureMsg: login.fail.message
remainingAttempts: <remaining_attempts>
```

When locked
```
errorCode: 17003
lockedReason: MAX_ATTEMPTS_EXCEEDED
failedUsername: <username>
remainingAttempts: 0
```
