### ISSUE TITLE
[Migration] - Disabling the internal cleanup task by default

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16342]
**Describe the issue:**

With the changes from this PR https://github.com/wso2/carbon-identity-framework/pull/4724, we are disabling the internal session data cleanup task.

To keep the existing behavior (enable the internal session data cleanup), need to add the following to the deployment.toml file.
```
[session_data.cleanup]
enable_expired_data_cleanup = true
clean_logged_out_sessions_at_immediate_cycle = true
enable_pre_session_data_cleanup = true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
