### ISSUE TITLE
[Feature] Support for managing API resources and securing access to API resources

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#16344]
**Describe the improvement**

Securing access to API resources is a primary requirement during development of most applications.

Typically this is done by fronting the APIs with an API Gateway and securing the API resources with OAuth2 access tokens and scopes. The API Gateway plays the part of enforcing the security policy of not allowing access to API resources with an access token with the right scope. However, issuing the OAuth2 access token with the right scope is usually done by an Identity Provider / OAuth2 Authorization Server

Though WSO2 IS supports OAuth2 it currently does not have the capability to support securing an API resource first class.

Here are a few aspects that are lacking,

- No way to represent APIs or permissions (a.k.a scopes) related to the APIs
- No way to attach policies to decide how/when a particular API permission(scope) should be included in an access token. For example: which roles are allowed to access a particular scope.
- No way to enforce policies related to API permissions(scopes) during access token issuing
- No way to represent or enforce whether a particular application is authorized to access an API resource (This is more of a specialized example of 3)

**Additional context**

**Comment by AnuradhaSK** [comment]
**Identified Issues**

- [ ] https://github.com/wso2/product-is/issues/17238

**Comment by SujanSanjula96** [comment]
UI implementation PRs - 

- https://github.com/wso2/identity-apps/pull/4271
- https://github.com/wso2/identity-apps/pull/4300
- https://github.com/wso2/identity-apps/pull/4369

**Comment by ThaminduR** [comment]
This has been implemented and deployed with Identity Server 7.0.0 - Alpha
