### ISSUE TITLE
[Feature] Add the new Password Expiry feature

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#16349]
In IS, password expiry is implemented as a local authenticator which is not architecturally correct. So we need to implement password expiry as a post authentication handler

**Comment by dhaura** [comment]
The following issue has been raised in IS regarding the Password Expiry Enforcer.
- https://github.com/wso2/product-is/issues/16132

The following PR was created as a fix for the above issue.
- https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/pull/44

**Comment by madurangasiriwardena** [comment]
Backend improvements are completed. UI improvements in https://github.com/wso2/identity-apps/pull/4015 needs to be merged. Waiting for the new UI implementation since merging the existing PR will complicate the new UI merge.

**Comment by madurangasiriwardena** [comment]
UI changes are merged and added to the distribution.
