### ISSUE TITLE
Support setting allowed_auth_handlers for introspect endpoint

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16348]
Related to https://github.com/wso2/product-is/issues/12309

Currently, a access control block has to be defined in order to set allowed_auth_handlers for introspect endpoint.
```
[[resource.access_control]]
context="(.*)/oauth2/introspect(.*)"
http_method = "all"
secure = true
allowed_auth_handlers="BasicClientAuthentication"
```

But the following is already available in the identity.xml.j2
```
        <Resource context="(.*)/oauth2/introspect(.*)"
                secured="{{resource_access_control.introspect.secured}}"
                http-method="all">
            {% for permission in resource_access_control.introspect.permissions %}
            <Permissions>{{permission}}</Permissions>
            <Scopes>internal_application_mgt_view</Scopes>
            {% endfor %}
        </Resource>
```
This allows setting permission, etc for introspect endpoint, but not `allowed_auth_handlers`. That was the reason we had to add a separate `[[resource.access_control]]` section to override above default config.

Anyway, if we set `allowed_auth_handlers="BasicClientAuthentication"` with a  `[[resource.access_control]]` section, these permissions are not honored. Because there is no such with `BasicClientAuthentication` and other authentication options are not supported anyway.

The ideal solution is to support setting `allowed_auth_handlers` under `resource_access_control.introspect`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
