### ISSUE TITLE
Link resident provider section to Resident IDP documentation 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1634]
In [1] the 6th point is using a resident IDP. Please link this to the resident IDP description as a user who is entering the doc space need to know why the resident IDP is used.

[1] https://docs.wso2.com/display/IS540/Forced+Password+Reset#ForcedPasswordReset-PasswordResetviaRecoveryEmail

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
