### ISSUE TITLE
[Migration] Migrate Lite user Identity claims to Identity database

### ISSUE THREAD

**Issue by Wathsara** [wso2/product-is#16355]
**Describe the issue:**
Due to an issue in the lower packs, Identity claims of the lite users were added to the userstore even after configuring the identity store to store the identity claims.
- https://github.com/wso2/product-is/issues/16187

With the fix introduced using the below PR, the claim addition is fixed. for the users who are migrating from the lover versions, we need to migrate the identity claims of the lite users to the `idn_identity_user_data` table in identity database.
- https://github.com/wso2-extensions/identity-governance/pull/729

**How to reproduce:**
Follow the steps in below issue
- https://github.com/wso2/product-is/issues/16187

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
