### ISSUE TITLE
In the workflow management flow, user requires unnecessary permissions

### ISSUE THREAD

**Issue by UpekshaGalappaththi** [wso2/product-is#16350]
**Describe the issue:**
In Identity Server 6.0/ 6.1 versions, the workflow approval is done through the Console unlike My Account in the  versions before 5.11. Here an issue is present as logging into the console requires multiple admin permissions unlike in 5.11. A role created with the following permissions should be able to login to the Console and approve the workflow but currently when trying to access the Console it gives a 404 error.

Manage > Human Task > View Task
Manage > Identity > Workflow Management > BPS Profiles > View
Configure > Login

If the user with the role needs to login they require the below minimum permissions as well as the above mentioned ones.

Admin Permissions > Manage > Identity > Authentication Management > Session Management > View
Admin Permissions > Manage > Identity > User Management > View
Admin Permissions > Manage > Identity > User Management > List
Admin Permissions > Manage > Identity > User Store Management > User Store Configuration Management > View
Admin Permissions > Manage > Identity > Group Management > View
Admin Permissions > Manage > Identity > Governance Connector Management > View
Admin Permissions > Manage > Identity > Role Management > View

This is an issue as a role created for just workflow approval should not be able to view users or roles but If we remove the view permissions or any other above mentioned permissions user will not be able to login to the console and it will throw a 404 error.

It seems the root cause for this is In IS 5.11, the path of the current location passed into the gracefullyHandleRouting method at admin.tsx file [1] is /console/manage/users and the routes list contains the path for the approvals page - /console/manage/approvals. At the check isRouteAvailable [2], we check whether the routes list contains the current path and since the route list passed into this method does not contain the path /console/manage/users, isRouteAvailable becomes false and proceeds to [3], where the approvals path route is pushed to history.

But in IS 6.1.0, due to behavioural changes introduced by latest features the current location passed into the gracefullyHandleRouting method at admin.tsx file has been changed to /console/manage/approvals. Since this path is available in the route list, RouteUtils.isRouteAvailable method returns true at [4] and the gracefullyHandleRouting method returns without pushing the approvals path route to history. Therefore the logic of gracefullyHandleRouting method should be modified to handle this current path change and correctly push the relevant route.

**How to reproduce:**
Create a role with the following permissions.

Manage > Human Task > View Task
Manage > Identity > Workflow Management > BPS Profiles > View
Configure > Login

Try to login to console with a user belonging to that role and a 404 error will be shown.

**Expected behavior:**
A user belonging to the role should be able to login to console and only view the approvals page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.0, IS 6.1]

[1] https://github.com/wso2/identity-apps/blob/1.0.x/apps/console/src/views/admin.tsx#L126
[2] https://github.com/wso2/identity-apps/blob/1.0.x/apps/console/src/features/core/utils/route-utils.ts#L79
[3] https://github.com/wso2/identity-apps/blob/1.0.x/apps/console/src/features/core/utils/route-utils.ts#L83
[4] https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/core/utils/route-utils.ts#L75

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
