### ISSUE TITLE
 [Feature][Improvement] Introduce tenant-wise username input validation. 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#16357]
Epic: https://github.com/wso2-enterprise/iam-engineering/issues/648
Currently IS has username validation can be set on user store level.
Email as user name can be configured also https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/

But what we need a tenant-wise username validator where the admin can enforce rule based validators such as min, max character efficiently.

**Comment by Thumimku** [comment]
Postponing to alpha cause we need tenant qualified URL feature to be enabled

**Comment by Thumimku** [comment]
Integration test: https://github.com/wso2/product-is/pull/16983

**Comment by Thumimku** [comment]
We are nto delievering this feature as per the mail due to a functional limitaiton,
check: [Unification] Bring new tenant level Password/username validation feature to IS

**Comment by Thumimku** [comment]
@bhagyasakalanka is working on removing the feature from input validation listener.
@bhagyasakalanka can you please update the status?

**Comment by bhagyasakalanka** [comment]
Integration tests are fixed with: https://github.com/wso2/product-is/pull/17508
Username Input validation disable for IS: https://github.com/wso2/carbon-identity-framework/pull/5106

**Comment by bhagyasakalanka** [comment]
https://github.com/wso2/identity-apps/pull/4442
