### ISSUE TITLE
Disabled IDP is picked for fidp parameter leading to an error page

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#16351]
**Describe the issue:**
If there are 2 IDPs with same home realm identifier with one disabled and if the disabled IDP was not added to the particular SP, and if it happened to be selected during the IDP identification process using fidp parameter, it led to the error page: "Domain cannot be identified! Please retry."

**How to reproduce:**
1. Create 2 IDPs with same home realm identifier with one disabled.
    - IDP1 (home realm identifier: test)
    - IDP2 (home realm identifier: test) - disabled

2. Add the IDP1 to the SP and make the authentication request with `fidp=test`
    `https://localhost:9443/oauth2/authorize?response_type=code&scope=openid&redirect_uri=http://localhost.com:8080/pickup-dispatch/oauth2client&client_id=dt8pSXnfNo60fsP024n3zUazIXIa&fidp=test`
    as
It will show an error page intermittently.

**Expected behavior:**
1. Disabled IDP should not be selected for fidp paramater
2. Creation of duplicate home realm identifier should be prevented #13349
3. A proper error message should be shown, if the fidp is not found #14806

**Environment information**
 - Product Version: IS 5.11.0

**Comment by Lakshan-Banneheke** [comment]
Solution: Updated the DB query to retrieve only enabled IDPs.
