### ISSUE TITLE
[Feature] Support application roles for Identity Server and support RBAC for apps

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16363]
**Is your feature request related to a problem? Please describe.**
Role-based access control (RBAC) is a widely used access control mechanism for B2E and B2B applications. To support RBAC, API resource management, API Authorization to applications, application role management, and application role-based scope validation are key features to have in the IAM solution.

**Describe the solution you would prefer**

- Implement roles management catering organization level role mgt and application level role mgt
- Ability to assign userstore groups and  locally managed users to roles in the newly implemented model
- Ability to assign federated idp groups to roles in the newly implemented model
- Use these roles for scope validation and support RBAC
- Ability to share roles of B2B applications when sharing the app with sub org 
- Use these roles in XACML policies
- Add an adaptive script functions to consume application roles of a user during adaptive scripts

**Comment by Achintha444** [comment]
## Design

### Wireframe
https://docs.google.com/document/d/1Jt1ksVptBHmcrsitva_r4Aa7UjAFwVcr_rdlvkgh0Ns/edit

**Comment by Achintha444** [comment]
### Front-End PR's
- https://github.com/wso2/identity-apps/pull/4162
- https://github.com/wso2/identity-apps/pull/4147
- https://github.com/wso2/identity-apps/pull/4152
- https://github.com/wso2/oxygen-ui/pull/165

**Comment by AnuradhaSK** [comment]
### BE PRs

**SCIM and Charon Changes for Role V2 support**

- https://github.com/wso2/charon/pull/392
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/486

**Add access control and /o/ path support for /scim2/v2/Roles endpoint**

- https://github.com/wso2/carbon-identity-framework/pull/4917
- https://github.com/wso2/carbon-identity-framework/pull/4998

**Capability to associate roles in the new model with an application**

- https://github.com/wso2/carbon-identity-framework/pull/5001
- https://github.com/wso2/identity-api-server/pull/504

**Shared role managing event handler**
- https://github.com/wso2-extensions/identity-organization-management/pull/255

**Comment by AnuradhaSK** [comment]
### Migration Issues

- https://github.com/wso2/product-is/issues/16865 
- https://github.com/wso2/product-is/issues/16864

**Comment by AnuradhaSK** [comment]
Pending Items

- [ ] Cache fixes such as https://github.com/wso2/carbon-identity-framework/pull/4965#discussion_r1359897996
- [ ] Add Audit logs in the new pattern
- [ ] Integration Tests

**Comment by shashimalcse** [comment]
### Improvements :

- [ ] Organization validation improvement - https://github.com/wso2/carbon-identity-framework/pull/5043
- [ ] Invalid application cache after application audience role added - https://github.com/wso2/carbon-identity-framework/pull/5043

**Comment by PasinduYeshan** [comment]
### Improvements/ Bug Fixes :

[X] Fix permission not getting replaced when empty permission list is sent -  https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/495
[X] Fix 500 returns when empty value object is sent in patch replace operation - https://github.com/wso2/charon/pull/395

**Comment by asekawa** [comment]
Identified bugs
1.UI issues in groups assign section in the roles tab - https://github.com/wso2/product-is/issues/17235

**Comment by AnuradhaSK** [comment]
**Creating issues for pending tasks**

- [ ] Add a caching layer for role management
- [ ] Add audit logs for role management
- [ ] Support federated group to role mapping
- [ ] Use the newly introdicued roles in XACML policies with new authz runtime
- [ ] Add an adaptive script function to consume roles of a user during adaptive scripts
