### ISSUE TITLE
Password Reset via Recovery Email section refers to configuration files

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1636]
In [1] under **Password Reset via Recovery Email** it referees to the configuration where seemingly that stores the email templates. Asking the user to change the template from here is bit impractical as it can be done using the management console. Further more the 1st point direction to some configurations done above which is not clear enough. Please refactor this section so the user will have a demonstration using a given template.

[1] https://docs.wso2.com/display/IS540/Forced+Password+Reset#ForcedPasswordReset-PasswordResetviaRecoveryEmail

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
