### ISSUE TITLE
[Improvement] Quick start guide for B2B feature in Console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16364]
**Describe the improvement**

Depends on https://github.com/wso2/product-is/issues/16359
Once the B2B feature is onboarded to Identity Server, IS users should be aware about the feature and guide them  to setup and use the feature through a quick start guide.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
