### ISSUE TITLE
[Feature] Invite Parent Organization Users to a Child Organization for B2B Application Functionalities

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#16366]
**Is your feature request related to a problem? Please describe.**

In a B2B scenarios, some child organization may need to get some help from the parent organization to perform tasks in the child organization. For this requirement a user in the parent organization can be invited to the child organization. This invitation process can be happen from several ways.

1. Invitation initiation happens from a user in sub org
- Existing users at the parent org are invited from the child org and provide the permissions to manage the application in the child org.
- If the user does not have an account in the parent organization the ability for the user to register is provided only based on the fact if self registration is allowed or not from the parent org to the respective service.

2. Initiation happens from a user in parent org
- In this case the parent organization will give administrative access for an existing user in the parent org to manage resources of a child org.

**Describe the solution you would prefer**

Invitations should be initiated from a privileged user in a organization and after the invitation is accepted by the parent organization user, that user should be onboarded to the corresponding child organization.

**Comment by AnuradhaSK** [comment]
@ShanChathusanda93 and @dasuni-30 
Please link all the public PRs related to this feature in a comment

**Comment by asekawa** [comment]
@Shenali-SJ is there is a particular build version that we can test this feature , or else please do attach a version / build pack which we can test this feature within the eod.

**Comment by ShanChathusanda93** [comment]
Hi Team, 

Followings are the API and BE layer PRs for the feature.
* API Layer
  1. https://github.com/wso2/identity-api-server/pull/472
  2. https://github.com/wso2/identity-api-server/pull/488
  3. Add to the product-is : https://github.com/wso2/product-is/pull/16533

* BE
  1. Core Service : https://github.com/wso2-extensions/identity-organization-management/pull/221
  2. Unit tests for Core Service : https://github.com/wso2-extensions/identity-organization-management/pull/228
  4. Permissions for product-is : https://github.com/wso2/carbon-identity-framework/pull/4853
  5. Permission for invitation accept API : https://github.com/wso2/carbon-identity-framework/pull/4891
  6. User Sharing : https://github.com/wso2-extensions/identity-organization-management/pull/229
  7. User Invitation jar to the product-is : https://github.com/wso2-extensions/identity-organization-management/pull/232
  8. Improvements : https://github.com/wso2-extensions/identity-organization-management/pull/235 , https://github.com/wso2-extensions/identity-organization-management/pull/238
  9. Event handler config for send invitation : https://github.com/wso2-extensions/identity-organization-management/pull/236 , https://github.com/wso2-extensions/identity-organization-management/pull/237
  
* DB Schema
  1. https://github.com/wso2/carbon-identity-framework/pull/4850

**Comment by Shenali-SJ** [comment]
Please find the below FE PRs.
- https://github.com/wso2/identity-apps/pull/4286
- https://github.com/wso2/identity-apps/pull/4343
