### ISSUE TITLE
[Improvement] Revisit the parameters and behavior of the JWT token issued for a B2B application

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16365]
**Describe the improvement**

Revisit the parameters and behavior of the JWT token issued for a B2B application

There is a set of confusion regarding the JWT tokens issued for B2B applications. Ex: whether to include scopes, how to mention the organization issued for, etc. We need to clarify and define a standard set of parameters and behaviors for these tokens,

**Comment by sadilchamishka** [comment]
1.  With this improvement, the organization switch grant is not required for the B2B login users to access their organization resources. The first token received for B2B login can be used. 
 - Create an organization and user inside that. Assign an admin role to that user. Use this Curl as UI is broken atm
 - Login to the B2B app with a user with admin access.
 - Use that token to invoke an API in that organization space (suborg)

2. Also, check the retrieved ID token.  Their should be claims
org_id -> which denotes which org the token is bounded/scoped
org_name -> For display purpose
user_org -> The org where his identity is managed

3. Complex B2B use case - Switch that initial token

**Comment by sadilchamishka** [comment]
Documentation effort
- https://github.com/wso2/product-is/issues/17083

**Comment by asekawa** [comment]
- [ ] Is this document impacted?
- [ ] Is the end-to-end (e2e) testing complete?
- [ ] Are unit tests available?
- [ ] Are integration tests available?
- [ ] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ] Have demo sessions been completed? (If yes, please attach the recording link)
- [ ] Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?

**Comment by sadilchamishka** [comment]
`Is this document impacted` 
- Yes it is doc impacted as tracked with this https://github.com/wso2/product-is/issues/17083
2. Yes.
3. Not yet added.
4. There are no specific integration tests added. But the improvement is for access token issues for B2B apps and organization switching, the existing sample b2b app and console app should not break.

**Comment by asekawa** [comment]
> `Is this document impacted`
> 
> * Yes it is doc impacted as tracked with this [Improve documentation about the usage of organization switch grant #17083](https://github.com/wso2/product-is/issues/17083)
> 
> `Is the end-to-end (e2e) testing complete?`. - Yes.
> 
> `Are unit tests available?` - Not yet added.
> 
> `Are integration tests available`
> 
> * There are no specific integration tests added. But the improvement is for access token issues for B2B apps and organization switching, the existing sample b2b app and console app should not break.
> 
> `Are all the relevant sub-tasks updated as complete`
> 
> * No. Documentation and adding tests are remaining.
> 
> `Have demo sessions been completed?` - No
> 
> `Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?`
> 
> * It wil impact both

 @sadilchamishka any reason why uni tests are not available yet

**Comment by sadilchamishka** [comment]
There are remaining works
- Add integration tests
- Improve documentations
- Stop org_id & or_name for B2C login tokens.
