### ISSUE TITLE
Provide APIs to configure signup flow against applications and perform registration against it

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#16371]
**Is your feature request related to a problem? Please describe.**
The onboarding experience that one application wants to give its users may differ from another. So the application developer may configure their own flow for the registration.
These applications may need their own registration portals rather than redirecting users to the IS-provided registration page. Therefore, there should be an API that the developers can use to retrieve the configured registered flow and render the UIs accordingly.

**Describe the solution you would prefer**
Provide a set of APIs to configure a signup flow against an application and to perform the user registration against the configured signup flow.

First, priority should be given to the blocking use cases including

* registering with username/pwd with/without verification based on identifier (like email/sms verification), social login and passwordless options (email magic link, email OTP, SMS OTP)
* onboarding the second factor during the registration (TOTP)
* attribute collection at the registration (prompt for firstname, lastname, country)

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
