### ISSUE TITLE
Change document perspective on forced password reset

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1637]
Currently the document [1] describes the password reset as a guide which has a mixture of configurations, admin service calls etc... This is a direct technical document that explains how to get it done but does not explain the user perspective. AFAIU there are three personas that can be incorporated here which are end user, app developer and admin. So it's better to explain using those personas of what needs to be done to get the password reset working when using WSO2 Is as the IDP in a particular use case.

[1] https://docs.wso2.com/display/IS540/Forced+Password+Reset#ForcedPasswordReset-PasswordResetviaRecoveryEmail

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
