### ISSUE TITLE
Support same client Id for applications over different tenants

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#16370]
**Is your suggestion related to an experience ? Please describe.**

Currently in IS client ID is considered to be unique across the server and as a result the same client ID cannot be used in two different tenants. However when there are specific terms like `CONSOLE`, `MYACCOUNT`, etc, organization bound client ID is a valid requirement and should provide this capability.

**Describe the improvement**

Same client ID should be able to use across different tenants.

**Additional context**

**Comment by ThaminduDilshan** [comment]
**Related doc issue:**
- https://github.com/wso2/product-is/issues/16432

**Comment by melanisilva** [comment]
- [ ] Is this document impacted?
- [ ]  Is the end-to-end (e2e) testing complete?
- [ ]  Are unit tests available?
- [ ]  Are integration tests available?
- [ ]  Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
- [ ]  Has the cloud readiness been verified?

⭐ Please provide links to relevant Unit tests and integration tests

@ThaminduDilshan  Could we please have this checklist updated?

**Comment by ThaminduDilshan** [comment]
@melanisilva updated and testing can be started
