### ISSUE TITLE
[Feature] Support resolving the organization of the user at the point of access with email domains for B2B apps

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#16379]
**Is your feature request related to a problem? Please describe.**
When the user is accessing the system, we should be able to identify the organization of the user using the email domain. This is required to identify the organization where the user belongs and to give authority to the respective owner of that business to manage that identity.

**Describe the solution you would prefer**

We are only considering the sales-led approach and after the mapping is done at the primary organization level, flow should be as follows.

- User comes to the B2B application's home page and clicks login.
- Username input is prompted for the user.
- User enters an email address.
- System identified the user belongs to the respective sub-organization that owns the email domain and redirects the user to the organization login.
- User logins with the organization login and returns to the organization space of the B2B application.
- User registration also needs to be limited to the mapped email domain.

**Comment by dewniMW** [comment]
The design doc and user stories have been finalized.
Currently working on finalizing the API definition for organization discovery attribute management.

**Comment by dewniMW** [comment]
Steps to try out the feature:

1. Create sub organizations.
2. In the super organization console map email domains to these sub organizations (organizations may or may not have associated email domains.)
3. For sub organizations with mapped email domains create users with the username as email where the email is of one of the mapped organizations of that organization. Note that we only allow to register users with that particular domain. If a sub organization doesn't have a mapped domain, then users can't be created with an email domain that is associated with another organization in the hierarchy.
4. Register a B2B app in the super organization and share it with sub organization.
5. Access the B2B organization and sign with organization SSO. 
( 
- If the sub organization has a mapped domain, enter the username. The user will be redirected to the correct sub organization for authentication.
-  If the sub organization doesn't have mapped domains, enter the organization name to continue with the flow
)

**Comment by asekawa** [comment]
@dewniMW can you please check into this checklist


- [ ] Is the end-to-end (e2e) testing complete?
- [ ] Are unit tests available?
- [ ] Are integration tests available?
- [ ] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ] Have demo sessions been completed? (If yes, please attach the recording link)
- [ ] Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?

**Comment by asekawa** [comment]
@dewniMW 
tested this feature on the build no 4886(Jenkins build) but could not procced with the complete end-to-end flow as redirecting to  a blank page,after giving a sub org specific username(with the configured tenant name)

https://github.com/wso2/product-is/assets/40081059/2df5fd9a-a660-4f14-8638-a875b3cacfc1

**Comment by asekawa** [comment]
@dewniMW verified the basic flow under the pack https://drive.google.com/file/d/1e1WrjxJdhEbujc5brM5vdPFwIKBmXQos/view.

https://github.com/wso2/product-is/assets/40081059/94114c5c-5f9e-4ec0-9e64-98f1603b84fe

Given below are the identified issues.
1.https://github.com/wso2/product-is/issues/17382
2.https://github.com/wso2/product-is/issues/17390

**Comment by dewniMW** [comment]
Documentation aspect is tracked with https://github.com/wso2/product-is/issues/17396

**Comment by asekawa** [comment]
> @dewniMW can you please check into this checklist
> 
> * [ ]  Is the end-to-end (e2e) testing complete?
> * [ ]  Are unit tests available(if not provide reason)?
> * [ ]  Are integration tests available(if not provide reason)?
> * [x]  Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
> * [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
> * [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
> * [ ]  Does this change impact the on-prem environment only(s this an IS-specific feature) ?
> * [ ]  Are impacted docs updated?

@dewniMW please do attach the relevant doc issues related to the changes , and mention the reason for not having 
e2e and intergrations tests

**Comment by Rashmini** [comment]
Wireframes of the email domain discovery feature in the console:

Organization list with email domain mappings:
![image](https://github.com/wso2/product-is/assets/36252940/71303df5-ee66-4840-a7b0-00cc9f169c4a)

Add email domains to an organization:
![image](https://github.com/wso2/product-is/assets/36252940/24e94bf9-57bc-4a7f-a02f-04ceae822d88)

Update email domains of an organization:
![image](https://github.com/wso2/product-is/assets/36252940/18fd6071-c7be-46c6-bb31-ea3786ab6f89)

**Comment by dewniMW** [comment]
Closing this function as the overall functionality has been delivered with IS 7.0.0 alpha release. The rest of the improvements/tasks will be tracked with separate issues.
