### ISSUE TITLE
SDKs for API Based authentication

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#16374]
**Is your feature request related to a problem? Please describe.**
There should be SDKs for API Based authentication for mobile and web platforms covering Android, iOS, react, nextJS, etc (This is a sample list of technologies.)

**Describe the solution you would prefer**

**Additional context**
API based authentication will be delivered with https://github.com/wso2/product-is/issues/15684

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
