### ISSUE TITLE
[Improvement] Update IS console design to match Asgardeo (IS cloud version)

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#16384]
**Is your suggestion related to an experience ? Please describe.**
Currently IS has a beta version console app and my account app which has a close look and feel for the Asgardeo apps, and Asgardeo has more improved UI with better UX. Bring in those UIs to the IS will give better UX for IS users as well.

**Describe the improvement**
Merge Asgardeo app UIs with IS app UIs.

- [x] #16410
- [x] #16411
- [x] #16414
- [x] #16416
- [x] #16560
- [x] #16417
- [x] #16664
- [x] #16633
- [x] https://github.com/wso2/product-is/issues/16986
- [ ] ~https://github.com/wso2/product-is/issues/16629~ - This will track as a separate task. IS 7.0 new console will not have the UI support and complete feature will be taken off from IS 7 after the BETA.

**Comment by DonOmalVindula** [comment]
**Update - 12/09/2023**

All the related code for the initial merge is available in `identity-apps` and `carbon-framework`. But the version are not yet bumped in `product-is`. It will be bumped via https://github.com/wso2/product-is/pull/16596

**Comment by jeradrutnam** [comment]
Closing the issue as updated on the issue body.
