### ISSUE TITLE
General improvement on the SimplePAPStatusDataHandler class

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#16381]
**Is your suggestion related to an experience ? Please describe.**

When calling the `getStatusData` operation of the `EntitlementPolicyAdminService` SOAP service and internal call to the `readStatus()` method is made to retrieve the resource from the registry. During the execution of this method, a `PublisherPropertyDTO` object is created/updated [1] but it's never used in any other part of the method implementation.

**Describe the improvement**

Remove unnecessary code from the implementation.

**Additional context**

Tested on IS-6.1.0 but it applies for all versions.

---
[1] https://github.com/wso2/carbon-identity-framework/blob/60aadd9f5df0c1d1697249b77c36ba8e53f0772b/components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/SimplePAPStatusDataHandler.java#L232-L233

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
