### ISSUE TITLE
[Improvement] Change Identity-apps build from Jenkins to GitHub actions

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#16385]
**Is your suggestion related to an experience ? Please describe.**
Currently, the Identity-Apps build happens in Jenkins. Regardless of the changed module, the whole project is built and released as artifacts. With independent versioning and releasing this can be improved to build and release only the changed (affected) modules. This drastically reduces the build times and increases the efficiency in CI/CD.

**Describe the improvement**
As Jenkins, out of the box doesn't support such behavior, moving the release workflow to a GitHub Action should be considered.
A GitHub Action can build the affected modules and push artifacts to NEXUS by combining changesets with a custom release script.

**Comment by JayaShakthi97** [comment]
Release builder improvements are completed implementation-wise. As there is a major folder restructuring to accomplish separate versioning [https://github.com/wso2/product-is/issues/16417], planning to merge the changes after the jsp-apps and console refactoring changes are merged. Therefore pushing the milestone.

**Comment by JayaShakthi97** [comment]
Release workflow improvement is completed along with the separate app versioning. Product-is end improvement is yet to be merged due to integration test failures.

**Comment by JayaShakthi97** [comment]
Product-is end improvement is merged.
