### ISSUE TITLE
[Migration] - ske query parameter is removed in TOTP enroll flow by default

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#16391]
With https://github.com/wso2/carbon-identity-framework/pull/4826 ske query parameter is excluded by default in TOTP enroll flow. 

- These changes can be affected if someone has already done customizations based on the query param.
- This will get overridden if someone already has the config in the toml.

Therefore this information needs to be captured in the migration guide.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
