### ISSUE TITLE
Authentication Data API doc doesn't state the query params that are excluded by default

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#16394]
With [Authentication Data API](https://is.docs.wso2.com/en/latest/apis/use-the-authentication-rest-apis), users can configure a filter policy to exclude parameters from the URL in the authentication flow.
By default at the [code level](https://github.com/wso2/carbon-identity-framework/blob/a63b30b5719a92934aeee29fcfb71361ed402249/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkUtils.java#L1814), we have excluded the following params:

- `loggedInUser` - this parameter is used in the oauth2 consent flow
- `ske` -  this parameter is used in the TOTP enrollment flow

If the user adds a config like below to drop `sample_param1`, then it will override the default behavior of excluding `loggedInUser` and `ske` query params.

```
[authentication.endpoint.redirect_params] 
filter_policy = "exclude"    
parameters = ["sample_param1"]
```

Therefore in the docs, it should be stated clearly. If the user wants to exclude a new param including the params that are excluded by default, the config should be something like below.

```
[authentication.endpoint.redirect_params] 
filter_policy = "exclude"    
parameters = ["sample_param1", "ske", "loggedInUser"]
```

Related issue: https://github.com/wso2/product-is/issues/16391

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
