### ISSUE TITLE
When clicked on " UserProfileMgtService admin service" it's redirected to the management console

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1639]
In [1] (section Password Reset via Recovery Email) when clicked on "UserProfileMgtService admin service" it's redirected to the management console. Please correct this as here document that explains the relevant admin service with available operations should load.

[1] https://docs.wso2.com/display/IS540/Forced+Password+Reset#ForcedPasswordReset-PasswordResetviaRecoveryEmail

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
