### ISSUE TITLE
Configuring user claim regex validation

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16399]
This is to track documentation of the config introduced in https://github.com/wso2/product-is/issues/13174

```
[identity_mgt]
enable_user_claim_input_regex_validation = true
```
https://github.com/wso2/carbon-identity-framework/pull/3940

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
