### ISSUE TITLE
[Improvement] UI support for token exchange grant in Identity Server

### ISSUE THREAD

**Issue by shashimalcse** [wso2/product-is#16390]
**Is your suggestion related to an experience ? Please describe.**
With support for the token exchange grant type in the identity server (https://github.com/wso2/product-is/issues/16345), we should add UI support for the token exchange grant and trusted token issuer connection.

**Describe the improvement**
- Add the token exchange grant as a protocol in the application
- Add a connection for trusted token issuer

**Comment by madurangasiriwardena** [comment]
Implemented with https://github.com/wso2/product-is/issues/16384

**Comment by shashimalcse** [comment]
Closing this since it has been completed.
