### ISSUE TITLE
[Doc] old version of document links  are pointed in Configuring IWA on Linux page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1640]
Please update the link in the "For more information about IWA" in [1]. This link is referring to IS 5.2.0 Document.

[1] https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
