### ISSUE TITLE
Suborganization Self Service Text Display Issue in User Onboarding Section of Console

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#16407]
**Describe the issue:**
In the console's User Onboarding section, the text within the Suborganization Self Service Section is not being displayed correctly.
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/74205483/61e87889-a155-4d96-811b-97287c893b10">

**How to reproduce:**
- Build the IS 6.2.0 Alpha4 current source
- Login to the console
- Move to the Manage section
- Select `User Onboarding` under the `Configurations` in left panel
- Select the `Suborganization Self Service` from `Castegories` in right side

**Expected behavior:**
Text should be meaningfully displayed

**Environment information:**
 - Product Version: IS 6.2.0 Alpha4
 - OS: Mac
 - Database: Default
 - Userstore: Default

**Comment by dhaura** [comment]
Cause -  `i18n` module is not updated for the Suborganization Self Service feature. (Need to add necessary strings.)
