### ISSUE TITLE
[Migration] Allow case-insensitive username filtering in LDAP searches via SCIM2 API

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#16418]
In previous IS versions, username filtering in LDAP searches via SCIM2 APIs was case-sensitive when there are multiple filters including group membership, which was against the default LDAP searching behavior. LDAP searching is supposed to be case-insensitive always. There is an userstore configuration `CaseInsensitiveUsername` which we haven't honored due to this.
 
This bug was fixed through the following PR[1], allowing only the case-insensitive username searches.

However, for IS-6.0[2] and IS-6.1 we have to fix this issue in a backward-compatible manner to avoid regressions as there might be customers who have disabled `CaseInsensitiveUsername` and who have obtained the output as case-sensitive searches as expected according to the meaning of the configuration. Hence a new LDAP userstore configuration `CaseInsensitiveUsernameFiltering` was introduced to preserve the existing behavior. For IS-6.0 and IS-6.1 after the fix default behavior will be **case-sensitive** username filtering, by enabling `CaseInsensitiveUsernameFiltering` they can obtain the **case-insensitive** results.

For the public fix (IS-6.2.0) it was decided to consider this behavior as a bug and fix it. Hence in IS-6.2.0 the new configuration `CaseInsensitiveUsernameFiltering` will not be included and we will not honor the `CaseInsensitiveUsername` configuration as well allowing only case-insensitive searches for LDAP compiling to the correct behavior.

Related Issue:

- https://github.com/wso2/product-is/issues/16254

[1] - https://github.com/wso2/carbon-kernel/pull/3635
[2] - https://github.com/wso2-support/carbon-kernel/pull/2190

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
