### ISSUE TITLE
Unify the features and capabilities in Asgardeo and on-prem product UIs

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16414]
### Description 

We need to merge the features from Asgardeo products to the on-prem product as required. This would be done as a part of the user experience unification effort. Following are the tasks that will be covered under this effort.

- [x] https://github.com/wso2/product-is/issues/16462
- [x] https://github.com/wso2/product-is/issues/16463
- [x] https://github.com/wso2/product-is/issues/16464
- [x] https://github.com/wso2/product-is/issues/16580
- [x] https://github.com/wso2/product-is/issues/16465
- [x] https://github.com/wso2/product-is/issues/16466

**Comment by jeradrutnam** [comment]
Closing this issue as the tasks are completed and delivered with IS 7.0 Alpha.
