### ISSUE TITLE
Two color schemes in the sample request shown for setUserProfile

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1641]
As shown in the below image, there are two colors in the sample request under "Password Reset via Recovery Email" 

![is_doc_1](https://user-images.githubusercontent.com/15624590/34093603-23979a0c-e3ef-11e7-958c-350e82a4b18d.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
