### ISSUE TITLE
Remove external links when merging the Asgardeo and Onprem Portals

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16411]
### Description 

In the effort carried out to merge the Asgardeo and on-prem portals, we need to remove any links pointing to external resources such as documentation links, Github repository links, etc.

**Comment by JayaShakthi97** [comment]
### Progress Update - 12-09-2023
- Initial improvements are made to replace the anchor tags with `DocumentationLink` component.
- Improvements are made to use the `useDocumentation` hook where it is not been used.
- There are a few reported external links pointing to privacy policy, etc.

**Comment by JayaShakthi97** [comment]
Reported external links also updated and completed the task.
