### ISSUE TITLE
Add support to independent app versioning for on-prem portals

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16417]
### Description

In the current build, we fetch the identity-apps artifact which includes all the portals under the same version. In order to support the unification effort we need to add support to independent app versioning for Console and My Account.

**Comment by NipuniBhagya** [comment]
This task is will be carried out as a sub task of https://github.com/wso2/product-is/issues/16385

**Comment by JayaShakthi97** [comment]
Release builder improvements are completed implementation-wise. As there is a major folder restructuring to accomplish separate versioning, planning to merge the changes after the jsp-apps and console refactoring changes are merged. Therefore pushing the milestone.

**Comment by JayaShakthi97** [comment]
Update: https://github.com/wso2/product-is/issues/16385#issuecomment-1716932859
