### ISSUE TITLE
Check and deprecate unused overloaded methods from AbstractUserStoreManager class

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#16425]
**Describe the issue:**
There are overloaded methods available in AbstractUserStoreManager class but it seems not all of the methods are currently not being used in the product. Better to evaluate and deprecate un-used methods from AbstractUserStoreManager class. 

- https://github.com/wso2/carbon-kernel/blob/4.9.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L10644
- https://github.com/wso2/carbon-kernel/blob/4.9.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L11011

**How to reproduce:**

**Expected behavior:**
If there any un-used methods in the mentioned class file, its need to properly deprecated from the code base. Be mindful about the annotations and the documentations should be updated if we deprecate any methods.
 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [6.2.0-alpha4]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
