### ISSUE TITLE
The ID token expiry time cannot be updated in the WSO2 Identity Server Key Manager 5.6.0.54

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#16426]
**Describe the issue:**

The ID token expiry time of an OAuth service provider cannot be updated in the WSO2 Identity Server Key Manager 5.6.0.54. I have checked this with the WUM timestamp 1602171844704 as well and it still does not work.

**How to reproduce:**

- Login to the management console as an administrator.
- Create a OAuth service provider.
- Try to update the ID token expiry time after the creation.

The updated value will not be saved and it will revert to the previous value. According to the initial debugging process, it seems like the the SQL statements that are used in the source code is incorrect because it does not contain the `ID_TOKEN_EXPIRE_TIME` field that needs to be updated. This seems to be introduced as a fix for [1] because in the public tag [2] the field is considered in the SQL statement e.g. `prepStmt.setLong(7, oauthAppDO.getIdTokenExpiryTime());`.

[1] - https://github.com/wso2/product-is/issues/5323
[2] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.0.14/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/dao/OAuthAppDAO.java#L482-L501

**Expected behavior:**

The id token expiry field should get updated properly without an issue.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-KM 5.6.0.54
 - OS: Ubuntu 20.04.3 LTS
 - Database: H2
 - Userstore: LDAP

**Comment by RushanNanayakkara** [comment]
Closing as completed
