### ISSUE TITLE
Server start up issues

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#16429]
Server start-up fails with the following error logs in OpenJDK version "openjdk version "11.0.18" in wso2is-6.1.0-m1-SNAPSHOT pack.

1. Component1 : Component[
	name = identity.application.authenticator.SMSOTP.component
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.authenticator.smsotp.internal.SMSOTPAuthenticatorServiceComponent
	state = Unsatisfied
	properties = 
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = AccountLockService, interface = org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockService, policy = dynamic, cardinality = 1..1, target = null, bind = setAccountLockService, unbind = unsetAccountLockService]
		Reference[name = EventMgtService, interface = org.wso2.carbon.identity.event.services.IdentityEventService, policy = dynamic, cardinality = 1..1, target = null, bind = setIdentityEventService, unbind = unsetIdentityEventService]
		Reference[name = IdentityGovernanceService, interface = org.wso2.carbon.identity.governance.IdentityGovernanceService, policy = dynamic, cardinality = 1..1, target = null, bind = setIdentityGovernanceService, unbind = unsetIdentityGovernanceService]
		Reference[name = RealmService, interface = org.wso2.carbon.user.core.service.RealmService, policy = dynamic, cardinality = 1..1, target = null, bind = setRealmService, unbind = unsetRealmService]
	}
	located in bundle = org.wso2.carbon.extension.identity.authenticator.smsotp.connector_3.3.4 [235]
]
Component2: Component[
	name = identity.application.authenticator.SMSOTP.component
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.authenticator.smsotp.internal.SMSOTPAuthenticatorServiceComponent
	state = Unsatisfied
	properties = 
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = AccountLockService, interface = org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockService, policy = dynamic, cardinality = 1..1, target = null, bind = setAccountLockService, unbind = unsetAccountLockService]
		Reference[name = EventMgtService, interface = org.wso2.carbon.identity.event.services.IdentityEventService, policy = dynamic, cardinality = 1..1, target = null, bind = setIdentityEventService, unbind = unsetIdentityEventService]
		Reference[name = IdentityGovernanceService, interface = org.wso2.carbon.identity.governance.IdentityGovernanceService, policy = dynamic, cardinality = 1..1, target = null, bind = setIdentityGovernanceService, unbind = unsetIdentityGovernanceService]
		Reference[name = RealmService, interface = org.wso2.carbon.user.core.service.RealmService, policy = dynamic, cardinality = 1..1, target = null, bind = setRealmService, unbind = unsetRealmService]
	}
	located in bundle = org.wso2.carbon.extension.identity.authenticator.smsotp.connector_3.2.0 [234]
]  

2. [2023-08-10 14:19:56,009] []  WARN {org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector} - [SCR] Found components with duplicated names! Details: 
Component1 : Component[
	name = org.wso2.carbon.identity.authentication.internal.X509CertificateRealmServiceComponent
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateRealmServiceComponent
	state = Unsatisfied
	properties = {service.pid=org.wso2.carbon.identity.authentication.internal.X509CertificateRealmServiceComponent}
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = user.realmservice.default, interface = org.wso2.carbon.user.core.service.RealmService, policy = dynamic, cardinality = 1..1, target = null, bind = setRealmService, unbind = unsetRealmService]
	}
	located in bundle = org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector_3.1.8 [239]
]
Component2: Component[
	name = org.wso2.carbon.identity.authentication.internal.X509CertificateRealmServiceComponent
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateRealmServiceComponent
	state = Unsatisfied
	properties = {service.pid=org.wso2.carbon.identity.authentication.internal.X509CertificateRealmServiceComponent}
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = user.realmservice.default, interface = org.wso2.carbon.user.core.service.RealmService, policy = dynamic, cardinality = 1..1, target = null, bind = setRealmService, unbind = unsetRealmService]
	}
	located in bundle = org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector_3.1.5 [238]
]  

3.[2023-08-10 14:19:56,010] []  WARN {org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector} - [SCR] Found components with duplicated names! Details: 
Component1 : Component[
	name = osgi.servlet.dscomponent
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.authenticator.x509Certificate.internal.X509CertificateServiceComponent
	state = Unsatisfied
	properties = {service.pid=osgi.servlet.dscomponent}
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = accountLockService, interface = org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockService, policy = dynamic, cardinality = 1..1, target = null, bind = setAccountLockService, unbind = unsetAccountLockService]
		Reference[name = osgi.user.realm.service.default, interface = org.wso2.carbon.user.core.service.RealmService, policy = dynamic, cardinality = 1..1, target = null, bind = setRealmService, unbind = unsetRealmService]
		Reference[name = osgi.httpservice, interface = org.osgi.service.http.HttpService, policy = dynamic, cardinality = 1..1, target = null, bind = setHttpService, unbind = unsetHttpService]
	}
	located in bundle = org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector_3.1.8 [239]
]
Component2: Component[
	name = osgi.servlet.dscomponent
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.authenticator.x509Certificate.internal.X509CertificateServiceComponent
	state = Unsatisfied
	properties = {service.pid=osgi.servlet.dscomponent}
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = accountLockService, interface = org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockService, policy = dynamic, cardinality = 1..1, target = null, bind = setAccountLockService, unbind = unsetAccountLockService]
		Reference[name = osgi.user.realm.service.default, interface = org.wso2.carbon.user.core.service.RealmService, policy = dynamic, cardinality = 1..1, target = null, bind = setRealmService, unbind = unsetRealmService]
		Reference[name = osgi.httpservice, interface = org.osgi.service.http.HttpService, policy = dynamic, cardinality = 1..1, target = null, bind = setHttpService, unbind = unsetHttpService]
	}
	located in bundle = org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector_3.1.5 [238]
]  

Full log can be viewed here. https://docs.google.com/document/d/1kiy6wmpNZ2zcN_heFhPgbjDeUGO2H99JOlRJx2RNwA8/edit

**Comment by RushanNanayakkara** [comment]
This issue is not reproducible in the latest wso2is-6.1.0 and wso2is-6.2.0 Alpha 4 versions. Therefore closing the issue.
