### ISSUE TITLE
Switch to using the latest Java patch versions in the Github Actions

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16437]
**Describe the issue:**
With recent updates in the Java patch version `11.0.20+8`, we've encountered certain restrictions that have impacted our PR builders and dependency updater workflows. As a workaround, we had to revert to using an older version `11.0.19+7` via the `setup-java@v2` action. However, using a stale Java version isn't a sustainable or secure solution.

We need to look at an approach where we can pass system properties during the Java setup phase. The properties are:

```sh
-Djdk.util.zip.disableZip64ExtraFieldValidation=true 
-Djdk.nio.zipfs.allowDotZipEntry=true
```

One possible approach is to see if we can customize system properties via `setup-java@v2` itself.
Or else, we might need to find another action which would support that functionality.

actions we need to update: 

- [ ] [product-is dependency-updater.yml](https://github.com/wso2/product-is/blob/master/.github/workflows/dependency-updater.yml)
- [ ] [product-is pr-builder-test-JDK11.yml](https://github.com/wso2/product-is/blob/master/.github/workflows/pr-builder-test-JDK11.yml)
- [ ] [identity-inbound-auth-oauth pr-builder.yml](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/.github/workflows/pr-builder.yml)
- [ ] [identity-inbound-provisioning-scim2 pr-builder.yml](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/.github/workflows/pr-builder.yml)

**Comment by DilshanSenarath** [comment]
As all related tasks have been completed, including the merging of the relevant pull requests, this issue is now considered resolved and will be marked as closed.

**Comment by DilshanSenarath** [comment]
Further the actions have been successfully updated in the following repositories:

- [ ] https://github.com/wso2-extensions/identity-outbound-auth-oidc/blob/master/.github/workflows/pr-builder.yml

**Comment by CommandoHuan** [comment]
> **Describe the issue:** With recent updates in the Java patch version `11.0.20+8`, we've encountered certain restrictions that have impacted our PR builders and dependency updater workflows. As a workaround, we had to revert to using an older version `11.0.19+7` via the `setup-java@v2` action. However, using a stale Java version isn't a sustainable or secure solution.
> 
> We need to look at an approach where we can pass system properties during the Java setup phase. The properties are:
> 
> ```shell
> -Djdk.util.zip.disableZip64ExtraFieldValidation=true 
> -Djdk.nio.zipfs.allowDotZipEntry=true
> ```
> 
> One possible approach is to see if we can customize system properties via `setup-java@v2` itself. Or else, we might need to find another action which would support that functionality.
> 
> actions we need to update:
> 
> * [x]  [product-is dependency-updater.yml](https://github.com/wso2/product-is/blob/master/.github/workflows/dependency-updater.yml)
> * [x]  [product-is pr-builder-test-JDK11.yml](https://github.com/wso2/product-is/blob/master/.github/workflows/pr-builder-test-JDK11.yml)
> * [x]  [identity-inbound-auth-oauth pr-builder.yml](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/.github/workflows/pr-builder.yml)
> * [x]  [identity-inbound-provisioning-scim2 pr-builder.yml](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/.github/workflows/pr-builder.yml)

Can you show me each specific steps to pass it. Thank you.

**Comment by chamathns** [comment]
> > **Describe the issue:** With recent updates in the Java patch version `11.0.20+8`, we've encountered certain restrictions that have impacted our PR builders and dependency updater workflows. As a workaround, we had to revert to using an older version `11.0.19+7` via the `setup-java@v2` action. However, using a stale Java version isn't a sustainable or secure solution.
> > We need to look at an approach where we can pass system properties during the Java setup phase. The properties are:
> > ```shell
> > -Djdk.util.zip.disableZip64ExtraFieldValidation=true 
> > -Djdk.nio.zipfs.allowDotZipEntry=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > One possible approach is to see if we can customize system properties via `setup-java@v2` itself. Or else, we might need to find another action which would support that functionality.
> > actions we need to update:
> > 
> > * [x]   [product-is dependency-updater.yml](https://github.com/wso2/product-is/blob/master/.github/workflows/dependency-updater.yml)
> > * [x]   [product-is pr-builder-test-JDK11.yml](https://github.com/wso2/product-is/blob/master/.github/workflows/pr-builder-test-JDK11.yml)
> > * [x]   [identity-inbound-auth-oauth pr-builder.yml](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/.github/workflows/pr-builder.yml)
> > * [x]   [identity-inbound-provisioning-scim2 pr-builder.yml](https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/.github/workflows/pr-builder.yml)
> 
> Can you show me each specific steps to pass it. Thank you.

hi @CommandoHuan 

you can export the JAVA_TOOL_OPTIONS env variable as:

`export JAVA_TOOL_OPTIONS="-Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true"`
