### ISSUE TITLE
[Docs] Support same client Id for applications over different tenants

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#16432]
**Is your suggestion related to a missing or misleading document? Please describe.**

Currently in IS client ID is considered to be unique across the server and as a result the same client ID cannot be used in two different tenants. However when there are specific terms like `CONSOLE`, `MYACCOUNT`, etc, organization bound client ID is a valid requirement and should provide this capability.

Same client ID should be able to use across different tenants. This improvement will be done with https://github.com/wso2/product-is/issues/16370. Need to document this properly.

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by aaujayasena** [comment]
@ThaminduDilshan is this deliver with the IS 7.0.0. If not, shall we move this to  new dashboard. https://github.com/orgs/wso2/projects/97/views/1

**Comment by ThaminduDilshan** [comment]
This is a doc issue. Should we add it to new dashboard?

**Comment by ThaminduDilshan** [comment]
This needs to be completed when related sections are added to the documentation.

Related PR: https://github.com/wso2/docs-is/pull/3987
