### ISSUE TITLE
Notification on user credentials change through mechanisms other than the account recovery mechanism

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#16431]
**Is your feature request related to a problem? Please describe.**

Currently, we offer the functionality to notify the user on password reset success in the account recovery flow. However, if the user uses a mechanism such as SCIM Me to update the password, a notification is not sent (such as in My Account/User-Portal applications).

**Describe the solution you would prefer**

It would be preferred if a functionality to do the said task can be added to the product.

**Additional context**

Related issue: https://github.com/wso2/product-is/issues/8895

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
