### ISSUE TITLE
An error popping up continuously when DB connection failure during IDP creation

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1643]
**Environment**
IS 5.4.0 standalone pack
JDK - 1.8
DB - Postgres 9.6.3
OS - ubuntu 15.10

**Steps to recreate the issue**
1. Provide IDP name and register IDP
2. Go to Federated Authenticator -> Facebook configuration and provide the configuration params
3. Stop DB connection
4. Click the update button to save Federated authenticator providers
5. Then start the DB connection

**Observations**
1. If a user tries to update the IDP configurations at a point where DB connection failure occurs, an error message is **continuously popping up in the IDP mgt console**.
![screenshot from 2017-12-18 12-23-44](https://user-images.githubusercontent.com/14962228/34093737-e81a2480-e3ef-11e7-8240-360e6cc82990.png)

2. The configurations added in the IDP configuration did not save or updated

3. Error message correctly reflect that DB connection issue exists

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
