### ISSUE TITLE
Sinhala translation issues in Console UI

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16430]
**Describe the issue:**

The Sinhala term "හැඳුනුම්පත්" too should be replaced with "අනන්‍යතා" as well to maintain consistency.

![Screenshot 2023-08-10 at 13 47 49](https://github.com/wso2/product-is/assets/41533942/e477bd47-9cf4-4110-9172-dc22c9fd84ef)

We should use the term "යෙදුම්" in the highlighted places in order to preserve consistency.
 
![Screenshot 2023-08-10 at 13 58 41](https://github.com/wso2/product-is/assets/41533942/bde3efa4-7dd3-4d5f-ba75-bf846b536a9f)

No Si-LK translation is available for application templates.

![Screenshot 2023-08-10 at 14 07 16](https://github.com/wso2/product-is/assets/41533942/d62df681-8103-4318-85ef-4bb554a9781e)

No Si-LK translation is available for connection templates

![Screenshot 2023-08-10 at 14 08 49](https://github.com/wso2/product-is/assets/41533942/ab4750ce-a85f-474a-84d5-d13cf1f94cea)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
