### ISSUE TITLE
SetProfile method in  UserProfileMgtService returns 202 on success

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1644]
According to [1] status 202 indicates that the request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place. But in this case, when the request is successful then the relevant change will be done on the resource and completed. Hence this should return 200 OK.

[1] https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
