### ISSUE TITLE
SCIM PATCH Group operation depends on 'display' attribute and never uses 'value' (User ID)

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#16451]
**Describe the issue:**
While attempting to add an User to a Group with only the User ID (provided as `value`), server encounters an `NullPointerException` and responds with 500. Looking at the code for updating the Group [1] we can see that `value` is never used and User ID is always retrieved from the username provided as `display` [2] [3].
I believe we should be using `value` to get an User out of `SCIMUserManager#getUser` [4] like `UserResourceManager` does before invoking `SCIMUserManager#updateUser` [5]
It seems some providers such as Azure AD SCIM is "out-bounding" only `value` with the user's :
```json
{ ":schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
  ":Operations":[
    {":op":"Add",":path":"members", ":value":[{":value":"<<UUID>>"}]}
  ]
}
```

**How to reproduce:**
1. Create an user and a role for this test. Like `testuser` and `testrole`.
2. Get the role's Group ID and user's SCIM ID from the `/Group` and `/Users` endpoint respectively.
3. Attempt to update only providing the User ID in the `value`:
```sh
curl -k -X 'PATCH' \
  'https://localhost:9443/t/carbon.super/scim2/Groups/ebb74d52-af85-45ad-baa1-706642c70bf2' \
  -H 'accept: application/scim+json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/scim+json' \
  -d '{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "add",
      "value": {
        "members": [
          {
            "value": "7b8819c5-ff51-48f9-948e-782e26c9b417"
          }
        ]
      }
    }
  ]
}'

*Response:* %{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],
"detail":"Error in performing the patch operation on group resource.","status":"500"}%
``` 
4. On the other hand, doing this only with `display` works:
```sh
curl -k -X 'PATCH' \
  'https://localhost:9443/t/carbon.super/scim2/Groups/ebb74d52-af85-45ad-baa1-706642c70bf2' \
  -H 'accept: application/scim+json' \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Content-Type: application/scim+json' \
  -d '{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "add",
      "value": {
        "members": [
          {
            "display": "testuser"                     
          }
        ]
      }
    }
  ]
}'

*Response:* %{{"displayName":"testrole","meta":{"created":"2023-08-14T20:51:46.516Z","location":"https://localhost:9443/scim2/Groups/ebb74d52-af85-45ad-baa1-706642c70bf2","lastModified":"2023-08-14T20:51:46.516Z"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:Group"],"members":[{"display":"testuser","value":"7b8819c5-ff51-48f9-948e-782e26c9b417","$ref":"https://localhost:9443/scim2/Users/7b8819c5-ff51-48f9-948e-782e26c9b417"}],"id":"ebb74d52-af85-45ad-baa1-706642c70bf2"}%
```

**Expected behavior:**
The SCIM Specs [6] doesn't specify the `display` attribute being required, focusing on how to handle `value`. So the Identity Server should accept `value` and add the role of the given Group ID to the User of the given User ID.

**Environment information:**
 - Product Version: IS 5.10.0

**References:**
[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.1/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L2432
[2] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.1/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L2452-L2469
[3] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.1/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L2535-L2536
[4] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.5.1/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L282
[5] https://github.com/wso2/charon/blob/v3.3.15/modules/charon-core/src/main/java/org/wso2/charon3/core/protocol/endpoints/UserResourceManager.java#L656
[6] https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2.1

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
