### ISSUE TITLE
SOAP Service removal from the Integration tests of the Identity Server

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#16456]
## **Describe the issue:**
This issue will track the effort of removing the SOAP based API usages in the Integration Tests of the Identity Server by replacing them with the current REST based API implementations. Task is done without affecting the current flows of the test cases. 

Test Cases which tests the SOAP API usages will not be removed while other test cases will be modified accordingly with adding new Rest based Clients.

## Progress
https://docs.google.com/spreadsheets/d/1sErPrBsHRo7IOR2uEJvGxpKeIYGPsmhKfSU9zhx-Knk/edit?usp=sharing

## **Email Thread:**
[Removing SOAP services from Asgardeo and Identity Server] 
(This email thread was initiated according to the roadmap of the Lightweight Identity Server distribution for Asgardeo.)

## Related PRs:
- https://github.com/wso2/product-is/pull/16223
- https://github.com/wso2/product-is/pull/16271
- https://github.com/wso2/product-is/pull/16354
- https://github.com/wso2/product-is/pull/16455

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
