### ISSUE TITLE
When force password reset is applied for the user the error given at the management console is wrong

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1645]
Please see the below image where the wrong error is given for a forced password reset in management console

![is_issue_1](https://user-images.githubusercontent.com/15624590/34093920-e2782d00-e3f0-11e7-9dd1-3ed4a34dede2.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
