### ISSUE TITLE
Minimum Waiting Period(Minimum password age) for Password Changes

### ISSUE THREAD

**Issue by Ushani-Athu** [wso2/product-is#16452]
**Is your suggestion related to an experience ? Please describe.**
Currently, there is no specific configuration for minimum waiting period after a password change before allowing another password change through the password reset functionality. 

**Describe the improvement**
Adding a feature to the Identity Server that enforces a minimum waiting period would greatly improve security and provide a smoother user experience.

**Additional context**
[1] - https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-age#best-practices

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
