### ISSUE TITLE
Add B2B Organization management UIs to the IS Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16466]
**Is your suggestion related to an experience ? Please describe.**
In the current IS console we have disabled the organization management feature as we did not have the BE support for this feature in the on prem product. With the unification effort we need to bring the organization management UIs to the IS Console and resolve the UI gaps.

- [ ] When user is in the super tenant (root-organization), user should be able to create parallel tenants
- [ ] Remove view sub-organizations option from dropdown
- [ ] Administrators listing navigation should come along with the root-organization listing dropdown (It could be a cog wheel icon to popup settings for the organization). Note:- This task may not need immediately, can be done when the environment support is on-boarded

**Comment by sadilchamishka** [comment]
https://github.com/wso2/product-is/issues/16581
