### ISSUE TITLE
Add Remote Logging configuration UI in the IS Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16464]
**Is your suggestion related to an experience ? Please describe.**
We need to bring the Remote logging UI configuration of https://github.com/wso2/product-is/issues/16697 to IS Console.

**Comment by pavinduLakshan** [comment]
Marking this issue as on-hold since the GET /configs/remote-logging is not implemented yet and it wouldn't be possible to introduce the UI without it as it is required to deliver a better UX.

cc: @madurangasiriwardena @NipuniBhagya

**Comment by pavinduLakshan** [comment]
@bhagyasakalanka is currently working on the backend improvements for the GET /configs/remote-logging.

**Comment by bhagyasakalanka** [comment]
I'm started working on back-end improvements for remote logging feature today.  Following tasks are pending
- Store configurations in the database
- Write a periodically running thread to update configuration in a clustering environment.
- Write a GET API 
- Improve other API if applicable. 

To write the GET API, we need the first task to be completed. Based on that, to deliver the APIs,

Best case: 2nd October (Monday)
Average case: 3rd October (Tuesday)
