### ISSUE TITLE
After password reset happens once the link in the email directs to a password reset page again

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1646]
After resetting the password from the email, after clicking on the link or button re-directs to the password reset page again. But when reset no error is given rather goes to a blank page. 

![is_issue_3](https://user-images.githubusercontent.com/15624590/34094122-d74d02c4-e3f1-11e7-99fc-4cd1c07f1583.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
