### ISSUE TITLE
Improve the user store onboarding flow in the Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16462]
**Is your suggestion related to an experience ? Please describe.**
In Asgardeo we have an improved user experience in the user store onboarding flow. We need to bring that improved experience to the Identity Server under the unification effort.

**Comment by DonOmalVindula** [comment]
After discussing about the unification, it was decided to keep the IS experience for User Store as it is with the new look and feel. Therefore the features and UI will be the same with the new theme

**Comment by DonOmalVindula** [comment]
This is available with the console version 2.0.0 in the is pack
