### ISSUE TITLE
Adaptive function for user creation

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#16471]
**Describe the improvement**
Currently our just-in-time provisioning flow is too rigid. In a super-tenant deployment, if we enable JIT provisioning, a new account would always gets created regardless of whether the business can determine a potential mapped account already exists or not. There is no dynamic override option to check for a potential mapped account existence either by providing a unique set of attribute values or prompting the user to enter some identifier values, and associating  an existing local account to the federated identity. If the JIT provisioning is disabled we can only associate the federated identity to an existing local account via adaptive script, but cannot JIT provision and associate via adaptive script if a mapped local account does not exist. The problem is, we can't achieve both the above use cases at the same time in the same super-tenant deployment.

Potential solution could be to provide an adaptive function for user creation so that the developer can explicitly invoke this function in the middle of the login journey when the necessary conditions are met, rather than depending on GUI configuration. If this is provided we also need to think about the overall experience of how the function and GUI configuration are going to coexist.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
This must be covered with https://github.com/wso2-enterprise/iam-product-management/issues/14
