### ISSUE TITLE
[DOC]WS-Federation (Passive) Configuration screenshot is invalid in Idp Creation 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1647]
Document: https://docs.wso2.com/display/IS540/Configuring+WS-Federation
Step 3-1

Please include the correct screenshot and provide relevant configuration details in WS-Federation (Passive) Configuration.
![aa](https://user-images.githubusercontent.com/31693103/34094171-06fb67ae-e3f2-11e7-9a0f-cfaa553170a7.png)

The selected values in above screenshots are not included in the doc.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
