### ISSUE TITLE
Request Object and related validations in PAR request

### ISSUE THREAD

**Issue by anjuchamantha** [wso2/product-is#16475]
As per the PAR specification [1], it is not mandated to send ‘request’ parameter, but if request parameter is an accepted parameter, need to validate properly.

PAR says: 
> “Clients MAY use the request parameter as defined in JAR [[RFC9101](https://datatracker.ietf.org/doc/html/rfc9101)] to push a Request Object JWT to the authorization server.”
> “The client is authenticated with JWT client assertion-based authentication”
> “Validate the Request Object signature as specified in JAR”

However if the client app is FAPI [2] compliant (check Notes*) sending the ‘request’ parameter is mandatory.

FAPI says:
> “shall require a JWS signed JWT request object passed by value with the request parameter or by reference with the request_uri parameter”
For PAR requests, this should be done in the PAR call, not the authorization call.

Because of these above reasons, need to validate request object in PAR request.

PKCE Validation:
PKCE is mandated in request object in FAPI spec [3]. Hence if the app is FAPI compliant, need to have PKCE mandatory validation for request object validation.
> "shall require [PAR](https://tools.ietf.org/html/draft-ietf-oauth-par) requests, if supported, to use PKCE ([RFC7636](https://tools.ietf.org/html/rfc7636)) with S256 as the code challenge method."

In addition to these validations mandated by FAPI, an extension point to validate extra claims sent inside the request object would be helpful.

---
References
[1] [PAR Specification : Request Object](https://datatracker.ietf.org/doc/html/rfc9126#:~:text=parameters%20as%20a-,Request%20Object,-according%20to%20%5B)
[2] [FAPI Specification : Request Object](https://openid.net/specs/openid-financial-api-part-2-1_0.html#authorization-server:~:text=the%20authorization%20server-,shall,-require%20a%20JWS)
[3] [FAPI Specification : PKCE Validation](https://openid.net/specs/openid-financial-api-part-2-1_0.html#:~:text=supported%2C%20to%20use-,PKCE,-(RFC7636)%20with)

---
Notes*
_As per the current discussions, FAPI is planned to be supported in client application level as a Service Provider app metadata.
For validations mandated by FAPI (making request object mandate and PKCE inside request object mandate), may need to have an overridable isFapi() method which returns False by default._

**Comment by Yoshani** [comment]
PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2139 onboards request object validations to PAR endpoint. FAPI compliance related improvements need to be done by OB.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
