### ISSUE TITLE
RoleManagement Event publishing is not handling exceptions to stop the operation

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#16480]
**Describe the issue:**

Even though we are throwing a exception according to  https://github.com/wso2-extensions/identity-governance/blob/824e240008cfb393f840700be7ab5dac70185f7a/components/org.wso2.carbon.identity.password.policy/src/main/java/org/wso2/carbon/identity/password/policy/handler/PasswordPolicyValidationHandler.java#L161

But as per the role management core at the event publisher proxy the exception is ignored after logging and not interfered with the operation.
https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/role-mgt/org.wso2.carbon.identity.role.mgt.core/src/main/java/org/wso2/carbon/identity/role/mgt/core/RoleManagementEventPublisherProxy.java#L342

**Expected behavior:**
It is required to stop the operation and essentially pass the error message to the UI rather than only printing it and ignoring.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

**Comment by hwupathum** [comment]
Introduced a new error code (RMA-55001) where we can use if we want to break RoleManagement operations in a custom event.

**Comment by hwupathum** [comment]
To throw an exception from a custom event who has subscribed to pre roles operations, use the error code `org.wso2.carbon.identity.role.mgt.core.RoleConstants.Error.ERROR_CODE_CUSTOM_EVENT_HANDLER_ERROR`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
