### ISSUE TITLE
When adding an email template with an invalid name the message given should be modified

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1648]
In $subject the error message contains a regex. Rather than the regex, please provide a wording on the expected pattern

![is_issue_1](https://user-images.githubusercontent.com/15624590/34094286-93944974-e3f2-11e7-8cd2-90feb94d38cc.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
