### ISSUE TITLE
Confluence related jargon is displayed in the documentation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1649]
Please see the below image with respective to [1]. Please remove the jargon

![is_doc_1](https://user-images.githubusercontent.com/15624590/34094359-e98e9618-e3f2-11e7-955f-da3de7f6f502.png)

[1] https://docs.wso2.com/display/IS540/Customizing+Automated+Emails

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
