### ISSUE TITLE
Additional calls to secondary LDAP

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/product-is#16491]
**Describe the issue:**

While using the password grant, there is an additional call to the secondary LDAP. Even though the user in the primary user store is found, it seems we are querying the secondary user store for some reason. This behavior can be seen in both the most recent U2 versions of APIM 4.0.0 and IS 5.11.0.

**How to reproduce:**

We believe it is the result of changes in U2 update 7577. When we debug the flow we were able to see there is an additional call to the secondary user stores even though the user in the primary user store is found.

**Expected behavior:**

We do not need to call the secondary user stores even when the user is found on the primary user store.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
