### ISSUE TITLE
TOTP Device Registered Even with Wrong OTP in the Business User Login Flow

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#16497]
**Describe the issue:**

> Even if an incorrect OTP is entered during the login flow, the device is still being registered.

<img width="577" alt="image" src="https://github.com/wso2/product-is/assets/59449070/e1a55e82-29c4-480a-91d9-08394f10443f">

> If the business user login to my account and configure an Authenticator App, then the behaviour is working properly.

<img width="870" alt="image" src="https://github.com/wso2/product-is/assets/59449070/b55ac840-008d-4fd9-b1a6-85e005d5ebe5">

The reason behind this is when the business user configures TOTP through my account and initially provides invalid TOTP, then in the database `http://wso2.org/claims/identity/verifySecretkey` value is populated to the `IDN_IDENTITY_USER_DATA` table.
Once the user enters the correct TOTP, the `http://wso2.org/claims/identity/secretkey` value is populated.

But for the business user login flow, the `http://wso2.org/claims/identity/secretkey` value is populated in first place and `http://wso2.org/claims/identity/verifySecretkey` value is not used.

**How to reproduce:**

1. Try the TOTP login scenario in the document - https://is.docs.wso2.com/en/latest/guides/mfa/2fa-totp/#try-it-out
2. In the second steps it shows to register TOTP by showing the QR code.
3. Click continue and enter an invalid OTP.
4. It shows an error, and then try to log in again.
5. Now it doesn't show the QR code to register, only prompts to enter the TOTP.

**Expected behavior:**
If the user enter an invalid TOTP in the registration, it should not register that device.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [wso2is-6.2.0-alpha4.zip](https://github.com/wso2/product-is/releases/download/v6.2.0-alpha4/wso2is-6.2.0-alpha4.zip)
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
* https://github.com/wso2/product-is/issues/15197

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
