### ISSUE TITLE
Add default support for tenant qualified URLs

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16504]
**Describe the issue:**
Currently,  tenant qualified URLs are not enabled in the Identity Server by default. We need to do a comprehensive gap analysis on tenanted URL unsupported features in Identity Server. Following this analysis, we should address these gaps to ensure that tenant-qualified URLs are enabled by default in the Identity Server.

**Comment by Thisara-Welmilla** [comment]
PRs to fix integration test failures after enabling tenanted qualified URLs
- https://github.com/wso2/product-is/pull/16683
- https://github.com/wso2/product-is/pull/16756
