### ISSUE TITLE
XACML 'Simple Policy Editor' doesn't allow creating a policy with a name having more than 20 characters

### ISSUE THREAD

**Issue by dulanjal** [wso2/product-is#16527]
**Describe the issue:**
XACML 'Simple Policy Editor' has a policy name max limit of 20 characters. Other editors like Basic and Standard supports 50 characters. 20 characters is too short sometimes to give a meaningful policy name.  

**How to reproduce:**
Try to create a new policy using the 'Simple Policy Editor' and give "Entitlement Policy Name" a value with 21 characters or more. It give a JS popup saying "Policy Name is invalid".
 
**Expected behavior:**
- It should allow to create a policy name with at least 50 characters.
- If the max length is exceeded, error message should explicitly indicate the issue.

**Environment information** 
 - Product Version: IS 6.1.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
