### ISSUE TITLE
Add SUBJECT_IDENTIFIER column to IDN_OAUTH2_DEVICE_FLOW table

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#16524]
**Describe the issue:**
$subject has been introduced to fix https://github.com/wso2/product-is/issues/16177. This will need migration for the existing versions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
