### ISSUE TITLE
No error messages when user stores are created with invalid domain names via admin services

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1653]
Type: Bug
Priority: High
Severity: Major
Release: 5.4.0-update 1

1. Create a user store with an invalid domain name via admin services
eg: domain name = PRIMARY1-ATTRIBUTE STORE

**Issue**
The response does not mention any error and the user store seems to be created. But, actually the store is not created

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
