### ISSUE TITLE
ClassNotFound error thrown in identifier-first flow handler when ValidateUsername is enabled

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#16537]
**Describe the issue:**
Identifier-first flow handler is throwing and ClassNotFound error for the `org/wso2/carbon/identity/application/authenticator/basicauth/util/BasicAuthErrorConstants$ErrorMessages` class when validate username is enabled and user enters an invalid username.

**How to reproduce:**
1. Enable validate username in identifier first handler.

- In 5.7, go to application-authnetication.xml in <IS_HOME>/repository/conf/identity directory.

Enable ValidateUsername for `IdentifierExecutor` authenticator config.

```
<AuthenticatorConfig name="IdentifierExecutor" enabled="true">
    <Parameter name="ValidateUsername">true</Parameter>
</AuthenticatorConfig
```

- If deployment.toml is used, add the following config.

```
[authentication.authenticator.user_identifier] 
name ="IdentifierExecutor"
enable=true
[authentication.authenticator.user_identifier.parameters]
validate_username= true
```

2. Create a service provider and add the identifier-first as the first step.
3. Enter an invalid username.
4. User will be redirected to retry.do page (this redirection is happening due to ClassNotFound error ignoring the acutal exception).

**Expected behavior:**
User should not redirected to retry.do page and an error should shown in the same page (where the username needs to be entered) saying the user not found.

**Environment information:**
 - Product Version: IS 5.7 and upwards

---

This issue is happening due to the missing import package in identifier-first osgi imports. Importing the following package will resolve the issue.

```
org.wso2.carbon.identity.application.authenticator.basicauth.util; version="${identity.application.auth.basicauth.imp.pkg.version.range}",
```

**Comment by ZiyamSanthosh** [comment]
The missing import is already available in the master branch [1]. No fix is required for the master branch. Hence closing the issue.
[1] https://github.com/wso2-extensions/identity-local-auth-basicauth/blob/master/components/org.wso2.carbon.identity.application.authentication.handler.identifier/pom.xml#L150
