### ISSUE TITLE
[DOC] Onboard B2B organization management related documantation

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#16548]
The B2B organization management feature is available in the Identity Server distribution 7.0.0 onwrads. Hence the IS documentations should be properly updated.

Ref - https://ciamcloud.docs.wso2.com/en/latest/guides/b2b-org-management/b2b-org-permissions/

The documantation effort done of the WSO2 PCC can be reused, and update the documentation as necessary.

#### Related Issues
- https://github.com/wso2/product-is/issues/16359

**Comment by AnuradhaSK** [comment]
- [ ] Improve API docs of organization mgt with proper API paths and sample payloads
