### ISSUE TITLE
Improvements to PAR implementation

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#16549]
The following improvements need to be done to complete the PAR implementation to continue the effort in issue [1].

- [x] DB scripts for clearing 
- [x] Parameters to be added to Discovery documentation
- [x] Public documentation
- [x] Developer documentation

### Related Issues
- Issue https://github.com/wso2/product-is/issues/16013

**Comment by Yoshani** [comment]
### Progress

 - [ ] DB scripts for clearing

> - PR https://github.com/wso2/carbon-identity-framework/pull/4875

 - [ ] Parameters to be added to Discovery documentation

**Comment by chamathns** [comment]
closing this since completed
