### ISSUE TITLE
[Doc] Inconsistency in properties used in JDBC userstore manager

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1655]
Type: Improvement
Priority: High
Severity: Minor
Release: 5.4.0

Some properties are in camel case and some are in pascal case. These need to be consistent.
eg:
userName
ReadOnly

https://docs.wso2.com/display/IS540/Configuring+a+JDBC+User+Store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
