### ISSUE TITLE
[Migration] The lastPasswordUpdate claim update event handler changes

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#16555]
**Description:**

With the improvement done to the identityUserMetadataMgtHandler with PRs[1][2] in the effort of onboarding idle account identification feature [3], the following behavioural change was introduced,
- The identityUserMetadataMgtHandler will not update the http://wso2.org/claims/identity/lastPasswordUpdateTime claim at password update. 
Note: This event handler is not enabled by default previously and we have kept the same behavior for this with improved handler as well.
- The http://wso2.org/claims/identity/lastPasswordUpdateTime claim is updated with the enforcePasswordResetEventHandler which is enabled by default.

[1]. https://github.com/wso2-extensions/identity-governance/pull/739
[2]. https://github.com/wso2/carbon-identity-framework/pull/4865
[3]. https://github.com/wso2/product-is/issues/16356

**Comment by Thisara-Welmilla** [comment]
Please refer https://docs.google.com/document/d/1N7N6VoZk4N2_m-ZUWAz3Zp5YYBANSFgiLVBFH1orWuM/edit#heading=h.u0z7cmmifynb

**Comment by Thisara-Welmilla** [comment]
As

**Comment by shashimalcse** [comment]
ack
