### ISSUE TITLE
[Migration] Update PRIMARY KEY constraint in `FIDO2_DEVICE_STORE` table in H2 database

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#16553]
It was observed that there is an inconstancy in the PRIMARY KEY defined on `FIDO2_DEVICE_STORE` table in H2 database when compared to other databases.

**PRIMARY KEY in H2 database**
 ```
PRIMARY KEY (TENANT_ID, DOMAIN_NAME, USER_NAME, USER_HANDLE);
```
**PRIMARY KEY defined in other databases(DB2, MYSQL, MSSQL, POSTGRESQL, ORACLE)**

```
PRIMARY KEY (CREDENTIAL_ID, USER_HANDLE)
```

With the fix[1] done for the issue[2] USER_HANDLE no longer will be unique across the table and instead it will be unique to the user. Due to the PRIMARY KEY defined on H2 database will cause an issue as it is no longer unique. Considering that and the consistancy with other database it is required to update the  aforementioned PRIMARY KEY in `FIDO2_DEVICE_STORE` table in H2 database.

To achieve that following two queries need to be executed in H2 database.

- Drop the existing PRIMARY KEY in `FIDO2_DEVICE_STORE` table.
```
ALTER TABLE FIDO2_DEVICE_STORE DROP PRIMARY KEY
```
-  Add the new PRIMARY KEY to align with the other databases.
```
ALTER TABLE FIDO2_DEVICE_STORE ADD PRIMARY KEY(CREDENTIAL_ID,USER_HANDLE)
```

[1] - https://github.com/wso2-extensions/identity-local-auth-fido/pull/109
[2] - [https://github.com/wso2/product-is/issues/16443](https://github.com/wso2/product-is/issues/16443)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
