### ISSUE TITLE
Add missing index for the table `IDN_OAUTH2_ACCESS_TOKEN`

### ISSUE THREAD

**Issue by UdeshAthukorala** [wso2/product-is#16567]
**Describe the issue:**

With fix [1], we have introduced a new db query GET_ACCESS_TOKENS_BY_BINDING_REFERENCE. With a significant amount of records in the IDN_OAUTH2_ACCESS_TOKEN this query execution (without proper indexes) will require a significant amount of time to complete and in turn will introduce thread deaths.

**Expected behavior:**

Since this is a very frequent query following index needs to added.

`CREATE INDEX IDX_TBR_TS ON IDN_OAUTH2_ACCESS_TOKEN(TOKEN_BINDING_REF, TOKEN_STATE);`

**Environment information**
 - Product Version: [e.g., IS 5.10.0, IS 6.0.0, IS 6.1.0]

**References**

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1564

**Comment by UdeshAthukorala** [comment]
This is already fixed in master branch via:  https://github.com/wso2/carbon-identity-framework/pull/4472

**Comment by ImalshaG** [comment]
> This is already fixed in master branch via: [wso2/carbon-identity-framework#4472](https://github.com/wso2/carbon-identity-framework/pull/4472)

Closing the issue based on this comment.
