### ISSUE TITLE
[DOC] Onboard idle account identification API documentation

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#16562]
With the feature [1], the idle account identification API is on-boarded to the product is. Need to improve the office IS-Serve doc space with the new API specification.

To enable the event handler to store the last logon time claim for the user, add following to the deployment.toml
```
[identity_mgt.events.schemes.identityUserMetadataMgtHandler.properties]
enable=true
```

Updated yaml: https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.idle.account.identification/org.wso2.carbon.identity.api.idle.account.identification.v1/src/main/resources/idleAccountIdentification.yaml

Please Refer:
- https://wso2.com/asgardeo/docs/apis/idle-account-identification/
- https://wso2.com/asgardeo/docs/apis/organization-management/idle-account-identification/#/

[1]. https://github.com/wso2-enterprise/iam-engineering/issues/650

**Comment by divyaamunugama** [comment]
This is a new API doc for the **IS 7.0.0** release.

**Comment by AnuradhaSK** [comment]
API: https://github.com/wso2/docs-is/pull/4405
