### ISSUE TITLE
Improve language switcher UX

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16565]
**Is your suggestion related to an experience ? Please describe.**

The current language switcher component takes too much width and too much explicit. Instead, it can be made more compact by showing only the flag / ISO language code in the dropdown.

![Screenshot 2023-09-01 at 15 09 08](https://github.com/wso2/product-is/assets/41533942/412a65a6-b4c0-4068-8749-f5ea0f0eb7b2)

**Describe the improvement**

Need to make the language switcher more compact.

**Additional context**

N/A

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
