### ISSUE TITLE
[Doc] Please include the steps how to find the DNS name in AD server.

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1656]
When I'm going through the "Configuring IWA on Linux" page [1]-> under Setting up IWA section,

We have to find the DNS host name in the AD, In order to find these server details, you can follow the steps mentioned in [2]. Please update the document with these information to find the DNS host entry.

[1] https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux

[2] https://support.microsoft.com/en-us/help/816587/how-to-verify-that-srv-dns-records-have-been-created-for-a-domain-cont

**Comment by chalitha87** [comment]
There is a alternative step of doing this mapping etc/hosts entry in windows. Please mentioned that step as well.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
