### ISSUE TITLE
Revisit the performance tuning related docs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16570]
The doc [1][2] seem to be outdated and not having latest information. It is really great to update it. Some suggestions can be found in [3].

Following were some issues found in [1]
- The config under `Set the thread execution limit for multitenant mode` is incorrect. It duplicates the valve which is enabled by default
- JVM settings
  - MaxPermSize is deprecated since java 8
  - entity expansion limit is not seem to be related to IS since it does not do that much of complex operations with XML
- Database level settings
  - why this index can not be shipped in the product itself? Aren't there any other indexes to be added? 
  - Include about `CaseInsensitiveUsername` property along with information on https://github.com/wso2/product-is/issues/14204
- MaxPermSize is not related to JDBC pool configuration
- Pool LDAPS connections; 
  - It should mentioned about userstore property as well (ConnectionPoolingEnabled)
  - if there are both ldaps and ldap connections, this property should be as following
```
-Dcom.sun.jndi.ldap.connect.pool.protocol=”plain ssl”
```
- Are the OS level optimizations up to date?

----
Following were some issues found in [2]
- The image is not found
- The following point is incorrect. We are not using distributed caching anymore.
```
WSO2 Identity Server is using Hazelcast for underlying caching implementation to distribute the policy cache among clustered Identity Servers.
```
- What is the action required here? Any config changes?

[1] https://is.docs.wso2.com/en/latest/deploy/performance/performance-tuning-recommendations/
[2] https://is.docs.wso2.com/en/latest/deploy/performance/improve-pdp-performance/
[3] https://github.com/wso2-cs/iam-resources/tree/main/WSO2-Identity-Server-Deployment-Guide

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by rksk** [comment]
This needs to be fixed sooner or later.
