### ISSUE TITLE
Make nonce mandatory for Request Object validation in PAR

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#16578]
**Is your suggestion related to an experience ? Please describe.**

The nonce parameter should be made mandatory in the Request Object validation of the PAR flow to prevent `Request URI Swapping` issue, according to the PAR specification [1].

```
Clients SHOULD make use of PKCE [[RFC7636](https://datatracker.ietf.org/doc/html/rfc7636)], a unique state parameter [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)], or the OIDC "nonce" parameter [[OIDC](http://openid.net/specs/openid-connect-core-1_0.html)] in the pushed Request Object to prevent this attack.
```
### Related issues 
- Issue https://github.com/wso2/product-is/issues/16573

[1] https://datatracker.ietf.org/doc/html/rfc9126#name-request-uri-swapping

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
