### ISSUE TITLE
Update IDN_RECOVERY_DATA table and add IDN_RECOVERY_FLOW_DATA table

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#16576]
With the fixes done for https://github.com/wso2/product-is/issues/16536, following DB changes were done.

- Introduced the new table `IDN_RECOVERY_FLOW_DATA`
- Added `RECOVERY_FLOW_ID` column to the `IDN_RECOVERY_DATA` table
- Made `RECOVERY_FLOW_ID` column a foreign key in the `IDN_RECOVERY_DATA` table

Related PR: https://github.com/wso2/carbon-identity-framework/pull/4883

This needs a migration for the existing versions.

**Note for the migration Impact doc** 

```
### Disabling User Account Recovery V1 API

With IS 7.0.0, User Account Recovery v1 API will be disabled by default.
It is recommended to migrate to the User Account Recovery v2 API. For users who still wish to use the v1 API, adjustments to the deployment.toml file are necessary. Add the following configuration to enable the v1 API:

[identity_mgt.recovery]
enable_v1_api = true

By incorporating this configuration, the v1 API will be kept enabled, aligning with behaviors observed in earlier versions.
```

**Comment by Rashmini** [comment]
Cleanup script for the new table is added with https://github.com/wso2/carbon-identity-framework/pull/4969

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
