### ISSUE TITLE
PAR improvements

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#16573]
**Describe the issue:**
This issue keeps track of the following improvements which need to be done to the PAR implementation.

- [ ] Improve `PrivateKeyJWTClientAuthenticator` to accept PAR ep url, issuer identifier as audience value
  - Issue https://github.com/wso2/product-is/issues/16574

- [ ] Make nonce mandatory for Request Object validation in PAR 
  - Issue https://github.com/wso2/product-is/issues/16578 

- [x] Add PAR metadata parameter to DCR ep
  - Issue https://github.com/wso2/product-is/issues/16579

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
