### ISSUE TITLE
Cached Tokens are not Updated Immediately after Deletion of OAuth Client Applications

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#16582]
### Describe the issue
- When an OAuth client application, which previously issued an access token for a specific set of scopes, is deleted and then, a new application bearing the same client ID is created, we get the same revoked access token when a new token is requested for the same set of scopes. 

https://github.com/wso2/product-is/assets/57411348/de2d66e9-ca0b-40d3-a774-f30b58cb0a55

- After some time (most probably after the cached is cleared periodically) or after we restart the IS, we get a new authorized token.

### How to reproduce
1. Download the IS pack and start it up. 
2. Create an OAuth client application with a specific client ID [1].
3. Create an access token for the above client with `client_credentials` as the grant type [2] and specify a set of scopes as well (ex: `openid`).
4. Access some API end point with the retrieved token (ex: Applications Management API [3]). You should be able to successfully access it.
5. Delete the created client application [4]. 
6. Now create another OAuth client application with the same client ID as in step 2.
7. Now request an access token for the new client with the same attributes (grant type, scopes and etc.) as mentioned in Step 3. You can see that it returns the same access token that was received in Step 3.
8. Now try to access some API end point (as in Step 4) and you should get an `unauthorized` response with `401` code.

### Expected behavior
- In Step 7 you should get a new access token.
- In Step 8, you should be able to access the API successfully.

### Additional Note
- If we revoke [5] the tokens of the application before deletion, then this issues does not persist.

https://github.com/wso2/product-is/assets/57411348/e714c227-65e8-4ea5-89d8-9a2e089642b2

### Environment information
 - Product Version: IS `7.0.0-m1`
 - OS: `macos Ventura 13.5.1`
 - Database: `Defaut`
 - Userstore: `Default`

---

### Optional Fields

**Related issues:**
(None)

### References
[1] - https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-dynamic-client-registration/#register-an-oauth-application
[2] - https://is.docs.wso2.com/en/latest/guides/access-delegation/client-credentials-playground/#try-client-credentials-grant
[3] - https://is.docs.wso2.com/en/5.10.0/develop/application-rest-api/#/Applications/getAllApplications
[4] - https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-dynamic-client-registration/#delete-an-oauth-application
[5] - https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-token-revocation/

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2294/files
