### ISSUE TITLE
Sub-organization view menu should display the organization informations instead of creating another level of sub-orgs

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#16589]
**Describe the issue:**

When clicking an organization listed in the organizations list, it doesn't display the organization details, but it allows to create another level of organization as shown below. 

<img width="1222" alt="Screenshot 2023-09-05 at 15 26 21" src="https://github.com/wso2/product-is/assets/35717390/554be096-9b54-4ea1-8836-daeee7f3e821">

Creating sub-org in another level should be disabled, and it should only be done after switching to that organization. Fix should be done in both FE (hide it) and BE. As mentioned, upon clicking view the organization it should list the organization information as shown in below.

<img width="758" alt="Screenshot 2023-09-05 at 15 27 14" src="https://github.com/wso2/product-is/assets/35717390/c6e1a20b-73cb-4a89-8e4f-582b897a352f">

**How to reproduce:**
1 - Create an organization and check the organization list view.
2 - Click an organization.

**Expected behavior:**

The organization information should be displayed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0-m1]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
