### ISSUE TITLE
Add Application API Endpoint to Filter Apps by Name

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#16585]
### Is your suggestion related to an experience ? 
- During the process of onboarding the E2E test suite for IS, it was noticed that it requires an endpoint to filter applications by name, in order to check the existence sample apps before creating them.

### Describe the improvement
- A new API endpoint for applications [1], in order to retrieve applications filtered by application name (just like for application ID [2]).

[1] - https://is.docs.wso2.com/en/5.10.0/develop/application-rest-api/
[2] - https://is.docs.wso2.com/en/5.10.0/develop/application-rest-api/#/Applications/getApplication

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
