### ISSUE TITLE
Password reset options - multiple are able to be enabled

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1659]
Currently through UI its able to enable both Enable Password Reset via Recovery Email and Enable Password Reset via OTP.  But having both enabled does not have a use. Can we restrict the UI to take only one value at a time?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
