### ISSUE TITLE
Docs needs to be updated with new JIT config to allow the user to login to fidp even the associated local user is locked/disabled

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#16599]
**Is your suggestion related to a missing or misleading document? Please describe.**
With this improvement https://github.com/wso2/product-is/issues/16318, the users can able to login to IDP even the associated local user is locked or disabled in JIT provisioning flow.

**Describe the improvement**
Introduce the following configurations to allow the user to login to federated IDP if the JIT provisioned associated local user is locked or disabled.
```
[authentication]
jit_provisioning.allow_idp_login = true
```
---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
