### ISSUE TITLE
Wrong message given when Enable Password Reset via OTP enabled

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1660]
Currently as shown in the attached image, wrong error message given which does not match the actual situation. Since its a force password rest, at all time the user should be made aware of the fact. 

Current error message:
```
Login failed! Please recheck the username and password and try again.
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
