### ISSUE TITLE
When Logging in using multitenant user of a domain with an angular SPA, getting error "Failed to find the 'kid' specified in the id_token"

### ISSUE THREAD

**Issue by shubham16394** [wso2/product-is#16607]
**Describe the issue:**
When I am logging in as a super user created under carbon super admin with Applications permission I am successfully able to login and idToken is generated successfully, but when I create a tenant with the domain "xyz.com", under this if I create a user with "Applications" permission and trying to login with a sample Agular Single Page Application provided Asgardeo SDK, I m getting the error -

![image](https://github.com/wso2/product-is/assets/19387518/fd36d826-2855-4260-a8d1-6fc5d0378114)

Error -
`{
    "message": "Failed to find the 'kid' specified in the id_token. 'kid' found in the header: NWMzM2Y1MGIyZTIyNDgzNmU1MDg5M2U4NWM2OWVjNWZiNDcwMmQ4NDY4YjJhZDMwY2YwN2Q2YzA4ZmM5ZThjYw_RS256, Expected values: MDJlNjIxN2E1OGZlOGVmMGQxOTFlMzBmNmFjZjQ0Y2YwOGY0N2I0YzE4YzZjNjRhYmRmMmQ0ODdiNDhjMGEwMA_RS256",
    "name": "kid not found.",
    "code": "JS-CRYPTO_UTIL-GJFTIT-IV01"
}`

**How to reproduce:**
1) Create a tenant using carbon super admin, e.g. - xyz.com
2) Under this tenant create one user with "Applications" permission
3) Create a Service Provider using the tenant admin, configure the callback URL as - https://localhost:3000 in Inbound Authentication Configuration -> OAuth/OpenID Connect Configuration
4) Copy the ClientId and set it in the config of the Angular Application

`{
    "clientID": "PeVimgivbHjC3OS_exAca1K4tT8a",
    "baseUrl": "https://localhost:9443",
    "signInRedirectURL": "https://localhost:3000",
    "signOutRedirectURL": "https://localhost:3000",
    "scope": ["openid", "profile"]
}`

5) Restart the angular application and open https://localhost:3000 in a new browser
6) Provide the tenant user credentials which has "Applications" permission added to the role.
7) After providing the credentials the user will be redirected to the landing page of the application and the above error will be thrown in the browser's console

**Expected behavior:**
On successful login, idToken should be generated and displayed. e.g. -

![image](https://github.com/wso2/product-is/assets/19387518/3a9d44cc-95ff-45a7-9f9b-2c375c67605a)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: WSO2 Server 6.1.0
 - OS: Windows
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
