### ISSUE TITLE
FIDO authentication is not working for business apps

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16608]
**Describe the issue:**

$subject

FIDO authentication with the sample React app prints the following error log in the IS terminal.

```
[2023-09-06 16:28:58,020] [bb7b9adb-0747-488c-ac86-e2e516072e61] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Assertion failed while finishing the assertion to retrieve the assertion result.
```

**How to reproduce:**

1. Sign into the console
2. Create an application using the Single Page App template
3. Add FIDO2 to the first step in the sign in flow in the sign-in method
4. Sign into my account as a business user and register a passkey.
5. Configure the sample React app with the configs of the created application
6. Try to sign in to the react app using the 'Sign in with Passkey' option
7. You will be prompted to select a key. As soon as the key is selected, you are redirected back to the login screen.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.2.0-alpha4
 - OS: Mac
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Issue could not be reproduced in the latest distributions.
