### ISSUE TITLE
Improve DPoP to support specification

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#16606]
OAuth 2.0 Demonstrating Proof of Possession (DPoP) specification has been published recently [1]. We already have a soluction which developed from the draft phase of the specification [2]. We need to imporve the code base according to the released specification,

- [x] Identify the gaps with the draft spec and released specification
- [x] Improve the code according to the released specification

[1] - https://www.rfc-editor.org/rfc/rfc9449.html
[2] - https://github.com/wso2-extensions/identity-oauth-addons/tree/master/component/org.wso2.carbon.identity.dpop

**Comment by PasinduLakshan99** [comment]
### Feb16 2024

- created issue : https://github.com/wso2/product-is/issues/19606
- created issue : https://github.com/wso2/product-is/issues/19612
- Fixed issue : https://github.com/wso2/product-is/issues/19612

**Comment by PasinduLakshan99** [comment]
### Feb16 2024

- Made changes to the pull request : https://github.com/wso2-extensions/identity-oauth-addons/pull/120 to address the feedback received from a reviewer.
- Worked on the issue https://github.com/wso2/product-is/issues/19606).

**Comment by PasinduLakshan99** [comment]
### Feb 19 2024 (Mon)

- Changes to PR : https://github.com/wso2-extensions/identity-oauth-addons/pull/120  regarding error handling,log improvements.
- Worked on the issue : https://github.com/wso2/product-is/issues/19606

**Comment by Thumimku** [comment]
We are tracking supporting DPoP OOTB via https://github.com/wso2/product-is/issues/20428
