### ISSUE TITLE
[DOC] Onboard expired password identification API documentation

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#16611]
With the feature [1], the password expired users identification API is on-boarded to the product is. Need to improve the official IS-Serve doc space with the new API specification.
Updated yaml: https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.expired.password.identification/org.wso2.carbon.identity.api.expired.password.identification.v1/src/main/resources/ExpiredPasswordIdentification.yaml

[1]. https://github.com/wso2/product-is/issues/16529

**Comment by AnuradhaSK** [comment]
It's documented https://is.docs.wso2.com/en/latest/apis/password-expiring-users-identification-rest-api/
