### ISSUE TITLE
Fix unit tests in Identity-apps to match new ui changes

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#16619]
**Describe the issue:**
With the new UI improvements, unit tests are failing.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
We have enabled unit tests in the PR builder. Hence closing this issue as completed.
