### ISSUE TITLE
SCIM2/Me DELETE not implemented in IS 5.11 

### ISSUE THREAD

**Issue by Ushani-Athu** [wso2/product-is#16610]
**Describe the issue:**
The scim2/Me DELETE is not implemented in IS 5.11 but implemented in IS  5.10 and 6.0. This is documented in [1]. 

**How to reproduce:**
When executing the SCIM2/me DELETE API, it returns the following error response.

{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Self delete is not supported",
    "status": "501"
}

**Environment information** 
 - Product Version: IS 5.11.0

[1] - https://is.docs.wso2.com/en/5.11.0/develop/scim2-rest-apis/#/Me%20Endpoint/deleteUserMe

**Comment by lashinijay** [comment]
Closing this issue as proactive fixes and public fixes are already done.
