### ISSUE TITLE
Typo error in Jaas.conf file in Fresh IS 5.4.0

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1661]
In fresh 5.4.0 pack, we are having following typo error in jaas.conf file. 
Please make it correct as below.

**Incorrect one**
`Server {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=**tfalse**
storeKey=true
useTicketCache=false
isInitiator=false;
};
Client {
com.sun.security.auth.module.Krb5LoginModule required
useTicketCache=false;
};

**Corrected one**
`Server {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=false
storeKey=true
useTicketCache=false
isInitiator=false;
};
 
Client {
com.sun.security.auth.module.Krb5LoginModule required
useTicketCache=false;
};`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
