### ISSUE TITLE
[IS 7.0.0] Document Token exchange grant in IS

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#16616]
**Is your suggestion related to a missing or misleading document? Please describe.**
$subject

Related issues:

- https://github.com/wso2/product-is/issues/16386
- https://github.com/wso2/product-is/issues/16345

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
