### ISSUE TITLE
[Docs] Correct the documentation on updating an application by invoking the DCR endpoint

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#16613]
**Describe the issue:**
Currently in [docs](https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-dynamic-client-registration/#update-an-oauth-application) following curl is provided to update an existing OAuth application using the DCR endpoint.
```
curl -X PUT -H "Authorization: Basic <Base64_encoded_username:password>" -H
"Content-Type: application/json" -d '{
"redirect_uris":["<callback_url>"],
"client_name": "<application_name>",
"grant_types": ["<grant_types>"] }'
"https://<IS_HOST>:<IS_PORT>/api/identity/oauth2/dcr/v1.1/register"
```

However this returns `405 method not allowed` response. Doc should be updated to invoke the DCR endpoint with the client Id in the request path.

```
curl --location --request PUT 'https://localhost:9443/t/tenant1.com/api/identity/oauth2/dcr/v1.1/register/provided_client_id0001' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW5AdGVuYW50MS5jb206YWRtaW4=' \
--data '{
    "redirect_uris": [
        "https://client.example.org/callback"
    ],
    "client_name": "application1",
    "grant_types": [
        "password"
    ]
}'
```

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduDilshan** [comment]
However correct docs are there in [API docs](https://is.docs.wso2.com/en/latest/apis/use-the-openid-connect-dynamic-client-registration-rest-apis/)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
