### ISSUE TITLE
Doc Feedback: Use same set of sample values throughout the change hostname docs

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16620]
Location : https://is.docs.wso2.com/en/latest/deploy/change-the-hostname/

In Option 01 in the first step, a sample command is provided with the values to generate a certificate for the new  host name.

![Screenshot 2023-09-11 at 16 17 30](https://github.com/wso2/product-is/assets/41533942/a73a8189-9683-4a18-842a-88a315d20edd)

But in the second step, an entirely different set of values are used as sample values for updating the primary keystore configs.

![Screenshot 2023-09-11 at 16 18 35](https://github.com/wso2/product-is/assets/41533942/33358cc9-eb89-48c1-9e9c-0fd04cbcd515)

It'd be easier especially for the beginners if a same set of sample values had been used throughout the document, so that the cognitive load of manually finding the correct values from the previously entered sample command and updating the toml configs can be reduced.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
