### ISSUE TITLE
Prompt adaptive script function not properly working with remove_on_consume_from_api="true" config

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#16622]
Configure an adaptive script with the prompt function and try the authentication flow. 

```
var onLoginRequest = function(context) {
   executeStep(1, {
       onSuccess: function (context) {
           var username = context.steps[1].subject.username;
           prompt("genericForm", {"username":username, "inputs":[{"id":"fname","label":"First Name"},{"id":"lname","label":"Last Name"}]}, {
             onSuccess : function(context) {
                var fname = context.request.params.fname[0];
                var lname = context.request.params.lname[0];
                Log.info(fname);
                Log.info(lname);
             }
           });
       }
   });
}
```

The prompt function will work as shown below.

<img width="946" alt="Screen Shot 2023-09-11 at 7 38 45 PM" src="https://github.com/wso2/product-is/assets/24982871/4823ad84-4ad8-4e31-b231-7f291cb87b82">

Now add the following config (https://is.docs.wso2.com/en/latest/apis/use-the-authentication-rest-apis/) in the deployment.toml and retry the authentication flow after a server restart.

```
[authentication.endpoint.redirect_params]
filter_policy = "exclude"
remove_on_consume_from_api = "true"
parameters = ["ske"]
```

The input fields are missing in the UI as shown below.

<img width="894" alt="Screen Shot 2023-09-11 at 7 33 29 PM" src="https://github.com/wso2/product-is/assets/24982871/91e5289b-e332-458e-95c0-b65efb50ccf4">

If we remove `remove_on_consume_from_api = "true"` from the config and try the flow, then it works correctly. As per the analysis https://github.com/wso2/identity-apps/blob/master/identity-apps-core/apps/authentication-portal/src/main/webapp/dynamic_prompt.jsp#L55 becomes null when `remove_on_consume_from_api = "true"`

**Environment information:**
 - Product Version: wso2is-7.0.0-m2-SNAPSHOT
 - OS: Mac

**Comment by ashanthamara** [comment]
Closing the issue since the fix is deployed in the product-is ([4976](https://wso2.org/jenkins/job/products/job/product-is/4976/))
