### ISSUE TITLE
deployment.toml configurations missing on externalizing authentication endpoint document

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#16624]
**Is your suggestion related to a missing or misleading document? Please describe.**
The deployment.toml configurations to be added in WSO2 IS is missing in the [Host Authentication Endpoint on a Different Server](https://is.docs.wso2.com/en/latest/references/extend/host-authentication-endpoint-on-a-different-server/) documentation, which can be found in [IS 5.11 doc](https://is.docs.wso2.com/en/5.11.0/develop/hosting-authentication-endpoint-on-a-different-server/). 

**Describe the improvement**
The deployment.toml configurations that need to be added in WSO2 IS should be clearly indicated, and any other missing steps should be included to make this document comprehensive.

**Related Issues:**
#15721 #15714

**Comment by UdeshAthukorala** [comment]
Please find the Doc PRs for the fix of fix these issues.

- Master: https://github.com/wso2/docs-is/pull/3953
- IS 6.1: https://github.com/wso2/docs-is/pull/3960
- IS 6.0: https://github.com/wso2/docs-is/pull/3961

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
