### ISSUE TITLE
Resend-code API returns 501 error response

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#16626]
**Describe the issue:**
resend-code API returns 501 HTTP error response when the recovery information is unavailable on the IDN_RECOVERY_DATA. When we initiate any recovery flow, an entry gets created on `IDN_RECOVERY_DATA` table. If that entry got deleted (Due to clean up process or some other reasons) and someone tries to invoke the resent-code API to resend the recovery information back to the user, a 501 error response gets thrown by the API.

If this entry got removed by this table (due to the cleanup process or any other reasons), and 

**How to reproduce:**
1. Try out the Ask password flow. (or any other recovery flow)
2. Delete the entry that is getting created on the `IDN_RECOVERY_DATA` table after initiating the recovery flow.
`DELETE FROM IDN_RECOVERY_DATA WHERE USER_NAME = 'username'`;
3. Then try invoking the resend-code API to retrieve the recovery information.
Sample request:
```
curl --location 'https://localhost:9443/t/carbon.super/api/identity/user/v1.0/resend-code' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
  "user": {
    "username": "<username>",
    "realm": "PRIMARY"
  },
  "properties": [
    {
      "key": "RecoveryScenario",
      "value": "ASK_PASSWORD"
    }
  ]
}'

```

**Expected behavior:**
Instead of throwing 501, we should return a proper error message mentioning that recovery information is not available and reinitiate the recovery flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
