### ISSUE TITLE
Default email template for Password Reset via OTP does not reflect OTP specifically

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1663]
Currently both the default subjects and body text for Password Reset via Recovery Email and Password Reset via OTP contains the same subject and body text. Please change them to reflect difference between each other to make the first time user to use them with ease as well as to complete the user experience

![is_issue_3](https://user-images.githubusercontent.com/15624590/34097839-6f2e0f58-e400-11e7-870f-64951150b257.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
