### ISSUE TITLE
Remove error message text from document

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1664]
In [1] the Password Reset via OTP section carries the following sentence

`Log out of the dashboard and attempt to login again as the user you created above, "Tom". The login attempt will fail and a password reset will be prompted in the form of an error message saying "Login failed! Please recheck the username and password and try again".`

Please remove the error message as it's not needed for the user to continue with the flow and this makes the document tightly coupled with the UI and subjected to changed which are unwanted

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
