### ISSUE TITLE
Need to include samlsso_response jsp file in authentication portal

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16642]
**Describe the issue:**

samlsso_response.jsp, which is an intermediate loading page showing during the SAML SSO flows need to be added to the onprem authentication portal.

Currently, including it in the onprem authentication portal results in throwing NPEs [1] during the SAML SSO flows.

[1] https://github.com/wso2/product-is/actions/runs/6142237049

**How to reproduce:**

1. Add samlsso_response.jsp to the onprem authentication portal
2. Try out SAML SSO using the pickup-dispatch and pickup-manager apps

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
@pavinduLakshan need to address this issue (https://github.com/wso2/product-is/issues/16786) for saml sso login as well after adding this page into the authentication portal.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
