### ISSUE TITLE
Update the migration docs to note the h2-engine dependency upgrade

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16652]
**Describe the issue:**
Need to add a note in the migration docs noting that older versions of the h2 database would not be compatible with the new h2-engine. And the users who are affected should use the h2-migration-tool (https://github.com/wso2/samples-is/tree/master/h2-migration-tool) and migrate their data to the new databases.

**Comment by chamathns** [comment]
related https://github.com/wso2/product-is/issues/16438

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
