### ISSUE TITLE
[Doc] Information is not clear on setting up IWA in linux page.

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1665]
In step 04 under Setting up IWA section in [1], 

The following statement is not clear what it is asking to do.  Please clearly mentioned 
         1) How we can use the DNS tool to find the hostname (pointed link is not explaining it)
         2) As per my understanding DNS tool should run on windows server which AD is exist and 
           WSO2 IS is running on linux machine. Please explain clearly what needs to be done in order to achieve this step. 
        3) why we are having two domain names as idp.wso2.com and idp.is.local. Earlier we are asking to have same domain name in AD and WSO2 IS.

1) Register WSO2 IS using the same hostname (idp.wso2.com) in Active Directory. To do this, use the DNS tool on the machine that is running WSO2 IS to add an entry for the hostname (idp.is.local), and map it to the local ip address.

[1] https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
