### ISSUE TITLE
Enablement process of adaptive script does not work when there is a space in the WSO2 IS path

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#16655]
**Describe the issue:**

When there is a space in the path which the WSO2 Identity Server is located, the adaptive.sh file [1] does not properly get executed. However, it says that the enable process was success.

[1] - https://is.docs.wso2.com/en/6.0.0/guides/adaptive-auth/configure-adaptive-auth/#prerequisites

**How to reproduce:**

- Try to enable adaptive script when the WSO2 Identity Server exists in the path that contains a space.

**Expected behavior:**

It should work even if there are spaces and if it did not work properly, a proper error should be shown.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0
 - OS: Ubuntu 22.04.2 LTS
 - Database: H2
 - Userstore: JDBC

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
