### ISSUE TITLE
Provide support to localize custom text input via branding & give ability to customize the static content on Identity Server login UIs

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#16664]
**Is your feature request related to a problem? Please describe.**

ATM, we will have the following problems in IS login UI Branding when the capability is onboarded to IS Console.

1. Custom text (Copyright, etc.) added via Console's Branding doesn't change when the language is changed. (note that i've selected spanish)

  <img width="493" alt="Screenshot 2023-09-15 at 11 40 50" src="https://github.com/wso2/product-is/assets/25959096/fc2a4cfb-d47a-4573-a738-4291d55f2552">

2. There's no way to customize any static headers or other content in the login UIs.

Ex: If I want to change the `Sign In` heading to `Login`, i'm not able to do it easily without applying CSS hacks, etc.
 
   <img width="490" alt="Screenshot 2023-09-15 at 11 41 25" src="https://github.com/wso2/product-is/assets/25959096/f7bc1536-52fa-4118-96a0-6cff9d8087fe">

**Describe the solution you would prefer**

Implement a scalable solution that would support:

- Text Customization.
- Custom text localization.

**Comment by asekawa** [comment]
@brionmario  can you please verify this checklist

- [ ] Is this document impacted?
- [ ] Is the end-to-end (e2e) testing complete?
- [ ] Are unit tests available?
- [ ] Are integration tests available?
- [ ] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ] Have demo sessions been completed? (If yes, please attach the recording link)
- [ ] Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?
- [ ] 
- [ ]
