### ISSUE TITLE
[Doc] Typos in Configuring a JDBC User Store page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1666]
Type: Bug
Priority: High
Severity: Minor
Release: 5.4.0

Issues
1. The username used to connect **todatabaseand** perform various operations.
2. "Bulk Import Support" display name should be "Is Bulk Import Supported"
3. GroupSearchBase, GroupNameListFilter, or GroupNameAttribute are not properties used to configure JDBC user store as mentioned in the below para.
`When WriteGroups is set to false, it Indicates whether groups should be read from the user store. If this is disabled by setting it to false, none of the groups in the user store can be read, and the following group configurations are NOT mandatory: GroupSearchBase, GroupNameListFilter, or GroupNameAttribute.`

https://docs.wso2.com/display/IS530/Configuring+a+JDBC+User+Store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
