### ISSUE TITLE
STSHostName config is not templated in the carbon.xml.j2 file.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#16661]
**Describe the issue:**
In WS trust flow the issuer name can be set to a custom issuer[1] other than the server hostname by adding the following configuration in the carbon.xml inside the server tag.

 ```<STSHostName>STSHostname</STSHostName>```

This configuration cannot be added through the deployment.toml file since it is not templated in the <IS_HOME>/repository/resources/conf/templates/repository/conf/carbon.xml.j2 file

**Environment information** **:**
 - Product Version: [5.11.0]

[1]https://github.com/wso2-extensions/identity-inbound-auth-sts/blob/a39d7d59eb318e7c78871d9f7c426da261a1d9ae/components/org.wso2.carbon.sts/src/main/java/org/wso2/carbon/sts/STSDeploymentInterceptor.java#L158

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
