### ISSUE TITLE
Cofusing doc on JWT generation

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16673]
**Is your suggestion related to a missing or misleading document? Please describe.**
The access token issuer type JWT and the extension point (token_context_generator) described in this doc are two different aspects. It seems there is a mixture of both concepts in this doc [1]. Some content has to be moved to [2].

[1] https://is.docs.wso2.com/en/5.11.0/learn/jwt-token-generation/
[2] https://is.docs.wso2.com/en/5.11.0/learn/self-contained-access-tokens/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
