### ISSUE TITLE
Domain prepended super admin user will not see the assigned super admin internal role

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#16677]
**Describe the issue:**
When domain is prepended while logging into the management console, the Internal/{super_admin.admin_role} is not listed for the super admin user.

This is happening because of [1] conditional comparing [2]. The currentUser would be PRIMARY/admin if domain is prepended. But the getAdminUser() returns admin. Hence the !userRealmInfo.getAdminUser().equals(currentUser) conditional will be true for the Internal/admin role. Subsequently the role will not be added to the list.

Note: {super_admin.admin_role} refers to the deployment.toml specified super admin role,

**How to reproduce:**
1. log in as super admin user with domain prepended (ex: PRIMARY/admin),
2. list roles,
3. Internal/{super_admin.admin_role} will not be listed.

**Expected behavior:**
List the hybrid Internal/{super_admin.admin_role} under roles even when the domain is prepended,

**Environment information :**
 - Product Version: IS 5.11.0
 - OS: MacOs
 - Database: MySQL
 - Userstore: JDBC - Primary

**Suggestion**
currentUser = currentUser.replaceAll("(?i)primary/", ""); after [2]

[1] https://github.com/wso2/carbon-identity-framework/blob/b26f147535feca0747208752db7552932d7a9edf/components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/role-mgt.jsp#L578-L580
[2] https://github.com/wso2/carbon-identity-framework/blob/b26f147535feca0747208752db7552932d7a9edf/components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/role-mgt.jsp#L162

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
