### ISSUE TITLE
The sample custom mobile grant is confusing

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16675]
**Describe the issue:**
As per the PR [1], the sample mobile grant provided in doc [2] is returning just random random UUIDs as the access and refresh tokens. But it not useful at all for someone who is trying to build custom grant type to be used in real world. Instead, this should guide on building a real world usecase.

There has been another PR [3] merged which addresses the issue which was worked around by [1]. Shall we please revert [1] and remove related doc notes [4]?

[1] https://github.com/wso2/samples-is/pull/323
[2] https://is.docs.wso2.com/en/latest/references/extend/oauth2/write-a-custom-oauth-2.0-grant-type/
[3] https://github.com/wso2/samples-is/pull/321
[4] https://github.com/wso2/docs-is/pull/3087

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
