### ISSUE TITLE
Introduce the client_id parameter to the /oidc/logout endpoint

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#16671]
According to the OIDC RP-Initiated logout specification [1], the logout request at the logout endpoint can include several optional parameters. These parameters are:

- id_token_hint
- logout_hint
- client_id
- post_logout_redirect_uri
- state
- ui_locales

Within our current implementation, we have support for the following parameters:

- id_token_hint
- post_logout_redirect_uri
- state

The id_token_hint parameter contains the ID token that was previously issued by the server to the RP application. It is used internally to validate and resolve the client_id of the application. Subsequently, it is employed to validate the post_logout_redirect_uri with the callback_url registered for the application. According to the specification, the client_id parameter can be used to resolve the client ID of the RP application when the id_token_hint parameter is not present.

It's important to note that the oidc/logout endpoint supports both GET and POST requests. RP applications append the above parameters as query parameters when sending a GET request to the oidc/logout endpoint. Given that query parameters are accessible to request interceptors and can also be logged in server access logs, introducing the client_id parameter provides a more secure option to ensure the security of the logout process.

With this improvement, a new parameter `client_id` will be introduced. The clients can invoke the logout endpoint with this parameter when sending the logout request. If the client send the `client_id` parameter, they don't need to send the `id_token_hint` parameter. 

[1] - https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

**Comment by DMHP** [comment]
@Yasasr1 Can we please improve the issue body? The problem your trying to solve is not clear from he issue description.

**Comment by Yasasr1** [comment]
Proposed improvement was onboarded with the following PR
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2169

Closing the issue since the task is complete
