### ISSUE TITLE
[Doc] Adding  TOTP connector content in Multi-factor Authentication in section IS documentation

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1667]
In IS documentation  [1]  no section which cover's  **Multi-factor Authentication using TOTP**.  But related documentation is in IS connector docs space [2] . Link this documentation under,  **Multi-factor Authentication** in IS documentation
[1] https://docs.wso2.com/display/IS540/Multi-factor+Authentication+for+WSO2+IS
[2] https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
