### ISSUE TITLE
Evaluate Third-Party Dependencies for Compatibility with latest Java Patch Update

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16684]
**Describe the issue:**
Due to recent updates in Java patch version 11.0.20+8, stricter validation rules have been introduced which are affecting our application. We had to add the following properties to work around these restrictions:

```bash
-Djdk.util.zip.disableZip64ExtraFieldValidation=true  
-Djdk.nio.zipfs.allowDotZipEntry=true
```
These properties were added to skip the new validation rules, allowing our application to work with existing third-party dependencies.

Steps to reproduce:

    Update Java to version 11.0.20+8
    Run the application without the aforementioned properties.

Additional Context:

We initially added these properties as a workaround. The goal is to remove these properties once we can confirm that the third-party dependencies have been updated to comply with the newer Java version.

To Do:

- Evaluate the current third-party dependencies for compatibility with the Java 11.0.20+8, and Java 17 update.
-  Update the third-party libraries if newer versions are available that comply with Java's stricter rules.
- Test to make sure that the updated libraries work as expected with the new Java version.
- Remove the temporary properties (-Djdk.util.zip.disableZip64ExtraFieldValidation=true, -Djdk.nio.zipfs.allowDotZipEntry=true) once the application is confirmed to be stable.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
