### ISSUE TITLE
[Doc][Query] What is the use of TenantManager property when creating a JDBC user store

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1668]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

In the below doc there is a property named "TenantManager" and it does not have a Display Name. What does this property do. The description is not clear.
And where to map this in the JDBC user store creation page in the MC

https://docs.wso2.com/display/IS530/Configuring+a+JDBC+User+Store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
