### ISSUE TITLE
Logging in with Google for existing/new users in My Account does not show the user details within My Account

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#16699]
**Describe the issue:**
When attempting to log in with a Google account for an existing user (registered using the standard self-signup process) or new user in the My Account application, the login was successful. However, the user details and other options that should have been displayed in My Account were not shown. Below are screenshots of My Account after logging in with Google for an existing account.

Overview Page
<img width="1512" alt="Untitled" src="https://github.com/wso2/product-is/assets/74205483/89c50d83-b54c-4724-bb3e-3b9b17cf94b8">

Personal Info Page
<img width="1512" alt="Untitled" src="https://github.com/wso2/product-is/assets/74205483/f3e99f24-1f8a-4ae5-bad5-374e048fd037">

The following backend calls failed in each section of My Account,

- Overview Page
  - GET: https://localhost:9443/scim2/Me?attributes=urn:scim:wso2:schema.isReadOnlyUser
    - Status: 404
    - Response
      - `{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"User c3d1739b-d42d-42d0-9a8b-9ee15c7f5f06 does not exist in: PRIMARY","status":"404"}`
- Personal Info Page
  - GET: https://localhost:9443/api/users/v1/me/federated-associations
    - Status: 400
    - Response
      - `{
    "code": "UAA-10005",
    "message": "Error while getting associations of user: dilshanse99@gmail.com@carbon.super",
    "description": "The provided user identifier is invalid",
    "traceId": "37e7b58f-8ea5-442e-b6fd-ea50318d42e5"
}`
- Security Page
  - GET: https://localhost:9443/scim2/Me
    - Status: 404
    - Response
      - `{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"User c3d1739b-d42d-42d0-9a8b-9ee15c7f5f06 does not exist in: PRIMARY","status":"404"}`
  - GET: https://localhost:9443/api/users/v1/me/mfa/authenticators
    - Status: 500
    - Response
      - `{
    "code": "MFA-15003,",
    "message": "Unable to retrieve claims from the userstore",
    "description": "MFAService failed while trying to retrieve claim values from the userstore for the user : %s",
    "traceId": "a4a15be9-626e-4043-bb4e-5c510e16aa2f"
}`

**How to reproduce:**

- Setup IS 6.1.0 or IS 7.0.0
- Enable self sign up
- Use self signup to register a new user
- Enable google login for myaccount
- Use the same email address that was used to register the user mentioned above to log in to My Account using Google login

**Expected behavior:**
User details should be displayed correctly.

**Environment information:**
 - Product Version: IS 6.1.0, IS 7.0.0
 - OS: Mac
 - Database: Default
 - Userstore: Default

**Comment by mpmadhavig** [comment]
This issue could not be reproduced in the beta2 pack. Hence closing.

https://github.com/wso2/product-is/assets/47152272/ffd90eb3-f658-46e0-a8a7-1e5d212b18c4

**Comment by mpmadhavig** [comment]
Reopening when this was recorded, JIT provisioning was enabled.

**Comment by mpmadhavig** [comment]
The usage of MY ACCOUNT is users can manage their account-related preferences via this portal. The user will not be having any user related data in Identity Server if they are not provisioned to Identity Server. Hence the above mentioned calls will fail as such a user does not exist in the system.

**Comment by Thisara-Welmilla** [comment]
MyAccount app is for managing the user account. If the JIT provisioning is disabled, there will not be valid usercase to log in to MyAccount and no user detail are to display in MyAccount.
By default, we do not provide any federated IDP login option for MyAccount as well. If the JIT provisioning is disabled for a connector, developer should not add it as login option for MyAccount.

Additional note: If the JIT provisioning is enabled, login with federated option for existing/new users in My Account does show the user details within My Account as expected.
