### ISSUE TITLE
Update Documentation related to Twitter Authenticator

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16698]
The [current docs](https://is.docs.wso2.com/en/latest/guides/identity-federation/twitter/#set-up-a-twitter-app) related to configuring twitter as a federated IDP needs to be updated.

The app creation process has changed and therefore the current steps mentioned in the docs are outdated. 

Moreover, after creating an app the API key/secret for Oauth 1.0 and the Client ID/secret for Oauth 2.0 are now at the same page. 
<img width="628" alt="image" src="https://github.com/wso2/product-is/assets/47671237/e8205afc-146c-43ad-92af-046e89e707d9">

Since we need to enter the Oauth 1.0 API key and secret in our twitter configurations at the Identity Server, we need to clearly mention this, since a user can mistakenly add the Oauth 2.0 client id and secret instead.

**Comment by himeshsiriwardana** [comment]
This is completed with https://github.com/wso2/docs-is/pull/4372
