### ISSUE TITLE
[Doc] Default values for the JDBC user store properties are incorrect

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1669]
Type: Bug
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

Default values for the JDBC user store properties are incorrect.
- UsernameJavaRegEx
- UsernameJavaScriptRegEx
- RolenameJavaRegEx
- RolenameJavaScriptRegEx

https://docs.wso2.com/display/IS530/Configuring+a+JDBC+User+Store

**Comment by dilinisg** [comment]
This is applicable for all other user store documents as well.

https://docs.wso2.com/display/IS540/Configuring+a+Read-write+LDAP+User+Store
https://docs.wso2.com/display/IS540/Configuring+a+Read-write+Active+Directory+User+Store
https://docs.wso2.com/display/IS540/Configuring+a+Read-only+LDAP+User+Store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
