### ISSUE TITLE
Unable to configure a  custom domain name in the console app

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16703]
**Describe the issue:**

when changing the domain name of the console app , the authorized request failed due to callback url mismatch issue even though its correctly configured .

When analyzed it was noticed that the `serverOrigin` [1] doesn't update according to the given value in the `deployment.toml`.

[1] - https://github.com/wso2/identity-apps/blob/master/apps/console/java/org.wso2.identity.apps.console.server.feature/resources/deployment.config.json.j2#L83

**How to reproduce:**

Followed the  steps in the document
https://is.docs.wso2.com/en/latest/deploy/change-the-hostname/

https://github.com/wso2/product-is/assets/40081059/5c30c013-b6a1-4301-9eb4-eea261bc6f53

**Comment by pavinduLakshan** [comment]
Not reproducible with the latest pack (wso2is-7.0.0-m3-SNAPSHOT)

![Screenshot 2023-09-26 at 11 41 35](https://github.com/wso2/product-is/assets/41533942/9f27488c-a0a8-4fe5-9745-0ed9742cb203)

**Comment by pavinduLakshan** [comment]
Closing for now as it's not reproducible. Feel free to re-open otherwise.
