### ISSUE TITLE
Provide centralized CSS management support for branding

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16706]
**Is your suggestion related to an experience ? Please describe.**
In the current approach adding custom CSS related to branding user-facing UIs is achieved by adding the required CSS at the application level. Since this override should happen at a global level for an organization we suggest having a centralized approach to manage the CSS. With the unification effort, this experience should be available for Identity Server onprem product as well.

**Describe the improvement**

We would suggest to have a mechanism to resolve the CSS from a centralized location. Suggested approaches are given below

- In Asgardeo we can host the CSS file in the remote location and we can resolve it using the URL. In this approach on the onprem product we will have to resolve it using the relative file path.
- Provider CSS editor and encode the CSS and save it in the DB.

**Comment by jeradrutnam** [comment]
For IS 7.0 Alpha having an input field for Override CSS URL will be enough.

**Comment by DilshanSenarath** [comment]
Consider the requirement to have the centralised layout store when designing a solution for this. (https://github.com/wso2/identity-apps/pull/5078)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
