### ISSUE TITLE
[Improvement] Fix claim/user-attribute management issues in sub-organizations

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16702]
**Describe the improvement:**

When a B2B business uses the product as its IDP, it will need to define new user claims other than the OOTB-provided ones based on their application requirements. When the new claims are defined and used by a shared B2B application, those new claims need to be available to the sub-organizations of that business that use the application. Since the users who consume those applications reside in the sub-organization levels, their profiles will need to be configured with those claims.

**Comment by ChanikaRuchini** [comment]
Steps to verify:

1. All the claim management endpoints of the sub-organization without a GET endpoint should give a 403 Forbidden response with the following output
![Screenshot from 2023-10-10 10-14-37](https://github.com/wso2/product-is/assets/36252774/c27fa928-8552-4dda-ac9f-a5fb91e31e66)

2.  - create a sub organization.
     - create a b2b app and and share with sub organization.
     - Add a custom claim with oidc and scim mapping. 
     - Add that custom attribute to the application as requested attributes
     - call suborganization list local claims endpoint and list external claim endpoints and check whether the new claims are already added to the sub organizations.
     - Log in to the b2b app with a sub organization user. should be able to log into the app without any issues.

3.  - create a sub organization.
     - create a b2b app (don't share with sub organizations).
     - Add a custom claim with oidc and scim mapping. 
     - Add that custom attribute to the application as requested attributes
     - Then share the application with sub organization.
     - call suborganization list local claims endpoint and list external claim endpoints and check whether the new claims are already added to the sub organizations.
     -  Log in to the b2b app with a sub organization user. should be able to log into the app without any issues.

(Application flows should be checked with both oidc and saml)
    
4. update the custom local claim/ external claim in parent org. and check whether that claim is updated in the sub organization
5. Delete the custom local claim/ external claim in parent org. and check whether that claim is updated in the sub organization

**Comment by asekawa** [comment]
@ChanikaRuchini 

- [ ] Is this document impacted?
- [ ] Is the end-to-end (e2e) testing complete?
- [ ] Are unit tests available?
- [ ] Are integration tests available?
- [ ] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
- [ ] Have demo sessions been completed? (If yes, please attach the recording link)
- [ ] Does this change impact the on-prem environment only or required to be specifically onboarded to Asgardeo?

**Comment by asekawa** [comment]
This issue is QA rejected due  to https://github.com/wso2/product-is/issues/16910
(A sub org user can't login into a b2b app with mandatory claims enabled)
cc:@chamathns

**Comment by ChanikaRuchini** [comment]
Oidc application login flow with custom attributes

[Untitled_ Oct 18,2023 1_18 PM.webm](https://github.com/wso2/product-is/assets/36252774/617d257a-ed41-4af8-ae6b-2ed31f846119)


saml application login flow with custom attributes

[Untitled_ Oct 18,2023 1_24 PM.webm](https://github.com/wso2/product-is/assets/36252774/050fae9e-14cb-44f0-a40e-4d6a678fb19c)

**Comment by ChanikaRuchini** [comment]
This issue is completed
