### ISSUE TITLE
Continue button not working in SMS OTP verification page

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#16701]
**Describe the issue:**
When using SMS OTP as second factor in an application, `Continue` button is not working in SMS OTP verification page.
<img width="790" alt="Screenshot 2023-09-19 at 14 45 18" src="https://github.com/wso2/product-is/assets/56070320/9bd4403f-071b-4382-ba8b-a342ed66c8a8">

**How to reproduce:**
1. Create an application
2. Set the SMS OTP as second factor
3. Try to login by entering the OTP.

**Expected behavior:**
User should be logged in when pressing `Continue` button

**Current Behaviour**
`Continue` button does not respond

**Comment by JayaShakthi97** [comment]
When unifying authentication-portal, OTP fieldname been changed from `OTPcode` to `OTPCode`. Commonauth API accepts `OTPcode`.
Updated the SMS OTP JSP page's OTP field name.
- https://github.com/wso2/identity-apps/pull/4370
