### ISSUE TITLE
Improve extension points to support re-usability and extend apps with the new app versioning strategy

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#16707]
**Is your suggestion related to an experience ? Please describe.**
Publish necessary code sources to pull and rebuild extended apps for SaaS (Asgardeo). And improve the configuration and extension points to facilitate it. This is to avoid maintenance overhead for 2 product builds (SaaS and On-prem).

**Comment by JayaShakthi97** [comment]
This task is done along with the https://github.com/wso2/product-is/issues/16790 as extension points need to decided based on the onboarding feature improvements.
* Update - https://github.com/wso2/product-is/issues/16790#issuecomment-1744058606

**Comment by JayaShakthi97** [comment]
Extension points are implemented and integrated with both on-prem and cloud offerings. Since this is a code level improvement, unable to verify visually.
