### ISSUE TITLE
Consent purpose cannot be removed from the signup page

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#16704]
**Is your suggestion related to a missing or misleading document? Please describe.**
We can configure consent purposes for the signup flow from [1]. When a consent purpose is added to the flow, as for now that cannot be removed from the sign up form. This needs to be documented properly in the doc [1].

[1] https://is.docs.wso2.com/en/6.0.0/guides/consent-mgt/manage-consent-purposes/

**Describe the improvement**
Add a warning or note mentioning that the purpose cannot be removed once added to the sign up flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
