### ISSUE TITLE
Invalid characters appearing in the validation messages

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1670]
**Environment**
IS 5.4.0 - 2 node IS cluster fronted by Nginx
JDK - 1.8
DB - Mysql 5.6
OS - ubuntu 
Browser - Chrome - Version 58.0.3029.96

**Steps to recreate the issue**
1. Create a tenant user with invalid configuration parameters (ex: Provide blank content for mandatory field)

**Observations**
Error message contains <br/> chrachter 

![screenshot from 2017-12-18 14-52-06](https://user-images.githubusercontent.com/14962228/34098738-6264bfd0-e403-11e7-929a-b2977c684aff.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
