### ISSUE TITLE
Unify Asgardeo and Identity Server Documentation Experience

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#16711]
**Epic**
With the strategy of merging the two products' experiences.

Epic derived from: https://github.com/wso2-enterprise/iam-engineering/issues/630

**Description**
With the strategy of merging the 2 products' experience. It makes sense to merge the documentation as well and maintain the differences where necessary. So, that users will have a seamless experience across both products.

Asgardeo issue: https://github.com/wso2-enterprise/iam-engineering/issues/688

**Comment by ashensw** [comment]
- **Repository Changes:**
> - Both products docs now reside in the same repository [1].
> - The structure no longer features branches for each IS version; instead, all doc versions are organized as folders within the master branch.
> 
> > ```
> > - en
> >    - asgardeo
> >    - identity-server
> >       - 5.9.0
> >       - 5.10.0
> >       - 5.11.0
> >       - 6.0.0
> >       - 6.1.0
> >       - next
> >       - versions (will be renamed as 7.0.0 with the release and a new `next` directory will be created)
> >    - includes
> > ```
> 
> Note: The old master branch is renamed as `master-deprecated`.
> 
> WSO2 IS 7 documentation is available at [2], the folder name and the URL will be updated from `next` to `7.0.0` with the release.
