### ISSUE TITLE
[Improvement] Enable organization management for tenants

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#16712]
**Is your suggestion related to an experience ? Please describe.**

Currently, organization management is enabled only for the super tenant. But with the unification effort, we need to enable organization management for tenants of IS.

**Describe the improvement**

1. Tenant creation will be available only through APIs. Super admin is responsible for this.
2. During the tenant creation, we need to register the Console application for the tenant
3. Organization management is enabled for tenants
4. Now, tenants can create organizations from their console or from a B2B application, similar to super tenant
(Important: Organizations are always created from a B2B application perspective)

**Additional context**

**Comment by sadilchamishka** [comment]
### PRs

- https://github.com/wso2/identity-organization-management-core/pull/89
- https://github.com/wso2-extensions/identity-organization-management/pull/253
