### ISSUE TITLE
Doc Feedback: Twilio SMS URL is outdated

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16713]
Location : https://is.docs.wso2.com/en/latest/guides/mfa/2fa-sms-otp/

The SMS URL mentioned in the Twilio section is now deprecated [1]. The new URL should be `https://api.twilio.com/2010-04-01/Accounts/<AccountSID>/Messages.json`.

![Screenshot 2023-09-19 at 21 03 55](https://github.com/wso2/product-is/assets/41533942/ec0bf5f3-a0da-4e10-bfc8-84d10b762929)

[1] https://support.twilio.com/hc/en-us/articles/223181028-Switching-from-SMS-Messages-resource-URI-to-Messages-resource-URI-

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
