### ISSUE TITLE
Add missing SAML identity provider configuration

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#16718]
**Is your suggestion related to an experience ? Please describe.**
> We need to bring in missing SAML IDP configurations given below. Need to check and decide if all the configurations in the management console are required.

Already available

- [x] HTTP binding - already available in the new console
- [x] Include protocol binding - already included in the console
- [x] Additional query parameters

Currently not available in the new console (as of 20th, oct )

- [x] Attribute consuming service index - AttributeConsumingServiceIndex
- [x] Enable force authentication - ForceAuthentication
- [x] Include public certificate - IncludeCert
- [x] Include nameID policy - IncludeNameIDPolicy
- [x] Include authentication context - IncludeAuthnContext
- [x] Authentication context comparison level - AuthnContextComparisonLevel
- [x] SAML2 Web SSO user ID location - saml2_sso_user_id_location
- [x] Response authentication context class - ResponseAuthnContextClassRef
- [x] Enable assertion encryption - IsEnableAssetionEncription
- [x] Enable assertion signing - isEnableAssertionSigning
- [x] Enable artifact binding - ISArtifactBindingEnabled
   - [x] Artifact resolve endpoint URL - ArtifactResolveUrl
   - [x] Enable artifact resolve request signing - ISArtifactResolveReqSigned
   - [x] Enable artifact response signing - ISArtifactResponseSigned
 
- [ ] Authentication context class

![image](https://github.com/wso2/product-is/assets/30111554/363ba127-4812-40f7-a995-0e405fcd49fa) 
![image](https://github.com/wso2/product-is/assets/30111554/fd880f8c-5a4f-4d67-83e9-e6c288d15475)

- [x] The assertion signing config should be enabled by default as per the specification.

![image](https://github.com/wso2/product-is/assets/30111554/315337e0-d49d-4206-bfd9-387890f70b0f)

**Comment by pavinduLakshan** [comment]
Identified improvements will be tracked with https://github.com/wso2/product-is/issues/17690
