### ISSUE TITLE
Clear emailVerifyTemporaryClaim thread local variable during post add user event in the UserEmailVerificationHandler

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#16721]
**Is your suggestion related to an experience ? Please describe.**

The emailVerifyTemporaryClaim thread local variable is set at the pre-add-user event but not cleared after the post-add-user event. If the thread local variable is not cleared, there can be situations where pre-add-user event is not triggered in the current flow and based on the previously set pre-add-user event flow, current post-add-user event flow execute in erroneous flow.

**Describe the improvement**

Clear thread local variable in the post user event after using it.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
