### ISSUE TITLE
Create docs for adding new translations to identity apps

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16739]
**Is your suggestion related to an experience ? Please describe.**

Improve dev docs

**Describe the improvement**

Currently, there is no document that explains how to add a new translation to identity apps. If we had such a guide, we can point contributors who are interested in providing new translations to that doc.

**Additional context**

https://github.com/wso2/identity-apps/pull/4117

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
