### ISSUE TITLE
Add PAR endpoint to Info tab of console

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#16732]
**Describe the Issue:**
The PAR feature has recently been onboarded to IS. Accordingly, the PAR endpoint `https://localhost:9443/oauth2/par` should be added to the Info tab of OIDC applications in IS console.
The endpoint has been added to the Discovery endpoint as `pushed_authorization_request_endpoint`

### Related Issues
- Issue https://github.com/wso2-enterprise/iam-engineering/issues/568

**Comment by DonOmalVindula** [comment]
This feature was introduced with https://github.com/wso2/product-is/issues/16705
<img width="1440" alt="Screenshot 2023-10-31 at 14 46 42" src="https://github.com/wso2/product-is/assets/42619922/da40d922-3cd6-4da6-baff-17960456ffe9">
