### ISSUE TITLE
Improve audit log details in user creation flow

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#16737]
**Is your suggestion related to an experience ? Please describe.**

The user creation flow, such as self-registration or ask password, cannot be identified because identity claims are not logged in the audit logs.

**Describe the improvement**

Include identity claims as well in the audit logs. Hence, user creation flow can be identified using those claims.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
