### ISSUE TITLE
Unable to access the myacount 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16738]
**Describe the issue:**

Unable to access the myacount 
https://localhost:9443/myaccount
**How to reproduce:**

Try to access the https://localhost:9443/myaccount
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
    Product Version: [e.g., 7.0.0 M2 - https://github.com/wso2/product-is/releases/tag/v7.0.0-m2]
 - OS: [e.g., Mac]
 - 

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This will be fixed with https://github.com/wso2/identity-apps/pull/4105

**Comment by DilshanSenarath** [comment]
This problem has been resolved in this build - https://wso2.org/jenkins/job/products/job/product-is/4833/
