### ISSUE TITLE
[Doc] Update supported IS version for TOTP Authenticator

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1673]
IS 5.4.0  supported  TOTP Authenticator. Update in doc [1] as below 
`TOTP Authenticators are supported by WSO2 Identity Server versions 5.1.0, 5.2.0, 5.3.0, 540`

[1]  https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator

**Comment by Chankami** [comment]
There are multiple places in the doc which need to update  on latest version 5.4.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
