### ISSUE TITLE
Email OTP Authenticator fails with email configured under EMAIL OTP IDP

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#16735]
**Is your suggestion related to a missing or misleading document? Please describe.**

The documentation does not provide clear information on the email property available under the email OTP IDP configuration [1]. The relevant email property is used if any other OTP Provider is configured (GMAIL). However, if there is no intention to use APIs for OTP sending, and the email property is set, the Email OTP flow breaks without any indication of failures to the user (redirected to the login page).

**Describe the improvement**

Add a note stating the use of the email property under EMAIL OTP IDP configuration [1].

[1] https://is.docs.wso2.com/en/5.11.0/learn/configuring-email-otp/#configure-the-identity-provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
