### ISSUE TITLE
Add User UI component in IS Console is not Unified properly

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16731]
**Describe the issue:**

The UI components design does not support the unification standards
ex:placement of the generate password button
<img width="715" alt="Screenshot 2023-09-20 at 12 00 47" src="https://github.com/wso2/product-is/assets/40081059/87cacb5b-6d13-4179-a825-5d16a31cc519">

**How to reproduce:**

1.Visit the IS console
2.Go to user management
3. Click on "Add user"

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., 7.0.0 M2 - https://github.com/wso2/product-is/releases/tag/v7.0.0-m2]
 - OS: [e.g.,  Mac]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment]
@NipuniBhagya can you please verify if this is already done?
