### ISSUE TITLE
Scenario name of the security policy scenarios appeared as null 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1674]
**Environment**
IS 5.4.0 standalone pack
JDK - 1.8
DB - Postgres 9.6.3
OS - ubuntu 15.10
Browser - Chrome - Version 58.0.3029.96

**Steps to recreate the issue**
1. Go to Resident IDP -> nbound Authentication Configuration -> Security Token Service Configuration
2. Click 'Apply security Policy' and enable security
3. Select a security scenario to view details

**Observations**
Scenario name appeared as 'null'

![screenshot from 2017-12-18 15-12-05](https://user-images.githubusercontent.com/14962228/34099569-de250524-e405-11e7-89da-ccafcf91be12.png)

![screenshot from 2017-12-18 15-12-22](https://user-images.githubusercontent.com/14962228/34099573-e0876a8c-e405-11e7-87f9-8e9b15ed41e9.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
