### ISSUE TITLE
[Performance] DB CPU Utilisation Maxed out when requesting user attributes for a Test Flow

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#16744]
**Describe the issue:**
> Affected test flow - OIDC_Auth_Code_Grant_Redirect_With_Consent_Retrieve_User_Attributes

Obtain an access token and an id token using the OAuth 2.0 authorization code grant type.

> Requested user attributes - country, email, first name and last name

Response time against concurrency graph

![50_3000_lines](https://github.com/wso2/product-is/assets/59449070/ed071c4a-b6f1-4bbd-b60d-ade310d61c07)

RDS CPU Utilization

- Single Node 4 Core (maxed out in 500 concurrency)

<img width="468" alt="image" src="https://github.com/wso2/product-is/assets/59449070/e4f5627c-49e2-4d85-a4c9-a4c19322949e">

- Four Node 4 Core (maxed out in 300 concurrency

<img width="468" alt="image" src="https://github.com/wso2/product-is/assets/59449070/474baed8-6d18-47fa-a9f1-00bab9be0376">

<img width="468" alt="image" src="https://github.com/wso2/product-is/assets/59449070/8d649f6c-b953-4f0c-a49c-c4cda2776693">

<img width="468" alt="image" src="https://github.com/wso2/product-is/assets/59449070/bb881ed6-b96b-4fb1-87ca-b14b88ed6a38">

<img width="468" alt="image" src="https://github.com/wso2/product-is/assets/59449070/1a4d0a48-01ae-41e3-8c25-33d7365e3afa">

```
SELECT R.CONSENT_RECEIPT_ID FROM CM_RECEIPT R INNER JOIN CM_RECEIPT_SP_ASSOC RA ON R.CONSENT_RECEIPT_ID=RA.CONSENT_RECEIPT_ID WHERE R.PII_PRINCIPAL_ID= 'istestuser_647' AND RA.SP_NAME='app_984' AND R.PRINCIPAL_TENANT_ID=-1234 AND RA.SP_TENANT_ID=-1234 AND R.STATE='ACTIVE'
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - Database: MySQL
 - Userstore: JDBC

Test Parameter | Description | Values
-- | -- | --
Scenario Name | The name of the test scenario. | Refer to the above table.
Heap Size | The amount of memory allocated to the application | 2G
Concurrent Users | The number of users accessing the application at the same time. | 50, 100, 150, 300, 500, 1000, 1500, 2000, 2500, 3000
IS Instance Type 2 Cores | The AWS EC2 instance type used to run the Identity Server. | c5.large
IS Instance Type 4 Cores | The AWS EC2 instance type used to run the Identity Server. | c5.xlarge
RDS Instance Type | The AWS RDS instance type used to run the Identity Server. | db.m4.2xlarge
JDK version | The JDK version used to run the Identity Server. | JDK 11.0.15.1

deployment.toml config

```
[database.identity_db.pool_options]
maxActive = "500"

[database.shared_db.pool_options]
maxActive = "500"

[database.user.pool_options]
maxActive = "500"

[transport.https.properties]
maxThreads = "500"
acceptCount = "500"
```

**Related issues:**
> * https://github.com/wso2/product-is/issues/15460

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
