### ISSUE TITLE
Weird button placement in attributes page in unified console

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#16741]
**Describe the issue:**

![Screenshot 2023-09-21 at 10 42 12](https://github.com/wso2/product-is/assets/41533942/207acea2-f950-4be2-b6d0-742ec14d0c61)

**How to reproduce:**

Go to attributes > manage attribute mapping > OIDC or attributes > manage attribute mapping > SCIM

**Expected behavior:**

Button placement should be consistent with the other pages.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by jeradrutnam** [comment]
This was a conscious decision to move it here when there multiple tabs. When other dialects has and applied the same here. In fact we were thinking of all the other add button to same position with a style improvement. So, better we keep this as it is for now.
