### ISSUE TITLE
Missing the changes added with "Add login and identifier auth page changes" commit

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#16750]
**Describe the issue:**
After the PR https://github.com/wso2/identity-apps/pull/3931 got merged to the porduct, changes added with the PR https://github.com/wso2/identity-apps/pull/3924 had been got reverted. Hence the genericReCaptchaEnabled config is not getting checked when showing the recaptcha.

**How to reproduce:**
1. disable recaptcha.
2. enable generic recaptcha for identifier first.
3. recaptch won't be visible.

**Expected behavior:**
The recaptch should be available.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: master branch
 - OS:Mac
 - Database: H2
 - Userstore: jdbc

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
