### ISSUE TITLE
The language type and country (English - United states) is not incorrect aligment

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16757]
**Describe the issue:**

The language type and country (English - United states) is in incorrect alignment
<img width="907" alt="Screenshot 2023-09-21 at 16 29 51" src="https://github.com/wso2/product-is/assets/40081059/0fa4a26c-ce0d-4e82-80a0-6ded17071ee4">

<img width="292" alt="Screenshot 2023-09-21 at 16 30 18" src="https://github.com/wso2/product-is/assets/40081059/2e5cf958-5769-42be-be8d-b5d0eb2b4c40">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Not reproducible.

<img width="1479" alt="Screenshot 2023-10-11 at 11 59 43" src="https://github.com/wso2/product-is/assets/41533942/120e4d20-d4e4-4c02-ae95-ed6c945580ca">
