### ISSUE TITLE
Unable to configure an SMS OTP connection from New console.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16767]
**Describe the issue:**

On the connections page no option to create an SMS OTP connection

<img width="1512" alt="Screenshot 2023-09-22 at 13 00 17" src="https://github.com/wso2/product-is/assets/41188245/313f3904-4cdb-433a-bc50-de7fc3f784ec">

**How to reproduce:**

1. Go to the connections page in the react console
2. try to add a new SMS OTP connections.

**Expected behavior:**
An SMS OTP connection should be able to be created using the React console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
We populate the authenticators list by calling the `api/server/v1/configs/authenticators` API. But it does not return the SMS OTP authenticator. Therefore this should be enabled from the API to be visible in the Console connections page.

**Comment by asekawa** [comment]
Closing this issue , as we can now create a sms otp connection via the UI
