### ISSUE TITLE
[Doc] No enough information for create a service account in the Active Directory

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1676]
I'm following [1] for Configuring IWA on Linux. 

In step 5, Document is mentioning to create a service account in AD, but there's no reference or steps described on how to do that.
Please include those information in the document

[1] https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
