### ISSUE TITLE
Add Private Key JWT Client Authentication handler by default in IS

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#16766]
**Is your suggestion related to an experience ? Please describe.**
Private Key JWT Client Authentication handler is an extension that can be added to the Identity Server. We need to distribute this extension by default with the IS from the next release onwards.

**Describe the improvement**

**Additional context**

**Comment by asekawa** [comment]
- [ ] Is this document impacted? 

- [ ] Is the end-to-end (e2e) testing complete? 

- [ ] Are unit tests available? 

- [ ] Are integration tests available?
- [ ] Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)

- [ ] Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?

- [ ] Have demo sessions been completed? (If yes, please attach the recording link)

- [ ] Has the cloud readiness been verified?

**Comment by asekawa** [comment]
> * [ ]  Is this document impacted?
> * [ ]  Is the end-to-end (e2e) testing complete?
> * [ ]  Are unit tests available?
> * [ ]  Are integration tests available?
> * [ ]  Has this feature been tested on the latest Jenkins build after merging the changes? (Please Attach Proof, Screenshots, Screen recordings)
> * [ ]  Are all the relevant sub-tasks updated as complete (e.g., Cloud readiness tasks and migrations, docs)?
> * [ ]  Have demo sessions been completed? (If yes, please attach the recording link)
> * [ ]  Has the cloud readiness been verified?

@bhagyasakalanka can u please check on the list
