### ISSUE TITLE
Unable to Add Email OTP as First or Second Factor Step When Customizing Sign-in Method from Console

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16762]
**Describe the issue:**
The Email OTP connection is not listed in the UI to select it as the First or second factor in sign-in flow.

https://github.com/wso2/product-is/assets/41188245/ed457e02-23bd-4050-bec1-858d9a10fcd3

**How to reproduce:**

1. Create an Email OTP connection
2. Create an application
3. Redirect to Sign in method tab
4. Try to add Email OTP as the first factor in the sign-in flow.

**Expected behavior:**
The email OTP connection card should be visible in the options list 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 M2
 - OS: Mac
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Observed this in the Sign-in method editors as well. Selecting Email OTP as second factor from predefined flows doesn't work as expected.
![image](https://github.com/wso2/product-is/assets/37938529/b9df1c48-2729-4333-976f-533314c9ceaa)

In the authenticators response, email OTP is disabled. This could be the reason for breaking this flows in UI.
![image](https://github.com/wso2/product-is/assets/37938529/2709515f-3ae8-4577-8b7d-3a9a448cc95e)
