### ISSUE TITLE
Failure in loading scenario descriptions for some security policies

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1677]
**Environment**
IS 5.4.0 standalone pack
JDK - 1.8
DB - Postgres 9.6.3
OS - ubuntu 15.10
Browser - Chrome - Version 58.0.3029.96

**Steps to recreate the issue**
1. Go to Resident IDP -> inbound Authentication Configuration -> Security Token Service Configuration
2. Click 'Apply security Policy' and enable security
3. Select a security scenario to view details (select policy 17 to 20)

**Observations**
Failure in loading the security policy description.
![screenshot from 2017-12-18 15-16-33](https://user-images.githubusercontent.com/14962228/34099762-7512bcce-e406-11e7-8b18-ba9248acb5d6.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
