### ISSUE TITLE
Supported allowed_auth_handlers name is not specified 

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#16772]
**Is your suggestion related to a missing or misleading document? Please describe.**
We should mention all the available authentication handlers' names in this document [1]. Currently, we have only mentioned the sample value as BasicAuthentication but if someone wants to add the support for bearer token we haven't mentioned the handler name "OAuthAuthentication". We have to mention all the available handlers.

[1] https://is.docs.wso2.com/en/latest/apis/overview/#additional-configurations

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
