### ISSUE TITLE
Add UM_ATTR_NAME_VALUE_INDEX to performance tuning steps

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16774]
The following index is not shipped with <=5.10.0 versions, but it is useful when searching users by a given claim. Based on the usecases, this could become a blocker if it gets executed frequently.

```
CREATE INDEX UM_ATTR_NAME_VALUE_INDEX ON UM_USER_ATTRIBUTE(UM_ATTR_NAME, UM_ATTR_VALUE);
```

This can be added to https://is.docs.wso2.com/en/5.10.0/setup/performance-tuning-recommendations/

Also need to consider this as well https://github.com/wso2/product-is/issues/14204#issuecomment-1579935592

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
