### ISSUE TITLE
Remove user filtering column section 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16771]
**Describe the issue:**

There is a user filtering column section in the Users section, which does not support the unification.
Hence that can be removed

<img width="1296" alt="Screenshot 2023-09-22 at 14 27 00" src="https://github.com/wso2/product-is/assets/40081059/203e0769-f60e-463f-8ea9-adaa4a9d7395">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

-  Product Version: [e.g., 7.0.0 M2 - https://github.com/wso2/product-is/releases/tag/v7.0.0-m2]
- OS: [e.g., Mac]
- Database: [e.g., MySQL, H2]
- Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
@NipuniBhagya  this issue is marked as done in the sheet ? is this issue fixed
cc:@chamathns

**Comment by NipuniBhagya** [comment]
> @NipuniBhagya this issue is marked as done in the sheet ? is this issue fixed cc:@chamathns

It was decided to bring this to Asgardeo Console. Therefore we don't need to remove this functionality.

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest build.

<img width="1506" alt="Screenshot 2023-12-02 at 00 03 06" src="https://github.com/wso2/product-is/assets/41533942/044e7d8e-f1bb-4fbc-8fe4-2624133ce119">
