### ISSUE TITLE
Invalid `validate-code` API is pointed in "Enable Mobile Number Verification for an Updated Mobile Number" docs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16777]
**Is your suggestion related to a missing or misleading document? Please describe.**

The pointed `validate-code` API is not supported in this particular flow.
To validate the verification code sent to the user, use the existing validate-code and resend-code APIS of the [Self Registration REST APIs](https://api-docs.wso2.com/apidocs/is/is511/selfregister-v5.11.0/).

validate code: https://api-docs.wso2.com/apidocs/is/is511/selfregister-v5.11.0/#!/operations#SelfRegister#validateCodePost - Not supported in this flow

self validate code: https://api-docs.wso2.com/apidocs/is/is511/selfregister-v5.11.0/#!/operations#SelfRegister#meValidateCodePost - supported.

Correct the documentation.

**Additional context**
Reported the same issue in SO: https://stackoverflow.com/questions/77135111/wso2-identity-server-5-11-validate-code-api-not-working-as-expected 
Feature introduced with git issue:https://github.com/wso2/product-is/issues/9045
`/me/validate-code` API introduced to the purpose in PR https://github.com/wso2-support/identity-governance/pull/240

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
