### ISSUE TITLE
Application quick start section contains asgardeo specific sample applications

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16779]
**Describe the issue:**

The application quick start section contains asgardeo specific sample applications , including Asgardeo specific SDK .
Moreover, the UI s are also inconsistent and contains Asgardeo specific guiding information.

Ex:
<img width="1148" alt="Screenshot 2023-09-25 at 11 43 42" src="https://github.com/wso2/product-is/assets/40081059/303c2608-77b8-40bd-a202-d3b42018cbc2">

<img width="1148" alt="Screenshot 2023-09-25 at 11 43 42" src="https://github.com/wso2/product-is/assets/40081059/7354e9b0-0b41-46bb-8652-93b047f2fb92">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [[wso2is-7.0.0-m3-SNAPSHOT.zip](https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m3-SNAPSHOT.zip)]
 - OS: [e.g., Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
AFAIU, there are a couple of approaches we can consider to address this issue.

1. Move SDK repos to WSO2 / WSO2 Enterprise orgs and rename the SDKs to something generic (Eg: Asgardeo Auth React SDK @asgardeo/auth-react  -> WSO2 Auth React SDK @wso2/auth-react) - Then we can use the generic names in both IS and asgardeo sides, but this would take a significant effort, plus introduce breaking changes.

2. Hide the SDK Quickstart sections from applications in IS console - Would be the easiest to implement, but there will be a negative effect to UX.

**Comment by pavinduLakshan** [comment]
As discussed with the team, this is out of the scope of portal unification. Hence, closing for now.

**Comment by chamathns** [comment]
Hi @pavinduLakshan 

As you have mentioned, having the samples and SDKs in a generic repository would be the ideal solution. 
But given the urgency, I think we should remove/hide the references from the IS console and cover the quick start guides with the docs. Furthermore, the info tab should remain as it does not have any enterprise branding. 

re-opening this since this issue would be a blocker for the release given the business and legal complexities this would entail.
cc: @madurangasiriwardena @jeradrutnam

**Comment by NipuniBhagya** [comment]
Application quick start guide was removed with https://github.com/wso2/identity-apps/commit/0b2dd9ee67a071e109de125a1eb38391099794b7 as discussed.
