### ISSUE TITLE
krb5.conf file in product is not taken into account

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16776]
**Describe the issue:**

The properties set in the `IS_HOME/repository/conf/identity/krb5.conf` file are not taken into account.

The system variable name in KERBEROS_CONFIG_PROPERTY defined in the PR [1] should be corrected as  `java.security.krb5.conf`, not `java.security.auth.krb5.conf`.

The workaround is to set the correct system property as follows in JVM params when starting the product.
```
    -Djava.security.krb5.conf="$CARBON_HOME/repository/conf/identity/krb5.conf" 
```

With the JDK change done at [2]. this config file is important to apply the workaround of setting `allow_weak_crypto = true` in the krb5.conf

[1] https://github.com/wso2-extensions/identity-local-auth-iwa-kerberos/pull/42
[2] https://www.oracle.com/java/technologies/javase/11-0-17-relnotes.html#JDK-8139348

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by jcgarciaa** [comment]
Deployments using IWA authentication are affected by this issue.
