### ISSUE TITLE
Idle Account Suspension Email Template 

### ISSUE THREAD

**Issue by dinzie95** [wso2/product-is#16785]
From Identity Server 5.10 onwards, the template used for sending idle account locking emails is "`AccountLockFailedAttempt`". In the documentations, it is mentioned as "`AccountLock`"

[IS 5.10.0 Documentation](https://is.docs.wso2.com/en/5.10.0/learn/user-account-suspension/)
[IS 5.11.0 Documentation](https://is.docs.wso2.com/en/5.11.0/learn/user-account-suspension/)
[IS 6.0.0 Documentation](https://is.docs.wso2.com/en/6.0.0/guides/identity-lifecycles/suspend-accounts/)
[IS 6.1.0 Documentation](https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/suspend-accounts/)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
