### ISSUE TITLE
[Migration] Behaviour Change in getting OIDC claims retrival for client credential grant type

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#16788]
**Describe the issue:**
With https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2132/files,
OIDC claims were skipped in JWT token issuer for client credential grant type.

This can be reversed with following config
```
[oauth.grant_type.client_credentials]
skip_oidc_claims = false
```

Note that this is not recommended way to request OIDC claims via CC grant type. This config should be suggested to anyone previously using this behaviour and want to use it after migration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
