### ISSUE TITLE
Getting Asgardeo Logo as pre-loader.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16786]
**Describe the issue:**
The initial loading page to the IS console has the Asgardeo logo as the pre-loader.

https://github.com/wso2/product-is/assets/41188245/f40e665a-aee4-48c7-81b2-74bf01d26ddf

 
**How to reproduce:**

1. Download the latest IS build from Jenkins 
2. Start the Product IS 
You'll see the Asgardeo logo as the pre-loader.

**Expected behavior:**
Product IS logo should be visible.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [wso2is-7.0.0-m3-SNAPSHOT.zip](https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m3-SNAPSHOT.zip)
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
This issue will remain on hold until the necessary backend changes are provided. For more information, please refer to this issue (https://github.com/wso2/product-is/issues/16789).
