### ISSUE TITLE
Create group UI should be unified accordingly

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16787]
**Describe the issue:**

The existing Group creation UI is not properly unified

<img width="784" alt="Screenshot 2023-09-25 at 15 34 38" src="https://github.com/wso2/product-is/assets/40081059/b9690cd3-454a-4ab8-9283-ef6b55fec929">

It should be similar to a UI as follows
<img width="928" alt="Screenshot 2023-09-25 at 15 37 25" src="https://github.com/wso2/product-is/assets/40081059/70b912d9-e1ba-4be0-b639-31dcfab74b6d">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [[wso2is-7.0.0-m3-SNAPSHOT-src.zip](https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m3-SNAPSHOT-src.zip)]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
@DonOmalVindula Shall we close this issue as this should now be fixed with https://github.com/wso2/identity-apps/pull/4859?

**Comment by DonOmalVindula** [comment]
Yes... will close this issue
