### ISSUE TITLE
[DOC] Alignment issue should be corrected in user management page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1679]
Please correct the doc content for $subject. See attached for clear details.

Label: IS-5.4.0-update-1
Doc: [https://docs.wso2.com/display/IS540/Configuring+Users#ConfiguringUsers-Searchingforusers]

![search4](https://user-images.githubusercontent.com/15671620/34100057-4752e3bc-e407-11e7-99f9-15027558da5e.jpeg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
