### ISSUE TITLE
Redirecting to an invalid error page when attempting to switch to a disabled Suborganization

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16797]
**Describe the issue:**
Getting a 404 and an Invalid Tenant domain Error when a user tries to switch to a disabled Sub Org.

<img width="1512" alt="Screenshot 2023-09-26 at 15 31 30" src="https://github.com/wso2/product-is/assets/41188245/21c93d98-39b2-402e-8f35-80ce1c5c241d">

**How to reproduce:**

https://github.com/wso2/product-is/assets/41188245/b741740e-31f4-4cb8-b537-42f6ea4b77df

1. Create a Sub organization
2. Disable the created sub org
3. then try to switch to the disabled org

**Expected behavior:**
TBD

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
Need to disable the switch button, if the organization is disabled
