### ISSUE TITLE
[Doc] All the user store manager properties should specify the mandatory fields

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1680]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

All the user stores managers under this page have a table which describes the properties and their descriptions. Need another column specifying if this field is mandatory or not. This is really helpful when using admin services as we have to manual configure most of these properties

https://docs.wso2.com/display/IS540/Configuring+User+Stores

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
