### ISSUE TITLE
There's no User Account Locking feature.

### ISSUE THREAD

**Issue by SulakshanaBandara** [wso2/product-is#16809]
**Describe the issue:**
There's no lock users' account function

**How to reproduce:**
when go to the user account configurations there cant see a lock user account function.

**Expected behavior:**
There should appear a lock user account function.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0]
 - OS: [Linux]

**Comment by asekawa** [comment]
Closing this issue as the option is visible now in the UI
