### ISSUE TITLE
Issues in  JWT Secured Authorization Response Mode (JARM) for OAuth 2.0 Scenarions

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16804]
**Describe the issue:**

when testing JARM related scenarios , the following response mode and response type combinations didn't give the expected 
output

References
1.https://is.docs.wso2.com/en/next/references/concepts/authorization/jarm/
2.[JARM_Scenarios (1).pdf](https://github.com/wso2/product-is/files/12734288/JARM_Scenarios.1.pdf)

1.Verify in query.jwt response mode if response_type = token
 Page 13
 No error response is generated

2.Verify response_mode fragment.jwt navigates to Authorization Flow
Page 16

3.Verify the '#' Sign' authorization server need to send the authorization response as HTTP redirect to the redirect URI
Page 18

4.Verify in fragment.jwt response mode if response_type = code id_token
Page 19 

5.Verify in fragment.jwt response mode if response_type = none
Page 22
return an error saying that the response type is not supported

6.Verify authorisation flow with response method jwt and response type code id_token
Page 26
WT contains token - no jwt is generated

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [[wso2is-7.0.0-m3-SNAPSHOT-src.zip](https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m3-SNAPSHOT-src.zip)]
 - OS: [Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment]
> 
> when testing JARM related scenarios , the following response mode and response type combinations didn't give the expected output
> 
> References 1.https://is.docs.wso2.com/en/next/references/concepts/authorization/jarm/ 2.[JARM_Scenarios (1).pdf](https://github.com/wso2/product-is/files/12734288/JARM_Scenarios.1.pdf)
> 
> 1.Verify in query.jwt response mode if response_type = token Page 13 No error response is generated

This will. be fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2191

> 
> 2.Verify response_mode fragment.jwt navigates to Authorization Flow Page 16

This flow is working as expected.

> 
> 3.Verify the '#' Sign' authorization server need to send the authorization response as HTTP redirect to the redirect URI Page 18

This flow is working as expected.

> 
> 4.Verify in fragment.jwt response mode if response_type = code id_token Page 19

This flow is working as expected.

> 
> 5.Verify in fragment.jwt response mode if response_type = none Page 22 return an error saying that the response type is not supported

The given test scenario is incorrect. According to the spec, if response_type = none and response_mode = fragment.jwt, it should return a fragment JWT without any authorization info in the JWT.
refer: https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#none

> 
> 6.Verify authorisation flow with response method jwt and response type code id_token Page 26 WT contains token - no jwt is generated

This flow is working as expected.

>

**Comment by chamathns** [comment]
closing since fixed.
