### ISSUE TITLE
[DOC] Adding missing content to step  in TOTP Authenticator 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1681]
Under section **Deploying TOTP artifacts** in  [1] it mentioned to copy a war file as step1.
But that war files inside the other artifacts zip folder. It needs to be updated as below 

Place the totpauthenticationendpoint.war file which is inside the **other_artifacts folder** innto the <IS_HOME>/repository/deployment/server/webapps directory.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
