### ISSUE TITLE
`lastPasswordUpdateTime` or `lastPasswordChangedTimestamp` does not update when the password is changed by recovery

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#16810]
**Describe the issue:**
We have `lastPasswordUpdateTime` or `lastPasswordChangedTimestamp`  claims in IS as identity and local claims. Even though we change the password, these claims won't update unless the password expiry feature is enabled.

**How to reproduce:**
- Create a user
- Try password recovery
- Inspect the Identity DB/user DB and notice that the claim is not there.
- Enable password expiry
- Try password recovery
- Inspect the Identity DB and User DB and notice that the claim is not there.

**Expected behavior:**
- Update the last update claim despite of password expiry feature enabled of not.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
