### ISSUE TITLE
Directing to a null page when selecting the setup guide under sign-in methods

### ISSUE THREAD

**Issue by SulakshanaBandara** [wso2/product-is#16814]
**Describe the issue:**
In Google and Microsoft authentication under application sign-in methods there's a button as user guide and it directs to a null page.

**How to reproduce:**
1. Go the applications
2. Choose a application and select Google or Microsoft under "configure new connection" .
3. There can find the setup guide.

[null page.webm](https://github.com/wso2/product-is/assets/129736390/ee892e25-33f8-41c4-bbd4-c4949c7e8b76)

**Expected behavior:**
Not having a setup guide button.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0]
 - OS: [Linux]

**Comment by melanisilva** [comment]
Closing Duplicate Issue. -> [https://github.com/wso2/product-is/issues/16833](https://github.com/wso2/product-is/issues/16833)
