### ISSUE TITLE
Retrieve applications with filter param is not working with DB2 database

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#16811]
**Describe the issue:**
Sending GET query to retrieve applications with `filter` query param is not working correctly when DB2 database is configured. Results are not returned.

**How to reproduce:**
1. Configure identity database with DB2. https://is.docs.wso2.com/en/latest/deploy/change-to-ibm-db2/
2. Start the server
3. Create an application with a given client ID.
4. Send a get request to retrieve the applications with filter param (filter param: `clientId co "TEST_"`).
    ```
    curl --location 'https://localhost:9443/t/tenant1.com/api/server/v1/applications?filter=clientId%20co%20%22TEST_%22' \
    --header 'Accept: application/json' \
    --header 'Authorization: Bearer 960be8e0-f6d6-339b-ad70-087d8b2c9fd3'
    ```

**Expected behavior:**
Application should be returned.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 alpha
 - OS: Ubuntu
 - Database: DB2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
