### ISSUE TITLE
Magic Link Authentication is not working properly

### ISSUE THREAD

**Issue by SulakshanaBandara** [wso2/product-is#16818]
**Describe the issue:**
Doesn't receive an email when using  Magic Link Login Authentication. It ask to check the inbox in emails, but it won't work.

**How to reproduce:**
1. Configure  Magic Link Login Authentication for the application,
2. Try to sign-in through magic link authentication.

**Expected behavior:**
Email should be received after trying the magic link authentication.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0]
 - OS: [Linux]

**Comment by madurangasiriwardena** [comment]
Cannot reproduce with the given steps. Feel free to re-open if the issues persists with the exact steps to reproduce the issue.
