### ISSUE TITLE
Case sensitive when using filtering

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#16812]
**Describe the issue:**
When a user searches for an application, the search is case-sensitive; so the intended application will not be displayed. You can refer to the following video for more details.

https://github.com/wso2/product-is/assets/46097917/525b5022-f527-4fb9-abd2-b1131fc7f9c6

**Expected behaviour:**
Filtering should be case insensitive

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0.0 M3 (Reproducible in 6.1.0)
 - Database: H2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
