### ISSUE TITLE
Configurable hashing algorithm property for Public certificate created in multi-tenancy

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#16817]
**Describe the issue:**
In multi-tenancy, for each new tenant created, a key store is generated with a key pair. As of now, a less secure algorithm is hardcoded in [1] in this and a stronger hashing algorithm for the public certificate in the key pair generation process is required. 
A configurable property to define the hashing algorithm for public certificate created in multi-tenancy is required so that a stronger  hashing algorithm maybe used.

[1] https://github.com/wso2/carbon-multitenancy/blob/53c1ec02dde1dc58ca992e74d9f3ab0c46ec81b7/components/tenant-mgt/org.wso2.carbon.tenant.keystore.mgt/src/main/java/org/wso2/carbon/keystore/mgt/KeyStoreGenerator.java#L180-L184

**How to reproduce:**

**Expected behavior:**
Hashing algorithm should be configurable.

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by hwupathum** [comment]
```
[tenant_mgt]
signing_alg = "MD5withRSA"
```

List of supported algorithms
- SHA1withDSA
- SHA1withECDSA
- SHA256withECDSA
- SHA384withECDSA
- SHA512withECDSA
- MD5withRSA
- SHA1withRSA
- SHA256withRSA
- SHA384withRSA
- SHA512withRSA
