### ISSUE TITLE
Primary user store user's username get populated as the lastname 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1682]
In the default setup the primary user store user's username get populated in the lastname field in the user profile

![is_issue_4](https://user-images.githubusercontent.com/15624590/34101124-add18adc-e40a-11e7-872c-e891e309b944.png)

For the secondary user store user this does not happen

![is_issue_5](https://user-images.githubusercontent.com/15624590/34101162-cbadadd8-e40a-11e7-80be-a09b333d13c3.png)

Ideally the username should not get populated as the lastname in the default setup

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
