### ISSUE TITLE
project loading time

### ISSUE THREAD

**Issue by ghost** [wso2/product-is#16822]
after UI  changes in carbon file and run the server,  using this command ./api-manager.sh. project taking time to load 
I'm trying to change the carbon UI , after Project not running. 
![Screenshot from 2023-09-30 09-54-06](https://github.com/wso2/product-is/assets/116829871/3d326f6f-d3b5-45bd-9f47-b37c57e0a19d)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
