### ISSUE TITLE
Remove broken Doc links from console 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16833]
**Describe the issue:**
The console consists of broken doc links `Setup guide` in creating new connection UI through the Application `sign-in method` tab.

<img width="1512" alt="Screenshot 2023-10-02 at 15 15 29" src="https://github.com/wso2/product-is/assets/41188245/78620bc3-1b18-4331-b68c-52de35e5e918">

**How to reproduce:**

1. Create an application
2. Redirect to the `Sign in methods` tab 
3. click on the `Add Authentication` Plus button (+)
4. In the `Add Authentication` pop-up, click on `+ Configure New Connection`
5. In the listed connections options, there will be a `Set up Guide` 

https://github.com/wso2/product-is/assets/41188245/6e908698-2e6b-4161-8813-9b91bf01b79a

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  Identity Server-7.0.0-m3-SNAPSHOT
 - OS: mac
 - Database: H2
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
