### ISSUE TITLE
[Doc] Missing information in Configuring IWA on Linux page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1683]
Please include where to run the setspn commands in step 06 [1].  Sometime normal command promt is not allowing to this **setspn** commands. 

[1]  https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
