### ISSUE TITLE
The type of jit  provisioned user is not  displayed/not mentioned in the user

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16834]
**Describe the issue:**

when we configure a social login like Google , Apple etc  with jit provisioned user enabled. 
Even though the user is created in the users section the type of the jit provisioned user is not mentioned.
This type of the jit provisioned user should me mentioned in the UI

**How to reproduce:**

set up google as below
https://wso2.com/asgardeo/docs/guides/authentication/social-login/add-google-login/

or can set up Apple as follows
https://medium.com/identity-beyond-borders/integrating-sign-in-with-apple-into-your-asgardeo-applications-e25cda87ea38
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Not reproducible due to https://github.com/wso2/product-is/issues/16907

**Comment by asekawa** [comment]
@pavinduLakshan the issue is type of the jit provisoned user is not displayed! It should be mentioned whether the user is provisioned from Google , Apple etc

**Comment by pavinduLakshan** [comment]
It is intentional not to show the Identity Provider from which the user was provisioned in on prem console. This will only be available in the cloud offering.
