### ISSUE TITLE
Improve JWT Bearer Grant Documentation

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16830]
**Is your suggestion related to a missing or misleading document? Please describe.**
The current [documentation](https://is.docs.wso2.com/en/latest/guides/access-delegation/configure-jwt-grant/#configure-jwt-grant) to setup and try JWT bearer grant type is not sufficient and needs to be improved. 

**Describe the improvement**
There is a [blog](https://piraveenaparalogarajah.medium.com/try-out-jwt-bearer-grant-with-wso2-identity-server-d384b3c30579) that can be followed to try out this flow. But there are several improvements that needs to be done on this as well. 

In the blog, after adding the certificate to the IDP in the primary IS, the `Identity Provider's Issuer Name` should be added as `https://localhost:9444/oauth2/token` (the issuer of the trusted IS). By doing so, the first step of configuring the trusted IDP (adding the IDTokenIssuerID to identity.xml) can be skipped.

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
