### ISSUE TITLE
User emails are not displayed in the Console's user listing view even though email column is enabled

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#16840]
**Describe the issue:**
The Users listing view of the Console app allows selecting which attributes to be displayed in the view by selecting the required attributes from the 'Columns' dropdown. 
<img width="192" alt="Screenshot 2023-10-03 at 10 48 37" src="https://github.com/wso2/product-is/assets/25479743/164ae1d7-d4c8-479a-86ca-8fb5ea8670b8">
The drop down list contains 'email' and it is checked by default (not even editable). However, the user list view does not show the email address. Instead it shows the 'username' twice (Under the name of the user, and in another column).

In IS 7.0.0-m3

<img width="1728" alt="Screenshot 2023-10-03 at 10 51 46" src="https://github.com/wso2/product-is/assets/25479743/36ed69c3-be98-40c2-be9a-6dbc559a5ad1">

In IS 6.1.0.79

<img width="1725" alt="Screenshot 2023-10-03 at 10 56 11" src="https://github.com/wso2/product-is/assets/25479743/3b61c95c-79a5-498e-9e78-602321387fa4">

**How to reproduce:**
1. Create a user and update the profile with the name and email address
2. Go to Console app and list the users

**Expected behavior:**
The "email" should be displayed in the listing view.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0, IS 6.1.0, IS 7.0.0-m3

**Comment by aaujayasena** [comment]
Shall we update the issue status. If this is not ready with the IS 7.0.0-rc1, please update the milestone. Ex: https://github.com/orgs/wso2/projects/97/views/1 board "backlog" @chamathns

**Comment by DonOmalVindula** [comment]
<img width="1439" alt="Screenshot 2024-01-03 at 12 28 27" src="https://github.com/wso2/product-is/assets/42619922/6a70972f-e53c-4278-8fc0-855d24a71e45">

This is no longer reproducible as we have removed custom column dropdown from users section

**Comment by johannnallathamby** [comment]
How is this supposed to work with https://is.docs.wso2.com/en/latest/guides/authentication/multi-attribute-login/? There can be cases where username is a UUID and email address is not even used in the solution. We need some other unique attribute to show up in additional First name and Last name.

**Comment by DonOmalVindula** [comment]
During an offline discussion with @johannnallathamby, it was decided to include a function (probably a dropdown selection) to change the attribute displayed in the user list from `username` to whichever attribute that is configured in the multi-attribute login feature instead of custom columns

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/72
