### ISSUE TITLE
Login with email address using multi attribute login feature without appending the tenant domain to the email address

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#16849]
**Describe the issue:**

1. Get a fresh IS pack and enable 'multi attribute login' with 'http://wso2.org/claims/emailaddress' (Unique attribute config is added to the deployment.toml).
2. Try to login to MyAccount with an email address of a user.
3. The user cannot login with the email address because the email domain is identified as the tenant domain. The user can login by appending @carbon.super (or the specific tenant domain) to the email address. 

https://github.com/wso2/product-is/assets/25479743/d2f4418d-7034-4b10-88e7-fb08b45a34b9

This can be addressed by adding the below config to the deployment.toml. But this is not documented.
```
[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true
```

❗️Note : While this resolves not allowing the users to login without appending the tenant domain to the email address, adding this config overrides the UI (tracked with https://github.com/wso2/product-is/issues/14930) in IS 6.1.0 or below. In IS 7.0.0-m3, regardless multi attribute login is enabled or not, the field to enter the login identifier is labled as 'username'. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Tested with IS 6.0.0, IS 6.1.0, IS 7.0.0-m3

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by nachii** [comment]
This issue arises exclusively when the Service Provider is configured as a SaaS Application by enabling the corresponding flag.
