### ISSUE TITLE
Add documentation for Email OTP as First Factor

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#16845]
**Is your suggestion related to a missing or misleading document? Please describe.**

Email OTP as first factor was onboarded to the federated email OTP authenticator in IS. We need to add documentation for this feature.

Additionally, the local email OTP authenticator was introduced to IS which provides the same capability to configure email OTP as first factor. This #16339 should be taken into consideration when working on the above.

**Related Issue**
- https://github.com/wso2/product-is/issues/15581

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by melanisilva** [comment]
Could you please provide an ETA for this task?
@himeshsiriwardana @ashensw

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
