### ISSUE TITLE
Confirmation link has been sent to your email pop up displays in self-registration when confirmation is disabled

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#16842]
**Describe the issue:**
When the user self registration is enabled, but the account confirmation email sending is disabled, the user will created without sending a confirmation email. But the pop up Confirmation link has been sent to your email is still displayed to the user after self user registration completion.

**How to reproduce:**
1. Enable User Self registration from resident IDP. 
2. Disable account confirmation email sending by unticking Enable Account Confirmation On Creation, Manage notifications sending internally and Lock user account on creation
3. Create Account for new user using self registration flow
4. Confirmation link has been sent to your email pop up will be displayed.

**Expected behavior:**
Confirmation link has been sent to your email pop up should not displayed. Instead user registration successful pop up needs to be displayed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.0.0

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
