### ISSUE TITLE
[DOC] [Highest] User count function for jdbc user store is not includede in the documentation

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1684]
As $subject, I have verified the doc pages [1], [2] & [3]; But I couldn't see the details for enabling user count. Please update the relevant pages for this.
User count will become enabled once I added a jdbc primary/secondary user store. 
Note : For primary user count property should be enabled in config file, for secondary it is there bydefault when adding via UI. See the attachment for more infor.

label: IS-5.4.0 Docs

[1] [https://docs.wso2.com/display/IS540/Configuring+a+JDBC+User+Store]
[2] [https://docs.wso2.com/display/IS540/Configuring+Secondary+User+Stores]
[3] [https://docs.wso2.com/display/IS540/Configuring+Users]

![user-count](https://user-images.githubusercontent.com/15671620/34101513-f3694318-e40b-11e7-8247-e3f82bbed15c.jpeg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
