### ISSUE TITLE
Inconsistent user identifiers in the Audit Logs

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#16851]
**Describe the issue:**
It is observed that currently in the audit logs of Identity Server 6.1, we are using several user identifiers to denote the same user. I have added some examples below.

Authenticated user in the data payload is denoted by username in some actions, and by username in some actions.

Here are some examples : 

**Username is logged in the audit log for Action : LoginStepSuccess** 
`
TID: [-1234] [2023-10-04 12:29:00,936] [4e8b2925-c1dd-438b-957d-225c04a8237c]  INFO {AUDIT_LOG} - Initiator : frank123 | Action : LoginStepSuccess | Target : ApplicationAuthenticationFramework | Data : { "ContextIdentifier" : "f614e446-a6b5-44fd-aab3-e22c3ec02dad","AuthenticatedUser" : "frank123","AuthenticatedUserTenantDomain" : "carbon.super","ServiceProviderName" : "My Account","RequestType" : "oidc","RelyingParty" : "MY_ACCOUNT","AuthenticatedIdP" : "LOCAL","User Agent" : "null","RemoteAddress" : "null","UserStoreDomain" : "PRIMARY" } | Result : Success 
`

**Username is logged in the audit log for Action : StoreSession**
`
TID: [-1234] [2023-10-04 12:29:01,034] [4e8b2925-c1dd-438b-957d-225c04a8237c]  INFO {AUDIT_LOG} - Initiator : frank123 | Action : StoreSession | Data : { {"traceId":"4e8b2925-c1dd-438b-957d-225c04a8237c","RememberMe":false,"sessionContextId":"a80f34e9bf17473479379810b1ef3a2e4a7dcf023b4836a7f5b10d3f3d6452fd","AuthenticatedUserTenantDomain":"carbon.super","AuthenticatedUser":"frank123","LastAccessedTimestamp":1696418940956} } | Result : Success 
`

**UserID@tenant is logged in the audit log for Action : Login** 
`
TID: [-1234] [2023-10-04 12:29:01,050] [4e8b2925-c1dd-438b-957d-225c04a8237c]  INFO {AUDIT_LOG} - Initiator : 9f640340-9e90-4a15-a4c8-ff367cc70376@carbon.super | Action : Login | Target : ApplicationAuthenticationFramework | Data : { "ContextIdentifier" : "f614e446-a6b5-44fd-aab3-e22c3ec02dad","AuthenticatedUser" : "9f640340-9e90-4a15-a4c8-ff367cc70376@carbon.super","AuthenticatedUserTenantDomain" : "carbon.super","ServiceProviderName" : "My Account","RequestType" : "oidc","RelyingParty" : "MY_ACCOUNT","AuthenticatedIdPs" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3c28yIiwiZXhwIjoxNjk2NDE4OTQzOTM4LCJpYXQiOjE2OTY0MTg5NDA5MzgsImlkcHMiOlt7ImlkcCI6IkxPQ0FMIiwiYXV0aGVudGljYXRvciI6IkJhc2ljQXV0aGVudGljYXRvciJ9XX0.HnIu8dtceXA1f6v1NaUWBV7e7FOTZKmU0_3uuVx0__Q","User Agent" : "null","RemoteAddress" : "null","UserStoreDomain" : "PRIMARY" } | Result : Success 
`

**UserID is logged in the audit log for Action : PostTokenIssue (password grant flow)**
`
TID: [-1234] [2023-10-04 12:47:59,365] [a2990a17-b304-46c7-9f20-62e46479d80f]  INFO {AUDIT_LOG} - Initiator : harry123 | Action : PostTokenIssue | Target : PasswordGrantAuditLogger | Data : { "AuthenticatedUser" : "a3f31a1f-4e98-4e7c-810e-252869506ac5","AuthenticatedUserStoreDomain" : "PRIMARY","AuthenticatedUserTenantDomain" : "carbon.super","ServiceProvider" : "Mgt App","RequestType" : "oauth2","RelyingParty" : "V4nChvQMvEwSwISaOPwpqS6OIZoa" } | Result : Success 
`

**Expected behavior:**
A single user should be denoted by a unique identifier in all the audit logs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
