### ISSUE TITLE
[Migration] Support for managing API resources and securing access to API resources

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#16859]
### Describe the issue:
With support for managing API resources and securing access to API resource being introduced to IS, new database tables are introduced. 

Following tables need to be created in the `identity` database. 

- API_RESOURCE
- SCOPE
- AUTHORIZED_API
- AUTHORIZED_SCOPE

### Related Issue
https://github.com/wso2/product-is/issues/16344

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
