### ISSUE TITLE
Absence of configuration of recovery callback URL regex in the console

### ISSUE THREAD

**Issue by Shenali-SJ** [wso2/product-is#16852]
### Description
The configuration of the recovery callback URL regex pattern which is available in the management console should also be supported from the console.

Please note that this is available in the IS 6.1 beta console as well.

### Additional Context
Recovery callback URL regex configuration:
<img width="926" alt="Screenshot 2023-10-04 at 19 56 33" src="https://github.com/wso2/product-is/assets/66279520/9a96add1-0abb-4180-a149-dbca4df34898">

**Comment by brionmario** [comment]
@Shenali-SJ Is this issue still available?

**Comment by NipuniBhagya** [comment]
According to discussion, we had @ayshsandu @malithie @jeradrutnam @madurangasiriwardena, It was decided to remove this from the UI and give the support to update the regex from the API only.

cc: @brionmario @Shenali-SJ

**Comment by NipuniBhagya** [comment]
Closing the issue as this is no longer required.
