### ISSUE TITLE
Some mandatory parameters required to create a ReadWriteLDAP are under optional section

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1685]
Type: Bug
Priority: High
Severity: Major
Release: wso2is-5.4.0-update1

Some mandatory parameters required to create a ReadWriteLDAP are under optional section in MC
eg:
- GroupSearchBase
- GroupEntryObjectClass

Errors were returned when these parameters are omitted when creating a user store via admin services

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
