### ISSUE TITLE
Enable Password Expiration options via Password validation page is not working

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16861]
**Describe the issue:**
When trying to enable a password expiration option from the password validation page it gives a 404 error.

<img width="1512" alt="Screenshot 2023-10-04 at 22 34 37" src="https://github.com/wso2/product-is/assets/41188245/a6c91a06-245b-4d5a-8201-44b48db4c58b">

**How to reproduce:**

1. Log in to the react console
2. Go to Account Security under Organisation Settings
3. Select password Validation
4. Go to the Password Expiry option check the Password Expiry checkbox and enter the preferred duration
5. Click Update.

**Expected behavior:**
Enabling the option should be updated successfully. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
`PASSWORD_EXPIRY_CONNECTOR_ID` needs to be updated to match the unified implementation.

Fix:
- https://github.com/wso2/identity-apps/pull/4189

**Comment by chamathns** [comment]
@JayaShakthi97 can you please verify the fix and close the issue?

**Comment by JayaShakthi97** [comment]
This is fixed.
