### ISSUE TITLE
Hyperlinks for the user store manager class and domain name which are not really hyperlinks

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1686]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

Hyperlink effect for the user store manager class and domain name which are not really hyperlinks. 

![11](https://user-images.githubusercontent.com/1845370/34103539-0bff920e-e413-11e7-9629-10a839cae319.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
