### ISSUE TITLE
[Migration-Identity DB] Support application roles for Identity Server and support RBAC for apps

### ISSUE THREAD

**Issue by shashimalcse** [wso2/product-is#16865]
### Describe the issue:
Due to the requirement in https://github.com/wso2/product-is/issues/16363,
- added new tables 
  - APP_ROLE_ASSOCIATION
  - ROLE_SCOPE
- added column named `AUDIENCE_REF_ID ` column to `IDN_SCIM_GROUP ` table 
- changed unique constrain of table IDN_SCIM_GROUP to `UNIQUE(TENANT_ID, ROLE_NAME, ATTR_NAME, AUDIENCE_REF_ID)`

Schema PR : https://github.com/wso2/carbon-identity-framework/pull/4936

**Comment by shashimalcse** [comment]
added with : https://github.com/wso2-enterprise/identity-migration-resources/pull/315

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
