### ISSUE TITLE
Modify the error message received when user enters a invalid device code , 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16869]
**Describe the issue:**

Modify the error message received when a user enters an invalid device code , when trying to access the device verification endpoint
<img width="749" alt="Screenshot 2023-10-06 at 13 59 56" src="https://github.com/wso2/product-is/assets/40081059/1f60c20c-fb2d-4f06-be57-57d14c147467">

**How to reproduce:**

1.Login in to the console
2.Create a standard-based application
3.Enable device code as the grant type
4.Sends the device authorization request

```
curl -X POST 'https://localhost:9443/oauth2/device_authorize' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'client_id=<client_id>'
```

5.Access the device verification endpoint received from the above response using the web browser a
ex:
"https://localhost:9443/authenticationendpoint/device.do?user_code=yFjMHM"

6. Enter a invalid device code grant type and click on continue

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [[wso2is-7.0.0-m4-SNAPSHOT-src.zip](https://wso2.org/jenkins/job/products/job/product-is/4856/artifact/modules/distribution/target/wso2is-7.0.0-m4-SNAPSHOT-src.zip)]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by chamathns** [comment]
@pavinduLakshan can you please verify the fix and close the issue?

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest pack. Hence closing
