### ISSUE TITLE
Update docs for Private JWT client configurations

### ISSUE THREAD

**Issue by bhagyasakalanka** [wso2/product-is#16866]
**Is your suggestion related to a missing or misleading document? Please describe.**
Since we are packing private JWT client with IS-7.0.0, we need to update existing document.

**Describe the improvement**
- Remove sections related to downloading the connector as this will be available in IS-7.0.0
- Remove configurations related to connector as those will be available by default now

Doc Link: https://is.docs.wso2.com/en/5.10.0/learn/private-key-jwt-client-authentication-for-oidc/#!

**Comment by mpmadhavig** [comment]
Related issues:
- https://github.com/wso2/product-is/issues/20535
- https://github.com/wso2/product-is/issues/19949
- https://github.com/wso2/product-is/issues/15132

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
