### ISSUE TITLE
Count Implementation property will be automatically set when creating a JDBC user store, but does not behave correctly

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1687]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

**Steps**
1. Create a JDBC user store without configuring the Count Implementation property via admin services
2. Verify the properties of the created store from management console. The Count Implementation property will be internally set 
3. Check if the user counts are displayed for the user store from Users and Roles section

**Issue** 
The user counts will not shown for this user store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
