### ISSUE TITLE
Add a new configuration type to IDN_CONFIG_TYPE table in identity db

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#16878]
**Description:**
A new configuration to maintain organization-related configurations has been introduced with https://github.com/wso2/carbon-identity-framework/pull/4935. This has been done as part of addressing https://github.com/wso2/product-is/issues/16728

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
