### ISSUE TITLE
Add UM_ORG_DISCOVERY table to Shared database

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#16879]
**Description:**
To support the feature: https://github.com/wso2/product-is/issues/16379, a new table called UM_ORG_DISCOVERY has been introduced with https://github.com/wso2/carbon-kernel/pull/3678. This table needs to be added to the shared database.

Please note that in **mssql**, we have to delete UM_ORG_DELETE_TRIGGER and recreate it: https://github.com/wso2/carbon-kernel/pull/3678/files#diff-accf99af12e8c9f96677bf661a0ca70b7a7b0ea9c1b4633e53c5e4aa1daac7f2L792-R806

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
