### ISSUE TITLE
Missing grant types in protocol section of a standard based application

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16870]
**Describe the issue:**

grant types such as 

- ~SAML 2~
- ~jwt bearer~

**Update (09/10/2023)**: SAML2 and JWT Bearer grant types have been already added via https://github.com/wso2/product-is/issues/16715 and https://github.com/wso2/identity-apps/pull/4174. 

- IWA-NLTM

are not displayed in the UI of the protocol section of a standard-based application.

**How to reproduce:**

**Expected behavior:**

These grant types should be displayed in the UI to ne enabled.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build. 

https://github.com/wso2/product-is/assets/41533942/23ea869e-bcf5-4139-b585-c28665a51df6
