### ISSUE TITLE
Userinfo enpoint doesn't return userid claim sporadically

### ISSUE THREAD

**Issue by daoxxx** [wso2/product-is#16881]
**Describe the issue:**
I've added userid claim to the openid OIDC scope as per documentation. That is: 

- confirmed that local claim User id exist in the local dialect (`http://wso2.org/claims/userid` mapped to `scimid`)
- configured external claim mapping (`http://wso2.org/oidc/claim/userid` to `http://wso2.org/claims/userid`)
- added userid claim to the `openid` scope.
- in Service Provider added as a requested claim `http://wso2.org/claims/userid`

Now as I obtain access token for that Service Provider and invoke /oauth2/userinfo endpoint with that token **some day i get userid attribute in the answer, some day i don't.**
There's no clue in the logs.

I've suspected that this has something to do with consents [#2985](https://github.com/wso2/product-is/issues/2985#issuecomment-374506227). As we have 'Skip Login Consent` set. And account was created long time ago. And userid claim was added some time later.

But no. Create new account and you'll get the same effect: yesterday userid is there, today it's absent.

**How to reproduce:**
I don't know how to reproduce this. Seems like it's moon phase effect or something.

**Expected behavior:**
`userid` is returned by /oauth2/userinfo endpoint on every call.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 6.0.0]
 - OS: [Linux]
 - Database: [PostgreSQL]
 - Userstore: [JDBC]

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
