### ISSUE TITLE
After changing the offset, unable to access 'console/myaccount

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16887]
**Describe the issue:**
After changing the offset via deployment.toml, attempts to access 'console/myaccount' result in an error. 
 error message logs `[[2023-10-09 12:21:01,502] [4d30e12c-c100-4971-8bfb-7936cf1433a4]  WARN {org.wso2.carbon.identity.oauth2.authz.validators.AbstractResponseTypeRequestValidator} - Provided Callback URL does not match with the registered one.
].`
 This behavior was not observed prior to changing the offset. and still I can access management console 

**How to reproduce:**
    1.Change the offset via deployment.toml 
    2. Attempt to access 'console/myaccount'.

**Expected behavior:**
I should be able to access 'console/myaccount' without encountering any errors.

**Environment information*
Product  Version: 7.0.0-m3 (default userstore & other changes)
Java Version: 17.0.8.1
Operating System: Ubuntu & MacOS

```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offset = 3
```
![Screenshot from 2023-10-09 12-21-33](https://github.com/wso2/product-is/assets/39120228/1c4ea04a-58df-40e5-940c-d665d0ef8b07)

**Comment by chamathns** [comment]
duplicate issue: https://github.com/wso2/product-is/issues/10514

**Comment by NilukaSripalim** [comment]
This issue is closed, we can track the issue already created - https://github.com/wso2/product-is/issues/10514

**Comment by NilukaSripalim** [comment]
Tested and verified : wso2is-7.0.0-m4-SNAPSHOT
![Screenshot 2023-10-23 at 10 44 49](https://github.com/wso2/product-is/assets/39120228/8fe99ad8-0184-4c43-9250-34af9bd31f93)

![Screenshot 2023-10-23 at 10 42 57](https://github.com/wso2/product-is/assets/39120228/7b87d3b4-9386-439c-8e8c-9a1a5dbdb740)
