### ISSUE TITLE
getting 404 Browser console logs in My Account

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16886]
**Describe the issue:**
When logging into my account with the default super user credentials (admin:admin), I encounter browser log errors (404 - related to branding).

**How to reproduce:**
1. Login to My account with  default super user credentials (admin:admin)
Note: This is default pack, didn't change any configs

Product version - wso2is-7.0.0-m3
Java version  - 17.0.8.1
OS - Ubuntu
Browser Firefox
![Screenshot from 2023-10-09 10-10-18](https://github.com/wso2/product-is/assets/39120228/62233cf4-cf13-47ab-9eae-346b4bc4f82d)

**Comment by madurangasiriwardena** [comment]
I believe this is expected. We are checking if there is a branding configured for the tenant with the request. Since there is no branding available, we are getting this error response.
