### ISSUE TITLE
Absence of i18next localization for error messages in file picker component

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#16894]
**Describe the Issue:**

The File Picker component in the identity-apps repository does not utilize i18next localization for error messages. This omission could lead to inconsistent user experience in different locales, as error messages may not be displayed in the user's preferred language.

**How To Reproduce:**

1. Navigate to the [File Picker component](https://github.com/wso2/identity-apps/blob/master/modules/react-components/src/components/file-picker/file-picker.tsx) in the identity-apps repository on GitHub.
2. Examine the code and observe that error messages are hardcoded and do not utilize the i18next localization library.

**Expected behavior:**

Error messages within the File Picker component should be localized using the i18next localization library to ensure a consistent user experience across different locales.

**Device Information:**
 - Device (e.g. PC, iPhone6): Any
 - OS (OSX, Android, iOS): Any
 - Browser + Version: N/A (Source Code Issue)

---

### Optional Fields

**Related Issues:**

**Suggested Labels (for non-committers):**
bug, localization, i18next

**Suggested Assignees (for non-committers):**

---
### Testing Related Fields

**Local e2e Tests Status (Please attach the screenshots of the result):**

**Manual Test Plan (Please attach the document link):**

**Manual Test Plan Reviewed by:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
