### ISSUE TITLE
Console Access url in the administration section in incorrect

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16892]
**Describe the issue:**

Console Access url in the administration section in incorrect. It is directed to the carbon path instead of the carbon path
<img width="1250" alt="Screenshot 2023-10-09 at 16 07 46" src="https://github.com/wso2/product-is/assets/40081059/64beb3f0-0d63-47f3-b40c-483646321670">

**How to reproduce:**

1.Login to the console
2.Go to organizational settings =>adminstrators
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [[wso2is-7.0.0-m4-SNAPSHOT-src.zip](https://wso2.org/jenkins/job/products/job/product-is/4861/artifact/modules/distribution/target/wso2is-7.0.0-m4-SNAPSHOT-src.zip)]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest pack.

<img width="1507" alt="Screenshot 2023-10-16 at 08 50 37" src="https://github.com/wso2/product-is/assets/41533942/599eca4c-30cd-40d6-a5ff-253b87d93dc5">

<img width="1507" alt="Screenshot 2023-10-16 at 08 50 49" src="https://github.com/wso2/product-is/assets/41533942/027f50b1-ad6a-4d36-9c33-6ed60c964dff">
