### ISSUE TITLE
Restore behavior to use only numeric characters for Email OTP

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#16893]
**Describe the issue:**
We have done some improvements to the email otp authenticator so that it would work as first factor[1]. With this update the Email OTPs are sent as alphanumeric instead of the numeric code that were sent previously.

We need to preserve the previous behavior or properly send a warning and the update instructions to configure the email otp authenticator to behave as it did previously in the update summary.

[1]https://github.com/wso2/product-is/issues/15581

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
