### ISSUE TITLE
Stop usage of JWT access token as id_token_hint in OIDC logout

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#16895]
**Describe the issue:**
The JWT access tokens issued by the Identity server can be used as the id_token_hint in OIDC logout request. As per the OAuth specifications, you should pass the ID token for the 'id_token_hint' parameter[1]. But in case the jwt access token is passed it is accepted as well(because the azp claim that is used by the server to identify the SP is present in the jwt access token as well).

**How to reproduce:**

- Create an Oauth service provider with jwt token issuer.
- login to the service provider
- Issue the logout request with the jwt access token
- The logout is processed.

**Expected behavior:**
The logout should not be processed since the id token was not used. There should be a validation for the Id token.

**Environment information** **:**
 - Product Version: [IS-5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
