### ISSUE TITLE
Fix Broken "Run in Postman" Links in IS REST API Documentation

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16899]
**Is your suggestion related to a missing or misleading document? Please describe.**

It's been identified that some "Run in Postman" links within the IS documentation for REST APIs are not functioning as expected. For an example: https://is.docs.wso2.com/en/6.0.0/apis/idp-rest-api/. 

The underlying issue appears to be that these Postman collections were hosted on personal developer accounts, which are now inaccessible.

**Describe the improvement**

To rectify this, we have a couple of options:

- Move the Postman collections to a common WSO2 repository.
- Remove the broken links from the documentation until a more permanent solution is found.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
