### ISSUE TITLE
Branding is not applied to sub-organization sign in page

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16890]
**Describe the issue:**

Branding is not applied to sub-organization sign in page

https://github.com/wso2/product-is/assets/40081059/8d01d79e-71bd-41b2-bfaf-fba97760ee7a

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [[wso2is-7.0.0-m4-SNAPSHOT-src.zip](https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m4-SNAPSHOT-src.zip)]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dhaura** [comment]
The branding resolver caching issue is tracked by https://github.com/wso2/product-is/issues/16890.

Furthermore, in order to enable the branding resolver for sub-orgs in product-is, the following lines should added to the deployment.toml (because tenanted urls need to be activated, to resolve branding).
```
[tenant_context]
enable_tenant_qualified_urls=true
enable_tenanted_sessions=true
```

**Comment by asekawa** [comment]
@chamathns   @dhaura once we add the configs to the deployment.toml  its working as expected.However these 
changes should be merged ASAP inorder to assure the stability of the relevant functionalities

<img width="644" alt="Screenshot 2023-10-10 at 12 06 56" src="https://github.com/wso2/product-is/assets/40081059/d745e558-1c1d-4e2c-8403-379b26119218">

```
[tenant_context]
enable_tenant_qualified_urls=true
enable_tenanted_sessions=true
```

**Comment by chamathns** [comment]
tenanted URLs and sessions will be enabled with the alpha milestone. We are working on stabilizing the test suite to support these configs by default.
