### ISSUE TITLE
Please explain the reason for disabling orderId in IdentityMgtEventListener

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1689]
In [1] there is a statement to disable orderId. But the reason for the disabling is not given. Please provide an explanation to why the disabling is needed

[1] https://docs.wso2.com/display/IS540/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
