### ISSUE TITLE
[Migration] [7.0.0] Removing the existing config and Introducing a new configuration to specify public client support for grant types

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#16909]
With PRs [1] and [2], we introduced grant type level public client support. We introduced an array to mention the name of the grant types to support public client authentication as given below.

```
[oauth.public_client_support]
grant_type_names = ["customGrant1"]
``` 

With PRs [3] and [4], we improved the configuration where we introduced a property named `PublicClientAllowed` under `SupportedGrantType` configuration. The value of this property should be either true or false according to the requirement. An example configuration has given below.

```
[[oauth.custom_grant_type]]
name="customGrant1"
grant_handler="org.wso2.carbon.identity.oauth2.customGrantHandler"
grant_validator="org.wso2.carbon.identity.oauth2.customGrantValidator"
[oauth.custom_grant_type.properties]
PublicClientAllowed=true
```

**What has changed:**
1. With [5], we are **removing** the array configuration. If the array configuration is utilized to define public client supporting grant types, they should be added with the new property as mentioned above.
2. Default grant types defined within Identity Server has been added with the property and its default values. These values can be overridden through the deployment.toml. 
```
Note:
Hereafter, Public client support using client credentials grant type has been disabled by default.
```
3. If the customer has not added any grant types to the array configuration, all grant types would have supported public clients. If a customer is using a custom grant type for public clients, it should be explicitly configured as true for the new property.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2022
[2] https://github.com/wso2/carbon-identity-framework/pull/4467
[3] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2161
[4] https://github.com/wso2/carbon-identity-framework/pull/4905
[5] https://github.com/wso2/product-is/issues/16831

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
