### ISSUE TITLE
Properties section remains disabled for custom local attributes despite adding a mapped SCIM claim.

### ISSUE THREAD

**Issue by ChanikaRuchini** [wso2/product-is#16902]
**Describe the issue:**
Properties section always disable in custom local attributes although we added a mapped scim claim.

**How to reproduce:**
1. create a custom local claim with mapping scim claim.
2. try to edit the properties of added custom local claim.
3. It shows as disabled.
 
![Screenshot from 2023-10-10 09-55-00](https://github.com/wso2/product-is/assets/36252774/08ba9e93-47f7-453c-873b-e6dbd5dbf744)

**Expected behavior:**
If there is a mapped  scim claim this section should be able to edit.

---

**Comment by DilshanSenarath** [comment]
This change is available in the latest IS pack.
