### ISSUE TITLE
SCIM Custom Schema UI has UI/UX issues when all custom claims got deleted

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16915]
**Describe the issue:**
1. Get IS-7.0.0-m4-SNAPSHOT
2. Go to Attributes section. Go to Attributes tile
3. Click new Attribute creation.
4. Create a custom attribute with scim claim mapping and OIDC claim mapping
5. Go to SCIM attributes section, you will see the "Custom Schema" tab and added custom claim and it's scim claim mapping there.
<img width="1400" alt="Screenshot 2023-10-10 at 22 56 49" src="https://github.com/wso2/product-is/assets/25483865/c3bf5cf2-bd6f-424b-a829-810d45c71919">

6. Next delete all the scim claim mapping under "Custom Schema"
7. The following UI is displayed. `{{type}}` place holder needs to be fixed. Also need to have an option to add new scim custom schema claim

<img width="1029" alt="Screenshot 2023-10-10 at 23 00 09" src="https://github.com/wso2/product-is/assets/25483865/65298c9b-f8b1-43be-94c4-da7952deda4c">

**How to reproduce:**
mentioned above.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS-7.0.0-m4-SNAPSHOT

**Comment by jeradrutnam** [comment]
![image](https://github.com/wso2/product-is/assets/7569427/d60b2166-e0e8-4e8f-b309-d1c9e6230dfb)

Issue is no longer there in the IS 7.0 BETA 2 pack. But need to change text to `Add a SCIM Attribute`
