### ISSUE TITLE
recaptcha is not showing with multi option for max failed attempts

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#16917]
**Describe the issue:**

Recaptcha is not showing when user reached max failed attempts with multi option authentication is enabled. But recaptcha is prompt `max failed login attempts` + 1 is reached. But it prompt correctly when service provider is configured with Basic authenticator only.

**How to reproduce:**

- Configure `Prompt reCaptcha after max failed attempts` and `Max failed attempts for reCaptcha` in the resident Identity Provider under Login Policies --> Captcha for SSO Login
- Configure service provider with multi options login
- Provide incorrect password for login until it reaches max failed attempts configured in the above
- Recaptcha is prompt after max failed attempts +1 is reached.

**Expected behavior:**

Recaptcha should be prompt after max failed attempts is reached.

**Environment information** 
 - Product Version: [IS 5.10.0]
 - OS: [Linux,]
 - Database: [ H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ShehanDinuka** [comment]
When multi option is enabled, current authenticator is coming as null to handleAuthenticationStepFailure() method even if it is the basic authentication step. Hence, it does not go inside of the IF block[1] and not able to check the isMaximumFailedLoginAttemptsReached is resulting in not setting the recaptcha paramters in here[2].

[1] https://github.com/wso2-extensions/identity-governance/blob/v1.4.1/components/org.wso2.carbon.identity.captcha/src/main/java/org/wso2/carbon/identity/captcha/validator/FailLoginAttemptValidationHandler.java#L97 
[2] https://github.com/wso2-extensions/identity-governance/blob/v1.4.1/components/org.wso2.carbon.identity.captcha/src/main/java/org/wso2/carbon/identity/captcha/connector/recaptcha/SSOLoginReCaptchaConfig.java#L177

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
