### ISSUE TITLE
Connecting to a mysql server with ssl: provide information on how to disable ssl logs

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1691]
When connecting to secondary user store that uses mysql 5.7 following logs are displayed. It would be better if this logs can be hidden. Please point to a configuration

```
Mon Dec 18 17:10:08 IST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
