### ISSUE TITLE
Both email and  username fields are marked as mandatory when trying to create a new user , even though  email configured as  the username format

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16929]
**Describe the issue:**

When both email and alphanumeric fields are marked as mandatory when trying to create a new user, even though  email is  configured as  the username format

**Git issue** : https://github.com/wso2/product-is/issues/16323
**Local pack used :** https://drive.google.com/drive/u/2/folders/1UubS6-c-_-3lnp2TelO6yoYSBX5IcXkZ
**Reference documentation and use case :** https://docs.google.com/document/d/1aaCJ70OjAxICRMk72ctYDsG6khIfxojzu8OG0pBJGnY/edit

**How to reproduce:**

1.Go to the console
2.Go to account login =>Go to username-validation and set email as the username type.
3.Go to user management and try to create a new user
<img width="727" alt="Screenshot 2023-10-12 at 13 14 10" src="https://github.com/wso2/product-is/assets/40081059/5fcb9288-f0d9-4800-9960-bc274dd1279a">

Here both username  and email fields are marked as mandatory
**Expected behavior:**

Since we set email as the username no need to configure both
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by bhagyasakalanka** [comment]
We dont support email as username type by default in IS-7.0.0. This username input validation feature also disabled in IS-7.0.0. In the current console, we dont have the option to set username as email. So, the existing behavior should be correct.

**Comment by brionmario** [comment]
@asekawa Shall we close this issue if the behaviour is expected.
