### ISSUE TITLE
Migrate HTTP client to use system properties in Salesforce Provisioning Connector

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#1692]
System properties are not being picked up correctly by Commons HttpClient 3.x that we have in the current Salesforce Provisioning Connector v5.1.2. So need to migrate the HTTP client to HttpComponents HttpClient 4.x.

**Comment by ashensw** [comment]
Fixed with PR: https://github.com/wso2-extensions/identity-outbound-provisioning-salesforce/pull/16

**Comment by madurangasiriwardena** [comment]
Improvements added with https://github.com/wso2-extensions/identity-outbound-provisioning-salesforce/pull/17
