### ISSUE TITLE
Document the concept of Groups and Roles

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#16938]
The new APIs introduced via https://github.com/wso2/product-is/issues/8123 are documented in the API docs at [1]. But the concept of role and group separation [2] is not properly documented.

[1] https://is.docs.wso2.com/en/latest/apis/scim2-rest-apis/#/Roles%20Endpoint/getRole
[2] https://medium.com/identity-beyond-borders/manage-groups-and-roles-with-wso2-identity-server-5-11-0-onwards-93d42fe2f135

**Comment by ThaminduDilshan** [comment]
Need to document on the config to enable group role separation as well.
```
[authorization_manager.properties]
GroupAndRoleSeparationEnabled = true
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by rksk** [comment]
This is somewhat explained in the below docs
https://is.docs.wso2.com/en/latest/guides/users/manage-roles/
https://is.docs.wso2.com/en/latest/guides/users/manage-groups/
