### ISSUE TITLE
No validation while creating OAuth App with given client ID and secret 

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1693]
**Operating System:** Ubuntu 16.04
**Java Version**: Oracle JDK 1.8.0_144
**Packs**: IS 5.4.0 GA
**Setup**: Standalone Pack (Pack in a remote instance)

**Steps to reproduce**
1. Create OAuth app using admin service which will create OAuth app using given client id and secret.
Note: while creating OAuth app, give invalid client ID and client secrets.

**Expected Result**
It should not allow using any client id or secret. Should give an error.

**Actual Result**
It creates OAuth app with given client ID and secret.

**Note**: Tested for possible Cross-site Scripting (XSS) attacks using samples like "<body onload=alert('test1')>". Those giving 500 internal error due to parsing error. 

```
com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '(' (code 40) in start tag Expected a quote
 at [row,col {unknown-source}]: [11,49]
```
These errors should be validate in code level.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
