### ISSUE TITLE
Can not login in to the console when configure email as the username format

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16930]
**Describe the issue:**

Can not login in to the console when configure email as the username format , even if we use correct credentials

<img width="510" alt="Screenshot 2023-10-12 at 11 56 33" src="https://github.com/wso2/product-is/assets/40081059/45759965-94bc-4c81-83db-13298e602c41">

**Git issue :** https://github.com/wso2/product-is/issues/16323
**Local pack used  :** https://drive.google.com/drive/u/2/folders/1UubS6-c-_-3lnp2TelO6yoYSBX5IcXkZ
**Reference documentation and use case :** https://docs.google.com/document/d/1aaCJ70OjAxICRMk72ctYDsG6khIfxojzu8OG0pBJGnY/edit

**How to reproduce:**

1.Go to the console
2.Go to account login =>Go to username-validation and set email as the username type.
3.Logout from the console and try to login again
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thumimku** [comment]
Difference between previous email type user name config and current config is

Previous config ensures 2 things

- New user creation should validate email type username.
- All users in the tenant are email type.

With current EmailType Username config we can't ensure 2nd option. 
(Ex: It's possible that there can be users with usernames : sample and sample@test.com in the test.com tenant.)


To differentiate this, We need to take either one of following decisions,
- Tenant domain can't be in email domain format.
- There can't be users with email domain which is same as tenant domain.

Organisation features we are introducing is following first option. Organisation domain can't be email domain.

**Comment by bhagyasakalanka** [comment]
We disable username validation feature. Now, the username will be validated based on the userstore level regex
