### ISSUE TITLE
Username recovery document points to IS 5.3.0 for Customizing email templates

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1694]
In [1] the customizing email templates is pointed to IS 5.3.0 document. Please update

[1] https://docs.wso2.com/display/IS540/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
