### ISSUE TITLE
Issues in Concurrent Session Management Template

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#16946]
**Describe the issue:**
The `Concurrent Session Management Template` has the following issues:

- [ ] The script has two variables to collect info on the maximum session count, `maxSessionCount` and `MaxSessionCount`. In this case, we will have to instruct the users to enter the same information in both places. 

```
// This script will prompt concurrent session handling
// to one of the given roles
// If the user has any of the below roles, concurrent session handling will be prompted
// and it will either kill sessions or abort login based on number of active concurrent user sessions
var rolesToStepUp = ['admin', 'manager'];
var maxSessionCount = 1;

var onLoginRequest = function(context) {
   executeStep(1, {
       onSuccess: function (context) {
       // Extracting authenticated subject from the first step
           var user = context.currentKnownSubject;
           // Checking if the user is assigned to one of the given roles
           var hasRole = hasAnyOfTheRoles(user, rolesToStepUp);

           if (hasRole) {
               Log.info(user.username + ' Has one of Roles: ' + rolesToStepUp.toString());
                   executeStep(2, {
                       authenticatorParams: {
                            local: {
                                 SessionExecutor: {
                                      MaxSessionCount: '1'
                                 }
                            }
                       }
                   }, {});
           }
       }
   });
};
```

- [ ] The template's name is inconsistent with the other names under the conditional authentication templates.

![image](https://github.com/wso2/product-is/assets/84217321/19736994-bcb5-4903-b683-d0a9c104bc41)

- [ ] The buttons on the login screen are not aligned properly

![image](https://github.com/wso2/product-is/assets/84217321/88c50898-e827-45f6-bfa7-da31cf35321d)

- [ ] Selecting `Deny` also logs the user into the application.
https://drive.google.com/file/d/1JAIaxRxj2oRXh3hSErC8sjDM3MxP8j26/view?usp=sharing

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
