### ISSUE TITLE
PATCH operation for application's inbound auth configs

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#16948]
**Is your suggestion related to an experience ? Please describe.**
As of now we currently have only the PUT operation to update a certain inbound auth configs [1]. In order to update a single config, users need to get the whole object, do the change and call the PUT endpoint with the whole payload. If we introduce the PATCH operation we can simply update the values that we need without doing the whole object update. This issue is to track down the improvement.

[1] https://is.docs.wso2.com/en/latest/apis/application-rest-api/#/

**Describe the improvement**
Adding the PATCH operation for inbound auth config update.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
