### ISSUE TITLE
Update "Password recovery via user preferred channel" docs

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#16943]
**Is your suggestion related to a missing or misleading document? Please describe.**
Following two configs were introduced with the User Account Recovery v2 API. Hence, we need to update the configs at the 4th step of [Set up Password recovery](https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/extend-username-and-password-recovery/#set-up-password-recovery) section and update the image.

- Max failed attempts for password recovery - Number of maximum allowed failed attempts for an initiated recovery flow, Default: 3
- Max resend attempts for password recovery - Number of maximum allowed resend attempts for an initiated recovery flow, Default: 5

![image](https://github.com/wso2/product-is/assets/36252940/8104f35d-e375-4d79-9b24-4b2bfb341247)

Additionally, following minor bug should be corrected in the 2nd step at https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/extend-username-and-password-recovery/#password-recovery-flow

"The API prompts the user to select a channel from the available notification channels for receiving the **password** recovery notification."

**Related Issues:**
https://github.com/wso2/product-is/issues/16536

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
