### ISSUE TITLE
 [UI] Visibility and Alignment Issues in JDBC Secondary User Store Connection Edit Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16947]
**Describe the issue:**
The JDBC Secondary User Store Connection Edit page is experiencing visibility and alignment issues with a few UI elements. 
: Connection Password Element , Update connection , Driver Name

**How to reproduce:**
    Log in to the Consoleusing valid credentials.
    Go to User Store section under User Managemnt
    Click on the "JDBC Secondary User Store" tile.
    Create any Type JDBC UserStore
    Click on the "Edit" option for an existing JDBC Secondary User Store.
    Observe the visibility and alignment of UI elements on the Connection Tab.

**Expected behavior:**
All UI elements on the JDBC Secondary User Store Connection Edit page should be clearly visible and properly aligned

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT
 - OS: Linux
 - Userstore: JDBC
 - Browser Firefox 

**Linux(Ubuntu)**
![Screenshot from 2023-10-13 11-49-26](https://github.com/wso2/product-is/assets/39120228/59320574-1324-4b04-acdc-a14e91556ec9)

![Screenshot from 2023-10-13 11-50-36](https://github.com/wso2/product-is/assets/39120228/d4f1828b-fd33-46ee-ae55-10c7173f008a)

![Screenshot from 2023-10-13 12-25-33](https://github.com/wso2/product-is/assets/39120228/1d7aa39a-83a4-4f24-89d6-cd2da8f16ee3)

MacOS
<img width="1728" alt="Screenshot 2023-10-13 at 12 34 16" src="https://github.com/wso2/product-is/assets/39120228/3549348a-101a-49ad-a8df-168349089baf">

<img width="504" alt="Screenshot 2023-10-13 at 12 34 25" src="https://github.com/wso2/product-is/assets/39120228/f65b78f2-d929-4463-a053-b048131a1821">

---

**Comment by pavinduLakshan** [comment]
Closing since this will be tracked with https://github.com/wso2/product-is/issues/16950
