### ISSUE TITLE
Assigned Roles Disappear After Group Name Update, but Reappear Upon Reverting to Initial Name

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16956]
**Describe the issue:**
When a group's name is updated in a secondary user store in WSO2 Identity Server, the assigned roles are not displayed. However, upon reverting the group name to its initial value, the previously added roles reappear. 

**How to reproduce:**
    1. Log in to Console as an admin.
    2. Navigate to the "Groups" section.
    3. Edit an existing group in a secondary user store and update its name.
    4. Observe that the previously assigned roles are not displayed for the updated group.
    5. Revert the group name back to its initial value.
    6. Verify that the previously assigned roles are now visible for the group.

**Expected behavior:**
After updating the group name, the previously assigned roles should remain associated with the group in the secondary user store. Administrators should be able to view and manage these role assignments.

**Tested Environment information** 
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT
 - OS: Linux
 - Database: Primary MSSQL Secondary Postgres
 - Userstore:Secondary JDBC User Store 

[recording.webm](https://github.com/wso2/product-is/assets/39120228/f8b1f5bf-7e6f-470e-8313-19cd4066aa5f)

**Comment by ThaminduDilshan** [comment]
Should be fixed with the next kernel release
