### ISSUE TITLE
[UI] Organization SSO Connection Icon Display Issue

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16957]
**Describe the issue:**
There is an issue with the display of the organization SSO connection icon in the Connection List page. The icon is not rendering correctly.

**How to reproduce:**
    Log in to the console.
    Create an any application & enable Allow sharing with sub-organizations option
    Navigate to the connections section.
    Observe the display of the organization connection icons.

**Expected behavior:**
The SSO organization connection icon should be displayed correctly 

**Environment information**
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT
 - OS:Linux, Mac
 - Database: MSSQL
 - Userstore:JDBC

---

![Connections](https://github.com/wso2/product-is/assets/39120228/923185e8-5b08-40ce-a866-812ff5e7c97f)

![Screenshot from 2023-10-14 12-08-25](https://github.com/wso2/product-is/assets/39120228/c0c35469-c792-4201-bc2a-c4b77b32eea7)

**Comment by jeradrutnam** [comment]
Related: https://github.com/wso2/product-is/issues/17943

**Comment by jeradrutnam** [comment]
![image](https://github.com/wso2/product-is/assets/7569427/917a0a4a-120c-41f8-a4ee-c5e240fd743a)

Tested on BETA 2 pack and issue seems to be fixed by another task. Hence closing this.
