### ISSUE TITLE
Organization Administrators, Admin User List Displays as View-Onlybut it is Allowing Editing on Click

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16962]
Under the "Organization Administrators" section, the admin user list is currently displaying as view-only. However, once a user is clicked, it allows for the editing of the user profile. This behavior is inconsistent and not aligned with the expected functionality.

Issue 2: There is option to delete super admin as well 
![Administrators(2)](https://github.com/wso2/product-is/assets/39120228/18427992-0b7a-48b1-8c19-cf946adcd93b)

**Steps to Reproduce:**

1. Navigate to the "Organization Administrators" section.
2. Observe the user list, which should be in view-only mode.
3. Click on a user.

**Expected Behavior:**
The user list under "Organization Administrators" should remain view-only, even when a user is clicked.

- Product Version: wso2is-7.0.0-m4-SNAPSHOT
- Browser/Platform:FireFox
![Administrators(1)](https://github.com/wso2/product-is/assets/39120228/10947fe5-088c-4135-a2e8-0d92a3d261db)
[recording(3).webm](https://github.com/wso2/product-is/assets/39120228/5f5c2a6a-6247-4467-b891-d5e48329666e)

**Comment by brionmario** [comment]
This is invalid since it was moved to a new section -> `Console Settings`

<img width="1692" alt="Screenshot 2023-11-29 at 16 01 55" src="https://github.com/wso2/product-is/assets/25959096/d98ae466-3a3d-4b09-bd1f-7215589e8944">

**Comment by NilukaSripalim** [comment]
Due to the new UI implementation, this issue cannot be reproduced.
