### ISSUE TITLE
Bulk User import option is not  much visible 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16961]
**Describe the issue:**

Bulk User import option is not  much visible 
<img width="1254" alt="Screenshot 2023-10-14 at 15 48 29" src="https://github.com/wso2/product-is/assets/40081059/0903c3fc-d099-4b57-9500-d830f1380d99">

**Git issue** - https://github.com/wso2/product-is/issues/16935
**Testing issue** - https://github.com/wso2/product-is/issues/16945  

**How to reproduce:**

1. Login into the console using the below local pack
https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoMCpqP
2. Go to the user management section => users => Add user
3. Choose bulk import option

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
With the "Invite set of external users to register into the organization at once" effort "Bulk Import" text will be replaced as follow image. 

![multiple users](https://github.com/wso2/product-is/assets/61885844/c4c2fb9b-bb00-41fd-88e2-0e55956f776d)
