### ISSUE TITLE
The email to set  password is not sending (automatically), when users are onbaorded via the "bulk import" option

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#16963]
**Describe the issue:**

The email to set password is not sent (automatically), when users are onbaorded via the "bulk import".

**Git issue -** https://github.com/wso2/product-is/issues/16935
**The local build given below is used for testing-**
[https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoM](https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoMCpqP)

**How to reproduce:**

1.Login into the console using the below local pack
https://drive.google.com/drive/u/2/folders/1r-t8ek3TPl_oN7F3gT28fTZdCjoMCpqP
2.Go to the user management section => users => Add user
3.Choose bulk import option

**Expected behavior:**

An email to set the password should be automatically sent to the user email.

they askPassword option also set to true in the payload
<img width="1459" alt="Screenshot 2023-10-14 at 16 45 52" src="https://github.com/wso2/product-is/assets/40081059/d585d290-49e9-4944-aae2-119931ffb96d">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
Email sending is not triggered if the user onboarding based on invitation flow is not enabled . https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/invitation-workflow/#enable-the-invitation-flow

In IS, this config is not by default enabled.

For bulk user import feature to work enabling this config is required.
options:
1. For better UX, give a wizard to enable the invitation-based user onboarding before proceeding to bulk import
2. Document in the steps to enable invitation based user onboarding before working with bulk import

IMO we should go with option #10408

**Comment by PasinduYeshan** [comment]
Option 1 would definitely offer a better user experience. For the current phase, let's proceed with Option 2 and document the steps. In our subsequent updates, I'll collaborate with the frontend team to decide how this can be applied.

**Comment by PasinduYeshan** [comment]
This issue is addressed [here](https://github.com/wso2-enterprise/asgardeo-product/issues/20008).
