### ISSUE TITLE
"Organization Administrators" page provided console link is based on managent console not the console url

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#16960]
$subject
![Administrators](https://github.com/wso2/product-is/assets/39120228/6ae4196d-df24-47c4-b851-18c44afb94a9)

1. Login to console
2. Go to Organizational Settings
3. Click on Organization Administrators

**Comment by pavinduLakshan** [comment]
Duplicate of https://github.com/wso2/product-is/issues/16892
