### ISSUE TITLE
Username recovery:  Account Recovery REST API section refers to old documentation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1696]
In [1]  Account Recovery REST API option refers to an IS 530 document. Please update and focus the relevant section as the current loading is as below

![is_doc_5](https://user-images.githubusercontent.com/15624590/34104937-7f5839c2-e418-11e7-8e36-20b28cec91e4.png)

[1] https://docs.wso2.com/display/IS540/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
