### ISSUE TITLE
Add new column to the IDN_OAUTH2_ACCESS_TOKEN table and alter the CON_APP_KEY constraint

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#16976]
**Describe the issue:**

The organization bound access token feature is given with IS 7.0.0 by adding a new column `AUTHORIZED_ORGANIZATION` to the `IDN_OAUTH2_ACCESS_TOKEN` table. Also the `CON_APP_KEY` unique key constraint also need to be altered to include that newly introduced column.

**Comment by sadilchamishka** [comment]
After this migration, the tokens issued before the migration execution and the token received after the execution, should work.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
