### ISSUE TITLE
Unable to delete user Via console UI user profile page.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16978]
**Describe the issue:**
Unable to delete Users from user profile page delete user section.

<img width="1512" alt="Screenshot 2023-10-16 at 11 11 54" src="https://github.com/wso2/product-is/assets/41188245/3f8bee96-1da3-4dda-880e-561f03b2a866">

Note: The user deletion via the User List delete icon functions as expected.

### Analysis Of the issue:

Analyzed scopes of both successful and failed Delete requests;  no difference can be found between the two delete requests.
Since the request path couldn't be inspected, The issue could be related to the request path.

**How to reproduce:**

1. Go to the users page under the User Management Section
2. Select a user from the list or add a new user 
3. Try to delete the User from the selected User's profile page.

**Expected behavior:**
The user should be successfully deleted.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Identity Server-7.0.0-m4-SNAPSHOT
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This is fixed in the latest Jenkins build.

https://github.com/wso2/product-is/assets/41533942/9be31413-3a60-4983-986b-99b4f97146f2
