### ISSUE TITLE
[Setting Up Service Provider for Inbound Provisioning] Mention the way of invoking SCIM with "Access Token"

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1698]
**Documentation**: Setting Up Service Provider for Inbound Provisioning [1].

**Issue Identified**: Under the section "Testing the provisioning", it has a description of how to test SCIM using token. And it may ask to refer SCIM API for more information.

It should explain that we can add "--header "Authorization: Bearer 955fded39fc6cb08525b5f2a35b3e2e"" part as a replace of user. Because there is no any indication on SCIM API [2], how to use SCIM API with 
access token

[1] https://docs.wso2.com/display/IS540/Setting+Up+Service+Provider+for+Inbound+Provisioning
[2] https://docs.wso2.com/display/IS540/SCIM+1.1+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
