### ISSUE TITLE
"Configuring Cache Layers" link doesn't work in IS 6.1.0 docs

### ISSUE THREAD

**Issue by lahirugmg** [wso2/product-is#16990]
**Is your suggestion related to a missing or misleading document? Please describe.**
"Configuring Cache Layers" link doesn't work in IS 6.1.0 docs 
https://is.docs.wso2.com/en/latest/deploy/configure-hazelcast/

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
