### ISSUE TITLE
HYPR Authenticator UI doesn't align with the UI

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16993]
**Describe the issue:**
 
<img width="1319" alt="Screenshot 2023-10-16 at 16 19 25" src="https://github.com/wso2/product-is/assets/41188245/4cfbc6d3-0683-4992-9a79-8d3f70943117">

**How to reproduce:**

1. Configure HYPER Authenticator [https://docs.google.com/document/d/13Y3h9k3d1WSLOHwSuRx4JLbe9c3MahSxjhtfv5D92lI/edit#heading=h.b6b5qscuf6a3](https://docs.google.com/document/d/13Y3h9k3d1WSLOHwSuRx4JLbe9c3MahSxjhtfv5D92lI/edit#heading=h.b6b5qscuf6a3)
2. Add the authenticator to the sign-in flow.

**Expected behavior:**

The UI should be aligned with the rest of the login pages.
<img width="1131" alt="Screenshot 2023-10-16 at 14 35 39" src="https://github.com/wso2/product-is/assets/41188245/d5ec454e-6991-4d81-bfb3-fd24efca9753">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
