### ISSUE TITLE
[UX] Selecting user store domain at count user drop down list changed while selecting user store domain as "All" at user search

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1699]
Steps to recreate:
- Add two secondary jdbc user store
- Add user for jdbcstore1 and no users to other
- Select user store domain in the user search => works
- Select user store domain in user count => works
- Select "All user store domain" result the changes in user count's user store drop down
See attached.

label: IS-5.4.0-update-1 pack

![search5](https://user-images.githubusercontent.com/15671620/34105646-31269d4a-e41b-11e7-856e-74a0bf74fc0f.jpeg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
