### ISSUE TITLE
Getting something went wrong error when trying to navigate into users section

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17008]
**Describe the issue:**
Getting something went wrong error when trying to navigate into users section

<img width="1504" alt="Screenshot 2023-10-17 at 15 36 30" src="https://github.com/wso2/product-is/assets/40081059/c1253984-d44f-4f2a-b144-cc120f6e129e">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [https://wso2.org/jenkins/job/products/job/product-is/4871/]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
<img width="1107" alt="Screenshot 2023-10-17 at 15 47 23" src="https://github.com/wso2/product-is/assets/40081059/c49b2eef-3186-4e7e-b5e9-86328cd26175">

**Comment by PasinduYeshan** [comment]
The issue arises from a missing configuration. The problem has been addressed in the following pull requests:

- https://github.com/wso2/identity-apps/pull/4235
- https://github.com/wso2/carbon-identity-framework/pull/5014

**Comment by PasinduYeshan** [comment]
This issue is fixed from above PRs.
