### ISSUE TITLE
Deprecate `trusted-token-issuer` API endpoints

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#17009]
**Describe the issue:**
`/api/server/v1/trusted-token-issuers` endpoint was introduced to streamline managing the trusted token issuing IdPs in the identity server. This can be managed via `/api/server/v1/identity-providers` as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
