### ISSUE TITLE
Introduce M2M Application Template

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17006]
**Describe the issue:**

Currently there is no dedicated template for M2M authentication and authorisation. This introduces a confusion for the users as they need to enable the client credential grant in an application created using another template.

As a solution, we need to introduce a new type of application templates for M2M applications that will only have the client credentials grant (and Token Exchange grant) enabled. In this template type, user related configurations should be removed.

**Comment by asekawa** [comment]
@amanda-ariyaratne is there is a particular build version that we can test this feature , or else please do attach a version / build pack which we can test this feature within the eod.

**Comment by amanda-ariyaratne** [comment]
> @amanda-ariyaratne is there is a particular build version that we can test this feature , or else please do attach a version / build pack which we can test this feature within the eod.

Please test with this 
https://drive.google.com/file/d/102k7Zaqvzrt9bFmVkhY15NBI45L-EDUS/view?usp=sharing

**Comment by amanda-ariyaratne** [comment]
### Checklist to Verify

- The template should not contain any user related configurations such as User Attributes, Sign-in Method, Id token etc.
- If registered as a management application, the app credentials should be capable to retrieve a token that authorizes the management APIs.
- The M2M application should be able to subscribe for API resources. A token retrieved using the client ID and client secret should return all the scopes authorized for the application.
- An M2M application doesn't support sharing with sub-organizations from the UI but can be shared using the share API.
```
POST o/<main_organization_id>/api/server/v1/organizations/<sub_organization_id>/applications/<application_id>/share

Request body: {"shareWithAllChildren":false,"sharedOrganizations":["95bac261-92af-4765-9d16-107b5"]}
```
- A shared M2M application should be visible to suborganizations. Similar to the main application, user related configurations should not be available in the shared application.
