### ISSUE TITLE
Cannot enable the Verify the hostname option Remote Log Publishing

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17007]
**Describe the issue:**

Cannot enable the Verify the hostname option in Remote Log Publishing

https://github.com/wso2/product-is/assets/40081059/6f08eedb-1624-41b8-807c-bb9d8ced4bf1

**How to reproduce:**

1.Login in to the console
2.Go to remote logging function
3.Try to enable verify hostname option and click on update.
4.Navigate to another page and check the status of verify hostname option you can see that the option is still in disable state.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [https://drive.google.com/file/d/1aPLoG3Dnap-4Uk7jkXvbwK2jlqCHQmgy/view?usp=sharing]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This is now fixed in the latest Jenkins build.


https://github.com/wso2/product-is/assets/41533942/9c4c7ffb-e91a-4f22-8c6e-97e70583f550
