### ISSUE TITLE
UI issue in Group assigning tab , in  role section

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17017]
**Describe the issue:**

There is UI issue in Group assigning tab , in admin , manger role section.

<img width="1213" alt="Screenshot 2023-10-17 at 17 25 21" src="https://github.com/wso2/product-is/assets/40081059/cf757d35-d801-43fd-b5ab-cc916d810bea">

**How to reproduce:**

1.Login in to the console
2.Go to admin roles
3.Go to groups tab
you can see this UI if there are no any groups asigned

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
The fix is available in the latest Jenkins build.

![Screenshot 2023-10-23 at 20 09 13](https://github.com/wso2/product-is/assets/41533942/e7419aa4-cf80-4125-ae87-08ed67ecea33)
