### ISSUE TITLE
Getting an session expiry when deleting group that is assigned to admin role

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17013]
**Describe the issue:**

Getting a session expiry when deleting a group, which is assigned to a role.
This is occurring when the group is assigned to an admin role only

https://github.com/wso2/product-is/assets/40081059/3016d204-7245-4441-a02e-547ef796a44a

**How to reproduce:**

1.Login into the console
2.Create a group  and Assign admin as users
3.Assign the group into a role
ex:Admin role
4.Go to the groups section and try to delete the relevant group

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [https://wso2.org/jenkins/job/products/job/product-is/4872/]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
<img width="1512" alt="Screenshot 2023-10-17 at 17 09 30" src="https://github.com/wso2/product-is/assets/40081059/ccbe07f5-06e0-44bc-9630-895da60c7646">
<img width="1509" alt="Screenshot 2023-10-17 at 17 09 19" src="https://github.com/wso2/product-is/assets/40081059/e454b735-a61a-44b2-9aeb-f19ef4ba26c8">

**Comment by pavinduLakshan** [comment]
The group is successfully deleted, but the subsequent requests fail with 400/401 errors. It seems like the token is getting invalidated after the group where the logged in admin is a member of is deleted. No error log on the IS side as well.

**Comment by Thisara-Welmilla** [comment]
This session timeout only happens if the logged in admin user is also belongs to deleting group. When we deleting a group, the active tokens of that users in that group need to be revoked. 
Therefore in above scenario, getting session expired is expected. In the UI, we also displays the sign in option as well. Hence closing the issue.
