### ISSUE TITLE
Username recovery: update the image to reflect all three options selected

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1702]
In [1] only two of the mentioned options are selected. But altogether there are three options which are "Enable Username Recovery", "Enable Notification Internally Management" and "Notify when Recovery Success ". Since we are demonstrating a sample it's very important for the instructions and the images tally with each other

[1] https://docs.wso2.com/display/IS540/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
