### ISSUE TITLE
Email Magic link flow error message and the UI should be updated.

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#17023]
<img width="597" alt="image" src="https://github.com/wso2/product-is/assets/12690906/c2e179b0-5358-44bd-b57e-1bab8d0c5d27">

- [ ] The label and hint values should be updated as 'username'.

<img width="537" alt="image" src="https://github.com/wso2/product-is/assets/12690906/00d0d912-2065-46e6-b67d-2fb98d15e83e">

- [ ] The error message has masked the username. 'we sent to {User name} to sign in.' is not meaningful. So we need to update the value.

**Comment by pavinduLakshan** [comment]
This issue is no longer reproducible in the latest build.

https://github.com/wso2/product-is/assets/41533942/220ae9d1-df63-4613-8aa0-fbfdc161d334
