### ISSUE TITLE
Branding text section contains Asgardeo references

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17025]
**Describe the issue:**

The branding text section contains Asgardeo references.
<img width="1205" alt="Screenshot 2023-10-18 at 11 16 22" src="https://github.com/wso2/product-is/assets/40081059/224d3889-fee0-411b-8f0b-9f161a79fff7">

**How to reproduce:**

1.Login into the console
2.Go to branding section
3.Navigate to text section
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
Closing this issue as this is no longer reproducable

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest build, hence closing
