### ISSUE TITLE
Unable to authenticate user in the next attempt after an unsuccessful authentication when accountLock is enabled in custom tenant domain

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#17028]
## **Describe the issue:**
User authentication failing after entering correct credentials just after a wrong authentication when `accountLock` is enabled in custom tenant domain

https://github.com/wso2/product-is/assets/75057725/8a3a6d8e-e637-47e4-8fe4-3d609762f285

## **How to reproduce:**

1. Login to console
2. Create a custom tenant
3. Login to custom tenant using tenant admin credentials
4. Create user
5. Create application
6. Configure application with basic outbound provisioning
7. Enable accountLock in `ResidentIdp` (Identity Providers > Resident > Login Attempts Security > Account Lock)
8. Login to the application

## Steps to reproduce the behavior. 

1. Login with correct credentials of the user >> Successful authentication
2. Enter wrong credentials >> Unsuccessful authentication.
3. Enter correct credentials again >> Unsuccessful authentication.  << `User should be authenticated`
4. Enter correct credentials again >> Successful authentication. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0-m4]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by AnjanaSamindraPerera** [comment]
Tested the scenario with [wso2is-7.0.0-beta](https://github.com/wso2/product-is/releases/download/v7.0.0-beta/wso2is-7.0.0-beta.zip) and this is not reproducible. 

https://github.com/wso2/product-is/assets/38417165/6d195dfc-9b3f-469c-a87c-6004918f8227
