### ISSUE TITLE
Tenant login flow to management console fails once after enabling 'SAML2SSOAuthenticator'

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1703]
== Environment ==

IS 5.4.0 standalone pack
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate == 

1. Logged into IS and configure management console as the Service Provider by following 1-4 steps in [1]
2. Enable Service Provider as a 'SaaS Application' 
3. Go to 'Configure' and add a tenant (ex-tenant1.com with admin as 'admin1')
4. Follow 10-13 steps in [1] in order to enable 'SAML2SSOAuthenticator'
5. Start the server and go to management console.

*Scenario 1*

6. Login with tenant admin credentials (admin1@tenant1.com, where there's no user with that name in super tenant)

== Actual Outcome ==

'Authentication/Authorization Failure' Error message displayed in UI and below exception in backend

![authentication_authorization failure](https://user-images.githubusercontent.com/8849472/34106312-bc8bdfc4-e41d-11e7-9710-99e819378715.png)

``
WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  Failed Administrator login attempt 'admin1[-1234]' at [2017-12-18 17:40:35,628+0530]
``

== Expected Outcome ==

User should be successfully logged into the tenant1.

*Scenario 2*

7. Login with tenant admin credentials (admin1@tenant1.com, where there's a user -> admin1, with same name and password in super tenant)

== Actual Outcome ==

User logged into Super tenant as 'admin1' instead of tenant1 as 'admin1@tenant1.com'

== Expected Outcome ==

User should only logged into the tenant1.

[1] https://docs.wso2.com/display/IS540/Multi-factor+Authentication+for+WSO2+IS#Multi-factorAuthenticationforWSO2IS-Configuringmulti-factorauthenticationforWSO2IdentityServer

**Comment by madurangasiriwardena** [comment]
This error is coming since you have not enabled "Use tenant domain in local subject identifier" and "Use user store domain in local subject identifier" in the service provider config.
![image](https://user-images.githubusercontent.com/1332991/55132414-5fe74d00-5148-11e9-86d4-8769e6e637e6.png)
Docs need to be updated with this config
