### ISSUE TITLE
Allow organization creation only from immediate parent organization

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#17031]
**Describe the issue:**

- Organizations should be allowed  to be created from the immediate parent organization only. 

- Also the permission check for organization creation inside the organization creation service can be removed as the required authorization check is done at the authorization valve level.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
