### ISSUE TITLE
UI error when deleting a user from the sub organization 

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#17037]
Deleting a user from the sub organization results in the following view.

<img width="1725" alt="Screen Shot 2023-10-18 at 5 22 15 PM" src="https://github.com/wso2/product-is/assets/24982871/7260d99e-babf-49d9-9050-d5ac34d815a4">

Refreshing the page gives the correct view.

**Comment by NipuniBhagya** [comment]
Verified in the console version 2.2.0. Closing the issue as this is fixed.
