### ISSUE TITLE
[Migration][5.10.0-7.0.0 and above] Migrate the already configured OnlyNumericCharactersForOtp property for email OTP idp

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#17041]
**Describe the issue:**
The email OTP as first factor feature introduced to the wso2is-5.10.0 introduced a new governance connector property called `OnlyNumericCharactersForOtp`. This property will be using in wso2is-7.0.0 as `OnlyAlphanumericCharactersForOtp`. If the customer is already configured the email OTP federated IDP with this config, you need to reconfigure it here to what you configured already. 

**Intructions**
1. Goto the created email OTP federated idp.
2. Expand `Federated Authenticators`.
3. Expand `Email OTP Configuration` 
4. Check `Use alphanumeric characters for OTP` field if you want to recieve alphanumeric OTP.

**Related Issues:**
- https://github.com/wso2/product-is/issues/16893

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
