### ISSUE TITLE
Github Connection Setting Edit  section is empty

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17043]
**Describe the issue:**
Currently, when attempting to edit the GitHub connection settings, the Edit section appears to be empty. This means that users are unable to modify or update any GitHub connection configurations.

**How to reproduce:**
Navigate to the GitHub connection settings in the created github connection.

**Expected behavior:**
The Edit section for GitHub connection settings should display the relevant fields and options, allowing users to modify and update the GitHub integration configurations as needed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT (https://wso2.org/jenkins/job/products/job/product-is/lastSuccessfulBuild/artifact/modules/distribution/target/wso2is-7.0.0-m4-SNAPSHOT.zip)
 - OS: Mac
 - Database: H2
 - Userstore:JDBC

---

<img width="1491" alt="Screenshot 2023-10-18 at 18 40 33" src="https://github.com/wso2/product-is/assets/39120228/f0a574ac-c2c5-45c3-8970-42e794f877ab">

**Comment by NipuniBhagya** [comment]
Resolved with https://github.com/wso2/carbon-identity-framework/pull/5067
