### ISSUE TITLE
Updating standard based IDP logo functionality is missing in the unified console.

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17048]
**Describe the issue:**

$subject

In IS 6.1

<img width="1504" alt="Screenshot 2023-10-19 at 09 56 32" src="https://github.com/wso2/product-is/assets/41533942/0811c915-90a7-47ed-9288-6b9c7c653c6d">

In the latest pack

![Screenshot 2023-10-19 at 09 57 19](https://github.com/wso2/product-is/assets/41533942/8bdf51a5-3ddc-44e7-9e0c-5ec91e94c36e)

**How to reproduce:**
1. Sign into unified console
2. Create a connection from the standard based IdP template
3. Go to General section. The setting for updating the connection logo is missing.
4. Run a IS 6.1 pack and follow the steps 1 -2.
5. Go to General section. The setting for updating the connection logo is there.

**Expected behavior:**

Updating standard based IDP logo functionality should be there in the unified console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
