### ISSUE TITLE
The Logs type set into "All logs" , everytime it the page is refreshed [Remote Logging feature]

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17040]
**Describe the issue:**

The Logs type set into "All logs" , everytime it the page is refreshed [Remote Logging feature]

https://github.com/wso2/product-is/assets/40081059/cd6b5eab-2cee-4512-83ef-ee81bfdce491

**How to reproduce:**

1.Login in to the console
2.Go to remote logging feature
3.Set the log type into Carbon logs and update the other configurations
4.Refresh the page 
and you will see that the log type is set to All logs

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This is fixed in [@wso2is/console@2.1.5](https://github.com/wso2/identity-apps/releases/tag/%40wso2is%2Fconsole%402.1.5) and onwards.

**Comment by pavinduLakshan** [comment]
This issue wouldn't be reproduced in the latest jenkins build as the problematic dropdown has been removed with the latest revamp. Hence closing the issue as completed.
