### ISSUE TITLE
Username recovery: The email contains domain of the user store

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1705]
As shown in the below image, the email contains domain of the user store. But for an end user that information is not relevant. The default template that is packed with IS should be changed keeping different personas in mind, hence please remove the user store information from the template

![is_issue_6](https://user-images.githubusercontent.com/15624590/34106532-97116cc2-e41e-11e7-8797-f24e098893d5.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
