### ISSUE TITLE
Unable to retrive the suborganization list

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17057]
**Describe the issue:**

Unable to retrieve the suborganization list.

![Uploading Screenshot 2023-10-19 at 11.20.08.png…]()

Getting a 400 Bad Request in the ME endpoint.

https://github.com/wso2/product-is/assets/40081059/01eb3a12-6f96-4791-b1c7-27851d8bc562

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pamodaaw** [comment]
This is working fine in the latest pack.
<img width="1440" alt="image" src="https://github.com/wso2/product-is/assets/12439288/891042fa-476e-487d-8631-ed26f03f3977">
