### ISSUE TITLE
Missing Advanced Userstore Properties from Console UI

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17061]
**Describe the issue:**
There is a list of advanced properties missing from the new Console UI.

<img width="1511" alt="Screenshot 2023-10-19 at 12 27 48" src="https://github.com/wso2/product-is/assets/41188245/c207b89c-549e-448b-8d23-faf95a2d9b21">

**How to reproduce:**
Analyze the Properties available on the management console with the properties on the React console app.

**Expected behavior:**
Properties like `Immutable Attributes` etc are required to be on the react console side as well in order to successfully configure a userstore.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Identity Server-7.0.0-m4-SNAPSHOT
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Tracked with https://github.com/wso2/product-is/issues/17147
