### ISSUE TITLE
Role listing and user listing is not working during workflow creation

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17067]
**Describe the issue:**

Role listing and user listing is not working during creation of a workflow. It only lists `Internal/admin` or the `admin` user.
Also the search doesn't work when a domain is selected.

![Screenshot from 2023-10-19 15-37-08](https://github.com/wso2/product-is/assets/35653110/9ce98c7f-d478-4568-9c44-f44713fd2ade)

**How to reproduce:**
1. Login to management console and go to `Manage -> Workflow Definitions`
2. Check `Add` and enter a name
3. Click `Next` and then click `Add Approval Step`
4. Click on `Search Roles` button
5. Click the radio button and click `Search Users`

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
