### ISSUE TITLE
Unable to lock a user from the UI (Toggle button not functioning properly)

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17074]
**Describe the issue:**

When u try to lock a created user from the UI , it doesn't show that the user is in the locked state even if we enable the toggle.

https://github.com/wso2/product-is/assets/40081059/dd724922-a583-4ad9-bcbf-f385134c125a

even though in the UI it is said that the user is not locked , in the response accountLocked is said to true 
<img width="1259" alt="Screenshot 2023-10-20 at 10 00 48" src="https://github.com/wso2/product-is/assets/40081059/dda74e88-4a02-46d6-b6de-7d1d4456a63a">

**How to reproduce:**

1.Login into the console
2. Create a user
3. Go to the created user

Go and click on the lock User toggle button

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This issue occurs due to the API response returned by https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/users/components/user-profile.tsx#L244 [1] doesn't have the information about updated attributes.

[1] 
```js
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        "urn:scim:wso2:schema"
    ],
    "id": "2c8a3825-84cd-4b51-9ca4-ab40cfccacbb"
}
```

## Proposed solution

Instead of sending another API request, we might be able to use the existing `user` object to get the updated values.

```diff
-        getUserDetails(user?.id, attributes)
-            .then((response: ProfileInfoInterface) => {
-                console.log(response)
-                setAccountLock(response[ProfileConstants.SCIM2_ENT_USER_SCHEMA]?.accountLocked ?? false);
-              setAccountDisable(response[ProfileConstants.SCIM2_ENT_USER_SCHEMA]?.accountDisabled ?? false);
-                setOneTimePassword(response[ProfileConstants.SCIM2_ENT_USER_SCHEMA]?.oneTimePassword);
-            });
+        setAccountLock(user[ProfileConstants.SCIM2_ENT_USER_SCHEMA]?.accountLocked ?? false);
+        setAccountDisable(user[ProfileConstants.SCIM2_ENT_USER_SCHEMA]?.accountDisabled ?? false);
+        setOneTimePassword(user[ProfileConstants.SCIM2_ENT_USER_SCHEMA]?.oneTimePassword);
```

**Comment by pavinduLakshan** [comment]
This issue occurs because the onprem API response for retrieving user attributes does not have the requested user attributes.

**Comment by pavinduLakshan** [comment]
> This issue occurs because the onprem API response for retrieving user attributes does not have the requested user attributes.

The issue was actually due to. onprem SCIM configs had not been used in the console. Updating the SCIM configs fixed the issue. The fix is in https://github.com/wso2/identity-apps/pull/4309

**Comment by pavinduLakshan** [comment]
This issue is now fixed in the latest Jenkins build.


https://github.com/wso2/product-is/assets/41533942/0bef90bd-d817-46b8-84d1-67b94647a553
