### ISSUE TITLE
User is not authenticated with basic authenticator and redirected to SMSOTP

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#17072]
**Describe the issue:**
User is not authenticated with basic authenticator and redirected to SMSOTP page. This could be related to the recent changes done to use SMSOTP and EmailOTP as first authenticators.

**How to reproduce:**
1. Configure a sp with identifier-first as the 1st step and basic, SMSOTP, EmailOTP (Federated Authenticator) in the 2nd step.
![image](https://github.com/wso2/product-is/assets/2381693/26c0cedf-2b43-4ea8-89cf-b1811c4b7935)

2. In the 1st step of the authentication flow, enter the username and continue.
![image](https://github.com/wso2/product-is/assets/2381693/2e160c41-19c2-4bf9-a65c-e4cccfd7b3b2)

3. In the 2nd step, enter the password for basic authentication and continue.
![image](https://github.com/wso2/product-is/assets/2381693/6987ec08-d96d-439a-a9e3-1313b6ac9a49)

4. The user is redirected to the SMSOTP page instead of authenticating with the basic authenticator.
![image](https://github.com/wso2/product-is/assets/2381693/7dc92e2d-23e1-415b-9a8f-1da3b43fd0b3)

**Expected behavior:**
User should be authenticated after step 3 and not redirected to SMSOTP

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0, IS-KM 5.10
 - Update level 248

**Comment by hwupathum** [comment]
All the PRs related to this issue are merged
