### ISSUE TITLE
Improve self organization onboarding flow

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17086]
**Describe the issue:**

At the moment, registering a user in a suborganization during self organization onboard requires the following. 
- Create sub-organization under the primary organization.
- Switch the access token to the suborganization.
- Create the user in the suborganization.

The suborganization creation flow should be improved to include the user creation, without having to switch the access token and add the user separately.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
