### ISSUE TITLE
Check the possibility to remove Role reource management from Charon

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17096]
**Describe the issue:**
Role resource is a custom SCIM resource defined by WSO2 IS. Since the charon is the core library for SCIM spec, Role resource management should be ideally moved out.

Try to use the custom resource defining extensibility of charon and move this to SCIM management component in IS.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
