### ISSUE TITLE
Document the purpose of configuring domain name in cluster configurations

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1710]
Cluster documentation [1] should include information on why it is required to define a domain name in axis2.xml when configuring the cluster.

Is it mandatory to define a domain name or is it okay to use the default cluster domain that is there in the axis2.xml

[1] https://docs.wso2.com/display/IS540/Clustered+Deployment

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
