### ISSUE TITLE
Make email domain regex configurable for the primary organization for organization discovery feature

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#17106]
With https://github.com/wso2/product-is/issues/16379, we are providing the capability to identify the user's organization from the email domain during the B2B login flow. As a part of supporting this capability, we have introduced a new API to map the relevant email domains for the sub organizations by the primary organization. PR: https://github.com/wso2-extensions/identity-organization-management/pull/265 validates whether the provided email domains are in the correct format. The regex pattern is defined at the code level. This issue is created to track the improvement of making this regex configurable at the primary organization level.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
