### ISSUE TITLE
Registry mounting configurations are missing in Cluster Docs

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1711]
The cluster doc [1] does not contain registry mounting configurations which are required to mount the registry for the cluster setup.

[1] https://docs.wso2.com/display/IS540/Clustered+Deployment

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
