### ISSUE TITLE
Improvements to the Texts section in the branding configs

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#17128]
**Is your suggestion related to an experience ? Please describe.**
With the new Texts section in the branding configs, there are improvements that can improve the user experience.

**Describe the improvement**

- Screens dropdown in the Texts section does not align with the other sections in the branding.
   <img width="1333" alt="image" src="https://github.com/wso2/product-is/assets/1332991/1346cd06-8dec-44ff-859b-02494b3321bc">

- Add email templates to the screens dropdown, since there are some texts that can be applied to email templates as well.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
