### ISSUE TITLE
Alignment issues in the user store creation page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1712]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

The property name, value and the description is not properly aligned so that it is difficult for a user to identify the proper values/descriptions

![12](https://user-images.githubusercontent.com/1845370/34140617-f9fb8fba-e4a1-11e7-8567-2ca723016d91.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
