### ISSUE TITLE
Headers are missing in table interfaces.

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#17124]
**Describe the issue:**
Headers are missing in table interfaces in all table interfaces.

<img width="1548" alt="Screenshot 2023-10-23 at 10 08 34" src="https://github.com/wso2/product-is/assets/46097917/eb5835f1-12c6-4183-89c6-9e6da9fc93b3">

**Ideally:**
Headers should be visible.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
