### ISSUE TITLE
Make the parameterized 'AssertionConsumerServiceURL'  values to work with IS Dashboard configurations

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1713]
Better to get the parameterized values working for IS dashboard configurations rather than asking the user to manually configure the Dashboard configurations in "sso-idp-config.xml" when configuring the cluster setup. 

Purpose of this is to reduce the number of manual configurations required from user's point of view.

Ex: Doc [1], "Setting up the dashboard" step 1 where the "AssertionConsumerServiceURL" needs to be configured. 
Parameterized configurations are as below
``` <AssertionConsumerServiceURL>${carbon.protocol}://${carbon.host}:${carbon.management.port}/dashboard/acs</AssertionConsumerServiceURL>```

[1] https://docs.wso2.com/display/IS540/Clustered+Deployment

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
