### ISSUE TITLE
Improve User Experience: Enable "Signin" Option in the Same Window After Password Reset

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17137]
Currently, after users complete a password reset process due to an expired password, they are redirected to the "https://localhost:9444/accountrecoveryendpoint/completepasswordreset.do" page. However, there is no option to "Signin" on the same page. 
This design flaw forces users to manually reenter the console link and sign in again. This additional step not only inconveniences users but also disrupts the user experience, causing confusion and frustration.

### Proposed Solution:

To improve user experience and eliminate the inconvenience faced by users, it is essential to add a "Signin" option directly on the "https://localhost:9443/accountrecoveryendpoint/completepasswordreset.do" page after a successful password reset.

<img width="1101" alt="Screenshot 2023-10-23 at 15 47 01" src="https://github.com/wso2/product-is/assets/39120228/b37608f2-cffc-498a-a986-1c05d940baf6">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
