### ISSUE TITLE
Emails don't have the default logo shown in the email template branding section

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17135]
**Describe the issue:**

When email template branding is not configured, emails sent from the IS don't have the default logo.

![Screenshot 2023-10-23 at 13 17 18](https://github.com/wso2/product-is/assets/41533942/93b62a89-cb0e-4bc7-ae79-981c88e42aa2)

**How to reproduce:**

1. Get a fresh IS pack.
2. Sign into the console and enable self sign up
3. Perform self signup with the console.
4. Observe the confirmation email sent from the IS.

**Expected behavior:**

Default email notifications should have the wso2 logo in emails.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mpmadhavig** [comment]
It was found out that the src tag for the logo contains a identity server specific URL [1] which cannot get resolved by another email server. This issue would not be reproducible in the prod environment as the IS host can be resolved by the email server.

As this is not a production affected case, closing the issue.

[1] https://localhost:9443/console/libs/themes/default/assets/images/branding/logo.svg
