### ISSUE TITLE
Missing Configuration in Token Exchange Grant Type 

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#17140]
**Describe the issue:**
[IAT_VALIDITY_PERIOD](https://github.com/wso2-extensions/identity-oauth2-grant-token-exchange/blob/main/component/org.wso2.carbon.identity.oauth2.grant.token.exchange/src/main/java/org/wso2/carbon/identity/oauth2/grant/token/exchange/Constants.java#L61) is not configurable value. Should be added to the identity.xml.j2 file and add the default value to default.json file.

**Comment by AmshikaH** [comment]
Closing as this is not a missing configuration.
