### ISSUE TITLE
Inability to Set other selected Attributes as Subject Attribute in OIDC Applications (SPA & Traditional Web)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17144]
**Describe the issue:**
When configuring OIDC applications (both Single Page Applications - SPA and Traditional Web Applications) , there is a persistent issue where other selected attributes cannot be set as the Subject attribute. 

Despite the presence of a dropdown menu to select the desired attribute, the configuration defaults to setting the Username attribute in the application's User Attribute Tab. 

Even after selecting a different attribute and receiving a success message, the chosen attribute is not applied as the Subject attribute

Note: This is working as expected in SAML web application.

**How to reproduce:**

**Expected behavior:**
The OIDC application configuration should allow admin to successfully set selected attributes as the Subject attribute. After selecting a selected attribute from the dropdown menu and receiving a success message, the chosen attribute should be applied as the Subject attribute.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT
 - OS: Mac
 - Database:MySQL
 - Userstore:JDBC

SP Application
[recording.webm](https://github.com/wso2/product-is/assets/39120228/fe405ad6-9327-4f95-a444-3f4b0efb33e4)

OIDC Tradional Web Application
[recording(1).webm](https://github.com/wso2/product-is/assets/39120228/fc778307-86f9-4f8b-ad34-285d6f01fabf)

**Comment by Thisara-Welmilla** [comment]
In the `/api/server/v1/applications/{app-id}` PATCH request, the `subject` data is not sending. Need to fix PATCH call from UI.

**Comment by brionmario** [comment]
This field was removed from the UI intentionally with https://github.com/wso2/product-is/issues/17584, since with the new IS features, we don't really need such configuration for *OIDC* .

For SAML apps, it'll be enabled: Tracker -> 

Hence, closing this....
