### ISSUE TITLE
Upload certificate will remove the added JWKS endpoint

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#17145]
**Describe the Issue:**
Upload certificate will remove the added JWKS endpoint

**How To Reproduce:**
1. Login to console and create connection
2. Add JWKS end point in connection setting and update
3. Select the certificate section and add .pem and update
4. Check the JWKS input field

**Expected behavior:**

Added values in JWKS input field should be there

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by brionmario** [comment]
This is a fix porting: https://github.com/wso2/identity-apps/pull/4295

Need to validate in BETA 2 and close.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
