### ISSUE TITLE
Username recovery: email config step refers password recovery

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1714]
In [1] the step 6 is refering to a password reset. But the step prior to that is addressing username recovery. Please verify and change so that the step would reflect enabling sending mail when recovering username.

[1] https://docs.wso2.com/display/IS540/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
