### ISSUE TITLE
The `Advanced` properties are absent in the Userstore (LDAP and AD) edit section

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#17147]
**Describe the issue:**
When attempting to configure a LDAP (RW, RO) or Active Directory userstore, some times it's necessary to configure the `Advanced` properties as well (It depend on the user's usecase). However, at present, this fields are not displaying on frontend because the `attrbutes` key is not present on the metadata response from the API for `Advanced` properties. For the JDBC userstores, `Advanced` properties are displaying on frontend because API response returns the `attributes` key for all properties in `Advanced` section. Please refer to the following API responses (GET: https://localhost:9443/api/server/v1/userstores/meta/types/{typeId}).

LDAP and AD metadata for the `Advanced` section properties.
<img width="812" alt="image" src="https://github.com/wso2/product-is/assets/74205483/0571dd03-4cf2-4e06-8c1d-59e205321b66">

JDBC metadata for the `Advanced` section properties.
<img width="751" alt="image" src="https://github.com/wso2/product-is/assets/74205483/e2c18d54-b2d7-475c-852c-9b8bd73004b3">

As observed, the properties within the `Advanced` section currently lack information about whether they are required or not, category, and type of the property. It is essential to review and include the `attributes` key for all properties within the `Advanced` section of the API response for LDAP and AD as well. The information included within the `attributes` key plays a vital role in categorizing and rendering the form fields on the frontend.

**How to reproduce:**
1. Setup a LDAP (RW) in latest IS pack using new Console (Guide - https://docs.google.com/document/d/1Efzq_NLXctBicsukNT50ZJZGC1eKyQG7mIg4I58vsaU/edit?usp=sharing)
2. Try to onboard a user through new console into the configured LDAP
3. Then you will get a `202` response with the message `The new user was accepted and pending approval.` and user will not be added to the userstore.

**Expected behavior:**
1. API should return the `attributes` key for the `Advanced` properties.
2. Should be able to configure `Advanced` properties for LDAP and AD from the new console and add users to the secondary userstore.

**Environment information**
 - Product Version: 7.0.0 (latest)
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: LDAP

**Comment by madurangasiriwardena** [comment]
IMO advanced properties should not be mandatory, that's the essence of that being an advanced property. So if the `Immutable Attributes` is an advanced property, it should not be mandatory.

**Comment by madurangasiriwardena** [comment]
Now the backend is properly sending the properties. But As it seems in the User section the non-mandatory properties are now shown.

**Comment by DilshanSenarath** [comment]
> Now the backend is properly sending the properties. But As it seems in the User section the non-mandatory properties are now shown.

Fixed with this PR - https://github.com/wso2/identity-apps/pull/4970
