### ISSUE TITLE
Multiple `checksession` requests in My Account

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#17146]
**Describe the Issue:**
When login to My Account (Super tenant or Tenanted path both), two checksession requests are fired.
One request is getting failed with an empty tenant domain in URL. Ideally, this initial checksession request shouldn't be fired.

**How To Reproduce:**
1. Login to the My Account.
2. Observe the network trace.

**Expected behavior:**

N/A

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by brionmario** [comment]
This is a fix porting: https://github.com/wso2/identity-apps/pull/4296

Need to validate in BETA 2 and close.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
