### ISSUE TITLE
Misalignment in user name and image in user list item in assigned users list in a group.

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17154]
**Describe the issue:**

$subject

<img width="1505" alt="Screenshot 2023-10-24 at 10 35 35" src="https://github.com/wso2/product-is/assets/41533942/ee9ae0a7-7e6e-4de1-a007-f24434ae8f76">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
