### ISSUE TITLE
Ensure uniqueness across OIDC scopes and API resource scopes

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#17153]
**Describe the issue:**
Ensure the uniqueness across the OIDC scopes and the API resource scopes.

**Expected behavior:**

- OIDC scopes in the tenant cannot be created as an API resource scopes. (This is already ensured in the API resource management API)
- API resource scope in the tenant cannot be created as an OIDC scopes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
