### ISSUE TITLE
Password recovery: reason for orderId related configs

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1715]
In [1] there is the section where it instructs for disabling and enabling of some orderId related properties. Please include the reason for doing so and how it's affected to the content that follows

[1] https://docs.wso2.com/display/IS540/Password+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
