### ISSUE TITLE
Update the display name of the `organization-self-service` connector

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#17169]
**Describe the issue:**
Since we have decided to change the `Sub organization` term in the console to `organizations` the displayname of the `organization-self-service` connector should be updated accordingly.

Relevant API Request:

`api/server/v1/identity-governance/VXNlciBPbmJvYXJkaW5n`

Relevant API Response:

```
{
  "id": "b3JnYW5pemF0aW9uLXNlbGYtc2VydmljZQ",
  "name": "organization-self-service",
  "category": "User Onboarding",
  "friendlyName": "Suborganization Self Service",
  "order": 0,
  "subCategory": "DEFAULT",
  "properties": [ {...} ]
}
```

**How to reproduce:**

1. Access the Console.
2. Click on Login & Registration navbar item.
3. Select User Onboarding.
4. The following section will utilize the displayname.

![image](https://github.com/wso2/product-is/assets/30111554/982ef161-b705-4c53-8327-10ddbab62c7a)

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
