### ISSUE TITLE
EMAIL OTP prompts as an authentication step when proceeding with another authenticator in MFA 

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#17161]
**Describe the issue:**
When MFA is enabled with `EMAIL OTP` authenticator, eventhough we used another authenticator for authentication, EMAIL OTP authentication step appears as a second step.
 

https://github.com/wso2/product-is/assets/75057725/34afbcb1-2f49-4f3c-b141-877aa1c7330a

**How to reproduce:**

1. Login to console
2. Create an application
3. Enable MFA for the application (Choose Basic, EMAIL OTP(federated authenticator))
4. Login to the application
5. Choose BAsic authenticator and proceed.

**Expected behavior:**
Authentication should be succesful and directed to the application without any authentication steps.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0-m4]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

---

**Related issues:**

- https://github.com/wso2/product-is/issues/17072

**Comment by DMHP** [comment]
This issue will be solved in this pr : https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/172/files

**Comment by hwupathum** [comment]
All the PRs related to this issue are merged
