### ISSUE TITLE
Self registration section update message should be improved

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17164]
**Describe the issue:**

Self-registration section update message should be improved.
<img width="1492" alt="Screenshot 2023-10-24 at 13 19 11" src="https://github.com/wso2/product-is/assets/40081059/4b2f9d15-3efe-40ea-98a9-532b342e7aff">

**How to reproduce:**

1.Login into console
2.Go to login and registration
3.Go to user onbaording
4.Enable some configs and click on update button

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
We can close this issue as this is no longer applicable.
