### ISSUE TITLE
[Doc] Invalid URLs in IS OpenID Connect Dynamic Client Registration REST APIs Documentation.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17167]
**Describe the issue:**
There are invalid URLs in the OpenID Connect Dynamic Client Registration REST API documentation.
Missing forward slash in the URL [OpenID Connect Dynamic Client Registration REST APIs
](https://is.docs.wso2.com/en/latest/apis/use-the-openid-connect-dynamic-client-registration-rest-apis/)

<img width="934" alt="Screenshot 2023-10-24 at 14 52 01" src="https://github.com/wso2/product-is/assets/41188245/70ff25c3-e1f9-4d9b-97b7-8b4d20283897">

**Expected behavior:**
Should be `https://localhost:9443/api/identity/oauth2/dcr/v1.1`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
