### ISSUE TITLE
[Doc] Need to change enable show WSDLs in order to access Admin Services need to be mention in TOTP Docs.

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1716]
In  **Obtaining the QR code without using the end user dashboard** section [1], it is mentioned to access WSDL. But without changing  **<HideAdminServiceWSDLs>false</HideAdminServiceWSDLs>** user cannot access WSDL. Mention it as info.

 Inorder to acess admin service pls do the belwo changes
<IS_HOME>/repository/conf/carbon.xml 
<HideAdminServiceWSDLs>false</HideAdminServiceWSDLs>
`
[1]https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
