### ISSUE TITLE
[Doc] Better to add a note on the requirement of having an existing project to register OAuth 2.0 Application in Google

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1717]
A user should either have an existing project to select or create a new one in order to proceed with registering an OAuth 2.0 Application in Google. Better to mention that under 2nd step in [1]

https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
