### ISSUE TITLE
Getting a 404 error when trying to navigate to myacccount after password set completion flow

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17188]
**Describe the issue:**

Getting a 404 error when trying to navigate to myacccount after password set completion flow.
It will redirect into this endpoint https://localhost:9443/accountrecoveryendpoint/null

https://github.com/wso2/product-is/assets/40081059/075fa620-9c31-445e-9988-682bd8a89e2e

**How to reproduce:**

1.Login into console
2.Onbaord a user using multiple users option
3.Goto the received email ti set the password
4.Give password and set the password sucessfully
5.And click on the My Account button

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduDilshan** [comment]
With the fix done in above PR, super tenant myaccount url will be returned. Tenanted myaccount will be returned with the [PR](https://github.com/wso2/identity-apps/pull/4216).
