### ISSUE TITLE
Password recovery:  Account Recovery REST API is pointing to the wrong documentation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1718]
In [1] for Account Recovery REST API is pointing to old document. Please update

[1] https://docs.wso2.com/display/IS540/Password+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
