### ISSUE TITLE
[Doc] Update the Claim mapping navigation to latest doc version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1719]
Refer to doc [1]. Update the navigation for Adding claim mapping to the latest doc version

[1]. https://docs.wso2.com/display/IS540/Configuring+Claims

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
