### ISSUE TITLE
Hide MyAccount access Link showed in profile dropdown of console if the user accessing org != user resident org

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17195]
**Describe the issue:**

Hide MyAccount access Link showed in the profile dropdown of the console if the user accessing org != user resident org.

Users should be able to see the myaccount access URL under drop down of the user profile when he is logged into his resident org

**Comment by JayaShakthi97** [comment]
Updated the logic to hide App switch button, comparing the current organization id and user_org param returns in IDToken.
- https://github.com/wso2/identity-apps/pull/4420

**Comment by JayaShakthi97** [comment]
Verified in Alpha release


https://github.com/wso2/product-is/assets/37938529/77f90085-7da6-47a1-afdc-1bc0e6f0b3ac
