### ISSUE TITLE
Missing UI Support for Creating a Role in the PRIMARY Domain

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17199]
**Describe the issue:**
The current UI lacks the functionality to assign a role in the PRIMARY domain. Which was available in the carbon console.
Any roles created through the console are automatically assigned to the `Internal` Domain.

### Note: No Support to list the PRIMARY users 

<img width="737" alt="Screenshot 2023-10-25 at 14 15 01" src="https://github.com/wso2/product-is/assets/41188245/d3095ab4-88ff-41d4-a679-199259caeaa5">
 
<img width="737" alt="Screenshot 2023-10-25 at 14 29 18" src="https://github.com/wso2/product-is/assets/41188245/f65bef80-83c8-42cc-a583-8c5fb6d70f53">

**Expected behavior:**
 The UI Should provide the capability to create roles in a preferred domain (`PRIMARY, APPLICATION`)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: WSO2 Identity Server-7.0.0-m4-SNAPSHOT
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
In old mgt console, both Roles and Groups are under Roles section.
What ever the role created with userstore domain is treated as a group in IS-5.11.0 onwards if group vs role sepeartion is enabled.

**Comment by AnuradhaSK** [comment]
Btw, IS-7.0.0 there are changes to role mgt feature delivered through https://github.com/wso2/product-is/issues/16363

**Comment by brionmario** [comment]
@melanisilva Is this valid now?

**Comment by brionmario** [comment]
This is invalid based on the comments provided by @AnuradhaSK (https://github.com/wso2/product-is/issues/17199#issuecomment-1779085488).

Also, the UI has changed since the issue was created to support the new runtime.

<img width="1180" alt="Screenshot 2023-12-01 at 13 07 20" src="https://github.com/wso2/product-is/assets/25959096/bbca728b-a5fa-4d84-91a4-95f1746d30e8">
