### ISSUE TITLE
Bring Custom email template adding support to the Unified Console

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#17207]
### Context
In the 6.1 release, the Beta console provided UI support for adding Custom email templates. This feature is missing in the unified Console.

**User experience in 6.1 release Beta console**

https://github.com/wso2/product-is/assets/37938529/b4e72478-781e-42d1-b12b-947d81ce81e7

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
