### ISSUE TITLE
Support API-Based Authentication with Magic Link

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17206]
**Describe the issue:**
We'd better be able to improve API-based authentication capabilities for MagicLink

Currently if set Magic Link as 1st Factor Authenticator, the API response will be, "oauth2/authorize"
Ex:
```
{
    "flowId": "35bed9dc-a3ac-4137-8d6c-fb74e7ac07a7",
    "flowStatus": "INCOMPLETE",
    "flowType": "AUTHENTICATION",
    "nextStep": {
        "stepType": "AUTHENTICATOR_PROMPT"
    },
    "links": [
        {
            "name": "authentication",
            "href": "https://localhost:9443/oauth2/authn",
            "method": "POST"
        }
    ]
}
```

**Comment by DMHP** [comment]
This has been improved. Please validate with the alpha 2.

`{
    "flowId": "ba35f08a-7ae7-4bf4-9113-2d41dbb152c4",
    "flowStatus": "INCOMPLETE",
    "flowType": "AUTHENTICATION",
    "nextStep": {
        "stepType": "AUTHENTICATOR_PROMPT",
        "authenticators": [
            {
                "authenticatorId": "TWFnaWNMaW5rQXV0aGVudGljYXRvcjpMT0NBTA",
                "authenticator": "Magic Link",
                "idp": "LOCAL",
                "metadata": {
                    "promptType": "USER_PROMPT",
                    "params": [
                        {
                            "param": "username",
                            "type": "STRING",
                            "order": 0,
                            "i18nKey": "username.param",
                            "confidential": false
                        }
                    ]
                },
                "requiredParams": [
                    "username"
                ]
            }
        ]
    },
    "links": [
        {
            "name": "authentication",
            "href": "https://localhost:9443/t/carbon.super/oauth2/authn",
            "method": "POST"
        }
    ]
}`
