### ISSUE TITLE
Getting something went wrong page after deleting a user

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17228]
**Describe the issue:**

Getting a something went wrong page after deleting a user in a organization. Following stacktrace can be seen in the browser console.

![Screenshot from 2023-10-26 11-30-39](https://github.com/wso2/product-is/assets/35653110/07bd990b-87ca-49ab-b3a4-0d2839eeb1ad)

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at He (19026.aa890b44.chunk.js:1:26394)
    at 19026.aa890b44.chunk.js:1:23364
    at il (vendor.14e7fb03.js:102:1548714)
    at Sc (vendor.14e7fb03.js:102:1568844)
    at cc (vendor.14e7fb03.js:102:1561145)
    at ji (vendor.14e7fb03.js:102:1502107)
    at rc (vendor.14e7fb03.js:102:1558301)
    at ns (vendor.14e7fb03.js:102:1523593)
    at 19026.aa890b44.chunk.js:1:17859
    at <anonymous>
```

Reproducible with latest IS snapshot build (console v2.2.0).

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
This issue cannot be reproduced in the most recent build using Console version 2.3.0.

**Comment by DilshanSenarath** [comment]
This issue can be reproduced within a sub-organization.
