### ISSUE TITLE
Reevaluate JSON Response for Invalid Client ID in "oauth2/authorize" API Endpoint 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17225]
**Describe the issue:**

"oauth2/authorize" API endpoint is currently returning a 200 status code even when an invalid client ID is provided.

Additionally, it would be better to improve our JSON response structure by using a more meaningful key, "correlationId" instead of "crId".

**Requirements**:

Reevaluate the "oauth2/token" API endpoint's behavior for invalid client ID scenarios.

If necessary, modify the HTTP status code to 400 Bad Request and update the JSON response structure to incorporate "correlationId" and provide accurate error feedback.

**How to reproduce:**
1. Create OIDC Application
2. Setup Username & password as signin option
3. In "oauth2/authorize" API endpoint  provide invalid ClientID

<img width="929" alt="Screenshot 2023-10-26 at 10 49 08" src="https://github.com/wso2/product-is/assets/39120228/ec47ccf0-4d27-4b2d-9821-09c51285cc5d">

**Comment by janakamarasena** [comment]
This is resolved with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2249
