### ISSUE TITLE
Hide HYPR and Github Authenticator templates in the Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#17239]
**Is your suggestion related to an experience ? Please describe.**
As we have decided to consider the HYPR and Github as OOTB connectors we need to hide the templates on the connections page in the onprem identity server by default. The finalized approach is to hide the relevant UIs from the console and provide the capability to override the behavior from the deployment.toml file.

Users will be able to view the HYPR and Github templates by adding the following configuration.

```
[console.ui]
hiddenConnectionTemplates = []
```

**Comment by chamathns** [comment]
Related https://github.com/wso2/product-is/issues/17043
