### ISSUE TITLE
Two Add roles buttons are visible in the roles section

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17236]
**Describe the issue:**

Two Add roles buttons are visible in the roles section
<img width="1074" alt="Screenshot 2023-10-26 at 12 21 16" src="https://github.com/wso2/product-is/assets/40081059/1c31c99a-128e-4236-8e2c-eb8d1c487c1a">

**How to reproduce:**

1.Login to the console
2.Go to roles section in user management
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
Further,

- The role creation button should not be available in sub-organizations.
- Change the shown message if there is not shared roles available in the sub-organization
