### ISSUE TITLE
[Doc] Add sample values for External Claim URIs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1723]
Refer to doc [1]. Provide sample values as examples for external claim URIs under Add external claim

[1]. https://docs.wso2.com/display/IS540/Adding+Claim+Mapping

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
