### ISSUE TITLE
UI improvements in API resource management

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17238]
**Describe the issue:**

- [ ] Add titles for the table columns
- [ ] Include a column to indicate that the API type "SYSTEM"/ "BUSINESS"
- [ ]  Add a filter to filter the API resources by name, by type etc
- [x] Remove edit/delete icons from SYSTEM APIs and add eye icon

<img width="1712" alt="Screenshot 2023-10-26 at 11 40 29" src="https://github.com/wso2/product-is/assets/25483865/f53e8f6b-a557-4727-8321-aeb736b061f6">

- [x] Remove the scope deletion icon in the system API's scopes

<img width="1715" alt="Screenshot 2023-10-26 at 14 11 22" src="https://github.com/wso2/product-is/assets/25483865/0e7e0d63-da61-4176-986e-a452a47caa7f">

**Comment by DonOmalVindula** [comment]
Will be fixed with https://github.com/wso2/product-is/issues/17453
