### ISSUE TITLE
UI issues in groups  assign section in the roles tab

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17235]
**Describe the issue:**

UI issues in groups assign section in the roles tab. Here the Update button is not visible to the users when groups are assigned.

https://github.com/wso2/product-is/assets/40081059/2676ea4f-6295-4b9a-8e0c-72bf3e39411d

**How to reproduce:**

1.Login to the console
2.Go to roles section in user management
3. Create a new role and try to assign a group

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment]
This is currentlty fixed in 7.0.0-alpha.
