### ISSUE TITLE
Getting an error  when trying to delete a custom API Resource

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17246]
**Describe the issue:**

Getting an error and directing to the something went wrong page  when trying to delete a custom API Resource

https://github.com/wso2/product-is/assets/40081059/36a582ee-2575-4a92-9496-990fa4379f1f

**How to reproduce:**

1. Login to the console
2. Create an API resource
3. Go to the created all API resources
4. then try to delete the custom API resource from delete icon

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by SujanSanjula96** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/4399
