### ISSUE TITLE
[doc] Backup codes support for Email OTP authenticator

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#17245]
The improvement is available with IS5.8.0 wum updated pack(update number 6098) and latest master. 

- To support this backup codes for emailotp authenticator, add the following config under EmailOTP authenticator config in application-authentication.xml file located in <IS_HOME>/repository/conf/identity folder.

` <Parameter name="BackupCode">true</Parameter>  
`

- Add "http://wso2.org/claims/otpbackupcodes" claim via management console to store backup codes for email-otp-authenticator

Need to improve the email-otp document[1]. The content will be similar to the backup-codes support in SMS-OTP authenticator[2]

[1]https://docs.wso2.com/display/IS580/Configuring+Email+OTP#ConfiguringEmailOTP-ConfiguringUserClaimConfiguretheuserclaims
[2]https://docs.wso2.com/display/IS580/Configuring+SMS+OTP#ConfiguringSMSOTP-Configuringclaims

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
