### ISSUE TITLE
Getting an error when trying to create an API resource in mobile application

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17249]
**Describe the issue:**

Getting an error when trying to create an API resource in the mobile application.

https://github.com/wso2/product-is/assets/40081059/48165261-a563-4366-b6a0-e484cb2240b7

**How to reproduce:**

1.Login to the console
2.Create and mobile application
3.Go to the created mobile application and go to the API authorization section

Try to create a API resource
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by SujanSanjula96** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/4357
