### ISSUE TITLE
Password recovery: Doesn't work with tenant user

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1724]
**Steps**
1. Create a tenant
2. Create a user
3. Associate an email address in the profile
4. In resident IDP of the tenant configure password recovery
5. Go to dashboard and click password reset option
6. Enter the email address
7. Click the link posted to the mail
8. Reset the password
9. Log in to dashboard using the new credentials

Authenticaton error is given in the client and an error is given in the server

```
[2017-12-19 11:16:32,357] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Context does not exist. Probably due to invalidated cache
```

![is_error_7](https://user-images.githubusercontent.com/15624590/34142677-8d67f822-e4ae-11e7-87b6-ce0f712d835b.png)

**Comment by DMHP** [comment]
This issue can not be reproduced in the current IS master. Hence resolving the issue. Please re-open if you have any other concerns.
