### ISSUE TITLE
Unable to Proceed Application Sign-in flow when enabled Mandatory user attributes

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17243]
**Describe the issue:**

When mandatory user attributes are enabled and API-based authentication is used, users are unable to proceed through the sign-in flow. There seems to be a lack of functionality to handle the mandatory attribute requirement in the API-based authentication process

**How to reproduce:**
ex:

1. Create OIDC Applicction
2. set few user attributes as mandatory 
3. setup username as 1st factor 
4. Try API based Endpoints, ``` oauth2/authorize ``` & ``` /oauth2/authn ```

**Expected behavior:**
Modify the API-based authentication endpoint to handle mandatory user attributes.

<img width="1305" alt="Screenshot 2023-10-26 at 13 57 58" src="https://github.com/wso2/product-is/assets/39120228/bbea04ef-cb88-42fd-8b31-55685bac94e8">

**Comment by aaujayasena** [comment]
@janakamarasena
