### ISSUE TITLE
Issue in emailOTP and smsOTP backup code persistence 

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#17252]
**Describe the issue:**
Currently OTP backup codes are stored in the http://wso2.org/claims/otpbackupcodes claim. Ideally, it should be an identity claim. This will also facilitate using backup code feature for users who are residing on read-only userstores.

**Related Case:**
https://github.com/wso2/product-is/issues/7474
https://github.com/wso2/product-is/issues/6486

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
