### ISSUE TITLE
Getting an error when trying to create an application based role

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17257]
**Describe the issue:**

Getting an error when trying to create an application based role
https://github.com/wso2/product-is/assets/40081059/52fa43ff-7a76-4367-b0cf-f7438a840dc6

**How to reproduce:**

1. Go to the console
2. Create an application 
3. Create an API resource and assign it to the created role
4. Go to the roles section and try to create an application role
5. Give the required details and try to complete the creation process

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Kanapriya** [comment]
Closing this issue as it is not reproducible with the latest wso2is-7.0.0-alpha2-SNAPSHOT pack. Please refer to the below screencast for further reference.

https://github.com/wso2/product-is/assets/13362482/783031d4-1524-4635-b324-caaca6b4edab
