### ISSUE TITLE
[Improvement] [UI] Display a proper error message once a user attempts to self register when the feature disabled by default

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1725]
== Environment ==

IS 5.4.0 standalone pack
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

1. Follow 10-13 steps in [1] in order to enable 'SAML2SSOAuthenticator'
2. Start the server and go to management console.
3. Click 'Register Now' from the login window

![login page](https://user-images.githubusercontent.com/8849472/34142738-dc66572a-e4ae-11e7-87a3-45a85eefdbea.png)

4. Fill the details and click register

== Result ==

Following error message displayed in UI with an error code but there's no reference to the error message to search. 

![self sign up feature is disabled](https://user-images.githubusercontent.com/8849472/34142721-cffd8f94-e4ae-11e7-930b-b3386cdb358e.png)

So having a proper error message would be great since this is a user attempts to register an account. As an example,

"Self sign up feature is disabled. Please contact administrator to create an account"

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
