### ISSUE TITLE
Password recovery: Reset with security questions - mismatching content

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1726]
In [1] under reset with security questions section following is given

"Before setting this up, you must configure the required claims for this feature. To do this, do the following" but the succeeding content discusses setting up the resident IDP. Ideally it should discuss configuring claims 

[1] https://docs.wso2.com/display/IS540/Password+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
