### ISSUE TITLE
Getting an error when trying to update the API resources(System)

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17260]
**Describe the issue:**

Getting an error message when trying to update the API resources(System API s)

https://github.com/wso2/product-is/assets/40081059/59c93afb-e129-496c-8db6-0ccef03ae046

**How to reproduce:**

1.Login to the console
2.Go to API resources section
3.Click on a API resource
4.Do some changes and click on the update button

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduR** [comment]
Backend issue is fixed with https://github.com/wso2/identity-api-server/pull/518 PR

**Comment by SujanSanjula96** [comment]
UI improvement are done to disable system API update options with https://github.com/wso2/identity-apps/pull/4388 PR.
