### ISSUE TITLE
Difficult to distinguish org level system APIs and tenant level system APIs during authorizing an API to an app

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17265]
**Describe the issue:**

Try to authorize an API to an application. Search "Roles"
You will see two APIs with same dispaly name.
One API is the system API which is used in tenants (eg: /scim2/Roles)
Other API is the system API which is used in organization access (eg: /o/scim2/Roles)

https://github.com/wso2/product-is/assets/25483865/efc3cc3f-78f7-4089-8587-ab246cbc7e60

We need to distinguish these in the API authorization listing view.
Suggestion: Add API identifier and API type into the list view

Since the display name is not unique in a tenants' APIs, the same disaply name could be used to custom business API

**Comment by DonOmalVindula** [comment]
Will be fixed with - https://github.com/wso2/product-is/issues/17265
