### ISSUE TITLE
API resources section contains Asgardeo references

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17263]
**Describe the issue:**

API resources section contains Asgardeo references
<img width="844" alt="Screenshot 2023-10-26 at 23 41 38" src="https://github.com/wso2/product-is/assets/40081059/86c55afd-591c-49b9-ae36-e2e9531ae03e">

**How to reproduce:**

1.Go to the console
2.Go to API resources section and try to create a resouce

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest (pre-alpha) pack.

![Screenshot 2023-10-29 at 19 38 20](https://github.com/wso2/product-is/assets/41533942/ad432f76-4e83-4fe4-9a6f-811e2273ef41)
