### ISSUE TITLE
Inconsistency in Display names of scopes in System APIs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17266]
**Describe the issue:**

- [x] Some APIs' scope display name is in the parrren of `<CRUD operation> <Resource name>`

eg:
<img width="528" alt="Screenshot 2023-10-27 at 00 02 26" src="https://github.com/wso2/product-is/assets/25483865/6a3f614b-2723-41d2-b61c-e372b42f1e8f">

Some APIs' scope display name is in the parrren of `<CRUD operation> <Resource name> Management`
eg:

<img width="720" alt="Screenshot 2023-10-27 at 00 01 49" src="https://github.com/wso2/product-is/assets/25483865/ba9ff0bd-0538-404e-bd05-d4681539ab3d">

Better to have a consistent pattern on display names of scopes in System APis

- [x] /o/<path> APIs' some scopes have "Organization" part in the display name of the scope
<img width="716" alt="Screenshot 2023-10-27 at 00 01 31" src="https://github.com/wso2/product-is/assets/25483865/abb4aac5-8469-468b-914f-1e97b0762fee">

**How to reproduce:**
Check the API resources section / Try to authorize an API to an application

**Comment by ThaminduR** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5083
