### ISSUE TITLE
Manager challenge questions: remove credentials and provide synonym 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1727]
In [1] under "Adding challenge question set" the 1st step includes admin/admin credentials. Since these credentials are dynamic please use the synonym "administrator credentials"

[1] https://docs.wso2.com/display/IS540/Managing+Challenge+Questions

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
