### ISSUE TITLE
Visibility Issue with "Verify the hostname" Toggle Button in Disabled Mode on Remote Log Publishing Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17276]
**Describe the issue:**

When the "Verify the hostname" toggle button is in the disabled mode on the Remote Log Publishing Page, it is not properly visible

**How to reproduce:**
Navigate to the Remote Log Publishing Page.
Disable the "Verify the hostname" toggle button.( default mode) 

**Expected behavior:**
The "Verify the hostname" toggle button should be clearly visible even in the disabled mode, ensuring that users can easily identify its status.

<img width="558" alt="Screenshot 2023-10-27 at 10 23 53" src="https://github.com/wso2/product-is/assets/39120228/0097fb26-bd07-4cd1-a7e2-08b101ac2ea7">

**Comment by pavinduLakshan** [comment]
Fixed in the latest beta snapshot Jenkins build

https://github.com/wso2/product-is/assets/41533942/fe7fcc90-ddd9-4684-a32f-152952dea845
