### ISSUE TITLE
 Non-User Friendly Information Visible During Role Audience Switch to Application/  Organization? (App Roles Section)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17271]
**Describe the issue:**
When attempting to switch the role audience to the Application/ Organization within the App Roles section, there is a significant usability problem. Non-user-friendly information is visible, creating confusion and hindering the smooth operation of role switching.

**How to reproduce:**
1. Navigate to the App Roles section.
2. Attempt to switch the role audience to the Application.

**Expected behavior:**
Users should encounter a clear, concise, and user-friendly interface during the role audience switch. Any technical or irrelevant information should be hidden from the user to avoid confusion.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-alpha-SNAPSHOT
 - OS: Mac
 - Database:Mysql
 - Userstore:JDBC

---

<img width="1135" alt="Screenshot 2023-10-27 at 09 41 44" src="https://github.com/wso2/product-is/assets/39120228/c9a89d99-5fab-4669-be1a-40a7ce62c8c6">

<img width="1061" alt="Screenshot 2023-10-27 at 10 20 40" src="https://github.com/wso2/product-is/assets/39120228/552f79ad-a9d4-49ac-adcc-61e65c5c8efb">

**Comment by JayaShakthi97** [comment]
Fixed in beta-SNAPSHOT.


https://github.com/wso2/product-is/assets/37938529/bc7fd232-8b5b-4dfc-9d83-f17694458701
