### ISSUE TITLE
UI Issue in Inactive warning pop up  modal.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17279]
**Describe the issue:**
There's a UI issue in the inactive warning modal. Where the background color is not applied to the animated-icon div.

<img width="892" alt="Screenshot 2023-10-27 at 10 31 04" src="https://github.com/wso2/product-is/assets/41188245/327cd33d-92ba-4c8c-8940-5edd2db010d3">

**Expected behavior:**

<img width="1507" alt="Screenshot 2023-10-27 at 10 31 50" src="https://github.com/wso2/product-is/assets/41188245/efbc884b-5ce3-428c-a3bc-4aa0e506a3bf">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT
 - Browser: Chrome(Version 117.0.5938.149 (Official Build) (arm64))
 - OS: mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Seems not reproducible.

<img width="1497" alt="Screenshot 2023-10-29 at 21 05 25" src="https://github.com/wso2/product-is/assets/41533942/16382d90-e042-47dc-a08c-0aa30b51cc03">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
