### ISSUE TITLE
Update expired certificates in the keystore

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#17281]
**Describe the issue:**

Need to update the certs in the keystone in the IS 7.0.0-alpha-SNAPSHOT binary.

![Screenshot 2023-10-27 at 10 22 19](https://github.com/wso2/product-is/assets/25428696/7f2b2395-3c27-4794-bd73-34b8e8bc1f1e)

**Comment by madurangasiriwardena** [comment]
Along with this, we can incorporate https://github.com/wso2/product-is/issues/18466 as well.

**Comment by Thisara-Welmilla** [comment]
Fixed with https://github.com/wso2/product-is/issues/18466
