### ISSUE TITLE
[Docs] Documentation for manual multiple invite feature

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#17282]
Write new documentation for the manual multiple invite feature.

**Comment by dasuni-30** [comment]
PR: https://github.com/wso2-enterprise/asgardeo-docs/pull/1283 cc: @divyaamunugama

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
