### ISSUE TITLE
Getting an error while creating a sub organization under a suborg

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17290]
**Describe the issue:**

Gettinng an error while creating a sub organization under a suborg
<img width="611" alt="Screenshot 2023-10-27 at 12 00 22" src="https://github.com/wso2/product-is/assets/40081059/ec3f31ac-e406-4944-8ac1-34a5ff15a53e">

https://github.com/wso2/product-is/assets/40081059/723c59dd-e2a6-4895-9428-1b629891344e

**How to reproduce:**

1.Login in to the console
2.Go to organization
3.Create sub org
4.Navigate to the suborg and try to creat a another organization

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Kanapriya** [comment]
Closing this issue as it is not reproducible with the latest wso2is-7.0.0-alpha2-SNAPSHOT pack. Please refer to the below screencast for further reference.

https://github.com/wso2/product-is/assets/13362482/68f21dc7-1dca-40a1-b19a-f633fa94e919

Thanks,
Kanapriya
