### ISSUE TITLE
Unable to Switch Edit/Delete Sub-Organizations 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17293]
**Describe the issue:**

The admin is currently unable to edit or delete sub-organizations when using the **legacy runtime.**

<img width="1504" alt="Screenshot 2023-10-27 at 13 59 33" src="https://github.com/wso2/product-is/assets/41188245/f941ffa5-3983-4349-a6af-74cd2383c04a">

  

**How to reproduce:**

1. Add a new organization.
2. Try to edit or delete the created organization  

**Expected behavior:**
The authorized users must be able to edit and delete sub-organizations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
When the legacy runtime is enabled, the recommendation is not to use the console (as it is considered as beta). Therefore only the management console should be used. Hence closing the issue.
