### ISSUE TITLE
Incorrect user creation wizard title

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#17303]
**Describe the issue:**

<img width="753" alt="Screenshot 2023-10-27 at 16 47 25" src="https://github.com/wso2/product-is/assets/67315176/722ae8f5-a572-40a4-bf07-a441ae7fdf04">

**How to reproduce:**
- Go to the Console > User Management > Users
- Create a user
- Enter the required details
- Click next
- Check the title of the modal header

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
- Removed unnecessary code block: https://github.com/wso2/identity-apps/pull/4407

**Comment by JayaShakthi97** [comment]
Verified in alpha release.

![image](https://github.com/wso2/product-is/assets/37938529/dd107ecc-fdbc-48fa-81ad-d36821124611)
