### ISSUE TITLE
Google Connection Icon Missing in Application Sign-In Method Section When Google is Set as Authenticator

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17308]
**Describe the issue:**
The Google connection icon is missing from the application's sign-in section when Google is set as the authenticator. This issue is affecting the visual representation of the authentication options

**How to reproduce:**
Navigate to the application's sign-in Method section 
Select Google as the authenticator for the sign-in process.
Observe that the Google connection icon is missing from the list of authentication methods.

**Expected behavior:**
The Google connection icon should be displayed alongside the Google sign-in option in the application's sign-in section. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0 alpha snapshot
 - OS: Mac
 - Database: Mysql
 - Userstore: JDBC
 - Browser - Microsoft Edge for Business - Version 118.0.2088.69 (Official build) (arm64)

---

<img width="1134" alt="Screenshot 2023-10-27 at 17 13 17" src="https://github.com/wso2/product-is/assets/39120228/a9aec86b-7dc1-4544-9960-4c33e78715b9">

**Comment by asekawa** [comment]
Closing this issue as it no longer reproducing
![Uploading Screenshot 2023-11-08 at 14.54.31.png…]()
