### ISSUE TITLE
Incorrect validation message for the username field in the user creation wizard

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#17302]
**Describe the issue:**

<img width="722" alt="Screenshot 2023-10-27 at 16 39 39" src="https://github.com/wso2/product-is/assets/67315176/1fe982cf-8d5a-4830-b5b4-ceb3c02ae7a4">

**How to reproduce:**
- Go to the Console > User Management > Users
- Create a user
- Enter an invalid username (a name with spaces)
- Click next

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
- Updated the message: https://github.com/wso2/identity-apps/pull/4404

**Comment by JayaShakthi97** [comment]
Verified in Alpha release.
![image](https://github.com/wso2/product-is/assets/37938529/77ec6d02-1e38-4f74-a5f0-ef293d8cc4ea)
