### ISSUE TITLE
Branding Page (Design > Theme Preferences) Referring Asgardeo Links in Input Placeholders 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17306]
**Describe the issue:**

The branding page in Console Theme Preferences section appears to be referencing Asgardeo links within input placeholders

**How to reproduce:**
Navigate to the Branding Page > Design >  "Theme Preferences" section
Observe the branding page, particularly the input placeholders for links.
Notice that Asgardeo links are directly inserted into these placeholders.

**Expected behavior:**
The input placeholders should not contain hardcoded Asgardeo links. 

<img width="652" alt="Screenshot 2023-10-27 at 15 18 07" src="https://github.com/wso2/product-is/assets/39120228/27a9205c-fe68-4234-83f5-0853011f59e2">

<img width="593" alt="Screenshot 2023-10-27 at 15 17 39" src="https://github.com/wso2/product-is/assets/39120228/8f0a169c-4dbe-4e01-8c88-910e1b725559">

<img width="652" alt="Screenshot 2023-10-27 at 15 17 01" src="https://github.com/wso2/product-is/assets/39120228/992bd517-1abe-43a9-8505-7e484117cba9">

**Comment by asekawa** [comment]
Closing this issue with the fix https://github.com/wso2/identity-apps/pull/4451
