### ISSUE TITLE
Managing challenge questions: Reorder the document

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1731]
The current document [1]  at start gives the impression to the user that one of the given points can be used to setup, rather those are configuration steps which are mutually inclusive. Rather than having this structure it's better to take a scenario. 

As an example, for a user store the admin wants to step up a set of challenge questions, those have to cater different languages. Then taking maybe two questions and two different languages, the sample can be explained. 

[1] https://docs.wso2.com/display/IS540/Managing+Challenge+Questions

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
