### ISSUE TITLE
When update the users related to the groups, its redirected to the general section in the edit group interface

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#17318]
**Is your feature request related to a problem? Please describe.**

Currently in the edit groups interface, when we update the users related to the group, its redirected to the general section of the interface.

**Describe the solution you would prefer**

Since this process breaks the user flow, because they expect to stay in the users section, ideally to confirm whether the intended change has happened, they instead redirected to the general section, and they have to click again on the users tab to view the details have been updated.

**Additional context**

https://github.com/wso2/product-is/assets/55197812/e81a0e06-9e20-4566-b434-d35c73cdacdc

**Related Issues:**
- #17322

**Comment by Achintha444** [comment]
This is fixed in the `roles` interface section. Developer who gets assigned for this issue can view those files to get an idea on how to approach this issue.

https://github.com/wso2/identity-apps/blob/86af656e628d644f0c870c24d10f0a16aae98c8b/apps/console/src/features/roles/pages/role-edit.tsx#L54

**Comment by jcgarciaa** [comment]
Verified in latest build:

[group-users.webm](https://github.com/wso2/product-is/assets/55197812/ef568bac-d4bc-4d14-a1c4-1791bdce1374)
