### ISSUE TITLE
Doc Feedback: This page has a JIRA link

### ISSUE THREAD

**Issue by BechtelCanDoIt** [wso2/product-is#17315]
Location : https://is.docs.wso2.com/en/5.11.0/develop/creating-a-third-party-authenticator-or-connector-and-publishing-in-wso2-store/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
