### ISSUE TITLE
Password recovery through challenge questions: provide details on getting locale support through dashboard

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1732]
In [1] when configuring the challenge questions through the console, there is no indication of locale support which is available through management console. Please provide the information

[1] https://docs.wso2.com/display/IS540/Password+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
