### ISSUE TITLE
[Doc] Ask user to go to Identity Server first in order to Configure IDP

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1733]
3rd step of 'Configuring Google' [1] asked user to 'Expand the Google Configuration form and configure the Google authenticator as shown below'. This step needs to be done in IS side but since the previous step related to configurations in Google side, this may confuse the user. So it's better to ask user to go to IS and do the needful in 3rd step.

[1] https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
