### ISSUE TITLE
Improve Identity-apps PR builder

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#17336]
**Is your suggestion related to an experience ? Please describe.**

With current implementation, PR builder builds all the project even though there are no changes in those projects.

**Describe the improvement**

Since NX tool is already integrated, workflow can be improved to build only the affected projects.

**Additional context**

N/A

**Comment by JayaShakthi97** [comment]
PR builder improved by utilizing concurrency to avoid unnecessary parallel runs.
- https://github.com/wso2/identity-apps/pull/4432

**Comment by JayaShakthi97** [comment]
Improvement in utilizing the NX tool is failing in Github action. Need to be investigated and properly fixed.
- https://github.com/wso2/identity-apps/pull/4423

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
