### ISSUE TITLE
Password recovery: Misaligned attachement

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1734]
Please realign following

![is_doc_4](https://user-images.githubusercontent.com/15624590/34143766-6c0c60ea-e4b4-11e7-9d14-bdd24e3df5f7.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
