### ISSUE TITLE
Manage challenge questions: improve claim mapping details

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1735]
The current documentation [1]  with respect to claim mapping on questions is not clear. The document does not cover the following

As an admin I have a set of questions that needs to be configured with claims, how do I get it done and support different locale and different user stores?

[1] https://docs.wso2.com/display/IS540/Managing+Challenge+Questions

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
