### ISSUE TITLE
Improve the application selection list shown under Application audience role creation 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17351]
**Describe the issue:**
1. create an application. don't change the allowed audience for associated roles. Default it is set to "organization".
2. Go to role creation. Give a role name and select "application" as the audience.
3. All available applications except "console" and "myaccount" will be listed
4. If you select an application which doesn't support application audience roles, you will be given the error on finishing the role creation operation.

https://github.com/wso2/product-is/assets/25483865/ad48e95f-df09-41df-ba08-2a153ecc1a41

**Expected Behavior** 
Use API https://github.com/wso2/identity-api-server/pull/515#issue-1958481033 to get list of applications with allowed audience 
- When showing the application list, list the apps which has allowed role audience as "application" as enabled fields
- The application which allows "organization" audience show as disabled fileds
- Give the option to switch the role audience for application which has set "organization" as the allowed audience

**Comment by dasuni-30** [comment]
### Updated UI

- Disabled the applications with `organization` audience
- Added a navigation to update the audience of applications with `organization` audience

<img width="943" alt="Screenshot 2023-11-03 at 14 32 46" src="https://github.com/wso2/product-is/assets/27746285/2f21dd61-3c43-4592-a22a-d586828d5461">
