### ISSUE TITLE
Getting Something Went Wrong on User attribute tab of an application 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17359]
**Describe the issue:**
Getting Something went wrong on User attribute tab of an application 

<img width="1722" alt="Screenshot 2023-10-29 at 11 11 21" src="https://github.com/wso2/product-is/assets/25483865/6a637581-94dd-4457-a383-78d5ff91cf98">

https://github.com/wso2/product-is/assets/25483865/3a7b8e32-416f-48fa-8e2d-a6b066fc674f

```
 Error: Objects are not valid as a React child (found: object with keys {key, text, value}). If you meant to render a collection of children, use an array instead.
    at I (vendor.71b00a6a.js:205:5383168)
    at I (vendor.71b00a6a.js:205:5382899)
    at N (vendor.71b00a6a.js:205:5383445)
    at Object.toArray (vendor.71b00a6a.js:205:5384095)
    at main.94f8e49e.js:2:2630596
    at Array.map (<anonymous>)
    at e (main.94f8e49e.js:2:2629929)
    at g (main.94f8e49e.js:2:2630717)
    at render (main.94f8e49e.js:2:2631649)
    at s (vendor.71b00a6a.js:205:5140617)
```

**Comment by JayaShakthi97** [comment]
This is only reproducible in production mode.

Cause: Advanced attribute settings form has been updated to `uncontrolledFrom = true`. With this update dropdown fields do not accept `children` prop in production.

Fix: Replaced `children` prop with `options` prop, which is used in other places as well.
- https://github.com/wso2/identity-apps/pull/4438

**Comment by JayaShakthi97** [comment]
Verified in Alpha release


https://github.com/wso2/product-is/assets/37938529/651520ce-5f68-4ce5-91ec-8b1543635e40
