### ISSUE TITLE
Error message appearing at a session timeout does not reflect the real behaviour

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1736]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
Browser Chrome 58.0.3029.96

When a session timeout happens "The input stream for an incoming message is null" error message will appear, this does not reflect the real behaviour of the system (session timeout issue)

![screenshot from 2017-12-19 11-55-16](https://user-images.githubusercontent.com/14962228/34144064-f142e1a2-e4b5-11e7-8cfc-49d4b71c48e6.png)

For example: From a new users point of view this error message does not reflect the session timeout issue, hence we need to improve the error message to reflect the real behaviour. 

Note - We should specifically be mentioned that the session is timeout

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
