### ISSUE TITLE
Invalid API resource request being sent in non super tenant console

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#17375]
**Describe the issue:**
When trying to display the permissions of a particular role in the Roles tab of a non super tenant console, following error can be seen

![Screenshot 2023-10-30 at 09 47 33](https://github.com/wso2/product-is/assets/45028707/3cdeaafc-bb37-4322-b487-819cf6515478)

This is due to an invalid request being sent to the API resources endpoint.

![Screenshot 2023-10-30 at 10 02 43](https://github.com/wso2/product-is/assets/45028707/9642873e-1010-4930-bd2f-1f13c1dabdab)

**How to reproduce:**

- Login to non super tenant console and go to roles tab.
- Create a role
- View the permissions of the role

**Comment by JayaShakthi97** [comment]
This happens due to the incompatibility of API resource ID extracting logic. Logic is not compatible with non-super tenants since the ref URL length is different.
- Fix: https://github.com/wso2/identity-apps/pull/4443

**Comment by JayaShakthi97** [comment]
Verified in Alpha release

https://github.com/wso2/product-is/assets/37938529/8df96dc8-6a69-42f2-a613-9b1aa98e72ee
