### ISSUE TITLE
[Doc] Swap the image placements under 3rd step in Configure Google Doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1737]
3rd step in Configure Google Doc [1] ask user to configure the Google authenticator in IS side with Callback Url and Client id and Secret. But the image right after the description has the google side configuration information instead of configurations need to be done in Identity Server side. So it's better to swap 2 images with each other to give a proper understanding to the user.

![google config - 3rd step](https://user-images.githubusercontent.com/8849472/34143981-84c6c9da-e4b5-11e7-8b1a-7aa8275f61f2.png)

[1] https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
