### ISSUE TITLE
User not redirected to error page upon wreply url mismatch in Passive STS login flow

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#17379]
**Describe the issue:**
If the wreply url in the authentication request is different to the wreply url configured in the service provider, the user is still redirected to the wreply url in the request instead of being sent to an error page. 
There is currently a validation to verify the configured url (Passive STS WReply URL) is equal to the url in the request and a soap fault is set, but the user is still redirected to the wreply url given in the request.

**How to reproduce:**
1. Register a SP with WS-Fedaration (Passive) for inbound authentication.
2. Get the sample app PassiveSTSSampleApp.
3. Configure a url different to wreply url set in the configuration as the "replyUrl" url in the web.xml in the sample app.
4. Attempt to login using the sample app.

**Expected behavior:**
The user should be redirected to an error page stating that the wreply url in the request is different to wreply url configured. (Similar to callback url mismatch behaviour in the oauth flow).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
