### ISSUE TITLE
Unable to delete custom claims even the external claims are deleted

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17374]
**Describe the issue:**

1. Create a custom attribute with OIDC/SCIM attribute mapping
2. Try to delete the local attribute . Failed to delete saying external claim mappings are there. -> Expected
3. Delete all external claims mapped to it.
4. Come back to local claim and try to delete. Still it says that claim is mapped to external claims -> Issue
5. Restart the server and try to delete the local claim. Still fail to delete -> Issue (This means it's not a caching issue too)

**Comment by ChanikaRuchini** [comment]
This is a front end issue. when creating a custom local claim with only a OIDC claim( by removing scim mapping from the UI), a scim claim also get created. by deleting the scim claim and oidc claims, local claim can be deleted.  

[Untitled_ Oct 30,2023 12_55 AM.webm](https://github.com/wso2/product-is/assets/36252774/18c44a53-9311-4943-a866-a5f478d57c57)

**Comment by ChanikaRuchini** [comment]
No backend issues of deleting external claims. So close this issue. created new issue to track the above FE issues https://github.com/wso2/product-is/issues/17392
