### ISSUE TITLE
Modularize Carbon Identity Framework Repository for Improved Build Times

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#17380]
**Is your suggestion related to an experience ? Please describe.**
The current build time for the Carbon Identity Framework stands at around an hour, primarily due to its 20+ components.

This monolithic structure can significantly hinder development velocity and overall project maintainability. Therefore, it's suggested to pursue a modularization strategy to mitigate these challenges. However, this effort may introduce certain complexities

**Modularization Strategy:**

- Separate Repositories: 
Extracting some of the components into their own repositories could be a viable approach to modularize the project, allowing for parallel development and independent versioning.

- Inter-Repository Dependencies: 
Establish clear inter-repository dependencies to ensure seamless integration and compatibility between different components.

**Potential Complexities:**

- Cyclic Dependencies: 
There might arise cyclic dependency issues when extracting some components into separate repositories. This scenario is likely if components have tightly coupled relationships with each other.

- Dependency Management:
        Managing dependencies across multiple repositories could become a complex task, particularly when there are breaking changes in one component affecting others.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
