### ISSUE TITLE
Throttle role name validation API call when creating a new role

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#17385]
**Is your suggestion related to an experience ? Please describe.**

Currently, for each keystroke API call is fired to validate the role name.

https://github.com/wso2/product-is/assets/37938529/b42ea72c-d05c-4d18-be32-a601bb8a1533

**Describe the improvement**

This needs to be throttled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
