### ISSUE TITLE
Getting a 404 Error when Navigating to My Account after FIDO Error Page

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#17381]
**Describe the issue:**
When a pass key is not enrolled for fido authentication, user is redirected to the following error page.
<img width="484" alt="image" src="https://github.com/wso2/product-is/assets/47671237/19f40c95-84cf-418b-a90f-bd31278d23d6">

The Myaccount url linked at this page will lead to a 404 page not found error because the myaccount url is not resolved correctly.
<img width="941" alt="image" src="https://github.com/wso2/product-is/assets/47671237/7b1eecce-65d3-4759-b481-17700e99e195">

**How to reproduce:**
1. Configure fido as an authenticator without configuring the pass key.
2. Click on the myaccount url at the `No enrolled passkey found ` error page

**Expected behavior:**
User should be redirected to the myaccount login.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AfraHussaindeen** [comment]
Resolved via https://github.com/wso2/identity-apps/pull/4380


https://github.com/wso2/product-is/assets/47135592/9aeb03bb-c066-47c4-9744-77a56ea7d813
