### ISSUE TITLE
Add organization administrator button is not working in the console

### ISSUE THREAD

**Issue by ThaminduR** [wso2/product-is#17386]
**Describe the issue:**

Add organization administrator button is not working in the console

**How to reproduce:**

Go to Administrators tab in the console and try to add an admin.

**Comment by JayaShakthi97** [comment]
Didn't released with alpha. Hence moving the milestone.

**Comment by JayaShakthi97** [comment]
This is a regression due to an improvement in Add User Wizard.
- Fixed with: https://github.com/wso2/identity-apps/pull/4454
