### ISSUE TITLE
A configuration to indicate whether all orgs in the hierarchy should be discovered only via the email domain or not

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#17399]
Organization discovery with email domain in B2B login flow has been implemented with https://github.com/wso2/product-is/issues/16379. 

I've included the current experience below:

1. The user accesses the B2B app and clicks on sign-in with SSO.
2. The user can either enter the email or provide the organization name.
3. The user gets directed to the correct sub organization for authentication.

When the configuration is enabled for this feature, there should be a way to indicate whether all the organizations in the hierarchy should be discovered via the email domain or not. If all organizations are to be discovered with email domains, we should not provide an option to provide the organization name. This issue is created to track this improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
