### ISSUE TITLE
Doc search: configure captcha for password reset

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1739]
Please see the below image, when searched with "configure captcha for password reset" the result set does not include the relevant document at all

![is_doc_6](https://user-images.githubusercontent.com/15624590/34144312-fa6810bc-e4b6-11e7-918d-ce5c7ddead1f.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
