### ISSUE TITLE
UI improvements in the email domain discovery feature

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17390]
**Describe the issue:**

1.The user  should notify that the email as a username feature has to be configured to tryout the end-to- end  flow sucessfully
<img width="1090" alt="Screenshot 2023-10-30 at 12 16 43" src="https://github.com/wso2/product-is/assets/40081059/10fd026a-2eff-44c1-b368-cc3bfbe9ddf6">

2.Better to provide an example of the expected email.domain for better clarity 
<img width="1090" alt="Screenshot 2023-10-30 at 12 16 43" src="https://github.com/wso2/product-is/assets/40081059/c0a38bee-eca0-414f-9bc6-13afead7cd84">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Rashmini** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/4466
