### ISSUE TITLE
Missing Option to Add or Remove Roles in User's Role Edit Tab

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17393]
**Describe the issue:**
the description stating "Add or remove the roles this user is assigned," there is currently no visible option to add or remove roles in the User's Role Edit tab.

**How to reproduce:**
1. Log in as an administrator.
2. Navigate to the User Management section.
3. Select a user and access the Role Edit tab.
4. Observe the absence of options to add or remove roles.

**Expected behavior:**
As shown in the description provided, the User's Role Edit tab should contain an option to add or remove roles for users.

**Environment information**
* Product Version: wso2is-7.0.0-alpha-SNAPSHOT
* OS: Mac -
* Database: Mysql - 8.1.0
* Userstore: JDBC
* Browse - Safari, Firefox
---

<img width="1413" alt="Screenshot 2023-10-30 at 13 22 41" src="https://github.com/wso2/product-is/assets/39120228/cfb44fa7-53b6-4d40-8a92-0c6478d455b0">

**Comment by DilshanSenarath** [comment]
This is intentionally disabled in this section. However, the text needs to be updated. This issue is being tracked at https://github.com/wso2/product-is/issues/17636.
