### ISSUE TITLE
Branding is not applied to email templates

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17405]
**Describe the issue:**
even though branding is configured for a tenant, the branding changes are not visible in the received emails. However the changes will be previewed in the email templates section.

![Screenshot from 2023-10-30 16-35-36](https://github.com/wso2/product-is/assets/35653110/e513db30-7195-4618-a3fe-61a9320ba0b0)

![Screenshot from 2023-10-30 16-35-25](https://github.com/wso2/product-is/assets/35653110/a358748c-3820-4417-a93e-1c44adec0d21)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5120
