### ISSUE TITLE
Improve Sub-Organizations Users Page to Clearly Indicate Shared Users from Parent Organization.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17402]
**Describe the issue:**
The Sub-Organization Users page fails to accurately reflect that the admin user is shared from the parent organization and managed by it.

<img width="1477" alt="Screenshot 2023-10-30 at 15 06 21" src="https://github.com/wso2/product-is/assets/41188245/f1a75588-4c94-4b66-8436-5d68c3b71ee1">

**Expected behavior:**
It's better to have at least a `managed-by` label to improve the user experience there.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
will be improving to add a label indicating that this user is from a parent org
