### ISSUE TITLE
UI Error message given when trying to create two service providers with same name is not meaningful

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1740]
**Environment**
Standalone 5.4.0 GA pack
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**

1. Run Standalone IS 5.4.0 GA pack
2. Add a Service Provider by giving name as abc
3. Try to add another service provider with the same name

Observation
Error message will be displayed in the UI as [1]. The error message given is not meaningful. Provide a meaningful error message than this

[1]. sp-create-error.png

![sp-create-error](https://user-images.githubusercontent.com/31848014/34144103-1ee326f8-e4b6-11e7-960c-3f94f73df716.png)

**Comment by deshankoswatte** [comment]
This is **fixed** in IS _5.10.0-M4_:

![Screenshot from 2019-10-29 13-59-54](https://user-images.githubusercontent.com/33062368/67750149-9f667680-fa54-11e9-8425-523fe0b08fdb.png)
