### ISSUE TITLE
Empty Page with Error Message When Clicking "Setup" Link for Backup Code Authenticator on Connection Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17419]
**Describe the issue:**
Encountering an empty page with an error message when clicking the "Setup" link for the Backup Code Authenticator on the connection page. 

**How to reproduce:**
1. Login to Console
2. Navigate to Connection page
3. Filter connections by click on "MFA"option
4. Click on the "Setup" link for the Backup Code Authenticator. 

**Expected behavior:**
Clicking the "Setup" link for the Backup Code Authenticator should allow users to set it up without encountering errors. 

**Environment information** 
* Product Version: wso2is-7.0.0-alpha-SNAPSHOT
* OS: Mac -
* Database: Mysql - 8.1.0
* Userstore: JDBC
* Browse - Safari, Firefox

[recording(7).webm](https://github.com/wso2/product-is/assets/39120228/81f5998f-9952-4f35-974e-bcd24bb08f16)

**Comment by AnjanaSamindraPerera** [comment]
This is not available in wso2is-7.0.0-beta-snapshot 
![Screenshot 2023-11-14 at 10 15 23](https://github.com/wso2/product-is/assets/38417165/bd504e84-c4a3-4ffa-b707-78cd576ecae1)
