### ISSUE TITLE
Unable to detect the QR code generated when confuguring passkey through my account

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17410]
**Describe the issue:**

Unable to detect the QR code generated when confuguring passkey through my account

Tried to scan the QR code with various scanners , but couldn't detect the QR code

https://github.com/wso2/product-is/assets/40081059/e907bdf0-5fe6-44ed-8f4a-d06235640658

<img width="504" alt="Screenshot 2023-10-30 at 15 50 13" src="https://github.com/wso2/product-is/assets/40081059/e1873b11-ee14-41a9-87ed-ac4d7cfcffc0">

**How to reproduce:**

1. Login to the myaccount
2. Go to security 
3. Try to configure passkey by phone or tablet option

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduDilshan** [comment]
This QR code is generated from the browser and we don't have any control over it. On a side note this QR code supposed to be scanned on a device which supports FIDO passkeys (ideally a mobile phone with passkey support) and not from a regular QR code scanner.

Refer for device support matrix: https://passkeys.dev/device-support/#matrix

**Comment by asekawa** [comment]
@ThaminduDilshan checked this on various QR code mobile applications ,on ios device. 
Still couldnt reproduce it

**Comment by madurangasiriwardena** [comment]
@asekawa, you have to use the phone camera or a QR scanner for this to work.

However, there are some issues if you are using Samsung mobile devices with "Samsung Pass" application to store the passkey. If you use Google password manager to store the passkey, this is working fine. Hence closing the issue.
