### ISSUE TITLE
Getting  'Something Went Wrong' Issue in some Governance Connectors for Tenanted Flow

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17416]
**Describe the issue:**

Encountering "Something Went Wrong" Error in "Login & Registration" -> "Governance Connectors" for tenanted flow. 
The following connectors are affected by this issue

1. Password Policies
2. Login Attempts Security
3. Multi Factor Authenticators
4. Other Settings

<img width="1512" alt="Screenshot 2023-10-30 at 18 19 04" src="https://github.com/wso2/product-is/assets/41188245/2c46e314-df92-457d-a86e-50de9a3616f1">

https://github.com/wso2/product-is/assets/41188245/5fb6960f-3193-4b8a-b3de-d429e956aa33

**How to reproduce:**

1. Create a tenant.
2. Login to the console using tenanted path.
3. Navigate to the `Login & Registration`
4. Try to load the above mentioned connectors.

**Expected behavior:**
This should load the relevant UI s.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

 - Product Version: https://drive.google.com/file/d/1e1WrjxJdhEbujc5brM5vdPFwIKBmXQos/view?usp=sharing
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
> This issue is occuring due to the block of code https://github.com/wso2/identity-

With the latest changes, identification of the level of the org logic should be different. Since this block of code is old, we may have to revisit.

**Comment by savindi7** [comment]
We should list all the Governance Connectors for the Super Admin and the first level tenants.. and for the rest, it is already handled.

Suggesting to remove the block of code mentioned in my previous comment. wdyt? @NipuniBhagya
