### ISSUE TITLE
Browser Console Error 400 When Filtering Connections via "MFA" Option

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17418]
**Describe the issue:**

Upon attempting to filter connections using the "MFA" option, users are encountering a 400 error in the browser console. 

**How to reproduce:**
Access the connections filter functionality.
Select the "MFA" option to filter connections based on MFA status.
Observe the browser console and notice the 400 error appearing.

**Expected behavior:**
Users should be able to filter connections using the "MFA" option without encountering any errors. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
* Product Version: wso2is-7.0.0-alpha-SNAPSHOT
* OS: Mac -
* Database: Mysql - 8.1.0
* Userstore: JDBC
* Browse - Safari, Firefox

---

<img width="1725" alt="Screenshot 2023-10-30 at 18 47 42" src="https://github.com/wso2/product-is/assets/39120228/76927d7f-f6c5-4702-b9e0-af8669edb45f">

**Comment by madurangasiriwardena** [comment]
Same request is sent 3 times.

**Comment by ThaminduDilshan** [comment]
When filtering connections, two different API calls are made; one to the identity-providers endpoint (`https://localhost:9443/t/carbon.super/api/server/v1/identity-providers`) and another to the authenticators endpoint (`https://localhost:9443/t/carbon.super/api/server/v1/authenticators`).

The authenticators endpoint call gets success and returns the filtered result (Ex: filtered MFA connections). The identity-providers endpoint call returns 400 as it doesn't support filtering with tags. IDP filtering is implemented only for the idp name, description, home realm, enabled and UUID attributes ([refer code](https://github.com/wso2/carbon-identity-framework/blob/5b7138f04fb974349e2e0a3157b9ce2109f58313/components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/dao/IdPManagementDAO.java#L908-L928)).

Currently tags are only applicable for authenticators and not identity-providers. Hence when filtering, the additional frontend call for idps with filtered param should be prevented.
