### ISSUE TITLE
Alert messages doesnt change with the language translation in myAccount

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17411]
**Describe the issue:**

Alert messages doesnt change with the language translation in myAccount

https://github.com/wso2/product-is/assets/40081059/36d606aa-590d-4a2f-8efc-36e805eff9ce

**How to reproduce:**

1.Go to the my account
2.Change the language from the defualt language
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment]
This issue is fixed in the latest identity-server hence closing the issue.

https://github.com/wso2/identity-apps/assets/46097917/749afb3b-5068-4428-b8f4-c0f2aa70f1ef
