### ISSUE TITLE
Support federated IDP groups to role mapping

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#17429]
**Is your suggestion related to an experience ? Please describe.**
Currently we only support local group to role mappings. We need to support federated IDP groups to role mappings.

**Comment by JayaShakthi97** [comment]
- Frontend task: https://github.com/wso2/product-is/issues/17780

**Comment by SujanSanjula96** [comment]
Implemented with following PRs -
https://github.com/wso2/carbon-identity-framework/pull/5143
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/504
