### ISSUE TITLE
Update the install as a windows service doc with JDK 11 support

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#17427]
**Is your suggestion related to a missing or misleading document? Please describe.**
In [1], we have added a sample wrapper.conf file which can be used to install WSO2 IS as a windows service. Following params are missing in the sample conf file if using the the jdk > 11.0.20

```
wrapper.java.additional.29 = -Djdk.util.zip.disableZip64ExtraFieldValidation=true
wrapper.java.additional.30 = -Djdk.nio.zipfs.allowDotZipEntry=true
wrapper.java.additional.31 = -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
```

[1] https://is.docs.wso2.com/en/latest/deploy/get-started/install/#install-as-a-windows-service

**Describe the improvement**
Update the doc.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
