### ISSUE TITLE
Sign In URL received from Magic Link Authentication is Broken

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#17421]
**Describe the issue:**
The Sign in url received through email during Magic Link authentication is not working. The URL does not properly resolve the needed parameters and therefore does not redirect to the required page.

Ex: Sign in URL received through email
```
https://localhost:9443{{caller.path}}?mlt=wiTOYYlzs158zJ8xuNgrnHHzUdyFDKl5
```

**How to reproduce:**
1. Configure an application and add magic link as the local authenticator. 
2. Try logging in to the app.
3. Enter the username and check for the email.
4. Click on the Sign in button. This will not work.
5. Copy the link from the Sign in button. This will be an invalid URL.

**Expected behavior:**
Successful authentication and should redirect back to the application.

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-event-handler-notification/pull/209
