### ISSUE TITLE
[Doc] Image which displayed google side information doesn't shows the client secret

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1743]
The image listed under 3rd step in [1] only shows the Client ID and it's better to replace the image with a one which has the client secret (with a step to go to the screen as well).

![google5_e](https://user-images.githubusercontent.com/8849472/34144749-f041f380-e4b8-11e7-8bd1-748bc0a5d9bb.png)

to

![cliend id and secret google](https://user-images.githubusercontent.com/8849472/34145226-ff169ed6-e4ba-11e7-9ed8-c9adee0da0a7.png)

[1] https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
