### ISSUE TITLE
Unable to configure group based authentication into an application

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17432]
**Describe the issue:**

Unable to configure group-based authentication into an application. 
when you select group-based authentication  from conditional authentication and update, the scrip disappears.

https://github.com/wso2/product-is/assets/40081059/08dc10fc-5907-4c10-b223-572af906c34e

**How to reproduce:**

1. Login to the console
2. Create an application
3. Go to the sign in methods of the application
4. Go conditional authentication section 
5. Choose roles based authentication 
6. Update

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
Further Analysis :
This doesnt show the authentication is updated real time like other authenticators .But if we refreshed and see  we can see the autheticator is updated

**Comment by ashanthamara** [comment]
Issue is not reproducing (Console version `2.6.2`)


https://github.com/wso2/product-is/assets/75057725/9d8b5d51-3050-4de3-a7eb-b2278efd8ea1
