### ISSUE TITLE
Password recovery option is not by default enabled for organizations

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17434]
**Describe the issue:**

In B2B use cases, identity governance of organizations should be governed by the root tenant. Since that feature is not yet available,
enabling password recovery for organizations has been a blocker.
If the organization has allowed using username-password-based login, password recovery is a common requirement. 
Hence we have decided to enable password recovery by default in orgniazations.

But it's not happening in Is-7.0.0-alpha

**How to reproduce:**
1. Create an organization
2. Create an application and share it with orgs
3. Try appication login with SSO
4. Give the org name
5. In the login page, you should see password recovery option

**Comment by sadilchamishka** [comment]
- Fixed by - https://github.com/wso2/carbon-identity-framework/pull/5122
