### ISSUE TITLE
Getting a invalid URL message when we try to access the magic link through the received email

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17446]
**Describe the issue:**

Getting a invalid URL message when we try to access the magic link through the received email

<img width="1507" alt="Screenshot 2023-10-31 at 16 31 05" src="https://github.com/wso2/product-is/assets/40081059/362066d7-9462-48bb-ba37-c333c7160e33">

https://github.com/wso2/product-is/assets/40081059/d60aef61-04bf-4c1d-88c3-cda371b6b546

**How to reproduce:**

1.Go to the console
2.Create and application
3.Set up basic as 1 st factor  magic link as the 2nd factor  as the sign in method.
4.Go to the login flow ,  enter usrname and pws and complete the password 
5.Click on continue
6.Go to the received email and click on the  "Sign in" button

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-event-handler-notification/pull/209
