### ISSUE TITLE
ReCaptcha is not visible even when the security questions attempts have exceeded given limit

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1744]
**Tried with**
1. Google chrome Version 63.0.3239.108
2. Firefox 57.0.1 (64-bit)

Os: Ubuntu 16.04
JDK : 1.8.0_144

**Steps**
1. Followed [1] to configure reCaptcha
captcha-config.properties
```
# Google reCAPTCHA settings

# Enable Google reCAPTCHA
recaptcha.enabled=true

# reCaptcha API URL
recaptcha.api.url=https://www.google.com/recaptcha/api.js

# reCaptcha verification URL
recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify

# reCaptcha site key
recaptcha.site.key=6LeL8iATAAAAABEWUx1LwFAiSCT06fY7Kfra5WcT

# reCaptcha secret key
recaptcha.secret.key=6LeL8iATAAAAAJUgXu_ZgEm_dOC3AT4gmWRstil4
```
2. Followed [2] to associate with the resident IDP
![is_issue_8](https://user-images.githubusercontent.com/15624590/34145283-48c04cda-e4bb-11e7-88e3-9471121a9960.png)

But even when the max failed attempts exceeds, the reCaptcha is not appearing

[1] https://docs.wso2.com/display/IS540/Setting+Up+ReCaptcha
[2] https://docs.wso2.com/display/IS540/Configuring+reCaptcha+for+Password+Recovery+Flow

**Comment by madurangasiriwardena** [comment]
For the reCaptcha to appear, we need to enable account locking. This seems to be not captured in the doc properly. Updated the 5.8.0 docs.

https://docs.wso2.com/display/IS580/Configuring+Google+reCaptcha+for+Security-Question+Based+Password+Recovery
