### ISSUE TITLE
Remove MyAccount access link from console application's header dropdown

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17451]
**Describe the issue:**

The MyAccount link needs to be removed from the console application's header dropdown.

<img width="1272" alt="Screenshot 2023-10-31 at 19 55 31" src="https://github.com/wso2/product-is/assets/25483865/7f445abd-0b75-43f1-a115-4cfbcf6a4007">

Only the logged-in user information and logout button should be visible in the Console header.

**Comment by Achintha444** [comment]
* Closing this issue as a decision was taken to keep the `My Account` label as it is in the header.
- https://github.com/wso2/product-is/issues/17900
