### ISSUE TITLE
"Email Domain Discovery" configuration should be moved to different location

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17455]
**Describe the issue:**
Email domain-based organization discovery feature was introduced with IS-7.0.0. The option to enable this feature is under Organization Management as follows.
<img width="891" alt="Screenshot 2023-10-31 at 20 14 33" src="https://github.com/wso2/product-is/assets/25483865/4785bee7-01d2-4897-80ea-0740a672964e">

Once it's enabled, the admin can define email domains for any organization in the subtree by clicking `+Assign Email Domain`
<img width="1395" alt="Screenshot 2023-10-31 at 20 20 28" src="https://github.com/wso2/product-is/assets/25483865/78d05255-2c5e-47d2-87be-c10097e50784">

**Suggestion to Improve:**

- Email domain-based organization discover feature enable/disable config should go under `Login & Registration` section.
Under `Login & Registration` user should be able to find `Organization Discovery` tile.
Under that category show `Email domain based discovery` enable/disable config

- In order to claim an email domain for an organization, need to go to the edit view of a given organization. Claimed email domains also need to be shown in the same page.
<img width="1267" alt="Screenshot 2023-10-31 at 20 25 12" src="https://github.com/wso2/product-is/assets/25483865/afe0db66-6178-4f14-b4b2-7872e3a88dfd">

NOTE: There is a limitation to implement the second suggestion. From the root tenant admin can see only the first level organization in the subtree. but the admin might want to configure an email domain for an organization below the first level

**Comment by dewniMW** [comment]
The entire email domain discovery view will be moved as a new tile under `Login & Registration` section (both enabling the config and mapping email domains to organizations will happen in this view).

**Comment by nipunsampath** [comment]
During offline discussions, it was decided to: 

- Add a section for email domain discovery in the `Login & Registration` page where users will be allowed to:
    - 	Enable/disable email domain discovery for its immediate child organizations.
    -   View organizations that have configured email domains along with their configured email domains.
- Allow configuring email domains for a organization via a separate tab in the settings page of the organization. 
- Conditionally render the above mentioned tab only if the email domain discovery is enabled.
