### ISSUE TITLE
Clearly represent API resources with proper separation

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17453]
**Describe the issue:**
Now API resources section contains all the IS tenant management APIs, end user related APIs, organization management APIs, and user defined custom APIs in a single list.

<img width="1712" alt="Screenshot 2023-10-31 at 19 56 53" src="https://github.com/wso2/product-is/assets/25483865/2c9ec08a-860e-4f02-84d2-7c0eddf56bfe">

**Expected Behavior:**

-  IS defined APIs and customer defined Business APIs should be separated.
-  IS defined APIs should be further separated under 
    -  Server management APIs (eg: /api/server/v1/applications)
    -  Organization APIs  (eg: /o/api/server/v1/applications)
    - End user APIs (eg: /Me endpoints)

- Need to have filtering capability in API resources UI

**Comment by thanujalk** [comment]
As per the feedback received the following experience is agreed upon.

- Define API resource types
  - System APIs (Multi-tenancy APIs, etc.)
  - Tenant APIs (Application management, User management, etc.)
  - Tenant User Me APIs (User Me, etc.)
  - Organization APIs (Application management, User management, etc.)
  - Organization User Me APIs (User Me, etc.)
  - Custom APIs
- On the API resources page, above categories will be available.
- When clicking on each section, a filtered list from the type will be listed
- API search by name also available in this section
- This will be available when authorizing APIs to applications and assigning scopes to roles.

**Comment by DonOmalVindula** [comment]
UI task related to this feature is done. However, categorization is yet to be finalized. The FE will categorize the APIs accordingly based on the values receive from the BE as of now

**Comment by dewniMW** [comment]
> UI task related to this feature is done. However, categorization is yet to be finalized. The FE will categorize the APIs accordingly based on the values receive from the BE as of now

Closing this issue as the BE PR is also merged.

**Comment by dewniMW** [comment]
> @madurangasiriwardena we need to review the categorization

@malithie @madurangasiriwardena we will schedule a meeting to review the current categorization.
