### ISSUE TITLE
Improve the UX of email domain based organization recovery during login flow

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17456]
**Current Behavior**
Email domain-based organization recovery feature works as follows in the B2B user login flow.
1. Land to the login portal of B2B application
2. Click on Sign in with SSO
3. If the email domain based org discovery feature is enabled in the B2B organization, enter email option is visible.
4. By giving an email which has a claimed domain, user will be redirected to the resolved organization's login page
5. If the org resolving is failed, user has the option to reenter different email/ proceed with giving organization name

<img width="661" alt="Screenshot 2023-10-31 at 21 30 15" src="https://github.com/wso2/product-is/assets/25483865/9eb29d29-a011-4965-901a-33b760dd728e">

https://github.com/wso2/product-is/assets/25483865/e8314d52-256e-4f14-80b7-6cfe9b87a494

**Describe the improvement**

- If email domain-based org discovery is enabled, the identifier first handler should be set as the first step of B2B applciation login flow
- We need to have an organization resolving handler, that need to be plugged as the second step of the B2B application
- During the application login user has to give an email first, based on the input internally resolve the organization by organization resolving handler.
- If the resolution is successful, land the user to the login page of the discovered organization.
- If failed, redirect the user to input the organization name(optional. It should be able to decided by B2B organization)
- Under the fallback case, we need to give root business's login option as well if the root business users also wants to use the application (Btw, this point is negatively impacted to UX)

NOTE:
* If we want to automate the application login flow changes based on email domain-based org discovery feature enablement, feature configuring person should select what are the application that you want have this login flow.
* If root business users also need to log into an application that uses email domain-based org discovery feature, he need to go through email domain-based org discovery resolver failure path. This will negatively impact the UX.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
