### ISSUE TITLE
Application should be able to authorize to multiple APIs at once

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17454]
**Describe the issue:**
When you need to authorize multiple APIs to an application, you have to select API resources one by one and authorize as shown in the following recording.

https://github.com/wso2/product-is/assets/25483865/43fb1ad4-840b-431c-bb6a-c4929362d3f5

**Expected behavior:**
There should be a capability to authorize to multiple API resources at once.
There should be a capability to authorize to all system APIs at once.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
