### ISSUE TITLE
Need to have two different Myaccount applications for admin user and business users

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17452]
**Describe the issue:**

Currently, for a given tenant there is a single myaccount application for admin users and business users.
To serve the myaccount capabilities for different personas 
(eg: define specific login flow for business users of the tenant and another login flow for admin users)
there should be two my account applications.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
