### ISSUE TITLE
[Doc] Move order of fields listed in table to fill google IDP details according to the UI

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1746]
It's better to reorder the fields in Table listed under 4th step of 'Configure Google' [1] according to the UI in Identity Server side while configure Google as IDP. So the idea order should be 'Enable', 'Default', 'Client id', 'Client Secret', 'Callback url' and 'Additional Query Parameters'.

[1] https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by Nashaath** [comment]
This is already fixed in docs.
