### ISSUE TITLE
User name is not avaiable in the My Account

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#17463]
**Describe the issue:**
After login to the myaccount username is not visible.
<img width="1439" alt="Screenshot 2023-10-31 at 11 36 06 PM" src="https://github.com/wso2/product-is/assets/51480027/d88d924e-cd5e-465e-8ca5-31cee3ac2782">

**How to reproduce:**
Login to the My Account and click on profile

**Comment by Achintha444** [comment]
This issue is fixed in the latest identity-server hence closing the issue.
<img width="1269" alt="Screenshot 2023-11-15 at 12 17 56" src="https://github.com/wso2/identity-apps/assets/46097917/f57841cb-03ba-499c-9804-359cadf51d09">
