### ISSUE TITLE
Management Console Login is not working after enter the credential

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#17460]
**Describe the issue:**
After entering the login credentials to the management console, mgt console goes to a blank screen.

**How to reproduce:**
1. Go to https://localhost:9443/carbon// (Add another / to the end)
2. Enter credentials
3. Toy will be redirected to a blank page (https://localhost:9443/carbon//?loginStatus=true)

**Expected behavior:**
Should not redirect to a blank page after the login screen.

https://github.com/wso2/product-is/assets/51480027/f15835a7-b372-4cda-a7a5-efdf21eb8364

**Comment by madurangasiriwardena** [comment]
Is there any particular need to enter the additional `/` in the URL?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
