### ISSUE TITLE
Newly added application audience roles are not reflated under the given application's  role tab immediately

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17469]
**Describe the issue:**
1. Create an application
2. Go to it's Role tab and set "Application" as the allowed role audience 
3. Go to roles tab under User Management
4. Add a new role, selecting the application audience and selecting the application which is created in step 1
5. Go back to the applications list and select the application created in step 1
6. Go to it's role tab.
7. The added role in step 4 should be visible as an associated role.
8. The API response for the application has returned that value, but UI doesn't show it
9. If you go back and come,it is visible

https://github.com/wso2/product-is/assets/25483865/8ff6c2de-6644-43e3-86ef-20f4ce55b833

**Comment by DonOmalVindula** [comment]
Fixed with https://github.com/wso2/product-is/pull/17516
