### ISSUE TITLE
Parent user invitation modal always show the root org. 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17465]
**Describe the issue:**

- Go to carbon.super tenant
- Create an organization
- switch to the created organization.
- create an organization inside.
- Try the invite parent user feature. 
- The modal will show invite from "carbon.super" (which is the root org)

https://github.com/wso2/product-is/assets/25483865/2f568076-ccbe-4627-a684-d9bb42672f97

**Expected behavior:**

- Also this should show, immediate parent's **organization name**
- carbon.super is the tenant name. That also need to be fixed

**Comment by sadilchamishka** [comment]
How to retrieve the parent org name from the child organization?

**Comment by AnuradhaSK** [comment]
> How to retrieve the parent org name from the child organization?

can't we use /api/users/v1/me/organizations/root/descendants ?

**Comment by sadilchamishka** [comment]
> > How to retrieve the parent org name from the child organization?
> 
> can't we use /api/users/v1/me/organizations/root/descendants ? and resolve the current org's parent org name?

Here the inivitations are made by the organization admin who is not aware of the parent neither get the result which is expected by the above API call.
