### ISSUE TITLE
[Doc] Typos in 'Configuring Google' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1747]
Following typos need to be fixed in 'Configuring Google' doc [1]

1. This is the password from the Google application you created from **goole** developer console.
2. This is the username from the Google application you created from **goole** developer console.

[1] https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by shavidissa** [comment]
This has been updated.
[1] https://docs.wso2.com/display/IS540/Configuring+Google
