### ISSUE TITLE
Not properly Update Custom User Attributes Upon Page Refresh or Navigating Back from Another Tab/Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17475]
**Describe the issue:**
Currently, all configured and saved application custom user attributes are disappearing when users refresh the page or navigate back from another tab or page. This

**How to reproduce:**
1. Configure and save custom user attributes in the application.
2. Refresh the page or navigate away to another tab/page.
3. Return to the original tab/page.
4. Observe that the previously configured custom user attributes  not updated.

**Expected behavior:**
Custom user attributes should persist even after page refresh or when users navigate away and then return to the application. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Alpha 7.0
 - OS: Mac, Linux
 - Database: MySQL, H2, MSSQL, Postgres
 - Userstore: LDAP, JDBC

---
[updateissue1.webm](https://github.com/wso2/product-is/assets/39120228/eee1910b-a90c-4ebf-8781-ef309bae2b0a)

**Comment by madurangasiriwardena** [comment]
Upon further analysis, this seems to be a race condition. When you update the claim configs from the UI, there are 2 update requests are invoked.

```
curl 'https://localhost:9443/t/carbon.super/api/server/v1/applications/7e254aca-8aae-4d9c-ae4b-5e775c4f5723' \
  -X 'PATCH' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{"claimConfiguration":{"dialect":"LOCAL","requestedClaims":[],"role":{"claim":{"uri":""},"includeUserDomain":true}}}'
```

```
curl 'https://localhost:9443/t/carbon.super/api/server/v1/applications/7e254aca-8aae-4d9c-ae4b-5e775c4f5723/inbound-protocols/oidc' \
  -X 'PUT' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{"clientId":"JMeiAQWdP8ft5qxd4fKrFQfrF2Qa","clientSecret":"ZoQ9rd2qEmAgKOBsPCfJfx3bH2SpVSRGEy2WWZPfNSIa","state":"ACTIVE","grantTypes":["client_credentials"],"callbackURLs":[],"allowedOrigins":[],"publicClient":false,"pkce":{"mandatory":false,"supportPlainTransformAlgorithm":false},"accessToken":{"type":"Default","userAccessTokenExpiryInSeconds":3600,"applicationAccessTokenExpiryInSeconds":3600,"revokeTokensWhenIDPSessionTerminated":false,"validateTokenBinding":false},"refreshToken":{"expiryInSeconds":86400,"renewRefreshToken":false},"idToken":{"expiryInSeconds":3600,"audience":[],"encryption":{"enabled":false,"algorithm":"","method":""}},"logout":{},"validateRequestObjectSignature":false,"scopeValidators":[],"clientAuthentication":{},"requestObject":{"encryption":{"algorithm":"","method":""}},"pushAuthorizationRequest":{"requirePushAuthorizationRequest":false},"subject":{"subjectType":"public"}}' \
```

Though these are going as 2 update requests for 2 sections of the application, the whole application is updated with both of the requests. 

In the backend first we get the application configuration and then update the application object with the requested changes in the request. Then we delete the application details and recreate it with the updated objects. Now when we take the application for the 2nd request the claims are not modified yet, and when we update the application for the 2nd request, it will override the claims again.
