### ISSUE TITLE
Getting Started Page Not Loading Properly and Create Application Button Not Visible When Switching Back from a Sub-Organization

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17479]
**Describe the issue:**

When the admin user switches from a sub-organization back to the super organization, the Getting Started page fails to load properly initially. However, upon refreshing the page, all components are loaded correctly.

https://github.com/wso2/product-is/assets/41188245/ffd1640e-de55-44d0-9b60-b0d8a83ac14a

**How to reproduce:**

1. Create a sub Org.
2. Switch to the sub org
3. Then switch back to the super org 
4. Find the Getting Started page is missing some components
5. Navigate to applications page `Add application` button will be also not visible. 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sadilchamishka** [comment]
This is fixed in the latest IS distribution
https://github.com/wso2/product-is/assets/35717390/50d58495-1920-4a1d-8cb0-8a57a33ce76f
