### ISSUE TITLE
Cannot proceed with the Email OTP flow as it redirects to the  Sign in page when we enter the  OTP

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17476]
**Describe the issue:**

Cannot proceed with the Email OTP flow as it redirects to the  Sign in page when we enter the  OTP.
This happened even we enter both correct /incorrect otp as well as the backup code option.

The given stack trace is printed in the terminal
<img width="1503" alt="Screenshot 2023-11-01 at 09 54 07" src="https://github.com/wso2/product-is/assets/40081059/a9309138-373b-4f60-a56b-d5cb843b3fa6">

https://github.com/wso2/product-is/assets/40081059/33b560e1-b013-4d96-87a1-cc63ac271934

**How to reproduce:**

1.Login to the console
2.Create an application 
3.Go to the application
- Set basic username and pwd as 1 st factor
- Email OTP as the 2nd factor
(Make sure to enable backup code as well)
- update

4.Go to the application login page
5.Enter username and pwd
6.Click on the email otp option 
7.Enter the email otp received and proceed
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest build.


https://github.com/wso2/product-is/assets/41533942/16e201fa-2706-4e6c-99a0-ae21bc5ac88b

**Comment by pavinduLakshan** [comment]
Reproducible when the backup codes are enabled for email OTP.


https://github.com/wso2/product-is/assets/41533942/035af7f4-aff6-4a68-be46-04f82490340b

**Comment by madurangasiriwardena** [comment]
Could not reproduce the issue with the given details. Can you update the issue with the specific configs you have added for the application.

However, when the backup codes are enabled, showing below screen is incorrect IMO since there is only one login option available.
<img width="422" alt="image" src="https://github.com/wso2/product-is/assets/1332991/a3f9e173-a9d9-47bd-a01e-11a0c8707e87">
