### ISSUE TITLE
Disable the Next button on Role creation step 1 if the role name is invalid

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17470]
**Describe the issue:**

1. Created an application and authorized to few APIs
2. Go to application's Roles tab and select "application" as the allowed audience
3. Then go to Roles section under "User Management"
4. Try to create a role with an invalid role name. Give input as "Role$@#". select audience as application and select the created app.
5. It shows the error message under the role name input field but can click on the Next button
6. If you click on the Next button, the permission selection drop-down will not list any authorized API.
7. If you go back and correct the name, authorized APIs will be listed properly to select permissions

https://github.com/wso2/product-is/assets/25483865/06767a20-85ac-433a-be8d-f7c5958925eb

**Expected Behavior:**
- Disable the "Next" button if the role name input/ if the selected application's audience is invalid

**Comment by DonOmalVindula** [comment]
Fixed with https://github.com/wso2/product-is/pull/17516
