### ISSUE TITLE
Authentication Steps in Application Sign-In Method Section Not Properly Updating

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17483]
**Describe the issue:**
The "Authentication Steps" within the Application Sign-In Method section are not being updated correctly.

**How to reproduce:**
1. Navigate to the Application Sign-In Method section.
2. Update "Authentication Steps" Ex: set User name /Password as 1st Factor authenticatior &  2FActor Authenticator Email OTP 
3. Click on Update 
4.

**Expected behavior:**
The "Authentication Steps" in the Application Sign-In Method section should be regularly updated to reflect the most current and accurate information. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Alpha 7.0
 - OS: Mac 
 - Database: Mysql , H2
 - Userstore: JDBC
 - Browser : FireFox 

[recording(9).webm](https://github.com/wso2/product-is/assets/39120228/8c6b79ab-77bb-4e46-b08f-f118f2bc492a)

**Comment by Achintha444** [comment]
This is fixed in the latest console version.

https://github.com/wso2/product-is/assets/46097917/2ef124a9-73fc-4d8d-b241-1689632b56b9

Hence closing this issue, but if this issue still persists please feel free to reopen the issue.
