### ISSUE TITLE
Deleted roles are not updated immediately in application roles tab

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#17482]
**Describe the issue:**
$subject

https://github.com/wso2/product-is/assets/61885844/a5135e39-4211-4366-9f57-ffe02182b5db

**How to reproduce:**
- Create application with application role audience.
- Associate some roles to previously created application. 
- Delete some roles.  

**Expected behavior:**
- Deleted roles should be updated immediately.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
Fixed with https://github.com/wso2/product-is/pull/17516
