### ISSUE TITLE
Unable to Add Email Provider Information and Encountering Error Message and 405 Browser Network Error When Updating

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17488]
**Describe the issue:**
encountering an error message along with a 405 Browser Network Error when attempting to update their email provider information

**How to reproduce:**

1. Navigate to email provider Page (Console > Branding > Notification Channels)
2. Attempt to update the email provider information.
3. Encounter an error message and observe a 405 Browser Network Error in the network tab of the browser's developer tools.

**Expected behavior:**
Users should be able to update their email provider information without encountering errors. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:Alpha 7.0
 - OS: Mac
 - Database: Mysql
 - Userstore:JDBC
 - Browser: Safari 

---
[
[emailProvider.webm](https://github.com/wso2/product-is/assets/39120228/0ab79438-31d3-4cb3-acec-259217053095)
](url)

**Comment by madurangasiriwardena** [comment]
This is happening for the super tenant and according to few discussions, this is the expected behaviour (UI needs to provide a readonly view). Since the SMTP configs are added through config files, this feature is allowing to override it from tenants. Need to finalize if the UX is correct.

**Comment by madurangasiriwardena** [comment]
We can improve the issue in super tenant in 2 steps.
**Step 1:**
Config view option. This is a mandatory requirement.

**Step 2:**
Config edit option. This is optional for this release.
If this not added for the release, step 1 should provide a readonly view with a notice indicating how to update them through the config files.

Considering the technical complexities, I believe we can onboard the step 1 only for this release.

**Comment by ayshsandu** [comment]
Since we don't allow making changes to the super.tenant email provider in the product or haven't come across a requirement to do it in the dynamically as of now we do not need to show the email provider config in super.tenant console.

For other tenants, the option should be available over COnsole.

**Comment by malithie** [comment]
Well, we decided super tenant to be just another tenant. Above statement contradicts with that.
Compromising this for timelines is fine. But IMO it needs to be fixed later

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
