### ISSUE TITLE
The Add Administrator button is not functiontioning (Disabled)

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17487]
**Describe the issue:**

The Add Administrator button  is  is not functioning(Disabled)

https://github.com/wso2/product-is/assets/40081059/bfd66df1-3030-4dd3-affd-1a80b2b59591

**How to reproduce:**

1.Login to the console

2.Go to Administrator section and try to add a new one Admin

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Duplicated https://github.com/wso2/product-is/issues/17386
