### ISSUE TITLE
Add link to my account on backup code not enabled error page

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17485]
**Describe the issue:**

It'd be better to show a link to the my account here so that end user can directly navigate to the my account right from the error page.

<img width="1502" alt="Screenshot 2023-11-01 at 11 43 47" src="https://github.com/wso2/product-is/assets/41533942/529a9671-e203-40db-a7fb-e179d773466c">

**How to reproduce:**

1. Sign into console.
2. Create an application.
3. Go to sign in method tab and set email OTP as 2nd factor. Enable backup codes as well
4. Create a new user. (this user should not have backup code enabled in my account)
5. Sign into application using user credentials.
6. Observe the above mentioned error page once credentials are submitted.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 alpha
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
