### ISSUE TITLE
Fields Required for Input in SMS Provider Page Not Clearly Indicated as Mandatory in UI

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17494]
**Describe the issue:**
On the SMS Provider Page, there are fields that require user input (sms provider configurations), but they are not clearly marked as mandatory in the UI. Users are not aware that these fields are required, leading to confusion and incomplete form submissions. 

**How to reproduce:**
Navigate to the SMS Provider (Branding > Page in the application.
Observe the fields that require user input.
Notice that there are no visible indicators or labels denoting these fields as mandatory.

**Expected behavior:**
Mandatory fields on the SMS Provider Page should be visibly indicated in the UI, either through asterisks (*) next to the field labels or any other universally recognized symbol. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:7.0 Alpha
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

---

<img width="1328" alt="Screenshot 2023-11-01 at 12 18 37" src="https://github.com/wso2/product-is/assets/39120228/a99031f3-b8a3-473d-bc47-64cc7f41ae59">

<img width="1483" alt="Screenshot 2023-11-01 at 12 17 37" src="https://github.com/wso2/product-is/assets/39120228/e9d674c6-efe4-40c2-84c5-8acb5837955f">

<img width="1483" alt="Screenshot 2023-11-01 at 12 17 37" src="https://github.com/wso2/product-is/assets/39120228/6939739e-53fe-4f02-ab07-36fd02f23c16">

**Comment by dasuni-30** [comment]
The `required` prop is not passed to the text field of `FinalFormField`. Hence the required fields are not displayed as required even if we make them required. This PR fixes the issue. https://github.com/wso2/identity-apps/pull/4614

The required (*) is not displayed in red color in the text field. Hence this needs to be fixed from the `oxygen-ui`.
<img width="951" alt="Screenshot 2023-11-15 at 14 44 48" src="https://github.com/wso2/product-is/assets/27746285/25283af2-3c8e-4459-8655-aa477a9b7e85">

**Comment by brionmario** [comment]
Making the asterisks red will be covered in https://github.com/wso2/product-is/issues/18642
