### ISSUE TITLE
[Doc] Provide more information on 'Additional Query Parameters' used when configuring Google as IDP

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1749]
When configuring Google as an IDP, there's a field to configure 'Additional Query Parameters'. The doc [1] defined some parameters but doesn't say what each parameter do. So it's better to include that as well. 

[1] https://docs.wso2.com/display/IS540/Configuring+Google

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
