### ISSUE TITLE
Should not allow Updating Invited Users from Parent Organization to Child Organization via Child Organization

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17492]
**Describe the issue:**
 In `Invite Parent Organization Users to a Child Organization for B2B Application Functionalities` feature it supports updating the user profile of a invited user.

https://github.com/wso2/product-is/assets/41188245/7b56cd20-7a75-477a-b08b-780ddb3e415a

**How to reproduce:**

1. Create a sub org
2. switched to the created sub org 
3. Invite a user from the parent org
4. Accept the user invitation
5. From the sub org Users , Navigate to the invited User profile
6. Try to Update the invited user

**Expected behavior:**
Should not support invited user update.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sadilchamishka** [comment]
What is the issue of letting update the user profile here given that user is listed as a user here.
