### ISSUE TITLE
Users from all userstores are not getting displayed when navigating to the Users tab

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#17500]
**Describe the issue:**
Navigating to `Users` tab from any other tab displays only the users from the PRIMARY userstore.

**Reason**
The SCIM API call made to retrieve users is being sent to specific userstores. (In this scenario, DEFAULT and PRIMARY). The request should be sent without the `domain` query parameter.

**How to reproduce:**
1. Create users in 2 different user stores. (PRIMARY and a secondary one.)
2. Navigate to Users tab from any other tab.
3. It only displays users from PRIMARY userstore.

**Expected behavior:**
Users page should display all the users if `All user stores` option is chosen in the dropdown.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-7.0.0-alpha2

**Screenshots**
<img width="1512" alt="Screenshot 2023-11-01 at 14 46 37" src="https://github.com/wso2/product-is/assets/50801227/4e496ad4-67b6-4aa9-8a65-85ae67c32c20">
<img width="1512" alt="Screenshot 2023-11-01 at 14 46 46" src="https://github.com/wso2/product-is/assets/50801227/9a84d209-ac0a-4dc4-bce9-ea464d5db44e">

**Comment by madurangasiriwardena** [comment]
We are planning to remove the support for `All user stores` and with that you have to specify the exact user store.

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/17761
