### ISSUE TITLE
SDK Overview documentation page refers to archived repositories

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#17505]
The WSO2 Identity Server v6.1.0 documentation contains references to archived Github repositories for some sample SDKs in [1]. These need to be replaced with up-to-date references.

[1] - https://is.docs.wso2.com/en/latest/sdks/sdk-overview/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
