### ISSUE TITLE
No input validations for Governance Connector forms

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#17503]
**Describe the issue:**
There are no validation controls for inputs in forms related to Governance connectors causing users to enter and submit invalid values.

<img width="500" alt="Screenshot 2023-11-01 at 16 11 47" src="https://github.com/wso2/product-is/assets/67315176/c4577688-45d3-4184-97ff-aae0466b07fd">

<img width="500" alt="Screenshot 2023-11-01 at 16 11 33" src="https://github.com/wso2/product-is/assets/67315176/406c9bd1-f6ae-4861-894f-a9f6b1e2b8e4">

**How to reproduce:**
- Go to the Console > Login and Registration.
- Configure any governance connector (User validation, password policies etc.)
- Input any invalid value and submit.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
