### ISSUE TITLE
Remove redundant submit buttons in the Governance connector forms

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#17504]
**Describe the issue:**

Certain forms do not require submit buttons as they only have the enable/disable option.

Example
<img width="516" alt="Screenshot 2023-11-01 at 16 29 59" src="https://github.com/wso2/product-is/assets/67315176/aa6154f7-ef3f-4e8a-8407-3c2a5fcf5e42">

Enable/disabled switched which do not depend on any user additional information can also be placed on the listing card itself.

<img width="653" alt="Screenshot 2023-11-01 at 16 32 46" src="https://github.com/wso2/product-is/assets/67315176/54a5c4ca-bcca-4bdd-b8c8-4e94936e75a2">

**How to reproduce:**
- Console > Login & Registration 
- Check out the connector forms

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest pack, hence closing.

<img width="1506" alt="Screenshot 2023-12-02 at 00 21 21" src="https://github.com/wso2/product-is/assets/41533942/52f55801-a109-4d4c-822f-d773a2da70ee">
