### ISSUE TITLE
Same style used for both editable and non-editable fields in invite multiple users view

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#17509]
<img width="404" alt="Screen Shot 2023-11-02 at 10 25 05 AM" src="https://github.com/wso2/product-is/assets/24982871/13aedab2-4ef8-4668-b004-b6c899fe4197">

Also `Select user store` should be reworded as `User store`

**Comment by shanggeeth** [comment]
PR:
- https://github.com/wso2/identity-apps/pull/4532
