### ISSUE TITLE
Some `User Onboarding` sections are missing for the tenant admin

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17502]
**Describe the issue:**
Following user onboarding sections are missing for a tenant admin, however is available for the super tenant admin.
- Organization Self Service
- Self Registration

Also the `Ask Password` section doesn't include all the configs for the tenant admin. It only have a limited set of configs.

![Screenshot from 2023-11-01 16-08-35](https://github.com/wso2/product-is/assets/35653110/a3a15df1-cbfc-4d6b-9e98-4ff5ff00a555)

**How to reproduce:**
1. Create a tenant and login to console with the tenant admin
2. Go to `Login and Registration -> User Onboarding`

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sadilchamishka** [comment]
@ThaminduDilshan Please can you check with a latest pack whether the issue still persists. Didn't noticed with latest product

**Comment by sadilchamishka** [comment]
The issue was not reproduced. Hence closing the issue.

https://github.com/wso2/product-is/assets/35717390/0cb59519-f2ca-487e-81c6-cf3ef6bc1dad
