### ISSUE TITLE
Getting redirected to the login page when trying to sign in  to an application with Microsoft Connection

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17517]
**Describe the issue:**

Getting redirected to the login page when trying to sign in  to an application with Microsoft Connection

<img width="1497" alt="Screenshot 2023-11-02 at 12 03 53" src="https://github.com/wso2/product-is/assets/40081059/e34f883a-2071-46f2-8617-289a3e73d4cc">

https://github.com/wso2/product-is/assets/40081059/6fde83a0-4c5e-4a53-80f2-ea39feeb680e

**How to reproduce:**

1.Login to the console
2.Create an application
3.Create Microsoft connection
4.Assign it a  sign in method to the application
5.Try to login into the sample application

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dhaura** [comment]
### Analysis
- When configuring Microsoft Live app in IS Console, `Secret Value` should be copied as the client secret. (**Not** the `Secret ID`)
<img width="942" alt="Screenshot 2023-11-06 at 16 09 33" src="https://github.com/wso2/product-is/assets/57411348/73cdba1e-99aa-4ef9-8841-5913d3ccb6db">

- Therefore, when the Microsoft connection is configured properly as mentioned above, the user can log into the app successfully as follows.

https://github.com/wso2/product-is/assets/57411348/616ae918-b8e1-42aa-9839-8bd23af73de6
