### ISSUE TITLE
Remove additional sections in M2M application template

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17515]
**Describe the issue:**

The following sections need to be removed from the Protocol tab of an M2M template.
- Pushed Authorization Requests
- Request Object
- ID token response signing algorithm
- Warning symbol next to the client credentials grant

**How to reproduce:**
1. Create an M2M application.
2. Navigate to the Protocol tab.
3. Find the above mentioned sections in the UI.

**Comment by janakamarasena** [comment]
This has happened due to additions to the standard template. This needs to be fixed in a manner that additions to the standard template don't automatically come to the m2m template

**Comment by madurangasiriwardena** [comment]
`Warning symbol next to the client credentials grant` is not removed yet.

**Comment by brionmario** [comment]
@amanda-ariyaratne Can you please share the status of this issue?

**Comment by brionmario** [comment]
> `Warning symbol next to the client credentials grant` is not removed yet.

<img width="791" alt="Screenshot 2023-11-30 at 15 14 07" src="https://github.com/wso2/product-is/assets/25959096/fe2bd949-e2d1-4bcc-905d-e8715b8d7fd4">

It currently shows the above warning. That shouldn't be a problem right?
