### ISSUE TITLE
[User Info Endpoint] User clams not filtered based on consent for implicit grant tokens

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-is#17521]
**Describe the issue:**

After generating a token from implicit grant with following default config in identity.xml, if the token is provided for the UserInfo endpoint, the claims are not getting filtered by consent as expected.

```
        <UserConsentEnabledGrantTypes>
            <UserConsentEnabledGrantType>
                <GrantTypeName>authorization_code</GrantTypeName>
            </UserConsentEnabledGrantType>
            <UserConsentEnabledGrantType>
                <GrantTypeName>implicit</GrantTypeName>
            </UserConsentEnabledGrantType>
        </UserConsentEnabledGrantTypes>
```

**How to reproduce:**
1. Generate a token via implicit grant. IS_CONSENTED column value in access_token table is set to false.
2. Provide token to `https://localhost:9443/oauth2/userinfo` endpoint.
3. All the claims regardless of the userconsent are returned back.

**Expected behavior:**
Claim filtering should happen similar to authorization_code grant and based on the correct value of access_token table. Hence when persisting token during implicit grant, need to check the above config and set is_consented value in the table.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
