### ISSUE TITLE
Add vender specific logos in the SMS Provider (Notification channels) page

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#17528]
**Is your suggestion related to an experience ? Please describe.**

- [ ] Add vender logos for Twilio and Vonage
- [ ] Add the gear icon for the custom option

<img width="993" alt="Screenshot 2023-11-02 at 18 21 34" src="https://github.com/wso2/product-is/assets/67315176/67ee12f5-94fb-445e-8681-5d95f9c17ba1">

**Describe the improvement**

**Additional context**

**Comment by brionmario** [comment]
@bhagyasakalanka Any update on this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
