### ISSUE TITLE
Unable to Update "SMS Provider" Configurations - Receiving an Error Message

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17524]
**Describe the issue:**
when attempting to update the "SMS Provider" configurations (Branding > Notification Channels). Whenever I make changes and try to save them, I receive an error message that prevents the update from being applied.

[recording(11).webm](https://github.com/wso2/product-is/assets/39120228/d47b31c6-48e0-483e-aa82-422e7fad0bad)

**How to reproduce:**
Log in to the application.
Navigate to the "SMS Provider" configuration page.
Make changes to the configurations

**Expected behavior:**
The changes should be saved successfully, and the "SMS Provider" configurations should be updated without any issues.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Alpha 7.0
 - OS: Mac
 - Database:MySQL, H2
 - Userstore: JDBC

---

**Comment by bhagyasakalanka** [comment]
This is a backend limitation we have. Currently, if the SMS provider is configured in any of the applications, we cannot delete the sms provider configurations. 

Our current FE implementation is, when we update the configurations, 
1. Delete existing configurations
2.  Create new configurations

But since we have already configure SMS OTP in an application, the delete step is failing.

**Comment by madurangasiriwardena** [comment]
@bhagyasakalanka I don't think we can say this is a limitation. It is intensional that the SMS provider cannot be deleted when an application is configured with SMS otp.

So from the UI we have to handle the error message sent in backend and show the proper error message.

**Comment by JKAUSHALYA** [comment]
@madurangasiriwardena actually we are getting the proper error message as well in the network payload. What we have to do is show it in proper manner.

**Comment by pavinduLakshan** [comment]
> This is a backend limitation we have. Currently, if the SMS provider is configured in any of the applications, we cannot delete the sms provider configurations.
> 
> Our current FE implementation is, when we update the configurations,
> 
> 1. Delete existing configurations
> 2. Create new configurations
> 
> But since we have already configure SMS OTP in an application, the delete step is failing.

This issue had occurred because instead of using PUT request for updating SMS provider details, we are recreating an SMS provider by deleting the existing configs. Using the PUT /notification-senders/sms/SMSPublisher for updating the SMS provider details fixes this issue.

**Comment by pavinduLakshan** [comment]
This issue has again been introduced. Will update the comment with the RC

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

https://github.com/wso2/product-is/assets/41533942/f84d3b87-2731-4e57-9982-140f303aff7d
