### ISSUE TITLE
Use one pattern out of permissions(scopes) or scopes(permissions) 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17535]
**Describe the issue:**
Use one pattern out of permissions(scopes) or scopes(permissions)  to keep consistency.

<img width="934" alt="Screenshot 2023-11-03 at 08 37 11" src="https://github.com/wso2/product-is/assets/25483865/19c31250-ac70-45b4-adaf-5ec826035940">
<img width="906" alt="Screenshot 2023-11-03 at 08 37 49" src="https://github.com/wso2/product-is/assets/25483865/d3ff2f2f-92b1-4afd-90c5-33a03431a354">

Check role's permission assignment and API resource creations/edits

**Comment by JayaShakthi97** [comment]
Improvement;
1. Current representation is invalid (Need to be swapped).
2. Using one pattern won't work as the Role and API resource are two concepts.
3. For an API resource --> Scope need to be assigned not Permission. Therefore all the wordings referred to as Permission should be updated to Scope in API resource related interfaces.
4. For a Role --> Permission need to be assigned not Scope (Even though we use scopes under the hood).
