### ISSUE TITLE
Self signup url on the login page is invalid

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17534]
**Describe the issue:**
An invalid link for self signup url is shown on the login page when **self signup is not enabled**. It has org name as null and signup page loads without any styles due to this.

```
https://localhost:9443/authenticationendpoint/null/register.do?...
```

**How to reproduce:**

- Start server
- Make sure self signup is **not** enabled
- Open myaccount url
- Click `Register` link in the bottom of login page

**Environment information** 
Product Version: IS 7.0.0-alpha

**Comment by Achintha444** [comment]
This is fixed in the latest console version
<img width="1800" alt="Screenshot 2023-11-14 at 15 39 20" src="https://github.com/wso2/product-is/assets/46097917/9cea47be-1948-4b15-9f72-2e9c50443b4d">

Hence closing the issue. If the problems persists, please feel free to open this issue again.
