### ISSUE TITLE
 Add a caching layer for role management

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17538]
**Describe the Improvement:**

- A new service has been introduced for role management as RoleManagerV2
- To improve the performance of the service, a caching layer is required.

**Comment by dewniMW** [comment]
Adding a caching layer needs to be done in a careful manner as the role has dependencies with other components such as groups, users, IdPs, applications, API resources, scope and permission. Handling the cache invalidation needs to be done based on any modifications for these components.
Therefore we initially decided to analyze the possibility to cache permissions against a role. Upon further analysis there is an issue with invalidating cache when an API resource gets deleted as this has been handled as a cascade delete at db level. Hence there are complexities with invalidating the cache.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
