### ISSUE TITLE
Add audit logs for role management v2 serivce

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17539]
**Describe the issue:**

- Audit logs are crucial for the role management service operations.
- There is an ongoing effort to improve audit logs and add the audit logs in more consistent manner.
- Following the same pattern, we need to add audit logs to role management operations

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
