### ISSUE TITLE
Old products listed in About Page of Identity Server 5.4.0

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1754]
About page listed Old products such as 'WSO2 Business Process Server',  'WSO2 Business Activity Monitor', 'WSO2 Gadget Server', 'WSO2 Mashup Server' and 'WSO2 Business Rules Server' and new products need to be included as well.

![old products](https://user-images.githubusercontent.com/8849472/34152222-d923ef44-e4d3-11e7-9e8f-553f77a7c126.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
