### ISSUE TITLE
Analytics menu does not work on Console

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17545]
**Describe the issue:**
When Analytics menu is clicked on Console, it shows `Something went wrong` error message while the API call returns following.

`GET /t/carbon.super/api/server/v1/identity-governance/T3RoZXIgU2V0dGluZ3M/connectors/ZWxhc3RpYy1hbmFseXRpY3MtZW5naW5l`
```
{
    "code": "IDG-50009",
    "message": "Resource not found.",
    "description": "Unable to find any connector with the provided identifier ZWxhc3RpYy1hbmFseXRpY3MtZW5naW5l.",
    "traceId": "xxx"
}
```

**How to reproduce:**
- Login to Console
- Click on Analytics menu

**Environment information** 
 - Product Version: Product Version: IS 7.0.0-alpha

**Comment by Achintha444** [comment]
Currently this is working on the latest console version

https://github.com/wso2/product-is/assets/46097917/418597f8-8d5e-4a1b-962c-8d59046f5d2e

Hence closing the issue. but if this problems persists, please feel free to open this issue again.
