### ISSUE TITLE
UX issues in Passkey based login

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17544]
**Describe the issue:**

1.  The "On-the-fly passkey enrollment" script is only available when a user start with the Passkey template.
2.  Having an adaptive script for the on the fly enrollment makes it harder to understand and error prone to developers. At least there should be a mechanism to educate the user on the requirement for the adaptive script and a clear information on what happens there. 
3.  For someone who starts with default or other templates, script is not available.
4. It makes it harder to write event simple conditional authentication flows such as only to execute MFA for nonPasskey flow when 1st step has multiple options.

**Comment by madurangasiriwardena** [comment]
As a quick solution, we can add the relevant scripts to the docs until the issue is properly fixed.
