### ISSUE TITLE
Configuration Issue with HYPR Authenticator in Console

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17546]
**Describe the issue:**
After following the doc and configuring HYPR the connection template is not visible in the connections UI.
<img width="1495" alt="Screenshot 2023-11-03 at 11 31 07" src="https://github.com/wso2/product-is/assets/41188245/6f6bdd6f-44d3-4d28-90d2-8da91d52e840">

**How to reproduce:**

1. Configure HYPR [Add HYPR login](https://is.docs.wso2.com/en/next/guides/authentication/passwordless-login/add-passwordless-login-with-hypr/)
2. Add the below configurations to the deployment toml.
```
[[resource.access_control]]
context = "(.*)/api/hypr/v1/authentication/status/(.*)"
secure = "false"
http_method = "GET"

[tenant_context]
enable_tenant_qualified_urls = "true"
enable_tenanted_sessions = "true"
rewrite.custom_webapps=["/api/hypr/"]

[console.ui.idp_templates.hypr]
enabled = true
```
4. Download [HYPR connector](https://store.wso2.com/store/assets/isconnector/details/9fae98d3-26a6-4b1f-a356-f58b08d060ed)
5. Added `org.wso2.carbon.identity.application.authenticator.hypr-1.0.*-SNAPSHOT.jar` to `<IS_HOME>/repository/components/dropins`
6. Copy `org.wso2.carbon.identity.application.authenticator.hypr.common-1.0.*-SNAPSHOT.jar` to `<IS_HOME>/repository/components/lib`
7. Copy `api#hypr.war ` file to `<IS_HOME>/repository/deployment/server/webapps`
8. Added `hyprlogin.jsp` to `<IS_HOME>/repository/deployment/server/webapps → authenticationendpoint`
9. Try to create a new HYPR connection through Add Connections.

**Expected behavior:**
The HYPR connector should be visible in Add connections UI.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Hi @melanisilva can you please refer to this issue [1]. If has the required configuration to display the HYPR template in the Console. 

[1] - https://github.com/wso2/product-is/issues/17239

**Comment by melanisilva** [comment]
@divyaamunugama FYI 

The correct config would be : 
```
[[resource.access_control]]
context = "(.*)/api/hypr/v1/authentication/status/(.*)"
secure = "false"
http_method = "GET"

[tenant_context]
enable_tenant_qualified_urls = "true"
enable_tenanted_sessions = "true"
rewrite.custom_webapps=["/api/hypr/"]

[console.ui]
hiddenConnectionTemplates = []

```

**Comment by nipunsampath** [comment]
@melanisilva is the issue not reproducible after using this config?

> @divyaamunugama FYI
> 
> The correct config would be :
> 
> ```
> [[resource.access_control]]
> context = "(.*)/api/hypr/v1/authentication/status/(.*)"
> secure = "false"
> http_method = "GET"
> 
> [tenant_context]
> enable_tenant_qualified_urls = "true"
> enable_tenanted_sessions = "true"
> rewrite.custom_webapps=["/api/hypr/"]
> 
> [console.ui]
> hiddenConnectionTemplates = []
> ```

**Comment by melanisilva** [comment]
Yes @nipunsampath , With these Configs the issue was solved.
 

> @melanisilva is the issue not reproducible after using this config?
> 
> > @divyaamunugama FYI
> > The correct config would be :
> > ```
> > [[resource.access_control]]
> > context = "(.*)/api/hypr/v1/authentication/status/(.*)"
> > secure = "false"
> > http_method = "GET"
> > 
> > [tenant_context]
> > enable_tenant_qualified_urls = "true"
> > enable_tenanted_sessions = "true"
> > rewrite.custom_webapps=["/api/hypr/"]
> > 
> > [console.ui]
> > hiddenConnectionTemplates = []
> > ```
