### ISSUE TITLE
Broken/Incorrect links pointed in About Page of Identity Server 5.4.0 under 'Need more help?'

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1755]
There're several links pointed under 'Need more help?' section in 'ABOUT' page of Identity Server 5.4.0 which needs to be corrected.

* Online Documentation - Pointing to an old doc repo
* Read articles - Pointing to IAM product downloading page
* Post to the forum - Broken link
* Report an Issue - Point only to jira. Need to point to GIT as well.

![need more help](https://user-images.githubusercontent.com/8849472/34152689-753302ca-e4d5-11e7-93fc-fd5d907b5097.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
