### ISSUE TITLE
Unnecessary screen when backup codes are enabled with Email OTP

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#17557]
**Describe the issue:**
When backup codes are enabled for the Email OTP, user has to go through below page, which does not server any purpose
![image](https://github.com/wso2/product-is/assets/1332991/b448f6ec-a736-4baa-b26b-982ec4cdb517)

**How to reproduce:**
Add basic authentication as 1st step and Email OTP as the 2nd step. Enable "Enable backup codes" option.
![image](https://github.com/wso2/product-is/assets/1332991/701b3b40-12d3-4614-8be0-1d11afa04e2b)

Before going to the Email OTP page, user lands in the above mentioned page, which does not serve any purpose.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Verified in the latest beta snapshot Jenkins build.

https://github.com/wso2/product-is/assets/41533942/fdd88f19-4ae3-42ff-8e74-f422f87582e0
