### ISSUE TITLE
No indication about why the role name is incorrect and how to fix it

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17553]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/44be0b6d-5364-4eb3-8120-aed2525972c2)

**How to reproduce:**
1 - try adding a new application role with a name like "Pet Store Admin"

**Comment by ChanikaRuchini** [comment]
Tested with wso2is-7.0.0-beta-SNAPSHOT. flow works as expected.

[Untitled_ Nov 10,2023 4_07 PM.webm](https://github.com/wso2/product-is/assets/36252774/599cf3b2-8d33-4ea0-b54b-39dda1d64ec7)
