### ISSUE TITLE
Text content explanations are not intutive in application resources

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17556]
**Describe the issue:**
Configuration options are not clear/intuitive to the users in the application resources flow.

Examples: 

![image](https://github.com/wso2/product-is/assets/5061791/8a4625bc-5b2e-4a04-bcd5-594eec845c77)

![image](https://github.com/wso2/product-is/assets/5061791/ac8f5285-b2c0-4aa5-bac9-73559fbbbbd6)

**How to reproduce:**
Try the application resources feature from external users PoV.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
