### ISSUE TITLE
TOTP authenticator keeps prompting when Google is set as the first factor.

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#17558]
**Describe the issue:**
When Google is set as the first factor and TOTP is set as the second factor, the TOTP authenticator repeatedly prompts for input after sending the correct token during API authentication.

**How to reproduce:**
1. Set google as the first factor and totp as the second factor.
2. Logged in using google using API authentication.
3. TOTP authenticator will be prompted, then send the correct totp code as the token.

**Expected behavior:**
Ideally error message should return, before prompting the TOTP authenticator, as we cannot use TOTP authenticator for federated users.

**Comment by DMHP** [comment]
Adding TOTP as the second factor with federated IDPs is already restricted from the UI.
![Uploading image.png…]()

**Comment by Achintha444** [comment]
> Adding TOTP as the second factor with federated IDPs is already restricted from the UI. <img alt="image" width="1719" src="https://user-images.githubusercontent.com/12690906/281671653-6b630cdc-23c0-457c-a495-95c92a13e5cb.png">

This was not done using UI, it was added using the API.

**Comment by janakamarasena** [comment]
Tested and the flow is working now. Closing as it cannot be reproduced.
