### ISSUE TITLE
Filed lable under branding looks like it is not properly rendered

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17562]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/805269b2-2723-445c-b714-6fa928cc4e1e)

**How to reproduce:**
1- check branding configurations for `site title`

**Expected behavior:**
Human readable label should be there

**Comment by brionmario** [comment]
The actual intention was to show the `object` key as the label.
Seems like it's not intuitive.

Need to fix.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
