### ISSUE TITLE
In TOTP email templete must updated 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1756]
TOTP email template must update user variable from **{username}, to {{ user.claim.givenname}}**
Otherwise, the username is not updated in the email body as in the image.

![totpemail](https://user-images.githubusercontent.com/13656890/34152762-b240df70-e4d5-11e7-87c2-ccdf69071a85.png)
```<configuration type="totp">
    <targetEpr></targetEpr>
    <subject>WSO2 Carbon - Time-Based One Time Password</subject>
    <body>
**Hi {{user.claim.givenname}},**
Please use the token {totp-token} as the password for your login.
    </body>
    <footer>
Best Regards,
WSO2 Identity Server Team
http://www.wso2.com
    </footer>
    <redirectPath></redirectPath>
</configuration>```
``
[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator

**Comment by sherenewso2** [comment]
Fixed in [1] 

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator
