### ISSUE TITLE
Unable to Access Console/My Account After Changing Hostname with MySQL as Primary DB

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17572]
**Describe the issue:**
After changing the hostname and MySQL set as the primary database, unable to access the console and My Account.
This issue occurs even though the process works as expected with the default pack.

**How to reproduce:**
1. 
Configure the hostname as follows in <IS_HOME>/repository/conf/deployment.toml.

``` [server]
hostname = "wso2.com" 
```

2. Change keystore necessary commands
3. go to repository/resources/security
```
mv wso2carbon.jks /home/ubuntu/m7/test
keytool -genkey -alias wso2carbon -keyalg RSA -keysize 2048 -keystore wso2carbon.jks -dname "CN=wso2.com, OU=Home,O=Home,L=SL,S=WS,C=LK" -storepass wso2carbon -keypass wso2carbon
keytool -export -alias wso2carbon -keystore wso2carbon.jks -file test.pem
keytool -import -alias carbon1 -file test.pem -keystore client-truststore.jks -storepass wso2carbon
```
Change Default DB as MYSQL - toml 
```
[user_store]
type = "database_unique_id"

[database.identity_db]
#type = "mysql 5 7"         # Infers the local H2 DB connection details for 'DEV' pattern. SHOULD BE CHANGED TO PRODUCTION READY DB FOR PRODUCTION
url = "jdbc:mysql://localhost:3306/alphamysql?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
#type = "mysql 5.7"         # Infers the local DB connection details. SHOULD BE CHANGED TO PRODUCTION READY DB FOR PRODUCTION
url = "jdbc:mysql://localhost:3306/alphamysql?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false
```
add relevant mysql jdbc jar to (/repository/components/lib)

Error 
```
 [d984d726-2af8-48a3-a52d-93cabd3f8f34]  WARN {org.wso2.carbon.identity.oauth2.authz.validators.AbstractResponseTypeRequestValidator} - Provided Callback URL does not match with the registered one.
```
<img width="1666" alt="Screenshot 2023-11-03 at 13 36 44" src="https://github.com/wso2/product-is/assets/39120228/dcddfb40-0342-4acf-8c00-a8eb078944fe">

References : https://is.docs.wso2.com/en/latest/deploy/change-the-hostname/

**Comment by Thisara-Welmilla** [comment]
Similar to https://github.com/wso2/product-is/issues/10514

**Comment by NilukaSripalim** [comment]
> Similar to #10514

This is not related to offset changes, this is based on changing hostname

**Comment by NilukaSripalim** [comment]
Tried with postgress, this is not working as expected ( latest jenkin build) [#4938](https://wso2.org/jenkins/job/products/job/product-is/4938/)


<img width="1365" alt="Screenshot 2023-11-21 at 12 20 13" src="https://github.com/wso2/product-is/assets/39120228/f1406936-3686-4b5e-bea0-a335ea6f3a39">
