### ISSUE TITLE
UI is not loading when we enable email OTP federated authenticator

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17579]
**Describe the issue:**

UI is not loading when we enable email OTP as a federated authenticator

https://github.com/wso2/product-is/assets/40081059/aef744b8-c3aa-4e82-9277-6105044a62c7

**How to reproduce:**

1.Login to the management console
2.Enable emailOTP as a federated authenticator
https://is.docs.wso2.com/en/5.9.0/learn/configuring-email-otp/
3Login to the console
4.Go to connections

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
This is a scenario where the IDP is created from the management console and therefore will not have the template details. We need to improve the edit section of IDPs to handle the IDPs created without a template.

Possible Solutions:

1. If the templateId is missing in the IDP object we can treat them as an expert-mode-idp.
2. We can append the templateId by looking at the default authenticator.
