### ISSUE TITLE
Clarification Required: Duplicate Passkey Configurations in "Connection" and "Multi Factor Authenticators" Sections

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17588]
**Describe the issue:**
Observed that Passkey configurations are duplicated in two distinct sections: the "Connection" section and the "Multi Factor Authenticators" section. Both sections contain the same configuration options

This raises several questions and concerns:

    **Why do we have duplicate Passkey configurations in both the "Connection" and "Multi Factor Authenticators" sections? Is this intentional, or does it stem from historical reasons?

    **What are the specific use cases or scenarios for these dual configurations? Are they meant to serve different purposes, or is there overlap in their functionality?

    **Does having duplicate configurations affect the consistency, maintainability, or security of the project? Are there any potential issues that we should be aware of?

    **Is there any documentation or guidance available to help us understand the rationale behind this configuration design?

### Under Connection Section 
<img width="593" alt="Screenshot 2023-11-06 at 13 58 03" src="https://github.com/wso2/product-is/assets/39120228/0686efdc-a406-46a7-9853-69fba81fee79">

<img width="701" alt="Screenshot 2023-11-06 at 13 58 09" src="https://github.com/wso2/product-is/assets/39120228/f11318dc-e58e-4241-aa2c-4cec75da0761">

### Login & Registration 

<img width="1041" alt="Screenshot 2023-11-06 at 14 03 42" src="https://github.com/wso2/product-is/assets/39120228/d53f3b31-9384-4ec4-9141-11c135399e7f">

**Comment by nipunsampath** [comment]
**Multi factor authentication** section was removed from the **Login & Registration** section with the https://github.com/wso2/identity-apps/pull/4702. This issue is not reproducible now.
