### ISSUE TITLE
There are two logo urls for an applicaion- update the descriptions according to the proper usage

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17582]
**Describe the issue:**

![image](https://github.com/wso2/product-is/assets/5061791/b97c8e4c-6b4b-48e6-a6f3-b0ac609b1491)

![image](https://github.com/wso2/product-is/assets/5061791/004e1230-7ed9-45a7-96c5-0972df2230a9)

**How to reproduce:**
One under application general settings, and one under branding.

**Expected behavior:**
Remove if there are redundant configs
update the descriptions properly

How will this fit when application-level branding comes into the picture?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
