### ISSUE TITLE
Self signup: Try out self sign up section indicates user needed to be created before self registering

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1758]
In [1] under Try out self sign up it states that the user should be created via the management console with login permissions. Is there any reason why that is needed? Ideally self registering should create a user with login permission.

[1] https://docs.wso2.com/display/IS540/Self+Sign+Up+and+Account+Confirmation

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
