### ISSUE TITLE
Revise the classic features in the console and hide them in the new mode with option to enable in classic mode

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17584]
**Describe the issue:**

There are some UI components that are not required for the latest IAM features but are required for users who upgrade from older versions and still need to use classic features over new features.

- [x] request path authentication
![image](https://github.com/wso2/product-is/assets/5061791/1b4d576a-eb36-452c-b7f6-8c347edc30ef)

- [x] Role mapping at the application level
![image](https://github.com/wso2/product-is/assets/5061791/8da1db68-259e-4cd4-b7d8-05aa475a1428)

- [x] Engaging authorization policies with XACML
![image](https://github.com/wso2/product-is/assets/5061791/413b8bce-89c8-4118-bb3b-553fa98adb0a)

- [x] Application settings

![image](https://github.com/wso2/product-is/assets/5061791/1e51bc56-0c28-472c-a12f-c9b0c07507ad)
 

Review other features as well.

**Comment by ayshsandu** [comment]
This should be addressed over the unification efforts.

**Comment by pavinduLakshan** [comment]
Default subject attribute cannot be changed to user ID in OIDC apps because we don't have the userid claim in OIDC dialect. If we need to make user ID the default subject identifier, we may need to add it to the OIDC claim dialect.

**Comment by pavinduLakshan** [comment]
Since userid is the default subject identifier for oidc apps in both onprem and cloud, it was decided to place the default subject identifier behind a deployment config.

**Comment by pavinduLakshan** [comment]
Verified in the latest build.

<img width="1503" alt="Screenshot 2023-11-21 at 09 58 08" src="https://github.com/wso2/product-is/assets/41533942/fd43599b-a98f-4e40-98dc-aa48f2b25c66">

<img width="1503" alt="Screenshot 2023-11-21 at 09 58 28" src="https://github.com/wso2/product-is/assets/41533942/b5406849-9e73-499d-b045-12bc44c3a2e0">

<img width="1503" alt="Screenshot 2023-11-21 at 09 57 38" src="https://github.com/wso2/product-is/assets/41533942/48bfcd5c-75f1-4723-9820-5ccb3abf5f7b">
