### ISSUE TITLE
Reevaluate Governance Connectors Content for Clarity and Updated Descriptions

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17592]
**Describe the issue:**
The current content related to Governance Connectors requires revisiting. Some configurations lack clear explanations of their functionality, and the descriptions provided are not as clear as needed. To improve user understanding and usability, a thorough review and clarification of the Governance Connectors documentation is necessary.

Example:  In `Other Settings ` 

1. Better to have a little more descriptive description of the connector usage.
2. The OTP related config is a bit unclear and feels like a bug since the same config is related in `User Onboarding` -> `Ask Password`

<img width="958" alt="Screenshot 2023-11-06 at 15 19 50" src="https://github.com/wso2/product-is/assets/41188245/5e8ac7ac-c964-481b-8ced-4f8411129633">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ayshsandu** [comment]
This should be fixed with the restructuring effort in the UI related to these connectors. @NipuniBhagya is working on https://github.com/wso2/product-is/issues/17590
