### ISSUE TITLE
Unable to set callback url in connections from the console app

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#17595]
**Describe the issue:**
In the Carbon based management console for Identity Providers it is possible to set the callback url to any url. 
<img width="895" alt="Screenshot 2023-11-06 at 15 47 43" src="https://github.com/wso2/product-is/assets/11583571/0c56a47d-f624-41db-a446-02d728c813b0">

But in the new Console app it is not possible to set the callback url in a connection.
<img width="1154" alt="Screenshot 2023-11-06 at 15 47 23" src="https://github.com/wso2/product-is/assets/11583571/7b3e16f6-84f4-45bb-9959-40d8cf846b29">

This is a breaking change when switching to the new console from the old carbon management console. 
This especially becomes a blocker for api based authentication as it is expected to set the apps redirect url as the callback

**How to reproduce:**
Try creating a connection from the console app and setting a callback url.

**Expected behavior:**
Should be able to set a prefered callback url.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
The redirect URI can't be edited in the previous IS versions as well. The following screenshot is from IS 6.1.

<img width="1503" alt="Screenshot 2023-11-15 at 00 49 18" src="https://github.com/wso2/product-is/assets/41533942/cfe83fb2-2966-4ce3-ae74-272bb0fb269a">

Do we still require allowing any URL to be set as the authorized redirect URI for the connections?

> This especially becomes a blocker for api based authentication as it is expected to set the apps redirect url as the callback

AFAIU, each app's redirect URI should be set in application > protocol section, not in the connection's settings, shouldn't it? 

Please correct me If I'm wrong and apologies if I'm missing something obvious here :)

**Comment by janakamarasena** [comment]
In the previous IS versions the console app was in beta and the main management app was the carbon management console. In the carbon management console, this url is editable. And since the carbon management console will be deprecated and the new react based portal is the one that will be used, for this particular it is a blocker IMO

**Comment by pavinduLakshan** [comment]
Removing the blocker status as per the offline conversation with @janakamarasena

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
