### ISSUE TITLE
Improve and unify `Login & Registration` section with Asgardeo

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#17590]
**Is your suggestion related to an experience ? Please describe.**
Currently `Login & Registration` page is loaded with new feature and configurations from old mgt console. Page seems to be cluttered and experience is inconsistent with Asgardeo.

**Describe the improvement**
Go through each sub section and cross check the configs and unify those with Asgardeo console and improve the UX to available feature on both Asgardeo and Identity Server v7.0 new console.

**Additional context**
Affected version v7.0 Alpha

**Comment by shanggeeth** [comment]
The UI configs related to `Organization Self Service` needs to be removed
- Issue - https://github.com/wso2/product-is/issues/17901
- Refer to https://github.com/wso2/product-is/issues/17901#issuecomment-1817427044

**Comment by jeradrutnam** [comment]
This task is done. and PRs are merged.

**Comment by JeethJJ** [comment]
As we made changes to the password expiry connector[1] where we have the functionality in the product available by default, it is not required to show the deprecated connector through the console anymore. 

There needs to be similar decisions taken on which connectors need to be shown through the console and not. 

[1] https://github.com/wso2/product-is/issues/17735
