### ISSUE TITLE
Update the UI text on SMS OTP connections's note box

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/product-is#17596]
**Describe the issue:**
The note box on the SMS OTP connection UI has content related to Asgardeo.

![image](https://github.com/wso2/product-is/assets/84217321/15ec9222-b23e-47c9-b04b-bc7e00d5e1cf)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
