### ISSUE TITLE
[DOC] [Improve] mention the config file location where the config changes required in given doc page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1759]
On the doc page [1] we require to change refresh token validity period whenever needed (see attached), So it is good to mentoin the location where changes should be done.

label - IS-5.4.0

[1] [https://docs.wso2.com/display/IS540/Refresh+Token+Grant]

![tokentime](https://user-images.githubusercontent.com/15671620/34156353-d1c69f62-e4e2-11e7-8300-59e6da9b2386.jpeg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
