### ISSUE TITLE
[Docs] Wreply validation for login and logout flow in passive STS

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#17593]
We have recently introduced a configuration to set the wreply url for validation in the logout flow and this needs to be added to the documentation.
Furthermore, documentation is missing for the existing wreply validation of the login flow. This needs to be added as well.

It is currently not possible to do the update in the docs for the next release, since the pages have not been added to the is docs repo yet. So this will have to be done later once they are added.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
