### ISSUE TITLE
Improving exception handling in the TokenBinder interface

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/product-is#17604]
**Describe the improvement**
Currently the methods in the TokenBinder interface [1] has been implemented in a manner in which exceptions cannot be thrown from them and therefore exception handling needs to be performed where these methods are being referred. But the issue that we come across here due to that implementation is that we are not able to let the end user know about the exact reason causing the issue and we are only able able to give a generalized error. This needs to be improved to provide the ability to throw relevant exceptions in error scenarios that could occur when generating and validating token binding values so that we could let the end user know the exact reason that caused an error to occur. 

After improving the methods in the TokenBinder interface as aforementioned, it is required to perform the relevant exception handling as well accordingly where those methods are being referred.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/TokenBinder.java

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
