### ISSUE TITLE
Invalid response for unsupported authenticators during API based authentication

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#17600]
**Describe the issue:**
I have configured an application with the following login sequence.
<img width="1147" alt="image" src="https://github.com/wso2/product-is/assets/12439288/8cf054ba-623f-48fe-af58-1e85e679f9ae">

When an API-based authentication request is initiated for the given application, the following response is returned.
```
{
    "flowId": "7d622ddb-edbb-41b4-a414-18fe7f56c76c",
    "flowStatus": "INCOMPLETE",
    "flowType": "AUTHENTICATION",
    "nextStep": {
        "stepType": "MULTI_OPTIONS_PROMPT",
        "authenticators": [
            {
                "authenticatorId": "QmFzaWNBdXRoZW50aWNhdG9yOkxPQ0FM",
                "authenticator": "Username & Password",
                "idp": "LOCAL",
                "metadata": {
                    "promptType": "USER_PROMPT",
                    "params": [
                        {
                            "param": "username",
                            "type": "STRING",
                            "order": 0,
                            "i18nKey": "username.param",
                            "confidential": false
                        },
                        {
                            "param": "password",
                            "type": "STRING",
                            "order": 1,
                            "i18nKey": "password.param",
                            "confidential": true
                        }
                    ]
                },
                "requiredParams": [
                    "username",
                    "password"
                ]
            }
        ]
    },
    "links": [
        {
            "name": "authentication",
            "href": "https://localhost:9443/t/carbon.super/oauth2/authn",
            "method": "POST"
        }
    ]
}
```

The response type is `MULTI_OPTIONS_PROMPT` but it only contains details about the basic authenticator. The email OTP federated authenticator details are missed.

**How to reproduce:**
1. Configure an application with the login sequence as above.
2. Initiate a API based authentication
```
curl --location 'https://localhost:9443/oauth2/authorize/' \
--header 'Accept: application/json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-urlencode 'client_id=lEKvp7rORWHDJzeWCV_2qYnd_I4a' \
--data-urlencode 'response_type=code' \
--data-urlencode 'redirect_uri=https://localhost/callback' \
--data-urlencode 'state=logpg' \
--data-urlencode 'scope=openid internal_login' \
--data-urlencode 'response_mode=direct'
```

**Expected behavior:**
If there are authenticators that does not support API based authentication, it should be properly notified.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 Alpha
 - OS: Mac

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by janakamarasena** [comment]
This is fixed with https://github.com/wso2/carbon-identity-framework/pull/5166. If the flow contains an unsupported authenticator it will send a error response during the initial request
