### ISSUE TITLE
Organization SSO authentication option should not be let remove from the console UI when application is shared with at least one organization

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#17609]
**Describe the issue:**

When the application has shared applications, it is better to disable the Organization SSO remove icon from the sign in options.

**Expected behavior:**

When the app is shared with atleast one organization, the UI should not allow removing the organization SSO IDP.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0.0-alpha]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by JayaShakthi97** [comment]
- Improvement: https://github.com/wso2/identity-apps/pull/4879

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-rc1-SNAPSHOT

https://github.com/wso2/product-is/assets/37938529/8b4f8587-40eb-45c1-835c-900dd86540cc
