### ISSUE TITLE
[Bug] verification code is not initially receiving to email when enable TOTP

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1760]
**Environment**
IS 540 

**Steps**
- Configure the IS  to send email and add the email template  which is user receives when generating the token 
- Enable TOTP as a second step in the multi-step authenticator [1] 
- Go to the SP (Travelocity ) in order to the login 
- Enter username and password as the first step in  dashboard
- Redirected to the TOTP authentication page which needs to enter the verification code

**Issue**
Initially, verification code is not received via email. But after clicked the  `Get a Verification Code`  link user will receive the verification code via email. Below info logs also can see in the backend 
```
[2017-12-19 17:34:29,511]  INFO {org.wso2.carbon.identity.mgt.mail.DefaultEmailSendingModule} -  Sending user credentials configuration mail to test1@gmail.com```

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
