### ISSUE TITLE
Protocol tab is loading indefinitely intermittently

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17607]
**Describe the issue:**

$subject

https://github.com/wso2/product-is/assets/41533942/540b947c-37cd-4979-b375-155ee808471a

**How to reproduce:**

1. Sign into console
2. Create a single page application
3. Navigate to protocol section. You will see it is loading indefinitely.
4. Click on another side panel menu item (Eg: Connections) and navigate to its page.
5. Now again click on "Applications" in the side panel and navigate to the protocol section of the created application.
6. Protocol section is rendered as expected.

**Expected behavior:**

Behaviour in step 3 should not occur.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 Alpha 2
 - OS: Mac OS
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
**Verified in the wso2is-7.0.0-beta-SNAPSHOT**

https://github.com/wso2/product-is/assets/27746285/73eee71a-8524-4e90-ae3b-55e1fa7254ac
