### ISSUE TITLE
[Doc - Improvement] Mention about the TOTP verification code validation period

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1761]
No information  about the TOTP verification code validation period in [1]

[1]https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
