### ISSUE TITLE
Not all the email templates available in the product is shown for branding under email templates in the Console

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17618]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/60b5b49d-d41d-4d8c-b86a-2bfc58601f6a)

Example:
 - Verification mail at the email value update in the profile
 
 ![image](https://github.com/wso2/product-is/assets/5061791/d6c1d45e-f40c-4f59-90b6-4f475924059c)

 - Email update notification at the email value update in the profile 
    
  ![image](https://github.com/wso2/product-is/assets/5061791/910de905-20c9-44b3-918b-9fb8587fdac5)

**How to reproduce:**
All the email templates available in the product should come for the customization in the console

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asha15** [comment]
Closing the issue as it's fixed in `IS 7.0.0-alpha2`. 

Related issue: https://github.com/wso2/product-is/issues/17250
Related PRs:
- https://github.com/wso2/carbon-identity-framework/pull/5072
- https://github.com/wso2/identity-apps/pull/4489
