### ISSUE TITLE
Getting SQL Error While executing MySQL Queries - 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17610]
**Describe the issue:****

###  <IS_HOME>dbscripts/identity/stored-procedures/mysql/confirmation-code-cleanup
encountering a SQL error while executing MySQL queries in the dbscripts/identity/stored-procedures/mysql/confirmation-code-cleanup 

**PROCEDURE <DBName>.WSO2_CONFIRMATION_CODE_CLEANUP_RESTORE does not exist**
**PROCEDURE <DBName>.WSO2_CONFIRMATION_CODE_CLEANUP does not exist**

```
Error occurred during SQL script execution

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$
CREATE PROCEDURE `WSO2_CONFIRMATION_CODE_CLEANUP_RESTORE`()
BEGIN
 ' at line 1 
```

```
Error occurred during SQL script execution

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$
CREATE PROCEDURE `WSO2_CONFIRMATION_CODE_CLEANUP_RESTORE`()
BEGIN
 ' at line 1
```

2. ` <IS_HOME>dbscripts/identity/stored-procedures/mysql/par-request-cleanup/mysql-par-request-cleanup.sql
```
Error occurred during SQL script execution

Reason:
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$
CREATE PROCEDURE `WSO2_PAR_REQUEST_CLEANUP`()
BEGIN

    -- -------' at line 1
```

**Comment by ashanthamara** [comment]
Scripts can be successfully executed against the MYSQL identity DB.

<img width="921" alt="image" src="https://github.com/wso2/product-is/assets/75057725/9d94a431-ee44-4aad-9ed0-d4f6ef94724e">

<img width="920" alt="image" src="https://github.com/wso2/product-is/assets/75057725/99f1d209-e8a1-4a67-a268-a618e736b60f">

Above issue could occur when setting the `DELIMETER` from the script executing software.
