### ISSUE TITLE
The added second factor authentication step is not visible in the UI , unless the page is refreshed.

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17628]
**Describe the issue:**

The added second-factor authentication step is not visible in the UI ,unless the page is refreshed.

https://github.com/wso2/product-is/assets/40081059/3df4d23c-5628-4944-92d2-66e57491f8ea

**How to reproduce:**

1.Login to the console
2.Create and application
3.Go to the sign in method section
4.set password and username as the first factor authentication
5.Set email OTP as the second step of authentication
6.Click on Update

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by lashinijay** [comment]
Issue is not reproducible in the latest pack.
[Screencast from 19-11-23 02:20:48 PM IST.webm](https://github.com/wso2/product-is/assets/30428591/6d116203-ad0f-4e31-95c2-47d5cb137cd4)
