### ISSUE TITLE
Add Unit Tests for Branding Preference Resolver 

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#17627]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**
- Currently, `Branding Preference Resolver` component [1] does not contain unit tests to verify its functionality.

**Describe the solution you would prefer**
- Add unit tests into the component.

[1] - https://github.com/wso2-extensions/identity-branding-preference-management/tree/main/components/org.wso2.carbon.identity.branding.preference.resolver

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
