### ISSUE TITLE
Self sign up: When account confirmation is expired a blank page appears

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1762]
**Tried in:**
Google Chrome Version 63.0.3239.108

**Steps**
1. Self registered for an account
2. Let the account confirmation link be expired

Clicked the link and the following page loaded. Proper error message should be given.

![is_issue_9](https://user-images.githubusercontent.com/15624590/34157668-98fbf2c6-e4e8-11e7-920b-35324feb3fe1.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
