### ISSUE TITLE
Improve Branding Preference Resolver Cache Clearing

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#17626]
**Is your suggestion related to an experience ? Please describe.**
- Currently,  branding resolver caches for a specific organization and all its children down the tree will be cleared once new branding is added for that organization [1].

**Describe the improvement**
- The following improvements are suggested.
    - Check if the sub org has branding and if so, skip clearing the cache for that sub org and all its children down the tree [2].
    - Fetch the tenant domains of the sub-tree in a breadth first order in one database call [3].
    - Offload the work of clear cache if exist to a executor service [3].

[1] - https://github.com/wso2-extensions/identity-branding-preference-management/pull/17
[2] - https://github.com/wso2-extensions/identity-branding-preference-management/pull/17#discussion_r1360587612
[3] - https://github.com/wso2-extensions/identity-branding-preference-management/pull/17#discussion_r1363009937

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
