### ISSUE TITLE
"Enable assertion encryption" is not working at new management console

### ISSUE THREAD

**Issue by indeewari** [wso2/product-is#17622]
**Describe the issue:**
UI uses an incompatible property key named "IsEnableAssetionEncription" instead of "IsAssertionEncrypted" for IDP "Enable assertion encryption" in new management console. This has blocked encrypting the SAML assertion.

The same flow working properly in the carbon console .

This defect can be due to this PR.
- https://github.com/wso2/identity-apps/pull/4231

**How to reproduce:**
1. Create an IDP in new management console
2. Check "Enable assertion encryption" with relevant certificate
3. Try SAML login
4. SAML login fails

<img width="870" alt="image" src="https://github.com/wso2/product-is/assets/4128062/6d86757f-f2ef-4e1f-9c6b-5018a8f138be">

**Expected behavior:**
New management console should support SAML assertion encryption

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Verified in the latest beta snapshot

<img width="1503" alt="Screenshot 2023-11-20 at 15 24 38" src="https://github.com/wso2/product-is/assets/41533942/354118fd-c895-4c35-bfd2-efe5d8f7e9b6">

**Comment by pavinduLakshan** [comment]
Verified in the latest build

<img width="1503" alt="Screenshot 2023-11-20 at 15 24 38" src="https://github.com/wso2/product-is/assets/41533942/ddc42585-b66b-429c-be46-75fadd954941">
