### ISSUE TITLE
Google connection icon will be removed when updated from the Management Console

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#17637]
**Describe the issue:**
When a Google connection created from the Console is updated from the management console, the Google icon displayed in Console will be changed to the default connection icon.

When created,
<img width="361" alt="image" src="https://github.com/wso2/product-is/assets/12439288/c5088a46-557f-4406-a1ad-19612db94cbe">

After updated,
<img width="351" alt="image" src="https://github.com/wso2/product-is/assets/12439288/32f5a166-6cfd-4319-9e0c-09af3b34b8ff">

**How to reproduce:**
1. Login to the console
2. Create a google connection
3. Login to the Management console
4. Update the same connection

**Expected behavior:**
The Google icon should not change

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
