### ISSUE TITLE
Adding Organization User Invitation Email Template to Existing Organizations/Tenants

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#17634]
**Is your suggestion related to an experience ? Please describe.**
Add the email template [1] for existing organizations.

[1] https://github.com/wso2-extensions/identity-event-handler-notification/pull/204

**Describe the improvement**

**Additional context**

**Comment by sadilchamishka** [comment]
Will be captured from the migration docs. It is asked to copy the email-admin-config.xml file from the new IS 

<img width="1120" alt="Screenshot 2024-02-07 at 06 39 13" src="https://github.com/wso2/product-is/assets/35717390/b07e06de-8709-4c42-ac48-3107927c3343">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
