### ISSUE TITLE
Update IS samples to work with localhost instead localhost.com

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17635]
**Is your suggestion related to an experience ? Please describe.**
Created this task from the [PR](https://github.com/wso2/docs-is/pull/3699) to track the improvement of using `localhost` in sample applications instead of `localhost.com`. This PR only updates a few sample applications and we should update all the apps to cater this requirment.

With regard to this,
- Sample application config files
- Sample application catalog
- Docs
Should be updated.

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
