### ISSUE TITLE
[Doc] The complete request for claim mapping is not specified

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1763]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

In the below doc, the SP updation request does not specify the complete claim mapping request, neither specify ... to indicate that there are more to configure. Inconsistent with the SP creation request

```
<xsd1:claimMappings>
                  <!--Optional:-->
                  <xsd1:defaultValue>?</xsd1:defaultValue>
                  <!--Optional:-->
                  <xsd1:localClaim>
                     <!--Optional:-->
                     <xsd1:claimId>?</xsd1:claimId>
                     <!--Optional:-->
                     <xsd1:claimUri>?</xsd1:claimUri>
                  </xsd1:localClaim>
                  <!--Optional:-->
                  <xsd1:mandatory>?</xsd1:mandatory>
                  <!--Optional:-->
                  <xsd1:remoteClaim>
                     <!--Optional:-->
                     <xsd1:claimId>?</xsd1:claimId>
                     <!--Optional:-->
                     <xsd1:claimUri>?</xsd1:claimUri>
                  </xsd1:remoteClaim>
                  <!--Optional:-->
                  <xsd1:requested>?</xsd1:requested>
               </xsd1:claimMappings>
```

https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
