### ISSUE TITLE
Customized email template with the selected locale is not applied for the emails sent

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17638]
**Describe the issue:**

Customized email template with the selected locale is not applied for the emails sent

Follow the below document for customized email templates
https://is.docs.wso2.com/en/next/guides/branding/customize-email-templates/

**How to reproduce:**

1. Login to the console
2. Create a user, with the attribute local 
(have added **fr**  for French locale)
3. Go to branding => email templates
4. Configure an email template with the preferred locale
(Here I have selected email OTP with french template, which includes french )

https://github.com/wso2/product-is/assets/40081059/d7ee3bc1-660d-49b3-9e00-038bb569d0a9

5. Create an application 
 - set username and password as the first factor of authentication
 - set email OTP as the second-factor authentication.
 
6.Try to login in to the application
7.Select the languqge as french and procced with authentication steps

https://github.com/wso2/product-is/assets/40081059/211127c3-8715-4c68-8f50-be0caec5180d

The received email with the OTP code is still in English locale , even though it should be in French template

<img width="587" alt="Screenshot 2023-11-07 at 16 56 21" src="https://github.com/wso2/product-is/assets/40081059/636e33d7-f045-4dc5-9228-954050104e37">

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnjanaSamindraPerera** [comment]
This is working fine for me. Please use the correct [locale](https://wso2.com/asgardeo/docs/references/localization-in-asgardeo/#language-settings:~:text=%23-,Supported,-languages) in step 2. Here **fr_FR** for French.

![Screenshot 2023-11-09 at 16 58 57](https://github.com/wso2/product-is/assets/38417165/aee8a20e-f722-4e24-8033-09f3b19b8d5f)

**Comment by AnjanaSamindraPerera** [comment]
This is working fine for me. Please use the correct [locale](https://is.docs.wso2.com/en/next/references/localization/) in step 2. Here **fr_FR** for French.

![Screenshot 2023-11-09 at 16 58 57](https://github.com/wso2/product-is/assets/38417165/8709c80a-ebea-40c6-bcb3-db13d6264dc0)
