### ISSUE TITLE
Add a new claim to the existing tenants/organizations

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#17633]
**Is your suggestion related to an experience ? Please describe.**
From the feature[1] we have introduced a new claim to store the organization which the user is originally managed after sharing to a sub organization. PR[2].

Introduced Identity Claim : http://wso2.org/claims/identity/managedOrg

[1] 
[2] https://github.com/wso2/carbon-identity-framework/pull/4879

**Describe the improvement**

**Additional context**

**Comment by ShanChathusanda93** [comment]
Hi team,

This newly introduced claim will be created in the organization creation process. But as for now we are checking whether the data is available for the claim and based on that we are executing a listener. This needs to be improved by checking whether the claim is available in the organization and then proceed with the listener execution. [1] will track down the fixing.

[1] https://github.com/wso2/product-is/issues/17687

Best regards,
Shan.

**Comment by AnuradhaSK** [comment]
- According to https://github.com/wso2/product-is/issues/17633#issuecomment-1803115638 and the feature design new claim is required only for organizations.
- The organization creation is introduced to default IS in IS-7.0.0 as a new feature.
- Therefore, no need to add the new claim to migrating users' existing tenants.
- Hence closing the migration issue

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
