### ISSUE TITLE
Issue with Misleading Instruction in Application Registration Flow

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17632]
**Describe the issue:**

In the Application Registration flow, there is a statement indicating, "You can download and run a sample at a later step." However, the current implementation lacks the option to download a sample app, and there are no instructions provided on how to download and run the sample application.

**How to reproduce:**

**Expected behavior:**
If applicable, provide clear instructions or links on where users can find and download the sample application for their reference.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: alpha2 Onprem 7.0
 - OS: Mac
 - Database:MySQL, H2
 - Userstore:JDBC
 - Browser: Firefox
 - 

<img width="750" alt="Screenshot 2023-11-07 at 15 26 47" src="https://github.com/wso2/product-is/assets/39120228/5e24bcfc-f331-4ca7-a08e-eb3cda9fb925">

**Comment by Achintha444** [comment]
Since in WSO2 identity server, we do not have a sample application pointed out, we have discussed to remove the message component.

**Comment by Achintha444** [comment]
* Fixed in the latest identity-server version, hence closing the issue
<img width="1145" alt="Screenshot 2023-11-13 at 18 42 49" src="https://github.com/wso2/identity-apps/assets/46097917/f21acd5c-f5d9-46e7-a3ca-cbf1e63e1cc4">
