### ISSUE TITLE
Pagination is not applied to the "Scopes" page

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17642]
**Describe the issue:**
Even with more than 10 scopes, the page is not displayed with pagination, which is inconsistent with the rest of the UIs. 

[recording(14).webm](https://github.com/wso2/product-is/assets/106053688/6432ca19-1e3e-4e47-812f-85f6746ef219)

**How to reproduce:**
1. Navigate to "Scopes" page
2. Create more than 10 scopes
3. Verify the pagination

**Expected behavior:**
User should be populated with pagination consistent to the other pages.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment]
Currently, the API `api/server/v1/oidc/scopes` does not support pagination hence we cannot enable pagination from the UI. This was discussed to track as an `improvement`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
