### ISSUE TITLE
Incorrect permission displaying module is used for roles' permission display during the user creation wizard

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17647]
**Describe the issue:**

1. Try user creation flow. 
2. There is a step to assign roles
3. For a given role, you can see a key icon to view permissions of the role
4. It shows the old permission tree model instead of actually assigned permissions through API resources

https://github.com/wso2/product-is/assets/25483865/fb9f8b7c-d27b-4bd7-b03b-724c70d3bff8

<img width="772" alt="Screenshot 2023-11-08 at 00 18 01" src="https://github.com/wso2/product-is/assets/25483865/4016fb15-f0c4-406b-beaf-5f7a1e3eb475">

<img width="755" alt="Screenshot 2023-11-08 at 00 17 50" src="https://github.com/wso2/product-is/assets/25483865/4785fb5e-e6bc-41b0-aa83-6bfaa8f8d04c">

**Comment by AnuradhaSK** [comment]
- This issue depends on https://github.com/wso2/product-is/issues/17645.
- If we decides to remove role assignment option during user creation, nothing to be fixed in reported issue in #17647

**Comment by GoushiRam** [comment]
Population of API Resource permissions without the old IS Permissions is a critical level issue as it hinders a user from  viewing the permissions relevant to a role before adding it to a user
