### ISSUE TITLE
Improve the user creation options' text

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#17640]
**Is your suggestion related to an experience ? Please describe.**

<img width="625" alt="Screenshot 2023-11-07 at 17 07 00" src="https://github.com/wso2/product-is/assets/67315176/c929c7da-9d25-47e9-a82c-072654258949">

**Describe the improvement**

**Additional context**

**Comment by dasuni-30** [comment]
This dropdown was improved as shown below.

<img width="217" alt="Screenshot 2023-10-18 at 18 10 24" src="https://github.com/wso2/product-is/assets/27746285/ddd163ee-87e0-4a61-bbad-853ec7df1855">

And this is a regression created from another PR.

**Comment by dasuni-30** [comment]
### Verified in the `WSO2 Identity Server-7.0.0-beta-SNAPSHOT`

<img width="173" alt="Screenshot 2023-11-09 at 11 47 45" src="https://github.com/wso2/product-is/assets/27746285/001ee5d0-da4a-4aa0-8d97-16dcb7c38bf0">
