### ISSUE TITLE
Role audience is required in role assignment view given during user creation flow

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17648]
**Describe the issue:**
1. Create roles with the same name in different audiences (eg: role1 in organization audience, role1 in different application audience)
<img width="1394" alt="Screenshot 2023-11-08 at 00 14 43" src="https://github.com/wso2/product-is/assets/25483865/0a61038a-5881-4433-b20a-3fb4ac2b6b06">

2.  Try user creation flow
3. During the role assignment option you can see multiple roles with the same name. In order to differentiate the roles "role audience" detail is required to show

<img width="829" alt="Screenshot 2023-11-08 at 00 15 33" src="https://github.com/wso2/product-is/assets/25483865/0c098b57-6514-4049-8a3d-fec40aa0b020">

**Comment by AnuradhaSK** [comment]
- This issue depends on https://github.com/wso2/product-is/issues/17645.
- If we decides to remove role assignment option during user creation, nothing to be fixed in reported issue in #17647

**Comment by kayathiri4** [comment]
![Screenshot from 2023-11-17 18-12-43](https://github.com/wso2/product-is/assets/36656035/e7923051-436f-4470-97f5-2fb2dc4977a3)
