### ISSUE TITLE
Enhance Landing Page Design for Generic Design Independent of User Scopes.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17644]
**Describe the issue:**
When a user signs in to the console without being assigned to any group or without having a proper role, a blank Getting Started page is displayed. This issue needs attention to ensure that users without the necessary group or role assignments receive an appropriate message or are redirected to the correct page instead of encountering a blank Getting started page.

<img width="1497" alt="Screenshot 2023-11-07 at 17 48 27" src="https://github.com/wso2/product-is/assets/41188245/c81bb92d-9755-4c9c-a6d8-32dc9ddf6f24">

**How to reproduce:**

1. Add a user 
2. Try to login to the console with that user
3. A blank Getting started page will be prompt.

**Expected behavior:**
A proper error page should be displayed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
@melanisilva shall we change the title to imply that we need to improve the landing page to have a generic design independent of user scopes?

**Comment by melanisilva** [comment]
> @melanisilva shall we change the title to imply that we need to improve the landing page to have a generic design independent of user scopes?

Ack. Will do.

**Comment by pavinduLakshan** [comment]
There's no point in showing the getting started page to a user who doesn't have app mgt and user mgt permissions. Therefore, it is planned to hide this page for such a user. Improvement is tracked with https://github.com/wso2/product-is/issues/17209

**Comment by jeradrutnam** [comment]
Navigation groups also should be hidden if user doesn't have required permissions
