### ISSUE TITLE
Leading and trailing whitespaces on OTP inputs are not removed

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17641]
**Describe the issue:**
Leading and trailing whitespaces on OTP inputs (TOTP, EmailOTP, SMSOTP) are not removed and causes authentication failures.

**How to reproduce:**
Add a leading or trailing whitespace on OTP inputs (TOTP, EmailOTP, SMSOTP)

**Expected behavior:**
It should trim leading and trailing whitespaces on OTP inputs

**Environment information** 
 - Product Version: IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
