### ISSUE TITLE
Incorrect permission displaying module is used for roles' permission display during the group creation wizard

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17649]
**Describe the issue:**

1. Try group creation flow.
2. There is a step to assign roles
3. Click on the key icon given to see the permissions of the role. It will show old permission tree instead of assigned permissions from the API resources
<img width="745" alt="Screenshot 2023-11-08 at 00 40 09" src="https://github.com/wso2/product-is/assets/25483865/bdaad611-b070-495a-9845-2be0912e8af6">

**Comment by dasuni-30** [comment]
**Verified in wso2is-7.0.0-beta-SNAPSHOT.0 pack**
