### ISSUE TITLE
Analyze Console UI inconsistencies: Super Tenant vs. Other Root Tenants due to isCurrentOrganizationRoot() method

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#17657]
**Describe the issue:**
In console, the method `isCurrentOrganizationRoot()` [[1](https://github.com/wso2/identity-apps/blob/e623561d6b4a518dfef77ec9b998b8402c63547a/apps/console/src/features/organizations/utils/organization.ts#L45)] is defined to check whether the current organization is the root organization for the particular IS deployment. The current implementation logic defines the root organization as the super tenant. 

However, use of this method leads to UI inconsistencies between the super tenant and the other tenants since other tenants can also be considered as root level organizations according to B2B scenarios.

ex: 
- https://github.com/wso2/product-is/issues/17378
- https://github.com/wso2/product-is/issues/17659

Since this method has been used across several features, we need to check to each usage and verify the use particular feature is behaving as intended for super tenant, every other root level tenant and sub organizations.

[1] https://github.com/wso2/identity-apps/blob/e623561d6b4a518dfef77ec9b998b8402c63547a/apps/console/src/features/organizations/utils/organization.ts#L45

**Comment by pavinduLakshan** [comment]
The ambiguous method has been removed and all the conditions also have been replaced with more comprehensive methods with https://github.com/wso2/identity-apps/pull/4628, but there still might be cases where `isCurrentOrganizationRoot` has been incorrectly used to determine a first level org and vice versa. With the more comprehensive methods that are now available, we would be able to fix those issues in a much lower effort.
