### ISSUE TITLE
The user profile UI is editable for users in read-only user stores when the tenant is not the super tenant

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#17659]
**Describe the issue:**

In the tenants other than the super tenant, if we navigate to a profile of a user who is in a read only user store, an editable UI is displayed for the user instead of a read only UI.

<img width="918" alt="image" src="https://github.com/wso2/product-is/assets/27700915/8532edaa-40c1-4b4b-898e-2279ee7ab330">

<img width="1116" alt="image" src="https://github.com/wso2/product-is/assets/27700915/00ab9f59-c089-4972-81d6-3a763878728e">

If we try the same flow in the super tenant, a proper read only UI is displayed for the user profile.

**How to reproduce:**

1. Create a tenant in the IS.
2. Log into the console as an admin in the created tenant. 
3. Create a JDBC user store.
4. Add a user to the created user store.
5. Go to the settings page of the user store and mark it as read only.
6. Navigate to the user profile section of the user in the read only user store. 

**Expected behavior:**

A read only UI should be displayed.

**Comment by savindi7** [comment]
The `readOnly` property of read only userstores is being sent as false from the BE. Hence, this is changed as a BE issue.

<img width="638" alt="Screenshot 2023-11-13 at 15 23 34" src="https://github.com/wso2/product-is/assets/67315176/b0d18e88-8df6-479a-ba2e-d6c43162d110">

**Comment by JeethJJ** [comment]
All the properties listed here are added to the userStore related xml file on userStore creation. The `ReadOnly` property is required to be sent  from the request on that UserStore creation, where it is not present. Hence, when retrieving the userstore related properties, a default value of `false` is set. 

Also, there is a UI validation for not sueprTenant to avoid the case [1]. This needs to be removed as well.

With the property true and the validation removed, the UI is as expected.

<img width="1211" alt="Screenshot 2023-11-18 at 13 02 59" src="https://github.com/wso2/product-is/assets/50905371/e38b7d15-d617-4eba-8146-d5c17c9aaf99">


[1] https://github.com/wso2/identity-apps/blob/f9e250b900d6dc62eacdaf9a67b44b5cd02118dd/apps/console/src/features/users/pages/user-edit.tsx#L110
