### ISSUE TITLE
Application configured allowed role audience is not correctly displayed in role creation view

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17653]
**Describe the issue:**
1. Create a few apps
2. Go to the roles tab of them, set some applications allowed audience for role association as "Application" and set "Organization" for some applications
3. Go to User Management > Roles
4. Give a role name and select "Application" radio button under audience selection
5. The available applications will be listed except the console and my account
6. See the supported audience description 
7. It has the negation of actual configured value

In my case, app4 supports organization audienced roles and others supports application audienced roles.

<img width="796" alt="Screenshot 2023-11-08 at 01 11 19" src="https://github.com/wso2/product-is/assets/25483865/6dc96380-4005-4200-b026-cbaf4bfa5814">

**Comment by JayaShakthi97** [comment]
Duplicated issue: https://github.com/wso2/product-is/issues/17630

**Comment by JayaShakthi97** [comment]
Fixed in Beta-SNAPSHOT

![image](https://github.com/wso2/product-is/assets/37938529/167ea869-2012-454f-9f78-c36178d89e33)
