### ISSUE TITLE
Need to improve UX of Create role option given under application's Role tab

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17654]
**Describe the issue:**
1. Create new application
2. Go to Roles tab of the created application
3. You want to set the allowed roles audience as "Application" and create a few roles from there.
4. Unless the user selects the "Application" radio button and clicks "update button", user can't create a role here.
5. Need to improve the UX to successfully do the tried steps in the following recording.

https://github.com/wso2/product-is/assets/25483865/f9ca8ddc-45f0-4213-ae14-dcac56bc0502

**Comment by dewniMW** [comment]
In this view if clicked on confirm, we can send an API call to update the role type in the application.
<img width="670" alt="Screen Shot 2023-11-15 at 12 31 27 PM" src="https://github.com/wso2/product-is/assets/24982871/51bd9af8-70e9-4f3c-b7bd-8a8d93af87c4">
