### ISSUE TITLE
Role audience is required in role assignment view given during group creation flow 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17650]
**Describe the issue:**

1. Create roles with the same name in different audiences (eg: role1 in organization audience, role1 in different application audience)

<img width="1394" alt="Screenshot 2023-11-08 at 00 14 43" src="https://github.com/wso2/product-is/assets/25483865/0a61038a-5881-4433-b20a-3fb4ac2b6b06">

2.  Try group creation flow
3. During the role assignment option you can see multiple roles with the same name. In order to differentiate the roles "role audience" detail is required to show

<img width="745" alt="Screenshot 2023-11-08 at 00 40 09" src="https://github.com/wso2/product-is/assets/25483865/a73653f5-bd08-444a-8eb7-a334ccece563">

**Comment by kayathiri4** [comment]
![image](https://github.com/wso2/product-is/assets/36656035/5972bd37-c762-4ef5-9b8f-fda98d21006e)
