### ISSUE TITLE
Assigned roles of the group need to show role's audience 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17652]
**Describe the issue:**
1. Create roles with the same name in different audiences (eg: role1 in organization audience, role1 in different application audience)
2. Create a group
3. Assign the group to roles with the same name in different audiences.
4. Group-to-role assignments will be successful 
5. Go to the Group's assigned roles view
6. Only the assigned roles names are shown
7. But the role audience is also required to distinguish the assigned roles. (API returns the audience data)

https://github.com/wso2/product-is/assets/25483865/29dcf047-af25-40d1-8f6d-7a474224c6f6

<img width="1709" alt="Screenshot 2023-11-08 at 00 56 26" src="https://github.com/wso2/product-is/assets/25483865/61bd9052-6892-4701-a3a6-cc8a57cc3588">

**Comment by shashimalcse** [comment]
There is also a backend issue. In the new authorization runtime, when retrieving a group's roles, roles with similar names are assigned the same audience (You can see this in the screen shot).
Fix for backend issue : https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/509
