### ISSUE TITLE
Warning Log Generated in wso2carbon.log When User Attempts Login to Application with "Enable Authorization" Enabled

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17656]
**Describe the issue:**
When a user tries to log in to an application where "Enable Authorization" is enabled under the Application Advanced Tab, a warning log is generated in the wso2carbon.log file. 

```
[2023-11-08 08:53:51,195] [fe971235-5390-4685-a81d-cdfba6d7e4ef]  WARN {org.wso2.carbon.identity.application.authz.xacml.handler.impl.XACMLBasedAuthorizationHandler} - No applicable rule for service provider 'SP_AppAlpha2_Nov07@carbon.super', Hence authorizing the user by default. Add an authorization policy (or unset authorization) to fix this warning.
```

**How to reproduce:**
1. Enable "Enable Authorization" under the Application Advanced Tab
2. Attempt to log in to the application using valid credentials.
3. Observe the wso2carbon.log file for warning logs generated during the login attempt.

**Expected behavior:**
Logging in to the application with "Enable Authorization" enabled triggers a warning log entry in the wso2carbon.log file.

Remove "Enable Authorization" button/ option from console

**Environment information** 
 - Product Version: Alpha2 7.0
 - OS: Mac
 - Database: Mysql
 - Userstore: JDBC

---

**Comment by ayeshajay** [comment]
This is not reproducible in the latest console version

![Screenshot 2023-11-18 at 3 22 00 PM](https://github.com/wso2/product-is/assets/51480027/250134c3-d427-4af6-bedb-6086692d739c)

**Comment by ayeshajay** [comment]
Closing the issue as this is not reproducible.
