### ISSUE TITLE
[Doc][Query] What is the Integer value that identifies the claim?

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1766]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

**Under Claim configuration level parameters**
claimMappings.localClaim.claimId
claimMappings.remoteClaim.claimId 

Description: Integer value that identifies the claim. Applies to both localClaim and remoteClaim elements.

What is the Integer value that identifies the claim? Is it the Display Order ID?

https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
