### ISSUE TITLE
Email magic link connection can be added as the first step, but QSG says to add with identifier first as the first step 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17664]
**Describe the Issue:**
When added by the template
![image](https://github.com/wso2-enterprise/asgardeo-product/assets/5061791/ff791b5c-41a3-4953-849c-1234e8c24d0e)

What is shown in the QSG

![image](https://github.com/wso2-enterprise/asgardeo-product/assets/5061791/bd9e7667-ee33-497f-aeda-fdd971cac0c2)

**How To Reproduce:**

**Expected behavior:**
Update the QSG accordingly

**Device Information:**
 - Device (e.g. PC, iPhone6):
 - OS (OSX, Android, iOS):
 - Browser + Version:

---

### Optional Fields

**Related Issues:**

**Suggested Labels (for non-committers):**

**Suggested Assignees (for non-committers):**

---
### Testing Related Fields

**Local e2e Tests Status (Please attach the screenshots of the result):**

**Manual Test Plan (Please attach the document link):**

**Manual Test Plan Reviewed by:**

**Comment by Achintha444** [comment]
* Fixed in the latest identity-server

<img width="1800" alt="Screenshot 2023-11-20 at 10 57 55" src="https://github.com/wso2/product-is/assets/46097917/dd71a4fe-8a4f-44d6-8989-cc6cbd9efe35">
