### ISSUE TITLE
Adding new attribute mappings should be under "Manage Attribute Mapping"

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17668]
**Describe the issue:**

![image](https://github.com/wso2/product-is/assets/5061791/181e15a2-98ca-4420-8ad6-4743ef278a7a)

**How to reproduce:**

**Expected behavior:**
$subject

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
### Verified in the wso2is-7.0.0-beta-SNAPSHOT

<img width="1437" alt="Screenshot 2023-11-19 at 09 50 48" src="https://github.com/wso2/product-is/assets/27746285/2ab3356c-ef2f-4c40-919d-327c00688104">
