### ISSUE TITLE
Myaccount being an application provided out of the box in IS, what is the purpose of allowing other configurations to be changed

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17665]
**Describe the issue:**

![image](https://github.com/wso2/product-is/assets/5061791/f816907f-6c01-4073-8bc5-3ac98e4e927d)

User Attributes, APIs, Roles, Protocol are predefined at the time application is developed. 

**How to reproduce:**

**Expected behavior:**

 Myaccount should be listed under the application list in IS 7
    - My account should be sharable to other orgs
    - Sign in method should be editable
    - support externalizing the account, by allowing to change the callback URL
    - Attributes sharing settings should be editable
    - Other settings shouldn't be editable
    - Info, Provisioning, Advanced, and Roles sections are not needed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
- [ ] Myaccount should be listed under the application list in IS 7
- [ ] My account should be sharable to other orgs
- [ ] Sign in method should be editable
- [ ] support externalizing the account, by allowing to change the callback URL
- [ ] Attributes sharing settings should be editable
- [ ] Other settings shouldn't be editable
- [ ] Info, Provisioning, Advanced, and Roles sections are not needed

**Comment by DilshanSenarath** [comment]
This issue will be on hold until we receive a decision from the B2B team. The decision pertains to whether the 'My Account' should be removed from system apps and retained solely as a B2B app. Then, users would be able to make changes similar to a regular application when registered with any organization by default.

**Comment by DilshanSenarath** [comment]
Since these changes are available in 7.0.0-Beta release, will close the issue.
