### ISSUE TITLE
Configuration flow for email magic link under connections endup in the API authorization view in the application instead of sign-in flows

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17663]
**Describe the issue:**
Refer the video below.

https://github.com/wso2/product-is/assets/5061791/9c4cd277-13b6-4956-91ed-5d832b7fc7cb

**How to reproduce:**
Refer the video below.

**Expected behavior:**
User should be taken to the Sign-in flow configuration as mentioned in the quick start.
Test this flow for other connection types as well and fix.

**Comment by Achintha444** [comment]
* This is fixed in the latest console, hence closing the issue.
