### ISSUE TITLE
Overlay on the login page timeout error message 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17669]
**Describe the issue:**

There is an Overlay on the login page timeout error message 
<img width="1487" alt="Screenshot 2023-11-08 at 11 27 40" src="https://github.com/wso2/product-is/assets/40081059/d192869f-1ea7-443d-bfca-8b635b2bbf98">

**How to reproduce:**

1. Login to the console
2. Stay idle on the console until the page timeout error 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ayshsandu** [comment]
This overlay is expected when a user has been idle on the login page for some time and the login instance is about to timeout. Problem is the styling of the overlay message which make it impossible to read anything on the page. 
Need to fix it.
