### ISSUE TITLE
Tenant tier retrieval API call throws CORS error

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17675]
**Describe the issue:**

$subject

<img width="1432" alt="Screenshot 2023-11-08 at 14 59 28" src="https://github.com/wso2/product-is/assets/41533942/56d84d08-d7b7-4dea-8572-ce0eb2f27b59">

**How to reproduce:**
1. Sign into console
2. Observe the network requests being sent.

**Expected behavior:**

This API should not be called in IS.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
Let's try to stop the `/tier` call by checking the existence of the of the API endpoint URL without having to use a config to stop the call

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

https://github.com/wso2/product-is/assets/41533942/e800e577-bcf0-41d7-952d-2333974b9a5a
