### ISSUE TITLE
Revisit the template of the email OTP  content section  , as it contains duplicate email body tags /placeholders

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#17671]
**Describe the issue:**

Revisit the template of the email OTP  content section, as it contains duplicate email body tags /placeholders.

Check line 316 and 366 , both contains body tags with different content . But only the body content which starts from 358 is taken into consideration and shown in the preview section /emails sent.

<img width="1129" alt="Screenshot 2023-11-08 at 13 46 30" src="https://github.com/wso2/product-is/assets/40081059/9d975feb-6667-4860-9525-2ffdbc9a10ee">

Only this section is updated in the preview section
<img width="1139" alt="Screenshot 2023-11-08 at 13 46 51" src="https://github.com/wso2/product-is/assets/40081059/02b046d7-331d-45cf-932e-5b429c1aa70e">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Hi @asekawa,

These body tags serve 2 purposes.

- 1st tag is within `<!-- BEGIN PREHEADER // -->` and `<!-- // END PREHEADER -->` which will be used to show the content in the email list view
  <img width="945" alt="image" src="https://github.com/wso2/product-is/assets/1332991/98576ae8-624c-4f54-8958-a87265e5eb53">

- 2nd tag is actually used to show the show the mail content.

So both of the tags are actually required in the template.
