### ISSUE TITLE
Add username paramter to the query params when user is locked on Email OTP

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17674]
**Is your suggestion related to an experience ? Please describe.**
As mentioned in https://github.com/wso2/product-is/issues/16333#issuecomment-1679205342, when a user is locked, following params are sent.

TOTP
```
username: <username>
authFailure: true
authFailureMsg: login.fail.message
```

Email OTP
```
authFailure=true
authFailureMsg=user.account.locked
```

The request is to add `username` param in the Email OTP flow as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
