### ISSUE TITLE
Implementation for populating the UIs related to the custom extensions in IS

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17676]
**Is your feature request related to a problem? Please describe.**
There are multiple customizations and extensions that can be added to the IS. 
 ex: 
 - custom federated authenticators
 - custom local authenticators
 - provisioning connectors
 - governance connectors

There has to be a methodology to populate the respective UIs in the console according to it. 

**Describe the solution you would prefer**

**Additional context**

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/19125 too

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
