### ISSUE TITLE
Remote Logging Should be Hidden from the Side Navbar for Tenants, Except Super Tenant.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17679]
**Describe the issue:**
The Remote Logging page is currently visible for first-level organizations. However, the expected behavior is the opposite—Remote Logging should not be visible for other tenants but not for the super tenant. The current behavior needs to be corrected to align with the intended visibility for these entities.

<img width="1512" alt="Screenshot 2023-11-08 at 17 13 07" src="https://github.com/wso2/product-is/assets/41188245/a743687b-a746-4dbe-87dd-4586b6e1b8a1">

<img width="544" alt="Screenshot 2023-11-08 at 17 57 13" src="https://github.com/wso2/product-is/assets/41188245/04b90cea-67f1-4fbb-a407-927f55c1d63b">

**How to reproduce:**

1. Create a new tenant.
2. Log in to the newly created tenant from the console.

**Expected behavior:**
The Remote Logging feature should be hidden for other tenants.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This issue has been introduced again with the effort of revamping server configurations section.

<img width="1503" alt="Screenshot 2023-11-20 at 13 12 28" src="https://github.com/wso2/product-is/assets/41533942/b2ec3797-999b-408e-9b1b-3717889dd7d3">

cc: @DonOmalVindula

**Comment by pavinduLakshan** [comment]
Verified in the latest build.

<img width="1503" alt="Screenshot 2023-11-21 at 10 00 19" src="https://github.com/wso2/product-is/assets/41533942/1fa20c25-a2f7-4883-b596-c9d83253e5e8">
<img width="1503" alt="Screenshot 2023-11-21 at 10 01 46" src="https://github.com/wso2/product-is/assets/41533942/cda1efd0-7ff2-4ba3-b55e-426aeb1393ce">
