### ISSUE TITLE
Add multiple users UX is confusing

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17670]
**Describe the issue:**

**How to reproduce:**

1.  Goto user management section in the console
2. Add new user -> select multiple useres
3. Enter a email for the user and proceed

![image](https://github.com/wso2/product-is/assets/5061791/ac349ca3-fbd3-42fb-99e6-0045fdd4da33)

Issue 1
 - Message is confusing as I did not intended to import a user from anywhere

Issue 2
 - What is the purpose of this user search?  

Issue 3
 - Even there is a default set of roles and groups nothing is listed under the roles and groups step
![image](https://github.com/wso2/product-is/assets/5061791/674b0a09-7b1f-4803-849e-828d6068cd53)

Issue 4
 - state that the user creation ends up is different for creating individual users and multiple users

Issue 5
 - you have to press enter to properly add a user, otherwise, the user won't be created even if you proceed. There is no indication about how to add multiple users to the screen.

https://github.com/wso2/product-is/assets/5061791/eeb30298-c8a7-4463-a0a9-0700bcb580b6

**Expected behavior:**
- user creation wizard should be self-explanatory and intuitive to use.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
```
Issue 1

Message is confusing as I did not intended to import a user from anywhere
```
The summary view is common to both Manual and File-based approaches. We can update the messaging of the success alert to be more specific for the Manual View.

```
Issue 2

What is the purpose of this user search?
```
We can hide the user search when the list is empty

```
Issue 3

Even there is a default set of roles and groups nothing is listed under the roles and groups step
```
The role assignment is done as a later improvement and tracked with https://github.com/wso2/product-is/issues/17284.

```
Issue 4

state that the user creation ends up is different for creating individual users and multiple users
```
Since we are adding multiple users in this wizard, we implemented a summary view to represent the successful and failed creations. Hence we cannot end the user in the user profile view similar to the single user creation.

```
Issue 5

you have to press enter to properly add a user, otherwise, the user won't be created even if you proceed. There is no indication about how to add multiple users to the screen.
```
We identified that pressing enter is not intuitive here and discussed about including it in the underneath the email input.

**Comment by dasuni-30** [comment]
### Action items

- [ ] Update the success/failed alert messaging from Import Successful to `User Creation Successful` for Manual option.

- [ ] Disable the Invite button when the email field is empty or when the user enters an invalid email.

- [ ] Update the hint text for the emails field `Add the email address of the user you wish to invite and press enter.`

**Comment by dasuni-30** [comment]
### Design Improvements 
cc: @jeradrutnam 

- [ ] Update the title and descriptions to avoid the `invite` term

- [ ] Add the info box to indicate that the newly created user receives the email to set the password.

- [ ] Update the emails hint

<img width="718" alt="Screenshot 2023-11-09 at 22 37 32" src="https://github.com/wso2/product-is/assets/27746285/e79fd35d-d384-4022-b1a7-a617bcd1f88e">

<img width="718" alt="Screenshot 2023-11-09 at 22 43 10" src="https://github.com/wso2/product-is/assets/27746285/4da412cf-c803-4559-a5fe-8629877b8fd5">

**Comment by jeradrutnam** [comment]
let's make the email sending information similar to add user modal design. Remove the info icon and make to fluid.
![image](https://github.com/wso2/product-is/assets/7569427/f6053e7f-f076-4213-b038-1a8bf2055989)
- Instead of showing that warning "Manual invite multiple users features can only be ..." message should show before coming to this page, if the email as username is disabled only, as a tip.
- Primary user store input should change to a information instead.

**Comment by JayaShakthi97** [comment]
- The following improvements are made through: https://github.com/wso2/identity-apps/pull/4581
  - [ ] Update the success/failed alert messaging from Import Successful to `User Creation Successful` for Manual option.
  - [ ] Disable the Invite button when the email field is empty or when the user enters an invalid email.
  - [ ] Update the hint text for the emails field `Add the email address of the user you wish to invite and press enter.`
  - [ ] Update the title and descriptions to avoid the `invite` term.
  - [ ] Add the info box to indicate that the newly created user receives the email to set the password.


https://github.com/wso2/product-is/assets/37938529/80290695-5afb-46d8-9a31-607cef7b4aa4

**Comment by JayaShakthi97** [comment]
- A discussion need to done on following points
	- Instead of showing that warning "Manual invite multiple users features can only be ..." message should show before coming to this page, if the email as username is disabled only, as a tip.
	- Primary user store input should change to a information instead.

**Comment by dasuni-30** [comment]
`Primary user store input should change to a information instead.` will be covered with https://github.com/wso2/product-is/issues/17681

**Comment by JayaShakthi97** [comment]
`Instead of showing that warning "Manual invite multiple users features can only be ..." message should show before coming to this page, if the email as username is disabled only, as a tip.`
- This will be addressed with https://github.com/wso2/product-is/issues/17613
