### ISSUE TITLE
Correction on the IS documentation on SAML RelayState query parameter

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17677]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the documentation around the SAML `RelayState` parameter, it has mentioned that `This request will authenticate and redirect the user to the URL in the RelayState parameter itself.`.

However the "RelayState" parameter is not processed at the SAML IDP side and it always returns the same value back in the authentication response. We can't redirect to the "RelayState" value.

Hence the documentation should be fixed for IS 6.1.0 and master.

[1] https://is.docs.wso2.com/en/latest/guides/login/saml-parameters-in-auth-request/

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
