### ISSUE TITLE
Disabled and non disabled input fields look almost identical

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#17689]
**Describe the issue:**

Disabled input fields and Active input fields with placeholders almost look identical. There should be a clear distinction.

<img width="701" alt="Screenshot 2023-11-09 at 09 33 00" src="https://github.com/wso2/product-is/assets/59327626/20221de9-4e82-43e6-83f1-15180f74e1be">

**Comment by Achintha444** [comment]
Better to track this as an `improvement`, hence removing the `bug` label.
