### ISSUE TITLE
Invalid Error message in Remote logging page. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17680]
**Describe the issue:**

Invalid error message for the tenants when trying to navigate to the Remote Logging page.

<img width="1512" alt="Screenshot 2023-11-08 at 17 27 08" src="https://github.com/wso2/product-is/assets/41188245/ec7455ef-8579-4af3-a635-6785b1f445af">

**How to reproduce:**
1. Add a new tenant.
2. log in to the created tenant from console\
3. Navigate to the Remote Logging page from the Side nav bar.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**
#17679  Remote Logging Should be Hidden from the Side Navbar for Tenants, Except Super Tenant. 

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This error is no longer reproducible in the latest beta snapshot build.
