### ISSUE TITLE
 Unnecessary User Store Selection Option for Bulk User Import

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17681]
**Describe the issue:**
Currently readonly input option to select the user store for bulk user import and manual import operations for external user stores. However, as currently does not support bulk user import or manual import for external user stores, this selection option is unnecessary and can cause confusion among users.

**How to reproduce:**
Navigate to the user Management 
Try Bulk user option
Look for the input option to select the user store for bulk user import.
Observe that the input option is present, even though bulk user import and manual import are not supported for external user stores.

**Expected behavior:**
Remove the input option to select the user store for bulk user import and manual import from external user stores, as these functionalities are not supported.
If, for any reason, the selection option needs to be displayed, set the dropdown as readonly to prevent any user interaction.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: Alpha2 7.0
 - OS:Mac
 - Database: MuSql
 - Userstore:JDBC

---

<img width="1089" alt="Screenshot 2023-11-08 at 14 41 02" src="https://github.com/wso2/product-is/assets/39120228/fb6f6846-d096-4e80-8ea3-8ea804ec49fc">

<img width="1174" alt="Screenshot 2023-11-08 at 14 40 55" src="https://github.com/wso2/product-is/assets/39120228/69e3b1ee-889e-47c1-9f27-6d866fd40be8">

**Comment by dasuni-30** [comment]
### Verified in wso2is-7.0.0-beta-SNAPSHOT

The user store option is removed

<img width="720" alt="Screenshot 2023-11-19 at 09 52 39" src="https://github.com/wso2/product-is/assets/27746285/bd47f179-0697-4eab-a38a-301af990c1ff">

<img width="720" alt="Screenshot 2023-11-19 at 09 52 53" src="https://github.com/wso2/product-is/assets/27746285/63ba2407-a4ac-417f-bfa5-274faaeca892">
