### ISSUE TITLE
Instead of the words "Ask password" we currently refer to "Invite user to set password".

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17683]
**Describe the issue:**
The current wording in the console states "Invite user to set the password" instead of the appropriate term "Ask Password." 

**How to reproduce:**
1. Login to console
2. Go to  login & registration > User Onboarding > Invite user to set the password
3. 

<img width="822" alt="Screenshot 2023-11-08 at 18 50 20" src="https://github.com/wso2/product-is/assets/39120228/5bbac6db-e622-4f00-9dbf-ea864166b379">

**Comment by Achintha444** [comment]
This will be tracked from the following issue
- https://github.com/wso2/product-is/issues/17590

Hence closing this.
