### ISSUE TITLE
[5.10.0] Getting hostname as the server host name when the authAPIURL is not configured

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#17686]
When using prompt function[1] with identity server 5.10 if the below configuration is not enabled(commented) in the <IS_HOME>/repository/deployment/server/webapps/authenticationendpoint/WEB-INF/web.xml , the host name is collected from the server host configured in the deployment.toml file.

By default this is commented .
```

  <context-param>
        <param-name>AuthenticationRESTEndpointURL</param-name>
        <param-value>https://localhost:9443/api/identity/auth/v1.1/</param-value>
    </context-param>
    
```

Ideally , it should be collected from the identity.server.serviceURL , if the above  web.xml configuration is not enabled.

**Error scenario**

When using the prompt funciton in their adaptive script. In our dynamic_prompt.jsp file it has the below code snippet

```
String authAPIURL = application.getInitParameter(Constants.AUTHENTICATION_REST_ENDPOINT_URL);
    
    if (StringUtils.isBlank(authAPIURL)) {
        authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);
    }
    if (!authAPIURL.endsWith("/")) {
        authAPIURL += "/";
    }
```

According to the above implementation if the authAPIURL is getting from the web.xml file. Which will return null to the authAPIURL as it is commented by default. Due to that reason the authAPIURL will be build with the hostname value which is configuring in the deployment.toml file.

If the identity server deployment fronted by a loadbalancer  and as the  `https://<IS_HOST>/api/identity/auth/v1.1/context/<id>`  API required the MTLS to authenticate with Identity server, this returns 401 response because the request is served through the LB in this scenario and the LB uses SSL termination.

[1]https://is.docs.wso2.com/en/5.10.0/references/adaptive-authentication-js-api-reference/#prompttemplateid-data-eventhandlers

**Comment by dhaura** [comment]
### Note
- Even though this issue was fixed in product-is, after the unification process, all the fixes have been lost. Therefore, all the related places need to be fixed again with the usage of `internal_hostname` when invoking internal API calls in [identity-apps](https://github.com/wso2/identity-apps).
- The git issue which tracked this issue previously - https://github.com/wso2/product-is/issues/11878
