### ISSUE TITLE
[Doc] No explanation for the defaultValue property under claim mappings

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1768]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

No explanation for the defaultValue property under claim mappings
```
<xsd1:claimConfig>
               <!--Optional:-->
               <xsd1:alwaysSendMappedLocalSubjectId>?</xsd1:alwaysSendMappedLocalSubjectId>
               <!--Zero or more repetitions:-->
               <xsd1:claimMappings>
                  <!--Optional:-->
                  <xsd1:defaultValue>?</xsd1:defaultValue>
                  <!--Optional:-->
                  <xsd1:localClaim>
               ....
            </xsd1:claimConfig>
```

https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
