### ISSUE TITLE
Remove Mgt Console URL from startup logs

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#17698]
**Describe the issue:**
Since the old Mgt Console (/carbon) is deprecated in IS 7.0, the following log line should be removed from the startup logs.
```
INFO {org.wso2.carbon.ui.internal.CarbonUIServiceComponent} - Mgt Console URL  : https://localhost:9443/carbon/
```

**How to reproduce:**
Start the IS 7.0 and observe the logs

**Environment information**
 - Product Version: IS 7.0 Alpha

**Comment by ashanthamara** [comment]
Changes are deployed in product-is. Hence closing the issue.
