### ISSUE TITLE
SAML assertion encryption is not working for the sub orgs due to missing registry initialisation for the sub org

### ISSUE THREAD

**Issue by indeewari** [wso2/product-is#17691]
**Describe the issue:**
Core cannot find the private key of the sub organization since the registry is not initialized properly at the time of private key retrieval.

**How to reproduce:**
1. Create a sub organization in the IS
2. Add a standard based SAML authenticator with encryption enabled for the SAML assertion
3. Try to login via the IDP
4. IDP authentication failed since the system cannot find the private key for the sub organization 

NOTE : When the registry is being initialized via retrieving the meta file in the browser, the registry get initialized.
i.e: https://localhost:9443/t/daa61cbb-28ca-4918-89e0-d40a9a205c4e/identity/metadata/saml2

**Expected behavior:**
SAML login should work without any error when the assertion is encrypted.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sadilchamishka** [comment]
Have decided to use the public cert of the root organization. Hence not initialising the sub-org registry to load the decryption keys can be neglected as the root organization's key can be used to decrypt.
