### ISSUE TITLE
Cannot create a role that has Application as the audience

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17696]
**Describe the issue:**

Create a role with Application as the audience of the role. It will be created as a role that has the organization as the audience. This role cannot be assigned to any application that has the role audience as application.

**How to reproduce:**

https://github.com/wso2/product-is/assets/28347418/59241fa4-f9a7-4b24-be4b-789b0e798625

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Fixed in latest Beta-SNAPSHOT.

https://github.com/wso2/product-is/assets/37938529/d3523804-4266-4e10-a132-8277ad0a02d0
