### ISSUE TITLE
Improvements to the Localization Feature

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#17699]
In IS 7.0.0 localization support provides for several languages. Currently we have used complete translatons of each text elements. There were couple of concerns I have observed. 

1. Languages are not consistent among Login portal and myaccount. In login portal it shows a different list rather the list inside the myaccount. Also the flag emojies are different in portuguese language as well.
2. In myaccount application if we choose sinhala as the language, for me personally it becomes hard to understand. IMO some terms are global terms and can not map to a local language directly. So it would provide a better experience if we can have mixed language in certain places user exprience would be better. Check out the image[1]

[1] - 
![image](https://github.com/wso2/product-is/assets/19922157/3140f856-44af-40c5-8821-39c7fcb71739)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
