### ISSUE TITLE
The GitHub Authenticator Settings page is not loading.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17706]
**Describe the issue:**
The GitHub connector settings page is not loading 
<img width="1498" alt="Screenshot 2023-11-09 at 13 59 11" src="https://github.com/wso2/product-is/assets/41188245/4a22c94e-da3d-4702-bbdf-6a6d0e3daefc">

**How to reproduce:**

1. Log in to the console 
2. Download Git connector from [connector store](https://store.wso2.com/store/assets/isconnector/details/bfed96a9-0d79-4770-9c55-22378d3a2812).
3.  Add the relevant configs to the Deployment toml. 
```
[console.ui]
hiddenConnectionTemplates = []
```
4. Create a GitHub connection from Add Connections 
5. Navigate to the settings page.

**Expected behavior:**
Relevant configs should be available. 
<img width="1498" alt="Screenshot 2023-11-09 at 14 46 21" src="https://github.com/wso2/product-is/assets/41188245/7b251773-11ce-4830-a913-6b62aa32d423">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnjanaSamindraPerera** [comment]
The settings page is visible locally.
