### ISSUE TITLE
No Email/OTP Received when Enabling "Send OTP in E-mail" - Self Registration Flow

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17707]
**Describe the issue:**
When enabling the option to "Send OTP in e-mail" ( Enable to send OTP in verification e-mail instead of confirmation code) for verification instead of a confirmation code, users are not receiving any email or OTP. This issue is causing significant problems for users who are unable to log in to the desired application. Furthermore, there is no option available to unlock the user within their profile.

**How to reproduce:**
    Log in to the onsole.
    Go to the User Onboarding > Self Registration  or profile.
    Enable the "Send OTP in e-mail" option for verification.
   Try user self-regulation via myaccount
    Attempt to log back in.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:alpha2 7.0
 - OS: Mac
 - Database: Mysql
 - Userstore: JDBC

**Comment by AnjanaSamindraPerera** [comment]
This is not reproducible as expected. In addition to the above steps, we need to enable User self registration from Self registration.

**Comment by NilukaSripalim** [comment]
> This is not reproducible as expected. In addition to the above steps, we need to enable User self registration from Self registration.

I already enabled self-registration , but didn't get any OTP there

**Comment by AnjanaSamindraPerera** [comment]
Here intention of this feature to enable OTP is to either give an OTP or a confirmation code. If we inspect the confirmation link we can see the difference. 

>Here we get OTP behaviour - SjCCzx (alphanumeric characters)
```
https://localhost:9443/accountrecoveryendpoint/confirmregistration.do?confirmation=SjCCzx&userstoredomain=PRIMARY&username=wqmasb%40mail7.io&tenantdomain=carbon.super&callback=https%3A%2F%2Flocalhost%3A9443%2Fauthenticationendpoint%2Flogin.do%3Fclient_id%3DMY_ACCOUNT%26code_challenge%3Dq2HNRcmhhiWW1DufAhvQGCgy2x4GlHj1LPoKre8aZPc%26code_challenge_method%3DS256%26commonAuthCallerPath%3D%2Foauth2%2Fauthorize%26forceAuth%3Dfalse%26passiveAuth%3Dfalse%26redirect_uri%3Dhttps%3A%2F%2Flocalhost%3A9443%2Fmyaccount%26response_mode%3Dform_post%26response_type%3Dcode%26scope%3Dopenid+openid+SYSTEM%26state%3Drequest_0%26sessionDataKey%3D8e45a6a4-3ef8-4073-ad78-718779e93279%26relyingParty%3DMY_ACCOUNT%26type%3Doidc%26sp%3DMy+Account%26isSaaSApp%3Dfalse%26authenticators%3DOrganizationAuthenticator%3ASSO%3BBasicAuthenticator%3ALOCAL
```

>Here we get confirmation code behavior -  2e3bb3bb-9e9f-4961-977f-e243bf1eebff (basically UUID)
```
https://localhost:9443/accountrecoveryendpoint/confirmregistration.do?confirmation=2e3bb3bb-9e9f-4961-977f-e243bf1eebff&userstoredomain=PRIMARY&username=otpno%40mail7.io&tenantdomain=carbon.super&callback=https%3A%2F%2Flocalhost%3A9443%2Fauthenticationendpoint%2Flogin.do%3Fclient_id%3DMY_ACCOUNT%26code_challenge%3Dq2HNRcmhhiWW1DufAhvQGCgy2x4GlHj1LPoKre8aZPc%26code_challenge_method%3DS256%26commonAuthCallerPath%3D%2Foauth2%2Fauthorize%26forceAuth%3Dfalse%26passiveAuth%3Dfalse%26redirect_uri%3Dhttps%3A%2F%2Flocalhost%3A9443%2Fmyaccount%26response_mode%3Dform_post%26response_type%3Dcode%26scope%3Dopenid+openid+SYSTEM%26state%3Drequest_0%26sessionDataKey%3D8e45a6a4-3ef8-4073-ad78-718779e93279%26relyingParty%3DMY_ACCOUNT%26type%3Doidc%26sp%3DMy+Account%26isSaaSApp%3Dfalse%26authenticators%3DOrganizationAuthenticator%3ASSO%3BBasicAuthenticator%3ALOCAL
```


If this is documented correctly there is no issue in the flow as I see.
