### ISSUE TITLE
Email magic link flow has incorrect UX to the user

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17704]
**Describe the issue:**
Although the email magic link option asks the user to enter an Email, it doesn't work upon providing the email, rather it works over the username.

![image](https://github.com/wso2/product-is/assets/5061791/9f1742d9-9dd4-4f5b-b593-031b341190fb)

The information on the next screen following the magic link is wrong

![image](https://github.com/wso2/product-is/assets/5061791/cb0b7e80-f933-44fa-bc73-279801b8958e)

**How to reproduce:**
Set up email magic link with an application and try it/

**Expected behaviour:**
1 - Should ask for the correct input 
2 - Information should be correct

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
- For the first issue https://github.com/wso2/identity-apps/pull/4618

- The second issue is fixed by now from :
https://github.com/wso2/identity-apps/blame/11035eaca803c210ca41c08dc2e8dd38b1d04841/identity-apps-core/apps/authentication-portal/src/main/webapp/identifierauth.jsp#L249
