### ISSUE TITLE
Directly retrieve displayable authenticators in Connections

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#17703]
**Is your suggestion related to an experience ? Please describe.**
Currently in the Console Connections page the authenticators that are displayed are filtered from the FE after retrieving all the authenticators with `https://localhost:9443/t/carbon.super/api/server/v1/authenticators`. Ideally the backend should not send any authenticators that shouldn't be shown. 

**Describe the improvement**
A new API should be in place to retrieve only the authenticators that should be displayed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
