### ISSUE TITLE
Can't update the protocol details from the /applicaiton PATCH request

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#17713]
**Is your feature request related to a problem? Please describe.**
Currently we are unable to update the protocol details of an application by a `/application` PATCH request. In order to update protocol details, we have to seperately send update requests to each and every protocol endpoints manually. The `/application` endpoint should be able to accept and update the protocol details as well.

**Comment by DilshanSenarath** [comment]
This enhancement addresses the problem of calling both the protocol and application endpoints when updating the protocol section. By resolving this, it will also eliminate the issue of generating two AUDIT logs when updates are made to the protocol section (https://github.com/wso2/product-is/issues/17694).

**Comment by brionmario** [comment]
@sahandilshan I hope this improvement is not going to be done for IS 7?

**Comment by sahandilshan** [comment]
This is not a mandatory improvement, however we need to add this to the project. Therefore adding it the IS-7.0.0 Project dashboard

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
