### ISSUE TITLE
[Migration] Add indexes to shared registry and user db

### ISSUE THREAD

**Issue by kayathiri4** [wso2/product-is#17712]
**Describe the issue**
Related issue: https://github.com/wso2-enterprise/asgardeo-product/issues/15215
Related PR: https://github.com/wso2/carbon-kernel/pull/3539

Following indexes are added:

Table:[REG_RESOURCE_PROPERTY]
Indexed columns:[REG_TENANT_ID], [REG_PROPERTY_ID]

Table:[UM_ROLE_PERMISSION]
Indexed columns:[UM_TENANT_ID], [UM_ROLE_NAME]

Table:[UM_TENANT]
Indexed columns:[UM_ORG_UUID]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
