### ISSUE TITLE
[Migration] Support PAR

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#17714]
**Describe the issue:**
With the PAR feature, the table `IDN_OAUTH_PAR` needs to be added to the identity db.

### Related issues
- Issue https://github.com/wso2-enterprise/iam-engineering/issues/568

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
