### ISSUE TITLE
Custom user store managers are not shown in the IS console

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#17729]
**Describe the issue:**
When a custom user store manager is added, it should be shown as a user store template in the console, so that we can create user stores using that. (This is possible through the management console.)

![image](https://github.com/wso2/product-is/assets/36252940/8e8a6b43-a36c-40a2-9384-177df5d67e24)

**How to reproduce:**

1. Add a custom user store manager [1].
2. Navigate to `User Attributes & Stores` -> `User Stores`.
3. Click `New User Store`.
4. There should be a template for the custom user store manager.

[1] https://is.docs.wso2.com/en/latest/references/extend/write-a-custom-user-store-manager/#try-out-the-sample-user-store-manager

**Comment by Achintha444** [comment]
* Fixed in the latest identity server version, hence closing the issue

<img width="1800" alt="Screenshot 2023-11-15 at 19 01 07" src="https://github.com/wso2/identity-apps/assets/46097917/e12be5cd-ade2-48b8-92ec-f9d3112f2b21">
