### ISSUE TITLE
SCIM2 Roles Patch - Replace operation not working for users and groups

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17733]
**Describe the issue:**
If we invoke a PATCH call for `/t/<tenant_name>/scim2/v2/Roles/<role_id>` or `/t/<tenant_name>/o/scim2/v2/Roles/<role_id>` with replace operations, the response returns 200 OK but the users and groups are not updated.

Eg: The users that are assigned to the role with id `128e2f13-9472-4673-959c-a7fc61aa0d9b` before and after the below call are the same.

```
curl --location --request PATCH 'https://localhost:9443/t/carbon.super/o/scim2/v2/Roles/128e2f13-9472-4673-959c-a7fc61aa0d9b' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>' \
--data '{
    "Operations": [
        {
            "op": "replace",
            "value": {
                "users": []
            }
        }
    ],
     "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ]
}'
```

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
replacing empty list / replacing another set of values doesn't work properly

**Comment by shashimalcse** [comment]
completed with 
- https://github.com/wso2/carbon-identity-framework/pull/5153
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/506
