### ISSUE TITLE
[Doc] Add an image for the authentication with Github to travelocity.com application

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1773]
We need to add images to the last step of 'Testing the sample' section in [1] for login to travelocity with Github as the step for authentication and after the authentication to give a complete picture of the scenario.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Github+Authenticator#ConfiguringGithubAuthenticator-TestingthesampleTestingthesample

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
