### ISSUE TITLE
Update documentation for configure myaccount application

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17739]
**Is your suggestion related to a missing or misleading document? Please describe.**
The Configure My Account Application documentation [1] is not updated for WSO2 IS versions 6.0.0 and 6.1.0. The documentation advises to edit the `deployment.config.json` file is invalid. Editing this file is not correct and will get overridden at server start/ restart. Instead we should edit the `deployment.toml` file as stated in the IS 5.11 docs [2].

[1] https://is.docs.wso2.com/en/6.0.0/references/extend/myaccount/configure-my-account/#configure-my-account-application
[2] https://is.docs.wso2.com/en/latest/references/extend/myaccount/configure-my-account/#configure-my-account-application
[2] https://is.docs.wso2.com/en/5.11.0/develop/configure-my-account/

@divyaamunugama please consider this for the master branch as well

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
