### ISSUE TITLE
Incompleteness in FAPI related features

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17734]
**Describe the issue:**
UX and UI components added related to FAPI need to be revised

**Expected behavior:**

1.  Labels and information are descriptions are not intuitive
  
  example: 
   ![image](https://github.com/wso2/product-is/assets/5061791/f7002afc-215f-4089-8ce0-c914f199b712)

2. Configs and functionalities must be verified against all the application types and should only be onboarded to the respective application templates as applicable. (Ex: Private key JWT client authentication may not make sense for a single page application". Should evaluate all such configurations and fix them in IS.

**Comment by RivinduM** [comment]
As discussed offline the following changes were made.

1. Changed the info messages and added a hint to the pairwise subject identifier.
<img width="709" alt="Screenshot 2023-11-15 at 15 22 44" src="https://github.com/wso2/product-is/assets/25494651/7ca6e6d6-b0ec-4474-bbbd-81d17c5fba68">

2. Configs added for FAPI were restricted only to the Standard based applications
