### ISSUE TITLE
[Doc] Need a sample for local claim and remote claim mapping

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1775]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

Need a sample for local claim and remote claim mapping under "Claim configuration level parameters". The description too lengthy and difficult to understand. 

claimMappings.localClaim.claimUri
claimMappings.remoteClaim.claimUri

https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
