### ISSUE TITLE
Existing TOTP not shown in MyAccount

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#17751]
**Describe the issue:**
If TOTP already configured, it's not shown in myaccount. So, even when a TOTP exists, it shows the UI to create a new. 
While it already exists, clicking on `+` and then `Cancel` removes the existing one.  

https://github.com/wso2/product-is/assets/50905371/d88b4145-b01c-4a2b-862c-6f8ead92f6ac

How to reproduce:

1. Go to the myAccount =>security
2. Go to the Additional Authentication section
3. Configure TOTP
4. Refresh or navigate to a different tab and go back to Additional Authentication section again

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
