### ISSUE TITLE
[Performance] Response Time increases for OIDC Password Grant Type flow when IS nodes increases

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#17757]
**Describe the issue:**

![50_3000_lines](https://github.com/wso2/product-is/assets/59449070/a2141173-db70-4479-82b8-c4e66a631692)

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-ee2c00f7-7fff-4ada-e5d9-c92c30a8cc21"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:3pt;"><span style="font-size:26pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Avg Response Time - Password Grant</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">
Concurrency | 2 Node 4 Core | 3 Node 4 Core | 4 Node 4 Core
-- | -- | -- | --
50 | 113.56 | 141.89 | 164.81
100 | 228.52 | 248.04 | 459.05
150 | 349.63 | 567.26 | 436.15
300 | 744.87 | 1158.39 | 889.59
500 | 1247.53 | 1232.82 | 2459.05
1500 | 2615.83 | 4110.85 | 5165.08
2000 | 4165.24 | 6212.6 | 7993.54
2500 | 5276.4 | 8277.73 | 10365.55
3000 | 6364.41 | 10323.26 | 13201.92
3500 | 7643.88 | 12326.18 | 15826.28

</div><br /></b>

According to the above data, the response time of the OIDC password grant flow increases, when we increase the number of IS nodes.

![image](https://github.com/wso2/product-is/assets/59449070/d877eda9-fe1c-413f-b1af-999cf7d3b744)

But if we perform the test without clustering, the response time won't increases.

<google-sheets-html-origin><style type="text/css"></style>

4 Nodes 4 Core 95th Percentile of Response Time (ms) | 3 Node 4 Core 95th Percentile of Response Time (ms) | 2 Nodes 4 Core 95th Percentile of Response Time (ms)
-- | -- | --
118 | 115 | 188
236 | 225 | 531
353 | 615 | 783
703 | 1407 | 1839
1151 | 2399 | 2975
2303 | 4703 | 5791
3551 | 7647 | 8319
5023 | 10111 | 9791
9407 | 12159 | 13759
6879 | 10111 | 14527

By observing those results we can see that when clustering is disabled we can have a performance improvement. Hence we can expect that the issue should be related to clustering cache invalidation messages. 

Refer the email:

- [IS-5.10.0_performance test] Performance test numbers
- IS product scaling and capacity planning for Horizontal and Vertical scales
- Presenting our performance results in an optimal way to do capacity planning for our customers

For that database side improvement, following slow query was identified,
```sql
SQL=SELECT DISTINCT UM_USER.UM_USER_ID FROM UM_USER, UM_USER_ATTRIBUTE WHERE UM_USER_ATTRIBUTE.UM_USER_ID = UM_USER.UM_ID AND UM_USER_ATTRIBUTE.UM_ATTR_NAME =? AND UM_USER_ATTRIBUTE.UM_ATTR_VALUE =? AND UM_USER_ATTRIBUTE.UM_PROFILE_ID=? AND UM_USER_ATTRIBUTE.UM_TENANT_ID=? AND UM_USER.UM_TENANT_ID=?; time=156 ms;
```

**How to reproduce:**

Execute performant test for the OIDC password grant flow with requesting user attributes. Obtain an access token and an id token using the OAuth 2.0 password grant type. Retrieve country, email, first name and last name as user attributes.

deployment.toml configurations

```toml
[database.identity_db.pool_options]
maxActive = "500"

[database.shared_db.pool_options]
maxActive = "500"

[database.user.pool_options]
maxActive = "500"

[transport.https.properties]
maxThreads = "500"
acceptCount = "500"
```

**Expected behavior:**

> When we increase the number of IS nodes, the response time should decrease. Unless there is no RDS bottleneck.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-6.1.0, IS-7.0.0. M3
 - OS: Linux
 - Database: MySQL
 - Userstore: JDBC

**Related issues:**
> * https://github.com/wso2/product-is/issues/15460

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
