### ISSUE TITLE
Application audienced role creation will result in creating organization audienced role

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17759]
**Describe the issue:**
1. Create an application. 
2. Go to the roles tab of that application, and change the audience of the role as application.
3. Go to the roles section under User Management.
4. Try to create a role with the application audience, selecting the application created in step 1
5. The role will add as an organization audience role

https://github.com/wso2/product-is/assets/25483865/7cb2cf04-d71d-4fd7-a09f-5959d4d90471

The following API call was made to create the role. Audience data is missing here. That's the root cause.
```
curl 'https://localhost:9443/t/carbon.super/scim2/v2/Roles' \
  -H 'Access-Control-Allow-Origin: https://localhost:9443/t/carbon.super/console' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer;' \
  -H 'Authorization: Bearer f639a04c-e87e-391b-9a0e-fab09d708bb4' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw '{"displayName":"Advisor","permissions":[],"schemas":[]}' \
  --compressed \
  --insecure
```

Reproducible in 7.0.0-Beta-SNAPSHOT built on 13/11/2023 around 2.00 pm IST

**Comment by JayaShakthi97** [comment]
- Duplicated https://github.com/wso2/product-is/issues/17696
