### ISSUE TITLE
SAML application does not have the Roles sections as in OIDC applications

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#17756]
**Describe the issue:**
The roles section should be available for the SAML applications. Both role types should be available for the SAML applications as well.
We **do not** need API Authorization section.

**How to reproduce:**
Create a SAML application and go to edit view. Roles section not available.

**Comment by Achintha444** [comment]
* Fixed in the latest identity-server, hence closing the issue
<img width="1799" alt="Screenshot 2023-11-14 at 15 33 18" src="https://github.com/wso2/identity-apps/assets/46097917/731e6492-e4c6-48e7-b3aa-b0e77a8d0661">
