### ISSUE TITLE
Self registration link is not shown in the login ui for business apps even when the self registration is enabled.

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17750]
**Describe the issue:**

$subject

**How to reproduce:**

1. Sign into console and create application.
2. Enable self registration in **Login and Registration** page.
3. Configure the application and run.
4. Observe that the self signup link is not visible in the sign in page.

**Expected behavior:**

Self signup link should be displayed for business apps when self registration is enabled.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
This is not reproducible in latest build from source.
### Super Tenant Console
<img width="1512" alt="Screenshot 2023-11-14 at 10 08 03" src="https://github.com/wso2/product-is/assets/74205483/f049dfc1-cd3d-4a37-a1bf-67a3bff4cba9">

### Business App
<img width="1512" alt="Screenshot 2023-11-14 at 10 07 51" src="https://github.com/wso2/product-is/assets/74205483/195ea657-e75e-4b28-b0f9-7f8129d1d7d4">
