### ISSUE TITLE
Enable `testOAuthApplicationLoginWhenTenantQualifiedUrlsDisabled` integration test

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17762]
**Describe the issue:**

With the https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2242, a startup validation will be added to check for the compatibility with client ID tenant unification. However a test added with the original feature requires running the server by disabling tenant qualified URLs and tenanted sessions. With the new change, a DB scheme change is required to start the server in that mode and it requires a test improvement.

This task is created to track the improvement to re-enable the disabled test in https://github.com/wso2/product-is/pull/17760

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
