### ISSUE TITLE
Unnecessary user local search during federated authentication flow

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#17767]
**Describe the issue:**
When the authentication step is set as follows,
- Step 1: Identifier First
- Step 2: Federated IDP

the IS tries to find the user in the local userstore as follows when the session is persisted after the successful authentication. This happens since all the authenticated IDPs are iterated and this gets executed when the session data of the identifier first is persisted, as it is considered LOCAL.
```
// If the user is federated, generate a unique ID for the user and add an entry to the IDN_AUTH_USER
// table with the tenant id of the idp and user store domain as FEDERATED.
if (LOCAL_IDP_NAME.equals(idpName)) {
    userId = FrameworkUtils.resolveUserIdFromUsername(tenantId, userStoreDomain, userName);
} else {
```
However, this should only be executed, if the user is provisioned and if `isAlwaysSendMappedLocalSubjectId()` is true for federated scenarios.

**How to reproduce:**
Configure the authentication steps as above and observe the method invocations.

**Expected behavior:**
 If JIT provisioning and "Assert identity using mapped local subject identifier" are not enabled, the user should not be searched in the local userstore.

**Environment information**
 - Product Version: IS 5.10.0

**Related issues:**
#12971, #12169

**Comment by ShanChathusanda93** [comment]
> Fix which was added to `storeSessionData` function in the `concludeFlow`, to stop the local search in the identifier first step when it has federated authentication in the second step. This is not reproducible in the master branch if [skipIdentifierPreProcess](https://is.docs.wso2.com/en/next/guides/authentication/add-identifier-first-login/#customize-the-authentication-flow) configuration is set to true in `conditional authentication script`.

As per this comment this was fixed in service provider level. However it is better if we can provide the fix for server level as well. Reopening to track the public issue.

**Comment by Sachin-Mamoru** [comment]
Introduced a server level configuration from https://github.com/wso2/carbon-identity-framework/pull/5373
