### ISSUE TITLE
Remove All user stores filter option in resource listing pages

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#17761]
**Is your suggestion related to an experience ? Please describe.**
We need to remove the All user stores filter option in Users and Groups feature listing pages. 

<img width="1727" alt="image" src="https://github.com/wso2/product-is/assets/30111554/80b2eaff-e33c-47b0-92d8-41bab95f3fe5">

**Comment by pavinduLakshan** [comment]
Verified in the latest beta snapshot build.

<img width="1503" alt="Screenshot 2023-11-20 at 03 27 02" src="https://github.com/wso2/product-is/assets/41533942/e0059aef-ef3c-47d7-aeb9-6367d128955e">
