### ISSUE TITLE
Improvement on the inviting parent organization API

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#17779]
**Is your suggestion related to an experience ? Please describe.**
The [inviting parent organization API](https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.server.organization.user.invitation.management/org.wso2.carbon.identity.api.server.organization.user.invitation.management.v1/src/main/resources/organization-user-invitation.yaml) resource doesn't have an endpoint to retrieve the invitation by its invitation id. Only list all the invitation API is available.
<img width="1618" alt="Screenshot 2023-11-14 at 1 34 56 PM" src="https://github.com/wso2/product-is/assets/13362482/bff6ce7e-b2b0-4a59-aed7-f6e5bfac4f79">

**Describe the improvement**

- When introducing front end improvement with role assignements when inviting a user from the parent organization, this API may required, hence better to include the API to retrieve the invitation by its id.
- And with the support of [RoleV2](https://github.com/wso2/product-is/issues/17522) in role assignments in parent user invite flow, change the model to provide the role details with its audience details. As of now the the list all the user invitations will provide the response as follow and this may be improved to list the role with the reference location to the `/guests/invitations/{invitationId}`
```
{
    "invitations": [
        {
            "id": "51310724-b33c-4b8c-a805-41580765a9d2",
            "username": "alex",
            "email": "xxxx@gmail.com",
            "roles": [
                {
                    "displayName": "testrole",
                    "id": "d3ffa7cf-a4d9-4dc7-b0a1-cdd2c6a6ab84",
                    "audience": [
                        {
                            "value": "c139b9ef-79a4-4402-af1c-27406aeab5ff",
                            "display": "app2",
                            "type": "application"
                        }
                    ]
                }
            ],
            "status": "PENDING",
            "expiredAt": "2023-11-16 09:37:36.0"
        },
        {
            "id": "5f32d028-8c5d-451d-8dec-0b2d29fabf1f",
            "username": "bob",
            "email": "yyyyy@gmail.com",
            "roles": [
                {
                    "displayName": "testrole",
                    "id": "d3ffa7cf-a4d9-4dc7-b0a1-cdd2c6a6ab84",
                    "audience": [
                        {
                            "value": "c139b9ef-79a4-4402-af1c-27406aeab5ff",
                            "display": "app2",
                            "type": "application"
                        }
                    ]
                }
            ],
            "status": "PENDING",
            "expiredAt": "2023-11-17 05:20:26.0"
        }
    ]
}
```

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
