### ISSUE TITLE
The commonauthId cookie is incorrectly creating under "/" and not in "t/carbon.super" which is resulting in providing tenant admin session for consumer logins

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17784]
**Describe the issue:**
When the tenant admin session is available and the business user sample application is accessed, the tenant admin session is accessed. 

**How to reproduce:**
1. Login to IS Console as a tenant admin
2. Create an application, user and a configured sample application
3. Login to Sample application from another tab
4. Verify the session accessed

**Expected behavior:**
The business user session should be provided and tenant admin session should not be accessed in this scenario

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thisara-Welmilla** [comment]
Temporary fixed with the https://github.com/wso2/carbon-identity-framework/pull/5169. 

Will provide a proper solution for this.
