### ISSUE TITLE
[Chaos] DB connection loss resulted in displaying multi-login option page

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1778]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
OS - Ubuntu-14.04-LTS
Browser Chrome 58.0.3029.96

**Steps to reproduce the issue**
1.Create Facebook and Google as IDP
2. Create SP and add two IDPs and Resident IDP for outbound authentication
3. Configure fidp in travelocity with the Home Realm identifier of Resident IDP (ex: localhost)
4. Sign in to travelocity 
5. Stop the DB connection
6. Enter valid username and password to authenticate with resident IDP and click sign in button
7. Restart the DB connection

**Observations**
All the configured IDPs appeared with the authentication failure due to connection issue

![screenshot from 2017-12-19 23-19-13](https://user-images.githubusercontent.com/14962228/34172552-734ab550-e518-11e7-8c2d-47016d72b5c6.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
