### ISSUE TITLE
Unable to update boolean attribute through Console

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#17799]
**Describe the issue:**
Unable to update boolean attribute through Console

**How to reproduce:**
1. Create a custom attribute
2. Add additional property ("dataType" : "boolean")
3. Make it avail in user profile
4. Try updating the attribute. It will not be updated

**Expected behavior:**
Should be able to update.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
As per the discussion had with @VivekVinushanth , this feature is only available through API and therefore the chance of end users encountering this bug through UI is slim. Therefore reducing the severity.

**Comment by VivekVinushanth** [comment]
And IMO data type should be a first class property. This has been a concern when user tries to signup with a boolean value (though we changed the attribute type to boolean through API) , the signup still prompts with a text box. 

1. When registering an attribute type should be considered and signup/ profile pages should reflect this
2. For all the text value, we still provide a text box but there can be a necessity to get input from a dropdown which we dont support.

**Comment by VivekVinushanth** [comment]
This has been a concern for few prospects and customers to be frank

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
