### ISSUE TITLE
PassiveSTS template doesn't send the inbound auth configuration details when creating the applicaiton

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#17793]
**Describe the issue:**
When we try to create a PassiveSTS app from the console, it doesn't create the inbound auth protocol details in the backend. The root cause for this issue could be due to the request that is sending from the console app doesn't have any inbound auth information in the request payload. 

**How to reproduce:**
1.  Login to the console
2. Naviaget to the `Applicaiton` section
3. Select Standard based applicaiton template
4. Select PassiveSTS
5. Create the applicaiton 
6. Once the applicaiton is created, navigate to the protocol section. There will be no information available in there

The below screenshot is the payload of the application and it doen't contain the inbound auth config data
<img width="453" alt="Screenshot 2023-11-15 at 11 04 27 AM" src="https://github.com/wso2/product-is/assets/32576163/0a50e431-b934-4e1d-83b5-c75429ddce83">

**Expected behavior:**
Before creating the applction, the PassiveSTS should be ask the protocol information from the user and then send those information in the request.

**Comment by NipuniBhagya** [comment]
We also need to change the template name from `PassiveSTS` --> `WS-Federation`
