### ISSUE TITLE
PassiveSTS information is missing in the documentation

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#17794]
**Is your suggestion related to a missing or misleading document? Please describe.**

- The latest documentation doesn't have the passiveSTS instructions. We need to properly document those once we fix https://github.com/wso2/product-is/issues/17793 issue

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
