### ISSUE TITLE
Google as Service Provider - Given admin credentials in the Basic Auth, redirects to a specific admin gmail account

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1779]
**Steps to re-create**
Make sure Google domain, wso2support.com, is SSO enabled and configuration done. 

1. Create a user in the domain - wso2support.com (jane123@wso2support.com)
2. Configure Google as the SP and use Basic Authentication. 
3. Navigate to mail.google.com
4. In the Gmail screen, provide the email address you created. (jane123@wso2support.com)
5. Now user would be navigated to Basic Auth. 
6. Provide admin/admin as the credentials. 

**Expected:** It should result an error. 
**Actual**: User is navigated to an admin email account which owns under a specific name. 

Please refer the email 'Google as Service Provider - Given admin credentials in the Basic Auth, redirects to a specific admin gmail account'

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
