### ISSUE TITLE
Channels Page header containtns " Email Providers"  Config  for Super Admin User as well

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17805]
**Describe the issue:**
The Email Provider configuration option is currently not visible for super admin users. Despite the page header stating "SMS / Email Providers: Configure the SMS and Email providers for your organization," only SMS configurations are visible for super admin users.

**How to reproduce:**
1. Login to console
2. Click on "Channel" in Left side panel

<img width="1570" alt="Screenshot 2023-11-15 at 14 35 52" src="https://github.com/wso2/product-is/assets/39120228/44333eb4-3432-4d3b-a703-98383bf4fc84">

**Comment by Achintha444** [comment]
### Related Issues
- https://github.com/wso2/product-is/issues/17488#issuecomment-1792006356

**Comment by brionmario** [comment]
We need to handle the side nav as well. @Achintha444 

<img width="1373" alt="Screenshot 2023-11-24 at 11 09 25" src="https://github.com/wso2/product-is/assets/25959096/21541873-e0e8-4915-be46-6988f9868b61">

**Comment by madurangasiriwardena** [comment]
I think the agreement is to provide an info card in the page to instruct the users on how to configure the Email provide configs.

**Comment by NipuniBhagya** [comment]
We also need to update card styling to be consistent with the other sections.

<img width="402" alt="image" src="https://github.com/wso2/product-is/assets/30111554/2e08b019-266d-40cb-8069-639ad6f405e6">

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/18146

**Comment by pavinduLakshan** [comment]
> Based on a discussion with @malithie, we need to add a card for `Email OTP` and show that it should be configured via `deployment.toml`.
> 
> <img alt="Screenshot 2023-11-24 at 11 09 25" width="1373" src="https://private-user-images.githubusercontent.com/25959096/285368786-21541873-e0e8-4915-be46-6988f9868b61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjYwNDEsIm5iZiI6MTcwMTY2NTc0MSwicGF0aCI6Ii8yNTk1OTA5Ni8yODUzNjg3ODYtMjE1NDE4NzMtZTBlOC00OTE1LWJlNDYtNjk4OGY5ODY4YjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA0NTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OTA2YmU3NGRmM2Y1OTFmYzMwMzIzNmY4ZTc3MTkzNzMyYWM3MjFjZmMxNGY2M2JlZGI5Y2IzYTVlMmM1OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AC0aFCyplrUfmHifjAYEYdHzjfuu5MM0L4nfQL6aQK8">

Verified the fix in the latest build.

https://github.com/wso2/product-is/assets/41533942/cba62f5a-c543-4262-994b-961c27cd6588
