### ISSUE TITLE
[Doc ] Login permission for Dashboard

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1780]
**Improvement**
**Environment**
IS 5.4.0
In order to log-into dashboard  for newly created users, they need login permission .
Default **Internal everyone** role is assign to users when creating users. But this role doesn't content any permission. Therefore newly created user cannot login to dashboard. 
So,iIn the docs mentioned that users need to create a septate role with **Login** permission and assign that role to users to login to Dashboard.

[1] https://docs.wso2.com/display/IS540/Using+the+End+User+Dashboard

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
