### ISSUE TITLE
Something went wrong when navigate back to the parent organisation 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#17806]
**Describe the issue:**
Something went wrong when navigate back to the parent organisation from sub organization application view. 

https://github.com/wso2/product-is/assets/39077751/46e9720d-c71b-4e6e-9a43-8ae7566b14d9

**How to reproduce:**
1. Login to console
2. Create a sub organization
3. Switch to sub organization
4. Navigate to application page
5. Navigate back to the parent organization.

**Expected behavior:**
No error should be available. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
This is fixed in 
- https://github.com/wso2/identity-apps/pull/4664
