### ISSUE TITLE
Make short and meaningful button name  

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#17803]
**Is your suggestion related to an experience ? Please describe.**
Button name is long 
<img width="1190" alt="Screenshot 2023-11-15 at 12 42 33" src="https://github.com/wso2/product-is/assets/39077751/7adde8d5-442e-4dde-8164-a71f3dedfe10">

**Describe the improvement**
Make short and meaningful button name  

**Additional context**

**Comment by GoushiRam** [comment]
As "Restore Default Configs for Audit Logs" is available in the component, a one word meaningful name should be ideal here

**Comment by DonOmalVindula** [comment]
Will be fixed with https://github.com/wso2/identity-apps/pull/4600
