### ISSUE TITLE
[SMS OTP Provider] UI gives the perspective of able to configure more than 1 custom sms otp provider

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17812]
**Describe the issue:**
There are few issues in "SMS OTP Provider" that give the  experience that the user is capable of adding more than 1 SMS OTP Providers

1. The UI provides the tab navigation which seems that we provide multiple SMS OTP configurations

<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/a814185b-8c18-471f-86e3-ec9246da348a">

2. The Delete section is separate from the SMS OTP Configuration components. Further the deletion context is in plural providing the effect that multiple SMS OTP configurations can be configured and deleted. 

<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/74c1a952-4a00-4469-b34f-86b0a821e322">

**How to reproduce:**
1. Login to IS Console
2. Navigate to Branding > Channels and navigate within SMS OTP Configurations

**Expected behavior:**
The SMS OTP behaviour should provide the experience only one type of configuration is allowed at a given time. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
If the button groups are not intuitive enough, we can implement a radio card component and see if that sticks.
Anyway, we shouldn't go with the traditional radio groups since the logos of Twillio and Vonage will be onboarded later.

<img width="890" alt="Screenshot 2023-11-19 at 10 44 44" src="https://github.com/wso2/product-is/assets/25959096/4703f596-cd87-4465-8003-30cb0dbd76ed">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
