### ISSUE TITLE
Rename `username` parameter used in the API based authentication payloads to a more general lable ex:`login-identifier`

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17819]
**Is your suggestion related to an experience ? Please describe.**
Suggestion to rename the login identifier `username` in the API-based authentication API to be aligned with future enhancement 

**Describe the improvement**
- Eventually, we would need to support different identifiers as the login identifier (email, mobile, NIC)
- Instead of hardcoding the parameter to `username` shall we rename it to something like `login-identifier`
 - And introduce an optional parameter `login-identifier-hint` so that the request can specify what exact attribute the login identifier should resolve (Username, email, mobile, etc). If not defined the a default resolution can be done.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
