### ISSUE TITLE
Incorrect option `Continue with SSO` in the Self signup flow

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17813]
**Describe the issue:**
Check the video below

https://github.com/wso2/product-is/assets/5061791/d6de2c52-9535-4c9c-8a03-23832a2c636c

**How to reproduce:**

1.  Enable self registration
2. Access the login page and try `Create an Account`
3. There is an option with `Continue with SSO` which results in a dead end  
      
![image](https://github.com/wso2/product-is/assets/5061791/def25c58-9ddc-423a-a4ea-bbdcd9ce0c7b)

**Expected behavior:**
` Continue with SSO` option shouldn't be there.

Note: Only the options applicable to provision should be there, given they are login options in the app (Google, Facebook)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
Any idp configured will come here (not only b2b)

**Comment by indeewari** [comment]
@dewniMW IMO Having any IDP here is not an issue as long as those IDPs are JIT provisioning enabled. @ayshsandu WDYT ?

I am suggesting the fix as filtering the JIT enabled authenticators only.

**Comment by indeewari** [comment]
Since there is a counter argument on the method on provisioning, this was decided to remove the SSO option only.
