### ISSUE TITLE
Delete linked user account is not working 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#17815]
**Describe the issue:**
Delete linked user account is not working.

<img width="1427" alt="image" src="https://github.com/wso2/product-is/assets/39077751/8f588a5f-29e8-4089-811a-80103c5598a3">

**How to reproduce:**
1. Login to console
2. Create 2 users (user1 and user2)
3. Login to the my account with user1
4. Navigate to porfile section
5. Select user2 and linked account and update. 
6. Delete the linked account

**Expected behavior:**
User linking should be delete. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashanthamara** [comment]
Issue is not reproducing
Console Version `2.6.6`
MyAccount Version `2.2.16`

https://github.com/wso2/product-is/assets/75057725/732a2f72-592d-4662-a266-a6e6e37f3a01
