### ISSUE TITLE
Include a sample for admin service invocation using a tool

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1782]
In the admin service doc [1] "Invoking an admin service" section contains to use with the JAVA client program.

However, it would be better if we can provide a simplest solution for the user to easily try out the admin service invocation using a tool like SOAP UI. Authentications can also be verified easily with SOAP UI

[1] https://docs.wso2.com/display/IS540/Calling+Admin+Services

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
