### ISSUE TITLE
Inconsistency in the response payload authenticators in API based authentication

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17822]
**Describe the issue:**
Consider when the authentication step has username/password and email OTP as login options. In the init call response
- Username & password have meta-information required for the next step
- But Email OTP doesn’t have the meta information 

<img width="905" alt="Screenshot 2023-11-17 at 11 10 40 AM" src="https://github.com/wso2/product-is/assets/5061791/faad4bd9-b3b3-49e0-818e-deaaaa5763ef">

- This inconsistency makes it harder for developers to implement respective UIs. Generating dynamic UIs is even harder.
- Or may end up in making additional API calls or the UI rendering has to have context aware logic to check for specific values when rendering the UI for different authenticators

**How to reproduce:**

1. Setup an app with sign-in options username/password and email OTP as 1st step
2. Try API based auth 

**Expected behavior:**
Payloads should be consistent.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-local-auth-emailotp/pull/24

**Comment by DMHP** [comment]
Added the i18n key as the metadata. But with the current architecture of the framework we can not send input meta-da of all the authenticators other than the basic and identifier-first when using MFA. That information should captured in the documentations. @janakamarasena Please consider this when writing the documentations.

**Comment by janakamarasena** [comment]
Lowering the severity as this is a limitation of the current framework as mentioned in https://github.com/wso2/product-is/issues/17822#issuecomment-1842026598

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
