### ISSUE TITLE
[Application Roles] : After deletion, role is not removed from an application

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17824]
**Describe the issue:**
After deleting an application role from the "Roles" page, the role is not removed from the application. 

https://drive.google.com/file/d/1M0ssJwGj4RaMpviH_BJUJhlcEOXt1_Mx/view?usp=sharing

**How to reproduce:**
1. Login to IS Console
2. Navigate to "Roles" page
3. Create an application role and assign it to a relevant application 
4. Delete the above role from the "Roles" page
5. Navigate to the application and verify the roles connection

**Expected behavior:**
Once deleted, role should be removed from the application successfully

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by somindatommy** [comment]
Tried with the latest master of product-is (8:40am 2023-11-18) and unable to reproduce this

**Comment by somindatommy** [comment]
https://github.com/wso2/product-is/assets/39567992/39ba140e-7d05-4312-9e5d-2e5eb3c45905

**Comment by somindatommy** [comment]
@GoushiRam can you verify whether the tried flow is correct?

**Comment by GoushiRam** [comment]
> @GoushiRam can you verify whether the tried flow is correct?

Previous pack where this was verified is having this issue. The latest pack verified with "#4931" this issue is not reproducible. Hence closing this issue

cc: @somindatommy @NilukaSripalim
