### ISSUE TITLE
Ensure Consistent Design for Field hints.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17828]
**Describe the issue:**
The pop-up messages should be replaced with the new tooltip design.

<img width="1502" alt="Screenshot 2023-11-15 at 17 39 09" src="https://github.com/wso2/product-is/assets/41188245/527c4d9b-155f-4b65-8c6b-d52358c7e8ab">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
