### ISSUE TITLE
[Application Roles] : Selected API Resource's scopes are not populating

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17826]
**Describe the issue:**
Under an Application, when trying to create an Application Role, the selected API Resource's scopes are not populating

https://drive.google.com/file/d/1QMpdmKwZ3w97H0knyc2PGfNczJfx3ors/view?usp=sharing

**How to reproduce:**
1. Navigate to a created application
2. Configure an API Resource
3. Navigate to the Roles Tab under the Application
4. Create an Application
5. Select the API Resource
6. Verify whether its permissions are populated

**Expected behavior:**
The scopes should be populated correctly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by somindatommy** [comment]
Seems like the UI is not populated properly
![Screenshot 2023-11-17 at 22 37 26](https://github.com/wso2/product-is/assets/39567992/245c7dc3-b92d-4d04-9264-c074fae2c2c5)

**Comment by somindatommy** [comment]
There seems to be a UI issue here.
