### ISSUE TITLE
Improve how the required fields related to a user prompt are indicated in the API based authentication responses 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17821]
**Is your suggestion related to an experience? Please describe.**
Why aren’t the required status of the parameters presented in line with the param (similar to `confidential`)? It helps render mandatory parameters in the user prompt easily. 

<img width="465" alt="Screenshot 2023-11-15 at 8 54 53 PM" src="https://github.com/wso2/product-is/assets/5061791/35b59123-696e-4eeb-a405-8e2776564b8c">

**Describe the improvement**
Add an inline field to the parameter to indicate whether it's required or optional.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
