### ISSUE TITLE
[Application Roles] - Revisit the section to provide more User Experience of "Organization", "Application"

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17820]
**Describe the Issue:**
When using the section where Application Roles are defined, there are several issues that needs to be addressed to cater proper user experience. 

1. There is no segregation between Application and Organization User Audience
<img width="1512" alt="image" src="https://github.com/wso2-enterprise/asgardeo-product/assets/106053688/97bf5620-505a-47d0-9026-d57285ade446">

- The Create Roles doesn't have to be displayed when Organization is selected
- The "Roles Assigned" section seems common for both Application and Organization audience
                                       
2. Unnecessary "Removed Roles" component. User is able to view the Removed Roles from the multi drop down, clicking on the "Assigned Roles" section

<img width="928" alt="image" src="https://github.com/wso2-enterprise/asgardeo-product/assets/106053688/510bffeb-ef06-4e10-915a-594f8d825764">

3.  No point of Adding an API Resource without selecting a scope, which makes the "X" button and addition both redundant
4. Further the Role UI becomes crowded once an API Resource is added

<img width="1512" alt="image" src="https://github.com/wso2-enterprise/asgardeo-product/assets/106053688/34a4e35c-7153-4b01-a863-703485bba43a">

5. When a user access this page, we need provide certain help to understand and navigate through this section. Proper doc links and tooltips should be available to enhance the user process

- For an application role, to add API Resources we need to add an “API Authorisation”. This is not indicated in the UI

6. The UI of the Application Role creation adds the Application Resource as a component, giving the idea that multiple such resources can be added. This is not the case. 

**How To Reproduce:**
Explained above

**Expected behavior:**
Explained above

**Device Information:**
 - Device (e.g. PC, iPhone6):
 - OS (OSX, Android, iOS):
 - Browser + Version:

---

### Optional Fields

**Related Issues:**

**Suggested Labels (for non-committers):**

**Suggested Assignees (for non-committers):**

---
### Testing Related Fields

**Local e2e Tests Status (Please attach the screenshots of the result):**

**Manual Test Plan (Please attach the document link):**

**Manual Test Plan Reviewed by:**

**Comment by JayaShakthi97** [comment]
- Following points were addressed with: https://github.com/wso2/identity-apps/pull/4755
  - [ ] Hide "Create Role" button for Application Role audience.
  - [ ] Avoid navigating to Role edit page once a role is created.

**Comment by JayaShakthi97** [comment]
Pending items:
- [ ] Unnecessary "Removed Roles" component. User is able to view the Removed Roles from the multi drop down, clicking on the "Assigned Roles" section.
- [ ] No point of Adding an API Resource without selecting a scope, which makes the "X" button and addition both redundant.
- [ ] When a user access this page, we need provide certain help to understand and navigate through this section. Proper doc links and tooltips should be available to enhance the user process.
    - For an application role, to add API Resources we need to add an “API Authorisation”. This is not indicated in the UI
- [ ] The UI of the Application Role creation adds the Application Resource as a component, giving the idea that multiple such resources can be added. This is not the case.
    - This was a bug and addressed through: https://github.com/wso2/product-is/issues/18084

**Comment by JayaShakthi97** [comment]
- Added hint when the API resources are not setup for the application.
![Screenshot 2023-11-29 at 4 12 06 PM](https://github.com/wso2/product-is/assets/37938529/b8990f6b-059c-4cf6-abc5-30b6f45a32d9)

- Blocked submission with empty scopes filed.
![Screenshot 2023-11-29 at 4 13 01 PM](https://github.com/wso2/product-is/assets/37938529/36a83b51-d45a-4b69-9b22-b181fd887374)
