### ISSUE TITLE
[Common] Tab navigation should be consistent within the modals

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17830]
**Describe the issue:**
There should be a consistency when a page is navigated via tab. It should be "left to right" and "top to bottom". In some pages, this is not properly followed.

1. Add User - the tab gets lost after Username
2. Create Groups > Role Assignment page

**How to reproduce:**
1. Navigate to the above mentioned pages
2. Try to enter details by navigating through tabs
3. Verify the tab navigation

**Expected behavior:**
There should be a consistency when a page is navigated via tab. It should be "left to right" and "top to bottom". 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
