### ISSUE TITLE
Revise the text on the OOB provided adaptive auth templates

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17837]
**Is your suggestion related to an experience ? Please describe.**

Some UI labels in the grouping and headings of OOB provided adaptive auth templates are not meaningful

![image](https://github.com/wso2/product-is/assets/5061791/9755c015-da49-466c-9999-850172d0d687)

**Describe the improvement**
Revisit the texts and fix them

**Additional context**

**Comment by ZiyamSanthosh** [comment]
According to the offline chat with @jeradrutnam, We have regrouped the templates as mentioned below.

**Adaptive MFA**
- IP Based
- New Device Based
- Group Based
- ACR Based
- Role Based
- User-Store Based
- Tenant Based
- Login Attempts Based
- ELK Risk Based
- [Deprecated] Risk Based

**Access Control**
- Session Based
- User Age Based

**Attributes**
- Update User Role

@ayshsandu Can we have a +1 on this?

**Comment by ZiyamSanthosh** [comment]
This is completed. Hence, closing the issue.
