### ISSUE TITLE
Add a consistent `flowStatus` to the response once the authentication flow is completed

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17835]
**Is your suggestion related to an experience ? Please describe.**
The API response has no consistent attribute to identify the intermediate authentication steps(INCOMPLETE) and authentication complete status. 

Incomplete

<img width="1025" alt="Screenshot 2023-11-16 at 10 54 29 AM" src="https://github.com/wso2/product-is/assets/5061791/cc79f7be-2022-4048-938d-f7e58a591a04">

complete
<img width="1046" alt="Screenshot 2023-11-16 at 10 53 52 AM" src="https://github.com/wso2/product-is/assets/5061791/8fa44dbf-cf77-4489-bfd0-58d6b13539e6">

**Describe the improvement**
Keep the API responses consistent to indicate the status of the authentication flow.

**Additional context**
It will improve the developer experience and remove unwanted complexities while dealing with the API.

**Comment by janakamarasena** [comment]
Lowering the severity of this issue as the current API response was a design decision. The idea was the the api based auth will start and end with OAuth flow. And to aling with that the current final response is an OAuth response. 
I agree with the mentioned improvement as it will be easier to process for an implementer. Theresfore will proceed with fixing this.
