### ISSUE TITLE
User creation wizard UI Username filed position is interrupting user experience. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#17831]
**Describe the issue:**
User creation wizard UI Username filed position is interrupting user experience. Better it list down on below the user store field since it is amandatory, unique and primary information for user createion. 

<img width="764" alt="image" src="https://github.com/wso2/product-is/assets/39077751/0b6c6bd1-cab8-4db1-a273-c20b156eb9fa">

**Comment by Achintha444** [comment]
This is better to track as an improvement, rather than a bug. Hence adding the `improvement` label.

**Comment by jeradrutnam** [comment]
This will be fixed when unfing the UIs with Asgardeo. cc: @DonOmalVindula
