### ISSUE TITLE
Ask password option: The configuration in identity.xml should be changed

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1783]
In [1] in the first step it asks to change the <AskPassword> expiry time option. Following should be corrected

1. The parent of the entire identity.xml is the <Server> hence telling <AskPassword> is under that does not help a user to find it quickly, rather the immediate parent of the <AskPassword> option should be given.
2. In default identity.xml the config that contains the <AskPassword> is by default disabled and there are other configs within this segment. Hence clearly mention what to enable and what to disable to get this working

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
