### ISSUE TITLE
[Groups]/[Roles]: Page is crashing on clicking "View Permission"

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17836]
**Describe the issue:**
When trying to View the Permissions of a role that has assigned permissions from the "Create User" and "Create Groups" page, the page is crashing.

https://drive.google.com/file/d/1R7PCdqpHOjTCeNpB7_oqmneN5wJ_ons-/view?usp=sharing

**How to reproduce:**
1. Navigate to Users/Groups page
2. Click on Create Users/Create Groups
3. Enter the details and navigate to Roles assignment
4. Click on "View Permissions"
5. Verify the behaviour

**Expected behavior:**
The permissions should be populated correctly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
### Related Issues: 
https://github.com/wso2/product-is/issues/17647
https://github.com/wso2/product-is/issues/17649

**Comment by dasuni-30** [comment]
Discussed about hiding the `View Permissions` button from user creation and groups creation wizards until https://github.com/wso2/product-is/issues/17859 task is completed. cc: @AnuradhaSK @Achintha444
