### ISSUE TITLE
New configuration for oauth code persistence

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-is#17834]
**Describe the issue:**
There is a non-templated config in identity.xml prior IS 7.0.0 as follows for both token and auth code non persistence.

```
        <TokenPersistence>
            <Enable>true</Enable>
```

With PR https://github.com/wso2/carbon-identity-framework/pull/5073 and https://github.com/wso2/carbon-identity-framework/pull/5162/files,

the above config is templated and used for token non persistence only (https://github.com/wso2/api-manager/issues/1664). To explicitly handle auth code persistence, we have introduced new config in identity.xml with https://github.com/wso2/carbon-identity-framework/pull/5162. This is is hardcoded to true.

```
        <!--
            Config related to OAuth2 authorization code persistence.
            Prior to IS 7.0.0, this was handled by the config <TokenPersistence>.<Enable>.
       -->
        <EnableAuthCodePersistence>true</EnableAuthCodePersistence>
```
If a user migrating from a version prior to IS 5.7 (with no j2 templates), and using the TokenPersistence.Enable to disable auth code persisting, we need to template the above config <EnableAuthCodePersistence>.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
