### ISSUE TITLE
Inconsistent UI Design in Groups > Users Tab

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17849]
**Describe the issue:**
Observing inconsistencies in the UI within the 'Groups > Users' tab. The elements appear to be inconsistent.

<img width="1499" alt="Screenshot 2023-11-16 at 15 56 17" src="https://github.com/wso2/product-is/assets/41188245/33397580-9646-45f5-94fb-cd46c5cef978">

**How to reproduce:**

1. Log in to the console 
2. Navigate to User Management> Groups 
3. Add a Group
4. Navigate to the Users tab.

**Expected behavior:**
The UI should be aligned with the rest of the component designs 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta-SNAPSHOT
 - OS: mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
