### ISSUE TITLE
Icons are broken in the add authenticator UIs

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17845]
**Describe the issue:**

![image](https://github.com/wso2/product-is/assets/5061791/d78d6caa-4957-4a65-8c5f-cb244b42ae16)

**How to reproduce:**

Goto application sign-in flow settings.
Try adding a new option from the add authenticator modal `Configure new Connection`

![image](https://github.com/wso2/product-is/assets/5061791/53624d80-906e-47b5-86bc-7bccd1ff3706)

**Expected behavior:**
Icons should work properly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
Closing as this is a duplicated issue https://github.com/wso2/product-is/issues/17412
