### ISSUE TITLE
[Doc] Unnecessary step to fill the fields for Github IDP in 'Configuring Github Authenticator' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1784]
7th step under 'Configuring the identity provider' section in [1] can be omitted since it covers with 8th step.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Github+Authenticator#ConfiguringGithubAuthenticator-ConfiguringtheidentityproviderConfiguringtheidentityprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
