### ISSUE TITLE
Inconsistent UI Issues -> In User Management Section.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17850]
**Describe the issue:**

**Users > Groups**

<img width="1191" alt="Screenshot 2023-11-16 at 16 13 20" src="https://github.com/wso2/product-is/assets/41188245/480c2f4c-f7f6-4f76-b61a-64997022981d">

**Inconsistencies in Roles > Connected apps vs Users > active sessions (When empty)**

<img width="1191" alt="Screenshot 2023-11-16 at 16 15 31" src="https://github.com/wso2/product-is/assets/41188245/9459d77e-4b03-41b7-b168-953bd94e7334">

<img width="1191" alt="Screenshot 2023-11-16 at 16 15 46" src="https://github.com/wso2/product-is/assets/41188245/9eefcfa5-5b42-4879-aba2-bc26f0609b13">

**Related issues:**
[https://github.com/wso2/product-is/issues/17849](https://github.com/wso2/product-is/issues/17849)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Suggested labels:**

**Comment by Achintha444** [comment]
Better to track this as an `improvement`, hence removing the `bug` tag.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
