### ISSUE TITLE
Display correct permissions(scopes) in the roles tab of the user/group creation wizards

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#17859]
**Is your suggestion related to an experience ? Please describe.**
Currently, the `view permissions` display's the old permissions tree in the user/group creation wizards/ This should display the correct permissions(scopes) in the roles tab of the user/group creation wizards.
![image](https://github.com/wso2/product-is/assets/46097917/6b3b3d7b-22ab-4619-b3e2-f42e78e57c6f)

**Related Issues**
- https://github.com/wso2/product-is/issues/17649
- https://github.com/wso2/product-is/issues/17836
- https://github.com/wso2/product-is/issues/17647

**Comment by kayathiri4** [comment]
View permission action is removed with https://github.com/wso2/identity-apps/pull/4646.

**Comment by thanujalk** [comment]
The current UI seems to be fine. But can improve UI as we have to scroll in both directions to see the whole thing.

![Image](https://github.com/wso2/product-is/assets/1498339/ef87702a-3d27-484c-9dec-ae0cf3fefeee)

**Comment by JayaShakthi97** [comment]
Created a separated task to track the UX improvement.
- https://github.com/wso2/product-is/issues/18250
