### ISSUE TITLE
Ask password option: Change the configuration points, give priority to management console

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1785]
In [1] the first point where its setting an expiry time the priority in the document is given to the changing the config in the file system. This requires a server restart. Secondly the option of configuring expiry time through management console is given which is not in focus. But ideally what should be in focus is the change from management console because changing configuration for each and every thing we need and restarting the server is not practical.

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
