### ISSUE TITLE
Email OTP resend send the user back to the application

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17868]
**Describe the issue:**

Recording and HAR file - https://drive.google.com/drive/folders/1EdIAuzynBzmM3GLLPEdeOS0RZKG7wkD8?usp=sharing 

**How to reproduce:**
Try emailing OTP as the first factor flow and try resending the option
Check the video for more details 

https://github.com/wso2/product-is/assets/5061791/663446c8-2e64-4bce-9660-a87cc05d7d7d

**Expected behavior:**
Resend should successfully send a new token to the user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - User

store: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ZiyamSanthosh** [comment]
This issue is not reproducible in the latest 7.0 beta pack.

https://github.com/wso2/product-is/assets/50801227/64eca31c-efba-4d04-aece-020c208d7e42

**Comment by ZiyamSanthosh** [comment]
Adding Username & password authenticator along with EmailOTP and trying the above mentioned steps returned the UI page to Username & password.

https://github.com/wso2/product-is/assets/50801227/c3a0e723-8b1e-41e1-bb59-835898a5b071

**Comment by pamodaaw** [comment]
This behavior is reproducible when there are more authenticators in the first factor other than the email OTP. Then UI is redirected to the Login page. Otherwise the resend is working fine.


https://github.com/wso2/product-is/assets/12439288/8dc49714-58c6-45e1-b90d-4c45bdba4f55

**Comment by pamodaaw** [comment]
The resend code requests are handled via the authentication retry flow. 

https://github.com/wso2-extensions/identity-local-auth-emailotp/blob/main/components/org.wso2.carbon.identity.local.auth.emailotp/src/main/java/org/wso2/carbon/identity/local/auth/emailotp/EmailOTPAuthenticator.java#L174

According to the way it is handled, if there are multiple options in that step, the retry flow will be redirected to the multi-option page without staying in the same authenticator page.

https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/AbstractApplicationAuthenticator.java#L132

We may be able to overcome this issue by setting the following configurations for the authenticator.
`enableRetryFromAuthenticator= true`
`redirectToMultiOptionPageOnFailure=false`
