### ISSUE TITLE
Configured federated authenticators are not shown in the login UI when there is only one connection configured except passkey

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17864]
**Describe the issue:**

$subject

**How to reproduce:**

1. Create a tenant from the management console.
2. Configure github connection (or any other connection)
3. Sign into react console and create a single page application.
4. In the sign-in method tab, configure the created connection in the first step.
5. Start the sample react app with created app's credentials.
6. Observe that the configured connection is not shown in the login UI.
7. Go back to application sign-in method and add passkey connection to the first step along with basic auth.
8. Access the sample app and observe that passkey option is visible.

**Expected behavior:**

Configured connections should be visible even when there is only one federated idp is configured.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
