### ISSUE TITLE
[API based authentication] Backup code authenticator is not supported in the API based authentication

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17866]
**Describe the issue:**
Backup code authenticator-related information are not available in the API response

**How to reproduce:**
1 -Add username/password as 1st step and TOTP as second step
2 - enable backup codes for the 2nd step
3 - Try API-based authentication
4 - when reaching 2nd step even the stepType is MULTI_OPTIONS_PROMPT, there is only one authenticator option

**Expected behavior:**
Implement backup code authenticator over the API and document necessary guidelines how to use it in the UI development along with any limitations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-outbound-auth-backup-code/pull/25/files
