### ISSUE TITLE
Encountering 400 Bad Request Error when Attempting to Create a Group in a Sub-Organization.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17860]
**Describe the issue:**
When trying to create a new group in a sub-organization it gives a 400 and the error message also seems to be invalid,
Error : 

```
"scimType": "invalidValue",
    "detail": "30011 - InvalidRole Role name Sub org admin is not valid. Role name must be a non null string with following format, ^[\\S]{3,30}$",
    "status": "400"
```

<img width="1506" alt="Screenshot 2023-11-17 at 10 25 59" src="https://github.com/wso2/product-is/assets/41188245/b3c87288-7911-4463-9d48-d45042d05b69">

https://github.com/wso2/product-is/assets/41188245/bfb143db-4f9e-48dc-a37e-a42ba67d1140

**How to reproduce:**

1. Create an organization
2. Redirect to groups page 
3. Add an organization, Enter the relevant details and click on finish.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by kayathiri4** [comment]
The group name should not contain spaces. In the parent organization, the error message clearly mentions that the group name should have alpha numeric characters.

[Screencast from 2023-11-18 09:52:26.webm](https://github.com/wso2/product-is/assets/36656035/743028cf-f209-4764-a58b-a995ebf5accb)

**Comment by melanisilva** [comment]
@kayathiri4 Shall we improve the error message ?

**Comment by kayathiri4** [comment]
**Fix:**
![Screenshot from 2023-11-18 10-48-40](https://github.com/wso2/product-is/assets/36656035/1e479d19-5300-4635-b3c4-ae28c5f027f7)
