### ISSUE TITLE
[API Based Authentication] There is no way to distinguish submitting TOTP initiation or submiting wrong TOTP code which makes it hard to prompt relavent errors to the end user and action items

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17863]
**Describe the issue:**

When TOTP is configured as a second-factor authentication step in the application, there is no indication in the API response after submitting an incorrect code.

**How to reproduce:**
1 - Configure username/password as the first step and TOTP as the 2nd step 
2 - Try API-based authentication flow
3 - At the TOTP step enter a wrong code and continue
4 - There is no indication about code being wrong so that the app developer is unable to give any indication to the user

**Expected behavior:**
When a wrong code is entered there should be a indication that the entered code is wrong

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
The error message currently retrieved is 
<img width="447" alt="image" src="https://github.com/wso2/product-is/assets/12690906/c0cef960-6d12-4125-a608-e57b8078189a">

The message should be modified.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
