### ISSUE TITLE
Ask password option: Provide explanation and image of management console config

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1786]
In [1] the management console config section does not contain an image where the expected configs are displayed. Please provide it. Furthermore in management console under User on boarding section there are other configs as well. Please explain the usage of them and mention if they are not relevant to this particular case,

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
