### ISSUE TITLE
Include Roles Tab on Sub-Organization User Page.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17873]
**Describe the issue:**
The User page in Sub organizations should have the view only Roles tab.

<img width="1125" alt="Screenshot 2023-11-17 at 11 34 28" src="https://github.com/wso2/product-is/assets/41188245/55742a08-b736-466e-b053-96e96f5d911b">

**How to reproduce:**

1. Navigate to Organizations page 
2. Switch to an Organization
3. Navigate to the Users page  
4. Find that the Roles tab i missing from the UI

**Expected behavior:**
Roles Tab is expected to be there in the user page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by amanda-ariyaratne** [comment]
This is fixed in identity apps console version 2.9.1.
