### ISSUE TITLE
SPs with multiple inbound protocols configured are not working on Console

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17875]
**Describe the Issue:**
$subject could mostly affect users who are migrating from older versions. Because the carbon management console allowed this and now Console does not.

**How to reproduce:**
- Create a new SP from carbon management console
- Configure both SAML and OAuth inbound configs
- Goto Console and try viewing Protocol section of the same SP
- It just keeps loading, no error messages to user

**Environment information**
 - Product Version: IS 7.0 Affected/7.0.0-Alpha2

**Comment by Avarjana** [comment]
I have sent a fix for a similar issue when there are no protocol configured.
- Issue: https://github.com/wso2/product-is/issues/17910
- Proposed fix: https://github.com/wso2/identity-apps/pull/4705

After the fix, now the interface shows OAuth2.0/OpenID Connect only even if both are configured. Show we improve this further to have support to edit multiple protocols in the console? (refer to the screenshots below)

![Screenshot 2023-11-19 at 15 20 27](https://github.com/wso2/product-is/assets/27714968/7f8d94bd-57f4-456d-b4b5-5719191e24a6)

![Screenshot 2023-11-19 at 15 20 40](https://github.com/wso2/product-is/assets/27714968/c6884b23-5e27-4c65-833e-82a4139b972a)

**Comment by Avarjana** [comment]
Multiple protocol management can be handled from the management console. The console will provide support for only one protocol. Closing this issue since the loading issue is now fixed.
