### ISSUE TITLE
Ask Password Option: Confusing and repetitive steps for the user

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1787]
In [1] the expiry time is set in the first step and the email verifcation is enabled in a latter step. In order to get this working the user has to restart the server, log in to management console twice. This maybe tiresome for the user who wants to try out this particular flow. Hence to reduce effort on user side to enable configs, please provide the configs in one go. 

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
