### ISSUE TITLE
Authorization header is missing in some curl commands

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17871]
**Is your suggestion related to a missing or misleading document? Please describe.**
Authorization header is missing in some curl commands. Therefore curls are not usable in copy pasted manner.
example:
https://is.docs.wso2.com/en/next/apis/scim2-rest-apis/#tag/Groups-Endpoint/operation/getGroup

<img width="1716" alt="Screenshot 2023-11-17 at 13 15 17" src="https://github.com/wso2/product-is/assets/25483865/41cd9f06-61c1-41b3-81da-718042e01369">

Ideally the API section should contain an option to set the authorization header based on user input (basic auth, [bearer token](https://redocly.com/docs/openapi-visual-reference/oauth-flows/) ..)
But now we have hard coded curls. Therefore appending a dynamic authorization header is not possible.

Eventhough bearer token based authorization is the common case and which we promote, to give usability aspect in current curl commands we need to add basic auth based authorization header to hardcoded curls

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
