### ISSUE TITLE
Unable to update Subject attribute of an application from console

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17876]
**How to reproduce:**
- Login to Console and create a standard OAuth app
- Goto user attributes section of the same app, add some requested claims and save
- Now select a different claim for Subject attribute and save
- The value for Subject attribute will not update 

Also, UI will keep showing username, but under the hood, it will use user id as the default during authentication.

**Environment information** 
 - Product Version: IS 7.0 alpha 2

**Comment by NilukaSripalim** [comment]
Duplicated https://github.com/wso2/product-is/issues/17144
