### ISSUE TITLE
Adaptive script functionality is hidden in carbon management console

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17874]
**Describe the issue:**
Noticed the $subject.  IMO, though the old management console is deprecated, the existing functionalities should continue to work until it is completely removed from the product.

**How to reproduce:**
- Create a new SP (from Console or old management console)
- Try to configure an adaptive script for it from carbon management console

**Environment information**
 - Product Version: IS 7.0 Affected/7.0.0-Alpha2

**Comment by NilukaSripalim** [comment]
Duplicated https://github.com/wso2/product-is/issues/17808
