### ISSUE TITLE
Set return_manually_added_local_roles true

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#17884]
**Describe the issue:**

The following config was set to false by default before IS 7.0.0
```
"idp_role_management.return_manually_added_local_roles": false,
```

But with IS 7.0.0 that config is set to true by default.

**Comment by sadilchamishka** [comment]
- https://github.com/wso2/carbon-identity-framework/pull/5174

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
