### ISSUE TITLE
Intermittently shared apps are not sent in b2b app sharing with sub orgs call

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#17882]
https://github.com/wso2/product-is/assets/24982871/f47fdacb-9501-4e64-a261-df9f5bc8c909

**Comment by JayaShakthi97** [comment]
- Fixed with: https://github.com/wso2/identity-apps/pull/4813

**Comment by JayaShakthi97** [comment]
Verified in latest beta2-SNAPSHOT


https://github.com/wso2/product-is/assets/37938529/f7cef01d-7dc2-4dfb-bad3-76a50619f164
