### ISSUE TITLE
[Roles] When an organization role is assigned to an application, the restriction of its deletion is not displayed in the UI

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17897]
**Describe the issue:**
When you try to delete a role that is assigned to an application, proper error message should be displayed. Currently no, error message is displayed

https://drive.google.com/file/d/1yPQLgjfOPuNGxD0EpJtEfwALiBO2b5vR/view?usp=sharing

**How to reproduce:**
1. Assign an organization role to an application
2. Navigate within the Role information > click on the respective role and navigate to the edit role page
3. Try to delete the role
4. Verify the behaviour of the system

**Expected behavior:**
When you try to delete a role that is assigned to an application, proper error message should be displayed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
This is the error message displayed
<img width="1689" alt="Screenshot 2023-11-18 at 10 22 52" src="https://github.com/wso2/product-is/assets/25483865/9abb9275-989c-416d-bfc9-d7a75893fb34">

This has followed a similar pattern in other places:
eg:
1. try to delete an attribute which has an external claim mappings

<img width="1711" alt="Screenshot 2023-11-18 at 10 24 20" src="https://github.com/wso2/product-is/assets/25483865/e8080ded-3bd4-413a-9118-0a9dca56e5f4">

2. Remove the external claim mappings of the attribute and try to delete the attribute when it is a requested attribute of an application

<img width="1708" alt="Screenshot 2023-11-18 at 10 25 05" src="https://github.com/wso2/product-is/assets/25483865/53290971-63b7-4f17-9c69-d6cf3363ad33">
