### ISSUE TITLE
[Administrators] Managed by is displayed as "N/A" for Administrators

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17899]
**Describe the issue:**
For Administrators displaying "Managed By" as "N/A" is not correct. In Asgardeo, this is displayed as follows:

**Current IS Behaviour:**
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/edb0802a-7d70-4bab-ba1b-d66a18921da5">

**Behaviour in Asgardeo:"**
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/533b5792-f5a6-49e6-be38-8982cdeebbf1">

**How to reproduce:**
1. Login to IS Console
2. Navigate to Administrators page
3. Verify the "Managed By" column population

**Expected behavior:**
The entity which maintains the user identity should be displayed here

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Lakshan-Banneheke** [comment]
Decided to remove the "Managed By" field for the Identity Server based on conversation with @jeradrutnam
