### ISSUE TITLE
[Doc] Mention reasons why user has to tick specific checkboxes while configuring Github as IDP

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1789]
6th step under 'Configuring the service provider' section in [1], asked user to tick 4 check boxes. In order to give more understanding to the user it's better to give reasons why and what these options will do with GITHUB authentication.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Github+Authenticator#ConfiguringGithubAuthenticator-ConfiguringtheserviceproviderConfiguringtheserviceprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
