### ISSUE TITLE
 Unintended API Calls on Switching from SubOrg to SuperOrg

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#17892]
**Describe the issue:**
An issue arises when transitioning between organizational contexts, such as moving from a sub-organization to a super organization. This problem is not limited to but includes scenarios where the `useMyAccountStatus`  is incorrectly triggered and API request is sent with 'o' path in super organization right after switching from a sub organization. The broader issue involves the SWR strategy, where API calls are mistakenly made due to a failure in adapting to the updated organizational context. This leads to API requests with outdated path.

**How to reproduce:**
1. Login to console
2. Create a sub organization
3. Switch to sub organization
4. Navigate to application page
5. Navigate back to the parent organization.

**Expected behavior:**
- No request should be sent with sub organization path after switching to super organization. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**
- https://github.com/wso2/product-is/issues/17806

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
