### ISSUE TITLE
Remove the management app check when application creation

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#17896]
**Describe the issue:**

- Remove the check box given to mark an application as a Management application. 

<img width="744" alt="Screenshot 2023-11-18 at 10 15 49" src="https://github.com/wso2/product-is/assets/25483865/cf24b629-66e0-4a00-af59-443ee27dc91a">

**Comment by kayathiri4** [comment]
**Fix:**
![image](https://github.com/wso2/product-is/assets/36656035/d6220823-2643-48c4-9dad-901b9964ed49)

**Comment by kayathiri4** [comment]
This is required for client-credentials grant. Any reason to remove this? 
@sadilchamishka

**Comment by AnuradhaSK** [comment]
> This is required for client-credentials grant. Any reason to remove this? @sadilchamishka
> 
> The error logs when using client-credentials grant without management application is added here [error log](https://github.com/wso2/product-is/files/13399922/error.log)
> 
> CC: @AnuradhaSK

- Previously internal_ scopes were returned only if this config was checked.
- But with API authorization feature, any app which authorized to an IS API which returns internal_ scopes you can get a  token with internal_ scopes by requesting in the authz/token request.
- Therefore, management app check behavior is getting obsolete.
- That's the reason to remove the management app check.

However `- But with API authorization feature, any app which authorized to an IS API which returns internal_ scopes you can get a  token with internal_ scopes by requesting in the authz/token request.` this behavior is enabled in IS pack based on legacy runtime disabled config.

Threrefore, we need to fix the CC grant logic as follows.

- If the legacy runtime is enabled - management app check should be done during CC grant 
- If the legacy runtime is disabled  ignore is management app Check

**Comment by kayathiri4** [comment]
Removed my assignment as i am not working today.
Informed B2B team.
Cc: @sadilchamishka 

Required changes are added in the above comment by @AnuradhaSK
