### ISSUE TITLE
Consent page shows unnessary information to the user

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#17904]
**Is your suggestion related to an experience ? Please describe.**
Currently, the consent page that shows after the authentication shows details that aren't very helpful to the user:
- API names
- Scope name or display name

For users, this information isn’t very informative. They simply need a clear understanding of what permissions or consents the application is asking for, explained in detail.

Current view.
<img width="579" alt="Screenshot 2023-11-18 at 3 50 44 PM" src="https://github.com/wso2/product-is/assets/32576163/26b33a4a-5208-4d53-a9c0-d930caec45f2">

**Describe the improvement**
We need to improve the consent page to show something like this,
https://nestcode.co/wysiwyg/5735api-post-to-linkedin-page-asking-for-consent-to-crud-post.PNG

**Comment by aaujayasena** [comment]
@sahandilshan please update the issue status correctly.
