### ISSUE TITLE
Skip login and logout consent by default for the applications

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#17905]
**Is your suggestion related to an experience ? Please describe.**

Right now, the default setting for new applications requires users to give login and logout consent every time. This can be repetitive and user-unfriendly. To improve the experience, we're changing the default to have the 'skip login and logout consent' option turned on for all applications. This way, users won't be prompted to consent every time they log in or logout.

<img width="709" alt="Screenshot 2023-11-18 at 2 56 08 PM" src="https://github.com/wso2/product-is/assets/32576163/ca2c4610-bd34-4a26-8a04-68683d11c725">

We need to enable above options by default when creating an application.

**Comment by chamathns** [comment]
let's track the migration impact of this in a migration issue
