### ISSUE TITLE
Authentication Issue with Backup Code Option when TOTP is Enabled as Second-Factor Authentication Setup

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#17906]
**Describe the issue:**
When enable TOTP as the second factor and try to authenticate with the backup code authentication selected, It gives an error.

<img width="1497" alt="Screenshot 2023-11-17 at 17 56 42" src="https://github.com/wso2/product-is/assets/41188245/5d81d6bc-5156-4379-a41c-b91585968881">

**How to reproduce:**

1. Create an application 
2. update the sign-in method to have TOTP as the second-factor authenticator.
3. Create a user and log in to the created user my account.
4.  Redeem the back up codes from the security tab > Recovery options

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by lashinijay** [comment]
This is not reproducible in the latest pack.
