### ISSUE TITLE
[Console]: "Console" to "My Account" switch is not available 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17900]
**Describe the issue:**
User is unable to SSO from Console to My Account. The switch is missing from the tenant admin

**How to reproduce:**
1. Login to IS Console
2. Click on the profile icon
3. Verify the options displayed

**Expected behavior:**
User should be able to SSO from Console to My account, with the option available in Console UI

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This is intentional it seems.

https://github.com/wso2/product-is/issues/17451

**Comment by GoushiRam** [comment]
> This is intentional it seems.
> 
> #17451

As discussed with @thanujalk, this has been agreed to be available
