### ISSUE TITLE
[Attribute] : Telephone is displayed by default in self registration but the configuration doesn't work. 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17914]
**Describe the issue:**
There are 2 issues concerning the "Telephone" field. 
- This a default attribute available in the Self registration field. But this field's external mappings are not configured. If we are not providing default assistance, this should not be available in the self registration page. We already have mobile field available. Hence, this is unnecessary. 
- Even though it is displayed and configuring the external mapping, is not saving the details entered. We are unable to see the entered value in the user profile or edit user pages. 

Screen recording: https://drive.google.com/file/d/1p_MnFsg2HRLy7ROwggoozDUfpbolCSCv/view?usp=sharing

**How to reproduce:**
1. Login to IS Console
2. Enable self registration
3. Self register a user with entered value in the "Telephone" field
4. Verify the details displayed in the Profile and Edit User pages. 
5. Map the external attribute with this doc https://is.docs.wso2.com/en/latest/references/extend/provisioning/extend-scim2-user-schemas/
6. Verify whether the entered details are populating

**Expected behavior:**
1. If we are providing this default, we need to provide the relevant mapping to make this completely available. 
2. The data should be available from the scim call, when the mapping is configured. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Yoshani** [comment]
Removed the telephone claim from defaultly appearing in the user profile with https://github.com/wso2/carbon-identity-framework/pull/5185
