### ISSUE TITLE
[Attribute] The saved custom attribute details are not populating

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17916]
**Describe the issue:**
The saved custom attribute details are not populating in the edit pages and profile

Screen recording: https://drive.google.com/file/d/1t1v79DuBwWDF86im1KkAj89rjZEKibD6/view?usp=sharing

**How to reproduce:**
1. Login to IS Console
2. Create a custom attribute, map to external claim
3. Make the attribute available in User profile
4. Self register a user and view the claim details in the profile > the details are available in the scim call, but not populated in the UI

**Expected behavior:**
The custom attribute details should be populated correctly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment]
This issue is fixed in the latest identity-server hence closing the issue.

https://github.com/wso2/identity-apps/assets/46097917/2f8ba33c-2dbd-4fca-93b5-b2e87f98f1fd
