### ISSUE TITLE
[Attribute] Regex validation for attributes is missing from the console. This is available in IS 6.1.0

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17919]
**Describe the issue:**
User is unable to set a regex validation for an attribute via console. This is available in IS 6.1.0

** IS 6.1.0 **
<img width="1512" alt="Screenshot 2023-11-18 at 18 32 38" src="https://github.com/wso2/product-is/assets/106053688/b6f14831-cc01-4b48-8bef-d43599527f31">

** IS 7.0 BETA **
<img width="1512" alt="Screenshot 2023-11-18 at 18 36 19" src="https://github.com/wso2/product-is/assets/106053688/99ede61c-112c-4209-b913-19a4549f2dfe">

**How to reproduce:**
1. Login to IS Console
2. Navigate to Attribute, select an attribute
3. Verify if the attribute has a place to configure the relevant regex validation

**Expected behavior:**
It should be available in IS 7.0 as it is already available in IS 6.1.0 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
### Verified in the wso2is-7.0.0-beta-SNAPSHOT.0 pack

<img width="882" alt="Screenshot 2023-11-20 at 14 47 17" src="https://github.com/wso2/product-is/assets/27746285/6c3fa80b-eec4-471f-9406-c70b444973c1">
