### ISSUE TITLE
[Attribute]  During self registration, Flow crashes when the user enters an invalid value to attribute violating the regex validation, without giving an error message

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#17918]
**Describe the issue:**
When the regex validation is set to parameters the validation is triggered after submit, causing server error

Screen recording: https://drive.google.com/file/d/1TMxWipvbV7LClWmTI6_06uqw9XaYiLoF/view?usp=sharing

**How to reproduce:**
1. Navigate to the management consol
2. Add regex pattern to an attribute 
3. Make the attribute available in the profile
4. Try to self register  a user with invalid data (against the regex validation) for the above attribute
5. Verify the behaviour

**Expected behavior:**
The validation should be triggered on screen rather than redirecting to the server error

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sumedhe** [comment]
According to the logic [1], the custom attribute validation doesn't contain the regex validation.

But we have set the regex as the `pattern` param in the input element [2].

Need to add the regex validation step also to the validation steps.

[1] https://github.com/wso2/identity-apps/blob/41c939f6a47ab1cf36d65915e11c2d02b912d3d4/identity-apps-core/apps/recovery-portal/src/main/webapp/self-registration-username-request.jsp#L1756-L1811
[2] https://github.com/wso2/identity-apps/blob/41c939f6a47ab1cf36d65915e11c2d02b912d3d4/identity-apps-core/apps/recovery-portal/src/main/webapp/self-registration-username-request.jsp#L961
