### ISSUE TITLE
400 error while updating a role name from the console

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#17911]
**Describe the issue:**
400 Bad request error is being returned while updating a role name from the console UI since the updated role name is not being set as value in the API request body

Sample request body
```
{
    "Operations": [
        {
            "op": "replace",
            "path": "displayName"
        }
    ],
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ]
}
```

**How to reproduce:**
1. Create a role in console UI
2. Click on update button under the role name

<img width="1512" alt="Screenshot 2023-11-18 at 16 22 50" src="https://github.com/wso2/product-is/assets/50801227/bc8a988e-2520-4c94-b485-58a17cf864a1">

**Expected behavior:**
The request should respond with 200 code and the name of the role should be updated

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Achintha444** [comment]
This is duplicate https://github.com/wso2/product-is/issues/17833
