### ISSUE TITLE
Unable to Set Protocol in the Console for a Service Provider Registered Without a Protocol in the Carbon Management Console

### ISSUE THREAD

**Issue by AmshikaH** [wso2/product-is#17910]
**Describe the issue:**

In the Console, when applications (called service providers in the Carbon Management Console) are registered, the protocol is configured as well. Of the 5 types currently available, for `Traditional Web Application` and `Standard-Based Application`, it is mandatory to select a protocol when registering the application, whereas for the other 3, a protocol is configured by default.

However, in the Carbon Management Console, when service providers (called applications in the Console) are registered, it is not mandatory to configure a protocol.

When a service provider is registered in the Carbon Management Console without configuring a protocol and then accessed from the Console, selecting the protocol tab gives the following message.

![image](https://github.com/wso2/product-is/assets/66556626/320bb558-836d-45b8-aec8-58cc568ad688)

**How to reproduce:**

1. Register a service provider in the Carbon Management Console without setting the protocol (i.e., `Inbound Authentication Configuration`).
2. Open the created service provider in the Console.
3. Open the Protocol tab.

**Expected behavior:**

It should be possible to configure the protocol in the Console for service providers created in the Carbon Management Console or there should be a message informing the user to configure the protocol from the Carbon Management Console.

**Environment information:**
 - Product Version: wso2is-7.0.0-beta (built from the product-is master branch)

---

### Optional Fields

**Related issues:**
- https://github.com/wso2/product-is/issues/17875 - another issue where the behaviour in the Console differs from that in the Carbon Management Console.

**Comment by Avarjana** [comment]
Fix PR
- https://github.com/wso2/identity-apps/pull/4705

**Comment by Avarjana** [comment]
Closing since the fix is in place.
