### ISSUE TITLE
Ask Password option: Default Ask password wording should change

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1792]
As shown in the below image the wording of the email sent represent resetting password. But this particular use case is on setting a whole new password. Hence please change the email template to reflect that.

![is_issue_10](https://user-images.githubusercontent.com/15624590/34193452-cd06a55c-e579-11e7-893c-8e3da0af7a74.png)

Furthermore as shown in the below image, the link that the user get redirected to also mentions reset password, it should also change to reflect the real use case.

![is_issue_11](https://user-images.githubusercontent.com/15624590/34193459-d979334a-e579-11e7-96cc-bc05cad33b20.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
