### ISSUE TITLE
Add documentation for new OTP pattern related configs 

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#17928]
**Is your suggestion related to a missing or misleading document? Please describe.**

Following new configurations are added
1. Send OTP in e-mail
2. Include uppercase characters in OTP
3. Include lowercase characters in OTP
4. Include numbers in OTP
5. OTP length

to following governance connectors
1. Self registration
2. Lite user registration
3. Ask Password
4. Account Recovery
5. User Claim Update

<img width="1352" alt="Screenshot 2023-11-19 at 13 07 36" src="https://github.com/wso2/product-is/assets/59327626/e8dc9349-b6bb-4ea1-b802-053038a386ab">

Related Issue
- https://github.com/wso2/product-is/issues/14808

The SMS OTP regex config from [1] is no longer supported

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/extend-username-and-password-recovery/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
