### ISSUE TITLE
Proper messaging is not available when the user roles are not available

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#17924]
**Describe the issue:**
When checking the roles assigned to a user, if the roles are not available (This is a bug reported under [1]) only the i18n tag is printed as the message. Please refer the below SS.

<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/19262008/6484b7f5-944e-4c39-9392-c0a9edb1b98d">

Here there is another issue. This tab's description is `View assigned roles for the user.`. But the i18n tag contains `editRoles` part in it.

`manage.features.user.updateUser.roles.editRoles.placeholders.title`

[1] https://github.com/wso2/product-is/issues/17923

**How to reproduce:**
1. Add the following config to the deployment.toml file and start the server.
```
[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false
```
2. Go to the user listing and go to edit user page.
3. Now go to the Roles tab.

**Expected behavior:**
* Display the proper message.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0.0-beta
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by Achintha444** [comment]
This issue is fixed in the latest identity-server hence closing the issue.
<img width="1512" alt="Screenshot 2023-11-19 at 10 57 18" src="https://github.com/wso2/identity-apps/assets/46097917/20647be8-3c1d-4ae2-a1fc-20327baee2a0">
