### ISSUE TITLE
[Doc] Example should modified with same format given under 'Testing the Sample' in Configuring Github Authenticator doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1793]
'Testing the Sample' section contains an example of path for travelocity application as 'http://<TOMCAT_HOST>:<TOMCAT_PORT>/travelocity.com/index.jsp'. But the example given as 'http://localhost:8080/travelocity.com' and doesn't contain 'index.jsp' part.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Github+Authenticator#ConfiguringGithubAuthenticator-TestingthesampleTestingthesample

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
