### ISSUE TITLE
Issues with the `Audience` in the add user/group wizard

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#17938]
**Describe the issue:**
Following issues exists in the `Audience` in the add user/group wizard.

- [ ] Font type of the `Audience` column should change to adhere to the following.

****Current Interface****
<img width="1800" alt="Screenshot 2023-11-20 at 10 39 41" src="https://user-images.githubusercontent.com/36656035/283808325-a21af912-0aa1-48a4-94d8-20233ccb157b.png">

****Expected Interface****
<img width="1800" alt="Screenshot 2023-11-20 at 10 39 41" src="https://github.com/wso2/product-is/assets/46097917/7144e328-17f9-4e9c-8f06-48eb85b11267">

- [ ] In the legacy run time audience value is not returning hence, that column should not display in the legacy authz runtime.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
