### ISSUE TITLE
Change organization SSO authenticator icon to a key

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#17943]
Change organization SSO authenticator icon to a key.

<img width="541" alt="Screen Shot 2023-11-20 at 11 19 46 AM" src="https://github.com/wso2/product-is/assets/24982871/47f7733e-7079-4602-bdae-92f99f29bbcb">

<img width="156" alt="Screen Shot 2023-11-20 at 11 20 34 AM" src="https://github.com/wso2/product-is/assets/24982871/30aa042a-571a-47cd-933b-138e0dd18a65">

**Comment by JayaShakthi97** [comment]
The current icon is a fallback icon since the icon for SSO is not resolved from the client.
- Frontend - Updated SSO svg need to be added.
    - https://github.com/wso2/identity-apps/pull/4728
- Backend - Client should be updated to resolve the image path for SSO.
