### ISSUE TITLE
Uncaught SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#17941]
**Describe the issue:**
Getting these errors in the browser console, when accessing the MyAccount.
```
Uncaught SyntaxError: Unexpected token ';' (at myaccount:46:29)
Uncaught SyntaxError: Unexpected token ';' (at myaccount?code=aaf7edf5-7a3f-31cb-b681-684631c5910c&session_state=3b07e47b70bfd87b736a4921b3f38c90bb3658fda44b5035f19df02a3efe2ddf._mTka7LU1YNjBwtGIB5McQ&state=sign-in-silently_request_0&scope=SYSTEM+openid+profile:46:29)
```

**How to reproduce:**
Access the MyAccount and observe the browser console.

**Environment information**
 - Product Version: IS 7.0 Alpha

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
