### ISSUE TITLE
[Doc] All the samples under Managing Users and Roles with APIs are outdated

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1794]
Type: Bug
Priority: High
Severity: Major
Release: wso2is-5.4.0-update1

All the samples and properties mentioned under Managing Users and Roles with APIs are outdated
https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addUser()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
