### ISSUE TITLE
Multiple user adding feature is not usable for organizations in IS Console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17946]
**Describe the issue:**
1. Multiple users adding feature-enabling behavior in **tenants**:

https://github.com/wso2/product-is/assets/25483865/e4dc5d96-1f4c-4ac7-8b2d-75a08ee8c7dc

2. Multiple users adding feature-enabling behavior in **organizations**:

https://github.com/wso2/product-is/assets/25483865/03c0153c-c883-45a7-b4d5-21dbdda43d9e

- The organization's console view doesn't have the config to enable "invite the user to set the password" feature
- Even though we enable this config by default, the feature won't work if the email sender configurations are not setup https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/invitation-workflow/#use-the-management-console:~:text=Enable%20the%20email%20sending%20configurations%20of%20the%20WSO2%20Identity%20Server.
IS doesn't have a default email sender configuration either.

**Comment by PasinduYeshan** [comment]
This issue is fixed with following PR. 
- https://github.com/wso2-extensions/identity-organization-management/pull/305

Decision was made to enable "invite the user to set the password" option in sub organization by default.
