### ISSUE TITLE
There is no option to switch to suborgs and No delete option  which are not in 1st pagination page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17940]
**Describe the issue:**
Currently, there is no option or mechanism provided to switch & Delete  to suborganizations that are not present on the first pagination page.

**How to reproduce:**
Navigate to the organization page with a large number of suborganizations ( more than 10).
Observe that only suborganizations on the first pagination page are accessible.

**Expected behavior:**
Users should be able to navigate to suborganizations beyond the first pagination page. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: BetaSnapshot 7.0
 - OS: Mac
 - Database: H2
 - Userstore:JDBC

---

https://github.com/wso2/product-is/assets/39120228/3e8d50db-99df-401c-a1d5-196dd7ff1d5b

**Comment by PasinduYeshan** [comment]
This issue is addressed by following PR
- https://github.com/wso2/identity-apps/pull/4724
