### ISSUE TITLE
Access to Console by End users

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#17942]
**Describe the issue:**
End users are able to access the management console (/console) in IS 7.0.

**How to reproduce:**
Create a regular user and try to access the management console (/console).

**Expected behavior:**
End users should not be able to access the management console.

**Environment information**
 - Product Version: IS 7.0 Alpha

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
