### ISSUE TITLE
OTP entering page of the Email OTP Federated connection is not properly updated.

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#17951]
**Describe the issue:**
There are some misleading messages shown on the OTP entering page of the **Federated Email OTP** Connection.

**How to reproduce:**
1. Login to the Management Console 
2. Configure an Email OTP  Federated Identity Provider
3. Engage the IdP to an application and try to login

Error 1:
The error message for incorrect OTP is not cleared when showing the next error.
<img width="496" alt="image" src="https://github.com/wso2/product-is/assets/12439288/d3497f36-f059-4704-976e-68825a5242b5">

Error 2:

`Authentication failed. The code you entered is invalid or expired. Please retry.` error message is not cleared out when reinitiating the flow

https://github.com/wso2/product-is/assets/12439288/8311e598-37b4-4b8b-9ab9-0ce9d6df6a57

Error 3:
Ideally `A new OTP is sent to your email` message should be displayed once the `Resend Code` button is clicked.

https://github.com/wso2/product-is/assets/12439288/66ed33af-4140-4174-94e9-33e272a40296

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/17868

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
