### ISSUE TITLE
Ask Password Option: Why are we sending a password reset successful when adding a new password

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1795]
By following [1] when the password is taken from the user itself, the user get a mail as below that indicates success of a password reset. In this use case we are not resetting a password, rather a asking the password from the user itself. The document also does not mentions anything on a success mail.

![is_issue_12](https://user-images.githubusercontent.com/15624590/34193624-b05ed8ce-e57a-11e7-9979-c64bf2017948.png)

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by hauntingEcho** [comment]
it may be clearer just to change the default message from saying the password was reset to saying it was set, which will make sense in both onboarding & resetting.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
