### ISSUE TITLE
Remember me period needs to be specified in minutes

### ISSUE THREAD

**Issue by Dinithi-Hasanika** [wso2/product-is#17950]
**Is your suggestion related to a missing or misleading document? Please describe.**
In documentation [1], It states that 

Remember Me period | This is the duration in *weeks* for which WSO2 Identity Server should remember an SSO session given that you have selected the Remember Me option in the WSO2 Identity Server login screen.
-- | --

[1] - https://is.docs.wso2.com/en/latest/guides/login/session-timeout/

**Describe the improvement**
Since the value needs to be specified in minutes in the relevant configuration, **weeks** word needs to be changed to **minutes**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
