### ISSUE TITLE
Incorrect API call to list roles during user creation in organization

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17968]
**Describe the issue:**
This API call is used to list roles in organization onboarding.
`/t/carbon.super/o/api/server/v1/organizations/f87640bc-3a32-4253-85d4-7efc04465bac/roles`

This needs to be changed into `/o/scim2/v2/Roles`

https://github.com/wso2/product-is/assets/25483865/7c7df8b2-6e70-4664-9bff-d72c3c4cb9cc

**How to reproduce:**

- Create a new org.
- Try to create a user.

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR.
- https://github.com/wso2/identity-apps/pull/4760
