### ISSUE TITLE
Getting 403 for `POST https://localhost:9443/t/carbon.super/o/scim2/Roles/.search` when onboarding users to organization

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#17965]
**Describe the issue:**
- Try to onboard a user to the organization.
- API call POST https://localhost:9443/t/carbon.super/o/scim2/Roles/.search will return 403

https://github.com/wso2/product-is/assets/25483865/a501e091-db0c-448a-a087-e54ad285eddd

The invoked API is wrong. `v2` part is missing
/o/scim2/**v2**/Roles/

**Comment by PasinduYeshan** [comment]
Couldn't reproduce this issue.
Incorrect listing role API is addressed through the following PR.
- https://github.com/wso2/identity-apps/pull/4760
