### ISSUE TITLE
[Doc] The section "What has changed in this release" should be reworded

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1796]
In [1\] the section "What has changed in this release" should be reworded. The sentence " " leads to confusion to the reader whether it says one feature/ functionality was deprecated but below we talk about 3 functionalities.

[1\] [https://docs.wso2.com/display/IS540/About+this+Release](https://docs.wso2.com/display/IS540/About+this+Release)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
