### ISSUE TITLE
Improve documentation on Change the hostname

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#17973]
When the hostname or port changes, it's crucial to update the callback URL regex and access URL stored in the databases. Failure to do so may result in a callback URL mismatch error during login to the console or myaccount and gets error page when redirecting the page defined as the access URL. While IS-server versions 7.0 and onward handle this properly, migration from versions below 7.0 does not automatically support updating callback URL regex and access URL for console and myaccount applications.

To address this, customers need to manually update the callback URL regex and access URL for the console and myaccount applications via APIs using the following steps:

1. Retrieve all applications.
2. Obtain the app IDs for the console and myaccount.
3. Update the access URL using the PATCH API /applications/{app-id} as in example.
4. Update the callback URL regex using the PATCH API /applications/{app-id}/inbound-protocols/oidc as in example.

Eg: `https://localhost:9443` -> `<PROTOCOL>://<HOSTNAME>:<PORT>`

By following these steps and making the necessary updates via APIs, customers can ensure that the console and myaccount applications align with the new hostname and port, preventing above errors.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
