### ISSUE TITLE
Current SQL queries of oGetUserListFromPropertiesWithID method consumes CPU spikes when having large amount of records

### ISSUE THREAD

**Issue by DInuwan97** [wso2/product-is#17986]
**Describe the issue:**

When triggering the password grant the following query will be triggered within the `doGetUserListFromPropertiesWithID` method.

```
SELECT DISTINCT UM_USER.UM_USER_ID FROM UM_USER, UM_USER_ATTRIBUTE WHERE UM_USER_ATTRIBUTE.UM_USER_ID = UM_USER.UM_ID AND UM_USER_ATTRIBUTE.UM_ATTR_NAME =? AND UM_USER_ATTRIBUTE.UM_ATTR_VALUE =? AND UM_USER_ATTRIBUTE.UM_PROFILE_ID=? AND UM_USER_ATTRIBUTE.UM_TENANT_ID=? AND UM_USER.UM_TENANT_ID=?
```

As per the above query, it is going to fetch the UM_USER_ID attribute from the `UM_USER_ATTRIBUTE` table even if the claim URI was set as the username claim URI. However, it's not essential to query the `UM_USER_ATTRIBUTE` table since the method parameters contain the username claim URI. Instead of the UM_USER_ATTRIBUTE table, we can use the UM_USER table to retrieve the username. But still, the above query should be available to search the user attributes if the claim URI is not equal to the username.

The current query causes higher CPU spikes while having nearly 50 million records in the tables, even if the RDS is allocated sufficient resource utilization.

If the passing property parameter is equal to the mapped attribute against the username, this method[1] should be changed to query the `UM_USER` table. Otherwise, it should query the `UM_USER_ATTRIBUTE` table and get the user attributes.

**How to reproduce:**
Require a load test. Invoke the password grant with higher number of records in `UM_USER` and `UM_USER_ATTRIBUTE`.
(20 million and 50 million records)

---
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Windows, Linux, Mac
 - Database: All
 - Userstore: JDBC

[1] - https://github.com/wso2/carbon-kernel/blob/v4.6.1/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L2304

**Comment by RushanNanayakkara** [comment]
Closing as completed.
