### ISSUE TITLE
[Chaos] Error while one node going shutdown from cluster

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1798]
**Operating System:** Ubuntu 16.04
**Java Version**: Oracle JDK 1.8.0_45
**Packs**: IS 5.4.0 GA
**Setup**: Cluster

**Steps to reproduce**
1. Run the scenario automated [1] for the 17th use case in [2]. 
2. Run the login with higher frequency (1000 threads with 100 ramp-up period). While running the test, shut down and restart one of the nodes in the cluster.

**Expected Result**
It should handle requests by the exisiting node in the cluster.

**Actual Result**
Most of the requests going to fail and existing node log following error continously:

`TID: [-1234] [] [2017-12-20 05:36:55,282] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Context does not exist. Probably due to invalidated cache `

[1] https://github.com/wso2-incubator/identity-test-integration/tree/master/solution17
[2] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by jsonds** [comment]
Observed the similar error even in a standalone step while gracefully restarting the server which was serving requests.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
