### ISSUE TITLE
Define resource access controls for `/configs` API

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17993]
**Describe the issue:**

Currently resource access controls for the `api/server/v1/configs/` paths are defined only for the `GET` requests and haven't defined any permissions [1]. APIs are governed through the `internal_login` scope. This raise following concerns.
1. Do we need to govern these server config APIs through proper permissions and scopes
2. Is `internal_login` the expected scope for these server APIs
3. With the new resource access control runtime, these kind of APIs with undefined access controls won't be accessible. Hence we need to define access controls for `/configs` path.

[1] https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml.j2#L3087-L3090
[2] https://github.com/wso2/carbon-identity-framework/blob/abf18c7235934a520eb02d9224314480647e9b6a/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/resource-access-control-v2.xml.j2#L590

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduDilshan** [comment]
PATCH and PUT requests are covered with `internal_config_update` scope in https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/resource-access-control-v2.xml.j2#L1052-L1054.

Need to consider other paths

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
