### ISSUE TITLE
Upon clicking the "Update" button on the self-registration page, the self-registration feature is disabled automatically

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#17990]
**Issue Description:**

> Please refer the $subject

**Steps to Reproduce:**

- Enable the toggle button for self-registration in the console under "Login & Registration."
- Click on the "Update" button located at the bottom of the page.
- Notice that self-registration is updated to disabled, and the toggle button becomes disabled as well.

[Screencast from 21-11-23 11:19:58 AM IST.webm](https://github.com/wso2/product-is/assets/30428591/e5e2fb15-1054-4b5a-9d52-778da79132f3)

**Expected Behavior:**

After enabling self-registration, clicking the "Update" button should retain the enabled status rather than automatically disabling the self-registration feature.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

https://github.com/wso2/product-is/assets/41533942/8b339d04-d58b-4031-b3af-886deb2a7572
