### ISSUE TITLE
Honour to application access URLs for callback url regex pattern in recovery scenarios

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#17999]
**Is your suggestion related to an experience ? Please describe.**
At the moment we have callback URL regex patterns configured at the tenant level to validate the redirected URLs after completing the below scenarios.

- Self Registration
- Account Recovery

However, since this is a tenant level config, if there are a lot of applications, its not feasible to configure a regex pattern to honour to all the applications. This callback URL shouldn't be a tenant level config, but rather a application level config.

https://github.com/wso2/product-is/assets/1332991/c081376d-df27-4664-bf88-f62a02456335

Please ignore the difference in the UIs.

**Describe the improvement**
Application already has the access URL configuration which is the place that should be the ideal place for the user to redirect. Hence we should first honour to the application access URL and then fallback to the configured regex pattern.

**Additional context**

**Comment by ashanthamara** [comment]
Tested the User self registration email verification resend flow as well. It is working as expected.
(Tested Artifacts: https://wso2.org/jenkins/job/products/job/product-is/5016/)
Hence closing the issue.
