### ISSUE TITLE
Ask password option: Blank page is given the link is expired

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1800]
**Tried with**
Browser: Google Chrome Version 63.0.3239.108
OS: Ubuntu 16.04
JDK: 1.8.0_144

**Steps**
1. Created a user with ask password option enabled
2. After the link expiry time exceeded, clicked on the link -> password reset option appeared 
3. Gave password and clicked submit

A blank page as given below appeared

![is_issue_13](https://user-images.githubusercontent.com/15624590/34195299-c4ba23ac-e582-11e7-97df-3066bb641e73.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
