### ISSUE TITLE
Enhancement: Improve UI Alignment on API Resources Page in Initial State and Left Side Panel Title Consistency

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18009]
**Describe the issue:**
issue 1: API Resources Page (Initial State):
The API Resources page, in its initial state when there are no APIs added, currently lacks alignment with UI components on other pages. To enhance user experience and maintain consistency across the application, consider the following improvements:

Add "Add" Option in the Center:

**Introduce an "Add" option in the center of the page, similar to most other pages, providing a consistent and intuitive user interface.**

issue 2:
2. Left Side Panel Title Consistency:
On the API Resources Page, the left side panel title is not aligned with the header of the particular page, 
Ensure that the left side panel title on the API Resources page aligns with the header of the page, maintaining consistency with other sections.

<img width="1726" alt="Screenshot 2023-11-21 at 16 52 06" src="https://github.com/wso2/product-is/assets/39120228/3e833520-8c70-49ac-9c92-5094d8606a8a">

**Comment by JayaShakthi97** [comment]
The following UX improvements are done.
- https://github.com/wso2/identity-apps/pull/5309
- Update the page title to "API Resources".
- Show the Add button in the empty placeholder.
- Hide search input when the list is empty.
