### ISSUE TITLE
 Able to delete Tenant owner via Console User Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18014]
**Describe the issue:**
When using the Console User Page, there is a delete option that allows users to delete a Tenant owner. 

<img width="1728" alt="Screenshot 2023-11-21 at 18 15 14" src="https://github.com/wso2/product-is/assets/39120228/7717923c-7bf9-4e56-af28-330b11045c16">

**Comment by pavinduLakshan** [comment]
Not reproducible in the latest build.

<img width="1506" alt="Screenshot 2023-12-01 at 23 52 38" src="https://github.com/wso2/product-is/assets/41533942/683931f9-5a86-4c81-ae34-02ed00b536f1">
