### ISSUE TITLE
Deprecate revoked token headers from OAuth2 /revoke endpoint response.

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-is#18018]
**Describe the issue:**
The OAuth 2.0 Token Revocation specification, defined in RFC 7009, does not specify returning revoked tokens as headers in the revocation response. The server should respond with a status code of 200 if the revocation is successful, and the response body is typically empty.  The specification does not mandate returning revoked tokens in headers of the response. The focus is on the simple revocation request and response mechanism.

These specific headers were added to identity oauth2 component for API-M 2.x and 3.x  versions where KM's revoke endpoint was proxied by Gateway and Gateway was needed to be aware about the revoked tokens. With API-M 4.x onwards, with introduction of revoke event notification and JMS topic, GW no longer need to proxy the revoke endpoint and we do not rely on these headers.

Hence we need to deprecate these headers through a config in identity.xml
```
<OAuth>

<EnableRevokeTokenHeadersInResponse> false </EnableRevokeTokenHeadersInResponse>
```

**Comment by dushaniw** [comment]
Need to add this to the release note and migration docs as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
