### ISSUE TITLE
[API Based Authentication] [Bug] Getting Null when enable only API Based Authtincation

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#18019]
**Describe the issue:**
$sub

## Steps to Reproduce
- Create an Standard base Application with OAuth 2.0 protocol
- Go to advanced Section
- You should see the API Based Authentication Configuration
- Enable only API Based Authentication Configuration and clikc Update.
- Android Package Name and Apple ID values will be shown as Null

## Possible Root Cause
-  When updating an application via patch, we internally retrieve the application object apply the changes and save the object.
https://github.com/wso2/carbon-identity-framework/blob/424f1d087371db7425028ccdba51dbf7a05eb46f/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java#L5057
- In above code we are checking 
`
 androidPackageName.setValue(String.valueOf(clientAttestationMetaData.getAndroidPackageName()));
`
if clientAttestationMetaData.getAndroidPackageName() == null then androidPackageName will be set as "Null"

**Comment by DMHP** [comment]
<img width="865" alt="image" src="https://github.com/wso2/product-is/assets/12690906/d5e05ba0-8c23-400b-9f4b-fe0c6f8c5910">
