### ISSUE TITLE
Ask password option: Difference between ask password code expiry time and email notification code expiry time

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1801]
When configuring according to [1] in the actual configuration following two configs are there

1. Email verification code expiry time
2. Ask password code expiry time

How do the above configs are interrelated to the ask password option. Here since we are configuring the expiry time to an email based link, is there any dependency between the two configs?

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
