### ISSUE TITLE
[API Based Authentication] [Bug] Improvement for Client Attestation

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#18021]
**Is your suggestion related to an experience ? Please describe.**
With https://github.com/wso2/product-is/issues/16836, we delivered  Client Attestation capabilities for API_Based_Authentication.
We got several feedbacks along the process and we have prioritise them based on our timeline.  Hence I will raise this issue to track all the improvements for Client Attestation (Security API Based Authentication).

[Note that following tasks are not in the order of priority]
- In Android Attestation, we need to call Google Attestation service. But [here](https://github.com/wso2/carbon-identity-framework/blob/93f26cc928417637c5605c95e9dfaa2a9ad24d52/components/client-attestation-mgt/org.wso2.carbon.identity.client.attestation.mgt/src/main/java/org/wso2/carbon/identity/client/attestation/mgt/validators/AndroidAttestationValidator.java#L147), the same thread requested for android attestation is used for this external call. We need to improve this by having a thread pool and execute the external call. 
- In Apple Attestation, we have the basic security implemented. But there are some advanced security implementation given in the [doc](https://developer.apple.com/documentation/devicecheck/validating_apps_that_connect_to_your_server#3576643),  we need to improve those validations also.
- In Apple Attestation, revocation check is disabled by default and we provide an configuration to enable it [here](https://github.com/wso2/carbon-identity-framework/blob/b7ad5dcb78e8050d6c36f75a221eea47b0ff0756/components/client-attestation-mgt/org.wso2.carbon.identity.client.attestation.mgt/src/main/java/org/wso2/carbon/identity/client/attestation/mgt/validators/AppleAttestationValidator.java#L186). We have to set true and test for the cloud deployments.
- In Apple Attestation, currently we are shipping Apple Attestation root CA with the product as pem. But we need to use a keystore by anychance Apple decided to provide set of root certs. More details can be found in this mail [Request to add Apple Attestation Root Certificate to Product IS and Asgardeo]
- Nonce Issuance, This improvement is to track and develop Client Attestation As A Service where Client Attestation Service issues Nonce to clients.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
