### ISSUE TITLE
[DOC] TOTP with authentication federated authentication are not clear 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1802]
**Improvements** 

Under service provider configuration its given the steps to connect federated authentication. But it is not clear the exacts steps that end user need to do.
Better to have a new section for federated authentication. 

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+TOTP+Authenticator#ConfiguringTOTPAuthenticator-ConfiguringtheserviceproviderConfiguringtheserviceprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
