### ISSUE TITLE
SAML IDP connection template does not have an option to get the public certificate.

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18020]
**Describe the issue:**

When onboard a SAML IDP connection, the public certificate of the Identity server should be shared with the external IDP. The current SAML IDP connection template doesn't have an option to download/get the public certificate.

Ideally, the public certificate of the IS should be able to download from the SAML connection template to increase the user experience. 

**Expected behavior:**

A kind of view (only the certificate) which can be seen in the SAML App info tab should be available for the SAML connection.

<img width="843" alt="Screenshot 2023-11-22 at 09 54 54" src="https://github.com/wso2/product-is/assets/35717390/11ffae39-31b9-4181-8405-4ffbe7ed2552">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0.0-beta]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by pavinduLakshan** [comment]
In SAML applications, the IdP certificate is retrieved from `GET /identity/metadata/saml2` [1][2], but there is no way to retrieve the IdP certificate for SAML IDPs.

[1] curl 'https://localhost:9443/t/carbon.super/identity/metadata/saml2' \
  -H 'Access-Control-Allow-Origin: https://localhost:9001/t/carbon.super/console' \
  -H 'Accept: application/json' \
  -H 'Referer;' \
  -H 'Authorization: Bearer 3d2a15ec-959e-3ae4-a26a-54062e37179a' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  --compressed \
  --insecure

[2]
<img width="1506" alt="Screenshot 2023-12-02 at 10 42 12" src="https://github.com/wso2/product-is/assets/41533942/91b50220-9222-4347-8f84-1c9296f606ad">

**Comment by pavinduLakshan** [comment]
Marking as on hold as this is not currently a critical requirement.

**Comment by chamathns** [comment]
> Marking as on hold as this is not currently a critical requirement.

This is not a new feature. We cannot break/remove any feature that we already had.

**Comment by aaujayasena** [comment]
Based on this comment https://github.com/wso2/product-is/issues/18020#issuecomment-1837051387, removing the on-hold label. @pavinduLakshan

**Comment by kayathiri4** [comment]
If a user wants to configure Asgardeo as an external OIDC IDP, currently there is no way to download the public certificate from the OIDC application created in Asgardeo side.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
