### ISSUE TITLE
Getting a retrieval error when navigating to admin Active sessions inside a sub organization

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18027]
**Describe the issue:**

Getting a retrieval error when navigating to admin Active sessions inside a sub-organization

https://github.com/wso2/product-is/assets/40081059/e9107006-0356-46f5-8ea4-2f1a00432151

**How to reproduce:**

1.Login to the console
2.Create a sub organization
3.Go to the created suborganization
4.Go to users and then select the admin user
5.Navigate to Active session tab

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sadilchamishka** [comment]
Will be tracked with https://github.com/wso2/product-is/issues/18023
Will update once completed
