### ISSUE TITLE
Invoke same /scim2/Groups API 4 times list groups. Also getting groups info with assigned users, assigned roles which are not required for listing view

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18029]
**Describe the issue:**
- Open the network tab
- Go to groups list view
- You could see 4 GET API calls to /scim2/Groups

https://github.com/wso2/product-is/assets/25483865/3e96e908-709a-4775-9523-4c7f21dbed77

- [ ] Also, /scim2/Groups returns all the details of groups such as assigned members, and roles of the group which are not required for group listing purposes.

In the backend, we need to join multiple tables to return assigned members and roles of a group. This is performance intensive.
exclude unwanted attributes when invoking the API.
eg: `/scim2/Groups?excludedAttributes=members,roles`

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

- Only one GET /Groups request is sent on page load.
<img width="1506" alt="Screenshot 2023-11-29 at 10 45 24" src="https://github.com/wso2/product-is/assets/41533942/46d542db-f486-4395-9214-e035c23d13d1">

- Assigned members and the roles assigned to the groups are not included in the GET /Groups call in the Group list page.
<img width="1506" alt="Screenshot 2023-11-29 at 10 45 11" src="https://github.com/wso2/product-is/assets/41533942/9ea06050-4109-4fcc-aa39-afff8f12f0b2">
