### ISSUE TITLE
Console access URL shown in organization console settings page

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18031]
**Describe the issue:**

The console settings page of the organization (previously known as sub-org) need not to show the console URL. As the user already accessed the console console via the URL and switch to that space. Also, the currently shown `/t/<tenant-domain>/o/<org-id>` URL will not help to land in to the organization console page directly. Hence that URL is not usefull, eithe we can remove or have the root tenant's console URL.

<img width="1369" alt="Screenshot 2023-11-22 at 11 32 51" src="https://github.com/wso2/product-is/assets/35717390/3e8ee2fa-1acb-4c0c-b9ed-275eaa8980b2">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0.0-beta]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
I'm working on this issue (https://github.com/wso2/product-is/issues/17477) that'll fix the `t/<TENANT>/o/<ORG_ID>` path navigation issues.

With that, if a user enters a fully qualified console URL on the browser, they'll automatically switch to the relevant organization.

If that's done, do we still need to remove the URL?

**Comment by sadilchamishka** [comment]
Closing this issue as the raised concern is tracked with https://github.com/wso2/product-is/issues/17477
