### ISSUE TITLE
Irrelevant parts in hint text for client ID input is displayed as code

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18035]
**Describe the issue:**

$subject

<img width="1503" alt="Screenshot 2023-11-22 at 13 10 13" src="https://github.com/wso2/product-is/assets/41533942/90936790-2c0f-4627-8b23-2ef4633fd1fa">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
Sent a fix through https://github.com/wso2/identity-apps/pull/4791
<img width="899" alt="Screenshot 2023-11-22 at 23 23 48" src="https://github.com/wso2/product-is/assets/40081059/591b06d9-6c82-406f-8a2c-172775cc1c61">
