### ISSUE TITLE
Assigned permissions of a role are not getting displayed and an error is seen when accessing for the first time

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#18039]
**Describe the issue:**

When accessing a particular role's permission by navigating to the permissions tab of the roles page for the first time after logging in, relevant permissions are not getting displayed and an error message is displayed. Navigating to the same page once again from another page displays the permissions properly and no error message is displayed.

https://github.com/wso2/product-is/assets/50801227/16a7b4e5-3516-4cd8-9380-db295c749c13

**How to reproduce:**
1. Login to the console as admin
2. Move to roles menu
3. Select a role and move to it's permissions tab

**Expected behavior:**
Assigned permissions should be displayed and no error messages should be shown.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
Related issue https://github.com/wso2/product-is/issues/18040
