### ISSUE TITLE
Ask password option: Provide a link to SCIM 2.0 api page or provide explanation on each of the request params

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1803]
In [1] the scim request is not explained. Please provide explanation of the request params or provide to a documentation that includes comprehensive explanations.

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
