### ISSUE TITLE
Exclude unwanted attributes of user for user listing

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18034]
**Describe the issue:**

- Open network tab
- Go to users section
- /scim2/Users API call is invoked with domain param and pagination params
- Therefore, user's assigned groups, user asisgned roles also returned. Those details are not required to populate the user listing view. Returning all users' assigned groups and roles is also resource intensive. 

https://github.com/wso2/product-is/assets/25483865/c10220af-8fc7-43dc-9f8f-0c1d2a22fda2

Exclude roles and groups when listing users 
eg: `/scim2/Users?domain=PRIMARY&count=10&excludedAttributes=roles,groups`

**Comment by pavinduLakshan** [comment]
Verified in the latest build.

<img width="1506" alt="Screenshot 2023-11-29 at 10 43 02" src="https://github.com/wso2/product-is/assets/41533942/2a22c61a-7da3-44fe-b41a-2afcddb57d02">
