### ISSUE TITLE
Unable to delete and edit "admin" role in Application Levels

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18045]
**Describe the issue:**

Already have a "admin" role in organization level. And it can not be deleted. We can create the role again in application level as "admin" and it also can't deleted. Also can not assign permissions.

<img width="1145" alt="Screenshot 2023-11-22 at 16 32 32" src="https://github.com/wso2/product-is/assets/39077751/b0c34061-c86c-40a8-93e4-d5cb01f7bfb7">

**How to reproduce:**
1. Login to console
2. navigate to role section
3. Create application role name as "admin"

**Expected behavior:**
Since this is a application level role its should allow to delete and assign permission. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This issue occurs because the readonly roles are hard coded in the frontend [1] as the `GET scim2/v2/Roles` API doesn't return any information about the role's status (readonly or not etc). 

To fix this, the Roles API should send the editable status of each role in the API response, so that the frontend can use that property to conditionally show/hide the actions.

**Comment by chamathns** [comment]
There are a few approaches we can handle this.
1. We can remove the restriction from the frontend. This would throw an error in the backend and user would see that it is not allowed to delete that particular role. I'm +1 for this approach.
2. We can check the roles audience. From the reserved role names, f it is application level, we should be able to delete it. 
3. Having a property in the backend. This would add an unnecessary property for most of the roles created (apart from the reserved role names). If this is going to be a feature, we will have to evaluate the proposal with PM team.

**Comment by ZiyamSanthosh** [comment]
This is done. Hence closing the issue
