### ISSUE TITLE
Switching back to parent organization try to fetch the IDP of an organization.

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18048]
**Describe the issue:**

After configuring IDP of an organization, and switch back to the root organization, unnecessary IDP get request is initiated. As the token is switched to the root organization, the IDP get call will be failed to resolve the IDP by the ID as IDP is not found in that organization.

**How to reproduce:**

1 - Click on an IDP in the organization
2 - Switch back to the root organization.

https://github.com/wso2/product-is/assets/35717390/52c47800-5cda-4ac7-9466-f0928e89b3cf

**Expected behavior:**

An IDP get request should not be invoked after switching to the root organization.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0-beta]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by dasuni-30** [comment]
This issue is fixed in the new pack.

https://github.com/wso2/product-is/assets/27746285/57eec7c6-8d59-4206-b251-6a8b56e3de90


Fixed with https://github.com/wso2/product-is/issues/17675
