### ISSUE TITLE
User role section description should be updated

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18047]
**Describe the Issue:**
User roles section shows only externally added roles. But it does not indicate the role assigned to users through groups. Had discussion with @SujanSanjula96 and @AnuradhaSK  and this is expected. To improve the user experience we can update user role section description like "View externally assigned roles for the user."

<img width="1278" alt="image" src="https://github.com/wso2-enterprise/asgardeo-product/assets/39077751/c41e8da7-d974-4a7b-8159-848a4326fe8e">

**How To Reproduce:**
1. Login to console
2. Create application role adminteam
3. Create group adminteamgroup and assign adminteam role to that group
4. Create user and assign adminteamgroup to user.
5. Go to created user edit section and check the role tab

**Expected behavior:**
In role tab user will display only the "everyone" role. But with the group it has the adminteam role which is not indicate here. Since in this view it only show directly added role (not through group) better to improve the description

**Comment by JayaShakthi97** [comment]
Decided to go ahead with a Info message rather than updating the description.

Message: "User Roles assigned via Groups are not displayed here."

![Screenshot 2023-12-07 at 7 50 29 PM](https://github.com/wso2/product-is/assets/37938529/8539dbe7-8bef-49d2-80cf-a311dbaef227)

**Comment by himeshsiriwardana** [comment]
> Decided to go ahead with a Info message rather than updating the description.
> 
> Message: "User Roles assigned via Groups are not displayed here."
> 
> ![Screenshot 2023-12-07 at 7 50 29 PM](https://private-user-images.githubusercontent.com/37938529/288787034-8539dbe7-8bef-49d2-80cf-a311dbaef227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMTAzOTMsIm5iZiI6MTcwMjAxMDA5MywicGF0aCI6Ii8zNzkzODUyOS8yODg3ODcwMzQtODUzOWRiZTctOGJlZi00OWQyLTgwY2YtYTMxMWRiYWVmMjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA0MzQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTZlZmZlNzY0OWIwZTRiYWMxOGJjYmU3YjFiYzc2Y2IwYTMyYmJiYjhkNGI2MDYwNjQ2MDI2NmY1MTkyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QhTeGIG3N5sipUkPOnipXYlu8fM0qW8Rbny-tbI7_4s)


We can change the description as follows:

"View roles assigned directly to the user."

Info box - Roles inherited via groups are not shown

**Comment by JayaShakthi97** [comment]
- Improvement: https://github.com/wso2/identity-apps/pull/5011

**Comment by JayaShakthi97** [comment]
Verified in wso2is-7.0.0-beta4-SNAPSHOT

<img width="1166" alt="image" src="https://github.com/wso2/product-is/assets/37938529/0d8742b1-a66f-40ac-989e-b40995c42684">
