### ISSUE TITLE
Revisit the application role delete

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18044]
**Describe the issue:**
Currently Application roles can be delete without any warning, even though roles are assigned with applications. This need to be improved by warning the user that sustains applications using this roles or not allow to delete until the application level role assignment get removed. 

**How to reproduce:**
1. Login to console
2. Create application
3. Navigate to role tab in applicatiom
4. Create role and assign permission 
5. Navigate to the role page
6. Delete the created application role

**Expected behavior:**
A warning message or should be display regarding the application assignment or should not allow to delete until remove the application level  role assignment 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
- UX improved with: https://github.com/wso2/identity-apps/pull/4830


https://github.com/wso2/product-is/assets/37938529/4c8cacd2-3a95-4a9f-a2fe-5a3b7590d409


https://github.com/wso2/product-is/assets/37938529/40477d18-73e2-4c39-9bf0-bcb1fad57e05

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-rc1-SNAPSHOT

https://github.com/wso2/product-is/assets/37938529/ead1e5ea-d396-461c-a0e8-dd431a7f38a7
