### ISSUE TITLE
Restrict Deletion of 'Administrator' Role.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18046]
**Describe the issue:**
The current system permits the deletion of the 'Administrator' role, It should not be allowed from the console.

<img width="1211" alt="Screenshot 2023-11-22 at 17 02 01" src="https://github.com/wso2/product-is/assets/41188245/52465bea-1141-45c9-97fb-3dcc9d671a9f">

**How to reproduce:**

1. Navigate to the Roles page
2. Find that the Delete option is available for the Administrator role.

**Expected behavior:**
The Delete option should not be there in the UI.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
@sadilchamishka @thanujalk Do we need to restrict this from the FE level? AFAIR, this role is getting created again even if we disable?

**Comment by sadilchamishka** [comment]
> @sadilchamishka @thanujalk Do we need to restrict this from the FE level? AFAIR, this role is getting created again even if we disable?

This role gets created at the 1st server startup and not again. Not sure whether it is created again. Did you noticed that kind of behaviour. Btw we are planning to block that role deletion from the BE level.

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

<img width="1506" alt="Screenshot 2023-11-29 at 10 40 16" src="https://github.com/wso2/product-is/assets/41533942/ddf7ec5d-5f43-4ba1-adcc-e9620cfaf1f2">
