### ISSUE TITLE
Contradicting UIs when creating an application role without an application

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#18043]
**Describe the issue:**
When you try to create an application role without an application, a dropdown to select the application is shown with no applications for the first time since the default role audience is selected as application. If you change the audience to organization and come back to application, it shows a different warning message to create an application and the application dropwdown is now hidden.

https://github.com/wso2/product-is/assets/50801227/f4651e26-40dc-43de-80bf-24e6e045c08c

**How to reproduce:**

1. Login as admin
2. Create a new role
3. Notice the UI when it is selected audience as application.
4. Change to organization type and change audience to application once again. Different warning message will be visible.

**Expected behavior:**
The warning message to create an application should be displayed in the first time as well. Also the application dropdown should be hidden as well.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
