### ISSUE TITLE
SMS OTP can not be configured as first factor

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18058]
<img width="1386" alt="image" src="https://github.com/wso2/product-is/assets/12690906/0c2eabb7-ce66-46ef-9dfe-93ac8b16f0e0">

**Comment by AnjanaSamindraPerera** [comment]
**Flow is tested using below steps:** 

1.  Create a user. Add a mobile number to him. This number also will be used in the latter stages.
2.  Go to the application and create an app. Then add SMS OTP as the first factor or use it as the second factor.
3. Then you need to create a [Twillo](https://www.twilio.com/en-us/messaging/channels/sms) account. Use your email and the mobile number used in step 1.
4. Then you will have 15.5$ worth sms sending capability. To use this service copy the Account SID, Auth Token, and My Twilio phone number given by Twillo to the Email & SMS configuration in the IS console.
5. Try to log in to the created app using the user we created in step 1.
