### ISSUE TITLE
[Blocker] User store does not behave as expected when it is created through admin service with only mandatory parameters

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1805]
Type: Bug
Priority: Highest
Severity: Blocker
Release: wso2is-5.4.0-update1

User store does not behave as expected when it is created through addUserStore admin service with only mandatory parameters.

**Steps**
1. Create a JDBC secondary user store successfully via admin services
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://dto.configuration.store.user.identity.carbon.wso2.org/xsd">
   <soap:Header/>
   <soap:Body>
      <xsd:addUserStore>
         <!--Optional:-->
         <xsd:userStoreDTO>
            <!--Optional:-->
            <xsd1:className>org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager</xsd1:className>
            <!--Optional:-->
            <xsd1:description>created with admin services</xsd1:description>
            <!--Optional:-->
            <xsd1:disabled>false</xsd1:disabled>
            <!--Optional:-->
            <xsd1:domainId>PRIMARY-JDBC780-ATTRIBUTE-STORE</xsd1:domainId>
            <!--Zero or more repetitions:-->
            <xsd1:properties>
               <xsd1:name>url</xsd1:name>
               <xsd1:value>jdbc:mysql://localhost:3306/is520user</xsd1:value>
            </xsd1:properties>
            <xsd1:properties>
               <xsd1:name>userName</xsd1:name>
               <xsd1:value>wso2carbonxxx</xsd1:value>
            </xsd1:properties>
            <xsd1:properties>
               <xsd1:name>password</xsd1:name>
               <xsd1:value>wso2carbonxxx</xsd1:value>
            </xsd1:properties>
            <xsd1:properties>
               <xsd1:name>driverName</xsd1:name>
               <xsd1:value>com.mysql.jdbc.Driver</xsd1:value>
            </xsd1:properties>       
            <xsd1:properties>
               <xsd1:name>CountRetrieverClass</xsd1:name>
               <xsd1:value>org.wso2.carbon.identity.user.store.count.jdbc.JDBCUserStoreCountRetriever</xsd1:value>
            </xsd1:properties>  
         </xsd:userStoreDTO>
      </xsd:addUserStore>
   </soap:Body>
</soap:Envelope>
```
2. Try to add a user to the created user store

**Issue**
Error message will say the password length does not match even though it is matched. 
![16](https://user-images.githubusercontent.com/1845370/34198766-8df01c64-e591-11e7-8981-b74637bf0e8d.png)

The issue is the request does not handle the other optional parameters such as username/password regex and other db queries internally when the request is sent. Without those optional parameters there is no use of the created user store. Note, that there are around 100 optional parameters if the user has to create a user store via admin services and it is not practical from users perspective. Therefore, this blocks the automation of user store creation for scenario 27 of [1].

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by dilinisg** [comment]
Mail thread : [IAM] User store does not behave as expected when it is created through admin services with only mandatory parameters

**Comment by dilinisg** [comment]
Same applies to ReadWriteLDAP user store

**Comment by dilinisg** [comment]
@wso2/is-doc-team - A complete sample/request to create JDBC and other user stores needs to be included in the document ASAP for us to continue automation

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
