### ISSUE TITLE
Add semantic search capability to attribute search

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18056]
**Is your suggestion related to an experience ? Please describe.**

yes

**Describe the improvement**

In the attributes page, users may not always know the exact phrase to search to find a certain attribute, therefore users may have a hard time finding the attribute they need.

If there was a semantic search capability, the application will be able to produce a list of attributes that are more semantically similar to the search phrase.

Eg; When a user searches with the phrase "fullname", the search results should show the "Full Name" attribute in the search results.

**Additional context**

N/A

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
