### ISSUE TITLE
No option to delete attribute mapping collections(i.e claim dialtects) in Console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18050]
**Describe the issue:**

- Create a new attribute mapping (i.e claim dialect)
- UI doesn't have any option to delete the created dialect
- If you check the old management console, there is an option to delete them

expected: - User should be able to delete the custom-defined dialects 

https://github.com/wso2/product-is/assets/25483865/c7654fd9-b719-4543-a553-dbce27b2e987

**Comment by pavinduLakshan** [comment]
Verified the fix in the latest build.

https://github.com/wso2/product-is/assets/41533942/a93841e2-4b07-4140-b08f-bfc5068e66cc
