### ISSUE TITLE
User account suspension: Configure account suspension for an user in secondary user store

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1806]
In [1] there is a specific configuration with relevant to the user store and instructions for the LDAP and JDBC is given which is done in user-mgt.xml. Since secondary user store configuration is not in user-mgt.xml please mention specific steps when configuring in secondary user store

[1] https://docs.wso2.com/display/IS540/User+Account+Suspension

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
