### ISSUE TITLE
Confusing UX in standard connection disable section

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18068]
**Describe the issue:**

Even when the connection status is received as enabled, the UI gives an impression that the connection is disabled.

https://github.com/wso2/product-is/assets/41533942/bf406df7-9954-4b18-ad14-3df4db00c46f

**How to reproduce:**

1. Login to console.
2. Create a standard connection.
3. Go to General section and scroll down to disable connection section.

**Expected behavior:**

The UX should be improved to correctly convey the enabled/disabled status.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
