### ISSUE TITLE
OIDC scopes are missing in the new Console

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#18063]
**Describe the issue:**
$subject
This has been available in 7.0.0-alpha pack under User Attributes & Stores

![Screenshot 2023-11-24 at 10 14 01](https://github.com/wso2/product-is/assets/25428696/d6b6535d-abd8-4162-924b-397354ccceaf)

In 7.0.0-beta, this is missing from the UI.
![Screenshot 2023-11-24 at 10 14 28](https://github.com/wso2/product-is/assets/25428696/40baf2f4-2658-44a5-84fe-aaf26a87e0cb)

**Comment by chamathns** [comment]
![Screenshot 2023-11-24 at 10 22 55](https://github.com/wso2/product-is/assets/25428696/07fdd6ba-4ea5-4a25-9023-0eb977341fb5) 

This has been moved under "scopes" in Attributes -> Open ID Connect

We may need to update the documentation to reflect this.

cc: @himeshsiriwardana @AnuradhaSK

**Comment by Rashmini** [comment]
Fixed with https://github.com/wso2/docs-is/pull/4217
