### ISSUE TITLE
Oracle database related Issues

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#18079]
**Describe the issue:**
> $subject

### Related Issues

- [Encountering permission issues for admin login to console with Oracle DB configured in IS. #18210](https://github.com/wso2/product-is/issues/18210)

**Comment by aaujayasena** [comment]
Please update the current status of this issue @Sachin-Mamoru

**Comment by Sachin-Mamoru** [comment]
With the following fixes I was abled to start up the pack with oracle without any issues.

> * https://github.com/wso2/product-is/issues/17974
> * https://github.com/wso2/product-is/issues/17903

Now we need to test the beta2 pack with oracle and if any issues occured those should be reference this issue. Then we can analyse the oracle related issues in one place.

@hasanthiP will assign a person to analyse the further issues on IS with oracle

**Comment by DMHP** [comment]
@NilukaSripalim @melanisilva please consider testing the latest version with oracle and check the compatibility.

**Comment by DMHP** [comment]
@NilukaSripalim Please create a new issue for testing purposes.
