### ISSUE TITLE
Console application's role permission can't be edited from `Console Settings` -> ` Roles` section

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18071]
**Describe the issue:**
- Go to  `Console Settings` -> ` Roles`
- Create a role with few permission
- Click on the crated role
- Go to permissions section
- Can't change the permissions
- If you go to `User Management` -> `Roles` -> created role's permissions, you can edit the permissions

https://github.com/wso2/product-is/assets/25483865/8ccbc039-2de5-4aab-9608-fb12c1c11a45

Expected Behavior:
Permission for editing should be possible from the view
`Console Settings` -> ` Roles` -> selected role permission

**Comment by brionmario** [comment]
As per an offline discussion with @thanujalk, it was decided to keep this as a limitation.
Since there's no way to have a mapping with the created role response and the resource collections.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
