### ISSUE TITLE
`Next` button is not working for secondary user store user listing 

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#18078]
**Describe the issue:**
> $subject

**How to reproduce:**
1. Configure a secondary userstore
2. Add 15(more than the pagination number) users to that userstore.
3. Retrieve the users of that user store from the users page.

![image](https://github.com/wso2/product-is/assets/75057725/654bedc1-e6d0-426f-8a8a-68686268e40a)

**Expected behavior:**
1. Should be able to navigate to next page to see the other users.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 7.0.0 beta]
 - OS: [Mac]
 - Database: [MySQL]
 - Userstore: [JDBC]

---

**Comment by DonOmalVindula** [comment]
Analyzed the issue with @ashanthamara and found it was an issue with a corrupted user object and not related to the product. Hence closing the issue.
