### ISSUE TITLE
Unable to add both read and write permissions on Console role creation

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18070]
**Describe the issue:**

- Go to Console Settings -> Roles 
- Create a role by giving a name and selecting an API
- From the selected API select the "Write" button
- It will add Create, update, and delete permissions. "Read" permission is not added 
- We can't select both Read and Write for given API as well

https://github.com/wso2/product-is/assets/25483865/68bf7f2c-3cb4-4ea7-b185-45fec847fd5c

Expected behavior:
- [x] Rename `Read` -> `View` and `Write` -> `Edit`
<img width="713" alt="Screenshot 2023-11-24 at 11 45 00" src="https://github.com/wso2/product-is/assets/25483865/acf3eb39-8740-4a1d-bac1-2a49c515eadd">

- [x] If user selects the `Edit`, "read", "create", "update" and "delete" permissions should be selected

**Comment by brionmario** [comment]
Decided to rename the terms based on an offline discussion:

- read -> `View`
- write -> `Edit`
