### ISSUE TITLE
"sub organization" term is still used in error messages shown on UI

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18081]
**Describe the issue:**

1. Login to root tenant
2. create an organization with the name "org1"
3. Try to create another org with same name.

<img width="576" alt="Screenshot 2023-11-25 at 13 59 37" src="https://github.com/wso2/product-is/assets/25483865/1e245e5c-dde7-4144-a206-1bc7416723f4">

https://github.com/wso2/product-is/assets/25483865/bb143aff-f519-4383-b8b1-5c8e45d7bc7f

"suborganization" term should be changed to "organization" everywhere in the UI
Check other possible error messages as well

**Comment by JayaShakthi97** [comment]
Found another place.
- Assign email domains page

![image](https://github.com/wso2/product-is/assets/37938529/4a27d0de-8045-4e18-ab07-818c2a3f0e47)

**Comment by JayaShakthi97** [comment]
- Wording updated: https://github.com/wso2/identity-apps/pull/4824

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-rc1-SNAPSHOT

<img width="600" alt="image" src="https://github.com/wso2/product-is/assets/37938529/b50b8713-5da2-464a-8210-4837e4086dee">

<img width="821" alt="image" src="https://github.com/wso2/product-is/assets/37938529/09edf8b7-f608-4709-8f4b-2b101f9ac7da">
