### ISSUE TITLE
Improve the selected role displaying view under manually adding multiple users

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18087]
**Describe the issue:**
1. Enable the "invite user to set the password" in carbon.super tenant (need to do this via mgt console in the beta pack. Since the config is not available in new UI)
2. Login to console. Go to User Management -> Users -> Select Multiple user option
3. Select few roles
<img width="1114" alt="Screenshot 2023-11-27 at 06 19 35" src="https://github.com/wso2/product-is/assets/25483865/65f7fc58-cf89-4f4e-918e-0ac34bd42495">
Once a role is selected it is shown as `<role name>:<role audience type>` This is not a clear representation.

Instead, it would be better to show just the role name in the input field and show other information on a card. When the role audience is an application, the application name is also required to be shown.

Example for showing more details on a card:
- Assign users to a role. The user's username is displayed. userstore domain kind of information is available on the card info

https://github.com/wso2/product-is/assets/25483865/9ad0d9bf-0544-48d8-8ec5-585bf6644b27

**Comment by dasuni-30** [comment]
### Suggested Design 01

Discussion in UX Thread: https://chat.google.com/room/AAAALlrrsT0/tZqzeX2oSRo/

- Added the Role Name and Role Audience as the title and subtitle of the menu item.
- Updated the chip to display Role Name, Role Audience, and App/Org name.

![new](https://github.com/wso2/product-is/assets/27746285/ee7e9851-4e1c-4e17-ad26-4294e47d8915)

**Comment by dasuni-30** [comment]
**Final Design**

Meeting Notes: https://docs.google.com/document/d/1Q5DozDfve5zN7daqnfoISy5TSsh3zs_Io3Taw6i0HI4/edit#heading=h.2b7edbuglwxm

<img width="1440" alt="Screenshot 2023-12-01 at 13 34 27 (1)" src="https://github.com/wso2/product-is/assets/27746285/f9361af6-3947-4ad4-a418-b937243ba0c1">

**Comment by dasuni-30** [comment]
The above roles dropdown will be replaced with the groups down and hence the above roles dropdown changes are not needed. The Roles chip changes are addressed with https://github.com/wso2/identity-apps/pull/4937

**Comment by dasuni-30** [comment]
Verified in the new pack
