### ISSUE TITLE
[Blocker] Cannot update a user store via admin services

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1808]
Type: Bug
Priority: Highest
Severity: Blocker
Release: wso2is-5.4.0-update1

**Steps**
1. Create a user store via admin services
2. Update the same user store via admin services
![17](https://user-images.githubusercontent.com/1845370/34199696-a1bb5742-e594-11e7-8943-acc02532695a.png)

**Issue**
`Exception occurred while trying to invoke service method editUserStore` error message is returned to the user. No error in the IS side, but shows that the user was authenticated through logs. So cannot update user stores

`[2017-12-20 14:24:05,262]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@carbon.super [-1234]' logged in at [2017-12-20 14:24:05,261+0530]`

Note: User store creation request successfully works

**Comment by thanujalk** [comment]
First, you need to get the _UniqueId_ property of the secondary user-store using _getSecondaryRealmConfigurations_ method
Then you can call the _editUserStore_ method with that property.
<img width="1217" alt="screen shot 2018-03-01 at 2 43 05 pm" src="https://user-images.githubusercontent.com/1498339/36836342-0b263b32-1d5f-11e8-8c4b-936eb1e5ca4f.png">

**Comment by dilinisg** [comment]
This is not mentioned in the docs. Therefore please document the flow. So, reopening the issue.

**Comment by sherenewso2** [comment]
@thanujalk do we need to use the _UniqueID_ property when using the deleteUserStore() and changeUserStoreState() as well?

**Comment by sherenewso2** [comment]
Fixed in versions 5.5.0 - 5.8.0 [1] 

[1] https://docs.wso2.com/display/IS580/Managing+User+Stores+with+APIs#ManagingUserStoreswithAPIs-editUserStore()
