### ISSUE TITLE
Multiple API permission selection during role creation under Applciation->Roles tab is not clear

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18084]
**Describe the issue:**
1. Create an application
2. Authorize to few APIs by going to the application's "Authorize API" tab
3. Go to the Roles tab of the application. select the application audience
4. Try to create a role by selecting permissions from multiple APIs.
5. Once you assign permission from one API, and try to select another API the first one will disappear. Feels like only one API's permissions can be assigned. But when you check on the created role, the selected permissions of multiple APIs were added to the role.

https://github.com/wso2/product-is/assets/25483865/97cb88de-f958-4243-82f8-9e65542c520c

If you check the permission assignment of role creation under User Management -> Roles, it clearly shows the selected APIs and permissions

https://github.com/wso2/product-is/assets/25483865/bf632bcf-9d6c-4b3c-b890-1dd381f83898

**Comment by JayaShakthi97** [comment]
- Fix: https://github.com/wso2/identity-apps/pull/4820

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-rc1-SNAPSHOT

https://github.com/wso2/product-is/assets/37938529/1487bacf-8871-4987-b9c9-2e3eafe8aaef
