### ISSUE TITLE
Confusing action confirmation section in USERSTORE delete confirmation message box.

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#18089]
### **Describe the issue:**
When deleting a USERSTORE, it pops up a message box for the confirmation of the action. And in that message box, it asks the user to proceed the action by typing the userstore name. But in the message box it is not properly mentioned (what to enter in that box to proceed with the deletion)

![image](https://github.com/wso2/product-is/assets/75057725/3d64fe66-5cd0-4635-b45d-34cb9d546d3a)

### **How to reproduce:**
1. Configure a secondary userstore.
2. And try to delete it.

**Expected behavior:**
Content in the message box should be clear to proceed with the deletion

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 7.0.0]
 - OS: [e.g., Mac]
 - Database: [e.g., MySQL]
 - Userstore: [e.g., LDAP]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
