### ISSUE TITLE
Change Sign In With Ethereum to a Pluggable Connector

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#18095]
**Describe the issue:**
$subject
As of now, we have the SIWE as a starting template when we try to create a connection.

<img width="1728" alt="Screenshot 2023-11-27 at 13 09 35" src="https://github.com/wso2/product-is/assets/25428696/5baec135-1141-4afe-b4ae-9578b4ec0e02">

This should be available as a connector for the user to configure.

**Comment by chamathns** [comment]
This jar is not available in the drop-ins folder, however, it is being populated in the UI as above.

cc: @NipuniBhagya @jeradrutnam

**Comment by aaujayasena** [comment]
<img width="1397" alt="image" src="https://github.com/wso2/product-is/assets/39077751/140eb445-3d59-4f88-9576-fdc6fb17702e">
For me this is not reproducing.  @chamathns

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
