### ISSUE TITLE
User Account Suspension: Values for "Alert User in" configuration

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1809]
As per [1] user can be alerted repetitively within given time periods until the account lock period occurs. 

1. What will happen if the admin does not specify any value here?
2. What will happen if the admin specifies a larger value than the account lock period here?
3. What will happen if the admin specifies a single value which is less than the account lock period here?
4. What will happen if the admin specifies a single value that is the account lock time here?

Please include these information in the documentation

[1] https://docs.wso2.com/display/IS540/User+Account+Suspension

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
