### ISSUE TITLE
Permission assignment to role in same Tenant API and organization API can't be distinguished 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18090]
**Describe the issue:**
1. Go to User Management -> Roles
2. Create new role. Give a role name, select organization as the role audience
3. Select SCIM User API at the tenant level and organization level. During the selection, you can see the separation.
4. But at the state of multiple API permissions selected before completing the action, there is no info to distinguish the API. (If an API permission is hovered only you can identify)

<img width="1010" alt="Screenshot 2023-11-27 at 09 49 09" src="https://github.com/wso2/product-is/assets/25483865/8c2e7bbf-7cd4-4181-ba2e-cba8b03d92fc">

5. Once the role is created, go to the created role's permission section. The same issue exists there too.

<img width="1107" alt="Screenshot 2023-11-27 at 06 41 23" src="https://github.com/wso2/product-is/assets/25483865/c4b5036e-a3c4-4218-b6b7-f22741f076c6">

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR
- https://github.com/wso2/identity-apps/pull/4898
