### ISSUE TITLE
Account lock: account of the super admin is also subjective to locking

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1810]
The super admin account is also subjective to be locked. In real world use case is it practical to lock the super admin account? Shouldn't the super admin be exempted of account lock?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
