### ISSUE TITLE
Email template footer can not be empty

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#18102]
**Describe the issue:**
It does not allow keeping the footer empty in email templates. The Console has a UI validation and carbon managament console throws an error if user tried to keep footer blank and update. But there could be valid cases where a footer is not required. For example, the default email templates also does not include a footer and just `---` are added. So it is visible in the emails sent out.

Note the `---` at the left bottom corner.
<img width="629" alt="Screenshot 2023-11-27 at 5 33 59 PM" src="https://github.com/wso2/product-is/assets/719073/4ff5cf4a-65f8-4e53-b6cb-155191ee3e44">

**Workaround:**
Use following in the footer
```
<!--  -->
```

**Environment information** 
 - Product Version: Any

**Comment by ashanthamara** [comment]
Closing since the changes are deployed in the product-is
