### ISSUE TITLE
Account lock: Wrong error message is given when a user account is locked

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1811]
After unsuccessful login attempts when the account is locked, when trying to login from the correct credentials the following error message is given in both the management console and dashboard. This should change to reflect the state the account is currently in

![is_issue_14](https://user-images.githubusercontent.com/15624590/34200365-d61899a8-e596-11e7-8d20-f1fceeea0318.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
