### ISSUE TITLE
Accumulation of database connections corresponding to the 2ndry user store datasources.

### ISSUE THREAD

**Issue by pandukakarunasena** [wso2/product-is#18118]
During the analysis, it was observed that there are multiple data source object initialization for the object[1] based on the expiration of the cache 'DefaultRealmCacheTimeout'

Because of this new object creation each time a new connection pool also will be created, But the connection pool will not be removed due to the existing reference from the tomcat level even if we have dumped the object that was used to create the connection pool. The references for the connection pool are relevant to the connection pool clean-up tasks.

As per the book clean-up tasks, it seems the Tomcat is not expecting to create multiple data sources for one data source as the Identity Server has done by creating new Datasource instances by creating new objects[1].

This can be easily observed by reducing the 'DefaultRealmCacheTimeout'.

As per my understanding following will be the options to resolve the connection pool accumulations.

Change the codebase to use the same object[1] without initializing it multiple times. - This will be the ideal solution.

Please check [2] for the fix available in the user core in APIM 2.6.0

[1] https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L102
[2] https://github.com/wso2/api-manager/issues/781

Steps to Reproduce

- Configure DefaultRealmCacheTimeout in deployement.toml to a lesser value
- Create a tenant and configure a secondary user store (JDBC)
- Do a database operation ( Invoke password grant, Login, Loading user profile, Logout... ).
- Wait for the DefaultRealmCacheTimeout
- Redo a database operation ( Invoke password grant, Login, Loading user profile, Logout... )
- Monitor the connections IS is making to the database, it's increasing and stays without dropping.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0.239
 - Database: Postgres, Oracle 12c
 - Userstore: JDBC

---

**Comment by cgchamath** [comment]
What is the ETA for the fix for this? It seems APIM 3.2 and 4.1 need this for customer issue.

**Comment by madurangasiriwardena** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/3746
