### ISSUE TITLE
When IDP connection creation, image URL are generated differently for embedded console and static console.

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18119]
**Describe the issue:**

 There is an UI issue where, the IDP image URL is differently set for two different cases.
When accessing console with port 9443 default mode, when creating a connection (ex- standard based IDP), the image URL is set to an absolute path. When accessing the console in developer mode 9001, when creating a connection, the image URL is set to a relative path. Due to this, the logo resolving fails for the connections created for the IDP created by developer mode.

Absolute path
<img width="906" alt="Screenshot 2023-11-27 at 19 41 36" src="https://github.com/wso2/product-is/assets/35717390/10b0897e-98f9-4f3e-93e3-ffbdc3bac57b">

Relative path
<img width="922" alt="Screenshot 2023-11-27 at 19 42 05" src="https://github.com/wso2/product-is/assets/35717390/043eff2e-1d78-4607-938f-ca69025d2490">

The issue for the relative path is, there is no image with the name `enterprise.svg`, but there is `enterprise-idp-illustration.svg`

1 - We will have to define what is the correct way of image URL resolving. For tomcat deployed console & static console deployment, whether relative/absolute or both for each type to be used.
2 - Whether the image file name to be renamed.
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
