### ISSUE TITLE
Alignment issue in Sign In With SSO button

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#18122]
<img width="587" alt="Screen Shot 2023-11-28 at 11 35 36 AM" src="https://github.com/wso2/product-is/assets/24982871/0e0c3e5b-68ef-406b-8cd8-1db41c16b661">

**Comment by ChanikaRuchini** [comment]
Discussed this issue with the UX team. According to them, the previous text was center-aligned. However, when the authenticator names are lengthy, there were some alignment issues. Therefore, they decided to left-align the text.
