### ISSUE TITLE
There is no option to select the userstore when creating a single user

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18135]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/10ac09fa-1b5d-4440-8a74-7cea6f9c760a)

**How to reproduce:**
Create a new userstore. (JDBC)
Try adding a new user to the new userstore

**Expected behavior:**
Should be able to choose to which userstore the user should be added.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
This is already fixed in the latest console version
