### ISSUE TITLE
Alignment issue when selecting permissions(scopes) from the selected API resources

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18131]
**Describe the issue:**
Alignment issue

<img width="631" alt="Screenshot 2023-11-28 at 13 53 19" src="https://github.com/wso2/product-is/assets/39077751/0955e0ec-41b1-4af1-bb7e-d060c4c2e6a8">

**How to reproduce:**
1. Create application
2. Authorise API
3. Add role
4. Assign permission for the role 

**Expected behavior:**
No alignment issue 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by malithie** [comment]
These issues breaks the first the impression on quality given this is is a primary flow. Thus, changed the severity to critical
