### ISSUE TITLE
Cannot delete user store sets via admin services

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1813]
Type: Bug
Priority: Highest
Severity: Critical
Release: wso2is-5.4.0-update1

**Steps**
1. Try to delete multiple user stores at once using deleteUserStoresSet admin service (user stores are created via admin services as well)
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://org.apache.axis2/xsd">
   <soap:Header/>
   <soap:Body>
      <xsd:deleteUserStoresSet>
         <!--Zero or more repetitions:-->
         <xsd:domains>PRIMARY9000-ATTRIBUTE-STORE,PRIMARY-JDBC78056-ATTRIBUTE-STORE</xsd:domains>
      </xsd:deleteUserStoresSet>
   </soap:Body>
</soap:Envelope>
```

**Issue**
A successful response will be returned, but the user stores will not be deleted. No error in the backend
![18](https://user-images.githubusercontent.com/1845370/34200780-54287a06-e598-11e7-82e7-d4a2c616e07b.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
