### ISSUE TITLE
Remove `Custom` from the notification provider configuration heading

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18146]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/9fe30835-31bd-472c-9655-a6bc6e86eee9)

![image](https://github.com/wso2/product-is/assets/5061791/2c725e55-5870-47cc-a44c-f4f25377ace1)

There is no reason to mention these providers as `Custom`

**How to reproduce:**

**Expected behavior:**
Remove custom from the heading.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
New UI would look like follows.

![image](https://github.com/wso2/product-is/assets/41533942/be014af5-acd4-4d6c-a7cb-249a41b1a034)
