### ISSUE TITLE
There is no support for creating multiple users in a secondary userstore from console

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18145]
**Describe the issue:**
Unable to specify to which user store the users should be onboarded.

![image](https://github.com/wso2/product-is/assets/5061791/daeb33ee-7056-4ebe-bc2e-d3443e8d6ae4)

And it's hard wired to onboard multiple users only to the primary userstore

**How to reproduce:**
Add a new userstore
Try creating multiple users from the console

**Expected behavior:**
Should be able to specify to which userstore the users are to be onboarded.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
We tested file-based bulk user import with the remote user store and encountered some issues. We discussed limiting this functionality in  IS to maintain consistency. Hence we need to properly test and give the capability to IS if we are giving the functionality.
cc: @PasinduYeshan @AnuradhaSK

**Comment by PasinduYeshan** [comment]
Following our offline discussion, the decision has been made to enable the secondary userstore option in the Identity Server and disable this option in cloud deployment.

**Comment by PasinduYeshan** [comment]
This issue if fixed from following PR. 
- https://github.com/wso2/identity-apps/pull/4955
