### ISSUE TITLE
Group list view contains items from all userstores even Primary userstore is selected by default

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18140]
**Describe the issue:**

![image](https://github.com/wso2/product-is/assets/5061791/f5eaa7d1-0d70-4a9c-8c47-9eb731da1a3e)

**How to reproduce:**
Create a new userstore and add some groups
Access groups section list view
The very first time the list contains the items from the secondary userstore as well

**Expected behavior:**
Only groups from the primary userstore(Selected userstore)  should be queried and listed here.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashanthamara** [comment]
Tested with console version `2.9.36`. Issue is resolved.
(plugged secondary userstore type: MYQL JDBC Read/Write)


https://github.com/wso2/product-is/assets/75057725/f2d3035d-37cc-4e06-bd27-2da1abf8f296

**Comment by DonOmalVindula** [comment]
Closing as it's done - https://github.com/wso2/product-is/issues/18140#issuecomment-1835913167
