### ISSUE TITLE
[Doc] Add sample value for the 'Scope' when adding Github as an IDP

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1814]
8th step under 'Configuring the identity provider' section in [1] contains samples values for fields which needs to be filled when configuring Github as an IDP. But for the field 'Scope', there's no sample value.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Github+Authenticator#ConfiguringGithubAuthenticator-ConfiguringtheidentityproviderConfiguringtheidentityprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
