### ISSUE TITLE
Stop giving first level support for `ELK Analytics`

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#18141]
**Is your suggestion related to an experience ? Please describe.**

ATM, we are giving first level support to `ELK Analytics` but that is only useful for the `ELK-Risk-Based` adaptive auth template.
<img width="2039" alt="Screenshot 2023-11-28 at 15 21 08" src="https://github.com/wso2/product-is/assets/25959096/693a6fed-7201-4c7c-b6d2-b6e104fd7047">

**Describe the improvement**

We should remove the first level support and move it along with the `ELK-Risk-Based` adaptive auth template.

Suggestion:

<img width="1692" alt="Screenshot 2023-11-28 at 15 23 43" src="https://github.com/wso2/product-is/assets/25959096/e538a829-82c8-430a-866a-58b72d534521">

**Additional context**

- Remove the feature config from `deployment.config.json`
- Remove related routing configs and other stale files after the refactor

**Comment by savindi7** [comment]
A rough idea of the experience delivered with this improvement is illustrated below.
cc - @brionmario @ashensw 

![image](https://github.com/wso2/product-is/assets/67315176/261c0027-d674-44b8-b874-6250232ce48b)

**Comment by malithie** [comment]
Changed the priority as the current UX give the wrong idea on the capability
