### ISSUE TITLE
Inconsistent UX and options in the single user and multiple user creation flows

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18143]
**Describe the issue:**
Unable to select the userstore when multiple user creation option is selected

When adding a single user the steps consists of adding a user with group(s)

![image](https://github.com/wso2/product-is/assets/5061791/54699408-a1ce-4ea1-a31d-e1f844ce2309)

When adding multiple users the steps consists of adding a user with role(s)

![image](https://github.com/wso2/product-is/assets/5061791/8493acf9-a262-4e45-a360-13deef193173)

Role and Groups are two different types of collections, but they are presented in one group in multiple user addition flow.

![image](https://github.com/wso2/product-is/assets/5061791/93fc6095-37a1-4f6e-b266-c55a007fd9cb)

**How to reproduce:**
There should be an options to select the userstore when adding multiple users in bulk
Try add new user flows from the console.

**Expected behavior:**
Both single-user creation and multiple user creation should have same UX and end up the created accounts in similar states

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
- [ ] Replace the Roles dropdown with the Groups dropdown
- [ ] Change the precedence of emails and group input fields
- [ ] Change the Role/Group Assignment to Groups
- [ ] Update the content related to Roles/Groups Assignment

PR: https://github.com/wso2/identity-apps/pull/4937

**Comment by dasuni-30** [comment]
### Verified in the new pack

https://github.com/wso2/product-is/assets/27746285/ac9fc491-6e41-4924-bdff-03d435fb81e4
