### ISSUE TITLE
Error when retrieving datasource configurations.

### ISSUE THREAD

**Issue by pandukakarunasena** [wso2/product-is#18148]
**Describe the issue:**
When initializing a datasource the pool properties are read[1]. However, the configured pool configurations are not properly assigned to the datasource because of failing the condition in [2]. This can be observed in several places. All the places which have the mentioned issue should be fixed.

**How to reproduce:**

- Set up a secondary user store.
- Change/Add the INITIALSIZE of the pool configs.
- Observe if the INITIALSIZE changes.
- As the above-mentioned condition[2] fails the default JDBC pool INITIAL SIZE will be assigned,

**Expected behavior:**
Proper datasource configurations should be honored when initializing the database.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0, IS 5.10.0]
 - Userstore: [JDBC]

---
[1] https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/util/DatabaseUtil.java#L346
[2] https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/util/DatabaseUtil.java#L444

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
