### ISSUE TITLE
The retrieval clients service URL building logic should be improved for organization resource accesses

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18155]
**Describe the issue:**
The existing retrieval clients service URLs are build with an organization qualifier. But the organization qualifier for IS resource access is restricted. Hence the internal API calls for meta data retrieval should follow tenant qualified paths.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0-beta2]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by malithie** [comment]
What's the impact of above ?

**Comment by sadilchamishka** [comment]
> What's the impact of above ?

For an example, if authentication portal is hosted outside, while the authentication flow, the IDP logo retrieval would be done by invoking the IDP metadata endpoint in the IS. In order to retrieve those metadata, the IDP GET API is called via a client authentication mechanism.  Currently those request URLs are build with an organization qualifier `/o/<org-id>/api/server/v1/identity-provider/..`
We have defined a mechanism for tenant/organization resource/runtime API access  at the moment. 
- Accessing resources and runtime APIs in tenant ->  `/t/<tenant-domain>/api/server/v1/identity-provider`  &  `/t/<tenant-domain>/oauth2/token` 
- Accessing resources in org. -> `/t/<tenant-domain>/o/api/server/v1/identity-provider`
- Invoking runtime APIs -> `/o/<org-id>/oauth2/token`

In order to comply as much with above, the effort of this issue is to build the URL in the format of
`/t/<tenant-domain>/api/server/v1/identity-provider` where the tenant-domain is the tenant related for the organization(sub-org). 

Ideally the above URL should have been build as `/t/<tenant-domain>/o/api/server/v1/identity-provider` and invoked with organization bound token. But the client authentication mechanism having at the moment is not match with that.

As a summary, the effort is for avoiding URLs build with prefix with `/o/..`. The given solution is not the optimal way but a workaround, where tenant domain and org-id is assumed to be equal (at the moment it is equal for orgs), and replace `/o/` with `/t/`. Also, These calls are back channel calls.
