### ISSUE TITLE
Invite user to set the password option is always disabled in UI

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18151]
**Describe the issue:**
1. Go to Login & Registration > Invite User to Set Password > Check Enable user email verification
2. Go to User Management > Users > click +Add User . Then select single-user
3. Still the Invite user to set the password option is disabled

https://github.com/wso2/product-is/assets/25483865/b6ced96e-1e3d-45c0-9b7b-5b394c1c3d4b

**Comment by DonOmalVindula** [comment]
This is already fixed with the latest console version
