### ISSUE TITLE
[Doc]TenantMgtAdminService should be one word in doc.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1816]
TenantMgtAdminService should be one word in doc [1]

[1] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs

This section guides you through invoking and working with the **Tenant ManagementService** and the operations you can work with in this service.

Fix the same in here as well. Check the below statement. 
The following operations are available in the **TenantManagement Service:**

TenantManagement Service should be one word.

This is not searchable within doc space since this is not one word

**Comment by ShirazAzad** [comment]
Fixed. Updated the docs [1] and [2]
[1] https://docs.wso2.com/display/IS530/Managing+Tenants+with+APIs
[2] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs
