### ISSUE TITLE
Refactor the temporary fix to `hasRequiredScopes` function

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#18160]
**Issue Description:**
The hasRequiredScopes function is designed to verify if a user possesses the required scopes to execute a specific action. Currently, the function takes both the user's scope list and the scopes needed for the action. Due to recent changes related to sub-organizations, there was a temporary modification to replace "internal_" with "internal_org_" in a sub-organization.

**Expected Behavior:**
It's recommended to adjust the function to receive only the organization type and the scopes list (allowed and user's scopes) for better functionality, eliminating the need for temporary alterations.

**Related PR's:**
- https://github.com/wso2/identity-apps/pull/4368

**Comment by brionmario** [comment]
Need to add an additional arg to the `hasRequiredScopes` function and let Typescript break the build and add the arg in the places where `hasRequiredScopes` is used.
