### ISSUE TITLE
Intermittently an error is displayed when navigating to the Permissions tab of a role

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#18168]
<img width="1434" alt="Screen Shot 2023-11-29 at 11 41 53 AM" src="https://github.com/wso2/product-is/assets/24982871/4c04290b-faa2-4a1b-af33-165bb2ce8cb1">

IS pack built on 29/11/2023

Seems like this happens when API resources exist for the role

**Comment by dasuni-30** [comment]
Duplicate Issue: https://github.com/wso2/product-is/issues/18039

This will be fixed with https://github.com/wso2/product-is/issues/18039
