### ISSUE TITLE
Internal_hostname is not Honored in identity-apps

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#18163]
**Describe the issue:**

- It's expected to use the hostname configured in `internal_hostname` for every internal communication. Even though this was fixed in `product-is`, after the unification process, all the fixes have been lost. Therefore, all the related places need to be fixed again with the usage of `internal_hostname` when invoking internal API calls in [identity-apps](https://github.com/wso2/identity-apps).

**How to reproduce:**
- Mentioned in https://github.com/wso2/product-is/issues/11878#issue-913818472

**Expected behavior:**
- For internal API calls, `internal_hostname` should be used.

**Environment information:**
 - Product Version: `IS-7.0.0 beta2-SNAPSHOT`
 - OS: `macos`
 - Database: `Default`
 - Userstore: `Default`

---

### Optional Fields

**Related issues:**
- The git issue which tracked this issue previously - https://github.com/wso2/product-is/issues/11878

**Comment by dhaura** [comment]
### Analysis

- Currently, the following files are identified as urls which are are built using the server hostname.

| Component                             | File                                     | Code                                                                                              |
|----------------------------------------|------------------------------------------|---------------------------------------------------------------------------------------------------|
| **Authentication Portal**              | `dynamic_prompt.jsp`                    | `authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);`                |
|                                        | `block-sign-in.jsp`                     | Only used in imports. No other usage.                                                              |
|                                        | `fido2_auth.jsp`                        | `authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);`                |
|                                        | `fido2_identifierfirst.jsp`             | `authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);`                |
|                                        | `fido2-passkey-status.jsp`              | `authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);`                |
|                                        | `user-not-found.jsp`                    | Only used in imports. No other usage.                                                              |
|                                        | `username.jsp`                          | Only used in imports. No other usage.                                                              |
|                                        | `identifierauth.jsp`                    | Only used in imports. No other usage.                                                              |
|                                        | `generic-exception-response.jsp`        | `authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);`                |
|                                        | `basicauth.jsp`                         | ` if (StringUtils.isNotBlank(EndpointConfigManager.getServerOrigin())) { url = EndpointConfigManager.getServerOrigin() + proxyContextPath + path; } else { url = IdentityUtil.getServerURL(path, true, false); }` 
| **Recovery Portal**                    | `self-registration-complete.jsp`         | ` String url; if (StringUtils.isNotBlank(EndpointConfigManager.getServerOrigin())) { url = EndpointConfigManager.getServerOrigin() + proxyContextPath + path; } else { url = IdentityUtil.getServerURL(path, true, false); } ` |
|                                        | `self-registration-username-request.jsp`| ` String identityServerEndpointContextParam = IdentityUtil.getServerURL("/", true, true); commonauthURL = identityServerEndpointContextParam + "/commonauth";` |
|                                        | `accept-invitaion.jsp`                  | `String apiUrl = IdentityUtil.getServerURL("/api/server/v1/guests/invitation/accept", true, true); ` |
| **components/org.wso2.identity.apps.common** | `AppPortalUtils.java`                | `String callbackUrl = IdentityUtil.getServerURL(portalPath, true, true); ` ` String accessUrl = IdentityUtil.getServerURL(portalPath, true, true);` `serviceProvider.setAccessUrl(IdentityUtil.getServerURL(portalPath, true, true)); `|

- Here, we have to identify if the url is used for an internal API call and if so fix it such that it uses `internal_hostname` when building the url. For that purpose `IdentityManagementEndpointUtil.getBasePath()` method can be used instead of `IdentityUtil.getServerURL()`.

**Comment by brionmario** [comment]
`getServerURL` is used in My Account and Console as well. @dhaura FYI

**Comment by dhaura** [comment]
Since My Account and Console should use server `hostname` (not the internal_hostname) for its API calls (these API calls are initiated from the client side unlike in jsps which are hosted in the server), `getServerURL()` should be used there.

**Comment by UdeshAthukorala** [comment]
This will be fixed with: https://github.com/wso2/identity-apps/pull/5004
