### ISSUE TITLE
Need a way to update Console's Callback & Allowed Origins

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#18164]
**Is your suggestion related to an experience ? Please describe.**

ATM, the API restricts any updates to the `api/server/v1/applications/<ID>/inbound-protocols/oidc` endpoint with PUT  operations for Console application since it's treated as a system application by default.

**Describe the improvement**

We need to allow this since it's needed if a user wants to externalize the Console.

*Proposed UI*

<img width="1714" alt="Screenshot 2023-11-28 at 08 09 36" src="https://github.com/wso2/product-is/assets/25959096/8c83b350-8cf0-4d1c-b6e5-982751ad6157">

**Additional context**

A similar improvement was done to allow the update of Authentication Sequence of Console. (https://github.com/wso2/identity-api-server/pull/536/files)

**Comment by brionmario** [comment]
@UdeshAthukorala FE PR is merged: https://github.com/wso2/identity-apps/pull/4842

And the tab is disabled. Please enable after BE PRs are merged.

**Comment by malithie** [comment]
Changing the priority level as this is a blocker for Asgardeo

**Comment by brionmario** [comment]
The UI implementation is already merged to the Console and is hidden from the UI for now until the API is merged.

@malithie Should we keep it hidden and document to use the API for updating these URLs?

**Comment by malithie** [comment]
Is this a tenat wide config ? Is that why we have an API ?
Or this API is not tenant level but server level ?

**Comment by UdeshAthukorala** [comment]
> Is this a tenat wide config ? Is that why we have an API ? Or this API is not tenant level but server level ?

Hi @malithie ,

With this improvement we can change console application's callBack URLs and allowed origins, from this updateInboundOAuthConfiguration API[1]. Since this is a tenanted API we can change it tenant wise.


[1] https://is.docs.wso2.com/en/latest/apis/application-rest-api/#/Inbound%20Protocols%20-%20OAuth%20%2F%20OIDC/updateInboundOAuthConfiguration

**Comment by malithie** [comment]
IMO, this is a server level requirement. Externalizing the console is not a requirement from the Identity Server perspective but from Asgardeo perspective.
And there's no requirement anyway to have this tenant wise.
@darshanasbg what's your view on this

**Comment by darshanasbg** [comment]
> IMO, this is a server level requirement. Externalizing the console is not a requirement from the Identity Server perspective but from Asgardeo perspective. And there's no requirement anyway to have this tenant wise. @darshanasbg what's your view on this

Yes, externalizing the console, don't needed to be a tenant wise option. Having server level config should be enough.

**Comment by UdeshAthukorala** [comment]
Hi all, 
Previous Tenant wise api improvement to upodate console application's callbaclk urls & allowed orgins willl be reverted with the below PRs.
- https://github.com/wso2/identity-api-server/pull/556
- https://github.com/wso2/identity-apps/pull/5015

**Comment by UdeshAthukorala** [comment]
After having a further discussions with the team we have decided to introduce a new toml config as a server level to update console & myacount callback urls.

For update allowed orgins we can use the existing cors configuration toml config. SO no need to have a seperate improvement for this.

**Comment by UdeshAthukorala** [comment]
This will be fixed with:
- https://github.com/wso2/carbon-identity-framework/pull/5304
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2301

**Comment by UdeshAthukorala** [comment]
- Introduced a toml config to update console & myaccount callback url & access urls

  #### New Toml Configs

  ```
  [console]
  callback_url = "https://localhost:9001/t/{TENANT_DOMAIN}/console"
  access_url = "https://localhost:9001/t/{TENANT_DOMAIN}/console"
  
  [myaccount]
  callback_url = "https://localhost:9000/t/{TENANT_DOMAIN}/myaccount"
  access_url = "https://localhost:9000/t/{TENANT_DOMAIN}/myaccount"
  ```
