### ISSUE TITLE
Make Application native authentication primary authentication mode in the mobile application template

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#18175]
**Describe the issue:**
Make Application native authentication primary authentication mode in the mobile application template.

**Related issues:**
- https://github.com/wso2/product-is/issues/16836

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
