### ISSUE TITLE
Account lock: IdentityGovernanceAdminService points to a general admin service config document

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1817]
In [1] IdentityGovernanceAdminService is given as an alternative to the management console. But the document that is linked for more information directs to the general admin service calling guide. Please direct the link to a page where IdentityGovernanceAdminService operations are described

[1] https://docs.wso2.com/display/IS540/User+Account+Locking+and+Account+Disabling

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
