### ISSUE TITLE
Inconsistency in the styles of input field validations

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18176]
**Is your suggestion related to an experience ? Please describe.**

<img width="659" alt="image" src="https://github.com/wso2/product-is/assets/67315176/f5fd86d7-e46e-4300-8ac3-5deec937bc9c">

<img width="640" alt="image (1)" src="https://github.com/wso2/product-is/assets/67315176/2a7b5414-0787-443a-9087-9a2fdee3cbb8">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
