### ISSUE TITLE
Remove enabling client credential grant config by default in Standard-based Application template.

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18173]
**Is your suggestion related to an experience ? Please describe.**

Currently, the Standard-based Application template enables client credential grant config by default. Since this template is there for developers to configure the protocol from scratch, adding a default grant is unnecessary. Also, we have a separate M2M template now for client credentials grants. 

![Screenshot 2023-11-29 at 12 06 03](https://github.com/wso2/product-is/assets/13478571/87c30a31-29c9-4fca-b13b-626bc61ab31a)

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
