### ISSUE TITLE
Change UX of Google Service Account Credential Upload

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#18174]
**Describe the issue:**
Currently, the UI component to upload the **Google Service Account Credential** is a text area. But, since the user is receiving a the credential as a file, we need to support to directly upload the file.

- https://doc.superannotate.com/docs/integration-gcp
  - Check step 5

**How to reproduce:**
Create an application > Advanced > Application native authentication > Enable client attestation > Service Account Credential

**Related issues:**
- https://github.com/wso2/product-is/issues/16836

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
