### ISSUE TITLE
[UX] Assigning or Removing Groups and Roles to a user is not consistant

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18188]
**Describe the issue:**

Im not sure whether this is by design but for me this feels like a UX issue. When I create a user and then add a Group I get the option to add groups to the user

<img width="937" alt="Screenshot 2023-11-29 at 14 39 12" src="https://github.com/wso2/product-is/assets/29881881/9baa1d8b-bf12-415e-b74d-8c8c50e04064">

But when it comes to roles we dont have a option to remove roles to the user 

<img width="1365" alt="Screenshot 2023-11-29 at 16 40 47" src="https://github.com/wso2/product-is/assets/29881881/fa586f86-1078-4be6-b1a2-f2a412f52f2b">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
