### ISSUE TITLE
Unable to add users to a secondary userstore - no option in the UI

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18184]
**Describe the issue:**
There are 

**How to reproduce:**
Configure a secondary user store (JDBC PostgreSQL)
Try adding a new user
There is no option to select the userstore

**Expected behavior:**
Should be able to select the secondary userstore and add user to the secondary userstore

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashanthamara** [comment]
Tested with console version `2.9.36`. Issue is resolved and can successfully create users in a secondary userstore.
(plugged secondary userstore type: MYQL JDBC Read/Write)

https://github.com/wso2/product-is/assets/75057725/efd64816-6b36-4ab0-865e-b8b5ebb37661
