### ISSUE TITLE
Invite users from parent organizations options is missing

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18189]
**Describe the issue:**

$subject due to https://github.com/wso2/identity-apps/commit/e5bd9c1a9e17a8da8b701742c53a04a7eb514fd3

<img width="1506" alt="Screenshot 2023-11-29 at 19 12 00" src="https://github.com/wso2/product-is/assets/41533942/8a8d178c-ab9b-4d04-a591-cc76c630f83c">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 Beta 2 snapshot
 - OS: N/A
 - Database: H2
 - Userstore: N/A

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
The option has been moved to a different location.

https://github.com/wso2/product-is/assets/25483865/2674d3e9-746a-4bbd-96b1-ffaa971a6ccd
