### ISSUE TITLE
[Doc]Wrong service name is mentioned in the doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1818]
[Doc]Wrong service name is mentioned in the doc [1]

[1] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs

**RemoteUserStoreManagerService** is an admin service ...

In here it should be TenantMgtAdminService not RemoteUserStoreManagerService

**Comment by Nashaath** [comment]
Fixed this in WSO2 IS doc versions 5.2.0 through 5.5.0 as well as in 5.x.x.
