### ISSUE TITLE
Add an fullscreen option to Visual Editor code editor

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#18180]
**Is your suggestion related to an experience ? Please describe.**

ATM, the code editor in the Visual Editor is fairly small and hard to work.

**Describe the improvement**

Add an fullscreen option to Visual Editor code editor like we have for classic editor to improve DX.

**Additional context**

N/A

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
