### ISSUE TITLE
Empty second step when there are no secondary userstore created on the wizard

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#18186]
**Describe the issue:**

Empty step on attribute creation wizard.

![image](https://github.com/wso2/product-is/assets/7569427/9a975d4c-8169-4e2a-9f25-6e6027c809ad)

**How to reproduce:**
- Navigate to attributes section and click on `New attribute` and enter an attribute name follow to next step. And you will get the above blank screen as the second step. This confuses user on what has missed or why it's not loaded.

**Expected behavior:**
This step should not show when there no additional userstore connected and no attributes to map.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0 BETA 2
 - OS: Windows

**Comment by dasuni-30** [comment]
### Fixed in new pack

<img width="789" alt="Screenshot 2023-12-14 at 09 06 00" src="https://github.com/wso2/product-is/assets/27746285/57325989-c80c-41e0-ad32-862cac6886cc">
