### ISSUE TITLE
[Chaos] While start second node in to cluster, getting error with high load

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1819]
**Operating System:** Ubuntu 16.04
**Java Version**: Oracle JDK 1.8.0_45
**Packs**: IS 5.4.0 GA
**Setup**: Cluster

**Steps to reproduce**
1. Run the scenario automated [1] for the 17th use case in [2] in one active node cluster.
2. Run the login with higher frequency (100 threads with 10 ramp-up period while having 2 loops ). While running the test, start the other node in the cluster.

**Expected Result**
It should handle requests by the cluster.

**Actual Result**
Got following error time to time:

`TID: [-1234] [] [2017-12-20 08:12:12,127] ERROR {org.wso2.carbon.identity.oauth.proxy.LoginProxy} -  org.apache.amber.oauth2.common.exception.OAuthSystemException: java.io.IOException: Server returned HTTP response code: 500 for URL: https://is540.qa.com/oauth2/token `

Note: This error can even be seen with a heavy load while having both nodes in the cluster.

[1] https://github.com/wso2-incubator/identity-test-integration/tree/master/solution17
[2] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
