### ISSUE TITLE
Doc links in the Adaptive templates are outdated 

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18195]
**Describe the issue:**
Doc links in the Adaptive templates are outdated. Most of the doc links are from the IS 5.7.0 version. Check below,

**How to reproduce:**
<img width="320" alt="Screenshot 2023-11-30 at 09 38 13" src="https://github.com/wso2/product-is/assets/13478571/f2f6e540-3eda-42e8-aa1d-caf82535cfeb">

<img width="813" alt="Screenshot 2023-11-30 at 09 37 29" src="https://github.com/wso2/product-is/assets/13478571/1718ad2b-6ad1-4c24-8989-99d8bc4ba43c">

**Expected behavior:**
Some of the template does not have doc links. We normally don't provide doc links in the IS console. Hence we have to decide whether this is the correct approach. If we are keeping it we need to update it in every product release. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Need to update the adaptive auth template JSON files in the pack.

**Comment by sahandilshan** [comment]
This will be fixed with https://github.com/wso2/carbon-identity-framework/pull/5331

<img width="761" alt="Screenshot 2023-12-21 at 12 44 23 PM" src="https://github.com/wso2/product-is/assets/32576163/994a0f46-e26c-4065-a7b1-9ccc37918909">
