### ISSUE TITLE
Remove unwanted configs from the user attributes section and add necessory sections

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18190]
**Describe the issue:**

From IS7 onward, the subject will be the userID, there is no requirement to `include userstore domain` to the subject. 

![image](https://github.com/wso2/product-is/assets/5061791/94d7b0de-4c9e-46e8-ae2c-4660dac0309a)

The role behaviour also get changes with the new applications roles feature. Hence there's no requirement to keep it here.

**How to reproduce:**
Create an application and open attributes configurations.

**Expected behavior:**
Keep only the required configurations and remove unwanted ones. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
There seems to be a bug in the PATCH request when the subject attributes are enabled. @DonOmalVindula Please validate that as well.

**Comment by DonOmalVindula** [comment]
After discussing with @ayshsandu, @thanujalk, @ashensw and @Yasasr1 it was decided to take the following steps in the `User Attributes` section.

For OIDC applications
- **Remove** the Subject section by default using a config `isOIDCSubjectIdentifierEnabled = false` in the `deployment.config.json` as we are using the **User ID** as the subject identifier in OIDC. For legacy users, they may enable the section via the above mentioned config.
- **Include user domain** in Subject section will be re-located under Linked Accounts via task - https://github.com/wso2-enterprise/iam-engineering/issues/821
- **Remove** the Role attribute section by default using a config `isApplicationLevelRoleAttributeEnabled = false` as this can handled via new roles. For legacy users, they may enable the section via the above mentioned config.
- **Remove** the Role mapping section by default using a config `isOIDCRoleMappingEnabled = false` as this can handled via new roles. For legacy users, they may enable the section via the above mentioned config.

For SAML applications
- **Keep** the Subject section  as the subject identifier is configurable.
- **Include user domain** in Subject section will be re-located under Linked Accounts via task - https://github.com/wso2-enterprise/iam-engineering/issues/821
- **Remove** the Role attribute section by default using a config `isApplicationLevelRoleAttributeEnabled = false` as this can handled via new roles. For legacy users, they may enable the section via the above mentioned config.
- **Keep** Role Mapping section
