### ISSUE TITLE
Response message is not adequate for getPolicyByVersion operation

### ISSUE THREAD

**Issue by chaminda** [wso2/product-is#1820]
**Steps To Recreate:**
1. Invoke getPolicyByVersion operation in the EntitlementPolicyAdminService giving non-existing version or policyId

**Actual Result:**
for both the cases: non-existing version and non-existing policy, the response message is "Invalid policy version". Please see the img.
![image](https://user-images.githubusercontent.com/7115693/34201178-abcfc2b8-e599-11e7-9d0d-6af277161117.png)

**Expected Result** 
It is better giving a message like "Policy version does not exist" rather claiming invalid policy version; this is ok in a scenario where user inserts unsupported data type for the version.
**And also** the response code is 500, this is not correct and should return correct response code(ex:-404)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
