### ISSUE TITLE
In the Facebook connector the scopes and the user-information fields can not be requested

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18202]
**Describe the issue:**

In the Facebook connector the scopes and the user-information fields can not be requested. Even though this is available in the MC need to check whether this is required.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

Derived from https://github.com/wso2/product-is/issues/16691

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
