### ISSUE TITLE
Missing FIDO Documentation in WSO2 IS 7.0 Compared to Version 6.1

### ISSUE THREAD

**Issue by AfraHussaindeen** [wso2/product-is#18207]
**Is your suggestion related to a missing or misleading document? Please describe.**

I noticed that specific FIDO-related content present in the WSO2 Identity Server (IS) documentation for version 6.1 seems to be missing in the documentation for version 7.0. This missing content is crucial for understanding and implementing FIDO functionalities in WSO2 IS. Below are the details of the missing content:

- What is FIDO: https://is.docs.wso2.com/en/latest/references/concepts/authentication/mfa-with-fido/
- FIDO2 Attestation validation : https://is.docs.wso2.com/en/latest/guides/passwordless/fido-attestation/#fido2-metadata-service-mds

**Comment by himeshsiriwardana** [comment]
What is FIDO: https://is.docs.wso2.com/en/latest/references/concepts/authentication/mfa-with-fido/

This document will be added from the following issue [1]

[1] https://github.com/wso2/product-is/issues/18804
