### ISSUE TITLE
When creating the groups, “Basic details” section has the screen to assign users. But to assign roles, there is a separate screen available with title “Assign roles”

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18200]
**Describe the issue:**

$subject

<img width="1506" alt="Screenshot 2023-11-30 at 10 44 57" src="https://github.com/wso2/product-is/assets/41533942/c9f9a5f0-3036-4a4d-9b2c-3d08171c29da">

<img width="1506" alt="Screenshot 2023-11-30 at 10 45 27" src="https://github.com/wso2/product-is/assets/41533942/faf6dcc7-f54b-423f-964b-f9714ea23445">

**How to reproduce:**

1. Sign into console.
2. Navigate to user management > Groups
3. Click on "New Group" button.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

Derived from https://github.com/wso2/product-is/issues/16691

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
