### ISSUE TITLE
Inconsistency in Email & SMS Config UI

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18204]
**Describe the issue:**
Inconsistency in Email & SMS Config as below

- Even thogh it is mentioned Email & SMS Config, only SMS Config is there when you click it
- UI card component is not consistent with other places
- Better to remove the custom part from the label as well

<img width="1103" alt="Screenshot 2023-11-30 at 09 52 10" src="https://github.com/wso2/product-is/assets/13478571/1059cbe0-564f-4825-87d4-8804e5c2cb55">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
The design of this was changed.
@pavinduLakshan Can we check if it solves the issues mentioned here.

**Comment by pavinduLakshan** [comment]
> The design of this was changed. @pavinduLakshan Can we check if it solves the issues mentioned here.

Yes, it will. Tracked with https://github.com/wso2/product-is/issues/18146 and https://github.com/wso2/product-is/issues/17805
