### ISSUE TITLE
[Doc]Link to the latest carbon docs if exists

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1821]
In this [1] doc the below statement link should be linked to latest docs. Currently it directs to Carbon 420. [2] 

For more information on WSO2 admin services and how to invoke an admin service using either SoapUI or any other client program, see **Calling Admin Services from Apps** section in WSO2 Carbon documentation. 

[1] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs
 Calling Admin Services from Apps
[2] https://docs.wso2.com/display/Carbon420/Calling+Admin+Services+from+Apps

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
