### ISSUE TITLE
Missing SAML and JWT bearer grant types in Cloud Support

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18215]
**Describe the issue:**

Missing SAML and JWT bearer grant types in Cloud Support

**How to reproduce:**

1.Login to the console
2.Create a standard based OIDC application
3.Go to protocol section of the application  and check the grant types

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
These grant types were not already available in the cloud offering, hence they were not added for the cloud offering during the unification effort.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
