### ISSUE TITLE
Role audience and Assigned roles is missing in cloud support 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18229]
**Describe the issue:**

Role audience and Assigned roles are missing in cloud support.

<img width="1141" alt="Screenshot 2023-11-30 at 16 10 39" src="https://github.com/wso2/product-is/assets/40081059/7f635ec4-938c-4c57-9d1a-a9973152dd50">

**How to reproduce:**

1. Log in to the console
2.Create an application
3.Go to roles section in the crated application

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
