### ISSUE TITLE
Single User Creation wizard  user store filed is enable by default. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18221]
**Describe the issue:**
In IS Single User Creation wizard  user store filed is enable by default and in cloud it available only once we create user store only.

Cloud
![image](https://github.com/wso2/product-is/assets/39077751/1cc5934a-9e37-454b-8dce-100cbacf6789)

IS

<img width="622" alt="image" src="https://github.com/wso2/product-is/assets/39077751/968b8a1c-f6a3-43d6-9c83-5ba8b234e8c5">

**How to reproduce:**
1. Login to console
2. Select the user management -> select users
3. Click Add user
4. Select single user

**Expected behavior:**
Single User Creation wizard  user store filed is enable by default in IS and in cloud its not. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
This is expected since in Asgardeo we don't need to show the default asgardeo user store name.
