### ISSUE TITLE
[Blocker][Doc] No details on Carbon user store manager under configuring user stores

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1822]
Type: Bug
Priority: Highest
Severity: Blocker
Release: wso2is-5.4.0-update1

No details on Carbon user store manager under configuring user stores in the below doc.
https://docs.wso2.com/display/IS540/Configuring+User+Stores

Therefore, the users cannot get to know which properties to configure and the exact property name to create a user store via admin services

**Comment by sherenewso2** [comment]
This content can be found here [1].  Please reopen if this is not the required content you were looking for. 

[1] https://docs.wso2.com/display/IS580/Carbon+Remote+User+Store+Manager
