### ISSUE TITLE
When creating a new user, have the option to assign roles

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18227]
**Describe the issue:**
$ can be observed in both cloud and IS. 

**How to reproduce:**
1. Login to console
2. Create role
3. Create user

**Comment by dewniMW** [comment]
This is the experience we have agreed on. Hence removing marking this with the FUTURE milestone

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
