### ISSUE TITLE
Exclude Console from Applications List that can be viewed through Connections `Quick Start` tab.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18226]
**Describe the issue:**
To ensure non-editability, exclude Console from the Applications List in the Connections Quick Start Tab's Select Application Step.

NOTE: In the cloud product, we are not listing the console or My account in this view.

<img width="1511" alt="Screenshot 2023-11-30 at 15 44 52" src="https://github.com/wso2/product-is/assets/41188245/333ab2a7-f492-4665-9620-1ff650617436">

**How to reproduce:**

https://github.com/wso2/product-is/assets/41188245/6c912e48-ee24-4d7a-942b-70b4347475b8

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Related issue: https://github.com/wso2/product-is/issues/18253

**Comment by GoushiRam** [comment]
Raising the severity of this issue as user can manipulate the shared access, api authorisation and other critical functions for this application. 

> Related issue: #18253

- @pavinduLakshan will modify this issue tracking the severity

**Comment by brionmario** [comment]
This should be done conditionally based on the legacy mode. In legacy mode, the exitsing error behaviour should be there. and in the new runtime, we can handle this differently as mentioned in (https://github.com/wso2/product-is/issues/18253)
