### ISSUE TITLE
 Server Endpoints UI in Info section should be updated

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18225]
**Describe the issue:**

 Server Endpoints UI in Info section should be updated

The following Server endpoints should be removed

- Web finger
- Session Iframe
- Dynamic Client Registration

<img width="633" alt="Screenshot 2023-11-30 at 15 28 45" src="https://github.com/wso2/product-is/assets/40081059/b13f97da-5fd3-4d3d-8b45-fbef4c4f900c">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by janakamarasena** [comment]
@asekawa Can you give the reasoning behind the request to remove these?
Session iframe is required for an application using session management.

And this info was present in the resident idp configs. It makes sense to remove webfinger (as this is a server-level ep) and the DCR as this is needed to create the app mainly. But we need to have this info in some place

**Comment by ayshsandu** [comment]
Webfinger endpoint> is redundant as the Discovery endpoint also serves the same purpose.

Session iframe > As @janakamarasena suggested we can enable this only for OIDC types of apps other than M2M and Mobile (i.e, enable for SPA, TWA - OIDC, Standard based - OIDC)

DCR > is needed before creating the application, It doesn't make sense after creating the application. 
+1 to move this under a sensible server-level section. But not needed under each application.
