### ISSUE TITLE
Repeated warn log for every token call for client-credentials grant using M2M template.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18224]
**Describe the issue:**
Following Warn log in the wso2carbon log for each token call
```
[2023-11-30 15:02:41,025] [b2c7e4f9-80b1-42b2-81e7-219c30acebbf]  WARN {org.wso2.carbon.identity.oauth2.client.authentication.PublicClientAuthenticator} - The request contained grant type : 'client_credentials' which is not allowed for public clients.
```

**How to reproduce:**
1- Register M2M app using the M2M template
2 - obtain a token over client credentials grant

**Expected behavior:**
The warning log looks uncessory for this flow as this is a expected flow. Evaluate the need and update the log accordingly. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
