### ISSUE TITLE
 Include  domain option should be removed from the application attributes section

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18223]
**Describe the issue:**

 Include domain option should be removed from the application attributes section. This should be removed in
- simple page application
- Traditional page application
- Standard-based application 

<img width="674" alt="Screenshot 2023-11-30 at 15 03 51" src="https://github.com/wso2/product-is/assets/40081059/6a66a369-14c3-4903-9ba7-ef95a811c50b">

**How to reproduce:**

1.Login to the console
2.Create an application
3.Go to attributes section

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
This will be removed on in OIDC applications. In SAML applications this will be kept. This will be changed via - https://github.com/wso2/identity-apps/pull/4900
