### ISSUE TITLE
Ask password should be enable by default

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18238]
**Describe the issue:**
Currently ask password option is disable by default. This need to be enable by disable.  

<img width="919" alt="image" src="https://github.com/wso2/product-is/assets/39077751/ba09152c-2140-4138-a583-b1a215f6d981">

**How to reproduce:**
1. Login to console
2. Navigate to the login & registration -> Invite User to Set Password

**Expected behavior:**
Enable user verification should be enable. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
@chamathns @madurangasiriwardena as per the discussion with UI team this has been planned to enable by default. 
CC: @NipuniBhagya

**Comment by chamathns** [comment]
We don't have an email server configured by default in the Identity Server. Hence it does not make sense to make the ask password option enabled by default.

**Comment by aaujayasena** [comment]
CC: @NipuniBhagya

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
