### ISSUE TITLE
Clarify and Improve Path for Enabling "Invite the User to Set Their Own Password" in User Creation Wizard

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18232]
**Describe the issue:**
While navigating the user creation wizard, users may face confusion in finding the correct path to enable the "Invite the User to Set Their Own Password" feature. To enhance user experience, it is suggested to provide a more explicit and accurate path.

```
" Login & registration >  Invite User to Set Password > Enable user email verification 
```
<img width="790" alt="Screenshot 2023-11-30 at 16 51 47" src="https://github.com/wso2/product-is/assets/39120228/8ed3d95c-edaa-41a4-8f4e-b6c6142c1fef">

**Comment by JayaShakthi97** [comment]
Decided to add a link in the hint to enable email verification.
- https://github.com/wso2/identity-apps/pull/5232

**Comment by JayaShakthi97** [comment]
Verified in the latest `wso2is-7.0.0-beta6-SNAPSHOT`


<img width="1510" alt="image" src="https://github.com/wso2/product-is/assets/37938529/1fc89000-a9c4-46ff-a648-fe22d85fc2f4">
