### ISSUE TITLE
403 Forbidden error when accessing the permissions section of a parent org role via the console of a sub org

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#18235]
**Describe the issue:**

A `403 - Forbidden` response is received when using the console of a sub organization to access the `Permissions` section of a role shared by its parent organization.

https://github.com/wso2/product-is/assets/27700915/3206da22-e6db-4b11-866f-11705a8ba767

**How to reproduce:**
1. Log into the console and create a sub organization.
2. Create an organization role in the parent organization.
3. Create an application in the parent organization and share it with the sub organizations.
4. Assign the role created in step 2 into the application created in step 3.
5. Switch to the sub organization and go to the **Roles** section.
6. Click on the role from the parent organization.
7. Go to the `permissions` tab.

**Expected behavior:**
If the permissions of a parent org role can be accessed by a user in the sub organization, permissions should be properly displayed. Otherwise, the `Permissions` section should not be visible to the user.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0 Beta

**Comment by dewniMW** [comment]
Seems like the GET call https://localhost:9443/t/carbon.super/o/api/server/v1/api-resources is not required for sub-organizations.
