### ISSUE TITLE
Enhance User Experience by Adding UI Options for "Recovery link expiry time in minutes"  and "Notify when recovery success"  in User Name Recovery

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18241]
**Describe the issue:**
Currently, the user name recovery section lacks UI options for notifying users when recovery is successful and specifying the recovery link expiry time in minutes. This enhancement aims to improve user experience by introducing these capabilities, similar to what is available in the password recovery process.

**Proposed Changes**
Notify When Recovery Success:

Add an option to enable or disable notifications for users when their user name recovery is successful.
Recovery Link Expiry Time (in minutes):

Introduce a field allowing administrators to set the expiration time for the recovery link in minutes.
<img width="1590" alt="Screenshot 2023-11-30 at 18 39 11" src="https://github.com/wso2/product-is/assets/39120228/4ed6ea4d-0e26-4957-8281-8cb959aa9853">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
