### ISSUE TITLE
Well known endpoint URL configuration is invalid during organization switch in  Authz legacy runtime

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18243]
**Describe the issue:**
This is only reproducible in Authz legacy runtime

1. Create a tenant 
2. Create a sub organization 
3. Switch to suborg with network trace. 
4. Check the well known endpoint 

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
### This is fixed in the new pack

The well-known endpoint is removed from the identity server pack

https://github.com/wso2/product-is/assets/27746285/acd8bb15-c50a-46fc-bc1f-7ed7c3f4e8aa
