### ISSUE TITLE
Account lock: Configure the user store for storing relevant claims section

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1824]
In [1] there is a mention of "Configure the user store for storing relevant claims". But when clicked on this [1] itself is loaded again. Apparently there is no visible reason for needing claims in [1] as well. Please check and change accordingly.

[1] https://docs.wso2.com/display/IS540/User+Account+Locking+and+Account+Disabling#UserAccountLockingandAccountDisabling-ConfiguringWSO2IdentityServerforaccountlockinganddisabling

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
