### ISSUE TITLE
Using the wrong token to refresh the organization switched causing a logout in Authz legacy mode 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18245]
**Describe the issue:**

Using the main organisation for calling the refresh token call for the sub organization. 
**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
In on-prem for legacy mode, organization management related functionalities will be hidden in the console. Hence closing this issue.

**Comment by Buddhimah** [comment]
Reopening since this is more of a issue in console url building

**Comment by brionmario** [comment]
A possible fix was added with https://github.com/wso2/identity-apps/pull/4852 to fix a related issue (https://github.com/wso2/product-is/issues/17675).

@pavinduLakshan lets validate if this is fixed.

**Comment by pavinduLakshan** [comment]
Needs to be verified after the identity-apps version bump. I'm currently working on it.

**Comment by pavinduLakshan** [comment]
This issue seems to be still there.

Currently working on dev e2e stabilization. Will start working on this once that's completed.

<img width="1503" alt="Screenshot 2023-12-12 at 10 02 23" src="https://github.com/wso2/product-is/assets/41533942/9690d4a8-75ab-4cdf-834b-5e53f2ef9639">

**Comment by Buddhimah** [comment]
@sadilchamishka this issue still getting reproduced in cloud deployment
