### ISSUE TITLE
Admin Initiated Password Reset Checkbox Not Updating After Successful Enablement via Console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18249]
**Describe the issue:**
When attempting to enable "Admin Initiated Password Reset" via the console, although a success message is displayed, the corresponding checkbox is not updated as expected. 

**How to reproduce:**
Log in to the console as an administrator.
Navigate to the  "login & registration" >  section where "Admin Initiated Password Reset" can be configured.
Enable "Admin Initiated Password Reset."
Observe the success message confirming the enablement.
Check the status of the "Admin Initiated Password Reset" checkbox.

**Expected behavior:**
The checkbox for "Admin Initiated Password Reset" should be updated and reflect the enabled status after a successful enablement.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:&. RC1Snapshot
 - OS: Mac
 - Database: H2

https://github.com/wso2/product-is/assets/39120228/85a722af-c45e-4598-8784-56bbee3d88ce

**Comment by NipuniBhagya** [comment]
Verified in rc1-snapshot pack relased on 06.12.2023.
