### ISSUE TITLE
UX improvement in parent user invite flow

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#18255]
**Describe the issue:**
With this improvement https://github.com/wso2/product-is/issues/16719, now can invite multiple users to the sub organisation from parent organisation at once with the set of roles. Hence the below UI wizard needs to be updated to invite multiple users with the same list of roles.

<img width="728" alt="Screenshot 2023-11-30 at 8 20 18 PM" src="https://github.com/wso2/product-is/assets/13362482/2e80b241-9657-4e1c-a95f-77453c782e49">

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR
- https://github.com/wso2/identity-apps/pull/5119
