### ISSUE TITLE
Console application selection on SMS OTP, Email OTP, TOTP, Magic Link, passkey quick start guide should navigate to console setting's sign in method tab

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18253]
**Describe the issue:**

1. Go to connections >SMS OTP/ Email OTP
2. Go to the Quick Start tab
3. Click on the applications link there, select Console 
4. You will be navigated to the uneditable sign in method page of the console
5. Instead the user should be navigated to sign in methods tab under `Console Settings`

https://github.com/wso2/product-is/assets/25483865/8e92dc29-86f6-489d-94e8-79e3dd4cecb6

**Comment by brionmario** [comment]
Related Issue: https://github.com/wso2/product-is/issues/18226

**Comment by brionmario** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/4982
