### ISSUE TITLE
Session expired. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18259]
**Describe the issue:**
<img width="1440" alt="image" src="https://github.com/wso2-enterprise/asgardeo-product/assets/39077751/1035302c-e5a5-452f-a65e-dbd1bdbc9cea">

**How To Reproduce:**
1. Login to console
2. Create multiple roles 

**Expected behavior:**
Session should not be expired. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-rc1-SNAPSHOT-4957
 - OS: [e.g., Windows, Linux, Mac]
 - Database: Postgres
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/18259

**Suggested labels:**

**Comment by ZiyamSanthosh** [comment]
We have sent a fix for the similar issue with https://github.com/wso2/carbon-identity-framework/pull/5251
This issue is not reproducible in the pack updated with the fix. Will close once the PR is merged.
https://github.com/wso2/product-is/assets/50801227/cfcebb3b-88d7-4e0d-b303-1fe4c6f1d563

**Comment by ZiyamSanthosh** [comment]
This is being tracked with https://github.com/wso2/product-is/issues/18222
Hence closing the issue.
