### ISSUE TITLE
[Doc]Operations included in the API does not include all the operations 

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1825]
Operations included in the API does not include all the operations in this doc [1]

[1] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs

It mentions below

- addTenant()
- activateTenant()
- deactivateTenant()
- getTenant()
- retrievePaginatedPartialSearchTenants()
- retrievePaginatedTenants()
- retrievePartialSearchTenants()
- retrieveTenants()
- updateTenant()

It is missing,

deleteTenant
addSkeletonTenant

Include their API descriptions as well.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
