### ISSUE TITLE
[cloud support] Add multiple users wizard notes and help section are missing 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18252]
**Describe the issue:**
IS
![image](https://github.com/wso2/product-is/assets/39077751/a99fde59-dd48-42cd-8b4c-d7e6c82a8fc8)

Cloud
![image](https://github.com/wso2/product-is/assets/39077751/bd47bd72-ae8e-4c06-a844-3ac24dde1aaa)

**How to reproduce:**
1. Login to console
2. Navigate to the user management -> users 
3. Click add user 
4. Select multiple users

**Expected behavior:**
UI should be same

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
