### ISSUE TITLE
application slection from Quick Start guide of email otp, totp etc .. in organization will land into empty signin method tab of application

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18256]
**Describe the issue:**
1. Login to console
2. Create an app and share it with all orgs
3. Create a new org
4. Switch to the created org
5. Go to connections. select email otp/ totp ... -> Click on Quick start
6. Click applications link there
7. Select one application you will be redirected to signin method tab but it is empty

https://github.com/wso2/product-is/assets/25483865/7aa9e289-08db-4dda-85be-853762a0d3fa

Also, Conole application should not be listed there, because we are not allowing to change the console application's signin methods for organizations

**Comment by JayaShakthi97** [comment]
This is not reproducible in the latest `wso2is-7.0.0-beta6-SNAPSHOT`


https://github.com/wso2/product-is/assets/37938529/d0c5aa83-9c45-43fe-ba17-ebf20be9f613
