### ISSUE TITLE
Inconsistency in Users roles UI

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18258]
**Describe the issue:**

There seems to be a UX issue in Users -> Roles tab.

When you go to  Users -> Roles tab you can view assigned roles to the user. You cannot assign new roles to the user. But there is a dropdown and a search option available. 

<img width="1693" alt="Screenshot 2023-11-30 at 21 15 01" src="https://github.com/wso2/product-is/assets/13478571/ecb1fe2d-405f-405f-92cc-0fa4292dcb37">

Also, all the available roles are showing in the box without the dropdown as well. 

<img width="1334" alt="Screenshot 2023-11-30 at 21 20 22" src="https://github.com/wso2/product-is/assets/13478571/bf8ee02e-ab7a-4ade-9e84-8be0a3fb1064">

**Expected behavior:**
Better if we could improve this UI to provide a better UX. The dropdown gives the idea that you can assign those roles to the user. But they are already assigned. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
@nipunsampath is already working on improving this view. Hence assigning the issue to him.

**Comment by nipunsampath** [comment]
This is addressed by the PR https://github.com/wso2/identity-apps/pull/4984.
