### ISSUE TITLE
User manage by column in user list table is missing

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18262]
**Describe the issue:**
User manage by column in user list table is missing

cloud
![Screenshot 2023-12-01 at 10 03 11](https://github.com/wso2/product-is/assets/39077751/1086e6e7-f8c8-495d-ac06-2d8af3abdb9c)

IS
![image](https://github.com/wso2/product-is/assets/39077751/96af093b-b110-42ae-9f5e-bb7bc398763f)

**How to reproduce:**
1. login to console
2. Navigate to user list 

**Expected behavior:**
Manage by section  should be there. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
This was decided to remove in the IS side. This decision can be referred in the IS-Asgardeo Feature Gap doc
