### ISSUE TITLE
Attribute Mapping delete option for SCIM and OIDC mappins is not working in the new React console, but possible in the old mgt console

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18267]
**Describe the issue:**

Custom Attribute mappings can be successfully deleted from the new console, but SCIM and OIDC mappings cannot be deleted.

However, in the old management console, these mappings cannot be deleted.

https://github.com/wso2/product-is/assets/41533942/1f0cf74c-9086-4bc8-ba9f-dac0dd69184e

**How to reproduce:**

1. Sign into console.
2. Navigate to attributes page.
3. Locate attribute mapping section and click on either OIDC or SCIM mapping.
4. In the edit page, click delete option.
5. Even though the backend sends a success response, the mapping is not deleted.
6. However, custom mappings created from the console can successfully be deleted.

**Expected behavior:**

Attribute mapping delete UX should be consistent with the old mgt console

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 Beta2 snapshot
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

N/A

**Suggested labels:**

N/A

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
