### ISSUE TITLE
Can not user filter from first name and last name

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18261]
**Describe the issue:**
Can not user filter from first name and last name
IS
<img width="532" alt="image" src="https://github.com/wso2/product-is/assets/39077751/a7fb779b-0631-4adf-bd78-ee67e96e4c15">

cloud
![image](https://github.com/wso2/product-is/assets/39077751/27daec58-8207-4ba4-8221-2073d329f379)

**How to reproduce:**
1. Login to conosle
2. Create users
3. Search users from firstname
4. 
**Expected behavior:**
There should be a option to search users from first name

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
