### ISSUE TITLE
Invalid error message for locked account 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18265]
**Describe the issue:**
Locked account display invalid error when attempting to login. 

![image](https://github.com/wso2/product-is/assets/39077751/d2025c17-c25a-4ad2-904b-9ac2c5aabe15)

**How to reproduce:**
1. Login to console
2. Lock created user
3. login with locked user

**Expected behavior:**
Error should be below,
![image](https://github.com/wso2/product-is/assets/39077751/f23ccccd-58b6-495b-931f-a19e9eaac8e6)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
