### ISSUE TITLE
SSO Connection behaviour should be unified. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18269]
**Describe the issue:**
The current behavior differs between SSO connection creation in IS and the cloud product. In IS, it defaults to creating an SSO connection with `My Account` as a connected app, while in the cloud product, it only occurs if a sub-org is connected. If this behaviour is not expected this should be addressed and unified accordingly.

https://github.com/wso2/product-is/assets/41188245/62351974-b9b3-447d-b9c1-38a69505e70c

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
This is cause in the cloud we still run with legacy runtime. When the new runtime is enabled, myaccount will have the organization sso authenticator configured.

**Comment by melanisilva** [comment]
> This is cause in the cloud we still run with legacy runtime. When the new runtime is enabled, myaccount will have the organization sso authenticator configured.

ACK, Since the IS behaviour will be applied to the cloud will be tracking this on the relevant project board.
