### ISSUE TITLE
Account lock: The email template does not contain the name of the user for a user in secondary store

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1827]
**Steps**
1. Lock the account of a user in secondary user store in the super tenant domain
(secondary user store: MYSQL 5.7)

The email template is as follows. The username is not properly picked

![is_issue_15](https://user-images.githubusercontent.com/15624590/34201903-110a45d4-e59c-11e7-98a7-c7be3345972d.png)

**Comment by erandidesilva** [comment]
This is re-producible for users added through add password option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
