### ISSUE TITLE
User listing and user creation is broken in Console

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18271]
**Describe the issue:**

$subject

https://github.com/wso2/product-is/assets/41533942/d9feec6a-0199-46c6-9602-ffe10cb3a53a

No error logs on the terminal as well.

**How to reproduce:**

Refer to the screencast.

**Expected behavior:**

Users should be listed as expected and user creation should work as expected.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 RC1 snapshot build 
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnjanaSamindraPerera** [comment]
This was resolved at https://wso2.org/jenkins/job/products/job/product-is/4963/

![Screenshot 2023-12-04 at 10 09 45](https://github.com/wso2/product-is/assets/38417165/bbb1add0-02fc-466c-b721-1e7b5b4c1da0)
