### ISSUE TITLE
[Single sign-on / Federated authentication for applications][RC Based][SAML]

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18287]
Single Sign-On / Federated authentication for a web application with SAML |
SP-Init
IdP-Init
SAML POST Binding
SAML Redirect Binding
SAML 2.0 Artifact binding support
End-user consent and claim mapping

**Comment by NilukaSripalim** [comment]
Single Sign-On / Federated authentication for a web application with SAML |
 SP-Init
 IdP-Init
 SAML POST Binding
 SAML Redirect Binding
SAML 2.0 Artifact binding support
End-user consent and claim mapping

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
