### ISSUE TITLE
Need to remove "Server" section from Console Conditionally 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18281]
**Describe the issue:**
Server section does not make sense for a cloud user so it should be configurable and should be able to disable in a cloud deployment 

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
This is now fixed and cab be conditionally hidden via the following methods.

*deployment.tom* (Recommended for non-externalized Console)

```toml
[console.server]
enabled = false
```

*deployment.config.json* (File Path: repository/deployment/server/webapps/console)

```json
{
  ...,
  "ui": {
     "features": {
            "server": {
                "disabledFeatures": [
                ],
                "enabled": false,
                "scopes": {
                    "read": [
                            "internal_governance_view"
                    ],
                    "delete": [
                    ],
                    "update": [
                            "internal_governance_update"
                    ],
                    "create": [
                    ]
                }
            },
            ...
```
