### ISSUE TITLE
`Identity Verification Providers` text overflowing in Management Console

### ISSUE THREAD

**Issue by AmshikaH** [wso2/product-is#18297]
**Describe the issue:**

In the Management Console, the text "Identity Verification Providers" found at Main > Identity > Identity Verification Providers is overflowing.

![image](https://github.com/wso2/product-is/assets/66556626/45e708ec-0a0c-43b2-9d82-f74510ea23eb)

**How to reproduce:**

1. Login to the Management Console
2. See Main > Identity > Identity Verification Providers

**Expected behavior:**

The gray header area should cover the entire text.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-rc1-SNAPSHOT
 - OS: Mac

**Comment by DonOmalVindula** [comment]
Reducing severity and priority as the issue is related to the management console

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
