### ISSUE TITLE
[Single sign-on / Federated authentication for applications][RC Based][OIDC]

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18294]
Single Sign-On / Federated authentication for a web application with OIDC 

Discover OIDC metadata and register OIDC application dynamically
 Request object support
 Basic profile
 Implicit profile
 Hybrid profile
 End-user consent and claim mapping
 Logout

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
