### ISSUE TITLE
[Localization] On profile change to "Chinese"/ "Japanese" the loader language text is not added. 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18301]
**Describe the issue:**

<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/26ef11d5-5b1c-423c-8222-2a16e74ba0e2">

**How to reproduce:**
1. Navigate to the console login
2. Change the language to Japanese/Chinese
3. Enter the credentials and login to the system
4. Verify the loader displayed. ^ check the screenshot above

**Expected behavior:**
The language switch should clearly change the texts correctly

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
