### ISSUE TITLE
Update the default certificate to reflect the new WSO2 address.

### ISSUE THREAD

**Issue by gnudeep** [wso2/product-is#18307]
**Describe the issue:**

Update the default certificate to reflect the new WSO2 address.

<img width="595" alt="Screenshot 2023-12-02 at 12 35 53" src="https://github.com/wso2/product-is/assets/155502/1dc6b4c7-1f94-4045-886a-80de7c7f8c79">

**How to reproduce:**

Run and load https://localhost:9443/console

**Expected behavior:**

Certificate information should be up to date. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0.0-rc1]
 - OS: [Mac OS X 13.3, aarch64]

**Comment by DMHP** [comment]
https://github.com/wso2/product-is/issues/18466

**Comment by Thisara-Welmilla** [comment]
Fixed with https://github.com/wso2/product-is/issues/18466
