### ISSUE TITLE
[Social Authentication / Admin Login] - The Profile is not populated in the console of the social authenticated user. 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18313]
**Describe the issue:**
When a social federated user logs in to the console, even with JIT provisioning the user's profile is not propagated with console. 

**How to reproduce:**
1. Login to IS Console as a tenant admin
2. Setup a google connector for the console settings login flow **(same for all social authentications)**
3. Login to Console with a google user
4. Verify the profile details populated in the top-right corner of the screen. 

**Actual behavior:**
1. The user only has the internal access and not the Administrator access

Screen recording: 

https://github.com/wso2/product-is/assets/106053688/fcd673cd-f687-4a7c-996e-7b1e6ef44a87

**Expected behavior:**
1. The user should have the administrator access

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]  - https://wso2.org/jenkins/job/products/job/product-is/4957/
 - OS: [e.g., Windows, Linux, Mac] - MAC
 - Database: [e.g., MySQL, H2] - MSSQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by GoushiRam** [comment]
Related to https://github.com/wso2/product-is/issues/18283

**Comment by Thisara-Welmilla** [comment]
Possible should be due to https://github.com/wso2/product-is/issues/18316

**Comment by DMHP** [comment]
@SujanSanjula96 Can you please verify whether this has been fixed from the https://github.com/wso2/product-is/issues/18316

**Comment by SujanSanjula96** [comment]
This is only partially fixed with the fix in https://github.com/wso2/product-is/issues/18283. Scope issuing part is going to be fixed with https://github.com/wso2/product-is/issues/18316 which encountered few issues considering all the scenarios. Currently working on a fix to cover all the scenarios.

**Comment by SujanSanjula96** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5303
