### ISSUE TITLE
Inconsistency in the Switch button styles

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18318]
**Is your suggestion related to an experience ? Please describe.**

We need to match the new switch styles to the Semantic one.

- E.g. - used in Login & Registration pages
<img width="157" alt="Screenshot 2023-12-02 at 15 23 50" src="https://github.com/wso2/product-is/assets/67315176/7c82b8de-76e8-4fd3-aa02-41ac5c20034b">

- New switch
<img width="110" alt="Screenshot 2023-12-02 at 15 23 30" src="https://github.com/wso2/product-is/assets/67315176/da18f03a-7d93-45b3-b924-bfbb0cc0545a">

**Comment by aaujayasena** [comment]
We don't see any enable or disable toggles on  remote log publishing page. Any reason @savindi7 


<img width="1049" alt="image" src="https://github.com/wso2/product-is/assets/39077751/835821c3-0f8c-4c8f-85bd-f94666e5076b">

**Comment by bhagyasakalanka** [comment]
We dont have backend support to enable/disable remote log publishing as of now. Currently, If we configure the remote log publishing settings, it will automatically enabled. If you need to disable, have to completely remove the all the settings.

**Comment by pavinduLakshan** [comment]
> We don't see any enable or disable toggles on remote log publishing page. Any reason @savindi7
> 

The only toggle button that has been used in this page was for enabling/disabling the `Verify the hostname` option. However, that toggle button has been removed in favor of a checkbox in a later UI revamp. Therefore, there are no toggle buttons in the current log publishing UI, and consequently we can close this issue.

The concern that there is no toggle button to just enable/disable the remote publishing feature, without reverting the existing configurations, is valid in UX perspective IMO. As discussed offline, let's create a separate issue to track that as a UX improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
