### ISSUE TITLE
[Doc]Explain the missing parameters in the doc in  TenantManagementService

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1831]
Explain the missing parameters in the doc [1] in  TenantManagementService.

[1] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs#ManagingTenantswithAPIs-addTenant()

Explain all the places where it is applicable 

tenantInfoBean.originatedService
tenantInfoBean.successKey 
tenantInfoBean.usagePlan

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
