### ISSUE TITLE
[JIT Provisioning] [Consent Provision] When the "prompt for username, password and consent" is selected and self sign up is disabled, JIT provision does not work

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18329]
**Describe the issue:**
When an IdP has selected to provide consent with prompt for username, password and consent, the user is redirected to the sign up page. And if the self sign up is disabled, the user is provided with this information only after entering the details.

**How to reproduce:**
1. Login to IS Console
2. Create an IdP
3. Enable JIT with provisioning scheme "prompt for username, password and consent"
4. Connect the IdP to an application
5. Login to the application
6. Provide the Idp information and verify the redirection > The user is redirected to the self sign up page. 
7. Once the info is given , the user is prompted to the self sign up disabled page. 

**Actual Behaviour**
1. The user is redirected to the self sign up page. 

Screenrecording:

https://github.com/wso2/product-is/assets/106053688/24578c8b-72aa-41c3-9543-fd42d50de1c4

https://github.com/wso2/product-is/assets/106053688/a7a4ddb9-a223-4855-bbe0-5311c39c40fa

**Expected behavior:**
The mandatory attributes required to create the user should be prompted to add, rather than requiring the self sign up page. Further when self sign up is disabled, the user can't proceed - the reason for this being blocker. 

**This is working in IS 6.1.0 even without enabling self sign up. The user is provided the option of selecting the username and proceed to create an account where the details are populated. Better than what we are seeing in IS 7**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by GoushiRam** [comment]
> Sending to the self-sign up page is expected, but values send in the url must be auto filtered expect the username and the password. The corresponding values for the field in the self sign up page are available as url params. Need to set them to relevant fields in UI.

This can't be the expected behaviour and the user is able to provision **without the self sign up enabled** in 6.1.0. What is the reason for the difference of behaviour here? Why do we need self sign up to provision a user?

cc: @thanujalk @malithie

**Comment by Thisara-Welmilla** [comment]
>
> This can't be the expected behaviour and the user is able to provision **without the self sign up enabled** in 6.1.0. What is the reason for the difference of behaviour here? Why do we need self sign up to provision a user?
> 
> cc: @thanujalk @malithie

In the 6.1.0 also we send the user to self-sign up page with fields already filled with the values comes from the IDP, to get the user consent. The issue here is, the fields are not already filled with the values comes from the IDP.

**Comment by GoushiRam** [comment]
> > This can't be the expected behaviour and the user is able to provision **without the self sign up enabled** in 6.1.0. What is the reason for the difference of behaviour here? Why do we need self sign up to provision a user?
> > cc: @thanujalk @malithie
> 
> In the 6.1.0 also we send the user to self-sign up page with fields already filled with the values comes from the IDP, to get the user consent. The issue here is, the fields are not already filled with the values comes from the IDP.

As discussed, skipsignupenablecheck=true is not honored at processregistration.do. This should be expected to work as 6.1.0

**Comment by GoushiRam** [comment]
In 6.1, this works as follows: when the "provision username, password and consent" is selected.
1. User logs in with the social account
2. User is provided with a page where he is prompted that he will be navigating to the sign up page
3. Once he confirms, he navigates to the sign up page. 

IS 6.1 behaviour: 

https://github.com/wso2/product-is/assets/106053688/d8a3989f-cf26-406d-8395-e8efbed95cf4

We need to align the above modification with 6.1

**Comment by pavinduLakshan** [comment]
IS 6.1 behaviour

https://github.com/wso2/product-is/assets/41533942/f81a1464-7cd4-4b78-aa4a-4c5305f33b71

IS 7 RC snapshot behaviour

https://github.com/wso2/product-is/assets/41533942/c57d256a-2020-4f84-8ffc-31024caac69a

**Comment by pavinduLakshan** [comment]
> > > This can't be the expected behaviour and the user is able to provision **without the self sign up enabled** in 6.1.0. What is the reason for the difference of behaviour here? Why do we need self sign up to provision a user?
> > > cc: @thanujalk @malithie
> > 
> > 
> > In the 6.1.0 also we send the user to self-sign up page with fields already filled with the values comes from the IDP, to get the user consent. The issue here is, the fields are not already filled with the values comes from the IDP.
> 
> As discussed, skipsignupenablecheck=true is not honored at processregistration.do. This should be expected to work as 6.1.0

Even if this property is sent in the self registration POST request as in [1], the API throws the following error.

> org.wso2.carbon.identity.mgt.endpoint.util.client.ApiException: {"code":"20021","message":"Bad Request","description":"Self sign up feature is disabled","traceId":"eb1ff597-5fcd-4d06-b3df-7dc62e49ca30"}

[1] https://github.com/wso2/identity-apps/pull/4980

**Comment by Thisara-Welmilla** [comment]
> 
>Even if this property is sent in the self registration POST request as in [1], the API throws the following error.
> > org.wso2.carbon.identity.mgt.endpoint.util.client.ApiException: {"code":"20021","message":"Bad Request","description":"Self sign up feature is disabled","traceId":"eb1ff597-5fcd-4d06-b3df-7dc62e49ca30"}
> 
> [1] [wso2/identity-apps#4980](https://github.com/wso2/identity-apps/pull/4980) 

We cannot rely on the `skipsignupenablecheck` values comes from the MePost API call and create the user if it true. Because, then anyone can add that property to the POST API and create users even though the self registration is disable for org. 
For other provisioning options, we do not user this POST API.

@pavinduLakshan  will check how we did this in IS-6.1 and other provisioning options from the fronted.

**Comment by dasuni-30** [comment]
### This is fixed in the latest pack.

https://github.com/wso2/product-is/assets/27746285/93fbd16b-7428-4e73-85df-46fc5b1caed1
