### ISSUE TITLE
Revisit Page to configure User Attribute Change Verification settings 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18326]
**Describe the issue:**
Required to revisit page to configure User Attribute Change Verification settings 

- Page title should be improve
- Descriptions are too long
- Add grouping
- Sub cases are enable even though the main cases are disable. ( ex: include upper case character, include numbers in OTP)

<img width="841" alt="image" src="https://github.com/wso2/product-is/assets/39077751/eb58a11a-1ce5-403e-9f0c-8d5e4e33c8d3">

**How to reproduce:**
1. Login to console
2. Go to user attributes and stored -> Select attibutes
3. Select "User Attribute Change Verification"

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-rc1-SNAPSHOT- buildno: 4957
 - OS: [e.g., Windows, Linux, Mac]
 - Database: postgres
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
This feature is not available on Build #4961 
<img width="1412" alt="image" src="https://github.com/wso2/product-is/assets/39077751/1bae36c6-bd1f-4d7c-ad8a-cbe68991fdb5">

**Comment by brionmario** [comment]
> This feature is not available on Build #4961 <img alt="image" width="1412" src="https://private-user-images.githubusercontent.com/39077751/287449519-1bae36c6-bd1f-4d7c-ad8a-cbe68991fdb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1Mzc2MzMsIm5iZiI6MTcwMTUzNzMzMywicGF0aCI6Ii8zOTA3Nzc1MS8yODc0NDk1MTktMWJhZTM2YzYtYmQxZi00ZDdjLWFkOGEtY2JlNjg5OTFmZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE3MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZDgxMDMzNjZlY2RmMGY4MTQ2Mzk2YzM4NWI5NzVkMmRjYWZhNzczYTBmY2U4OTgxOWQwOTkyNWUwMTg3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TfGXakhAcMXQy9ndG2ARpIJKrwEL0HTDPo4HoGPhCfE"> @brionmario @jeradrutnam is this expected?

Will check this and verify. There was a config rename and seems like the build `#4961` doesn't have the latest framework verion.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
