### ISSUE TITLE
Internal Scopes don't have any descritptions

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#18320]
**Describe the issue:**
With the https://github.com/wso2/product-is/issues/17904 improvement, we are showing scope descriptions on the consent page. Currently non of our internal scopes has any description. We need to add meaningful descriptions to each of our internal scopes

**Comment by Thisara-Welmilla** [comment]
The description of the scope has been drafted for the existing scopes. Currently awaiting the finalization of API categorization and scope names to complete the review and finalization of the description.

**Comment by PasinduYeshan** [comment]
This issue is fixed with following PR. 
- https://github.com/wso2/carbon-identity-framework/pull/5378
