### ISSUE TITLE
Disabling self-registration account verification does not work

### ISSUE THREAD

**Issue by AmshikaH** [wso2/product-is#18321]
**Describe the issue:**

In the self-registration flow, when `Account verification` is disabled, the server still attempts account verification and does not allow a user to login without completing the email verification.

In the self-registration flow, even when `Account verification` is not enabled in the self-registration configurations, the user is asked to activate their account by checking their inbox.

![image](https://github.com/wso2/product-is/assets/66556626/4e72f7dc-feba-41e5-a0ad-faae894c609e)

If the smtp email sender configurations are found in the deployment.toml file, the email is sent;

![image](https://github.com/wso2/product-is/assets/66556626/56985cbc-66a3-4247-a200-ae52f74b8d5b)

If the smtp email sender configurations are not found in the deployment.toml file, email sending fails with the following exception.

```
[2023-12-02 15:20:28,198] [6a2a7141-e7c3-47b0-9019-9d9c60e20297] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Exception occurred when sending email to user@gmail.com. 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials fb3-20020a056a002d8300b006bde2480806sm4303238pfb.47 - gsmtp
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials fb3-20020a056a002d8300b006bde2480806sm4303238pfb.47 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

When the user attempts to login via the account created, they are asked to complete their account verification as shown below.

![image](https://github.com/wso2/product-is/assets/66556626/8392f77e-4180-4ab4-bc98-94aad9072af1)

In the self-registration page, the help box says that it is "recommended" to enable account verification. However, based on the behaviour, it appears to be mandatory.

![image](https://github.com/wso2/product-is/assets/66556626/ac4f5cb2-9686-47ee-b5e9-08da73754a02)

There is a configuration called `Activate account immediately` which is only visible when `Account verification` is enabled. If this is the only way to activate the account created by the user regardless of the email verification status, this defeats the purpose of allowing `Account verification` to be enabled/disabled. 

**How to reproduce:**

1. Add the following configurations to the deployment.toml file with valid email login credentials.
```[output_adapter.email]
from_address="abcd@gmail.com"
username="abcd"
password="xxxx"
hostname="smtp.gmail.com"
port=587
enable_start_tls=true
enable_authentication=true
```
2. Login to the Console.
3. Go to Login & Registration > User Onboarding > Self Registration and enable self-registration.
4. Leave the remaining configurations as they are - with `Account verification` disabled.
5. Go to My Account and click on Register.
6. Fill in the details for a new user and click on Sign Up.

The verification email will be sent to the user's email despite `Account verification` being disabled. If step 1 is skipped and the email sender configurations are not added, the server's attempt to send the verification email fails and the stack trace given above will be printed.

**Expected behavior:**

When `Account verification` is disabled, the email verification process should be skipped and the user should be allowed to register and login without email verification or the configuration `Account verification` should not support being disabled.

**Environment information:**
 - Product Version: wso2is-7.0.0-rc1-SNAPSHOT
 - OS: Mac

**Comment by Thisara-Welmilla** [comment]
The `Account verification` must be enabled if `SelfRegistration.LockOnCreation` is true or `SendConfirmationOnCreation` is true.

```
SendConfirmationOnCreation = true & SendConfirmationOnCreation = true -> Account verification = enabled, Activate account immediately = disabled
SendConfirmationOnCreation = true & SendConfirmationOnCreation = false -> Account verification = enabled, Activate account immediately = enabled
SendConfirmationOnCreation = false & SendConfirmationOnCreation = true -> Account verification = enabled, Activate account immediately = disabled
SendConfirmationOnCreation = false & SendConfirmationOnCreation = false -> Account verification = disabled, Activate account immediately = disabled
```

**Comment by savindi7** [comment]
Verified in the new pack
