### ISSUE TITLE
[Custom Connector][RC-Based]- Custom Connector testing

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18324]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**

- [ ] GitHub
- [ ] Office 365
- [ ] Twitter
- [x] Facebook
- [x] Google 
- [ ] Microsoft Windows Live
- [ ] Passive STS
- [ ] IWA Kerberose
- [ ] Saml
- [ ] Apple 
- [ ] OpenID Connect

**Describe the solution you would prefer**

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by GoushiRam** [comment]
https://github.com/wso2/product-is/issues/18378
https://github.com/wso2/product-is/issues/18377
