### ISSUE TITLE
[Doc] Ask user to set the ip address of the server accordingly instead of adding 127.0.0.1 as the website 

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1832]
2nd step under 'Configuring the Twitter App' in [1] asked user to enter 'http://127.0.0.1' as the website url. But rather than explicitly saying to put the home address, it's better to ask the user to add the server address instead.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Twitter+Authenticator#ConfiguringTwitterAuthenticator-ConfiguringtheTwitterAppConfiguringtheTwitterApp

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
