### ISSUE TITLE
Role attribute config that doesn't have the option to pick the role claim

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#18338]
**Describe the issue:**
There's a role attribute configuration section under the 'User Attributes' configuration  which confuses what that really means

<img width="805" alt="Screenshot 2023-12-02 at 7 51 02 PM" src="https://github.com/wso2/product-is/assets/4951983/151b4325-e480-475c-93cc-c1b847631cfb">

**How to reproduce:**
1. Added a traditional web app with OIDC protocol
2. Navigate to 'User Attributes' configuration and above section is visible and it's not possible to pick an attribute other than the user name until the attributes to be passed to the app is configured and the complete section is saved.
3. If you clicked the drop down you will have to update the app choosing 'username' as the role attribute and after saving have to repick 'role' attribute and save

**Expected behavior:**
1. Given that we have now provided adding application roles, for any new user who is using the product this should not be visible. And by default role claim is fixed and defined within the system for apps the choice is to select the role claim to be passed in user attributes. Related issue https://github.com/wso2/product-is/issues/18337
4. For users migrating/upgrading from prior versions they should be able to the role to application role mapping in the "Roles" section. IIRC this role claim is defined for the system even in that scenario, and both groups and internal roles can be mapped with the roles the developer expects to have in his app. Recheck this behaviour with the carbon console before proceeding
5. Additionally if 'Include user domain' is ticked in subject side IMO, it should be applicable here (New behaviour for new customers). Recheck if there was a separate config provided in prior IS version and if for users upgrading that should be preserved
6. Further above experience should be consistent for all application templates other than the M2M template where roles doesn't apply

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7 RC SNAPSHOT build:4959

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by malithie** [comment]
Added severity as critical given the first user experience problem on a primary flow of the product

**Comment by PasinduYeshan** [comment]
This section is already removed. 
- https://github.com/wso2/product-is/issues/18190
