### ISSUE TITLE
[Doc] No information available about Identity provider configurations with API related to Twitter Federated authenticator

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1833]
**Environment** 
IS 5.4.0
Refer to doc [1]. No information available about Identity provider configurations with API related to Twitter Federated authenticator
[1]. https://docs.wso2.com/display/IS540/Identity+Provider+Configurations+used+with+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
