### ISSUE TITLE
Have 'roles' added as a default OIDC scope and ship it by default

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#18337]
**Is your suggestion related to an experience ? Please describe.**
Given now that the product supports application roles, and role to scope mapping, having 'roles' defined in the IS by default as a OIDC scope will simplify the user experience for developers to pass that scope to applications just by adding it in the 'attribute' configuration section of the app without going over docs and having hard time to figure out how to pass roles to the application in the id token

**Describe the improvement**
Add roles to the OIDC scopes by default
<img width="1157" alt="Screenshot 2023-12-02 at 7 39 16 PM" src="https://github.com/wso2/product-is/assets/4951983/02c4d873-2204-4e61-8009-46c311820a75">

**Comment by malithie** [comment]
Added severity as critical given this is a common flow and a common expectation for those who try to do RBAC for their apps

**Comment by ZiyamSanthosh** [comment]
This is done. Hence closing the issue.
