### ISSUE TITLE
Something went wrong when accessing the Analytic page

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18334]
**Describe the issue:**

<img width="269" alt="Screenshot 2023-12-02 at 18 58 20" src="https://github.com/wso2/product-is/assets/39077751/15a54809-4954-4fdd-bfba-44b9308ded38">
<img width="955" alt="image" src="https://github.com/wso2/product-is/assets/39077751/24ed62e4-f251-405a-b36f-bffa8199ab40">

**How to reproduce:**
1. Login to the console
2. Navigate to  the Analytic

**Expected behavior:**
No error 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
The Analytics page is removed from the side panel with the PR https://github.com/wso2/identity-apps/pull/4903. This is not reproducible.
