### ISSUE TITLE
[GitHub][Silent Provisioning] User is unable to provision via GitHub 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18336]
**Describe the issue:**
When the user logs into github (with provisioning enabled) the user is not provisioned. 

**How to reproduce:**
1. Login to IS Console
2. Configure a github connector, enable silent provisioning
3. Connect the github IdP to the application
4. Login to the application via GitHub
5. Verify the provisioned user

**Actual behavior:**
1. The user is NOT provisioned

Screen recording: 

https://github.com/wso2/product-is/assets/106053688/fc73e17b-7065-4401-b490-21497ba0f067

Error Stacktrace: 
[stacktrace.txt](https://github.com/wso2/product-is/files/13536467/stacktrace.txt)

**Expected behavior:**
The user should be provisioned successfully

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashensw** [comment]
This is not reproducible in the latest pack. wso2is-7.0.0-rc1-SNAPSHOT built on 04/12/2023. The Github user is getting provisioned correctly.
