### ISSUE TITLE
[JIT Provisioning][Consent Provision] - When the "prompt for password and consent" is selected, user doesn't have the means to enter the password :)

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18331]
**Describe the issue:**
When an IdP has selected to provide consent with prompt for password and consent, the user is redirected to a page that doesn't have a password field. 

**How to reproduce:**

1. Login to IS Console
2. Create an IdP
3. Enable JIT with provisioning scheme "prompt for username, password and consent"
4. Connect the IdP to an application
5. Login to the application
6. Provide the Idp information and verify the redirection

**Actual behavior:**
1. The user is not provided with an option to enter the password

Screen recording: 

https://github.com/wso2/product-is/assets/106053688/bfa535b2-f5b2-4584-8d5c-80e40166c596

**Expected behavior:**
1. The user should be provided with an option to enter the password when this option is selected

**This is working in IS 6.1.0 where the user can enter the password**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] https://wso2.org/jenkins/job/products/job/product-is/4957/
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thisara-Welmilla** [comment]
The `passwordProvisionEnabled=true` URL param is sending in the redirection url which is send in the response of the commonauth call to indicate the password need to provided.

The showing the password field has been removed with https://github.com/wso2/identity-apps/commit/81578bff7edfc317ad7f7d66b6bd366f97911586#diff-4de4d4b15e1ab0f295ff4495903989c4a187039b66c3764f8d22b1698a3c2e8dL373-L387

**Comment by DilshanSenarath** [comment]
The problem arose with the UI unification, leading to the removal of the two password fields introducing a hidden field for password. We should verify the potential impact on the other end if we introduce these two password fields.

**Comment by dasuni-30** [comment]
### Fixed in the new pack

<img width="922" alt="Screenshot 2023-12-09 at 19 59 10" src="https://github.com/wso2/product-is/assets/27746285/6da31665-e7c6-4d3c-80fb-29c614c3ff78">
