### ISSUE TITLE
Tenant Id should be manually set to create a tenant using wso2admin services

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1834]
Tenant Id should be manually set to create a tenant using wso2admin services. But according to the doc we do not have to pass a value. 
Tenant ID should not be a mandatory user input field. Document sample request shows as we do not have to input any value [1]

[1] https://docs.wso2.com/display/IS540/Managing+Tenants+with+APIs#ManagingTenantswithAPIs-addTenant()
When you do not specify ID, it will gives 'unknown' soap error 500 error code

Request : 

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.mgt.tenant.carbon.wso2.org" xmlns:xsd="http://beans.common.stratos.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:addTenant>
         
         <ser:tenantInfoBean>
            
            <xsd:active>true</xsd:active>
            
            <xsd:admin>admin</xsd:admin>
            
            <xsd:adminPassword>ushani1</xsd:adminPassword>
            
            <xsd:createdDate></xsd:createdDate>
            
            <xsd:email>ushani@wso2.com</xsd:email>
            
            <xsd:firstname>Ushani</xsd:firstname>
            
            <xsd:lastname>Balasooriya</xsd:lastname>
            
            <xsd:originatedService></xsd:originatedService>
            
            <xsd:successKey></xsd:successKey>
            
            <xsd:tenantDomain>ushani3.com</xsd:tenantDomain>
            
            <xsd:tenantId></xsd:tenantId>
            
            <xsd:usagePlan></xsd:usagePlan>
         </ser:tenantInfoBean>
      </ser:addTenant>
   </soapenv:Body>
</soapenv:Envelope>`

Response : 

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode>soapenv:Server</faultcode>
         <faultstring>unknown</faultstring>
         <detail/>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
