### ISSUE TITLE
[Legacy Mode] Getting an empty page when creating application

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18359]
**Describe the issue:**

Getting an empty page when creating application

![spa](https://github.com/wso2/product-is/assets/40081059/1c09ed0c-61dd-414e-87e7-b1e04117d4c2)

https://github.com/wso2/product-is/assets/40081059/57eca96b-1e6c-4daf-af3d-8385175366b9

**How to reproduce:**

1.Login to the console
2.Go to applications
3.Create a new application

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7 legacy snapshot]
 - OS: [e.g., Windows]
 - Database: [e.g., MySQL, H2]
 -
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Happening due to the Path issues mentioned in:

- https://github.com/wso2/product-is/issues/18366
- https://github.com/wso2/product-is/issues/18418

Fixed with: https://github.com/wso2/identity-apps/pull/5043
