### ISSUE TITLE
[Legacy mode config enabled]Getting 404 error message after log in to the console.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18352]
**Describe the issue:**
Getting 404 , Something went wrong error pop up right after login in to the console [Legacy pack]
![Screenshot 2023-12-03 at 10 51 38](https://github.com/wso2/product-is/assets/41188245/8f72a476-8c91-4a27-bb22-7495cdf17785)

![Screenshot 2023-12-03 at 10 52 09](https://github.com/wso2/product-is/assets/41188245/d7b276cc-4383-4fcb-b397-5391e3473f2a)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  WSO2 Identity Server-7.0.0-rc1-SNAPSHOT Legacy
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
- Fix: https://github.com/wso2/identity-apps/pull/4983

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-rc1-SNAPSHOT

https://github.com/wso2/product-is/assets/37938529/9a029c33-b759-45ea-be30-ac75e9c8cef6
