### ISSUE TITLE
[Legacy Mode] Redirecting to a blank page when trying to add a connecting to an application through Connection's > Quick start page. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18361]
**Describe the issue:**

$Subject Redirecting to a blank page  from

https://github.com/wso2/product-is/assets/41188245/254295e5-664d-46b5-bf63-12c67604d9f2

![Screenshot 2023-12-03 at 12 29 16](https://github.com/wso2/product-is/assets/41188245/bd5c3389-1616-488e-a7a5-bd7cf05578a9)

**How to reproduce:**

1. Redirect to connections page 
2. Select SMS OTP > Set up
3. Navigate to Quick Start
4. Click on Application link in `Select Application` step.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
Possibly related to https://github.com/wso2/product-is/issues/18366

**Comment by brionmario** [comment]
Modified the `j2` to honor  `legacy_mode.enabled` and `legacy_authz_runtime.enable`  as well when resolving `isSaas` since the apps are `SaaS` in the legacy mode.

```j2
    {% if console.is_saas is defined %}
    "isSaas": {{ console.is_saas }},
    {% elif legacy_mode.enabled is defined %}
    "isSaas": {{ legacy_mode.enabled }},
    {% elif legacy_authz_runtime.enable is defined %}
    "isSaas": {{ legacy_authz_runtime.enable }},
    {% endif %}
```

PR: https://github.com/wso2/identity-apps/pull/5043
