### ISSUE TITLE
[Legacy Mode] After adding a new group, the recently created group is not displayed on the group page, and no success message is shown.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18367]
**Describe the issue:**
After adding a new group, the newly added group is not visible on the group page. Additionally, no success message is displayed, making it difficult to confirm whether the group was created successfully.

**How to reproduce:**

1. Redirected to the Groups page
2. Create a new group
3. The created group will not be visible. 

**Expected behavior:**
The newly created group should be listed on the group page, and a success message should be displayed to confirm the successful addition.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: RC Legacy pack
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR. 
- https://github.com/wso2/identity-apps/pull/4977
