### ISSUE TITLE
[Legacy Mode] Getting incorrect console URL path when loggd in 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18366]
**Describe the issue:**

Getting incorrect console URL path  when logged in . No error logs are generated as well

<img width="1362" alt="Screenshot 2023-12-03 at 14 09 47" src="https://github.com/wso2/product-is/assets/40081059/11d2801f-9ca2-4400-9a09-a391626a6a90">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7 legacy snapshot]
 - OS: [ Mac]
 - Database: [H2]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Related Issue: https://github.com/wso2/product-is/issues/18418

**Comment by brionmario** [comment]
Modified the `j2` to honor  `legacy_mode.enabled` and `legacy_authz_runtime.enable`  as well.

```j2
    {% if console.is_saas is defined %}
    "isSaas": {{ console.is_saas }},
    {% elif legacy_mode.enabled is defined %}
    "isSaas": {{ legacy_mode.enabled }},
    {% elif legacy_authz_runtime.enable is defined %}
    "isSaas": {{ legacy_authz_runtime.enable }},
    {% endif %}
```

PR: https://github.com/wso2/identity-apps/pull/5043
