### ISSUE TITLE
[Legacy Mode] My Account self service portal is not available

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18362]
**Describe the issue:**

My Account self service portal is not available

https://github.com/wso2/product-is/assets/40081059/2bb04dd0-7563-4c1d-a506-7db65c3c99c2

**How to reproduce:**
1.Login into the console
2.Go to application
3.Click on my Account self service portal

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7 legacy snapshot]
 - OS: [Windows]
 - Database: [H2]
 

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
Possibly related to https://github.com/wso2/product-is/issues/18366

**Comment by brionmario** [comment]
Happening due to the Path issues mentioned in:

- https://github.com/wso2/product-is/issues/18366
- https://github.com/wso2/product-is/issues/18418

Fixed with: https://github.com/wso2/identity-apps/pull/5043
