### ISSUE TITLE
[Latest Build] Missing UI Elements and Error Messages with MySQL as Primary Database

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18360]
**Describe the issue:**
issues with the console (UI) when configured to use MySQL as the primary database. Several UI elements are missing, and error messages are displayed.

**How to reproduce:**
Configure  MySQL as the primary database.
Start the Server.
Log in to the console.
Navigate through different sections of the UI and observe missing elements and error messages.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: wso2is-7.0.0-rc1-SNAPSHOT
OS:Mac
Database: MySql
Userstore: JDBC
Build : https://wso2.org/jenkins/job/products/job/product-is/4962/

Toml 
```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:mysql://localhost:3306/rc101?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"


[database.shared_db]

url = "jdbc:mysql://localhost:3306/rc101?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

# The KeyStore which is used for encrypting/decrypting internal data. By default the primary keystore is used as the internal keystore.

#[keystore.internal]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

# The KeyStore which is used for tls communication. By default the primary keystore is used as the tls keystore.

#[keystore.tls]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

#Google reCAPTCHA settings.

#[recaptcha]
#enabled = true
#api_url = "https://www.google.com/recaptcha/api.js"
#verify_url = "https://www.google.com/recaptcha/api/siteverify"
#site_key = ""
#secret_key = ""

# SMTP email sender settings.
#[output_adapter.email]
#from_address= "abcd@gmail.com"
#username= "abcd"
#password= "xxxx"
#hostname= "smtp.gmail.com"
#port= 587


```
---

https://github.com/wso2/product-is/assets/39120228/8ac41c85-41e8-402c-a16e-e2b6162776d7

<img width="1724" alt="Screenshot 2023-12-03 at 12 25 14" src="https://github.com/wso2/product-is/assets/39120228/4dc9aac1-5940-4291-857b-045423c0e932">

**Comment by sadilchamishka** [comment]
Shall we check for a new DB with the deployment.toml configs added according to this documentation https://is.docs.wso2.com/en/latest/deploy/change-to-mysql/

If you set default auto commit = false, make sure to have both of the below configs.
```
defaultAutoCommit=false
commitOnReturn=true
```

**Comment by NipuniBhagya** [comment]
Removing the UI label as this is not a UI issue but a MySQL configuration issue.
