### ISSUE TITLE
Console sends too many GET requests in Connections page

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18368]
**Describe the issue:**

$subject

<img width="1502" alt="Screenshot 2023-12-03 at 14 17 51" src="https://github.com/wso2/product-is/assets/41533942/7d5f0d56-0484-4bb6-bfa8-4ac42d6e18f7">

**How to reproduce:**

1. Sign into console.
2. Open the browser devtools and navigate to Connections page.
3. Observe that in the network panel, there are 4 identical GET requests being sent.

**Expected behavior:**

There should be only one GET request occurred.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
