### ISSUE TITLE
Even though claim order for a claim is set to 1 it is shown 2nd in the list

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1837]
*Environment*
```
IS 5.4.0
Ubuntu 14
Java version "1.8.0_51"
Firefox 55
DB - MySQL
```
Added a new claim and configured it with 1 as the claim display order. Refer below image. It states that the claims are ordered considering the same dialect.

*Steps*

1. Login to management console and navigate to claims section
2. Add a local claim and set the Display Order to 1
3. View a user from the console

Issue
Even though the order is set as 1 the claim is set as second in the order.

![createclaim](https://user-images.githubusercontent.com/17248809/34203607-d68d4c7a-e5a1-11e7-9f36-75211d1740ee.png)
![1](https://user-images.githubusercontent.com/17248809/34203614-d92aaa04-e5a1-11e7-8a60-0ead80843631.png)

**Labels** IS 5.4.0 , Bug

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
