### ISSUE TITLE
[Legacy Mode] Console is not accessible when host is changed and DB is H2

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18370]
**Describe the issue:**
<img width="1657" alt="Screenshot 2023-12-03 at 14 18 11" src="https://github.com/wso2/product-is/assets/29881881/93dd6e3f-9670-4857-b72b-17b42f52f381">

Stucked in console loading hostname changed and database h2

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
@UdeshAthukorala is this related to https://github.com/wso2/product-is/issues/18163?

**Comment by asekawa** [comment]
This is happening when we change the hostname into anothename
[server]
hostname = "xxxx"

Note:did the necessary config changes in etc/hosts file as well

**Comment by madurangasiriwardena** [comment]
Could not be reproduced in the latest distribution. 

@Buddhimah can you check if this is happening only when legacy mode is enabled? If so can you add the exact configs you have used?
