### ISSUE TITLE
[Legacy Mode] Getting  errors when navigating to organization section due to unsupported organization specific routing endpoint.

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18371]
**Describe the issue:**
'
Getting  errors when navigating to organization section due to failure unsupported organization specific routing endpoint.

https://github.com/wso2/product-is/assets/40081059/5a84e55f-aaf5-4e4c-a3a4-1f248d28239b

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
This will be fixed via https://github.com/wso2/identity-apps/pull/4933 as we will be disabling `Organization` section in legacy mode

**Comment by nipunsampath** [comment]
When enabled the legacy runtime in a fresh pack (from the nightly build on 15th Dec) I got this error again. Furthermore, I can see the `Organization` section in the console. Please refer to the screencast below.


https://github.com/wso2/product-is/assets/27700915/356922ae-b6ce-46bf-98f5-125a140eee64
