### ISSUE TITLE
[Legacy Mode] Getting error when navigating to Analytics section due to a issue in retrieving governance connector.

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18379]
**Describe the issue:**

Getting error when navigating to Analytics section due to a issue in retrieving governance connector.

https://github.com/wso2/product-is/assets/40081059/235b8669-3e62-4a07-b48b-fba39e3f8f7e

**How to reproduce:**

1.Login to the console
2.Navigate to analytics section

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7 legacy snapshot]
 - OS: [ Windows]
 - Database: [H2]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
This is reported with https://github.com/wso2/product-is/issues/18334
