### ISSUE TITLE
[Doc] Move the Note at the end of 2nd step under 'Configuring the Twitter App' to not to confuse the customer

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1838]
2nd step under 'Configuring the Twitter App' in [1] describes about configuring twitter application with appropriate hostname. Here, it's better to move the note under 3rd bullet point to bottom of that since the next line ( For example https://apps.customhost.com:9443/commonauth) describes about commonauth configs in application.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Twitter+Authenticator#ConfiguringTwitterAuthenticator-ConfiguringtheTwitterAppConfiguringtheTwitterApp

**Comment by ShirazAzad** [comment]
Fixed. But there are few issues in the page which I am in the process of fixing.
