### ISSUE TITLE
Add Authentication Context Class Documentation to IS 7

### ISSUE THREAD

**Issue by himeshsiriwardana** [wso2/product-is#18399]
Add documentation missing from IS 6.1 and the previous versions.

https://is.docs.wso2.com/en/5.10.0/learn/working-with-acr-and-amr/#requesting-the-acr-with-oauth2
https://is.docs.wso2.com/en/latest/guides/adaptive-auth/acr-based-adaptive-auth/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
