### ISSUE TITLE
Add SSO documentation for SAAS applications

### ISSUE THREAD

**Issue by himeshsiriwardana** [wso2/product-is#18392]
**Is your suggestion related to a missing or misleading document? Please describe.**
Documentation that is in 6.1 [1] related to SSO in SAAS applications is missing from IS 7 documentation.

[1] https://is.docs.wso2.com/en/latest/guides/login/log-into-google-using-is/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
