### ISSUE TITLE
[Connector Store]Update IS 5.4.0 version as supported versions in  connector store for Email OTP Authenticator  

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1839]
Update  IS 5.4.0 as supported version for  Email OTP Authenticator in connector store.
https://store.wso2.com/store/assets/isconnector/details/9edc37f6-873c-408c-a532-bbb386d71e08
![emailotp](https://user-images.githubusercontent.com/13656890/34204022-219f872c-e5a3-11e7-8619-42da3bf96c93.png)]

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
