### ISSUE TITLE
Migrate Deprecated Features to IS Connector Store

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#18407]
We have deprecated certain features like challenge questions and workflow features. These are planned to be hosted as connectors, but they are not yet available in the IS connector store.

Objective

- To oversee the migration of deprecated features (challenge questions and workflow features) to the IS connector store.

Tasks

- [ ]  Migrate deprecated features to connectors.
- [ ]  Test the migrated features for compatibility and performance.
- [ ]  Host the new and migrated connectors in the IS connector store.
- [ ]  Update documentation to reflect these changes.

**Comment by Rashmini** [comment]
Moving HYPR connector resource files to the IS Connector store is tracked with https://github.com/wso2/product-is/issues/18416

**Comment by asha15** [comment]
Closing the issue as the connectors are hosted in the connector store
Challenge Questions connector: https://store.wso2.com/store/assets/isconnector/details/1f79b51f-acae-4365-83ab-a2f1a6b690f9
Workflow connector: https://store.wso2.com/store/assets/isconnector/details/1ab83e39-15f9-40f2-a905-1053713b17e0
