### ISSUE TITLE
[Doc] Identity provider configurations used with APIs does not have all the parameters related to yahoo and Google IDPs

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1840]
**Environment** 
IS 5.4.0

Refer to doc [1]. Identity provider configurations used with APIs does not have information about all the parameters related to yahoo and Google Federated Authenticators.

[1].https://docs.wso2.com/display/IS540/Identity+Provider+Configurations+used+with+APIs#IdentityProviderConfigurationsusedwithAPIs-Googleconfiguration

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
