### ISSUE TITLE
[Legacy Mode] Regression testing with Legacy Mode configs enabled[Windows/OS Focus]

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18402]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**

[Legacy Mode] Regression testing with Legacy Mode configs enabled[Windows/OS Focus]
In this task, A regression round will be conducted on the legacy pack in Widows operating system,. To verify and compare the IS 6.1 product and the IS 7.0.0 pack. 

- [x] Manage Users
- [x] Manage Administrators
- [x] Manage Groups
- [ ] Manage active sessions
- [x] Register an OpenID Connect single-page app
- [x] Register an OpenID Connect web app
- [x] Register a SAML web app
- [ ] Tenant creation
- [x] Register a standard-based application
- [x] Register a mobile app
- [ ] Magic Link Login
- [ ] FIDO2 Login
- [ ] HYPR Login
- [ ] Email OTP Login
- [ ] Add Facebook Login
- [ ] Add Google Login
- [ ] Add Microsoft Login
- [ ] Add Apple Login
- [ ] Sign in with Ethereum
- [x] #18401
- [x] #18400
- [ ] Add TOTP
- [ ] Add Email OTP
- [ ] Add User Preferred MFA
- [ ] Configure OIDC flows
- [ ] Configure SAML flows
- [ ] Configure JIT User Provisioning
- [ ] Configure the token exchange flow.
- [ ] Register an API resource
- [x] Configure UI Branding
- [ ] Customize The email templates
- [ ] Configure the email provider
- [ ] Configure Self service portal
- [ ] Configure password recovery
- [ ] configure self registration
- [ ] Manage Account Security
- [ ] Manage Account login
- [x] Self Service Portal
- [ ] Build self service capabilities]
- [ ] Analyze login attempts
- [ ] Analyze active sessions
- [x] ELK analytics

**Describe the solution you would prefer**

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
