### ISSUE TITLE
After unshare with all orgs, the radio button is set to share with a selected orgs.

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18410]
**Describe the issue:**

https://github.com/wso2/product-is/assets/35717390/a3e7158d-b361-4113-bd46-d8fd954a15b5

**How to reproduce:**

1 - Share app with all orgs.
2 - Navigate to a different place and come back to app sharing section.
3 - Try unshare with all orgs.

**Comment by JayaShakthi97** [comment]
- Fix: https://github.com/wso2/identity-apps/pull/4971

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-rc1-SNAPSHOT

https://github.com/wso2/product-is/assets/37938529/3e84dc80-0a3f-4e4f-9632-84a8a69fdaa8
