### ISSUE TITLE
[Doc] Document that how organization inherit claims defined from root organizations

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18415]
**Describe the issue:**

Document the facts related to https://github.com/wso2/product-is/issues/16702

**Comment by AnuradhaSK** [comment]
The adding document for IS-7.1.0 should be added to IS-7.0.0 docs as well

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
