### ISSUE TITLE
Add Facebook login Documentation should be updated.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18413]
**Is your suggestion related to a missing or misleading document? Please describe.**

The documentation needs updating to align with the new UI on the [Facebook developer portal](https://developers.facebook.com/apps). Requesting revisions to ensure compatibility with the latest interface changes.

Doc link - [Add Facebook login](https://is.docs.wso2.com/en/next/guides/authentication/social-login/add-facebook-login/)

**Describe the improvement**

After the first step, 2nd should be this.

<img width="1444" alt="Screenshot 2023-12-04 at 18 06 11" src="https://github.com/wso2/product-is/assets/41188245/a942395f-048d-4f4a-b3a4-dba5456d0c83">

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
