### ISSUE TITLE
[Legacy Mode]Tenant admins can't use the react console. Gives authorization error since API path doesn't have tenant domain

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18418]
**Describe the issue:**
1. Create a tenant via mgt console
2. log in to the new Console application based on tenant admin credentials.
3. The invoked API paths don't contain the tenant domain
4. Therefore, getting authorization issues

https://github.com/wso2/product-is/assets/25483865/664bacc3-cc6f-4de6-99c6-84884cbf9233

tested in DB type: H2 and Mssql

**Comment by brionmario** [comment]
Adding the following config fixes the issue.

```
[console]
is_sass=true
```

Need to validate if this is actually necessary since `legacyAuthzRuntime` means the same thing in IS7.

**Comment by brionmario** [comment]
Modified the `j2` to honor  `legacy_mode.enabled` and `legacy_authz_runtime.enable`  as well.

```j2
    {% if console.is_saas is defined %}
    "isSaas": {{ console.is_saas }},
    {% elif legacy_mode.enabled is defined %}
    "isSaas": {{ legacy_mode.enabled }},
    {% elif legacy_authz_runtime.enable is defined %}
    "isSaas": {{ legacy_authz_runtime.enable }},
    {% endif %}
```

PR: https://github.com/wso2/identity-apps/pull/5043
