### ISSUE TITLE
General configuration required on "Configuring a SP and IdP Using Configuration Files"

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-is#1842]
**Documentation:** Configuring a SP and IdP Using Configuration Files [1].

**Issue Identified:** According to the topic in the documentation, users may try to find how we are going to add SP and IdP using configuration files rather than UI. 

The first topic ("Adding the service provider in the identity provider IS") identify adding SP through management console and then other topics describe how we are going to add IDP and SP limiting to Travelocity web app.  

It should describe how we can add SP and IDP generally with all possible mechanisms. For an example, as a user, I may not aware how to add SP with OAuth inbound authenticator. So we have to have the general configuration which addresses all possible values.

[1] https://docs.wso2.com/display/IS540/Configuring+a+SP+and+IdP+Using+Configuration+Files

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
