### ISSUE TITLE
Creation wizard position change on window when inactive for a long time

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18423]
**Describe the issue:**
Creation wizard position change on window when inactive for a long time.

https://github.com/wso2/product-is/assets/39077751/331cf326-6b68-499c-ba0c-dfceab87a00c

**How to reproduce:**
1. Login to console
2. Go to user store creation page 
3. Click new user store 
4. Idle until show warning message inactive for long time
5. Click go back

**Expected behavior:**
Once click the go. back will refresh the page and there, UI popup wizards positioning should be correct. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
This is not reproducible for Application creation wizard. 


https://github.com/wso2/product-is/assets/39077751/3788cdfd-5cbe-40bc-b7fc-31d3af525581

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
