### ISSUE TITLE
[Doc] Add missing API docs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18427]
**Is your suggestion related to a missing or misleading document? Please describe.**
The following set of APIs is not documented.  Check the validity and add the APIs to public docs (some might not be promoted)

- [x] - Advisory Management API /api/server/v1/admin-advisory-management/banner
- [x]  - Association Management API (Admin and user both)
- [x]  - Authenticators Management API | /api/server/v1/authenticators
- [x] - Extension Management API | /api/server/v1/extensions
~- [ ] - Identity Verifier Management API | /api/server/v1/idv-providers~-> Not documenting because feature is not fully completed
~- [ ] - Secret Type Management API | /api/server/v1/secret-type~ -> Not documenting due to https://github.com/wso2/product-is/issues/19515
~- [ ] - Secret Management API | /api/server/v1/secrets~ -> Not documenting due to https://github.com/wso2/product-is/issues/19515
~- [ ] - IDV Claim Management API | /api/users/v1/(.*)/idv~ -> Not documenting because feature is not fully completed
- [x] - User Management API | /api/identity/user/v1.0
- [x] - Brading Preferences API | /api/server/v1/branding-preference
- [x] - Account Recovery API | /api/users/v2/recovery
- [x] - Expired password identification API | /api/server/v1/expired-password-identification
- [x] - Functionality Management API (Admin and user API) | /api/users/v1/(.*)/user-functionality/(.*)
- [x] - Organization Discovery API | /api/server/v1/the organizations/discovery
- [x] - Offline user invite API
- [x] - Idle user account identification API
- [x] - Input Validation Rest API

Add missing organization-level APIs
- [x] Branding API
- [x] Idle Account Identification Management API | /o/api/idle-account-identification/v1/inactive-users
- [x] Claim Management API | /o/api/server/v1/claim-dialects
- [x] Identity Recovery | /o/api/identity/recovery
- [x] Authenticators Management API | /o/api/server/v1/authenticators
- [x] Expired Password Identification API | /o/api/server/v1/expired-password-identification
- [x] Organization Discovery API | /o/api/server/v1/organizations/discovery
- [x] SCIM2 Bulk API | /o/scim2/Bulk
- [x]  Offline user invite API

**Comment by Rashmini** [comment]
Expired password identification API: Refer https://github.com/wso2/product-is/issues/18777
