### ISSUE TITLE
My account link for the invited flows are not teneted. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18430]
**Describe the issue:**
My account link for the invited flows are not tented. 
Link: https://wso2.is:9443/myaccount

<img width="984" alt="image" src="https://github.com/wso2/product-is/assets/39077751/90da03a5-4cdd-41e4-b6a7-8c9d60f09b4a">

**How to reproduce:**
1. Login to console (teneted)
2. Do user invite to set a password flow
3. Get the link received for the email
4. Click and set the password.
5.  Click the My account link to access the tented my account

**Expected behavior:**
User should be navigate to the teneted my account login page. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
Presently, on the frontend side, we extract the My Account link URL using the `IdentityManagementEndpointUtil.getUserPortalUrl` method (source: [link](https://github.com/wso2/carbon-identity-framework/blob/1c829bd29ce6ee17b6b4a2fcc1ee052124ca87f9/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementEndpointUtil.java#L183-L207)). However, the current behavior of this method is limited to returning only the My Account URL for the super tenant and does not include the tenanted My Account URL (source: [link](https://github.com/wso2/carbon-identity-framework/blob/1c829bd29ce6ee17b6b4a2fcc1ee052124ca87f9/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementEndpointUtil.java#L192-L196)).

**Comment by JeethJJ** [comment]
Fixed with : https://github.com/wso2/carbon-identity-framework/pull/5325
