### ISSUE TITLE
Switching back to root org from a child org is ended up with black contentn with left nav bar due to wrong redirection

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18434]
**Describe the issue:**
1. Login to root org
2. Create an organization
3. Switch to organization
4. Switch back to root organization

Redirected URL is `https://localhost:9443/t/carbon.super/o/<org-id>/console/getting-started`

**Comment by NipuniBhagya** [comment]
Duplicate of https://github.com/wso2/product-is/issues/18431
