### ISSUE TITLE
[Custom Connector] Issue in updating authenticators from settings page.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18439]
**Describe the issue:**
In the current custom connector after updating an authenticator from the settings page the callback URL is changed in-to a different value. 

PS : Specifically to the previous default authenticator's Valid OAuth redirect URI

https://github.com/wso2/product-is/assets/41188245/90465651-4fd6-48a8-82d4-f78510334ffe

<img width="1491" alt="Screenshot 2023-12-05 at 12 33 35" src="https://github.com/wso2/product-is/assets/41188245/f5ec6f28-df86-4dca-a584-a5eca4da21b4">

**How to reproduce:**

1. Create a custom connector 
2. Add a new authenticator from the settings page (In my case I've used Facebook)
3. update the authenticator and  check the `Authorized redirect URI`

Special note: Another authenticator (Google Authenticator) has already been created here.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: Mac
 - Database:  MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
Release with https://wso2.org/jenkins/job/products/job/product-is/4979/
