### ISSUE TITLE
[Doc] The "Supported by Default" description should state that enabling it will show the claim in the user profile 

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1843]
In [1\] Under the "Supported by Default" description, it should state that enabling it will show the claim in the user profile as well. The product says it refer the image below.
![createclaim](https://user-images.githubusercontent.com/17248809/34204310-25d8be8e-e5a4-11e7-913a-09c703895410.png)

[1\] [https://docs.wso2.com/display/IS540/Adding+Claim+Mapping](https://docs.wso2.com/display/IS540/Adding+Claim+Mapping)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
