### ISSUE TITLE
[Doc] Better to specifically mention where to add an entry in the note under 'Deploying Twitter artifacts' section

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1844]
Note in 2nd step under 'Deploying Twitter artifacts' section [1] ask user to add an entry of given hostname and ip address but doesn't mentioned in where. Better to mentioned that to add the entry in /etc/hosts file.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Twitter+Authenticator#ConfiguringTwitterAuthenticator-ConfiguringtheTwitterAppConfiguringtheTwitterApp

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
