### ISSUE TITLE
Revisit the error message content

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18446]
**Describe the issue:**
![image](https://github.com/wso2/product-is/assets/5061791/9b2871c0-d6c9-4f80-93e4-832a8346bc37)

The overall section is connection and in the error message it has abbreviation IDP which doesn't make sense. 

**How to reproduce:**
Try to create a custom connector with the name of existing one.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
This error description is being taken from the BE. 

<img width="890" alt="Screenshot 2023-12-06 at 22 36 17" src="https://github.com/wso2/product-is/assets/67315176/004bc8fa-0c82-48ed-baf8-26be18a56c14">

**Comment by madurangasiriwardena** [comment]
Tested in the latest distribution.

While the original issue is no longer there, still the error message is wrong. I cannot see any error response sent from the BE as well. Hence this is a FE issue.

<img width="1711" alt="image" src="https://github.com/wso2/product-is/assets/1332991/ad532cea-fc02-4a69-a2b0-e06872ffdada">

**Comment by DilshanSenarath** [comment]
Verified in https://wso2.org/jenkins/job/products/job/product-is/4983/
