### ISSUE TITLE
Fix broken links in IS 7.0.0 Docs

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18447]
**Describe the issue:**

Identify and fix any broken links in IS 7.0.0 Docs.

**Comment by AnuradhaSK** [comment]
**PRs:**

- https://github.com/wso2/docs-is/pull/4225
- https://github.com/wso2/docs-is/pull/4224
- https://github.com/wso2/docs-is/pull/4225
- https://github.com/wso2/docs-is/pull/4223
- https://github.com/wso2/docs-is/pull/4216
- https://github.com/wso2/docs-is/pull/4186
- https://github.com/wso2/docs-is/pull/4010

**Comment by Rashmini** [comment]
PRs:

- https://github.com/wso2/docs-is/pull/4199
- https://github.com/wso2/docs-is/pull/4213
