### ISSUE TITLE
Revise the UX and options under provisioning

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18445]
**Describe the issue:**
Some of the configurations under application provisioning section are not applicable.
![image](https://github.com/wso2/product-is/assets/5061791/5b2e9c8d-0eea-4a56-acc0-9d378c50b73d)

**How to reproduce:**
Create a traditional web app and access the provisioning section.

**Expected behavior:**
Need to evaluate the usecases and enable only the required configurations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
Verified in new pack
