### ISSUE TITLE
Redirection issue in all the tabs in the Custom Connector.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18442]
**Describe the issue:**
After updating a configuration in the custom connector tabs, it consistently redirects to the wrong page.
This happens all over the connector.

https://github.com/wso2/product-is/assets/41188245/b7b24920-aa3c-4723-a9f2-7fe4e8f31bd1

**How to reproduce:**

1. navigate to the created custom connector.
2. Go to OutBound Provisioning
3. add a role and update

**Expected behavior:**
Should stay in the relevant tab.
 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
Released with https://wso2.org/jenkins/job/products/job/product-is/4979/
