### ISSUE TITLE
Feature GAP in IS-7 Alpha and Cloud product - Connectors

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18440]
**Is your suggestion a test requirement/change or improvement of the test framework? Please describe.**
In this task, an effort will be conducted to identify the gaps in IS 7 compared to the cloud product.

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by melanisilva** [comment]
### Identified Issues 

- [https://github.com/wso2/product-is/issues/18226](https://github.com/wso2/product-is/issues/18226)
- [https://github.com/wso2/product-is/issues/18269](https://github.com/wso2/product-is/issues/18269)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
