### ISSUE TITLE
User Self Registration, verification Email Resend Failed

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#18443]
### **Describe the issue:**
> $subject

https://github.com/wso2/product-is/assets/75057725/00e914c2-aeb0-4ccb-8657-19c5941bca3a

### **How to reproduce:**
1. Create an application.
2. Enable self registration and account verification (Console > Login & Registration > Self Registration)
3. Go to the login page of the application.
4. Click on `Register` option to proceed with self registration.
5. Add necessary details and click `Signup`
6. Go to the login page of the application again.
7. Try to login to the application using created user credentials.
8. Click on `Resend` option in the appeared text box.

### **Expected behavior:**
Email should be sent without any failures.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 7.0.0-rc1-SNAPSHOT] ([4964](https://wso2.org/jenkins/job/products/job/product-is/4964/))
 - OS: [e.g., Mac]
 - Database: [e.g.,H2]
 - Userstore: [e.g., JDBC]

**Comment by UdeshAthukorala** [comment]
Will be fixed with: https://github.com/wso2/identity-apps/pull/4985

**Comment by UdeshAthukorala** [comment]
Closed with https://github.com/wso2/identity-apps/pull/4991
