### ISSUE TITLE
[Doc] No 5.4.0 Doc found for Configuring SMSOTP

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1845]
Refer to doc [1]. No IS 5.4.0 Doc version found for Configuring SMSOTP [2]

[1]. https://docs.wso2.com/display/IS540/Configuring+SMSOTP
[2]. smsotp.png

![smsotp](https://user-images.githubusercontent.com/31848014/34204465-b448ce5c-e5a4-11e7-8eee-f66d404b8cf8.png)

**Comment by shavidissa** [comment]
Thank you, for reporting! I added the content to docs and tested it using the Nexmo SMS provider.

[1] https://docs.wso2.com/display/IS540/Configuring+SMSOTP
