### ISSUE TITLE
Case insensitive for username is not working

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18458]
**Describe the issue:**
Given toggle from the user store user configurations "Case insensitive" is not working as expected. 

<img width="788" alt="image" src="https://github.com/wso2/product-is/assets/39077751/6a6a7f30-88e7-488c-937e-04424117f360">

**How to reproduce:**
1. Login to console
2. Create user store LDAP (for this case use 5.11 IS pack embedded LDAP)
3. Navigate to created User store edit section and check the "Case insensitive username"  configuration
4. Update the configuration validate the scenarios

**Expected behavior:**
When enable case incentive, 

When case-insensitive, creating users with the same username in different cases is restricted, but login remains case-insensitive for convenience.

 When disable case incentive, 

When case-sensitive, creating users with the same username in different cases is allowed, but login is case-sensitive and distinct.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: postgres
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
At present, despite the toggle being disabled, the username searching remains case-insensitive. This is not a frontend issue. As per the discussion with Maduranga, when searching the username in the database, the search should consider the case sensitivity toggle value. Consequently, this appears to be a backend-related issue.

**Comment by madurangasiriwardena** [comment]
I believe the default value for this configuration should be true and the LDAP needs to be case sensitive to disable it.

CC @ShanChathusanda93
