### ISSUE TITLE
Empty label on the selected API resource when creating an application role

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-is#18463]
**Describe the issue:**

When the API resource is not present in the selected API resource, an empty label is displayed near the API resource name. Refer to the screenshot below.

![Screenshot 2023-12-06 at 15 19 45](https://github.com/wso2/product-is/assets/27700915/480f04c4-443a-4929-b29c-e728e19785d0)

**How to reproduce:**
1. Create a standard based application in the IS console.
2. Navigate to the **API Authorization** section of the created application and authorize `SCIM2 Bulk API`.
3. Navigate to the **Roles** section, select application role type and click on **Create Role**.
4. Select the  `SCIM2 Bulk API` from the **Select API Resource** dropdown on the **Create Application Role** wizard.

**Expected behavior:**
If the API resource type is not available for the API resource, the label should not be shown.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0 Beta

**Comment by JayaShakthi97** [comment]
- Fix: https://github.com/wso2/identity-apps/pull/5000

**Comment by JayaShakthi97** [comment]
Verified

![image](https://github.com/wso2/product-is/assets/37938529/d7153492-eb3c-427f-8edd-835b228c5b57)

![image](https://github.com/wso2/product-is/assets/37938529/5fb54c0d-9136-4500-a5e4-a03620e1e184)

![image](https://github.com/wso2/product-is/assets/37938529/919fb691-e0dc-47f1-88ae-2b27e2f6397f)
