### ISSUE TITLE
Lock specific account: Given image is different from actual ui

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1846]
In [1] when listing the claim account lock the image is given is different to the actual ui. Please update

![is_doc_7](https://user-images.githubusercontent.com/15624590/34204943-976d689a-e5a6-11e7-81c6-b6dc7d299653.png)

[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
