### ISSUE TITLE
`This is the description of the scope` will be added as the description to creating OIDC scopes through console UI

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18468]
**Describe the issue:**

https://github.com/wso2/product-is/assets/25483865/7770f888-002a-49b8-8efb-8b7e5d4913e6

- Go to Attributes -> OpenID Connect -> Scopes -> + New OIDC Scope
- Give values to the scope and Display Name. Leave the Description blank
- But the UI sends `This is the description of the scope` as the description when invoking the API

**Comment by dasuni-30** [comment]
### This is fixed in the latest pack

https://github.com/wso2/product-is/assets/27746285/4deed0f3-eead-4cc0-b29a-c93f2a8ae854
