### ISSUE TITLE
Access delegation documents are missing. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18462]
**Describe the issue:**
IS 7.0.0 documentations are missing the access delegation guide. This need to be add. 
https://is.docs.wso2.com/en/latest/guides/access-delegation/configure-kerberos-grant/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
