### ISSUE TITLE
Using PKCS12 keystores as default primary keystore and truststore

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#18466]
WSO2 uses JKS type keystores as the default keystores which uses SHA1 which is no longer considered as secure. Furthermore, JKS keystores are not FIPS compliant [1].

To use PKCS12 keystores, following configs can be used in the deployment.toml

```
[keystore.primary]
file_name = "wso2carbon.p12"
password = "wso2carbon"
type="PKCS12"

[truststore]
file_name="client-truststore.p12"
password="wso2carbon"
type="PKCS12"
```

[1] https://docs.oracle.com/en/middleware/fusion-middleware/weblogic-server/12.2.1.4/secmg/fips.html#GUID-8191241C-B9A7-4D41-82B6-BC92AC3BD425

**Describe the improvement**
Primary keystore and trusture will use PKCS12 type keystores

**Additional context**
To convert an existing JKS keystore to PKCS12, following command can be used
```
keytool -importkeystore -srckeystore wso2carbon.jks -destkeystore wso2carbon.p12 -srcstoretype JKS -deststoretype PKCS12 -deststorepass wso2carbon
```

**Comment by Thisara-Welmilla** [comment]
PRs:
- https://github.com/wso2/carbon-kernel/pull/3770
- https://github.com/wso2/carbon-multitenancy/pull/255
- https://github.com/wso2/carbon-kernel/pull/3771
- https://github.com/wso2/identity-apps/pull/5170
- https://github.com/wso2/product-is/pull/18849
- https://github.com/wso2/carbon-identity-framework/pull/5357
- https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/415

**Comment by hwupathum** [comment]
Reopening since default keystore is changed to JKS format with https://github.com/wso2/product-is/pull/19517
