### ISSUE TITLE
Host Authentication Endpoint on a Different Server

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#18473]
**Is your suggestion related to a missing or misleading document? Please describe.**
Authentication endpoint externally hosting[1] part is not available in the IS 7 docs. Also, there are two new context params introduced. So the new script and the context params should be taken from here [2].

[1] https://is.docs.wso2.com/en/latest/references/extend/host-authentication-endpoint-on-a-different-server/
[2] https://github.com/wso2/samples-is/pull/422/files

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
