### ISSUE TITLE
Account unlock: Email notification is not recieved for user in secondary user store in tenant domain

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1847]
**Env**
OS: Ubuntu 16.04
JDK: 1.8.0_144

**Steps**
1. Added a secondary user store to a tenant domain
2. Added a user to the secondary user store
3. Enabled account locking and email notification
4. Locked the account by wrong credentials

**Actual result**: The lock notification comes but when the account is unlocked again no email notification appears

**Expected result**: Both lock and unlock notifications should reach the user

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
