### ISSUE TITLE
Hazelcast K8s DNS based pod discovery has been removed

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#18470]
**Describe the issue:**
Hazelcast K8s DNS based pod discovery has been removed with https://github.com/wso2/carbon-kernel/pull/3290/files, it was supposed to be deprecated[1] and not removed entirely without any notice.

**Expected behavior:**
DNS based pod discovery mechanism should not be removed without any notice.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0]

[1]https://github.com/wso2/kubernetes-common/issues/22

**Comment by madurangasiriwardena** [comment]
We don't have any plans to re-introduce DNS based pod discovery back to the next product release. Hence closing the issue.
