### ISSUE TITLE
The M2M app created for self organization onboarding should not be shared/visible to the organizations

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18486]
**Describe the issue:**

Currently, when the self-service organization management is enabled, the auto generated M2M is getting shared with all the organizations. The organization users may not aware of this app. Hence we can either hide this app from the application get response (That could cause pagination issues) or not share the M2M app with orgs. Have a custom logic for the organization_switch_cc grant to not to check the app is shared with the org when requesting for switched token.

**Comment by thanujalk** [comment]
We need to unshare the M2M application once the user is invited.

**Comment by dewniMW** [comment]
Approach:

The logic to share B2B-Self-Service-Mgt-Application with all sub organizations will be removed.
When needed to obtain organization_switch_cc grant to invite user to sub organization, the B2B-Self-Service-Mgt-Application should be shared with the relevant sub organization and then should be unshared when the relevant operations are done (the doc should be updated accordingly with the API calls).
