### ISSUE TITLE
Lock specific account: Fresh user too has the checkbox

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1848]
In [1] following is stated but in the actual UI even for a fresh user the checkbox appears. Please verify and update. If for a fresh user the text box should appear please comment.

```
If it is the first time this particular account is being locked, a textbox will appear in front of the Account Locked field as seen below. To lock the account, type true in the textbox and click Update.
```
[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
