### ISSUE TITLE
Organization Switch grant should not be shown in the self service APP.

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18487]
**Describe the issue:**
The normal M2M app doesn't show the organization_switch grant, but the self-service app which is marked as M2M app template shows the organization_switch grant.

<img width="772" alt="Screenshot 2023-12-07 at 12 59 30" src="https://github.com/wso2/product-is/assets/35717390/af39dd83-eaa6-471d-abb9-a7de8693e836">

**How to reproduce:**

Enable the self service feature.
```
curl --location --request PATCH 'https://localhost:9443/api/server/v1/self-service/preferences' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data '{
    "operation": "UPDATE",
    "properties": [
        {
            "name": "Organization.SelfService.Enable",
            "value": "true"
        }
    ]
}'
```
**Expected behavior:**

Only client credentials grant should be displayed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0.0-beta2]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by JayaShakthi97** [comment]
Verified in wso2is-7.0.0-beta4-SNAPSHOT

<img width="1173" alt="image" src="https://github.com/wso2/product-is/assets/37938529/78fdad93-6acc-477b-aa21-7ec4bbab587e">
