### ISSUE TITLE
[GrantType] Koberose 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18485]
**Describe the issue:**
Provided kerberos client project should be update. 
1. [Document](https://is.docs.wso2.com/en/latest/guides/access-delegation/configure-kerberos-grant/),  has mention a private repo.  
<img width="526" alt="image" src="https://github.com/wso2/product-is/assets/39077751/c4fde195-505d-4583-9f59-e9328942a2ba">

2. Project is outdated and not support with latest .net frameworks. 

Need to check the possibility to provide this client as an extension.

**Comment by aaujayasena** [comment]
Related issues: 
https://github.com/wso2/product-is/issues/18462

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
