### ISSUE TITLE
Users are listed by their email instead of their username in role update

### ISSUE THREAD

**Issue by shashimalcse** [wso2/product-is#18484]
**Describe the issue:**
When trying to update assigned users of the role, users are listed by their email instead of their username as previously.
![Screenshot 2023-12-07 at 12 00 48](https://github.com/wso2/product-is/assets/43197743/fa2f199b-6985-4c76-8dec-e0aa06bfd767)

**How to reproduce:**

**Expected behavior:**
users should listed by their username.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
