### ISSUE TITLE
Error Logs during Server Startup with DB2 as Primary Database

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18499]
**Describe the issue:**
Encountering error logs during the startup of the server when using DB2 as the primary database

terminal logs

```
org.ops4j.pax.logging.pax-logging-api [log4j2] WARN : Error while converting string [Test] to type [class java.net.URL]. Using default value [null].
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : No URL provided for SecuredHttpAppender: url
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Could not create plugin of type class org.wso2.carbon.logging.appender.http.SecuredHttpAppender for element SecuredHttp
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Null object returned for SecuredHttp in Appenders.
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Unable to locate appender "AUDIT_LOGFILE" for logger config "AUDIT_LOG"
org.ops4j.pax.logging.pax-logging-api [log4j2] WARN : Error while converting string [Test] to type [class java.net.URL]. Using default value [null].
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : No URL provided for SecuredHttpAppender: url
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Could not create plugin of type class org.wso2.carbon.logging.appender.http.SecuredHttpAppender for element SecuredHttp
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Null object returned for SecuredHttp in Appenders.
org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Unable to locate appender "AUDIT_LOGFILE" for logger config "AUDIT_LOG"
```

**How to reproduce:**
configure  with DB2 as the primary database. - https://is.docs.wso2.com/en/latest/deploy/change-to-ibm-db2/#change-the-default-datasource
Start the server.

**Expected behavior:**
The server should start without any errors when configured with DB2 as the primary database.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-rc1-SNAPSHOT - Build 4967 (07-Dec-2023 00:33:24)
 - OS: Mac
 - Database: DB2
 - Userstore:JDBC

---

**Comment by ZiyamSanthosh** [comment]
I tried it with a new beta3 pack from https://wso2.org/jenkins/job/products/job/product-is/4968/
This is not reproducible in this pack. Only the below given error log is visible related to pax logging.
```
[2023-12-08 16:40:11,700] []  INFO {org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier} - Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
```

https://drive.google.com/file/d/10lrnytCf_2PjhXfct8cg-ZGiWaLcpIwx/view?usp=drive_link

@NilukaSripalim Please verify

**Comment by NilukaSripalim** [comment]
Tested and verified wso2is-7.0.0-beta4-SNAPSHOT, This is fixed and no error logs while server startup
