### ISSUE TITLE
Hazelcast configuration key change affecting cluster initilization after U2 298

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#18496]
**Describe the issue:**
With hazelcast changing the parameter keys to dash separated, now the previous camelCase configurations [2][3] will not be honored as it expected as dash-seperated [4]. This will result the com.hazelcast.internal.cluster.impl.DiscoveryJoiner t iterate through the combinations of 5701 to 5708 default ports through all instance ips in the environment and not just the instances bound by the security group.

[1] https://docs.hazelcast.org/docs/4.0/manual/html-single/#aws-element
[2] https://is.docs.wso2.com/en/5.11.0/setup/deployment-guide/#clustering-related-configurations
[3] 
```
[clustering.properties]
accessKey = "{access-key}"
secretKey = "{secret-key}"
securityGroup = "{security-group}"
region = "{region}"
tagKey = "{tag-key}"
tagValue = "{tag-value}"
```
[4]
```
[clustering.properties]
access-key = "{access-key}"
secret-key = "{secret-key}"
security-group-name = "{security-group}"
region = "{region}"
tag-key = "{tag-key}"
tag-value = "{tag-value}"
```

**How to reproduce:**
In AWS environment,
1. Update the product IS 5.11.0 to U2 298 or after,
2. Keep the cluster properties as previous [2]/[3],
3. Start the server,

**Expected behavior:**
With previious configurations [3] the cluster should initilize properly.

**Environment information :**
 - Product Version: IS 5.11.0
 - OS: Ubuntu
 - Jdk: 8 and 11
 - Cloud provider: AWS

**Comment by ShanChathusanda93** [comment]
Closing the issue since this is fixed in master.
