### ISSUE TITLE
Authorized redirect URL becomes undefined when the connection is created from sign in methods

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#18498]
**Describe the issue:**

Authorized redirect URL becomes undefined when the connection is created from sign in methods

https://github.com/wso2/product-is/assets/27746285/14ffffae-68ed-4b0a-a9c1-530c7b746f58

**How to reproduce:**

- Login to console
- Applications > Navigate to created App > Sign in methods
- Add Authentication
- Create new connection
- Check the authorized redirect URL

**Expected behavior:**
authorized redirect URL cannot be undefined

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ShanChathusanda93** [comment]
Same issue is there when we create a connection directly from the Connections menu. Please find the below clip.


https://github.com/wso2/product-is/assets/19262008/bb47be4e-80c1-4ea3-9629-1ceb10bb8c6f

**Comment by dasuni-30** [comment]
### Fixed in the new pack

<img width="859" alt="Screenshot 2023-12-09 at 19 52 31" src="https://github.com/wso2/product-is/assets/27746285/ca1fd4a6-f89b-4de4-8064-84334d2ca56f">
