### ISSUE TITLE
[Doc] Contradictory values given for website url in content and image when configuring twitter application

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1849]
2nd step under 'Deploying Twitter artifacts' section [1] ask user to configure website url with contradictory values. 

Content asks to configure as -> http://127.0.0.1
and
Image has the value of -> https://127.0.0.1
[1] 

Should specify one value here.

https://docs.wso2.com/display/ISCONNECTORS/Configuring+Twitter+Authenticator#ConfiguringTwitterAuthenticator-ConfiguringtheTwitterAppConfiguringtheTwitterApp

**Comment by ShirazAzad** [comment]
Fixed. Doc [1] is updated.
[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Twitter+Authenticator

**Comment by omindu** [comment]
@maneeshaheshan Have you tested the twitter connector with 5.4.0 ?

**Comment by maneeshaheshan** [comment]
Hi @omindu ,
I've tested embedded twitter federated authenticator with travelocity in Identity Server 5.4.0 Update3 and it works fine.
