### ISSUE TITLE
[IS 6.1.0][Docs] Application creation sample curl in the documentation is not working

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#18502]
**Is your suggestion related to a missing or misleading document? Please describe.**
Sample curl provided in the documentation for creating an application doesn't work and return errors. It appears that the request payload contains some unsupported data as well some placeholder strings.

**Describe the improvement**
The documentation needs to be updated so that someone can tryout the sample curl for testing purposes.

This should be fixed IS 6.1.0 and master

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
