### ISSUE TITLE
Lock specific account: Steps for the tenant is missing

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1850]
In [1] steps in getting the configuration done for a tenant is missing. Please add the information

[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
