### ISSUE TITLE
 `Organization Settings` missing in `Login and Registration` section of the console

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#18508]
Please note that this is available on a pack built on 03/12/2023. Hence this is a regression. Due to this email domain discovery feature can't be tried out.

Expected UI
<img width="705" alt="Screen Shot 2023-12-08 at 10 12 14 AM" src="https://github.com/wso2/product-is/assets/24982871/c0d4a56c-8c76-4703-9989-94ae5469ab43">

**Comment by JayaShakthi97** [comment]
Default values for legacy mode configs need to be updated. (In framework)
- Fix: https://github.com/wso2/carbon-identity-framework/pull/5285

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0.0-beta4-SNAPSHOT

<img width="1283" alt="image" src="https://github.com/wso2/product-is/assets/37938529/f113b60e-b07f-463e-ba25-e763f3e72096">
