### ISSUE TITLE
[doc] Pack charon-config.xml.j2 to the product

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#18506]
Describe the issue:
Since we are packing `charon-config.xml.j2` to the product, customers who has alternations done to the default `charon-config.xml` has to move their configurations to `deployment.toml`.

Related issues:
https://github.com/wso2/product-is/issues/16916

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
