### ISSUE TITLE
[Improvement] FAPI Conformance Suite Improvements

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#18501]
We added FAPI Conformance Suite via, https://github.com/wso2/product-is/issues/16630 but we need to track some improvements for ease of maintenance and support other JARM and PAR tests.

- [ ] Current SandBox certs have validity period of 1 year, we need to have self signed certs with long period or need to have way to rotate the certs every year.
- [ ] Need to support JARM test suite - JARM test suite is not supported currently due to a [limitation](https://github.com/wso2/product-is/issues/18062) Once we fixed the limitation we can enable the JARM suite
- [ ] Need to support PAR test suite - Similar to JARM, PAR also has a limitation.
- [ ] Integrate Google Chat with FAPI suite
- [ ] [Important] Add Read Me with Local setup and testing steps in FAPI Conformance tests folder

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
