### ISSUE TITLE
MyAccount Pull Path Missing - Partial URL for Self-Service Portal Access

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18500]
**Describe the issue:**
When navigating to the Application Page, the pull path is missing, resulting in a partial URL being provided for accessing the Self-Service Portal information.

**How to reproduce:**

**Expected behavior:**
The URL provided for accessing the Self-Service Portal information should be complete and functional.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: wso2is-7.0.0-rc1-SNAPSHOT - Build 4967 (07-Dec-2023 00:33:24)
OS: Mac
Database: DB2, H2
Userstore:JDBC

<img width="1674" alt="Screenshot 2023-12-07 at 20 37 25" src="https://github.com/wso2/product-is/assets/39120228/df6d9e22-abec-4fc6-bb51-4f595ac37fdc">

**Comment by DilshanSenarath** [comment]
This issue can't be reproduced in beta4-SNAPSHOT pack (Build from source)
<img width="1505" alt="image" src="https://github.com/wso2/product-is/assets/74205483/4acc0be2-f652-4e8e-b434-330b9e676704">
