### ISSUE TITLE
Inconsistency in Menu styles

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18512]
**Is your suggestion related to an experience ? Please describe.**
<img width="277" alt="Screenshot 2023-12-08 at 12 10 38" src="https://github.com/wso2/product-is/assets/67315176/2969e7fe-42b6-4b42-a859-135e429495ee">

<img width="238" alt="Screenshot 2023-12-08 at 12 10 58" src="https://github.com/wso2/product-is/assets/67315176/2286241e-2b01-42e8-a77f-ba91e5879644">

**Comment by Avarjana** [comment]
Hover on drop-downs with rounded corners leads to an overflow.

![Screenshot 2024-01-16 at 15 20 12](https://github.com/wso2/product-is/assets/27714968/5c120cf7-4691-4266-b326-f3df1e5f2cc3)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
