### ISSUE TITLE
User account locking by admin option is not available for users in organizations

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18518]
**Describe the issue:**

- Admin initiating user locking feature is not available for users in suborganizations in Console UI

Super tenant:
<img width="1708" alt="Screenshot 2023-12-08 at 11 49 40" src="https://github.com/wso2/product-is/assets/25483865/90a7867f-6e5e-4bef-b055-9ad4e5262bb6">

Organization under super tenant:
<img width="1707" alt="Screenshot 2023-12-08 at 11 50 51" src="https://github.com/wso2/product-is/assets/25483865/5ce312a2-e2cf-41f0-b96a-37ff2c2a062a">

**Comment by DilshanSenarath** [comment]
Released with https://wso2.org/jenkins/job/products/job/product-is/4979/
