### ISSUE TITLE
Style inconsistencies in the icons used for Connections.

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18510]
**Is your suggestion related to an experience ? Please describe.**

The inconsistencies in the icons used for connections give off an unprofessional look to the page. The icons must be re-designed.

<img width="700" alt="Screenshot 2023-12-08 at 11 34 56" src="https://github.com/wso2/product-is/assets/67315176/a9851250-c6a7-490b-bc12-a2e939712d97">

- [ ] Color needs to be consistent.
- [ ] All icons must be either filled or outlined icons.
- [ ] Size needs to be consistent and should adhere to our icon guidelines. 
<img width="550" alt="Screenshot 2023-12-08 at 11 43 08" src="https://github.com/wso2/product-is/assets/67315176/f589de0e-0162-4d29-9cca-e8ec7b724d6e">

[Figma](https://www.figma.com/file/9QxyluUvzXAMbTdixve9Dh/Assets?type=design&node-id=1714%3A17&mode=design&t=0JZuTh8kpU6CFtOc-1)

**Comment by Sergiy-b** [comment]
<img width="1176" alt="Screenshot 2023-12-20 at 09 59 49" src="https://github.com/wso2/product-is/assets/63072741/cd8ee7b7-c461-4965-ab0b-377bfe805734">
[Source](https://www.figma.com/file/9QxyluUvzXAMbTdixve9Dh/Assets?type=design&node-id=1703%3A702&mode=design&t=EK8wEUFtqg14GeAo-1)

**Comment by Sergiy-b** [comment]
<img width="1150" alt="Screenshot 2023-12-20 at 10 01 45" src="https://github.com/wso2/product-is/assets/63072741/21e96759-01ec-4062-b05d-73888f00e803">
[Source](https://www.figma.com/file/9QxyluUvzXAMbTdixve9Dh/Assets?type=design&node-id=1703%3A702&mode=design&t=EK8wEUFtqg14GeAo-1)
