### ISSUE TITLE
Inconsistency in empty placeholders through the Console App

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#18513]
**Is your suggestion related to an experience ? Please describe.**

There are inconsistencies in empty placeholders through the Console App. Refer following Screenshots.

Edit Role > Assign Users
![image](https://github.com/wso2/product-is/assets/37938529/c6c801d2-ca36-4e6f-944e-c6c2be2d3223)

Edit Group > Assign Users
![image](https://github.com/wso2/product-is/assets/37938529/b2b27d38-5d60-475c-9eab-f0a110a67942)

Edit Group > Assign Roles
![image](https://github.com/wso2/product-is/assets/37938529/22c7913b-398a-4f18-bce3-211bc0be4a52)

**Describe the improvement**

These UIs need to be consistent.

**Additional context**

N/A

**Comment by JayaShakthi97** [comment]
Edit user > Active Sessions
![image](https://github.com/wso2/product-is/assets/37938529/9ff18bb2-b488-4e45-a495-e8baf36c445b)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
