### ISSUE TITLE
When a new user is created from carbon console username is set to lastname value as well

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1851]
*Environment*
```
IS 5.4.0
Ubuntu 14
Java version "1.8.0_51"
Firefox 55
DB - MySQL
```
Creating a user from admin console sets the username in the last name field as well.

*Steps*

1. Login to management console and navigate to add users
2. Add a user by providing a username and pw
3. View the user from the console

Issue
The username is shown in the "Last Name" as well. Ideally, it should be only shown when the username claim is set to "Support by Default"

**Labels** IS 5.4.0 , Bug

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
