### ISSUE TITLE
Display DCR endpoint information in the tenant level

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18516]
**Is your suggestion related to an experience ? Please describe.**

The DCR endpoint information used to be displayed under the info tab of applications.

DCR is typically performed independently of individual application creation and is closely associated with OAuth 2.0 client registrations. Hence, this was removed,

We need to display the DCR endpoint in a suitable server-level configuration or settings section (Example - In an organization level info section) enhancing the clarity of the configuration and eliminating redundancy at the application level.

**Related issue**
https://github.com/wso2/product-is/issues/18225

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
