### ISSUE TITLE
Test IS 7.0.0 on ARM architecture and add it into the automatic testing infrastructure 

### ISSUE THREAD

**Issue by gnudeep** [wso2/product-is#18526]
**Describe the issue:**
ARM architecture is now ubiquitous in the public clouds. It is essential to test WSO2 IS 7.0.0 and add this new architecture to the automatic testing infrastructure.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
