### ISSUE TITLE
[Doc][Highest] Misisng information in "Configuring IWA on Linux" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1852]
When i referring to [1] for configure IWA in Linux,
    In step 02-> Under Testing the IWA authenticator 
        It's redirecting the common SSO configuration document.
But we have some addition configuration related to IWA in  the travelocity.properties file.
 We have to edit the 
            SAML2.IdPURL url related to the hostname you have put in the IS server
           **Default config in travelocity.properties file**
                     SAML2.IdPURL=https://localhost:9443/samlsso
         **Updated config of travelocity.properties file**
                 SAML2.IdPURL=https://<Your IS host name>:<Your IS server POrt>/samlsso
                 Ex: **SAML2.IdPURL=https://idp.wso2.test:9443/samlsso**

[1] https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
