### ISSUE TITLE
Test IS 7.0.0 on Azure virtual machines with Hazelcast Azure membership scheme 

### ISSUE THREAD

**Issue by gnudeep** [wso2/product-is#18527]
**Describe the issue:**

Azure public cloud is getting popular among the public. Hazelcast Azure VM membership scheme needs to be tested with IS 7.0.0.

https://github.com/pabasara-mahindapala/azure-membership-scheme

\

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
