### ISSUE TITLE
Authorizations are not listed under app role

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#18522]
**Describe the issue:**
 When an App role is created, I should be able to add authorizations under that app role. (The ones that are related to subscribed APIs by that application).

But with the latest state (beta 3 snapshot which is built on 8th of December), none of these authorisations are getting listed under the application role. 

Some times the authorizations are listed. But when you create it and later try to add more, the rest of the authorizations are not listed. @thanujalk also could reproduce this issue.

**How to reproduce:**
Create some API resources along with authorizations
Create an application and subscribe to API resources
try to create an application role through role view (not through application)
Authoriztions are not getting listed under the role to be selected.

**Comment by thanujalk** [comment]
This is tracked with https://github.com/wso2/product-is/issues/18525

**Comment by dasuni-30** [comment]
### Fixed in the new pack

<img width="1158" alt="Screenshot 2023-12-14 at 16 23 57" src="https://github.com/wso2/product-is/assets/27746285/15c1be2a-93e8-47a0-8254-e87fcc5fe6e7">
