### ISSUE TITLE
Connections existence seems to be checked by retrieving all the connections in "Custom Connector" type

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#18536]
**Describe the issue:**
When creating a connection in "Custom Connector" type, existence of the connection is checked by listing all the connections as it seems (cannot see any filter call with the connection name).
<img width="1711" alt="image" src="https://github.com/wso2/product-is/assets/1332991/f6de6716-3c35-46c1-a985-6a22d6970161">

**How to reproduce:**
Create a connection in "Custom Connector" type with an existing connection name.

**Comment by DilshanSenarath** [comment]
Released with https://wso2.org/jenkins/job/products/job/product-is/4979/
