### ISSUE TITLE
Custom Even Handlers Does not work In Product IS

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#18538]
https://github.com/wso2/carbon-identity-framework/commit/b8295c92378f3921f9a4dc9984ea347a92902bf7 This commit removed the workflow related event handler from identity-event.properties. This has removed the 35th event handler from the file and that made  the event handler from 34 to 36. 

Due to this https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-event/org.wso2.carbon.identity.event/src/main/java/org/wso2/carbon/identity/event/IdentityEventUtils.java#L59 module loading loop get exit since it gets a null for the i=35 

This is causing all the custom event handlers and event handlers after number 34 fail.

**Comment by madurangasiriwardena** [comment]
Seems to be fixed with https://github.com/wso2/carbon-identity-framework/commit/c43adfe4c7413745f4f47faf22e472b1613c6fb2 . Please validate.

**Comment by madurangasiriwardena** [comment]
While we have fixed this issue by updating the event handler ids to be continuous, this needs to be properly fixed to remove that requirement.
