### ISSUE TITLE
Update 'SAML2 Web SSOConfiguration' configuration screenshot with latest

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1854]
'SAML2 Web SSOConfiguration' screenshot provided in [1] seems outdated compared to the latest shown below.

![screenshot from 2017-12-20 17-33-03](https://user-images.githubusercontent.com/14962228/34206271-e0c6b546-e5ab-11e7-9835-a95f89bf0dff.png)

[1] https://docs.wso2.com/display/IS540/Log+in+to+the+Identity+Server+using+another+Identity+Server+-+SAML2

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
