### ISSUE TITLE
Improve Allow Authentication without the client secret configuration tooltip and documentation

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#18549]
Currently, in OIDC/OAuth2 configurations, the tooltip for the `Allow Authentication without the client secret` configuration has `This option will allow the client to authenticate without a client secret` as the tooltip. However, this tooltip does not emphasize the fact that the token call will fail if the client_secret was sent in the token request body as a parameter.

The documentation does not explain the purpose of the `Allow Authentication without the client secret` as well and only has the tooltip text in the description.

[1] - https://is.docs.wso2.com/en/latest/guides/login/oauth-app-config-advanced/#allow-authentication-without-the-client-secret

**Describe the improvement**
Improve the tooltip and documentation to emphasize the fact that the token call will fail if the client_secret was sent in the token request body as a parameter.

**Additional context**
Applicable for IS 5.10.0 and onwards which are using the management console

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
