### ISSUE TITLE
Once SMS OTP is selected as the authentication option, there is no way to go back for a different option.

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#18546]
**Describe the issue:**

When I have SMS OTP as passwordless authentication, and when I choose it as my login option, there is no way to go back to a different option if I decide to pick a different option . The page doesn't provide me a way to go back. Email OTP provides a way to go back

**How to reproduce:**

Setup SMS OTP as passwordless authentication. Select it while trying to login . The below page appears and there is no way to go back choose a different option.

![Screenshot 2023-12-11 at 19 26 00](https://github.com/wso2/product-is/assets/3666100/0f136d85-c5b6-4aad-9028-13a93bef780a)

Email OTP gives a way to go back. 
![Screenshot 2023-12-11 at 19 26 57](https://github.com/wso2/product-is/assets/3666100/56160c2a-6c0f-40fe-ac06-7bce88753b98)

**Expected behavior:**
We should have a way to go back as email otp.

**Comment by DilshanSenarath** [comment]
This issue arises from the absence of the `multiOptionURI` query parameter. In both the email-otp and sms-otp scenarios, the frontend sets the `multiOptionURI` parameter and calls the `/commonauth` endpoint. However, when redirecting the user to the login page from the backend, the `multiOptionURI` parameter is only set in the email-otp case and not in the sms-otp case. Consequently, the 'Choose Different Options' link is not displayed.

**Comment by ashanthamara** [comment]
This will be fixed with https://github.com/wso2-extensions/identity-auth-otp-commons/pull/5

**Comment by ashanthamara** [comment]
Closing the issue since the changes are deployed in the product-is. 
There is another issue related to `Choose a different option` and it will be tracked with https://github.com/wso2/product-is/issues/18655
