### ISSUE TITLE
Improve user creation UI of Console to behave based on user creation permissions and parent user inviting permission

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18553]
**Describe the issue:**

Sub organization's console view has a user creation option and invite parent user to the sub-organization option.
Navigation to this option is : User Management -> Users -> + Add user.  Once the `+ Add user` button is clicked the following wizard is prompt
<img width="843" alt="Screenshot 2023-12-13 at 09 42 33" src="https://github.com/wso2/product-is/assets/25483865/dea90aec-df42-4bf4-9e0a-6db09b41c54a">

- However, `+ Add user` button is visible only if user creation scope is available.
- There could be a scenario where someone wants to have only inviting parent organization user option but not be able to create users in the organization directly.

**Improvements:**

- [ ] Consider both user management API scopes and parent user inviting API scopes to show `+ Add user` on organization's console view
- [ ] Handle the options of wizard prompted on `+ Add user` button click based on the available scopes
- [ ] Improve the API scope collections of user management

**Comment by PasinduYeshan** [comment]
This issue is addressed from following PRs.
- https://github.com/wso2/carbon-identity-framework/pull/5329
- https://github.com/wso2/carbon-identity-framework/pull/5330
- https://github.com/wso2/identity-apps/pull/5081
