### ISSUE TITLE
Some Connections does not have APIAuth Tag

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18559]
Some connections like
- Email OTP
- Passkey
- Magiclink does not have this tag. Please verify in all the connectors.

<img width="1715" alt="image" src="https://github.com/wso2/product-is/assets/12690906/26d7954a-9513-4351-b0d8-5949ebeb323d">

**Comment by dasuni-30** [comment]
### Verified in the new pack

![Uploading Screenshot 2023-12-18 at 11.16.37.png…]()

**Comment by aaujayasena** [comment]
https://github.com/wso2/product-is/issues/18559#issuecomment-1859597011 Please add the verifed build number @dasuni-30
