### ISSUE TITLE
Unable to create a sub organization

### ISSUE THREAD

**Issue by sahandilshan** [wso2/product-is#18551]
**Describe the issue:**
An error occurred while creating a sub-organization

**How to reproduce:**
1. Login to the console
2. Navigate to the *Organization* tab and create a new sub-org

An exception will get thrown and sub-organization creation will get failed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0.0-beta3
 - Database: Oracle

**Comment by aaujayasena** [comment]
https://github.com/wso2/product-is/issues/18626

**Comment by sahandilshan** [comment]
Verified this on the latest is pack by connecting with an oracle database

https://github.com/wso2/product-is/assets/32576163/a31599b6-7686-4fb5-9219-68a75ce6cdb2
