### ISSUE TITLE
[Chaos] Authentication requests not served until the cluster sync message passed during a server restart

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1855]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
OS - Ubuntu-14.04-LTS
Browser Chrome 58.0.3029.96

**Steps to reproduce the issue**
1. Create Facebook and Google as IDP
2. Create SP and connect FB, Google and Resident IDP and IDPs
3. Configure Travelocity with the fidp query param corresponding with the resident IDP (ex: in default pack this is localhost)
4. Simulate the login with resident IDP using jmeter and send a load of (1 thread , 10 ramp up and 100 loop)
5. Restart the IS servers inbetween

**Observations**
Authentication requests not served until the Member left message passed to the other node 
It tool around 1 minute to pass the member left message to the other cluster node

```
TID: [-1] [] [2017-12-20 12:17:15,246]  INFO {org.wso2.carbon.core.clustering.hazelcast.HazelcastClusterMessageListener} -  Received ClusteringMessage: ClusterCacheInvalidationRequest{tenantId=-1234, tenantDomain='carbon.super', messageId=7cac01e4-8338-4377-af6c-bbc63ec7c6f1, cacheManager=IdentityApplicationManagementCacheManager, cache=$__local__$.AuthenticationContextCache, cacheKey=org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationContextCacheKey@74188f00} 



TID: [-1] [] [2017-12-20 12:18:25,978]  INFO {org.wso2.carbon.core.clustering.hazelcast.wka.WKABasedMembershipScheme} -  Member left [0ee2255f-5e64-4d22-8fd4-2f840f9e588b]: /192.168.48.167:4000 
TID: [-1] [] [2017-12-20 12:18:31,970]  INFO {org.wso2.carbon.core.clustering.hazelcast.wka.WKABasedMembershipScheme} -  Member joined [719281c3-a6f2-4e31-aa38-5774b3bec0ff]: /192.168.48.167:4000 
TID: [-1] [] [2017-12-20 12:18:38,123]  INFO {org.wso2.carbon.core.clustering.hazelcast.HazelcastClusterMessageListener} -  Received ClusteringMessage: ClusterCacheInvalidationRequest{tenantId=-1234, tenantDomain='carbon.super', messageId=2093126d-a14d-45a5-b358-8aaca3bd22f5, cacheManager=IdentityApplicationManagementCacheManager, cache=$__local__$.AuthenticationRequestCache, cacheKey=org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationRequestCacheKey@7b922622} 

```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
