### ISSUE TITLE
The domain 'carbon.super' is appended in URLs displayed in console UIs

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#18558]
**Describe the issue:**

The domain `carbon.super` is appended in some of the URLs displayed in console UIs. We have fixed this in the backend and removed t/carbon.super from the URLs with a config. But it seems the URLs displayed in the console are not honoring that config. Due to this there are multiple problems.

1. URLs are incisistant in IS. By default, IS will only have a single tenant. Therefore we don't need the domain in URLs. Since we have fixed this in backed URLs, UIs also need to be aligned with that.
2. The console URL and Myaccount URL also have the `t/carbon.super` appended.
3. Some of the Connections such as Google, Github, Facebook etc, we are setting the callback URLs by default as below with `t/carbon.super`, and users cannot change that value as well. But in documents, we do not mention `t/carbon.super` in the URLs. Hence if someone follows the docs and configures these connections, functionality breaks due to callback URL mismatch issues. Hence we need to fix this in those places and honor the config defined to remove the `carbon.super` from URLs.

![Screenshot 2023-12-13 at 13 59 10](https://github.com/wso2/product-is/assets/13478571/05fb7ec3-f28e-460f-9793-49200582b16a)

**How to reproduce:**

**Expected behavior:**
Console UI components also need to honor the below config to remove `t/carbon.super` from URLs.

```
[tenant_context]
require_super_tenant_in_urls = false
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/18640
