### ISSUE TITLE
Permission name is not centered in the label

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18555]
**Describe the issue:**

- Go to Console settings -> Roles -> select one role -> go to permissions.
- You will get the following view.

<img width="1210" alt="Screenshot 2023-12-13 at 11 22 21" src="https://github.com/wso2/product-is/assets/25483865/2e8993a0-1417-45bc-a6d6-6a2e94fbb086">

https://github.com/wso2/product-is/assets/25483865/94f38e75-78d7-4c88-b32a-a018931f6985

**Comment by brionmario** [comment]
@Achintha444 Will revert the changes done in Oxygen UI as a quick fix. Later we can properly integrate those changes by running a complete regression round.

**Comment by Achintha444** [comment]
> @Achintha444 Will revert the changes done in Oxygen UI as a quick fix. Later we can properly integrate those changes by running a complete regression round.

This issue is not related to the recent bump of the Oxygen to 1.8.2. In this specific UI, there were some hardcoded padding values, which makes the UI distorted. This will be fixed from the following PR

- https://github.com/wso2/identity-apps/pull/5045

**Comment by Achintha444** [comment]
### Developer tested in the beta-4-snapshot

<img width="1800" alt="Screenshot 2023-12-13 at 13 42 07" src="https://github.com/wso2/identity-apps/assets/46097917/a0080b1d-e557-44a2-a94f-dea82b9351c5">
