### ISSUE TITLE
IS-KM 5.10.0 - Missing InvokeTokenRevocationEventOnRenewal configs in identity.xml.j2

### ISSUE THREAD

**Issue by Manasha11** [wso2/product-is#18564]
The following configuration is not templated in IS-KM 5.10.0.

```
[oauth.access_token] 
invoke_token_revocation_event_on_renewal = <true/false>
```

Need to update following section of <ISKM_HOME>/repository/resources/conf/templates/repository/conf/identity/identity.xml.j2 file,

```
{% else %}
<TokenPersistenceProcessor>org.wso2.carbon.identity.oauth.tokenprocessor.PlainTextPersistenceProcessor</TokenPersistenceProcessor>
{% endif %}
```

with,

```
{% else %}
<TokenPersistenceProcessor>org.wso2.carbon.identity.oauth.tokenprocessor.PlainTextPersistenceProcessor</TokenPersistenceProcessor>
{% endif %}

<!-- To invoke token revocation events when renewing access token. -->
{% if oauth.access_token.invoke_token_revocation_event_on_renewal is defined %}
<InvokeTokenRevocationEventOnRenewal>{{oauth.access_token.invoke_token_revocation_event_on_renewal}}</InvokeTokenRevocationEventOnRenewal>
{% endif %}
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by HiranyaKavishani** [comment]
Public fix not applicable based on comment [1]

[1] https://github.com/wso2/carbon-identity-framework/pull/5542#issuecomment-2082100714
