### ISSUE TITLE
Lock specific account: Account status is shown as true for accounts where previous lock has occurred in secondary user store in tenant domain

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1856]
**Env:**
OS: Ubuntu 16.04
JDK: 1.8.0_144

**Pre-requisites**: Configure account lock for specific accounts according to [1] 

**Steps**
1. Create account lock for a user in secondary user store in tenant domain by providing invalid credentials
2. Unlock the account after the time perios
3. Even though account is unlocked the "Account locked" checkbox is ticked.

[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
