### ISSUE TITLE
'Identity Server Console" and organizations are too close in Developer console

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#18566]
**Describe the issue:**
IMO, the two texts are too close. For a first time user, it feels like something that we haven't given priority.

![Screenshot 2023-12-13 at 20 34 30](https://github.com/wso2/product-is/assets/3666100/c8720abd-7e24-447c-ad2c-494b65d23572)

**Comment by jeradrutnam** [comment]
Fix for this will be available in the next version bump.

**Comment by pavinduLakshan** [comment]
Switching the issue status back to "OPEN" since this fix needed to be added to the oxygen-ui side, along with removing hardocded min-width introduced with https://github.com/wso2/oxygen-ui/pull/199/files

**Comment by pavinduLakshan** [comment]
> Switching the issue status back to "OPEN" since this fix needed to be added to the oxygen-ui side, along with removing hardocded min-width introduced with [wso2/oxygen-ui#199 (files)](https://github.com/wso2/oxygen-ui/pull/199/files)

This will be done with https://github.com/wso2/oxygen-ui/pull/200
