### ISSUE TITLE
Update the title 'SMS / Email Providers'

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18569]
<img width="672" alt="image" src="https://github.com/wso2/product-is/assets/12690906/81c9bfa4-1252-4bbe-916d-3c543b0e44fb">

Even though the title says SMS / Email Providers this page has SMS provider details only.

**Comment by NipuniBhagya** [comment]
This is the updated view in the latest version.

<img width="1492" alt="image" src="https://github.com/wso2/product-is/assets/30111554/53f403b8-578c-459d-833c-d7bf8eadefe8">

So closing the issues as the title is valid for the current UI.
