### ISSUE TITLE
Give an option to shift into sub organization once we go into sub organization view.

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#18565]
**Is your suggestion related to an experience ? Please describe.**

The natural movement of a user / admin is to click on the sub organisation when he wants to shift into sub organization. But once the user clicks on the sub organization and go into the overview page of the sub organization , there is no option to shift into the sub organization. Hence the user has to come back to the organzation list page and shift by clicking the respective shift button. 

Edit : Rather I think we should shift into sub organization when we click on the organiztion. We can give a different button / settings button to go into overview page. When we see it in user perspective, why would someone need to go to overview page again and again ? So by default it should shift into the sub org. 

**Describe the improvement**

I would like to have the option to shift into sub organization inside the organization overview page. 

![Screenshot 2023-12-13 at 20 09 40](https://github.com/wso2/product-is/assets/3666100/dd9b84d2-623d-4800-be89-c4509c9c76a0)
ontext**

**Comment by dewniMW** [comment]
We have decided to improve the UI by giving the user to switch to that particular organization in the overview page of the sub organization.
