### ISSUE TITLE
UI improvement: Sign in with Apple doesn't work with localhost

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#18571]
**Describe the issue:**

Sign in with Apple feature doesn't work with `localhost` (or 127.0.0.1) and requires a real domain/ or domain name with etc/hosts mapping. We have intended to cover this through the documentation ([doc issue](https://github.com/wso2/product-is/issues/15536#issuecomment-1440486332)).

![Screenshot from 2023-12-14 09-28-56](https://github.com/wso2/product-is/assets/35653110/aad1603e-bb65-4765-b1cc-6872d6ce5304)

However when creating a Apple connection from UI, it shows Web domain/ Return URLs in the help guide and there we allow showing localhost URLs. This may raise confusion for a end user.

![Screenshot from 2023-12-14 10-39-32](https://github.com/wso2/product-is/assets/35653110/c31eca7e-d460-4831-abda-6d20deb0d0a0)

**Suggested fix:** When using localhost or 127.0.0.1, we can hide the above UI helper guide and display a warning indicating this cannot be used with localhost.

**How to reproduce:**
Try to create an Apple connection by login to the React console

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Discussed with @jeradrutnam and decided to disable the create button of Apple connection if the host domain is `localhost`.

**Comment by JayaShakthi97** [comment]
Verified in latest wso2is-7.0-1.0-beta5-SNAPSHOT.
