### ISSUE TITLE
Attribute sync method gets modified when updating JIT settings of a Apple connection

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#18572]
**Describe the issue:**
As per the Apple implementation, Sign in with Apple requires setting the `attributeSyncMethod` to `NONE` to correctly sync the user attributes. This is because Apple IDP is only sending the user attributes during the very first login and doesn't send any attributes thereafter. Hence if the `attributeSyncMethod` is not set to `NONE`, it overrides the previously provisioned user details to null.

Doc issue: https://github.com/wso2/product-is/issues/15536#issuecomment-1440486332

**How to reproduce:**
1. Create a Apple connection from console UI
2. Navigate to JIT privisoning section and update some provisioning settings.
3. If you inspect the network tab, can see the `attributeSyncMethod` is set to `NONE`
4. Login to a sample app with Apple ID. User gets provisioned correctly
5. Logout and login again. Already provisioned user details gets removed

**Expected behavior:**

Provisioned user details should be preserved in subsequent login attempts

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DilshanSenarath** [comment]
Verified in https://wso2.org/jenkins/job/products/job/product-is/4983/
