### ISSUE TITLE
FIDO doesn't work on unsecured domains except localhost

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#18573]
**Describe the issue:**

FIDO authentication/ key registration doesn't work on unsecured networks. This is not a bug in our implementation and is a improvement done from browser/ Webauthn APIs. When browsers are updated, FIDO fails to work on unsecured networks. 

This is reproducible in IS when we change the hostname/ internal_host of Identity server without adding the proper certificates.
After adding some logs, we could observe the following error that gets thrown from webauthn API.
```
DOMException: WebAuthn is not supported on sites with TLS certificate errors.
```
cc: @UdeshAthukorala can you add the error log?

This needs to be analyzed to find out if this validation can be disabled from browsers to tryout FIDO in local IS development environments. Also we need to add steps to make this work by securing the domains. I.e. with self sign certificates.

Better to document this as well.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by UdeshAthukorala** [comment]
Error LOG: `DOMException: WebAuthn is not supported on sites with TLS certificate errors.`

**Comment by ThaminduDilshan** [comment]
Now it seems webauthn doesn't work on sites with TLS certificate errors. This is introduced to webauthn as an improvement as stated in [1]. This is already reported in several community groups as well [2][3].

One option to resolve this issue is to ignore this by starting chrome with the flag `–disable-features=DisableWebAuthnWithBrokenCerts`. However this is not a recommended step and should only be used for local testing purposes.

Other and the most viable option is to get browsers/ OSes to trust the certificate of the wso2 identity server. We need to explore and see how this can be done. Some useful references:
- https://superuser.com/questions/1296596/how-can-i-get-chrome-accepting-self-signed-certificates
- https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate/18602774#18602774
- https://medium.com/@tbusser/creating-a-browser-trusted-self-signed-ssl-certificate-2709ce43fd15


[1] https://lists.w3.org/Archives/Public/public-webauthn/2022Nov/0135.html
[2] https://community.bitwarden.com/t/chromium-110-brave-chrome-edge-extension-webauthn-issue/48034/16
[3] https://community.brave.com/t/webauth-errors-with-1-48-158-which-was-working-in-1-47-186-and-earlier/467824/7

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
