### ISSUE TITLE
WS Fedaration logo (for passive sts flow) not shown in Standard-Based Application in Register New Application page

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#18575]
**Describe the issue:**
WS Fedaration logo (for passive sts flow) not shown in Standard-Based Application in Register New Application page which may mislead users into thinking WS Fedaration passive sts flow is not supported. 
![Screenshot 2023-12-14 at 12 12 55 PM](https://github.com/wso2/product-is/assets/62496951/059c42a5-7dc5-47cc-8763-cd85865fadb2)

However, after clicking on it, we can create passive sts applications and the WS Fedaration logo is displayed in the wizard.

**How to reproduce:**
Go to Register New Application page and observe that only the OIDC and SAML logos are present. 

**Expected behavior:**
The WS Fedaration logo should also be present.

**Comment by DonOmalVindula** [comment]
When creating the icon, better to look into resizing the WS federation icon which is visible in the wizard as well as it is smaller than the other icons

<img width="566" alt="Screenshot 2024-01-03 at 11 57 47" src="https://github.com/wso2/product-is/assets/42619922/92350504-2ab9-4391-984e-724a37050ef1">
