### ISSUE TITLE
In consistencies in the UI when admin user login to console with email as username

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#18582]
**Describe the issue:**
When Email Address as the Username is configured [1], and the super admin login to the console using the new credentials, the UI doesn't contain the admin email address in the home page and in the user avatar the username is not displayed.
Please refer to the screencast:

https://github.com/wso2/product-is/assets/13362482/b473f2eb-c466-4cac-a098-7fd9bb3b09c4

[1] https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-as-username/

**How to reproduce:**

1. Enable Email Address as the Username[1].
2. Login to console using the new admin credentials as mentioned in the doc[1].

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by thanujalk** [comment]
![Image](https://github.com/wso2/product-is/assets/1498339/973ee6d5-2fc4-475b-9f49-0a74fc192edf)
