### ISSUE TITLE
Give application level configuration support for the self registration feature.

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18585]
**Is your suggestion related to an experience ? Please describe.**
Give configuration support app wise, for the the self registration option so users can configure the options such as verification,  auto login etc. for different apps in a flexible way.

Currently, as we do not have this support, we have the option to enable Self registration for the Console. and when a user creates an account through the normal registration flow, without the necessary permissions, they cannot access the Console and the unauthorized page is displayed. This resuls in a bad user experience as this option is redundant for the Console.

<img width="520" alt="Screenshot 2023-12-14 at 15 24 28" src="https://github.com/wso2/product-is/assets/67315176/5d9b03af-3da3-401e-a487-ceb112b37b39">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
