### ISSUE TITLE
Lock specific account: given link for UserIdentityManagementAdminService doesn't work

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1858]
In [1] the link given for the UserIdentityManagementAdminService is not working. See below attached

![is_doc_9](https://user-images.githubusercontent.com/15624590/34207377-36c52794-e5b0-11e7-9d30-adec2c458627.png)

[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by madurangasiriwardena** [comment]
Cannot find the link specified in the doc. Reason for the error you are getting is since this is a soap service you need to append "?wsdl" to the end of the url.
