### ISSUE TITLE
Improve the validation message for the username in the registration form

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18588]
**Is your suggestion related to an experience ? Please describe.**

The message shown is not enough for the user to enter a valid username.

https://github.com/wso2/product-is/assets/67315176/606e0686-26fd-4fcb-a3a9-c6cf2518584d

**How to reproduce:**

Turn self registration on from Login & Registration > User Onboarding > Self registration
Create an application
Register a user in the application
Enter a username like "test" and submit

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
