### ISSUE TITLE
Lock specific account: provide an image of the permission tree for calling admin service section

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1859]
In [1] the following content is there under "Using the AdminService" section

```
An administrative user (with the permission level /permission/admin/configure/security/usermgt/users )
```

Please provide a graphical illustration of the above permission

[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
