### ISSUE TITLE
[DOC] [JIT] Attribute mapping between local and external connection

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#18594]
Issue: 
- https://github.com/wso2/product-is/issues/17408

By default, the subject identifier derived from the connector is utilized as the username for the user account created in the Identity Server during the Just-In-Time (JIT) provisioning flow. It is essential for the subject identifier obtained from the external connection to adhere to the organization's username validation regex.
If an administrator intends to use a different attribute value from the connector as the username for the user account, the attribute mapping must be done.

Please find the doc content from here: https://docs.google.com/document/d/1eWc5yTdPTI-ETlRjsgWUNfQW5maeYlj3u-Nppq7BnLM/edit?usp=sharing

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
