### ISSUE TITLE
Email is a mandatory when creating the consumer user

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#18606]
**Describe the issue:**
Email is marked as a mandatory failed when creating consumer users. For onprem consumer users, email should be an optional field. But we can create users from carbon console without email address
<img width="722" alt="Screenshot 2023-12-15 at 1 46 53 PM" src="https://github.com/wso2/product-is/assets/51480027/9b6d45c0-c14b-4b10-9363-888922cb6a18">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
AFAIK this is expected. @NipuniBhagya @brionmario WDYT?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
