### ISSUE TITLE
Unsupported sample application in IS 7 Docs

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#18605]
**Describe the issue:**
https://is.docs.wso2.com/en/next/get-started/try-samples/qsg-oidc-webapp-java-ee/ has an unsupported sample web application.

**How to reproduce:**
Download the sample application and login to that one.
![Screenshot 2023-12-15 at 1 41 18 PM](https://github.com/wso2/product-is/assets/51480027/a260eb0a-eadc-4ec7-8e6f-d04748d75070)

**Expected behavior:**
Login should not break.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
