### ISSUE TITLE
[Custom Connector] (SAML) Meta data file field is populated as a text field. This should be a place to upload the meta data file. 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18615]
**Describe the issue:**
In the general SAML Idp connector, this is an upload file field. Making this an input field provides the following issues should impose proper validations which are missing now. 
- Input field is not validated in UI for empty content
- When the meta data file is pasted in the field, the details cannot be saved. 

**How to reproduce:**
1. Create a custom connector
2. Navigate to Settings and click on "Add Authenticator"
3. Click on the SAML authenticator
3. Verify the "SAML Meta Data File" field behaviour for inputs.

**Expected behavior:**
Either the input should be an upload file type field or proper validations should be in place

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
This behavior is the same in the Identity Server 6.1 pack. Hence we need to implement the file picker for the meta data file from scratch.

https://github.com/wso2/product-is/assets/27746285/2d2bd3bb-9de9-4fc5-bf88-c3b7eb1651a3

**Comment by dasuni-30** [comment]
### Verified in the new pack

<img width="713" alt="Screenshot 2024-01-11 at 13 40 28" src="https://github.com/wso2/product-is/assets/27746285/1dfabfc5-8d48-4f55-84aa-797ec284be9e">
