### ISSUE TITLE
[DB2] Updating Copyright in Branding Not Reflected in Console and MyAccount Login Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18613]
**Describe the issue:**
Even though the "copyright" information has been updated under branding, the changes are not being reflected in both the console and the MyAccount login page. 
Note : Primary Database : DB2
And Host Name also changed 

**Note: This is working as expected in FireFox Browser**
**How to reproduce:**
1. Setup DB2 as Primary Database 
2. Please consider this while you setup Primary database in toml https://github.com/wso2/product-is/issues/18319#issuecomment-1843701560
3. Change Host Name  Ex: 
3. 1 Generating a Key Pair and Self-Signed Certificate:
```
keytool -genkey -alias wso2carbon -keyalg RSA -keysize 2048 -keystore wso2carbon.jks -ext SAN="dns:localhost,ip:127.0.0.1" -dname "CN=is70.qa.com, OU=Home,O=Home,L=SL,S=WS,C=LK" -storepass wso2carbon -keypass wso2carbon
```
3.2 Exporting the Certificate to a PEM File:
```
keytool -export -alias wso2carbon -keystore wso2carbon.jks -file newkeystore.pem
```
3.3 Importing a Certificate into a Truststore:
```
keytool -import -alias newkeystoresalias -file newkeystore.pem -keystore client-truststore.jks -storepass wso2carbon
```
3.4 Configure the hostname as follows in <IS_HOME>/repository/conf/deployment.toml.
```
[server]
hostname = "is70.qa.com"
```
3.5 If you are trying this on your local machine, open the etc/hosts/ file and add the following entry to map the new hostname. is.dev.wso2.com is an example in the sample entry below.
```
127.0.0.1       is70.qa.com
```
5. Go to the branding section in the console.
6. Update the "copyright" information.

**Expected behavior:**
The updated "copyright" information should be applied in both the console and the "myaccount" login page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 - OS: Mac
 - Database: DB2
 - Userstore: JDBC

---

<img width="990" alt="Screenshot 2023-12-15 at 13 57 58" src="https://github.com/wso2/product-is/assets/39120228/a3d6daac-0c61-495d-bc6e-5f9d0b63ad86">

Login page
<img width="530" alt="Screenshot 2023-12-15 at 13 58 09" src="https://github.com/wso2/product-is/assets/39120228/d949e4ee-2065-444f-be20-0c3f78dea6a1">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
