### ISSUE TITLE
[SAML] Enabling Artifact Binding doesn't provide the capability to configure Artifact resolve endpoint URL and other sub configurations.

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18619]
**Describe the issue:**
User is unable to configure the Artifact resolve endpoint URL, artifact request/response signing configurations when artifact binding is enabled. User has to save the enable check box for the sub configs to be available. In Management console, once the artifact binding is enabeld, the sub configs are allowed to edit

**How to reproduce:**
1. Create a SAML connection
2. Navigate to the settings of the connections and click on "Enable Artifact bindings"
3. Verify the configurations below

Screen recording: 

https://github.com/wso2/product-is/assets/106053688/4cf6d8d3-606e-42d3-9f7c-98c5f7cea8fb

**Expected behavior:**
The configurations are not allowed to edit. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
Issues addressed with this task :

- [ ] Disable/enable the sub fields based on the state of the checkbox enabling Artifact Binding.
- [ ] Remove duplicated hints - Improvement issue: https://github.com/wso2/product-is/issues/18705
- [ ] Fix incorrect payload issue on update of artifact request/response signing configuration values
