### ISSUE TITLE
The applied primary color is not applied for checkboxes in the console login page

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18610]
**Describe the issue:**

The applied primary color is not applied for checkboxes in the console login page

![checkbox](https://github.com/wso2/product-is/assets/40081059/d1c2abbb-1033-440c-8436-d83074dfc340)

**How to reproduce:**

1.Login to the console
2.Go to branding
3.Go to Design => color palette => set the primary color

**Expected behavior:**

The checkbox background color should align with primary color

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Regression from: https://github.com/wso2/identity-apps/blob/028e15f359362eddbdf9f635bbc7dfdb251dcc47/modules/theme/src/themes/default/modules/checkbox.overrides#L30

Need to handle this in the skeleton: https://github.com/wso2/identity-apps/blob/%40wso2is/validation%402.0.2/identity-apps-core/apps/authentication-portal/src/main/webapp/includes/theme-skeleton.jsp#L1276 
 
Also, add a `border radius` for the checkbox as well.
