### ISSUE TITLE
[Custom Connector] (SAML) Manual/File Based both the options are displayed even without proper selection for "Select Mode"

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18612]
**Describe the issue:**
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/b9ffea4c-d921-40f7-b40d-2b064f23020b">

There is no point of showing both the configurations. On selection of an option to "Select Mode" the respective configuration should be populated. 

**How to reproduce:**
1. Create a custom connector
2. Navigate to the Settings page
3. Click on SAML and verify the create page

**Expected behavior:**
1. Once the user selects an option in the "Select Mode", the details relevant to it should be displayed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/18615

**Comment by dasuni-30** [comment]
This behavior is the same in the Identity Server 6.1 pack. Hence we need to implement rendering the fields based on the manual or file-based configurations.

https://github.com/wso2/product-is/assets/27746285/2d2bd3bb-9de9-4fc5-bf88-c3b7eb1651a3

**Comment by dasuni-30** [comment]
### Verified in the new pack

https://github.com/wso2/product-is/assets/27746285/9e44764c-ec0c-438d-bae3-f930e35802fa
