### ISSUE TITLE
The UI doesnt fit properly with the Microsoft Edge browser

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18614]
**Describe the issue:**

The UI doesnt fit properly with the Microsoft Edge browser, it gives much of  a enlarged view even at 100 % view

Here if we go to text section in branding , the UI doesnt fit properly and also doesnt have a option to scroll down as well
![edge](https://github.com/wso2/product-is/assets/40081059/00e73259-d367-4576-9798-4c4a5ab77ec7)

[screen-capture.webm](https://github.com/wso2/product-is/assets/40081059/9d6777ae-a336-462c-a57f-01d0341d464a)

**How to reproduce:**

1.Login to the console
2.Go to branding=>text

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
@asekawa could you mention the dimensions you tested the UI in?
