### ISSUE TITLE
When using Amazon as the Federated Authenticator, space does not count as a character in client secret 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1861]
## Description: 
space is not counted as a character in the client secret in the beginning or in the end. 

## Steps to re-create
1. Configure SP - Travelocity
2. Configure Amazon as an external Idp
3. Select Amazon as the Federated Authenticator of Travelocity
> client id - amzn1.application-oa2-client.8247ac178da943c394a289a4f39b455f
> secret: 56fdb34ac9ca2d1e7fc903ae029b8922738aeee62d1fc682365e097097656c16
4. Update the client secret with a space character in the end. 
> 56fdb34ac9ca2d1e7fc903ae029b8922738aeee62d1fc682365e097097656c16 
5. Try logging in to Travelocity. 

**Expected:** It should result in an authentication failure. 
**Actual:** User can successfully log in.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
