### ISSUE TITLE
Unable to use API based authenticaion for SPA applications and Traditional Web applications

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18617]
**Describe the issue:**
When API based authenticaiton is executed from a single page application following error is returned.

```
{"code":"ABA-60007","message":"App native authentication is not enabled for the application.","description":"App native authentication is not enabled for this application with id cf64ae99-5528-40f0-949f-83d04c240671","traceId":"3d2c1a5d-9ec2-4ce5-86b6-8d40fecf6a1e"}

```
Respective configurations are not shown under the Advanced section as well
![image](https://github.com/wso2/product-is/assets/5061791/a1961963-90d1-4eaa-bacc-252a6b30e91c)

Cannot try the flow from traditional web applications as well.

**How to reproduce:**

1. Create a single-page app
2. Try API-based authentication from an app
3. Create a traditional web application and try the flow

**Expected behavior:**
API-based authentication should be possible for SPAs as well.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thumimku** [comment]
Hi Dev,

We have an ongoing discussion about whether to add ANA UI to SPA. As per last discussion, I am adding the UI config with this PR: https://github.com/wso2/identity-apps/pull/5092
If we decided to add the UI config to SPA template the fix can be found here, https://github.com/wso2/identity-apps/pull/5092/commits/b06791b73010891c3b9e97f0669c632a16cf36df
Hence removing my assignment.

CC: @janakamarasena @ayshsandu

**Comment by JayaShakthi97** [comment]
API-based authentication UI support for Traditional Web App is added through the following;
- https://github.com/wso2/identity-apps/pull/5145

Discussion is pending to decide on adding Application Native Authentication UIs for the SPA template.

**Comment by JayaShakthi97** [comment]
In a discussion had with @janakamarasena, @jeradrutnam, @ayshsandu, @malithie following decisions were made;
- ANA UIs should not be included in SPA.
- ANA UIs should be included in Traditional Web Apps. However, attestation configs should not be shown.

**Comment by jeradrutnam** [comment]
> In a discussion had with @janakamarasena, @jeradrutnam, @ayshsandu, @malithie following decisions were made;
> - ANA UIs should not be included in SPA.
> - ANA UIs should be included in Traditional Web Apps. However, attestation configs should not be shown.

Mobile and Standard-based applications as well.
