### ISSUE TITLE
Single logout is not working for OIDC sample apps with external LDAPs

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#18621]
**Describe the issue:**
SSO is working for OIDC apps. But SLO is not working.

**How to reproduce:**
1. Configure two webapps with external LDAP
2. SSO to the webapps
3. Try to SLO

**Expected behavior:**
SLO should work

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0,]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
@ayeshajay can you elaborate what you mean by SLO not working?

**Comment by ayeshajay** [comment]
I have tested that on using https://is.docs.wso2.com/en/latest/guides/login/cross-protocol-logout/#pickup-dispatch-saml, https://is.docs.wso2.com/en/latest/guides/login/cross-protocol-logout/#set-up-the-pickup-manager-sample applications  and https://is.docs.wso2.com/en/latest/guides/login/sso-for-oidc/#pickup-dispatch for this operation.

**Comment by asha15** [comment]
I tested SLO with playground2, and also with the Myaccount and console applications as well. SLO worked without any issue. However, SLO did not function as expected in the pickup-dispatch and pickup-manager applications. A separate issue has been created to address it[1]

[Screencast from 04-01-24 20:52:12.webm](https://github.com/wso2/product-is/assets/28682701/e4918774-abcc-41cc-b069-bd1ac52df079)
[Screencast from 04-01-24 17:35:21.webm](https://github.com/wso2/product-is/assets/28682701/8e8b1e76-76f5-41c1-bb22-6e2dc2e111e1)

[1] https://github.com/wso2/product-is/issues/18814

**Comment by asha15** [comment]
Since SLO is working with the latest IS pack we’re closing the issue.
