### ISSUE TITLE
Single logout is not working for Cross-Protocol applications

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#18624]
**Describe the issue:**
SSO is working for Cross-Protocol apps. But SLO is not working.

**How to reproduce:**
1. Configure two webapps(OIDC + SAML) with external LDAP
2. SSO to the webapps
3. Try to SLO

**Expected behavior:**
SLO should work

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [S 7.0.0]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Thisara-Welmilla** [comment]
Possibly related to https://github.com/wso2/product-is/issues/18621

**Comment by asha15** [comment]
I have tested cross-protocol logout using OIDC `pickup-manager` and `saml2-web-app-pickup-manager.com` sample applications. Single Logout (SLO) worked seamlessly without encountering any issues. However, the documentation[1] doesn't include instructions on enabling back-channel logout and adding the SLO URL for OIDC application. I've created a separate issue [2] to address this issue.

[Screencast from 07-01-24 12:57:18.webm](https://github.com/wso2/product-is/assets/28682701/2359a0fe-44db-4c94-a3b9-6340067357e5)

[Screencast from 08-01-24 23:09:58.webm](https://github.com/wso2/product-is/assets/28682701/69be5597-d6ba-4b20-b13d-60473514d904)


[1] https://is.docs.wso2.com/en/latest/guides/login/cross-protocol-logout/#pickup-dispatch-saml
[2] https://github.com/wso2/product-is/issues/18842

**Comment by asha15** [comment]
Since cross protocol logout worked with the latest IS pack, we're closing the issue.

**Comment by aaujayasena** [comment]
@asha15 did you verify this for all 3 binding? Back channel, front channel HTTP redirect, Front channel HTTP post

**Comment by asha15** [comment]
> @asha15 did you verify this for all 3 binding? Back channel, front channel HTTP redirect, Front channel HTTP post

I tested the back-channel logout.
