### ISSUE TITLE
Lock specific account: Provide details of how to achieve account lock and unlock through admin service for a tenant user, secondary user store user

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1862]
Please include the following in [1] 

1. Invoking the admin service and locking account of a tenant primary user
2. Invoking the admin service and locking account of a secondary user store user

[1] https://docs.wso2.com/display/IS540/Locking+a+Specific+User+Account

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
