### ISSUE TITLE
[OracleDB] Sub Organization switch not available on tenants

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18627]
**Describe the issue:**
[OracleDB] Sub Organization switch not available on tenants.

![Screenshot from 2023-12-15 14-53-55](https://github.com/wso2/product-is/assets/39077751/74215c02-7cdf-4fca-a9cd-fcfa08d907e0)

**How to reproduce:**
1. Login to management console
2. Create tenant
3. Login to console with tenanted path
4. Create sub oraganization
5. Switch to the sub organization

**Expected behavior:**
There should be option to switch to sub organization. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
@aaujayasena let's verify this in the latest pack

**Comment by sahandilshan** [comment]
https://github.com/wso2/product-is/assets/32576163/8efc5c47-0b5f-4121-8aae-38d7254a768b

Verified in the latest pack by connecting into an oracle database, the issue is no longer reproducible
