### ISSUE TITLE
Local role to service provider role mapping support in IS 7.0.0

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#18636]
**Is your suggestion related to an experience ? Please describe.**
In prior versions of IS, we have supported local role to service provider role mappings. We need to analyze whether we need to support  local role to service provider role mappings or use application roles introduced with the new role v2 implementation instead of service provider role mappings.

**Comment by shashimalcse** [comment]
Fix with : https://github.com/wso2/carbon-identity-framework/pull/5368 https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2320

**Comment by hwupathum** [comment]
Fixed the issue where the sub-organization admins cannot login to console using SSO https://github.com/wso2/carbon-identity-framework/pull/5396/commits/82a79fe3bbc02b6116ff7bd59b1485ce01598731 
Here, in OrganizationAuthenticator, roles claim is taken from the user attributes, and set it to the identity provider mapped user roles claim.
