### ISSUE TITLE
[BUG] No way to get a new verification Code in Email OTP

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1863]
Configure  Email OTP. If user need to regenerate or resend the verification code to there email address, there is should be away in UI.   But current Ui is not supporting the  functionality .
![emailverification](https://user-images.githubusercontent.com/13656890/34208308-039f575a-e5b4-11e7-947b-a3b95c373cae.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
