### ISSUE TITLE
Console doesn't properly render UI based on console application roles

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18632]
**Describe the issue:**
1. Create a user
2. Go to console settings -> Roles
3. Create a new role named "Application developer" and select permissions as follows
- Tenant permissions -> Application -> Edit
4. Assign the role to the created user in step 1
5. Admin log out from console and login to console by the user created in step1
6. Application management is not rendered to the user

received scopes in the token:
```
"console:applications internal_application_mgt_create internal_application_mgt_delete internal_application_mgt_update internal_application_mgt_view internal_claim_meta_view internal_cors_origins_view internal_idp_view internal_login openid profile"
```
Additional note: the returned scopes are not sufficient to show all tabs in applications.
Role related scopes, API authorization, application unsharing related scopes are missing here

https://github.com/wso2/product-is/assets/25483865/61a8a17a-e45c-42bd-a1a6-60084fbee2ef

Expected behavior:

- User should be able to do application management operations. 
- Other than that user should see the internal_login permission required sections only

Need to verify the same behavior with other permission collections

**Comment by DonOmalVindula** [comment]
Closing as all the roles are fixed
