### ISSUE TITLE
[SAML] Idp Connection Assertion Consumer Service (ACS) URL param is wrong for super tenants. 

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18640]
**Describe the issue:**
Common auth endpoint for super tenant should be without the t/carbon.super content. With this, IdP connection will not work. 
<img width="1512" alt="Screenshot 2023-12-16 at 18 48 51" src="https://github.com/wso2/product-is/assets/106053688/f0b4ef01-509f-4a32-9520-67d59fe505d8">

**How to reproduce:**
1. Create a SAML Connection
2. Verify the Assertion Consumer Service (ACS) URL field

**Expected behavior:**
Should be https://localhost:9443/commonauth

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Part of https://github.com/wso2/product-is/issues/18558
