### ISSUE TITLE
Required fields are not indicated with RED color * in SMS OTP configs (They are in greay color)

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18642]
**Describe the issue:**

- Go to the Email & SMS configuration section and then go to SMS provider configs.
- The mandatory input fields are marked in grey color *

<img width="1250" alt="Screenshot 2023-12-17 at 12 04 34" src="https://github.com/wso2/product-is/assets/25483865/a9fcb3c4-eadc-46f5-9a97-25d23182c28f">

they should be in red as same as other places
<img width="731" alt="Screenshot 2023-12-17 at 12 04 58" src="https://github.com/wso2/product-is/assets/25483865/6458331c-a9ee-4ed0-af7f-506cad8aa315">

<img width="1113" alt="Screenshot 2023-12-17 at 12 04 44" src="https://github.com/wso2/product-is/assets/25483865/f76e1ada-7b49-4946-af10-1ed34c71c54a">

**Comment by brionmario** [comment]
Related Issue: https://github.com/wso2/product-is/issues/17494
