### ISSUE TITLE
UserIdentityManagementAdminService guide on all the available operations and parameter descriptions

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1864]
Please provide a comprehensive documentation on UserIdentityManagementAdminService available operations and the parameters. This document should include the mandatory and optional details of the params as well

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
