### ISSUE TITLE
"Forget Username" Option Not Visible on Login Page with Identifier First as the 1st Factor in Authenticator

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18644]
**Describe the issue:**
Even though the "Forget Username" option is enabled via the console, when adding an identifier first as the first factor in the Authenticator in application (ex: console ), the "Forget Username" option is not visible in the application login page.

**How to reproduce:**
Enable the "Forget Username" option via the console.
Configure an identifier first as the first factor in the Authenticator.
Access the application login page.

**Expected behavior:**
If it's common for users to forget this information, enabling the option can enhance user satisfaction.

<img width="446" alt="Screenshot 2023-12-17 at 15 18 33" src="https://github.com/wso2/product-is/assets/39120228/4c7f696c-0ec0-4040-919a-a63d976b0b06">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
