### ISSUE TITLE
Unable to Edit "Pick User Identifier" and "Pick Attributes" Options in Classic Editor when Identifier First as 1st Factor in Application

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18643]
**Describe the issue:**
When adding an identifier First as the first factor in an Application with another 2nd factor, the "Classic Editor" option has "Pick user identifier from this step" and "Pick attributes from this step" options disabled by default.

However, when using the same configuration in the "Visual Editor," these options are editable.

**How to reproduce:**
Access the "Classic Editor." in a application 
Add an identifier as the 1st Factor for an Application with Google. facebook
Add  another 2nd factor , Username password.
Observe that the "Pick user identifier from this step" and "Pick attributes from this step" options are disabled.

**Expected behavior:**
The "Classic Editor" should allow the editing of "Pick user identifier from this step" and "Pick attributes from this step" options when configuring the identifier as the 1st Factor, consistent with the behavior in the "Visual Editor."
Or Both should have the same behavior

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 - OS: Mac
 - Database: DB2
 - Userstore: JDBC

---

[signinmethod.webm](https://github.com/wso2/product-is/assets/39120228/e558fb30-26fc-4d61-ae25-57ac8bda5e79)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
