### ISSUE TITLE
 Unable to Sign Up After Enabling "Self Registration" via Console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18641]
**Describe the issue:**
Enabling "Self Registration" via the console with provided options on the self-registration page results in an issue where users are unable to sign up via any authentication option. The page navigates to a "You are not authorized" page. 

To enhance user experience and prevent confusion, it's suggested that the "Registration" option on the console login page be hidden when self-registration is not allowed via the console.

**How to reproduce:**
Access the console.
Enable "Self Registration" with or without selecting any provided options.
Attempt to sign up using various authentication options (e.g., Google, email).
Observe that the page navigates to a "You are not authorized" page instead of completing the signup process.

**Expected behavior:**
When "Self Registration" is not allowed via the console, the "Registration" option on the console login page should be hidden, providing a clear indication to users that self-registration is not permitted.se

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 - OS: Mac
 - Database: DB2, H2
 - Userstore:JDBC

---

[selfRegister.webm](https://github.com/wso2/product-is/assets/39120228/b75d3d78-672a-4af4-919a-0f444a22d4be)

**Comment by thanujalk** [comment]
Disable self registration for Console.

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/18585
