### ISSUE TITLE
The localized custom text input via branding is not being reflected correctly due to a cookie issue.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18653]
**Describe the issue:**
When the localize custom text input via branding is updated it is not getting updated in the first attempt (Initial stage).

https://github.com/wso2/product-is/assets/41188245/14938883-f17c-46b1-a6ca-264aba00e712

**How to reproduce:**

1. Navigate to branding -> Styles & Texts 
2. Go to the Text Tab 
3. Update Copyright text in English 
4. Save and publish
5. Go to My Account you might not see the changes 
6. Change the language 
7. then change back to English, you'll be able to find the updated changes now.

### Analysis

Initially, when we don't have the ui_lang cookie the changes are not getting applied. but once we change the language and retrieve the cookie the previous changes will be applied.

https://github.com/wso2/product-is/assets/41188245/ce132726-98ae-4ecf-ad85-f05d87d044c3

<img width="1498" alt="Screenshot 2023-12-18 at 10 58 08" src="https://github.com/wso2/product-is/assets/41188245/60d576e2-201c-42f2-adab-0281d930ca0b">

<img width="1498" alt="Screenshot 2023-12-18 at 10 58 52" src="https://github.com/wso2/product-is/assets/41188245/558d4fe3-9f14-4d30-af00-8dcee8dedf5e">

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 Beta4
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
As explained in the description, this happens when the `ui_lang` cookie is not there. The language read is faulty (Log the resolved language in localize.jsp and see).

**Comment by savindi7** [comment]
Unable to reproduce issue


https://github.com/wso2/product-is/assets/67315176/5f7a6ebb-ae82-44a7-8aab-6edc4fd794a8
