### ISSUE TITLE
Lack of Clarity in UI Regarding SMS Provider Configuration

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18650]
**Describe the issue:**
The current UI design creates confusion as it provides separate sections for configuring SMS providers under "Emails & SMS" and an additional section for SMS OTP connections. However, there is a missing explanation or link between these sections, leaving users unaware that configured SMS provider options under "Emails & SMS" impact the SMS OTP Connection page. This lack of clarity could lead to misunderstandings and difficulties in managing SMS-related configurations.

**How to reproduce:**
Navigate to "Emails & SMS" section.
Configure SMS providers.
Visit the SMS OTP Connection page.
Observe the lack of information regarding the impact of configured SMS providers.

**Expected behavior:**
Provide clear information or a visual cue in the UI to indicate the relationship between the configured SMS providers under "Emails & SMS" and their impact on the SMS OTP Connection page. This can enhance user understanding and streamline the configuration process.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 - OS: Mac
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---
Provider is configured
<img width="1704" alt="Screenshot 2023-12-18 at 09 16 35" src="https://github.com/wso2/product-is/assets/39120228/2c75a5ab-40da-43e8-a558-4dff92d88800">

SMS OTP Connection Page
<img width="1447" alt="Screenshot 2023-12-18 at 09 18 49" src="https://github.com/wso2/product-is/assets/39120228/d8361910-4ee5-4139-815e-946579e32bb6">

**Comment by NipuniBhagya** [comment]
Related issue https://github.com/wso2/product-is/issues/18642

**Comment by NipuniBhagya** [comment]
@JKAUSHALYA can we close this issue?

**Comment by NipuniBhagya** [comment]
Assigning @pavinduLakshan as he's looking into a similar fix.

**Comment by pavinduLakshan** [comment]
Proposed design:

![image](https://github.com/wso2/product-is/assets/41533942/89a2900a-a981-41cd-9890-c189688289b3)

**Comment by dasuni-30** [comment]
### Verified in the latest pack

<img width="1161" alt="Screenshot 2024-02-13 at 12 39 10" src="https://github.com/wso2/product-is/assets/27746285/4a5fd8dc-a4fa-445e-81ef-ffc433c53f35">
