### ISSUE TITLE
[Custom Connector] Revisit the creation page of connectors in the custom connector

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18652]
**Describe the issue:**
ACS URL field is displayed in the creation page of SAML Connection in the custom connector. 

Other such issues are:
https://github.com/wso2/product-is/issues/18623
https://github.com/wso2/product-is/issues/18625
https://github.com/wso2/product-is/issues/18612
https://github.com/wso2/product-is/issues/18609

Other such validation 
**How to reproduce:**
1. Create a custom connector
2. Navigate to Settings page and click on "Add Authenticator"
3. Click on SAML and verify the fields displayed

<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/106053688/439019e0-94aa-44f4-8fc3-5d903acb216c">

**Expected behavior:**
The page should have the validations similar to the general connection creation

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
ACS URL can be given as input when creating a SAML federated authenticator in the custom connector. But it is displayed as a copy-read-only field after creation. Discussed about making the ACS URL editable after creation in the SAML federated authenticator. cc: @brionmario

**Comment by dasuni-30** [comment]
Closing the issue since the sub issues are closed and ACS URL is editable after creation

<img width="620" alt="Screenshot 2024-01-16 at 10 24 52" src="https://github.com/wso2/product-is/assets/27746285/548358a1-9ba8-4c6d-b7c0-f54d72000a47">
