### ISSUE TITLE
Account lock: Configuring WSO2 IS for automatic account unlock section has some ambiguities 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1866]
In [1] under "Configuring WSO2 IS for automatic account unlock" there is a setting under discussion. But when account locking is concerned locking can happen to below two reasons

1. User attempts failing
2. Admin locking an account

So with this configuration in place will all locked accounts be unlocked or is it only the above 1st category? Furthermore please provide details on the configuration when it's 0. Since this is a global configuration, all possible cases where this will be affected has to be documented.

[1] https://docs.wso2.com/display/IS540/Account+Locking+by+Failed+Login+Attempts

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
