### ISSUE TITLE
Unnecessary html comments in the email templates 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18666]
**Describe the issue:**
There are unnecessary html comments in the email templates.
These might end up marking these emails as spam as well.

![image](https://github.com/wso2/product-is/assets/5061791/7c9214f8-0531-4dbe-8868-07af5879ba37)

>                 

**How to reproduce:**
Open email templates from console

**Expected behavior:**
Remove unnecessary HTML comments.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-event-handler-notification/pull/214/files
