### ISSUE TITLE
Error when trying to assign users to a role from a secondary userstore

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#18665]
**Describe the issue:**
Getting "Something went wrong" error when trying to assign users from a secondary userstore.

<img width="1724" alt="Screenshot 2023-12-18 at 3 15 35 PM" src="https://github.com/wso2/product-is/assets/5061791/0a3482a4-b41c-4f35-afc6-631cfcdacaf5">

**How to reproduce:**

1. Setup a secondary user store (JDBC/PostgreSQL) in this specific case
2. Add few users to the new user store
3. Create a new application role
4. Access the users tab from the role setting view
5. Select the secondary user store 

**Expected behavior:**
Should be able to select users from the correct userstore.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
The user store domain name is sent here as a base64 encoded value which causes this issue
