### ISSUE TITLE
Remove unwanted configurations under user claim update settings

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#18668]
**Describe the issue:**
We need to remove the following configurations under user claim update settings.

- Send OTP in e-mail
- Include uppercase characters in OTP
- Include lowercase characters in OTP
- Include numbers in OTP
- OTP length
- Enable user mobile number verification on update
- Mobile number verification on update SMS OTP expiry time
- Enable mobile number verification by privileged users

**Comment by PasinduYeshan** [comment]
@NipuniBhagya Was there any specific reason to hide these configurations in UI?
