### ISSUE TITLE
Document the missing adaptive auth functions

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18674]
**Is your suggestion related to a missing or misleading document? Please describe.**

- Most of the common adaptive auth functions in https://github.com/wso2-extensions/identity-conditional-auth-functions/tree/master are missing in the documentation  https://is.docs.wso2.com/en/next/references/conditional-auth/api-reference/

Need to document the missing adaptive auth functions

Related sub issues:
- [x] https://github.com/wso2/product-is/issues/18664

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
