### ISSUE TITLE
Inconsistent `Sign in with` text on login page

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18685]
**Describe the issue:**

- Configure an application with the following second factors.
- Try the login flow, this login page will be shown

<img width="504" alt="Screenshot 2023-12-19 at 13 37 13" src="https://github.com/wso2/product-is/assets/25483865/44d2bec6-052a-4a4f-a00f-1e201140d06e">

`Sign In With` -> used in Passkey option
`Sign in with` -> used in other options

**Comment by brionmario** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/5144
