### ISSUE TITLE
When the user navigate to "back" after switching to a suborganization , the console doesnt update accordingly

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18681]
**Describe the issue:**

When the user navigates to "back" after switching to a sub-organization , the console doesnt update accordingly.
the URL s get updated accordingly but Console UI doesn't update properly

https://github.com/wso2/product-is/assets/40081059/ad4bc990-7711-4594-a3af-acfc9ae1cbcc

**How to reproduce:**

1.Login to the console
2.Create a suborganizatiom
3.Swicth into the suborg
4.Click on the back button from the browser

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 7.0.0 beta4]
 - OS: [ Mac]
 - Database: [H2]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
Getting the access denied page on back navigation. Looking into this.


https://github.com/wso2/product-is/assets/67315176/54d26313-d195-4f76-83c5-24b56ce43b88
