### ISSUE TITLE
Displayed MyAccount path of a suborganization should be updated

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18682]
**Describe the issue:**

Displayed MyAccount path of a suborganization should be updated
<img width="1512" alt="Screenshot 2023-12-19 at 12 16 00" src="https://github.com/wso2/product-is/assets/40081059/7e90241f-9a7d-4969-944e-0de6d8de8984">

**How to reproduce:**

1.Login to the console
2.Create a suburbanization
3.Switch into a sub organization
4.Go to applications section and check the my account URL path displayed

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
This feature should be supported along with the completion of Sub Org user login support for My Account & Console.

 Issue: https://github.com/wso2/product-is/issues/18554

**Comment by brionmario** [comment]
Fixed with PR: https://github.com/wso2/identity-apps/pull/5141
