### ISSUE TITLE
Getting an error while creating an application role from the Application -> Roles tab.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18687]
**Describe the issue:**
When trying to add an application role from the roles tab, Got both a success and an error message.
(It might be a Browser-specific dual submission issue.)

### Special Note : Browser -> Firefox

<img width="1132" alt="Screenshot 2023-12-19 at 14 28 46" src="https://github.com/wso2/product-is/assets/41188245/de65bb3f-5934-4abc-bf07-7a46e83edba9">

<img width="1420" alt="Screenshot 2023-12-19 at 14 42 06" src="https://github.com/wso2/product-is/assets/41188245/8c20f79c-1a3e-4db0-b648-8139cf8a4bc6">

https://github.com/wso2/product-is/assets/41188245/b6d28c6d-028e-4964-b604-ff4d74d2d24f

**How to reproduce:**

1. Go to a selected application
2. Navigate to the Roles tab.
3. Click on Create Role
4. Provide the specific details and create the role 
5. analyze the POST requests after clicking the submit button. 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS:  Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by melanisilva** [comment]
Plus is it expected to show an `SQLIntegrityConstraintViolationException` error log for this type of a scenario?
<img width="1512" alt="Screenshot 2023-12-20 at 15 04 30" src="https://github.com/wso2/product-is/assets/41188245/4a8b50ca-d295-4edf-9f67-dda7cbf3ffc8">

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR.
- https://github.com/wso2/identity-apps/pull/5127#issue-2052359341
