### ISSUE TITLE
Saver page is only available at the super tenant. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18692]
**Describe the issue:**

Tenant path
<img width="1147" alt="Screenshot 2023-12-17 at 19 48 34" src="https://github.com/wso2/product-is/assets/39077751/a1db4c17-9566-4db4-9e2b-52bad516bd0b">

Super Tenant 

<img width="1058" alt="Screenshot 2023-12-17 at 19 49 02" src="https://github.com/wso2/product-is/assets/39077751/1685267a-511a-4ccf-82c6-212eff871cde">

**How to reproduce:**
1. Login to console with tenant
2. Login to super tenant
3. Check the server page availability

**Expected behavior:**
@NipuniBhagya is this should be available on both or is this expected? 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Hi @aaujayasena, this is the expected behavior. Server settings should only be available for the super tenant. Hence closing the issue.
