### ISSUE TITLE
The option to edit admin details should be removed in the Guardio-Admin-App

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18698]
**Describe the issue:**

The option to edit admin details should be removed in the Guardio-Admin-App

<img width="1490" alt="Screenshot 2023-12-20 at 09 44 18" src="https://github.com/wso2/product-is/assets/40081059/87a0beee-c94b-4926-8a4a-01c6e036bc76">

https://github.com/wso2/product-is/assets/40081059/9363c12d-d29f-4865-ab8a-f5fc53b29124

**How to reproduce:**

1.Follow this document to up a Guardio-Admin-App and to sign in a user
https://github.com/wso2/samples-is/tree/master/b2b-sample

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
