### ISSUE TITLE
Conditional authentication,  Prompt() for user information is not working

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18693]
**Describe the issue:**
Conditional authentication,  Prompt() for user information is not working.
Document: https://is.docs.wso2.com/en/next/references/conditional-auth/api-reference/#prompt-for-user-input

**How to reproduce:**
1. Login to console
2. Create application
3. Deploy application
4. Configure conditional Authetication

```
var onLoginRequest = function(context) {
  executeStep(1, {
      onSuccess: function (context) {
          var username = context.steps[1].subject.username;
          prompt("genericForm", {"username":username, "inputs":[{"id":"fname","label":"First Name"},{"id":"lname","label":"Last Name"}]}, {
            onSuccess : function(context) {
                var fname = context.request.params.fname[0];
                var lname = context.request.params.lname[0];
                Log.info(fname);
                Log.info(lname);
            }
          });
      }
  });
}

```
6. Login to application

**Expected behavior:**
Input filed for Last name and first name should be prompt. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
This is working as expected. 
<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/12690906/3bf24db7-f652-462d-b745-ef9a042f3e51">
Closing this as this is not reproduced in the Beta5 snapshot.
