### ISSUE TITLE
Incorrect Redirect URI are given when creating connections in suborganizations

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18691]
**Describe the issue:**

Incorrect Redirect URI are given when creating connections in suborganizations

Google :https://localhost:9443/t/carbon.super/o/commonauth
instead it should be in https://localhost:9443/o/sub-orgid/commonauth

<img width="1065" alt="Screenshot 2023-12-19 at 17 34 29" src="https://github.com/wso2/product-is/assets/40081059/64851874-3bf1-43f9-bba8-ab80acad3031">

These issue is reproducing in Facebook , Github, Microsoft and Apple connections as well

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0 beta 4 SNAPSHOT]
 - OS: [Mac]
 - Database: [ H2]
 

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Related to https://github.com/wso2/product-is/issues/18558
