### ISSUE TITLE
Error when creating a FAPI Compliant application

### ISSUE THREAD

**Issue by himeshsiriwardana** [wso2/product-is#18690]
**Describe the issue:**
When creating a FAPI application from the console, the following error pops up.

<img width="674" alt="image" src="https://github.com/wso2/product-is/assets/31583807/6c0473b8-2551-4778-a00b-b1288abac3db">

**How to reproduce:**
1. Navigate to **Console** -> **Applications**.
2. Click **New Application** and choose to register a **Standard-based application**.
3. Select **OAuth2.0 OpenID Connect** as the protocol.
4. Provide a name and select the **FAPI Compliant Application** checkbox.
5. Click **Register**.

**Comment by aaujayasena** [comment]
https://github.com/anjuchamantha/product-is/actions/runs/7253495848
