### ISSUE TITLE
Alignment Issue with Lengthy Connection Display Names

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18696]
**Describe the issue:**
When a connection display name is lengthy, the alignment of the name is not displayed correctly, 

**How to reproduce:**

<img width="570" alt="Screenshot 2023-12-19 at 21 25 44" src="https://github.com/wso2/product-is/assets/39120228/a150ad53-bc33-4027-b3d3-2d8698a0413c">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
