### ISSUE TITLE
Add hints for input fields in the Artifact Binding section of SAML Connections

### ISSUE THREAD

**Issue by savindi7** [wso2/product-is#18705]
**Describe the issue:**
The hints duplicated with the label of input fields are removed. the following screenshots show the hints that were there previously.

<img width="320" alt="Screenshot 2023-12-20 at 14 37 55" src="https://github.com/wso2/product-is/assets/67315176/6a072314-7611-48be-82f1-7adb6159c990">

We need to add hints to these fields that support users to enter valid inputs.

SAML connection > Settings tab > Artifact Binding section

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
