### ISSUE TITLE
Redirecting to an empty page when clicked on local attribiutes link , when trying to create bulk users

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18706]
**Describe the issue:**

Redirecting to an empty page when clicked on local attribiutes link , when trying to create bulk users

<img width="936" alt="Screenshot 2023-12-20 at 14 50 58" src="https://github.com/wso2/product-is/assets/40081059/545cb648-7766-4c6a-bbb3-0ed5a7efeb86">

https://github.com/wso2/product-is/assets/40081059/2d38ab9c-8c2d-4397-961c-c1a79c07a38a

**How to reproduce:**

1.Login to the console
2.Create a sub org
3.Go to users
4.Select multiple users

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
This issue if fixed from following PR.
- https://github.com/wso2/identity-apps/pull/5121
