### ISSUE TITLE
IDP role to local role mapping support in IS 7.0.0

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#18714]
**Describe the issue:**
With the new authorization runtime introduced with the IS 7.0.0, roles of the federated user is resolved using IDP groups which was not available in previous versions of IS. In previous versions, federated user roles were resolved based on the IDP role to local role mappings. We need to come up with an approach to handle the IDP roles to local role mapping behaviour with new authorization runtime.

**Comment by hwupathum** [comment]
Fixed the issue where the sub-organization admins cannot login to console using SSO https://github.com/wso2/carbon-identity-framework/pull/5396/commits/82a79fe3bbc02b6116ff7bd59b1485ce01598731 
Here, in OrganizationAuthenticator, roles claim is taken from the user attributes, and set it to the identity provider mapped user roles claim.
