### ISSUE TITLE
Update Terminology in "Add Outbound Provisioner" Wizard from "Identity Provider" to "Connection"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18717]
**Describe the issue:**
The "Add Outbound Provisioner" wizard in the application still uses the term "Identity Provider" despite the shift in terminology to "Connections.
<img width="779" alt="Screenshot 2023-12-21 at 11 57 55" src="https://github.com/wso2/product-is/assets/39120228/3933cbb8-b1ca-4164-8677-5b0c91bbbb24">

**How to reproduce:**
1. Create Application OIDC
2. Click on Provisioning Tab > Outbound Provisioning
3. Navigate to the "Add Outbound Provisioner" wizard.
4. Observe that the term "Identity Provider" is used in the wizard.

**Expected behavior:**
The terminology in the "Add Outbound Provisioner" wizard should be updated to use "Connection" instead of "Identity Provider" to align with the current terminology being used in the application.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
