### ISSUE TITLE
Consent request screen is not populating during authentication flow.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#18724]
**Describe the issue:**
In OAuth authorise Code scenario, after successful authentication there will be a consent approval page. But in the latest pack its gone. 

https://github.com/wso2/product-is/assets/25488962/0c8eeff1-3ef8-4dab-a21c-a70dcc2839f3

**How to reproduce:**
1. Create a standard base application.
2. Enable Code grant type 
3. Disable Skiping login, logout consent  checkbox
4. Try OAuth Code grant type with following scope ` openid sampleScope email profile`
5. After authentication there is no consent approval screen

**Expected behavior:**
After authentication there is should be a consent approval screen

**Comment by Thumimku** [comment]
To get the consent screen, I need to add OIDC scopes as requested user attributes in the application configuration.
Hence this is a false positive one.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
