### ISSUE TITLE
[Doc] Maintain consistency in documenting sample requests and responses under API's

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1872]
Type: Improvement
Priority: High
Severity: Minor
Release: wso2is-5.4.0-update1

In the below page both request and response is documented for each method
https://docs.wso2.com/display/IS540/Managing+Claims+with+APIs
![14](https://user-images.githubusercontent.com/1845370/34206850-32d3a8f6-e5ae-11e7-9b76-06ba948418cd.png)

But in other pages under api's only the request is documented
https://docs.wso2.com/display/IS540/Using+APIs
![15](https://user-images.githubusercontent.com/1845370/34206857-37443f7c-e5ae-11e7-8b2a-b801eda99cbc.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
