### ISSUE TITLE
Error and 500 Network Error When Removing Application Role in App Role Tab

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18729]
**Describe the issue:**
Encountering an error message and a 500 network error when attempting to remove an added application role in the App Role Tab.
**Note: MSSQL Database** 

**How to reproduce:**

1. Navigate to the App Role Tab in the application.
2. Attempt to remove an added application role.
3. Observe the error message and 500 network error.

**Expected behavior:**
Removing an application role from the App Role Tab should proceed without errors and without encountering a 500 network error.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 

---

```
[2023-12-21 13:59:15,293] [373023a9-ad31-49fd-bc2c-1d839e6dd761] ERROR {org.wso2.carbon.identity.api.server.application.management.v1.core.functions.Utils} - errorCode: APP-65001 | message: Error while updating shared roles related to application 11 update.


```
[recording(9).webm](https://github.com/wso2/product-is/assets/39120228/563dab08-951b-4d64-97dc-f53e88ca7df9)

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR. 
- https://github.com/wso2/carbon-identity-framework/pull/5333
