### ISSUE TITLE
Something went wrong when root org admin switching to self onboarded orgs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18727]
**Describe the issue:**

Try  https://is.docs.wso2.com/en/next/guides/organization-management/onboard-sub-org-admins/#maintain-admins-in-the-organization guide

1. Configure email provider in deployment.toml
2. Then try API collection: 
[B2B Stories API Collection.postman_collection.json](https://github.com/wso2/product-is/files/13748968/B2B.Stories.API.Collection.postman_collection.json)

Execute APIs in the following folders in sequence

- Configure a B2B application
- Enable Self Organization Onboarding
- Option 1: onboard admin to created org

You need to manually fix the issue https://github.com/wso2/product-is/issues/18726 

3. Then root org admin login to the console.
4. He can see the self onboarded org with the switch icon
5. When he tries to switch, there is something went wrong page

Organization switching works fine for the orgs created via console

https://github.com/wso2/product-is/assets/25483865/39f29e98-5987-4ffe-b462-c0aefc5a92e9

**Expected behavior:**

- Since the root org admin doesn't have any Console role against the sub org, he should not see the switch icon to switch into the created org via the self-service approach

**Comment by sadilchamishka** [comment]
At the moment, we identify a given organization is an authorized organization if a user association with the authenticated user for that given organization exist.  We can improve that logic further to check the associated user has a role associated with him to indicate it is an authorized organization.
If the b2b app is application audience (ex-console) -> The shared user should have at least one role with audience of given app-id.
if the b2b app is organization audience -> The shared user should have at least one role with organization audience.

**Comment by ChanikaRuchini** [comment]
Approach:

The endpoint /api/users/v1/me/organizations returns a list of organizations for which the user has any role. If someone wants to view the user's authorized organizations due to a particular app's role, they can add a query parameter 'applicationName' to the endpoint. This query parameter filters the result based on the specified application. Subsequently, the console application should display a switch button if the user has a console app role for the organization
