### ISSUE TITLE
Getting an error when deleting role in console setting section [in a sug org] 

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#18722]
**Describe the issue:**

Getting an error when deleting role in console setting section [in a sug org] 

https://github.com/wso2/product-is/assets/40081059/609a0851-5660-4f4c-ae2d-c5fe35b20b72

**How to reproduce:**

1.Login to the console
2.Create a role
3.Create a suborg and switch to it
4.Go to the console setting section
5. navigate to the roles tab in the console setting

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
At the sub organization level, the delete option shouldn't be shown

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR.
- https://github.com/wso2/identity-apps/pull/5127
