### ISSUE TITLE
Secondary User Store Not Displaying in "JIT Provisioning" List

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18736]
**Describe the issue:**
The secondary user store is not displaying in the "JIT Provisioning" list under the Connections section, specifically in the "User store domain to always provision users" section.

**How to reproduce:**

1. Add a secondary user store to the Identity Server.
2. Navigate to the Connections section.
3. Access the "User store domain to always provision users" section.
4. Observe that the secondary user store is not listed in the "JIT Provisioning" dropdown.

**Expected behavior:**
The secondary user store should be listed in the "JIT Provisioning" dropdown under the "User store domain to always provision users" section.

**Environment information** 

- Product Version: wso2is-7.0.0-beta4-SNAPSHOT
- OS: Mac
- Database: DB2
- Userstore: JDBC

---

[recording(10).webm](https://github.com/wso2/product-is/assets/39120228/227e2a69-d01a-440d-8486-338cb8885b20)

**Comment by Thisara-Welmilla** [comment]
The userstores are getting properly retrieved with `/api/server/v1/userstores` API and but does not provide UI support to select the userstores.

**Comment by NipuniBhagya** [comment]
Closing the issue as this is not reproducible in the IS 7.0.0 Beta 4 pack.

<img width="1726" alt="image" src="https://github.com/wso2/product-is/assets/30111554/824118b2-5ffb-48fb-a100-754697498283">

**Comment by deshankoswatte** [comment]
This issue is still reproducible, and it is not reproducible for the super tenant; instead, it is reproducible for a tenant. The steps to reproduce this are as follows:

- Create a tenant through the management console.
- Log in to the tenant console and create a secondary user store.
- Establish a connection and attempt to enable Just-In-Time (JIT) provisioning to provision the user to the secondary user store (note that the secondary user store is not available for selection).

**Comment by brionmario** [comment]
> This issue is still reproducible in WSO2 IS 7.0.0-RC1, and it is not reproducible for the super tenant; instead, it is reproducible for a tenant. The steps to reproduce this are as follows:
> 
> * Create a tenant through the management console.
> * Log in to the tenant console and create a secondary user store.
> * Establish a connection and attempt to enable Just-In-Time (JIT) provisioning to provision the user to the secondary user store (note that the secondary user store is not available for selection).

@savindi7 Please validate this against RC5
