### ISSUE TITLE
Enable branding support for toggle, sliders, and radios

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#18739]
### Description
Currently,  authentication and recovery portals only include checkboxes. Therefore, branding color changes are only enabled for checkboxes.
<img width="314" alt="image" src="https://github.com/wso2/product-is/assets/74205483/a59f894b-c965-49cb-96bb-99f66ec502ab">
However, if we are planning to use any radio, toggle, and slider-type checkboxes, we need to enable branding for those as well. For that, we need to update the `theme-skeleton.jsp` to support branding. This suggestion is derived from https://github.com/wso2/product-is/issues/18610.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
