### ISSUE TITLE
[Doc] Typos in the Configuring a Read-write LDAP User Store page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1873]
Type: Improvement
Priority: Normal
Severity: Minor
Release: wso2is-5.4.0-update1

1. Grammatical mistake in the below description
`Unique name to identify the user store. This should only configured for secondary user store.
`
2. User entry should be two words
`Filtering criteria used to search for a particular userentry.`

https://docs.wso2.com/display/IS540/Configuring+a+Read-write+LDAP+User+Store

**Comment by ShirazAzad** [comment]
Fixed. Corrected the docs [1] and [2]
[1] https://docs.wso2.com/display/IS530/Configuring+a+Read-write+LDAP+User+Store
[2] https://docs.wso2.com/display/IS540/Configuring+a+Read-write+LDAP+User+Store
