### ISSUE TITLE
UI Issue in Outbound Provisioning  Connection 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18734]
**Describe the issue:**
It Should be 
1. OutBound Provisioning Connectors > Outbound Provisioning Connectors
2. OutBound Provisioning Roles > Outbound Provisioning Roles

<img width="1349" alt="Screenshot 2023-12-21 at 17 37 08" src="https://github.com/wso2/product-is/assets/39120228/f20da82f-e8b3-4c94-b692-110893d08f19">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
