### ISSUE TITLE
Unable to Add and List Created Roles in Outbound Provisioning 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18735]
**Describe the issue:**
There is no option to add and no listing of created roles in Outbound Provisioning, in Connectors.
Although the new UI provides a list for roles, the created roles are not appearing in the list, and it is not possible to add roles using the provided "+" option.

 In the management console, the same feature requires users to type the role, but in the new UI, it is expected to be a list.

[outboundprovisionrole_issue.webm](https://github.com/wso2/product-is/assets/39120228/a754eea8-adea-49f0-b7b9-6c1d77aadc4f)

**How to reproduce:**

1. Navigate to the Outbound Provisioning section in the new UI.
2. Observe that the list of created roles is not displayed.
3. Attempt to add a role using the provided "+" option and observe the issue.

**Expected behavior:**
The new UI should provide a list of created roles in the Outbound Provisioning Connectors, and users should be able to add roles using the provided "+" option.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta4-SNAPSHOT
 - OS:Mac
 - Database: DB2
 - Userstore: JDBC

---

**Comment by NilukaSripalim** [comment]
This is fixed and verified in wso2is-7.0.0-beta5-SNAPSHOT
<img width="1625" alt="Screenshot 2023-12-24 at 17 14 08" src="https://github.com/wso2/product-is/assets/39120228/e6e5d755-ba1a-43bd-9119-170898ba6f8b">

<img width="704" alt="Screenshot 2023-12-24 at 17 14 13" src="https://github.com/wso2/product-is/assets/39120228/af1fc4ae-76ea-4841-899a-24213a471c6e">

**Comment by NilukaSripalim** [comment]
still reproduce a particular issue  with a "tenanted path." 
<img width="803" alt="Screenshot 2023-12-24 at 17 21 20" src="https://github.com/wso2/product-is/assets/39120228/2ce49f03-a9c4-431b-bac2-6e7c62344558">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
