### ISSUE TITLE
UM_GROUP_UUID_DOMAIN_MAPPER uses the sequence number generator from a different table on PostgreSQL User Store Scripts

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#18737]
**Describe the issue:**
We're currently using `UM_HYBRID_REMEMBER_ME_PK_SEQ` as the sequence number generator for the `UM_GROUP_UUID_DOMAIN_MAPPER` table even though it was meant for the `UM_UUID_DOMAIN_MAPPER`.
This likely stems from a copy and pasting issue when creating the script for the first time.

```sql
DROP TABLE IF EXISTS UM_UUID_DOMAIN_MAPPER;
DROP SEQUENCE IF EXISTS UM_UUID_DOMAIN_MAPPER_PK_SEQ;
CREATE SEQUENCE UM_UUID_DOMAIN_MAPPER_PK_SEQ;
CREATE TABLE IF NOT EXISTS UM_UUID_DOMAIN_MAPPER (
            UM_ID INTEGER DEFAULT NEXTVAL('UM_HYBRID_REMEMBER_ME_PK_SEQ'),
            UM_USER_ID VARCHAR(255) NOT NULL,
            UM_DOMAIN_ID INTEGER NOT NULL,
            UM_TENANT_ID INTEGER DEFAULT 0,
            PRIMARY KEY (UM_ID),
            UNIQUE (UM_USER_ID),
            FOREIGN KEY (UM_DOMAIN_ID, UM_TENANT_ID) REFERENCES UM_DOMAIN(UM_DOMAIN_ID, UM_TENANT_ID) ON DELETE CASCADE
);

# . . .

DROP TABLE IF EXISTS UM_GROUP_UUID_DOMAIN_MAPPER;
DROP SEQUENCE IF EXISTS UM_GROUP_UUID_DOMAIN_MAPPER_PK_SEQ;
CREATE SEQUENCE UM_GROUP_UUID_DOMAIN_MAPPER_PK_SEQ;
CREATE TABLE IF NOT EXISTS UM_GROUP_UUID_DOMAIN_MAPPER (
            UM_ID INTEGER DEFAULT NEXTVAL('UM_HYBRID_REMEMBER_ME_PK_SEQ'),
            UM_GROUP_ID VARCHAR(255) NOT NULL,
            UM_DOMAIN_ID INTEGER NOT NULL,
            UM_TENANT_ID INTEGER DEFAULT 0,
            PRIMARY KEY (UM_ID),
            UNIQUE (UM_GROUP_ID),
            FOREIGN KEY (UM_DOMAIN_ID, UM_TENANT_ID) REFERENCES UM_DOMAIN(UM_DOMAIN_ID, UM_TENANT_ID) ON DELETE CASCADE
);

```

**How to reproduce:**
1. See the PostgreSQL User Store DB Scripts (`<IS_HOME>/dbscripts/postgres.sql`) on any fresh or updated Identity Server instance.

**Expected behavior:**
It's expected that `UM_GROUP_UUID_DOMAIN_MAPPER` uses the sequence created for it (`UM_GROUP_UUID_DOMAIN_MAPPER_PK_SEQ`).

**Environment information:**
 - Product Version: IS 5.10.0 -> 6.1.0
 - Database: PostgreSQL
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
