### ISSUE TITLE
Username and password pattern policy is not executed when creating users under user stores

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1874]
Type: Bug
Priority: High
Severity: Major
Release: wso2is-5.4.0-update1

1. Create a secondary user store.
2. Configure the username and password validation error message
![19](https://user-images.githubusercontent.com/1845370/34213544-7e52ff2c-e5c5-11e7-87d0-cb299ebe3583.png)
3. Create a user under the user store violating the username and password pattern policy

**Issue**
The error message returned to the user is not what is configured here

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
