### ISSUE TITLE
[Userstore][JDBC] "Test Connection" doesn't work with the saved JDBC Connection details

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#18747]
**Describe the issue:**
As in carbon console, the Test Connection of a JDBC userstore should work with saved details. Currently, Test Connection doesn't work unless the password is entered. 

**How to reproduce:**
1. Create a JDBC Userstore
2. Navigate "Connection"
3. Click on "Test Connection"

Screen recording: 

https://github.com/wso2/product-is/assets/106053688/e63fed97-8c79-4d7f-bd78-b1a23388e262

**Expected behavior:**
Since the password is already saved, the test connection should work. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
