### ISSUE TITLE
`errorMessage` param should always be an i18n key and should not contain special characters.

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18740]
**Describe the issue:**

$subject

Derived from https://github.com/wso2/product-is/issues/18730#issuecomment-1866440102

**How to reproduce:**

Please see the above mentioned issue comment.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
When the logout fails due to post logout redirect URI doesn't match with registered URLs, the following UI is displayed. Note that here also the error message in plain text is returned to frontend. Instead, an i18n key should have been returned.

<img width="1501" alt="Screenshot 2024-04-26 at 16 23 58" src="https://github.com/wso2/product-is/assets/41533942/fa51b9da-4d05-49a5-a048-ca5f99c3b32b">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
