### ISSUE TITLE
Alignment issue in userstore enabled icon and popup

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#18749]
**Describe the issue:**

<img width="1512" alt="Screenshot 2023-12-22 at 12 37 48" src="https://github.com/wso2/product-is/assets/41533942/672e9ed7-b4c2-4153-8746-87d0c507cd36">

**How to reproduce:**

1. Sign into console.
2. Create a userstore.
3. In the userstore list page, hover over the status icon in the userstore list item.

**Expected behavior:**

Icon and popup should be aligned.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
