### ISSUE TITLE
System logs does not reflect the errors encountered during an authentication failure

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1875]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
OS - Ubuntu-14.04-LTS
Browser Chrome 58.0.3029.96

**Steps to reproduce the issue**
1. Create Facebook and Google as IDP
2. Create SP and connect FB, Google and Resident IDP and IDPs
3. Configure Travelocity with the fidp query param corresponding with the resident IDP (ex: in default pack this is localhost)
4. Stop one node of the cluster
5. Disconnect the db connectivity
6. Simulate the login with resident IDP using jmeter and send a load of (1 thread , 10 ramp up and 100 loop)
7. Connect the DB
8. Log in to management console and check the system logs to view the errors on the server

**Observations**
Backend errors do not reflect in the system logs.

![screenshot from 2017-12-21 10-07-16](https://user-images.githubusercontent.com/14962228/34240756-c1902cf8-e636-11e7-9087-d6061780fe00.png)

**Expected Results**
Several error messages logged in the backend due to db failure (check the logs for more details) but that does not reflect in the System logs. As an admin user, I prefer to check the system logs to identify the server failures.

Please find the downloaded log files  
[wso2carbon.log.zip](https://github.com/wso2/product-is/files/1577934/wso2carbon.log.zip)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
