### ISSUE TITLE
Customizing authentication endpoint URL is not working

### ISSUE THREAD

**Issue by Rashmini** [wso2/product-is#18754]
**Describe the issue:**
Authentication endpoint URL customization is not working.

**How to reproduce:**

1. Add the following configurations to the `<IS_HOME>/repository/conf/deployment.toml` file, and change the value of the `login_url` parameter depending on the URL on which the web application should run. [1]

```
[authentication.endpoints] 
login_url="/sso/login"
```

2. Run the web application on the new authentication endpoint URL.

**Expected behavior:**
Authentication endpoint URL should be changed to the customized one.

[1] https://is.docs.wso2.com/en/latest/references/extend/customize-the-authentication-endpoint/

**Comment by DMHP** [comment]
Need to remove the following docs from the doc space.
1. 'Customize the authentication endpoint URL' part of the https://is.docs.wso2.com/en/latest/references/extend/customize-the-authentication-endpoint/
2. 'Control the request parameters going to the authentication endpoint' part of the https://is.docs.wso2.com/en/latest/references/extend/customize-the-authentication-endpoint/

Need to add the following document to the versions later than 5.9.0
https://is.docs.wso2.com/en/5.9.0/develop/authentication-data-api/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
