### ISSUE TITLE
UI alignmnet issue > Connections, Create outbound provisioning connector wizard

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18760]
**Describe the issue:**
<img width="881" alt="Screenshot 2023-12-24 at 17 06 36" src="https://github.com/wso2/product-is/assets/39120228/47ce3e2d-cfe2-4f92-a69e-41d15366abe5">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT 
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
