### ISSUE TITLE
Account suspension: configuration effect when done through management console

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1876]
In [1] in the account suspend delay is configured through the management console. In identity-event.properties file there is below config.
`suspension.notification.account.disable.delay=90`

How is this affecting to the overall suspension delay time? What takes priority is it above config or the one configured through management console?

[1] https://docs.wso2.com/display/IS540/User+Account+Suspension

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
