### ISSUE TITLE
Newly Added Scopes Not Visible in User Consent Page and Authentication Response

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18763]
**Describe the issue:**
After adding new scopes to the existing API resources, the added scopes are not reflecting on the user consent page during the login application process. Additionally, the authentication response does not include information about the newly added scopes.

**How to reproduce:**

1. Navigate to the WSO2 Identity Server Console.
2. Go to API Resources.
3. Select an existing API resource.
4. Click on the "Scopes" tab.
5. Add new scopes to the API resource.
6. Save the changes.
7. Authorize API Resources for an App, and 
8. Select the application and go to User Management > Roles. and update Permissions 
9. Attempt to log in using an application that requests access to the API resource.

**Expected behavior:**
The user consent page should display the newly added scopes for user approval.
The authentication response should include information about the granted scopes.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT
 - OS: Mac
 - Database:Db2
 - Userstore:JDBC

---

[APIResources.webm](https://github.com/wso2/product-is/assets/39120228/c4744f12-b3f8-4e75-9a34-65d0a924b211)

**Comment by ChanikaRuchini** [comment]
This works as expected. By default, the 'skip login consent' option is enabled. To display the newly added scopes on the user consent page, should untick the 'skip login consent' checkbox in the application settings > advanced.

**Comment by NilukaSripalim** [comment]
Tested with wso2is-7.0.0-beta5-SNAPSHOT, working as expected 
<img width="953" alt="Screenshot 2024-01-03 at 15 27 04" src="https://github.com/wso2/product-is/assets/39120228/a6f3c9af-c47d-48cd-9da6-d135e26b0c6f">
