### ISSUE TITLE
Global Token Expiration Time Update Issue in Single Page (SP) and Traditional Web Applications

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18766]
**Describe the issue:**
When attempting to change the default token expiration time globally, two distinct issues have been identified:

**Single Page (SP) Application Issue:**

The global changes to the expiration time are not reflecting in Single Page (SP) applications. Despite updating the values via the global configuration, SP applications still operate with the previous expiration times.
After Changes
<img width="958" alt="Screenshot 2023-12-28 at 01 27 10" src="https://github.com/wso2/product-is/assets/39120228/4015c26d-be36-44b7-8182-09a4348747a9">

**Traditional Web Application Issue:**

In Traditional Web Applications, specifically in the "Access token expiry time" input field, is missing after updating the global configuration. 
Before Changes 
<img width="940" alt="Screenshot 2023-12-28 at 01 30 36" src="https://github.com/wso2/product-is/assets/39120228/fa6f2ffa-32e2-4b38-8e56-9b8c060fe1bb">

After Changes
<img width="1241" alt="Screenshot 2023-12-28 at 01 30 15" src="https://github.com/wso2/product-is/assets/39120228/e967f04f-2a97-4964-9050-e16e660d6647">

**How to reproduce:**
Open the global configuration file (e.g., deployment.toml).
Change the default expiration times globally under [oauth.token_validation].
eg.
```
[oauth.token_validation]
app_access_token_validity=1800
user_access_token_validity=1800
refresh_token_validity = 96400
```
Save the changes and restart the application.
Observe the behavior in both Single Page (SP) and Traditional Web Applications.

**Note : Changes are applied as expected with "standards based application" and Management console**
<img width="1023" alt="Screenshot 2023-12-28 at 01 42 35" src="https://github.com/wso2/product-is/assets/39120228/bc2adac3-2568-4ec4-a991-9a3dfc538730">

<img width="666" alt="Screenshot 2023-12-28 at 01 43 33" src="https://github.com/wso2/product-is/assets/39120228/54664428-e1aa-4fd8-9c8d-fda7e98d29d7">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore:JDBC

---

**Comment by DMHP** [comment]
Some default values have been set from the FE.


![Image](https://github.com/wso2/product-is/assets/12690906/3e54f679-3c04-4093-ab71-dcd0b771aa86)

The values for "userAccessTokenExpiryInSeconds" and "applicationAccessTokenExpiryInSeconds" should not have any default values or be 0. Please check all the expiry times and remove the defaults from the FE side.  Additionally we need to check the reason for not displaying the  "Access token expiry time" in the Traditional Web Applications.

**Comment by savindi7** [comment]
This issue is there in 6.1 pack as well. Adding a fix by taking the values from the oidc meta endpoint.

<img width="401" alt="Screenshot 2024-01-05 at 13 12 33" src="https://github.com/wso2/product-is/assets/67315176/1e6ffbe5-02eb-47b9-a03d-70b9e740ddc4">

**Comment by savindi7** [comment]
Regarding the traditional web application issue mentioned in the description,
the Application access token expiry time field is hidden when client credentials grant type is not chosen.. this is expected. Shall we check again if you are getting this behaviour on enabling/disabling the grant type? @NilukaSripalim

**Comment by NilukaSripalim** [comment]
Yes, it is updated after enabling client credential grant type in traditional web application, expected app access token expiration is updated when token time is updated globally.
<img width="885" alt="Screenshot 2024-01-09 at 05 37 32" src="https://github.com/wso2/product-is/assets/39120228/4848d4fa-abad-41fc-92d4-ba7cbe32b471">
