### ISSUE TITLE
Issue with Different Error Messages After Keeping Console Idle 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18764]
**Describe the issue:**
After keeping the console idle, different error messages are encountered. However, no corresponding error logs are generated, making it challenging to identify the root cause of the issue.

Can be reproduce with even if No any config changes fresh pack 
**How to reproduce:**
1. Open the console/application.
2. Keep the console idle for approximately 1 hour.
3. Observe the occurrence of different error messages.

**Expected behavior:**
The system should remain stable and not produce any errors after being idle for an extended period. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT
 - OS: Mac
 - Database:H2, DB2
 - Userstore: JDBC

---

<img width="1728" alt="Screenshot 2023-12-27 at 23 02 18" src="https://github.com/wso2/product-is/assets/39120228/ff29d523-5afc-48c6-8917-69b3f94206fa">

<img width="1727" alt="Screenshot 2023-12-27 at 23 02 38" src="https://github.com/wso2/product-is/assets/39120228/203a410c-9e0d-4e4b-9f36-593409a22330">

<img width="1728" alt="Screenshot 2023-12-27 at 23 03 38" src="https://github.com/wso2/product-is/assets/39120228/e0380291-a581-45cd-b599-54c6d50ea30c">

<img width="1728" alt="Screenshot 2023-12-27 at 23 03 48" src="https://github.com/wso2/product-is/assets/39120228/2786e9d6-d74a-4cad-80ad-13aea228affe">

<img width="1728" alt="Screenshot 2023-12-27 at 23 03 57" src="https://github.com/wso2/product-is/assets/39120228/38d769e1-27a9-4305-aa5b-b1fed1889720">

**Comment by NilukaSripalim** [comment]
2024-01-03 

<img width="1728" alt="Screenshot 2024-01-03 at 12 43 11" src="https://github.com/wso2/product-is/assets/39120228/555e1c0f-9f96-468d-a60f-25008d50cb8b">
<img width="1728" alt="Screenshot 2024-01-03 at 12 45 56" src="https://github.com/wso2/product-is/assets/39120228/dd44118f-fcae-45a8-9118-f8426e17c74c">

**Comment by NilukaSripalim** [comment]
<img width="1728" alt="Screenshot 2024-01-05 at 10 02 53" src="https://github.com/wso2/product-is/assets/39120228/06fb217b-3092-4a8e-98ec-15100c1ece9c">

<img width="1728" alt="Screenshot 2024-01-05 at 10 03 05" src="https://github.com/wso2/product-is/assets/39120228/5d702f31-3168-4b80-a68f-4e12c4d4f8da">

**Comment by melanisilva** [comment]
Cannot even logout when this happens.

https://github.com/wso2/product-is/assets/41188245/5b9570c3-cd69-47d2-971f-421aeb5f3966

**Comment by brionmario** [comment]
Related Issue:

- https://github.com/wso2/product-is/issues/18914

*@malithie's observations*

**How to reproduce:**
1. Keep the console idle for like an hour and try to access. You will see the popup that says 'you have been inactive for a long time'
2. Try to list some apps, or list connections etc.
3. Note the errors coming up
4. If you refreshed the screen things will start working again

**Expected behavior:**
After the popup, the console should reinitiate the session and things should work properly
