### ISSUE TITLE
Account locking by failed attempts: Provide sample for IdentityGovernanceAdminService and relevant permission needed for user who invokes this

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1877]
In [1] it states to use the IdentityGovernanceAdminService but there is no sample. Please provide a sample and also include what kind of permission a user needs to have to invoke this service as using super admin credentials to invoke admin services is not practical.

[1] https://docs.wso2.com/display/IS540/Account+Locking+by+Failed+Login+Attempts#AccountLockingbyFailedLoginAttempts-Accountlockingforaparticularuser

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
