### ISSUE TITLE
Invite offline link API is not working for sub-organizations

### ISSUE THREAD

**Issue by DonOmalVindula** [wso2/product-is#18788]
**Describe the issue:**
When implementing https://github.com/wso2/product-is/issues/18248, It was observed that the `invite-offline-link` API is not working for sub-organizations. 

This is likely due to missing scopes in the sub-organizations.
![image](https://github.com/wso2/product-is/assets/42619922/8dc93236-dd5d-4f92-af46-286c0a245082)

**How to reproduce:**
1. Call `invite-offline-link` API with the scopes received from a sub-org

**Expected behavior:**
- The API should work in sub-orgs similar to root orgs and super orgs

**Related issues:**

- https://github.com/wso2/product-is/issues/18248

**Comment by JeethJJ** [comment]
Above pr resolves the access for the endpoint. So the 403 is resolved. 
But there is a bug in the feature where the sub org users are still not detected. This needs to be checked.
