### ISSUE TITLE
Account suspension: No information on claim information

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1878]
In [1] it states that there are relevant claim values and they can be viewed by following another document.

```
By default, the claim values of the identity claims used in this feature are stored in the JDBC datasource configured in the identity.xml file. See Configuring Claims for more information on how to store the claim values in the user store.
```
If any claims are used for this feature then they needs to be mentioned here. Please mention any such here itself

[1] https://docs.wso2.com/display/IS540/User+Account+Suspension

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
