### ISSUE TITLE
[SAML] Invalid Error: Enter a valid URL for URL based SAML application creation for valid meta url

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18785]
**Describe the Issue:**

Error: Enter a valid URL for URL based SAML application creation. URL is a valid one. required to make click action outside from the input filed for remove the invalid error message 

<img width="725" alt="Screenshot 2024-01-03 at 08 54 39" src="https://github.com/wso2-enterprise/asgardeo-product/assets/39077751/d12d7a07-e65a-46f4-8dd6-3260785a969e">

https://github.com/wso2-enterprise/asgardeo-product/assets/39077751/4ab87bfd-4f39-4747-b368-433781431cd0

**How To Reproduce:**

1. Login to console
2. Navigate to application and select traditional or standard based application.
3. Select SAML
4. Select url based
5. Add app name
6. Add valid meta url : https://samltest.id/saml/sp

**Expected behavior:**

Since the url is valid no error should be appear. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 beta5 jenkin build 5005
 - OS: [e.g., Windows, Linux, Mac]
 - Database: Postgres
 - Userstore: [e.g., LDAP, JDBC] 

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
Unable to reproduce in the latest pack
