### ISSUE TITLE
Represent all server errors through system logs

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1879]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
OS - Ubuntu-14.04-LTS
Browser Chrome 58.0.3029.96

**Steps to reproduce the issue**
1. Go to 'Monitor' -> System Logs
2. Check the error logs on the server

**Use Case**
As an admin user, I want to monitor the server errors in the cluster nodes, so that I can get corrective action depending on the severity of the issue.

**Observations**
Since the nodes are fronted by Nginx, From the management console it does not reflect the errors in both nodes. It only reflects the logs relevant to the node where the management console is up and running.

It would be better to provide a mechanism to monitor all server logs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
