### ISSUE TITLE
Improvement to navigate back to multi-option page after entering a wrong OTP code

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#18807]
**Describe the issue:**
Users are unable to go back to the multi-option page after entering a wrong OTP code during the MFA option.

As shown in the below image before entering the OTP users has the option to choose a different authentication option

<img width="548" alt="Screenshot 2024-01-04 at 1 54 18 PM" src="https://github.com/wso2/product-is/assets/13187638/05d4769a-e485-49e7-9423-40f93ce0e62d">

After entering the wrong OTP code, user is no longer able to choose a different authentication option

<img width="548" alt="Screenshot 2024-01-04 at 1 54 27 PM" src="https://github.com/wso2/product-is/assets/13187638/195d5f15-0d04-411f-8fec-888a0f9ebbe4">

This can be improved by submitting back the multiOptionURI to relevant backend components during above form submission.
```
<%
 String multiOptionURI = request.getParameter("multiOptionURI");
 if (multiOptionURI != null && AuthenticationEndpointUtil.isValidURL(multiOptionURI)) {
%>

<input type='hidden' name='multiOptionURI' id='multiOptionURI' value= <%=multiOptionURI%> />

<%
 }
%>
```

**How to reproduce:**
- Get the latest IS-5.10.0 pack
- Configure a service provider with two MFA options (eg: smsotp, emailotp)
- Login to the service provider and when prompted for the OTP code enter a wrong OTP code

**Expected behavior:**
The user should be able to go back to multi-option page and choose a different authentication option. This needs to be fixed in the all the webapps (smsotp, emailtop, totp).

**Environment information**  **:**
 - Product Version: [IS 5.10.0]

---

**Related issues:**
https://github.com/wso2/product-is/issues/16252

**Comment by madurangasiriwardena** [comment]
Fixed with https://github.com/wso2-extensions/identity-auth-otp-commons/pull/5
