### ISSUE TITLE
SP: cas-client-webapp - 500 Internal Server Error displayed when client secret in incorrect in Facebook federated authenticator 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1880]
**Steps to re-create**
1. Configure Service Provider as cas-client-webapp[1]
2. Configure Federated Authenticator as Facebook. 
3. Update Facebook Idp and provide an incorrect client ID. 
4. Login to cas client web app. 
> https://localhost:8443/cas-client-webapp/ 
5. Provide Facebook credentials. 

**Expected:** A meaningful error page is expected. 
**Actual:** It is displayed as 500 Internal Server Error. 

[1] - https://docs.wso2.com/display/ISCONNECTORS/CAS+Inbound+Authenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
