### ISSUE TITLE
Admin user can not be assigned to a user group by editing the Group

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18800]
Admin users can not be assigned to a user group by editing the group. 
<img width="926" alt="image" src="https://github.com/wso2/product-is/assets/12690906/6475667b-4825-46a5-9b70-8470c67ab73e">

By editing the group the admin user can be assigned.

<img width="793" alt="image" src="https://github.com/wso2/product-is/assets/12690906/5808f05c-969f-42e2-8222-f00e0c513abf">
  

Expectation: The user should be able to assign tot he user group by editing the group.

**Comment by savindi7** [comment]
Unable to reproduce in the latest pack.
