### ISSUE TITLE
AuthFailure message not getting cleared after choosing a different authentication option

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#18811]
**Describe the issue:**

AuthFailure message is persisted in the redirection URIs to the webapps(smsotp, emailotp, ...). In a scenario, where there are multiple MFA options, upon entering a wrong OTP code below error message is displayed, which is correct.

<img width="547" alt="Screenshot 2024-01-04 at 2 43 32 PM" src="https://github.com/wso2/product-is/assets/13187638/ddb44e49-f1e2-4138-9901-ae24aa1a07b4">

But, when the user clicks on "Choose a different authentication option" and selects a different MFA option, still the error message is displayed in the new authentication option.

This happens because the framework sets retrying to true [1] in the authentication context when a wrong OTP code is entered. But this value is not getting cleared when the user is navigating back to the multi-option page. 

**How to reproduce:**
- Get the latest IS-5.10.0 pack
- Configure a service provider with two MFA options (eg: smsotp, emailotp)
- Login to the service provider and when prompted for the OTP code enter a wrong OTP code
- Select "Choose a different authentication option" (https://github.com/wso2/product-is/issues/18807)
- From the multi-option page choose a different MFA option 

**Expected behavior:**
AuthFailure should be cleared after choosing a different authentication option

**Environment information** **:**
 - Product Version: [IS 5.10.0]

---

[1] - https://github.com/wso2/carbon-identity-framework/blob/v5.17.5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/AbstractApplicationAuthenticator.java#L60-L131

**Comment by Sachin-Mamoru** [comment]
Public fixed with https://github.com/wso2/carbon-identity-framework/pull/5392
