### ISSUE TITLE
[Doc] [Improvement] Please update Troubleshooting Tips with an addtional step in "Configuring IWA on Linux" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1882]
In configuring IWA on Linux page [1] Please add some additional troubleshooting step for below error.

Enter username and password of appeared  UI console while SSO via travelocity app
Once you click on the login buttion,
         it will try to reload the page and backend will throw below error. 
         This is due to browser is not sending the Kerberos  token.
         In order to resolve this, follow the steps mention in the article [2]
`WARN {org.wso2.carbon.identity.application.authenticator.iwa.servlet.IWAServlet} -  NTLM token found.
[2017-12-20 16:36:29,800] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  GSS token not present in the http session
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: GSS token not present in the http session`

[1] https://docs.wso2.com/display/IS540/Configuring+IWA+on+Linux#2301bef1899c44458567e19e6c99dd29
[2] https://ping.force.com/Support/PingFederate/Integrations/How-to-configure-supported-browsers-for-Kerberos-NTLM

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
