### ISSUE TITLE
Getting a Start up error - `ERROR {org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementEventPublisherProxy} `

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18838]
**Describe the issue:**
Getting a start-up error as below.

`ERROR {org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementEventPublisherProxy} - Error while publishing the event: POST_UPDATE_PERMISSIONS_FOR_ROLE_V2_EVENT. org.wso2.carbon.identity.event.IdentityEventException: Invalid role id :39a9f8b0-29de-4a79-9e46-a96e3387c054in tenant domain carbon.super`

### Note : Build #5011 (08-Jan-2024 00:33:22)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ZiyamSanthosh** [comment]
This is completed. Hence, closing this issue.
