### ISSUE TITLE
Office 365-Based Adaptive Authentication Script Not Functioning Properly

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18832]
**Describe the issue:**
Office365-based Adaptive Authentication default script is not working since it has the domain in the `roleToBeAssigned` variable.

Note: Once the `Internal ` part is removed the script works as expected.

**How to reproduce:**

1. Create a role named `office365Role`
2. Go to the selected app and from sign-in method tab enable the `Update office365 role` script
3. Assign the created role to the app from the Roles `tab`
4. try the sign-in flow
5. Find that the defined role is not assigned to the logged-in user.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
As discussed with @AnuradhaSK let's modify this function hasAnyOfTheRolesV2 to ignore the domain and validate the role. For example in this case the role needs to be assigned in both cases when the role is Internal/office365Role or office365Role

**Comment by PasinduYeshan** [comment]
This issue is fixed from following PR.
- https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/153
