### ISSUE TITLE
Configure enabling/disabling x5t#s256 in JWKS response

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#18839]
**Describe the issue:**
The x5t#S256 parameter in the JWKS response is an optional parameter, it is included in the JWKS response and the value returned for this parameter is calculated through different mechanisms[1][2] and it is causing failures in certain libraries when parsing the x5t#s256.

Since this parameter was newly introduced, a configuration can be used to disable it until the proper format of x5t#S256 parameter is confirmed[1].

 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]

[1]https://github.com/wso2/product-is/issues/18817
[2]https://github.com/wso2/product-is/issues/14899

**Comment by dhaura** [comment]
Closing this issue since the proper fix is provided by: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2331
