### ISSUE TITLE
[Doc] There should be a document explaining methods supported by KeyStoreAdminService and its functionalities

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1883]
[Doc] There should be a document explaining methods supported by KeyStoreAdminService and its functionalities.

This is specially useful when you have a tenant and need to import certificate  and wll. better to explain with a sample for tenant space as well

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
