### ISSUE TITLE
Onboarding org with self service approach doc should be updated to share the app with sub org before switching token

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#18835]
When needed to obtain organization_switch_cc grant to invite user to sub organization, the B2B-Self-Service-Mgt-Application should be shared with the relevant sub organization and then should be unshared when the relevant operations are done (the doc: https://is.docs.wso2.com/en/next/guides/organization-management/onboard-sub-org-admins/#self-service-approach should be updated accordingly with the API calls for both `Maintain admins in the organization` and `Maintain admins in the organization (root)`)

Related issue - https://github.com/wso2/product-is/issues/18486

**Comment by AnuradhaSK** [comment]
This is not required because the self-org onboarding approach has changed. 
Required changes is tracked in https://github.com/wso2/product-is/issues/19080
Hence closing this issue
