### ISSUE TITLE
[Design] Create a logo for workflow connector

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#18843]
**Describe the task**
Recently we removed the workflow feature from IS carbon and created a connector. We need an icon for the workflow IS connector to publish in the [connector store](https://store.wso2.com/store/assets/isconnector/list  ).  Need to come up with a suitable design that includes a workflow logo.  Here is the related [documentation](https://is.docs.wso2.com/en/5.9.0/learn/workflow-management/#:~:text=The%20workflow%20feature%20enables%20you,when%20adding%20a%20user%20account) of this feature. I think an icon similar to [this](https://www.vectorstock.com/royalty-free-vector/workflow-icon-on-white-background-flat-style-vector-22691904) might convey the message.

**Task derived from**

https://github.com/wso2/product-is/issues/18407

**Comment by savindi7** [comment]
Example icon (as mentioned in the description)
<img width="250" alt="Screenshot 2024-01-09 at 14 26 31" src="https://github.com/wso2/product-is/assets/67315176/62d8e764-e8d2-4cc0-887b-de9e8beba983">

**Comment by Sergiy-b** [comment]
![Uploading Screenshot 2024-01-10 at 18.08.22.png…]()

**Comment by savindi7** [comment]
https://www.figma.com/file/9QxyluUvzXAMbTdixve9Dh/Assets?type=design&node-id=2155-4&mode=design&t=jhjB4wR8E0CeUuR5-0 

@AnjanaSamindraPerera let's add this to Oxygen and use.
