### ISSUE TITLE
[Custom-connector] Allow federated authenticator deletion when there is only one authenticator

### ISSUE THREAD

**Issue by dasuni-30** [wso2/product-is#18845]
**Is your suggestion related to an experience ? Please describe.**
We are allowing to have only one federated authenticator for the custom connector with https://github.com/wso2/product-is/issues/18651. The console prompts an error when the user attempts to delete the authenticator when there's only one authenticator. 

https://github.com/wso2/product-is/assets/27746285/e42dbe9c-1ac9-40e7-ae50-bf6712ac1b94

**Expected Behaviour**
Ideally, when we create a new custom connector, there are no federated authenticators in the beginning. Hence the user should be able to delete the federated authenticator when there's only one and add a new authenticator as preferred.
<img width="1440" alt="Screenshot 2024-01-09 at 10 17 53" src="https://github.com/wso2/product-is/assets/27746285/42155ffb-e4e8-44b4-b030-72b472a738d4">

**Comment by UdeshAthukorala** [comment]
Hi @dasuni-30 ,

- We can delete the authenticator when there's only one authenticator configured in the custom connector IDP by using the [federated authenticator Update API](https://is.docs.wso2.com/en/latest/apis/idp-rest-api/#/Federated%20Authenticators/updateFederatedAuthenticators). Following Is the same payload that I have used to delete the authenticator.

  ```
  {
          "defaultAuthenticatorId": "",
          "authenticators": []
  }
  ```

- According to the abov attched vedio seems like the value you have used for `defaultAuthenticatorId` is wrong. According to the Federated Authenticators Update request payload definition `defaultAuthenticatorId` is a required attribute and we need to send a empty string when there are no authenticators.
- Even when creating the new custom connector at the beginning without any authenticators also, in the [IDP create request](https://is.docs.wso2.com/en/latest/apis/idp-rest-api/#/Identity%20Providers/addIDP) we are using a similar approach with the federated authenticators by setting a empty string as the value of `defaultAuthenticatorId` attribute.

  ```
  {
      "image": "assets/images/logos/expert.svg",
      "roles": {
          "mappings": [],
          "outboundProvisioningRoles": []
      },
      "certificate": {},
      "description": "Custom",
      "federatedAuthenticators": {
          "defaultAuthenticatorId": "",
          "authenticators": []
      },
      "homeRealmIdentifier": "",
      "isPrimary": false,
      "claims": {
          "userIdClaim": {
              "uri": ""
          },
          "provisioningClaims": [],
          "roleClaim": {
              "uri": ""
          }
      },
      "name": "IDP",
      "alias": "",
      "provisioning": {},
      "isFederationHub": false,
      "idpIssuerName": "",
      "templateId": "expert-mode-idp"
  }
  ```

**Comment by dasuni-30** [comment]
We didn't make any changes for the API call nor the payload from the FE. Will check if we can change the payload from the FE and fix it.

**Comment by dasuni-30** [comment]
### Verified in the new pack

https://github.com/wso2/product-is/assets/27746285/fbbcdcb5-2747-4a28-bc95-2a6a853b3361
