### ISSUE TITLE
Outbound Provisioning - SCIM via Console not working

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18840]
**Describe the issue:**
Outbound provisioning via SCIM in the Console is not functioning as expected. There are multiple issues identified in the current flow.

**Issue 1: Incorrect Display of SCIM Type in Console UI**

When enabling SCIM as the Outbound provisioning type via "Custom Connector > Outbound Provisioning" in the Console, the UI incorrectly displays "scim" as the selected type. This is reminiscent of the previous behavior when SCIM 1.1 was selected using the management console. However, there is currently no option to choose between SCIM 2.0 or SCIM 1.1. Consequently, even though SCIM 2.0 user/groups endpoints are provided, the UI inaccurately shows the selected type as "scim."

<img width="1340" alt="Screenshot 2024-01-08 at 17 41 19" src="https://github.com/wso2/product-is/assets/39120228/78ecef73-ac0d-401f-94b0-804b4bdd4026">

**Issue 2: Incorrect Display of SCIM Type via Service Provider**

Similarly, when selecting the outbound type via the Service Provider, the UI displays "scim" even though SCIM 2.0 configurations are in place. This inconsistency in the UI is causing issues when attempting outbound provisioning via SCIM in the New Console.

<img width="1525" alt="Screenshot 2024-01-08 at 17 44 08" src="https://github.com/wso2/product-is/assets/39120228/46ba210f-7484-4da8-af61-2d4ff54fe57b">

**Additional Observations:**

Upon inspecting the Management Console, it was noted that the configured SCIM 2.0 details are listed under "SCIM 1.1 Provisioning Configuration." Furthermore, in the "Service Providers > Resident" section, the connection selected via the Console is not reflected in the Management Console.
<img width="1484" alt="Screenshot 2024-01-08 at 18 09 54" src="https://github.com/wso2/product-is/assets/39120228/0946b36f-b37b-4400-bab2-feecf6ee3baf">

**Proposed Solution:**

It is recommended to revalidate the Console UI to accurately reflect the selected SCIM type and ensure proper integration with SCIM 2.0 configurations. Additionally, the discrepancy between the Management Console and the Console in terms of SCIM configuration should be addressed for a seamless user experience.

**How to reproduce:**

1. Navigate to "Custom Connector > Outbound Provisioning" in the Console.
2. Observe the display of "scim" as the selected type despite the presence of SCIM 2.0 configurations.
3. Select the outbound type via the Service Provider and note the similar display issue.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta5-SNAPSHOT
 - OS: Mac
 - Database: H2, DB2
 - Userstore: JDBC

---
**Expected output:**
The UI should accurately display the selected SCIM version (either SCIM 2.0 or SCIM 1.1) during the configuration process in both "Custom Connector > Outbound Provisioning" and the Service Provider settings.
The Outbound provisioning - SCIM flow should work seamlessly with the New Console.

**Comment by dasuni-30** [comment]
Discussed providing a single template **only** for SCIM2 since SCIM1 is already deprecated in the identity server 6.1.0.
Doc: https://is.docs.wso2.com/en/latest/references/about-this-release/#deprecated-features

cc: @NipuniBhagya
