### ISSUE TITLE
[Remote Log Publishing] Getting 403 when trying to Restore Default Configuration.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18853]
**Describe the issue:**

When the admin user configures Remote log publishing and then tries to Restore Default Configuration it gives and 
<img width="1511" alt="Screenshot 2024-01-09 at 13 58 58" src="https://github.com/wso2/product-is/assets/41188245/b7cab940-40b5-414a-a217-9ad15b27d404">

**How to reproduce:**

1. Redirect to Server view 
2. Select Restore Default Configuration
3. configure audit logs or carbon logs 
4. then try to Restore Default Configuration

https://github.com/wso2/product-is/assets/41188245/0176879c-61fe-4f58-858a-4b6629f27a05

**Expected behavior:**
The user should be able to successfully Restore Default Configuration.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
In addition to those, the following endpoint URL should be updated.
https://localhost:9443/t/carbon.super/api/server/v1/configs/remote-logging/AUDIT to https://localhost:9443/t/carbon.super/api/server/v1/configs/remote-logging/audit
