### ISSUE TITLE
[Remote Log Publishing] UI issue in Audit Logs and Carbon logs forms.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18855]
**Describe the issue:**
Once the specific form field is clicked the value will be added to the other form as well.

https://github.com/wso2/product-is/assets/41188245/0edbc89d-b96f-4142-9766-a3c91ab4301e

**How to reproduce:**

1. Redirect to `Server`
2. Configure audit logs
3. navigate to the Carbon logs form and find the values visible in that form as well. 

**Expected behavior:**
only the changed form should have the values.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 beta5 snapshot (5011 Pack- 08th Jan )
 - OS: Mac
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
The `/remote-login` endpoint's response should consist of object with `AUDIT` log type. We are getting only `CARBON` log type object. cc - @bhagyasakalanka 

<img width="310" alt="Screenshot 2024-01-09 at 15 33 19" src="https://github.com/wso2/product-is/assets/67315176/f064231b-6462-4a30-a1ad-c8abae5897ad">

**Comment by brionmario** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/5183
