### ISSUE TITLE
Allows to save the Twitter IDP without the mandatory input field API key

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#1885]
**Environment**
Standalone 5.4.0 GA pack
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to recreate the issue**

1. Run Standalone IS 5.4.0 GA pack
2. Register Twitter as a IDP using Twitter configuration without giving a value to API key
3. Allows to save the IDP

**Observation**
Even though API key is a mandatory field allows to save the IDP. No error message is displayed.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
