### ISSUE TITLE
[Remote Log Publishing] Issue when both the Audit and Console logs are configured. 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18862]
**Describe the issue:**
when both the Audit and Console logs are enabled only the audit logs will be logged.
but when only one of the log types is enabled the specific log will be logged. 

Behavior When only Audit logs are configured.

<img width="1152" alt="Screenshot 2024-01-09 at 17 38 04" src="https://github.com/wso2/product-is/assets/41188245/653909fb-8115-49a1-890e-b7e68226382c">

Behavior When only Carbon logs are configured.

<img width="1152" alt="Screenshot 2024-01-09 at 17 52 57" src="https://github.com/wso2/product-is/assets/41188245/0c3a8d58-2bea-49c0-a2b5-6bcdd129b961">

Behavior When both log types are configured.
 
**Issue: Only the Audit logs will be logged.**

<img width="1152" alt="Screenshot 2024-01-09 at 17 55 39" src="https://github.com/wso2/product-is/assets/41188245/e1c75c78-f37e-414a-ad39-927b0603f7ff">

**How to reproduce:**

1. Configure Remote Log Publishing from `Server ` - > `Remote Log Publishing`
2. Configure one type at a time and analyze the logs.
3. Configure both the log types at the same time and analyze the logs 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
As discussed let's hide the carbon console logs configurations from the UI. So we can get rid from these behaviours.

@jeradrutnam @savindi7

**Comment by jeradrutnam** [comment]
Fixed in: https://github.com/wso2/identity-apps/pull/5200
