### ISSUE TITLE
[docs] Recommended Database Structure for IS-Clustering

### ISSUE THREAD

**Issue by CharinduThisara** [wso2/product-is#18865]
Location : https://is.docs.wso2.com/en/latest/deploy/set-up-separate-databases-for-clustering/

Hi, I'm currently trying to create separate databases for IS-Clustering in kubernetes. In the recommended database structure, it is mentioned that the **Shared database** in the default structure is divided into two separate databases called **SHARED_DB**  & **USERSTORE_DB**.  

Could you please clarify the role of **USERSTORE_DB**?  

And also, if I create a separate database for consent management(**CONSENT_MGT_DB**), how can I link that using the **deployment.toml**? 

Thank you!

![image](https://github.com/wso2/product-is/assets/114144341/03a80b0f-d8a8-419b-bacc-636db8f13489)

**Comment by himeshsiriwardana** [comment]
This info is now available: https://is.docs.wso2.com/en/latest/deploy/set-up-separate-databases-for-clustering/
