### ISSUE TITLE
SAML Artifact Binding Issue: 500 Server Error during Authentication

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18873]
**Describe the issue:**
Encountering a 500 Internal Server Error when attempting to use SAML artefact binding for authentication.
<img width="1365" alt="image" src="https://github.com/wso2/product-is/assets/39077751/3ddeea3c-3688-4829-8ae5-8f2d51ed3d2e">

**How to reproduce:**
Please go through the documented steps,
https://is.docs.wso2.com/en/latest/guides/login/use-artifact-binding/#try-artifact-binding

**Expected behavior:**
Application authentication should be successful and SAML Artifact should look like in
`Artifact: urn:oasis:names:tc:SAML:2.0:artifact:example123`
 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 beta5
 - OS: [e.g., Windows, Linux, Mac]
 - Database: Postgres
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by UdeshAthukorala** [comment]
This will be fixed with:
- https://github.com/wso2/samples-is/pull/426
- https://github.com/wso2/carbon-identity-framework/pull/5381
