### ISSUE TITLE
ClassNotFoundException happens when  deploying /api/identity/recovery/v0.9 web app 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-is#18880]
**Describe the issue:**
We're working on upgrading Identity components for API-M 4.3.0 release. After upgrading to latest versions, we have encountered **_ClassNotFoundException: org.wso2.carbon.identity.recovery.endpoint.SecurityQuestionApi_** issue during /api/identity/recovery/v0.9  webapp deployment when server startup.  When we check the beans.xml file[1], it seems to include the SecurityQuestionApi although it has been removed. Shouldn't it be removed from here ? 

[1] https://github.com/wso2-extensions/identity-governance/blob/v1.8.100/components/org.wso2.carbon.identity.recovery.endpoint/src/main/webapp/WEB-INF/beans.xml#L13

**How to reproduce:**

**Expected behavior:**

**Environment information**

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by HiranyaKavishani** [comment]
@asha15 Could you please have a look on this?

**Comment by asha15** [comment]
Closing the issue as it's fixed with https://github.com/wso2-extensions/identity-governance/pull/796
