### ISSUE TITLE
Explain the purpose of suggested DB tuneup parameters in Doc

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1888]
Explain the purpose of the Database performance tuneup parameter given in [1]. 

Why do we need to add this property (what sort of issues that we can recover by adding this config)?
Do we need to add this at deployment phase, or possible to add it then and there only when performance tests are carried out in servers?

For example: As a user, I encountered "Lock wait timeout exceeded; try restarting transaction" during my testing, I want to know whether this could be because of this suggested index, and apply the changes to my setup to fix the issue.
[1] https://docs.wso2.com/display/IS540/Performance+Tuning+Recommendations#PerformanceTuningRecommendations-Databaselevelsettings

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
