### ISSUE TITLE
Server occasionally crashes when accessing a newly created tenant through console

### ISSUE THREAD

**Issue by thiva-k** [wso2/product-is#18897]
**Describe the issue:**

The issue occurs when a new tenant is created through the IS Management Console, and attempting to log into the new tenant through the console leading to occasional server crashes.

**How to reproduce:**

1. Create a new tenant using the WSO2 Management Console.
2. Attempt to log into the newly created tenant through the console.

https://github.com/wso2/product-is/assets/114133267/99da5fa2-01b9-448b-8b4a-23a680be7e49

**Expected behavior:**

Successful creation of a new tenant through the WSO2 Management Console.
Consistent and stable login experience for the newly created tenant without server crashes.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

 - Product Version: IS 7.0 Beta 4
 - OS: Windows 11 
 - JDK: 17 (Intermittent, JDK 11 seems to be working fine)
 - Database: H2

**Related issues:**

This behavior is also observed when creating a new tenant through APIs, with an initial client ID mismatch error when accessing the console for the first time after creating a new tenant, which is resolved after restarting the server .

**Comment by AnuradhaSK** [comment]
Not reproducible in beta6-snapshot

https://github.com/wso2/product-is/assets/25483865/e5f92294-1dcd-4e13-ab04-414edc4fc5c2
