### ISSUE TITLE
Document the tune up instructions for JVM heap size

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1890]
The document [1] does not contain information on where to configure the "JVM heap size" configuration properties.

Please include the following

- Which file this should be applied
- At which location in the configuration file this tune up parameter should be included

Ex: 
In Linux
```
if [ -z "$JVM_MEM_OPTS" ]; then
   java_version=$("$JAVACMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')
   JVM_MEM_OPTS="-Xms256m -Xmx1024m"
   if [ "$java_version" \< "1.8" ]; then
      JVM_MEM_OPTS="$JVM_MEM_OPTS -XX:MaxPermSize=256m"
   fi
```

In Windows
```
set CMD_LINE_ARGS=-Xbootclasspath/a:%CARBON_XBOOTCLASSPATH% -Xms256m -Xmx1024m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="%CARBON_HOME%\repository\logs\heap-dump.hprof"  -Dcom.sun.management.jmxremote -classpath %CARBON_CLASSPATH% %JAVA_OPTS% 
```
[1] https://docs.wso2.com/display/IS540/Performance+Tuning+Recommendations#PerformanceTuningRecommendations-Databaselevelsettings

**Comment by ShirazAzad** [comment]
Fixed. Updated the doc [1] with file name and JVM heap size info according to the doc [2]
[1] https://docs.wso2.com/display/IS540/Performance+Tuning+Recommendations#PerformanceTuningRecommendations-Databaselevelsettings
[2] https://docs.google.com/document/d/1i_tGOn4J0jAaRmK28EWBi3j0OA7WtRwi9oL29UJc7-g/edit
