### ISSUE TITLE
Update copyright statement

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-is#18917]
**Describe the improvement**
Updated the IS doc sites to showcase the latest year.

**Comment by Mariangela** [comment]
This probably needs to be added to the "master" branch. Need to check the Markdown layout before adding the change.

**Comment by Mariangela** [comment]
## Note to Reviewer
@himeshsiriwardana, please check and merge these PRs. Also let me know how which file I should update to get the changes in the master branch.

## Assignee
@Mariangela

**Comment by ashensw** [comment]
> ## Note to Reviewer
> @himeshsiriwardana, please check and merge these PRs. Also let me know how which file I should update to get the changes in the master branch.
> 
> ## Assignee
> @Mariangela

Hi @Mariangela,

We have moved all the versions to the master branch with the IS 7 unification effort. So all the changes should be done in the master branch -> https://github.com/wso2/docs-is/tree/master/en/identity-server

**Comment by himeshsiriwardana** [comment]
We have made the necessary changes in the master branch to dynamically display the current year with https://github.com/wso2/product-is/issues/18917

**Comment by Mariangela** [comment]
Thanks for the update, @ashensw and @himeshsiriwardana! Sorry, I only saw your messages just now.
