### ISSUE TITLE
Prevent Automatic Addition of 443 Port in Account Recovery Callback URL in hosted IS environment

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#18911]
**Describe the issue:**
Encountering the following error during the specified steps in a hosted IS environment:

```
Configured callback URL does not match with the provided callback URL: https://is.wso2isdemo.com/o/3c585f99-7d69-4b1f-9a4b-7b10b99a7d19/myaccount in the request.
```

The root cause lies in the hosted IS, where the account recovery callback regex automatically includes the 443 port. This behavior, however, poses challenges, particularly for sub-organizations. Unlike in the super org, there is currently no UI provision for sub-organizations to modify this setting. Admins are forced to utilize APIs for adjustments, introducing inconvenience. The optimal solution is to prevent the automatic addition of the 443 port in the callback URL.

<img width="943" alt="image" src="https://github.com/wso2/product-is/assets/61885844/4f8e1d38-63c9-4b26-9cdd-b9b13c51ba2d">

**How to reproduce:**
- Login to console.
- Switch to a sub organization. 
- Create a user and invite the user to set their own password
- User receive email
- Upon receiving user click set password

**Expected behavior:**
Ensure that the 443 port is not automatically added to the account recovery callback URL.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by malithie** [comment]
In the new console from where above can be configured ?

**Comment by PasinduYeshan** [comment]
> In the new console from where above can be configured ?
I couldn't find an option to configure this in new console. @NipuniBhagya any idea on this? 
In the management console you can find this configuration under
```
Identity Providers -> Resident -> Account Management -> Account Recovery -> Recovery callback URL regex
```

**Comment by brionmario** [comment]
> > In the new console from where above can be configured ?
> > I couldn't find an option to configure this in new console. @NipuniBhagya any idea on this?
> > In the management console you can find this configuration under
> 
> ```
> Identity Providers -> Resident -> Account Management -> Account Recovery -> Recovery callback URL regex
> ```

This was available in the new Console but was later refactored to remove certain fields in the connector.
@NipuniBhagya will have more ideas on this.

**Comment by NipuniBhagya** [comment]
> In the new console from where above can be configured ?

It was decided to remove this field from the UI and give support to update the regex only from the API level [1] aligning with the improvement done with [2].

[1] - https://docs.google.com/spreadsheets/d/128CteZXJ2nlQb4mpS20iUgxuqTCSUligqpV3YxN8FJE/edit#gid=936785435&range=C94
[2] - https://github.com/wso2/product-is/issues/17999

**Comment by malithie** [comment]
1. We don't need to have the regex in the UI.
2. But default we should make sure following is working
3. In the user invite if app is specified (my understanding is we have a query param to set it), upon setting passwords user should be directed to the access url of that app
4. In the user invite if app is not specified as user set the password, user should redirect to myaccount (In tenant level it should be the tenant level my account, in sub org level it should be the myaccount url qualified for that org)
5. When admin portal for b2b admins is done, ideally (4 ) should change to the org qualified admin portal url in b2b scenarios
