### ISSUE TITLE
Missing validation on email OTP authenticator configuration under Federated Authenticators

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1893]
**Environment**
5.4.0

While configuring EmailOTP  according to [1]  user need to  add a federated identity provider. When adding IDP using  email OTP authenticator configuration under Federated Authenticators , use must  set at least one option(Email or Email API ), otherwise it is no use of enabling Email OTP  authenticator.  Therefor include validation.

![emailotpfed](https://user-images.githubusercontent.com/13656890/34245562-63860816-e650-11e7-8da8-ceb8512cf262.png)

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Multi-factor+Authentication+using+EmailOTP#ConfiguringMulti-factorAuthenticationusingEmailOTP-ConfiguringtheEmailOTPproviderStep2-ConfiguretheEmailOTPprovider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
