### ISSUE TITLE
Provide the capability to configure FIDO trusted origins from the UI

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#18938]
**Is your suggestion related to an experience ? Please describe.**
Currently, FIDO trusted origins can only be configured in server-level configs. This is fine if the config does not require much alteration. But if there are multiple additions or occasional changes, a UI configuration is required, otherwise deployment config changes are needed each time. Ex: With API based auth if passkeys are used then FIDO trusted origins need to be added with the used origins.

**Describe the improvement**
Provide the capability to add a FIDO trusted origin from the UI.

**Additional context**

**Comment by ImalshaG** [comment]
This capability is added through https://github.com/wso2/identity-apps/pull/6100 and https://github.com/wso2-extensions/identity-local-auth-fido/pull/135.
