### ISSUE TITLE
Myaccount redirection is failing after a successful password set by suborg user 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18933]
**Describe the issue:**

- Configure [output_adapter.email] in deployment toml
- Login to the Console and create a suborg
- Switch to the suborg
- Create a user inviting user to set the password
- Accept the invite by the user, set the password.
- The user will see myaccount link to redirect. Click on that. My account access will be failed with following error
<img width="1581" alt="Screenshot 2024-01-16 at 11 52 32" src="https://github.com/wso2/product-is/assets/25483865/40002ecf-aeac-496a-a622-70bcf50cb755">

The working API is this pattern
```
https://localhost:9443/t/carbon.super/o/286f1979-cb42-4f13-8e00-6092fb57f0c5/myaccount
```

https://github.com/wso2/product-is/assets/25483865/5c97a610-e072-49c2-ae06-210844caed32

Need to fix org qualified my account redirection in user invite flows, password reset flows etc in suborgs

**Comment by dewniMW** [comment]
can be fixed by allowing `o/<org id>` path for myaccount via OrgContextsToRewrite config
