### ISSUE TITLE
Give the capability to configure the service provider in email template used in "Invite user to set the password" flow and use that SP's access URL for redirection 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18939]
**Describe the issue:**

Honor the similar capability of https://github.com/wso2/product-is/issues/17999 for inviting users to set the password flow. 
At the moment always the user will be redirected to the specific tenant/organization's myaccount URL after setting the password. Redirecting to myaccount should be the default behavior.
but if some admin wants to redirect the user to thier own application at the end of the flow, the email template should have an option to include SP name and based on that resolve the access URL and show the redirection.

**Comment by UdeshAthukorala** [comment]
This will be fixed with: https://github.com/wso2/identity-apps/pull/5264

**Comment by UdeshAthukorala** [comment]
### Steps to verify the fix
- Change the 'user-invitation(askPassword)' email template's user invitation link by adding spparam (ex: &sp=saml2-web-app-pickup-dispatch) similar to given below.
  ```
  href="{{account.recovery.endpoint-url}}/confirmrecovery.do?confirmation={{confirmation-code}}&amp;userstoredomain={{userstore-domain}}&amp;username={{url:user-name}}&amp;tenantdomain={{tenant-domain}}&amp;type=invite&sp=saml2-web-app-pickup-dispatch"
  ```
- Invite to a user to the organization.
- Open the user the invitation mail and setup a password to the account and finally can see below UI.

   ![access_URL](https://github.com/wso2/identity-apps/assets/36252606/818f22e4-a22f-4399-8698-f90c37da9dbd)

- Click the `Application` URl and it should redirect to  the given service provider's access URL.
