### ISSUE TITLE
Direct login to second level suborg in Console is not working

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18944]
**Describe the issue:**

1. Login to super tenant using admin credentials
2. Create a new org
3. Switch to that org
4. Create another org inside it
5. Switch to the created org
6. Create a user in the second level sub org created in step 4
7. Assign that user to the Console's Administrator role
8. Copy the console access url for the second-level suborg
9. logout from the console by admin
10. Access the console by URL copied in step 8
11. Give the credentials of the user created in step 6
12. The console login flow will be broken at /o/commonauth endpoint with following error

<img width="1725" alt="Screenshot 2024-01-16 at 21 42 54" src="https://github.com/wso2/product-is/assets/25483865/06b39c7d-3bd4-4e15-bc70-ca4ed8f0eeeb">

expected endpoint if `http://<host>:<port>/t/<root org tenant domain>/commonauth` (NOTE `t/<root org tenant domain>` is not required for super tenant case)

https://github.com/wso2/product-is/assets/25483865/bdb16437-5130-4fd3-aac1-ce115235710b

**Comment by PasinduYeshan** [comment]
This issue is fixed with following PR. 
- https://github.com/wso2-extensions/identity-organization-management/pull/331
