### ISSUE TITLE
Switch back to higher level org from hierarchy doesn't properly work when org admins logged into console as the B2B administrative portal  

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18947]
**Describe the issue:**

1. Login into Console
2. Create an organization and switch to it
3. Create a user and assign the Administrator role of the console application 
4. Copy the console access URL from the sub org's console settings page
5. Access the console from the copied link and give the credentials of the user created in step 3
6. Now navigate to the organization's section and create another org
7. Switch to the created org
8. Then switch back to the logged-in org
9. It will be reset to the root org and get not permitted (403) error message for operations

https://github.com/wso2/product-is/assets/25483865/db7c2226-61e2-40a7-9e98-7f8942187159

**Comment by PasinduYeshan** [comment]
This issue is fixed with following PR
- https://github.com/wso2/identity-apps/pull/5257
