### ISSUE TITLE
[FE] `Validate token bindings` checkbox value is not reflected in checkbox

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#18943]
**Describe the Issue:**
The checkbox `Validate token bindings` is always checked, regardless of the value returned from the API.

**How To Reproduce:**
1. In the console, create a new standard-based application.
2. Go to the Protocol tab and enable sso-session binding for the access token.
3. Notice that the checkbox Validate token bindings is checked by default.
4. Uncheck this and click update.
5. Reload the page and observe that the checkbox is still checked.

Notice in the network trace that the updates are happening correctly and the correct value is returned. It is not reflected in the checkbox correctly.

https://github.com/wso2/product-is/assets/46979289/e91afaa2-0ce9-44e5-953e-fbb2ef7966c4

**Expected behavior:**
The checkbox should indicate the actual value.

**Comment by JayaShakthi97** [comment]
Issue was a regression introduced through: https://github.com/wso2/identity-apps/commit/e2ed10aaa3c1bc125cee4996a20e8ae21906bd9c#diff-7e55f319d275ebee15c91c34b2455b3ce53cee47cecb1befc266b18d83649f26R2183
- Fix: https://github.com/wso2/identity-apps/pull/5241

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta6-SNAPSHOT`

https://github.com/wso2/product-is/assets/37938529/9050b396-1918-44dc-913f-53822d786851
