### ISSUE TITLE
[UX] Issue with Cancel button at Add SSO for Service provider using url & using config file page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#1894]
Setup: Standalone
Pack : 5.4.0-update-1

Steps to recreate:
- Register SP
- Go to inbound authenticator -> SSO config
- Select "Metadata File Configuration" 
- Click on Cancel button => Not working
- Select "URL Configuration"
- Click on Cancel button => Not working
Expected : Cancel clickevent should directed back to SP page.
see attached.
![cancel](https://user-images.githubusercontent.com/15671620/34245931-5c78ca34-e652-11e7-888f-42b527851357.jpeg)
![cancel1](https://user-images.githubusercontent.com/15671620/34245932-5ff9f99e-e652-11e7-9de8-d19c2ef0f463.jpeg)

**Comment by deshankoswatte** [comment]
This is fixed by https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/261

![Peek 2019-10-31 12-25](https://user-images.githubusercontent.com/33062368/67926689-a61ff580-fbdc-11e9-9ca0-629f24ce012f.gif)

Please close the issue when the pr is merged
