### ISSUE TITLE
There should be a way to retrieve tenant by ID using admin services

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1895]
There should be a way to retrieve tenant by ID using admin services.

I cannot see a method. What happens is if we try to create a tenant with providing an existing ID, it will throw an error. So it would be better to have  a way to check if tenant id exists before creating one using admin services.

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode>soapenv:Server</faultcode>
         <faultstring>Error in adding tenant with domain: vihana1.com</faultstring>
         <detail>
            <ns:TenantMgtAdminServiceException xmlns:ns="http://services.mgt.tenant.carbon.wso2.org">
               <ns:TenantMgtAdminServiceException>
                  <axis2ns3:Message xmlns:axis2ns3="http://services.mgt.tenant.carbon.wso2.org">Error in adding tenant with domain: vihana1.com</axis2ns3:Message>
               </ns:TenantMgtAdminServiceException>
            </ns:TenantMgtAdminServiceException>
         </detail>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
