### ISSUE TITLE
Authentication failure when continuing authentication after clicking on `Choose a different Option` in Magic link

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#18951]
While fixing https://github.com/wso2/product-is/issues/18655, I was able to find this issue

**How to reproduce:**
1. Create an application
2. Add following Local Authenticators as 1st step (EMAIL OTP, BASIC AUTH, Magic Link)
3. Go to the login page of the application
4. Try to login with EMAIL OTP
5. Click on `Choose a different option` link.
6. Try the Magic link

### Configuration

<img width="1422" alt="Screenshot 2024-01-17 at 09 30 53" src="https://github.com/wso2/product-is/assets/25488962/c6884a8d-b073-4242-b5e3-77ded8405439">

### Flow

https://github.com/wso2/product-is/assets/25488962/cf5b9a64-b7d7-4570-9a12-b258324e2545

### Expected Outcome

Magic Link should work as expected

**Comment by ZiyamSanthosh** [comment]
**Analysis**

Redirecting users to the IDF page in local authenticators such as emailOTP and smsOTP depends on the existence of the username in the request object [1] whereas, magic link authenticator depends on the value of IS_IDF_INITIATED_FROM_AUTHENTICATOR constant [2]. The value of this constant will be made true when other local authenticators were chosen before selecting magicLink as the authenticator. When we click on `choose different option` button and come back to the options page, still the value of the constant remains the same. Hence, magicLink authenticator will not prompt for username and fails to identify the username from the request object.

**Solution**

An additional validation can be done to verify whether the username is available in the request object and if not, the IDP page will be prompted to enter the username.

[1] https://github.com/wso2-extensions/identity-auth-otp-commons/blob/dbbdcece3a7774f09065ef8a801d714b3ed550e7/components/org.wso2.carbon.identity.auth.otp.core/src/main/java/org/wso2/carbon/identity/auth/otp/core/AbstractOTPAuthenticator.java#L183
[2] https://github.com/wso2-extensions/identity-local-auth-magiclink/blob/4e8ae6f4b0dc9820d9a4511a93252abb37397a61/components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java#L117

**Comment by ZiyamSanthosh** [comment]
This is completed. Hence, closing the issue.
