### ISSUE TITLE
Email template updating does not function as expected

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#18957]
**Describe the issue:**
When attempting to update the content of email templates, including the subject, body, and footer, the update payload is not being generated correctly based on the provided inputs. The body section is updating intermittently, but the subject field remains unchanged in every update call. However, the changes to the footer input are being applied correctly. Please refer to the attached request image for details.
<img width="1512" alt="image" src="https://github.com/wso2/product-is/assets/74205483/7c8eb9fd-9cf8-402f-b507-17954f793232">

**How to reproduce:**
- Navigate to the `Email Templates` item in the `Branding` section.
- Access the content tab and make edits to the subject, body, and footer fields.
- Click the `Save` button.

**Expected behavior:**
Email templates should be correctly updated according to the input changes.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by pavinduLakshan** [comment]
**Verified in the latest build**

https://github.com/wso2/product-is/assets/41533942/e084979b-7a48-452e-bb45-08eb2d5b38db
