### ISSUE TITLE
Add SAML2 Web SSO configuration Documentation.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18961]
**Is your suggestion related to a missing or misleading document? Please describe.**

Include  SAML2 Web SSO configuration documentation in IS 7.0.0 Docs.
[https://is.docs.wso2.com/en/6.0.0/guides/access-delegation/saml2-bearer-assertion-profile/#saml2-web-sso-configuration](https://is.docs.wso2.com/en/6.0.0/guides/access-delegation/saml2-bearer-assertion-profile/#saml2-web-sso-configuration
)

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by ashensw** [comment]
Relevant docs are added.

https://is.docs.wso2.com/en/next/guides/applications/register-saml-web-app/
https://is.docs.wso2.com/en/next/references/grant-types/#saml-20-bearer-grant
