### ISSUE TITLE
The user creation window should not be displayed if the user store is read-only

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18960]
Even if the user store is read-only, the user creation dialog is displayed.  When trying to add a user it says the username is invalid.
<img width="910" alt="image" src="https://github.com/wso2/product-is/assets/12690906/57dbb5b1-b8b7-4ea3-b30b-6dc7ce2959ca">

Expectation :
If the user store is read-only the user creation window should not be displayed.

**Comment by DMHP** [comment]
The following error is displayed when trying to add a group for a read-only user store.
<img width="626" alt="image" src="https://github.com/wso2/product-is/assets/12690906/054e576b-702f-41a4-bee1-a0980cf4db85">

Adding group values for read-only user stores should be restricted too.

**Comment by JayaShakthi97** [comment]
Hi @DMHP,

The 1st issue is not reproducible as the read-only userstores are not listed in the Add User wizard.
2nd issue is reproducible. The solution will be not listing read-only userstores in the Add Group wizard.

**Comment by JayaShakthi97** [comment]
Read-only userstores removed in the Group creation wizard.
- https://github.com/wso2/identity-apps/pull/5285

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta6-SNAPSHOT`

Read only userstores are not listed in group creation wizard.

![image](https://github.com/wso2/product-is/assets/37938529/0e0699f1-aa42-47e5-9063-8e95e4c18157)

![image](https://github.com/wso2/product-is/assets/37938529/13ec509b-b5bc-485e-89fb-d05ccf4717c7)
