### ISSUE TITLE
[Improvement] Validate Advanced authentication configuration

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1896]
Currently, we allow the users to configure the advanced authentication configuration under Local & Outbound  Authentication configuration section. The issue is if a user mistakenly configures a sequence incorrectly (authentication order) IS will save it successfully. It would be better if we can validate it

E.g - Setting the order as password-reset-enforcer been set first and then followed by the basic authenticator. It would be good if we can validate this.

![authenticatorflow](https://user-images.githubusercontent.com/17248809/34251795-364fb650-e667-11e7-9890-cf727b5d8ade.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
