### ISSUE TITLE
[Doc] Enhance Documentation for Inviting Users to Set Password During User Creation

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18978]
**Describe the issue:**
The current documentation titled "Invite user to set password" lacks detailed information on the full path of inviting a user to set a password during the user creation process. The documentation mentions prerequisites but does not provide step-by-step instructions on how to complete the flow.

Doc: https://is.docs.wso2.com/en/next/guides/account-configurations/user-onboarding/invite-user-to-set-password/

2:In the current documentation titled "Invite user to set password," there is a misalignment between the content of the "Parameters" table and the provided screenshot. 
Related to : IS 7.0 Onprem

**Comment by ashensw** [comment]
The detailed information on the full path of inviting a user to set a password during the user creation process is available at the manage users doc. Please refer https://is.docs.wso2.com/en/next/guides/users/manage-users/#onboard-users
