### ISSUE TITLE
Some UI fields does not have proper validations like max length and special characters

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18977]
Some fields do not have a maximum length and special characters are not handled.
<img width="709" alt="image" src="https://github.com/wso2/product-is/assets/12690906/00744a19-2246-4418-87fb-507d6cec4226">

If we add a lengthy value or special characters the request fails from the BE or the db level.

**Comment by savindi7** [comment]
stacktrace printed in logs

<img width="1013" alt="Screenshot 2024-01-22 at 15 36 07" src="https://github.com/wso2/product-is/assets/67315176/2e585277-4493-40f7-b009-86aaa7e2c959">
