### ISSUE TITLE
Add Documentation for Configuring Twitter as a Federated Authenticator.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#18974]
**Is your suggestion related to a missing or misleading document? Please describe.**

Add missing docs on Configure Twitter as a Federated Authenticator.
[https://is.docs.wso2.com/en/6.0.0/guides/identity-federation/twitter/#register-an-identity-provider](https://is.docs.wso2.com/en/6.0.0/guides/identity-federation/twitter/#register-an-identity-provider)

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by melanisilva** [comment]
The below issue should be fixed when adding the new documentation. 
[https://github.com/wso2/product-is/issues/16698](https://github.com/wso2/product-is/issues/16698)

**Comment by himeshsiriwardana** [comment]
This is fixed in: https://github.com/wso2/docs-is/pull/4372
