### ISSUE TITLE
Unable to Update "Email Verification Code Expiry Time" and "Password Setup Invitation Code Expiration Time" via UI

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18973]
**Describe the issue:**
When attempting to update the "Email Verification Code Expiry Time" and "Password Setup Invitation Code Expiration Time" via the UI, users are encountering an error message and receiving a 400 status code. 

**Additional Information**
Endpoint: /api/server/v1/identity-governance/VXNlciBPbmJvYXJkaW5n/connectors/dXNlci1lbWFpbC12ZXJpZmljYXRpb24
HTTP Status Code: 400

**How to reproduce:**
Navigate to the UI section for updating "Email Verification Code Expiry Time" and "Password Setup Invitation Code Expiration Time." ( login & registration > Invite User to Set Password)
Attempt to modify the values.
Observe the error message and the received HTTP status code 400.

**Expected behavior:**
Users will be able to seamlessly update the "Email Verification Code Expiry Time" and "Password Setup Invitation Code Expiration Time." as we mentioned in the description 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

---

[issueUI.webm](https://github.com/wso2/product-is/assets/39120228/a8ad3e9e-a835-49df-9b65-16f94c56c863)

**Comment by ZiyamSanthosh** [comment]
**Analysis**

When the patch call is done because of changing either "Email Verification Code Expiry Time" or "Password Setup Invitation Code Expiration Time", the request body constructed for the API call is wrong. Currently, the request body is constructed as [1] and the correct body should be like [2]. With this change, this issue will get fixed.

[1]
```
{
    "name": "EmailVerification",
    "value": {
        "ExpiryTime": "1441"
    }
}
``` 

[2]
```
{
    "name": "EmailVerification.ExpiryTime",
    "value": "1441"
}
```
