### ISSUE TITLE
Provisioning fails when the initially provisioned user is deleted.

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#18976]
Steps to reproduce
- Create a SP application
- Create a Google connection and enable JIT provisioning.
- Try the first attempt and when the Gmail user is provisioned, delete that provisioned user.
- Then try again to log in to the same application with Google.

Expected behaviour
- The user needs to be provisioned again.
- But the following error can be seen and the user is not provisioning again.
`[2024-01-17 17:33:53,471] [554f7f45-4563-410e-a7b1-c217c2bbf6a0] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.JITProvisioningPostAuthenticationHandler} - 80018 - Provided username already exists.`

It seems like when deleting some tables are not clearing properly.

**Comment by ZiyamSanthosh** [comment]
This issue is not reproducible in the latest pack taken on 18th Jan. Hence, closing this issue.

https://github.com/wso2/product-is/assets/50801227/91bb32ba-502f-43e1-b8e7-3b978e8169da
