### ISSUE TITLE
Account disable: Switch off account disabling

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1897]
In [1] it states that the given config is only valid for super tenant. Please mention the particular config applicability to other user stores 

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
