### ISSUE TITLE
Provide Direct Link to Enable "Enable User Email Verification" during User Creation

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18971]
**Describe the issue:**
Currently, during the user creation process,when user try to invite user to set password via email,  users are prompted to "Enable User Email Verification," if it is not enabled,
 but it would be easier to enhance the user experience by providing a direct link to enable this feature.

**How to reproduce:**

**Expected behavior:**
Users invited to set their password via email will have a direct path to enable email verification, creating a more straightforward onboarding experience.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: MSSQL, H2
 - Userstore: JDBC

---

<img width="812" alt="Screenshot 2024-01-17 at 15 04 33" src="https://github.com/wso2/product-is/assets/39120228/99daf9e7-a71c-4af5-9288-c6643b764c9d">

**Comment by JayaShakthi97** [comment]
- Addressed with https://github.com/wso2/product-is/issues/18232
