### ISSUE TITLE
Adding subattributes of a scim complex attribute through new console UI is failing and it doesn't have proper UX 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#18984]
**Describe the issue:**
If you want to configure a custom complex scim attribute the steps to follow are
https://is.docs.wso2.com/en/latest/references/extend/provisioning/add-scim2-custom-user-schema-support/#how-to-add-claims-to-support-complex-attributes

When creating a subattribute through the UI it fails to configure the scim attribute because UI doesn't allow the input `.`

<img width="745" alt="Screenshot 2024-01-17 at 21 45 52" src="https://github.com/wso2/product-is/assets/25483865/290e5e54-0665-4663-a810-ccbcf63b29af">

The current UI is handling only the simple attributes.

Further, if the user wants to create a complex attribute there should be a way to mark it as dataType = complex, and allow to configure the subattribute during the attribute creation

**Comment by DilshanSenarath** [comment]
As a quick fix, I've made changes to allow the use of the `.` character and corrected the user profile to display the data correctly. However, there's a UX issue as mentioned in this issue when creating a complex attribute and assigning sub-attributes. To address this, I've created a separate issue (https://github.com/wso2/product-is/issues/19020) to keep track of and improve the UX.
