### ISSUE TITLE
[Stress] 500 error response at travelocity login authentication at a higher load

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1898]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
OS - Ubuntu-14.04-LTS
Browser Chrome 58.0.3029.96

**Steps to reproduce the issue**
1. Create Facebook and Google as IDP
2. Create SP and connect FB, Google and Resident IDP and IDPs
3. Configure Travelocity with the fidp query param corresponding with the resident IDP (ex: in default pack this is localhost)
4. Go to Travelocity application and login with basic auth. (Simulate the login with resident IDP using jmeter single request) - Request rate 150 users -> 10 loops (4 http requests overall)

Jmeter Script -
[AuthenticationVerification.jmx.zip](https://github.com/wso2/product-is/files/1578879/AuthenticationVerification.jmx.zip)

**Observations**
Around 14% of the authentication requests failed. No errors observed at IS servers.

Sample Result
--------------------
```
Thread Name: Scenario 28 - Stress 1-54
Sample Start: 2017-12-21 15:54:29 IST
Load time: 1637
Connect Time: 1480
Latency: 1637
Size in bytes: 355
Sent bytes:527
Headers size in bytes: 162
Body size in bytes: 193
Sample Count: 1
Error Count: 1
Data type ("text"|"bin"|""): text
Response code: 500
Response message: Internal Server Error

Response headers:
HTTP/1.1 500 Internal Server Error
Server: nginx/1.7.11
Date: Thu, 21 Dec 2017 10:24:30 GMT
Content-Type: text/html
Content-Length: 193
Connection: close


HTTPSampleResult fields:
ContentType: text/html
DataEncoding: null

```

Request
------------
```
POST https://is540-load-test.wso2.com/samlsso

POST data:
sessionDataKey=721ec7fd-693d-4f0d-9d10-70949c851cd3&password=admin&tocommonauth=true&username=admin

[no cookies]

Request Headers:
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Content-Type: application/x-www-form-urlencoded
Content-Length: 99
Host: is540-load-test.wso2.com
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_66)
Authorization: Basic YWRtaW46YWRtaW4=

```

Response Data
---------------------
```
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.7.11</center>
</body>
</html>
```
![screenshot from 2017-12-21 16-43-28](https://user-images.githubusercontent.com/14962228/34253549-1b9a1d6c-e66e-11e7-98bc-c9d01a18e586.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
