### ISSUE TITLE
Account disable: Provide some steps in trying out functionality when account is disabled

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1899]
Currently in [1] there are no steps indicating verifying the steps for account disabling. Please include the steps that verifies the account being disabled

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by ShirazAzad** [comment]
Added a "Try it out" section in doc [1]
[1] https://docs.wso2.com/display/IS540/Account+Disabling
