### ISSUE TITLE
Missing Guide for "Writing a Custom Local Authenticator" in IS 7.0

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18998]
**Is your suggestion related to a missing or misleading document? Please describe.**
The documentation for IS version 7.0 lacks a guide or detailed documentation on how to write a custom local authenticator.

Previous docs: https://is.docs.wso2.com/en/latest/references/extend/federation/write-a-custom-local-authenticator/

**Comment by ZiyamSanthosh** [comment]
The configuration menthion in comment [1] has to be added to the documentation when this page is constructed.

[1] https://github.com/wso2/product-is/issues/19001#issuecomment-1900083668
