### ISSUE TITLE
Provide the option to upload the .p12 file for the private key in Google outbound provisioning connector.

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#18993]
**Describe the issue:**
In the current implementation we have provided an input field to enter the private key of the Google outbound provisioning connector. But ideally we should provide the option to upload the .p12 file as we suggest that format in our documentation.

<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/30111554/c7e55228-4228-42aa-8fc2-43c70b9e7c70">

**Comment by dasuni-30** [comment]
Currently, our file picker doesn't have a file strategy to upload a .p12 file. Also, the serialize method in the default file strategy is not working as expected. Hence we need to write a file strategy to serialize the .p12 files.

**Comment by dasuni-30** [comment]
**Status**

Implemented the file upload for the .p12 file. File upload gives a BE error when we upload the file from the FE.  (There's a pending dependant BE fix for that.) 

<img width="1440" alt="Screenshot 2024-01-22 at 20 10 15" src="https://github.com/wso2/product-is/assets/27746285/68779bb5-c7fd-4baf-b8a0-af6929aecf25">


Additionally, we need to improve the FE component to display and delete the uploaded file.

**Comment by dasuni-30** [comment]
**Status 24/01/2024**

Successfully implemented the file upload strategy for the .p12 file. Currently working on writing a new component to display and delete options of the FE component. (Faced a couple of issues due to the old deprecated forms module used)

**Comment by dasuni-30** [comment]
**Verified in the latest pack**

<img width="713" alt="Screenshot 2024-02-09 at 10 31 55" src="https://github.com/wso2/product-is/assets/27746285/d320e0ee-b203-43b4-a6f3-ac9ad0c98518">
