### ISSUE TITLE
Account disable: Provide an image with the user profile configuration

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1900]
In [1] when disabling an account through the profile, there is no image that illustrates the config. Please provide one to make the document more comprehensive

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by ShirazAzad** [comment]
Added image for user profile configuration in doc [1]
[1] https://docs.wso2.com/display/IS540/Account+Disabling
