### ISSUE TITLE
Alias configuration is available in two places in the connection config

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19008]
**Describe the issue:**
Alias configuration is available in two places in a connection. In the "General" tab and in the "Advanced" tab. 

**How to reproduce:**
<img width="1115" alt="Screenshot 2024-01-19 at 10 11 44" src="https://github.com/wso2/product-is/assets/11583571/5a1fbd02-45ee-42e8-9a5a-079bb5e5ac5e">

<img width="1180" alt="Screenshot 2024-01-19 at 10 23 09" src="https://github.com/wso2/product-is/assets/11583571/ebd46c30-2f4e-4ae0-a408-6fe44e06f2b8">

**Expected behavior:**
Have this only in the General tab.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7-beta-6-snapshot

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
`Alias` was available in the advance tab of IdPs. And `Alias` was recently added to the `General` tab as well to make it available for IdPs like `Trusted Token Issuer` that didn't have an Advance tab.

Fixed in: https://github.com/wso2/identity-apps/pull/5281
