### ISSUE TITLE
Loophole to create Apple connection in localhost

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19018]
**Describe the issue:**
When the IS is running in localhost the connection page has disabled Apple connection creation. But we can still create a connection through to the Sign in options tab of an application.

<img width="578" alt="Screenshot 2024-01-19 at 15 25 42" src="https://github.com/wso2/product-is/assets/11583571/6a219278-5e10-490b-82c1-89c608a22b29">

https://github.com/wso2/product-is/assets/11583571/e5332a71-4d73-42ee-b682-5746b03f2b0c

**Expected behavior:**
No need to block the Apple connection creation on the connection page as the connection not working in localhost is not due to a behaviour in our system. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7-beta-6-snapshot

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by JayaShakthi97** [comment]
Disabled Apple connection in other places as well.
- https://github.com/wso2/identity-apps/pull/5301

**Comment by JayaShakthi97** [comment]
Moving back to in-progress as there is Apple option in visual editor as well.

![image](https://github.com/wso2/product-is/assets/37938529/ca67c7a4-1d33-4f21-aa6e-f6fff84e6664)

**Comment by JayaShakthi97** [comment]
Fix is completed with:
- https://github.com/wso2/identity-apps/pull/5316
