### ISSUE TITLE
Account disable: mention about the email templates and email sending mechanism 

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1901]
In [1] there is no indication of the used email templates. Please include the relevant information as we have default templates for account disabling and enabling

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by ShirazAzad** [comment]
Fixed due to restructuring in doc [1]
[1] https://docs.wso2.com/display/IS540/Account+Disabling
