### ISSUE TITLE
Optional userstore "Display Name" marked as mandatory

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19010]
**Describe the issue:**
When creating a user store under "User" config there is a mandatory attribute names Display Name. When checking the carbon management console this is an optional attribute. Furthermore having this as a mandatory attribute hinders the UX as its not intuitive what this attribute is for. The old carbon console has the following info against the attribute 
"This is the attribute name to display as the display name of the user"

<img width="860" alt="Screenshot 2024-01-19 at 10 56 36" src="https://github.com/wso2/product-is/assets/11583571/647e6571-22f9-42f8-a5e3-be8f39c1e782">

**Expected behavior:**
Display name should not be mandatory

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS7-beta-6-snapshot

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
`DisplayNameAttribute` *required* property is coming as `true`

<img width="915" alt="Screenshot 2024-01-20 at 14 20 08" src="https://github.com/wso2/product-is/assets/25959096/591ffab1-c1a5-40e6-8ba1-82f69c832d56">

**Comment by brionmario** [comment]
The mandatory check was removed with: https://github.com/wso2/identity-apps/pull/5282

**Comment by brionmario** [comment]
Additionally, the placeholders of these fields are dynamically generated and doesn't make much sense.

Ex: `Display Name` here is meant for the attribute used for the displayname property of a user in the userstore. But that's not intuitive in the UI.

We need to revamp the placeholders and possibly add hints:

Tracker: @brionmario Create an issue

**Comment by NipuniBhagya** [comment]
Since we dynamically populate this UI based on the API response, shouldn't this be fixed from the BE as well?
