### ISSUE TITLE
Confusing UX in user creation wizard

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19014]
**Describe the issue:**
The user creation wizard contains 3 steps; Basic Details, User Groups, Summary. At the "User Groups" step when you click "next" it actually creates the user and then only goes to a Summary. This UX is very confusing as the general expectation is that the summary page would show a summary of the entered configuration and upon continuing from the summary the user will be created. There is no indication that the user will be created when clicking "Next" from the "User Groups" page. This suprise user creation becomes even worse as there can be coupled actions that cannot be rolled back such as an invite mail being sent to users.

This UX is also inconsistent with some of the other places. Ex: When you create a user store in that wizard the desired UX is there. The summary page shows the summary of the entered configuration and upon continuing the user is created. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS7-beta-6-snapshot

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
I think the issue here is that we cannot create the user invitation without creating the user. So I would suggest we can simply fix the UX here by changing the title of the step from `Summary` --> `Invitation`

**Comment by janakamarasena** [comment]
> I think the issue here is that we cannot create the user invitation without creating the user. So I would suggest we can simply fix the UX here by changing the title of the step from `Summary` --> `Invitation`

+1. This makes things much better. And also we can change the "Next" button name to something more appropriate.

**Comment by NipuniBhagya** [comment]
> > I think the issue here is that we cannot create the user invitation without creating the user. So I would suggest we can simply fix the UX here by changing the title of the step from `Summary` --> `Invitation`
> 
> +1. This makes things much better. And also we can change the "Next" button name to something more appropriate.

I would suggest that we can go with "Save & Continue".
