### ISSUE TITLE
Email OTP won't receive after providing wrong TOTP and come back

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#19025]
**Describe the issue:**
Email OTP won't receive after providing the wrong TOTP and coming back to the multi-option page.

**How to reproduce:**

1. Login to the Console
2. Configure a login sequence for an application with Username and Password, Email OTP and TOTP as second factor options
3. Try to login to the application and select the TOTP as the desired option.
4. Provide wrong TOTP and come back to the multi-option page
5. Try email otp option now
6. You won't get the email otp

**Expected behavior:**
Even after failure attempt from another authenticator, still needs to get the email otp.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

---

**Comment by ZiyamSanthosh** [comment]
Closing since this is completed.
