### ISSUE TITLE
Home Realm identifier should be validated against the letter case

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1902]
**Environment**
IS 2 node cluster setup fronted by Nginx
Mysql 5.6
JDK 1.8
OS - Ubuntu-14.04-LTS
Browser Chrome 58.0.3029.96

**Steps to reproduce the issue**

1. Create Facebook and Google as IDP 
Define following Home Realm Identifiers;
_Facebook HRI - Facebook
Google HRI - FACEBOOK_
2. Create SP and connect FB and Google as IDPs
3. Configure Travelocity with the fidp query param as "facebook" 
_ex: QueryParams=fidp=facebook_
4. Log in to travelocity App

**Observations**
Log in will redirect to authenticate with the last modified IDP (ex: If you change the Google HRI as the latest modification, Google authentication page will appear, vice versa)

**Expected Result**
Since the query param (fidp) doesn't consider the case sensitivity of the Home Realm identifier, validation should be included to verify an identifier provided with different letter cases. (It should not be possible to provide 'FACEBOOK' as identifier when there is an existing IDP with identifier name as 'facebook' )

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
