### ISSUE TITLE
Getting "Something Went Wrong" error when resetting the user password from the Console

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#19034]
**Describe the issue:**
Privileged users / admins can reset the passwords of the users by using the reset password option in the Console application. When doing that the admins get the "Something Went Wrong" error message. When checking the API response, it is showing the proper error message as follows.

```
{
   "schemas":[
      "urn:ietf:params:scim:api:messages:2.0:Error"
   ],
   "scimType":"invalidValue",
   "detail":"The password should contain at least 1 upper case characters.",
   "status":"400"
}
```

Can see the same error log printed in the backend terminal as well.

```
[2024-01-20 15:26:49,680] [fc65d789-f851-4ddd-81ad-b58575dcbc1c] ERROR {org.wso2.carbon.identity.input.validation.mgt.listener.InputValidationListener} - Failed to validate password for user. The password should contain at least 1 upper case characters.
```

**How to reproduce:**
1. Create a user from the console.
2. Open the user profile and click on the Reset Password button.
3. Add a password that does not contain an upper case letter.
4. Click on the Reset Password button the you will see the "Something Went Wrong" error.

**Expected behavior:**
Option 01 : Can validate the rules in front end.
Oprion 02 : Can show the proper error message.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by DMHP** [comment]
@ShanChathusanda93 In the UI there is a validation to restrict adding a password without uppercase letter. "add a password that does not contain an upper case letter"
<img width="472" alt="image" src="https://github.com/wso2/product-is/assets/12690906/bb546ffa-f99e-4eb0-b7b4-d576fbb7a40f">

So as you mentioned in the reproducing steps we can not add password without an uppercase. Can you explain the way you added the user? Is it by using the API or Self-registration?

**Comment by ShanChathusanda93** [comment]
@DMHP Here the issue is not in the user creating flow. Issue is there in the password resetting flow of a user from the Console. In the user creating form we have the validation as below.
<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/19262008/8e4d12a0-1315-41af-9503-cda573f1e764">

But in the password reset form we don't have such a validation in the front end level.
<img width="1728" alt="image" src="https://github.com/wso2/product-is/assets/19262008/9c384fb9-e0d0-4fbe-b48f-f406ad37a177">

**Comment by DMHP** [comment]
Ack. We need to fix this. @NipuniBhagya @brionmario we need to add a FE validation
