### ISSUE TITLE
Remove unused js in dashboard app

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#1904]
Following js not being used in the runtime. Remove packing those in the product.

- https://github.com/wso2/product-is/blob/v5.4.0/modules/jaggery-apps/portal/themes/portal/js/shindig%20(copy).js
- https://github.com/wso2/product-is/blob/v5.4.0/modules/jaggery-apps/portal/themes/portal/js/elfinder.full.js
- https://github.com/wso2/product-is/blob/v5.4.0/modules/jaggery-apps/portal/themes/portal/js/elfinder.js
- https://github.com/wso2/product-is/blob/v5.4.0/modules/jaggery-apps/portal/themes/portal/js/elfinder.min.js

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
