### ISSUE TITLE
hyprlogin.jsp available in the identity-outbound-auth-hypr connector not updated

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#19041]
**Describe the issue:**
The hyprlogin.jsp is available in both the identity-apps[1] and  identity-outbound-auth-hypr[2] connector.

According to the documentation[3], when configuring the hypr login with the Identity Server, the user is supposed to get the hyprlogin.jsp file from the dentity-outbound-auth-hypr[2] connector and paste it into the authentication endpoint.

However, the hyprlogin.jsp file in the dentity-outbound-auth-hypr connector has not been updated for 2 years. The jsp in the identity-apps has been updated and contains different functionality to the jsp in the connector.

Had a discussion with @brionmario regarding this and it seems like the hyprlogin.jsp should not exist in the identity-apps repo and is currently present due to the unification.

Therefore, need to look into:

1. Removing the hyprlogin.jsp from the identity-apps repo and move to the connector side.
2. Analyzing the differences between the two jsps and unifying them. At a glance it seems like updates done in the identity-apps have been brought to the jsp in the connector, but requires further analysis.

### **It is critical to update the hyprlogin.jsp in the connector repo as customers who use the documentation to set up hypr will be obtaining the file from the connector**

[1] https://github.com/wso2/identity-apps/blob/master/identity-apps-core/apps/authentication-portal/src/main/webapp/hyprlogin.jsp
[2] https://github.com/wso2-extensions/identity-outbound-auth-hypr/blob/main/components/org.wso2.carbon.identity.application.authenticator.hypr/src/main/resources/artifacts/hyprlogin.jsp
[3] https://is.docs.wso2.com/en/next/guides/authentication/passwordless-login/add-passwordless-login-with-hypr/#deploy-the-hypr-login-page

**Comment by Thumimku** [comment]
Based on my initial look,
 There are some features added to hypr jsp file in identity apps such as 

- branding preference
- UX improvement
- Improvement in error handling
- Improvement i18n
- Using auth header when checking the status

We can migrate these changes to connector but we have to test it.

**But there is another improvement where the user name is validated against [Email regex format](https://github.com/wso2/identity-apps/blob/dfabac54f6c304d2c163da5d98e7efd4c348ea00/identity-apps-core/apps/authentication-portal/src/main/webapp/hyprlogin.jsp#L191),** which means email type Username as inly allowed and we can't migrate this behaviour to connector.

Hence coping entire jsp in identity apps to connector is not possible we have to check case by case.

**Comment by Lakshan-Banneheke** [comment]
Adding to what @Thumimku mentioned, I don't think we can directly remove the jsp from identity-apps as well after migrating the changes to the hypr connector. We'll have to introduce it as an extension in asgardeo-apps

**Comment by Thumimku** [comment]
This [PR](https://github.com/wso2-extensions/identity-outbound-auth-hypr/pull/16) will add latest changes to connector JSP file.

**Comment by Thumimku** [comment]
New connector publication requested via mail: :"Request to Host a New Version of HYPR Authenticator"

**Comment by Thumimku** [comment]
TODO: Update docs after publishing new connector
