### ISSUE TITLE
Roles tab is not visible in sub-organization console view

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#19058]
**Describe the issue:**

Cannot assign a role to the suborganization user because the Roles tab is not visible in the suborganization console view.

<img width="1512" alt="Screenshot 2024-01-22 at 11 10 24" src="https://github.com/wso2/product-is/assets/28347418/269dca9f-4086-4c4a-b3b7-94c9d0fa4d9b">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by malithie** [comment]
Folks this is a blocker. Updated the issue status
