### ISSUE TITLE
[UserInfo Endpoint] The claims are not returning from the userinfo endpoint in the password grant type similar to the ID token

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#19054]
**Describe the issue:**
According to IS Documentation, the userinfo endpoint should be returning the claims that are available from the scoped access token. 

But from the userinfo endpoint the details are not returning, checked for the password grant flow
1. Create a token with password grant flow and scope=openid, other custom scopes
2. Call the userinfo endpoint with the access token and verify whether the claims are displayed. 

**Expected behavior:**
Userinfo endpoint should return the claims 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] IS beta 6
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ZiyamSanthosh** [comment]
**Analysis**

When fetching the userClaims of the user belongs to the token, the subject claim URI value is being resolved as an empty string. Hence, it is being added to the claimsList and while fetching the claim values, the error [1] is being thrown. 

The root cause of the issue is that, when updating the application with custom scopes, the subject claim URI is being sent as an empty string in the request body [2] of the PATCH API call. This is not expected and this is causing the issue mentioned above whereas the subject claim URI should contain a value instead of an empty string.

[1]
```
aused by: java.lang.IllegalArgumentException: Local claim URI parameter cannot be empty
	at org.wso2.carbon.identity.claim.metadata.mgt.DefaultClaimMetadataStore.getAttributeName(DefaultClaimMetadataStore.java:125)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getClaimAtrribute(AbstractUserStoreManager.java:3950)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserClaimValuesWithID(AbstractUserStoreManager.java:12312)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValuesWithID(AbstractUserStoreManager.java:12181)
	... 80 more

```

[2]
```
{
  "claimConfiguration": {
    "dialect": "LOCAL",
    "requestedClaims": [
      {
        "claim": {
          "uri": "http://wso2.org/claims/username"
        },
        "mandatory": false
      }
    ],
    "role": {
      "claim": {
        "uri": ""
      },
      "includeUserDomain": false
    },
    "subject": {
      "claim": {
        "uri": ""
      },
      "includeTenantDomain": false,
      "includeUserDomain": false,
      "useMappedLocalSubject": false
    }
  }
}
```

**Comment by pavinduLakshan** [comment]
Frontend will be updated to avoid sending empty, null, or undefined values for subject attribute with https://github.com/wso2/identity-apps/pull/5303.

@ZiyamSanthosh is currently working on adding backend validation for the subject attribute value in the application PATCH request.

**Comment by ZiyamSanthosh** [comment]
Backend changes are implemented with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2333.

**Comment by Lakshan-Banneheke** [comment]
This FE fix was also onboarded with this to mitigate a regression: https://github.com/wso2/identity-apps/pull/5323
