### ISSUE TITLE
[Doc][Highest]Unable to find any information related to IWA fedarated authenticator Admin service

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1906]
I am trying to automate the IWA federated authenticator configuration using Admin serverice
I was referring [1] in order to find the available admin service per above particular scenario. Those information are not listed on this.

If this is a common doc, atlease put a reference on how find those details.

[1] https://docs.wso2.com/display/IS540/Calling+Admin+Services

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
