### ISSUE TITLE
Unable to update Password validation when the length is less than 8

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#19062]
**Describe the issue:**
When an admin want to update the password validation where the min length is 5 (any number less than 8) following error shows in the console. There is a FE validation prohibits to enter numbers less than eight cause there is no backend call.

https://github.com/wso2/product-is/assets/25488962/db5d9456-f3cb-4e9a-ae59-2028d0ee2f66

**Note that, I can update the validation via REST API and create a user with 5 letter password**

**How to reproduce:**
1. Go to Password validation
2. Type 5 as minimum length 
3. Try to update the configuration.

**Expected behavior:**
Admin should able to add a minimum length less than 8. Actually minimum length should be greater than 0.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0Beta6 Snapshot

**Comment by jeradrutnam** [comment]
Any specific requirement to go beyond 8? If not I don't see this is critical as we can define the recommendation. And may be improve the error optionally.

**Comment by janakamarasena** [comment]
> Any specific requirement to go below 8? If not I don't see this is critical as we can define the recommendation. And may be improve the error optionally.

Previous IS versions had 5 as the minimum default. There can be an impact for migrating setups.

**Comment by JayaShakthi97** [comment]
As per the discussion, the minimum will be updated to 5 since that's the minimum limit had in previous IS versions.

**Comment by JayaShakthi97** [comment]
Min limit is updated with:
- https://github.com/wso2/identity-apps/pull/5320
