### ISSUE TITLE
UI Alignment Issues and User Confusion in Permission Types and Endpoints in Role section under User management 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#19066]
**Describe the issue:**
The current UI in the Role Section of User Management presents alignment issues and lacks clarity, leading to user confusion. Specifically, the problem is evident in the representation of permission types and endpoints associated with roles. Users are finding it challenging to understand the meaning and implications of different permission types such as "TENANT_ADMIN," "ORGANIZATION_ADMIN," and "CONSOLE FEATURE" without clear information about the corresponding endpoints.

Note : specifically more confusion when role created via Console Settings 
**How to reproduce:**
1. Login to console
2. Create Role via Console Settings 
3. Add permissions for the Role 

**Expected behavior:**
The UI should be updated to align the elements properly and provide a clear, organized presentation of permission types and associated endpoints. A table format is recommended for better readability and understanding.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC
 - Browser: | Chrome 120.0.6099.234

[issueUI.webm](https://github.com/wso2/product-is/assets/39120228/ca92e650-3b34-4246-817a-720c4eddfa07)

<img width="1686" alt="Screenshot 2024-01-22 at 11 44 00" src="https://github.com/wso2/product-is/assets/39120228/552b35fe-bf9c-4696-9657-788fcf2fe517">

**Comment by DonOmalVindula** [comment]
As an improvement for user reference, we have mapped the permission types to following terms to be more in-line with the API Resource types in the API Resources page.
- ORGANIZATION_ADMIN -> Organization API
- TENANT_ADMIN -> Management API
- CONSOLE_FEATURE -> Console Feature
- BUSINESS -> Business API

Additionally we will also be adding tooltips that will show a short description of each type of API for better understandability.

The result would be as follows.
![Screenshot 2024-02-01 at 15 05 44](https://github.com/wso2/product-is/assets/42619922/e6818a26-1f0d-45c8-a5be-bf2a6a0725fe)
