### ISSUE TITLE
Improve user experience related to assigning a user to a role

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#19073]
**Describe the issue:**

In the Roles edit section, after selecting the user from the dropdown, we need to click on the Select button and then click on Update button to persist the changes. This is inconsistent with the other select dropdowns (eg: In the Groups tab, the group only needs to be picked. There is no additional step to click on a Select button.)

https://github.com/wso2/product-is/assets/28347418/fa7c6e60-999f-4bbf-8056-0349e2eeec7f

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Improved UX:

https://github.com/wso2/product-is/assets/41533942/9381becd-f28c-456a-b7ef-30bd45961caa
