### ISSUE TITLE
Error when using a + sign in the user's email

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#19085]
**Describe the issue:**
Have we changed the default email regex in IS? when I create a user with `+` in the email getting the below error from the API.
`"Error in adding the user: PRIMARY/alex. Email is not in the correct format."`

But UI allows to create a user with + in the email in the fresh pack.

**How to reproduce:**
Create a new user and add something like `ayesha+abc@wso2.com`
**Expected behavior:**
The default regex should be unified in UI and backend.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ZiyamSanthosh** [comment]
This is completed.
