### ISSUE TITLE
Configuring a SP and IdP Using Service Calls link redirects to older version of document

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1909]
Document: https://docs.wso2.com/display/IS540/Configuring+a+SP+and+IdP+Using+Configuration+Files

In this document, Configuring a SP and IdP Using Service Calls link redirects to an older version of the document.

**Comment by omindu** [comment]
@wso2/is-doc-team There can be other docs in 5.4.0 space which are linked to 5.3.0 docs.

**Comment by shavidissa** [comment]
Thank you! Fixed [1]. 

We will keep a lookout and correct the link. It happens when the 5.3.0 links are directly copied and linked to a section without using the page name in the doc space.

[1] https://docs.wso2.com/display/IS540/Configuring+a+SP+and+IdP+Using+Configuration+Files
