### ISSUE TITLE
Inconsistency in enable button in login and registration configs

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#19095]
**Describe the issue:**

There are some Inconsistencies in the enable button in login and registration configs. Most of them have a toggle button. But two of them have check boxes as below.

<img width="316" alt="Screenshot 2024-01-22 at 18 35 05" src="https://github.com/wso2/product-is/assets/13478571/6122f58d-2cec-4c23-a872-ce5894b96143">
<img width="526" alt="Screenshot 2024-01-22 at 18 35 15" src="https://github.com/wso2/product-is/assets/13478571/8b033fef-faba-43ff-ac17-cb9996412732">
<img width="526" alt="Screenshot 2024-01-22 at 18 36 30" src="https://github.com/wso2/product-is/assets/13478571/f9abc183-c53d-413d-b4e5-ab273440d36d">

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Hi @ashensw it was decided to add check boxes in the forms for enabling configurations and outside the forms we'll be using the toggle .
