### ISSUE TITLE
Organization users who logged in via SSO doesn't get the required scopes 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19097]
**Describe the issue:**
1. Create an organization
2. Switch to it
3. Create a user
4. Go to console settings and assign the user to Administartor role
5. Copy the Console access URL for that org
6. Try console login for the user in organization
7. Required scopes will not be returned, hence getting unauthorized error
8. The same behavior was expected with other B2B apps setup to try. btw, organization switch grant works fine.

https://github.com/wso2/product-is/assets/25483865/b13c205a-c313-48ab-9485-8d50f2845c2f

**Comment by shashimalcse** [comment]
Reverted the changes made to the federated user role resolver in oAuth (https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2336). This fixes the issue. Improvement with https://github.com/wso2/product-is/issues/18714 will address the previously solved problem.
