### ISSUE TITLE
Add tenant level outbound provisioning configuration in the Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#19100]
**Is your suggestion related to an experience ? Please describe.**
We need to introduce the tenant-level outbound provisioning configuration in the new Console. This configuration is listed under the resident service provider.

![image](https://github.com/wso2/product-is/assets/30111554/61c4349b-4116-4883-b62b-a0d824ef520d)

**Comment by JayaShakthi97** [comment]
UI support is introduced with:
- https://github.com/wso2/identity-apps/pull/5348


https://github.com/wso2/product-is/assets/37938529/860b6582-0e3a-4ce7-b312-2dd1df0671f3


https://github.com/wso2/product-is/assets/37938529/f815d90a-e63d-4abc-ae0f-b068bd07a2df

**Comment by JayaShakthi97** [comment]
As there is an ongoing discussion to finalize the user experience, the PR is marked as a draft.

**Comment by JayaShakthi97** [comment]
Framework changes:
- https://github.com/wso2/carbon-identity-framework/pull/5474

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta7-SNAPSHOT`

![image](https://github.com/wso2/product-is/assets/37938529/e6308e87-e328-4a8d-9ecd-1aefb6c897da)
