### ISSUE TITLE
[Doc] Please include all the required parameters when we are invloking admin service for IWA fedarated authenticator

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#1910]
Please include which properties should map with the UI values, when you are invoking through the admin service. Below information should include in the document which discuss how to create the IWA authenticator using admin service

Service Principal Name=SPNName
Service Principal Password=SPNPassword
USER_STORE_DOMAINS=UserStoreDomains
AUTHENTICATOR_NAME=IWAKerberosAuthenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
