### ISSUE TITLE
[Doc] Where are the Service Providers created?

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1911]
Type: Improvement
Priority: High
Severity: Major
Release: wso2is-5.4.0-update1

Service providers are created in the registry and that was not mentioned in the docs. Mentionthe path in the registry as well
https://docs.wso2.com/display/IS540/Adding+and+Configuring+a+Service+Provider

**Comment by omindu** [comment]
Only SAML configurations are store in the registry, rest of the SP configs are stored in the identity database.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
