### ISSUE TITLE
RemoteUserStoreManagerService WSDL does not return response code/ message

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#19114]
**Describe the issue:**
To align with the specification[1], there were fixes in 2 stages, but both of the fixes were not optimal (and these fixes have impacted the API user behaviour when migrating to latest versions):

- Adding respective In-Only message receiver wso2-extensions/identity-user-ws#26 - This method was defined as In-Only in WSDL, since the return type is void. However, this still returns a response payload, but as per the specification, the In-Only operation should not have a response code.
- Specify mepURI for in-only operations of the RemoteUserStoreManager service https://github.com/wso2-extensions/identity-user-ws/pull/56 - Since this is defined as In-Only in the aforementioned PR, the response payload was removed and the response code was changed to only return 202, aligning with the specification [1].

**How to reproduce:**
The updateCredential service (for example) returning 202 response code even for invalid old passwords. After the above mentioned changes, the updateCredential service is considered as an in-only operation and no response is returned. 
However, in the previous version of the customer, a 500 error response was returned for invalid old passwords.

**Expected behavior:**
Even though the method returns void, this should not be considered an In-Only operation, since this Admin Service requires a response code/ message (Example: updateCredentials to identify whether the password is updated successfully). It's WSO2 design that even though the return type is void, the error codes/ messages are returned by throwing exceptions. Hence, to align this with the specification, this should be defined as an In-Out operation properly (either changing the return type or defining this in any other way in Axis2).

[1] http://www.ws-i.org/Profiles/BasicProfile-1.1.html#One-Way_Operations

**Environment information**
 - Product Version: IS 6.1.0

**Comment by UdeshAthukorala** [comment]
Closing since the relevant PRs were merged.
