### ISSUE TITLE
Cannot download the config file created for Service providers in the registry

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1912]
Type: Bug
Priority: High
Severity: Major
Release: wso2is-5.4.0-update1

**Steps**
1. Create a SP
2. Go to the registry and download the created file

**Issue**
Cannot download the file. Tried with chrome and firefox

![21](https://user-images.githubusercontent.com/1845370/34260347-a059ac80-e68b-11e7-890c-e4ef192ec99e.png)

**Comment by omindu** [comment]
This is because the resource doesn't have any content. It only has properties.
