### ISSUE TITLE
Google Outbound Provisioning - Service Provider Configs Not Functioning in Console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#19121]
**Describe the issue:**
The outbound provisioning configurations for Google in the console are not working as expected for the Service Provider.

**How to reproduce:**
1. Login to Console
1. Configure Google as OutBound Provisioning Connector in selected Custom Connector 
2. Create Application 
3. Select configured connector as outbound provisioning
4. Select SCIM create user with Manage access to the API Resources in the application
5. Get the Access token via any grant type ex: client credentials
6. Try SCIM User creation API with access token we got in above step

[Uploading scim_spbasedOP.webm…]()

**Comment by UdeshAthukorala** [comment]
This was already fixed with the: https://github.com/wso2/product-is/issues/18856
