### ISSUE TITLE
Account disable: Incomplete instruction given in documentation

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1913]
In [1] the step where configuring account disable in the resident IDP is not provided. Please include it as without it the disabling won't work

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by sherenewso2** [comment]
Fixed and restructured content accordingly from 5.6.0 - 5.8.0 [1] 

[1] https://docs.wso2.com/display/IS580/Account+Disabling
