### ISSUE TITLE
[Doc] [Google federated authenticator] Google federated authenticator page is not updated.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#19148]
when following https://is.docs.wso2.com/en/next/guides/authentication/social-login/add-google-login/,
we can see that UI on [Google API & Services](https://is.docs.wso2.com/en/next/guides/authentication/social-login/add-google-login/#register-wso2-identity-server-on-google) is not updated in our doc space,

**Comment by himeshsiriwardana** [comment]
This is fixed. https://is.docs.wso2.com/en/latest/guides/authentication/social-login/add-google-login/
