### ISSUE TITLE
Groups are not listed in the new console when connecting to an existing ldap

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#19145]
**Describe the issue:**
$subject

**How to reproduce:**
1.  Have a ldap that have users & groups already populated
2.  Connect that (Read Write) ldap as a secondary user store with the (new) IS Console UI
3.  Navigate to user view and you can see the user list, Navigate to groups view you cant see groups

Groups are getting listed in the old management console without an issue.
Also, if you connect the ldap as read-only user store (even with the new console), groups get listed without an issue.

**Expected behavior:**
Groups should be listed in the groups UI in the new console when connecting an existing ldap in read-write mode.

---

### Optional Fields

**Related issues:**
Need this get fixed: https://github.com/wso2/product-is/issues/16368

**Comment by somindatommy** [comment]
This will be fixed with https://github.com/wso2/product-is/issues/16368. The LDAP part is already merged to BETA-6
