### ISSUE TITLE
Account disable: Wrong error message given when trying to log in from a disabled account

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1915]
Currently when the account is disabled the error message given does not indicate of the disabling rather states of a incorrect username or password. This should be corrected and the disabling should be notified to the user

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
