### ISSUE TITLE
Console login is not working in legacy runtime 

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#19167]
**Describe the issue:**
Console log is not working and redirect to the below page after enter the credentials in legacy runtime mode

**How to reproduce:**
- Get the latest IS pack
- Before start the pack add the below config to the depolyment.toml file
```
[legacy_authz_runtime]
enable=true
```
- Start the server
- Try to login to console with admin credentials
- Redirected to the below page

![Screenshot from 2024-01-24 15-03-45](https://github.com/wso2/product-is/assets/36092400/f9d9d29b-c5ad-4c3b-8ce0-a55609199949)

**Expected behavior:**
Admin should be able to login to the console

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT

**Comment by brionmario** [comment]
`console:<SCOPE>` are not returned in the token causing the console UI to go to an unauthorized state as expected.

We need to figure out if this is the expected behaviour in legacy mode and if so, add an additional config to the `legacyMode` configs in the Console to enable/disable these scope validations.

**Comment by brionmario** [comment]
As discussed with the B2B, seems like the scope validator is dropping the `console:` scopes in legacy mode.
This is not the expected behaviour and needs to be fixed from the BE.

**Comment by PasinduYeshan** [comment]
As per the discussion a new config was introduced to conditionally disable the console scope check in legacy mode. This config will be enabled when the `legacy_mode` is enabled in the pack. 

To enable legacy mode, add the following configuration under the `server` section in your configuration file:
```
[server]
.....
legacy_mode = true
```

Note: Activating the `legacy_authz_runtime` configuration will enable the legacy authz runtime in the backend. However, it's important to understand that merely enabling this configuration does not fully replicate the behavior of the legacy mode."

### PRs
- https://github.com/wso2/identity-apps/pull/5380
- https://github.com/wso2/carbon-identity-framework/pull/5454
