### ISSUE TITLE
Account disabling: confusing content on documentation regarding switching off disabling

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1916]
In [1] it states that by changing the following property in identity-event.properties, when set to false that it will remove the account disabling option from the super tenant.

`account.disable.handler.enable=false`

But in the default config it is set to false but when I configure account disable for resident IDP im able to disable accounts. Hence the given statement in the document is confusing. Please verify and update

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
