### ISSUE TITLE
Account disabling: document states configuring resident idp to disable accounts is only possible for tenants

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1917]
In [1] at the end it says that to disable accounts in the tenant the account disable feature in resident idp can be used. This implies that it's only able to do so for tenants. But for super tenant also it's able to configure disabling the same way. Please rectify the document.

[1] https://docs.wso2.com/display/IS540/Account+Disabling

**Comment by ShirazAzad** [comment]
Fixed. in [1] 
[1] https://docs.wso2.com/display/IS540/Account+Disabling
