### ISSUE TITLE
Intermittently B2B sub org user logout doesn't work

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19171]
**Describe the issue:**

- Configure a B2B app share with orgs
- Log as a sub org user
- Try logout

https://github.com/wso2/product-is/assets/25483865/19d7dee8-761e-47da-a2c5-a987f6a2bfda

Getting this printed in the terminal

```
[2024-01-24 15:11:35,520] [835565a9-8abf-40b3-a282-b7c4e46bfa34]  WARN {org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet} - Provided Post logout redirect URL does not match the registered callback url.
```

Configured callbacks are as follows:
<img width="943" alt="Screenshot 2024-01-24 at 16 31 45" src="https://github.com/wso2/product-is/assets/25483865/084a5fe2-46f2-4b1c-bf6e-6640822951fb">

**Comment by sadilchamishka** [comment]
Can you show the callback URL which is set in the shared app. @AnuradhaSK

**Comment by AnuradhaSK** [comment]
Seems the callback URL is wrong, it should be root tenant's common auth URL
<img width="1714" alt="Screenshot 2024-01-25 at 12 18 55" src="https://github.com/wso2/product-is/assets/25483865/d5a5f30c-be51-48f9-8160-1b1f429155e5">

**Comment by PasinduYeshan** [comment]
This issue is not reproducible in the latest pack. Callback URL in the shared app is correct.
![image](https://github.com/wso2/product-is/assets/61885844/8c475922-e6bd-4b10-92f1-b572a4a87c93)
