### ISSUE TITLE
Few errors are displayed when adding a user in a sub-organization via console.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#19179]
<img width="1728" alt="Screen Shot 2024-01-25 at 4 27 32 PM" src="https://github.com/wso2/product-is/assets/24982871/55ac3dc5-768d-448b-b7ee-dd206f2d9c94">
<img width="1483" alt="Screen Shot 2024-01-25 at 4 28 03 PM" src="https://github.com/wso2/product-is/assets/24982871/e317189b-3162-47bf-9913-e3797b0f11b6">

Note: This search API call was not in a pack built a few weeks back.

**Comment by DilshanSenarath** [comment]
The fix has already been merged into the identity-apps. https://github.com/wso2/identity-apps/pull/5334
