### ISSUE TITLE
How do i get the login history for audit purposes using wso2 is

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1918]
I have a use case where I need to get the login history for accounts for audit purposes. How do I achieve this?

**Comment by omindu** [comment]
You can use IS analytics [1] for this. Also some information are available in the `audit.log` as well

[1] - https://docs.wso2.com/display/IS540/Monitoring+WSO2+IS+Using+WSO2+Analytics

**Comment by erandidesilva** [comment]
@omindu: Thank you will try this out.

**Comment by omindu** [comment]
Probably not. Would be nice to have something like [1]

[1] - https://docs.wso2.com/display/AM210/Working+with+Audit+Logs

**Comment by sagara-gunathunga** [comment]
ATM there is no plan to support this feature, will move this into product roadmap.
