### ISSUE TITLE
Cannot configure custom servlet mappings in accountrecoveryendpoint web.xml file

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#19185]
Hi Team,

In later IS versions,  the web.xml file changes in accountrecoveryendpoint and authenticationendpoint needs to be configured through the deployment.toml file as the web.xml files are templated.

However, it seems that we cannot add custom servlet mappings in accountrecoveryendpoint because it is not templated to configure the custom servlet mappins.. 
In authenticationendpoint we have this capability where it has the below configuration in web.xml.j2 file .

{% for custom_servlet in servlet %}
    <servlet>
        <servlet-name>{{custom_servlet.name}}</servlet-name>
        <jsp-file>{{custom_servlet.jsp}}</jsp-file>
    </servlet>
    <servlet-mapping>
        <servlet-name>{{custom_servlet.name}}</servlet-name>
        <url-pattern>{{custom_servlet.url}}</url-pattern>
    </servlet-mapping>
    {% endfor %}
It is required to add the same kind of template to configure the custom servlet mappings in accountrecoveryendpoint.

**Comment by AfraHussaindeen** [comment]
Please note that the following structure must be utilized to configure servlet mappings through the deployment.toml:

```
[[accountrecoveryendpoint.servlet]]
name = "<servlet-name>"
url = "<url-pattern>"
jsp = "<jsp-file>"
```
