### ISSUE TITLE
API resources are not loading in the dropdown in the Create Application Role Wizard

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#19183]
**Describe the issue:**
$subject

<img width="1504" alt="Screenshot 2024-01-25 at 23 26 32" src="https://github.com/wso2/product-is/assets/41533942/7f1838f1-18c1-4801-8daa-980e6f6d1749">

**How to reproduce:**

N/A

**Expected behavior:**

API resource dropdown should be populated with the api resources.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
`GET /authorized-apis` only returns one result in the response.

<img width="1504" alt="Screenshot 2024-01-25 at 23 31 43" src="https://github.com/wso2/product-is/assets/41533942/53a8a8ef-3db4-4fb3-b1d7-f7b15f834f72">

**Comment by PasinduYeshan** [comment]
This issue is already fixed.
