### ISSUE TITLE
Incorrect Logging of Removed Claims

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#19196]
**Describe the issue:**
The logic at [`logUpdatedClaims`](https://github.com/wso2/carbon-identity-framework/blob/v5.18.187/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserClaimsAuditLogger.java#L162) incorrectly logs removed claims ( the removed claims logged in the audit logs are not the removed claims). This issue arises because, when a claim is set for a user using a method, the loggableClaims captures the list of current claim values and marks all claims, except the one being updated, as removed claims.

**How to reproduce:**
Lockout a user due to failed login attempts and observe the audit logs below.
```
Initiator : wso2.system.user | Action : doPreSetUserClaimValues | Target : user3 | Added Claims : { "http://wso2.org/claims/identity/lockedReason" : "MAX_ATTEMPTS_EXCEEDED" } | Updated Claims : { "http://wso2.org/claims/identity/accountLocked" : "true" } | Removed Claims : { "http://wso2.org/claims/modified" : "2024-01-26T05:04:43.296Z" , "http://wso2.org/claims/emailaddress" : "admin@wso2.com" , "http://wso2.org/claims/givenname" : "Mifraz" }
Initiator : wso2.system.user | Action : doPreSetUserClaimValues | Target : user3 | Added Claims : {  } | Updated Claims : {  } | Removed Claims : { "http://wso2.org/claims/modified" : "2024-01-26T05:06:29.960Z" , "http://wso2.org/claims/identity/lockedReason" : "MAX_ATTEMPTS_EXCEEDED" , "http://wso2.org/claims/emailaddress" : "admin@wso2.com" , "http://wso2.org/claims/identity/accountLocked" : "true" , "http://wso2.org/claims/givenname" : "Mifraz" }
```
For instance, the lockedReason claim is logged as a removed claim in the 2nd audit log.

**Expected behavior:**
The removed claim list should only contain a list of claims that are removed (ex: set empty value).

**Environment information**
 - Product Version: IS 5.11.0

**Comment by Yasasr1** [comment]
Closing since the fix is onboarded with the above pr
