### ISSUE TITLE
Secondary user stores are not listed in the Groups page in Console when no groups are available in the Primary userstore

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#19203]
**Describe the issue:**
In IS 7.0, a default group named `Primary/admin` is available in the Groups. This group can be deleted by a user. In a situation like that if we does not have more than two secondary userstores, the search bar is not visible for the filtering.

When the `admin` group is available in the `Primary` userstore following is the Groups page search bar.
<img width="1715" alt="image" src="https://github.com/wso2/product-is/assets/19262008/207051ed-608e-4f1b-820c-7a6769fc957f">

Following is the view of the userstores in the Groups search bar.
<img width="1715" alt="image" src="https://github.com/wso2/product-is/assets/19262008/b92b7a86-56f3-4d52-8d0a-376b1c3c682b">

After deleting the `admin` group from the `Primary` userstore and if there are only two secondary userstores, then following is the Groups page result.
<img width="1715" alt="image" src="https://github.com/wso2/product-is/assets/19262008/ebbd0505-fea5-445f-871c-11de41fa8b64">

If the secondary userstore count is more than 2, then we can see the userstores on the search bar.
<img width="1715" alt="image" src="https://github.com/wso2/product-is/assets/19262008/bf5e3135-4252-4a45-9b21-fcc44e8567aa">

**How to reproduce:**
1. Login to the Console.
2. Add any kind of a secondary userstore (Just adding them from the app is enough. No need a functional database).
3. Remove the `admin` group from the `Primary` usestore.
  - In this place you will be signed out from the console.
4. Login again and go to the Groups page.

**Expected behavior:**
The search bar should be visible without considering the number of secondary userstores available.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by brionmario** [comment]
An arbitrary `3` array length is used to `show/hide` the userstore select panel.
- https://github.com/wso2/identity-apps/blob/8cd9ba967bea23c3c0ed605a3ff1ed1f54e490f0/apps/console/src/features/groups/pages/groups.tsx#L345

Need to get rid of the arbitrary value and if it's needed for any product extending the IS, that should go in to a configuration.

**Comment by pavinduLakshan** [comment]
This issue is not reproducible in the latest build it seems.

<img width="1502" alt="Screenshot 2024-01-29 at 15 00 28" src="https://github.com/wso2/product-is/assets/41533942/b22ef7f2-57c6-4fec-9ea5-20736c54ddba">

**Comment by pavinduLakshan** [comment]
Was able to reproduce.

**Steps followed**:

1. Create a new JDBC user store.
2. Go to groups page.
3. Delete primary/admin group
