### ISSUE TITLE
Readonly ldap userstore attributes are not rendered properly

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#19211]
**Describe the issue:**
Readonly ldap userstore attributes are not rendered properly. All boolean attributes should have a toggle. Refer to the image below.
![Screenshot 2024-01-26 at 06 20 30](https://github.com/wso2/product-is/assets/39567992/459ae497-3b6f-467f-908d-b82cc3af2743)

**How to reproduce:**
1. try the wizard to add a readonly ldap and notice the above.
2. Add the LDAP and then go to group settings of the userstore. Notice the above.

**Expected behavior:**
Should display a toggle

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
`type` is returned as `string` for the metadata response. Better fix this from the backend.

<img width="581" alt="Screenshot 2024-01-26 at 17 06 13" src="https://github.com/wso2/product-is/assets/25959096/36b7d14d-da28-4500-ad66-703d5caea5dd">

**Comment by ZiyamSanthosh** [comment]
Closing since this is completed.
