### ISSUE TITLE
Permission Error When Adding and Updating Sub-Organization User Profiles

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#19219]
**Describe the issue:**
When the Super admin attempts to add a user to a sub-organization and subsequently update the user's profile, an error message is displayed: 
` 
"Error retrieving the admin role. Operation is not permitted. You do not have permissions to make this request." 
`

Additionally, a 403 error is logged in the browser console for the endpoint 
` "t/carbon.super/o/scim2/Roles/.search." `

**How to reproduce:**

1. Log in as the Super admin.
2. Navigate to a sub-organization.
3. Add a user to the sub-organization.
4. Attempt to update the user's profile.
5. Observe the error message and check the browser console for a 403 error related to "t/carbon.super/o/scim2/Roles/.search."

**Expected behavior:**
The Super admin should be able to add a user to a sub-organization and successfully update the user's profile without encountering errors related to admin role retrieval and 403 errors in the browser console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta6-SNAPSHOT Build #5035
 - OS: Mac
 - Database: Mssql
 - Userstore: JDBC

---

[suborguser.webm](https://github.com/wso2/product-is/assets/39120228/c2f7f369-ae09-484a-9963-f99972080be1)

**Comment by dewniMW** [comment]
Closing the issue based on https://github.com/wso2/product-is/issues/19179#issuecomment-1911440363
