### ISSUE TITLE
Mark "Payload" attribute of Custom SMS Provider as a required attribute

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19231]
**Describe the issue:**

- Go to Email & SMS configs -> SMS -> Select custom option
- Only  SMS Provider Name  and SMS Provider URL are marked as mandatory attributes. Hence give some values there and submit
- Request fails with 400 error response 
```
{
    "code": "NSM-60004",
    "message": "Required attribute is missing.",
    "description": "SMS payload is not defined for notification sender.",
    "traceId": "06e9155d-67bb-4af5-a9eb-e70c6ab61740"
}
```
https://github.com/wso2/product-is/assets/25483865/d8c4f29b-e98f-4a64-94e8-8766b0103baf

Since payload is mandatory attribute, mark it in UI and do UI validation for field is not empty

<img width="1724" alt="Screenshot 2024-01-27 at 16 22 25" src="https://github.com/wso2/product-is/assets/25483865/029ce1b1-7ad0-475b-977e-c2288f0bf5fb">

**Comment by DilshanSenarath** [comment]
Similar issue: https://github.com/wso2/identity-apps/pull/5375
