### ISSUE TITLE
Console application selection on SMS OTP, Email OTP, TOTP, Magic Link, passkey quick start guide doesn't land into "Login Flow" tab of Console Settings

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19234]
**Describe the issue:**

1. Go to connections >SMS OTP/ Email OTP
2. Go to the Quick Start tab
3. Click on the applications link there, select Console
4. You will be navigated to the Console Settings -> Administrators tab

https://github.com/wso2/product-is/assets/25483865/edca871b-65db-450b-aafe-a99680a620dc

Expected behavior:
Land in to Console Settings ->  Login Flow tab

**Comment by JayaShakthi97** [comment]
Fixed with:
- https://github.com/wso2/identity-apps/pull/5382

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta7-SNAPSHOT`

https://github.com/wso2/product-is/assets/37938529/e63082b2-509a-4b9d-9caa-f782a8f67049
