### ISSUE TITLE
Signin methods section doesn't render in UI unless the tab is clicked when navigating to sub org's MyAccount app config from a SMS OTP like connection's quick start

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19235]
**Describe the issue:**
1. Create a sub org and switch to it
2. Go to connections >SMS OTP/ Email OTP
3. Go to the Quick Start tab
4. Click on the applications link there, select My Account
5. You will be navigated to the MyAccount's "Sign in Methods" tab, but the signin methods doesn't render in UI unless you click on the tab

https://github.com/wso2/product-is/assets/25483865/f8b4551b-7d4e-4025-b5bb-9294fdbc3e66

**Comment by JayaShakthi97** [comment]
Issue is occurring due to setting the tab index incorrectly when redirecting to the edit view of the My Account App. The tab index should be 0 in the sub-organization.
- Fix: https://github.com/wso2/identity-apps/pull/5378

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta6-SNAPSHOT`


https://github.com/wso2/product-is/assets/37938529/73900a2a-af8d-4028-a2f5-c1cb3a30b944
