### ISSUE TITLE
Password pattern: Error message given in dashboard

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-is#1923]
As shown in the below image, the error message given obstructs further functionality.

![is_issue_18](https://user-images.githubusercontent.com/15624590/34285603-d161bd66-e700-11e7-9c11-2b26f8b3b6b8.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
