### ISSUE TITLE
Console administrator cannot log in to organization's myaccount as organization user

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#19242]
**Describe the issue:**

$subject

**How to reproduce:**

1. Sign into console as an admin.

2. Make an existing user an admin.

3. Create an organization and switch to the created organization.

4. Invite the user in step 2, to the sub organization.

5. Navigate to Applications page and copy the myaccount URL.

6. Go to the copied URL and try to log in with the credentials of the admin created in step 2.

7. Observe that the user is redirected to super tenant path and the UI is loading indefinitely.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This was only reproducible to me when trying to run myaccount locally and wasn't reproducible when running myaccount in the pack. Hence closing the issue.

**Comment by dewniMW** [comment]
Couldn't reproduce the said behavior on a pack built on 28/01/2024
The following assumptions were made
Step 2 - Here admin means the Administrator role
Step 5 - My account URL of sub org (anyway checked the behavior with both invited sub org and user residing actual org)
