### ISSUE TITLE
Application's API authorization addition and removing API authorization should be protected from `internal_application_mgt_update` scope

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19240]
**Describe the issue:**

POST `https://localhost:9443/api/server/v1/applications/cd863fe8-18d0-4fdd-8139-e4637a2bf223/authorized-apis` which is used to authorize an API to an application is protected from `internal_application_mgt_create` scope

DELETE `https://localhost:9443/api/server/v1/applications/cd863fe8-18d0-4fdd-8139-e4637a2bf223/authorized-apis/143e75ca-489d-4d3f-98f5-edb463fe5201` which is used to remove an authorized API from an application is protected from `internal_application_mgt_delete` scope

Since both of the above operations are editing an application, `internal_application_mgt_update` scope is ideal for the purpose
Need to fix from resource access controller
+ update in yaml  in api-server and API in docs

**Comment by ZiyamSanthosh** [comment]
This is completed. Hence closing!
