### ISSUE TITLE
The Error message pops up when disabling an IDP which associated with at least one SP, disappears quickly in UI

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1925]
== Environment ==

IS 5.4.0 2 single node
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

1. Create an IDP (ex- Facebook [1])
2. Create a SP and set Facebook IDP as Federated Authentication Type.
3. Go to 'Identity Providers' and try to disable the created Facebook IDP

== Actual Result ==

Pop up appears and disappears quickly and user couldn't see the error message.

== Expected Result ==

Error message should be appears a reasonable time until the user close it after viewing.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
