### ISSUE TITLE
[DOC][Testing Passive STS]Provide a reference how to test this via Admin service

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1926]
Document: https://docs.wso2.com/display/IS540/Testing+Passive+STS

Please provide a reference/sample on how to do the same thing, which is done through Management Console, via Admin Services.

**Comment by omindu** [comment]
Refere "Configuring STS WebApp as the Service Provider through Admin Services" [1]

[1] - http://wso2-oxygen-tank.10903.n7.nabble.com/Configuring-STS-WebApp-as-the-Service-Provider-through-Admin-Services-td153933.html

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
