### ISSUE TITLE
[Userstore] Creating a corrupt userstore when the userstore name is given with special characters like ${}

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#19263]
**Describe the Issue:**
Userstore can be created with a name as WERWER${}SEWR. But after creation, the userstore cannot be accessed 

**How To Reproduce:**
1. Navigate to the Userstore page
2. Create a userstore with name as WERWER${}SEWR
3. Verify the system behaviour

**Expected behavior:**
1. Either it should be restricted if we are allowing it via the API and front-end

**Device Information:**
 - Device (e.g. PC, iPhone6):
 - OS (OSX, Android, iOS):
 - Browser + Version:

---

### Optional Fields

**Related Issues:**

**Suggested Labels (for non-committers):**

**Suggested Assignees (for non-committers):**

---
### Testing Related Fields

**Local e2e Tests Status (Please attach the screenshots of the result):**

**Manual Test Plan (Please attach the document link):**

**Manual Test Plan Reviewed by:**

**Comment by Lakshan-Banneheke** [comment]
Updated the validation at the api level to not allow the ${} pattern and also added a validation to check whether the userstore name is a valid file name. The userstore name is used to create an xml file and therefore should be a valid file name.
