### ISSUE TITLE
The "Learn More" link in the Product Branding section's custom layout is navigating to the 6.1 documents

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#19275]
**Describe the issue:**

The "Learn More" link in the Product Branding section's custom layout is navigating to the 6.1 documents instead of the 7.0 docs.

``` https://is.docs.wso2.com/en/latest/references/extend/rebranding/customizable-login-portal ```

<img width="1705" alt="Screenshot 2024-01-30 at 10 31 36" src="https://github.com/wso2/product-is/assets/39120228/b401181c-98ac-4a51-a5ac-a4871fefcb9b">

Product version : wso2is-7.0.0-beta6-SNAPSHOT

**Comment by AnuradhaSK** [comment]
- Usually `Learn More` sections are not included in the console UI of the Identity Server.
- Since the IS can be run on-prem without a network connection documentation access should not be in the UI IMO,
- @brionmario shouldn't this be a FE issue instead of Docs issue

**Comment by brionmario** [comment]
> * Usually `Learn More` sections are not included in the console UI of the Identity Server.
> * Since the IS can be run on-prem without a network connection documentation access should not be in the UI IMO,
> * @brionmario shouldn't this be a FE issue instead of Docs issue

Yes. We need to remove this from the UI.

**Comment by brionmario** [comment]
> * Usually `Learn More` sections are not included in the console UI of the Identity Server.
> * Since the IS can be run on-prem without a network connection documentation access should not be in the UI IMO,
> * @brionmario shouldn't this be a FE issue instead of Docs issue

This was left intentionally to improve DX.
@DilshanSenarath will know more context.

**Comment by DilshanSenarath** [comment]
> * Usually `Learn More` sections are not included in the console UI of the Identity Server.
> * Since the IS can be run on-prem without a network connection documentation access should not be in the UI IMO,
> * @brionmario shouldn't this be a FE issue instead of Docs issue

As mentioned by @brionmario, while this enhances the UX, users might not be able to access this link if the product is deployed in a VPN network that blocks public network access. Since the description provides clear instructions to consult the identity server documentation, I will remove the documentation link from the custom layout preview.
