### ISSUE TITLE
[Doc] Remove unavailable scripts execution steps from `Change to MySQL` documentation.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19276]
**Is your suggestion related to a missing or misleading document? Please describe.**
$Subject

<img width="1302" alt="Screenshot 2024-01-29 at 18 10 04" src="https://github.com/wso2/product-is/assets/41188245/e2d24686-1cdf-4120-be8c-a1105cb1584c">

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by ashensw** [comment]
This is fixed https://is.docs.wso2.com/en/next/deploy/configure/databases/carbon-database/change-to-mysql/#change-the-default-datasource
