### ISSUE TITLE
[Doc] Foursquare app creation images should be updated with latest ones

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1927]
The current images for Foursquare application configurations in [1] needs to be update with current application development screenshots.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Foursquare+Authenticator#ConfiguringFoursquareAuthenticator-ConfiguringtheFoursquareApp

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
