### ISSUE TITLE
Update Documentation to Align with Product UI for MFA based on User Sign-in

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#19288]
**Issue**

Currently, there is no option to select "MFA based on user sign-in" via the product UI. However, the documentation suggests that this option is available, which is inaccurate. To ensure alignment between the product UI and documentation

**Describe the improvement**
Update the documentation to reflect the actual state of the product UI. 

---

Related document : https://is.docs.wso2.com/en/next/guides/authentication/conditional-auth/sign-in-option-based-template/

<img width="1127" alt="Screenshot 2024-01-30 at 14 23 52" src="https://github.com/wso2/product-is/assets/39120228/218101e5-3dd6-47bd-923f-217993db827f">

<img width="1184" alt="Screenshot 2024-01-30 at 14 23 56" src="https://github.com/wso2/product-is/assets/39120228/8b759214-c804-4bc4-8698-b59afca7b6cd">

**Product UI :** 

Classic Editor
<img width="523" alt="Screenshot 2024-01-30 at 14 24 53" src="https://github.com/wso2/product-is/assets/39120228/22e3e481-55d4-490a-bbdc-cf8de047fcb4">

Visual Editor
<img width="463" alt="Screenshot 2024-01-30 at 14 25 06" src="https://github.com/wso2/product-is/assets/39120228/ba618093-57e0-4a3b-9dde-0983ebc59790">

Product version: wso2is-7.0.0-beta6-SNAPSHOT

**Comment by himeshsiriwardana** [comment]
This doc is removed from IS 7.0 docs
