### ISSUE TITLE
Google JIT Provisioning is not working when a user exists with a username of local part of provisioning user.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#19294]
**Describe the issue:**

During JIT (Just-In-Time) provisioning **when provisioning scheme is other than silent**, if a user attempts to register with a username that already exists without domain (ex: if the email is "abc@gmail.com", user exist as "abc"), an authentication error occurs,`Username 'abc@gmail.com' is already taken. Please pick a different username. To fix this issue, please contact the administrator.`

https://github.com/wso2/product-is/assets/25488962/aa5786f2-21b1-49cd-b0e0-da873015c733

However, if no user with the specified username (with or without the domain) is found, the user is successfully onboarded with the specified domain. (ex: user onboard as "abc@gmail.com")
 
There is a inconstancy with the behaviour.  

**How to reproduce:**
1. Login to console
2. Create application
3. Create google IDP
4. Enable JIT provisioning on created IDP
5. Modify the JIT provisioning scheme to Prompt for Password and consent
6. Configure created application with the google IDP as first factor. 
7. Create user with  the email username and without domain (ex: if your email user name is abc@gmail.com create user with username abc)
8. Authenticate to the application. 
9. Check the behaviour. 
10. Login to console again and delete created user "abc"
11. Authenticate to the application with abc@gmail.com
12. Validate the provisioned user  username. 

**Expected behavior:**
there is a inconstancy of the behaviour in step  8 provisioning should be completed since the existing user,"abc" is different from  "abc@gmail.com"

**Comment by DMHP** [comment]
@RushanNanayakkara Hope, you are planning to address this issue from your effort. Please let me know if you are planning to de-prioratize this.

**Comment by RushanNanayakkara** [comment]
@DMHP Yes, after the final discussion on this today. I'm starting to work on the fix.

**Comment by RushanNanayakkara** [comment]
Closing as all relavent PRs are merged.
