### ISSUE TITLE
is there pre-packaged IS 5.4.0u2  to be KeyManager for APIM 2.1.0 ?

### ISSUE THREAD

**Issue by crognon** [wso2/product-is#1929]
The $subject is complete :)

I would like to know if this release exists to be KM for APIM 2.1.0 : IS-KM 5.4.0update2

**Comment by omindu** [comment]
Hi @crognon,

As per the API manager team, most likely the prepacked 5.4.0 KM will be released for APIM 2.2.0 [1]

[1] - http://mail.wso2.org/mailarchive/architecture/2017-December/029497.html
