### ISSUE TITLE
Add support for attributes section for OIDC connections

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#19297]
**Describe the issue:**
Currently, attribute section is not supported for OIDC connections in the console. We need to support the attribute section for OIDC connections for custom claim mappings

**Comment by JayaShakthi97** [comment]
The attribute section is available in `IS 6.1.0`.

https://github.com/wso2/product-is/assets/37938529/634a8088-8537-4b19-935e-0d731a46bdae

Seems there is an extension configuration issue, which causes to hide the Attributes tab in the OIDC connection.

**Comment by SujanSanjula96** [comment]
This should be hidden since the default behaviour does not honor the custom claim mappings previously. With the fix https://github.com/wso2/carbon-identity-framework/pull/5481, the default behavior will be changed to honour the custom claim mappings. Hence we can show the attribute section. But we need to hide this section / or add a banner when the `authentication.endpoint.enable_custom_claim_mappings` config is set to false.

**Comment by JayaShakthi97** [comment]
Fix:
- https://github.com/wso2/identity-apps/pull/5445

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta7-SNAPSHOT`

![image](https://github.com/wso2/product-is/assets/37938529/b52da437-fe4a-418e-907a-8d67a4a96438)

**Comment by iwmarktaglieri** [comment]
Hi there, do you have an estimate for when this bug fix will be available in a beta release patch? Thanks.
