### ISSUE TITLE
When configuring an IDP with Foursquare, it allows to configure without having mandatory fields such as client id, client secret

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1930]
== Environment ==

IS 5.4.0 standalone pack
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate == 

1. Copy 'Foursquare authenticator .jar' file from [1] to <IS_HOME>/repository/components/dropins 
2. Start the IS server,  Go to management console and click 'Add' Identity Provider. 
3. Give a valid name for IDP and expand 'Foursquare Configuration' section under 'Federated Authenticators' section.
4. Add values to optional fields such as 'Profile Version' and click update.

== Actual Result ==

IDP saved without any issue.

== Expected Result ==

IDP shouldn't be saved since mandatory fields weren't filled.

[1] https://store.wso2.com/store/assets/isconnector/list?q=%22_default%22%3A%22foursquare%22

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
