### ISSUE TITLE
Update Azure AD references to Microsoft Entra ID under Microsoft login 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#19312]
**Is your suggestion a test requirement/change or improvement of the test framework? Please describe.**
Azure Active Directory is now Microsoft Entra ID. https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id

There are product UIs, URLs and documentation that still refer to Azure AD.

https://wso2.com/asgardeo/docs/guides/authentication/social-login/add-microsoft-login/
https://is.docs.wso2.com/en/next/guides/authentication/social-login/add-microsoft-login/

<img width="1728" alt="Screenshot 2024-01-31 at 2 23 08 PM" src="https://github.com/wso2/product-is/assets/5061791/3ecf50d8-411d-437b-9778-6fdb8e45ddf1">

**Describe the solution you would prefer**
Update the UIs, URLs and Product documentation and screenshots to update the necessary references to Entra ID. 

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by DilshanSenarath** [comment]
UI and URL changes associated with this issue are done. A new issue has been created to track the documentation changes related to this. Please refer to https://github.com/wso2/product-is/issues/19329 for details.
