### ISSUE TITLE
[Docs] Need to include Localization support extension guides

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#19324]
**Is your suggestion related to a missing or misleading document? Please describe.**

We used to have documentation on extending the localization support in the Login Portals & My Account / Console.
   - https://is.docs.wso2.com/en/6.1.0/references/extend/localization-support-in-identity-server/#!

But in the latest in progress IS 7.0 docs, we don't have this documented. 

**Describe the improvement**

- Need to validate the previous content and include the guides.
- ⚠️ Need to specially make sure that the approach is U2 safe (specially in Console / My Account)

**Comment by ShanChathusanda93** [comment]
This doc implementation is hold since there is an issue with the customization. Issue created [1]

[1] https://github.com/wso2/product-is/issues/19529

**Comment by himeshsiriwardana** [comment]
This doc is now available: https://is.docs.wso2.com/en/latest/guides/branding/localization/
