### ISSUE TITLE
Provide a dedicated API to trigger notifications

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#1934]
**Description:**

Currently we do not have an independent notification service (REST/SOAP) to trigger notifications/send emails to users. We can have a dedicated service which takes the user information and email template type as input parameters and manually trigger notification event handler inside this service to send a notification to the user.

**Suggested Labels:**

Improvement

**Suggested Assignees:**

**Affected Product Version:**
IS 5.4.0

**Related Issues:**

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
