### ISSUE TITLE
The subject attribute can not be modified in OIDC Applications

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#19349]
The following section is missing in the OIDC Applications. 

<img width="1047" alt="image" src="https://github.com/wso2/product-is/assets/12690906/8e362549-b323-484a-81b9-5822dad241f5">

The sections should be added to the OIDC applications.

In addition to the above, change the Subject Attribute of the OIDC applications to user-id from username

**Comment by DMHP** [comment]
Need to track the migration task to add migrations docs for this behavioral change.

**Comment by DonOmalVindula** [comment]
> Need to track the migration task to add migrations docs for this behavioral change.

Added a migration task - https://github.com/wso2/product-is/issues/19504
