### ISSUE TITLE
Trying to remove Administrator role from console leads to session timeout

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#19342]
**Describe the issue:**

https://github.com/wso2/product-is/assets/35717390/5a1d677c-313b-4785-8268-f97aa6484aeb

Better if we can restrict the role delete if that role is not allowed to be deleted. "Administrator" role.

It looks when trying to delete the role, the token is revoked. It should be happen in normal cases but in this case, the revocation shouldn't happen as the role was not deleted. Looks there is an issue in the order of execution.

**Comment by dewniMW** [comment]
In a pack built on 02/02/2024 couldn't see the delete option:

<img width="1713" alt="Screen Shot 2024-02-02 at 12 09 31 PM" src="https://github.com/wso2/product-is/assets/24982871/cd3127f0-4aa1-4593-9a9b-adf93646bb8b">
