### ISSUE TITLE
Add mobile claim verification related feilds to the exsisting claim update verification section

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#19358]
Add the following fields to the claim update verification section. 
- Enable user mobile number verification on update
- Enable mobile number verification by privileged users

Please make sure to test the whole feature properly to identify whether there are any gaps.

**Comment by AnuradhaSK** [comment]
Duplicate https://github.com/wso2/product-is/issues/19289

**Comment by brionmario** [comment]
Had a chat with @ayshsandu, @NipuniBhagya, @UdeshAthukorala. Following are the highlights.

- Show the mobile claim update related configs.
- Verify whether the email & mobile claim update verification flows works as expected as per docs.
   - https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-email-account-verification-for-an-updated-email-address/
   - https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/enable-verification-for-updated-mobile-number/
 - ATM, there's no UI to enter the OTP received for mobile claim updates. Create an issue for this improvement.

**Comment by NipuniBhagya** [comment]
According to this PR [1] we have provided the capability to verify the mobile claim in the My Account app. But in the current implementation this is not working as expected. Therefore we need to fix this UX.

[1] - https://github.com/wso2/identity-apps/pull/1275

**Comment by NipuniBhagya** [comment]
@brionmario We already have the UI to enter OTP in the My Account profile section. It is implemented in such a way that it is conditionally hidden in the implementation level and the admin will have to manually update the UI config.

CC: @ayshsandu @UdeshAthukorala 
 
![Screenshot 2024-02-06 at 14 32 29](https://github.com/wso2/product-is/assets/30111554/4dd4fa5d-123e-473f-8930-b527b5223f27)
