### ISSUE TITLE
Allow user to recover password through email if the account is locked

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#1935]
When the user account is locked, the user will not be able to any operation through IS. As an improvement, the user should be allowed to reset the password through email when the user account is locked.

**Comment by ChamathNS** [comment]
Fixed with https://github.com/wso2-extensions/identity-governance/pull/394.

**Comment by ChamathNS** [comment]
Fixed with https://github.com/wso2-extensions/identity-governance/pull/394.
