### ISSUE TITLE
Certificate Issue when configuring the Sample OIDC app for IS 7.0.0

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#19363]
**Describe the issue:**
When configuring the Sample OIDC Java EE web app[1] according to our documentation, getting the following error after clicking the Login button. 
<img width="1031" alt="image" src="https://github.com/wso2/product-is/assets/47671237/92e1e287-6b56-44b4-a9e3-6b1fd58d0c99">

This issue can be seen in the Sample SAML app as well.

**How to reproduce:**
1. Configure the sample OIDC app as instructed in the documentation [2].

**Expected behavior:**
The sample apps should work with IS 7.0.0 and should be able to login properly.

[1] https://github.com/asgardeo/asgardeo-tomcat-oidc-agent/tree/master/io.asgardeo.tomcat.oidc.sample
[2] https://is.docs.wso2.com/en/next/get-started/try-samples/qsg-oidc-webapp-java-ee/

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-7.0.0-beta6
 - Sample app - Asgardeo Tomcat Agent for OIDC Authentication - v0.1.28

**Comment by Thisara-Welmilla** [comment]
Will be fixed with https://github.com/wso2/product-is/issues/19124

**Comment by Thisara-Welmilla** [comment]
This is fixed with latest sample app release tag:4.6.0.

Docs will be updated with https://github.com/wso2/product-is/issues/19303
