### ISSUE TITLE
Password validity period of the imported users should be configurable

### ISSUE THREAD

**Issue by madawas** [wso2/product-is#1936]
**Description:**
According to the doc [1] the default password for the imported users are valid only for 24 hours and it is not configurable. This should be made a configurable parameter.

**Suggested Labels:**
Type/Improvement, Severity/Minor, Priority/High

**Affected Product Version:**
IS-540

[1] - https://docs.wso2.com/display/IS530/Configuring+Users#ConfiguringUsers-Importingusers

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
