### ISSUE TITLE
No failure response for incorrect or non-existing policy version

### ISSUE THREAD

**Issue by chaminda** [wso2/product-is#1937]
**Steps to Recreate:**
1. Invoke operation(pubishToPDP) of EntitlementPolicyAdminService with incorrect or non-existing version of the policy.
Below is the sample request.
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:publishToPDP>
         <!--Zero or more repetitions:-->
         <xsd:policyIds>sample_policy_template</xsd:policyIds>
         <!--Optional:-->
         <xsd:action>CREATE</xsd:action>
         <!--Optional:-->
         <xsd:version>1.0</xsd:version>
         <!--Optional:-->
         <xsd:enabled>false</xsd:enabled>
         <!--Optional:-->
         <xsd:order>2</xsd:order>
      </xsd:publishToPDP>
   </soapenv:Body>
</soapenv:Envelope>
```
**Actual Result:**
User getting success response(200) with the content which is exactly same for valid version.
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns:publishToPDPResponse xmlns:ns="http://org.apache.axis2/xsd">
         <ns:return xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
      </ns:publishToPDPResponse>
   </soapenv:Body>
</soapenv:Envelope>
```
**Expected Result:**
Once user provided an invalid or non-existing version of policy, the admin service should return the error response(404) and meaningful message to the user

**Comment by ruwanta** [comment]
Duplicate ?
https://github.com/wso2/product-is/issues/1939

**Comment by chaminda** [comment]
Added this for failing the test case of invalid version for publishToPDP operation.
#1939 for non-existing policy when invoke the dePromotePolicy but it seems the root cause is same for both as explained in #1939

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
