### ISSUE TITLE
Issue when selecting the Passive STS User ID location

### ISSUE THREAD

**Issue by himeshsiriwardana** [wso2/product-is#19371]
**Describe the issue:**
When creating a WS-Federation custom connection, there is an issue when selecting the location of the user identifier.

**How to reproduce:**
1. Create a custom connection.
2. On the created custom connector, go to the **Settings** tab..
3. Click **New Authenticator**, select **WS-Federation** and click **Next**.
4. Check the Passive STS User ID Location checkbox and uncheck again to find the 2 options.

https://github.com/wso2/product-is/assets/31583807/1e2a9862-f8a6-4db7-a666-1b4a410429f3

**Expected behavior:**
Radio buttons to select one of the 2 buttons as shown below for IS 6.1
<img width="871" alt="image" src="https://github.com/wso2/product-is/assets/31583807/6a9fc7e6-cc76-4662-b9bf-3a0581e9ffa8">

**Comment by dasuni-30** [comment]
### Verified in the latest pack

https://github.com/wso2/product-is/assets/27746285/1acd7a55-65a4-4107-aceb-edd1de92bb67
