### ISSUE TITLE
Users view has inconsistencies with secondary userstores

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#19374]
**Describe the issue:**
Getting the option to create a user when readonly userstore is selected from the userstore drop down.

![image](https://github.com/wso2/product-is/assets/5061791/cffdb134-6e7f-40e3-a270-9d191db99d8a)

![image](https://github.com/wso2/product-is/assets/5061791/25309638-4896-43f0-bb70-9e04d7eafc54)

Search and Filter bars disappear once you select the user store that doesn't have any users 
 
**How to reproduce:**
Create a new readonly userstore that doesn't have users
goto users view and select the respective userstore from the drop down

**Expected behavior:**

1. Search and Filter bars should be available in the screeen
2. For readonly userstore the description should not say to add new users.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
When the user select a userstore without any user, the ideal experience would be to display the search and filter segment without the search bar.

**Comment by indeewari** [comment]
I think 
1. The user store filter should be there for both of the user stores regardless user exists or not
2. "Add a new user" description and the "Add user" button should not be there for the **read-only user store**.
3. Search bar display depends on whether there are user exist or not.

**Comment by DilshanSenarath** [comment]
This issue will be resolved through PR https://github.com/wso2/identity-apps/pull/5437 for both the `users` and `groups` sections. When there are no users in the selected user store, search and filter options will be disabled, while the user store dropdown will remain functional. If the user store is `read-only`, the `add user` text and related actions will be removed. Refer to the following videos.

### Without users

https://github.com/wso2/identity-apps/assets/74205483/6280e5c0-2f94-47e5-999d-64508feb1d07

### With users

https://github.com/wso2/identity-apps/assets/74205483/34c21d7a-27a3-4e23-ad1e-efe206df5091
