### ISSUE TITLE
Policy version reference is not consistent over the operations in EntitlementPolicyAdminService

### ISSUE THREAD

**Issue by chaminda** [wso2/product-is#1938]
**Details:**
```
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"  PolicyId="sample_policy_template" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
...
...
</Policy>
```
Above sample policy we can see the version of the policy refers as 1.0 and this is same for createPolicy operation as well. But in other operations like publishToPDP, getPolicyByVersion, etc., the version is referred as 1(other than 1.0)

**Expected Result:**
Version reference should be consistent all over the operations in the EntitlementPolicyAdminService.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
