### ISSUE TITLE
[Secondary User Store][ApacheDS 2.0][B2B] Cannot invite to  a user in a secondary user store in the parent organization

### ISSUE THREAD

**Issue by indeewari** [wso2/product-is#19390]
**Describe the issue:**
User not found error for the secondary user store user in the parent organization.

<img width="1346" alt="image" src="https://github.com/wso2/product-is/assets/4128062/46512487-494a-462e-b9b5-dab624e8efd4">

**How to reproduce:**
1. Create a sub organization named IAM in the parent organization.
2. Connect a readonly LDAP secondary user store.
3. Create a role named "Notification" in the parent org and apply that to a user named "tom" from the secondary user store
4. Go to the IAM sub organization
5. Invite tom to the "IAM" sub org
6. Invitation fails with "User not found error"
`curl 'https://localhost:9443/t/carbon.super/o/api/server/v1/guests/invite' \
  -H 'Access-Control-Allow-Origin: https://localhost:9443/t/carbon.super/o/762fb0fd-2ee3-48e5-af57-b505f7bd2ca0/console' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer;' \
  -H 'Authorization: Bearer a404da9e-e88a-3bec-b5ed-93687cd9c958' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw '{"roles":["1d870276-fb31-413c-a53d-eb20cd4dd1b3"],"usernames":["tom"]}' \
  --compressed \
  --insecure`

**Response**

`[
    {
        "username": "tom",
        "result": {
            "status": "Failed",
            "errorCode": "OUI-10011",
            "errorMessage": "Invalid user identification provided.",
            "errorDescription": "Could not find an user with given username."
        }
    }
]`

**Expected behavior:**
Have to support uses invite to a user in a secondary user store in B2B flows.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 7 Beta 6]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
To initiate this invitation getting the parent org user’s username is done through an offline communication. In such communication letting know the userstore of the user is not intuitive and the userstore is an internal detail for SaaS business. Hence this will not be visualized in the console.
