### ISSUE TITLE
Getting Bad Request when a user tries to sign in with Google authenticator.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19400]
**Describe the issue:**
Encountering `400 Bad Request` for Federated-Associations Request When Signing In with Google Authenticator, Alongside `Something Went Wrong` Errors While Navigating to Other Pages.

Special note -> When JIT is enabled the issue won't occur.

<img width="860" alt="Screenshot 2024-02-06 at 11 55 08" src="https://github.com/wso2/product-is/assets/41188245/2a2f6221-5a79-4005-9dc1-8ee9d703c225">

<img width="860" alt="Screenshot 2024-02-06 at 11 54 25" src="https://github.com/wso2/product-is/assets/41188245/643ab6bc-e987-4105-8991-c383c9b9ab20">

<img width="860" alt="Screenshot 2024-02-06 at 11 57 55" src="https://github.com/wso2/product-is/assets/41188245/161ce092-1b62-4752-ab74-2a5f356822b9">

https://github.com/wso2/product-is/assets/41188245/4230f0f0-a219-4a78-ab92-52f3fe80a0e8

**How to reproduce:**

1.  Create a Google connection
2.  Add Google to the sign in flow in a selected application
3. Try to sign in using Google authenticator.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by melanisilva** [comment]
Stack trace error ->

**Comment by malithie** [comment]
This scenario is less likely and practical requirements to just have google login without requirements to manage account is almost zero.
However, login should be smooth and there should not be errors like this.
The UI may indicate no linked account, no managed profile etc

**Comment by brionmario** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/5553

**Comment by JayaShakthi97** [comment]
Decided to gracefully handle the users without a local account.
Fix:
- https://github.com/wso2/identity-apps/pull/5553
