### ISSUE TITLE
[Migration] Add using PKCS12 keystores as default primary keystore and truststore

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#19407]
With https://github.com/wso2/product-is/issues/18466, we have update the default keystore and truststore types to the PKCS12 from JKS. 

Need to educate the user that the default keystore and trustore type for super tenant and for newly creating tenants have been changed. Therefore they have to one of following options.

1. [Recommended] Convert existing JKS keystores (not required for existing tenants other than super tenant) to PKCS12 format and change usage according.

**Additional context**
To convert an existing JKS keystore to PKCS12, following command can be used
```
keytool -importkeystore -srckeystore wso2carbon.jks -destkeystore wso2carbon.p12 -srcstoretype JKS -deststoretype PKCS12 -deststorepass wso2carbon
```

2. Use the following config in deployement.toml to use JKS keystores:

For super tenant:
```
[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"
type="JKS"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"
```

**Comment by Thisara-Welmilla** [comment]
Please refer https://docs.google.com/document/d/1N7N6VoZk4N2_m-ZUWAz3Zp5YYBANSFgiLVBFH1orWuM/edit#heading=h.71gqxxef48q7

**Comment by Thisara-Welmilla** [comment]
Wi

**Comment by hwupathum** [comment]
> With #19517, default keystore is changed to JKS format. Hence this migration is not required now.

This happended due to https://github.com/wso2/product-is/issues/19506

**Comment by hwupathum** [comment]
Re opening for IS 7.1 release

**Comment by nilasini** [comment]
Migration docs has been updated with the above details. Please verify and close it

**Comment by hwupathum** [comment]
Only the default keystore type of primary keystore and trustrore has been changed, the keystore type of other tenants is still JKS.
