### ISSUE TITLE
Proper validation message should be shown for password reset page

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1940]
*Environment*
```
IS 5.4.0
Ubuntu 14
Java version "1.8.0_51"
Firefox 55
DB - MySQL
```
**Issue**
After configuring [1\] tried to provide a new password with a space character in the password. The validation message shown does not reflect. It says enter password with 5 - 30 characters ( where the new password already had 7 characters)

![incorrectvalidationmsg](https://user-images.githubusercontent.com/17248809/34374727-8b174946-eb08-11e7-8daf-e9aaec84c8d9.png)

[1\] [https://docs.wso2.com/display/ISCONNECTORS/Configuring+Password+Policy+Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Password+Policy+Authenticator)

**Labels** IS 5.4.0 , Bug

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
