### ISSUE TITLE
Getting 404 for  password expired user identification API

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19411]
**Describe the issue:**
Try 
```
curl --location 'https://localhost:9443/api/server/v1/expired-password-identification/password-expired-users?expiredAfter=2024-03-01&excludeAfter=2024-03-30' \
--header 'Accept: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

It fails with 404.
The same error is coming even if the password expiration feature is enabled and keep some users whose password get expired within the range

**Comment by janakamarasena** [comment]
The path should be https://localhost:9443/api/server/v1/password-expired-users however that call gets currently blocked due to resource access control restrictions as thats added to the path `/expired-password-identification/password-expired-users`
