### ISSUE TITLE
'Notify user when lock time is increased'  option is not available in the console

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#19419]
Need to bring support for the above option in a way that the user will be notified when the lock time is increased.

**Comment by NipuniBhagya** [comment]
Initially, this was removed as it was decided we needed to enable this by default for improved UX. However, if we are giving the UI capability we need to make sure that the user gets notified once the account lock duration is increased. @DilshanSenarath will have a look into this. 

CC: @ayshsandu @malithie @madurangasiriwardena
