### ISSUE TITLE
[Doc] Explain what "Subject Identifier step" and "Attribute step" means

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1941]
in [1\] Step 7 we very briefly explain what "Subject Identifier step" and "Attribute step" means. Can we give some more information in the areas of what it exactly means and how it is used? Or provide a link to a doc if it's already elaborated in another topic.

[1\] [https://docs.wso2.com/display/IS540/Multi-factor+Authentication+for+WSO2+IS](https://docs.wso2.com/display/IS540/Multi-factor+Authentication+for+WSO2+IS)

Labels : Docs 5.4.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
