### ISSUE TITLE
Doc Feedback: Issue in the OAuth2.0 Pushed Authorization requests (PAR) Diagram

### ISSUE THREAD

**Issue by CharinduThisara** [wso2/product-is#19418]
Location : https://is.docs.wso2.com/en/next/references/pushed-authorization-requests/

Step Number 04 is missing.

![image](https://github.com/wso2/product-is/assets/114144341/7895bdbe-d0cc-4864-bba1-03c0e14b15ee)

**Comment by himeshsiriwardana** [comment]
This is fixed: https://is.docs.wso2.com/en/next/references/pushed-authorization-requests/
