### ISSUE TITLE
Observed an ERROR log  while gracefully restarting the IS server when it was serving requests

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1942]
*Environment*
```
IS 5.4.0
Ubuntu 14
Java version "1.8.0_51"
Firefox 55
DB - h2
```
**Issue**
IS was configured with a SP ( travelocity ) with basic auth. While requests to login was continuosly flowing gracefully restarted the IS server. On the shutting down process observed the below error.

**_TID: [-1234] [] [2017-12-28 14:49:03,282] ERROR {org.apache.catalina.loader.WebappClassLoaderBase} -  The web application [/shindig] appears to have started a thread named [com.google.inject.internal.util.$Finalizer] but has failed to stop it. This is very likely to create a memory leak._**

`TID: [-1234] [] [2017-12-28 14:48:00,869]  INFO {org.wso2.carbon.core.ServerManagement} -  Starting to switch to maintenance mode... 
TID: [-1234] [] [2017-12-28 14:48:00,906]  INFO {org.wso2.carbon.core.ServerManagement} -  Stopped all transport listeners 
TID: [-1234] [] [2017-12-28 14:48:00,907]  INFO {org.wso2.carbon.core.ServerManagement} -  Waiting for request service completion... 
TID: [-1234] [] [2017-12-28 14:49:00,992]  WARN {org.wso2.carbon.core.ServerManagement} -  Timeout occurred even though there are active connections. 
TID: [-1234] [] [2017-12-28 14:49:00,992]  INFO {org.wso2.carbon.core.ServerManagement} -  All requests have been served. 
TID: [-1234] [] [2017-12-28 14:49:00,992]  INFO {org.wso2.carbon.core.ServerManagement} -  Waiting for deployment completion... 
TID: [-1234] [] [2017-12-28 14:49:01,390]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/STRATOS_ROOT] 
TID: [-1234] [] [2017-12-28 14:49:01,677]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/mex] 
TID: [-1234] [] [2017-12-28 14:49:01,900]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/emailotpauthenticationendpoint] 
TID: [-1234] [] [2017-12-28 14:49:02,269]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api/identity/entitlement] 
TID: [-1234] [] [2017-12-28 14:49:02,757]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/oauth2] 
TID: [-1234] [] [2017-12-28 14:49:02,938]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api/identity/user/v0.9] 
TID: [-1234] [] [2017-12-28 14:49:03,009]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/scim2] 
TID: [-1234] [] [2017-12-28 14:49:03,282] ERROR {org.apache.catalina.loader.WebappClassLoaderBase} -  The web application [/shindig] appears to have started a thread named [com.google.inject.internal.util.$Finalizer] but has failed to stop it. This is very likely to create a memory leak. 
TID: [-1234] [] [2017-12-28 14:49:03,289]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/shindig] 
TID: [-1234] [] [2017-12-28 14:49:03,329] ERROR {org.apache.catalina.loader.WebappClassLoaderBase} -  The web application [/api/identity/oauth2/dcr/v1.0] appears to have started a TimerThread named [Timer-5] via the java.util.Timer API but has failed to stop it. To prevent a memory leak, the timer (and hence the associated thread) has been forcibly canceled. 
TID: [-1234] [] [2017-12-28 14:49:03,336]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api/identity/oauth2/dcr/v1.0] 
TID: [-1234] [] [2017-12-28 14:49:03,383]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api/identity/recovery/v0.9] 
TID: [-1234] [] [2017-12-28 14:49:03,417]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api/identity/oauth2/v1.0] 
TID: [-1234] [] [2017-12-28 14:49:03,453]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/authenticationendpoint] 
TID: [-1234] [] [2017-12-28 14:49:03,481]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/mexut] 
TID: [-1234] [] [2017-12-28 14:49:03,503]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/smsotpauthenticationendpoint] 
TID: [-1234] [] [2017-12-28 14:49:03,530]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/accountrecoveryendpoint] 
TID: [-1234] [] [2017-12-28 14:49:03,553]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/x509certificateauthenticationendpoint] 
TID: [-1234] [] [2017-12-28 14:49:03,584]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/wso2] 
TID: [-1234] [] [2017-12-28 14:49:03,600]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/dashboard] 
TID: [-1234] [] [2017-12-28 14:49:03,617]  INFO {org.wso2.carbon.webapp.mgt.WebApplication} -  Unloaded webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/portal] 
TID: [-1234] [] [2017-12-28 14:49:03,617]  INFO {org.wso2.carbon.core.ServerManagement} -  All deployment tasks have been completed. 
TID: [-1234] [] [2017-12-28 14:49:03,617]  INFO {org.wso2.carbon.core.ServerManagement} -  Waiting for server task completion... `

**Labels** IS 5.4.0 , Bug

**Comment by omindu** [comment]
This can occur when undeploying webapps. As this is during server shutdown there's no real harm here. Please refer [1].

[1] - https://stackoverflow.com/a/6025294

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
