### ISSUE TITLE
[Docs] Custom OAuth 2.0 Grant Type - Sample response incorrect

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#19421]
The `token_type` in the response is set as “mobile” from the sample app[1] and the response token received contains `token_type: mobile`, but it is shown as ‘token_type: bearer’ in the documentation.

Documentation
<img width="964" alt="Screenshot 2024-02-07 at 11 09 38 AM" src="https://github.com/wso2/product-is/assets/62496951/4d377c3d-2d11-4e5d-a2d1-670da023f2e8">

Actual Resonse
```
{
    "access_token": "d9b46507-0300-4a8e-839f-0b856a64c481",
    "refresh_token": "45a82bd4-ef55-4368-bc20-9cbc340308d1",
    "token_type": "mobile",
    "expires_in": 10000
}
```

[1] https://github.com/wso2/samples-is/blob/master/oauth2/custom-grant/src/main/java/org/wso2/sample/identity/oauth2/grant/mobile/MobileGrant.java#L102

**Comment by himeshsiriwardana** [comment]
This is verified to be already fixed: https://github.com/wso2/product-is/issues/19421
