### ISSUE TITLE
UX improvements related to IDP groups section

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#19431]
**Describe the issue:**
Currently we are providing following UI for IDP group attribute setting.
<img width="1052" alt="idp-groups" src="https://github.com/wso2/product-is/assets/56070320/fb0b0053-2b4c-4c6a-8fbd-1b9b8d48272d">

We need to improve the UX so that,
- When there are no custom claim mappings, IDP group attribute should be shown in the read only mode with the corresponding value. (For example: for OIDC connections, group attribute in OIDC default claim dialect should be shown. for SAML connections, group attribute in local claim dialect should be shown .)
- When there are custom mappings, federated IDP attribute mapped to the local group claim should be shown as the IDP group attribute and should display a notice to configure claim mapping for local group claim as IDP group attribute if it is not already configured. Additionally, we should have an update option to the IDP group attribute and should give a caution informing that it will change the current claim mapping of the local group claim when trying to update the IDP group attribute.

Also this UX should be handled for `federated.idp.use_idp_role_claim_as_idp_group_claim` config as well.

**Comment by JayaShakthi97** [comment]
UX improvement:
- https://github.com/wso2/identity-apps/pull/5473

**Comment by JayaShakthi97** [comment]
New requirements were raised. Hence reopening the issue.

**Comment by JayaShakthi97** [comment]
Further improvements were introduced with:
- https://github.com/wso2/identity-apps/pull/5514

**Comment by JayaShakthi97** [comment]
Verified in the latest `wso2is-7.0.0-beta7-SNAPSHOT`
