### ISSUE TITLE
Request object signature and encryption validations can be just skipped, by just sending a plain request object.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#1943]
Service provider should be able to enforce signature and encryption validation on request object.
As per [1] we are only validating the request object, if it's signed or encrypted. If not we simply pass the plain request object. This fails to support the purpose of using request object signing and encryption.
, which is to verify the authenticity and integrity of the request object content.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/RequestObjectValidatorImpl.java#L178-L188

`    @Override
    public void validateRequestObject(String requestObject, OAuth2Parameters oAuth2Parameters)
            throws RequestObjectException {

        if (!OAuth2Util.isValidJson(requestObject)) {
            String[] jwtTokenValues = requestObject.split("\\.");
            if (jwtTokenValues.length == NUMBER_OF_PARTS_IN_JWS) {
                processRequestObject(jwtTokenValues);
                validateSignature(requestObject);
            } else if (jwtTokenValues.length == NUMBER_OF_PARTS_IN_JWE) {
                decrypt(requestObject, oAuth2Parameters);
            }
        }`

**Comment by mefarazath** [comment]
Improvement added with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/792
Refer: https://docs.wso2.com/display/IS550/Enforcing+Signature+Validation+for+Request+Objects
