### ISSUE TITLE
Remove identity verification related APIs by default from the product

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19430]
**Describe the issue:**
At the moment IDV feature is not available in new console or legacy management console
Disabled the feature in new console by https://github.com/wso2/carbon-identity-framework/pull/4966

Therefore ideally, the related APIs also should not be available in the product by default.

<img width="992" alt="Screenshot 2024-02-07 at 14 28 08" src="https://github.com/wso2/product-is/assets/25483865/ba875223-9894-4dd6-bc67-232aa890e11c">

Suggestion : 

Remove API resources in 
- https://github.com/wso2/carbon-identity-framework/blob/56a49c33ab428bc9bd1131e26395ecd6f8a37f10/features/api-resource-mgt/org.wso2.carbon.identity.api.resource.mgt.server.feature/resources/system-api-resource.xml.j2#L533
- https://github.com/wso2/carbon-identity-framework/blob/56a49c33ab428bc9bd1131e26395ecd6f8a37f10/features/api-resource-mgt/org.wso2.carbon.identity.api.resource.mgt.server.feature/resources/system-api-resource.xml.j2#L281

and relevant access controls in https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/resource-access-control-v2.xml.j2

**Comment by Thisara-Welmilla** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5484
