### ISSUE TITLE
No validation for  inactiveAfter value greater than excludeBefore value in idle users identification API

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19436]
**Describe the issue:**

Try this API with the following conditions
1.  inactiveAfter value greater than excludeBefore
2. inactiveAfter value less than excludeBefore
https://is.docs.wso2.com/en/next/apis/idle-accounts-identification-rest-api/#tag/Get-inactive-users/operation/getInactiveUsers

Ideally `inactiveAfter value less than excludeBefore` case should return 400, but getting 200 response

**Comment by Thisara-Welmilla** [comment]
Fixed with https://github.com/wso2/identity-api-server/pull/590
