### ISSUE TITLE
Introduce UI scopes for organization level

### ISSUE THREAD

**Issue by DonOmalVindula** [wso2/product-is#19446]
**Is your suggestion related to a experience ? Please describe.**
Currently we use the same UI scopes (Ex: `console:applications`) for both tenant and organization level permissions. But this can lead to unintended behaviour where certain UI elements will be visible for organization without explicitly granting the UI scope permissions as they are common for both.

This also have lead to limitations such as https://github.com/wso2/product-is/issues/19040#issuecomment-1929486749. 

https://github.com/wso2/product-is/assets/25959096/461ef4e0-fde2-43e3-9856-326574dca96c

Due to these issues, it is better to have UI scopes for organization level as well, similar to other scopes.

**Describe the improvement**
Introduce new UI scopes for organizations such as `console:org:applications` and tenant level scopes as `console:applications`

This will require some effort in both BE and FE aspects.

**Additional context**
Related issue - https://github.com/wso2/product-is/issues/19040

**Comment by PasinduYeshan** [comment]
From the BE side, new api resources have to be introduced for the required console org scopes as follows.

```
<APIResource name="Application Management Feature" identifier="console:org:applications"
                 requiresAuthorization="true"
                 description="Resource representation of the Application Management Feature"
                 type="CONSOLE_ORG_FEATURE">
        <Scopes>
            <Scope displayName="Application Feature" name="console:org:applications" 
                    description="Manage applications from the Console in  the organization"/>
        </Scopes>
    </APIResource>
 ```

Further,  the `api-resource-collection.xml` has to be updated with the introduced scopes.

**Comment by DonOmalVindula** [comment]
The effort from the FE aspect are as follows.
- Need to refactor the `hasRequiredScopes()` function to accept `console:featureName` scopes in root organizations and `console:org:featureName` scopes in sub organizations similar to `internal_featureName` and `internal_org_featureName`
- Test and verify thoroughly that RBAC console is working as expected in both root orgs and sub orgs.

Approximate time for the effort - 1 working day

**Comment by DonOmalVindula** [comment]
Closing as this is completed
