### ISSUE TITLE
[Custom Connector] Extra Components Loaded on Custom Connector Settings Page After Settings Update

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19449]
**Describe the issue:**
$Subject
<img width="992" alt="Screenshot 2024-02-08 at 11 55 17" src="https://github.com/wso2/product-is/assets/41188245/bbaef444-b619-474a-8a16-9052c03ff012">

https://github.com/wso2/product-is/assets/41188245/5e45c65b-9542-42f3-a4f0-6a4ad675edc3

**How to reproduce:**

1. Create a new custom connector 
2. Add an Authenticator from settings page and continue with [linkedIn connector ](https://github.com/wso2/product-is/issues/19347#issuecomment-1928815944)
3. Fill the relevant data and Finish
4. After the authenticator is added Update a value and submit.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 Beta7 Snapshot
 - OS: [e.g., Windows, Linux, Mac]
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
### Verified in the latest pack

https://github.com/wso2/product-is/assets/27746285/62317a68-7637-45b0-8f5c-ef71ea4476b9
