### ISSUE TITLE
SMS sent for Mobile attribute verification on update does not contain OTP

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#19441]
**Describe the issue:**
The SMS sent when mobile attribute verification is enabled after updating the mobile number of the user does not contain the OTP.
Only the payload configured in the SMS provider settings is sent.
Configured payload
<img width="1003" alt="Screenshot 2024-02-08 at 11 53 26 AM" src="https://github.com/wso2/product-is/assets/62496951/a8d31693-312c-4ffb-9200-fa4e50717e32">

SMS received in webhook.site after updating the mobile number of a user
<img width="292" alt="Screenshot 2024-02-08 at 11 54 01 AM" src="https://github.com/wso2/product-is/assets/62496951/e377f40b-db42-4b06-bddf-56ea39da3e39">

**How to reproduce:**
1. Enable mobile verification on update through the API
```
curl --location --request PATCH 'https://localhost:9443/t/carbon.super/api/server/v1/identity-governance/T3RoZXIgU2V0dGluZ3M/connectors/dXNlci1jbGFpbS11cGRhdGU' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Cookie: JSESSIONID=8FFF77140B4AF828B5E4BC28C2498038' \
--data '{
  "operation": "UPDATE",
  "properties": [
    {
      "name": "UserClaimUpdate.MobileNumber.EnableVerification",
      "value": true
    },
    {
      "name": "UserClaimUpdate.MobileNumber.EnableVerificationByPrivilegedUser",
      "value": true
    }
  ]
}'
```
2. Setup the SMS provider using webhook.site [1]
3. Update the mobile number and observe the message received in the webhook

[1] https://docs.google.com/document/d/1bmkXCDiT8tvTEk9fSkXjoZyCFTjUhWA9OQ55n1Q1VOE/edit#heading=h.c17n3vfklebo

**Expected behavior:**
1. The OTP should be received.
Given below is the sms received when using SMS OTP for login
<img width="434" alt="Screenshot 2024-02-08 at 11 54 11 AM" src="https://github.com/wso2/product-is/assets/62496951/77fe8f1b-75b2-4392-b133-1096aa3ece09">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0-beta7
 - OS: Mac

**Comment by janakamarasena** [comment]
My guess is that 760269 in the payload received screenshot is the otp
