### ISSUE TITLE
Unable to call the token endpoint with client_assertion_type jwt-bearer and grant type

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#1945]
Hi All

When trying to call the token endpoint by using the refresh token grant type and client_assertion_type **urn:ietf:params:oauth:client-assertion-type:jwt-bearer.** The system prints invalid_request', description='Missing parameters: client_secret client_id

 In this request I am not passing the Authorization: Basic <Base64Encoded(Client_Id:Client_Secret)>. When I invoke the below sample with the necessary values

steps i followed to get  the refresh token
1.use the client credentials grant type and get an access token
2.use the access token and get an AccountRequestId
3.Using the AccountRequestId in the signed request object call the Authorize Endpoint and get an access token and a refresh token
4.pass the refresh token to the below sample

curl -k -d "grant_type=refresh_token&refresh_token=**<refresh-token>**&scope=am_application_scope accounts&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=**<jwt-assertion>**" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8"  -H "Content-Type: application/x-www-form-urlencoded" https://192.168.48.106:8243/TokenAPI/v1.0.0/

Logs and identity.xml
[identity.zip](https://github.com/wso2/product-is/files/1594304/identity.zip)

**Comment by shavantha** [comment]
[identity.zip](https://github.com/wso2/product-is/files/1594306/identity.zip)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
