### ISSUE TITLE
Improper error message is returned while retrieving access tokens when password reset is forced by admin

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#1946]
Enabled password reset via email notification. Then admin force password reset by setting the respective password reset claim. While the account is locked invoke an access token request with password grant type.
The error response does not indicate a meaningful reason for the error.

`{"error_description":"Error when handling event : PRE_AUTHENTICATION","error":"invalid_grant"}`

Each even handler registered for identity management should return an IdentityEventException with a proper error code and a meaningful error message.
IdentityMgtEventListener should include the error code and the message thrown from the handler in the exception [1]

[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.governance/src/main/java/org/wso2/carbon/identity/governance/listener/IdentityMgtEventListener.java#L609

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
