### ISSUE TITLE
No description about 'Mandatory pushed Authorization" requests

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#19488]
<img width="807" alt="image" src="https://github.com/wso2/product-is/assets/12690906/d9cee137-f83f-48b4-9ebc-9ad1d27df063">

The document  [1] should contain the details about above configuration

**Comment by himeshsiriwardana** [comment]
PAR config is now added to References > App Configurations > OIDC Configurations

https://is.docs.wso2.com/en/next/references/app-settings/oidc-settings-for-app/#pushed-authorization-requests-par
