### ISSUE TITLE
[Improvement] When adding a claim which is already existing from admin service proper response message/code to be shown

### ISSUE THREAD

**Issue by jsonds** [wso2/product-is#1948]
When adding a local claim which is already existing from admin service proper response message/code to be shown. Currently it returns with error code 500 and the response is as below.

`?xml version='1.0' encoding='UTF-8'?>    soapenv:Server  Error while adding claim http://wso2.org/claims/lastPasswordChangedTimestamp to dialect http://wso2.org/claims `  

Labels - IS 5.4.0, Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
