### ISSUE TITLE
Onboard the organization-wise JWT Token re-use config.

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#19502]
Onboard the organization-wise JWT Token re-use config.
<img width="1508" alt="image" src="https://github.com/wso2/product-is/assets/12690906/634f0427-294c-4158-ae5f-3156fa65a97c">

**Comment by JayaShakthi97** [comment]
UI will be enabled with;
- https://github.com/wso2/identity-apps/pull/5484
