### ISSUE TITLE
Performance drop when the keystore type changed to PKCS12

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#19506]
**Describe the issue:**
When the default keystore type changed from JKS to PKCS12 a significant performance drop can be seen. 

Keystore type = PKCS12
![Screenshot 2024-02-12 at 15 57 04](https://github.com/wso2/product-is/assets/47152272/32d135e4-e7e4-457e-aa2a-6603896341a3)

Keystore store = JKS

![Screenshot 2024-02-12 at 15 57 13](https://github.com/wso2/product-is/assets/47152272/adcbd352-0d5c-47b1-9ab1-0118d481b9d1)

**How to reproduce:**
1. Download IS [7.0.0-beta6 pack](https://github.com/wso2/product-is/releases/download/v7.0.0-beta6/wso2is-7.0.0-beta6.zip).
2. Change the deployment.toml config.

```
[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"
type="JKS"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"
```

3. Add wso2carbon.jks and  and client-truststore.jks files to the following directory.
/repository/resources/security/

(You can get these files from [7.0.0-beta5](https://github.com/wso2/product-is/releases/download/v7.0.0-beta5/wso2is-7.0.0-beta5.zip) pack)

Related issues:
- https://github.com/wso2/product-is/issues/16517

**Comment by hwupathum** [comment]
Closing since using BC provider has solved the performance issue
