### ISSUE TITLE
Unable to set the name of the Custom SMS Provider

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#19519]
**Describe the issue:**
The name of the custom SMS provider can be set in the configs but it is always defaulting to "Custom". When checking the network trace its seen that we are always sending the name as "Custom".

Additionally note that the "Content Type" is mandatory when trying to save the config but its not marked as mandatory in the UI.

https://github.com/wso2/product-is/assets/11583571/5d93c710-47a8-4228-989f-58fe73203083

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta7-SNAPSHOT

**Comment by JayaShakthi97** [comment]
Fix:
- https://github.com/wso2/identity-apps/pull/5499

**Comment by JayaShakthi97** [comment]
Verified in latest `wso2is-7.0.0-beta7-SNAPSHOT`

![image](https://github.com/wso2/product-is/assets/37938529/3e5e8577-d360-4c2f-9aad-e07abea65b0d)

**Comment by brionmario** [comment]
There was a regression with the fix , hence we need to revert and figure out the use case of this `name` attribute and hide if redundant.

Issue to fix the regression: https://github.com/wso2/product-is/issues/19601

**Comment by JayaShakthi97** [comment]
Since no usecase was found for the "SMS Provider name" property, it was decided to remove the field from the UI.
For Custom SMS Provider, provider property will be hardcoded to "Custom"
- https://github.com/wso2/identity-apps/pull/5528
