### ISSUE TITLE
Admin user should be able to revoke authorized applications of other users 

### ISSUE THREAD

**Issue by GayanM** [wso2/product-is#1951]
Simply admin user should be able to revoke access tokens issued for other users

**Comment by SachithUd** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/750

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
