### ISSUE TITLE
OAuth2 Performance improvements to refresh grant flow

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-is#1952]
We need to include following two indexes to default identity db scripts shipped with product. Those will add considerable improvement to the refresh token generation time  when there are large number of entries in the tables.

CREATE INDEX IDX_RT ON IDN_OAUTH2_ACCESS_TOKEN(REFRESH_TOKEN);
CREATE INDEX IDX_TID ON IDN_OAUTH2_AUTHORIZATION_CODE(TOKEN_ID);

**Comment by DMHP** [comment]
The following two indexes are already available, hence closing this issue

CREATE INDEX IDX_AC_TID ON IDN_OAUTH2_AUTHORIZATION_CODE(TOKEN_ID);
CREATE INDEX IDX_AT_RT ON IDN_OAUTH2_ACCESS_TOKEN(REFRESH_TOKEN);
