### ISSUE TITLE
Not receving totalResults,  itemsPerPage and startIndex in v1/me/approval-tasks API response

### ISSUE THREAD

**Issue by DInuwan97** [wso2/product-is#19532]
Hi All,

The current 'v1/me/approval-tasks'[1] endpoint is not returning the totalResults parameters in the API response. Further expected approach is to return itemsPerPage, startIndex etc in the API response.

Expected output

```
{
  "totalResults": <>,
  "startIndex": <>,
  "itemsPerPage": <>

  [<An array of approvals>]
}

```

[1] - https://is.docs.wso2.com/en/5.10.0/develop/approvals-rest-api/#/me/listApprovalTasksForLoggedInUser

Thanks

**Comment by PasinduYeshan** [comment]
This support was provided only for IS 5.10.
