### ISSUE TITLE
"Register Now" link present on default frontpage when self-registration is disabled

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#1954]
to reproduce:

1. install default WSO-IS 5.4.0 installation
2. navigate to `localhost:9443/dashboard` - this will redirect you to the login page
3. see "Register Now" link - click it
4. fill out registration form, and click "REGISTER NOW"
5. receive error message:
`Code : 20021`
`Message :Self sign up feature is disabled`

desired behavior:
* do not show "Register Now" link when this feature is disabled
* do not allow access to registration form when this feature is disabled

recommended labels: `Type/UX`

**Comment by omindu** [comment]
Hi @hauntingEcho,

Enabling/Disabling self-signup feature can be done per tenant. Even if self signup is disabled for one tenant, another tenant may have that feature enabled. The server checks whether the feature is enabled during the user registration after extracting the tenant domain from the registered user name. Therefore, entirely removing the link will not be an option as the feature might be enabled for other tenants.

One improvement would be to do this check while entering the username.

**Comment by hauntingEcho** [comment]
Hi @omindu - that makes sense.  Another possible improvement would be to detect when no tenant has self-signup enabled, and not display the link or allow access to the form

**Comment by sagara-gunathunga** [comment]
As Omindu has explained this is a limitation of current architecture and there is no plan to change this behaviour
