### ISSUE TITLE
Unsharing with a selected organization removes the SSO sign in option from login flow

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#19540]
**Describe the issue:**
Initially an application is shared with multiple organizations. Then the SSO login option is shown in the login flow. Then, when it is unshared from one organization, the SSO login option is automatically removed. And it is also not possible to add the SSO login option.

https://github.com/wso2/product-is/assets/62496951/c471e01b-186a-48c6-98e0-146007a78b60

**How to reproduce:**
1. Share an application with multiple organizations
2. Unshare with one organization
3. Go to the Login flow page and observe that the SSO login option is removed. 

**Expected behavior:**

SSO login option should not be removed as the app is still shared with some organizations. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0-beta7

**Comment by sadilchamishka** [comment]
When an organization is unselected, only shared app delete request should be sent. 
The request which is sent as shared-with-all-children=false and empty list is the reason for this bug. That API call not required to be sent. It only required when an addintional org is added from the list (In that case that added org will be added to that list with the flag is set to true of false based on selecting all or not)

https://github.com/wso2/product-is/assets/35717390/de3258a6-696e-4457-8e84-84916b656037
