### ISSUE TITLE
[Design] Create a logo for challenge questions connector

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#19554]
**Is your suggestion related to an experience ? Please describe.**
From IS 7.0.0 challenge questions feature is removed from the default IS pack and hosting as a connector. We need an icon for the challenge questions connector to publish in the [connector store](https://store.wso2.com/store/assets/isconnector/list) 

sample image:

![Untitled design](https://github.com/wso2/product-is/assets/28682701/fe94c890-cf32-49d7-847f-1f30a97298d4) 

Please add a suitable background color  

Related issue: https://github.com/wso2/product-is/issues/18407

**Comment by savindi7** [comment]
https://www.figma.com/file/9QxyluUvzXAMbTdixve9Dh/Assets?type=design&node-id=2259-17&mode=design&t=lpcz8c82v8lJLrQW-0

<img width="79" alt="Screenshot 2024-02-14 at 10 39 20" src="https://github.com/wso2/product-is/assets/67315176/5a9cc130-a647-42f9-9e2c-55940775065d">

[SVG](https://github.com/wso2/product-is/assets/67315176/53c6f8e0-be40-4cf4-9b78-88d2ffdc4f21)

**Comment by asha15** [comment]
Logo: 
![challenge-questions-connector](https://github.com/wso2/product-is/assets/28682701/8002f575-7ab1-4710-a33c-1165a08b96ff)
