### ISSUE TITLE
[Doc]Include an architecture/flow diagram to explain "Outbound Provisioning with SCIM"

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1955]
[Doc]Include an architecture/flow diagram to explain "Outbound Provisioning with SCIM" scenarion in this doc [1]

[1] https://docs.wso2.com/display/IS540/Outbound+Provisioning+with+SCIM

This will be more clear if a diagram can be included.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
