### ISSUE TITLE
Application sharing issues

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#19561]
**Describe the issue:**

https://github.com/wso2/product-is/assets/35717390/0c343064-f158-4c25-a66f-39207ca029d5

There are two issues explained in above screen recording.
1 - When few orgs are shared, and then click share with all organizations. Then again check the share orgs with selected organizations still shows only the previously shared orgs (Should be react state issue)

2 - When share with all orgs is selected, and then switch to the select the orgs to share menu, and then unselecting an organization from the list cause to call delete all shared apps. 
Actually the `shared-apps` DELETE call only should be invoked when unshare with all organization is selected.

**Expected behavior:**

Only the individual DELETE API calls should be invoked. The API call which is relevant for unsharing all the shared-apps should not be invoked.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS  7.0.0-beta6]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by pavinduLakshan** [comment]
> 2 - When share with all orgs is selected, and then switch to the select the orgs to share menu, and then unselecting an organization from the list cause to call delete all shared apps.
> Actually the `shared-apps` DELETE call only should be invoked when unshare with all organization is selected.

When the sharing access setting is set to "share with all suborgs" and the user tries to unshare an organization, the backend reponds with 400 error.

**Error response**: 

```json
{
    "code": "ORG-60069",
    "message": "Invalid request.",
    "description": "Cannot unshare the application with ID 2a50bfd1-f79b-45a3-ad42-2fa4c262ef76 from the organization with ID 8e26e5f0-cf2b-4c67-953c-75c34eb25ae4 if the application is shared with all children organizations."
}
```

**Comment by dewniMW** [comment]
As mentioned in step 4 of https://github.com/wso2-extensions/identity-organization-management/pull/154#issuecomment-1261620752, the current implementation dictates this behavior, which is expected.

Therefore, it is necessary to align the UI with this behavior by implementing appropriate messaging to indicate the reset action.
