### ISSUE TITLE
Getting cert validate issue

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#19575]
Encountering the following issue in Firefox's incognito mode while attempting to access the console.

We modified the keystore type to JKS during the Jenkins job build `#5067`, and it appears that this issue is not reproducible within that IS pack. This issue can observe from the `#5068` Jenkins job.

Note: It seems that this problem is only reproducible for a few people.

![image](https://github.com/wso2/product-is/assets/82029070/5ab05aea-8403-4078-bb07-f9993ec3042c)

**Comment by UdeshAthukorala** [comment]
Fixed with: https://github.com/wso2/product-is/pull/19581
