### ISSUE TITLE
Multifilter pagination in scim2 search is not working properly for oracle user DB

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#19585]
**Describe the issue:**

When user filtering through two claims with the **count** parameter added for pagination, expected user results are not returned.
Please find the sample request below.
```
curl --location 'https://localhost:9443/scim2/Users/.search' \
--header 'Content-Type: application/scim+json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data '{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "attributes": [
        "name.familyName",
        "userName",
        "name.givenName"
    ],
    "filter": "name.familyName eq di and name.givenName co shehan",
    "domain": "PRIMARY",
    "startIndex": 1,
    "count": 1
}'
```
```
SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, UM_USER_NAME FROM UM_USER U INNER JOIN UM_USER_ATTRIBUTE UA ON U.UM_ID = UA.UM_USER_ID WHERE U.UM_TENANT_ID = ? AND UA.UM_TENANT_ID = ? AND UA.UM_PROFILE_ID = ? AND UA.UM_ATTR_NAME = ? AND LOWER(UA.UM_ATTR_VALUE) LIKE LOWER(?) INTERSECT SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, UM_USER_NAME FROM UM_USER U INNER JOIN UM_USER_ATTRIBUTE UA ON U.UM_ID = UA.UM_USER_ID WHERE U.UM_TENANT_ID = ? AND UA.UM_TENANT_ID = ? AND UA.UM_PROFILE_ID = ? AND UA.UM_ATTR_NAME = ? AND LOWER(UA.UM_ATTR_VALUE) LIKE LOWER(?) ORDER BY UM_USER_NAME) where rownum <= ?) WHERE  rnum > ?))
```
Above DB query will be executed for the for the mentioned scim2 API search request. There, pagination is happening for the 2nd condition only, hence resulting incorrect output. Pagination should happen for total result not for the one condition's result.

**How to reproduce:**

- Create few users with the firstname and lastname claims(filtering claims)
- Among first few created users, assign firstname that uses in the second search condition
- Create another set of users that matches firstname and lastname in both search conditions
- Users may not listed in the scim response even though there are users that satisfy the two search conditions

**Expected behavior:**

- Users should be listed according to search conditions and pagination(count).

**Environment information** 
 - Product Version: [IS 5.11.0]
 - OS: [ Linux]
 - Database: [ H2]
 - Userstore: [JDBC, ORACLE]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Sachin-Mamoru** [comment]
Fix is in public https://github.com/wso2/carbon-kernel/pull/3307
