### ISSUE TITLE
[Doc] Link 'Adding and Configuring a Service Provider' doc in service provider creation section in 'Basic Client Profile with Playground' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1959]
Add 'Adding and Configuring a Service Provider' [1] as a reference under 'Set up the WSO2 OAuth2.0 Playground sample' section for service provider creation in [2]

[1] https://docs.wso2.com/display/IS540/Adding+and+Configuring+a+Service+Provider
[2] https://docs.wso2.com/display/IS540/Basic+Client+Profile+with+Playground

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
