### ISSUE TITLE
Default Password field is disabled in SCIM Provisioning Configuration

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1960]
Default Password field is disabled in SCIM Provisioning Configuration.

When you configure IDP with SCIM provisioning Configuration, default password field is disabled. You cannot input anything. In documentation it says below as it can be configured. 

Please fix this is this is a product issue. Or update the documentation how it can be enabled.

Default Password | The default password that must be sent. | <password>

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
