### ISSUE TITLE
Custom SMS Provider is not working

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#19601]
**Describe the issue:**

With the fix for https://github.com/wso2/product-is/issues/19519, the custom SMS provider name is sent as the `provider` property causing the functionality to break.

**How to reproduce:**

- Add configurations to a Custom provider and inspect the network track.
- Try to use the custom provider.

**Expected behavior:**

Custom provider should work without any issues.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by JayaShakthi97** [comment]
Fix:
- https://github.com/wso2/identity-apps/pull/5526

This will revert the fix sent for https://github.com/wso2/product-is/issues/19519#issuecomment-1945414129
