### ISSUE TITLE
Include a sample how we can see the outbound provisioning a user using scim in the doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1961]
Include a sample how we can see the outbound provisioning a user using scim. Link the relevant page or include a section in this [1] doc. It just talks how to configure. But does not mention a sample of how we can provision a user and view.
 
[1] https://docs.wso2.com/display/IS540/Outbound+Provisioning+with+SCIM

**Comment by ushanib** [comment]
This should include all the permitted operations via SCIM provisioning and how they will behave with sample response. 

How POST/PUT/PATCH/DELETE/GET operations will work in SCIM commands if relevant.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
