### ISSUE TITLE
The functionality for listing groups in a secondary Active Directory is not working

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19620]
**Describe the issue:**
After configuring an Active Directory as a secondary user store, the ability to list groups is not functioning properly. Consequently, creating a user in the Active Directory is also failing due to this issue.

```
Something went wrong
Error in obtaining role names from user store. No group found with the name: Domain Controllers in tenant: -123
```

<img width="1512" alt="Screenshot 2024-02-15 at 15 58 23" src="https://github.com/wso2/product-is/assets/41188245/382c460a-fe24-4b81-a6b9-d4d10cce5c5d">

**How to reproduce:**

1. Configure an Active directory
2. Set is as a Secondary US
3. try to list the AD groups.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by melanisilva** [comment]
As Per @somindatommy 's analysis, The issue here was occurring since the  `Group ID Attribute` value returning from the core is now changed to `entityUUID` where previously the correct value (`objectGUID`) was returned from the metadata. 
With this value being changed to `objectGUID` the flow works as expected.

Better to change the Meta Data to return the default correct value  (`objectGUID`).

**Comment by somindatommy** [comment]
@melanisilva this was not previously there. This is the first time we configured this. Anyway, this is fixed now.

**Comment by UdeshAthukorala** [comment]
This was fixed with: https://github.com/wso2/carbon-kernel/pull/3890
