### ISSUE TITLE
Cannot Edit the Groups configuration in a configured Active directory.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19621]
**Describe the issue:**
When an Active directory is configured cannot edit the Groups section.

<img width="1512" alt="Screenshot 2024-02-15 at 16 08 10" src="https://github.com/wso2/product-is/assets/41188245/68ecdd07-3eb4-460f-8297-1767670d4f6f">

**How to reproduce:**

1. Configure an Active directory
2. Configure it as a Secondary US
3. Navigate to the created Active directory and try to edit configurations in the Groups section

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by UdeshAthukorala** [comment]
Wiil be fixed with: https://github.com/wso2/carbon-kernel/pull/3892
