### ISSUE TITLE
Include the supported operations in salesforce outbound provisioning. 

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1962]
In Salesforce outbound provisioning, we can add a user. But when updating it should clearly mention which fields will be updated according to the claim mapping. 
Also when we delete a user, that operations will not be permitted from Salesforce side. 
Also we should clearly mention how these functionalities will work during SCIM when salesforce outbound provisioning. We can add users via SCIM in to salesforce. But what are the other operations that will be permitted? 

When resolving this issue, document should clearly mention all the relevant information mentioned above in this doc [1]

[1] https://docs.wso2.com/display/IS540/Outbound+Provisioning+with+Salesforce#OutboundProvisioningwithSalesforce-Workingwithusers

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
