### ISSUE TITLE
[Doc] Specify the reason for using the specified 'Callback Url' when configure OAuth/OpenID Connect

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1963]
2nd point under 'Configuring OAuth for WSO2 Playground' section in [1] ask user to specify 'http://wso2is.local:8080/playground2/oauth2client' as the callback url and better to,

- mention the reason for having exact url as the callback url
- mention that the user can change the hostname of the url accordingly without specifying the given one.

[1] https://docs.wso2.com/display/IS540/Basic+Client+Profile+with+Playground

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
