### ISSUE TITLE
[Doc] Incorrect checkout tag mentioned in Downloading a Sample doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1964]
4th step in [1] mentioned the tag to update the empty repository as 'v5.3.0' and it needs to be changed as 'v5.4.0'

[1] https://docs.wso2.com/display/IS540/Downloading+a+Sample

**Comment by ShirazAzad** [comment]
Fixed. (by Shavi)

**Comment by omindu** [comment]
Fixed one more v5.3.0 occurrence as well.
