### ISSUE TITLE
Need logs that describes the root cause for the issue when configuring secondary user stores

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#1965]
Identity Server 5.3
Type: Improvement
Priority: High

**Issue**
This issue has been reported by a customer where he configures a secondary user store and gets the following error when the user profile of a user is retrieved. This is a very generic error message and has lots of causes.
For example,
- The developer who was working on the issue could reproduce when wrong claims are mapped
- But the actual error was in the configuration of the user store where UserNameSearchFilter and GroupNameSearchFilter were incorrectly configured

```
ERROR
{org.wso2.carbon.identity.user.profile.ui.client.UserProfileCient}
- org.wso2.carbon.identity.user.profile.stub.UserProfileMgtServiceUserProfileExceptionException: UserProfileMgtServiceUserProfileExceptionException
```

**Expected**
There is no way to check which claim has been incorrectly mapped as well. Therefore, meaningful and descriptive error messages which describes the actual root cause is expected

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
