### ISSUE TITLE
Account verification is not working as intended

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#19650]
### Description
Users can perform actions that require account verification such as password/username recovery, Email OTP login when both "account verification" and "activate account immediately" is selected. 

![Screenshot 2024-02-16 at 14 20 42](https://github.com/wso2/product-is/assets/27714968/68ef3392-5576-4c46-900c-e622bc821e3b)

### How to reproduce
- Navigate to login and registration section
- Go to self registration and enable both "account verification" and "activate account immediately"
- Create a new user but don't verify the email
- Try to login with email OTP enabled flow
- Try to recover username or password

### Expected behaviour
Users with not verified account should be able to login but be restricted to do actions such as username/password recover, Email OTP etc.

**Comment by janakamarasena** [comment]
This is not a bug but the intended behaviour as documented in https://is.docs.wso2.com/en/latest/guides/account-configurations/user-onboarding/self-registration/

Currently Identity Server does not block user actions based on the account verification status.

**Comment by janakamarasena** [comment]
If you think this sort of capability is needed let's open a feature type issue
