### ISSUE TITLE
 Its better to  add the ssl certificate import command in the cluster document  

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1966]
in the document[1] its mentioned to import  ssl certificate  to client-truststore.jks . Its better to give the example of the commons as below 

`Also, import the ssl certificate used in the nginx to the wso2is-5.3.0/repository/resources/security/client-truststore.jks of the Identity Server nodes.`

`keytool -import -file sever.crt -keystore client-truststore.jks -storepass wso2carbon -alias wso2carbon2`

[1] https://docs.wso2.com/display/IS540/Setting+Up+Deployment+Pattern+1
[2]https://docs.wso2.com/display/IS540/Setting+Up+Deployment+Pattern+2

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
