### ISSUE TITLE
Update RBAC description in Add API resource wizard

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#19678]
**Describe the issue:**

Since we support user to role mappings in IS 7.0, the description given for RBAC has to updated accordingly.

![Screenshot 2024-02-19 at 11 15 11](https://github.com/wso2/product-is/assets/50801227/148d50ca-4bfb-4fb7-8dbe-e23ec6926a4c)

**How to reproduce:**
1. Create an application
2. Move to API resources tab
3. Add new API resource
4. You will be able to see the RBAC description

**Expected behavior:**
The content should contain "role to user mappings" as well.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
Suggestion: `Permission to role and role to group/user mappings will be evaluated during the authorize call.`
