### ISSUE TITLE
[Doc] Link 'Adding and Configuring a Service Provider' doc in service provider creation section in 'Configuring OAuth2-OpenID Connect Single-Sign-On' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1967]
Add 'Adding and Configuring a Service Provider' [1] as a reference under 'Before you begin!' section for service provider creation in [2]

[1] https://docs.wso2.com/display/IS540/Adding+and+Configuring+a+Service+Provider
[2] https://docs.wso2.com/display/IS540/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
