### ISSUE TITLE
Store service provider cert in DB instead of the keystore

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-is#1968]
According to the current service provider implementation, certificates upload into SPs are added to tenant's keystore. When the SPs are created in super tenant space, current model has few drawbacks ..

1. In a IS cluster deployment, keystore syncing mechanism is required between nodes.
2. Server restart is needed since keystore changes are read only at server startup 

Therefore, suggested improvement is to keep SP certs in DB instead of in keystore (similart to IdP certs)

**Comment by rushmin** [comment]
The next immediate release after reporting this fix was IS 5.4.1. Since it is a patch release it has been decided to ship this feature in IS 5.5.0
