### ISSUE TITLE
[Doc][Salesforce] Outbound provisioning connector is not updated in next version

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#19689]
Check out the latest version of the $ here
https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/outbound-provisioning-with-salesforce/#configure-salesforce

following doc is for the same subject for next version.
https://is.docs.wso2.com/en/next/guides/users/outbound-provisioning/salesforce/

There is several sections missed in the next version, with this issue we need to bridge the gap.
Related issue: https://github.com/wso2/product-is/issues/19577

**Comment by himeshsiriwardana** [comment]
This will be covered with this: https://github.com/wso2/product-is/issues/21340
