### ISSUE TITLE
Add support to configure account enable/disable at tenant level

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#19687]
**Describe the issue:**
We need to add support to configure account enable/disable at the tenant level under Login and Registration.

<img width="1387" alt="image" src="https://github.com/wso2/product-is/assets/30111554/ac79de6c-0a52-42d2-8b60-2bc4e68b3c98">

**Comment by JayaShakthi97** [comment]
- UI is implemented.
- TODO: Define scopes for access control.
- https://github.com/wso2/identity-apps/pull/5574

**Comment by JayaShakthi97** [comment]
It was concluded not to introduce a UI to enable/disable this config. Rather there's a consideration to keep this config enabled by default in the pack.
