### ISSUE TITLE
Encountering a 404 Error When Attempting to Update the Custom SMS Provider

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#19694]
**Describe the issue:**
Encountering a 400 error when attempting to update the custom SMS Provider. This problem arises when a customer inputs an invalid `Payload Template`. Subsequently, the SMSPublisher update call may fail immediately or after a few retries.

<img width="1510" alt="Screenshot 2024-02-19 at 16 44 05" src="https://github.com/wso2/product-is/assets/41188245/1aa947c6-eb75-40e9-ad4f-649b60e59d25">

https://github.com/wso2/product-is/assets/41188245/cac8185b-03c1-4023-91af-a4df8ee5b6ee

**How to reproduce:**

1. Create a Custom SMS Provider
2. First enter the correct `Payload Template` as the placeholder value shows. 
3. Then try to enter an invalid one.
4. Then refresh the page and again try to give a valid/invalid value as the `Payload Template` input and submit. (If the immediate PUT call didn't reproduce try 2/3 times. )

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
When the PUT request starts failing, the only option to get it resolved is to restart the server.

As per offline conversation had with @bhagyasakalanka, this seems to be a backend cache issue.

**Comment by Thisara-Welmilla** [comment]
The issue occurred at subsequent request after invalid request is fixed with https://github.com/wso2-extensions/identity-governance/pull/808.

Returning 400 responses for invalid payload template is complex. Hence, it will track with another issue.

As the blocker is fixed with above fix, closing the issue.
