### ISSUE TITLE
[Doc] Missing step when configure the service provider for Playground

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1969]
Under 1st step of 'Configuring OAuth2-OpenID Connect Single-Sign-On' doc [1], it mentioned to expand the OAuth/OpenID Connect Configuration. But it didn't mentioned to go to 'Inbound Authentication Configuration'.

[1] https://docs.wso2.com/display/IS540/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
