### ISSUE TITLE
[Doc] Mention whether the Custom grant type displayed in UI in 'OAuth/OpenID Connect Configuration' by default or not

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1970]
According to the 2nd step in [1], 'urn:ietf:params:oauth:grant-type:jwt-bearer' custom grant type only appear on the UI if the user has configured the JWT grant type. By default with a vanila pack, this grant type can be seen on UI. So it's better to revisit the term on visibility based on enabling jwt grant type.

[1] https://docs.wso2.com/display/IS540/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
