### ISSUE TITLE
UI issues in the landing page of the Console

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#19716]
**Describe the issue:**

The following are some minor UI improvements that we can do to make the console look more polished.
since this is the landing page, I feel like having these kinds of minor issues can affect the UX significantly.

![Screenshot 2024-02-20 at 11 25 41](https://github.com/wso2/product-is/assets/25428696/2db935a5-27e0-4f0e-8c2b-5e7fea1b0943)

1. No period at the end of the sentence. inconsistent with the Manage Users section
2. Icon is smaller than the other illustrations. It pops out as being small.
3. View all applications is not aligned with View Users and Set-up connections in the other panes.
4. Onboard and manage apps is not aligned with Manage Users.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NipuniBhagya** [comment]
Also, there's a small inconsistency in the SPA card.

<img width="249" alt="image" src="https://github.com/wso2/product-is/assets/30111554/ae4dca5a-26d8-4c7a-9279-6f6ad5eaebde">
