### ISSUE TITLE
[User Attribute Change Verification] The "Enable user mobile number verification on update" /"Enable user email verification on update" is getting triggered when "adding" a mobile number/email

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#19719]
**Describe the issue:**
Scenario 1:
With the "Enable user mobile number verification on update" checked and the consumer user/admin tries to update the business user mobile number/email details
When adding a mobile number for an existing consumer user (not an update, but adding), the SMS cannot be triggered for the existing mobile, since the mobile number is blank. So this config should be exempted if the existing mobile number is blank/null.

Scenario 2:
Same behaviour is applicable if the email address is blank and "Enable user email verification on update" is checked

**How to reproduce:**
1. Check "Enable user email verification on update" under User Attribute Change configuration
2. Navigate to a consumer user with no mobile numbers
3. Add a mobile number and verify the behaviour

**Expected behavior:**
The mobile number should be allowed to add

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by UdeshAthukorala** [comment]
This will be fixed with: 
- https://github.com/wso2/identity-apps/pull/5573
- https://github.com/wso2-extensions/identity-event-handler-notification/pull/220

**Comment by UdeshAthukorala** [comment]
> This will be fixed with:
> 
> * [Update SMS provider payload template identity-apps#5573](https://github.com/wso2/identity-apps/pull/5573)
> * [Update SMS provider payload template wso2-extensions/identity-event-handler-notification#220](https://github.com/wso2-extensions/identity-event-handler-notification/pull/220)

Reverted the above PRs due to a regresiion(https://github.com/wso2/product-is/issues/19750) and fixed this issue with https://github.com/wso2-extensions/identity-event-handler-notification/pull/222
