### ISSUE TITLE
No information related to different user-stores in cluster document  

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1972]
IS cluster can pointed to different user-stores but in the document its only focusing on LDAP 

[1] https://docs.wso2.com/display/IS540/Setting+Up+Deployment+Pattern+1
[2]https://docs.wso2.com/display/IS540/Setting+Up+Deployment+Pattern+2

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
