### ISSUE TITLE
Provide a meaningful error message when a user attempts to perform an action after staying idle (after session timeout)

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1973]
== Environment ==

IS 5.4.0 GA 
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Issue Summary ==

When a logged in user perform an action in management console after being idle for some time (after session timeout happens), there's an error thrown in back end as below.

````
WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/carbon/oauth/add-finish-ajaxprocessor.jsp, error:request token does not match session token)
````
By looking at the error log, it's difficult identify the reason for the exception since this will implies a CSRF attack at first place.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
