### ISSUE TITLE
No format defined when configure Kerberos KDC service

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1976]
== Environment ==

IS 5.4.0 GA
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

1. Login to management console, click 'Add' under Service Providers
2. Register a service provider and go to 'inbound authentication configurations'
3. Click 'Configure' under 'Kerberos KDC'
4. Add a service name

== Actual Outcome ==

There's a pop up displayed when user add a name out of format. But there's no indication of what's the format to add the service name.

![service principal](https://user-images.githubusercontent.com/8849472/34529129-06e47102-f0d1-11e7-931c-76335089de10.png)

== Expected Outcome ==

Having a tooltip or description with proper format would be great.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
