### ISSUE TITLE
[Doc] Callback url isn't mandatory when not defining 'Code' or 'Implicit' as grant types

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1977]
'New Application form' under 3rd step in [1] mentioned that callback url is mandatory to define when configure 'OAuth/OpenID Connect Configuration'. But when a user doesn't define 'Code' or 'Implicit' as grant types, 'callback url' doesn't need to be add. Need to mention this in documentation.

[1] https://docs.wso2.com/display/IS540/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

**Comment by ShirazAzad** [comment]
Fixed. Updated the docs [1], [2] and [3] with the suggested info.
[1] https://docs.wso2.com/display/IS520/Configuring+OAuth2-OpenID+Connect+Single-Sign-On
[2] https://docs.wso2.com/display/IS530/Configuring+OAuth2-OpenID+Connect+Single-Sign-On
[3] https://docs.wso2.com/display/IS540/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

**Comment by omindu** [comment]
@ShirazAzad The modifications seems to be incorrect.

> This is the exact location in the service provider's application where an access token would be sent. This is a required field (if the grant type is anything other than 'Code' or 'Implicit') and it is important to configure, as it is imperative that the service provider receives the access token.

1. The callback URL can either receive the authorization code or the access token, depending on the grant type. For code grant type, it receives the authorization code and for implicit grant type it receives the access token and ID token (for OpenID connect).

2. The callback URL is mandatory for code and implicit grant types and not the other way around.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
