### ISSUE TITLE
Enable Group Unique ID property shown as string value in JDBC userstores

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#19779]
**Describe the issue:**

Enable Group ID property shown as a string value in JDBC user stores as below.

<img width="650" alt="Screenshot 2024-02-21 at 21 45 02" src="https://github.com/wso2/product-is/assets/13478571/6e500035-cdca-40d5-8816-133de0a3d413">

**How to reproduce:**

1. Try to create a JDBC userstore from the console.

**Expected behavior:**
- The property should be a boolean value and it should be shown as a toggle button in the UI.
- It is properly working in other 3 userstore types. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by UdeshAthukorala** [comment]
This will be fixed in is 7.0 RC-6 pack with: https://github.com/wso2/carbon-kernel/pull/3913
