### ISSUE TITLE
Passkey registration/ authentication fails in Android

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#19785]
**Describe the issue:**

Observed following error while trying out passkey registration/ authentication on my Android mobile. This used to work before without any issues and may cause by a recent Android update. This issue hasn't occurred in iPhones and was able to register a passkey.

Created this issue to track and find the root cause of this.

![Screenshot from 2024-02-22 08-06-35](https://github.com/wso2/product-is/assets/35653110/0f5ef7f1-9c8c-4993-9675-4ef554a0422f)

![PSX_20240222_080712](https://github.com/wso2/product-is/assets/35653110/33f031bf-ba38-4afb-889a-34876387eb80)

Able to catch the following stacktrace with a console log.
```
DOMException: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client
```

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] IS 7.0.0
 - OS: [e.g., Windows, Linux, Mac] Ubuntu  20.04.6
 - Mobile: OnePlus 10 Pro - Android 14 (Nov 5 2023 security update)
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sahandilshan** [comment]
Check this on the following device and the passkey flow works as expected
- Device: Samsung Galaxy s23 Ultra
- OS: Android 14

**Comment by ThaminduDilshan** [comment]
It appears that this is failing only for the external devices (eg: with QR code flow) and authentication with on device passkeys are working. Looks like this is an issue with OnePlus devices.

There are few reported similar cases.
- https://community.oneplus.com/thread/1524482911464587269
- https://answers.microsoft.com/en-us/windows/forum/all/failed-to-login-by-passkey-using-android-device-on/b3208f02-fdc3-451f-af61-752c16305b25
- https://stackoverflow.com/questions/77742863/webauthn-not-registering-validating-on-oneplus-devices

**Comment by ThaminduDilshan** [comment]
Closing as this is not a WSO2 IS bug
