### ISSUE TITLE
[Doc] Identity Provider Login URL and Identity Provider Logout URL should be provided when the server is not running in localhost

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#1978]
Usually, in production environments, the servers are fronted by a load balancer. Therefore it will be useful to add a note and show an example on how to provide the "Identity Provider Login URL" and "Identity Provider Logout URL" values when using a domain name rather than showing with "localhost".

Currently, this is displayed as below:
Issuer | localhost
Identity Provider Login URL | https://localhost:9443/samlsso
Identity Provider Logout URL | https://localhost:9443/samlsso

Doc link: https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server#LoggingintoSalesforceusingtheIdentityServer-ConfiguringSalesforce

**Comment by pubudup** [comment]
Tested version: IS: 5.4.1

**Comment by ShirazAzad** [comment]
Updated the doc [1] by editing the 1st step.
[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option
