### ISSUE TITLE
[Doc] Provide instructions on how to generate a "Identity Provider Certificate" file when configuring a clustered environment

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#1979]
Current document here [1], explains how to generate a certificate for to provide in Salesforce when the server is running locally. In a practical scenario, this is done mostly in a clustered environment. Therefore, it is necessary to provide information on how to create this file on a cluster.

For example, the reader might have the question of whether to generate this file for each node or create it in one node and copy it across all the other nodes etc.

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server#LoggingintoSalesforceusingtheIdentityServer-ConfiguringSalesforce

**Comment by pubudup** [comment]
Tested on: 5.4.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
