### ISSUE TITLE
[Doc] "Identity Provider Logout URL" should be changed as Custom logout URL as per salesforce UI

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#1980]
Please update "Identity Provider Logout URL" as "Custom Logout URL" as displayed in Salesforce UI

Doc link: https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server#LoggingintoSalesforceusingtheIdentityServer-ConfiguringSalesforce

**Comment by pubudup** [comment]
Tested on: 5.4.0

**Comment by ShirazAzad** [comment]
Fixed. Docs [1] and [2] updated with "Custom logout URL". 
[1] https://docs.wso2.com/display/IS530/Logging+in+to+Salesforce+using+the+Identity+Server
[2] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server
