### ISSUE TITLE
[Doc] Under step 6, it doesn't clearly specify which checkboxes to select

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#1981]
In this document [1], under step 6 when configuring SP it only asks user to select "Enable Response Signing" and "Enable Attribute Profile", but by default "Enable Signature Validation in Authentication Requests and Logout Requests" and "Enable Single Logout" are also checked. 

In that case, it should be clearly stated which checkboxes should be unchecked while doing the configuration.

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server#LoggingintoSalesforceusingtheIdentityServer-ConfiguringSalesforce

**Comment by pubudup** [comment]
Tested on : 5.4.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
