### ISSUE TITLE
[Doc] In Solution 04, unable to find a document on adding IS as a trusted IDP to an Service Provider

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#1982]
In solution 4 in blog [1], it is required to add IS as a trusted IDP to an external SP as described. But unable to find any documents on how to add IS as a trusted IDP to any SPs (eg: Salesforce prefered)

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by pubudup** [comment]
Tested in :5.3.0

**Comment by omindu** [comment]
[1] should have information on configuring IS as an IDP in SF. 

[1] - https://docs.wso2.com/display/IS530/Logging+in+to+Salesforce+using+the+Identity+Server

**Comment by pubudup** [comment]
@omindu : Actually this is the document I have followed and this does not contain any information on adding IS as a trusted IDP to an external SP.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
