### ISSUE TITLE
[B2B] Unable to access the Connection page with all the permissions provided for an Organization

### ISSUE THREAD

**Issue by GoushiRam** [wso2/product-is#19832]
**Describe the issue:**
When an administrator role is created, in the permission section > there is no permission to give for the Connections page. This restricts the creation of a role with the Connection page access. 

i.e > we can't create a full functional sub organization administrator with the roles

**How to reproduce:**
1. Navigate to the Root organization
2. Create a role with all the organization permission and verify the permissions. (There are no "Connections" permission, only closer one is "Identity Providers")
3. Create a sub organization and switch to it
4. Create a user, make him a sub org admin with the above role
5. Login to the admin and verify the access

Recording: 

https://github.com/wso2/product-is/assets/106053688/5e50e18d-fa31-40a2-b50e-e389c1406810

**Expected behavior:**
The connection permission should be available in order to provide its access to the sub organization administrators

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0] - RC4
 - OS: [e.g., Windows, Linux, Mac] - Mac
 - Database: [e.g., MySQL, H2] - MSSQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Looks like `internal_org_authenticator_view`[1] scope is required for the `https://localhost:9443/t/carbon.super/o/api/server/v1/authenticators` to work.

<img width="774" alt="Screenshot 2024-02-25 at 15 05 02" src="https://github.com/wso2/product-is/assets/25959096/171c9db5-520c-4b36-bd40-f518dd8cf464">

Looks like the scope is not returned from the meta endpoint resulting in the issue.

<img width="605" alt="Screenshot 2024-02-25 at 15 06 47" src="https://github.com/wso2/product-is/assets/25959096/5aa0e246-306b-440f-b60d-d024bb45f729">

Need to add that to the [api-resource-collection.xml](https://github.com/wso2/carbon-identity-framework/blob/master/features/api-resource-mgt/org.wso2.carbon.identity.api.resource.mgt.server.feature/resources/api-resource-collection.xml#L537)

[1] https://github.com/wso2/carbon-identity-framework/blame/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/resource-access-control-v2.xml#L808
