### ISSUE TITLE
Organization switch option is not available for the sub-org admins invited from the parent org when root org "view organizations" permission is assigned via groups

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#19849]
**Describe the issue:**
Organization switch option is only available in the root organization's console for the sub-org admins that are invited from parent org when root org "view organizations" permission is directly assigned to that user via a role. If the same role is assigned to a user via a group, the organization switch option is not available for that user in the root organization's console.

**How to reproduce:**
1. Create an admin role from the "Console Settings" section and assign 'Organization view' permission under 'Root Organization Permissions' to the role.
2. Create two users. Assign the above created role to one user via a group. Assign the role directly to the other user.
3. Create a sub organization and switch to it. 
4. Go to 'Console Settings' in the sub-org and invite the above created 2 users as sub-org admins (Assign sub-org level admin access via a role accordingly). The two users will get email invitations to join the sub-org.
5. Accept the invitations.
6. Log in to the root org console using the credentials of the 2 users.
- When logged in with the user who got organization view permission assigned via a group cannot see the organization switch option for the invited sub-org.
- When logged in with the user who got organization view permission assigned directly via the role can see the organization switch option for the invited sub-org.

For the user who got assigned the 'organization view' permission directly by assigning the role
<img width="1466" alt="Screenshot 2024-02-26 at 15 54 42" src="https://github.com/wso2/product-is/assets/25479743/cbc00fe5-78a9-4f1f-aecd-fd23f12cd652">

For the user who got assigned the 'organization view' permission indirectly via a group
<img width="1471" alt="Screenshot 2024-02-26 at 15 55 24" src="https://github.com/wso2/product-is/assets/25479743/a91ec8cd-7d3a-4506-a09b-67c8ead72102">

**Expected behavior:**
Both the users should be able to switch to the sub-organization using the organization switch option in the root organization console. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0 RC5

**Comment by HasiniSama** [comment]
This issue has been resolved, as both users can now switch to the sub-organization using the organization switch option in the root organization console.

However, in step 04 of reproducing the issue, the user assigned to the admin role via the group, cannot be directly invited to join as a sub-org level admin. 

The following error is shown when invited:
<img width="718" alt="Screenshot 2024-05-14 at 14 59 04" src="https://github.com/wso2/product-is/assets/65800949/531f2d4f-eb6a-4ea0-81c1-3266b7d16a39">

Therefore, the following issue is opened: https://github.com/wso2/product-is/issues/20377
