### ISSUE TITLE
Update button is enable on governance connectors  edit pages  in sub organization level. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19848]
**Describe the issue:**
Permission error when updating the governance authenticators on sub organization level 

![Screenshot from 2024-02-26 17-40-21](https://github.com/wso2/product-is/assets/39077751/45e7191b-adb3-4e59-bda8-df426ade8f25)

![Screenshot from 2024-02-26 17-40-07](https://github.com/wso2/product-is/assets/39077751/e1fb5076-5911-47e6-84db-da99af39bfdf)

Email [1]  has not mentioned the behavior of the governance connector update within the sub organization level. But the  only defined scopes under [Organization] Identity Governance Management API  ((.*)/o/api/server/v1/identity-governance(.*)") is  **internal_org_governance_view** . Hence assuming this is a UI bug and update option should be remove from the sub organizations for governance authenticators.  @AnuradhaSK 

Scope <IS-HOME>/repository/identity/resource-access-control-v2<img width="809" alt="image" src="https://github.com/wso2/product-is/assets/39077751/8666ad28-d5e5-4510-8f10-06d67a3410ec">

[1] email: "Permission error when updating the local governance authenticators on sub organization level" `""/o/api/server/v1/identity-governance" Governance configuration API - If the root organization (B2B Service providing organization) configures self-registration, password validation, or recovery option kind of configurations, those will not get updated in customer/partner organizations due to tenancy. To apply the same change to the customer/partner organizations, need to use the PATCH request of "/o/api/server/v1/identity-governance" API."`

**How to reproduce:**
1. Login to console
2. Create sub org
3. Switch to sub org
4. Navigate to connection
5. navigate to edit page on one of the connections, Email OTP, Passkey or SMS OTP
6. Click update

**Expected behavior:**
Update option should be disable from UI

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by savindi7** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/5614

We used the isSubOrganization hook to disable update operation. We should use scope based operation management for such sub features - https://github.com/wso2/product-is/issues/19861
