### ISSUE TITLE
EI version that use for work flow must mention in documentation 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1985]
In the doc [1] Its mentioned to download and configure  BPM profile , its better to mentioned which version of the EI should user download 

[1] https://docs.wso2.com/display/IS540/Configuring+the+BPM+Profile+of+WSO2+EI+as+a+Workflow+Engine

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
