### ISSUE TITLE
Metadata is not getting applied for custom connector

### ISSUE THREAD

**Issue by ZiyamSanthosh** [wso2/product-is#19856]
**Describe the issue:**

According to [1], metadata for custom authenticator connectors can be added through the deployment.toml file. This will improve the UI and UX in the console to know more information about the authenticators added as connectors. 

This capability is not working as expected.

**How to reproduce:**
1. Add a custom connector artifacts to the IS distribution. (Eg: Linkedin connector)
2. Add the configuration to the deployment.toml as mentioned in [1]
3. Login to the console and create a custom connection
4. Move to settings and try to add a new connector
5. The linkedin connector won't have any information except the name of the authenticator retrieved from the API.

**Expected behavior:**
Display name, description, and logo of the authenticator should be shown in the UI.

<img width="1134" alt="Screenshot 2024-02-27 at 12 15 30" src="https://github.com/wso2/product-is/assets/50801227/e6c36095-9a8b-4401-be81-b8193b3f5105">

[1] https://github.com/wso2/identity-apps/blob/master/docs/CONNECTORS.md

**Comment by dasuni-30** [comment]
This issue is occurred due to a templating issue in the default.json configurations file.
https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json#L841
