### ISSUE TITLE
No configuration information  regarding JDBC user store with BPS

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1986]
No configuration information  regarding JDBC user store is mentioned in Configuring the BPM Profile of WSO2 EI as a Workflow Engine for IS . Only LDAP information is provided.
[1]https://docs.wso2.com/display/IS540/Configuring+the+BPM+Profile+of+WSO2+EI+as+a+Workflow+Engine

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
