### ISSUE TITLE
No success message when adding an administrator to the console

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#19863]
**Describe the issue:**
We can configure admins to the console. When we add a user to the administrator role, no success message is seen. But when removing the user, an success message can be seen.
![Screenshot 2024-02-27 at 04 44 04](https://github.com/wso2/product-is/assets/39567992/7fbdcbf2-2904-472a-95fe-baebf1f1bcc3)

**How to reproduce:**
1. Create a user.
2. Navigate to the `console settings`. 
3. Click on `Add Administrator` and add the above user. Notice that the success msg is not there.

**Expected behavior:**
- Operation success msg to maintain consistency.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
This is verified with the wso2is-7.1.0-m5 .

**Verification steps** 

1. Add user
2. Navigate to console setting
3. Select Administrator role
4. Navigate to user tab
5. Select the user and add
6. Validate the success message. 

[Screencast from 2024-11-25 11:52:00.webm](https://github.com/user-attachments/assets/f0a9ea75-c39b-4c8d-814d-e1c45f5b69eb)

**Expected outcome:** 
Success message should be appear when add user

**Actual outcome:**
Success message appeared when add user. 

This is fixed. Hence closing the issue.
