### ISSUE TITLE
[Doc] Ouath2 Playground image need to be update with latest changes in UI

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#1987]
The first image listed under 'Try out scenario' section needs to be updated with last change - **'Use PKCE'** according to the the below,

![use pkce](https://user-images.githubusercontent.com/8849472/34566343-30530914-f184-11e7-86b6-e6dfd88e96d2.png)

[1] https://docs.wso2.com/display/IS540/Basic+Client+Profile+with+Playground

**Comment by nilasini** [comment]
duplicates
https://github.com/wso2/product-is/issues/2973
