### ISSUE TITLE
[Doc] Recaptcha configuration doc missing in the IS 7 docs

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#19897]
IS 6.1 doc: https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/
https://is.docs.wso2.com/en/latest/guides/login/configure-recaptcha-for-single-sign-on/#configure-single-sign-on-with-recaptcha-globally

This is not present in the IS 7 docs

This doc is present
https://is.docs.wso2.com/en/7.0.0/guides/account-configurations/login-security/bot-detection/

But a doc for deployment.toml configurations is not present

**Comment by aaujayasena** [comment]
Required to set instruction for setup recpatcha keys as well. 

https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/#configure-recaptcha-api-keys

**Comment by savindi7** [comment]
This must be included too - https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/#choosing-the-type-of-recaptcha 

cc - @himeshsiriwardana
