### ISSUE TITLE
[Docs] Login portal customization is missing in the IS 7 docs

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#19891]
**Is your suggestion related to a missing or misleading document? Please describe.**

 https://is.docs.wso2.com/en/6.1.0/references/extend/rebranding/customizable-login-portal/

We need to provide this documentation to provide guidance on adding a custom layout for login and registration pages. Additionally, we can mention that we can now incorporate layouts at the tenant level, and sub-org level.

**Comment by himeshsiriwardana** [comment]
Branding documentation is now available. Hence closing.

https://is.docs.wso2.com/en/latest/guides/branding/
