### ISSUE TITLE
Improvements to the B2B use case documentation

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#19916]
**Is your suggestion related to a missing or misleading document? Please describe.**

Following improvements are noticed while going through the B2B use case documentation.

1. In the guide we first instruct to setup the application and then instructs to setup the organization. While setting up the application, we ask to [share it with the sub organizations](https://is.docs.wso2.com/en/7.0.0/guides/organization-management/try-a-b2b-use-case/#step-2-share-the-applications-with-organizations). However at this point users may not have created the sub organizations. Hence would it make sense to move the [Set up the organization](https://is.docs.wso2.com/en/7.0.0/guides/organization-management/try-a-b2b-use-case/#set-up-the-organization) section prior to the [Set up the applications](https://is.docs.wso2.com/en/7.0.0/guides/organization-management/try-a-b2b-use-case/#set-up-the-applications) section?
2. Instructions given in the "API Authorization" section under the [Step 3: Configure the applications on WSO2 Identity Server](https://is.docs.wso2.com/en/7.0.0/guides/organization-management/try-a-b2b-use-case/#step-3-configure-the-applications-on-wso2-identity-server) does not include steps on how someone can authorize the listed APIs. Would it make sense to add a reference to the [Authorize the API resources for an app](https://is.docs.wso2.com/en/7.0.0/guides/authorization/api-authorization/api-authorization/#authorize-the-api-resources-for-an-app) section here?
3. [Try out Sign In with SSO](https://is.docs.wso2.com/en/7.0.0/guides/organization-management/try-a-b2b-use-case/#try-out-sign-in-with-sso) section introduction describes about login to the `Guardio Insurance Business App`. However other instructions and screenshots are given for the `Guardio Insurance Admin App`. Should this have instructions for business app or admin app login?
4. Also it is better to have a step on onboarding an organization user in the [Set up the organization](https://is.docs.wso2.com/en/7.0.0/guides/organization-management/try-a-b2b-use-case/#set-up-the-organization) section.

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by himeshsiriwardana** [comment]
These documentation changes are already implemented. Refer to the organization [1] section.

[1] https://is.docs.wso2.com/en/latest/guides/organization-management/
