### ISSUE TITLE
[Docs] Review Content for iProov Authenticator

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#19926]
**Is your suggestion related to a missing or misleading document? Please describe.**
iProov authenticator will be integrated with Identity Server as a connector. It is required to get the content that is presented in the console UIs for iProov authenticator. Please find the attached screenshots of the related UIs.

_Create Connection view_
![Screenshot from 2024-03-04 17-21-30](https://github.com/wso2/product-is/assets/30428591/2fd24626-9d42-46b4-ace3-94efe5b524ba)

_Create iProov Connection part 1_
![Screenshot from 2024-03-04 17-27-11](https://github.com/wso2/product-is/assets/30428591/d093a3d8-648d-4f61-9ef9-26fa34f8096a)

_Create iProov Connection part 2_
![Screenshot from 2024-03-04 17-27-17](https://github.com/wso2/product-is/assets/30428591/96a13470-14de-4d52-9b32-2639c20d8b96)

_Quick start view part 1_
![Screenshot from 2024-03-04 17-28-21](https://github.com/wso2/product-is/assets/30428591/17a9917f-b5c4-480b-ab86-1b7295455d41)

_Quick start view part 2_
![Screenshot from 2024-03-04 17-28-27](https://github.com/wso2/product-is/assets/30428591/d24337f0-47cd-44e1-93b2-78d66302c744)

_Settings view_
![Screenshot from 2024-03-04 17-28-36](https://github.com/wso2/product-is/assets/30428591/eb849550-7478-493a-9418-ca935ee7d219)

**Architecture mail thread:** [Architecture][IS/Asgardeo] Integration of iProov

### Optional Fields

**Additional context**

**Related Issues:**

- [https://github.com/wso2-enterprise/iam-engineering/issues/887](https://github.com/wso2-enterprise/iam-engineering/issues/887)

**Comment by divyaamunugama** [comment]
**_Create Connection view_**
No changes are required, +1 to proceed.

**_Create iProov Connection part 1 and 2_**

- Suggested text: `Enter the iProov server's base URL.`
![image](https://github.com/wso2/product-is/assets/84217321/627301f4-810a-418b-8482-163c48552047)

- The hint text is incorrect, should be OAuth password.
![image](https://github.com/wso2/product-is/assets/84217321/acf80ab5-79ea-4dac-92f5-97e1997dea84)

- For all the fields let's use the following format:
`Enter the API key obtained from the service provider created in iProov.`

- Apply the changes mentioned above to the descriptions on the right panel as well.

**_Quick start view part 1 and 2_**
No changes are required, +1 to proceed.

**_Settings view_**

- Suggested text: `When enabled, users can enroll with iProov during login.`
![image](https://github.com/wso2/product-is/assets/84217321/c22b6a94-78a3-4c0a-96f4-06f2662d2f9d)

- For the remaining hints, let's use the following format by replacing `Enter` with `The`, and adding the word `obtained`.
`The base URL obtained from the service provider created in iProov.`
