### ISSUE TITLE
Intermittently Pass key enrolment is not working.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19938]
**Describe the Issue:**
Intermittently Pass key enrolment is not working. 

**How To Reproduce:**
1. Login to console
2. Create customer user
3. Login to my account with the customer user (My account tenanted path)
4. Navigate to the security page
5. Select pass key add button
6. Select use a phone, tablet and security key
7. Scan the QR code from phone (here intermittently )

**Expected behavior:**
QR scanning complete and pass key generate success. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
Closing the issue since the behavior is expected due to the network slowness.
