### ISSUE TITLE
Improve passkey Alert-note 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19964]
**Is your suggestion related to an experience ? Please describe.**

To enable the passkey it's required to enable the allow the passkey progressive enrolment check box at passkey connector configuration. The given detail are not enough.

<img width="1141" alt="image" src="https://github.com/wso2/product-is/assets/39077751/1134cba0-c4d9-4d67-8912-9aeb63c00144">

**Describe the improvement**
We have several approaches to enhance the user experience by improving the aware of the end user by adding this information on UI and solutions suggesting are 

- Add note in alert regarding the  passkey progressive enrolment check box at passkey connector configuration.
- Add link to navigate to the passkey connector configuration page
- Add [documentation](https://is.docs.wso2.com/en/next/guides/authentication/passwordless-login/add-passwordless-login-with-passkey/#enable-passkey-progressive-enrollment) link 

**Additional context**

**Comment by dasuni-30** [comment]
### Verified in the pack

https://github.com/user-attachments/assets/b8f40ab7-403d-4f76-afaa-c966ee61c014
