### ISSUE TITLE
Update error message is not display in visual editor

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19970]
**Describe the issue:**
Update error messages should be display for invalid login flow configurations and currently its not display on Visual editor. This was displayed On Classic editor view.
<img width="1075" alt="image" src="https://github.com/wso2/product-is/assets/39077751/d07cd527-4438-4be4-8a6a-dee5542f0959">

**How to reproduce:**
1. Login to console
2. Create application
3. Navigate to application edit phase
4. Click login flow
5. On visual editor remove default configuration added as username and password
6. Select add option in 1st step of the login flow
7. Select "Identifier first" option

**Expected behavior:**
Error update message should be displayed. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
Fix PR: https://github.com/wso2/identity-apps/pull/5727
