### ISSUE TITLE
Support registering multiple email addresses and mobile phone numbers per user

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#19991]
**Is your feature request related to a problem? Please describe.**

Identity Server currently allows only one email address and one phone number per user. However, there could be scenarios where users might have multiple email addresses and phone numbers, and they would like to add those in their user profile and designate a primary email address and a phone number for the purpose of receiving notifications and OTPs by default. They also expect to change or delete any of those email addresses or mobile numbers or change the primary selection at their will.

**Describe the solution you would prefer**

- Allow users to add multiple email addresses or mobile phone numbers in their user profile. 
- If user has multiple email addresses, force them to designate one as the primary email.
- If user has multiple mobile phone numbers, force them to designate one as the primary number.
- When sending Email or SMS OTP, or any communication where a user action is needed (E.g. Magic link, Account recovery), users should be give the option to send to any of the registered email addresses or mobile numbers.
- When sending notifications to users (E.g. Account Locked), that should be done to the primary.

**Migration Issue**

- https://github.com/wso2/product-is/issues/20506

**Comment by lashinijay** [comment]
The myaccount details are not getting updated when navigated to Personal Info tab. This is now fixed.

- https://github.com/wso2/product-is/issues/20297

**Comment by lashinijay** [comment]
There are two governance config that allow organizations to enable verification when updating mobile number and email address. However to enable the UIs for verification we have introduced a separate config to FE. Hence even when the user enable mobile/ email verification on update from the governance configs UIs were not enable.

To make the UIs to be align with the server-side config, the FE config will be removed and both FE and BE will be rely on the existing governance config.

With the following PR this will be addressed.

- https://github.com/wso2/identity-apps/pull/6220

**Comment by PasinduYeshan** [comment]
Documents - https://is.docs.wso2.com/en/next/guides/users/attributes/manage-attributes/#assign-multiple-email-addresses-and-mobile-numbers-to-a-user
