### ISSUE TITLE
Basic Client Profile with Playground sample doc introduction should be more elaborated.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1999]
Basic Client Profile with Playground sample doc [1] introduction should be more elaborated.

[1] https://docs.wso2.com/display/IS540/Basic+Client+Profile+with+Playground

Current doc has only the below introduction. 
**This section demonstrates the WSO2 Identity Server's OpenID Connect Basic Client Profile implementation with the WSO2 OAuth2 playground sample.** 

Would be great if this can be explain with the use case of this scenario.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
