### ISSUE TITLE
BPS scerts must import to IS trust store 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2001]
When  configure an external BPS server as a workflow engine (BPS component in EI server)  of IS,  user need to  change the keystore with the CN matching to BPS server hostname and then they must import the created cert  to the client-trust store of IS. Otherwise Hostname verification error  occur.  This details must in the document (1)

.
[1]https://docs.wso2.com/display/IS540/Configuring+the+BPM+Profile+of+WSO2+EI+as+a+Workflow+Engine

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
