### ISSUE TITLE
Confirm password recovery documentations request body schema is not readable due to text colour.  

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#20020]
**Is your suggestion related to a missing or misleading document? Please describe.**
The REQUEST BODY SCHEMA sections of the documentation for the user-account-recovery-v2-rest-api is unreadable due to it's font color blending with the background color. 

<img width="846" alt="Screenshot 2024-03-16 at 10 48 52" src="https://github.com/wso2/product-is/assets/42939752/faa9a78a-50bc-4f13-957a-dd135052a3d6">

**Describe the improvement**
Change the color of the font.

---

**Comment by himeshsiriwardana** [comment]
API documentation is now fixed.
