### ISSUE TITLE
[Doc] Incorrect step defined when trying with Basic Client Profile with Playground

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2002]
According to the document [1], 6th step of 'Try Out Scenario' has an image with 'Logged in User', 'Access Token' and 'UserInfo Endpoint' but when trying out it will give the below window.

![next screen](https://user-images.githubusercontent.com/8849472/34609244-f05be7b8-f241-11e7-81b7-d653205c2d3f.png)

[1] https://docs.wso2.com/display/IS540/Basic+Client+Profile+with+Playground

**Comment by nilasini** [comment]
Duplicates
https://github.com/wso2/product-is/issues/2973
