### ISSUE TITLE
[Doc] Add final window with user information to the document when trying Basic Client Profile with Playground

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2003]
Following screen should be added to the documentation [1], at the end of 'Trying out Scenario'. This contain user information window which comes as the last step.

![last screen](https://user-images.githubusercontent.com/8849472/34610111-926c227c-f245-11e7-905e-ab81be345045.png)

[1] https://docs.wso2.com/display/IS540/Basic+Client+Profile+with+Playground

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
