### ISSUE TITLE
Unable to bump kernel version in Framework

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#20041]
**Describe the issue:**
Unable to bump kernel 4.10.x to the framework master branch

**How to reproduce:**
bump kernel version :https://github.com/wso2/carbon-identity-framework/pull/5569

**Expected behavior:**
Should be able to bump

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by darshanasbg** [comment]
@VivekVinushanth @madurangasiriwardena: Is this sorted guys? If so shall we close the issue adding the resolution details?

**Comment by darshanasbg** [comment]
As per https://github.com/wso2/carbon-identity-framework/pull/5592 this should be solved now.. Reopen if it isn't the case.
