### ISSUE TITLE
[cluster]Dashboard shows incorrect BPS profile in drop down

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2005]
Configured an external BPS server as a workflow engine (BPS component in EI server) of IS.
Created a new profile and added new work flow
When Approver login to dashboard and approve  its shows the task under embdedbps. But the configure task is belong to new work flow engine refer attached image 

![bps](https://user-images.githubusercontent.com/13656890/34610964-82f1fa98-f249-11e7-975d-a5e7aeea92e5.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
