### ISSUE TITLE
[Doc] Missing `Enable Email Account Verification for an Updated Email Address` docs IS-7.0 doc

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#20067]
**Is your suggestion related to a missing or misleading document? Please describe.**

Please refer the $subject. IS-7.0 provides the capability to Enable Email Account Verification for an Updated Email Address. However the relevant docs are missing from IS-7.0 doc space.

Relevant IS-6.1 Docs - https://is.docs.wso2.com/en/6.1.0/guides/identity-lifecycles/enable-email-account-verification-for-an-updated-email-address/?query=user_claim_update#enable-email-account-verification-for-an-updated-email-address

**Comment by himeshsiriwardana** [comment]
This is covered in this section: https://is.docs.wso2.com/en/latest/guides/users/attributes/user-attribute-change-verification/
