### ISSUE TITLE
[Cluster] Work flows are not working with external BPS [EI] in cluster mode 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2006]
**Environment details**

- JDBC user Store (Shared user DB and BPs DB)
- External BPS - wso2ei-6.1.1
- IS (5.4.0 update 3 )2 node cluster fronted with Ningx 

**Steps** 

1. Configuring the BPM Profile of WSO2 EI as a Work flow Engine for IS [1].
2. Add under Work flows Engagement for add user.
3. Create a new user 
4. Log into dashboard of the cluster using a user who has approval permissions.
5. Approve the pending task.
6. Below exceptions can be seen in back end and nothing happens in the front end.
7. When we revisit the approval page no task is pending to approve. But from the user its  not allow to login .

Pls note that this same scenario is correct working in standalone mode .

_IS cluster_
`ERROR {JAGGERY.gadgets.approvals.controllers.approvals.approve-client:jag} -  JavaException: org.jaggeryjs.scriptengine.exceptions.ScriptException: Error occurred while invoking callback service](url) 
 `
_BPS_ 
```WARN {org.apache.xml.security.signature.XMLSignature} -  Signature verification failed. {org.apache.xml.security.signature.XMLSignature}
TID: [-1234] [] [2018-01-07 09:00:32,243]  WARN {org.apache.xml.security.signature.XMLSignature} -  Signature verification failed. {org.apache.xml.security.signature.XMLSignature}
TID: [-1234] [] [2018-01-07 09:00:32,247] ERROR {org.wso2.carbon.identity.authenticator.saml2.sso.SAML2SSOAuthenticator} -  Authentication Request is rejected. Signature validation failed. {org.wso2.carbon.identity.authenticator.saml2.sso.SAML2SSOAuthenticator}
TID: [-1234] [] [2018-01-07 09:00:32,247]  WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  Failed Administrator login attempt 'SManager@carbon.super[-1234]' at [2018-01-07 09:00:32,247+0000] {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil
```

[1]https://docs.wso2.com/display/IS540/Configuring+the+BPM+Profile+of+WSO2+EI+as+a+Workflow+Engine

**Comment by Chankami** [comment]
This issue also can be related https://github.com/wso2/product-is/issues/2005

**Comment by isharak** [comment]
@Chankami 
Seems to be there is a certificate configuration issue.
TID: [-1234] [] [2018-01-07 09:00:32,247] ERROR {org.wso2.carbon.identity.authenticator.saml2.sso.SAML2SSOAuthenticator} -  Authentication Request is rejected. Signature validation failed

Can you please check the configuration

**Comment by Chankami** [comment]
@isharac 
I have created jk in BPS side  and import  to IS trust store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
