### ISSUE TITLE
"Management Console is currently operating in legacy mode."

### ISSUE THREAD

**Issue by CommandoHuan** [wso2/product-is#20060]
When i open IS Management Console. It show "_Management Console is currently operating in legacy mode. It offers limited functionality, including Multi-Tenancy, XACML, and Keystore Management. For a more comprehensive suite of features, we strongly recommend using the new console._". But i didn't see anything to change to new console. Can anyone show me where to do that

**Comment by darshanasbg** [comment]
Hi @CommandoHuan,

You can access the new console from the url `https://localhost:9443/console` in the default. Refer the doc [1] for more details. Also if you like to refer a small description about the new console, please refer the IS 7.0 release note [2].

[1] https://is.docs.wso2.com/en/latest/guides/your-is/manage-console-access/
[2] https://is.docs.wso2.com/en/latest/references/about-this-release/#whats-new-in-this-release

Hope this helps!

**Comment by CommandoHuan** [comment]
Thank you very much.
