### ISSUE TITLE
[Improvement] Reliable outbound provisioning & the ability to retry

### ISSUE THREAD

**Issue by menakaj** [wso2/product-is#2008]
In outbound provisioning in Identity server, there is no mechanism of retry in case of a failure.

There should be a mechanism for notifying the users whether the provisioning is successful or not and If failed, the user should be able to retry.

Redmine: [https://redmine.wso2.com/issues/6934](url)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
