### ISSUE TITLE
Token generation failing when token hashing is enabled

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-is#20085]
**Describe the issue:**

During the APIM 4.3.0 release testing effort, we noticed that the token generation when token hashing feature is enabled is not working as expected. Upon further investigation, we found out that this issue was caused by a recent fix [1] done on SP caching. The issue occurs here because the SP is not removed from the AppInfoCache based on a newly added condition[3].

The original issue [2] related to user claims in a federated scenario talks about a possible improvement on the AuthorizationGrantCache. However, the fix done is affecting only the AppInfoCache. Due to this, the outdated SPs are not cleared from the cache after an update to the SP. Token generation when token hashing is enabled is not working as expected due to this as the client credentials comparison happens between the plain text value and the hashed value [4]. The flow works fine when the product is restarted as the cache is cleared upon the restart and the up to date SP configurations are fetched from the database.

In APIM's use cases, we update the SPs after creation so that they can be used even when the hashing feature is enabled. This is applicable to both the SP apps created for UI portals as well as the ones created for consumer apps. However, this flow is broken due to the behavioural change of the cache. The product has to be restarted every time we create a new app in order for the token generation to work.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1963
[2] - https://github.com/wso2/product-is/issues/15127
[3] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L146
[4] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L562

**How to reproduce:**

Enable token hashing feature and try to log into portals or try to generate tokens using a newly created SP.

**Expected behavior:**

Token generation works on first try when hashing is enabled.

**Related issues:**

https://github.com/wso2/api-manager/issues/2545

**Comment by nilasini** [comment]
@JeethJJ are we good to close this issue?

**Comment by JeethJJ** [comment]
Yes, we can close this.
