### ISSUE TITLE
Remove existing extensions/i18n/tmp directory during pre-build process

### ISSUE THREAD

**Issue by thiva-k** [wso2/product-is#20105]
**Is your suggestion related to an experience ? Please describe.**

During the pre-build process of identity-apps a tmp directory is created under apps/console/src/extensions/i18n to store the final meta file after adding the extensions namespace. After this pre-build the meta file is copied from this tmp folder to console/build/resources/i18n. Currently, in the pre-build script the meta file is added to tmp directory if the directory already exists or else a new directory is created. This leads to multiple meta files being added to tmp folder and getting copied to build if i18n files change during development processes, causing issues during rendering pages in development server.

**Describe the improvement**

Check if the tmp folder already exists during pre-build process. If it exists delete the existing one and create a new one and then generate the meta file inside this directory. This makes sure only the latest meta file is stored inside tmp directory and gets subsequently copied to build.

**Comment by JayaShakthi97** [comment]
Addressed with:
- https://github.com/wso2/identity-apps/pull/5839
