### ISSUE TITLE
Applications created via console set application as the role audience in IS-7.0.0 but it is set to organization audience in latest pack

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#20100]
**Describe the issue:**
- Login to the console
- Create an application
- Go to the Roles tab of that application
- IS-7.0.0, "Application" is set as the roles audience, but in the latest pack it is set to organization

IS-7.0.0

https://github.com/wso2/product-is/assets/25483865/557cca48-9a64-475f-a6f3-e9a2d320b7e4

IS-7.0.1

https://github.com/wso2/product-is/assets/25483865/5ebc63da-611d-44fd-b6d9-83c8d0752ca4

**What need to be changed:**

- BE needs to be improved to consider the application consuming role audience is "application" if there is no value set to the app associated role audience in DB
- Update the migration client to set migrating application as application which consume organization audience roles

**Comment by asha15** [comment]
Fixed with: https://github.com/wso2/identity-api-server/pull/605
