### ISSUE TITLE
Admin features in identity-server repository are tightly coupled with the Console application

### ISSUE THREAD

**Issue by thiva-k** [wso2/product-is#20119]
**Is your suggestion related to an experience ? Please describe.**

In the current repository structure of identity-apps, all the administrative features are nested in apps/console/src/features. This effectively results in a scenario where these administrative features could be only used within the console application. Modularization and using these features in other applications is not effective in this current implementation.

**Describe the improvement**

Common administrative features which are in apps/console/src/features could be modularized and moved to the root of the project. Additionally these features could be transformed into a node package which could then be easily re-used in other applications within the mono-repository.

**Comment by brionmario** [comment]
This is now completed:

- https://github.com/wso2/identity-apps/tree/b92dc50499d41c799a6f7cbc0e92ca93d6a750e2/features

Futher improvements will be tracked with:
 - https://github.com/wso2/product-is/issues/20184
 - https://github.com/wso2/product-is/issues/20802
