### ISSUE TITLE
Organization switching will not properly return shared user's groups and roles

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#20122]
**Describe the issue:**
Through the parent organization user invite feature, and organization creation operation we are creating a user reference in sub orgs to maintain the user entitlement org wise.
When obtaining the token through organization switch grant for those users:
- roles, groups and scopes should be derived based on the switching org
Other profile informations are from where the user really resides

**At the moment scopes are resolved correctly from the switching org, but groups and roles are not.**

Recording:
https://drive.google.com/file/d/1DHk724Jf_oa4ih0Z3uOndZMkqm4m0tQg/view?usp=drive_link

**How to reproduce:**
1. Create a traditional web app and share it with all orgs
2. go to protocol section -> Enable organization switch grant and authz code grant
3. Change the access token type to JWT
4. Go to API authorization tab and authorize user mgt API under management APIs and organization API with all scopes
5. Go to roles tab of the app and create two roles User_editor (give all the scopes in both APIs) and User_viewer (Give view scopes in both APIs)
6. Go to application -> User attributes and mark groups and roles as required attributes
7. Create a user in root org
8. Go to groups and create few groups, assign the user to them
9. Assign the user to User_editor role in root level
10. Create a sub org and switch to it
11. Invite the user created in step  7 to the sub org, and let the user accept the invite and onboard to sub org
12. Assign the User_Viewer role to the user in sub org
13. Create few groups (with different names) in sub org and assign the user to those groups

Tryout:
1. Try application login:
```
https://localhost:9443/oauth2/authorize?response_type=code&client_id=b3vOV_CS0NUfU5CfpfVUZ0mfIksa&redirect_uri=https://example-app.com/redirect&scope=openid groups roles internal_org_user_mgt_delete internal_org_user_mgt_update internal_org_user_mgt_view internal_org_user_mgt_create internal_org_user_mgt_list internal_user_mgt_create internal_user_mgt_view internal_user_mgt_list internal_user_mgt_delete internal_user_mgt_update
```

2. Give user credentials and obtain the authz code

3. Try token request
```
curl --location 'https://localhost:9443/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'code=8de39121-7b66-3802-aff4-9caec71f8cbd' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'client_id=b3vOV_CS0NUfU5CfpfVUZ0mfIksa' \
--data-urlencode 'client_secret=fjmxgg3HyLg8u4MZJkUmsX_0Yag1RC1qpnoViuZt80Ma' \
--data-urlencode 'redirect_uri=https://example-app.com/redirect' 
```

4. Try organization switch grant with the token obtained in 3
```
curl --location 'https://localhost:9443/oauth2/token' \
--header 'Authorization: Basic YjN2T1ZfQ1MwTlVmVTVDZnBmVlVaMG1mSWtzYTpmam14Z2czSHlMZzh1NE1aSmtVbXNYXzBZYWcxUkMxcXBub1ZpdVp0ODBNYQ==' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=organization_switch' \
--data-urlencode 'token=eyJ4NXQiOiJyVDVGYi1Cd1doWUZYWE9JQjlnaG9NZDhfSWsiLCJraWQiOiJPV1JpTXpaaVlURXhZVEl4WkdGa05UVTJOVE0zTWpkaFltTmxNVFZrTnpRMU56a3paVGc1TVRrNE0yWmxOMkZoWkdaalpURmlNemxsTTJJM1l6ZzJNZ19SUzI1NiIsInR5cCI6ImF0K2p3dCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI2OTk3Mjk4Yy0xZDgyLTRiNWUtOWMyNS0wNWVlNWJjNTg5ODEiLCJhdXQiOiJBUFBMSUNBVElPTl9VU0VSIiwicm9sZXMiOiJVc2VyX0VkaXRvciIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImdyb3VwcyI6WyJncm91cDEiLCJncm91cDIiXSwiY2xpZW50X2lkIjoiYjN2T1ZfQ1MwTlVmVTVDZnBmVlVaMG1mSWtzYSIsImF1ZCI6ImIzdk9WX0NTME5VZlU1Q2ZwZlZVWjBtZklrc2EiLCJuYmYiOjE3MTE2ODkxOTgsImF6cCI6ImIzdk9WX0NTME5VZlU1Q2ZwZlZVWjBtZklrc2EiLCJvcmdfaWQiOiIxMDA4NGE4ZC0xMTNmLTQyMTEtYTBkNS1lZmUzNmIwODIyMTEiLCJzY29wZSI6Imdyb3VwcyBpbnRlcm5hbF9vcmdfdXNlcl9tZ3RfY3JlYXRlIGludGVybmFsX29yZ191c2VyX21ndF9kZWxldGUgaW50ZXJuYWxfb3JnX3VzZXJfbWd0X2xpc3QgaW50ZXJuYWxfb3JnX3VzZXJfbWd0X3VwZGF0ZSBpbnRlcm5hbF9vcmdfdXNlcl9tZ3RfdmlldyBpbnRlcm5hbF91c2VyX21ndF9jcmVhdGUgaW50ZXJuYWxfdXNlcl9tZ3RfZGVsZXRlIGludGVybmFsX3VzZXJfbWd0X2xpc3QgaW50ZXJuYWxfdXNlcl9tZ3RfdXBkYXRlIGludGVybmFsX3VzZXJfbWd0X3ZpZXcgb3BlbmlkIHJvbGVzIiwiZXhwIjoxNzExNjkyNzk4LCJvcmdfbmFtZSI6IlN1cGVyIiwiaWF0IjoxNzExNjg5MTk4LCJqdGkiOiIzYzE5M2JmMS0xYjY5LTRiMGUtYTBjOS1jOGVlNWI1NjUxYmUifQ.Yhqv_yKHnMgAAaTDVtweTK3dFnZkYiICYtUFWSBuc0NUgtli4tSBVMsF9sgzluRF1zLHOW0SCzXX2FHaV9tdAO6wcGGOVrfRmLkGhsoSjmNivd7k-FqxcdrbvCBC-jn0-WWUWQnfd_lx3bW6tEyirwW7NHHl1M-5TOD1aoCCTLxgNya4n5IcmaExu3PxNIpbL_idv0h9xsAXrNbTip7m4b5Fa0lFjbkN3rmUuVR7iTmLLqo-863FOVkpUNq5f5tH4pCwu0Kj1VduHmeh6xdLlgtmTaomQwlHk4SssmK5kXdIeuKj8b_bm5rJv-tf2z5KOcwPj_I7IKmmcc8IRIvBkA' \
--data-urlencode 'scope=openid groups roles internal_org_user_mgt_delete internal_org_user_mgt_update internal_org_user_mgt_view internal_org_user_mgt_create internal_org_user_mgt_list internal_user_mgt_create internal_user_mgt_view internal_user_mgt_list internal_user_mgt_delete internal_user_mgt_update
' \
--data-urlencode 'switching_organization=91010f07-e82a-478e-b929-108cde8730d0'
```

Check the switched access token and ID token, groups and roles contains the user's assignments in root org
Scopes are properly derived,

**Comment by nilasini** [comment]
Closing it as it is already fixed.
