### ISSUE TITLE
Getting this exception when tried Authorization Code grant type

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#2014]
Description:

In IS 5.2.0  When generated an auth code and used that code to issue an access token. For the second time as expected, it's not giving an access token if use same code. But getting the following exception.

- Error occurred while issuing the access token for Client ID : PvIKDTcwavVbEUazqTpB82zVnWca, User ID null, Scope : [] and Grant Type : authorization_code 
java.lang.NullPointerException

According to [1], the issue is fixed in IS 5.3.0. But it is not fixed in IS 5.2.0.

[1] https://wso2.org/jira/browse/IDENTITY-5830

Suggested Labels:
Identity Server 5.2.0

Suggested Assignees:

Affected Product Version:
Identity Server 5.2.0

OS, DB, other environment details and versions:

Steps to reproduce:

Related Issues:
 https://wso2.org/jira/browse/IDENTITY-5830

**Comment by darshanasbg** [comment]
Closing the issue since this is already fixed in 5.4.0 with https://wso2.org/jira/browse/IDENTITY-5830
