### ISSUE TITLE
Idle Session Timeout value above 5 minutes is not being honored in v7.0

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#20181]
**Describe the issue:**

The Idle Session Timeout value that is configured via the Console app in WSO2 Identity Server v7.0 is not honored when the value is above 5 minutes. When the modal with "_It looks like you have been inactive for a long time_" appears and the user clicks on the "_Go back_" button after the idle timeout period, the user is not logged out, contrary to the behavior in the carbon management console that the new Console replaces.

![image](https://github.com/wso2/product-is/assets/32578617/745ef176-2bdc-4050-b356-7bd4e00a2c64)

Upon further analysis, it was observed that the "_console.session.params.sessionRefreshTimeOut_" property was set to 5 minutes by default, which meant that the console app executes _/authorize_ API calls with the _prompt=none_ parameter in 5-minute intervals to refresh the session. Since the default Idle Session timeout value is 15 minutes, this means that the user will not get logged out after 15 minutes and the user will be able to continue using the session after clicking on the "Go back" button.

This needs to be fixed so that the _Idle Session Timeout_ value configured in the UI is being honored and has precedence over recovering the session. A workaround is to set the sessionRefreshTimeOut value to one that is larger than that of the configured Idle Session Timeout in the _deployment.toml_ file.

```
[console.session.params]
sessionRefreshTimeOut = 28800.0
```

Additionally, when performing the above analysis, it was observed that the Console app also does not perform _checksession_ calls according to the defined time interval. This should also be fixed along with the above.

[1] - https://is.docs.wso2.com/en/next/guides/account-configurations/login-security/session-management/

**Environment information** **:**
 - Product Version: v7.0

**Comment by JayaShakthi97** [comment]
Fixed with
- https://github.com/wso2/identity-apps/pull/6135
