### ISSUE TITLE
Magic link doesn't show up in the Passwordless filter under connection

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#20192]
**Describe the issue:**
Even though the magic link is a passwordless connection, it will not filtered out when the connections are filtered with Passwordless tag.

- When all the connections are listed
<img width="1124" alt="Screenshot 2024-04-13 at 18 58 41" src="https://github.com/wso2/product-is/assets/25483865/3c18f05e-968f-4169-88bc-fc5fe601d6ec">

- When the passwordless connections filter is selected
<img width="1388" alt="Screenshot 2024-04-13 at 18 58 50" src="https://github.com/wso2/product-is/assets/25483865/15c9cf5c-7777-45db-90db-329cec6565d6">

The invoked API is:
```
GET https://localhost:9443/t/carbon.super/api/server/v1/authenticators?filter=(tag+eq+Passwordless)
```
Response is:
```
[
    {
        "id": "RklET0F1dGhlbnRpY2F0b3I",
        "name": "FIDOAuthenticator",
        "displayName": "Passkey",
        "isEnabled": true,
        "type": "LOCAL",
        "tags": [
            "MFA",
            "Passwordless",
            "Passkey",
            "APIAuth"
        ],
        "self": "/api/server/v1/configs/authenticators/RklET0F1dGhlbnRpY2F0b3I"
    },
    {
        "id": "ZW1haWwtb3RwLWF1dGhlbnRpY2F0b3I",
        "name": "email-otp-authenticator",
        "displayName": "Email OTP",
        "isEnabled": true,
        "type": "LOCAL",
        "tags": [
            "Passwordless",
            "MFA",
            "APIAuth"
        ],
        "self": "/api/server/v1/configs/authenticators/ZW1haWwtb3RwLWF1dGhlbnRpY2F0b3I"
    },
    {
        "id": "c21zLW90cC1hdXRoZW50aWNhdG9y",
        "name": "sms-otp-authenticator",
        "displayName": "SMS OTP",
        "isEnabled": true,
        "type": "LOCAL",
        "tags": [
            "Passwordless",
            "MFA",
            "APIAuth"
        ],
        "self": "/api/server/v1/configs/authenticators/c21zLW90cC1hdXRoZW50aWNhdG9y"
    }
]
```

**How to reproduce:**
1. Login to Console
2. Navigate to Connections
3. Select "Passwordless" filter
4. Magic link connection will not be displayed

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5641
