### ISSUE TITLE
[Doc] No mention of how to specify multiple grant types when using 'OAuth/OpenID Connect' admin APIs

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2019]
In the request body of 'OAuth/OpenID Connect' configuration in [1] there's an option to specify grant types. But in the table of Input Parameters, there's no mention of how to specify multiple grant types with the message body.

[1] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by omindu** [comment]
Grant types should be separated with a whitespace in the request parameter.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
