### ISSUE TITLE
URL validations are missing when creating BPS engine profile

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2021]
**Steps**
- Login to IS and access Configure > Workflow Engine Profiles > Add
- Enter invalid URLs  for BPS Manager Host Services and URL BPS Worker Host Services URL and Save

**Issue**
- There must be a validation to valid whether URL is in correct URL format

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
