### ISSUE TITLE
Masking with regex for SMS OTP

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#20221]
Currently, the SMS OTP provides masking capability with the option to mask either the first few digits or the last few digits, as follows:
```
[authentication.authenticator.sms_otp.parameters]
screenUserAttribute = "http://wso2.org/claims/mobile"
noOfDigits = 4
order = backward
```
However, introducing masking capability with a regex similar to #7711 would be a significant improvement.

**Comment by JayaShakthi97** [comment]
Fixed with;
- https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/195
