### ISSUE TITLE
Custom outbound provisioning connectors cannot be selected from the new console

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#20222]
**Describe the issue:**

Custom outbound provisioning connectors added to the drop-ins folder are not visible in the Outbound Provisioning Connectors. This is because we have hard-coded the values at [1].

[1] - https://github.com/wso2/identity-apps/blob/master/features/admin.identity-providers.v1/components/meta/connectors.ts

**How to reproduce:**

- Add a custom outbound provisioning connector as mentioned in [1].
- Add a connection, navigate to the Outbound Provisioning section, and click on "New Connector".
- The connectors that are visible are Google, SCIM, and Salesforce. However, the custom one is not displayed.

[1] - https://is.docs.wso2.com/en/6.1.0/references/extend/provisioning/write-an-outbound-provisioning-connector/

**Expected behavior:**

The custom one should also be displayed alongside the default ones.

**Environment information:**
 - Product Version: IS 7.0.0
 - OS: Ubuntu 22.04.2 LTS
 - Database: H2
 - Userstore: JDBC

---

**Comment by JayaShakthi97** [comment]
Improvement is introduced with
- https://github.com/wso2/identity-apps/pull/6217
