### ISSUE TITLE
[Doc] No mention of what values need to specify for grant types when using 'OAuth/OpenID Connect' admin APIs

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2023]
When automating OIDC/Oauth2 flows by refering [1], user has to specify parameters which included in request payload under 'Configuring OAuth/OpenID Connect' section. But to specify Grant types, there's no mention of values which need to be filled within the payload. 

According to the Admin API (OAuthAdminService), following values can be used within '<xsd1:grantTypes>?</xsd1:grantTypes>'

- refresh_token
- urn:ietf:params:oauth:grant-type:saml2-bearer
- implicit
- password
- client_credentials
- iwa:ntlm, authorization_code
- urn:ietf:params:oauth:grant-type:jwt-bearer

[1] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
