### ISSUE TITLE
[UX] Improve the policy publish view 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2025]
![policypublish](https://user-images.githubusercontent.com/6497326/34713261-abab7f68-f54b-11e7-89fb-6857a8561bed.png)

This UI can be added as a modal window on the previous page. The first option is simple dropdown action items. Enable/Disable can be a simple toggle button, policy version can be dropdown list & order is a text filed with default number

IMHO Current UI adds a cognitive overload to the user.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
