### ISSUE TITLE
[Doc] Broken images in Configure a custom connector section

### ISSUE THREAD

**Issue by JayaShakthi97** [wso2/product-is#20250]
**Is your suggestion related to a missing or misleading document? Please describe.**

Check: https://is.docs.wso2.com/en/latest/guides/authentication/configure-custom-connector/#map-groups-with-wso2-identity-server

![image](https://github.com/wso2/product-is/assets/37938529/4a6ee61c-a149-48ff-bab5-34008899936d)

**Describe the improvement**

- Need to be updated with proper images.

**Comment by KaveeshaPiumini** [comment]
This issue is fixed, hence closing the issue

![FireShot Capture 004 - Configure a custom connector - WSO2 Identity Server - is docs wso2 com](https://github.com/user-attachments/assets/a4f08abf-909c-4def-a171-cf6820cbde9d)
