### ISSUE TITLE
Custom Authentication option UI not get populated in Login Page

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#20265]
**Describe the issue:**
When the custom authenticator added using [1] to application, in the login page, the authentication options shows as below.

<img width="440" alt="Screenshot 2024-04-25 at 11 08 18" src="https://github.com/wso2/product-is/assets/47152272/adb18ed6-1312-4048-95c9-22bb0e87c32a">

**How to reproduce:**
- Please follow [1].

**Expected behavior:**
- Option should be there to select.

**Environment information**
 - Product Version: IS 7.0.0
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

[1] https://is.docs.wso2.com/en/latest/references/extend/authentication/write-a-custom-local-authenticator/

**Comment by mpmadhavig** [comment]
Login flow UI

<img width="434" alt="Screenshot 2024-04-25 at 12 18 22" src="https://github.com/wso2/product-is/assets/47152272/99314a05-65c2-4f18-a0b8-d4bbc6bbf58d">

**Comment by pavinduLakshan** [comment]
Do the available authenticators come in the url as query parameters?

**Comment by pavinduLakshan** [comment]
> Login flow configuration UI:
> 
> <img alt="Screenshot 2024-04-25 at 12 18 22" width="434" src="https://private-user-images.githubusercontent.com/47152272/325502733-99314a05-65c2-4f18-a0b8-d4bbc6bbf58d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTczMTUsIm5iZiI6MTcxODI1NzAxNSwicGF0aCI6Ii80NzE1MjI3Mi8zMjU1MDI3MzMtOTkzMTRhMDUtNjVjMi00ZjE4LWEwYjgtZDRiYmM2YmJmNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA1MzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1Y2UxZDEzMDlkZmQ0ODAyNTdkMWQ5Y2ZjMmRhM2Q0NWMyZjdlYzU4MDkxZDU2ZjdhNGNkNDk4NjI3ZjIxMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ajRo79U9KGKx-9oj4kARmfnueQHzpUiNbMM-wnoSrX4">
> This is the expected view.

As per the offline discussion today, in this case, the authenticator is not present in the query parameters.

**Comment by pavinduLakshan** [comment]
When there is one or more authenticators with the custom authenticators, all authenticators are present in the query param

**Comment by nilasini** [comment]
@sadilchamishka are we good to close this issue?
