### ISSUE TITLE
User Stores won't work in xacml policy if name isn't in capital 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2026]
How to reproduce:

1. Add Sp
2. Create secondary User store
3. Use authn_user_store_based_policy_template
4. Edit with user store name: foostore
5. Policy won't work

When user adding secondary user store the listing shows it in simple letters, but in policy, we need to use that in the capital. (ALLCAPS) 
![bugpolicy](https://user-images.githubusercontent.com/6497326/34717089-d9b7fd3a-f557-11e7-8034-9440082053bb.png)
![userstore](https://user-images.githubusercontent.com/6497326/34717090-d9f6bd2c-f557-11e7-91b5-7c198ea2fa4e.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
