### ISSUE TITLE
Self sign up - The account confirmation mail for a tenant doesn't load

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-is#2028]
Followed the steps in [1] to register a user to a specific tenant and encountered the following:

1.  Clicked the account confirmation button in the mail.
2. The mail doesn't load.
<img width="1098" alt="screen shot 2018-01-09 at 18 09 46" src="https://user-images.githubusercontent.com/22474854/34721311-5028912c-f568-11e7-81a4-cd7d16e867c0.png">

3. When you go to the dashboard and try to login with the registered user details, the account is not verified message is given.
<img width="331" alt="screen shot 2018-01-09 at 18 10 18" src="https://user-images.githubusercontent.com/22474854/34721347-63cbe210-f568-11e7-93e9-48426aa4c964.png">

[1] https://docs.wso2.com/display/IS540/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Selfsignupforothertenantusers

**Comment by ashensw** [comment]
Fixed with PRs [1][2].
[1] https://github.com/wso2/carbon-identity-framework/pull/1270
[2] https://github.com/wso2/carbon-identity-framework/pull/1272
