### ISSUE TITLE
[Migration] IS-7.0.0 scripts fails on Oracle databases

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#20293]
**Describe the issue:**

The scripts to migrate to IS-7.0.0 when using Oracle databases insert multiple record on the IDN_CONFIG_TYPE table [1]. However this sentence does not meet Oracle's INSERT specifications [2] causing a syntax error (`INSERT ALL` clause is missing at the beginning of the statement):

```
Error occurred while executing :  INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES ('8469a176-3e6c-438a-ba01-71e9077072fa', 'APPLICATION_BRANDING_PREFERENCES', 'A resource type to keep the application branding preferences') INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES ('f4e83b8a-d1c4-a0d6-03a7-d48e268c60c5', 'PK_JWT_CONFIGURATION', 'A resource type to keep the tenant private key jwt configuration.') INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES ('9ec61e9d-f0e6-4952-9a09-ab842aeb2db2', 'ATTRIBUTE_CONFIGURATION', 'A resource type to store attribute related configurations.') INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES ('132b0ee6-43e0-462d-8b4b-15b68109d71d', 'ORGANIZATION_CONFIGURATION', 'A resource type to keep the organization configurations.') INTO IDN_CONFIG_TYPE (ID, NAME, DESCRIPTION) VALUES ('1fc809a0-dc0d-4cb2-82f3-58934d389236', 'CUSTOM_TEXT', 'A resource type to keep the tenant custom text preferences.') SELECT 1 FROM dual
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:349)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:265)
        ... 32 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00900: invalid SQL statement
```

**Expected behavior:**

IS-7.0.0 Migration scripts should run without syntax errors.
- <MIGRATION_CLIENT>/migration-resources/7.0.0/dbscripts/step1/identity/oracle.sql
- <MIGRATION_CLIENT>/migration-resources/7.0.0/dbscripts/step1/identity/oracle_rac.sql

**Environment information:**
 - Product Version: IS 7.0.0
 - Database: Oracle

---

[1] https://github.com/wso2-enterprise/identity-migration-resources/blob/e1530f3a321b8f28143c95b551af27029836e0f8/components/org.wso2.is.migration/migration-resources/7.0.0/dbscripts/step1/identity/oracle.sql#L1-L12
[2] https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/INSERT.html

**Comment by AnjanaSamindraPerera** [comment]
The Oracle syntax issue is fixed now hence closing the issue.
