### ISSUE TITLE
Migration Client could not handle proper migrations of existing `secretKey`

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#20296]
**Description :**
As per the **$title**, it was observed the new claims [1] introduced need to be created along with [2] in `IDN_IDENTITY_USER_DATA`.
Currently, migration client does not handle all required claims. Same case for sync client too.

Because of this [1] missing identity claims of TOTP, following behaviour happens:

- When TOTP is 2nd factor after Basic Auth as 1st step=>
- Authentication is fine [3] with 5.10 QR as secretKey was migrated but,
- when redirected to profile [4] there is no TOTP enabled and asking to recapture QR.

[1]
http://wso2.org/claims/identity/secretkey <-- only this is being migrated
http://wso2.org/claims/identity/totpEnabled
http://wso2.org/claims/identity/verifySecretkey
http://wso2.org/claims/identity/failedTotpAttempts
[2] http://wso2.org/claims/identity/secretkey
[3] 
<img width="891" alt="326658715-1c1a28a1-cef2-4fe1-89b2-1204d6b2d854" src="https://github.com/wso2/product-is/assets/15968322/e4e2240c-e277-4f2b-b64d-bf4412dcc31c">
[4] 
<img width="932" alt="326659850-642d8a35-9745-4b0c-8b4b-47765dc50c2c" src="https://github.com/wso2/product-is/assets/15968322/4fa81f0d-8818-404b-b4d6-d3e80d0ffce8">
Product :IS-5.10.0 to 6.1.0

**Comment by nilasini** [comment]
@amanda-ariyaratne are we good to close this issue with the PR https://github.com/wso2-enterprise/identity-migration-resources/pull/428

**Comment by amanda-ariyaratne** [comment]
@nilasini Yes. closing the issue
