### ISSUE TITLE
[UX] Manage FIDO U2F Device User portal improvements 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2030]
Currently, we do have a page for  Manage FIDO U2F Devices. IMO we can improve this bit on the Visibility of system status

1. we can improve this by adding few extra status on the page. When user clicks on "Attach FIDO Token" we need to change that to loading icon and disable it until the registration finish. Otherwise user may click this multiple times
2. Show image regarding the touch the device
3. Give feedback on registration on the same UI with state change

![3 security and login2](https://user-images.githubusercontent.com/6497326/34734092-93930046-f590-11e7-9b9c-cfc119305c42.png)
![3 security and login](https://user-images.githubusercontent.com/6497326/34734093-93c7edba-f590-11e7-8687-7138498f7bdc.png)

  Some Suggestions from the FB

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
