### ISSUE TITLE
[Doc] Include which parameters are mandatory and which are optional when specifying values for 'OAuth/OpenID Connect' payload with admin APIs

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2032]
Input parameters table in [1], having values which use in 'OAuth/OpenID Connect' payload. For each parameter, it's better to mention whether it's a mandatory one or optional one.

[1] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
