### ISSUE TITLE
CallbackUrl in OAuth/OpenID Connect payload specifies as optional but documents explain that it should be mandatory 

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2033]
Admin service for adding an oAuth application [1] has 'CallbackUrl' as an optional parameter in the payload. But the document [2] mentioned 'CallbackUrl' parameter is a mandatory one to specify.

[1] https://localhost:9443/services/OAuthAdminService?wsdl
[2] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
