### ISSUE TITLE
[Doc] Add a reference for 'IWA-NTLM' grant type in 'Service Provider Configurations used with APIs' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2034]
Input parameters table in [1], describes 'IWA-NTLM' as a grant type which similar to the password grant type, but it is specific to Microsoft Windows users. But in order to refer more, it's better to have a reference.

[1] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
