### ISSUE TITLE
Missing information in App Native Authentication documentation

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#20347]
**Is your suggestion related to a missing or misleading document? Please describe.**
The official App Native Authentication documentation [1] has gaps on how federated authentication works and the information related to available authentication options. 

[1] - https://is.docs.wso2.com/en/latest/guides/authentication/add-app-native-authentication/

**Describe the improvement**
Include information on authentication options including any special considerations (ex: working mode of federation options).

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by indeewari** [comment]
Federated authentication via api-based authentication.

- Native mode

https://is.docs.wso2.com/en/latest/references/app-native-authentication/#scenario-4-user-selects-federated-authentication-native-mode

- Redirect mode

https://is.docs.wso2.com/en/latest/references/app-native-authentication/#scenario-5-user-selects-federated-authentication-redirect-mode

**Comment by indeewari** [comment]
Closing the issue as the above links cover the missing information related to app-native authentication in federated authentication in public documentation.

**Comment by Thumimku** [comment]
Related PR: https://github.com/wso2/docs-is/pull/4614
