### ISSUE TITLE
[Doc] Old doc link provided for 'Mitigating Authorization Code Interception Attacks' in 'Service Provider Configurations used with APIs' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2035]
'Mitigating Authorization Code Interception Attacks' link in table for the parameter 'pkceMandatory' under 'Configuring OAuth/OpenID Connect ' section [1] pointed to an old doc link.

[1] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
