### ISSUE TITLE
[Doc] pkceSupportPlain parameter usage needs to explain more in 'Service Provider Configurations used with APIs' doc 

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2036]
Input parameters table in [1], having a parameter called 'pkceSupportPlain' which has an explanation just as - Set true if you are using PKCE. It's better to give a brief explanation on what's the usage of this parameter and how it can use with grant type like - authorization code.

[1] https://docs.wso2.com/display/IS540/Service+Provider+Configurations+used+with+APIs#ServiceProviderConfigurationsusedwithAPIs-ConfiguringOAuth/OpenIDConnect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
