### ISSUE TITLE
[Doc] Provide more information on "Attribute Consuming Service Index" 

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2037]
https://docs.wso2.com/display/IS530/Configuring+SAML+2.0+Web+SSO

Not enough information provided on how to fill "Attribute Consuming Service Index" value. Please provide how users can provide this value and what the purpose of this.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
