### ISSUE TITLE
Giving executable file for Identity Anonymization tool

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#20375]
Currently we are asking developers to build the source code (snapshot) to get the Identity Anonymization tool [1].  It'll be good to release the tool and provide the executable file to download from the website. 

[1] https://is.docs.wso2.com/en/latest/deploy/configure/databases/remove-references-to-deleted-user-identities/#building-the-identity-anonymization-tool

**Comment by madurangasiriwardena** [comment]
This is done for IS 7 now. https://github.com/wso2/docs-is/pull/4592
