### ISSUE TITLE
Roles tab is missing in Applications

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#20380]
**Describe the issue:**
From the roles tab inside the application edit, we can configure the audienace of the roles and we can create/assign application roles to the application as well. Now that is not available in there.

<img width="1670" alt="image" src="https://github.com/wso2/product-is/assets/19262008/3b5791d0-664d-4baf-92e8-4fbfcd1e194a">

This happened after the fix [1]. This config was validated in the application edit page[2]. This config was introduced for a previous version of the role management we need to come up with a solution for this.

1. Enable the applicationRoles.
2. Introduce a new config and find the references of the applicationRoles and change those configs to the new config to handle the new implementation.

[1] https://github.com/wso2/identity-apps/pull/6240
[2] https://github.com/wso2/identity-apps/blob/6d590c068d5e77cc2d3530703d1c1b291eeadd49/features/admin.extensions.v1/configs/application.tsx#L448

**How to reproduce:**
1. Go to console and create an app.
2. Go to edit page and the roles tab is not available there.

**Expected behavior:**
- Roles tab should be available in the application edit.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.1-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by dasuni-30** [comment]
Closing the issue since this is done.
