### ISSUE TITLE
[Improvement] Add details on tooltip with format for the name of service provider when creating a SP

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2039]
== Environment ==

IS 5.4.0 Update 3 - 2 node cluster
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

Login to management console, click 'Add' under Service Providers
Register a service provider with special character

== Actual Outcome ==

There's an error pop up and says that the SP name is invalid as below,

![provided service provider name is invalid](https://user-images.githubusercontent.com/8849472/34763890-b5b920ec-f612-11e7-894f-d706df83a230.png)

== Suggestion ==

Add information on current tooltip with format for adding the name for service provider

**Comment by sagara-gunathunga** [comment]
We have plan to devalop new admin portal and new user portal will incorporate these changes to portal.
