### ISSUE TITLE
Unable to understand the exact reason from the pop up when adding a service provider with a long description

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2040]
== Environment ==

IS 5.4.0 Update 3 - 2 node cluster
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

- Login to management console, click 'Add' under Service Providers
- Register a service provider with a long description (may be with more than 1000 characters)

== Actual Outcome ==

There's an error pop up and says "Error while Creating Application" as below

![no reason for long description](https://user-images.githubusercontent.com/8849472/34764465-a57b4b90-f614-11e7-9c0c-44f5b04ef9c7.png)

== Suggestion ==

Since the popped up error message doesn't convey the issue exactly, it's better to modify the error message and ask user to limit the characters in description (may be saying, less than $max characters)

**Comment by madurangasiriwardena** [comment]
UI validation is done with https://github.com/wso2/carbon-identity-framework/pull/1794. We can do a back end validation also.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
