### ISSUE TITLE
[UI] Add 'User Access Token Expiry Time' and 'Refresh Token Expiry Time' as mandatory fields in UI when adding OAuth/OpenID Connect Configuration while creating SP

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2041]
== Environment ==

IS 5.4.0 Update 3 - 2 node cluster
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

- Login to management console, click 'Add' under Service Providers
- Register a service provider
- Go to 'Inbound Authentication Configuration' and click configure in 'OAuth/OpenID Connect Configuration'
- Provide a callback url
- Keep empty at least one from 'User Access Token Expiry Time' and 'Refresh Token Expiry Time'

== Actual Outcome ==

There're warning pop up to fill the respective field.

![invalid value for user access token expiry time](https://user-images.githubusercontent.com/8849472/34766735-969f17da-f61b-11e7-9967-c87d2cf11171.png)

== Expected Outcome ==

Mention above fields as mandatory in UI or keep the optional by allowing to save the oAuth applciation without any if the above 2 fields

**Comment by hauntingEcho** [comment]
these fields should not be mandatory if only the client-credentials grant type is enabled.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
