### ISSUE TITLE
Adding 'application Access Token Expiry Time' with empty or non numeric value will pop up an error but proceed with updating

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2042]
== Environment ==

IS 5.4.0 Update 3 - 2 node cluster
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

- Login to management console, click 'Add' under Service Providers
- Register a service provider
- Go to 'Inbound Authentication Configuration' and click configure in 'OAuth/OpenID Connect Configuration'
- Provide a callback url
- Keep empty or provide num numeric value (ex -abcd) for 'Application Access Token Expiry Time'
- Click 'Update'

== Actual Outcome ==

There's an error message pop up as below but proceed with update action. Here, the given value doesn't stored for the field but it doesn't stop when an incorrect value provided.

![error occurred while updating the application1](https://user-images.githubusercontent.com/8849472/34767623-9af9e6b8-f61e-11e7-9e98-186ca0ba2ec1.png)

== Expected Outcome ==

Once after the error message, update shouldn't process to the next step.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
