### ISSUE TITLE
Improve Add administrator docs to align with the product functionality

### ISSUE THREAD

**Issue by lashinijay** [wso2/product-is#20499]
**Is your suggestion related to a missing or misleading document? Please describe.**

There are several incorrect information in https://is.docs.wso2.com/en/latest/guides/users/manage-administrators/

1. Admins can change passwords of other admins. Hence the note section needs to be removed.
2. When adding users there is no such step as **Add Role**. Hence step 5 needs to be removed from https://is.docs.wso2.com/en/latest/guides/users/manage-administrators/#add-an-administrator
3. Users that has been granted administrator privileges via admin group are **not listed** in the Console Settings --> Administrators section. Hence the note needs to be removed.
4. Need to convey the users that by default, the administrator role is assigned to admin group.

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/docs-is/pull/4613
