### ISSUE TITLE
Unable to startup the IS 7 With Oracle Rac DB

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#20493]
**Describe the issue:**

Unable to startup the IS 7 With Oracle Rac DB , due to getting following error traces

```
[2024-06-03 16:34:28,216] []  INFO {org.opensaml.core.config.InitializationService} - Initializing OpenSAML using the Java Services API
[2024-06-03 16:34:52,144] [] ERROR {org.wso2.identity.apps.common.internal.AppsCommonServiceComponent} - Failed to activate identity apps common service component. org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occured while assigning administrator role to the admin user.
	at org.wso2.identity.apps.common.util.AppPortalUtils.initiatePortals(AppPortalUtils.java:343)
	at org.wso2.identity.apps.common.util.AppPortalUtils.initiatePortals(AppPortalUtils.java:267)
```

**How to reproduce:**

A guide to setup a oracle rac db and reproducing can be assist

Reference 
https://is.docs.wso2.com/en/latest/deploy/configure/databases/carbon-database/change-to-oracle-rac/

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asekawa** [comment]
The above error trace is probably generating from the following point 

https://github.com/wso2/carbon-identity-framework/blob/0f850f34dcff73ebf76229a751d4ad6447415b85/components/role-mgt/org.wso2.carbon.identity.role.v2.mgt.core/src/main/java/org/wso2/carbon/identity/role/v2/mgt/core/dao/RoleDAOImpl.java#L210

**Comment by bhagyasakalanka** [comment]
Maybe Database tables  or columns are missing in the oracle instance

**Comment by asekawa** [comment]
> Maybe Database tables or columns are missing in the oracle instance

@bhagyasakalanka we were able to create  all the dbs and able to successfully connect through SQL server as well

**Comment by Xaldelare** [comment]
It s same on postgres. the problem come from module WSO2 IS - IS Profile Generation. 
Just try to build is 7 rc7 , 6.x and other all failled to this module.

**Comment by Xaldelare** [comment]
for me i tryed to put script in specifique schema. if i put all in public it work well.

**Comment by asekawa** [comment]
> It s same problem on: Product version: IS 7 rc7, Database: postgres. OS: linux rocky 8
> 
> @asekawa your link reference target version 6 not 7.
> 
> but it work fine with H2.

Updated the reference version

**Comment by Shenali-SJ** [comment]
Below are the primary findings we have observed.
- The "Administrator" role is created during the CONSOLE app creation ([AppPortalUtils.java](https://github.com/wso2/identity-apps/blob/%40wso2is/console%402.12.46/identity-apps-core/components/org.wso2.identity.apps.common/src/main/java/org/wso2/identity/apps/common/util/AppPortalUtils.java#L405))
- This is triggered only during the first execution.

Until a definitive solution is determined, we could mitigate this issue by attempting the following workaround.
- Delete the CONSOLE app from the `SP_APP` table from the Oracle RAC database
`DELETE FROM SP_APP WHERE APP_NAME = 'Console';`
- Further, make sure that the CONSOLE app has not been added to the cache.

---

Furthermore, we faced the below issue during the testing process.
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/1577#issuecomment-2129276938 

---

cc: @inthirakumaaran

**Comment by shanggeeth** [comment]
Closing this since the fix is delivered with https://github.com/wso2/carbon-identity-framework/pull/5796
