### ISSUE TITLE
Validate token bindings should be enabled for Renew JWT without revoking existing token

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#20513]
**Describe the issue:**
In IS 5.10, it is necessary to enable "Validate token bindings" in the service provider configurations to facilitate renewing JWT without revoking the existing token [1][2]. This requirement is in addition to the configuration mentioned below. However, in IS 5.11, it is sufficient to add only the configuration mentioned below. Ideally, there shouldn't be a requirement to enable "Validate token binding" to enable this feature.
```
[oauth.jwt.renew_token_without_revoking_existing]
enable = true
allowed_grant_types = ["client_credentials","password", ...]
```

**How to reproduce:**
Ref: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2018 (documentation not available, which should be fixed as well).

**Expected behavior:**
The "Renew JWT without revoking existing token" feature should work without enabling Validate token bindings from SP configurations.

**Environment information** 
 - Product Version: IS 5.10.0

**Related issues:**
[1] https://github.com/wso2/product-is/issues/19927
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2018

**Comment by lashinijay** [comment]
This issue is not reproducing in lastest product. Hence closing this issue.
