### ISSUE TITLE
Management Console IDP filtering does not work with the search

### ISSUE THREAD

**Issue by UpekshaGalappaththi** [wso2/product-is#20522]
**Describe the issue:**
When list IDP function with a filter is invoked in the management console, a soap request will be sent with the filter. In IS 5.10 this filter parameter is sent as follows.

For 'Abc*' -  `<ns4:filter>Abc*</ns4:filter>`
Correct filter - `<ns4:filter>name sw "Abc"</ns4:filter>`

For '*Abc' - `<ns4:filter>*Abc</ns4:filter>`
Correct filter- `<ns4:filter>name ew "Abc"</ns4:filter>`

For 'Abc' - `<ns4:filter>Abc</ns4:filter>`
Correct filter- `<ns4:filter>name eq "Abc"</ns4:filter>`

When the filter parameter is sent as `<ns4:filter>Abc*</ns4:filter>`, in [1] the error will be thrown[2] and the IDP will not be listed. If sent according to the given example, it will work as expected.

**How to reproduce:**
Configure an Identity Provider using the management console and search for it using any method above

**Expected behavior:**
The relevant IDP should be listed when searched using *

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]

[1] https://github.com/wso2/carbon-identity-framework/blob/v5.17.5/components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java#L1108
[2] https://github.com/wso2/carbon-identity-framework/blob/v5.17.5/components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java#L1120

**Comment by AfraHussaindeen** [comment]
Closing the issue as the fix is available in both reported IS version and the master
