### ISSUE TITLE
Enable myAccount status indicator

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#20541]
**Describe the issue:**
With this effort, myAccount can be enabled and disabled and hence the indicator has to work accordingly.

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dasuni-30** [comment]
Closing the issue since this is done.
