### ISSUE TITLE
git issue 2053

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#2054]
duplicate key value violates unique constraint" error with Postgres SQL when trying to add a user who is already there in one user store domain to a different user store domain

public jira : https://wso2.org/jira/browse/IDENTITY-7297

**Comment by omindu** [comment]
@denuwanthi Was the error in only 5.2.0 ?

**Comment by denuwanthi** [comment]
@omindu It occurs in 5.4.x as well

**Comment by omindu** [comment]
Thanks. Please close the issue once this is fixed in public branch.

**Comment by denuwanthi** [comment]
Fixed with https://github.com/wso2/carbon-kernel/commit/6fe9b785760a6d5dbd04bb13c66cb48fd0af7e77

**Comment by omindu** [comment]
Cool! Will this be shipped with next 5.4.0 update ?

**Comment by darshanasbg** [comment]
Fixed with IS 5.4.1
