### ISSUE TITLE
[IS 6.1] Unable to update application through SOAP request due to cache not being removed

### ISSUE THREAD

**Issue by UpekshaGalappaththi** [wso2/product-is#20553]
**Describe the issue:**
In IS 5.11 when an application is created using [1] API, the following[2] will be called and the cache will be removed from the AppInfoCache. In 6.1 however this behavior is not the same due to the If check we have introduced[3]. Here the issue arises, since initially we add the AppInfo cache without the AppID (Database autoincrement value) in[4] the App Info cache will not contain the App ID and when trying to execute the DB call to update application using the following[5] it will throw an error. 

An Or clause should be added to [3] to make sure the cache is removed in the application creation.

**How to reproduce:**
Use [1] to create an application.
Without waiting until 15 minutes (AppInfo cache timeout configured in the identity.xml) try to update the application using[6]

**Expected behavior:**
Should be able to successfully update the application

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 6.1]

---
[1] 
```curl --location --request POST 'https://localhost:9443/api/identity/oauth2/dcr/v1.1/register/' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=44EB0E0966FDEA755A6693F91E5DB711' \
--data-raw '{
    "client_name": "testApp",
    "token_type_extension": "JWT"
}'
```
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.4.111/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L136

[3] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v6.11.21/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L146

[4] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/31f7e95785b49245ad4d9249674877f8993ba601/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminServiceImpl.java#L522

[5] 
```curl --location --request POST 'https://localhost:9443/services/OAuthAdminService' \
--header 'Content-Type: text/plain' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://model.common.application.identity.carbon.wso2.org/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soapenv:Header/>
   <soapenv:Body>
            <xsd:updateConsumerApplication>
         <!--Optional:-->
         <xsd:consumerAppDTO>
            <xsd1:oAuthVersion>OAuth-2.0</xsd1:oAuthVersion>
            <xsd1:applicationAccessTokenExpiryTime>3600</xsd1:applicationAccessTokenExpiryTime>
            <xsd1:applicationName>testApp</xsd1:applicationName>
            <xsd1:audience xsi:nil="true"/>
            <xsd1:backChannelLogoutUrl xsi:nil="true"/>
            <xsd1:bypassClientCredentials>false</xsd1:bypassClientCredentials>
            <xsd1:callbackUrl xsi:nil="false"/>
            <xsd1:frontchannelLogoutUrl xsi:nil="true"/>
            <xsd1:grantTypes>client_credentials</xsd1:grantTypes>
            <xsd1:idTokenEncryptionAlgorithm>null</xsd1:idTokenEncryptionAlgorithm>
            <xsd1:idTokenEncryptionEnabled>false</xsd1:idTokenEncryptionEnabled>
            <xsd1:idTokenEncryptionMethod>null</xsd1:idTokenEncryptionMethod>
            <xsd1:idTokenExpiryTime>3600</xsd1:idTokenExpiryTime>
            <xsd1:oauthConsumerKey>XXXX</xsd1:oauthConsumerKey>
            <xsd1:oauthConsumerSecret>XXXX</xsd1:oauthConsumerSecret>
            <xsd1:pkceMandatory>false</xsd1:pkceMandatory>
            <xsd1:pkceSupportPlain>false</xsd1:pkceSupportPlain>
            <xsd1:refreshTokenExpiryTime>86400</xsd1:refreshTokenExpiryTime>
            <xsd1:renewRefreshTokenEnabled xsi:nil="true"/>
            <xsd1:requestObjectSignatureValidationEnabled>false</xsd1:requestObjectSignatureValidationEnabled>
            <xsd1:scopeValidators>Role based scope validator</xsd1:scopeValidators>
            <xsd1:state xsi:nil="true"/>
            <xsd1:tokenBindingType xsi:nil="true"/>
            <xsd1:tokenBindingValidationEnabled>false</xsd1:tokenBindingValidationEnabled>
            <xsd1:tokenRevocationWithIDPSessionTerminationEnabled>false</xsd1:tokenRevocationWithIDPSessionTerminationEnabled>
            <xsd1:tokenType>JWT</xsd1:tokenType>
            <xsd1:userAccessTokenExpiryTime>3600</xsd1:userAccessTokenExpiryTime>
            <xsd1:username>admin</xsd1:username>
         </xsd:consumerAppDTO>
      </xsd:updateConsumerApplication>

   </soapenv:Body>
</soapenv:Envelope>'
```

**Comment by amanda-ariyaratne** [comment]
This is fixed in IS 6.1. Not reproducible in the master branch.
