### ISSUE TITLE
Cannot change the default notification page in Magic Link Authenticator 

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#20562]
**Describe the issue:**

In the magic link authenticator , we cannot have a new url / customized page as the notification page. Currently it having as the "authenticationendpoint/magic_link_notification.do"[1]

[1]https://github.com/wso2-extensions/identity-local-auth-magiclink/blob/main/components/org.wso2.carbon.identity.application.authenticator.magiclink/src/main/java/org/wso2/carbon/identity/application/authenticator/magiclink/MagicLinkAuthenticator.java#L233

**How to reproduce:**
1. Set up the magic link authenticator [1]

**Expected behavior:**

We should be able to change the default hardcoded notification page URL from the configuration level(deployment.toml).

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0

[1]https://is.docs.wso2.com/en/6.1.0/guides/passwordless/magic-link/

**Comment by asha15** [comment]
Fixed in the master branch with : https://github.com/wso2/carbon-identity-framework/pull/5762, https://github.com/wso2-extensions/identity-local-auth-magiclink/pull/56

Magic link authenticator's notification page URL can be change using the following configuration

```
[authentication.authenticator.magiclink.parameters]
MagicLinkAuthenticationEndpointURL= "<notificationPageURL>"
```
