### ISSUE TITLE
[Migration Client] TOTP Enabled Claims Migration Query in IS Migration-Client Causing Syntax Error During Migration in ORACLE DB

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#20577]
**Describe the issue:**
The query "`SET_TOTP_ENABLED_CLAIM_SQL`" which is used to set the TOTP enabled claims in the `TOTPClaimDataMigrator` class in the IS migration-client (v1.0.274) is declared with a trailing semicolon. During the migration, it fails when executing order 18 under version 6.0.0 due to a syntax error caused by this semicolon.
The following error was observed during a migration in Oracle DB

```
ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped.
org.wso2.carbon.identity.core.migrate.MigrationClientException: An error occurred while updating user data for the claim http://wso2.org/claims/identity/totpEnabled
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended.
```

**How to reproduce:**
Run a migration from lower IS version to IS-6.1.0 for ORACLE DB (using ORACLE DB dump)

**Expected behavior:**
Executing the order 18 without an error
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-migration client (v1.0.274) 
 - OS: [e.g., Windows, Linux, Mac]
 - Database: ORACLE
 - Userstore: [e.g., LDAP, JDBC]

**Comment by nilasini** [comment]
@bhagyasakalanka are we good to close this issue?
