### ISSUE TITLE
Existing servlets cannot be edited to point to a different JSP pages in v7.0.0

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#20570]
**Describe the issue:**

Currently there is a way to configure custom servlets via the following _deployment.toml_ configuration.

```
[[accountrecoveryendpoint.servlet]]
name = "<name>"
url = "<url>"
jsp = "<jsp>"
```

However, if the above configuration is utilized to edit an existing servlet, the following error occurs.

```
ERROR {org.apache.tomcat.util.digester.Digester} - End event threw exception java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.IllegalArgumentException: The servlets named [recoverpassword.do] and [recoverpassword.do] are both mapped to the url-pattern [/recoverpassword.do] which is not permitted
...
ERROR {org.apache.tomcat.util.descriptor.web.WebXmlParser} - Parse error in application web.xml file at [file:/WEB-INF/web.xml] org.xml.sax.SAXParseException; systemId: file:/WEB-INF/web.xml; lineNumber: 260; columnNumber: 23; Error at line [260] column [23]: [The servlets named [recoverpassword.do] and [recoverpassword.do] are both mapped to the url-pattern [/recoverpassword.do] which is not permitted]
...
Caused by: java.lang.IllegalArgumentException: The servlets named [recoverpassword.do] and [recoverpassword.do] are both mapped to the url-pattern [/recoverpassword.do] which is not permitted
...
```

This indicates that existing servlets cannot be added using the same configuration utilized to add custom ones. This needs to be fixed since any migrations that occur from older versions to newer versions that had previously edited existing servlets will have to edit the relevant _.xml.j2_ file in order to persist that change, which is not a feasible solution in the long term.

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
@bhagyasakalanka are we good to close this issue?
