### ISSUE TITLE
Unable to startup the IS 5.11 With Oracle Rac DB[19c]

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#20587]
**Describe the issue:**

Unable to startup the IS 5.11 With Oracle Rac DB [19c], due to getting following error traces

`[2024-06-25 16:30:02,511] [] ERROR {org.wso2.carbon.identity.scim.common.internal.SCIMCommonComponent} - Error occurred while setting SCIM attributes for the Admin org.wso2.carbon.user.core.UserStoreException: Error in adding SCIM metadata to the admin in tenant domain: carbon.super`
**How to reproduce:**

[is.docs.wso2.com/en/latest/deploy/configure/databases/carbon-database/change-to-oracle-rac](https://is.docs.wso2.com/en/latest/deploy/configure/databases/carbon-database/change-to-oracle-rac/)
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduR** [comment]
This issue is occurring because there are some missing entries in the IDN_CLAIM and IDN_CLAIM_MAPPING tables. Further investigation is needed to determine why these entries were not added during the server startup. 

A possible cause could be the connection being terminated abruptly due to the slowness of the database instance itself.

**Comment by inthirakumaaran** [comment]
We have fixed the startup issues with Oracle Rac in IS 7.0.0 with this effort [1][2]

[1] "Testing Oracle Rac with IS 7.0.0"
[2] https://github.com/wso2/product-is/issues/20493

**Comment by inthirakumaaran** [comment]
Need to double check whether this is fixed for the IS 5.11.0

cc: @shanggeeth

**Comment by inthirakumaaran** [comment]
Closing this as we have fixed this in the master branch https://github.com/wso2/carbon-identity-framework/pull/5796
