### ISSUE TITLE
XACML policy order can be define with negative values but doesn't update the order exactly as defined

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2059]
== Environment ==

IS 5.4.0 Update 3 - 2 node cluster
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

Login to management console and add a XACML policy.
Go to PDP -> Policy View.
Click on 'Edit Order' of an available policy, enter a negative value (ex: -10) and Save.

== Actual Outcome ==

There's a pop up displayed and it says that ordering is successful. When check the order it's the same as before.

![entitlement policy will be ordered](https://user-images.githubusercontent.com/8849472/34831487-1e7824ca-f70d-11e7-8bd7-0ffc650668c6.png)

== Expected Outcome ==

Policy order update process shouldn't be proceed with negative values and an error should pop ups and saying to enter a valid value.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
