### ISSUE TITLE
Error messages disappear quickly when try to add an IDP with a long set of characters as name

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2060]
== Environment ==

IS 5.4.0 Update 3 - 2 node cluster
JDK - 1.8
DB - mysql 5.6
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate ==

Login to management console  and go to Add Identity Provider.
Give a long name (more than 400 characters may be) and Resgister the IDP

== Actual Outcome ==

There's a pop up displayed in a quick time and disappears fast.

== Expected Outcome ==

Error message displayed until user proceed with 'OK'

**Comment by nilasini** [comment]
This issue occurs with short length identity provider's name as well.

Fixed with https://github.com/wso2/carbon-identity-framework/pull/1287
