### ISSUE TITLE
[GraalJS] Need to add @HostAccess.Export for custom adaptive authentication functions

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#20613]
In IS when the default script engine is changed to GraalJS, for custom adaptive authentication functions that are written it is required to add `@HostAccess.Export`. This needs to be documented in the migration docs with the next IS release.

**Comment by shanggeeth** [comment]
- Alternatively they can use other script engines without the need for the above mentioned code level change.

1. If Identity Server is run with Java 17,
```
[AdaptiveAuth]
ScriptEngine = "openjdkNashorn"
```
In addition we need to run adaptive.sh script to download the required dependencies for OpenJDK Nashorn as documented in https://is.docs.wso2.com/en/latest/deploy/enable-adaptive-authentication/

2. If Identity Server is run with Java 11,
```
[AdaptiveAuth]
ScriptEngine = "nashorn"
```

**Comment by nilasini** [comment]
@shanggeeth migration doc has been updated with the above details. Can you please check and close the issue
