### ISSUE TITLE
[Doc] PDP Policy View image is not aligned in 'Writing a XACML Policy using a Policy Template' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2063]
The image for 'PDP Policy View', listed under 10th step in [1], needs to align with text.

![pdp policy view](https://user-images.githubusercontent.com/8849472/34845223-2a0b288c-f73a-11e7-8b3c-f9799da04638.png)

[1] https://docs.wso2.com/display/IS540/Writing+a+XACML+Policy+using+a+Policy+Template

**Comment by ShirazAzad** [comment]
This is already fixed.
