### ISSUE TITLE
Ciphertool version should be upgraded for  -Dchange functionality to work

### ISSUE THREAD

**Issue by kasundharmadasa** [wso2/product-is#2065]
The current ciphertool version 1.0.0-wso2v3 contains a bug that results in breaking the password change functionality [1]. This has been already resolved in the later versions of the ciphertool with the fix [2].

[1] https://wso2.org/jira/browse/CARBON-15382
[2] https://github.com/wso2/cipher-tool/pull/21

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
