### ISSUE TITLE
Improve "Additional Query Parameter" option to support dynamic query parameters

### ISSUE THREAD

**Issue by azinneera** [wso2/product-is#2066]
At the moment, the "Additional Query Parameter" option only supports passing static query parameters. Based on the customer request, this should be improved to support dynamic values as well.

**Comment by nilasini** [comment]
fixed with https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/57
merged with https://github.com/wso2-extensions/identity-outbound-auth-samlsso/commit/3be12c6b28bf38d161041dcd02661a9b73f29835
