### ISSUE TITLE
Conditional Authentication

### ISSUE THREAD

**Issue by SamFentie** [wso2/product-is#20665]
Conditional Authentication Does not work at all on manually turned on the Conditional authentication toggle and used the default script but it does not work at all am currently using wso2 7.0.0 and JDK version of 11
I even tried out the docker image but yet the same outcome.

**Comment by Malith-19** [comment]
Hi @SamFentie ,

Can you specify which conditional authentication method you tried (e.g., user role-based, user store-based, etc.)?

Also, you can ask these types of questions in our [Discord channel](https://discord.gg/DqHM43X6) to get help faster. Thank you.

WSO2 Discord server link: [WSO2 discord server](https://discord.gg/DqHM43X6)

**Comment by SamFentie** [comment]
user role-based and group-based

**Comment by Malith-19** [comment]
For the user role based, you need to either enable the user role audience to the organization [1] or create new roles under the application. 

1. changed the role audience to organization.
<img width="1145" alt="image" src="https://github.com/wso2/product-is/assets/79596630/7e4632a9-15b3-4fe4-a013-a0dc0fcd1f3d">

**Comment by SamFentie** [comment]
Thanks it worked
