### ISSUE TITLE
[DOC]Please remove the unwanted step from "JWT Token Generation" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#2067]
I was following steps mentioned in [1] to try out the JWT scenario. 
Please remove step 2 from the Document.
It's not required step to complete the scenario.

[1]https://docs.wso2.com/display/IS540/JWT+Token+Generation

**Comment by shavidissa** [comment]
Thank you! Updated [1].

Disclaimer: I did not test the document after doing this update. 

[1] https://docs.wso2.com/pages/viewpreviousversions.action?pageId=80728964
