### ISSUE TITLE
[DOC] Please alter the screenshot of the sample soap request in Calling the "OAuth2ValidationService with a valid token"

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#2068]
Under Calling the "OAuth2ValidationService with a valid token" section in [1], Please alter the sample soap request as below.

`
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://dto.oauth2.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:validate>
         
         <xsd:validationReqDTO>
            
            <xsd1:accessToken>
               
               <xsd1:identifier>221db3c6-70eb-36fa-9d0f-d213ecd32565</xsd1:identifier>
               
               <xsd1:tokenType>bearer</xsd1:tokenType>
            </xsd1:accessToken>
            
            <xsd1:context>
            </xsd1:context>
            
            <xsd1:requiredClaimURIs>http://wso2.org/claims/displayName</xsd1:requiredClaimURIs>
         </xsd:validationReqDTO>
      </xsd:validate>
   </soapenv:Body>
</soapenv:Envelope>
`

[1] https://docs.wso2.com/display/IS540/JWT+Token+Generation

**Comment by shavidissa** [comment]
Thank you, for the info and for sending the screenshot, Chalitha! :)
Updated docs [1].

[1] https://docs.wso2.com/display/IS540/JWT+Token+Generation
