### ISSUE TITLE
IS Console Branding Inconsistencies

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#20694]
**Describe the issue:**
The following inconsistencies were found in branding UI in IS Console.
1. Organization `Text` section UI seems to be missing its styling.
2. When navigated application branding section from the Organization `Text` section, app branding `Text` section will appear even though App branding `Text` section is disabled.
3. When navigated application branding section, the application selector drop down appears under branding toggle instead on its right side.

https://github.com/user-attachments/assets/169362db-0dee-432b-b800-2a789c461adc

**How to reproduce:**
1. Get the latest IS snapshot build.
2. Navigate to `Branding` > `Styles & Text`. 
5. Now select `Text` section inside Organization branding.
6. You will see that some styling seems to be missing in this section (ex: Locale, Screen)
7. Now click on `Application` in the toggle.
8. You will be navigated to the `Text` section in application branding which is disabled.
9. Moreover, take a look at how the application list selector drop down is positioned.

**Expected behavior:**
1. Organization `Text` section styling should consistent with other styling in IS Console.
2. User should not be able to navigate to the text section of application branding since it is disabled.
3. Application selector drop down should appear on the right side of the branding toggle.

**Environment information:**
 - Product Version: `IS 7.0.1 SNAPSHOT`
 - OS: `macos`
 - Database: `default`
 - Userstore: `default`

**Comment by savindi7** [comment]
```
1. Organization Text section UI seems to be missing its styling.
3. When navigated application branding section, the application selector drop down appears under branding toggle instead on its right side.
```

The above issues cannot be reproduced in the latest pack.

**Comment by savindi7** [comment]
This issue is fixed in IS
