### ISSUE TITLE
Sample for Provision federated users to a tenant 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2070]
As 6 solution in blog [1] its explain how to  Provision federated users to a tenant  using CarbonRemoteUserStoreManager. But in IS 5.4.0 [2] its not explained the steps to do it. Its better to add steps using an example so user easily  get an idea . In the doc [3] it only have details how to configure CarbonRemoteUserStoreManager.

[1]https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389In
[2]  https://docs.wso2.com/display/IS540/
[3] https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
