### ISSUE TITLE
Explanation on  why we need Carbon Remote User Store Manager 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2071]
In the documentation its not clearly explain why we need Carbon Remote User Store Manager 

[1]https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
