### ISSUE TITLE
[Doc]Document how to configure email as auser when configuring  Carbon Remote User Store Manager

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2073]
Document how to configure email as a user  when configuring  Carbon Remote User Store Manager
Add the note in documentation [1] on how to configure email as user  when configuring  Carbon Remote User Store Manager. Because some authenticators  use email as Username 
[1]https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
