### ISSUE TITLE
Missing Slash in Pagination Links of Organization Management API

### ISSUE THREAD

**Issue by HasiniSama** [wso2/product-is#20744]
**Describe the issue:**
In the Organization Management API, the pagination href returned in the response is missing a "/" between "server" and "v1". This leads to incorrect URLs and results in error codes.

**How to reproduce:**

1. Call any Organization Management API that supports pagination (e.g. /organizations GET API) with a lower limit than the total organizations.
2. Inspect the links section in the API response.
3. Observe the href value for pagination links.
4. Use the pagination link to call the next page, this returns an error.

https://github.com/user-attachments/assets/c0e3d2b3-9095-4586-a2b4-e3dc4914c893

```
"links": [
    {
        "href": "/api/serverv1/organizations?limit=1&recursive=false&after=MjAyNC0wNy0xMiAwNDo1OToyNC42MDY5NDc=",
        "rel": "next"
    }
]
```

**Expected behavior:**
The href value should include a "/" between "server" and "v1".

```
"links": [
    {
        "href": "/api/server/v1/organizations?limit=1&recursive=false&after=MjAyNC0wNy0xMiAwNDo1OToyNC42MDY5NDc=",
        "rel": "next"
    }
]
```

**Environment information**
 - Product Version: IS 7.10.0
 - OS: Mac

**Comment by kumardeepak5** [comment]
Hi @BimsaraBodaragama, @HasiniSama , 
are you currently working on this issue? I’d like to contribute. Could you please confirm?

**Comment by BimsaraBodaragama** [comment]
This is not yet prioritized. So, yeah, you can proceed with the fix. Thanks.

**Comment by kumardeepak5** [comment]
@BimsaraBodaragama, just a gentle reminder to review the related PR.

**Comment by AnuradhaSK** [comment]
Hi @kumardeepak5 

Thank you for your contribution!
We have reviewed and merged the changes.

Regards,
Anuradha
