### ISSUE TITLE
How to add user to  secondary user store in CarbonRemoteUserStoreManger

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2074]
**Steps**
- Configure Carbon Remote User Store Manager according to [1]
- Add secondary user store to  the remote server (primary LDAP, secondary  JDBC)
- Configure IDP

**Issue**
Need to provision users to to the **secondary user store** in  Carbon Remote User Store Manager.
But in the  UI its not allow user to provision  users to the secondary user store in CarbonRemoteUserStoreManger. What's the expected behavior?

**Comment by omindu** [comment]
@Chankami The link is missing.

**Comment by omindu** [comment]
How are you provisioning users ? Through JIT provisioning ?

**Comment by Chankami** [comment]
Hi @omindu 
Sorry https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager
Yes JIT  provisioning

**Comment by Chankami** [comment]
Hi @omindu 
Sorry https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager
Yes JIT  provisioning

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
