### ISSUE TITLE
Application login flow page has distorted view

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#20749]
**Describe the issue:**
Shared application at sub org level has this distorted view
![image](https://github.com/user-attachments/assets/87ab1190-8eb1-4048-bba9-9715d71b332d)

**How to reproduce:**
1. Create an application 
2. Create a sub org
3. Share the app with sub org
4. Visit the shared app in the sub organization 

**Expected behavior:**
Should render properly 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
Should be due to https://github.com/nrwl/nx/issues/19595
