### ISSUE TITLE
Add UI for Action Configuration

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#20751]
### Description
Add user interface for Actions management configuration.

> Sub Task Issue for: https://github.com/wso2/product-is/issues/20747

### Wireframes
<img width="1191" alt="image" src="https://github.com/wso2-enterprise/asgardeo-product/assets/75057725/c4e630db-45c6-4781-a37b-ed32033ed5d7">

### Sub Tasks: 

- [x] Create Icons related to Action Configuration Feature 
    - https://github.com/wso2/product-is/issues/20816

**Comment by ashanthamara** [comment]
### Figma Project Link:
- https://www.figma.com/design/r760MkakYXOPF8p9SpPvKs/Actions?node-id=879-11765&m=dev

**Comment by ashanthamara** [comment]
Had a design review with @malithie, @jeradrutnam, @NipuniBhagya, @dasuni-30, @Achintha444, @JayaShakthi97, @pavinduLakshan  and @savindi7 and finalized the designs as following.

Actions Page.
![image](https://github.com/user-attachments/assets/ce88ee45-83d6-405f-bf2c-fbde7264832d)

Action Creation page.
![image](https://github.com/user-attachments/assets/1ff1177e-db71-4be0-80c4-56177a1e047b)

![image](https://github.com/user-attachments/assets/a83d8bc1-40bb-4ce7-9832-639590ec4b12)

Action Update Page.
![image](https://github.com/user-attachments/assets/5be21123-a9bb-4dbc-bcee-a7e1bce8618d)

Action Endpoint Authentication Update Page.
![image](https://github.com/user-attachments/assets/c5b17a0a-7c1c-4af8-bde7-e5a745528bac)

**Comment by ashanthamara** [comment]
Revised Designs after the design review meeting held on 31.07.2024 

Meeting Notes: https://docs.google.com/document/d/1Tk3rAGD5iznT353GY9aZ_KbhXMFay6tgeDOe1aEfScM/edit

Action Creation Page:
![image](https://github.com/user-attachments/assets/461441f7-f770-4e0d-8ba5-015cdf4f184e)

![image](https://github.com/user-attachments/assets/d3d0ca8c-62c8-4ca8-954f-a91744d72adf)

Action Update Page:
![image](https://github.com/user-attachments/assets/d8faafac-6067-4173-9152-0001ce98dfd7)

![image](https://github.com/user-attachments/assets/ebfd4717-81f6-43e9-976f-38eaa5c7c7fd)

**Comment by pavinduLakshan** [comment]
Since the PRs are merged, we can now close the issue, can't we? @ashanthamara

**Comment by ashanthamara** [comment]
> Since the PRs are merged, we can now close the issue, can't we? @ashanthamara

There are few remaining bug fixes. Hence will keep this issue open until those are fixed. @pavinduLakshan

**Comment by ashanthamara** [comment]
Closing as this is completed
