### ISSUE TITLE
Support rule-based password expiration

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#20771]
#### Is your feature request related to a problem? Please describe.
In Identity Server v7.0.0, the password expiration feature lacks flexibility, particularly in managing different expiration policies based on user roles or groups. This limitation poses challenges, especially for administrators who need to prevent password expiration for critical roles such as administrators or specific user groups. The current system does not support defining tailored password policies, which can lead to unnecessary disruptions and security concerns.

#### Describe the solution you would prefer
We propose implementing a rule-based password expiration feature. This feature would allow administrators to define multiple password expiration rules based on user attributes, such as roles and groups. Each rule can specify conditions under which password expiration applies or is skipped, with the ability to set priorities for these rules.

#### Additional context
This feature enhances security and user experience by allowing tailored password policies that meet specific organizational needs. It also simplifies the management of critical user accounts, ensuring that essential personnel are not locked out due to standard expiration policies. The feature will require both front-end and back-end modifications, including UI components for rule configuration and storage changes in the backend.

#### Related Issues 
- https://github.com/wso2/product-is/issues/16250

**Comment by PasinduYeshan** [comment]
IS Migration effort will be tracked through 
- https://github.com/wso2/product-is/issues/21041

**Comment by aaujayasena** [comment]
Related migration task ; https://github.com/wso2/product-is/issues/21041
