### ISSUE TITLE
Email regex is hardcoded in usr-mgt component in carbon-identity-framework

### ISSUE THREAD

**Issue by azinneera** [wso2/product-is#2077]
The regular expression pattern for email is hardcoded in user-mgt/org.wso2.carbon.user.mgt.ui [1]. This restricts customizing the pattern of the email address. This should be fixed to provide the email address regex as an attribute in user-mgt.xml similar to the username and password patterns to customize if necessary.

[1] https://github.com/wso2/carbon-identity-framework/blob/v5.7.5/components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/add-step1.jsp#L228

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1279
merged with https://github.com/wso2/carbon-identity-framework/commit/4f794d1adda2c76cfe0bf2f43a64c64e82962496
