### ISSUE TITLE
User account not getting automatically unlocked in the Email OTP/SMS OTP based login flow

### ISSUE THREAD

**Issue by Chathurangap688** [wso2/product-is#20781]
**Describe the issue:**

When we use EmailOTP/SMSOTP authenticators as First Factor Authenticators with Account Lock on Failed Attempts feature, the account gets locked after maximum failed OTP attempts. But it seems that user claims are not updated when trying to login again with correct OTP after account unlock time is exceeded. But the user can login to the system. Still the accountLocked claim and accountState claim values ​​show as LOCKED

**How to reproduce:**

1. Get IS KM 5.10 latest update
2. Configure SMSOTP authenticator as federated identity provider
 Also we added following configurations to enable SMSOTP authenticator
```
[authentication.authenticator.sms_otp] 
name ="SMSOTP"
enable=true

[authentication.authenticator.sms_otp.parameters]
screenUserAttribute = "http://wso2.org/claims/mobile"
noOfDigits = 4
order = "backward"
showAuthFailureReason = true
CaptureAndUpdateMobileNumber = false
redirectToMultiOptionPageOnFailure=false
EnableAccountLockingForFailedAttempts = true
TokenExpiryTime = 2
BackupCode=false
```
3. Enable account locking on failed login attempts 
   **Resident Identity Provider > Login Policies > Account Locking**
![Screenshot 2024-07-26 at 01 24 06](https://github.com/user-attachments/assets/cb189384-b733-4c98-b26b-c2a51dec0cdd)
Add following claim 

`http://wso2.org/claims/identity/failedSmsOtpAttempts
`

4. Setup a SP like this:
![image](https://github.com/user-attachments/assets/2752d82c-86f5-42fa-8653-bc2031d3650f)

5. Start authentication flow and use SMSOTP to authenticate. And then enter wrong OTP until account locked 

6. Then check the user profile 
You will see it like this
![image](https://github.com/user-attachments/assets/8c40e730-1880-4312-bbd8-fd297893855c)

7. Wait until you exceed unlock time(or you can update unlock time manually) and then start the authentication flow again and enter the correct OTP.

8. You will login to the system without any issue. But accountLocked flag and accountState will not be updated. It shows as LOCKED. **We see similar behavior for email OTP flow as well**.

**Expected behavior:**
The accountLocked and accountState claims should be updated the same as the basic authenticator flow. 

**Environment information**  **:**
 - Product Version: ISKM 5.10.0

**Comment by rksk** [comment]
Both of the EmailOTP and SMSOTP authenticators are invoking `AccountLockService.isAccountLocked()` [1] to check the account lock status. If the the user was unlocked and the unlock time is not passed, it considers the account is not locked but does not update the relevant claims. It is required to unlock the user in the same way done in AccountLockHandler [2].


[1] https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/06152cc6d6818134203556067d35d97d459949b6/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/service/AccountLockServiceImpl.java#L64
[2] https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/06152cc6d6818134203556067d35d97d459949b6/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java#L430
