### ISSUE TITLE
Issues in the B2B sample application

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#20796]
**Describe the issue:**
There are the below issues in the current B2B sample application

- [x] Integrate typescript as a dev-dependency 
- [x] Upgrade library versions in the B2B sample application
  - Currently when installing packages in the B2B sample application following error is shown
  
    ```npm warn EBADENGINE Unsupported engine {
    npm warn EBADENGINE   package: 'next-auth@4.16.4',
    npm warn EBADENGINE   required: { node: '^12.19.0 || ^14.15.0 || ^16.13.0 || ^18.12.0' },
    npm warn EBADENGINE   current: { node: 'v20.15.1', npm: '10.7.0' }
    npm warn EBADENGINE }```

**Comment by dhaura** [comment]
### Public PRs
- https://github.com/wso2/samples-is/pull/479
