### ISSUE TITLE
Double clicking on 'Approve'/ 'Login' button on Consent page/login page gives Invalid Request Screen. 

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-is#2080]
The issue occurs in Consent page, when user double clicks on the 'Approve' button. This is not reproduced in all environments, but may be with setups which has slow network connections, this could be reproduced.

If we have enabled debug logs for OAuth2AuthzEndpoint class, the debug log printed is as below.
   
 _DEBUG {org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint} - Invalid authorization request.'SessionDataKey' not found in request as parameter or attribute, and client_id parameter cannot be found in request_

The same error is occurred on "Login" page too, after double clicking on 'Login' Button.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
