### ISSUE TITLE
[Doc] Documentation on how to debug wso2 IS  

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2081]
As our products are open source need to give steps on how to  debugWSO2 IS in doc [1]
[1] https://docs.wso2.com/display/IS540/

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
