### ISSUE TITLE
Propagate Permission as Claims

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#2082]
**Description:**
To get the permissions of a relevant user as claims in the id_token.

Eg: User's roles as R1 (perm1 and perm3)  and R2(perm2 and perm3)
       User's permission perms: ["perm1", "perm2", "perm3"]

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
WSO2IS-5.4.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
