### ISSUE TITLE
[Migration] Enable SCIM2 Group based User Filtering Improvements by Default

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#20820]
### Purpose
- The following SCIM2 group based user filtering improvements were done with a config to enable/ disable the improvements. 
    - The SCIM 2 user endpoint with a groups filter returns the `totalResults` based on the total user count corresponding to the given group-based filter.
    - When invoking the user endpoint with a groups filter by passing a role (hybrid or system roles), it returns an empty list when role group separation is enabled, instead of returning users linked to the passed role.
- With the following PR, these improvements are enabled by default in the product.
    - https://github.com/wso2/carbon-identity-framework/pull/5830
- Therefore, these improvements should be noted in migration docs of future releases.

### Related Issues
- https://github.com/wso2/product-is/issues/12813

### Related PRs
- https://github.com/wso2/carbon-identity-framework/pull/5533
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/547
- https://github.com/wso2/carbon-kernel/pull/3906
- https://github.com/wso2/carbon-kernel/pull/3951

**Comment by nilasini** [comment]
Updated the migration doc
