### ISSUE TITLE
Improve implementation of Secret Management in Adaptive Authentication Scripts

### ISSUE THREAD

**Issue by Sachin-Mamoru** [wso2/product-is#20828]
**Describe the issue:**
Focuses on integrating a secret management system within adaptive authentication scripts. The key enhancement involves writing a JavaScript wrapper function to facilitate passing resolved secrets directly within the adaptive authentication scripts. This change aims to unify secret management across WSO2 Identity Server, enhancing security and simplifying script development.

**Comment by Sachin-Mamoru** [comment]
### Developer Testing

1. Create an application and add the following in the login flow.
- First Factor - Username & Password
- Second Factor - Passkey
2. Add the following script
```
var url = "https://token3.free.beeceptor.com/token3";

var authConfig = {
    "type": "clientcredential",
    "properties": {
        consumerKey: secrets.clientId,
        consumerSecret: secrets.clientSecret,
        tokenEndpoint: "https://api.asgardeo.io/t/suborg4/oauth2/token"
    }
};

var requestHeaders = {
    "accept": "application/json"
};

var secretTest1 = secrets.test1;

var groupsToStepUp = ['manager', 'employee'];
Log.info('Secret test2 : ' + secrets.test2);

var onLoginRequest = function(context) {
    Log.info('Secret test3 : ' + secrets.test3);
    executeStep(1, {
        onSuccess: function(context) {

            var payload = {
                ip: context.request.ip
            }

            Log.info('Secret test4 : ' + secrets.test4);

            httpPost(url, payload, requestHeaders, authConfig, {
                onSuccess: function(context, data) {
                    Log.info('Received risk:' + data.hasRisk);
                    Log.info('Secret test7 : ' + secrets.test7);
                    if (data.hasRisk === true) {
                        Log.info('Secret test6 : ' + secrets.test6);
                        // Prompt the second authentication factor if the hasRisk is true.
                        executeStep(2, {
                            onSuccess: function(context) {
                                Log.info('Secret test1 : ' + secretTest1);
                                Log.info('Secret test5 : ' + secrets.test5);
                            }
                        });
                    }
                }
            });
        }
    });
};
```
3. Add the following secrets
- clientId: "<client id of the choreo created app>"
- clientSecret: "client secret of the choreo created app"
- test1: "secretValTest1"
- test2: "secretValTest2"
- test3: "secretValTest3"
- test4: "secretValTest4"
- test5: "secretValTest5"
- test6: "secretValTest6"
- test7: "secretValTest7"

<img width="382" alt="image" src="https://github.com/user-attachments/assets/516c75ea-0c0d-42e9-8b81-b78093c778a9">


4. Log in with a user and check the terminal logs for the secrets

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/e9562185-fd2f-49e1-813c-a53852ac17a2">

**Comment by Thisara-Welmilla** [comment]
Verified on the latest pack as per 30/10/2024

<img width="1676" alt="Screenshot 2024-10-30 at 15 28 53" src="https://github.com/user-attachments/assets/ca171852-91a8-4d76-9c06-1b7db65c22fd">
