### ISSUE TITLE
Browser back button behavior with MFA configured

### ISSUE THREAD

**Issue by Binara-Sachin** [wso2/product-is#20831]
**Describe the issue:**
Can observe the following behavior in WSO2 IS 5.10.0
- MFA configured for a Service Provider (Ex: Basic Auth, EmailOTP)
- A user successfully logs in after completing both/all steps.
- User clicks the browser back button.
- User will be redirected to the MFA auth page (Ex: `emailOtp.jsp`)
- When the user clicks the 'Authenticate' button on this page, no action is performed.

**Expected behavior:**
- The user should be redirected to `retry.jsp` page.

**How to reproduce:**
- Configure MFA, (Basic Auth + EmailOTP) for a service provider.
- Follow the above steps.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by DilshanSenarath** [comment]
This is already fixed in master.
