### ISSUE TITLE
Configuring a SP and IdP Using Service Calls parameters should be explained

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2084]
Configuring a SP and IdP Using Service Calls parameters should be explained according to this doc [1]

[1] https://docs.wso2.com/display/IS530/Configuring+a+SP+and+IdP+Using+Service+Calls

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
