### ISSUE TITLE
[Doc] Reorder the types of policy editors according to the list in UI

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2085]
The doc [1] listed available policy editors as below,

- Basic Policy Editor
- Standard Policy Editor
- Policy Set Editor
- Import Existing Policy
- Write Policy in XML

To improve the user experience, it's better to reorder the list according to the UI.

![policy editors](https://user-images.githubusercontent.com/8849472/34941533-2040ef52-fa1a-11e7-8893-d9bedabce064.png)

[1] https://docs.wso2.com/display/IS540/Creating+a+XACML+Policy

**Comment by omindu** [comment]
Basically, Simple Policy Editor is missing in the table of content.

**Comment by ShirazAzad** [comment]
Fixed. Updated the docs [1] and [2]
[1] https://docs.wso2.com/display/IS530/Creating+a+XACML+Policy
[2] https://docs.wso2.com/display/IS540/Creating+a+XACML+Policy
