### ISSUE TITLE
[Doc] Not enough details on the usage of parameter "SkipUserConsent" in identity.xml

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2087]
Doc link: https://docs.wso2.com/display/IS500/Configuring+identity.xml

Doesn't explain what's the usage and there's no background information available on this parameter. Without that, users are unable to understand what exactly to do with this config point. 

Also, unable to find the relevant document for IS 5.3.0,5.4.0

**Comment by pubudup** [comment]
Tested on : 5.4.0 update 4

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
