### ISSUE TITLE
My Account page not loading on every browser/computer

### ISSUE THREAD

**Issue by Karbust** [wso2/product-is#20883]
**Describe the issue:**
The "My Account" page is not loading on every browser and computer.

![image](https://github.com/user-attachments/assets/8c4275eb-8cf9-4679-bc49-7234aba84485)

The error on the console is on this line: https://github.com/wso2/identity-apps/blob/6fecf9fcb389e64f928cfd38c9bb2b555edec53f/apps/myaccount/src/home.jsp#L156

Browsers tested (Windows 11 Pro 23H2):
- Vivaldi 6.8.3381.53 (Stable channel) (64-bit)
- Edge 127.0.2651.98 (Official build) (64-bit)
- Chrome 127.0.6533.100 (Official Build) (64-bit)
- Firefox 129.0 (64-bit)

Tested on 2 computers, both have the same OS and browser versions, and all browsers tested in private/anonymous tabs with no extensions or extensions disabled.

Computer 1 didn't work on any of the tested browsers.
Computer 2 worked on on all of the tested browsers.

**How to reproduce:**
I have no idea at the moment, it doesn't happen on every browser/computer.

**Expected behavior:**
It's expected the page to load on every browser/computer.

![image](https://github.com/user-attachments/assets/d7215e9e-682c-4948-9ad5-6551aa23c0cc)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0
 - OS: Docker on Ubuntu 22.04.4
 - Database: PostgreSQL 14

**Comment by pavinduLakshan** [comment]
If we are to bring any script based external integrations, we can do it through extensions/head-script.js.

cc: @brionmario
