### ISSUE TITLE
[Minor][UX] Change Id to ID

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-is#2088]
Under the **Identity Providers > Resident > Inbount Authentication Configuration > SAML2 SSO Web Configuration**, we have Identity **Provider Entity Id**, technically we should use ID and not Id.

(The correct abbreviation for identification is ID.)

**Comment by deshankoswatte** [comment]
This is **fixed** in IS _5.10.0-M4_:

![Screenshot from 2019-10-29 13-43-29](https://user-images.githubusercontent.com/33062368/67749332-f3705b80-fa52-11e9-9bdb-d0e601c9b918.png)
