### ISSUE TITLE
[Doc] Add a note to mention when Saas is enabled the SP details will not be visible in tenant management console

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2089]
Doc link: https://docs.wso2.com/display/IS540/Adding+and+Configuring+a+Service+Provider

When creating an SP and enabled Saas, the expectation is for users across all the tenant domains to be able to login to the SP. This also implies that the SP config should be visible to all the tenants. But design we do not display the SP configs in other tenants except for the tenant in which the SP is created. Please add a note and state that even though the users of all tenants are able to log in when SaaS is enabled, the SP config is only visible to only the tenant who created the SP.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
