### ISSUE TITLE
[Doc] Link related documentation for RemoteProfileConfigurationManagerService

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2090]
In "User Management with APIs" doc [1] contains a point with 'RemoteProfileConfigurationManagerService' which doesn't have a reference like other points mentioned in the doc.

[1] https://docs.wso2.com/display/IS540/User+Management+with+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
