### ISSUE TITLE
[Doc] Provide a pre-condition in the doc to start BPS with relevant inscturctions

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2091]
Doc link: https://docs.wso2.com/display/IS540/Adding+a+Workflow+Engine

Looks like this doc is referring to a separate BPS node to be up and running. Please provide this as a pre-condition in the doc.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
