### ISSUE TITLE
[Migration client] Migration of Local claim http://wso2.org/claims/role

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#20910]
**Describe the issue:**

The local claim http://wso2.org/claims/roles was introduced in IS 6.0.0 and further emphasized in IS 7.0.0 with the instruction to enable the role vs group separation improvement (GroupAndRoleSeparationEnabled=true). As a result, the local claim http://wso2.org/claims/role is considered non-existent in IS 7.0.

During the migration process (In this specific case, during the migration from version 5.10 to 7.0.), it has been observed that if http://wso2.org/claims/role was configured as claim mappings in service providers or identity providers, these claims are not automatically migrated to http://wso2.org/claims/roles. Consequently, when updating service providers or identity providers, the following errors are encountered.
```
{
    "code": "APP-60001",
    "message": "Error patching application with id: 449d94db-4484-4239-b094-39ad8f68fdbb",
    "description": "Invalid application configuration for application: 'testApp' of tenantDomain: carbon.super. Local claim http://wso2.org/claims/role is not available in the server for tenantDomain:carbon.super.",
    "traceId": "54e4d998-3c10-4fcf-8558-c824e560cfac"
}
```
```
{
    "code": "IDP-60024",
    "message": "Invalid claim uri.",
    "description": "Invalid claim uri http://wso2.org/claims/role provided in claim config.",
    "traceId": "d3e84226-543e-45e6-929e-777f738bab51"
}
```

**How to reproduce:**

- Create an instance of IS 5.10 with default database schemas.
- Create a service provider and an identity provider, and add the claim http://wso2.org/claims/role to both the service provider and identity provider.
- Run the migration to IS 7.0.
- Revert the migration-time configurations and restart the server.
- Attempt to update the service provider (application) or the identity provider (connection).
- The aforementioned errors will be encountered, and the update will be unsuccessful.

**Expected behavior:**

Role claim should be migrated to Roles claim in every occurrence; in the service provider claims, identity provider claims etc.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0]
 - OS: [ Mac]
 - Database: [MySQL]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by nilasini** [comment]
@ThaminduR are we good to close this issue?

**Comment by ThaminduR** [comment]
Closing this as this was fixed with the migration client improvement.
