### ISSUE TITLE
[Migration-Identity DB] Selective JWT Access Token Claims Handling

### ISSUE THREAD

**Issue by shashimalcse** [wso2/product-is#20929]
### Describe the issue:
Due to the requirement in https://github.com/wso2/product-is/issues/20880,
- added new tables 
  - IDN_OAUTH2_TOKEN_CLAIMS

Schema PR : https://github.com/wso2/carbon-identity-framework/pull/5853

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-enterprise/identity-migration-resources/pull/502
