### ISSUE TITLE
[Workflow] When invalid workflow name is provided, the error message is not clear enough

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2092]
1. Login to IS management console.
2. Go to Configure > Workflow Engine Profiles > Add
3. Provide the Workflow name as "WSO2BPS1#%" (with special characters)
4. Provide "https://localhost:9444/services" as BPS Manager Host Services URL and BPS Worker Host Services URL
5. Provide user credentials as username and password
6. Click Add button

Expected Results:-
- An error message should be displayed with a description that explains special characters are not allowed in workflow name

Actual Results:-
- "Error when adding the BPS profile." is displayed and it doesn't contain what the error is

![bps2](https://user-images.githubusercontent.com/13449310/34985588-928ebb82-fada-11e7-8758-0142dbd12c4b.jpg)
![bps1](https://user-images.githubusercontent.com/13449310/34985590-92d99c24-fada-11e7-9557-3638deea4942.jpg)

**Comment by pubudup** [comment]
Tested on IAM 5.4.0 update4

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
