### ISSUE TITLE
Add support to enable/disable action execution for an action type at server level

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#20927]
**Is your suggestion related to an experience ? Please describe.**
$subject as it might be useful to switch off certain extensions getting executed overall from the product.

**Describe the improvement**
- Have facility to enable or disable a particular action type from a server level config

**Comment by nilasini** [comment]
Seems the new config("actions.types.pre_issue_access_token.enable": false) is disabled by default(https://github.com/wso2/carbon-identity-framework/pull/5837/files). Did we mention this config in our documentation(https://is.docs.wso2.com/en/next/guides/customize/actions/pre-issue-access-token-action/#request-from-wso2-identity-server)? @ashanthamara
