### ISSUE TITLE
Unable to create tenants when enabling email as the username

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2093]
== Environment ==

IS 5.4.0 Update 4 - 2 node cluster & IS 5.4.0 Update 4 Standalone
JDK - 1.8
DB - mysql 5.6 / H2 
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate =
1. Enable email as username according to [1]
2. Go to management console -> Configure -> Multitenancy -> Add New Tenant
3. Provide a valid values for all available fields such as domain name, First Name, Last Name, Admin Username, Admin Password and Admin Password (Repeat)  
4. Click 'Save'

== Actual Outcome ==

Error message pops up by saying "Please enter a valid email address.<br ,/>"

![valid email address](https://user-images.githubusercontent.com/8849472/34985694-f7434606-fada-11e7-9975-eec8e40d3732.png)

Note - There's no option to add the email address in UI.

== Expected Outcome ==

There should be an option to add email address of the tenant admin user.

[1] https://docs.wso2.com/display/IS540/Using+Email+Address+as+the+Username

**Comment by omindu** [comment]
Have you tried providing the email address for the admin user name ?

**Comment by maneeshaheshan** [comment]
It's work with email as the username. Sorry for the noise.
