### ISSUE TITLE
Tenant domain getting appended to the subject identifier in JWT token when "Use tenant domain in local subject identifier" is disabled

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#2094]
**Steps to reproduce:**

Configure LinkedIn as the federated IDP and SP in SAML with email address configured as the local subject identifier. 
Use the SAML assertion contained in the SAML response of successful authentication at the IS to obtain an access token using SAML bearer grant type. 
Using that access token invoke OAuth2TokenValidationService to get a JWT token.
In the received JWT token, the local subject identifier consisted of tenant domain appended to the email address.Please note that "Use tenant domain in local subject identifier" option was not enabled. Furthermore SUBJECT_IDENTIFIER field of IDN_OAUTH2_ACCESS_TOKEN table for the corresponding access token contained only the email address. 

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
WSO2IS-5.4.0

**The cause for this issue:**

In the generateToken() method of JWTTokenGenerator which is called when invoking OAuth2TokenValidationService, we have directly added the authzUser as the JWT sub claim[1]. This authzUser is obtained from the Oauth2TokenValidationMessageContext. In TokenValidationHandler the authzUser string is constructed by appending the both user store and tenant domain to the subject identifier by default [2] and it is passed to the JWTTokenGenerator. Instead this should be the subject identifier of an authenticated user entity as done in DefaultIDTokenBuilder when generating ID tokens at the time of issuing access tokens for specific grant types [3].

[1] https://github.com/wso2-support/identity-inbound-auth-oauth/blob/support-5.3.4/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authcontext/JWTTokenGenerator.java#L218
[2] https://github.com/wso2-support/identity-inbound-auth-oauth/blob/support-5.3.4/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/TokenValidationHandler.java#L338
[3] https://github.com/wso2-support/identity-inbound-auth-oauth/blob/support-5.3.4/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java#L158

**Comment by DMHP** [comment]
This issue is resolved in the latest master branch. Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/TokenValidationHandler.java#L488. Hence closing the issue.
