### ISSUE TITLE
RTL support for login portal and recovery portal

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#20945]
## Feature Description

WSO2 Identity Server currently lacks support for Right-to-Left (RTL) languages in its login and recovery screens. This creates a significant usability issue for customers in the MEA region, who require Arabic, Hebrew, and Persian languages in their login screens.

**Objective**: Provide an out-of-the-box (OOTB) solution to support RTL mode in login screens.
- When a user selects an RTL-supported language, the layout should automatically adjust to RTL.
- Consider adding an additional `RTL` flag in the branding section to enforce the layout (Evaluate if this is necessary).

Currently, users from the MEA region must manually implement RTL support, which involves modifying JSPs, styles, etc., making it cumbersome and prone to errors.

## Considered Alternative Solutions

Provide a public guide on how to implement RTL support with minimal changes.

### Possible Paths to Solve This:

1. **Custom CSS Approach**

   - Add a global `dir="rtl"` flag, along with any necessary granular direction flags, to handle RTL layout.
   - Override styles in places where the layout does not properly reflect RTL direction.

   **Pros**: Relatively easy to implement.  
   **Cons**: Manual validation is required for every element, and additional overrides may be needed where `text-align` is used, as it could break the layout.

2. **Semantic UI Recommended Approach**

   - `Semantic UI` offers a build-time option to generate an additional RTL bundle [1].

   **Pros**: Fewer manual overrides required.  
   **Cons**: Modifications to the `theme` build mechanism in `identity-apps` are necessary, as the default Gulp build mechanism from Semantic UI is not used.

[1]: [Semantic UI - Advanced Usage (RTL Languages Section)](https://semantic-ui.com/introduction/advanced-usage.html)

**Comment by savindi7** [comment]
Closed as a new issue is created https://github.com/wso2-enterprise/asgardeo-product/issues/27929
