### ISSUE TITLE
<br/> tag displayed in error message when try to add an username in non-email format

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2095]
== Environment ==

IS 5.4.0 Update 4 - 2 node cluster & IS 5.4.0 Update 4 Standalone
JDK - 1.8
DB - mysql 5.6 / H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate =

- Enable email as username according to [1]
- Go to management console -> Configure -> Multitenancy -> Add New Tenant
- Provide a valid values for domain name, First Name, Last Name, Admin Password and Admin Password (Repeat)
- Provide a non-email username for 'Admin Username' field.
- Click 'Save'

== Actual Outcome ==

Error message pops up by saying "Please enter a valid email address.<br ,/>" which contain the line break tag within the error message text.

![valid email address](https://user-images.githubusercontent.com/8849472/35029516-4c03aefa-fb81-11e7-8cc4-5ee363c75b28.png)

== Expected Outcome ==

Error message should displayed without line break tag.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
