### ISSUE TITLE
Onboard SSO templates for the most commonly used SaaS apps 

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#20951]
**Describe the issue:**

Enhance user experience with first-level SSO configuration support. Offer a set of SSO templates similar to our application templates, requiring minimal user-side configurations and providing guidance for configuring SSO on the vendor's side such as:

- Google Workspace
- Salesforce
- Office 365

**Comment by pavinduLakshan** [comment]
## Feature Testing

### Docs

❗ The Workforce IAM page[1] displays the available SSO configuration options but does not provide direct links to the guides for each application. As a result, users must manually search for and access the documentation.

It would be more convenient if those guides were accessible directly from the main documentation.

Created an issue: https://github.com/wso2/product-is/issues/22510

:x: Google Workspace SSO Documentation contains the create app screenshot with the help panel, but the console in latest IS build is missing the help panel.

In docs:
![Image](https://github.com/user-attachments/assets/1ef1b27a-dadc-4238-9e95-81ca52b0e40b)

In latest IS build:
![Image](https://github.com/user-attachments/assets/e20729bb-fd51-427a-82d3-5ee03bd93503)

Created an issue: https://github.com/wso2/product-is/issues/22512

### Feature

#### Google Workspace

Pending

#### Office 365

Pending

#### Salesforce

Pending
