### ISSUE TITLE
Characters inherent to other languages are dropped in change password authorisation header in myaccount app

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#20957]
**Describe the issue:**

Certain special characters in passwords are being dropped when attempting to change the password using the MyAccount app.  These characters which are usually specific to other languages, such as French or Greek (e.g., ç, æ, ô, £) included in the password during the password change function within the MyAccount app are dropped. 

The issue arises because SCIM2 Patch request fails due to the authorisation header, which includes an encoded username and password, not retaining these special characters [1]. As a result, the user is shown the following error message:

```
Change password error
The current password you entered appears to be invalid. Please try again
```
[1] https://github.com/wso2/identity-apps/blob/master/apps/myaccount/src/api/change-password.ts#L50

**How to reproduce:**
1. Register a user with a password consisting of unique characters found in other languages. For example: Testç123.
2. Login to myaccount with the password.
3. Update the password providing the current password.
4. Password update fails with an invalid password error.

**Expected behavior:**
These characters should be correctly encoded and included in the authorisation header.

**Environment information:**
 - Product Version: IS 6.1.0

**Comment by ImalshaG** [comment]
@Yasasr1 Are we good to close this issue?

**Comment by Yasasr1** [comment]
Fix is done with the following pr hence closing the issue
- https://github.com/wso2/identity-apps/pull/6839
