### ISSUE TITLE
[Doc] No path given for AuthenticationDataPublisher.xml file to configure 'authenticatorURL'

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2097]
'Authenticator URL' property in table in [1] refers to ' AuthenticationDataPublisher.xml' to change the value for the property but there's no mention of file path in the documentation.

[1] https://docs.wso2.com/display/IS540/Prerequisites+to+Publish+Statistics#PrerequisitestoPublishStatistics-Configuringeventpublishers

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
