### ISSUE TITLE
UI issue in role based outbound provision dropdown menu

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#20983]
**Describe the issue:**

When clicking the dropdown menu without selecting an option leads to get selected an item from the dropdown unintentionally.

https://github.com/user-attachments/assets/a0612d74-8ded-47d1-93a8-eaea685d2280

**Comment by Achintha444** [comment]
@sadilchamishka this is the default behaviour of the dropdown component, hence I think this behaviour is correct. If we need to change this behaviour, IMO we need to change all other places as well.

**Comment by Achintha444** [comment]
@sadilchamishka this is the default behaviour of the semantic dropdown component. To fix this we need to move this to oxygen-ui dropdown component.

**Comment by sadilchamishka** [comment]
> @sadilchamishka this is the default behaviour of the semantic dropdown component. To fix this we need to move this to oxygen-ui dropdown component.

Okay. Thanks @Achintha444 for the input.

**Comment by dasuni-30** [comment]
This is the default behavior of the semantic UI dropdown component and we can fix this by adding the following prop to the component.

```
selectOnBlur={ false }
```

**Comment by dasuni-30** [comment]
### Verified in the pack

https://github.com/user-attachments/assets/f9f4961a-3b65-4dcd-87c6-7afd168ab3fd
