### ISSUE TITLE
[Doc] Add description on give values for protocol in 'Configuring event publishers' section

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2099]
Protocol property has 2 values; thrift and binary defined in [1] under table in 'Configuring event publishers' section. It's better to have description for both values on what it do.

[1] https://docs.wso2.com/display/IS540/Prerequisites+to+Publish+Statistics#PrerequisitestoPublishStatistics-Configuringeventpublishers

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
