### ISSUE TITLE
[Doc] Mention what will happen if user defined 'blocking' as the Publishing Mode and specify a Publishing Timeout

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2100]
Publishing Timeout property description in table in [1] mentioned that it denote the timeout for non=blocking publishing mode. It's better to mention the impact of this value if the user defines 'blocking' as the Publishing mode.

[1] https://docs.wso2.com/display/IS540/Prerequisites+to+Publish+Statistics#PrerequisitestoPublishStatistics-Configuringeventpublishers

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
