### ISSUE TITLE
Password recovery API breaks when Recaptcha is enabled

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#21035]
**Describe the issue:**
Password recovery API calls from backends break when the reCaptcha is enabled.

WSO2 IS has enabled Recaptcha validation at the backend as the security improvement via an update. However, this introduces a behavioral change to the users who were already using the UI and REST APIs for the same functionalities (e.g. Using the WSO2 IS password recovery pages in the browser while the mobile application utilizes the REST API for the password recovery).

It is required to introduce a config to disable the backend reCaptcha validation for the APIs to cater the users who are utilizing both UI and the REST APIs. Additionally, it is required to properly document that the requirement of reCaptcha validation at the backend and usage of the config.

**How to reproduce:**

1. Update the IS 5.9.0 to level 127 or the latest
2. Enable reCaptcha for password recovery [1].
3. Use password recovery API to recover the password of a user[2].
4. API call will respond with a 302 instead of 201.

**Expected behavior:**
API call should be successful as it did in the previous update levels.

Note this issue has been fixed for the self-registration APIs with https://github.com/wso2/product-is/issues/20726

**Environment information** **:**
 - Product Version: [IS 5.9.0]

[1]https://is.docs.wso2.com/en/5.9.0/learn/configuring-recaptcha-for-password-recovery/#configuring-password-recovery-with-recaptcha-globally
[2]https://api-docs.wso2.com/apidocs/is/is590/account-recovery-v5.9.0/#!/operations#PasswordRecovery#recoverPasswordPost

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
