### ISSUE TITLE
Rest API yaml files are outdated and missing fields

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#21068]
**Is your suggestion related to a missing or misleading document? Please describe.**
Rest API yaml files in the documentation are outdated and missing properties.

For example, the application management rest API[1] is missing the following:

ApplicationResponseModel is not correct. Missing fields from the documentation:

- associatedRoles
- SubjectConfig
  - mappedLocalSubjectMandatory
- AdvancedApplicationConfiguration
  - fragment
  - enableAPIBasedAuthentication
  - attestationMetaData
  - additionalSpProperties

**Describe the improvement**
Need to update the yaml files in the documentation.

[1]https://is.docs.wso2.com/en/latest/apis/application-rest-api/

**Comment by HasiniSama** [comment]
Master fix:

- https://github.com/wso2/docs-is/pull/4938
- https://github.com/wso2/identity-api-server/pull/763
