### ISSUE TITLE
[Doc] Sample request needs to align properly in SCIM 1.1 APIs doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2106]
Need to left align the content in "Using the SCIM API" section in [1] with the main content.

![align scim](https://user-images.githubusercontent.com/8849472/35090120-cedf009e-fc5e-11e7-9799-005036246b91.png)

[1] https://docs.wso2.com/display/IS540/SCIM+1.1+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
