### ISSUE TITLE
Support usernames recovery when email address is not unique

### ISSUE THREAD

**Issue by KD23243** [wso2/product-is#21073]
**Is your feature request related to a problem? Please describe.**
Identity Server currently allows for username recovery only when the user account can be uniquely identified. However, there could be scenarios where usernames need to be recovered even though the attributes provided for account recovery do not uniquely identify the account.

For example, there could be multiple users sharing the same email address. In cases where the username is forgotten, a user might attempt to recover the account using only the email address.

**Describe the solution you would prefer**
The problem to be solved is enhancing the username recovery process in WSO2 Identity Server when the email address is not unique. Currently, the system supports username recovery only when a user can be uniquely identified by the provided attributes. This limitation poses challenges when multiple user accounts share the same email address, leading to user confusion and potential security risks. A solution is needed to allow users to recover their usernames securely and effectively without compromising user experience or increasing the risk of unauthorized access. In such instances, users expect to receive an account recovery email listing all the usernames associated with that email address. This approach would help users verify the existence of user accounts and identify all the user accounts created using their email addresses.

**Additional context**
https://docs.google.com/document/d/1OegQCQNfa6B-X8YJMGWflbqLWgNf1KIDG9WMOYRjm9c/edit?usp=sharing

**Comment by aaujayasena** [comment]
This feature testing is blocked due to,  https://github.com/wso2/product-is/issues/21407
