### ISSUE TITLE
Session expire when updating Application role with scopes

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#21077]
When trying to update the Application role, it was identified that the 7.0 console session is expiring . 

How to reproduce :

1.Setup 5.11.0 version(with any RDBMS other than h2).
2.Create a Oauth2 application
3. Setup migration for updated 7.0 version pack and do the migration by pointing to the 5.11.0 databases.
4.After the migration, go to the console app of the 7.0 .
5.Access the Roles -> Application Role 
6.Go to Scopes tab and add a API resource -> SCIM USER API
7. Try to update it.
8. Observe the session expiry in console app

**Comment by kayathiri4** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2570
