### ISSUE TITLE
[Doc] The contents are not enough to full fill the title of the document.

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2108]
In the doc [1] we have mentioned the heading as configuring openid connect single sign on but the content didn't give any information regarding how to configure single sign on. We need to explain how can we achieve single sign on as we explained for single logout.

For single logout we have a documentation as [2] and linked to a documentation which explains single logout[3].

[1] https://docs.wso2.com/display/IS540/Configuring+OAuth2-OpenID+Connect+Single-Sign-On
[2] https://docs.wso2.com/display/IS540/Configuring+OpenID+Connect+Single+Logout
[3] https://docs.wso2.com/display/IS520/Session+Management+with+Playground

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
