### ISSUE TITLE
SAML2 SessionNotOnOrAfter support

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2109]
**Description:**
support for SAML2's SessionNotOnOrAfter property of the <AuthnStatement> would be useful for enforcing an idle session timeout on Service Providers, and ensuring that service providers will refresh from the IdP within that timeframe to prevent an idle timeout at the IdP.

Copied from the plugin repo, as this one seems to get more attention:
https://github.com/wso2-extensions/identity-inbound-auth-saml/issues/165

**Suggested Labels:**
Component/SAML, Affected/5.4.0

**Comment by LahiruLS** [comment]
The pull https://github.com/wso2/carbon-identity-framework/pull/2225/files is referred from the https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/226.

**Comment by lemoinem** [comment]
Sorry to revive an old PR, but this is the only mention of this feature I could find anywhere...

How is this configurable in WSO2 IS 5.10.0 ?
I can find no documentation anywhere and no mention of it in the carbon UI...
Can this be configured on a per-SP basis or just globally?

**Comment by hauntingEcho** [comment]
It's only configurable globally, last I knew: https://github.com/wso2/product-is/issues/6366

**Comment by lemoinem** [comment]
@hauntingEcho We've tried configuring this within our `identity.xml` file (using WSO2 IS 5.10.0).
However, it seems to be overwritten, maybe because of the implementation of `deployment.toml`.
Do you have any idea how this can be configured in WSO2 IS 5.10.0?

**Comment by hauntingEcho** [comment]
I changed jobs toward the beginning of the year & haven't really worked with 5.10.  Best of luck though!
