### ISSUE TITLE
incorrect SAML implementation when SP's NameIDFormat is not "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2110]
**Description:**
Changing the NameIDFormat which a service provider is configured to use to a value other than "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" results in incorrect behavior, as the behavior of the NameID field is not actually changed.  For example (from [SAML Core](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) section 8.3):

- "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" should cause the NameID field to be set to the user's email address
- "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" specifies that the NameID "must not be shared with other providers" (where the current system uses one ID for all service providers)

As the NameID behavior doesn't actually change to match the NameIDFormat used, I recommend either removing the option to specify this (and only using "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified") or moving to a drop-down box, to which options are added when support is added.

Copied from the plugin repo as this one seems to get more attention:
https://github.com/wso2-extensions/identity-inbound-auth-saml/issues/166

**Suggested Labels:**
Affected/5.4.0, Component/SAML, Type/Bug

**Steps to reproduce:**
1. set up a default installation of WSO2 IS 5.4.0
1. register a SaaS Service Provider with a SAML metadata file
1. change NameIDFormat to "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" in their SAML config
1. set up a user with an email address
1. initiate an SSO request
1. see that the response contains the user's ID, not email address

**Comment by madurangasiriwardena** [comment]
@hauntingEcho thank you for reporting the issue.

With proper configurations, we can achieve the functionality of "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress". We can change the subject claim uri of the service provider to have email address, if we add "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" as the name id format.

But I agree that we can't support "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" at the moment.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
