### ISSUE TITLE
Getting 404 for /authenticationendpoint/device_success.do 

### ISSUE THREAD

**Issue by shashimalcse** [wso2/product-is#21129]
**Describe the issue:**
When attempting to login with device code grant, the /authenticationendpoint/device_success.do endpoint is returning a 404 (Not Found) error.

![Screenshot 2024-09-19 at 17 37 13](https://github.com/user-attachments/assets/46feaa0d-4431-4d10-8b04-8865976552a0)

**How to reproduce:**
Try device flow

**Expected behavior:**
The endpoint should return a successful response for successful login.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 7.0.0
 - OS: Mac
 - Database: H2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by shashimalcse** [comment]
fix : https://github.com/wso2/identity-apps/pull/6903

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/6907
