### ISSUE TITLE
Generation of SAML SP metadata file

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2112]
**Description:**
When configuring an external IdP, automatic generation of the SP metadata file for WSO2 would simplify the process.  [WSO2 already supports reading these files in the inbound authenticator](https://docs.wso2.com/display/IS530/Configuring+SAML2+Web+Single-Sign-On#ConfiguringSAML2WebSingle-Sign-On-Metadatafileconfiguration)

copied from the plugin repo as this one seems to get more attention:
https://github.com/wso2-extensions/identity-outbound-auth-samlsso/issues/55

**Suggested Labels:**
Component/SAML, Type/Improvement, Affected/5.4.0

**Steps to reproduce:**
go through [the steps to connect one WSO2 instance to another via SAML](https://docs.wso2.com/display/IS510/Login+to+the+Identity+Server+using+another+Identity+Server+-+SAML2), there is no apparent option to generate SP metadata in the menus involved

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
