### ISSUE TITLE
JWT token performance issue when renew_token_without_revoking_existing is enabled

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#21122]
**Describe the issue:**

A delayed response time can be observed when the renew_token_without_revoking_existing config is set to true in IS v5.11.0 (shown below).

```
[oauth.jwt.renew_token_without_revoking_existing]
enable = true
allowed_grant_types = ["password", "client_credentials", "refresh_token"]
```

Furthermore, the response time continues to get worse when the number of tokens in the DB increases. This needs to be fixed.

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by KD23243** [comment]
The issue has been resolved, and the fix has been merged into the master branch [1]. Additionally, the migration documentation has been updated. Therefore this issue is can be closed.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2630
