### ISSUE TITLE
GUI grammar issue - "internally management"

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2113]
**Description:**
a minor grammatical issue in the GUI: "notification internally management" should be "internal notification management" or "internally managed notifications".  This is found in a handful of locations in the extensions:
https://github.com/search?utf8=%E2%9C%93&q=org%3Awso2-extensions+%22internally+management%22&type=Code

copied from the plugin repos, as this one seems to get more attention:
https://github.com/wso2-extensions/identity-event-handler-account-lock/issues/43
https://github.com/wso2-extensions/identity-governance/issues/199

**Suggested Labels:**
Affected/5.4.0, Type/UX

**Affected Product Version:**
IS 5.4.0 default distribution

**OS, DB, other environment details and versions:**    
using Debian 9 with LXDE in VirtualBox

**Steps to reproduce:**

- install WSO2 IS 5.4.0
- open the admin console, go to "Main" -> "Identity" -> "Identity Providers" -> "Resident" -> "Login Policies" -> "Account Disabling"
- see checkbox option for "Enable Notification Internally Management"

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
