### ISSUE TITLE
Improving SMS OTP Flow User Experience in WSO2 IS 

### ISSUE THREAD

**Issue by Ushani-Athu** [wso2/product-is#21134]
**Describe the issue:**
In the SMS OTP flow, users encounter confusion with the "Resend Code" button, particularly when they do not receive the OTP due to network issues or phone number changes. The current process can be lengthy and may not be intuitive.

**How to reproduce:**
Log in to the application and choose SMS OTP or get redirected to the SMS OTP page based on the application's MFA methods.
If the SMS OTP is not received, enter a random code.
Observe the "Resend Code" button appears with the error message: “Authentication Failed! Please Retry.”
Click the "Resend Code" button.
Notice that the code is not sent again.
Enter a random code again and click "Authenticate."
Authentication fails.
Finally, the code arrives via SMS.
Enter the received code and click "Authenticate" to succeed.

**Expected behavior:**
The "Resend Code" button should appear immediately on the SMS OTP page without requiring the user to enter a random code first. However, the button should be disabled for a specific time interval  before becoming active(clickable). This change aims to enhance user experience by making the flow more intuitive and reducing the likelihood of authentication failures.

**Environment information** 
 - Product Version: WSO2IS 6.1

**Comment by sandushi** [comment]
Closing this issue, because this issue is already addressed in master branch with a better UX.
