### ISSUE TITLE
Empty management console home page

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#21154]
**Describe the issue:**

With the fix provided in [1], the homepage of the management console appears blank, and an error in the console indicates that the baseCarbonURL variable cannot be found, as shown below.

![image](https://github.com/user-attachments/assets/509a51ba-c953-49e3-a409-283c4445e511)

The root cause of this issue is the improper use of the Java variable [2] within the JavaScript logic [3] [4]. The correct way to use the variable is as follows:

```
var url = "<%=baseCarbonURL%>" + "server-admin/system_status_ajaxprocessor.jsp";
url: "<%=baseCarbonURL%>" + "admin/jsp/session-validate.jsp",
```

[1] - https://github.com/wso2/product-is/issues/20416
[2] - https://github.com/wso2/carbon-kernel/blob/4.10.x/core/org.wso2.carbon.ui/src/main/resources/web/admin/index.jsp#L31
[3] - https://github.com/wso2/carbon-kernel/blob/4.10.x/core/org.wso2.carbon.ui/src/main/resources/web/admin/index.jsp#L82
[4] - https://github.com/wso2/carbon-kernel/blob/4.10.x/core/org.wso2.carbon.ui/src/main/resources/web/admin/index.jsp#L86

**How to reproduce:**

- Start WSO2 Identity Server.
- Log in to the Management Console. The homepage will appear blank, as described above.

**Expected behavior:**

The homepage should display correctly with the relevant details, as shown in the screenshot below.

![image](https://github.com/user-attachments/assets/bfe838c4-5290-4cec-b545-eb330157ab28)

**Environment information:**

 - Product Version: IS 5.11.0.372
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

**Comment by nilasini** [comment]
@sandushi can we close this issue?

**Comment by sandushi** [comment]
The master fix is send by https://github.com/wso2/carbon-kernel/pull/4085 and it is merged. Hence we can close the issue.
