### ISSUE TITLE
MS browser testing

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2116]
As many government, hospital, and other enterprise systems can be locked into the MS desktop ecosystem, official support for MS browsers would be much appreciated.  They do provide several VMs for testing: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by sagara-gunathunga** [comment]
Do you have any specific problem while testing on MS borrowers, if so create separate issue per each case.
