### ISSUE TITLE
[SchemaMigrationTask] Add VERSION column to SP_APP table

### ISSUE THREAD

**Issue by mpmadhavig** [wso2/product-is#21163]
### **Describe the issue:**
As a part of the effort https://github.com/wso2/product-is/issues/20917 there is a requirement to create a new column `APP_VERSION` is `SP_APP` table. The default value of the column will depend on the below server configurations.

```
[oauth]
use_client_id_as_sub_claim_for_app_tokens = true
remove_username_from_introspection_response_for_app_tokens = true
```

The logic should be as below.
- When both the configs are ON -> Default value `v1.0.0`
- When any of the configs are OFF -> Default value `v0.0.0`

### SQL scripts:
```
ALTER TABLE SP_APP ADD VERSION VARCHAR(255) NOT NULL DEFAULT <default_value>;
```

### Related Issues:
- https://github.com/wso2/product-is/issues/20917

**Comment by mpmadhavig** [comment]
Add the default value to v2.0.0 as part of the effort https://github.com/wso2/product-is/issues/20880

**Comment by nilasini** [comment]
7.0.0 to 7.1.0 migration is not working with below error.
<img width="1790" alt="Screenshot 2024-12-02 at 16 26 07" src="https://github.com/user-attachments/assets/2cf67c64-7ca6-480d-8cba-f2c13b7c2b77">

Can we please get this fixed?

**Comment by mpmadhavig** [comment]
Please note:

> When both the configs are ON -> Default value v1.0.0

From IS 7.0.0 onwards by default the two configs are on. Therefore the migration scripts were added to address this.

> When any of the configs are OFF -> Default value v0.0.0

Migration docs need to be added to ask the customers to change the db script to v0.0.0.
