### ISSUE TITLE
 🚥 [Testing] New Feature Status Check and Testing Plan.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#21176]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**

Features | Estimation for delivery | Status
-- | -- | --
[Evaluate alternatives for Nashorn and bring that as the scripting engine to execute Adaptive Scripts](https://github.com/wso2/product-is/issues/21182) | Done before Sept 23rd |  ✅ Done
[Integrating iProov with WSO2 Identity Server and Asgardeo](url) |  |  ✅ Done
[Provide developer friendly tools to easily integrate API based authentication capabilities for Android Mobile Applications](url) |  |  ✅ Done
[Ability to selectively disable user access to an application](url) |  |  ✅ Done
[Support to configure allowed response types for OIDC/OAuth applications](url) | Done before Sept 23rd |  ✅ Done
[Provide configuration support to use the same JWT more than once as the client assertion token in private-key-jwt client authentication at an application level ](url)| Done before Sept 23rd |  ✅ Done
[User Impersonation](url) | Done before Sept 23rd | ✅ Done 
[Monitor and analyze the logs published in Asgardeo usecaeses and optimize the log usage](url) | Done before Sept 23rd |  ✅ Done
[Ability to add sub themeing preferences at the application level for login, registration, recovery UIs and emails over APIs](url) | Done before Sept 23rd |  ✅ Done
[Provide first class support for dynamic password update during the login flow to support password migration from an existing system](url) |  |  ✅ Done
[Support rule-based password expiration](url) |  |  ✅ Done
  |   |  
[Support configuring custom keypairs for root-organizations](https://github.com/wso2/product-is/issues/20564) | Oct 1st week | 🚧 In-progress
[Onboard SSO templates in Asgardeo for the most commonly used SaaS apps within enterprises](url) | Oct 1st week |  🚧 In-progress
[Support "login_hint" parameter as organization discovery hint ](url)| Oct 1st week |  🚧 In-progress (Integration tests are yet to be completed, Feature done)
[Support usernames recovery when email address is not unique](url) | Oct 1st week |  🚧 In-progress
[Integrate Onfido as a identity verification solution](url) | Oct 1st week |  🚧 In-progress

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by aaujayasena** [comment]
- This effort is to check the new feature status, so the information can contribute for plan the new feature testing. 
Release Timeline
- These issues were marked as 'Delivery Complete' in the 4th week of September and 1st week of October. 'Delivery Complete' refers only to the on-prem product side
-

**Comment by melanisilva** [comment]
### Feature Status In Asgardeo 

- https://docs.google.com/spreadsheets/d/1nLr50WHY9j_ZVimg1Vw8B1D_tK1WRU5AROt4z-SAJ0g/edit?usp=sharing

**Comment by aaujayasena** [comment]
**Update** 
The initial new features released with M1 have been completed. Through our sync-up discussions, we’ve finalized that list of new features, improvements, and bug fixes  primarily sourced from the Git dashboard and includes issues associated with the relevant milestone. Since this has been completed, we are closing the issue.
Features with M1 release: https://github.com/orgs/wso2/projects/113/views/1?filterQuery=label%3A%22Type%2FNewFeature%22+milestone%3A%227.1.0-m1%22
Improvements with M1 release : https://github.com/orgs/wso2/projects/113/views/10?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Milestone%22%5D&filterQuery=label%3A%22Type%2FImprovement%22+milestone%3A%227.1.0-m1%22
