### ISSUE TITLE
[IS E2E] - Revisit and Update IS E2E test grid integration.

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#21177]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**

This Task will track the effort of revamping and updating the IS E2E test grid implementation and fix the current issues in test grid test execution.

<img width="1108" alt="Screenshot 2024-10-03 at 15 16 02" src="https://github.com/user-attachments/assets/d5eadde9-eb7a-4134-9bf6-07ae6d24bf7c">

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by aaujayasena** [comment]
Stack creating getting fail [1]  and CentOS [2] is no supporting anymore and need to check this further

[1] https://testgrid.wso2.com/job/RELEASE/job/Scenario-Tests/job/product-is/job/is-master-scenario-testgrid-pipeline/232/console
[2] Email: [Strategy] [TestGrid] Replacing CentOS with Rocky Linux in WSO2 TestGrid
Inbox
