### ISSUE TITLE
[Improvement] Ask Password email has hyperlinks for the username when defined user name is an email

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2118]
== Environment ==

IS 5.4.0 Update4 - 2 node Cluster
JDK - 1.8
DB - H2
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate =

- Enable email as username for JDBC [1].
- Enabled 'Ask Password' according to [2]
- Go to Management Console, create a user by specifying an 'email as username' and request for a ask password.
- User should get an email

== Actual Outcome ==

Received email has a hyperlink for the username like below. 

![email ask password](https://user-images.githubusercontent.com/8849472/35113038-22b47f90-fca6-11e7-8ad3-528a0d04c6e7.png)

== Expected Outcome ==

Since the "hyperlink" type username doesn't intended to use as redirection or composing a mail, it's better to make it a static value.

[1] https://docs.wso2.com/display/IS540/Using+Email+Address+as+the+Username
[2] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by nilasini** [comment]
@maneeshaheshan Could you please change the title of the issue?. Seems like the title and actual issue are not relevant.

**Comment by omindu** [comment]
The template does not hyperlink the email address, it is done by the email client (browser).

**Comment by madurangasiriwardena** [comment]
Thanks @maneeshaheshan,

This is a mailto: link which is added from the browser.
