### ISSUE TITLE
SMS support for username recovery flow

### ISSUE THREAD

**Issue by Malith-19** [wso2/product-is#21180]
**Is your feature request related to a problem? Please describe.**
Current username recovery flow only supports only by email. Need to extend this support for SMS as well.

- Users have the option to create accounts using their mobile numbers instead of an email address.
- As a result, their accounts may not contain email information, but only the mobile number.
- When these users forget their username and attempt the username recovery process, there is currently no option to recover via SMS, causing them to get stuck in the recovery flow due to this limitation.

**Describe the solution you would prefer**
- Add the sms support in the UI and add configurations under the username recovery.

**Comment by aaujayasena** [comment]
Related issue: https://github.com/wso2/product-is/issues/21407
