### ISSUE TITLE
Test failure due to key not found for java 11.11 runtime

### ISSUE THREAD

**Issue by indeewari** [wso2/product-is#21193]
**Describe the issue:**

Key not found : HmacPBESHA256

Stack trace:

error occurred while activating 'org.wso2.carbon.crypto.provider' component. org.wso2.carbon.crypto.api.CryptoException: An error occurred while loading the internal keystore using the configurations in 'Security.InternalKeyStore' block.
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -     at org.wso2.carbon.crypto.provider.internal.DefaultCryptoProviderComponent.getKeyStoreBasedInternalCryptoProviderFromServerConfiguration(DefaultCryptoProviderComponent.java:208)

**How to reproduce:**
Build the product-is with Java 11.11 and run the integration tests in java 11.11

**Expected behavior:**
Product should be up and running without failures

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by hwupathum** [comment]
The PKCS12 keystores with default configurations does not work with Java 11.0.11 or earlier versions because `HmacPBESHA256` algorithm does not support those versions [1].

[1] https://www.oracle.com/java/technologies/javase/11-0-12-relnotes.html
