### ISSUE TITLE
Integrate with Sift for fraud detection at login

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#21197]
**Is your feature request related to a problem? Please describe.**
Preventing fraud has become an increasing requirement and IAM systems are in the front line of preventing such fraudulent activities for unauthorized account access. By integrating fraud detection solution to a IAM system, we can improve security and enhance the UX.

**Describe the solution you would prefer**
As the 1st step it will be good to integrate with Sift during the login time to analyse the login event for fraud.

**Comment by ThaminduR** [comment]
Sift connector is released https://store.wso2.com/connector/identity-fraud-detection-sift
