### ISSUE TITLE
Inconsistent Error Responses in Device Flow

### ISSUE THREAD

**Issue by shashimalcse** [wso2/product-is#21192]
**Describe the issue:**
In the  device flow, the token response is the same for multiple scenarios that should have distinct error codes according to the OAuth 2.0 Device Authorization Grant specification (RFC 8628).

Currently, the following scenarios all return the same error response:

- While waiting for the user to authenticate/authorize
- When polling too fast from the application
- When the authorization request was denied
- When the device code has expired

The current error response for all these scenarios is:
```
{
   "error_description": "Error occurred while retrieving subject identifier for device code: 1a29b9d9-1d86-4f71-be32-202a1a29029c",
   "error": "invalid_grant"
}
```

**How to reproduce:**
- Initiate a device flow authentication process.
- Attempt to retrieve a token in each of the following scenarios:
  - Before the user has authenticated
  - Immediately after a previous token request (to trigger rate limiting)
  - After the device code has expired

**Expected behavior:**
According to the specification, there should be distinct error codes for different scenarios:

- authorization_pending: The authorization request is still pending.
- slow_down: The client is polling too frequently.
- expired_token: The device code has expired.
- access_denied: The user denied the request.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2587
