### ISSUE TITLE
IDP returned role must be identical to the internal role in Identity server

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#2119]
There is a limitation on Identity server which prevents role mappings from IDP to IS unless both role names are identical.

Steps to reproduce:

- Install Identity Server pack
- Create an IDP which points to an external IDP and do the basic SAML SSO configuration 
- Create an internal role A in IS 
- Map the IDP returned role into the internal role A in IDP role mappings
- Enable JIT provisioning
- Log into the SSO app (travelocity or similar)

Behavior:

- User is created in the Identity Server
- Role A won't be added to the created user

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
