### ISSUE TITLE
[Doc] Provide sample values for attributes used in Request body of operations listed in 'User Information Recovery Service' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2120]
'User Information Recovery Service' listed available admin service operations which are used to recover information of a particular user in [1]. Here, there're are descriptions of attributes which are used inside the message body. But there's no sample values to be used (ex- 'registerUser' operation)

[1] https://docs.wso2.com/display/IS540/User+Information+Recovery+Service#UserInformationRecoveryService-registerUser

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
