### ISSUE TITLE
Roles Are Not Displayed in the Role Assignment Step During Group Creation

### ISSUE THREAD

**Issue by BimsaraBodaragama** [wso2/product-is#21211]
**Describe the issue:**
In WSO2 IS, when creating a group, we want to assign users and roles. After filling out the basic details, such as the user store, group, and users, we click "Next" to proceed to the role assignment step. However, the issue is that no available roles are displayed in this section.

**How to reproduce:**

1. Begin creating a group in WSO2 IS.
2. Fill out the basic details: select the user store, enter the group name, and assign users.
3. Click "Next" to proceed to the role assignment step.

**Expected behavior:**
 The expectation is that the available roles should be visible in the role assignment section, allowing users to select roles to assign to the group.

https://github.com/user-attachments/assets/de89a3e5-aa50-416f-8beb-070b02001100

**Comment by JayaShakthi97** [comment]
Closing as duplicate https://github.com/wso2/product-is/issues/21422
