### ISSUE TITLE
[Cluster / SF as SP] Unable to login via IS with credentials of a non admin user in Salesforce

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2121]
When I followed instructions at document [1], under "Testing the configurations" it asks user to login to the salesforce login URL with credentials of a user who exists in both Salesforce and IS. When I attempt this, I am unable to login to Salesforce with any users except for the account I used to reate the salesforce account.

Eg:-
1. user1@wso2.com registered in salesforce and configures the domain as describe in [1]
2. user1@wso2.com creates sf1@wso2.com in salesforce as a user
3. WSO2 IS admin creates sf1@wso2.com in IS as a user
4. sf1@wso2.com attempts to login to the salesforce login url with valid credentials.

Expected Results:-
- sf1@wso2.com should be able to login to salesforce once config [1] is completed
- if the assertion fails salesforce logs should reflect that

Actual Results:-
- sf1@wso2.com is unable to login to salesforce
- user1@wso2 is able to login via login url and this takes user through successfully SAML sso redirections. Please refer to the attached screenshots for sf1@wso2.com example.
- salesforce logs display does not show any errors

[1] https://docs.wso2.com/display/IS540/Logging+in+to+Salesforce+using+the+Identity+Server

![sfassertionlog](https://user-images.githubusercontent.com/13449310/35138437-91c632e8-fd14-11e7-8c6d-26e8f5a6197b.jpg)
![sf1login](https://user-images.githubusercontent.com/13449310/35138438-926295d4-fd14-11e7-8235-8f8d869d8024.jpg)

**Comment by pubudup** [comment]
Pack: IS 5.4.0 update4
Tags: Priority/High

**Comment by omindu** [comment]
Can you add the saml response sent from IS to SF for sf1@wso2.com user ?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
