### ISSUE TITLE
[Doc] Missing User Information Recovery Service operations needs to be updated in the doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2122]
Information on 'getUserChallengeQuestions' and 'verifyUserChallengeAnswers' methods are missing in User Information Recovery Service doc [1]. Refer below image for the total methods available for this admin service.

![soap ui userinforrecovery](https://user-images.githubusercontent.com/8849472/35139078-81246d1c-fd17-11e7-8bd5-b41c8b814b1a.png)

[1] https://docs.wso2.com/display/IS540/User+Information+Recovery+Service#UserInformationRecoveryService-registerUser

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
