### ISSUE TITLE
Ask Password email has an old year in the content

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2124]
== Environment ==

IS 5.4.0 Update4 - Cluster
JDK - 1.8
DB - mysql
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate =

Enable email as username for JDBC [1].
Enabled 'Ask Password' according to [2]
Go to Management Console, create a user by specifying an 'email as username' and request for a ask password.
User should get an email

== Actual Outcome ==

Received email contains the year as '2017' at the end.

![email ask password](https://user-images.githubusercontent.com/8849472/35139439-1cf31954-fd19-11e7-82b4-cd9f3eb1c30a.png)

== Expected Outcome ==

Year contains in the mail should update to '2018'

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-extensions/identity-event-handler-notification/pull/82

**Comment by nilasini** [comment]
@maneeshaheshan Could you please change the title of the issue?. Seems like the title and actual issue are not relevant.
