### ISSUE TITLE
Test the connectivity  in  Carbon Remote User Store Manager 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2126]
When configure Carbon Remote User Store Manager  as  user store there must be a way to test the 
connectivity  with the other IS. In the as JDBC user store it have a way to check the connectivity
![testconnection](https://user-images.githubusercontent.com/13656890/35139637-0478f3b6-fd1a-11e7-906c-7e9f6ead9476.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
