### ISSUE TITLE
TOTP validation fails due to regeneration of the secret key

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#21283]
**Describe the issue:**
TOTP validation fails due to regeneration of the secret key

**How to reproduce:**

1. Setup TOTP in IS 5.10.0.324 and verify that the validation of the TOTP works fine. Used the following curl commands

- curl -i -X POST -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization:Basic YWRtaW46YWRtaW4=' https://localhost:9443/services/TOTPAdminService/initTOTP -k -d 'username=testuser'

- curl -i -X POST -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization:Basic YWRtaW46YWRtaW4=' https://localhost:9443/services/TOTPAdminService/retrieveSecretKey -k -d 'username=testuser'

- curl -i -X POST -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization:Basic YWRtaW46YWRtaW4=' https://localhost:9443/services/TOTPAdminService/validateTOTP -k -d 'username=testuser' -d 'verificationCode=610385'

2. updated the server to IS 5.10.0.325, use the validateTOTP method to validate the TOTP.
curl -i -X POST -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization:Basic YWRtaW46YWRtaW4=' https://localhost:9443/services/TOTPAdminService/validateTOTP -k -d 'username=testuser' -d 'verificationCode=newtotp'

3. The validation fails always because a new secret key is generated.

The logic[1] is wrong:

```
                if (secretKey.length > 0) {
                    TOTPAuthenticatorKey key = TOTPKeyGenerator.generateKey(tenantDomain, context);
                    secretKey = key.getKey().getBytes();
                    if (context == null) {
                        encoding = TOTPUtil.getEncodingMethod(tenantDomain);
                    } else {
                        encoding = TOTPUtil.getEncodingMethod(tenantDomain, context);
                    }
                    claims.put(TOTPAuthenticatorConstants.SECRET_KEY_CLAIM_URL, TOTPUtil.encrypt(secretKey));
                    claims.put(TOTPAuthenticatorConstants.ENCODING_CLAIM_URL, encoding);
                    TOTPKeyGenerator.addTOTPClaimsAndRetrievingQRCodeURL(claims, username, context);
                } else {
                    secretKey = TOTPUtil.decryptSecret(new String(secretKey));
                }
```
If secretKey.length is greater than zero it means that there is already a secret key. why are we generating a new key?

**Expected behavior:**
The secret key should not be regenerated there is already one.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0.325]

[1]https://github.com/wso2-extensions/identity-outbound-auth-totp/blob/5a89b383f1eaaba7f3ae614882f8761b488cb4ba/component/authenticator/src/main/java/org/wso2/carbon/identity/application/authenticator/totp/services/TOTPAdminService.java#L210

**Comment by lashinijay** [comment]
This is not reproducing in master branch.
