### ISSUE TITLE
[Doc] There's no need of add <ExpiryTime> tag inside AskPassword since it's already available in the configuration

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2128]
1st step under 'Configuring the Identity Server' section in [1], asks user to add the give configuration inside  <Server> element . But by default, those configurations are available in identity.xml

![askpassword -file](https://user-images.githubusercontent.com/8849472/35140005-954f472c-fd1b-11e7-81ab-c160382bc866.png)

[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option

**Comment by ShirazAzad** [comment]
Updated the doc[1] by rephrasing the step.
[1] https://docs.wso2.com/display/IS540/Creating+Users+using+the+Ask+Password+Option
