### ISSUE TITLE
[Doc] Missing parameter description for profileName in resendSignUpConfiramtionCode section

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2131]
"resendSignUpConfiramtionCode" method of User Information Recovery Service in [1] describes parameters used in request body and 'profileName' is missing here.

[1] https://docs.wso2.com/display/IS540/User+Information+Recovery+Service#UserInformationRecoveryService-resendSignUpConfiramtionCode

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
