### ISSUE TITLE
Missing Configuration details for Change the Default Datasource for BPS for Oracle Rac DB

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21323]
**Describe the issue:**

Missing Configuration details for Change the Default Datasource for BPS for Oracle Rac DB

Refer the below documentation
https://is.docs.wso2.com/en/6.1.0/deploy/change-datasource-bpsds/
**How to reproduce:**

N/A
**Expected behavior:**

N/A

**Expected behavior:**

N/A
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Product Version: [e.g., IS 6.1]
OS: [e.g. Linux/Oracle RAC vm]
Database: [e.g., Oracle Rac]

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by himeshsiriwardana** [comment]
Closing this as BPS related documentation is moved to the connector documentation and was removed from IS from the following issue:
https://github.com/wso2/product-is/issues/20526
