### ISSUE TITLE
Account state claim changes to LOCKED when account locking is enabled in the ask password flow

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#21322]
**Describe the issue:**

When the account lock feature is enabled with the ask password option, and a user is created through SCIM2 with the ask password option, the account state is set to LOCKED instead of PENDING_AP. Without the account lock feature enabled, the account state is correctly set to PENDING_AP. This occurs because the account lock handler disregards the PENDING_AP status and sets the new state as described at [1]. This issue has already been fixed in the master branch via [2].

[1] - https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/v1.4.0/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java#L531
[2] - https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/97

**How to reproduce:**

- Enable the account locking and ask password features (test with account lock disabled as well).
- Invoke the SCIM2 API with an ask password request similar to the following example.
```
curl --location 'https://localhost:9443/scim2/Users' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "schemas": [],
    "name": {
        "familyName": "Smith",
        "givenName": "Paul"
    },
    "userName": "test",
    "password": "password",
    "emails": [
        {
            "primary": true,
            "value": "paul@somemail.com"
        }
    ],
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
        "askPassword": "true"
    }
}'
```
- Monitor the account state claim value.

**Expected behavior:**

The account state should be correctly reflected as PENDING_AP instead of LOCKED.

**Environment information:**
 - Product Version: IS-KM 5.10.0
 - OS: MacOs
 - Database: H2
 - Userstore: JDBC

---

**Comment by KD23243** [comment]
Resolved by the following PRs on the master branch:

- https://github.com/wso2-extensions/identity-event-handler-account-lock/pull/97
- https://github.com/wso2-extensions/identity-governance/pull/521
