### ISSUE TITLE
[Doc] Describe how a user should decide or understand, to which profile the connected app should be added

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2132]
In document [1], in section 6 it requires user to add the connected app to a profile. But we should explain how user can find out which profiles are available for the user and what's the reasoning behind selecting which profile they need to add. (At least identify which profiles are available for that user to add the connected app)

[1] https://docs.wso2.com/display/IS540/Outbound+Provisioning+with+Salesforce#OutboundProvisioningwithSalesforce-ConfiguringSalesforce

**Comment by pubudup** [comment]
Pack: 5.4.0 update4
Tags: Doc
Priority: High

**Comment by pubudup** [comment]
After spending a bit of time I understood that the profile we are adding here should be assigned to the user in Salesforce. Maybe lets include that in the doc.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
