### ISSUE TITLE
[Doc] Looks like the provided Identity provider claim URI and Local claim URI do not match

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2133]
Document: https://docs.wso2.com/display/IS540/Outbound+Provisioning+with+Salesforce#OutboundProvisioningwithSalesforce-ConfiguringSalesforce

Please refer to the attached screenshot. Can you please confirm these values are correct? Looks like the meanings of these claims mismatch. Also, emailaddress claim is being used twice. Is this intentional?

![claim1](https://user-images.githubusercontent.com/13449310/35146260-78e752cc-fd30-11e7-9ede-3d9f76c775da.jpg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
