### ISSUE TITLE
Bad pagination logic in JDBC user store manager when filtering with identity and non-identity claims

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#21335]
**Describe the issue:**
We discovered a problem during the investigation of an issue where the SCIM2/Users API returned only `2` results despite setting `count` to `3` and having a large `totalResults` value.

The issue arises due to incorrect offset calculation in the pagination logic, specifically the unnecessary subtraction of the offset value by 1 before it's used in the SQL query, leading to overlapping results the first and second pages:
```
Finished reading results from query: SELECT . . . LIMIT 3 OFFSET 0
Got 3 users in the result: [SECOND/aaron42, SECOND/adam85, SECOND/adrianasullivan]

Finished reading results from query: SELECT . . . LIMIT 3 OFFSET 2
Got 3 users in the result: [SECOND/adrianasullivan, SECOND/agonzalez, SECOND/aguirrejason]
```

Here you can see the repeated username `adrianasullivan` at the end of the first page and at the beginning of the second.

For additional context, these logs were manually added at `UniqueIDJDBCUserStoreManager::executeQueryAndGetUsernames` [1] and `UniqueIDJDBCUserStoreManager::doGetUsernameListWithID` [2]:
```java
private List<String> executeQueryAndGetUsernames(Connection dbConnection, SqlBuilder sqlBuilder,
                                                 FilterConfigs filterConfigs, String type)
        throws SQLException {

// . . . [omitted for brevity] . . .

            try (ResultSet rs = prepStmt.executeQuery()) {
                while (rs.next()) {
                    processUsernameResultSet(rs, usernames);
                }
                // added extra log below
                log.info(String.format("Finished reading results from query: %s", rs.getStatement().toString()));
            }
        }
    }
    return usernames;
}
```

```java
@Override
protected UniqueIDPaginatedUsernameSearchResult doGetUsernameListWithID(Condition condition, String profileName,
                                                                        int limit, int offset, String sortBy,
                                                                        String sortOrder)
        throws UserStoreException {

// . . . [omitted for brevity] . . .

			usernames = executeQueryAndGetUsernames(dbConnection, sqlBuilder, filterConfigs, type);
			// added extra log below
			log.info(String.format("Got %d users in the result: %s", usernames.size(), usernames));
			result.setUsers(usernames);

// . . . [omitted for brevity] . . .
}
```

It's important to note that there are no duplicate user entries in the database. The duplicates observed in the logs are a result of the faulty pagination logic.

This was confirmed by checking the same logs after removing the subtraction in the `UniqueIDJDBCUserStoreManager::adjustOffsetForDatabase` method [3]:
```java
private void adjustOffsetForDatabase(String type, OffsetLimit offsetLimit) {
	// removed subtraction
    offsetLimit.setOffset(Math.max(offsetLimit.getOffset(), 0));

// . . . [omitted for brevity] . . .
}
```

Result:
```
Finished reading results from query: SELECT . . . LIMIT 3 OFFSET 0
Got 3 users in the result: [SECOND/aaron42, SECOND/adam85, SECOND/adrianasullivan]

Finished reading results from query: SELECT . . . LIMIT 3 OFFSET 3
Got 3 users in the result: [SECOND/agonzalez, SECOND/aguirrejason, SECOND/ahoward]
```

The reason why this can cause missing results in the SCIM2/Users endpoint (and the second problem in this pagination logic) is due to how the `while` loop [4] depends on the size of `aggregateUsernameList` in the condition to stop iterating, even though there can be duplicates in the list returned from `getFilteredUsernames`; causing the loop to exit early and collecting fewer users than necessary.

Duplicates are removed after the loop has exited [5], which can reduce the size of `aggregateUsernameList` below the requested `count`, but the loop doesn't continue to fetch more users. Ideally, we would've used a `Set` rather than a `List` to avoid duplicates while running the loop.

Again, please note there are no duplicate user entries in the database.

Please see the gist [6] for an example of this happening. The values were based on our reproduction attempt of the issue.

**How to reproduce:**
1. Set up an Identity Server 5.11.0 and MySQL instance.
2. Add the below to the `deployment.toml` file:
```toml
[scim2]
enable_complex_multivalued_attribute_support = true
consider_max_limit_for_total_results = false

[scim2_multi_attribute_filtering]
use_pagination = true
```
3. Start the server with `--debug 5005`, attach the JVM to an IDE with the `carbon-kernel` repository checked out in the tag corresponding to the component version, and add a breakpoint at [7]. Optionally, you can add extra log lines, build the component, and add it to the `patches` directory.
4. Create a secondary MySQL JDBC user store.
5. Create some users and populate their profiles with values for both identity and non-identity claims. In our test, we created two custom claims and used `http://wso2.org/claims/accountState` for the identity claim; removing the read-only flag in the scim2-schema-extension.config and adding the custom claims too. Then, we used a Python script to run POST requests to the SCIM2/Users endpoint and populate the user store domain.
6. Run a GET SCIM2/Users request with a mix of identity and non-identity claims in the `filter`, specify the user store domain in the `domain`, and include non-zero pagination values to `count` and `startIndex`.
7. See the repeated result in the first and second iteration.

**Note:** Reproducing the missing results in the SCIM2/Users response is hard, since it's a very specific edge-case scenario. You can see the gist [6] for a simulation based on a real reproduction attempt.

**Expected behavior:**
The `OFFSET` clause in a SQL query is used to skip a specified number of rows (inclusive 0-based index) before starting to return rows from the query. Therefore, it shouldn't get subtracted by 1.
Also, if we're relying on the size of a collection to determine the end of a iteration, it shouldn't contain duplicates.

**Environment information:**
 - Product Version: IS 5.11.0 (likely affecting more recent major versions)
 - Database: MySQL
 - Userstore: JDBC

---

[1] https://github.com/wso2/carbon-kernel/blob/f22e659eb79c5ffe91498d3ab832dcad13989524/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L3606
[2] https://github.com/wso2/carbon-kernel/blob/f22e659eb79c5ffe91498d3ab832dcad13989524/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L3565
[3] https://github.com/wso2/carbon-kernel/blob/f22e659eb79c5ffe91498d3ab832dcad13989524/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L3674
[4] https://github.com/wso2/carbon-kernel/blob/f22e659eb79c5ffe91498d3ab832dcad13989524/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L16787-L16811
[5] https://github.com/wso2/carbon-kernel/blob/f22e659eb79c5ffe91498d3ab832dcad13989524/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L16814
[6] https://gist.github.com/vfraga/df83deef1551075f89a9fa48f48b08e2
[7] https://github.com/wso2/carbon-kernel/blob/f22e659eb79c5ffe91498d3ab832dcad13989524/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L3593

**Comment by sadilchamishka** [comment]
This issue is not reproducible with the latest updates of the product. Hence closing the issue.
