### ISSUE TITLE
Provide password recovery via SMS OTP

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#21356]
**Describe the issue:**
Business users should be able to recover their accounts via an OTP received to the mobile when the password is forgotten through the recovery portal.

We need to update the recovery portal to provide the capability to recover the password of business users using SMS OTP using the [API](https://is.docs.wso2.com/en/5.11.0/learn/password-recovery-via-user-preferred-notification-channel/).

Expected Experience for the developers
1 - Enable SMS-based password recovery in the org
2 - Add option to recover password using SMS OTP in the recovery portal.

---

**Comment by asekawa** [comment]
The relevant doc issues are partially completed -https://github.com/wso2/product-is/issues/21790
