### ISSUE TITLE
Default MultiAttributeSeparator is set to 'null'

### ISSUE THREAD

**Issue by harshanL** [wso2/product-is#2136]
As per the documentation [1], the default MultiAttributeSeparator is ",". However, in JDBC UserStore this is not picking up properly and it is set to "null" if not specified explicitly. 

[1]. https://docs.wso2.com/display/IS530/Configuring+a+JDBC+User+Store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
