### ISSUE TITLE
Upgrade dependency 'json-smart' to v2.4.9

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#21370]
Upgrade json-smart to version 2.4.9

**Comment by asha15** [comment]
Fixed with the following PRs:

- https://github.com/wso2/carbon-identity-framework/pull/6053
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/187
- https://github.com/wso2/identity-api-server/pull/729
- https://github.com/wso2/carbon-registry/pull/442
