### ISSUE TITLE
User with an authenticated session should be prompted for login after SP configuration change

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#2137]
**Description:**

When there is an already authenticated session for an application user with Identity Server, we can change the service providers authentication scheme (authentication steps and authenticators in each step) while the user has this session. In this case, if the user tries to log into the application he is not prompted for re-authentication. This is the default behavior of IS.  

The reason for this behaviour is that we cache the service provider configuration in the users session context(context created for successful authentication ). This session context is stored against the cookie (commonauth) used to identify whether the user already has a session in IS.

So whenever a user reauthenticates user's authenticated steps/idps are compared with cached service proivder configs. When you change the service provider configs it does not get reflected in the cached service provider configs in the user's authenticated session. 

 we should improve this to always fetch the latest service provider configs and compare user's authentication steps/IDPs against it.

**Suggested Labels:**
Type/Improvement, Priority/High

**Affected Product Version:**
WSO2IS-5.4.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
