### ISSUE TITLE
[Migration] Migration Client Improvements

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#21388]
When migrating from 5.3.0 to 7.0, dry run migration always fails at:

5.11.0, Migration Step: TokenBindingValidationMigrator in order: 11.

This is due to the following error:

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'IDN_OIDC_PROPERTY'.

The IDN_OIDC_PROPERTY table is created in the first step of the 5.5.0 migration. However, since the dry run checks the current state of the DB, and these tables are not created during the dry run, the team consistently encounters this error.

**Comment by ImalshaG** [comment]
We don't need to have a public issue for this as this is a migration client improvement. Hence, closing the issue.
