### ISSUE TITLE
[Doc] Please update the screenshots with valid values rather than providing screenshots with empty fields

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2139]
[1] https://docs.wso2.com/display/IS540/Configuring+Outbound+Provisioning+Connectors+for+an+Identity+Provider#ConfiguringOutboundProvisioningConnectorsforanIdentityProvider-ConfiguringSalesforceprovisioning

When providing screenshots for a specific config section, can we please provide the screenshots with described values inserted into the fields? It will make the user experience much pleasant and users will be able to add configs quicker by looking at the screenshots.

**Comment by pubudup** [comment]
Pack: IAM 5.4.0 pack4
Tags: Priority/High

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
