### ISSUE TITLE
"Block authentication on outbound authentication failure" is not working

### ISSUE THREAD

**Issue by pandukakarunasena** [wso2/product-is#21396]
**Describe the issue:**

An issue has been identified where JIT provisioning followed by outbound provisioning to a third party in blocking mode does not prevent authentication when the outbound provisioning fails.

**How to reproduce:**

The issue can be reproduced with the following steps:

1. Configure a federated IDP with JIT provisioning enabled.
2. Set up the outbound provisioning connector.
3. Authenticate the user via the federated IDP (FIDP).
4. Authentication succeeds, but the user is not created in the third party where outbound provisioning is directed.

A similar issue has also been reported. Please refer to the details below.

https://github.com/wso2/product-is/issues/5587

**Expected behavior:**

Here it should be checked when the blocking mode is enabled for the outbound provisioning why the user is not created but the authentication becomes a success.

A brief analysis has been done and identified when a JIT provision is followed by an outbound provision the provisioningEntity.isJitProvisioning() is true hence if condition fails[1] ultimately not executing the scim client to provision the user.

[1] https://github.com/wso2-extensions/identity-outbound-provisioning-scim2/blob/fd50b41cd5370ee9c551f9b4c5009173373e5b41/components/org.wso2.carbon.identity.provisioning.connector.scim2/src/main/java/org/wso2/carbon/identity/provisioning/connector/scim2/SCIM2ProvisioningConnector.java#L116

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0

**Comment by sadilchamishka** [comment]
The configurations given from the patches are not yet covered properly to be addressed in the doc space. Hence closing the issue as there is nothing pending. When there is an effort for documenting the newly introduced configs, will cover this case.
