### ISSUE TITLE
Account lock error message not appear when the exceed the invialid login attempts

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21399]
**Describe the issue:**
After multiple failed login attempts, the account lock error message is not displayed. Although the its account lock, details such as the error message or lock reason are not presented to the user. 

This could be due to different redirection and currently end url contains parameters, 

`authFailure=true&authFailureMsg=login.fail.message.`

But expected to have 
```
errorCode=17003
remainingAttempts=0
lockedReason=MaxAttemptsExceeded 
```

![Screenshot from 2024-10-16 16-05-36](https://github.com/user-attachments/assets/5f56cd1b-3bf9-4499-bee6-59884bd6d120)

**How to reproduce:**
1. Login to console
2. Navigate to Login and registration
3. Navigate to login attempt
4. Enable account lock and set maximum login attempts count
5. Update
6. User attempt to login to the application with invalid password
7. User exceed the invalid login attempts count
8. User get lock
9. Check the error message

**Expected behavior:**
![Screenshot from 2024-10-16 15-41-13](https://github.com/user-attachments/assets/ca7078c5-d9a5-41da-a699-85b3017511d5)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-M1
 - OS: Ubuntu 22.04
 - Database: Oracle 19c
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduR** [comment]
This was implemented as a precautionary measure to prevent username enumeration. With following deployment.toml config, reason for the authentication failure can be displayed in the login page. 

```
[authentication.authenticator.basic.parameters]
showAuthFailureReason = true
showAuthFailureReasonOnLoginPage = true
```

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/517b76ea-7433-4335-8860-98fb97da33ee" />

However this is not properly documented in the IS docs. Hence converting this to a doc issue and changing the severity.
