### ISSUE TITLE
Locked user account does not get automatically unlocked after the locked duration expires

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21406]
**Describe the issue:**
User accounts that are locked due to multiple failed login attempts are not being automatically unlocked after the configured locked duration time has passed.

**How to reproduce:**
1. Login to console
2. Create user
3. Navigate to login and registration section
4. Navigate to login attempts 
5. Enable account lock
6. Configure the locked duration
7. Update
8. Customer user attempt to login to the application and exceed the invalid login attempt count (user invalid password)
9. Navigate to the user profile and check the user account status (Status should be locked)
10. Wait until configured locked duration time pass
11. Navigate to the user profile and check the user account status 

**Expected behavior:**
User account should be unlock

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-m1
 - OS: Ubuntu 22.04
 - Database: Oracle 19c
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashensw** [comment]
This is the expected behavior. If the account is locked due to invalid login attempts, it will be unlocked during the first successful login attempt after the lock duration has passed. After the successful login, I can see the account status as unlocked.
