### ISSUE TITLE
User not notified when account lock duration increases after continuous failed login attempts

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21408]
**Describe the issue:**
User not get notify when their account lock duration is extended due to additional failed login attempts while the account is already locked. 

**How to reproduce:**
1. Login to console
2. Create user
3. Enable the account lock and configure the maximum attempt count, locked duration.
4. Enable the "Notify user when locked time increased"
5. Update
6. Customer user exceed the invalid login attempt and get account lock
7. User wait until exceed the lock time period get exceed
8. User again attempt to logon with invalid password
9. Check the email for exceed lock time duration notification

**Expected behavior:**
When a user continues to make failed login attempts while their account is locked, the system should notify them that the lock duration has been extended, 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-m1
 - OS: Ubuntu 22.04
 - Database: Oracle 19c
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ashensw** [comment]
This is working as expected in the latest IS pack with below configs.

<img width="820" alt="Screenshot 2024-12-17 at 14 30 37" src="https://github.com/user-attachments/assets/e1e21c3d-9e37-4641-9d5b-65b9b08dda46" />
<img width="675" alt="Screenshot 2024-12-17 at 14 29 52" src="https://github.com/user-attachments/assets/5d328086-e8f4-4148-9051-866e6bb6064e" />
