### ISSUE TITLE
Username mismatch in self sign up and account creation in console when Email as Username is Enabled in IS 7

### ISSUE THREAD

**Issue by Ushani-Athu** [wso2/product-is#21411]
**Describe the issue:**
After enabling the "Email as Username" feature, the user management console [1] correctly displays "Username (Email)" without separate fields for username and email, which is the expected behavior.

However, in the self-registration process, both the username and email fields are displayed[2]. If a user fills in both fields (e.g., username: testUser, email: testUser@gmail.com) and proceeds with registration, an error occurs[3]. This can cause confusion, as users expect to register using only their email as the username.

**Expected behavior:**
When "Emails as Username" is enabled, only the email field should appear during self-registration, and the form should allow a seamless signup using the email as the username.

**Environment information** 
 - Product Version: IS 7

---
[1] - 
![Screenshot from 2024-10-18 20-37-44](https://github.com/user-attachments/assets/db7729f3-de34-4487-8369-a053b9613b14)

[2] - 
![Screenshot from 2024-10-18 20-36-53](https://github.com/user-attachments/assets/724aa78e-57d4-44ec-90fd-1099c48454da)

[3] -  
![Screenshot from 2024-10-18 20-37-13](https://github.com/user-attachments/assets/a8e35060-8caf-4e00-9d43-e2f2f0158cd2)

**Comment by ThaminduDilshan** [comment]
This is already fixed with https://github.com/wso2/identity-apps/pull/7097

**Comment by BestOwl** [comment]
> This is already fixed with [wso2/identity-apps#7097](https://github.com/wso2/identity-apps/pull/7097)

This should be included in the documentation
