### ISSUE TITLE
Break the authentication flow if the JIT Provisioning fails

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#21429]
**Describe the issue:**
Currently, there no indications of JIT provisioning failures for the federated users. The authentication flow will be successful even if the user is not created in the WSO2 IS.

User experience of the the JIT provisioning flow can be improved (by introducing a config) to fail the authentication flow.

**How to reproduce:**

This is sample scenario of breaking the JIT provisioning. It should be handled for other failures as well.

1. Configure Email as a unique attribute following the steps in [1].
2. Create a local user with a specific email (abc@cde.com) in WSO2 IS.
3. Configure a connector with a federated authenticator.
4. Enable JIT provisioning with the 'Prompt for Username, password, and consent' option.
5. Create another user on the FedIDP side with the same email (abc@cde.com) but with a different username (to prevent user association).
6. Try a JIT provision scenario.

**Expected behavior:**
User authentication flow should be fail if the JIT provisioning fails.

**Environment information :**
 - Product Version: 7.0.0

---

[1] - https://is.docs.wso2.com/en/latest/guides/users/attributes/configure-unique-attributes/#configure-unique-attributes

**Comment by nilasini** [comment]
@sadilchamishka can we close the issue?

**Comment by sadilchamishka** [comment]
Yes we can. Needed to check possible doc improvement. After checking will close the issue.

**Comment by sadilchamishka** [comment]
The configurations given from the patches are not yet covered properly to be addressed in the doc space. Hence closing the issue as there is nothing pending. When there is an effort for documenting the newly introduced configs, will cover this case.
