### ISSUE TITLE
Roles Not Retrieved While Creating Groups

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21422]
**Describe the issue:**

When creating groups, the application roles are not being retrieved, which prevents roles from being added to groups. Roles should be fetched using the following API endpoint:
- https://localhost:9443/api/server/v1/organizations/10084a8d-113f-4211-a0d5-efe36b082211/roles?count=100
but required to be ,
https://localhost:9443/<org>/scim2/v2/Roles

Current view 
![Screenshot from 2024-10-21 06-51-34](https://github.com/user-attachments/assets/08cac5b7-c5c4-4831-aa38-bfcd18bad8d6)
![Screenshot from 2024-10-21 06-51-41](https://github.com/user-attachments/assets/7a017b7b-40b5-4e54-a09d-c9003ada9fe1)

[Screencast from 2024-10-21 06:41:09.webm](https://github.com/user-attachments/assets/6695760d-d9a2-4552-ba99-d496a833780b)

**How to reproduce:**
1. Login to console
2. Create application and navigate to application edit -> Roles
3. Create application role 
4. Navigate to groups
5. Click create group and add name
6. Click next and search for role

**Expected behavior:**
Roles should be retrieved successfully when creating groups, and should be available for selection and addition to groups.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
Duplicate issue: https://github.com/wso2/product-is/issues/21211

**Comment by JayaShakthi97** [comment]
- Fix: https://github.com/wso2/identity-apps/pull/7199
- Version bump: https://github.com/wso2/product-is/pull/22030

**Comment by JayaShakthi97** [comment]
### Verified in the latest `wso2is-7.1.0-m6-SNAPSHOT`
- Super org

https://github.com/user-attachments/assets/f70d9cac-8867-4e79-a2d8-fd6501a278ff

- Sub org

https://github.com/user-attachments/assets/9d121b64-9a95-4f39-9ac9-34bcd0d2c0fa
