### ISSUE TITLE
[Postgress/DB]Getting a 500 internal server  error when trying to create a sub organization

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21427]
**Describe the issue:**

Getting a 500 internal server  error when trying to create a sub-organization

https://github.com/user-attachments/assets/d73ca0aa-69c2-484d-8a04-bca723d59395

Here we observed that the sub-organization has been created despite the error message, but all the created sub-organizations can be view only

<img width="1280" alt="Screenshot 2024-10-21 at 10 28 10" src="https://github.com/user-attachments/assets/b28dca96-4165-436f-b164-ecc54d1bdfa8">

**How to reproduce:**

1. Login to the console
2. Go to connections
3. Create a new connections
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: [ IS 7.1.0 M1]
- OS: [Mac]
- Database: [Postgress]
- Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Yasasr1** [comment]
Tried with IS 7.1.0-m3 with postgress. Was able to create sub orgs without any errors

**Comment by nilasini** [comment]
@asekawa could you please validate this?

**Comment by asekawa** [comment]
Closing this issue as it's not reproducing with the latest pack, Please feel free to reopen it if further attention is needed
