### ISSUE TITLE
[DOC]Some properties  explanation is missing  on CarbonRemoteUserstoreManger

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2143]
Explain Below properties used in Carbon Remote Userstore Manger
- Password RegEx (Javascript)  
- Username RegEx (Javascript)                  
- Role Name RegEx (Javascript)      
Also  mentioned the patternwhich need to be use for  email as usename 

[1] https://docs.wso2.com/display/IS540/Carbon+Remote+User+Store+Manager

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
