### ISSUE TITLE
Upgrade dependency 'commons-collections' to v3.2.2

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#21440]
Upgrade commons-collections to version 3.2.2

**Comment by asha15** [comment]
Fixed with the following PRs:

- https://github.com/wso2-extensions/identity-outbound-auth-x509/pull/95
- https://github.com/wso2-extensions/identity-outbound-auth-x509/pull/97
- https://github.com/wso2/identity-api-server/pull/726
- https://github.com/wso2/identity-api-server/pull/724
