### ISSUE TITLE
Missing Documentation for "Provide first class support for dynamic password migration from external system" Feature

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21448]
**Describe the issue:**

 Documentation is not avaialble for "Provide first-class support for dynamic password migration from external system" Feature

[1]https://github.com/wso2/product-is/issues/20425
**How to reproduce:**

N/A
**Expected behavior:**

N/A
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduDilshan** [comment]
Pending doc issue https://github.com/wso2/product-is/issues/20444
