### ISSUE TITLE
Add Secret Button Not Visible Due to secretsManagement Config Set to False

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#21455]
**Describe the issue:**

The "Add Secret" button is not visible in the Identity Server (IS) UI due to the `secretsManagement` configuration being set to false. This issue is preventing users from adding secrets as expected.

![secretMangement](https://github.com/user-attachments/assets/baf96372-4b85-4a79-b4ac-3a47e662d75b)

**How to reproduce:**

1. Create a new application in the IS console.
2. Switch to the "Login Flow" tab.
3. Enable "Conditional Authentication".
4. Observe that the "Add Secret" button is not visible.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0 M1
 - OS: Windows
 - Database: MySQL
 - Userstore:

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Sachin-Mamoru** [comment]
### Developer Testing

1. Create an app
2. Go to Login Flow
3. Enable `Conditional Authentication`
4. Add Secret
5. View Secret
6. Delete Secret


https://github.com/user-attachments/assets/ebb3384d-9637-4f3c-901f-f23942d8864e
