### ISSUE TITLE
[DOC] Information on mapping claims must in the top of the document 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2145]
Information on mapping claims are currently in the bottom of the page. I think it should be take to upper level. Its easy for user t understand the concept and do the claim mapping.
Better  if you can explain Requested Claim and Mandatory Claim via a simple example 
[1]https://docs.wso2.com/display/IS540/Configuring+Claims+for+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
