### ISSUE TITLE
[Postgress/DB]Getting a 500 Internal Server error when trying to disable an application via UI

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21452]
**Describe the issue:**

Getting a 500 Internal Server error when trying to disable an application via UI

```
{
    "code": "APP-65001",
    "message": "Error patching application with id: e2f0fdb3-1f1a-4997-ab5d-bf4ff735850d",
    "description": "Error while deleting user consents for application Test",
    "traceId": "af4e1a74-060e-4e5a-8580-8682cd529309"
}

```

https://github.com/user-attachments/assets/566df7c8-396c-40e3-8aff-6adb374c0aa7

We noticed that even though we are getting an error once refreshed the application is disabled

**How to reproduce:**

1. Login to the console
2. Create an application
3. Click on disable application option
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 7.1.0 - M2]
 - OS: [Mac]
 - Database: [Postgress]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by KaveeshaPiumini** [comment]
Tried to reproduce this issue but it is working fine with the following versions.

- Product Version: IS 7.1.0 - M4
- OS: [Mac]
- Database: postgres (PostgreSQL) 14.13 (Homebrew)
- Userstore: JDBC (postgresql driver v42.7.4)

### Screen Recording
https://drive.google.com/file/d/1bo7zJUEypEJ2RXOUyBcK4g95_HK93bBq/view?usp=sharing

### Deployment.toml configurations
<img width="193" alt="Screenshot 2024-11-01 at 14 25 03" src="https://github.com/user-attachments/assets/fc4e33c9-4a01-4a66-a50a-1de4b73beb7e">

### Usersotre Connection 
<img width="644" alt="Screenshot 2024-11-01 at 14 24 02" src="https://github.com/user-attachments/assets/8d98e9dc-1892-4480-bfdd-20956d7b83d6">

### DB connection used in the screen recording
<img width="769" alt="Screenshot 2024-11-01 at 14 23 38" src="https://github.com/user-attachments/assets/78cdda54-da85-45f1-8610-f29185df3331">
