### ISSUE TITLE
[Doc] How to configure consent screen is not provided in document

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2146]
Doc: https://docs.wso2.com/display/IS540/Configuring+Google

In Step 2 after clicking on "OAuth client ID", the user is redirected to the screen displayed in the screenshot. Please provide relevant configs required on this page or mention what needs to be done, since the options are disabled unless user configs this screen properly.

![googleidp1](https://user-images.githubusercontent.com/13449310/35221130-02d08466-ff9f-11e7-9f54-ae3d1c9e25fc.jpg)

**Comment by pubudup** [comment]
Pack: IAM 5.4.0 update4

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
