### ISSUE TITLE
[Postgress/DB] Getting 500 internal Server error when navigating  to the security section of myAccount

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21462]
**Describe the issue:**

[Postgress/DB] Getting 500 internal Server error when navigating  to the security section of myAccount , with the error notification of couldn't load the list of consented applications.
<img width="1498" alt="Screenshot 2024-10-23 at 11 52 58" src="https://github.com/user-attachments/assets/260f179e-435b-4e32-a68d-c15131647014">

https://github.com/user-attachments/assets/18c1eaa8-8e52-49ad-82fb-209d37587e62

**How to reproduce:**

1.Login to the myAccount
2. Go to security section of the myAccount
**Expected behavior:**

The user should be able to navigate to the myAccount security section sucessfully

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.1.0 M1]
 - OS: [Mac]
 - Database: [Postgress]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Eranda2001** [comment]
Didn't encounter a 500 internal server error. Checked through IS 7.1.0 M4, using Windows OS.

<img width="959" alt="Issue - PostgressDB Getting 500 internal Server error" src="https://github.com/user-attachments/assets/ca3e21cb-2e51-4d0b-a242-18eb4792523c">

**Comment by asekawa** [comment]
Closing this issue, as it's not reproducing. Feel free to open if the issue persists
