### ISSUE TITLE
[Doc] Admin service operations are missing in 'Entitlement with APIs' doc 

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2147]
EntitlementPolicyAdminService contains admin service operations which are related to XACML policies. In [1] , there're only 8 are documented but according to the admin service following are the total list of operations which are available. We need to document the rest of operations.

![entitleadminapis](https://user-images.githubusercontent.com/8849472/35233222-7d09c9bc-ffc3-11e7-9be1-1499f2ec91ed.png)

[1] https://{IS_HOST}:{IS_PORT}/services/EntitlementPolicyAdminService?wsdl
[2] https://docs.wso2.com/display/IS540/Entitlement+with+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
