### ISSUE TITLE
Unable to Add New Role via "Console Settings" (400 Error)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#21478]
**Describe the issue:**
When attempting to add a new role via the "Console Settings" section, the system fails to create the role and returns a 400 Bad Request error. 

[recording(4).webm](https://github.com/user-attachments/assets/b5b1f785-85db-4420-8553-efad68d36f68)

**How to reproduce:**

1. Navigate to Console Settings.
2. Go to the Roles section.
3. Attempt to create a new role by filling in the necessary details. ( name and some selected permissions / all permissions)
4. Submit the form to create the new role.
5. Observe that a 400 error is returned and the role is not created.

**Expected behavior:**
The new role should be successfully created and appear in the Roles list after submission.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

- Product Version: wso2is-7.1.0-m4-SNAPSHOT.zip - Build 5524 (24-Oct-2024 12:51:17)
- OS: Mac
- Database: H2
- Userstore:JDBC ( Default)

---

**Comment by ThaminduDilshan** [comment]
As per the screen recording it seems that the application name is not getting passed in the API request. However this is not reproducible in any of the `wso2is-7.1.0-m3`, `wso2is-7.1.0-m4` or `wso2is-7.1.0-m5` release tags.

[screen-capture.webm](https://github.com/user-attachments/assets/c39c6bf8-de9d-4b06-9aa8-2714dfa5cfa2)

[screen-capture (1).webm](https://github.com/user-attachments/assets/2a0ae01f-a937-48cb-931e-57e7c9b41809)

**Comment by NilukaSripalim** [comment]
This flow is working as expected in IS 7.1 M6 

https://github.com/user-attachments/assets/67c05248-e72b-4686-bb94-d670258b36e7
