### ISSUE TITLE
Error log printed in Identity Server startup 

### ISSUE THREAD

**Issue by RushanNanayakkara** [wso2/product-is#21481]
**Describe the issue:**
The following error log is printed in the startup of the Identity Server. 
`[2024-10-24 15:20:47,743] [] ERROR {org.wso2.carbon.identity.conditional.auth.functions.analytics.internal.AnalyticsFunctionsServiceComponent} - Error while activating AnalyticsFunctionsServiceComponent
`
<img width="1412" alt="Screenshot 2024-10-24 at 19 13 21" src="https://github.com/user-attachments/assets/32297eae-96ed-4773-ae34-a1e6a5f1db49">

**How to reproduce:**
Get the `wso2is-7.1.0-m4-SNAPSHOT` pack. 
Start the pack

**Expected behavior:**
Error log should not be printed. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.1.0-m4-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by hwupathum** [comment]
Fixed with https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/194
