### ISSUE TITLE
[Doc] Add which parameters are mandatory when using an operation in Entitlement API

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2149]
When using operations in Entitlement Service, there're several parameters which are mandatory and rest of them are optional. So it's better to mention that in the documentation [1] for each operation when describing parameters. 

[1] https://docs.wso2.com/display/IS540/Entitlement+with+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
