### ISSUE TITLE
[Doc] Missing parameter descriptions for operations in 'Entitlement with APIs' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2150]
There're some missing parameter descriptions for following operations in [1]

1. 'version' and 'enabled' in 'publishToPDP()' section
2. 'dePromote' in 'removePolicy()' section
3. 'policyEditorData' in 'updatePolicy()' section

[1] https://docs.wso2.com/display/IS540/Entitlement+with+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
