### ISSUE TITLE
Linux daemon script: "update-rc.d: error: identityserver Default-Start contains no runlevels, aborting."

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2151]
when trying to use the sysVinit script from [the documentation](https://docs.wso2.com/display/IS540/Installing+as+a+Linux+Service), it gives the error "update-rc.d: error: identityserver Default-Start contains no runlevels, aborting."  I was able to get it working by adding the following after the shebang:
```
### BEGIN INIT INFO
# Provides:          wso2is
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: starts the wso2 identity server
### END INIT INFO
```

**Comment by Nashaath** [comment]
Updated the basic startup script structure to include the suggested changes after shebang.  

Did this change in doc versions 5.4.0 through 5.7.0.
