### ISSUE TITLE
[Account Locked] Account Lock related emails sent when flow has Account Locking disabled and is not an Admin Initiated flow

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#21529]
**Describe the issue:**
As explained in $title, the fix for https://github.com/wso2/product-is/issues/20976 has made account locking feature enabled by default. However, the Account Locking feature is independent of Admin Initiated Account Locking and the emails are triggered even when there is no Admin Initiated Account Locking. This change in behaviour is causing emails to be sent.

**How to reproduce:**
1. Keep account locked feature disabled in the Resident IDP but configure rest of parameters including 'Internal Notification Management' checked.<img width="1078" alt="image" src="https://github.com/user-attachments/assets/010c953c-c0e1-4bf1-bddf-12064eb21e45">
2. Try failed login attempts until max failed attempts reached.
3. IS sends an email for the scenario when Account Locking is Disabled and not an Admin initiated locking Flow.

**Expected behavior:**
When the Account Locking Enabled or when Admin has locked the account the emails should trigger. If both are disabled then there should not be any notification
The validation for whether account locking is enabled is missing before sending emails in sections such as in _else_ blocks and the: https://github.com/wso2-extensions/identity-event-handler-account-lock/blob/931686a634cafd8fe98dcce6bfbced49b3952eaf/components/org.wso2.carbon.identity.handler.event.account.lock/src/main/java/org/wso2/carbon/identity/handler/event/account/lock/AccountLockHandler.java#L521-L527

**Environment information:**
 - Product Version: IS 5.10.0 KM

### Optional Fields
**Related issues:** https://github.com/wso2/product-is/issues/20976

**Comment by aaujayasena** [comment]
@kayathiri4 can we close this

**Comment by kayathiri4** [comment]
We can close this issue as this is already working as expected in master
