### ISSUE TITLE
OAuth related APIs/Endpints, Token Introspection API and UserInfo Endpint should have Swagger definitions

### ISSUE THREAD

**Issue by thariyarox** [wso2/product-is#2152]
Currently there are no swagger definitions available in Identity Server for OAuth related APIs or endpoints. For external parties, it is easy if we have the swagger definitions so that they can make API calls based on those.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
