### ISSUE TITLE
[Doc] Reorder the steps of configuring google as IDP document

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2154]
Doc: https://docs.wso2.com/display/IS540/Configuring+Google

Currently, it advises the reader to the first login to the management console, fill in the general information and then create a google app. This sounds a bit confusing to the reader since we skip from management console to google app

Ideally, the correct order should be, first create a google app, then login to the management console and fill all the information related to IDP. Also, provide a brief description why we are creating a Google app when we reorder the steps so that reader gets a better understanding.

**Comment by pubudup** [comment]
Pack: IAM 540 update4
Tags: Priority/High

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
