### ISSUE TITLE
[Doc] Step 3 of google as IDP document is not clear with provided screenshots

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2155]
Doc: https://docs.wso2.com/display/IS540/Configuring+Google

Step 3 of the document does not directly relate to the screenshots provided. It should be restructured with the following points provided below.

1. Update the screenshot with sample values
2. Move the google app screenshot under step 2 and make a note to copy google app client and secret
3. Advice user to provide google app client and secret under section 3

**Comment by pubudup** [comment]
Pack: IAM 540 Update4
Tags: Priority/High

**Comment by samgnaniah** [comment]
Fixed. Also fixed in older versions as this is not version specific.

https://docs.wso2.com/display/IS570/Configuring+Google
