### ISSUE TITLE
[Impersonation] [Migration] Handling Config Type data through migration

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#21563]
**Is your suggestion related to an experience ? Please describe.**
With, https://github.com/wso2/product-is/issues/20066 we have to add following data to IDN_CONFIG_TYPE table.

| ID                                   | NAME                      | DESCRIPTION                                             |
|--------------------------------------|---------------------------|---------------------------------------------------------|
| 3e5b1f91-72d8-4fbc-94d1-1b9a4f8c3b07 | IMPERSONATION_CONFIGURATION | A resource type to keep the tenant impersonation preferences. |

Since this feature delivered as PATCH to IS 7.0.0 customers some might have this data some might not. This issue is to handle migration process for following case

- Customers already in IS 7.0.0 and Using the feature - No need for data addition cause its already handled via docs.
- Customers already in IS 7.0.0 and **but not using** the feature - Need to discuss and decide based on our migration approach.
- Customers not migrated to IS 7.0.0 - With https://github.com/wso2/product-is/issues/20650, this casue will be handled ( I added the migration to IS 7.0.0 migration steps)

**Comment by aaujayasena** [comment]
@Thumimku I am planning to re-test using IS 7.1.0-M6. Could we proceed?

**Comment by Thumimku** [comment]
> @Thumimku I am planning to re-test using IS 7.1.0-M6. Could we proceed?

Yes
