### ISSUE TITLE
Improper Utilization of LDAP Connection Pooling for user Authentication

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#21571]
**Is your suggestion related to an experience ? Please describe.**
The fix was implemented via https://github.com/wso2/carbon-kernel/pull/1109/files is not available in the new method [`public LdapContext getContextWithCredentials(String userDN, Object password)`](https://github.com/wso2/carbon-kernel/blob/v4.10.9/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/LDAPConnectionContext.java#L568), with the deprecation of the previous method: [`public LdapContext getContextWithCredentials(String userDN, String password)`](https://github.com/wso2/carbon-kernel/blob/v4.10.9/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/LDAPConnectionContext.java#L473) through https://github.com/wso2/carbon-kernel/pull/1206.

Therefore, during the authentication with AD/ LDAP userstores, separate connections are created for each user authentication, resulting in a high amount of connections during user authentication and leading to performance degradation. Each authentication also requires a fresh initialization of connections, contributing to the delay.

According to the [Oracle JNDI documentation](https://docs.oracle.com/javase/jndi/tutorial/ldap/connect/config.html), `The maximum pool size is the maximum number of connections per connection identity that can be maintained concurrently by the LDAP service provider.` This indicates that separate connections are established for each identity, meaning that the `maxsize` JVM parameter is not universally applied. Hence, it's possible that the number of connections exceeds the `maxsize`, if the number of concurrent users is high.

**Comment by kayathiri4** [comment]
Hi @mifrazmurthaja 

This is being tracked with https://github.com/wso2-enterprise/wso2-iam-internal/issues/2607.
