### ISSUE TITLE
Unable to find document on  enforce users to provide missing required attributes 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2157]
AFAIK this is very straightforward in latest IS. but couldn't find any doc related to this. 

![fixedmandatory](https://user-images.githubusercontent.com/6497326/35265885-79991ec0-0047-11e8-86c5-7aefaa33cbda.png)

**Comment by dakshika** [comment]
This is related to scenario 21 on https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389

**Comment by omindu** [comment]
@dakshika Please refer: https://docs.wso2.com/display/IS540/Configuring+Claims+for+a+Service+Provider
