### ISSUE TITLE
Multivalued emails, mobiles, verified mobiles and verified emails holding claims are not marked as multivalued claims

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#21588]
**Describe the issue:**

Check-IS-7.1.0-m4:
- Login to console
- Go to user attributes & stores -> SCIM -> custom schema
- You can see newly introduced 4 default scim claim mapping to hold multivalued emails, mobiles, verified mobiles and verified emails 

<img width="1685" alt="Screenshot 2024-11-03 at 19 23 00" src="https://github.com/user-attachments/assets/396246a9-7fb3-4904-b93b-0c099d02f777">

- Check each local claim mapped to them.
-  As per the doc https://is.docs.wso2.com/en/6.1.0/references/extend/provisioning/add-scim2-custom-user-schema-support/#how-to-add-claims-to-support-multivalued-simple-attributes, custom SCIM schema pick whether the attribute is multivalued based on additional property `multivalued : true` stored in the local claim

But that information is not available in those claims

<img width="1676" alt="Screenshot 2024-11-03 at 19 24 18" src="https://github.com/user-attachments/assets/84e81bef-f6f1-4d8a-a386-125f83a57b54">

**How to reproduce:**

Mentioned in the description

**Expected behavior:**

- The mentioned attributes should be marked as simple multi valued attributes 
- as per https://is.docs.wso2.com/en/6.1.0/references/extend/provisioning/add-scim2-custom-user-schema-support/#how-to-add-claims-to-support-multivalued-simple-attributes
- Also address this doc issue https://github.com/wso2/product-is/issues/20121

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.1.0-m4

**Comment by PasinduYeshan** [comment]
Multivalued emails, mobiles, verified mobiles and verified emails holding claims were marked as multivalued claims through following PR for the IS. 
- https://github.com/wso2/carbon-identity-framework/pull/6103

**Comment by PasinduYeshan** [comment]
Doc issue is tracked separately through 
- https://github.com/wso2/product-is/issues/20121

**Comment by PasinduYeshan** [comment]
Since these attributes are newly introduced, user profile currently doesn't handle these claims. When merging UI PRs, we will ensure they are treated as multi-valued attributes.
