### ISSUE TITLE
[Cluster] Google provisioning with Salesforce

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2158]
I have followed the blog [1] solution 4.0. Please find the steps below.

Involved parties:
IS, Salesforce as Service provider, Google as external IDP

Pre-Conditions:-
- Enable Salesforce logs in IS with log4j.logger.org.wso2.carbon.identity.provisioning.connector.salesforce=DEBUG
- Enable email as username

1. Create Salesforce as Service provider
2. Create Salesforce as provisioning IDP with salesforce provisioning connector
3. Create Google as IDP with JIT provisioning enabled
4. Add google IDP as federated identity in Salesforce IDP
5. In Salesforce SP, under outbound provisioning configuration, add Salesforce as provisioning IDP

Expected Results:-
- Google users should be provisioned in IS
- Google users should be provisioned in SF
- Google users should be successfully logged into Salesforce domain

Actual Results:-
- Google users are provisioned in IS
- Google users are NOT provisioned in SF via IS
- Google users are not logged into SF (screenshot attached)

Documents followed [2][3][4]

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
[2] https://docs.wso2.com/display/IS540/Outbound+Provisioning+with+Salesforce#OutboundProvisioningwithSalesforce-ConfiguringSalesforce
[3] https://docs.wso2.com/display/IS540/Adding+and+Configuring+a+Service+Provider#AddingandConfiguringaServiceProvider-Configuringaresidentserviceprovider
[4] https://docs.wso2.com/display/IS540/Configuring+Google

![samlsf2](https://user-images.githubusercontent.com/13449310/35267093-31afd582-004b-11e8-845b-d71d9a71d977.jpg)

![sfgidp](https://user-images.githubusercontent.com/13449310/35267326-e445c2b0-004b-11e8-8ec2-d47a7317d1ad.jpg)

**Comment by pubudup** [comment]
Pack: IAM 540 Update4
Tags: Priority/Blocker

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
