### ISSUE TITLE
Missing Configuration for Preferred Username Channels in Username Recovery

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21592]
**Describe the issue:**
 The option to enable preferred username channels, specifically Email and SMS, for the username recovery feature is not available in the WSO2 Identity Server Console. This prevents administrators from configuring the self-service username recovery functionality as documented.[1]
[1] https://is.docs.wso2.com/en/next/guides/account-configurations/account-recovery/username-recovery/

![Screenshot from 2024-11-04 02-39-58](https://github.com/user-attachments/assets/91556b88-3111-4ed0-b666-f5d27d89f186)

**How to reproduce:**
Log in to the WSO2 Identity Server Console as an administrator.
Navigate to Login & Registration > Account Recovery > Username Recovery.
Attempt to locate and enable the Email and SMS options under the username recovery settings.

**Expected behavior:**
Configuration for Preferred Username Channels in Username Recovery should be available. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-M4
 - OS: Ubuntu
 - Database: H2, Oracle 19c
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/21073

**Suggested labels:**

**Comment by Malith-19** [comment]
The feature is not merged yet and you can find the progress from here https://github.com/wso2/product-is/issues/21180

**Comment by ashensw** [comment]
The mentioned configs are available in the UI now. 
<img width="931" alt="Screenshot 2024-12-10 at 11 56 24" src="https://github.com/user-attachments/assets/fac50876-e186-4e1c-b3ae-59ccbfef5575">
