### ISSUE TITLE
Explain the behavior of the  Requested Claim and Mandatory Claim 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2160]
Explain the behavior of the  Requested Claim and Mandatory Claim. Current explanation is bit confusing .
Refer mail thread 

> Clarification regarding Requested Claims

[1] https://docs.wso2.com/display/IS540/Configuring+Claims+for+a+Service+Provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
