### ISSUE TITLE
[Doc] Admin service operations are missing in 'Managing Users and Roles with APIs' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2161]
RemoteUserStoreManagerService contains admin service operations which are related to user management. In wsdl of admin service, there're 35 operations are available but in the document [1] I can find was 29. Following missing operations need to be documented.

- addUserClaimValue
- addUserClaimValues
- getPasswordExpirationTime
- getProperties
- getTenantId
- getUserId

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
