### ISSUE TITLE
Guidance on Switching JavaScript Engines in WSO2 Identity Server

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21613]
**Is your suggestion related to a missing or misleading document? Please describe.**
With the recent updates in WSO2 Identity Server, there is support for three JavaScript engines: Nashorn, OpenJDK Nashorn, and GraalJS. However, there is a lack of comprehensive documentation detailing how to switch. 

**Describe the improvement**
Develop and share detailed guidance on the following aspects:

1. Overview of Supported JavaScript Engines:

-  Brief descriptions of Nashorn, OpenJDK Nashorn, and GraalJS.

2. Configuration Steps:
        Step-by-step instructions on how to switch.
---

### Optional Fields

**Additional context**

**Related Issues:**
https://github.com/wso2/product-is/issues/21182
https://github.com/wso2/product-is/issues/21586

**Comment by nilasini** [comment]
track with https://github.com/wso2/product-is/issues/20613

**Comment by aaujayasena** [comment]
@shanggeeth  I am planning to re-test using IS 7.1.0-M6. Could we proceed?

**Comment by shanggeeth** [comment]
> @shanggeeth I am planning to re-test using IS 7.1.0-M6. Could we proceed?

We can proceed with the testing.
