### ISSUE TITLE
Verify Migration Preparedness for  GraalJS as default scripting engine to execute Adaptive Scripts 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21612]
**Describe the issue:**
From 7.1.0  uses GraalJS as the default engine for adaptive authentication scripts, replacing Nashorn  [1]. This change could potentially impact customers who have developed their own adaptive  functions [2]. Therefore, It would be essential to develop a migration plan and prioritize. 

[1] https://github.com/wso2/product-is/issues/21182
[2] https://is.docs.wso2.com/en/next/references/extend/authentication/conditional-auth/write-custom-functions-for-conditional-authentication/

Key Considerations:
- Identify Affected Customers:Identify any customers who have implemented custom adaptive functions and are planning to migrate to IS 7.1.0.
- Migration Plan:  Identify necessary changes for adaptive authentication scripts, create a detailed migration plan, and ensure resources are available to support script updates.
- Engine Switching Options: Since WSO2 Identity Server now supports three JavaScript engines—Nashorn, OpenJDK Nashorn, and GraalJS—develop and share comprehensive guidance on how to switch between these engines, including clear configuration steps.

**Comment by shanggeeth** [comment]
Required Migration Steps:

In case customers have implemented their own custom adaptive functions,

- They have to add the `@HostAccess.Export` imported from `org.graalvm.polyglot.HostAccess` package to the method of the class that is implementing `@FunctionalInterface`
- Alternatively they can use other script engines without the need for this code level change.
```
[AdaptiveAuth]
ScriptEngine = "openjdkNashorn"
```
```
[AdaptiveAuth]
ScriptEngine = "nashorn"
```

**Comment by nilasini** [comment]
@shanggeeth Did we add this to our official documentation? If not shall we add it?

**Comment by shanggeeth** [comment]
> @shanggeeth Did we create a migration doc issue? If not shall we create it?

Migration Doc Issue: https://github.com/wso2/product-is/issues/20613

**Comment by nilasini** [comment]
closing since we are tracking with https://github.com/wso2/product-is/issues/20613

**Comment by aaujayasena** [comment]
@shanggeeth I am planning to re-test using IS 7.1.0-M6. Could we proceed?
