### ISSUE TITLE
User must enter value for mandatory claims for each login when custom claim mappings are added in the SP's claim configs

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2162]
**Scenario** 
Enforce users to provide missing required attributes while getting JIT provisioned to the local system.
In order to achieve this, set a Mandatory Claim  in SP and also all the users who logged in  will provisioning to secondary JDBC user store. 
**Issue**
Every time already logged in user login to system (Travelocity), it ask to enter the value for the mandatory Claim.
**Observation**
When remove the custom claims from SP and keep only the mandatory claims as local claims  issue resolved. But this bug need to fix.

Refer mail thread 
> Clarification regarding Requested Claims

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
