### ISSUE TITLE
Remove "Sign In" Button on Disabled Application Page

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21636]
**Is your suggestion related to an experience ? Please describe.**
When an application is disabled, users are redirected to a "`https://localhost:9443/authenticationendpoint/retry.do?` with `status=authentication.flow.app.disabled` and authentication message is `statusMsg=authentication.flow.app.disabled.description `page, The page currently includes a "Sign In " button if access url is defined in the application side. 
This behavior can be confusing, as the application is no longer active and cannot be accessed. To improve user experience, the "Sign In" button should be removed from the disabled page, as it serves no purpose when the application is not accessible. 

![image](https://github.com/user-attachments/assets/1f1b0e30-e5c8-4097-84b7-f7a40911ca23)

**Describe the improvement**
Enhance the logic to verify both the application's disabled status and accessible URL, on displaying the 'signin button' Application disable page. 
**Additional context**

**Comment by pavinduLakshan** [comment]
Fixed with https://github.com/wso2/identity-apps/pull/7095
