### ISSUE TITLE
[DOC]Provide a sample request for for adding Use Local Claim Dialect  using admin services 

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2163]
Provide a sample request for for adding Use Local Claim Dialect  using admin service request [1] And also in that request mentioned how to make it as a Requested Claims

https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
