### ISSUE TITLE
Invalid endpoint call  when creating the New Oraganization

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21632]
**Describe the issue:**
Creating new organization fail. Request direction for the invalid endpoint. 

![image](https://github.com/user-attachments/assets/0cf7f316-5104-40c6-a25f-845c1856ef6a)

![image](https://github.com/user-attachments/assets/5d270ae3-e934-4abb-8a3b-2ebe8142c178)

**How to reproduce:**
1. Login to console
2. Click the Drop down from the at the left corner
3. Click to add new organization

**Expected behavior:**
Organization should be created.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-M4
 - OS: Ubuntu 22.04
 - Database: H2, Oracle 19c
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AnuradhaSK** [comment]
This is not reproducible in IS-7.0.0-m5-SNAPSHOT
<img width="1596" alt="Screenshot 2024-11-17 at 21 06 19" src="https://github.com/user-attachments/assets/10320d30-4da7-4342-871f-481a6119be01">
<img width="1588" alt="Screenshot 2024-11-17 at 21 06 26" src="https://github.com/user-attachments/assets/64d6b8db-b4f4-4c00-9125-018f5df762fd">
