### ISSUE TITLE
[Doc] Add more information to check the system configured limit when using listUsers()

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2164]
For the input parameter - 'Max Item Limit' in **listUsers()** operation in [1] mentioned about a 'system configured limit' for which the max limit will affected. It's better to have some additional descriptions on what's exactly the system limit and where to do the configuration and so on.

[1] https://docs.wso2.com/display/IS540/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-listUsers()

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
