### ISSUE TITLE
OIDC `address` claim is incorrectly formatted in the ID token when it is multi-valued attribute

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#21658]
**Describe the issue:**
`$title` issue happens because [1] handles the `address` claim as `JSONObject` but in [2] it's converted `toString`.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/35d2b91f19d322dd2e923025d1c90c257cee024d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/OpenIDConnectClaimFilterImpl.java#L388
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/35d2b91f19d322dd2e923025d1c90c257cee024d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultOIDCClaimsCallbackHandler.java#L627

**How to reproduce:**
1. Assign the local claim for address with name of address under `http://wso2.org/oidc/claim`
2. Mapped the new address claim into OIDC Scope under `openid`
3. Save the value of address attribute in a user's profile as:`address1:qwerty,address2:Medavakkam,city:Chennai,state:Tamilnadu,country:India`
4. Add address local claim and mark it as a mandatory claim in a service provider for which the above user is authorised.
5. Login with this user credentials to the application and get the ID token. 
6. Introspecting this token's content shows the address claim in below malformed format:
```json
  "address": [
    "{\"address\":\"address1:qwerty",
    "address2:Medavakkam",
    "city:Chennai",
    "state:Tamilnadu",
    "country:India\"}"
  ]
```  
**Expected behavior:**
Introspecting the token should show the multi-valued address as a properly formatted array:
```json
"address": [
    "address1:qwerty",
    "address2:Medavakkam",
    "city:Chennai",
    "state:Tamilnadu",
    "country:India"
  ]
```

**Suggestion:**
Consider changing below code statements in [2],
```java
String claimValue = claimEntry.getValue().toString();
String claimKey = claimEntry.getKey();
```
into the following:
```java
String claimKey = claimEntry.getKey();
String claimValue = claimEntry.getValue() instanceof JSONObject? ((JSONObject) claimEntry.getValue()).getAsString(claimKey): claimEntry.getValue().toString()
```
 - Product Version: wso2is-5.10.0 KM

**Comment by RushanNanayakkara** [comment]
Closing as this is already fixed in the public branch.
