### ISSUE TITLE
[DOC]Provide a sample request for for adding Subject Claim URI using admin services

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#2166]
Provide a sample request for for adding Subject Claim URI using admin services
https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
