### ISSUE TITLE
[Improvement] Modify parameters of updateRoleListOfUser() operation according to multiple usage in RemoteUserStoreManagerService admin service

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2167]
== Environment ==

IS 5.4.0 Update4 - 2 node Cluster
JDK - 1.8
DB - mysql
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Summary ==

updateRoleListOfUser() operation in **'RemoteUserStoreManagerService'** API has 2 parameters called 'deletedRoles' and 'newRoles' which used to specify roles which need to be add or remove from the given user. Even the name of the parameter defined as plural (ex-deletedRoles), only one role can be defined to remove or add per each tag as below.

````
         <!--Zero or more repetitions:-->
         <ser:deletedRoles>Teacher</ser:deletedRoles>
         <ser:deletedRoles>lecturer</ser:deletedRoles>
         <!--Zero or more repetitions:-->
         <ser:newRoles>doctor</ser:newRoles>
         <ser:newRoles>carpenter</ser:newRoles>
````

So shall we rename the paramters to 'deletedRole' and 'newRole' ? It will be less confusing for a user who users APIs to modify user role.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
