### ISSUE TITLE
[Oracle Rac] Default admin user is not listed in console setting Adminstrator section

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21683]
**Describe the issue:**

The default admin user is not listed in the console setting Administrator section

![image (3)](https://github.com/user-attachments/assets/d7afd7a2-c2a4-4680-927a-efdb9551913c)

**How to reproduce:**

1. Login to the console
2. Go to console settings
3. Go to the Administrators tab

**Expected behavior:**

The default admin user should be listed in the Administrator section

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.1.0 M4]
 - OS: [Mac]
 - Database: [H2]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by bhagyasakalanka** [comment]
Cannot reproduce this for oracle database

**Comment by bhagyasakalanka** [comment]
https://github.com/user-attachments/assets/d48d9f10-87d1-4424-a4ac-61ae4f1056e4

Tested environments
- Oracle database with oracle sql db scripts
- Oracle database with oracle rac sql db scripts

Work without issue in both cases

**Comment by bhagyasakalanka** [comment]
Verified in oracle rac cloud. This is not reproducible. 

https://drive.google.com/file/d/1W0FIktG-I3xt3cSJ7qlH1RH5_SbRPwJA/view?usp=drive_link

**Comment by bhagyasakalanka** [comment]
Closing since not reproducible
