### ISSUE TITLE
[Oracle Rac] Getting Something went wrong when redirected to the console login flow

### ISSUE THREAD

**Issue by asekawa** [wso2/product-is#21682]
**Describe the issue:**

Getting Something went wrong when redirected to the console login flow
**How to reproduce:**

1. Login to the console
2. Go to console settings
3. Click on the "Login flow"

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.1.0 M4]
 - OS: [Mac]
 - Database: [ H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by bhagyasakalanka** [comment]
Cannot reproduce this for oracle database

**Comment by bhagyasakalanka** [comment]
https://github.com/user-attachments/assets/4334bdf5-e38d-4420-9099-9f98ea1d2411

Tested environments
- Oracle database with oracle sql db scripts
- Oracle database with oracle rac sql db scripts

Work without issue in both cases

**Comment by bhagyasakalanka** [comment]
Verified in oracle rac cloud. This is not reproducible.

https://drive.google.com/file/d/1W0FIktG-I3xt3cSJ7qlH1RH5_SbRPwJA/view?usp=drive_link

**Comment by bhagyasakalanka** [comment]
Closing since not reproducible
