### ISSUE TITLE
[Doc] Explain what orderId is and what's the purpose of setting 95 to false and 97 to true

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2170]
Doc: https://docs.wso2.com/display/IS540/Self+Sign+Up+and+Account+Confirmation

Please refer to "Before you begin" section and explain what's mentioned in the title

**Comment by pubudup** [comment]
Pack: IAM 540 update4
Tags: Priority/High, Doc

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
