### ISSUE TITLE
[Improvement] Invalid Callback URL validation should be shown in OAuth/OpenID Connect Configuration page

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2171]
Description
- When a invalid callback URL is provided OAuth/OpenID Connect Configuration the error message is shown in SP update page, hence the user needs to again click on OAuth/OpenID Connect Configuration-> Configure and the previous selected data is lost. The callback URL validation should be handled in OAuth/OpenID Connect Configurations page itself.  

Suggested Labels
- UX, Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
