### ISSUE TITLE
Add backward-compatibility config for oauth2/userinfo roles field format

### ISSUE THREAD

**Issue by boromi** [wso2/product-is#21713]
**Describe the issue:**
In IS5.2, the format of the roles field in the oauth2/userinfo response was a string as follows:

`{
    "sub": "admin@test.com",
    "roles": "role1,role2,role3"
}`

This format has changed to an array in IS7.0:
`{
    "sub": "admin@test.com",
    "roles": [
      "role1",
      "role2",
      "role3"
    ]
}`

There's a requirement to introduce backward-compatibility through configuration for IS7.0 to produce the IS5.2 behavior.

**How to reproduce:**
`curl --location 'https://localhost:9443/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic hash' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=openid'`

`curl --location 'https://localhost:9443/oauth2/userinfo' \
--header 'Authorization: Bearer xyz'`

**Expected behavior:**
After introducing a new configuration option to the deployment.toml file and setting it to true, the roles field of the oauth2/userinfo produces the string version of the roles (separated by commas) and not the array of roles

**Environment information**  **:**
 - Product Version: IS 7.0
 - Database: MySQL
 - Userstore: JDBC

**Comment by kumardeepak5** [comment]
Hi @boromi 
are you currently working on this issue? I’d like to contribute. Could you please confirm?
