### ISSUE TITLE
[Doc] Explain how to find the username of SMTP account

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2172]
Doc link: https://docs.wso2.com/display/IS540/Self+Sign+Up+and+Account+Confirmation

It would be useful if we can provide some screenshots of, from where we can gather SMTP information for someone who is not familiar with it. Currently, it shows the value as abcd. I think it's better we provide some real-life example with screenshots to simplify the document understanding process for the user.

**Comment by pubudup** [comment]
Pack: IAM 540 update4
Tags: Priority/Medium, Doc

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
