### ISSUE TITLE
[Doc] Add sample requests to create secondary userstores with UserStoreConfigAdminService

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2173]
'addUserStore()' section in 'Managing User Stores with APIs' doc [1] explains about how to add a userstore with a sample request, input parameters and etc. But the provided content needs to be update with complete set of parameters (specially parameters such as username, password, drivername) that will required to create a secondary userstore. Please update the documentation with sample requests and input parameters for following user stores,

- JDBCUserStoreManager
- ActiveDirectoryUserStoreManager
- ReadOnlyLDAPUserStoreManager
- ReadWriteLDAPUserStoreManager
- CarbonRemoteUserStoreManager 

[1] https://docs.wso2.com/display/IS5xx/Managing+User+Stores+with+APIs#ManagingUserStoreswithAPIs-addUserStore()

**Comment by sherenewso2** [comment]
Fixed in 5.5.0 - 5.8.0 [1] 

[1] https://docs.wso2.com/display/IS550/Managing+User+Stores+with+APIs#2ea45d71a2b140b897c651718b99bf0d
