### ISSUE TITLE
[UX] mysql script not intutive

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2174]
<repository>/dbscripts/mysql.sql

this contains the UserMgt tables + Registry tables, but if someone opens the file they can't easily figure out it. At least we need to add section comments to identify it. IMO we need to add this details on data dictionary section as well.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
