### ISSUE TITLE
[Doc] User should be asked to save the changes before moving to next section

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2175]
Doc link: https://docs.wso2.com/display/IS540/Self+Sign+Up+and+Account+Confirmation

Under "Self sign up for super tenant users" section, user should be asked to save the changes after step 5, before moving to try out self signup section.

**Comment by pubudup** [comment]
Pack: IAM 540 update4
Tags: Priority/Low, Doc

**Comment by ShirazAzad** [comment]
Updated the doc [1] 
[1] https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation
