### ISSUE TITLE
[Logs/ Improvement] No log messages displayed on user self sign up

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2177]
Doc: https://docs.wso2.com/display/IS540/Self+Sign+Up+and+Account+Confirmation

1. Follow the document and sign up as a new user on self-sign up page.
2. Check server logs in Identity server

Expected Results:-
- There should be some log message that displays a user has submitted a self-signup form

Actual Results:-
- No logs displayed on self-sign up submission

**Comment by pubudup** [comment]
Pack: IAM 540 Update4
Tags: Priority/Medium

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
