### ISSUE TITLE
[Doc] Rest API is linked to the older version

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2178]
Doc link: https://docs.wso2.com/display/IS540/Self+Sign+Up+Using+REST+APIs

1. Click on the link "swagger docs on Self Registration REST APIs."
2. Go to opened web page and check the version in URL

Expected results:-
- Version should be 540 
eg:-
https://docs.wso2.com/display/IS540/apidocs/self-registration/

Actual results:-
- Version is displayed as 530
eg:-
https://docs.wso2.com/display/IS530/apidocs/self-registration/

**Comment by pubudup** [comment]
Pack: IAM 540 update4
Tags: Priority/High, Doc

**Comment by ShirazAzad** [comment]
Updated the docs[1] and rest of the doc spaces with correcting the links.
[1] https://docs.wso2.com/display/IS540/Self+Sign+Up+Using+REST+APIs
