### ISSUE TITLE
[User portal] Identity server logo doesn't look neat in user portal

### ISSUE THREAD

**Issue by pubudup** [wso2/product-is#2180]
Pre-Conditions:-
- Self-sign up should be configured as described in [1]
- A user should be signed up using self-signup
- Signed up user should have confirmed the account via email

Steps:-
1. Access dashboard [2] 
2. Login with signed up user credentials
3. Check the Identity Server logo displayed at the top right corner

Expected Results:-
- Logo should be neat

Actual Results:-
- Logo seems a bit pixelated at the edges (Refer to attached screenshots)

* All browsers 

[1]https://docs.wso2.com/display/IS540/Self+Sign+Up+Using+REST+APIs
[2]https://localhost:9443/dashboard/index.jag

![islogo](https://user-images.githubusercontent.com/13449310/35329540-4869231a-0126-11e8-9847-8c0c78c6b4fb.jpg)

**Comment by pubudup** [comment]
Pack: IAM 540 update4
Tags: Priority/Low

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
