### ISSUE TITLE
Improve redirection in resend account confirmation scenario

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#21818]
**Describe the issue:**

It was observed that the Resend Account Confirmation email link in WSO2 redirects to the My Account application. The scenario that is being tested is as follows:

1. A user self-registers through an application registered in WSO2 IS v7.0.0 (not the My Account application).
2. After the confirmation email is sent, attempt to log in using the created username and password. A warning appears indicating the account is not verified, along with a Resend Code link.
3. Then click the Resend Code link to initiate the email.
4. Upon receiving the email and accessing the confirmation URL, you will be redirected to the My Account application.

The ability to redirect users to the application where the self-registration originated, rather than the My Account application should be available out-of-the-box in WSO2 Identity Server v7.0.0.

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by HasiniSama** [comment]
This fix is not needed for IS 7 and Master, as this is the self-registration complete page.

<img width="565" alt="Screenshot 2024-12-11 at 11 55 19" src="https://github.com/user-attachments/assets/2ec6405a-2d81-4f0f-866f-5ededce41b84">

Here the user will redirected by the **Application Access URL** if it's set in the profile.
