### ISSUE TITLE
Missing information in a log line when forcefully shutdown the server

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2182]
== Environment ==

IS 5.4.0 Update4 
JDK - 1.8
DB - mysql
OS - ubuntu 16.04
Browser - Chrome - Version 59.0.3071.115

== Steps to Recreate =

Go to Manage -> Shutdown/Restart/ and click Graceful Shutdown

== Actual Outcome ==

When shutting down the server, following log file will be printed in backend.
````
INFO {org.wso2.carbon.tomcat.ext.internal.CarbonTomcatServiceComponent} -  Stopping the carbon web-app registered under : / 
````

== Expected Outcome ==

Log message should be complete with correct path for the web-app.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
