### ISSUE TITLE
[Doc] Provide more information on how Service Account Email for Rule based Provisioning with Google

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2185]
'Service Account Email' in table under 4th step in [1] mentioned the description as 'it will use for authentication purposes'. But it's better to give some information on what is the usage in authentication purpose and a reference to create an service account email for a new user.

[1] https://docs.wso2.com/display/IS540/Rule+Based+Provisioning#RuleBasedProvisioning-Step1:ConfigureoutboundprovisioninginWSO2IdentityServer

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
