### ISSUE TITLE
[Doc] Link a doc to refer on how to create a private key while doing Rule based Provisioning with Google

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#2186]
'Private Key' field in table under 4th step in [1] ask users to attach the created private key from local machine. It's better if we can refer a documentation from our doc space on how to create the key. So a first time user won't get confused on what steps to follow in order to accmplish this.

[1] https://docs.wso2.com/display/IS540/Rule+Based+Provisioning#RuleBasedProvisioning-Step1:ConfigureoutboundprovisioninginWSO2IdentityServer

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
