### ISSUE TITLE
Cleanup procedures for the OAuth2 Device Code grant type tables

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#21882]
**Describe the issue:**

Currently, there is an unavailability of cleanup procedures for OAuth2 Device Code grant type tables.

A stored procedure for deleting unused data on the tables IDN_OAUTH2_DEVICE_FLOW and IDN_OAUTH2_DEVICE_FLOW_SCOPES related to the above grant type will be useful in scenarios where significant data growth is observed in these tables.

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by asha15** [comment]
Related issue: https://github.com/wso2/product-is/issues/21835
