### ISSUE TITLE
Connector is not available for Onfido at Connector store

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21905]
**Describe the issue:**
Connector is not available for Onfido at Connector store

**How to reproduce:**
1. Access the wso2 connector store
2. Check for the onfido connector

**Expected behavior:**
Onfido connector should be availabale. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by AfraHussaindeen** [comment]
Onfido connector is now available in the Connector store. Refer https://store.wso2.com/connector/identity-verification-onfido
