### ISSUE TITLE
[Bug] description not get saved in  Create XACML Policy using simple editor

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2197]
steps to reproduce

1. Goto PAP -> policy administration
2. Add New Policy
3. Simple Policy Editor
4. Enter Entitlement Policy Name
5. Add description 

Save it. Then open it again. the entered description is missing

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
