### ISSUE TITLE
[Doc] File path is wrong to  embedded-ldap.xml

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-is#2198]
Doc Link: https://docs.wso2.com/display/IS530/Kerberos+Security

Given: <PRODUCT_HOME>/repository/conf
Should be: <PRODUCT_HOME>/repository/conf/identity

**Comment by ShirazAzad** [comment]
Updated the docs [1] and onwards.
[1] https://docs.wso2.com/display/IS530/Kerberos+Security
