### ISSUE TITLE
Redirect to Empty Page on "Admin Advisory" and "Remote Log Publishing" in Server Section

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#22000]
### Description

Clicking on "Admin Advisory" or "Remote Log Publishing" under the "Server" section in the Console redirects users to an empty page instead of loading the expected content 
<img width="1723" alt="Screenshot 2024-12-10 at 19 06 18" src="https://github.com/user-attachments/assets/cd08939a-2ac9-4014-9eb7-a12c11453e94">

<img width="1727" alt="Screenshot 2024-12-10 at 19 06 10" src="https://github.com/user-attachments/assets/f4d8caa3-031b-401b-8dab-a4104ebe9723">

### Steps to Reproduce

Navigate to the "Server" section in the Console.
Click on "Admin Advisory".
Observe that the user is redirected to an empty page.
Repeat the above steps for "Remote Log Publishing".

### Version

IS 7.1 M6 - https://wso2.org/jenkins/job/products/job/product-is/5611/

### Environment Details (with versions)

MacBook
Google Chrome 
H2 database

**Comment by ThaminduDilshan** [comment]
It appears that the `Admin Advisory Banner` and `Remote Log Publishing` sections are moved to `Manage Root Organization > Configure System Settings` with the multi tenancy onboarding effort [1][2]. We may have to remove the existing sections or make them redirect to the new sections.

![Screenshot 2024-12-17 at 12 58 17 PM](https://github.com/user-attachments/assets/384bcf4e-2aa4-47ad-a4a9-f1cab801f991)

[1] https://github.com/wso2/product-is/issues/21178
[2] https://github.com/wso2/identity-apps/pull/6962/commits/8fea75b9e0b1b537f49f77be8a5c13cee617a100

**Comment by ThaminduDilshan** [comment]
After having a chat with @brionmario it was decided to remove these two cards from the server section.
