### ISSUE TITLE
User is taken to a blank page after clicking environment select in Create XACML Policy 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2201]
Description
Steps to reproduce the issue
1. Select Entitlement Policy Administration->Add New Entitlement Policy->Basic Policy Editor 
2. Add policy name
3. Expand "This Policy is going to evaluated, Only when followings are matched...." or "Define Entitlement Rule(s)" end click on the select environment name icon

Shows a message as "No entitlement data finder module is defined for this category" and directs to a blank page with  Select Attribute Values title.  
The user should be directed to the relevant page with a proper descriptive message

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
