### ISSUE TITLE
require authentication from external IDP before linking a federated account

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2206]
Currently, a local account can be linked with a federated account via the dashboard without actually having access to that federated account.

This can cause issues if the user misspells, or otherwise incorrectly enters, their federated account name.  A user should be required to prove that they have access to both accounts before they can be linked (similarly to the way linking a local account already requires the other account's password).

The most serious intentional misuse of this function I can think of offhand is to self-register a bunch of accounts and then link them all to another user's federated account, which could cause confusion for that user.  I haven't thoroughly explored how permissions might be shared with federated accounts at this point, but that could certainly be an area of concern as well.

**Comment by hauntingEcho** [comment]
a possible more-aggressive misuse of this for spearphishing, under the assumption that IS is being used as an authN/Z layer for something allowing private details to be added:

1. malicious user (M) knows target user (T)'s name as provided by an external SSO identity provider (X).  I'll assume T has not yet used the system protected by IS, but has used X before
2. M links an account they control in IS to T's account in X
3. T logs in via X, thinking someone (their admin / service provider / automatic provisioning) had set up the account link for them
4. T enters private information
5. M now has access to this information

Preventing step 2 in this chain would be the purpose of this request - I would argue it to be a relatively serious security hole.

**Comment by hauntingEcho** [comment]
it looks like it may be possible to disable linking from a local account to a federated account entirely (while still allowing the reverse, which requires a password) as of [this pull request](https://github.com/wso2/product-is/pull/3673/files) - which could be used as a temporary workaround for the issue.

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-carbon-auth-saml2/pull/49

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-carbon-auth-saml2/pull/49

**Comment by hauntingEcho** [comment]
it looks like a full solution is being re-raised here: https://github.com/wso2/product-is/issues/3829
