### ISSUE TITLE
[Doc] Add the path to find the try it tool in Identity Server as an XACML Engine section 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2209]
Doc link : https://docs.wso2.com/display/IS540/Identity+Server+as+an+XACML+Engine

Description
-Add the path to find the  XACML try it tool in step 5 under "Identity Server as an XACML Engine" topic.

Suggested labels
-Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
