### ISSUE TITLE
[Doc] Unclear steps to evaluate the published XACML policy

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2210]
Doc link : https://docs.wso2.com/display/IS540/Identity+Server+as+an+XACML+Engine

Description 
-Content under step 5 states to 'Copy and paste the following on the above screen and click "Evaluate." The above request means that the "admin" user is trying to access the echoString operation of the http://localhost:8280/services/echo service.'  
It is not clear which is meant by "Copy and paste the following" and what meant by "above request".  
-When copy pasting the request code in IS try it tool a info message is given as "Indeterminate"  without any logs or changes. 
-Mention the out put of the request.

Suggested Labels
Doc Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
