### ISSUE TITLE
Error messages given in XACML try it tool are not descriptive to identify the issues

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2214]
Description
Messages are given as  "Indeterminate". The user should be given the reason for the issue and the ways to overcome them.

Suggested labels
Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
