### ISSUE TITLE
[Doc] More step by step descriptions needed for Configuring the EI entitlement mediator 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2217]
Doc link : https://docs.wso2.com/display/IS540/Configuring+WSO2+EI+Entitlement+Mediator+with+Identity+Server

The steps under Configuring the EI entitlement mediator topic needs more step by step explanations with screenshots of the UI. 
Refer blog : https://yumani.blogspot.com/2014/04/fine-grained-authorization-scenario.html

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
