### ISSUE TITLE
NPE when no client authentication information is included into OAuth token request

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#2218]
Send out a valid token request without parameters of client id and secret and without authorization header as well. This will cause a NPE

**Comment by GDRDABARERA** [comment]
This is fixed in IS 5.4.1

**Comment by omindu** [comment]
@GDRDABARERA can you add the relevant PR/Commit and close this off ?

**Comment by GDRDABARERA** [comment]
Fix with the commit  a223af80f751a62ae5f552035b08cdc194770bb5

**Comment by nilasini** [comment]
Don't we need to give pro-active wum for older versions like 5.4.0, 5.3.0?
