### ISSUE TITLE
Correct error message for local account association with invalid password

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2224]
When associating local users through the dashboard by giving an invalid password, the error message popup shows the exception type. This should be fixed to display a meaningful error.

![image](https://user-images.githubusercontent.com/9883427/35610907-2b8a306e-0689-11e8-9407-baf48bfe4671.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
