### ISSUE TITLE
[Doc] Need to update the content in applying UsernameToken security policy to the Proxy Service 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2226]
Doc link : https://docs.wso2.com/display/IS540/Configuring+WSO2+EI+Entitlement+Mediator+with+Identity+Server

Description :
Configuring the EI entitlement mediator  step 5 - the mentioned link to apply UsernameToken security policy redirects to a diagram and does not provide the relevant information to apply the policy. 
Also the issue with Proxy Services needs more descriptions.

Suggested Labels
Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
