### ISSUE TITLE
[Doc] Rename "Writing XACML3 Policies in WSO2 Identity Server" sub topics to related example topics

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2227]
Doc link : https://docs.wso2.com/display/IS540/Writing+XACML2.0+Policies+in+WSO2+Identity+Server

Description
In Writing XACML3 Policies in WSO2 Identity Server the content is separated to pages and named 1,2,3 etc. 
Instead of that we can add topics which relates to the examples
For eg: Writing XACML 3 Policies in WSO2 Identity Server - 2 --> Role based access control 
Then the user is able to find the content easily without going through all Writing XACML 3 Policies in WSO2 Identity Server  pages

Suggested Labels
Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
