### ISSUE TITLE
Subject claim configuration in service provider does not get reflected in Self Contained Access Tokens sub

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#2228]
Configure Self contained access tokens in 5.4.0 (You need to change column length of the token table to avoid initial issue stated in [1]). Change the subject claim in SP configuration. It doesnt get reflected in the access tokens sub element. 

[1] https://github.com/wso2/product-is/issues/2220

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
