### ISSUE TITLE
[Doc] Step invalid for Authenticating and Authorizing REST APIs

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2230]
https://docs.wso2.com/display/IS540/Authenticating+and+Authorizing+REST+APIs

Step 1 and 2 mention uncommenting few lines in config. the latest pack has given lines already uncommented

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
