### ISSUE TITLE
[Doc] Misleading information about SCIM 1.1 APIs config

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2232]
By default <Property name="SCIMEnabled">true</Property>  is set under org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager. IMO we need to mentioned the bydefault case and need to mentioned that if user using any other mechanisam they have to enable it on config.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
