### ISSUE TITLE
Claims are not sorted in the Mapped Local Claim dropdown in Add External Claim menu

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#2233]
![addexternalclaim](https://user-images.githubusercontent.com/13478571/35668938-77d38418-0759-11e8-8750-706e3bad9392.png)

**Comment by darshanasbg** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/commit/402ca1317da143edf8bfac57bc9945c3b401d124
