### ISSUE TITLE
IDP is not shown in the UI when it is created via IdentityProviderMgtService

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#2235]
When an IDP is created via the SOAP service - IdentityProviderMgtService, it is not shown in the UI even though the response says it was successfully created. 
Previously created IDPs are displayed when the server is restarted.

Suggested label - bug

**Comment by mefarazath** [comment]
Once you add the IDP using the SOAP can you try to logout from management console and login again and list the IDPs and see if you can find the added IDP?

**Comment by mefarazath** [comment]
Related to https://wso2.org/jira/browse/IDENTITY-6938

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
