### ISSUE TITLE
[UX] No proper documentation or tutorial on mutual authentication support using apache or any other server

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2236]
Usually, people may try to develop apps using php or reactjs or node. But we don't have proper guidance on writing and connecting such apps with wso2 IS. 
while working with scenario 24 on below blog, 
https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
I came across of writing a custom app in react or php. To handle XACML part I'm looking for mutual auth since its the only applicable use case for such scenario. But couldn't find any guide on this. 

Our all samples focus on JAVA world and IMO world isn't JAVA :)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
