### ISSUE TITLE
[Doc] EI6 does not allow to add policies to a proxy service

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2239]
Doc link: https://docs.wso2.com/display/IS540/Configuring+WSO2+EI+Entitlement+Mediator+with+Identity+Server

Description:
Configuring the EI entitlement mediator step 5-  Could not find "Policies"  to remove the applied policies from the Binding Hierarchy to continue the scenario in EI 6.1.1.
The content needs to be updated accordingly or older and new EI versions as this is done through dev studio in EI6.1.1.

Doc link to for applying security to a proxy service for EI6 : https://docs.wso2.com/display/EI611/Applying+Security+to+a+Proxy+Service#ApplyingSecuritytoaProxyService-Importingaproxyservice

Suggested Labels
Bug

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
