### ISSUE TITLE
OAuth2/OpenID Connect Configuration endpoints are hard to find on documentation

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2241]
If the particular user wants to write a php or javascript app they need to configure Access Token Endpoint, Authorize Endpoint etc. But those are hard to find on the wso2 doc space and the user may get frustrated due to lack of guidance

**Comment by dakshika** [comment]
Can be seen in some samples but if the user isn't a JAVA guy they may hate this :-1: 

https://docs.wso2.com/display/IS540/Try+Request+Path+Authentication

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
