### ISSUE TITLE
[SCIM][Docs] SCIM interaction samples using charon-core

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2242]
**Description:**
The provided client samples in charon-samples just use huge JSON text blobs for objects, instead of using charon-core.  As a developer attempting to interact with WSO2 Identity Server, it would be very helpful to have examples which make use of charon-core for client implementations in the way the Readme suggests is intended.

In the meantime, does any documentation exist elsewhere for this use case?

also reported in the charon project:
https://github.com/wso2/charon/issues/88

**Suggested Labels:**
Type/Docs

**Affected Product Version:**
github master

**Comment by sagara-gunathunga** [comment]
Thanks for the suggestion, FYI we are in process of moving IS samples into it's own separate repo, will address along with that.
