### ISSUE TITLE
[Doc] Need to link to EI product download page in Configuring WSO2 EI Entitlement Mediator with Identity Server

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#2244]
Doc link : https://docs.wso2.com/display/IS540/Configuring+WSO2+EI+Entitlement+Mediator+with+Identity+Server

Suggested Labels
Improvement

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
