### ISSUE TITLE
[DOC] mention the acronym OIDC in doc

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2248]
https://docs.wso2.com/display/IS540/Adding+and+Configuring+an+Identity+Provider

We have mentioned the OpenID Connect in the doc, but for SEO purpose. IMO we need to optimize with the acronym as well.

https://docs.wso2.com/display/IS530/OAuth2-OpenID+Connect

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
