### ISSUE TITLE
Add tutorial based on Mobile identity provider proxy

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2251]
There is a document on $subject @wso2 main website. 

https://wso2.com/library/articles/2014/07/sso-for-native-mobile-applications-with-wso2-identity-server/

IMO we need to add this to the tutorial section. Then user can easily figure out the capability of using wso2 IS on native mobile app

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
