### ISSUE TITLE
Deprecate and Remove Kerberose KDC

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2259]
Deprecate Kerberos KDC in immediate next major release and remove it in the release after.

**Comment by darshanasbg** [comment]
Lets update documentation on this.. @sherenewso2 Please note.

**Comment by samgnaniah** [comment]
@darshanasbg has this been done? I can see this option under the inbound authenticators list in the SP configuration form.

**Comment by darshanasbg** [comment]
@samgnaniah There are no UI options for this.. Please mention in the docs that we are dedicating this functionality and update any content relevant on this topic to have a note/warning mentioning the same.

Please followup with @thanujalk for any further clarifications.

**Comment by isuruhettiarachchi** [comment]
UI related to the feature is still exists in 5.10 and 5.11 versions.

![Screenshot_2021-02-11 WSO2 Management Console(2)](https://user-images.githubusercontent.com/22415272/107636557-d20ca080-6c92-11eb-995b-4323d74fd1cb.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
