### ISSUE TITLE
IS 5.3.0 latest wum pack cannot login with DB2 database

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#2263]
Steps to reproduce:
1.Configure db2 database as the identity databse in master-datasource.xml
2.Change the identity.xml jndi name to point to the above database
3.start the server with -Dsetup and try to login to the mgt console.
Cannot login.
Following error can be seen in the backend:
ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} -  Error occurred while accessing Java Security Manager Privilege Block
ERROR {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} -  System error while Authenticating/Authorizing User : Error when handling event : PRE_AUTHENTICATION

When disable the event listeners can login to the admin console

**Comment by sagara-gunathunga** [comment]
-Dsetup is not production ready feature so we will get rid of this feature, please refer "[Dev] How to create database tables with -Dsetup in Carbon 5?" thread. Please reopen the issue if this error occur when connecting to manually created database without using -Dsetup option.
