### ISSUE TITLE
Feature Management add repository get failed due to blank space

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2279]
How to reproduce

1. Log into the Management Console.
2. Click Configure, and then click Features.
3. Click Repository Management, and then click Add Repository.
4. Enter the name and add URL with space
"http://product-dist.wso2.com/p2/carbon/releases/wilkes/ "

Get error saying Error on URL but IMO we need to trim and add the URL

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
