### ISSUE TITLE
Cannot generate authorization code without browser interaction when using request path authentication in IS 5.1.0

### ISSUE THREAD

**Issue by Saubhy** [wso2/product-is#2288]
Steps to reproduce.

1. Change **SkipUserConsent** property in <IS_HOME>/repository/conf/identity/identity.xml file to **true**.
2. Login to Management Console.
3. Navigate to **Service Provider** -> **Add**. Provide a service provider Name and click **Register**.
4. Expand the **Inbound Authentication Configuration** section, then the **OAuth2/OpenID Connect Configuration** and click **Configure**. Provide the **Callback URL** and click **Add**.
5. Expand the **Local & Outbound Authentication Configuration** section and then the **Request Path Authentication Configuration** section.
6. Select **basic-auth** and click **Add**. Click **Update** to save changes to the Service Provider.

7. Then execute following CURL command through the terminal to get the code.

`curl -v -X POST --basic -u USERNAME:PASSWORD -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "response_type=code&client_id=CLIENT_ID&redirect_uri=CALLBACK_URL&scope=openid"  https://localhost:9443/oauth2/authorize`

Expected response:
Location: https://xi-cloud/callback?code=cfd244a8-a1cb-3fe7-83ea-35ccdd5c6c91&session_state=d7a61d1d8bb0939d95a6b3d4732cb2d7ca8b5c2624601e9ff9edc9b1f3e5071c.ArCaKAuJ51EPcdz-B17Fcw

Actual response doesn't contain the **code** parameter. 
This works perfectly in the browser, but not through back channel. This issue is fixed in IS 5.3.0.

**Comment by GDRDABARERA** [comment]
This issue is already fixed in latest version of WSO2 IS above IS 5.3.0. Hence, closing this issue
