### ISSUE TITLE
Facebook authenticator fails if "Not now" is clicked without providing credentials

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#2289]
Steps to reproduce:

1. Setup an SP for SSO
2. Configure a multi option step where FB is one of the options
3. At the option selection page select FB
4. At FB login page click "Not now"

Then following error occurs:
```
[2018-02-07 15:28:40,176] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework
org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: No authenticator can handle the request in step :  1
```

**Comment by IndunilRathnayake** [comment]
Fixed with https://github.com/wso2-extensions/identity-outbound-auth-facebook/pull/33
