### ISSUE TITLE
Wso2 is 5.1.0 escapes username with + and adds 2 cn attribute

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#2293]
In wso2 is 5.1.0. When we going to add a new user with "username + char" they observed that user added with "username +char" and 2 "cn" is added as part of LDAP.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
