### ISSUE TITLE
[Doc] Description or page link should be given for setting database at deployment pattern page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#2296]
As $subject, description or link to point particular page is missing in[1]. Please update accordingly.
![db](https://user-images.githubusercontent.com/15671620/36085279-b8c56736-0fea-11e8-98dd-d23c2ab38a29.jpeg)

Labels:
IS-5.4.1 
Type/document
Type/bug

[1] [https://docs.wso2.com/display/IS541/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Settingupthedashboard]

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
