### ISSUE TITLE
[DOC] File update instructions not clear

### ISSUE THREAD

**Issue by dakshika** [wso2/product-is#2297]
https://docs.wso2.com/display/IS541/Setting+Up+the+Sample+Webapp

Step 5> Make sure to update param-value parameter in the WEB-INF/web.xml

IMO we need to mention the file location clearly. It's not clear that we asked to update the web.xml after the deployment to tomcat or the change on source code before the build. Also, path needs to update with full path, instead of saying WEB-INF/web.xml

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
