### ISSUE TITLE
[Doc] Property 'TenantManager' is missing in sample jdbc configs

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#2300]
All sample configs given at page[1] for $subject. Due to miss config am getting below error when server startup. Please update the doc.

`[2018-02-12 14:24:44,586] ERROR {org.wso2.carbon.user.core.config.RealmConfigXMLProcessor} -  Required property 'TenantManager' not found for the primary UserStoreManager in user_mgt.xml. Cannot start server!
[2018-02-12 14:24:44,592] ERROR {org.wso2.carbon.user.core.internal.Activator} -  Cannot start User Manager Core bundle
org.wso2.carbon.user.core.UserStoreException: Required property 'TenantManager' not found for the primary UserStoreManager in user_mgt.xml. Cannot start server!`

Labels:
IS-5.4.1
Type/bug
Type/documentation

[1] [https://docs.wso2.com/display/IS541/Configuring+a+JDBC+User+Store]

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
