### ISSUE TITLE
LDAP groups not listed in scim2 in wso2is 5.4

### ISSUE THREAD

**Issue by csbrogi** [wso2/product-is#2309]
I am using wso2is in version 5.4 with ldap readonly  user store. I  have scim2 enabled and I am able to list users via the /scim2/Users  Interface as expected. When I try to list the groups by calling the /scim2/groups Interface,  only 2 groups are returned: the PRIMARY/admin group - I guess this is an  internal group and another group, which is the LDAp group configured as AdminRole in the user-mgt.xml file. If I list the roles (groups) from the admin console, much more roles are  listed, which are imported from LDAP, oddly enough the role  corresponding to the group listed by the Groups Command is not visible. When I call the /Users command, on the console messages are logged:
`[2018-02-06 12:49:02,798] DEBUG {org.wso2.carbon.identity.scim2.common.group.SCIMGroupHandler} -  The group MID.Portal.Consulting is not a SCIM group. Skipping..`

I can add the groups manually by inserting them to the database, but wso2is should add them automatically.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
