### ISSUE TITLE
[Doc] OAuth 2.0 with WSO2 Playground Docs Outdated

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#2315]
[OAuth 2.0 with WSO2 Playground](https://docs.wso2.com/display/IS541/OAuth+2.0+with+WSO2+Playground) are out of date. For example, step 6 of [Try Authorization Code Grant](https://docs.wso2.com/display/IS541/Try+Authorization+Code+Grant​) is incorrect. Current playground app shows a Get UserInfo button and a Logout button at this step.

**Comment by nilasini** [comment]
Duplicates
https://github.com/wso2/product-is/issues/2973
