### ISSUE TITLE
New Oauth2 DAO classes missing unit test cases.

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#2320]
From 5.4 onwards TokenMgtDAO class was deprecated and new AccessTokenDAO,AuthorizationCodeDAO was introduced.

But the unit tests are still written for deprecated TokenMgtDAO class.
New set of unit tests are needed for newly introduced classes.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
