### ISSUE TITLE
Incompatible mysql script naming for 5.6 and 5.7

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2322]
In the product, inside dbscripts folder we can see there are separate MySQL scripts for 5.6 and 5.7 for carbon and identity. 

But there is only one mysql scripts inside metrics and BPS. Can you please confirm whether this script is valid for both 5.6 and 5.7 or should there be another script for 5.7? Please confirm. If so mention that in the document [1] and this doc [2] under 3 rd point in **Configurations for a single node in production** section

[1] https://docs.wso2.com/display/IS550/Data+Dictionary
[2] https://docs.wso2.com/display/IS550/Deployment+for+Small+and+Medium-sized+Enterprises

**Comment by madurangasiriwardena** [comment]
If there is not specific database script provided for MySQL 5.7, available script should work for any version (5.5, 5.6, 5.7) of the database.

**Comment by pulasthi7** [comment]
Verified that the BPS and metrices scripts work for 5.7. 

Better to mention in the docs that the scripts are valid for all the mysql versions, unless there is a specific file with version is provided.

**Comment by sherenewso2** [comment]
Added a note [1] 

[1] https://docs.wso2.com/display/IS550/Data+Dictionary
