### ISSUE TITLE
Specify in which log file user creation activity gets logged

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2338]
Document: [Configuring Users](https://docs.wso2.com/display/IS550/Configuring+Users#ConfiguringUsers-Addinganewuserandassigningroles)
In this doc, please specify in which log file user creation activity gets logged and how it is getting logged. When the product gets GDPR compliant, this information should be available in the docs in order to users to check once any modification is done. If it has been mentioned in some other document, please provide the reference. If this information gets saved in multiple places in different log files, please mention all the locations. 

Priority/High
Type/Docs
Severity/Major

**Comment by sherenewso2** [comment]
@JKAUSHALYA  @ruwanta any idea about the specific log files for this?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
