### ISSUE TITLE
No record has been created in audit log file when role permission is updated. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2347]
## Steps to re-create
1. Login to Management Console and create a secondary JDBC user store - JDBCUSERSTORE
2. Create JDBCUSERSTORE/Finance role with login permission only. 
3. Now update the permission of the above role as below. 
`All Permissions > Admin Permissions > Identity > Entitlement PAP Management`
4. Verify the audit log. 

**Expected:** Permission update record should be logged in audit log file. 
**Actual:** No record is created on update operation. 

Priority/High
Severity/Major
Type/Bug
Affected/5.5.0-M4

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
