### ISSUE TITLE
No record is created in audit log after it is cleared. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2349]
## Steps to re-create

1. Start the Identity Server and login to Management Console. 
2. Create 2 users and verify those records are created in audit.log file. 
3. Open <IS-HOME>/Repository/Logs/audit.log file and clear all the logs and save it. Make sure no log is printed in audit log file. 
4. Now redo the step 2. 

Expected: user creation records need to be created in audit.log file. 
Actual: No record is created after clearing the logs. 

Type/Bug
Severity/Major
Priority/High
Affected/5.5.0-M4

**Comment by ruwanta** [comment]
This is the behavior of any live logs. Log files are opened with only "A" (Append) flag. Clearing a log causes the OS to loose track of the last written position and then subsequent logs go to /dev/null.

Log can only be cleared after it is rolled out. 

Marking as not a bug.
