### ISSUE TITLE
User role creation unsuccessful attempt - logs do not get recorded in audit.log file

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2351]
## Steps to re-create
1. Create a user role with Admin permission. 
2. Create a user and assign that user to above role. 
3. Log out from admin and log in from the created user credentials in step 2. 
4. Try to create another role with admin permission. 
5. The user is not allowed to create the role with admin permission. 
6. Verify the audit.log file is this failure record is created. 

Expected: The failure record should be created. 
Actual: No record of above operation. 

Type/Bug
Priority/Normal
Severity/Major
Affected/5.5.0-M4

**Comment by ruwanta** [comment]
Audit log is for auditing purposes.
This should list what (sensitive) change was done, by whom, at what time.
There is no reason to put failed cases in audit log as there is no change was made. It can go to error log if needed, with reason.

Take an example of a bank statement. It contains only the successful transactions. Not any attempt to withdraw money, which has not been successful.

**Comment by darshanasbg** [comment]
Agreed @ruwanta ..

In general, we need better mechanism to track failure operations. Which we would not by adding to audit log but need to have a better strategy which can address along with new restful api redesigning..
