### ISSUE TITLE
Explain the each parameter in consent-mgt-config.xml given in doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2359]
Explain the each parameter and possible values could be given in consent-mgt-config.xml given in doc [1]

`<PIIController>
    <PiiController>sample</PiiController>
    <Contact>sample</Contact>
    <Email>sample@abc.com</Email>
    <Phone>+01433444333</Phone>
    <OnBehalf>false</OnBehalf>
    <PiiControllerUrl>https://sample.piicontroller.url</PiiControllerUrl>
    <Address>
        <Country>USA</Country>
        <Locality>Mountain View</Locality>
        <Region>CA</Region>
        <PostOfficeBoxNumber>233</PostOfficeBoxNumber>
        <PostalCode>94043</PostalCode>
        <StreetAddress>1600 Amphitheatre Pkwy</StreetAddress>
    </Address>
</PIIController>`

[1] https://docs.wso2.com/display/IS550/Consent+Management+Using+REST+APIs#ConsentManagementUsingRESTAPIs-Definitionsforconsentmanagement

**Comment by sherenewso2** [comment]
Fixed in [1] under the expand tag "Click to see more information about each property". 

[1] https://docs.wso2.com/display/IS550/Consent+Management+Using+REST+APIs
