### ISSUE TITLE
Correct the AskPassword location which is mentioned in the doc. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2362]
Document: https://docs.wso2.com/display/IS550/Creating+Users+Using+the+Ask+Password+Option
Step 1

In the document it is said generally < AskPassword > element is inside the < Server > tag. But it is actually as below. 

```
<Server>
   <EmailVerification>
          <AskPassword>
          </AskPassword>
   </EmailVerification>
</Server>
```

Therefore please specify the correct location of < AskPassword > element and mention if 
the whole < EmailVerification > tag should be enabled. 

Type/Docs
Priority/Normal
Severity/Major
Affected/5.5.0-M4

**Comment by ShirazAzad** [comment]
Updated the doc [1] by adding more content in identity.xml code block.
[1] https://docs.wso2.com/display/IS550/Creating+Users+Using+the+Ask+Password+Option
