### ISSUE TITLE
[Doc] Give examples for PII data

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2365]
Give examples for PII data in the below section in the doc pointed.

Personally Identifiable Information (PII) - Any information that can be used to identify the PII Principal to whom the information relates to.

https://docs.wso2.com/display/IS550/Consent+Management+Using+REST+APIs#ConsentManagementUsingRESTAPIs-APIsandsupportedoperations

**Comment by sagara-gunathunga** [comment]
We don't need to overload our docs with generic  information available in the web and allover in our tutorials, here PII definition is enough so that users can understand we also use PII with same definition.
