### ISSUE TITLE
IS should get user consent before it store tokens (SAML/OIDC) from 3rd party IDP

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2366]
IS should get user consent before it store tokens (SAML/OIDC) from 3rd party IDP, this consent should explan the purpose and timelimit etc.  In case the user reject this consent IS should not store token and should fail flow.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
