### ISSUE TITLE
Why we can't enable 'Audience Restriction' for JWT by default 

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2370]
According to following doc : https://docs.wso2.com/display/IS550/Configuring+OAuth2-OpenID+Connect+Single-Sign-On 

It's required to enable <EnableAudiences>true</EnableAudience> before add any audience restrictions, why we can't make this setting 'true' by default ?

**Comment by emswbandara** [comment]
This property is true by default in 5.5.0.
The doc mentions to ensure that this property is set to true.
