### ISSUE TITLE
Location of identity.xml is incorrect

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2372]
Document:  https://docs.wso2.com/display/IS550/Creating+Users+Using+the+Ask+Password+Option#CreatingUsersUsingtheAskPasswordOption-Managementconsole
Step 6

Please correct the location of identity.xml as <IS_HOME>/repository/conf/identity/identity.xml

Type/Docs
Affected/5.5.0-M4
Priority/Normal
Severity/Major

**Comment by omindu** [comment]
This is fixed now in 5.3.0 ... 5.5.0 docs. Thanks!
