### ISSUE TITLE
Correct IS 5.3.0 as IS 5.5.0

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2374]
Document: https://docs.wso2.com/display/IS550/Creating+Users+Using+the+Ask+Password+Option#CreatingUsersUsingtheAskPasswordOption-SCIM2.0
Section: SCIM 2.0
Before you begin box. 

Please correct IS 5.3.0 as IS 5.5.0

Type/Docs
Affected/5.5.0-M4
Severity/Major
Priority/Normal

**Comment by omindu** [comment]
Fixed in 5.4.0 ... 5.5.0. Thanks
