### ISSUE TITLE
Configuring SCIM 2.0 Provisioning Connector Documentation redirects to configuring IS5.3.0

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2375]
Document: https://docs.wso2.com/display/IS550/Creating+Users+Using+the+Ask+Password+Option#CreatingUsersUsingtheAskPasswordOption-SCIM2.0
Section: SCIM 2.0

This redirects the user to Configuring SCIM 2.0 Provisioning Connector for IS 5.3.0. 
Please provide the doc for 5.5.0 and redirect to it. 

Type/Docs
Affected/5.5.0-M4
Priority/Normal
Severity/Major

**Comment by Nashaath** [comment]
The reported issue is already fixed since doc[1] has been updated to remove the word IS 5.3.0 from the content.

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+SCIM+2.0+Provisioning+Connector
