### ISSUE TITLE
No details about the property SCIMEnabled in userstore

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2378]
Document: https://docs.wso2.com/display/IS550/Configuring+Users#ConfiguringUsers-CreatingnewusersusingSCIM
Section: Creating new users using SCIM

Please make a note for the user to check if SCIMEnabled is set to true is the primary user store. 

Type/Docs
Affected/5.5.0-M4
Priority/normal
Severity/Major

**Comment by ShirazAzad** [comment]
Updated the doc [1] with the note that the SCIMEnabled should be set to 'true'.

[1] https://docs.wso2.com/display/IS550/Configuring+Users#ConfiguringUsers-CreatingnewusersusingSCIM
