### ISSUE TITLE
Check whether public cert is configured at SP when enabling request object signature validation or ID token encryption

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2384]

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Comment by nilasini** [comment]
Same issue is being tracked already with https://github.com/wso2/product-is/issues/11206
