### ISSUE TITLE
Provide SP level config to configure id token encryption algorithms

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2387]

**Comment by mefarazath** [comment]
@vihanga-liyanage

**Comment by vihanga-liyanage** [comment]
@mefarazath please close the issue.

**Comment by mefarazath** [comment]
UI option to provide SP level config to configure id token encryption algorithms have been added from IS 5.5.0-beta onwards as below.

![](https://user-images.githubusercontent.com/9441136/36909167-4ab4dd62-1e63-11e8-970c-b3a4af77707d.png)
