### ISSUE TITLE
Show the display-name of the claim instead of claim URI, in the self registration page and user consent gadget

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#2390]
Display Claim display name instead of claim URI, when self-registration and user portal consent gadget.

**Comment by IsuraD** [comment]
Added DisplayName support for PII Category with https://github.com/wso2/carbon-consent-management/pull/62/

**Comment by IsuraD** [comment]
Adding purposes/PII categories with displayName and description is supported with 

https://github.com/wso2/carbon-consent-management/pull/63/

**Comment by IsuraD** [comment]
@thusithak,
Now we can change the signup page and dashboard with displayName instead of claim URI.

**Comment by thusithak** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1381

**Comment by hasinthaindrajee** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1381
