### ISSUE TITLE
Use char (1) in DDL scripts instead of boolean

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2401]
As some of the DBs doesn't support boolean data type, char (1) should be set as a data type in DB script. Along with this, the prepared statement should be fixed to handle setting and getting values for columns with char (1) data type.

eg:
- OIDC request object

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1388 and https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/823
