### ISSUE TITLE
Always return to Dashboard after trying out Forgot UserName/Password in SSO Login page

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#2403]
Please find the steps to create this issue.

1. Configure travelocity application with identity server (Service providers etc.)
2. Click login button in travelocity application
3. Click on Forgot Password/Username
4. Click cancel button of Forgot password/Username screen
5. Enter valid username and Password and sign in
6. It is redirecting to Identity Server Dashboard

Ideally, it should return to a correct service provider which initiated the login request. As per the SAML tracer, once we click on cancel button in Forget Password/Username, it sends a SAML request with issuer "wso2.my.dashboard", So after that, it's proceeding as Dashboard issuer.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
