### ISSUE TITLE
Carbon console:  Login page needs Privacy and Cookie policy links

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#2413]
Need to add this into carbon kernel 4.4.x
Add default pages for Privacy and Cookie policy, in 4.4.x which will be packed into each product.

**Comment by ashensw** [comment]
Carbon console is targeted on identity admins. Hence reducing the severity.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
