### ISSUE TITLE
Per SP consent management support

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2418]
Consent management should be able to enable/disable at SP level.

**Comment by johannnallathamby** [comment]
In all the webinars we've done on GDPR, we talk about IS as a consent repository that can do consent management of applications through Restful APIs. However, when looking at the APIs it looks like we can't really do application wise consent management and it is global consent management model we have.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
