### ISSUE TITLE
Add sample purposes including default purpose at server startup and tenant creation. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#2420]
Add sample purposes including default purpose at server startup and tenant creation.

**Comment by darshanasbg** [comment]
Better to use tenant loading listeners to implement things needed to be done at tenant creation.. This make sure those things get executed properly,
* in a migrated setup where tenants are already created in the system
* when tenant created on a other product in a multiproduct deployment

To achieve first concern, it could handle the same in the migration client as well.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
