### ISSUE TITLE
CustomUserStore sample code is not build

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#2422]
https://github.com/wso2/product-is/blob/5.x.x/modules/samples/user-mgt/sample-custome-user-store-manager/pom.xml

It doesn't have parent pom details.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
