### ISSUE TITLE
Explain requirePasswordChange element in addUser() adminService

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2423]
Document: https://docs.wso2.com/display/IS550/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addUser()
Please explain requirePasswordChange property in the addUser() request. Further, explain when we add users through Management console, for which step this get tallies with. 

Type/Docs
Affected/5.5.0-M4
Priority/Normal
Severity/Minor

**Comment by rksk** [comment]
One and a half years gone :(

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
