### ISSUE TITLE
In consent gadget, move the receipt ID to detailed view section

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2434]
![image](https://user-images.githubusercontent.com/9883427/36338388-a55e48e2-13d3-11e8-88af-f917f17fa32c.png)

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/product-is/pull/2652

**Comment by ayshsandu** [comment]
![cosent](https://user-images.githubusercontent.com/5061791/36664720-90a0d462-1b0b-11e8-966e-a593e772cc0d.png)
 Id is moved to sub line.
