### ISSUE TITLE
Change the post authentication error page

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2439]
![image](https://user-images.githubusercontent.com/9883427/36339423-317b7bc6-13eb-11e8-8b03-ae0a9c075760.png)

This page should be modified to to give a message without disclosing framework internals.

**Comment by hasinthaindrajee** [comment]
This is changed with [1] and [2]

[1] https://github.com/wso2/carbon-identity-framework/pull/1409
[2] https://github.com/wso2/carbon-identity-framework/pull/1412
