### ISSUE TITLE
Document information on customizing consent page

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2441]

**Comment by harsha1979** [comment]
When we write this, please mention about this "sessionDataKeyConsent" parameter because this ConsentSubmit is identified by the OAuth endpoint using this paramter.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
