### ISSUE TITLE
Fix - Security error for container __gadget_gadgetArea-d5

### ISSUE THREAD

**Issue by thusithak** [wso2/product-is#2446]
### How to reproduce
- Open browser console in a new tab
- Goto https://localhost:9443/dashboard/
- wait for about 15 seconds to see below error generated from `shindig.js:15`

`Security error for container __gadget_gadgetArea-d5 : OpenAjax.hub.SecurityAlert.LoadTimeout`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
