### ISSUE TITLE
Dashboard UI responsiveness issue @media (max-width: 979px)

### ISSUE THREAD

**Issue by thusithak** [wso2/product-is#2447]
### How to reproduce
- Goto https://localhost:9443/dashboard/index.jag
- simulate screen width < 979px
- click on hamburger menu at top right of the UI

![responsiveness_fail](https://user-images.githubusercontent.com/11048376/36353333-4ae312a8-14eb-11e8-8ed9-0e16dcd32813.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
