### ISSUE TITLE
Properly arrange user dashboard gadgets for all users

### ISSUE THREAD

**Issue by thusithak** [wso2/product-is#2450]
There's a layout arrangement issue when dashboard gadgets are hidden for low-permission level users. 

Also clean up these files
-  [product-is/modules/jaggery-apps/user-dashboard/dashboard/apis/gadget.json](url) 
-  [product-is/modules/jaggery-apps/user-dashboard/dashboard/index.jag](url)

![clean_and_arrange_gadgets](https://user-images.githubusercontent.com/11048376/36362688-ee1a215c-155c-11e8-9973-58d5863b7c62.png)

### How to reproduce
- create a new user with only login permission
- Goto https://localhost:9443/dashboard/

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
