### ISSUE TITLE
Migration for DB backed Service Provider application certs for request object validation

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2457]
Previously(before IS 5.5.0-alpha) we supported storing application/SP public cert in keystore. Now we have removed that support and moved to DB backed public certificates.

Therefore we would require to provider a migration from public certs in keystore to db backed public certs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
