### ISSUE TITLE
Integrate XACML based scope validation for OAuth2

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2459]

**Comment by senthalan** [comment]
- [ ] Core implementation of XACML based scope validation for access token - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/801

- [ ] Test for core implementation of XACML based scope validation for access token - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/802

- [ ] Scope validator for application management core - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/808

- [ ] WSDL changes for add scope validation for application management - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/810

- [ ] UI changes for add scope validation for application management - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/811

- [ ] Change default scope validator to execute for only registered validators during token validation - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/812

- [ ] Database script and Configuration changes for xacml based scope validator for OAuth2 token - https://github.com/wso2/carbon-identity-framework/pull/1333

- [ ] XACML Sample policy - https://github.com/wso2/product-is/pull/2329 

- [ ] Migration script for xacml based scope validator for OAuth2 token - https://github.com/wso2/product-is/pull/2328

**Comment by senthalan** [comment]
- Change scope validator position in identity.xml  - https://github.com/wso2/carbon-identity-framework/pull/1370

**Comment by senthalan** [comment]
- policy mover PRs - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/819 , 
https://github.com/wso2/product-is/pull/2633

**Comment by senthalan** [comment]
- Encode the scope validator name before display - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/814

**Comment by senthalan** [comment]
- Integration Test - https://github.com/wso2/product-is/pull/2681

**Comment by senthalan** [comment]
- Add method to specify the display name for scope validator - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/821

**Comment by senthalan** [comment]
- Move the core implementation of the XACML based scope validator to oauth addons repo -https://github.com/wso2-extensions/identity-oauth-addons/pull/13
- Add xacml based scope validator as a feature in product IS. And copy jar and sample policy - https://github.com/wso2/product-is/pull/2875
- Change scope validator in identity.xml to new feature - https://github.com/wso2/carbon-identity-framework/pull/1462
- Revert xacml based scope validtor in inbound auth -  wso2-extensions/identity-inbound-auth-oauth#801,  wso2-extensions/identity-inbound-auth-oauth#802

**Comment by mefarazath** [comment]
All PRs merged. Hence closing the issue.
