### ISSUE TITLE
Correct the typo in Consent management for SSO document

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2461]
Document: https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On#ConsentManagementwithSingle-Sign-On-ConsentmanagementflowforSSO
Step3
'Note' box

Please correct 'u ser' as 'user'.

Type/Docs
Affected/5.5.0-Alpha
Priority/Low
Severity/Minor

**Comment by omindu** [comment]
Fixed. Thanks!
