### ISSUE TITLE
Provide a reference link to creating a service provider flow.

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2464]
Document: https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On#ConsentManagementwithSingle-Sign-On-ConsentmanagementflowforSSO
Since this section is the middle of configuring a Service Provider flow, for a user reference, provide the reference link to the configuring Service Provider document at the beginning of the flow. 

Type/Docs
Affected/5.5.0-Alpha
Priority/Normal
Severity/Minor

**Comment by sherenewso2** [comment]
Added a link to [1] 

[1] https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On#ConsentManagementwithSingle-Sign-On-ConsentmanagementflowforSSO
