### ISSUE TITLE
Need a differentiation between the privacy and cookie policy labels

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2466]
![1](https://user-images.githubusercontent.com/1845370/36368231-487bf1a6-157c-11e8-88e3-f4756a79acd9.png)

Seems like a one word

**Comment by thusithak** [comment]
Fix
1. Text will change for cookie policy
After successful login we use a cookie in your browser to tag your session. for more details, refer our cookie policy from here.
2. ATM include empty page to have policy content.

**Comment by emswbandara** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1368
