### ISSUE TITLE
Provide the correct sample version

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2467]
Document: https://docs.wso2.com/display/IS550/Downloading+a+Sample
Step 4
The user is asked to checkout the v5.4.0 tag. Please correct it as v5.5.0. Further, change the version of the following command accordingly. 
`
git checkout -b v5.5.0-M1 v5.5.0-M1`

Type/Docs
Affected/5.5.0-Alpha
Priority/High
Severity/Major

**Comment by Nashaath** [comment]
Updated step 4 and the command to reflect the current release tag v5.5.0-alpha3. Will keep track of this and change it accordingly based on the upcoming releases.
