### ISSUE TITLE
Configuring commonauth URL parameter for SAMLSSOAuthenticator not documented

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#2468]
We can change commonauth URL for federated authentication by adding the following parameter under SAMLSSOAuthenticator in application-authentication.xml. This is not documented.

<Parameter name="SAMLSSOAssertionConsumerUrl">http://127.0.0.1:9443/commonauth</Parameter>

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
