### ISSUE TITLE
Explain the importance of adding the Application Certificate when configuring the SP

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2469]
Document: https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On#ConfiguringSingleSign-On-Configuringtheserviceprovider
Step 5

Please add a note of the importance of this step, in what kind of a scenario user needs to do this step. 

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/Normal

**Comment by rushmin** [comment]
@isuruuy429, A comprehensive explanation of application certificates is documented [here](https://docs.wso2.com/display/IS550/Adding+and+Configuring+a+Service+Provider)

However, as you pointed out, we should connect the above explanation in SSO configuration.

@ShirazAzad  and @sherenewso2  shall we do this modification.

**Comment by ShirazAzad** [comment]
Updated the doc [1] with a reference to [2] 

[1] https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On#ConfiguringSingleSign-On-Configuringtheserviceprovider

[2] https://docs.wso2.com/display/IS550/Adding+and+Configuring+a+Service+Provider
