### ISSUE TITLE
Configuring Claims for a Service Provider link redirects to an older version of the doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2470]
Document: https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On#ConfiguringSingleSign-On-ConfiguringClaims
Step1
Configuring Claims for a Service Provider link redirects to 5.3.0 document. 

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by sherenewso2** [comment]
Fixed the links in [1] 

[1] https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On
