### ISSUE TITLE
'Enable Attribute Profile' is not included in the screenshot in SP configuration using SAML2 document

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2472]
Document: https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On#ConfiguringSingleSign-On-Configuringtheserviceprovider
Step 9(screenshot)

This example carries configuring claims for Service Provider(SAML2) and maps custom claims which need to enable '**Enable Attribute Profile**' and  **'Include Attributes in the Response Always**' checkboxes as per [Claim mapping](https://docs.wso2.com/display/IS550/Configuring+Claims+for+a+Service+Provider) document. But the screenshot mentioned in step 9 in above-mentioned document does not include it, which may mislead the user. Therefore provide the correct screenshot which has those two attributes ticked.

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by Nashaath** [comment]
Updated the screenshot with the specified fields selected.
