### ISSUE TITLE
Provide a note/reference/screenshot on consent management

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2474]
Document: https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On#ConfiguringSingleSign-On-Runningthesample

In this example, custom claims have been added. As consent management has been enabled by default in IS5.5.0, there will be a middle step before login to Travelcoity application, which asking the approval for user consent from the user. 
Therefore, please provide a note/reference doc/screenshot on consent management after step2(Running a sample). 

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by sherenewso2** [comment]
Added to [1] 

[1] https://docs.wso2.com/display/IS550/Configuring+Single+Sign-On#ConfiguringSingleSign-On-Runningthesample
