### ISSUE TITLE
Complete the incomplete sentences in the document. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2475]
Document: https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On#ConsentManagementwithSingle-Sign-On-ConsentmanagementflowforSSO
Step 4

**The user has revoked consent for the application. For more information on revoking user consent, see** 

Please complete the above sentence and provide resources if need any.

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/Normal

**Comment by sherenewso2** [comment]
Added the relevant link [1] 

[1] https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On#ConsentManagementwithSingle-Sign-On-ConsentmanagementflowforSSO
