### ISSUE TITLE
Document should mention we need to provide permission to the forget-me file

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2478]
Document should mention we need to provide permission to the forget-me file to execute ./forget-me -U <username> in this [1] doc under running the tool section

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-MasterConfig

**Comment by JKAUSHALYA** [comment]
What kind of permissions that are you suggesting ? By default forgetme.sh file do have Linux level execute permission. Are you suggesting that we have to document that the tool should be executed by a privilege user who should have access to DB, Logs, etc... ?

**Comment by ushanib** [comment]
Hi,
./forget-me could not be run without providing executable permission. Would be better if a note can be mentioned.

**Comment by Nashaath** [comment]
This will be fixed so that ./forget-me can be run without having to provide executable permission.
Jayanga mentioned that he will provide the PR to fix this.
