### ISSUE TITLE
No option to navigate back in some features in the dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2479]
No option to navigate back in the below features of the dashboard. Some features have a cancel button which allows the user to go back

- Associated accounts
- Login sessions
- Pending approvals
- Monitor users login sessions
- Consent management

**Comment by sagara-gunathunga** [comment]
We will consider these inputs when design new user portal in Q2/Q3

**Comment by dilinisg** [comment]
Hi Sagara,

If you are planning to fix this in a future release, can we change the resolution to "Postponed"? If it will not be fixed, you can keep it as it is.

Thanks
