### ISSUE TITLE
When user/role is created with invalid characters, the validation happens at the end. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2481]
When creating a user role, if any invalid role name is used, user does not get validated right at that point. After selecting users/permission and then finally role name pattern get validated. In user point of view, it takes time define permissions/ select users. But if we could validate the rolename/ username right at the point if the pattern is valid, user time is saved. 

## Steps to re-create

> Pre-requisite: create user: user001

1. Start Identity Server and log in to Management Console. 
2. In the Main tab, under Add Users and Roles, select Add > Add New Role. 
3.  Provide information as below. 
Domain: Primary

> Role Name: role-1234
> Permission: admin/login
> Permission: admin/manage/Identity/Claim Management
> Permission: admin/manage/Identity/Consent Management/Add
> user: user001

4. Click Finish button. 

Now only the role name gets validated. If this was done in the beginning, considerable effort would be saved. The same thing applies to the user creation as well. 

Type/Improvement
Affected/5.5.0-Alpha
Priority/Normal
Severity/Major

**Comment by sagara-gunathunga** [comment]
This known limitation of Carbon UIs
