### ISSUE TITLE
Document should mention why we have datasources and if any changes should be done in datasources.xml files

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2485]
Document should mention why we have datasources and if any changes should be done in datasources.xml files.

When you consider below location, there are several datasource.xml files with DB configs.
Document should provide information what exactly they are and if any changes should be done in this [1] doc. It only mentions below.

"Contains the datasources that should be connected to remove references to deleted user identities."

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-Configuringtheconfig.jsonfile

identity-anonymization-tool/components/org.wso2.carbon.privacy.forgetme.tool/target/org.wso2.carbon.privacy.forgetme.tool-1.0.3-SNAPSHOT/conf/datasources

**activiti-datasources.xml  apim-datasources.xml  cdm-datasources.xml  master-datasources.xml**

**Comment by Nashaath** [comment]
Checked with Jayanga on the exact purpose of the datasources directory and updated the description accordingly.
