### ISSUE TITLE
Can we simplify the forget me tool structure?

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2486]
Can we simplify the forget me tool structure?
As an end user, for me it contains whole lot of files and configurations. E.g., If you take below path, in order to go in to datasource folder, you should go in to 7 folders.

identity-anonymization-tool/components/org.wso2.carbon.privacy.forgetme.tool/target/org.wso2.carbon.privacy.forgetme.tool-1.0.3-SNAPSHOT/conf/datasources

**Comment by JKAUSHALYA** [comment]
This is the structure if you ran the tool inside the source repository. This isn't the artifact end user is getting. If you check the target folder there is a zip file as the artifact. After un-ziping it you will get structure like <TOOL_HOME>/conf, <TOOL_HOME>/datsources, <TOOL_HOME>/bin.. etc....
