### ISSUE TITLE
Privacy Policy link in Travelocity Application does not redirect to a privacy note. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2488]
## Steps to re-create
1. Check out samples for v5.5.0-alpha from https://docs.wso2.com/display/IS550/Downloading+a+Sample
2. Register Travelocity as the Service Provider. 
3. Follow the steps in [Consent Management](https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On#ConsentManagementwithSingle-Sign-On-ConsentmanagementflowforSSO) document. 
4. Login to Travelocity, provider details for claims and user will be directed to following screen. 
<img width="1440" alt="screen shot 2018-02-19 at 5 34 42 pm" src="https://user-images.githubusercontent.com/31693103/36377127-e5c64cbc-159b-11e8-9aa3-7432264d6b29.png">

5. Click on Privacy Policy link. 

**Expected:** User should be navigated to privacy note. 
**Actual:** It redirects to the same page. 

Type/Improvement
Affected/5.5.0-alpha
Severity/Major
Priority/High

**Comment by omindu** [comment]
This is already captured with https://github.com/wso2/product-is/issues/2398. Policy URL should be configurable for all SPs.
