### ISSUE TITLE
Document UTF-8 support with Identity Server

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#2491]
**Description**
Document how to configure the support for UTF-8 in the identity server.

**Comment by abhi4u1947** [comment]
For 5.7.0 also please consider this.

**Comment by abhi4u1947** [comment]
A valuable ticket lying open for 2 years and there is no progress or no updates ??

**Comment by nilminiwso2** [comment]
Will address this with https://github.com/wso2/product-is/issues/10352
Thanks for reporting.
