### ISSUE TITLE
Migration consent management 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#2497]
Need to implement a migration client to migrate claim related configs and databases when migrate from 5.4.1 to 5.5.0

**Comment by darshanasbg** [comment]
This has been added with,
https://github.com/wso2/product-is/commit/853ce2245b4e5b09829d80b44a659d86b12b92a4#diff-717c6621cfe628f37dc4ebb259eba4d5

@nuwandiw Please reopen if there are anything yet to added related to $subject.
