### ISSUE TITLE
Add a sample code of custom random password generator for the Ask password documentation. 

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#2501]
When you try to create a user with Ask password option, Identity Server will create a random password for that user using the extension class org.wso2.carbon.user.mgt.common.DefaultPasswordGenerator, until the user configures a new password. So when you enable a Password Policy [1] it might give an error if the generated random password violates the policy that you have defined in your configurations.

To overcome that issue you can write a custom random password generator which does not violate your password policy. I have attached sample code ([wso2-sample-custom-password-generator.zip](https://github.com/wso2/product-is/files/1801491/wso2-sample-custom-password-generator.zip)) of a custom password generator for your reference. And do the following steps to use your custom password generator for ask password option.

1. Build the custom password generator source and get the com.wso2.password.policy-1.0.0.jar file.
2. Copy the jar file into <IS_HOME>/repository/components/lib directory.
3. Start the server.
4. Then you need to configure your custom password generator class form the management console in order to use it instead of DefaultPasswordGenerator. Please do the following steps.

- Click Resident under Identity Providers found in the Main tab of the IS management console.
- Expand the Account Management Policies tab.
- Expand the User Onboarding tab and define your custom password generator class in Temporary password generation extension class section. (ex: com.wso2.password.policy.CustomPasswordGenerator)

Then you should be able to create a new user with ask password option without any issue.

Add the above sample for Ask password documentation [2].

[1] https://docs.wso2.com/display/IS541/Password+Patterns
[2] https://docs.wso2.com/display/IS541/Creating+Users+using+the+Ask+Password+Option

**Comment by andeandr100** [comment]
Thx, this saved me a lot of time.

But should not "01" be in the digits string?
Currently in the zip file the digits only contains "23456789"

**Comment by hauntingEcho** [comment]
it looks like this was already added [here](https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt.common/src/main/java/org/wso2/carbon/user/mgt/common/DefaultPasswordGenerator.java)

**Comment by hauntingEcho** [comment]
it looks like this was already added [here](https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt.common/src/main/java/org/wso2/carbon/user/mgt/common/DefaultPasswordGenerator.java)

**Comment by hauntingEcho** [comment]
possibly superseded by #4600

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
