### ISSUE TITLE
"Mandatory claims required" message is shown even when there are no mandatory claims

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2503]
"Mandatory claims required" message is shown even when there are no mandatory claims which confuses the user. 

![10](https://user-images.githubusercontent.com/1845370/36411437-a36c5d34-163b-11e8-8fde-f56cfbcc339b.png)

Expected
1. Should not show this message when there are no mandatory claims
2. The explanation of (*) should be at the bottom of the claims when there are mandatory claims

**Comment by thanujalk** [comment]
Now the message has updated as below,
<img width="611" alt="screen shot 2018-03-01 at 3 36 38 pm" src="https://user-images.githubusercontent.com/1498339/36839149-2e0565d0-1d67-11e8-8c6b-eae8390e250e.png">

This message is required to inform the user there are no mandatory claims requested by the service provider.
