### ISSUE TITLE
Need a meaningful error message when the user denies to share data

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2504]
**Steps**:
1.  Log into travelocity app
2. Deny sharing information

**Expected**
Need a meaningful error message when the user denies to share data. The message should mention the reason for the failure; that you cannot proceed as you cannot share the information.

![11](https://user-images.githubusercontent.com/1845370/36411555-3b3b66fa-163c-11e8-9a19-e1b20393ecd0.png)

**Comment by omindu** [comment]
Fixed with: https://github.com/wso2/carbon-identity-framework/pull/1412
