### ISSUE TITLE
Need a meaningful error message when the user retries after denying to share information

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2505]
**Steps**: 
1. Log into travelocity app 
2. Deny sharing information
3. Go back and try to login again

**Expected**:
Need a meaningful error when the user retries to login in after denying to share information. It should mention why you cannot proceed.

![12](https://user-images.githubusercontent.com/1845370/36411682-b768d078-163c-11e8-88e1-7f492cedbc85.png)

**Comment by hasinthaindrajee** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1409
