### ISSUE TITLE
How do we change the claims we need to share later after approving once?

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2507]
**Scenario**
Assume the SP requests 3 claims (not mandatory)
1. Log into travelocity app 
2. Approve sharing only 2 claims

After this, the user wants to either give access to the third claim or deny one of the claims he approved earlier. Is there any mechanism to change these after the first attempt?

IMO, the user should be able to change the preferences at anytime.

**Comment by omindu** [comment]
This can be achieved through the dashboard [1]. A user can remove consent for the attributes he/she already given consent to thought the dashboard. If the user wants to add a consent for an attribute he/she has not given previously, the existing consent for the service provider should be revoked first and login again. Then the user will be prompted to with all the required claims for consent.

This should be documented IMO. Created [2] to track it.

[1] -
 https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Configuringconsentforservices
[2] - https://github.com/wso2/product-is/issues/2728
