### ISSUE TITLE
All the roles are not visible in the dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2509]
All the roles are not visible in the dashboard

![15](https://user-images.githubusercontent.com/1845370/36414235-a2aeccf4-1647-11e8-9e6a-2892a92b5bed.png)

**Comment by hasinthaindrajee** [comment]
@dilinisg : Any specific type of roles missing ? Or else are you saying that roles are not visible due to the fact that we have them as read only so that it limits the length of the text box?

**Comment by dilinisg** [comment]
@hasinthaindrajee - I wanted to say the roles are not visible due to the length of the text box. I tried scrolling horizontally and it worked as you mentioned. But, I figured it out only after you mentioning it and I expected it to pop-up a tool tip with the entire list. Shall we improve this in the dashboard? 

Reopening the issue

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
