### ISSUE TITLE
JWT client-handler path should be corrected in the documentation

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2510]
JWT client-handler path should be corrected in the documentation [1]

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

Under below section, **Deploying and configuring JWT client-handler artifacts** it mentions as below: 

Navigate to client-handler/org.wso2.carbon.identity.oauth2.grant.jwt and build.

It should be,

Navigate to **component/client-handler/org.wso2.carbon.identity.oauth2.grant.jwt** and build.

**Comment by ShirazAzad** [comment]
Updated the doc [1] with the correct path mentioned.  
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
