### ISSUE TITLE
Wrong message logged when a JDBC user store is created

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2511]
**Steps**
1. Create a JDBC user store (tried in the tenant domain)
2. Verify logs

**Issue**
It says an LDAP connection is created instead of JDBC

`[2018-02-20 14:18:38,506] @abc.com [1] [IS] INFO {org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager} -  LDAP connection created successfully in read-write mode`

**Comment by thanujalk** [comment]
Above log is not related to the user store creation process. It is printed while verifying whether the logged in user is authorized to perform the operation. For that, IS requires user realm. IS first checks whether realm is available in the realm cache and if not available, IS will initialize a new user realm. In that case, you will see the above log which related to your primary user store(LDAP).
