### ISSUE TITLE
Inheritance of permissions from SaaS SP not possible

### ISSUE THREAD

**Issue by adirtyshame** [wso2/product-is#2512]
When I create a Service Provider as admin@carbon.super in a SaaS Application with custom permissions ('All Permissions' > 'Applications' > SPname > customPermission), I expect to inherit the configured (custom) permission set in all other tenants.
Instead, I only receive the permissions configured in the tenant's SP.

Is this the expected behaviour, and if so, how can I create reusable, global SaaS permissions?

**Comment by sknohsalla** [comment]
+1

**Comment by Odi55555** [comment]
+1

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
