### ISSUE TITLE
Give the command to build in JWT client-handler

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2513]
Give the command to build in JWT client-handler in this doc [1] 2nd step

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

Navigate to client-handler/org.wso2.carbon.identity.oauth2.grant.jwt and build.

**Comment by ruwanta** [comment]
I think we need to modify the docs. The client handler needs to be either
1) available in  the Store
2) packed with the product.

Users should not need to build from the source

**Comment by ShirazAzad** [comment]
Updated the doc [1] addressing the two ways mentioned above. 
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

Please verify
