### ISSUE TITLE
clientauth.jwt jar version mentioned in the doc is different from the actual jar version created

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2514]
clientauth.jwt jar version mentioned in the doc [1] is different from the actual jar version created.

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

It says,
 Place the target/org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt-1.0.2-SNAPSHOT.jar in the <IS_HOME>/repository/component/dropins directory.

But the actual jar created is as,
org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt-1.0.3-SNAPSHOT.jar

**Comment by ShirazAzad** [comment]
Doc [1] updated with the correct jar file version
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
