### ISSUE TITLE
Correct the Typo in the code segment in the doc which will lead to errors

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2515]
Correct the Typo in the code segment in the doc [1] which will lead to errors

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

Below code segment ” should be as " . Otherwise it will be displayed as an XML error in identity.xml if you copy and paste from the doc.
`  <Property name=”TokenEndPointAlias">sample url</Property>`

**Comment by ShirazAzad** [comment]
Updated by correcting the quotes in [1]
https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
