### ISSUE TITLE
Issues in the "Using Email Address as the Username" page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2517]
1. The below phrase says you need to restart only if you change the password. But, you need to restart the server anyway. 

`If you changed the password of the admin user to something other than 'admin', start the WSO2 IS server using the -Dsetup parameter as seen in the command below.`
I tried the same steps and it worked only after restarting. IS team members, please advice.

2. "Supper" tenant occurrences in the below sentence should be changed to "Super"

`You can configure email user name without enabling EnableEmailUserName property, then users can login to both supper tenant and tenant using email and non-email user names. But supper tenant users should always use @carbon.super at the end of user names. `

**Comment by sherenewso2** [comment]
1. That tip is specifically about starting the server with -Dsetup if the admin password has been changed. But either way, step 6 in this doc says to restart the server so it is given as a mandatory step anyway. 

2. This has been corrected by @ShirazAzad in [1].

[1] https://docs.wso2.com/display/IS550/Using+Email+Address+as+the+Username
