### ISSUE TITLE
Explain why we should do cache configuration when Deploying and configuring JWT client-handler artifacts

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2518]
Explain why we should do cache configuration when Deploying and configuring JWT client-handler artifacts in this doc [1]
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

In step 5 it says,
Do the cache configuration in <IS_HOME>/repository/conf/identity/identity.xml as shown below:

**Comment by ShirazAzad** [comment]
Updated the doc [1] describing in a note why this Cache configuration is needed. 
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
