### ISSUE TITLE
Need a meaningful error message when wrong configurations are provided 

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2519]
Need a meaningful error message when wrong configurations are provided when email as username is enabled. You need to say to which field you need to enter the correct email address. HTML tags should be removed

![16](https://user-images.githubusercontent.com/1845370/36419961-77455620-1659-11e8-8aea-e2f5a5e0c36d.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
