### ISSUE TITLE
Migration client for Oauth2 encryption

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#2520]

**Comment by denuwanthi** [comment]
PR : https://github.com/wso2/product-is/pull/2665

**Comment by milindaperera** [comment]
Migrating rest of the persisted (in DB/Filesystem/Registry) RSA encrypted data to self-contained ciphertext

1.     BPS profile password
2.     Datasource configuration
3.     Syslog password
4.     Userstore configurations
5.     Key Store registry entries
6.     Subscriber registry entries
7.     Service security policies
8.     Event publishers configurations

Will be tracked by: https://github.com/wso2/product-is/issues/2745
