### ISSUE TITLE
No descriptions are displayed for the claims added for consent purposes

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2521]
![17](https://user-images.githubusercontent.com/1845370/36421808-ea19a916-165f-11e8-8ca3-817cdc8578f8.png)

**Comment by thanujalk** [comment]
Now the UI is updated to show the "Display Name" and "Description".

<img width="1391" alt="screen shot 2018-03-01 at 4 44 16 pm" src="https://user-images.githubusercontent.com/1498339/36841886-d781dce4-1d6f-11e8-854d-f580c3c17a12.png">
