### ISSUE TITLE
No logs when Consent purposes are added/updated/deleted

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2523]
No logs when Consent purposes are added/updated/deleted

**Comment by IsuraD** [comment]
@dilinisg Can you more elaborate this? Where should print logs? Are you talking about audit logs?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
