### ISSUE TITLE
Need the option to view the DEFAULT consent purpose

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2526]
Currently, we cannot review the claims added.
![20](https://user-images.githubusercontent.com/1845370/36423018-5339076c-1664-11e8-8ea0-e66335343705.png)

**Comment by IsuraD** [comment]
Yes. Default permission by default has all the claims/PII categories. It is like Internal/everyone role, (It is assigned to all the users by default, but it is not possible to view users of that role )

**Comment by omindu** [comment]
Added the information on DEFAULT PII category at [1]

[1] - https://docs.wso2.com/display/IS550/Managing+Consent+Purposes
