### ISSUE TITLE
UI issues in the Add new purpose page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2527]
Browser: Firefox 58.0.2 (64-bit)

**Issues**
1. The description text field should be changed to a text box
2. The bottom line of the table is not visible
3. Some element on top of the Finish button

![21](https://user-images.githubusercontent.com/1845370/36423247-245eea32-1665-11e8-8c03-45cdae2a9ddf.png)

**Comment by thusithak** [comment]
Fixed with https://github.com/wso2/carbon-consent-management/pull/70/commits/3383300b53369ebb75f53fc7cff069fc36914b3a
