### ISSUE TITLE
[Docs] [5.4.1] self-registration API documentation missing

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2533]
the API page linked from [the 5.4.1 documentation](https://docs.wso2.com/display/IS541/Self+Sign+Up+Using+REST+APIs) is missing.  It seems like it should be an updated version of [this page from 5.4.0](https://docs.wso2.com/display/IS540/apidocs/self-registration/)

**Comment by Nashaath** [comment]
The API docs for 5.5.0 as well as 5.4.1 were hosted via mail thread [1]. Therefore, self-registration API documentation [2] is now available for 5.4.1.

[1] [swagger docs] [IAM] REST API swagger docs for IS 5.5.0
[2] https://docs.wso2.com/display/IS541/apidocs/self-registration/
