### ISSUE TITLE
[Docs] [5.4.1] MultiExcerpt named 'emailTemplatePara' was not found, in 'customizing automated emails'

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2534]
the generated documentation contains an error that "emailTemplatePara" was not found on the page for [customizing automated email](https://docs.wso2.com/display/IS541/Customizing+Automated+Emails#CustomizingAutomatedEmails-Editinganemailtemplate)

**Comment by Nashaath** [comment]
Added the missing MultiExcerpt to fix the reported issue.

Fixed this in WSO2 IS doc versions 5.4.0 through 5.5.0 as well as 5.x.x.
