### ISSUE TITLE
Add facility to backup the test pack after each test.

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#2537]
This will allow the identity server pack to be backed up after tests with the test data to a given location. To enable this. Uncoment following line in automation.xml
```
<!--<parameter name="backup-test-pack" value="true"/>-->
<!--<parameter name="backup-location" value="<Absolute path for backup location with trailing foreword slash>"/>-->
```

**Comment by darshanasbg** [comment]
Fixed with: https://github.com/wso2/product-is/commit/951920231fa00ee1fa674619edded309afdfcc75
