### ISSUE TITLE
Step 7 should be more descriptive Private Key JWT Client Authentication for OIDC doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2540]
Step 7 should be more descriptive Private Key JWT Client Authentication for OIDC doc [1]

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

It says,  
Expand the OAuth/OpenID Connect Configuration and click Configure.

it should be as

Expand the OAuth/OpenID Connect Configuration under Inbound Authentication section and click Configure Configuration

**Comment by ShirazAzad** [comment]
Updated the doc [1] by making the step more descriptive.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
