### ISSUE TITLE
Step 6 should be more descriptive regarding adding the service provider in Private Key JWT Client Authentication for OIDC doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2541]
Step 6 should be more descriptive regarding adding the service provider in Private Key JWT Client Authentication for OIDC doc [1] 

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

6. Add the service provider. 

It should provide example values to add the service provider

**Comment by ShirazAzad** [comment]
Updated the doc [1]. The link to "Adding a Service Provider" is included.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
