### ISSUE TITLE
Provide a sample private_key_jwt issuer to run this sample.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2543]
Provide a sample private_key_jwt issuer  [1] to run this sample at least point to a sample location

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

Below is the description :
The JWT must contain some REQUIRED claim values and may contain some OPTIONAL claim values. For more information on the required and optional claim values needed for the JWT for private_key_jwt authentication, click here.

**Comment by ShirazAzad** [comment]
Updated the doc [1] with the link to the sample app as part of the pre-requisites.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
