### ISSUE TITLE
Any mandatory claim must be a requested claim.

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2547]
If we select some claim as mandatory,  "Requested Claim" checkbox should be changed to selected and read-only.
![git_issue](https://user-images.githubusercontent.com/20336761/36469438-3c0c4258-170d-11e8-9061-033cb5cc3858.png)

Labels:- UI

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
