### ISSUE TITLE
Provide a meaningful message when taking approval for data usage when signing in

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2552]
Provide a more meaningful message for the below when taking approval for data usage when signing in. This should include for what purpose you need these information for (without just pointing to the policies). And better it could be worded in a more polite way.

`By selecting below categories you agree to Identity Servers Terms of Services. You also agree to our Privacy Policy, which describes how we process your information, including below attributes`

**Comment by thusithak** [comment]
This has been changed as below with the Doc team's help, 
<img width="670" alt="screen shot 2018-02-23 at 10 19 13" src="https://user-images.githubusercontent.com/11048376/36578413-0e734b9e-1883-11e8-8f60-a89b06331c48.png">




Changes are already with **5.5.0-alpha2** release
https://github.com/wso2/carbon-identity-framework/pull/1368

@emswbandara shall we close this?
