### ISSUE TITLE
Missing letters in Curl command For Authz_code grant type

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2553]
Missing letters in Curl command For Authz_code grant type in this [1] doc step 14

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

curl -v POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "grant_type=authorization_code&code=f2d0f7dd-df6d-34ac-9d61-851f4f0cab9f&scope=openid&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=<jwt_assertion>&redirect_uri=http://localhost:8080/playground2/oauth2client" **https://localhost:9443/oauth2/tok**

Should be https://localhost:9443/oauth2/token

**Comment by ShirazAzad** [comment]
Updated the doc [1] by correcting the curl command.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
