### ISSUE TITLE
Better to include the DB that the new tables are introduced

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2555]
Better to include the DB that the new tables are introduced in this doc [1]

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

Current doc mentions,

A new table named IDN_OIDC_JTI has been introduced to store the JTI with the following columns.
JWT_ID VARCHAR(255)
EXP_TIME TIMESTAMP DEFAULT 0
TIME_CREATED TIMESTAMP DEFAULT 0
PRIMARY KEY (JWT_ID))

These can be seen in the script inside identity.

**Comment by ShirazAzad** [comment]
Updated the doc [1] with the database info where the table is created.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
