### ISSUE TITLE
Logic explained for the 'Lock Timeout Increment Factor' differs from the actual behaviour

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#2557]
Suppose account lock at login is configured as below.
Maximum Failed Login Attempts = 2
Account Unlock Time = 5
Lock Timeout Increment Factor = 2

Then as per the doc [1], when user enters incorrect password 2 times, his account gets locked for 5 minutes. Then after waiting for 5 minutes if user enters incorrect password again the account should be locked for 5 + 2 = 7 minutes. 
But, in the implementation account unlock time out is calculated as below.
account unlock time out = account unlock time out configured * (lock time out increment factor ^ failed login attempt cycles)

That means for above scenario where failed login attempt cycles is 1 the account unlock time out will be for 5 * (2^1) = 10 minutes.

The documentation needs to be updated accordingly.

[1] https://docs.wso2.com/display/IS530/Account+Locking+by+Failed+Login+Attempts

**Comment by omindu** [comment]
@sherenewso2 can we add this info to the docs ?

**Comment by sherenewso2** [comment]
Fixed in [1] from 5.3.0 onwards. 

[1] https://docs.wso2.com/display/IS530/Account+Locking+by+Failed+Login+Attempts
