### ISSUE TITLE
Screenshots added are blurred

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2558]
Document: https://docs.wso2.com/display/IS550/Managing+Consent+Purposes
The screenshots provided in this document are slightly blurred. Refer Add New Purpose and List PII categories screenshots. 

Type/Docs
Priority/low
Severity/minor
Affected/5.5.0-Alpha

**Comment by sherenewso2** [comment]
Fixed [1] 

[1] https://docs.wso2.com/display/IS550/Managing+Consent+Purposes
