### ISSUE TITLE
Explain or provide a reference why it needs to add a purpose

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2560]
Document: https://docs.wso2.com/display/IS550/Managing+Consent+Purposes
Explain or provide if any existing reference which describes why we need to add a purpose for consent management. 

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/Normal

**Comment by sherenewso2** [comment]
Linked off to relevant topics that explain how consent purposes are used within it's flow under the note "See the following topics for more information on how consent purposes are used:" [1]

[1]  https://docs.wso2.com/display/IS550/Managing+Consent+Purposes
