### ISSUE TITLE
Privacy Policy link in self registration page navigates to IS docs

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2562]
## Steps to re-create
1. Follow the steps in https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation document. 
2. Click on Privacy Policy link in the below page. 
![privacy](https://user-images.githubusercontent.com/31693103/36479794-ff56b83e-172f-11e8-8e5e-b58e84894c24.png)

**Expected:** Privacy note expected to be displayed. 
**Actual:** It redirects to the Identity Server Docs main page. 

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by thusithak** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1381/commits/5afff12a9f89d99601a4b1f132df62283edb8731
