### ISSUE TITLE
Cookie Policy link in self registration page navigates to IS docs

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2563]
## Steps to re-create
1. Follow the steps in https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation document. 
2. Click on Cookie Policy link in the below page. 
![cookiepolicy](https://user-images.githubusercontent.com/31693103/36479910-6fcb1b82-1730-11e8-9f2b-ae04aa5105a1.png)

**Expected:** Cookie policy expected to be displayed. 
**Actual:** It redirects to the Identity Server Docs main page. 

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by thusithak** [comment]
**Update:**
We improved the ux in self registration page for **5.5.0-alpha2** and now it looks like this.
Clicking the cookie policy link now redirects to an internal page for cookie policy, doesn't redirect to docs pages.

Also applies to #2562 

> TODO: Add cookie policy content
 

### Self registration page
<img width="751" alt="screen shot 2018-02-23 at 12 51 40" src="https://user-images.githubusercontent.com/11048376/36582670-5b42a144-1898-11e8-8e6d-941b29895b5c.png">

### Cookie policy page
<img width="1680" alt="screen shot 2018-02-23 at 12 58 30" src="https://user-images.githubusercontent.com/11048376/36582979-a45a20ea-1899-11e8-891f-3100f66264f0.png">

**Comment by thusithak** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1381/commits/6ddf1401bc256aa17e2a28e4876ba0016358208f
