### ISSUE TITLE
Document does not directly ask user to add purposes and PII. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2565]
Document: https://docs.wso2.com/display/IS550/Consent+Management+for+Self+Sign+Up
In order to display the consent, it needs to add a purpose. Otherwise [this](https://lh5.googleusercontent.com/bm30KI8rYNwzj57Y9upkA7jTQSpx8wuA0jQqzocFlpc0rs5Vl1SQJrNboxO1hR7Fv-nLHObJWKio1548mCw6TU_5bFVLdoXTJdJLccC-XDpDrVCi-OO6qQ133zu9Za0nD5ChU1e2) does not get displayed to the user. 

But as presented in the document, it does not directly ask the user to add a purpose. It just says **'The identity admin can add purposes and PII (Personal Identifiable Information) categories in the super tenant domain that define the reasons for collecting user information'**, which does not give a clear idea that adding purposes and PII is essential. Therefore In step1, say straightforwardly to add purposes and PII.

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/Normal

**Comment by sagara-gunathunga** [comment]
Above guidelines mentioned in the doc page is correct, users who sign-up through self-care portal should not be worried about adding/removing purposes, if there are purposes shown in the sing-up page they can select/deselect them, that's the only functionality related to them. It's a job for Identity Admin to add/remove purposes for the organization.
