### ISSUE TITLE
playground2 app is not working in chrome

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2566]
playground2 app is not working in chrome. It will reset to the same page as in attachment.

Environment
==========
Chrome 54 
playground v5.5.0-alpha

![screenshot from 2018-02-21 18-17-00](https://user-images.githubusercontent.com/12966170/36480795-985b3016-1733-11e8-8805-752ee59a7ea1.png)

**Comment by hasinthaindrajee** [comment]
Can you please check this with proper host names ? This should be an issue due to not allowing naked hostnames by browsers (localhost)

**Comment by darshanasbg** [comment]
Setup the sample as described in the following doc.

https://docs.wso2.com/display/IS550/Setting+Up+the+Sample+Webapp
