### ISSUE TITLE
Private Key JWT Client Authentication for OIDC sample doc does not explain how to get the Authorization code

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2569]
Private Key JWT Client Authentication for OIDC sample doc [1] does not explain how to get the Authorization code which should be given in the curl command.

From where should I get it? Is it from the playground app? If so please provide steps on how to access playground app and get the token in the doc.

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

curl -v POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "grant_type=authorization_code&code=f2d0f7dd-df6d-34ac-9d61-851f4f0cab9f&scope=openid&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=<jwt_assertion>&redirect_uri=http://localhost:8080/playground2/oauth2client" https://localhost:9443/oauth2/token

**Comment by ShirazAzad** [comment]
Added a note in [1] on where to get the Authorization code from:
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
