### ISSUE TITLE
400 Bad request is thrown for the request for Authz_code grant type

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2570]
400 Bad request is thrown for the request for Authz_code grant type as per the command mentioned in doc [1]. 

- authorization_code is taken from the playground app
- client_assertion= <JWT_assertion> is taken from the base64encoded(client id:secret) taken from SP created as explained in the step 8

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

`curl -k -v POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "grant_type=authorization_code&code= 0e5ea05d-0b0d-35d6-b181-b0f9b32b9850&scope=openid&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=UTlBVmVmUDB3VFg3b2ZDaTE5NUxNM2ZJbWdnYTppZWpYdUNYUjNSclBqaE1ueEx4UUZJTjRNd2Nh&redirect_uri=http://localhost:8090/playground2/oauth2client" https://localhost:9443/oauth2/token
* Rebuilt URL to: POST/
* Could not resolve host: POST
* Closing connection 0
curl: (6) Could not resolve host: POST
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#1)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=localhost,O=WSO2,L=Mountain View,ST=CA,C=US
* 	start date: Jul 19 06:52:51 2017 GMT
* 	expire date: Jul 17 06:52:51 2027 GMT
* 	common name: localhost
* 	issuer: CN=localhost,O=WSO2,L=Mountain View,ST=CA,C=US
> POST /oauth2/token HTTP/1.1
> Host: localhost:9443
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/x-www-form-urlencoded;charset=UTF-8
> Content-Length: 326
> 
* upload completely sent off: 326 out of 326 bytes
< HTTP/1.1 400 Bad Request
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Wed, 21 Feb 2018 13:02:21 GMT
< Content-Type: application/json
< Content-Length: 78
< Connection: close
< Server: WSO2 Carbon Server
< 
* Closing connection 1
{"error_description":"Error while parsing the JWT.","error":"invalid_request"}`

**Comment by hasinthaindrajee** [comment]
The given assertion is not a valid assertion. Assertion should be a valid signed jwt assertion. If you observe the given error message it describes that there is an "Error while parsing the JWT."
