### ISSUE TITLE
REG_PORPERTY table growth at each getPolicy() method invocation

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#2571]
**Description**
When calling getPolicy() method with isPDPPolicy status "false" we perform registry.put operation on each status change hence the status information in REG_PROPERTY table continues to grow, which is a performance issue. 

Product Version - IS 5.1.0

**Steps to reproduce the issue**
1. Create an XACML policy
2. Call getPolicy() method with isPDPPolicy = "False" attribute. [1]

[1] https://docs.wso2.com/display/IS530/Entitlement+with+APIs#EntitlementwithAPIs-getPolicy()

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
