### ISSUE TITLE
Explain further the concept behind revoking the consent

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2573]
Document: https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-RevokingConsentsapprovedforServices
Please explain the following. 

- What happens when a particular consent gets expired. 
- What happens to the details gathered from the user when consent is not valid anymore?

Type/Docs
Affected/5.5.0-Alpha
Severity/Minor
Priority/Normal

**Comment by sherenewso2** [comment]
Added these details within the explanation of the last bullet point in [1]

[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Configuringconsentforservices
