### ISSUE TITLE
Provide a meaningful error message in self signup when the username format is invalid.

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2577]
## Steps to re-create
1. Enable email as username. 
2. Follow the steps in [this](https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation) document. 
3. Login to Dashboard - https://localhost:9443/dashboard
4. Click on 'Register Now' link. 
5. Provide the following information. 
![emailasuser](https://user-images.githubusercontent.com/31693103/36516278-42a3b826-17a3-11e8-8a1d-8581f6750793.png)
6. Click on Register button. 

**Expected:** Since email as username is enabled, the user should not be created, but a meaningful error message should be provided. 
**Actual:** The user is not created, and the error message is not descriptive. 
![screenshot-localhost-9443-2018 02 22-07-39-20](https://user-images.githubusercontent.com/31693103/36516360-92f3b27c-17a3-11e8-8cc7-b3d7ed4b516f.png)

Type/Improvement
Priority/Normal
Affected/5.5.0-Alpha

**Comment by ayshsandu** [comment]
Fixed with,
- https://github.com/wso2-extensions/identity-governance/pull/216
- https://github.com/wso2/carbon-identity-framework/pull/1427
