### ISSUE TITLE
Text is not aligned in Re-send link in self sign up

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2579]
Document: https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Tryoutselfsignup

Once a user gets self-signed up to access the dashboard, it gets the following screen if the email is not yet verified and the user tries to log in with the registered credentials. 
![resendlink](https://user-images.githubusercontent.com/31693103/36519175-118ab8a4-17b0-11e8-92af-76a8a96b2259.png)

The Resent link is not properly aligned and is half broken the text. 
Tested Browsers: 
- Google Chrome Version 64.0.3282.167 (Official Build) (64-bit) - macOS
- Firefox Version 57.0.4.(64bit) - macOS

Type/Improvement 
Affected/5.5.0-Alpha
Priority/Normal
Severity/Minor

**Comment by hasinthaindrajee** [comment]
This is broken into two parts since your browser is zoomed. If you reduce zooming you will see this as a single text. However there is a problem with alignment of this text in 5.5.0-alpha3 even though it's not observable in attached screenshot
