### ISSUE TITLE
Customizing Automated Emails link redirects to an older version of document. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2580]
Document: https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Tryoutselfsignup
Section: Want to resend the confirmation email?
Inside Tip 
Customizing Automated Emails link redirects to an older version of the IS docs. 

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by sherenewso2** [comment]
Fixed links in 5.4.0, 5.4.1, 5.x.x and 5.5.0 doc spaces[1] 

[1] https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation
