### ISSUE TITLE
Configuration for NameIDPolicy and  AuthnContextClassRef of the authentication request from travelocity

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#2583]
NameIDPolicy and  AuthnContextClassRef of the authentication request from travelocity should be able to configurable. Currently it's hard coded in [1].

[1] https://github.com/wso2-extensions/identity-agent-sso/blob/master/components/org.wso2.carbon.identity.sso.agent/src/main/java/org/wso2/carbon/identity/sso/agent/saml/SAML2SSOManager.java#L598-L617

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
