### ISSUE TITLE
Account unlocking - Self signup users

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2590]
Document: https://docs.wso2.com/display/IS550/Account+Locking+by+Failed+Login+Attempts
Step 6
Section: Configuring WSO2 IS for automatic account unlock

It says if **'Authentication.Policy.Account.Lock.Time'** in <IS_HOME>/repository/conf/identity/identity-mgt.properties file is set to 0, the account needs to be unlocked by an admin user through Management Console. 

But after locking time expires user can log into the account with correct credentials. Admin user does not need to unlock it. If this information is not relevant for a self-signed up user, please mention it in the document. 

Mail thread: Clarification on user account unlock - self signup users

Related docs: 
[1]- https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Tryoutselfsignup
[2] - https://docs.wso2.com/display/IS550/Account+Locking+by+Failed+Login+Attempts
[3] - https://docs.wso2.com/display/IS550/Locking+a+Specific+User+Account

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by hasinthaindrajee** [comment]
This configuration has to be done through Admin console since this is new identity mgt features . However documentation needs to be improved.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
