### ISSUE TITLE
Invalid screenshot in the doc - user account lock

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2591]
Document: https://docs.wso2.com/display/IS550/Locking+a+Specific+User+Account
Section: Using the management console
Step 6 - screenshot

It should be corrected as below. 
![aaaa](https://user-images.githubusercontent.com/31693103/36529869-9e8c6070-17df-11e8-98ac-5f252ee7b079.png)

Type/Docs
Affected/5.5.0-Alpha
Priority/High
Severity/minor

**Comment by hasinthaindrajee** [comment]
I think this not a bug. We don't have the ability to figure out whether this is a boolean value or not when there is no value for this particular field. This is a limitation we do have. Hence for the first time it will show a text box. If we update does with this image it gives a wrong impression to a person who is initially filling this.
