### ISSUE TITLE
Self sign up/ account unlock - provide the missing information in the doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2599]
Document: https://docs.wso2.com/display/IS550/Account+Locking+by+Failed+Login+Attempts

Specify the following scenario in the doc. 
1. Navigate to the dashboard and self-signup a user. 
2. verify if the user is added to user list in the management console. Follow the configs in doc [1].
3. Now try 5 invalid login attempts. The account will get locked for 5 minutes. 

But after 5 minutes account does not automatically gets unlocked. The user has to log in with the correct credentials and then it will be get unlocked. The account lock checkbox in the user profile gets unticked/false after user logins. Better if we can mention this in the doc. 

[1] - https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Tryoutselfsignup

Type/Improvement
Affected/5.5.0-Alpha
Severity/Minor
Priority/Normal

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
