### ISSUE TITLE
No information about managing U2F Authentication in Dashboard

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2600]
Document: https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Editingyourprofile
There is no information available about U2F authentication in the doc under the topic of profile accessing. If there is any, please provide the reference. 

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by sherenewso2** [comment]
Added a tip to [1] with a reference for more info on U2F. 

[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Editingyourprofile
