### ISSUE TITLE
Dashboard/Profile Information - Department cannot be edited. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2601]
## Steps to re-create
1. Navigate to dashboard and self-signup a user. 
2. Login to the user account with created user credentials. 
3. Click on View Details button on My Profile section. 

The department field is uneditable. 
![dept](https://user-images.githubusercontent.com/31693103/36535361-5c7b920e-17ef-11e8-9cc0-48913970a350.png)

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by hasinthaindrajee** [comment]
This is because this particular claims is readOnly. You can change this by logging into admin console. However we can make it read write after considering whether there are any effects from this.

**Comment by hasinthaindrajee** [comment]
There seems to be a migration overhead of this. Considering the fact that we can make this readwrite through admin console we thought of not changing this.
