### ISSUE TITLE
Why user is given the option to lock his own account?

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2604]
## Steps to re-create
1. Self-signup a user following configs in doc[1]. 
2. Login into the dashboard - https://localhost:9443/dashboard with the created user credentials. 
3. Click on My Profile and View Details. 
4. Make the Account Locked - true
5. Update and save the information. 
6. Logout from the dashboard. 

Now, this account is locked and only admin user can unlock the account. Why are we giving this option to user? In the doc[2], this is not mentioned in the provided screenshot. Therefore marking it as a bug. If it is not, please provide reasons in the doc why we need this. 

![acclocked](https://user-images.githubusercontent.com/31693103/36536659-cb4a2764-17f3-11e8-81a6-3c69c4310255.png)

[1] - https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation#SelfSignUpandAccountConfirmation-Tryoutselfsignup
[2] - https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Editingyourprofile

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by hasinthaindrajee** [comment]
@isuruuy429 This is not available OOTB as per alpha3 pack. I think you may have made this particular claim a supported by default claim through Admin console. Can you please confirm ?
