### ISSUE TITLE
No information is downloaded when trying to download user info from the dashboard. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2605]
It only downloads a null document. 
![userinfo](https://user-images.githubusercontent.com/31693103/36537541-7d21fa78-17f6-11e8-9316-e973828f1fdc.png)

Type/Bug
Severity/Major
Priority/High
Affected/5.5.0-Alpha

**Comment by vihanga-liyanage** [comment]
I tried following approaches to reproduce the issue.
- Logging to the dashboard via admin account.
- Creating a tenant and logging into the dashboard.
-- Said issue reproduced but there is an already closed issue for that [here](https://github.com/wso2/product-is/issues/2494)
- Enabled email usernames, created a new user and logged in to the dashboard.

I didn't face this issue. Can you please give specific steps to reproduce this?
