### ISSUE TITLE
Correct the cURL command in the document. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2607]
Document: https://docs.wso2.com/display/IS550/apidocs/User-export-apis/#!/operations#UserExport#getMe

Sample CURL should be as below. 
```
curl -k -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -X GET "https://localhost:9443/api/identity/user/v1.0/me"
```

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by sherenewso2** [comment]
@madurangasiriwardena please advise on whether it is okay to give the curl command in docs with -k as adding '-k' turns off certificate verification?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
