### ISSUE TITLE
When URL is incorrect in curl command, instead of 400 it is getting 302

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2612]
Document: https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/#!/operations#Purpose#consentsPurposesGet

## Steps to re-create
1. Execute the following cURL command in which my url is incorrect. Please note that my admin is admin@wso2.com
```
curl -k -v -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type:application/json" -X GET "https://localhost:9443/api/identity/consent-gt/v1.0/consents/purposes?limit=10&offset=0"
```

Expected: 400
Actual: 302

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by hasinthaindrajee** [comment]
400 status is a bad request. However this our default behaviour of carbon products. When the endpoint is not reachable for carbon products it will send a 302 redirection with admin console page.
