### ISSUE TITLE
Users who do not have permission for consent management, can view the purposes through REST API. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2613]
## Steps to re-create
1. Login to Management Console as an admin user and create a user who only has login permission. 

> username: user1@wso2.com
> password: Test123

2. Create 3 purposes as Marketing/ Sales and Stat. 
3. Get the base64 value of (user1@wso2.com:Test123)
4. Execute the following curl command. 
```
curl -k -v -H "Authorization: Basic base64encodedvalue" -H "Content-Type:application/json" -X GET "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/purposes?limit=10&offset=0"
```

**Expected:** 401
**Actual**: 200 
Purposes get listed. 

Type/Bug
Affected/5.5.0-Alpha
Severity/Critical
Priority/High

**Comment by hasinthaindrajee** [comment]
Listing purposes is not a privileged operation. Users or application which can authenticate can view purposes. We need these information to be available without authorization for certain purposes. Ex- showing purposes on self registration page.
