### ISSUE TITLE
Users who do not have permission for consent management, can delete the purposes through REST API.

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2617]
## Steps to re-create
1. Login to Management Console and create 3 purposes as Marketing/ Sales and Stat. 
2. Create a role which has only has login permission and assign a user to it. 
> username: user1@wso2.com
> password: Test123
3. List the purposes list and get a purpose ID. (Assume purpose ID=3)
4. Get the base64 value of (user1@wso2.com:Test123)
5. Execute the following curl command. 
```
curl -k -v -H "Authorization: Basic base64encodedvalue" -H "Content-Type:application/json" -X DELETE "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/purposes/3
```

**Expected:** 401
**Actual**: 200 

Purpose gets deleted using encoded user credentials which only has login permission. 

Type/Bug
Affected/5.5.0-Alpha
Severity/Critical
Priority/High

**Comment by hasinthaindrajee** [comment]
This is fixed with https://github.com/wso2/carbon-identity-framework/pull/1389/files
