### ISSUE TITLE
How to add PII category from Management Console?

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2618]
In order to add a PII category from REST API found this doc. 
https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html#!/operations#PIICategory#consentsPiiCategoriesPost

No doc could be found to add a PII category from Management Console and Admin Services. Please do needful. 

Type/Docs
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by ruwanta** [comment]
There are no Admin Services for all new REST APIs defined. We do not develop any SOAP services.
Consent Management is only available in API. Reason, consent management is done by customers specific Web apps. 
We can add this to docs.

**Comment by hasinthaindrajee** [comment]
Adding PIICategory means adding a claim under a purpose. Hence this is supported. Anyway the above comment from @ruwanta is valid since we do provide a comprehensive REST API
