### ISSUE TITLE
How to delete PII category from Management Console?

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2619]
No method found to delete PII category from Management Console. If we want to delete the P2, the purpose needs to be deleted. 

![p2](https://user-images.githubusercontent.com/31693103/36552451-ef35442a-181f-11e8-9ac9-fa65f6d3b455.png)

Type/Bug
Affected/5.5.0
Severity/Major
Priority/High

**Comment by omindu** [comment]
This will not be supported as there's no update operation for Purposes.
