### ISSUE TITLE
Cannot delete PII category from REST API

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2620]
## Steps to re-create
1. Login to Management console and create a purpose with 2 PII categories. 
2. Retrieve PII category IDs through REST API. 
3. In order to delete the PII category, execute the following command. Assume PII category Id is 9. 
```
curl -k -v -H "Authorization: Basic base64encodedval" -H "Content-Type:application/json" -X DELETE "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/pii-categories/9"
```

**Expected:** 200 OK and PII category is deleted.
**Actual:** HTTP/1.1 400 Bad Request
{"code":"CM_00082","message":"Bad Request","description":"PII Category Id: 9 is associated with one or more purpose(s) or service(s)."}

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by omindu** [comment]
This is the expected behavior as the system doesn't allow to remove PII categories if they are associated with a receipt.

**Comment by isuruuy429** [comment]
Hi @omindu 
I got your point. Is this content invalid?
https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html#!/operations#PIICategory#consentsPiiCategoriesPiiCategoryIdDelete

**Comment by omindu** [comment]
@sherenewso2 FYI

**Comment by sherenewso2** [comment]
Added a note at the end of this document [1] 

[1] https://docs.wso2.com/display/IS550/Managing+Consent+Purposes
