### ISSUE TITLE
Monitor Users Login Sessions - dashboard gadget does not display any data

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2622]
## Steps to re-create
1. Log in to the dashboard with super admin credentials. 
2. Click on 'Monitor Users Login Sessions'. 

**Expected:** Login information to be displayed for each user. 
**Actual:** No data is displayed. 

Type/Bug
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by omindu** [comment]
Need to configure analytics to work with this feature https://docs.wso2.com/display/IS550/Terminating+User+Sessions
