### ISSUE TITLE
[Docs][5.4.0] self-registration swagger documentation does not list 'properties' body argument

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2624]
[the documentation here](https://docs.wso2.com/display/IS540/apidocs/self-registration/#!/operations#SelfRegister#resendCodePost) does not include the 'properties' body argument in the table of Parameters for any of the endpoints.

**Comment by darshanasbg** [comment]
@IsuraD Can you have a look on this please?

**Comment by IsuraD** [comment]
@sherenewso2 
We better to descriptions are default values for each attribute. Can you work on that?

The properties body parameter in register user request is documented [1]. We need to improve the doc.

 
[1] https://docs.wso2.com/display/IS540/apidocs/self-registration/#!/models#SelfUserRegistrationRequest

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
