### ISSUE TITLE
[Docs/Question][5.4.1] askPassword expiry behavior / resending

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#2625]
I was unable to find in the documentation what happens when the ['Ask Password'](https://docs.wso2.com/display/IS541/Creating+Users+Using+the+Ask+Password+Option) email's token expires, or a way to resend the email if the user cannot find it (or their email address needs to be corrected) - is there a way to do so, preferably via SCIM?

**Comment by hauntingEcho** [comment]
It looks like the current behavior is to throw an error in the UI (as of 5.6.0 WUM update 1552832456043), which is causing some confusion for our users.  An alternative workflow could be to display the error and give the user the option of resending the onboarding email (or resetting the password for the user they were trying to onboard with the normal reset-password email)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
