### ISSUE TITLE
There is no error is logged in backend when consent purpose gets failed to delete. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2626]
## Steps to re-create
1. Create a consent purpose and associate it with a consent receipt. 
2. Obtain the consent purpose ID. 
3. Delete the consent purpose by executing the following curl command. 
(In the following command purpose ID =7)
```
curl -k -v -H "Authorization: Basic base64(username:password)" -H "Content-Type:application/json" -X DELETE "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/purposes/7"
```

**Expected:** A meaning full error log expected to be printed in the backend. 
**Actual:** Getting the response for the REST API. But no error message is printed in the carbon log.

When the same procedure is done through the Management Console, user is not aware of the error which is getting since no errors in the carbon, and the UI error message is too as below. 
![deletepurpose](https://user-images.githubusercontent.com/31693103/36581496-448e74aa-1893-11e8-9ec1-8339e632516e.png)

Type/Improvement
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by darshanasbg** [comment]
As mentioned https://github.com/wso2/product-is/issues/2351#issuecomment-369546148, we do not print error logs for same reason..
