### ISSUE TITLE
No log is printed when a PII category is added

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2627]
Document: https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html#!/operations#PIICategory#consentsPiiCategoriesPost

## Steps to re-create
1. Execute the following curl command in order to add a PII Category. 
curl -k -v -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type:application/json" -X POST -d "{ \"piiCategory\": \"email\", \"description\": \"user email\", \"sensitive\": false}" "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/pii-categories"

2. Verify the carbon log/audit log. 

Expected: Above activity is expected to be logged. 
Actual: PII Category is added but no log is printed in carbon. 

Type/Improvement
Affected/5.5.0-Alpha
Severity/Major
Priority/High

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
