### ISSUE TITLE
There is no document to disable grant types

### ISSUE THREAD

**Issue by ruks** [wso2/product-is#2632]
We can edit the identity.xml file to disable mentioned grants in <SupportedGrantTypes> section. But to disable implicit grant we have to remove SupportedResponseType which ResponseTypeName is “token”.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
