### ISSUE TITLE
IS Dashboard should not display "Register Now" link if self registration is not enabled

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2646]
![image](https://user-images.githubusercontent.com/739892/36659957-4535422e-1afc-11e8-9644-579516e7b14d.png)

**Comment by hasinthaindrajee** [comment]
At this point we don't have a clue under which tenant domain user is going to register. Hence we can't disable it.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
