### ISSUE TITLE
"Cancel" button is not properly rendered in "My Profile"

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2648]
![image](https://user-images.githubusercontent.com/739892/36660733-3471c5d6-1aff-11e8-98c6-18dcdd4dad82.png)

**Comment by sagara-gunathunga** [comment]
Following pages effected with this issue. 

1. My Profile
2. Account Recovery
3. Change Password


Following pages don't have cancel button (Consistency issue)
1. Authorized Apps 
2. My Login Sessions
3. Consent Management 
4. Associated Accounts

**Comment by thusithak** [comment]
#2738 Only addresses cancel button styling defect.
TODO: Cancel button placement for consistency throughout user dashboard

**Comment by emswbandara** [comment]
It is not required to have cancel buttons in following pages.

    Authorized Apps
    My Login Sessions
    Consent Management
    Associated Accounts
