### ISSUE TITLE
No tooltips for any of the buttons in the Dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2657]
The following were noted in the Consent Management UI
![36](https://user-images.githubusercontent.com/1845370/36667421-c73f2d68-1b13-11e8-852b-c8d47885d970.png)

![37](https://user-images.githubusercontent.com/1845370/36667448-e2d37c14-1b13-11e8-931d-1aab267d2387.png)

**Comment by thusithak** [comment]
Fixed areas now looks like this.
<img width="443" alt="screen shot 2018-03-02 at 14 44 39" src="https://user-images.githubusercontent.com/11048376/36892297-551bd280-1e2a-11e8-9084-15ba1e6b3db5.png">
<img width="284" alt="screen shot 2018-03-02 at 14 44 56" src="https://user-images.githubusercontent.com/11048376/36892299-5559fae2-1e2a-11e8-916d-0f7d0dcfc8b0.png">
<img width="281" alt="screen shot 2018-03-02 at 14 45 04" src="https://user-images.githubusercontent.com/11048376/36892300-5594a886-1e2a-11e8-8173-5a568d3ecc59.png">
