### ISSUE TITLE
Travelocity does not appear under Authorized Applications in the dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2658]
Travelocity does not appear under Authorized Applications in the dashboard for Admin user and other users in the super admin domain

"No authorized applications found !" message will be displayed

**Comment by hasinthaindrajee** [comment]
Authorized apps are OAuth2 authorized applications. Hence travelocity will not be displayed under authorized applications. This is different from usual consent.

**Comment by dilinisg** [comment]
But, the below doc shows travelocity app under authorized applications. Please correct the document if it is wrong.

https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Workingwithyourauthorizedapplications

**Comment by hasinthaindrajee** [comment]
Travelocity is just a name of an application. You can register playground application by giving the name as travelocity. I think this is what has happened here. I would say it's better to remove it since people get confused as this case. @sherenewso2

**Comment by sherenewso2** [comment]
Removed the screenshot showing Travelocity from [1]
[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard
