### ISSUE TITLE
Issues in SCIM / Me Endpoint user update (PUT)

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-is#2662]
**Steps to reproduce**

1. Follow the documentation[1] and update the user using SCIM / Me Endpoint.

2. The below error appears.

``
{"Errors":[{"description":"No user exists with the given id: me","code":"404"}]}
``

[1] https://docs.wso2.com/display/IS530/SCIM+1.1+APIs

**Comment by emswbandara** [comment]
Duplicates https://github.com/wso2/product-is/issues/2641
