### ISSUE TITLE
Newly added claims are not displayed in the dashboard under Consent Mgt

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2664]
**Steps**
1. Modify and add new claims in the travelocity app
2. Check Consent Mgt in the dashboard

**Issue**
The newly added claims will not be displayed unless they are mandatory claims

**Comment by hasinthaindrajee** [comment]
Can you please elaborate more on this issue ? By just adding a claim to SP configuration doesn't affect any of the consents.

**Comment by ayshsandu** [comment]
This may related to https://github.com/wso2/product-is/issues/2661.
When requested claims are modified in the SP configurations, it doesn't imply user gives his consent to use newly added attributes. And it doesn't make changes to the users consent reciept which is build on already consented attributes. Hence, no change is reflected in the dashboard.
