### ISSUE TITLE
All the curl commands provided in Consent Management RESTfulAPI are missing the authorization header

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2671]
All the curl commands provided in Consent Management RESTfulAPI are missing the authorization header

https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html

ex: 
**Given**
`curl -k -X POST "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/purpose-categories" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"purposeCategory\": \"Marketing\", \"description\": \"For marketing related activities\"}"`

**Expected**
`curl -v -k -X POST "https://localhost:9443/api/identity/consent-mgt/v1.0/consents/purpose-categories" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"purposeCategory\": \"Marketing\", \"description\": \"For marketing related activities\"}"`

**Comment by sherenewso2** [comment]
Fixed the docs. The doc changes will be reflected when digital operations re-hosts it. 
@rumeshbandara please re-host the doc.
