### ISSUE TITLE
Request of add consent is wrong

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2674]
Request of add consent is incorrectly documented in the below doc. It not consistent with other requests.

https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html#!/operations#Consent#consentsPost

```
Request
POST https://localhost:9443/api/identity/consent-mgt/v1.0/consents
```

**Comment by sherenewso2** [comment]
Fixed the docs. The doc changes will be reflected when digital operations re-hosts it. 
@rumeshbandara please re-host the doc.
