### ISSUE TITLE
Not allowing to add Roles for CarbonRemoteUserStoreManger

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#2675]
Added user store as CarbonRemoteUserStoreManger. It shows Roles/Users and it is allowing to add users to remote Identity Server instance, But user store domain not listing when we trying to add roles.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
