### ISSUE TITLE
Need a working sample to add a consent via rest api

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2677]
Tried the sample request suggested in the below doc modifying the values. Got a 500 error. Please provide a working sample for a sample app like travelocity.

https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/index.html#!/operations#Consent#consentsPost

The request used:
`curl -k -X POST "https://localhost:9443/api/identity/consent-mgt/v1.0/consents" -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"piiPrincipalId\": \"test\", \"services\": [ { \"service\": \"travelocity.com\", \"tenantDomain\": \"carbon.super\", \"purposes\": [ { \"purposeId\": 1, \"purposeCategoryId\": [ 1 ], \"consentType\": \"EXPLICIT\", \"piiCategory\": [ { \"piiCategoryId\": 1, \"validity\": \"days:30\" }, { \"piiCategoryId\": 2, \"validity\": \"days:30\" } ], \"primaryPurpose\": true, \"termination\": \"days:30\", \"thirdPartyDisclosure\": false, \"thirdPartyName\": \"\" } ] } ], \"collectionMethod\": \"Sign-Up\", \"jurisdiction\": \"CA\", \"language\": \"EN\", \"policyURL\": \"https://foo.com/privacy\", \"properties\": [ { \"key\": \"k1\", \"value\": \"v1\" } ]}"`

**Comment by ruwanta** [comment]
Providing a UI is not within the scope of this release.

However need to investigate why 500 is returned.

**Comment by hasinthaindrajee** [comment]
@dilinisg : Did you add all related purposes and piiCategories before hand ?

**Comment by hasinthaindrajee** [comment]
@dilinisg : Having default one and other two purposes wouldn't be enough. The IDs which are returned while creating those purposes and categories should be recorded and send out properly in the above request. Can you confirm that you send out correct IDs ? IDs does not need to be continuous values.

**Comment by dilinisg** [comment]
@hasinthaindrajee : yes I changed the purpose id to a valid one below.
`"purposes\": [ { \"purposeId\": 1, `
Hope changing only the purposeId would be enough. 
I don't know the category id's. So, I kept the values as it is. Note I have two categories in each purpose. So, I added 1 and 2 as pii category id's.

**Comment by hasinthaindrajee** [comment]
piiPrincipalId is not there in the API as an input. It will be inferred from authenticated user. We need to fix docs. @sherenewso2

**Comment by sherenewso2** [comment]
Fixed the docs. The doc changes will be reflected when digital operations re-hosts it. 
@rumeshbandara please re-host the doc.
