### ISSUE TITLE
Add essential claims handling to OIDC claim filtering logic when building the id_token

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2680]
We have done the same for user info response logic,
https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/AbstractUserInfoResponseBuilder.java#L78

Need to do the same when id_token building.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
