### ISSUE TITLE
Step 2 in Removing References to Deleted User Identities doc is not clear

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2684]
Step 2 in Removing References to Deleted User Identities doc [1] is not clear

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities

It says,
The location path is the value given after -d within the following line. Modify the value after -d to change the location. 
The default location path is $CARBON_HOME/repository/components/tools/forget-me/conf. 
what is the location we should provide in the command

Please mention to which location should we change? Does it identify $CARBON_HOME or do we have to provide absolute path? It is not clear in the documentation

**Comment by sherenewso2** [comment]
Updated step 2 in [1]. This is an optional step. The user may want to do this if they have a multi-product environment where they want to manage all the configs in a single location for ease of use. Reflected this in the doc [1]. Hope it is clearer now. 

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingthedefaultconfigurationslocation
