### ISSUE TITLE
forget-me.bat path is wrong in the forget-me.bat script

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2686]
forget-me.bat path is wrong in the forget-me.bat script in wso2is-5.5.0-alpha2/bin folder
Script says,

call %CARBON_HOME%\repository\components\tools\forget-me.bat

it should be, 

repository\components\tools\forget-me\bin\forget-me.bat

**Comment by JKAUSHALYA** [comment]
Fixed in https://github.com/wso2/identity-anonymization-tool/pull/47
