### ISSUE TITLE
The location of the error is confusing in self registration

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2688]
The error is displayed below the "Enter your username here" label which is confusing. Ideally the errors should be displayed at the top

![38](https://user-images.githubusercontent.com/1845370/36728456-d2379b46-1be6-11e8-8d3b-877bc968879c.png)

**Comment by hasinthaindrajee** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1403
