### ISSUE TITLE
Cannot disable consent management for SSO

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2689]
**Steps**
1. Followed the section "Disabling consent management for SSO" in the doc below and added the event listener configuration in the identity.xml file. 
https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On
2. Try to log into the travelocity app (with mandatory claims)

**Issue**
The consent was asked when logging in.

**Comment by emswbandara** [comment]
Duplicates https://github.com/wso2/product-is/issues/2724
