### ISSUE TITLE
Revisit OpenIDConnectClaimFilter extension point

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2697]
Need to refine the methods in https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/OpenIDConnectClaimFilter.java

At the moment it seems that context information passed into the methods isn't sufficient prompting method additions to the interface everytime a new claim filtering requirement comes up.

Also, need to revisit when to use this extension point.

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
