### ISSUE TITLE
Integrating consent management for OAuth/OIDC code and implicit flows

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2701]

**Comment by omindu** [comment]
Depends on: https://github.com/wso2/product-is/issues/2702

**Comment by mefarazath** [comment]
PRs:

- Changes to OAuth code to integrate consent management for sharing claims
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/825

- Change to OIDC consent page
https://github.com/wso2/carbon-identity-framework/pull/1399
