### ISSUE TITLE
The expiration/validity of the consent is not working properly

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2705]
**Steps**
1. Create travelocity as a SP
2. Log into travelocity app by user1
3. Give consent to all the claims
4. Login to dashboard of user1
5. Change the validity until the same day.
eg: the user gets authorized with the app on 1st and validity also ends on 1st.
6. On 2nd login to the travelocity app by user1

**Issue**
The consent will not be asked again from the user.

**Comment by omindu** [comment]
fixed with https://github.com/wso2/carbon-identity-framework/pull/1419
