### ISSUE TITLE
[Sporadic] Cannot delete a purpose even if it is not attached to a consent 

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2711]
There is a purpose which cannot be deleted. It is not attached to any consent of any user in the system. What can be the reason for this?

**Comment by hasinthaindrajee** [comment]
@dilinisg Do you have this particular setup with you ? The given information is too abstract to predict the issue

**Comment by dilinisg** [comment]
You can find the pack in [1].
[1] https://drive.google.com/file/d/1ixoU6BLhzrYHHiTcxDeUxL2lpS-ELYdI/view?usp=sharing

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
