### ISSUE TITLE
Inconsistance Information in "Basic Client Profile with Playground" page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#2713]
Type/Docs
Severity/Critical
Priority/High
Affected/5.5.0

When configuring Playground app as the service provider,Followed the steps mentioned in [1].

Under "Register the Playground application in WSO2 Identity Server" topic ,it contains callback url as https://testapp:8000/callback
Under "Try out scenario topic" it contains the callback url as http://wso2is.local:8080/playground2/oauth2client.

Please maintains one url throughout the Scenario, Then it will easy for the reader to understand.  
[1] https://docs.wso2.com/display/IS550/Basic+Client+Profile+with+Playground

**Comment by ShirazAzad** [comment]
Updated the doc [1] with a screen with proper callback URL
[1] https://docs.wso2.com/display/IS550/Basic+Client+Profile+with+Playground
