### ISSUE TITLE
It does not validate for non existing or wrong pseudonym when you run forget me tool with -pu

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2714]
It does not validate for non existing or wrong pseudonym when you run forget me tool with -pu

./forgetme.sh -U user3 -pu xsfdscdsxfds
2018-02-28 15:22:12 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-02-28 15:22:16 INFO  HikariDataSource:72 - HikariPool-1 - is starting.
2018-02-28 15:22:18 INFO  HikariDataSource:72 - HikariPool-2 - is starting.
2018-02-28 15:22:18 INFO  ForgetMeExecutionEngine:218 - Processor execution completed. Processor : log-file
2018-02-28 15:22:18 INFO  ForgetMeExecutionEngine:218 - Processor execution completed. Processor : rdbms
2018-02-28 15:22:18 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down
[ushani@127 bin]$

**Comment by JKAUSHALYA** [comment]
What do you mean by wrong or non existing pseudonym ? Pseudonym is just a random string to replace the user name. It can be any string. No validation required.

**Comment by ushanib** [comment]
My Question is, since we can provide a value as -pu shouldnt it be a value which is existing? 
In here we can provide any value as -pu. Eventhougu I provide an existing or non existing -pu it still treats as a valid case. If it is a random number that generates, what is the actual use case of providing -pu as a parameter in the below command?

./forgetme.sh -U user3 -pu xsfdscdsxfds

**Comment by JKAUSHALYA** [comment]
It is the string used to replace the user name. In the process of anonymization we do not erase records instead we replace the records with a random value. We replace all the instances of the same user name with the same random string, so later on system admins can have connected record that these actions are performed by the same user. We allow user's to enter the pseudonym as a external input under a scenario where they want specially track that record or if some error occurred in middle of the process and it stops, system admin can re run the utility with the same pseudonym so the connection for the same user records will preserve.
