### ISSUE TITLE
Document should provide the use of giving each parameters in forget me tool

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2717]
Document [1]  should provide the use of giving each parameters in forget me tool.

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities 

Doc says Following are details of all possible command line options that you can use when you run the tool. It is better if doc can say why we provide each of this parameter in terms of GDPR. 

E.g., 

pu | The pseudonym with which the user name should be replaced.

The above description does not actually say what exactly trying to do by replacing the username. it would be great to have a small description for each to explain what exactly will be achieved.

**Comment by Nashaath** [comment]
Improved the descriptions and added an example scenario in the command description to describe how and why specifying a pseudonym can be useful.
