### ISSUE TITLE
Default carbon home value given in the forget me tool doc is wrong

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2718]
Default carbon home value given in the forget me tool doc [1] is wrong
[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities

carbon | The CARBON HOME. This should be replaced with the variable $CARBON_HOME in directories configured in the main configuration file. | No | -carbon “/usr/bin/wso2is/wso2is5.4.1

Product version should be changed as 5.5.0. Reconfirm this path

**Comment by sherenewso2** [comment]
Fixed in [1] 

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities
