### ISSUE TITLE
Changing default configurations of the tool  section of the doc should be meaningful 

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2720]
Changing default configurations of the tool  section of the doc [1] should be meaningful 

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities

Document says,

All configurations related to this tool can be found inside the <IS_HOME>/repository/components/tools/forget-me/conf directory. The default configurations are set up as follows:
Read Logs: <IS_HOME>/repository/logs
Read Datsources: <IS_HOME>/repository/conf/datasources/
Default datsource name: WSO2_CARBON_DB
Log file name regex: wso2carbon.log

Please explain what sort of configurations of the tool? Does it mean the logs related to tool is generated in <IS_HOME>/repository/logs location? or is it the location where tool tries to delete information of a deleted user? Please explain the correct usage of the above mentioned information in the doc

**Comment by sherenewso2** [comment]
The tool looks for references of the deleted user from those file paths. Added the following line in the doc [1]  to make it clearer:

_"The default configurations of the tool are set up to search for references of the deleted user from the following file paths: "_

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities
