### ISSUE TITLE
Document should explain the correct use of config.json and each config set

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2721]
Document [1] should explain the correct use of config.json and each config set

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-MasterConfig

Document says,

config.json | This is the master configuration file. You can configure this file based on your requirement. For information on how to configure this file, see Configuring the master configuration file.

**_Can you please explain what sort of configurations we should do in here in terms of GDPR? 
Is it the place where we configure the locations or information to be deleted of a user?_** 

**The below content is too technical. Can we explain each of the section's usage?** 

You can configure the following in the config.json file based on your requirement:

**processors** - **Specify a list of processors that you want to enable**. The names of the processors that you can enable are pre-defined. Possible values are RDBMS and log-file. - **_Why we need to enable processors? Why do we call them processors?_** 

**directories** - Specify required directories. When you include config directories, be sure to either specify the config directories relative to the location of this file or specify the absolute path. - **_Required directories for what?  Why a user needs to include config directories?_**

**processor** - Specify the processor to be used to process instructions in a selected directory. - **_Why need to use a process to provide instructions? Why do we call it a processor? What is the difference between processor and processors in config.json?_**

**extensions** - Specify any extensions to be initialized prior to starting the processor. - **_What is an extension? Why need an extensions in here? What is the difference of each processor directories and extension?_**

**Comment by ruwanta** [comment]
This is not related to IS 5.5.0. Please move this to appropriate project.

**Comment by ushanib** [comment]
IS side, the relevant document link to this page for more information is below [1]. So ideally the relevant information should be fixed. This is not an invalid issue. This is an issue which needs more information on configuring config.json.

If the relevant page will not be fixed, Please mention the relevant information need in IS side in this page. Hence reopening this issue.


Below is the link provided in the doc.

For information on changing these configurations, see Configuring the config.json file in the Product Administration Guide. 

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

**Comment by Nashaath** [comment]
The descriptions have been improved
