### ISSUE TITLE
There is no indication for the end user on the time the user is not allowed to reattempt login when account is locked reaching maximum failed attempts for account unlock time defined

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#2722]
Suppose account lock is configured as a login policy configuring maximum failed login attempts, 
account unlock time, and account lock timeout increment factor.
With this when a user reach the maximum failed login attempts allowed, a user won't be able to attempt login again for the specified account unlock time and neither allowed to invoke recovery APIs. Then, upon the next attempt cycle if that also fails account unlock time grows exponentially.
The problem here is that, unless the user gets an indication of the time that the user is not allowed to attempt login, the end user will have no idea on what is happening and will be frustrated.

At the moment, when 'showAuthFailureReason' property is configured in the  <IS_HOME>/repository/conf/security/application-authentication.xml under 'BasicAuthenticator' configuration, WSO2 IS sends the error code indicating that the error occurred due to account is being locked and also sends the no of remaining attempts as context information. This allows customizing the login page and showing a more appropriate message with respect to the context to the end user. But still the time period in which the user will be allowed to attempt login is being missed. It is better to feed this time period to the login page as well, to indicate on when login can be attempted again to the end user.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
