### ISSUE TITLE
Change User Dashboard Screenshots to Latest in all Doc References

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#2726]
![dashboarb2](https://user-images.githubusercontent.com/5061791/36829936-5451d04a-1d47-11e8-869e-5754b0b5ca41.png)

**Comment by sherenewso2** [comment]
Seems like the screenshot is only there in page [1]. Updated it in [1].

[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard
