### ISSUE TITLE
"PROVIDE MANDATORY DETAILS" page need to show display name of the claim instead claim URI

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#2727]
<img width="678" alt="screen shot 2018-03-01 at 3 47 20 pm" src="https://user-images.githubusercontent.com/1498339/36839453-20c0d7f0-1d68-11e8-8358-e8f7d144d537.png">

- In this page, claim URI value is displayed. Its better if we show the display name of that claim.
- Also "SIGN IN" button should be changed to something like "SUBMIT"

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
