### ISSUE TITLE
Document on modifying consents given by a user for a service provider

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2728]
Related to: https://github.com/wso2/product-is/issues/2507

A user can remove consent for the attributes he/she already given consent to thought the dashboard. 

If the user wants to add a consent for an attribute he/she has not given previously, the existing consent for the service provider should be revoked first and login again. Then the user will be prompted to with all the required claims for consent.

**Comment by sherenewso2** [comment]
Documented under the "Accepting consent for new attributes" section in [1] 
[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Configuringconsentforservices
