### ISSUE TITLE
[Doc] Configuring Active Directory User Stores for Inbound Provisioning Doc Outdated

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#2729]
[Configuring Active Directory User Stores for Inbound Provisioning](https://docs.wso2.com/display/IS550/Configuring+Active+Directory+User+Stores+for+Inbound+Provisioning) document is outdated. Specially the screenshots.

Type: Bug
Priority: High
Severity: Major

**Comment by rksk** [comment]
This should include steps for SCIM2 as well.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
