### ISSUE TITLE
Mandatory claim mapping for primary userstore

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#2734]
Claim mapping for primary user store should be mandatory. We need to add a validation in UI level and in back-end service level to restrict adding claim mapping without having a claim mapping for primary userstore.

**Comment by thusithak** [comment]
Currently the UI do validate the Mapped Attribute as mandatory.
But there's an issue in making claim mapping for primary user store deletable.

Shall we remove the selection from the very first attribute mapping and make it a mandatory field and remove "Delete" for that domain name?
### Before
<img width="724" alt="before" src="https://user-images.githubusercontent.com/11048376/37082115-9b53c786-2211-11e8-8337-b13b2809644f.png">

### After
<img width="724" alt="after" src="https://user-images.githubusercontent.com/11048376/37082114-9b22cfbe-2211-11e8-98b7-dcfdae641b54.png">

WDYT?

**Comment by madurangasiriwardena** [comment]
+1

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
