### ISSUE TITLE
identity-anonymization-tool-master should be identity-anonymization-tool in the doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2739]
identity-anonymization-tool-master should be identity-anonymization-tool in the doc [1]

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-MasterConfig

2nd step under **Building the Identity Anonymization tool** section says ,
In the source that you checked out, navigate to identity-anonymization-tool-master, 

It should be In the source that you checked out, navigate to identity-anonymization-tool ...

It should be fixed wherever it is relevant

**Comment by Nashaath** [comment]
Corrected this in all applicable places.
