### ISSUE TITLE
Dont mention the specific snapshot version in the doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2740]
Dont mention the specific snapshot version in the doc [1]

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-MasterConfig

In docs it is mentioned as, 
 org.wso2.carbon.privacy.forgetme.tool-1.0.0-SNAPSHOT.zip

org.wso2.carbon.privacy.forgetme.tool-1.0.0-SNAPSHOT 

Better to mention as, 

 org.wso2.carbon.privacy.forgetme.tool-<VERSION>-SNAPSHOT.zip since it keeps on changing. 
org.wso2.carbon.privacy.forgetme.tool-<VERSION>-SNAPSHOT

**Comment by Nashaath** [comment]
Removed the version from the doc as suggested since it keeps changing.
