### ISSUE TITLE
Unzip directory name is wrong in the doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2741]
Unzip directory name is wrong in the doc.

Doc says,
Unzip the org.wso2.carbon.privacy.forgetme.tool-1.0.0-SNAPSHOT.zip file. This creates the org.wso2.carbon.privacy.forgetme.tool-1.0.0-SNAPSHOT directory with a directory  structure similar to the following:

But the actual unzipped folder created is,
identity-anonymization-tool-1.1.6-SNAPSHOT.

Mention as identity-anonymization-tool-<VERSION>-SNAPSHOT

**Comment by Nashaath** [comment]
Changed the name of the directory accordingly.
