### ISSUE TITLE
Error page link has been linked to Axis2Service custom policy in WS-Trust

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2747]
In[1] & later version of the same doc under point 4, "You can download the complete policy from **here**" pointing to a 404 error page [2]. Please correct it with the right page.

[1]https://docs.wso2.com/display/IS540/Broker+Trust+Relationships+with+WSO2+Identity+Server#BrokerTrustRelationshipswithWSO2IdentityServer-Step1-SecureWebServicewithaClaim-awareSecurityPolicy
[2] https://sourceforge.net/error-404.html

**Comment by nilasini** [comment]
The "sourceforge" was under maintenance that's why we have redirected to an error page. Currently, it came back from maintenance.

**Comment by omindu** [comment]
Better if we can move the sample to a WSO2 space to avoid this sort of situation in the future.

**Comment by nilasini** [comment]
Yes. +1 for that. Therefore reopening the issue.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
