### ISSUE TITLE
Invalid Error Status/Messaged are returned from the Consent Management API

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2748]
Description:
Moved from: https://github.com/wso2/carbon-consent-management/issues/56
Some of the API error responses contain mismatching information.

ex:

Internal server error when sent "string" instead "integer" for {purposeID} to GET /consents/purposes/{purposeID} endpoint
Bad request, when entry is not found for the provided {purposeID} to GET /consents/purposes/{purposeID} endpoint
Need to check all the other API resources for the correct error responses.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
