### ISSUE TITLE
No access for the GDPR FAQ page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2754]
![50](https://user-images.githubusercontent.com/1845370/36959290-4e06c736-2067-11e8-9251-0b37730ad786.png)

**Page**:
https://docs.wso2.com/pages/viewpage.action?pageId=85392776

**Comment by ShirazAzad** [comment]
Edited the restrictions for [1] 
[1] https://docs.wso2.com/display/IS550/GDPR+FAQ
