### ISSUE TITLE
Deploying and configuring JWT client-handler artifacts does not specify the correct location to build in step 2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2757]
**Suggested Labels**
Type/Doc
Priority/High

**Description**
Refer to link [1]. In step 2 doc specify as Navigate to component /clienthandler/ org.wso2.carbon.identity.oauth2.grant.jwt and build. There is no such a location in the code checked out as in step 1 [2]. Please update the doc specifying the correct location under step 2.

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
[2]. jwt-token.png

![jwt-token](https://user-images.githubusercontent.com/31848014/36967247-37620694-2085-11e8-897e-2c122653b887.png)

**Comment by ShirazAzad** [comment]
Updated the doc [1] with the correct location.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
