### ISSUE TITLE
Issues in the cookie policy 

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2760]
https://localhost:9443/authenticationendpoint/cookie_policy.do

1. refereed hereafter as “IS 5.5.0” - wrong spellings
2. "these can not be used to not personally identify you or your activities", "These can not be used to personally identify you." - cannot is a one word
3. MSGnnnnnnnnnn - Better to use something like xxx or <random_number> notation

@sherenewso2 - Shall we proof read the cookie policy and check all the punctuation and other mistakes? I feel we can reword some information too.

**Comment by sherenewso2** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1471
