### ISSUE TITLE
Deploying and configuring JWT client-handler artifacts SNAPSHOT.jar name specified in the doc does not match with the latest version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2765]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Alpha3

**Description**
Refer to link [1]. Step 3 under Deploying and configuring JWT client-handler artifacts does not mention the correct SNAPSHOT.jar name. According to the current repository it should be org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt-1.0.5-SNAPSHOT.jar. Please update the SNAPSHOT name to match with the latest build as in [2]

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
[2]. target.png

![target](https://user-images.githubusercontent.com/31848014/36970515-e7043622-208e-11e8-9c9e-083a6063710b.png)

**Comment by madurangasiriwardena** [comment]
Thanks you for reporting the issue.

Now you don't need to build the artifacts from source. Instead you can download the artifacts from https://store.wso2.com/store/assets/isconnector/details/3990fa78-6696-4b98-8af8-d4cc7611099a as mentioned in the documentation.
