### ISSUE TITLE
Typo errors in Adding and configuring a service provider

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2768]
**Suggested Labels**
Type/Docs
Priority/Normal
Affected/5.5.0-Alpha3

**Description**
There is a statement as "Under This topic contains the following sections" in [1] 
There remove the bullet points which does not have a content included.

[1]. https://docs.wso2.com/display/IS550/Adding+and+Configuring+a+Service+Provider

**Comment by Nashaath** [comment]
removed the unnecessary bullet points.
