### ISSUE TITLE
IS 5.0.0 to 5.4.0 Aggregated Migration client DB script changes

### ISSUE THREAD

**Issue by SaubhagyaW** [wso2/product-is#2771]
Initial issue: https://github.com/wso2/product-is/issues/2575

Following changes should be added to MySQL DB scripts.

**5.1.0 UM DB script**
1. Delete claim "http://wso2.org/claims/passwordTimestamp".

2. Add following claims.
> <Claim>
	<ClaimURI>http://wso2.org/claims/username</ClaimURI>
	<DisplayName>Username</DisplayName>
	<AttributeID>uid</AttributeID>
	<Description>Username</Description>
</Claim>

> <Claim>
	<ClaimURI>http://wso2.org/claims/identity/failedLoginAttempts</ClaimURI>
	<DisplayName>Failed Login Attempts</DisplayName>
	<AttributeID>failedLoginAttempts</AttributeID>
	<Description>Failed Login Attempts</Description>
</Claim>

> <Claim>
	<ClaimURI>http://wso2.org/claims/identity/unlockTime</ClaimURI>
	<DisplayName>Unlock Time</DisplayName>
	<AttributeID>unlockTime</AttributeID>
	<Description>Unlock Time</Description>
</Claim>

> <Claim>
	<ClaimURI>http://wso2.org/claims/displayName</ClaimURI>
	<DisplayName>Display Name</DisplayName>
	<AttributeID>displayName</AttributeID>
	<Description>Display Name</Description>
</Claim>

**5.2.0 UM DB script**
Update claim "urn:scim:schemas:core:1.0:local" to "urn:scim:schemas:core:1.0:locale".

**5.4.0 Step 1 Identity DB script**
Delete claim "urn:scim:schemas:core:1.0:roles".

**Comment by Saubhy** [comment]
These should be fixed in step by step migration client scripts as well.

**Comment by Saubhy** [comment]
Increased VARCHAR2(255) to 1023 in WS_BPS_PROFILE table in Oracle DB scripts. Please check this in MYSQL scripts.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
