### ISSUE TITLE
The screen shots should be updated in the consent management with SSO page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2775]
https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On

**New UI**
![53](https://user-images.githubusercontent.com/1845370/37014165-bdfcec38-2124-11e8-8bd5-001f05e146a3.png)

**Comment by sherenewso2** [comment]
Updated [1] 

[1] https://docs.wso2.com/display/IS550/Consent+Management+with+Single-Sign-On
