### ISSUE TITLE
Need to simplify the Consent management page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2778]
1. We have the IDP/SP name repeated twice. What is the reason?
![54](https://user-images.githubusercontent.com/1845370/37015543-e3987904-212d-11e8-8705-c3253f1109e8.png)

2. The Receipt Id:  is null in Resident IDP. Can we put N/A or something meaningful without leaving it blank?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
