### ISSUE TITLE
Provide details on how to proceed with setting up the sample web app under step 9 in Deploying and configuring JWT client-handler artifacts

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2779]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Alpha3

**Description**
Refer to document link [1]. In Step 9 under Deploying and configuring JWT client-handler artifacts please mention that you need to build the playground app and take the war file and need to deploy that in the tomcat server. Provide a linking for [2] to guide the users on how to build playground and take the war file.

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
[2]. https://docs.wso2.com/display/IS550/Setting+Up+the+Sample+Webapp

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
