### ISSUE TITLE
Explain what is referred as "private_key_jwt issuer" under Deploying and configuring JWT client-handler artifacts

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2780]
**Suggested Labels**
Type/Docs
Priority/Highest
Affected/5.5.0-Alpha3

**Description**
Refer to doc link [1]. Under step 10 in Deploying and configuring JWT client-handler artifacts explain what is referred as "private_key_jwt issuer"

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
