### ISSUE TITLE
Provide a sample url value for TokenEndPointAlias parameter in JWT client authentication

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2781]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Alpha3

**Description**
Refer to document link [1]. In step 4 under Deploying and configuring JWT client-handler artifacts please provide a example for sample url value in TokenEndPointAlias parameter. 

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
