### ISSUE TITLE
Update the included screenshot in step 11 under Private key JWT client authentication for OIDC

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2783]
**Suggested Labels**
Type/Docs
Priority/Normal
Affected/5.5.0-Alpha3

**Description**
Refer to doc link [1]. In step 11 under Deploying and configuring JWT client-handler artifacts update the given screenshot to display the specific column names as well to be more discriptive for the user.

[1].  https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
