### ISSUE TITLE
A temp log was not created when removing all occurrences of username in logs

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2789]
1. Run the forget me tool with default configurations
` sh forgetme.sh -U admin`
The logs says the tool has run successfully

**Issue**
According to the comments mentioned in [1], a "*-tmp.log" file should be created and all the occurrences of the username should be deleted. But, this temp log was not created. Therefore, the occurrences of username in logs were not deleted

[1] https://github.com/wso2/product-is/issues/2769

**Comment by dilinisg** [comment]
This was tested with default configurations where a relative path was given for the log-file-path property. Once the absolute path was given, it worked. Therefore reducing the severity. But, the default configurations should work fine

**Comment by JKAUSHALYA** [comment]
Fix with https://github.com/wso2/identity-anonymization-tool/pull/54
