### ISSUE TITLE
Update the screenshot given under running the playground application (without PKCE) to match with current version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2800]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Alpha3

**Description**
Refer to doc link [1]. In step 2 Under Running the application (without PKCE) please update the given screenshot as [2] to match with the current version.

[1]. https://docs.wso2.com/display/IS550/Try+Authorization+Code+Grant
[2]. playground-new.png

![playground-new](https://user-images.githubusercontent.com/31848014/37078756-73c717be-2206-11e8-8a91-6d6c64f2ad68.png)

**Comment by nilasini** [comment]
Duplicates
https://github.com/wso2/product-is/issues/2973
