### ISSUE TITLE
Provide a sample value for Authentication Context Class/LoA under Trying authorization code grant

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2801]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Alpha3

**Description**
Refer to doc link [1]. As per the current playground sample checked out using [2] UI will be as [3]. Therefore under Running the application (without PKCE) please provide sample values that needs to be provide for Authentication Context Class/LoA

[1]. https://docs.wso2.com/display/IS550/Try+Authorization+Code+Grant
[2]. https://docs.wso2.com/display/IS550/Downloading+a+Sample
[3]. playground-new.png

![playground-new](https://user-images.githubusercontent.com/31848014/37078836-ae9a7746-2206-11e8-81d9-96b5e2413943.png)

**Comment by ruwanta** [comment]
This does not need a value to try out only PKCE. So no sample is needed.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
