### ISSUE TITLE
Images given under step 3 Trying authorization code grant does not display the support of privacy and cookie policies

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2804]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Alpha3

**Description**
Refer to doc link [1]. Step 3 under running the application (without PKCE) contain a out dated screenshot which does not display the support of privacy policy and cookie policy. Please update it as per [2].

[1]. https://docs.wso2.com/display/IS550/Try+Authorization+Code+Grant
[2]. playground-signin.png

![playground-signin](https://user-images.githubusercontent.com/31848014/37077083-5f4a19fa-21ff-11e8-9976-89fb496c611f.png)

**Comment by nilasini** [comment]
Duplicates
https://github.com/wso2/product-is/issues/2973
