### ISSUE TITLE
AskPassword expiry time not updated with new value by identity.xml configs

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#2805]
Description:
AskPassword expiry time not updated with new value by identity.xml configs. Is given value "1440" hard coded?

Label:
Type/Query
Priority/High

Environment:
IS-5.3.0
wum updated pack (wso2is-5.3.0.1513701178179.zip)

Steps to recreate:
- Follow the steps to configure askpassword[1]
- When updating identity.xml for expiry time, update with new value
`   <AskPassword>
      <ExpiryTime>600</ExpiryTime>
   </AskPassword>
`
- Start the server
- Check mgt-console for Resident Identity Providers-> Account Management Policies -> User Onboarding tab and Check "Ask password code expiry time" field. It always updated "1440"

[1] [https://docs.wso2.com/display/IS530/Creating+Users+using+the+Ask+Password+Option]

**Comment by madurangasiriwardena** [comment]
Hi @kavithasub,

Thanks for reporting the issue. However, the value specified in the identity.xml is used only for the initial server startup and tenant creation time. After that, if you want to update the value, you have to update it from the "Resident Identity Providers" UI.
