### ISSUE TITLE
[Doc] [Improvement] Add email template location correctly in the steps

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#2806]
As $subject, it should be correct in the step.2 as Main-> Manage-> Email templates
![doc-email](https://user-images.githubusercontent.com/15671620/37078811-9f2a261c-2206-11e8-9c33-4dc8ef49f422.jpeg)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
