### ISSUE TITLE
Access Token generated under Running the application (without PKCE) can be edited by a user.

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2808]
**Suggested Labels**
Type/Improvement
Priority/Normal
Affected/5.5.0-Alpha3

**Description**
In trying Private key JWT client authentication for OIDC, followed the doc in [1] and [2] and obtained the Access Token using playground web app. The access token generated has the edit privileges for the user. Suggest to make this token Read only.

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
[2]. https://docs.wso2.com/display/IS550/Try+Authorization+Code+Grant

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
