### ISSUE TITLE
Restructure the steps adding missing details under Deploying and configuring JWT client-handler artifacts

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2810]
**Suggested Labels**
Type/Docs
Priority/Highest
Affected/5.5.0-Beta

**Description**
Refer to doc link [1]

Refer the doc link [1]. Step 11, 12 and 13 under Deploying and configuring JWT client-handler artifacts should come under the main step 10. 
11th, 12th, and 13th are subsets of 10th (Import the public key of the private_key_jwt issuer). 11, 12 , 13 explains how to perform what is mentioned in step 10. So restructure this accordingly because uses get confused on what they need to do with step 10

Also step 14 is an alternative way to install public key through keytool and **it requires a server restart**. Please mention this providing a note under step 14

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
