### ISSUE TITLE
Include the reason for doing step 11 under Deploying and configuring JWT client-handler artifacts as mentioned in the Issue description

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2811]
**Suggested Labels**
Type/Docs
Priority/Normal
Affected/5.5.0-Beta

**Description**
Refer to doc link [1]. In step 11 under Deploying and configuring JWT client-handler artifacts it is asking to rename the public key certificate file with OAuth app client ID value. There add a note and mention the reason as **this is need to be done because management console takes the file name of the public key certificate file as the alias which is clientID.**

[1]. https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
