### ISSUE TITLE
Screenshots in step 4, step6 under without PKCE and step 2, step 3, step4, step6 under with PKCE in trying authorization code grant does not match with latest version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2814]
**Suggested Labels**
Type/Docs
Priority/High
Affected/5.5.0-Beta

**Description**
Refer doc link [1]. please update the outdated images as mentioned below

Running the application (without PKCE)
Step 4 change as [2]
Step 6 change as [3]

Running the application (with PKCE) 
Step 2 change as [4]
Step 3 change as [5]
Step 4 change to match current version
Step 6 change to match current version

[1]. https://docs.wso2.com/display/IS550/Try+Authorization+Code+Grant
[2]. step4.png
[3]. step6.png
[4]. step2-withPKCE.png
[5]. playground-signin.png

![step4](https://user-images.githubusercontent.com/31848014/37086141-df26eb0e-221c-11e8-839b-18e822a74bd9.png)
![step6](https://user-images.githubusercontent.com/31848014/37086302-3ed11cc8-221d-11e8-887c-51740d792d1c.png)
![step2-withpkce](https://user-images.githubusercontent.com/31848014/37086385-70f2e056-221d-11e8-8a99-5f759c4fad79.png)
![step2-withpkce](https://user-images.githubusercontent.com/31848014/37086670-26bbce8e-221e-11e8-98aa-460f790ff52e.png)
![playground-signin](https://user-images.githubusercontent.com/31848014/37086682-3199c266-221e-11e8-9231-480a2b13c0e3.png)

**Comment by nilasini** [comment]
Duplicates
https://github.com/wso2/product-is/issues/2973
