### ISSUE TITLE
username can be seen in IDN_AUTH_SESSION_STORE eventhough the user is deleted and forgetme tool is run

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2815]
username can be seen in IDN_AUTH_SESSION_STORE eventhough the user is deleted and forgetme tool is run.

This is appended with other characters.

carbon.supert\0\n**sol18user1**t\0^GPRIMARY\0q\0~\01psq\0~\0 

carbon.supert\0\n**sol18user1**t\0^GPRIMARY\0q\0~\01psq\

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
