### ISSUE TITLE
Cannot find the path to Config.json in Windows

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2817]
Environment - Windows Server 2012 R2

Run the forget me tool changing the paths in the config.json file. But the path to config.json cannot be identified from the forgetme.bat script.

Refer the error in the screen shot
![56](https://user-images.githubusercontent.com/1845370/37093114-3bcc8b04-2234-11e8-9eaa-023bcb27ca31.png)

**Comment by JKAUSHALYA** [comment]
Fix with https://github.com/wso2/product-is/pull/2859
