### ISSUE TITLE
[Doc] Update docs for invalidation of local caches

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#2820]
Need to remove the parts about distributed cache from [1] and add a section explaining how local caches are invalidated now. 

[1] https://docs.wso2.com/display/IS550/Improving+XACML+PDP+Performance+with+Caching+Techniques

**Comment by harsha1979** [comment]
https://medium.com/@harsha.thirimanna/cache-invalidation-in-wso2-carbon-kernel-platform-31753fe879ba

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
