### ISSUE TITLE
Cannot find the Service Packs in the mentioned location in the docs

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2821]
In IS 5.0.0 doc space [1], it has mentioned the SP can be downloaded from the download page. But, the pack is not available to download in the said location

[1] https://docs.wso2.com/display/IS500/Installing+the+Service+Pack

**Comment by Nashaath** [comment]
Now since the service pack has been added to the previous download page, I have updated the doc [1] with steps on how to download WSO2 IS 5.0.0 as well as the service pack for IS 5.0.0 from the previous download page.
[1] https://docs.wso2.com/display/IS500/Installing+the+Service+Pack
