### ISSUE TITLE
How to change the default config location in windows?

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2823]
The doc [1] mentions that we can change the default location of the configurations related to forget-me. But, the .bat script is different. How can we change the default config location in windows?

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

**Comment by ruwanta** [comment]
Please elaborate.
What is the difference in .bat script ?

**Comment by dilinisg** [comment]
In the .sh file you can configure the default config location with -d option.
`sh $CARBON_HOME/repository/components/tools/forget-me/bin/forget-me -d $CARBON_HOME/repository/components/tools/forget-me/conf $@`

But, the .bat file does not have an option like that by default. It has only the below command. 
`call %CARBON_HOME%\repository\components\tools\forget-me\bin\forgetme.bat %*`

Ideally, the bat file should also have the configuration to change the config location by default. Also, it needs to be documented in the above doc too.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
