### ISSUE TITLE
Change 'Default Service Provider' and 'Resident IDP' names in user portal into somthing meaningful for endusers

### ISSUE THREAD

**Issue by sagara-gunathunga** [wso2/product-is#2825]
Change 'Default Service Provider' and 'Resident IDP' names in user portal into somthing meaningful for endusers.

![image](https://user-images.githubusercontent.com/739892/37135594-ec4e09e6-22c3-11e8-8c2c-2691a9bdd8ee.png)

**Comment by omindu** [comment]
The `Default Service Provider` was renamed to `Self Care Portal`. We can keep the `Resident IDP` under `System Consent`
