### ISSUE TITLE
Need to document the purpose of the forget-me tool in more detail

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2826]
This tool can be used,
1. when a user is deleted
2. when the user is Active and requested to anonymize his details as well. 

But, point 2 is not a valid use case. Therefore, can we specifically mention the purpose of this tool in more detail including information on what will happen if a user in Active state is anonymized etc?

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

**Comment by Nashaath** [comment]
Added a few points to keep in mind before running the tool. Added the points as a note under  the "Running the tool in WSO2 IS" section. The first point addresses the reported improvement.
