### ISSUE TITLE
Lot of TODO's in the GDPR Compliance page

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2827]
This page has lot of TODO's. Shall we fix those soon?

https://docs.wso2.com/pages/viewpage.action?pageId=85392485

**Comment by ruwanta** [comment]
This is the purpose of TODO in WIP document, so why create an issue for such things?

**Comment by dilinisg** [comment]
This issue was raised, so that the TODO's won't be missed and will be addressed soon. Since we are relying entirely on docs, having TODO's at this stage blocks us verifying the content in that page.

**Comment by ShirazAzad** [comment]
Fixed.
