### ISSUE TITLE
It would be better if all the default logs files can be deleted by running the forget me tool without any additional configurations

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2830]
It would be better if all the default logs files can be deleted by running the forget me tool without any additional configurations. This is how its done in APIM

E.g., 

We can give the  regex to delete log files as below.  

{
  "processors" : [
    "log-file",
    "rdbms"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
       "log-file-path" : "../../../../logs",
      **"log-file-name-regex" : "(.)*(log|out)"**
    },
    {
      "dir": "sql",
      "type": "rdbms",
      "processor" : "rdbms"
    }
  ],
  "extensions": [
    {
      "dir": "../../../../conf/datasources",
      "type": "datasource",
      "processor" : "rdbms",
      "properties" : [
        {
        **"identity": "WSO2AM_DB",
        "apim": "WSO2AM_DB",
        "um": "WSO2_CARBON_DB"**
        }
      ]
    }
  ]
}

**Comment by JKAUSHALYA** [comment]
By saying "deleted" I think you meant anonymize. (Tool does not delete anything)
Fixed with https://github.com/wso2/identity-anonymization-tool/pull/62
