### ISSUE TITLE
What is the use of forgetmebatch script?

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2834]
What is the use of forgetmebatch script? No information could be found in docs

**Comment by ruwanta** [comment]
Where is this "forgetmebatch" ?

**Comment by dilinisg** [comment]
Forgetmebatch script can be found in the below location
`wso2is-5.5.0-beta/repository/components/tools/forget-me/bin`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
