### ISSUE TITLE
Tokens obtained with OpenID hybrid flow has wrong expiry time

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#2836]
Although our default expiry time is set to 3600s tokens issued from hybrid flow have 299999s

Response 
`https://localhost/callback#access_token=2be441d4-e9d7-3a85-997c-b6ed6cb17ef0&code=61b226a4-11c2-3a27-a5d2-62f00d6602b5&id_token=eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiM05PTzVCTTV5VkdmWHhvTnlDNTQtUSIsImNfaGFzaCI6InpDSG9MMXZJTmNNQm81VzUtZ1I5QUEiLCJzdWIiOiJhZG1pbiIsImF1ZCI6WyJfZTNpTmtmOFZJWWhUdnRFYmY0bEdwcmZmWlVhIl0sImF6cCI6Il9lM2lOa2Y4VklZaFR2dEViZjRsR3ByZmZaVWEiLCJhbXIiOltdLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjE1MjA1MDMxOTYsIm5vbmNlIjoiMTIzMzQyMzQiLCJpYXQiOjE1MjA0OTk1OTZ9.kSf1q7B6lR5dNqeKWZVYbnoYYQFzajQzapE4mjV5Zu3oTzRopGJmtFA8knA8ZF_B9ZmBzzyS5TE46N1aWfYcBdR1olnH8I1gFWegDDSDG8VGx21nD7blob_dIg2yESu8XfO0FP-obmPTFYTT32vO-FJZBGMANEzm-av1paPaK6GNWh82G8VflIxzhfMqU5M-zaX3HMTLVJzRlqh_pRG9tvh6XOHrCVnuL16xtp9r03M0PGOvzZVJpVn76MtoOa6Idkhlz0INnryqqmdB5VD4gfYe7UZzrAO087a4hd5ghnHXZtN_ukexwXNFZvJDCsLFlhiR0gRpfuQq7Qq1a7FwHg&token_type=Bearer&expires_in=299094&session_state=414144d26df8cd69a2b5c66887838d055e0d983f758f9f0b4df62e5f0203d98b.hK42tNG_gK6Ky_hgS82DDQ`

**expires_in=299094**

Also, the expiry time seems to be in milliseconds rather than in seconds.

**Comment by bjornvildljung** [comment]
Linked to this issue, when using hybrid flows: (5.4.1 tested, expecting the same for 5.5)
Userinfo endpoint returns only "sub" claim when refreshing the ID-token from Hybrid flows.

Reproduce by:
1. Login using Hybrid flow (code id_token)
2. Exchange the code for tokens. (lifetime is now 300k seconds, as a stated above)
3. Use access_token on Userinfo endpoint. All claims are received.
4. Re-do the login (sso) to get a new code and ID-Token. (This is the application refreshing its session)
5. Exchange the code for tokens.
6. Use access_token on Userinfo endpoint. **ONLY "sub" claims is received**

The ID-Token will match the content of the Userinfo endpoint both times.
