### ISSUE TITLE
Tag name has been missed

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2841]
Please update the doc [1] first point from

Configure the TokenPersistenceProcessor as shown below in the <IS_HOME>/repository/conf/identity/identity.xml file to enable token encryption. 

to 

**Change** the TokenPersistenceProcessor as shown below in the <IS_HOME>/repository/conf/identity/identity.xml file **under <OAuth> tag** to enable token encryption.

[1] https://docs.wso2.com/display/IS530/Setting+Up+OAuth+Token+Encryption

**Comment by sherenewso2** [comment]
Updated [1] 
[1] https://docs.wso2.com/display/IS530/Setting+Up+OAuth+Token+Encryption
