### ISSUE TITLE
How to configure the config.json to point to multiple datasources/log files

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2842]
The doc does not mention how to configure the config.json to add multiple datasources and log files

https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-Configuringtheconfig.jsonfile

**Example for APIM for datasources**
Provide a sample for all the datasources (carbon, bps, metrics etc.)

```
 "extensions": [
    {
      "dir": "/home/tharika/wso2am-2.2.0-SNAPSHOT/repository/conf/datasources",
      "type": "datasource",
      "processor" : "rdbms",
      "properties" : [
        {
        "identity": "WSO2AM_DB",
        "apim": "WSO2AM_DB",
        "um": "WSO2_CARBON_DB"
        }
      ]
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
