### ISSUE TITLE
The "log-file-name-regex" should be changed to identify all the log files by default

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2843]
The following regex is configured in the config.json in the forget-me tool in APIM by default
`
 "log-file-name-regex" : "(.)*(log|out)"`

**Comment by dilinisg** [comment]
The regex should also capture the old log files as well.
eg: 
audit.log.2018-03-08
wso2carbon.log.2018-03-08

**Comment by dilinisg** [comment]
This should also capture already created temp.log file as well

**Comment by JKAUSHALYA** [comment]
Added the fix to capture all instances of wso2carbon and audit logs. I don't think we need to modify generated log files as well since the procedure is to always move the anonymized log file to backup.
