### ISSUE TITLE
No message when wrong configurations are provided in the config.json in forgetme tool

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2845]
**Steps**
1. Configure the log-file-path incorrectly in the config.json file
2. Run the tool

**Issue**
The tool run successfully and no errors will be shown to the user. Ideally, a meaningful message should be shown to the user saying the configurations are wrong. This way the user can identify any mistakes easily

**Comment by ruwanta** [comment]
Document says
"All references to the user are wiped from WSO2 Identity Server. You can view the generated reports inside the <IS_HOME>/repository/components/tools/forget-me/conf"

This way the user can identify any mistakes easily.
And this is the way command-line tools behaves.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
