### ISSUE TITLE
The forgetme tool does not replace the pseudonym when the username is associated with the domain name

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2846]
**Steps**
1. Create a user : test
2. Login to the management console with user test
3. Try to delete a user without proper permissions. Then an exception will be logged
4. Logout from management console
5. Delete the user
6. Run the forgetme tool

**Issue**
Login and logout logs are replaced. But, the name in the exception was not replaced.
Ex:
`WARN {org.wso2.carbon.user.mgt.UserRealmProxy} -  An attempt to delete a user who has admin permission by user : PRIMARY/test
`

**Comment by darshanasbg** [comment]
@dilinisg This particular line logs about an administrative operation which cannot be performed by an end user. Hence not anonymizing this log is correct.
