### ISSUE TITLE
Black page in the management console when logged in from a tenant

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2847]
**Steps**
1. Create a tenant
2. Login to the management console from the tenant 

**Issue**
Directed to a blank page
![58](https://user-images.githubusercontent.com/1845370/37151443-8467219a-22fb-11e8-9907-0671d8d68de9.png)

**Comment by emswbandara** [comment]
reducing priority since this doesn't have a severe functional impact.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
