### ISSUE TITLE
When JWT access token issuer is configured, after cache expiration an access token with an opaque string is returned instead of the JWT

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#2849]
**Environment:**
IS 5.4.1 WUM updated distribution since 2018-02-20 with fix for [1].

**Configurations:**
JWT Token issuer is specifically being enabled in identity.xml with below configuration.
```
<IdentityOAuthTokenGenerator>org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer</IdentityOAuthTokenGenerator>
```
Access token expiration configured for the service provider (default 1h) is greater than the cache expiration time (default 15 minutes)

**Flow:**
OAuth2 implicit grant flow with response_type=token or OIDC implicit grant flow with response_type=id_token token

**Scenario 1:**

1. Get an access token with either of above options. This will return a JWT as the access token.
2. After the cache expirary time has exceeded, initiate a token request with implicit grant flow again. This will return the hash value of the JWT token issued previously, as the cache has been invalidated but still the token issued is not expired.

**Scenario 2:**

1. Try initiating a revoke token request (Ideally, for self contained access tokens token revocation doesn't apply as they are short lived)
2. If the cache entry for the previously issued JWT access token is there, it will clear the cache, but that will not impact the token entry for this respective token in the database. The token will still be active in the database.
3. Initiate a token request with implicit grant flow again. It will return the hash value of the JWT token issued previously.

[1] https://github.com/wso2/product-is/issues/2220

**Comment by pulasthi7** [comment]
Needed to revert wso2-extensions/identity-inbound-auth-oauth#865 to resolve merge conflicts when merging 5.6.x to maste. Need to resend back once the branch is merged.
