### ISSUE TITLE
No information given about the <log-file-name.log.temp.txt> file that gets created after running the forget me tool

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2854]
**Suggested Labels**
Type/Docs
Affected/IS550-Beta
Priority/High
Compliance/GDPR

**Description**

Refer to doc link [1]. In step 3 under running the tool in wso2 IS Add a note and include that after running the forget me tool a separate .text will be created with the name extension <log-name.log.temp.txt>
eg :- wso2carbon.log.temp.txt

and the deleted users user entries will be replaced by a pseudonym. 
Also include the file path where this file is created as 

<IS-Home>/repository/logs

[1].https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

**Comment by Nashaath** [comment]
Added the info based on the current naming convention used when log file copies are created. Added the info at the end of the "Running the tool in WSO2 IS" section.
