### ISSUE TITLE
Provide a sample command to show the usage of -pu together with other command line options in running forget me tool

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2857]
**Suggested Labels**
Type/Docs
Affected/IS550-Beta
Priority/Normal
Compliance/GDPR

**Description**
Refer to doc link [1]. Under the topic Running the tool in WSO2 IS in the given table under pu command section please include a sample command to show that how we can use the -U with -pu as below to replace the username with the provided Pseudoname

-U john.doe -pu “123-343-435-545-dfd-4”
-U john.doe -D Finance-Domain  -pu “123-343-435-545-dfd-4”

[1].https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

**Comment by ruwanta** [comment]
This is a command line tool.
The usual practice to do documentation e.g.[1]

[\[1\] dd man page](http://man7.org/linux/man-pages/man1/dd.1.html)

**Comment by Nashaath** [comment]
Added sample commands.
