### ISSUE TITLE
Can we have a compatible KM p2 repo for IS 5.5.0

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#2860]
**Description:**
In order to verify the IS as Key manager features, can you please provide us IS 5.5.0 KM p2 repo which compatible with APIM 2.1.0 update packs.

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/IS 5.5.0

**Comment by omindu** [comment]
Please move this issue to API product repo as it will be coming from APIM team
