### ISSUE TITLE
Can we include a sample command to run forget me tool with all the possible values?

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2861]
Can we include a sample command to run forget me tool with all the possible values in this doc [1]

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

E.g.,
For a user deleted in a tenant's secondary user store

 sh forgetme.sh -U user5 -D secondt -T test -TID 1

**Comment by ruwanta** [comment]
This is command line tool. 
The usual practice to document options and valid combinations. Please see [1] 

[\[1\] linux dd](http://man7.org/linux/man-pages/man1/dd.1.html)
