### ISSUE TITLE
Document should mention if we configure a secondary user store with JDBC, still we should include driver inside the tool

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2862]
Document should mention if we configure a secondary user store with JDBC, still we should include driver inside the tool in this doc [1]

[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Changingdefaultconfigurationsofthetool

It has below section. Better to include that as well.

If you have configured a JDBC user store instead of the H2 database provided by default, copy the relevant JDBC driver to the <IS_HOME>/repository/components/tools/forget-me/lib directory. For more information, see Configuring a JDBC User Store.

**Comment by ruwanta** [comment]
Why secondary user store is treated differently. It is a user store.
-1 for the suggestion.

BTW, the doc needs change as it is misleading. Tool does not touch user store. It accesses all other databases connected.

**Comment by Nashaath** [comment]
Changed the note as follows:

If you have configured any JDBC database other than the H2 database provided by default, copy the relevant JDBC driver to the <IS_HOME>/repository/components/tools/forget-me/lib directory.
