### ISSUE TITLE
Session time out explain

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#2864]
As in this doc , it says there was hard coded time out for 10 hours in previous release. But we don't need such statement now because we are already in 5.5.0 and in documentation better not to mention the previous version number. We will try to explain about current version detail against all previous versions. Went ?
https://docs.wso2.com/display/IS550/Configuring+Session+Timeout

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
