### ISSUE TITLE
Keep users informed displaying a proper back end message as it takes a reasonable time to finish scanning the log files when run the Forget me tool

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2865]
**Suggested Labels**
Type/Improvement
Affected/IS550-Beta
Priority/Normal
Compliance/GDPR

**Description**
While running the forget me tool using ./forgetme.sh -U <username> it takes a reasonable time to scan the log files. A user who is using this can get confused whether the Scan is running properly or not. Therefore suggest to Add a backend message like " Scanning In progress" untill the task ends successfully.

**Comment by ruwanta** [comment]
This is not possible. 
None of the command line tools available can do that.
try doing "grep" on large file, having no match an see the behavior. You will note get any feedback until  completed.

**Comment by emswbandara** [comment]
Closing since this is not a valid requirement.
