### ISSUE TITLE
UI issues in the login page of analytics dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2866]
1. The links of privacy and cookie policies are not visible

![60](https://user-images.githubusercontent.com/1845370/37206674-b4ad6322-23bf-11e8-84f0-b32ebbffe590.png)

**Comment by ruwanta** [comment]
Analytics is not an end user accessible product.
I think we can remove the  privacy and cookie policy banners.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
