### ISSUE TITLE
Do we need to restart server to update tenant wise data from UI

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#2868]
As in this document we can update tenant wise session time out and save it from UI.
But is says we have to restart the server ? Is that true ?

https://docs.wso2.com/display/IS550/Configuring+Session+Timeout

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
