### ISSUE TITLE
Incorrect steps are added for securing a service in ESB 5.0.0

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#2869]
Document: https://docs.wso2.com/display/IS541/Accessing+Claim+Aware+Services+using+STS+Secured+with+Non-repudiation#AccessingClaimAwareServicesusingSTSSecuredwithNon-repudiation-SecuringanEchoService(theRelyingParty)inESB
Step 2a

When securing the echo service, the unsecured text is disabled to be clicked. In the doc, the screenshot is added and continued the steps by moving through that path. This document redirects to ESB 5.0.0. In ESB 5.0.0, this is not the method to secure a service. 

Type/Bug
Severity/Major
Priority/Highest

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
