### ISSUE TITLE
Couldn't find documentation related to editing the PII controller data

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2870]
Searched "Configuring the PII controller" in the IS doc space, but couldn't find information on this.

![62](https://user-images.githubusercontent.com/1845370/37207870-f4ef2786-23c4-11e8-91e0-a576f74d194b.png)

**Comment by omindu** [comment]
@sherenewso2 can we add this to the doc. This option was recently introduced. Basically, this is one of the first steps and mandatory steps before configuring consent management

**Comment by sherenewso2** [comment]
Documented in [1] 

[1] https://docs.wso2.com/display/IS550/Consent+Management+Using+REST+APIs#ConsentManagementUsingRESTAPIs-ConfiguringthePIIcontroller
