### ISSUE TITLE
The exported user info does not show the edited PII controller details

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2871]
**Steps**
1. Change all the PII controller data under the resident service provider
2. Login to the dashboard and export the user info

**Issue**
The PII controller details shown are not updated.

**Comment by omindu** [comment]
The consent receipt will have the PII controller information, at the time the receipt was generated. A change of the PII controller will not be reflected in the existing receipts. If you generate a new receipt, that receipt should have the new PII controller information.

Is it not the behavior ?

**Comment by dilinisg** [comment]
Verified creating a new user and the updated PII information was received.

@sherenewso2  - shall we document this behaviour please?

**Comment by sherenewso2** [comment]
Added a note to [1] to describe this behaviour. @omindu please verify. 
[1] https://docs.wso2.com/display/IS550/Using+the+End+User+Dashboard#UsingtheEndUserDashboard-Exportingpersonalinformation
