### ISSUE TITLE
Oracle Rac scripts issues in IS 5.5.0

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-is#2879]
There are some errors when running the oracle rac scripts on oracle 12c

following are some of the errors. There are many errors similar to this

Error starting at line : 136 in command -
CREATE TABLE IDN_OAUTH2_SCOPE (
            SCOPE_ID INTEGER NOT NULL,
            NAME VARCHAR2(255) NOT NULL,
            DISPLAY_NAME VARCHAR2(255) NOT NULL,
            DESCRIPTION VARCHAR2(512),
            TENANT_ID INTEGER NOT NULL DEFAULT -1,
            PRIMARY KEY (SCOPE_ID))
Error report -
ORA-00907: missing right parenthesis
00907. 00000 -  "missing right parenthesis"
*Cause:    
*Action:

Oracle script seems to be working fine. seems like **TENANT_ID INTEGER NOT NULL DEFAULT -1,** needs to be **TENANT_ID INTEGER DEFAULT -1 NOT NULL,**

**Comment by omindu** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1467

**Comment by omindu** [comment]
Fixed with https://github.com/wso2/carbon-consent-management/pull/88/files
