### ISSUE TITLE
Column size should be increased

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2887]
In [1] point c should be changed. We should increase the column size to 2048 for REFRESH_TOKEN,ACCESS_TOKEN, AUTHORIZATION_CODE and CONSUMER_SECRET.

For example, H2/oracle/mysql should be as follows:-

ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN modify REFRESH_TOKEN VARCHAR(2048);
ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN modify ACCESS_TOKEN VARCHAR(2048);
ALTER TABLE IDN_OAUTH2_AUTHORIZATION_CODE modify AUTHORIZATION_CODE VARCHAR(2048);
ALTER TABLE IDN_OAUTH_CONSUMER_APPS modify CONSUMER_SECRET VARCHAR(2048);

[1] https://docs.wso2.com/display/IS530/Setting+Up+OAuth+Token+Encryption

**Comment by sherenewso2** [comment]
Edited the commands for all tabs in point c. @nilasini could you please check and verify if they are correct? Please re-open if anything is wrong. 

[1] https://docs.wso2.com/display/IS530/Setting+Up+OAuth+Token+Encryption

**Comment by nilasini** [comment]
@sherenewso2 shall we make all capital? I mean only "modify" is in small letter

**Comment by sherenewso2** [comment]
Fixed [1] 

[1] https://docs.wso2.com/display/IS530/Setting+Up+OAuth+Token+Encryption

**Comment by nilasini** [comment]
@emswbandara This change only needed in 5.3.0 doc.
