### ISSUE TITLE
Include the command to add the certificate file to the client trust store in Setting up a Cluster

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2896]
**Suggested Labels**
Type/Docs
Affected/IS550-Beta2
Priority/High

**Description**
Refer doc [1]. Under create ssl certificates section add a step and include the command to import the created certificate file into the client truststore as below

Execute the following command to add the certificate to the <IS_HOME>/repository/resources/security/client-truststore.jks file: keytool -import -trustcacerts -alias server -file server.crt -keystore client-truststore.jks

[1]. https://docs.wso2.com/display/IS550/Setting+Up+Deployment+Pattern+1

**Comment by Nashaath** [comment]
Added this step in doc versions 5.3.0 through 5.7.0.
