### ISSUE TITLE
Provide the file location where we need to execute the create ssl certificate commands in setting up a Cluster

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2899]
**Suggested Labels**
Type/Docs
Affected/IS550-Beta2
Priority/High

**Description**
Refer doc [1]. Under create ssl certificate please mention that we need to execute these commands by being inside /etc/nginx/ssl 

[1]. https://docs.wso2.com/display/IS550/Setting+Up+Deployment+Pattern+1

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
