### ISSUE TITLE
Cannot edit the Department under User Update profile section

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2900]
**Suggested Labels**
Type/Bug
Affected/IS550-Beta2
Priority/High

**Description**
Login to the management console
Create a user role
Create a User
Assign the created role to the user
Go to Update profile section of the created user

**Observation**
Cannot input a value for the Department as in [1]

[1]. update-profile.png
![update-profile](https://user-images.githubusercontent.com/31848014/37283506-42609f08-261e-11e8-84d1-bb974472632f.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
