### ISSUE TITLE
Update the places that are referring as <wso2is-5.3.0> to <wso2is-5.5.0> under setting up a cluster

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#2901]
**Suggested Labels*
Type/Docs
Affected/IS550-Beta2
Priority/Normal

**Description**
In [1] update the places that have wso2 is 5.3.0 as wso2 is 5.5.0

eg :- <wso2is-5.3.0> /repository/deployment/server/jaggeryapps/portal/conf/site.json 

[1]. https://docs.wso2.com/display/IS550/Setting+Up+Deployment+Pattern+1

**Comment by sherenewso2** [comment]
Fixed. Changed them to "IS_HOME"

[1] https://docs.wso2.com/display/IS550/Setting+Up+Deployment+Pattern+1
