### ISSUE TITLE
"Running the toolkit in standalone mode" is not clear

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2903]
What is meant by Running the toolkit in standalone mode?
It says,
`This tool can run standalone and therefore cater to multiple products. This means that if you are using multiple WSO2 products and need to delete the user's identity from all products at once, you can do so by running the tool in standalone mode.`

Also, need to describe how to delete the user's identity from all products at once

**Comment by Nashaath** [comment]
Updated the information [1] to mention that users can use the standalone version of the tool [2] if they want to remove references to a deleted user from multiple WSO2 products in one go.
[1] https://docs.wso2.com/display/IS550/Removing+References+to+Deleted+User+Identities#RemovingReferencestoDeletedUserIdentities-Runningthestandaloneversionofthetool
[2] https://github.com/wso2/identity-anonymization-tool
