### ISSUE TITLE
Cannot self sign in Firefox as it requests consent for all claim even when the consent is given

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2904]
Browser: Firefox Quantum - 58.0.2 (64-bit)
Pack: Beta 2

**Steps**
1. Enable self registration feature
2. Create a consent purpose
3. Try to sign up as a new user by selecting all the claims in the consent purpose

**Issue**
Pop up is displayed asking to give consent for all claims even when the consent is given for all claims
![69](https://user-images.githubusercontent.com/1845370/37287275-6f6c3190-262a-11e8-9db3-75bf5e1e5431.png)

Note: It is happening only in Firefox browser

**Comment by omindu** [comment]
Duplicates: https://github.com/wso2/product-is/issues/2902
