### ISSUE TITLE
Can't we get consent for the username in self registration itself

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2905]
When self registering a user, a user is given a set of claims as consent purposes to get the consent. After successful account confirmation, when the user tries to login to the application, a consent for the username is requested again.
![66](https://user-images.githubusercontent.com/1845370/37287608-3454ee52-262b-11e8-9eeb-cc236e9b3c4a.png)

Can't we get the consent for the username in self registration as another consent purpose without asking for the consent for different claims again and again?
What is the exact reason to get the consent for username in sign in?

**Comment by omindu** [comment]
During self signup, we are collecting consent for the resident IDP and that consent is not valid for the Dashboard, which is a seperate application.
