### ISSUE TITLE
Need a meaningful name for wso2_sp_dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2906]
Pack - beta2
It is better to give a meaningful name for wso2_sp_dashboard

![66](https://user-images.githubusercontent.com/1845370/37289213-2647f878-262f-11e8-808e-581c8b974e21.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
