### ISSUE TITLE
Oauth token encryption missing some configuration detail

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2913]
In [1], we should mention regarding the following xml files configurations.

Before starting the server user should change the property encrypted in '**IsAnalytics-Publisher-wso2event-OauthTokenValidation.xml**' to false as follows.

`<property encrypted="false" name="password">admin</property>`

The same configuration must be done for **IsAnalytics-Publisher-wso2event-OauthTokenRevocation.xml** as well.

Please include these detail in the doc.

[1] https://docs.wso2.com/display/IS530/Setting+Up+OAuth+Token+Encryption

**Comment by darshanasbg** [comment]
@sherenewso2 Please note that this is not required for 5.5.x.

@denuwanthi Please help to add this content for related wum update documentations

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
