### ISSUE TITLE
Inconsistent behaviour when special characters are used in the pseudonym

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2914]
Pack - beta2

Inconsistent behaviour when special characters are used in the pseudonym

**Original** 
'dilini@wso2.com@carbon.super [-1234]' logged out at [2018-03-13 09:39:11,0742]

1. **pu** = remove!wso2
**command run** = ./forgetme.sh -U dilini@wso2.com -pu removewso2is-5.5.0-beta2/bin/
**replaced value** = 'removewso2is-5.5.0-beta2/bin/ [-1234]' logged out at [2018-03-13 09:39:11,0742]

2. **pu** = remove&delete@wso2.com
**Error** = delete@wso2.com: command not found
**replaced value** = 'remove [-1234]' logged out at [2018-03-13 09:39:11,0742]

Need to mention the supported values for the pseudonym or handle the special characters properly

**Comment by JKAUSHALYA** [comment]
Updated the doc with allowed characters.
