### ISSUE TITLE
The purpose of default purpose and other purposes should be explained

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2919]
The purpose of default purposes and other purposes should be explained in the below doc

https://docs.wso2.com/display/IS550/Managing+Consent+Purposes

**Comment by sherenewso2** [comment]
There is already a note in the doc [1] that states the following: 

"The DEFAULT purpose listed at the top is used for single-sign-on authentication and includes all the PII categories. For more information about consent management with single sign on, see Consent Management with Single-Sign-On."

[1] https://docs.wso2.com/display/IS550/Managing+Consent+Purposes#ManagingConsentPurposes-Listconsentpurposes

**Comment by dilinisg** [comment]
@sherenewso2 - That is not enough to understand the concept, hence raised the issue. Reopening

**Comment by sherenewso2** [comment]
@dilinisg there is an introductory paragraph at the top of the page with a description and relevant definitions including definition of  what a 'purpose' is has been listed in the note below the intro paragraph. 

In the note explaining what the DEFAULT purpose is, there is a link to 'consent management with SSO' which is what the default purpose is used for. The user can get more information from that topic. 

What more information are you proposing to add to this document?

**Comment by dilinisg** [comment]
@sherenewso2 - @omindu and I discussed few points regarding this;  
- Default purpose is used only by the resident IDP
- examples for usages of default purpose 
- requirement for different consents for different SP's etc. 

Can you talk with Omindu and get it done please?

**Comment by sherenewso2** [comment]
Updated the description[1] 

[1] https://docs.wso2.com/display/IS550/Managing+Consent+Purposes#ManagingConsentPurposes-Listconsentpurposes
