### ISSUE TITLE
Option to delete the PII categories from management console

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2920]
We can delete PII categories of a consent purpose from the REST API, but not from the management console. Need to have that option from the MC too.

https://docs.wso2.com/display/IS550/Managing+Consent+Purposes

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
