### ISSUE TITLE
Replacing the PII information in original log file and a temporary file

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#2933]
**Description**:
Temp file of the already converted file should be provided in a meaningful manner (anon-1520948971627-anon-1520946792014-audit.log).

**Affected Product Version**:
EI 6.1.1 update 23

**OS, DB, other environment details and versions**:
OS - ubuntu 15.10
DB - mysql 5.6
JDK - 1.8

**Pre- Requisites**
PII information exists in the logs for user Peter and Sam

**Steps to recreate the issue**
1. Execute the tool to replace the user information (ex: ./forget-me.sh -U peter)
2. Stop the server and remove the original log file
3. Start the server and perform the operation
4. Execute the tool to replace information (ex: ./forget-me.sh -U Sam) in the original log file (audit.log) and the previous temp file (anon-1520946792014-audit.log)

**Observations**
temp files are getting generated for the original log and the initial temp file. How can we manage to replace PII information when original log file and temporary log file contains PII information.

![screenshot from 2018-03-13 19-50-26](https://user-images.githubusercontent.com/14962228/37347438-d84a4b84-26f7-11e8-9999-9abe3a8dd884.png)

**Related**
[1] https://github.com/wso2/identity-anonymization-tool/issues/60

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
