### ISSUE TITLE
Error when duplicated purpose name is added.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#2935]
### Steps to reproduce
- Log into management console.
- Add a new Consent Purpose.
- Try to add another purpose with the same name.

### Observed behavior
Error message: "Purpose: testPurpose1 adding failed"

### Expected behavior
Meaningful error message stating that the purpose name already exists.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
