### ISSUE TITLE
Can add same PII category more than once.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#2940]
### Steps to reproduce
- Log into the management console
- Add new Consent Purpose
- Select a particular PII category from the list
- Add same PII category again

![image](https://user-images.githubusercontent.com/9441136/37384345-55845938-2774-11e8-8fa5-156b5456e0f8.png)

### Observed behavior
When Finish button is clicked, only one instance per PII category got saved.

### Expected behavior
Selected PII categories should be removed from the list or an error message should be prompted explaining the issue.

### Tags
 Type/Improvement 
Priority/Low 
Affected/5.5.0-Beta

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
