### ISSUE TITLE
Issues in the README.txt

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2945]
1. Under "Secure sensitive information in carbon configuration files", the link returns to a page not found. Should point to the latest doc as well. 
```
For more details see
https://docs.wso2.com/display/Carbon443/WSO2+Carbon+Secure+Vault
```

2. Points to the old documentation
```
For further details, see the WSO2 Identity Server documentation at
https://docs.wso2.com/display/IS540/WSO2+Identity+Server+Documentation
```
3.  Under Project Resources, link to JIRA issue tracker is given. Ideally we should promote the Github for issue tracking now.

4. The link directs to the platform page. Also, no link to the WSO2 Oxygen Tank developer portal
```
For more information about WSO2 Identity Server please see http://wso2.org/projects/identity or visit the
WSO2 Oxygen Tank developer portal for addition resources.
```

5. Under Installation and Running, no link to the installation guide
`For more information, see the Installation Guide`

**Comment by dilinisg** [comment]
Also, throughout the README, it mentions 5.5.0 release, not RC1.
example:
```
==========================
WSO2 Identity Server 5.5.0
==========================

Welcome to the WSO2 Identity Server 5.5.0 release.
```

**Comment by emswbandara** [comment]
Fixed with https://github.com/wso2/product-is/pull/2946

**Comment by emswbandara** [comment]
In README it should be mentioned as 5.5.0 release and not RC1 because this is a release candidate of 5.5.0.
