### ISSUE TITLE
Unable to Strip off Secondary Userstore domain while using CAS Duo as Federated Authenticatior

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#2960]
Steps to reproduce:

1. Configure service provider in IS side. (PassiveSTS)
2. Configure DUO authenticator as a federated IDP by following [1]
3. Add a user in a secondary user store in IS
4. Login to the PassiveSTS sample application

Actual outcome 
When login to passiveSTS sample in the second step it will redirect to the DUO authenticator.
The user name which is redirected to the authenticator contains user name appended with secondary user store domain.

Expected outcome
There should be a configuration in duo authenticator configuration to optionally append user store domain and tenant domain. The default value should be the user name with out appending tenant domain or the user store domain.

NOTE 
With out depending on a configuration replacing below line in DuoAuthenticator initiateAuthenticationRequest method,

String tenantAwareUsername = MultitenantUtils.getTenantAwareUsername(username);
with below 
String userNameWithoutTenantDomainAndUserStoreDomain = MultitenantUtils
        .getTenantAwareUsername(UserCoreUtil.removeDomainFromName(userName));
and refactoring the tenantAwareUsername with userNameWithoutTenantDomainAndUserStoreDomain could solve the issue.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
