### ISSUE TITLE
Private Key JWT Authenticator documentation ask the user to build connector from source

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#2965]
In Private Key JWT Authenticator documentation, we ask the user to build the connector from source. This should be removed and instead it should point to download the connector from connector store [2] and place the downloaded connector in dropins directory instead of the compiled one. 

Following section should be removed. 

```
You can get the Private Key JWT Client Authenticator by building it. Follow the steps below to build:

1. Check out the code from https://github.com/wso2-extensions/identity-oauth-addons master branch.

2. Navigate to component/client-handler/

3. Execute "mvn clean install" to build the project.

4. Place the target/org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt-1.0.8-SNAPSHOT.jar in the <IS_HOME>/repository/component/dropins directory.
```

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
[2] https://store.wso2.com/store/assets/isconnector/details/3990fa78-6696-4b98-8af8-d4cc7611099a

**Comment by ShirazAzad** [comment]
Updated the doc [1] by removing that building steps.
[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC
