### ISSUE TITLE
Allow to override ACS url and SSO Skip URIs

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#2967]
**Description:**
Let's say the web applications come under a tenant space (a.com). Now, if you are fronting the application with a load balancer (e.g. Nginx) and a custom domain (custom.mine.com), one would not prefer to see the internal application server URL in the browser. For example, if we expect the application URL to be "custom.mine.com/foo", we would prefer to not show the original URL "appserver.com/t/a.com/foo".

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
WSO2IS-5.0.0

**Comment by pulasthi7** [comment]
Hi @SachithUd ,

What was the resolution for this ticket?

**Comment by rksk** [comment]
This can be done with a Vhost on the proxy.
