### ISSUE TITLE
The log file path and directory path are specified in an inconsistent way

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2969]
The log file path and directory path are specified in an inconsistent way.
"log-file-path" : "repository/logs", -> relative path from the Carbon Home.
"dir": "../../../../conf/datasources", -> relative path from the current directory

```
{
  "processors" : [
    "log-file", "rdbms"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "repository/logs",
      "log-file-name-regex" : "^(wso2carbon(.)*\\.log|audit(.)*\\.log)$"
    },
    {
      "dir": "sql",
      "type": "rdbms",
      "processor" : "rdbms"
    }
  ],
  "extensions": [
    {
      "dir": "../../../../conf/datasources",
      "type": "datasource",
      "processor" : "rdbms",
      "properties" : [
        {"identity": "WSO2_CARBON_DB"}
      ]
    }
  ]
}
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
