### ISSUE TITLE
Mention regarding playground.properties in doc

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2971]
(1) With [1] we have introduced a new property file called **playground2.properties** in playground application. Using that we can do the configurations like hostname, port and etc. Currently, we have **hardcoded** some sample values.

For example we have mentioned **IdentityServerPort** as **9443** but this value will change according to other configurations. For example, if someone starts the server with port offset 2 then the configured value in the **playground.properties**  file also needs to be changed as **IdentityServerPort=9445**

Could you please convey this message in the documentation [2].

[1] https://github.com/wso2/product-is/pull/1449
[2] https://docs.wso2.com/display/IS550/Basic+Client+Profile+with+Playground

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
