### ISSUE TITLE
Change all the old images of playground app with the latest playground application

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2973]
We are having old images of playground app in [1]. Please get the latest playground app from [2] and change all the images according to the new UI.

[1] https://docs.wso2.com/display/IS550/Basic+Client+Profile+with+Playground
[2] https://github.com/wso2/product-is/tree/5.5.x/modules/samples/oauth2/playground2

**Comment by nilasini** [comment]
Duplicated by 
https://github.com/wso2/product-is/issues/2315
https://github.com/wso2/product-is/issues/2804
https://github.com/wso2/product-is/issues/2814
https://github.com/wso2/product-is/issues/2800
https://github.com/wso2/product-is/issues/2002
https://github.com/wso2/product-is/issues/1987

**Comment by sherenewso2** [comment]
Screenshots have been updated now [1] 
[1] https://docs.wso2.com/display/IS550/Basic+Client+Profile+with+Playground
