### ISSUE TITLE
Need a way to disable security question based password recovery in accountrecovryendpoint web app.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#2974]
- We can disable notification based password recovery from the web.xml file as follows, but there is no option to disable security question-based password recovery from a config file.

  ```
  <context-param>
        <param-name>EnableEmailNotification</param-name>
        <param-value>false</param-value>
    </context-param>
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
