### ISSUE TITLE
Improve audit logs related with User Management

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#2975]
Currently when doing some user management tasks, we could not find the relevant audit logs related with that activity. For example, when adding claims to a users, those are not logged. 
This is very important for monitoring.

**Comment by Megala21** [comment]
Userstory - https://docs.google.com/document/d/1Ls0VuLsJaQtQAPgR3NkwtrcbFUvVZuPW_gXA7bV5mmo/edit?usp=sharing

**Comment by Megala21** [comment]
Documentation - https://docs.google.com/document/d/1U7X_I1-YSSkAP1FNsF0C-Yxc5xPyTmyhQUICf4nYbIE/edit

**Comment by madawas** [comment]
Fixed with wso2/carbon-kernel#1737 & wso2/carbon-identity-framework#1496
