### ISSUE TITLE
In the Hybrid flow, when IDtoken is generated there is no way to get the requested claims for filtering.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#2976]
This is with reference to [1],

In Hybrid flow when the response type is 'code id_token' the id_token is missing the effect of requestObject sent in the request. When there is a requirement to filter the id_token based on the values received in the requestObject, it is impossible at this moment.
Even from the DAO layer, this is not supported to retrieve RequestObject when 'token' is not available. If the requestObject details can be retrieved from either code or sessionDataKey, it can be consumed via an extension.

[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v5.6.63/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/dao/RequestObjectDAOImpl.java

@ayshsandu is aware of the context.

**Comment by Pushpalanka** [comment]
Could overcome this for state parameter using below method with IDTokenBuilder extended class as sessionDataKey is available at the moment.

```
SessionDataCache.getInstance().getValueFromCache(
                new SessionDataCacheKey(authzReqMessageContext.getAuthorizationReqDTO().getSessionDataKey()))
                .getoAuth2Parameters().getState();
```

It is useful and convenient if we can access state parameter with AuthorizationRequestDTO that is passed along. Thanks, @malithie for help with figuring out this workaround.

**Comment by ashensw** [comment]
Reducing the severity as a workaround is available.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
