### ISSUE TITLE
SCIM2 PATCH add operation fails when updating existing attributes along with non-existing attributes.

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#2978]
# Steps to reproduce

Enable SCIM2 listener in identity.xml

User create request 

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim1"},"userName":"kim1","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

**PATCH add existing attribute e.g emails.home**

curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"emails":[{"value":"kim.home2@gmail.com","type":"home"}]}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/752689e8-22c4-4f39-afe2-46ee32f3047d
 **response : 200 OK**

**PATCH add non-existing attribute e.g emails.other**

curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"emails":[{"value":"kim.other@gmail.com","type":"other"}]}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/752689e8-22c4-4f39-afe2-46ee32f3047d
**Response : 200 OK**

**PATCH add existing attribute + non-existing attribute**

curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"displayName":"display", "emails":[{"value":"kim.other@gmail.com","type":"other"}]}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/6a66ad20-3686-476c-a401-84cd47b05699

This will give 500 Internal Server Error giving below stack trace.

```
Caused by: org.wso2.carbon.user.core.UserStoreException: One or more attributes you are trying to add/update are not supported by underlying LDAP for user : kim3
	at org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager.handleException(ReadWriteLDAPUserStoreManager.java:2126)
	at org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager.doDeleteUserClaimValue(ReadWriteLDAPUserStoreManager.java:1103)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.deleteUserClaimValue(AbstractUserStoreManager.java:1497)
	... 66 more
Caused by: javax.naming.directory.NoSuchAttributeException: [LDAP: error code 16 - NO_SUCH_ATTRIBUTE: failed for     Modify Request
        Object : 'uid=kim3,ou=Users,dc=wso2,dc=org'
            Modification[0]
                Operation :  delete
                Modification
    displayName: (null)
: ERR_55 Trying to remove an non-existant attribute: ATTRIBUTE_TYPE ( 2.16.840.1.113730.3.1.241
 NAME 'displayName'
 DESC RFC2798: preferred name to be used when displaying entries
 EQUALITY caseIgnoreMatch
 SUBSTR caseIgnoreSubstringsMatch
 SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
 SINGLE-VALUE
 USAGE userApplications
```

**Comment by pulasthi7** [comment]
Merged https://github.com/wso2/carbon-identity-framework/pull/1501
