### ISSUE TITLE
Please make sure client-truststore.jks contains all the up to date trusted CAs

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#2980]
Can we verify this in every product release ?

**Comment by sagara-gunathunga** [comment]
+1 let's make it a part of release check-list.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
