### ISSUE TITLE
[Doc]Request object with custom claims couldn't be retrieve through user info endpoint

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#2985]
Followed the documentation [1] and did the procedure part.

When testing the flow with playground, from the user info endpoint only email claim is returning, the custom claim **customClaim2** is not returned.

Here the logged in user has a value for **customClaim2** and customClaim2 is selected as requested claim. But still user info endpoint not returning the **customClaim2**.

After some debugging found that **PiiCategory** doesn't have the **custom claims** which are requested at the same time it only contains the **local claims** which are requested.

[1] https://docs.wso2.com/display/IS550/Passing+OIDC+Authentication+Request+Parameters+in+a+Request+Object#PassingOIDCAuthenticationRequestParametersinaRequestObject-Procedure

**Comment by nilasini** [comment]
With Consent management, if we select particular claims as requested claims and then give the consent and access the userinfo it will give the requested claims.

But once you want to change the requested claims from the SP configuration then you need to revoke the consent and do the flow again otherwise userinfo won't give the newly selected requested claims.
![revoke](https://user-images.githubusercontent.com/20336761/37642119-030c7cd0-2c42-11e8-8eb3-d800e6a4a0fc.png)

At the same time if you not like to do the user consent revocation then you should mention the newly added requested claims as mandatory claim as well then only you can get the claims from user info endpoint.

![mandatory](https://user-images.githubusercontent.com/20336761/37642101-f43bcb0c-2c41-11e8-915d-8bff68df113c.png)

We have to mention this in the docs[1]

https://docs.wso2.com/display/IS550/Passing+OIDC+Authentication+Request+Parameters+in+a+Request+Object

**Comment by sherenewso2** [comment]
Added a note in versions 5.5.0 - 5.8.0 under step 3(c) [1] 

[1] https://docs.wso2.com/display/IS580/Passing+OIDC+Authentication+Request+Parameters+in+a+Request+Object#PassingOIDCAuthenticationRequestParametersinaRequestObject-Procedure
