### ISSUE TITLE
Documentation on admin services does not give complete information about fine grained information needed for each operation

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#2994]
Currently we have 
https://docs.wso2.com/display/IS530/API+Permissions
and 
https://docs.wso2.com/display/IS530/Permissions+Required+to+Invoke+Admin+Services

Documentation related to admin services permissions of IS 5.3.0. It could be better if we could link both of these docs and change the title to match with each other. Further some permissions listed are not actual permissions needed for the particular admin service.
For instance getSecondaryRealmConfigurations operation of UserStoreConfigAdminService actually requires "/permission/admin/manage/identity/userstore/config/view" however in doc we have mentioned "/permission/admin/manage" permission is required for that particular operation.

We need to document all the fine grained permissions in this spreadsheet
https://docs.google.com/spreadsheets/d/18WEbvU7DMoAZPNBTXdy0wHqIaGJSKNcB7K1F14iknIw/edit#gid=311719447

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
