### ISSUE TITLE
Configuration of certificate alias to use for assertion/response sigining  

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#2998]
Currently we use the certificate alias which is configured in carbon.xml or the tenant domain as the alias for retrieving the certificate for signing. Since we support different signing algorithms, we should have a way to configure the alias accordingly (ex: ECDSA algorithm only support with ECDSA certificates)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
