### ISSUE TITLE
Consent base user attribute filtering inconsistencies at consent expiry

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3001]
When requesting consent for expired claims, if a user picks a different set of claims during the second time. The attributes will not be properly filtered according to the new consent. This happens only during the attribute sharing just after providing consent for the expired claims. When the user logs in 2nd time, the attributes will be filtered correctly according to the new consent.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
