### ISSUE TITLE
Image is blurred

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3002]
In [1] the image is blurred. The error message description is not readable. Please change it to a clear image.

[1] https://docs.wso2.com/display/IS550/Enforcing+Signature+Validation+for+Request+Objects

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
