### ISSUE TITLE
Make consent request for federated claims non mandatory

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3003]
Currently, consent for federated user claims (when SP claim configs are not available) are prompted as mandatory, this should be changes as required as the user should have the option to proceed with authentication by selecting only a subset of federated claims.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
