### ISSUE TITLE
Support POST to oidc/logout

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#3004]
When ID_TOKEN value of id_token_hint is too long, browser tends to truncate logout URL. Hence, we need to support POST to logout.

https://localhost:9443/oidc/logout?id_token_hint=<ID_TOKEN>&post_logout_redirect_uri=<REDIRECT_URI>&state=<STATE>

**Comment by mefarazath** [comment]
@ayshsandu Can we actually support POST?
We need to get the consent of the user before logging out and redirect the user back to post_redirect_uri after clearing cookies etc.

**Comment by mefarazath** [comment]
@ayshsandu It seems we already support this via HTML auto submit forms. Information seems to be missing from docs regarding this. Created https://wso2.org/jira/browse/DOCUMENTATION-7830 track doc changes.
