### ISSUE TITLE
When calling logout, if already loggedout, need to redirect back instead of error page.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#3005]
When hit the logout url twice, If the user already logged out, we should redirect the user to redirect url

**Comment by malithie** [comment]
This is kind of a common practice. Ideally, if application should be notified of logout SLO needs to be used.
If the concern is on showing an error, better option would be to show an appropriate message. Something like below.
"No valid session found. Maybe you have already logged out."

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
