### ISSUE TITLE
Management console times out when loading service providers when there are many

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#3007]
Management console times out when loading service providers when there are many
Eg:
When there are 10,000 service providers - takes around 5 minutes to load all service providers
When there are 20,000 service providers - UI time out

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
