### ISSUE TITLE
Internal server error when trying to login to applications with 1500 concurrency

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#3008]
1. Create an OAuth application with client credentials grant type
2. Login to the application with 1500 and 2000 concurrency

**Issue**
Some requests fail with Internal server error (500)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
