### ISSUE TITLE
Internal Server Error when trying to update password feild via SCIM2 user endpoint.

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#3009]
Steps to reproduce.

Create user

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jayawardana","givenName":"vindula"},"userName":"vindula","password":"vindula","emails":[{"primary":true,"value":"vindula_home.com","type":"home"},{"value":"vindula_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

Update user password field using PUT

curl -v -k --user admin:admin -X PUT -d '{"schemas":[],"name":{"familyName":"jayawardana","givenName":"vindula"},"userName":"vindula","password":"sathya","emails":[{"value":"vindula@wso2.com","type":"work"},{"value":"vindulamj@gmail.com","type":"home"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/a5876e65-3803-48c6-9772-e7004cb13ee0

User update operation fails with 500 Internal Server Error

**Comment by pulasthi7** [comment]
Merged https://github.com/wso2/carbon-identity-framework/pull/1501
