### ISSUE TITLE
Captcha verification soap call times out when there are large amount of permission entries in the DB

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#3012]
Upon verifying the captcha code, the image stored as a registry resource is deleted. As a result, the registry tries to clear any authorizations (permissions) for the same resource.

The following database query is used for the aforementioned task.

DELETE FROM UM_ROLE_PERMISSION WHERE UM_PERMISSION_ID IN (SELECT UM_ID FROM UM_PERMISSION WHERE UM_RESOURCE_ID=?) AND UM_TENANT_ID=?

But there are no permissions set to the captcha image resource.

Therefore the inner query, SELECT UM_ID FROM UM_PERMISSION WHERE UM_RESOURCE_ID=? returns null and the index in UM_ROLE_PERMISSION table is not used. 

So when there is a huge number of records in UM_ROLE_PERMISSION table, there is a significant slowness.

**Comment by rushmin** [comment]
The PR [carbon-kernel-1735](https://github.com/wso2/carbon-kernel/pull/1735) fixes the issue.

**Comment by malithie** [comment]
Also reported at https://github.com/wso2/product-is/issues/2988
