### ISSUE TITLE
id_token returns with refresh_grant does not contain tenant domain in sub

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-is#3019]
Steps to reproduce :
- Enable "Use tenant domain in local subject identifier" in SP
- Try password grant with openid scope. This gives correct id_token with excepted sub (having tenant domain in it)
- Try refresh_grant with the refresh_token provided before. id-token returns from refresh_grant response done not contain the expected sub value. (sub value does not contain the tenant domain.)

**Comment by malithie** [comment]
Fixed over 
[1] https://github.com/wso2/product-is/issues/2561
[2] https://github.com/wso2/product-is/issues/2816
