### ISSUE TITLE
Need to mention the configurations to be done in a cluster setup when enabling MFA

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#3022]
Step 11 and 12 in the doc [1] mentions some configurations to do when configuring multi-factor authentication for WSO2 Identity Server. But, it is not sufficient when trying out the same in a cluster setup. The following two properties in the authenticators.xml file should also be changed in a cluster setup. Otherwise, it won't work. Please mention to configure these two properties as well.

```
      <Parameter name="IdentityProviderSSOServiceURL">https://is550.qa.com:443/samlsso</Parameter>
      <Parameter name="AssertionConsumerServiceURL">https://is550.qa.com:443/acs</Parameter>
```

[1] https://docs.wso2.com/display/IS540/Multi-factor+Authentication+for+WSO2+IS

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
