### ISSUE TITLE
[Doc] Upgrading+from+a+Previous+Release

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#3027]
Issues
1.please explain this in a bit details, at first glance its a bit confusing
`Copy the following configuration files from the <NEW_IS_HOME> and paste it in the copy of the <OLD_IS_HOME> in the relevant path.`

2.Under` "Configuration changes: Click here to view the table.."` 
"carbon.xml file stored in the` <IS_HOME>/repository/conf/identity folder`." but the carbon.xml is not inside the identity folder but the `repository/conf `folder

3.The document [1] does not discuss about moving any required webapps which could be a required step.
[1]https://docs.wso2.com/display/IS550/Upgrading+from+a+Previous+Release

4.We need to mention changed on api-manager.xml

5.From IS-KM5.3.0 to IS-KM5.5.0 just moving the user-mgt.xml wont work as the below property needs to be added.
` <Property name="UsernameWithEmailJavaScriptRegEx">^[\S]{3,30}$</Property>`

**Comment by shavantha** [comment]
when we are migrating from 5.3.0 to 5.5.0 other than the below two files[1] we also need to mention to move the below 3 files from the <NEW IS HOME> to the <OLD IS HOME> conf folder 
    [1] files mentioned on the docs
    <IS_HOME>/repository/conf/carbon.properties
    <IS_HOME>/repository/conf/consent-mgt-config.xml

 /repository/conf/identity/charon-config.xml 
 /repository/conf/security/balana-config.xml
/repository/conf/scim2-schema-extension.config

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
