### ISSUE TITLE
Migration clients did not start

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#3031]
Migration clients did not start 

products
1.IS KM 5.5.0 
steps
1.add the migration-client to IS ROOT as on[1]
[1]https://docs.wso2.com/display/IS550/Upgrading+from+a+Previous+Release
2.start the migration
3.check if the migration clients 

The migration client is not loaded and when the bundles for org.wso2.carbon.is.migration-5.5.0.jar showed as INSTALLED and not ACTIVE status
Migration clients org.yaml.snakeyaml did not load

**Comment by shavantha** [comment]
this same issue came with the migration client pointed from the step 6 of https://docs.wso2.com/display/AM220/Upgrading+from+the+Previous+Release

**Comment by DMHP** [comment]
https://github.com/wso2/product-is/pull/3037

**Comment by shavantha** [comment]
please update the migration client for the APIM product also with the same jar
