### ISSUE TITLE
SCIM2 allows extension attributes when the schema-extension property is disabled.

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#3034]
**Steps to reproduce:**

Disable schema extension by setting the following property to false in <SERVER_HOME>/repository/conf/identity/provisioning-config.xml

   Property name="user-schema-extension-enabled">false</Property>
Restart the server

Create SCIM user with extension schema
**Request**
curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Bandara","givenName":"sathya"},"EnterpriseUser":{"manager":{"displayName":"sathya1","$ref":"User"}},"userName":"sathya","password":"1234","emails":[{"primary":true,"value":"sathya_home.com","type":"home"},{"value":"sathya_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

Now do a GET request on the created user 
curl -v -k --user admin:admin https://localhost:9443/scim2/Users/3ad23e86-cfbf-4bb6-87df-0223f4b95aa8

**Response** 
{"emails":[{"type":"work","value":"vindula_work.com"},{"type":"home","value":"vindula_home.com"}],"meta":{"created":"2018-04-03T16:43:47Z","location":"https://localhost:9443/scim2/Users/3ad23e86-cfbf-4bb6-87df-0223f4b95aa8","lastModified":"2018-04-03T16:43:47Z","resourceType":"User"},"displayName":"sathya1","schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"EnterpriseUser":{"manager":{"displayName":"sathya1","$ref":"User"}},"name":{"givenName":"vindula6","familyName":"jayawardana"},"id":"3ad23e86-cfbf-4bb6-87df-0223f4b95aa8","userName":"vindula6"}

**Expected behavior**
The created user should not contain extension attributes since the config is disabled.

**Comment by emswbandara** [comment]
For SCIM2 in order to disable the extension schema we need to do the following configuration change.

- In charon-config.xml file in <SERVER_HOME>/repository/conf/identity folder, set the following property to false.
 
`    <Property name="user-schema-extension-enabled">false</Property>`

This needs to mentioned in [1]

[1] https://docs.wso2.com/display/IS550/Extensible+SCIM+User+Schemas+With+WSO2+Identity+Server

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
