### ISSUE TITLE
Add Documentation related with New User Management Audit Logs and Error Listener

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#3048]
Please refer [1], https://github.com/wso2/product-is/issues/2975.

We are introducing new event listener to handle the errorenous scenario and futher we have improved the logging format to support the log management systems. This need to be documented. 

https://docs.google.com/document/d/1U7X_I1-YSSkAP1FNsF0C-Yxc5xPyTmyhQUICf4nYbIE/edit?usp=sharing

**Comment by sherenewso2** [comment]
Added wum update content to [1]. Added content about the listener and operations to the 5.6.0 doc [2]. 

[1] https://docs.wso2.com/display/IS550/Using+the+User+Management+Errors+Event+Listener
[2] https://docs.wso2.com/display/IS560/Using+the+User+Management+Errors+Event+Listener
