### ISSUE TITLE
IS 5.3.0 to 5.4.0 migration script for identity fails

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#3053]
The migration script for IS 5.3.0 to 5.4.0 does not run when we execute with the command [1] as per the document[2]. However, it was noted that once the script was run manually the first two alter  steps of the script was applied 

after running the tool
=====================
![after_tool_run](https://user-images.githubusercontent.com/6552100/38491373-4a1f1fa2-3c09-11e8-84d2-b812f76f02d3.png)

manually applying the changes
======================
![manual](https://user-images.githubusercontent.com/6552100/38491852-bcbde39e-3c0a-11e8-8b2f-5131a3ad55b7.png)

[1]sh wso2server.sh -Dmigrate -Dcomponent=identity
[2]https://docs.wso2.com/display/IS540/Upgrading+from+a+Previous+Release

```

sp_rename 'IDN_OAUTH2_SCOPE.NAME', 'DISPLAY_NAME', 'COLUMN';
sp_rename 'IDN_OAUTH2_SCOPE.SCOPE_KEY', 'NAME', 'COLUMN';
ALTER TABLE IDN_OAUTH2_SCOPE ALTER COLUMN NAME VARCHAR(255) NOT NULL;
ALTER TABLE IDN_OAUTH2_SCOPE ALTER COLUMN DISPLAY_NAME VARCHAR(255) NOT NULL;
ALTER TABLE IDN_OAUTH2_SCOPE DROP COLUMN ROLES;
UPDATE IDN_OAUTH2_SCOPE SET TENANT_ID = -1 WHERE TENANT_ID = 0;
CREATE UNIQUE INDEX SCOPE_INDEX ON IDN_OAUTH2_SCOPE (NAME, TENANT_ID);

DECLARE @Command NVARCHAR(max), @ConstaintName NVARCHAR(max), @TableName NVARCHAR(max),@ColumnName NVARCHAR(max)
SET @TableName = 'IDN_OAUTH2_SCOPE'
SET @ColumnName ='TENANT_ID'
SELECT @ConstaintName = name
    FROM sys.default_constraints
    WHERE parent_object_id = object_id(@TableName)

SELECT @Command = 'ALTER TABLE '+@TableName+' drop constraint '+ @ConstaintName

IF @Command IS NOT NULL
BEGIN
    EXECUTE sp_executeSQL @Command
    SELECT @Command = 'ALTER TABLE '+@TableName+' ADD CONSTRAINT '+@ConstaintName+' DEFAULT -1 FOR ' + @ColumnName
    EXECUTE sp_executeSQL @Command
END

DECLARE @COMMAND1 NVARCHAR(200);SELECT TOP 1 @COMMAND1= 'ALTER TABLE IDN_OAUTH2_RESOURCE_SCOPE DROP CONSTRAINT ' + RC.CONSTRAINT_NAME + ';' FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KF ON RC.CONSTRAINT_NAME = KF.CONSTRAINT_NAME JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KP ON RC.UNIQUE_CONSTRAINT_NAME = KP.CONSTRAINT_NAME WHERE KF.TABLE_NAME = 'IDN_OAUTH2_RESOURCE_SCOPE' AND KP.TABLE_NAME='IDN_OAUTH2_SCOPE';EXEC (@COMMAND1);

ALTER TABLE IDN_OAUTH2_RESOURCE_SCOPE ALTER COLUMN SCOPE_ID INTEGER NOT NULL;
ALTER TABLE IDN_OAUTH2_RESOURCE_SCOPE ADD FOREIGN KEY (SCOPE_ID) REFERENCES IDN_OAUTH2_SCOPE(SCOPE_ID) ON DELETE CASCADE;
```
~

**Comment by DMHP** [comment]
This issue is occurring when duplicate entries for the key NAME,TENANT_ID are exist in the IDN_OAUTH2_SCOPE table. There should be no possibility for adding duplicate data for this key. When analyzing it was identified that duplicate records are added to the IDN_OAUTH2_SCOPE table when we design an API. This causes the migration scripts "step2" for (ISKM 5.4.0)  to fail. So raised [1] in APIM to track this.

[1] https://github.com/wso2/product-apim/issues/3190

**Comment by shavantha** [comment]
This issue should be ideally fixed from APIM side where they prevent multiple records from being inserted into the table

**Comment by shavantha** [comment]
Doc Impact :N/A
