### ISSUE TITLE
The subject will not contain tenant domain in the id-token, when cookie is availble

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#3058]
Steps to reproduce:

1. Create a SP with OAuth/OpenID Connect Configurations in Inbound authentication configuration
2. Tick the Use tenant domain in local subject identifier in Local & Outbound Authentication Configuration
3. Get a id token from a new session. The subject will contain tenant domain.
4. Get another id token from the same session. The subject will not contain tenant domain.

eg: 
id_token1 :  
{
  "sub": "testuser11@carbon.super",
  "aud": [
    "vnxzLMpkYNnfMUQ2_4NaZ2cSjiMa"
  ],
  "azp": "vnxzLMpkYNnfMUQ2_4NaZ2cSjiMa",
  "amr": [],
  "iss": "https://localhost:9853/oauth2/token",
  "exp": 1523285686,
  "nonce": "oidc",
  "iat": 1523282086,
  "sid": "3ed42cc0-3b0a-46a3-bb48-ddde3ee03039"
}

id_token2 :

{
  "sub": "testuser11",
  "aud": [
    "vnxzLMpkYNnfMUQ2_4NaZ2cSjiMa"
  ],
  "azp": "vnxzLMpkYNnfMUQ2_4NaZ2cSjiMa",
  "amr": [],
  "iss": "https://localhost:9853/oauth2/token",
  "exp": 1523285767,
  "nonce": "oidc",
  "iat": 1523282167,
  "sid": "3ed42cc0-3b0a-46a3-bb48-ddde3ee03039"
}

**Comment by chunyeow** [comment]
@GDRDABARERA Is this issue fixed? Where is the patch?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
