### ISSUE TITLE
Latest versions of authenticators are not updated in IS 5.3.0, 5.4.0,5.4.1 WUM 

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#3059]
TOTP, EmailOTP, Office365, X509, SMS OTP, and Twitter authenticators not get updated to the latest version in IS 5.2.0 WUM.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
