### ISSUE TITLE
Parameters in the Urls of  email templates should UrlEncorded

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#3061]
There are some parameter values in the URL which are not encoded, as best practice we have to encode them.

Eg:
Available : 
            https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation={{confirmation-code}}&amp;userstoredomain={{userstore-domain}}&amp;username={{url:user-name}}&amp;tenantdomain={{tenant-domain}}

Must be:

            https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation={{confirmation-code}}&amp;userstoredomain={{url:userstore-domain}}&amp;username={{url:user-name}}&amp;tenantdomain={{url:tenant-domain}}

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
