### ISSUE TITLE
Both TokenLoggable and validityPeriodMillis are considering when returning the validityPeriodMillis

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#3065]
In [1] token loggable and access token validity period depended on each other. Ideally, both should not depend on each other.

When going through the below condition, under getTokenExpireTimeMillis method.

```
        if (accessTokenValidityPeriodMillis < 0 &&
                IdentityUtil.isTokenLoggable(IdentityConstants.IdentityTokens.ACCESS_TOKEN)) {
            log.debug("Access Token : " + accessTokenDO.getAccessToken() + " has infinite lifetime");
            return -1;
        }
```
According to the above condition, when not enabling TokenLoggable, return 0 if accessTokenValidityPeriodMillis < 0. But when enabling TokenLoggable, it returns -1 correctly.

Need to change the above condition as below.

```
        if (accessTokenValidityPeriodMillis < 0) {
            if (IdentityUtil.isTokenLoggable(IdentityConstants.IdentityTokens.ACCESS_TOKEN)) {
                log.debug("Access Token : " + accessTokenDO.getAccessToken() + " has infinite lifetime");
            }
            return -1;
        }
```
Above fix returns -1, when accessTokenValidityPeriodMillis < 0, if the TokenLoggable is enabling or not.

[1] https://github.com/wso2-support/identity-inbound-auth-oauth/blob/support-5.3.4/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L745

**Comment by DMHP** [comment]
This issue is already fixed in the latest versions from IS 5.5.0
