### ISSUE TITLE
Mapping external claim URLs to multiple local claim URLs is allowed from claim-config.xml

### ISSUE THREAD

**Issue by madawas** [wso2/product-is#3069]
#### Description
When adding an external claim via Carbon UI, the same local claim cannot be mapped to multiple external claim URIs. However, this is possible via configuring the external claim via the `claim-config.xml` file.

#### Steps to Reproduce
Add a new external claim in `claim-config.xml` defining the local claim as an already mapped local claim.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
