### ISSUE TITLE
initializeRegistry() in IdentityTenantUtil is called for every SSO request

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#3076]
How to reproduce

1.  Enable account locking
2.  Restart the server & send several Openid connect requests (authorization code)
3. This method is hit for every request.

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-identity-framework/commit/f88715f5234cb560c702529a2ebea586dc5f9f8e#diff-65f77487fa7914309562d0e4dff87be5R203. But the fix is not available in latest master code
