### ISSUE TITLE
setUserClaimValue is called even for success authentication when authentication lock is enabled

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#3077]
Following attributes are being updated for every authentication. 

 ============= KEY =========== http://wso2.org/claims/identity/unlockTime 
=============== VALUE ========= 0 

============= KEY =========== http://wso2.org/claims/identity/failedLoginAttempts 
=============== VALUE ========= 0 

============= KEY =========== http://wso2.org/claims/identity/accountLocked 
=============== VALUE ========= false 

============= KEY =========== http://wso2.org/claims/identity/failedLoginLockoutCount 
=============== VALUE ========= 0 

We need to eliminate it.

**Comment by thanujalk** [comment]
This is already fixed in the latest.
