### ISSUE TITLE
Whenever a claim is added DB queries get initiated for each existing claim to retrieve claim mappings

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#3081]
Below happens whenever a claim gets added in order to load claims back to the cache.
- Add claim, attribute mappings and attribute properties to the database
- Get all claims from the database
- For each claim a database call is initiated to retrieve attribute mappings and another call is initiated to retrieve metadata properties

A separate cache which is distributed across nodes is used to identify the claim set is updated. 
Above model seems to be used due to this approach. Need to review and improve

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
