### ISSUE TITLE
[Bug] User profile is not updated by PostAuthnMissingClaimHandler

### ISSUE THREAD

**Issue by menakaj** [wso2/product-is#3084]
When federated authentication is enabled along with JIT provisioning, the missing claims post authentication handler should update the claims of the created user account.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
