### ISSUE TITLE
Column size is not enough for UM_ATTR_VALUE of the UM_USER_ATTRIBUTE table when Orcle databse is created.

### ISSUE THREAD

**Issue by NShani** [wso2/product-is#3089]
The below database error occurs during the attempt to provision the user when the Oracle database is created.

> 

ORA-12899: value too large for column "M_ISU_X"."UM_USER_ATTRIBUTE"."UM_ATTR_VALUE" (actual: 260, maximum: 255)

- Error occurs due to the not having enough length for the UM_ATTR_VALUE of the UM_USER_ATTRIBUTE table.
- All roles are going to be stored in this column as an array.
- Therefore it is not enough to save when there are several roles.
- Column size should be increased for this UM_ATTR_VALUE column in Oracle database script.

**Comment by senthalan** [comment]
same issue - https://github.com/wso2/product-is/issues/3098
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1541/files

**Comment by madurangasiriwardena** [comment]
Duplicate of https://github.com/wso2/product-is/issues/3098
