### ISSUE TITLE
Cross-protocol logout feature

### ISSUE THREAD

**Issue by DeshanKTD** [wso2/product-is#3090]
In WSO2 Identity Server, single sign-on among different SSO protocols is supported. But currently, it does not support single logout among application which uses different SSO protocols.
 As an example, if the user has some service provider (SP) sessions in  OIDC and SAML, when user-initiated logout from an OIDC SP, it only informs the other OIDC SPs for terminate the sessions. Not for the SAML SPs. 

So main task of the feature is to provide cross-protocol logout for SAML and OIDC as the first phase.

**Comment by hauntingEcho** [comment]
as a heads-up, Identity Server does not support front-channel IdP-initiated (or IdP-forwarded) SAML single-logout in general: https://github.com/wso2/product-is/issues/2111

**Comment by sachiniWettasinghe** [comment]
The Cross-Protocol logout feature is planned to be implemented using backchannel SAML logout and backchannel OIDC logout. Currently, backchannel SAML logout is implemented and unit tests are added in [1]. 

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/195
