### ISSUE TITLE
When run a scim call to update a non-exisiting user giving NPE

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3091]
When accessing the following request response must be similar to "user: "fake" does not exist" but actual response is NPE.

Request :- 
curl -v -k --user admin:admin -X PATCH -d '{"schemas": ["urn:scim:schemas:core:1.0"],"name":
{"familyName": "Tester"},"userName": "fake","meta": {"attributes": []}}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users/fakee

Actual response (Part of the error is shown here ):- 

</pre></p><p><b>root cause</b> <pre>java.lang.NullPointerException
	org.wso2.charon.core.protocol.endpoints.UserResourceEndpoint.updateWithPATCH(UserResourceEndpoint.java:637)
	org.wso2.carbon.identity.scim.provider.resources.UserResource.updateUserPATCH(UserResource.java:307)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.jav

**Comment by madawas** [comment]
Fixed with #106
