### ISSUE TITLE
Support SCIM for existing groups

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3093]
WSO2 Identity Server does not support retrieving existing groups in a user store over SCIM at the moment. This is because at the moment, IS maintains the unique group id separately from the user store plugged. Either that needs to be populated for existing groups or we should support reading the group id from an immutable attribute like objectGUID in AD.

Below can be done to support this case:

1. Make SCIMUserManager and GroupHandler pluggable.
2. May have to move the logic of adding unique group id for SCIM groups, from SCIMUserOperationEventListener to SCIMUserManager. Because the logic to retrieve those group ids are in SCIMUserManager. Therefore it creates an inconsistency in the design. Yet, need to check whether there are other reasons to do it this way.
3. Give the ability to have group attributes in internal SCIM table or external user store. The generic feature to support this is the ability to support attributes for external groups. However since we don't have this feature at user store level, we need to at least support this at SCIM level in order to make SCIM work for existing groups.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
