### ISSUE TITLE
Referencing groups on the SCIM Group endpoint

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3095]
With the user's endpoint, we can call individual users by their username (We need to map scimid with username through claim configuration)

e.g.https://localhost:9443/wso2/scim/Users/testUser will bring back the details for that user.

 when trying to do the same with the group's endpoint it appears we can only reference groups by the unique ID that is created when the group is made through IS - for example, calling https:localhost:9443/wso2/scim/Groups/<id> returns the group detail.

But calling the displayName instead of this. i.e. *https://localhost:9443/wso2/scim/Groups/groupTest, returns an error - *{"Errors":[
{"code":"404","description":"Group not found in the user store."}
]}*

In order to make this feature available, we need to make SCIMGroupHandler to be extensible, so that we can write a custom SCIMGroupHandler and support this feature.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
