### ISSUE TITLE
Adding end users cert to the SP is not enough for Private Key JWT Client Authentication

### ISSUE THREAD

**Issue by amalkasubasinghe** [wso2/product-is#3096]
Adding cert to the SP is not enough, need to add it to the keystore too.
isn't this should support to work with the cert which is added to the SP?

We are using org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt-1.0.7.jar

**Comment by isharak** [comment]
Fixed with 
https://github.com/wso2-extensions/identity-oauth-addons/commit/8a4812a693fa12765ec002c444d31cfc74acbc7f
