### ISSUE TITLE
Localization for accountrecoveryendpoint in IS-KM-5.3.0

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#3101]
accountrecoveryendpoint web application in IS-KM-5.3.0 doesn't have localization (multi-language) support implemented.

**Comment by dicastro** [comment]
Hi, I am really interested in this issue.

What does it mean the label `FUTURE`? In which version it is going to be developped?

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1566
