### ISSUE TITLE
Using existing claim for password-policy-connector 1.0.4 without adding a new claim.

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#3112]
**Description:**
While adding the password-policy-connector 1.0.4, in the documentation \[1], it is mentioned to add a new claim called "http://wso2.org/claims/lastPasswordChangedTimestamp". 
But already there is a claim called "http://wso2.org/claims/identity/lastPasswordUpdateTime".

While referring to the code, it seems like that the claim "http://wso2.org/claims/lastPasswordChangedTimestamp" is requesting from the code.

Therefore, can we make it clearer and do the needful to use the default claim without adding a new claim.

\[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Password+Policy+Authenticator

**Suggested Labels:**
PasswordPolicyAuthenticator

**Affected Product Version:**
WSO2IS-5.3.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
