### ISSUE TITLE
[IS510-Docs]Execution steps are missing in sample downloading

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#3118]
Document: https://docs.wso2.com/display/IS510/Downloading+a+Sample
It gives the following error since this step is missing. 

> fatal: This operation must be run in a work tree

Please include the following line before step 3. 
`cd ../../`

Type/Docs
Severity/Minor
Priority/High
Affected/5.1.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
