### ISSUE TITLE
Configuration step is missing in Shibboleth installation

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#3121]
Document: https://docs.wso2.com/display/IS530/Configuring+Shibboleth+IdP+as+a+Trusted+Identity+Provider
Section: https://docs.wso2.com/display/IS530/Configuring+Shibboleth+IdP+as+a+Trusted+Identity+Provider#ConfiguringShibbolethIdPasaTrustedIdentityProvider-ConfiguringShibbolethasaSAML2identityprovider

Before step 9, the following step should be included. 

> Copy the <SHIBBOLETH_HOME>/lib/endorsed folder to Tomcat root folder. 

If this step is not included, the war file inside SHIBBOLETH_HOME/idp folder does not get successfully deployed. Once you try to access https://localhost:8443/idp/status, it gives a 404 error. 

Type/Bug
Severity/Major
Priority/High 
Affected/is-5.3.0 docs

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
