### ISSUE TITLE
Not getting  claims from WSO2 (intermittent issues)

### ISSUE THREAD

**Issue by GITOmpratap** [wso2/product-is#3129]
I have been using wso2 IS 5.4.0 for SP initiated SSO.

Work flow step:
1. Request to wso2 with passing **fidp** parameter
2. Wso2 redirect base on FIDP mapped with SP to SSO login page.
3. Logged from SSO page and post all SAML repose to /commonauth Endpoint. 
4. Wsso2 validating all claims and redirect back on callback(my application endpoint) URL with authorization_code.
5. Application initiated background call to fetch OIDC token with passing authorization_code (grant_type:code) to **/oauth2/token** end point.
Wso2 not return remote claim only from some time not always.

**Stack trace while getting claims:**    
  
TID: [-1234] [] [2018-04-24 07:25:03,296] DEBUG {org.wso2.carbon.identity.application.common.util.IdentityApplicationManagementUtil} -  JWT Header :{"typ":"JWT", "alg":"HS256"} 
TID: [-1234] [] [2018-04-24 07:25:03,296] DEBUG {org.wso2.carbon.identity.application.common.util.IdentityApplicationManagementUtil} -  JWT Body :{"iss":"wso2","exp":15245547032963000,"iat":1524554703296,"idps":[{"idp":"adfs_idp_company1","authenticator":"SAMLSSOAuthenticator"}]} 
TID: [-1234] [] [2018-04-24 07:25:03,297] DEBUG {org.wso2.carbon.identity.application.authentication.framework.config.ConfigurationFacade} -  Trying to find the IdP for name: adfs_idp_company1 
TID: [-1234] [] [2018-04-24 07:25:03,297] DEBUG {org.wso2.carbon.identity.application.authentication.framework.config.ConfigurationFacade} -  A registered IdP was found 
TID: [-1234] [] [2018-04-24 07:25:03,298] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Role claim uri is not configured for the external IDP: adfs_idp_company1, in Domain: company1sso. 
TID: [-1234] [] [2018-04-24 07:25:03,298] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultSequenceHandlerUtils} -  Getting Service Provider mapped roles of application: falcon-app of user: null 
TID: [-1234] [] [2018-04-24 07:25:03,298] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultSequenceHandlerUtils} -  Service Provider Mapped Roles: null 
TID: [-1234] [] [2018-04-24 07:25:03,299] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  Executing claim handler. isFederatedClaims = true and remote claims = [MIDDLE_NAME:M,ID:user2.pawar,LAST_NAME:Pawar,EMAIL:user2.pawar@domain.com,FIRST_NAME:user2,] 
TID: [-1234] [] [2018-04-24 07:25:03,299] DEBUG {org.wso2.carbon.identity.claim.metadata.mgt.dao.CacheBackedExternalClaimDAO} -  Cache hit for external claim list for dialect: http://wso2.org/oidc/claim in tenant: -1234 
TID: [-1234] [] [2018-04-24 07:25:03,299] DEBUG {org.wso2.carbon.identity.claim.metadata.mgt.dao.CacheBackedExternalClaimDAO} -  Cache hit for external claim list for dialect: http://wso2.org/oidc/claim in tenant: -1234 
TID: [-1234] [] [2018-04-24 07:25:03,300] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  Setting 'ServiceProviderSubjectClaimValue' property value from attribute map user2.pawar@domain.com 
TID: [-1234] [] [2018-04-24 07:25:03,300] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  Tenant aware username or user store 'NULL'. Possibly federated case 
TID: [-1234] [] [2018-04-24 07:25:03,300] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -   **Returning claims from claim handler = [middle_name:M,given_name:user2,family_name:Pawar,email:user2.pawar@domain.com,]** 

>log in case of getting claims

TID: [-1234] [] [2018-04-24 07:25:03,300] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  UNFILTERED_IDP_CLAIM_VALUES map property set to [MIDDLE_NAME:M,ID:user2.pawar,LAST_NAME:Pawar,EMAIL:user2.pawar@domain.com,FIRST_NAME:user2,] 
TID: [-1234] [] [2018-04-24 07:25:03,300] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  UNFILTERED_LOCAL_CLAIM_VALUES map property set to [http://wso2.org/claims/emailaddress:user2.pawar@domain.com,http://wso2.org/claims/lastname:Pawar,http://wso2.org/claims/middleName:M,http://wso2.org/claims/givenname:user2,] 
TID: [-1234] [] [2018-04-24 07:25:03,300] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  UNFILTERED_SP_CLAIM_VALUES map property set to [middle_name:M,given_name:user2,family_name:Pawar,email:user2.pawar@domain.com,] 
TID: [-1234] [] [2018-04-24 07:25:03,301] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Authenticated User: user2.pawar@domain.com 
TID: [-1234] [] [2018-04-24 07:25:03,301] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Authenticated User Tenant Domain: carbon.super 
TID: [-1234] [] [2018-04-24 07:25:03,301] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Step processing is completed. 
TID: [-1234] [] [2018-04-24 07:25:03,302] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultPostAuthenticationHandler} -  Post authentication handling for missing claims started 
TID: [-1234] [] [2018-04-24 07:25:03,303] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler} -  Concluding the Authentication Flow 
TID: [-1234] [] [2018-04-24 07:25:03,319] DEBUG {org.wso2.carbon.identity.data.publisher.application.authentication.AbstractAuthenticationDataPublisher} -  Publishing session creation 
TID: [-1234] [] [2018-04-24 07:25:03,321] DEBUG {org.wso2.carbon.identity.application.common.processors.RandomPasswordProcessor} -  Cache Key not found for Random Password Container 
TID: [-1234] [] [2018-04-24 07:25:03,321] DEBUG {org.wso2.carbon.identity.data.publisher.application.authentication.AbstractAuthenticationDataPublisher} -  Retrieving current IDPw for user  
TID: [-1234] [] [2018-04-24 07:25:03,321] DEBUG {org.wso2.carbon.identity.data.publisher.application.authentication.AbstractAuthenticationDataPublisher} -  Returning roles, adfs_idp_company1 
TID: [-1234] [] [2018-04-24 07:25:03,322] DEBUG {org.wso2.carbon.identity.data.publisher.application.authentication.AbstractAuthenticationDataPublisher} -  Publishing authentication success 

**Stack trace while not getting claims:**
 
TID: [-1234] [] [2018-04-24 07:32:19,061] DEBUG {org.wso2.carbon.identity.application.common.util.IdentityApplicationManagementUtil} -  JWT Header :{"typ":"JWT", "alg":"none"} 
TID: [-1234] [] [2018-04-24 07:32:19,061] DEBUG {org.wso2.carbon.identity.application.common.util.IdentityApplicationManagementUtil} -  JWT Body :{"iss":"wso2","exp":15245551390613000,"iat":1524555139061,"idps":[{"idp":"adfs_idp_company1","authenticator":"SAMLSSOAuthenticator"}]} 
TID: [-1234] [] [2018-04-24 07:32:19,061] DEBUG {org.wso2.carbon.identity.application.authentication.framework.config.ConfigurationFacade} -  Trying to find the IdP for name: adfs_idp_company1 
TID: [-1234] [] [2018-04-24 07:32:19,061] DEBUG {org.wso2.carbon.identity.application.authentication.framework.config.ConfigurationFacade} -  A registered IdP was found 
TID: [-1234] [] [2018-04-24 07:32:19,061] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Role claim uri is not configured for the external IDP: adfs_idp_company1, in Domain: company1sso. 
TID: [-1234] [] [2018-04-24 07:32:19,061] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultSequenceHandlerUtils} -  Getting Service Provider mapped roles of application: default of user: user2.pawar@carbon.super 
TID: [-1234] [] [2018-04-24 07:32:19,062] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultSequenceHandlerUtils} -  Service Provider Mapped Roles: null 
TID: [-1234] [] [2018-04-24 07:32:19,062] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  Executing claim handler. isFederatedClaims = true and remote claims = [MIDDLE_NAME:M,ID:user1.garg,LAST_NAME:Garg,EMAIL:user1.garg@domain.com,FIRST_NAME:user1,] 
TID: [-1234] [] [2018-04-24 07:32:19,062] DEBUG {org.wso2.carbon.identity.claim.metadata.mgt.dao.CacheBackedExternalClaimDAO} -  Cache hit for external claim list for dialect: http://wso2.org/oidc/claim in tenant: -1234 
TID: [-1234] [] [2018-04-24 07:32:19,062] DEBUG {org.wso2.carbon.identity.claim.metadata.mgt.dao.CacheBackedExternalClaimDAO} -  Cache hit for external claim list for dialect: http://wso2.org/oidc/claim in tenant: -1234 
TID: [-1234] [] [2018-04-24 07:32:19,062] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -   **Returning claims from claim handler = []** 

> log traces in case of missing claims 

 
TID: [-1234] [] [2018-04-24 07:32:19,063] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  UNFILTERED_IDP_CLAIM_VALUES map property set to [MIDDLE_NAME:M,ID:user1.garg,LAST_NAME:Garg,EMAIL:user1.garg@domain.com,FIRST_NAME:user1,] 
TID: [-1234] [] [2018-04-24 07:32:19,063] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  UNFILTERED_LOCAL_CLAIM_VALUES map property set to [http://wso2.org/claims/emailaddress:user1.garg@domain.com,http://wso2.org/claims/lastname:Garg,http://wso2.org/claims/middleName:M,http://wso2.org/claims/givenname:user1,] 
TID: [-1234] [] [2018-04-24 07:32:19,063] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} -  UNFILTERED_SP_CLAIM_VALUES map property set to [middle_name:M,given_name:user1,family_name:Garg,email:user1.garg@domain.com,] 
TID: [-1234] [] [2018-04-24 07:32:19,065] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  User user1.garg@carbon.super doesn't have an associated account. Hence continuing as the same user. 
TID: [-1234] [] [2018-04-24 07:32:19,065] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Step processing is completed. 
TID: [-1234] [] [2018-04-24 07:32:19,065] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultPostAuthenticationHandler} -  Post authentication handling for missing claims started 
TID: [-1234] [] [2018-04-24 07:32:19,065] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler} -  Concluding the Authentication Flow 
TID: [-1234] [] [2018-04-24 07:32:19,070] DEBUG {org.wso2.carbon.identity.application.common.processors.RandomPasswordProcessor} -  Cache Key not found for Random Password Container 
TID: [-1234] [] [2018-04-24 07:32:19,071] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache. ContextCache} -  Context ID : 5ca80cb9a0ca55483805300dbaa3a38d1162e79872f7b9ea3c1ecfe0cd352f86 :: idleSessionTimeOut : 900000, currentTime : 1524555139071, lastAccessedTime : 1524554737709 
TID: [-1234] [] [2018-04-24 07:32:19,071] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache.SessionContextCache} -  Found a valid session corresponding to the key : 5ca80cb9a0ca55483805300dbaa3a38d1162e79872f7b9ea3c1ecfe0cd352f86 
TID: [-1234] [] [2018-04-24 07:32:19,080] DEBUG {org.wso2.carbon.identity.data.publisher.application.authentication.AbstractAuthenticationDataPublisher} -  Publishing session update 
TID: [-1234] [] [2018-04-24 07:32:19,080] DEBUG {org.wso2.carbon.identity.application.common.processors.RandomPasswordProcessor} -  Cache Key not found for Random Password Container

**Comment by emswbandara** [comment]
This is a known issue. We have fixed this in later versions [1]. Please check with latest versions of Identity Server.

[1] https://github.com/wso2/carbon-identity-framework/pull/1495

**Comment by darshanasbg** [comment]
@GITOmpratap Could you please confirm you also experienced the same issue as the pattern mentioned in https://github.com/wso2/carbon-identity-framework/issues/1494?

**Comment by GITOmpratap** [comment]
Thank for contact.
Yes it is similar issues and we had resloved it with patch of wso2 5.5.0.

 Again thanks to wso2 Team.


Om pratap

**Comment by darshanasbg** [comment]
Great to hear that you were able to get it solved.. Thanks for confirming @GITOmpratap .. Closing as per the above comment..
