### ISSUE TITLE
Client Side support for SAML Artifact Binding

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3132]

**Comment by IndunilRathnayake** [comment]
Fixed with 
https://github.com/wso2/carbon-identity-framework/pull/1540
https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/63

**Comment by madawas** [comment]
Closing as the issue fixed with following PRs.
wso2/carbon-identity-framework#1540
wso2-extensions/identity-outbound-auth-samlsso#63
