### ISSUE TITLE
Subject Identifier of the first factor(basic) is not used in multi-factor authentication when conditional authentication is enabled

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#3133]
**Steps to reproduce**

1. Create a user.
2. Configure a service provider.
3. Configure multi-factor authentication with Twitter as the second factor.
4. Use the subject identifier from the first step.
5. Tick "use this script" and add a simple script under the Javascript based conditional step.
6. Update the application.

When you log into the sample application with the user successfully you'll see that user's Twitter ID will be returned as the subject ID, not the username.

**Comment by pulasthi7** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1554
