### ISSUE TITLE
Map roles upon Federated SAML to JWT ID Token exchange

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#3145]
**Description:**

Following are already available in WSO2IS.

1. In SAML grant type pass the SAML token to the token endpoint
2. In the returned JWT, we are including all the claims that were already in the SAML token.

Following modifications needed to be added to the above mentioned 1 and 2.

1.1. If it has roles (you can specify what is the role claim URI in the IDP UI in IS), then read the claim mapping in the IDP configuration
1.2. Return back the roles only which have a mapping. For examples, if we have a mapping foo --> foo1, bar --> bar1, and in the SAML token if it has foo, zee, return back only foo1 (the mapped role for foo), but not see (because there is no mapping) in the JWT

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
WSO2IS-5.3.0

**Comment by IndunilRathnayake** [comment]
This is provided as a WUM update for IS 5.3.0. it's better to fix this issue in public branch as soon as possible, to get it released in the next version.
