### ISSUE TITLE
Support for per-service provider ID token expiry time

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#3149]
Using **spTokenExpireTime** registry property, IS 5.3.0 supports service provider specific token expiry time for
1. user access token
2. application access token
3. refresh token
But not for **ID token**. This has to be improved.

**Comment by rushmin** [comment]
Sent the PR : https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/882

@ShirazAzad we need to amend documentation.  https://docs.wso2.com/display/IS560/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

**Comment by ShirazAzad** [comment]
Updated the doc [1] with the description and screenshot.
[1] https://docs.wso2.com/display/IS560/Configuring+OAuth2-OpenID+Connect+Single-Sign-On
