### ISSUE TITLE
Document of the effect of multi attribute separator foro OIDC/SAML

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3155]
> When building the id_token, the product consider , as the multi attribute separator and represent the value as a json array. You can change this behavior by making the following configuration in user-mgt.xml if the user is in primary user store (repository/conf directory) or in the relevant secondary user store manager configuration which user resides (repository/deployment/server/userstores or in the management console, 'Advanced' section in user store configuration UI). Please note that changing the user-mgt.xml will require a server restart.

```xml
<UserStoreManager class="org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager">
        ...
        <Property name="MultiAttributeSeparator">,,</Property>
        ...
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
