### ISSUE TITLE
Change in IS accountrecoveryendpoint webapp look and feel

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#3164]
There is a change in look and feel in one jsp window due to an extra tag.

**Comment by Dumindu-Kanchana** [comment]
@pulasthi7 Already fixed it.

**Comment by pulasthi7** [comment]
@Dumindu-Kanchana great! Please close the issue then.

**Comment by Dumindu-Kanchana** [comment]
Already fixed in the master branch with wso2/carbon-identity-framework#1566
