### ISSUE TITLE
authenticationendpoint web app cookie_policy.do page footer scrolls up and down.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#3170]
Mozilla firefox for ubuntu 59.0.2 (64bit) isn't working properly with the IS 5.5.0 Authenticationendpoint web app cookie_policy.do page.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
