### ISSUE TITLE
Problem with logging out of travelocity sample

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3172]
Steps to reproduce,

1. Configure SSO with travelocity
2. Login to travelocity application
3. Logout of the travelocity application
4. Login again and logout
5. If tried to login again, user is redirected to login home page.

When tracing the requests, instead of a logout request, travelocity sends a login request to IS.

Tried with,
- IS 5.5.0 and 5.6.0-M7
- Tomcat 9
- Java 1.8.0_171

**Comment by hauntingEcho** [comment]
I've seen this issue as well - it looks like the logout request is not actually even sent.  The user is just redirected to `/travelocity.com/`, which then redirects to IS with a login request.  See the attached screenshot.
![screen shot 2018-12-11 at 4 58 11 pm](https://user-images.githubusercontent.com/1661988/49837170-217d7c00-fd6b-11e8-9281-df9213c6d453.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
