### ISSUE TITLE
IS 5.3.0 WUM updated pack - wso2is-5.3.0.1526021724277 attributes in email templates (eg:- emailContentType) does not picked up

### ISSUE THREAD

**Issue by dnwick** [wso2/product-is#3174]
in email-admin-config.xml , even though attribute is emailContentType="text/plain" in UI it shows it as text/html. we need to make sure other attributes also getting picked up.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
