### ISSUE TITLE
User store xml getting corrupted when editing via UI multiple times

### ISSUE THREAD

**Issue by warunap** [wso2/product-is#3176]
When we add a secondary user store via UI and edit it multiple times, there is a chance it corrupts entries as following. Please note that additional **amp;**. This simply ruins any user login or other actions.

`<Property name="UserNameSearchFilter">(&amp;amp;(objectClass=user)(cn=?))</Property>
<Property name="GroupNameSearchFilter">(&amp;amp;(objectClass=group)(cn=?))</Property>`

**Comment by thanujalk** [comment]
This is already resolved with https://github.com/wso2/carbon-kernel/pull/1749
