### ISSUE TITLE
Certificate Revocation Validation with CRL and OCSP for X509 Authenticator

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3178]

**Comment by IndunilRathnayake** [comment]
Fixed with 
https://github.com/wso2-extensions/identity-outbound-auth-x509/pull/17
https://github.com/wso2-extensions/identity-x509-revocation/pull/1

**Comment by pulasthi7** [comment]
@IndunilRathnayake Can we close this now? Any pending work?

**Comment by IndunilRathnayake** [comment]
Feature for identity-x509-revocation added with : 
https://github.com/wso2-extensions/identity-x509-revocation/pull/3
https://github.com/wso2/product-is/pull/3245

**Comment by malithie** [comment]
Feature is included in https://github.com/wso2/product-is master branch x509 authenticator has been upgraded.
