### ISSUE TITLE
Include horizontal scrolling for text area of javascript based conditional authentication in SP 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3193]

**Comment by thusithak** [comment]
This has been solved with the introduction of the right side template docking. 
https://github.com/wso2/carbon-identity-framework/pull/1588

**Comment by thusithak** [comment]
Also note that the script editor soft-wraps its code (thus no need to have a horizontal scrollbar).
The soft-wrapping is only applied when inside the editor. Copied code will take its original column width.
