### ISSUE TITLE
Enabling setting custom parameters in the accessToken response

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#3194]
In our current implementation, access token response is hard coded and we can not set any custom parameters which be are setting in the token request.

This improvement should enable ability to set custom parameters to the access token response if any custom parameter is set in the request.

**Comment by malithie** [comment]
The improvement should include adding custom parameters to the token response over a custom grant handler only. Request parameters should not be incorporated to the token response directly.
