### ISSUE TITLE
Include more functions for script based conditional authentication

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3204]
Implement lockUserAccount,getLocalUser and associateUserAccount functions for script-based conditional authentication.
1. lockUserAccount(user)
locks the user account. Only the admin can unlock the account

2. getLocalUser(user,idp)
Get the local user. If it is a federation login, check whether the federated user is associated with a local user. If there is a user association then return the associated local user, if not return the local user.
Parameters:- user - federated user, idp - federated identity provider

3. associateUserAccount(localuser, fuser, fidp)
Associate the local user with the federated user.
Parameters:- fuser - federated user, fidp - federated identity provider

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
