### ISSUE TITLE
Application owners should obtain distinct tokens for user types APPLICATION and APPLICATION_USER

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#3205]
Problem scenario,

1. Create a user 'abc'
2. Login as user 'abc' and create auth application 'app1'
3. Obtain a access token for application 'app1' from client_credential grant type for scope=somescope
4. Now, same application for the same user 'abc' and same scope=somescope using password grant
5. Same access token in #3 will be returned

Token obtained in #3 is a APPLICATION token, while #5 should return a token of type APPLICATION_USER and they should be distinct.

**Comment by madurangasiriwardena** [comment]
Duplicates https://github.com/wso2/product-is/issues/3199
