### ISSUE TITLE
Conditional authentication script editor UI not aligned properly

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3207]
See the screenshot attached below.

![image](https://user-images.githubusercontent.com/1332991/40365136-922dbcfe-5df1-11e8-8f1f-307132f67c9e.png)

**Comment by thusithak** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1588
Tested for Mac/Ubuntu Chrome/ FF browsers
