### ISSUE TITLE
 Allow CORS for revoke endpoint as configuration.

### ISSUE THREAD

**Issue by ruks** [wso2/product-is#3212]
According to the doc[1], we need to edit the oauth2.war and it is not best practive to edit the war file need to support this as a cosnfiguration.

[1] https://docs.wso2.com/display/IS530/Invoking+an+Endpoint+from+a+Different+Domain

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
