### ISSUE TITLE
High validity period for the access token after the migration

### ISSUE THREAD

**Issue by rizmir22** [wso2/product-is#3213]
The customer receives high validity period for the access token (3600000s) for the access token which is created by using an application which is involved in the migration.

If we created an access token with a new application there is no issue and it is created with the default value (3600s).

It seems there is a problem with migration client. In the code [1] default value for the **applicationAccessTokenExpiryTime**  is 3600000. 
 

[1] https://github.com/wso2/product-is/blob/b210a95ba9c289b98c812d9ad493a4d5f279e594/modules/migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v540/migrator/OAuthDataMigrator.java

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2/product-is/pull/3221
