### ISSUE TITLE
New configurations for temp data cleanup should be documented.

### ISSUE THREAD

**Issue by nuwandiw** [wso2/product-is#3214]
There is a new configuration for Temporary authentication context data deletion. Following should go under **SessionDataPersist** tag.

```
               <TempDataCleanup>
                     <Enable>true</Enable>
                     <PoolSize>20</PoolSize>
                     <CleanUpTimeout>40</CleanUpTimeout>
               </TempDataCleanup>
```
Following details should be added to https://docs.wso2.com/display/IS560/Authentication+Session+Persistence

Enable - Enabling separated cleanup for temporary authentication context data

PoolSize - Maximum number of threads to be allocated for temp data deletion. When PoolZize > 0, temporary data which have no usage after the authentication flow will be deleted immediately. When PoolZise = 0, data will be deleted only by the scheduled cleanup task

CleanUpTimeout - All temporary authentication context data older than CleanUpTimeout value are considered as expired and would be deleted during cleanup task

related to https://github.com/wso2/product-is/issues/3202

**Comment by sherenewso2** [comment]
Documented in [1] 

[1] https://docs.wso2.com/display/IS560/Authentication+Session+Persistence
