### ISSUE TITLE
[Doc] Add More information on how to do artifact synchronization in deployment patterns

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#3220]
There needs to be more information on how to do artifact synchronization [1] in Identity Server artifact synchronization in following areas,

- Add references to different file sharing systems mentioned in [1] (ex-Network File System)
- Add samples on command to follow in provided 4 steps. (ex- do symlink)
- Add a reason for creating both 'Deployment' and 'Tenant' directories in selected file system

[1] https://docs.wso2.com/display/IS550/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Enablingartifactsynchronization

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
