### ISSUE TITLE
Disable script evaluation for sequencial steps

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#3224]
If the script is unchanged from auto-generated, need to save it as a normal flow to use default sequence handler

**Comment by nuwandiw** [comment]
UI level implementation is done. Hence reducing priority.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
