### ISSUE TITLE
The filter by role name doesn't return SCIM ID for the Service provider roles (created during the Service Provider creations).

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-is#3243]
Steps to reproduce

1. Create a service provider.(NewServiceProvider)

2. Filter for the group Application/NewServiceProvider by using the following commands.

curl -k --user admin:admin https://localhost:9443/wso2/scim/Groups?filter=displayName+Eq+%22Application/NewServiceProvider%22

Results

{"totalResults":
1,"schemas":
["urn:scim:schemas:core:1.0"],"Resources":
[{"displayName":"Application/NewServiceProvider"
}
]}

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2-support/carbon4-kernel/pull/415

**Comment by dilin993** [comment]
Tested with wso2is-5.6.0-rc2, issue has been fixed.

**Comment by madurangasiriwardena** [comment]
This seems to be not working with 5.6.0, but working with 5.7.0
