### ISSUE TITLE
default mismatch between authentication frontend & server - self-sign-up & recovery

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3247]
**current behavior**
By default, [self-sign-up](https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation) & [recovery](https://docs.wso2.com/display/IS550/Account+Recovery) are both disabled in Identity Server 5.5.0.  However, they are active in the user interface (as configured in `EnableSelfSignUpEndpoint` and `EnableRecoveryEndpoint` in [identity.xml](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L608)).  This leaves several dead UI paths.

**desired behavior**
The default behavior matches between the backend & frontend.

**Comment by Abilashini** [comment]
Self-sign up and account recovery are enabled by default at the server level(in identity.xml). Those operations will be enabled with the tenant level configurations in the resident IdP. If not those operations in the login UI will end up with respective error messages. If self-sign up and account recovery are not needed, those can be disabled in the identity.xml which removes those operations from the login UI.

**Comment by hauntingEcho** [comment]
I guess my proposal is more that either the resident IdP should have this enabled by default (which may not be feasible, since it requires email configuration) or it should be disabled by default in identity.xml.  As it stands, the default configuration leads to non-functional links on the login page, which is a bit of a gotcha for new deployments.

**Comment by DMHP** [comment]
@hauntingEcho 
Thanks for your suggestion. We do understand you requirement. Enabling above features can be done via management console without a restart. If we make the property in identity.xml as false then it requires a server restart. Anyway we cant make these properties consistant between the identity.xml and the the resident IDP UI as it differs from tenant to tenant.

I am closing the above issue. Please do re-open if you have any other concerns.
