### ISSUE TITLE
Update all the grant handlers to support the property "EXPIRY_TIME_JWT"

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#3253]
"EXPIRY_TIME_JWT" property is introduced to support handling the expiry time of generated self contained access token based on incoming assertions.

If "EXPIRY_TIME_JWT" is set, when setting the expiry time for JWT token, minimum of (configuration based expiry time, value of "EXPIRY_TIME_JWT") will be set as expiry time of JWT token. 

Relevant grant handlers are expected to set this property

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
