### ISSUE TITLE
Improve JWT Bearer Grant type to handle the local user scenarios.

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#3257]
If the JWT token generated by resident IDP provider is provided, the JWT bearer grant handler should be improved to handle it as local user. Currently all the scenarios are handled in a federated manner.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
