### ISSUE TITLE
some dependencies missing from Central

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3263]
Many, but not all, WSO2 packages are available via maven central as well as via maven.wso2.org.  It would be much appreciated if the remaining packages were added to central.  Many Orbit packages are missing, particularly Hazelcast 3.5.4.wso2v2

use case -
CI-built/maintained [customization of the authenticationendpoint](https://docs.wso2.com/display/IS550/Customizing+Login+Pages+for+Service+Providers), using an existing internal Nexus repository proxying/mirroring Central.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
