### ISSUE TITLE
Missing "sp" or "application" request params to use in AuthenticationEndpointFilter

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3266]
Some of the requests doesn't contains SP information to process in AuthenticationEndpointFilter to redirect to the pages in custom authentication endpoints rather for default authentication endpoint.
Ex: oauth2_error.jsp

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/184,
https://github.com/wso2/carbon-identity-framework/pull/1661

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/907
