### ISSUE TITLE
[Improvement] Add debug logs such that a user could track the end to end flows for 'ClaimMetadataManagementService' operations.

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-is#3267]
*Issue Description*

Currently enabling debug logs for 'org.wso2.carbon.identity.claim.metadata.mgt' package doesn't provide sufficient logs to understand/track end to end flows of the claim management operations such as;
* addClaimDialect
* addLocalClaim
* addExternalClaim
* getLocalClaims

*Issue Type:* Improvement

*Version:* Identity server 5.5.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
