### ISSUE TITLE
lock SP's SAML NameIDFormat to "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" until other options are functional (#2110)

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3271]
Currently the behavior of the SAML NameID field is not being updated to match a Service Provider's specified NameIDFormat (#2110) - until this is resolved, the option to use broken implementations should be removed & the value of NameIDFormat should be locked to "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified".

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
