### ISSUE TITLE
Authentication error in JavaScript based conditional authentication sample

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#3274]
When accessing the app (http://wso2is.local:8080/travelocity.com) with JavaScript-based conditional authentication configuration [1], got the authentication error. It works when accessing the index page directly on http://wso2is.local:8080/travelocity.com/index.jsp.  

Error stack: 
![image](https://user-images.githubusercontent.com/11737221/41040191-47166b02-69b9-11e8-9cfc-cf18b6c4e37e.png)

[1] [https://docs.wso2.com/display/IS560/Conditional+Authentication#ConditionalAuthentication-Scenariotwo-multipleauthenticationstepsareenforcedforuserswithan'admin'role.](url)

**Comment by senthalan** [comment]
If you are trying at IS 5.6.0-beta, you need to change the StepBasedSequenceHandler and StepHandler. Because we have disabled the script based authentication by default. 

```
<StepBasedSequenceHandler>org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler</StepBasedSequenceHandler>
  <StepHandler>org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.GraphBasedStepHandler</StepHandler>
```


And the script also has to be changed due to https://github.com/wso2/carbon-identity-framework/pull/1605
```
function onInitialRequest(context) {
   executeStep(1,{
       on: {
           success: function (context) {
               var user = context.steps[1].subject;
               var isAdmin = hasRole(user, 'admin');
               Log.info("--------------- Has Admin " + isAdmin);
               if (isAdmin) {
                   executeStep(2);
             executeStep(3);
               }
           }
       }
   });
}

```


Documentation have to be updated.

**Comment by Abilashini** [comment]
note: In order to activate JavaScript-based conditional authentication, have started the server with '-DenableConditionalAuthenticationFeature' tag and used the latest script. 

The issue is when accessing the URL of the sample app with JavaScript-based conditional authentication configuration enabled, is not redirecting to the index page and end up with an authentication error.

**Comment by pulasthi7** [comment]
This flag is now removed and this works out-of-the-box now. Hence closing the issue
