### ISSUE TITLE
[Doc] IS 5.5.0 missing from browser compatibility page

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3284]
Identity Server 5.5.0 is missing from the [Tested Web Browsers](https://docs.wso2.com/display/compatibility/Tested+Web+Browsers) documentation page

**Comment by omindu** [comment]
@hauntingEcho Thank for reporting this. We will update the document with the compatibility information.

**Comment by sherenewso2** [comment]
Updated [1] 

[1] https://docs.wso2.com/display/compatibility/Tested+Web+Browsers
