### ISSUE TITLE
dedicated log for user activities

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-is#3291]
have a separate dedicated log for user activities related token with grant_type password or any other grant that validate user credentials?
have a separate dedicated log for user activities related access to the Management console?
have a separate dedicated log for user updates triggered via Management console?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
