### ISSUE TITLE
Allow two certificate for a identity provider

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3295]
Currently, only one certificate can be added through identity provider. Need to allow two certificates to be uploaded to the identity provider.

**Comment by Pushpalanka** [comment]
Hi team,

Can you please shed some light on what is the use case/s supported by this? Isn't an IDP is expected to be identified by one private key only that will map to one public key? By letting two or more public keys to be added, I think we assume one IDP can have two private keys, in which case the ideal approach would be to have two IDPs defined mapping to each. Appreciate some insights into when to use case this feature.

**Comment by DMHP** [comment]
@Pushpalanka This feature is used in the certificate rollover scenario. When the IDP is going to change the certificates they will give a grace period to use both the certificates for sometime. In such cases this multiple certificate use case can be utilized.

**Comment by Pushpalanka** [comment]
Thanks @hasanthiP for the details.
