### ISSUE TITLE
Support bulk deleting users with username in scim

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#3309]
Currently, we cannot bulk delete users passing the usernames of the users. We need to pass the user id. It will be useful if we can delete users using the username as well.

Also, include a sample request in the documentation [1] for bulk user deletion 

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+SCIM+2.0+Provisioning+Connector#ConfiguringSCIM2.0ProvisioningConnector-/BulkEndpoint

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
