### ISSUE TITLE
Dispatch sample app login as null user for failures

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#3311]
Following is observed for idp failures

![image](https://user-images.githubusercontent.com/1415573/41588857-87487938-73d0-11e8-825f-c0fb0e0dbe04.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
