### ISSUE TITLE
Claims not retrieved in the JWT token when having a "." in the claim URI in oidc claim dialect

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#3313]
**Steps to reproduce**
1. Add the following claims in the http://wso2.org/oidc/claim dialect
- org/division
- http://wso2.org/oidc/claim/division
2. Map the same URI's in  registry "/_system/config/oidc" under property "openid".
3. Create a Service Provider and configure the claims accordingly
4. Fill the values of the claims in the user profile of the user
5. Retrieve the id token (as below) and decode to it to get the JWT token

`curl -v -X POST --basic -u <clientID>:<secret> -H 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' -k -d 'grant_type=password&username=admin&password=admin&scope=openid' https://localhost:9443/oauth2/token`

**Issue**
The claim for "http://wso2.org/oidc/claim/division" is not retrieved as it is having a "." in the claim URI.

**Pack**
wso2is-5.5.0.1528222430880

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/901
