### ISSUE TITLE
Introducing filters for Groups and Users listing in identity server with SCIM2

### ISSUE THREAD

**Issue by shyabithd** [wso2/product-is#3314]
The current version of WSO2 identity server supports filtering criteria's only with Equal operator for listing users. This feature introduces new operators such as Begin with, End with and Contains for filtering and extended to filter groups as well.

**Comment by pulasthi7** [comment]
@shyabithd @emswbandara Is this fixed now with above PRs?

**Comment by shyabithd** [comment]
Hi pulasthi, Yes changes related to this has already been merged hence we can close this.
