### ISSUE TITLE
Signature verification of ID token hint fails in OIDC single logout for tenants.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#3317]
Signature verification of ID token hint fails in OIDC single logout for tenants.

**Comment by nuwandiw** [comment]
The issue get fixed when **Use tenant domain in local subject identifier** is enabled or **SignJWTWithSPKey** is set to true. Created doc jira [1] for documentation.

[1] https://github.com/wso2/product-is/issues/3604
