### ISSUE TITLE
[Doc] Include information/steps on how logout flow works with playground in 'Basic Client Profile with Playground' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#3323]
'Basic Client Profile with Playground' doc [1] explains on how a user can follow through with travelocity.com and it needs to be update with information regarding to logging out operations (ex-Redirect to a logout URL after RP-initiated logout section in [2]).

Also the images need to be updated because the current images in the doc doesn't have the 'logout' button (when scope set to 'openid', there's a logout button there) in 'Get Access Token' page and 'Get User Info' page.

[1] https://docs.wso2.com/display/IS530/Basic+Client+Profile+with+Playground
[2] https://docs.wso2.com/display/IS530/Session+Management+with+Playground

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
