### ISSUE TITLE
Provide a signature validation fall back policy to be selected by the user when using multiple idp certificates

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-is#3324]
Signature validation fallback policy to be selected by the user, so that if the signature validation fails the selected policy should be executed. Suppose there are two policies defined as:

1. Sequential selection policy.
2. Primary cert expiration policy. 

Sequential selection policy will select the secondary cert if the signature validation fails with the primary cert.  In the primary cert expiration policy if the primary cert is expired then the cert should be deprecated and should not use to validate the requests.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
