### ISSUE TITLE
Emails are not sent for new users created in tenants with askPassword enabled after a migration

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#3329]
Emails are not sent for new users created in tenants with askPassword enabled after a migration.

**Steps**
1. Migrate from IS 5.0.0 to 5.3.0 when there are tenants in IS 5.0.0 with askPassword enabled 

**Issue**
The eventstreams and eventpublishers directories will not be created in old tenants from the migration scripts. Hence, notifications will not be triggered when new users are created in old tenants.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
