### ISSUE TITLE
Issue in the  Use IDP JWKS endpoint and Upload IDP certificate

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3331]
When we first upload IDP the certificate and update following UI was shown
![1](https://user-images.githubusercontent.com/20336761/41913812-f0449914-796e-11e8-8d78-b3c026e77566.png)

While editing the IDP if I switch to Use IDP JWKS endpoint following UI will be shown
![2](https://user-images.githubusercontent.com/20336761/41913856-1518785a-796f-11e8-8eb3-271e85f95b34.png)

Without doing anything if I switch to Upload IDP certificate then previously uploaded IDP certificate is not listed. 
![3](https://user-images.githubusercontent.com/20336761/41913909-4370e41c-796f-11e8-84bd-7f365928a8eb.png)
After closing the window and edit the IDP again only, I could see the uploaded certificate

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
