### ISSUE TITLE
Requested claims are missing when "Subject Claim URI:" is not selected

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#3332]
**Description:**
$subject
Fix: https://github.com/wso2-extensions/identity-inbound-auth-oauth/commit/89db22a3fa4741a662ffaf16eaeecfecb3cf52cd#diff-2279172db0d5fdaeff54eee493c2a4afR133

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
5.2.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by pulasthi7** [comment]
@darshanasbg  Is this fixed in public?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
