### ISSUE TITLE
Improve the code comment when validating the host name of the authentication request initiator against the IS server host

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#3335]
**Description**
When the authentication request is initiated from the same host as the IS server, then the KDC will not issue a Kerberos token, hence IWA using Kerberos will not work. Therefore the IS server will validate whether the initiator and the IS is in the same host and if so return the error message "Cannot handle IWA authentication request from the same host as the KDC).

The following comment provided in the code is misleading and it does not reflect the correct behaviour. This need to be corrected appropriately.
```
 // we cannot handle this since the Identity Server and Kerberos Server are running on the same host
```

[1] https://github.com/wso2-extensions/identity-local-auth-iwa-kerberos/blob/master/components/org.wso2.carbon.identity.application.authenticator.iwa/src/main/java/org/wso2/carbon/identity/application/authenticator/iwa/servlet/IWAServlet.java#L68

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
