### ISSUE TITLE
After enabling re-captcha for SSO, login to user dashboard fails even for correct credentials

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#3337]
Product version - 5.5.0

Reproducing steps
--------------------------
1. Enable the recaptch for SSO
2. Try to login with the wrong password for 4 times(i.e.If we add the value as 3 in UI, it only shows the recaptcha after 4th time) to enable the recaptcha.
3. Try to login to the same account 5th time with the correct password, after entering the captcha.
4. It fails and goes on a loop. 
5. Cannot login after that.

In addition to that, this issue https://github.com/wso2/product-is/issues/3310 also need to be fixed along with this.

**Comment by pulasthi7** [comment]
Hi @Megala21 @IsuraD Is this also reproducible in current development branches?
