### ISSUE TITLE
Groups created in Carbon UI are not visible using SCIM2 API

### ISSUE THREAD

**Issue by domeniquemulder** [wso2/product-is#3340]
Affecting: multiple version of WSO2 IS 5.x

When creating a role in Carbon UI user management the role is not available as a group over SCIM2 API (GET /scim2/Groups).

Using the SCIM2 API to get all users and group memberships (GET /scim2/Users) the group is visible. There is a slight difference:

```
        {
            "meta": {
                "created": "2018-06-29T11:07:52Z",
                "lastModified": "2018-06-29T11:07:52Z"
            },
            "name": {
                "familyName": "user1"
            },
            "groups": [
                {
                    "display": "manager",
                    "value": "4ac7a870-9dd7-4bbb-9a5c-fb39cd04a4c2"
                },
                {
                    "display": "testRole2"
                }
            ],
            "id": "7a7c6e7f-92aa-4971-b4aa-463a9c9690c4",
            "userName": "user1"
        },
```

Role "manager" is created using the SCIM2 API. 
Role testRole2 is created using CarbonUI.

As you can see the testRole2 is missing the "value" parameter hence we can not manage the memberships of the group/role over SCIM2.

**Comment by omindu** [comment]
Hi @domeniquemulder,

Can you specify the exact product version you have used for this ? eg: 5.5.0 ?

**Comment by domeniquemulder** [comment]
Hi Omindu,

I've tested this on:

- WSO2 IS 5.4.0
- WSO2 IS 5.4.0.1529685331806 (WUM update until today)

- WSO2 IS 5.5.0
- WSO2 IS 5.5.0.1529949139950 (WUM update until today)

The process I test is:

1. Download & Start WSO2 IS

2. Create a new group using SCIM API

`curl -k --user admin:admin --data '{"displayName":"manager2"}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups`

3. Go to carbon console, create a new group (testRole2) using "Users & Roles - Add role"

4. GET groups using SCIM2 API
`curl -v -k --user admin:admin https://localhost:9443/scim2/Groups/`

`{
    "totalResults": 2,
    "startIndex": 1,
    "itemsPerPage": 2,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "displayName": "PRIMARY/manager2",
            "meta": {
                "created": "2018-06-29T15:27:18Z",
                "location": "https://localhost:9443/scim2/Groups/fde41a40-90f2-414e-9f4e-aa9a2610bd2e",
                "lastModified": "2018-06-29T15:27:18Z"
            },
            "members": [
                {
                    "display": "admin",
                    "value": "fc016bc6-c283-4408-b1c9-d38c608fe86b"
                }
            ],
            "id": "fde41a40-90f2-414e-9f4e-aa9a2610bd2e"
        },
        {
            "displayName": "PRIMARY/admin",
            "meta": {
                "created": "2018-06-29T15:26:27Z",
                "location": "https://localhost:9443/scim2/Groups/177e923d-aea8-424e-84c5-807e86f9da5e",
                "lastModified": "2018-06-29T15:26:27Z"
            },
            "members": [
                {
                    "display": "admin",
                    "value": "fc016bc6-c283-4408-b1c9-d38c608fe86b"
                }
            ],
            "id": "177e923d-aea8-424e-84c5-807e86f9da5e"
        }
    ]
}`

> As you can see the testRole2 is NOT in the response

5. Add user admin to all roles using Carbon Console " "Users & Roles - list users - assign roles"

6. GET all users using SCIM2 API

`curl -v -k --user admin:admin https://localhost:9443/scim2/Users`

`{
    "totalResults": 1,
    "startIndex": 1,
    "itemsPerPage": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "meta": {
                "created": "2018-06-29T15:26:27Z",
                "lastModified": "2018-06-29T15:26:27Z"
            },
            "name": {
                "givenName": "admin",
                "familyName": "admin"
            },
            "groups": [
                {
                    "display": "testRole2"
                },
                {
                    "display": "manager2",
                    "value": "fde41a40-90f2-414e-9f4e-aa9a2610bd2e"
                }
            ],
            "id": "fc016bc6-c283-4408-b1c9-d38c608fe86b",
            "userName": "admin"
        }
    ]
}`

> As you can see the user Admin is assigned to both groups. But the create role/group using the Carbon console is missing the "value" field.

**Comment by domeniquemulder** [comment]
I assume this is related to a known issue in IS: 

https://github.com/wso2/product-is/issues/3093

**Comment by omindu** [comment]
Hi @domeniquemulder ,

Can you check whether you have enabled the scim 2.0 listener in the product. In 5.5.0 scim 1.0 is enabled by default and scim 2.0 is disabled.

You can find the steps to enable scim 2.0 in 5.5.0 at [1]. Check the section **Enabling SCIM 2.0**.

[1] - https://docs.wso2.com/display/IS550/SCIM+2.0+REST+APIs

**Comment by omindu** [comment]
Also the 2 issues you have mentioned are not related to this case, they occur when we plug an existing user store to the product. If the group is created through Identity Server (Carbon UI or SCIM API) there shouldn't be an issue.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
