### ISSUE TITLE
[Doc] [IS 5.5.0] example listed for "/scim2/Users/.search" is actually for "/scim2/Users"

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3345]
The example [here](https://docs.wso2.com/display/IS550/apidocs/SCIM2-endpoints/index.html#!/operations#UsersEndpoint#getUsersByPost) for a filtered user search is actually using a different endpoint.  Further, it doesn't document anything about the body parameter.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
