### ISSUE TITLE
Create OAuth application using management console broken in the latest WUM updated pack

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#3348]
Pack: IS 5.5.0 as Key Manager WUM updated pack (Timestamp: 1530271598324)

Steps to reproduce:
* Create a Service Provider
* Configure OAuth2/OIDC inbound authentication

Application creation fails with an error,
![image](https://user-images.githubusercontent.com/5237653/42206878-01a61036-7edb-11e8-89d4-b07d4f525042.png)

If you try to retry, then it also fails with an error,
[2018-07-03 16:07:08,875] ERROR {org.wso2.carbon.identity.oauth.OAuthUtil} -  Error when adding the application. An application with the same name already exists.

This means the application that was created initially was done partially or was not rolled back properly.

Tried creating the App using dynamic client registration endpoint. It worked fine.

**Comment by pulasthi7** [comment]
Closing as this is not reproducible in latest builds
