### ISSUE TITLE
Confirmation mail sent to users created using askPassword contains placeholders

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#3349]
When creating users using askPassword option [1] from Management Console, the email sent to the user 
contains placeholders which are not replaced with actual values similar to following.

```
Hi {{user.claim.givenname}},

            Please change your password for the newly created account : cathy. Please click the link below to
            create the password.

            https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation=7c993c05-eadc-403b-8db9-8392d0cdc475&userstoredomain=PRIMARY&username=test&tenantdomain=carbon.super
            If clicking the link doesn't seem to work, you can copy and paste the
            link into your browser's address window.
```

The reason is, there is no value for the user.claim.givenname, since we can only provide the username in the management console UI.

So as a fix we can use username claim instead given name claim in the confirmation mail template. e.g. {{user.claim.username}}

[1] https://docs.wso2.com/display/IS530/Creating+Users+Using+the+Ask+Password+Option

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
