### ISSUE TITLE
more-specific return type for Charon3.core:JSONDecoder.decodeResource

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3350]
mirroring the issue request here because it gets much more attention than Charon - 

`JSONDecoder.decodeResource` currently returns a SCIMObject, but can be made much more type-safe without further code changes - `public <T extends AbstractSCIMObject> T decodeResource(String scimResourceString, ResourceTypeSchema resourceSchema, T scimObject)`

https://github.com/wso2/charon/issues/114
https://github.com/wso2/charon/pull/115

**Comment by omindu** [comment]
Fix committed with https://github.com/wso2/charon/commit/515002ab5b16de52035b564d0c6997cbfa43db5c
