### ISSUE TITLE
Need to have a way to filter the roles when we have a SP role mapping configured.

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#3351]
If a user has so many roles need to have a way to only the mapped roles to be included in the SAML response. But even though we do a role mapping it will receive a SAML response with all the available roles not only the roles that we handled especially via role mapping.

**Comment by DMHP** [comment]
Re-opening the issue as this framework level fix won't affected to the grant types which don't go through the framework. Ex: password grant type. So the fix should be ported to OAuth component as well.
