### ISSUE TITLE
Document "Monitoring Workflow Requests" does not contain description for the request types

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#3355]
**Related document:**
 "https://docs.wso2.com/display/IS550/Monitoring+Workflow+Requests"

**Issue Description:**
There are two types of request types in the filter ("My task" and  "All task") and "My task" filter does not show any of the request list even though the user already perform a task in the workflow. If the document can provide the exact description for the requested types, will be able to clarify the mentioned behavior.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
