### ISSUE TITLE
Captcha is not working properly when server restart in SSO flow for a failed user before the restart

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#3359]
Steps to reproduce:
- Take IS 5.3.0 WUM pack and Enable captcha for SSO flow, 

-  Login into dashboard with username and wrong password. 

-  Once you see captcha is visible, restart the server

-  Try to log in using the previous login user who failed with correct username and password.

- You will be re-directed to a page as follows:
![errorcaptcha](https://user-images.githubusercontent.com/9637873/42301803-ef1305ea-8034-11e8-9d4d-82e373a7fa68.png)

But we should be re-directed to the login page with re-captcha, as he was already a failed user before the server restart.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
