### ISSUE TITLE
Document a SSO tutorial with independent user stores

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#3360]
Scenario: 
A company uses four applications (A, B, X, and Z) and wants to configure SSO for these applications separately as indicated below. 

SSO Group 1 - app A and app B use user store1
SSO Group 2 - app X and app Z use user store2 

Users in user store1 should not be able to log in to apps in SSO group 2 and users in user store2 should not be able to log in to apps in SSO group 1.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
