### ISSUE TITLE
[IS 5.6.0] [SCIM2] "406 Not Acceptable" returned when "Accept: application/scim+json" header included

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3374]
when attempting to query a local installation of WSO2 IS with the SCIM endpoints' security disabled via `curl -v -k -H "Accept: application/scim+json" https://localhost:9443/scim2/Users?filter=userName+eq+admin`, the server returns a 406 error (stating that it cannot send back `application/scim+json` content) and no response body.  However, when the `Accept` header is set to `*/*`, the response is:
```
< HTTP/1.1 200 OK
< Cache-Control: private
< Expires: Wed, 31 Dec 1969 18:00:00 CST
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Fri, 06 Jul 2018 22:00:14 GMT
< Content-Type: application/scim+json
< Content-Length: 375
< Server: WSO2 Carbon Server
< 
* Connection #0 to host localhost left intact
{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"meta":{"created":"2018-06-27T11:12:31Z","lastModified":"2018-06-28T15:37:38Z"},"name":{"givenName":"admin","familyName":"admin"},"groups":[{"display":"Application/impression-DS"}],"id":"a450e086-ce5e-4e38-b048-d397e6190ac3","userName":"admin"}]}
```

Interestingly enough, the response when the `Accept` header is `application/*` is:
```
< HTTP/1.1 406 Not Acceptable
< Cache-Control: private
< Expires: Wed, 31 Dec 1969 18:00:00 CST
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Fri, 06 Jul 2018 21:59:20 GMT
< Content-Type: application/scim+json
< Content-Length: 115
< Server: WSO2 Carbon Server
< 
* Connection #0 to host localhost left intact
{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","detail":"application/* is not supported.","status":"406"}
```

since the response will have a `Content-Type` of `application/scim+json`, both of these should be fine.  This is causing me an issue, as `scim2-sdk-client` by default sends an `Accept` header of `application/scim+json,application/json`, which should also match correctly.

**Comment by hasinthaindrajee** [comment]
Fixed with https://github.com/hasinthaindrajee/charon/commit/76b850cad20a7dc5d952e07616af40d24aa89fba
