### ISSUE TITLE
[IS 5.5.0] [SCIM2] filter attributes should not be case-sensitive

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3375]
per [Section 3.4.2.2 of RFC 7644](https://tools.ietf.org/html/rfc7644#section-3.4.2.2):
```
Attribute names and attribute operators used in filters are case
   insensitive.  For example, the following two expressions will
   evaluate to the same logical value:

   filter=userName Eq "john"

   filter=Username eq "john"
```

however, when attempting to query a local installation of WSO2 IS 5.5.0:
* `curl -k https://localhost:9443/scim2/Users?filter=username+eq+admin` returns `{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","scimType":"invalidValue","detail":"Not a valid attribute name/uri","status":"400"}`
* `curl -k https://localhost:9443/scim2/Users?filter=userName+eq+admin` returns `{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"meta":{"created":"2018-06-27T11:12:31Z","lastModified":"2018-06-28T15:37:38Z"},"name":{"givenName":"admin","familyName":"admin"},"groups":[{"display":"Application/impression-DS"}],"id":"a450e086-ce5e-4e38-b048-d397e6190ac3","userName":"admin"}]}`

this can cause some compatibility issues with SCIM2 client libraries.

**Comment by hauntingEcho** [comment]
thanks!  Is there currently an estimate for 5.6's final release?

**Comment by omindu** [comment]
The official 5.6.0 GA release announcement will be on 16th July.

**Comment by hauntingEcho** [comment]
this is still failing for me in 5.6.0:
* `curl -k https://localhost:9443/scim2/Users?filter=userName+eq+admin` returns `{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":[{"type":"other","value":"admin@wso2.com"}],"meta":{"created":"2018-07-16T17:51:30Z","lastModified":"2018-07-16T17:51:30Z"},"name":{"givenName":"admin","familyName":"admin"},"groups":[{"display":"Application/local-8443"}],"id":"f2d980d6-cd5f-4c2d-890f-94bc9cf39705","userName":"admin"}]}`
* `curl -k https://localhost:9443/scim2/Users?filter=username+eq+admin` returns `{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","scimType":"invalidValue","detail":"Not a valid attribute name/uri","status":"400"}`
