### ISSUE TITLE
Incorrect statement in documentation about IS rest apis

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3376]
documentation [1] mentions that "From 5.4.0 onwards, the functionality provided by these SOAP APIs are provided through REST APIs." and below points

- Calling Admin Services
- User Management with APIs
- User Information Recovery Service
- Identity Application Management API
- Identity Provider Management API

Problem with this is,

- We don't have rest apis for most of these soap services. We have some user management functionalities with SCIM and User Information Recovery
- It does not make sense to have "Calling Admin Services" in this list when the above mentioned statement is there.

[1] https://docs.wso2.com/display/IS550/SOAP+APIs

**Comment by samgnaniah** [comment]
This is fixed now [1].

[1] - https://docs.wso2.com/display/IS550/SOAP+APIs
