### ISSUE TITLE
Separate keystore to be used for internal data encryption

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3380]
This is issued as a WUM update for IS 5.5.0, need to include this into IS 5.6.0 as a WUM update.

**Comment by IndunilRathnayake** [comment]
@rushmin: is this included in the public branch?

**Comment by rushmin** [comment]
@IndunilRathnayake Yes, it is. Closing the ticket.

[1] - https://github.com/wso2/carbon-kernel/issues/1789
[2] - https://github.com/wso2/carbon-kernel/pull/1818
