### ISSUE TITLE
[IS 5.6.0] return 301 to https when http is attempted

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3385]
currently, when attempting to access an Identity Server instance via HTTP, garbage data is returned (`�P`).  Instead, a 301 redirect to the HTTPS version of the same page should be returned, ideally with an HSTS header.

For example, `http://localhost:9443/dashboard` should redirect to `https://localhost:9443/dashboard`

**Comment by madurangasiriwardena** [comment]
No longer valid since the dashboard is shipped with the product anymore.
