### ISSUE TITLE
Typo in the stored producedure. 

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#3387]
![typo](https://user-images.githubusercontent.com/791850/42475137-aef98d18-83c1-11e8-91f1-56f529739604.png)

Let's correct. :)  https://docs.wso2.com/display/IS530/Removing+Unused+Tokens+from+the+Database 
Other versions may be affected too.

**Comment by Nashaath** [comment]
Fixed in IS doc versions 5.1.0 through 5.3.0. Those were the only affected versions.

Thanks for reporting :)
