### ISSUE TITLE
Documentation for Deployment Pattern 1 might be lacking some steps

### ISSUE THREAD

**Issue by danAtInv** [wso2/product-is#3389]
I am trying to configure Identity Server v5.6.0 (I know it's in RC3 as of this writing) for ["Deployment Pattern 1"](https://docs.wso2.com/display/IS560/Setting+Up+Deployment+Pattern+1).

The documentation seems to be missing some configuration Steps.  One difference is that I am deploying to an Openshift / Kubernetes environment and the Identity Server nodes are running in a docker container.  They point to a single database instance in AWS.  The load ingress and load-balancing are handled by Openshift.

1. Configure Tomcat RemoteIPValve in repository/conf/tomcat/catalina-server.xml.
Reason: Without this configuration, I get infinite redirects from:
`https://<proxy_host>/carbon/admin/index.jsp`
 ... to
`https://<proxy_host>:443/carbon/`
 ... which the browser rewrites to
`https://<proxy_host>/carbon/`
 ... infinitely until you get a "too many redirects" error.

The valve config I used is as follows:
```
                <Valve
                    className="org.apache.catalina.valves.RemoteIpValve"
                    internalProxies="reg_ex_for_internal_docker_IPs"
                    remoteIpHeader="x-forwarded-for"
                    proxiesHeader="x-forwarded-by"
                    protocolHeader="x-forwarded-proto"
                />

```

2. When running in a dev-environment where the proxy has a self-signed certificate not signed by a CA, I had to import the certificate into repository/resources/security/client-truststore.jks
Reason: Without this, when attempting to login to the self-serve dashboard (/dashboard), you get the error:
`JavaException: org.jaggeryjs.scriptengine.exceptions.ScriptException: SSL peer failed hostname validation for name: null (/dashboard/controllers/wsUtil.jag#76)`
I suspect that if the certificate was trusted by a CA, this error wouldn't occur, but I haven't gotten that far yet.  Regardless, our certs in dev environment are likely to be self-signed.

**Comment by pulasthi7** [comment]
@sherenewso2 , Can we get these added to doc space. IIRC (2) is already included, better check and confirm.

**Comment by sherenewso2** [comment]
I added point 1 to the deployment doc [1] as a tip to follow when using Openshift Docker for deployment. 

Point 2 is already given as an instruction in step 5 under "Create SSL certificates" section 

[1] https://docs.wso2.com/display/IS560/Setting+Up+Deployment+Pattern+1
[2] https://docs.wso2.com/display/IS560/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-CreateSSLcertificates
