### ISSUE TITLE
[IS 5.6.0] dashboard widgets enabled by default, which do not work out-of-the-box

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3396]
per #2622, "Monitor Users Login Sessions" does not work out-of-the box.  To minimize surprises when setting up a new instance, it may make more sense for this to be enabled as part of configuring Analytics or to detect whether analytics has been configured rather than having the non-functional widget visible to admin end-users.

**Comment by hauntingEcho** [comment]
confirmed present in 5.6.0 as well

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
