### ISSUE TITLE
Mismatch between service WSDL and Stub wsdl file of RemoteTenantManagerService

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#3398]
This WSDL https://github.com/wso2-extensions/identity-user-ws/blob/v5.1.4/components/org.wso2.carbon.um.ws.api.stub/src/main/resources/RemoteTenantManagerService.wsdl#L149-L158 is not a match with the WSDL exposed by the actual service.

**Comment by thanujalk** [comment]
Reverted this due to a compilation failure https://github.com/wso2-extensions/identity-user-ws/pull/29

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
