### ISSUE TITLE
Introducing New Claim Properties to Control Claims Shown in Different Views

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#3412]
The way we select the claims shown in following views is based on a single property which is "supported by default".  It is not possible to control the behavior of a claim individually for each of these views and causing some major usability issues.  Need a way to individually configure each view rather than just based on the "supported by default" property.

1. Admin user profile view in the management console
2. My user profile view in the user portal
3. Self sign-up view

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
