### ISSUE TITLE
[Doc] Potential improvement in file-based SP configuration 

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#3420]
The subsection 'Adding the service provider in the service provider IS' in the document [1] contains the configuration of **travelocity.com.xml** which has a line as below,

`<LocalClaimDialect>true</LocalClaimDialect><ClaimMappings><ClaimMapping><LocalClaim><ClaimUri>http://wso2.org/claims/givenname</ClaimUri></LocalClaim><RemoteClaim><ClaimUri>http://wso2.org/claims/givenName</ClaimUri>ClaimUri></RemoteClaim><RequestClaim>true</RequestClaim></ClaimMapping></ClaimMappings></ClaimConfig>`

It is not properly alignend and has a unnecessary 'ClaimUri>' inbetween 

Can be improved as,

```
	<ClaimConfig>
		<AlwaysSendMappedLocalSubjectId>true</AlwaysSendMappedLocalSubjectId>
		<LocalClaimDialect>true</LocalClaimDialect>
		<ClaimMappings>
			<ClaimMapping>
				<LocalClaim>
					<ClaimUri></ClaimUri>
				</LocalClaim>
				<RemoteClaim>
					<ClaimUri></ClaimUri>
				</RemoteClaim>
				<RequestClaim>true</RequestClaim>
			</ClaimMapping>
		</ClaimMappings>
	</ClaimConfig>
```

[1] https://docs.wso2.com/display/IS550/Configuring+a+SP+and+IdP+Using+Configuration+Files

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
