### ISSUE TITLE
[Conditional Authentication Samples-sample1]-Error "A tenant with same domain already exist"

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#3422]
**Description:**
When the [sample1](https://github.com/wso2/samples-is/tree/master/conditional-auth-sample/src/main/resources/sample1) in conditional authentication samples was run in the first time it executes correctly and, then cleaned up the generated artifacts at the end. However, when it was run the second time, the following error was encountered since the tenant with the same domain exists. 

![croped_is_error](https://user-images.githubusercontent.com/25483865/42752513-c7f631c8-890b-11e8-8dab-b2ea74158e38.png)

**Steps to reproduce:**
1.Navigate to <SAMPLE_HOME>/conditional-auth-sample/src/main/resources/sample1 in terminal and execute the configuration script `sh configure_sample1.sh`
2. Clean the created artifacts.
3. Try the 1st step again.

**Affected Versions:**
IS: 5.6.0

**OS, DB, other environment details and versions:**
OS: Ubuntu 16.04

**Comment by pulasthi7** [comment]
This is a valid result as we can't delete any created tenants. We need to think of an alternative(add only the users if tenant exists) or warn/document this in the QSG that this operation is one time.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
