### ISSUE TITLE
JWT roles (groups) serialization

### ISSUE THREAD

**Issue by saxicek** [wso2/product-is#3440]
Trying to use Microprofile JWT support as documented in <https://docs.wso2.com/display/IS560/Microprofile+JWT+1.0+support+for+IS>

When roles are serialized to JWT claim `groups`, there is a type inconsistency:
1. When user has a role other than "Internal/everyone" assigned, roles are serialized as array:

   ```
   "groups": [
    "ADMIN",
    "Internal/everyone"
   ]
   ```
2. When user has no role other than "Internal/everyone" assigned, roles are serialized as string:

   ```
   "groups": "Internal/everyone"
   ```

This makes validation harder because I have to check for 2 datatypes for the `groups` field. I would expect that even single role is serialized as array:

   ```
   "groups": [
    "Internal/everyone"
   ]
   ```

**Comment by pulasthi7** [comment]
@madawas

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
