### ISSUE TITLE
Edit Service Provider - SAML2 Web SSO Configuration UI - Too short data fields.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#3443]
The fields in the UI are not long enough to see the information fully. Since we have so much space left to the right of the screen, we should make the fields longer.

![image](https://user-images.githubusercontent.com/9441136/42887018-9db945f4-8ac2-11e8-924d-3bcf1b05ff39.png)

**Comment by GDRDABARERA** [comment]
Solution merged, hence closing
