### ISSUE TITLE
Scim/me endpoint doesn't return wso2extension section

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3447]
Add a user
`curl -v -k --user admin:admin --data "{"schemas":[],"userName":"nilasinit","password":"Wso2@123","wso2Extension":{"organization":"WSO2"}}" --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users`

Call scim/me endpoint
`curl -v -k --user nilasinit:Wso2@123 https://localhost:9443/wso2/scim/Users/me
`
Note:- Before call scim/me endpoint assign the login permission to the use nilasinit.

Actual result should contain the wso2extension section, but it is not returning. Need to fix it.

**Comment by GDRDABARERA** [comment]
Fixes with https://github.com/wso2-support/carbon-identity/pull/302
