### ISSUE TITLE
Getting "Not Applicable" when calling the entitlement rest service for tenant after server restart

### ISSUE THREAD

**Issue by mushthaq33** [wso2/product-is#3450]
Pack - IS 5.5.0

When we call the Entitlement rest service to get the decision of a xacml policy request for a tenant after a server restart it always gives a the decision as "Not Applicable". This is not reproducible for super tenant users.

Steps to Reproduce.
1. Create XACML policy in Identity Server and publish it to PDP (These needs to be done using a tenant).
2. Send a xacml request using the entitlement REST service by calling the tenant url (Using Postman).
3. This will return the decision as "Not Applicable"
4. Click on the "Registry Policy Finder Module" refresh button.
5. Try the same call using postman and you will get the expected output.

**Comment by thanujalk** [comment]
Hi @mushthaq33,

Tested this with is-5.50 fresh pack and is-5.7.0-alfa3. But didn't able to reproduce the issue. Do we need to enable additional configurations to reproduce this?

Thanks,
Thanuja

**Comment by thanujalk** [comment]
This is already resolved in the latest release.
