### ISSUE TITLE
Support for 'Use user store domain in roles' in SAMLBearerGrant type.

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#3470]
Based on the SP level UI configuration 'Use user store domain in roles' it should be appended/not appended user store domain name to the roles which we get as user claims in saml bearer grant type.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
