### ISSUE TITLE
setting EmailVerification/Enable to true in identity.xml not reflected in UI

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3476]
uncommenting the block for `EmailVerification`, setting `Enable` to `true`, and restarting the server is populating all other relevant fields, but not checking the box to enable:

```
<EmailVerification>
  <Enable>true</Enable>
  <ExpiryTime>1440</ExpiryTime>
  <LockOnCreation>true</LockOnCreation>
  <Notification>
    <InternallyManage>true</InternallyManage>
  </Notification>
  <AskPassword>
    <ExpiryTime>1440</ExpiryTime>
    <PasswordGenerator>org.wso2.carbon.user.mgt.common.DefaultPasswordGenerator</PasswordGenerator>
  </AskPassword>
</EmailVerification>
```

![screen shot 2018-07-25 at 16 18 39](https://user-images.githubusercontent.com/1661988/43228183-7b0efa94-9026-11e8-871c-7fc65b3d5d10.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
