### ISSUE TITLE
[SCIM2] create user fails without password, after setting up Ask Password

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3477]
after following the instructions for [Creating Users Using the Ask Password Option](https://docs.wso2.com/display/IS560/Creating+Users+Using+the+Ask+Password+Option) and confirming that the UI enables creation of users without providing a password, attempting to issue the command `curl -k -H "Content-Type: application/json" -d @intl.txt https://localhost:9443/scim2/Users` against a local IS 5.6.0 instance with SCIM2 endpoint security disabled in identity.xml & the contents of `intl.txt` as:
```
{
  "externalId" : "qwerty",
  "userName" : "qwertyAAAAAA",
  "name" : {
    "familyName" : "b",
	"givenName" : "a"
  },
  "emails" : [ {
    "value" : "a@a.aa",
	"type" : "work",
	"primary" : true} ],
  "phoneNumbers" : [ {"value" : "+1 222-333-4444"} ],
  "EnterpriseUser":{"askPassword":"true"}
}
```
results in `{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","detail":"Error in adding the user: qwertyAAAAAA to the user store. PasswordInvalidAsk Password Feature is disabled","status":"500"}`

After enabling Ask Password, a password shouldn't be required.  Ideally, `EnterpriseUser`.`askPassword` should also be implied by the presence of an email address & the absence of a password.

**Comment by Sathiyakugan** [comment]
To create user using  askPassword  by SCIM 2.0,  The password filed should be there in the JSON payload. The doc doesn't explicitly mention this.
