### ISSUE TITLE
creating user claims success when ask password enabled & SMTP misconfigured

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3489]
I've been fighting a bit to get WSO2 IS configured with OSX's default postfix installation, and thus my email adapter is not working correctly - giving `ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} -  Event dropped at Output Adapter 'EmailPublisher' for tenant id '-1234', Error in message format, Could not connect to SMTP host: localhost, port: 25` errors.  However, it seems like the user is successfully created (and a success message returned) even if the ask-password email is not successfully sent - both via the UI and via SCIM.  This email should be considered part of the creation process, and should cause that process to fail if unable to send.

This is particularly troubling in combination with #2625

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
