### ISSUE TITLE
[Doc] Remove Enable Script Based Conditional Authentication checkbox content

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3498]
**Description**
Remove Enable Script Based Conditional Authentication checkbox content in the Tip section in [1] as it is been removed from the UI.

**Doc Links**
[1] https://docs.wso2.com/display/IS570/Configuring+a+Service+Provider+for+Adaptive+Authentication

**Comment by madurangasiriwardena** [comment]
Closing since this is fixed in the linked doc page.
