### ISSUE TITLE
Email sending notification can be seen, even when email is not sending.

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#3502]
In the self-registration page, we can see the email sending notification although we disabled account lock on the creation. This is misleading the users thinking that email module is not working. We need to fix the UI.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
