### ISSUE TITLE
Password contains colon ":" character cannot be used to invoke Admin Services.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#3505]
Based on the "HTTP Authentication: Basic and Digest Access Authentication"  specification[1], the username cannot have ":", but no restrictions are defined for the password. 

      basic-credentials = base64-user-pass
      base64-user-pass  = <base64 [4] encoding of user-pass, except not limited to 76 char/line>
      user-pass   = userid ":" password
      userid      = *<TEXT excluding ":">
      password    = *TEXT

**Comment by pulasthi7** [comment]
@IsuraD : Is this fixed with above PR? can we close this once kernel version is updated?
