### ISSUE TITLE
Minor Adaptive Authentication Doc and UI improvements

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#3508]
1. The doc page titles were updated therefore please update the doc links in the UI (see [1] for a list of the page links) 

2. There needs to be hyphen in between if there is a compound noun before the modified verb. Therefore "Role Based", "Tenant Based", etc., need to be changed to "Role-Based","Tenant-Based", etc., in the UI. 

3. "User's Age Based" should change to "User-Age-Based".

4. "Userstore Based" should change to "User Store-Based". (user store is two words but refers to one object)

5. Is it possible to call the "New Device Login" template as "Device-Based" or "Cookie-Based" template?

6. Can we change "ACR" to "ACR-Based"?

7. Can we change "Risk Calculation" to "Risk-Based" for consistency (only if it doesn't affect the meaning we are trying to convey). 

[1] https://docs.wso2.com/display/IS570/Adaptive+Authentication+Scenarios

@Minoli

**Comment by Minoli** [comment]
Fixed with PR https://github.com/wso2/carbon-identity-framework/pull/1771
