### ISSUE TITLE
Error occurred when manually sourcing the Identity-Oracle sql script

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-is#3516]
**Enviornment**
OS-CentOS
JAVA-JDK 1.8.0_171
DB - Oracle 12.1.0.2
wso2is-5.7.0-m5 pack

**Steps:**
Took the latest oracle script which fixed in [1] 
Source that Identity-oracle script.
Below error could able to see when sourcing the script. 

[1] https://github.com/wso2/carbon-identity-framework/blob/5d1d944ea6faae73892a71b6e54dd191cf564fd9/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/oracle.sql

**Error**

<img width="858" alt="screen shot 2018-08-02 at 2 31 11 pm" src="https://user-images.githubusercontent.com/14923354/43574034-c4f559a6-9660-11e8-8b35-a06c839a5cc1.png">

**Comment by senthalan** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1777/files
