### ISSUE TITLE
Create documentation for Identifier first login and user input prompt

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3540]
Sample scripts can be found from
- https://github.com/wso2/carbon-identity-framework/pull/1690
- https://github.com/wso2/carbon-identity-framework/pull/1650

**Comment by samgnaniah** [comment]
https://docs.wso2.com/display/IS570/Configuring+Multi-factor+Authentication+with+Username+and+Password

**Comment by gomathyk** [comment]
Doc added now: [1](https://docs.wso2.com/display/IS570/Identifier-first+Flow+Handler)
