### ISSUE TITLE
Missing instructions to deploy Private Key JWT Client Authentication for OIDC

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3541]
Documentation at [1] does not specify where to copy the artifacts downloaded.

[1] https://docs.wso2.com/display/IS550/Private+Key+JWT+Client+Authentication+for+OIDC

**Comment by Nashaath** [comment]
Added a step to mention that the downloaded jar should be copied to the <IS_HOME>/repository/component/dropins directory.

Added this step in doc versions 5.5.0 through 5.7.0.
