### ISSUE TITLE
Rest API to retrieve OAuth Application with SP name

### ISSUE THREAD

**Issue by nuwandiw** [wso2/product-is#3543]
[1] should be updated with the API request details which allow to retrieve oauth application data with sp name.

Sample Request.
`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register?client_name="application_1"`

Sample Response
```
"HTTP/1.1 200 OK"
{ "client_id": "s6BhdRkqt3",
"client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
"client_secret_expires_at": 1577858400,
"redirect_uris":["https://client.example.org/callback"],
"client_name":"application_1" }
```

[1] https://docs.wso2.com/display/IS540/apidocs/OAuth2-dynamic-client-registration/index.html#!/operations#OAuthDCR#getApplication

**Comment by nuwandiw** [comment]
With the addition of new API method, the dcr API version is increased. Therefore the new API URL is https://localhost:9443/api/identity/oauth2/dcr/**v1.1**/register.

This is effective for all the dcr APIs

**Comment by Nashaath** [comment]
Got the updated OAuth2 dynamic client registration REST API docs hosted for IS 5.7.0.
Updated [1] to point off to the latest REST API docs hosted for IS 5.7.0.
[1] https://docs.wso2.com/display/IS570/OpenID+Connect+Dynamic+Client+Registration+using+REST+APIs
