### ISSUE TITLE
Cannot update SAML Inbound authentication configs

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#3546]
- Add a SAML SP and Save
- Then on the saved SP, click 'Edit' on SAML inbound configs. This does not load the complete configuration that we configured previously. 'Issuer' is missing
- Try to re-save the config. That will give an error as the 'Issuer' is missing.
- This blocks updating SAML SP inbound configurations

Labels:
Affected/5.7.0-Alpha

**Comment by thanujalk** [comment]
Tested with 5.7.0-alfa3 and scenario works fine. So resolving the issue.
