### ISSUE TITLE
Make SSO authentication related pages responsive

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3558]
The current pages can use some improvements to to be more responsive

![image](https://user-images.githubusercontent.com/9883427/43972654-b67207b0-9cf2-11e8-8a90-6a76a00bb42d.png)

![image](https://user-images.githubusercontent.com/9883427/43972663-bcb07990-9cf2-11e8-8cc1-67ac0ece31d6.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
