### ISSUE TITLE
Rename the existing sub heading “Filter Users” as “List Users” in IS 5.6.0 doc.

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#3559]
In IS 5.6.0 SCIM2 documentation, under filter users, instead of describing filters, we discussed how to list the users using different attributes. [https://docs.wso2.com/display/IS560/apidocs/SCIM2-endpoints/#!/operations#UsersEndpoint#getUsersByPost](url)

**Comment by hauntingEcho** [comment]
possibly related to #3345

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
