### ISSUE TITLE
All authenticator's names should be documented

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3561]
We need to have correct authenticator names when we use file based IDPS, so we have to document all the authenticator names in the docs. 

For example, when we configure linkedin authenticator we should mention the federated authenticator name as "LinkedIn" according to [1].

Likewise, we have to use the appropriate names for other authenticators as well. Therefore all the authenticator names should be documented in some place.

[1] https://github.com/wso2-extensions/identity-outbound-auth-linkedIn/blob/master/component/src/main/java/org/wso2/carbon/identity/authenticator/linkedIn/LinkedInAuthenticatorConstants.java#L27

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
