### ISSUE TITLE
Instructions to set pool size for 0 in migration documentation

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3565]
In IS 5.3.0, default PoolSize we shipped was 0. But in previous releases, this value was 200. As our recommendation for pool size is 0, we need to update this information in migration documentation.

https://docs.wso2.com/display/IS530/Upgrading+from+the+Previous+Release

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
