### ISSUE TITLE
Self-Registration UI improvements

### ISSUE THREAD

**Issue by Nashaath** [wso2/product-is#3566]
Need to use consistent terminology across UIs with regard to the term self-registration.
Right now we have the following terms used when it comes to self-registration:

- User Self Registration
- self user registration
- Self-Sign-Up
- self registration
![self-reg](https://user-images.githubusercontent.com/9528121/44090755-dec8216a-9fe8-11e8-99b5-e0501a68bf96.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
