### ISSUE TITLE
[doc] set default to "ask password" on user creation via API (SCIM/bulk/etc)

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3567]
Is there a way to set the server default to "ask password" on a newly-created user, particularly for users created via APIs?  I'm not seeing a way to in the [Ask Password documentation](https://docs.wso2.com/display/IS560/Creating+Users+Using+the+Ask+Password+Option) or in the [SCIM2 connector configuration documentation](https://docs.wso2.com/display/ISCONNECTORS/Configuring+SCIM+2.0+Provisioning+Connector#ConfiguringSCIM2.0ProvisioningConnector-/UsersEndpoint)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
