### ISSUE TITLE
Include information on creating the consent DB in 5.4.0 and 5.4.1 migration docs

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3569]
- Create a DB for consent management
- Point to the new DB from a datasource in master-datasources.xml
- Refer the new data source through consent-mgt-config.xml

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
