### ISSUE TITLE
[5.6.0] privacy & cookie policy state that they are for IS 5.5.0

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3570]
On a locally-running instance of WSO2 IS 5.6.0, both the pages at `authenticationendpoint/cookie_policy.do` and `authenticationendpoint/privacy_policy.do` state that they are the policies for 5.5.0 in multiple places.  5.5.0 is hardcoded in both the [cookie policy](https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/cookie_policy.jsp) & [privacy policy](https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/privacy_policy.jsp) code rather than retrieving the current server version.

**Comment by dewniMW** [comment]
Closing issue as Product version is no longer maintained [1] in cookie policy
[1] [https://github.com/wso2/carbon-identity-framework/commit/c92b534c60a183741713beea379c5a5bb4260b51]

**Comment by darshanasbg** [comment]
Thanks for the contribution @dewniMW.
