### ISSUE TITLE
Typo in identity.xml code comment

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#3575]
"PoolZize" should be changed to "poolsize" within this code comment in the identity.xml file under the <TempDataCleanup> tag: 

```
<!-- When PoolZize > 0, temporary data which have no usage after the authentication flow will be deleted immediately
                 When PoolZise = 0, data will be deleted only by the scheduled cleanup task-->
        <PoolSize>20</PoolSize>
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
