### ISSUE TITLE
[Doc] [5.6.0] dead link to "Applying Patching" in "Implementing Security in the Identity Server" documentation

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3578]
On the page "[Implementing Security in the Identity Server](https://docs.wso2.com/display/IS560/Implementing+Security+in+the+Identity+Server#)", the "Applying Patches" link is dead.  The [closest relevant documentation I could find](https://docs.wso2.com/display/IS510/Applying+Patches) was for 5.1.0.

**Comment by madurangasiriwardena** [comment]
Hi @hauntingEcho, since IS 5.6.0 is supporting WUM and does not provide patches by WSO2, the link should be pointing to [this](https://docs.wso2.com/display/updates/Using+WSO2+Update+Manager) document. We will fix the link and the text of the link to reflect this information.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
