### ISSUE TITLE
Enable FIDO2 authentication

### ISSUE THREAD

**Issue by elukewalker** [wso2/product-is#3579]
This request is to enable FIDO2 authentication.

[FIDO2](https://fidoalliance.org/fido2/) is the next step beyond FIDO U2F. It composed of two open standards:
1. [FIDO Client To Authenticator Protocol 2.0 (CTAP2)](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html) and,
2. [W3C Web Authentication (WebAuthn)](https://www.w3.org/TR/webauthn/)

IMHO, the main benefits of FIDO2 are:
1. W3C WebAuthn standardizes how browsers create and use attested, scoped, public key-based credentials. This is enabling broader adoption beyond just Chrome.
2. CTAP2 allows credentials to be stored in authenticators, like a Security Key by Yubico. These are called [resident keys](https://www.w3.org/TR/webauthn/#client-side-resident-credential-private-key). This enables a roaming root of trust. This is particularly interesting for enterprises whose employees access shared workstations.
3. CTAP2 allows user verification, e.g. a user can set a PIN which is required to unlock cryptographic operations. The PIN never leaves the authenticator.
4. The combination of resident keys and user verification enables multi-factor authentication from a single authenticator. This can enable interesting use cases such as roaming passwordless authentication.
5. FIDO2 is backwards compatible with FIDO U2F.

Additional Resources:
* [Browsers are working towards supporting WebAuthn](https://caniuse.com/#search=webauthn)
* [Edge announced support for FIDO2 support.](https://blogs.windows.com/msedgedev/2018/07/30/introducing-web-authentication-microsoft-edge/#89b8LL1y8KxQdE5R.97)
* [Web Authentication on MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)
* [WebAuthn implementations are showing up on GitHub](https://github.com/search?q=webauthn)

**Comment by elukewalker** [comment]
Any update? What does the process look like to get a feature prioritized to a release?

**Comment by madurangasiriwardena** [comment]
Hi @elukewalker, 

FIDO2 is a great feature to have in the Identity Server. Unfortunately, we could not prioritize this feature for the 5.8.0 (votes are going on for this release) and for the next release 5.9.0. We will definitely prioritize this feature for one of the next releases.

Thanks,
Maduranga

**Comment by elukewalker** [comment]
Thanks for the update @madurangasiriwardena.

FIDO2/WebAuthn has gained more traction since this issue was created.  There has even been some interested expressed by attendees at the previous RSA conference is SF about WSO2 and WebAuthn.

Please keep me in the loop.

**Comment by mefarazath** [comment]
@IsurangaPerera
