### ISSUE TITLE
Change ArtifactResponse extraction method

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#3580]
- A regex pattern was used to extract the ArtifactResponse object. Hardcoded regex string can cause problems when specification versions or lib versions are upgraded. Therefore we have used library constants to validate and extract the object.

https://github.com/wso2-extensions/identity-outbound-auth-samlsso/commit/0abbfd39313ec5d55a52798c63ed182a455eed12#diff-c1c4202758b11a45ebc80dd15896a5b4R119

```
...
String artifactResponseString = soapMessageService.sendSOAP(envelopeElement, SSOUtils.getArtifactResolveUrl(authenticatorProperties));
Pattern pattern = Pattern.compile("<samlp:ArtifactResponse.+</samlp:ArtifactResponse>", Pattern.DOTALL);
Matcher matcher = pattern.matcher(artifactResponseString);
if (matcher.find()) {
...
```

**Comment by darshanasbg** [comment]
product-is has updated to include this fix with https://github.com/wso2/product-is/commit/860654dda97ec7f672f82f21e5a034389a43858b
