### ISSUE TITLE
 Need to print the stack trace at INFO log level in "org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager"

### ISSUE THREAD

**Issue by madeesha** [wso2/product-is#3582]
Description:
In high load scenario, if LDAP gets timeout, this issue does not print at INFO log level.

TID: [-1234] [] [2018-08-09 17:40:38,338] DEBUG {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager} - Searching for user 20b30505Ufc68U4bbeU801bU089fd8a5acbc_DP {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager}
TID: [-1234] [] [2018-08-09 17:40:38,338] DEBUG {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager} - Searching for user with SearchFilter: (&(objectClass=person)(|(cn=20b30505Ufc68U4bbeU801bU089fd8a5acbc_DP)(international
ISDNNumber=20b30505Ufc68U4bbeU801bU089fd8a5acbc_DP))) in SearchBase: {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager}

TID: [-1234] [] [2018-08-09 17:40:43,339] DEBUG {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager} - LDAP response read timed out, timeout used:5000ms. {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager}
javax.naming.NamingException: LDAP response read timed out, timeout used:5000ms.; remaining name 'OU=DP,OU=2,DC=dpaycoll,DC=local'
at com.sun.jndi.ldap.Connection.readReply(Connection.java:490)
at com.sun.jndi.ldap.LdapClient.getSearchReply(LdapClient.java:638)
at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:561)
at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1985)
at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1844)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
