### ISSUE TITLE
OIDC logout documentation should be updated for tenant flow

### ISSUE THREAD

**Issue by nuwandiw** [wso2/product-is#3604]
[1] Should contain following details.

If **SignJWTWithSPKey** property is set to **true** in identity.xml, JWT will be signed with the application tenant key.

If the property is set to **false**, tenant would be decided by the subject of the id token. subject would not contain tenant domain by default. Therefore need to enable, **Use tenant domain in local subject identifier** in Service Provider configuration.

[1] https://docs.wso2.com/display/IS570/OpenID+Connect+Logout+URL+Redirection

**Comment by samgnaniah** [comment]
Fixed. 

https://docs.wso2.com/display/IS570/OpenID+Connect+Logout+URL+Redirection
