### ISSUE TITLE
IS Migration will not work for separate Registry resource 

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#3605]
In migration client, we have used 3 data sources that for um, identity and consent. We expect it will be the same data source for both registry and um.
But in case, if there are any separate data source for the registry resource, it will not be possible to do the migration using this client.
https://github.com/wso2/product-is/blob/42b39a49316f39dde962ba971fb72f58189c09d9/modules/migration/migration-service/src/main/java/org/wso2/carbon/is/migration/DataSourceManager.java

We need to introduce new data source for registry as well.

**Comment by vozzy** [comment]
Does this mean that this will not work with the following data source configuration? 

`<datasource>
            <name>WSO2REG_DB</name>
            <description>The datasource used for gov registry</description>
            <jndiConfig>
                <name>jdbc/WSO2REG_DB</name>
            </jndiConfig>
            <definition type="RDBMS">
                <configuration>
                    <url>jdbc:mysql://mysql.com:3307/wso2_reg_qa_1?autoReconnect=true&amp;</url>
                    <driverClassName>com.mysql.jdbc.Driver</driverClassName>
                    <maxActive>75</maxActive>
                    <maxWait>60000</maxWait>
                    <testOnBorrow>true</testOnBorrow>
                    <validationQuery>SELECT 1</validationQuery>
                    <validationInterval>30000</validationInterval>
                </configuration>
            </definition>
        </datasource>
        <datasource>
            <name>WSO2UM_DB</name>
            <description>The datasource is used for user management and userstore</description>
            <jndiConfig>
                <name>jdbc/WSO2UM_DB</name>
            </jndiConfig>
            <definition type="RDBMS">
                <configuration>
                    <url>jdbc:mysql://mysql.com:3307/wso2_user_qa_1?autoReconnect=true&amp;</url>
                    <driverClassName>com.mysql.jdbc.Driver</driverClassName>
                    <maxActive>75</maxActive>
                    <maxWait>60000</maxWait>
                    <testOnBorrow>true</testOnBorrow>
                    <validationQuery>SELECT 1</validationQuery>
                    <validationInterval>30000</validationInterval>
                </configuration>
            </definition>
        </datasource>
        <datasource>
            <name>WSO2_AM_DB</name>
            <description>The datasource used for API Manager database</description>
            <jndiConfig>
                <name>jdbc/WSO2AM_DB</name>
            </jndiConfig>
            <definition type="RDBMS">
                <configuration>
                    <url>jdbc:mysql://mysql.com:3307/wso2_api_qa_260_1?autoReconnect=true</url>
                    <driverClassName>com.mysql.jdbc.Driver</driverClassName>
                    <maxActive>75</maxActive>
                    <maxWait>60000</maxWait>
                    <testOnBorrow>true</testOnBorrow>
                    <validationQuery>SELECT 1</validationQuery>
                    <validationInterval>30000</validationInterval>
                </configuration>
            </definition>
        </datasource>`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
