### ISSUE TITLE
Missing configurations when configuring newer versions of SMSOTP Authenticator with Identity Server

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#3610]
Following the configuration steps available in the [SMS OTP doc](https://docs.wso2.com/display/IS570/Configuring+SMS+OTP) result in a NullPointerException during runtime. 
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework
java.lang.NullPointerException
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.processAuthenticationResponse(SMSOTPAuthenticator.java:625)
```

The latest versions of SMSOTP Authenticator requires following additional properties in application-authentication.xml file as mentioned in the [git doc](https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/master/docs/config.md). We need to add these missing steps to WSO2 documentation as well.

```
<AuthenticatorConfig name="SMSOTP" enabled="true">
    <Parameter name="SMSOTPAuthenticationEndpointURL">https://localhost:9443/smsotpauthenticationendpoint/smsotp.jsp</Parameter>
    <Parameter name="SMSOTPAuthenticationEndpointErrorPage">https://localhost:9443/smsotpauthenticationendpoint/smsotpError.jsp</Parameter>
    <Parameter name="MobileNumberRegPage">https://localhost:9443/smsotpauthenticationendpoint/mobile.jsp</Parameter>
    <Parameter name="RetryEnable">true</Parameter>
    <Parameter name="ResendEnable">true</Parameter>
    <Parameter name="BackupCode">true</Parameter>
    <Parameter name="SMSOTPEnableByUserClaim">false</Parameter>
    <Parameter name="SMSOTPMandatory">false</Parameter>
    <Parameter name="usecase">association</Parameter>
    <Parameter name="secondaryUserstore">primary</Parameter>
    <Parameter name="CaptureAndUpdateMobileNumber">true</Parameter>
    <Parameter name="SendOTPDirectlyToMobile">false</Parameter>
    <Parameter name="EnableAlphanumericToken">true</Parameter>
    <Parameter name="TokenExpiryTime">30</Parameter>
    <Parameter name="TokenLength">8</Parameter>
</AuthenticatorConfig>
```

**Comment by GayanM** [comment]
@emswbandara I could reproduce same in IS 5.7.0. I suppose there are some properties you can move from application-authentication.xml to federated authenticator UI

**Comment by GayanM** [comment]
@emswbandara I have sent https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/pull/46 just to avoid NPE

**Comment by hauntingEcho** [comment]
alternatively, is there a reason not to make these changes in the default configuration?

**Comment by hauntingEcho** [comment]
following these directions leads to the user's phone number being sent as their OAuth ID by IS5.6.0, rather than using the assertions from the step specified in the configuration.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
