### ISSUE TITLE
Add thread names to long wait task threads

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3612]
This will be critical when analyzing thread dumps.

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by omindu** [comment]
@ashensw Not sure why this is High complexity issue. My feeling is that this will be a very small fix. Can you check with @madurangasiriwardena on this ?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
