### ISSUE TITLE
do not show default-disabled recovery options by default

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3625]
By default, both password recovery options (notification & questions) are disabled at the server-level but visible to end-users, which ends in an error page.
The default setup shouldn't leave visible-but-non-working options for end-users.

**Comment by hauntingEcho** [comment]
generally speaking, not showing the options when they are disabled in general would be beneficial

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
