### ISSUE TITLE
Support for having placeholders in SP templates

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3627]
Following would be the future improvements for SP template support.

- Provide capability to import SP templates in XML with placeholders.
- When creating a service provider from a template, will be showing a pop-up to enter values for the placeholders.
- If the placeholder values are for inbound authentication configurations, corresponding application should be created (i.e. placeholder values are for SAML issuer & Assertion Consumer URLs, registry entry should be created with the SAML configurations when registering SP with template).
- Improve DCRM endpoint to pass the template placeholder values.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
