### ISSUE TITLE
Capability to provide an option to select the default template from existing list

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3628]
Currently the tenant default template should be created from management console with the name "default". It can be improved to provide an option(i.e. check box) to select one of the existing template as the tenant default template.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
