### ISSUE TITLE
Capability to use multiple SP templates, when creating a Service provider 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3629]
This is to provide capability to use multiple SP templates, when creating a Service provider (ex: use both template with custom SP claim configurations and a template with TOTP/multi-step authentication (i.e.which can be applicable for all the SPs in a tenant)).
Backend APIs, UI and DCRM endpoint should be improved with this.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
