### ISSUE TITLE
oidcdiscovery/.well-known/openid-configuration returns additional scopes when configure IS as a KM

### ISSUE THREAD

**Issue by amalkasubasinghe** [wso2/product-is#3632]
In our setup we have configured IS as KM with APIM
IS-Km 5.60
APIM 2.50

When I invoke the oidcdiscovery/.well-known/openid-configuration,  it returns additional scopes (registry.*) that we haven't defined 
Any idea what are those? 

{
    "scopes_supported": [
        "profile",
        **"registry.user",**
        **"registry.realpath",**
        **"registry.link",**
        **"registry.author",**
        "phone",
        "email",
        "address",
        **"registry.mount",**
        "openid"
    ],
    "check_session_iframe": "https://localhost:9444/oidc/checksession",
    "issuer": "https://localhost:9444/oauth2/token",
    "authorization_endpoint": "https://localhost:9444/oauth2/authorize",
    "claims_supported": [
 .......
    ],
    "token_endpoint": "https://localhost:9444/oauth2/token",
    "response_types_supported": [
        "id_token token",
        "code",
        "id_token",
        "token"
    ],
    "end_session_endpoint": "https://localhost:9444/oidc/logout",
    "userinfo_endpoint": "https://localhost:9444/oauth2/userinfo",
    "jwks_uri": "https://localhost:9444/oauth2/jwks",
    "subject_types_supported": [
        "pairwise"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "registration_endpoint": "https://localhost:9444/api/identity/oauth2/dcr/v1.0/register"
}

This did not reproduce in standalone iskm560

**Comment by Pushpalanka** [comment]
This occurs only when registry mounting is at place. We need to filter these internal details and expose only the other defined scopes at,
Oauth2Util class, method - getOIDCScopes 
[1] - https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L1301-L1322
