### ISSUE TITLE
Upgrade xercesimpl jar to fix security vulnerability

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#3634]
Apache Xerces2 Java allows remote attackers to cause a denial of service (CPU consumption) via a crafted message to an XML service, which triggers hash table collisions.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
