### ISSUE TITLE
IllegalArgumentException when replacing strings with "$" signs.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#3635]
The issue observed when building email notification in `NotificationBuilder` class. Inside the [replaceTags()](https://github.com/wso2/carbon-identity-framework/blob/v5.7.5/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/mail/NotificationBuilder.java#L71) method, a replace all operation called to replace tags with values such as email. But there's a known [issue](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#replaceAll-java.lang.String-java.lang.String-) in String.replaceAll() method where **$** signs and **/** signs are included in the replacement string.

**Comment by darshanasbg** [comment]
Same issue fixed under issue: https://github.com/wso2/product-is/issues/3057 with PR: https://github.com/wso2-extensions/identity-event-handler-notification/pull/84
