### ISSUE TITLE
Getting org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException when trying to delete old captcha details from the registry

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-is#3647]
This issue is already reported and fixed for single node instance. Please refer to the issue\[1]. But the fix should implement to the clustered environment when the registry is mounted.

**Product version: wso2is-5.1.0**

**Steps to reproduce:**

- Create a captcha image using the soap API getCaptcha() of service in a registry mounted clustered envirnment https://localhost:9443/services/UserInformationRecoveryService?wsdl

- Delete only the captcha image from the registry after 20mins
 (management console -> Registry -> Browse -> _system -> config -> repository -> components -> org.wso2.carbon.captcha-images)
 
- Now try to call the getCaptcha() API.
 
**Solution**

Follwoing fix should be applied in order to avoid the exception in both single instance and clusterd instance.

**org.wso2.carbon.captcha.mgt.util.CaptchaUtil.java**

// deleting the captcha image

                            try {
                                superTenantRegistry.delete(imagePath);
                            } catch (RegistryException ex) {
                                if (ex.getCause() != null && ex.getCause() instanceof ResourceNotFoundException) {
                                    if (log.isDebugEnabled()) {
                                        log.debug("Captcha image in the following path not found. " + imagePath);
                                    }
                                } else if(ex.getCause() instanceof ResourceNotFoundException ) {
                                    if (log.isDebugEnabled()) {
                                        log.debug("Captcha image in the following path not found. " + imagePath);
                                    }
                                }else {
                                    throw ex;
                                }
                            }

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
