### ISSUE TITLE
OIDC Discovery not working when hostname is different

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#3652]
Change the hostname in the carbon.xml (lets say is.wso2.com)

Access https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration
(Note, above url have different hostname compared to the hostname in carbon.xml)

Response is 500 internal server error with the message body
```
Error while loading the endpoint. The path to the discovery document should be in the format of {issuer}/.well-known/openid-configuration
```

After sending a one request, even it changed to to access https://is.wso2.com:9443/oauth2/oidcdiscovery/.well-known/openid-configuration
its still does not work (now the access url and the hostname in the carbon.xml is same).

During the first request that server serves, it cache hostname from the request, and it keep using the same..

Ideally we shouldn't have any hostname validation.

**Comment by dmxunlimit** [comment]
Also if the there is the LB front-end with proxy port enable for wso2server. could reproduce the issue even with calling the same hostname.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
