### ISSUE TITLE
separate theme webapp would greatly simplify skinning

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3661]
Due to the current structure of webapps, [customizing the interface](https://docs.wso2.com/display/IS560/Customizing+Login+Pages+for+Service+Providers) can involve changing many files to skin all endpoints.  Using a separate webapp just to serve theming-related content (e.g. the `css` and `images` folders which are duplicated across webapps \[[1](https://github.com/wso2/carbon-identity-framework/tree/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp)\]\[[2](https://github.com/wso2/carbon-identity-framework/tree/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/webapp)\]\[[3](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/tree/master/component/authentication-endpoint/src/main/webapp)\]\[[4](https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/tree/master/component/authentication-endpoint/src/main/webapp)\]\[[5](https://github.com/wso2-extensions/identity-outbound-auth-totp/tree/master/component/authentication-endpoint/src/main/webapp)\]\[[6](https://github.com/wso2/product-is/tree/v5.6.0/modules/jaggery-apps/user-dashboard/dashboard)\]\[[7](https://github.com/wso2-extensions/identity-outbound-auth-x509/tree/master/component/authentication-endpoint/src/main/webapp)\] would greatly simplify making sure theme updates are consistent across webapps.

**Comment by hauntingEcho** [comment]
a centralization of internationalization strings (e.g. \[[1](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/resources/org/wso2/carbon/identity/mgt/recovery/endpoint/i18n/Resources.properties)\]\[[2](https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/resources/org/wso2/carbon/identity/application/authentication/endpoint/i18n/Resources.properties)\]) could also have similar benefits

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
