### ISSUE TITLE
scim2 filter from "displayName" is not working for the admin role.

### ISSUE THREAD

**Issue by AnuGayan** [wso2/product-is#3679]
When using the following curl command, it will return a 200 without any records.
`curl -v -k --user admin:admin -X GET "https://localhost:9443/scim2/Groups?filter=displayName+Eq+admin" -H "Accept: application/json"` 

but when we run the following curl command, it shows that there is the admin role registered.

Curl command- 
`curl -v -k --user admin:admin -X GET "https://localhost:9443/scim2/Groups" -H "Accept: application/json"`

Result -
`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"PRIMARY/admin","meta":{"created":"2018-09-04T11:03:57Z","location":"https://localhost:9443/scim2/Groups/90d521f9-eae8-4452-ad30-07926a6174f7","lastModified":"2018-09-04T11:03:57Z"},"members":[{"display":"admin","value":"ed0ee696-8802-4b45-a735-6f889863e185"}],"id":"90d521f9-eae8-4452-ad30-07926a6174f7"}]}%`

**Comment by sarubi** [comment]
I tried with 5.7.0 beta, observed the same issue, but its working fine with other groups except for admin group. 
At the same time, It supports to get admin user details from the user endpoint.
