### ISSUE TITLE
Include "encryptUsernameInUrl" property in user-mgt.xml file (Primary use store) and add this property in the secondary user store UI.

### ISSUE THREAD

**Issue by mathuriga** [wso2/product-is#3684]
In order to pass the encrypted username in Management Console URL, we have to add following property in the user-mgt.xml config file. 

`<Property name="encryptUsernameInUrl">true</Property>
`
At the moment, This functionality is there. When we add this property in user-mgt.xml config file, then the encrypted username is passed in Management Console URL.

Further, This property needs to be added in the secondary user store UI.

**Comment by dulanjal** [comment]
Why is this a configuration at userstore level? This should be applied globally.

**Comment by malithie** [comment]
Agree that this should be a global level config. We will review and fix accordingly in a future release

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
