### ISSUE TITLE
OAuth token introspection fails when an unknown token_type_hint is passed.

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#3685]
If an unknown token_type_hint is passed the introspection endpoint responds with the following payload.

`{ "active": false }`

But as per the spec [1], if the a token can't be found for the given token_type_hint, the introspection implementation must try all the known hints to see whether a token can be found.

**IMPORTANT** : Right now the hint 'bearer' and 'jwt' are accepted by IS. When this issue is fixed we have to make sure that the support for the aforemention hints are not discontinued. 

[1] - https://tools.ietf.org/html/rfc7662#page-4

**Comment by IsurangaPerera** [comment]
Fixed in **5.8.0-m22**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
