### ISSUE TITLE
Drop down icon missing in Resident IDP configuration 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3686]
![residentidp](https://user-images.githubusercontent.com/11655825/45069491-69e12a00-b0ea-11e8-9c12-f4e59a0def6a.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
