### ISSUE TITLE
Authentication steps of the adaptive authentication script are missing after chaning authentication type 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3687]
Please use the following steps to reproduce this behavior.
1) Create a SP with adaptive authentication script.
2) Update the SP to use "default" authentication type.
3) Again update to use the advanced configuration. Authentication steps are missing, but the adaptive authentication script is shown as follows, no errors are shown.
![step1](https://user-images.githubusercontent.com/11655825/45070176-a95d4580-b0ed-11e8-9a76-5f0714e59b81.png)
4) Cancel updating the SP.
5) Try to update the SP again by selecting advanced configuration. Following errors can be seen.
![step2](https://user-images.githubusercontent.com/11655825/45070230-e1648880-b0ed-11e8-8666-fd71b455ba50.png)

**Comment by darshanasbg** [comment]
Lets clean all the data in advanced section, if it changed the authentication type.

**Comment by darshanasbg** [comment]
@thanujalk Just to clarify, was this fully fixed by https://github.com/wso2/carbon-identity-framework/pull/1872?

As of the description of https://github.com/wso2/carbon-identity-framework/pull/1872, it was mentioned it only solving this issue, partially..
