### ISSUE TITLE
Minor UX improvements for adding service provider template screens 

### ISSUE THREAD

**Issue by sherenewso2** [wso2/product-is#3696]
**Update Service Provider Template** screen

- _Template Name_ field help tip says "A unique name for the service provider". This should be corrected to "A unique name for the service provider template".
- Same issue for the _Description_ field help tip.

**Export service provider template** confirmation message

- Click Export on an existing SP template.
The following pop-up message appears: "Do you want to export Service Provider Template as the file ?". The wording of the message can improve..maybe something like "Are you sure you want to export this service provider template as an XML file?"

@Minoli @IndunilRathnayake

**Comment by IndunilRathnayake** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1879

**Comment by deshankoswatte** [comment]
Hi @sherenewso2,

> **Update Service Provider Template** screen
> 
> - Template Name field help tip says "A unique name for the service provider". This should be corrected to "A unique name for the service provider template".
> - Same issue for the Description field help tip.

I think these are good enough for the purpose so, changes would not be needed.

> **Export service provider template** confirmation message
> 
> - Click Export on an existing SP template. The following pop-up message appears: "Do you want to export Service Provider Template as the file ?". The wording of the message can improve..maybe something like "Are you sure you want to export this service provider template as an XML file?"

This is fixed by https://github.com/wso2/carbon-identity-framework/pull/2505

![Screenshot from 2019-10-30 11-31-49](https://user-images.githubusercontent.com/33062368/67833186-f4b08f80-fb09-11e9-8f7a-c4c2ddf64cdb.png)

**Comment by GDRDABARERA** [comment]
As fix is merged, closing the issue
