### ISSUE TITLE
Inconstancy in returing the sub value in user info endpoint.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#3700]
- UserInfoEndpoint is not giving the sub value adhere to the following properties 

 Use tenant domain in local subject identifier
 Use user store domain in local subject identifier

Steps to reproduce : 

1) Create a tenant secondary user store
2) Create SP in tenant space and  make above properties to false.
3) Get an access token for tenant user.
4) call user info endpoint to get the claims. sub claim will not have the domain and tenant info.
5) Update the user or refresh the token
6) call user info endpoint again. 
7) Sub claim will contain the domain and tenant domain.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
