### ISSUE TITLE
Cannot create tenant with in-active state via addTenant Admin Service

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#3706]
When adding a new tenant via admin services by setting the "active" attribute to false, the status of the newly created tenant is not being set to false. 

In addTenant() of TenantMgtAdminService [1], it activates the added tenant regardless of the value in the request.
```
// For the super-tenant tenant creation, tenants are always activated as they are created.
TenantMgtUtil.activateTenantInitially(tenantInfoBean, tenantId);
```

The issue can be reporduced by following [2] & setting "active" to false.

[1] https://github.com/wso2/carbon-multitenancy/blob/aec9750154b03d08775f720124750cf2f37b9e57/components/tenant-mgt/org.wso2.carbon.tenant.mgt/src/main/java/org/wso2/carbon/tenant/mgt/services/TenantMgtAdminService.java#L110
[2] https://www.dilan.me/2016/03/01/how-to-call-wso2-admin-service-using-curl/

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
