### ISSUE TITLE
Get Unauthorized while trying the UMA flow

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#3716]
Followed the steps here: https://medium.com/@dewni.matheesha/uma-2-0-features-in-wso2-identity-server-9f86fdfbb644

Get Unauthorized error in step 6. Use admin/admin to get the PAT.

**Comment by dewniMW** [comment]
Issue is not reproducible.

**Comment by JKAUSHALYA** [comment]
Closing since not reproducible.
