### ISSUE TITLE
Identifier first authenticator with invalid username

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#3720]
1. Type invalid username --> take you to the next step
2. Type password --> Fails
3. No way to come back and correct the username

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Comment by senthalan** [comment]
This is fixed in the latest version.
