### ISSUE TITLE
All configured claims are not added to the XML template file

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3724]
**Description**

When adding an SP template using an existing service provider configuration, only one custom claim is added to the template file.

Database : Oracle Rac

**Steps to reproduce**
1. Create a SP
2. Add multiple custom claims
3. Click "Save as template" and save the template

The saved template file does not contain all configured claims

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
