### ISSUE TITLE
The default Option for service provider template need to be set to none

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3726]
**Description**
In SP create view the service provider template default option "Select" needs to be changed to "None".

![screenshoot-sp-create](https://user-images.githubusercontent.com/9837443/45359404-0ecb9d80-b5ea-11e8-94b0-c395989346da.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
