### ISSUE TITLE
Improvements in Template add flow

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3727]
**Description**
1. "Import" button should be renamed to "Add".
2. "File Location" should be renamed to "Template File"
3. When adding a template with a XML file with errors and clicking Import resets the already added template name.
4. XML errors in the uploaded file needs to be shown when adding a template.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
