### ISSUE TITLE
User should be displayed with a message when saving a template without SP template configurations. 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3732]
**Description**
User is prompted to add template name and description when saving a template without SP template configurations and the error message is displayed in SP list page. 

The user needs to be prompted a message stating that there are no configurations to be saved as a template.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
