### ISSUE TITLE
[Doc] Update Add a service provider using the DCRM endpoint steps

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3739]
**Description**
In [1] Add a service provider using the DCRM endpoint step 2(Create a new service provider using the DCRM endpoint) is not needed as it is done through step 3. 

Doc Links
[1] https://docs.wso2.com/display/IS570/Adding+a+Service+Provider+Template

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
