### ISSUE TITLE
[Doc] Add the last step Update Resident IDP in Configuring self-registration

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3741]
**Description**
In Configuring self-registration[1] add Click Update as the last step.

[1] https://docs.wso2.com/display/IS570/Self-Registration+and+Account+Confirmation

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
