### ISSUE TITLE
"Confirmation link sent to email" message shows even when User Self Registration account locking is disabled

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3742]
**Description**
The following message shows even when User Self Registration account locking is disabled

![confirm-link](https://user-images.githubusercontent.com/9837443/45414724-a63bf980-b699-11e8-9183-9f98b9ac2213.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
