### ISSUE TITLE
[Doc] Update the screenshot in Configuring self-registration consent purposes

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3743]
Update the screenshot in Configuring self-registration consent purposes step 5[1] and Configuring Just-In-Time Provisioning Consent Purposes[2] step 6

[1] https://docs.wso2.com/display/IS570/Self-Registration+and+Account+Confirmation
[2] https://docs.wso2.com/display/IS570/Configuring+Just-In-Time+Provisioning+Consent+Purposes

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
