### ISSUE TITLE
Update the application name on consent screen when login to dashboard

### ISSUE THREAD

**Issue by Minoli** [wso2/product-is#3744]
The application name should be displayed to user without underscores. eg. WSO2 SP Dashboard

![dashboard-consent](https://user-images.githubusercontent.com/9837443/45415553-8a395780-b69b-11e8-9355-b424e4775957.png)

**Comment by darshanasbg** [comment]
As mentioned by @madurangasiriwardena in https://github.com/wso2/product-is/pull/4912#issuecomment-560298871

> In the same time dashboard application is deprecated and will no longer be shipped with the product. 5.10.0 release will contain a brand new user portal application that will contain similar name as you have fixed.

The generic issue of showing proper display name for any application during the consent page is raised with: https://github.com/wso2/product-is/issues/6950.

Hence closing this issue.
