### ISSUE TITLE
When the logged in user does not have mandatory claims IS throws a null pointer when custom claims are defined for SP

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#3759]
Steps to reproduce:

- Create a custom dialect for SP marked them as mandotery
- Logged in with a user who doesn't have mandotery claims
- You will get a error after the login page

**Comment by Buddhimah** [comment]
Issue Does Not reproduce in the IS wso2is-5.8.0-alpha5. Should be already resolved
