### ISSUE TITLE
No confirmation dialog box is prompted when deleting / revoking / regenerating secrets of OAuth App

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#3760]
1) Create an SP and register an Oauth App.
2) Click on Revoke, Regenerate Secret or on Delete buttons. 
3) No confirmation dialog box is prompted.

**Comment by thanujalk** [comment]
Related https://github.com/wso2/product-is/issues/4797

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.
