### ISSUE TITLE
Need to improve current OIDC Scopes view.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#3761]
In the current implementation, it is hard for a user to understand the functionality of the view.
Ex: Update
It feels like we need to select and finish to add them to a scope. But actually, it removes them.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
