### ISSUE TITLE
Need to fix conflict between ask password and password policy

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3763]
when we enable password policy and ask password option, the random generated password was validated against the password policy. Therefore if the random password does not comply with the password policy then there will be an error regarding policy violation.

In order to solve this issue, we have to write a custom password generator and register as an OSGi service. Sample could be found in  [1]. With this approach, in addition to the custom jar, we need to fix org.wso2.carbon.user.mgt.ui. The reason for this patch is, we don't have a dynamic import in [2] and we do not recommend to use dynamic import.

[1] https://github.com/nilasini/CustomPwdGenerator/tree/master/sample-custom-password-generator
[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt.ui/pom.xml#L141-L146

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
