### ISSUE TITLE
session_state parameter is sent in the redirect uri when the user deny the consent

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#3768]
According to the "3.1.2.6.  Authentication Error Response" section of [1],
> Unless the Redirection URI is invalid, the Authorization Server returns the Client to the Redirection URI specified in the Authorization Request with the appropriate error and state parameters. Other parameters SHOULD NOT be returned.

[1] https://openid.net/specs/openid-connect-core-1_0.html#AuthError

**Comment by ashensw** [comment]
Duplicate: https://github.com/wso2/product-is/issues/4018
