### ISSUE TITLE
List down the availbale local roles to be selected in role mapping of SP creation UI

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3770]
![local_role](https://user-images.githubusercontent.com/11655825/45817180-8b9dfc00-bcfb-11e8-9582-93c07690dcc8.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
