### ISSUE TITLE
Change the default "change-me" values in consent information controller configuration of resident IDP

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3774]
![consent_mgt](https://user-images.githubusercontent.com/11655825/45875377-1e4ea180-bdb5-11e8-8fa0-700c45908dae.png)

Having "change-me" in all the configurations as above, is not user friendly and are not applicable for some of the fields. Better to keep all the fields empty.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
