### ISSUE TITLE
Deleting a claim  will not delete the claim mapping configuration related entries in SPs/IDPs/User attributes

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#3784]
If a claim, which is included in claim mapping configuration of SPs/IDPs or in the user profiles, is deleted corresponding tables in SPs/ IDPs or User attributes won't get properly updated by removing claim URLs. This occurs because  the claim mappings of SPs and IDPs are stored by claim URL rather than a reference to the claim.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
