### ISSUE TITLE
Tenant wise Default Authentication Sequence

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3792]

**Comment by IndunilRathnayake** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1911

**Comment by IndunilRathnayake** [comment]
Integration Tests : https://github.com/wso2/product-is/pull/3820

**Comment by nilasini** [comment]
Reverted the feature with [1] since the feature is not production ready[2].

[1] https://github.com/wso2/carbon-identity-framework/pull/2094
[2] https://github.com/wso2/product-is/issues/4568

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
