### ISSUE TITLE
Add the newly added configurations of OpenID connect in identity.xml

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#3795]
The relevant configurations are explained in [1]. Following should be added by default in the pack.

```
<OpenIDConnect>
…
<ConvertOriginalClaimsFromAssertionsToOIDCDialect>false</ConvertOriginalClaimsFromAssertionsToOIDCDialect>
<AddUnmappedUserAttributes>false</AddUnmappedUserAttributes>
…
</OpenIDConnect>
```

[1] https://docs.wso2.com/display/IS550/Handling+Custom+Claims+with+the+JWT+Bearer+Grant+Type

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
