### ISSUE TITLE
Provide search functionality for service providers in Carbon console

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#3797]
Currently, there is no search functionality is available for service providers in the Carbon console. So it becomes difficult to find a specific service provider when the numbers of service providers exceed one page.

As the first step, search by name is sufficient as it fits most use cases.

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-identity-framework/pull/1932

**Comment by IshikaGodage** [comment]
https://github.com/wso2-support/carbon-identity-framework/pull/330 (For IS 5.2.0)
