### ISSUE TITLE
Client secret field disappears from UI after clicking cancel in OAuth application edit page

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3798]
Steps to reproduce

- create an oauth app
- click edit on oauth inbound auth settings
- click cancel

![image](https://user-images.githubusercontent.com/9883427/46494757-461c1b80-c831-11e8-887a-f922559d955c.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
