### ISSUE TITLE
Oauth audience restriction doesn't reflect after updating the audience values

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3799]
Steps to reproduce

- Create an OAuth app with audience values.
- Obtain an id_token and check the aud values. The aud values should be there.
- Then edit the app and add another aud value
- Obtain the id_token again
- Only the previous aud value is there in the id_token

**Comment by emswbandara** [comment]
Fixed in public via https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1055
