### ISSUE TITLE
[IS-KM-5.7] ClassNotFoundException when retrieving consent purposes and authorize flow in Windows 

### ISSUE THREAD

**Issue by Niveathika92** [wso2/product-is#3801]
Steps to reproduce

1. Configure APIM and IS-KM
2. Start the servers
3.  Go to stores> SignUp flow

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-event-handler-notification/pull/88
https://github.com/wso2/carbon-utils/pull/17
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/967
https://github.com/wso2/carbon-identity-framework/pull/1942
