### ISSUE TITLE
Need to update DB scripts to support mysql innodb cluster and fully test product deployment

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#3807]
Current DB scripts do not have a primary key for each table, hence when executing the schema in MySQL innodb cluster it fails as it is mandatory to have a primary key for each table schema.

Need to update the DB scrips accordingly and test for fully supporting the deployment.

**Comment by MehdiSE** [comment]
I got the same issue, ive setup mysql innoDB cluster, imported wso2 databases and i get the following error when starting the wso2 product  

ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO} -  Failed to add properties to the resource /_system/config/repository/connection/props. The table does not comply with the requirements by an external plugin.

**Comment by JonnyLewis** [comment]
Good day, is there any update on this?

**Comment by rksk** [comment]
Related https://github.com/wso2/product-apim/issues/9505

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
