### ISSUE TITLE
user store domain is not set in the challenge question path

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#3809]
Even though we passed the username with correct tenant domain and user store domain (ex  DIR/siluni@xyz.com) in change password in challenge question path

It displays the message as  "user does not exist" in the dashboard UI. even though the user exists in the secondary user store.

And following info log in the wso2carbon.log

 INFO {org.wso2.carbon.identity.recovery.password.SecurityQuestionPasswordRecoveryManager} -  initiateUserChallengeQuestion :User store domain is not in the request. set to default for user : siluni@xyz.com

Applicable version IS 5.5.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
