### ISSUE TITLE
[DOC]UserIdentityManagementAdminService can't be used if new identity event listener enabled

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3810]
If we enable **org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener**, then we can't use UserIdentityManagementAdminService for locking/unlocking. Instead we can use RemoteUserStoreManagerService as follows. 

i. Configure the "Account Locked" claim by enabling the "Supported by Default" attribute as described in document [1].
ii. Use the "setUserClaimValues" operation of the "RemoteUserStoreManagerService" to lock/unlock the user account[2]. A sample request is as follows.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org" xmlns:xsd="http://common.mgt.user.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:setUserClaimValues>
         <!--Optional:-->
         <ser:userName>test</ser:userName>
         <!--Zero or more repetitions:-->
         <ser:claims>
            <!--Optional:-->
            <xsd:claimURI>http://wso2.org/claims/identity/accountLocked</xsd:claimURI>
            <!--Optional:-->
            <xsd:value>true</xsd:value>
         </ser:claims>
         <!--Optional:-->
         <ser:profileName>default</ser:profileName>
      </ser:setUserClaimValues>
   </soapenv:Body>
</soapenv:Envelope>
```
Document [1] should be corrected with the above details.

[1] https://docs.wso2.com/display/IS530/Locking+a+Specific+User+Account#LockingaSpecificUserAccount-UsingtheAdminService

**Comment by sherenewso2** [comment]
Fixed in doc versions 5.3.0 - 5.7.0 [1] 

[1] https://docs.wso2.com/display/IS570/Locking+a+Specific+User+Account#LockingaSpecificUserAccount-UsingtheAdminService
