### ISSUE TITLE
Password reset jsp drops callback url request parameter

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-is#3814]
Following issue happens in  password reset with password policy enabled in IS . The request is initiated as in[1] with a callback url and when the password reset fails the callback url seems to be dropped in the subsequenct calls.

1. Try the password reset with invalid passwords which violate the policy
2. Enter a valid password
3. Gets redirected to the IS dashboard login page instead of callback url given

[1] - https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation=<confirmation_id>&userstoredomain=PRIMARY&username=testuser&tenantdomain=carbon.super&callback=<call_back_url>

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
