### ISSUE TITLE
Support for multiple default authentication sequences per tenant

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3817]
As an improvement for the current tenant wise default authentication sequence implementation, we can allow creating multiple default authentication sequences per tenant.

As per the current approach, tenant default sequence will be applicable for all the service providers with default authentication type. There can be use cases in an organization to apply an authentication sequence for all the public SPs, but apply another sequence with some additional secure layer, for all the private SPs. In that case, would be beneficial for a tenant admin to configure two separate default authentication sequences in the tenant and apply appropriately.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
