### ISSUE TITLE
Primary flag for email and phone number as per SCIM 2.0 spec.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#3823]
Have the possibility to use the "primary" flag in SCIM2 spec to determine which email address or phone number is set as the primary.

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/119/files
https://github.com/wso2/carbon-identity-framework/pull/1934
