### ISSUE TITLE
Extended attributes not properly update in SCIM2 patch request

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#3826]
In Identity Server 5.3.0

1.Configured SCIM2 by following https://docs.wso2.com/display/ISCONNECTORS/Configuring+SCIM+2.0+Provisioning+Connector

Then configured to support add any custom attributes by Extending the SCIM API.

Create user and then try to patch custom attribute by the following curl command.

curl -k --user admin:admin -X PATCH -d '{"schemas":[], "Operations":[{"op":"add","value": {"userName":"vindula","EnterpriseUser":{"userName":"vindula","clinid":"testMary"}}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/7858ef27-ffa2-4548-a04c-4b8a67ee251a

But response looks following

{"emails":[{"type":"work","value":"vindula_work.com"},{"type":"home","value":"vindula_home.com"}],"meta":{"created":"2018-10-12T11:02:17Z","location":"org.wso2.charon3.core.attributes.SimpleAttribute@3fcc28bd","lastModified":"2018-10-12T16:36:46Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"EnterpriseUser":{"clinid":"org.wso2.charon3.core.attributes.SimpleAttribute@3fcc28bd"},"name":{"givenName":"vindula","familyName":"jayawardana"},"id":"7858ef27-ffa2-4548-a04c-4b8a67ee251a","userName":"vindula"}s

The value is updated as following
{"clinid":"org.wso2.charon3.core.attributes.SimpleAttribute@3fcc28bd"}

It should be updated as 
{"clinid":"testMary"}

**Comment by dicastro** [comment]
I've observed the same behaviour with `givenName` and `familyName` when calling `/scim2/Me`

curl -k -H "Authorization: Bearer <USER_ACCESS_TOKEN>" -X PATCH -d '{ "schemas": [ "urn:ietf:params:scim:api:messages:2.0:PatchOp" ], "Operations": [{ "op": "add", "value": { "name": { "givenName": "test01Modif", "familyName": "test01Modif" }, "phoneNumbers": [{ "type": "mobile", "value": "555555555" }] } }] }' https://localhost:9443/scim2/Me

Response

```
{
    "emails": [
        "test01@locken.es"
    ],
    "meta": {
        "created": "2018-10-30T13:15:29Z",
        "lastModified": "2018-10-30T13:26:32Z",
        "resourceType": "User"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "name": {
        "givenName": "org.wso2.charon3.core.attributes.SimpleAttribute@639a4b5c",
        "familyName": "org.wso2.charon3.core.attributes.SimpleAttribute@6124c946"
    },
    "id": "5c4b02fa-906c-4b83-b97b-54f43c629040",
    "userName": "test01@locken.es",
    "phoneNumbers": [
        {
            "type": "mobile",
            "value": "555555555"
        }
    ]
}
```

The value is updated as following:

```
"name": {
    "givenName": "org.wso2.charon3.core.attributes.SimpleAttribute@639a4b5c",
    "familyName": "org.wso2.charon3.core.attributes.SimpleAttribute@6124c946"
}
```

It should be updated as:

```
"name": {
    "givenName": "test01Modif",
    "familyName": "test01Modif"
}
```
