### ISSUE TITLE
Enabling Multi Factor Authentication for User Association via Dashboard

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-is#3829]
Multi-Factor Authentication for User Association is not available for associating federated accounts or for associating local accounts using the dashboard association gadget.
There is a possibility of security attacks if an attacker already has an account in the system with login permission (if self-signup is enabled) due to not having MFA with User Association.

Therefore, the need of having MFA for User Association via the Dashboard has been raised.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
