### ISSUE TITLE
When navigate 'back' after successful login the server direct to login page in `wso2is-km-5.3.0`

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [wso2/product-is#3832]
When user get successfully logged in as follows 
![47016387-3247b200-d16d-11e8-9c9f-c7873ccc7605](https://user-images.githubusercontent.com/16388948/47197772-e6238a00-d385-11e8-9f4e-5e5c7d1567ee.png)

and navigate 'back', login page is given as follows,
![47016422-48557280-d16d-11e8-8312-ae723709e23f](https://user-images.githubusercontent.com/16388948/47197776-ed4a9800-d385-11e8-8ae3-dd3d20a94de0.png)

This is a bug as the user has already logged in, navigating 'back' should redirect him to 'homepage' or etc.

Upon above when the user tries to log in again with correct credentials following error is thrown (this is ok as the SAML token has already being used for login)
![47016530-94081c00-d16d-11e8-8ad1-9532336ee962](https://user-images.githubusercontent.com/16388948/47197779-f3407900-d385-11e8-9302-3c45620c480f.png)

upon above when navigate directly to 'https://localhost:9443/dashboard/index.jag',  the user has already logged in as follows and the *user portal* is provided (this is possible as the session is not closed)
![47016915-91f28d00-d16e-11e8-9230-567555ff00ab](https://user-images.githubusercontent.com/16388948/47197789-fcc9e100-d385-11e8-9ad3-03e7a359e703.png)

This is reproduciable in latest wum update `1539458974075` timestamp `wso2is-km-5.3.0` distribution.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
