### ISSUE TITLE
Need to Improve the Implementation of SCIM2 Multi Attribute Filter for Mysql DB

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#3834]
In SCIM2 multi-attribute user filter implementation, we need to improve the code base where the filter query contains multi-group and multi-claim filtering. So far it has been done in java level as a temporary fix when providing the fix for wso2/product-is#3611.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
