### ISSUE TITLE
SSO - Loading WSO2 IS in an iframe of an application for Kibana Dashboard

### ISSUE THREAD

**Issue by subhomoymukherjee** [wso2/product-is#3835]
I am trying to load a `kibana` dashboard in my application using `iframe` and implementing `saml sso `using `wso2 IS`.

Now, I want to load the wso2 IS in the iframe and have tried using the X-Frame-Options but it didn't help.

In the Kibana config.yml file, I have tried configuring the x-frame. Is there any particular solution to this or any particular configuration?

Any help is appreciated. Thanks in advance.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
