### ISSUE TITLE
[Doc] Need more info on configuring SP and IdP using config files

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#3841]
The document on Configuring a SP and IdP Using Configuration [1] does not describe the meaning of the elements in the config files clearly.

For example, it is hard to find what values can be used for <Name> under <FederatedAuthenticatorConfig>.

[1] https://docs.wso2.com/display/IS570/Configuring+a+SP+and+IdP+Using+Configuration+Files

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
