### ISSUE TITLE
Getting intermittent authentication exception when using TOTP authenticator

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#3844]
set up
IS cluster fronted by load balancer (version 5.6.0)
TOTP configured as second factor authenticator
When trying to validate OTP with the authenticator, it is giving authentication failed exception intermittently when we provide the correct code.
This issue gets resolved after clearing the secret key claim.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
