### ISSUE TITLE
Conformation code invalidation does not delete relevant properties from the DB

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#3845]
**Description:**
When user signs up via self-signup, the conformation code and related properties are stored in the registry. Then, user clicks the conformation link, the resource entry is deleted from DB but the attributes are not getting deleted from relevant DB tables.

**Steps to reproduce:**

1. Configure [Self Sign Up and Account Confirmation](https://docs.wso2.com/display/IS520/Self+Sign+Up+and+Account+Confirmation) and register a user
2. Check REG_RESOURCE, REG_RESOURCE_PROPERTY & REG_PROPERTY tables from the DB
3. Click the confirmation link and verify the user
4. REG_RESOURCE entry is deleted, but REG_RESOURCE_PROPERTY & REG_PROPERTY entries still exist in the DB

Related issues
https://github.com/wso2/carbon-kernel/issues/1866

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
