### ISSUE TITLE
SMS OTP doesn't work when the first step is a federated authenticator and the user is already associated

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#3846]
Steps to reproduce in 5.7.0 pack

Configure Facebook and SMS otp IDPs. Enable JIT for Facebook IDP
Create an SP and add Facebook as an IDP. 
Login to SP through FB. Update the phone number of the JIT Provisioned user.
Update the Service provider to have SMS OTP as the second factor.
SMS OTP is not prompted.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
