### ISSUE TITLE
portal-dashboard-designer.js not adding rows with less then three widgets

### ISSUE THREAD

**Issue by SingularTechnology** [wso2/product-is#3849]
There is a line in Javascript saying
if its the third widget in a row add the widget to the row and to the layout. else it will only add the widget to the row and not the layout. So if you have less then 3 widgets on a row it will never be added to the layout.

Asking for a fix on line 61 of portal-dashboard-designer.js:

` if((((i+1)%3)==0)&&(i!=0))   // wrong if clause
{
                               elements.append(el);
                               $("#layouts_grid").append(elements);
                               elements = $('<div class="row row-gutter-30"></div>');
}else{
elements.append(el);
}
`

should be 

` if((((i+1)%3)==0)&&(i!=0) || (i+1) == userWidgets.length) // correct one
 `

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
