### ISSUE TITLE
Migration is needed for new event properties for 5.8.0

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#3853]
Migration is required for the pr [1] for IS 5.8.0

[1] https://github.com/wso2/carbon-identity-framework/pull/1931/

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
