### ISSUE TITLE
Error in IS analytics editor node when creating a Siddhi app

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#3857]
I tried to create a siddhi application using WSO2 IS analytics instead of WSO2 SP by following the steps in [1]. 

The siddhi application gets deployed successfully when deploying it using the worker runtime in WSO2 IS analytics but it gives the following error when trying to create the application using the editor runtime: 

**Error:** [2018-10-23_16-15-20_687] ERROR {org.wso2.extension.siddhi.io.http.util.HttpIoUtil} - Bootstrap configuration is not in expected format please insert them as 'key1:val1','key2:val2' format in http source. (Encoded) 

**Siddhi app:** 
`@App:name("IS_ANALYTICS_RiskBasedLogin")
@App:description("Description of the plan")
 
@Source(type = 'http', receiver.url="http://localhost:8281/RiskBasedLogin/TransactionInputStream", basic.auth.enabled='false', @map(type='json', @attributes(username='$.event.username', transaction='$.event.transaction')))
define stream TransactionInputStream (transaction double, username string);
 
@Source(type = 'http-request', source.id='testsource', basic.auth.enabled='true', parameters="'ciphers:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256', 'sslEnabledProtocols:TLSv1.1,TLSv1.2'", receiver.url="https://localhost:8280/RiskBasedLogin/InputStream", @map(type='json', @attributes(messageId='trp:messageId',username='$.event.username')))
define stream InputStream (messageId string, username string);
 
@sink(type='http-response', source.id='testsource', message.id='{{messageId}}', @map(type='json'))
define stream OutputStream (messageId string, username string, riskScore int);
 
define stream TempStream (messageId string, username string, sumTransactions double);
 
from TransactionInputStream#window.time(5 min)
right outer join InputStream#window.length(1) unidirectional
on TransactionInputStream.username == InputStream.username
select InputStream.messageId, InputStream.username, sum(transaction) as sumTransactions
group by messageId, InputStream.username
insert into TempStream;
 
from TempStream
select messageId, username, ifThenElse(sumTransactions > 10000, 1, 0) as riskScore
insert into OutputStream;`

[1] https://docs.wso2.com/display/IS570/Using+WSO2+Stream+Processor+for+Adaptive+Authentication

@dilin993 @madurangasiriwardena

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
