### ISSUE TITLE
Error on SCIM PATCH operation when all SCIM meta claims are empty

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#3860]
Error in performing the SCIM PATCH operation on user resource when all of following claims are not mapped to local claims which contain values.

- urn:ietf:params:scim:schemas:core:2.0:meta.created
- urn:ietf:params:scim:schemas:core:2.0:meta.location
- urn:ietf:params:scim:schemas:core:2.0:meta.lastModified
- urn:ietf:params:scim:schemas:core:2.0:meta.resourceType
- urn:ietf:params:scim:schemas:core:2.0:meta.version

**Steps to Reproduce**

1. Change claim mapping for all the above mentioned claim uris to local claims which don't contain values. Then the response of GET user will not return the meta attribute object.
`curl -k --user admin:admin https://localhost:9443/scim2/Users/44793f15-0265-45f7-984d-61972a3f0805`

2. Try patch operation on a user

`curl -k --user admin:admin -X PATCH -d '{"schemas":[], "Operations":[{"op":"add","value": {"nickName": "b1"}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/44793f15-0265-45f7-984d-61972a3f0805`

Following error is returned, but no proper error message or logs are written. 

`{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","detail":"Error in performing the patch operation on user resource.","status":"500"}`

Internally following NPE is thrown because following line [1] is trying to access the META object and the getAttribute() returns null if meta is not found.

`validatedObject.setAttribute(oldObject.getAttribute(SCIMConstants.CommonSchemaConstants.META));`

> java.lang.NullPointerException
> 	at org.wso2.charon3.core.objects.AbstractSCIMObject.setAttribute(AbstractSCIMObject.java:70)
> 	at org.wso2.charon3.core.schema.ServerSideValidator.validateUpdatedSCIMObject(ServerSideValidator.java:153)
> 	at org.wso2.charon3.core.utils.PatchOperationUtil.doPatchAdd(PatchOperationUtil.java:794)
> 	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.updateWithPATCH(UserResourceManager.java:564)
> 	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.patchUser(UserResource.java:360)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
> 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
> 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:267)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> ....
> 

[1] https://github.com/wso2/charon/blob/v3.0.7/modules/charon-core/src/main/java/org/wso2/charon3/core/schema/ServerSideValidator.java#L151

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
