### ISSUE TITLE
Error pages are not shown properly

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3863]
1. If we have repeated parameters in the authorization request an empty page is shown without any error messages.
2. If we send a wrong client id or inactive state client id through authorization request the response is printed in the web page as 
"{"error_description":"A valid OAuth client could not be found for client_id: omK9KZqwsJEfy4m01JN8oxfcRZkbEa","error":"invalid_client"}"
![printed_in_the_web_page](https://user-images.githubusercontent.com/20336761/47478864-bd4d3a00-d848-11e8-8013-452c08bb207d.png)
3. When using password recovery if the password violates the policy empty page is shown
![blank_page](https://user-images.githubusercontent.com/20336761/47478873-c50cde80-d848-11e8-804a-6a4b402e572f.png)

These need to fixed.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
