### ISSUE TITLE
Localization of error messages with variables are not available

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3865]
If the error messages contain variables then localization can't be done using the procedure mentioned in [1]

Example:- if the error message is "Unable to find an user with username: **USER1** in the system", then we can't follow the procedure [1] because we don't know the username prior.

[1] https://docs.wso2.com/display/IS560/Localization+Support+in+Identity+Server

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
