### ISSUE TITLE
Make SelfContained Access token and ID token consistent. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#3869]
There are some inconsistent behaviors in the self-contained Access token and ID Token. One is the issuer claim in JWT.

If we change the "Identity Provider Entity ID" from Resident IDP under OAuth 2.0, it reflects the ID token, but not to the self-contained Access token. 

Have to change <IDTokenIssuerID> element in identity.xml to change the issue claim in the self-contained Access token. 

Also, it is required to fix https://github.com/wso2/product-is/issues/3718

**Comment by hpmtissera** [comment]
Looks like this issue is already fixed. 


![](https://lh3.googleusercontent.com/-NmS6gLs09Fc/XIiay1OP54I/AAAAAAAA6Zw/SXgk72snnlM6QeKXcZ1rwPqNjI3nAJJ9ACK8BGAs/s0/Screen%2BShot%2B2019-03-13%2Bat%2B14.52.55.png)

**Comment by darshanasbg** [comment]
Sub-issue is reported at: https://github.com/wso2/product-is/issues/4669

**Comment by DMHP** [comment]
@hpmtissera 
Thanks for your contribution. I am closing the issue as the original issue has already fixed.
@IsuraD 
Please re-open if you have any additional issues regarding this.

**Comment by darshanasbg** [comment]
as per the screenshot shared by @hpmtissera, still, the subject format is not consistent.

@DMHP Shall we have a look on above?

**Comment by IsurangaPerera** [comment]
The subject format is consistent in 5.8.0-Alpha3

Still, there are some claims such as amr claim which is not common to both tokens. Since the amr token contains authentication data one can argue that it should not be included in the access token. We may have a separate feature which allows users to decide which claims are to be included in the token.

**Comment by malithie** [comment]
Can we check standard claims except user claims, that should be returned with id_token is consistent. 
For an access token one can argue that user claims should not be reflected. Let's create a separate issue for that discussion

**Comment by IsurangaPerera** [comment]
Refer wso2/product-is#4908
