### ISSUE TITLE
Authorization issues with ChallengeQuestionManagementAdminService::setUserChallengeAnswers operation

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#3871]
We are allowing to set the challenge answer for a user if,

- authenticated user and the user sent in request payload is the same.
- authenticated user has /permission/admin/manage/identity permission.

Seems neither of these checks happens properly. 

The authorization check should be done for the logged in user instead of the authenticated user [1].

Also, if the user is authenticated with the secondary user store domain appended to the user name, the user validation again fails.

[1] - https://github.com/wso2-extensions/identity-governance/blob/v1.1.42/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/services/ChallengeQuestionManagementAdminService.java#L191-L200

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-governance/pull/259
https://github.com/wso2-extensions/identity-governance/pull/258
