### ISSUE TITLE
[SCIM2] `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` used by IS 5.6.0 contains properties not in IETF specification

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#3872]
The `askPassword` option used by IS 5.6.0 (on line 138 of `scim2-schema-extension.config`) is set to be included as part of `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`. This conflicts with the standard as registered in IANA, which references RFC 7643 section 4.3. Thus, to prevent compatibility problems with client libraries, this should be included as a separate wso2-specific extension.

**Comment by hauntingEcho** [comment]
This may be a duplicate of #3488
