### ISSUE TITLE
Errors during migration from IS 5.2.0 to 5.6.0 in H2 DB

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-is#3876]
When running the IS migration client to migrate from IS 5.2.0 to 5.6.0 in H2 DB, the following errors are encountered. This should be fixed. 

```
java.lang.Exception: Error occurred while executing :  ALTER TABLE SP_INBOUND_AUTH ADD COLUMN INBOUND_CONFIG_TYPE VARCHAR(255) NOT NULL
```
```
java.lang.Exception: Error occurred while executing :  DROP INDEX IF EXISTS IDX_AT ON IDN_OAUTH2_ACCESS_TOKEN
```

The relevant PR is https://github.com/wso2-support/product-is/pull/217

**Comment by DMHP** [comment]
Closing this, as this is fixed.
