### ISSUE TITLE
Username column max length mismatch when saving access token

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-is#3881]
In the openid connect flow, when saving usernames for an access token in the AUTHZ_USER column in the IDN_OAUTH2_ACCESS_TOKEN table, we will not able to generate access tokens for username length exceeds 100. But in the UM_USER table, the UM_USER_NAME allows saving usernames with length up to 250. Therefore when trying to store the access token along with the username it fails to store since the username length exceeds the column limit.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
