### ISSUE TITLE
[Bug] Modification to the Destination URLs in the Resident IdP doesn't reflect in the SAML metadata

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#3883]
When the customer modifies the Destination URLs of a tenant-specific Resident IdP, it is not reflected in the returned metadata of that tenant's Resident IdP.

 We need to update idp-metadata file.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
