### ISSUE TITLE
[Feature] Resident IdP SAML metadata validation

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#3885]
Need a feature to sign the Resident IdP SAML metadata so the external SPs can validate the Resident IdP metadata.

Currently, we don't sign the Resident IdP metadata, so it can't be validated at the SP. As discussed internally we need to sign the metadata and include the signed hash in the metadata. According to the SAML-2.0-Metadata specification, it is recommended that at least the **root element** of a metadata instance be signed. 

We need to sign the Resident IdP SAML metadata returned.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
