### ISSUE TITLE
[Feature] Enabling/Disabling the signing request in the Resident IdP SAML metadata

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#3886]
Currently, we don't have a tag in the Resident Identity provider metadata to be enabled/disabled, to request from the Service Provider to send authentication request signed or not.

It should be something like this **<md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">**

According to this **WantAuthnRequestsSigned** parameter in the metadata, SP should be able to figure out whether to send SAML authentication request signed or not.

Currently, we don't have this parameter in the metadata returned. So we need to support this feature for tenant-based Resident Identity Provider metadata with different tenant domains and accessing the metadata.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
