### ISSUE TITLE
UserID claim URI and role mapping not working in seamless JIT mode

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#3887]
UserID claim URI and role mapping not working in seamless JIT mode
- Not working in Standard dialect with userID claim URI
- Not working in Standard dialect with role mapping
- Not working in Non-Standard dialect with userID claim URI
- Not working in Non-Standard dialect with userID claim URI

**Comment by ashensw** [comment]
Refer: https://github.com/wso2/product-is/issues/3870
Related PR: https://github.com/wso2/carbon-identity-framework/pull/1956
