### ISSUE TITLE
Identity claims are not included in the SAML2 service provider's response

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-is#3895]
**Steps to reproduce**

- IS version - 5.6.0
- Use an Active Directory User Store.
- Enable email as username.
- Enable multi-attribute logging for email as username and sAMAccountName as username.
- Create a claim with the claim URI http://wso2.org/claims/identity/cocoID under http://wso2.org/claims dialect while having Mapped Attribute as givenName (Mapped Attribute of a standard claim).
- Create another claim with claim URI http://wso2.org/claims/identity/ID123 under http://wso2.org/claims dialect having the Mapped Attribute as emailVerified (Mapped Attribute of an identity claim).
- Create a user and fill the user profile setting values to cocoID and ID123 claims as well.
- Create a SAML2 service provider and enable Attribute Profile.
- Set the created two claims under the service provider Claim Configuration.
- Log in to the sample application giving consent to the two claims.

**Expected output:** Should be able to retrieve all the service provider requested claims when logging with email as username and sAMAccountName as username both.

**Actual output:** All the requested claims can be retrieved when logging with email as username.
When logging with sAMAccountName as username http://wso2.org/claims/identity/ID123 claim (Having a Mapped Attribute of an identity claim) cannot be retrieved while http://wso2.org/claims/identity/cocoID claim can be retrieved along with other standard claims (Non identity claims).

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
