### ISSUE TITLE
Additional Security for SAML2/JWT Bearer Assertion Grant Flows

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#3897]
**Status Quo**

Let's say there are two legitimate service providers A and B. Both A and B are registered in IdP X as SAML2 service providers. Both A and B are enabled to exchange SAML2 assertion with WSO2 IS using SAML2 Bearer Assertion grant flow. To do this, WSO2 IS's token endpoint is set as an audience and recipient in the SAML2 assertion for A and B.

When we validate the SAML2 assertion sent to the token endpoint in IS we simply validate whether the assertion is issued by a trusted IdP, whether the client sending it is a legitimate client and whether the assertion is intended to be used for exchanging to an OAuth2 access token by checking the list of audience contains the token endpoint (or some acceptable alias). We don't validate whether this assertion was in fact sent by the intended recipient for the assertion.

This implementation is of course compatible with the specifications.

**Problem**

If B somehow is able to get hold of the assertion intended to A, and send it to the token endpoint with B's client credentials, WSO2 IS will still issue a valid OAuth2 access token.

**Proposed Solution** 

If sharing of SAML2 assertions between OAuth2 clients are not required, we can have an option in the token endpoint to validate the client_id identified from he basic auth header (or any other means depending on the client authentication mechanism), against the client_id in the SAML2 assertion. To do this, IdP X has to support adding multiple additional audiences into the SAML2 assertion. Also the client_id issued by WSO2 IS (which is public info) needs to be configured as an audience in IdP X. I don't see any issue with this either.

This will allow us to validate that the intended recipient of the SAML2 assertion is the one who is in fact sending it to the OAuth2 token endpoint as well, to exchange to an OAuth2 access token.

**Benefit**

This will give us a way to make sure that the OAuth2 client who requesting the access token, has obtained it by authorized means (not stolen).

**Reference**
[1] "[IAM] Additional Security for SAML2/JWT Bearer Assertion Grant Flows" in architecture@wso2.org

P.S. this is not just for IS service providers where SAML2 and OAuth2 inbound configurations can be done for the same service provider. This proposal goes beyond that for any OAuth2 authorization server.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
