### ISSUE TITLE
Missing primary key in some tables

### ISSUE THREAD

**Issue by SaubhagyaW** [wso2/product-is#3898]
Mysql InnoDB cluster requires a primary key for each table to work and below tables don't set a primary key.
REG_RESOURCE_COMMENT
REG_RESOURCE_RATING
REG_RESOURCE_TAG
REG_RESOURCE_PROPERTY
UM_SHARED_USER_ROLE

**Note:** Any migration scripts related to this should be fixed as well.
Issue was identified in IS 5.3.0, other versions should also be verified.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
