### ISSUE TITLE
Update session data cleanup procedure call in documentation

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#3901]
The session data cleanup procedure syntax in the documentation needed to be updated in documentation[1]. (IS 5.3 to 5.7) with procedure call in the GitHub repo[2].

[1] - https://docs.wso2.com/display/IS530/Data+Purging
[2] - 
https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mysql-5.7/session-data-cleanup.sql

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Comment by rksk** [comment]
Re-opening since this needs to be fixed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
