### ISSUE TITLE
UI and Service validation for restriction of adding claim config without attribute for primary user store

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3904]
Include a validation to restrict the ability to save the claim configurations without having a attribute mapping for primary user store.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
