### ISSUE TITLE
Use correct TLS certificates to invoke the DCRM service using mutual authentication

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3905]
Use correct TLS certificates to invoke the DCRM service using mutual authentication :
Different organizations can invoke the OpenID Connect Dynamic Client Registration service without the need to know username/password of a user who's in IS, with relevant permissions(/permission/admin/manage/identity/applicationmgt/), but just providing correct private key / certificate issued by known Certification Authority.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
