### ISSUE TITLE
Consider the certificate in SAML metadata file as the SP certificate

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3907]
When adding SAML configuration of a SP, currently it's possible to add from a metadata file which has the application certificate(s), but it's not considered as the SP certificate.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
