### ISSUE TITLE
Add support for PBKDF2 and adaptive one way functions(Argon2,scrypt,bcrypt) 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3912]
Add support for PBKDF2 which is a “password-strengthening algorithm” that uses a password, a variable-length salt and an iteration count and applies a pseudorandom function to these to produce a key. 
Support for adaptive one way functions(Argon2,scrypt,bcrypt) in https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Impose_infeasible_verification_on_attacker.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
