### ISSUE TITLE
Add "OAUTH2TokenUrl" and "OAuth2AuthzUrl" property key changes to IS 5.0.0 - 5.1.0 migration

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3915]
In IS 500, token endpoint of the OpenIDConnect authenticator configuration is being persisted against 'OAUTH2TokenUrl' property key and authorization endpoint is being persisted against 'OAuth2AuthzUrl'. But in IS 510, these property keys are being changed to 'OAuth2TokenEPUrl' and 'OAuth2AuthzEPUrl' respectively. Migration with respect to these changed property key values has been missed in IS 500 to IS 510 migration. Thus, the UI will not populate the token endpoint and authorization endpoint values, as the values in the database are not persisted against the expected property key values.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
