### ISSUE TITLE
5.1 -> 5.3 migration rename some wso2 claims

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3927]
In IS 5.2.0 all the claims are mapped only to a mapedAttribute. But from IS 5.3.0 , all the claims in other dialects are mapped to a claim in WSO2 dialect. During a migration from 5.2.0 to 5.3.0, if the two mapped attributes in the wso2 dialect and the other dialect is different, the migration client itself should create a new local claim to keep this association between wso2 dialect.
As an example:
In 5.2.0,

```
<Dialect dialectURI="http://wso2.org/claims">
                                <ClaimURI>http://wso2.org/claims/streetaddress</ClaimURI>
                                <DisplayName>Address</DisplayName>
                                <AttributeID>streetAddress</AttributeID>

<Dialect dialectURI="http://wso2.org/oidc/claim">
                                <ClaimURI>street_address</ClaimURI>
                                 <DisplayName>Street Address</DisplayName>
                                 <AttributeID>street</AttributeID>
```

Since these two mapped attributes (streetAddress and street) are different it is difficult to create an association between oidc claims and wso2 local claims during 5.3.0 migration. Therefore, from the migration client, it should create a new local claim "http://wso2.org/claims/migration_streetaddress_73622" to create the association between two dialects.​ But seems like there is an issue in creating a new claim, instead it rename the existing wso2 claim URI.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
