### ISSUE TITLE
Last Modified Time in the claim

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-is#3928]
The time value gets in the system and appends z end of the time. So the value covert to UTC time. But the value generated from the system timezone.

**Comment by emswbandara** [comment]
@Abilashini is this fixed in master?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
