### ISSUE TITLE
[Doc]Schedule task for postgresql

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3929]
By default there is no way to schedule task for posgtgresql. If we want to schedule a task then need to schedule cron jobs using \[1]. This should be included in the documentation \[2].

\[1] https://github.com/citusdata/pg_cron
\[2] https://docs.wso2.com/display/IS530/Removing+Unused+Tokens+from+the+Database

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
