### ISSUE TITLE
Additional custom claims are not retrieving from UserInfo endpoint 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3930]
Can get family_name, emailaddress, etc, but the custom claim is not returned.
Cause : Several leading and trailing blank in the openid property value in /_system/config/oidc registry location.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
