### ISSUE TITLE
[Doc] Explain the reason for Authentication.Policy.Password.Reset.Time.In.Days property

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3932]
In doc \[1] we have to mention why we need to configure Authentication.Policy.Password.Reset.Time.In.Days property and what will happen if we increase or decrease the value.

\[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+Password+Policy+Authenticator

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
