### ISSUE TITLE
logging in at `/carbon/admin` results in 405 failure retrieving `favicon.ico`

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3933]
On a fresh installation of 5.6.0, going to `https://localhost:9443/carbon/admin` and logging in will bring you to a blank screen.  looking at the network tab reveals a 405 error retrieving `favicon.ico`.

This page should either function as expected, or redirect the user to `/carbon/admin/index.jsp` (which does function as expected)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
