### ISSUE TITLE
'nonce' parameter validation is done at the endpoint

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#3938]
### Background
> According to the [ OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#RequestParameterValidation), 'nonce' parameter validation is done once all the request parameters are assembled from both OAuth request and the request object.

### Issue
> 'nonce' parameter validation is done at the endpoint once all the parameters are assembled. This validation needs to be moved to a proper validator class.

### Reference
> [nonce validation](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/37ada5b79fa48e5a945e18c057cf50882cd505c6/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L1215)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
