### ISSUE TITLE
[Doc]Twilio as the service provider during SMS OTP not working

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3940]
In \[1] point 10 click on "Click here to configure Twilio as the service provider.". It has following value in the HTTP Payload.
 
From={FROM_NUM}

it should be changed to

From=urlencode{FROM_NUM}

\[1] https://docs.wso2.com/display/IS540/Configuring+SMS+OTP

**Comment by Nashaath** [comment]
Fixed this in doc versions 5.3.0 through 5.8.0
