### ISSUE TITLE
[Doc]Point to correct RFC link for JWT

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#3943]
In the documentation related to self contained access tokens [1], under the section "Configuring WSO2 Identity Server to issue self-contained access tokens" in step 4, in the section related to "Response" it points to a link "JSON Web Token (JWT)."  When you click that link it directts to an old draft version [2]of the JWT specification.

But now the complete RFC of the JWT specification is relased as a RFC [3].
We need to point to [3] for "JSON Web Token (JWT)." link.

This need to be updated on all the versions.

[1]https://docs.wso2.com/display/IS580/Self-contained+Access+Tokens
[2]https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-16
[3]https://tools.ietf.org/html/rfc7519

**Comment by Nashaath** [comment]
Fixed in doc versions 5.4.0 through 5.8.0
