### ISSUE TITLE
Invalid error code return when using malformed request to create scim2 bulk users

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#3947]
**Description** - Using a malformed request to provision bulk users return invalid status code as 200 where 400 is expected.

**Tested Environement**
IS 5.8.0-m6
DB - H2
JDK - 8
Ubuntu 15.10

**Steps to Reproduce**
1. Start the IS server
2. Send the following request to create multiple users using scim2 API (https://localhost:9443/scim2/Bulk)
```
{  
   "failOnErrors":1,
   "schemas":[  
      "urn:ietf:params:scim:api:messages:2.0:BulkRequest"
   ],
   "Operations":[  
      {  
         "method":"POST",
         "path":"/Users",
         "bulkId":"qwerty",
         "data":{  
            "schemas":[  
               "urn:ietf:params:scim:schemas:core:2.0:User"
            ],
            "Name":"Kris100",
            "password":"krispass"
         }
      },
      {  
         "method":"POST",
         "path":"/Users",
         "bulkId":"qwerty",
         "data":{  
            "schemas":[  
               "urn:ietf:params:scim:schemas:core:2.0:User"
            ],
            "userName":"Kris101",
            "password":"krispass"
         }
      }
   ]
}
```
3. Response 

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:BulkResponse"
    ],
    "Operations": [
        {
            "bulkId": "qwerty",
            "method": "POST",
            "response": "{\"schemas\":[\"urn:ietf:params:scim:api:messages:2.0:Error\"],\"scimType\":\"invalidValue\",\"detail\":\"Required attribute userName is missing in the SCIM Object.\",\"status\":\"400\"}",
            "status": {
                "code": 400
            }
        }
    ]
}
```

**Expected Results**
Expected to get the **400 Bad Request**

![scim2statuscode](https://user-images.githubusercontent.com/14962228/48260664-44ea9980-e442-11e8-92d6-1000db390b10.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
