### ISSUE TITLE
Error occured in adaptive authentication script

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#3950]
**Description:**

I want to write an adaptive authentication script such that consider a user's continuous failed login attempts and step up the authentication (provide an additional authentication script) after a specific number of failed attempts. Also, I want to consider the failing continuity for several days. 'failed login attempts' claim is used to keep track the number of failed login attempts of a user.

This is the script I have written.
```
var invalidAttempts = 4;
var failedLoginAttemptsClaim = 'http://wso2.org/claims/identity/failedLoginAttempts';

function onLoginRequest(context) {
    doLogin(context);
}

function doLogin(context) {
  executeStep(1, {
	onSuccess : function(context) {
	  var user = context.steps[1].subject;
	  var failedLoginAttempts = user.localClaims[failedLoginAttemptsClaim];
	  if(failedLoginAttempts >= invalidAttempts) {
		executeStep(2);
	  }
	   user.localClaims[failedLoginAttemptsClaim] = 0;
	},
	onFail: function(context) {
	  var user = context.steps[1].subject;
	  user.localClaims[failedLoginAttemptsClaim] =(parseInt(user.localClaims[failedLoginAttemptsClaim]) + 1).toString();
	  doLogin(context);
	}
  });
}
```
However, when a user failed his/her login it gives this error.

![error-for-git-issue](https://user-images.githubusercontent.com/25483865/48297598-8f1b5b80-e4d2-11e8-9335-a27bfe493112.png)

The reason for the error seems like the unavailability to get the user under `onFail` method.
Any option to set failedLoginAttemptsClaim of user under onFail method?

**Affected Product Version:**
wso2is-5.7.0

**Steps to reproduce:**

1. Get wso2is-5.7.0 pack.
2. Setup the samples using step01 in [here](https://docs.wso2.com/display/IS570/Configuring+a+Service+Provider+for+Adaptive+Authentication).
3. Navigate to <PRODUCT_HOME>/bin in terminal and execute the `sh wso2server.sh`.
4. Configure a service  provider for adaptive authentication following the step02 in [here].(https://docs.wso2.com/display/IS570/Configuring+a+Service+Provider+for+Adaptive+Authentication)
5. Enter the following script to the service provider's editor for script-based adaptive authentication.

```
var invalidAttempts = 4;
var failedLoginAttemptsClaim = 'http://wso2.org/claims/identity/failedLoginAttempts';

function onLoginRequest(context) {
    doLogin(context);
}

function doLogin(context) {
  executeStep(1, {
	onSuccess : function(context) {
	  var user = context.steps[1].subject;
	  var failedLoginAttempts = user.localClaims[failedLoginAttemptsClaim];
	  if(failedLoginAttempts >= invalidAttempts) {
		executeStep(2);
	  }
	   user.localClaims[failedLoginAttemptsClaim] = 0;
	},
	onFail: function(context) {
	  var user = context.steps[1].subject;
	  user.localClaims[failedLoginAttemptsClaim] =(parseInt(user.localClaims[failedLoginAttemptsClaim]) + 1).toString();
	  doLogin(context);
	}
  });
}
```

**OS, DB, other environment details and versions:**   
OS: Ubuntu 16.04 
DB: H2

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
