### ISSUE TITLE
Requirement of an additional claim for local claim dialect

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#3951]
**Requirement:**

Considering a user's continuous failed login attempts and stepping up the authentication (providing an additional authentication) after a specific number of failed attempts is a common use case in adaptive authentication. As well as, failing login attempts continued  for several days is an important factor to consider. When writing an adaptive authentication script for this case, failed login attempts claim can be used. However, instead of setting the value to it from the script, enabling account locking under resident IDP --> login policies will be able to update it automatically. The problem is, when a successful user login happens, the failed login attempts claim is reset to 0. 
When comparing the failed login attempts with the allowed number of failed attempts before step up, failed login attempts claim is 0 instead of the required value. So the comparison cannot be performed. This issue can be resolved using an additional local claim to store the number of failed login attempts before resetting it to 0.

**Comment by nilasini** [comment]
Even though the fix had been done the claim needs to be added in upcoming releases.

**Comment by pulasthi7** [comment]
Need this PR for the login attempt based authentication template

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
