### ISSUE TITLE
Embedded userstore does not support 'middleName' attribute

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#3954]
**Description**
Unable to include a user with 'middleName" attribute using scim2 as the default embedded IS userstore does not support the 'middleName' claim attribute.

**Tested Environment**
IS 5.8.0 - m6
DB - h2
Ubuntu 15.10

**Steps to reproduce the issue**
1. Enable Middle Name claim attribute
2. Update the user's profile with the middle name 

**Actual Behaviour**
Unable to update the middle name for the user
```
[2018-11-12 10:54:26,125] ERROR {org.wso2.carbon.identity.user.profile.ui.client.UserProfileCient} -  org.apache.axis2.AxisFault: Profile information could not be updated in LDAP user store for user : dinuka
```

**Expected Behaviour**
It should be possible to add the users middle name and supported by the default embedded user store

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
