### ISSUE TITLE
Unable to update "identity" claims via management console or SOAP APIs when PRIMARY user store is read-only

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#3955]
The requirement is to use read-only LDAP as the primary authentication user store and extend the users with some attributes. And these attributes need to retrieve via OAuth2/OpenID Connect id_token and userinfo.

When tried to use "identity" claims and store the value in internal JDBC store, using JDBCBasedIdentityDataStore, the management console's UI fields are not editable if the user's user store is read-only. Also when using the SOAP API, they get an error: 30002 - InvalidOperation Invalid operation. 

== Steps to reproduce the issue ==

1. Edit [IS_HOME]/repository/conf/user-mgt.xml and make the UserStoreManager as read only LDAP. (uncomment the ReadWriteLDAPUserStoreManager)
2. Go to Identity Management Console -> Claims -> Add -> Add Local Claim
3. Create a new claim by defining below values.

```Claim URI - http://wso2.org/claims/identity/province
Display Name - Province
Description - This is the user's province 
Mapped Attribute - Primary & province
Supported by Default - tick
```

4. Go to a particular user's profile and check whether you can add a value for this attribute. Since this claim is store as identity claim, it should allow user to add a value even the userstore is read only. But with the issue, user can't add a value for this attribute.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
