### ISSUE TITLE
support intermediate certificate validation

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#3956]
In a certificate-based request, the incoming certificate should be issued by an intermediate certificate. The intermediate certificates CN should be added to a config where it will be read and matched with incoming certificate' issuer CN. 

Currently, the user is taken from the "WSO2-Identity-User" instead the user should be specified in an attribute in the incoming certificate. The selected attribute should also be configurable.

**Comment by janakamarasena** [comment]
Need to add new identity.xml configuration[1] to IS 5.8.0 migration docs.

[1] - https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L976-L986

**Comment by nilasini** [comment]
Fixed with 
https://github.com/wso2/carbon-identity-framework/pull/1962
https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/62

Created a migration doc issue to track the documentation update [1]

[1] https://github.com/wso2/product-is/issues/4633
