### ISSUE TITLE
check if question-based recovery is enabled before displaying option to end-user

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3965]
Currently, the recovery endpoint [checks if email-based recovery is enabled](https://github.com/piecestech/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/webapp/password-recovery.jsp#L101) and decides whether or not to present that option to the end-user.  However, it does not perform the same check for question-based password reset.

Per [NIST standards](https://pages.nist.gov/800-63-FAQ/#q-b7), recovery questions are not an acceptable form of authentication.  For those users which must therefore disable them, the frontend should react to that choice.

**Comment by hauntingEcho** [comment]
The configuration that this is referring to is in "identity.xml", setting "Server.Recovery.Question.Password.Enable" to "false" should cause the gadget not to be displayed

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
