### ISSUE TITLE
do not show Recovery Questions dashboard widget to end-user if question-based recovery is disabled

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#3966]
Currently, with question-based account recovery disabled, the "Account Recovery" dashboard widget is still displayed to end-users.

related to #3965

**Comment by hauntingEcho** [comment]
The configuration that this is referring to is in "identity.xml", setting "Server.Recovery.Question.Password.Enable" to "false" should cause the gadget not to be displayed

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
