### ISSUE TITLE
Invalid authorization code received from token request

### ISSUE THREAD

**Issue by bansalvijay** [wso2/product-is#3968]
I have setup the WSO2 environment for OAuth 2.0 authentication.  When I send the authorization request with the client_id and client_secret, I do receive the authorization code on the redirect process.  The problem is when I send "Access token" request:

curl -k -v -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "grant_type=authorization_code&client_id=AZCXWJOsmhBpAAHUKqt0B7EwPzka&client_secret=nf7BBlw5_iCeR6tDZzsInhciYosa&code=77d40dce-36fd-3308-8f06-b184d305a8b5&scope=openid&redirect_uri=https%3A%2F%2Flocalhost%2Fcyberscriptfe%2Foauthredirect.aspx" https://wso2.ais-rx.com:9443/oauth2/token

I am getting the error code: "Invalid_grant" and the description is "Invalid authorization code received from token request".

Please advise.

Thanks,
Vijay

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
