### ISSUE TITLE
Outbound provisioning extension point does not return provisioning identifier for delete operation.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#3972]
Steps to reproduce.
1. Writing a custom outbound provisioning connector extending the **AbstractOutboundProvisioningConnector** class.
2. In the create user operation return a unique ID of the user as the provisioning identifier.
` @Override
    public ProvisionedIdentifier provision(ProvisioningEntity provisioningEntity) throws IdentityProvisioningException {`
3. Do an update operation for the newly created user. Previously persisted identifier claim will be provided in the `provisioningEntity`. We can use this identifier to update the user in the external system.
4. Do a delete operation for the same user. Provisioning identifier will not be included in the `provisioningEntity`. Therefore, we can't delete the user in the external system.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
