### ISSUE TITLE
Revisit SCIM2 filter functionality for ‘Eq’, ‘Ew’, ‘Co’, ‘Sw’ operations

### ISSUE THREAD

**Issue by nuwandiw** [wso2/product-is#3973]
**Eq** should strictly check for the String match (in this case cross user store search should not be performed)
**Co** should check in all user stores.

**Comment by Seralahthan** [comment]
I think this requirement for searching only in the primary user stores for **Eq** operator, only applies to **userName** attribute.

**Eq** should always do exact string match and when it is used with **userName** attribute it should not search across user stores. 

If the **Eq** operator is used with **givenName** or **familyName** we may need to search across user stores domains. As they need not be unique.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
