### ISSUE TITLE
User added mandatory claims are not validated 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#3980]
**Description**
Mandatory claims are not getting validated 

**Tested Environement**
IS 5.8.0-m6
Ubuntu 15.10, DB - H2, JDK 1.8

**Steps to recreate the Issue**
1. Register travelocity web app
2. Create SP with mandatory claim attributes (ex: email) and enable attribute profile
3. Log in to Travelocity and provide the mandatory claim attribute (email) with an invalid value (invalid email address)

**Actual Behaviour**
1. Invalid email attribute added to the user profile

**Expected Behaviour**
1. Invalid claim attributes should be rejected

![screenshot from 2018-11-15 10-44-49](https://user-images.githubusercontent.com/14962228/48531834-e56a0f00-e8c3-11e8-8dd7-e43a1a8ed4d1.png)
![screenshot from 2018-11-15 10-46-03](https://user-images.githubusercontent.com/14962228/48531836-e7cc6900-e8c3-11e8-9614-fd707cd2db08.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
