### ISSUE TITLE
Show the (masked) email address in the password recovery ui message.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-is#3987]
Please refer the screenshot below. 
![screenshot](https://user-images.githubusercontent.com/10165411/48555297-d0fb3600-e906-11e8-87ad-8bb0af1e6cdb.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
