### ISSUE TITLE
Mandatory claims with custom claim dialects requested by the IS even the claim values exists

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#3992]
**Description**
Mandatory custom claims appeared to collect the consent at each user login even though the mandatory claim attributes already exist in the IS

Tested Enviroenemnet
IS 5.8.0 M6
DB - H2, JDK 1.8, Ubuntu 15.10

Steps to recreate the issue
1. Register Travelocity as the SP
2. Defined custom claim dialect with requested and mandatory claims
![screenshot from 2018-11-16 12-24-45](https://user-images.githubusercontent.com/14962228/48602934-ce4a2080-e99a-11e8-8f6e-63852165f573.png)

3. Then log in to Travelocity with an existing user
4. Provide the mandatory claims when it is popped up
5. Again log in to travelocity with the same user

**Actual Behaviour**
Given mandatory claim is appearing at each login attempt
![screenshot from 2018-11-16 12-30-08](https://user-images.githubusercontent.com/14962228/48603124-634d1980-e99b-11e8-9a81-191f2b52a4b2.png)

**Expected Behaviour**
Given mandatory claim should not appear if the claim value already exists with the IDP (For example: email is already provided by the logged in user at the first login attempt)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
