### ISSUE TITLE
Document on how to configure jwks endpoint

### ISSUE THREAD

**Issue by Megala21** [wso2/product-is#4001]
This can configured by configuring "OAuth2JWKSPage" element under "OAuth" element in identity.xml which resides in <IS_HOMe>/repository/conf/identity folder. 

Proposed page of modification https://docs.wso2.com/display/IS560/JSON+Web+Key+Set+Endpoint

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
