### ISSUE TITLE
Dashboard app logout session management

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#4005]
When Dashboard app is the originator of the logout request, it will not destroy its session before forwarding the request to its IdP (the WSO2 server) .
Currently dashboard destroys its session after receiving a logout response from the IS.

So, for some reason, dashboard did not receive a logout response, it will not try to call the IS for re-authentication since dashboard has the session still.

Affects IS 5.6.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
