### ISSUE TITLE
Failed to configure captcha for the initial login page

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4007]
**Description**
Use case - Enable recaptcha for an application at its first login attempt itself

**Tested Environment**
IS 5.8.0 m6
JDK - 1.8, DB - H2, Ubuntu 15.10

**Steps to recreate the issue**
1. Configure capture ( refer [1])
2. Configure the failed attempts to '0' as the requirement is to get the capture option at initial login attempt
![screenshot from 2018-11-21 12-40-44](https://user-images.githubusercontent.com/14962228/48824572-b30c5600-ed8a-11e8-870c-59fb8537f770.png)
3. Configure Travelocity as SP for SSO using SAML
4. Log in to Travelocity app

Actual Results
1. Login page appeared without the capture feature
2. Another login page appeared with the recaptcha
3. following warning appeared in the logs
```
[2018-11-21 12:34:11,589]  WARN {org.wso2.carbon.identity.captcha.filter.CaptchaFilter} -  Captcha validation failed for the user. Cause : reCaptcha response is not available in the request.
```
**Expected Results**
Recaptcha should appear at first login attempt

[1] https://docs.wso2.com/display/IS570/Setting+Up+ReCaptcha

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
