### ISSUE TITLE
Can i use identity server as access control service?

### ISSUE THREAD

**Issue by VidurJain** [wso2/product-is#4008]
I am looking to build PAAS for access control management. I came across WSO2 as a solution which provides IAM with access control. I want to understand if i can use it solely as access control management, since i have a different IAM that i want to use

**Comment by isharak** [comment]
@VidurJain

Apologies for the delay in response, If this not solved yet please join our Slack channel[1] we can help you there.

[1]https://wso2is.slack.com/join/shared_invite/enQtNzk0MTI1OTg5NjM1LTllODZiMTYzMmY0YzljYjdhZGExZWVkZDUxOWVjZDJkZGIzNTE1NDllYWFhM2MyOGFjMDlkYzJjODJhOWQ4YjE#/
