### ISSUE TITLE
Less Number of Claims are issued for SP in the Second Login than in the Very First Login

### ISSUE THREAD

**Issue by sahanruwanga** [wso2/product-is#4015]
**Issue**

When a Service Provider is configured with **Claim Configuration**, a Service Provider Claim Dialect can be configured as either **Use Local Claim Dialect** or **Define Custom Claim Dialect**. If a claim dialect is selected as service provider claim dialect and **a newly created user** tries to login at very first time, usual user consents are asked for approval. Then, in the next step, user logs in and there are some claims included in the response **based on the selected claim dialect**. But when user logs out and try to logs in again, **not all** previously included claims are in the response (only some claims are included). 

**Re-Produce Steps for the Issue**
1. Start **WSO2 IS** and go to **Management Console**
2. Create a **New User**
3. Configure an SP with SAML configurations (I used travelocity application)
4. Go to **Claim Configuration**
5. Select **Define Custom Claim Dialect**
6. Set **Service Provider Claim Dialect** (eg: urn:ietf:params:scim:schemas:core:2.0)
7. Add Claim URI (This may be optional and but can try adding)
8. Update configuration
9. Run the application (I used tomcat server to host the application)
10. Run SAML Tracer (Response can be clearly seen)
11. Use **Newly created user credentials** to log in
12. Approve all prompted user consents and it will make user logs in
13. Observe claims in the response (Can be seen in web page too)
14. Do log out
15. Do log in again using the **same user credentials**
16. Observe claims in the response

 
Not all previous claims are included here, but if Claim URIs are defined manually, they might be included in both times. Instead of above 5th step, it can be tried using **Use Local Claim Dialect** option as well. However, the same behavior is occurred.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
