### ISSUE TITLE
Content of the default NameID format is not as expected

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4030]
Description 
According to the SAML 2.0 specification, NameID format of "emailaddress" should be in the format of email [1] but this is not validated in the Identity Server.

The default name format identifier in the IS is "urn:oasis:names:tc:SAML:1.1:nameid-format:email address" and this accepts values that are not in email format.

For example:
```
saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">admin</saml2:NameID>
```

**Tested Environment**
IS 5.8.0 m6

[1] [8.3.2] in chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
