### ISSUE TITLE
SLO with two federated IDPs are not working properly.

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#4031]
When two federated IDPs are configured as multi-step authentication. When try to logout from SP, the logout request only goes for first federated IDP. The second federated IDP does not receive the logout request.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
