### ISSUE TITLE
Incorrect information for account disabling 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4032]
**Description**

Incorrect information provided for account disabling [1]

As per the documentation effect of the property 'account.disable.handler.enable' will get affected to carbon superuser only at the server startup. And if this the property to get affected for the tenant users, the property needs to be set accordingly before tenant creation.

Hence its incorrect to mention,
```
Set the following property to false to disable account disabling. _This will remove the account disabling option from the tenant_
```

Also, enable/disable account locking that is supported via the UI, it applies to the specific tenant domain where we do the configuration. 

Hence incorrect to mention,
```
To disable or enable this option _for all tenants_, do the following:
```

**Environment**
IS 5.7.0 docs

[1] https://docs.wso2.com/display/IS570/Account+Disabling#AccountDisabling-Switchoffaccountdisabling

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
