### ISSUE TITLE
[UI] Highlight the mandatory field for username recovery option

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4037]
**Description**
According to the current implementation, it is mandatory to provide the first name to recover the username. However its not reflected in the UI.

![screenshot from 2018-11-26 15-50-14](https://user-images.githubusercontent.com/14962228/49008075-fdc70d00-f192-11e8-95a9-5049b5ed727f.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
