### ISSUE TITLE
Support for SAML2.0 asynchronous (front-channel) bindings for single logout

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#4038]
Currently, WSO2 IS supports back-channel SLO requests with SAML SOAP binding. But Spring SAML Extension does not support SOAP binding in SLO and it supports only HTTP-Redirect and HTTP-POST bindings in SLO [1]. 
Therefore it is required to support asynchronous (front-channel) bindings (such as the HTTP Redirect, POST, or Artifact bindings) for single logout in WSO2 IS. 

[1] https://docs.spring.io/spring-security-saml/docs/current-SNAPSHOT/reference/pdf/spring-security-saml-reference.pdf

**Comment by nadeepoornima** [comment]
Similar issue[1].

[1]. https://github.com/wso2/product-is/issues/2111

**Comment by sachiniWettasinghe** [comment]
#https://github.com/wso2-support/identity-inbound-auth-saml/pull/44
