### ISSUE TITLE
Incorrect response code when invalid attribute values provided for username recovery

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4042]
**Description**
When an invalid attribute value is provided to recover a username (ex: wrong email address is provided) the response code appearing is '202 Accepted'. A proper response code should be return as '404 -NotFound'

```
https://localhost:9443/api/identity/recovery/v0.9/recover-username/
[{"uri": "http://wso2.org/claims/givenname","value": "nuwa"},{"uri": "http://wso2.org/claims/emailaddress", "value": "sashi@wso2.com"}]
```

**Tested Environment**
IS 5.8.0 m6

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
