### ISSUE TITLE
Provide a proper response when a nonexisting username is provided to recover the password

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4044]
**Description**
When a user provided an unexisting username when try to recover the password a valid response is not provided to the user.

**Tested Environment**
IS 5.8.0 m6

**Actual Results**
The following message appeared in application side
![screenshot from 2018-11-27 14-28-29](https://user-images.githubusercontent.com/14962228/49070038-c0c15000-f250-11e8-9a91-d0664ca3abc4.png)

Following error appear in the IS backend
```
[2018-11-27 14:28:27,677] ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.RecoverPasswordApiServiceImpl} -  Unable to find an user with username: sashini in the system.
```

**Expected Results**
Should provide the proper response message as the user does not exist or some other appropriate message to indicate that the provided username is not valid.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
