### ISSUE TITLE
[DOC] Potential improvements in the document of post-authentication handler

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#4052]
Please verify the below issues in the doc of Post-authentication handler[1] and fix
1. Identity Server version is not updated. Says Identity Server 5.5.0

1. Invalid link for 'Readme'

[1] https://docs.wso2.com/display/IS570/Post-authentication+Handlers+in+Identity+Server

**Comment by dilin993** [comment]
Affects, 5.8.0 as well. The sample link[1] is also not working.

[1] https://github.com/wso2/samples-is/tree/master/sample-post-authentication-handler

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
