### ISSUE TITLE
Wrong error code is generated when we submit a user name in wrong format

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4054]
Wrong error code is generated when we submit a user name in wrong format

preconditions
1.a fresh pack should be used with embedded ldap. 

setup
1.Identity server WUM updated 5.7.0 ex: wso2is-5.7.0+1541435691728.full.zip

steps
1.run a curl to add a user with email as username format. ex: tester2@wso2.com

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"{FAMILY_NAME}","givenName":"{FIRST_NAME}"},"userName":"tester2@wso2.com","password":"tester","emails":[{"primary":true,"value":"tester@tester.com","type":"home"},{"value":"tester@tester.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users

Note:
Response we get is 
{"Errors":[{"code":"500","description":"Error in adding the user: tester2@wso2.com to the user store. 31301 - Username tester2@wso2.com is not valid. User name must be a non null string with following format, [a-zA-Z0-9._\\-|//]{3,30}$"}]}
expected is  400 Bad Request

**Comment by shavantha** [comment]
lets say we attempt to add a user with the password not in expected format ex:ab as the password the response code is a 500

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
