### ISSUE TITLE
Add support for Partial Logout in SAML single logout

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#4055]
Please refer saml core specification single logout section.

"In the event that not all session participants successfully respond to these <LogoutRequest> messages
(or if not all participants can be contacted), then the session authority MUST include in its
<LogoutResponse> message a second-level status code of
urn:oasis:names:tc:SAML:2.0:status:PartialLogout to indicate that not all other session
participants successfully responded with confirmation of the logout."

**Comment by mefarazath** [comment]
related to https://wso2.org/jira/browse/IDENTITY-3388

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
