### ISSUE TITLE
Move UserInfoJSONResponseBuilder extension point to oAuth core package from oAuth endpoint.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#4061]
Currently, UserInfoJSONResponseBuilder is there in oAuth endpoint. It is very hard to extend the UserInfoJSONResponseBuilder to update the json format based on a custom requirement. Ideally, that should come on oauth core or there should be another extension point in OAuth core.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
