### ISSUE TITLE
[Doc] Missing information on Enable Request Object Signature Validation in OAuth2-OpenID Connect Single-Sign-On document 

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#4063]
There's missing information on 'Enable Request Object Signature Validation' option when creating the auth application in 'Configuring OAuth2-OpenID Connect Single-Sign-On' document [1]. Needs to update the image and add description on what above option would do.

[1] https://docs.wso2.com/display/IS570/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

<img width="627" alt="enable request object signature validation" src="https://user-images.githubusercontent.com/8849472/49203911-ff314900-f3cf-11e8-986d-cddb2455b40e.png">

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
