### ISSUE TITLE
"IF NOT EXISTS" syntax is not working in certain versions of Postgres

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4073]
Postgres token cleanup stored procedure has "IF NOT EXISTS" for table creation and it may not work in certain versions of Postgres.

[1] https://github.com/wso2/carbon-identity-framework/blob/v5.12.215/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/postgre/postgresql.sql#L69-L71

**Comment by dmxunlimit** [comment]
IF NOT EXISTS working only after the Postgres 9.1. 
Previous versions we need to check if the table exists and created the new table. refer [1]

   IF EXISTS (SELECT 1 FROM pg_catalog.pg_tables 
              WHERE  schemaname = 'myschema'
              AND    tablename  = 'mytable') THEN
      RAISE NOTICE 'Table myschema.mytable already exists.';
   ELSE
      CREATE TABLE myschema.mytable (i integer);
   END IF;

[1] https://stackoverflow.com/questions/1766046/postgresql-create-table-if-not-exists

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
