### ISSUE TITLE
Inconsistency in username recovery UI implementation

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4075]
**Description**
There is an inconsistency in the username recover API implementation [1] and the UI implementation [2]. 

In the UI implementation its mandatory to provide the 'firstname' but according to the API implementation, it's not mandatory to provide the 'givenname' claim. The implementations should be consistent

Tested Environment
IS 5.8.0 m6

**Related Tickets**
https://github.com/wso2/product-is/issues/4037

[1] https://docs.wso2.com/display/IS570/apidocs/account-recovery/#!/operations#UsernameRecovery#recoverUsernamePost
[2] https://docs.wso2.com/display/IS570/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
