### ISSUE TITLE
Password reset via email not working for tenant users

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4076]
when this confirmation link is posted on a web browser it gives a below error:
Code : 18013
Message :Invalid tenant domain: abc.com 

 
https://localhost:9444/accountrecoveryendpoint/confirmrecovery.do?confirmation=7feb3e16-278c-47b3-9f5b-fcc81740dd55&userstoredomain=PRIMARY&username=saman&tenantdomain=abc.com&callback=https%3A%2F%2Flocalhost%3A9444%2Fauthenticationendpoint%2Flogin.do%3FSSOAuthSessionID%3D9A4E50B2E410D8246A65A3CB9776833F5CC1A1E64597F99C27CE4E02F6AE3C14FF159E4BE921158D05F2DB78B28EF196D4458B3155B5ECF7DEF8DA23986614E9BD98F1C9186DA150764279A0117714DF6F48FCDBB6F8C7BCC7498CE39AD2DC117B8AF40BAFF361416E9F6CCFCBED7771B5A8AA5BAFFBA1B67ABBA81E1F3D7054%26commonAuthCallerPath%3D%252Fsamlsso%26forceAuth%3Dfalse%26passiveAuth%3Dfalse%26tenantDomain%3Dcarbon.super%26sessionDataKey%3D280915dd-9f54-44d7-835d-a3c30949000f%26relyingParty%3Dwso2.my.dashboard%26type%3Dsamlsso%26sp%3Dwso2_sp_dashboard%26isSaaSApp%3Dtrue%26authenticators%3DBasicAuthenticator%3ALOCAL

**Comment by IshikaGodage** [comment]
Fixed in version 5.8.0
