### ISSUE TITLE
Update the consent purpose management documentation

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4080]
**Description**
Outdated information for managing consent purposes.

The consent purpose information provided in the documentation is not up to date with the implementation.
Please update the requirement of the following fields.

![screenshot from 2018-11-30 14-18-27](https://user-images.githubusercontent.com/14962228/49278541-26a91400-f4ab-11e8-8fdd-ae873a8bcaff.png)

Verison - IS 5.8.0 docs

[1] https://docs.wso2.com/display/IS580/Managing+Consent+Purposes#ManagingConsentPurposes-Addingaconsentpurpose

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
