### ISSUE TITLE
No proper error message when invalid password used when creating associated accounts

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4082]
**Description**
No proper error message appearing when a user failed to provide correct password when attempting to create associating account.

**Tested Environment**
IS 5.8.0 m6 
DB - h2

**Steps to recreate the issue**
1. Create a user with login permission
2. Log in to dashboard and add an associated account (with nvalid password)

**Actual Result**
Following error message will appear.
```
"UserAccountAssociationServiceUserAccountAssociationClientExceptionException"
```
![screenshot from 2018-11-30 15-06-10](https://user-images.githubusercontent.com/14962228/49281038-91f5e480-f4b1-11e8-9174-f19167325765.png)

**Expected Result**
A proper error message should appear

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
