### ISSUE TITLE
Handle data migration in IS 5.5.0 to IS 5.6.0 with changes in wso2/product-is/issues/3202

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#4087]
1.  During migration from IS 5.5.0 to IS 5.6.0, we have a schema change to add a new column 'EXPIRY_TIME' in  IDN_AUTH_SESSION_STORE table. (As a result of improvements in https://github.com/wso2/product-is/issues/3202)

For example for MySQL DB we have,
`ALTER TABLE IDN_AUTH_SESSION_STORE ADD EXPIRY_TIME BIGINT;
`
As a result of this schema change, the default value for the 'EXPIRY_TIME' column is set to NULL. The' impact of this is that entries which will have 'NULL' in 'EXPIRT_TIME' column will not be cleaned up by the session data cleanup task as we have modified the code to use this column to detect expired data.

Therefore during migration, we need to handle the schema change gracefully by adding appropriate EXPIRY_TIME for each entry.

2. We have provided the improvement(wso2/product-is/issues/3202) as updates for IS 5.3.0 / IS 5.4.1 etc. Therefore the schema changes required by the improvement might already be there when we migrate from IS 5.5.0 to IS 5.6.0.

Therefore we need to only do the schema changes due to wso2/product-is/issues/3202 only if they are already not present.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
