### ISSUE TITLE
JSON XACML request with custom categories do not evaluated properly. Giving a request parse Exception

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4090]
**Policy** 
`<?xml version="1.0" encoding="UTF-8"?>
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" PolicyId="order_processing_authz_policy" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
  <Description>This policy template provides ability to authorize users to a given service provider(defined by SP_NAME) in the authentication flow based on the roles of the user (defined by ROLE_1 and ROLE_2). Users who have at least one of the given roles, will be allowed and any others will be denied.</Description>
  <Target>
     <AnyOf>
        <AllOf>
           <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
              <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">orders</AttributeValue>
              <AttributeDesignator AttributeId="http://ecomm.org/authz/resource/name" Category="http://ecomm.org/authz/resource" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false" />
           </Match>
           <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
              <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">POST</AttributeValue>
              <AttributeDesignator AttributeId="http://ecomm.org/authz/action/name" Category="http://ecomm.org/authz/action" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false" />
           </Match>
        </AllOf>
     </AnyOf>
  </Target>
  <Rule Effect="Permit" RuleId="permit_by_roles">
     <Condition>
        <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:or">
           <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-is-in">
              <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">admin</AttributeValue>
              <AttributeDesignator AttributeId="http://wso2.org/claims/role" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true" />
           </Apply>
        </Apply>
     </Condition>
  </Rule>
  <Rule Effect="Deny" RuleId="deny_others" />
</Policy>`

**Request**
`{
   "Request": {
       "Category": [
           {
           "CategoryId": "http://ecomm.org/authz/resource",
           "Attribute": ["http://ecomm.org/authz/resource/name"]
           },
           {
           "CategoryId": "http://ecomm.org/authz/action",
           "Attribute": ["http://ecomm.org/authz/action/name"]
           }
       ],
       "Attribute": [
           {
               "AttributeId": "http://ecomm.org/authz/resource/name",
               "Value": "orders"
           },
           {
               "AttributeId": "http://ecomm.org/authz/action/name",
               "Value": "POST"
           }
       ],
       "AccessSubject": {
           "Attribute": [
               {
                   "AttributeId": "urn:oasis:names:tc:xacml:1.0:subject:subject-id",
                   "Value": "admin@carbon.super"
               }
           ]
       }

   }
}`

Error: {"code":40020,"message":"Request Parse Exception."}

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
