### ISSUE TITLE
Provide meaningful error pop up when a SP with already exists created.

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#4091]
Currently, when importing an SP with the same name, we are showing this pop-up,
![error-importing-sp](https://user-images.githubusercontent.com/11584828/49335848-d7cebc00-f61b-11e8-86fd-57f89a28b6f2.png)

We need to display more meaning message.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
