### ISSUE TITLE
Improving Tenant deletion via Tenant Management Admin Service

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#4100]
Following Issues are encountered in Tenant Deletion via Tenant Deletion Admin Service

* Existing methods only capable of deleting tenant from
   * JDBC user store 
   * Registry tables
   * Tenant Cache
* But we still need to delete more artifacts while deleting tenant
   * Tokens
   * All Caches and cache managers
   * Service Providers
   * Deployment Folders
   * Java layer Registries

** Related Issues **
[Improve Tenant Deletion via Tenant deletion Admin Service.](https://github.com/wso2/carbon-multitenancy/issues/146)
[Security exception occurred when try to create a tenant with deleted tenant's domain name](https://github.com/wso2/carbon-kernel/issues/1878)

** Related Document **
[Tenant Deletion Document](https://docs.google.com/document/d/1B75o3kGJiR4TpsQ8WKiHewV6Zs8iV7PtBSQqO6-W0oc/edit?usp=sharing)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
