### ISSUE TITLE
Support renaming the username

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4116]
At the moment there is no service available to perform username rename.
This is to include that support over the capability of identity anonymization tool.

**Comment by nilasini** [comment]
Fixed with
https://github.com/wso2/product-is/pull/4115
https://github.com/wso2/carbon-identity-framework/pull/2020

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
