### ISSUE TITLE
SCIM2 list groups returns only PRIMARY userstore groups, Secondary userstore groups are missing for a plugged LDAP userstore who has groups

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4117]
Groups should be properly handled as Users to list pluged LDAP groups 

curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups'
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: localhost (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=CA,L=Mountain View,O=WSO2,CN=localhost
* 	 start date: Wed, 19 Jul 2017 06:52:51 GMT
* 	 expire date: Sat, 17 Jul 2027 06:52:51 GMT
* 	 issuer: C=US,ST=CA,L=Mountain View,O=WSO2,CN=localhost
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'admin'
> GET /scim2/Groups HTTP/1.1
> Host: localhost:9443
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: private
< Expires: Thu, 01 Jan 1970 05:30:00 IST
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Mon, 03 Dec 2018 14:25:53 GMT
< Content-Type: application/scim+json
< Content-Length: 1760
< Server: WSO2 Carbon Server
< 
{"totalResults":5,"startIndex":1,"itemsPerPage":5,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"Application/SP","meta":{"created":"2018-12-03T12:27:06Z","location":"https://localhost:9443/scim2/Groups/3af0529f-a4f3-486a-b770-ed942e880bbb","lastModified":"2018-12-03T12:27:06Z"},"members":[{"display":"admin","value":"2b8fa979-b609-40ce-a9b7-c38bcd173a12"}],"id":"3af0529f-a4f3-486a-b770-ed942e880bbb"},{"displayName":"Internal/system","meta":{"created":"2018-12-03T11:29:05Z","location":"https://localhost:9443/scim2/Groups/a4646e4a-8663-4c65-8ca0-bb64409a0a4a","lastModified":"2018-12-03T11:29:05Z"},"id":"a4646e4a-8663-4c65-8ca0-bb64409a0a4a"},{"displayName":"Application/saml2-web-app-pickup-manager.com","meta":{"created":"2018-12-03T12:39:05Z","location":"https://localhost:9443/scim2/Groups/ae37dc64-8589-4248-bd3a-5913d13f3bca","lastModified":"2018-12-03T12:39:05Z"},"members":[{"display":"admin","value":"2b8fa979-b609-40ce-a9b7-c38bcd173a12"}],"id":"ae37dc64-8589-424* Connection #0 to host localhost left intact
8-bd3a-5913d13f3bca"},{"displayName":"PRIMARY/admin","meta":{"created":"2018-12-03T11:29:04Z","location":"https://localhost:9443/scim2/Groups/6d39a429-bbed-49b4-be8c-6f1cfadd3c90","lastModified":"2018-12-03T11:29:04Z"},"members":[{"display":"admin","value":"2b8fa979-b609-40ce-a9b7-c38bcd173a12"},{"display":"umuser2","value":"83707113-daf8-4d46-a129-bf3633a8f1e3"}],"id":"6d39a429-bbed-49b4-be8c-6f1cfadd3c90"},{"displayName":"Application/SP2","meta":{"created":"2018-12-03T15:16:27Z","location":"https://localhost:9443/scim2/Groups/95de6799-4e3e-4c5b-a58c-d5d944f46bd3","lastModified":"2018-12-03T15:16:27Z"},"members":[{"display":"admin","value":"2b8fa979-b609-40ce-a9b7-c38bcd173a12"}],"id":"95de6799-4e3e-4c5b-a58c-d5d944f46bd3"}]}

**Comment by rksk** [comment]
Duplicate of https://github.com/wso2/product-is/issues/8623
