### ISSUE TITLE
Checking the availability of SP_CLAIM_DIALECT does not work properly with mysql

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#4121]
If the MySQL database server has the table SP_CLAIM_DIALECT in any other database other than the connected database, it will still work as the table is existing.
IS Version 5.5.0.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
