### ISSUE TITLE
Invalid attribute names in secondary user stores

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#4129]
If you create secondary user store it will create user store xml file with following elements.
 
      <Property name="UserNameJavaRegEx">a-zA-Z0-9._-{3,30}$</Property>
      <Property name="UserNameJavaScriptRegEx">^[\S]{3,30}$</Property>
 
These attribute names are not valid because of some upper case text (user-mgt.xml has the correct one). In code level it read from below text. So this need to be fix. We can change it in the user store file, but once some one update from the UI, this will get change.
 
UsernameJavaRegEx
UsernameJavaScriptRegEx

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-kernel/commit/54e0faff40985a260b17653cc522ee149f811fed
