### ISSUE TITLE
There are no attributes for 'eduPerson' Object Class defined in Embedded LDAP 

### ISSUE THREAD

**Issue by sahanruwanga** [wso2/product-is#4134]
**Requirement**

A set of new attributes are needed to use in embedded LDAP for the feature of **InCommon Federation Compliance for WSO2 IS**. Those attributes are defined under [**eduPerson Object Class Specification**](http://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201602.html). The existing LDAP doesn't support this object class but, it is required to be supported.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
