### ISSUE TITLE
SCIM2 add user return 500 when password policy violation happens

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4145]
Example : 

curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim1","password":"kim","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

Response:

{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","detail":"Error in adding the user: kim1 to the user store. 30003 - Credential is not valid. Credential must be a non null string with following format, ^[\\S]{5,30}$","status":"500"}

**Comment by shavantha** [comment]
similar issue was reported for user name https://github.com/wso2/product-is/issues/4054 format violation
