### ISSUE TITLE
Export and Import functionality support for Functions Library Management Component

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#4150]
**Description:**

Export and import functinalities need to be implemented for [functions library management component](https://github.com/wso2/carbon-identity-framework/tree/master/components/functions-library-mgt) in carbon identity framework. UI section is already done.

- Export functionality should be able to download and save a function library in the database to a file.

- Import functionality should be able to add a function library to the database using a file.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
