### ISSUE TITLE
Default function library to ship with the product

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#4151]
**Description:**

A default function library needs to be created, in order to ship with the product-is. A mechanism needs to be confirmed to load the function library to the database when starting the product-is.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
