### ISSUE TITLE
require() function usage in function libraries

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#4152]
**Description:**

If an adaptive authentication script requires a function library A.js and inside A.js library it requires B.js library, The module B is not found only inside the onSuccess and onFail methods in the authentication script.

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
