### ISSUE TITLE
post_logout_redirect_uri and id_token_hint parameters not being passed by Playground2 app during logout

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#4156]
post_logout_redirect_uri and id_token_hint parameters are not being passed with the request to the OIDC Logout Servlet at the IS during logout.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
