### ISSUE TITLE
OIDC Frontchannel and Backchannel logout not available in OIDC Discovery and Dynamic Client Registration

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#4157]
Frontchannel and Backchannel logout cannot be configured using OIDC DCR and it is also not available in OIDC Discovery.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
