### ISSUE TITLE
OB Directory authorization URL parameters are not there

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#4165]
After enabling the fix for Removal of the redirection query parameters, Manual registration flow with Open Banking Directory seems like not working as expected.
When comparing the SAML traces, can see at the redirection, query parameters for OB-Directory also getting filtered.

**Successful Case :**

          "name": "Location",
          "value": "https://sso.openbankingtest.org.uk/as/authorization.oauth2?response_type=code&redirect_uri=https%3A%2F%2F10.6.184.154%3A9446%2Fcommonauth&state=e5871c5a-2f59-4e02-abee-6bbc6720e88d%2COIDC&client_id=6a7Tz5kaYqWPNAgtATDtGr&scope=openid+email+profile&prompt=login"

**Failure Case :**

          "name": "Location",
          "value": "https://sso.openbankingtest.org.uk/as/authorization.oauth2?"

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-identity-framework/pull/2015
