### ISSUE TITLE
Incorrect permission for 'OIDC Scopes'

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#4169]
OIDC scopes menu is appearing for users with login permission only in IS 5.7.0 pack.
![image](https://user-images.githubusercontent.com/12690906/49709554-ea1faa00-fc5a-11e8-9932-bc62cea51015.png)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
