### ISSUE TITLE
SCIM1.1  org.wso2.charon.core.exceptions.CharonException when attepmting to assign a user to a newly provisioned role

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4173]
When attempting to provision a user and a role and attempt to assign the new role to the user the below exception is thrown

 org.wso2.charon.core.exceptions.CharonException: Error occurred while updating old group

steps
1.provision a new user calling scim 1.1 api
2.provision a new role calling scim 1.1 api
3.attempt to update the role and assign the user to the role

environment
1.wso2is-5.7.0 with updates (1541435691728/1543336788716)
2.java version "1.8.0_161"
3.ubuntu 18.04

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
