### ISSUE TITLE
[Improvement] Provide a user confirmation window before deleting the auth application in a single step

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-is#4174]
Currently when we're trying to delete an existing auth application of a Service provider, it doesn't give a confirmation box to get the approval of the user before deleting it. Without having this, a configured auth application can be deleted in a single click (probably by accident) and it's better to add a confirmation window before deleting it.

Affected Product = IS 5.7.0

== Auth App ==

<img width="1116" alt="created_auth_app" src="https://user-images.githubusercontent.com/8849472/49716167-e3079480-fc78-11e8-8a8b-976a94ae529d.png">

== Deletion Successful Window without a Confirmation ==

<img width="1174" alt="auth_app_deletion" src="https://user-images.githubusercontent.com/8849472/49716186-f9adeb80-fc78-11e8-9618-59a4c6d3c5ad.png">

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
