### ISSUE TITLE
Handle 500 internal error properly 

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#4179]
In certain cases when an error occurred the user will get redirected to a default tomcat error page, which prints a huge error trace. Although this can be disabled, it will show the error in a blank page.  There is no current option to customize this page from a central location.

Therefore some method should be implemented to send the user to a default error page for any kind of 500 internal error occurred.

**Comment by malithie** [comment]
Do we know in which cases this is being observed and on which web apps

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
