### ISSUE TITLE
Documentation Update of Identity Server - Username Recovery

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#4183]
The service caller can define any number of claims that should be used in the user details verification. But when defining the claims make sure to define a unique user attribute (claim) or a unique composite user attributes (multiple claims) as can identify the user separately.

To define the claims need to follow the steps below.
1. Login to the Management Console and list the claims.
2. Click on http://wso2.org/claims and find the relevant claim.
3. Edit the relevant claim and mark as Supported by Default and then Update.

Need to update [1] documentation with the above information.
[1]. https://docs.wso2.com/display/IS550/Username+Recovery

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
