### ISSUE TITLE
OpenID connect discovery not working in 5.7.0 with standard ssl port 443

### ISSUE THREAD

**Issue by ecky-l** [wso2/product-is#4188]
Identity Server 5.7.0 configured as either behind a proxy (Apache httpd) or with tomcat running as root and the https connector on port 443.

Say, hostname is wso2.local. I have valid certificates for that domain name and they are properly configured. The secured parameter is set to false in conf/identity/identity.xml for "(.*)/.well-known(.*)" url patterns, so that I can access all urls containing "/.well-known" without authentication.

I try to access https://wso2.local/oauth2/oidcdiscovery/.well-known/openid-configuration via curl:

`curl https://wso2.local/oauth2/oidcdiscovery/.well-known/openid-configuration`

and always get the error:

> Error while loading the endpoint. The path to the discovery document should be in the format of {issuer}/.well-known/openid-configuration

I tried several combinations of setting <IDTokenIssuerID> in identity.xml and "Identity Provider Entity ID" in the Resident Identity Provider's inbound configuration in carbon, setting it to "https://wso2.local/oauth2/oidcdiscovery" with or without /.well-known/openid-configuration, but nothing helps.

All other entdpoints can be accessed without problem. And apparently (I didn't test this too exhaustive) this problem does not occur when the port is set to 9443 or any other non-privileged and the identity server is accessible via this port from the outside world.

**Comment by gorkma** [comment]
Having the same problem.

**Comment by ecky-l** [comment]
Setting the port 443 explicitly in the curl calls didn't work.

But I can confirm that it works when I do the following:

- remove the port entry ${carbon.management.port} _completely_ from _all_ URLs in conf/identity/identity.xml
- set the <IDTokenIssuerID> and the <OIDCDiscoveryEPUrl> to the _same_ value: `${carbon.protocol}://${carbon.host}/oauth2/oidcdiscovery` in identity.xml
- In carbon, logged in as admin, go to "Service Providers"->"Resident"->"Inbound Authentication"->"OAuth2/OpenID Connect Configuration" and change the "Identity Provider Entity ID" value to the same value as <IDTokenIssuerID> and <OIDCDiscoveryEPUrl> in identity.xml, if necessary: `${carbon.protocol}://${carbon.host}/oauth2/oidcdiscovery`

Then, `curl -s https://wso2is.local/oauth2/oidcdiscovery/.well-known/openid-configuration` gives the correct answer 👍 

I think:
- it should not be necessary to change this entry at 3 different places around the configs. And these entries should contain the correct value per default
- the server should detect when it can serve the discovery on a standard port (i.e. without port in the url) and act accordingly. Or at least behave consistently when the port isset explicitly.
- the documentation should highlight this issue and give a solution when there is no quick fix possible

**Comment by davebaol** [comment]
Same issue here.
I'm in a multitenant scenario.
Any chance to get it fixed soon?

**Comment by darshanasbg** [comment]
It seems like we are discussing multiple issues here.

@davebaol Could you kindly create a new git issue for the issue you are facing with the steps to reproduce? So I can reproduce and may able to help you out for a solution...

**Comment by darshanasbg** [comment]
@tharindu-bandara Hope you may find this interesting...

**Comment by davebaol** [comment]
Thanks @darshanasbg.
A colleague of mine opened the new issue #4671 with the steps to reproduce.

**Comment by darshanasbg** [comment]
Thanks @davebaol. Lets follow up in the https://github.com/wso2/product-is/issues/4671

**Comment by vihanga-liyanage** [comment]
Closing this and continue discussion on https://github.com/wso2/product-is/issues/4671
