### ISSUE TITLE
Design of having user store domain as 'FEDERATED' is error prone

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4193]
In oauth, the identification for a federated user has been persisting the user's user store domain as 'FEDERATED'.
This verification is scattered over the code, thus has a high chance of being buggy.
It would be better if resolving the user is federated or not and persisting that in the data layer and retrieving back has been handled centrally. Also rather than having additional checks to validate user store domain to identify the user is federated or not better a separate field could have been used in the persistence layer.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
