### ISSUE TITLE
Cache invalidation among cluster nodes happen only with ForceLocalCache property

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#4194]
**Problem**: 
The cache invalidation among cluster nodes is happening for the caches which are marked as isDistributed="false" in the identity.xml only if the property ForceLocalCache is enabled at carbon.xml.

**Expected behavior**:
The caches marked as isDistributed="false" need to be considered as local caches and cache invalidation among the clusters need to happen even without the ForceLocalCache property.

**Comment by mefarazath** [comment]
We need to make this property set to true by default in IS_HOME/repository/conf/carbon.xml

    <Cache>
        
        <DefaultCacheTimeout>15</DefaultCacheTimeout>
        
        <ForceLocalCache>true</ForceLocalCache>
    </Cache>
