### ISSUE TITLE
Fix incorrect DB constraint for Oracle and PostgreSQL

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#4197]
This has been fixed with https://github.com/wso2/carbon-identity-framework/pull/2018 in master.
Need to make sure we handle this during migration.
 
* Need to handle entries that violate this constraint currently in the table

**Comment by malithie** [comment]
@mefarazath , @DMHP ,
Can we please specify the possible approach to get the constraint applied during migration

**Comment by madurangasiriwardena** [comment]
Duplicates https://github.com/wso2/product-apim/issues/4006

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
