### ISSUE TITLE
Tables missing in identity anonymization which impacts username rename capability

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4199]
Noted below tables are missing. Yet, as the anonymization tool is to delete further references of the user after user is deleted, these may not be applicable to it's default behavior. But these will impact the username rename capability provided with the anonymization tool (https://github.com/wso2/product-is/issues/4116).

UM_HYBRID_USER_ROLE:
This table keeps a reference to the domain id. Thus, the entry should be updated over an API.

UM_HYBRID_REMEMBER_ME:
No domain as a column. If the table is referred within user store, update should occur from the API as the domain cannot be identified in data entries in the table.

UM_USER_PERMISSION:
No domain as a column. If the table is referred within user store, update should occur from the API as the domain cannot be identified in data entries in the table.

IDN_OAUTH2_ACCESS_TOKEN_AUDIT:
Not incorporated. Need to incorporate with default scripts as well.

IDN_UMA_RESOURCE:
Not incorporated.  Need to incorporate with default scripts as well.

IDP_PROVISIONING_ENTITY:
Not incorporated.  Need to incorporate with default scripts as well.

**Comment by tharindu-bandara** [comment]
Needs to verify the following table in scripts under the location `<PRODUCT_HOME>/dbscripts/bps/bpel/create` as well.

ATTACHMENT

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
