### ISSUE TITLE
Migration does not make the TOKEN_ID as the primary key in IDN_OAUTH2_ACCESS_TOKEN In 5.1.0 migration

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4200]
This will later cause an issue in adding IDN_OIDC_REQ_OBJECT_REFERENCE table as it will have a foreign key to that column.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
