### ISSUE TITLE
[Doc] Update needed in "Configuring Claims for a Service Provider" for IS570

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4204]
In the [Configuring Claims for a Service Provider ](https://docs.wso2.com/display/IS570/Configuring+Claims+for+a+Service+Provider)[1] page under Claim mapping in the "Click to view vital information when configuring claims for an OpenID Connect Service Provider" section mentions editing a  /_system/config/oidc file in the Registry. This file is no longer available in the Registry. 

There is a new configuration available called "OIDC Scopes" under Manage on the Main tab of the management console. 

[1] - https://docs.wso2.com/display/IS570/Configuring+Claims+for+a+Service+Provider

**Comment by rksk** [comment]
Additionally, there is a missing image under "Information on mapping claims". This applies to all the versions.

**Comment by sherenewso2** [comment]
Fixed the steps in versions 5.7.0 and 5.8.0 [1] 

[1] - https://docs.wso2.com/display/IS570/Configuring+Claims+for+a+Service+Provider
