### ISSUE TITLE
Support for "RenewRefreshTokenForRefreshGrant" property at application level for IS 5.7.0

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#4205]
It is good to have an option to configure "RenewRefreshTokenForRefreshGrant" property at the application level.

**Comment by LahiruLS** [comment]
Related: https://github.com/wso2/product-is/issues/4550

**Comment by LahiruLS** [comment]
Already fixed in the master branch with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1027
