### ISSUE TITLE
The actual behavior and the WARN printed on logs for updating a user role in scim 1.1 is confusing

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4214]
The actual behavior and the WARN printed on logs for updating a user role in scim 1.1 is confusing

If we call HTTPPatch when adding a user to a role as in[1] the logs on identity server prints a WARN as in [2]. However, the user is actually added to the role as shown in the screenshot [3].

[1]method to add a user to a role
```
    public void testCreateAdminUser() throws Exception {

        for (int i = 0; i < 1; i++) {
            JSONObject member = new JSONObject();
            member.put(SCIMConstants.DISPLAY, ProcessJsonFile.getJsonObject().get("userName"));
            member.put(SCIMConstants.VALUE_PARAM, userId);
            members.add(member);
        }
        groupObject.put(SCIMConstants.MEMBERS, members);

        updateRoleRequest(client,groupURL,groupObject,getCommonHeaders());
    }

    public static HttpResponse updateRoleRequest(HttpClient client, String url, JSONObject jsonObject,
                                                 Header[] headers) throws Exception {
        HttpPatch request = new HttpPatch(url);
        if (headers != null) {
            request.setHeaders(headers);
        }

        request.setEntity(new StringEntity(jsonObject.toString()));
        return client.execute(request);
    }
```

[2]Identity server logs
[2018-12-17 15:36:14,254]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@carbon.super [-1234]' logged in at [2018-12-17 15:36:14,254+0530]
[2018-12-17 15:36:14,408]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  User: scim1admin is created through SCIM.
**[2018-12-17 15:36:14,518]  WARN {org.wso2.carbon.identity.scim.provider.impl.SCIMUserManager} -  There is no updated field in the group: admin. Therefore ignoring the provisioning.**

[3]
![user_added_to_admin_role](https://user-images.githubusercontent.com/6552100/50080540-59c10680-0212-11e9-96e6-ffe620270185.png)

**Comment by shavantha** [comment]
In this scenario I am not updating the user role name but calling HTTPPatch and updating the Members of the groups. However, the WARN shows as "There is no updated field in the group: admin. Therefore ignoring the provisioning."

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
