### ISSUE TITLE
Add PK or Unique Indexes for each tables

### ISSUE THREAD

**Issue by harsha1979** [wso2/product-is#4215]
Since we need to support multi-region deployment in database level, we have to have this in order to avoid the slowness when the replication happens.

Here are the tables that we found without having any keys.

IDN_OAUTH2_ACCESS_TOKEN_AUDIT
IDN_OAUTH2_SCOPE_BINDING
REG_RESOURCE_COMMENT
REG_RESOURCE_PROPERTY
REG_RESOURCE_RATING
REG_RESOURCE_TAG
ODE_SCHEMA_VERSION
STORE_PROC_TO_PROP
HT_HUMANROLE_ORGENTITY

**Comment by swgkg** [comment]
> Since we need to support multi-region deployment in database level, we have to have this in order to avoid the slowness when the replication happens.
> 
> Here are the tables that we found without having any keys.
> 
> IDN_OAUTH2_ACCESS_TOKEN_AUDIT
> IDN_OAUTH2_SCOPE_BINDING
> REG_RESOURCE_COMMENT
> REG_RESOURCE_PROPERTY
> REG_RESOURCE_RATING
> REG_RESOURCE_TAG
> ODE_SCHEMA_VERSION
> STORE_PROC_TO_PROP
> HT_HUMANROLE_ORGENTITY
> UM_SHARED_USER_ROLE

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
