### ISSUE TITLE
Document on configuring Email OTP connector for federated users

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#4216]
In the current documentation for Email OTP configuration, it only describes how Email OTP can be configured for local users. 
For configuring email OTP on federated users following additional steps need to be followed.

Add the following properties to <IS_HOME>/repository/conf/identity/application-authentication.xml under EmailOTP authenticatorConfig.
```

<Parameter name="EMAILOTPMandatory">true</Parameter>
<Parameter name="sendOTPToFederatedEmailAttribute">true</Parameter>
<Parameter name="federatedEmailAttributeKey">email</Parameter>
```

It is required to have the emailaddress claim for the federated user. In the case where a secondary IS configured as the  federated IDP, 'emailaddress' should be selected under requested claims of federated IDP's SP configuration. And the federateduser should have the correct value assigned for the email claim.

[1] https://docs.wso2.com/display/IS530/Configuring+Email+OTP

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
