### ISSUE TITLE
AuthnInstant value return in the SAML2 response is invalid if user has an existing session at the IdP

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#4219]
AuthnInstant value in the SAML2 response is described in the following specifications as follows,

SAML Core 2.0

> AuthnInstant [Required] Specifies the time at which the authentication took place. The time value is encoded in UTC, as described in Section 1.3.3.

SAML 2.0 Session Token Profile

> AuthnInstant [Required]
> The SA MUST set the AuthnInstant to the time authentication occurred, as defined in [SAML2Core]. The SC MAY use this value to implement a maximum login time.

So AuthnInstant value represents the time which user authenticated with the IdP. When user login to an application using an already authenticated IdP session, in the SAML2 response it should include the time which user authenticated, as the AuthnInstant value. 

In the current implementation[1] we always set the current time for the AuthnInstant value, which is wrong according to the specification.

Similar attribute available in the OIDC specification as well.

> auth_time
> Time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. When a max_age request is made or when auth_time is requested as an Essential Claim, then this Claim is REQUIRED; otherwise, its inclusion is OPTIONAL. (The auth_time Claim semantically corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] auth_time response parameter.)

In the current implemetation[2], we use session updated time as auth_time which is also wrong according to the specification, if new authenticators are not involved.

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/builders/assertion/DefaultSAMLAssertionBuilder.java#L221
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L2412

**Comment by dilin993** [comment]
Created a separate issue to track OIDC case.
https://github.com/wso2/product-is/issues/4247
