### ISSUE TITLE
Configuring and endpoint for error page is missing

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4224]
Configuring a different relative endpoint to handle an error at authentication flow is missing in documentation [1]

`<AuthenticationEndpointRetryURL>/authenticationendpoint/retry.do</AuthenticationEndpointRetryURL>`

Similar to the login URL an endpoint relative to the server context can be configured to handle error cases.
 [1] https://docs.wso2.com/display/IS570/Customizing+the+Authentication+Endpoint#CustomizingtheAuthenticationEndpoint-CustomizingtheauthenticationendpointURL

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
