### ISSUE TITLE
SCIM2 filter user by emails returns duplicate results

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4228]
Version IS 5.7.0
Follow below steps to reproduce the issue.
- Change the userstore to JDBC
- Enable scim in the userstore manager.
- Change the username attribute to mail
- Enable ask password feature
- Create the user(jane@wso2.com) with username and email using ask password feature from the management console.

### Issue 01
Try filtering user just added.

In SCIM 2.0 its returns same user twice.
Request:
curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=emails%20eq%20jane@wso2.com

### Issue 02
In the database, mail attribute is saved twice.

Configs to enable email as username is mentioned in [1]

[1] https://docs.wso2.com/display/IS570/Using+Email+Address+as+the+Username

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
