### ISSUE TITLE
[Doc] Missing information for configuring a custom login page

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4232]
When using a custom login page it is possible to redirect to the custom pages by modifying the authenticationendpoint web app's web.xml file located in <IS_Home>/repository/deployment/server/webapps/authenticationendpoint/WEB-INF (this folder is only available after the 1st server startup)

By adding the following configuration it is possible to redirect to the custom login page and also handle the retry error page with a custom page

```
<context-param>
  <param-name>/login.do</param-name>
  <param-value><!--url to the custom login page--></param-value>
</context-param>
<context-param>
  <param-name>/retry.do</param-name>
  <param-value><!--url to the custom retry page--></param-value>
</context-param>
```

sample configuration will look as follows;

```
<context-param>
  <param-name>/login.do</param-name>
  <param-value>http://localhost:8080/customportal/login.do</param-value>
</context-param>
<context-param>
  <param-name>/retry.do</param-name>
  <param-value>http://localhost:8080/customportal/retry.do</param-value>
</context-param>
```

this workings of this functionality are also available as a comment in the web.xml file [1] and also in this blog post[2]
[1] - https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/WEB-INF/web.xml#L23-L48
[2] - https://medium.com/thetechblogger/using-a-custom-login-page-for-wso2-identity-server-b8451b35cdd

I think this information can be added to the following docs page[3]
[3] - https://docs.wso2.com/display/IS570/Customizing+Login+Pages+for+Service+Providers

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
