### ISSUE TITLE
Same username with different letter case considered as different users

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#4234]
**Description**
The same username in different letter cases is considered as different users in the analytics dashboards. Therefore there will be duplicate entries for users.

**Steps to reproduce:**

If the databases are case sensitive, the issue occurs when a token request is made.

1. Assume that the primary user store has the user account "admin".
2. Do a token request with the username "admin".
3. Do another token request for the same user with the username "ADMIN"
4. If the databases are case sensitive, the second request will get a new token and if the databases are case insensitive, the same token will be returned.
5. For the requests, the subject identifier stored in 'IDN_OAUTH2_ACCESS_TOKEN' in the database is the username entered by the user.

If the databases are case-insensitive the issue is reproducible only after a token expiry happens. 

1. As above, make a token request with username "admin"
2. Then the subject identifier will store as "admin"
3. After the token expires, make another request with the username "ADMIN"
4. For the new token, the subject identifier will be "ADMIN"

In analytics for APIM, the API access are calculated via the key validation. Therefore each different subject identifier will be considered as a different user.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
