### ISSUE TITLE
[Improvement] Add debug/monitoring to XACML Policy execution flow

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#4236]
Currently in the IS we don't support debug/monitoring of the execution of a XACML policy flow step by step to verify whether each rule is evaluated into **deny/permit/inderminate/not applicable** result status. One possible way i found for achieving this is by logging the rule and result when evaluating the decision [1] 

[1] https://github.com/wso2/balana/blob/master/modules/balana-core/src/main/java/org/wso2/balana/combine/xacml2/FirstApplicableRuleAlg.java#L108

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
