### ISSUE TITLE
UMA resource registration request spec violation

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#4241]
In UMA resource registration request payload `resource_scope` should be `resource_scopes`
> curl -v -X POST -H "Authorization:Bearer <PAT>" -H "Content-Type: application/json" -d '{"resource_scope":["view", "download"], "description":"Collection of digital photographs", "icon_uri":"http://www.example.com/icons/flower.png", "name":"Photo Album", "type":"http://www.example.com/rsrcs/photoalbum"}' https://localhost:9443/api/identity/oauth2/uma/resourceregistration/v1.0/resource -k

**Comment by madurangasiriwardena** [comment]
Fixed with https://github.com/wso2-extensions/identity-oauth-uma/pull/36
