### ISSUE TITLE
UMA resource registration response spec violation 

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#4243]
Resource registration response should be corrected

from:

> {
>    "resourceId":"3f88c89a-d3b8-4ebb-9567-08e5bb774d3c",
>    "policy_uri":null
> }

to

> _id (mandatory) and 
> user_access_policy_uri (optional)

**Comment by madurangasiriwardena** [comment]
Fixed with: https://github.com/wso2-extensions/identity-oauth-uma/pull/39
