### ISSUE TITLE
Store calculated expiry times in IDN_OAUTH2_ACCESS_TOKEN

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#4245]
As of now, only the validity period is stored. So in order to check whether a token is expired or not in an SQL query, a function is needed. When a field is in an operand of a function the indexes for the same field is not applied. So there will be a performance impact.

The ideal solution is to store the expiry time.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
