### ISSUE TITLE
[OpenID Connect Discovery] A validate button for the resident Idp entity id value

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4279]
**Requirement**

Fix for the [issue](https://github.com/wso2/product-is/issues/4277) enables _resident Idp entity id_ to be used as an OIDC issuer location. Therefore the _resident Idp entity id_ needs to be validated as a valid OIDC issuer location.

**Improvement**

A validate button in the UI for the _resident Idp entity id_ .

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
