### ISSUE TITLE
Problems with encrypting Embedded Ldap Password

### ISSUE THREAD

**Issue by Epic55** [wso2/product-is#4291]
Hello, i can't encrypt Embedded LDAP password in repository/conf/identity/embedded-ldap.xml file on Identity Server 5.6.0. I encrypted a password in embedded-ldap.xml file. In "cipher-tool.properties" file i have string:
          EmbeddedLdap.Property.ConnectionPassword=repository/conf/identity/embedded-ldap.xml//EmbeddedLDAPConfig/EmbeddedLDAP/Property[@name='connectionPassword'],false.

In cipher-text.properties i have encrypted password for it. But when i launch Identity Server i get error:
       LDAP: error code 49 - INVALID_CREDENTIALS: Bind failed: ERR_229 Cannot authenticate user uid=admin,ou=system.

How to encrypt Embedded Ldap Password?
Also there is "PartitionAdmin" password in embedded-ldap.xml file. I encrypted it. IS is started normal with this encrypted password.

On [https://stackoverflow.com/questions/53773499/how-to-encrypt-embedded-ldap-password](https://stackoverflow.com/questions/53773499/how-to-encrypt-embedded-ldap-password) i got a reply that it is maybe a bug/limitation in WSO2.

**Comment by rksk** [comment]
It does not retrieve the value from cipher-text.properties file for the "connectionPassword" property in the <IS_HOME>/repository/conf/identity/embedded-ldap.xml even though secretAlias param exists. Instead, it uses the value defined inline within the embedded-ldap.xml file.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
