### ISSUE TITLE
Inconsistency in subject claim identifier appeared in access token and id token

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#4292]
**Description**
When the user belongs to secondary user store in a tenant domain, 'subject claim identifier' of the access token and id token behaves inconsistently.

Environment
IS 5.5.0 wum updated pack

**Steps to reproduce the issue**
1. Enable self-contained access token
2. Generate a self contained access token
```
Example:
curl -u <CLIENT_ID>:<CLIENT_SECRET> -k -d "grant_type=password&username=<USERNAME>&password=<PASSWORD>&scope=openid" -H "Content-Type:application/x-www-form-urlencoded" https://<IS_HOST>:<IS_HTTPS_PORT>/oauth2/token
```
3. Decode the generated access token and id token

**Actual Behaviour**
The 'Access_Token' contains the fully qualified user name but the 'Id_Token' does not contain the fully qualified username

Example:
- ID_TOKEN - "sub": "sashika@gmail.com",
- ACCESS_TOKEN - "DIP/sashika@gmail.com@cpaas.test"

**Expected behavior**
Subject claim identifier should be consistent in the 'access_token' as well as 'id_token'

**Note** - In order to get the fully qualified user name in the 'Id_Token', we need to enable '_Use user store domain in local subject identifier_' and '_Use tenant domain in local subject identifier_' in the Service Provider configuration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
