### ISSUE TITLE
Add new local claims to the migration client.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#4294]
We discovered that the old migration client doesn't add newly introduced local claims to the system when migrating from 5.2.0 to 5.3.0. As a result, an error is thrown when migrating from 5.5.0 to 5.6.0, since the new migration client expects those local claims to be present in the system.
We can add those missing claims to the [claim-config.xml](https://github.com/wso2/product-is/blob/master/modules/migration/migration-resources/5.6.0/data/claim-config.xml) file of 5.6.0 migration client so that it'll add the missing claims.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
