### ISSUE TITLE
Add audit logs for token revocation and renewal

### ISSUE THREAD

**Issue by nuwandiw** [wso2/product-is#4295]
More details on https://github.com/wso2-extensions/identity-inbound-auth-oauth/issues/1003

**Comment by mefarazath** [comment]
We also need to add the details to the docs.

**Comment by rksk** [comment]
Reopening since this is not documented yet. This needs to be enabled specifically.

```
[[event_listener]]
id = "token_revocation_audit_logger"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.data.publisher.oauth.listener.TokenRevocationAuditLogger"
order = "17"
enable = "true"
```

Sample audit entry
```
INFO {AUDIT_LOG} - Initiator : N/A | Action : PostTokenRevocationByClient | Target : TokenRevocationAuditLogger | Data : { "AuthenticatedUser" : "N/A", "AuthenticatedUserStoreDomain" : "N/A", "AuthenticatedUserTenantDomain" : "N/A", "ServiceProvider" : "test", "TokenType" : "access_token", "ActiveDuration" : "N/A", "RelyingParty" : "yWj8tXqhtfGaDuxMJqAbWMt4vxwa" } | Result : Success
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by sanjulamadurapperuma** [comment]
Reopening this as it has not yet been documented. Shall we document all of the relevant configurations for all applicable IS versions?
