### ISSUE TITLE
[Configuration Store] Features to Implement

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4303]
### Remaining features to be implemented in the JDBC based Configuration Store for WSO2 IS
- [x] Multi-database support
- [ ] A Caching layer
- [ ] Support for HTTP PATCH
- [ ] Support for  GET Resources, Attribute, Resource Type and File by ID.
- [ ] Pagination support
- [x] File management endpoint
- [ ] GET all resources per resource type and per-tenant domain
- [ ] Search API support: GET resources with multiple key,,value constraints joined by logical operator 'AND'. Ex: Get resources having **Attribute1=v1 AND Attribute2=v2**
- [ ] Tenant isolation support for Resource type
- [X] API documentation

**Comment by tharindu-bandara** [comment]
Please refer to the https://github.com/wso2/product-is/issues/4426

**Comment by emswbandara** [comment]
With the PR to add the schemas for all the database types, we need to remove this logic - https://github.com/wso2/carbon-identity-framework/blob/master/components/configuration-mgt/org.wso2.carbon.identity.configuration.mgt.core/src/main/java/org/wso2/carbon/identity/configuration/mgt/core/internal/ConfigurationManagerComponent.java#L152-L171 from the code as it becomes redundant in the master.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
