### ISSUE TITLE
[Doc]Redirection to old version of documnet.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#4305]
'Outbound Provisioning '
'run it'
'Management Console'
'Configuring an Identity Provider'
'SPML'
'SCIM'
'Salesforce connecter'
'Configuring Role and Permissions' 
and  'Configuring Users'
under 'Role Based Provisioning' in [1] pointed to older documents.

[1] https://docs.wso2.com/display/IS570/Role+Based+Provisioning

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
