### ISSUE TITLE
Unable to filter based on numeric values in SCIM2

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#4313]
**Steps to reproduce**

- Enable SCIM2
- Create a user with an attribute of a numeric value.

**Request**
curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jayawardana","givenName":"vindula"},"userName":"vindula","password":"vindula","phoneNumbers":[{"value":123456,"type":"home"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users

Filter users based on the numeric value of attribute email
**Request**
curl -k --user admin:admin "https://localhost:9443/scim2/Users?filter=emails.home+Eq+vindula_home.com"

**Response**
{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","scimType":"invalidValue","detail":"Not a valid attribute name/uri","status":"400"}

**Affected version**
wso2is-km-5.5.0

**Issue-Type**
Type/Bug

**Comment by GDRDABARERA** [comment]
This is resolved with this
