### ISSUE TITLE
Remove the warning printed by CEP component

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#4322]
Following warning is displayed when identity server is started in a clustering setup.

```
WARN {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} - CEP started with clustering enabled, but SingleNode configuration given.
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
