### ISSUE TITLE
How to Check Observability Logs Effectively

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#4323]
**Description:**

**Suggested Labels:**
IS-Documents
Observability

**Steps to follow:**
Select related log lines for a separate correlationID from the correlation.log file.
Paste them in a separate file and save it.
Create a spreadsheet and import the previously created file with the below configurations;
	Go to File and select import.
	Then select Upload in the Import File window and provide the path to the file created previously.
	Under Seperator Type, select custom and give the seperator as "|" and click on Import data button.

With other document types (microsoft office, libreoffice... etc), use "|" as delimeter and import as above.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
