### ISSUE TITLE
Role-based provisioning does not work properly when defined in Camel case

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/product-is#4324]
Role-based provisioning does not work properly when the **Identity Provider OutBound Provisioning Roles** is defined in Camel Case. 
![image](https://user-images.githubusercontent.com/15902071/51331029-c5f78a00-1a9e-11e9-98ef-a2f598bfcc52.png)

>Similar issues
https://github.com/wso2/product-is/issues/3689

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
