### ISSUE TITLE
remove "addressing" Axis2 module by default

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4326]
per step 3 of [Configuring Email OTP](https://docs.wso2.com/display/IS570/Configuring+Email+OTP), the "addressing" module must be disabled.

- should this be disabled by default?
- if there is a tradeoff when disabling the module, that should be noted in documentation pages recommending to disable it.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
