### ISSUE TITLE
Editing user profile with non-latin characters returns malformed values.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#4329]
Steps to reproduce.
1. IS 5.7 WUM 1544501821620 with MYSQL databases.
2. Create databases as `create database WSO2_CARBON_DB CHARACTER SET utf8 COLLATE utf8_Unicode_ci;`
3. Use the connection string : `<url>jdbc:mysql://localhost:3306/WSO2_CARBON_DB2?socketTimeout=1800000&amp;characterEncoding=UTF-8&amp;useSSL=false</url>`
4.  Add below line to **catalina-server.xml** file. 
    `<Valve className="org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve" 
                       headerToCorrelationIdMapping="{'activityid':'Correlation-ID'}" queryToCorrelationIdMapping="{'RelayState':'Correlation-ID'}"/>`
5. Create user from Mgt console -> Edit profile -> Set firstname -> `苏юзенत`
6. Save and view again. notice the malformed data.

Reason
The tomcat valve decodes the request that is going from the JSP with the form to the process JSP page. At that moment, it decodes the request using the default system encoding type as request doesn't have the encoding type set yet.

If we remove the valve this works fine.

**Comment by GDRDABARERA** [comment]
Resolved hence closing
