### ISSUE TITLE
Add configurations to disable metrics property by default

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/product-is#4330]
**Requirement**
The JVM metrics in the product is enabled by default and have to disable manually if a user does not need to use it, which is an unnecessary configuration for a user to handle. 

**Improvement**
Add configurations to disable metrics property by default.

**Related Git issues**
https://github.com/wso2/carbon-metrics/issues/76

**Comment by senthalan** [comment]
Fixed with https://github.com/wso2/product-is/pull/5955
