### ISSUE TITLE
Improve readbility of the error message.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#4333]
When a not-attached IDP is sent in the fidp parameter in the request in authorization code grant flow below screen appears. As seen in the screenshot there is an issue in the formatting of the error, related to readability.
![fidp](https://user-images.githubusercontent.com/791850/51509274-73132f00-1e1e-11e9-8acc-7410d7692540.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
