### ISSUE TITLE
Migration client does not properly migrate claims due to an additional white space.

### ISSUE THREAD

**Issue by RaveenAthapaththu** [wso2/product-is#4336]
We have found that some claims that are in registry in 5.3.0 are not migrated to 5.7.0.

When inserting the OIDC claims to the IDN_OIDC_SCOPE_CLAIM_MAPPING table we need to trim the claims. Otherwise, the claims won't be persisted because it fails to find the claim from the where clause as the claim contains additional white space. Eg: The value 'gender' contains an additional space.

ex : INSERT INTO IDN_OIDC_SCOPE_CLAIM_MAPPING (SCOPE_ID,
EXTERNAL_CLAIM_ID) SELECT 4,IDN_CLAIM.ID FROM IDN_CLAIM LEFT JOIN IDN_CLAIM_DIALECT ON IDN_CLAIM_DIALECT.ID
= IDN_CLAIM.DIALECT_ID WHERE CLAIM_URI=' gender' AND IDN_CLAIM_DIALECT.DIALECT_URI='http://wso2.org/oidc/claim'

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
