### ISSUE TITLE
Deprecate the Counting users feature in the management console

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4338]
Deprecate the feature in [1], as it create a continuous data source connections. The design was not applicable to a perfect  user search 

[1] https://docs.wso2.com/display/IS570/Counting+users+and+roles+using+Management+Console+and+Admin+Services

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
