### ISSUE TITLE
[Doc] The document for self contained access token does not mention to select "jwt" for Token Issuer

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4339]
[Doc] The document for self contained access token does not mention to select "jwt" for Token Issuer. The current document points to a standard page related to creation of a service provider and that page does not mention the selection of the option "jwt" for Token Issuer

refer 
https://docs.wso2.com/display/IS570/Self-contained+Access+Tokens
on step 3 the page [2]https://docs.wso2.com/display/IS570/Adding+and+Configuring+a+Service+Provider

But this link on step3 is not specific for creation of self contained access token. As a result we need to add a note for [2] which explains that for self contained access token we need to select "jwt"  for Token Issuer type

**Comment by michaldo** [comment]
Moreover, step 1 and step 2 from [Self-contained+Access+Tokens](https://docs.wso2.com/display/IS570/Self-contained+Access+Tokens) not necessary for version 5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
