### ISSUE TITLE
The ORACLE database scripts have NOT NULL DEFAULT '0' and the proper syntax should be DEFAULT '0' NOT NULL.

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4342]
The database scripts have NOT NULL DEFAULT '0' and the proper syntax should be DEFAULT '0' NOT NULL. Marked below is one such area with syntax error

CREATE TABLE SP_PROVISIONING_CONNECTOR (CREATE TABLE SP_PROVISIONING_CONNECTOR (     ID INTEGER,     TENANT_ID INTEGER NOT NULL,            IDP_NAME VARCHAR (255) NOT NULL ,     CONNECTOR_NAME VARCHAR (255) NOT NULL ,     APP_ID INTEGER NOT NULL,     IS_JIT_ENABLED CHAR(1) DEFAULT '0',     BLOCKING CHAR(1) DEFAULT '0',     RULE_ENABLED CHAR(1) **NOT NULL DEFAULT '0**',            PRIMARY KEY (ID))

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
