### ISSUE TITLE
Documentation typo in "Sample configuration of bps-datasources.xml"

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/product-is#4348]
There is a documentation typo in "Sample configuration of bps-datasources.xml" in https://docs.wso2.com/display/IS570/Setting+Up+Deployment+Pattern+1. 
```
<url>jdbc:mysql://wso2is-pattern1-mysql-service:3306/WSO2_IDENTITY_DB autoReconnect=true&amp;verifyServerCertificate=false&amp;useSSL=true</url>
```
There is a missing "?" in the connection URL after WSO2_IDENTITY_DB. It should be corrected as follows.
```
<url>jdbc:mysql://wso2is-pattern1-mysql-service:3306/WSO2_IDENTITY_DB?autoReconnect=true&amp;verifyServerCertificate=false&amp;useSSL=true</url>
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
