### ISSUE TITLE
Invalid Session when using Mobile Connect as a Federated Authenticator

### ISSUE THREAD

**Issue by alshaikh1** [wso2/product-is#4349]
Hi, 
I'm trying to use WSO2 with Mobile Connect authentication, I followed the steps in the WSO2 docs.
When trying to access MobileConnect Discovery from localhost:8080/travelocity.com/index.jsp , it returns an error (session is not valid). however, it works perfectly when doing so from the same server browser.

In other words, accessing the mobileconnect discovery is not working when I browse it from the public internet.
Server OS: Ubuntu 18.04
WSO2 IDS: 5.70
Mobile Connect credentials: Preproduction

![image](https://user-images.githubusercontent.com/8459043/51712601-f3f94300-2037-11e9-9ebc-9e7c807e8fee.png)

Any suggestion?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
