### ISSUE TITLE
Supporting User store preference order during authentication

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#4350]
Currently, if the user doesn't specify the user store domain name with username then we are trying to authenticate the user with all the available user store. I am in the process of implementing a  feature to support authentication against a predefined user store list.

If more than one user stores having the same user name with different passwords then during the authentication we must have to specify the user store domain. In case if user stores are LDAP or AD and the user store domain couldn't be appended to the username then there can be issues like account locking if AD and LDAP have configured for wrong password policies. So with the current implementation, the following requirement can't be full filled without specifying the user store domain along with the username.

**Requirement**

1. AD and LDAP have configured for wrong password policies. AD and LDAP are having the same user(let's say the username is bob) with a different password.
2. Employees only can access SP1(service provider) and Employees details are stored in UserStore1(LDAP).
3. Customers only can access SP2 and Customers details are stored in UserStore2(AD).

Now if either employee or customer tries to log in to SP1 without specifying the userStoredomain then the user will be searched to both the user store domains
We need to fix this and allow the users to search only through UserStore1 for SP1 application, allow the users to search only through UserStore2

**Comment by nilasini** [comment]
Created a doc issue[1] to track the documentation 

[1] https://github.com/wso2/docs-is/issues/405
