### ISSUE TITLE
Issue with calculation of x5t header in JWTs

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#4352]
I generated an id_token using the latest WUM pack of IS 5.7.0 and tried validating the JWT in jwt.io
 
id_token
 
eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiVXI3V0VLaHFPdW92V21acF9mMnFXUSIsImF1ZCI6IjZzbE0xbkFGMXhFSGZzSVp3RllaaHpWT2xEd2EiLCJzdWIiOiJhZG1pbiIsIm5iZiI6MTU0Mzk5MDE3NiwiYXpwIjoiNnNsTTFuQUYxeEVIZnNJWndGWVpoelZPbER3YSIsImFtciI6WyJwYXNzd29yZCJdLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjE1NDM5OTM3NzYsImlhdCI6MTU0Mzk5MDE3Nn0.j2by-aoWu5dbM5HpI887afF8ggGfbQdNAreGWWQAVSV2OF4AdNkfTSzDNuSEjFGaYOTgaywlJKnhEtgLEgyse8KWiDD6N9Ezvp87Mo2HfyuSKJhJHSXRaKfGQyyJZTjhrgxuuytNKrSVQYDslCeVyBeMJUsn_ZOFz5uv7Yq4fULte3tG5Xa31eVk6xvjX2owD06FbPdLUkpRtRwEiWq17mupR0PPjiJU_0GZ134lKhq1j8bdYKeH6aSmRIWUZzmPQUVc23hmFqWeEwnpH3Vnd6y7wUCnE9vXUcKOrpcvvCDqAnTJFFmaJyr7q22e9djcF9GI2u4TZwgFAvOkndx4Cg
 
Default public cert in X509 format,
----BEGIN CERTIFICATE----
MIIDSTCCAjGgAwIBAgIEAoLQ/TANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwJV
UzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxDTALBgNVBAoT
BFdTTzIxEjAQBgNVBAMTCWxvY2FsaG9zdDAeFw0xNzA3MTkwNjUyNTFaFw0yNzA3
MTcwNjUyNTFaMFUxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMN
TW91bnRhaW4gVmlldzENMAsGA1UEChMEV1NPMjESMBAGA1UEAxMJbG9jYWxob3N0
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAluZFdW1ynitztkWLC6xK
egbRWxky+5P0p4ShYEOkHs30QI2VCuR6Qo4Bz5rTgLBrky03W1GAVrZxuvKRGj9V
9+PmjdGtau4CTXu9pLLcqnruaczoSdvBYA3lS9a7zgFU0+s6kMl2EhB+rk7gXluE
ep7lIOenzfl2f6IoTKa2fVgVd3YKiSGsyL4tztS70vmmX121qm0sTJdKWP4HxXyq
K9neolXI9fYyHOYILVNZ69z/73OOVhkh/mvTmWZLM7GM6sApmyLX6OXUp8z0pkY+
vT/9+zRxxQs7GurC4/C1nK3rI/0ySUgGEafO1atNjYmlFN+M3tZX6nEcA6g94Iav
yQIDAQABoyEwHzAdBgNVHQ4EFgQUtS8kIYxQ8UVvVrZSdgyide9OHxUwDQYJKoZI
hvcNAQELBQADggEBABfk5mqsVUrpFCYTZZhOxTRRpGXqoW1G05bOxHxs42Paxw8r
AJ06Pty9jqM1CgRPpqvZa2lPQBQqZrHkdDE06q4NG0DqMH8NT+tNkXBe9YTre3EJ
CSfsvswtLVDZ7GDvTHKojJjQvdVCzRj6XH5Truwefb4BJz9APtnlyJIvjHk1hdoz
qyOniVZd0QOxLAbcdt946chNdQvCm6aUOputp8Xogr0KBnEy3U8es2cAfNZaEkPU
8Va5bU6Xjny8zGQnXCXxPKp7sMpgO93nPBt/liX1qfyXM7xEotWoxmm6HZx8oWQ8
U5aiXjZ5RKDWCCq4ZuXl6wVsUz1iE61suO5yWi8=
----END CERTIFICATE----
 
And the tool showed the signature was verified successfully.
 
 
I tried to generate the x5t manually and compare with the one we send in the id_token
 
1. Get the cert thumbprint (https://www.samltool.com/fingerprint.php)
501fc1432d87155dc431382aeb843ed558ad61b1
 
2. Base64url encode the value (https://simplycalc.com/base64url-encode.php)
NTAxZmMxNDMyZDg3MTU1ZGM0MzEzODJhZWI4NDNlZDU1OGFkNjFiMQ==
 
3. Compared this with the value we send in the id_token
 
calculated = NTAxZmMxNDMyZDg3MTU1ZGM0MzEzODJhZWI4NDNlZDU1OGFkNjFiMQ==
id_token x5t = NTAxZmMxNDMyZDg3MTU1ZGM0MzEzODJhZWI4NDNlZDU1OGFkNjFiMQ
 
URL decoding the values gives,
calculate      = 501fc1432d87155dc431382aeb843ed558ad61b1
id_token x5t = 501fc1432d87155dc431382aeb843ed558ad61b
 
There is a difference here as we have missed base64url encoding the thumbprint at id_token generation logic[1] and JWT generation logic[2]. This could be why some libraries fail during signature validation.
 
So this needs to be fixed both in id_token and JWT generation logic.
 
Few things to note,

* Even with this bug, signature validation passed in jwt.io
* This bug is not in the way we calculate the thumbprint but rather due to an error in failing to base64 URL encode the calculated thumbprint.
 
[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L2012
 
[2] https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.keymgt/src/main/java/org/wso2/carbon/apimgt/keymgt/token/AbstractJWTGenerator.java#L393

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
