### ISSUE TITLE
Having question mark in the commonAuthCallerPath during the direct logout from commonauth leads to invalid call back url

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#4353]
Ex:
`https://localhost:9443/commonauth?commonAuthLogout=true&type=oidc&sessionDataKey=RANDOMSTRING&commonAuthCallerPath=http%3A%2F%2Fwww.example.com%2Ffoo%3Fbar&relyingParty=playground`

Invaild URL having two '?' charatcers.
`http://www.example.com/foo?bar?sessionDataKey=RANDOMSTRING`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
