### ISSUE TITLE
[Feature] Pluggable cache implementation replacing Hazelcast based Cache

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#4355]
Currently IS (and Carbon4.x) based products uses Hazelcast for underlying cache implementation.
It has been made less reliant on Hazelcast distributed cache [(Kernel 1833)](https://github.com/wso2/carbon-kernel/pull/1833).

However it still relies on Hazelcast for Invalidation message sending when a local cache is used. No invalidation message means a cache entry in one node will not be invalidated due to change done by another node.

It is a good improvement to remove this hard dependency on Hazelcast on caching layer. Here are few (not exhaustive list of) problems need to be solved.

1. Change underlying cache (kernel 4) layer to accept different ached implementation
2. Pluggable cluster node discovery mechanism. Currently Hazelcast abstract almost all cluster discovery (e.g. WKA, AWS, K8S, Multicast, ECS, etc.). Need to find a rich abstraction layer similar to that provided by Hazelcast.
3. Pluggable cluster messaging mechanism. IS used cluster messages for triggering artifact deployment and synchronization. We may remove the artifact deployment/sync mechanism altogether so that this requirement will not be needed. (BTW, artifact deployment/sync is not advisable in container world)

Related [#1781][#1855]

**Comment by nirmal070125** [comment]
ref: 001E000001244KH

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
