### ISSUE TITLE
Role-based provisioning does not work when a new user creates with  assigning a role sequentially

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#4356]
Steps to reproduce : 
Role-based user Provisioning between two WSO2 Identity Servers
Configuring the Internal IS
1. Configuring an identity provider with Role Configuration and Outbound Provisioning Connector-SCIM
2. Configuring outbound provisioning
3. Add New User with assigning a role which is configured in identity provider

Configuring the External IS
1. Inbound Provisioning Configuration-select Domain

Expected result : user should be provisioned to the external identity provider
Actual result : user does not  provision to the external identity provider

**Comment by nilasini** [comment]
Track with https://github.com/wso2/product-is/issues/4357
