### ISSUE TITLE
Role-based provisioning does not work when a new user creates with assign a role sequentially.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#4357]
IAM version wso2is-5.7.0
Steps to reproduce :  Role-based user Provisioning between two WSO2 Identity Servers 

Configuring the Internal IS
1. Configuring an identity provider with Role Configuration and Outbound Provisioning Connector-SCIM
2. Configuring outbound provisioning
3. Add New User with assigning a role which is configured in identity provider
Configuring the External IS
1. Inbound Provisioning Configuration-select Domain

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
