### ISSUE TITLE
[SCIM2.0] Sorting support for SCIM2 API

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/product-is#4362]
WSO2 IS SCIM API does not support sorting.

Sample request
`curl -v -k --user [username]:[password] https://localhost:9443/scim2/Users?sortBy=userName`

Response
```
{
    "schemas": "urn:ietf:params:scim:api:messages:2.0:Error",
    "detail": "Sorting is not supported",
    "status": "501"
}
```

Ref https://tools.ietf.org/html/rfc7644#section-3.4.2.3

**Comment by ashensw** [comment]
Reducing the severity as this is a request for a new feature.

**Comment by AnuradhaSK** [comment]
Related  issue https://github.com/wso2/product-is/issues/9772

**Comment by ruwanta** [comment]
Sorting and Pagination does not work on multiple user stores unless taken all data to memory and do the operation in memory.
By nature of Identity server it is a must to support multiple user stores.
Pagination and sorting can only be implemented if the query runs on single user store having RDBMS semantics.

Hence this request need to be done carefully, or should not be done at all.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
