### ISSUE TITLE
[Doc][IS 5.5.0][SCIM2] Documentation states support for pagination and sorting which is unsupported

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/product-is#4363]
The pagination and sorting features of the SCIM2 API are not supported in WSO2 IS-5.5.0. However, the documentation states that it is supported and hence it misleads the customers. This needs to be improved.

Related documentation:
https://docs.wso2.com/display/IS550/apidocs/SCIM2-endpoints/#!/operations#UsersEndpoint#getUsersByPost

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
