### ISSUE TITLE
Spaces appended on the certificate content in IAM management console service providers' edit functionality

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/product-is#4368]
To recreate the issue

1. Create an application in the store.
2. Log in to IAM management console.
3. Under service provider click the edit button of any service providers 
4. You can see extra spaces appended at the end of the certificate content in Application certificate 
5. Remove the spaces and update
6. Redo the above flows and you can see the spaces appended again

If the certificate is updated (by removing the spaces) in step 4 successfully the request flow works fine but if you click the edit button again the spaces are appended, which means every time the page loads on the edit function the spaces are appended at the end of the certificate content. 

<img width="1674" alt="screen shot 2019-01-29 at 9 28 13 am" src="https://user-images.githubusercontent.com/18033158/51884526-981f1900-23ad-11e9-9d22-5b1b3d1d3bb9.png">

**Comment by nilasini** [comment]
@DivyaPremanantha it is not reproducible with default IS 5.8.0 pack hence closing the issue.
