### ISSUE TITLE
[Registry] Disable the versioningProperties in the Default Pack

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4377]
In the existing wso2is product, the static registry configuration versioningProperties in [1] is by default enabled. This will keep a version history of the registry properties. However, the default value should be set to false.

[1] IS_HOME/repository/conf/registry.xml

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
