### ISSUE TITLE
Obfuscate username from the response of Token Introspection Endpoint

### ISSUE THREAD

**Issue by abhishekdesilva** [wso2/product-is#4378]
**Description:**
The current implementation of the Identity Server provides the following response when the Token Introspection Endpoint is being invoked.

`{ "active": true, "client_id": "l238j323ds-23ij4", "username": "jdoe", "scope": "read write dolphin", "sub": "Z5O3upPC88QrAjx00dis", "aud": "https://protected.example.net/resource", "iss": "https://server.example.com/", "exp": 1419356238, "iat": 1419350238, "extension_field": "twenty-seven" }`

As per the information which can be seen in the response, 'username' of the resource owner is a privacy sensitive information and it is being shared across the network. With regard to the [1], measures MUST be taken to prevent disclosure of this information to unintended parties.

**Affected Product Version:**
All the versions of the Identity Server

[1] https://tools.ietf.org/html/rfc7662#section-5

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
