### ISSUE TITLE
Add issuing a new token per request configuration at SP level

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4380]
Currently issuing a new token per request is configured on a global level affecting all service providers. Add the ability to configure this feature per service provider.

**Comment by malithie** [comment]
@janakamarasena , IIRC, this improvement is done.
Could you please link the PR for this

**Comment by janakamarasena** [comment]
@malithie Nope, what I did was adding the configuration at a global level

**Comment by malithie** [comment]
@janakamarasena , In that case please link the issue which resolved the global level config

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
