### ISSUE TITLE
password policy violation grammar issue

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4382]
the default password policy violation message is `Password pattern policy violated. Password should contain a digit[0-9], a lower case letter[a-z], an upper case letter[A-Z], one of !@#$%&* characters`.  This should be changed to `Password pattern policy violated. Password should contain a digit[0-9], a lower case letter[a-z], an upper case letter[A-Z], and one of the characters !@#$%&*`.

This message [seems to come from carbon-identity framework](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-event/org.wso2.carbon.identity.event.server.feature/resources/identity-event.properties)

**Comment by omindu** [comment]
Thanks for reporting this @hauntingEcho.

@inthirakumaaran @piraveena can one of you send the PR correcting this ?
