### ISSUE TITLE
[DOC] User Information Recovery Service document should include information on how to set user challenge question answers

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#4385]
Doc link: https://docs.wso2.com/display/IS570/User+Information+Recovery+Service

Issues:

1. Document do not specify the exact request URL or the service name(UserInformationRecoveryService)
2. It doesn't have information on how to set the user's answers to challenge questions.
       - Need to use the method **setUserChallengeAnswers** in **ChllengeQuestionManagementAdminService** to answer the questions.

**Comment by malithie** [comment]
IMO, this deprecated service should be documented only in IS 5.2.0 doc space.
I think we already point to those docs for legacy identity management and that should be enough.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
