### ISSUE TITLE
[DOC] Migration guide link for Updating WSO2 Products redirects to non existing page

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#4387]
Doc: 
[1] https://docs.wso2.com/display/IS570/Upgrading+From+an+Older+Version+of+WSO2+IS#UpgradingFromanOlderVersionofWSO2IS-Migratingthedata
[2] https://docs.wso2.com/display/IS570/Upgrading+from+the+Previous+Release

![migration](https://user-images.githubusercontent.com/5061791/52043784-964c8580-2566-11e9-9fbf-ead8f40c6f12.png)

Link [Updating WSO2 Products](https://docs.wso2.com/display/ADMIN44x/Updating+WSO2+Products
) doesnt exists. It should be [https://docs.wso2.com/display/updates/Using+WSO2+Update+Manager](https://docs.wso2.com/display/updates/Using+WSO2+Update+Manager)

**Comment by nilasini** [comment]
Fixed from IS-5.2.0 to IS-5.8.0

\[1] https://docs.wso2.com/display/IS580/Upgrading+from+the+Previous+Release
