### ISSUE TITLE
[SCIM2.0] Enable SCIM only for specific user stores

### ISSUE THREAD

**Issue by madeesha** [wso2/product-is#4388]
If there are two user-store as PRIMARY and EXTERNAL and SCIM is only enabled for External user store,  /scim2/Users rest call does not work.  It gives the below error, 

"Error","detail":"Cannot get the user through scim to user store. SCIM is not enabled for user store PRIMARY","status":"500"

the other rest calls such as  /scim2/Users/{uuid} works as expected. 

Root cause: when this rest API is invoked ( /scim2/Users), it calls the listUsersWithGET method in SCIMUserManager.java. 
It retrieves all the usernames as follows,
 userNames = carbonUM.getUserList(userIdLocalClaim, "*", null);

This userName contains all the users in PRIMARY and EXTERNAL user stores. And then it gets the scimuser by passing the userName to the getSCIMUser method. 
User scimUser = this.getSCIMUser(userName, requiredClaimsInLocalDialect);

When a user who is in a PRIMARY user store (which SCIM is disabled) passed to the above method, the below exception throws, and it breaks the flow. 

Cannot get the user through scim to user store. SCIM is not enabled for user store PRIMARY

**Comment by emswbandara** [comment]
Same issue can be reproduced with /Groups endpoint when SCIM is enabled for the secondary userstore and disabled for primary userstore. 

This issue is fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/135
