### ISSUE TITLE
Backward compatibility broken in JIT provisioning users with  IDP mapped roles

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#4391]
Configure Two IS servers for SAML federated authentication.

1. Comment out "MulitAttributeSeparator" property in the user-mgt.xml
2. Create two roles X and Y
3. Create a user and assign role X and Y
5. Create a SP and enable role claim as requested one.
The SAML Response should contain the role claim as a concatenated string
```
<saml2:AttributeStatement>
      <saml2:Attribute Name="role"
                       NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xsi:type="xs:string">Internal/everyone,X, Y</saml2:AttributeValue>
      </saml2:Attribute>
    </saml2:AttributeStatement> 
```

On the local IS,
1. Create a federated IDP
2. Enable JIT provisioning 
3. Add role mapping for X and Y IDP roles
X --> Internal/X
Y --> Internal/Y
4. Configure an SP and configure Federated IDP configured above as authentication mechanism

First try above setup in IS 5.2.0.

* Login to SP using the federated IDP
* You will see that the user is **provisioned** correctly with Internal/X and Internal/Y roles.

Then try the same in IS 5.6.0
* You will see that the user is provisioned but mapped roles are **missing in the provisioned user**.

This behaviour change happens due to below code change.

IS 5.2.0
----------
https://github.com/wso2/carbon-identity-framework/blob/v5.2.2/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/sequence/impl/DefaultStepBasedSequenceHandler.java#L630-L635

IS 5.6.0
-----------
https://github.com/wso2/carbon-identity-framework/blob/v5.12.153/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkUtils.java#L1552-L1562

ie. In 5.2.0 role claims is split using comma(,) and the list is processed for role mappings so in the above example,
Internal/everyone,X, Y --> ["Internal/everyone","X", "Y"] --> [Internal/X,Internal/X]

But in IS 5.6.0 when **no MulitAttributeSeparator** is configured it defaults to ",,," (three commas). This results in 
Internal/everyone,X, Y --> ["Internal/everyone,X,Y"] --> [] 
(Internal/everyone,X, Y  is treated as a single string..)

This behaviour change has been introduced in IS 5.4.0.

**Comment by M0nikaSharma** [comment]
Hi All,
As above fixed is closed in the 5.8.0 version of wso2 identity server. But still role mapping is not working in 5.8 version of IS.I am using the wso2-is - 5.8.0 version as local IS and federated IDP.
