### ISSUE TITLE
[Doc] We need to mention the user create a key with the CN/SAN to overcome  SSL peer failed hostname validation for name: localhost on admin dashboard

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4393]
[Doc] We need to mention the user create a key with the CN/SAN to overcome  SSL peer failed hostname validation for name: localhost on admin dashboard

steps
We need to mention that the below steps be followed where the user mentions the CN/SAN to avoid the blow error

```
TID: [-1234] [] [2019-01-28 22:26:20,222] INFO {org.apache.axis2.transport.http.HTTPSender} - Unable to sendViaPost to urlhttps://localhost:9444/services/AuthenticationAdmin {org.apache.axis2.transport.http.HTTPSender}
javax.net.ssl.SSLPeerUnverifiedException: SSL peer failed hostname validation for name: localhost
```

1.Creating keystore & self-signed certificate

keytool -genkeypair -keystore wso2carbon.jks -dname "CN=da3d-gen-aut-rpt005.dalab.syniverse.com, OU=Eng, O=WSO2, L=MountainView, ST=CA, C=US" -keypass wso2carbon -storepass wso2carbon -keyalg RSA -alias wso2carbon -ext SAN=dns:localhost

2.Export generated certificate

keytool -export -alias wso2carbon -file wso2carbon.cer -keystore wso2carbon.jks

Enter keystore password as prompted(wso2carbon)

3.Import the cert into trustore of WSO2 IS

keytool -importcert -file wso2carbon.cer -keystore client-truststore.jks -alias "wso2carbon"
 Enter keystore password as prompted(wso2carbon)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
