### ISSUE TITLE
Generating same access token for all users with Client Credential Grant Type

### ISSUE THREAD

**Issue by HareeshYHY** [wso2/product-is#4396]
The application receives the same access token for the user for the grant type Client_Credentials.
An unauthenticated user launch the application

apiGateway: https://sandbox-test.com:8243/token
grant_type=client_credentials

**Steps To reproduce the issue.**

**User 1  in  Machine 1** 
  {"access_token":"65f2f8a9-f45b-3d08-a8c4-f40eef3fe471", "scope":"am_application_scope default","token_type":"Bearer","expires_in":1989}

**User 2  in  Machine 2** 
  {"access_token":"65f2f8a9-f45b-3d08-a8c4-f40eef3fe471","scope":"am_application_scope default","token_type":"Bearer","expires_in":1962}

**User 3  in  Machine 3** 
  {"access_token":"65f2f8a9-f45b-3d08-a8c4-f40eef3fe471","scope":"am_application_scope default","token_type":"Bearer","expires_in":1778}

**Note** :- access token is same for all user with different expiry times.

**Here is my concern: -**
Why we are getting same access toke for all user, is there any way to refresh?
Is there any approach to get the new access toke for each user request?
Is there any way to update the expiry time for each new request?

Please help me to resolve the issue.

**Comment by HareeshYHY** [comment]
**The issue is with Unauthenticated user**

Two unauthenticated launches the application from and we are using the same client key, client secret for the request. We are getting same access token for the 2 unauthenticated users.

grant_type=client_credentials

**`Here is the response for the 2 Unauthenticated users`**

**Unauthenticated User 1**
{"access_token":"65f2f8a9-f45b-3d08-a8c4-f40eef3fe471", "scope":"am_application_scope default","token_type":"Bearer","expires_in":1989}

 **Unauthenticated User 2**
{"access_token":"65f2f8a9-f45b-3d08-a8c4-f40eef3fe471","scope":"am_application_scope default","token_type":"Bearer","expires_in":1962}

**`Here is the Requirement: -`**
**Is there any approach to get different access token and the expiry time with Client credential grant for all the unauthenticated users?**
 
**Is there any approach to get different token by using Client credential grant?**
**Expected Result**
**User1**
{"access_token":"**123456**", "scope":"am_application_scope default","token_type":"Bearer","expires_in":**3600**}

 **User2**
{"access_token":"**987654**", "scope":"am_application_scopedefault","token_type":"Bearer","expires_in":**3600**}

**Is there any approach to get the same fixed expiry time for each unauthenticated user?**
**Expected Result**
**User1**
{"access_token":"**123456**", "scope":"am_application_scope default","token_type":"Bearer","expires_in":**3600**}

**User2**
{"access_token":"**123456**", "scope":"am_application_scope default","token_type":"Bearer","expires_in":**3600**}

Please help me to resolve the issue.

**Comment by nikhil4326** [comment]
Can we use 'authorization code' grant for anonymous user(a user without login and credentials)?

**Comment by Kavindu-Dodan** [comment]
> Can we use 'authorization code' grant for anonymous user(a user without login and credentials)?

Unfortunately, this is not the intended usage of the Authorization code grant defined by[ RFC6749](https://tools.ietf.org/html/rfc6749#section-4.1) . According to the specification, mentioned grant must interact with the resource owner (simply user).

> The authorization code grant type is used to obtain both access tokens and refresh tokens and is optimized for confidential clients. Since this is a redirection-based flow, the client must be capable of interacting with the resource owner's user-agent (typically a web browser) and capable of receiving incoming requests (via redirection) from the authorization server.

If your use case involves an anonymous user, then I see two approaches you can try.

1. Allow user to register and obtain credentials 

This is supported by WSO2 IS. More can be read from [this](https://docs.wso2.com/display/IS570/Self-Registration+and+Account+Confirmation) link.

2. Obtain access token for anonymous users through client credential grant

Given that there is no user login, your application can obtain tokens that are granted on client credentials. From your backend, you can expose APIs which allow access on top of access tokens obtain through client credential grant. How to do the separation ? For this you can use [WSO2 token introspection ](https://docs.wso2.com/display/IS570/Invoke+the+OAuth+Introspection+Endpoint) and verify for **scope** and **username** values.

**Comment by ms019** [comment]
For the above suggestion, we observe a peculiar behavior. When we have user 1 and user 2 accessing application simultaneously with client credential grant and getting distinct token, It is observed that within sometime the token for both users get revoked somehow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
