### ISSUE TITLE
Passive STS metadata.xml contains hard coded URL values.

### ISSUE THREAD

**Issue by SaubhagyaW** [wso2/product-is#4409]
In a scenario which a hostname is changed, a proxy port is configured and a custom proxy context path is added, none of the above changes are reflected in the URLs configured in Passive STS metadata.xml (<IS_HOME>/repository/deployment/server/webapps/mex/metadata.xml), which will fail the Passive STS login flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
