### ISSUE TITLE
Patch operation Failed with 500 when group is assigned

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#4413]
1. Add a user
2. Add a role
3. Assign the role to the user
4. Do a patch operation. It fails with following error.
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in performing the patch operation on user resource.","status":"500"} 
5. Remove the user from the role
6. Do a patch operation.
7. Patch request is successful.

**Comment by malithie** [comment]
@DMHP , Is this fixed in the master ?

**Comment by DMHP** [comment]
Closing as this is already fixed in master.
