### ISSUE TITLE
[Doc] Missing steps in 'Configuring X509Certificate Authenticator' 

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#4414]
**Background**
Prior to 570 WSO2 IS versions, CRL and OSCP validations were disabled in the certificate-validation.xml file in the <IS_HOME>/repository/conf/security/ repository. 

From 570 onwards, the certificates of CAs and intermediate CAs that are to be considered as trusted CAs for X509 authentication must be configured in the certificate-validation.xml as follows.

`<?xml version="1.0" encoding="ISO-8859-1"?>
<CertificateValidation xmlns="http://wso2.org/projects/carbon/certificate-validation.xml">
…….
<TrustStores>
    <TrustStore truststoreFile="/path/to/truststore.jks" truststorePass="cacertspassword" type="JKS"/>
</TrustStores>
</CertificateValidation>
`

To complement this behaviour, CRL and OSCP validations were enabled by default from WSO2 IS 570 onwards. So, if you don't want to configure the truststore as given above, you will have to disable the CRL and OSCP validation as well.

**To-Do**
Add a separate section subsequent to the 'Configuring the X509 Certificate for the app' section in the [Configuring X509Certificate Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator) page to explain this behavior.

**Comment by YvonneW** [comment]
Added a new section called [Disabling Certificate Validation](https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator#ConfiguringX509CertificateAuthenticator-DisablingCertificateValidation) with the steps required to disable CRL and OCSP validators.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
