### ISSUE TITLE
[Improvement]  Need to modify the end user error message when there is a connection issue with the userstore.

### ISSUE THREAD

**Issue by madeesha** [wso2/product-is#4416]
If there is a connection issue with the user store, though the user enters a valid username and password, UI shows "invalid username or password" error to the end user. It is misbehaving to the end user and we need to provide a message like "Service unavailable" in such scenarios. 
We need to concern this in the future releases.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
