### ISSUE TITLE
isFederated flag is not set for authorized user with JWT Bearer Grant when the token info is taken from the database 

### ISSUE THREAD

**Issue by azinneera** [wso2/product-is#4417]
This issue is observed in identity-inbound-auth-oauth-5.6.63.

When an access token is generated by passing a saml bearer, the user is handled as a federated user and therefore, the **isFederated** flag for the user is set to true. When the token is unavailable in the cache (e.g. after the cache timeout) the latest access token information is taken from the database and the properties are set to the authorized user and added to the cache. Setting the isFederated flag is missed here and therefore during the API invocation, in scenarios where the user store is accessed, this will fail to identify the user in the userstore. An exception similar to the below posted lines will be thrown.
```
org.wso2.carbon.user.core.UserStoreException: Invalid Domain Name
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:170)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.isExistingUser(AbstractUserStoreManager.java:3646)

```
This has been fixed in  identity-inbound-auth-oauth-6.0.53 (for wso2is-5.7.0 ) by the improvements done for #4189. Same has to be done for v5.6.63.

**Comment by malithie** [comment]
Fixed along with https://github.com/wso2/product-is/issues/4189
