### ISSUE TITLE
[Doc] Retrieving user information through introspection endpoint

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4425]
We can retrieve user information as a JWT through introspection endpoint by following the below steps. We need to include this information in our introspection documentation \[1]

1. Enable AuthorizationContextTokenGeneration as mentioned in [2]
2. Invoke the introspection endpoint with the required claims (if it is more than one then it should be comma separated values) similar to below request.
`curl -k -u admin:admin -H 'Content-Type: application/x-www-form-urlencoded' -X POST --data 'token=bff07310-610b-33c1-8d79-95c8c93024e6&required_claims=http://wso2.org/claims/emailaddress' https://localhost:9443/oauth2/introspect`
4. Then we will get a JWT with the introspection response. If we decode the JWT we could see that the requested claims will be retrieved through the JWT.

\[1] https://docs.wso2.com/display/IS570/Invoke+the+OAuth+Introspection+Endpoint
\[2] https://docs.wso2.com/display/IS570/JWT+Token+Generation#JWTTokenGeneration-Configurations

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
