### ISSUE TITLE
[IS 5.6.0] User ID Claim URI cannot be saved by selecting a local claim uri in basic claim configuration - IDP

### ISSUE THREAD

**Issue by madeesha** [wso2/product-is#4431]
User ID Claim URI cannot be saved in basic claim configuration of the identity provider in IS 5.6.0.

Steps to recreate:

Add an IDP 
Go to claim configuration -> Basic claim configuration 
Select a local claim URI for "User ID Claim URI"
Click on update  => it is not saved

**Comment by IshikaGodage** [comment]
Hi @madeesha,
I was unable to reproduce the issue. Can you mention the specification of the distribution that you used ?

**Comment by malithie** [comment]
This is fixed in IS 5.7.0 and not visible.
Thus, closing the issue
