### ISSUE TITLE
Dashboard backend admin service URL is not configurable

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#4434]
If we are setting up a proxy for the identity server and set proxy host and port as mentioned in [doc](https://docs.wso2.com/display/IS530/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Changinghostnamesandports), then all the admin service calls from the dashboard and portal jaggery apps are using `https://proxy_host:proxyport/services` URL.

There are some cases, we need to avoid these admin service calls going through proxy and hit the backend direclty.

According to [doc](https://docs.wso2.com/display/IS530/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Settingupthedashboard), it seems that URL is configurable using `site.json`. But according to the [code](https://github.com/wso2/product-is/blob/master/modules/jaggery-apps/user-dashboard/dashboard/util/utility.jag), the `proxyHost` and `proxyPort` set in `site.json` is discarded in the `setServerURL()`.

**Comment by nilasini** [comment]
Fixed with 
https://github.com/wso2/product-is/pull/4518
https://github.com/wso2/product-is/pull/4662
