### ISSUE TITLE
[Doc] [5.7.0] Configuring X509Certificate Authenticator

### ISSUE THREAD

**Issue by nihlaakram** [wso2/product-is#4438]
The doc [1] for Configuring X509Certificate Authenticator in IS 5.7.0 is incorrect. The following are the corrections to made specifically for 5.7.0 version.

1. Do not need to add org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector-X.X.X.jar, already available in the product.
2. Do not need to add x509certificateauthenticationendpoint.war, already available in the product.
3. Disable crlvalidator and ocspvalidator in the registry through the management console

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator#6b39a9c6aacc4b998fa20e098aec2215

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
