### ISSUE TITLE
[Doc] description on the use of claim dialect for a service provider

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#4439]
Can we have a section that explains the use of claim dialect when we configure a service provider. This should include the purpose its benefits for the service provider configuration. We could include that under the section : **Click here for details on how to configure claims**

```
**Service Provider Claim Dialect**

When the service provider claim dialect is configured without configuring claim mapping from the top config it returns all claims defined in the respective dialect. But, in case, claim mappings are defined along with that, it won't return all but a subset.
```

https://docs.wso2.com/display/IS570/Adding+and+Configuring+a+Service+Provider

**Comment by NCMEC-daavendasora** [comment]
Adding this documentation for the "Service Provider Claim Dialect" property would be _hugely helpful_. I spent an enormous amount of time digging through the documentation for 5.10 and 5.11 trying to understand exactly what this setting does is for but could not find it.

https://is.docs.wso2.com/en/latest/learn/configuring-claims-for-a-service-provider/ does not even mention the property.

**Comment by rksk** [comment]
This is not recommended to be used as an alternative for requested claims. The expected use case of this configuration is eIDAS SAML Attribute Profile for IS [1]. Ref: https://github.com/wso2/product-is/issues/11390#issuecomment-806419822

[1] https://is.docs.wso2.com/en/5.10.0/learn/eidas-saml-attribute-profile-support-via-wso2-identity-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
