### ISSUE TITLE
[Doc] Incorrect description for parameter name on resource description

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4443]
User management access end point document [1] has incorrect description for resource name parameter.
Current description as below, 
A human-readable string naming the resource. **The authorization server can use the referenced icon in the user interface when presenting information to a resource owner.**
The bolt section should be correct. 

[1]https://docs.wso2.com/display/IS570/User+Managed+Access+Endpoints

Type: Doc/product scenario
Affected version: 5.7 +

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
