### ISSUE TITLE
NPE and 200 OK for invalid bearer tokens

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/product-is#4444]
WhAt the moment we get a NPE in server log along with a 200 OK empty response for invalid bearer tokens

Steps to reproduce

- Invoke token introspection endpoint with an invalid bearer token

Impacted product - IS 5.3.0

**Comment by DMHP** [comment]
Tested in the latest IS 5.8.0-M24 pack. As this is already fixed in the latest pack closing the issue.
