### ISSUE TITLE
[Doc][5.1.0] Missing step to when setting up samples

### ISSUE THREAD

**Issue by nihlaakram** [wso2/product-is#4445]
The document [1] needs an additional step to move back to the is-samples folder before running the checkout(Step 3) command.

[1] https://docs.wso2.com/display/IS510/Downloading+a+Sample

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
