### ISSUE TITLE
[Doc] Reviewing 'Mutual TLS for OAuth Clients' doc page

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#4448]
The [Mutual TLS for OAuth Clients](https://docs.wso2.com/display/IS570/Mutual+TLS+for+OAuth+Clients) needs to be reviewed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
