### ISSUE TITLE
[DOC] Improve information related to adding secondary user stores manually.

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#4451]
We have [1] explaining how a user can add a secondary JDBC user-store by deploying a file. (Without using the Admin UI or the admin services)

But we have not explained how a user can get the password field encrypted. Saving the user store file as XML does not encrypt the password automatically.

In order, get IS to encrypt the password need to follow the below steps.

1. Create the user store config file and remove any "encrypted" attribute (if any) from the password field. Name the file <userstore_domain_name>.enc (with .enc extension)
2. Copy the .enc file to IS_HOME/repository/deployment/server/userstores
3. This will encrypt the password field, deploy the user store and rename the user store configuration file as <userstore_domain_name>.xml

[Archive.zip](https://github.com/wso2/product-is/files/2873191/Archive.zip)

This information needs to be in our docs.

[1] https://docs.wso2.com/display/IS560/Configuring+a+JDBC+User+Store#ConfiguringaJDBCUserStore-SampleConfigurationforJDBCUserstoremanager

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
