### ISSUE TITLE
created and last modified time in get SCIM2 call doesn't return "Z" even though it is in UTC format

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4455]
The current behavior of created and last modified time is as follows.

1. Without the JVM parameter -Dscim2.compliance=true 
Create a user through SCIM2
The user is stored in the database in local time (Eg:- 2019-02-18T13:27:58)
Get call to SCIM, give the created time as local time (Eg:- 2019-02-18T13:27:58)

2. With the JVM parameter -Dscim2.compliance=true 
Create a user through SCIM2
The user is stored in the database in UTC time (Eg:- 2019-02-18T08:03:34Z)
Get call to SCIM, give the created time in UTC time  (Eg:- 2019-02-18T08:03:34) but without the suffix "Z"
"Z" is used to indicate that the time zone is "UTC" [1] hence we should not remove the "Z" when we giving a UTC time. Because according to the SCIM specification date format should include the "Z" [2]. In that case, the fix for the issue should be improved [3] which is removing the "Z" of UTC format. 

[1] https://www.timeanddate.com/time/zones/z
[2] https://tools.ietf.org/html/rfc7643#section-2.3.5
[3] https://github.com/wso2/product-is/issues/4401

**Comment by Kavindu-Dodan** [comment]
This is already fixed in public Charon under PR  https://github.com/wso2/charon/pull/157
