### ISSUE TITLE
[Doc] Improve information on using SQL queries when adding a secondary user stores manually

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#4456]
**Description:**
When adding a JDBC user-store while using the provided SQL queries in the documentation [1] under "Sample Configuration for JDBC User store manager", not all of them can be used at once. 
Only around 7-8 queries can be used. But there is no limitation mentioned on the number of queries that can be used at once.
And also it is better if we mentioned clearly that it is our **recommendation** that not to use the default queries in user-store configuration unless you need to change the default ones.

https://docs.wso2.com/display/IS560/Configuring+a+JDBC+User+Store

**Suggested Labels:**
IS-Documents

**Affected Product Version:**
IS-5.6.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
