### ISSUE TITLE
Missing index in IS IDN_OAUTH2_AUTHORIZATION_CODE table from 5.1.0 to 5.2.0 migration

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#4457]
The index CREATE INDEX IDX_AUTHORIZATION_CODE ON IDN_OAUTH2_AUTHORIZATION_CODE (AUTHORIZATION_CODE,CONSUMER_KEY_ID) is introduced in IS 5.2.0 and it was not there in the migration client.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
