### ISSUE TITLE
[Doc] Update the documentation for Setting Up Deployment Pattern2 -Minimum High Availability Deployment for WSO2 IS-Analytics

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/product-is#4458]
The documentation[1] contains outdated instructions on setting up deployment pattern 2 with Identity Server analytics. It should be updated with the instructions to setup the pattern 2 by appluying the changes to the deployment.yaml files instead of XML files as before.
1. https://docs.wso2.com/display/IS570/Setting+Up+Deployment+Pattern+2#SettingUpDeploymentPattern2-MinimumHighAvailabilityDeploymentforWSO2ISAnalytics

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
