### ISSUE TITLE
[New Feature] "Initiating Login from a Third Party" as per the OpenID Connect specification.

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-is#4460]
Currently, "Third-party initiated login flow" as per the OpenID Connect specification [1] is not available in WSO2 IS. 
It would be better if this can be incorporated into the product in a future release.

[1] https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin

**Comment by hauntingEcho** [comment]
For further background, the end-to-end workflow that would be supported by this would be:

1. starting state:
    * user is not authenticated to WSO2IS, any SP, or any IdP
    * multiple IdPs are connected with which a user may authenticate
      * generally one IdP per customer organization, controlled by that customer
    * user exists in IdP A, as well as SaaS SPs X and Y
    * IdP A provides an application menu, such as F5's \[1]
      * that menu contains links to X and Y
1. user authenticates to A.
1. user clicks link to X
1. without further user interaction, user goes to X and is authenticated.

Currently, this is possible if both A & X are SAML2-based via spEntityId, but is not possible if either use OpenID Connect.  To a certain extent, a workaround can be done using the `fidp` parameter, but as this is non-standard it cannot be used by off-the-shelf OpenID-based service providers or those heavily dependent on libraries.

\[1] -
![Windows-Live-Writer-V11_92D5-apmwebtop21_2](https://user-images.githubusercontent.com/1661988/54055079-818c8e80-41b1-11e9-8546-3945e8e5d55c.png)

**Comment by hauntingEcho** [comment]
ideally this could be done in such a way that the SP configuration could be changed (e.g. between SAML2 & OIDC implementations) without needing a change in the configuration in the IdP - e.g. by using `${server}/serviceproviders/${SP_Name}` provided from upstream (via e.g. SAML2's `RelayState` or OIDC's `target_link_uri`) which would then choose the correct way to forward the user to the SP based on the SP's configuration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
