### ISSUE TITLE
[Doc] Brocken hyperlink  for  User Managed Access with WSO2 Identity Server documentaion

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4462]
User Managed Access with WSO2 Identity Server document, obtain a permission ticket section [1] navigation hyperlinks for obtain PAT token and registering the report are incorrect. 
Valid hyperlinks should be like,
`<a href="#UserManagedAccesswithWSO2IdentityServer-ObtaintheProtectionAPIAccesstoken(PAT)" </a>`
and 
`<a href="#UserManagedAccesswithWSO2IdentityServer-Registeringtheresource"> </a>`

but available  like,
`<a href="#UserManagedAccesswithWSO2IdentityServer-GettingtheProtectionAPIAccesstoken(PAT)" </a>`
and 
`<a href="#UserManagedAccesswithWSO2IdentityServer-Registertheresource" </a>`

Type: doc/product scenario
product version: 5.7/5.8

[1] https://docs.wso2.com/display/IS570/User+Managed+Access+with+WSO2+Identity+Server#UserManagedAccesswithWSO2IdentityServer-Obtainapermissionticket

**Comment by sherenewso2** [comment]
Fixed in  versions 5.7.0 and 5.8.0 [1]
[1] https://docs.wso2.com/display/IS580/User+Managed+Access+with+WSO2+Identity+Server#UserManagedAccesswithWSO2IdentityServer-Obtainapermissionticket
