### ISSUE TITLE
no feature to set configuration in service provider level when configuring Email OTP 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#4463]
When configuring email otp using [this](https://docs.wso2.com/display/IS570/Configuring+Email+OTP#ConfiguringEmailOTP-ConfiguringtheEmailOTPproviderConfigureGmailastheemailOTPprovider) guide it gives us two options for OTP provider.
1)WSO2 IS
2)Gmail

but when setting configurations it has to be done globally . There is no feature to do it in service provider level

**Comment by malithie** [comment]
Default axis2 transport should not be configured for this case and it should be either an authenticator level config done globally or at the federated authenticator level when configured as IdP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
