### ISSUE TITLE
[SequenceConfig] Introduce a Method to Retrieve the StepConfig by Step Number

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4467]
In the current implementation, a step configuration for the given step number is retrieved from a **SequenceConfig** object is done by exposing the step map internal object[1].
```
context.getSequenceConfig().getStepMap().get(stepNumber)
```
This need to be implemented with a better approach, by providing a new method, **getStepConfig(stepNumber)** to the **SequenceConfig** class[1] similar to the one below.
```
    public StepConfig getStepConfig(Integer stepNumber) {
        
        return this.stepMap.get(stepNumber);
    }
```
Once this is fixed, we need to deprecate the **getStepMap()** method[1] to prevent exposing the internal stepMap object outside. 

[1] https://github.com/wso2/carbon-identity-framework/blob/772a285037212f6a7e702589e03c4ebf705130f0/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/config/model/SequenceConfig.java#L65

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
