### ISSUE TITLE
[DOC] Change of  session idle timeout in identity.xml won't reflect the existing tenants

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4469]
During the first startup, the session idle timeout is read from the identity.xml file and persisted in the DB
Thereafter session idle timeout is read from the DB. Any changes to the identity.xml won't be reflected in existing tenants. Any tenant created **after the change will have the updated session idle timeout** value by default.

This information needs to be updated in **all IS version's** documents \[1]

\[1] https://docs.wso2.com/display/IS560/Configuring+Session+Timeout

**Comment by gomathyk** [comment]
I have modified the following document in order to add this information: 
[1](https://docs.wso2.com/display/IS560/Configuring+Session+Timeout )

**Comment by rksk** [comment]
@gomathyk we have to fix this issue in all the IS versions

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
