### ISSUE TITLE
[5.7.0] Scim2/users api doesn't return response when User name is added having '$' character.

### ISSUE THREAD

**Issue by deepaksharma1982** [wso2/product-is#4471]
Add **$testuser@abc.com** from Tenant admin in add new user section.
Home>Identity	>Users and Role>Add>Add New User
Enter username as **$testuser@abc.com** and Defined password.It will be added successfully .

After adding user run the **scim2/users** api from JMeter for the tenant and we see the following error comes in WSo2 server logs.
ERROR -  Error occurred while accessing Java Security Manager Privilege Block
Error occurred while retrieving SCIM user information
org.wso2.charon3.core.exceptions.CharonException: Error occurred while retrieving SCIM user information
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block
Caused by: java.lang.IllegalArgumentException: No group with name {c1}
                at java.util.regex.Matcher.appendReplacement(Matcher.java:849)
                at java.util.regex.Matcher.replaceFirst(Matcher.java:1004)
                at java.lang.String.replaceFirst(String.java:2178)

Looks like the User added **$testuser@abc.com** is not valid therefore JAVA API fails in replaceFirst() method.
So this user name is actually invalid and There should be validation in Tenant side for adding the New User as Valid email id.

**Comment by hpmtissera** [comment]
This bug cannot be reproduced in 5.8.0-m24-SNAPSHOT

Steps :

UsernameJavaRegEx property under UserStoreManager in user-mgt.xml set as following to allow $ for usernames.

```
<Property name="UsernameJavaRegEx">^[\S]{3,30}$</Property>
```

Add user $testuser@abc.com under tenant test@test.com via Management Console

Request 

```
curl -v -k --user test@test.com:password https://localhost:9443/t/test.com/scim2/Users/660944d1-7a08-4903-acb1-1aba32bbdb16
```

Response 

```
{  
   "meta":{  
      "created":"2019-03-11T11:46:46Z",
      "lastModified":"2019-03-11T11:46:46Z",
      "resourceType":"User"
   },
   "schemas":[  
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
   ],
   "roles":[  
      {  
         "type":"default",
         "value":"Internal/everyone"
      }
   ],
   "name":{  
      "familyName":"$testuser@abc.com"
   },
   "id":"660944d1-7a08-4903-acb1-1aba32bbdb16",
   "userName":"$testuser@abc.com"
}
```

**Comment by DMHP** [comment]
Thanks @hpmtissera for the contribution. I will close the issue based on the above comment.
