### ISSUE TITLE
[Doc] WSO2IS-5.7.0 is not compatible with older JTDS driver versions

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#4474]
**Description:**
WSO2IS-5.7.0 is not compatible with JTDS driver version 1.2.6 or below. 
The reason is within WSO2IS-5.7.0, we have used a method called **isClosed** and the same method is not available in JTDS driver version 1.2.6 or below. It is only available in JTDS drivers after version 1.2.6.

This should be mentioned in the documentations saying that WSO2IS-5.7.0 is compatible with JTDS driver versions **higher than** 1.2.6 only.

**Suggested Labels:**
IS-Documents

**Affected Product Version:**
IS-5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
