### ISSUE TITLE
Documentation for User's failed login attempts based adaptive authentication

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#4476]
The documentation for this [feature](https://github.com/wso2/product-is/issues/3951) needs to be added to the doc space

Refer "User's failed login attempts based adaptive authentication" in dev@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
