### ISSUE TITLE
Enable additional Error Messages for Password Policy authenticator

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#4479]
In some systems need to be aware of additional information at any failures during the [password policy Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Password+Policy+Authenticator) flow as in following.

https://docs.wso2.com/display/IS530/Customizing+Authentication+Error+Messages and https://docs.wso2.com/display/IS530/Error+Codes+and+Descriptions

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
