### ISSUE TITLE
[Doc] Update the documentation including details related to scope validators

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4480]
Suggested Labels
Type/Docs
Affected/IS 5.7.0

In a OAuth2-openid connect single sign on flow as mentioned in [1] scope validators can be configured for a service provider. But the doc does not have details related to Role based scope validators. As a improvement suggest to add details related to how this 2 differs and why we should use them and how to use them under [1]. Related to xacml based scope validators we can link to [2] from [1]. But couldnt find details related to how role based scope validators can be used. 

[1]. https://docs.wso2.com/display/IS570/Configuring+OAuth2-OpenID+Connect+Single-Sign-On
[2]. https://docs.wso2.com/display/IS570/Validating+the+Scope+of+OAuth+Access+Tokens+using+XACML+Policies

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
