### ISSUE TITLE
two DefaultPasswordGenerators - the one currently active by default does not comply with the default password regex

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4484]
Currently, the default-configured (although disabled) password regex requires numbers, lowercase letters, capital letters, and special characters.

Currently, there are two implementations of `DefaultPasswordGenerator` - [one of which](https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt.common/src/main/java/org/wso2/carbon/user/mgt/common/DefaultPasswordGenerator.java) follows this requirement, and [one of which](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/password/DefaultPasswordGenerator.java) does not.  The non-compliant implementation is the one configured by default in `repository/conf/identity/identity.xml` ([source](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L644)) and `identity-mgt.properties` ([source](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/identity-mgt.properties#L85)).  The compliant implementation should be the default, and the non-compliant implementation should be removed.

See also #2501

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
