### ISSUE TITLE
disconnect versioning of `org.wso2.carbon.user.mgt.common` from `carbon-identity-framework`

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4485]
currently, [custom password generators](https://github.com/wso2/product-is/issues/2501) are dependent on `org.wso2.carbon.user.mgt.common`.  The codebase of this package has not changed in a year, but in that time it has had [hundreds of unnecessary versions](https://github.com/wso2/carbon-identity-framework/commits/master/components/user-mgt/org.wso2.carbon.user.mgt.common) due to being tied to the versioning of carbon-identity-framework.  This creates extra overhead for maintainers of addons based on this package, such as customer password generators.

Splitting the codebase & lifecycle of these two packages would greatly improve the stability of such addons.

**Comment by malithie** [comment]
Unless there is a requirement to use some specific API being introduced in some latter version of the dependent component `org.wso2.carbon.user.mgt.common`, I don't think there is any necessity to change the dependent component version when building up the extension.
As in runtime, if the extension defines a major to minor, or major to major version range, it will get resolved to the version which is available in the runtime within its version range. We don't see any complications there.

Therefore, appreciate if you can elaborate more on the experience in maintaining the custom password generator extensions and limitations observed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
