### ISSUE TITLE
[DOC] Wrong hyperlink to the sample

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#4490]
Link provided to access the sample in the following documentations result in 404 error.
Sample is not in the accessed URL path (https://github.com/wso2/samples-is/tree/master/sample-post-authentication-handler)

https://docs.wso2.com/display/IS550/Post-authentication+Handlers+in+Identity+Server
https://docs.wso2.com/display/IS560/Post-authentication+Handlers+in+Identity+Server
https://docs.wso2.com/display/IS570/Post-authentication+Handlers+in+Identity+Server
https://docs.wso2.com/display/IS580/Post-authentication+Handlers+in+Identity+Server

The Post-authentication handler sample code is accessible through the following URL
https://github.com/wso2/samples-is/tree/master/etc/sample-post-authentication-handler

Kindly modify the mentioned documentations pointing to the correct sample path.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
