### ISSUE TITLE
[DOC] SimpleSAMLPHP SLO Response URL Configured in IS is wrong

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#4491]
In the following documentation which guides the customer to configure the SimpleSAMLPHP application as a Service Provider for IS. There are some misconfigurations.

- In the following IS540 documentation
https://docs.wso2.com/display/IS540/Logging+in+to+SimpleSAMLphp+using+Identity+Server

```
SLO Response URL: http://localhost/simplesamlphp/www/module.php/saml/sp/saml2-logout.php/wso2-sp
```
This URL is not accessible, I tested the setup locally. This needs to change as follows.

```
SLO Response URL: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/wso2-sp
```

- In the following IS530 documentation

https://docs.wso2.com/display/IS530/Configuring+SimpleSAMLphp+as+a+Service+Provider

Same change mentioned above applies.

- In the following IS510 documentation

https://docs.wso2.com/display/IS510/How+To%3A+Configure+SimpleSAMLphp+as+a+Service+Provider

```
Logout URL: http://localhost/simplesamlphp/www/module.php/saml/sp/saml2-logout.php/wso2-sp
```
This logout URL need to be changed as follows
```
Logout URL: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/wso2-sp
```
Kindly fix the above mentioned documentations.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
