### ISSUE TITLE
[Doc] Update 'Configuring reCaptcha for Single Sign On' doc page

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#4495]
**Background**

In order to enable reCaptcha for SSO, we need to enable the Account Locking feature. This information is missing in the [docs](https://docs.wso2.com/display/IS530/Configuring+reCaptcha+for+Single+Sign+On).

**Comment by YvonneW** [comment]
Updated the following docs:

- https://docs.wso2.com/display/IS530/Configuring+reCaptcha+for+Single+Sign-On
- https://docs.wso2.com/display/IS530/Setting+Up+ReCaptcha
- https://docs.wso2.com/display/IS540/Configuring+reCaptcha+for+Single+Sign-On
- https://docs.wso2.com/display/IS540/Setting+Up+ReCaptcha
- https://docs.wso2.com/display/IS541/Configuring+reCaptcha+for+Single+Sign-On
- https://docs.wso2.com/display/IS541/Setting+Up+ReCaptcha
- https://docs.wso2.com/display/IS550/Configuring+reCaptcha+for+Single+Sign-On
- https://docs.wso2.com/display/IS550/Setting+Up+ReCaptcha
- https://docs.wso2.com/display/IS560/Configuring+reCaptcha+for+Single+Sign-On
- https://docs.wso2.com/display/IS560/Setting+Up+ReCaptcha
- https://docs.wso2.com/display/IS570/Configuring+reCaptcha+for+Single+Sign-On
- https://docs.wso2.com/display/IS570/Setting+Up+ReCaptcha

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
