### ISSUE TITLE
Supporting configuration for validating algorithm used for signing purposes

### ISSUE THREAD

**Issue by SachiniSiriwardene** [wso2/product-is#4498]
Currently it is not possible to restrict signed messages sent to IS to be signed by a particular algorithm, from a common end point. We need to support a configurable approach to specify acceptable signing algorithms for inbound assertions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
