### ISSUE TITLE
Table creation scripts related to configuration store feature are missing. 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#4499]
Table creation scripts related to Configuration Store feature [1] not available. Following PR available for H2 and MySQL. Require other DBMS as well.

[1] https://github.com/wso2/carbon-identity-framework/pull/2022
[2] https://github.com/wso2/carbon-identity-framework/pull/2026

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
