### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release is observed in Java 11

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#4501]
Warning: Nashorn engine is planned to be removed from a future JDK release is observed when running the adaptive authentication scripts in  Java 11

**Comment by JKAUSHALYA** [comment]
Since the version that the Nashorn will be removed not announced yet, changing the severity of this issue to a minor. However, this will be a high priority task.

**Comment by senthalan** [comment]
Can we hide this warning for 5.9.0 as this warning will be logged per authentication request in java 11

**Comment by JKAUSHALYA** [comment]
> Can we hide this warning for 5.9.0 as this warning will be logged per authentication request in java 11

Please check https://stackoverflow.com/questions/55641738/how-to-hide-java-11-nashorn-deprecation-warnings

**Comment by senthalan** [comment]
https://github.com/wso2/carbon-identity-framework/pull/2414 with this the warning will be removed in jdk 11. And created https://github.com/wso2/product-is/issues/6404 to track the migration of GraalVM from nashorn. Hence closing this issue

**Comment by senthalan** [comment]
Warning temporarily hiden with https://github.com/wso2/product-is/commit/994125fb90e6f02ce8782c87d574fe6f409b7e5b
