### ISSUE TITLE
Modify syntax : Ask Password Option with SCIM API

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#4503]
[1]https://docs.wso2.com/display/IS570/Creating+Users+Using+the+Ask+Password+Option#CreatingUsersUsingtheAskPasswordOption-SCIM2.0

Added syntax for the scenario where Ask Password Option is enabled and user is inserted with SCIM call.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
