### ISSUE TITLE
Redirect to Git: Password Reset doesn't work as expected in Password Policy Authenticator

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#4504]
Doc: https://docs.wso2.com/display/ISCONNECTORS/Configuring+Password+Policy+Authenticator 

Doc was modified to direct the user to the git documentation if the authenticator version was v1.0.8

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
