### ISSUE TITLE
Modify: Quick Start Guide 

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#4507]
The QSG is modified with the new approach eliminating the need for Tomcat. 
Doc: [1](https://docs.wso2.com/display/IS570/Quick+Start+Guide#QuickStartGuide-FATOP)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
