### ISSUE TITLE
Wrong regex causes open curly bracket to be accepted for username and role name

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/product-is#4510]
Impacted versions - IS 5.3.0 
Need to be tested - All other product versions

Steps to reproduce,

1. Obtain a fresh pack
2. Create a new user;  Home -> Add User
3. Insert a username with open curly brace(s)

ex: test{ , test{{, {{{{ , test{test

User will be created even through regex does not allow open curly brace

This is observed for adding new roles as well.

**Comment by Kavindu-Dodan** [comment]
Issue seems to be caused by not escaping meta characters properly. IS 5.3.0 default ships with regex **[a-zA-Z0-9._-|//]{3,30}$** for UsernameJavaRegEx and RolenameJavaRegEx. According to Java documentation [1],  characters **|** , **/** and **-** are meta characters present in our default regex. But these are not properly escaped. This issue seems to occur due to this invalid escaping 

[1] - https://docs.oracle.com/javase/tutorial/essential/regex/literals.html

**Comment by Kavindu-Dodan** [comment]
On closer look, issue was caused by regex section  **_-|** which converts to a single character in the range between character 95 to 124. This include open curly bracket "{" as well as  grave accent "`"

**Comment by ashensw** [comment]
Reducing the severity as this can be addressed with a simple configuration as suggested above.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
