### ISSUE TITLE
User retrieval through scim and user delete fails if user name was created with open curly bracket

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/product-is#4511]
This issue is related to https://github.com/wso2/product-is/issues/4510.

Issue is evident in IS 5.3.0 as bug 4510 allows user names to be accepted with open curly bracket. But if regex allows curly brackets, then issue can be reproduced in IS 5.7.0 too.

Steps to reproduce,

1. Start a fresh pack
2. Crete a user with open curly bracket. Ex:- test{
3. Try to delete the user or retrieve users through scim

Note that this is observed when cache get activated. For example, obtaining users second time through scim.

Possible code line causing this is referred here [1]. We believe message formatter is not essential when retrieving user through cache as we already cache formatter entries. 

[1] - https://github.com/wso2-support/carbon4-kernel/blob/support-4.4.35/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ReadOnlyLDAPUserStoreManager.java#L832

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
