### ISSUE TITLE
[Doc] Properly Document fix for product-is#4361

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#4512]
- At the moment username claim is populated only if we have enabled "SCIMEnabled" property true in user-mgt.xml or secondary userstore properties. But we should picked up the username that we entered during user creation, even without having "SCIMEnabled" considering username claim as a special claim
- This fix introduces a new property `<OverrideUsernameClaimFromInternalUsername>` in the user-mgt.xml file in the `<carbon-home>/repository/conf` folder
- When this property is set to **true** it will override the username claim value with the internal username
- If this is set to **false**, It will retrieve the username claim value from the UM_USER table and this will be read only
- Default value should be **false**
-  To enable this fix globally, add the below property to the user-mgt.xml file in the  `<carbon-home>/repository/conf` folder, under the  `<Configuration>` tag. By default we have switched off the feature by making it this false.
```
<UserManager>
    <Realm>
        <Configuration>
        ...
        
        <OverrideUsernameClaimFromInternalUsername>false</OverrideUsernameClaimFromInternalUsername>
        ...
```

**Comment by YvonneW** [comment]
Added the related instructions under the 'Configure primary user store with datasource' section of the [560 - Configuring a JDBC User Store](https://docs.wso2.com/display/IS560/Configuring+a+JDBC+User+Store#ConfiguringaJDBCUserStore-ConfigurePrimaryuserstorewithdatasource) page.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
