### ISSUE TITLE
Inconsistency in SCIM2 user filtering

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4514]
Currently, when using the SCIM2 API to retrieve users using filtering there are few inconsistencies in the way the API returns users based on the query parameters we specify.

1. In single attribute filtering with or without count query param, It will return the users from all userstores.
/scim2/Users?count=10&filter=name.givenname+co+sam

2. In multi-attribute filtering with count It will return the users from only the PRIMARY userstore.
/scim2/Users?count=10&filter=name.givenName+co+sam+and+username+co+sam

3. In order to retrieve users from a secondary userstore we need to specify the userstore using the domain query param.
/scim2/Users?count=10&filter=name.givenName+co+sam+and+username+co+sam&domain=SECONDARY

4. If pagination is not required, when using multi-attribute filtering we can retrieve users from all userstores without the need to specify the domain query param (currently not working due to a bug [1]).
/scim2/Users?filter=name.givenName+co+sam+and+username+co+sam

The behaviour of 2, 3 and 4 are also documented in the SCIM2 docs[3].

In brief when using multi-attribute filtereing with pagination we need to specify a userstore domain and when using multi-attribute filtereing without pagination we don't need to specify the userstore domain. 

[1] - https://wso2.org/jira/browse/IDENTITY-7383
[3] - https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#UsersEndpoint#getUser

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
