### ISSUE TITLE
[DOC] Need to document more details on Adaptive authentication excuteStep API 

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#4516]
The document [1] says the API can have 3 parameters as executeStep(stepId, options, eventCallbacks) where stepId is mandatory and the parameters 'options' and 'eventcallbacks' are optional. 

The document should also contain the following details on this API to provide a better understanding to write AA scripts.  

- This API can be called with only stepId as a parameter. 
` eg: executeStep(1); `
- This API can be called with only stepId and evenCallbacks. 
` eg: executeStep(1, {onSuccess: function(context) { // Do something on success }); `
- This API cannot be called with only stepId and options. If we need so, we need to add an empty array in place of evenCallbacks. 
` eg: executeStep(1, {authenticationOptions:[{authenticator: 'totp'}]}, {}); `

[1]https://docs.wso2.com/display/IS570/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-executeStep(stepId,options,eventCallbacks)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
