### ISSUE TITLE
Explain Authorization headers in Account Recovery REST API docs

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#4520]
There are two issues in the account recovery rest api docs [1]. 

1. The authorization header is given as ""Authorization: Basic YWRtaW46YWRtaW4=" without a proper explanation on what that random value represents. 

Instead, we can simply use the "--basic -u <username>:<password>" option. 

2. In 5.7.0 and 5.5.0 [2], the request has the value "car" for the second challenge question answer. Instead, it should have the place holder 'answer2". This has been fixed in 5.3.0, 5.4.0, and 5.6.0 but has missed 5.5.0 and 5.7.0. 

[1] https://docs.wso2.com/display/IS530/apidocs/account-recovery/index.html#!/operations#PasswordRecovery#securityQuestionsGet
[2] https://docs.wso2.com/display/IS570/apidocs/account-recovery/index.html#!/operations#SecurityQuestion#validateAnswerPost

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
