### ISSUE TITLE
[DOC] Invalid  call back URL example in the OAuth2-OpenID Connect Single-Sign-On configuration document

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4521]
Invalid sample call back url for the sample web app playground.
Expected callback url: https://myapp.com/callback|https://testapp:8000/callback
Actual callback url: https://myapp.com/callback|https://testapp:8000/callback**)**
Document: https://docs.wso2.com/display/IS570/Configuring+OAuth2-OpenID+Connect+Single-Sign-On

Affected : Version 5.2.0 +
Severity: Minor
Priority : Normal
Component : SAML SSO
Type: Document/product scenario

**Comment by sherenewso2** [comment]
Closing this because the bracket is required there. It's inside a code block where we are asking the user to set the regex pattern as follows:

regexp=(https://myapp.com/callback|https://testapp:8000/callback)
