### ISSUE TITLE
[Doc]Improve the documentation for Add a prompt for user input java script function

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4525]
We could see a documentation which explains add user prompt \[1] but it needs to be improved with some more details like below.

If we want to add our own function according to the user action on the prompted page then we could achieve it as below.

1. Create a template page in <IS_HOME>/repository/deployment/server/webapps/authenticationendpoint/templates folder
2. Add the page to template-mapper.jsp
3. In the custom page add buttons according to the requirement.
4. In the custom page add a javascript function to create different input elements(name of the inputs should start with "**action.**" Eg:- action.existing, action.new) according to the button click.
5. In the adaptive authentication script adds a function like "onExisting, onNew" (the function name should be "on" appended with second part of the input name(existing/new) with capitalized first letter(E/N)) like below.

```
function onLoginRequest(context) {
 var username = context.request.params["username"][0];
 prompt("custompage", {
    "username": username,
"inputs": [{"id": "existing", "label": "Existing User"}, {"id": "new", "label": "New User"}]
  }, {
    onNew: function (context) {
        executeStep(1);
  },
    onExisting: function (context) {
        executeStep(2);
  }
 });
}

```

\[1] https://docs.wso2.com/display/IS570/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-prompt(templateId,data,eventHandlers)

**Comment by sherenewso2** [comment]
https://github.com/wso2/product-is/issues/3442

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
