### ISSUE TITLE
[DOC] Enable <commitOnReturn> Property For Versions With Improper DB Transaction Closing

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4527]
We need to fix the [issue](https://github.com/wso2/product-is/issues/4526) for upcoming releases.

For the versions without the fix, `<commitOnReturn>` pooling property needs to be enabled in the data source, as mentioned in the above issue.

This needs to be included in the document space.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
