### ISSUE TITLE
Need to assign registry write permission for a non-admin user to update SP role mapping/permission

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#4528]
In order to update the role/permissions of a service provider for a user other than the super tenant admin in management console, it is required to assign registry write permissions for that user. By default only the super admin role will have the registry write permissions.

Therefore in order to assign registry write permissions, following steps needs to be followed. We need to add this to the doc in [1] 

Log into management console as super admin.
Go to Main > Registry section and click 'browse'.
In the location box type '/_system/governance/permission/applications' and click on 'Go' button. This will open up the applications registry collection view page.
Click on the '+' mark next to 'permissions' tab. This will expand the 'New Role Permissions' section.
Now select the subjective role from the drop down list and choose 'Write' as the action and click on 'Add Permission'
Now that role should be visible under 'Defined Role Permissions'. Make sure that 'write' permission is allowed for that role.

[1] https://docs.wso2.com/display/IS550/Configuring+Roles+and+Permissions+for+a+Service+Provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
