### ISSUE TITLE
[Doc] Need to update the list of .jar files in the documentation.

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#4536]
**Description:**
We need to add one more Jar file except to the list mentioned in the documentation [1]. And also one mentioned Jar file is not available in the WSO2IS-KM-5.7.0 pack.

Content of the below attachment should replace in the setup-authentication.sh script's relevant section mentioned in the documentation [2] since it contains the scripts for WSO2IS-5.3.0.
[jars.txt](https://github.com/wso2/product-is/files/2930332/jars.txt)

[1] https://docs.wso2.com/display/IS570/Hosting+Authentication+Endpoint+on+a+Different+Server
[2] https://docs.wso2.com/display/IS570/Hosting+Authentication+Endpoint+on+a+Different+Server#HostingAuthenticationEndpointonaDifferentServer-step2

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
WSO2IS-KM-5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
