### ISSUE TITLE
[Doc] Need to update authentication request in  Passing OIDC Authentication Request Parameters in a Request Object  Documentation

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#4537]
**Description**
Invalid authentication request in [Passing OIDC Authentication Request Parameters in a Request Object](https://docs.wso2.com/display/IS570/Passing+OIDC+Authentication+Request+Parameters+in+a+Request+Object) , Testing the flow section. 
`https://localhost:9443/oauth2/authorize?request=<JWT>` 
by referring to the [OIDC Specs](https://openid.net/specs/openid-connect-core-1_0.html#RequestParameter) this should be replaced with 
`https://localhost:9443/oauth2/authorize?response_type=code%20id_token&client_id=<client ID>&redirect_uri=http%3A%2F%2Fwso2is.local%3A8080%2Fplayground2%2Foauth2client&scope=openid&nonce=n-0S6_WzA2Mj&request=<JWT>`

**Affected** : Version 5.5.0 +
**Suggested Severity**: Minor
**Suggested Priority** : Normal
**Component** : OIDC
**Type**: Document/product

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
