### ISSUE TITLE
Make buildAuthnRequest() and buildLogoutRequest() methods protected in DefaultSAML2SSOManager

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4540]
There is a requirement to override some attributes in the outbound SAML request, based on some dynamic contextual parameters. 

For example, update the issuer of the outbound SAML request to some value read from the service provider configuration.

We can extend the default Identity Server functionality to support this by extending DefaultSAML2SSOManager (org.wso2.carbon.identity.application.authenticator.samlsso.manager) and configuring the new class in repository/conf/application-authentication.xml under the authenticator name.

But - some important methods in the DefaultSAML2SSOManager class is private - and extending this class will result in lot of code duplication. 

Can we make buildAuthnRequest() and buildLogoutRequest() methods protected - so we can extend the new functionality by overriding those methods?

**Comment by darshanasbg** [comment]
Adding the location of DefaultSAML2SSOManager.java for ease of reference.
https://github.com/wso2-extensions/identity-outbound-auth-samlsso/blob/5.1.x/components/org.wso2.carbon.identity.application.authenticator.samlsso/src/main/java/org/wso2/carbon/identity/application/authenticator/samlsso/manager/DefaultSAML2SSOManager.java
