### ISSUE TITLE
[Doc]Enabling X509Certificate based authentication during ssl-termination

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#4542]
For the new feature, document need to be created. Please refer this public git issue for this particular feature [[1]](https://github.com/wso2/product-is/issues/4395).  Refer this blog [[2] ](https://medium.com/@piraveenaparalogarajah/configuring-x509-authenticator-in-wso2-identity-server-using-ssl-termination-with-nginx-1c21c6e5f27a)for further information about this feature.

[1]https://github.com/wso2/product-is/issues/4395
[2]https://medium.com/@piraveenaparalogarajah/configuring-x509-authenticator-in-wso2-identity-server-using-ssl-termination-with-nginx-1c21c6e5f27a

**Comment by danijelt** [comment]
The linked instructions don't work in IS 5.9.0. There's no option to configure X509 valve in `deployment.toml`, and manual edits in `catalina-server.xml` are overwritten on restart.

Same happens in `identity.xml` where `<X509>` element has to be added.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
