### ISSUE TITLE
Support "Monitor User Login Sessions" IS dashboard gadget to use IS Analytics 5.7.0

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4545]
The "Monitor User Login Sessions" gadget in IS5.7.0 which can be used to terminate user sessions[1] is currently only supported with IS analytics versions which has WSO2 DAS. Need to support the gadget to use with IS Analytics 5.7.0. 
This also needs to be documented for IS 5.7.0

The needed data is already published to IS Analytics[2]. 

[1] - https://docs.wso2.com/display/IS560/Terminating+User+Sessions
[2] - https://github.com/wso2/analytics-solutions/blob/master/features/is-analytics-feature/org.wso2.analytics.solutions.is.analytics.feature/src/main/resources/siddhi-files/IS_ANALYTICS_SESSION_DATA.siddhi#L27-L45

**Comment by janakamarasena** [comment]
We had several discussions for adding this capability internally without depending on IS Analytics.

**Comment by ayshsandu** [comment]
This is not supported internally withing the identity server components without needing the Analytics distribution. 
Fixed in https://github.com/wso2/product-is/issues/6054
