### ISSUE TITLE
Support for renew refresh token property to be configurable per application.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#4550]
Currently, the renew refresh token property value can be only configured globally from identity.xml.

We need to improve the current implementation of the IS for this property value to be configurable per application.

We can achieve this in a future minor version release.

**Comment by malithie** [comment]
@Dumindu-Kanchana , can you link the PR

**Comment by emswbandara** [comment]
@Dumindu-Kanchana can you please create a doc issur since this features includes a doc impact?

**Comment by malithie** [comment]
Resolving as this is fixed
