### ISSUE TITLE
Change pool size - To avoid slowness in production environments

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#4558]
Made changes to the following Docs:

[(https://docs.wso2.com/display/IS520/Enabling+Authentication+Session+Persistence)]
[(https://docs.wso2.com/display/IS530/Token+Persistence)]
[(https://docs.wso2.com/display/IS540/Token+Persistence)]
[(https://docs.wso2.com/display/IS550/Token+Persistence)]
[(https://docs.wso2.com/display/IS560/Token+Persistence)]
[(https://docs.wso2.com/display/IS570/Token+Persistence)]

**Comment by sherenewso2** [comment]
Closing this issue as the changes are already made.
