### ISSUE TITLE
Add warning- valid special characters in the service provider name

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#4559]
We have restricted special characters in the SP name. After this fix we are allowing only ". - _ and space". This restriction is there is SOAP service and DCR Rest service as well.

Hence added a warning in the following docs:
[(https://docs.wso2.com/display/IS570/Adding+and+Configuring+a+Service+Provider)]
[(https://docs.wso2.com/display/IS560/Adding+and+Configuring+a+Service+Provider)]
[(https://docs.wso2.com/display/IS550/Adding+and+Configuring+a+Service+Provider)]
[(https://docs.wso2.com/display/IS540/Adding+and+Configuring+a+Service+Provider)]
[(https://docs.wso2.com/display/IS530/Adding+and+Configuring+a+Service+Provider)]

[(https://docs.wso2.com/display/IS570/Using+the+Service+Provider+API)]
[(https://docs.wso2.com/display/IS560/Using+the+Service+Provider+API)]
[(https://docs.wso2.com/display/IS550/Using+the+Service+Provider+API)]
[(https://docs.wso2.com/display/IS540/Using+the+Service+Provider+API)]
[(https://docs.wso2.com/display/IS530/Using+the+Service+Provider+API)]

**Comment by sherenewso2** [comment]
Closing this issues since the changes have been made already.
