### ISSUE TITLE
Change OIDC CustomClaimsCallbackHandler API to prevent using objects from third party jars

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#4562]
In CustomClaimsCallbackHandler [1] , the API is implemented to take in a third party jar object as argument and also return an object from this third library. This is incorrect and we need to fix this API layer properly in the master as it can cause API changes when updating the third party library version. 

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/CustomClaimsCallbackHandler.java#L29

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
