### ISSUE TITLE
Product scenario manage user and roles -SCIM, test script issues

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4565]
Found below issues in product scenario test scripts.

Affected: Product scenario test scripts
Severity: High
Priority : Major
Component : Manage user and roles -SCIM
Type: improvement

Test Script | Test method | Solution
-- | -- | --
Scenario : Scenario 01 |   |  
**Issue:case Ids are not available** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testCreateGroupWithoutPermission | Add test case ID 1.1.1.3
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testCreateExistingGroup | Add test case ID 1.1.1.4
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testDeleteGroup | Add test case ID 1.1.1.5
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesWithUsersSCIM2TestCase.java | testProvisionUser | Add test case ID 1.1.1.1
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RenameExistingRoleToNameOfAnExistingRoleSCIM2TestCase.java | testCreateGroups | Add test case ID 1.1.1.20
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RoleNamingViolationSCIM2TestCase.java | testCreateGroupWithLessThanMinCharacters | Add test case ID 1.1.1.15
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/UpdateRoleSCIM2TestCase.java | testCreatePrimaryGroup |  
**Issue: Invalid test case IDs** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/scenarios/test/scim2/AnonymousProvisioningTestCase.java | selfRegister | Update test case Id to 1.2.1.15
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/scenarios/test/sProvisionEmailUserSCIM2TestCase.java | testSCIM2CreateUser | Update test case Id to 1.2.1.14
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/scenarios/test/ProvisionExistingUserTestCase.java | testSCIM2CreateExistingUser | Update test case Id to 1.2.1.4
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/scenarios/test/ProvisionUserSCIM2EnterpriseUserRequestTestCase.java | testSCIM2CreateEnterpriseUserRequest | Update test case Id to 1.2.1.12
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserSCIM2FullRequestTestCase.java | testSCIM2CreateUserWithFullRequest | Update test case Id to 1.2.1.11
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserSCIM2TestCase.java | testSCIM2ProvisionUser | Update test case Id to 1.2.1.1
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserWithAllAttributesTestCase.java | testSCIM2CreateUserWithAllAttributes | Update test case Id to 1.2.1.7
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserWithMalformedRequestTestCase.java | testMalformedSCIMUserCreate | Update test case Id to 1.2.1.2
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserWithoutAuthHeaderTestCase.java | testSCIMUserWithoutAuthHeader | Update test case Id to 1.2.1.5
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserWithoutContentHeaderTestCase.java | testSCIMUserWithoutContentHeader | Update test case Id to 1.2.1.6
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserWithValidationFailuresTestCase.java | testInvalidSCIMUserCreate | Update test case Id to 1.2.1.3
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/UpdateProvisionedUserSCIM2TestCase.java | testUpdateUser | Update test case Id to 1.2.1.18
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/UserProvisionSCIMWithDifferentContentTypeTestCase.java | testWrongContentType | Update test case Id to 1.2.1.10
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/UserProvisionWithInsufficientPrivilegesSCIM2TestCase.java | testSCIMCreateSecondUser | Update test case Id to  1.2.1.17/1.2.1.20
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.2-manage-users-with-scim1/src/test/java/org/wso2/identity/scenarios/test/scim/UserProvisionSCIMTestCase.java | testSCIMCreateUser | Update test case Id to 1.2.2.7
**Issue: Unnecessary @TEST methods for validation and steps** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testGetGroup | Add this test method under test case 1.1.1.3
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testGetDeletedGroup | Add this test method under test case 1.1.1.5
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testReCreateGroup | Add this test method under test case 1.1.1.5
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testDeleteReCreatedGroup | Add this test method under test case 1.1.1.3
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesWithUsersSCIM2TestCase.java | testCreateGroupWithMembers | Add this test method under test case 1.1.1.1
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesWithUsersSCIM2TestCase.java | testDeleteUser | Add this test method under test case 1.1.1.1
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesWithUsersSCIM2TestCase.java | testDeleteCreatedGroup | Add this test method under test case 1.1.1.1
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RenameExistingRoleToNameOfAnExistingRoleSCIM2TestCase.java | testGetGroups | Add this test method under test case 1.1.1.20
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RenameExistingRoleToNameOfAnExistingRoleSCIM2TestCase.java | testReNameExistingGroupToAnExistingGroup | Add this test method under test case 1.1.1.20
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RenameExistingRoleToNameOfAnExistingRoleSCIM2TestCase.java | testDeleteGroups | Add this test method under test case 1.1.1.20
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/UpdateRoleSCIM2TestCase.java | testUpdatePrimaryGroup | Add this test method under test case 1.1.1.19
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/UpdateRoleSCIM2TestCase.java | testDeletePrimaryGroup | Add this test method under test case 1.1.1.19
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserSCIM2TestCase.java | testSCIM2GetUser | Add this test method under test case 1.2.1.1
product-is/product-scenarios/1-manage-users-and-roles/1.2-admin-user-manage-user-accounts/1.2.1-manage-users-with-scim2/src/test/java/org/wso2/identity/ProvisionUserSCIM2TestCase.java | testSCIM2DeleteUser | Add this test method under test case 1.2.1.1
**Issue: Missing verification** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesSCIM2TestCase.java | testCreateExistingGroup | 1. Verify group has created,To verify can use the group ID2. Verify that role should not duplicate.
**Issue: Missing test steps** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/ManageRolesWithUsersSCIM2TestCase.java | testProvisionUser | Add update user steps
**Issue: Missing test data combinations** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RoleNamingViolationSCIM2TestCase.java | testCreateGroupWithSpecialCharacters | upadte test with more special characters (can use DD approach)
**Issue: Resource clear not available** |   |  
product-is/product-scenarios/1-manage-users-and-roles/1.1-admin-user-manage-roles/1.1.1-manage-roles-with-scim2/src/test/java/org.wso2.identity.scenarios.test.scim2/RoleNamingViolationSCIM2TestCase.java |   | Add after class with resource clear

Other than the above issues automated tests which are relevant to below test case IDs where the PR is still in review status also need to be improved as per to the comments column in the shared scenario test spread sheet. 

- 1.1.2.1
- 1.1.2.3
- 1.1.2.6
- 1.1.2.7
- 1.1.2.10
- 1.1.2.15
- 1.1.2.16
- 1.1.2.18
- 1.1.2.19
- 1.1.2.20
- 1.1.2.23
- 1.1.2.26
- 1.1.2.27

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
