### ISSUE TITLE
Support service provider template

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4566]
Refer the mail thread "[Architecture] [IAM] Service Provider Template Support"

**Comment by nilasini** [comment]
Fixed with 
https://github.com/wso2/carbon-identity-framework/pull/1814
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/936

**Comment by nilasini** [comment]
Reverted the feature with \[1] since the feature is not production ready.

\[1] https://github.com/wso2/carbon-identity-framework/pull/2091

**Comment by malithie** [comment]
Re-opened as the feature is not still completed

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
