### ISSUE TITLE
Print a stack trace for an unsuccessful login request.

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#4571]
**Description:**
When a wrong username or password provided (authentication failure), it will print a stack trace.

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
WSO2IS-5.7.0

**Steps to reproduce:**

- Configure STS token service as in our documentation [1]. 
- Use the STS client and test the service as highlighted in our documentation [2].
- Assign an invalid password to ut.password property or create a user without admin privileges and use them in **ut.username** and **ut.password**  properties.

[1] https://docs.wso2.com/display/IS570/Configuring+WS-Trust+Security+Token+Service 
[2] https://docs.wso2.com/display/IS570/Running+an+STS+Client

**Comment by malithie** [comment]
Reopening due to dependency on https://github.com/wso2/product-is/issues/4927
