### ISSUE TITLE
Upgrade maven-surefire-plugin to the latest version

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4575]
At the moment we use 2.18.1 - and the latest version is 2.22.1 with some bug fixes: https://blogs.apache.org/maven/entry/apache-maven-surefire-plugin-version1

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
