### ISSUE TITLE
Size of the IS 5.8.0 M25 pack has increased  

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#4580]
The size of IS 5.8.0 M25 has increased to 680 MB where size of the IS 5.7.0 is 450 MB.

**Comment by malithie** [comment]
This has been fixed with below approach
- Removing duplicated bundles
- Removing jars duplicated in webapps that are available with the runtime. Can be improved further more with https://github.com/wso2/product-is/issues/5003
