### ISSUE TITLE
Handle i18n consistently in authenticationendpoint

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/product-is#4582]
This is a discrepancy between IS 5.30 and IS 5.4.1 version when it comes to i18n handling of authenticationendpoint. Fix must concentrate on front-porting changes from this PR [1]

[1] - https://github.com/wso2/carbon-identity-framework/pull/1306

**Comment by DMHP** [comment]
As this is already fixed in master branch closing the issue.
