### ISSUE TITLE
WSO2 Identity Server Migration Status

### ISSUE THREAD

**Issue by Ramya-Palaniswami** [wso2/product-is#4586]
What is the absolute way of knowing that the migration has been carried out successfully?

I'm upgrading WSO2IS from 5.3.0 to 5.7.0 following the Migration guide of each version. I'm checking the About page where the version is displayed and the new features released in order to confirm the migration is done.

A freshly downloaded 5.4.0 shows version in about page on running the product, whereas freshly downloaded 5.5.0 doesn't.

While upgrading from 5.3.0 to 5.4.0, the version was displayed in the about page and I proceeded with next version. After migrating to 5.5.0, the version is not getting displayed in the about page and I assume because a fresh download didn't show either.

Documentation doesn't provide any information on verifying the migration status once it has been run.

**Comment by DMHP** [comment]
@Ramya-Palaniswami 

> What is the absolute way of knowing that the migration has been carried out successfully?

If the migration client executed without throwing any errors that means the migration client executed successfully.

> A freshly downloaded 5.4.0 shows version in about page on running the product, whereas freshly downloaded 5.5.0 doesn't.

I have just checked this and the version is available in the home page.
![image](https://user-images.githubusercontent.com/12690906/54523752-49960000-4996-11e9-9592-505be3ff53e5.png)

> Documentation doesn't provide any information on verifying the migration status once it.

Without migrating from versions one by one we can migrate to 5.3.0-5.7.0 directly. Please refer the doc [1]

[1] https://docs.wso2.com/display/IS570/Upgrading+From+an+Older+Version+of+WSO2+IS

If you have further concerns on this please re-open the issue.
