### ISSUE TITLE
Remove HSM feature from product (Temporary)

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#4588]
### This feature should be removed from the release 5.7.1-GA and add it later. 

How to test if the feature was removed successfully. (This is straightforward) 

1. Make sure the CryptoService is enabled in the carbon.xml (By default this is enabled)
2. Make sure the default key store is configured (Can configure custom key store as well)
3. Check whether the internal data encryption-decryption works. (Service Provider)
4. Check whether the external data encryption-decryption and signing works. (SAML - Enc/Dec, Signing, OAuth - Enc ID Token, JWT, etc)

**Comment by malithie** [comment]
Resolved
