### ISSUE TITLE
Add HSM Feature to the Product

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#4589]
Please follow the steps give below to do this. No code changes will require. (Hopefully :grimacing:) 

1. Merge https://github.com/wso2/carbon-identity-framework/pull/2001 to master
2. Merge https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/992 to master
3. Revert https://github.com/wso2/product-is/pull/4593

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
