### ISSUE TITLE
Support OIDC front channel logout 

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4592]
Spec: https://openid.net/specs/openid-connect-frontchannel-1_0.html

Effort BE::15

**Comment by omindu** [comment]
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/985
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1001
https://github.com/wso2/product-is/pull/3937

**Comment by IsurangaPerera** [comment]
Front channel UI changes reverted with wso2/product-is#4647

**Comment by madurangasiriwardena** [comment]
merged https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1001 to the feature branch. We need to fix the comments and merge the feature branch to the master

**Comment by mefarazath** [comment]
Additional improvements required are tracked with https://github.com/wso2/product-is/issues/9118

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
