### ISSUE TITLE
[DOC] Session termination during user password reset and user deletion

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#4599]
**Supported versions: IS 5.2.0 and IS 5.7.0**

This is an important security consideration where when a user password gets reset or when a user gets deleted, all the existing active sessions of the user need to be invalidated in order to ensure the safety of the application. 

To enable this functionality, follow the below steps.

1. Configuration
Add the following configuration in the identity.xml file located at <IS_HOME>/repository/conf/identity folder under <SessionDataPersist> tag
```
<JDBCPersistenceManager>
.....
   <SessionDataPersist>
   .....
       <UserSessionMapping>
	    <Enable>true</Enable>
       </UserSessionMapping>
   </SessionDataPersist>
</JDBCPersistenceManager>
```

1. Create the 2 new tables in the database using the below queries,
```
CREATE TABLE IDN_AUTH_USER (
	USER_ID VARCHAR(255) NOT NULL, 
	USER_NAME VARCHAR(255) NOT NULL, 
	TENANT_ID INTEGER, 
	DOMAIN_NAME VARCHAR(255), 
	IDP_ID INTEGER, 
	PRIMARY KEY (USER_ID),
	CONSTRAINT USER_STORE_CONSTRAINT UNIQUE (USER_NAME, TENANT_ID, DOMAIN_NAME, IDP_ID));
```

```
CREATE TABLE IDN_AUTH_USER_SESSION_MAPPING (
	USER_ID VARCHAR(255) NOT NULL, 
	SESSION_ID VARCHAR(255) NOT NULL,
	CONSTRAINT USER_SESSION_STORE_CONSTRAINT UNIQUE (USER_ID, SESSION_ID));

CREATE INDEX IDX_USER_ID ON IDN_AUTH_USER_SESSION_MAPPING (USER_ID);

CREATE INDEX IDX_SESSION_ID ON IDN_AUTH_USER_SESSION_MAPPING (SESSION_ID);
```

**Comment by sherenewso2** [comment]
Documented in 5.2.0 [1] and 5.7.0 [2]. 

[1] https://docs.wso2.com/display/IS520/Session+Termination+for+Reset+or+Deleted+Users
[2] https://docs.wso2.com/display/IS570/Session+Termination+for+Reset+or+Deleted+Users
