### ISSUE TITLE
Remove temporary password generation extension class from management console UI

### ISSUE THREAD

**Issue by kasun-bandara** [wso2/product-is#4600]
Since the "org.wso2.carbon.user.mgt.common.DefaultPasswordGenerator" used as the default password generator when a user is created with ask password from user option, password generation endpoint can be configured from the management console (Resident Identity providers -> Account Management Policies -> User Onboarding -> Temporary password generation extension class )

In the event of a password policy has been defined, we can use a user operation event listener [1] to generate a password that matched to the policy defined where DefaultPasswordGenerator may fail to generate a matching password for ask password from user operation. Since the use operation event listener override the DefaultPasswordGenerator or any custom random password generator implementation, we should remove configuration to set "temporary password generation extension class" from the management console. 

[1] - Sample user operation event listener for generating a password (https://github.com/kasun-bandara/CustomUserOperationEventListener)

**Comment by hauntingEcho** [comment]
to further drive the discussion, per my understanding of PIECESTECHSUB-62 the option is no longer functional/supported anyway.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
