### ISSUE TITLE
Maintain Account Lock Reason in the claim for Identity Management Rest APIs

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#4602]
A user can be locked due to different reasons like
1. Admin initiated account lock
2. Exceed maximum attempts and lock the account.

We need to validate all the possible reasons for an account lock and add the exact reason to the claim.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
