### ISSUE TITLE
Validating JWT using JWKS end point not working 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#4614]
Steps to reproduce 
 You need to have two IS Packs
port shift them and run them in ports 9443 and 9444

9444- External IDP (IS2)
9443-Auth Server (IS1)
When Port shifting do the same change in the resident idp id in the relevent pack

In IS 1

Create an Identity Provider 

Identity Provider Name: https://localhost:9444/oauth2/token 
This is the token endpoint of the IS 2. Also in WSO2 IS this is the id of the resident IDP. 

Identity Providers JWKS EndPoint: https://localhost:9444/oauth2/jwks

This is the JWKS EndPoint of IS 2

Alias: https://localhost:9444/oauth2/token

Go to Service Providers and Create an SP

Name: SP1 

Go to OAuth/OIDC Configuration under Inbound Authentication Configuration 

Token Issuer: JWT

Enable Audience Restrictions and add this as an Audience
http://localhost:9443/oauth2/token

In IS 2

Create an SP 

Name: SP2

Go to inbound Authentication Configuration and then OAuth/OIDC Configuration 

Enable Audience Restriction 

Add these as the Audiences: <Client ID of SP in IS1> 
				<ID of resident IDP in IS1>
Token Issuer:Default

Curl Requests 

For getting a ID token from IS 2

curl -X POST \
  https://localhost:9444/oauth2/token \
  -H 'Authorization: Basic  <Base64 Encoded Client ID:Client Secret  >' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type=password&username=admin&password=admin&scope=openid&undefined='

Response 

{
    "access_token": "dd027c97-487d-373b-a62b-a12d00f3ad6f",
    "refresh_token": "a37f81a7-92d1-3f47-b152-2e9136a167e0",
    "scope": "openid",
    "id_token": "eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZmxqSDhRNXdvT3FUSm9mTDVaM1IwdyIsImF1ZCI6WyJmcDVMT3YyQkFjYmkxeWRxQmZnRWFZZlNQR01hIiwiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIl0sInN1YiI6ImFkbWluIiwibmJmIjoxNTUyMzc0NDE4LCJhenAiOiJmcDVMT3YyQkFjYmkxeWRxQmZnRWFZZlNQR01hIiwiYW1yIjpbInBhc3N3b3JkIl0sImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0NFwvb2F1dGgyXC90b2tlbiIsImV4cCI6MTU1MjM3ODAxOCwiaWF0IjoxNTUyMzc0NDE4fQ.EcI0bH2q3uYOBhkgFJ-ADGnC4A13pGpGlUdPft6LM1ZPTPrSqI22zsUdGJMvI-pEUpXhGaxWlDQiQ36Fj4N5yIPysagpJwaaClXrKXIMayG0eY-yo8-i6QkcBmXLcW8Lotd8d_tujn0rX93oKNCJNSIhW5fZAahzNiHpPTsJ9-SL5mmUqzB77_5kXs16g9Y-CmRnKxi8hB7eor0A7ZvfwDOlVjQXr4M_rkEI4BGNDQNXrNCLkXD7BaZ88EV4G-ru9koQmF15gnYEjvr5nU_BZsrY7en6bpu8oloQ-iELvfKS3FVQZmasx0FZ2mVWq79UZwbDRpO6adG1X975yowM8g",
    "token_type": "Bearer",
    "expires_in": 1333
}

For exchanging the id token for an access token 

curl -X POST \
  https://localhost:9443/oauth2/token \
  -H 'Authorization: Basic <Base64 Encoded Client ID:Client Secret  >' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'cache-control: no-cache' \
  -d 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=<JWT Token ID>&scope=openid&undefined='

Response

{
    "error_description": "Signature validation failed for the provided JWT.",
    "error": "invalid_grant"
}

When Debugging found out that the exception is thrown at retrieveResource function in DefaultResourceRetriver

**Comment by Buddhimah** [comment]
This same error occurs at the same class same function when using jwks endpoint for service provider [#4094](https://github.com/wso2/product-is/issues/4094)

**Comment by Buddhimah** [comment]
The issue is not reproduced when trusted JWKS endpoint is used. This was tested when fixing the Issue wso2/product-is#4663.

**Comment by malithie** [comment]
Resolving as per comment above
