### ISSUE TITLE
One of the Resource Paths is not working on IS docs

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-is#4615]
Under the title **"To test the HTTP GET method (API resource list)"** in "[Using REST APIs via XACML to Manage Entitlement](https://docs.wso2.com/display/IS570/Using+REST+APIs+via+XACML+to+Manage+Entitlement)" docs, resource path is not working.

Current resource path : https://localhost:9443/api/identity/entitlement/decision/pdp
Correct one should be : https://localhost:9443/api/identity/entitlement/decision/home

**Comment by sherenewso2** [comment]
Fixed in versions 5.6.0 - 5.8.0 [1] 
[1] https://docs.wso2.com/display/IS580/Using+REST+APIs+via+XACML+to+Manage+Entitlement
