### ISSUE TITLE
The SAML SSO URL in the resident IDP should be editable

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [wso2/product-is#4616]
The **SAML SSO URL** in the resident IDP per tenant should be editable so that a user can replace the default **SAML SSO URL** with a custom url (ex: **https:// idp.abc.com/samlsso**) and get it returned from the **/saml2/metadata** endpoint of the particular tenant.
![1](https://user-images.githubusercontent.com/16388948/54259354-778cd600-458b-11e9-9efc-a4acd24fc055.png)

**Comment by thanujalk** [comment]
In the IS 5.8.0 pack, if you change the hostname it will be reflected here.

**Comment by inthirakumaaran** [comment]
Even in IS 5.7.0, you can edit the SSO URL in resident IDP via identity.xml but I think the correct requirement is to have this URL editable via the management console.
