### ISSUE TITLE
Show a specific error code or exception in the UI layer

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#4622]
#### Description
When a user login to the management console is failed due to account locking, invalid username/password, authorized user, the same error message is displayed in the UI. That is,
`Login failed! Please recheck the username and password and try again.`
It would be better if the displayed message could contain a specific error code or exception. Because in scenarios such as locked account, user does not have a way to identify that his/her account is locked.

#### Suggested Labels:
Improvement

#### Steps to reproduce

Unauthorized user login
1. Start an identity server and login to management console with admin user.
1. Create a new user.
1. Logout from the admin user
1. Try to log with the newly created user.

Locked User.
1. Enable account locking in IS server.
1. Start server and login to management console with admin user.
1. Create a new user and give login permissions
1. Logout from admin user
1. Try to log with the newly created user with incorrect password.
1. After the allowed number of failed attempts, the account will be locked.
1. Then if the tried to login with the correct credentials, the same error message is shown.

**Comment by IsuraD** [comment]
Need to add the following config in carbon.xml file to enable this feature.

`<EnableLoginFailureReason>true</EnableLoginFailureReason>`
