### ISSUE TITLE
Add support for overriding IdP Entity ID per SAML Service Provider in WSO2 IS

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#4623]
**The following tasks are completed :**

- Implement support for overriding the IdP Entity ID of resident IdP by an Alias specified in SAML SSO inbound configuration of Service Providers.
- Implement support for registering multiple SAML Service Providers with the same SAML ‘issuer’ by using an extra qualifier to identify correct SP.
- Implement support for validating SAML assertions with overridden IdP Entity ID values in SAML2 Bearer Grant Profile for OAuth.
- Implement unit tests for the implementations.
- Prepare documentation on the new features added to WSO2 IS.

**Pending task:** 

- Implementing integration tests to test SAML SSO flow with entity id overriding enabled.

**Following are the links of the prepared documents :**
 - Configuring SAML SSO (Introducing new attributes - Issuer Qualifier and IdP Entity ID Alias) - https://docs.google.com/document/d/1m67T85r42qeTsJuzQtgUZmqM_7xpbDMeQn7hpr3FGis/edit?usp=sharing
- Federating Multiple Office 365 Domains with WSO2 IS using SAML 2.0 - https://docs.google.com/document/d/1vxLF9o3qJpujOg92GjxyYT2EREfWKJFkE4Z0bik3g5Q/edit?usp=sharing
- Overriding IdP Entity ID per SAML SP - https://docs.google.com/document/d/1V5dD-50AqrSLrp4S_4Cad-Y8_mi89Hkxsa0UYj2JVRI/edit?usp=sharing

**Following are the PRs :**
- https://github.com/wso2/carbon-identity-framework/pull/1999
- https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/201
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/994

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
