### ISSUE TITLE
It is possible to add a regex as a ACS URL from the carbon management console

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4624]
A regex can be added as an ACS URL in the SAML2 Web SSO Configuration even though checking the regex pattern is not internally implemented. The UI validations need to be changed to properly validate this input case.

Steps to reproduce;
In the SAML2 Web SSO Configuration add the following as an ACS URL and it will be accepted.

`regexp=(https://myapp.com/callback|https://testapp:8000/callback)`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
