### ISSUE TITLE
Custom proxy context path is missing from some "/shindig" URLs and /portal/csrf.js in Dashboard

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#4627]
When a custom proxy context path is added in the carbon.xml or site.json, IS Dashboard fails because of  the following issue when gadgets are updated. 

The below error observed when account-recovery gadget is updated:

potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/portal/gadgets/account-recovery/controllers/account_recovery/edit_finish.jag, error:request token does not match session token

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
