### ISSUE TITLE
IS-5.8.0 Start up time should be reduced

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4630]
Currently, IS-5.8.0 startup time is greater than 1 minute. Ideally, we should keep the startup time less than 1 minute.

**Comment by thanujalk** [comment]
In windows, it takes a longer time than usual.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
