### ISSUE TITLE
Improvement for support intermediate certificate validation

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4632]
In a certificate-based request, if the incoming certificate is issued by an intermediate certificate then the intermediate certificates CN should be added to a config where it will be read and matched with incoming certificate' issuer CN.

It should be able to specify multiple intermediate certificates for different context paths in the config and also specify any context path that can be exempted from the intermediate certificate validation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
