### ISSUE TITLE
[Doc] support intermediate certificate validation

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4633]
In \[1] we have mention the following detail.

You could configure the following configuration in your identity.xml file if you want to use intermedia certificate validation then the value in the CN would be taked as the username otherwise the username will be taken from the header.
```
<IntermediateCertValidation enable="true">
     <IntermediateCerts>
         <CertCN>wso2isintcert</CertCN>
         <CertCN>localhost</CertCN>
     </IntermediateCerts>
     <ExemptContext>
         <Context>scim2</Context>
     </ExemptContext>
 </IntermediateCertValidation>
```

\[1] https://docs.wso2.com/display/IS580/Authenticating+and+Authorizing+REST+APIs

**Comment by sherenewso2** [comment]
Details are added to [1] 
[1] https://docs.wso2.com/display/IS580/Authenticating+and+Authorizing+REST+APIs
