### ISSUE TITLE
[DOC] Improvement on curl examples with single quotes. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4643]
Suggested labels: 
Affected : 5.8-m25
Severity: Major
Priority: Normal
Component: SCIM2
Type: Docs/Improvement/QATesting

Windows command prompt not support to the single quote but support to the double quote. Better documents [1] [2] provide the curl example with double quote since double quote support both ubuntu terminal and windows cmd. 

Ex: 
curl -v -k --user admin:admin --data **'**{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}**'** --header "Content-Type:application/json" https://localhost:9443/scim2/Users

[1]https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#GroupsEndpoint#createGroup

[2] https://docs.wso2.com/display/ISCONNECTORS/Configuring+SCIM+2.0+Provisioning+Connector#ConfiguringSCIM2.0ProvisioningConnector

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
