### ISSUE TITLE
Re-captcha for login works only when account locking is enabled for login

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4644]
Noted that re-captcha for login works only when account locking is enabled in login policies.
IMO, enabling re-captcha for login flow should be independent from account locking policies. The only consideration there should be that the no of failed login attempts for re-captcha should be less than the no of failed login attempts for account locking.
Shouldn't this be the case. WDYT?

**Comment by murathazer** [comment]
@malithie re-captcha for login does not work even if account locking is enabled in login policies (we use 5.9.0)
I think we encounter this issue `https://github.com/wso2/product-is/issues/7457`, is there any workaraound that you know?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
