### ISSUE TITLE
[Doc] No API document is available for SCIM2 for IS 5.8.0

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4649]
Suggested Labels
Affected : 5.8.0- m27
Severity: Major
Priority: High
Component: SCIM2
Type: Doc , Type:Improvement , Type: QA-Testing

SCIM2 API doc is available for IS 5.7.0 but still not available for IS 5.8.0. Please add a doc for IS 5.8.0 [1].

[1]. https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/index.html#guide

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
