### ISSUE TITLE
Domain name is getting appended for the display name in the create group response in SCIM2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4651]
**Suggested Labels**
Affected : 5.8.0- m27
Severity: Major
Priority: High
Component: SCIM2
Type:Improvement , Type: QA-Testing

**Environment**
IS 5.8.0-m27 pack 

**Actual Behavior**
When creating a group providing a display name (eg:- manager) using SCIM2 endpoint, in the response retrieved display name will be shown as PRIMARY/manager appending the domain name. If I give PRIMARY/manager as the display name when creating the group in the response will get manager as the display name.

**Expected Behavior**
In the response display name should be shown without appending the domain name.

[1]. https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/index.html#!/operations#GroupsEndpoint#createGroup

**Comment by DMHP** [comment]
related https://github.com/wso2/product-is/issues/4175

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
