### ISSUE TITLE
Snake case properties in swagger definition is converted to camel case when generating stubs

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4664]
When generating stubs from swagger definition using [swagger2cxf-maven-plugin](https://github.com/hevayo/swagger2cxf-maven-plugin) camel case properties are converted to camel case properties. Because of this issue, the stub code has to be modified manually.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
