### ISSUE TITLE
Invalid Response is given when trying to add a Group with mix of special characters using SCIM2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4668]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: High
Component: SCIM2
Type:Improvement , Type: QA-Testing, Type-Bug

**Environment**
IS 5.8.0-m27
2 node cluster against Mysql 5.7
Ubuntu 16.04

**Steps to reproduce.**
1. Enable JDBC userstore in usr-mgt.xml
2. Set Enable SCIM to true
2. Try to create a group with SCIM2 using special characters

sample request
`curl -v -k --user admin:admin --data '{"displayName":"myrole@#$*!^,./]{a"}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Groups
`
Sample response received

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Cannot create group through scim to user store . SCIM is not enabled for user store MYROLE@#$*!^,.","status":"500"}`

Even though the error is due to not matching the role name regex allowed by the user store with the input value for the role name, in the response we get a invalid error message as SCIM is not enabled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
