### ISSUE TITLE
SSO user login fails

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#4670]
If the user is logged using google social site login option, SSO is not working:

1. Start login into Application 1 using oauth2 auth code grant type.
2. During login, select the option to log in with Google
3. WSO2 gets user redirected to google, complete login with google creds.
4. Login success, WSO2 redirects to Application 1.
5.Using the same browser window (same cookies) login into Application 2 (IOL) using oauth2 auth code grant type and same WSO2 endpoint. that is pointed to the same WSO2 URL (hostname, so cookies match for domain)
6. WSO2 login fails without asking for password, shows login error.

<Expected>  - User should get through WSO2 authentication without any prompts or errors since user's session with WSO2 is still valid and user already been authenticated.

The issue is with:- wso2is-5.3.0+1544787851827.full

**Comment by nilasini** [comment]
This is expected behavior in the latest IS releases hence closing the issue.
