### ISSUE TITLE
JWT Bearer Grant is using the IDP name for issuer validation

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#4672]
In the current implementation of JWT Bearer Grant, we are comparing the JWT issuer against the Identity Provider Name. Instead this should be a property configured in the OIDC configuration section since Issuer field is specific to OIDC protocol.

**Comment by darshanasbg** [comment]
This new property should be unique across idps in a tenant. Have to validate\maintain that uniqueness when adding\updating this property.

**Comment by janakamarasena** [comment]
Keeping issue open till document changes are completed.
