### ISSUE TITLE
Does not allow to delete a created group when '+' special character is used in creating the Group using SCIM2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4673]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: Highest
Component: SCIM2
Type-Bug, Type: QA-Testing, 

**Environment**
IS 5.8.0-m27
2 node cluster against Mysql 5.7
Ubuntu 16.04

**Steps to reproduce.**

1. Enable JDBC userstore in usr-mgt.xml
2. Set Enable SCIM to true
3. Create a group by including the special character + in the group name. Will allow to add the group successfully and can view the created group without any issue through the management console. Sample Request

`curl -v -k --user admin:admin --data '{"displayName":"managerrrr+"}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Groups`

4. Login to the management console and try to delete the created group in step 3. Will not allow to delete the group. Will prompt a error message as attached in [1]

`Could not delete role managerrrr . Error: 31806 - Cannot delete non-existing role`

[1]. error-message.png

![is580error2](https://user-images.githubusercontent.com/31848014/54606385-b92ced80-4a71-11e9-851a-f1127a157e54.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
