### ISSUE TITLE
[Doc] Review the OIDC-based SSO tutorial

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#4677]
**Description**
Review the [06-Tutorial-Single Sign On (SSO) - OIDC](https://docs.google.com/document/d/1G-P-sVoSUlHJg7xYv2sqk4G82gUUfcclJDt9JwUPsTQ/edit#).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
