### ISSUE TITLE
Querying `getRoleListOfUser(userName)` for each application for the same user

### ISSUE THREAD

**Issue by kasunsiyambalapitiya** [wso2/product-is#4678]
**Description:**
When loading the Service Provider page for the logged in user from Management console, the following method [isUserAuthorized](https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java#L95) is executed for each application which in turn queries the UserStore with the following method [getRoleListOfUser(username)](https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java#L131) of the relevant userstore for getting roles list of the logged in user in order to match with the **_applicationRoleName_**. Here the above call is redundant as it will always return the same role list of the logged in user for each application. 

The above flow can be optimized such that **userStoreManager.getRoleListOfUser(username);** is called to get roles list of the logged in user first and then validate the above-obtained roles with each **_applicationRoleName_**

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
**wso2is-5.7.0**
**OS, DB, other environment details and versions:**    
Any

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
