### ISSUE TITLE
Cannot login to a tenant when a userstore config has an invalid UserStoreManager class

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4682]
Cannot login to a tenant when a userstore config has an invalid UserStoreManager class.

The error can only be seen in the terminal when user.core DEBUG logs are enabled.

Steps to reproduce;

1. Enable user.core debug logs. (As the error is only displayed when debug logs are enabled)
2. Create a tenant.
3. Login to the tenant and add a new userstore.
4. Shutdown the server.
5. Open the relevant userstore config xml file and change the UserStoreManager class to non-existant class. (ex: org.wso2.carbon.user.core.jdbc.JDBCUserStoreManagerNew)
6. Start the server and try to login to the tenant.

Cannot login and the stacktrace is shown in the terminal. With a error realated to the following

> [2019-03-21 10:49:31,864] DEBUG {org.wso2.carbon.user.core.common.DefaultRealmService} -  Error occurred while getting tenant user realm for tenant id : 1
org.wso2.carbon.user.core.UserStoreException: Error while building user store manager from file

- Also from the super tenant if you try to edit the created tenant you will see a error page related to the same error.

- If you follow the same steps for the super tenant in the server startup you can see the same error but it does not affect any flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
