### ISSUE TITLE
[DOC] Explain the parameter changes not recomended situtaion 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4686]
**Suggested labels:**
Affected: 5.8-m27
Severity: Minor
Priority: Medium
Component:User Mgt
Type: Improvement/QATesting

JDBC user store configuration include different configuration through parameter changes in  the xml file. [1]. There parameter,  'CaseInsensitiveUsername' status change not recommended if the system already have multiple users who have same user Ids but user IDs change form the case. [2]. Better to mentioned these information as well in the documents under particular parameter.  

[1]https://docs.wso2.com/display/IS580/Configuring+a+JDBC+User+Store
[2] https://github.com/wso2/product-is/issues/4655

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
