### ISSUE TITLE
[Docs] Mutual SSL doc is missing some information

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-is#4687]
I've tried ["Using REST APIs via XACML to Manage Entitlement"](https://docs.wso2.com/display/IS570/Using+REST+APIs+via+XACML+to+Manage+Entitlement) tutorial and I wanted to have mutual SSL instead of Basic Auth. To configure Mutual SSL, I've followed ["Enabling Mutual SSL"](https://docs.wso2.com/display/IS570/Enabling+Mutual+SSL) doc. I have found out that, `WSO2-Identity-User` header should be sent in order to do this, but this part is not there in the doc.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
