### ISSUE TITLE
Updating a Group throgh SCIM2 gives a unmatching action log in the carbon console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4688]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: High
Component: SCIM2
Type-Bug, Type: QA-Testing,

**Environment**
IS 5.8.0-m27
2 node cluster against Mysql 5.7
Ubuntu 16.04

**Steps to reproduce.**

1. Enable JDBC userstore in usr-mgt.xml
2. Set Enable SCIM to true
3. Create  a group using SCIM2 providing the display name as manager 
Sample Request
`curl -v -k --user admin:admin --data '{"displayName":"manager"}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Groups`

4. Update the group to display name worker using a PUT request
Sample Request
`curl -v -k --user admin:admin -X PUT -d '{"displayName":"worker"}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Groups/6a6a3341-052b-45d2-8701-eb39b8c28816
`

Actual Behavior
In the carbon console following log will be displayed
`TID: [-1234] [] [2019-03-21 09:59:13,031]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  Group: PRIMARY/worker is updated through SCIM. 
`
But its not the worker role that got updated its the original role manager that got updated as worker. Therefore the log that gets printed in the carbon console does not match with the actual action happened.

**Comment by ShanikaWickramasinghe** [comment]
@malithie 
Verified this issue against a IS 5.8.0 alpha 5 fresh pack with LDAP default userstore and issue is still getting reproduced 

[2019-04-09 14:15:16,084]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  Group: PRIMARY/manager is created through SCIM.
[2019-04-09 14:16:43,637]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  Group: PRIMARY/worker is updated through SCIM.

**Comment by IsurangaPerera** [comment]
Changes were merged into scim2 inbound provisioning connector version 1.2.25  and change not included in IS 5.8.0 alpha 5 (scim2 inbound provisioning connector version 1.2.22).

**Comment by malithie** [comment]
Changed the milestone accordingly
