### ISSUE TITLE
Passwords with trailing spaces are trimmed silently causing authentication failures

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#4689]
Problem:
We support configuring password regexes per-user store. Therefore it is perfectly valid for a user to have a password with trailing whitespaces given that the regex configured allows it.

But we noticed that in our Carbon UI and at user store level we trim trailing whitespaces silently. Therefore any user whose has a password with trailing whitespaces will have problems with login to the management console and SSO logins.

Users who are created via IS do not have the issue since during account creation password will anyways be trimmed. This too is a problem. Let's say if the user wants to create a password "password#123 ", the actual password that gets stored in the user store is "password#123". The user will not have a problem as long as he logs in via IS. If he uses the same account for any other purpose outside IS, he will have an issue in login. The user will type in "password#123 " but the actual password at the user store in "password#123"

Steps to reproduce,
1. Create a user having a password with spaces at the end (eg: "password123 ") directly on the user store. Let's say an AD
2. Configure AD as the secondary user store.
3. Modify the password regex to allow spaces in the password (in the user store)
4. Try to login to the management console with the user, it will fail
5. Try an SSO login (login to user portal), it will fail.

Trimming of the password in carbon console happens at [1] and [2].
Trimming at the user store level happens at [3] when preparing the password for authentication.

[1] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.ui/src/main/resources/web/admin/login.jsp#L69
[2] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.ui/src/main/resources/web/admin/js/main.js#L1660
[3] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.utils/src/main/java/org/wso2/carbon/utils/Secret.java#L156

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/2004

**Comment by malithie** [comment]
Reopening to be closed with https://github.com/wso2/product-is/issues/4894
