### ISSUE TITLE
SCIM 2 property names are inconsistent

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#4692]
There are few inconsistencies in charon-config.xml related to word separation.
Some keys use camel case (eg. "documentationUri"), some keys use '-' (eg. "patch-supported") and some use both (eg. "bulk-maxOperations").

Need to have a consistent way to have the keys.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
