### ISSUE TITLE
[Doc] Include the request details related to bulk user deletion using SCIM2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4693]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: Normal
Component: SCIM2
Type-Bug, Type: QA-Testing

Bulk user deletion can be done by using the below request. Please include request details related to this in the api doc [1]
Sample Request
`curl -v -k --user admin:admin --data '{"failOnErrors":2,"schemas":["urn:scim:schemas:core:1.0"],"Operations":[{"path":"/Users/48cd8d06-9f63-4555-a38d-44e2c8cb7506","method":"DELETE"},{"path":"/Users/b4ee5df2-3bd6-4e20-b9d3-7ba1d5b6c1d2","method":"DELETE"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Bulk`

[1]. https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/index.html#!/operations#BulkEndpoint#createBulkUsers

**Comment by sherenewso2** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2148
