### ISSUE TITLE
SCIM SP resource manager capabilities are read by configuration

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#4695]
Consider,
 "bulk-supported";
 "sort-supported";
 "patch-supported";
 "etag-supported";
 "filter-supported";

These should have been provided at the code itself, instead of exposing as a configuration file.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
