### ISSUE TITLE
SPInitLogoutRequestProcessor custom implementation is ignored

### ISSUE THREAD

**Issue by markusglue** [wso2/product-is#470]
When adding <SPInitLogoutRequestProcessor>CustomClass</SPInitLogoutRequestProcessor> to "identity.xml" the custom class is stated to be loaded in the logs, but finally the original implementation is still used.

**Comment by dewniMW** [comment]
Fixed in https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/238
