### ISSUE TITLE
Inconsistency in SCIM2 outbound provisioning(Dumb mode)

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4702]
**Suggested Labels**

Affected: 5.8.0-alpha2
Severity: Major
Priority: High
Component: SCIM2/Outbound Provisioning
Type-Bug

**Steps to reproduce**

- [Configure outbound provisioning using SCIM](https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+SCIM)
- Enable dumb mode
- Start another IS instance running on a different port (SCIM inbound provisioning enabled)
- Use SCIM 2.0 rest API to create a new user/group

**Actual Behavior**

When using SCIM API to provision users/group it works fine (entity is not created in the local user store.). However, when using SCIM 2.0 rest API the entity is created in both user stores.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
