### ISSUE TITLE
Provisioning entity is persisted in dumb mode

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4703]
**Suggested Labels**

Affected: 5.8.0-alpha2
Severity: Major
Priority: High
Component: SCIM2/Outbound Provisioning
Type-Bug

**Steps to reproduce**

- [Configure outbound provisioning using SCIM](https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+SCIM)
- Enable dumb mode
- Start another IS instance running on a different port (SCIM inbound provisioning enabled)
- Use SCIM 1.1 rest API to create a new user
- Remove the created user from the second IS
- Send the same request again(user name should be identical)

**Actual Behavior**

The user is created at the user-store of the second IS. However, there is a **JdbcSQLException** thrown from the first IS. This is resulted by persisting provisioning entity locally even in dumb mode.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
