### ISSUE TITLE
Errors are concatenating in username recovery flow.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#4709]
1) Enable captcha verification with username recovery
2) Try invalid user with a correct captcha
3) Try again with incorrect captcha.

![image](https://user-images.githubusercontent.com/8455535/54864368-4aef7000-4d7c-11e9-8aaa-368cdd7f49be.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
