### ISSUE TITLE
JIT provisioning Prompt for username shows misleading text.

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#4710]
When JIT povisioning is enabled and  Prompt for username is enabled, after the user is authenticated the next page shows as,
![image](https://user-images.githubusercontent.com/11584828/54864342-05cb3e00-4d7c-11e9-8bf9-fa71e672a878.png)
Here,
**"If you do not specify a tenant domain, you will be registered under super tenant"** has to be removed, because in the user will be created in the applications' tenant. The user can't change the tenant

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
