### ISSUE TITLE
Once SP name is updated, unable to create a new SP with old name.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#4712]
Steps to reproduce.
1. Create an SP with name "sp-name-1"
2. Update SP name to "sp-name-2"
3. Try to create a new SP with name "sp-name-1"

Step#3 fails with error "Application registration failed. An application with name 'sp-name-1' already exists."

expected: 
When the SP name is updated, all the references for old SP should be deleted.

**Comment by senthalan** [comment]
This may be due to the newly added cache improvements.
