### ISSUE TITLE
Input fields validation has to be done in sign up page

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#4714]
The password min length validation is failing in the UserStor Manager level and returns 500 internal error. Proper validation has to be done in the UI or proper error code needs to send back from the server and it needs to be displayed correctly

Telephone and phone number on the sign-up page should be validated in the UI and service layer. Currently, there is no validation at all.  In the service layer, we will get everything as claims, so it will be hard to validate. But at least, we can easily have validation in the UI

This validation will resolve: https://github.com/wso2/product-is/issues/2942

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
