### ISSUE TITLE
Response handler related to OIDC hybrid flow are disabled by default

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4720]
Need to enable response type handlers that captures OIDC hybrid flow requests.
Those needs to be specifically enabled  right now [1].

[1] https://docs.wso2.com/display/IS570/OpenID+Connect+Hybrid+Flow

**Comment by mefarazath** [comment]
https://is.docs.wso2.com/en/next/learn/openid-connect-hybrid-flow/

**Comment by mefarazath** [comment]
Once we support this OOTB, we need to modify the docs to remove additional config steps that were previously required.
