### ISSUE TITLE
Invalid warning when updating JIT provision users with cloud service provider google

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4723]
**Suggested labels:**
Affected/5.8.0-Alpha2
Component/Identity Mgt
Severity/Critical

**Problem observed:**
Once attempt to update the IDP JIT provisioning users with cloud service provider google appear invalid  'Google connector Primary Email claim URI should be selected'. [1]

**Steps you executed**

1. Log in to management console
2. Navigate to the Main menu to access the Identity menu. Click Add under Identity Providers
3. Fill in the details in the Basic Information section
4. Navigate to the Outbound Provisioning Connectors and select Google Provisioning Configuration
5. Fill the fields with relevant data. Fill Primary Email, Given Name, Family Name fields also with valid values.
6. Register
7. Navigate to the identity provider list
8. Select the created IDP and Click edit
9. Update the JIT provisioning 
10. Click update

**Expected result:**
Update should be success with the Successful message

**Actual result:**
Warning message appeared. ' 'Google connector Primary Email claim URI should be selected'.' 

**The environment you used**
Ubuntu/DB2

[1] https://docs.wso2.com/display/IS580/Configuring+Outbound+Provisioning+Connectors+for+an+Identity+Provider#ConfiguringOutboundProvisioningConnectorsforanIdentityProvider-ConfiguringGoogleprovisioning

**Comment by dilin993** [comment]
This is due to the issue https://github.com/wso2/product-is/issues/4721
