### ISSUE TITLE
Endpoint validation fails with proxy port enabled, Nginx fronted deployments 

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4727]
During the SAML bearer grant flow, the audience from the incoming token request is validated against the token endpoint of the WSO2 IS server. With Nginx fronted proxy enabled deployment, this token endpoint is present with the proxy port. 

`Token Endpoint URL: | https://is.wso2.com:443/oauth2/token
`

For requests made without the proxy port added fails this validation.

Steps to reproduce:

- Proxy enabled deployment

- A token request with an audience URL without the proxy port, 443

In this deployment, resident IDP also conatains many other URL values with the proxy port. 

`
Authorization Endpoint URL:	https://is.wso2.com:443/oauth2/authorize,
Token Endpoint URL:	https://is.wso2.com:443/oauth2/token,
Token Revocation Endpoint URL:	https://is.wso2.com:443/oauth2/revoke,
Token Introspection Endpoint URL:	https://is.wso2.com:443/oauth2/introspect,
User Info Endpoint URL:	https://is.wso2.com:443/oauth2/userinfo,
Session IFrame Endpoint URL:	https://is.wso2.com:443/oidc/checksession,
Logout Endpoint URL:	https://is.wso2.com:443/oidc/logout,
Web finger Endpoint URL:	https://is.wso2.com:443/.well-known/webfinger,
Discovery Endpoint URL:	https://is.wso2.com:443/oauth2/oidcdiscovery,
Dynamic Client Registration Endpoint URL:	https://is.wso2.com:443/api/identity/oauth2/dcr/v1.1/register,
JWKS Endpoint URL:	https://is.wso2.com:443/oauth2/jwks
`

Need to analyze their effect to the existing flows in a proxy fronted scenaro.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
