### ISSUE TITLE
code is not returned in response with code token hybrid flow request on an active session 

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4728]
Environment:
DB: DB2
JDK: Java 8

Steps to reproduce.
1. Create an Oauth service provider in a tenant
2. Create a user in the same tenant
3. Initate a request with OIDC Hybrid flow for response type `code token`
`https://localhost:9443/oauth2/authorize?response_type=code token&client_id={client-id}&nonce=abcd&redirect_uri={redirect-uri}&scope=openid`
4. Login and note that the response includes both the access token and the code
5. In the same browser session hit the same request for OIDC Hybrid flow for response type `code token`
6. Note that only access token is received in the response and code is missing

The specification just says that both code and token should be present, but not is this specific case. Yet, seems to be a bug, and as the hybrid flow defines retrieving id token or access token from the token endpoint using the code returned

**Comment by nilasini** [comment]
Checked with 5.8.0-Alpha2 pack with DB2 in tenant mode, could able to get both access token and code when there is an active session hence closing the issue.
