### ISSUE TITLE
Warning logs can be seen when Google used as a federated authenticator

### ISSUE THREAD

**Issue by wijith7** [wso2/product-is#4730]
WARN {org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils} - Unable to filter redirect params for url.https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Fcommonauth&state=26991b3b-3969-47e3-9817-d8fd086551a1%2COIDC&client_id=192218414291-3mkko67vgt4cbmd62l5l4klcqhrd26f8.apps.googleusercontent.com&scope=openid email profile

Possible cause - There are spaces in the url, possible solution urlencode in scope.

https://github.com/wso2-extensions/identity-outbound-auth-oidc/blob/b58fca1682a380409c350566935ef8ee8f1bedad/components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java#L301

@ayshsandu

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
