### ISSUE TITLE
Claims are not retrieving through id token in tenant mode

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4731]
1) Create a tenant
2) Login to the created tenant
3) Create a SP with OIDC inbound protocol
4) Select country, email address as requested claims
5) get access token and id token
6) **id token will not have country**, email but if you invoke user info you could see the country and email

**Comment by DMHP** [comment]
@nilasini 
What is the grant type you tried to reproduce this issue? Please make sure whether you have email address and country updated in the user profile.

Following is the payload that I could obtain after following the exact same steps mentioned in the issue. I used authorization code grant type.

{
  "at_hash": "bV2Did_5wWDfqi5I27Y3bw",
  "sub": "admin",
  "country": "Sri Lanka",
  "amr": [
    "BasicAuthenticator"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "sid": "f075f00a-5346-4638-8b4b-c1bcf528a030",
  "aud": "s0ez4IcinPZi_3bSx2z88ZefkQsa",
  "c_hash": "N9n-bZManyRXNGiFODoVDg",
  "nbf": 1553837920,
  "azp": "s0ez4IcinPZi_3bSx2z88ZefkQsa",
  "exp": 1553841520,
  "iat": 1553837920,
  "email": "jonathan@wso2.com"
}

I am closing the issue. Please re-open if you have any other concerns.
