### ISSUE TITLE
Does not allow to upate the User Claim Department through users default profile

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4734]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: High
Component: UI
Type-Bug

**Environment**
DB Mysql 5.7
Userstore JDBC
Tomcat v7.0.64
2 node cluster fronted with nginx DB

Steps to Reproduce
Create a user and try to update the user claim value Department from the UI by updating the Users default profile. 

**Observation**
Does not allow to update the Department value

![dep](https://user-images.githubusercontent.com/31848014/54867832-fd3e2c00-4daa-11e9-8261-568f027c60fb.png)

**Comment by ShanikaWickramasinghe** [comment]
As this field is marked as a read only attribute by default it does not allow to edit the field. Any reasons to make only that field as a read only field by default.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
