### ISSUE TITLE
Adding, updating OIDC scopes from the UI does not update them properly

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4736]
Environment:
DB: DB2
JDK: Java 8

Steps to reproduce:
1. Create a tenant
2. Logged into the management console
3. Go to 'OIDC scopes'
4. Click 'update' button and tick a claim (nickname) listed there
5. Click 'Remove'. This removes from the list. 
6. Click 'Back' and try to update again. Note the claim is not there anymore. As per the UI if back is clicked without update it should not be removed. Because it has an update step to confirm
7. Perform 1 to 6 and click 'update'. This removes from the claim from the list.
8. Now try to add the claim (nickname) from the 'Add Claim' option. 
9. It does not get added to the list and not updated.

The UX on the view is not that friendly and there are multiple clicks involved unnecessarily.
Moreover, Add, Update seems to have some inconsistent behaviours

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
