### ISSUE TITLE
IdP/Office 365 adaptive authentication script needs to be removed

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4738]
IdP/Office 365 adaptive authentication script needs to be removed.

This is the template we have today.

// Office365-based from Template...

// This script will assign the below Office365 specific role to any user if not already assigned
var roleToBeAssigned = ['office365Role'];

function onLoginRequest(context) {
    executeStep(1, {
        onSuccess: function (context) {
            // Extracting authenticated subject from the first step
            var user = context.currentKnownSubject;
            // Checking if the user is already assigned to the given Office365 specific role
            var hasRole = hasAnyOfTheRoles(user, roleToBeAssigned);
            if (!hasRole) {
                Log.info('Assigning role: ' + roleToBeAssigned.toString() + ' for the user:' + user.username);
                assignUserRoles(user, roleToBeAssigned);
            }
        }
    });
}

It simply adds a role to the user - if user does not have that role in the login flow. Can we please make it a generic template under User, say Assign Roles?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
