### ISSUE TITLE
Users should be able to retry after denying consent in the login flow.

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4740]
At the moment, if the user denies consent, we present an error page:

AUTHENTICATION ATTEMPT FAILED.
Attention :
Authentication failed. User denied consent to share information with salesforce.

But - we should ideally take the user back to the consent page itself, with a a warning message, and give him/her the opportunity to change his decision if needed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
