### ISSUE TITLE
No consent asked for requested user attributes in the login flow (tested with SAML SP)

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4741]
1. Create an SP (SAML) - with no requested attributes
2. Login.
3. Update the SP and add Email as a requested attribute.
4. No consent prompted for the Email during the login flow.

**Comment by malithie** [comment]
@nilasini , This should be due to pre-consented requested claims. Can you confirm.

**Comment by nilasini** [comment]
@malithie Yes this issue is due to pre-consented requested claims. According to the implementation, this is expected behavior. 
Please refer \[1] for more details on this.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227

**Comment by nilasini** [comment]
This issue will be tracked with the doc issue \[1] hence closing the issue.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227
