### ISSUE TITLE
Consent page on OIDC and SAML flows are not consistent

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4742]
<img width="1038" alt="Screen Shot 2019-03-23 at 8 39 43 PM" src="https://user-images.githubusercontent.com/1422563/54874603-e4824600-4dab-11e9-931a-0f1956da7f83.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
