### ISSUE TITLE
OIDC flow consent screen shows with no requested claims (please see attached image)

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4743]
In the ODIC configuration, email is a requested claim.

![Screen Shot 2019-03-23 at 8 43 46 PM](https://user-images.githubusercontent.com/1422563/54874635-86099780-4dac-11e9-9b0f-189ed580c478.png)

**Comment by malithie** [comment]
@nilasini , This should be due to pre-consented requested claims. Can you confirm.

**Comment by nilasini** [comment]
@malithie Yes this issue is due to pre-consented requested claims. According to our current implementation, this is expected behavior.
Please refer [1] for more details on this.

[1] #2985 (comment)

**Comment by nilasini** [comment]
This issue will be tracked with the doc issue \[1] hence closing the issue.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227
