### ISSUE TITLE
How we handle denial of consent in login flow if consistent between SAML and OIDC

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4744]
How we handle denial of consent in login flow if consistent between SAML and OIDC.

1. In SAML flow error page.
2. In OIDC redirects back to the SP with an error message.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
