### ISSUE TITLE
Claims not received in user info for the access token, or in id token for the code returned via code token OIDC hybrid flow, when mandatory claims are configured

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4747]
**Environment:**
DB: DB2
JDK: Java 8

**Steps to reproduce:**

1. Create a tenant
2. Create a user in that tenant
3. Update first name -> http://wso2.org/claims/givenname, last name -> http://wso2.org/claims/lastname, email -> http://wso2.org/claims/emailaddress claims of that user
4. Create an oauth application
5. Configure claims section as below.
![image](https://user-images.githubusercontent.com/4951983/54875264-a3c51400-4e21-11e9-8931-39b9c7f844cc.png)
6. Make sure above claims are available for OIDC scopes as below.
given_name (mapped to http://wso2.org/claims/givenname) in openid scope
email (mapped to http://wso2.org/claims/lastname) only in email scope
family_name (mapped to http://wso2.org/claims/lastname) only in profile scope
gender (mapped to http://wso2.org/claims/gender)in openid scope
7. Initiate a request with OIDC Hybrid flow for response type code token only for openid scope
https://localhost:9443/oauth2/authorize?response_type=code id_token&client_id=xxx&nonce=asd&redirect_uri=http://localhost:8080/playground2/oauth2client&scope=openid
Flow will prompt for the value for mandatory claim gender
8. Invoke userinfo endpoint with the received access token. Note that it returns only sub and gender, not given-name as expected for the openid scope.
9. Now initiate a token request for the code received. It returns only sub and gender in id token. It should also return given-name
10. Perform step 7, 8 and 9 to openid email, openid email profile  scope and note non responds with claims in requested scopes

**Comment by malithie** [comment]
Same behavior is observant for response type **code id_token** with OIDC hybrid flow

**Comment by malithie** [comment]
Same behavior is observant for response type **code id_token token** with OIDC hybrid flow

**Comment by nilasini** [comment]
Please refer the comment \[1]

\[1] https://github.com/wso2/product-is/issues/4758#issuecomment-477501077
