### ISSUE TITLE
Certificate defined at the service provider level not used for the response encryption

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#4748]
Steps to reproduce:
(In any of tenant including super tenant)
1. Create a  service provider and upload service provider certificate at the service provider level.
2. Add a SAML2 service provider to it.
3. Enable signature validation and assertion encryption.
4. From the drop-down select different Certificate Alias value for the service provider

Result:
1. Signature verification is a success even though we select a different certificate alias from the drop-down
2. Assertion get encrypted from the certificate selected in the drop down

If the user wants to encrypt the SAML assertion using the same certificate at the service provider level, he needs to import it to the tenant keystore and select it from the drop-down.

This is behavior is ambiguous. Needs a redesign.

Environment: DB2, Mac OS

**Comment by malithie** [comment]
This needs to be verified for OIDC flows as well

**Comment by rpalmarin** [comment]
Hi,
same proble, this behavior is ambiguous, is not compliant with the documentation and this way it is mandatory the restart of the service.
Roberto

**Comment by rksk** [comment]
For the encryption we are getting the certificate from the keystore with the given alias at [1].
```
X509Credential cred = SAMLSSOUtil.getX509CredentialImplForTenant(domainName, alias);
```

But for signature validation, we use the cert came in the SAMLSSOServiceProviderDO.
```
SAMLSSOServiceProviderDO serviceProviderConfigs = SAMLSSOUtil.getServiceProviderConfig(issuerName,
                    tenantDomain);

boolean isSignatureValid = SAMLSSOUtil.isSignatureValid(authnReq, queryString, validationResponse
                        .getIssuer(), serviceProviderConfigs.getX509Certificate());
```

SAMLSSOServiceProviderDO is populated with the correct certificate.

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/util/SAMLSSOUtil.java#L796
[2] https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/validators/SPInitSSOAuthnRequestValidator.java#L170



Followiing is the steps to reproduce this with the Travelocity sample app.

Generate a new keystore for travelocity and export its public cert
```
keytool -genkey -alias wso2carbon -keyalg RSA -keysize 2048 -keystore wso2carbon.jks -dname "CN=example.com, OU=Home,O=Home,L=SL,S=WS,C=LK" -storepass wso2carbon -keypass wso2carbon

keytool -exportcert -alias wso2carbon -keypass wso2carbon -keystore wso2carbon.jks -storepass wso2carbon -rfc -file travelocity.pem
```

Export public cert of WSO2 IS and import it into travelocity keystore
```
keytool -import -alias wso2is -file wso2carbon.pem -keystore wso2carbon.jks -storepass wso2carbon
```

Upload this travelocity.pem into service provider and enable authentication request signature validation and assertion encryption.

Additionally, update travelocity.properties file as follows.
```
SAML2.EnableAssertionEncryption=true
SAML2.EnableRequestSigning=true
KeyStorePassword=wso2carbon
IdPPublicCertAlias=wso2is
PrivateKeyAlias=wso2carbon
PrivateKeyPassword=wso2carbon
```
Now Travelocity app will during the authentication saying "Unable to decrypt the SAML2 Assertion".
