### ISSUE TITLE
[Doc] Version number needs to be updated on 5.8.0

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#4750]
**Purpose**
> Version number needs to be updated in the 5.8.0 Documentation QSG

![image](https://user-images.githubusercontent.com/7569427/54875328-1682bf00-4e23-11e9-94d5-1c4002c3c663.png)

**Steps to reproduce**
> Navigate to https://docs.wso2.com/display/IS580/Quick+Start+Guide and scroll down a bit

**Comment by sherenewso2** [comment]
Fixed in [1] 

[1] https://docs.wso2.com/display/IS580/Quick+Start+Guide
