### ISSUE TITLE
Load balancer host name and node host names are configured differently in the deployment pattern 1 

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4751]
In the [deployment pattern 1 document](https://docs.wso2.com/display/IS580/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Frontingwithaloadbalancer(Nginx))[1], node hostname is set for wso2.is.com, but in the Nginx server name is is.wso2.com.

This configuration can lead to the requirement for proxy path rewrites. Also, the recommended approach is to have the same hostname for nodes and the Nginx server name.

[1] https://docs.wso2.com/display/IS580/Setting+Up+Deployment+Pattern+1#SettingUpDeploymentPattern1-Frontingwithaloadbalancer(Nginx)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
