### ISSUE TITLE
[UX] Cannot delete user added authentication step

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#4757]
**Purpose**
> Radio button shouldn't be a link. Once user select the option. We need to show the "Configuration" link.

![image](https://user-images.githubusercontent.com/7569427/54875763-9e1ffc00-4e2a-11e9-8978-4d84967e1df0.png)

> And under "Advance Configuration", Once user add steps, user cant delete the first step. And the error message is too technical and can't understand the issue why it's not allowing to delete that step. And if it's a mandatory to have that step. Would be better to keep that step by default and differentiate on the UI to emphasis as it is a mandatory step.

![image](https://user-images.githubusercontent.com/7569427/54875703-af1c3d80-4e29-11e9-83ba-59a2f4b55d46.png)

**Steps to reproduce**
> 1. Log in to WSO2 IS Management Console
> 2. Navigate to "Add" section under "Service Providers"
> 3. Expand "Local & Outbound Authentication Configuration" And click on "Advanced Configuration"
> 4. Add 2 or more steps and keep on deleting the steps to the first one

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
