### ISSUE TITLE
Some values are not provisioned in SCIM outbound provisioning

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4759]
**Suggested Labels**

Affected: 5.8.0-alpha2
Severity: Major
Priority: High
Component: Outbound Provisioning
Type-Bug

**Steps to reproduce**

- Configure SCIM outbound provisioning using 2 IS-packs
- Use the following request to create a new user

> curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"smith","givenName":"john"},"userName":"john@wso2.com","password":"john123","emails":[{"primary":true,"value":"john_home.com","type":"home"},{"value":"john_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users

- View the user profile from the management console of the second IS

**Actual Behavior**

Some property values are not provisioned (outbound) to the second IS

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
