### ISSUE TITLE
[UI] TOTP element alignment issue

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#4760]
**Purpose**
> TOTP option element position looks broken and misaligned.

![image](https://user-images.githubusercontent.com/7569427/54875932-89913300-4e2d-11e9-8fc0-a91a1974843f.png) 

**Steps to reproduce**
> 1. Follow the guide on https://docs.wso2.com/display/IS580/Multi-factor+Authentication+for+WSO2+IS
> 2. Under local & outbound authentication give "totp" as an option
> 3. As on the "Try out" step, navigate to https://localhost:9443

**Comment by DonOmalVindula** [comment]
Closing as it's no longer applicable.
