### ISSUE TITLE
Obsolete instructions for UMA in IS 5.8.0 docs

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#4768]
Refer: https://docs.wso2.com/display/IS580/User+Managed+Access+with+WSO2+Identity+Server

Following instructions is not needed with IS5.8.0 as now the default identity.xml comes with that element.
<img width="1602" alt="uma-obsolete-instruction" src="https://user-images.githubusercontent.com/1617810/54876243-a0865400-4e32-11e9-9602-d0badd12c7bd.png">

**Comment by sherenewso2** [comment]
Fixed in [1] 

[1] https://docs.wso2.com/display/IS580/User+Managed+Access+with+WSO2+Identity+Server
