### ISSUE TITLE
Introspection data providers must be OOTB enabled

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#4769]
To inject UMA permissions to introspect response, the following PR introduced "Introspection DataProvider" concept.
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1009

In order to use this, the following configuration should be present in identity.xml
```
      <Introspection>
          <EnableDataProviders>true</EnableDataProviders>
      </Introspection>
```

This configuration should be OOTB available in the identity.xml rather having someone to manually modify the identity.xml...

**Without this, UMA flow breaks when the resource server introspects the RPT.**

Ex:
Introspection response without above configuration:
```
{
  "nbf": 1553411123,
  "active": true,
  "token_type": "Bearer",
  "exp": 1553414723,
  "iat": 1553411123,
  "client_id": "JfTSiJ24gh8sYHTQVuOl5RoftkAa",
  "username": "oliver.uma.demo"
}
```

Introspection response with above configuration:
```
{
  "nbf": 1553414959,
  "permissions": [
    {
      "resource_scopes": [
        "view"
      ],
      "resource_id": "08e69621-e418-4914-b85f-164e127c20de"
    }
  ],
  "active": true,
  "token_type": "Bearer",
  "exp": 1553418559,
  "iat": 1553414959,
  "client_id": "JfTSiJ24gh8sYHTQVuOl5RoftkAa",
  "username": "oliver.uma.demo"
}
```

Further, (migration?) docs should mention the impact on both having the configuration and not having the configuration, and the vendor recommendation.

**Comment by gomathyk** [comment]
Updated doc:
https://docs.wso2.com/display/IS580/User+Managed+Access+with+WSO2+Identity+Server

**Comment by malithie** [comment]
This property impacts introspection for bearer tokens issued for any other grant type as this triggers the UMA handler which does a DB call and grabs permissions to be included in the introspection response.
Refer [1].
As UMA is a special use case and the fix for the above mentioned issue incurs some complexity, setting up the respective config to 'false' by default as the flow impacts the common introspection use cases.
[1] https://github.com/wso2/product-is/issues/5150

**Comment by malithie** [comment]
Created [1] to capture doc impact.
Reducing the severity as there is a configuration to enable the behavior if required

[1] https://github.com/wso2/product-is/issues/5175

**Comment by Abilashini** [comment]
Added to the migration doc of IS 5.8.0 (https://docs.wso2.com/display/IS580/Understanding+What+Has+Changed)
