### ISSUE TITLE
Outbound provisioning to Salesforce does not work as expected

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4778]
**Suggested Labels**

Affected: 5.8.0-alpha2
Severity: Major
Priority: High
Component: Salesforce Outbound Provisioning
Type-Bug

**Steps to reproduce**

- Follow the instructions in the [documentation](https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce)

**Actual Behavior**

BadRequestException is thrown from the backend and the user is not created at Salesforce.

**Comment by sarubi** [comment]
I also encountered the same issue in IS 5.7.0 WUM pack when doing outbound provisioning to salesforce.

**Comment by IsurangaPerera** [comment]
functionality restored in 5.8.0-alpha2 without any code changes at IS side.

**Comment by malithie** [comment]
Resolving as per comment above
