### ISSUE TITLE
Cannot retrieve an access token from SAML2 Bearer Grant type for a user in a secondary user-store

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4781]
In  SAML2 Bearer Grant type, need to append the user-store domain for the secondary userstore user. Otherwise, the token request would fail if `<UserType>LOCAL</UserType>` is enabled in the identity.xml.

Need to update this in the document[1].

[1] https://docs.wso2.com/display/IS580/Setting+up+a+SAML2+Bearer+Assertion+Profile+for+OAuth+2.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
