### ISSUE TITLE
Invalid requests\responses in UMA doc

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#4788]
Refer doc: https://docs.wso2.com/display/IS580/User+Managed+Access+with+WSO2+Identity+Server

**Issue#1: Register resource request is wrong**

resource_scope should be changed as resource_scopes
Ex: Correct request,
```
curl -X POST \
  https://localhost:9443/api/identity/oauth2/uma/resourceregistration/v1.0/resource \
  -H 'Authorization: Bearer 64658549-47c1-3b5a-8637-c629f16c4118' \
  -H 'Content-Type: application/json' \
  -d '{
  "resource_scopes": [
    "view",
    "download"
  ],
  "description": "Collection of digital photographs",
  "icon_uri": "http://www.example.com/icons/flower.png",
  "name": "Photo Album 2",
  "type": "http://www.example.com/rsrcs/photoalbum"
}'
```

**Issue#2: Register resource response is wrong**

`resourceId` should be changed to `_id`.
`"policy_uri":null` won't be present in the response.

Ex: Correct response,
```
{
    "_id": "ceaa6506-1da9-456b-88d8-027797d2e081"
}
```

Above 1 & 2 code changes has been done with: https://github.com/wso2-extensions/identity-oauth-uma/pull/36

**Comment by sherenewso2** [comment]
Fixed in [1] 

[1] https://docs.wso2.com/display/IS580/User+Managed+Access+with+WSO2+Identity+Server
