### ISSUE TITLE
'groups' claim is not properly returned when requested for OIDC hybrid flow

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4789]
**Environment:**
DB: DB2
JDK: Java 8

**Steps to reproduce:**
1. Create a tenant
2. Create a user in that tenant
3. Create two roles as testrole1 and testrole2 and assign to that user
4. Create an oauth application
5. Configure claims section as below.
![image](https://user-images.githubusercontent.com/4951983/54877997-28c52300-4e4c-11e9-8d1b-6d5e29f26d13.png)
6. Make sure 'groups' open id connect claim mapped to http://wso2.org/claims/role is available only for 'profile' scope
7. Initiate requests with OIDC Hybrid flow and verify response in user info for the access token retrieved,  id token in response and id token returned from token endpoint for the code received for **code token**, **code id_token**, **code id_token token** response types.
- **code token** flow
   - When request initiated for scope=openid profile
**Response of userinfo for the access token**
Returned only 'Internal/everyone' in 'groups' even though the user is assigned to testrole1 and testrole2
**id_token of token request initiated for the code returned from code token authorization request**
Didn't have 'groups' claim at all
- **code id_token** flow
   - When request initiated for scope=openid profile
**id_token in code id_token authorization request**
Didn't have 'groups' claim at all
**id_token of token request initiated for the code returned from code id_token authorization request**
Didn't have 'groups' claim at all
- **code id_token token** flow
   - When request initiated for scope=openid profile
**Response of userinfo for the access token**
Returned only 'Internal/everyone' in 'groups' even though the user is assigned to testrole1 and testrole2
**id_token in code id_token token authorization request**
Didn't have 'groups' claim at all
**id_token of token request initiated for the code returned from code id_token token authorization request**
Didn't have 'groups' claim at all

**Comment by malithie** [comment]
Verify role mapping once this is fixed

**Comment by nilasini** [comment]
Tested with 

1. code token
Retrieve the id token through the **code token** contains all the roles assigned to that particular user.
**Request** 
`https://localhost:9443/oauth2/authorize?response_type=code token&client_id=JQXBO6Wr4gk6mcgDUR4jd1S8WSoa&nonce=asd&redirect_uri=http://wso2is.local:8080/playground2/oauth2client&scope=openid profile`
```
{
  "at_hash": "ZrWc4yPyAWrwoaY1vTMmHg",
  "aud": [
    "JQXBO6Wr4gk6mcgDUR4jd1S8WSoa",
    "https://localhost:9443/oauth2/token"
  ],
  "c_hash": "IyZM4w40Gh7GbQs5Z7gmxw",
  "sub": "nilasini",
  "nbf": 1553846076,
  "azp": "JQXBO6Wr4gk6mcgDUR4jd1S8WSoa",
  "amr": [
    "BasicAuthenticator"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "groups": [
    "Internal/everyone",
    "testrole2",
    "login"
  ],
  "exp": 1553849676,
  "iat": 1553846076,
  "nonce": "asd"
}
```
Invoke userinfo for the retrieved access token, got all the roles

`{"sub":"nilasini","groups":"Internal/everyone,testrole2,login"}
`

2. **code id_token**
id_token contains the roles
```
{
  "at_hash": "ZrWc4yPyAWrwoaY1vTMmHg",
  "aud": [
    "JQXBO6Wr4gk6mcgDUR4jd1S8WSoa",
    "https://localhost:9443/oauth2/token"
  ],
  "c_hash": "rVuGhagoz1SObttSk_E_Pg",
  "sub": "nilasini",
  "azp": "JQXBO6Wr4gk6mcgDUR4jd1S8WSoa",
  "amr": [
    "BasicAuthenticator"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "groups": [
    "Internal/everyone",
    "testrole2",
    "login"
  ],
  "exp": 1553850049,
  "iat": 1553846449,
  "nonce": "asd",
  "sid": "5e3a7d76-7f34-4fdb-b4f9-92ccdb831300"
}
```
**id_token of token request initiated for the code returned from code id_token authorization request**
Contains

3.
 - **code id_token token** flow
   - When request initiated for scope=openid profile
**Response of userinfo for the access token**
Contains all the roles.
**id_token in code id_token token authorization request**
Contains all the roles.
**id_token of token request initiated for the code returned from code id_token token authorization request**
Contains all the roles

**Comment by nilasini** [comment]
This could occur due to the issue \[1]

\[1] https://github.com/wso2/product-is/issues/4758#issuecomment-477501077
