### ISSUE TITLE
Allowing Password grant type to public client

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#4791]
For password grant type, "Allow authentication without the client secret" check box is shown. It means that, It is allowing public clients to use password grant type without client secret. However, it is need to check whether we should use that option with password grant type.

<img width="935" alt="Screen Shot 2019-03-24 at 5 00 27 PM" src="https://user-images.githubusercontent.com/18381642/54878751-02f14b80-4e57-11e9-8fa8-f6633b4d432a.png">

**Comment by ashensw** [comment]
Also when we use `authentication without client secrets` option for **password** and **client credential** grant types sends the following response,

```
{
    "error_description": "Error decoding authorization header. Space delimited \"<authMethod> <base64Hash>\" format violated.",
    "error": "invalid_request"
}
```
We need to give a proper message in the `error_description`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
