### ISSUE TITLE
UMA get resource does not works properly

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#4792]
(Refer https://github.com/wso2/product-is/issues/4788 for corrected request\responses)

1. Obtain PAT referring: https://docs.wso2.com/display/IS570/User+Managed+Access+with+WSO2+Identity+Server#UserManagedAccesswithWSO2IdentityServer-ObtaintheProtectionAPIAccesstoken(PAT)

2. Register a resource referring: https://docs.wso2.com/display/IS570/User+Managed+Access+with+WSO2+Identity+Server#UserManagedAccesswithWSO2IdentityServer-Registertheresource

Note down the resource id.

3. Repeat 1 & 2 using different client id and username.

4. Invoke resources list API with the latest PAT,
```
curl -X GET \
  https://localhost:9443/api/identity/oauth2/uma/resourceregistration/v1.0/resource \
  -H 'Authorization: Bearer 58eedce6-73ad-3034-b339-c6080b085f8d'
```
It returns only the list of resources that belong to that client+user.

5. Get resources API with the latest PAT referring the resource that noted in step 2 with the latest PAT,
```
curl -X GET \
  https://localhost:9443/api/identity/oauth2/uma/resourceregistration/v1.0/resource/08e69621-e418-4914-b85f-164e127c20de \
  -H 'Authorization: Bearer 58eedce6-73ad-3034-b339-c6080b085f8d'
```
It returns the resource description, even that resource does not belong to that user nor to the client.

6. Try to update the resource with the PAT which does not belong to the resource owner,
```
curl -X PUT \
  https://localhost:9443/api/identity/oauth2/uma/resourceregistration/v1.0/resource/08e69621-e418-4914-b85f-164e127c20de \
  -H 'Authorization: Bearer 58eedce6-73ad-3034-b339-c6080b085f8d' \
  -H 'Content-Type: application/json' \
  -d '{
    "resource_scopes": [
        "view"
    ],
    "name": "Photo Album 2",
    "type": "http://www.example.com/rsrcs/photoalbum",
    "icon_uri": "http://www.example.com/icons/flower.png",
    "description": "Collection of digital photographs",
    "_id": "ceaa6506-1da9-456b-88d8-027797d2e081"
}'
```
resource does not get updated, yet the response code is 500. It should have return 401.

7. Try to delete the resource with the PAT which does not belong to the resource owner,
```
curl -X DELETE \
  https://localhost:9443/api/identity/oauth2/uma/resourceregistration/v1.0/resource/08e69621-e418-4914-b85f-164e127c20de \
  -H 'Authorization: Bearer 58eedce6-73ad-3034-b339-c6080b085f8d'
```
The resource get deleted.

**Comment by darshanasbg** [comment]
Should block 5 & 7. Should fix the status code in 6.

**Comment by ashensw** [comment]
Created a migration issue to track the index addition: https://github.com/wso2/product-is/issues/4996
