### ISSUE TITLE
Unenecessary username claim in SAML response when federated for an OIDC IdP

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#4793]
**Environment:**
DB: DB2
JDK: Java 8

**Steps to reproduce:**
1. Create a tenant and a user within the tenant
2. Create a SAML SP within the tenant
3. Setup another instance as an OIDC IdP (IS2) and configure that as an OIDC IdP
4. Link SAML SP to the OIDC IdP
5. Without no claim configurations done at all, login to the SAML SP
6. Consent will be prompted for 'username' claim which should not ideally
7. In SAML response 'http://wso2.org/claims/username' claim will be returned in attribute statement. Yet, only subject statement should be available here

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
