### ISSUE TITLE
No confirmation pop-up when deleting SAML2 or OAuth2 configuration from the service provider UI

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#4797]
There are no confirmation pop-ups for delete buttons under SAML2 or OAuth2 configurations in SP UI.

Similar validation required for Revoke & Regenerate options under OAuth2 configuration.

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by madurangasiriwardena** [comment]
Duplicate of https://github.com/wso2/product-is/issues/1975
