### ISSUE TITLE
Claims are not populated for a local user in SAML bearer grant

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#4800]
**DB:** 
MySQL 5.7
**User:** 
Secondary user store, LDAP

`<UserType>LOCAL</UserType>` is configured in the identity.xml. 

Requested claims in the service provider, are not populated in the ID Token retrieved via SAML bearer grant type. Ideally, a local user should be able to access the requested OIDC local claims.

**Comment by thanujalk** [comment]
Tested the scenario with for primary, JDBC secondary and LDAP secondary users. Scenario worked as expected.
