### ISSUE TITLE
If Username or Password were not provided in token request, error_description needs to be improved

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4801]
If Username or Password were not provided in the token request for password grant type, error_description needs to be improved.
Currently, the response comes like below.
`{"error_description":"OAuthProblemException{error='invalid_request', description='Missing parameters: password', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}","error":"invalid_request"}`

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1047

**Comment by DMHP** [comment]
Re-opened the issue. Inorder to preserve the backward compatibility we need to introducue a property to enable disable this fix.
