### ISSUE TITLE
Incorrect error response when client id is not sent in the token request

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4802]
Error response comes like below.
`<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">org.wso2.carbon.identity.base.IdentityRuntimeException: Parameters map trying to override existing key client_secret</ns1:faultstring></ns1:XMLFault>`

**Comment by DMHP** [comment]
This issue can not be fixed from the oAuth level and this response is coming for a wrong request. Hence reducing the priority and increasing the complexity. Moving this issue to the milestone future.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
