### ISSUE TITLE
Local & Outbound Authentication Configuration (Tenant mode) - Authentication Type reset to Default in UI

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#4803]
**Note:** Seems this is a caching issue and this was not reproduced after the restart. 

Steps to reproduce,

- Configure Travelocity app in a **tenant** by creating a service provider. 
- Change the `Local & Outbound Authentication Configuration` -> `Authentication Type` to any other type as below,

<img width="1142" alt="Screen Shot 2019-03-25 at 10 24 20 AM" src="https://user-images.githubusercontent.com/13478571/54896028-316b3700-4ee8-11e9-83b8-07645a1de03b.png">

- Login to the Travelocity app once and you will see the configurations has been changed correctly.
- But again when you check the above mentioned configuration, you will see it has reset to the default again in the UI.
<img width="1141" alt="Screen Shot 2019-03-25 at 10 27 37 AM" src="https://user-images.githubusercontent.com/13478571/54896133-b0606f80-4ee8-11e9-865e-b040ebe4ef6d.png">

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
