### ISSUE TITLE
Introspection response and id token has different formats for sub

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4804]
Id token
```
{
  "at_hash": "V2eM-bxw_00VFA-PoJOwkA",
  "aud": "iizsXhzgNhdmDdgXuJFOfuHa8XAa",
  "sub": "user2",
  "nbf": 1553496530,
  "azp": "iizsXhzgNhdmDdgXuJFOfuHa8XAa",
  "amr": [
    "password"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "exp": 1553500130,
  "iat": 1553496530
}
```

Introspection response
```
{  
   "nbf":1553496530,
   "scope":"openid",
   "active":true,
   "token_type":"Bearer",
   "exp":1553500130,
   "iat":1553496530,
   "client_id":"iizsXhzgNhdmDdgXuJFOfuHa8XAa",
   "username":"TEST/user2@wso2.com"
}
```

**Comment by nilasini** [comment]
By default the configuration BuildSubjectIdentifierFromSPConfig set to false in identity.xml, that means subject identifier will be set as the fully qualified username hence you will get the username with userstore domain and tenant domain appended. You could refer the documentation [1][2] for the reference.

[1] https://wso2.org/jira/browse/IDENTITY-6955
[2] https://docs.wso2.com/display/IS570/OAuth2+Token+Validation+and+Introspection

**Comment by piraveena** [comment]
As @nilasini mentioned, I was able to solve this issue by enabling the configuration <BuildSubjectIdentifierFromSPConfig>true</BuildSubjectIdentifierFromSPConfig> in identity.xml file

**Comment by malithie** [comment]
Re opening the issue as fixing this has impacts in below flows.
- user info endpoint
As at now we identify the user realm (tenant, user store) from the 'username' claim in introspection response. With the approach used to fix this, calling user info breaks for tenant flows and claims are not returned [1].
- rest valve engaging authorization for REST APIs, when authenticating to the APIs with oauth2 bearer access tokens [2].

Introspection response provides some meta data, with which the resource server could perform further validation. So, should it be consistent with the id_token response as mentioned here.
Further, if the resource server needs to pick up user for further validation, I think introspection response should include meta information supporting that.

Anyhow, as the approach suggested here breaks above two basic flows, by default, it's important to set this property value to 'false'

[1] https://github.com/wso2/product-is/issues/5259
[2] https://github.com/wso2/product-is/issues/5078

**Comment by malithie** [comment]
Changed the severity as this does not blocks any flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
