### ISSUE TITLE
[Doc] Outbound Provisioning with Salesforce document images are not visible

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4812]
Affected: 5.8.0-Alpha2
Severity: Minor
Priority: Normal
Component: Outbound Prov
Type: Docs

Some of the images are not display in the page, Outbound Provisioning with Salesforce  [1]  

[1] https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce

**Comment by sherenewso2** [comment]
Hi,

Closing this as since it seems to be fixed now [1]. Please re-open if the issue is still there. 

[1] https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce
