### ISSUE TITLE
[Doc] Support for renew refresh token property to be configurable per application. IS-5.7.0

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#4815]
We need to include documentation on how to configure/use this new feature. Below attachment includes a sample documentation.

[Instructions.docx](https://github.com/wso2/product-is/files/3006781/Instructions.docx)

improvement for: wso2/product-is#4550

**Comment by gomathyk** [comment]
Documented in -https://docs.wso2.com/display/IS570/Issuing+New+Tokens+Per+Request#1143ed04acef4af2b55d5088eea15663
