### ISSUE TITLE
Deprecate the usage of Thrift Entitlement Service and Thrift Authenticator from IS 5.8.0 release

### ISSUE THREAD

**Issue by dilin993** [wso2/product-is#4819]
In our entitlement component we have support for thrift. We also have an authenticator for thrift. Customers rarely use thrift when utilizing these features.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
