### ISSUE TITLE
message for password requirements before user attempts to set password

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4821]
One of the most frustrating parts of registering an account with a new service is discovering their password requirements by trial-and-error rather than being told up-front.  Being able to provide a message describing these requirements to users, displayed on both the password-reset page and the self-sign-up page, would be very useful.  This could replace `PasswordJavaRegExViolationErrorMsg`, or be a fallback value in the interest of backwards-compatibility.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
