### ISSUE TITLE
[UX] SCIM2 default userstore mismatch between behavior & UI

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4823]
By default, SCIM2 will provision users to the primary userstore when used by a service provider.  However, the Service Provider configuration will display `---Select---` as the default value in the SCIM2 domain drop-down, rather than prepopulating it with the primary userstore.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
