### ISSUE TITLE
[Doc] Review the Adaptive Authentication tutorial

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#4828]
Description
Review [11. Adaptive Authentication Tutorial](https://docs.google.com/document/d/15E3lzybrXTVDwXy0eQygdtFczAaZ7aFejMeJKfR0LsE/edit?ts=5c9b298f#heading=h.khm0683yaytl).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
