### ISSUE TITLE
File where account.lock.handler.login.fail.timeout.ratio needs to be set is not included in the doc

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4830]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: Highest
Component: Account Locking
Type-Doc

In [1] under **Lock Timeout Increment Factor** details mentioned in the table (Tip section) include in which file we need to set the account.lock.handler.login.fail.timeout.ratio.

[1]. https://docs.wso2.com/display/IS580/Account+Locking+by+Failed+Login+Attempts

**Comment by sherenewso2** [comment]
Fixed in versions 5.3.0 - 5.8.0 [1] 
[1] https://docs.wso2.com/display/IS540/Account+Locking+by+Failed+Login+Attempts
