### ISSUE TITLE
Consent Management Rest APIs don't support application wise consent management

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#4833]
In all the webinars we've done on GDPR, we talk about IS as a consent repository that can do consent management of applications through Restful APIs. However, when looking at the APIs it looks like we can't really do application wise consent management and it is global consent management model we have.

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
