### ISSUE TITLE
Consent Purpose descriptions are not shown to the end user

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#4834]
Consent purpose descriptions are not shown to the user, when (s)he needs to provide consent to share user claims to the application. It looks like the user has to provide a "bundled" consent. This violates basic GDPR consent design guideline of "unbundled consent".

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
