### ISSUE TITLE
Consent Purpose descriptions do not support i18n

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#4836]
The consent purpose descriptions do not support internationalization. This violates another one of the basic GDPR consent design guideline of "informed consent". Ideally we should be using the same design we've implemented for challenge question internationalization.

**Comment by ashensw** [comment]
Reducing the severity as this is a request for improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
