### ISSUE TITLE
Cannot have optional Consent Purposes or PII Categories during Self Sign-up

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#4837]
When a user does self sign-up, we are collecting consent for all consent purposes and PII categories. It looks like user cannot sign-up without providing consent for at least one consent purpose or PII category. For example, even if first_name is optional and I don't fill the value for first_name, I need to provide consent to store first_name which doesn't make any sense.

**Comment by johannnallathamby** [comment]
Another follow-up question to this issue.

If we agree to fix this and make consent purposes and/or PII categories optional during self sign-up, can we have scenario where user will give an optional claim value during sign-up, but not give consent to store it? Or will that scenario be avoided?

**Comment by tharindu-bandara** [comment]
@johannnallathamby raised concern moved to the https://github.com/wso2/product-is/issues/5010.
