### ISSUE TITLE
Challenge Question locale not sorted

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4838]
Affected: 5.8.0-Alpha2
Severity: Major
Priority: Normal
Component: User Mgt
Type: Bug

Challenge Questions locale list is not sorted. It's user friendly if can sorted it according to to alphabetical order 
![image](https://user-images.githubusercontent.com/39077751/55076029-6af39c00-50ba-11e9-89a9-e428bc27d140.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
