### ISSUE TITLE
Challange questions ID  can be given every qestions in the set and it is not unique

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4840]
Affected: 5.8.0-Alpha2
Severity: Major
Priority: Normal
Component: User Mgt
Type: Bug

According to the document [1] Challenge Question Id field allows you to enter the question Id of the first question in the set. But here its allows to enter question ID in every questions and can duplicate the Question ID within the set. 

[1] https://docs.wso2.com/display/IS580/Managing+Challenge+Questions#ManagingChallengeQuestions-Addingachallengequestionset

![image](https://user-images.githubusercontent.com/39077751/55087121-91700200-50cf-11e9-9abc-fc10c7273e3b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
