### ISSUE TITLE
Pagination is Not Work Properly in SCIM2 Filters

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#4842]
Pagination is failed in some multi-attribute filter search.
Steps to reproduce,

1. Start the IS server
2. Create around 9 users from kim1 to kim9 
3. Filter users as below
 `https://localhost:9443/scim2/Users?startIndex=5&count=5&attributes=userName&filter=userName+sw+ki+and+userName+co+k`
will return 4 result set,
`{
    "totalResults": 4,
    "startIndex": 5,
    "itemsPerPage": 4,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "id": "09e59379-ed8b-4c46-8eb3-3956b1bf15ac",
            "userName": "kim5"
        },
        {
            "id": "93e6dd69-5423-4002-ac36-fdd12f126737",
            "userName": "kim6"
        },
        {
            "id": "fe8769af-f4e1-4012-99d0-b712f537f0bb",
            "userName": "kim7"
        },
        {
            "id": "dd908a62-f854-43a2-a7a2-c5bb5157eb2f",
            "userName": "kim8"
        }
    ]
}`
5. Apply this filter as startIndex=2&count=5, will work as expected.
 `https://localhost:9443/scim2/Users?startIndex=2&count=5&attributes=userName&filter=userName+sw+ki+and+userName+co+k`
will return 5 result set as expected, 
`{
    "totalResults": 5,
    "startIndex": 2,
    "itemsPerPage": 5,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:ListResponse"
    ],
    "Resources": [
        {
            "id": "d083df4a-2a21-47cd-b5d0-08e1c710092b",
            "userName": "kim2"
        },
        {
            "id": "ff268562-654e-4753-903b-1907daddb5c7",
            "userName": "kim3"
        },
        {
            "id": "04f168fd-547c-4a26-884f-9bd426efc3d7",
            "userName": "kim4"
        },
        {
            "id": "09e59379-ed8b-4c46-8eb3-3956b1bf15ac",
            "userName": "kim5"
        },
        {
            "id": "93e6dd69-5423-4002-ac36-fdd12f126737",
            "userName": "kim6"
        }
    ]
}`

Affected versions;
IS 5.7.0 & above

**Comment by malithie** [comment]
Closing as the fix merged to kernel
