### ISSUE TITLE
'Approve Always' in the consent page for a specific scope will add consent for all the scopes

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#4844]
**Problem**:
If we select 'Approve Always' in the consent page for a specific scope, for all the future authorization requests with different scopes for the specific user will be accepted without consent. It compromises the security since an application can get the end user consent for a scope of low privileged resource and later it can access any highly privileged resources without the end user consent for the scopes. 

**Steps to reproduce**:

1. Configure a OAuth service provider in WSO2 IS

1. Make a authorization request with a scope. Eg:
```https://localhost:9443/oauth2/authorize?scope=email&response_type=code&redirect_uri=http://localhost:8080/playground2/oauth2client&client_id=j0kjC0ba33z5Dw48gdmskbsPQvIa```
1. After user authentication select 'Approve Always' in the consent page and continue

1. Now make a authorization request with a different scope
```https://localhost:9443/oauth2/authorize?scope=phone&response_type=code&redirect_uri=http://localhost:8080/playground2/oauth2client&client_id=j0kjC0ba33z5Dw48gdmskbsPQvIa```
1. User consent page won't be shown for the scope.

**Reason**:
If the consent is given as 'Approve always', an entry will be added in the table 'IDN_OPENID_USER_RPS'  with the combination of user and SP [1]. 
![image](https://user-images.githubusercontent.com/11737221/55130102-a1bfc580-513f-11e9-8252-b9c1c5e36738.png)

The value of TRUSTED_ALWAYS is used to decide whether the consent page need to be prompted or not for a specific user and SP combination during every authorization request [2].
 
[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L968
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L1746

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
