### ISSUE TITLE
Consent page asked for all requested claims without considering the scope

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#4847]
1) Create a service provider
2) Select the requested claims as http://wso2.org/claims/emailaddress, http://wso2.org/claims/givenname, http://wso2.org/claims/lastname
3) Edit the openid scope and removed the claims email,familyname from opeid scope
4) Invoke an authorization request with openid scope, you will ask for the consents for all the requested claims but in the retrieved id token you will only have given name. Ideally consent should be asked for only givenname.

**Comment by malithie** [comment]
This relates with https://github.com/wso2/product-is/issues/4844
Better to discuss together

**Comment by nilasini** [comment]
This issue will be tracked with the doc issue \[1] hence closing the issue.

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227

**Comment by nilasini** [comment]
Reopening the issue since need to consider request object flow with the fix.
