### ISSUE TITLE
Account Lock Email templates does not render content type plain/text

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4849]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: High
Component: Account Locking
Type-Bug

**Steps to Reproduce*

1. Login to management console as admin user
2. Email Templates > List > 
Email Template Type - AccountLock
3. Change the content type to text/plain 

**Observation**
Still will display the text/html content related to an sample Email template

![email1](https://user-images.githubusercontent.com/31848014/55146504-b8c7dd00-516a-11e9-9a49-b113f8c7f0d9.jpg)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
