### ISSUE TITLE
AccountLock adding email templates with other languages does not save the applied changes properly

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4850]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: High
Component: Account Locking
Type-Bug

**Steps to Reproduce**
1. Login to the management console as admin 
2. Email Templates > Add > Add Email Template 
Email Template Type select AccountLock 
Email Template Locale - Arabian
3. Likewise add another template with locale Chinese for Email Template Type AccountLock
Email Template Type select AccountLock 
Email Template Locale - Chinese
4. Email Templates > List
5. From drop down select type as AccountLock
6. Select Template Language to English (default supported locale) and save 
7. UI shows that successfully saves the email temlate
8. Now again go for Email Templates > List > select type AccountLock 

**Observation**
Template Locale Type drop down will show Arabian as the selected Language eventhough we saved it for English in the previous step

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
