### ISSUE TITLE
Log line contain less context

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4853]
Affected: 5.8.0-Alpha2
Severity: Minor
Priority: Normal
Component: User Mgt
Type: Improvement

Error line [1] of the below mentioned log should contain better log context.

 [1]

`[2019-03-26 18:13:23,585] ERROR {org.wso2.carbon.user.core.common.DefaultRealm} -  nullType class java.lang.reflect.InvocationTargetException]`

**Comment by nilasini** [comment]
@aaujayasena Could you please explain more on the issue by including the reproduce steps?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
