### ISSUE TITLE
Sample app for SAML Assertion Query Request profile

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4857]
Currently, SAML2 assertion query profile is tested as in doc[1]. Since this involves modifying a test class from an external repository we may use some other mode of testing as in Pickup sample app.

[1] [https://docs.wso2.com/display/IS580/Querying+SAML+Assertions](https://docs.wso2.com/display/IS580/Querying+SAML+Assertions)

**Comment by deshankoswatte** [comment]
Hi @IsurangaPerera,

This is no longer tested by pointing to an external repository as it has been moved to samples-is. But keeping this issue opened since we need to have an improved method of testing the scenario.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
