### ISSUE TITLE
[Doc] Omit testing scenarios from SAML Assertion Query profile doc

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4858]
Since scenarios explained in https://docs.wso2.com/display/IS580/Querying+SAML+Assertions  involves modification and execution of test classes from an external repository we may drop scenario testing from the doc.

**Comment by deshankoswatte** [comment]
Hi @IsurangaPerera,

The content of the [external repository](https://github.com/gayangithub/wso2-is-assertion-query-client) was refactor and moved to [samples-is](https://github.com/wso2/samples-is/) with [https://github.com/wso2/samples-is/pull/211](https://github.com/wso2/samples-is/pull/211). With the PR there were few changes which needs to be made for the docs, which is tracked with [https://github.com/wso2/docs-is/issues/924](https://github.com/wso2/docs-is/issues/924). Hence closing this issue as it will no longer point to an external repository.

**Comment by GDRDABARERA** [comment]
Sample is merged hence clossing
