### ISSUE TITLE
[Doc] Tabs in the user guides are misleading

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#4859]
The tabs in the documentation [Working with Product Observability](https://docs.wso2.com/display/IS570/Working+with+Product+Observability) seems to be confusing. There is high possibility to miss configuration steps since the tabs are hidden by defualt.

**Comment by vihanga-liyanage** [comment]
+1
We can add general topics for Configuring Product Observability, Enabling Observability, etc. And use tabs for Log Patterns and other optional stuff. WDYT?

**Comment by YvonneW** [comment]
Restructured the content in the following pages accordingly: 
- https://docs.wso2.com/display/IS540/Working+with+Product+Observability
- https://docs.wso2.com/display/IS541/Working+with+Product+Observability
- https://docs.wso2.com/display/IS550/Working+with+Product+Observability
- https://docs.wso2.com/display/IS560/Working+with+Product+Observability
- https://docs.wso2.com/display/IS570/Working+with+Product+Observability
- https://docs.wso2.com/display/IS580/Working+with+Product+Observability

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
