### ISSUE TITLE
Reset password filed is autocomplete

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4866]
Affected: 5.8.0-Alpha2
Severity: Major
Priority: Normal
Component: User Mgt
Type: Bug

Password filed autocomplete is not necessary for the password reset fields since user will not use the same password again. Therefor  better to add autocomplete attribute and set value as 'off'

![image](https://user-images.githubusercontent.com/39077751/55233581-09b10180-524f-11e9-864b-f5cf68bcd436.png)

**Comment by Chamodii** [comment]
started checking

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
