### ISSUE TITLE
Invalid field type when add filed value as true

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4872]
Affected: 5.8.0-Alpha2
Severity: Major
Priority: Law
Component: User Mgt
Type: Bug

Setting up the filed  value  in the user profile as 'true' using admin services, shows a invalid input filed type. 

Example fields: country, One Time Password, Force Password Reset

Admin service: https://localhost:9443/services/UserProfileMgtService?wsdl

Request:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mgt="http://mgt.profile.user.identity.carbon.wso2.org" xmlns:xsd="http://mgt.profile.user.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <mgt:setUserProfile>
         <!--Optional:-->
         <mgt:username>tom</mgt:username>
         <!--Optional:-->
         <mgt:profile>
            <!--Zero or more repetitions:-->
            <xsd:fieldValues>
               <!--Optional:-->
               <xsd:claimUri>http://wso2.org/claims/country</xsd:claimUri>
           <xsd:fieldValue>true</xsd:fieldValue>
            </xsd:fieldValues>
            <!--Optional:-->
            <xsd:profileName>default</xsd:profileName>
         </mgt:profile>
      </mgt:setUserProfile>
   </soapenv:Body>
</soapenv:Envelope>
```

![image](https://user-images.githubusercontent.com/39077751/55235750-47fcef80-5254-11e9-9104-178e9f2d5ecc.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
