### ISSUE TITLE
Invalid filed value for Force Password Reset in the user profile

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4873]
Affected: 5.8.0-Alpha2
Severity: Major
Priority: Law
Component: User Mgt
Type: Bug

In user profile Force Password Reset values should be true or false. Value can be manage with a drop down so this will avoid invalid inputs. 

![image](https://user-images.githubusercontent.com/39077751/55237538-6238cc80-5258-11e9-8791-bbe95f08a620.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
