### ISSUE TITLE
[UX] error page for attempting to use an expired onboarding or password-reset email should give user option to send a new one

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4875]
In WSO2IS 5.6.0, when a user-onboarding email expires, that user is simply displayed an error message.  Presenting the option to send a fresh email alongside this message would improve the user experience in this case.

I suspect, but have not verified, that the same applies for an expired password-reset email.

**Comment by hauntingEcho** [comment]
screenshot for reference:
![Screen Shot 2019-03-29 at 11 33 10 AM](https://user-images.githubusercontent.com/1661988/55249754-d48abc00-521a-11e9-8941-4cdac7cd34a1.png)

**Comment by ashensw** [comment]
This capability is already available in the REST API [1]. Hence reducing the severity since this is a UI improvement. 

[1] https://docs.wso2.com/display/IS550/apidocs/self-registration/#!/operations#SelfRegister#resendCodePost

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
