### ISSUE TITLE
Migration client skips the migration when the starting version is 5.4.1

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#4881]
If we set the "currentVersion" as 5.4.1 in the migration-config.yaml, the migration won't start. Because we don't have a version migrator called 5.4.1 and then the logic in [1] will never become true. 

`if (!isMigrationStarted && versionMigration.getPreviousVersion().equals(config.getCurrentVersion())) `

Also, according to [2], there is nothing to do in the migration from 5.4.0 to 5.4.1.

Therefore, it is required to add a note in the migration doc saying "even if you are in 5.4.1, use 5.4.0 in the yaml" or update the migration client to treat 5.4.1 also as 5.4.0.

[1] https://github.com/wso2/product-is/blob/master/modules/migration/migration-service/src/main/java/org/wso2/carbon/is/migration/MigrationClientImpl.java#L76
[2] https://docs.wso2.com/display/IS541/Upgrading+from+a+Previous+Release

**Comment by rksk** [comment]
Created a DOC jira to update the migration docs.

[1] https://wso2.org/jira/browse/DOCUMENTATION-8497

**Comment by nilasini** [comment]
Added a note in the doc
