### ISSUE TITLE
SCIM2/Me user provisioning with a non allowed email id as the username returns non matching email id in the response with wrong message

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4886]
**Suggested Labels**
Affected : 5.8.0- alpha3
Severity: Major
Priority: Highest
Component: SCIM2
Type-Bug

**Environment**
Linux, JDBC UserStore

**Steps to Reproduce the issue**

1. Enable SCIM for JDBC userstore from user-mgt.xml
2. In identity.xml make the scim/Me resources secured property as false [1]
3. Try to provision a user using scim2/Me endpoint using a email id as the username which is not allowed from the user store regex

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim_df-dkAEE,.//@wso2.com","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Users`

Will get the below response

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Cannot add user through scim to user store . SCIM is not enabled for user store KIM_DF-DKAEE,.","status":"500"}`

Eventhogh SCIM is enabled in the system response specify as SCIM is not enabled and also the email id given as the input is showing with capital letters in the response.
Request - userName":"kim_df-dkAEE,.//@wso2.com
Response received - KIM_DF-DKAEE,.

![me1](https://user-images.githubusercontent.com/31848014/55329540-7aa12500-54ac-11e9-860d-b3fce95e2d3e.png)

[1]. https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#MeEndpoint#createUserMe

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
