### ISSUE TITLE
SCIM2/Me User provisioning with empty password in the request doesnt give a response as password cannot be empty

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4889]
**Suggested Labels**
Affected : 5.8.0- alpha3
Severity: Major
Priority: High
Component: SCIM2
Type-Bug

**Environment**
Linux, JDBC UserStore

**Steps to Reproduce the issue**

1. Enable SCIM for JDBC userstore from user-mgt.xml
2. In identity.xml make the scim/Me resources secured property as false [1]
3. Try to provision a user without a empty password in the request

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim_df-dkAEE,.@wso2.com","password":"","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Users`

Will get the below response
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in adding the user: kim_df-dkAEE,.@wso2.com to the user store. PasswordInvalidAsk Password Feature is disabled","status":"500"}
`
The message given in the response is not matching with the user action. As user haven't input a password and this is the 1st time user is trying to set the password therefore we cant say it is invalid. It gives a feeling like user have already set a pw. But now trying to access the server with a non matching pw for what he has already set. Therefore Need to change the response message as Password field cannot be empty.

![me2](https://user-images.githubusercontent.com/31848014/55330888-cacdb680-54af-11e9-8061-ae3aa42bce8f.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
