### ISSUE TITLE
Role-Based Adaptive Authentication do not work with a Service Provider of a SAML application in a SSO scenario

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/product-is#4890]
**Suggested Labels:**
Affected : 5.7.0
Severity: Blocker
Priority: Highest
Type: Bug

**Steps to Reproduce the issue:**

1. Setup SAML application and the service provider with SAML configuration as given in [Configuring a Service Provider for Adaptive Authentication](https://docs.wso2.com/display/IS570/Configuring+a+Service+Provider+for+Adaptive+Authentication). 
2. Set up role-based adaptive authentication for previously created Service Provider as given in [Configuring Role-Based Adaptive Authentication](https://docs.wso2.com/display/IS570/Configuring+Role-Based+Adaptive+Authentication).
3. Login to the WSO2 IS Dashboard (https://localhost:9443/dashboard) using admin credentials.
4. Then go the index page of the SAML application (http://localhost.com:8080/saml2-web-app-pickup-dispatch.com/) and click the login button.
5. This should redirect to Adaptive Authetication page but this will skipped the Adaptive Authentication.The admin role has been authenticated successfully only after going through the basic authentication.

This issue's cause is FLOW_STATUS parameter [1]
```
AuthenticatorFlowStatus flowStatus = (AuthenticatorFlowStatus) request
                .getAttribute(FrameworkConstants.RequestParams.FLOW_STATUS);`
```

When the request come from SAML component the FLOW_STATUS is set to null value. However, the OAuth components set this value to COMPLETED value when the request come. Therefore, this scenario is working for OAuth applications. 

[1]. https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/sequence/impl/GraphBasedSequenceHandler.java#L415

**Comment by senthalan** [comment]
This issue already identified with https://github.com/wso2/product-is/issues/3717 and fixed with https://github.com/wso2/carbon-identity-framework/pull/1900 in master
