### ISSUE TITLE
Missing indexes in the database

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#4891]
#### Description
Following  indexes improve the performance in WSO2 IS

- `CREATE INDEX IF NOT EXISTS IDX_SIA_AI ON SP_INBOUND_AUTH(APP_ID);`

There are no indexes which will be hit by the following queries.
- `SELECT PROPERTY_KEY, PROPERTY_VALUE FROM IDN_OIDC_PROPERTY WHERE TENANT_ID = ? AND CONSUMER_KEY = ?`
- `SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME =? AND UM_TENANT_ID=?`

#### Type
Improvement

#### Affected version
5.7.0

**Comment by mefarazath** [comment]
These changed need to be added to the migration client as well..

**Comment by malithie** [comment]
Migration impact tracked with https://github.com/wso2/product-is/issues/5245

Resolving the issue as fixes are incorporated
