### ISSUE TITLE
Update product-is to kernel-4.4.39 version.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#4894]
Following issues will be resolved with this:

- Resolves https://github.com/wso2/product-is/issues/4676
- Resolves https://github.com/wso2/product-is/issues/4648
- Resolves https://github.com/wso2/product-is/issues/3838
- Resolves https://github.com/wso2/product-is/issues/4689
- Resolves https://github.com/wso2/product-is/issues/4842
- Resolves https://github.com/wso2/product-is/issues/4966
- Resolves https://github.com/wso2/product-is/issues/4985

**Comment by DMHP** [comment]
https://github.com/wso2/product-is/issues/4604

**Comment by ashensw** [comment]
Updated the kernel : https://github.com/wso2/product-is/pull/5033
