### ISSUE TITLE
Can not update the user profile email address and force to reset password field simultaneously

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4897]
Affected: 5.8.0-Alpha2
Severity: Critical
Priority: High
Component: User Mgt
Type: Bug

Update the user profile email address and force reset password field simultaneously through admin console.

**Steps:**
01.  Admin user login to the carbon
02. Admin user navigate to the Claims ->  List -> http://wso2.org/claims/identity/adminForcedPasswordReset and click edit
03. Admin user enable Supported by Default option
04. Admin user create a user
05. Admin user navigate to the created users, default user profile for update user profile
06. Admin user update the user profile fields,
First Name, Last Name, Email (with valid email), Force password reset (with string true) 
07. Admin user click update

**Expected result:**
1. Created new users profile details should be update successfully 
2. Force password reset request should be send to the user

**Actual result:** 
1. Error (image 01)

![image](https://user-images.githubusercontent.com/39077751/55379905-22196880-553c-11e9-97f1-e403dad3f120.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
