### ISSUE TITLE
'Ask Password from User' not available in WSO2 Identity Server v 5.1

### ISSUE THREAD

**Issue by AnujaK** [wso2/product-is#490]
We do not have facility to enter email id of newly created user. Need this functionality so that newly created user received email and can change his password by following the link.

Attaching screenshot of v 5.0 and v 5.1 'Add User'.
![wso2idpversion5 1](https://cloud.githubusercontent.com/assets/1309080/15322617/7e5b48b0-1c5b-11e6-8662-044171bccdff.png)
![version5 0](https://cloud.githubusercontent.com/assets/1309080/15322636/97f5fe3c-1c5b-11e6-8f3b-d25cfa8c5759.png)

**Comment by omindu** [comment]
Hi Anuja,

Have you followed https://docs.wso2.com/display/IS510/Creating+Users+using+the+Ask+Password+Option ?

**Comment by AnujaK** [comment]
@omindu Cross-checked all the steps mentioned in the documentation. The Add User page continues to be same- Username, password, repeat password. No facility to send email.

**Comment by omindu** [comment]
@AnujaK I just tried it with a fresh IS 5.1.0 pack and it is functioning as expected. Make sure `IdentityMgtEventListener` is enabled (`enable="true"`)

`<EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener" name="org.wso2.carbon.identity.mgt.IdentityMgtEventListener" orderId="50" enable="true"/>`

**Comment by AnujaK** [comment]
Thanks @omindu . Worked wonders!
