### ISSUE TITLE
Can provision the users using scim2/Me with invalid email formats

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4904]
**Suggested Labels**
Affected : 5.8.0- alpha3
Severity: Major
Priority: Normal
Component: SCIM2
Type-Improvement

**Environment**
Linux, EmbeddedLDAP UserStore

**Steps to Reproduce the Issue**
1. Enable SCIM in user-mgt.xml
2. Set the scim2/Me Create Resource secured as false in identity.xml as in [1]
3. Provision a user using the sample request

`curl -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"alex","password":"alexwso2","emails":[{"primary":true,"value":"alex.j","type":"home"},{"value":"alex_j@","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Me`

Will allow to provision the users with email addresses that are invalid. Better to have a validation to validate the email addresses.

[1]. https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#MeEndpoint#createUserMe

**Comment by ShanikaWickramasinghe** [comment]
Related - User Update using the below sample command also allows to update the users with invalid email formats.

`curl -v -k --user alex:alexwso2 -X PUT -d '{"schemas":[],"name":{"familyName":"JacksonJohnoo","givenName":"Kimoo"},"userName":"alex","emails":[{"primary":true,"value":"jacksonkkkmmmgmail.com","type":"home"},{"value":"jackson_kkkwso2.com","type":"work"}]}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Me`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
