### ISSUE TITLE
Forced password reset via OTP and offiline not notify the password reset require message

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4907]
Affected: 5.8.0-Alpha2
Severity: Major
Priority: High
Component: User Mgt
Type: Bug

Password reset request notification not receive to the login user in  'Forced password reset via OTP' and 'Offline Password Reset'. Notification would be very useful if any case user miss to check his email. Currently this notification only contain that the inserted password or user name is invalid message only. (image 01). In Forced password reset via recovery email had this notification  with detail to check the email. (image 2) There for better to apply the same method here also. 

Image 01:
![image](https://user-images.githubusercontent.com/39077751/55401244-c7990000-556d-11e9-9eb0-dc72e015f522.png)

Image 02:
![image](https://user-images.githubusercontent.com/39077751/55401293-e8f9ec00-556d-11e9-96c5-e2deb47b74ed.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
