### ISSUE TITLE
Configure user claims included in self contained access token

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4908]
amr claim value is included in the ID Token. But it is not required in the self-contained access token. Likewise, there are some claims which are not required to be included in the self-contained access token. We need a feature where users can configure which user claims are to be included in the access token.

**Comment by darshanasbg** [comment]
A created a separate issue (https://github.com/wso2/product-is/issues/4915) to track the feature request.

Let's conclude what claims should be present in which token in this thread.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
