### ISSUE TITLE
Performance improvement for client_credentials grant type token flow

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#4909]
Few places where we could avoid DB lookup were identified and need to be fixed.

1. During client_id, client_secret based client authentication, we are doing a DB lookup to get the client secret. Instead, we can derive the same from the application information object. The advantage is that application information can be cached and will be reused within the request flow.
2. Instead of doing a separate DB lookup to get app state, we can derive the app state from the application information object.
3. Service Provider loading is very heavy with multiple DB calls. During the token issuing path, we are unnecessarily loading the SP to derive the authenticated identifier of the user to which the token was issued. This should ideally happen in the token issuing path. Also, the subject identifier of local users is always calculated based on SP configs so storing the authenticated identifier of local users in unnecessary

**Comment by mefarazath** [comment]
@nilasini these improvements are in the token issuing path. 
So its important we get these improvements into the 5.8.0 release.

**Comment by DMHP** [comment]
Re-opening to fix the integration test failure.

**Comment by madurangasiriwardena** [comment]
Test failures are fixed https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1059
