### ISSUE TITLE
Token validation fails when the JWT access token is looked up from the DB 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#4913]
Steps to reproduce:

1. Create a Service Provider and configure OAuth.
2. Set the token type as JWT
3. Enable SCIM provisioning for the SP
4. Obtain an access token using the SP created in step #1
5. Restart the server (This is to make sure caches are cleared)
6. Do a SCIM request, (curl -v -k -H "Authorization:Bearer $jwt_token" https://localhost:9443/wso2/scim/Users)
7.  Request fails with 
{"Errors":[{"code":"401","description":"Authentication failed for this resource."}]}

This issue occurs due to a flaw in the token persistence logic when JWT access tokens are used. When the token is served from the cache the validation logic works as expected. But when the token is looked up from the DB validation fails.

**Comment by mefarazath** [comment]
Another way to reproduce this would be,

1. Disable OAuthCache in identity.xml
2. Create an OAuth app with JWT access token type
3. Obtain an access token
4. Try to introspect the obtained token

Since the token misses the cache and the DB lookup logic fails, the token will be returned as INACTIVE.
