### ISSUE TITLE
Developer Mode For the Identity Server

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4918]
A suggestion to have a developer mode for the WSO2 Identity Server. The developer mode will include all the standard features, plus developer-friendly features. 

An example of a developer-friendly feature would be the [Cache Invalidation API](https://github.com/wso2/product-is/issues/4916).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
