### ISSUE TITLE
User enable all three option for the force password reset fail

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4920]
Affected: 5.8.0-Alpha2
Severity: Critical
Priority: High
Component: User Mgt
Type: Bug

IS management console allow to enable all three options of  force password reset . If this  is a valid one, Once the admin user force to reset the password

**Expected results are,**

-  All three type of options should be receive to choose. (Password Reset via Recovery Email/ Password Reset via OTP and Offline Password Reset)
- Once the user selected one option and proceed,  password reset should be successfully and  after others two options should be invalid

**Actual results are,**

- Receive only two options (Password Reset via Recovery Email/Offline Password Reset)
-Offline Password Reset is not working

**Steps to reproduce:**
01. Enable all three options of force password reset [1]
02. Create user
03.  Send soap request for the force password reset
04. User attempt to login to the dashboard
05. User receive the password reset notification
06. User try with offline password reset option
07. User try with  Password Reset via Recovery Email option

[1] https://docs.wso2.com/display/IS580/Forced+Password+Reset

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
