### ISSUE TITLE
Ask password from user option is enabled but still admin user can set a pw before the user set a pw

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4926]
**Suggested Labels**
Affected : 5.8.0- alpha3
Severity: Major
Priority: High
Component: Ask Password
Type-Bug

**Environment**
Linux, Embedded LDAP UserStore, 

1. Followed document [1] to enable ask password feature in user on boarding.
2. Admin user add a new user via ask password admin UI by selecting the option Ask password from user.
3. User will receive a email as saying to set a password for his account
4. Meantime before the user set a password for his account even though the Ask password from user is selected in step 2 admin user still can view the created user from the management console and list created users > select the user > change password option and change the password for the user

If Ask password feature is enabled and admin user selects the ask pw from user option then after sending a email for the user to set a password then before the user set a password admin user should not be able to set a password for that users account.

[1]. https://docs.wso2.com/display/IS580/Creating+Users+using+the+Ask+Password+Option

**Comment by nilasini** [comment]
@ShanikaWickramasinghe this is an expected behaviour.
