### ISSUE TITLE
Re-evaluate property loading mechanism from database

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/product-is#4928]
At the moment, when we start product for the first time, we set default property values in IDP_METADATA. But if we introduce a new update which require a new property, we will not set the default value for the property. This leads to possible errors.

Same observation is not present when configuration files are used to introduce new property values.

**Comment by hauntingEcho** [comment]
for clarification: in 5.6.0, this can prevent new users from being created with the ask-password after a WUM update is applied as `Recovery.CallbackRegex` is missing.  The issue can be worked around by opening the resident IDP configuration UI, which will add a default value.

**Comment by malithie** [comment]
Fixed
