### ISSUE TITLE
SCIM2 Ask password option from user fails giving Java Security Manager Privilege Block Error

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4932]
**Suggested Labels**
Affected : 5.8.0- alpha2
Severity: Major
Priority: High
Component: Ask Password
Type-Bug

**Environment**
Linux, Embedded LDAP UserStore,
JDK 1.8.0_121

**Steps to reproduce the issue**

1. Followed the document [1] on user on boarding with Ask password option
2. Under Scim 2.0 section tried the request as given below to create a user using ask password option

sample request

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com","type":"home"},{"value":"dewmi123455@gmail.com","type":"work"}],"EnterpriseUser":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

Observed the below error in the carbon console
User is created in the management console but the request failed with 500 status code and below errors. Didn't received an email for the email addresses which are configured to set the password for the user account.

`[2019-04-03 16:40:36,943] ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} -  Error occurred while accessing Java Security Manager Privilege Block when called by method addUser with 6 length of Objects and argTypes [class java.lang.String, class java.lang.Object, class [Ljava.lang.String;, interface java.util.Map, class java.lang.String, boolean]`

```
upload completely sent off: 271 out of 271 bytes
< HTTP/1.1 500 Internal Server Error
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Wed, 03 Apr 2019 11:24:18 GMT
< Content-Type: application/scim+json
< Content-Length: 406
< Connection: close
< Server: WSO2 Carbon Server
< 
* Closing connection 0
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in adding the user: Paul to the user store. Error occurred while accessing Java Security Manager Privilege Block when called by method addUser with 6 length of Objects and argTypes [class java.lang.String, class java.lang.Object, class [Ljava.lang.String;, interface java.util.Map, class java.lang.String, boolean]","status":"500"}
```

[1]. https://docs.wso2.com/display/IS580/Creating+Users+using+the+Ask+Password+Option

**Comment by ashensw** [comment]
For the **askPassword** feature, email is a mandatory attribute. As for the default IS configs the email claim and the relevant scim claim mapping would be as below,

`http://wso2.org/claims/emailaddress -> urn:ietf:params:scim:schemas:core:2.0:User:emails`

Therefore you need to send the email address as below in the user creation request,

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com"}],"EnterpriseUser":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

Or else you have to map the `http://wso2.org/claims/emailaddress` claim to relevent scim claim as below,

<img width="1140" alt="Screen Shot 2019-04-05 at 5 36 42 PM" src="https://user-images.githubusercontent.com/13478571/55626544-75ecb180-57c9-11e9-8033-69b740f01882.png">

Then you can use the below request as well,

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com","type":"home"},{"value":"dewmi123455@gmail.com","type":"work"}],"EnterpriseUser":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

Documentation needs to be updated with the correct details. Created a separate doc issue https://github.com/wso2/product-is/issues/4973.
