### ISSUE TITLE
Should not allow to reset the password when user provides the initial password as the new password with SCIM2/Me

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4939]
**Suggested Labels**
Affected : 5.8.0- alpha3
Severity: Major
Priority: High
Component: SCIM2
Type-Improvement

Environment
Linux, JDBC Userstore

**Steps to reproduce the issue**

1. Create a user with below command 

`curl -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"alex","password":"alexwso2","emails":[{"primary":true,"value":"alex.j@gmail.com","type":"home"},{"value":"alex_j@wso2.com","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Me`

2. Assign the created user with a role that contain login permission
3. Update the users password with below command using a PUT request 

`curl -v -k --user alex:alexwso2 -X PUT -d '{"schemas":[],"name":{"familyName":"JacksonJohnoo","givenName":"Kimoo"},"userName":"alex","password":"alexwso2","emails":[{"primary":true,"value":"alex.j@gmail.com","type":"home"},{"value":"alex_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://is580.qa.com:443/scim2/Me`

Allows to send the request to update the users password by providing the initial password again.

Should notify for the user in the response that he cant use the same password as the new password that he is going to set 

Response 

```
* upload completely sent off: 233 out of 233 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.7.11
< Date: Wed, 03 Apr 2019 14:48:33 GMT
< Content-Type: application/scim+json
< Content-Length: 671
< Connection: keep-alive
< Cache-Control: private
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Location: https://is580.qa.com/scim2/Users/5a1873d5-6f02-41f5-9876-8d9e3378ffa5

```

**Comment by nilasini** [comment]
@ShanikaWickramasinghe we can use the same password as the new password unless we configure password history feature. Hence it is not a bug.

**Comment by ShanikaWickramasinghe** [comment]
Shall we open this issue as a doc gap. Because I could not find any SCIM requests on Password reset via SCIM. Eventhough there is a general command given for user update in [1]. I observed several people are looking over stackoverflow as well to find right commands for password reset with wso2 IS via SCIM as in [2][3]

We can include these information in the doc also creating a link for the doc [4] which specify about pw history validation from the place where those commands are mentioned. Then users will clearly understand if they want to enable password history validation they have to enable that as a separate feature. Fresh user is impossible to identify the link for this doc [4] if they don't know that they have to enable it as a separate feature .

[1]. https://docs.wso2.com/display/IS570/apidocs/SCIM2-endpoints/#!/operations#MeEndpoint#createUserMe
[2]. https://stackoverflow.com/questions/45558895/wso2-scim-password-reset
[3]. https://stackoverflow.com/questions/51072415/wso2-scim2-password-change
[4]. https://docs.wso2.com/display/IS580/Password+History+Validation
