### ISSUE TITLE
Can not set challenge answers of tenant user as the tenant admin

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#4942]
Steps to reproduce
1. IS 5.6.0 latest update
2. Create a tenant and create a tenant user in that.
3. Use **ChallengeQuestionManagementAdminService** service and try to set challenge answers for the tenant user. Authenticate the service as the tenant admin.
4. Will fail with the log saying admin can not change the user challenge answers.

Reason
`
String tenantAwareUserName = MultitenantUtils.getTenantAwareUsername(user.getUserName());
..
boolean isAuthorized = isUserAuthorized(tenantAwareUserName, tenantDomain);
`
We are checking if the same tenant user is authorized. Instead this should be the authenticated user in the carbon context.

This is fixed in IS 5.7.0 latest update.

**Comment by ayshsandu** [comment]
Fixed as a WUM update for 5.6.0

**Comment by ayshsandu** [comment]
Same as https://github.com/wso2/product-is/issues/3871
