### ISSUE TITLE
'isPaginatedUserStoreAvailable()' property should not be available after IS-5.8.0

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#4943]
The 'isPaginatedUserStoreAvailable()' property use to deviate to the legacy APIs in SCIM. However after IS-5.8.0, these legacy APIs won't be used. Therefore after the release IS-5.8.0, this property won't be available.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
