### ISSUE TITLE
[Doc] Update the migration documentation

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#4945]
Update the migration docs by including changes introduced in wso2/product-is/issues#4776.
Here we introduced an additional column **"ASSERTION"** (type: Blob) to **IDN_SAML2_ASSERTION_STORE** table.

Refer to wso2/product-is#4776

There are three scenarios that can be affected by this implementation

- IS 5.8.0 is used along with the modified database schema
- IS 5.8.0 is pointed to an old database where IDN_SAML2_ASSERTION_STORE table doesn't have this additional column. In this case, we will be checking if this additional column exists and act accordingly.
- User migrates to the new version

**Comment by Abilashini** [comment]
This has been included in 5.8.0 migration script
