### ISSUE TITLE
ArrayIndexOutOfBoundsException for the request to /oauth2/userinfo without providing the access token 

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/product-is#4947]
**Suggested Labels:**
Affected: 5.3.0
Severity: Major
Type-Bug

**Environment:**
Linux, JDK 1.8.0_121

**Steps to reproduce the issue:**
1. Start the server.
2. Request the following curl command.

> curl -k -H "Authorization: Bearer " https://localhost:9443/oauth2/userinfo?schema=openid

This will respoce Internal Server Error (500) to the request and folllowing logstrace will be available on wso2carbon.log file. This exception need to be handle and respoce with a  error meesage.

> Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
> 	at org.wso2.carbon.identity.oauth.endpoint.user.impl.UserInforRequestDefaultValidator.validateRequest(UserInforRequestDefaultValidator.java:93)
> 	at org.wso2.carbon.identity.oauth.endpoint.user.OpenIDConnectUserEndpoint.getUserClaims(OpenIDConnectUserEndpoint.java:65)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)

**Comment by Buddhimah** [comment]
The issue cannot be reproduced in wso2is-5.8.0-alpha5
