### ISSUE TITLE
Exception when user try to Encrypt keystore & truststore Passwords  with Cipher Tool for updated trustore  & keystore password

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#4953]
Steps to reproduce : 
1.Navigate to wso2 server location:
IS_HOME/repository/resources/security

2. Change keystore password: keytool -storepasswd -new [new keystore password] -keystore [keystore name]
3. Change Private Key password : keytool -keypasswd -alias wso2carbon -keystore 
wso2carbon.jks  
4. Change truststore password: keytool -storepasswd -new [new truststore password] -truststore [keystore name]
****Important : should be new keystore password not equal new truststore password**
5. keytool -keypasswd -alias wso2carbon -keystore wso2carbon.jks  
6.Change carbon.xml at @wso2_server/repository/conf
7.Change identtity.xml at @wso2_server/repository/conf
8. Change catalina-server.xml at  the @wso2_server/repository/conf/tomcat/
9.Change EndpointConfig.properties at the @wso2_server/repository/conf/identity

10. Encrypt Passwords (keystore & truststore)with Cipher Tool in EndpointConfig.properties at the @wso2_server/repository/conf/identity
***Steps to Encrypt Passwords (keystore & truststore)with Cipher Tool in EndpointConfig.properties
@wso2_server/bin sh ciphertool.sh, with this encypt both plin text which we provied for keystore & truststore
12. Update the EndpointConfig.properties with encrypted passwods 
 follow step 11 in Encrypting Passwords with Cipher Tool[1] document.
13.Restart the WSO2 server.

[1] https://docs.wso2.com/display/ADMIN44x/Encrypting+Passwords+with+Cipher+Tool#EncryptingPasswordswithCipherTool-manual_processEncryptingpasswordsmanually

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
