### ISSUE TITLE
post_logout_redirect_uri	should be marked as optional parameter

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#4954]
Already updated following doc,
https://docs.wso2.com/display/IS570/OpenID+Connect+Logout+URL+Redirection

Created this issue to track the change & update docs of other versions like,
https://docs.wso2.com/display/IS560/OpenID+Connect+Logout+URL+Redirection

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
