### ISSUE TITLE
Role mappings not working properly. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#4957]
1. Configure inbound SAML SP
2. Outbound SAML IDP. 
3. Configure role mappings. (IDP role name test to test123 local role)
4. Enable JIT provisioning.
5. check the role list of the provisioned user. 

Roles are not provisioned properly. 

![image](https://user-images.githubusercontent.com/8455535/55584705-7c841600-5742-11e9-85f3-d0015c583536.png)

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/carbon-identity-framework/pull/2164
