### ISSUE TITLE
Password Recovery via Email Notify as Password details sent when trying to recover password for non existing usernames

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#4962]
**Suggested Labels**
Affected : 5.8.0- alpha3
Severity: Major
Priority: Highest
Component: Password Recovery
Type-Bug

**Environment**
Linux, Embedded LDAP UserStore,

**Steps to Reproduce the issue**

1. Followed [1] for password recovery using user portal
2. A user mistakenly provide a wrong username (non existing username) when try to recover the password via Email

Observation

UI still shows the notification as below even though there is no user exist in the system for that username

![recovery1](https://user-images.githubusercontent.com/31848014/55605527-99483a00-5792-11e9-8b62-38252df4c0ef.png)

Carbon console error is given as user does not exist

`[2019-04-05 13:45:07,635] ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.RecoverPasswordApiServiceImpl} -  Unable to find an user with username: test1237888 in the system.`

[1]. https://docs.wso2.com/display/IS580/Password+Recovery

**Comment by madurangasiriwardena** [comment]
This is the expected behavior to avoid account enumeration IMO.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
