### ISSUE TITLE
Enable Self User Registration checkbox reset to default while adding a purpose

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#4965]
**Suggested Labels:**

- Complexity/Low
- Priority/High
- Severity/Critical
- Type/UX

**Stes to reproduce**

1. Enable `Enable Self User Registration` under residentIdp -> User Self Registration
2. Without doing anything, add a Self-Sign-Up purpose
3. Once the purpose is added, user redirected to the `User Self Registration` configurations. Here the enabled checkbox in step 1 is unchecked

**Comment by DonOmalVindula** [comment]
Closing as it's no longer applicable.
