### ISSUE TITLE
Update scim2 extension EnterpriseUser name change in migration doc

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#4967]
We have updated 'EnterpriseUser' attribute name in <IS_HOME>/repository/conf/scim2-schema-extension.config to "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" in order to achieve spec compliancy. Please refer https://github.com/wso2/product-is/issues/3487. We need to mention this change in the migration document and if the users need to use the old attribute name, they can simply change the attribute name in scim2-schema-extension.config file.

**Comment by sherenewso2** [comment]
This has been documented in the migration guide [1]
[1] https://docs.wso2.com/display/IS580/Understanding+What+Has+Changed

**Comment by danijelt** [comment]
All documentation, even the new one for IS 5.9.0, still uses "EnterpriseUser" in API call examples. (This caused me to waste a significant amount of time.)
