### ISSUE TITLE
Add ability to disable hostname verification for the calls made from HTTPClient within the IS

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#4968]
Relates to: https://github.com/wso2/product-is/issues/4940

We need to fix this for all the places apart from the place mentioned in the above-mentioned issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
