### ISSUE TITLE
A created IDP's saml authenticator can have the same IDPEntityId as the resident IDPs saml authenticator

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#4971]
A created IDP saml authenticator can have the same IDPEntityId as the resident IDPs saml authenticator. This happens because the resident IDP has a saml authenticator with the name "samlsso" when we create IDPs the saml authenticator name is "SAMLSSOAuthenticator".

This will be a problem in cases like the saml bearer grant where it cannot pick the proper IDP based on the IDPEntityId.

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/04198ac315e660cf93278c9e18c489818ff6fe22/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/saml/SAML2BearerGrantHandler.java#L800-L818

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
