### ISSUE TITLE
Implicit Flow - at_hash: empty

### ISSUE THREAD

**Issue by antonigiovanniello** [wso2/product-is#4972]
Hello, by authenticating with Angular webApp
and WSO2 IS 5.6.0 setting OAuth / OpenID Connect Configuration,
the at_hash field is not set by the server, which is mandatory for the Implicit type request.

angular-auth-oidc-client.js: 647 STS server: https: // localhost: 9443 / oauth2 / oidcdiscovery
angular-auth-oidc-client.js: 647 IsAuthorizedRace: Silent Renew Not Active. Issue.
angular-auth-oidc-client.js: 647 IsAuthorizedRace: completed
angular-auth-oidc-client.js: 647 getIsAuthorized: false
angular-auth-oidc-client.js: 647 BEGIN authorizedCallback, no authentication data
home.component.ts: 38 userData receiving data
angular-auth-oidc-client.js: 647 getIsAuthorized: false
Angular-auth-oidc-Client.js: 647 {access_token: "e046acdc-6e48-311a-b6e5-9a22277cf50d" id_token: "... eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0 YrwkFRijHuiyPU_bJM5GXLSmSEjIUJG9pLrQXClik8gOYWi9A" say: "15,506,789,473,230.5280966452301199" token_type: "bearer" expires_in: "3600", ...}
angular-auth-oidc-client.js: 647 authorizedCallback created, token validation begins
angular-auth-oidc-client.js: 647 jwks_uri: https: // localhost: 9443 / oauth2 / jwks
client: 77 [WDS] Replacement of hot module enabled.
angular-auth-oidc-client.js: 647 validate_id_token_iat_max_offset: 2948 <20000
angular-auth-oidc-client.js: 647 Token not expired?: 1550682642000> 1550679044953 (true)
angular-auth-oidc-client.js: 647 at_hash from the server: not defined

Does anyone have the same problem?

**Comment by tharindu-bandara** [comment]
This issue has been fixed in the current master branch with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/909, thus closing the issue.
