### ISSUE TITLE
Ask password using SCIM doc needs to be updated

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#4973]
For the **askPassword** feature, email is a mandatory attribute. As for the default IS configs the email claim and the relevant scim claim mapping would be as below,

`http://wso2.org/claims/emailaddress -> urn:ietf:params:scim:schemas:core:2.0:User:emails`

Therefore you need to send the email address as below in the user creation request,

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com"}],"EnterpriseUser":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

Or else you have to map the `http://wso2.org/claims/emailaddress` claim to relevent scim claim as below,

<img width="1140" alt="Screen Shot 2019-04-05 at 5 36 42 PM" src="https://user-images.githubusercontent.com/13478571/55626544-75ecb180-57c9-11e9-8033-69b740f01882.png">

Then you can use the below request as well,

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"Smith","givenName":"Paul"},"userName":"Paul","password":"password","emails":[{"primary":true,"value":"dewmi123455@gmail.com","type":"home"},{"value":"dewmi123455@gmail.com","type":"work"}],"EnterpriseUser":{askPassword:"true"}}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

This need to be clearly communicated in the documentation as the sample request provided in the doc [1] is not working with the default claim configs. So better to change the sample request as suggested above.

[1] https://docs.wso2.com/display/IS580/Creating+Users+using+the+Ask+Password+Option

**Comment by sherenewso2** [comment]
Updated the request in versions 5.5.0 - 5.8.0 [1] 

[1] https://docs.wso2.com/display/IS580/Creating+Users+Using+the+Ask+Password+Option
