### ISSUE TITLE
[UX] "Disable SMSOTP" in user dashboard should be a checkbox, not a text field

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#4976]
As an end-user, it's relatively unclear how to use this & a checkbox would be greatly preferred:

![Screen Shot 2019-04-05 at 4 16 56 PM](https://user-images.githubusercontent.com/1661988/55657002-7f245100-57be-11e9-8d4e-3100ffc3480b.png)

**Comment by DonOmalVindula** [comment]
Closing as it's no longer applicable.
