### ISSUE TITLE
Why is there 5.3.0 M1 after 5.2.0 beta?

### ISSUE THREAD

**Issue by ppawel** [wso2/product-is#498]
Is there going to be 5.2.0 release or are you going straight to 5.3.0? We are waiting for a release that has working multi-tenancy and a non-broken OAuth userinfo endpoint - that eliminates 5.0 and 5.1... 

With 5.2 beta those two features look OK but now you switched to 5.3? What is your release road map?

**Comment by darshanasbg** [comment]
Hi   @ppawel,

There will be two releases Identity Server 5.2.0 and Identity Server 5.3.0. Identity Server team is working partially on both releases. KIT with the dev@wso2.com for release notices.
