### ISSUE TITLE
[Doc] Update URLs of the consent management extension point samples

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-is#4981]
Update URLs of the below consent management extension point samples. (Refer [this](https://docs.wso2.com/display/IS570/Using+the+Consent+Management+REST+APIs) page)

**PIIController Connector Extension**

Current URL - https://github.com/wso2/samples-is/tree/master/consent-mgt/piicontroller/org.wso2.carbon.identity.piicontroller
Correct URL - https://github.com/wso2/samples-is/tree/product-is3289/consent-mgt/piicontroller/org.wso2.carbon.identity.piicontroller

**Interceptor Extension**

Current URL - https://github.com/wso2/samples-is/tree/master/consent-mgt/interceptor
Correct URL - https://github.com/wso2/samples-is/tree/product-is3289/consent-mgt/interceptor

(Refer below image regarding where this needs to be updated)

![image](https://user-images.githubusercontent.com/9979373/55697626-c50c2f80-59df-11e9-9ce2-179671012cc6.png)

**Comment by sherenewso2** [comment]
Fixed in versions 5.5.0 - 5.8.0 

[1] https://docs.wso2.com/display/IS580/Using+the+Consent+Management+REST+APIs
