### ISSUE TITLE
Can not configure a SAML service provider in a IS run on a Windows OS

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#4982]
IS Latest WUm 5.7.0  on Windows server with JDK 1.8.

When starting as a service with YAJSW and try to access SAML configs of a service provider, the below issue can be seen.

 ERROR {org.apache.catalina.core.ApplicationDispatcher} -  Servlet.service() for servlet bridgeservlet threw exception
FINEST|4444/0|"WSO2 Carbon"|19-04-08 03:21:58|java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by org.wso2.carbon.identity.sso.saml.ui_5.4.22
INFO|wrapper|"WSO2 Carbon"|19-04-08 03:21:58|Trigger found: Exception in line:
INFO|wrapper|"WSO2 Carbon"|19-04-08 03:21:58|java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by org.wso2.carbon.identity.sso.saml.ui_5.4.22
INFO|wrapper|"WSO2 Carbon"|19-04-08 03:21:58|start script scripts/trayMessage.gv
FINEST|4444/0|"WSO2 Carbon"|19-04-08 03:21:58|  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
INFO|wrapper|"WSO2 Carbon"|19-04-08 03:21:58|end script scripts/trayMessage.gv

**Comment by malithie** [comment]
@LahiruLS , @JKAUSHALYA ,
Is this fixed in public?
Could you please point the public PR

**Comment by LahiruLS** [comment]
PR:  https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/224

**Comment by LahiruLS** [comment]
Public fix: https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/227
