### ISSUE TITLE
In SCIM2 single attribute filtering, results are sorted before pagination, causing false results.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#4984]
In SCIM2 single attribute filtering, results are paginated after fetching all the results. These results are paginated in a single method and they are sorted before pagination process begins. Due to this sometimes the primary user store results comes second to secondary user store results. This happens due to sorting according to the alphabetical order. This needs to be fixed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
