### ISSUE TITLE
[Doc] Update "Hosting Authentication Endpoint on a Different Server" doc for IS 5.7.0

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#4990]
The jars mentioned in the doc in [1] are complying to IS 5.3.0. This needs to be updated with the relevant jars in IS 5.7.0.

[1]https://docs.wso2.com/display/IS570/Hosting+Authentication+Endpoint+on+a+Different+Server

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
