### ISSUE TITLE
When reCaptcha is enabled, multi option login steps are not shown for given number of failed attempts.

### ISSUE THREAD

**Issue by jan1tha** [wso2/product-is#4992]
- Add a Service Provider (OIDC/SSO samples)
- Enable reCaptcha (after 1 failed login)
- Enable multi-option login (eg: basic auth as step 1 and Email OTP as step 2)
- Add a new claim to store the failed attempts before login.
- Use script based adaptive authentication and added the following code.

```
// This variable is used to define the number of invalid attempts allowed before prompting the second factor
var invalidAttemptsToStepup = 2;

var failedLoginAttemptsBeforeSuccessClaim= 'http://wso2.org/claims/identity/failedLoginAttemptsBeforeSuccess';

function onLoginRequest(context) {
	doLogin(context);
}

function doLogin(context) {
  executeStep(1, {
    onSuccess : function(context){
      var user = context.steps[1].subject;
      if (isExceedInvalidAttempts(user)) {
   	 executeStep(2);
      }
    },
    onFail : function(context) {
      // Retry the login..
      doLogin(context);
    }
  });  
}

function isExceedInvalidAttempts(user) {
  if (user.localClaims[failedLoginAttemptsBeforeSuccessClaim] >= invalidAttemptsToStepup) {
    return true;
  } else {
    return false;
  }
}
```
When reCaptcha is set to come up after 1 failed login attempt and Email OTP to come up after 2 failed login attempts, to get E-mail OTP (which is set as the 2nd step) it takes 5 or more invalid login attempts.

**Comment by vihanga-liyanage** [comment]
@pulasthi7 @IsuraD Can you please have a look?

**Comment by Buddhimah** [comment]
The issue does not reproduce in the IS 5.8 alpha 6. http://wso2.org/claims/identity/failedLoginAttemptsBeforeSuccess this claim is used to check this issue. after the configured number of exceeded invalid attempts step 2 which is the email otp executed .

**Comment by nilasini** [comment]
Related issue 
https://github.com/wso2/product-is/issues/5034

**Comment by Buddhimah** [comment]
This issue reproduced in IS-5.8 Beta-3 . This reproduces only when ReCaptcha is enabled. The claim does not properly get updated. If we configured to prompt ReCaptcha after 3 failed attempts. Then  if the user gives wrong credentials and correct Recaptcha then it will not ask for recaptcha in the next login attempt. So that does not count as a attempt in the claim.
