### ISSUE TITLE
Add new index to IDN_UMA_RESOURCE table

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#4996]
Following index was added to 5.8.0

`CREATE INDEX IDX_USER_RID ON IDN_UMA_RESOURCE (RESOURCE_ID, RESOURCE_OWNER_NAME, USER_DOMAIN, CLIENT_ID);`

Refer PR: https://github.com/wso2-extensions/identity-oauth-uma/pull/50

**Comment by janakamarasena** [comment]
This is available in IS580 migration.
