### ISSUE TITLE
Twillio SMS provider's error codes are not returned properly.

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#5002]
When we configure Twilio SMS provider for SMS OTP and provide a well-formed and invalid phone number, Twilio SMS provider returns a "400 Bad Request"  HTTP Response with the body containing the error code and error message from Twilio. 

Currently, we are only returning the response code and reason phrase returned in status line of the HTTP response. As in https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/v2.0.15/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPAuthenticator.java#L888

```
context.setProperty(SMSOTPConstants.ERROR_CODE, 
httpConnection.getResponseCode() + " : " + httpConnection.getResponseMessage());
```

This issue faced here is the end user is displayed with a error page without proper information on the actual error occurred as the following.

```
 TID[-1234] [IS] [2019-03-29 17:25:25,308] ERROR {org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator} - Error while sending SMS: error code is 400 and error message is BAD REQUEST 
```

Twilio has a set of error codes and error messages defined and sent in the body with "400 Bad Request" status line. https://support.twilio.com/hc/en-us/articles/223181868-Troubleshooting-Undelivered-Twilio-SMS-Messages. 

A sample response will look like this

```
<html>
<head>
   <title>400 Bad Request</title>
</head>
<body>
   <h1>Bad Request</h1>
   <p>Error Code</p>
   <p>Error Message</p>
</body>
</html>
```
We might need to modify the logic to fetch the error code and error message from the body and pass it to the end-user for better useability. 

**Steps to reproduce :** 
- Setup a SMS OTP with IS-5.6.0 https://docs.wso2.com/display/IS560/Configuring+SMS+OTP#ConfiguringSMSOTP-Configuringtheidentityprovider
- Provide the mobile number as "1111111111" 
- Try to authenticate using SMS OTP

**Comment by hauntingEcho** [comment]
as a further driver, the reason string (which is currently used by IS) is dropped entirely from HTTP/2: https://tools.ietf.org/html/rfc7540#section-8.1.2.4
