### ISSUE TITLE
Remove duplicated jars in webapp lib of IS connectors packed in the product

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#5003]
The following IS connectors packed in product IS have jars in their WEB-INF>lib folders that are also in the plugins folder. These duplicated jars have to be removed from the webapp lib folder of each connector. 
- emailotpauthenticationendpoint
- smsotpauthenticationendpoint
- totpauthenticationendpoint
- x509certificateauthenticationendpoint

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
