### ISSUE TITLE
Need to have a way to show newly added requested claims to consent page

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5004]
Need to consider the $subject because if the identity admin add new requested claims currently there is no way to show the consents for the new requested claims to the user.

**Comment by nilasini** [comment]
Currently, without this improvement, we could achieve the use case using \[1]

\[1] https://github.com/wso2/product-is/issues/2985#issuecomment-374506227

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
