### ISSUE TITLE
File.separator need to be removed from getResource(..) method in TomcatInitializerTestCase

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5007]
In TomCatInitializerTestCase, File.separator is used inside getResource(..) method.

```
URL resourceUrl = getClass()
        .getResource(File.separator + "samples" + File.separator + application + ".war");
```
[TomcatInitializerTestCase, Line78](https://github.com/wso2/product-is/blob/master/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/base/TomcatInitializerTestCase.java#L78)

Integration tests in windows environment fail due to this line of code.

The reason for the above is that the classloader takes care of loading the resource in platform independent way (unlike Files (java.io) api which is bound to system).

So this file.separator (which is platform dependent) should be removed.

**Comment by malithie** [comment]
Closing as fixed
