### ISSUE TITLE
User will give an optional claim value during sign-up, but not give consent to store it

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#5010]
During the user self-registration, consent to store claim values for required purposes are shown. The user is allowed to enter claim values here.

![Screenshot from 2019-04-09 14-31-51](https://user-images.githubusercontent.com/22551445/55788191-7b057580-5ad5-11e9-8ebf-5eec9ff3ce7f.png)

But if the consent to store claim value is optional, it is unclear how WSO2 IS handles the scenario if the user enters the claim value but do not give consent for it, from the UI.

**Comment by tharindu-bandara** [comment]
Need to evaluate the possibility for the frontend validation during this effort, as mentioned [here](https://github.com/wso2-extensions/identity-governance/pull/284#issuecomment-480814017)[1].

[1] https://github.com/wso2-extensions/identity-governance/pull/284#issuecomment-480814017

**Comment by DonOmalVindula** [comment]
Closing as it's no longer applicable.
