### ISSUE TITLE
Single Logout passes empty NameId from IS-KM to the external IdP 

### ISSUE THREAD

**Issue by selakap** [wso2/product-is#5012]
**Description**
Single Logout passes empty NameId from IS-KM to the external IdP when log out proceed as follows.

- Access Publisher Portal, Login there
- Access Store Portal (logged automatically thanks to SSO)
- Logout from Store Portal (which is not the login entrypoint, Publisher portal was) 

or

- Access Store Portal, Login there
- Access Publisher Portal (logged automatically thanks to SSO)
- Logout from Publisher Portal (which is not the login entrypoint, Store portal was)

**Steps to reproduce**
- Configure External IDP through Identity Server (IS-KM) for SSO with SLO
- Access Store Portal, Login there
- Access Publisher Portal (logged automatically thanks to SSO)
- Logout from Publisher Portal (which is not the login entrypoint, Store portal was)
- Observe 500 internal server error
- Using saml trace, observe the empty nameID from IS-KM to external IDP

**Effected versions**
IS-KM 5.7.0

**Comment by malithie** [comment]
@JKAUSHALYA , @mefarazath ,
Is this fixed

**Comment by wijith7** [comment]
This is fixed with https://github.com/wso2/carbon-identity-framework/pull/2137
