### ISSUE TITLE
Claims mappings are not reflected in other nodes when ForceLocalCache is used.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5015]
Step a cluster with two or more nodes. Configure ForceLocalCache to true in carbon.xml file.

1. List all claims from node1.
2. List all claims from node2.
3. Add a new claim from node1.
4. Go to node2 and list claims. 

In the step4. the newly added claim in step4 will not be visible in node2.

**Comment by malithie** [comment]
@LahiruLS , @JKAUSHALYA ,
Can you point the public PR here

**Comment by LahiruLS** [comment]
@malithie This functionality has been moved to identity-framework from IS 5.3.0 on. Please refer to this pull https://github.com/wso2/carbon-identity-framework/pull/697.
