### ISSUE TITLE
'SignJWTWithSPKey' enabled by default in the product

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#5016]
Along with the fix for https://github.com/wso2/product-is/issues/4722 we have decided to set the 'SignJWTWithSPKey' to true by default in <IS_HOME>/repository/conf/identity/identity.xml file in 5.8.0 onwards. When this config is enabled JWTs issued from IS will be signed with the keystore belonging to service provider's keystore. In older version default behavior was to get the keystore of authorized user's tenant domain. In the migration doc we need to mention this change of behavior and if they need to switch back to old behavior then they need to add the following two properties to <OpenIDConnect> tag in <IS_HOME>/repository/conf/identity/identity.xml file in order to fix the above mentioned issue. 

```
<AddTenantDomainToIdToken>true</AddTenantDomainToIdToken>
<AddUserstoreDomainToIdToken>true</AddUserstoreDomainToIdToken>
```

**Comment by sherenewso2** [comment]
This has been documented in the 5.8.0 migration guide [1] 

[1] https://docs.wso2.com/display/IS580/Understanding+What+Has+Changed
