### ISSUE TITLE
Disabling tenantList won't disable mutualSSLManager in EndpointConfig.properties

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5024]
If we set `tenantListEnabled=false` in the `EndpointConfig.properties` file, still it tries to initialize the MutualSSLManager. Then, we have to add `mutualSSLManagerEnabled=false` avoid this.

As this MutualSSLManager is only used with tenant list feature, `tenantListEnabled=false` should avoid initializing the MutualSSLManager as well.

Related issue: https://github.com/wso2/carbon-identity-framework/issues/2039

**Comment by SiluniPathirana** [comment]
The above issue still not fixed in IS 5.10.0 and APIM 3.1.0 Shall we take a step to fix this

**Comment by rksk** [comment]
Mutual SSL is used for other REST API invocations as well in the later versions. So, now we cannot disable it once tenantList is disabled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
