### ISSUE TITLE
All the query params in "Additional Query Parameters" of federated oauth/openid connect IDP config is not visible in management console

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#5027]
Add space separated multiple scopes in additional query parameters of fed authenticator configs.
scope=openid profile vo fed rrn 
Save and view again. few values are missing as below.
scope=openid

Same issue reported in : [https://wso2.org/jira/browse/IDENTITY-6736](https://wso2.org/jira/browse/IDENTITY-6736)

IS - 5.1.0

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2-support/carbon-identity/pull/323

**Comment by ayshsandu** [comment]
Additional fixes in https://github.com/wso2-support/carbon-identity/pull/324

**Comment by ayshsandu** [comment]
Fixed in master with https://github.com/wso2/carbon-identity-framework/pull/2181
