### ISSUE TITLE
Properties to be enabled for tenant OIDC logout

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#5028]
In 5.8.0 'SignJWTWithSPKey' property will be set to true by default. Please refer https://github.com/wso2/product-is/issues/4722. Enabling this property will use the keystore of service provider's tenant when signing and validating id tokens. If user wants to make this property to false, in order to sign/validate tokens with keystore of user's tenant domain, they have to set the following two properties to true in <IS_HOME>/repository/conf/identity/identity.xml 

```
<AddTenantDomainToIdToken>true</AddTenantDomainToIdToken>
<AddUserstoreDomainToIdToken>true</AddUserstoreDomainToIdToken>
```

**Comment by ayshsandu** [comment]
These configuration has not been templated for the new configuration model.

**Comment by janakamarasena** [comment]
The configurations are templated from IS-5.9.0 onwards

```
[oauth.oidc.id_token]
add_tenant_domain_to_realm = "true"
add_userstore_domain_to_realm = "true"
```
