### ISSUE TITLE
[DOC][IS530] Configuring token expiry time per service provider

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5030]
There are Service Provider level configurations for configuring "token expiry times" and "refresh token renewal per request" in IS530.  This needs to documented.

**Comment by nilasini** [comment]
@janakamarasena Is it only missing in 5.3.0?

**Comment by janakamarasena** [comment]
@nilasini not sure on that... Also not sure what other versions have this particular configuration

**Comment by nilasini** [comment]
Seems like it is there in 5.3.0. Could you please recheck and confirm?
![validity](https://user-images.githubusercontent.com/20336761/55859739-4c98a080-5b90-11e9-8ae6-8f235a47c9a9.png)

**Comment by janakamarasena** [comment]
Hi @nilasini looks like its there in the doc[1] we only need to add the "refresh token renewal per request" config. Thanks for pointing it out.

The configuration part is located under
**Configuring Inbound Authentication for a Service Provider**  
\> **OAuth/OpenID Connect Configuration** 
  \>> **Defining access token validity period** 
    \>>> **Defining access token validity period per service provider**

[1] - https://docs.wso2.com/display/IS530/Configuring+Inbound+Authentication+for+a+Service+Provider

@YvonneW can you please do the needful.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
