### ISSUE TITLE
Missing index in IDN_OAUTH_CONSUMER_APPS table

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5031]
We need to add the below index on IDN_OAUTH_CONSUMER_APPS table

`CREATE INDEX IDX_IDN_OAUTH_CONSUMER_APPS ON IDN_OAUTH_CONSUMER_APPS(USERNAME,TENANT_ID,USER_DOMAIN, APP_NAME)`

When an OAuth application is created through DCR or through Management console, the OAuthApplicationMgtListener checks whether there is an already existing app with the same name at [1]. Without the index its a sequential search on the  IDN_OAUTH_CONSUMER_APPS. With the increase in the number of OAuth apps in IDN_OAUTH_CONSUMER_APPS table, this causes performance degradation and high CPU usage on the DB server. 

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/ca4690d734709b108ef2df33a69ae3c9242febc8/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L553

**Comment by mefarazath** [comment]
These changed need to be added to the migration client as well..

**Comment by malithie** [comment]
Created [1] to track the fix for migration client.
Closing this as this is fixed
