### ISSUE TITLE
Page redirection  fail once the user cancel the JIT provitiong with responding to the security warning message

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#5032]
Affected: 5.8.0-Alpha6
Severity: Major
Priority: Normal
Component: User Mgt
Type: bug

Once user cancel the given warning message while  JIT provisioned user association scenario, not redirect to the application home page. Given post button also not responding.

Steps: 
01. User Configure IDP, JIT provisioning and google federate authentication [1] [2] 
02. User configure federate authentication with Google  for the travelocity SP
03. User access the travelocity home page and navigate to google logging page
04. User enter google credentials and click login button
05. User receive the warning message (Image 01) and click cancel button
06. Once user user not redirect to travelocity home page user click post button also. [image 2]

Expected result:
User have to redirect to the travelocity home page by click the cancel button or post button

Actual result:
Redirection fail

Image 01:
![image](https://user-images.githubusercontent.com/39077751/55858332-0d1c8500-5b8d-11e9-98d0-ffd6508ea4e0.png)

Image 02: 
![image](https://user-images.githubusercontent.com/39077751/55858373-2de4da80-5b8d-11e9-850b-640b1fad15a9.png)

[1] https://docs.wso2.com/display/IS580/Configuring+Just-In-Time+Provisioning+for+an+Identity+Provider
[2] https://docs.wso2.com/display/IS580/Configuring+Just-In-Time+Provisioning+for+an+Identity+Provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
