### ISSUE TITLE
Avoid additional service call / DB lookup during DCR App creation flow

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5035]
In our current DCR app creation flow when an app create request is sent

1. We create the OAuth App using OAuthAdminService.registerOAuthApplicationData() method
2. Validate whether the app is created using OAuthAdminService.getOAuthApplicationDataByAppName() method.
(https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/a2e9b5ea35c0a77ffd6112b652511ac4723e2329/components/org.wso2.carbon.identity.oauth.dcr/src/main/java/org/wso2/carbon/identity/oauth/dcr/service/DCRMService.java#L362-L389)

Instead, we can use OAuthAdminService.registerAndRetrieveOAuthApplicationData() which does both the above in one service call.

**Comment by vihanga-liyanage** [comment]
@mefarazath did we add this fix to master as well?

**Comment by mefarazath** [comment]
> @mefarazath did we add this fix to master as well?
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1115
