### ISSUE TITLE
[Doc] Audit logs for claims

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5036]
Introduced a filtering mechanism to display selected claims as audit logs. To enable that you should enable the following listener and loggable claims. Here loggable claims can be one or more claims. The claims which are mentioned as loggable claims will be logged in the audit log.

```
<EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.user.mgt.listeners.UserClaimsAuditLogger"
                       orderId="9" enable="false"/>
```

Uncomment the loggable claims and add the preferred claims.
```
 <LoggableUserClaims>
        <LoggableUserClaim>http://wso2.org/claims/identity/accountLocked</LoggableUserClaim>
        <LoggableUserClaim>http://wso2.org/claims/role</LoggableUserClaim>
    </LoggableUserClaims>
```

**Comment by sherenewso2** [comment]
Closing this as it has been documented in [1] now. 

[1] https://docs.wso2.com/display/IS580/Logging+Claims+in+Audit+Logs
