### ISSUE TITLE
Audit logs should be handled properly

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5037]
Extracted from the issue \[1]

WSO2 Identity Server is lacking important audit logs which we have to fix. Need to find out all the places where audit logs are needed and fix those places.

- Disable existing audit logs based on a property
- [x] Kernel
- [x] Framework
- [x] Governance

We are introducing a new format for the audit logs.
In order to make these changes backward compatible a system property will be introduced.

This is the deployment.toml config to disable legacy audit logs. The default value for the disableLegacyAuditLogs is set to true once the new audit logs are added to every component.
```
[system.parameter]
disableLegacyAuditLogs=true
```
We don't support printing old/new audit logs. The user has to decide which logs to be printed and configure accordingly.

![logpublishing module](https://user-images.githubusercontent.com/25483865/130066476-a29732e6-5cdb-429d-9a99-3f8f33e25705.jpg)

- Add new audit logs

- [x]  Application Mgt - https://github.com/wso2/carbon-identity-framework/pull/3674
- [ ] IDP Mgt
- [x] User Mgt
- [ ] Group Mgt
- [ ] Role Mgt

[1] https://github.com/wso2/product-is/issues/4991

**Comment by piraveena** [comment]
We have done few improvements in the AuditLog model from this PR https://github.com/wso2/carbon-kernel/pull/3600/files. This has following API changes.
1. Removed setters
2. Removed EventCatalog class
3. Moved to Builder pattern
4. Type of `recordedAt` changed to String from Instant
5. Type of `data` changed to String to Map, and the name changes to `dataChange` to `data`
6. Name of `logId` changed to `id`
7. Name of `correlationId` changed to `requestId`
8. Removed `initiatorName` and `targetName`
9. Removed `clientComponent`
