### ISSUE TITLE
Implement Logic to Pick Default Token Issuer.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5038]
We need to implement a proper logic to pick a default token identifier in https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L2922

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
