### ISSUE TITLE
[OB] Need to configure the kid value of token response

### ISSUE THREAD

**Issue by imesh94** [wso2/product-is#5042]
IDTokens built by the default IDToken builder gives kid values based on SHA-1 DER thumbprint, but UK Directory specification specifies this should be SHA-1 JWK Thumbprint[1].
In order to aachieve the requirement (issue [2]), there should be a method to externally assign the kid value when signing the JWT, or a configuration to define on which thumbprint generation logic the kid value is assigned.

[1] - [https://openbanking.atlassian.net/wiki/spaces/DZ/pages/131236509/The+Open+Banking+Directory+-+v1.2 ](url)

[2] - [https://github.com/wso2/financial-open-banking/issues/3265](url)

**Comment by mefarazath** [comment]
@dimuthnc is this requirement implemented with https://github.com/wso2/product-is/issues/9277?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
