### ISSUE TITLE
Create a set of dev tools

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5052]
This issue is opened to track, creating a set of dev tools that will help with the tasks of developers integrating with the Identity Server.

**Comment by janakamarasena** [comment]
Possible tools
- saml decode / encode
- jwt generator / decoder
- base64encode / decode

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
