### ISSUE TITLE
MissingClaimHandler does not handle sp claim mapping for oidc sp

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5054]
**Steps to reproduce**
1. Add an oidc sp
2. Add a sp claim mapping for a know oidc claim with a different name (Eg: "userCountry" for "http://wso2.org/claims/country")
3. Mark it as requested and mandetory
4. Configure the sp with an oidc deferated IdP
5. Try to authenticate a user with the code grant flow
6. Login to a user in the federated IdP who does not have above mandetory claim (country)
7. It will ask to fill the mandetory claim manually, fill it and continue
8. Then, send authz code grant /token request
9. Following exception is thrown

> ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} -  Error occurred while issuing the access token for Client ID : zqlfCn_efCyjDKlfRFS5Ul6TsQsa, User ID null, Scope : [] and Grant Type : authorization_code
> java.lang.NullPointerException
> 	at net.minidev.json.JSONObject.writeJSON(JSONObject.java:162)
> 	at net.minidev.json.JSONObject.toJSONString(JSONObject.java:72)
> 	at net.minidev.json.JSONObject.toString(JSONObject.java:251)
> 	at com.nimbusds.jose.Payload.toString(Payload.java:386)
> 	at com.nimbusds.jose.Payload.toBytes(Payload.java:418)
> 	at com.nimbusds.jose.Payload.toBase64URL(Payload.java:434)
> 	at com.nimbusds.jose.JWSObject.<init>(JWSObject.java:120)
> 	at com.nimbusds.jwt.SignedJWT.<init>(SignedJWT.java:57)
> 	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.signJWTWithRSA(OAuth2Util.java:2005)
> 	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.signJWT(OAuth2Util.java:1960)
> 	at org.wso2.carbon.identity.openidconnect.DefaultIDTokenBuilder.getIDToken(DefaultIDTokenBuilder.java:309)
> 	at org.wso2.carbon.identity.openidconnect.DefaultIDTokenBuilder.buildIDToken(DefaultIDTokenBuilder.java:224)
> 	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:314)
> 	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:225)
> 	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:300)
> 	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:90)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ...

**Anaysis**
In the PostAuthnMissingClaimHandler L221[1], `spToCarbonClaimMappingObject` has mapping between local claims and odic claims.
> "http://wso2.org/claims/country" => "country"

 But, `localClaimURI` comes with the sp mapped name `userCountry`. In this case, `claimsForContext` will have an entry with a null key.
> null => "Sri Lanka"

When it tries to build the id_token with those claims in [2], jwtClaimsSet contains an entry with a null key and `claimsSet.toJSONObject().toJSONString()` throws an NPE

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/PostAuthnMissingClaimHandler.java#L221
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L2097

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
