### ISSUE TITLE
SP claim mapping does not work for OIDC

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5055]
This doc [1] says, we if we trying to use sp claim mapping for odic sp, we have to add the mapped name to the oidc scope. 

According to the new implementation of oidc scope management, we are unable to add claims to oidc scopes without having a claim mapping in the oidc dialect. But it is not possible to have two oidc mappings for the same local claim. Therefore, it is not possible to have any other name for an oidc claim other than the mapped name in the oidc dialect. In other words: sp claim mapping is not possible for oidc sps.

Eg: "userCountry" for "http://wso2.org/claims/country"

PS:
- Tested and confirmed that mapped claims do not come to the id_token without adding them to the scope.
- Related issue https://github.com/wso2/product-is/issues/5054

[1] https://docs.wso2.com/display/IS570/Configuring+Claims+for+a+Service+Provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
