### ISSUE TITLE
Revoke Token Flow Breaks for a Refreshed JWT Access Token.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5060]
### Steps to reproduce.

1. Add OAuth client with JWT token issuer.
2. Request Token.
3. Execute introspection endpoint. (Optional, just to make sure the new token works)
4. Get a new token using the refresh token grant.
5. Execute introspection endpoint. (Optional, just to make sure the new token works)
6. Revoke the new access token.
7. Execute introspection endpoint again. Still, the token is active.

This happens due to a caching issue. If we send the same revoke request again, flow works and the token get revoked as expected.

**Comment by Kktheoch** [comment]
This still seems to be the case in 5.9.0, unsure of newer versions.

"Workaround" of revoking the refresh token twice seems to still be applicable.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
