### ISSUE TITLE
"Approve" option and consent don't work well together

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#5066]
1. I login to an OIDC application with "approve" and giving consent for all claims
2. I logout  from the application
3. Now I login again.

Expected behavior:
I need to consent all the claims again.

Actual Behavior:
I need to just select either "approve" or "approve always" and continue

The above behavior doesn't have any meaning to me. Either the consent for all claims must be asked again or the approval step should be skipped for specific time. I don't understand current behavior.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
1. I didn't observe this behavior in IS 7.0 fresh pack.
2. The "approval always" option is no more available in IS 7.0.
