### ISSUE TITLE
Validation of user submitted form data

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5069]
As of now user data submitted via JIT provisioning is not handled properly. If the password provided by the user violates password policy it won't allow the user to correct it and retry the submission. Instead, it directs the user to an error page(Refer to wso2/product-is#5009). 

In addition to that, there should be a proper mechanism to validate other user attributes(ex. username) as well.

**Comment by malithie** [comment]
Reducing the priority and to be addressed in a future milestone as this incorporates improvements

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
