### ISSUE TITLE
Add event triggering for missing identity operations

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#5070]
Currently we only fire "account lock" event only. Which is a generic event where it can be fired for multiple operations. We need to trigger a specific event here. Furthermore, there are multiple operations that we do not trigger events. We need to identify them and trigger events accordingly.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
