### ISSUE TITLE
OAuth/OpenID callback URL validation

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5073]
Only the scheme is considered when validating callback URLs. If the URL contains a valid scheme it is considered as a valid URL irrespective of its proper format.

http://localhost::8080/playground2/oauth2client and http://localhost??8080/playground2/oauth2client are considered valid as the scheme is valid.

However when using regular expressions to define multiple callback URLs even the scheme is not validated.

**Comment by VivekVinushanth** [comment]
1. It is difficult to validate when multiple call back URLs are provided :
* Especially when multiple call back URL's with URL followed by a regex.

2. In  http://localhost??8080/playground2/oauth2client
   It is a bit ambiguous. Here ?? need not to be a port.but can be a "Query string" of a URL.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
