### ISSUE TITLE
Filtering Groups with and operator and pagination query params fails saying complex filters are not supported

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5076]
**Suggested Labels**
Affected : 5.8.0- beta
Severity: Major
Priority: Highest
Component: SCIM2
Type-Bug

**Steps to reproduce**
1. Create 2 roles as manager and testrole1 via management console
2. Try to filter the created groups with pagination using the below request

`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?filter=displayName+eq+manager+and+displayName+eq+testrole1&startIndex=1&count=1'`

Will receive the below response 
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Complex filters are not supported yet","status":"501"}`

Sample Request
`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?filter=displayName+eq+manager+and+displayName+eq+testrole1'`

Response 
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Complex filters are not supported yet","status":"501"}`

**Observation**
As count is set to 1 starting from the 1st index even though it filter 2 roles from the displayName response needs to output only one result. But this request fails with above response

**Comment by somindatommy** [comment]
Multi attribute filtering is not implemented for groups endpoint. That's the reason for this error. Currently we do not support multi attribute filtering for groups endpoint.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
