### ISSUE TITLE
Pagination is not supported error given in the response when startIndex is set to a number other than 1 in Filtering groups with SCIM2

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5079]
**Suggested Labels**
Affected : 5.8.0- beta
Severity: Major
Priority: Highest
Component: SCIM2
Type-Bug

**Steps to reproduce**

1. Create 2 roles as manager and mana via management console
2. Try to filter the created groups with the below request

`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?startIndex=3&count=2&filter=displayName+sw+m'

`
Response Received
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Pagination is not supported","status":"501"}`

When the startIndex=1 will get the response as below without error
Request
`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?startIndex=1&count=2&filter=displayName+sw+m'
`
Response
`{"totalResults":2,"startIndex":1,"itemsPerPage":2,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"PRIMARY/manager","meta":{"created":"2019-04-17T06:39:23Z","location":"https://is580cluster2.qa.com/scim2/Groups/8cdaedd1-3f51-4144-be49-f25dde786e40","lastModified":"2019-04-17T06:39:23Z"},"id":"8cdaedd1-3f51-4144-be49-f25dde786e40"},{"displayName":"PRIMARY/mana","meta":{"created":"2019-04-17T10:31:39Z","location":"https://is580cluster2.qa.com/scim2/Groups/af4220e9-6739-4705-acbe-ccd220f8f31d","lastModified":"2019-04-17T10:31:39Z"},"id":"af4220e9-6739-4705-acbe-ccd220f8f31d"}]}
`

`

**Comment by somindatommy** [comment]
This is the current behaviour since pagination is not implemented in groups endpoint. Only count param in request will not give this error since the count param is omitted when processing the request.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
