### ISSUE TITLE
SAML Single Logout Failed when Back Channel Logout enabled

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5080]
Steps to reproduce:

Create two SP's: travelocity.com, travelocity.com2
Enable Single Out on both SP's
Check on Back-Channel Logout on Both SP's 
Log in to both and log out from one 
IDP should send a request to other SP 
and a Debug log should be their LogOutRequestSender Line 246
that debug log is not present in the logs

**Comment by nilasini** [comment]
@Buddhimah Since line number may change time to time it would be easy to track if you specify the exact debug log you were mentioning.

**Comment by Buddhimah** [comment]
log.debug("single logout request is sent to : " + logoutReqDTO.getAssertionConsumerURL() +
                                    " is returned with " + HttpStatus.getStatusText(response.getStatusLine().getStatusCode()));

**Comment by IsurangaPerera** [comment]
This is an issue with the Travelocity app and provides the expected behaviour when used with pick-up app. Hence no fix needed.
