### ISSUE TITLE
Filtering Groups fails with SCIM2 when the user store is a secondary user store 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5083]
**Suggested Labels**
Affected : 5.8.0- beta
Severity: Major
Priority: Critical
Component: SCIM2
Type-Bug

**Steps to reproduce**
1. Create a secondary user store
2. Create 2 roles as SECONDARY/secondaryrole1, SECONDARY/secondaryrole2  in the secondary userstore

3. Try to filter the roles in the secondary user store with below commands

Request
`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?domain=secondary&filter=displayName+eq+secondaryrole1'`

Response
`{"totalResults":0,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}`

Request
`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?filter=displayName+eq+SECONDARY/secondaryrole1'`

Response
`{"totalResults":0,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}`

Request
`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?filter=displayName+eq+secondaryrole1'
`
Response
`{"totalResults":0,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}
`
Filtering is not working for none of the commands above when the Groups are added for the secondary userstore

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
