### ISSUE TITLE
Filtering Groups with pagination in SCIM2 fails when the groups are created in secondary userstore

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5089]
**Suggested Labels**
Affected : 5.8.0- beta
Severity: Major
Priority: Highest
Component: SCIM2
Type-Bug

**Steps to reproduce**

1. Create a secondary user store
2. Create 2 roles as SECONDARY/secondaryrole1, SECONDARY/secondaryrole2 in the secondary userstore
3. Try to filter the roles in the secondary user store with the pagination and startIndex 

Sample Request

`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?domain=SECONDARY&filter=displayName+eq+secondaryrole1&startIndex=1&count=1'
`
Response
`{"totalResults":0,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}
`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
