### ISSUE TITLE
Listing Groups with the query param "attributes" in SCIM2 does not work with Groups in secondary user store

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5095]
**Suggested Labels**
Affected : 5.8.0- beta
Severity: Major
Priority: Highest
Component: SCIM2
Type-Bug

**Steps to reproduce**

1. Create a secondary user store
2. Create 2 roles as SECONDARY/secondaryrole1, SECONDARY/secondaryrole2 in the secondary userstore
3. Try to list the groups with the query parameter "attributes" as in the below sample commands

Sample Request

`curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?attributes=id'
`
Response
`{"totalResults":6,"startIndex":1,"itemsPerPage":6,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"id":"6e3df0e2-4e49-47e6-bac3-1e7d3a251357"},{"id":"f981e9c4-67f6-4955-95bc-a74ebde94317"},{"id":"8cdaedd1-3f51-4144-be49-f25dde786e40"},{"id":"af4220e9-6739-4705-acbe-ccd220f8f31d"},{"id":"ffb9d4c9-a3c7-490b-abce-ba07d82fdc0d"},{"id":"86b433ac-47a3-406f-b40f-087a94d26873"}]}`

Sample Request
curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?attributes=id&domain=secondary'

Response
`{"totalResults":6,"startIndex":1,"itemsPerPage":6,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"id":"6e3df0e2-4e49-47e6-bac3-1e7d3a251357"},{"id":"f981e9c4-67f6-4955-95bc-a74ebde94317"},{"id":"8cdaedd1-3f51-4144-be49-f25dde786e40"},{"id":"af4220e9-6739-4705-acbe-ccd220f8f31d"},{"id":"ffb9d4c9-a3c7-490b-abce-ba07d82fdc0d"},{"id":"86b433ac-47a3-406f-b40f-087a94d26873"}]}`

Does not list the groups in the secondary user store with the query param attributes

**Comment by ShanikaWickramasinghe** [comment]
This is not working in secondary userstore when trying to filter the users(members) assigned for a particular group as well
sample command
 `curl -v -k --user admin:admin 'https://is580cluster2.qa.com:443/scim2/Groups?filter=displayName+eq+secondaryrole1&attributes=members&domain=secondary'`

**Comment by somindatommy** [comment]
This issue is fixed from IS 5.8.0 onwards.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
