### ISSUE TITLE
Can't do Step-up Authentication for Untrusted 3rd Party Service Providers

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#5098]
Details are provided in [1].

[1] "[IAM] Can't do Step-up Authentication for Untrusted 3rd Party Service Providers" in architecture@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be tracked with https://github.com/wso2-enterprise/iam-product-management/issues/364
