### ISSUE TITLE
[Doc] Cleanup scripts are not clearly made available for 5.6.0 and lower versions

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5102]
Some of the following docs point to [1] for cleanup scripts, but there we can find mysql and mssql script only. In some docs, the link is incorrect (404). Some still contain the scripts itself (on the doc page)

> https://docs.wso2.com/display/IS560/Removing+Unused+Tokens+from+the+Database
> https://docs.wso2.com/display/IS550/Removing+Unused+Tokens+from+the+Database
> https://docs.wso2.com/display/IS541/Removing+Unused+Tokens+from+the+Database
> https://docs.wso2.com/display/IS540/Removing+Unused+Tokens+from+the+Database
> https://docs.wso2.com/display/IS530/Removing+Unused+Tokens+from+the+Database
> https://docs.wso2.com/display/IS520/Removing+Unused+Tokens+from+the+Database
> https://docs.wso2.com/display/IS510/Removing+Unused+Tokens+from+the+Database

[1] https://github.com/wso2/samples-is/tree/master/scripts/token-cleanup-scripts

**Comment by rksk** [comment]
> Once the cleanup is over, start the WSO2 Identity Server pointing to the cleaned-up database dump and test **throughly** for any issues. 

Here, the word **throughly** seems to be misspelled.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
