### ISSUE TITLE
Document 'EnableFilteringEnhancements' property

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#5108]
Affected version: IS 5.7.0 WUM, IS 5.6.0 WUM, IS 5.5.0 WUM

`<EnableFilteringEnhancements>` property introduced for applying filtering enhancements for SCIM2 filter results. This makes sure that Eq should strictly check for the String match (in this case cross user store search should not be performed). This config also enforces consistency on the filtered attribute formats in the response when filtering is done via different endpoints. e.g. Users and Groups endpoints.

In order to enable the filtering enhancements, add following config under <SCIM2> tag in <IS_HOME>/repository/conf/identity/identity.xml file.
    `<EnableFilteringEnhancements>true</EnableFilteringEnhancements>`

**Comment by JKAUSHALYA** [comment]
These configuration values should be documented as TOML. (Not as XML)
`"scim2.enable_filtering_enhancements": false`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
