### ISSUE TITLE
Include libraries in the product build phase

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5109]
Some libraries like wss4j and charon should be packed in the product build phase. At the moment wss4j packs from the carbon-identity-framework and charon packs from the identity-inbound-provisioning-scim2. We need to list all the libraries which are not packed in the product build phase and add them to it.

**Comment by madurangasiriwardena** [comment]
I think this is the expected behavior. If some feature needs a dependency, that feature is the entity that knows the version of the dependency that it needs. So we can't move the component packing task to the product build phase.
