### ISSUE TITLE
SCIM2 filtering using eq operator failed when username equals admin 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5119]
use the IS 5.8 Beta 3

send the following curl request 
curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=userName+eq+admin'

it will give an error

this issue only occurs for the username admin 

error:

{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in getting user information for user: admin","status":"500"}B

**Comment by malithie** [comment]
Fixed
