### ISSUE TITLE
[DOC] Link to the Custom authenticator example for WSO2 IS 5.7.0 server imperceptible

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5122]
**Description**.

The link to sample custom authenticator for wso2 IS 5.7.0 mentioned in the documentation [1] 
 under the highlighted area in point 2 is so slight that it cannot be noticed.

It would be great if we can  project link at the first in the documnetation & details at the bottom. So it will be convinent for those who refering the documnetation.

**Comment by SiluniPathirana** [comment]
Link https://docs.wso2.com/display/IS570/Writing+a+Custom+Local+Authenticator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
