### ISSUE TITLE
Inconsistency in SCIM2 Filtering with domain parameter and domain in the attribute value

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#5129]
In SCIM2 when we filter users using Users endpoint, we can use following attribute values.
E.g. userName, groups, name.filterName, emails.

[1]`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=userName+eq+PRIMARY/user1&domain=PRIMARY`

When domain name in the attribute value(_PRIMARY_ in PRIMARY/user1) equals with domain query param (_PRIMARY_ in domain=PRIMARY), it will be retrieved the relevant users from particular domain name. 

[2]`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=userName+eq+PRIMARY/user1&domain=TEST`
When domain name in the attribute value(_PRIMARY_ in PRIMARY/user1) not equals with domain query param (_PRIMARY_ in domain=TEST), it will give following error message.

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Domain parameter: test in request does not match with the domain name in the attribute value: user1 ","status":"500"}`

However, above error message is given only for userName and groups attribute values. If we use other attribute value (e.g. name.filterName, emails), It will give users from domain name in the attribute value(PRIMARY in PRIMARY/test@gmail.com). [3]

[3]`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=emails+eq+PRIMARY/test@gmail.com&domain=TEST`

Response of [3]
`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":["test@gmail.com"],"meta":{"created":"2019-04-24T14:19:07.716Z","lastModified":"2019-04-24T14:21:58.709Z","resourceType":"User"},"name":{"givenName":"Ishika","familyName":"user1"},"groups":[{"display":"PRIMARY/Engineering1","value":"de357adc-8f28-48d7-bc1f-e56f9fe44c46"}],"id":"97e088dc-3017-4bad-aaae-02df177ae2e6","userName":"PRIMARY/user1"}]}`

**Comment by somindatommy** [comment]
It was decided to only let userName and group attributes to embed domain name in the attribute value. Therefore the above fix is not needed

**Comment by malithie** [comment]
Resolving based on the comment above
