### ISSUE TITLE
Migration client - Event-based session termination

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5132]
This is to terminate the active sessions of a user during the following events
- Update user credentials
- Delete user
- Lock user account
- Disable user account

The following configuration need to be added to the identity.xml file located in the <IS_HOME>/repository/conf/identity folder within the <SessionDataPersist> tag to enable the functionality
```
<JDBCPersistenceManager>
.....
   <SessionDataPersist>
   .....
       <UserSessionMapping>
	    <Enable>true</Enable>
       </UserSessionMapping>
   </SessionDataPersist>
</JDBCPersistenceManager>
```

PR on the migration scripts to add newly introduced tables: https://github.com/wso2/product-is/pull/4115

**Comment by nilasini** [comment]
Configurations had been added with the PR \[1]. Migration client had been updated with the PR \[2]

\[1] https://github.com/wso2/carbon-identity-framework/pull/2105
\[2] https://github.com/wso2/product-is/pull/4115

Hence resolving the issue
