### ISSUE TITLE
When the "totalResults" is 0 it returns "startIndex":1,"itemsPerPage":0 in SCIM2 user filter 

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5137]
Request :
curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=userName+Eq+"hasanthi"

Response :
{"totalResults":0,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}

quoted from the spec:
"A query that does not return any matches SHALL return success (HTTP
   status code 200) with "totalResults" set to a value of 0."

So it should return 200 code and we don't need to return startIndex or itemsPerPage

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
