### ISSUE TITLE
SCIM2 Filtering is not supported with the schema attribute

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5139]
Request : curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=schemas+eq+"urn:ietf:params:scim:schemas:core:2.0:User"

Response : {"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"Not a valid attribute name/uri","status":"400"}

Quoted from the spec
 "The following are examples of valid filters."
"filter=
 schemas eq "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"

The above filter should be supported from wso2 IS

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
