### ISSUE TITLE
In SCIM2 Filtering the attribute names and attribute operators used in filters should be case insensitive

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5140]
Request :curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=EMAILS.home+EQ+hasanthi@gmail.com

Response :{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"Not a valid attribute name/uri","status":"400"}

Request :
curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=emails.home+EQ+hasanthi@gmail.com

Response :{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":[{"type":"work","value":"hasanthi@wso2.com"},{"type":"home","value":"hasanthi@gmail.com"}],"meta":{"created":"2019-04-25T10:14:12.028Z","location":"https://localhost:9443/scim2/Users/a3b249d0-573b-4e96-b2cd-09bcbbe539c4","lastModified":"2019-04-25T11:22:03.278Z","resourceType":"User"},"name":{"givenName":"hasanthi","familyName":"Purnima"},"id":"a3b249d0-573b-4e96-b2cd-09bcbbe539c4","userName":"hasanthi"}]}

Quoted from the spec

"Attribute names and attribute operators used in filters are case
   insensitive.  For example, the following two expressions will
   evaluate to the same logical value:

   filter=userName Eq "john"

   filter=Username eq "john""

So it should support to use attribute names in an case insensitive manner using wso2 IS

**Comment by JayaShakthi97** [comment]
- Related issue: https://github.com/wso2/product-is/issues/20511

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
