### ISSUE TITLE
SCIM2 Filtering with multi-attribute returns incorrect data with meta attributes 

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5141]
Request :curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=meta.resourceType+eq+User+AND+name.familyName+EW+Dissanayake
 
Response :{"totalResults":2,"startIndex":1,"itemsPerPage":2,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":[{"type":"home","value":"jon@wso2.com"},"hasanthi@gmail.com"],"meta":{"created":"2019-04-25T10:19:53.487Z","lastModified":"2019-04-25T12:08:51.243Z","resourceType":"User"},"name":{"givenName":"hansi","familyName":"pur"},"id":"40878f6b-4213-41c1-a5d1-450f27ba53fc","userName":"test"},{"emails":[{"type":"work","value":"vindula@wso2.com"},{"type":"home","value":"abc@gmail.com"}],"meta":{"created":"2019-04-25T10:14:12.028Z","location":"https://localhost:9443/scim2/Users/a3b249d0-573b-4e96-b2cd-09bcbbe539c4","lastModified":"2019-04-25T11:22:03.278Z","resourceType":"User"},"name":{"givenName":"hasanthi","familyName":"Dissanayake"},"id":"a3b249d0-573b-4e96-b2cd-09bcbbe539c4","userName":"hasanthi"}]}

It returns both the user that the user store contains even if the familyName of the other user is different. Following request gives the expected result after swapping things around AND.

Request : curl -v -k --user admin:admin https://localhost:9443/scim2/Users?filter=name.familyName+EW+Dissanayake+AND+meta.resourceType+eq+User

Response :{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":[{"type":"work","value":"hasanthi@wso2.com"},{"type":"home","value":"hasanthi@gmail.com"}],"meta":{"created":"2019-04-25T10:14:12.028Z","location":"https://localhost:9443/scim2/Users/a3b249d0-573b-4e96-b2cd-09bcbbe539c4","lastModified":"2019-04-25T11:22:03.278Z","resourceType":"User"},"name":{"givenName":"hasanthi","familyName":"Dissanayake"},"id":"a3b249d0-573b-4e96-b2cd-09bcbbe539c4","userName":"hasanthi"}]}

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
