### ISSUE TITLE
RemoteUserStoreManagerService.updateRoleListOfUser allows to update "Internal" roles of non existing users

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#5143]
Steps to reproduce.

1. Create a new "Internal" role from Management console (ex: Internal/test)
2. Now use RemoteUserStoreManagerService.updateRoleListOfUser with non existing user to update its roles to newly created Internal role.
A sample request is as below.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:updateRoleListOfUser>
         <ser:userName>non-existing-user</ser:userName>
         <ser:newRoles>Internal/test</ser:newRoles>
      </ser:updateRoleListOfUser>
   </soapenv:Body>
</soapenv:Envelope>
```

Above request returns 202 Accepted response. Instead, this request should fail and respond with a proper error message.

Additionally, in the database UM_HYBRID_USER_ROLE table, there is an entry with a non-existing username. Another concern here is storing the username instead of a user-id.

UM_ID | UM_USER_NAME | UM_ROLE_ID | UM_TENANT_ID | UM_DOMAIN_ID
-- | -- | -- | -- | --
12 | non-existing-user | 2 | -1234 | 6

When browsing from management console under User List of Role : Internal/test, this non-existing user is listed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
