### ISSUE TITLE
SAML SLO sends back-channel call even front-channel is enabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5148]
When we have selected a front-channel SAML logout method, the SAML logout request is going in the front-channel as expected for both POST and Redirect bindings. But it tries to send the back-channel request always despite the Logout method.

**Steps to reproduce**
- Enable debug logs for org.wso2.carbon.identity.sso.saml
- Configure a SAML sp with followings
> SLO Request URL = "http://pqr.local"
> Logout Method = "Front-Channel Logout POST/Redirect"
> Enable IdP Initiated SLO = true
- Try to do IdP initiated SAML SLO.
> https://localhost:9443/samlsso?slo=true&spEntityID=saml2-web-app-pickup-manager.com
- Following log is written
> DEBUG {org.wso2.carbon.identity.sso.saml.logout.LogoutRequestSender} -  Error while executing http request.
> java.net.UnknownHostException: pqr.local: Name or service not known
> 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)

**Comment by rksk** [comment]
**Affected versions**
5.3.0 and 5.7.0

**Comment by thushaaanthan** [comment]
Fix 
[IS5.3] https://github.com/wso2-support/identity-inbound-auth-saml/pull/58
[IS5.7] https://github.com/wso2-support/identity-inbound-auth-saml/pull/59

**Comment by malithie** [comment]
This was not observed in SP-initiated SLO flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
