### ISSUE TITLE
Access Token Introspection depend on UMA tables 

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5150]
When following property is enabled in identity.xml the access token validation depend on some UMA tables.

` <OAuth>
        <Introspection>
            <EnableDataProviders>true</EnableDataProviders>
        </Introspection>
</OAuth>`

If the token is a normal access token not a UMA one then depend on UMA tables is wrong here. So there should be  way to identify which data provider should be executed based on the data which is processing.

**Comment by malithie** [comment]
As at now, there is no indication on the grant the token is being issued at the [UMAIntrospectionDataProvider](https://github.com/wso2-extensions/identity-oauth-uma/blob/master/components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/impl/UMAIntrospectionDataProvider.java).
Thus, without that it cannot distinguish a token issued for UMA.
This info needs to be incorporated for [OAuth2IntrospectionResponseDTO](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dto/OAuth2IntrospectionResponseDTO.java) to fix this.

Therefore, as further permission details is to be included selectively for UMA, it's recommended to enable above property if needed and to set it to false by default for 5.8.0 version.

Above fix should be incorporated in a future release and UMA tokens should be handled specially

**Comment by malithie** [comment]
Once this is fixed the afore mentioned property should be enabled by default in the product [1].

[1] https://github.com/wso2/product-is/issues/4769

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
