### ISSUE TITLE
When authenticate with email attribute already added Service providers are not visible

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#5151]
**Step to Reproduced :**
Product version: wso2is-5.8.0-beta3-SNAPSHOT
Tested Environment : (macOS, H2, embedded LDAP)

1. Login with admin: admin (with default configurations )
2. Add a service provider - TestSP
3. Change the configurations to authenticate with email attribute [1] 
4. Login with admin@wso2.com: admin (with modified configurations )

**Actual Result:** 
Added service provide is not visible when  authenticating with email attribute
 and also can not add new the Service provider with the previous SP name (TestSP), saying "'TestSP' already exists."
**Screenshot :** 

 ![image](https://user-images.githubusercontent.com/39120228/56889768-f59e3100-6a94-11e9-9b1c-2f762be697c4.png)

2. 
![image](https://user-images.githubusercontent.com/39120228/56889793-0cdd1e80-6a95-11e9-9eff-12262e4da031.png)

[1] https://docs.wso2.com/display/IS570/Using+Email+Address+as+the+Username

**Comment by DMHP** [comment]
This is the expected behaviour. In the middle we do not recommend to do this configuration change and if we do so this is expected.
