### ISSUE TITLE
[Doc] Adaptive authentication script doc improvements

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5152]
This issue is to track the doc improvements for the adaptive authentication documentation for [5.8.0 doc space](https://docs.wso2.com/display/IS580/Adaptive+Authentication+JS+API+Reference).

### Authenticated user of the step can be changed in the adaptive authentication. 
_(Introduced with https://github.com/wso2/product-is/issues/4885)
In adaptive JS API reference of the [user](https://docs.wso2.com/display/IS580/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-userObject ) object change the following,_

user.username : (Read/Write)The user’s username.
user.tenantDomain : (Read/Write)The user’s tenant domain (only for local users; federated users will have this as carbon.super).
user.userStoreDomain : (Read/Write)The user’s user store domain (only for local users).
user.roles : (Read)List of user’s roles.

### Utility function to get unique User with claim values
_(Introduced with https://github.com/wso2/product-is/issues/4884, available in 5.8.0 WUM pack)
In the JS API reference of the [utility function  ](https://docs.wso2.com/display/IS580/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-Utilityfunctions) add the getUniqueUserWithClaimValues(claimMap, tenantDomain, profile)_

The utility function will search on the underlying user stores and return a unique user with the claim values. The claim map will consist of the claim and value. The function will get the 1st key from the map and get all users with the claim and add to list. Then remove the users from that list not having the other claims. So the order of the map will decide the performance of this function. The first claim in this must have a low number of users.

Parameter | Description
-- | --
claimMap | A map contains the claim URI and claim value
tenantDomain | The tenant domain of the user
profile| Profile of the user. (Optional, the default value is 'default'

```
var claimMap = {};
claimMap[MAPPED_FEDERATED_USER_NAME_CLAIM] = federatedUserName;
claimMap[MAPPED_FEDERATED_IDP_NAME_CLAIM] = idpName;
var mappedUsername = getUniqueUserWithClaimValues(claimMap, context.tenantDomain);
```

**Comment by senthalan** [comment]
## Utility function to get the associated local user of a federated user 
_(Introduced with https://github.com/wso2/product-is/issues/3984)
In the JS API reference of the [utility function  ](https://docs.wso2.com/display/IS580/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-Utilityfunctions) add the getAssociatedLocalUser(federatedUser)_


Parameter | Description
-- | --
federatedUser | The federated user object

**Comment by Thumimku** [comment]
According to this issue https://github.com/wso2/product-is/issues/11777, we are changing the method signature as 

Parameter | Description
-- | --
claimMap | A map contains the claim URI and claim value
context | JsAuthenticationCOntext
profile| Profile of the user. (Optional, the default value is 'default'

```
var claimMap = {};
claimMap[MAPPED_FEDERATED_USER_NAME_CLAIM] = federatedUserName;
claimMap[MAPPED_FEDERATED_IDP_NAME_CLAIM] = idpName;
var mappedUsername = getUniqueUserWithClaimValues(claimMap, context);
```

**Comment by rksk** [comment]
### Utility function to associate a federated user with a local user

Introduced with https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/44

doAssociationWithLocalUser(fedUser, localUsername, tenantDomain, userStoreDomain)

Parameter | Description
-- | --
fedUser | Federated user object
localUsername | Username of the local user to be associated
tenantDomain | The tenant domain of the local user
userStoreDomain| The user store domain of the local user

**Comment by divyaamunugama** [comment]
The requested changes are updated in IS 5.8.0 docs. 

https://docs.wso2.com/display/IS580/Adaptive+Authentication+JS+API+Reference

**Comment by divyaamunugama** [comment]
Hi Sajith, 

Sure, I will update those as well. Thank You!
