### ISSUE TITLE
Error in provisioning user with the claims returned from userinfo endpoint

### ISSUE THREAD

**Issue by vithu30** [wso2/product-is#5154]
**Description:**
Error in provisioning user to IS when the claims return from /userinfo endpoint of federated identity provider is in following format:
 `{ "website" : ["test_value1", "test_vlaue2"] }`
This is valid JSON format which is mandatory as per the OpenID specifications for response type for user-info endpoint [1]. 
[1] https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse

**Suggested Labels:**
Bug

**Affected Product Version:**
IS-5.7.0 

**Steps to reproduce:**
* Configured a separate Identity Server as federated Identity Provider for an Identity Server
* Hard coded a claim with the value  **["test_value1", "test_vlaue2"]** (I have added this value to URL claim)
* When authenticating and provisioning the user to the first Identity Server, URL claim is added as "[Ljava.lang.Object;@54f471b6"
Please note that I have followed above steps to reflect the scenario where the federated IdP returns claims in a valid JSON format and those claims are not added to provisioned users in IS

**Comment by omindu** [comment]
@vithu30 can you please point me to the public fix related to this issue
