### ISSUE TITLE
OAuthSessionDataCache Entries are Not Cleared

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5156]
Entries stored in the IDN_AUTH_TEMP_SESSION_STORE with the SESSION_TYPE of OAuthSessionDataCache are not getting cleared as expected. We ran a long-running test with IS 5.8.0 beta3 pack and after 15 hours, the following number of records were left on IDN_AUTH_TEMP_SESSION_STORE table.
```
+----------------------------+----------+
| SESSION_TYPE               | count(*) |
+----------------------------+----------+
| AuthenticationContextCache |       20 |
| AuthenticationResultCache  |        6 |
| OAuthSessionDataCache      |    29909 |
| SAMLSSOSessionDataCache    |       12 |
+----------------------------+----------+
```

**Comment by mefarazath** [comment]
OAuthSessionDataCache entries are created during authorization code and implicit flows. Ideally with our improved cleanup logic if they were deleted at the end of the request they would not remain in the IDN_AUTH_TEMP_SESSION_STORE.

So it is most probable that the code does not clear these cache entries at the end of the request.

**Comment by hari819** [comment]
@JKAUSHALYA @madurangasiriwardena 

Any plans to improve the logic , i faced similar issue from table IDN_AUTH_TEMP_SESSION_STORE which i mentioned in this issue ,[https://github.com/wso2/product-is/issues/7392](url),

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
