### ISSUE TITLE
Issue in Enabling debug logs from carbon console. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5170]
- Enable debug to some of the package from log4j.properties file. 
- Go to the management console and change those class to INFO level from UI. 
- Re-enable debug level to some of those classes. 
- Then those debug logs are not working properly. 
- Start to work again if we click on the 'Restore to default'
- Also, if we set the package to ERROR level in log4j.properties initially, everything works fine.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
