### ISSUE TITLE
Role create with super admin permission (When invoke addRole in the )  RemoteUserStoreManagerService without specifying the resourceId

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5171]
Hi All,

The issue is regarding the Identity server 5.3.0

1. Invoke addRole method in the RemoteUserStoreManagerService without specifying the resourceId as below request

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org" xmlns:xsd="http://dao.service.ws.um.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:addRole>
         <!--Optional:-->
         <ser:roleName>Internal/yello</ser:roleName>
            <!--Optional:-->
            <xsd:action>ui.execute</xsd:action>
            <!--Optional:-->
            <xsd:resourceId></xsd:resourceId>
         </ser:permissions>
      </ser:addRole>
   </soapenv:Body>
</soapenv:Envelope>
```

2.Then we can find even we have not specified xsd:resourceId for the role. The Role has created with all the root permissions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
