### ISSUE TITLE
Issue while restarting the Identity Server

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5174]
seeing this error when we bring up the WSO2 service 

Caused by: java.sql.SQLException: ORA-01483: invalid length for DATE or NUMBER bind variable. [1](url)

- Further analyzed the issue and found that it is copying resources in wso2is-5.0.0/resources/allthemes/Default/images location to the registry in each restart. 

- This issue is not observing in the other node which connects to the same database. 
- Renaming the allthemes folder fix the issue. Since then it won't copy the files to the registry. 
- Copy the files from the working node to the now working node, but the issue still persists. So, there is no issue in the patch. 

Environment is, IS 5.0.0 with SP1

[wso2carbon.log](https://github.com/wso2/product-is/files/3139158/wso2carbon.log)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
