### ISSUE TITLE
Need to add newly introduced properties in Migration Doc

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#5178]
**Suggested Labels**
Component: Migration
Type-Doc

We have introduced 3 new properties in identity.xml under SCIM2. Therefor we need to add behavioral changes introduced with each property and other details regarding each property.

Followings are the new properties.

1. FilterUsersAndGroupsOnlyFromPrimaryDomain
2. MandateDomainForGroupNamesInGroupsResponse
3. MandateDomainForUsernamesAndGroupNamesInResponse

**Comment by sherenewso2** [comment]
Documented in [1] 

[1] https://docs.wso2.com/display/IS580/Upgrading+from+the+Previous+Release
