### ISSUE TITLE
[DOC] Documents related "Installing as a Windows Service" need to be update 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#5191]
The current document which is discredited "Installing as a Windows Service" [1] should be updated, 
Under the **Prerequisites**, it should update and can recommend that we can use  "Yet Another Java Service Wrapper" (YAJSW) version 11.03 as well as version 12.13 (the latest version).

I have tested and verified this in the latest wso2is-5.8.0-beta6-SNAPSHOT  in Windows environment.
I tested with both yajsw-stable version-11.03 and -12.13a.

[1]https://docs.wso2.com/display/IS570/Installing+as+a+Windows+Service

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
