### ISSUE TITLE
Add HashAlgorithm configuration to identity.xml

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5192]
There should be a configuration `HashAlgorithm` under OAuth in identity.xml. In the [OAuthServerConfiguration](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/config/OAuthServerConfiguration.java#L2565) we read the value of HashAlgorithm and then this value is used in [HashingPersistenceProcessor](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/689d8cac3c4b6efab76910afefa64999743babc7/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/tokenprocessor/HashingPersistenceProcessor.java#L117) for hashing. 

But the configuration `HashAlgorithm` is not included in the `identity.xml`. The below line should be added in identity.xml under OAuth tag.

`<HashAlgorithm>SHA-256</HashAlgorithm>`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
