### ISSUE TITLE
[DOC] Lack of information on defining claims using xml configuration

### ISSUE THREAD

**Issue by anupamgogoi0907** [wso2/product-is#5200]
Hi Team,

There is not enough information in the official documentation regarding declaration of claims using configuration file. For, example, when we define claims in the **claim-config.xml** we can define the claims specific to a **User Store Domain**. For example,

```
<Claim>
	<ClaimURI>http://abc.com/claim/payrollID</ClaimURI>
	<DisplayName>Panera Employee ID</DisplayName>
	<AttributeID>ABC.COM/payrollID</AttributeID>
	<Description>Panera Employee ID</Description>
	<SupportedByDefault>true</SupportedByDefault>
</Claim>
```

I think a detail information on this topic can be added to the documentation.

https://docs.wso2.com/display/IS570/Editing+Claim+Dialects

Regards,
Anupam G
WSO2 - LATAM

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
