### ISSUE TITLE
[Doc] Missing Recommendation Information on Customizing Webapps and Java Implementations

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#5202]
**Description:**
It is great if we can add the following point to the IS documentations. (Documentations related to customizing web apps eg: https://docs.wso2.com/display/IS530/Customizing+the+Authentication+Endpoint)

- We recommend editing web apps (.jsp files) but not java implementations. 
- That is because if a .jsp file is updated, you can find it in the related web app and there you can find the implementation. 
- But we do not ship the java implementation with WUM updates. So the changes did to the Java implementation cannot be found in the public branch as well.
- Therefore, we do not recommend to customize java implementations.

**Suggested Labels:**
Documentation/Improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
