### ISSUE TITLE
[DOC] Groups filtering and listing in groups endpoint support domain parameter.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5205]
When listing and filtering groups in the groups endpoint, domain parameter was not honored in the previous versions. 
This is fixed in the latest release. New features are as follows.

To filter or list groups in a domain, domain param can be used.
To filter groups in a domain, domain value can be embedded in search attribute value. This feature only supports for following search attributes.

- DISPLAY_NAME_URI
- DISPLAY_URI
- VALUE_URI

Complex filters are not implemented in the groups endpoint filtering.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
