### ISSUE TITLE
[DOC] Custom Claim Handler for Identity Server

### ISSUE THREAD

**Issue by ghost** [wso2/product-is#5208]
Hi Team,

When a Custom Claim Handler class is created and deployed in Identity Server, this class will not be executed for  **grant_type=password (or client_credentials)**. It executes for **grant_type=code**

I think more information on this should be added to the documentation [1].
And probably we can provide a link to an example with proper Maven dependency.

https://docs.wso2.com/display/IS570/Writing+a+Custom+Claim+Handler#WritingaCustomClaimHandler-Writingthecustomclaimhandler

Thanks
WSO2- LATAM

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
