### ISSUE TITLE
[DOC] Reserved Character for the product

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5220]
In the product `/` is used as the DEFAULT_DOMAIN_SEPARATOR to identify the domain name is filtering.
Therefore it needs to be documented to avoid using `/` as much as possible. Also  needs to documented that character `/` **MUST NOT BE USED** for following attributes.
- USERNAME_URI
- GROUPS_URI
- DISPLAY_NAME_URI (members.display)
- VALUE_URI (members.value)
- ID_URI

 Better to document`/` as a product reserved character.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
