### ISSUE TITLE
Check for index modifications required with the addition of the IDP_ID column

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5226]
Check for index modifications required with the addition of the IDP_ID column to the IDN_OAUTH2_AUTHORIZATION_CODE, IDN_OAUTH2_ACCESS_TOKEN and IDN_OAUTH2_ACCESS_TOKEN_AUDIT

reference PR: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1102

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
