### ISSUE TITLE
ID token is signed with SP tenant and Access token is signed with User tenant

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#5230]
In identity.xml there are two configurations to change the option to use SP tenant or User tenant  like 
1.  UseSPTenantDomain>True</UseSPTenantDomain
2.  SignJWTWithSPKey>true</SignJWTWithSPKey

The first config is used in access token generation and by default, it is commented out in the identity.xml. Which means the user tenant is used for access tokens

The second config is specific for ID tokens and by default, it is set to true which means IDToken uses SP tenant.

Do we need two separate Configs for ID token and Access token in this case? Even if that the case, In an ideal scenario using SP tenant is recommended. Can we change the access token to use SP tenant?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
