### ISSUE TITLE
[DOC] Need to have an end to end guide on how to configure SAML Bearer Profile in IS

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#5235]
Under https://docs.wso2.com/display/IS570/SAML2+Bearer+Assertion+Profile+for+OAuth+2.0  document, it doesn't explain steps to integrate an external Identity Provider/SAML issuer and exchange externally generated SAML assertion to an access token in IS. 

Given sample only explains, how to do it using resident IDP, using a sample app. But not no samples on end to end configurations and request-response flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
