### ISSUE TITLE
Improve the JWT Token Generation document with configuring JWT token issuer via management console

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5239]
The JWT Token generation doc [1] should contain the details on configuring JWT token issuer via the management console when configuring OAuth application

![image](https://user-images.githubusercontent.com/11737221/57505824-7d96fd00-7317-11e9-9c5e-48e5fa75586e.png)

[1] https://docs.wso2.com/display/IS580/JWT+Token+Generation

**Comment by gomathyk** [comment]
Updated [](https://docs.wso2.com/display/IS580/JWT+Token+Generation) with a note.

**Comment by Abilashini** [comment]
> 1. On the Main tab, click Service Providers -> Add and register a new service provider. 

> 2. Expand the Inbound Authentication configuration -> OAuth/OpenID Connect Configuration section, and click Configure. 

I think the 1st and 2nd steps are unnecessary since they can enable JWT token issuer for an existing OAuth application as well. 
So rather providing the above configuration steps we can say,
`Select JWT as the Token issuer for a new or an existing OAuth/OpenID connect consumer application. `
and point to the 'OAuth/OpenID Connect Configuration' document.

**Comment by gomathyk** [comment]
Updated [1](https://docs.wso2.com/display/IS580/JWT+Token+Generation) with the suggestions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
