### ISSUE TITLE
Description for "FilterUsersAndGroupsOnlyFromPrimaryDomain" property in identity.xml is misleading

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5247]
`FilterUsersAndGroupsOnlyFromPrimaryDomain` is a new property introduced in IS 5.8.0 which will enable filtering users and groups in the primary user store if the a domain is not included in the query param or in the attribute value. 

But the description [1] for the above property does not mention about the impact by the domain value in a request. This needs to be fixed. Till the issue is fixed, this needs to be documented.

[1] - `If you set the property value to true, regardless the Users endpoint and Groups endpoint, it will filter users or groups only from 'PRIMARY' user store. if the property value is false, it will filter users or groups across all user stores. 
Default value : false`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
