### ISSUE TITLE
[DOC] The functionality of the property 'FilterUsersAndGroupsOnlyFromPrimaryDomain' needs to be documented

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5249]
Regarding: [wso2_is#5247](https://github.com/wso2/product-is/issues/5247)

`FilterUsersAndGroupsOnlyFromPrimaryDomai`n is a new property introduced in IS 5.8.0 which will enable filtering users and groups in the primary user store if the a domain is not included in the query param or in the attribute value.

The description in the Identity.xml is misleading. Therefore this needs to be documented.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
