### ISSUE TITLE
UserInfo response doesn't contain requested claim values for tenants

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5250]
This is the same for both PRIMARY and SECONDARY userstores. However, this doesn't affect super tenant.

**Comment by DMHP** [comment]
Changing the property value of BuildSubjectIdentifierFromSPConfig to false solves this issue. Following method should be fixed accordingly [1].

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/TokenValidationHandler.java#L491

**Comment by dewniMW** [comment]
Couldn't reproduce the issue. Tested with both playground sample app and curl for both true and false property values of BuildSubjectIdentifierFromSPConfig.

**Comment by DMHP** [comment]
Resolving the issue as per the above comment.
