### ISSUE TITLE
In SCIM2 filtering, role displayed when the users are displayed is not consistent.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5253]
When internal roles are displayed in when listing roles and listing roles of a particular user is not consistent.

**Method to reproduce:**

1.  List all the groups (In the groups endpoint). Notice that internal/system role is retrieved as well.
2. Create a new user (user1) and do not assign any roles. By default Internal/everyone role will be assigned.
3. Filter the that user (user1) in the users endpoint. Notice that no group is returned with other attributes when filtering.
4. Assign internal/system role to user1 and then filter user1 again. Notice still no group is returned. This is not consistent compared to (1) scenario.
5. Now assign another role (any role other than internal eg: eng1) to user1. Then filter the user1 again. Notice 'eng1' is in the response.

Therefore, there is an inconsistency with two responses and this needs to be fixed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
