### ISSUE TITLE
In SCIM2 multi attribute filtering fails when groups are retrieved which are in a secondary Postgre user store

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5254]
**Steps to reporduce**

- Create a Postgre secondary user store. Create a group( Eg: eng1) and assign a user (Eg: user1) to it.

- Now list all the groups in secondary user store. Notice that group `eng1` is retrieved.

- Now filter user `user1` in users endpoint. Notice that group `eng1` is in the responce.
- Now use a multi attribute filter in the users endpoint and filter from userName starts with `u` and groups sw `e` [1].

Expected behaviour is to retrieve 'user1' in the reponse. Instead following error is displayed [2]. This happens when a group is combined with another filter attribute. This needs to be fixed.

[1] - curl -v -k --user admin2@t.com:admin2 'https://localhost:9443/t/t.com/scim2/Users?filter=userName+sw+s+and+groups+sw+e&domain=test1'

[2] - {"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in filtering users by multi attributes ","status":"500"}

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
