### ISSUE TITLE
[UX] grammar issue in error - "Password at least should have x characters"

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#5257]
The error text returned by a too-short password contains a grammar error - it is currently "Password at least should have x characters", while it should be "Password should have at least x characters".  It may also be worthwhile to change "should" to "must".

https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/policy/password/DefaultPasswordLengthPolicy.java#L68

**Comment by darshanasbg** [comment]
@brionmario Lets fix this one.

**Comment by brionmario** [comment]
I'm working on this.

**Comment by brionmario** [comment]
I was able to reproduce the mentioned behaviour in IS 5.8.0 with following configuration changes

1. Enabled old identity management framework.
Changed <IS_HOME/>repository/conf/identity/identity.xml,
from
```
        <EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.mgt.IdentityMgtEventListener"
                       orderId="50" enable="false"/>
```
to
```
        <EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.mgt.IdentityMgtEventListener"
                       orderId="50" enable="true"/>
```

2. Disabled new identity management framework
Changed <IS_HOME/>repository/conf/identity/identity.xml,
from
```
        <EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener"
                       orderId="95" enable="true"/>
```
to
```
        <EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener"
                       orderId="95" enable="false"/>
```

3. Enabled password policy (length validations with proper values.
Uncommented <IS_HOME/>repository/conf/identity/identity-mgt.properties,
```
Password.policy.extensions.1=org.wso2.carbon.identity.mgt.policy.password.DefaultPasswordLengthPolicy
Password.policy.extensions.1.min.length=8
Password.policy.extensions.1.max.length=20
```

Then I created a user with name `johnsmith` and a 6 character password in management console and got following error message,

<img width="487" alt="Screen Shot 2019-07-23 at 12 25 20 PM" src="https://user-images.githubusercontent.com/25959096/61689517-f87f8980-ad44-11e9-9ae5-59f96e56836a.png">

After fixing the grammar issues, the validation message appears as follows.

<img width="487" alt="Screen Shot 2019-07-23 at 12 21 09 PM" src="https://user-images.githubusercontent.com/25959096/61689533-01705b00-ad45-11e9-8952-8711eeb71d6f.png">
