### ISSUE TITLE
user info endpoint does not return claims when 'BuildSubjectIdentifierFromSPConfig' is set to true

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#5259]
In user info endpoint user realm (tenant, user store) info is identified from the 'username' claim in introspection response.
When above property is set to true, unless 'user tenant domain in subject identifier and user store domain in subject identifier' configs are not enabled for SP, that realm info user info endpoint relies on goes missing.

Thus, even though the token is valid, user info endpoint fails to return claim of the user

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
