### ISSUE TITLE
Account recovery API doc returns 404

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5260]
1. Go to https://docs.wso2.com/display/IS580/Using+the+Account+Recovery+REST+APIs

2. Click on "REST API swagger docs on account recovery. " to view the API doc. 

It says Page not found

![image](https://user-images.githubusercontent.com/5237653/57573542-c4374500-7446-11e9-9b9c-5a32944aa7d9.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
