### ISSUE TITLE
Clients within the product context should invoke APIs within the JVM

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#5264]
In IS, we have SOAP services and REST services.
Typically, client applications within the server context user local transport for SOAP services.
Yet there are places which does not do so. For example, authenticationednpoint webapp has some services which are invoked remotely.
When it comes to REST services, even there a similar pattern can be followed and OSGi services can be invoked.
So, there should be an option to let API be invoked remotely, yet by default it should be within JVM.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
