### ISSUE TITLE
Config reader of authenticationendpoint duplicated

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#5265]
Authentication endpoint web app includes several manager classes like TenantManager, MutualSSLManager, etc, that reads the same config file.
It would be better to have a one configuration manager and that to be used in each based on their usecases

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
