### ISSUE TITLE
Tool -> SAML Response Builder is not generating Claims [IS - 5.3]

### ISSUE THREAD

**Issue by ghost** [wso2/product-is#5268]
Hi Team,

Seems the SAML Response Builder tool is not generating the response with the declared claims (Claim Mapping) that are defined in a Service Provider even after enabling **Enable Attribute Profile**. 

Tested version of IS: 5.3.

Regards,
Anupam G
WSO2- Brazil

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
