### ISSUE TITLE
IdP Entitlement Decision cache not work as expected in clustering environmnet

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5269]
The issue is related to IS 5.1.0.
Steps to reproduce the issue. Setup node IS cluster (5.1.0)

Test Case 1

1. Update policy SOAP request sends to node1.
2. Publish policy SOAP request sends to node1
3. XACMLDecisionQuery SOAP request sends to node 2.
4.XACMLAuthzDecisionQuery returns incorrect output which sends to node 2

Test Case 2

1. Update policy SOAP request sends to node1.
2. Publish policy SOAP request sends to node 2
3. XACMLDecisionQuery SOAP request sends to node 1.
4.XACMLAuthzDecisionQuery returns incorrect output which sends to node 1

**Comment by thushaaanthan** [comment]
Fixed: https://github.com/wso2/product-is/issues/5310
