### ISSUE TITLE
SAML2SSOAuthenticator isHandle method needs to be implement properly

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#5271]
Currently the **isHandle** method does not check any conditions [1]. Therefore if the Authenticators propriety is high, even the admins service calls with the basic auth will be picked up by SAMLSSOAuthenticator. 

As a workaround we can set the priority of the SAML2SSOAuthenticator to 0 as below,

<CARBON_HOME>/repository/conf/security/authenticators.xml

```
<Authenticator name="SAML2SSOAuthenticator" disabled="false">
        <Priority>0</Priority>
        <Config>
            <Parameter name="LoginPage">/carbon/admin/login.jsp</Parameter>
            <Parameter name="ServiceProviderID">carbonServer</Parameter>
            <Parameter name="IdentityProviderSSOServiceURL">https://localhost:9443/samlsso</Parameter>
            <Parameter name="NameIDPolicyFormat">urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</Parameter>
            <Parameter name="AssertionConsumerServiceURL">https://localhost:9443/acs</Parameter>
	</Config>
</Authenticator>
```

But we need to fix the isHandle method properly as the permeant solution.

[1] https://github.com/wso2-extensions/identity-carbon-auth-saml2/blob/master/components/org.wso2.carbon.identity.authenticator.saml2.sso/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/SAML2SSOAuthenticator.java#L266

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
