### ISSUE TITLE
Need to change the priority of the SAML2SSOAuthenticator

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#5272]
As a workaround for this [issue](https://github.com/wso2/product-is/issues/5271) [1] we need to set the priority of the SAML2SSOAuthenticator to 0 as below,

<CARBON_HOME>/repository/conf/security/authenticators.xml
```xml
<Authenticator name="SAML2SSOAuthenticator" disabled="false">
        <Priority>0</Priority>
        <Config>
            <Parameter name="LoginPage">/carbon/admin/login.jsp</Parameter>
            <Parameter name="ServiceProviderID">carbonServer</Parameter>
            <Parameter name="IdentityProviderSSOServiceURL">https://localhost:9443/samlsso</Parameter>
            <Parameter name="NameIDPolicyFormat">urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</Parameter>
            <Parameter name="AssertionConsumerServiceURL">https://localhost:9443/acs</Parameter>
	</Config>
</Authenticator>
```

This need to be mentioned in the documentation[2] until the issue [1] is fixed.

[1] https://github.com/wso2/product-is/issues/5271
[2]https://docs.wso2.com/display/ADMIN44x/Configuring+SAML2+Single-Sign-On+Across+Different+WSO2+Products

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
