### ISSUE TITLE
Saving old access tokens in audit table is enabled by default.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5274]
By default following are the configurations sent with the IS pack in identity.xml file.
```
<!-- Token cleanup feature config to clean IDN_OAUTH2_ACCESS_TOKEN table-->
<TokenCleanup>
    <!--If true old access token cleaning feature is enabled -->
    <EnableTokenCleanup>true</EnableTokenCleanup>
    <!--If true  old access token retained in audit table  -->
    <RetainOldAccessToken>true</RetainOldAccessToken>
</TokenCleanup>
```
Enabling token cleanup by default is acceptable but keeping the old data in the audit table is not, IMHO. With this property, we're just moving tokens from one table to another and will cause DB growth issues in the long run. If someone wants these data, they should go ahead and enable it specifically knowing the consequences.

**Comment by ruwanta** [comment]
+1, please do this before next milestone release.
