### ISSUE TITLE
[DOC] Improve cipher tool documentation for EndpointConfig.properties

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5275]
The cipher tool usage for EndpointConfig.properties file is a bit confusing.
current doc: https://docs.wso2.com/display/ADMIN44x/Encrypting+Passwords+with+Cipher+Tool

We also need to mention in the doc that the following property needs to be added to EndpointConfig.properties file(Needed only after IS580)

`secretProvider=org.wso2.securevault.secret.handler.SecretManagerSecretCallbackHandler`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
