### ISSUE TITLE
Make NameFormat in AttributeStatement configurable. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5281]
Identity server doesn't support NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri in AttributeStatement .

By default, it is set to 'urn:oasis:names:tc:SAML:2.0:attrname-format:basic'

**Comment by janakamarasena** [comment]
Related issue https://github.com/wso2/product-is/issues/4299

**Comment by janakamarasena** [comment]
Closing as duplicate
