### ISSUE TITLE
Support PKI mutual TLS OAuth client authentication  approach for Mutual TLS for OAuth Clients

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5285]
Current Identity Server does not support PKI mutual TLS OAuth client authentication approach for Mutual TLS for OAuth Clients.

Type/Improvement  
Affected/5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
