### ISSUE TITLE
[Doc] Samples need to be updated in "2-legged OAuth for Securing a RESTful Service"

### ISSUE THREAD

**Issue by arunans23** [wso2/product-is#5291]
https://docs.wso2.com/display/IS570/2-legged+OAuth+for+Securing+a+RESTful+Service

In the above documentation, the following issues are there.

- In Step 10, it is mentioned that the proxy configuration can be added in ESB via Manage > Service Bus > Source View.  But that Source View is Read Only and you cannot add the proxy that way. You have to go to Manage > Services > Add > Proxy Service to do that.

- Also in Step 10, it says we can alternatively update the configuration org.wso2.carbon.identity.samples.oauth/src/main/resources/synapse.xml. It is not quite clear, how updating a configuration in that file would get hosted in an ESB automatically without we adding them there.

- In the Proxy Sample given under Step 10, the line `<oauthService remoteServiceUrl="https://localhost:9443/services/"/>` is wrong because you cannot create a oauthService mediator without giving a username and password attributes. Correct way should be `<oauthService remoteServiceUrl="https://localhost:9443/services/" username="foo" password="bar"/>`

- In step 6, the sample taken from the svn also have some flaws. In TwoLeggedOAuthDemo.java class, line 150 it is creating a URL as `String baseString = ESB_SERVER + "services/OAuthTest/greet?name="+ param;` It is wrong because the Proxy we are creating is **OAuthProxy** and not **OAuthTest**.

- Also in the same code line 48, the port of the identity server should be 9443, not 9444. `private static final String IDENTITY_SERVER = "https://127.0.0.1:9443/"`

- In Step 11, running the sample client has some ambiguous terms. For example it is not clear what jars to add and how to add to the project.

Even though the functionality is working, it is quite hard to get it done for the first time because of the shortcomings in the documentation and the sample. It would be helpful for the user if the above issues can be solved.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
