### ISSUE TITLE
sendError method should return all parameters as uri fragments if required

### ISSUE THREAD

**Issue by abhishekdesilva** [wso2/product-is#5293]
In script-based adaptive authentication, we can return the error response with uri fragments if needed. In order to do that, please follow the below procedure.

1. Create the error page url as below.

> var errorPage = "https://www.sample.me#errorcode=404&errorMsg=Simple%20Error%20Message";

2. Add this errorPage to the sendError method with empty error page parameters.

> sendError(errorPage, {});

By doing so, we can get a redirect url something similar to the following.

>  https://www.sample.me/?#errorcode=404&errorMsg=Simple%20Error%20Message?sp=travelocity.com&tenantDomain=carbon.super

As you can see, the **errorcode** and the **errorMsg** is appended as uri fragments but the **sp** and the **tenantDomain** is added as query parameters.

This is a violation of OIDC spec section 3.3.2.6 [1] of how the error is returned to the client.

The [2] is appending the service provider and the tenant domain to the redirect URL as query parameters. There should be another condition check for the # key/symbol. If the uri contains the # key/symbol, the sp and tenantDomain should added as uri fragments as follows.
 
>  https://www.sample.me/?#errorcode=404&errorMsg=Simple%20Error%20Message&sp=travelocity.com&tenantDomain=carbon.super

[1] https://openid.net/specs/openid-connect-core-1_0.html#HybridAuthError
[2] https://github.com/abhishekdesilva/carbon-identity-framework-1/blob/support-5.12.153/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkUtils.java#L565

**Comment by ruwanta** [comment]
Closing as all pull requests are merged.
