### ISSUE TITLE
Refactor and improve hybrid data are handling 

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/product-is#5294]
A good example for this is the reported issue on addRememberMe functionality. At the moment it is built into UserStoreManager. But underlying data is stored in UM_HYBRID_REMEMBER_ME  table. This has been already reported #5181. 

Ideally, our architecture needs to be refactored and improved to separate hybrid data handling from current implementation. 

Label suggestions - Complexity : High , Priority : Medium , Type : Improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
