### ISSUE TITLE
I am following the document guide of WSO IS 5.7.0 and could not find OpenLDAP version mentioned. This link https://docs.wso2.com/display/IS570/Deployment+Patterns suggests ldap v2 and v3 but the original version used is not found.

### ISSUE THREAD

**Issue by Jagatjot** [wso2/product-is#5296]

**Comment by omindu** [comment]
Hi @Jagatjot 

The document mentions the supported version of the LDAP specification. If you are planning to use OpenLDAP, you can use OpenLDAP 2.x which support LDAPv3 [1]

[1] - https://www.openldap.org/faq/data/cache/162.html
