### ISSUE TITLE
CON_APP_KEY constraint violation recovery doesn't work with PostgreSQl

### ISSUE THREAD

**Issue by kavishkafernando** [wso2/product-is#5297]
Recover method uses the same connection as the one caused the CON_APP_KEY constraint failure for recovery attempts as well. This doesn't work in Postgres. 

**OS, DB, other environment details and versions:** DB : PostgreSQL

**Steps to reproduce:**
Use PostgreSQL as Identity DB.
Do a load test with refresh grant or any other method that will violate the CON_APP_KEY constraint.

**Comment by mefarazath** [comment]
Related to https://github.com/wso2/product-apim/issues/4698

**Comment by IshikaGodage** [comment]
After having a CON_APP_KEY constraint failure, Can you please explain what happens to the connection ?

**Comment by kavishkafernando** [comment]
Issue 
Recover method uses the same connection as the one that causes the CON_APP_KEY constraint failure for recovery attempts as well. This doesn't work in Postgre. If there was a previous error, use a new connection.
Fix :
Check if connection is Postgre. If yes, close existing connections. Create new connection and do the recovery.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/434
