### ISSUE TITLE
[DOC] recommendations for configuring defaultAutoCommit and commitOnReturn parameters for PostgreSQL

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5306]
it's not required to set the defaultAutoCommit to True for WSO2 products, Hence recommendation is to set the defaultAutoCommit to False all the time unless there is a special case where WSO2 team may be requested to set it True for verify certain issues related to the database. The underneath logic is to keep the defaultAutoCommit false for WSO2 products is that because of the SQL commit is handled within the application code of WSO2 products for most of the DML statements (INSERTS, UPDATES or DELETE ).

However, we have encountered some issues with certain database types like Postgres, where the selects statements would also need to be committed to end its transaction before return it to the connection pool. 
Otherwise, the particular transactions will be kept open in Postgres end.
Since the default execution of a select statement does not require commit after its execution, we have not explicitly committed each and every select statement in our code base and it causes issues.

Therefore, to address the mentioned issues we are recommending to use the commitOnReturn parameter to be True. So that when the connection is returned into the pool, the particular connection will be committed hence the Postgres would know that the transaction is also completed from database end.

Following are the recommended sample data source configuration for defaultAutoCommit and commitOnReturn parameters

<PRODUCT_HOME>/repository/conf/datasources/master-datasources.xml file
```
<datasource>
     ...
     <definition type="RDBMS">
         <configuration>
               ...
               <defaultAutoCommit>false</defaultAutoCommit>
               <commitOnReturn>true</commitOnReturn>   
               ...
         </configuration>
     </definition>
</datasource>
```

Products: Identity Server and API Manager

**Comment by dmxunlimit** [comment]
Following are the PostgreSQL specific parameters which are required.
 
`<validationQuery>SELECT 1; COMMIT</validationQuery>`
`<defaultAutoCommit>false</defaultAutoCommit>`
`<commitOnReturn>true</commitOnReturn>`
`<rollbackOnReturn>false</rollbackOnReturn>`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
