### ISSUE TITLE
PDP Caches are not sync inside the clustered environment environment

### ISSUE THREAD

**Issue by thushaaanthan** [wso2/product-is#5310]
Description:
use e.g. 'updatePolicy' and 'publishToPDP' (of the 'EntitlementPolicyAdminService' service) to publish changes for a certain policy.
After doing this, we notice that the changes aren't being activated every time (when performing an 'EntitlementService\XACMLAuthzDecisionQuery' afterward), although the Entitlement PDP Policy View shows the right version.
Doing a 'Clear Decision Cache' and/or a 'Clear Attribute Cache' doesn't help. It looks like the only thing that always works is restarting the service and then performing the Clear Caches."

issue: https://wso2.org/jira/browse/IDENTITY-5812

**Comment by thushaaanthan** [comment]
Fix : https://github.com/wso2/carbon-identity-framework/pull/863
Improvement: https://github.com/wso2/carbon-identity-framework/pull/867

**Comment by madurangasiriwardena** [comment]
Duplicate of https://github.com/wso2/product-is/issues/5269
