### ISSUE TITLE
Move registry based relying party URL configuration to service provider configuration

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5311]
Refer: https://docs.wso2.com/display/IS540/Customizing+the+Authentication+Endpoint#CustomizingtheAuthenticationEndpoint-Handlingbrowserbackbuttonandbookmarkedloginpage

**Comment by mefarazath** [comment]
We need to think about the migration from registry based configs too.

**Comment by malithie** [comment]
Fixing this would require to below.
1. Changing the persistence layer to persist the request initiation URI as SP related properties rather than registry
2. Support configuring the request initiation URI via UI under service provider configurations

**Comment by abhi4u1947** [comment]
Very important improvement, currently its tedious and also complex additional effort for DCR use cases.

**Comment by ayshsandu** [comment]
We can rely on the discoverable url of the application for this.

**Comment by mefarazath** [comment]
@ayshsandu you mean the access URL of the service provider?

**Comment by ayshsandu** [comment]
> @ayshsandu you mean the access URL of the service provider?

Yes.

**Comment by ayshsandu** [comment]
Fixed in following PRs
 - https://github.com/wso2/carbon-identity-framework/pull/3274
 - https://github.com/wso2/product-is/issues/10667

Migration effort is captured in https://github.com/wso2/product-is/issues/10667
