### ISSUE TITLE
Identity server 5.7 Update-Username Rest API endpoint gives 404

### ISSUE THREAD

**Issue by waqasalirazzaq** [wso2/product-is#5313]
Hi,

I am trying wso2 identity server 5.7 self sign up rest api. As per documentation https://docs.wso2.com/display/IS570/apidocs/self-registration/#!/operations#UsernameUpdate#updateUsernamePut Update username api should be available.

But when I try to invoke the api endpoint given in the above documentation. it gives 404 error. I checked the war file in webapps and seems like the api resource is not there.

Can you please check and let me know how to use this feature to change the usernames?

Thanks!

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
