### ISSUE TITLE
Unable to register U2F device in the dashboard

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5316]
Applicable versions - All Identity Server versions (regular, WUM updated) 
1.Log into the WSO2 Identity Server end-user dashboard.
2. Navigate to the My Profile section by clicking the associated View Details button.
3. Click Manage U2F Authentication.
4. Then touch the 'key' icon on the FIDO device and click attach fido token button.
5. U2F device in the dashboard not getting registered

When debugging js we have observed the following error.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null').

This is caused due to u2f API change please refer [1], [2] and [3]

[1] https://github.com/google/u2f-ref-code/issues/174
[2] https://github.com/google/u2f-ref-code/issues/107
[3] https://groups.google.com/a/fidoalliance.org/forum/#!topic/fido-dev/HeNBVRosRGs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
