### ISSUE TITLE
Regex Bug in Shindig URL white listing 

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5322]
Regex built by the [getURIRegex](https://github.com/wso2/wso2-shindig/blob/2.5.2-wso2/java/wso2-ext/src/main/java/org/apache/shindig/wso2/ext/impl/WhitelistImpl.java#L107) method should return a complete regex in both cases of the if-else block.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
