### ISSUE TITLE
[Doc] Update Documentation of X509Certificate Authenticator with relevant to connector version 2.0.9

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5326]
With relevant to the fix: wso2/product-is#5057 
Below Instructions should be added For the Doc [Configuring X509Certificate Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator)

**Configuring X509 authenticator to extract authenticating subject from the certificate**

Add the following configurations to the <IS_HOME>/repository/conf/identity/application-authentication.xml file under the AuthenticatorConfig name="x509CertificateAuthenticator” tag. 

- Authenticating using Subject Alternative Names

What is a Subject Alternative Name in x509 Certificate?

The Subject Alternative Name is an identifier placed in a subjectAltName extension. The Subject Alternative name extension is a standard PKIX certificate extension enabling identifiers of various types to be bound to the certificate subject -- in addition to, or in place of, identifiers that may be embedded within or provided as a certificate's subject field. According to the specification, when authenticating using the subject attribute, priority should be given to the subject alternative names. 

` <Parameter name="AlternativeNamesRegex">^[a-zA-Z]{3}$</Parameter>
`

Without this configuration the system will not check for the alternative names in the certificate. 
When the configuration is present in the application-authentication.xml file,  and when there are no alternative names in the certificate or when there are no matching string to the given pattern in alternative names of the certificate or if there is more than one match to the given pattern in alternative names  the system will throw an error and authentication process will fail. If there is one match to the given pattern, that match will be used as the username and the systems attempts to authenticate the user. If there is a user in the system with that given username, the user will get authenticated. 

- Authenticate using specific string value of subject DN

	`<Parameter name="UsernameRegex">[a-zA-Z]{3}</Parameter> `

When this configuration is present in the application-authentication.xml file,  the system will get the matching string from the subject DN. That will be used as the username to authenticate. If more than one match found or there are no matches found, the system will throw an error and fail the authentication process. 

Note: If you are authenticating a user in  tenant mode,the tenant domain must  be present in the certificate and the regex should be capable of extracting  the string with the tenant domain. The same applies when the user is in a secondary user store.

Example : 
For a user in a tenant domain abc.com
[a-z]{9}@[a-z]{3}.[a-z]{3}   -   buddhimau@abc.com
For a user in a secondary user store TEST
[A-Z]{4}\/[a-z]{9}     	  -    TEST/buddhimau

**Comment by Buddhimah** [comment]
Updated the documentation waiting for doc team review 
[https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator)

**Comment by YvonneW** [comment]
The [content](https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator#ConfiguringX509CertificateAuthenticator-Extendingtheauthenticator) has been reviewed and rephrased. Please check. 

In addition, the [5.9.0 docs](https://is.docs.wso2.com/en/5.9.0/develop/x509certificate-authenticator/) will also have to be updated accordingly.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
