### ISSUE TITLE
Ability to manage service provider properties from the management console

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5330]
The `IdentityApplicationManagementService` supports setting additional SP properties for an SP.

It would be nice to have this functionality in SP UI as well.

**Comment by hauntingEcho** [comment]
Ideally, this could be used to manage arbitrary properties (which may or may not have already been managed via `IdentityApplicationManagementService`).  From my perspective, an implementation similar to the current role-mapping menu would be fantastic.

My particular use case is configuring a URL & Logo for an application-menu dashboard widget

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
