### ISSUE TITLE
Unable to update EmailOTP template via management console

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5334]
**Summary**
It is not possible to update the email template for EmailOTP from the management console. It always read from the email-admin-config.xml file and send the email.

**Analysis**
In the email OTP authenticator, we have following dependency [1].
```
<dependency>
    <groupId>org.wso2.carbon.identity</groupId>
    <artifactId>org.wso2.carbon.identity.mgt</artifactId>
    <version>5.0.7</version>
    <scope>provided</scope>
</dependency>
```
And it uses ConfigBuilder class from there to fetch the email templates from the registry. But, it has an incorrect regitry path [2] which is not available in newer IS versions. Therefore, when the registry returns not found, it reads from the config file and returns the default template on the file always.

[1] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/v2.0.15/pom.xml
[2] https://github.com/wso2-attic/carbon-identity/blob/v5.0.7/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/config/ConfigBuilder.java#L45

**Comment by mefarazath** [comment]
Looks like the email otp authenticator is using the old email template management features.

**Comment by rksk** [comment]
> Looks like the email otp authenticator is using the old email template management features.
We have the same incorrect path in the latest code as well [1].

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/config/ConfigBuilder.java#L45

**Comment by LahiruLS** [comment]
Yes, I also tried the scenario too it is not working and apart from that try to use a CDATA tag and set an HTML page as an OTP template. Seems HTML is not identified as a HTML. So we can not use HTML styling and deal with plain text template as well :(

**Comment by mefarazath** [comment]
Okay. So this looks like something that needs to be fixed. Which version did you try this out with?

**Comment by mefarazath** [comment]
@IsuraD @ayshsandu

**Comment by IsuraD** [comment]
@LahiruLS , How did you update the template? have you enabled the old email template module form carbon.xml file?

**Comment by LahiruLS** [comment]
@IsuraD I have checked with the old way to change the email template too. But it is causing an exception due to the issue in REG_PROPERTY table contains less character space to store the template. As @rksk pointed out we are trying to access the wrong path. it is trying the old reg path(/_system/config/identity/config/ ) according to the code.

**Comment by LahiruLS** [comment]
@IsuraD and @mefarazath After adding the following parameter to the 
<Parameter name="useEventHandlerBasedEmailSender">true</Parameter>
IS_HOME>/repository/conf/identity/application-authentication.xml AuthenticationConfig element. It is working as expected. 

This is only mentioned in the git hu docs: https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/docs/html-support.md
I will close this issue.

**Comment by rksk** [comment]
Possible duplicate https://github.com/wso2/product-is/issues/1598

**Comment by rksk** [comment]
If we are to close this issue, we have to enable "useEventHandlerBasedEmailSender" by default or fix the above-mentioned issue from the code level.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
