### ISSUE TITLE
Role based scope validation failure with Implicit Grant

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5335]
**Description**

Role based scope validation fails in Implicit Grant. When roles in scope do not match to any roles in user, still an access token is issued to the user without giving "Invalid Scope" error.

**Steps to reproduce the issue**

- Create a new Service Provider with 'Role-based scope validator' option.
- Create a scope[1] but do not map to any role in the scope with WSO2 IS Scope Management.
`curl -k -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"name": "test_scope", "displayName": "test_scope", "description": "testing", "bindings": ["role1", "role2"]}' "https://localhost:9443/api/identity/oauth2/v1.0/scopes"`
- Invoke the authorize endpoint with `test_scope` scope to generate token with the implicit grant type.
`https://localhost:9443/oauth2/authorize?response_type=token&client_id=CLIENT_ID&nonce=abc&redirect_uri=CALLBACK_URL&scope=test_scope`

- Then an access token will be issued without giving an error.

[1] - [https://docs.wso2.com/display/IS570/apidocs/OAuth2-scope-endpoint/index.html#!/operations#ScopeManagement#registerScope](https://docs.wso2.com/display/IS570/apidocs/OAuth2-scope-endpoint/index.html#!/operations#ScopeManagement#registerScope)

**Suggested Labels**
Type/Bug
Affected/5.7.0

**Comment by vihanga-liyanage** [comment]
Once this is fixed, playground application also has to be updated to cater to the new behavior.
