### ISSUE TITLE
Change How We Store Access Tokens in the Database.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5336]
### Problem Definition
- In the beginning, we only had OPAC (UUID) tokens. When we're issuing a new token, we just stored the token string in ACCESS_TOKEN column of our database and we used the same token string as the cache key.
- Then came JWT access tokens, which the token string is quite large compared to UUID token. Therefore, storing it directly in the database caused problems. As a solution, we used the JTI claim value as a representation of the token and stored this in the ACCESS_TOKEN column.
- Since we have two different behaviors regards to tokens, now we had to decide what type of token came to the server during token validation calls (such as introspect) in order to extract the value to match with the DB. In order to identify whether a token is JWT or not, we looked for periods (.) in the coming token string.
- This broke when a customer came with his own token issuer, which issues compressed JWT tokens. These tokens had the right amount of periods but they were not parsable as usual JWT tokens.
- As a solution, we implemented a chaining logic, where we try all available token issuers one by one until a parsable issuer is found. If one parser throws an exception, we continue the loop and checks with the next token issuer.
- This also broke when another customer came with his own JWT token issuer which issued usual JWT tokens that did not contain a JTI value. Our own JWTTokenIssuer can parse these tokens and therefore we pick it and continue the flow. When we try to extract the JTI value to lookup, we get nothing and flow breaks.
### Proposed Solution
- We think we're facing these regression issues because we didn't go with a proper design in the first place. The original issue was that we cannot store JWT token string directly in the DB as it is too large.
- As a solution, we propose to hash the token and store it in a new column we'd like to call LOOKUP_HASH. Either it's a UUID or JWT or something else, we use the same hash function to get the hash and store it in this column. 
- Whenever a token validation call comes, we do the same again. Hash the token string and lookup. Cache keys should also be this same token hash value.
- When issuing a new token, we can store the real token in the ACCESS_TOKEN column if it's a UUID token, which is used to send the same token if the same request came again. In JWT case, we can store anything, since it doesn't serve any purpose.

PS. We already have an ACCESS_TOKEN_HASH column, which is not search-friendly since it is a JSON value. I hope we can do something about that too.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
