### ISSUE TITLE
Account Lock feature of WSO2 doesn’t work properly

### ISSUE THREAD

**Issue by SwatiNEC** [wso2/product-is#5338]
Hi 

while using account lock feature of wso2, if user account is locked due to failed login attempt then even after the account lock time expires user account remains locked.
I am using wso2-is_km5.7.0, wso2-am2.6.0, LDAP 2.4.48 and mysql 5.7.
I have followed the below documents for enabling the account lock and sharing the user store:
[Account lock feature](https://docs.wso2.com/display/IS570/Account+Locking+by+Failed+Login+Attempts)
[Sharing user store only](https://docs.wso2.com/display/AM210/Configuring+Identity+Server+as+IDP+for+SSO#ConfiguringIdentityServerasIDPforSSO-Sharingtheuserstore)

I have followed the below document for LDAP configuration:
[LDAP configuration](https://docs.wso2.com/display/IS500/Configuring+a+Read-write+LDAP+User+Store)

Steps to reproduce:
1) User try to login at IS with incorrect credentials 3 times.
2) After 3rd attempt user account is locked.
3) When account lock time expires even then user is not able to login on both IS and APIM.

[Actual Behavior]:
Following logs will be displayed on IS when user try to login on IS:
> [2019-05-27 09:29:28,396] DEBUG {org.wso2.carbon.identity.claim.metadata.mgt.DefaultClaimMetadataStore} -  Assigned mapped attribute : failedLockoutCount from user store domain : PRIMARY for claim : http://wso2.org/claims/identity/failedLoginLockoutCount in tenant : -1234
> [2019-05-27 09:29:28,398] ERROR {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} -  System error while Authenticating/Authorizing User : Error when handling event : POST_AUTHENTICATION

logs on APIM, when user try to login on APIM:

> [2019-05-27 07:25:19,314] DEBUG - DefaultClaimMetadataStore Assigned mapped attribute : lastLogonTime from user store domain : PRIMARY for claim : http://wso2.org/claims/identity/lastLogonTime in tenant : -1234
> [2019-05-27 07:25:19,316] DEBUG - ReadWriteLDAPUserStoreManager One or more attributes you are trying to add/update are not supported by underlying LDAP for user : admin
> javax.naming.directory.InvalidAttributeIdentifierException: [LDAP: error code 17 - lockedReason: attribute type undefined]; remaining name 'cn=admin'
>         at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3223)
>         at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
>         at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
>         at com.sun.jndi.ldap.LdapCtx.c_modifyAttributes(LdapCtx.java:1408)
> [2019-05-27 07:25:19,322] ERROR - AuthenticationAdmin System error while Authenticating/Authorizing User : Error while saving user store data : http://wso2.org/claims/identity/lastLogonTime for user : admin.
> org.wso2.carbon.user.core.UserStoreException: Error while saving user store data : http://wso2.org/claims/identity/lastLogonTime for user : admin.
> Caused by: org.wso2.carbon.identity.base.IdentityException: Error while persisting identity user data in to user store for user: admin
>         at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:60)
> Caused by: javax.naming.directory.InvalidAttributeIdentifierException: [LDAP: error code 17 - lockedReason: attribute type undefined]; remaining name 'cn=admin'
>         at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3223)
>         at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
>         at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
>         at com.sun.jndi.ldap.LdapCtx.c_modifyAttributes(LdapCtx.java:1408)
>         at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_modifyAttributes(ComponentDirContext.java:257)
>         at org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager.doSetUserClaimValues(ReadWriteLDAPUserStoreManager.java:941)
>         ... 86 more

[Expected Behavior]:
User should be able to successfully login after Account lock time expires.

Note: As per my analysis, account lock feature is working properly with mysql but it displays error when I use LDAP.

**Comment by mefarazath** [comment]
Can you check the mapped attribute of the claim http://wso2.org/claims/identity/lastLogonTime?
Looks like it is mapped to an attribute not supported by the LDAP.

Refer: https://docs.wso2.com/display/IS570/Configuring+Claims

**Comment by SwatiNEC** [comment]
Hi 

I have checked the claim-config.xml for claim mapping. It is same as mentioned on below link
 [claim-config](https://docs.wso2.com/display/IS570/Configuring+Claims)

And as per my understanding if there is problem in storing claim `http://wso2.org/claims/identity/lastLogonTime` in LDAP then there will be an error when user login on IS/APIM, But at the time of login this field is updated properly in LDAP.

**Comment by SwatiNEC** [comment]
Hi @mefarazath 

As per my investigation, if i will configure account locking in WSO2 IS as per given document provided for WSO2 IS 5.7.0 :
https://docs.wso2.com/display/IS570/Account+Locking+by+Failed+Login+Attempts

then account is not unlocked after unlockTime expires But if I configure WSO2 IS as per document provided for WSO2 IS 5.2.0 given at below link:
https://docs.wso2.com/display/IS520/User+Account+Locking+and+Account+Disabling

then it works properly.
Could you please suggest?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
