### ISSUE TITLE
Change SAML Outbound Authenticator development branch

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5342]
Currently the active development of https://github.com/wso2-extensions/identity-outbound-auth-samlsso happens in the 5.1.x branch. The master branch contains C5 related development which were halted.

Since C5 development is abandoned for IS. We need to to make the 5.1.x branch to be the master.

This task involves

1. Taking a backup branch of c5 development. This is already done with https://github.com/wso2-extensions/identity-outbound-auth-samlsso/tree/6.x.x
2. Create the new master branch from 5.1.x branch. Delete the 5.1.x branch
3. Amending the Jenkins build jobs. 
4. Sending out a mail in dev@wso2.org with information on the changes done.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
