### ISSUE TITLE
Refactor oAuth cache token with Cachedback DAO

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5343]
The token cache implementation need to be refactored in the OAuth module by moving all the token related cache actions to the cached back DAO(before the actual DAO, we will have a cached layer. All the cache operation needs to be handled in that layer).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
