### ISSUE TITLE
Application/<SP_Name>' role incorporates an implicit permission which is not reflected in UI

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#5345]
'Application/<SP_Name>' incorporates an implicit permission, that associates with the respective service provider.
But, in UI it is still reflected as a role and there won't be any permissions associated to that which might being confusions on the use of that role.

It's a fact that it is of specific type 'Application', but nothing in UI which denotes the implicit permission that it carries.

**Comment by hauntingEcho** [comment]
this has caused some confusion for us - particularly interpretations that the `Application/<SP_NAME>` role does not do anything and can be repurposed or deleted, as it carries no permissions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
