### ISSUE TITLE
[Doc Update] Update Documentation of OAuthTokenGenerator extension point and Self-contained accesstoken

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5347]
https://docs.wso2.com/display/IS570/Self-contained+Access+Tokens
https://docs.wso2.com/display/IS570/Extension+Points+for+OAuth#ExtensionPointsforOAuth-OAuthTokenGenerator

In these above documents related to OAuthTokenGenerators, the following issue was found.

Once the custom OAuthTokenGenerator added in the identity.xml file, we need to configure the relevant token Issuer in identity inbound Authentication configurations under service provider configs 
So now we have to go to the service provider> Inbound Authentication Configuration > OAuth/OpenID Connect Configuration > Token Issuer and select the Token Issuer configured. 

Without adding that configs in service provider, the changes in the token issuer will not be reflected for the service provider.

This need to be added in the document.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
