### ISSUE TITLE
source jars not attached to transitive orbit dependencies

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#5349]
When attempting to write a carbon plugin piggybacking off of the `org.wso2.carbon.identity.application.mgt` backend, the source of transitive dependency `org.wso2.orbit.org.owasp.encoder:encoder:1.2.0.wso2v1` is not available with the maven artifact.  This prevents the use of IDE autocomplete and documentation features.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
