### ISSUE TITLE
[IS-5.6.0] Cache Configuration Timeouts values are not reading when isDistributed="false"

### ISSUE THREAD

**Issue by npamudika** [wso2/product-is#5350]
There is an issue in reading cache configuration timeout values when **isDistributed** has been set to "**false**" in identity.xml file for the IS 5.6.0 version. The impact of this is, when isDistributed="false", the cache timeout values are not being set to the values we set in the below section and it will be set to the default cache timeouts.

> <CacheManager name="IdentityApplicationManagementCacheManager">
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="AppAuthFrameworkSessionContextCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="AuthenticationContextCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="AuthenticationRequestCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="AuthenticationResultCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="AppInfoCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="AuthorizationGrantCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="OAuthCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="OAuthScopeCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="OAuthSessionDataCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="SAMLSSOParticipantCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="SAMLSSOSessionIndexCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="SAMLSSOSessionDataCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="ServiceProviderCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="ProvisioningConnectorCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="ProvisioningEntityCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="ServiceProviderProvisioningConnectorCache" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="IdPCacheByAuthProperty" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="IdPCacheByHRI" timeout="1"/>
        <Cache capacity="5000" enable="true" isDistributed="false"
            name="IdPCacheByName" timeout="1"/>
 </CacheManager>

**Comment by IshikaGodage** [comment]
The above issue has been fixed already by [1].
[1][https://github.com/wso2/carbon-identity-framework/pull/913](https://github.com/wso2/carbon-identity-framework/pull/913)

**Comment by Prasadi-R** [comment]
The above issue has not been fixed in the IS 5.2.0 version.

**Comment by isuruirj** [comment]
This needs to be fixed in IS-5.3.0 as well.
