### ISSUE TITLE
Give priority to custom header over request attribute in X509CertificateAuthenticationValve

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#5351]
X509CertificateAuthenticationValve allows to pass the client's TLS certificate in a custom header in the case of SSL termination at LB.

In the case where client authentication is enabled in IS catalina-server.xml file, SSL handshake will happen between IS and LB, and as a result LB's certificate will be available as a request attribute. 

In the authenticator, we are only extracting the client certificate from header only if the certificate is not available in request attributes [1]. However in the above case LB's certificate will be available in request attributes. Therefore it would be better if we change the order to first check the certificate in the custom header and if not present proceed with the certificate in request attribute. 

[1] https://github.com/wso2-extensions/identity-x509-commons/blob/master/components/valve/src/main/java/org/wso2/carbon/extension/identity/x509Certificate/valve/X509CertificateAuthenticationValve.java#L69

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
