### ISSUE TITLE
Description and Internationalization for OAuth2 Scopes

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#5354]
The OAuth2 scopes implementation in IS doesn't support providing a human readable description that can be shown in to the end-user when providing consent.

The description should also support internationalization as in challenge questions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
