### ISSUE TITLE
XACML policy based scope validation during Access Token Issuing Phase and code issuing phase

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5358]
Identity Server supports XACML based scope authorization during access token validation phase. But it is important to have XACML based scope authorization during access token issuing phase also.

According to the spec, the scope is optional in the authorization request [1]. But authorization response should contain error response as invalid_scope if the requested scope is invalid, unknown, or malformed [2].

**Authorization code grant:**
Authorize request: scope is optional [1]
Authorize response:authorization response should contain error response as invalid_scope if the requested scope is invalid, unknown, or malformed [2]
Accesstoken request : Not mentioned about scope [3]
Access token response : Not mentioned about error response when scope is invalid [4]

Role based scope validation : Currently we are validating scope when issuing access tokens, and not when we are issuing authorization code. But according to the spec, we should do scope validation when issing authorization code as well
XACML based scope validation : Currently we are not validating when issuing authorization code or access token. We do scope validation when validating access token only.

**Implicit flow:**
Authorize request: scope is optional [5]
Access token response : scope is OPTIONAL, if identical to the scope requested by the client; otherwise, REQUIRED. 
Error response:  invalid_scope if the requested scope is invalid, unknown, or malformed.

Role based and XACML based scope validation : Currently, Both validators do not validate the scope when issuing access token 

**Client credential, Password grant flow:**
Authorize request:  scope is optional in the token request. 
Error response : invalid_scope If The requested scope is invalid, unknown, malformed, or exceeds the scope granted by the resource owner.[7][8][9]

Role based scope validation : Currently we are validating scope when issuing access tokens.
XACML based scope validation : Currently we are not validating when issuing access token. We do scope validation when validating access token only.

As a fix
For authorization code flow, We need to validate scope when issuing authorization code and issuing access tokens in Role-based scope validator and XACML based scope validator. For authorize request in Authorization code grant, we need to validate the scope if the scope is set as a request parameter and return the response as invalid_scope if the scope is invalid. If the request is not set as a request parameter then we should not do scope validation. We will do the same thing for the token request as well.

For implicit flow, client credentials and password grant, we have to validate scope when issuing access tokens in Role-based scope validator and XACML based scope validator. Here have to validate the scope if the scope is set as a request parameter and return error response as invalid_scope if the scope is invalid. If the authorization request doesn't have scope as request parameter, then we should not do scope validation.

1]https://tools.ietf.org/html/rfc6749#section-4.1.1
[2]https://tools.ietf.org/html/rfc6749#section-4.1.2
[3]https://tools.ietf.org/html/rfc6749#section-4.1.3
[4]https://tools.ietf.org/html/rfc6749#section-4.1.4

[5]https://tools.ietf.org/html/rfc6749#section-4.2.1
[6]https://tools.ietf.org/html/rfc6749#section-4.2.2.1

[7]https://tools.ietf.org/html/rfc6749#section-4.4.1
[8]https://tools.ietf.org/html/rfc6749#section-4.3.2
[9]https://tools.ietf.org/html/rfc6749#section-5.2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
