### ISSUE TITLE
Throw specific exception when creating internal role

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5363]
**Description:**
Now when creating internal role common UserStoreException is thrown for all kind of role creation failures even if the role already exists in the system. So from other components unable to differentiate the error. So need to throw specific exceptions.

Related to : #https://github.com/wso2/carbon-kernel/issues/1870

**Affected Versions** - 5.7.0/5.8.0

**Comment by madurangasiriwardena** [comment]
User core API changes are added with https://github.com/wso2-support/carbon4-kernel/pull/509. We need to fix the API consumers to handle this specific error.
