### ISSUE TITLE
[Migration] OAuth2 Error response redirection behavior is changed

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5367]
The default behavior of the error response redirection in OAuth flow is changed in order to compliant with the OAuth2 specification.
A new configuration is introduced to have backward compatibility. 

**Added property,**
`<RedirectToRequestedRedirectUri>true</RedirectToRequestedRedirectUri>` under the `<OAuth>` tag in _<CARBON_HOME>/repository/conf/identity/identity.xml_ file

* Reported Issue - https://github.com/wso2/product-is/issues/5277
* Fix - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1118

Therefore the migration client and documentation should be updated accordingly

**Comment by Abilashini** [comment]
Added at https://is.docs.wso2.com/en/latest/setup/migrating-what-has-changed/#redirecting-to-callbackurl-in-oauth-flow-errors
