### ISSUE TITLE
[Doc] Improve the doc regarding the "Configuring the BPM Profile of WSO2 EI as a Workflow Engine"

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-is#5374]
Document [1] has pointed out how to configure the BPM Profile with the IS user LDAP but, role permissions are not shared by configuring only given steps. Role permissions are in the USER database; so, we have to share the IS USER database with the BPS.

Shall we add the following steps to how to share the user database which has the role permission?

- Create a database named "userdb"

- Change the master-datasources.xml (resided in <PRODUCT_HOE>/repository/conf/datasources) as follows. (need to do it in both BPS and Identify servers)

```
<datasource>
 <name>WSO2_CARBON_USER</name>
 <description>The datasource used for registry and user manager</description>
 <jndiConfig>
    <name>jdbc/WSO2CarbonDB_User</name>
 </jndiConfig>
 <definition type="RDBMS">
    <configuration>
       <url>jdbc:mysql://localhost:3306/userdb</url>
       <username>wso2carbon</username>
       <password>wso2carbon</password>
       <driverClassName>com.mysql.jdbc.Driver</driverClassName>
       <maxActive>50</maxActive>
       <maxWait>60000</maxWait>
       <testOnBorrow>true</testOnBorrow>
       <validationQuery>SELECT 1</validationQuery>
       <validationInterval>30000</validationInterval>
    </configuration>
 </definition>
</datasource>
```

- Change the user-mgt.xml (resided in <PRODUCT_HOE>/repository/conf) as follows. (need to do it in both BPS and Identify servers)
`<Property name="dataSource">jdbc/WSO2CarbonDB_User</Property>`
- Start the database with the following command. (required only in the first time)
 `sh wso2server.sh -Dsetup`

[1] - https://docs.wso2.com/display/IS570/Configuring+the+BPM+Profile+of+WSO2+EI+as+a+Workflow+Engine

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
