### ISSUE TITLE
IDP Enable/Disable Options prompts a message when click on that and gets disappear quickly

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5375]
Moved from: [https://wso2.org/jira/browse/IDENTITY-7125](https://wso2.org/jira/browse/IDENTITY-7125) & [https://wso2.org/jira/browse/IDENTITY-7138](https://wso2.org/jira/browse/IDENTITY-7138)

**Steps to recreate the issue**
1. Run the IS 5.4.0 pack
2. Configure Facebook as an IDP from the management console
3. Go to Identity providers > List option
4. There is a Disable/Enable option for the created IDP
5. Click on the Disable/Enable option
6. A message will be displayed.

**Expected Result**
The message that gets prompted needed to be available for some time for the user to see and understand it

**Actual Result**
Prompting message get disappear within a short time

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
