### ISSUE TITLE
Change the name of isCorporateIP() function in IP-Based template

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#5377]
Change the name of isCorporateIP() function in IP-Based template to isIpInSubnets() and add it as a generic function that can be used in other places.

Refer doc page https://docs.wso2.com/display/IS580/Configuring+IP-Based+Adaptive+Authentication

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
