### ISSUE TITLE
No Cancel button in STS Configuration page

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5378]
Moved from: [https://wso2.org/jira/browse/IDENTITY-7116](https://wso2.org/jira/browse/IDENTITY-7116)

There is no $subject.

![Screenshot from 2017-12-11 14-07-17](https://user-images.githubusercontent.com/12288369/58934804-2b67c100-8789-11e9-965b-df0ec50cdb7c.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
