### ISSUE TITLE
Some configurations in SAML config page doesn't have tool-tips

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5379]
Moved from: https://wso2.org/jira/browse/IDENTITY-7110

Some configurations in SAML config page doesn't have tool-tips. Refer to the attached image.

![Screenshot from 2017-12-11 13-33-40](https://user-images.githubusercontent.com/12288369/58935043-daa49800-8789-11e9-8fdf-0b8b5d239819.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
