### ISSUE TITLE
Error generated when creating a service provider without a name can be improved

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5382]
Moved from: https://wso2.org/jira/browse/IDENTITY-7097

When doing the subject IS gives the attached error. This should be improved as "Please provide Service Provider Name" not ID.

Related to wso2/product-is#5381

![Screenshot from 2017-12-11 09-54-04](https://user-images.githubusercontent.com/12288369/58935457-20ae2b80-878b-11e9-8319-daa13255c95d.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
