### ISSUE TITLE
Improve the error produced when creating a SP name with special characters

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5383]
Moved from: [https://wso2.org/jira/browse/IDENTITY-7096](https://wso2.org/jira/browse/IDENTITY-7096)

When doing the $subject it gives the attached error. We can improve this by specifying what are the characters allowed in the name.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
