### ISSUE TITLE
[OAuth/OIDC] When a incorrect URI is entered for the callback URI the application creation page exits

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5384]
Moved from: https://wso2.org/jira/browse/IDENTITY-7146

Add a correct URI for the callback URI with space at the end and click ok. Application creation page exits with an error message.

See the attached screenshot.

![Screenshot from 2017-12-12 13-30-54](https://user-images.githubusercontent.com/12288369/58936156-bac2a380-878c-11e9-9dd9-330a60e5a67b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
