### ISSUE TITLE
Can add invalid values for "Application Access Token Expiry Time"

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5386]
Moved from: [https://wso2.org/jira/browse/IDENTITY-7143](https://wso2.org/jira/browse/IDENTITY-7143)

We can add invalid times for "Application Access Token Expiry Time", both other fields are validated properly.

![Screenshot from 2017-12-12 13-15-44](https://user-images.githubusercontent.com/12288369/58936736-193c5180-878e-11e9-967c-351851bcd68b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
