### ISSUE TITLE
Make thrift Authenticator an optional extension and remove from default pack

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#5387]
IS packs "org.wso2.carbon.identity.authenticator.thrift"
This is originally used when ESB want to call IS to evaluate XACML policy.
This does not have primary use case in IAM, and can be moved as a connector, where one can install when the integration is needed.

Proposed,
Create new repo in extensions,
Create extension
Publish in connector store

Related:
https://github.com/wso2/product-is/issues/4819

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
