### ISSUE TITLE
Allowing forwardslash (/) in user/role names in WSO2 products

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5388]
**Description**
Currently, the forward slash is considered as a special character in WSO2 products as it is used for user store domain separator. Therefore it is not possible to use usernames *& roles with "/"

**Type**
Improvement

**Priority**
Highest

**Affected version**
5.0.0-GA, 5.8.0

**Component/s**
user-core

**Estimated Complexity**
Moderate

**Label/s**
Affected/5.0.0, Affected/5.8.0, Component/User Mgt, Severity/Major, Priority/Highest, Type/Improvement, Complexity/Medium

**Similar issue**
https://github.com/wso2/product-is/issues/4883

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
