### ISSUE TITLE
Request mandatory claims by claim description rather than claim URI

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5389]
Moved from https://wso2.org/jira/browse/IDENTITY-5569 

Requesting mandatory claims by URI is not end-user friendly. Use claim description instead.

![image](https://user-images.githubusercontent.com/11737221/58945798-295e2c00-87a2-11e9-9106-92a4b3c2dbb6.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
