### ISSUE TITLE
Last Modified Time is not updated properly, getting the created time as a last updated time in SCIM2

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5390]
Steps to reproduce:

1. Create a group via SCIM2
2. List the groups via SCIM2, note down the last modified time.
3. Try to update the group. Ex: Add a new member to the group via a patch or UI.
4. List the groups again, last modified time is the same as created time. 

Reproduced in 5.6.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
