### ISSUE TITLE
Cannot log in to analytics dashboard portal with created credentials	

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#5392]
Cannot log into analytics dashboard with the created user credentials.
Steps to reproduce:
1. Download the IS Analytics pack and run it.
2. Download the IS pack and run it.
3. Log into Management Console using Admin/Admin
4. Create a user (ex: testuserfoo)
5. Assign a role to that user with login permissions
6. Go to https://localhost:9444/portal and try to log in using 'testuserfoo'
The 'testuserfoo' will not be able to log in to the analytics dashboard. There will be a message saying username or password you entered is not correct.
Is it because these two products (IS and IS Analytics) maintain two different user stores and the two do not sync with default implementation. Any user (potential customer or evaluating user) should be able to log into dashboard without doing any data store configurations explicitly.

Same as https://wso2.org/jira/browse/IDENTITY-6841
Moved from: https://wso2.org/jira/browse/ANLYIS-196

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
