### ISSUE TITLE
[Dashboard] Improve usability of dashboard by handling browser back button actions

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5393]
Moved from https://wso2.org/jira/browse/IDENTITY-5794

The user gets an authentication error while traversing through IS dashboard using the browser back button.

Steps to reproduce:
1. Login to IS dashboard
2. Go inside a gadget (ex: user profile)
3. Click browser back button
4. Login again via login form; submit
5. Gets an authentication error. But active session can be reconnected to the browser by manually entering /dashboard to the URL

Reason:
The previous page for the dashboard landing page is login form. So cannot log in as we have an active session already in IS

Improvement:
As this is a SPA application, better if we have some disclaimer message (page) before we land to the dashboard. So the immediate click for back button is this disclaimer page, not the login page.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
