### ISSUE TITLE
Incorrect response status codes from selfsignup rest API

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5395]
**Description**
* API: [https://localhost:9443/api/identity/user/v0.9/me](https://localhost:9443/api/identity/user/v0.9/me)
* Send non-existing domain name as the realm
example
```
{
  "user": {
      
        "username": "aysh3",
        "tenant-domain": "carbon.super",
        "realm": "non-existing-domain",
        "password":"test123",
        "claims":[{
        	"uri":"http://wso2.org/claims/emailaddress",
        	"value":"ayesha@wso2.com"
        }]		 
}
```
* Response status code 500-Server error with message
```
{
  "code": "20019",
  "message": "Internal server error",
  "description": "The server encountered an internal error. Please contact administrator."
}
```
* But should be a meaningful error message to the client.

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.8.0

**Component/s**
user-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
