### ISSUE TITLE
[Doc] Web application is calling the /commonauth url to logout

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5397]
**Description**
Need documentation for calling the /commonauth url to logout in web application.

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.2.0-Beta, 5.8.0

**Component/s**
openid

**Severity**
Major

**Estimated Complexity**
Moderate

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
