### ISSUE TITLE
Inconsistency in SCIM2 response when filtering users that have roles created while SCIM2 is disabled

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#5398]
**IS Version: 5.6.0**

There is an inconsistency in the SCIM2 response received when filtering users that have roles created while SCIM2 is disabled. Ideally, it should not list the roles that were created while SCIM2 is disabled. But here it lists such roles without the SCIM id value as it is not generated when the role is created. 

**Steps to Reproduce**

1. With SCIM2 Enabled in the User Store.
      - Create a user (sam)
      - Create a role (scim_role)
2. With SCIM2 Disabled in the User Store.
      - Create another role (non_scim_role)
3. Then assign the created roles to the user (sam).
4. Execute the following CURL command.

`curl -k --user admin:admin "https://localhost:9443/scim2/Users?filter=userName+eq+PRIMARY/sam&attributes=groups,roles"`

**Response:**
`{
	"totalResults": 1,
	"startIndex": 1,
	"itemsPerPage": 1,
	"schemas": ["urn:ietf:params:scim:api:messages:2.0:ListResponse"],
	"Resources": [{
		"roles": [{
			"type": "default",
			"value": "scim_role,non_scim_role,Internal/everyone"
		}],
		"groups": [{
			"display": "scim_role",
			"value": "451c700f-82e8-467a-a52b-75b186068623"
		}, {
			"display": "non_scim_role"
		}],
		"id": "c07adf2b-6d5b-456e-89c7-c916a6c4815f"
	}]
}
`

This behaviour can be seen for both user roles and SP roles.

**Comment by hauntingEcho** [comment]
I strongly disagree that the groups in which a user is a member should be excluded from the response, regardless of whether SCIM2 was enabled when the group was created.  Rather, groups with missing IDs should be assigned an ID.

See also #5290

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
