### ISSUE TITLE
Non-editable fields should be grey

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5400]
Moved from https://wso2.org/jira/browse/IDENTITY-5956

Non-editable fields should be Grey (During tenancy modification). But anyway they are not changeable. need to improve this.

![image](https://user-images.githubusercontent.com/11737221/58955497-ce383380-87b9-11e9-9b6d-5b65eca406ab.png)
The domain name and Admin username fields are not allowed to be edited. So better to show them in grey

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
