### ISSUE TITLE
Changing the password from dashboard does not give any success message on success

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5401]
Steps to recreate the issue
1. Log in to dashboard using (https://localhost:9443/dashboard/index.jag)
2. Go to 'Change Password' option to change the current password of the logged in user
3. Change the password and click 'Update' button

Observations
Does not get any success message on the successful update of user's password. the window will get closed without any notification.

**Comment by senthalan** [comment]
Original issue https://wso2.org/jira/browse/IDENTITY-6731

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
