### ISSUE TITLE
Claim dialect extending for different IDP

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5402]
**Description**
Since we may have different cliams for different IDPs even though those are based on same protocol, we are going to give a feature to extend claim dialect and add the additional claims there.

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.1.0-GA, 5.8.0

**Component/s**
claim-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Labels**
Affected/5.1.0, Affected/5.8.0, Component/Claim Management, Severity/Major, Priority/Normal, Type/Improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
