### ISSUE TITLE
Add a configuration restriction to the Service Provider to accept a selected algorithm to SAML request signing

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5403]
**Description**
Currently we can select the response signing algorithm for a specific SP.
The customer needs to restrict the SAML request signing algorithm from the SP.
The configurations should look like same as the response signing that currently we use in the SP configurations.

**Type**
New Feature

**Priority**
High

**Affected version**
5.5.0-GA, 5.8.0

**Component/s**
saml2-sso

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Affected/5.5.0, Affected/5.8.0, Component/SAML, Severity/Major, Priority/High, Type/New Feature

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
