### ISSUE TITLE
Incorrect message in Mandatory Claim Request page

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5404]
Moved from https://wso2.org/jira/browse/IDENTITY-5578

The message instructs to manually fill the claim value in the user profile. But it automatically gets filled when the user enters the value in this page.

![image](https://user-images.githubusercontent.com/11737221/58957518-646e5880-87be-11e9-9050-275a20711db2.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
