### ISSUE TITLE
IDENTITY-6438 - 'JIT Outbound' check box has changed as 'Enable JIT' when updating

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5405]
Steps to reproduce:

1. Configure a IDP
2. Configure a SP and click on 'Outbound Provisioning Configuration'
3. Click on the '+' mark in-front of the IDP name
4. There there will be a check box as 'JIT Outbound'
5. Save the SP with the configurations
6. Edit the SP and expand 'Outbound Provisioning Configuration'.
7. The check box named as 'JIT Outbound' has changed to 'Enable JIT '

**Labels**
Type: Bug
Priority: Normal
Component/s: service-provider
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6438_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
