### ISSUE TITLE
IDENTITY-6429 OAuth2 endpoint define per tenant and validate for tenant in each implementation.

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5408]
As an example, now we can validate the token that is given for tenant A application by the tenant B introspection service. 
Since we have tenant specific URL for each oauth endpoint, we can validate that from each implementation and reject if it is across the tenants.

**Labels**
Type: Improvement
Priority: High
Component/s: oauth
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6429_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
