### ISSUE TITLE
IDENTITY-6413 Issue in Account Association when users are in two different tenant domains

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5410]
1. Create two users (say User1 in T1 and User2 in T2) in two different tenants.
2. Create a SP in a third tenant and enable SaaS
3. Configure an external IDP for the SP
4. Associate the two local users which is created from step 1
5. Associate User1 with IDP and associate User2 with IDP
6. Make the SP to receive local claims
7. It picks the user who resides in the top of the db table and display

Expected Behavior:
1. Allow first user to associate a local User to IDP
2. When associating the second local user to the IDP it should ask to remove the first association if the user needs to proceed
As a summary there can not be two associations for two local users with the Same IDP for the same SP.

(When the users are in the same tenant domain then we can not associate both the users with IDP which is as expected as it throws a Primary key violation) from db level

**Comments**
_comment-1_

> Associate User1 with IDP and associate User2 with IDP

In this case are the usernames of User1 and User2 same?
or the associate the username at IDP (let's say ASSOCIATED_USER_NAME) equal for both User1 and User2 at IDP?

> 6. Make the SP to receive local claims
> 7. It picks the user who resides in the top of the db table and display

Have we enabled "Assert identity using mapped local subject identifier" configuration in SP?

_Comment-2_

> In this case are the usernames of User1 and User2 same?
> or the associate the username at IDP (let's say ASSOCIATED_USER_NAME) equal for both User1 and User2 at IDP?

No the users have two different user names.

> Have we enabled "Assert identity using mapped local subject identifier" configuration in SP?

Yes.

**Labels**
Type: Bug
Priority: Normal
Component/s: authentication-framework, user-mgt
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6413_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
