### ISSUE TITLE
IDENTITY-6468 UI Improvements in Challenge Questions and Email Templates

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5411]
Challenge Questions

Set / Question - remove space between the slash
Help text for Set Id, Id
Id => ID
After adding a question it redirects to question list but the breadcrumb shows as
Home > Challenge Question Management. 
Need to change it to 
Home > Manage > Challenge Questions > List
Challenge questions table change “Question_ID” to “Question ID”
Remove Add in “Add Challenge Question” label
In add challenge questions remove the table with table headers when there is no data in the table
Email Templates

"Add a New Email Template” to “Add New Email Template”
Missing “Email Template Type” and “Add a New Email Template” page breadcrumbs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
