### ISSUE TITLE
IDENTITY-6457 Remove the outdated feature "usage plan for the tenant"

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5412]
Since "Usage plan for the tenant" functionality is outdated, we could remove it from our product. It will help to avoid the confusion.
![image](https://user-images.githubusercontent.com/29881881/58961461-caf77480-87c6-11e9-9302-fb6dcd91ae98.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
