### ISSUE TITLE
IDENTITY-6511 - UI Improvements in 'Workflows' screens

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5413]
**Screen - Workflow Engagements>Add**

1. Leave **Operation Category** field empty and click Add. 
The error message is "Operation Category must be select". 
Change error message to "Operation Category must be selected."

2. Same issue for the *Operation name *field

3. Select **Apply if** or **Advanced** and leave 'Condition' field blank.
Page gets redirected to a page that says "Error when creating the association"
It would be more meaningful to have a **popup** error message that says to 'fill the required field'.

4. The **condition** field can have a help text so that the user knows what format the condition should be entered in. The condition field should have a required field validator with the red star.

5. Select Apply if and click Add without selecting anything from the dropdown.
Nothing happens. An error message should appear prompting the user to select.

6. Select **create new workflow** on the **Select workflow** dropdown.
The page is redirected to Add Workflow screen but there is no breadcrumb on top.

**Screen - Workflow Definitions> Add**

1. Enter workflow name, click Next and then click Add Approval Step.
Select Search Users. 
Change "Enter user name pattern" to "Enter username pattern".

2. On the table under Search Users, change the 'UserName' column to 'Username'.

**Screen - Workflow Engagements>List**

1. Click Disable for a particular workflow association.
Confirmation message is currently "Are you sure you want to disable this association". 
This message should have a question mark at the end of it.

2. Same issue when Enabling a workflow association.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
