### ISSUE TITLE
IDENTITY-6487- UI Improvement related to Main/Identity Provider area

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5414]
Section - Add New Identity Provider

1. Help text for the description. Instead of saying "A meaningful description about the identity provider" say something like "Provide a meaningful description about the identity provider
2. Description for the Alias ("If the resident identity provider is known by an alias at the federated identity provider specify it") there should be a comma after the word "provider"

Section - Claim Configuration ->Advanced Claim Configuration
1. When you click the plus sign to add the claim without selecting a claim, it gives the error "Add Valid Attribute". A more meaningful error message is better. Ex: Select a valid claim URI
2. Select a claim URI for provisioning and click Add (+ sign). The "Delete" is not accompanied by a "Bin" image.

Section - Role Configuration
1. Identity Provider OutBound Provisioning Roles: The term "OutBound" should be "Outbound"
2. The description "Enter the identity provider's comma separated provisioning roles name" . Is should be "role names"

Section - Federated Authenticators: SAML 2 Web SSO Configuration
1. If selecting Enable SAML2 Web SSO makes the default one clicked, it should not look selectable. Can we make it with lighter font?
2. Select Mode description question mark should a space backward.
3. Descriptions Enable SAML2 Web SSO and Enable Assertion Signing, better make the term consistent "specify vs specifies"
4. Description "Specifies if logout/single Logout is enabled for this identity provider", "Logout" should be "logout" (Lower case "L")
5. "Url" should be "URL" everywhere
6. The question marks in front of the descriptions should be aligned correctly.

Area - WS-Federation C
1. "STS" should be uppercase in the description

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
