### ISSUE TITLE
IDENTITY-6399 [IDP Configs] [Connectors & Authenticators] Doesn't allow saving empty values for mandatory fields when they are disabled

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5417]
In the IDP configuration

1. configure an authenticator or a connector
2. Save the configs
3. Disable the authenticator or connector
4. remove all fileds
5. Press Update button
6. Give an error saying that mandatory fields are missing.

Then to save it user need to fill the mandatory fields.
Instead, if the Connector or the Authenticator is disabled it should not give an error saying that the mandatory fields are missing.

**Labels**
Type: Bug
Priority: Normal
Component/s: identity-provider
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6399_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
