### ISSUE TITLE
IDENTITY-6396 Errors while updating mandatory attributes in IS side, should not stop application authentication

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5418]
When requested claim is marked as mandatory, and not currently present in user profile details, IS will ask user to provide these values during authentication.

For local users, other than sending to value to SP, IS will save these claim values in user profile as well. If some error occurs while updating the user profile. Authentication will fail. Also, no error is printed in the carbon logs. This is wrong, ideally user should be able to proceed with authentication with provided claim values.

**Labels**
Type: Bug
Priority: Normal
Component/s: authentication-framework, service-provider
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6396_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
