### ISSUE TITLE
Outdated reference links in carbon console sign-in page

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5419]
The following has outdated references in the carbon console sign-in page.

- Docs
- About
- User Guide
- Sign-in Help

If changing these links cannot be automated let's add this in here[1] to keep track.
https://github.com/wso2/product-is/blob/master/release-guidelines.md

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
