### ISSUE TITLE
IDENTITY-6049 Instead of using a regex when configuring multiple callback Urls in Inbound OAuth Configuration UI, use an Add button

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5420]
Give a similar implementation like configuring "Assertion Consumer URLs" in SAML2 Web SSO Configuration under Inbound Authentication Configuration.

**Labels**
Type: Improvement
Priority: Normal
Component/s: oauth, service-provider
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6049_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
