### ISSUE TITLE
IDENTITY-6097 Some datatypes are not properly built in to the XACML request.

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5422]
Please check following code [1] in XACMLRequetBuilder class of the entitlement proxy. This code does not work for all the data types in here [2] Basically followings

```
urn:oasis:names:tc:xacml:1.0:data-type:x500Name.
urn:oasis:names:tc:xacml:1.0:data-type:rfc822Name
urn:oasis:names:tc:xacml:2.0:data-type:ipAddress
urn:oasis:names:tc:xacml:2.0:data-type:dnsName
urn:oasis:names:tc:xacml:3.0:data-type:xpathExpression
```

[1] https://github.com/wso2-attic/carbon-identity/blob/master/components/agents/org.wso2.carbon.identity.entitlement.proxy/src/main/org/wso2/carbon/identity/entitlement/proxy/XACMLRequetBuilder.java#L67
[2] http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html#_Toc325047261

**Comments**
_comment-1_

We have to have some data type and prefix mapping instead of hard coding XMLSCHEMA
attributeValueXML.addAttribute("DataType", XMLSCHEMA + attribute.getType(), null);

_comment-2_

The issue seems to still exist.
https://github.com/wso2-extensions/identity-agent-entitlement-proxy/blob/master/components/org.wso2.carbon.identity.entitlement.proxy/src/main/org/wso2/carbon/identity/entitlement/proxy/XACMLRequetBuilder.java#L73

**Labels**
Type: Bug
Priority: Normal
Component/s: xacml
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6097_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
