### ISSUE TITLE
IDENTITY-5995 [LDAPConnector] Decouple username attribute with user entry RDN

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5423]
Currently RDN coupled with username attribute;

means
- user entry created with the username attribute as its RDN and also
- we try to authenticate with the same attribute.

This lead us to impossible to rename usernames.

**Labels**
Type: Improvement
Priority: High
Component/s: user-core, user-store, user-store-ldap
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-5995_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
