### ISSUE TITLE
IDENTITY-7175 Reading attributes from an attribute store does not work for tenants

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5424]
Moved from: https://wso2.org/jira/browse/IDENTITY-7175

Steps
1. Follow the scenario number 27 of the blog below - Authenticate the users against one user store but fetch user attributes from multiple other sources
https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
2. Follow the blog (1) and copy the jar/custom extension specified in the blog to <WSO2IS_HOME>/repository/components/dropins directory.
3. Set up travelocity.com as a SP using SAML and set requested claims. Enable SAAS

givenname
lastname
email
telephone
4. Follow the blog (1) and set up a JDBC user store as the primary user store(credential store) and another JDBC user store as an attribute store (secondary). Follow the naming conventions in the blog
5. Create a tenant 
6. Create the same tenant in the seconday user store and configure the user profile of the tenant admin
7. Login to the travelocity app using the tenant admin

Issue
The attributes of the user configured in step 6 should appear in the travelocity app. But, it does not show the attributes.

Note: This works for the super ten
(1) http://xacmlinfo.org/2015/03/03/configure-attribute-sources-with-wso2-identity-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
