### ISSUE TITLE
IDENTITY-7177 [XACML][EntitlementAdminService] Inappropriate response code when resource already eixst

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5425]
Moved from: https://wso2.org/jira/browse/IDENTITY-7177

Steps To Recreate:

Add a policy from admin service, which is already existing(policy id is same as existing one)
https://localhost:9443/services/EntitlementPolicyAdminService.EntitlementPolicyAdminServiceHttpsSoap11Endpoint/ >> addPolicy
**Actual Result:**
The client(jmeter) getting the response as a failure since it is receiving the response code as 500 (internal server error)
But response message clearly says Policy Id is already exist
**Expected Result:**
So this is not correct. Response code should be 409(conflict) ideally. Since client side validation would implement according to the response code then this will not give the correct intention of the error

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
