### ISSUE TITLE
IDENTITY-7171 No method to get the number of secondary user stores configured in IAM

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5426]
Moved from https://wso2.org/jira/browse/IDENTITY-7171

Scenario
I am in the process of implementing the scenario number 27- "Authenticate the users against one user store but fetch user attributes from multiple other sources" [1]. Here I need to get the number of secondary user stores in the system and iterate through the attribute stores to find the user's attributes.

I am following the blog in [2] which explains how to do it extending the AbstractUserOperationEventListener class. But, for my scenario I need to connect multiple attribute stores to one credential store, therefore, need to find the number of attribute stores in the system.

Issue
There is no method to get the number of secondary user stores configured in IAM

[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
[2] http://xacmlinfo.org/2015/03/03/configure-attribute-sources-with-wso2-identity-server/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
