### ISSUE TITLE
IDENTITY-7152 Home Realm identifier should be unique to an Identity Provider

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5427]
Moved from https://wso2.org/jira/browse/IDENTITY-7152

Steps to recreate the issue
1. Create Facebook and Google as IDP by providing a same value for the Home Realm identifier
ex: HRI = facebook
2. Create Travelocity as SP and add the facebook and google as outbound authenticator
3. Configure the fidp value in the travelocity application.
QueryParams=fidp=facebook
4. Access travelocity application with SAML

Observations
Redirection will happen based on the last modified IDP
For example: If you first create Facebook as IDP by providing "facebook" identifier and then create Google IDP by providing "facebook" identifiers, authentication will rediecte via Google as it is the last updated IDP matching the given fidp

Expected Results
Should not allow creating identifiers with the same name, it should be unique.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
