### ISSUE TITLE
IDENTITY-7142 IDP redirection failed when the Home Realm identifier contains Spanish characters

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5428]
Moved from https://wso2.org/jira/browse/IDENTITY-7142
Steps to recreate the issue
1. Create Facebook as IDP by adding a value that contains Spanish characters as the Home Realm identifier
ex: "Janucá"
 
2. Create Travelocity as SP and add the facebook as outbound authenticator
3. Configure the fidp value in the travelocity application.
QueryParams=fidp=Janucá
4. Access Travelocity application with SAML

Observations
Home Realm identifier not identified by the IS hence not redirected to the IDP for authentication

Expected Results
Should redirect to authenticate via configured IDP
Spanish character should support for the Home Realm as some of the users might use it

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
