### ISSUE TITLE
IDENTITY-7141 Allowing spaces for Home Realm identifier resulted in a failure for IDP redirection

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5429]
Moved from https://wso2.org/jira/browse/IDENTITY-7141

Steps to recreate the issue
1. Create Facebook as IDP by adding a value that contains a space as the Home Realm identifier
ex: "test 123"
 
2. Create Travelocity as SP and add the facebook as outbound authenticator
3. Configure the fidp value in the travelocity application.
QueryParams=fidp=test 123
4. Access travelocity application with SAML

Observations
Allowed to provide a value to Home Realm Identifier with spaces in it
Authentication redirection failed without any error message

Expected Results
1. If Home Realm Identifier should not contain spaces it should be applied as a validation when creating or editing the IDP
2. If not (Home Realm can contain spaces) travelocity login should direct to Facebook authentication

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
