### ISSUE TITLE
IDENTITY-7128 Back end throws a WARN {org.owasp.csrfguard.log.JavaLogger} - potential cross-site request forgery (CSRF) attack when the session is expired

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5430]
Moved from https://wso2.org/jira/browse/IDENTITY-7128

Steps to recreate the issue
1. Run the pack IS 5.4.0
2. Configure Facebook as a IDP 
3. Go to Identity providers > List 
4. Let some time for the session to get expired
5. Click on Enable/Disable option infront of the IDP name
6. Will get a Warn meessage in the backend as follows

[2017-12-11 17:18:52,815] WARN

{org.owasp.csrfguard.log.JavaLogger}
- potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/carbon/idpmgt/idp-mgt-edit-finish-ajaxprocessor.jsp, error:request token does not match session token)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
