### ISSUE TITLE
IDENTITY-7174 Insufficient information when creating a SP in audit logs

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5431]
Moved from https://wso2.org/jira/browse/IDENTITY-7174

When creating an SP the action is given as update, but it doesn't mention that you are adding a SP. This should be mentioned in the Audit logs.

`[2017-12-13 14:09:50,642]  INFO {AUDIT_LOG}-  Initiator : admin | Action : update | Target : 12 | Data : { addSp } | Result : Success  `

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
