### ISSUE TITLE
[doc] broken link in 5.6.0 "Managing Permissions with APIs"

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#5432]
on [the 5.6.0 documentation for Managing Permissions with APIs](https://docs.wso2.com/display/IS560/Managing+Permissions+with+APIs#ManagingPermissionswithAPIs-isRoleAuthorized), the first link in the document ("RemoteAuthorizationManager API") points to "https://localhost:9443/services/RemoteAuthorizationManagerService?wsdl", which only exists if the reader is currently running an instance of WSO2IS on their computer.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
