### ISSUE TITLE
Improving the claim mapping in IDP and SP configurations

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#5437]
Currently we have only support the standard OIDC dialect for the OIDC IDPs and SPs. So we have to do the following improvements in the product,

- Provide the flexibility to select a claim dialect per IDP and SP regardless of the protocols (OIDC, SAML etc).
- Provide the flexibility to add a custom claim mapping per IDP and SP for OIDC protocols as well.

**Comment by janakamarasena** [comment]
The above PRs makes improvements based on this issue. They introduce a global configuration to allow federated authenticators to use the idp local claim dialect instead of the authenticator's claim dialect when using a custom dialect claim mapping.

**Comment by mefarazath** [comment]
@janakamarasena Why is this issue still open? are there any pending improvements?

**Comment by mefarazath** [comment]
Also, why can't we have our default behaviour to allow custom claim mappings if they are defined at the IDP level?

**Comment by janakamarasena** [comment]
@mefarazath we have only done the improvement related to IDP claim mapping ATM. +1 to change the default behaviour.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
