### ISSUE TITLE
IDENTITY-6888 In the OAuth/OIDC idp configuration not showing error messages for error scenarios

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5439]
Moved from https://wso2.org/jira/browse/IDENTITY-6888

The actual issue is not showing an error when the required fields are not filled. If we fill the values for "Additional Query Parameters" only then we should get an error since there are required fields.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
