### ISSUE TITLE
IS 5.1.0 Dashboard Gadgets not working in restricted environments

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5440]
Moved from - https://wso2.org/jira/browse/IDENTITY-4348

IS 5.1.0 Dashboard Gadgets not working in restricted environments.

1. Amazon EC2
2. No internet connectivity
3. HostName and MgtHostName in carbon.xml (which is the external AWS ELB hostname) is not reachable from the node. We tried mapping that hostname to the internal Nginx Cluster listening on 443 which worked for IS 5.0.0 (with slight delay after server restart), but not on IS 5.1.0. Observed following exceptions on browser developer console.

TID: [-1234] [] [2016-02-05 18:34:36,952] INFO

{org.apache.shindig.gadgets.render.Renderer} - The gadget at https://identity-develop.ngiris.io/portal/gadgets/connected_accounts/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].
TID: [-1234] [] [2016-02-05 18:34:36,966] INFO {org.apache.shindig.gadgets.render.Renderer}
- The gadget at https://identity-develop.ngiris.io/portal/gadgets/user_profile/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].
TID: [-1234] [] [2016-02-05 18:34:36,972] INFO

{org.apache.shindig.gadgets.render.Renderer} - The gadget at https://identity-develop.ngiris.io/portal/gadgets/account-recovery/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].
TID: [-1234] [] [2016-02-05 18:34:36,978] INFO {org.apache.shindig.gadgets.render.Renderer}
- The gadget at https://identity-develop.ngiris.io/portal/gadgets/user_auth_apps/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].
TID: [-1234] [] [2016-02-05 18:34:36,981] INFO

{org.apache.shindig.gadgets.render.Renderer} - The gadget at https://identity-develop.ngiris.io/portal/gadgets/pwd_change/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].
TID: [-1234] [] [2016-02-05 18:34:36,983] INFO {org.apache.shindig.gadgets.render.Renderer}
- The gadget at https://identity-develop.ngiris.io/portal/gadgets/approvals/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].
TID: [-1234] [] [2016-02-05 18:34:36,990] INFO

{org.apache.shindig.gadgets.render.Renderer}
- The gadget at https://identity-develop.ngiris.io/portal/gadgets/connected_accounts/gadget.xml did not render. The following error occurred: Unsupported feature: [pubsub-2].

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
