### ISSUE TITLE
User Impersonation feature in WSO2 Identity Server

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5443]
Moved from https://wso2.org/jira/browse/IDENTITY-4379

User Impersonation feature for wso2 IS is not available currently. This feature will enable an user to acquire another user's roles/permissions at run time.

For an example normal user can execute super user commands by executing with 'sudo' in Linux.

**Comment by IsuraD** [comment]
When design a solution on this, have a look on [1], since that spec also address the requirement of obtaining tokens employing impersonation.

[1] https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-03

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
