### ISSUE TITLE
Log the IP address in audit.log

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5444]
Created from https://wso2.org/jira/browse/IDENTITY-4389

Currently, IS 5.1.0 does not support ip-address in audit.log.
Needs to log the IP address in <IS_HOME>/repository/logs/audit.log.

**Comment by IsuraD** [comment]
Logging support for user id and the authenticator should also be added.

**Comment by GANGANI** [comment]
In IS-5.10.0, IP address can be enabled in audit logs by adding the following config in _<IS_HOME>/repository/conf/deployment.toml_ file.

```
[audit.log.contextual_param]
params = ["remote_address"]
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
