### ISSUE TITLE
UI error message should be displayed when deleting an IDP which is used from a SP

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5445]
steps to reproduce :

a. Create a SP
b. Create an IDP
c. Assign IDP to SP
d. Delete IDP

Outcome :It popup an error message in the UI and suddenly it disappears.

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6986

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
