### ISSUE TITLE
Adding new OAuth service provider should be a atomic transaction.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5446]
Moved from https://wso2.org/jira/browse/IDENTITY-4403

The process of creating Identity Service Providers, should be handled in an atomic way. If not in a situation like network failures there can be a data inconsistency. This will create orphan records and adding new SP will give errors.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
