### ISSUE TITLE
IDENTITY-6874 Common puppet modules Wiki page and IS puppet modules having two different information

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5448]
Moved from https://wso2.org/jira/browse/IDENTITY-6874

When copying JDK packs to the Puppet master in Common wiki page[1] is advised to use JDK 1.8 versions.
When referring to the IS puppuet READMe file[2], it has advised to use JDK 1.7 version.

Please have same information in both pages.

[1] https://github.com/wso2/puppet-base/wiki/Use-WSO2-Puppet-Modules-in-puppet-master-agent-Environment/4882558f9173085d6f6e2af8b554e9d8095eaa2d
[2] https://github.com/wso2/puppet-is

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
