### ISSUE TITLE
Rename "sessionDataKey" parameter

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5449]
**Description**
Many security scanners and researches report "sessionDataKey" getting passed in the URL as a security threat. This is mostly due to the misconception of that parameter pointing to an authenticated session. In contrast, it simply acts as a state maintenance parameter like "RelayState" in SAML and "state" in OAuth - both go in the URL.
To avoid confusion, this parameter should be renamed.

**Type**
Improvement

**Priority**
Normal

**Component/s**
authentication-framework

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Auth Framework, Severity/Major, Complexity/Medium

Moved from [https://wso2.org/jira/browse/IDENTITY-5202](https://wso2.org/jira/browse/IDENTITY-5202)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
