### ISSUE TITLE
Stop sending two email when Admin forced password reset is triggered

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5450]
**Description**
When admin force a password reset, two emails are sent to the user,

1. one containing a password reset link
2. another one containing account lock notification. (This get triggered only once when an account goes from unlocked to locked state)

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.8.0

**Component/s**
identity-governance

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Affected/5.8.0, Component/Identity Governance, Severity/Major

Moved from https://wso2.org/jira/browse/IDENTITY-5193

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
