### ISSUE TITLE
Tool to import/export tenant data

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5452]
**Description**
Need to build a tool (optionally a feature in the UI) to import/export tenant configurations selectively as much as possible.
It should be able to support all current and future identity feature we will provide.
This will be mainly used for environment migration, backup (mostly in dev and QA), etc.

**Type**
New Feature

**Priority**
Normal

**Component/s**
all-identity

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/New Feature, Component/Tenant Mgt, Component/Identity Mgt, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5152

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
