### ISSUE TITLE
Google federated idp allowed authentication with another gmail account

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5453]
**Description**
Observed Google federation allowed with another google account and claim information of new user account was retrieved successfully

**Steps**
1. Generated 'OAuth client ID' credentials from a test gmail account (testkavikavi@gmail.com)
2. Registered an IDP in IS server and do google federated authenticator configuration (Using above credentials)
3. Register a SP for web app (used Travelocity) and select Google as a federated authenticator
4. Access Travelocity: 
 -- authentication was successful
5. Go to a private browser and log into any other Google account (kavitha@wso2.com)
6. Access Travelocity from the same browser window:
 -- Without authentication page, it directs to access page(attached google1.jpeg)
7. Click Allow
-- returned requested claims(see attached google2.jpeg)

In the last two steps, seems it has authenticated with existing logged in account and the end user can see all information of different gmail user account.

![image](https://user-images.githubusercontent.com/12439288/59029314-972a5680-887b-11e9-8607-5dcd9d3cf4ec.png)
google1.jpeg

![image](https://user-images.githubusercontent.com/12439288/59029349-b45f2500-887b-11e9-808e-9b853e2d9c17.png)
google2.jpeg

**Type**
Bug

**Priority**
Normal

**Affected version**
5.2.0 RC1, 5.8.0

**Component/s**
application-authenticators

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/Identity Mgt, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5132

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
