### ISSUE TITLE
Internal Roles need to be tested and fixed for SCIM

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5454]
**Description**
E.g. internal roles created via admin console don't get listed thought SCIM API. Likewise, all the SCIM combinations involving internal roles should be tested

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.8.0

**Component/s**
SCIM

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/SCIM, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5097

**Comment by hauntingEcho** [comment]
possibly related to #5290 & #5398

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
