### ISSUE TITLE
IDENTITY-6881 getTenantIdofUser using RemoteUserStoreManagerService is not working

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5455]
Moved from https://wso2.org/jira/browse/IDENTITY-6881

1)create a user (Eg:-nilasini)
2)Invoke getTenantIdofUser using RemoteUserStoreManagerService as below

```<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getTenantIdofUser>
         <!--Optional:-->
         <ser:username>nilasini</ser:username>
      </ser:getTenantIdofUser>
   </soapenv:Body>
</soapenv:Envelope>```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
