### ISSUE TITLE
Structure of the SOAP message should re-arranged to support multiple claims for a user

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5463]
Refer to: https://wso2.org/jira/browse/IDENTITY-6744

When adding a user with multiple claim mapping using a SOAP admin service [1] the structure of the SOAP message should be organized as follows to get it a success because we need to both ClaimURI and the value.

         <ser:claims>
            <xsd:claimURI>http://wso2.org/claims/organization</xsd:claimURI>
            <xsd:value>EE</xsd:value>
         </ser:claims>

          <ser:claims>
         <xsd:claimURI>http://wso2.org/claims/emailaddress</xsd:claimURI>
            <xsd:value>testc@gmail.com</xsd:value>
         </ser:claims>

However, the correct arrangement of the SOAP message should be as below because we have defined the tags as "ser:claims"

     <ser:claims>
         <ser:claim>
              <xsd:claimURI>http://wso2.org/claims/organization</xsd:claimURI>
              <xsd:value>EE</xsd:value>
         </ser:claim>
        <ser:claim>
            <xsd:claimURI>http://wso2.org/claims/emailaddress</xsd:claimURI>
            <xsd:value>testc@gmail.com</xsd:value>
         </ser:claim>
     <ser:claims>
[1] https://docs.wso2.com/display/IS530/Configuring+Users

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
