### ISSUE TITLE
IDENTITY-6135 No proper error message showing in the UI, when a non exists role is added as a local role in role mapping of IDP

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5465]
No proper error message showing in the UI, when a non exists role is added as a local role in role mapping of IDP

**Labels**
Type: Bug
Priority: Normal
Labels: component_verified
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6135_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
