### ISSUE TITLE
IDENTITY-6196 Solely white-spaced text is allowed in mandatory fileds in Identity Provider Add/Edit Configuration UI

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5466]
In Identity Provider Add/Edit UI, except for Identity Provider Name, other mandatory fileds are allowed to enter and save solely white-spaced text.

**Labels**
Type: Bug
Priority: Normal
Component/s: identity-provider
Labels: component_verified
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6196_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
