### ISSUE TITLE
IDENTITY-6211 scim-schema-extension.config location is inconsistent with other identity configurations

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5467]
scim-schema-extension.config is not under repository/conf/identity. It is still under repository/conf. This is inconsistent with all the other identity related configurations.

**Labels**
Type: Improvement
Priority: Normal
Component/s: scim
Labels: component_verified migration
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6211_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
