### ISSUE TITLE
IDENTITY-6143 Provide IWA Kerberos Authentication using Kerberos Servers of two realms

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5468]
Let me explain the scenario,

There are two Kerberos servers with 2 domains, say USA.COM and LK.COM. For the same IS instance to be able to do IWA with both these servers it should have two DNS entries like idp.usa.com and idp.lk.com in each AD(Kerberos Server) respectively. So basically here IS will be acting as a Kerberos Principal belonging to two realms USA.COM and LK.COM

Therefore we would need to expose IS with multiple hostnames ie. idp.usa.com and idp.lk.com. This is required so that the browser would talk to the correct Kerberos Server when authenticating.

For example, if I want to log in from a machine belonging to USA.COM realm, When I click on the login button of the app, IS will do a 401 challenge. IS needs to do this challenge while exposing itself as idp.usa.com. This will allow the browser to talk to the Kerberos Server of USA.COM automatically.

We can use something like [1] to achieve this. It would be great if we could test the suggested approach and provide an article/doc with the config steps and details.

[1] http://xacmlinfo.org/2015/11/24/service-provider-grouping-with-wso2-identity-server/

**Labels**
Type: Task
Priority: High
Component/s: kerberos
Labels: iwa kerberos
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6143_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
