### ISSUE TITLE
IDENTITY-1287:Add additional key management functionality

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#5469]
Some of the current key management functionality is listed below:

- User can use Carbon to add (upload) a keystore (a single private key must be present in the keystore)
- User can use Carbon to add (upload) certificates to an existing keystore
- User can use Carbon to view private and public key certificates in an existing keystore
- User can use Carbon to delete public key certificates in an existing keystore
- Using this model, users that are uploading new keystores will have access to the private keys which should be avoided in higher security environments.

For that reason, we need to support a few additional use cases:

- User can use Carbon to delete the private key in a keystore
- User can use Carbon to create the private key in a keystore (specifying the x509 fields)
- User can use Carbon to create a new keystore
- Keystores that have been created or modifier are copied to cluster member nodes (this may already be supported?)
- User can use Carbon to create and download a certificate signing request for the private key

moved from: [IDENTITY-1287](https://wso2.org/jira/browse/IDENTITY-1287)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
