### ISSUE TITLE
IDENTITY-6373 XACML policy set editor's policy pagination UI doesn't allow to browse other pages

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5470]
In the XACML Policy Set Editor, we cannot go to next pages in 'Define Policy references' section. Clicking on other pages always ends up in the 1st page.

Workaround: Use the 'Search Policy Option' to overcome this.

**Labels**
Type: Bug
Priority: Low
Component/s: xacml
Labels: component_verified
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6373_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
