### ISSUE TITLE
Provide valid error messages when an exception occured while invoking admin services

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5471]
When invoking the workflow admin services with, I could get the following error message which does not explain where the issue is.

Please improve the service to throw exceptions at the point where the actual issue occurred rather than using general error messages

Following is the admin service request used and the error generated

```<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode>soapenv:Server</faultcode>
         <faultstring>Exception occurred while trying to invoke service method addWorkflow</faultstring>
         <detail/>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>
```

Refer to https://wso2.org/jira/browse/IDENTITY-6779

**Comment by senthalan** [comment]
Refer to : https://wso2.org/jira/browse/IDENTITY-6788

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
