### ISSUE TITLE
Include 'x5t#S256' header param in the JWTs

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5472]
Moved from: https://wso2.org/jira/browse/IDENTITY-6825

Since SHA1 is getting deprecated, it'd better to send 'x5t#S256' header param [1] also in the JWT. We can have both x5t and x5t#S256.

[1] https://tools.ietf.org/html/rfc7515#page-12

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
