### ISSUE TITLE
IDENTITY-6455  Password patterns validation is done even after assigning a role to the user.

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5473]
When enable password patterns feature as in [1], it validates the password at the final stage of user add operation. By that time we have already assigned a role to that user.
I think that is a waste of users time.
The validation error should come when clicking the next button before adding the role.
This is how it happens when add users with default passowrd policy or email username is enabled. We should keep the consistency in this case as well.

[1][https://docs.wso2.com/display/IS580/Password+Patterns](https://docs.wso2.com/display/IS580/Password+Patterns)

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6455

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
