### ISSUE TITLE
Support an expiry time for OAuth/OIDC 'ApproveAlways' consent

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5481]
* During the OAuth/OIDC consent prompt, we have the option of selecting approve always which results in a permanent consent for the particular app.

* Currently we have to invoke updateApproveAlwaysForAppConsentByResourceOwner of OAuthAdminService and change the state of the consent. 

* It is better to consent to be expired automatically after some time. Include a global/application wise configuration to mention the expiration time of a consent Or provide a way for a user to change the expiration of consent in UI.

Refer: https://wso2.org/jira/browse/IDENTITY-5928

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
