### ISSUE TITLE
Should be able to configure where to save individual identity

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#5482]
There are number of identity claims available as follows. If we change Identity.Mgt.User.Data.Store to org.wso2.carbon.identity.mgt.store.UserStoreBasedIdentityDataStore, It'll persist all the identity claims in the underline userstore. There can be situations(especially in LDAP and AD) where users won't able to change existing LDAP structure and still want to map one of an identity claim with the existing LDAP attribute. Ex http://wso2.org/claims/identity/accountLocked

http://wso2.org/claims/identity/verifyEmail
http://wso2.org/claims/identity/askPassword
http://wso2.org/claims/identity/adminForcedPasswordReset
http://wso2.org/claims/identity/lockedReason
http://wso2.org/claims/identity/failedPasswordRecoveryAttempts
http://wso2.org/claims/identity/accountLocked
http://wso2.org/claims/identity/emailVerified
http://wso2.org/claims/identity/phoneVerified
http://wso2.org/claims/identity/accountDisabled
http://wso2.org/claims/identity/failedLoginAttempts
http://wso2.org/claims/identity/failedLoginLockoutCount
http://wso2.org/claims/identity/unlockTime
http://wso2.org/claims/identity/lastLogonTime
http://wso2.org/claims/identity/lastPasswordUpdateTime

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
