### ISSUE TITLE
Identity claim with LDAP attribute

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#5483]
Current Identity claims such as http://wso2.org/claims/identity/accountLocked should be able to work with existing LDAP/AD attributes.

**Comment by SwatiNEC** [comment]
Hi @godwinamila 

Could you please review the above pull request for account locking feature

**Comment by SwatiNEC** [comment]
Hi @godwinamila 

Could you please review the above pull request for account locking feature.

**Comment by godwinamila** [comment]
Hi @SwatiNEC,
Sorry for the late to comment this, Exact problem is w

Thanks
Godwin

**Comment by SwatiNEC** [comment]
Hi @godwinamila, @IsuraD 

As per the documents of [WSO2 IS](https://docs.wso2.com/display/IS570/Account+Locking+by+Failed+Login+Attempts), we need to use IdentityMgtEventListener with orderId=95. But if we use this then we need to add mapping of **failedLockoutCount** field in LDAP as this field is missing in **identityPerson.ldif**. So we also need to add **failedLockoutCount** field.

**Comment by SwatiNEC** [comment]
Hi @godwinamila, @IsuraD

As per the solution provided by me in this PR, the solution is partially merged. But as per the documents of [WSO2 IS](https://docs.wso2.com/display/IS570/Account+Locking+by+Failed+Login+Attempts), we need to use IdentityMgtEventListener with orderId=95. But if we use this then we need to add mapping of failedLockoutCount field in LDAP as this field is missing in identityPerson.ldif. So we also need to add failedLockoutCount field.
Could you please confirm the reason why partial solution was considered for this fix?
