### ISSUE TITLE
Workflow is not triggered when a workflow engagement is added to "Update roles of User" operation and user is added with the roles

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5485]
**Description**
Workflow is not triggered when a workflow engagement is added to "Update roles of User" operation and user is added with the roles

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.3.0-RC2, 5.8.0

**Component/s**
workflows

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Workflow, Affected/5.8.0, Affected/5.3.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5566

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
