### ISSUE TITLE
User management operations can be made more fine grain

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5486]
**Description**
Currently, `"/permission/admin/manage/identity"` permission is needed to make role management UI components visible in the UI.

And UserAdmin service also can be improved to use crud level permissions in `"/permission/admin/manage/identity/rolemgt"` permission for handling each operation separately.

_Example_
`"/permission/admin/manage/identity/rolemgt/create"` permission for addRole() method

**Comments**
1. For the UserAdmin service the issue is there even by assigning the role to the resourceId "/permission/admin/manage/identity/rolemgt", user can't manage roles unless he choses "/permission/admin/manage/identity"
2. Admin UIs should be improved accordingly.

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.3.0, 5.8.0

**Component/s**
user-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/User Mgt, Affected/5.3.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5560

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
