### ISSUE TITLE
Optional user store properties are required for secondary user store due to issues in user store configuration builder

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5487]
**Description**
When you are implementing a custom secondary user store, you can define mandatory & optional properties.

When you implement the user store with only mandatory properties, you can not update the user store from UI Because; it generates null pointer from the following code segment.
```
private RandomPasswordContainer getAndRemoveRandomPasswordContainer(String uniqueID) {
        return RandomPasswordContainerCache.getInstance().getRandomPasswordContainerCache().getAndRemove(uniqueID);
    }
```
As a solution; some optional user store property should be defined in custom user store.

**Type**
Bug

**Priority**
Normal

**Affected version**
5.2.0, 5.8.0

**Component/s**
user-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/User Mgt, Affected/5.8.0, Affected/5.2.0,Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5523

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
