### ISSUE TITLE
Unable to view the user profile with corrupted claims, even though the corrupted claims are not being used

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#5491]
When a claim is corrupted with attribute mapping not having correctly in the DB, the user profile of a user cannot be retrieved via UI.

![Screenshot from 2019-06-07 19-24-07](https://user-images.githubusercontent.com/22551445/59109018-dfb84180-8959-11e9-825a-0febbd3ff13b.png)

But this error happens even with users not having the corrupted claims configured as supported by default.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
