### ISSUE TITLE
After deleting the user role existing user can access resource

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5492]
**Setup**
WSO2 IS 5.0.0 + SP1 ,Secondary user store is read only LDAP.

**Steps to reproduce**
1. Create a sample XACML policy(attached [policy.txt](https://github.com/wso2/product-is/files/3266297/policy.txt) file) for reading access to the dashboard (https://localhost:9443/dashboard).
2. Upload to the IS and publish it.
3. Create the Internal/manager role and add a user test1.
4. Then use Tryit tool to validate the policy. 
     * Now validation is success(permit).
5. Then delete the role Internal/manager using management console.
6. Again validate with tryit tool, 
      * now permit access.

***To reconfirm the issue;***
**Option 1**
Restart the IS and repeat the validation above. Now validation failed(deny - expected behavior).

**Option 2**
1. Again add role Internal/manager and assign the test1 user to it.
2. then validate with tryit tool and validation success.
3. once again delete the role and validate. This time also validation success(permit).

Now clear the attribute cache in **PDP>extention.**
Again validation fail(deny).

**Type**
Bug

**Priority**
Normal

**Affected version**
5.4.0, 5.8.0

**Component/s**
user-core, XACML

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/XACML, Component/Kernel, Affected/5.4.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5180

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
