### ISSUE TITLE
Tenant mode warning when connected to a SSL enabled MySQL 5.7

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5493]
**Description**
Point Registry, User DB and Identity DB to SSL enabled MySQL 5.7 
Import the MySQL server certificates to the client trust store.

The following warning can be seen when browsing registry or connecting the JDBC users ( eg: Listing users) in tenant mode.
This is not reproduced in the super tenant.
Verified by importing the above certificates to the tenant keystore as well.

```
  <url>jdbc:mysql://192.168.48.98:3306/is520akk_is?autoReconnect=true&amp;useSSL=true&amp;requireSSL=true&amp;verifyServerCertificate=true</url>
```

**Type**
Bug

**Priority**
Normal

**Affected version**
5.2.0, 5.8.0

**Component/s**
db-mysql

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/DataSource, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5136

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
