### ISSUE TITLE
Configure the default claim configurations in the IS pack itself

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5494]
Moved from: https://wso2.org/jira/browse/IDENTITY-6870

According to the current implementation of SCIM 1.1/SCIM 2.0 for ask password option, a user/developer needs to manually define the additional claim configurations in the scim-schema-extension.config which we can avoid by having those claim mapping configured in the pack itself. This will reduce the work to the developer and server restarts.

Additionally, we can guide the user about the claim configurations that are configured and why those are necessary, which will help them to troubleshoot issues.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
