### ISSUE TITLE
Add ability control SAML assertion query profile requests types from UI

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5495]
**Description**
SAML Assertion Query\Request Profile consists 5 types of requests
* AssertionIDRequest
* SubjectQuery
* AuthnQuery
* AttributeQuery
* AuthzDecisionQuery

As of now it can only enable\disable assertion query\request profile for the given service provider. So it can enable all these 5 request types as a single unit or disable all 5 request types.

From SAML service provider configuration UI, it can add another field to restrict what are the request types it needed to be allowed for this service provider when assertion query\request profile enabled.

SSO Config Admin service already has a flag (SupportedAssertionQueryRequestTypes) to set this, but it needs to fix UI and request validators to make this flag used in the runtime.

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.5.0, 5.8.0

**Component/s**
saml2-sso

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Type/UX, Component/SAML, Affected/5.5.0,  Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5506

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
