### ISSUE TITLE
When hostname is changed for the server, embeded_bps hostname for tenants remains same

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5496]
**Description**
When hostname is changed in carbon.xml, the hostname of embeded_bps profile changes for the super tenant. But for tenants that already created, it goes with the old hostname.

Probably DB entry can be updated when loading the profile for tenants. Or let the users edit the embedded_bps hostname for tenants at least. For super tenant, this can be done in component activation.

**Notes**
Changing the hostname in the middle of the multi-tenanted deployment is not practical.
It can externally deploy a listener which triggered when a tenant gets loaded, to check on this and update as needed.

**Type**
Bug

**Priority**
Normal

**Affected version**
5.2.0-GA

**Component/s**
workflows

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/Workflow, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5422

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
