### ISSUE TITLE
Improvements for XACML Rest Profile

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5497]
**Description**
* Use the generic authentications filter to secure the webapp
* Remove elements with null values from the JSON response
* Use standard https error codes and include the custom error codes in the error response body
* Remove the ApiOriginFilter since CORS support doesn't need to be explicitly handled
* Fix the getDecisionByAttributes method. For this, a method from balana will be needed to accept attributes and returns ResponseCtx. 
* Downgrade Jackson version to 2.4 to get it working with Swagger
* Remove the Authentication filter and other implementations related to authentication and use the generic
* Try to remove the root level element AllEntitlements and use the EntitledResultSetDTO object without wrapping it in AllEntitlementsRequestModel before converting to an xml object. Same should be done to EntitledAttributesRequestModel.
* Change the name of AbstractEntitlementException since it's too broad. Can change to something like AbstractParserException
* Remove ApplicationInitializer and ClearThreadLocalInterceptor classes once
* Move tests in the main package to test directory
* Rename models package to model and resources package to resource
* Make the Balana MultiRequest class constructor public to handle multi requests
* Use CXF object parser instead of the JSON parser. For this, have an object model which represent a complete XACML request. 
* Move the missing URI constants to balana
* Improve exception handling including runtime exceptions
Run findbugs security plugin

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.3.0, 5.8.0

**Component/s**
xacml

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/XACML, Affected/5.3.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5402

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
