### ISSUE TITLE
Make the Keystore path configurable for Workflow feature in Identity Server

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5498]
**Description**
To support the workflow feature in IS, by default mutual SSL is enabled. If we disable mutual SSL, then the internal communication with the embedded BPS is blocked. The workflow feature should be able to use a separate keystore for mutual SSL communication and also the path should be configurable.

**Type**
Improvment

**Priority**
Normal

**Affected version**
5.2.0, 5.8.0

**Component/s**
workflows

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Workflow, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5281

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
