### ISSUE TITLE
IDENTITY-2063:[Google] Make private key read from wso2carbon.jks instead directly from key

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#5499]
Import the private key to wso2carbon.jks and use that imported key for the Google Identity Provisioning Connector.

Earlier we had restriction on keystore that it can have only one key but now it is resolved

moved from: [IDENTITY-2063](https://wso2.org/jira/browse/IDENTITY-2063)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
