### ISSUE TITLE
Create internal keystore for tenants

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#5500]
Currently, we only have one keystore in tenants and this keystore is used for encrypting some internal critical data for that tenant. Because of this, it is not possible to switch the key in tenants. Thus we need a separate keystore for tenants to encrypt & decrypt internal critical data.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
