### ISSUE TITLE
Inbound Authentication Configuration get automatically filled in Admin Console

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#5502]
Steps to reproduce:

1. Add SP: Give name and register
2. Open Inbound Authentication Configuration section: you can see two right icons on open ID & Ws-Federation
3. Now click Update
4. Service Provider Name automatically assigned to OpenID and WS-Federation tabs.

Original issue: https://wso2.org/jira/browse/IDENTITY-7184

**Comment by emswbandara** [comment]
@nimashanishadi
