### ISSUE TITLE
Allow to pass service provider name as a query parameter to username recovery, password recovery URLs

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#5503]
Currently, we don't use a service provider name query param for username-recovery, password-recovery, and other identity recovery features. This is a key requirement to handle service provider wise email templates.

Original issue: https://wso2.org/jira/browse/IDENTITY-7181

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
