### ISSUE TITLE
User attributes/Username (PII details) must be encrypted

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5504]
JDBC user store of WSO2IS contains PII details of the user. Therefore it is better to secure those. Currently user attribute table (UM_USER_ATTRIBUTE) is not encrypted in WSO2IS by default. Also; username information is available in "UM_USER & UM_USER_ROLE" tables as well. Therefore, we can consider them as well

Refer: https://wso2.org/jira/browse/IDENTITY-4413

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
