### ISSUE TITLE
[DOC] Documentation for SCIM 2.0 REST APIs with IS 5.8.0 has wrong title for PATCH and PUT in groups endpoint

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5506]
The available documentation for SCIM2 in IS 5.8.0 is [[1]](https://docs.wso2.com/display/IS580/Using+the+SCIM+2.0+REST+APIs)

In the doc, the title for PATCH and PUT in groups endpoint says "Update Users". Instead, it should be corrected as "Update Group".

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
