### ISSUE TITLE
EntitlementExtensionBuilder does not support AttributeFinder properties with comma in value

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5507]
The EntitlementExtensionBuilder only passes the first piece of each AttributeFinder property value if the value contains a comma. 
The flawed code is:
` 
String[] props = properties.getProperty(className + "." + j++).split(",");
                designatorProps.put(props[0], props[1]);
`
If the property is `foo.bar.MyAttributeFinder.1=key,hello,world,` we would get the property `key` -> `hello` in the AttributeFinder.

        
This is repeated several times in EntitlementExtensionBuilder.

Repository: https://github.com/wso2/carbon-identity-framework
Previous Issue: https://github.com/wso2-attic/carbon-identity/issues/1663
OT Jira: https://wso2.org/jira/browse/IDENTITY-4518

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
