### ISSUE TITLE
Adopt the same searching mechanism used in Search Users for Count Users

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5508]
**Steps**

1. Connect a JDBC user store (primary or secondary).
2. Navigate to MC and create two users namely Test and Test2.
Search the user "Test". Then only Test user will be returned
Search the same user "Test" in the "Count Users" section. Then the count will be returned as 2 for Test as well as Test2

**Improvement**
1. The two searching implementation behaves in two different ways which will confuse the user (Also, note that the two functions are available in the same page. Same page but two different implementations)
2. The operators used for searching (* vs %)
3. The counts are by default displayed in Count Roles but not in Count Users (0 users displayed until search)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
