### ISSUE TITLE
STS SAML Token Validity Period should be configurable

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5509]
There is no way to modify the period of validity of a ticket SAML2 for the STS service. It would be interesting that could change.

OT JIRA: https://wso2.org/jira/browse/IDENTITY-4614

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
