### ISSUE TITLE
Special characters for Tenant Domain

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5510]
Currently usernames can have special characters by configuring the 'UsernameJavaRegEx' property in 'user-mgt.xml. Can configure the 'UsernameJavaRegEx' property in 'user-mgt.xml to allow special characters for the user names including tenant admin user name. But tenant domain is validated as considering special characters are illegal characters for the tenant domain name.

It would be an improvement to allow special characters for Tenant Domain

<img width="1467" alt="Screen Shot 2019-06-09 at 2 40 43 PM" src="https://user-images.githubusercontent.com/17597293/59158596-dbb32d80-8ad9-11e9-9514-97474e968771.png">

Original issue: https://wso2.org/jira/browse/IDENTITY-3035

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
