### ISSUE TITLE
SingleLogoutRequest.setLogoutResponse() is a misnomer

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5511]
In org.wso2.carbon.identity.sso.saml, the SingleLogoutRequestDTO.setLogoutResponse() method is a misnomer. For clarity, it really should be refactored to something like setRequest or anything that doesn't say response. The method is used for storing the request that is to be made, not the response. It'll help with code clarity.

Original issue: https://wso2.org/jira/browse/IDENTITY-3740

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
