### ISSUE TITLE
Number of concurrent active session for user

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5512]
Limit the number of concurrent sessions for system administrators or users who are working in sensitive domains. This configuration could be based on tenant, user store or role.

Original issue : https://wso2.org/jira/browse/IDENTITY-4191

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
