### ISSUE TITLE
Show the revoked state of a OAuth App

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5513]
Moved from: [https://wso2.org/jira/browse/IDENTITY-7133](https://wso2.org/jira/browse/IDENTITY-7133)

When you revoke your OAuth application IS doesn't indicate the state of the Application, only if you revoke again you will know the application is already revoked. Can we address this?

![Screenshot from 2017-12-12 07-56-06](https://user-images.githubusercontent.com/12288369/59160101-62bed080-8aef-11e9-8a65-e23f53b88ee6.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
