### ISSUE TITLE
Change the OAuth config page title to Camel Case

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5514]
Moved from: [https://wso2.org/jira/browse/IDENTITY-7134](https://wso2.org/jira/browse/IDENTITY-7134)

Can we do the $subject?

![Screenshot from 2017-12-12 08-01-56](https://user-images.githubusercontent.com/12288369/59160114-c3e6a400-8aef-11e9-93ff-cc5344fd8e67.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
