### ISSUE TITLE
Mismatching colum name in regenerate confirmation message

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5515]
Moved from: https://wso2.org/jira/browse/IDENTITY-7132

When you regenerate your client secret, the confirmation message says,

> Client Secret successfully updated for Client ID: f7z2OVfpLfZxBgZamvgyXlclDNIa

This should be matched with the Field name. It should be Client Secret Updated for OAuth Client Key: f7z2OVfpLfZxBgZamvgyXlclDNIa

![Screenshot from 2017-12-12 07-44-48](https://user-images.githubusercontent.com/12288369/59160147-7b7bb600-8af0-11e9-9cf2-d90d553fbb60.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
