### ISSUE TITLE
Tool-tip and the page title doesn't match when editing OAuth config

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5518]
Moved from: https://wso2.org/jira/browse/IDENTITY-7120

Refer the attached screenshot.

![Screenshot from 2017-12-11 14-28-44](https://user-images.githubusercontent.com/12288369/59160366-b252cb80-8af2-11e9-909e-b6a95585ef00.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
