### ISSUE TITLE
Sort the Certificate Alias list by alphabetical order in SAML config page

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5519]
Moved from: https://wso2.org/jira/browse/IDENTITY-7112

If you have a long list of Certificate Aliases it's difficult to find it since the list is not ordered. Can we sort the list Alphabetically?

![Screenshot from 2017-12-11 13-41-11](https://user-images.githubusercontent.com/12288369/59160409-3ad16c00-8af3-11e9-916b-0742b06e7e7b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
