### ISSUE TITLE
Confirmation Code Revocation

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5521]
Moved from: https://wso2.org/jira/browse/IDENTITY-7064

In case of a forgery, we may need to expire the confirmation link, manually before the configured time (without resending the confirmation link).

Subtask of https://wso2.org/jira/browse/IDENTITY-7062

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
