### ISSUE TITLE
Authentication error when user decided to cancel the authentication via the directed federated IDP

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5522]
Steps to recreate the issue
1. Create Google and Facebook as federated IDPs
2. Create an SP (ex: travelocity.com)
3. Connect the SP to authenticate with either Facebook or Google
4. Go to Travelocity app and select Facebook to authenticate
5. When the facebook login page is loaded select 'Not Now' option (scenario - User directed to the Facebook page, but then user decided not to sign in using the facebook, therefore select the 'Not Now' option to go back to the application login page)

Refer to https://wso2.org/jira/browse/IDENTITY-6713

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
