### ISSUE TITLE
Unused 'EnableCaptchaVerification' property in 'accountrecoveryendpoint' web.xml

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5523]
Noted that there is an unused property as 'EnableCaptchaVerification' in the web.xml of accountrecoveryendpoint web app.
This should be removed to avoid confusions.
```
    <context-param>
        <param-name>EnableCaptchaVerification</param-name>
        <param-value>false</param-value>
    </context-param>

```

Refer to https://wso2.org/jira/browse/IDENTITY-6813

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
