### ISSUE TITLE
Fix org.wso2.identity.integration.test.oauth2.IDENTITY6777OAuth2TokenExpiryTestCase

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5524]
org.wso2.identity.integration.test.oauth2.IDENTITY6777OAuth2TokenExpiryTestCase test cases passes in isolation but fails when run together with other tests. Need to fix it.

Refer to : https://wso2.org/jira/browse/IDENTITY-6829

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
