### ISSUE TITLE
405 method not allowed thrown when using the invalid URL

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5525]
Moved from: https://wso2.org/jira/browse/IDENTITY-6844

1. login to the IS carbon console with "https://192.168.48.71:9443/cabon" (note the "cabon")
2. provide the correct credentials and login

the page goes to a "405 - Method not allowed" page.

Expected outcome:
If the page/path does not exist it should show a 404 page instead

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
