### ISSUE TITLE
Deprecate legacy feature implementations

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5527]
The following implementations should be deprecated and indicated in the docs

- RemoteClaimManagerService: see https://wso2.org/jira/browse/IDENTITY-6832
- Old implementation of DCR/DCRM: see https://wso2.org/jira/browse/IDENTITY-6808

**Comment by janakamarasena** [comment]
We need to remove openid as well.
https://wso2.org/jira/browse/IDENTITY-6304

**Comment by omindu** [comment]
Legacy notification management - https://wso2.org/jira/browse/IDENTITY-7011

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
