### ISSUE TITLE
IDENTITY-7159  No validations for admin services

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5529]
Moved from   https://wso2.org/jira/browse/IDENTITY-7159
When admin services are use to create SP/ IDP no mandatory fields validations are check. If user add SP/ IDP without mandatory fields its give errors when view/edit same via UI and also functionality breaks which is hard to debug. Therefore all the validation we do from UI should be done for admin service calls as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
