### ISSUE TITLE
IDENTITY-7077 Issues in the descriptions in the user-mgt.xml file

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5534]
Moved from https://wso2.org/jira/browse/IDENTITY-7077

Following issues are identified in the descriptions of the user-mgt.xml file.

1. In the below section No 3. should be added for the "isADLDSRole" property
2. " In which role is stored at user level." in No 2. is not a complete sentence
```
They are :
                 1.Referral - (comment out this property if this feature is not reuired) This enables LDAP referral support.
                 2.BackLinksEnabled - (Do not comment, set to true or false) In some cases LDAP works with BackLinksEnabled.
                 In which role is stored at user level. Depending on this value we need to change the Search Base within code.
                 isADLDSRole - (Do not comment) Set to true if connecting to an AD LDS instance else set to false.
```
3. A grammatical mistake in the below sentence. "Needs" should be changed to "need"

``Currently the identified escape characters that needs to be replaced are '\' & '\\'
`
4. Proper punctuation rules are not followed. 
Example, comma is not used in required places.

5. The following properties are not available in the JDBCUserStoreManager, but the description says the below.

`Furthermore properties, IsEmailUserName and DomainCalculation are readonly properties.`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
