### ISSUE TITLE
Can not perfom SCIM2 operation once we defined a WebContextRoot

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5539]
Steps to reproduce:

1. open the carbon.xml and change the WebContextRoot as follows,
`<WebContextRoot>/sarubi</WebContextRoot>`
2. Create a tenant as a test.com
2. Once we added a web context root, server URL should be 
https://localhost:9443/sarubi/t/test.com/carbon/user/user-mgt.jsp?ordinal=1
3. Try to create a user using the following correct URL, 
https://localhost:9443/sarubi/t/test.com/scim2/Users
Response as, 
`<html>
    <body>No service was found.</body>
</html>`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
