### ISSUE TITLE
"Location" URL is Wrong When We create a User for a Tenant 

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5540]
Steps to reproduce:
in IS 5.6.0

1. Create a tenant as test.com
2. Create a user using SCIM2
URL https://localhost:9443/t/test.com/scim2/Users
Response will be 
`{
    "emails": [
        {
            "type": "home",
            "value": "kim.jackson@gmail.com"
        }
    ],
    "meta": {
        "created": "2019-06-10T13:35:19Z",
        "location": "https://localhost:9443/scim2/Users/df61cf7f-2cd0-4027-952f-d682c2064129",
        "lastModified": "2019-06-10T13:35:19Z",
        "resourceType": "User"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "roles": [
        {
            "type": "default",
            "value": "Internal/everyone"
        }
    ],
    "name": {
        "givenName": "kimxx",
        "familyName": "jackson"
    },
    "id": "df61cf7f-2cd0-4027-952f-d682c2064129",
    "userName": "kimxx"
}`

Location URL doesn't contain tenant name,
```
Expected: 
        "location": "https://localhost:9443/t/test.com/scim2/Users/df61cf7f-2cd0-4027-952f-d682c2064129",
```

This need to be fixed, need to add tenant check there.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
