### ISSUE TITLE
When account is locked, it says login failed, but should say account locked

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5541]
Moved from - https://wso2.org/jira/browse/IDENTITY-6723

Console error says 

[2017-12-15 20:37:14,348] ERROR {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} -  System error while Authenticating/Authorizing User : Account is locked for user samisa in user store PRIMARY in tenant carbon.super. Cannot login until the account is unlocked.

But UI just says ```Login failed! Please recheck the username and password and try again. ``` Should we not mention that account is locked?

**Comment by SwatiNEC** [comment]
Hi @vihanga-liyanage 

I am also facing an issue in account locking [Issue#5338](https://github.com/wso2/product-is/issues/5338).

Could you please suggest.

**Comment by rksk** [comment]
This will be resolved if you have enabled the `showAuthFailureReason` property for basic authenticator in `repository/conf/identity/application-authentication.xml`
```
	<AuthenticatorConfigs>
		<AuthenticatorConfig name="BasicAuthenticator" enabled="true">
			<Parameter name="showAuthFailureReason">true</Parameter>
```
Then, the user will be redirected to retry.do with more descriptive error details. 
```
errorCode=17003&failedUsername=sajith%40sa.com&remainingAttempts=0
```
The error code 17003 says the user is locked. You will have to customize the retry.jsp in authentication endpoint to show the information to the end-user.

**Comment by aaptl** [comment]
i have enabled the showAuthFailureReason property for basic authenticator in repository/conf/identity/application-authentication.xml
but after restarting the wso2 server its automatically getting removed

**Comment by rksk** [comment]
> i have enabled the showAuthFailureReason property for basic authenticator in repository/conf/identity/application-authentication.xml but after restarting the wso2 server its automatically getting removed

If you are using >= IS 5.9.0, the following needs to be added to the deployment.toml instead.
```
[authentication.authenticator.basic.parameters]
showAuthFailureReason = true
```
