### ISSUE TITLE
Allows to login to service provider home page when a invalid email is given for the claim

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5544]
1. Run the wso2 IS pack
2. Login to the management console
3. Configure Travelocity as a service provider using inbound authenticator SAML
4. Configure email address as a custom claim for the service provider 
5. Access http://localhost:8080/travelocity.com
6. Click on SAML redirect binding
7. Will direct to claim input page
8. Input as abc for email address
9. Allow to log into the traveocity home page

Expected result
If a non valid email given as input should not be able to log in to the travelocity home page. email validation should be required.

Actual result
Allow to log in to travelocity home page

**Comment by DMHP** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-7054

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
