### ISSUE TITLE
Provide a notification for an invalid domain name

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5548]
Steps to reproduce the issue
1. Create two IDPs (ex: facebook, google)
2. Configure Travelocity as the service provider and provide multi options for Facebook and Google IDPs
3. Add a query param name for travelocity.properties file with invalid parameter name (QueryParams=fidp=facebok )
4. Log in to Travelocity and enter invalid domain (home realm that is invalid) and submit

Observation
Error message does not specifically say the fidp is not valid. It says the Domain is invalid

Expected Results
Better to provide a notification that the fidp is not valid rather than the 'Domain' name

Note - When tenancy is used (QueryParams=fidp=RDIP&tenantDomain=tenant.com) we should be specific whether the domain is invalid or the fidp is invalid

![image](https://user-images.githubusercontent.com/12690906/59192755-16cc6400-8ba1-11e9-9291-721ab6e2e71e.png)
Originally reported in [1]
[1] https://wso2.org/jira/browse/IDENTITY-7025

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
