### ISSUE TITLE
When user store disabled, user can retrieved the role count of that user store via countRolesInDomain

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5551]
**Steps**
1.Connect a JDBC primary user stores
2. Navigate to MC and add roles to each user store
3. Disable that user store. (eg :wso2 )
4. Invoke countRolesInDomain via soapUI
_admin service: https://localhost:9443/services/UserStoreCountService_

***Request***
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:countRolesInDomain>
         <!--Optional:-->
         <xsd:filter></xsd:filter>
         <!--Optional:-->
         <xsd:domain>wso2</xsd:domain>
      </xsd:countRolesInDomain>
   </soapenv:Body>
</soapenv:Envelope>
```
***Response***
```
 <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns:countRolesInDomainResponse xmlns:ns="http://org.apache.axis2/xsd">
         <ns:return>1</ns:return>
      </ns:countRolesInDomainResponse>
   </soapenv:Body>
</soapenv:Envelope>
```

***Expected outcome***
-1 must return

**Type**
Bug

**Priority**
High

**Affected version**
5.2.0, 5.8.0

**Environment**
OS: Ubuntu 14.04.5 LTS
JDK: 1.7.0_79
Database : oracle
Browser : Firefox
Setup : Standalone

**Component/s**
user-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/User Mgt, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/High

Moved from https://wso2.org/jira/browse/IDENTITY-5160

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
