### ISSUE TITLE
XACML policy source view display a incomplete source code

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5552]
Moved from: https://wso2.org/jira/browse/IDENTITY-7073

**Steps to recreate the issue**
1. Run IS 5.4.0 beta pack
2. Log into the management console and configure 2 JDBC user stores as secondary user stores 
3.In the management console Go to Main > Entitlement > PAP > Policy administration 
4. Select standard policy editor 
5. Define a policy
6. Click on Finish
7. Go to Entitlement > Policy administration
8. Select the policy you created
9. go to the source view

**Observations**
Will display incomplete source code

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
