### ISSUE TITLE
When listing roles from scim endpoint, internal roles which are added from management console are not be displayed

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5553]
**Description**
In the user store configuration, if the “SCIMEnabled” property is set to true when adding internal roles from the management console, SCIM attributes are not getting stored in IDN_SCIM_GROUP table. So that when listing roles from scim endpoint, those internal roles will not be displayed.

**NOTE**
This is a known limitation of user core where user operation event listeners (or any similar listener) doesn't get invoked when adding internal roles. We are using these listeners to update scim related tables with scim metadata.
Without having such listener model, it cannot achieve the requested use case.

**Type**
Bug

**Priority**
Normal

**Affected version**
5.1.0, 5.8.0

**Component/s**
SCIM

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/SCIM, Affected/5.1.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5357

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
