### ISSUE TITLE
"Add workflow" title is shown for the edit mode of the workflow

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5554]
Moved from: https://wso2.org/jira/browse/IDENTITY-7089

**Steps to reproduce**
1. Go to Identity -> Workflow Definitions
2. Create a workflow definition
3. Then select the 'Edit' option to edit the workflow definition.

**Observations**
"Add workflow" title shown in the workflow definition edit mode.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
