### ISSUE TITLE
Expose private methods as protected so simplify extensions

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5555]
**Description**
When developing extensions for the Identity Server we are often required to duplicate code when modifying the default behavior. This is largely due to the use of private methods and large protected\public methods. In order to reduce the amount of code copied to reduce the impact of patches on the extensions could we please address some of these issues.
A list of the method which we have copied due to the dependency on private methods are included.
[CustomSAML2SSOManager.txt](https://github.com/wso2/product-is/files/3272011/CustomSAML2SSOManager.txt)
[CustomStepBasedSequenceHandler.txt](https://github.com/wso2/product-is/files/3272012/CustomStepBasedSequenceHandler.txt)
[ReadWriteLDAPUserStoreManager.txt](https://github.com/wso2/product-is/files/3272013/ReadWriteLDAPUserStoreManager.txt)

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.2.0, 5.8.0

**Component/s**
all-identity

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Identity Mgt, Component/Extensions, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5251

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
