### ISSUE TITLE
Invalid SAML2 Issuer NameID format

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5556]
**Description**
An invalid SAML response is generated when something other than an absolute URI is entered in the "Identity Provider Entity Id" field when configuring an IdP for SAML2 Web SSO.

This is the offending line from the response:
<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">acme.com/samlsso</saml2:Issuer>

According to the SAML2 specs, when the "entity" NameID format is used, the value must be an absolute URI. This is causing a validation error in several SAML2 implementations we have tried.

**Notes**

> **8.3.6 Entity Identifier**
> **URI: urn:oasis:names:tc:SAML:2.0:nameid-format:entity**
> Indicates that the content of the element is the identifier of an entity that provides SAML-based services (such as a SAML authority, requester, or responder) or is a participant in SAML profiles (such as a service provider supporting the browser SSO profile). Such an identifier can be used in the <Issuer> element to identify the issuer of a SAML request, response, or assertion, or within the <NameID> element to make assertions about system entities that can issue SAML requests, responses, and assertions. It can also be used in other elements and attributes whose purpose is to identify a system entity in various protocol exchanges.
> The syntax of such an identifier is a URI of not more than 1024 characters in length. It is RECOMMENDED that a system entity use a URL containing its own domain name to identify itself

The recommendation as per the specification is that the entity uses a URL containing its own domain name to identify itself. The use of a URI is mandatory. A URI has been defined in the SAML 2.0 specifications as follows:

> **1.3.2 URI Values**
> All SAML URI reference values have the type xs:anyURI, which is built in to the W3C XML Schema Datatypes specification [Schema2].
> Unless otherwise indicated in this specification, all URI reference values used within SAML-defined elements or attributes MUST consist of at least one non-whitespace character, and are *REQUIRED to be absolute* [RFC 2396].
> Note that the SAML specification makes extensive use of URI references as identifiers, such as status codes, format types, attribute and system entity names, etc. In such cases, it is essential that the values be both unique and consistent, such that the same URI is never used at different times to represent different underlying information.

*****Requirement***
URI validation should be implemented to the field for ensuring validity of the provided URI**

**Type**
Bug

**Priority**
High

**Affected version**
5.1.0, 5.8.0

**Component/s**
saml2-sso

**Severity**
Major

**Estimated Complexity**
Novice

**Label/s**
Type/Bug, Component/SAML, Affected/5.1.0, Affected/5.8.0, Severity/Major, Complexity/Low, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-4992

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
