### ISSUE TITLE
Audit logs for user profile/claim update

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5557]
**Description**
Currently, when a user is updated, it's not logged in audit logs. The purpose of having audit logs is to log events in more end-user level. 
Profile updates are done via the management console, dashboard and API calls should be also logged in audit logs.

Therefore UserMgtAuditLogger should include doPostSetUserClaimValue, doPostSetUserClaimValues, doPostDeleteUserClaimValues, doPostDeleteUserClaimValue method implementations to log those events.

**Comments**
* Implement this using **UserOperationEventListener**[1]. Since **UserMgtAuditLogger** is an already implemented UserOperationEventListener for audit logging purposes, improving the listener with missing methods would be ideal.
* Names of the private method, 'getUser' in UserMgtAuditLogger can be changed with something more meaningful such as 'getInitiator' or 'getLoggedInUser' which would more explain the purpose and outcome of the method. _These methods might be purposely implemented in this way to avoid any additional complexities_

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserMgtAuditLogger.java

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.3.0, 5.8.0

**Component/s**
user-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/User Mgt, Affected/5.3.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5557

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
