### ISSUE TITLE
Provide the capability to dynamically import certificates to the trust store

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#5558]
Currently, the identity server does not have the capability to import certificates to the trust store dynamically. So it needs a restart after importing that to the trust store.

**Comment by nirmal070125** [comment]
ref: 001E000001244KH

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
