### ISSUE TITLE
IDENTITY-6952 Move the "AccessTokenValueGenerator" element as a child element of "IdentityOAuthTokenGenerator"

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5561]
Moved from https://wso2.org/jira/browse/IDENTITY-6952

Move the "AccessTokenValueGenerator" element in the identity.xml as a child element of the IdentityOAuthTokenGenerator as access token value generator is a sub component of the IdentityOAuthTokenGenerator.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
