### ISSUE TITLE
IDENTITY-6953 Improve the introspection API to handle JWT tokens.

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5562]
Moved from https://wso2.org/jira/browse/IDENTITY-6953

When the token is JWT, introspection API should return JWT specific parameters, which are optional in other cases.

[1] Ex:

1. 'jti' OPTIONAL: String identifier for the token, as defined in JWT
2. 'aud' OPTIONAL: Service-specific string identifier or list of string identifiers representing the intended audience for this token, as defined in JWT

[1] https://tools.ietf.org/html/rfc7662

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
