### ISSUE TITLE
Allow two claims mapped with same local claim in service level

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5566]
Currently, through admin service, we could add two claims mapped with same local claims but through UI we can't create two external claims mapped with same local claim.

We need to fix the admin services to not to allow to create two external claims mapped with same local claims.

**Reproduce steps**
1. Create an oidc claim called "role"(which is mapped to local role claim.) through admin service.

claim creation is successful even though we already have an oidc claim called "groups" which is mapped with local role claim.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
