### ISSUE TITLE
After delete the user role existing user can access resource

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5567]
Moved from https://wso2.org/jira/browse/IDENTITY-4424

Setup:
WSO2 IS 5.0.0 + SP1 ,Secondary user store is read only LDAP.
Steps to reproduce,
Create a sample xacml policy(attached policy.xml) for read access to the dashbord (https://localhost:9443/dashboard).
Upload to the IS and publish it.
create the Internal/manager role and add an user test1.
then use tryit tool to validate the policy. Now validation success(permit).
Then delete the role Internal/manager using management console.
Again validate with tryit tool , now permit access.
To reconfirm the issue;
Option 1
Restart the IS and repeat the validation above. Now validation failed(deny - expected behavior).
Option 2
Then again add role Internal/manager and assign the test1 user to it.
then validate with tryit tool and validation success.
once again delete the role and validate.
This time also validation success(permit).
Now clear the attribute cache in PDP>extention.
Again validate validation fail(deny).

policy

`<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"  PolicyId="sample-policy-3" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
   <Target>
      <AnyOf>
         <AllOf>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">https://localhost:9443/dashboard</AttributeValue>
               <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"></AttributeDesignator>
            </Match>
         </AllOf>
      </AnyOf>
   </Target>
   <Rule Effect="Permit" RuleId="Rule-1">
      <Target>
         <AnyOf>
            <AllOf>
               <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                  <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</AttributeValue>
                  <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"></AttributeDesignator>
               </Match>
            </AllOf>
         </AnyOf>
      </Target>
      <Condition>
         <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:any-of">
            <Function FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-equal"></Function>
            <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">Internal/manager</AttributeValue>
            <AttributeDesignator AttributeId="http://wso2.org/claims/role" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"></AttributeDesignator>
         </Apply>
      </Condition>
   </Rule>
   <Rule Effect="Deny" RuleId="Deny-Rule"></Rule>
</Policy>  
`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
