### ISSUE TITLE
EntitlementExtensionBuilder does not support multiple instances of same Attribute Finder with different configuration

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5568]
Moved from https://wso2.org/jira/browse/IDENTITY-4517

If I build a generic attribute finder that can support multiple uses, there is no way to distinguish between two instances in configuration. E.g. I specify the two finders in entitlement.properties

PIP.AttributeDesignators.Designator.1=foo.Bar
PIP.AttributeDesignators.Designator.2=foo.Bar

To supply each instance with configuration I define properties:

foo.Bar.1=property,value

Since the property names are based on the class name of the attribute finder, there is no way to supply different configuration for each instance. This severely limits the reusability of attribute finders.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
