### ISSUE TITLE
Fix Double-Checked Locking

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5569]
Moved from https://wso2.org/jira/browse/IDENTITY-4535

Following classes includes double-checked locking which won't work in multi-threaded environment. No state is maintained in these classes, but need to be fixed as a quality improvement.
OAuthServerConfiguration.java	279
PolicyEditorEngine.java	64
OAuthServerConfiguration.java	384
OAuthCallbackHandlerRegistry.java	78
OAuthServerConfiguration.java	541
TokenValidationHandler.java	108
UserInfoEndpointConfig.java	54
OAuthCallbackHandlerRegistry.java	61
IdentityClaimManager.java	49
OAuthServerConfiguration.java	472
OAuthServerConfiguration.java	504
WSRealm.java	105
IdentityProfileManager.java	43
OAuthServerConfiguration.java	345
EntitlementBaseCache.java	96
OAuthServerConfiguration.java	161
OAuthServerConfiguration.java	607
MultipleCredentialsUserProxy.java	170
ClaimCache.java	39
UserInfoEndpointConfig.java	74
EntitlementEngine.java	131
ThriftAuthenticationConfigParser.java	65
UserInfoEndpointConfig.java	98
IdentityConfigParser.java	69
SCIMAuthenticatorRegistry.java	40
AuthorizationHandlerManager.java	68
EntitlementEngine.java	120
OAuthServerConfiguration.java	430
AccessTokenIssuer.java	81
UserInfoEndpointConfig.java	121
OAuthServerConfiguration.java	640
OAuthAdminService.java	514
IdentityLogTokenParser.java	63
EntitlementAdminEngine.java	96
OAuthServerConfiguration.java	667

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
