### ISSUE TITLE
Enforce best practices on OAuth clients from authorization server

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5570]
Moved from https://wso2.org/jira/browse/IDENTITY-4548

Referring section "2.3.1. Client Password" in https://tools.ietf.org/html/rfc6749#page-16

> Including the client credentials in the request-body using the two
> parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
> to directly utilize the HTTP Basic authentication scheme (or other
> password-based HTTP authentication schemes).

Though its the client who should decide the best way to send credential, It would be better to enforce the same from the authorisation server. So it would be nice to have the authorisation server don't obtain client credential from the request body as the default behaviour. It can give an option at the SP/App registration process to enable obtaining client credentials from the request body, so the authorisation server should retrieve client credential from the request body only if that option is set.

And as per current behaviour, authorization server reads request parameters without considering the credential send as the query parameters or the post body. Since the specification forbid clients to send credentials over the url, its better to enforce the same from the authorisation server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
