### ISSUE TITLE
Cannot retrieve user counts by using Identity Claims.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5571]
Moved from https://wso2.org/jira/browse/IDENTITY-4563

If the Identity.Data.Store is JDBCIdentityDataStore then the Identity claims are persisted in the identity db. (Not in user store)

Since the org.wso2.carbon.identity.user.store.count.jdbc.JDBCUserStoreCountRetriever retrive the user count from the user store, it cannot search user count with identity claims.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
