### ISSUE TITLE
Redundant UNIQUE index on UM_DOMAIN_NAME column of UM_TENANT table

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5572]
Moved from https://wso2.org/jira/browse/IDENTITY-4595

There are two UNIQUE indexes on UM_DOMAIN_NAME column of UM_TENANT table. In the schema we have the following index,

CREATE UNIQUE INDEX INDEX_UM_TENANT_UM_DOMAIN_NAME ON UM_TENANT (UM_DOMAIN_NAME);

In addition, the UM_DOMAIN_NAME column of UM_TENANT table is also marked UNIQUE which in turn creates an index on this column. Therefore the index INDEX_UM_TENANT_UM_DOMAIN_NAME is redundant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
