### ISSUE TITLE
Newly created user can view the pending approvals of the removed user with same username

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5573]
Steps to recreate the issue
1. Create two users and roles (Roles: Manager, Director | Users: manageruser, directoruser )
2. Create a workflow (multi-role approval process)
3. Create few user matching the workflow criteria

4. When logged in to IS portal with manageruser, pending approvals will list.
5. Delete the 'manageruser' and 'Manager' Role
6. Create another user with same username as 'manageruser'
7. Log in to IS portal with the newly created user
8. Previous pending approvals will list in the IS portal

Expected Behaviour
When removing a user, all the relevant artefacts should be removed. (New user should not be able to view the pending approval assigned for the older user with same usrname)

Refer to : https://wso2.org/jira/browse/IDENTITY-6790

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
