### ISSUE TITLE
Issue with "enforce user to provide missing required attributes"

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5576]
Enforce user to provide missing attribute can be done with skipping missing attribute page while do the federation authentication.
Steps to recreate:

Register SP for travelocilty app with SSO inbound authenticator
Add IDP for google federated authenticator
Map an additional claim in SP (e.g. phone)
Configure google IDP for federated outbound authenticator
Access travelocity with redirect url
Give google credentials => prompt to enter mendatory attribute
on "...authenticationendpoint/claim.do" page (see attached attribute.jpeg), click on browser back navigation button => directed to google choos account page 
select particular account which already provided the credentials => authentication succeed and directed to travelocity home page 

Refer to : https://wso2.org/jira/browse/IDENTITY-6849

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
