### ISSUE TITLE
Content in Sign in Help page is out dated

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5579]
Moved from: https://wso2.org/jira/browse/IDENTITY-7095

Seems content in https://localhost:9443/carbon/docs/signin_userguide.html is outdated. These should be updated to the latest carbon version.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
