### ISSUE TITLE
Can we add IS logo to the help pages

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5580]
Moved from: https://wso2.org/jira/browse/IDENTITY-7105

Currently, all the help pages have a WSO2 Carbon logo, which doesn't make much sense to an external user. Is it possible to add IS logo here?

![Screenshot from 2017-12-11 12-03-51](https://user-images.githubusercontent.com/12288369/59261893-db42a000-8c5b-11e9-84fd-02c3993ef88c.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
