### ISSUE TITLE
Support for X.500/LDAP Attribute Profile in WSO2IS

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5581]
**Description**
WSO2IS is already shipped by connecting with the LDAP server. Therefore it is better to support this profile by default

Spec line 1677 https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.1.0, 5.8.0

**Component/s**
saml2-sso

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/SAML, Affected/5.1.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5301

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
