### ISSUE TITLE
ciphertool failure for carbon.xml keystore passwords

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5582]
I've replaced the default keystore and private key with my own. Utilizing the ciphertool I've successfully replaced the database password inside of repository/conf/datasources files. Restarted the IS successfully. Was moving on to the keystore values inside of the carbon.xml file and I keep getting the following error (see attachment). I've confirmed that ciphertool.bat -Dconfigure executes successfully:

```
<KeyStore>
<!-- Keystore file location-->
<Location>${carbon.home}/repository/resources/security/KeyStore.jks</Location>
<!-- Keystore type (JKS/PKCS12 etc.)-->
<Type>JKS</Type>
<!-- Keystore password-->
<Password svns:secretAlias="Conf.Carbon.KeyStore.Password">password</Password>
<!-- Private Key alias-->
<KeyAlias>QaCert</KeyAlias>
<!-- Private Key password-->
<KeyPassword svns:secretAlias="Conf.Carbon.KeyPassword">password</KeyPassword>
</KeyStore>
```
I've triple checked the password in cipher-text.properties is correct. If I replace the ciphertool's references for keystore and key passwords inside of carbon.xml with the clear text version and restart, everything works fine again. The keystore/key passwords don't appear to resolve correctly at startup.

Refer to : https://wso2.org/jira/browse/IDENTITY-6799

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
