### ISSUE TITLE
SP description can be trimmed before inserting to the DB

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5583]
Moved from: https://wso2.org/jira/browse/IDENTITY-7103

It seems white spaces in the EOL, are not trimmed when IS inserts the description into the DB. We can improve this by trimming the value of the description.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
