### ISSUE TITLE
IDENTITY-7173 No systematic way to identify an attribute store

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5584]
Moved from https://wso2.org/jira/browse/IDENTITY-7173
Scenario
Consider about a scenarios that enterprise user’s details can be found in two places. User credentials may be kept in one user store and User’s attribute may be stored in another user store. When you are configuring the Attribute User store, you need to follow special notation for domain name such as follows.

Domain must be same as the corresponding credentials store
Domain name must be qualified with a post prefix called “-ATTRIBUTE-STORE”
Here we don't have a systematic way to identify attribute stores of a particular credential store rather than using a naming convention to distinguish the two types of user stores.

Expected
Introduce a property which specifies whether the user store is an attribute store or a credential store.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
