### ISSUE TITLE
Claims with nested tags are not properly handled

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5585]
Moved from https://wso2.org/jira/browse/IDENTITY-4615

Microsoft Windows Live claims do not work properly in WSO2 Identity Sever 5.1.0. The return claims include nested tags which are currently handled.

Related Stackoverflow link
http://stackoverflow.com/questions/36999133/configuring-microsoft-windows-live-claims-in-wso2/37005115#37005115

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
