### ISSUE TITLE
IDENTITY-6515 Security token reference based KeyInfo support in SAML2 supporting token validation

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5586]
It seems to be that "validateSignature(Assertion assertion, Crypto crypto)" is expecting only X.509 [1]

But i assume that it is fine to send a security token reference inside keyinfo. 
So; it is better to fix it.

[1] https://svn.wso2.org/repos/wso2/carbon/kernel/branches/4.2.0/dependencies/wss4j/1.5.11-wso2v6/src/org/apache/ws/security/saml/SAML2Util.java

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6515

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
