### ISSUE TITLE
[IS] Salesforce Outbound provisioning is not working in JIT mode when outbound provisioning in resident IDP also configured

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5587]
Please follow below steps to reproduce the issue.

1. Add salesforce provisioning idp and configure salesforce outbound provisioning connector.
2. Add federated IDP google/facebook etc.
3. Add travelocity service provider and add federated IDP as IDP created in #2 and add outbound provisioning as salesforce IDP created in #1 and enable JIT under outbound provisioning.
3. Add salesforce IDP as resident service provider outbound provisioning
4. Login to Identity server management console and add a user. If salesforce outbound provisioning works fine it'll provision the user to salesforce successfully.
5. Then try to login to travelocity service provider. This should authenticate with the federated IDP and provision that user into salesforce. But it's not working.

Note: When debugging the code identified EnableJIT flag populate as disable reason is we have added Outbound provisioning for Resident service provider and the resident service provider doesn't have Enable JIT option if we trigger user adding option first global variable initialize with the false flag for EnableJIT. Then if we try authenticating the user, flag is still false and provisioning will not work. 

Refer to : https://wso2.org/jira/browse/IDENTITY-6862

**Comment by hasinidilanka** [comment]
This behaviour is same for all the outbound provisioning connectors.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
