### ISSUE TITLE
Hard to find the Mgt Console URL since some other log print after that

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#5591]
Hard to find the Mgt Console URL since some other log print after that. IMO Mgt Console URL should be the last line.

Moved from https://wso2.org/jira/browse/IDENTITY-7194

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
