### ISSUE TITLE
Authenticated Session maintainence for multiple tenants (in the same browser)

### ISSUE THREAD

**Issue by isharak** [wso2/product-is#5592]
Currently WSO2IS (IS 5.4.1) does not create end user's session per tenant. Session is created for given server instance (Hostname of the server). And this session is tracked by a cookie that get created for the hostname exposed to outside.

If its need to create a separate session per tenant basic with the current versions, its need to virtually expose different tenants of WSO2IS from different hostnames. Following blog [1] explain similar approach (different hostnames for different service providers).. Have to follow the same approach for distinct tenants..

However, keeping the ticket open, until IS support this functionality as a first class feature.

[1] http://xacmlinfo.org/2015/11/24/service-provider-grouping-with-wso2-identity-server/

Moved from https://wso2.org/jira/browse/IDENTITY-3577

**Comment by ruwanta** [comment]
There are only one of two ways to identify session
1. having session ID in URL
2. having session ID in cookie.

Having session ID in URL is currently considered a security risk as it can be logged in access log systems. So only option is to keep the session ID in the cookie.

How the question is how to have separate cookie identified with different tenant. Cookies are isolated with "Host" +"Path". We need to encode tenant in either Host or Path. Encoding it in the path may not be a robust mechanism, as all URL has to conform to the same path. This might fail when there is a proxies and reveres proxies. Only robust way is to isolate by host name, if the tenant level session is required.

**Comment by rksk** [comment]
Done with https://github.com/wso2/product-is/issues/8975
