### ISSUE TITLE
Outbound JIT provisioning does not work if enabled after an attempt to inbound provision a user

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5595]
**Description**
1. Configure an SP with Travelocity.
2. Configure 2 IDPs for Facebook and an external IS.
3. Configure the Facebook IDP as a federated authenticator of the Travelocity SP.
4. Enable JIT inbound provisioning for the Facebook IDP.
5. Enable Outbound provisioning in the SP, for the external IS.
   - Do not check the option "Enable JIT".
6. Restart the IS (IS where the SP is configured)
7. Load tavelocity App.
   - Redirected to facebook.
8. Enter Facebook credentials.
   - User is logged in and the Travelocity app is loaded
   - User is provisioned to the first IS.
9. Delete the provisioned user.
10.Check the option 'Enable JIT' in the SP configurations in the outbound provisioning section for the external IS.
11. Repeat steps 7 - 8.
    - User is inbound provisioned to the first IS.
    - User is not outbound provisioned to the external Is.

If you skip the steps 7 - 10 in the above scenario, outbound provisioning is successful.

The same way, if you disable JIT outbound provisioning after performing inbound and outbound provisioning in the above scenario, the configuration change is not applied. I.e. The user is still outbound provisioned to the external IS.

**Note**
Problem here is, once the user is provisioned (that means if the user exists) the IS will not outbound provision the user.

So this is the behavior as for now. The workaround for this would be to define a provisioning role in the IDP configuration and assign the users to that role. 
Then all that users will be provisioned to the that IDP.

**Type**
Improvement

**Priority**
Low

**Component/s**
provisioning

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Outbound Prov, Severity/Major, Complexity/Medium, Priority/Low

Moved from https://wso2.org/jira/browse/IDENTITY-5111

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
