### ISSUE TITLE
IDENTITY-6564 Add IWA NTLM Authenticator to Connector Store

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5597]
This JIRA is to track the task of adding IWA NTLM Authenticator to the connector store.

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6564

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
