### ISSUE TITLE
Incorrect error message shown while adding SP

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5599]
Moved from https://wso2.org/jira/browse/IDENTITY-7198

$subject

Please provide Service Provider ID

UI says  Service Provider Name:* not ID

![image](https://user-images.githubusercontent.com/9441136/59264289-69b92080-8c60-11e9-82fd-219765f108f1.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
