### ISSUE TITLE
Add a UI configuration to choose email address to send notifications

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5603]
It would be easy if we had a UI, to configure the email address to send notifications.

For example, in recovery scenarios, we can use a different/secondary email instead of primary mail. For other simple notifications, we can use primary mail to send notifications.

**Comment by DMHP** [comment]
Originally reported in [1].

[1] https://wso2.org/jira/browse/IDENTITY-6936

**Comment by cwichoski** [comment]
Or an option to choose wich email claim to use as secondary, Work Email, Other Email, Personal Email, and so on.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
