### ISSUE TITLE
Add Text Area support in IDP UI for the SMS-OTP Authenticator.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5604]
Moved from https://wso2.org/jira/browse/IDENTITY-4635

HTTP Payload field have large text in SMS OTP. We need text area field in authentication framework.

![image](https://user-images.githubusercontent.com/8455535/59264722-5d819300-8c61-11e9-94a4-db7017692d8b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
