### ISSUE TITLE
OIDC Discovery - certain parameter values in WebFinger request are not validated

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5606]
**Description**
In the web finger request (i.e. https://localhost:9443/.well-known/webfinger?resource=acct:admin@localhost&rel=http://oopenid.net/specs/connect/1.0/issuer), although the 'rel' parameter is mandatory, the parameter value is not validated.
i.e. Even the following URL gives the expected response 
https://localhost:9443/.well-known/webfinger?resource=acct:admin@localhost&rel=ht21324243

In addition the host value of the resource parameter is not validated either.
i.e. The following request is successful.
https://localhost:9443/.well-known/webfinger?resource=acct:admin@newhost&rel=12345

Apart from the above the request works even if you specify a non existing user in the resource parameter as long as the tenant domain is valid
For https://localhost:9443/.well-known/webfinger?resource=acct:admin@localhost&rel=http://oopenid.net/specs/connect/1.0/issuer) - Super tenant domain is taken here.
For . https://localhost:9443/.well-known/webfinger?resource=acct:admin@tenant1.com@localhost&rel=http://oopenid.net/specs/connect/1.0/issuer - Tenant 1 domain

**Type**
Task

**Priority**
Normal

**Affected version**
5.3.0, 5.8.0

**Component/s**
OAuth

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Task, Component/OAuth, Affected/5.3.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5327

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
