### ISSUE TITLE
Improve XACML cache clearing logic when User attributes are updated.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5607]
According to the current implementation, when a user updates his attributes a listener is fired invalidation the attribute, decision and policy caches.
We need to improve the cache clearing logic to invalidate/remove only affected entries in caches like the policy cache.

OT JIRA: https://wso2.org/jira/browse/IDENTITY-4890

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
