### ISSUE TITLE
Cannot see a IDP created using wso2 admin services without signing back for the management console

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5608]
Moved from:https://wso2.org/jira/browse/IDENTITY-7107

**Steps to recreate the issue**
1.Run the pack IS 5.4.0
2.Create an IDP using wso2 admin services

**Expected Results**
Should be able to view the created the IDP from the management console UI

**Actual Result**
Need to sign out from the management console and sign in again to see the created IDP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
