### ISSUE TITLE
Claim retrieval and user mapping for IWA Federated authenticator

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5609]
**Description**
Implementation for User lookup and claim retrieval for federated IWA authenticator

**Type**
Improvement

**Priority**
Normal

**Component/s**
application-authenticators, claim-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Claim Management, Affected/5.8.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5190

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
