### ISSUE TITLE
IS should provide an error message if the email settings are incorrect or failed to sent the mail.

### ISSUE THREAD

**Issue by thushaaanthan** [wso2/product-is#5610]
I have configured password recovery with IS 5.2.0 using email notifications. The issue is, 
Even though we have provide invalid email settings(invalid host, invalid/empty port) under axis.xml file, Identity server didn't prompt any error message and the mail also not getting sent from the mail server. 
Instead of giving an error message, Identity server provides below log,

> INFO {org.wso2.carbon.identity.mgt.mail.DefaultEmailSendingModule} -  Sending user credentials configuration mail to shanakaw@wso2.com

IS should provide an error message if the email settings are incorrect or failed to sent the mail.

moved from: https://wso2.org/jira/browse/IDENTITY-5826

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
