### ISSUE TITLE
IDENTITY-6047 Need to run the OAuth2 test cases with caching disabled.

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5613]
We need to improve the OAuth test cases, so that same test cases runs on server where oauth cache is disabled.

**Labels**
Type: Improvement
Priority: Normal
Component/s: oauth
Labels: component_verified
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6047_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
