### ISSUE TITLE
IDENTITY-6152 Make Symmetric Key Encryption the default

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5614]
Mail : [Architecture] [IS] Move to symmetric data encryption from asymmetric encryption

**Labels**
Type: Task
Priority: Highest
Component/s: product-is
Severity: Major
Estimated Complexity: Novice

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6152_

**Comment by malithie** [comment]
This is now addressed with https://github.com/wso2/product-is/issues/7898
