### ISSUE TITLE
Issue in passing tenant domain in Federation and SAML SSO with office 365

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5618]
**Description**
1. Follow [1] and configure Azure AD to trust IS
2. Follow [2] and configure office 365 federation with IS for a tenant user. - Eg : User name : kaushie6@qa.federationdemo.com
3. Try to access the url "https://login.microsoftonline.com/" once the configurations are done.
4. Enter the user name with in the ofice 365 login page - Eg : kaushie6@qa.federationdemo.com

redirected to IS login page
5. Enter the complete user name with domain Eg : kaushie6@qa.federationdemo.com@tenant4.com
The user domain is not recognized. (screenshot attached)
The same issue can be observed during SAML SSO with office 365.

How do we pass the tenant domain here. 
In the attempt to add a user on Azure AD with along with the tenant domain for User principle name , an Invalid Syntax error is thrown.
What is the correct way to handle this?

Note that this works in super tenant mode.
```
https://localhost:9444/authenticationendpoint/login.do?client-request-id=f893af43-dfb4-4b22-a12a-8e480ddfba1b&commonAuthCallerPath=%2Fpassivests&forceAuth=false&passiveAuth=false&popupui=&wa=wsignin1.0&wctx=estsredirect%3D2%26estsrequest%3DrQIIAeNisNLJKCkpKLbS1y_ILypJzNHLzUwuyi_OTyvJz8vJzEvVS87P1csvSs9MAbGKhLgEnNdP_rHlvpL3Qq0-D977u6RXMSoTNkL_AiPjC0bGW0yC_kXpninhxW6pKalFiSWZ-XmPmHhDi1OL_PNyKkPys1PzJjHz5eSnZ-bFFxelxafl5JcDBYAmFCQml8SXZCZnp5bsYlZJTTW3NDJJTdNNtTQy0jUxSk7WTTQ1NtE1MUk2MTc1SDazTLO4wCLwg4VxESvQzec2xEndFnru0iHjWVnmKyp8ilW_IiTY3Du8LCUvxcLFIynP1dXU0MfP0a0828PTNSitwLcy16UgM8LJL0-_3NbAyvAAJyMA0&wtrealm=urn%3Afederation%3AMicrosoftOnline&sessionDataKey=a3a8f2b3-ef82-46db-8775-51c488459eb0&relyingParty=urn%3Afederation%3AMicrosoftOnline&type=passivests&sp=Office365&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL&authFailure=true&authFailureMsg=user.tenant.domain.mismatch.message
```
![is_login](https://user-images.githubusercontent.com/12439288/59266855-5f018a00-8c66-11e9-911e-50592ecc10b2.png)
![login_failed](https://user-images.githubusercontent.com/12439288/59266856-5f018a00-8c66-11e9-8332-3639d1c67e74.png)

[1] https://docs.wso2.com/display/IS520/Configuring+Azure+Active+Directory+to+Trust+WSO2+Identity+Server
[2] https://docs.wso2.com/display/IS520/Configuring+Office+365+WS-Federation+with+Identity+Server

**Note**
There are two important points to note.

1. When configuring the IDP URL in Azure AD we have to give the correct tenants IDP URL. Which means if the SP is registered in a tenant, the IDP UTL must have the query param tenantDomain=wso2.com. Else if the SP is registered in super tenant space SaaS application configuration must be enabled. The screen shot attached indicates probably this kind of issue.

2. The subject value that is sent back to Azure AD must be understood by Azure AD as a unique AD user. I.e. if the subject value ends with "wso2.com", which is the tenant domain in IS, it doesn't mean anything to AD and it can't understand that subject. You may have to remove this part by unchecking "Use tenant domain in local subject identifier".

_Following Results were observed after applying the above two points_

1. Passed the tenant domain as a query parameter in the $passiveLogonUri.
2. "Use tenant domain in local subject identifier" was not checked.
3. The SP was registered in a tenant domain and the user was registered within the same tenant domain.
   - redirected to IS login page
   - Enter the complete user name with domain Eg : akk666@qa.federationdemo.com@tenant5.com
   - redirected to'https://login.microsoftonline.com/login.srf' (Screenshot attached)
   - User does not get logged in.

**Type**
Bug

**Priority**
Normal

**Affected version**
5.2.0, 5.8.0

**Environment**
30th Aug (pack) beta2
PostgreSQL 9.5.3
Ubuntu 14.04
JDK 1.7
Active Directory primary user store

**Component/s**
saml2-sso

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Identity Governance, Component/Identity Mgt, Affected/5.2.0, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-5516

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
