### ISSUE TITLE
IDENTITY-6214 Read redirect url for relying party from Service Provider configuration

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5619]
ATM, we keep relying party, redirect url mapping in registry. Need to get that from service provider configuration.

**Labels**
Type: Improvement
Priority: Normal
Component/s: oauth, saml2-sso, service-provider
Labels: component_verified
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6214_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
