### ISSUE TITLE
Unable to fail login attempt when multi attribute login is enabled using JDBCIdentityDataStore

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5620]
Moved from https://wso2.org/jira/browse/IDENTITY-4671

When the multi attribute login is enabled in the a secondary user store and when using JDBCIdentityDataStore the user will be allowed to login if an another attribute is used to do SSO login other than the one used to self sign the the user.

To reproduce

Enable email login in carbon.xml
Enable following configuration in Identity-mgt.properties
Identity.Mgt.User.Data.Store=org.wso2.carbon.identity.mgt.store.JDBCIdentityDataStore

Configure secondary user store and allow multi attribute login.

> <Property name="UserNameSearchFilter">(&amp;(objectClass=person)(|(mail=?)(uid=?)))</Property>
> <Property name="UserNameListFilter">((objectClass=person)(|(mail=*)(uid=*)))</Property>
> <Property name="UserDNPattern"/>
> <Property name="UserNameJavaRegEx">[a-zA-Z0-9@._-|//]{3,30}$</Property>
> <Property name="UserNameJavaScriptRegEx">^[\S]{3,30}$</Property>
> <Property name="MultipleAttributeEnable">true</Property>

Self register using UserInformationRecoveryService.registerUser operation with the username as "SecDomain/foo_1". Following is a sample request.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.mgt.identity.carbon.wso2.org" xmlns:xsd="http://dto.mgt.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:registerUser>
         <ser:userName>SecDomain/foo_1</ser:userName>
         <ser:password>password</ser:password>
		<ser:claims>
			<xsd:claimUri>http://wso2.org/claims/givenname</xsd:claimUri>
			<xsd:claimValue>test</xsd:claimValue>
		</ser:claims>
		<ser:claims>
			<xsd:claimUri>http://wso2.org/claims/lastname</xsd:claimUri>
			<xsd:claimValue>test</xsd:claimValue>
		</ser:claims>
		<ser:claims>
			<xsd:claimUri>http://wso2.org/claims/emailaddress</xsd:claimUri>
			<xsd:claimValue>foo_1@wso2.com</xsd:claimValue>
		</ser:claims>  
         <ser:profileName></ser:profileName>
         <ser:tenantDomain></ser:tenantDomain>
      </ser:registerUser>
   </soapenv:Body>
</soapenv:Envelope>
```

Then try to login to configured SP (travelocity.com) by using username as email "SecDomain/foo_1@wso2.com"

User will be able to login. However user should not allow to login.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
