### ISSUE TITLE
[Doc] Changing a user store's SCIM2 configuration after the creation of the user store is not supported

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#5621]
According to IS product design, enabling SCIM2 for a user store is considered as a one-time decision taken at the time of onboarding that user store. Changing this property later on is not anticipated. This should be reflected in IS docs.

**Comment by hauntingEcho** [comment]
currently, the UI allows you to change this property after initial setup (which can cause breakages) - ideally, guardrails could be in place to prevent this as well

**Comment by JKAUSHALYA** [comment]
Created the issue https://github.com/wso2/product-is/issues/6394 to track improvement that we need to do in IS side.

**Comment by dewniMW** [comment]
From IS 5.10.0 release onwards, all userstores will be using SCIM api by default. Therefore enabling SCIM2 property will be removed from user store configuration.

**Comment by IsuraD** [comment]
Resolving the issue since IS 5.10.0 release onwards, all userstores will be using SCIM api by default
