### ISSUE TITLE
IDENTITY-7156 Loading disabled policy via SOAP admin interface does not work correctly

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5622]
Moved from https://wso2.org/jira/browse/IDENTITY-7156
When loading a policy via the SOAP admin interface and setting the policy to "disabled" the policy remains active until the server is restarted.

I have tested against v5.4.0-beta applying the following test case:

A test case using the SOAP admin API EntitlementPolicyAdminService call addPolicy still demonstrates incorrect behavior.

Details for the test case is as follows:

Create a simple policy file
Load the policy file using the SOAP admin API EntitlementPolicyAdminService call addPolicy setting the Policy to disabled
Check the Admin GUI: Policy was added and correctly displayed as "disabled" in Policy View
Run an XACML entitlement request using curl
Policy is evaluated and server returns permit although the policy should not as it is disabled
Restart the WSO2 server
Run the same XACML entitlement request using curl again
Policy is not evaluated and server returns not applicable which is correct and expected
The SOAP call to load and deploy the policy is:

```
<?xml version="1.0" ?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
	<S:Body>
		<ns2:addPolicy xmlns:ns3="http://entitlement.identity.carbon.wso2.org/xsd" xmlns:ns2="http://org.apache.axis2/xsd" xmlns="http://dto.entitlement.identity.carbon.wso2.org/xsd">
			<ns2:policyDTO>
				<active>false</active>
				<policy>
				 ... XACML POLICY CUT FOR BREVITY ...
				</policy>
				<promote>true</promote>
			</ns2:policyDTO>
		</ns2:addPolicy>
	</S:Body>
</S:Envelope>
```
Let me know if you need anything else to reproduce the issue.

Please note the behavior is different from the problem described in IDENTITY-5603

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
