### ISSUE TITLE
IDENTITY-7144 Deny Overrides option does not make any difference in to XACML policy

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5625]
Moved from https://wso2.org/jira/browse/IDENTITY-7144

Deny Overrides option does not make any difference in to XACML policy.

1. Configure travelocity.com as a service provider.
2. Create a role called finance and sales and users belong to them
3. Configure XACML policy as below.

```
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" PolicyId="rolebasedplicy" RuleCombiningAlgId="urn:oasis:names:tc:xacml:3.0:rule-combining-algorithm:deny-overrides" Version="1.0">
   <Target>
      <AnyOf>
         <AllOf>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">travelocity.com</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/identity/sp/sp-name" Category="http://wso2.org/identity/sp" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
            </Match>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">finance</AttributeValue>
               <AttributeDesignator AttributeId="http://wso2.org/claims/role" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
            </Match>
         </AllOf>
      </AnyOf>
   </Target>
   <Rule Effect="Deny" RuleId="denyothers">
      <Target>
         <AnyOf>
            <AllOf>
               <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                  <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">travelocity.com</AttributeValue>
                  <AttributeDesignator AttributeId="http://wso2.org/identity/sp/sp-name" Category="http://wso2.org/identity/sp" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
               </Match>
            </AllOf>
         </AnyOf>
      </Target>
   </Rule>
</Policy>        
```
Check the screenshot for configurations.

Select Deny Overrides
serviceprovider is equal to travelocity.com
Subject is equal to finance (role - String)
Define Entitlement Rule(s)

denyothers - Deny
Serviceprovider is equal to travelocity.com
In here according to the document,

This combining algorithm combines decisions in such a way that if any decision is a Deny, then that decision wins. 
Deny overrides is one of the safest combining algorithms since it favors a Deny decision. However, if none of the children return a Deny decision, then the combining algorithm will never produce a Deny.

So according to this it should deny access for travelocity.com sp. But it allows the users who do not belong to finance role to login.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
