### ISSUE TITLE
User search does not search only in Primary when claims are given.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5626]
Moved from https://wso2.org/jira/browse/IDENTITY-4674

onfigure primary and secondary user stores. Configure multi attribute login. Enable email username.

Create a user in secondary user store as foo.

Go to management console users list

Give the search options
Select domain : Primary
Pattern : foo*
Select claim URI : emailAddress

This search will show the user SecDomain/foo in the secondary user store. However we have only specified to search in Primary user store only.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
