### ISSUE TITLE
IDENTITY-7024 - Policies are not getting deployed until server is restarted

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5627]
Issue migrated from: [https://wso2.org/jira/browse/IDENTITY-7024](https://wso2.org/jira/browse/IDENTITY-7024)

**Steps to reproduce**

- Create a role

- Create a user and assign the role

- Follow the steps given in [1] and create a SP and publish a policy with the created role.
- Then delete the SP and the policy and recreate them and try to log into the SP with a user who is not assigned to the role created.

**Expected Outcome:**
- User should not be able to authenticate

**Actual Outcome**
- User is successfully authenticated.

**Labels**
Type: Bug
Component/s: xacml

[1] -[https://docs.wso2.com/display/IS530/Configuring+Access+Control+Policy+for+a+Service+Provider](https://docs.wso2.com/display/IS530/Configuring+Access+Control+Policy+for+a+Service+Provider)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
