### ISSUE TITLE
Internal/everyone returned even for non existing users for getRoleListOfUser operation

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#5628]
**Steps to reproduce** 

1. Set the `<HideAdminServiceWSDLs>` element to **_false_** in <IS_HOME>/repository/conf/carbon.xml file.

2. Create a SoapUI project from [https://localhost:9443/services/RemoteUserStoreManagerService?wsdl](https://localhost:9443/services/RemoteUserStoreManagerService?wsdl)

3. Send a request to getRoleListOfUser operation with a non-existing user name.
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.ws.um.carbon.wso2.org">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getRoleListOfUser>
         
         <ser:userName>test@test.com</ser:userName>
      </ser:getRoleListOfUser>
   </soapenv:Body>
</soapenv:Envelope>`

4. Response
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <ns:getRoleListOfUserResponse xmlns:ns="http://service.ws.um.carbon.wso2.org" xmlns:ax2728="http://tenant.core.user.carbon.wso2.org/xsd" xmlns:ax2731="http://dao.service.ws.um.carbon.wso2.org/xsd" xmlns:ax2733="http://common.mgt.user.carbon.wso2.org/xsd" xmlns:ax2724="http://core.user.carbon.wso2.org/xsd" xmlns:ax2725="http://api.user.carbon.wso2.org/xsd">
         <ns:return>Internal/everyone</ns:return>
      </ns:getRoleListOfUserResponse>
   </soapenv:Body>
</soapenv:Envelope>`

**Tested Version** 
IS-5.8.0

**More info**
[https://wso2.org/jira/browse/IDENTITY-3859](https://wso2.org/jira/browse/IDENTITY-3859)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
