### ISSUE TITLE
"PAP.Enable" properties not working properly in WSO2IS Entitlement feature

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5631]
There is following property
PAP.Enable
This just disable the PAP policy store related PDP... but still PAP policy store can be init. It is better to fix this properly for future version.

OT Jira: https://wso2.org/jira/browse/IDENTITY-4862

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
