### ISSUE TITLE
[Doc] User Self Registration UI field name should be changed

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5632]
Issue migrated from: [https://wso2.org/jira/browse/IDENTITY-7362](https://wso2.org/jira/browse/IDENTITY-7362)

**Proposed Changes**

- The product UI field in User Self Registration Screen (Identity > Resident Identity > User Self-registration) has changed. 

- This will mandate screen changes everywhere where this screen is used. 

- https://docs.wso2.com/display/IS550/Self+Sign+Up+and+Account+Confirmation and other spaces.

**Labels**
Type: Doc Improvement
Priority: Normal
Component/s: identity-provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
