### ISSUE TITLE
User claim based atuhorization does not work for tenant users in Saas scenario

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5633]
related to this 
https://wso2.org/jira/browse/DOCUMENTATION-5000

**Comment by DMHP** [comment]
originally moved from https://wso2.org/jira/browse/IDENTITY-6910

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
