### ISSUE TITLE
Document on scope validation related extension points

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5634]
We have 3 extension points for scope validation

- OAuth2ScopeValidator

This extension point is used to engage application specific scope validation during scope issuance and scope validation when invoking token validation service. Can be registered multiple validators.

- OAuthCallbackHandler

This old extension can also be used for scope validation. Only one callback handler can be registered

- OAuth2ScopeHandler

Global callback handler for scope validation. Getting executed after `OAuthCallbackHandler`. Can register multiple handlers

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
