### ISSUE TITLE
Scope awareness in OAuth token revocation

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5635]
Moved from https://wso2.org/jira/browse/IDENTITY-5930

Currently, in IS, access tokens can be revoked for a particular client, user and scope combination if it's ACTIVE or EXPIRED. And it can be done using revokeAuthzForAppsByResoureOwner method of OAuthAdminService. When we revoking the tokens, it will revoke the consents for a particular client, user and tenant combination.
It is better to concern about the following scenarios as well.
1) Revoke access token/refresh token based on the consent (Revoke tokens with the consent "approve always")
2) Revoke access token/refresh token for a given client and a scope

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
