### ISSUE TITLE
Revoke and List user consents based on scope/ particular application/ particular user/expiration date

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5636]
Moved from: https://wso2.org/jira/browse/IDENTITY-5929

Currently, we can update the consent of a particular application for a particular user in a particular tenant using OAuthAdminService. So that if the user has selected the consent as "approve always", we can change it and the client will have to ask for the consent again.
Need also provide ways to:
1) revoke all consents given for a particular scope/ particular application/ particular user
2) get a list of user consents for a particular scope/ particular application/ particular user
3) get a list of the current OAuth consents with scope and expiration date

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
