### ISSUE TITLE
Improve DefaultClaimHandler claim handling logic

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#5637]
From JIRA : https://wso2.org/jira/browse/IDENTITY-6185

In the current implementation of the Default Claims handler,

When handling local or federated claims,

We go through all the steps such as,

1. Loading local claims
2. Loading all non empty claims of the user

even when there are no requested claims configured at the Service Provider level. When there are no request claims at SP level we return an empty map after going through all the steps which result in DB calls, UserStore class etc..

With the current logic, this takes up a significant portion of the time taken for the authentication call to commonAuth endpoint.

A possible improvement would be to check whether there are any requested claims at SP level before trying to proceed with the claim retrieval logic.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
