### ISSUE TITLE
IDENTITY-6056 [XACML]When there are more than one policy with different target attribute ids, it fails when trying to invoke a policy

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5638]
1. I created a simple policy with 'resource-id' as an attribute id using simple policy editor.
2. Then created a second policy by editing 'authn_time_and_role_based_policy_template'.
This second polcy does not contain 'resource-id' as an attribute id.
it only contains
http://wso2.org/identity/sp/sp-name and http://wso2.org/identity/identity-action/action-name as attribute ids of the target.

But when try to invoke second policy, it fails saying

```
No attribute designators defined for the category urn:oasis:names:tc:xacml:3.0:attribute-category:resource
[2017-06-05 11:44:26,801] DEBUG {org.wso2.carbon.identity.entitlement.pip.CarbonAttributeFinder} -  No attribute designators defined for the attribute urn:oasis:names:tc:xacml:1.0:resource:resource-id
[2017-06-05 11:44:26,801] DEBUG {org.wso2.balana.finder.AttributeFinder} -  Failed to resolve any values for urn:oasis:names:tc:xacml:1.0:resource:resource-id
```
it seems like PDP is evaluating all the policy targets within the tenant.
The current workaround I used is to add a custom PIP to handle this.

**Labels**
Type: Bug
Priority: Normal
Component/s: xacml
Labels: component_verified
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6056_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
