### ISSUE TITLE
IDENTITY-6164 enablePersist check for TokeMgtDAO

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5639]
Need to decide, whether we need enablePersist check for read operations in TokeMgtDAO also.

**Labels**
Type: Improvement
Priority: High
Component/s: oauth
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6164_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
