### ISSUE TITLE
IDENTITY-6167 Need to honor modifications to email-admin-config.xml file

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5640]
At the moment, we save the email-admin-config.xml in the registry during the very first server startup. After that, changes to the file are not picked up. So, users are forced to go to the registry to update the config.

This is a bit confusing since a user probably expects that the changes to the file will be honored especially since it is located under repository/conf folder.

We can do some hashing mechanism and verify whether the contents in the registry and the file matches. And, then we can update the registry accordingly.

**Labels**
Type: Improvement
Priority: Normal
Component/s: identity-mgt
Labels: component_verified high
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6167_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
