### ISSUE TITLE
IDENTITY-6183 Associations are not removed when IDP is deleted.

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5642]
There is no way to remove the associations, once IDP is deleted.

Note: federated user associations.

**Labels**
Type: Bug
Priority: High
Component/s: identity-provider, user-mgt
Labels: prioritized
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6183_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
