### ISSUE TITLE
IDENTITY-6265 Ldap search filter for base64 encoded objectGUID not working

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5644]
Currently IS can send objectGUID user attribute as a base64 encoded string, rather than sending it in canonical form. So if this value is send back to IS (as SCIM get user or searching from management console) functionality is not working.

**Labels**
Type: Bug
Priority: Normal
Component/s: user-core
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6265_

**Comment by jsonp80** [comment]
anyone know the fix for this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
