### ISSUE TITLE
IDENTITY-6272 "userName" attribute is mandatory in Users/{id} PATCH operation

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5645]
"userName" attribute is mandatory in Users/{id} PATCH operation. This is not the case according to the spec.

**Labels**
Type: Bug
Priority: Normal
Component/s: scim
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6272_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
