### ISSUE TITLE
IDENTITY-6293 Server Startup error when account.lock.handler.notification.manageInternally is not configured in the configuration file

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5646]
Server Startup error when account.lock.handler.notification.manageInternally is not configured in the configuration file.

**Labels**
Type: Bug
Priority: Normal
Component/s: identity-governance
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6293_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
