### ISSUE TITLE
IDENTITY-6303 Add Audit and Debug logs to SCIM component

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5647]
We need to have a fresh look at the SCIM operations, and make a small plan on how to add AUDIT and DEBUG logs. Then, we need to go ahead add them as necessary.

All the write operations such as user creation, modification, deletion need to have audit logs.

Following are the repos we need to checkout:

https://github.com/wso2-extensions/identity-inbound-provisioning-scim
https://github.com/wso2-extensions/identity-outbound-provisioning-scim
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2

**Labels**
Type: Task
Priority: Normal
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6303_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
