### ISSUE TITLE
IDENTITY-6314 User that belongs to disabled tenant can successfully register

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5648]
Steps to reproduce the issue.
1. Created a tenant and a tenant user from GUI.
2. Disabled the tenant from the GUI.
3. Access the IS Dashboard and registered an user under created tenant domain by providing required fields.
4. User added to the userstore successfully even that tenant domain already disabled.

For a deactivated tenant, from a web app or a rest api, can call realm service and it's possible to perform user operations.

But the authentication should be failed if the tenant is deactivated.

**Labels**
Type: Bug
Priority: Normal
Component/s: tenant-mgt, user-core
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6314_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
