### ISSUE TITLE
IDENTITY-6318 external bps is not shown for human task approvals In tenant mode

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5649]
external bps profiles are not shown for human task approvals in user portal for tenants

**Lebels**
Type: Bug
Priority: Normal
Component/s: workflows
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6318_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
