### ISSUE TITLE
IDENTITY-6329 Two scim id's created (SCIM1 & SCIM 2) when disabling SCIM2 and create user with SCIM2 endpoint

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5650]
1) Enable SCIM1 only in identity.xml (disable SCIM2)

2) Try to add a user with SCIM2 endpoint as follows
```
curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jayawardana","givenName":"vindula"},"userName":"vindula","password":"vindula","emails":[{"primary":true,"value":"vindula_home.com","type":"home"},{"value":"vindula_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users
```
3) You will get response with user id as follows
```
{"emails":[{"type":"home","value":"vindula_home.com","primary":true},{"type":"work","value":"vindula_work.com"}],"meta":{"created":"2017-08-31T18:05:10Z","location":"https://localhost:9443/wso2/scim/v2/Users/337f83f2-75a8-41f7-bbc2-82b799fe11b1","lastModified":"2017-08-31T18:05:10Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"name":{"familyName":"jayawardana","givenName":"vindula"},"id":"337f83f2-75a8-41f7-bbc2-82b799fe11b1","userName":"vindula"}
```

4) check the user id from management console (See the attachment)
The user id you got as the response (point 3) and user id in management console(point 4) are different.

5) If you want to get the user with following request then you need to give the user id you got from management console only.
curl -k -v -u admin:admin https://localhost:9443/scim2/Users/<user id you got from management console>

**Labels**
Type: Bug
Priority: Normal
Component/s: scim, scim2
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6329_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
