### ISSUE TITLE
IDENTITY-6359 error occurs while adding external bps profiles for tenants with email username

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5652]
error occurs while adding external bps profiles for tenants with email username.

**Labels**
Type: Bug
Priority: Normal
Component/s: workflows
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6359_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
