### ISSUE TITLE
IDENTITY-6362 Update Group during Outbound Provisioning with SCIM doesn't work

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5653]
When doing outbound provisioning, updating group by renaming the group name and assigning new users to the group doesn't work. Gives an error in debug level as

```
[2017-09-07 16:49:46,007] INFO

{org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - SCIM - update group operation returned with response code: 500
[2017-09-07 16:49:46,007] ERROR {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient}
- Error occurred while updating old group : PRIMARY/buny
```

**Comments**
_comment-1_
Problem : The doPostUpdateRoleName has not implemented in DefaultInboundUserProvisioningListener in carbon-identity-framework

**Labels**
Type: Bug
Priority: High
Component/s: scim
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6362_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
