### ISSUE TITLE
Multi Tenant - User Force Password Reset Issue

### ISSUE THREAD

**Issue by wijith7** [wso2/product-is#5659]
Moved from [https://wso2.org/jira/browse/IDENTITY-7364](https://wso2.org/jira/browse/IDENTITY-7364)

Where same user existing in multiple tenants, has an issue with Force Password Reset. When Force Password reset call is made on user from one tenant, the user receives proper link. But doing password reset for the same user for another tenant within 15 mins is triggering password reset from earlier tenant and user is receiving password reset link for earlier tenant even though this password reset is done from another tenant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
