### ISSUE TITLE
[Doc] Sample authenticator pointed in doc has out dated dependencies

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5662]
Issue migrated from : https://wso2.org/jira/browse/IDENTITY-7320

"Writing a Custom Federated Authenticator" [documentation](https://docs.wso2.com/display/IS580/Writing+a+Custom+Federated+Authenticator#WritingaCustomFederatedAuthenticator-CustomauthenticatorforGoogle) for IS 5.8.0 has a sample of custom authenticator for Google.
Pointing to the below SVN location : https://svn.wso2.org/repos/wso2/people/thanuja/org.wso2.carbon.identity.application.authenticator.social/

But the pom file has the below import, which does not include the version that is available in the IS5.8.0

```
<Import-Package>
        ......
        org.wso2.carbon.identity.application.authenticator.oidc; version="[5.0.7,5.1.0)"
</Import-Package>
```
org.wso2.carbon.identity.application.authenticator.oidc version available in the IS5.8.0 is 5.1.21. Therefore, changing the above entry as below fixes the OSGI not activating issue.

`org.wso2.carbon.identity.application.authenticator.oidc; version="5.1.21"`
This should be fixed in the SVN repo or the documentation should point to a sample with updated versions.

All the docs from 5.3-5.8 should be changed according to particular `org.wso2.carbon.identity.application.authenticator.oidc` versions

**Labels**
Type: Bug
Priority: Normal
Affects Version/s: 5.3 to 5.8

**Comment by dewniMW** [comment]
https://github.com/wso2/product-is/issues/11312#issuecomment-914151337
