### ISSUE TITLE
[DOC] SCIM2 filtering with multiple attributes. 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5663]
SCIM filtering is supported for both single attribute and multi attribute cases. 
A single attribute filter request with no domain param returns all the users from all the user stores. 
But Multi attribute filtering does not support filtering across all user stores when the domain is not specified. If the domain is not specified, results will be only from the PRIMARY user store.

The documentation for [SCIM 2.0 REST APIs](https://docs.wso2.com/display/IS580/Using+the+SCIM+2.0+REST+APIs#UsingtheSCIM2.0RESTAPIs-GET/GetUsers(UserListing/Filtering)) does not mention this specifically. There is an [OT Jira](https://wso2.org/jira/browse/IDENTITY-7383) regarding this as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
