### ISSUE TITLE
[Feature Request] Move session data persistence in to NON-SQL storage

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#5667]
PROBLEM
-------------------
As of now, the session persistence will be using the IDN_AUTH_SESSION_STORE table from the identity database. 
Hence the table will grow really fast when it comes to high concurrency logins and the data size stored in the particular table.

In order to manage this, there are introduced the session data purging task to be executed from the Identity server [1] and the stored procedure to be run from the database itself. 

However, it has one downside were the disk space will continuously grow even though the purging activities being carried.
This is due to the nature of most of the databases where the database does not reclaim the disk space on a delete operation, hence it does not perform a permanent delete of such data from the disk. 
Therefore in order to reclaim this disk space, a DBA should perform a database maintenance activity such as to optimise table, vacuum table etc. However, this could not be run often as these activities would require a downtime.

POSSIBLE SOLUTIONS
----------------------------------
1 Move the session data persistence into NON-SQL storage such as Redis.
2. Verify the possibility of using table partitioning for the IDN_AUTH_SESSION_STORE table. Hence the partition's data which are eligible to delete can be dropped and claim the disk space immediately rather doing a delete operation which is more expensive.

[1] https://docs.wso2.com/display/IS580/Authentication+Session+Persistence

**Comment by dmxunlimit** [comment]
Related Issue: https://github.com/wso2/product-is/issues/4355

**Comment by LahiruLS** [comment]
Ref: https://github.com/wso2/product-is/issues/10453

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
