### ISSUE TITLE
IDENTITY-6539 WSO2 Performance Tuning Recommendation for Windows

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5670]
Hi,

I have noticed that this URL only provides the performance tuning parameters for Linux environment: https://docs.wso2.com/display/IS580/Performance+Tuning+Recommendations

Could you please point me to the WSO2 windows tuning recommendations?

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6539

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
