### ISSUE TITLE
IDENTITY-6565 Initial pending approvals are not visible for a newly created user with approval permission

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5672]
Requirement
I have defined a workflow to add users to our system. Workflow approval process is based on multi-role approval process. For example: If I want to add a new user to the system, that should be approved by a person in 'Manager' role and then a person in 'Senior Manager' Role.

If I created a user for the 'Manager' role, the person should be able to view all the pending approvals including the pending approvals created prior to joining

Purpose
If manager leaves the company, new manager should be able to view the pending approvals and continue the workflow

Environment:
IS 5.3.0 wum updated pack - 02/10/2017
JDK - 1.8
OS - ubuntu 15.10

**Comment by mefarazath** [comment]
Were you able to see the approvals for an admin user?

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6565

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
