### ISSUE TITLE
Separate the userstore operations in to different layers.

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5673]
Currently no there is no DAO layer seperation, instead all the DAO methods have been added to the service layer itself. When achieving the requirement of allowing userstores to be persisted in different repositories as database, file etc. the seperation is needed.

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-identity-framework/pull/2243

**Comment by DMHP** [comment]
Please add the content to docs: https://docs.google.com/document/d/1ITziujnC_DupPq9D_aLugXqqknc3fReLTpky52IssyQ/edit

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
