### ISSUE TITLE
Existing Service providers doesn't get update when deploying a jar of an authenticator which was not available by default

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#5674]
Moved from https://wso2.org/jira/browse/IDENTITY-6691

There're several federated authenticators (ex - Wordpress) which are not available by default when configuring an IDP [1]. Once after a user deploy respective jar file in [IS_HOME]/repository/components/dropins folder and it will have a specific authenticator inside federated authenticators in IDP only when creating a new IDP but not when updating an existing IDP.

[1] https://wso2.org/jira/browse/DOCUMENTATION-5375

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
