### ISSUE TITLE
STS client doesn't not return Multivalued attributes based on "MultiAttributeSeparator" property in the user store configuration

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#5675]
Moved from https://wso2.org/jira/browse/IDENTITY-6681

sts-client uses AttributeCallbackHandler for token generation. Here mulitattibute-separator is hard-coded to ",,," , only if requested claim comes with MultiAttributeSeparator it get overridden. [1]

Since this is setup with resident IDP, unable to configure an advanced claim "MultiAttributeSeparator" to be default to ",".

Even after defining a cliam "MultiAttributeSeparator" and it is requested in the request, attribute separation only happens for SAML 1.1, not for 2.0. However, when invoking from travelocity client attributes are properly sent to the client with based on "MultiAttributeSeparator" property of the user store. hence, two clients behave differently.

We should consider "MultiAttributeSeparator" property of the user store configuration also here in this flow and should be applied to SAML 2.0 as well.

[1] https://github.com/wso2-extensions/identity-inbound-auth-openid/blob/v5.1.1/components/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/AttributeCallbackHandler.java#L346
[2] https://github.com/wso2-extensions/identity-inbound-auth-openid/blob/v5.1.1/components/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/AttributeCallbackHandler.java#L359

Thanks!

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
