### ISSUE TITLE
IDENTITY-6567 COMPLETED task are bind to the person who approves it

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5676]
## Steps to recreate the issue

1. Create a workflow for adding user with bps embedded engine (Approval process contains two roles, 'Manager' [PersonA] and 'SeniorManager' [PersonB] )
2. Create users for approval process
3. Add another user for 'Manager' role [PersonC]
4. Create few more users for approval process
5. Then approve a newly created user from a 'PersonC'

## Observations

1. Task is shown as COMPLETED for 'PersonC'
2. COMPLETED task is not visible to the 'PersonA'

![image](https://user-images.githubusercontent.com/29881881/59347381-1fa06f80-8d32-11e9-8c5f-0f31c1961597.png)

![image](https://user-images.githubusercontent.com/29881881/59347399-2a5b0480-8d32-11e9-88a9-f798a1453eae.png)

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6568

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
