### ISSUE TITLE
"Pending Approvals" user dashboard gadget functionality broken

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5678]
* Engage a workflow for user add operation following https://docs.wso2.com/display/IS580/Engaging+a+Workflow+in+an+Operation
* Login to the user dashboard as an admin user and open the "Pending Approvals" gadget. It seems doesn't show any approvals. 
* In the JS console, we can see that a request sent to the backend errors with a 400.

**Comment by mefarazath** [comment]
Once we verify the above is working we have another reported issue (https://wso2.org/jira/browse/IDENTITY-5967)

**Pending Approval BPEL Profile Engine drop down not functioning properly**

- Create a new BPEL Profile engine named WSO2BPS1
- Create workflow.
- Log in to user portal to approve request as in [1]
- Go to Pending Approvals gadget.
- Try to select 'embedded_bps' from the drop down of 'BPEL Profile Engine'
- But it does not get selected. Instead the other profile engine(WSO2BPS1) get selected.


[1]https://docs.wso2.com/display/IS530/Managing+Human+Tasks

**Comment by mefarazath** [comment]
Seems like the issue is not present in IS 5.7.0-GA pack.

**Comment by ayshsandu** [comment]
> * WSO2BPS1



> Once we verify the above is working we have another reported issue (https://wso2.org/jira/browse/IDENTITY-5967)
> 
> **Pending Approval BPEL Profile Engine drop down not functioning properly**
> 
> * Create a new BPEL Profile engine named WSO2BPS1
> * Create workflow.
> * Log in to user portal to approve request as in [1]
> * Go to Pending Approvals gadget.
> * Try to select 'embedded_bps' from the drop down of 'BPEL Profile Engine'
> * But it does not get selected. Instead the other profile engine(WSO2BPS1) get selected.
> 
> [1]https://docs.wso2.com/display/IS530/Managing+Human+Tasks

In the above case, if you have defined server URL of WSO2BPS1 to be same as current server instance(embedded_bps) then the behaviour is expected. Approvals are listed for the server since both are pointing to the same server result would be the same.

When you point external server URL for secondary BPEL Profile Engines, the gadget works as expected.

**Comment by LahiruLS** [comment]
Hi, I observed the same behaviour in the IS as KM 5.7.0 latest WUM updates pack and I was able to fix it by changing as the PR? Should we fix this?
