### ISSUE TITLE
IDENTITY-6568 No option to view the applied application conditions of an existing workflow associations

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5679]
Currently, when a workflow engagement is created by adding workflow engagement conditions (ex: By applying application filtering condition) it is not possible to view the applied conditions

![image](https://user-images.githubusercontent.com/29881881/59347632-c5ec7500-8d32-11e9-8c5b-7865e9f3b892.png)

It would be better to provide an option to view the workflow application filtering condition, as it helps for any other user who has permission to identify what are the workflow conditions already applied and create new conditions based on prior knowledge. (People might forgot the application condition applied, and when they want to verify the condition its not visible)

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6568

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
