### ISSUE TITLE
Additonal tasks created when assigning a role for a workflow available to update user roles

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#5680]
Moved from https://wso2.org/jira/browse/IDENTITY-6571

**Steps to recreate the issue**
1. Create a workflow to change the role of the user (Update_Roles_Of_User)
2. Select an existing user and go to 'Assign Role' view
3. Then add an existing role and click 'Update'
4. Then finish the process by selecting the 'Finish' button

**Observations**
Two tasks will get created for the approval process. (If user click both 'update' and 'finish' buttons two tasks will get created)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
