### ISSUE TITLE
Need to implement proper rollback support for Identity-Mgt features

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5681]
**Description**
Currently when there are failures in notification sending modules in Identity-Mgt component, whatever state that has been persisted until then is not rolled back. This causes multiple issues. This is not easily fixable because the notification sending happens asynchronously. E.g. if the user is created creation failed due to email sending the user account is not deleted. Therefore the same user cannot be created again. Since this can occur during self-registration the end user won't have any clue of what happened but he won't be able to register with the same name until user account is manually deleted.

**Type**
Sub-Task

**Priority**
Normal

**Component/s**
identity-mgt

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Task, Component/Identity Mgt, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-3415

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
