### ISSUE TITLE
User added to the workflow not visible when searched in the primary userstore

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#5682]
Moved from https://wso2.org/jira/browse/IDENTITY-6597

**Steps to recreate the issue**
1. BPS server is connected as workflow engine and an AD is connected 
2. Create a workflow with multiple role approval process for the users added in primary user store (User created in primary user store for an existing primary userstore role name)
3. Create a user for the primary user store
4. Verify the user listed for the primary user store

**Observations**
User added to the primary userstore (and waiting for the approval) do not get listed for the primary user store. 

To find the user, should be searched with 'All_User_Store_Domain' category as below. But when it comes a scenario where thousands of users exists, it would be hard to identify the users waiting for approval from the user view

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
