### ISSUE TITLE
Improve Integration test cases for OAuth2 token introspection

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5685]
Cover all possible cases including following,
A valid access\refresh token should get the response
{ "active" : true }
A revoked access\refresh token should get the response
{ "active" : false }
A expired access\refresh token should get the response
{ "active" : false }
Invalid credentials for introspection endpoint return 401
A Introspection request have empty token should get error response.

OT Jira: https://wso2.org/jira/browse/IDENTITY-4681

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
