### ISSUE TITLE
TENANT_ID in IDN_AUTH_SESSION_STORE table is not filled properly

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5687]
moved from: https://wso2.org/jira/browse/IDENTITY-5935

Some rows in IDN_AUTH_SESSION_STORE table has -1 for TENANT_ID column.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
