### ISSUE TITLE
Need to support OIDC request_uri parameter

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5688]
Moved from: https://wso2.org/jira/browse/IDENTITY-6726

In this case the url will be a pre-registered url by the RP for use at the OP. The reference which is pointed from the url will consist the relevant jwt. The rationale behind returning claims will be same as the above in the request parameter. We need to support this optional parameter

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
