### ISSUE TITLE
Endpoint to extend User session

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5693]
As of now, we don't have a way to extend a user's session without going for workarounds like passive authentication requests sent from App.

From the perspective of security providing an endpoint of this kind has some benefits. For example, with the current implementation since we don't have a way to extend a authenticated user session explicitly, user admin will most probably have a large session timeout value. This causes sessions to be unnecessarily active for idle users.

If we have an endpoint to extend the session we could configure a minimum required value for session timeout value. For active users, we can use the endpoint to extend the session as necessary while for inactive users the session will timeout after this minimum value.

Moved from https://wso2.org/jira/browse/IDENTITY-5933

**Comment by lraveli** [comment]
Is it resolved on 5.5.0? I can't find any documentation about it.

**Comment by rksk** [comment]
The same is reported in https://github.com/wso2/product-is/issues/10560 and solved.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
