### ISSUE TITLE
WSO2 IS 5.3 - I can not create new IDPs on Solaris.

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5694]
I have been testing IS on solaris for several weeks with jdk 1.8 144. Everything works correctly.
However, when I try to register a new IDP from the console the browser accesses to the url:
https://myHost-fqdn:9443/carbon/idpmgt/idp-mgt-add-finish-ajaxprocessor.jsp?X-CSRF-Token=QHG4-GFEI-78V8-LKLH-5690-QYI8-YO7Y- IT3Y
and it gives the error "Non secure connection".
I added the exception to the browser to accept the self-signed carbon certificate.
I tried a clean installation where I only changed carbon.xml to adjust the host name.
I have tried the same in linux and it works correctly.

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6905

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
