### ISSUE TITLE
Multi step configuration in IDP Federation doesn't follow the correct validating process as specified in the multi step configuration

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5695]
Steps to recreate the issue
1. Add travelocity as the service provider using SAML SSO as the inbound authentication in the Identity server
2. Add google as the identity provider using OAuth 2/Openid connect as the federated authentication
3. Go to Service provider local and outbound configuration > Advanced configuration > Configure multi step authentication as shown in the attached screenshot [1]
4. Navigate to http://localhost:8080/traveocity.com
5. click on SAML redirect binding
6. Will navigate to google login page
7. Enter login credentials
8. Navigate to google account selecting page 
9. Just click on the relevant google account (User login page is not prompted)
10. Will direct to travelocity home page

Here even though I have enabled multi step configuration for Google it doesnt ask for the google credentials 2 times if i select the same google account. As it has previous session data it will fetch session data and will log to the travelocity home page. As I have enabled multi step configuration is it correct to log from previous session data without validating the user 2 times.
![image](https://user-images.githubusercontent.com/12690906/59350508-deac5900-8d39-11e9-8972-00f78d863ff9.png)

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6908

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
