### ISSUE TITLE
Change the method Signature of initializeRegistry in IdentityTenantUtil.java class in carbon-identity-framework

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5696]
Moved from:https://wso2.org/jira/browse/IDENTITY-5904

Since tenant domain can be taken from tenantId,
change the method public static void initializeRegistry(int tenantId, String tenantDomain) to public static void initializeRegistry(int tenantId) in IdentityTenantUtil.java in the repository carbon-identity-framework

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
