### ISSUE TITLE
Resident IDP's home realm identifier does not support multi-values

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5697]
In Resident IPD's basic configuration, the tool tip for home realm identifier specifies that it can be a comma-separated multi valued list [1]. This is not supported in IS

![image](https://user-images.githubusercontent.com/12690906/59350747-832e9b00-8d3a-11e9-86ef-e29c68b22dbc.png)

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6926

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
