### ISSUE TITLE
[DOC] Missing configurations when configuring newer versions of Email OTP Authenticator with Identity Server

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5699]
Following the configuration steps available in the Email OTP doc [1] or [2] result in a NullPointerException during runtime.

ERROR 
`org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework 
java.lang.NullPointerException
at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.checkEmailOTPBehaviour(EmailOTPAuthenticator.java:329)`
The latest versions of Email OTP Authenticator requires following additional properties in application-authentication.xml file. We need to add these missing steps to WSO2 documentation as well.

1. When configure  WSO2 IS as the email OTP provider.

` <AuthenticatorConfig name="EmailOTP" enabled="true">
      <Parameter name="EMAILOTPAuthenticationEndpointURL">https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp</Parameter>
      <Parameter name="EmailOTPAuthenticationEndpointErrorPage">https://localhost:9443/emailotpauthenticationendpoint/emailotpError.jsp</Parameter>
      <Parameter name="EmailAddressRequestPage">https://localhost:9443/emailotpauthenticationendpoint/emailAddress.jsp</Parameter>
      <Parameter name="usecase">association</Parameter>
      <Parameter name="useEventHandlerBasedEmailSender">true</Parameter>
      <Parameter name="secondaryUserstore">primary</Parameter>
      <Parameter name="EMAILOTPMandatory">false</Parameter>
      <Parameter name="sendOTPToFederatedEmailAttribute">false</Parameter>
      <Parameter name="federatedEmailAttributeKey">email</Parameter>
      <Parameter name="EmailOTPEnableByUserClaim">true</Parameter>
      <Parameter name="useEventHandlerBasedEmailSender">true</Parameter>
      <Parameter name="CaptureAndUpdateEmailAddress">true</Parameter>
      <Parameter name="showEmailAddressInUI">true</Parameter>
</AuthenticatorConfig>`

2. When configuring Gmail as the email OTP provider need to add the following properties under the AuthenticatorConfig for Gmail

`<Parameter name="usecase">association</Parameter>
<Parameter name="useEventHandlerBasedEmailSender">true</Parameter>`

[1] https://docs.wso2.com/display/IS570/Configuring+Email+OTP
[2] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/docs/html-support.md

**Comment by YvonneW** [comment]
The content is updated.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
