### ISSUE TITLE
Generating SCIM metadata for hybrid roles irrespective of the user store configuration

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#5702]
**IS Version:** 5.6.0

Hybrid roles (eg: Application, Internal) are independent of the user stores. Hence SCIM metadata generation for those roles should be independent of the primary user store configuration (SCIM enabled or SCIM disabled). Therefore when creating hybrid roles, SCIM metadata should be generated always.

**Comment by emswbandara** [comment]
@sachiniWettasinghe can you please create an issue to track the behavioral changes in the docs?
