### ISSUE TITLE
Allow configuring provision handler to combine user roles

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5704]
Moved from: https://wso2.org/jira/browse/IDENTITY-5576

When federated authentication is configured and syncing user roles from an external identity provider, locally configured user roles are removed and replaced with roles provided from an external identity provider.

There can be use cases where instead of removing locally configured roles, retaining both locally configured roles for a user and roles configured in the external identity provider.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
