### ISSUE TITLE
[XACML 3.0] Need to have a capability to retrieve values from a request context specified in the policy using <AttributeSelector> and <AttributeDesignator> properties within <ObligationExpressions>

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5705]
Moved from: https://wso2.org/jira/browse/IDENTITY-5809

Currently, in IS we can get the attribute value which is hardcoded inside the policy. But need to have a capability to retrieve values from a request context specified in the policy using <AttributeSelector> and <AttributeDesignator> properties.

- The <AttributeSelector> element produces a bag of unnamed and uncategorized attribute values. The values shall be constructed from the node(s) selected by applying the XPath expression given by the element's Path attribute to the XML content indicated by the element's Category attribute. (section 5.30)

- The <AttributeDesignator> element retrieves a bag of values for a named attribute from the request context. (section 5.29)

Example ObligationExpression in a policy. (Refer http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html - section 4.2.4.3).

```
<ObligationExpressions>
	<ObligationExpression ObligationId="urn:oasis:names:tc:xacml:example:obligation:email" FulfillOn="Permit">
		<AttributeAssignmentExpression AttributeId="urn:oasis:names:tc:xacml:3.0:example:attribute:mailto">
			<AttributeSelector MustBePresent="true" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" Path="md:record/md:patient/md:patientContact/md:email" DataType="http://www.w3.org/2001/XMLSchema#string"/>        
		</AttributeAssignmentExpression>
       		<AttributeAssignmentExpression AttributeId="urn:oasis:names:tc:xacml:3.0:example:attribute:text">
           		<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">Your medical record has been accessed by:    </AttributeValue>
        	</AttributeAssignmentExpression> 
		<AttributeAssignmentExpression AttributeId="urn:oasis:names:tc:xacml:3.0:example:attribute:text">
            		<AttributeDesignator MustBePresent="false" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" AttributeId="urn:oasis:names:tc:xacml:1.0:subject:subject-id" DataType="http://www.w3.org/2001/XMLSchema#string"/>
       		</AttributeAssignmentExpression>
	</ObligationExpression>
</ObligationExpressions>
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
