### ISSUE TITLE
IS : Custom claims lost when updating user profile

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5706]
Moved from: https://wso2.org/jira/browse/IDENTITY-7335

Hi WSO2 team,

WSO2 Identity Server offers some extension points for instance ability to add custom claims.
This is normally donc by writing a custom claim handler as described in one wso2 post :
http://pushpalankajaya.blogspot.com/2014/07/adding-custom-claims-to-saml-response.html

When using WSO2 OAuth2.0 Playground sample and OAuth2.0 Authorization code grant type, custom claim handler is invoked normally when resource owner is authenticated.
Then at the end of process you get an access token enabling to retrieve, for instance, user info with customs claim ("computed before when custom claim handler is invoked).

If you update some information of user profile and request again user info from user info endpoint with access_token, all the +custom + claims are lost in provided response.

Actually, when you update user profile, information that were previously cached are emptied so when user info endpoint is called with access_token, user claims (and their corresponding values) are computed from userstore perspective only so that why custom claims are lost.

Would it be possible in that scenario of retrieving claims from userstore that custom claim handler would be also called to ensure that customs claims are available in answer?

Regards,

Franck

**Comment by omindu** [comment]
From @mefarazath 

> We store claims against token. When user claims update we clear the claims stored against the token.
> Thereafter if u do userinfo calls then claims are retrieved from the user store..
> So custom claims will be lost.
> Best possible solution is to revoke the token if user claims are updated.
> 
> Anyways that too has practical issues. Consistency vs accuracy. If we don't clear the stored claims we might end up with stale values.
> 
> Improve the claim handling is also an option. So that even when we retrieve from the userstore custom claims can be injected.
> Basically we ask for user claims from an API in any flow (framework or not) it returns the same claims.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
