### ISSUE TITLE
SCIM groups created for a secondary user store does not get deleted when deleting the user store

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5712]
1. Add a read write secondary user store.
2. Create a SCIM group in the secondary user store via SCIM API.
`curl -v -k --user admin:admin --data '{"displayName": "EXTERNAL/engineer"}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Groups`

3. Delete the user store
4. Retrieve groups from SCIM
`curl -v -k --user admin:admin https://localhost:9443/wso2/scim/Groups
`
5. The group created for the secondary user store is still available. But that cannot be deleted as the user store is not found. 
`{"Errors":[{"code":"500","description":"Cannot delete group through SCIM. SCIM is not enabled for user store EXTERNAL"}]}`

Expected behavior:
It's expected that while the user store is being deleted all data related to that user store to be cleared as well. But in this case, some stale data will remain even the user store is not available.

Moved from https://wso2.org/jira/browse/IDENTITY-5832

**Comment by mefarazath** [comment]
This issue is reproducible on IS 5.8.0 as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
