### ISSUE TITLE
Improve SAML error response handling.

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5714]
Moved from https://wso2.org/jira/browse/IDENTITY-4813

SAML error response handling can be improved in the product. We should POST the error response to the ACS whenever possible and sign the error response, if SP is configured to sign the response even if response signing is not mandatory. Ideally we should get completely avoid samlsso_notification.jsp

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
