### ISSUE TITLE
Dependency on HttpSession should be removed in Passive STS authentication flow

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5715]
Moved from https://wso2.org/jira/browse/IDENTITY-4784

Passive STS component uses HttpSession to store relying parties participated in the user session in order to perform SLO. 
Once the HttpSession timeouts session participants will be missing even if authenticated session remains.
HttpSession dependency is not needed here rather a separate cookie can be used to track participants and they should be persisted using some other mechanism.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
