### ISSUE TITLE
IS - File based SP/IDP configurations are incomplete

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#5716]
Moved from https://wso2.org/jira/browse/IDENTITY-4758

The documentation in [1] does not give a detail description about the configuration.

Ex: There is no/limited details about configuring the following elements. Others are also not in a descriptive manner and hence it is difficult to identify the usage of each property/element.

    ```<ProvisioningConnectorConfigs>
    </ProvisioningConnectorConfigs>
    <DefaultProvisioningConnectorConfig></DefaultProvisioningConnectorConfig>
    <ClaimConfig></ClaimConfig>
    <Certificate></Certificate>
    <PermissionAndRoleConfig></PermissionAndRoleConfig>
    <JustInTimeProvisioningConfig></JustInTimeProvisioningConfig>```


[1] https://docs.wso2.com/display/IS510/Configuring+a+SP+and+IdP+Using+Configuration+Files

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
