### ISSUE TITLE
Support SCIM for existing users

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5719]
**Description**
WSO2 Identity Server does not support to plug a read-only user store and to retrieve users in that user store over SCIM.
Moreover, even a read-write user store is plugged the underlying immutable attributes cannot be mapped for scim claims like scim id, created date, modified date, etc. Specifically, this becomes useful when an AD is plugged and the immutable attributes of AD like objectGUID, whenCreated, whenModified needs to mapped with above claims.

The main cause for this seems to be that the ReadOnly attribute of a claim is not honoured. Thus, trying to write the value to the user store fails. This seems to be a bug and need to be fixed. Once this is fixed WSO2 Identity Server should be able to support SCIM for existing users if the SCIM meta claims are mapped properly.

**Type**
Improvement

**Priority**
High

**Component/s**
SCIM

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/SCIM, Severity/Major, Complexity/Medium, Priority/High

Moved from https://wso2.org/jira/browse/IDENTITY-6932

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
