### ISSUE TITLE
Oauth certificate method from x5t to x5c

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5720]
Moved from: https://wso2.org/jira/browse/IDENTITY-7345

We have configured Oauth2.0 for authentication and authorization with one Microsoft system.
As checked currently Microsoft system only accepts x5c fields. Now wso2 identity server 5.4.1 is sending x5t details. Please let me know how can we add or send x5c via wso2 IS.

(Please) refer the JIRA for issue artifacts.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
