### ISSUE TITLE
Management console shows as users stores added successfully even though the user store configurations are wrong.

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5721]
**Steps to reproduce**
1. Login to the management console of Identity server
2. Navigate to the Main Tab
3. Select Add under User stores
4. Select org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager from the class
5. Add configurations as given in the screenshot

Here even though one wrong input is given ( input given for user search base is not correct) for the user store configurations management console shows that the data store is added successfully but the command prompt shows an exception.

![config](https://user-images.githubusercontent.com/12439288/59399595-3686a680-8db2-11e9-80de-5e825369909b.png)

![config2](https://user-images.githubusercontent.com/12439288/59399596-3686a680-8db2-11e9-8c04-bab3f17f4eb9.png)

![exception](https://user-images.githubusercontent.com/12439288/59399597-371f3d00-8db2-11e9-93c7-812b59b5089a.png)

**Type**
Bug

**Priority**
Normal

**Affected version**
5.8.0

**Component/s**
user-store

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Bug, Component/User Mgt, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-6627

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
