### ISSUE TITLE
SSO logout from all session when user tries to login to an application with an invalid scope

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5722]
Usecase
------------
User A ----> login to the APP 1 with a valid scope (commonauth cookie and opbs cookie generated) ----> Logging successful.
User A ----> try to login to APP 2 with an invalid scope (only commonauth cookie will be generated) ----> Loggin unsuccessful.
User A -----> should log out from all the sessions using SSO log out.
User B -----> should be able to login to the APP2 using the same browser session.

Summary
-----------------
Since User A has failed to login to the APP 2, User A should be log out from all the sessions using SSO log out and then User A should be able to login to the APP 2 using a different account using the same browser session.

Requirement
-----------------
SSO logout for all sessions should be available even when the particular user tries to log in to an application with an invalid scope.

**Comment by DMHP** [comment]
originally reported in https://wso2.org/jira/browse/IDENTITY-7031

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
