### ISSUE TITLE
OIDCSessionDataCache should use a persistence store to store data

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5724]
OIDCSessionDataCache does not use a persistence store to store data. So there can be instances where data can be evicted from cache and cache miss can occur.

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6968

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
