### ISSUE TITLE
Centralise the session participants in Identity Framework

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5725]
In the current implementation, we can get session participants from the inbound authenticators' side by using session identifiers(SAMLSSOTokenID, OPBSTokenId). But there is no way to handle the session participants from the Identity framework side. Since this problem, when a user admin does a force logout using Identity Server dashboard, Single Logout cannot be done.

In order to handle that we have to have a mapping between Common Auth Id and authentication protocol specific session identifiers(SAMLSSOTokenID, OPBSTokenID).

If we have a mapping like this: when an admin does a force logout then inbound authenticators able to handle logout for their own session participants. So when the log out happens, an event will be initiated and sent to all inbound logout listeners in inbound authentication components. In that event, CommonAuthId will be sent as a property. So log out listeners will get the event and handle it. Listeners can get own session identifier from the CommonAuthId and send logout request to all the participants.

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6949

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
