### ISSUE TITLE
400 text : Bad Request on user provisioning to salesforce

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5728]
Moved from https://wso2.org/jira/browse/IDENTITY-7237

1. Add an IdP with salesforce provisioning enabled. [2]
2. Enable outbound provisioning in resident service provider and select above created IdP as the provisioning connector. 
3. Add user using UI - Do not select the role. just click finish

User is added to local user store without any issue. But it's not provisioned to salesforce.
Error: 
recieved response status code :400 text : Bad Request

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
