### ISSUE TITLE
Identity Server should able to handle Single Logout Requests recive from federated IdPs

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5729]
Scenario is as follows,

A service provider use WSO2 IS as a mediator to authenticate from a Federated Identity Provider.

Ex: SP <-> WSO2 IS <-> Google

If Federated IdP(Ex: Google) initiated a logout request to the IS, it should able to process and send back a valid logout response to the Federated IdP.

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6929

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
