### ISSUE TITLE
JIT provision users to cloud service providers is not working as expected

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#5731]
Moved from https://wso2.org/jira/browse/IDENTITY-7241

### Steps to reproduce

1. Introduce salesforce as a service provider (salesforce-sp) to the WSO2 Identity Server
2. Introduce salesforce as a provisioning identity provider (salesforce-idp) to the WSO2 Identity Server, and configure the Salesforce provisioning connector.
3. Introduce the Facebook as an identity provider to the WSO2 Identity Server running and enable JIT provisioning.
4. Under the salesforce-sp service provider configuration, under local and outbound authentication configuration, select facebook as a federated identity provider. This means, a user who wants to login salesforce-sp, will be redirected to the Facebook identity provider for authentication.
5. Under the salesforce-sp service provider configuration, under outbound provisioning configuration, select salesforce-idp as a provisioning identity provider.

Facebook is provision users to wso2 IS(Jit provisioning works fine), but not provisioning to SF.
But if you manually trigger using SCIM user will provision to SF
```
curl -v -k --header "Content-Type:application/json" --user emailk@gmail.com:dakshika --data '{"schemas": ["urn:scim:schemas:core:1.0"],"userName":"random@wso2.com","password":"test25","name":

{"familyName":"Gnaniah"}
,"emails": ["random@wso2.com"],"entitlements": [

{"value":"00e90000011aV2o","display":"ChatterFreeUser"}
]}' https://localhost:9443/wso2/scim/Users
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
