### ISSUE TITLE
IDENTITY-7326 Erro acess Dashboard aplication - BPS Task - Oracle

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5732]
When you access the Dashboard panel, in the User Approval Workflow item, with other databases, it works perfectly. However with Oracle v12c the same error is presented below.

This error occurs after running the stream the second time.

Log:
...
TID: [-1234] [] [2018-02-16 16:45:13,289] ERROR

{org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl}
- <openjpa-2.2.0-wso2v1-r128166:129108 fatal store error> org.apache.openjpa.persistence.OptimisticLockException: Unable to obtain an object lock on "null".
FailedObject: SELECT DISTINCT t FROM org.wso2.carbon.humantask.core.dao.jpa.openjpa.model.Task t JOIN t.humanRoles hr JOIN hr.orgEntities oe WHERE oe.name = :name AND hr.type = :roleType AND t.tenantId = :tenantId AND t.type = :taskType AND t.status IN :taskStatuses ORDER BY t.createdOn DESC [java.lang.String] 
FailedObject: SELECT DISTINCT t FROM org.wso2.carbon.humantask.core.dao.jpa.openjpa.model.Task t JOIN t.humanRoles hr JOIN hr.orgEntities oe WHERE oe.name = :name AND hr.type = :roleType AND t.tenantId = :tenantId AND t.type = :taskType AND t.status IN :taskStatuses ORDER BY t.createdOn DESC [java.lang.String]

![image](https://user-images.githubusercontent.com/29881881/59402986-66d44200-8dbe-11e9-83ef-197881b6793f.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
