### ISSUE TITLE
IDENTITY-6666 Approval requests not listed when a workflow approval is assigned to a user with email as a username

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5733]
Steps to recreate the issue
1.Create a workflow definition with email users
![image](https://user-images.githubusercontent.com/29881881/59403036-a1d67580-8dbe-11e9-91a5-0600f6febc4e.png)

2. Create a workflow association with ADD_USER operation (ex: for all requests)
3. Create a user

Observations
1. User assigned to the workflow (workflow icon is visible with the username from the management console)
2. Approval Request did not appear for the defined user (ex: hr@wso2.com)

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6666

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
