### ISSUE TITLE
IDENTITY-6653 Role did not considered for the workflow when workflow association is created for user store domain with lowercase

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5734]
Steps to recreate the issue
1. Create a workflow to approve the new role created in the system
2. Create a workflow association to filter user roles in the primary user store ('User Store' -> Primary)
![image](https://user-images.githubusercontent.com/29881881/59403069-cc283300-8dbe-11e9-863c-f852e95e57db.png)
3. Add a role to the primary user store

Observations
Created role did not assign to the workflow (directly added to the system)

Note - This will pick only when we define the user store with caps locks (ex: 'User Store' -> 'PRIMARY')
![image](https://user-images.githubusercontent.com/29881881/59403077-d9452200-8dbe-11e9-97ba-6fd54248fe62.png)

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6653

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
