### ISSUE TITLE
IDENTITY-6646 Roles are not filtered when Add Role operations workflow association applied based on a defined permission level

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5735]
Steps to recreate the issue
1. Create a workflow
![image](https://user-images.githubusercontent.com/29881881/59403113-00035880-8dbf-11e9-9930-be51e7346821.png)
2. Create a workflow association as below (requirement is to define a workflow if permission set assigned to the workflow contains 'login' permission)
![image](https://user-images.githubusercontent.com/29881881/59403120-0a255700-8dbf-11e9-84c2-d937a1671b9a.png)
3. Create a role with login permission

Observations
The above-created role will not be considered for the workflow, it will be added to the system ignoring the workflow.

If we add the permission as '/permission/admin/login->ui.execute' it will be applied to the workflow. But for an external user, it is difficult to find how they need to provide the permission level to filter

**Comment by madurangasiriwardena** [comment]
Moved from https://wso2.org/jira/browse/IDENTITY-6646

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
