### ISSUE TITLE
OpenID Connect Parameter "display=popup" is not supported

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5737]
Moved from: https://wso2.org/jira/browse/IDENTITY-2831

According to OpenID Connect Specification 
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

the request parameter "display=popup" is not supported by WSO2 IS.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
