### ISSUE TITLE
Improvements to SHARED Identity Providers

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#5738]
Moved from: https://wso2.org/jira/browse/IDENTITY-3012

In IS 5.0.0, Identity Providers added through file system are available for any tenant. However, due to the limitation that they are not visible in Service Provider UI to associate, they effectively become associable to file system based service providers only. Later the capability to add Shared Identity Providers was added as a patch to IS 5.0.0, by prefixing "SHARED_" to the IdP file name. These Shared IdPs become visible in service provider UI as well for all tenants.

Things to discuss and improve:
1. Non-shared IdPs to be registered through file system for any tenant. This is to make deployment easier.
2. Super tenant should be able to register Shared Identity Providers from management console UI.
3. Need to discuss and decide if tenants should be able to register Shared Identity Providers through file system.
4. Need to discuss and decide if tenants should be able to register Shared Identity Providers from management console UI.
5. Need to see how each of these various combinations effect the user associating his social identifier in dashboard.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
