### ISSUE TITLE
UserAdmin Service getAllRolesNames API returns invalid role

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5739]
Moved from https://wso2.org/jira/browse/IDENTITY-5908

Reproduced in 5.8.0

**getAllRolesNames** API of **UserAdmin** service returns an additional invalid role as below,

```
         <ns:return xsi:type="ax2764:FlaggedName" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <ax2764:dn xsi:nil="true"/>
            <ax2764:domainName xsi:nil="true"/>
            <ax2764:editable>false</ax2764:editable>
            <ax2764:itemDisplayName/>
            <ax2764:itemName>false</ax2764:itemName>
            <ax2764:readOnly>false</ax2764:readOnly>
            <ax2764:roleType xsi:nil="true"/>
            <ax2764:selected>false</ax2764:selected>
            <ax2764:shared>false</ax2764:shared>
         </ns:return>
```

At the meantime, **getRoleNames** API of **RemoteUserStoreManagerService** returns the correct list of roles.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
