### ISSUE TITLE
IDENTITY-7341 Even a user is disabled or locked from IS and API Manager console. It is still able to call and use authentication API of API store and Oauth2

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5743]
Even a user is disabled or locked from IS and API Manager console. It is still able to call and use authentication API of API store and Oauth2. I have attached the configuration file.
1. Configured identity server as key manager using below link
https://docs.wso2.com/display/AM210/Configuring+WSO2+Identity+Server+as+a+Key+Manager
I am using default database (H2 database)
2. Registered a user in identity server and assigned role is “internal\creator, internal\publisher, internal\subscriber”
3. Sing up the wso2 API store using this user
4.  Login to the store web application as the signed-up user. 
5. Create an Oauth application in the store application of the API manager and subscribe to the published API using this created application.
6. Generate consumer key consumer secret pair for that application and access token. This access token is used by user to access API.
7. This application is automatically created a Service Provider on the WSO2 API. An internal user role was automatically created and the user was automatically assigned to this role as well.
8. disable or locked user from IS and API management console. 
9. login disable or locked user in API store,it is still able to regenerate new token and also able to access to API using this access token.

So is it a normal operation ??? in my opinion once i disable or lock a user from IS and API manager side then it should not be able to access the API using the API store.

**Comments**
_comment-1_
I have also checked by using to configured Mysql database and LDAP user store in WSO2 identity server(5.3.0) and API manager(2.1.0) and facing the same issue....

**Labels**
Type: Bug
Priority: Normal
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-7341_

**Comment by omindu** [comment]
In the API store, the keys are generated for the application (client credential grant), and not for the app owner (the locked user). When the app owner is locked, the token issued with the client credential grant is not revoked and using the client credentials (consumer key and secret) tokens should be generated

This requirement should be handled at the application side (API store). When the account is locked, the application should capture the lock event and make the application inactive.

If you require further help regarding the API store, please open an issue at API project at https://github.com/wso2/product-apim/issues/new
