### ISSUE TITLE
IDENTITY-7381 IdP Initiated Login/logout - Error

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5744]
The flow is working fine for all SP initiated requests (login and logout), however, its not the case with IdP initiated. SAML requests reach /commonauth URL, however, it throws an error as below:

Context does not exist. Probably due to invalidated cache	More
TID[-1234] [IS] [2017-12-26 17:00:12,826] ERROR
{org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator}
Context does not exist. Probably due to invalidated cache

Find below the SP metadata XML with the external IdP
```
<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" validUntil="2017-11-07T17:29:39Z" cacheDuration="PT604800S" entityID="jobs.clientdomain.com">
<md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>$KEY</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:KeyDescriptor use="encryption">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>$KEY</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://wso2-domain/commonauth"/>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://wso2-domain/commonauth" index="1"/>
</md:SPSSODescriptor>
</md:EntityDescriptor>
```

**Labels**
Type: Improvement
Priority: Normal
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-7381_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
