### ISSUE TITLE
IDENTITY-6557 module order in identity-event.properties

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5745]
When defining modules in identity-event.properties file, numbers of module.name should be in 1 to the number of modules. If there are skipped numbers, modules after that number wont work.

**Labels**
Type: Bug
Priority: High
Component/s: identity-mgt
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6557_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
