### ISSUE TITLE
Need a better way to identify the start of a new authentication flow

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#5746]
Currently, the details of authentication failures occur in user store level are not properly bubbled to OAuth response so that the receiving party can separately identify issues. The default behavior might be intended to be so due to security reasons, but it's nice to have flexibility in case there can be a requirement to capture a detailed response specially in password grant.

In DefaultRequestCoordinator.java (carbon-identity-framework), 
```
            // Check whether this is the start of the authentication flow.
            // 'type' parameter should be present if so. This parameter contains
            // the request type (e.g. samlsso) set by the calling servlet.
            // TODO: use a different mechanism to determine the flow start.
            if (request.getParameter("type") != null) {
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
