### ISSUE TITLE
Have SCIM 1.1 & SCIM 2.0 implementations to avoid conflicts

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5750]
Moved from: https://wso2.org/jira/browse/IDENTITY-6458

Have unified persistent layer in protocol agnostic manner & let the implementation to interpret data to protocol specific information.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
