### ISSUE TITLE
Unify responses of SCIM operations when user's who have same SCIM ID in different user stores

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5751]
Lets say the same underlying user store plugged as two different user stores(US1,US2) in identity server. And even though same user entity is sharing among user stores, it manage groups separately in each user store.

Here the user base is same but group base is different.

Now when create user "Darshana" in "US1" it will generate a scim id. Since the same underlying user store plugged is refering from "US2" also, it will show two users,
"US1/Darshana"
"US2/Darshana"
when listing users.

Steps to reproduce :

1. Create a user via SCIM. 
POST /Users { "userName: US01/TestUser", "password": "123456" } 

2. Query user by scimId and notice user store domain. 
GET /Users/db34031b-325f-4ba8-8c75-4d4e30821e75 --> "userName": "US01/TestUser" 

3. Create a new group via SCIM for the other secondary user store (different you got in step 2) assigning created user to it (POST /Groups). It fails. 
POST /Groups { "displayName": "US02/test","members": [ {"value": "db34031b-325f-4ba8-8c75-4d4e30821e75", "display": "US02/TestUser"} ] } --> Error 

4. Create a new group for the other secondary user store (as done in step 3) using Management Console. Update the existing group via SCIM and assign created user to the group (PUT /Groups/{groupId}. It works. 
PUT/Groups/ab34031b-325f-4ba8-8c75-4d4e30821e76 { "displayName": "US02/test","members": [ {"value": "db34031b-325f-4ba8-8c75-4d4e30821e75", "display": "US02/TestUser"} ] } --> Success 

Issue here is, step 3 and 4 should act as same way. Need to check whether step 3 can be improved to pick correct user in correct domain or 4 needed to added domain name validation.

If we going to support 3, all operations which able to pass domain name, should pick user in that domain.
(Still SCIM operations which only pass SCIM id don't have a enough info to choose correct user)

OT Jira: https://wso2.org/jira/browse/IDENTITY-3066

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
