### ISSUE TITLE
Give a option to select a existing "Claim Dialect" in the Service Providers\Identity Providers claim configuration

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5752]
**Description**
Currently we have two options in the claim configurations,
1. Use local claim dialect.
2. Define custom claim dialect.

This improvement is for adding a third option like,
3. Use existing claim dialect.

Or else we can replace option one with a drop down, which contains the wso2 claim dialect as default.

***NOTE***
This capability is available for Service providers in latest versions IS-5.8.0. But need to implement in identity providers as well.

**Type**
Improvement

**Priority**
Normal

**Affected version**
5.8.0

**Component/s**
claim-mgt, service-provider

**Severity**
Major

**Estimated Complexity**
Moderate

**Label/s**
Type/Improvement, Component/Claim Management, Affected/5.8.0, Severity/Major, Complexity/Medium, Priority/Normal

Moved from https://wso2.org/jira/browse/IDENTITY-3037

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
