### ISSUE TITLE
OIDC DCR specification compliance issues.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5753]
- **response_types**
OPTIONAL. JSON array containing a list of the OAuth 2.0 response_type values that the Client is declaring that it will restrict itself to using. If omitted, the default is that the Client will use only the code Response Type.
- **A validation should happen for below,**
The following table lists the correspondence between response_type values that the Client will use and grant_type values that MUST be included in the registered grant_types list:
code: authorization_code
id_token: implicit
token id_token: implicit
code id_token: authorization_code, implicit
code token: authorization_code, implicit
code token id_token: authorization_code, implicit
If omitted, the default is that the Client will use only the authorization_code Grant Type.
- Support for other 'Client Metadata' section validations needs to be implemented.
- redirect_uris meta data should not be mandatory for all grant types. Client registration should be possible without this meta data for password, client credentials, SAML2 and IWA-NTLM grant types.

OT Jira: https://wso2.org/jira/browse/IDENTITY-5879

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
