### ISSUE TITLE
Improve Caching Layer in OAuth component

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5755]
There are instances in the OAuth component where we cache a different object that what we store in the DB. 

Let me give a few examples,
* When we issue an authorization code we cache the authorization code object. This cached object contains the authorized user. The authorized user in the cached object contains **user attributes**, etc. But when we store the authorization code in DB the user attributes are not stored. **So we have a difference between the actual object stored in DB and cache**. This could cause inconsistencies when the DO object is served from cache and DB.

* When we issue a JWT access token, we store the JWT ID in the DB instead of the JWT token returned to the client. But the token added to the cache has the JWT as the access token. This once again is inconsistent

So it would be worth to revisiting the caching layer in OAuth and other places to make sure that we only cache an exact copy of what we store in the DB.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
