### ISSUE TITLE
Edits to the Cookie Policy 

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#5758]
The cookie policy of WSO2 Identity Server 5.7.0 is mentioning the 5.5.0 version. Please fix in 5.7.0 and other applicable versions.

**Comment by hauntingEcho** [comment]
possibly a duplicate of https://github.com/wso2/carbon-identity-framework/issues/1842

**Comment by darshanasbg** [comment]
@dewniMW Lets fix this for master. Additionally, we have to come up with a way to avoid updating version in each product release as it doesn't scale.

**Comment by madurangasiriwardena** [comment]
@YvonneW, thanks for reporting the issue and @hauntingEcho thanks for pointing out that this is a duplicate.
We are closing this since this is a duplicate of https://github.com/wso2/carbon-identity-framework/issues/1842.

**Comment by madurangasiriwardena** [comment]
@YvonneW thanks for reporting the issue.
@hauntingEcho Thanks for pointing out that the issue is duplicate.

We are closing this issue since this is a duplicate of https://github.com/wso2/product-is/issues/3570
