### ISSUE TITLE
Issue due to username case sensitivity in consent management

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#5761]
When logging into an SP, providing a different upper-lower case version of the username prompts the user the set consent page. Each upper-lowercase variation of one particular username has it’s own consent settings.

The case of the username should have no influence on the consent configuration and it should be bound to the user, regardless of the variation of the usernames’ case.

**Comment by Buddhimah** [comment]
For the public fix the issue is by default resolved. So system will consider user name case insensitive by default. in the public fix.
