### ISSUE TITLE
Define required permissions for OAuth2 Scope Endpoint

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5762]
At the moment we do not have any permission requirements specified for the operations done on the oauth2 scopes via https://docs.wso2.com/display/IS570/Using+the+OAuth2+Scopes+REST+APIs

We need decide and enforce the correct permissions using the REST API valve.

**Comment by Thumimku** [comment]
Adding path to identity.xml file
https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L1190
