### ISSUE TITLE
[DOC] OAuth2 Scope Endpoint not documented in IS 5.8.0 doc space

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5763]
OAuth2 scope endpoint is documented for IS 5.7.0 at https://docs.wso2.com/display/IS570/Using+the+OAuth2+Scopes+REST+APIs

It seems to be missing from the IS 5.8.0 doc space.

**Comment by mefarazath** [comment]
Was this done intentionally?

**Comment by sherenewso2** [comment]
This page is available in 5.8.0 here. It has just been renamed. 
Asked infra to redirect the old url to the new one to avoid confusion. 

https://docs.wso2.com/display/IS580/Using+OAuth2+Scopes+REST+APIs

**Comment by mefarazath** [comment]
Thanks for the prompt action @sherenewso2
