### ISSUE TITLE
setCookie always sets an encoded value in authentication scripts

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5765]
Even if we disable "sign" and "encrypt" as below
```
setCookie(context.response, "name1", "value1", {"expires" : "session",
                                            "path" : "/",
                                            "httpOnly" : false,
                                            "hostOnly" : false,
                                            "secure" : false,
                                            "encrypt" : false,
                                            "sign" : false});
```

The cookie sent to the browser has the following format
`base64encode({"signature": null,"value": "value1"})`

**Suggestions**
- Update the doc [1] to describe the cookie format to avoid confusion when observing the cookies from a browser
- Consider about setting the plain text or encrypted value of the cookie to the browser when "sign" is false.

[1] https://docs.wso2.com/display/IS570/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-setCookie(response,name,value,properties)

**Comment by senthalan** [comment]
I have created https://github.com/wso2/product-is/issues/5758 to track the 2nd suggestion

**Comment by ruwanta** [comment]
In the documentation please add the following.
1. The cookie is only interpreted by Identity server. 
2. Please do not make any assumption about the cookie value or format. 
3. Please do not access the cookie with front end Javascript.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
