### ISSUE TITLE
Comma (",") is appended to the email after SCIM patch operation

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#5766]
Please see the steps given below on how to reproduce.

1. Configure a JDBC user store with SCIM enabled. 
2. Add a user. (Through SCIM or management console)
3. Update user profile to have an email address.
4. Update this user using SCIM patch operation. (Update attribute other than the email.)
5. You can see a comma appended at the end of the email.

**Comment by nilasini** [comment]
You could see the comma appended to the email through a user profile(management console)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
