### ISSUE TITLE
Directing to the same topic of the latest document with the provided link in the documents of older versions

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5767]
When we go to a specific topic in an older version doc, in the top of the page a link to the latest document is provided as, "This documentation is for WSO2 Identity Server 5.5.0. View documentation for the latest release." 

When we click on the link, we will be directed to the page https://docs.wso2.com/display/IS580 always. But it would be more convenient if the link takes the user to the **same topic** in the latest document when clicking on the given link. 

Now the easiest way to access the latest document of a specific topic from an older version doc is changing the version manually in the URL. It won't be always possible for external users.

**Comment by sherenewso2** [comment]
Hi,

Ack. This issue has been reported before and we have considered this. Yes, linking the user to the same page in the next version would be great but unfortunately, not every page will have a corresponding page in the latest version (titles could have changed, page could have been removed, restructured etc). This causes a "page not found" and a bad UX for the user..

As discussed with @jeradrutnam  usually one user will be using one version at a given time. Once they navigate to the docs of that version, they won't need to go back and forth between versions all that much and hence this function is not much of an issue for end users. We have made the UX of this navigation a bit better in the Git-based docs.
