### ISSUE TITLE
[Doc]How to send request for tenants is not mentioned in Scope Management

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#5768]
The documentation[1] about Scope Management didn't mention about how to send requests to 
tenants.

1. [Scope Management](https://docs.wso2.com/display/IS580/apidocs/OAuth2-scope-endpoint/#!/operations#ScopeManagement#registerScope)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
