### ISSUE TITLE
[DOC] EmailOTP documentation needs to be updated.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5771]
The documentation available for emailOTP is [1]. Some content in [2] is not there in [1]. Therefore, if these configs are necessary, the documentation needs to be updated.

```
<AuthenticatorConfig name="EmailOTP" enabled="true">
    <Parameter name="EMAILOTPAuthenticationEndpointURL">https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp</Parameter>
    <Parameter name="EmailOTPAuthenticationEndpointErrorPage">https://localhost:9443/emailotpauthenticationendpoint/emailotpError.jsp</Parameter>
    <Parameter name="EmailAddressRequestPage">https://localhost:9443/emailotpauthenticationendpoint/emailAddress.jsp</Parameter>
    <Parameter name="usecase">association</Parameter>
    <Parameter name="secondaryUserstore">primary</Parameter>
    <Parameter name="EMAILOTPMandatory">false</Parameter>
    <Parameter name="sendOTPToFederatedEmailAttribute">false</Parameter>
    <Parameter name="federatedEmailAttributeKey">email</Parameter>
    <Parameter name="EmailOTPEnableByUserClaim">true</Parameter>
    <Parameter name="CaptureAndUpdateEmailAddress">true</Parameter>
    <Parameter name="showEmailAddressInUI">true</Parameter>
</AuthenticatorConfig>
```

[1] - https://docs.wso2.com/display/IS580/Configuring+Email+OTP
[2] - https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/docs/config.md#enabling-email-configuration-on-wso2-is

**Comment by rksk** [comment]
All the configuration params have to be described in the doc along with steps to enable HTML Templates in Emails. Everything is mentioned in the above github page, but it is not that simple to find it.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
