### ISSUE TITLE
[Docs] Update configurations in the self contained access tokens doc

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#5776]
Documentation [1] is outdated and still shows global server side configurations for the Self Sign Access token. It needs to be updated

[1] https://docs.wso2.com/display/IS570/Self-contained+Access+Tokens

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
