### ISSUE TITLE
URL validation inconsistency between SAML2 and OAuth/OpenID Connect configs

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#5783]
#### Description
When adding inbound authentication configurations for a service provider, the callback URL in the OAuth/OpenID is validated as a URL but the assertion consumer URL in the SAML2 does not.

#### Steps to Reproduce
Try to configure the following URL as both OAuth/OpenID callback URL and SAML2 assertion consumer URL, in the service provider inbound authentication configurations. 

 `https://www.goo  gle.com/`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
