### ISSUE TITLE
Performance reduction on service provider creation

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5797]
When invoking the DCR endpoint, the following query is executed twice for each invocation. This query is run to check whether a given user has a given role from [1]. When there is a lot of service providers created from a single user, that user may have lots of roles and this query will select them all and take time for it.
```
SELECT UM_ROLE_NAME
FROM   UM_HYBRID_USER_ROLE,
       UM_HYBRID_ROLE
WHERE  UM_USER_NAME = "admin"
       AND UM_HYBRID_USER_ROLE.UM_ROLE_ID = UM_HYBRID_ROLE.UM_ID
       AND UM_HYBRID_USER_ROLE.UM_TENANT_ID =- 1234
       AND UM_HYBRID_ROLE.UM_TENANT_ID =- 1234
       AND UM_HYBRID_USER_ROLE.UM_DOMAIN_ID = (SELECT UM_DOMAIN_ID
                                               FROM   UM_DOMAIN
                                               WHERE  UM_TENANT_ID =- 1234
                                                      AND UM_DOMAIN_NAME =
                                                          "PRIMARY")
```

[1] https://github.com/wso2/carbon-kernel/blob/v4.4.40/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/hybrid/HybridRoleManager.java#L389

Related: https://github.com/wso2/product-is/issues/2083

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
