### ISSUE TITLE
[Doc] OAuth/OpenID custom grant type is not highlighted

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#5799]
There is a note like below in the documents for 5.7.0 [1]. 

> Note: The grant type highlighted below is a custom grant type. This will only appear on the UI if you have configured the JWT grant type. The value specified in the <GrantTypeName> property of the identity.xml file when creating the custom grant type is the value that will appear on the UI. For more information on writing a custom grant type, see Writing a Custom OAuth 2.0 Grant Type.

But in the image below the custom grant type is not highlighted.

**Affected Document Versions:** 
5.5.0, 5.6.0, 5.7.0 and 5.8.0

Documents of 5.4.0 and 5.3.0 are with the correct image [2]

[1] https://docs.wso2.com/display/IS570/Configuring+Inbound+Authentication+for+a+Service+Provider
[2] https://docs.wso2.com/display/IS540/Configuring+Inbound+Authentication+for+a+Service+Provider

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
