### ISSUE TITLE
[Doc] Documents for WSO2IS-5.3.0 and WSO2IS-5.7.0 are not updated on "Configuring SAML2 Front-Channel Logout".

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#5805]
**Description:**
Documents for WSO2IS-5.3.0 and WSO2IS-5.7.0 are not updated on "Configuring SAML2 Front-Channel Logout". Only WSO2IS-5.8.0 documentations are updated.

**Suggested Labels:**
Type/Documentation

**Affected Product Version:**
WSO2IS-5.3.0, WSO2IS-5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
