### ISSUE TITLE
Two Claim Management UIs are displayed

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5807]
Notice subject on a IS 5.8.1-m5-snapshot pack after the new config model changes are merged.

<img width="256" alt="Screen Shot 2019-06-26 at 4 59 39 PM" src="https://user-images.githubusercontent.com/5237653/60177963-df63e580-9837-11e9-8a21-282d9069177f.png">

In previous versions, we had the below configs to hide the old claim management UI component

```
<HideMenuItemIds>
<HideMenuItemId>claim_mgt_menu</HideMenuItemId>
<HideMenuItemId>identity_mgt_emailtemplate_menu</HideMenuItemId>
<HideMenuItemId>identity_security_questions_menu</HideMenuItemId>
</HideMenuItemIds>
```

We should see similar issue with other UI components expected to be hidden with the above config.

**Comment by hasinidilanka** [comment]
Fixed with:https://github.com/wso2/product-is/pull/5865

**Comment by darshanasbg** [comment]
With the new configuration model, can we switch which claim UI need to be visible?

**Comment by hasinidilanka** [comment]
We can hide the old claim UI.
