### ISSUE TITLE
Active Directory as Primary, User List of Role : Domain Users is BLANK

### ISSUE THREAD

**Issue by kcsapersona** [wso2/product-is#5809]
After adding CA Certs, and setting up AD as my primary User Store, everything seems to be working. 
In the WSO2IS Mgmt Console, I can open up users and see them, and open up groups and see the users in each group, except "Domain Users".  User List of Role : Domain is BLANK.
In fact, I can add users to groups, but if I try to add a user to the Domain Users group, I get an error. (I can create new users, I just can't add them to the Domain Users group.)

ERROR {org.wso2.carbon.user.mgt.ui.UserAdminClient} -  Error occurred while modifying user entry: CN=abcd,CN=Users,DC=mydomain,DC=com in LDAP role: CN=Domain Users
org.wso2.carbon.user.mgt.stub.UserAdminUserAdminException: UserAdminUserAdminException

Environment
WSO2 v5.8 (Centos7)
AD (Windows 2016 Svr)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
