### ISSUE TITLE
Account Lock reason not update for account suspension events

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#5813]
Affected: 5.7.0 
Severity: Critical
Priority: High
Type: Bug

**Description:** 
Account suspension event not update the account locked reason claim.

**Steps to reproduce:**
01. Do the configuration according to the document [1]
02. Enable the last login claim and the account lock reason claims as default
03. Create a epoch time as a last login and add it into the users last login claim [2]
04. Update the user profile with the updated last login claim
05. Change the PC system date and time accordingly
06. Wait until suspension event to triggered
07. Verify the account is suspension and locked reason filed is updated in the user profile

**Expected result:**

Account should be suspended and locked reason claim should be update

**Actual results:**

Account is get suspend, but locked reason claim is not update accordingly.

[1] https://docs.wso2.com/display/IS570/User+Account+Suspension
[2] https://www.epochconverter.com/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
