### ISSUE TITLE
[DOC] Missing instruction in account suspension guide

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#5814]
Affected: All versions
Severity: Critical
Priority: High
Type: Bug

The account suspension document should mansion the relevant claims to set default to trigger the event. But document [1] not mentioned the relevant claims [2] and [3]

[1] https://docs.wso2.com/display/IS570/User+Account+Suspension
[2] http://wso2.org/claims/lastLoginTime
[3] http://wso2.org/claims/identity/lockedReason

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
