### ISSUE TITLE
User creation via SCIM2 API does not return updated attribute values of the user

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#5816]
The issue fixed in [here[1]](https://wso2.org/jira/browse/IDENTITY-6299) is not fixed for SCIM 2. Therefore if claims were modified over a 'UserOperationEventListener' while creating the user, neither those claims updated, will be reflected in the user creation response.

[1] https://wso2.org/jira/browse/IDENTITY-6299

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
