### ISSUE TITLE
NullPointerException after adding CAS authenticator

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#5821]
Hi All,

After adding CAS inbound authenticator inside the dropins folder, we are experiencing a NullPointerException in the server startup logs (Note: this happens only for the very first time).

Experiencing another NullPointerException while invoking the addUser admin service.

IS version - 5.7.0 + 1560701512699
(noticed the same behavior in latest WUM (1561483590685) updated IS pack)
Note: not reproducible in vanilla pack

Steps to Reproduce

**Issue 01**

- Download WUM updated IS-5.7.0 pack (unable to reproduce in the vanilla pack)
- Add CAS inbound authenticator connector [1] to the dropins folder
- Start the identity server
(Note: this is happening only for the very first time of server startup)

**Issue 02**

- In the same IS pack (with the CAS connector in the dropins folder), invoke the addUser endpoint through SoapUI
(https://localhost:9443/services/UserAdmin.UserAdminHttpsSoap11Endpoint/)
(Note: this is happening only for the very first request after server restart)

[1] - https://store.wso2.com/store/assets/isconnector/details/593aac68-3139-425c-b9ca-f66a65a0917a

Thanks

**Comment by gayashanbc** [comment]
**Note:** In the latest release of Identity Server, the following configuration has to be done **explicitly**, in order for the CAS authentication to work.
- **File:** ` <IS_HOME>/repository/resources/conf/templates/repository/conf/identity.xml.j2`
- **Parent Tag:**  `<ResourceAccessControl>`
- **Configuration that should be added inside the Parent Tag:**  `<Resource context="/identity(.*)" secured="false" http-method="all"/>`
- **Reason:**  In the latest version of Identity Server, `<ResourceAccessControl> `has been set to `<ResourceAccessControl default-access="deny">`. Hence, this will deny access to CAS authentication by default.

** Above configuration should be documented as well.
