### ISSUE TITLE
ACR not returned in SAML2 response

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#5823]
The use case is ACR template based conditional authentication. 
 
If we send the saml:AuthnContextClassRef value as below in the SAML auth request.
<samlp:RequestedAuthnContext Comparison="exact">
<saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:TimeSyncToken</saml:AuthnContextClassRef>
</samlp:RequestedAuthnContext>
After the authentication, the SAML response contains the below as the "saml2:AuthnContextClassRef".
<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>
 
According to the specification(section 3.3.2.2.1 and line number 1865)[1], the "RequestedAuthnContext" is the one which should be sent in the SAML response. Even if we put this aside in the adaptive ACR based script, the selected ACR is not returned in the response which is expected.
 
[1] - https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf

**Comment by ruwanta** [comment]
Pull Request for Framework https://github.com/wso2/carbon-identity-framework/pull/2278

**Comment by ruwanta** [comment]
Pull request for the SAML https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/233
