### ISSUE TITLE
Definition of ThriftAuthenticationService in documentation 

### ISSUE THREAD

**Issue by cicode225** [wso2/product-is#5824]
Hello,
This issue : https://github.com/wso2/product-is/issues/3339 is about adding ThriftAuthenticationService configuration in the documentation. But, for people like me (noobs!!!) there is NO definition of what ThriftAuthenticationService simply is. Could you tell me that please ?
Also, it'd be great if you add it in the doc. 
Thank you

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
