### ISSUE TITLE
access-subject attribute needs to added for the token scope validation request

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#5834]
In the https://github.com/wso2-extensions/identity-oauth-addons/blob/master/component/org.wso2.carbon.identity.oauth2.validators.xacml/src/main/java/org/wso2/carbon/identity/oauth2/validators/xacml/XACMLScopeValidator.java#L137, 'urn:oasis:names:tc:xacml:1.0:subject-category:access-subject' needs to be added to the XACML request, because the default PIP will search in the user stores for the claims using that attribute

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
