### ISSUE TITLE
Deprecate ClaimManagementService API

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5837]
We need to mark the ClaimManagementService API as deprecated. 

https://github.com/wso2/carbon-identity-framework/blob/master/components/claim-mgt/org.wso2.carbon.claim.mgt.ui/src/main/resources/ClaimManagementService.wsdl

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
