### ISSUE TITLE
Disable considering case insensitive by default in consent management

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#5838]
To avoid Each upper-lowercase variation of one particular username having it’s own consent settings. Consent management will consider by default user name is case insensitive. If you have a requirement of using case sensitive user names you need to disable this feature by adding the following property to relevant user store. 

`<Property name="UseCaseSensitiveUsernameForCacheKeys">true</Property>`

**Related PR**

[https://github.com/wso2/carbon-consent-management/pull/161](https://github.com/wso2/carbon-consent-management/pull/161)

**Related Issue**

[https://github.com/wso2/product-is/issues/5761](https://github.com/wso2/product-is/issues/5761)

Suggested Label: Migration

**Comment by Abilashini** [comment]
Has been included in the 5.9.0 migration doc [1]
[1] https://is.docs.wso2.com/en/latest/setup/migrating-what-has-changed/
