### ISSUE TITLE
IS-4.6.0 Axis2 mail sender error log missing the exception object

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#5843]
IS 4.6.0

Issue : 
IS 4.6.0 uses axis2 mail to transport to send mails. If the service invocation throws an error, the client logs the exception partially as [below](https://svn.wso2.org/repos/wso2/carbon/platform/tags/turing-chunk11/components/identity/org.wso2.carbon.identity.mgt/4.2.1/src/main/java/org/wso2/carbon/identity/mgt/mail/DefaultEmailSendingModule.java).
`} catch (Exception e) {
            log.error("Failed Sending Email" + e);
}`
This has been fixed in the latest versions.
`} catch (AxisFault axisFault) {
         log.error("Failed Sending Email", axisFault);
} finally {`

Reproducing:
Send out a a mail from the IS 4.6.0 with wrong SMTP credentials. (Ask password flow)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
