### ISSUE TITLE
Support comma seperated oauth2 scopes

### ISSUE THREAD

**Issue by karatakis** [wso2/product-is#5845]
Hello,
I have a legacy oauth2 application that requires the following scope `scope1`.

I configured it to request both `openid` and `scope1` scopes on the authentication flow.

**User story**
When a user tries to login, the application requests a token with the following scopes `openid,scope1`.
**Current Behavior**
But when I try to request the user info from the https://localhost:9443/oauth2/userinfo?context=openid endpoint I get the following error.

`{"error":"insufficient_scope","error_description":"Access token does not have the openid scope"}`

**Expected Behaviour**
Ignore that the scopes are comma separated and return user information.

**Solution**
Add a middleware function that checks if scopes are comma separated and replace the commas with spaces.

**Proposal**
I know that comma separated scopes are not mentioned in the OAUTH2 standard but production applications (ex Github) with incorrect oauth2 implementation unfortunately use them. Could you please provide a solution to this issue in the future ?

WSO2-IS Version: 5.7

**Comment by mefarazath** [comment]
@karatakis What grant type does the application use to get the access token?

**Comment by karatakis** [comment]
Implicit flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
