### ISSUE TITLE
[DOC] Missing instruction in configuring SessionDataCleanUp task.

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-is#5846]
Affected: All versions

The Authentication session persistence documentation [1] should mention that in a clustered deployment, the SessionDataCleanUp task should only be enabled in a single node. 

[1] https://docs.wso2.com/display/IS5XX/Authentication+Session+Persistence

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
