### ISSUE TITLE
Implement inbound authentication config export/import for CAS inbound authenticator

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#5848]
CAS inbound authenticator [1] config cannot be exported/inbound with the service provider configs. Need to implement an ApplicationMgtListener to do this.

[1] https://github.com/wso2-extensions/identity-inbound-auth-cas

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
