### ISSUE TITLE
Improve  QSG SSO samples to be compatible with latest sso agent version

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#5853]
Initially, there was an issue https://github.com/wso2/product-is/issues/3485 due to breaking changes introduced in sso-agent versions after 5.1.14 which resulted in compilation failures in the Travelocity sample.

While fixing https://github.com/wso2/product-is/issues/3485 we noticed that there are behavioural changes introduced to sso agent and the QSG saml sso samples[1].

One of the behavioural changes was that logic to redirect to "index.jsp" after a logout was added into the sso agent filter. This is not correct since we cannot assume that app will always have an index.jsp and the starting page of the app could be a different one.

 We reverted the behavioural changes with PR[2].

So, if we upgrade the sso agent version in QSG saml sso samples most probably it will break the expected behaviour. We need to check and fix the QSG samples.

[1] https://github.com/wso2/samples-is/tree/master/sso-samples/saml2-sso-sample
[2] https://github.com/wso2/product-is/pull/5818

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
