### ISSUE TITLE
SCIM2 Filtering does not support the logical operators ne,gt,lt,ge,le,or,not

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#5854]
**Suggested Labels:**
Type/Improvement

**Environment**
IS with KM 5.7.0

**Description**

SCIM 2 User filtering currently does not support for operations mentioned below. 
ne,
gt,
lt,
ge,
le,
or,
not 

As per the SCIM2 spec [1] section 3.4.2.2 we need to support SCIM2 filtering with above mentioned operators. 

Should support for user filtering for a scenario as mentioned below

`curl -v -k --user admin:admin https://wso2-kmis-001:9450/scim2/Users/?filter=(userName+sw+Shawn) or (EnterpriseUser.city+sw+dolly) or (EnterpriseUser.organization+sw+my) -k -i 
`

[1]. https://tools.ietf.org/html/rfc7644#section-3.4.2

**Comment by rksk** [comment]
`ge` and `le` are implemented with https://github.com/wso2/product-is/issues/11214

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
