### ISSUE TITLE
Upgrade jackson-databind dependency in new config parser

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#5856]
Related to: https://github.com/wso2/carbon-deployment/pull/321/files

Upgrade jackson-databind dependency[1] to 2.9.9.1

[1] - https://github.com/wso2/carbon-kernel/blob/4.5.x/parent/pom.xml#L632

**Comment by mefarazath** [comment]
Or if the minor release 2.9.10 is released we can move to that too.

**Comment by hasinidilanka** [comment]
Fixed by: https://github.com/wso2/carbon-kernel/pull/2107
