### ISSUE TITLE
Front Port: Imporvement - admin services to call through the local transport in the dashboard app

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#5866]
For a previous release(IS 5.6.0), there was an improvement for support local transport for the dashboard application. Shall we front port this improvement for IS 5.7.0 as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
