### ISSUE TITLE
Slowness Observed in SCIM2 APIs When Comparing IS 5.8.1-m5-SNAPSHOT With WSO2 IS 5.7.0

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5881]
While I was working with SCIM2, I observed that all the SCIM2 APIs in IS 5.8.1-m5-SNAPSHOT always consume more time by compared with WSO2 IS 5.7.0.  I have done a quick analysis on update group with patch operation of SCIM2 API.  Locally I measured the time (ms) taken to update a group with a new user when that particular group contains up to 5000 members in inbuilt JDBC user store. Please find my observation below, 

Latest WUM pack IS 5.7.0

No. of users in a group   |   Time is taken to add a new user to a group (ms)
-- | --
100 | 114
500 | 356
1000 | 416
1500 | 383
2000 | 424
5000 | 1614

Master pack IS 5.8.1-m5-SNAPSHOT

No. of users in a group | Time is taken to add a new user to a group (ms)
-- | --
100 | 991
500 | 1962
1000 | 3209
1500 | 4830
2000 | 4848
5000 | 14282

By looking at the response time, IS 5.8.1-m5-SNAPSHOT response time is always greater than 5 times of  IS 5.7.0 response time.

**Comment by aaujayasena** [comment]
This is retest with the product version 5.10.0-beta3 version and user count is 5000. Results as below.

No. of users in a group | Time is taken to add a new user to a group (ms)
-- | --
5000 | 274

Response time performance has been increased according to the above results. Hence this issue can be close. 

Test steps:
1. Configuring the  user server with relevant user store
2. Create 5000 users using jmeter script and all 5000 users assign to same group[1]
3. Add new user to the group with jmeter script [2], HTTP Request - PATCH/ Update Group

[1] https://github.com/wso2/performance-is/blob/master/common/jmeter/setup/TestData_Add_Super_Tenant_Users.jmx
[2]https://github.com/aaujayasena/scim2_tests-is/blob/master/SCIM2_TESTS.jmx
