### ISSUE TITLE
Not validating the SP's certificate expiry time upon using it to validate SAML signature.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#5883]
IS 5.2.0

Identity Server is not validating the Service Provider's public certificate's expiry time upon using it to validate the signature of the SAML authentication request. This should be done and discard the request if the certificate is already expired.

Steps to reproduce.
Configure Travelocity SAML SP with Identity Server 5.2.0
Check the copy the same keystore as IS server to the Travelocity.
Check the certificate expiry time using keytool command.
`keytool -list -v -alias wso2carbon -keystore wso2carbon.jks`
Change the system time of IS server machine to a date where the public certificate would be expired.
Try to login from the Travelocity app.

**Comment by GDRDABARERA** [comment]
Fixed in master , hence closing
