### ISSUE TITLE
[Docs] "Configure the Cache Layers" new versions are missing

### ISSUE THREAD

**Issue by rnavagamuwa** [wso2/product-is#5888]
I have noticed that ["Configure the Cache Layers"](https://docs.wso2.com/display/IS550/Configure+the+Cache+Layers) doc is not available after 5.5. Is there a specific reason for that? Is it okay to assume that the doc is valid for the latest versions as well?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
