### ISSUE TITLE
Improve debug logs to identify request context in authorization code flow

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#5890]
Not enough debug logs available in identifying the redirect URL validation for the authorization code flow in IS 5.2.0 version.

Steps:
1. Configure an oauth app with a specific redirect URI in IS
2. Initiate an authorization code grant request to IS for that client with a some other redirect URI which is different than configured
3. Observe the that the flow breaks but no enough information on server logs to identify the cause.

This informations is available with latest versions [1].

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/AuthorizationCodeGrantHandler.java#L107

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
