### ISSUE TITLE
Rename "callback" to "callbackUrl"

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#5909]
In https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/webapp/password-reset-complete.jsp#L41 use of "callback" word can cause collisions as there are many callback related  parameters that can set as name value pairs,

So better to rename as "callbackUrl"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
