### ISSUE TITLE
reword SMSOTP header

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#5913]
While OTP in this instance should be taken to mean "One-Time Pad", OTP has another less-work-safe meaning which is much more commonly used.  Therefore, rather than displaying "Authenticating with SMSOTP" to end-users a message like "SMS Verification" would be preferred.

"Authenticating with SMSOTP": https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/master/component/authentication-endpoint/src/main/webapp/smsotp.jsp#L97

email OTP uses the phrasing "Email Verification": https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authentication-endpoint/src/main/webapp/emailotp.jsp#L87

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
