### ISSUE TITLE
deduplicate auth endpoint JSP header code

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#5914]
several of the authentication-endpoint webapps duplicate code for their header bar.  Deduplicating this code can make it easier to update.  I've opened PRs to deduplicate the header within several of the default WARs:

wso2/carbon-identity-framework#2289
wso2/carbon-identity-framework#2290
wso2-extensions/identity-outbound-auth-sms-otp#64
wso2-extensions/identity-outbound-auth-email-otp#53
https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/52

I'd argue that only having a single header JSP (referenced by all webapps) would be even better, but I'm not familiar enough with the overall codebase to do so at this point.

**Comment by jeradrutnam** [comment]
Thanks for the contribution. Yes, it has been handled in the new webapps. And we have merged your PRs for the older code bases.
