### ISSUE TITLE
[Doc] Prioritize adding 'https' prefix to the domain name in Salesforce IDP configuration 

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#5916]
Documentation [[1]](https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce) needs to highlight adding 'HTTPS' prefix to the domain name in Configuring Salesforce as the Identity Provider section for outbound provisioning with Salesforce.

[1] - https://docs.wso2.com/display/IS580/Outbound+Provisioning+with+Salesforce

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
