### ISSUE TITLE
Unable to add registry resource through management console from Firefox browser

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#5918]
Hi All,

When adding a new registry resource through management console it keeps loading as below attached image. This is only reproducible only in Firefox browser after the release version v57 (Quantum release)

![image-2019-06-06-15-07-18-310](https://user-images.githubusercontent.com/13187638/61271565-9d88e800-a7c2-11e9-9280-dd735eb2a0b3.png)

wso2is version -5.7.0 / 5.8.0

Steps to Reproduce:

- login to management console through Firefox browser
- browse registry
- navigate to any registry path and click on Add Resource
- choose "Create Text Content" from method drop down and add new resource

I noticed that wso2 is using YUI library and from Firefox v57 release onwards, YUI library has stopped working on Firefox [1], this could be the issue.

[1] - https://bugzilla.mozilla.org/show_bug.cgi?id=1418639

Thanks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
