### ISSUE TITLE
Include optional parameters in the response when validating  the self-contained access token

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#5922]
Hi All,

According to spec [1], the following are optional parameters to be included in the validation response

"sub", "aud","iss", "jti"

The requirement is when we Invoking the token introspection endpoint to validate the self-contained access token
We need to add those above optional attributes to be included in the validation response.

[1] https://tools.ietf.org/html/rfc7662#section-2.2

**Comment by LahiruLS** [comment]
Hi All,

This was added to the product with the improvement: https://github.com/wso2-support/identity-inbound-auth-oauth/commit/2c3f5159b9b1284cce389ce9d06d2fc3d420feec

Ref: https://github.com/wso2/product-apim/issues/11894
