### ISSUE TITLE
Improve generating server metadata for identity-apps

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#5934]
Need to improve: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1143

* We need to avoid updating server configs during server startup as mentioned in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1143#pullrequestreview-263419338
* We need to move app creation logic from OAuth component.

**Comment by darshanasbg** [comment]
Also referred in: https://github.com/wso2/product-is/issues/5935

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
