### ISSUE TITLE
Portal application creation in IS needs to be an one-time Dev-Op task

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#5935]
We need to think of creating all the applications with a tool or command-line option. Creating at server start will not work for containers, or multi-node cluster, etc. Creating an application should be a one-time Dev-Op task.

**Comment by ayshsandu** [comment]
@thanujalk can you mention the state of this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
