### ISSUE TITLE
Remove autofilling of security question answer in password recovery

### ISSUE THREAD

**Issue by Chamodii** [wso2/product-is#5947]
security question answer field is auto-filled with some value which is unnecessary and a trouble to the user since he first has to remove that value before entering the answer. Better to get rid of that.
(autocomplete="off" doesn't solve the issue)
![security-question-git-issue](https://user-images.githubusercontent.com/37044398/61455126-4b8dc100-a980-11e9-9dbd-5640964c70fd.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
