### ISSUE TITLE
JWT token is not properly validated when token type hint is not provided

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5956]
When the token_type parameter is not presented with the introspection request it takes _"bearer"_ token type as the default one. Therefore when a self-contained access token is presented without the token type hint it is validated by **DefaultOAuth2TokenValidator** even though it should be validated by **OAuth2JWTTokenValidator**.

**Comment by malithie** [comment]
So what's the behaviour incurred on the introspection response due to above flow.
And what happens in the case of a bearer token

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
