### ISSUE TITLE
Error occured while perform multi attribute searching using SCIM2 User Filter API in Oracle DB

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#5959]
Steps to reproduce.

1) Configure "wso2is-km-5.7.0+1560701512699' with Oracle DB and JDBC user store(primary)
2) Create an user and fill the profile information.
3) try to filter user with multiple filter as mentioned in [1] and see below sample.

Request

`curl -v -k --user admin:admin 'https://10.200.1.202:9443/scim2/Users?startIndex=1&count=10&domain=PRIMARY&filter=name.givenName+Eq+dinesh+and+name.familyName+Eq+susa'`

Response

`{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","detail":"Error in filtering users by multi attributes ","status":"500"}`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
