### ISSUE TITLE
Universal location for the configurations for the web applications

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#5964]
Hi All, 

For the web application configurations, it is convinent if we could move all of the configurations to a universal location. 

Currently, if we need to change a configuration we have to extract the web app and change the configuration then repack again and use the modified war file.

This can be a registry location or a file location. It is convinent for the users to change the configurations on web applications in such location instead of inside the wen application itself. 

Related issues, #5211

**Comment by rksk** [comment]
Resolved with https://github.com/wso2/carbon-identity-framework/pull/2275
