### ISSUE TITLE
missing toml configs for .xml properties in user-mgt.xml file

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#5979]
The following prorperties in user-mgt.xml file, need their toml equivalent  in doc (1) and (2). 

In configuring the authorization manager (refer doc(1))
-dataSource
-isCascadeDeleteEnabled
-testOnBorrow

```
<AuthorizationManager class=""org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager"">
        <Property name=""AdminRoleManagementPermissions"">/permission</Property>
        <Property name=""AuthorizationCacheEnabled"">true</Property>
       <Property name=""GetAllRolesOfUserEnabled"">false</Property>
 </AuthorizationManager>
```

`<Property name=""CaseSensitiveAuthorizationRules"">true</Property>"`

In configuring the system administrator (refer doc(2))
```
<Realm>
  <Configuration>
   <AddAdmin>true</AddAdmin>
   <AdminRole>admin</AdminRole>
   <AdminUser>
       <UserName>admin</UserName>
       <Password>admin</Password>
   </AdminUser>
   <EveryOneRoleName>everyone</EveryOneRoleName> <!-- By default users in this role see the registry root -->
   <Property name=""""></Property>
   ...............
  </Configuration>
...
</Realm>
```

[1]https://docs.wso2.com/display/IS580/Configuring+the+Authorization+Manager
[2]https://docs.wso2.com/display/IS580/Configuring+the+System+Administrator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
