### ISSUE TITLE
Inconsistency of key names in GET ME response

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#5981]
Observed that when a GET request is sent to the scim2/me endpoint the key of the currently authenticated user's organization value is changed in the latest version. The key name change is as follows.

5.7.0: "EnterpriseUser":{"organization":"wso2"}
5.9.0-m4: "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"organization":"WSO2"}

Is this an expected behaviour?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
