### ISSUE TITLE
Invalid query params in OAuth error direction URL

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5982]
From the PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1118, the user is redirected back to the given redirect URI when an exception occurs( if the redirect URI and client id is valid). This is as to fix the issue reported in https://github.com/wso2/product-is/issues/5277

But now, when an exception happens, it is redirected back to the redirect URI, but the 
query params will be as oauthErrorCode and oauthErrorMsg. According to the specification the error message should be as follows,

- **error** - _REQUIRED_. Error code.
- **error_description** - _OPTIONAL_ Human-readable ASCII encoded text description of the error.
- **error_uri** - _OPTIONAL_ URI of a web page that includes additional information about the error.
- **state** -  OAuth 2.0 state value. _REQUIRED_ if the Authorization Request included the state parameter. Set to the value received from the Client.

**Comment by janakamarasena** [comment]
Ref issues:
https://github.com/wso2/product-is/issues/6273
https://github.com/wso2/product-is/issues/6280
