### ISSUE TITLE
Missing key-mappings for subscription configs in identity-event.properties

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6000]
Need key-mappings for the below configs.

identity_mgt.events.schemes.'account.lock.handler'.subscriptions
identity_mgt.events.schemes.'account.lock.handler'.properties.'notification.manageInternally
identity_mgt.events.schemes.emailSend.subscriptions
identity_mgt.events.schemes.accountConfirmationValidation.subscriptions
identity_mgt.events.schemes.passwordHistory.subscriptions
identity_mgt.events.schemes.'account.disable.handler'.properties.'notification.manageInternally
identity_mgt.events.schemes.userSelfRegistration.subscriptions
identity_mgt.events.schemes.userEmailVerification.subscriptions
identity_mgt.events.schemes.passwordPolicy.subscriptions
identity_mgt.events.schemes.adminForcedPasswordReset.subscriptions
identity_mgt.events.schemes.'suspension.notification'.subscriptions
identity_mgt.events.schemes.handleRequestObject.subscriptions
identity_mgt.events.schemes.'user.consent.delete'.subscriptions
identity_mgt.events.schemes.'user.consent.delete'.subscriptions
identity_mgt.events.schemes.authenticationAuditLogger.subscriptions

Tags:
Config

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
