### ISSUE TITLE
[Docs] TOML Configs required for Deployment Pattern 1

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6001]
Can you please list the corresponding TOML configs that are required for following Deployment Pattern 1 configs:

**<IS_HOME>/repository/conf/identity/embedded-ldap.xml**

- Config: 
```
<EmbeddedLDAP>
    <Property name="enable">false</Property>
<--------------------->
<EmbeddedLDAP> 
```
- Doc: Configuring the user store > Step 3

**<IS_HOME>/repository/conf/datasources/master-datasource.xml**
- Config:
-- Sample configuration of master-datasource.xml
-- Sample configuration of bps-datasources.xml 
- Doc: Configuring the datasource > Step 2 

**<IS_HOME>/repository/conf/registry.xml**
- Config: Sample configuration of registry.xml
- Doc: Mounting the registry > Para 1 and 2

**<IS_HOME>/repository/conf/registry.xml**
- Config: <versionResourcesOnChange>
- Doc: Mounting the registry > Note

**<IS_HOME>/repository/conf/axis2/axis2.xml**
- Config: enabling node - `<clustering class="org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent" enable="true">`
- Doc: Clustering Identity Server for high availability > Step 2.a

**<IS_HOME>/repository/conf/axis2/axis2.xml**
- Config: cluster name -  `<parameter name="domain">wso2.is.domain</parameter>`
- Doc: Clustering Identity Server for high availability > Step 2.b

**<IS_HOME>/repository/conf/axis2/axis2.xml**
- Config: WKA clustering method -  < parameter name = "membershipScheme" >wka</ parameter >
- Doc: Clustering Identity Server for high availability > Step 2.c

**<IS_HOME>/repository/conf/axis2/axis2.xml**
- Config: localMemberHost and localMemberPort entries
```
< parameter name = "localMemberHost" >127.0.0.1</ parameter >
< parameter name = "localMemberPort" >4000</ parameter >
```
- Doc: Clustering Identity Server for high availability > Step 2.d

**<IS_HOME>/repository/conf/axis2/axis2.xml**
- Config: hostName and port entries of WKA members
```
<members>
    <member>
      <hostName>127.0.0.1</hostName>
      <port>4000</port>
    </member>
    <member>
      <hostName>127.0.0.2</hostName>
      <port>4010</port>
    </member>
</members>
```
- Doc: Clustering Identity Server for high availability > Step 2.e 

**<IS_HOME>/repository/conf/user-mgt.xml**
- Config: datasource name
- Doc: Clustering Identity Server for high avaialability > Step 4.a

**<IS_HOME>/repository/conf/tomcat/catalina-server.xml**
- Config: node 1 proxy port 
- Doc: Changing hostnames and ports > Step 1

**<IS_HOME>/repository/conf/tomcat/catalina-server.xml**
- Config: Tomcat RemoteIPValve
```
<Valve
  className="org.apache.catalina.valves.RemoteIpValve"
  internalProxies="reg_ex_for_internal_docker_IPs"
  remoteIpHeader="x-forwarded-for"
  proxiesHeader="x-forwarded-by"
  protocolHeader="x-forwarded-proto"
/>
```
- Doc: Changing hostnames and ports > Step 1 > Tip

**<IS_HOME>/repository/conf/identity/sso-idp-config.xml**
- Config: service provider configuration for the dashboard
```
<AssertionConsumerServiceURLs><AssertionConsumerServiceURL>https://is.wso2.com/dashboard/acs</AssertionConsumerServiceURL></AssertionConsumerServiceURLs>
<DefaultAssertionConsumerServiceURL>https://is.wso2.com/dashboard/acs</DefaultAssertionConsumerServiceURL>
```
- Doc: Setting up the dashboard > step 1

**<IS_HOME>/repository/deployment/server/jaggeryapps/dashboard/conf/site.json**
- Config: proxyHost and proxyHTTPSPort
```
"proxyHost" : "is.wso2.com",
"proxyHTTPSPort" : "443",
```
- Doc: Setting up the dashboard > step 2

**<IS_HOME>/repository/deployment/server/webapps/shindig/WEB-INF/web.xml**
- Config: proxyHost and proxyHTTPSPort
```
"shindig.host" : "is.wso2.com",
"shindig.port" : "443",
```
- Doc: Setting up the dashboard > step 3

**<IS_HOME>/repository/conf/datasources/master-datasources.xml**
- Config: sample datasource configuration
- Doc: Setting up the dashboard > step 4

**<IS_HOME>/repository/conf/tomcat/catalina-server.xml**
- Config: proxy port in https connector
```
<Connector protocol="org.apache.coyote.http11.Http11NioProtocol"
    port="9443"
    proxyPort="443"    
```
- Doc: Configuring the proxy port in IS nodes > 1

**<IS_HOME>/repository/deployment/server/jaggeryapps/dashboard/conf/site.json**
- Config: proxy port and host
```
{
  "proxy":{
    "proxyHost":"nginx.mycomp.org"
    "proxyHTTPSPort":"443",
    "proxyContextPath":"",
    "servicePath":"/services"
  }    
}  
```
- Doc: Configuring the proxy port in IS nodes > 2

**<IS_HOME>/repository/deployment/server/jaggeryapps/portal/conf/site.json**
- Config: proxy port and host
```
{
  "proxy":{
    "proxyHost":"nginx.mycomp.org"
    "proxyHTTPSPort":"443",
    "proxyContextPath":""
  },
  "fido":{
    "appId":""
  }    
}
```
- Doc: Configuring the proxy port in IS nodes > 3

**<IS_HOME>/repository/deployment/server/webapps/shindig/WEB-INF/web.xml**
- Config: proxy port and host
```
<context-param>
    <param-name> system.properties </param-name>
    <param-value>
        <![CDATA[
    shindig.host=
    shindig.port=443
    aKey=/shindig/gadgets/proxy?container=default&url=
    ]]>
```
- Doc: Configuring the proxy port in IS nodes > 4

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
