### ISSUE TITLE
updating only the secondary user store domain user after changing the mapped attribute of scim id to username

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#6006]
1. Add a secondary user store called "secondary" and add a user called "user1" in primary and secondary user store domain.
2. Change the scim id's mapped attribute to user name.
3. If we want to update a value through scim for the user "secondary/user1" then at the moment there is no way to do this **or** if there is a way then it is not documented.

**Comment by JKAUSHALYA** [comment]
The attribute that is used for the SCIM id should be unique across the system according to the spec [1]. If it is changing from the default one. It should be guaranteed. 

[1] https://tools.ietf.org/html/rfc7643#section-3.1
