### ISSUE TITLE
SCIM2 patch operation fails when using urn:ietf:params:scim:schemas:extension:enterprise:2.0:User schema

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6015]
A change has been done in WSO2 IS 5.8.0 to be compliant with SCIM 2 specification regarding urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.

attributeName "EnterpriseUser" has been renamed to "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"

But the underlying code is not compatible with this change. AttributeName is not split well for PATCH operations.

curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"replace","path":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:employeeNumber","value": "xxx"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/673b0308-1473-4590-b1cd-dbfce642caa3

response before the fix:
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"noTarget","detail":"No such attribute with the name : urn:ietf:params:scim:schemas:extension:enterprise:2","status":"400"}

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
