### ISSUE TITLE
[DoC] Logging in to your application via Identity Server using Facebook Credentials is not up to date.

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6017]
Logging in to your application via Identity Server using Facebook Credentials documentation need to update with the new app registration mechanism in facebook.

 

https://docs.wso2.com/display/IS580/Logging+in+to+your+application+via+Identity+Server+using+Facebook+Credentials

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
