### ISSUE TITLE
Excluded  attributes are not coming in scim response but the values are getting updated

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#6018]
**Environment:- WUM updated wso2is-5.7.0 pack with embedded LDAP**

Execute the following curl command.

`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"replace","value":{"nickName":"nilasini3333"}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/d3bbed80-ee52-41d7-a195-9ccccc18de39?excludedAttributes=nickName`

Response is as follows:-
`{"emails":["nilasini@wso2.com"],"meta":{"created":"2019-07-25T14:41:44Z","lastModified":"2019-07-26T16:24:14Z"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"Internal/everyone"}],"name":{"givenName":"skjefjwf","familyName":"mathu"},"id":"d3bbed80-ee52-41d7-a195-9ccccc18de39","userName":"mathu"}`

But if I get the particular user I could see the nickName got updated with the patch operation but in the response, I couldn't able to see the nickName.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
