### ISSUE TITLE
Display account not activated reason in the claim for Identity Management Rest APIs

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#6019]
Hi All,

A user account can be locked or not activated due to different reasons.
1. Admin created an account not yet activated.
2. User-created account not yet activated and etc..
Therefore, we need to validate all the possible reasons and add the exact reason to the claim

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
