### ISSUE TITLE
Unauthorized error while following "Role Based Adaptive Authentication" example

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#6023]
When I was following [Role Based Adaptive Authentication](https://docs.wso2.com/display/IS580/Configuring+Role-Based+Adaptive+Authentication) example, It gives a `401 Unauthorized` error after entering the credentials to the web application.

**Note:** In the latest release of Identity Server, the following configuration has to be done **explicitly**, in order for the sample web application to work.
- **File:** ` <IS_HOME>/repository/resources/conf/templates/repository/conf/identity.xml.j2`
- **Parent Tag:**  `<ResourceAccessControl>`
- **Configuration that should be added inside the Parent Tag:**  `<Resource context="/sample-auth(.*)" secured="false" http-method="all"/>`
- **Reason:**  In the latest version of Identity Server, `<ResourceAccessControl> `has been set to `<ResourceAccessControl default-access="deny">`. Hence, this will deny access to any authentication endpoint by default.

** Above configuration should be documented as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
