### ISSUE TITLE
[UX] Self signup with REST API :User is getting an error message when click on confirmation link

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6027]
Self signup with REST API :User is getting an error message when click on confirmation link

tested product : **wso2is 5.8.0** GA and wso2is-5.9.0-m3
Step to Reproduce : 
1. Register a user using "Self Register user  REST API"
2. Click on confirmation link or "Confirm Account" button in your email.

Expected Result :  should display message "Successfully confirmed" and should navigate to dashboard screen
Actual Result : "Message : Invalid callback URL found in the request."

*note : this is issue does not occur when try with UI

Labels
Type: Bug
Priority: High
Severity : High
Component/s: identity-provider

![image](https://user-images.githubusercontent.com/39120228/62129173-b382c680-b2f3-11e9-8adf-3942d7b309f2.png)

**Comment by piraveena** [comment]
If you are using rest APi for self registration, either you can can remove callback in email-admin-config.xml file or give a callbackURL in properties.

**Comment by JKAUSHALYA** [comment]
Closing this as this is the expected behavior.
