### ISSUE TITLE
[UX] error page when attempting to re-use a used password reset code gives end-user an error number with no explanation

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#6029]
If a user attempts to re-use the link in an onboarding email, they will get a non-descriptive error page (see below).  Adding an option to re-send the email, or a message explaining that the user has already set their password, would be helpful for confused users

![Screen Shot 2019-07-30 at 2 25 22 PM](https://user-images.githubusercontent.com/1661988/62158802-e8802080-b2d5-11e9-9bdc-4a96711d9b92.png)

this issue is somewhat similar to #4875

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
