### ISSUE TITLE
Delare non secured subcontext within /api/users/v1 not supported

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#6033]
In ResourceAccessControl in identity.xml **_/api/users/v1_** has been declared as a secured context. However, it should be possible to declare a subcontext such as **_/api/users/v1/webauthn_** which is not secured. In that case, non secured **_/api/users/v1/webauthn_** should receive the precedence, but current implementation doesn't support this no matter what order you use.

**Comment by IsuraD** [comment]
This is already fixed with https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/81
