### ISSUE TITLE
hasMore() failed when having unprocessed continuation reference in AD

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-is#6035]
There is an issue when updating the password (Active Directory) of a user through the **doUpdateCredential()** and **doUpdateCredentialByAdmin()** methods. The reason is for this is, search results are having unprocessed continuation reference. Due to this, hasMore() throws a **javax.naming.PartialResultException** by skipping the process and user/ admin cannot update the password. 

We have checked the code and able to identify we have used "hasMore()" function in above methods in the search while loop. [1] However, most of the places we have used hasMoreElements() for the while loops. 

The different between hasMore() and hasMoreElements() is hasMoreElements() cannot throw exceptions. [2][3]

[1] - https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ActiveDirectoryUserStoreManager.java#L355
[2] - https://docs.oracle.com/javase/7/docs/api/javax/naming/NamingEnumeration.html
[3] - https://docs.oracle.com/javase/7/docs/api/java/util/Enumeration.html#hasMoreElements()

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
