### ISSUE TITLE
IsBulkImportSupported is enabled by default in user-mgt.xml

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6060]
$subject lead to show following in the Add User view, in the management console.

![bulk-import](https://user-images.githubusercontent.com/5061791/62299905-7d7c4880-b493-11e9-9811-ba6a38250c7d.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
