### ISSUE TITLE
Multi-attribute filtering support for SCIM2 group endpoint

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#6061]
SCIM2 multi attribute filtering for users is supported , but for groups this should be implemented.
Ex: filter with the group name and the last modified time
`filter=meta.lastModified gt "2011-05-13T04:42:34Z" and displayName sw "manager"`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
