### ISSUE TITLE
[DOC] There is no details for prerequisites

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6070]
Before access the REST API we have to enable configuration via Management console otherwise we are getting an error "Notification based password recovery is not enabled"

In this document does not mention the relevant configuration details.

Document - https://docs.wso2.com/display/IS580/apidocs/account-recovery/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
