### ISSUE TITLE
[DOC] It is not clear what value should be used as {"key": "[CONFIRMATION KEY]

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6071]
The problem is with the key parameter. It is not clear what value should be used as {"key": "[CONFIRMATION KEY] when trying to access Update Password REST API.

Document: https://docs.wso2.com/display/IS530/apidocs/account-recovery/index.html#!/operations#PasswordRecovery#setPasswordPost

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
