### ISSUE TITLE
405 status in consent revoke endpoint when accessed from a different origin even with a CORS filter

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#6074]
The consent revoke endpoint specified [here](https://docs.wso2.com/display/IS550/apidocs/Consent-management-apis/#!/operations#Consent#consentsReceiptsReceiptIdDelete) is giving a 405(Method Not Allowed) status when accessed from a different origin. 

I have the new user portal running on `localhost:9000` and I added following the CORS filter to the `api#identity#consent-mgt#v1.0/WEB_INF/web.xml` webapp in `Identity Server/repository/deployment/server/webapps/`.

```xml
<filter>
    <filter-name>CORS</filter-name>
    <filter-class>com.thetransactioncompany.cors.CORSFilter</filter-class>
    <init-param>
        <param-name>cors.allowOrigin</param-name>
        <param-value>https://localhost:9000</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>CORS</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```

**Comment by brionmario** [comment]
Adding the following `init-param` to the CORS filter, explicitly declaring the supported methods fixed the issue.

```xml
<init-param>
    <param-name>cors.supportedMethods</param-name>
    <param-value>GET, HEAD, POST, DELETE, OPTIONS</param-value>
</init-param>
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
