### ISSUE TITLE
Google Federation local claim mapping does not work properly.

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#6077]
We have configured a federation scenario with google using Google federation option with claim mapping and observed the following behavior. We could observe a claim mapping mismatch when we need to get the value of sub claim, we get the value of email claim instead. This can be observed in wso2-is 5.7.0 pack with latest wum version. The same scenario will work correctly when we use Oauth2/OpenID Connect configuration with the same claim mapping configurations.
 
Steps to recreate the issue: 

1)  Get the wso2is 5.7.0 pack with wum level 1564662300263.

2)  Configure an IDP using Google configuration under federated authenticators.

3)  Add http://wso2.org/claims/username as User ID Claim URI under basic claim configuration.

4) Configure the SP by adding a new SP.

5) Add the above configured IDP as the federated authenticator under Local and Outbound Authentication Configuration.

6) Add two Claim URIs  http://wso2.org/claims/username and  http://wso2.org/claims/emailddress under claim configuration of SP.

7) Test the scenario by sending a request to the SP application.
 
8) Get the id_token issued by the wso2is to the end user and decode it. Following can be observed at this step.
<img width="287" alt="Screen Shot 2019-08-06 at 3 26 20 PM" src="https://user-images.githubusercontent.com/47654317/62530834-e16d8b00-b85e-11e9-9fb5-20122faafbba.png">

9) Get the id_token issued by the google server and decode it. Then we can observe as follows.
<img width="305" alt="Screen Shot 2019-08-06 at 3 25 55 PM" src="https://user-images.githubusercontent.com/47654317/62530910-04983a80-b85f-11e9-8be7-5ddcf44b601f.png">

It is clear that google server return claims correctly but at the wso2- is side value of 'email' claim is set to value of 'sub' claim. It can be seen that the value of the "sub" claim is returned if and only if the value of the "email" claim is null according to the code implementation of GoogleOAuth2Authenticator.java class.

https://github.com/wso2-extensions/identity-outbound-auth-google/blob/v5.1.6/components/org.wso2.carbon.identity.application.authenticator.google/src/main/java/org/wso2/carbon/identity/application/authenticator/google/GoogleOAuth2Authenticator.java#L142

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
