### ISSUE TITLE
Replace log4j2.properties file in product IS

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6095]
**Problem**

- Currently, we maintain a different log4j2 file in the product-is. We need to take the log4j2.properties file from the kernel and then replace only the relevant values in the file.

**Suggested Labels**
- Kernel-4.5.0m4
- 5.9.0-M4

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
