### ISSUE TITLE
Cookie policy and Privacy Policy showing wrong IS version

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#6099]
Click on Cookie policy and  Privacy Policy  links 

![cookiepolicy](https://user-images.githubusercontent.com/20336761/62656154-337ae300-b929-11e9-9e90-a18415641d25.png)

You could see it is showing identity server 5.5.0 with identity server 5.7.0 pack. This issue may still exist in master. Please check and fix all the affected versions.

![cookie_policy](https://user-images.githubusercontent.com/20336761/62656308-818fe680-b929-11e9-8732-92935dd40005.png)

**Comment by janakamarasena** [comment]
Fixed in newer versions
