### ISSUE TITLE
Improvement : Hide the "Change password" gadget in the dashboard if the logged in user is from a Read Only user-store

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#6101]
Currently, the dashboard displays the "Change password" gadget even though the logged-in user is from a readonly user store. If the particular user tries to change the password, the user will get the following error hence the password cannot be updated in a readonly user store.

Since it's not user-friendly for allowing the readonly users to change the password at the first place and prompt an error later on, the requirement is to hide the "Change password" gadget if the user is from a readonly userstore.

![image](https://user-images.githubusercontent.com/20121821/62679126-244f7000-b9d1-11e9-8a58-63b8f71465b3.png)

**Comment by ruwanta** [comment]
This concern better be addressed in the new User portal based on ReactJS.
All user claims which comes from the user-store should be read only.
