### ISSUE TITLE
Set the SAML ACS url sent to a federated IDP per IDP

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#6103]
Hi All,

Currently, we can not set ACS Url per federated IdP. The ability to configure the "AssertionConsumerServiceURL" in the SAML AuthRequest is not supported per IdP in the OOTB wso2 identity server it would be great if we can add such improvement to the product. "AssertionConsumerServiceURL" was an optional parameter in the specification[1] which can be configured.

This improvement is nice to have feature in the identity server. Shall we provide such an improvement to the customer? WDYT?
 
[1] - https://docs.wso2.com/display/IS530/Configuring+SAML+2.0+Web+SSO  Fetch for "Configure ACL URL in a production environment"
[2] - Line number: 2062 in https://drive.google.com/file/d/1DDZFDEgz2dtQFW36rrBxViGU_EzUHzzW/view?usp=sharing

**Comment by rksk** [comment]
This is already done via https://github.com/wso2/product-is/issues/6925. But still, we don't have a tenant wise config. We only have system-wide config and per IDP config only.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
