### ISSUE TITLE
Storing device profiling in database instead of browser cookie

### ISSUE THREAD

**Issue by shubhkr1023** [wso2/product-is#6107]
Currently for adpative use case of WSO2 Identity Server(5.8.0), the device profiling details are saved in browser cookie. Is there a out of the box way to store it in WSO2 database/stand alone database and provision controls such as maximum no. of devices, restricted devices, etc. on it. Quick response from your side will be appreciated.

**Comment by shubhkr1023** [comment]
Anyone facing the same issue??? And how did you resolve it..???

**Comment by shubhkr1023** [comment]
Can anyone share any link for resolving this issue???

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
