### ISSUE TITLE
login.do is being used as callback of recovery flows

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6110]
Once a user clicks on forgot username/password links from login.do, the callback URL which is sent in the emailed recovery link is set to login.do as below.

```
    private String getRecoverPasswordUrl(String identityMgtEndpointContext, String urlEncodedURL) {
        return identityMgtEndpointContext + "/recoverpassword.do?callback=" + Encode.forHtmlAttribute(urlEncodedURL);
    }

String uri = (String) request.getAttribute(JAVAX_SERVLET_FORWARD_REQUEST_URI);
String prmstr = (String) request.getAttribute(JAVAX_SERVLET_FORWARD_QUERY_STRING);
String urlWithoutEncoding = scheme + "://" +serverName + ":" + serverPort + uri + "?" + prmstr;
String urlEncodedURL = URLEncoder.encode(urlWithoutEncoding, UTF_8);
```
```
<a id="passwordRecoverLink" href="<%=getRecoverPasswordUrl(identityMgtEndpointContext, urlEncodedURL)%>">
```

Therefore, at the end of the recovery flow, the user will be sent back to login.do with the sessionDataKey which represents the old authentication context. If that context is still valid, the user will be allowed to enter credentials and continue. 

IMO, we need to use relying party URL (application home page or another page where authentication flow starts from the beginning) here other than directly sending the user to the login page since there can be undesired outcomes such as https://github.com/wso2/product-is/issues/4539

For that, we may require to complete https://github.com/wso2/product-is/issues/5311 first

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
