### ISSUE TITLE
Remove config pattern "DEV"

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6111]
**Problem**
Remove the config pattern "DEV" and move the default configurations to the `deployment.toml `file. 

**Suggested Labels**

- Kernel-4.5.0m4
- 5.9.0-M5

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
