### ISSUE TITLE
Change "Shared_DB" name to "User_DB" in product-is

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6112]
Currently, we are getting the shared_db from the kernel which has user details and registry. The name "shared_db" is not meaningful in the product-is side. Hence need to replace the name to "user_db"

**Suggested Labels**

- Kernel-4.5.0m4
- 5.9.0-M5

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
