### ISSUE TITLE
[SCIM2] Incorrect error code when password policy is violated

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#6114]
During user creation, in case of user's password doesn't comply with the password policy the response is given as 500 with a generic error message.

We should fix it to return a proper status code and an error message.

The current response is as below,

```{

  "schemas": [

    "urn:ietf:params:scim:api:messages:2.0:Error"

  ],

  "detail": "Error while updating attributes of user: foo",

  "status": "500"

}```

**Comment by alrouen** [comment]
I've the same issue with IS 5.7.0

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/4145
