### ISSUE TITLE
registry_config_change.xml.j2 file is exposed in the product-is

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6115]
**Problem**
registry_config_change.xml.j2 file is used to add the specific configurations in the registry.xml related to the product -is. This file should not be packed in the product.

**Suggested Labels**

- Config
- 5.9.0-GA

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
