### ISSUE TITLE
Supporting Email or Mobile as the Preferred Communication Channel

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#6116]
## Issue
Currently IS supports different types of communication channels such as Email, SMS etc. for second-factor authentication, but not for account confirmation and notification paths. Account confirmation and notification paths only work with Email as the communication channel.

## Requirement
Supporting email or mobile as the preferred communication channel for the user based on user preference. The requirement needs to be implemented on account verification, account recovery and notification flows.
Communication channel on the above cases should be selected based on the following scenarios.

- SMS : If the user have provided only the mobile number.
- Email : If the user have provided only the email address.
- Either SMS or Email : If the user have provided both mobile and email. In this case communication channel should be the preferred channel selected by the specific user.

## User scenarios associated with Multiple Communication Channels

1. User self-registration and account confirmation
2. User account recovery (Username and Password recovery)
3. Notify on Failed Login Attempts
4. Account Suspension

## Identity / IT admin scenarios associated with Multiple Communication Channels

1. Onboard users with email based account verification and ask password
2. Forced Password Reset with OTP
3. Lock a user account with notifications
4. Disable a user account with notifications

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
