### ISSUE TITLE
Identity Provider OutBound Provisioning Role existence is not checked.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#6117]
When I was trying to add an Identity Provider OutBound Provisioning Role under the Role configuration section of an Identity Provider, it allows to add a role which is not existing. Before adding the Identity Provider OutBound Provisioning Role it is required to validate if such role is already existing. If the role is not available a proper error message should be generated for the user.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
