### ISSUE TITLE
Inconsistency in retrieving OAuthApplicationData using SOAP Admin Services

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6123]
- User having the Admin > Manage > Identity > Application Management > View   privileged role. And accessed the getOAuthApplicationDataByAppName and getOAuthApplicationData by consumer key. Even the user didn't create the SP user had the capability to get the App information by above to SOAP endpoints. 

- When the same user accessed getAllOAuthApplicationData it failed to provide all OIDC SP's. 

- When a user had the application role and if the sp havent been created by that user getAllOAuthApplicationData this SOAP endpoint failed to provide the SP details. even when the user has Admin > Manage > Identity > Application Management > View   privileged role.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
