### ISSUE TITLE
Cannot disable the checkbox in 'Use user store domain in roles' service provider

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#6128]
Issue:
When trying to disable 'Use user store domain in roles' from service provider level it always checked true.

Steps to reproduce to test the impact:
1. Create a user in secondary userstore
2. Create OAuth service provider
3. Uncheck user store domain in roles from SP level configurations
4. Configure roles as a requested claim
5. Get Id_token.

Sample request :
curl -v -X POST --basic -u ywa_5nzWYC62Fq5H4nTsMBdofrUa:YZLcctHWpVkr4ILEYFRAntuJskUa -H "Content-Type:application/x-www-form-urlencoded;charset=UTF-8" -k -d "grant_type=password&scope=openid&username=SECONDARY/hasanthi&password=admin" https://localhost:9443/oauth2/token

 Decoded id token extracted from the response
{
  "at_hash": "xSzR_ndDL84_W7YIsc76Cg",
  "aud": "ywa_5nzWYC62Fq5H4nTsMBdofrUa",
  "sub": "hasanthi",
  "nbf": 1565812187,
  "azp": "ywa_5nzWYC62Fq5H4nTsMBdofrUa",
  "amr": [
    "password"
  ],
  "iss": "https://localhost:9443/oauth2/token",
  "groups": [
    "SECONDARY/manager",
    "Internal/system",
    "Internal/everyone",
    "Application/PG"
  ],
  "exp": 1565815787,
  "iat": 1565812187
}
 

Expected result : SECONDARY/manager should be changed as manager in the response.

**Comment by denuwanthi** [comment]
https://github.com/wso2/product-is/issues/6124 duplicate
