### ISSUE TITLE
Templates not support to configure advanced mapping in event publishers

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#6129]
When publishing an event through identity event publisher we can use created template for configure the advance mapping to the event. Identity provider, it self has several email templates. Email publisher currently use the template among it to initiate the email body and send parameters.
 
I have tried to request soap endpoint within the event publishers with created template. Use the template body to add the payload with parameters. But for template not work for the added payload. 

**Steps to recreate:**
01. Create a new template from identity console.
02. Add the sample payload and parameters to the template.
![image](https://user-images.githubusercontent.com/39077751/62933864-c8c21f80-bde0-11e9-88bd-2e1e645b01d2.png)

Sample payload,
```
      <soapenv:Envelope
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.dataaccess.com/webservicesserver/">
        <soapenv:Header/>
        <soapenv:Body>
          <web:NumberToWords>
            <web:ubiNum>{{accountLock}}</web:ubiNum>
          </web:NumberToWords>
        </soapenv:Body>
      </soapenv:Envelope>
```
03. Create the publisher xml with the defined stream
Example for publisher xml
```
<?xml version="1.0" encoding="UTF-8"?>
<eventPublisher name="SoapPublisher" processing="enable"
  statistics="disable" trace="disable" xmlns="http://wso2.org/carbon/eventpublisher">
  <from streamName="id_gov_soap_output_notify_stream" version="1.0.0"/>
  <mapping customMapping="enable" type="xml">
    <inline>{{body}}</inline>
  </mapping>
  <to eventAdapterType="soap">
    <property name="url">http://webhook.site/35397daf-aacc-4f3e-8ace-a26e7c44fff0</property>
  </to>
</eventPublisher>
```
04. Add event configuration to the <IS_HOME>/repository/conf/identity/identity-event.properties
Sample configurations: 
```
module.name.13=default.notification.sender
default.notification.sender.subscription.1=POST_ACCOUNT_SUSPENSION
default.notification.sender.subscription.POST_ACCOUNT_SUSPENSION.stream=id_gov_soap_output_notify_stream:1.0.0
default.notification.sender.subscription.POST_ACCOUNT_SUSPENSION.claim.accountLock=http://wso2.org/claims/identity/accountLocked
default.notification.sender.subscription.POST_ACCOUNT_SUSPENSION.notification_template=soap
```
05. Configure the user suspension task and let the event get triggered. [1]

06. Validate the response receive. (Use [2] for get the response for validation)

**Expected result:**
Should receive successful response.

**Actual result:** 
Successful response not received. 

[1] https://docs.wso2.com/display/IS570/User+Account+Suspension
[2] https://webhook.site

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
