### ISSUE TITLE
[TOML Configus] TenantDomainDropDownEnabled in application-authentication.xml 

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6133]
Please provide the corresponding TOML configs for the `TenantDomainDropDownEnabled` in `<IS_HOME>/repository/conf/identity/application-authentication.xml`. 

Sample config: 
```
<TenantDomainDropDownEnabled>true</TenantDomainDropDownEnabled>
        <TenantDataListenerURLs>
            <TenantDataListenerURL>
                /authenticationendpoint/tenantlistrefresher.do
            </TenantDataListenerURL>
        </TenantDataListenerURLs>
```

ref: https://docs.wso2.com/display/IS580/Customizing+the+Authentication+Endpoint

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
