### ISSUE TITLE
[5.9.0-m7] user-portal always redirected to the default IS port (9443)

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#6134]
In 5.9.0-M7 the portal app is always trying to redirect to 9443 port. 

![port](https://user-images.githubusercontent.com/20336761/63123772-6186a580-bf6f-11e9-8a55-0e499f6a4a1d.png)

Steps to reproduce.

1. Start IS with port offset 1
2. go to  "https://localhost:9444/user-portal/login"
3. You will be redirected to Identity server with port 9443

Ideally, you should be redirected to the identity server with port 9444.

**Comment by madurangasiriwardena** [comment]
I could not observe this error anymore. However, if the port number is changed after the initial startup, I could observe [this](https://github.com/wso2/product-is/issues/7588) issue.
