### ISSUE TITLE
username recovery flow throws 'Server failed to respond.' error for invalid tenant.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#6135]
Issue : 
Identity Server username recovery flow throws **Server failed to respond.** message in the UI when non existing tenant domain is given in the username recovery UI.
![Screenshot from 2019-08-16 10-32-04](https://user-images.githubusercontent.com/11774310/63144601-58e6ab80-c011-11e9-9776-d98d79eeeae6.png)
![Screenshot from 2019-08-16 10-33-15](https://user-images.githubusercontent.com/11774310/63144631-774ca700-c011-11e9-9a09-a5c622feb441.png)
Should display a more descriptive error message in the UI.

Also, backend prints an error stack trace upon this. This should also be handled in a nicer way.
`[2019-08-16 10:19:42,892] ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} -  Could not handle request: /t/cceccrec/api/identity/recovery/v0.9/recover-username/
org.wso2.carbon.identity.base.IdentityRuntimeException: Invalid tenant domain cceccrec
...`

Steps to reproduce.
1. Enable notification based username recovery from mgt console.
2. Go to dashboard and select forgot username.
3. Provide a wrong tenant domain and proceed.
4. Observe the UI and back end errors.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
