### ISSUE TITLE
OIDC logout does not terminate user session when remember me is used and browser is restarted

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6140]
**Steps to reproduce**
1. Log in to an OIDC sp with "remember me" ticked
2. Close the browser and re-open it 
3. Try OIDC logout at first
4. Logout will be failed due to missing obps cookie, but it will show as a success if we have enabled "HandleAlreadyLoggedOutSessionsGracefully"
5. Then try to SSO into a SP, it will SSO the user seamlessly

**Explanation**
When we tick "Remember me", the "commonAuthId" cookie becomes a persistent cookie. Still, the obps is a session cookie. Therefore, when we restart the browser, "commonAuthId" is still remaining but obps is gone.

If we try an OIDC logout just after opening the browser, it will display as a successful logout if we have enabled "HandleAlreadyLoggedOutSessionsGracefully". But the "commonAuthId" is still valid and not cleared from the browser. Now, if we try to SSO, it will be successful even though previously user has seen a successful logout.

This happens because, if the obps cookie is missing we are just showing the success message to the user. Do not think about "commonAuthId" [1], [2].

This is an edge case, but the users may be left confused.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/servlet/OIDCLogoutServlet.java#L124
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/servlet/OIDCLogoutServlet.java#L697

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
