### ISSUE TITLE
Need to have an option in the management console UI to download public certificate of the Identity Server

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#6148]
Currently, in order to get the public certificate of the super tenant, we have to access the file system and use the `keytool` command. It is better to have a UI option as well to support the users who don't have access to the file system.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
