### ISSUE TITLE
Error can be seen while trying to upload a certificate from management console.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#6149]
Steps to reproduce:

1. Login to the super tenant and navigate to `Home > Manage > Keystores > List`
2. Click on View icon of wso2carbon.jks
3. Go to the second page
4. Click on the `Import Cert` button at the top.

You can see the following error.

Error in managment console:
<img width="354" alt="Screen Shot 2019-08-19 at 3 42 11 PM" src="https://user-images.githubusercontent.com/1498339/63257812-3a461600-c298-11e9-9db6-689bcec6b8ec.png">

Error in wso2carbon.log:
`[2019-08-19 15:33:12,030] ERROR {org.wso2.carbon.security.keystore.KeyStoreAdmin} -  Error has encounted while loading the keystore to the given keystore name null
org.wso2.carbon.security.SecurityConfigException: Key Store not found
	at org.wso2.carbon.security.keystore.KeyStoreAdmin.getKeystoreInfo(KeyStoreAdmin.java:522)
	at org.wso2.carbon.security.keystore.service.KeyStoreAdminServiceImpl.getKeystoreInfo(KeyStoreAdminServiceImpl.java:83)`

**Comment by emswbandara** [comment]
cannot reproduce in 5.9.0-m8-Snapshot
