### ISSUE TITLE
MSSQL IDN_ARTIFACT_STORE table does not get created

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6153]
**Environment**
Windows 2016 server
MSSQL
IS 5.9.0-m8- snapshot

**Suggested Lables**
Type/Bug
Priority/High

**Steps to Reproduce**

Execute the script in below location against MSSQL 

wso2is-5.9.0-m8-SNAPSHOT/dbscripts/identity/mssql.sql

The table with the name IDN_ARTIFACT_STORE is not getting created.

**Comment by emswbandara** [comment]
In MSSQL script, table creation checks for the existence of SP_AUTH_SCRIPT table. Instead it should be IDN_ARTIFACT_STORE

IF NOT EXISTS(SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[SP_AUTH_SCRIPT]') AND TYPE IN (N'U'))
CREATE TABLE IDN_ARTIFACT_STORE (
