### ISSUE TITLE
at_hash and c_hash claims missing in id_token in OIDC hybrid flow

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#6161]
Steps to reproduce:

    Setup OIDC Hybrid flow (https://docs.wso2.com/display/IS560/OpenID+Connect+Hybrid+Flow)
    Try the code id_token flow
    Check the received id_token
    at_hash and c_hash claims will be missing which breaks the clients expecting it.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
