### ISSUE TITLE
Adding Local Claims fails against Windows Internet Explorer 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6164]
**Environment** 
Windows Server 2016
JDK 1.8
Browser - Internet Explorer

**Suggested Labels**
Type/Bug
Priority/ High
Affected/ IS 5.9.0 M8 Snapshot

**Steps to Reproduce**

1. Navigate to Claims > Add > Add Local Claim
2. Give the necessary details
3. Click on Add button with Internet Explorer Browser

Claim will not get add and when inspect the operation with the browser it shows the below error.

Object doesn't support property or method 'includes'
Line no 786
add-local-claim.jsp

Related code for the above issue is as follows

```
if (!attributeArr.includes(combinedValue)) {
                                         attributeArr.push(combinedValue);
                                    }



```

**Comment by piraveena** [comment]
Could not reproduce it with IS5.9.0-alpha and alpha3 packs.
