### ISSUE TITLE
"ConfigParserException" when try to start Identity Server 5.9 as windows Service (Java Version: 1.8)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6165]
Affected version: wso2is-5.9.0-m8
Severity: High
Priority: High
Type: Bug
*Please consider both issue 1 & 2
**Issue 1:**
Test Environments: OS- Windows,  Java Version: 1.8.0_221,
"Running the product in console mode" fails with the following error.

NFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|[2019-08-20 19:43:25,592] ERROR {org.wso2.carbon.server.Main} -  Error while performing configuration changes
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|org.wso2.carbon.nextgen.config.ConfigParserException: Template directory (C:\is\wso2is-5.9.0-m8-SNAPSHOT\wso2is-5.9.0-m8-SNAPSHOT\null\templates) does not exist or is not a directory
INFO|wrapper|"WSO2 Carbon"|19-08-20 19:43:25|Trigger found: Exception in line:
INFO|wrapper|"WSO2 Carbon"|19-08-20 19:43:25|org.wso2.carbon.nextgen.config.ConfigParserException: Template directory (C:\is\wso2is-5.9.0-m8-SNAPSHOT\wso2is-5.9.0-m8-SNAPSHOT\null\templates) does not exist or is not a directory
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at org.wso2.carbon.nextgen.config.ConfigParser.checkTemplateDirExistence(ConfigParser.java:269)
INFO|wrapper|"WSO2 Carbon"|19-08-20 19:43:25|start script scripts/trayMessage.gv
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at org.wso2.carbon.nextgen.config.ConfigParser.backupConfigurations(ConfigParser.java:166)
INFO|wrapper|"WSO2 Carbon"|19-08-20 19:43:25|end script scripts/trayMessage.gv
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at org.wso2.carbon.nextgen.config.ConfigParser.deployAndStoreMetadata(ConfigParser.java:176)
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at org.wso2.carbon.nextgen.config.ConfigParser.parse(ConfigParser.java:125)
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at org.wso2.carbon.server.Main.handleConfiguration(Main.java:240)
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at org.wso2.carbon.server.Main.main(Main.java:99)
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|2648/5|"WSO2 Carbon"|19-08-20 19:43:25|    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Solution** 
It should be corrected as follows.
in wrapper.conf (<PRODUCT_HOME>/bin/yajsw/)
add a new line, 
wrapper.java.additional.30 = -Dcarbon.new.config.dir.path=${carbon_home}\\repository\\resources\\conf

**Issue 2**

With this, we can fix the above-mentined issue, but  we have another issue because of removing the "endorsed" folder (<PRODUCT_HOME>\lib)

Server startup fails with the following error.

FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|[2019-08-20 20:28:47,254] FATAL {org.wso2.carbon.tomcat.internal.TomcatBundleActivator} -  Error while starting server org/apache/xerces/util/SecurityManager
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|java.lang.NoClassDefFoundError: org/apache/xerces/util/SecurityManager
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.tomcat.internal.ServerManager.getSecuredDocumentBuilder(ServerManager.java:269)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.tomcat.internal.ServerManager.inputStreamToDOM(ServerManager.java:225)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:108)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at java.security.AccessController.doPrivileged(Native Method)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.Module.doStart(Module.java:581)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.Module.start(Module.java:449)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|Caused by: java.lang.ClassNotFoundException: org.apache.xerces.util.SecurityManager cannot be found by org.wso2.carbon.tomcat_4.5.0.m2
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|Trigger found: Exception in line:
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|Caused by: java.lang.ClassNotFoundException: org.apache.xerces.util.SecurityManager cannot be found by org.wso2.carbon.tomcat_4.5.0.m2
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|start script scripts/trayMessage.gv
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:398)
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|end script scripts/trayMessage.gv
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  ... 20 more
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|[2019-08-20 20:28:47,430] ERROR {org.wso2.carbon.user.core.internal.Activator} -  Cannot start User Manager Core bundle
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|java.lang.NoClassDefFoundError: org/apache/xerces/util/SecurityManager
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.utils.CarbonUtils.getSecuredDocumentBuilder(CarbonUtils.java:1329)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.utils.CarbonUtils.replaceSystemVariablesInXml(CarbonUtils.java:1094)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.user.core.common.DefaultRealmService.getConfigurationElement(DefaultRealmService.java:307)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.user.core.common.DefaultRealmService.buildBootStrapRealmConfig(DefaultRealmService.java:133)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:86)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at java.security.AccessController.doPrivileged(Native Method)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.Module.doStart(Module.java:581)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.Module.start(Module.java:449)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|Caused by: java.lang.ClassNotFoundException: org.apache.xerces.util.SecurityManager cannot be found by org.wso2.carbon.utils_4.5.0.m2
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|Trigger found: Exception in line:
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|Caused by: java.lang.ClassNotFoundException: org.apache.xerces.util.SecurityManager cannot be found by org.wso2.carbon.utils_4.5.0.m2
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|start script scripts/trayMessage.gv
INFO|wrapper|"WSO2 Carbon"|19-08-20 20:28:47|end script scripts/trayMessage.gv
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:398)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
FINEST|4644/0|"WSO2 Carbon"|19-08-20 20:28:47|  ... 24 more

**Solution** 
By adding a new line we fix this  -in wrapper.conf (<PRODUCT_HOME>/bin/yajsw/)

**wrapper.java.classpath.4 = ${carbon_home}\\lib\\*.jar**

**Comment by SwatiNEC** [comment]
Hi

I am also facing the same issue. I have also make changes which you mentioned above. But even after applying these changes I am still facing the same issue. Could you please help me in this.

**Comment by NilukaSripalim** [comment]
Hi @SwatiNEC , could you please share your updated .sh file and WSO2 identity server version

**Comment by SwatiNEC** [comment]
Hu @NilukaSripalim , I have updated the wrapper.conf as mentioned above. And I am using latest version of wso2 identity server and I am running this setup on windows.
