### ISSUE TITLE
Missing toml configs for identity-mgt.properties properties

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#6169]
In doc[1], 
`Authentication.Policy.Account.Lock.Time=5`

In doc[2], 
```
"UserInfoRecovery.UseHashedUserNames=true
UserInfoRecovery.UsernameHashAlg=SHA-1"
```
Reference docs,
[1] https://docs.wso2.com/display/IS580/Account+Locking+by+Failed+Login+Attempts
[2]https://docs.wso2.com/display/IS580/Using+Email+Address+as+the+Username

**Comment by BradNut** [comment]
@hasinidilanka @sachiniWettasinghe Are the feature sets available in the identity-mgt.properties file able to be implemented in the deployment.toml file?

The above comment "This file is deprecated therefore no need to template." and linked issue comment "identity-mgt.properties file will not be templated as it is decided to deprecate this file from the product." provide no useful insight into what is replacing those properties when converting to a deployment.toml file.

For example [Writing a Custom Password Validator](https://is.docs.wso2.com/en/latest/develop/writing-a-custom-password-validator/#writing-the-custom-password-policy) just states at the top "These instructions will be deprecated.".

What will replace custom password policies and extension so they can be utilized in the deployment.toml?

**Comment by BradNut** [comment]
@sachiniWettasinghe @IsuraD Is there any status on this given it's an open ticket since 2019.....?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
