### ISSUE TITLE
Tenant's secondary user store not loaded if the LDAP was unavailable upon tenant loading

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#6171]
Tenant's secondary user store is not loaded if the LDAP was not available when the tenant was loaded. Even if the LDAP is up and running later, the user store won't be loaded until the tenant in reloaded.

Steps to reproduce.
1. Create a tenant and create a secondary LDAP user store there.
2. Make the LDAP unavailable.
3. Try to login to the tenant's user who resides in the unavailable LDAP.
4. Secondary user store initialization will fail.
5. Make the LDAP available again.
6. Try to login with the same user. This will also fail, despite now that the LDAP is up and running.
7. If you disable and enable the particular user store, this will be started to work again.

IS 5.2.0 only try the LDAP upon the tenant loading. This should be fixed to do on demand.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
