### ISSUE TITLE
Circuit breaker for LDAP re connectivity attempts

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#6176]
If the LDAP connectivity was failed for a particular user store in the Identity Server, 2 reattempts will be made in the same flow. This will be repeated for any further requests as well. (But this is unnecessary as the LDAP won't be up and running if we tried immediately after.)

Need to implement a circuit breaker pattern to avoid any immediate successive attempts upon receiving requests. This should be a **configurable** wait time before making any further connection attempts to that LDAP server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
