### ISSUE TITLE
Error occurred when manually sourcing the Oracle sql script

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6177]
Enviornment
DB - Oracle 12.
wso2is-5.9.0-alpha pack

Priority: High
Severity: Medium

Steps:
Took the latest oracle script 
Source that oracle  (/wso2is-5.9.0-alpha/dbscripts)

**Error**
Error starting at line : 783 in command -
CREATE INDEX SYSTEM_ROLE_IND_BY_RN_TI ON UM_SYSTEM_ROLE(UM_ROLE_NAME, UM_TENANT_ID)
Error report -
ORA-01408: such column list already indexed
01408. 00000 -  "such column list already indexed"
*Cause:    
*Action:

Error starting at line : 783 in command -
CREATE INDEX REG_PATH_IND_BY_PATH_VALUE ON REG_PATH(REG_PATH_VALUE, REG_TENANT_ID)
Error report -
ORA-01408: such column list already indexed
01408. 00000 -  "such column list already indexed"
*Cause:    
*Action:

**Comment by senthalan** [comment]
https://github.com/wso2/carbon-kernel/blob/4.5.x/distribution/kernel/carbon-home/dbscripts/oracle.sql#L32-L41

We need to remove the index REG_PATH_IND_BY_PARENT_ID as we already have the unique constraint for (REG_PATH_PARENT_ID, REG_TENANT_ID)

**Comment by madurangasiriwardena** [comment]
Need to close the issue once the kernel version is updated.
