### ISSUE TITLE
Need to refactor idp-mgt-edit.jsp

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#6185]
With the tomcat 9 update, the following error is thrown when loading the idp-mgt-edit.jsp,
```The code of method _jspService(HttpServletRequest, HttpServletResponse) is exceeding the 65535 bytes limit```

The tomcat discussion says (https://bz.apache.org/bugzilla/show_bug.cgi?id=60126) "The changelog for 8.0.37 mentions a number of changes in Jasper around error handling that will have increased the volume of the auto-generated code Jasper creates."

Our idp-mgt-edit.jsp page has more than 6000 lines, Adding more jsp codes will break this page we need to refactor this class.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
