### ISSUE TITLE
JS Functions, Getting current tenant domain by context instead of threadlocal and MultiAttributeSeperator always overriden by DefaultClaimHandler

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#6188]
Resolves https://github.com/wso2/carbon-identity-framework/issues/2377
Resolves https://github.com/wso2/carbon-identity-framework/issues/2379

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
