### ISSUE TITLE
Getting "401" error when export the tenant public certificate

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6193]
Affected Version: wso2is-5.9.0-m8 pack
Priority: Medium
Severity: Low

Steps to Reproduce   :
1. 1. Login to Identity Server with admin/admin credentials
2. Go to Configure Tab > Add New Tenant
3. Navigate to "Home > Manage > Keystores > List"
4. Click on public-key link

2. Same issue when try to "Download" ( /_system/governance/repository/security/key-stores)

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2392
