### ISSUE TITLE
Unable to delete selected user association

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#6195]
### Description
When trying to delete a selected user account association by sending a DELETE request to **https://localhost:9443/api/users/v1/me/associations** through postman it deletes all the user account associations for the currently authenticated user. There are two behaviours noticed when trying to add a user account association again after deletion.

**Scenario 01** -  Add the deleted user account association again and send a GET request again to the same endpoint. This returns all the previously added associations.

**Scenario 02** - Add a completely new user account association and send a GET request to the same endpoint. This will not return the previously added associations.

### Steps to reproduce Scenario 01

1. GET user account associations
```
Path: https://localhost:9443/api/users/v1/me/associations
Method: GET

Sample response:
[
    {
        "userId": "nipunib",
        "username": "nipunib",
        "userStoreDomain": "PRIMARY"
    },
    {
        "userId": "nipuni-google",
        "username": "nipuni-google",
        "userStoreDomain": "PRIMARY"
    }
]

```

2. Send a DELETE request to the association endpoint

```
Path: https://localhost:9443/api/users/v1/me/associations
Method: DELETE
Params: associate-associate-user-id

Sample: https://localhost:9443/api/users/v1/me/associations?associate-user-id=nipunib

Response: 204 

```
3. Send a GET request to the same endpoint

```
Path: https://localhost:9443/api/users/v1/me/associations
Method: GET

Response:
[] (Returns an empty array. Ideally this should return the association with id nipuni-google)

```
4. Add new associated user account with the deleted user-id

```
Path: https://localhost:9443/api/users/v1/me/associations
Method: POST
Sample request body:
{
  "userId": "nipunib",
   "password": "1234",
   "properties": [
          {
            key: "string",
            value: "string"
          }
     ]
}

```
5. Send a GET request to the same endpoint

```
Path: https://localhost:9443/api/users/v1/me/associations
Method: GET

Sample response:
[
    {
        "userId": "nipunib",
        "username": "nipunib",
        "userStoreDomain": "PRIMARY"
    },
    {
        "userId": "nipuni-google",
        "username": "nipuni-google",
        "userStoreDomain": "PRIMARY"
    }
]

```
### Steps to reproduce Scenario 02

4. Repeat the steps 1 - 3 in **scenario 01** and in the 4th step try adding a new account as an associated account.

```
Path: https://localhost:9443/api/users/v1/me/associations
Method: POST
Sample request body:
{
  "userId": "nipunip",
   "password": "pa1234",
   "properties": [
          {
            key: "string",
            value: "string"
          }
     ]
}

```
5. Send a GET request to the association endpoint

```
Path: https://localhost:9443/api/users/v1/me/associations
Method: GET

Sample response:
[
    {
        "userId": "nipunip",
        "username": "nipunip",
        "userStoreDomain": "PRIMARY"
    }
]

```

**Comment by IsurangaPerera** [comment]
Issue will be closed as this is the expected behavior at the moment
