### ISSUE TITLE
Invalid mandotory field validation when adding a consent purpose

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6196]
**Suggested Labels**
Priority/Normal
Severity/Major
Affected/5.9.0-m8-snapshot

**Steps to Reproduce**
1. Login to the management console 
2. Manage > Consent Purposes > Add 
3. Add the consent purpose by filling only the mandatory fields Purpose Name , Purpose Group Type without filling the mandatory field Associated Flow 
4. Click on Finish 

Observation

UI will show a invalid message as Purpose group is not filled

![imageedit_2_4167052105](https://user-images.githubusercontent.com/31848014/63683910-52c6ab00-c819-11e9-8588-e42449f2883f.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
