### ISSUE TITLE
Removing the mapped attribute of the PRIMARY user store should be restricted

### ISSUE THREAD

**Issue by NipunaPrashan** [wso2/product-is#6202]
In general, every user store should have its own mapped attribute configured for a given claim.

But the UI, or the back end does not do this validation.

Nonetheless, it not even blocking to remove the mapped attribute for PRIMARY. And if somebody removes the mapped attribute for PRIMARY, it won't be able to do any claim handling not only for PRIMARY but also for other user stores which does not have specific mapped attribute setting.

Should have a UI\Backend validation to avoid user errors

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
