### ISSUE TITLE
Required claims needs to be validated at API layer based on scenario

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6204]
**Problem:**
We have several identity management features where notifications will be triggered internally for the user confirmation
- self registration
- ask password, etc.

In these, it's mandatory for a valid email claim to present (may be it can be some other claim based on notification requirements).
But, in the present implementation the availability of the claim that is required to initiate the notification is only validated at the notification initiation level (notification handler which listens for TRIGGER_NOTIFICATION event, or may in a particular handler which listens for pre or post user operation events and decide whether to trigger a notification).
Failures in this level are reflected back to the API as server errors. Therefore, by design there is a limitation on denoting user errors like above as a _'user error'_ from the API level.

**Suggested Approach:**
The approach that I think of implementing this is, based on the scenario, attributes that needs to be mandated should be flagged as 'required' in claim management.
Then, there should a claim validation layer that validates for mandatory attributes. That layer can be then extended to many other meta attribute validations.
This requires re-designing the present implementation we have

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
