### ISSUE TITLE
[Doc] Should document mandatory params for identity management APIs on initiating notifications based on scenarios

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6205]
Due to the present design problem of reflecting user errors as mandatory claims are missing to serve a request based on a scenario as mentioned at https://github.com/wso2/product-is/issues/6204, we need to clearly document, which claims are expected in input for the respective API to function as expected.
In addition, we need to document a trouble shooting guide based on scenarios, 
- highlighting most common configuration errors that comes in the development stage, 
-  highlighting most common runtime errors that comes in the production stage,

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
