### ISSUE TITLE
Need to add CORS filter for REST API swagger docs

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#6206]
**Description:**
The REST APIs don't generate a response and causes an error in swagger UI without the following cors filter configuration. To resolve this issue this config needs to be added into the <IS_HOME>/repository/deployment/client/webapps/WEBINF/web.xml file. 
```
    <filter>
      <filter-name>CORS</filter-name>
      <filter-class>com.thetransactioncompany.cors.CORSFilter</filter-class>
      <init-param>
          <param-name>cors.allowOrigin</param-name>
          <param-value>http://127.0.0.1:8000</param-value>
      </init-param>
       <init-param>
          <param-name>cors.supportedMethods</param-name>
          <param-value>GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH</param-value>
      </init-param>
  </filter>
  <filter-mapping>
      <filter-name>CORS</filter-name>
      <url-pattern>/*</url-pattern>
      <dispatcher>FORWARD</dispatcher>
      <dispatcher>REQUEST</dispatcher>
  </filter-mapping>
```

Additionally, the following resource needs to be added to the identity.xml and identity.xml.j2 files.

```
<Resource context="(.*)/api/users/v1/me/(.*)/(.*)/(.*)" secured="true" http-method="GET,POST,PUT,PATCH,DELETE">
<Permissions>/permission/admin/login</Permissions>
</Resource>
```

**Affected Product Version:**

5.9.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
