### ISSUE TITLE
[DOC] missing details in Basic security policy scenarios from the view scenario option.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6207]
Priority: Low
Severity: Low
Related document: https://docs.wso2.com/display/IS580/Configuring+WS-Trust+Security+Token+Service

Step to reproduced: 
Inbound Authentication Configuration section, click Security Token Service Configuration > Apply Security Policy.

Select Yes in the Enable Security?

Click on view scenario option.

Should be added details for 1- 4 Basic scenarios

![image](https://user-images.githubusercontent.com/39120228/63762724-ee6f1e80-c8e0-11e9-8b1c-1cb58af43c3d.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
