### ISSUE TITLE
Adding response time to access log valve

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#6209]
When troubleshooting a slowness of a deployment which has WSO2 IAM, in order to narrow down the component which is responding slow, it is a general practice to print the time taken to process a request.

This is done by changing the configurations of the AccessLogValve of repository/conf/tomcat/catalina-server.xml 

It would be a good idea to ship this configuration by default.

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/product-is/pull/6215/

**Comment by rksk** [comment]
@ayshsandu I don't see anything related to this issue in https://github.com/wso2/product-is/pull/6215 rather than adding some test cases.

**Comment by rksk** [comment]
> @ayshsandu I don't see anything related to this issue in #6215 rather than adding some test cases.

I think it is https://github.com/wso2/product-is/pull/6211
