### ISSUE TITLE
Adding the thread id to the wso2carbon.log log appender

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#6210]
When it comes to troubleshooting a flow which is used concurrently having the thread id in logs is very useful. 

Can we please add the thread id to the wso2carbon.log appender?

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2/product-is/pull/6215/
Instead of ThreadID, correlation-ID will be added in the log.

**Comment by rksk** [comment]
@ayshsandu I don't see anything related to this issue in https://github.com/wso2/product-is/pull/6215 rather than adding some test cases.

**Comment by rksk** [comment]
> @ayshsandu I don't see anything related to this issue in #6215 rather than adding some test cases.

I think it is https://github.com/wso2/product-is/pull/6211
