### ISSUE TITLE
Consent is not shown for the requested claims in Request object flow

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6212]
Steps to reproduce:

- Configure some claims under service provider claim configs.
- Make a authorization code flow or implicit flow.
- You will get consent for the claims requested under service provider.
- Add the claims that are requested via request object under claim config.
- Try request object flow.

Now you won't get consent for the claims that are requested via request object.
- If you check the id_token obtained for request object flow, it won't have the claims that are requested via request object

This breaks the request object flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
