### ISSUE TITLE
No response is sent after metadata file is uploaded to configure saml sso(Inbound Authentication Configuration)

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#6219]
**Description:**
During the process of configuring SAML SSO to a service provider by uploading a metadata file, the file does not get uploaded (request is sent to [https://localhost:9443/fileupload/service?X-CSRF-Token=QIJH-SG3F-4762-07F2-1FHH-N3LM-T4T5-L1V2](https://localhost:9443/fileupload/service?X-CSRF-Token=QIJH-SG3F-4762-07F2-1FHH-N3LM-T4T5-L1V2) but no response is given back). So what you basically see is a blank page as mentioned below : 

![Screenshot from 2019-08-28 12-41-27](https://user-images.githubusercontent.com/33062368/63833661-351c5180-c991-11e9-9c5b-596274275289.png)   

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
WSO2IS-5.9.0-M7

**Steps to reproduce:**
1. Register a service provider with a name.
2. Go to Inbound Authentication Configuration -> SAML2 Web SSO Configuration -> Configure.
3. Select Metadata File Configuration.
4. Upload the below sp-metadata.xml file which is from product-is : [https://github.com/wso2/product-is/blob/master/modules/integration/tests-integration/tests-backend/src/test/resources/artifacts/IS/saml/sp-metadata.xml](https://github.com/wso2/product-is/blob/master/modules/integration/tests-integration/tests-backend/src/test/resources/artifacts/IS/saml/sp-metadata.xml)

**Comment by madurangasiriwardena** [comment]
In the browser trace, I can see a 401 response

```
POST https://localhost:9443/fileupload/service?X-CSRF-Token=PXLJ-JNV2-WIEQ-TPSR-W7HG-S275-J1V0-OACJ HTTP/1.1
Origin: https://localhost:9443
Upgrade-Insecure-Requests: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryIpzAxuxdSQAXssJm
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3

HTTP/1.1 401
WWW-Authenticate: realm user=""
Transfer-Encoding: chunked
Date: Wed, 28 Aug 2019 09:23:24 GMT
Server: WSO2 Carbon Server
```

**Comment by mefarazath** [comment]
Could be a result of https://github.com/wso2/product-is/issues/5907

**Comment by ayshsandu** [comment]
> Could be due to changes done in #5907

Yes. Once the relavent permissions are added as in https://github.com/wso2/carbon-identity-framework/pull/2392, behaviour works as expected.
