### ISSUE TITLE
[windows] [jdk 11]  Server startup with ERROR log Adapter polling failed as EventReceiverManagementService not available

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6228]
**Suggested Labels**
Type/Bug
Affected/IS5.9.0-Alpha
Priority/High
Severity/major

**Environment Details** 
JDK 11.0.4
Windows 2016 server
Pack - IS5.9.0-alpha
DB MSSQL 
Userstore Embedded LDAP

**Steps to Reproduce**
At the server startup in windows instance against jdk 11 observed the below ERROR log getting printed.

`[2019-08-29 12:12:38,334] [] ERROR {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} - Adapter polling failed as EventReceiverManagementService not available`

**Comment by ShanikaWickramasinghe** [comment]
Observed this ERROR log against Ubuntu 16.04 jdk 8 as well

**Comment by senthalan** [comment]
Duplicate of https://github.com/wso2/product-is/issues/6189
