### ISSUE TITLE
UI capability to add tenant wise configuration Email Sender for email notifications

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6231]
When fixing the https://github.com/wso2/product-is/issues/6230 as in future releases we are discontinuing file-based configurations. There should be UI capability to add those configurations related to the corresponding tenant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
