### ISSUE TITLE
Unable to define an order config entries in ResourceAccessControl section in identity.xml via deployment.toml

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6233]
Authentication and Authorization for endpoints defined under ResourceAccessControl section in identity.xml, highly depend on the order of the enties defined.

If a customer needs to define access control for a custom endpoint, that needs precedence over existing access control, unable to do via the current toml model.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
