### ISSUE TITLE
SP pagination Java API is coupled only to a page number parameter

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6234]
There is a new API introduced to support application pagination [1] over https://github.com/wso2/product-is/issues/5280, which is only bound to a page number passed in.
The item count served by a page is a server configuration, that needs to be defined in the carbon.xml as 'ItemsPerPage'.

IMO, we need to have a Java API and an Osgi API, that support pagination based on the 'startIndex' and a 'count'.
This adds more flexibility for API consumers to decide on the way they need to paginate.

And just for the management console the above configuration should be used, which defines the items included in a page in the management console.
Then UI modules needs to be updated accordingly.

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationPaginationAndSearching.java

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
