### ISSUE TITLE
[Doc] Wildcard is not supported when configuring browser to support Kerberos and NTLM

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6235]
Documentation[1] step6 has not mentioned that Wildcard is not supported when configuring the browser to support Kerberos and NTLM.

If a wildcard configuration is used other than providing the IS hosted URL browser will not support the Kerberos authentication. Need to add a note on this special requirement.

[1] - https://docs.wso2.com/display/IS580/Configuring+IWA+on+Linux#ConfiguringIWAonLinux-ConfiguringWSO2ISwithIWAasalocalorfederatedauthenticator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
