### ISSUE TITLE
Tenant creation get intermittently fail

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#6237]
Affected - 5.8.0
Priority: High
Severity: Critical

**Description:**
When creating a large number of tenants, intermittently tenants creation get fail . I have use the performance test scrips to create 1000 of tenants.  [1] 
Please find the logs attached here with. 

[1] https://github.com/wso2/performance-is

[wso2carbon.log](https://github.com/wso2/product-is/files/3559672/wso2carbon.log)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
