### ISSUE TITLE
Getting "401" error when export the tenant public certificate with Tenant User

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6239]
Affected Version: wso2is-5.9.0-alpha
Priority: High
Severity: High

Steps to Reproduce :

Login to Identity Server with admin/admin credentials
Go to Configure Tab > Add New Tenant

Navigate to "Home > Manage > Keystores > List"

Click on public-key link

Same issue when try to "Download" ( /_system/governance/repository/security/key-stores)

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/carbon-identity-framework/pull/2397
