### ISSUE TITLE
Change in the hostname does not get reflected in SAML2 Web SSO Configuration section.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#6240]
Steps to reproduce:

- Update the carbon.xml with a different hostname.
- Restart the server
- Navigate to `Resident Identity Provider` > `Inbound Authentication Configuration` > `SAML2 Web SSO Configuration`

Even though we have changed the hostname all the URLs still start with `https://localhost:9443`

**Comment by thanujalk** [comment]
> Steps to reproduce:
> 
> * Update the carbon.xml with a different hostname.
> * Restart the server
> * Navigate to `Resident Identity Provider` > `Inbound Authentication Configuration` > `SAML2 Web SSO Configuration`

**Comment by wijith7** [comment]
Not reproduced with 5.9.0-Alpha4 pack
