### ISSUE TITLE
Change in the hostname does not reflected in the SAML2 IdP metadata file.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#6241]
Steps to reproduce:

- Update the carbon.xml with a different hostname.
- Restart the server
- Navigate to `Resident Identity Provider` > `Inbound Authentication Configuration` > `SAML2 Web SSO Configuration`

Download the SAML2 metadata file using the `Download SAML Metadata` button. This file still have URLs starts with `https://localhost:9443`

**Comment by JKAUSHALYA** [comment]
Related to https://github.com/wso2/product-is/issues/6240

**Comment by wijith7** [comment]
Not reproduced with 5.9.0-Alpha4 pack
