### ISSUE TITLE
[Doc] Adaptive authentication is missing in "Using WSO2 Identity Server" page

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#6248]
This will be the main document page and it should have a page for adaptive authentication which is a major feature. Currently, it is only there under tutorials.

This should be the same for other major features as well

**Comment by pulasthi7** [comment]
Will be tracked at https://github.com/wso2/docs-is/issues/113

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
