### ISSUE TITLE
[Doc]Old config is added in Configuring JWT Grant Type documentation

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6256]
Under Deploying artifacts in  **[Configuring JWT Grant Type documentation](https://is.docs.wso2.com/en/5.9.0/connectors/configuring-JWT-Grant-Type/#jwt-bearer-grant)** the following issues were found.

Under **step 2**, To register the JWT grant type, jwt-bearer grant config is added. But bydefault in IS5.9.0 alpha pack, this configuration is available in identity.xml file. SO we don't need to add the config.
Also, the configuration is given in old config model.

Under **step 4**.Add the audience values to the JWT token (ID token) in the , the old config model is used. 

<IS_HOME>/repository/conf/identity/identity.xml file as follows

```
<Audiences>
        <Audience>https://localhost:9443/oauth2/token</Audience>
 </Audiences>

```
But we need to change according to new config model as follows. 
```
[oauth.oidc.id_token]
audiences=[] 
```

Pointed here: https://github.com/wso2/docs-is/issues/118

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
