### ISSUE TITLE
[Docs] Duplicate list Items in SCIM API documentation

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#6257]
There are duplicate list items (`POST/ Create Group`) in the "Groups endpoint" documentation.
 
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/18381642/64059671-c92f2880-cbde-11e9-981c-846901fede37.png">

Documentation URL:  https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/using-the-SCIM-2.0-REST-APIs/#UsingtheSCIM2.0RESTAPIs-Groupsendpoint

Labels:

Priority/High
Type/Doc
Type/Bug
Complexity/Low
Affected/5.9.0-Alpha

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
