### ISSUE TITLE
[new config model] Setting up a 2 node cluster with toml missing j2 files

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6258]
**Suggested Labels**
Affected/IS5.9.0 alpha
Priority/High
Severity/Major
Type/Improvement

When setting up a 2 node cluster with deployment pattern 1 as in doc [1] using new configuration model (toml based) theres no j2 files for following configurations.

Under setting up dashboard section for the configurations mentioned there j2 files cannot be found.

IS_HOME>/repository/conf/identity/sso-idp-config.xml 
IS_HOME>/repository/deployment/server/jaggeryapps/dashboard/conf/site.json
WSO2IS_HOME>/repository/deployment/server/webapps/shindig/WEB-INF/web.xml

[1]. https://docs.wso2.com/display/IS580/Setting+Up+Deployment+Pattern+1

**Comment by wijith7** [comment]
We are not using this configurations in 5.9.0 IS pack

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
