### ISSUE TITLE
[Docs] All links under Developer guide are broken 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/product-is#6260]
If it's [1] still under WIP please ignore. 
[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/developer-Guide/

![Screen Shot 2019-08-31 at 11 16 16 AM](https://user-images.githubusercontent.com/54733286/64059803-e1a04280-cbe0-11e9-8e99-3cd7bf430708.png)

**Comment by isharanaotunna** [comment]
The links on the menu bar are working, just not under the "developer guide" page

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
