### ISSUE TITLE
Configured User ID Claim URI is not picked during User Provisioning in Facebook Authenticator

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#6265]
![image](https://user-images.githubusercontent.com/11584828/64059934-4a88ba00-cbe3-11e9-82bb-d57d27beeac6.png)

Even though the User ID Claim URI as email, during the provisioning time the server tried to create a facebook user name 

Environement : Tenant mode in Windows 2016 and Secondary Userstore MSSQL

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
