### ISSUE TITLE
[Docs] [Bug] Link under OAuth 1.0 is broken 

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/product-is#6268]
Under [1], page linked to "This specification" is broken
[1]https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/oauth-concepts/#oauth-10

![Screen Shot 2019-08-31 at 11 50 15 AM](https://user-images.githubusercontent.com/54733286/64060080-8e7cbe80-cbe5-11e9-915d-d5f46a6dd864.png)

**Comment by jeradrutnam** [comment]
Moved: https://github.com/wso2/docs-is/issues/120
