### ISSUE TITLE
[Dashboard] Blank modal on logging session terminate

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#6269]
Shows a blank modal on loggin session terminate button click

![image](https://user-images.githubusercontent.com/7569427/64060121-27133e80-cbe6-11e9-9070-61f77be179a2.png)

![image](https://user-images.githubusercontent.com/7569427/64060106-f501dc80-cbe5-11e9-9ae2-66ad28dc2338.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
