### ISSUE TITLE
Invalid SAML2 Destination URL generation during the tenant creation

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#6276]
- Create a new tenant and log in to that tenant.
- Navigate to `Resident Identity Provider` > `Inbound Authentication Configuration` > `SAML2 Web SSO Configuration`
Under Destination URLs we have,
`https://is590.qa.com/samlsso?tenantDomain=<tenant_domain>`

This should be changed to `https://is590.qa.com/samlsso` without the tenant domain. [Can be `https://is590.qa.com/samlsso?tenantDomain=<tenant_domain>` if same value present in the DB]

Also, if we send an authentification request without updating any configurations, it compares the destination URL to `https://is590.qa.com:443/samlsso`. So this is the value available in the DB. So need to correct that as well. Also, the metadata file needs to be corrected.

**Comment by senthalan** [comment]
As this is an improvement done for the product to add the tenant domain with this https://github.com/wso2/carbon-identity-framework/pull/2146/files#diff-98664c0777759c45d183f9180c27614eR168, it is the expected behaviour
