### ISSUE TITLE
[Config] SplitAuthzUser3Way in identity.xml file is not templated

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6278]
According to the this doc,[ Configuring JWT bearer Grant Type](https://is.docs.wso2.com/en/5.9.0/connectors/configuring-JWT-Grant-Type),

the following config  need to be added in identity.xml file. But that is not templated in identity.xml.j2 file .

`<SplitAuthzUser3Way>true</SplitAuthzUser3Way> `

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
