### ISSUE TITLE
SSO to a web application using identifier-first authenticator failed

### ISSUE THREAD

**Issue by Wathsara** [wso2/product-is#6279]
I created a tenant and tried to log in to a web application but it gave me an error like this
`ERROR {org.wso2.carbon.identity.application.authentication.endpoint.util.AuthContextAPIClient} - Sending GET request to URL : https://localhost:9443/api/identity/auth/v1.1/context/a976272e-97c1-4ee5-8dce-a245f14f119ffailed. java.io.IOException: Server returned HTTP response code: 401 for URL: https://localhost:9443/api/identity/auth/v1.1/context/a976272e-97c1-4ee5-8dce-a245f14f119` 

Then I changed the `login.jsp` file s line number 106 to 
`authAPIURL += "AuthRequestKey/" + request.getParameter("sessionDataKey");` and added `<Resource context="(.*)/api/identity/auth/v1.1/(.*)" secured="true" http-method="all"/>` this to the `identity.xml.j2` file locally and tested again

Then it gave an error like this
`ERROR {org.wso2.carbon.identity.application.authentication.endpoint.util.AuthContextAPIClient} - Sending GET request to URL : https://localhost:9443/api/identity/auth/v1.1/AuthRequestKey/a72aca94-875c-4ed4-911f-2b1ccaf5e653failed. java.io.FileNotFoundException: https://localhost:9443/api/identity/auth/v1.1/AuthRequestKey/a72aca94-875c-4ed4-911f-2b1ccaf5e653`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
