### ISSUE TITLE
When scope parameter is omitted a default scope value should be returned

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6281]
According to the spec[1],

>  If the client omits the scope parameter when requesting
>    authorization, the authorization server MUST either process the
>    request using a pre-defined default value or fail the request
>    indicating an invalid scope.  The authorization server SHOULD
>    document its scope requirements and default value (if defined).

In our implementation, we do not return a default scope value nor fail the request. 

Do we consider "" (empty string) as our default value? Shouldn't we have a default scope value defined?

[1] https://tools.ietf.org/html/rfc6749#section-3.3

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
