### ISSUE TITLE
In JWTBearer grant, configured Subject claim identifier is not added in id_token

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6282]
Reported Env:
db: postgres db
wso2is-5.9.0 alpha
tenant mode

Refered [Configuring JWT Grant Type](https://is.docs.wso2.com/en/5.9.0/connectors/configuring-JWT-Grant-Type/#jwt-bearer-grant) to configure JWT bearer grant
Steps to reproduce:

- Get JWT assertion(that has claims in oidc scope and has email address and country claim) from an identity provider(name it as JWTIDP).
- Configure the playground as  OAuth service provider in the primary IS.
- Request email address and country as requested claims from playground.
- Use email address as subject claim identifier.
- Invoke the token endpoint of primary IS with the JWT assertion obtained from the configured IDP(JWTIDP).
- Check the sub claim in the obtained id_token. It will be same as the JWT assertion.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
