### ISSUE TITLE
In JWTBearerGrant, tenant domain and userstore domain are not appended to the subject

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6283]
Reported Env:
db: postgres db
wso2is-5.9.0 alpha
in tenant mode

Referred [Configuring JWT Grant Type](https://is.docs.wso2.com/en/5.9.0/connectors/configuring-JWT-Grant-Type/#jwt-bearer-grant) doc to configure JWT bearer grant
Steps to reproduce:

- Get JWT assertion(that has claims in oidc scope and has email address and country claim) from an identity provider(name it as JWTIDP).
- Configure the playground as OAuth service provider in the primary IS.
- **Enable Use tenant domain in local subject identifier** and **Use user store domain in local subject identifier** under in **Local & Outbound Authentication Configuration**
- Invoke the token endpoint of primary IS with the JWT assertion obtained from the configured IDP(JWTIDP).
- Check the **sub** value in the obtained id_token. It does not have tenant domain or userstore domain.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
