### ISSUE TITLE
SCIM2 Me endpoint GET request does not retrive user data for the response in tenant mode

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6284]
**Suggested Labels**
Affected/wso2IS5.9.0alpha
Priority/Highest
Severity/Major

**Environment**
US-JDBC
DB- MYSQL 5.6
Ubuntu 

**Steps to Reproduce**
Change the deploymnet.toml as below to make secured parameter of SCIM2 ME endpoint to false

```
[resource_access_control.scim2_me_post_method]
secured = false
permission = "/permission/admin/manage/identity/usermgt/create"

[resource_access_control.scim2_me_get_method]
secured = false
permission = "/permission/admin/login"

```
Provision a user in tenant mode with SCIM2 Me endpoint
`curl -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"shanika94","password":"shanika94","emails":[{"primary":true,"value":"alex.j@gmail.com","type":"home"},{"value":"alex_j@wso2.com","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://192.168.108.66:9443/t/wso2.com/scim2/Me
`
Then try to retrieve the details of the created user
`curl -v -k --user shanika94:shanika94 https://192.168.108.66:9443/t/wso2.com/scim2/Me`

**Observation**
To get the user details we need to make the secured parameter as true. But as a negative test case if we make this parameter as false and try to retrieve user data it will just give 200 ok and no response details given. In a scenario like this it is better to give a valid response to the user  

![me21](https://user-images.githubusercontent.com/31848014/64062493-7b2d1b80-cc04-11e9-8c5c-762b457ca0dc.png)
![me22](https://user-images.githubusercontent.com/31848014/64062496-81bb9300-cc04-11e9-9f04-687a617530fe.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
