### ISSUE TITLE
SSO failed when enabled jwt-basic in local authenticators

### ISSUE THREAD

**Issue by Wathsara** [wso2/product-is#6286]
I enabled the jwt-basic and tested my application and it gave me this error. 
  
![error](https://user-images.githubusercontent.com/31571237/64062694-5e461780-cc07-11e9-814f-92fd4920a5d2.png)

I didn't configured anything related to jwt-basic. So if this the intended behavior the Error page has to be improved and if not the issue has to be fixed

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
