### ISSUE TITLE
Google outbound provisioning of groups not supported

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#6288]
IS 5.9.0 alpha

[Git link](https://github.com/wso2-extensions/identity-outbound-provisioning-google/blob/9c313493764ece05a623a4a6ca29adead81d4c1f/components/org.wso2.carbon.identity.provisioning.connector.google/src/main/java/org/wso2/carbon/identity/provisioning/connector/google/GoogleProvisioningConnector.java#L124)
Google outbound provisioning connector only supports user provisioning but groups. Groups provisioning support should be added.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
