### ISSUE TITLE
Duplicating XACML Policy ID update the existing policy

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#6289]
- If a new XACML policy is given with an existing policy ID, the new policy will replace the existing policy. 
- If the policy ID is the same as an existing ID but with a different letter case, the new policy ID will replace the existing policy ID.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
