### ISSUE TITLE
SCIM2 Me endpoint user provisioning with empty password response does not reflect the users correct action

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6290]
**Suggested Labels**
Affected/wso2is5.9.0alpha
US-JDBC
DB-MSSQL
Priority/Normal
Severity/Major

**Steps to Reproduce**
Provision a user with SCIM2 ME endpoint with null value for password field 

`curl -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"abcd","password":"","emails":[{"primary":true,"value":"alex.j@gmail.com","type":"home"},{"value":"alex_j@wso2.com","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://192.168.108.66:9443/t/wso2.com/scim2/Me
`
The response will be as follows

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in adding the user: abcd to the user store. PasswordInvalidAsk Password Feature is disabled","status":"500"}`

When we send a request with null value for username response will be as follows 
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"31301 - Username null is not valid. User name must be a non null string with following format, ^[\\S]{3,30}$","status":"400"}`

Should make the response consistent when password is null to match with the users correct action

when the password does not match the password standards
`curl -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"abcde","password":"12","emails":[{"primary":true,"value":"alex.j@gmail.com","type":"home"},{"value":"alex_j@wso2.com","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://192.168.108.66:9443/t/wso2.com/scim2/Me
`

**Response**
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"30003 - Credential is not valid. Credential must be a non null string with following format, ^[\\S]{5,30}$","status":"400"}

`
This also needs to change to say for the user exactly that the password does not match with the expected standards

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
