### ISSUE TITLE
Error with the response on SOAP UI after adding a role/user successfully

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/product-is#6292]
Description:
When adding a role or user using SOAP services, the WSO2 management console displays the amendments successfully but no response is displayed in SOAP UI console.

![Screenshot from 2019-08-31 15-44-34](https://user-images.githubusercontent.com/51709964/64063420-b97d0780-cc11-11e9-83ea-bf7e680eacf8.png)

Suggested Labels:
Type Bug

OS, DB, other environment details and versions:
OS- ubuntu
DB- POSTGRESS
Environment- 3

**Comment by ayshsandu** [comment]
This is not a bug. Response is 202, and in SOAP UI "Raw" view you can see the response as below.
<img width="1054" alt="Screen Shot 2019-09-16 at 10 38 16 PM" src="https://user-images.githubusercontent.com/5061791/64978271-c026a280-d8d2-11e9-8d00-d1edcffb29e4.png">
