### ISSUE TITLE
SCIM2 Me user provisioning with invalid email address should not provision the user

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6293]
`Suggested Labels` 
Affected/wso2is5.9.0alpha
US-JDBC
DB-MSSQL
Priority/Normal
Severity/Major

`Steps to Reproduce`
Provision a user with invalid email address using SCIM2 ME endpoint 
`url -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"abcde","password":"123456","emails":[{"primary":true,"value":"alex.j","type":"home"},{"value":"alex_j@wso2.com","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://192.168.108.66:9443/t/wso2.com/scim2/Me
`
**Response** 
`{"emails":[{"type":"work","value":"alex_j@wso2.com"},{"type":"home","value":"alex.j"}],"meta":{"created":"2019-08-31T11:31:42.358Z","location":"https://192.168.108.66:9443/t/wso2.com/scim2/Users/e683f44f-401b-4e96-bc46-15b630f9dce2","lastModified":"2019-08-31T11:31:42.358Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"Internal/everyone"}],"name":{"givenName":"Alex","familyName":"Johnson"},"id":"e683f44f-401b-4e96-bc46-15b630f9dce2","userName":"abcde"}`
**Observation**
User should not be provisioned if the email is invalid. But user will be succesfully provisioned with invalid email showing 200 ok .

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
