### ISSUE TITLE
"Login-Attempts-Based Authentication" template doesn't work

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#6298]
The required claim has been merged and removed later due to avoid 5.8.0 migration. Need to re-add it to enable this feature OOTB.

The related issue is:
https://github.com/wso2/product-is/issues/3951

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
