### ISSUE TITLE
Idle account lock after defined time does not work

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#6299]
Configure account lock on idle accounts as per [1] for 2 mins. Account locking for idle session configured 2 mins does not happen as expected.

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/user-account-suspension/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
