### ISSUE TITLE
Provisioning to secondary IS doesn't work as expected when user is created via SCIM1

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6300]
Configure outbound provisioning as in [this docmument](https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/outbound-provisioning-with-scim/), using two IS instances node1 and node2. Node1 being the primary is and node2 being the secondary IS. In the setup node1 is configured to provision users to node2.

01. Create a user with scim1 in node1, user gets created in node2, but user attributes are not synced.
02. Update the user in node1, user attributes don't get updated in node2. But user update works when the user is updated, using the management console.
03. Group update via SCIM1 fails with the following error in the console.
`[2019-08-31 18:18:29,732] [aa6878b8-ae66-4875-bcfe-4b6daa134f9a] ERROR {org.wso2.charon.core.protocol.endpoints.GroupResourceEndpoint} - org.wso2.charon.core.exceptions.CharonException: Error occurred while updating old group : PRIMARY/engineer_up`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
