### ISSUE TITLE
[Config] Template CacheConfig CacheManager to import dynamic configs in identity.xml.j2

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6301]
Template CacheConfig CacheManager to import dynamic configs in identity.xml.j2 as some components such as "Private Key JWT Client Authentication for OIDC" is not packed by default but when using will need cache configuration.

Ref: Step 4 of
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/private-key-jwt-client-authentication-for-oidc

**Comment by darshanasbg** [comment]
Why can't we have the mentioned configuration as the default values in code?

Why does end user need to change these configurations?

**Comment by janakamarasena** [comment]
+1 for the suggestion. Anyway, wouldn't it be good to have the improvement in config templating now as the changes to the components will take some time?
