### ISSUE TITLE
Error log printed during 5.9.0 alpha server startup 

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#6305]
Following error log is seen when starting the 5.9.0 alpha fresh pack in ubuntu

`ERROR {org.wso2.carbon.event.processor.manager.core.internal.CarbonEventManagementService} - Adapter polling failed as EventReceiverManagementService not available`

**Comment by ayshsandu** [comment]
The same issue is reported in https://github.com/wso2/product-is/issues/6189
