### ISSUE TITLE
Missing key-mappings for userstore configuration properties

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6306]
Currently, we have only added key-mappings for the below properties.

```
"user_store.connection_url": "user_store.properties.ConnectionURL",
"user_store.connection_name": "user_store.properties.ConnectionName",
"user_store.connection_password": "user_store.properties.ConnectionPassword"
```
Other properties only can be configured using the actual property value. 
Eg:

```
[user_store]
UsernameJavaRegEx = "^[\\S]{5,30}$"
```

But we have updated the documentation to add the above property as shown below.
```
[user_store]
username_java_regex="^[\\S]{5,30}$"
```
If we configure the additional changes as shown above it will not get reflected in the user-mgt.xml file.

Reference To: https://github.com/wso2/carbon-kernel/issues/2250
**Suggested Labels:**

- Priority/High
- Type/Config
- 5.9.0-Alpha

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
