### ISSUE TITLE
SCIM2 ME endpoint provision user update with PATCH operation fails with 500 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6308]
**Suggested Labels**
Affected/wso2is5.9.0alpha
US-JDBC
DB-MSSQL
Priority/Highest
Severity/Major
Type/Bug

**Steps to Reproduce**
Provision the user using SCIM2 Me endpoint

`curl -v -k --data '{"schemas":[],"name":{"familyName":"Johnson","givenName":"Alex"},"userName":"shanika93","password":"shanika93","emails":[{"primary":true,"value":"alex.j@gmail.com","type":"home"},{"value":"alex_j@wso2.com","type":"work"}],"EnterpriseUser":{"employeeNumber":"123A","manager":{"value":"Taylor"}}}' --header "Content-Type:application/json" https://192.168.108.66:9443/t/wso2.com/scim2/Me -i
`

Assign admin permission for the created user shanika93 from management console

Update the user using PATCH operation 
`curl -v -k --user shanika93@wso2.com:shanika93 -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"nickName":"shaggy"}}]}' --header "Content-Type:application/json" https://192.168.108.66:9443/t/wso2.com/scim2/Me -i 
` 
**Response**
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error occurred while trying to update the user","status":"500"}`

No back log errors getting printed

Note: tested the same behaviour against H2 Embedded LDAP and it worked fine observed above issue against JDBC US and DB type MSSQL

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
