### ISSUE TITLE
Adding a SAML IdP with same entity IdP does not reflect the error properly in MC

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6309]
Steps to reproduce:
- Configure a SAML based IdP and work with it for SAML federation
- Try to add another SAML IdP for the same 'Identity Provider Entity ID' being used in the previous IdP configured
- Note that something pops up in the UI and goes immediately. More over the IdP is not added.
- In the backend you will an error log as below,
`An Identity Provider Entity ID has already been registered with the name`
 but end user configuring an IdP will not know what actually happened.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
