### ISSUE TITLE
User provision to secondary IS doesn't work for some scenarios when user is created via SCIM2

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6311]
Related to https://github.com/wso2/product-is/issues/6300

Configure outbound provisioning as in this document, using two IS instances node1 and node2. Node1 being the primary is and node2 being the secondary IS. In the setup, node1 is configured to provision users to node2.

Case 1,
 - Node1 , Primary userstore ---> node2 primary user store

Case 2
 - Node1, secondary userstore ---> node2 primary user store 

Following are the observations when creating a user in node1 using scim2

01. Add user
         Case1: success
         Case2: success
02. Update user 
         Case1: fail
         Case2: fail
        - User gets updated in node 1, but not in node2
        - following error getting printed in the console
           `[2019-09-01 11:06:17,405] [17e15a3a-6d9d-409b-862d-e947e62a589e]  INFO {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - SCIM update user operation returned with response code: 400
[2019-09-01 11:06:17,405] [17e15a3a-6d9d-409b-862d-e947e62a589e] ERROR {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - An array of "attributes" needs to be present in "meta" of the SCIM request`

03. Add group
         Case1: success
         Case2: success

04. Update group with members
        Case1: success
        Case2: fail
        - Group gets updated in node 1 with members, but not in node2
        - following error getting printed in the console
           `[2019-09-01 11:33:24,877] [419d59a2-1a99-430a-9914-b9a863dd825e] ERROR {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - Users not found in the user store for the filter: userName Eq SECONDARY/aysh_scim2_local_tn_01
[2019-09-01 11:33:27,906] [419d59a2-1a99-430a-9914-b9a863dd825e]  INFO {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - SCIM update group operation returned with response code: 500
[2019-09-01 11:33:27,907] [419d59a2-1a99-430a-9914-b9a863dd825e] ERROR {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} - Error occurred while updating old group : PRIMARY/aysh_local_sec_manager_01`

05. Delete group
         Case1: success
         Case2: success
     
05. Delete User
         Case1: success
         Case2: success

06. Create a user in Dumb mode
         Case1: fail
         Case2: fail
           - User is created in Node1 server as well, ideally, the user only need to be provisioned to Node2 only.

07. Create a group in Dumb mode
         Case1: fail
         Case2: fail
           - Group is created in Node1 server as well, ideally, the group only need to be provisioned to Node2 only.

**Comment by rksk** [comment]
#2 is addressed with https://github.com/wso2-extensions/identity-outbound-provisioning-scim/pull/33

#4 is occurring due to an issue in the identity framework where it sends the userstore domain along with the username and group name in some flows. So that is sent to node2 but it is unable to process the secondary userstore domain. It can be avoided by defining the userstore domain in the outbound provisioning configuration of the node1.

#7 & #8 Dumb mode is not implemented at all in the SCIM2.0 inbound provisioning components.  The same is reported at https://github.com/wso2/product-is/issues/4702

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
