### ISSUE TITLE
Http Status is sent in the response body of SCIM2 error response

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6315]
Sending HTTP status code in error response is redundant.

`{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Group with name: PRIMARY/aysh_local_manager_01 already exists in the system.",
    "status": "409"
}`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
