### ISSUE TITLE
Associating user accounts with dashboard switch between accounts drop down hiden with associated accounts window

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6316]
**Suggested Labels**
Affected/wso2is5.9.0alpha
US-JDBC
DB-MSSQL
Priority/Highest
Severity/Major
Type/Bug
Type/UX

**Steps to Reproduce**
Follow the documentation [1] to add a user association. After successfully adding the user association click on the dropdown list at the top right corner of your screen to switch between accounts by selecting the required user account from the dropdown. View will be as below. The newly added account is coverd and hidden from the associated accounts window.
![user-association](https://user-images.githubusercontent.com/31848014/64073967-d58cb180-ccc2-11e9-98a0-f0035adc391d.png)

[1]. https://docs.wso2.com/display/IS580/Associating+User+Accounts

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
