### ISSUE TITLE
Remove a user association and re add the same from dashboard will give a inconsistent behaviour

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6317]
**Suggested Labels**
Affected/wso2is5.9.0alpha
US-JDBC
DB-MSSQL
Priority/High
Severity/Major
Type/Bug

**Steps to  Reproduce** 

1. Follow the documentation [1] to add a user association.
2. Remove the added user association from Remove option
3. Re add the same user account as a user association. 
4. Refresh the page 
5. A window with a Error message will pop up and get disappear with a short time and then only the secondly created user account association will get listed in the UI.

[1]. https://docs.wso2.com/display/IS580/Associating+User+Accounts

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
