### ISSUE TITLE
Audience and recipient validation failed when not using the port (443)

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#6318]
Audience and recipient validation failed when not using the port (443) https://is590.qa.com:443/oauth2/token

Steps to reproduce:

- Configure saml bearer grant using the using [1]
- Identity Server is started with 443 port instead of 9443.
- Ideally Audience and Recipient should be configured as follows.

Audience : https://localhost/oauth2/token

Recipient : https://localhost/oauth2/token

But it won't as above. It is mandatory to provide port although it is the default HTTPS port. 

[1] https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/setting-up-a-saml2-bearer-assertion-profile-for-oauth-2.0/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
