### ISSUE TITLE
SAML logout request not initiated for the IdP when OIDC SP is used

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6327]
Steps to reproduce:
- Configure an OIDC SP in a tenant
- Configure a SAML IdP in the same and link to the above configured SP for federation and enable logout
- Logs into the SP with OIDC and observe federated request is initiated and authenticated from the federated IdP
- Initiate an OIDC logout request with id_token_hint so that IS can identify the SP the request is initiated
- Yet, note that the logout request is not initiated to the SAML IdP

**Comment by rksk** [comment]
The fix has to be compatible for the both cases where logout consent is enforced and not.
