### ISSUE TITLE
User is not getting updated/deleted when outbound provisioned to Salesforce with secondary userstore user.

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6330]
**Description:**

1. Setup outbound provisioning for Salesforce[1] in super-tenant
2. Create a user in a secondary user-store
3. Try to update the claims of the user or delete the user.

User claims such as given_name, last_name is not getting updated and user will not be deleted.

[1] - https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/outbound-provisioning-with-salesforce/

**Suggested Labels**
- Priority/High
- Type/Bug
- 5.9.0-Alpha

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
