### ISSUE TITLE
Dashboard app session not invalidated when account is locked.

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#6331]
After administrator locks a particular account from mangement console, if that particualr user was already logged in to the dashboard app, if we refresh the dashboard app, that locked user is still logged in to the dashboard.
We need to fix our dashboard app session handling.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
