### ISSUE TITLE
Requested and mandatory claims are not passing in SAML bearer grant in federated scenario

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#6332]
When setting up Single Sign-On with SAML to an external Identity Provider and use SAML bearer grant to get token, requested claims are not passing in the id_token and access token. 

However, in the SAML assertion, the requested claims are getting passed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
