### ISSUE TITLE
Users not getting provisioned in secondary user-store tenant mode

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6334]
**Description:**

1. Create a tenant.
2. Setup outbound provisioning for Salesforce[1] in the created tenant
2. Create a user in a secondary user-store

User will not get provisioned into Salesforce

[1] - https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/outbound-provisioning-with-salesforce/

**Suggested Labels**

- Priority/High
- Type/Bug
- 5.9.0-Alpha

**Comment by Thumimku** [comment]
Issue is not reproducible in 5.10.0-beta-2. 
Secondary user store - Postgresql 10.5

**Comment by madurangasiriwardena** [comment]
Closing the issue as per the above comment.
