### ISSUE TITLE
UMA- update, get, delete resource not working in tenant mode

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#6335]
When trying to get, update and delete a resource using UMA resource registration endpoint in tenant mode, 401 unauthorized error occurs.
However creating a resource using UMA resource registration endpoint is successful and persisted in the db.

Tested environment:
IS 5.9.0 Alpha, db2

**Comment by darshanasbg** [comment]
Have you checked whether those HTTP methods allowed in identity.xml?

**Comment by dewniMW** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2396
