### ISSUE TITLE
Whitelist fileupload/entitlement-policy in Owasp.CsrfGuard.Carbon.properties

### ISSUE THREAD

**Issue by gayanlggd** [wso2/product-is#6337]
Trying to import a policy file in IS 5.8.0 latest WUM update gives the following error on the log and a 403 on the browser.

WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/fileupload/entitlement-policy, error:required token is missing from the request)

**Comment by madurangasiriwardena** [comment]
Could not observe the error in the latest 5.10.0 build. CSRF token is sent with the POST request to /fileupload/entitlement-policy endpoint and file upload is successful.
