### ISSUE TITLE
Primary sub attribute is not returning when creating a User in SCIM2

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#6347]
When creating a user with multiple emails and by defining any one of them as 'primary' email it should return the response with parameter 'primary' as per the documentation [1].

request :
`{  
   "schemas":[  

   ],
   "name":{  
      "familyName":"familyN",
      "givenName":"givenN"
   },
   "userName":"test-user",
   "password":"p@ssw0rd",
   "emails":[  
      {  
         "primary":false,
         "value":"email_work_01@test.com",
         "type":"work"
      },
      {  
         "value":"email_work_02@test.com",
         "type":"work",
         "primary":false
      },
      {  
         "value":"email_home_01@test.com",
         "type":"home",
         "primary":false
      },
      {  
         "value":"email_home_02@test.com",
         "type":"home",
         "primary":true
      }
   ]
}
`

response
`{  
   "emails":[  
      {  
         "type":"work",
         "value":"email_work_02@test.com"
      },
      {  
         "type":"home",
         "value":"email_home_02@test.com"
      }
   ],
   "meta":{  
      "created":"2019-08-28T07:55:49.695Z",
      "location":"https://localhost:9443/scim2/Users/334d0551-06d5-48c1-94f1-58920d785725",
      "lastModified":"2019-08-28T07:55:49.695Z",
      "resourceType":"User"
   },
   "schemas":[  
      "urn:ietf:params:scim:schemas:core:2.0:User",
      "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
   ],
   "roles":[  
      {  
         "type":"default",
         "value":"Internal/everyone"
      }
   ],
   "name":{  
      "givenName":"givenN",
      "familyName":"familyN"
   },
   "id":"334d0551-06d5-48c1-94f1-58920d785725",
   "userName":"test-user"
}`

As you can see "primary" filed is missing in the response. If this is the expected behavior we need to update the documentation or otherwise we have to fix it. In IS 5.7.0 this works as expected.

[1] https://docs.wso2.com/display/IS580/Using+the+SCIM+2.0+REST+APIs#UsingtheSCIM2.0RESTAPIs-POST/CreateUser

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
