### ISSUE TITLE
[Doc] IS 5.8.0 tutorial points to installing IS 5.7.0

### ISSUE THREAD

**Issue by gayanlggd** [wso2/product-is#6350]
In the Configuring+a+Service+Provider+for+Adaptive+Authentication documentation, linked below [1], under part 2 of the Before you begin section, it says "Install WSO2 IS version 5.7.0" where as it should be "version 5.8.0".

[1] https://docs.wso2.com/display/IS580/Configuring+a+Service+Provider+for+Adaptive+Authentication

**Comment by Seralahthan** [comment]
Document [1] has been modified with the intended text.

[1] https://docs.wso2.com/display/IS580/Configuring+a+Service+Provider+for+Adaptive+Authentication

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
