### ISSUE TITLE
Scope changes for the API endpoints in WSO2 Publisher are not reflecting into the WSO2 API Store

### ISSUE THREAD

**Issue by HareeshYHY** [wso2/product-is#6353]
**Version Details:-**
WSO2 IS - 5.5.0
WSO2 API Manager - 2.2.0

1.  I have created users, roles and mapped the users to the roles in WSO2 API Manager.
2. I modify and publish my API, assigning a scope to one on the endpoints so that it requires the editor authenticate and un-authenticate scope as shown below.
![image](https://user-images.githubusercontent.com/37172022/64251400-79a27280-cee6-11e9-957b-64511a6e9e68.png)

3. Generated the access_token with "unauthenticate" scope and invoke the authenticate scoped endpoint and it works. This shouldn't happen since the token was generated with the unauthenticate scope, not the authenticate one. I should get ((900910) - The access token does not allow you to access the requested resource) error.
4. Why am able to access the API with all the scopes.
5. any way to configure this behaviour?
6. I have followed the below link
   https://wso2.com/library/articles/2017/01/article-an-overview-of-scope-management-with-wso2-api-manager/

7. Why "Required Scopes" is not showing  the WSO2 API Store for the scoped API
![image](https://user-images.githubusercontent.com/37172022/64252152-27fae780-cee8-11e9-86b0-003b22d3a08e.png)

Please help me on this issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
