### ISSUE TITLE
Bug in searching users through SCIM 1.1 filter while using JDBC user-store.

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#6354]
**Description:**
Cannot store usernames that are the same but have an underscore instead of a period as this is seen as the same user when provisioning them.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
WSO2IS-5.6.0

**Steps to reproduce:**

1. Configure Identity server to use email as username.
2. Configure JDBC userstore instead of the LDAP userstore.
3. Create a user using SCIM 1.1 API (test.user@gmail.com).
4. Try to search user using "test.user@gmail.com". I t will give you the result as expected.
5. Try to search user using "test_user@gmail.com". I t will also give you the result as in the previous step (step 4).

**Comment by LahiruLS** [comment]
Hi All,
We observe the same issue in the identity server 5.7.0 version as well.

**Comment by GDRDABARERA** [comment]
This is fixed in master, hence closing the issue
