### ISSUE TITLE
Missing toml properties for user-mgt.xml 

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#6356]
In doc [1], 

```
1.    testOnBorrow

2.    <Property name="CaseSensitiveAuthorizationRules">true</Property>

```
In doc [2], 

```
1.    <EveryOneRoleName>everyone</EveryOneRoleName> <!-- By default users in this role see the registry root -->

2.     <AdminUser>

```
In doc [3],

 ```
"DomainName
Connection URL
driverName
Disabled
CountRetrieverClass
validationQuery
validationInterval
Description"
```

In doc [4], 

```
RoleDNPattern
CountRetrieverClass
java.naming.ldap.attributes.binary
 <Property encrypted="true">
<Property name="UserDNPattern"/>
<Property name="Disabled">false</Property>
 <Property name="RoleDNPattern"/>

```
In doc [5],

```
"DomainName
UserEntryObjectClass
UserDNPattern
WriteGroups
GroupEntryObjectClass
RoleDNPattern
MemberOfAttribute
UsernameJavaScriptRegEx
UsernameJavaRegExViolationErrorMsg
PasswordJavaScriptRegEx
PasswordJavaRegExViolationErrorMsg
PasswordJavaScriptRegEx
BulkImportSupported
EmptyRolesAllowed
kdcEnabled
CountRetrieverClass
java.naming.ldap.attributes.binary
MembershipAttributeRange"
```
In doc [6], 
```
"UserDNPattern
Disabled
RoleDNPattern
MemberOfAttribute
CountRetrieverClass
java.naming.ldap.attributes.binary
MembershipAttributeRange"
```

In doc [7],

```
"<EveryOneRoleName>everyone</EveryOneRoleName> <!-- By default users in this role see the registry root -->

 <Property name=""MultiTenantRealmConfigBuilder"">org.wso2.carbon.user.core.config.multitenancy.SimpleRealmConfigBuilder</Property>"
```

[1] https://docs.wso2.com/display/IS580/Configuring+the+Authorization+Manager
[2] https://docs.wso2.com/display/IS580/Configuring+the+System+Administrator
[3] https://docs.wso2.com/display/IS580/Configuring+a+JDBC+User+Store
[4] https://docs.wso2.com/display/IS580/Configuring+a+Read-write+Active+Directory+User+Store
[5] https://docs.wso2.com/display/IS580/Configuring+a+Read-only+LDAP+User+Store
[6] https://docs.wso2.com/display/IS580/Configuring+a+Read-write+LDAP+User+Store
[7] https://docs.wso2.com/display/IS580/Configuring+Roles+and+Permissions

**Comment by janakamarasena** [comment]
@hasinidilanka any idea how we can use this "java.naming.ldap.attributes.binary" in the deployment.toml?

**Comment by wijith7** [comment]
Doc fix for 1 - https://github.com/wso2/docs-is/pull/436

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
