### ISSUE TITLE
Issues when creating an application which contains the word 'internal' for the application name 

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#6357]
When creating/updating an application which contains the word 'internal' for the application name , an error is throwing and sometimes it is not loading the application to the management console UI. 

If we create an application as my_internal_app, then the filter [1] is set as 'Application/my_internal_app'. But from [2] if the filter contains the word 'internal' then it removes the domain name from the filter , hence the filter value modifies as 'my_internal_app'. When fetching the internal roles from the db it executes following query and pass the filter value to the 'LIKE' clause and returns nothing. The query expects to have 'Application/my_internal_app'

SELECT UM_ROLE_NAME FROM UM_HYBRID_USER_ROLE, UM_HYBRID_ROLE WHERE UM_USER_NAME='admin' AND UM_HYBRID_USER_ROLE.UM_ROLE_ID=UM_HYBRID_ROLE.UM_ID AND UM_HYBRID_USER_ROLE.UM_TENANT_ID=-1234 AND UM_HYBRID_ROLE.UM_TENANT_ID=-1234 AND UM_HYBRID_USER_ROLE.UM_DOMAIN_ID=(SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE UM_TENANT_ID=-1234 AND UM_DOMAIN_NAME='PRIMARY') AND UM_ROLE_NAME LIKE 'my_internal_app'

1] https://github.com/wso2/carbon-kernel/blob/4.5.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/hybrid/HybridRoleManager.java#L404

[2] https://github.com/wso2-support/carbon4-kernel/blob/support-4.4.35/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/hybrid/HybridRoleManager.java#L449

[3] https://github.com/wso2/carbon-kernel/blob/4.5.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/hybrid/HybridJDBCConstants.java#L82

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
