### ISSUE TITLE
Missing toml properties for claim-config.xml

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#6358]
In doc [1], [2], and [3]

```
"<Dialect dialectURI=""http://wso2.org/SampleAppClaims"">
    <Claim>
        <ClaimURI>http://wso2.org/SampleAppClaims/givenname</ClaimURI>
        <DisplayName>First Name</DisplayName>
        <MappedLocalClaim>http://wso2.org/claims/givenname</MappedLocalClaim>
    </Claim>
    <Claim>
        <ClaimURI>http://wso2.org/SampleAppClaims/nickName</ClaimURI>
        <DisplayName>Nick Name</DisplayName>
        <MappedLocalClaim>http://wso2.org/claims/nickname</MappedLocalClaim>
    </Claim>
</Dialect>"
```

[1] https://docs.wso2.com/display/IS580/Adding+Claim+Dialects
[2] https://docs.wso2.com/display/IS580/Editing+Claim+Dialects
[3] https://docs.wso2.com/display/IS580/Deleting+Claim+Dialects

**Comment by janakamarasena** [comment]
This file will not be templated as this is a data resource and will only be used at the initial server start-up.

**Comment by rszabolcs** [comment]
For us this would be really useful since we want to enable the feature of enabling/disabing user accounts. To achieve this first one need to add `deployment.toml` these lines:
```
[identity_mgt.account_disabling]
enable_account_disabling = "true"
```
But also the claim itself needs to be enabled as well which isn't by default.
Clicking through the UI is a no-go for us as well as I'd really like to avoid manipulating DB.

**Comment by mefarazath** [comment]
@rszabolcs The claim related to account disabled feature (http://wso2.org/claims/identity/accountDisabled) is shipped by default.

The default behaviour identity claims (any claim that starts with http://wso2.org/claims/identity/) is that they are stored in the Identity database and not in user stores.

Therefore you should be able to using the account disabled feature by simply enabling it.

**Comment by rszabolcs** [comment]
Thanks, @mefarazath , that is true that it is seems to be working, however not seen in the user's datapage w/o setting supportedByDefault to true. If there is no other side-effect but being invisible, we can live with that.
