### ISSUE TITLE
toml equivalent for Total File Size Limit property in carbon.xml file

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#6359]
```
<TotalFileSizeLimit>100</TotalFileSizeLimit>
```

Ref:
https://docs.wso2.com/display/IS580/Configuring+Users

**Comment by wijith7** [comment]
Doc fix - https://github.com/wso2/docs-is/pull/435

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
