### ISSUE TITLE
Missing toml property for properties in embedded-ldap.xml file

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#6360]
```
"<EmbeddedLDAP>
    <Property name=""enable"">false</Property>
    .......................
</EmbeddedLDAP>"
```

Ref:
https://docs.wso2.com/display/IS580/Configuring+the+Primary+User+Store

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
