### ISSUE TITLE
support for per-SP SAML2 SessionNotOnOrAfter config

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#6366]
Currently, the support for setting the window allowed by SAML2's SessionNotOnOrAfter is a single, global config (`SAMLSessionNotOnOrAfterPeriod` in `SSOService` in `identity.xml`).  Being able to configure this value independently for different service providers would be ideal, as some off-the-shelf service providers have different quirks in the way they handle session expiry.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
