### ISSUE TITLE
Retain initial request parameters until the logout completion in OIDC logout flow.

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#6369]
**Description:**

In the OIDC flow, once you are logged in to an application and when you click the logout button, it will pop up the consent and if you click on 'NO', then it will redirect to oauth2_error.do which mention the below message.

> **access_denied**
> End User denied the logout request

But it will be better if have the initial request parameters until the logout completion. 
So, it would be better to fix the code and redirect to the post logout URI (if it was sent in the initial logout request) when the user denies the consent.

**Suggested Labels:**
Type/Improvement

**Comment by darshanasbg** [comment]
@piraveena Whats should be the correct\recommended approach according to the spec?

**Comment by piraveena** [comment]
@darshanasbg , According to the OIDC session management spec, it is mentioned that during RP initiated logout flow [1], 

> At the logout endpoint, the OP SHOULD ask the End-User whether he wants to log out of the OP as well. If the End-User says "yes", then the OP MUST log out the End-User.

But it does not say anything about how to handle if the end-user declines it. So IMO, that is OP specific



[1]https://openid.net/specs/openid-connect-session-1_0.html#RPLogout
