### ISSUE TITLE
Move the authentication result publish logic in Authenticator to StepHandler

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#6376]
Currently, the authentication stats of the authenticators are published from the AbstractApplicaitonAthenticator. It should be handled by the framework. Mostly by the DefaultStepHandler

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
