### ISSUE TITLE
Shifting forcedpasswordreset attribute into scim2-schema-extension config as default

### ISSUE THREAD

**Issue by thushaaanthan** [wso2/product-is#6388]
While working on force password reset flow with SCIM [1], We define "forcePasswordReset" as an extension by adding an attribute in the scim2-schema-extension.config file. Then we add the attribute names of the attributes ("forcePasswordReset") that added to the scim2-schema-extension.config file as subAttribute of the wso2Extention attribute.

Rather than adding "forcePasswordReset" as an extension manually, we can shift this into scim2-schema-extension config as default. Also, we can able to add the other possible attributes into scim2-schema-extension config.

[1]https://docs.wso2.com/display/ISCONNECTORS/Configuring+SCIM+2.0+Provisioning+Connector

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
