### ISSUE TITLE
Provide a REST API for TOTP

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#6390]
**Description:**

Currently, we have a SOAP service for TOTP authenticator but we do not have a dedicated REST API for it. Since we need to provide the functionality to use TOTP authenticator as an MFA option in the user portal it would be better to have a REST API for TOTP.

**Suggested Labels:**

Type/Improvement

**Comment by ayshsandu** [comment]
Partially related to 
https://github.com/wso2/product-is/issues/6392
