### ISSUE TITLE
Forced Password reset via OTP will not logout a user who is logged in with another browser after the pw change

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6391]
**Suggested Labels**
Affected/IS 5.9.0
Priority/High
Severity/Major
Type/Bug

**Steps to Reproduce the issue**

1. Follow the doc [1] to try Admin forced password reset via OTP
2. Create a user as testuser@wso2.com in a secondary userstore.
3. Enable **Enable Password Reset via OTP** in Resident IDP
4. Send below request with soapUI

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mgt="http://mgt.profile.user.identity.carbon.wso2.org" xmlns:xsd="http://mgt.profile.user.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <mgt:setUserProfile>
         <!--Optional:-->
         <mgt:username>SECONDARY-ALPHA2/testuser</mgt:username>
         <!--Optional:-->
         <mgt:profile>
            <!--Zero or more repetitions:-->
            <xsd:fieldValues>
               
               <xsd:claimUri>http://wso2.org/claims/identity/adminForcedPasswordReset</xsd:claimUri>
               <!--Optional:-->
               
               <xsd:fieldValue>true</xsd:fieldValue>
               <!--Optional:-->
               
               <!--Optional:-->
               
               <!--Optional:-->
               
            </xsd:fieldValues>
            <!--Zero or more repetitions:-->
            
            <!--Optional:-->
            <xsd:profileName>default</xsd:profileName>
         </mgt:profile>
      </mgt:setUserProfile>
   </soapenv:Body>
</soapenv:Envelope>


```

3. Before resetting pw with the code received for email login to dashboard and management console as testuser@wso2.com with old credentials using a different browser (chrome)
4. Now reset the pw using dashboard by login to dashboard with a different browser (firefox)

**Observation**
Now even though the testuser@wso2.com 's pw is changed if you go and refresh the browsers where u logged in for dashboard and management console previously with old credentials you can still proceed . User (with old credentials login) will not be automatically logged out from dashboard or management console in chrome browser after the pw change.
[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/forced-password-reset/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
