### ISSUE TITLE
SP Initiated SAML SSO Flow breaks when the SAML Issuer is appended with tenantDomain

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#6395]
SP Initiated SAML SSO Flow breaks when the SAML Issuer is appended with tenant domain. 
This happens with the recent WUM changes of IS-5.7.0.

**Steps to reproduce the issue**

- Create a tenant domain and user
- Log in with the tenant user and create a service provider with SAML Inbound Authentication (SAML Issuer "travelocity.com")
- Edit the **travelocity.properties** in the travelocity web application configure the 
**SPEntityId** as below
`SAML2.SPEntityId=travelocity.com@wso2.com` 
- Comment the below lines in the **travelocity.properties** file
`QueryParams=tenantDomain`
- Try out the SAML SSO flow

The issue is not present in IS-5.7.0 WUM **1564662300263** (which is on August 01) and issue is present in WUM **1565902800000** (August 15).

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/6385
