### ISSUE TITLE
post_logout_redirect_uri needs to be configurable via management console

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6397]
According to OpenID Connect Session management spec [1],

**post_logout_redirect_uri**
> OPTIONAL. URL to which the RP is requesting that the End-User's User Agent be redirected after a logout has been performed. The value MUST have been previously registered with the OP, either using the post_logout_redirect_uris Registration parameter or via another mechanism. If supplied, the OP SHOULD honor this request following the logout.

PostLogout redirect URI can be configurable or we can use some other mechanism to take post-logout redirect URI.

Current WSO2 Identity server considers the callback URL as the post-logout-redirect URI and it validates against the callback-URI [2]. So it will be an improvement if SP is able to configure any URI as Post-logout-redirect URI from management console rather using callback URL.

And according to this OpenID COnnect issue [3], it is recommended that when post_logout_redirect_uri is present and the id_token_hint is not, the request should result in an error. This also can be considered as an improvement. 

[1]https://openid.net/specs/openid-connect-session-1_0.html#RPLogout
[2]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/servlet/OIDCLogoutServlet.java#L401
[3]https://bitbucket.org/openid/connect/issues/1071/require-id_token_hint-in-rp-initiated

Suggested Labels:
Type/Improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
