### ISSUE TITLE
Migration client doesn't work on upgradation from MySql 5.5 to MySql 5.7

### ISSUE THREAD

**Issue by SwatiNEC** [wso2/product-is#6402]
Hi 

I want to upgrade WSO2 by using [document](https://docs.wso2.com/display/IS580/Upgrading+From+an+Older+Version+of+WSO2+IS) with following version:
WSO2 IS 5.3.0 --> 5.7.0
WSO2 APIM 2.1.0 --> 2.6.0
MySql 5.5 --> 5.7

When i start WSO2 IS then I encountered exceptions which are mentioned in attached log.txt.
[log.txt](https://github.com/wso2/product-is/files/3595183/log.txt)

**Comment by SwatiNEC** [comment]
Hi @madurangasiriwardena, @hasinthaindrajee 

I have resolved the above issue by executing the below script file.
[wso2is_script.txt](https://github.com/wso2/product-is/files/3609454/wso2is_script.txt)

And I am able to succussfully migrate WSO2 and mysql with the above mentioned versions.
This script need to be executed before starting WSO2 IS using data migration option.

Please share you opinion on the attached script.

**Comment by madurangasiriwardena** [comment]
@SwatiNEC, thank you for the provided information about the issue and the solution. We will analysis this further and will incorporate necessary steps to product/docs.

@omindu, @janakamarasena FYI.

**Comment by SwatiNEC** [comment]
Hi @madurangasiriwardena,@omindu, @janakamarasena

Thank you for your response.
Hoping to hear from you soon.

**Comment by SwatiNEC** [comment]
Hi @madurangasiriwardena,@omindu, @janakamarasena, @JKAUSHALYA 

As [mentioned](https://github.com/wso2/product-is/issues/6402#issuecomment-531193357), Could you please provide your valuable comments.

**Comment by SwatiNEC** [comment]
Hi @madurangasiriwardena,@omindu, @janakamarasena, @JKAUSHALYA

Are there any updates?

Thanks

**Comment by omindu** [comment]
Hi Swati,

As you have experienced, the migration client does not handle migration between different database versions. Especially when the versions have incompatible changes.

By looking at the steps you have followed I'm assuming you have restored the MySQL 5.5 data dump on 5.7 and ran the migration steps on 5.7 data dump. Prior to restoring the data dump, you have run `wso2is_script.txt` to make 5.5 data dump compatible with 5.7.

If that the case, I do not see any issue with this approach for the migration.

Regards,
Omindu.

**Comment by SwatiNEC** [comment]
Hi @omindu 

Yes your understanding is correct. I have restored the MySQL 5.5 data dump on 5.7 and ran the migration steps on 5.7 data dump. Prior to restoring the data dump, I have run wso2is_script.txt to make 5.5 data dump compatible with 5.7.

Regards,
Swati Jain

**Comment by SwatiNEC** [comment]
Hi @omindu 

Can i raise a PR for these script to merge in WSO2 community? If yes could you please tell me suitable location for the same.

Regards,
Swati Jain

**Comment by SwatiNEC** [comment]
Hi @omindu

As [mentioned](https://github.com/wso2/product-is/issues/6402#issuecomment-547745666) could you please tell me suitable location to raise a PR.

Regards,
Swati Jain

**Comment by SwatiNEC** [comment]
Hi @omindu

Could you please tell me suitable location to raise a PR.

Regards,
Swati Jain

**Comment by SakshiSharma-India** [comment]
Hi @madurangasiriwardena , @omindu , @janakamarasena , @JKAUSHALYA 

As per the [document](https://docs.wso2.com/display/compatibility/Tested+DBMSs) , the compatible version of MySQL is v5.7 for WSO2 Identity Server v5.7. 
So, in our case, we (Me and @SwatiNEC) are upgrading from WSO2 Identity Server v5.1 to v5.7 along with MySQL from v5.5 to v5.7.
As per solution to this issue, we have created a [script](https://github.com/wso2/product-is/files/3609454/wso2is_script.txt) as mentioned in above [comment](https://github.com/wso2/product-is/issues/6402#issuecomment-531181136). We would like to confirm below:
1. Can this script can be a part of WSO2 product/document?
2. If yes, could you please tell us the suitable location to raise a PR for this script?
3. Shall we update the WSO2 [document ](https://docs.wso2.com/display/IS580/Upgrading+From+an+Older+Version+of+WSO2+IS) for this script?

**Comment by JKAUSHALYA** [comment]
Hi @SakshiSharma-India 

Thanks for you contribution. We can include this in the WSO2 documentation as a community contribution. 
[1] is the WSO2 official documentation repository. Please send a PR to the branches 5.9.0 and 5.10.0 for the section "Setup"[2][3]. WSO2 documentation team will review and merge this. 

[1] https://github.com/wso2/docs-is
[2] https://github.com/wso2/docs-is/tree/5.9.0/en/docs/setup
[3] https://is.docs.wso2.com/en/latest/setup/migration-process/

**Comment by SwatiNEC** [comment]
Hi @JKAUSHALYA 

As per my understanding from your previous comment, I will create a document for migration of mysql 5.5 to 5.7  as `migration-mysql-5.5-to-5.7.md` and will be added to both the links mentioned below:
[1] https://github.com/wso2/docs-is/tree/5.9.0/en/docs/setup
[2] https://is.docs.wso2.com/en/latest/setup/migration-process/

If above mentioned understanding is correct then I request you to provide a location where mysql script for migration can be committed in order to provide a link in the document.
I have created a mysql migration script which does the actual migration from mysql 5.5 to 5.7.

Note: There may be different script for each version of wso2is. The script I have attached here [wso2is_script.txt](https://github.com/wso2/product-is/issues/6402#issuecomment-531181136) in this issue is for wso2is 5.3.0.

**Comment by JKAUSHALYA** [comment]
Please put the PRs for branches [1] and [2].

We were planning to keep the MySQL script as well under the documentation. So you can commit it as well to the above branches. Let's add a heading for the script marking it as "IS 5.3.0 related". 

[1] https://github.com/wso2/docs-is/tree/5.9.0
[2] https://github.com/wso2/docs-is/tree/5.10.0

**Comment by SwatiNEC** [comment]
Hi @JKAUSHALYA 

Thanks for confirmation. 
I have one more query. Can I raise the PR for WSO2 IS v5.7.0 also?
As I am facing this issue with WSO2 IS v5.7.0 in my current project.

**Comment by JKAUSHALYA** [comment]
We don't have git-based documentation for IS-5.7.0. Instead, we have Atlassian Confluence documentation [1]. So we cannot add this, from a PR. However, if you like to contribute to that as well, it is better to initiate a discussion in the `iam-dev@wso2.org` mailing list so our team can consider it and decide a way to do it.

[1] https://docs.wso2.com/display/IS570/

**Comment by SwatiNEC** [comment]
Hi @JKAUSHALYA 

Request you to please review the above PR's.

**Comment by JKAUSHALYA** [comment]
Hi @SwatiNEC 
We are reviewing the PRs now and will merge them if no issues. Otherwise we will inform them in the PR.
Thanks for your contribution.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
