### ISSUE TITLE
Issue with listing user groups using SCIM 

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#6407]
When trying to list groups created from SCIM 1.1 API using SCIM2 by calling SCIM2 API endpoint “https://localhost:9443/scim2/Groups" .curruntly it is unable to retrieve the group details regardless of the SCIM version that used to create the user group. The reason is for that when listing the groups using SCIM, the SCIM call is querying the “IDN_SCIM_GROUP” table based on the SCIM schema attribute that used to create groups and retrieving the group list with respect to that attribute name as follows. 

In SCIM1 using attribute name - urn:scim:schemas:core:1.0:id
In SCIM2 using attribute name - urn:ietf:params:scim:schemas:core:2.0:id

Steps to reproduce:

- Take the latest IS WUM updated pack
-enable the SCIM 1 UserOperationEventListener in the identity.xml file reside in <IS_HOME>/repository/conf/identity folder
`<EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                   name="org.wso2.carbon.identity.scim.common.listener.SCIMUserOperationListener"
                       orderId="90" enable="true"/>`
- Start the server.
- Create a user using SCIM1 API
-  And create a group using SCIM1 API
-  List the created group by calling API "https://localhost:9443/wso2/scim/Groups"
- Then disable SCIM 1 UserOperationEventListener and enabled the SCIM2 UserOperationEventListener in the <IS_HOME>/repository/conf/identity/identity.xml file as follow
`<EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener"
                       orderId="93" enable="true"/>`
- Restart the server
- Create a user from SCIM2 API
- Create a Group using SCIM2 API
-  List the groups by calling API "https://localhost:9443/scim2/Groups"

listSCIMGroups method  [1] is querying groups from the  IDN_SCIM_GROUP based on the attribute value [2] "ATTR_NAME ='urn:ietf:params:scim:schemas:core:2.0:id'"

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/8b0e7881b2d5151facac2823af48d9fe72d2809e/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java#L56

[2] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/8b0e7881b2d5151facac2823af48d9fe72d2809e/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/SQLQueries.java#L24

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
