### ISSUE TITLE
Remove message body for 401 and 403 responses in server apis swagger doc 

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6414]
For unauthorized requests, the response is 401 and there is no response body. But in the swagger docs[1] it says a response body is available. I the same way for forbidden requests the response is 403 and there is no body but the swagger says there is.

[1] - https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.server.claim.management/org.wso2.carbon.identity.rest.api.server.claim.management.v1/src/main/resources/claim-management.yaml#L782

**Comment by janakamarasena** [comment]
Before updating the swagger doc. Best to verify that there is actually no 401 and 403 error usages in the API code.

Also better to check both Server and User APIs

**Comment by Thumimku** [comment]
There is no usage of Response.Status.UNAUTHORIZED and Response.Status.FORBIDDEN in sever apis. But there are few usages of these constants in user apis. For example [https://github.com/wso2/identity-api-user/blob/561183457d3761c786b3fca15100c462d8dc2076/components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java#L261](https://github.com/wso2/identity-api-user/blob/561183457d3761c786b3fca15100c462d8dc2076/components/org.wso2.carbon.identity.api.user.totp/org.wso2.carbon.identity.api.user.totp.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/totp/v1/core/TOTPService.java#L261)
