### ISSUE TITLE
Session termination service should notify the service providers that the session is terminated

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6419]
When a session is terminated via the session termination service, the service providers related to that session should be notified.

**Comment by ayshsandu** [comment]
@janakamarasena can you verify whether these are captured in latest session related git issues?

**Comment by janakamarasena** [comment]
Related to https://github.com/wso2/product-is/issues/10410

**Comment by janakamarasena** [comment]
Related to https://github.com/wso2/product-is/issues/10410
