### ISSUE TITLE
getApplicationBasicInfo SOAP service returns 0 as the applicationId for all the applications

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#6420]
### Description
When calling `getApplicationBasicInfo` SOAP service `returns 0` as the `applicationId` for all the applications.

**IS Version:** 5.8.*, 5.9.*

<img width="1792" alt="Screen Shot 2019-09-11 at 2 41 18 PM" src="https://user-images.githubusercontent.com/15249242/64684380-a46e6700-d4a2-11e9-9a1e-4146ae6dc0f7.png">

**Comment by senthalan** [comment]
auto increament applicationId is part of the internal implementation logic of the Identity Server. So need it is to be exposed outside.

**Comment by madurangasiriwardena** [comment]
@gayashanbc can you link the relevant pull requests here?
