### ISSUE TITLE
Username recovery with only email address when multiple users exists with same email address gives 202 with REST API but no mail sent

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6421]
**Suggested Labels**
Affected/ IS 5.9.0 alpha 3 snapshot
Type/ Bug
Priority/ High
Severity / Major

**Steps to Reproduce**

1. Follow the doc [1] user name recovery with dashboard
2. Set the deployment.toml to send the email
3. Resident IDP > Account management policies > Account Recovery > Enable Username Recovery checkbox and the Enable Notification Internally Management
4. Add 2 users for a secondary userstore in tenant mode and set the same email address in both the users profiles.
5. Use the below curl command to do user name recovery with REST API

`curl -X POST -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type: application/json" -d '[{"uri": "http://wso2.org/claims/emailaddress", "value": "dewmi123455@gmail.com"}]' "https://is590testenv2:9443/t/wso2.com/api/identity/recovery/v0.9/recover-username/" -i -k `

**Response**
```
HTTP/1.1 202 
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Date: Wed, 11 Sep 2019 06:44:02 GMT
Content-Length: 0
Server: WSO2 Carbon Server

```
When there are multiple users with same email address and as non of the claims required for username recovery are marked as mandotory a user may try the curl request for tenant domain as mentioned above. We get a 202 success response for the curl but no email will be sent for user name recovery for the email address. If this scenario is not supported we need to handle the 202 response that the curl request gives.

Note: this curl request with a user recovering the username by only providing a single claim value(email) will work succesfully if theres no multiple users with the same email in the system.

**Comment by ayshsandu** [comment]
If the system cannot identify a unique user with given information, it is unable to send a recovery email. Always it is recommended to use combination of user claims to identify a user account.
