### ISSUE TITLE
[Doc] 5.8.0 documentation refers old IS versions

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#6422]
In this [documentation](https://docs.wso2.com/display/IS580/Installing+as+a+Windows+Service) of WSO2 IS 5.8.0, configuration steps refer old versions of IS.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
