### ISSUE TITLE
SCIM2 Documentation missing some content.

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#6433]
In WSO2IS documentations regarding SCIM2 group end point, there is no mention about a PATCH REMOVE command. Only the PATCH ADD command is included in the documentation. We can update a GROUP using PATCH remove method as well. As an example when we need to remove a member from a Group, can use Patch Remove method by specifying path and operation. But there is no proper documentation available for this.

 Following is an example for patch remove method and sample curl commands.
EX: Curl command to remove a member from a group.
Curl request:
curl --user admin:XXXX -k -X PATCH -d@payload_new.json -H "Content-Type: application/scim+json" https://localhost:9443/scim2/Groups/143e8436-ca66-4802-9724-92858f425a3b -v

Payload :

{
"schemas": [
"urn:ietf:params:scim:api:messages:2.0:PatchOp"
],
"Operations":[
{ "op":"remove", "path":"members[display eq venura value eq d1f1577d-8305-4e16-8f3d-ee17ae7f388f]" }

]
}

**Comment by YvonneW** [comment]
https://github.com/wso2/docs-is/pull/951 will resolve this.

**Comment by senthalan** [comment]
Can we close this @YvonneW ?
