### ISSUE TITLE
TOML Configs pertaining to publishing statistics

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6443]
Please provide the corresponding TOML configs:

**identity.xml > Listener**  
- org.wso2.carbon.identity.data.publisher.application.authentication.AuthnDataPublisherProxy
- org.wso2.carbon.identity.data.publisher.authentication.analytics.login.AnalyticsLoginDataPublishHandler
- org.wso2.carbon.identity.data.publisher.authentication.analytics.session.AnalyticsSessionDataPublishHandler

**Login analytics: <IS_HOME>/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-AuthenticationData.xml**

**Session analytics: <IS_HOME>/repository/deployment/server/eventpublishers/IsAnalytics-Publisher-wso2event-SessionData.xml** 

REF: 
https://docs.wso2.com/display/IS580/Prerequisites+to+Publish+Statistics
https://is.docs.wso2.com/en/5.9.0/learn/prerequisites-to-publish-statistics/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
