### ISSUE TITLE
TOTP Does Not Redirects To The Authentication Page

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6451]
**Issue**
1. Configure basic auth as the first step and the TOTP as the second step for a service provider, with OAuth2 as the inbound authentication protocol.
2. Try to log in to the application.
3. Once you are successfully authenticated with the basic auth, you will be redirected to the TOTP authentication page with the redirected URL having the oauth2 path parameter appended.

Probable cause for this issue is we are using the relative path for the redirection[1]. We can fix this by changing [1] as shown below.

`response.sendRedirect(IdentityUtil.getServerURL(totpLoginPageUrl, true, true));`

[1] -  https://github.com/wso2-extensions/identity-outbound-auth-totp/blob/v2.0.14/component/authenticator/src/main/java/org/wso2/carbon/identity/application/authenticator/totp/TOTPAuthenticator.java#L180

**Related Issue** - https://github.com/wso2/product-is/issues/6431

**Affected Versions**

- IS-5.8.0
- totp.connector-2.0.14

**Comment by nilasini** [comment]
The reproduce steps for IS-5.8.0 is as follows.

1. Configure two service provider with OIDC as the inbound protocol.
2. For one sp configure basic auth as the first step and the TOTP as the second step, for the second sp configure basic auth.
3. Login to the second sp,then in another tab try to login to the first sp you will be redirected to the TOTP authentication page with the redirected URL having the oauth2 path parameter appended.
