### ISSUE TITLE
axis2.xml file need to be templated

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6452]
Usecase: Enabling Notifications for User Operations 

 
    

Ref: https://is.docs.wso2.com/en/5.9.0/learn/enabling-notifications-for-user-operations/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
