### ISSUE TITLE
Getting latest scim compliance fixes with wum

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#6454]
In order to get the latest scim compliance fix with wum update user should start the server with the following property

```
-Dscim2.compliance=true
```
After a product version release if we find any scim compliance issue we are fixing the issue depending on the above property. The reason for the above property is to keep backward compatibility. In latest releases, the scim compiance fixes will be availbale by default.

We need to mention this in our docs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
