### ISSUE TITLE
Template <CallbackFactory> in application-authentication.xml

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6457]
The `<CallbackFactory>` config is an optional config and it should be templated in a way that the tag should only appear in the application-authentication.xml if it is **defined** **only**.

`<CallbackFactory>` should be defined inside the `<Extensions>` tag

ex:
```
<Extensions>
        <RequestCoordinator>org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator</RequestCoordinator>
        <AuthenticationRequestHandler>org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler</AuthenticationRequestHandler>        

        ...
        <CallbackFactory>org.wso2.carbon.identity.custom.callback.userstore.CustomUserStoreOrderCallbackFactory</CallbackFactory>
</Extensions>
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
