### ISSUE TITLE
Template <UseUserIdFromClaims> in identity.xml

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6459]
The `<UseUserIdFromClaims>` config is an optional config and it should be templated in a way that the tag should only appear in the identity.xml if it is **defined only**.

`<UseUserIdFromClaims>` should be defined inside the  `<Server><OAuth><SAML2Grant>` tag

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
