### ISSUE TITLE
Monitor - System Logs missing

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#6462]
From the administration interface, Monitor the System Logs functionality is missing. Version wso2is-5.9.0-alpha3.
![image](https://user-images.githubusercontent.com/45126217/65150169-34c12480-da2c-11e9-8da6-23289ce83b29.png)

**Comment by JKAUSHALYA** [comment]
Now the log4j2.properties file is hot deployable. Any changes done through the UI can be done via the file. Hence removed this from the UI.

**Comment by hefesita** [comment]
But the main purpose was not the monitoring part? It was an easy way to monitor the systems log (errors) without going on the server.

**Comment by JKAUSHALYA** [comment]
Agree with your point. 
However, our roadmap is to slowly move into contanarize world. Even though this is good feature in the monolithic world it is considered as an anti-pattern in the container world.  So we are in the process of changing accordingly. We even plan to remove JVM matrics as well in future releases. Logs should be monitored through external tools as including those features inside the product will make it little heavy which is not suitable for containers.
