### ISSUE TITLE
[Refactor] ClaimDataMigrator class can be made common in identity-migration-resources

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6471]
ClaimDataMigrator class in identity-migration-resources[1] can be extracted and made common as it is used in multiple IS version migrations.

[1] - https://github.com/wso2-extensions/identity-migration-resources

**Comment by Abilashini** [comment]
Resolved with https://github.com/wso2-extensions/identity-migration-resources/pull/42
