### ISSUE TITLE
I cannot authenticate using OpenID Connect when my service provider is defined in an XML

### ISSUE THREAD

**Issue by davidballester** [wso2/product-is#6477]
Hello:

I'm using version 5.8.0.

I've followed this guide: [Configuring a SP and IdP Using Configuration Files](https://docs.wso2.com/display/IS580/Configuring+a+SP+and+IdP+Using+Configuration+Files). In my case, I want to configure a Service Provider that allows me to authenticate using an OpenID Connect implicit flow. For that, I'm using the playground2 application.

I've done the same thing using a service provider configured via the console and it works as expected. I've attached the exported XML for it.

Now, if I do the same thing with a service provider that I provide via XML to the IS, as described in the guide, and referenced from `sso-idp-config`, when I try to initiate the authentication implicit flow, I get an identity server error:

> invalid_client
> Cannot find an application associated with the given consumer key :

In the logs I can see that my service provider is properly registered:

> INFO {org.wso2.carbon.identity.sso.saml.admin.FileBasedConfigManager} -  A SSO Service Provider is registered for

Now, when I look into the code, I can see that the one in charge of finding a service provider given a client ID is looking into the database, and the service provider configured via XML is not in the database. The message in the log that I can see saying the provider is registered comes from `SSOServiceProviderConfigManager `, and in its documentation it says:

> This class is used in Stratos when SSO is enabled to the complete system.

Does that mean that I cannot use this configuration mechanism to define a service provider to authenticate using, for example, an implicit flow from the playground application?

Attachments:
- [Service provider configured via the console](https://github.com/wso2/product-is/files/3634841/service-provider-console.xml.txt)
- [Service provider configured via XML](https://github.com/wso2/product-is/files/3634900/xml-configured-service-provider.xml.txt)
- [sso-idp-config.xml](https://github.com/wso2/product-is/files/3634852/sso-idp-config.xml.txt)

**Comment by senthalan** [comment]
The filebased Service provider only supports the SAML configured in the sso-idp-config.xml.  OpenID Connect flows are not supported. Because the  OpenID Connect flows involve tokens to be persisted. So we need the database entries.

But you can create the service provider using this xml file through import service provider

**Comment by davidballester** [comment]
Thanks for your response, @senthalan. Yes, I created my service provider using the management console and then exported it in XML so I could import it wherever I want it. 

OK, so that's the way to go with OpenID for service providers. Do you think that could be made more prominent in the docs so others don't stumble where I did? Or maybe it already is and I just missed it. Do you accept PRs for docs?
