### ISSUE TITLE
wso2is-km 5.8.0 not available on Docker Hub

### ISSUE THREAD

**Issue by GJKrupa** [wso2/product-is#6482]
wso2/wso2is version 5.8.0 is available on Dockerhub
wso2/wso2is-km is not

We're trying to use OIDC with WSO2 deployed behind a k8s ingress and the existence of #4276 in 5.7.0 makes it difficult.

**Comment by JKAUSHALYA** [comment]
The WSO2 Identity Server Key Managers are released according to the relevant APIM release. (It isn't related to the Identity Server versions that comes out) For the latest APIM version (2.6.0) compatible Identity Server Key Manager version is 5.7.0. APIM 3.0.0 will be the next release and it will most probably go with Identity Server version 5.9.0. Hence, there isn't any Identity Server Key Manager version 5.8.0.
