### ISSUE TITLE
Need Speicfy Max Limit to Return in List Users

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#6484]
Currently, when we do list users, it will try to list all the users without restricting the total result. If we have 1million users it will try to return all the 1millition, we need to limit the total result using the "MaxUserNameListLength" user store property as we do for other calls.
For SCIM call [getUserList(String claim, String claimValue, String profileName) ](https://github.com/wso2-support/carbon4-kernel/blob/7656ec53788c77546e09c99df5a9d4e9168ab1d9/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L1301) API has been used, finally getUserListFromProperties(String property, String value, String profileName) used to get all the users from the corresponding user store type in where we don't have a max limit  for returning usernames.

Tested version IS 5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
