### ISSUE TITLE
Session Mgt service does not handle sessions of file based SPs

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#6485]
The new feature on session management services requires session information mapped with the service providers to be present in the tables introduced. Those mappings maintain the relation with the application from the appID (auto-generated ID in the SP_APP table). 

But for the file-based service providers, there is no entry in the database. Hence no ID in the database. Therefore the session information of these service providers is not added to the database as well.

We need to have session information of all the applications regardless they are files based.
Therefore we need to make sure that the `<ApplicationID>` defined in the configuration XML file is unique across the service providers and use this ID to maintain the mappings

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
