### ISSUE TITLE
Issues in emailOTP and smsOTP authenticator claims

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6486]
emailOTP uses the claim `http://wso2.org/claims/identity/emailotp_disabled` it is better to make it camel-case to follow the convention. `http://wso2.org/claims/identity/emailOTPDisabled`

smsOTP uses the claim `http://wso2.org/claims/identity/smsotp_disabled ` it is better to make it camel-case to follow the convention. `http://wso2.org/claims/identity/smsOTPDisabled`

SMSOTP uses the claim[1] `http://wso2.org/claims/otpbackupcodes` ideally this should be an identity claim. 

https://github.com/wso2-extensions/identity-outbound-auth-sms-otp/blob/34daf5faf3d761e45d9465ecd64606c8e5226386/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/smsotp/SMSOTPConstants.java#L36

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
