### ISSUE TITLE
No consistent error message when user creating with an invalid password.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#6491]
We've observed multiple different error messages when a user is created using an invalid password. (password policy violation)

1. Running the pack with default settings, h2 database, self-sign up enabled.
   1. Creating a new user via the management console.
      1. Error message configured in the user-mgt.xml file.
   2. User self-register.
      1. A custom error message with the validation regex, that we think comes from the code itself.
2. Password policy feature enabled.
   1. Same error message comes when using the management console as well as the user self-signup. But message is not completely configurable.
      1. Custom build message comes if the password length is nor correct.
      2. If the policy regex violated other than the length, the configured error message comes in the feature settings.

If someone needs to customize these messages, there's no way to do it since some message are thrown from the code. Multilanguage support is also not there.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
