### ISSUE TITLE
[Feature] User Profile ChallengeQuestion answer Hashing option

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#6495]
Currently, in the user profile of Identity Server, the ChallengeQuestions (Challenge Question1 and Challenge Question2 ) answers are displayed as an **SHA-256 hashed base64 encoded** value. 

ex : 
```
Challenge Question1 => 
Favorite vacation location ?!NQx1S6TTiJdpOqB370MHKoWdI/YTRDEz/su9kKNRLKU=
```

In some use-cases, administrative user's may need to view the ChallengeQuestion answers of the users for manual security verifications.

So it would be convenient to have a feature to set configurable hashing option for the ChallengeQuestion answers (hashing enabled or hashing disabled) along with an option to select the desired hashing mechanism (SHA-256 etc).

**Comment by ruwanta** [comment]
-1 on this feature request.
It violates the a basic privacy principles.
Challenge questions are treated same as password. All safeguards related to password should be applicable to challenge question answers.

No one should be able to view any sensitive data, like "Mothers maiden name", "My favorite teachers name", "Name of my first crush" etc.

If a deployment needs this feature, it should be done externally. One can have API proxy in front of product API, read the data on SOAP/REST, and save it outside the Identity Databases/User Store

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
