### ISSUE TITLE
Insert access token scopes as a bulk

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#6497]
When issuing the access token, there are insert queries running for each of the scopes to the table IDN_OAUTH2_ACCESS_TOKEN_SCOPE with the scope details. 

As an example, if a request comes with 50 scopes, there are 50 insert queries.

Can we do a bulk insert for this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
