### ISSUE TITLE
Errors while executing BPS > BPEL > CREATE DB2 Script

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#6499]
**Suggested Labels**
Affected/ IS 5.9.0 Beta
Type/ Bug
Priority/ High
Severity / Major

**Steps to Reproduce**

<IS-HOME>/dbscripts/bps/bpel/create/db2.script

Observed following ERRORS in the db2 script

1. All the Create table lines does not end properly
2. All Create index lines does not end properly
3. SQL Error [42601]: An unexpected token "INSERT INTO ODE_SCHEMA_VERSION values (6)" was found following "BEGIN-OF-STATEMENT".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.13
SQL Error [42601]: An unexpected token "INSERT INTO ODE_SCHEMA_VERSION values (6)" was found following "BEGIN-OF-STATEMENT".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.13
  An unexpected token "INSERT INTO ODE_SCHEMA_VERSION values (6)" was found following "BEGIN-OF-STATEMENT".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.13
  An unexpected token "INSERT INTO ODE_SCHEMA_VERSION values (6)" was found following "BEGIN-OF-STATEMENT".  Expected tokens may include:  "<space>".. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.25.13

4. create table ODE_SCHEMA_VERSION (VERSION integer) 
insert into ODE_SCHEMA_VERSION values (6) 
above 2 lines keywords needs to be capitalized properly

Needs to verify the whole script

**Comment by ShanikaWickramasinghe** [comment]
Observing the same issues against IS 5.10.0 M8 Snapshot pack

**Comment by ShanikaWickramasinghe** [comment]
Observing below Error against IS 5.10.0 alphs3 snapshot
dbscripts/pbs/pbel/create

SQL Error [42601]: An unexpected token "create table ODE_SCHEMA_VERSION (VERSION integer)" was found following "

**Comment by janakamarasena** [comment]
I was able to reproduce this issue when using the DBeaver tool. 
But when directly executing script file against the db (`db2 -f db2.sql`) the script executed without any issues.

I was also able to successfully run the script using the datagrip tool
