### ISSUE TITLE
Need to include group testcases with domain aware name

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#6503]
Currently, we only have test-case for groups which doesn't include display name with user store domain. 
Already TODO list has been added in [SCIM2GroupTestCase](https://github.com/wso2/product-is/blob/8c61ef8530cf73888132b3ab15319897b4947975/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/scim2/SCIM2GroupTestCase.java#L241). 

`        //TODO: groupsName comes from this is <Userstore_domain>/displayName
`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
