### ISSUE TITLE
Overwritten configurations 

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#6508]
Hi, 

We have installed the beta version in our test environment and noticed that if we make configuration changes they are overwritten with defaults when the server starts. Is this something for alpha/beta versions or is there a setting we need to disable?

Thanks

**Comment by JKAUSHALYA** [comment]
We have changed the configuration model to use much easier TOML[1] configurations. Now there is only a single configuration file (deployment.toml) to change only the necessary configurations. Documentation related to this[2] is WIP yet. But if you can let us know what is the exact configuration that you need to change, we can point out the correct TOML configs. 

[1] https://github.com/toml-lang/toml
[2] https://is.docs.wso2.com/en/5.9.0/

**Comment by hefesita** [comment]
For example we have the email as the username. A complete deployment.toml with all the possible configurations would be really nice.
