### ISSUE TITLE
Downloaded zip file does not have wso2server.bat 

### ISSUE THREAD

**Issue by Newbie112222** [wso2/product-is#6516]
Hi,
I downloaded the zip file but looks like it does not have the script. 

Following the steps below:
Extract the downloaded/built binary distribution zip file
Run the wso2server.sh or wso2server.bat file in the /bin directory
Once the server starts, point your Web browser to https://localhost:9443/carbon/
User dashboard is available at https://localhost:9443/dashboard
For more information, see the Installation Guide

**Comment by senthalan** [comment]
I have verified with the beta pack and current master, it has the wso2server.bat. I am closing this issue. Feel free to reopen if you have to face a different issue. Providing more information on the issue will helpfull.
