### ISSUE TITLE
Exception thrown as The deployment of secondary user store configuration is not valid during tenant loading.

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#6542]
1. Created Tenant
2.Created a secondary user store (LDAP)
3. Restart the server
4. Log in to the management console using tenant admin credentials (tenant loading)
5. When debugging we have observed that the exception thrown from [1].

6. Following exception could be observed when we enable org.wso2.carbon.user.core DEBUG logs

[2019-09-28 14:25:16,159] admin@abc.com [1] [IS]DEBUG {org.wso2.carbon.user.core.common.UserStoreDeploymentManager} -  The deployment of XYZ_COM.xml is not valid.

`Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException	at java.security.AccessController.doPrivileged(Native Method)	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:170)	... 86 moreCaused by: java.lang.reflect.InvocationTargetException	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:173)	... 88 moreCaused by: org.wso2.carbon.user.core.UserStoreException: Could not initialize new user store manager : XYZ.COM Duplicate domain names not allowed.	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addSecondaryUserStoreManager(AbstractUserStoreManager.java:6303)	... 93 more`

But we could observe that the user store config deployed properly and tenant admin login and tent loading process successful.

[1] https://github.com/wso2/carbon-kernel/blob/v4.4.9/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/UserStoreDeploymentManager.java#L82-L87

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
