### ISSUE TITLE
IdentityClaimMetadataMgtCacheManager is not currently available at the identity.xml file

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#6547]
Configuring caching is a useful cache for the users who do not enable clustering at the axis2.xml file. Currently, we do not have the  IdentityClaimMetadataMgtCacheManager cahce manager at the identity xml file.
```
<CacheManager name="IdentityClaimMetadataMgtCacheManager">            
            <Cache name="LocalClaimCache"   enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ExternalClaimCache"  enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ClaimDialectCache"  enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
    </CacheManager>
```

**Comment by LahiruLS** [comment]
We need to figure out the best values for the time out etc for default values.

**Comment by darshanasbg** [comment]
@LahiruLS Usually the identity server have two sets of timeout values for Caches.

1. default 15min timeout - most of the caches are using this.
2. 5min timeout - there are set of caches, in a way that acts as data holders (for ex: AuthnReqCache). And these caches have a low timeout value as those cached information needs to be available only for the lifetime of the processing Thread or the Request... Ideally, these shouldn't be treated as caches rather pure data holders.

Considering the above, these new caches belong to the first category, hence the timeout value 900 is correct.

Either case, these configurations won't be needed to change by a user. These configurations are pure developer-oriented controls.
