### ISSUE TITLE
[Doc] in the[1] documentation refers we do not have caching config for the IdentityClaimMetadataMgtCacheManager

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#6548]
[1] - https://docs.wso2.com/display/IS570/Configuring+Cache+Layers

Ref: https://github.com/wso2/product-is/issues/6547

**Comment by denuwanthi** [comment]
@YvonneW is this task completed?

**Comment by YvonneW** [comment]
IdentityClaimMetadataMgtCacheManager cache manager was added to the 5.7 docs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
