### ISSUE TITLE
Recaptcha not working with secondary LDAP UserStore

### ISSUE THREAD

**Issue by viniciusalbino-ipnet** [wso2/product-is#6551]
The recaptcha was configured following the documentation[1], when I'm trying to log in with wrong password, the Claim "Failed Login Attempts" is increased as expected, but when count reach the maximum try to show Captcha, nothing happens, but when reach the count to lock account the account is locked as expected.

This issue don't happens if the user is in Primary UserStore.

Debug log is enabled, but not logging anything about the captcha or something co-related.

Ref: [1] https://is.docs.wso2.com/en/5.9.0/learn/configuring-recaptcha-for-single-sign-on/

Tested Version: 5.8.0 and 5.9.0-rc1

**Comment by janakamarasena** [comment]
@viniciusalbino-ipnet thank you for reporting the issue. It's fixed with https://github.com/wso2/carbon-identity-framework/pull/2468
