### ISSUE TITLE
Deleting Non-Existing User Store With UserStoreConfigAdminService Returns 200 OK

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#6558]
When deleting a user store with the [UserStoreConfigAdminService[1]](https://docs.wso2.com/display/IS560/Managing+User+Stores+with+APIs#ManagingUserStoreswithAPIs-deleteUserStore()), the API call returns 200 OK for a non-existing user store.

### Steps to Reproduce:

Try deleting a user store using the admin service action[1] with a non-existing user store domain name.

[1] https://docs.wso2.com/display/IS560/Managing+User+Stores+with+APIs#ManagingUserStoreswithAPIs-deleteUserStore()

**Comment by Geesa-Vihara** [comment]
This issue is not reproducible in the latest IS pack.
This was fixed by https://github.com/wso2/carbon-identity-framework/commit/2a513475b35ac610b928e93829c47cd01de23f6a. Hence closed this issue
