### ISSUE TITLE
Auto commit is enable default. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#6561]
Product version : 5.9-beta
Priority: High
Severity: Medium
Type: Bug

Intermittently get mysql jdbc error, 'Can't call rollback when autocommit=true' at request refresh token performance test scenario.  No entries  entered to change auto commit status in master data source. 
Concurrency user count is 50. 

Issue detected after adding  defaultAutoCommit to false also
Sample toml configurtions: 

```
[database.identity_db]
driver = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://wso2isdbinstance2.cd3cwezibdu8.us-east-1.rds.amazonaws.com:3306/IDENTITY_DB?useSSL=false"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.identity_db.pool_options]
maxActive = "300"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit="false"

[database.shared_db]
driver = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://wso2isdbinstance2.cd3cwezibdu8.us-east-1.rds.amazonaws.com:3306/REG_DB?useSSL=false"
validation_query = "SELECT 1"
username = "wso2carbon"
password = "wso2carbon"
[database.shared_db.pool_options]
maxActive = "300"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit="false"
```

[wso2is.log](https://github.com/wso2/product-is/files/3676152/wso2is.log)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
