### ISSUE TITLE
Support for session management gadgets in IS 5.7.0 with built in session service

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#6563]
$subject is not supported in IS 5.7.0 due to complexity in DAS to SP migration. The gadgets can be updated to use the built in session management APIs to manage sessions with minimum  capabilities. 

1. The gadgets will use the internal session data
2. The session entries will not have additional metadata such as user agent, IP, start time. This is due to the unavailability of additional data in the built in session data storage (for IS 5.7.0)
3. A session entry will be represented as a unique opaque identifier (like a UUID)

**Comment by senthalan** [comment]
This is fixed in master with https://github.com/wso2/product-is/issues/6054
