### ISSUE TITLE
Workflow in 5.8.0 not showing pending approvals

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-is#6566]
In latest wum version 5.8.0 when you run scenario 6 in Quick Start Guide 
(https://docs.wso2.com/display/IS580/Quick+Start+Guide)
Workflow is created. 
After new user self registration , log in dashboard as admin, no pending approval in **Pending approvals** view while newly self registered user are visible in user view in carbon portal.
All actions are disabled and it is not possible to remove pending users

<img width="901" alt="Screen Shot 2019-10-01 at 7 45 49 PM" src="https://user-images.githubusercontent.com/13038128/66010378-47077d80-e484-11e9-824d-e2fa8e633725.png">
<img width="861" alt="Screen Shot 2019-10-01 at 7 45 19 PM" src="https://user-images.githubusercontent.com/13038128/66010380-47077d80-e484-11e9-9169-b40bd5909b9e.png">

**Comment by NilukaSripalim** [comment]
To view the task / Pending approvals via the dashboard, the user that approves the account should have a role with permissions (below listed) and also the specific user or specific role should add in “Add Approval Step”.[1] in defined Workflow Definitions.

* Login
* Human Tasks>View Task List
* Workflow Management>BPS Profiles>View

[1]https://docs.wso2.com/display/IS530/Adding+a+New+Workflow+Definition (step 3)

**Comment by lpastor74** [comment]
I followed the documentation and setup role with all permissions still no approval task in the dashboard.
Add admin in the task ... Admin has
<img width="293" alt="Screen Shot 2019-10-02 at 9 21 06 PM" src="https://user-images.githubusercontent.com/13038128/66094725-a041e080-e55a-11e9-880e-8da5f3ae558c.png">
<img width="224" alt="Screen Shot 2019-10-02 at 9 20 55 PM" src="https://user-images.githubusercontent.com/13038128/66094726-a041e080-e55a-11e9-8068-ecb074df125e.png">
<img width="662" alt="Screen Shot 2019-10-02 at 9 18 35 PM" src="https://user-images.githubusercontent.com/13038128/66094727-a041e080-e55a-11e9-8ef5-27b80fbc3ea3.png">
<img width="878" alt="Screen Shot 2019-10-02 at 4 45 32 PM" src="https://user-images.githubusercontent.com/13038128/66094728-a041e080-e55a-11e9-8879-0cee1e4a4af6.png">



 all permissions, still nothing.

**Comment by NilukaSripalim** [comment]
This scenario  is working fine in IS 5.9.0. tested and validated.

**Comment by 1abhinandk** [comment]
What I have done is, open the wso2is-5.8.0/repository/deployment/server/jaggeryapps/portal/gadgets/approvals/gadget.xml in a text editor and added the change that is done in the PR: 
https://github.com/wso2/product-is/pull/5887/files

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
