### ISSUE TITLE
Error response when using invalid client id to get an access token 

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#6569]
**How to reproduce**
1-Configure a Service Provider in IS 5.7.0 or any downward IS version side 

2-Deploy the application(playground 2)

3-Try to get an access token with implicit or authorization code grant type using the invalid client id

`{"error_description":"A valid OAuth client could not be found for client_id: Ujin_7oc14NI23N_1tZtD9WTNUEa","error":"invalid_client"}`

The error response has thrown as above JSON response instead of the proper error page. but in other cases like using an incorrect redirect_uri, it gives proper error response page.

This problem has been fixed in IS 5.8.0 version(invalid client_id, invalid callback URL both are thrown the error page.).

**Comment by DMHP** [comment]
<OpenIDConnect> 
... 
<RedirectToOAuth2ErrorPage>true</RedirectToOAuth2ErrorPage>
...
</OpenIDConnect>
