### ISSUE TITLE
Usage of Shared User Roles

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#6570]
From the kernel code, we can observe that the users [can have shared roles[1]](https://github.com/wso2/carbon-kernel/blob/b4f8bd1a37b2ccaed37d75fb907cd595c3b61a98/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L734).

Does the identity server maintain this feature?

@darshanasbg your feedback is much appreciated.

[1] https://github.com/wso2/carbon-kernel/blob/b4f8bd1a37b2ccaed37d75fb907cd595c3b61a98/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L734

**Comment by darshanasbg** [comment]
No.. This is deprecated functionality and there are no APIs or other components that make use of this capability.

We need to clean up the source and DB schema removing such items

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
