### ISSUE TITLE
The MaxUserNameListLength Property Is Not Honored While Listing User List Of A Role

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#6573]
The `getUserListOfRole` action does not honor the property `MaxUserNameListLength` in the admin service RemoteUserStoreManagerService. The same issue is observed while listing users from the management console for a LDAP user store.

This issue is similar to https://github.com/wso2/product-is/issues/6511.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
