### ISSUE TITLE
The getRoleListOfUser API Does Not Support Filter And Limit

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#6574]
Although `listUsers` does support filter and limit in the UserStoreManager, the `getRoleListOfUser` API does not support this. It is supported for the `getUserListOfRoles` with https://github.com/wso2-support/carbon-identity-framework/pull/792, thus it needs to do the same for `getRoleListOfUser` action.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
