### ISSUE TITLE
Authorized OAuth apps are not listed in the dashboard as expected

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6576]
Version: 5.9.0 RC2

Scenario:

1. Create a few OAuth apps and try the authorization grant or implicit flow. Do not exchange the code for a token.
2. In the consent screen, select the "Approve Always" options
3. Log in to the user dashboard and view the approved authorized apps gadget
![image](https://user-images.githubusercontent.com/5237653/66109967-5d781b00-e5e3-11e9-91cc-76ca9d793819.png)

(No authorized apps will be displayed)

4. Exchange the code for a token and then check the approved authorized apps gadget
![image](https://user-images.githubusercontent.com/5237653/66110028-84cee800-e5e3-11e9-8dbe-67664e3dc289.png)

4. Revoke the token and then check the gadget again. You will see that the list will be empty.

This behaviour is incorrect since in the next authorization code you will not be prompted for consent. So unless an app has an active token, the end-user cannot revoke the consent given to the app which is not correct.

A user should be able to revoke the consent given to an app anytime regardless of whether the app has obtained a token using the provided consent or not.

**Comment by madurangasiriwardena** [comment]
Closing the issue since the dashboard application is not shipped with the product anymore.

**Comment by mefarazath** [comment]
Have we verified this behaviour with the new user portal?

**Comment by LahiruLS** [comment]
I have checked in the latest restAPIs and the behavior is still the same. We need to improve the logic.
https://is.docs.wso2.com/en/5.10.0/develop/authorized-apps-rest-api/#/me/listLoggedInUserAuthorizedApps
