### ISSUE TITLE
Failing the SAML logout request when NameID Format is not found 2 ;)

### ISSUE THREAD

**Issue by boulik** [wso2/product-is#6578]
Hello.
I'm trying configure WSO2IS(5.7) with shibolleth as IDP. If SLO (SP initialized ) is made within 15 min after SSO, flow runs ok.  This was repaired in pull [wso2-extensions/identity-outbound-auth-samlsso#65](https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/65). :) 
If SLO (SP initialized ) is made 15 min after SSO, logout request on IDP fails. Problem is missing atribute format in nameid element. I was debug code and if i add nameidformat, SLO  wil run correct. 
I will made some pullrequest, but i dont know where is proper place to remember this info after succesfull SSO. Can anyone help me?
Thanks a lot. 
Slavo

**Comment by rileyw** [comment]
What's the status of this bug?
