### ISSUE TITLE
Keystore config of default deployment.toml needs to be updated

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6581]
Current:
[keystore.primary]
name = "wso2carbon.jks"
password = "wso2carbon"

Correct
[keystore.primary]
**file_name** = "wso2carbon.jks"
password = "wso2carbon"

**Comment by madurangasiriwardena** [comment]
Relates to https://github.com/wso2/carbon-kernel/issues/2334

**Comment by gdiamond** [comment]
This applies to all _*.toml_ files under _./modules/integration/tests-integration/tests-backend/src/test/resources/artifacts/IS_ as well.
