### ISSUE TITLE
5.9-RC2 Brand new instalation: $.get(...).error is not a function     at drawGadgets

### ISSUE THREAD

**Issue by L0rDPSYCH0** [wso2/product-is#6583]
Brand new fresh installation, started application, logged in to the user dashboard and getting this error:

![image](https://user-images.githubusercontent.com/12871744/66129524-c0c07800-e5f8-11e9-99b8-6701ef5231ed.png)

I don't think I am doing anything wrong since I have not modified any installation files.

**Comment by piraveena** [comment]
Thanks for reporting this issue. 

This happens, because .error(..) is not supported in jquery-3.4.1. We couldn't find any blockers in accessing the dashboard due to this issue. We are checking on this. Meanwhile, Did you find any blocking issues in accessing dashboard due to this error?

**Comment by L0rDPSYCH0** [comment]
I don't have any blocking issues... Only issue I have is with the alignment of gadgets, but that may not be related to this. For some reason the gadgets show up like this 
![image](https://user-images.githubusercontent.com/12871744/66391837-da860480-e9d6-11e9-9572-11dd5d3b3451.png)
2 / 1 / 1
 instead of 2 / 2
Or maybe I am not writing the x , y variables correctly in the gadget.json

**Comment by janakamarasena** [comment]
Closing this issue as from IS-5.10.0 onwards the dashboard is replaced with the user portal
