### ISSUE TITLE
[Conf] TOML configs for the jmx.xml

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6588]
The following XML config in the `<IS_HOME>/repository/conf/etc/jmx.xmll` need to be mapped to TOML configs as it is referred to in [1] and [2]. 

`RMIRegistryPort`

[1] https://is.docs.wso2.com/en/5.9.0/administer/default-ports-of-wso2-products/#jmx-monitoring-ports
[2] https://is.docs.wso2.com/en/5.9.0/administer/jmx-based-monitoring/

**Comment by senthalan** [comment]
Here is the corresponding configuration
[monitoring.jmx]
rmi_server_start = "true"
rmi_registry_port = "9999"
rmi_server_port = "1111"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
