### ISSUE TITLE
[Conf] TOML Configs for tasks-config.xml

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6589]
Need the TOML configs for the following configs in the `<PRODUCT_HOME>/repository/conf/etc/tasks-config.xml` file as it is referred in [1]

```
<defaultLocationResolver>
            <locationResolverClass>org.wso2.carbon.ntask.core.impl.RuleBasedLocationResolver</locationResolverClass>
            <properties>
                <property name="rule-1">HIVE_TASK,HTTP_SCRIPT.*,192.168.1.*</property>
                <property name="rule-2">HIVE_TASK,.*,192.168.2.*</property>
                <property name="rule-5">.*,.*,.*</property>
            </properties>
    </defaultLocationResolver>
```

[1] https://is.docs.wso2.com/en/5.9.0/administer/configuring-the-task-scheduling-component/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
