### ISSUE TITLE
[Config] TOML Configs for Access_Log_Valve

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6599]
Please provide the following configs that were available in the `catalina-server.xml` as it is referred in [1]

```
<Valve className="org.apache.catalina.valves.AccessLogValve"
    directory="${carbon.home}/repository/logs"
    prefix="localhost_access_log_sample."
    suffix=".log"
    pattern="combined"
```

[1] [https://is.docs.wso2.com/en/5.9.0/administer/http-access-logging/](https://is.docs.wso2.com/en/5.9.0/administer/http-access-logging/)

**Comment by senthalan** [comment]
The access log pattern can be changed through,

```
[http_access_log]
pattern = "%h %l %u %t %r %s %b %{Referer}i %{User-Agent}i %T"
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
