### ISSUE TITLE
[Config] TOML Configs for master-datasources.xml 

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6601]
The corresponding TOML configs in the `master-datasources.xml` are required as they are referred in [1]:

- maxActive
- maxWait
- minIdle
- maxIdle
- testOnBorrow
- validationInterval
- validationQuery
- MaxPermSize

[1] https://is.docs.wso2.com/en/5.9.0/administer/performance-tuning/#jdbc-pool-configuration

**Comment by senthalan** [comment]
These properties has to be defined under the [database.identity_db.pool_options].
```
[database.identity_db.pool_options]
maxActive = ""
maxWait = ""
minIdle = ""
maxIdle = ""
testOnBorrow = ""
validationInterval  = ""
validationQuery = ""
MaxPermSize = ""
```

Note that these configs will be applied to the  identity_db. We need to configure the same for the other dbs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
