### ISSUE TITLE
5.9 Unable to Start

### ISSUE THREAD

**Issue by L0rDPSYCH0** [wso2/product-is#6606]
So the issue I have is the following: A brand new installation of WSO2 5.9. If I change nothing, it stars. 

I want to modify some carbon UI attributes. I unzip the org.wso2.carbon.ui_4.5.1.jar as I did for previous versions, I change a couple of css classes, rezip everything as a jar, put it back into it's folder. 

When I try to start again it just freezes. I can't find any log or any sort of error message as to why it will not start.
![image](https://user-images.githubusercontent.com/12871744/66392103-9810f780-e9d7-11e9-8662-df19133e6312.png)
 If I put back the original jar, it starts.  

I am assuming there might be some sort of jar validation or signature check but I have not found any information on it, especially since this worked properly in 5.8 and I don't see any other way of modifying the Carbon Framework UI. ( End Goal is to change the color scheme for the Carbon Interface, no other changes )

**Comment by JKAUSHALYA** [comment]
Instead of directly replacing the jar file, can you try to patch it[1]? (Change the jar the way you want, then instead of replacing it, just put it into the /repository/patches folder maybe under patch9999 folder.)

[1] https://docs.wso2.com/display/ADMIN44x/WSO2+Patch+Application+Process

**Comment by L0rDPSYCH0** [comment]
I tried this, but as the application starts is does not pick up my changes, it shows the original content. (fonts/colors etc. ) 
I am stuck on this.

**Comment by JKAUSHALYA** [comment]
In the logs, do you see a log stating "Patch changes detected"? Check for this to verify whether the patch correctly applied.

**Comment by L0rDPSYCH0** [comment]
No, I am not seeing this in the log. I also tried putting the jar file in dropins but that has not done anything. 
I don't understand what happened from 5.8 - 5.9 regarding this matter since in 5.8 it worked perfectly. Is there a setting I would need to turn off ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
