### ISSUE TITLE
Updating multiple SPs in different browser tabs in same session leads to inconsistancies

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#6613]
Please follow the below steps to reproduce the issue.

1. Start the WSO2 identity server 5.8.0 and navigate to the Home > Identity > Service Providers > Add and add two SAML service providers with different names(testsp1 and testsp2). 
2. Then edit both service providers on different tabs of the same browser. Then also click on the edit of both issues of the both service providers.
3. Now you refresh one of the SP's tabs (testsp1).
4. Then go to the other tab where we open the (testsp2) issuer **without a refresh** and update some of the parameters in the service provider and update.
5 Now you can see that actually, it is updating the service provider 1(testsp1) instead of the service provider 2.
6. Now if we check for the testsp1 issuer configurations they have changed with the values of the testsp2.
7. Because of this behaviour in the registry path /_system/config/repository/identity/SAMLSSO contains data of the previous Issuer and users can not create an Issuer with the same name due to this.

This seems to be a buggy behaviour in the latest product release.

**Comment by LahiruLS** [comment]
https://drive.google.com/file/d/1WgCRK8MxJukPOC8cVy-PUy_03tImTHoy/view?usp=sharing
Reproduce video

**Comment by LahiruLS** [comment]
Hi All,
This issue can happen the same way for the OpenIdConnect service providers as well. I was able to reproduce inconsistence behaviour. We may need to prioritize this fix this.

**Comment by pulasthi7** [comment]
The above PR fixes the issue for SAML SPs only. Need to check and fix other such usages for other inbound auth protocols

**Comment by tharindu-bandara** [comment]
Re-opened as per https://github.com/wso2/product-is/issues/6613#issuecomment-557473119

**Comment by mefarazath** [comment]
The issue of OAuth/OpenID Connect SPs being affected is already tracked and fixed with https://github.com/wso2/product-is/issues/3705

Fix is available from IS 5.8.0 onwards

**Comment by nilasini** [comment]
This issue needs to fix in IS-5.8.0 for SAML protocol

**Comment by emswbandara** [comment]
@nilasini @ivantha @DinikaSen is this issue fixed in public? if so, shall we close the git issue?

**Comment by DinikaSen** [comment]
This issue is fixed in public.

**Comment by madurangasiriwardena** [comment]
Closed based on the last comment.
