### ISSUE TITLE
Review the email OTP usecases

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6617]
Currently, we do have a configuration property called `usecase` for email OTP. If we configure any value for this, it will always pick the username from the first step [1]. But there are cases where we do configure a different step as the subject step. According to the current implementation, if we are to use the correct subject from the subject step, we have to comment out the `usecase` property from the email OTP configurations. Therefore it is required to review the `usecase` configuration in the authenticator.

The problem of binding to the subject from the first step is being used could be there in other 2nd factor authenticators as well. We will need to review all the 2nd-factor authenticators on this issue.

Additionally, the description of `usecase` doesn't seem to be very straightforward for first-time users [2]. Maybe some diagrams could help. Also, we could enable `useEventHandlerBasedEmailSender` by default in the product to avoid using axis2 transport for email sending. 

The documentation pages need to be updated with the info from the git hub doc [2]

[1] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L228
[2] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/docs/config.md

**Comment by rksk** [comment]
Related: https://github.com/wso2/product-is/issues/6604

**Comment by rksk** [comment]
`FederatedAuthenticatorUtil.setUsernameFromFirstStep(context);` has following two lines.
```
username = getLoggedInLocalUser(context);
authenticatedUser = getUsername(context);
```
The first one iterates the auth steps backward and find a subject. But the second one iterates from the beginning and find a subject. So, if we had multiple steps before the 2nd-factor auth (TOTP, email OTP etc), there is a possibility on those two returns different values.

Due to this issue, we are unable to use "useEventHandlerBasedEmailSender" for most of the 2nd factor authenticators when we have more than one step before the email OTP, SMS OTP, TOTP authenticator. Because when we enable "useEventHandlerBasedEmailSender", it tries to make use of both params `username` and `authenticatedUser` set by `FederatedAuthenticatorUtil.setUsernameFromFirstStep(context);`. which have different usernames.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
