### ISSUE TITLE
SP listing page size should be configurable 

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#6620]
Current SP listing page size is 10 and page size is not configurable. If we have more service providers we have to go through several pages to find a particular SP. Therefore the SP listing page size should be configurable.

Affected Version: 5.6.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
