### ISSUE TITLE
URL encoded values are getting stored as it is without decoding it in the SCIM user creation flow 

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#6630]
For example, when we create a user with URL encoded value for the givenName, it's stored as the URL encoded value instead of decode and store the actual value. When we do the get request for that user also in the response URL encoded value is reflected.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
