### ISSUE TITLE
Double submits and user idle in Identifier First authenticator

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6633]
As we have done in [1], we have to handle two following cases in Identifier First authenticator form as well.
- Double submits (we have fixed it to some extent in [1,2], but still user may click submit twice in a slow network)
- Idling on the page until authentication context expires

Since basicauth.jsp and identifierauth.jsp are included in the login.jsp, we could be able to reuse the code block written in [1] for both basic and identifier-first cases by moving it into login.jsp.

[1] https://github.com/wso2/carbon-identity-framework/pull/2369
[2] https://github.com/wso2/product-is/issues/6032
[3] https://github.com/wso2/carbon-identity-framework/pull/2337

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
