### ISSUE TITLE
Issue with the Quick Start Guide in 5.8.0 version

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-is#6635]
hi,

I wanted to configure my IS version 5.8.0 with users and service providers of the Quick Start Guide. I run the corresponding scripts, however even if everything is working fine, although the users are visible under 'Users', no service providers are visible!

**Comment by stefanonegri** [comment]
closed

**Comment by wijith7** [comment]
Hi stefanonegri

We use Cameron credentials to create service providers therefore the service providers only visible if you log using Cameron credentials.

Thanks 
wijith
