### ISSUE TITLE
[Configs] TOML Configs for catalina-server.xml

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6637]
Need the corresponding TOML configs for the following as it is referred in the [1]

```
<Engine name="Catalina">

... 
 <!-- Authentication and Authorization valve for the rest apis and we can configure context for this in identity.xml  -->
 <!--Valve className="org.wso2.carbon.identity.auth.valve.AuthenticationValve"/>
 <Valve className = "org.wso2.carbon.identity.authz.valve.AuthorizationValve"/-->
```

[1] https://is.docs.wso2.com/en/5.9.0/develop/authenticating-and-authorizing-rest-apis/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
