### ISSUE TITLE
[Configs] TOML Configs for application-authentication.xml

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6638]
Need the toml config for the `sessionDataKey` element in the`application-authentication.xml` as it is mentioned in [1]

[1] https://is.docs.wso2.com/en/5.9.0/develop/authentication-data-api/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
