### ISSUE TITLE
XACML REST API call fails

### ISSUE THREAD

**Issue by shazni** [wso2/product-is#6644]
Affected version - 5.9.0

Create a new XACML policy using the 'Basic Policy Editor', with below details with First applicable rule combining algorithm
The policy is based on a resource 'user'
Add a 'Permit' rule based on below
Resource is equal 'user'
User's role is equal 'Manage'
Action Name is equal to 'add_user'

Add a Deny rule as below
Resource is equal 'user'
User's role is equal 'admin'
Action Name is equal to 'add_user'

Publish the policy.
Create a user named david and assign him to a role name 'Manager'.

Use the below curl command. It fails with 'Indeterminate' state. (xacml-request.json) is given at the bottom. 

curl -k --user admin:admin --header "Content-Type:application/json" https://localhost:9443/api/identity/entitlement/decision/pdp -d @xacml-request.json

{"Response":[{"Decision":"Indeterminate","Status":{"StatusMessage":"Couldn\u0027t find AttributeDesignator attribute","StatusCode":{"Value":"urn:oasis:names:tc:xacml:1.0:status:processing-error"}}}]}

This is working fine in IS 5.8.0. The UI try it tool also intermittently fails. 

`
{"Request":{"Action":{"Attribute":[{"AttributeId":"urn:oasis:names:tc:xacml:1.0:action:action-id","Value":"add_user"}]},"Resource":{"Attribute":[{"AttributeId":"urn:oasis:names:tc:xacml:1.0:resource:resource-id","Value":"user"}]},"AccessSubject":{"Attribute":[{"AttributeId":"urn:oasis:names:tc:xacml:1.0:subject:subject-id","Value":"david"}]},"Environment":{"Attribute":[{"AttributeId":"urn:oasis:names:tc:xacml:1.0:environment:environment-id","Value":"m"}]}}}
`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
