### ISSUE TITLE
Unit tests not executing with debug logs

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6645]
In some components even when the tests are configured to run with debug logs enabled it does not. This was observed when the pax logging dependency is used.

This causes the code coverage to drop below the minimum threshold set in the jacoco plugin and the build fails.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
