### ISSUE TITLE
Customising the values for the HTTP connection configurations in JWKS based JWT validator

### ISSUE THREAD

**Issue by chandimajayawickrama** [wso2/product-is#6646]
For the customization of the HTTP connection configurations in JWKS based JWT validator, **the unit of time**  (i.e milliseconds) configured and the **allowed values** (i.e timeouts, in milliseconds, zero for infinite. Must not be negative) are not mentioned in the documentation [1].

[1] https://docs.wso2.com/display/IS570/Validating+JWT+based+on+JWKS#ValidatingJWTbasedonJWKS-ConfiguringJWKSbasedJWTValidator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
