### ISSUE TITLE
Role mapping flow is needed to be refactored

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#6648]
In the authentication-framework,  we perform the role mapping first and then perform the claim mapping.  

Role mapping is happening in two steps

1. IDP role mapping where IDP role -> Local role 
2. SP role mapping where Local role ->  SP role

These transformations are handled by separate methods. However, claim mapping is happening at once in a single method. 

While performing claim mapping we are **expecting only Idp role mapped values** but currently, we are providing roles with SP mapping as well.

We need to refactor the code to reflect the correct behaviour in role mapping

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
