### ISSUE TITLE
5.9.0 - Overriding files in configuration directory

### ISSUE THREAD

**Issue by LucasHaddad** [wso2/product-is#6649]
The new version of wso2is doesn't let me change the configuration files (e.g., `identity.xml`).
How can I use [is as km for apim](https://medium.com/wso2-learning/how-to-protect-your-apis-with-self-contained-access-token-jwt-using-wso2-api-manager-and-wso2-75673d8a4686) with the server's ConfigParser overriding it? Is there a flag or the manual cofiguration is enough now (didn't work for me, but may be my fault)?

When I've tried to use the manual configurations only, I've got this:
```
{
   "error_description": "Signature or Message Authentication invalid.",
   "error": "invalid_grant"
}
``` 
While trying to authenticate in the apim using the idp retrieved JWT.

The previous versions (5.7 and 5.8) works just fine, using the `.deb`.

I'm using ubuntu 19.04 and the `.zip` of wso2is-5.9.0 (using the java 11 openjdk amd64) and wso2am-2.6.0 (using the java 1.8.0 openjdk amd64).

P.S.: I've tried using the same java (1.8.0) for both, and it just throws the same error. The apim can't be run using java 11 (1.7.0 and 1.8.0 only).

**Comment by ayshsandu** [comment]
IS-5.9.0, WSO2 has introduced a new configuration model[1] where the majority of the configurations are now managed via a single file; [Home]/repository/conf/deployment.toml if it is available in the location [Home]/repository/conf/. You may fall back to old .xml based config model by removing this file from the location. It is expected to reset changes in .xml configuration files unless these configurations are now represented in deployment.toml file, if the file is present. 

I have added some sample mappings in [2] that I've used sometimes back to identify the corresponding deployment.toml configurations, for .xml configs, in case you find it interesting.

[1] https://wso2.com/blogs/thesource/2019/10/simplifying-configuration-with-WSO2-identity-server
[2] https://github.com/ayshsandu/samples/tree/master/config-mapping

Thanks!
-Ayesha

**Comment by LucasHaddad** [comment]
Thank you very much @ayshsandu . I'll try it monday!

**Comment by kasperglobal** [comment]
This is a major change/feature. I'd like to suggest that this be included as a warning/notice in the download page [1]. I struggled a whole day to figure out why it's reverting back my config changes.

[1] https://wso2.com/identity-and-access-management/#

**Comment by ravihansa3000** [comment]
This is a major change/feature. I'd like to suggest that this be included as a warning/notice in the download page [1]. I struggled a whole day to figure out why it's reverting back my config changes.

[1] https://wso2.com/identity-and-access-management/#

**Comment by rohitmp** [comment]
I feel this should be prominently specified in documentation or elsewhere appropriately.

**Comment by jing-zhou** [comment]
too sad that 5.9.0 has dropped support of custom [JWTAccessTokenBuilder](https://github.com/wso2/msf4j/tree/v2.8.1/samples/jwt-claims/JWTAccessTokenBuilder) . I just can not achieve that by either the old .xml or the .toml

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
