### ISSUE TITLE
[TOML Config] claim-config.xml

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6656]
Need the corresponding TOML configs following as it is referred in [1].

```
<Claim>
   <ClaimURI>http://wso2.org/claims/username</ClaimURI>
   <DisplayName>Username</DisplayName>
   <AttributeID>mail</AttributeID>
   <Description>Username</Description>
</Claim>
```

[1] https://is.docs.wso2.com/en/5.9.0/learn/logging-in-to-salesforce-with-integrated-windows-authentication/

**Comment by janakamarasena** [comment]
This will not have a toml configuration as the claim-config.xml is a data file.
