### ISSUE TITLE
An error avoids updating the mapped attributes of a claim, when there are multiple attribute mappings

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#6660]
**Steps to reproduce**

1) Configure a couple of secondary user stores.

2) Go to the default WSO2 claim dialect.

3) Select a claim and add two more attribute mappings to the aforementioned secondary user stores and save.

4) Re-open the claim and go to the edit screen.

5) Remove the second attribute mapping in the list and click on the update button.

**Observations**

The update button won't work and the below error message appears in the Chrome browser's console.
```
Uncaught TypeError: Cannot read property 'options' of null
    at validate (update-local-claim.jsp?localClaimURI=http%3A%2F%2Fwso2.org%2Fclaims%2Femails.other:822)
    at HTMLInputElement.onclick (update-local-claim.jsp?localClaimURI=http%3A%2F%2Fwso2.org%2Fclaims%2Femails.other:1192)
```

**Notes**

1) The error doesn't appear when removing the last mapping.

2) The browser console says that a few JS files can't be loaded too.

e.g. https://localhost:9443/carbon/carbon/admin/js/main.js

There is a duplicate 'carbon' element in the URL

**Comment by piraveena** [comment]
The update button won't work in firefox also. But the error message is different as below.

```
TypeError: userstoreElem is nullupdate-local-claim.jsp:829:50
    validate https://localhost:9443/carbon/identity-claim-mgt/update-local-claim.jsp?localClaimURI=http://wso2.org/claims/department:829
    onclick https://localhost:9443/carbon/identity-claim-mgt/update-local-claim.jsp?localClaimURI=http://wso2.org/claims/department:1

```

**Comment by piraveena** [comment]
> The browser console says that a few JS files can't be loaded too.
> 
> e.g. https://localhost:9443/carbon/carbon/admin/js/main.js
> 
> There is a duplicate 'carbon' element in the URL 

Related to https://github.com/wso2/product-is/issues/5346
