### ISSUE TITLE
ERR_CERT_REVOKED error when logging into management console from chrome

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6663]
**Description:**
In macOS after upgrade to macOS 10.15 Catalina when trying to log into the carbon management console using chrome browser "ERR_CERT_REVOKED" message is displayed. The certificate is a valid cert.

Possible cause:
https://support.apple.com/en-us/HT210176

> TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).

**Comment by madurangasiriwardena** [comment]
After generating a key with below command I was able to resolve the issue.
`keytool -genkey -alias wso2carbon -keyalg RSA -keysize 2048 -keystore wso2carbon.jks -dname "CN=localhost, OU=Home,O=Home,L=SL,S=WS,C=LK" -storepass wso2carbon -keypass wso2carbon -ext san=dns:localhost -ext ExtendedKeyUsage=serverAuth -validity 825`

We have to generate a new keystore with above options and in-corporate to the product.

**Comment by madurangasiriwardena** [comment]
We need to identify what ExtendedKeyUsage options we have to use for our key pair.

**Comment by janakamarasena** [comment]
since we mention to have aliases for localhost in some of our guides, if it is possible we may need to add a wildcard(*) as a SAN.
