### ISSUE TITLE
5.10.0 Roadmap

### ISSUE THREAD

**Issue by kranidiotis** [wso2/product-is#6668]
Is there any roadmap for 5.10.0?

**Comment by madurangasiriwardena** [comment]
Hi @kranidiotis,

You can find our product roadmap from [here](https://wso2.com/identity-and-access-management/product-roadmap/). From the mentioned near-term items, we are mainly working on the items mentioned in the identity administration section for 5.10.0 release.

**Comment by darshanasbg** [comment]
Closing as answered.
