### ISSUE TITLE
Cannot update the checkbox in 'Use user store domain in roles' service provider if the property is not available in DB

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#6676]
This could happen in migrated setups (from < 5.5.0)
If SP_METADATA table doesn't contain USE_DOMAIN_IN_ROLES we cannot update the 'Use user store domain in roles' property from the management console.

Steps to reproduce. 

- In IS 5.5.0 or above create the SP.
- Go to SP_METADATA table
- Remove the USE_DOMAIN_IN_ROLES row from the table
- Load the SP from the management console
- Update the mentioned property
- Reload the SP from UI
- The property change is not reflected

**Comment by rksk** [comment]
The following query can be used to manually add the missing DB records for each of the SPs
```
INSERT INTO SP_METADATA (NAME, VALUE, DISPLAY_NAME, TENANT_ID, SP_ID) 
SELECT 'USE_DOMAIN_IN_ROLES', false, 'DOMAIN_IN_ROLES', TENANT_ID, ID FROM SP_APP;
```
