### ISSUE TITLE
Documenting IAM event publishers

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#6682]
Type: doc
Product version: 5.7 +

Add following IAM event publishers feature to product document. [1]

[Event publisher.pdf](https://github.com/wso2/product-is/files/3743538/Event.publisher.pdf)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
