### ISSUE TITLE
Support  "x5c" optional parameter in JWKS

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#6686]
As per the specification [1]  "x5c" is an optional parameter. 
From "x5c" (X.509 certificate chain) parameter, will contain a chain of one or more PKIX certificates. The certificate chain is represented as a JSON array of certificate value strings. Each string in the array is a base64-encoded PKIX certificate value. 

[1] https://tools.ietf.org/html/rfc7517#section-4.7

**Comment by nilasini** [comment]
It causes a known regresion https://github.com/wso2/product-is/issues/14899

**Comment by ThaminduDilshan** [comment]
Another known issue https://github.com/wso2/product-is/issues/18817
