### ISSUE TITLE
Archived log files getting replaced in IS-5.9.0

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6696]
Log4j2 supports two main methods to archive and backup the log files. 

1) Rollover based on file size. 
2) Rollover based on a time period.

In IS-5.9.0 by default, both these options are configured. which are, 

SizeBasedTriggeringPolicy
TimeBasedTriggeringPolicy

If the configured file size is 10MB and the Time period is 1 day. If the file size exceeds the 10MB within a day. then it will create an archive file with the current date. After that when a day is completed that file will be get overridden by a new file with the same file name. 

Suggested Labels: Config, IS-5.9.0

**Comment by Buddhimah** [comment]
Rollover based on a time period. should be remained and Rollover based on file size should be added as a feature that can be configured based on the requirement

**Comment by Buddhimah** [comment]
To avoid this issue file pattern should be as follows as per the official documentation.[1]
appender.CARBON_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy}.%i.log

[1]. https://logging.apache.org/log4j/2.x/manual/appenders.html

**Comment by ayshsandu** [comment]
I think the same should be fixed for other loggers as well.

```
appender.CARBON_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy}.log
appender.AUDIT_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/audit-%d{MM-dd-yyyy}.%i.log
appender.ATOMIKOS_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/tm-%d{MM-dd-yyyy}.%i.out
appender.CARBON_TRACE_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/wso2carbon-trace-messages-%d{MM-dd-yyyy}.%i.log
appender.CORRELATION.filePattern =${sys:carbon.home}/repository/logs/${instance.log}/correlation-%d{MM-dd-yyyy}.%i.log
appender.DELETE_EVENT_LOGFILE.filePattern =${sys:carbon.home}/repository/logs/delete-event-%d{MM-dd-yyyy}.%i.log
appender.TRANSACTION_LOGFILE.filePattern = ${sys:carbon.home}/repository/logs/transaction-%d{MM-dd-yyyy}.%i.log
```
