### ISSUE TITLE
Correlation Log file path is invalid in the  IS-5.9

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6700]
Following is the log file path provided.

`appender.CORRELATION.File=${carbon.home}/repository/logs/${instance.log}/correlation.log`

This will create a folder as ${instance.log}. and within that file correlation.log will be created which is unexpected. 

Observability Doc is updated with the expected behavior: https://github.com/wso2/docs-is/pull/591

In 5.8 file created in the logs folder, itself but it has above same configuration in log4j.properties file.

**Comment by ShanChathusanda93** [comment]
Can be reproced in IS 5.10.0 as well

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
