### ISSUE TITLE
[Configs] TOML configs for symmetric encryption

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6701]
Need the corresponding TOML configs that are available in the `carbon.xml` file as it is referred to in [1]. 

```
<SymmetricEncryption>
        <IsEnabled>true</IsEnabled>
        <Algorithm>AES</Algorithm>
        <SecureVaultAlias>symmetric.key.value</SecureVaultAlias>
</SymmetricEncryption>
```

[1] https://is.docs.wso2.com/en/5.9.0/administer/symmetric-encryption/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
