### ISSUE TITLE
[Config] bps-datasources.xml.j2 should follow the pattern followed in the master-datasources.xml.j2 in templating

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6704]
The database name is not relevant to the template we provide that from the deployement.toml and infer.json will map it to relevant configs. With the current implementation, we need to provide all the configurations from the deployement.toml as follows

```
{
  "bps_database.config.url" : "jdbc:h2:file:./repository/database/jpadb;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE",
  "bps_database.config.username" : "wso2carbon",
  "bps_database.config.password" : "wso2carbon",
  "bps_database.config.driver" : "org.h2.Driver"
} 
```
This should be able to given as follows 
```
           [database.bps_db]
           type = "postgre"
           hostname = "localhost"
           name = "testdb"
           username = "regadmin"
           password = "regadmin"
           port = "5432"
```

Url and driver should be created using infer.json. After this fix please update all the docs relevant to databases. 

such as: changing-to-postgresql, changing-to-mysql

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
