### ISSUE TITLE
[TOML Configs] Identity claim metadata management cache layer

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6715]
Need the corresponding TOML configs for the following configs in `identity.xml` as it needs to be referred in [1].

```
<CacheManager name="IdentityClaimMetadataMgtCacheManager">
	    <Cache name="LocalClaimCache"   enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
	    <Cache name="ExternalClaimCache"  enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
	    <Cache name="ClaimDialectCache"  enable="true"  timeout="900" capacity="5000" isDistributed="false"/>   
</CacheManager>
```

[1] https://is.docs.wso2.com/en/5.9.0/administer/configuring-cache-layers/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
