### ISSUE TITLE
"validUntil" attribute in the metadata file used to create a service provider should be updated to the current or a newer date

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-is#6716]
When using the metadata file to create service providers, the "validUntil" attribute in the metadata file should be updated to a newer date. This should be updated in the docs

**Comment by darshanasbg** [comment]
This is fixed in the 5.9.0 docs.
https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml2-web-single-sign-on/

Have to fix other versions as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
