### ISSUE TITLE
[TOML Configs] XACML scope validation

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#6719]
Need the corresponding TOML configs for the following in the `identity.xml` file as it is being referred to in [1].

```
<ScopeValidationEnabledForAuthzCodeAndImplicitGrant>false</ScopeValidationEnabledForAuthzCodeAndImplicitGrant>
```

[1] https://is.docs.wso2.com/en/5.9.0/learn/validating-oauth-access-token-scope-using-xacml-policies-during-token-issuance/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
