### ISSUE TITLE
Customizing the management console in 5.9 - Crashes WSO2IS [5.9.0]

### ISSUE THREAD

**Issue by L0rDPSYCH0** [wso2/product-is#6727]
I have opened another issue that is still unresolved, I am trying my luck again. 

Following the instructions from here: 
https://docs.wso2.com/display/DS200/Customizing+the+Management+Console#CustomizingtheManagementConsole-Changingthelayout

I have modified the org.wso2.carbon.ui_4.5.1.jar  I have placed it back to it's original folder but the WSO2IS does not start. If I put the original jar back it starts. By some recommendation I have placed it in the patches folder, but it does not seem to be picking it up.

Please, I don't know what else to try / do . Do I need to sign the jar file somehow?

**Comment by madurangasiriwardena** [comment]
@L0rDPSYCH0, Sorry about the late response. After the change, what is the error you observed while starting the server?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
