### ISSUE TITLE
Inconsistent TOML properties in user-mgt.xml

### ISSUE THREAD

**Issue by renekaesler** [wso2/product-is#6728]
The following properties are inconsistent/are not working:

**rolename_javascript_regex (name in documentation):**
I have tried `rolename_java_script_regex` & `rolename_javascript_regex`. Both are not working.

**username_javascript_regex (name in documentation):**
The property `rolename_javascript_regex` is not working, but `username_java_script_regex` does.

It should be considered to name the `_javascript_` propertiers by the same pattern. E.g. `password_java_script_regex` is working as expected... so i would assume the other properties are named with `java_script` as well.

**Comment by GDRDABARERA** [comment]
Hi @ReneKaesler 
You can use the previous properties in the below format as well
Eg:
[user_store.properties]
UsernameJavaRegEx=".*"
RolenameJavaRegEx=".*"
UsernameJavaScriptRegEx=".*"
UsernameJavaRegExViolationErrorMsg=".*"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
