### ISSUE TITLE
Provide Adaptive Authentication function to check user roles without caching

### ISSUE THREAD

**Issue by ranga-siriwardena** [wso2/product-is#6729]
Current Adaptive Authentication related function, which is used to check user roles using caching internally. This is causing caching issues during authentication flow in multi node-setups when clustering is disabled. Need to provide Adaptive Authentication function to check user roles without caching to avoid this issue.

**Comment by gayashanbc** [comment]
https://github.com/wso2-extensions/identity-conditional-auth-functions/pull/53 can be merged once a new version of the carbon-kernel is released.
