### ISSUE TITLE
User Store Sample for Mongo DB

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#6731]
Need $subject to use as a reference implementation for any one who looking to integrate their user base maintained in a Mongo DB.

This user store has be build based on the NOSQL concepts, rather following other RDBMS user stores like JDBCUserStoreManager.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
