### ISSUE TITLE
Have meaningful values for the profile of default admin user in embedded ldap

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#6735]
Currently default admin user (username: "admin") in the embedded ldap have,
* firstname as "admin"
* lastname as "admin"
* email as "admin@wso2.com"

Email value is acceptable IMO, but firstname and lastname is not give the impression of what those values are.

This lead to confusion in the first impression with different service providers (such as default portals, samples and demos).

For an example with the https://github.com/wso2/product-is/releases/tag/v5.10.0-m3, if you just logged into the user-portal, it would look like following,

<img width="1113" alt="Screen Shot 2019-10-27 at 6 48 39 PM" src="https://user-images.githubusercontent.com/1617810/67635323-8d1cf900-f8eb-11e9-88a9-5e493b02c09b.png">

As firstname and lastname values used for prominent elements in that UI, at glance it would look like the portal have bugs, showing username duplicated in many places..

This would be the case for product samples and demos. Hence, even it a minor thing, IMO it should be fixed.

**Comment by darshanasbg** [comment]
With the fix https://github.com/wso2-extensions/identity-userstore-ldap/pull/30, now the UI would like following,

<img width="1113" alt="Screen Shot 2019-10-27 at 7 09 59 PM" src="https://user-images.githubusercontent.com/1617810/67635459-914a1600-f8ed-11e9-90f1-40d7cdec0c4a.png">

This fix the problem to 95% (since i'm not a very good fan of using John Does :) ) and as @jeradrutnam mentioned in https://github.com/wso2-extensions/identity-userstore-ldap/pull/30#discussion_r339340554, this is not gender neutral.

**Comment by darshanasbg** [comment]
Updated to use "John Smith"

**Comment by darshanasbg** [comment]
@jeradrutnam Do you have any suggestion for a replace the above?

It's better, if we can include this basic fix with the, this weeks milestone.

**Comment by jeradrutnam** [comment]
Shall we clear "Last Name" and keep only the "First Name"? And make the "First Name" as "**Administrator**"

**Comment by darshanasbg** [comment]
+1. Updated PR

**Comment by darshanasbg** [comment]
Now the portal looks like following,

<img width="1172" alt="Screen Shot 2019-10-31 at 5 58 27 PM" src="https://user-images.githubusercontent.com/1617810/67946910-6969f380-fc08-11e9-92a0-caa49ca62519.png">

**Comment by denuwanthi** [comment]
Reopening .
Revert PR https://github.com/wso2-extensions/identity-userstore-ldap/pull/31
