### ISSUE TITLE
[IS580] SCIM2 Post /Me does not receive confirmation email

### ISSUE THREAD

**Issue by reidlai** [wso2/product-is#6736]
I am using IS 5.8.0 and tried to use normal Self Registration REST API /Me endpoint to create user, I can receive email with Confirm Account Button and URL with confirmation code.

Then I switched to use SCIM 2.0 Self Registration REST API /Me endpoint, I didn't receive any email.  After checking database, there is no record in IDN_RECOVERY_DATA table of Identity RDBMS store.

Is it normal?

**Comment by IsuraD** [comment]
@sarubi , this is the current behavior of the product. SCIM2/Me endpoint does not support account registration with email verification yet.

**Comment by IsuraD** [comment]
We can treat this as an improvement in the future.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
