### ISSUE TITLE
[Doc] [5.7.0] configuring UseEntityIdAsIssuerInOidcDiscovery property

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#6737]
The  identity.xml file found in the <IS_HOME>/repository/conf/identity/ folder does not include the following property

Therefore, we need to correct documentation [1] as follows.

1.Add the following property to the identity.xml file resides in <carbon-home>/repository/conf/identity directory. 
Under the `<OAuth>` tag.

```
<!-- If enabled, resident Idp entity id will be honoured as the issuer location in OpenId Connect Discovery -->
<UseEntityIdAsIssuerInOidcDiscovery>true</UseEntityIdAsIssuerInOidcDiscovery>
```

[1] https://docs.wso2.com/display/IS570/OpenID+Connect+Discovery

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
