### ISSUE TITLE
Add new API to configuration management rest API to get all resources for a specific resource type

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6742]
`/resource/{resource-type}`

Then the Create Resource Type response should point to the new API in its links attribute.

```
{
  "name": "string",
  "id": "string",
  "description": "string",
  "links": [
    {
      "href": "/t/abc.com/resource/publisher/",
      "rel": "resource"
    }
  ]
}
```

Label: future

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
