### ISSUE TITLE
User role claim is not updating in OIDC federated scenario

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#6746]
Hi Team,

I have configured an external Identity Provider as a federated IdP and enabled JIT provisioning. User is provisioned to the Identity Server successfully but later when updating user roles in external IdP and after the login, those changes don't get reflected to the Identity Server. Other claims (firstname, country) are updated successfully, except for the role claim.

We can easily reproduce this using two WSO2 Identity Server packs. Configure the second IS as an external IdP for the first IS and enable JIT provisioning.

**Observations**

- In the first login attempt, all the user claims provisioned to the first IS as expected.
- I tried changing the first name and country claim of the federated IdP and those changes got reflected after the next login attempt.
- When I change the role claim (tried adding new roles and removing existing roles) those changes didn't get reflected and I could see the initially provisioned roles in the user.

Thanks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
