### ISSUE TITLE
Token Cleanup constraint violation

### ISSUE THREAD

**Issue by praminda** [wso2/product-is#6747]
Constraint violation error comes up when running the token cleanup stored procedure after running the session cleanup procedure.

**Reason:** 
CHNK_IDN_OATH_ACCS_TOK_PRI and BATCH_IDN_OATH_ACCS_TOK_PRI is used in both session cleanup and token clean scripts.

https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/oracle-11.x/oracle-tokencleanup.sql#L251

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
