### ISSUE TITLE
Add Federated User Account Associations REST API 

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#6748]
The existing user account association REST API[1] only supports working with the local associations. Some additional APIs are needed in [1], in order to support this.

In summary, we need to have federated-association APIs for,
- GET, DELETE operations in /me
- GET, DELETE operations in /{user-id}

endpoints.

[1] https://is.docs.wso2.com/en/next/develop/association-rest-api/#/

**Comment by daucong** [comment]
With admin, why not add POST AND DELETE by user_id. Please update. Thanks!
