### ISSUE TITLE
Discovery endpoint shows pairwise subject identifier is supported but it is not

### ISSUE THREAD

**Issue by SachiniSiriwardene** [wso2/product-is#6749]
Even though the  well known endpoint documentation[1], mentions the subject_types_supported as "pairwise", it is not supported currently in the solution. 

[1] https://docs.wso2.com/display/IS570/OpenID+Connect+Discovery

**Comment by janakamarasena** [comment]
When calling the oidc discovery endpoint `https://localhost:9443/oauth2/oidcdiscovery/.well-known/openid-configuration` the following is available in the response.

```
"subject_types_supported": [
        "pairwise"
    ],
```
