### ISSUE TITLE
Migration changes related to Application Management APIs

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6751]
This issue will track the details related changes done in the Application Management API that would require a migration

**Comment by mefarazath** [comment]
Part of #6609

**Comment by mefarazath** [comment]
* New columns have been introduced to the SP_APP table. This would require a DB schema migration

**Comment by mefarazath** [comment]
WSDL of the Application Management service has changed significantly with the addition of new properties to the service provider model object. Therefore we need to document to instruct the SOAP API consumers to regenerate the stub or upgrade the dependency version of the stub.

**Comment by Abilashini** [comment]
The new column has been included in the migration for 5.10.0 release with https://github.com/wso2-extensions/identity-migration-resources/pull/39

**Comment by Abilashini** [comment]
> WSDL of the Application Management service has changed significantly with the addition of new properties to the service provider model object. Therefore we need to document to instruct the SOAP API consumers to regenerate the stub or upgrade the dependency version of the stub.

https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/#wsdl-of-the-application-management-service-has-been-changed
