### ISSUE TITLE
Implement a unique user identifier for WSO2 IS

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#6753]
Currently, we consider username of the user as an immutable attribute across the Identity Server and we do not maintain any other unique user identifier for all the users apart from the SCIM ID which is only applicable for SCIM enabled user stores. 

So we need to support an immutable user identifier that is unique across the system and maintains a mapping with all the other user attributes which can enable the following capabilities in the product.

- Provide a unique user identifier across the system - This id will be used for new Admin REST APIs, Identify the user internally and the same ID will be used as the SCIM ID as well.
- Username renaming capability - The users will be able to change them without having any impact on the existing system.
- Multi-attribute login capability - The users will be able to have multiple login identifiers such as username, email address, mobile number or any other identifier that’s unique across the system as for their preference.

**Comment by kranidiotis** [comment]
Do you think that maybe would be interesting to combine this task with an
SSI platform and this unique identifier could be a DID?

Στις Τρί, 29 Οκτ 2019 στις 6:50 μ.μ., ο/η Ashen Weerathunga <
notifications@github.com> έγραψε:

**Comment by madurangasiriwardena** [comment]
Hi @kranidiotis,
> Do you think that maybe would be interesting to combine this task with an SSI platform and this unique identifier could be a DID? 

Yes, that would be certainly doable if you implement a new user store manager to work with SSI platform and consider the unique user identifier to be the DID. The current extension points would allow such an implementation. However, at the moment we have not prioritized to implement such a user store manager immediately.

**Comment by madurangasiriwardena** [comment]
Closing the issue since the feature is implemented. However, user renaming capability and multi-attribute login capability is not implemented on top of the unique user identifier.
