### ISSUE TITLE
[Migration] Add federationAssociationId Column To IDN_ASSOCIATED_ID Table

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#6765]
The APIs introduced for the issue[1] requires deleting federated user association by id. But at the moment we don't have a unique id for a federated association of a given user in the table IDN_ASSOCIATED_ID.

Therefore a column is needed to be added to keep an ID in the table, for the requirement. This will introduce a migration effort(Please find the [PR](https://github.com/wso2/carbon-identity-framework/pull/2518) to add an additional column to the identity scripts.).

[1] [6748](https://github.com/wso2/product-is/issues/6748)

**Comment by Abilashini** [comment]
Included in the migration for 5.10.0 release - https://github.com/wso2-extensions/identity-migration-resources/pull/39
