### ISSUE TITLE
Create a separate widget with a table that contains the origin of the user instead of just a map.

### ISSUE THREAD

**Issue by rizmir22** [wso2/product-is#6767]
In the IS analytics, when the customer is using the geolocation feature, their access location (origin) will be shown on a world map. But the customer would like to have a separate widget with the table to show the origin of the customer. The customer is requesting this feature as an improvement.

**Comment by rizmir22** [comment]
The customer would like to have the cities of the origin as well with their country in the table representation.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
