### ISSUE TITLE
OAuth applications created are not retrieved when CaseInsensitiveUsername enabled

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-is#6781]
Steps to reproduce. 

1. Set the user store manager as JDBCUserStoreManager. Note that the below property is set as true OOB, in JDBCUserStoreManager in user-mgt.xml.

 "user_store.properties.CaseInsensitiveUsername": true

3. Create a new user with a name with both upper and lower case characters. (e.g. John) via management console.
2. Create OAuth application using registerOAuthApplicationData method of OAuthAdminService.
3. Call the admin service operation "getAllOAuthApplicationData" to get the created application. But the created app won't be returned. 

If the above configuration was set to "false",  "getAllOAuthApplicationData"  returns the created app.

Suggested labels: wso2is-5.9.0, wso2is-as-km-5.9.0
Type : Bug

**Comment by nilasini** [comment]
@rmsamitha Couldn't able to reproduce the issue in IS-5.9.0. Still could you able to reproduce the issue?

**Comment by madurangasiriwardena** [comment]
Closing the issue based on the above comment. Please feel free to re-open if you encounter the issue again.
