### ISSUE TITLE
[Doc]Clustering-related-configurations for multicast is not documented

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6783]
In this doc, https://is.docs.wso2.com/en/5.9.0/setup/deployment-patterns/#clustering-related-configurations
it only mentions about configurations related to WKA. 

Configurations for clustering using multicast need to be documented

**Comment by Madhu1029** [comment]
Hi @piraveena,

Have you found the multicast document?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
