### ISSUE TITLE
Dashboard cannot be accessed after configuring a additional connector in catalina-server.xml for X509 authentication and doing a port offset

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#6786]
Steps to reproduce the issue:

- Configure x509 authenticator according to the WSO2 documentation[1]. There is a step where the new connector is added with port 8443(you can configure only that part to reproduce the issue).

- Configure a port offset in carbon.xml. Eg Give a port offset of 7 

- Try to access the dashboard on port 9450, the user will be redirected to port 8450 which is not working.

In the logs, it can be seen that the management console also starts up on port 8450 but it cannot be accessed.

[1]https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
