### ISSUE TITLE
Governance identity store WSO2 IS 5.9.0

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#6787]
Hi

I am trying to configure the governance_identity_store as org.wso2.carbon.identity.governance.store.UserStoreBasedIdentityDataStore . I get an error that one attribute is unmapped http://wso2.org/claims/identity/failedLoginAttemptsBeforeSuccess even though I use the default claim-config.xml. In the claim-config.xml there is no entry on that attribute. Am I missing something?

Thank you

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
