### ISSUE TITLE
"isUserExistsInDomain" does not need to throw an exception. 

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#6788]
If you see this method [1].  It usually executes when pre authentication flow is initiated.  In this flow, user store domain of the user does not known in advance.   Therefore this [1] method is used to verify the user's domain.  
But it does not need to throw an exception as it can cause for issues when user stores are chaining.  As an example, if first user store is down, it would always throw exceptions for users in other user stores as well

[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/AccountConfirmationValidationHandler.java#L127

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
