### ISSUE TITLE
Improve Service provider DAO layer

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6793]
Currently, service provider update operation does multiple UPDATE DB calls to update separate columns of the same table. These can be combined to a single Update DB call. This would reduce the load on the DB significantly during the SP update.

Example:
https://github.com/wso2/carbon-identity-framework/blob/d25b13f2491c50e290eb5b5614a14dcb9f0ebf84/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java#L1238-L1329

There can be other places like this where we can cut down the number of DB calls by combining multiple DB calls.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
