### ISSUE TITLE
Provide support for end users to discover applications and access

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6794]
**Terms:**

- An application is discoverable for a user if the application is available in the user portal
- A discoverable application may or may not be accessible for a user based on runtime rules applied at the IdP level or application level.

**User Story:**
An application owner can,

1. Mark a application as discoverable.
2. For such discoverable application, owner can
2.a Assign a set of users that the application is discoverable for
2.b. Assign a set of roles that the application is discoverable for

If (1), application becomes available in the user portal of any user and they can access the app.
If (2.a), application becomes available in the user portal of the assigned users, and only they can access the app. Accessibility can further be restricted at runtime. 
If (2.b),  application becomes available in the user portal of the users, in the specified roles and only they can access the app. Accessibility can further be restricted at runtime. 

**Tasks:**

1. Provide support for an identity admin to flag an application as discoverable.
1.1 Add Java API - https://github.com/wso2/product-is/issues/6789
1.2 Provide UI support in management console - https://github.com/wso2/product-is/issues/6791
1.3 Implement a REST API for end users to consume - https://github.com/wso2/product-is/issues/6801
1.4 Add documentation - https://github.com/wso2/product-is/issues/6807
1.5 Add integration tests - https://github.com/wso2/product-is/issues/6808
1.6 Add samples - https://github.com/wso2/product-is/issues/6809
1.7 Address migration - https://github.com/wso2/product-is/issues/6810

**Comment by johannnallathamby** [comment]
The implementation in the latest milestone of IS 5.11.0 seems to only have the capability to always redirect the user to a URL that is configured in the application.

In my opinion, the following additional capabilities/changes are needed in this feature at a minimum: 
1. Ability to log-in using IdP initiated SSO without being redirected to the application first
2. Have the URL field as an optional field, where you can have a landing page if there is a anonymous view for the user

**Comment by svenzimmermann** [comment]
The functions in 5.11 always show all applications to all users. Has point 2a or 2b been implemented in the meantime?

**Comment by johannnallathamby** [comment]
2a and 2b will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/11
