### ISSUE TITLE
Provide support to customize .well-known/openid-configuration response from OIDC discovery

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#6795]
According to the current implementation, the OpenID Connect Discovery response is not customizable. It's good to have an extension point to customize it.

For example, if we have customized the IDTokenCustomClaimsCallBackHandler to inject additional claims to the id token. Those additional claims don't come under the "claims_supported" attribute of the discovery response even though they are available in the id token.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
