### ISSUE TITLE
Retrieve claims from userstore if not available in cache during ID token generation

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6796]
There are cases where the user claims are not found in the AuthorizationGrantCache. Currently we do recover the user claims from the userstore if the claim list is empty only
```
if (MapUtils.isEmpty(userAttributes) && !requestMsgCtx.getAuthorizedUser().isFederatedUser()) {
    ...
   claims = getClaimsFromUserStore(requestMsgCtx);
```
But there are rare cases, we do have the "sub" in `userAttributes` and no other claims. That case also needs to be handled.

Affected versions: < 5.4.0

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/v5.1.3/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/SAMLAssertionClaimsCallback.java#L193

**Comment by DMHP** [comment]
[IS 5.2.0]https://github.com/wso2-support/identity-inbound-auth-oauth/pull/535/files

**Comment by DMHP** [comment]
This is already fixed in master branch.
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/673
