### ISSUE TITLE
Return error code for users created as "Ask Password"

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#6798]
Both self signup users and users created with Ask password remain in the pending state. But only selfsignup users getting specific pending error code when trying to login in the SSO flow but user created as Ask password not getting specific error code (17005) and giving the authentication error as "Login failed! Please recheck the username and password and try again" (When showAuthFailureReason is enabled). Only Self signup user get specific error code(17005) when trying to log.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
