### ISSUE TITLE
Add supported cipher suites for the documentation for Tomcat 9 JDK 1.8

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6800]
Although IS-5.9 uses Tomcat 9 and JDK 1.8 below documentation does not have the relevant information for supported ciphers. That should be used when disabling weak ciphers. 

https://is.docs.wso2.com/en/5.9.0/administer/supported-cipher-suites/

Suggested Labels: Config, 5.9,

**Comment by somindatommy** [comment]
@Buddhimah This documentation is available in references[1]. I don't think we need to add it to administer. WDYT?

[1] - https://is.docs.wso2.com/en/latest/references/supported-cipher-suites/

**Comment by Buddhimah** [comment]
@somindatommy Although the documentation is there it does not have the content related to specific tomcat version and JDK version I have specified in the description. Hence this is still an issue

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
