### ISSUE TITLE
Improve audit logs related to application management operations

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6805]
The current audit logs are hard to interpret.

TID: [-1234] [2019-11-07 03:04:05,214] [e99974e4-0c6c-47d9-8a44-c80b91f7fee4]  INFO {AUDIT_LOG} - Initiator : admin@carbon.super | Action : create | Target : 3 | Data : { TripAction3 } | Result : Success

By looking at this log, we cannot identify which entity was created nor the meaning of the 3 in Target.
We can make the audit logs informative and easy to understand

Possible sample,

TID: [-1234] [2019-11-07 03:04:05,214] [e99974e4-0c6c-47d9-8a44-c80b91f7fee4]  INFO {AUDIT_LOG} - Initiator : admin@carbon.super | Action : create-application | Data : { name: TripAction3, resourceId: x12312-1231232 } | Result : Success

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
