### ISSUE TITLE
Add migration resources related to user discoverable applications API

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6810]
In order to support the first phase of user discoverable applications API that provides capability for an identity admin to flag an application as discoverable a new column as 'IS_DISCOVERABLE' is added to 'SP_APP' table.
Need to include this alteration in migration scripts

**Comment by Abilashini** [comment]
Included in the migration for 5.10.0 release - https://github.com/wso2-extensions/identity-migration-resources/pull/39
