### ISSUE TITLE
Add support for SCIM2.0 Schemas endpoint

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#6814]
Quoting the [SCIM 2.0 Spec](https://tools.ietf.org/html/rfc7644#section-4):

>    SCIM defines three endpoints to facilitate discovery of SCIM service
>    provider features and schema that MAY be retrieved using HTTP GET:
> 
>    /ServiceProviderConfig
>    /Schemas
>    /ResourceTypes

As of Identity Server 5.9.0, it supports only `ResourceTypes` `ServiceProviderConfig` endpoints not the `Schemas` endpoint.

When a SCIM client like user-portal wants to dynamically discover and adjust to the capability of the SCIM Service Provider(IDP), its needed these endpoint and specially the `Schemas` endpoint, since it defines what are the attributes that IDP support and what are the data-types of it it.

**Comment by darshanasbg** [comment]
Endpoint has been introduced with:
https://github.com/wso2/charon/pull/254 &
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/200

User-Schema Impl has been introduced with:
https://github.com/wso2/charon/pull/260 &
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/TBD

**Comment by hauntingEcho** [comment]
duplicate of 5284

**Comment by darshanasbg** [comment]
Closing this this issue with the implementation of support for user schema from the schema endpoint.

Let's keep the #5284 to track for other improvements like schemas for user extensions, groups.
