### ISSUE TITLE
Add common packages to log4j2.properties file

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6817]
To make life convenient for anyone debugging or enabling DEBUG logs, it would be better to have common packages added to the log4j2.properties file ready to be simply uncommented for use.

Right now if we want to add a new package,

we should first create an entry for the logger as below,

```
logger.org-wso2-carbon-identity-openidconnect.name=org.wso2.carbon.identity.oauth2.openidconnect
logger.org-wso2-carbon-identity-openidconnect.level=DEBUG
```

And then go an append the added logger to existing loggers property

`loggers = AUDIT_LOG, trace-messages, org-apache-coyote, com-hazelcast, Owasp-CsrfGuard, org-apache-axis2-wsdl-codegen-writer-PrettyPrinter, org-apache-axis2-clustering, org-apache-catalina, org-apache-tomcat, org-wso2-carbon-apacheds, org-apache-directory-server-ldap, org-apache-directory-server-core-event, com-atomikos, org-quartz, org-apache-jackrabbit-webdav, org-apache-juddi, org-apache-commons-digester-Digester, org-apache-jasper-compiler-TldLocationsCache, org-apache-qpid, org-apache-qpid-server-Main, qpid-message, qpid-message-broker-listening, org-apache-tiles, org-apache-commons-httpclient, org-apache-solr, me-prettyprint-cassandra-hector-TimingLogger, org-apache-axis-enterprise, org-apache-directory-shared-ldap, org-apache-directory-server-ldap-handlers, org-apache-directory-shared-ldap-entry-DefaultServerAttribute, org-apache-directory-server-core-DefaultDirectoryService, org-apache-directory-shared-ldap-ldif-LdifReader, org-apache-directory-server-ldap-LdapProtocolHandler, org-apache-directory-server-core, org-apache-directory-server-ldap-LdapSession, DataNucleus, Datastore, Datastore-Schema, JPOX-Datastore, JPOX-Plugin, JPOX-MetaData, JPOX-Query, JPOX-General, JPOX-Enhancer, org-apache-hadoop-hive, hive, ExecMapper, ExecReducer, net-sf-ehcache, axis2Deployment, equinox, tomcat2, StAXDialectDetector, org-apache-directory-api, org-apache-directory-api-ldap-model-entry, TRANSACTION_LOGGER, DELETE_EVENT_LOGGER, org-springframework, org-opensaml-xml-security-credential-criteria, org-wso2-carbon-user-core, org-wso2-carbon-identity, org-wso2-carbon-identity-sso-saml, org-wso2-carbon-identity-openidconnect`

We can avoid the second step if we have the common packages already defined as loggers and added to the above entry.

**Comment by rksk** [comment]
Related https://github.com/wso2/product-is/issues/12373

**Comment by rksk** [comment]
Some loggers were added with https://github.com/wso2/product-is/pull/13487

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
