### ISSUE TITLE
Having the map with User Store className vs User Store typeName 

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#6828]
Construct a map to maintain User Store **className** vs UserStore **typeName** in user store manager layer.
E.g: if the class name is **org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager** then type name should be **JDBCUserStoreManager**.

**Comment by tharindu-bandara** [comment]
@Kanapriya 

I have a small doubt. How does this change affect the User Store REST APIs?

**Comment by Kanapriya** [comment]
@tharindu-bandara : Already have these capabilities in the API layer, dicussed to move this capability to user store manager from the API layer. Hence it doesn't have any affect User Store REST APIs functionality.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
