### ISSUE TITLE
Client-Initiated Back-channel Authentication [CIBA] support for WSO2 Identity Server

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#6835]
### Client-Initiated Back-channel Authentication [CIBA]
- CIBA decouples the authentication process.
- Supports the authentication request initiated by the client.
- Authentication is initiated with or without customer acting on consumption devices.
- Customer authenticates & authorize from authentication devices.

### Specification 
https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html

### Sample flow:
![Screenshot from 2019-11-08 18-00-02](https://user-images.githubusercontent.com/32198547/68476802-c2153e00-0251-11ea-9510-3c9e80cde783.png)

### Sequence flow :
![cibaSequence](https://user-images.githubusercontent.com/32198547/68476882-ff79cb80-0251-11ea-91af-da06efb9642c.png)

### Design :
- Architecture Mail Thread - https://wso2.markmail.org/thread/rxn4dtikeb5wo3vu
- Design includes two main components
1. Ciba Endpoint [responsible for authentication requests and responses]
2. Ciba Module [supportive in the flow]

![cibaFlow](https://user-images.githubusercontent.com/32198547/68476999-47005780-0252-11ea-9b11-18b2eebb32ab.png)

### 1. Endpoint 
- PR  https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1210 is related to this.
- The functionality of EndPoint is explained below in the diagram.

![cibaEndPointFlow](https://user-images.githubusercontent.com/32198547/68477171-bece8200-0252-11ea-918f-d4f6a30f4b68.png)

### 2. Ciba Module 
- PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1209 is related to this.
- This module especially consists of
1. responseTypeHandler
2. grantHandler
3. Utils
4. DAO  layer

- And needed to add new logic at grantHandler to handle polling for tokens.
![cibaModulePolling](https://user-images.githubusercontent.com/32198547/68477746-36e97780-0254-11ea-8b05-ace0fba91f67.png)

### Additional Changes required 
- And in addition to the PR sent for the purposes served it is required to do additional changes in the identity-inbound-auth-oauth component.
- It is required to do changes to the modules below:
1. **ResponseTypeHandler** [added 2 new methods : **oauth module**]
2. **AuthorizationHandlerManager** [added 2 new methods : **oauth module**]
3. **OAuth2Service** [added 2 new methods: **oauth module**]
4. **Authorize endpoint** [added 2 new methods : **endpoint module**]

#### Reason for Change:
- AuthorizationHandlerManager calls **issue()** method of responseTypeHandler when authentication is successful.
- Same as when **consent denied / authentication failed** allowing **AuthorizationHandlerManager** to call responseTypeHandler to do the database update [inaddition to redirecting errorpage] is required for this feature.
- PR related to this change - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1211

**Comment by mefarazath** [comment]
PRs:
OAuth Changes - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1211
CIBA Core Module - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1209
CIBA Endpoint - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1210

DB Schema Changes - https://github.com/wso2/carbon-identity-framework/pull/2599
