### ISSUE TITLE
Local claims in the claim map is null in the adaptive authentication script when there is an existing session

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-is#6853]
Steps to reproduce:
1) Configure 2 service providers
2) Configure an adaptive script to print a local claim of the the authenticated user in one service provider
3) Configure single sign-on for the service providers
4) First login to one service provider
5) In the same browser session try to login to the second service provider, since there is an existing session user will be automatically logged in. But in the console the local claims from adaptive script gets printed as null.

The adaptive script used is as follows:

```
var mobileClaim = 'http://wso2.org/claims/mobile';

function onLoginRequest(context) {
    executeStep(1, {
        onSuccess: function (context) {
            var mobile = context.steps[1].subject.localClaims[mobileClaim];
            Log.info('Mobile of user ' + context.steps[1].subject.identifier + ' is : ' + mobile);
            
            if (!mobile) {
                executeStep(2);
            }
        }
    });
}
```

**Comment by IshikaGodage** [comment]
Fixed by : https://github.com/wso2/carbon-identity-framework/pull/2356
