### ISSUE TITLE
Introduce a new API to retrieve requested scopes only in OAuthScopeDAO

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#6863]
Introduce a new API to retrieve requested scopes only in OAuthScopeDAO. We can get rid of loading all the scopes if we have that API. 

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/c7503f99179086a7e8baa4bbe50195a9e13c2edb/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/JDBCPermissionBasedInternalScopeValidator.java#L143

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
