### ISSUE TITLE
Error message appear, when click on "Users and Roles -> Add"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6869]
**Describe the bug**
Error message is appearing when click on "Users and Roles → Add"

Type: BUG
Severity : LOW
Priority : LOW

**To Reproduce**
1. Go to 'Management Console'
2. Click on 'Workflow Definitions' and  Add "Workflow Definitions"
3. Click on 'Workflow Engagements' and Add "Workflow Engagements"
4. Click on ""Users and Roles -> Add"" 
5. See error message

**Screenshots** attached 
![image](https://user-images.githubusercontent.com/39120228/68921279-372acb00-079e-11ea-92b1-cd745f9444d4.png)

**Test Environment** 
 -Product-is- wso2is-5.10.0-m4
 - DB : H2
 - User Store : Default LDAP User Store
 - OS: macOS
 - Browser Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Additional context**
There is no any error logs- wso2carbon, 
User can continue the task after clicking "OK" in error msg.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
