### ISSUE TITLE
When a user is JIT provisioned through silent provisioning, the non claim attributes do not get updated.

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#6878]
When a user is JIT provisioned through silent provisioning, only the claims get updated, non-claim attributes remain the same if the user is already existing, or for a new user non-claim attributes are not updated. 

**Prerequisites:** 

1. Start two IS servers. 
2. In IS2, create an SP, add claim configuration for gender and country. 
3. In IS1, configure IDP(the created SP in IS2), provide the claim configuration as above.
4. Configure Federated Authenticator in IDP. 
5. Enable JIT provisioning in IDP (Option: Provision Silently)
6. Configure SP in IS1. 
7. For Outbound Authentication, select Federated Authentication as the configured IDP. 

**Steps to reproduce:**

1. Create a user in IS2. Complete the user profile by giving relevant details for first name, last name, organization, Mobile, IM including gender and country. 
2. Now login to the configured SP through the above created user credentials. 
3. User should be JIT provisioned in IS1. 

When the user profile JIT provisioned in IS1 is verified, it can be seen that only the claim attributes are updated, but not the other details.

**Comment by darshanasbg** [comment]
What you meant by non-claim attributes?

If the IS2 configured to send only the gender and country to IS1, its expected to IS1 to use only the gender and country attributes to create\update provisioned profile in IS1.

Can you share what are the attributes that IS2 sending to IS1 and what is actually happening in IS1 and what you expected to happen?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
