### ISSUE TITLE
SAML Front-channel logout request contains the user of the terminated session

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#6881]
Steps to reproduce:
1) There are two applications SSOed using IS 5.8.0 (WUM updated). Front channel logout is configured.
2) User A logs in to Application X
3) User A stays idle longer than the session idle timeout or logs out
4) User B accesses the Application Y in the same browser session.
5) Since the SSO session is expired the User B is authenticated.
6) When the User B signs out from Application Y and, the front channel logout request goes to Application X. But the user in the logout request is User A

**Comment by piraveena** [comment]
This is the root cause of this issue Related to https://github.com/wso2/product-is/issues/6881.
