### ISSUE TITLE
Externalizing authenticationendpoint is not working 

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6886]
Due to the changes introduced along with kernel 4.5.x upgrade, externalizing authenticationendoint is no longer works as expected.

Some causes,

1. Dependency update
3. changes introduced while fixing https://github.com/wso2/product-is/issues/6184 has a hard dependency to server at https://github.com/wso2/carbon-identity-framework/blob/v5.14.97/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/basicauth.jsp#L63

**Comment by ayshsandu** [comment]
Doc reference https://docs.wso2.com/display/IS580/Hosting+Authentication+Endpoint+on+a+Different+Server

Script https://github.com/wso2/samples-is/tree/master/host-endpoints-externally

**Comment by GDRDABARERA** [comment]
Flow that have tested:

- Login flow
- Username recovery flow
- Password recovery flow with email
- Password recovery flow with challenge question
- Ask password flow
