### ISSUE TITLE
Request schema of SCIM 2.0 PATCH on bulk resource updating multiple users is not compliance with SCIM spec

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#6887]
Sample requests in the SCIM specification for PATCH operation defines the body of the request as below.
`{
     "schemas": ["urn:ietf:params:scim:api:messages:2.0:BulkRequest"],
     "failOnErrors":1,
     "Operations":[
       {
         "method": "PATCH",
         "path": "/Users/5d8d29d3-342c-4b5f-8683-a3cb6763ffcc",
         "version": "W/\"edac3253e2c0ef2\"",
         "data": {[
           {
               "op": "remove",
               "path": "nickName"
           },
           {
               "op": "add",
               "path": "userName",
               "value": "Dave"
           }
         ]}
       }
     ]
   }`

where as for IS, to perform a bulk patch we have to send the request as below.

`{
    "failOnErrors": 1,
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:BulkRequest"
    ],
    "Operations": [
        {
            "method": "PATCH",
            "path": "/Users/47c4ac96-261c-4b4d-9747-a7924f1327a1",
            "data": {
                "Operations": [
                    {
                        "op": "replace",
                        "path": "name",
                        "value": {
                            "givenName": "john",
                            "familyName": "Anderson"
                        }
                    }
                ]
            }
        }
    ]
}
`

Note that in IS we have repeat the "Operations" array, which is being referred to in a single PATCH operation. But in the request defined in spec "data" section does not include that again.

**Comment by GDRDABARERA** [comment]
https://anuradha-15.medium.com/scim-2-0-bulk-operation-support-in-wso2-identity-server-5-10-0-8041577a4fe3

**Comment by AnuradhaSK** [comment]
@malithie, Seems the example given in the specification is erroneous (Even the JSON format is not correct), and later it has been corrected to the format that we support in the IS.
Refer to the mail thread: https://mailarchive.ietf.org/arch/msg/scim/ps4KjsEDrssyF1etJ3fSj0ps7Gc/

I think we can close this issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
