### ISSUE TITLE
Password policy violation using whitespace

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6890]
When Password History policy is set it should not allow the user to use the current or recent passwords. 

It is seen that this policy can be bypassed using trailing whitespace when invoking updateCredential() in the RemoteUserStoreManagerService[1]. Even when the `<EnablePasswordTrim>true</EnablePasswordTrim>`[2] config is set.

For example:
If the current password is **"admin123"** we can change the password to **"admin123 &nbsp;"** and then the user can login using **"admin123"**(The trimmed version of the password.)

It was also seen if I changed the password to **"admin123 &nbsp;"** using the soap service and try to change the password again to **"admin123 &nbsp;"** I get a password history violation error.

It looks like the Password History policy does not take to account the `<EnablePasswordTrim>true</EnablePasswordTrim>` config.

 [1] - https://docs.wso2.com/display/IS570/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-updateCredential()
[2] - https://github.com/wso2/carbon-kernel/pull/2004

**Comment by DMHP** [comment]
AddUser using RemoteUserStoreManagerService allows to add user ignoring the <EnablePasswordTrim>true</EnablePasswordTrim>. But from the UI it shows an error message when adding a user with a white space which is inconsistance. (Note:  The error message does not contain the exact reason. I shows 'Password length should be within 5 to 30 characters'
