### ISSUE TITLE
Embedded LDAP is not manageable using the deployment.toml file

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#6896]
Currently, we need to disable the embedded LDAP using the embedded-ldap.xml file. 

We have not templated the embedded-ldap.xml file in the new configuration model since we do not recommend using the embedded LDAP in any environment other than evaluation purposes. Therefore we have not given the ability to configure embedded LDAP through the toml configuration. The configurations of embedded LDAP that ship by default should not be changed by a user.

We should turn embedded LDAP off if an external user store is configured. We may be able to infer that configuration without asking the user to do so specifically.

**Comment by GDRDABARERA** [comment]
This is not needed as we can add any property with the name. So this need not to be templated. We can add this to the doc. Hence changing the label to doc issue.
