### ISSUE TITLE
 User account will  lock on the first wrong attempt 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6903]
Type/BUG
Affected: 5.8.0-GA
Severity: Critical
Priority: High

**Description** :  A few attempts were allowed, but the first wrong attempt would lock the user account 
and will email to the user's email address with the first wrong attempt.

**Step to reproduce** : 

1. Click Resident -→ Identity Providers.
2. Expand the Login Policies tab.
3. Expand the Account Locking tab and select the Account Lock Enabled checkbox. 
4. Specify number of Maximum Failed Login Attempts (5).
5. Click Update to save changes. 
6. Navigate to Claims>List on the Configure menu and select the http://wso2.org/claims  claim dialect. 
7. Select the Supported by Default check box and click Update. 
8. Navigate to Users and Roles>List>Users  
9. Click on User Profile and tick the checkbox for Account lock. 
10. Update.
11. Try to log in with above user with invalid credential, 

Actual Output:
in 1st wrong attempt:
User account will  lock .
and will email to the user's email address.

[2019-11-21 11:28:47,641] ERROR {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} -  System error while Authenticating/Authorizing User : Account is locked for user Accouser in user store PRIMARY in tenant carbon.super. Cannot login until the account is unlocked.

Unable to login with the particular user with correct credentials on next attempt.

**Comment by janakamarasena** [comment]
This is the expected behaviour as the "Account lock" claim is set to true. Hence closing the issue.
