### ISSUE TITLE
Attribute values sent in SCIM2 is trimmed when sending to the userstore

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6904]
When creating a user using SCIM2 if we add leading or trailing whitespace in the attribute values, they are automatically trimmed. But if we use the **addUser()** of the RemoteUserStoreManagerService[1] then the set attribute values are stored as given even with leading/trailing whitespaces.

The behaviour should be that the values sent in should be stored as it is if it does not violate any preset condition. 

[1] - https://docs.wso2.com/display/IS570/Managing+Users+and+Roles+with+APIs#ManagingUsersandRoleswithAPIs-addUser()

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
