### ISSUE TITLE
Properties to be templated for userstores

### ISSUE THREAD

**Issue by gomathyk** [wso2/product-is#6912]
The following properties have not been templated

[1] **JDBC User Store**
ReadOnly
RolenameJavaScriptRegEx
CaseInsensitiveUsername
IsBulkImportSupported
PasswordDigest
StoreSaltedPassword
TenantManager
UserNameUniqueAcrossTenants

[2] **read only ldap user store**
RolenameJavaScriptRegEx
IsBulkImportSupported
EmptyRolesAllowed

[3] **read write active directory user store**
RolenameJavaScriptRegEx
IsBulkImportSupported
EmptyRolesAllowed
Referral

[4] **read write ldap user store** 
RolenameJavaScriptRegEx
IsBulkImportSupported
EmptyRolesAllowed

[5] **Primary user store general properties** 
UsernameWithEmailJavaScriptRegEx
RolenameJavaScriptRegEx
CaseInsensitiveUsername
Referral
EmptyRolesAllowed
GroupSearchFilter
TenantManager
ReadOnly
IsEmailUserName
DomainCalculation
PasswordDigest
StoreSaltedPassword
UserNameUniqueAcrossTenants
RolenameJavaScriptRegEx
SharedGroupEnabled
SharedGroupSearchBase
SharedTenantObjectClass
SharedTenantNameAttribute
SharedTenantNameListFilter

1. https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-jdbc-user-store/
2. https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-read-only-ldap-user-store/
3. https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-read-write-active-directory-user-store/
4. https://is.docs.wso2.com/en/5.9.0/setup/configuring-a-read-write-ldap-user-store/
5. https://is.docs.wso2.com/en/5.9.0/setup/working-with-properties-of-user-stores/

**Comment by GDRDABARERA** [comment]
This is not needed as we can add any property with the name. So this need not to be templated. We can add this to the doc. Hence changing the label to doc issue.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
