### ISSUE TITLE
[Migration] Need To Generate Client Stub With Added Attributes

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#6920]
Fixing the issue, https://github.com/wso2/product-is/issues/6908 adds new attributes to the association user response. This could break any SOAP client using an older stub. Therefore we need to mention in the migration document, that any client consuming the UserAccountAssociation admin service, requires to regenerate the client stub.

**Comment by Abilashini** [comment]
documented at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/#wsdl-of-the-user-account-association-service-has-been-changed
