### ISSUE TITLE
[Migration] Email Templates has been changed for account lock 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6924]
WSO2 Identity Server 5.10.0 uses separate email templates for notifying, 

- Account locking by exceeding `Maximum Failed Login Attempts`
- Account unlocking by exceeding `Account Unlock Time`

WSO2 Identity Server 5.10.0 uses separate email templates for notifying, 

- Account locking by administrator
- Account unlocking by administrator 

As per the fix for issue : wso2/product-is#6778

Please refer the documentation for instructions : https://github.com/wso2/docs-is/pull/862

Suggested Labels : Migration/5.10

**Comment by Abilashini** [comment]
documented at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/#email-templates-has-been-changed-for-account-lock
