### ISSUE TITLE
Adding default email template for account lock and unlock scenarios. 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6926]
Fix for the wso2/product-is#6778 uses four templates for account lock and unlock overriding already existed breaking backward compatibility

**Comment by malithie** [comment]
@Buddhimah , can mention the templates newly added and templates being removed

**Comment by Buddhimah** [comment]
Added email templates : accountUnlockAdmin, accountLockAdmin, accountUnlockTimeBased,accountLockFailedAttempt 

Removed: accountUnlock, accountLock

https://github.com/wso2-extensions/identity-event-handler-notification/pull/107

Documentation: https://github.com/wso2/docs-is/pull/862/files 

Please add the milestone : 5.10.GA
