### ISSUE TITLE
Migration changes related to Identity Provider APIs

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#6932]
- Following new columns have been introduced to the IDP table. This would require a DB schema migration.

UUID CHAR(36)
IMAGE_URL VARCHAR(1024)
UNIQUE(UUID)

- WSDL of the Identity Provider Management service has changed with the addition of new attributes to the identity provider model object and with the introduction of SubProperty model object. Therefore we need to document to instruct the SOAP API consumers to regenerate the stub or upgrade the dependency version of the stub.

**Comment by emswbandara** [comment]
Part of https://github.com/wso2/product-is/issues/6774

**Comment by Abilashini** [comment]
Included in the migration for 5.10.0 release - https://github.com/wso2-extensions/identity-migration-resources/pull/39

**Comment by Abilashini** [comment]
documented at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/#wsdl-of-the-identity-provider-management-service-has-been-changed
