### ISSUE TITLE
Password expiration doesn't work with SMSOTP

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#6936]
**Steps to Reproduce**
Create a service provider SAML/OIDC with following sequence of MFA.
1- Basic
2- SMSOTP
3- Password enforcer.
**Result**
Password enforcer doesn't work after the SMSOTP and it works only after the Basic authenticator.

Affected IS. version - IS-5.7.0

**Comment by senthalan** [comment]
When I analysed the code the password policy authenticator has a logic to execute the only if the last authenticator is a local authenticator[1]. In this case, the smsotp is a federated authenticator that why the authentication failed. I think we should loop for all the previous authenticators and check whether the basic authenticator is in the step.

[1] - https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/v1.0.14/component/authenticator/src/main/java/org/wso2/carbon/identity/policy/password/PasswordResetEnforcer.java#L127-L128
