### ISSUE TITLE
[Migration] Added a column NAME to IDN_CONFIG_FILE Table

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6941]
Refer the 
Documentation : 
https://github.com/wso2/docs-is/blob/master/en/docs/develop/using-the-configuration-management-rest-apis.md

Related PR: https://github.com/wso2/carbon-identity-framework/pull/2480

Related Issue: wso2/product-is#6146

**Comment by Buddhimah** [comment]
In migration should add a column `name` to the table `IDN_CONFIG_FILE`. If there were data on that table they should be migrated. but the data under `name` column can be null.

**Comment by Abilashini** [comment]
Included in the migration for 5.10.0 release - https://github.com/wso2-extensions/identity-migration-resources/pull/39
