### ISSUE TITLE
wso2IS 5.9.0 failed supporting of custom JWTAccessTokenBuilder

### ISSUE THREAD

**Issue by jing-zhou** [wso2/product-is#6943]
i am using a custom JWT access token builder as per the [JWTAccessTokenBuilder ](https://github.com/wso2/msf4j/tree/v2.8.1/samples/jwt-claims/JWTAccessTokenBuilder) here. and it used to work perfectly with previous release (5.2.0 ~ 5.8.0). 
 i had tried both the old and new config methods (https://github.com/wso2/product-is/issues/6649) with release 5.9.0. and can not get it work. 
it unfortunately seemed that , the feature had broken in the release 5.9.0.

**Comment by inthirakumaaran** [comment]
Please follow our latest doc to https://is.docs.wso2.com/en/5.9.0/learn/jwt-token-generation configure custom JWT in 5.9.0.

If the problem still exists, can you tell us the configuration you did in 5.9.0 deployment.toml?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
