### ISSUE TITLE
The Proper error message should be displayed.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6944]
Affected IS version: wso2is 5.10 m7
Severity: Low
Priority: High

Issue: The content of the error message is not correct when submitting the "Associated Flow" field with empty.

Step to reproduce: 
1. Navigate to Home> Manage> Consent Purposes and click Add.
2. Leave the "Associated Flow" field empty and enter the correct information for the rest.
3. Click on "finish".

![image](https://user-images.githubusercontent.com/39120228/69649198-b23f8b80-1092-11ea-8a0a-e8b924e00f0b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
