### ISSUE TITLE
Allow to map and use Mapped Attributes as AD's immutable attributes in WSO2 IS

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#6949]
For the AD user store, we do the claim mapping for the mandatory SCIM claims to the existing attributes in the Active Directory. 
When provide mapping for, 

- urn:ietf:params:scim:schemas:core:2.0:meta.created 
- urn:ietf:params:scim:schemas:core:2.0:meta.lastModified

We can map the created time to the filed "whenCreated" and 
lastModified time to the filed "whenChanged" in AD.
Since these "whenChanged" and "whenCreated" fields are automatically generated and maintained by the AD itself [1]. 
Those formats are like below: 
```
Last Modified Time - whenChanged: 20191125071807.0Z
Created Time - whenCreated: 20191125071807.0Z
```
But SCIM2 is expecting time in the following different format. Doesn't like the timestamp string format provided by AD for these fields. 
```
Last Modified Time : 2019-11-21T21:11:34
Created Time : 2019-11-21T21:11:34
```
Due to these limitations currently, we can't map to these immutable system attributes. 
Not only these two, but we can also map the urn:ietf:params:scim:schemas:core:2.0:id to AD's UUID instead of creating SCIM ID in IS. 

The one possible approach is, 
We need to handle two cases when this kind of immutable system attributes are mapped. 

Case 1- Need to skip this immutable system mapped attributes when it's getting stored. 
One way to achieve this we can keep a file which contains all the immutable attribute for a particular user store type (currently for AD) and skipping those attribute when we perform create/update. 
Else directly hard code these attributes in Active Directory User store Manager level and skip it.

Case 2- When reading it, read these attributes and parse to the desired SCIM2 format. 
For this also, we can keep a file which contains all the details from which format to which format we need to parse a particular attribute and then we can perform parsing in Active Directory User store Manager level.

[1] https://docs.microsoft.com/en-us/windows/win32/adschema/a-whenchanged

**Comment by LahiruLS** [comment]
It seems we have missed processing immutable attributes in the user add flow.
