### ISSUE TITLE
User discoverable apps needs a mandatory access URL & imageURL input fields in the management console

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#6969]
When an application(service provider) is configured, it can be flagged as a user discoverable app. But the current UI doesn't provide a field to input the access URL of the application.

<img width="1646" alt="Screen Shot 2019-11-29 at 3 12 56 PM" src="https://user-images.githubusercontent.com/25959096/69859783-d8e00b00-12ba-11ea-9e3d-370b2ac44181.png">

**Comment by darshanasbg** [comment]
Added imageURL with: https://github.com/wso2/carbon-identity-framework/pull/2626
