### ISSUE TITLE
Image Service support

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#6971]

**Comment by madurangasiriwardena** [comment]
PRs for 
- https://github.com/wso2/carbon-identity-framework
- https://github.com/wso2/identity-api-server
- https://github.com/wso2/identity-rest-dispatcher
- https://github.com/wso2/product-is

are merged to `feature-image-service` branch in each repo. To test the feature, build `feature-image-service` in each repo above.

**Comment by tharindu-bandara** [comment]
#### Suggest improvements to the Image Service

- Refactor `Image Service` as `Content Service`, and serve any content.
- The above includes having a `content-type` parameter in the GET response.
- Also, this service should be able to be turned off via a configuration, to support enabling and disabling.

**Comment by malithie** [comment]
This task is being now tracked with https://github.com/wso2/product-is/issues/8499.
Thus, closing.
