### ISSUE TITLE
[Integration Test] Order Is Neglected In OIDC Metadata Response Assertion

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#6972]
When comparing OIDC metadata response, the order of the elements under the `options` in [several properties is neglected](https://github.com/wso2/product-is/blob/fd84bd5e73bc34969775aa29c3e1cdbdb6c5defb/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/rest/api/server/application/management/v1/ApplicationMetadataPositiveTest.java#L162).

For example, `accessTokenType` property contains an array of options, which does not have a guaranteed order. Therefore, the assertion could fail. Need to fix the whole assertion logic in this test and fix accordingly.

PS: The `Scope validators` [property is sorted prior to the assertion](https://github.com/wso2/product-is/blob/fd84bd5e73bc34969775aa29c3e1cdbdb6c5defb/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/rest/api/server/application/management/v1/ApplicationMetadataPositiveTest.java#L166) to avoid this issue. Maybe the same approach could be used.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
