### ISSUE TITLE
Cover Concurrent Requests Scenarios With Tests For Application Creation

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#6973]
> Regarding the issue,  https://github.com/wso2/product-is/issues/5363

The concurrent request handling scenarios introduced with https://github.com/wso2/carbon-kernel/pull/2420, and https://github.com/wso2/carbon-identity-framework/pull/2588 should be covered with sufficient tests.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
