### ISSUE TITLE
[Migration] DB schema migration for handling single logout requests from the federated IdP feature.

### ISSUE THREAD

**Issue by Isanka95** [wso2/product-is#6988]
**Description**

- Related issue:  wso2/product-is#5717

- In the inbound saml request process, saml index and session context key will be cached for the logout process. But in the outbound saml request process, there is no mapping between saml index and the session index. Without this mapping, we could not identify the session index for the saml index of the logout request from the federated IdP. 

- A new table(IDN_FEDERATED_AUTH_SESSION_MAPPING) is created to store the indexes and other important details.

- Related PR: https://github.com/wso2/carbon-identity-framework/pull/2566

**Comment by Abilashini** [comment]
Included in the migration for 5.10.0 release - https://github.com/wso2-extensions/identity-migration-resources/pull/39
