### ISSUE TITLE
Uniqueness of inbound authentication key is not ensured

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6991]
Except for SAML, OAuth inbounds, in all other inbound types such as

WS-Trust
WS-Fed (Passive STS) 
CAS

the uniqueness of the inbound key (unique identifier for the protocol) is not ensured at the API or DB level. The consequence of this is that there might be multiple SPs associated with the same inbound key.

For example,
We can register two SPs with the Passive STS realm "sample1". So when a passive sts request with realm=sample1 comes to the server there will be two SPs which could different authentication configurations etc. This will lead to unexpected behaviours.

In SAML and OAuth, since the inbound configurations are maintained separately from the framework, the uniqueness is verified during the time the inbound configurations are created.

Solution:
We can write an Application Management Listener or Application Resource Management Listener to check for the uniqueness of inbound during application create and update.

**Comment by emswbandara** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2609
