### ISSUE TITLE
Removing an OAuth application using the OAuthAdminService does not clear token caches

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6992]
According to the OAuthAdminService code,

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/9116d201cd62081ca791b50592a57c0d766f1f71/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminServiceImpl.java#L741-L752

When an application is removed using OAuthAdminService#removeOAuthApplicationData only the cache entry related to the application's consumer key is removed.

However, if tokens were issued for the applications those entries in the cache will remain for the duration fo the cache timeout. The tokens will be deleted from the DB since the OAuth application's id acts as a foreign key to the token table.

It was noticed that we have logic to clear all necessary caches in the OAuthApplicationMgtListener which acts on the preDeleteApplication() hook to clear all caches. We can move the logic to OSGi layer and reuse the same for the admin service as well.

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/9116d201cd62081ca791b50592a57c0d766f1f71/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java#L129

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
