### ISSUE TITLE
Authorization logic needs to move to a sepearate layer in ApplicationManagementServiceImpl

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6993]
Currently, we have authorization logic baked into OSGi layer of ApplicationManagementServiceImpl

https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationManagementServiceImpl.java#L2344

For example during,

Update and Delete operations we check whether the user has the Application/<APP_NAME> role. It would be better if we move the authorization checks to another layer so that we can keep the application management logic clean.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
