### ISSUE TITLE
Improve Performance of DCR Flow using the new ApplicationManagement OSGi methods

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6994]
In the previous versions (before IS 5.10.0), the ApplicationManagment OSGi APIs did not allow a method to completely persist and application. If we wanted to create an application, we usually

1. Call a method to create the basic application which returns the auto-increment internal id
2. Update the application using the internal id.

With the new OSGi methods introduce for REST APIs, we can create a complete application with a single API call using
```
public String createApplication(ServiceProvider application, String tenantDomain, String username)
```
https://github.com/wso2/carbon-identity-framework/blob/10c5d97f478d7ce5ff4078dc3876e07085d7900f/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationManagementServiceImpl.java#L2038

Current DCR Create Flow involves,

1. Check whether application name does not violate SP regex
2. Check whether an application already exists with the name
3. If the create request contains a client_id check whether it exists.
4. Create a basic service provider with the name
5. Get the Service Provider
6. Create an OAuth app
7. Set OAuth inbound information to the service provider and do an update.

https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/9116d201cd62081ca791b50592a57c0d766f1f71/components/org.wso2.carbon.identity.oauth.dcr/src/main/java/org/wso2/carbon/identity/oauth/dcr/service/DCRMService.java#L244-L293

By using the new API, we can rewrite the flow as

1. If the create request contains a client_id check whether it exists.
2. Create an OAuth app
3. Create a Service Provider with OAuth inbound information.

There are several benefits,
* A service provider Update is basically deleting and creating at the DAO level. With this change we avoid the unnecessary DELETE queries that run on the DB.
* Avoid unnecessary GET SP call in step 5
* Checks 1 and 2 already done at the Application Management API layer, for a valid request these checks happen twice. Therefore we can remove the checks at the DCR layer and allow Application Management APIs to do the job.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
