### ISSUE TITLE
Problem with sub when federated users provisioned in PRIMARY userstore 

### ISSUE THREAD

**Issue by kranidiotis** [wso2/product-is#6997]
A very strange bug. It happens on 5.7 and 5.8 as far i have checked. 

One PRIMARY and one SECONDARY USERSTORE
FEDERATED users provisioned with JIT on PRIMARY
During authentication process SOMETIMES (this is the strange part, that it happens randomly) in the response Local Subject Identifier contains the name of the SECONDARY USERSTORE even though  "Use user store domain in local subject identifier" IS NOT checked.

The most strange thing is that this pattern occurs also at the first time that user authenticates (BEFORE provisioning) but if JIT is enabled.
If JIT is not enabled the problem never occurs.

**Comment by hauntingEcho** [comment]
for clarity, if this bug affects a user will it always affect that user (in other words, is it transient per-user vs per-authentication)?  Is anything logged when this happens?

**Comment by kranidiotis** [comment]
No it is random. No nothing logged. If i restart the server it works well for a while but after sometime problem occurs again

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
