### ISSUE TITLE
Pending Improvements to Application Management REST API

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#7000]
This issue is to track the improvements added as TODOs in the code,

- [ ] Application Inbound friendly names need to be returned from API GET responses.
- [x] Reject inbound updates if the provided inbound key does not match the existing one. Basically prevent inbound keys changing in the updates.
- [x] Improve SAML inbound swagger structure.
- [ ] Return claim display name and id in API GET responses
- [ ] Return Links in the API list response.

**Comment by mefarazath** [comment]
SAML Swagger change - https://github.com/wso2/identity-api-server/pull/72/files

**Comment by mefarazath** [comment]
Prevent duplicate inbound keys - https://github.com/wso2/carbon-identity-framework/pull/2609/files

**Comment by mefarazath** [comment]
Return Links in the API list response depends on https://github.com/wso2/product-is/issues/6935

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
