### ISSUE TITLE
Cannot view User Profile of Primary Userstore users

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#7002]
When there're local claims only specific to the secondary user store and those claims have been configured only for the secondary user store. Primary user store user profiles cannot be seen.

**Steps to Reproduce:**

- Configure a secondary user store (JDBC).
- Add a custom claim for the secondary user store as below and make it supported by default.

<img width="1401" alt="Screenshot 2019-12-03 at 16 01 28" src="https://user-images.githubusercontent.com/13187638/70043544-b0238280-15e6-11ea-9fea-fa84074c6034.png">

- List users and view the user profile of a primary user store user, below error will appear.

<img width="1662" alt="Screenshot 2019-12-03 at 16 08 45" src="https://user-images.githubusercontent.com/13187638/70043845-35a73280-15e7-11ea-9966-97692b2c6714.png">

According to the current implementation, we can overcome this by disabling supported by default and mapping newly added claim to a local claim. End users expect even though claim mapping has not been done for Primary user store and supported by default enabled, still it should return user profile (for Primary user store) without error in profile UI.

**Comment by rksk** [comment]
IMO, there should be validation on claim creation/update flow to validate whether a mapped attribute is defined for PRIMARY.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
