### ISSUE TITLE
Secure Vault causes startup errors when the password alias includes a dot

### ISSUE THREAD

**Issue by nilushancosta** [wso2/product-is#7004]
I tried to enable Secure vault for an IS 5.9.0 deployment by following [1]. However I encountered an issue when the password alias used in the deployment.toml file had a dot (.) in the string.

Please follow the steps below to reproduce this issue

1. Extract a vanilla WSO2 IS 5.9.0
2. Open <CARBON_HOME>/repository/conf/deployment.toml file and add the following block at the end
```
[secrets]
my.password = "[wso2carbon]"
```
3. Execute ciphertool.sh -Dconfigure
4. Open the deployment.toml file and edit the [keystore.primary] block as follows to refer the encrypted password.
```
[keystore.primary]
name = "wso2carbon.jks"
password = "$secret{my.password}"
```
5. Start the wso2 carbon server by executing <CARBON_HOME>/bin/wso2server.sh and multiple errors are shown

I noticed that the <CARBON_HOME>/repository/conf/security/cipher-text.properties file gets changed when the the carbon server is started.
If I used an alias without a dot (.) in step  2 above (Ex. keystorepassword), the correct alias gets written to the cipher-text.properties file.
However, if I used an alias with a dot (.) in step  2 above (Ex. keystore.password), only the part before the dot gets written to the cipher-text.properties file (ie. keystore)

[1] - (https://is.docs.wso2.com/en/5.9.0/setup/encrypting-passwords-with-cipher-tool/)

**Comment by janakamarasena** [comment]
The reason for this is when using keys with dots (.) in the deployment.toml file it should be inside quotation marks.

ex:
```
[secrets]
"my.password" = "[wso2carbon]"
```

**Comment by nilushancosta** [comment]
Thanks for the information. It worked without errors when the alias was put inside quotation marks. Lets have the documents updated as well as they currently do not mention this information.

**Comment by ruwanta** [comment]
This is the way TOML syntax supposed to work.

ref: https://github.com/toml-lang/toml
```
Dotted keys are a sequence of bare or quoted keys joined with a dot. This allows for grouping similar properties together:

name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
```
