### ISSUE TITLE
Issues with install Identity Server as a windows service -JDK 11

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7008]
Affected - wso2is -5.10.0
Severity : High
Priority : High

Issue 1: #https://github.com/wso2/carbon-kernel/issues/2435

Issue 2: #https://github.com/wso2/carbon-kernel/issues/2434

**Comment by madurangasiriwardena** [comment]
Setting the carbon_home environment variable seems to be not working. However, if we set the carbon home variable in the wrapper.conf file itself, runConsole.bat seems to be starting the server properly.

**Comment by madurangasiriwardena** [comment]
Resolved with https://github.com/wso2/docs-is/pull/1120 and https://github.com/wso2/carbon-kernel/pull/2581
