### ISSUE TITLE
Response of the sample adaptive authentication templates in application management REST API,

### ISSUE THREAD

**Issue by Wathsara** [wso2/product-is#7010]
This Issue Is about the response of the sample adaptive authentication templates of application management REST APIs.  Instead of returning a JSON string from the templatesJSON key, it would be better if return a JSON object created from the string returns from templatesJSON key.

Image of the current Response.
![Current response](https://user-images.githubusercontent.com/31571237/70119435-4e1f5780-1690-11ea-8fed-e930ea2310cb.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
