### ISSUE TITLE
When updating the userstore domain name of a disabled userstore, userstore is getting deleted.

### ISSUE THREAD

**Issue by hasinidilanka** [wso2/product-is#7013]
**Steps to reproduce:**

- Create a secondary userstore from the management console.

- Disable the secondary userstore by clicking disable button

- Click the edit button and try to update the Domain Name of the userstore.

Then an error will be shown in the management console and the userstore will get deleted.

**Affected Versions**

WUM updated IS-5.8.0, IS-5.7.0

Related To: https://github.com/wso2/product-is/issues/7012

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
