### ISSUE TITLE
Support for OAuth Device Flow in WSO2 Identity Server

### ISSUE THREAD

**Issue by ayeshajay** [wso2/product-is#7014]
**Device Flow**
This is an OAuth 2.0 extension that enables devices with no browser (e.i IoT devices) or limited input capability (ex: smart TV) to obtain user authorization to access protected resources.

**Specification**
https://tools.ietf.org/html/rfc8628

**Flow**
![1_ewFnoMTGTfSIJ5mgJfg2gQ](https://user-images.githubusercontent.com/51480027/70126051-29ca7780-169e-11ea-9a09-76c966302bdf.png)

**Sequence Diagram**
![Blank Diagram (31) (1)](https://user-images.githubusercontent.com/51480027/70127418-03f2a200-16a1-11ea-8ec0-9da2d5ced961.png)

**Design**
Architecture mail thread: https://markmail.org/message/6ap4qj6zpggtm2xd

The design has two new endpoints and device flow directory. 
PR : https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1196

This PR consist of 
1. Grant handler
2. Response type handler
3. DAO layer
4. Device endpoint
5. User authentication endpoint

Two new JSP pages are required for the flow.
PR : https://github.com/wso2/identity-apps/pull/172
        https://github.com/wso2/identity-apps/pull/178

DB scripts 
PR : https://github.com/wso2/carbon-identity-framework/pull/2604

Integration Test
PR: https://github.com/wso2/product-is/pull/7020

Docs
PR: https://github.com/wso2/docs-is/pull/943

Demo App
PR: https://github.com/wso2/samples-is/pull/214

Effort BE::15

**Comment by darshanasbg** [comment]
I had to revert the use of new configs that has been introduced with https://github.com/wso2/carbon-identity-framework/pull/2604 in the PR https://github.com/wso2/carbon-identity-framework/pull/2620 to avoid few errors when updating the framework version of the product-is...

Please keep track of this and revert https://github.com/wso2/carbon-identity-framework/pull/2620 once https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1196 is merged and included in the product.

**Comment by IsuraD** [comment]
Reopen to fix following 
- https://github.com/wso2/product-is/issues/7348
- https://github.com/wso2/product-is/issues/7750

**Comment by ChamathNS** [comment]
Enabled with https://github.com/wso2/carbon-identity-framework/pull/3701. Documentation is tracked with https://github.com/wso2/product-is/issues/12393.

**Comment by nilminiwso2** [comment]
Have we done any documentation for this?
If not, shall we create a doc issue to track the documentation progress?
@chamathns 
@nilasini

**Comment by nilasini** [comment]
@nilminiwso2 Document is available with https://github.com/wso2/docs-is/pull/2737

**Comment by nilasini** [comment]
Reopen the issue since the fixes for [1] need to be ported to 5.12.0
[1] https://github.com/wso2/product-is/issues/7014#issuecomment-665633484

**Comment by ashendes** [comment]
@nilasini Improvements mentioned in https://github.com/wso2/product-is/issues/8166 need to be ported to 5.12.0.

**Comment by ShanikaWickramasinghe** [comment]
@nilasini @chamathns @ashendes This issue is in reopened state. Are the improvements tracked with #8166 are avaialble in the 5.11.0 alpha 14 pack to proceed with testing this feature

**Comment by chamathns** [comment]
> @nilasini @chamathns @ashendes This issue is in reopened state. Are the improvements tracked with #8166 are avaialble in the 5.11.0 alpha 14 pack to proceed with testing this feature

Improvements tracked with #8166 are available as of now. However, there are a few improvements that are being added by @senthalan for the device flow feature. We can start testing most of the device flow features.  Let's sync with @senthalan and proceed

**Comment by nilminiwso2** [comment]
@himeshsiriwardana - Let's update this issue with any improvements we do to the docs.

**Comment by piraveena** [comment]
@nilminiwso2 @himeshsiriwardana can we close this issue if this is done?

**Comment by nilminiwso2** [comment]
Docs:
- https://is.docs.wso2.com/en/6.0.0/guides/access-delegation/try-device-flow/
- https://is.docs.wso2.com/en/6.0.0/references/concepts/authorization/device-flow-grant/
