### ISSUE TITLE
[Doc] Configuring custom login page per service provider in web.xml is not documented

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#7018]
In this document [1], it only mentions about customizing the login page for service providers by checking the value of relyingParty parameter. Need to improve the same mentioning how we can achieve this using web.xml by adding the routing as below.

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#595979; ">&lt;!--  Custom Page configurations --&gt;</span>
<span style="color:#595979; ">&lt;!-- *************** Application specific configurations ********************** --&gt;</span>
<span style="color:#0057a6; ">&lt;</span><span style="color:#333385; ">context-param</span><span style="color:#0057a6; ">&gt;</span>
    <span style="color:#0057a6; ">&lt;</span><span style="color:#333385; ">param-name</span><span style="color:#0057a6; ">&gt;</span>ServiceProviderApp-/samlsso_login<span style="color:#008c00; ">.</span>do<span style="color:#0057a6; ">&lt;/</span><span style="color:#333385; ">param-name</span><span style="color:#0057a6; ">&gt;</span>
    <span style="color:#0057a6; ">&lt;</span><span style="color:#333385; ">param-value</span><span style="color:#0057a6; ">&gt;</span>http://localhost:<span style="color:#008c00; ">8080</span>/customauthenticationendpoint/login<span style="color:#008c00; ">.</span>do<span style="color:#0057a6; ">&lt;/</span><span style="color:#333385; ">param-value</span><span style="color:#0057a6; ">&gt;</span>
<span style="color:#0057a6; ">&lt;/</span><span style="color:#333385; ">context-param</span><span style="color:#0057a6; ">&gt;</span>
</pre>

[1] - https://docs.wso2.com/display/IS570/Customizing+Login+Pages+for+Service+Providers

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
