### ISSUE TITLE
Skip OIDC logout consent from service provider level

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#7019]
We have provided the functionality to configure consent from the service provider config UI with https://github.com/wso2/product-is/issues/5258. Still, the consent configuration for OIDC logout is directly read from the identity.xml and not the sp config.

I believe we can update logic this to honor the service provider level config, but the logic has to be changed to read the SP config after getting the client id from the ID token hint in the odic logout request. Also, we may have to consider backward compatibility.

We may handle consent at login and consent at logout separately. That will preserve the backward compatibility as well.

**Comment by manuel-di-iorio** [comment]
While waiting for the 5.10.0 release, is it possible right now to skip the logout consent with a configuration in the `deployment.toml` file ?
I only found the `<SkipUserConsent>` in the identity.xml but that file is obviously overwritten on server restart.

**Comment by senthalan** [comment]
@manuel-di-iorio From 5.10.0, the login and logout consent flow of the OAuth can be managed separately in deployment.toml
```
[oauth]
prompt_login_consent = false
prompt_logout_consent = false
```

Refer https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1295

**Comment by manuel-di-iorio** [comment]
Thank you @senthalan for your answer, do you know about previous versions (5.9) ?

Even if it disables both login and logout consent, something like:
```
[oauth]
prompt_consent = false
```
And sorry if I'm replying in a closed issue.

**Comment by senthalan** [comment]
@manuel-di-iorio No worries. We are glad to assist you 

Yes in 5.9.0, we don't have two separate configurations to manage the login and logout consent. So when prompt_consent set to false, it disables both login and logout consent.

**Comment by cannontechnology** [comment]
how about 5.11?

**Comment by rksk** [comment]
> how about 5.11?

@cannontechnology This is fully supported in 5.11.0 release. You can find the configuration under the local and outbound authentication configuration of service providers.
