### ISSUE TITLE
Cannot delete associated users

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#7028]
When trying to delete an associated user account by sending a `DELETE` request to the  `/me/associations/{associated-user-id}` endpoint, the server responds with a `404` error code.

Possible reason for the above issue might be due to having extra `==` characters at the end of the associated user's `userId` attribute. 

```json
  {
        "userId": "UFJJTUFSWS9oYXJyeQ==",
        "username": "harry",
        "userStoreDomain": "PRIMARY",
        "tenantDomain": "carbon.super",
        "lastName": "harry",
        "email": "test@wso2.com"
    }
```

**Comment by tharindu-bandara** [comment]
I have tested association deletion with `==` signs appended user ids, which worked as expected. Therefore, closing this issue.
