### ISSUE TITLE
Supporting the feature; Biometric authenticator to integrate with mobile devices, in WSO2 Identity Server..

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/product-is#7029]
# Biometric Authenticator to integrate with mobile devices
## Problem 
Biometric authentication is a missing functionality as of now in WSO2 product IS. 
Implementation of a biometric authenticator which can be integrated with mobile devices would solve this problem and would give an extra layer of authentication with biometrics.
## Insights behind the feature

- Bringing OOTB support for biometric authentication

- Integrating a passwordless solution for authentication from biometrics is way simpler and faster for the user.

- Biometrics is an inheritance factor(something that you are). Hence it's one of the most secure authentication methods to authenticate a user with the fingerprint.

- Biometric authenticators in the mobile devices are easily accessible to users.

## Design 

Architecture mail thread: [https://markmail.org/message/r2scjjbxfjfdd7yd](https://markmail.org/message/r2scjjbxfjfdd7yd)

The design includes:

-  Two main components (Biometric authenticator and the new endpoint at "/biometric-oath") - related PR wso2-incubator/identity-outbound-auth-biometric#3 

-  Android mobile application - related PR wso2-incubator/identity-outbound-auth-biometric#5

## Documentation 
[https://docs.google.com/document/d/1URKLwzGE8HOzGIsLfGkTbyCgOmEFasqitJZuzuyvCLk/edit?usp=sharing](https://docs.google.com/document/d/1URKLwzGE8HOzGIsLfGkTbyCgOmEFasqitJZuzuyvCLk/edit?usp=sharing)

**Comment by Yasara-Y** [comment]
## Sequence flow
#### Device registration flow (Not yet implemented.)
![deviceregistration](https://user-images.githubusercontent.com/51709964/70298750-b00ac900-1818-11ea-86f7-d5e3c291181c.png)

#### Biometric authentication flow (Implemented.)
![deviceRAeg](https://user-images.githubusercontent.com/51709964/70298690-7e91fd80-1818-11ea-80bb-b509370ccc65.png)

**Comment by Yasara-Y** [comment]
# Android application
## Here are the activites / user interfaces involved in the android application which is developed in kotlin.
![androidapp](https://user-images.githubusercontent.com/51709964/70300892-ce73c300-181e-11ea-99e6-a0b6938d46ce.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
