### ISSUE TITLE
Adding new tables for CIBA.

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#7030]
>  Client-Initiated Back-channel Authentication
* This feature requires two new tables for the successful operation
1. IDN_OAUTH2_CIBA_AUTH_CODE
2. IDN_OAUTH2_CIBA_REQUEST_SCOPES

* Refers PR:
https://github.com/wso2/carbon-identity-framework/pull/2599

**Comment by senthalan** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2599

**Comment by Abilashini** [comment]
Re-opening since these tables need to be added to the migration scripts

**Comment by Abilashini** [comment]
Done with https://github.com/wso2-extensions/identity-migration-resources/pull/39
