### ISSUE TITLE
 Some of the XACML-3.0 functions needs to be  implemented in Balana

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#7042]
The following  XACML-3.0 functions need to be implemented,

- rn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-equal
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-equal
- urn:oasis:names:tc:xacml:3.0:function:dateTime-add-dayTimeDuration
- urn:oasis:names:tc:xacml:3.0:function:dateTime-add-yearMonthDuration
- urn:oasis:names:tc:xacml:3.0:function:dateTime-subtract-dayTimeDuration
- urn:oasis:names:tc:xacml:3.0:function:dateTime-subtract-yearMonthDuration
- urn:oasis:names:tc:xacml:3.0:function:date-add-yearMonthDuration
- urn:oasis:names:tc:xacml:3.0:function:date-subtract-yearMonthDuration
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-one-and-only
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-bag-size
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-is-in
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-bag
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-one-and-only
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-bag-size
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-is-in
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-bag
- urn:oasis:names:tc:xacml:3.0:function:string-from-dateTime
- urn:oasis:names:tc:xacml:3.0:function:map
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-intersection
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-at-least-one-member-of
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-union
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-subset
- urn:oasis:names:tc:xacml:3.0:function:dayTimeDuration-set-equals
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-intersection
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-at-least-one-member-of
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-union
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-subset
- urn:oasis:names:tc:xacml:3.0:function:yearMonthDuration-set-equals
- urn:oasis:names:tc:xacml:3.0:function:access-permitted (optional)

**Comment by EatMeDrinkMe** [comment]
Any updates on this issue?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
