### ISSUE TITLE
New UI for OAuth2 Scopes

### ISSUE THREAD

**Issue by fabiolgc** [wso2/product-is#7046]
Currently OAuth2 Scopes and scope bindings(role, permission etc) can be managed by REST API OAuth2. 
It is important to have this configuration via UI for users or customer who want to use Identity Server without API Manager. 
Through this interface configuration, for example, in  /carbon portal will be possible to control by permissions who can access or modify these settings.

**Comment by darshanasbg** [comment]
Thanks for the input @fabiolgc.. We are in the process of revising handling scopes in IS. @sarubi @inthirakumaaran FYI.

Further @fabiolgc, do you have specific use case that you are trying to achieving here? Would like to know more about on specific details.

**Comment by fabiolgc** [comment]
I am working on an opportunity with a prospective customer where they use Axway as the API Manager platform and they are evaluating IS as their IAM platform for some projects. 

The use case would be manage the Scope and Roles binding via UI besides REST Api. 

Initially the expected scenarios are: 
- Registers a Scope
- Query an Scope by Scope Name
- Query an Scopes binded to a Role
- List of all available Scopes
- Updates a Scope
- Deletes a Scope

They have not mentioned about any restrictions by domain, tenant, user data store, etc. I can ask for additional details if needed. Just let me know.

**Comment by darshanasbg** [comment]
Interesting! Thanks for the details.

If we can verify all the expected use cases can be covered using the existing Scope API (just to validate the capability) that would be sufficient for now to brainstorm on the UI..

I agree that for the day-to-day usage we should have a UI to do to this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
