### ISSUE TITLE
Provide first class support for SAML Service Provider update

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#7050]
With the current implementation of SAMLSSOConfigAdminService or its OSGi service SAMLSSOConfigServiceImpl, we cannot update a service provider.

An update is done by deleting the old SAML SP and creating a new SP with the updated information. If an error occurs while adding the updated SP the SAML SP will be lost.

We need to provide first class support for updating SAML SPs with rollback handled at the persistence layer.

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/master/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/SAMLSSOConfigService.java

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
