### ISSUE TITLE
Improve extensible SCIM user schemas documentation

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#7078]
Current documentation[1] still having SCIM1 and not having SCIM2 samples. We need to add SCIM2 samples into the documentation.

[1] https://is.docs.wso2.com/en/5.9.0/get-started/provisioning-architecture/#extensible-scim-user-schemas

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
