### ISSUE TITLE
Add Rest API Test Cases For APIs that use unique user id

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7087]
Admin REST APIs which are using unique user id as a path parameter can now be enabled as the product supports unique user id for users. But these APIs are not covered with integration tests, only the /me REST API endpoints are covered with integration tests.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
