### ISSUE TITLE
changing encrypted password is not working in cipher tool

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7100]
Changing the encrypted passwords via sh ciphertool.sh -Dchange is not working in IS 5.9.0. This can be reproduced by following this document 
https://is.docs.wso2.com/en/5.9.0/setup/encrypting-passwords-with-cipher-tool/

This is because once the password is changed, it will be changed in cipher-text.properties file, but not changed in deployment.toml file. So once we restart the server, the changes are overridden

**Comment by ddefrancesco** [comment]
Same issue with wso2 apim 3.0.0...download zip version

**Comment by piraveena** [comment]
Yes. This issue exists in IS 5.9.0 and APIM3.0.0 with  cipher-tool version below 1.1.7

**Comment by janakamarasena** [comment]
As a workaround, we can remove the cipher-tool jar inside <HOME>/lib and add the cipher-tool 1.1.9 jar from [here](https://maven.wso2.org/nexus/content/repositories/public/org/wso2/ciphertool/org.wso2.ciphertool/1.1.9/org.wso2.ciphertool-1.1.9.jar) as this issue is fixed in that version.
