### ISSUE TITLE
SCIM should be enabled by default for all the user-stores.

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#7103]
Due to the following reasons, we need to enable SCIM for the user-stores by default form IS 5.10.0,

- With IS 5.10.0, most of the user/server APIs are available as REST APIs and SCIM API is the user management API.
- Also, the UI portals such as user-portal and admin-portal will depend on this for user-related operations.

**Comment by janakamarasena** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/2535
