### ISSUE TITLE
[Windows, Internet Explorer] `SCRIPT5009: scriptTextArea is undefined` Error when trying to add a Function Library

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7105]
**Suggested Labels**
Affected/ IS 5.10.0 M9
Type/ Bug
Priority/ Highest
Severity / Major

**Environment**
Windows Server 2016
JDK 11.0.4
Browser Internet Explorer 11.576

**Steps to Reproduce**

1.Try to add a adaptive authentication with function library [1].
2. Go to Function Libraries > Add
3. Try to add a Function Library Script in the section Function Library Script

**Observation**

UI will not load the Library Script Section to add the Script

Observed the below Javascript ERROR in the browser Console

`SCRIPT5009: scriptTextArea is undefined`

![test](https://user-images.githubusercontent.com/31848014/70891062-7dc54c80-200c-11ea-89a8-e57a683485b9.PNG)

Please note this is a issue that reproduced against the Browser Internet Explorer 11.576 in a Windows Environment.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
