### ISSUE TITLE
Self-registration process

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#7122]
The self-registration process sends two emails, one for account locked and one for email verification/account confirmation. Could it be possible to have the account locked but without sending the account locked email? To have just one email in the process.

Thank you!

**Comment by malithie** [comment]
@piraveena , IIRC we attended on a similar issue. Can you shed some light here.
Below two seems to be discussing a similar case.

[1] https://github.com/wso2/product-is/issues/5451
[2] https://github.com/wso2/product-is/issues/5450

**Comment by piraveena** [comment]
We fixed this with the latest IS and wum updated 5.7.0 and 5.8.0. Please refer to this git issue https://github.com/wso2/product-is/issues/5880.

You have to create a new local claim called accountState with claimURI "http://wso2.org/claims/identity/accountState" and map it. You have to make the accountState claim as readOnly claim.  This claim will be used to track the user's account state

You can find the detailed information here https://medium.com/@piraveenaparalogarajah/introducing-accountstate-claim-to-maintain-the-user-account-status-98a45f0e4edb

**Comment by vihanga-liyanage** [comment]
Closing as this is answered. Please re-open if needed.
