### ISSUE TITLE
NoClassDefFoundError when starting the km server as a windows service.

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#7126]
When starting the wso2 ob km server as a windows service, revived the following error.

```
ERROR {org.wso2.carbon.identity.data.publisher.oauth.internal.OAuthDataPublisherServiceComponent} -  Error occurred while activating Oauth data publisher bundle,  
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
```

**Comment by ShanikaWickramasinghe** [comment]
Can you please let us know in which JDK version this issue is observed. Because there is an already reported issue as in [1] against JDK 11

[1]. https://github.com/wso2/product-is/issues/7008

**Comment by madurangasiriwardena** [comment]
Could not observe with the latest IS 5.10.0 build.
