### ISSUE TITLE
Password History Is Not Cleared When User Store Is Deleted

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7131]
If we delete a user store, the password history of the corresponding users in that store is retained. But in my opinion, password history is coupled with the user store manager thus need to be cleared once the user store manager is removed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
