### ISSUE TITLE
[doc] Mention why Configuring a User Preferred Notification Channel is not available in IS 5.8 and 5.9

### ISSUE THREAD

**Issue by UmenR** [wso2/product-is#7135]
Can we please mention [here](https://docs.wso2.com/display/IS570/Configuring+a+User+Preferred+Notification+Channel) that this particular capability is currently, only available in IS 5.7.0 with a wum update due to a special request, therefore is not available in newer (5.8 & 5.9) versions of IS.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
