### ISSUE TITLE
Support for nested groups based permissions.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#7136]
We will consider the below-nested structure for roles.

– ManagerRole
------------ HRManagerRole
----------------------------ExecutiveHRManagerRole
----------------------------SeniorExecutiveHRManagerRole --> user1
--EngineerRole
--------------IAMEngineerRole

We will be assigning permission to 'ManagerRole'. The expectation is 'user1' who is assigned just with 'SeniorExecutiveHRManagerRole' to have all the permissions assigned to 'ManagerRole'.

**Comment by ruwanta** [comment]
@Pushpalanka 
It is not clear the value of this feature improvement in IAM case. Will you able to explain a bit more of a user-story.

**Comment by Pushpalanka** [comment]
@ruwanta 
This is mostly related to plugin external secondary user stores. Let's consider the below story.
- Admin configures IAM with 2 secondary user stores, both having nested groups.
- They want to let only one set of users from user store A to be able to manage the service providers. The rest of the users just have the login permission.
- Users from the user store B needs to be able to manage the users(CRUD) in the system.

In the case of this external user store is already governing user privilege levels via nested groups in an LDAP structure, the permission assignment task will be straight forward by assigning the required permission just to the relevant root level role. 

I agree that the value will be limited to the ease of admin task of assigning the permissions when there are a lot of roles, that need to be assigned with permissions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
