### ISSUE TITLE
UMA RPT introspection should be allowed for a PAT without verifying further permissions

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#7144]
In WSO2 Identity Server the introspection endpoint is default protected with `'/permission/admin/manage/identity/applicationmgt/view'` permission.
Thus, the introspection request can be initiated only with an access token issued for a user with above permission level.
This complicates the UMA story as the PAT issued for the resource owner is used to access the introspection endpoint to introspect the RPT.
Thus, the resource owner needs to have the above permission level, in order to successfully use PAT to introspect RPT.
But, that should not be the case, ideally if the bearer token coming to introspect endpoint is a PAT (A token issued for the resource owner for uma_protection scope) introspection of the RPT should be allowed.
Moreover RPT should have been issued for a resource of the resource owner for whom the PAT is issued

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
