### ISSUE TITLE
[Migration] DB schema migration for improvements in FIDO2 

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#7150]
- Related issues:
                           - https://github.com/wso2/product-is/issues/6970
                           - https://github.com/wso2/product-is/issues/7151
- Related PR: https://github.com/wso2/carbon-identity-framework/pull/2644
- With this PR it introduces the following new columns to FIDO2_DEVICE_STORE table. This is done for a requirement for improvements in the UI.

DISPLAY_NAME VARCHAR(255)
IS_USERNAMELESS_SUPPORTED CHAR(1) DEFAULT '0'

**Comment by Abilashini** [comment]
Done with https://github.com/wso2-extensions/identity-migration-resources/pull/39
