### ISSUE TITLE
Current login session does not shows when login with fido

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#7152]
1. Login to user portal and configure a fido device as a username less device.
2. Goto session list view and it **can** see the current authenticated session.
3. Login to management console and configure fido as first (& only) step of the user portal app.
4. Logout and login to user portal.
5. Goto session list view and it **cannot** see the current authenticated session.

**Comment by ayshsandu** [comment]
Need to test in latest versions

**Comment by IsuraD** [comment]
Tested the flow in IS 6.0.0 and it is working fine.  Hence closing the issue.
