### ISSUE TITLE
Weird Behaviour of SCIM 1.1 Group Endpoint

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7154]
If a group is added via SCIM 1.1 endpoint after enabling IS to provision to the PRIMARY user store subsequent get group operations don't return SCIM Metadata attributes.

1) Enable IS to provision to the PRIMARY user store

<img width="1133" alt="Screen Shot 2019-12-19 at 2 52 06 PM" src="https://user-images.githubusercontent.com/525801/71216535-96816c80-226f-11ea-8e07-adfba3a2ee96.png">

2) Add a new role via SCIM ep

`curl -v -k --user admin:admin --data '{"displayName": "engineer1","members": []}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Groups`

3) Filter group by displayName

`curl -v -k --user admin:admin https://localhost:9443/wso2/scim/Groups?filter=displayNameEqengineer1`

The result of the final request doesn't return SCIM metadata attributes of the group.

**Comment by IsuraD** [comment]
It is required to enable org.wso2.carbon.identity.scim.common.listener.SCIMUserOperationListener to work with SCIM1.1

Please add the following configs to deployement.toml. 


```
[event.default_listener.scim]
priority= "90"
enable = true

[event.default_listener.scim2]
priority= "93"
enable = false
```
