### ISSUE TITLE
SAML Service Provider Issuer max text length is limited to 100 characters when adding from the UI.

### ISSUE THREAD

**Issue by Prasadi-R** [wso2/product-is#7155]
When adding a **SAML Service Provider** from the management console using manual configuration, it is not allowed to insert an **Issuer** value which is having more than 100 characters. It will truncate the provided Issuer value to 100 characters and save the same truncated value into the database as well.

The cause for the above behavior seems to be, in the **add_service_provider.jsp** which is inside the org.wso2.carbon.identity.sso.saml.ui-[version].jar file, it has restricted the **maxlength** for the **"issuer"** to 100 as follows:
`    <td><input type="text" id="issuer" name="issuer" maxlength="200"
               class="text-box-big"
               value="<%=isEditSP? Encode.forHtmlAttribute(provider.getIssuer()):""%>" <%=isEditSP ? "disabled=\"disabled\"" : ""%>/>`

There are cases we need to add "issuer" values that have more than 100 characters. Therefore, it would be better if this can be fixed.

**Comment by mefarazath** [comment]
The SAML issuer valuer when saved,

* A registry resource is created with the base64encoded value of the issuer (== at the end are omitted). The maximum limit for the name of the registry resource is 256 characters

Considering the above constraint, the max length would be increased to 150 giving a fair chance for the base64 encoded to fall within the max 256 letters
