### ISSUE TITLE
Improve the logic of the "addUserWithID" for performance. 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#7160]
`addUserWithID() `method expects a list of claims to be added.  However, it does not get updated after the user addition with the claims that we have created internally. For example, Internal/everyone role is added from the server-side and if we can update the given list with new claims, we can reduce the second call to get the newer claims and improve the performance.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
