### ISSUE TITLE
User Account Lock feature is not working as expected when the "CaseInsensitiveUsername" property is set to false

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#7169]
Reproduction Steps:

1. Get the latest identity server WUM updated 5.7.0 version.
2. Make sure the below the property is uncommented in the identity-mgt.properties file.
`Identity.Mgt.User.Data.Store=org.wso2.carbon.identity.mgt.store.JDBCIdentityDataStore
`
This will store the identity claim data in the identity database IDN_IDENTITY_USER_DATA table.
3. Then Start the identity server and enable the Account Lock feature as explained in the official doc[1].
4. Then Start the identity server and create a JDBC secondary user store with the below configurations. please note that the Database should be a case-insensitive database such as MySQL.
5. In the secondary user store please make sure the below property is set to false. `<Property name="CaseInsensitiveUsername">false</Property>` 
You can do this in the UI as well. This will mark that the user name should be 
6. Then create a new user in the secondary user store with the name "demo".
7. Now validate that you can log in to the dashboard application with the user name "demo" as well as the "Demo". This will work since the CaseInsensitiveUsername is set to false and now the identity server is treating the user name as the case sensitive. (However please note that from the database level the MySQL DB is case insensitive by default)
8. Now lock the "demo" user by entering the wrong password 5 times.
7. Now please validate that you can not log in with the user name "demo"
8. However, if you tried to log in with the user name "Demo" you will be able to log in. 
9. The cause default H2 database is storing the identity claims in a case sensitive manner and the user store is storing the data in case insensitive manner if the database used is case insensitive database.

This issue needed to be fixed in the product. Since secondary user stores can be various. 

[1] - https://docs.wso2.com/display/IS570/Account+Disabling

**Comment by rksk** [comment]
This seems to be fixed with https://github.com/wso2/product-is/issues/3513
