### ISSUE TITLE
"Enable TOTP" not reflected in the dashboard in user profile after updating it. 

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7171]
Steps to reproduce:

1. Enable TOTP in the Dashboard user profile in IS-5.9.0.
2. Update the profile.
<img width="1677" alt="Screen Shot 2019-12-21 at 7 34 16 PM" src="https://user-images.githubusercontent.com/47600906/71309010-01c26e80-2429-11ea-89e8-a8d10766b484.png">
3. View the profile again. The "Enable TOTP" setting is unchecked and the Scan QR Code is not shown.

I was able to verify that the TOTP code generated by scanning the previously shown QR code works but the settings are not shown in the Dashboard.

**Comment by janakamarasena** [comment]
As a workaround; setting the "Secret Key" claim to supported by default seems to solve the issue.
This can be done by following the below steps from the carbon management console.

1. Click on "List" under "Claims" from the side menu.
2. Click on "http://wso2.org/claims" claim dialect.
3. Click on "Edit" in front of the "Secret Key" claim.
4. Tick the "Supported by Default" checkbox and click "Update"
