### ISSUE TITLE
When the "EnableEmailUserName" is set to true, tenant creation flow is breaking due to email is passed as null to the backend

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#7177]
Reproduction Steps:
1. Get a latest wum updated pack of identity server 5.7.0
2. Then start the identity server and go and create a tenant. It is successful. Please note that when creating the tenant the below email field is visible now,
![Screenshot from 2019-12-23 20-17-02](https://user-images.githubusercontent.com/19922157/71384643-46810d80-25c1-11ea-81fd-f10fe082fac9.png)
3. Now enable the below property in the carbon.xml file
   ` <EnableEmailUserName>true</EnableEmailUserName>`
4. Now you will see that the "Email" field is not visible. As below.
![Screenshot from 2019-12-23 20-14-56](https://user-images.githubusercontent.com/19922157/71384669-67e1f980-25c1-11ea-84aa-6aeb4e08428a.png)
5. So when we try to create a tenant below error is shown in the UI.
![Screenshot from 2019-12-23 20-14-03](https://user-images.githubusercontent.com/19922157/71384680-7cbe8d00-25c1-11ea-936f-15e29ca14b7f.png)

The issue was the logic of the add_tenant.jsp code here[1]

[1] - https://github.com/wso2/carbon-multitenancy/blob/0e0a4f8c0ffb01da7ab92db45aed7ea28a89f53b/components/tenant-mgt/org.wso2.carbon.tenant.mgt.ui/src/main/resources/web/tenant-mgt/add_tenant.jsp#L292

**Comment by DMHP** [comment]
@LahiruLS ,

Did you provide an email for Admin Username? When you make `<EnableEmailUserName>true</EnableEmailUserName>` the Admin Username should be an email. I have tried the same and it worked properly. Can u please check and verify?

**Comment by LahiruLS** [comment]
@DMHP 
Thank you for the clarification. I have tested again. It is working as expected.
