### ISSUE TITLE
Possible duplicates in UM_USER_ATTRIBUTE table

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#7182]
```
CREATE TABLE UM_USER_ATTRIBUTE (
                    UM_ID INTEGER,
                    UM_ATTR_NAME VARCHAR2(255) NOT NULL,
                    UM_ATTR_VALUE VARCHAR2(255),
                    UM_PROFILE_ID VARCHAR(255),
                    UM_USER_ID INTEGER,
                    UM_TENANT_ID INTEGER DEFAULT 0,
                    FOREIGN KEY (UM_USER_ID, UM_TENANT_ID) REFERENCES UM_USER(UM_ID, UM_TENANT_ID) ON DELETE CASCADE,
                    PRIMARY KEY (UM_ID, UM_TENANT_ID))
```

There could be duplicate records in the UM_USER_ATTRIBUTE due to concurrent insertions. For example, if we add the same claim to a user from two nodes concurrently, it would create two records for the same user and the same attribute name. Then if we search for users with that claim, the same user will be listed twice due to this duplication.

This could be avoided with a unique constraint for the columns `UM_ATTR_NAME, UM_PROFILE_ID, UM_USER_ID, UM_TENANT_ID`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
