### ISSUE TITLE
CommonAuthID cookie is cleared on openID logout even when RememberMe option is selected

### ISSUE THREAD

**Issue by sheikirfanbasha** [wso2/product-is#7185]
**Steps to reproduce:**

0. Use `wso2is-5.8.0` version
1.  Log in to an OIDC sp with "remember me" ticked
2. Try OIDC logout
3. Then try Log in to an OIDC sp, the username and password are not pre populated

**Expected result:** when user chooses the "remember me"  option while logging in . The system shall have saved the username and password

**identity.xml config:**

```xml
<JDBCPersistenceManager>
        <DataSource>
            <!-- Include a data source name (jndiConfigName) from the set of data
                sources defined in master-datasources.xml -->
            <Name>jdbc/WSO2CarbonDB</Name>
        </DataSource>
        <!-- If the identity database is created from another place and if it is
            required to skip schema initialization during the server start up, set the
            following property to "true". -->
        <!-- <SkipDBSchemaCreation>false</SkipDBSchemaCreation> -->
        <SessionDataPersist>
            <Enable>true</Enable>
            <Temporary>true</Temporary>
            <PoolSize>0</PoolSize>
            <SessionDataCleanUp>
                <Enable>true</Enable>
                <CleanUpTimeout>20160</CleanUpTimeout>
                <CleanUpPeriod>1440</CleanUpPeriod>
                <!--Instead of deleting all the records at once, we are deleting the records in chunks to prevent the -->
                <!--possible deadlock and lock scenarios. The following property defines the chunk size.-->
                <DeleteChunkSize>50000</DeleteChunkSize>
            </SessionDataCleanUp>
            <OperationDataCleanUp>
                <Enable>true</Enable>
            </OperationDataCleanUp>
            <TempDataCleanup>
                <!-- Enabling separated cleanup for temporary authentication context data -->
                <Enable>true</Enable>
                <!-- When PoolZize > 0, temporary data which have no usage after the authentication flow will be deleted immediately
                 When PoolZise = 0, data will be deleted only by the scheduled cleanup task-->
                <PoolSize>20</PoolSize>
                <!-- All temporary authentication context data older than CleanUpTimeout value are considered as expired
                and would be deleted during cleanup task -->
                <CleanUpTimeout>40</CleanUpTimeout>
            </TempDataCleanup>
            <UserSessionMapping>
                <Enable>true</Enable>
            </UserSessionMapping>
        </SessionDataPersist>
    </JDBCPersistenceManager>

<CacheConfig>
        <!-- Identity cache configuration.
             Timeouts are in seconds.
             Capacity is the maximum cache size.
             Unless specifically mentioned, you do not need to set the isDistributed flag.
         -->
        <CacheManager name="IdentityApplicationManagementCacheManager">
            <Cache name="AppAuthFrameworkSessionContextCache"
                                                     enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="AuthenticationContextCache" enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="AuthenticationRequestCache" enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="AuthenticationResultCache"  enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="AppInfoCache"               enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="AuthorizationGrantCache"    enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="JWKSCache"                  enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="OAuthCache"                 enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="OAuthScopeCache"            enable="true"  timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="OAuthSessionDataCache"      enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="SAMLSSOParticipantCache"    enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="SAMLSSOSessionIndexCache"   enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="SAMLSSOSessionDataCache"    enable="true" timeout="300" capacity="5000" isDistributed="false"/>
            <Cache name="ServiceProviderCache"       enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ServiceProviderCache.ID"       enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ServiceProvideCache.InboundAuth"       enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ProvisioningConnectorCache" enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ProvisioningEntityCache"    enable="true" timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="ServiceProviderProvisioningConnectorCache" enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="IdPCacheByAuthProperty"     enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="IdPCacheByHRI"              enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
            <Cache name="IdPCacheByName"             enable="true"  timeout="900" capacity="5000" isDistributed="false"/>
        </CacheManager>
    </CacheConfig>
```

**Observations:**

* When the user does not choose "remember me" option, `commonAuthId` cookie expiry is set to `Session`
* When the user choose "remember me" option, `commonAuthId` cookie expiry is set to `2 weeks`

* In both cases on logout `commonAuthId` cookie is getting cleared

**Comment by ruwanta** [comment]
Logout supposed to clear all sessions. It should clear all remember-me sessions. 
This is for security reasons, so that user can clear the session on the browser and leave.

Looks like the what mentioned on this issue is correct and expected behavior.

**Comment by sheikirfanbasha** [comment]
Thanks for the quick update @ruwanta  Understood it better now.

For anyone who will have similar question. Below information will be helpful:

# How does RememberMe option work?

## RememberMe option is not selected

By default, if the `RememberMe` option is not chosen, the `commonAuthId` cookie will have an expiry set to `Session` level. Below are the possible cases and behaviour:

=== Web App token expires, but user has not quit the browser yet and try to login again

In this case, since the `commonAuthId` expiry is at `Session` level. And the session is still valid. The user will not be prompted with login page again. He will be auto logged in.

=== Web App token expires, user has restarted the browser and try to login again

In this case, since the browser is restarted, all the `Session` level cookies will be deleted. Hence, when the user try to login, he/she will be prompted with the login page


== RememberMe option is selected

By default, if the `RememberMe` option is chosen, the `commonAuthId` cookie will have an expiry set to `2weeks`. Below are the possible cases and behaviour:

=== Web App token expires, but user has not quit the browser yet and try to login again

In this case, since the `commonAuthId` expiry is set to `2weeks`. The cookie will be  still valid. The user will not be prompted with login page again. He will be auto logged in.

=== Web App token expires, user has restarted the browser and try to login again

In this case, since the browser is restarted, all the `Session` level cookies will be deleted. But, since the `commonAuthId` expiry is set to `2weeks`. The `commonAuthId` wouldn't have been delete. the Hence, when the user try to login, he/she will be auto logged In without the login page prompt.

The idle session timeout and the RememberMe timeout can be configured as follows:

**FileName:** `/usr/lib/wso2/5.8.0/repository/conf/identity/identity.xml`

```xml
<TimeConfig>
        <SessionIdleTimeout>15</SessionIdleTimeout>
        <RememberMeTimeout>20160</RememberMeTimeout>
</TimeConfig>
```

[NOTE]
====
This configuration changes will come into effect for only the new tenants that are created after the server is restarted with these changes. For all the older created tenants the timeout values will be the same as that were present when these tenants are actually created
====

**Comment by ruwanta** [comment]
@sheikirfanbasha , I think Better to update your explanation in the official documentation. Thanks.

I created new documentation issue to track the task.

https://github.com/wso2/docs-is/issues/1015
