### ISSUE TITLE
Issue in adding authorization_manager configurations in deployment.toml

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7187]
The configuration changes are not reflected in user-mgt.xml, to add properties to authorization_manager configuration, if we add following property to deployment.toml,

```
[authorization_manager.properties]
AuthorizationCacheEnabled = false
```

This is because, the default value has been defined as a set of object in default.json file. This needs to be changed as follows untilhttps://github.com/wso2/config-mapper/issues/11 is fixed. Same issue observed with realm_manager as well.

```
"authorization_manager.class": "org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager",
"authorization_manager.properties.AdminRoleManagementPermissions": "/permission",
"authorization_manager.properties.AuthorizationCacheEnabled": "true",
"authorization_manager.properties.GetAllRolesOfUserEnabled": "false",
```
Already this issue identified and fixed in product-apim https://github.com/wso2/product-apim/issues/7133

**Comment by GDRDABARERA** [comment]
Resolved in master hence closing
