### ISSUE TITLE
Password expiry as a default feature

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-is#7188]
Currently, the Password expiry (enforcing password change after every n days) feature has to be configured as a connector [1]. As this is a basic account management feature, to enhance UX, shall we get this functionality into the pack as a default feature?
  
[1] https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/v1.0.8/docs/config.md

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
