### ISSUE TITLE
Enable Account Locking policy by default

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7190]
One of the important countermeasures against the password dictionary attack is locking an account after number of failed login attempts(account locking login policy). It is not enabled by default. If it is not enabled in the real-world it is going to open a security risk. To improve the security of the deployments we should enable this feature by default.

**Comment by ruwanta** [comment]
-1. Very first users or developers of the downloaded pack does mistakes, including entering wrong passwords. Then the pack becomes unusable.
Moreover, it is difficult to recover from this by inexperienced users (new to product). There are ways to get it back, but most probably spent considerable amount of time figuring out.

We need to keep first time developer (or evaluator) experience easy as possible.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
