### ISSUE TITLE
JDBCUserStoreManager doesn't support "displayName" property

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7194]
**Problem**

Customer is federating with Azure AD and just-in-time provisioning users to their local secondary JDBC user store. Azure AD's persistent pseudonym identifier is a non-human-readable which is used as the primary user ID in WSO2. Administrator who use the management console to manage these users can't manage them using these non-human-readable identifiers.

**Solution**

Configure the "DisplayNameAttribute" property in the specific user store which is used to provision federated accounts, so that users can be listed using the human-friendly email addresses or usernames in the federated IdP, but created using the persistent pseudonym identifiers  as primary username while just-in-time provisioning.

However, WSO2 IS doesn't support "DisplayNameAttribute" in JDBCUserStoreManager.

This needs to be classified as a bug on the basis of usability issue it creates.
1. We can't expect customer to have LDAP to provision federated users.
2. We can't provision using a mutable identifier which breaks the link.
3. We can't expect the administrators to manage users using the persistent pseudonym identifiers returned from federated IdP.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
