### ISSUE TITLE
"Account Blocked Reason" attribute not supported

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7195]
Account blocked reason is not supported as an attribute which is expected to work similarly to account locked reason attribute. Accounts can be blocked by administrator or inactivity. Similarly there are customers who have extended the product and block accounts for others reasons as well. Account blocked reason attribute should be updated for those reasons as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/145
