### ISSUE TITLE
Federated account linking cannot be done based on an attribute of a local account

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7196]
Federated account linking can only be done based on the match of user ID of a local account in IS with an attribute of a federated account. We cannot do it based on the match of an attribute of a local account in IS with an attribute of a federated account.

**Comment by ruwanta** [comment]
@johannnallathamby 
Can you explain what needs to be the logical flow for the said accociation

**Comment by johannnallathamby** [comment]
@ruwanta there was a typo in the comment and I've corrected it now. Please check if it makes sense now.

In IS we need to be able to configure a verified claim URI that is matched up with a verified claim in the federated account and linked.

**Comment by ruwanta** [comment]
+1 for the improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/188
