### ISSUE TITLE
Cannot combine attributes from a federated login and linked local account and assert

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7197]
In federated account linking scenario we cannot combine attributes that are asserted by a federated IdP and attributes fetched from local user store and assert to the service provider.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Should be covered with https://github.com/wso2-enterprise/iam-product-management/issues/188
