### ISSUE TITLE
Cannot explicitly fail login if a linked local account is not found

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7198]
In a federated account linking scenario, we cannot define a policy which says to fail the login if a linked local account is not found.

The current behavior of IS is, even if we have checked the "assert identity using the mapped local subject identifier" checkbox under service provider configuration, if a linked local account is not found, IS will pass through the identifier received from the federated IdP.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
