### ISSUE TITLE
Support enforcing authorization policies on federated account assertions

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7200]
Currently authorization policies in SSO flow, can only be enforced for local account and federated accounts that have a linked local account. We cannot enforce them on federated accounts that don't have linked local accounts.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
