### ISSUE TITLE
Support sending permissions of the user in the assertion

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7201]
Currently we can only send attributes and groups/roles of the user in the attribute statements of an assertion. We also must be able to send permissions because some users want to be able to model coarse grained hierarchical authorization based on our permission model.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
