### ISSUE TITLE
Supporting transferring of access tokens from federated authorization servers in assertions to service provider

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7202]
At the time we designed the authentication framework, OpenID Connect wasn't around and SAML2 SSO and WS-Federation were clearly federated authentication protocols where as OAuth2 was a rather different species. But with the advent of OpenID Connect the federated authentication and access delegation capabilities have converged to one protocol, so now this becomes a valid requirement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
