### ISSUE TITLE
Non-JIT provisioned roles of a user are removed during JIT update

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7203]
Any roles that have been manually added after a user is JIT provisioned, is removed during next JIT update.

**Comment by rksk** [comment]
**Suggested solution**
Consider idp role mappings and allow any local role which is not mapped to an external role not to be touched during JIT provisioning.

We may need to align the solution with the fix for [1] since it is also related to this but it is a different usecase.

[1] https://github.com/wso2/product-is/issues/11195

**Comment by nipunthilakshan** [comment]
I will work on this.

**Comment by isuruirj** [comment]
This is not completely fixed. If there are no idpToLocalRoleMapping, roles that have been manually added after a user is JIT provisioned are removed during the next JIT update.

Below is the IdP claim and role configurations.
<img width="1148" alt="Screenshot 2021-06-05 at 2 20 38 AM" src="https://user-images.githubusercontent.com/13187638/120861309-be1fde00-c5a4-11eb-8eb1-5e42a8ed7360.png">


Observed this in both IS-5.10.0+1622383532375 and IS-5.11.0

**Comment by Pushpalanka** [comment]
Hi @isuruirj ,
Is this confirmed with the below configurations in place as well?

`[idp_role_management]
return_only_mapped_local_roles = true
return_manually_added_local_roles = true`

**Comment by isuruirj** [comment]
Hi @Pushpalanka 

yes, even with the above two properties, it won't work.

**Comment by rksk** [comment]
Please note when backporting: This fix caused a regression https://github.com/wso2/product-is/issues/12081

**Comment by rksk** [comment]
documentation is pending

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
