### ISSUE TITLE
Cannot dynamically add an X509 certificate to the truststore for outbound connections to AD user stores without restarting the server

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7204]
We can't dynamically add an X509 certificate to the truststore when establishing connection to a new AD in read-write mode. In order to do this we need to us the new Truststore reload feature [1] for secondary user stores as well.

As a workaround we've provided a property to disable certificate validation [2], but that is not a permanent solution.

[1] https://github.com/wso2/carbon-identity-framework/pull/1387
[2] https://github.com/wso2/product-is/issues/6902

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
