### ISSUE TITLE
Support for JIT federated account linking to existing accounts

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7205]
Currently JIT federated account linking is only supported for new accounts. It is not supported for existing accounts. Federated account linking may be supported in 2 ways:
1. Implicit linking by admin configuration such as username match or attribute match
2. Explicit account linking such as interactive linking by the user by proving ownership of local identifier.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
#1 will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/328
#2 will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/160
