### ISSUE TITLE
Cannot specifically identify session expiry event

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7209]
With IS Analytics we had the capability of identifying session expiry events. Currently we don't have this capability. This is needed to cleanup tasks of sessions such as sending back-channel logout requests to service providers on session timeouts, etc.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
