### ISSUE TITLE
Why email claim is considered the user id if user id claim URI is not configured?

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7213]
**Setup**
Details are provided in [1].

**Issue**
Why is Facebook authenticator defaulting to 'email' claim as the user ID in IS, while I've configured the 'id' claim as the mapped claim for 'http://wso2.org/claims/username'? 'id' is the persistent and immutable user ID in Facebook. Ideally that should be considered as the default user ID, unless we've mapped a different claim to 'http://wso2.org/claims/username' or we've configured a different claim as the 'username claim URI' under claim configuration.

[1] "[IAM] Issues and Inconsistencies in Federated Flows" in dev@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
