### ISSUE TITLE
"Username Claim URI" in identity provider is changed from "no selection" to "email"

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7214]
**Setup**
Details can be found in [1].

**Issue**
I've noticed a very weird issue. Although I left the 'Username Claim URI' to its default (no selection) and saved the configuration, every time I do a federated login flow through Facebook and user gets provisioned,  and I go back and check the config, it has changed to 'email'. It is quite weird how a runtime action is changing the config data. Not sure if this is in anyway connected to #7213.

[1] "[IAM] Issues and Inconsistencies in Federated Flows" in dev@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
