### ISSUE TITLE
Email domain stripped before sending to service provider

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7215]
**Setup**
Details are provided in [1].

**Issue**
If 'email' is used as the user ID claim URI, the email address's domain part is stripped before provisioning and sending the response back to service provider? Shouldn't we treat all IdPs as 3rd parties by default and not consider the '@XXX' part as the tenant domain in WSO2? The default behavior IMO should be not to strip anything off. If needed this can be controlled through the adaptive authentication script.

[1] "[IAM] Issues and Inconsistencies in Federated Flows" in dev@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
