### ISSUE TITLE
Undocumented/unexplained behavior with account linking and JIT provisioning

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7216]
**Setup**
Details are provided in [1].

**Issue**
I changed the 'Username Claim URI' configuration to 'id', so that username is provisioned with Facebook user ID, as well as the link is always created between IS username and Facebook user ID.
I did federated account linking with my Facebook ID to an account in the PRIMARY user store. 3. 3. However, when I login through Facebook using same ID, a new user account is always provisioned in MYSQL user store but sends back the linked account in PRIMARY user store.

Following message in console is printed:
"[2020-01-05 21:33:32,751]  INFO {org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler} -  An association already exists for user: 10213967491684052. Skip association while JIT provisioning"

There seems to be no use case behind this behavior and it seems to be undocumented/unexplained.

[1] "[IAM] Issues and Inconsistencies in Federated Flows" in dev@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Must be fixed with https://github.com/wso2-enterprise/iam-product-management/issues/328
