### ISSUE TITLE
Incorrect subject claim sent on first response to service provider

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7217]
**Setup**
Details are provided in [1].

**Issue**
I removed the federated account link in issue #7216 and deleted the provisioned user account in MySQL. I again tried logging in through Facebook with JIT provisioning, and on the first login, the 'Subject Claim URI' in service provider response is not picked up, instead the 'Username Claim URI' set in IdP side, is what comes as the subject to the service provider response. E.g. in my setup the Facebook User ID comes as the subject during first login. From 2nd login onwards it sends whatever is configured in 'Username Claim URI'. In my case 'mobile' number.

[1] "[IAM] Issues and Inconsistencies in Federated Flows" in dev@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Must be fixed with https://github.com/wso2-enterprise/iam-product-management/issues/328
