### ISSUE TITLE
Local account linking

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7218]
Details can be found in [1].

[1] "[IAM] What is our Strategy on Local Account Linking?" in architecture@wso2.org

**Comment by madurangasiriwardena** [comment]
@johannnallathamby can you add the required information in the issue itself, rather than pointing to a mail thread.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/363
