### ISSUE TITLE
Improvements needed in federated account linking

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7219]
A single physical user may have a set of linked local accounts in WSO2 Identity Server. The same physical user may have one or more federated identities also.

**Problems**
1. How to reliably link all the federated identities to the set of linked local accounts?
2. How do we allow users to login with any one of the federated accounts and get mapped to the primary local account or one of the other local accounts based on either configuration or user input and login to service provider?

Details can be found in [1].

[1] "[IAM] Discussion point on Federated Account Linking" in architecture@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be covered with https://github.com/wso2-enterprise/iam-product-management/issues/363
