### ISSUE TITLE
Cannot link multiple federated accounts in the same IdP to a single local account.

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7220]
Details can be found in [1].

[1] "[IAM] Discussion point on Federated Account Linking" in architecture@wso2.org

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Should be covered by https://github.com/wso2-enterprise/iam-product-management/issues/160
