### ISSUE TITLE
Expose account linking functionality via adaptive authentication script

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7222]
Following are the use cases:
1. Read the account linking information in the middle of the authentication flow
2. Link accounts dynamically in the middle of the authentication flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Will be covered with
1. For B2C - https://github.com/wso2-enterprise/iam-product-management/issues/160
2. For B2B - https://github.com/wso2-enterprise/iam-product-management/issues/188
