### ISSUE TITLE
"ui.execute" is the only action supported in RemoteAuthorizationManager API

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#7223]
"ui.execute" is just a constant action for management console permissions. But for other permissions we should be able to create, authorize and retrieve any resource and action value. Both "getAllowedUIResourcesForRole" and "getAllowedUIResourcesForUser" methods return only the resource part of the permission but not respective action.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
This must be covered with https://github.com/wso2-enterprise/iam-product-management/issues/278
