### ISSUE TITLE
Hybrid role listing stick in to case sensitivity

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7226]
With this PR\[1] we have implemented "Support hybrid role listing & filtering with domain parameter for SCIM" but currently the implementation is stick with case sensitivity but ideally we should not stick in to case sensitivity.

**Reproduce steps:-**

1. curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?domain=primary' or curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?domain=PRIMARY' 
 **You will get all the roles in primary user store.**

2. curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?domain=application'
**No roles returned**

3. curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?domain=Application'
Application roles are returned
 

\[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/190

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
