### ISSUE TITLE
Email OTP returns success without authenticating when the user has disabled it.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#7238]
### Steps to Reproduce.

1. Setup email OTP and SMS OTP as second-factor auth. [1], [2]
2. Try one time to make sure the setup works. After the basic auth, a screen to choose SMS or Email OTP will be displayed. When Email is selected, an OTP should be sent to the user's email and needs to be validated.
3. Go to the user dashboard and disable Email OTP using the DisableEmailOTP Claim.
4. Now try to authenticate again. After the basic auth, click on the Email option in second factor. The user is directly logged in bypassing the second factor.

### Ideal Behavior
- Authentication should be denied if Email OTP is selected.

### Note
- Please make sure other OTP based authenticators such as SMS don't share the same bug. If does, need to fix them as well.

[1] - https://docs.wso2.com/display/IS530/Configuring+Email+OTP
[2] - https://docs.wso2.com/display/IS530/Configuring+SMSOTP

**Comment by senthalan** [comment]
We can force the email OTP by providing the following property in the 'EmailOTP' authenticator config in IS_HOME/repository/conf/identity/application-authenticators.xml,

`<Parameter name="EMAILOTPMandatory">true</Parameter>
`
This will be redirected to the error page if the user(who disabled the email OTP using the claim) clicks the email OTP as the 2nd step.
