### ISSUE TITLE
DB Script issues with Oracle 19c 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7239]
Test environment: Oracle 19c 
Product version : wso2is-5.10.0-alpha2-SNAPSHOT
script: wso2is-5.10.0-alpha2-SNAPSHOT/dbscripts/oracle.sql

Description: 
Error starting at line : 822 in command -
CREATE TABLE IF NOT EXISTS UM_UUID_DOMAIN_MAPPER (
            UM_ID INTEGER,
            UM_USER_ID VARCHAR(255),
            UM_DOMAIN_ID INTEGER NOT NULL,
            UM_TENANT_ID INTEGER DEFAULT 0,
            PRIMARY KEY (UM_ID),
            UNIQUE (UM_USER_ID),
            FOREIGN KEY (UM_DOMAIN_ID) REFERENCES UM_DOMAIN(UM_DOMAIN_ID)
)
Error report -
ORA-00922: missing or invalid option
00922. 00000 -  "missing or invalid option"
*Cause:    
*Action:

Sequence UM_UUID_DOMAIN_MAPPER_SEQUENCE created.

Error starting at line : 836 in command -
CREATE OR REPLACE TRIGGER UM_UUID_DOMAIN_MAPPER_TRIGGER
                    BEFORE INSERT
                    ON UM_UUID_DOMAIN_MAPPER
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                    BEGIN
                    SELECT UM_UUID_DOMAIN_MAPPER_SEQUENCE.nextval INTO :NEW.UM_ID FROM dual;
              END;
Error report -
ORA-00942: table or view does not exist
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:

Error starting at line : 846 in command -
CREATE INDEX UUID_DM_UID ON UM_UUID_DOMAIN_MAPPER(UM_USER_ID)
Error report -
ORA-00942: table or view does not exist
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:

Error starting at line : 848 in command -
CREATE INDEX UUID_DM_UID_TID ON UM_UUID_DOMAIN_MAPPER(UM_USER_ID, UM_TENANT_ID)
Error report -
ORA-00942: table or view does not exist
00942. 00000 -  "table or view does not exist"
*Cause:    
*Action:

**Comment by IsuraD** [comment]
Fixed  with https://github.com/wso2/carbon-kernel/pull/2523
