### ISSUE TITLE
Handle parallel scope addition for Postgres database

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7241]
In the 1st server startup of the deployment, scopes are added to the database. If 2 or more nodes are started parallelly for the first time, it can raise a race condition which will cause errors in server startup. This is fixed with [1]. But Postgres database does not throw the checked exception. SO we have to handle it separately.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1289

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
