### ISSUE TITLE
Adding custom RecoveryScenarios in custom event handlers breaks the login flow.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7244]
When a custom recovery scenario is persisted in the database as shown below:

<img width="1024" alt="Screen Shot 2020-01-03 at 9 07 58 PM" src="https://user-images.githubusercontent.com/47600906/72040080-77ee1e80-32cd-11ea-9272-736da721eeec.png">

When the user tries to login the PRE_AUTHENTICATION event triggers the adminForcedPasswordReset handler in this handler flow the following point in the code hits[1].

Since the custom recovery scenario is not available in the org.wso2.carbon.identity.recovery.RecoveryScenarios enum class the following exception is seen.
<img width="1674" alt="Screen Shot 2020-01-03 at 8 54 18 PM" src="https://user-images.githubusercontent.com/47600906/72040762-8fc6a200-32cf-11ea-87e2-78ee500939a4.png">

[1]https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/store/JDBCRecoveryDataStore.java#L260

**Comment by madurangasiriwardena** [comment]
Hi @tharakawijekoon, at the moment this is not considered as an extension point. However, we can consider this as an extension point and add this improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
