### ISSUE TITLE
SCIM2 user endpoint doesn't return internal/everyone role - should be documented

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#7254]
IS-5.6.0
Update version - 1578458664468

With this WUM update, we are returning the internal roles as well. But, not the everyone role as it is for the  sole purpose if WSO2 Identity Server internals. This should be documented.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
