### ISSUE TITLE
Federation User Association by default enabled in IS - 5.6

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#7257]
https://docs.wso2.com/display/IS560/Associating+User+Accounts#AssociatingUserAccounts-ManagingfederateduserIDs

According to this documentation, the Federation User Association should be by default disabled. As the property related to this is not present this becomes default enabled in 5.6. Hence need to make this disabled in code level

**Comment by madurangasiriwardena** [comment]
Closing the issue since the latest product versions contain the property in the identity.xml by default, disabling the feature and if the property is not there the default behavior is the feature is disabled.

**Comment by Buddhimah** [comment]
Since in the Identity Server, 5.6 is feature was default enabled, disabling it from the code level will break the backward compatibility. Hence decided to make this default enabled and update the updated documentation to disable this 
https://docs.wso2.com/display/IS560/Associating+User+Accounts#AssociatingUserAccounts-ManagingfederateduserIDs
