### ISSUE TITLE
[Doc] incorrect property when enabling kerberos_grant type in IS 5.9.0

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7258]
In documentation [1] it  mentioned that

To enable the Kerberos grant, add the following entry to the deployment.toml file in the <IS_HOME>/repository/conf/ folder.

```
[oauth.grant_type.kerberos_grant]
enable = true
```

But it should be corrected as follows

```
[oauth.grant_type.kerberos]
enable = true
```
[1] https://is.docs.wso2.com/en/next/learn/kerberos-grant/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
