### ISSUE TITLE
Change the scim2 documentation URI

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7263]
**Description:**
When SCIM 2.0 REST APIs doc for IS5.9.0 is ready then change the below key.

`scim2.documentation_uri`

Moved from https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/issues/181

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
