### ISSUE TITLE
Issue in UMA policy evaluation in a tenant flow

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#7264]
When trying out the UMA flow in a tenant, the added policy doesn't get evaluated. It looks like the code is trying to pick the policy from the super tenant. As if we put the policy to the super tenant the UMA flow works as expected.

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/5282. Since above explanation is easier to understand closing https://github.com/wso2/product-is/issues/5282
