### ISSUE TITLE
Incorrect default config for EnableMaxUserLimitForSCIM and EnableMaxUserLimitForSCIM configuration are  not documented

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7267]
According to the scim2 specification [1] maximum number of the results of the pagination parameter 'count',  should be specified by the service provider if it is not set by the user. 

Therefore  'EnableMaxUserLimitForSCIM' parameter in user management configuration has been introduce to enable this configuration and support to backward compatibility. 

If the parameter set to 'true' and parameter count not set by the user, the maximum number of the result will limited to 100. if it is false, it will list all the results. 

Currently 'EnableMaxUserLimitForSCIM' parameter default value is false which is not match with the SCIM2 specification and this will lead to a system crash if the list is a large amount.  

To resolve this,
- Parameter default value should change as 'true'.
- Add this to migration document as a behavioral change because with this changes, listing the users will be limited to 100 if not specify the parameter 'count'.
- And also , 'EnableMaxUserLimitForSCIM' parameter configuration details should add to the user management configuration  documents [2]

[1] https://tools.ietf.org/html/rfc7644    page 25
[2] 
https://is.docs.wso2.com/en/next/setup/configuring-a-jdbc-user-store/
https://is.docs.wso2.com/en/next/setup/configuring-a-read-only-ldap-user-store
https://is.docs.wso2.com/en/next/setup/configuring-a-read-write-active-directory-user-store
https://is.docs.wso2.com/en/next/setup/configuring-a-read-write-ldap-user-store

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
