### ISSUE TITLE
client_id is a mandatory request param in the device flow

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#7275]
When using the device flow and doing the initial call the client_id is currently mandatory in the request. 

But according to the [spec](https://tools.ietf.org/html/rfc8628#section-3.4) it should be as follows;

> client_id
>       REQUIRED if the client is not authenticating with the
>       authorization server as described in [Section 3.2.1. of [RFC6749]](https://tools.ietf.org/html/rfc6749#section-3.2.1).
>       The client identifier as described in [Section 2.2 of [RFC6749]](https://tools.ietf.org/html/rfc6749#section-2.2).

**Comment by ChamathNS** [comment]
I'm working on this.
