### ISSUE TITLE
Group not return with SCIM2 filtering and listing

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7279]
By default there is set of claim get return  in the SCIM2 listing and filtering which include group as well. But currently group not return at SCIM2 filtering and listing.

Validated with the product version 5.8.0 and 5.9.0 and 'group' is return with filtering and listing. 

Request:
`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?filter=userName+eq+isTestUser_1'`

Response:

`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"emails":["test@wso2.com"],"profileUrl":"http://test.com","meta":{"created":"2020-01-14T05:56:02.465Z","location":"https://localhost:9443/scim2/Users/5ce492b1-f68d-4725-a92c-06b881b829c1","lastModified":"2020-01-14T06:11:37.741Z","version":"testim","resourceType":"User"},"name":{"givenName":"givenname_isTestUser_1","familyName":"lastname_isTestUser_1"},"id":"5ce492b1-f68d-4725-a92c-06b881b829c1","userName":"isTestUser_1","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"organization":"wso2"},"phoneNumbers":[{"type":"mobile","value":"0981276589"}]}]}`

**Comment by ShanikaWickramasinghe** [comment]
Observing the same issue with the tenant flow as well while trying to list users in a secondary domain unique id jdbc userstore groups assigned for the user is not retrieved.

**Request**  

`curl -v -k --user admin@wso2.com:admin 'https://localhost:9443/t/wso2.com/scim2/Users?domain=TENANTJUNIQUEIDJDBCSECONDARY' -i
`
`Response`

`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"meta":{"created":"2020-02-03T07:27:47.387Z","location":"https://localhost:9443/t/wso2.com/scim2/Users/754f4645-94ad-4ff6-a052-419f6448dec2","lastModified":"2020-02-03T07:27:47.387Z","resourceType":"User"},"id":"754f4645-94ad-4ff6-a052-419f6448dec2","userName":"tenantsecuser1"}]}`
