### ISSUE TITLE
SCIM2 GET User Request with pagination fails with 500 with a UNIQUE ID JDBC Secondary user store

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7280]
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7

1. Add a secondary user store with type UNIQUEID JDBC USER STORE
2. Enable SCIM for the added secondary user store
3. Add a new user for the user store created in step 1
4. Try to GET users with below request with pagination

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?startIndex=1&count=2&domain=UNIQUEIDJDBC'
`

**Response**```

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: localhost (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=CA,L=Mountain View,O=WSO2,OU=WSO2,CN=localhost
* 	 start date: Wed, 23 Oct 2019 07:30:43 GMT
* 	 expire date: Tue, 25 Jan 2022 07:30:43 GMT
* 	 issuer: C=US,ST=CA,L=Mountain View,O=WSO2,OU=WSO2,CN=localhost
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'admin'
> GET /scim2/Users?startIndex=1&count=2&domain=UNIQUEIDJDBC HTTP/1.1
> Host: localhost:9443
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 500 
< Cache-Control: private
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Tue, 14 Jan 2020 10:16:29 GMT
< Content-Type: application/scim+json
< Content-Length: 172
< Connection: close
< Server: WSO2 Carbon Server
< 
* Closing connection 0
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error while retrieving users for the domain: UNIQUEIDJDBC with limit: 2 and offset: 1.","status":"500"}
```

**Comment by IsuraD** [comment]
Tested in IS 5.11.0 beta2 and cannot reproduce the issue. The issue could have been already fixed.
