### ISSUE TITLE
Need to write integration testcase for oauth application exports as a xml file scenario

### ISSUE THREAD

**Issue by piyumidasanayaka** [wso2/product-is#7281]
Due to gives an internal server error when using Application management Rest API to export oauth application as a xml file, changed the way of getting app information.
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1293
So we need to include integration testcases.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
