### ISSUE TITLE
[Improvement] Cleanup Stored Procedures logging should be store with a temporary table.

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#7282]
**Issue.**
As of now, cleanup stored procedures [1] logging is available as the console output only. hence it's hard to trace back the cleanup activity once the stored procedure deployed as a scheduled task in the RDBMS.

**Solution**
Improve the logging capability to insert the logs into a temporary table in the schema, Hence previous execution of the scheduled task logs can be monitored at a later time.

[1] https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
