### ISSUE TITLE
[Doc] SCIM create user samples need to be updated.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7283]
SCIM "CreateUser" doc[1] needs to be updated to warn users that if the askPassword feature is used the email address is a mandatory claim. If the current samples are used for user creation and askPassword feature is enabled errors will be observed in the sever.

The sample request in the following doc[2] is updated through the issue[3] but it is not specifically mentioned in the doc.

[1]https://docs.wso2.com/display/IS580/Using+the+SCIM+2.0+REST+APIs#UsingtheSCIM2.0RESTAPIs-POST/CreateUser
[2]https://docs.wso2.com/display/IS580/Creating+Users+Using+the+Ask+Password+Option
[3]https://github.com/wso2/product-is/issues/4973

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
