### ISSUE TITLE
determine fidp from Issuer in IdP-initiated SAML2

### ISSUE THREAD

**Issue by hauntingEcho** [wso2/product-is#7284]
Currently, IdP-initiated SAML2 is not supported for configured IdPs.  However, there is an ability to trigger the SP-initiated flow against IdP `x` by hitting `/samlsso?fidp=x`.

Enabling the `/commonauth` endpoint to determine the correct fidp from the Issuer present in the SAML2 message would:
- allow much simpler configuration of the federated IdPs
- remove the need to provide separate configuration metadata, with differing fidp parameters, to each.

**Comment by hauntingEcho** [comment]
We are using wso2is as an identity bus - our SaaS receives mapped local subject identifiers from WSO2IS, which in turn handles users from multiple identity providers.

For clarity, I was referring to the 'issuer' present in the SAML2 message received from the IdP, which is the IdP's issuer name.  The SP's issuer name is unrelated.

**Comment by hauntingEcho** [comment]
An example for further clarity:

* two connected instances of WSO2IS via these instructions: https://docs.wso2.com/display/IS560/Log+in+to+the+Identity+Server+using+another+Identity+Server+-+SAML2
* using those same instructions, 'primary' is connected to another WSO2IS instance Idp.  Lets' call it 'otherIdp'.
* 'primary' is connected to a service provider, lets' call it "SP", which is configured to take 1-step authentication from either 'secondary' or 'tertiary' and allows IdP-intiated login
* for ease of use, assume everything is on localhost with primary on port 9443, secondary on port 9444, and otherIdp on port 9445.

currently, for IdP-initiated login, 'secondary' must be given the ACS "https://localhost:9443?fidp=secondary&spEntityID=SP" and "otherIdp" must be given "https://localhost:9443?fidp=otherIdp&spEntityID=SP" in order to skip making the user choose the right IdP.  This means that a different metadata file would need to be manually created for each IDP to be configured.

However, in the IdP-initiated SAML flow, OtherIdp is already posting a SAML2 message with "<issuer>otherIdp</issuer>" and Secondary is already posting a SAML2 message with "<issuer>secondary</issuer>".  By using this field, the fidp parameter becomes unnecessary and configuration becomes more reusable.  The X509 certificate field can also be used for differentiation in messages with signed elements.

**Comment by thanujalk** [comment]
@hauntingEcho Thanks for the detailed clarification. Yes, for the federated IdP initiated SSO case, `fidp` parameter is redundant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
