### ISSUE TITLE
Invalid map for local claim http://wso2.org/claims/im

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7288]
IM value (http://wso2.org/claims/im ) is define for the Instant Messenger (IM) details. Currently there are few issues can be find related to this user profile attribute.
1. Local IM claim is mapped to the claim URI, urn:ietf:params:scim:schemas:core:2.0:meta.version which is not a valid. According to the SCIM 2 spec, version is the current resource version.  Version MAY be used if the service provider supports entity-tags (ETags) and "method" is "PUT", "PATCH", or "DELETE" [1]

2.  Lack of description about the claim
![image](https://user-images.githubusercontent.com/39077751/72495263-34a32b00-384c-11ea-9d73-ebba72ba774d.png)

3. No description available at the official documentation regarding IM claim.

4. Supported by Default should be false since this claim is not important as default.

Validate with the version 5.8.0 and 5.9.0. Issue presented at those version as well.

[1] https://tools.ietf.org/html/rfc7644#page-49

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
