### ISSUE TITLE
Handle migration for dropping redundant indexes

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7291]
Handle migration for the fix done to resolve https://github.com/wso2/product-is/issues/6177

Below indexes are dropped

- REG_PATH_IND_BY_NAME
- SYSTEM_ROLE_IND_BY_RN_TI
- UUID_DM_UID

**Comment by ayshsandu** [comment]
@Buddhimah can you verify this in latest version.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
