### ISSUE TITLE
[Doc] better remove the 'n to n' from content and define them 

### ISSUE THREAD

**Issue by chamindi-a** [wso2/product-is#7292]
##URL: https://is.docs.wso2.com/en/latest/get-started/overview/
heading: The Identity Server and the solution it provides

Better to define the term 'n to n' or rewrite as many to many (n to n)

**Comment by chamindi-a** [comment]
ACK

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
