### ISSUE TITLE
Random password generation and generalization should be in usercore level

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7295]
Random password generation and generalization should be in usercore level and should not implement in each other component (Ex. Provisioning handler), 

So the ideal solution would be

1. Have a general util method to generate the random password in user core level

2. Each Userstore manager implementation should check requirePasswordChange variable and generate a random password with above method

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
