### ISSUE TITLE
Wrong behavior on SCIM2 delete a user from the read only Ldap.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7299]
When an admin user attempt to delete a user who is not existing the unique id read only  Ldap user store, gets 404 error. This behavior is acceptable if we have write access to the user store. 
Therefore this scenario behavior should change and response should be 406 since the delete methods is not allowed in read only user store. 

Same behavior found by validating  the product version 5.9.0 and 5.8.0 as well.

**Request:** (user is invalid)
`curl -v -k --user admin:admin -X DELETE https://localhost:9443/scim2/Users/2acbee42-3561-4ae6-bf89-23fc43da6353 -H "Accept: application/scim+json"`

**Response:** 
```
curl -v -k --user admin:admin -X DELETE https://localhost:9443/scim2/Users/b228b59d-db19-4064-b637-d33c31209fae -H "Accept: application/scim+json"
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Specified resource (e.g., User) or endpoint does not exist.","status":"404"}
```

**Comment by aaujayasena** [comment]
Observed invalid behavior on PUT/ Update User method as well.
User: Not existing in the user store
User store: read_only_ldap_unique_id

Request:
`curl -v -k --user admin:admin -X PUT -d '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","emails":[{"value":"kim_j@wso2.com","type":"work"},{"value":"kim.jack@gmail.com","type":"home"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/c8c821ba-1200-495e-a775-79b260e717bd`

Response: 
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in getting user information from Carbon User Store foruser: c8c821ba-1200-495e-a775-79b260e717bd","status":"500"}`

**Comment by ashendes** [comment]
> When an admin user attempt to delete a user who is not existing the unique id read only Ldap user store, gets 404 error. This behavior is acceptable if we have write access to the user store.
> Therefore this scenario behavior should change and response should be 406 since the delete methods is not allowed in read only user store.
> 
> Same behavior found by validating the product version 5.9.0 and 5.8.0 as well.
> 
> **Request:** (user is invalid)
> `curl -v -k --user admin:admin -X DELETE https://localhost:9443/scim2/Users/2acbee42-3561-4ae6-bf89-23fc43da6353 -H "Accept: application/scim+json"`
> 
> **Response:**
> 
> ```
> curl -v -k --user admin:admin -X DELETE https://localhost:9443/scim2/Users/b228b59d-db19-4064-b637-d33c31209fae -H "Accept: application/scim+json"
> {"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Specified resource (e.g., User) or endpoint does not exist.","status":"404"}
> ```

The 404 response seems to be correct as it caters to the generic scenario where there could be multiple userstores of different read-write permissions. The request to the SCIM endpoint would be made with just the `userid` without specifying any userstore. Then the search for the specified user happens by scanning through the entire userstore chain, after which the read-write permissions are checked depending on the userstore to which the specified user belongs.

**Comment by ashendes** [comment]
> Observed invalid behavior on PUT/ Update and PATCH/Update User method as well.
> User: Not existing in the user store
> User store: read_only_ldap_unique_id
> 
> Request:
> `curl -v -k --user admin:admin -X PUT -d '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","emails":[{"value":"kim_j@wso2.com","type":"work"},{"value":"kim.jack@gmail.com","type":"home"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/c8c821ba-1200-495e-a775-79b260e717bd`
> 
> Response:
> `{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in getting user information from Carbon User Store foruser: c8c821ba-1200-495e-a775-79b260e717bd","status":"500"}`

I was not able to reproduce this on IS-5.11.0-beta6. Getting 404s for both the PUT and PATCH operations.
