### ISSUE TITLE
SCIM 2 emails field handling is different than in the RFC

### ISSUE THREAD

**Issue by bala-striva** [wso2/product-is#7304]
WSO 2 IS version: 5.9

According to the RFC email field should be a multi value field. (https://tools.ietf.org/html/rfc7643#section-4.1.2)

* IS is mixing the types here using simple string and objects
* the primary flag is not used

E.g.: user created with SCIM with the work email address, and after that I edited the user in the management interface and provided the email address.
```
            "emails": [
                {
                    "type": "work",
                    "value": "work@lolo.lolo"
                },
                "email@lolo.lolo"
            ],
```

Creating user with primary flag
```
[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]
```

In the response the flag is lost
```
    "emails": [
        {
            "type": "work",
            "value": "kim_j@wso2.com"
        },
        {
            "type": "home",
            "value": "kim.jackson@gmail.com"
        }
    ],

```

**Comment by emswbandara** [comment]
Regarding issue #1, the spec defines that elements of a Multi-Valued Attributes can be either primitive values, or objects with a set of sub-attributes and values. Please refer https://tools.ietf.org/html/rfc7643#section-2.4 for further information.

**Comment by bala-striva** [comment]
@emswbandara for issue 1: thank you we missed that

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
