### ISSUE TITLE
Not possible to configure the realm cache timeout

### ISSUE THREAD

**Issue by imedyaosandi** [wso2/product-is#7316]
**Description:**
Version 5.7.0

Issue: 
When a tenant user (in secondary user store) is loaded it is creating a set of db connections and when the same tenant is unloaded these connections are not getting closed, therefore the connections are getting accumulated with the time. 

Reason: 
These connections are getting idle after cache timeout time configured in carbon.xml.Therefore creating a new set of connections when the tenant is loaded again.

**Suggested Labels:**
type/bug

**Steps to reproduce:**
1. Create a tenant and create a secondary user store there. Create user x inside that.
2. Restart the server to unload the tenant.
3. Try login to the tenant using x user. 
4. Unload and load tenant user several times, You will see the number of db connections getting increased.

**Fix:**
Having different configuration for realm cache timeout other than default cache timeout, and configuring this realm cache timeout time to a higher time period will solve the increase in idle connections.
https://github.com/wso2-support/carbon4-kernel/pull/847

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
