### ISSUE TITLE
[SCIM] Value of 'location' HTTP header is incorrect in tenant mode

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#7317]
### Description

I noticed the above mentioned issue while creating a user via SCIM where the 'location' HTTP header does not include the tenant domain in the URL. However the value of the 'location' meta attribute is correct. Both the 'location' meta attribute and the 'location' HTTP header should have the same value. See the example below.

**_'location' meta attribute:_** 

> https://<span></span>localhost:9853/t/wso2.com/scim2/Users/ecea2770-fa2b-48a3-b33f-c43ae36e1aad

**_'location' HTTP header:_** 

> https://<span></span>localhost:9853/scim2/Users/ecea2770-fa2b-48a3-b33f-c43ae36e1aad

### Steps to Reproduce

1. Create a tenant (e.g. wso2.com).
2. Create a user with SCIM.
3. Compare the values of the 'location' meta attribute and the 'location' HTTP header.

### Post Actions

- Enable the test[1] after fixing this issue.

### Affected Versions

- 5.9

[1] https://github.com/wso2/product-is/blob/6593b883b0f5c0531c6c84f275a345cf91e419b2/modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/scim2/rest/api/SCIMUtils.java#L80

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
