### ISSUE TITLE
Migration (Oracle) errors out at 5.5.0 step due to ORA-02270

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#7318]
**Description**
Migration client (Oracle) errors out at 5.5.0 step giving the below stack trace.
```
TID: [-1234] [] [2020-01-18 06:56:45,877] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.4.0 to 5.5.0
TID: [-1234] [] [2020-01-18 06:56:45,964] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.5.0, Migration Step : SchemaMigrator of order : 1 is starting........................... 
TID: [-1234] [] [2020-01-18 06:56:45,965] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -  WSO2 Product Migration Service Task : Executing Identity Migration Scripts.
TID: [-1234] [] [2020-01-18 06:56:46,316] [] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} - Error occurred while executing SQL script for migrating database java.lang.Exception: Error occurred while executing :   CREATE TABLE IDN_OIDC_REQ_OBJECT_REFERENCE ( ID INTEGER, CONSUMER_KEY_ID INTEGER , CODE_ID VARCHAR(255) , TOKEN_ID VARCHAR(255) , SESSION_DATA_KEY VARCHAR(255), PRIMARY KEY (ID), FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE, FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE, FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE) 
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:260)
...
Caused by: java.sql.SQLSyntaxErrorException: ORA-02270: no matching unique or primary key for this column-list
...
Caused by: Error : 2270, Position : 325, Sql = CREATE TABLE IDN_OIDC_REQ_OBJECT_REFERENCE ( ID INTEGER, CONSUMER_KEY_ID INTEGER , CODE_ID VARCHAR(255) , TOKEN_ID VARCHAR(255) , SESSION_DATA_KEY VARCHAR(255), PRIMARY KEY (ID), FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE, FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE, FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE) , OriginalSql =   CREATE TABLE IDN_OIDC_REQ_OBJECT_REFERENCE ( ID INTEGER, CONSUMER_KEY_ID INTEGER , CODE_ID VARCHAR(255) , TOKEN_ID VARCHAR(255) , SESSION_DATA_KEY VARCHAR(255), PRIMARY KEY (ID), FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE, FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE, FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE) , Error Msg = ORA-02270: no matching unique or primary key for this column-list
```
This is when we migrate from 5.0.0 SP1 to 5.9.0.

**Reason**
This is because the FOREIGN KEY refernces mentioned here are neither UNIQUE nor PRIMARY in their respective tables.
Oracle : [does not allow non-unique foreign key references](https://dba.stackexchange.com/questions/130659/ora-02270-no-matching-unique-or-primary-key-for-this-column-list)
MYSQL : Allows non unique foreign jey refernces. This is why the migration doesn't break in Mysql.

**Reproducing steps**
1. Run -Dsetup aganst a 5.0.0 Oracle pack.
2. Run the migration client against that DB.
3. Or else simply try the below query of migration client against that database.
`CREATE TABLE IDN_OIDC_REQ_OBJECT_REFERENCE ( ID INTEGER, CONSUMER_KEY_ID INTEGER , CODE_ID VARCHAR(255) , TOKEN_ID VARCHAR(255) , SESSION_DATA_KEY VARCHAR(255), PRIMARY KEY (ID), FOREIGN KEY (CONSUMER_KEY_ID) REFERENCES IDN_OAUTH_CONSUMER_APPS(ID) ON DELETE CASCADE, FOREIGN KEY (TOKEN_ID) REFERENCES IDN_OAUTH2_ACCESS_TOKEN(TOKEN_ID) ON DELETE CASCADE, FOREIGN KEY (CODE_ID) REFERENCES IDN_OAUTH2_AUTHORIZATION_CODE(CODE_ID) ON DELETE CASCADE)`

**Fix**
We don't have these referenced columns in the default 5.0.0 pack. These were being added during the migration from the client it self.
Query which fails
`CREATE TABLE idn_oidc_req_object_reference 
  ( 
     id               INTEGER, 
     consumer_key_id  INTEGER, 
     code_id          VARCHAR(255), 
     token_id         VARCHAR(255), 
     session_data_key VARCHAR(255), 
     PRIMARY KEY (id), 
     FOREIGN KEY (consumer_key_id) REFERENCES idn_oauth_consumer_apps(id) ON 
     DELETE CASCADE, 
     FOREIGN KEY (token_id) REFERENCES idn_oauth2_access_token(token_id) ON 
     DELETE CASCADE, 
     FOREIGN KEY (code_id) REFERENCES idn_oauth2_authorization_code(code_id) ON 
     DELETE CASCADE 
  ) `
Places where we alter the respective tables to add these columns. (From the migration client)
`5.1.0/dbscripts/step1/identity/oracle.sql:ALTER TABLE IDN_OAUTH2_AUTHORIZATION_CODE ADD CODE_ID VARCHAR (255)`
`5.1.0/dbscripts/step1/identity/oracle.sql:ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN ADD TOKEN_ID VARCHAR (255)`
``
Fix 
Let's define the newly added columns UNIQUE in the alter script itself.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
