### ISSUE TITLE
Error while manually executing -MSSQL DB script 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7319]
Affected IS version: wso2is-5.10.0-alpha3-SNAPSHOT
DB script location: /wso2is-5.10.0-alpha3-SNAPSHOT/dbscripts/mssql.sql
MSSQL version: Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)

Error log:
Msg 1776, Level 16, State 0, Line 9223372036854775807
There are no primary or candidate keys in the referenced table 'UM_DOMAIN' that match the referencing column list in the foreign key 'FK__UM_UUID_D__UM_DO__55F4C372'.
Msg 1750, Level 16, State 1, Line 9223372036854775807
Could not create constraint or index.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
