### ISSUE TITLE
Upgrade 3rd party dependencies

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#7324]
Need to upgrade the following third party dependencies to the latest

Apache groovy 2.4.7 (tracked with https://github.com/wso2/product-is/issues/9369)
org.apache.geronimo.specs.geronimo-jpa_2.0_spec_1.1.0
geronimo-saaj_1.3_spec_1.0.1.wso2v2
geronimo-spec-jms_1.1.0.rc4-wso2v1

**Comment by emswbandara** [comment]
Need to track following upgrades as well.

sanselan-0.97-incubator.jar ---> commons-imaging-1.0-alpha1 or newer
xercesImpl-2.11.0.jar ----> 2.12.0 or newer
handlebars-v4.0.11.js ----> 4.3.0 or newer

**Comment by emswbandara** [comment]
Remove xalan:serializer dependency from the following webapps since JDK ships this by default.

emailotpauthenticationendpoint.war
smsotpauthenticationendpoint.war

**Comment by dewniMW** [comment]
> Need to track following upgrades as well.
> 
> sanselan-0.97-incubator.jar ---> commons-imaging-1.0-alpha1 or newer

In 5.11.0-m34, sanselan jar is not found. Hence an upgrade is not required.

**Comment by senthalan** [comment]
Apache poi needs to be updated to 3.17.0.wso2v1. The product has this version (added with [this](https://github.com/wso2/carbon-kernel/pull/1708)), so better to use the same version  [here](https://github.com/wso2/carbon-identity-framework/blob/v5.17.5/pom.xml#L2007)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
