### ISSUE TITLE
UserStoreConfigAdminService:addUserStore method Disabled parameter under userStoreDTO is not affected.

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7325]
In the UserStoreConfigAdminService when adding or updating UserStoreConfig Disabled parameter (which we used to enable or disable the user store) under userStoreDTO is not affected.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://dto.configuration.store.user.identity.carbon.wso2.org/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:addUserStore>
         <!--Optional:-->
         <xsd:userStoreDTO>
            <!--Optional:-->  <xsd1:className>org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager</xsd1:className> <!--Optional:-->
            <xsd1:description>?</xsd1:description>
            <!--Optional:-->
            <xsd1:disabled>false</xsd1:disabled>
         ----
         </xsd:userStoreDTO>
      </xsd:addUserStore>
   </soapenv:Body>
</soapenv:Envelope>
```

In order to enable/disable the configured user store, we need to send the Disabled parameter as a property inside the properties element of the request.

  ```
</xsd1:properties>
              <xsd1:properties>
               <!--Optional:-->
               <xsd1:name>Disabled</xsd1:name>
               <!--Optional:-->
               <xsd1:value>false</xsd1:value>
</xsd1:properties>
```

Since we have a property Disabled parameter under userStoreDTO  to enable/disable user store, we need to fix the product to read that Disabled parameter under userStoreDTO  to enable/disable user store.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
