### ISSUE TITLE
Introduce two separate configuration to manage OIDC consent flow

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#7327]
With https://github.com/wso2/product-is/issues/7256 separate configurations introduced to manage the consent during OIDC login and logout flow.

```
[oauth]
prompt_login_consent = false
prompt_logout_consent = false
```

If these properties are not defined the value of the  oauth.prompt_consent will be applied to them.

This needs to be documented and pointed in the migration doc

**Comment by Abilashini** [comment]
documented at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/#introducing-two-separate-configuration-to-manage-oidc-consent-flow
