### ISSUE TITLE
XACML "Deny-unless-permit" returns Not Applicable

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/product-is#7328]
According to http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html section "C.6 Deny-unless-permit", an “Indeterminate” or “NotApplicable” must never be the result.

However, in WSO2 IAM 5.9.0, "NotApplicable" can be returned when the "Deny-unless-permit" combining algorithm is used.

Such cases should always return "deny"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
