### ISSUE TITLE
Duplicated email field when getting user information SCIM2

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7329]
When using email as the username, the following behavior occurs in WSO2 IS 5.8.0.
BEFORE THE WUM (1567933846116)
"emails": [

{ "type": "work", "value": "user@mail.com" }
]

AFTER THE WUM (1575729125487)
"emails": [
{ "type": "work", "value": "user@mail.com" }
,
"user@mail.com"
]

The claim attributes are as follows.
http://wso2.org/claims/username: mail
http://wso2.org/claims/emailaddress: mail

Request payload:
{
	"schemas": [],
	"name": {
		"familyName": "John",
		"givenName": "Alex"
	},
	"userName": "ext1@mail.com",
	"password": "password",
	"emails": [{
			"primary": true,
			"value": "ext1@mail.com",
			"type": "work"
		}
	]
}

Response payload:
{
  "emails": [
    {
      "type": "work",
      "value": "ext1@mail.com"
    },
    **"ext1@mail.com"**
  ],
  "meta": {
    "created": "2020-01-21T08:47:14.666Z",
    "location": "https://localhost:9443/scim2/Users/a6e89e23-7d22-44fe-a7cb-eb7ccea4fda1",
    "lastModified": "2020-01-21T08:47:14.666Z",
    "resourceType": "User"
  },
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User",
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
  ],
  "roles": [
    {
      "type": "default",
      "value": "Internal/everyone"
    }
  ],
  "name": {
    "givenName": "John",
    "familyName": "Alex"
  },
  "id": "a6e89e23-7d22-44fe-a7cb-eb7ccea4fda1",
  "userName": "ext1@mail.com"
}

In order to get the response as previously, we need to provide a flag or configuration to switch to the old behavior.

**Comment by madurangasiriwardena** [comment]
The issue seems to be with backward compatibility. Since the current behavior is spec-compliant, we will not be changing the current behavior.
