### ISSUE TITLE
Auditing Provisioning

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7335]
In a typical deployment with provisioning configured to one or more target systems, there is no way for the help desk to troubleshoot provisioning related issues. I have checked the audit log there is no useful information available there to create dashboards for help desk.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
