### ISSUE TITLE
It is better to support weak key for sign/encry for backward compatibility 

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#7340]
New nimbus implementation is checking for weak keys as the default behavior.
WSO2IS uses same behavior which may create errors, if weak key is used.
Therefore it is better to have a configuration to decide whether weak keys are used or not.

[1] https://bitbucket.org/connect2id/nimbus-jose-jwt/src/210685bd7f95fc293a010c6dfb4bb6c30ed0ea12/src/main/java/com/nimbusds/jose/crypto/RSASSASigner.java#lines-111

**Comment by mefarazath** [comment]
By adding the 'allow_weak_rsa_signer_key' system flag, the weak keys (key length less than 2048) can be used for the signing.
