### ISSUE TITLE
IS-5.7 authentication EP's UI fields validation lacks emtpy input validations.

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#7344]
IS : 5.7.0
WUM : 1578666737897

Issue : 
Authentication endpoint's login window's UI input validation fails as below.
1. User name enter, Password not enter: validation working
2. Username not enter, Password enter: validation not working
3. Username not enter, Password does not enter: validation not working.

Expected : 
Should check for empty inputs from the UI level rather than doing an authentication attempt.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
