### ISSUE TITLE
Scope Management  Related Migration changes

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#7347]
There are two types of scopes in IS, OAuth2 binding scopes and OIDC scope binding. 
OAuth2 Scope Binding related data persist in two tables such as in IDN_OAUTH2_SCOPE, IDN_OAUTH2_SCOPE_BINDING.
OIDC Scopes related data persist against IDN_OIDC_SCOPE and IDN_OIDC_SCOPE_CLAIM_MAPPING tables. 

From IS 5.10 onwards we decided to maintain one single Scope table under "IDN_OAUTH2_SCOPE"  for both use-cases. Hence we need to do the data migration. 

- For the existing scopes in IDN_OAUTH2_SCOPE table, we need to include SCOPE_TYPE as "OAUTH2".
- Migrate the data from IDN_OIDC_SCOPE table to IDN_OAUTH2_SCOPE table by providing SCOPE_TYPE as "OIDC" also providing DISPLAY_NAME as the scope name which coming from IDN_OIDC_SCOPE table.

Apart from that, from  wso2/product-is#6777, we introduced the "BINDING_TYPE" in the IDN_OAUTH2_SCOPE_BINDING table. Here also we require data migration. 

- For the existing binding in IDN_OAUTH2_SCOPE_BINDING table, we need to include BINDING_TYPE as "DEFAULT".

**Comment by Abilashini** [comment]
Done with https://github.com/wso2-extensions/identity-migration-resources/pull/39
