### ISSUE TITLE
Add fine grained permissions for UserAdmin admin service

### ISSUE THREAD

**Issue by Manukam** [wso2/product-is#7349]
In order to search for users with a claim [1], it uses UserAdmin admin service. For this service, it requires User management permissions, which included, creating, updating and deleting permissions as well. There can requirements where a user should only be allowed to search for users but not delete, create or update.

Steps to reproduce - 
- Create a role with only 'list', 'view' of User management permissions and 'login' permissions.
- Assign a user to the role
- Invoke the 'ListUserByClaim' method of UserAdmin admin service with the assigned user.
- Returns an Access Denied error.

If the role is assigned with all the User Management permissions, the 'ListUserByClaim' method works.

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/UserAdmin.java#L580

**Comment by madurangasiriwardena** [comment]
To achieve this use case you can use the `getUserList` method of `RemoteUserStoreManagerService` admin service, which has the proper permissions set.

**Comment by Manukam** [comment]
The requirement here was to search for users with a claim via the management console. Missed to mention that.
