### ISSUE TITLE
Verify QSG samples with IS-5.10.0

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#7351]
Verify QSG samples with IS-5.10.0

**Comment by ashendes** [comment]
Working on this.

**Comment by ashendes** [comment]
When following scenario 1, after logging into an app with the given credentials, the server returns a HTTP 500 response.

**Comment by ashendes** [comment]
The [doc](https://is.docs.wso2.com/en/next/get-started/quick-start-guide/#before-you-begin) does not mention where to find the sample webapps or how to deploy them on tomcat.

**Comment by ashendes** [comment]
[[Doc](https://is.docs.wso2.com/en/next/get-started/quick-start-guide/#multi-factor-authentication)] The formatting of the toml config in the Multi Factor Authentication section is flawed.

**Comment by ashendes** [comment]
In the 3rd scenario (Multi factor Authentication), after logging in via the user portal, returns a 401 with server log, 
`INFO {org.wso2.carbon.identity.sample.extension.auth.AbstractSampleAuthenticator} - Sample Authenticator: "Demo HardwareKey Authenticator" called`

Also, no service providers have been created in the server.

**Comment by ashendes** [comment]
In scenario 4, link given to register OAuth2.0 application in Google does not work.
After logging into an app with the given credentials, the tomcat server returns a HTTP 500 response (error in saml2 webapp).

**Comment by ashendes** [comment]
The instructions given in the terminal are outdated in terms of links and buttons (UI elements) referring to the user portal.

**Comment by ashendes** [comment]
> ).
Issue fixed when keystore of new IS pack was copied to the webapps in tomcat.
