### ISSUE TITLE
OIDC SSO flow does not support for signed/encrypted 'userinfo' response (JWT)

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-is#7354]
**Description :** 
When implementing an SSO scenario using the OIDC protocol with the WSO2-IS with a 3rd party IDP which responded for the 'userinfo' endpoint as a JWT value, the flow breaks with the below error.

> TID: [-1234] [] [2020-01-17 07:04:33,830] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework 
> java.lang.IllegalArgumentException: String 'eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJHVUNVUFlYR1EyTENJUldTQ0czWFRDRklJM0RQU0tJMiIsImF1ZCI6InVybi5jYS5jYW5hZGEuZXNkYy5tc2NhLndzbzJkZXYiLCJiaXJ0aGRhdGUiOiIxOTk4LTA1LTAyIiwiaXNzIjoiaHR0cHM6XC9cL2lkdGVzdC5nb3YuYmMuY2FcL29hdXRoMlwvIiwiaWRlbnRpdHlfYXNzdXJhbmNlX2xldmVsIjozLCJnaXZlbl9uYW1lIjoiRVNEQ1RFU1QiLCJmYW1pbHlfbmFtZSI6IlRIUkVFIiwiaWF0IjoxNTc5MjYyNjY3LCJqdGkiOiJhYWRlY2MzZi1jN2UzLTQ5YzUtOTE2Yy05MGM0ODM5YWY5NGYifQ.dfZqzRqhI5fxd_sxhodVzao_NLMBkNGX0Q5sl2LOpXtvKQOQ9Xv-gAhcw0RA6kUCcTEpHzVV8UpsXJ4KxiGIxT2pVwcMy0tVE-FUYa6qbnAl0W9z0hIBi7PhrOxs9O-L-XY-1CPxEzH2DzzIbC7xZYm59iA_qCyP8kX3cAXgpdQlzy-rQtORQNpEHr5N0w77hiQaGTy7PzMieefnYXXDdvRkECk7i1pPqNqrIYlZFe3e4mHk7wkRpoL24TIGlYcb4VxtJ6nGskC9-GQEuUnE4ICHqIKizR93Pc1tJtuHVyF3LjniQAX8vWlrhuiI5cj_hJpWhGYHwXVpWqEJwH_zVg
> ' is not a valid JSON object representation, a JSON object text must begin with '{'
> 	at org.apache.oltu.oauth2.common.utils.JSONUtils.parseJSON(JSONUtils.java:62)
> 	at org.wso2.carbon.identity.application.authenticator.oidc.OpenIDConnectAuthenticator.getSubjectAttributes(OpenIDConnectAuthenticator.java:228)

**Steps to reproduce:** 
* We can add WSO2-IS as IDP for an SSO scenario to reproduce this issue by changing the below configuration to provide a signed/encrypted(JWT) 'userinfo' response.
`<UserInfoEndpointResponseBuilder>org.wso2.carbon.identity.oauth.endpoint.user.impl.UserInfoJWTResponse</UserInfoEndpointResponseBuilder>`

**Affected repository :** https://github.com/wso2-extensions/identity-outbound-auth-oidc

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
