### ISSUE TITLE
Trying to use UserStore REST API return 404

### ISSUE THREAD

**Issue by bala-striva** [wso2/product-is#7358]
WSO 2 IS: 5.9

According the docs (https://is.docs.wso2.com/en/5.9.0/develop/userstore-rest-api/#!)
I tried to query the available user stores but the IS returns "404 No service was found." error.

It's the same with or without providing a tenant
```
➜ https --verify no -a admin:admin :9443/api/server/v1/userstores
HTTP/1.1 404 
Content-Length: 47
Content-Type: text/html;charset=ISO-8859-1
Date: Thu, 23 Jan 2020 13:34:05 GMT
Server: WSO2 Carbon Server

<html><body>No service was found.</body></html>
```

Do I need to configure something to enable this functionality?

**Comment by mefarazath** [comment]
As far as I know the user store rest API was not shipped with IS 5.9.0

It is planned for IS 5.10.0

@Kanapriya can you confirm?

**Comment by Kanapriya** [comment]
Yes, this not shipped with WSO2 IS 5.9.0. This will be available in 5.10.0

**Comment by Kanapriya** [comment]
Seems the doc should be removed from the 5.9.0 docs space, @bala-striva we will remove the docs [1] from 5.9.0 docs space. Thanks for pointing this out.

[1] (https://is.docs.wso2.com/en/5.9.0/develop/userstore-rest-api/#!)

**Comment by bala-striva** [comment]
Thank you, we will try it out with 5.10 if it's will be released.
