### ISSUE TITLE
Invalid response code for unsupported filter option in SCIM 2 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7367]
Currently SCIM2 in wso2is support only  below operation types. 
(EQ ’, ' EW' , ‘ CO ’, ‘ SW ’, and ‘ AND ’.) 

Therefore the HTTP response codes should be,
For the invalid filter operation 400 (Bad request) and
For the unsupported filter operations (ne/lt) 405  or 406.

But for above both scenarios its get 400 response which is wrong for the unsupported operations.

Request: (Unsupported filter -lt)
`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?startIndex=1&count=5&domain=PRIMARY&filter=userName+sw+and+name.familyName+co+Test+lt+tt&attributes=userName,name.familyName`

Response:

{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"InvalidFilter","detail":"Given filter operator is not supported.","status":"400"}

Request: (Invalid filter-AA) 
`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?startIndex=1&count=5&domain=PRIMARY&filter=userName+AA+and+name.familyName+co+Test+lt+tt&attributes=userName,name.familyName`

Response: 
`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"InvalidFilter","detail":"Given filter operator is not supported.","status":"400"}`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
