### ISSUE TITLE
DCR code not compatible with swagger .yaml file

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#7369]
Description:
org.wso2.carbon.identity.oauth2.dcr.endpoint code is not compatible with api.identity.oauth.dcr.endpoint.yaml.

Swagger generate breaks the code in some places.

Moving from https://github.com/wso2-extensions/identity-inbound-auth-oauth/issues/1299

**Comment by mefarazath** [comment]
Reported by @Krishanx92

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
