### ISSUE TITLE
[Doc] the documentation need to update with the latest Kerberos jar file 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7371]
The documentation [1] does not include the latest Kerberos jar file with the fixes.
Need to update the doc with the latest jr file with fixes available in [2].

[1] https://is.docs.wso2.com/en/next/learn/kerberos-grant/
[2] https://github.com/wso2-extensions/identity-oauth2-grant-kerberos

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
