### ISSUE TITLE
Profile URL attribute is not returned in the user list - SCIM 2.0

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#7372]
In the current implementation, the profile URL of the user is not returned when we fetch the user list by sending a GET request to the https://localhost:9443/scim2/Users endpoint. Since we are hoping to display the user's image in the user listing of the new admin portal, we need to get the URL of the profile image. Therefore it will be better if we can include the profile URL attribute in the response.

**Comment by sarubi** [comment]
We can get the desired claims using the requested attributes parameter in the SCIM when retrieving the resources. 
example: 
https://localhost:9443/scim2/Users?attributes=userName,name.givenName,profileUrl
Hope you know what the attributes you required to return so you can specify those and retrieve it.
Let me know whether this works for you.

**Comment by NipuniBhagya** [comment]
Yes I tried this but we can only filter the response with already existing attributes. So it didn't work on profileUrl.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
