### ISSUE TITLE
Support for Trust Model based SAML Signature Validation

### ISSUE THREAD

**Issue by Seralahthan** [wso2/product-is#7374]
According to the current implementation of the Identity Server, in order to support the SAML signature validation (response signed from Federated Identity Provider), we need to upload the Federated Identity Provider's Public Certificate to the Identity Server. 

Instead of uploading the Public Certificate (of the Identity Provider) to the Identity Server, some vendors support a **_"Trust-based mechanism to trust the Public Certificate sent along with the SAML response (instead of uploading beforehand)"._**

Here is how the Trust-based SAML signature validation works, 

- Federated Identity Provided signs the SAML response and includes the Public Certificate in the Response itself.
- Identity Server trusts the Public Certificate based on the Subject's Issuer DN and ensures the issuer's CA is also trusted (Public Certificate is not uploaded to Identity Server).
- Identity Server validates the Public Certificate received in the response and uses it to verify the signature.

It would be great if we can incorporate this into the future roadmap of Identity Server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
