### ISSUE TITLE
Scenario Tests of IS-5.7.0 with Oracle are disabled

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#7375]
This PR  https://github.com/wso2/testgrid-job-configs/pull/417 disables the scenario tests of IS 5.7.0 with Oracle-SE2-12.1 due to some infrastructure issues. This should be reverted once those issues are resolved.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
