### ISSUE TITLE
Supporting secret management service from cloud vendors

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7376]
Currently, secret management is done through the WSO2 securevault in the identity server. Nowadays, almost all of the cloud vendors are having secret management service[1][2][3]. Identity server should support storing secrets(such as DB password, LDAP password, Keystore password ..etc) in the cloud secret managers.

[1] https://aws.amazon.com/secrets-manager/
[2] https://azure.microsoft.com/en-us/services/key-vault/
[3] https://cloud.google.com/blog/products/identity-security/introducing-google-clouds-secret-manager

**Comment by AmshikaH** [comment]
An extension has been developed to use Azure Key Vault as an external secret repository with Carbon Secure Vault.

**Comment by Lakshan-Banneheke** [comment]
An extension to support AWS Secrets Manager as an external secret repository in Carbon Secure Vault has been developed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
