### ISSUE TITLE
Supporting ACME for Cert management

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7377]
Automatic Certificate Management Environment (ACME) is now an [IETF RFC](https://tools.ietf.org/html/rfc8555) and it is supported by lets-encrypt. It would give the ability to manage certificates without maintenance overhead.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
