### ISSUE TITLE
Invalid displayName when list group SCIM2

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7389]
Some of the group displayNames are incorrect in SCIM2 

User store: read_only_ldap_unique_id

Steps:
To Create and configure unique Id read only ldap (Step 01 to 04)

01.  Download and unzip two wso2is servers.
02. Change one wso2is server offset to one and start the server (server 1)
03. Add roles and users in server 1
04. For the other server add unique id read  only ldap configuration.  (server 2)

Deployment.toml  configuration for user store
```
[user_store]
type = "read_only_ldap_unique_id"
connection_url = "ldap://localhost:10390"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"

[user_store.properties]
CaseInsensitiveUsername = false
SCIMEnabled=true
IsBulkImportSupported=false
EnableMaxUserLimitForSCIM=true
```
Here we user the server 1,  read and write unique id ldap as server2 read only unique id ldap.

05. Start server 2 with the unique id read only ldap user store. 
(User and role created in server1 should display in server2, user store as well. But they are read only)

Server 2

![image](https://user-images.githubusercontent.com/39077751/73159964-c729b100-410d-11ea-865d-ebeea860dea2.png)

06.  Get group from SCIM2 
Request:

`curl -v -k --user admin:admin https://localhost:9443/scim2/Groups/?attributes=displayName`

Response:

`{"totalResults":5,"startIndex":1,"itemsPerPage":5,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"role1","id":"84612342-c35f-44ba-b4a2-d547e7d6b9be"},{"displayName":"Application/User Portal","id":"34f3ece4-4390-4ce5-b5e6-f71ddba5ed44"},{"displayName":"role2","id":"b227cc5e-38cc-457b-8303-a0c5bea82f4f"},{"displayName":"Internal/system","id":"2dc6007c-b2ee-4563-a991-278aac185050"},{"displayName":"admin","id":"3db930e7-5657-46ff-916b-d275c3635088"}]}`

Some displayNames are valid . But below groups dispayNames are missing from the response,
Internal/everyone
testrole (Read-Only) .

And also there are two invalid displayNames. role1 and role2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
