### ISSUE TITLE
WSO2IS is firing very ineffective queries to clear session records from IDN_AUTH_TEMP_SESSION_STORE and IDN_AUTH_SESSION_STORE

### ISSUE THREAD

**Issue by hari819** [wso2/product-is#7392]
Hello , 

Recently we upgraded to 5.9.0 from 5.7.0 version of wso2IS . We are seeing long running and ineffective queries being run by wos2 to clear session records from both tables , IDN_AUTH_TEMP_SESSION_STORE and IDN_AUTH_TEMP_SESSION_STORE.

It looks like nothing is getting deleted from the tables in the end ,
1. DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < :1 AND ROWNUM <= 8192);

2. DELETE FROM IDN_AUTH_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_SESSION_STORE WHERE EXPIRY_TIME < :1 AND ROWNUM <= 8192);

3. DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < :1 AND ROWNUM <= 8192;

i am attaching the explain plans for the queries as well.

![image](https://user-images.githubusercontent.com/12997071/73162980-fc85cd00-4114-11ea-8a5c-704d97670062.png)

![image](https://user-images.githubusercontent.com/12997071/73162990-05769e80-4115-11ea-97a0-779055c43d40.png)

![image](https://user-images.githubusercontent.com/12997071/73164972-f72a8180-4118-11ea-85bc-a28106d44d5d.png)

![image](https://user-images.githubusercontent.com/12997071/73164987-fe518f80-4118-11ea-98a4-75ce88e5c55e.png)

![image](https://user-images.githubusercontent.com/12997071/73165056-188b6d80-4119-11ea-87ec-bc008c64f91a.png)

could you please help us solving this .?

**Comment by madurangasiriwardena** [comment]
@hari819, can you try adding indexes to `EXPIRY_TIME` in `IDN_AUTH_SESSION_STORE` and `IDN_AUTH_TEMP_SESSION_STORE` and see if there is any performance improvement?

**Comment by hari819** [comment]
@madurangasiriwardena , the index is not helping at all . The tables are growing larger and larger .

one more cursors error we see , 
ERROR {org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore} - Error while removing session data from the database for nano time 1579841951299813791 java.sql.SQLException: ORA-01000: maximum open cursors exceeded

Since the delete commands are failing , the negative impact of the DELETE commands is becoming greater and greater every day. The huge DB activity is related to the UNDO segments which are most likely chaining the changed database blocks.

The issue affects everything connected / trying to connect to this DB since the database is almost unusable during the period when these DELETE commands are running.

Is it possible to delete old records from the affected tables by hand? . Could you please provide us a workaround so that we can delete the old rows from the tables manually . We would like to know if there are other WSO2 actions related to the deletion of each row which prevent us from the manual deletion. 

This has become a critical issue for us now , could you please provide us a workaround on this issue ?

**Comment by JKAUSHALYA** [comment]
@hari819 You can use the session data cleanup script [1] to clean the session data table manually and using [2] you can disable the internal session data cleanup job. You can schedule the external script to run in a timely manner using a CRON job or a similar mechanism. 

[1] https://github.com/wso2/carbon-identity-framework/blob/v5.14.97/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/oracle-11.x/oracle-sessiondata-cleanup.sql

[2] https://is.docs.wso2.com/en/latest/learn/authentication-session-persistence/

**Comment by JKAUSHALYA** [comment]
@hari819 Meanwhile, can you check whether you have session data that are older than 14 days? By default, the internal job will clean only data older than 14 days. However, you can change that value as well as using `expire_session_data_after` property. [2]

[2] https://is.docs.wso2.com/en/latest/learn/authentication-session-persistence/

**Comment by hari819** [comment]
@JKAUSHALYA   ,yes it looks like records older than 14 days are deleted .  
Thanks , i will check the link and see how we can use the property "expire_session_data_after".

**Comment by hari819** [comment]
@JKAUSHALYA  , will the cleanup script handle both the tables we are facing issue with IDN_AUTH_SESSION_STORE and IDN_AUTH_TEMP_SESSION_STORE ?

**Comment by hari819** [comment]
@JKAUSHALYA @madurangasiriwardena ,

i have disabled the  internal session data cleanup job by setting false in identity.xml , <SessionDataCleanUp>
                <Enable>false</Enable>

But still the job is running and failing with the cursors error ,
Caused by: Error : 1000, Position : 0, Sql = DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < :1  AND ROWNUM <= 8192), OriginalSql = DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < ? AND ROWNUM <= 8192), Error Msg = ORA-01000: maximum open cursors exceeded

**Comment by hari819** [comment]
@JKAUSHALYA  , this is related to my previous question 8 days back , the cleanup script is handling the table IDN_AUTH_SESSION_STORE and it is not handling the second table IDN_AUTH_TEMP_SESSION_STORE.

I can disable the internal job for this also , but who will clean the data from the table  IDN_AUTH_TEMP_SESSION_STORE, do we have a cleanup script for this table ?

`<SessionDataCleanUp>
                <Enable>false</Enable>
                <CleanUpTimeout>20160</CleanUpTimeout>
                <CleanUpPeriod>1440</CleanUpPeriod>
                <DeleteChunkSize>8192</DeleteChunkSize>
            </SessionDataCleanUp>
            <OperationDataCleanUp>
                <Enable>true</Enable>
            </OperationDataCleanUp>
            **<TempDataCleanup>
                <Enable>false</Enable>**`

**Comment by hari819** [comment]
@JKAUSHALYA 

i see some code inside https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java

which might need some improvement,

`private void removeExpiredSessionData(String sqlQuery) {

        Connection connection = null;
        PreparedStatement statement = null;

        try {
            connection = IdentityDatabaseUtil.getDBConnection();
        } catch (IdentityRuntimeException e) {
            log.error(e.getMessage(), e);
            return;
        }

        if (log.isDebugEnabled()) {
            log.debug("DB query for removing expired data: " + sqlQuery);
        }

        long currentTime = FrameworkUtils.getCurrentStandardNano();
        try {
            boolean deleteCompleted = false;
            int totalDeletedEntries = 0;
            while (!deleteCompleted) {
                statement = connection.prepareStatement(sqlQuery);
                statement.setLong(1, currentTime);

                int noOfDeletedRecords = statement.executeUpdate();
                deleteCompleted = noOfDeletedRecords < deleteChunkSize;
                totalDeletedEntries += noOfDeletedRecords;
                if (log.isDebugEnabled()) {
                    log.debug(String.format("Removed %d expired session records.",
                            noOfDeletedRecords));
                }
                IdentityDatabaseUtil.rollbackTransaction(connection);
            }
            if (log.isDebugEnabled()) {
                log.debug(String.format("Deleted total of %d entries ", totalDeletedEntries));
            }
        } catch (SQLException e) {
            IdentityDatabaseUtil.rollbackTransaction(connection);
            log.error("Error while removing session data from the database for nano time " + currentTime, e);
        } finally {
            IdentityDatabaseUtil.closeAllConnections(connection, null, statement);
        }
    }`

i am not sure what is the use of the first "IdentityDatabaseUtil.rollbackTransaction(connection);" inside the while loop .

Even after increasing the open_cursors to 1000 , still we face the same issue ,
Caused by: Error : 1000, Position : 0, Sql = DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < :1 AND ROWNUM <= 8192), OriginalSql = DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < ? AND ROWNUM <= 8192), Error Msg = ORA-01000: maximum open cursors exceeded

I think the problem with while loop is it is not closing the individual prepared statements , so suggestion is replace the `"IdentityDatabaseUtil.closeAllConnections(connection, null, statement);"` inside while loop with `"IdentityDatabaseUtil.closeAllConnections(connection, null, statement);"` . This should make sure that each statement is closed after execution ,

Please respond as this has become critical for us .

Thanks,

**Comment by hari819** [comment]
@JKAUSHALYA ,

we can simply move the code `statement = connection.prepareStatement(sqlQuery);` out of the while loop which will solve the statements not getting closed .

Let us know if we make some changes in this class `SessionDataStore.java` , how can we bundle it again into the wso2IS.we will test it on our side and let you guys know.

Thanks,

**Comment by hari819** [comment]
@JKAUSHALYA @madurangasiriwardena ,

can we disable the persistence of temp data into this table "IDN_AUTH_TEMP_SESSION_STORE"  by having "false", .

Is it recommended and if so what are the side effects of disabling ?

`<SessionDataPersist>
    <Enable>true</Enable>
    **<Temporary>false</Temporary>**`

**Comment by hari819** [comment]
@JKAUSHALYA  @madurangasiriwardena 

i have disabled the internal job for temp data cleanup by having false in identity.xml as ,

`<TempDataCleanup> <Enable>false</Enable>` ,

and this is not working as expected and as per documentation , the job ran again to cause another oracle cursor error ,
Caused by: Error : 1000, Position : 0, Sql = DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < :1 AND ROWNUM <= 8192), OriginalSql = DELETE FROM IDN_AUTH_TEMP_SESSION_STORE WHERE ROWID IN (SELECT ROWID FROM IDN_AUTH_TEMP_SESSION_STORE WHERE EXPIRY_TIME < ? AND ROWNUM <= 8192), Error Msg = ORA-01000: maximum open cursors exceeded 

is the temp data cleanup job supposed to run even after setting false as mentioned above?

**Comment by tharindu-bandara** [comment]
@hari819 
Please accept our sincere apologies for the late reply.  Thanks for the investigation and suggestion on the [codebase](https://github.com/wso2/product-is/issues/7392#issuecomment-582464444). I will go through this and will check on a possible fix.

**Comment by tharindu-bandara** [comment]
Hi @hari819,

As you have mentioned, we too found several issues(delete query not getting committed, a prepared statement is not properly closed) in the codebase regarding this, where all of them together, can lead to the issue that you are facing. 

And also, you may not need to do any config changes regarding this.

In order to test the fix, you can try patching it with the existing WSO2 Identity server pack. First, find out what is the identity-framework version used in your WSO2 IS pack(You can go to the {WSO2-IS-PACK}/repository/components/plugins folder, and see what is the version number of the jar, `org.wso2.carbon.identity.application.authentication.framework`). Then checkout to that version tag in the identity-framework repository. Apply the [fix[1]](https://github.com/wso2/carbon-identity-framework/pull/2735) there. Then build the repo to get the corresponding jar file. You need to patch the WSO2 IS product with this jar file. Please refer to the [patching process](https://docs.wso2.com/display/ADMIN44x/WSO2+Patch+Application+Process).

I hope this would fix your issue. Let us know the feedback!

[1] [https://github.com/wso2/carbon-identity-framework/pull/2735](https://github.com/wso2/carbon-identity-framework/pull/2735)

**Comment by hari819** [comment]
@tharindu-bandara ,
thank you for accepting the issue and resolving it .
We will test the patch and let you know about the results.

Thanks,

**Comment by hefesita** [comment]
@hari819  did the patch work for you? I am facing the same problem but with PostgreSQL .

**Comment by hari819** [comment]
> @hari819 did the patch work for you? I am facing the same problem but with PostgreSQL .

we did not try the patch , we disabled the internal job and are running the cleanup jobs via cronjobs.

Thought we will wait for this till the next official release
