### ISSUE TITLE
Internal/everyone group  not retrieve in unique id read and write Ldap

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7393]
User store: unique id read and write Ldap

Internal/everyone group not retrieve from SCIM2 list

Request:

 `curl -v -k --user admin:admin https://localhost:9444/scim2/Groups/?attributes=displayName`

Response: 

`{"totalResults":4,"startIndex":1,"itemsPerPage":4,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"Application/User Portal","id":"ff4617fb-7eb7-4258-a3e7-060bab171073"},{"displayName":"isTestUserRole","id":"5c4d8bd6-a818-4bad-9eea-7a1ed7b3d898"},{"displayName":"Internal/system","id":"70db7029-b355-41ad-8387-9dc5874cc11b"},{"displayName":"admin","id":"275b9e61-4caa-470d-910c-2c60c996602a"}]}`

**Comment by tharindu-bandara** [comment]
`Internal/everyone` role is for IS internal use, thus decided not to return. Therefore, this is the expected behaviour. 

Please refer to the related issue: https://github.com/wso2/product-is/issues/7254
