### ISSUE TITLE
SCIM2 User POST Search operation fails with 500 against UniqueID JDBC Primary Usertstore

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7395]
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7

**Steps to Reproduce**

1. In deployment.toml change the primary userstore to uniqueidjdbc userstore
[user_store]
type = "database_unique_id"
[user_store.properties]
SCIMEnabled= true

2. Add a User as kim for the primary userstore set the last name of kim user as jackson

3. Do a Post Search operation as below

`curl -v -k --user admin:admin --data '{"schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],"attributes": ["name.familyName", "userName"],"filter":"userName sw ki and name.familyName co jac","domain":"PRIMARY","startIndex": 1,"count": 10}' --header "Content-Type:application/scim+json"  'https://localhost:9443/scim2/Users/.search'

`
Response

```
Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: localhost (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=CA,L=Mountain View,O=WSO2,OU=WSO2,CN=localhost
* 	 start date: Wed, 23 Oct 2019 07:30:43 GMT
* 	 expire date: Tue, 25 Jan 2022 07:30:43 GMT
* 	 issuer: C=US,ST=CA,L=Mountain View,O=WSO2,OU=WSO2,CN=localhost
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'admin'
> POST /scim2/Users/.search HTTP/1.1
> Host: localhost:9443
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type:application/scim+json
> Content-Length: 214
> 
* upload completely sent off: 214 out of 214 bytes
< HTTP/1.1 500 
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Mon, 27 Jan 2020 12:07:28 GMT
< Content-Type: application/scim+json
< Content-Length: 149
< Connection: close
< Server: WSO2 Carbon Server
< 
* Closing connection 0
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in filtering users by multi attributes in domain: PRIMARY","status":"500"}
```
According to the spec in [2] startIndex is a optional parameter. Without startIndex still it gives 500
[1]. https://is.docs.wso2.com/en/5.9.0/develop/using-the-scim-2.0-rest-apis/#post-search-groups
[2]. https://tools.ietf.org/html/rfc7644#section-3.4.3

**Comment by IsuraD** [comment]
Tested with IS 5.11.0 Beta 2 and cannot reproduce the issue.
