### ISSUE TITLE
Group list from domain not retrieve all the groups, SCIM2

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7402]
User store: User store: unique id read and write Ldap

Group list using the domain query parameter retrieve only admin group.

Request:
`curl -v -k --user admin:admin https://localhost:9443/scim2/Groups?domain=PRIMARY`

Response:

`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"admin","meta":{"created":"2020-01-06T05:14:00.636Z","location":"https://localhost:9443/scim2/Groups/3db930e7-5657-46ff-916b-d275c3635088","lastModified":"2020-01-06T05:14:00.636Z"},"members":[{"display":"admin","value":"70be2c76-1724-4102-bc59-bbd2a92474cf","$ref":"https://localhost:9443/scim2/Users/70be2c76-1724-4102-bc59-bbd2a92474cf"}],"id":"3db930e7-5657-46ff-916b-d275c3635088"}]}
`

**Comment by IsuraD** [comment]
This is not reproducible with the latest kernel version built from the source. Hence closing the issue.
