### ISSUE TITLE
Identifier too long in ORACLE db script

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#7411]
The following causes an Identifier too long error when executing the identity oracle script
- Sequence name IDN_OAUTH2_DEVICE_FLOW_SCOPES_SEQ
- Trigger name IDN_OAUTH2_DEVICE_FLOW_SCOPES_TRIG
- Table name IDN_FEDERATED_AUTH_SESSION_MAPPING

**Comment by senthalan** [comment]
We need to handle the migration client as well.

**Comment by janakamarasena** [comment]
All changed identifiers were introduced after the IS590 release so we will not need to handle migration.
