### ISSUE TITLE
Tenant id is not passed when retrive scim groups through IDN_SCIM_GROUP table

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7412]
In \[1] when retrieving scim groups we are not passing the tenant id so group retrieval won't with correctly with tenant-specific requests.

\[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/v1.4.36/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/DAO/GroupDAO.java#L56-L77

**Comment by GANGANI** [comment]
I'm working on this issue.

**Comment by GANGANI** [comment]
This issue is not reproducible.

**Comment by GANGANI** [comment]
This issue can't be reproduced. It is working as expected.

**Comment by madurangasiriwardena** [comment]
This is working fine in SCIM api layer since the roles are filtered from the code level, rather than from the database layer. But it can have a performance hit.
The tenant id is passed to the database level to filter and improve performance.
