### ISSUE TITLE
SCIM 2 parameter value of attribute is case sensitive 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7413]
SCIM 2 parameter value of attribute is case sensitive. According to the SCIM2 specification this attributes should be case insensitive [1]

Request:  (display**n**ame)

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?attributes=displayname'`

Response:

```

curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?attributes=displayname'
{"totalResults":5,"startIndex":1,"itemsPerPage":5,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"id":"84612342-c35f-44ba-b4a2-d547e7d6b9be"},{"id":"34f3ece4-4390-4ce5-b5e6-f71ddba5ed44"},{"id":"b227cc5e-38cc-457b-8303-a0c5bea82f4f"},{"id":"2dc6007c-b2ee-4563-a991-278aac185050"},{"id":"3db930e7-5657-46ff-916b-d275c3635088"}]}
```

Request:

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?attributes=displayName'`

Response:

`{"totalResults":5,"startIndex":1,"itemsPerPage":5,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"role1","id":"84612342-c35f-44ba-b4a2-d547e7d6b9be"},{"displayName":"Application/User Portal","id":"34f3ece4-4390-4ce5-b5e6-f71ddba5ed44"},{"displayName":"role2","id":"b227cc5e-38cc-457b-8303-a0c5bea82f4f"},{"displayName":"Internal/system","id":"2dc6007c-b2ee-4563-a991-278aac185050"},{"displayName":"admin","id":"3db930e7-5657-46ff-916b-d275c3635088"}]}`

[1] https://tools.ietf.org/html/rfc7644#section-3.10

**Comment by GANGANI** [comment]
I'm working on this

**Comment by GANGANI** [comment]
I'm working on this.

**Comment by santoshsp16** [comment]
In the response attribute Resource is the case sensitive, only for this attribute R is the capital. is this mandatory to add R to be capital in response.  

Response:

{"totalResults":5,"startIndex":1,"itemsPerPage":5,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"role1","id":"84612342-c35f-44ba-b4a2-d547e7d6b9be"},{"displayName":"Application/User Portal","id":"34f3ece4-4390-4ce5-b5e6-f71ddba5ed44"},{"displayName":"role2","id":"b227cc5e-38cc-457b-8303-a0c5bea82f4f"},{"displayName":"Internal/system","id":"2dc6007c-b2ee-4563-a991-278aac185050"},{"displayName":"admin","id":"3db930e7-5657-46ff-916b-d275c3635088"}]}
