### ISSUE TITLE
Count roles implementation should be improved.

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7414]
The logic \[1] should be changed. JDBC user store manager and Hybrid user store manager specific tasks has been mixed up in the PR \[2]. 

\[1] https://github.com/wso2/carbon-kernel/pull/2350/files#diff-152e550a8607bdbe1ea61672b02c1243R3807-R3815
\[2] https://github.com/wso2/carbon-kernel/pull/2350

**Comment by IsuraD** [comment]
This has been implemted with  https://github.com/wso2/carbon-kernel/pull/2590/
