### ISSUE TITLE
Internal Role assigned for a User via UserAdmin Admin Service Cannot be removed from the user via management console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7415]
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7

**Steps to Reproduce**

1. In deployment.toml change the primary userstore to uniqueidjdbc userstore
[user_store]
type = "database_unique_id"
[user_store.properties]
SCIMEnabled= true

2. Add a user as kim2 for the primary user store created in step1
3. Add an Internal Role with addInternalRole Request as below.
Admin Service - https://localhost:9443/services/UserAdmin/ 

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:addInternalRole>
         <!--Optional:-->
         <xsd:roleName>Internal/test4</xsd:roleName>
         <!--Zero or more repetitions:-->
         <xsd:userList>kim2</xsd:userList>
         <!--Zero or more repetitions:-->
         <xsd:permissions>/permission/admin</xsd:permissions>
      </xsd:addInternalRole>
   </soapenv:Body>
</soapenv:Envelope>
```
4. Login to the management console. There will be a Internal role created with name Internal/test4 and kim user will be assigned to this role
5. From management console try  to remove the assigned Inetrnal/test4 Role from the kim2 user.

**Observation**
It is unable to remove the Internal/test4 role from kim2 user from the management console.

**Comment by IsuraD** [comment]
This is happening since you have added role name with Internal prefix. This won't happen if you use role name as **test4** only 
         ` <xsd:roleName>Internal/test4</xsd:roleName>`

https://github.com/wso2/carbon-identity-framework/pull/3175
