### ISSUE TITLE
NameIDFormat & AttributeProfile in IDPSSODescriptor is not configurable in resident IDP

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7419]
We need to support NameIDFormat  + AttributeProfile configurable in the resident IDP and include AtrributeProfile element in IDP metadata

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
