### ISSUE TITLE
SCIM2 group end point not support for the 'SW' operator

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7420]
User store: Unique id ldap user store

According to the SCIM2 specification ,
The entire 'SW' operator value must be a  substring of the attribute value,  starting at the beginning of the   attribute value.  This criterion is satisfied if the two strings are identical. [1]

Request:

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Groups?filter=displayName+sw+Applicat&attributes=displayName,members.display'`

Response: 

`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>`

Expected result:

`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"displayName":"Application/User Portal","members":[{"display":"admin"}],"id":"34f3ece4-4390-4ce5-b5e6-f71ddba5ed44"}]}`

[1] https://tools.ietf.org/html/rfc7644#section-3.4.2.2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
