### ISSUE TITLE
[Doc] Configuration catalog for IS 5.9.0 deployment.toml

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7422]
We need a configuration catalog similar to [APIM Configuration Catalog](https://apim.docs.wso2.com/en/latest/Reference/ConfigCatalog/) to configure the new configuration model of IS 5.9.0 in the deployment.toml file.
Hence, please update the IS 5.9.0 documentations with the configuration catalog for new configuration model.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
