### ISSUE TITLE
Can't find scim disabled hybrid roles with scim2 group pagination

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7423]
With the fix \[1] we are finding the hybrid roles which have been created when the scim is disabled and creating the scim ids for tose hybrid roles when listing the roles. But when we introduce pagination we can't achieve that. The reason is below.

1. Let's say I have Application/role1, Application/role2 hybrid roles which have scim ids and Application/role3 doesn't have the scim id.
2. With pagination, if the user request 1 Application role then from scim level (through IDN SCIM GROUP table) only 1 role will be returned it can be Application/role1 or Application/role2. Let's assume Application/role1 is returned
3. Now if we try to find the scim disabled hybrid roles, Application/role2 also treated as scim disabled role since it is not returned from step 2.

Hence we have decided to remove the logic \[1] and add scim ids for all the roles which doesn't have scim id during the server startup/listener level. This will be covered with \[1]

\[1] https://github.com/wso2/product-is/issues/5702
\[2] https://github.com/wso2/product-is/issues/7365

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
