### ISSUE TITLE
Adding a user to a Primary JDBC User Store with SCIM2 fails with 500

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7424]
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7
Primary Userstore > jdbcuserstoremanager

**Steps to Reproduce**

1. In deployment.toml change the primary userstore to jdbc userstore
[user_store]
type = "database"
[user_store.properties]
SCIMEnabled= true

2. source dbscripts/mysql.sql script from 5.9.0 wum and other scripts from 5.10.0 alpha3 snapshot
3. Try to add a user with SCIM2 request as below

`curl -v -k --user admin:admin --data '{"schemas":[],"name":{"familyName":"jackson","givenName":"kim"},"userName":"kim","password":"kimwso2","emails":[{"primary":true,"value":"kim.jackson@gmail.com","type":"home"},{"value":"kim_j@wso2.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

**Response**

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: localhost (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=CA,L=Mountain View,O=WSO2,OU=WSO2,CN=localhost
* 	 start date: Wed, 23 Oct 2019 07:30:43 GMT
* 	 expire date: Tue, 25 Jan 2022 07:30:43 GMT
* 	 issuer: C=US,ST=CA,L=Mountain View,O=WSO2,OU=WSO2,CN=localhost
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'admin'
> POST /scim2/Users HTTP/1.1
> Host: localhost:9443
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 217
> 
* upload completely sent off: 217 out of 217 bytes
< HTTP/1.1 500 
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Date: Thu, 30 Jan 2020 06:15:03 GMT
< Content-Type: application/scim+json
< Content-Length: 135
< Connection: close
< Server: WSO2 Carbon Server
< 
* Closing connection 0
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in adding the user: kim to the user store. ","status":"500"}
```

**Comment by janakamarasena** [comment]
This is failing as the UM_UUID_DOMAIN_MAPPER table is not available in the DB. This table comes with the <IS-HOME>/dbscripts/<script>.sql of the IS 5.10.0. When running the migration client this table will be added. Therefore this issue will not exist in a migrated setup from a previous version.

**Comment by ShanikaWickramasinghe** [comment]
As per #7212 issue we have tried to use 5.10.0 dbscript/script to create the jdbcuserstore manager(old). But observed the issue mentioned in #7212 against 5.10.0 script and as per the comment in #7212, it was said to use 5.9.0 script when creating a jdbcuserstore. Therefore it is currently not possible to create a jdbcuserstore manager with any of the script. And have a conflict with #7212 on which schema to use. Which schema we should use to create a jdbcuserstore manager ?

https://github.com/wso2/product-is/issues/7212

**Comment by janakamarasena** [comment]
Created a migration issue to track adding the UM_UUID_DOMAIN_MAPPER table when migrating to IS 5.10.0

https://github.com/wso2/product-is/issues/7481
