### ISSUE TITLE
Support pagination for SCIM group endpoint with member filtering

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7432]
Currently in scim when a member filtering request come to scim(member.diplay+sw+us), we are getting all the users first and then querying the roles of those users. With this way we can't support pagination. Hence we need to introduce a new API in kernel level which can accept condition and traverse through UM_ROLE and UM_USER table and should be able to get the roles for the requested filter using one sq query.

This will be covered with https://github.com/wso2/product-is/issues/7365

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
