### ISSUE TITLE
Secured GET/ Get Me SCIM2 API return user detail.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7437]
According to the document  if the GET/ Get Me SCIM2 API end point secured can not receive the user detail.[1] But currently even it secured can retrieve the  current authenticated user. 

Current configuration in idetntity.xml
```
        <Resource
                context="(.*)/scim2/Me"
                secured="false"
                http-method="GET">
            <Permissions>/permission/admin/login</Permissions>
            <Scopes>internal_login</Scopes>
        </Resource>
```
Request:

`curl -v -k --user isTestUser_1:password https://localhost:9443/scim2/Me`

Response:

`{"emails":["test@wso2.com"],"profileUrl":"http://test.com","meta":{"created":"2020-01-21T09:22:05.072Z","location":"https://localhost:9443/scim2/Users/f28f1e52-d3e0-4b73-92d6-7442bf654de1","lastModified":"2020-01-23T08:43:45.287Z","version":"testim","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"isTestUserRole,Internal/everyone,admin"}],"name":{"givenName":"givenname_isTestUser_1","familyName":"lastname_isTestUser_1"},"groups":[{"display":"isTestUserRole"},{"display":"admin","value":"3db930e7-5657-46ff-916b-d275c3635088","$ref":"https://localhost:9443/scim2/Groups/3db930e7-5657-46ff-916b-d275c3635088"}],"id":"f28f1e52-d3e0-4b73-92d6-7442bf654de1","userName":"isTestUser_1","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User":{"organization":"wso2"},"phoneNumbers":[{"type":"mobile","value":"0981276589"}]}`

[1] https://is.docs.wso2.com/en/next/develop/using-the-scim-2.0-rest-apis/#get-get-me

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
