### ISSUE TITLE
[Doc] IS 5.9.0 incorrect account locking properties configured in the  "deployment.toml" 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7442]
The account locking properties (which need to be configured in the  "deployment.toml"  file resides in <IS_HOME>/repository/conf folder )mentioned in the documentation [1] for Identity server 5.9.0 are incorrect

the properties need to be corrected as follows
```
[identity_mgt]
account_locking.allowed_failed_attempts=8
account_locking.auto_unlock_time_increment_ratio=8
account_locking.auto_unlock_after=8
account_locking.enable_account_locking=true
```
hence we need to update the documentation with correct configuration properties

[1] https://is.docs.wso2.com/en/next/learn/account-locking-by-failed-login-attempts/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
