### ISSUE TITLE
Sample on custom OAuth authenticator is not working as expected.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#7447]
The steps and sample at https://is.docs.wso2.com/en/5.9.0/learn/writing-a-new-oauth-client-authenticator/ do not work. 
Below bugs were fixed and tried, yet there are few more corrections to be done.
- Upgraded the dependency versions.
- Try register specifically in the OSGI reference holder.

Still, the clientID and secret are not read from the headers and this custom authenticator is not engaged.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
