### ISSUE TITLE
Assigning permissions to user roles - cannot untick child element permissions. 

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#7453]
Hi, In the management console, when we assign permissions to a user role, it does not allow untick permissions within child elements, until parent elements are unticked. 
This makes the user do additional work to select permissions one by one. 
<img width="1792" alt="Screen Shot 2020-02-03 at 1 52 49 PM" src="https://user-images.githubusercontent.com/10182430/73639605-b8557800-4692-11ea-8f8f-c6a95efb2a88.png">

**Comment by ruwanta** [comment]
The permission model is defined in the inclusive inheritance. There is only "allow", which inherits permission to all children. 
There is no plan to implement "deny" with "allow", as it will add lot of performance overhead. Simple rule assignment is efficient at runtime. Yes, there is a bit of difficulty managing the permissions. However we need to weigh performance over easiness in this permission assignment.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
