### ISSUE TITLE
Invalid response code validation for Get user by ID with SCIM2 in Tenant flow for a non existing user

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7455]
**Environment**
IS 5.10.0 alpha3 snapshot
DB Mysql 5.7

**Steps to Reproduce**

1. In deployment.toml change the primary userstore to uniqueidjdbc userstore
[user_store]
type = "database_unique_id"
[user_store.properties]
SCIMEnabled= true

2. Add a tenant as admin@wso2.com:admin
3. Create a user under tenant domain primary userstore
4. Try to retrieve a user by providing a invalid user id 

Request

`curl -v -k --user admin@wso2.com:admin 'https://localhost:9443/t/wso2.com/scim2/Users/73e62af1-18c5-472c-9506-2ff244ec1efb' -i
`
**Response** 

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error in getting user information from Carbon User Store foruser: 73e62af1-18c5-472c-9506-2ff244ec1efbty","status":"500"}`

This needs to be validated as 404 user not found according to the scim2 spec and not as 500

Observing this issue in both the tenant and super tenant flows.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
