### ISSUE TITLE
 If two users with the same name are created in both the primary and secondary userstore, the primary userstore user cannot  log in to the User-portal successfully

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7456]
**Description**
If two users with the same name are created in both the primary and secondary userstore, the primary userstore user cannot log into the User-portal successfully.

**To Reproduce**
(In Management Console)
1. Add a user in PrmaryStore -->  eg. username=Testuser
2. Add a user in Secondary Userstore- (username=Testuser) 
3. Both users have different password and same permissions(added all permissions for Internal/everyone).
4. Assign same role for both users
5. Successfully create both users.

6. Try to log in to user portal with Primary user store user
7. Provide user name and Password,
8. Provide required inputs for consent 
9. See error page 

**Expected behavior**
 If two users with the same name are created in both the primary and secondary userstore,  users should able to login  User portal successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/39120228/72505265-99b74a80-3865-11ea-9b8b-4bcf4483531e.png)

Tested Environment and Details:
Create secondary user store with Mysql latest (MySQL Server 8.0.19)
Enable SCIM for secondary user store,

**Note: but Secondary User store user can successfully login to userportal**
(SECONDARY/Testuser)

**Comment by thanujalk** [comment]
This issue actually comes from the scim2 Me endpoint. If you have a user with the same name available in the secondary user store, then the Me call for the primary user will give this: `{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Multiple user's found for the given username.","status":"500"}`
