### ISSUE TITLE
reCaptcha does not enabled after mentioned  failed attempts  reach (in SSO flow)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7457]
Version- identity -app 0.9.11-SNAPSHOT

**Describe the bug**
configured reCaptcha for the single sign-on flow and 
validate that reCaptcha appears If the number of failed attempts reaches the maximum configured value.
But I was unable to view reCaptcha after failed attempts reach.

**To Reproduce**
1. Setting Up ReCaptcha.[1]
2. Update the configurations, in wso2is-5.10.0-alpha3-SNAPSHOT/repository/resources/conf/templates/repository/conf/tomcat/web.xml.j2
`<filter>
        <filter-name>CaptchaFilter</filter-name>
        <filter-class>org.wso2.carbon.identity.captcha.filter.CaptchaFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>CaptchaFilter</filter-name>
        <url-pattern>/samlsso</url-pattern>
        <url-pattern>/oauth2</url-pattern>
        <url-pattern>/commonauth</url-pattern>
        <dispatcher>FORWARD</dispatcher>
        <dispatcher>REQUEST</dispatcher>
    </filter-mapping>`
3. Start the WSO2 IS Server and login to the management console
4. Click Resident Identity Provider and expand the Login Policies tab. Then, expand the Captcha for SSO Login tab.
5. Select Enable and enter a value for the Max failed attempts field. 

**Expected behavior**
After configured reCaptcha for the single sign on flow. If the number of failed attempts reaches the maximum configured value, reCaptcha window should be appears.
For example, if you enter 3, reCaptcha will be re-enabled after 3 failed attempts.

[1] https://is.docs.wso2.com/en/5.9.0/learn/setting-up-recaptcha/

**Comment by pamodaaw** [comment]
The Account Lock feature should be enabled to enable Recaptcha after the allowed number of failed attempts.
This issue is not reproducible in wso2is-5.10.0-alpha3.

**Comment by deshankoswatte** [comment]
> The Account Lock feature should be enabled to enable Recaptcha after the allowed number of failed attempts.
> This issue is not reproducible in wso2is-5.10.0-alpha3.

I'm still facing this issue even after enabling account lock feature. Please reopen the issue.
