### ISSUE TITLE
Unable to Change password -users in a secondary JDBC userstore

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7459]
Affected version: wso2is- 5.10 m7
Type: BUG
Severity: High
Priority: High

**Description**
Unable to Change password -users in a secondary JDBC user store via user portal.
Display an error message, "The current password you entered appears to be invalid. Please try again". But provided the correct current password.

**Screenshots attached**

![image](https://user-images.githubusercontent.com/39120228/69718071-6395fe00-1133-11ea-9ac5-f1b0ada86707.png)

**Additional context**
There is no issue for users in a primary user store.

**Comment by IsuraD** [comment]
FIxed with https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/98 and https://github.com/wso2/carbon-identity-framework/pull/2726/
