### ISSUE TITLE
Limited features are displaying (in management console) for the user created with self signup via User poratal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7463]
Tested Environment :
IS version: wso2is-5.10.0-alpha3-SNAPSHOT(3/2/2020)
Identify app : 0.9.21-SNAPSHOT
Database H2, User store : read_write_ldap_unique_id(primary)

**Description** 
Limited features are displaying (in management console) for the user-created with self signup via the User portal

Step to Reproduced: 
Self registration is enabled and Enable User Email Verification via management console

deployment.toml
```
[output_adapter.email]
from_address= "stlis2019@gmail.com"
username="stlis2019"
password="Uoj2010@ddm"


[event.default_listener.identity_mgt]
priority= "50"
enable = false
[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true
[event.default_listener.governance_identity_store]
priority= "97"
enable = true

[identity_mgt.user_onboarding]
enable_email_verification = true 
lock_on_creation=true
```
Accounting to document[1]

**Steps:**
1. Click on Create Account link 
2. Provide proper user name and Proceed to self Register
3. Fill all the fields in "Create New Account", select "I hereby confirm that I have read and understood the Privacy Policy" and Register
4. Confirm email confirmation with the provided email
5. Log in to the management console with the self-registered user with correct credentials

See Screenshot:
![image](https://user-images.githubusercontent.com/39120228/73660931-2adc4d00-46bf-11ea-9526-a03a41baaa10.png)

![image](https://user-images.githubusercontent.com/39120228/73661060-6bd46180-46bf-11ea-9507-7695efbfcedc.png)

[1] https://is.docs.wso2.com/en/next/learn/self-registration/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
