### ISSUE TITLE
User-store configurations doesn't include by-default configurations

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#7464]
By default user store configurations are missing in the document page[1] with the new unique user id user store managers.

Ex: If we switch the default user store manager to the JDBC user store manager based on the [1], an error will be thrown from the server startup. This is because the default user store manager type needs to be suffixed with `unique_id` term.

[1] [ https://is.docs.wso2.com/en/next/setup/configuring-a-jdbc-user-store/]( https://is.docs.wso2.com/en/next/setup/configuring-a-jdbc-user-store/)

**Comment by denuwanthi** [comment]
Created doc issue https://github.com/wso2/docs-is/issues/1144
