### ISSUE TITLE
Remove DROP TABLE statements from postgresql.sql dbscript

### ISSUE THREAD

**Issue by gdiamond** [wso2/product-is#7466]
**Description:**
When postgresql.sql is run against an empty database it produces NOTICE messages.  This is producing anxieties in my systems administrator doing an install.  I would like to remove all DROP statements from the script.  This should be acceptable given that the database should already be empty and none of the other dbscripts DROP objects before creating objects.

**Comment by JKAUSHALYA** [comment]
@gdiamond I agree to the point that the database should be empty before running these queries, however, it seems we used this to mitigate the issue that the PostgreSQL does not have `IF NOT EXISTS` keyword to check the existence of the table. We have a mechanism to do this in every other DB script (Except Oracle and DB2). We may need to keep the consistency between all of the DB scripts.
