### ISSUE TITLE
Add  same-site cookie attribute support for all WSO2-IS products

### ISSUE THREAD

**Issue by thushaaanthan** [wso2/product-is#7477]
There is an upcoming change in the default behaviour of SamSite Cookie in Chrome. From Chrome 80 onwards which is due in February, All the cookies which do not have SameSite settings will be treated as SameSite=Lax. which will prevent doing a cookie-dependent POST from cross sites. This is going to affect possibly following IS functionalities. 

1) SAML SSO, SLO session management flow
2) OIDC SSO, SLO session management flow
3) Request path authentication

**Comment by ruwanta** [comment]
This is not a blocker. One can easily configure the respective cookie as none by the frontend load balancer.
e.g. https://serverfault.com/questions/849888/add-samesite-to-cookies-using-nginx-as-reverse-proxy
