### ISSUE TITLE
">" character in PasswordJavaScriptRegEx breaks add user page management console

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7480]
If a regex pattern containing the ">" is defined in the user-mgt.xml file for PasswordJavaScriptRegEx,  

Example regex: 
^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)[A-Za-z\d~\!\-@#\$%\^&\*_\+\=`\|:;\(\)\[\]\{\}\\"'\<\>,\.\?]{8,32}$

sample password: 
1Q6EpAr-<x

In the user-mgt.xml file, the above regex can be configured by using CDATA section or by using xml escape characters to avoid xml parsing issues. The same exact regex can be obtained without any parsing issues to the next level. The issue arises when this regex pattern is set to an input HTML hidden element value when the add new user page is loaded in the management console.

<img width="847" alt="Screen Shot 2020-02-06 at 1 35 19 AM" src="https://user-images.githubusercontent.com/47600906/73908092-921c1c00-48ce-11ea-9c8f-4c1c7cd7b063.png">

The > character in the regex pattern closes the hidden input element in the HTML page. The rest of the regex pattern after the > is seen in the UI and a user cannot be added after that.

![Screen Shot 2020-02-06 at 1 47 43 AM](https://user-images.githubusercontent.com/47600906/73908130-af50ea80-48ce-11ea-9357-ec196e9f6944.png)

Replacing < and > characters in the regex with xml escape characters inside the CDATA section solves the problem of closing the input element in the HTML page.

<img width="1206" alt="Screen Shot 2020-02-06 at 2 26 22 AM" src="https://user-images.githubusercontent.com/47600906/73908156-c1328d80-48ce-11ea-9605-07bb18cf0a69.png">

But when the new user is added the password regex stored in the hidden input element will be passed to a javascript validation function and since the regex does not contain < or > characters(only the xml escape characters of < and > are in the regex) the regex matching for the <> characters does not happen.

<img width="507" alt="Screen Shot 2020-02-06 at 2 42 42 AM" src="https://user-images.githubusercontent.com/47600906/73908193-d9a2a800-48ce-11ea-9556-2b2ca4daf633.png">

To solve this issue we can check for xml escape characters in the regex received by the javascript validation function and convert them back before matching with passwords.

**Comment by somindatommy** [comment]
Fixed By https://github.com/wso2/product-is/issues/7505

Therefore, closing the issue.
