### ISSUE TITLE
[Migration] Create the UM_UUID_DOMAIN_MAPPER table

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#7481]
The UM_UUID_DOMAIN_MAPPER is required to resolve the user's domain. This table should be added when migrating to IS 5.10.0

**Comment by denuwanthi** [comment]
Even secondary jdbc unique userstores SCIM2 user creation fails, if primary userstore does not have the UM_UUID_DOMAIN_MAPPER

**Comment by denuwanthi** [comment]
Need to consider when viewing user profile from mgt console.

**Comment by denuwanthi** [comment]
Need to consider, when assigning roles and view assigned roles.
