### ISSUE TITLE
Migration client oracle scripts creates IDP_ID column which is NOT NULLABLE leading to post migration issues

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7482]
Adding the IDP_ID column to both IDN_OAUTH2_ACCESS_TOKEN and IDN_OAUTH2_ACCESS_TOKEN_AUDIT tables as not null and then modifying it to be default null causes the IDP_ID column to be a default null column that is not nullable[1]. Therefore inserting a NULL value to the column causes an error. 

To fix the issue you would have to execute:

```ALTER TABLE IDN_OAUTH2_ACCESS_TOKEN MODIFY IDP_ID INTEGER DEFAULT NULL NULL``` 

with the extra NULL on the end to also make the column nullable enabled.

[1]https://github.com/wso2-extensions/identity-migration-resources/blob/master/components/org.wso2.is.migration/migration-resources/5.8.0/dbscripts/step1/identity/oracle_rac.sql#L45

**Comment by sahanruwanga** [comment]
I'm working on this.

**Comment by sahanruwanga** [comment]
@tharakawijekoon There is no possibility to insert a null value for IDP_ID in both tables after migration. Any suggestion on this?

**Comment by tharakawijekoon** [comment]
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("WSO2"."IDN_OAUTH2_ACCESS_TOKEN_AUDIT"."IDP_ID")

**Comment by tharakawijekoon** [comment]
> @tharakawijekoon There is no possibility to insert a null value for IDP_ID in both tables after migration. Any suggestion on this?

Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("WSO2"."IDN_OAUTH2_ACCESS_TOKEN_AUDIT"."IDP_ID")

When the token clean up is enabled. The server tries to store the old token in the audit table causing the above error.

**Comment by madurangasiriwardena** [comment]
The expectation is to have a value for the IDP_ID column always. So if there is a place that does not add value to the column, rather than fixing the schema to allow null values, what we have to do is fix the place that does not add the value.

> When the token clean up is enabled. The server tries to store the old token in the audit table causing the above error.

@sahanruwanga, were you able to observe the said behavior?

**Comment by sahanruwanga** [comment]
I tried revoking a token to check the behavior but couldn't get the error.

**Comment by Buddhimah** [comment]
I have tried reproducing this issue by following the steps
1) Use database Oracle 12 c and executed Scripts on IS 5.3.0 (1603358886474)
2) Create SP in IS 5.3 and used Password grant and took a token
3) Migrated to IS-5.10 and revoked the token using /revoke endpoint
4) No issue was observed. 
5) I have also tested this in MySQL 5.7 after migrating to IS-5.11

Please let me know if im missing anything? @tharakawijekoon @tharindu-bandara @vidurananayakkara @sahanruwanga

**Comment by DMHP** [comment]
As the issue was not reproducible, I'm closing the issue. Please re-open if you still face this issue , please re-open.

**Comment by tharindu-b-hewage** [comment]
Perfect. Thank you for the response 🙌
