### ISSUE TITLE
There is no user name length validation, while Self signup  

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7485]
**Description**

There is no user name length validation, while Self signup  

[user_store.properties]
UsernameJavaScriptRegEx="^[\\S]{5,30}$" with this configuration it should not allow user to create user name with less than 5 characters , but while try with UI- user prtal or via REST api there is no . validation,

Tested with via user portal and rest API
`{"user": {"username": "one","realm": "PRIMARY", "password": "Password12!","claims": [{"uri": "http://wso2.org/claims/givenname","value": "kim" },{"uri": "http://wso2.org/claims/emailaddress","value": "abcd@gmail.com"},{"uri": "http://wso2.org/claims/lastname","value": "Anderson"},{"uri": "http://wso2.org/claims/mobile","value": "+947721584558"} ] },"properties": [{"key":"callback","value": "https://localhost:9443/authenticationendpoint/login.do"}]}`

But, when I use Unique-JDBC user store, it will validate as expected.

**Comment by denuwanthi** [comment]
This is not working for unique jdbc user store as well.
 In order to enforce regex validation you have to set the following configuration in deployment.,yaml
[user_store]
username_java_regex = "[a-zA-Z0-9._\\-|//]{6,30}$"
