### ISSUE TITLE
Error log in wso2carbon log when adding a Workflow Definitions

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7487]
Tested with,
H2,  User store-read_write_ldap_unique_id
**Description** 
Error log in wso2carbon log when adding a Workflow Definitions

Step to reproduced:
1.  Main tab in the Management Console, click Add under Workflow Definitions in the Manage section.
2.  Enter the name and description of the workflow and click Next.
3. Add Approval Step button.
4.  Search Roles radio button
5. Add Selected Roles  and Next.
6. Fill in the deployment information
7. Click Finish
See Error log in carbon log

`ERROR {org.apache.ode.bpel.compiler.bom.BpelObjectFactory$BOMSAXErrorHandler} - null:file:///Users/niluka/WSO2/5_10_Release/alpha/alpha3latest/2_5alpha3L/test/wso2is-5.10.0-alpha3/repository/bpel/-1234/WorkflowNew-3/WorkflowNew.bpel:51:17:cvc-complex-type.2.4.a: Invalid content was found starting with element 'extensions'. One of '{"http://docs.oasis-open.org/wsbpel/2.0/process/executable":import, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":partnerLinks, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":messageExchanges, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":variables, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":correlationSets, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":faultHandlers, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":eventHandlers, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":assign, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":compensate, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":compensateScope, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":empty, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":exit, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":extensionActivity, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":flow, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":forEach, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":if, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":invoke, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":pick, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":receive, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":repeatUntil, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":reply, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":rethrow, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":scope, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":sequence, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":throw, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":validate, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":wait, "http://docs.oasis-open.org/wsbpel/2.0/process/executable":while}' is expected.
[2020-02-06 20:24:41,796] [] ERROR {org.apache.ode.bpel.compiler.bom.BpelObjectFactory$BOMSAXErrorHandler} - null:file:///Users/niluka/WSO2/5_10_Release/alpha/alpha3latest/2_5alpha3L/test/wso2is-5.10.0-alpha3/repository/bpel/-1234/WorkflowNew-3/WorkflowNew.bpel:304:84:cvc-elt.4.2: Cannot resolve 'p:tExpression' to a type definition for element 'p:searchBy'.
[2020-02-06 20:24:41,805] []  WARN {org.apache.ode.bpel.compiler.bom.BpelObjectFactory} - Validation errors during parsing, continuing due to -Dorg.apache.ode.compiler.failOnValidationErrors=false switch
[2020-02-06 20:24:41,806] []  INFO {org.apache.ode.bpel.compiler.BpelC} - info: [CompilingProcess] Compiling BPEL process.
[2020-02-06 20:24:41,809] []  WARN {org.apache.ode.bpel.compiler.bom.BpelObjectFactory} - Unrecognized element in BPEL dom: extensions`

**Comment by denuwanthi** [comment]
Reducing priority since, the functionality is working and according to http://mail.wso2.org/mailarchive/dev/2015-October/056758.html

**Comment by denuwanthi** [comment]
Can  safely ignore these logs as it does not affect the functionality.

**Comment by LahiruLS** [comment]
Once the above error occurred and the identity server is restated we can not access the mgt console.
