### ISSUE TITLE
Unable to connect to WSO2IS Admin service

### ISSUE THREAD

**Issue by scholtz** [wso2/product-is#7492]
Hi, i have installed WSO2IS 5.9 in K8S private cloud.

I am trying to connect to WSO2IS admin services using Visual studio.

**Steps to reproduce error**
1) Create new console application in .net core 3.1
2) Click on Dependencies -> Add Connected Service -> Microsoft WCF Web Service Reference Provider 
3) Fill in the IS admin ws: In my case https://is.k8s.mydomain.com/services/OAuthAdminService?wsdl, set namespace to OAuthAdminService
4) Next > Next > Finish 
5) Warning is shown, but finishes successfully: 
![image](https://user-images.githubusercontent.com/1223439/74021675-3ddf6d80-499c-11ea-8f04-b46d39082dac.png)
6) Application is not able to create client:
Error:
```
The method 'deleteScope' in type 'OAuthAdminService.OAuthAdminServicePortType' is marked IsOneWay=true and declares one or more FaultContractAttributes. One-way methods cannot declare FaultContractAttributes. To fix it, change IsOneWay to false or remove the FaultContractAttributes.
```

```c#
            try
            {
                var client = new OAuthAdminService.OAuthAdminServicePortTypeClient(OAuthAdminService.OAuthAdminServicePortTypeClient.EndpointConfiguration.OAuthAdminServiceHttpsSoap12Endpoint);
            }catch(Exception exc)
            {
                Console.WriteLine(exc.Message);
            }
```

I am using latest Visual Studio (16.4.4), so wso wants probably to get compatible with it..

\bug

**Comment by scholtz** [comment]
And error is only with the deleteScope method..

You are missing <wsdl:output> tag

![image](https://user-images.githubusercontent.com/1223439/74022623-3620c880-499e-11ea-93b2-d11ee40dd69e.png)

**Comment by ruwanta** [comment]
Hi @scholtz 
Thanks for reporting. 

By the way,
We are currently working on creating counterpart APIs as REST services to manage applications. This will go under the release tag 5.10.0. 
The beta may be ready in couple of weeks.  You may want to use REST services instead of SOAP, if you develop new projects.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
