### ISSUE TITLE
Password recovery using challenge questions prompts primary users challenge questions if same user exists in multiple user stores

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7493]
If the same user exists in multiple user stores the user store domain should be used when logging in. Password recovery using challenge questions only prompts the primary user's challenge questions, as a result, the password of the primary user is reset if the security questions are answered correctly.

Affected version IS-5.7.0

Steps to reproduce:

1. Create a secondary user store.
2. Create two users in with the same username both in primary and secondary(the requirement for user store domain).
3. Enable Password recovery using challenge questions and set challenge questions and answers for the two users.
4. Try to recover password of the secondary user using challenge questions. note: the user store domain should be appended for the username since the there are multiple users with the same username across user stores.

Cause for the issue: https://github.com/wso2/product-is/issues/3813

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
