### ISSUE TITLE
Cannot view user profile in WSO2IS dashboard

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-is#7496]
**Description:**
A user who only has login permissions cannot view the user profile in the WSO2IS dashboard.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
WSO2IS-5.9.0

**Steps to reproduce:**
1. Create a user with login permission
2. Log in to the user dashboard
3. Click on the "my profile" gadget
4. The profile widget is empty

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
