### ISSUE TITLE
Unable to list secondary user store-user profile data via management console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7508]
Tested Environment:
DB: postgres 11.5 & 11.6
User store: JDBC unique
Affected version: wso2is-5.10.0-beta
OS: Mac OS X 10.13.6, x86_64
java version : 11.0.5

"Description"
Unable to list secondary user store-user profile data via management console

**Re test same scenario and only changed DB type to MSSQL 2017
I got same issue,**

Issue is due to combination of user store, if I put Primary user store with default config and change Scenario 1: Secondary user store- JDBC unique 
Scenario 2: Secondary user store- JDBC  , then there was no issue

**Step to reproduce**
1. Add secondary user store, JDBC Unique
2. Configure properties for Postgres DB 
3. Create a user for particular secondary user store
4.click on "User Profile" 

![image](https://user-images.githubusercontent.com/39120228/74136780-b51f3680-4c14-11ea-9309-7ba7115d7699.png)

Error log
ERROR {org.wso2.carbon.identity.user.profile.ui.client.UserProfileCient} - org.wso2.carbon.identity.user.profile.stub.UserProfileMgtServiceUserProfileExceptionException: UserProfileMgtServiceUserProfileExceptionException

**NOTE**
I already configure primary database as Postgres 11.6 & user store -JDBC

**Comment by denuwanthi** [comment]
When debug the flow can see the root cause is "org.wso2.carbon.user.core.UserStoreException: Error occurred while reading the domain name for user id from database."

This can happen when the primary db is configured using 5.9 dbscripts and the UM_UUID_DOMAIN_MAPPER is not available.
This issue need to be handled through migration.
