### ISSUE TITLE
HTTP Status code 200 returned from resend confirmation code API even if Email is not sent to user

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7524]
When a new tenant is created the tenant will not have the resendAskPassword template which is required for sending the email when the resend confirmation code API is invoked. In such a scenario the following error is logged in the carbon logs and a response status 200 is returned by the API even though the mail is not sent.

org.wso2.carbon.identity.event.handler.notification.exception.NotificationRuntimeException: org.wso2.carbon.email.mgt.exceptions.I18nEmailMgtServerException: Cannot find 'resendAskPassword' template in the default 'en_US' locale for 'tdw.com' tenant.

Further analysis revealed that a runtime exception is thrown in this scenario and it is not handled in the code.

```[2020-02-10 16:49:03,644] admin1@tdw.com [1] [IS]ERROR {org.apache.catalina.core.ApplicationDispatcher} -  Servlet.service() for servlet CXFServlet threw exception
org.wso2.carbon.identity.event.handler.notification.exception.NotificationRuntimeException: org.wso2.carbon.email.mgt.exceptions.I18nEmailMgtServerException: Cannot find 'resendAskPassword' template in the default 'en_US' locale for 'tdw.com' tenant.
	at org.wso2.carbon.identity.event.handler.notification.exception.NotificationRuntimeException.error(NotificationRuntimeException.java:38)
	at org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.buildNotification(NotificationUtil.java:242)
	at org.wso2.carbon.identity.event.handler.notification.NotificationHandler.handleEvent(NotificationHandler.java:64)```

**Comment by IsuraD** [comment]
@AnuradhaSK is working on this.

**Comment by AnuradhaSK** [comment]
This issue can't be reproduced in IS 5.10.0-Beta 3
