### ISSUE TITLE
SupportedTokenTypes configuration missing - IS 5.9.0

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7525]
The below configuration is missing in  identity.xml template file of WSO2 IS 5.9.0 and hence it is not configurable through deployment.toml
```
<SupportedTokenTypes>
   <SupportedTokenType>
       <TokenTypeName>TokenType1</TokenTypeName>
       <TokenTypeImplClass>org.wso2.carbon.identity.oauth2.token.OauthTokenIssuerImpl</TokenTypeImplClass>
       <PersistAccessTokenAlias>true</PersistAccessTokenAlias>
   </SupportedTokenType>
</SupportedTokenTypes>
```
The above configuration is also mentioned at [TokenIssuerDO.java](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/model/TokenIssuerDO.java)
However, the configuration is working as expected if we add it manually through identity.xml in the versions above IS 5.5.0 WUM and the configured token types are listed under service provider configurations (as OAuth/OIDC Token Issuers). But there should be a template in the WSO2 IS 5.9.0 to configure it using the deployment.toml as it is not available currently.
It'd be great if you could add a configuration on the same.
Thanks

**Comment by janakamarasena** [comment]
Ideally, the token issuers available by default(default and jwt) should be removable as well.
