### ISSUE TITLE
Scope of the tokens are not displayed to users in OAuth2/openid connect SSO flow

### ISSUE THREAD

**Issue by sahangunathilaka** [wso2/product-is#7528]
**Description**
Scope of the tokens generated against the role are not displayed to users for all grant types in OAuth2/openid connect SSO flow. The following screenshot shows the screen displayed to users without showing the scope of the tokens.

![image](https://user-images.githubusercontent.com/25486294/74235821-ddcb2d00-4cf5-11ea-99a8-321030b3437e.png)

**Steps to reproduce**
1. Configure a web app in management console
2. Access to the configured web app with an AOuth2 request and request some scopes (Scopes without mapped display names were used)
3. Login with user credentials
4. Consent request page will be visible as per the above screenshot

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
