### ISSUE TITLE
Handling Last login time as identity claim

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7532]
With the fix \[1][2] we are handling the Last login time(which claim is used in account suspension) as identity claim in identity server. Before the fix we have handled the last login claim as default claim. Since this is a behavioural change we have introduced a new property to disable this behaviour.

If you want to get the previous behaviour please add the following property in deployment.toml file
```
[identity_mgt_account_suspension]
use_identity_claims =true
```

\[1] https://github.com/wso2-extensions/identity-governance/pull/358
\[2] https://github.com/wso2-extensions/identity-governance/pull/359

**Comment by Abilashini** [comment]
Added at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/

**Comment by nilasini** [comment]
Hi @Abilashini ,

Sorry there was a mistake if a customer wants the previous behaviour they should give the value as false so the property should be as follows.

```
[identity_mgt_account_suspension]
use_identity_claims =false
```

**Comment by Abilashini** [comment]
fixed with https://github.com/wso2/docs-is/pull/1412
