### ISSUE TITLE
Functioning Error in Login-Attempts-Based adaptive authentication script 

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#7534]
The Login-Attempts-Based adaptive authentication script is not functioning as the required claim of "failedLoginAttemptsBeforeSuccess" is not added.

**Related PR**
[https://github.com/wso2/carbon-identity-framework/pull/1976/](https://github.com/wso2/carbon-identity-framework/pull/1976/)

**Comment by madurangasiriwardena** [comment]
Hi @GANGANI, Did it work after adding the "failedLoginAttemptsBeforeSuccess" manually?

**Comment by GANGANI** [comment]
> Hi @GANGANI, Did it work after adding the "failedLoginAttemptsBeforeSuccess" manually?

@madurangasiriwardena 
No. It didn't work even after the claim is added manually as the above mentioned related PR depends on #1975 and wso2-extensions/identity-event-handler-account-lock#49

**Comment by denuwanthi** [comment]
The issue resolves after adding failedLoginAttemptsBeforeSuccess claim manually, with a mapped attribute.
@GANGANI can you re-check?
