### ISSUE TITLE
IS allows to create groups with group names containing special characters, using SCIM 1.1/2.0

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#7535]
**Tested environment**
Primary Data store : MySQL 8.0.19
Secondary Data store : MySQL 8.0.19 - Unique JDBC

**Description**
In _tenant mode_ when trying to create a group for a domain(i.e. {DOMAIN}/{GROUP_NAME}) with group name containing special characters($%&()*), server allows to create the user group. 

ex: wso2.com/Asso#$&ci*()--ate

Note : For the above domain(wso2.com) a MySQL 8.0.19 secondary user store has been configured.  

**Steps to reproduce**
1. Create a new tenant(ex:wso2.com).
2. Configure a MySQL 8.0.19 secondary user store for a selected domain(ex:wso2).
3. Create a sample group using SCIM 1.1/2.0, for the created domain(wso2) with a name including special characters.
Following are two sample curl requests to create groups for SCIM 1.1 and 2.0;

_SCIM 1.1_
`curl -v -k --user admin@wso2.com:admin -X POST -d '{"displayName": "wso2/Asso#$&ci*()--ate"}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Groups/`

_SCIM 2.0_
`curl -v -k --user admin@wso2.com:admin -X POST -d '{"displayName": "wso2/Asso#$&ci*()-ate"}' --header "Content-Type:application/json" https://localhost:9443/t/wso2.com/scim2/Groups/`

**Comment by pamodaaw** [comment]
The role/group name validity is decided upon the regex expression that is defined when configuring the user stores. 
You can change the regex from the Management Console by changing the value of the attribute **Role Name RegEx (Java)** under optional configuration in user-store configurations. 
Or else you can change the **RolenameJavaRegEx** property of the secondary user store configuration xml file located at _<IS_HOME>/repository/deployment/server/userstores_

**Comment by GANGANI** [comment]
I'm working on this issue.

**Comment by GANGANI** [comment]
I'm working on this issue.
