### ISSUE TITLE
Unable to add user claims to Salesforce while creating new user using SCIM 1.1 - Outbound professioning

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7537]
**Environment configuration**
OS : Ubuntu 18.04
Primary Data store : LDAP
Secondary Data store : Postgresql 10.5

**Description**
Salesforce set as Identity provider for outbound provisioning. When add the user via SCIM 1.1 using following command
```
curl -v -k --user {IS_USERNAME}:{IS_PASSWORD} --data '{"schemas":[],"name":{"familyName":"{FAMILY_NAME}","givenName":"{FIRST_NAME}"},"userName":"{USERNAME}","password":"{PASSWORD}","emails":[{"primary":true,"value":"{HOME_EMAIL}","type":"home"},{"value":"{WORK_EMAIL}","type":"work"}]}' --header "Content-Type:application/json" https://{IS_IP}:{IS_PORT}/wso2/scim/Users
```
Rather than adding given first name and last name, default claim values are stored in Salesforce. But given claims are added to IS user store. After updating user profile manually, Salesforce update the user claims. similar for updating user claims using SCIM 1.1.

**Method to reproduce the issue**

- Configure Postgresql 10.5 as shared db and identity db
- Try Outbound provisioning for Salesforce (https://is.docs.wso2.com/en/next/learn/outbound-provisioning-with-salesforce/)

- Add user using SCIM 1.1 using given curl command

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
