### ISSUE TITLE
Two different behaviour occur in Salesforce when deleting user using SCIM 1.1 and Mgtconsole - Outbound professioning

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7538]
**Environment configuration**
OS : Ubuntu 18.04
Primary Data store : LDAP
Secondary Data store : Postgresql 10.5

**Description**
Salesforce set as Identity provider for outbound provisioning. When delete the user via SCIM 1.1 using following command
```
curl -v -k --user {IS_USERNAME}:{IS_PASSWORD} -X DELETE https://{IS_IP}:{IS_PORT}/wso2/scim/Users/{SCIM_USER_ID} -H "Accept: application/json"
```
it deletes the user. But while deleting user from management console, Username replaced by an old ID in Salesforce.

**Method to reproduce the issue**

- Configure Postgresql 10.5 as shared db and identity db
- Try Outbound provisioning for Salesforce (https://is.docs.wso2.com/en/next/learn/outbound-provisioning-with-salesforce/)

- delete user using management console and SCIM 1.1 curl command

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
