### ISSUE TITLE
Identify server management console allow user to keep two Workflow Definitions with same name

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7539]
**Description**

Identify server management console allow user to keep two Workflow Definitions with same name
while **updating** the Workflow Definition with the existing Workflow Definition, 

system display that "System Error Occurred" and also there is error logs in carbon log, BUT
the  Workflow Definition is already added,

![image](https://user-images.githubusercontent.com/39120228/74324811-9d2eea80-4dad-11ea-8bfe-2f4f512309fc.png)

**Comment by DinikaSen** [comment]
Working on this

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
