### ISSUE TITLE
Service Provider name is displayed as 'null' in the consent page when using Google/Facebook/Twitter federated authenticators

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#7540]
**Tested Environment:**
Database : DB2 11.5

**Description:**
When the Twitter/Facebook/Google authenticator is configured as a federated authenticator in WSO2 Identity Server (in both tenant and super tenant modes), and trying to sign in, the consent page displays service provider as 'null'. 
![screenshot](https://user-images.githubusercontent.com/25479743/74323967-51c80c80-4dac-11ea-8dfc-0605edc7af32.png)

**Comment by madurangasiriwardena** [comment]
@htamahc is working on this.
