### ISSUE TITLE
SMS OTP authenticator does not support going back to multi-option page

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#7542]
**IS 5.8.0**

**Scenario :**
Set the service provider's authentication flow as basic authenticator(first step). Set Email and SMS authenticators as the seond step(multi-option).
Upon providing basic credentials user will be prompted to the multi-option page.
Say the selection was SMS authenticator where he/she was taken to the SMS OTP page.
Now only the user noiced phone s not in his possesion and wants to authenticate with Email OTP.
Not having a multi-option link forces the user to re-enter the asic credentials.

**Requirement :**
Provide going back to multi-option page to other authenticators as it is in the TOTP authenticator.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
