### ISSUE TITLE
Unable to create group with user using SCIM 2.0 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7543]
**Environment configuration**
OS : Ubuntu 18.04
Primary Data store : LDAP
Secondary Data store : Postgresql 10.5

**Description**
While create a group using SCIM 2.0 with a user, reply says there is no such user in the user store.
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"null","detail":"User: kim@wso2.com doesn't exist in the user store. Hence can not update the group: PRIMARY/manager","status":"500"}
```
Following curl command is used to create group
```
curl -v -k --user admin:admin -X PUT -d '{"displayName":"manager","members":[{"value":"b3c07363-f0ed-4798-97f9-0cb26d9d79c0","display":"kim"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/a43fe003-d90d-43ca-ae38-d2332ecc0f36
```

**Method to reproduce the issue**

- Configure Postgresql 10.5 as shared db and identity db
- Create a User
- Create group with above user using SCIM 2.0  curl command

**Comment by pamodaaw** [comment]
This is the sample curl request to assign users to a group.
_curl -v -k --user[username]:[password] -X PUT -d '{"displayName":[group name],"members":[{"value":[user ID],"display":[user's name]}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/[group ID]_

Here, the "display" attribute should be the **username** of the relevant user.

**Comment by Thumimku** [comment]
Resolved
