### ISSUE TITLE
'initializeNewClaimManager' property missing in the 'user-mgt.xml' file after the server startup.

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/product-is#7549]
**Description**
Even though we have the below property in the '<HOME>/repository/conf/user-mgt.xml' file of the default pack of IS-KM-5.9.0, it will be removed during the starting process of the server.
`<Property name="initializeNewClaimManager">true</Property>`

**Cause**
The issue caused due to missing of the  `"realm_manager.properties.initializeNewClaimManager" : true,` property in the '<IS-KM_HOME>/repository/resources/conf/default.json' file.(default template) 

**Affected version**
IS-KM-5.9.0 updated pack.

**Comment by mefarazath** [comment]
As a workaround, we can add below entry to the deployment.toml file

[realm_manager.properties]
initializeNewClaimManager = "true"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
