### ISSUE TITLE
Default regex for email claim does not allow valid email addresses

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#7550]
The default regex set for http://wso2.org/claims/emailaddress claim is ^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$

This does not seem to allow some valid email addresses such as farasath+1@gmail.com which is syntactically a valid one.

Test: https://regex101.com/r/BcVDUW/1

**Comment by mefarazath** [comment]
There is a lot of discussion on building the perfect regex for validating an email address 
https://stackoverflow.com/questions/201323/how-to-validate-an-email-address-using-a-regular-expression

I managed to get my use case done using the below regex
^(.+)@(.+)$

**Comment by mefarazath** [comment]
Another alternative is to allow +

^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
