### ISSUE TITLE
Role Based Scope Validator is available for Client Credential grant type too.

### ISSUE THREAD

**Issue by sahangunathilaka** [wso2/product-is#7556]
**Description**
Role based scope validator can be enabled for the **Client Credential** grant type too. When it is enabled, application can obtain the token only if the user which configured the SP has been assigned to roles for desired scopes.

**Steps to reproduce**
1. Login to management console and register an SP
2. Do OAuth/OpenID Connect Configuration and select Client Credential as the Allowed Grant Types
3. Enable Role Based Scope Validator
4. Create a new role (e.g. "login") and **do not** assign it to the user at first
5. Register some scopes (e.g. comment) at identity/oauth2 endpoint with binding to the role "login" 
6. Try obtaining a token with client credential grant type for the SP configured by the user
7.  It will not issue a token since "login" role is not assign to the user
8. Then, assign role to the user and try obtaining a token. It will provide a token this time.

**Suggestion**
Since client credential grant type depends on the application credentials, but not on users, does the Role Based Scope Validator need to be available for client credential grant type?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
