### ISSUE TITLE
Needs to remove sso-idp-config.xml which was previously used for dashboard related cluster configurations

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7559]
**Environment**
IS 5.10.0 beta 2 node cluster deployment
DB Mysql 5.7

While setting up a 2 node cluster deployment observed that the following file which we use to do previous dashboard configurations is still available in the IS 5.10.0 beta pack. 

`IS_HOME>/repository/conf/identity/sso-idp-config.xml`

According to new user portal implementation when setting up a cluster we do not need to do any configuration in the above file. Therefore it would be better to remove this file if we are no longer using this file.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
