### ISSUE TITLE
NullPointerException upon calling OAuth2TokenValidationService - validate operation (Oracle DB)

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7561]
Steps to reproduce the issue:

1. In a fresh IS pack use an Oracle database as the primary for IS. (IDN tables should be in this database)
2. Configure as per the following doc[1] to get the user claims of the authorized user as a JWT token with the validation response.
3. Set the DefaultCacheTimeout in carbon.xml to 0 to avoid waiting for 15min
4. Enable support by default for an identity claim like lastLogonTime to see the claim in the user profile.
5. Register a new SP application.
6. Create a new user. Update the new user's profile. (Leave the identity claim blank)
7. Obtain an access token for the new user and call the OAuth2TokenValidationService - validate operation.( A NullPointerException is seen, you might have to tail the logs to see it)

Analysis and cause of the issue:

When a new user is created and you update the user's details in the user profile, these values will get added to a cache and then persisted in the database. In an Oracle database, an empty string will be added as a null value, therefore all the empty values in the user's profile will be persisted in the database as null values. Upon JWT token generation the null value returned from the database for the identity claims causes a NullPointerException.

The above issue occurs only for identity claims, for other claims, the empty and null check is carried out.

[1]https://docs.wso2.com/display/IS560/JWT+Token+Generation

**Comment by rksk** [comment]
This affects SCIM patch operations as well
