### ISSUE TITLE
Document accountState claim values

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#7567]
There is no proper documentation to explain what are the values for accountState identity claim and what is the meaning of each value.

**Comment by piraveena** [comment]
We have this doc for 5.7.0 https://docs.wso2.com/display/IS570/Account+Pending+Status

**Comment by nilminiwso2** [comment]
Latest documentation : https://is.docs.wso2.com/en/latest/learn/pending-account-status/#account-pending-status
Note that these docs will be improved further for IS 6.0.0.

Please reopen the issue if you find anything missing.
