### ISSUE TITLE
[Migration] Handle newly added claim in migration

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#7573]
Related to claim introduced in fix https://github.com/wso2/carbon-identity-framework/pull/2747/
`<Claim>
				<ClaimURI>http://wso2.org/claims/identity/failedLoginAttemptsBeforeSuccess</ClaimURI>
				<DisplayName>Failed Attempts Before Success</DisplayName>
				
				<AttributeID>failedLoginAttemptsBeforeSuccess</AttributeID>
				<Description>Failed Attempts Before Success</Description>
			</Claim>`

**Comment by Abilashini** [comment]
Resolved with https://github.com/wso2-extensions/identity-migration-resources/pull/42
