### ISSUE TITLE
Unable to delete user while provision users only to external SCIM 1.1 supported system (Dumb Node)

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7576]
**Environment configuration**
OS : Ubuntu 18.04
Primary Data store : Postgresql 10.5
Secondary Data store : Postgresql 10.5

**Description**
While using following SCIM curl command to delete user for external SCIM 1.1 supported system(external IS) via dumb node(Internal IS), there is no deletion occurs. Here inbound provisioning set to tenant domain not super tenant domain.

**Method to reproduce the issue**

- Configure Postgresql 10.5 as shared db and identity db
- Create a tenant
- Configure postgresql 10.5 as secondary store 
- Configure external SCIM 1.1 supported system (another IS instance) as identity provider
- Configure outbound provisioning to external IS
- Configure inbound provisioning as dumb node
- Use following command to create user
```
curl -v -k --user test@oneexample.com:testt --data '{"schemas":[],"name":{"familyName":"gunasinghe","givenName":"hasinitg"},"userName":"Postgres/marcoo","password":"hasinitg","emails":[{"primary":true,"value":"hasini_home.com","type":"home"},{"value":"hasini_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users
```
- Use following command to delete user
```
curl -v -k --user test@oneexample.com:testt -X DELETE https://localhost:9443/wso2/scim/Users/{SCIM ID}
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
