### ISSUE TITLE
SCIM ID returns even by providing invalid user name for  SCIM Provisioning Configuration

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7580]
**Environment configuration**
OS : Ubuntu 18.04
Primary Data store : Postgresql 10.5
Secondary Data store : Postgresql 10.5

**Description**
While using following SCIM curl command to create role for external SCIM 1.1 supported system(external IS) via dumb node(Internal IS) by providing **invalid user name** for  SCIM Provisioning Configuration, role is not created. But instead of error response, new SCIM Id is returned with following response.
```
{"displayName":"testingooo","meta":{"created":"2020-02-14T14:20:30","location":"https://localhost:9443/wso2/scim/Groups/c9e35e94-e0bf-4ac3-b9ca-347dd985e146","lastModified":"2020-02-14T14:20:30"},"schemas":["urn:scim:schemas:core:1.0"],"members":[],"id":"c9e35e94-e0bf-4ac3-b9ca-347dd985e146"}

```

This error also occur when creating users by providing invalid user name for  SCIM Provisioning Configuration using SCIM 1.1

Response
```
{"emails":[{"type":"home","value":"hasini_home.com"},{"type":"work","value":"hasini_work.com"}],"meta":{"created":"2020-02-14T14:26:11","location":"https://localhost:9443/wso2/scim/Users/c6e9e34d-9ec0-45f4-ada0-1cd001687226","lastModified":"2020-02-14T14:26:11"},"schemas":["urn:scim:schemas:core:1.0"],"name":{"familyName":"gunasinghe","givenName":"hasinitg"},"id":"c6e9e34d-9ec0-45f4-ada0-1cd001687226","userName":"Postgres/olop"}
```

This issue may relate to https://github.com/wso2/product-is/issues/7578

**Method to reproduce the issue**

- Configure Postgresql 10.5 as shared db and identity db
- Create a tenant
- Configure postgresql 10.5 as secondary store 
- Configure external SCIM 1.1 supported system (another IS instance) as identity provider
- Configure outbound provisioning to external IS with invailid username
- Configure inbound provisioning as dumb node
- Use following command to create user
```
curl -v -k --user test@oneexample.com:testt --data '{"schemas":[],"name":{"familyName":"gunasinghe","givenName":"hasinitg"},"userName":"Postgres/olop","password":"hasinitg","emails":[{"primary":true,"value":"hasini_home.com","type":"home"},{"value":"hasini_work.com","type":"work"}]}' --header "Content-Type:application/json" https://localhost:9443/wso2/scim/Users
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
