### ISSUE TITLE
Prompts an incomplete Sign In page when account confirmation email's link is clicked, if self registartion is done via REST API

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#7581]
**Description**
If a user self-register using the REST API, an incomplete sign-in page is prompted to the user when he clicks on the account confirmation email's link. If the user self-register using the user-portal, the complete sign in page will be prompted after the email confirmation link is clicked.

After the account confirmation email's link is clicked, the following message box prompts.
![rsz_screenshot_from_2020-02-14_14-10-51](https://user-images.githubusercontent.com/25483865/74517617-751fc280-4f38-11ea-85c1-7dc23a1fb5ba.png)

After the close button of this message box is clicked, the following page prompts. (IF self-registration is done via REST API)
![rsz_screenshot_from_2020-02-14_14-11-14](https://user-images.githubusercontent.com/25483865/74517699-9b456280-4f38-11ea-86c5-a44e6c0cfc1f.png)

However, if the self-registration is done via user-portal, the following
page prompts.
![rsz_screenshot_from_2020-02-14_14-12-50](https://user-images.githubusercontent.com/25483865/74517758-b7490400-4f38-11ea-8a00-845c6199ab5a.png)

**To Reproduce**
 1. Go to 'management console' and follow the 'Set Up' section in https://is.docs.wso2.com/en/latest/learn/self-registration/
2. Self-register a user using REST API https://docs.wso2.com/display/IS590/apidocs/self-registration/#!/operations#SelfRegister#mePost
3. Login to the mail provided in the request and check the email received as "WSO2 - Account Confirmation"
4. Click on the account confirmation link, and then click the "close" button in the message box.
5. It will redirect to an incomplete Sign in page

**Environment**:
OS: Linux 18.04
DB: H2/PostgreSQL 11.5
Browers: Chrome

**Comment by NilukaSripalim** [comment]
Duplicated: https://github.com/wso2/identity-apps/issues/385
