### ISSUE TITLE
Error while using WSO2 Stream Processor for Adaptive Authentication

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#7582]
An error occurred while using WSO2 Stream Processor for Risk-based Adaptive Authentication. [https://is.docs.wso2.com/en/next/learn/configuring-risk-based-adaptive-authentication/](https://is.docs.wso2.com/en/next/learn/configuring-risk-based-adaptive-authentication/)

Below is the error log of Stream processor worker node:
![Screenshot from 2020-02-14 15-19-16](https://user-images.githubusercontent.com/25496816/74520581-dd24d780-4f3d-11ea-8ce2-ffcdf622a3b2.png)

Below image shows the error log of IS:
![Screenshot from 2020-02-14 15-18-35](https://user-images.githubusercontent.com/25496816/74520603-e9a93000-4f3d-11ea-86d9-fb1ba1e5c0bd.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
