### ISSUE TITLE
JSPException occurred when trying to load the Resident Identity Provider [IS-5.9.0]

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7586]
Description:
When loading the resident-idp, the UI is failing with a null pointer exception. The reason for the issue is samlAuthnRequestSigningProperty is not properly added with the default value

Suggested Labels:
bug

Suggested Assignees:

Affected Product Version:
IS 5.9.0

**Comment by Kanapriya** [comment]
@SiluniPathirana : Could you please add the steps to reproduce the exact issue?

**Comment by SiluniPathirana** [comment]
1. Configure identity DB in the IS 5.9.0
2.Edit the resident IDP config and save
3.take the Latest 5.9.0 update
3. Setup the identity DB by pointing the previous DB used
4.Start the server
5. try to load the resident IDP
