### ISSUE TITLE
Callback url of the service provider created for User Portal contains the server port number and host

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7588]
If the hostname or port number is changed after starting the server, login to the user portal fails with an invalid callback URL.

**Comment by ayshsandu** [comment]
Related to https://github.com/wso2/product-is/issues/10514

**Comment by ayshsandu** [comment]
The recommended approach is to manually change the callback URL of the Myaccount and Console apps accordingly when a port or hostname change is done in the server.

Steps:
1. Change hostname or port of the server
2. Remove Myaccount and Console apps from read only system apps by adding the following to the deployment.toml
   ```
    [system_applications]
    read_only_apps = []
   ```
3. Restart the server
4. Update callback URL of the myaccount and console apps from the management console accordingly.
5.  Change the issuer URI of the Resident IDP accordingly.
