### ISSUE TITLE
TOTP configuration not available on new user portal

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#7593]
**Description:**
Please refer [wso2/identity-apps/issues/425](https://github.com/wso2/identity-apps/issues/425)

**Related issues:** [docs-is/issues/1159](https://github.com/wso2/docs-is/issues/1159)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
