### ISSUE TITLE
Password recovery does not compare "Enter New Password" and "Confirm password" fields

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7594]
**Description:**
Password recovery does not compare "Enter New Password" and "Confirm password" fields

**Steps to reproduce:**
Try out the password recovery flow as mentioned [here](https://is.docs.wso2.com/en/next/learn/password-recovery/).

In the "Reset Password" page, enter different passwords for "Enter New Password" and "Confirm password" fields. Password reset is successful and now you can log in with the password in the "Enter New Password" field.

**Comment by thivi** [comment]
Similar issue: https://github.com/wso2/identity-apps/issues/458
Has been fixed by: https://github.com/wso2/identity-apps/pull/465
