### ISSUE TITLE
IS connector store is not updated with latest private key JWT client authenticator

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7596]
private key JWT client authenticator is not shipped with the product. So user needs to download it from the connector store.

In this doc https://is.docs.wso2.com/en/next/learn/private-key-jwt-client-authentication-for-oidc/ we have point to the connector store https://store.wso2.com/store/assets/isconnector/details/3990fa78-6696-4b98-8af8-d4cc7611099a and still we are using 1.0.9 .

In the public nexus, we have released 2.2.7. So we need to update the connector store with the latest private-key-jwt-client-authenticaticator and mark the supported version.

Public nexus location: https://maven.wso2.org/nexus/#nexus-search;quick~clientauth

I have tested org.wso2.carbon.identity.oauth2.token.handler.clientauth.jwt.PrivateKeyJWTClientAuthenticator-2.2.7 jar with IS5.1.0-beta2 and it is working

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
