### ISSUE TITLE
NET::ERR_CERT_INVALID Error when trying to access a Cluster setup with MAC using latest chrome version

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7599]
**Environmnet**
2 Node Ubuntu Cluster
Chrome 80
Mac OS

**Steps to Reproduce**

1. Setup a 2 Node Cluster using the guide [1].

2. Generate a server.crt file in the nginx side
Create the server key.
$sudo openssl genrsa -des3 -out server.key 1024
Create the certificate signing request.
$sudo openssl req -new -key server.key -out server.csr
Remove the password.
$sudo cp server.key server.key.org
$sudo openssl rsa -in server.key.org -out server.key
Sign your SSL certificate.
$sudo openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

3. Import the cert to the repository/resources/security/client-trustore.jks using the below command
keytool -import -trustcacerts -alias server -file server.crt -keystore client-truststore.jks

4. Add the relevant cluster domain name to the local machine etc/hosts file

5. Try to access the cluster URL with chrome latest browser version from a Mac OS

**Observation**
Observing below error in the UI

NET::ERR_CERT_INVALID
Subject: is590.qa.com
Issuer: is590.qa.com
Expires on: 19 Aug 2020
Current date: 15 Feb 2020
PEM encoded chain:-----BEGIN CERTIFICATE-----
MIICjTCCAfYCCQDrFXYUVsEOkTANBgkqhkiG9w0BAQsFADCBijELMAkGA1UEBhMC
TEsxDDAKBgNVBAgMA1dFUzEMMAoGA1UEBwwDQ09MMQ0wCwYDVQQKDARXU08yMQsw
CQYDVQQLDAJJUzEVMBMGA1UEAwwMaXM1OTAucWEuY29tMSwwKgYJKoZIhvcNAQkB
Fh1zaGFuaWthbmlzaGFkaGkxOTkyQGdtYWlsLmNvbTAeFw0xOTA4MjAwNjAwMTha
Fw0yMDA4MTkwNjAwMThaMIGKMQswCQYDVQQGEwJMSzEMMAoGA1UECAwDV0VTMQww
CgYDVQQHDANDT0wxDTALBgNVBAoMBFdTTzIxCzAJBgNVBAsMAklTMRUwEwYDVQQD
DAxpczU5MC5xYS5jb20xLDAqBgkqhkiG9w0BCQEWHXNoYW5pa2FuaXNoYWRoaTE5
OTJAZ21haWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC3/Z2X1IpK
ZNyk/28AkuG3AYJO8sGJwgOUVr5qoLm53FrzCWNx+bVP3xL3IyeHuPvwyMH1LORY
Cr/fna1wReeOMpYh88tYg3kQkGMH5FCYBV4Mo1tVbnySXrZZM9yqbtveCj3mro3a
ys0vxrCU7/oobs09msNO8a+o/xjEqegAEwIDAQABMA0GCSqGSIb3DQEBCwUAA4GB
AA0XvB3IzVIwPRR9KhkzZrelaRoNW8FuePMTBHfGYPV3k34fhKQLhReACpWdxS7s
Mp00dop26raSQxDrIxLxyo0TpsW6a+TPM8ZHyGbPSsTn5bg21PxH81AuM2HvzMX1
ymYPrYFH9ui90uhccrLk/zPCEIvOBoDTVp7bAbBIismB
-----END CERTIFICATE-----

![clus](https://user-images.githubusercontent.com/31848014/74584140-eb81fa80-4ff4-11ea-8ce5-472c0426670f.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
