### ISSUE TITLE
Bad UX when an incompatible password is entered in password recovery

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7605]
**Description:**
![image](https://user-images.githubusercontent.com/1332991/74584804-1d4a8f80-4ffc-11ea-9ab7-7eea5ad59f7c.png)

**Steps to reproduce:**
Follow the password recovery flow and enter a password with 4 characters in the new password field. The error message is shown as above, which is not meaningful to a non-technical person.

**Comment by AnuradhaSK** [comment]
I'm working on this
