### ISSUE TITLE
Bad UX when the challenge questions are not configured in password recovery

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7606]
**Description:**
![image](https://user-images.githubusercontent.com/1332991/74584857-ae216b00-4ffc-11ea-8125-ee998696a4b3.png)
  

**Steps to reproduce:**
Follow password recovery using challenge questions without configuring challenge questions. The error message is shown as shown above.

User experience needs to be improved.

**Comment by thivi** [comment]
This issue has been resolved by https://github.com/wso2/identity-apps/pull/101
The view looks as follows now: 
![image](https://user-images.githubusercontent.com/20745428/93878009-05a45980-fcf7-11ea-81f9-01760eace4da.png)
