### ISSUE TITLE
IDN_OIDC_JTI table is not cleared in Private key JWT authenticator

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7608]
Clients needs to send jwt_assertions to IS and IS stores in IDN_OIDC_JTI table against the jti https://github.com/wso2-extensions/identity-oauth-addons/blob/master/component/client-handler/src/main/java/org/wso2/carbon/identity/oauth2/token/handler/clientauth/jwt/dao/JWTStorageManager.java#L124. 

This jti should be unique unless we configure configure

```
[event_listener.properties]
PreventTokenReuse= false
``` 

Since the jti needs to be unique always, This IDN_OIDC_JTI table is not cleared at any point and it will make the table to grow.

According to the spec [1],
```
 The JWT MAY contain a "jti" (JWT ID) claim that provides a
        unique identifier for the token.  The authorization server MAY
        ensure that JWTs are not replayed by maintaining the set of used
        "jti" values for the length of time for which the JWT would be
        considered valid based on the applicable "exp" instant.
```
So we need to revisit on keeping the stale tokens in the db after 'exp' time of the jwt tokens.

[1]https://tools.ietf.org/html/rfc7523#section-2.2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
