### ISSUE TITLE
Re-Captcha for security questions based password recovery not working

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#7613]
**Steps to reproduce:**
Configure security questions based password recovery and add below configs

- Enable reCaptcha for Security Questions Based Password Recovery
- Max Failed Attempts for ReCaptcha

![image](https://user-images.githubusercontent.com/1332991/74585265-e1fe8f80-5000-11ea-9fb1-97df482f029a.png)

Captcha is not shown after 2 attempts with incorrect answers for security questions.

**Comment by GANGANI** [comment]
This issue is no longer there in the latest IS. Tested for both tenant mode and super tenant mode.
