### ISSUE TITLE
Remove redendent userid claims

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#7618]
**Description:**
$subject. See following redundant claims,
- http://wso2.org/claims/externalid 
- http://wso2.org/claims/identity/uuid 
- http://wso2.org/claims/userid 

Need to keep only one claim and its better to have it marked as "Supported by default" and "ReadOnly" as well.

**Comment by IsuraD** [comment]
http://wso2.org/claims/identity/uuid has been removed. Will keep http://wso2.org/claims/externalid to keep an external identifier for a user.
