### ISSUE TITLE
 Needs fine grained permission for user challenges API 

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#7624]
Currently, the authorization is enforced by only the following config in identity.xml

<Resource context="(.*)/api/users/v1/(.*)/challenges(.*)" secured="true" http-method="all">
<Resource context="(.*)/api/users/v1/(.*)/challenge-answers(.*)" secured="true" http-method="all">

Need to break this into individual operations and apply authz for each operation.

**Comment by IsuraD** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2795/
