### ISSUE TITLE
Blank response when trying to add a role from insufficient permission

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#7626]
**Description:**
When trying to add a role by using Basic Auth with the credentials of a user who is not permitted to create roles, status 403 Forbidden is returned but it does not have a response body. Please refer the attached screenshot.
![image](https://user-images.githubusercontent.com/19262008/74586230-93a2be00-500b-11ea-968e-63318c6344a6.png)
As [this](https://is.docs.wso2.com/en/next/develop/scim2-rest-apis/#/Groups%20Endpoint/createGroup) documentation a response must be there.
 
**Affected Product Version:**
wso2is-5.10.0-beta2

**OS, DB, other environment details and versions:**    
MacOS 10.15.3, MSSQL 2019

**Steps to reproduce:**
* Login to Management Console and create a tenant.
* Login to the created tenant.
* Add MSSQL 2019 a secondary user store.
* Add a user in the created secondary user store without providing the permission to add a role.
* Execute Create group API by referring https://is.docs.wso2.com/en/next/develop/scim2-rest-apis/#/Groups%20Endpoint (add the authentication as basic auth and use the created user credentials).

**Comment by gkaran** [comment]
The same applies to unauthorized. Given that this is scheduled for the "future" milestone, please at least fix the documentation as it is misleading. 

Based on your docs we created a whole layer of API management only to find out later that the unauthorized and forbidden responses were problematic.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
