### ISSUE TITLE
Analyzing overall login attempts has a misleading chart representation.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#7629]
Steps to reproduce:
1 - In IS in super tenant create a user (ex: user10)
2 - Create a sub-tenant and create a user with the same username as provided in step 1 (ex: user10)
3 - Follow [1]
4 - Analyze login analytics as provided in [2] and [3]

The observation for [3] and [2] are given below.

<img width="1630" alt="Screenshot 2020-02-15 at 17 04 12" src="https://user-images.githubusercontent.com/24982871/74587166-475c7b80-5015-11ea-973a-88dbed825000.png">

<img width="826" alt="Screenshot 2020-02-15 at 17 06 06" src="https://user-images.githubusercontent.com/24982871/74587183-8094eb80-5015-11ea-9852-6e308a9452ec.png">

Here we can see that when filtering out by username, all users with the username as 'user10' are represented in the same column in the chart. Ideally, these users should be separated out according to the userstore domain and tenant domain as with IS these users has a distinct representation.

Affected Product Version:
WSO2 IS Analytics 5.8.0

Suggested Labels:
Improvement

[1]  https://is.docs.wso2.com/en/next/learn/analyzing-overall-login-attempts/
[2] https://is.docs.wso2.com/en/next/learn/analyzing-overall-login-attempts/#details-of-login-attempts-by-user
[3] https://is.docs.wso2.com/en/next/learn/analyzing-overall-login-attempts/#full-details-of-each-login-attempt

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
