### ISSUE TITLE
When user account is locked REST API request gives 401 Un-Authorized.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7647]
Ex: 
Request endpoint: https://localhost:9443/t/carbon.super/api/users/v1/me/sessions
Authentication mechanism: Basic Authentication
User Account state: locked

Ideally, the response should be 403 Forbidden.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
