### ISSUE TITLE
Instagram federated authenticator cannot be used as Instagram API Platform is no longer available

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#7648]
**Description:**
When trying to access [https://www.instagram.com/developer/](https://www.instagram.com/developer/) to register a new client for the purpose of [Configuring Instagram Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Instagram+Authenticator) with WSO2 IS, the [Instagram API Platform page](https://www.instagram.com/developer/) notifies that "new client registration and permission review on Instagram API platform are discontinued". The new API Instagram provides is [Instagram Basic Display API](https://developers.facebook.com/docs/instagram-basic-display-api/), and it **cannot** be used for authentication purposes. Hence, "[Instagram Authenticator Connector](https://store.wso2.com/store/assets/isconnector/details/175db9b2-1aae-4402-adee-94c4acd751d2)" can no longer be used.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
