### ISSUE TITLE
No matching user message pops when assigned the only user to the role

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7652]
**Description:**
1. Create a role.
2. Create a user.
3. Make sure that only one user is available in the system. Then Go to the assign users page by clicking the corresponding button under the role.
4. You should see only one user. Then assign that user to the role(by clicking update).
5. The following message pops up first.
![Screenshot from 2020-02-16 13-39-25](https://user-images.githubusercontent.com/22551445/74601286-8563a900-50c2-11ea-8598-eee48319646b.png)
6. Once ok is clicked, then the expected message comes up.
![Screenshot from 2020-02-16 13-39-39](https://user-images.githubusercontent.com/22551445/74601294-93192e80-50c2-11ea-96aa-5415694f0b1e.png)

The message in `step 5` should pops up when there are no users to be assigned only. In this flow only `step 6` is expected.

**OS, DB, other environment details and versions:**    
- Email as username
- Db2 11.5
- Secondary user store(UniqueIdJDBC with Db2)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
