### ISSUE TITLE
Email Management endpoints permissions are not properly defined in identity.xml

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7654]
Due to $Subject, a user just having only the fine-grained level of permissions defined in the swagger documentation is not able to consume the API.

![email-permissions](https://user-images.githubusercontent.com/5061791/74601781-c90ce180-50c7-11ea-95ce-555fafae7348.png)

Validation must be falling back to permissions define in [here](https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml#L1275)

Validate the same case for all the REST endpoints in all the APIs.

**Comment by Thumimku** [comment]
I am working on this Issue
