### ISSUE TITLE
UMA tokenless request to resource server doesn't return the permission ticket

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#7655]
**Description:**
According to the diagram at https://is.docs.wso2.com/en/next/learn/user-managed-access-endpoints/#permission-endpoint and UMA2 specification on Resource Server Responds to Client's Tokenless Access Attempt (https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html#permission-success-to-client), resource request without token should return 401-Unauthorized response with a permission ticket. But in IS, permission ticket is not returned. 

*Request*
```
curl -X GET https://localhost:9443/t/wso2.com/api/identity/oauth2/uma/resourceregistration/v1.0/resource/9db9fe50-3cef-4c9c-b459-1af31001aec0 -H "Content-Type: application/json" -v -k
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
