### ISSUE TITLE
Can not revoke refresh token

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#7659]
Description
The refresh token generated can not be revoked.

Environment:
H2 database.
Email user name enabled.
Primary User store
Super Tenant User

The steps followed:
1. Generated a refresh token using 'password grant' type.
Request 
`curl -k -d "grant_type=refresh_token&refresh_token=4a5189de-ac7e-34dc-82b0-e9259628f431" -H "Authorization: Basic Ym9hSTh4Mnc3MDFBNkc3ZzFQWGh4QVh4SUtBYTpiakZJRHN5VEYwXzNxNEp4MmFreUpidElnbWdh" -H "Content-Type: application/x-www-form-urlencoded" https://localhost:9443/oauth2/token`

Response
`{"access_token":"6dcc833d-0b12-331f-a965-64bc59f0cd02","refresh_token":"6941d2c5-f2dd-3323-9bbc-50bc0faaf764","scope":"openid","id_token":"eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiN3JPaVJRNjZyck5EZHE5Y3VjMVB6dyIsImF1ZCI6ImJvYUk4eDJ3NzAxQTZHN2cxUFhoeEFYeElLQWEiLCJzdWIiOiJhZG1pbkB3c28yLmNvbSIsIm5iZiI6MTU4MTg0OTQ2NiwiYXpwIjoiYm9hSTh4Mnc3MDFBNkc3ZzFQWGh4QVh4SUtBYSIsImFtciI6WyJyZWZyZXNoX3Rva2VuIl0sImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6MTU4MTg1MzA2NiwiaWF0IjoxNTgxODQ5NDY2LCJlbWFpbCI6ImFkbWluIn0.AkioS3wawr_CXRP_gxjptKNRAZaIes4nQFCoJDhBRgLye4PweenUGpMfm-eN0SwztPqhS8ZYNVSxHE-YclBCYnTMQZlzczSS6oVf3ZWhOUEiiRUZoG73ire1b9e0_m4mWiAzGS7LBpR7kPxJjjVtOQ0aEE8bjP336olgtge4YizY_q58qYp-9Ji1PBoJFui7OIQaGDJR-1h5PmuZ5DDD9s1VEbI6cvEF1FqEVghD1V8nycFBtE5NeWsan_-bv1gbXTGSFdcnhslje8Md41t1cngBlwrn1n1Vvu2rSbs5NQ_g7tjljM0n323ajiHqqoGMOcJOWUUJX4OUUzQ2FZvAMw","token_type":"Bearer","expires_in":3600}`

2. Revoked the refresh token
Request:
`curl -X PUT --basic -u "boaI8x2w701A6G7g1PXhxAXxIKAa:bjFIDsyTF0_3q4Jx2akyJbtIgmga" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "token=6941d2c5-f2dd-3323-9bbc-50bc0faaf764&token_type_hint=access_token" https://localhost:9443/oauth2/revoke`
Response: Nothing displayed

3. Introspect the refresh token.
Request:
`curl -k -u admin@wso2.com:admin -H 'Content-Type: application/x-www-form-urlencoded' -X POST --data 'token=6941d2c5-f2dd-3323-9bbc-50bc0faaf764' https://localhost:9443/oauth2/introspect`

Response:
`{"nbf":1581849466,"scope":"openid","active":true,"token_type":"Refresh","exp":1581853066,"iat":1581849466,"client_id":"boaI8x2w701A6G7g1PXhxAXxIKAa","username":"admin@wso2.com@carbon.super"}`

Exchanging this revoked refresh token with an access token was also could be done.

**Comment by ashendes** [comment]
Working on this

**Comment by ashendes** [comment]
> Revoked the refresh token
> Request:
> curl -X PUT --basic -u "boaI8x2w701A6G7g1PXhxAXxIKAa:bjFIDsyTF0_3q4Jx2akyJbtIgmga" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -k -d "token=6941d2c5-f2dd-3323-9bbc-50bc0faaf764&token_type_hint=access_token" https://localhost:9443/oauth2/revoke
> Response: Nothing displayed
> ```

The cURL command used here is a PUT request, hence the reason for the failure. 
The refresh_token gets revoked properly when a POST request is issued as the the endpoint only accepts POST requests [1].

[[1] OAuthRevocationEndpoint](https://github.com/ashendes/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/revoke/OAuthRevocationEndpoint.java#L84)
