### ISSUE TITLE
SCIM2 groups pagination is not implemented

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7662]
#### OS, DB, other environment details and versions:
Db2 11.5
Ubuntu 19.10
Primary user store: Default LDAP
Secondary User store: Db2 11.5 - UniqueIdJDBC
Tenant user
email as username

#### Description

Groups pagination with count and startIndex parameters results in 501 not implemented response.

**Comment by ruwanta** [comment]
Pagination is a wrong approach on REST API as HTTP GET is supposed to be stateless.
What we need to implement is to have filtering with relevant criteria.
And there should be maximum records each list should return.
The UI need to implement such that it uses the filtering to search and get only the required limited set of records.

This has been the modern UI practice.  
Pagination is an old technique and it is not used any more on any modern UI designs.

**Comment by AnuradhaSK** [comment]
Duplicate issue https://github.com/wso2/product-is/issues/9237

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
