### ISSUE TITLE
SCIM2 groups filtering with 'and', pagination and offset is not implemented

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7664]
OS, DB, other environment details and versions:
Db2 11.5
Ubuntu 19.10
Primary user store: Default LDAP
Secondary User store: Db2 11.5 - UniqueIdJDBC
Tenant user
email as username

Description
SCIM GET https://localhost:9443/t/abc.com/scim2/Groups?filter=displayName+ew+User Portal+and+displayName+ew+User Portal

Response is,

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "scimType": "null",
    "detail": "Complex filters are not supported yet",
    "status": "501"
}
```

And also, pagination and offset are not implemented with groups.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
