### ISSUE TITLE
Error in JIT user provisioning under "Prompts for consent" / "Prompt for password and consent" option when Facebook is the federated authenticator

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#7666]
**Description:**
When the user-portal is configured to federated authentication using Facebook and, facebook Idp is configured to JIT provisioning with the option "prompt for consent"/"Prompt for password and consent" the following error occurs. 
![rsz_screenshot_from_2020-02-17_10-42-48](https://user-images.githubusercontent.com/25483865/74626327-565a3f80-5175-11ea-8d99-bfc267084721.png)

**Affected Environment:**

OS: Ubuntu 18.04
DB: PostgreSQL 11.5    

**Steps to reproduce:**
1. Configure Facebook as federated authenticator https://is.docs.wso2.com/en/next/learn/configuring-facebook/
2. Configure JIT provisioning for created IDP (select option "prompt for consent" / "Prompt for password and consent" )
https://is.docs.wso2.com/en/next/learn/configuring-just-in-time-provisioning-for-an-identity-provider/#configuring-jit-provisioning-for-an-identity-provider
3. Go to Service Providers -> List -> user-portal -> Edit -> Local & Outbound Authentication Configuration 
4. Select Federated Authentication as the authentication type and select Facebook from the drop-down. Then update.
5. Go to the user-portal
6. Provide Facebook account credentials

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
