### ISSUE TITLE
Nuxeo server not starting according to instructions given in the documentation

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#7669]
**Description:**
When following the instructions in **Configuring the Nuxeo application** in [1], the server fails to start for latest Nuxeo versions: the following error is shown,

`Error: Could not find or load main class servers.nuxeo-server-10.10-tomcat.conf.logging.properties
`

The instructions worked for Nuxeo Platform **v9.3**.

[[1] Configuring Nuxeo Authenticator](https://docs.wso2.com/display/ISCONNECTORS/Configuring+Nuxeo+Authenticator)

**Related issues:**
[docs-is/issues/1229](https://github.com/wso2/docs-is/issues/1229)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
