### ISSUE TITLE
Invalid OIDC back-channel logout token

### ISSUE THREAD

**Issue by jborgland** [wso2/product-is#7680]
**Description:**
When using OIDC back-channel logout the Identity Server sends a logout token that lacks the _required_ property `events` (which according to the [specification](https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken) _must_ contain the member `http://schemas.openid.net/event/backchannel-logout`). Instead it sends a property with the name `event` (notice the missing _s_) with no value.

The [documentation ](https://docs.wso2.com/display/IS580/OpenID+Connect+Single+Logout) documents the correct behavior so I assume this is a regression of some sorts.

A typical logout token from Identity Server 5.9.0 looks like this:
`eyJ4NXQiOiJaalJtWVRNd05USmpPV1U1TW1Jek1qZ3pOREkzWTJJeU1tSXlZMkV6TWpkaFpqVmlNamMwWmciLCJraWQiOiJaalJtWVRNd05USmpPV1U1TW1Jek1qZ3pOREkzWTJJeU1tSXlZMkV6TWpkaFpqVmlNamMwWmdfUlMyNTYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqZW5zYiIsImF1ZCI6IkRIS3NRd2Exdlhwa1V4WDk3NXN0bU9KdV92NGEiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJldmVudCI6e30sImV4cCI6MTU4MTk2MDEyNywiaWF0IjoxNTgxOTYwMDA3LCJqdGkiOiI2Y2ZmNzYyNC1mNDE1LTRlNzAtYjRiZC0yYWU0YjI2N2M1ODMiLCJzaWQiOiJhMWM1OTEzNi1iN2YwLTRjODgtOTZiYS1hMzkzYzA5YjkzZTAifQ.fUd_GV63llpPlN-rW_WSJMqCTCOiLFr0mzrEcGiKSAEIL_J03dMVIrsQcmGKb9wmTHzN1K91njh-3qXUO6cBig-nE8loc25zBbPKdOTzStYZXFM0xicnr79xcNLL2c7hOm3fZovVqDHnWcV2wyKLkGTkcJh7fSMERz7lSSl2ziqNLy804dhivgj5TnwFMLtWJnzwG8zqrWiV6TkDRaDmrxkAUZHv_baX_W7OIovz-VruokHQ-CHLl0t1HvwlmlBLqs3srw5gXsG_ucndeSdh2vgCjwJnt76jYhGiprArJMLjeK9foOKS_CCFt_JaSZA-FyyaDzK9JoRqZou1qtqAMw`

...which parsed gives the following payload:
`{
	"sub": "jensb",
	"aud": "DHKsQwa1vXpkUxX975stmOJu_v4a",
	"iss": "https://localhost:9443/oauth2/token",
	"event": {},
	"exp": 1581960127,
	"iat": 1581960007,
	"jti": "6cff7624-f415-4e70-b4bd-2ae4b267c583",
	"sid": "a1c59136-b7f0-4c88-96ba-a393c09b93e0"
}`

**Suggested Labels:**
Type/Bug
Component/OIDC

**Affected Product Version:**
5.9.0

**Steps to reproduce:**
1. Register an OIDC client that supports back-channel logout
2. Log into the client using OIDC towards the Identity Server
3. Perform a logout from the Identity Server
4. Observe the logout token being posted to the OIDC client

**Related Issues:**
https://github.com/wso2/product-is/issues/4590

**Comment by piraveena** [comment]
Hi @jborgland,

Thanks for reporting the issue. We could locally reproduce this behavior. We will analyze the root cause of this [1].

[1]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/backchannellogout/DefaultLogoutTokenBuilder.java#L126

**Comment by piraveena** [comment]
@ThaminduR will be looking into this
