### ISSUE TITLE
OIDC back-channel logout token contains an exp claim

### ISSUE THREAD

**Issue by jborgland** [wso2/product-is#7681]
**Description:**
The OIDC back-channel logout token sent by the Identity Server contains an `exp` claim. While not stricly illegal it's not mentioned by the OpenID Connect Back-Channel Logout [specification](https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken) and is discouraged by the Security Event Token [specification](https://tools.ietf.org/html/draft-ietf-secevent-token-00#section-2.1) (which OIDC back-channel logout tokens are supposed to be compatible with).

**Affected Product Version:**
5.9.0

**Related Issues:**
https://github.com/wso2/product-is/issues/7680
https://github.com/wso2/product-is/issues/4590

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
