### ISSUE TITLE
Unable to delete user from Salesforce (Outbound Provisiong)

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7687]
**Description:**
When admin tries to delete user from IS, ideal case is user also deleted from Salesforce. But instead of deleting user, Salesforce changes the username. Please note that user provision is working correctly.

**OS, DB, other environment details and versions:**    
OS : Ubuntu 18.04
Primary Data store : LDAP
Secondary Data store : Postgresql 10.5

**Steps to reproduce:**
- Enable email as user name.
- Register Salesforce as outbound provisioning IS.
- Add user
- Delete user

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
