### ISSUE TITLE
[Improvement] Masking email address in Email OTP page 

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7692]
**Description:**

Currently, in Identity Server, it is not possible to mask email address in Email OTP login page, In a successful authentication flow with Email OTP as the second step, IS redirects to the following URL:

```https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=d20e17db-f6e9-4328-b0f4-c7b30997977c&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=EmailOTP&screenValue=tharakawijekoon2%40gmail.com```

The URL contains the plain email address and in the UI this screenValue email address shown.  Due to security concerns, an option to mask the email address in the redirect URL and the UI would be a good addition.

Note: To get around this security concern it is possible to completely stop showing the email address in the redirect url and email OTP login page by setting the showEmailAddressInUI parameter under the EmailOTP AuthenticatorConfig in the file <IS_HOME>/repository/conf/identity/application-authentication.xml to false as shown below.

```<Parameter name="showEmailAddressInUI">false</Parameter>```

**Comment by mifrazmurthaja** [comment]
Addressed with #7711
