### ISSUE TITLE
Failed Sending Account Confirmation Email after Account Lock for failed attempts

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7698]
Affected: is 5.10 beta 2
Tested in, cluster ubuntu 16.4 & local setup with type = "read_write_ldap_unique_id", H2
**Description:**
Failed Sending Account Confirmation Email after Account Lock for failed attempts

Follow: https://is.docs.wso2.com/en/next/learn/account-locking-by-failed-login-attempts/

**Comment by GANGANI** [comment]
I'm working on this

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
