### ISSUE TITLE
Masking the email address in the email otp display page

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#7711]
**Description:**
Currently, in Identity Server, it is not possible to mask email address in Email OTP login page, In a successful authentication flow with Email OTP as the second step, IS redirects to the following URL:

https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=d20e17db-f6e9-4328-b0f4-c7b30997977c&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=EmailOTP&screenValue=wso2user%40gmail.com

The URL contains the plain email address and in the UI this screenValue email address shown. 

It is possible to completely stop showing the email address in the redirect URL and email OTP login page by setting the showEmailAddressInUI parameter under the EmailOTP AuthenticatorConfig in the file <IS_HOME>/repository/conf/identity/application-authentication.xml to false as shown below.

`<Parameter name="showEmailAddressInUI">false</Parameter>`

But it could be great if we have a configuration to mask the email address like `wso***er@g***l.com`
Or it could be awesome if we can make this mask pattern also configurable

**Comment by azraaroos10** [comment]
Please check the above [PR](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/78). It provides the above described capability.

**Comment by senthalan** [comment]
Fixed with https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/78
