### ISSUE TITLE
[RESTAPI][DevPortal] Regenerating client secret in OIDC flow is not changing the state from revoked

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7712]
**Description:**
If the client secret is in the revoked state when we regenerate, we expect the state to change from revoked to active. In the admin console, you can observe this behaviour but in the new rest endpoint, it is not working  as expected

**Steps to reproduce:**
1. Send a GET request to `api/server/v1/applications/{app-id}/inbound-protocols/oidc` to check the states. If the state is "ACTIVE" then follow the next step or else choose a application which is in the state "ACTIVE".
2. Send a POST request to `api/server/v1/applications/{app-id}/inbound-protocols/oidc/revoke`
3. Now send GET request and check whether the state is changed to "REVOKED"
4. Send a POST request to `/api/server/v1/applications/{app-id}/inbound-protocols/oidc/regenerate-secret`
5. Now again check the state and you can see that the state has not changed.

**Comment by ShanChathusanda93** [comment]
I am currently working on this.
