### ISSUE TITLE
[DOC] Microsoft Dynamics CRM with WS-Federation missing config

### ISSUE THREAD

**Issue by lkokila** [wso2/product-is#7713]
**Description:**
The WS-Trust Security Token Service URL should be configured in "WS-Trust Security Token Service Configuration" configuration of the service provider in the Microsoft Dynamics CRM integration. 

This detail needs to be included in the documentation [1]. 

[1]. https://is.docs.wso2.com/en/latest/learn/logging-in-to-microsoft-dynamics-crm-with-ws-federation/#configure-microsoft-dynamics-crm 

**Suggested Labels:**
Type/Docs

**Affected Product Version:**
IAM-5.9.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
