### ISSUE TITLE
Improvements in deployment.toml on enabling email username 

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#7717]
**Description:**

![image](https://user-images.githubusercontent.com/7569427/74940487-7f99fa80-5417-11ea-881c-0c51897069cf.png)

Current implementation of the `deployment.toml` has some inconsistent keys with the previous XML based configuration.

 As you see in the previous configuration for "enable email based username" `<EnableEmailUserName>` is used in XML. And it is completely different to the new key in the toml file. It's there as `enable_email_domain`. So there can be a user experience issue, where a person with previous experience of the product (Existing/Old Developers) finds difficult to try out/map or search for the property consciously.

Also this config is under `[tenant_mgt]`, which confuses more.

Also after enabling this, it is not applying to the super admin user credentials. And developer needs to update the super admin username separately, but it is not informed to the developer. I would suggest to do a validation there and inform the developer to update the super admin username in this scenario.

**Related Issues:**
https://github.com/wso2/docs-is/issues/1254

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
