### ISSUE TITLE
[RESTAPI][DEVPORTAL] Available authenticators details are not properly exposed

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7719]
**Description:**
In order to implement authentication sequence / sign-on methods, dev-portal needs to know the available authenticators. Currently, there is no way to retrieve information about local authenticators. Thus the following facilitation is needed

Expose all the supported authenticators with details like name, image and type. It would be great to have types like these first factors, second factors, require second factors and social logins.
eg: 

{
&nbsp;&nbsp;&nbsp;&nbsp;        authenticator: "BasicAuthenticator",
&nbsp;&nbsp;&nbsp;&nbsp;        authenticatorId: "QmFzaWNBdXRoZW50aWNhdG9y",
&nbsp;&nbsp;&nbsp;&nbsp;        displayName: "Basic",
&nbsp;&nbsp;&nbsp;&nbsp;        idp: "LOCAL",
&nbsp;&nbsp;&nbsp;&nbsp;        image: "some url",
 &nbsp;&nbsp;&nbsp;&nbsp;       type: FIRST_FACTOR,
    },
{
&nbsp;&nbsp;&nbsp;&nbsp;        authenticator: "FIDOAuthenticator",
&nbsp;&nbsp;&nbsp;&nbsp;        authenticatorId: "RklET0F1dGhlbnRpY2F0b3I=",
&nbsp;&nbsp;&nbsp;&nbsp;        displayName: "FIDO",
&nbsp;&nbsp;&nbsp;&nbsp;        idp: "LOCAL",
&nbsp;&nbsp;&nbsp;&nbsp;        image: "some  url",
&nbsp;&nbsp;&nbsp;&nbsp;        type:SECOND_FACTOR,
}
{
&nbsp;&nbsp;&nbsp;&nbsp;        authenticator: "Identfier-First",
&nbsp;&nbsp;&nbsp;&nbsp;        authenticatorId: "SWRlbnRmaWVyLUZpcnN0",
&nbsp;&nbsp;&nbsp;&nbsp;        displayName: "Identfier First",
&nbsp;&nbsp;&nbsp;&nbsp;        idp: "LOCAL",
&nbsp;&nbsp;&nbsp;&nbsp;        image: "some  url",
&nbsp;&nbsp;&nbsp;&nbsp;        type:"REQUIRE SECOND FACTOR",
}
{
&nbsp;&nbsp;&nbsp;&nbsp;        authenticator: "FacebookAuthenticator",
&nbsp;&nbsp;&nbsp;&nbsp;        authenticatorId: "RmFjZWJvb2tBdXRoZW50aWNhdG9y",
&nbsp;&nbsp;&nbsp;&nbsp;       displayName: "Facebook",
&nbsp;&nbsp;&nbsp;&nbsp;        idp: "FEDERATED",
&nbsp;&nbsp;&nbsp;&nbsp;        image: "some  url",
&nbsp;&nbsp;&nbsp;&nbsp;        type:"SOCIAL",
}

NOTE: for federated authenticators, we will use the `api/server/v1/identity-providers` listing API to get the IDP names.

**Related issue**
improvement to `api/server/v1/identity-providers`  listing API https://github.com/wso2/product-is/issues/7746

**Comment by emswbandara** [comment]
As per the IDP rest API design discussion we had with @prabath , we decided not to include resident IDP information in /identity-providers context. We need to introduce a new API e.g. pi/server/v1/resident in order to retrieve meta information about the Identity Server (similar to OIDC discovery endpoint)
