### ISSUE TITLE
Optimize secondary server startup when optimized for non-embedded DB test runs

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7729]
When the secondary server is started for provisioning test cases, the database components might be reused during env variable related builds. This is fixed with https://github.com/wso2/product-is/pull/7728.

But the above fix applies a configuration toml file change after the secondary server started and restarts again. This could be optimized by applying the change prior to starting the secondary server at the same time. This fix might involve automation framework related improvement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
