### ISSUE TITLE
Token Revoke automatically

### ISSUE THREAD

**Issue by nikhil4326** [wso2/product-is#7731]
We are using WSO2 version **5.5.0**. We have configured the API manager, publisher, store and Identity server. For unauthenticated user, we are using client_credentials grant along with device scope. So every browser session will have its own access_token and 60 min token expiry time.
With unauthenticated user, we are able to load the application. While accessing the other part application(not logged in flow), API's start responding back with unauthorized(401) error. It fails random time and for random API's. It is not failing specific API call or at specific time, it completely random.

Token gets revoked automatically without getting any call from front-end application.
Please help us to understand what could be wrong with our WSO2 configuration.
What would be the steps to fix this issue?

**Comment by ruwanta** [comment]
Please provide technical details to help you. 
This does not have much information to get any information out of the above description.

**Comment by nikhil4326** [comment]
What type of technical details will be required to help you understand the issue?
This is how our set up looks like
1. API Manager is configured to publish all the API's
2. Our front-end application is in angular 7
2. For Anonymous user, we are using client_credential grant with device scope
3. We are receiving access_token and expiry time from identity server and using it as bearer token along with every API call.
4. We are able access API's only when we pass request header: Authorization: Bearer {access_token}

We have refer the below document as i felt it's similar issue. Even that doesn't helped me.
https://medium.com/@technospace/how-to-avoid-getting-intermittent-401s-when-invoking-apis-with-access-tokens-wso2-apim-3e61db9447dd

<img width="515" alt="API-Manager" src="https://user-images.githubusercontent.com/7279864/75114192-0a7a2f80-567a-11ea-8f65-3812cfef8006.PNG">

**Comment by diegovegatedra** [comment]
Hi!, Same problem here. @nikhil4326 Did you resolve it?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
