### ISSUE TITLE
Monitor User Login Sessions - Enter causing abnormal behavior - IS 5.9.0

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7733]
**Description:**
In the Monitor User Login Sessions gadget available in the IS dashboard, when hitting the enter after typing the username to search for the user sessions, it gives an error message, "Missing or Malformed URL parameter". But the search button works fine.

**Affected Product Version:**
IS 5.9.0

**Steps to reproduce:**
1. Go to "**Monitor Users Login Sessions**" in the IS Dashboard.
2. Type any username and hit **Enter**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
