### ISSUE TITLE
Always getting the local IP address when IS server is fronted by LB - Monitor Users Login Sessions - IS 5.9.0

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7740]
**Description:**
In the **Monitor Users Login Sessions** gadget available in IS 5.9.0, the IP address field always displays the local IP address (127.0.0.1) when the IS server is fronted with a load balancer/ reverse proxy.
However, as a possible solution, we can set X-Forwarded-For or similar header in the LB and will be able to retrieve the remote IP address. Hence, the logic would be as follows.
1. Check if X-Forwarded-For or similar header exists. If exists, get the IP from that header.
2. Otherwise, use getRemoteAddr function to get the IP.

The above logic is already implemented in the getClientIpAddress function at org.wso2.carbon.identity.core.util.IdentityUtil. 

However, in the implementation of Monitor Users Login Sessions gadget available in the IS dashboard, it uses IDN_AUTH_SESSION_META_DATA table to retrieve the IP adress and there the IP address is stored directly using the getRemoteAddr function rather than using the above logic. (storeSessionMetaData function in org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler).
Therefore setting the X-Forwarded-For or similar header will not work on this gadget.

The actual function used to get the session details.
https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/internal/impl/UserSessionManagementServiceImpl.java#L166

The function used to retrieve session details
https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/dao/impl/UserSessionDAOImpl.java#L43

**The function used to store session details including the IP address - Need to be fixed**
https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java#L628

Currently, the IP is obtained as follows. (This will be stored in the database)
`String ip = request.getRemoteAddr();`

The correct implementation of getting the IP address
https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java#L973

By using the above implementation, the IP should be obtained as follows.
`String ip = IdentityUtil.getClientIpAddress();`

**Affected Product Version:**
WSO2 IS 5.9.0

**Comment by emswbandara** [comment]
@mifrazmurthaja thanks for the detailed explanation. :) can you please update the steps to reproduce the issue as well?

**Comment by mifrazmurthaja** [comment]
**Prerequisites**
Front the IS with an LB/ Reverse Proxy

**Steps to Reproduce**
1. Register an SP in WSO2 IS (SAML, OAuth, etc.)
2. Create a user Alex.
3. Log in to the SP through WSO2 IS using Alex' credentials.
4. Go to **Monitor Users Login Sessions** section of the WSO2 IS dashboard with admin credentials.
5. Find the session details of the user Alex by entering the username: Alex and click on the search button.
6. The session created above will be listed out here.
7. Have a look at the IP address of the session.

In the above scenario, if the IS is fronted by an LB, the IP address will always be 127.0.0.1 even if the session is created from a different client as request.getremoteaddr() returns the IP address of the client or the **last proxy that sent the request.**
