### ISSUE TITLE
getApplicationBasicInfo SOAP service not  returns applicationResourceId.

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7743]
Admin service getApplicationBasicInfo [1], should return applicationResourceId as a public branch fix of issue [2]. 

![image](https://user-images.githubusercontent.com/39077751/75151476-c7c55f80-572c-11ea-87ec-b47e8cba4761.png)

[1] IdentityApplicationManagementService, IdentityApplicationManagementService, https://localhost:9443/services/IdentityApplicationManagementService/ 

[2] https://github.com/wso2/product-is/issues/6420

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
