### ISSUE TITLE
Default authenticators details are not listed in Identity Provider list api

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7746]
**Description:**
 In order to implement authentication sequence / sign-on methods, dev-portal needs to know the available authenticators.

 Federated authenticator details are not simple to get and many API calls are needed to determine their details. 

Thus in the `api/server/v1/identity-providers` list endpoint,  add the default authenticators details. Then we can easily map them with the available federated authenticator details. 

May we can use filter kind of function to retrieve the default authenticator details along with the existing listing endpoint.

**Comment by Sathiyakugan** [comment]
I am taking this issue

**Comment by emswbandara** [comment]
@inthirakumaaran you can get the default authenticator by calling api/server/v1/identity-providers/{idp-id}/federated-authenticators endpoint. In api/server/v1/identity-providers we are providing only the basic information of IDP as per the API design.

**Comment by emswbandara** [comment]
we have decided to introduce requiredAttributes query param to serve this purpose. @sarubi is working on this.

**Comment by emswbandara** [comment]
fixed with https://github.com/wso2/identity-api-server/pull/116
