### ISSUE TITLE
SP management rest endpoint is missing a configuration for OIDC protocol

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7747]
**Description:**
Endpoint `/api/server/v1/applications/{app-id}/inbound-protocols/oidc` is missing the following new config that added to admin console recently for OIDC configurations

![image](https://user-images.githubusercontent.com/17597685/75173363-c576fb80-5754-11ea-8d7d-bfcdb3a8280c.png)

**Comment by mevan-karu** [comment]
I am working on this issue

**Comment by isuruirj** [comment]
This needs to be fixed in IS-5.11.0 as well.
