### ISSUE TITLE
Management console allows user to select dummy user role while adding approval step - add workflow 

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7751]
**Description:**
while adding user roles for approval step when create workflow, management console allows user to add repetitive roles.

**Affected Product Version:**
IS 5.10.0 beta4
**OS, DB, other environment details and versions:**    
Default
**Steps to reproduce:**
- [Doc](https://is.docs.wso2.com/en/next/learn/adding-a-workflow-engine/)
- Create a workflow
- Add approval step
- Try to add more admin/manager roles

![issue](https://user-images.githubusercontent.com/25488962/75217055-eb83b680-57bb-11ea-845b-77b9b51c3c6b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
