### ISSUE TITLE
[DOC] Application rest APIs has no permission specified

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#7752]
**Description:**
In [Doc](https://is.docs.wso2.com/en/next/develop/application-rest-api/#/Applications/getAllApplications
) no permission specified. But required permission is /permission/admin/manage/identity/applicationmgt/view

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
