### ISSUE TITLE
In Saml2bearer Flow for a federated non provisioned user trying to access SCIM APIs needs proper Error handling

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#7756]
**Environment**
IS 5.10.0 beta4 snapshot
H2 Embedded LDAP 

**Steps to Reproduce**
1. Offset a IS pack with offset = "1" and Configure it as a Secondary IS to register as a IDP in Primary IS[1].
SP > OAuth with callback url as https://localhost:9443/commonauth.
2. Add a User for the secondary IS created in step 1
3. Get another IS pack as primary IS and register travelocity as a SP [2]
4. Register secondary IS created in step 1 as a IDP in primary IS with OAUTH2/Openid 
5. Register playground as a SP in primary IS and get the client id and secret.
6. In travelocity.properties file 
EnableOAuth2SAML2Grant=true
Add the client id and secret taken in step 5 for 
OAuth2.ClientId
OAuth2.ClientSecret
7. Try the saml2 bearer grant flow by accessing http://wso2is.local:8080/travelocity.com 
8. Obtain the access token for the federated user

**Observation**
When the user is a federated user and obtains the saml2 bearer access token for the federated user and try to access the SCIM API as the user is not provisioned it should say that the User is not authenticated. But currently when trying to access the SCIM endpoint to get Users if the federated user is not provisioned it is giving the below response
**Request**
`curl -v -k --header "Authorization: Bearer 9a343551-32bb-3375-813c-e1f1939dede4" https://localhost:9443/wso2/scim/Users -i
`
**Response**
`{"Errors":[{"code":"500","description":"User is not authorized to perform provisioning"}]}`

As we are not trying user provisioning here this error response message needs to be handled properly.

[1]. https://medium.com/@methmas/federated-authentication-with-wso2-identity-server-with-openid-protocol-and-wso2-playground2-app-212151d66f7a
[2]. https://is.docs.wso2.com/en/next/learn/setting-up-a-saml2-bearer-assertion-profile-for-oauth-2.0/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
