### ISSUE TITLE
UMA Token Introspection fails

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#7757]
After obtaining the RPT with the fix done for https://github.com/wso2/product-is/issues/7634, I have tried to make a token introspection request as instructed at
https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#get-the-token-introspection

It fails with the status code: 401 (Unauthorized)

**Comment by AnuradhaSK** [comment]
I'm working on this

**Comment by AnuradhaSK** [comment]
Token introspection is done via oauth2/introspect endpoint and its scope is defined as `"internal_application_mgt_view"`. However, the PAT is obtained at https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#obtain-the-protection-api-access-token-pat using `uma_protection` scope. According to the UMA spec, 'uma_protection' scope is required to [obtain a permission ticket](https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#obtain-a-permission-ticket).

Status code: 401 (Unauthorized) can be eliminated at
https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#get-the-token-introspection step, by obtaining PAT with `"internal_application_mgt_view"` scope.

Therefore, [this](https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#obtain-the-protection-api-access-token-pat) should be changed as 
`curl -u <CLIENT_ID>:<CLIENT_SECRET> -k -d "grant_type=password&username=kate&password=kate123&scope=uma_protection internal_application_mgt_view" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/oauth2/token`

**Comment by Abilashini** [comment]
Can we please update the doc with the findings
