### ISSUE TITLE
Issue with customising Identity Data Store

### ISSUE THREAD

**Issue by godwinamila** [wso2/product-is#7760]
**Description:**
There is a requirement to make selected identity claims works with underline user store and others with JDBC. So we can write a custom Identity Store to selectively call Userstore Identity store and JDBC Identity Store. Please find a sample code snippet.

jdbcIDUserStore.store(claimsDO, userStoreManager); // Storing JDBC claims
ldapIDUserStore.store(claimsLdapDO, userStoreManager); // Storing LDAP claims

But InMemoryIdentityDataStore [1] changes the object passing to the method and it leads UserStoreBasedIdentityDataStore to try to persist other identity claims not only selected identity claims.

[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.governance/src/main/java/org/wso2/carbon/identity/governance/store/InMemoryIdentityDataStore.java#L104

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
