### ISSUE TITLE
SCIM has been enabled by default and can't be disabled anymore

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#7769]
**Description:**
From IS-5.10.0 onwards scim will be enabled by default with \[1] and we can't disable it anymore. Hence we need to mention this in our migration doc.

\[1] https://github.com/wso2/carbon-kernel/pull/2535
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Abilashini** [comment]
Added at https://is.docs.wso2.com/en/next/setup/migrating-what-has-changed/
