### ISSUE TITLE
SCIM2 schema endpoint does not return enterprise user schemas

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#7770]
**Description:**
The schema endpoint which introduced with #212 doesn't provide the schemas in `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` dialect. Since we are dynamically populating the user profile(new developer portal) by mapping the meta details from the schema endpoint, we need to support the enterprise user schemas in order to populate the fields such as organization, department, etc.

**Comment by madurangasiriwardena** [comment]
Subtask of https://github.com/wso2/product-is/issues/5284

**Comment by darshanasbg** [comment]
@mevan-karu We have implemented this, right?

**Comment by mevan-karu** [comment]
@darshanasbg yes we have implemented this. Please find the related PRs below;
https://github.com/wso2/charon/pull/279
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/257
