### ISSUE TITLE
Signing algorithm in SAML protocol configuration is not getting updated through rest api

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7786]
**Description:**
 Through the endpoint `/api/server/v1/applications/{app-id}/inbound-protocols/saml` it  is not possible to update the signing algorithm for response/assertion signing.

![image](https://user-images.githubusercontent.com/17597685/75524248-8b974500-5a33-11ea-87ea-9721ca776ada.png)

**Steps to reproduce:**

1. Send a GET request to /api/server/v1/applications/{app-id}/inbound-protocols/saml to check the current signing algorithm
2. Send a PUT request to /api/server/v1/applications/{app-id}/inbound-protocols/saml with different signing algorithm like http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
3. Again send GET request to `/api/server/v1/applications/{app-id}/inbound-protocols/saml` and check whether the signing algorithm has changed

**Comment by emswbandara** [comment]
this is assigned to @AnuradhaSK

**Comment by jcgarciaa** [comment]
This issue is also observed on version 5.10.0
