### ISSUE TITLE
passwordExpiryInDays IDP property in Management Console ignored - Password Reset Enforcer

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7787]
**Description:**
As mentioned in [Password Reset Enforcer](https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md#configuring-the-expiration-policy), in IS 5.9.0, the below properties configured in the Resident Identity Provider are ignored.
- Password Expiry In Days
- Enable Sending Email Notifications
- Prior Reminder Time In Days

Instead, it always takes the event property configurations available in deployment.toml (actually from identity-event.properties) as configured below even though the above configurations are getting stored in IDP_METADATA table.
`[event_handler.properties]
    passwordExpiryInDays= 20
    enableDataPublishing= false
    priorReminderTimeInDays= 0`

By looking at the code [PasswordResetEnforcer.java#L273](https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/policy/password/PasswordResetEnforcer.java#L273) below, it shows that it is getting the property as Identity Event Property as explained above.
`// Getting the number of days before password expiry in days
        String passwordExpiryInDaysProperty = PasswordPolicyUtils.getIdentityEventProperty(tenantDomain,
                PasswordPolicyConstants.CONNECTOR_CONFIG_PASSWORD_EXPIRY_IN_DAYS);`

Ultimately, it calls the [getModuleConfigurations](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-event/org.wso2.carbon.identity.event/src/main/java/org/wso2/carbon/identity/event/IdentityEventConfigBuilder.java#L213) function in the IdentityEventConfigBuilder.

**Affected Product Version:**
IS 5.9.0

**Steps to reproduce:**
- Configure as mentioned in the [Password Reset Enforcer](https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/blob/master/docs/config.md#configuring-the-expiration-policy) and change the value of Password Expiry In Days to a different value other than 30 (Since this is the default value) such as 2 days.
- The above configuration will not be considered when a user tries to log in to an SP whose password is updated 3 days ago (Manually changed the Last Password Update claim).

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
