### ISSUE TITLE
Invalid callback in the confirmation URL when workflows are enabled

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7793]
Steps to reproduce.

1. Enable self-registration with email confirmation
2. Access user-portal and register new user
3. The user gets an email and upon click, account get verified.
4. Log in to the management console and enable a workflow engagement for 'Add User' operation where `admin' role is authorized to approve the task.
5. Access user-portal and register a new user.
6. User does not get the confirmation email yet.
7. Login to user-portal as a user with 'admin' role.
8. Approve the pending task for 'Add User'
9. The newly registered user gets an email and upon click, account verification fails.
10. The reason is {{callback}} parameter of the confirmation link is not set at this point.
![email-confirm](https://user-images.githubusercontent.com/5061791/75547201-69f88680-5a50-11ea-98c0-5bab3eec3839.png)

Better, if we can add a default value or remove {{callback}} when it cannot be found.

As a workaround, we can remove `&amp;callback={{callback}}` from the `AccountConfirmation` email template which is not ideal.

**Comment by yuniet87** [comment]
The callback is generated without problems and the user validates correctly but when we press OK in the confirmation message and try to log in from the redirection that is done, it gives an error:
![redirect](https://user-images.githubusercontent.com/50919882/91067916-83464e00-e601-11ea-8601-6fe0b6550cd3.jpg)
Later, if we close that redirection and try to access the user-portal normally, everything works fine and the new user can access without difficulty.
