### ISSUE TITLE
Issuing OAuth2 access tokens with JWT returns active response in introspection for any previously issued token

### ISSUE THREAD

**Issue by Kktheoch** [wso2/product-is#7795]
**Description:**
When issuing a JWT OAuth token using client_credentials grant any previously issued tokens are still active until cache expiration.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** 5.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create a Service Provider with OAuth2 client_credentials grant type.
2. Issue an access token with a scope using client ID/client Secret of the SP.
3. Issue a second access token using the same parameters as 2.
4. Call OAuth2 /introspect endpoint with the issued tokens. 
The token you issued first will be inactive after cache expiration but will be active until the timeout expires.

This was tested on a clean installation of IS 5.9.0 with a cache expiration timeout of 300 seconds.

**Related Issues:**

**Comment by ashendes** [comment]
Working on this.

**Comment by andrewiethoff** [comment]
@janakamarasena 
We found that this behaviour is different from previous versions.
Is there a reason why previously issued tokens need to be invalidated? Is this defined in the OAuth2 standard?

I think that this has broken several use-cases which are important for us:
1. Logging in twice with the same user is not possible any longer (as we have several applications using the same identity server, some are used on mobile devices others on PC web browsers). So the same person needs to be logged in simultaneously on two devices.
2. Account sharing (which is done by our clients and which is totally fine in our use case) is also not possible any longer

Would be the result of this fix, that the user with latest login is able to work, all other sessions are closed?
If so, please think about undoing that fix or at least offer a switch in UI or config to change the behaviour of this function. 

Thank you for your attention!

**Comment by janakamarasena** [comment]
This was always the behaviour of jwt tokens in the Identity Sever. But due to an cache clearing bug only the previous token was active. If you check, the previous token will only be active until the cache timeout.

It is advised to use a separate service provider for  each device type. We do have plans to revise the current internal token logic which may stop the need to revoke the previous token but we dont have a timeframe for this improvement as of now.

Please feel free to open a git issue with your request.
