### ISSUE TITLE
Remove printing all user claims in audit logs, when a user logs in.

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#7797]
**Description:**
Currently, we print all the claims of user, in audit logs, when he logs in[1].
Ideally audit logs should print "what changed,when and why changed" aspects.
Printing all the user claims, when a user logs in does not serve the purpose of audit logs.
Therfore we need to remove all user claims getting printed when user logs in. This will help to reduce audit log filling up as well.

[1]https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserManagementAuditLogger.java#L294

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
