### ISSUE TITLE
SCIM2 User endpoint filtering combined with pagination does not work with PostgreSQL database.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7798]
**Description:**
SCIM User endpoint filtering combined with pagination does not work with PostgreSQL database.

**Suggested Labels:**
SCIM

**Affected Product Version:**
IS-5.8.0

**OS, DB, other environment details and versions:**
DB - PostgreSQL
IS-5.8.0

**Steps to reproduce:**

- Add a PostgreSQL database as the primary user store. 
- Create a few users and roles and assign the users to the roles
- Use queries like the following which will paginate and filter the user via the role/group

```
curl --location --request GET 'https://localhost:9443/scim2/Users?startIndex=1&count=12&domain=PRIMARY&filter=groups+EQ+Physicians' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```

**Analysis**

When the above SCIM request is used the following Query is executed in the underlying JDBC PostgreSQL database which gives a syntax error when executed.
```
SELECT DISTINCT UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR INNER JOIN UM_USER U ON R.UM_ID = UR.UM_ROLE_ID AND UR.UM_USER_ID =U.UM_ID WHERE R.UM_TENANT_ID = ? AND U.UM_TENANT_ID = ? AND UR.UM_TENANT_ID = ? AND R.UM_ROLE_NAME = ? ORDER BY UM_USER_NAME ASC LIMIT ? OFFSET ?; 
```

**doc links**
https://docs.wso2.com/display/IS580/Using+the+SCIM+2.0+REST+APIs#UsingtheSCIM2.0RESTAPIs-GET/GetUsers(UserListing/Filtering)

**Comment by tharindu-bandara** [comment]
This issue can be closed, once a kernel version contains the fix is released.
