### ISSUE TITLE
SCIM2 User endpoint filtering users by multi attributes does not work with PostgreSQL database.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7801]
**Description:**
SCIM2 User endpoint filtering users by multi attributes does not work with PostgreSQL database.

**Suggested Labels:**
SCIM

**Affected Product Version:**
IS-5.8.0

**OS, DB, other environment details and versions:**  
Primary DB - PostgreSQL
IS-5.8.0  

**Steps to reproduce:**

- Add a PostgreSQL database as the primary user store.
- Create a few users and roles and assign the users to the roles
- Use queries like the following:

```
curl --location --request GET 'https://localhost:9443/scim2/Users?filter=groups+EQ+Physicians+and+groups+EQ+Patients' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```
Cause for the issue: SQL syntax error

**Related Issues:**
https://github.com/wso2/product-is/issues/7798

**Comment by tharindu-bandara** [comment]
This issue can be closed, once a kernel version contains the fix is released.

**Comment by pulasthi7** [comment]
Closing as per @tharindu-bandara 's comment as new kernel release was done
