### ISSUE TITLE
Password Recovery doesn't work

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7803]
Steps to reproduce.
1. Enable both password recovery by email and challenge questions.
2. Login to user-portal and set answers to challenge questions.
3. Logout and try password recovery with email
4. An email with a recovery link is received to the user's email.
5. Click link
6. Enter a new password and submit.
7. **Nothing happens** and stuck at below page.
![password](https://user-images.githubusercontent.com/5061791/75606422-8ceb6f00-5b12-11ea-9c27-66ba759a1b63.png)
8. Try password recovery with challenge questions. 
9. Provide correct answers to challenges
10. Enter a new password and submit at the password reset page.
11. Same as #7 nothing happens.

**Comment by ayshsandu** [comment]
This is not reproduced in the latest 5.10.0-beta4-SNAPSHOT.

**Comment by IsuraD** [comment]
Resolved since this is not reproducible.
