### ISSUE TITLE
BirthDay is not showing in user-portal when enables by default.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7807]
01. Login to management console.
02. User 'Claims' > 'List' > 'http://wso2.org/claims'
03. Locate `http://wso2.org/claims/dob' and make it `Supported by Default`
04. Login to user-portal.
05. Ideally 'Birthday' should come under user info, but it is not showing.

Cause can be not having a scim2 claim mapping for 'BirthDay'. Ideally all the user attributes under http://wso2.org/claims should have ability to be able to view from user-portal. (unless special case)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
