### ISSUE TITLE
[Improvement] Persist secondary user store configuration in the database

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7817]
**Description:**
In cases where Identity server is running in a containerized environment, creating secondary userstores or tenants on the fly creates files in the filesystem which will not be persisted without a volume mount. 

As an Improvement to get around this the configurations can be persisted to a database and read from the database.

**Suggested Labels:**
Improvement

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
