### ISSUE TITLE
the UserNameAttributeClaimUri does not work probably when  users login with Email and UID in WSO2 Identity Server with CAS

### ISSUE THREAD

**Issue by naderjafari** [wso2/product-is#7837]
**Description:**
Enabling multiple attribute to let users login with Email and UID in WSO2 Identity Server with CAS

**Suggested Labels:**
Question,Multiple attribute

**Affected Product Version:**
WSO2 Identity Server Version : 5.9.0 

**Steps to reproduce:**

We install WSO2 Identity Server Version : 5.9.0 and configure an Service Provider to login with CAS

We need to login with email/uid in login page.

For this purpose, i change bellow configuration in deployment.toml based on this Document : https://is.docs.wso2.com/en/latest/learn/managing-user-attributes/

```
[user_store]
user_name_attribute = "uid"
multiple_attribute_enable = true
type = "read_write_ldap"
connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated
user_name_search_filter = "(&amp;(objectClass=person)(|(uid=?)(mail=?)))"
username_java_script_regex = '^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
username_java_regex='^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'


[authentication.authenticator.basic] 
name ="BasicAuthenticator"
enable=true
UserNameAttributeClaimUri = "http://wso2.org/claims/username"
```

In this situation everything is okay and users could login with uid and emails.

But my problem is: when users login with Emails the Username attribute that send from WSO2 Identity Server to my Service is Email and When users login with uid , the user attribute is uid.

In my CAS Client side when a single user login with email/uid detected as Two different user that is wrong.

i think the UserNameAttributeClaimUri does not work probably.

Also i change bellow configuration in service provider:

Claim configuration in my Serviece Provider

Local & Outbound Authentication Configuration

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
