### ISSUE TITLE
Password Validation for Compromised passwords

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7852]
**Description:**

User-provided passwords should be checked against compromised password databases in order to avoid account takeover.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
