### ISSUE TITLE
Docs on Configuring Tenant-Based Adaptive Authentication need to be updated

### ISSUE THREAD

**Issue by Sathiyakugan** [wso2/product-is#7854]
**Describe the Issue:**
I have tried to do Tenant-Based Adaptive Authentication demo using the docs described in this link   https://is.docs.wso2.com/en/5.9.0/learn/configuring-tenant-based-adaptive-authentication/

I could not signin to the application and I got the error **Application you are trying to access does not allow users from your organization.**
![Screenshot from 2020-02-24 16-36-19](https://user-images.githubusercontent.com/25485726/75147902-66998e00-5724-11ea-976f-4b750b4d1b96.png)

Then I try to sign in using the user portal : I got the same error

Then I try to add the /t/123.com/ user-portal
It was working . But the demo app was not developed to handle this multiple situations

**How To Reproduce:**
Docs should be updated to inform this to the users.

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
