### ISSUE TITLE
[IDP REST API] - Improvements federated authenticator meta attributes

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#7872]
### Description
Currently, we can get the metadata of a federated authenticator via `https://localhost:9443/api/server/v1/identity-providers/meta/federated-authenticators/{authenticator-id}` with a response similar to the following.

```
{
    "authenticatorId": "T3BlbklEQ29ubmVjdEF1dGhlbnRpY2F0b3I",
    "name": "OpenIDConnectAuthenticator",
    "displayName": "openidconnect",
    "properties": [
        {
            "key": "OAuth2TokenEPUrl",
            "displayName": "Token Endpoint URL",
            "description": "Enter OAuth2/OpenID Connect token endpoint URL value",
            "type": "STRING",
            "displayOrder": 4,
            "regex": ".*",
            "isMandatory": true,
            "isConfidential": false,
            "options": [],
            "defaultValue": "",
            "subProperties": []
        }
    ]
}
```

### Suggestion

1. `description` attribute may sometime contain a value which can be used as a **hint for the input field** when presenting in the front end. Sometimes it may contain a value that can be used as the **placeholder value of the respective input field**. Hence it's better if we can have a clear separation for this concern. i.e. two attributes `description` and `placeholderValue`.
2. `readOnly` property is required for some properties.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
