### ISSUE TITLE
[IDP REST API] - OIDC and SAML authenticators are not displayed in the federated authenticators list of a new IDP

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#7873]
### Description
`OIDC` and `SAML` authenticators are not displayed in the federated authenticators list of a new IDP.
But other authenticators such as `MicrosoftWindowsLiveAuthenticator` will be shown.
However if we have configured it already (i.e. through the management console), then it will be displayed under the authenticators list. This needs to be fixed.

### Steps to reproduce

1. Create a new IDP.
2. Retrieve the federated authenticators list for the IDP via `https://localhost:9443/api/server/v1/identity-providers/{idp-id}/federated-authenticators/`.

**Comment by emswbandara** [comment]
@gayashanbc can you please attach the IDP create request and the responses you got?

**Comment by emswbandara** [comment]
Im unable to reproduce this behavior.

Steps I followed.

Create a new Identity Provider using POST request to /identity-providers endpoint. Note that created identity provider does not have any federated authenticators.
Try to retrieve created IDP federated authenticators using identity-providers/1181ab0b-ff13-4efc-9fe8-acce15fa7ac8/federated-authenticators
Empty response is given as expected.

However please note that if we create IDP from management console and try to retrieve the authenticators via REST API the mentioned behavior is reproduced and that is expected. Therefore our recommendation is to use the REST API for IDP creation as well.
