### ISSUE TITLE
SAML User Session is not cleared on updateCredentialByAdmin service call.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#7875]
**Description:**
1. The user is logged in to a SAML application with the his credentials and has a valid samlssoTokenId set. 
2. Then the admin user triggers the **updateCredentialByAdmin** admin service call and updates the user's password.
3. Ideally, the user session should be invalidated in this case, the logged-in user's session is not cleared.

This is because the _samlssoTokenId_ is returned with a null value when the updateCredentialByAdmin admin service call is triggered. Ideally, a samlssoTokenId value should be returned and the following flow should be executed to trigger the user single logout 

**Affected Product Version:**
IS 5.9.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
