### ISSUE TITLE
User stores meta types endpoint is returning empty arrays, and an error when there are no secondary user stores

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#7877]
**Description:**
The `/userstores/meta/types/{type-id}` endpoint is 
- returning an empty array for all types except the JDBC User Store manager. 
- returning a 404 error when there is no secondary user store configured.
```
code: "SUS-60003"
message: "Resource not found."
description: "Unable to find a required resource for this request"
traceId: "40b08bbd-0474-4dda-a7ff-0a9d1d98f29d"
```
**Affected Product Version:**
5.11.0 m8

**Comment by AnuradhaSK** [comment]
For point 1:

`/userstores/meta/types/{type-id}` is tested for Read Write LDAP userstore and it works properly.

![usersore-type](https://user-images.githubusercontent.com/25483865/77094922-30a1ae00-6a33-11ea-80fb-b1f006092b88.png)

For point 2:

`returning a 404 error when there is no secondary user store configured.` this is the desired result for the request.  "This API provides the capability to retrieve the properties of the secondary user store of a given class name." If there is no such secondary user store is configured, 404 should be returned.

**Comment by thivi** [comment]
It seems like the API endpoint returns the list of user stores belonging to the requested type.

However, there is a requirement to get the properties associated with every user store type. For example, the connection details will have different properties for different types.

Therefore, we need an endpoint to get the properties of each type so that properties the user needs to fill can be shown.

**Comment by emswbandara** [comment]
@AnuradhaSK the meta endpoint of userstores should return the set of properties of a given userstore class name even if there is not secondary userstore configured for it. AFAIR this was the initial purpose of providing a meta endpoint for the userstore API. @Kanapriya any thoughts?
