### ISSUE TITLE
Implement sorting and filtering for the user store and claim management endpoints 

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#7878]
**Description:**
The **user stores** endpoint and the **claim management** endpoint don't support **filtering** and **sorting** as yet. These two endpoints are required to implement sorting and filtering in the developer portal.

**Comment by darshanasbg** [comment]
If, implementing these take lots of cycles compared to fixing these in UI itself, better to do that way, as filtering\sorting are not critical for these APIs as in general.
