### ISSUE TITLE
Meaningful Authenticator Config tab name

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#7881]
**Description:**
Right now the Authenticator config tab is named as "Sign-on method". Usually, sign-on means onboard/engage/register in. It is kind of confuses people. The proper name would be "Sign-in methods" or Authenticator config.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
5.11.0-m8

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
