### ISSUE TITLE
Application Template REST API

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#7882]
Track implementations related to the Application Template REST APIs

**Comment by emswbandara** [comment]
Re-opened to track integration test + doc PRs

**Comment by pamodaaw** [comment]
PRs related to each task,
- Implement the template manager backend service - https://github.com/wso2/carbon-identity-framework/pull/2827
-  Implement the application template REST API - https://github.com/wso2/identity-api-server/pull/125
-  Write the integration tests - https://github.com/wso2/product-is/pull/7981
