### ISSUE TITLE
Default value for secondary UserStore password encryption - Not backward compatible

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#7884]
**Description:**
The issue [7355](https://github.com/wso2/product-is/issues/7355) is not backward compatible as it causes the flow to break when the secondary user store is saved in .enc format.
The default value defined for the UserStorePasswordEncryption is InternalKeyStore. Hence, by default, it'll use the InternalKeyStore to decrypt the user store password.

Therefore, it is better to change the default Keystore of decryption to Primary Keystore to avoid any interruptions in the flow.
in carbon.xml:
`<UserStorePasswordEncryption>KeyStore</UserStorePasswordEncryption>
`
in default.json:
`"keystore.userstore_password_encryption": "KeyStore",
`
As a suggestion, following logic can be used.
`{% if keystore.userstore_password_encryption is defined %}
<UserStorePasswordEncryption>{{keystore.userstore_password_encryption}}</UserStorePasswordEncryption>
{% endif %}`

If we use the above logic, the UserStorePasswordEncryption configuration will not be exist in the carbon.xml and hence, it'll use the Primary keystore for the userstore.

**Affected Product Version:**
WSO2 IS 5.9.0

**Steps to reproduce:**
1. Use different keystores for Primary and Internal.
2. Save the user store file in .enc format without encrypted="true" is set.
3. That's it, when the file is converted to xml format, it cause an exception: ERROR {org.wso2.carbon.user.core.config.UserStoreConfigXMLProcessor} - encryption of Property=ConnectionPassword failed org.bouncycastle.jcajce.provider.util.BadBlockException: unable to decrypt block

**Comment by rksk** [comment]
Actually, this is not backward compatible because we are enforcing a configuration change for an already released version (5.9.0) because this configuration was not there previously and the code had used primary keystore by default. Now we are enforcing it to use internal keysotore.

So, it will break decrypting already encrypted data since we are referring to a different keystore now.

**Comment by janakamarasena** [comment]
Closing the issue as not affected in current master.
