### ISSUE TITLE
Issue with IDP Pagination

### ISSUE THREAD

**Issue by sarubi** [wso2/product-is#7886]
**Description:**
**Issue 1 with Limit param:**
Steps to reproduce:
https://is.docs.wso2.com/en/5.10.0/develop/application-rest-api/
[1] Create few IDPs such as 4.
[2] List the IDPs with-param '"limit"  =3, in the response, we'll only have 2 IDPs even though we have 4 total IDPs. 
![Screenshot from 2020-03-16 10-15-50](https://user-images.githubusercontent.com/20983809/76726974-bcd47c80-6778-11ea-84e2-9c969a3fd516.png)
Reason:
When we obtain DB query result it contains resident IDP as well, later we skip to add the resident IDP  in IDP listing. Since resident IDP shouldn't get listed in IDP listing we need to modify the DB query accordingly or handle properly. 

**Issue 2 with Offset Param:**
Same as issue 1, create 4 IDPs and try to List IDP with pagination by providing offset: 
Limit:3 offset:1, 
we will obtain 3 IDP as expected behaviour but in the response, StartIndex set to 2 even though I provided offset as 1. 
![Screenshot from 2020-03-16 11-38-52](https://user-images.githubusercontent.com/20983809/76727736-e1315880-677a-11ea-8513-d30927da78de.png)
Always start index set in the results as offset +1. But in other Endpoint such as application endpoint set the start index as the provided offset.

**Comment by emswbandara** [comment]
startIndex of the pagination result should identify the index of the first element in a page. Therefore it should be offset + 1 always. E.g. refer https://github.com/wso2/identity-api-user/blob/master/components/org.wso2.carbon.identity.api.user.application/org.wso2.carbon.identity.rest.api.user.application.v1/src/main/java/org/wso2/carbon/identity/rest/api/user/application/v1/core/ApplicationService.java#L131

**Comment by sarubi** [comment]
For the end-user isn't it confusing? in the input param, we use offset and in the response, we provide start index? why can't we use both places as start index like SCIM? 
BTW, I tired application listing, 
https://{{server-url}}/t/{{tenant-domain}}/api/server/v1/applications?limit=2&offset=3
where the response is alwasy offset = start index, 

![Screenshot from 2020-03-16 15-52-35](https://user-images.githubusercontent.com/20983809/76746991-6bd77f00-679e-11ea-9fc0-c862adfe566e.png)

**Comment by emswbandara** [comment]
@sarubi that is the approach we finalized for the Identity Server rest APIs. Please refer [1] for more information. I guess we need to fix that in application listing.

[1] "[Dev] Resource listing parameters for Identity Server REST APIs"
