### ISSUE TITLE
Error in Pickup dispatch and Pickup manager sample applications when configuring as service providers

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#7891]
**Description:**
I am trying to set up SAML SSO for pickup dispatch and pickup manager applications using WSO2 IAM 5.10.0 rc2 pack. 
I downloaded sample applications from [here](https://github.com/wso2/samples-is/releases/tag/v4.2.0). 
And did configurations as mentioned [here](https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-saml2-web-app-pickup-dispatch-webapp). 

However, when I try to login to pick up dispatch, instead of directing me to the IS login page it gives me the error page attached. The same happens with the pickup manager as well. 

<img width="1792" alt="Screen Shot 2020-03-16 at 10 36 06 AM" src="https://user-images.githubusercontent.com/10182430/76732834-9537e100-6785-11ea-9fdd-efb697207f92.png">

**Comment by krishnilak** [comment]
@janakamarasena Please advice

**Comment by deshankoswatte** [comment]
Hi @janakamarasena,

This is most probably clash between the classes in OpenSAML2 and OpenSAML3. I will work on this and fix it.

**Comment by janakamarasena** [comment]
This is resolved in the apps released in sample-is v4.3.0 release[1].

[1] - https://github.com/wso2/samples-is/releases/tag/v4.3.0
