### ISSUE TITLE
Ship configuration to use emailOTP template with pack

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#7893]
**Description:**
In the new release the template which is used form EmailOTP is shipped in the pack. In order to use this template we need to add a configuration[1] to the toml file. That was also missed in the docs and this issue [2] has that description. As we ship the emailOTP template by default with the pack, it is better to have that conf with the default pack. 

[1] "authentication.authenticator.email_otp.parameters.useEventHandlerBasedEmailSender" : true
[2] https://github.com/wso2/docs-is/issues/1452

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
