### ISSUE TITLE
[Applications REST API] Need an endpoint to get all the available JS functions for adaptive scripts.

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#7899]
**Description:**
When configuring script based adaptive authentication, the current management console gives hints and autocomplete suggestions to the user regarding the supported JS functions etc.

Same experience has to be provided to the new Dev Portal hence the $subject.

<img width="799" alt="Screen Shot 2020-03-17 at 10 30 11 AM" src="https://user-images.githubusercontent.com/25959096/76823468-5879f180-683a-11ea-93b5-83cb74684cc4.png">

**Comment by ruwanta** [comment]
This is already being addressed via 
https://github.com/wso2-incubator/identity-developer-tools

Better not do any improvement on this editor more than currently.

**Comment by ruwanta** [comment]
This adaptive script editor currently use CodeMirror as the editor

We need to improve it to use, which has rich IDE support, eg. "Language Server" 
https://www.eclipse.org/che/features/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
