### ISSUE TITLE
Cannot update SP claim configuration properly.

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7911]
**Description:**

We found the following issues when updating the claim configuration section in the application API

1.  Claim mapping is not working correctly: 
It always returns an error response.  PATCH endpoint of API `api/server/v1/applications/{app-id}` is not working with claim mapping.  However, POST endpoint is working as expected and if we remove the role and subject section we can make the PATCH endpoint to work. However it, not the expected behavior.

2. Cannot update the dialect of the claim configuration:
It always gets saved as "LOCAL". However, for in the case of mapping, it should be saved as "CUSTOM"

3. Subject claim URI cannot updated: 
In the POST we can set the subject claim URI and we cannot update it in the patch request.

**Steps to reproduce:**
1. Create SP in the admin console with claim mappings
2. Get the detail for that application via REST endpoint using `api/server/v1/applications` list and `api/server/v1/applications/{app-id}` get endpoint.
3. Now try to patch the claim config with same details in endpoint `api/server/v1/applications/{app-id}`

**Sample PATCH payload**

```
{
    "name": "test app with custom claims",
    "claimConfiguration": {
        "dialect": "CUSTOM",
        "claimMappings": [
            {
                "applicationClaim": "username",
                "localClaim": {
                    "uri": "http://wso2.org/claims/username"
                }
            }
        ],
        "requestedClaims": [
            {
                "claim": {
                    "uri": "username"
                },
                "mandatory": false
            }
        ],
        "subject": {
            "claim": {
                "uri": "username"
            },
            "includeUserDomain": false,
            "includeTenantDomain": false,
            "useMappedLocalSubject": false
        }
    }
}
```
response
![image](https://user-images.githubusercontent.com/17597685/76833341-2627be80-6851-11ea-8905-6a4fba35e705.png)

**Related Issues:**
https://github.com/wso2/product-is/issues/7856

**Comment by emswbandara** [comment]
@AnuradhaSK will attend to this.

**Comment by mefarazath** [comment]
In addition, to the fix in https://github.com/wso2/identity-api-server/pull/118 it would be better if we could add some backend validation for custom claim dialects in https://github.com/wso2/carbon-identity-framework/blob/12aa4f36153478f733e7bfc991eb6b86821a450a/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtValidator.java#L371-L384


For example when a custom claim dialect is used,
1. Validate the defined username claim URI is defined in custom claim mappings
2. Validate role claim URI defined is present in custom claim mappings

as an example, 
```
{
    "claimConfiguration": {
        "dialect": "CUSTOM",
        "claimMappings": [
            {
                "applicationClaim": "username",
                "localClaim": {
                    "uri": "http://wso2.org/claims/username"
                }
            },
            {
                "applicationClaim": "testclaim",
                "localClaim": {
                    "uri": "http://wso2.org/claims/lastname"
                }
            }
        ],
        "requestedClaims": [
            {
                "claim": {
                    "uri": "username"
                }
            },
            {
                "claim": {
                    "uri": "testclaim"
                }
            }
        ],
        "subject": {
            "claim": {
                "uri": "username1"
            }
        },
        "role": {
            "claim": {
                "uri": "testclaim1"
            }
        }
    }
}
```
This PATCH request should fail since the defined custom subject and role claims (username1, testclaim1) are not defined under claimMappings section
