### ISSUE TITLE
JDBC implementation for unique id for groups

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#7914]
**Description:**

Implement the new Group APIs for JDBC userstores.

- Sub Task of: https://github.com/wso2/product-is/issues/16368

**Comment by UdeshAthukorala** [comment]
### This was done by following PRs:

#### BE Changes

- https://github.com/wso2/carbon-kernel/pull/3847
- https://github.com/wso2/carbon-kernel/pull/3850
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim/pull/127
- https://github.com/wso2-extensions/identity-inbound-provisioning-scim/pull/128

#### Unit Test Changes
- https://github.com/wso2/carbon-kernel/pull/3877
- https://github.com/wso2/carbon-kernel/pull/3879
- https://github.com/wso2/carbon-kernel/pull/3878

### Integration Test Changes
- https://github.com/wso2/product-is/pull/19538
- https://github.com/wso2/product-is/pull/19566

All the tasks related to this sub task was tracked in the main task(https://github.com/wso2/product-is/issues/16368).

**Comment by UdeshAthukorala** [comment]
Closing since all the PRs were merged
