### ISSUE TITLE
[Secondary User Store]Unable to edit User Store Manager Class configuration in Admin/Carbon console

### ISSUE THREAD

**Issue by jenananthan** [wso2/product-is#7916]
**Description:**
Unable to edit User Store Manager Class configuration in Admin/Carbon console for already added secondary user store configuration

**Affected Product Version:**
IS : wso2is-5.10.0-rc2

**OS, DB, other environment details and versions:**    
OS : Mac OS Catalina
JAVA : jdk-11.0.6

**Steps to reproduce:**
1. Create a secondary user store by choosing JDBCUserStoreManager as User Store Manager Class from drop-down
2. Once configuration is successfully created, from the user store list pick the created user store and edit.
3. In the edit, page try to choose UniqueIDJDBCUserStoreManager as User Store Manager Class from the dropdown.
UI is getting refreshed and previous configuration is getting loaded in dropdown list. i.e unable to change the   User Store Manager Class

**Comment by emswbandara** [comment]
This is the expected behavior. If you need to change the userstore manager, you need to delete the existing one and add a new userstore with the expected userstore manager class.

**Comment by jenananthan** [comment]
Good to know it is expected behaviour. Disabling the uneditable fields (e,g drop-down box) in edit page would give more clarity for end-user on which fields can be modified and cannot be.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
