### ISSUE TITLE
Caching issue when updating username in XACML policy

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#7919]
**Description:**
Caching issue when updating username in XACML policy  

**Steps to reproduce:**
While trying UMA flow in [User Managed Access with WSO2 Identity Server](https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#try-out-the-uma-flow) documentation, under [publishing a policy](https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#publish-a-policy) you will find the XACML policy. There, if you try to update the username and publish it again, the expected UMA flow will break due to caching.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
