### ISSUE TITLE
The User Store endpoint doesn't categorise properties

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#7920]
**Description:**
The `/userstores/{userstore-domain-id}` endpoint returns the user store properties as an array. 
![image](https://user-images.githubusercontent.com/20745428/76928517-baecf380-6907-11ea-8894-78a317ae21e2.png)
Ideally, this should be categorized into 
- Mandatory
- Advanced 
- Optional

As in the response returned by the 
`/userstores/meta/types/{type-id}` endpoint.
![image](https://user-images.githubusercontent.com/20745428/76929214-972aad00-6909-11ea-9dc4-3b05cecee21a.png)

**Comment by emswbandara** [comment]
AFAIR this was finalized during the API design phase to provide the categorization only from the types API and send the properties in a flat hierarchy from the userstore API. @Kanapriya @IsuraD

**Comment by Kanapriya** [comment]
> AFAIR this was finalized during the API design phase to provide the categorization only from the types API and send the properties in a flat hierarchy from the userstore API. @Kanapriya @IsuraD

Yes, when we return the user store with its domain id, we decided to return its properties with key-value pairs, but when we retrieve the user store by its type, we are categorizing the properties whether it is mandatory, optional or and advanced.

**Comment by thivi** [comment]
But the problem is since there are around 164 elements in the array, we can't show all of them together in one UI. My idea was to present the key-value pairs in a tabbed screen like this:
![image](https://user-images.githubusercontent.com/20745428/76933493-415b0280-6913-11ea-89a1-20123edaf342.png)
The tabs correspond to the categorization found in the carbon console. 
![image](https://user-images.githubusercontent.com/20745428/76934063-72880280-6914-11ea-82f6-b62b7477fd98.png)
Therefore, I think it will be better if the array can be categorized.

**Comment by emswbandara** [comment]
As discussed during the discussion, we will use the following approach to resolve this issue:
First get the userstore property categories from the meta endpoint. Store them in the UI side and the properties that are available in a particular userstore instance we can compare against the available meta categories and assign them to appropriate categories in the UI.

We will close this issue based on the above mentioned solution. Please re-open if you need further clarifications.

**Comment by emswbandara** [comment]
Re-opened to track the UI level improvement.
