### ISSUE TITLE
Tenant-qualify inbound paths of Carbon Webapps

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7924]
**Description:**
The current inbound paths to carbon webapps do not have the tenant domain as a path parameter. This task will tenant-qualify the inbound paths by appending the tenant domain as follows,

eg: localhost:9443/t/{tenant.domain}/samlsso

This task will tenant-qualify the following Carbon webapp endpoints,

- [x] /commonauth : https://github.com/wso2/product-is/issues/8197
- [x] /oidc : https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1377
- [x] /samlsso : https://github.com/wso2/product-is/issues/8139
- [x] /samlartresolve : https://github.com/wso2/product-is/issues/8159
- [x] /identity (already follows the tenant qualfied URL pattern. Might need to change the way the tenant domain is fetched)
- [x] /.well-known/web-finger : https://github.com/wso2/product-is/issues/8528
- [x] /passivests : https://github.com/wso2/product-is/issues/8315

**Comment by malithie** [comment]
Fixed
