### ISSUE TITLE
Tenant-qualify inbound paths of JSP-based webapps

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7927]
**Description:**

The current inbound paths to JSP web apps do not have the tenant domain as a path parameter.
eg: localhost:9443/authenticationendpoint

This task will tenant-qualify the inbound paths by appending the tenant domain as follows,
eg: localhost:9443/t/{tenant.domain}/authenticationendpoint

This task will tenant-qualify the following JSP-based webapp endpoints, which are related to the core login and account lifecycle management functionalities.

- [x]  /authenticationendpoint https://github.com/wso2/product-is/issues/8249
- [x]  /accountrecovery https://github.com/wso2/product-is/issues/8130

**Comment by malithie** [comment]
Done
