### ISSUE TITLE
Tenant-qualify outbound paths of JSP Webapps

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#7928]
**Description:**
The current outbound paths to JSP webapps do not have the tenant domain as a path parameter. This task will tenant-qualify the outbound paths by appending the tenant domain as follows,

eg: localhost:9443/t/{tenant.domain}/authenticationendpoint/...

This task will tenant-qualify the following JSP webapp endpoints,

- [x] /authenticationendpoint : https://github.com/wso2/product-is/issues/7993
- [x] /accountrecovery: https://github.com/wso2/product-is/issues/8565

**Comment by malithie** [comment]
Done
