### ISSUE TITLE
Tenant-qualify Resident IdP metadata

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7931]
**Description**
This task assures that the metadata URLs of the resident IdP are updated with the tenant in path when the support for tenant-qualified URLs is enabled.

**Comment by mefarazath** [comment]
@ChamathNS Have we covered this with the improvements done to qualify URLs displayed in resident IDP? 

What are the task level to close this issue?

**Comment by ChamathNS** [comment]
@mefarazath We have tenant-qualified URLs only for saml and OAuth2/OIDC configs. We didn't fix the others (SCIM, passiveSTS, ...)

Also, we should decide whether we should allow the saml urls to be configured from the management console when operating in tenant-qualified mode.

**Comment by malithie** [comment]
passive sts is done

**Comment by GANGANI** [comment]
SCIM 2.0 is done

**Comment by malithie** [comment]
Closing as planned endpoints are qualified
