### ISSUE TITLE
Skip consent for login and logout is missing for application in the rest api 

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#7935]
**Description:**

 Currently, we only providing the following configuration through rest API to skip consent

![image](https://user-images.githubusercontent.com/17597685/77047439-bcdbb300-69ea-11ea-9328-08cab1459232.png)

However, in the management console, we can skip the consent for login and logout separately

![image](https://user-images.githubusercontent.com/17597685/77047472-c9f8a200-69ea-11ea-871d-3c40b2bf1e9e.png)

We need to update the rest API to support it.

**Comment by emswbandara** [comment]
@mefarazath was it not allowed from API intentionally or do we need to fix?

**Comment by mefarazath** [comment]
I think this improvement came after the REST APIs were done. Omitting this wasn't intentional.

**Comment by emswbandara** [comment]
@AnuradhaSK let's update the docs on this as well. https://github.com/wso2/docs-is/blob/master/en/docs/develop/restapis/applications.yaml#L2077

**Comment by emswbandara** [comment]
Also this will have a migration impact, if someone migrates from 5.10.0 to 5.11.0 which requires them to regenerate clients. so let's create a migration issue as well.
