### ISSUE TITLE
Some SAML2 issuer URLs break when stored in registry

### ISSUE THREAD

**Issue by nattyboyme3** [wso2/product-is#7942]
**Describe the issue:**
Problem when adding SAML2 Inbound Auth configuration to an SP when the Issuer URL evaluates to a Base64 string that includes the "/" character.

**How to reproduce:**
Add a SAML2 inbound auth config to an SP with the issuer url: 
```https://smarttrackpro.webdeskprint.com/eduAdmin/OrganizationDetail.aspx?OID=2```
This evaluates to the following Base64: 
```aHR0cHM6Ly9zbWFydHRyYWNrcHJvLndlYmRlc2twcmludC5jb20vZWR1QWRtaW4vT3JnYW5pemF0aW9uRGV0YWlsLmFzcHg/T0lEPTI=```
It seems that when it is stored in the registry, the registry interprets the "/" character near the end as a directory delimiter, storing the URL in two parts: A container ```aHR0cH...zcHg``` and a object ```T0lEPTI```

This breaks the SP's SAML2 config, and if you try to edit the SAML2 options, the ```/add_service_provider.jsp?SPAction=editServiceProvider...``` URL shows an empty SAML2 config, and redirects to a blank screen at ``/carbon/admin/error.jsp`` when trying to update any parameters in the SAML2 config. 

**Expected behavior:**
Add the URL above as a SAML2 issuer and be able to store and edit the resulting configuration. 

**Environment information:**
 - Product Version: IS 5.7.0
 - OS: CentOS Linux
 - Database: MS SQL
 - Userstore: AD LDAP
---

**Comment by janakamarasena** [comment]
Looks like this is fixed from IS-5.8.0 onwards with https://github.com/wso2/carbon-identity-framework/pull/2096

**Comment by nattyboyme3** [comment]
Thanks! I'll look at upgrading.

**Comment by malithie** [comment]
Duplicates https://github.com/wso2/product-is/issues/4554
