### ISSUE TITLE
Recaptcha not prompting as on failed login attemps

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#7943]
**Describe the issue:**
When Recaptcha for Single Sign-On is configured with Account Locking, Recaptcha is not prompted on failed login attempt.

**How to reproduce:**
Configure the following in resident IDP settings.
- Recaptcha for Single Sign-On: After 3 failed attempts
- Account Locking by Failed Login Attempts: 5 failed attempts

Recaptcha is not displayed after 3rd failed attempt

**Expected behavior:**
When a user enters a wrong password, the UI should display Recaptcha with the 4th attempt. But in this scenario, before trying for the 4th time, Recaptcha is not displayed. It is displayed one the user clicks on the login button. Therefore, the user experiences Recaptcha on the 5th attempt.

**NOTE:** I have tested the same scenario with IS 5.10.0 and wso2is-5.9.0+1583941829343 and the issue is fixed in those versions.

**Suggested labels:**
IS-5.7.0, IS-5.7.0-KM

**Comment by janakamarasena** [comment]
This is fixed in IS 5.8.0 onwards as a result of https://github.com/wso2-extensions/identity-governance/pull/275
