### ISSUE TITLE
[ISSUE] Cannot configure a HTTP connector with deployment.toml for X509Certificate based authentication

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#7945]
**Describe the issue:**
Ideal way to get the x509certificate authenticator configured is to introduce another HTTP connector on a different port pointed to a trust store managing client certificates.
However, with the deployment.toml based configuration option, there is no way to get a connector configured 

**How to reproduce:**
Doc:
https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator

**Expected behavior:**
deployment.toml based configuration model should have a way to locate a trust store for x509certificate authentication and enforce client authentication

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - IS 5.9.0
 - OS: Any
 - Database: Any
 - Userstore: Any

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
