### ISSUE TITLE
TOTP token verification before enabling the TOTP for user

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#7946]
**Is your feature request related to a problem? Please describe.**

In the TOTP admin service, we have the API to Enable TOTP [1]. In the enable TOTP call an encoded QR Code URL will be received in the response. At the same time, TOTP will be enabled to the user. However, if the user didn't use the returned QR code URL to register in the authenticator application then the user has enabled the TOTP, but the user doesn't have the TOTP code to authenticate. 

In this scenario, the user will have to again send the Enable TOTP request to get the QR URL back and scan in the TOTP application.

Also, it is observed when TOTP is enabled in the application and the user didn't scan the QR code, the user will not be able to log in after logging out from the application. This is because TOTP will be prompted as the Enable TOTP API call will update the user claim _http://wso2.org/claims/identity/secretkey_ as a user activated the TOTP.

**Describe the solution you would prefer**

So it would be better if we allow APIs,
* Create the QR code URL - A random URL will be generated and sent back. (same as the current Enable TOTP, but the TOTP will not be enabled for the user)
*  Enable TOTP - The application has to send the TOTP token, the server validates the token and enables TOTP for the user.

[1] https://docs.wso2.com/display/ISCONNECTORS/Using+the+TOTP+API#UsingtheTOTPAPI-EnableTOTPEnableTOTP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
