### ISSUE TITLE
[ISSUE] Possible break in tenant wise email sending flow

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#7950]
**Describe the issue:**
There is a change in **event-handler-notification** which will enable email sending by using tenant wise email configurations in IS 5.9.0. This change was introduced by backporting [1] from IS 5.10.0 to IS 5.9.0. There are couple of updated components from this improvement. However if any other product use only the updated **event-handler-notification** components there is a possible break in email sending flow. Previous behaviour of **event-handler-notification** is sending emails by using super tenant configurations. But from the new update **event-handler-notification** can send emails by using tenant wise configuration. As mentioned before in order to enable this feature it needs several other updated components. The issue is if any other product uses only the updated **event-handler-notification** component there is a possibility of breaking the email sending flow.

[1] https://github.com/wso2/product-is/issues/6146

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
