### ISSUE TITLE
[ISSUE]Secondary user store pass word encryption code is duplicated

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#7954]
**Describe the issue:**
In WSO2 IS secondary userstores can be deployed in 2 ways.
1.Through UI
2.By creating a file with secondary userstore configurations and saving it with '.enc' extension.

Both these cases, userstore password get encrypted.
1.Password encryption of user stores created with UI, is handled in [1] **org.wso2.carbon.identity.user.store.configuration**.utils.SecondaryUserStoreConfigurator

2.Password encryption with apprach 2 is handled in [2] **org.wso2.carbon.identity.user.store.configuration.deployer**.util.UserStoreUtil

As you can see the logic is same. But the method is duplicated in two osgi bundles.
1.org.wso2.carbon.identity.user.store.configuration
2.org.wso2.carbon.identity.user.store.configuration.deployer

We need to utilize this method and bring this method to one place.

Please refer comment https://github.com/wso2/carbon-identity-framework/pull/2833#discussion_r397370172 which talks about the same issue

[1]https://github.com/wso2/carbon-identity-framework/blob/745688e61d9965c6f573613694fe2fa661f96ac1/components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/SecondaryUserStoreConfigurator.java#L139
[2]https://github.com/wso2/carbon-identity-framework/blob/57ad2c97fc9486e4803a66185de8851642574848/components/user-store/org.wso2.carbon.identity.user.store.configuration.deployer/src/main/java/org/wso2/carbon/identity/user/store/configuration/deployer/util/UserStoreUtil.java#L122

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
