### ISSUE TITLE
[ISSUE] Bug in User stores meta types endpoint in IS - 5.10

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#7962]
**Describe the issue:**
`/userstores/meta/types/{type-id}` endpoint returns user store properties of the specified type, only if at least one user store is configured as the specified type of secondary user store. Moreover, if more than one user store is available for the defined type, it returns an array of user stores with the properties of that particular user store type. (i.e. same set of properties repeats in the response). 

**How to reproduce:**

1. GET request:  `https://localhost:9443/api/server/v1/userstores/meta/types/`

2. Select typeId of a secondary userstore type which is not configured already (ex:QWN0aXZlRGlyZWN0b3J5VXNlclN0b3JlTWFuYWdlcg for ActiveDirectoryUserStoreManager)

3. GET request:  `https://localhost:9443/api/server/v1/userstores/meta/types/QWN0aXZlRGlyZWN0b3J5VXNlclN0b3JlTWFuYWdlcg`

5. Response: Returning a 404 error when there is no secondary user store configured.

```
code: "SUS-60003"
message: "Resource not found."
description: "Unable to find a required resource for this request"
traceId: "40b08bbd-0474-4dda-a7ff-0a9d1d98f29d"
```

Then configure set of userstores from the particular type, and 
GET request:  `https://localhost:9443/api/server/v1/userstores/meta/types/{type-id}` It will return an array of configured userstore of that particular type with the same set of meta data

**Expected behavior:**
Return the metadata of Specified userstore type

**Environment information** 
 - Product Version:  IS 5.10.0

**Fixes done for 5.11.0**
[1]https://github.com/wso2/identity-api-server/pull/122
[2]https://github.com/wso2/product-is/pull/7955

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
