### ISSUE TITLE
[FEATURE] User account suspension according to fixed(pre-configured) time period

### ISSUE THREAD

**Issue by UmenR** [wso2/product-is#7965]
**Is your feature request related to a problem? Please describe.**
This feature is for use-cases such as **trial account suspension**. Where the users are registered in the system for a pre-configured period of time(trial period) and once this time period has passed the user is automatically disabled or removed from the system.

**Describe the solution you would prefer**
Currently, we have a similar feature used for **Idle account locking** where the user is locked if a particular user does not log into the system for a configured period of time. When the account is locked the user will be notified via email. Similar configuration and behaviour are prefered for this feature as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
