### ISSUE TITLE
[ISSUE] Unable to update user store name using a PUT request to the user store endpoint

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#7968]
**Describe the issue:**
Trying to update the name of a user store using the `/userstores/{userstore-domain-id}` endpoint results in the following error. 
![image](https://user-images.githubusercontent.com/20745428/77775839-2145e480-7073-11ea-842e-115feb2a6a4d.png)

However, I am able to successfully update the user store description using the same endpoint.

**Comment by emswbandara** [comment]
@Kanapriya 

As per the source code of userstore REST API, there is a comment that userstore domain name is not allowed to be updated from UI. https://github.com/wso2/identity-api-server/blob/master/components/org.wso2.carbon.identity.api.server.userstore/org.wso2.carbon.identity.api.server.userstore.v1/src/main/java/org/wso2/carbon/identity/api/server/userstore/v1/core/ServerUserStoreService.java#L130

did we come to a conclusion during the design review to not to allow users to update userstore domain name from REST API?

**Comment by Kanapriya** [comment]
Yes, we decided not to update the user store type and user store domain name in the design review at that time as we need to regenerate the type and domain id. But we can revisit and add this capability.

**Comment by emswbandara** [comment]
@thivi @thanujalk 
do we have a blocking requirement to update userstore domain name? Can't we delete the userstore and add again with the required new domain name as a work-around?

**Comment by thivi** [comment]
The userstore domain name can be made read-only on the frontend if that's the case. Since the carbon console allows it, I thought the same thing should be possible through the dev portal as well.

**Comment by thivi** [comment]
The userstore name was made readonly in the edit view. 
https://github.com/wso2/identity-apps/pull/682
