### ISSUE TITLE
[Doc] Capability to add HTTP access logs to carbon console (stdout)

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#7973]
**Is your feature request related to a problem? Please describe.**
Although we have the capability to add AUDIT_LOG, Correlation logs, transaction logs to carbon console we do not have the possibility to add HTTP access logs. 

**Describe the solution you would prefer**
developing our own access log valve. with cross-platform support. 

https://github.com/Scout24/tomcat-stdout-accesslog/blob/master/src/main/java/de/is24/tomcat/StdoutAccessLogValve.java

**Comment by rksk** [comment]
Addressed with https://github.com/wso2/carbon-kernel/issues/2660

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
