### ISSUE TITLE
Issues/improvements with federated authenticator metadata response

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#7983]
**Describe the Issue:**
- Even though [federated authenticator metadata response](https://localhost:9443/t/carbon.super/api/server/v1/identity-providers/meta/federated-authenticators/{id}) supports `isConfidential` parameter, it is not properly configured for the `OpenIDConnectAuthenticator`'s `Client Secret` paremeter(shows `false`, instead of  `true`). This needs to be checked in all available federated authenticator properties.
- The same response does not have a meta property to indicate for a URL field. This would be useful to enforce URL validation from the UI.

**How To Reproduce:**
1. Invoke `https://localhost:9443/t/{{tenant-domain}}/api/server/v1/identity-providers/meta/federated-authenticators`, and get the list of authenticators.
2. Fetch `OpenIDConnectAuthenticator` metadata with `https://localhost:9443/t/carbon.super/api/server/v1/identity-providers/meta/federated-authenticators/{authenticator-id}I`.
3. Observe followings.
3.1 `isConfidential` is `false`
3.2 URL fields are considered as text.

**Expected behavior:**
- `isConfidential` should be `true` for appropriate fields(ex: `Client Id` in the aforementioned scenario).
- URL fields should have a property to indicate them as URLs.

**Device Information** (_Please complete the following information_) **:**
 - Device: PC
 - OS: Ubuntu 18.04
 - Chrome; Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by emswbandara** [comment]
@tharindu-bandara can you please create another issue to track the URL option. It  is an improvement which requires changes to the Property model.

**Comment by tharindu-bandara** [comment]
> @tharindu-bandara can you please create another issue to track the URL option. It is an improvement that requires changes to the Property model.

+1. Please find the issue: https://github.com/wso2/product-is/issues/7987

**Comment by tharindu-bandara** [comment]
@emswbandara 

Kindly find the meta-properties below, which need to be marked as confidential.

- `client secret` field in `Oauth2, Facebook, Microsoft, Google, Yahoo, Office 365` Federated Authenticators
- `api secret` field in `Twitter` Federated Authenticator
- `service principal password` field in the `Kerberos` Federated Authenticator

**Comment by emswbandara** [comment]
@tharindu-bandara 

Except for **facebook and OAuth authenticators** for rest of the authenticators you mentioned the confidential property is already there. E.g. https://github.com/wso2-extensions/identity-local-auth-iwa-kerberos/blob/master/components/org.wso2.carbon.identity.application.authenticator.iwa/src/main/java/org/wso2/carbon/identity/application/authenticator/iwa/IWAFederatedAuthenticator.java#L157
