### ISSUE TITLE
[ISSUE] Inconsistency in APP_NAME values in IDN_OAUTH_CONSUMER_APPS 

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7985]
**Describe the issue:**
In IS side OAuth application data are stored in IDN_OAUTH_CONSUMER_APPS. This APP_NAME is not consistent.

When an OAuth App is created via REST API, the APP_NAME is a random uuid.
When an OAUth App is created via management console, the the APP_NAME is service provider's name.
And if we update the app created from the REST_API using management console, the APP_NAME changes from uuid to sp_name.

**How to reproduce:**
- Create a oauth sp(spname: testy) using Application Management Rest API. 

   The APP_NAME in IDN_OAUTH_CONSUMER_APPS  table will be a **uuid**.

<img width="1601" alt="Screen Shot 2020-03-30 at 1 45 48 PM" src="https://user-images.githubusercontent.com/17597293/77890348-f2a35600-728c-11ea-8a6f-cd2908e6d756.png">

- Update the sp(spname: **testy**) using management console (please note that I didn't update spname. ). 
  Now the APP_NAME in IDN_OAUTH_CONSUMER_APPS  table will be a **testy**.

<img width="1601" alt="Screen Shot 2020-03-30 at 1 46 31 PM" src="https://user-images.githubusercontent.com/17597293/77890368-fb942780-728c-11ea-8210-152d2c30e39e.png">

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
 - OS: Mac
 - Database: H2
 - Userstore:LDAP

---

**Related issues:**

In DCR endpoint, we can get app details from client_name. 

`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register?client_name=application_owner_application_1"`

**DCR resquest1:** 
`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register?client_name=befb1c3a-b895-44b0-88b6-074f7488731d"`

`{"client_id":"JbfZlQizwEfJWlK2gAyZYxRfYdMa","client_secret":"eRW3Vo2yfwEnyJ9RGekfm71u4aQa","client_secret_expires_at":null,"redirect_uris":["http://localhost:8000/login/code/wso2"],"client_name":"befb1c3a-b895-44b0-88b6-074f7488731d"}`

**DCR request2:**

`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register?client_name=Testsp"`

`{"client_id":"0eNmMiFl79vqGTUV_zy6sDE8kVka","client_secret":"DW0hQYsYbztgs0RRBgqxhwlWOkka","client_secret_expires_at":null,"redirect_uris":["http://localhost:8000/login/code/wso2"],"client_name":"Testsp"}`

The dcr endpoint uses the APP_NAME as the client_name.

Now if we update the sp using management console, the app_name will change from uuid to sp_name. This will make issues.

**Suggested labels:**

**Comment by piraveena** [comment]
@mefarazath @emswbandara Please give your thoughts

**Comment by mefarazath** [comment]
@piraveena Does the consumer app name change to SP's name only when you **change SP name** or do **any update to the OAuth app configurations**?

**Comment by piraveena** [comment]
@mefarazath APP_NAME changes to sp's name from uuid with any update to OAuth app configurations

**Comment by piraveena** [comment]
> @piraveena Does the consumer app name change to SP's name only when you **change SP name** or do **any update to the OAuth app configurations**?

@mefarazath APP_NAME changes to sp's name from uuid with any update to OAuth app configurations

**Comment by mefarazath** [comment]
Okay, that looks wrong to me :)
Management console shouldn't override the existing app name. What's the behavior when you change the SP name. I assume it will not change the OAuth client name?

**Comment by piraveena** [comment]
Updating the SP name (testapp -> testapp1) from management console changes the APP_NAME . It changes into uuid to the new app name (uuid -> testapp1).

**Comment by piraveena** [comment]
> Okay, that looks wrong to me :)
> Management console shouldn't override the existing app name. What's the behavior when you change the SP name. I assume it will not change the OAuth client name?
 
Created a sp **testapp**.
Updating the SP name testapp1 (testapp -> testapp1) from management console changes the APP_NAME . It changes into uuid to the new app name (uuid -> testapp1).

**Comment by piraveena** [comment]
Created a sp testapp1
<img width="1601" alt="Screen Shot 2020-03-30 at 2 45 00 PM" src="https://user-images.githubusercontent.com/17597293/77896164-7bbe8b00-7295-11ea-8668-89997ec8e33a.png">

Updated a sp using restapi.

```
curl --location --request PATCH 'https://localhost:9443/t/carbon.super/api/server/v1/applications/e6586b7e-7e47-40a4-bf01-aed6b9bb60f8' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data-raw '{
 "name": "newapp"
}'
```

APP_NAME changes to sp_name
<img width="1601" alt="Screen Shot 2020-03-30 at 2 46 53 PM" src="https://user-images.githubusercontent.com/17597293/77896177-7eb97b80-7295-11ea-9ea4-943af9b75b96.png">

**Comment by mefarazath** [comment]
Okay considering the complexity, I think the best way would be to fix the REST API to be consistent with other APIs (SOAP and DCR).
