### ISSUE TITLE
Indicate URL fields in federated authenticator metadata response

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#7987]
**Describe the issue:**
A separate issue to track the $subject concern raised in https://github.com/wso2/product-is/issues/7983.

**How to reproduce:**
Please refer https://github.com/wso2/product-is/issues/7983.

**Expected behavior:**
Please refer https://github.com/wso2/product-is/issues/7983.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Please refer https://github.com/wso2/product-is/issues/7983.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
