### ISSUE TITLE
[TASK] Create default template types in Configuration Store using DB scripts

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#7990]
**Describe the issue:**
At the moment there is no any default template type created in config store. Since we are going to enable configuration store by default in the product(i.e. Related to [issue](https://github.com/wso2/product-is/issues/7982)). It is required to create default template types such as IDP_TEMPLATE, APPLICATION_TEMPLATE etc. using DB scripts.

**Comment by emswbandara** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/2847
