### ISSUE TITLE
[ISSUE]Cannot update carbon.properties file with new configuration model

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#7991]
**Describe the issue:**
If we want to update the property value in carbon.properties file, there is no proper way of doing it using the new configuration model.

**How to reproduce:**
1.Add following configuration to deployment.toml file
[system.parameter]
'org.wso2.CipherTransformation'="AES"

2.Start the server. Still the original value will be picked up.

3.Restart the server. Now the new value in the deployment.toml will be picked.

**Expected behavior:**
Once you change the deployment.toml, that value should be fixed from first server start up onwards.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.9.0 onwards versions
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by senthalan** [comment]
Related issue https://github.com/wso2/carbon-kernel/issues/2555

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
