### ISSUE TITLE
[ISSUE] Table doesn't exist error when running session data cleanup script.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#7996]
**Describe the issue:**
When running the session data clean up task [1] following error was encountered.
`ERROR 1146 (42S02): Table 'testdewni1.IDN_AUTH_USER_SESSION_MAPPING' doesn't exist`
This error is due to the script modification from PR [2]. Ideally, this script should function successfully for all IS versions.

**Environment information:**
 - Product Version: IS 5.2.0
 - Database: MySQL 5.7

[1] https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mysql/sessiondata-cleanup/mysql-session-data-cleanup.sql
[2] https://github.com/wso2/carbon-identity-framework/pull/2792

**Comment by mcvidanagama** [comment]
Same error occurs when trying to run this against an APIM-2.1.0 during a migration. This needs to be fixed.
Conditional check for the existence of the table would resolve this IMO.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
