### ISSUE TITLE
[ISSUE] In application rest api passive sts configs are not mandatory

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8006]
**Describe the issue:**

Currently, in the rest api `api/server/v1/applications/app-id/inbound-protocols/passive-sts` passive sts configs "realm" and "reply to" are not a mandatory option but we need to make them mandatory.

**Comment by emswbandara** [comment]
@inthirakumaaran even in the management console these two fields are not marked as mandatory. 
The realm is automatically getting set to SP name if not configured. Can you please re-check whether these two are mandatory fields for passive sts inbound authentication?

**Comment by inthirakumaaran** [comment]
@fazlan-nazeem mentioned that we need those configs.

**Comment by fazlan-nazeem** [comment]
@inthirakumaaran I'm not sure whether you mentioned me as a mistake?

**Comment by inthirakumaaran** [comment]
> @inthirakumaaran I'm not sure whether you mentioned me as a mistake?

Sorry for the mistake. It is supposed to be @mefarazath

**Comment by mefarazath** [comment]
@emswbandara: it's true that these params are not made mandatory in the management console. But for passive STS work the replyTo needs to be provided. Also realm defaulting to the SP name is hidden from the user.

Considering these, at the REST API level. I feel it would better to make the two parameters mandatory
