### ISSUE TITLE
[IMPROVEMENT] Provide application status in the list view for OIDC applications

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8008]
**Describe the issue:**
Currently, for OIDC applications we can get the "state" property in the oidc protocol config.

![image](https://user-images.githubusercontent.com/17597685/78213143-5b7a1080-74cf-11ea-8e46-4e0d380ee28c.png)

It would be more helpful if we can get this value in the app list API `api/server/v1/applications`

**Comment by mefarazath** [comment]
Where do we plan to use this 'state'?
Also, this is specific to OAuth2/OIDC. So it correct have it at api/server/v1/applications level?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
