### ISSUE TITLE
[MIGRATION] Changes for AdvancedApplicationConfiguration component in application REST API

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#8011]
**Describe:**

- In Application REST API,
the property named **skipConsent** under  **AdvancedApplicationConfiguration**, renamed to **skipLoginConsent** and **skipLogoutConsent** property is added to resolve issue https://github.com/wso2/product-is/issues/7935.

- Changes are done in: https://github.com/wso2/identity-api-server/pull/127/

- Affected when migrating to: 5.11.0

**Comment by pamodaaw** [comment]
Tracked with https://github.com/wso2/product-is/issues/9642
