### ISSUE TITLE
[ISSUE] Application rest api is not sending meta data for custom protcols

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8016]
**Expected behavior:**

For custom inbound protocols, we need to get the input element details from the `api/server/v1/applications/meta/inbound-protocols/<protocol-id>` where the protocol id for custom protocol can be taken from  `api/server/v1/applications/meta/inbound-protocols?customOnly=true`.

**Describe the issue:**

However, there are few issues in that flow:

1. Endpoint `api/server/v1/applications/meta/inbound-protocols?customOnly=true` is not returning protocol-ids. It only returns name and displayName:

![image](https://user-images.githubusercontent.com/17597685/78329053-51731300-759e-11ea-8c13-a49365dfb15e.png)

2. If we use that name, we got from the above request in the endpoint `api/server/v1/applications/meta/inbound-protocols/<protocol-id>` for the custom protocol it is throwing the below error

![image](https://user-images.githubusercontent.com/17597685/78329190-a6af2480-759e-11ea-9db0-851283e91272.png)

**Note**: if we try to get meta detail for ws-federation it is throwing a server internal error. We need to handle this.
![image](https://user-images.githubusercontent.com/17597685/78329265-d827f000-759e-11ea-80d3-435c4836e920.png)

**How to reproduce:**
1. Get the CAS inbound connector from the [store](https://store.wso2.com/store/assets/isconnector/details/593aac68-3139-425c-b9ca-f66a65a0917a) and add to the IS server
2. Try to get the available inbound protocols in endpoint `api/server/v1/applications/meta/inbound-protocols?customOnly=true` and check whether CAS is there
3. send GET request to  endpoint `api/server/v1/applications/meta/inbound-protocols/<protocol-id>` using protocol id as name we got above

**Comment by inthirakumaaran** [comment]
`Note: if we try to get meta detail for ws-federation it is throwing a server internal error. We need to handle this.`

for this issue, rather than not listing the  ws-federation in `api/server/v1/applications/meta/inbound-protocols` can we send empty array when we call the `api/server/v1/applications/meta/inbound-protocols/ws-federation`.

**Comment by emswbandara** [comment]
@mevan-karu
