### ISSUE TITLE
Tenant-specific static claim value

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8018]
Currently, in WSO2 IS, we can only define claim values per user. That is, the claims values such as email address and first name can be define for users separately. However, let's say we have some common claim values such as campus phone number and a vendor-designated school name which are the same for every user, but they are not in an Active Directory attribute and would be ideal to be able to set it as hardcoded/static value for all users.
(ie) a tenant-specific static claim which will be used by all the users.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
