### ISSUE TITLE
Make CryptoService extensible to support different algorithms

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#8019]
**Describe the issue:**
In [SymmetricKeyInternalProvider](https://github.com/wso2/carbon-crypto-service/blob/master/components/org.wso2.carbon.crypto.provider/src/main/java/org/wso2/carbon/crypto/provider/SymmetricKeyInternalCryptoProvider.java#L125) we check specifically for particular encryption algorithm using if conditions.

This need to be written in a way that is extensible.

This is mentioned in this [git comment](https://github.com/wso2/carbon-crypto-service/pull/18#discussion_r402789748)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
