### ISSUE TITLE
Is there tutorial about branch 6.0.x-C5?

### ISSUE THREAD

**Issue by liujinf** [wso2/product-is#802]
Hi,
I checkout the branch 6.0.x-C5 and package successfully.
After start carbon.bat, then access 'http://localhost:9090/user-portal/', but only head page, like this:
![image](https://cloud.githubusercontent.com/assets/492824/19962504/f0fc848e-a1f2-11e6-9770-f9fab33823f7.png)

What functions this version(now) have?
Thanks.

hf

**Comment by mefarazath** [comment]
Hi @liuhaif ,

This branch is still in the preliminary stages of development for our Identity Solution on top of the next carbon platform (C5).  There isn't much you can play with at the moment. Will update once we have something sufficient for a tryout.

Cheers!

**Comment by Pushpalanka** [comment]
Hi liuhaif,

As of now we haven't integrated any new Identity Features to the product (except for few UI related samples.) You may find one ongoing feature development at [1] which is related to federated IDPs.

[1] - https://github.com/wso2/carbon-identity-providers

Thanks,
Pushpalanka

**Comment by zygimantus** [comment]
Are there any updates for product-is at the moment that could be tried on User Portal?

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
