### ISSUE TITLE
Introduce `services` attribute to the IdP template list model

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#8020]
**Is your feature request related to a problem? Please describe.**

An IdP template describes a specific Identity Provider configuration. Now this configuration can support various features; authentication, provisioning, etc. It makes sense to have this information while listing templates, in order to choose a template to cater to certain requirements.

**Describe the solution you would prefer**

Introduce a `services` attribute to the existing IdP template model. One suggested services object is described below.
```json
{
    name: "Authentication",
    displayName: "Authentication Capability",
    logo: "authentication"
}
```
When the above model is embedded into the template model, it would look like this.
```json
{
    name: "Google"
    ...
    services: [ 
        {
            name: "Authentication",
            displayName: "Authentication Capability",
            logo: "authentication"
        }
    ]
    ...
}
```

**Comment by emswbandara** [comment]
If a template is configured to use a specific authenticator / provisioning connector, can't we derive the template service type from that? what is the purpose of having a seperate field? can there be any other service types?

**Comment by tharindu-bandara** [comment]
@emswbandara 

> If a template is configured to use a specific authenticator / provisioning connector, can't we derive the template service type from that? what is the purpose of having a separate field? can there be any other service types?

The reason is both authenticator and provisioning connector information is a part of the full template response. Therefore during the listing, we don't have enough information to interpret services information unless we make additional API calls per each template, which would be unnecessary.

**Comment by emswbandara** [comment]
@tharindu-bandara in that case, we can process the template object from the backend and if there is a authenticator configured, we can add a service attribute to the template list model. However i feel its redundant to have the displayName - Authentication Capability  and logo - authentication. Can't you derive that from the UI itself if we send the service as 'authentication'?

    services: [ 
        {
            name: "Authentication",
            displayName: "Authentication Capability",
            logo: "authentication"
        }
    ]

**Comment by tharindu-bandara** [comment]
> @tharindu-bandara in that case, we can process the template object from the backend and if there is a authenticator configured, we can add a service attribute to the template list model. However i feel its redundant to have the displayName - Authentication Capability and logo - authentication. Can't you derive that from the UI itself if we send the service as 'authentication' as follows?
> 
> ```
> services: [ 
>        "Authentication", "Provisioning"
> ]
> ```

+1. We can derive it from the UI side, as the services are common for all templates.
