### ISSUE TITLE
[ISSUE] Infinite loop on user-portal when login

### ISSUE THREAD

**Issue by nao2001** [wso2/product-is#8025]
**Describe the issue:**
After a fresh new install on Windows but also Linux centos of 5.10.0, i got exactly the same behavior
1 - User go to https://134.122.78.126:9443/user-portal
2 - Login with admin / admin
3 - Then a loop start with this URL

It seems that endpoint return 400
POST /oauth2/token

**How to reproduce:**
GET /oauth2/authorize?response_type=code&client_id=USER_PORTAL&scope=internal_login%20internal_humantask_view%20openid&redirect_uri=https://134.122.78.126:9443/user-portal/login&code_challenge_method=S256&code_challenge=-oHtY-IVN6tALiWUM4qWE2vBD8eXSietviKd2AmjAVw HTTP/1.1 302 - https://134.122.78.126:9443/user-portal/login?code=7081b85e-70de-3278-bf90-4684e273637d&session_state=a8f28d8a8d4d7dcd74ee7d3e2678db94197b7b2f3197701eb7f9b485f7da6962.eiUd5c7wjIXdCOnvziOdjg 

GET /user-portal/login?code=072bbca2-9a8a-3069-a660-4b7ccda412a8&session_state=a7c0ef47367555d1e20c4372bd4a1fd7ff1c03c04e18febe4880c9c0bd073d40.KGbsRCunkPM9c4eSGTs1pg HTTP/1.1 404 1424 https://134.122.78.126:9443/user-portal/login?code=7081b85e-70de-3278-bf90-4684e273637d&session_state=a8f28d8a8d4d7dcd74ee7d3e2678db94197b7b2f3197701eb7f9b485f7da6962.eiUd5c7wjIXdCOnvziOdjg 

GET /oauth2/oidcdiscovery/.well-known/openid-configuration HTTP/1.1 200 2308 https://134.122.78.126:9443/user-portal/login?code=072bbca2-9a8a-3069-a660-4b7ccda412a8&session_state=a7c0ef47367555d1e20c4372bd4a1fd7ff1c03c04e18febe4880c9c0bd073d40.KGbsRCunkPM9c4eSGTs1pg 
- 400 - - - 0.00

 GET /user-portal/app.config.json HTTP/1.1 200 902 https://134.122.78.126:9443/user-portal/login?code=072bbca2-9a8a-3069-a660-4b7ccda412a8&session_state=a7c0ef47367555d1e20c4372bd4a1fd7ff1c03c04e18febe4880c9c0bd073d40.KGbsRCunkPM9c4eSGTs1pg

POST /oauth2/token HTTP/1.1 400 117 https://134.122.78.126:9443/user-portal/login?code=072bbca2-9a8a-3069-a660-4b7ccda412a8&session_state=a7c0ef47367555d1e20c4372bd4a1fd7ff1c03c04e18febe4880c9c0bd073d40.KGbsRCunkPM9c4eSGTs1pg
[03/Apr/2020:13:18:31 +0000] - 400 - - - 0.000
`

**Expected behavior:**
User shall be login to user-portal

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0 fresh install
 - OS: Windows 10 and Linux Centos, Also docker version same behavior
 - Database: H2 default
 - Userstore: default one

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
Thanks for reporting the issue.

The line[1] checks for the response code of the token request and if it is `400`, we sends another authorization request to retry the login. If the token endpoint keep responding with `400` status, then it'll cause a loop.

We'll look in to this. 

[1] https://github.com/wso2/identity-apps/blob/master/apps/userportal/src/store/actions/authenticate.ts#L226

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
