### ISSUE TITLE
[IMPROVEMENT] Get list of IDPs that have enabled provisioning connectors

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8037]
**Describe the issue:**
Currently, in order to identify the IDPs configured with provisioning connectors we have to get the list of all the IDPs and then check each of the IDPs whether they have provisioning connectors or not.

It would be better if can have filtering capability to identify the IDPs that enabled provisioning connectors and what connectors they are using.

**Comment by emswbandara** [comment]
As a possible solution to this, we can add the requiredAttribute federatedAuthenticators, and then from the result, identify the list of IDPs that have the federatedAuthenticators from the returned list of IDPs. WDYT?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
