### ISSUE TITLE
[ISSUE] Get entitled attributes API returns an empty response when XACML policy has regex starting with '^'.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8041]
**Describe the issue:**
Get entitled attributes API returns an empty response when a regex with format "^test*" is set for the attribute value in the string-regexp-match function of the XACML policy. 

**How to reproduce:**
add the following XACML policy.
```
<Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"  PolicyId="aaaa_test" RuleCombiningAlgId="urn:oasis:names:tc:xacml:1.0:rule-combining-algorithm:first-applicable" Version="1.0">
   <Target>
      <AnyOf>
         <AllOf>
            <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-regexp-match">
               <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">^test*</AttributeValue>
               <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"></AttributeDesignator>
            </Match>
         </AllOf>
      </AnyOf>
   </Target>
   <Rule Effect="Permit" RuleId="PERMIT_RULE"></Rule>
</Policy>  
```
Call the Get entitled attributes API with the following request
```
curl --request POST \
  --url https://localhost:9443/api/identity/entitlement/decision/entitled-attribs \
  --header 'accept: application/json' \
  --header 'authorization: Basic YWRtaW46YWRtaW4=' \
  --header 'content-type: application/json' \
  --data '{
  "subjectName" : "admin",
  "enableChildSearch" : "false"
}' -k
```
The following empty response is returned.
```
{"entitledResultSetDTO":{"entitledAttributesDTOs":[],"advanceResult":false,"message":null,"messageType":null}}%
```
If the '**^**' is removed from the "^test*" AttributeValue in the XACML policy the following response is returned.
```
{"entitledResultSetDTO":{"entitledAttributesDTOs":[{"resourceName":"test*","action":null,"environment":null,"allActions":true,"allResources":false,"attributeDTOs":[]}],"advanceResult":false,"message":null,"messageType":null}}%
```
**Cause:**
When the Get entitled attributes API is called the attribute values from the defined policies are extracted and used as the input to evaluate the policies and come up with a result. When a regex like "^test*" is defined in the XACML policy AttributeValue for the match function, this value is taken as the input for evaluating the policy. When "^test*" is used as both regex and input, it will fail to match. Code - https://github.com/wso2/balana/blob/master/modules/balana-core/src/main/java/org/wso2/balana/cond/MatchFunction.java#L415

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
