### ISSUE TITLE
[ISSUE] Unable to update the user profile through management console when userstore is an Active Directory

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#8043]
**Description:**

I have found two issues when trying to update the user profile through the management console.

**Issue 01**

When trying to update the user profile through the management console, it's failing with below LDAP error in the wso2carbon logs.

<pre style="color:#000020;background:#f6f8ff;">javax<span style="color:#308080; ">.</span>naming<span style="color:#308080; ">.</span>directory<span style="color:#308080; ">.</span>NoSuchAttributeException<span style="color:#406080; ">:</span> <span style="color:#308080; ">[</span>LDAP<span style="color:#406080; ">:</span> error code <span style="color:#008c00; ">16</span> <span style="color:#308080; ">-</span> <span style="color:#008c00; ">00000057</span><span style="color:#406080; ">:</span> <span style="color:#308080; ">.</span><span style="color:#308080; ">.</span><span style="color:#308080; ">.</span>
</pre>

The reason is, profile configuration claim only used with the JDBC userstores and has to be skipped in the AD/LDAP userstores inside doSetUserAttributesWithID [1] method. In the previous IS version we have skipped as here [2]. This will be fixed form this PR [3].

**Issue 02**

After fixing this, it returned the below error while updating the user profile.

<pre style="color:#000020;background:#f6f8ff;">javax<span style="color:#308080; ">.</span>naming<span style="color:#308080; ">.</span>directory<span style="color:#308080; ">.</span>SchemaViolationException<span style="color:#406080; ">:</span> <span style="color:#308080; ">[</span>LDAP<span style="color:#406080; ">:</span> error code <span style="color:#008c00; ">65</span> <span style="color:#308080; ">-</span> 0000207D<span style="color:#406080; ">:</span> UpdErr<span style="color:#406080; ">:</span> DSID<span style="color:#308080; ">-</span>031517BB<span style="color:#308080; ">,</span> problem <span style="color:#008c00; ">6002</span> <span style="color:#308080; ">(</span>OBJ_CLASS_VIOLATION<span style="color:#308080; ">)</span><span style="color:#308080; ">,</span> data <span style="color:#008c00; ">42</span>
<span style="color:#308080; ">]</span>
</pre>

The issue here seems to be with the user search filter [4], we have used a user id search filter to search users from the ObjectGUID.

Below is a sample filter currently passing but this didn't return any results.

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#308080; ">(</span><span style="color:#308080; ">&amp;</span><span style="color:#308080; ">(</span>objectClass<span style="color:#308080; ">=</span>user<span style="color:#308080; ">)</span><span style="color:#308080; ">(</span>objectGuid<span style="color:#308080; ">=</span>\5c55\5c4b\5c71\5c5e\5ca6\5c67\5cd7\5c45\5cb3\5ca2\5cf7\5c44\5c1f\5c78\5cb5\5ce4<span style="color:#308080; ">)</span><span style="color:#308080; ">)</span>
</pre>

To verify this, I replaced the user id search filter with username search filter as below and it returned the response correctly.

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#007d45; ">String</span> username <span style="color:#308080; ">=</span> getUserNameFromUserID<span style="color:#308080; ">(</span>userID<span style="color:#308080; ">)</span><span style="color:#406080; ">;</span>
username <span style="color:#308080; ">=</span> UserCoreUtil<span style="color:#308080; ">.</span>removeDomainFromName<span style="color:#308080; ">(</span>username<span style="color:#308080; ">)</span><span style="color:#406080; ">;</span>
userSearchFilter <span style="color:#308080; ">=</span> userSearchFilter<span style="color:#308080; ">.</span><span style="color:#200080; font-weight:bold; ">replace</span><span style="color:#308080; ">(</span><span style="color:#800000; ">"</span><span style="color:#1060b6; ">?</span><span style="color:#800000; ">"</span><span style="color:#308080; ">,</span> escapeSpecialCharactersForFilter<span style="color:#308080; ">(</span>username<span style="color:#308080; ">)</span><span style="color:#308080; ">)</span><span style="color:#406080; ">;</span>
</pre>

<pre style="color:#000020;background:#f6f8ff;"><span style="color:#308080; ">(</span><span style="color:#308080; ">&amp;</span><span style="color:#308080; ">(</span>objectClass<span style="color:#308080; ">=</span>user<span style="color:#308080; ">)</span><span style="color:#308080; ">(</span>cn<span style="color:#308080; ">=</span>abcuser<span style="color:#308080; ">)</span><span style="color:#308080; ">)</span>
</pre>

**How to reproduce:**

- Get an IS-5.10.0 pack
- Configure UniqueIDActiveDirectoryUserStoreManager as a secondary userstore.
- Create a new user in there and try to update the user profile through management console.

**Environment information**  **:**
 - Product Version: [IS 5.10.0]
 - Userstore: [AD(Windows Active Directory 2016) ]

[1] - https://github.com/wso2/carbon-kernel/blob/v4.6.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/UniqueIDReadWriteLDAPUserStoreManager.java#L983
[2] - https://github.com/wso2/carbon-kernel/blob/v4.4.35/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/ActiveDirectoryUserStoreManager.java#L234
[3] -  https://github.com/wso2/carbon-kernel/pull/2653
[4] - https://github.com/wso2/carbon-kernel/blob/v4.6.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/UniqueIDReadWriteLDAPUserStoreManager.java#L955

**Comment by jvitor83** [comment]
@isuruirj @janakamarasena There is any workaround to the "Issue 02" reported by @isuruirj that won't need to change the code? to fix in 5.10.0
