### ISSUE TITLE
[IMPROVEMENT] Delays in IdP update when there is a large number of SPs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8046]
**Describe the issue:**
There is a listener called `ApplicationIdentityProviderMgtListener` [1]. When we update an IdP, the listener's `doPreUpdateIdP()` gets hit and it does followings.
* Get a list of all SP names in the tenant
* Iterate the name list and fetch SP objects (a huge on DB since there are multiple queries for each SP)
* Iterate through the SPs and check whether any associated SP breaks due to disabling IdP (or one authenticator).

This flow causes a considerable delay for IdP update operation and causes LB timeouts.

**How to reproduce:**
Create around 100K service providers and try to update an IdP. There will be a huge delay.

**Expected behavior:**
Other than going through all the SPs to check the associations, we should query the associated SPs for the IdP in the consideration directly from the DB and do the validation. 

**Environment information** 
 - Product Version: All

**Related issues**
https://github.com/wso2/product-is/issues/6065

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationIdentityProviderMgtListener.java

**Comment by mefarazath** [comment]
AFAIR @emswbandara introduced an API to find associated SPs with an IDP. 

We also have https://is.docs.wso2.com/en/latest/develop/idp-rest-api/#/Connected%20Apps/getConnectedApps REST API to get the connected apps.

We should be able to make use of this API and implement the change suggested by @rksk

**Comment by mefarazath** [comment]
I would consider this as an issue :)
