### ISSUE TITLE
[FEATURE] Integrating Open Policy Agent with WSO2 Identity Server.

### ISSUE THREAD

**Issue by nimashanishadi** [wso2/product-is#8054]
### **Feature :**

Open Policy Agent (OPA) is a policy engine that can be used to implement fine-grained access control for your application and It provides greater flexibility and expressiveness than hard-coded service logic or ad-hoc domain-specific languages and comes with powerful tooling to help anyone get started and also expresses policies in a high-level, declarative language called Rego which promotes safe and fine-grained controls.

 In WSO2 Identity Server, currently using XACML to write authorization policies. If we integrate OPA as well,it will be a great opportunity as it is a highly practical solution for the critical security and policy challenges of the cloud-native ecosystems.

### **Use-cases :**

_Mainly we can use OPA with WSO2 IS to achieve_

1. To define authorization policies (e.g role based authorization, user-attribute based authorization).
2. To define authentication policies in OPA. I.e pass the set of authenticators of an authentication step to OPA, and based on the OPA policy result, construct the authentication step dynamically.
3. To completely delegate authentication sequence generation to OPA. E.g. pass cookies, ip-address to OPA and OPA can evaluate the policies based on the data that we send and send us back the authentication sequence.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
