### ISSUE TITLE
Patch Replace does not work for sub attribute of manager (multi-valued) - SCIM2

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8056]
**Describe the issue:**
We've used the below payload to replace a multi-valued attribute which is a sub-attribute of the manager.
`{
    "Operations": [
        {
            "op": "replace",
            "value": {
                "EnterpriseUser": {
                    "manager":{
                    	"custom1":["new1","new2"]
                    }
                }
            }
        }
    ]
}`
However, it does not replace the new value, instead the previous value remains the same.
Refer the [line](https://github.com/wso2/charon/blob/master/modules/charon-core/src/main/java/org/wso2/charon3/core/utils/PatchOperationUtil.java#L3464)

**How to reproduce:**
1. Create a SCIM EnterpriseUser->manager.custom multi-valued attribute ("multiValued":"true").
2. Add values to the custom attribute (We've used SCIM add as below)
  `{
    "Operations": [
        {
            "op": "add",
            "value": {
                "EnterpriseUser": {
                    "manager":{
                    	"custom1":["old1","old2"]
                    }
                }
            }
        }
    ]
}`
3. Update the values using SCIM replace as given in the description.

**Expected behavior:**
The values should be replaced with the new values given.

**Environment information** 
IS 5.7.0

**Comment by janakamarasena** [comment]
This issue is fixed in the current master with https://github.com/wso2/charon/pull/175
