### ISSUE TITLE
[ISSUE] SAML Logout HTTP-Redirect

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#8057]
**Describe the issue:**
I have configured a trust connection between a SAML 2.0 Shibboleth SP and WSO2 IS 5.9.0. When configuring frontend logout on HTTP-Redirect I receive an error. The SP cannot inflate the logout response.
After tracing the message flow it seems that WSO2IS is sending the logout response via a Form POST. The SAML2 standard states the response should be sent via an Location header for HTTP-Redirect.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.9.0
 - OS: Linux

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
