### ISSUE TITLE
Handle empty userstores with allowed_userstore property 

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#8073]
**Describe the issue:**
When  `allowed_userstore` property is configured with empty user stores, Add user store view breaks in the management console. 

**How to reproduce:**
Configure `allowed_userstore` property, but with zero user stores. Then try to click on add user store button in the management console.

**Expected behavior:**
Add user store view should be displayed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:** n/a

**Comment by ayshsandu** [comment]
@thanujalk can you please verify whether this is fixed in 5.11.0?

**Comment by thanujalk** [comment]
This fixed and can provide the configuration as,

[user_store_mgt]
allowed_user_stores = [
    "org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager",
    "org.wso2.carbon.user.core.ldap.UniqueIDActiveDirectoryUserStoreManager",
    "org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager",
    "org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager"
  ]
