### ISSUE TITLE
[QUESTION] application-authentication.xml overwritten 

### ISSUE THREAD

**Issue by altounsi** [wso2/product-is#8080]
I am moving from IS 5.7 to IS 5.10
I want to do some changes to application-authentication.xml but each time I start the server, the configuration get overwritten and back to the original one. What I want is simple : comment one line and replace it with other. 

This is a snippet from application-authentication.xml in IS 5.7 
 under Extensions tag 

I want this line to be COMMENTED 
`<!--StepBasedSequenceHandler>org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler</StepBasedSequenceHandler-->`

and replaced with this:
`<StepBasedSequenceHandler>com.me.iam.handlers.CustomStepBasedSequnceHandler</StepBasedSequenceHandler>`

**Comment by mefarazath** [comment]
Hi @altounsi,

From IS 5.9.0 we have moved to a toml based configuration. Idea is to use a single file to configure everything that was achieved with multiple XML files. You can learn more about this from https://is.docs.wso2.com/en/latest/references/new-configuration-model/#new-configuration-model

You can find the corresponding key to be added to the IS_HOME/repository/conf/deployment.toml file from either docs or from the templated files in repository/resources/conf/templates/repository/conf/identity/* files.

For example in your case you need to find the application-authentication.xml. You can find the corresponding templated file in repository/resources/conf/templates/repository/conf/identity/application-authentication.xml.j2. The key you need to add can be found as,

```
<StepBasedSequenceHandler>{{authentication.framework.extensions.step_based_sequence_handler}}</StepBasedSequenceHandler>
```

The corresponding value to be added to the deployment.toml would be,

```
[authentication.framework.extensions] step_based_sequence_handler="com.me.iam.handlers.CustomStepBasedSequnceHandler"
```

**Comment by altounsi** [comment]
@mefarazath Thank you so much for your fast and accurate reply. That was informative and did work for me.

**Comment by mefarazath** [comment]
Glad the answer helped. 

For questions and discussions i would encourage you to join our slack group https://join.slack.com/t/wso2is/shared_invite/enQtNzk0MTI1OTg5NjM1LTllODZiMTYzMmY0YzljYjdhZGExZWVkZDUxOWVjZDJkZGIzNTE1NDllYWFhM2MyOGFjMDlkYzJjODJhOWQ4YjE
