### ISSUE TITLE
[FEATURE] Fixed User Session Timeout 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#8081]
### **About the feature**
We already have a feature to force authentication after a default ideal timeout period. There can be a scenario that requires a force authentication( or log out the user) after a pre-defined time even though the user is active (not exceeding the ideal timeout).

In the current product, there is no such implementation in the product to support this requirement.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
