### ISSUE TITLE
[ISSUE] User Dashboard gadgets in Internet Explorer

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#8082]
**Describe the issue:**
I have installed WSO2IS 5.9.0 on Windows and when testing the user dashboard in IE, the gadgets are not loaded. The console offers the following errors:
![image](https://user-images.githubusercontent.com/45126217/79119091-3079a180-7d98-11ea-9a09-671128302d9c.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.9.0
 - Internet Explorer 11.719.18362.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
