### ISSUE TITLE
[ISSUE] Invalid authenticationOptions in adaptive script is not handled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8084]
**Description:**
When invalid authentication options are defined for `executeStep()`, the behaviour is different for two cases. No proper error logs are written in either case
* IndexOutOfBoundsException when there are more than one options are defined from the same type (eg: two SAML idps)
* It works fine if we have only one option from a give federated authenticator. (eg: two options SAML & OIDC)

**How to reproduce:**
- Add two federated IdPs to step01 (they should be using the same federated authenticator)
- Then configure following script with an invalid IdP name
```
function onLoginRequest(context) {
  	var idpName = "invalid_idp";
	executeStep(1,{authenticationOptions:[{idp:idpName}]} ,{
		onSuccess: function (context) {  
			Log.info("step1 is done");
		}
	});
}
```
Following error logs is written without giving any idea on what is going on
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:242)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleAuthenticationStep(GraphBasedSequenceHandler.java:414)
```

**Expected behavior:**
It should provide clear error logs when invalid authentication options are defined.

**Related issues:**
https://github.com/wso2/product-is/issues/3983

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
