### ISSUE TITLE
Not able to fetch custom user profile claims using oauth2/userinfo API

### ISSUE THREAD

**Issue by AmreeshTyagi** [wso2/product-is#809]
I am using WSO2 IS 5.2.0. I am trying to access custom claim `mobile_verified` . I have already created a mapping between "http://wso2.org/oidc/claim" dialect to "http://wso2.org/claims" dialect as mentioned on http://stackoverflow.com/questions/37074119/wso2-identity-server-not-returning-requested-claims-with-oauth-openid . Also, I have added this custom claim to openId scope in OIDC file using registry.

Is there any issue with 5.2 version, because it was working fine with 5.1?
![claim mapping in claims dialect](https://cloud.githubusercontent.com/assets/19740/20057766/6f2da4fa-a513-11e6-93b8-70d5a48f0077.png)
![claim mapping in oidc dialect](https://cloud.githubusercontent.com/assets/19740/20057767/6f3597e6-a513-11e6-9a88-6ff1cdf1f011.png)
![claim config in sp](https://cloud.githubusercontent.com/assets/19740/20057694/f642ddb2-a512-11e6-90ee-8e4b9ef77a10.png)
![custom claim added to oidc](https://cloud.githubusercontent.com/assets/19740/20057695/f64767a6-a512-11e6-8f59-f0a0dfabaf85.png)

**Comment by mefarazath** [comment]
I guess you have made sure that the claim is not empty in the particular user's profile. BTW are other claims returned with the user info response? Can you try with an existing claim like email?

**Comment by AmreeshTyagi** [comment]
It worked after removing **mobile_verified** value from **mobile** property which is mentioned in 3rd line from top. I don't know how, but it is working fine now. Closing this issue.
