### ISSUE TITLE
[FEATURE] - Retrieve locales of all the added email templates per email template type

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8090]
Currently the `email template type` api `GET` returns only an array of `template type` objects which consists of `id`, `displayName` and `self`.  A requirement of displaying locales of each added `email template` is required. 

**Describe the solution you would prefer**
Ideally there should be an additional parameter named `locales` per email template type which should consist of an array of all the locales which are used in a email template type.

**Comment by thanujalk** [comment]
@emswbandara can we have the requeriedAttribute support for this API?

**Comment by emswbandara** [comment]
If we query the set of templates of a particular template-type , you should be able to get the list of locales ( identified by the id attribute of the resulting json objects.) E.g. for account-recovery template type. if you query the  templates endpoint as follows,

`email/template-types/QWNjb3VudElkUmVjb3Zlcnk/templates`

output will be as follows which lists down all the locales it supports.
```
[
    {
        "id": "en_US",
        "self": "/t/carbon.super/api/server/v1/email/template-types/QWNjb3VudElkUmVjb3Zlcnk/templates/en_US"
    }
]
```
Is there a problem in retrieving the locales using this approach? @thanujalk @DimalChandrasiri

**Comment by DimalChandrasiri** [comment]
@emswbandara yes once approach is to query the `email template types` and for each template type again query the `email templates` to get the locales. But in my requirement I need to query all of the available `template types` to get what are the `locales` implemented per `template type`. 

The visual representation is as following. Which will list down all of the email `template types` and the `locales` of the available templates for each `template type`.

![Screenshot 2020-04-16 at 14 19 41](https://user-images.githubusercontent.com/11191791/79435810-bf332c00-7fed-11ea-9650-cb0aa30d0ac3.png)

IMO querying all of the templates in template types would make a performance hit on the server as well. WDYT?

**Comment by emswbandara** [comment]
Even for the template-types GET call, we are retrieving all the templates per template-type from the backend registry.. only in the API level we are doing the filtering.. in that case we can support requiredAttribute support for the template-types resource as following.

`email/template-types?requiredAttributes=templates.id`

The output will be similar to 
```

[
    {
        "id": "VE9UUA",
        "displayName": "TOTP",
        "templates" {
                            "id" : "en_US"
          }
         "self": "/t/carbon.super/api/server/v1/email/template-types/VE9UUA"
    }
]
```

**Comment by emswbandara** [comment]
In that case we can add requiredAtribute support for template-types API. As I checked, from the backend registry we are retrieving all the templates of a template-type for the template-types GET call. Only from the API level we are doing the filtering. Therefore supporting requiredAttributes can be done from the API level. 

Request
`email/template-types?requiredAttributes=templates.id`

Output

```
[
    {
        "id": "VE9UUA",
        "displayName": "TOTP",
        "templates":  [
                               {
                                "id" : "en_US"
                               }
                           ]
        "self": "/t/carbon.super/api/server/v1/email/template-types/VE9UUA"
    }
]
```
