### ISSUE TITLE
Improve the way locale is set in the user account

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8091]
When self-register regardless of the browser locale, 'en' is set as the local claim of the account.

**local** claim needs to be enabled by default to have above functionality, otherwise, the local claim is not set in the account.

Additionally, from the developer portal if we can capture the locale claim and give a dropdown to select the user's locale for admins that would be ideal. 

From the user-portal also, I'd like to see a drop-down with available locales for the locale claim.

**Comment by abhi4u1947** [comment]
Yes, its really a must to have feature, getting user local from identity system is really very important when securing other application with identity server and we have to show right user local in those applications along with identity server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
