### ISSUE TITLE
[ISSUE] The permission of the User search filter should be changed to View permission

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#8093]
![image](https://user-images.githubusercontent.com/9637873/79341711-d7516f80-7f49-11ea-9028-8ed2062e488f.png)

Theoretically this should be a type of list Users based on a filter. Hence the permission level should be changed to 
  `
<Permissions>/permission/admin/manage/identity/usermgt/list</Permissions>`
  `<Scopes>internal_user_mgt_list</Scopes>`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
