### ISSUE TITLE
[ISSUE]The basic authenticator is not displayed in the login page when the user is redirected to the multi-option login page after authentication failure due to account locking.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8094]
**Describe the issue:**
The basic authenticator is not displayed in the login page when the user is redirected to the multi-option login page after authentication failure due to account locking.

**How to reproduce:**

- Set up a multi-option login page with a basic and federated authenticator.
- Enable account locking and Lock the account of a user.
- Try to log in the locked user, on failure, the basic authenticator is not displayed in the login page
<img width="1678" alt="Screen Shot 2020-04-15 at 7 41 13 PM" src="https://user-images.githubusercontent.com/47600906/79347444-54341780-7f51-11ea-91bc-45466142f52e.png">

Product Version: IS 5.8.0

**Cause**
The authenticatorNames[1] is not URL encoded when creating the redirect URL.
[1]https://github.com/wso2-support/carbon-identity-framework/blob/support-5.12.387/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/step/impl/DefaultStepHandler.java#L764

**Comment by Abilashini** [comment]
The public fix is done with https://github.com/wso2/product-is/issues/7961
