### ISSUE TITLE
Implement AuthorizationCodeValidityPeriod config in the SOAP API

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8098]
AuthorizationCodeValidityPeriod config has to be added to the SOAP API in order for it to be used in the current Management Console.

**Comment by ruwanta** [comment]
Hi @ivantha ,
Can you explain why this feature is needed please.

Ideally validity period of auth code should be few seconds, and needed to be a configuration done per deployment considering the maximum permissible round trip time over the applications participating, and the level of security an organisation needs. It is not something to be changed arbitrary.

**Comment by ivantha** [comment]
> Hi @ivantha ,
> Can you explain why this feature is needed please.
> 
> Ideally validity period of auth code should be few seconds, and needed to be a configuration done per deployment considering the maximum permissible round trip time over the applications participating, and the level of security an organisation needs. It is not something to be changed arbitrary.

Hi @ruwanta, 

As per my understanding, when the IS moves to the cloud every user will basically be a tenant i.e. organization. A globally configured AuthorizationCodeValidityPeriod at the server level might not cater to the requirements of every organization. Therefore, there exists a requirement for the AuthorizationCodeValidityPeriod configuration to be changed at the app level. 

This issue addresses a part of the aforementioned requirement.

**Comment by ruwanta** [comment]
Hi @ivantha ,
What you might looking for is to configure the value per tenant. That requirement is valid, as it applies the login process.
However -1 on having this per application (Service Provider) as I can  not see a valid requirement.

**Comment by ivantha** [comment]
Closing this as AuthorizationCodeValidityPeriod should not be changed at the app level.
