### ISSUE TITLE
Support AuthorizationCodeValidityPeriod config in the Management Console

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8099]
AuthorizationCodeValidityPeriod config should be able to be configured in the Management Console per app.

**Comment by ruwanta** [comment]
Hi @ivantha ,
Can you explain why this feature request is required please.

**Comment by ivantha** [comment]
> Hi @ivantha ,
> Can you explain why this feature request is required please.

Hi @ruwanta,

Please refer to https://github.com/wso2/product-is/issues/8098#issuecomment-614377028 as the context is similar. 

THX

**Comment by ivantha** [comment]
Closing this as AuthorizationCodeValidityPeriod should not be changed at the app level.
