### ISSUE TITLE
Implement unit tests for the AuthorizationCodeValidityPeriod at DAO layer

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8101]
The functionality of AuthorizationCodeValidityPeriod should be tested using unit tests at the DAO layer in [identity-inbound-auth-oauth](https://github.com/wso2-extensions/identity-inbound-auth-oauth).

**Comment by ruwanta** [comment]
+1

**Comment by ivantha** [comment]
Closing this as AuthorizationCodeValidityPeriod should not be changed at the app level.
