### ISSUE TITLE
UX improvements for Windows (WPF) sample

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8104]
We need to improve the samples to adhere our own theming. Currently, samples are created using default Windows theming. 

Following improvements are suggested.
* Use modern FX styling to support latest Windows distributions.
* Change the colours to go with our colour pallet.
* Theming should be consistent with other samples.
* Add visual FX for transitions (Optional)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
