### ISSUE TITLE
WPF Sample Documentation

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8105]
**Problem description**
There should be a way for guide users on how to use WPF sample in order to integrate .NET SDK and use it.

**Preferred Solution**
Have a documentation README within the project repository. And optionally have a comprehensive guide within WSO2 Identity Sever public docs.

**Comment by darshanasbg** [comment]
@sherenewso2 @gomathyk will help on reviewing final content.

**Comment by gomathyk** [comment]
Reviewed the sdk and the sample with PRs, https://github.com/wso2-extensions/identity-sdks-dotnet/pull/5 and https://github.com/wso2-extensions/identity-samples-dotnet/pull/9.
