### ISSUE TITLE
Have side panal to show the personalized resouce file (installer conf)

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8110]
In the Console side panel, we should provide an option to download a customised resource file that can be used with the installer. It should contain the information as configured in the console (Ex: with correct client id, client secret etc...)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
