### ISSUE TITLE
Improve the installer to point a resouce file

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8111]
Currently installer has a hard coded resource file (Packed with the installed). We should provide an option to take a custom file by asking a path to the custom file from user. However, this step should be optional. By default packed resource file should be used. 

Related to:  https://github.com/wso2/product-is/issues/8110

**Comment by ayshsandu** [comment]
@JKAUSHALYA can you please add more description on the task.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
