### ISSUE TITLE
Identity claims does not reflect the claim value when used as placeholders in "Account Confirmation" email templates

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#8121]
**Description**
Identity claims does not reflect the claim value when used as placeholders in **"Account Confirmation"** email templates

**How to reproduce:**
1. Add a placeholder for an identity claim in the **"Account Confirmation"** email template. ex: `{{user.claim.identity.emailVerified}}`
2. Try the user self-registration REST API with a value for the above claim in the request payload.
ex: `http://wso2.org/claims/identity/emailVerified `

**Expected behaviour:**
Reflect the value of the identity claim in the placeholder when the account confirmation email is sent to the user.

**Environment information:**
 - Product Version: IS 5.7.0

**Workaorund:**
Assuming that the identity claim used for the email template was `http://wso2.org/claims/identity/emailVerified `
1. In the email template replace all the usages of `{{user.claim.identity. emailVerified }}` with `{{emailVerified}}` and save the template.

2. Under the `properties` in the request payload you have given above, you need to include an additional property called `emailVerified` and the respective value (same value given for the `emailVerified` identity claim). See the example below.

```
{
    "user": {
        "username": "john",
        "realm": "PRIMARY",
        "password": "passwd",
        "claims": [
         ...
            {
                "uri": "http://wso2.org/claims/identity/emailVerified",
                "value": "something"
            }
         ...
        ]
    },
    "properties": [
         ...
        {
            "key": "emailVerified",
            "value": "something"
        }
         ...
    ]
}
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
