### ISSUE TITLE
[ISSUE] Enable admin forced password reset via SCIM 2.0 available by default

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8136]
Steps to reproduce,

1. Follow the steps in https://is.docs.wso2.com/en/latest/learn/forced-password-reset to enable  `Enable Password Reset via OTP` option.
2. Add 'forcePasswordReset' as a SCIM 2 extension.
![admin-force](https://user-images.githubusercontent.com/5061791/79630224-3511d180-816d-11ea-93ab-382fa791fe93.png)
3. Use the following SCIM 2.0  patch request.
```
POST https://<host>:<port>/scim2/Users/<users-scim-id>

{"schemas": 
["urn:ietf:params:scim:api:messages:2.0:PatchOp","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],
 "Operations": [
 	{"op": "add",
 	"value": {"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {"forcePasswordReset": true}
}}]
}
````

If we add **forcePasswordReset** to SCIM 2 extensions by default, will be straightforward.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
