### ISSUE TITLE
[ISSUE] isUserAuthorized() fails due to case mismatch of internal roles

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8137]
**Describe the issue:**
In `isUserAuthorized()` of `JDBCAuthorizationManager` [1], we get a list of roles that are allowed to perform a given action by invoking `getAllowedRolesForResource()`. When it comes to application roles, the returned role names contain the domain in upper case (eg: APPLICATION/testrole). But the role names stored in `UM_HYBRID_ROLE` table the `UM_ROLE_NAME` column has role names with domain prepended which have first letter only in upper case (eg: Application/testrole).

Previously, there was no issue since we had get user's role list and did a `.equalsIgnoreCase()` comparison with the allowed roles.

But as a fix for https://github.com/wso2/product-is/issues/5797, we have done some improvements where we do not query all the internal roles of the user instead we filter the required role only. 

Hence, now it fails to check the user role due to this case mismatch.
We query for `UM_HYBRID_ROLE.UM_ROLE_NAME`='APPLICATION/testrole'`
But the actual value in DB is `Application/testrole`

`AbstractUserStoreManager.isUserInRole()` [2] has following line.
```
String[] internalRoles = doGetInternalRoleListOfUser(userName, roleName);
```

**How to reproduce:**

1. Use a case-sensitive DB for UMDB (eg: H2)
2. Create an internal role (eg: Application/login) and add login permission to it
3. Create a user and add the above role
4. Try to login to mgt console with the new user
5. Login is failed (the debug logs will say the user is not in APPLICATION/login role)

- If we login as admin user, view the role list of the new user (role list get cached) and try to login with new user, it works
- If enable "GetAllRolesOfUserEnabled" from user-mgt.xml, it works without an issue (*workaround*)

**Environment information**
 - Product Version: IS 5.7.0 (WUM), 5.9.0(GA) & later
 - Database: Any case sensitive DB

**Related issues:**
https://github.com/wso2/product-is/issues/5797

[1] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/authorization/JDBCAuthorizationManager.java
[2] https://github.com/wso2/carbon-kernel/blob/4.5.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L4052

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
