### ISSUE TITLE
Improve Authenticator and Provisioning Connector Metadata response display names

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#8141]
**Describe the issue:**
Display names and display names of the properties in the authenticator and provisioning connector metadata responses can be improved in ways such as,

- Using camel case
- Using spaces where required
etc.

**How to reproduce:**
Observe display names in the aforementioned metadata responses.

**Expected behavior:**
Proper display names should be available for better UX.

**Comment by ayshsandu** [comment]
Following Authenticators Remain to be fixed:

1.  FacebookAuthenticator
  `"displayName": "facebook",`
2. TwitterAuthenticator
   ` "displayName": "twitter",`
3. PassiveSTSAuthenticator
    `"displayName": "passivests"`
4. SAMLSSOAuthenticator
    `"displayName": "samlsso"`
5. OpenIDConnectAuthenticator
    `"displayName": "openidconnect"`

Following Provisioning Connectors Remain to be fixed:
1. SCIM Provisioning Connector
    `"displayName": "scim"`
2.  Salesforce Provisioning Connector
    `"displayName": "salesforce"`
3. Google Provisioning Connector
   ` "displayName": "googleapps"`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
