### ISSUE TITLE
[IMPROVEMENT] Write an extension to configure password hashing mechanism

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#8142]
We have many usercase where passwords need to be migrated without any issue, by the same hashing algorithm. In that case it is good if we have an extension to configure the hashing algorithm. So that we can use the same password when migrating users.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
