### ISSUE TITLE
[IMPROVEMENT] Add the required additional query params in the OIDC response

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#8149]
**Is your suggestion related to an experience ? Please describe.**
In case, if we need to pass the captured email address from the user on the identity server to the federated identity providers over the login_hint parameter, in OpenIDConnectAuthenticator we can set the following Additional Query Parameters in the UI to retrieve the dynamic value for the param from the request.
`login_hint=${fidp}`

But say if the value for the param is not present in the request, but it is available in a cookie or Since we have adaptive script functionality as of now, we can retrieve the user identifier based on some condition and we can't use the above functionality to add the required additional query params with captured values from an adaptive script.

In such a case, we can introduce a new pattern in OpenIDConnectAuthenticator as follows to capture the additional param from the adaptive script.
` login_hint=$authparam{paramName}`
And improve the OpenIDConnectAuthenticator to interpret the query string with additional params that are captured from the adaptive script.
 

**Describe the improvement**

**Additional context**

**Comment by mefarazath** [comment]
@Kanapriya is this the same pattern we have used in SAML outbound authenticator for supporting resolving values for query param place holders?

**Comment by Kanapriya** [comment]
No,

- in SAML we are using the pattern for supporting dynamic query params as follows:
`login_hint={paramName}`
- and in OIDC for the same capability the following pattern being used.
`login_hint=${paramName}`
- Now introduced the following pattern in OIDC to capture the authenticator params from the adaptive script and interpret the query string with the captured values
`login_hint=$authparam{paramName}`

**Comment by malithie** [comment]
> * in SAML we are using the pattern for supporting dynamic query params as follows:
>   `login_hint={paramName}`
> * and in OIDC for the same capability the following pattern being used.
>   `login_hint=${paramName}`
> * Now introduced the following pattern in OIDC to capture the authenticator params from the adaptive script and interpret the query string with the captured values
>   `login_hint=$authparam{paramName}`

Isn't there an inconsistency of the form used in SAML and OIDC, and also using authenticator params from the adaptive script is being utilized only in OIDC authenticator?
@Kanapriya

**Comment by mefarazath** [comment]
> > * in SAML we are using the pattern for supporting dynamic query params as follows:
> >   `login_hint={paramName}`
> > * and in OIDC for the same capability the following pattern being used.
> >   `login_hint=${paramName}`
> > * Now introduced the following pattern in OIDC to capture the authenticator params from the adaptive script and interpret the query string with the captured values
> >   `login_hint=$authparam{paramName}`
> 
> Isn't there an inconsistency of the form used in SAML and OIDC, and also using authenticator params from the adaptive script is being utilized only in OIDC authenticator?
> @Kanapriya 
There seems to be an inconsistency in the format.

Support for using adaptive script params for SAML outbound was added in https://github.com/wso2/product-is/issues/8552

**Comment by rksk** [comment]
Doc issue; https://github.com/wso2/docs-is/issues/1628

**Comment by Kanapriya** [comment]
Verified the flow with wso2is-7.0.0-pre-RC.zip and its working as expected.

https://github.com/wso2/product-is/assets/13362482/50c499cd-24af-4ac0-9c23-d16f0727e82d
