### ISSUE TITLE
Setting 'renew_access_token_per_request' does not affect to refresh token

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#8150]
**Describe the issue:**

Setting the below property does not affect to refresh token. Only the access token is renewed per each request.

```
[oauth.token_renewal]
renew_access_token_per_request= "true"
```

**Steps to reproduce:**
- Add the above property to the deployment.toml file and start the server.
- Create a new OAuth SP and execute a password grant call to obtain a token.
```
curl -u <CLIENT_ID:CLIENT_SECRET> -k -d "grant_type=password&username=admin&password=admin" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/oauth2/token
```
- Only the access token will be changed per each request.

**Expected behavior:**
Refresh token should also be changed, according to the official doc. [1] 

[1] - https://is.docs.wso2.com/en/latest/learn/issuing-new-tokens-per-request/

**Comment by Manukam** [comment]
Observed the same in IS 5.9.0 latest WUM. This works properly in the GA release

**Comment by vihanga-liyanage** [comment]
This is already fixed in the master.
