### ISSUE TITLE
[ISSUE] Authentication prompts before validating IdP init SSO is enabled for the SP

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#8151]
**Describe the issue:**
When an IdP initiated SSO flow in triggered for a specific service provider without enabling 'IdP Init SSO' for that SP, validation happens only after the login is prompted. 

**How to reproduce:**
- Configure a SAML SP without enabling 'IdP Init SSO'
- Initiate a IdP initiated SSO flow for the SP
- Observe that login prompts 
- Upon providing credentials note that you will be redirected to an error

**Expected behavior:**
Validation for the configuration of the service provider (request validation) should happen prior to authentication. 

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
