### ISSUE TITLE
Provide Method to Add Custom Parameters to OAuth error response.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8155]
**Is your feature request related to a problem? Please describe.**
When implementing a custom grant handler it is possible to add parameters to the success response[1] but it is not possible to add custom parameters to error responses.

**Describe the solution you would prefer**
Provide Method to Add Custom Parameters to OAuth error response to make it consistent across both success token responses and error responses

[1]https://github.com/wso2/product-is/issues/3194

Effort BE::5

**Comment by IsuraD** [comment]
This is already supported. Please check.  https://wso2.org/jira/browse/IDENTITY-6200
@mefarazath @tharakawijekoon What is additionally expected here?

**Comment by tharakawijekoon** [comment]
current error response :
```{"error_description":"Error when handling event : PRE_AUTHENTICATION","error":"invalid_grant"}```
expected error response with additional parameter:
```{"error_description":"Error when handling event : PRE_AUTHENTICATION","custom_error_code":"testing","error":"invalid_grant"}```

Currently, this can only be done in success responses.

**Comment by mefarazath** [comment]
Is this something admissible by the spec?

Something I have noticed is that in error scenarios generally the spec restricts the information that can be sent out and certain compliance suites strictly check whether unnecessary additional information is passed.

@tharakawijekoon will it be possible to explain a use case where this would be useful?

**Comment by tharakawijekoon** [comment]
It seems the spec provides room for extensibility[1]. To register new request/response parameters[2] or error codes[3] the procedure mentioned in section [11.2](https://tools.ietf.org/html/rfc6749#section-11.2) and [11.4](https://tools.ietf.org/html/rfc6749#section-11.4) should be followed to add them to the OAuth Parameters registry or OAuth Extensions Error registry. If these parameters that are added are registered, there should not be an issue adding the parameter to the response. 

If a client wants to get an additional error code with errors returning from the token endpoint this might be useful.

[1]https://tools.ietf.org/html/rfc6749#section-8
[2]https://tools.ietf.org/html/rfc6749#section-8.2
[3]https://tools.ietf.org/html/rfc6749#section-8.5

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
