### ISSUE TITLE
[FEATURE] Adding role based scope validator for WSO2 IS

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-is#8163]
Currently, WSO2 API Manager has the capability of issuing token scopes based on the user's roles. ATM it is done by plugin custom grant handlers. 
We would like to have a similar feature from WSO2 IS as a first-class feature.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
