### ISSUE TITLE
Improvements to the Device Flow

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#8166]
This issue is a reference to track related improvements that need to be done to the Device Flow.

**Device Flow**

- [x] https://github.com/wso2/product-is/issues/7812
- [x] https://github.com/wso2/product-is/issues/7750
- [x] https://github.com/wso2/product-is/issues/7348
- [x] https://github.com/wso2/product-is/issues/8471

Sample app
- [ ] https://github.com/wso2/product-is/issues/9011

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
