### ISSUE TITLE
[ISSUE] No exact permission subset for managing users and assigning/unassigning roles to users

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8176]
**Describe the issue:**
WSO2 IS has fine-grained permissions for most of its sub features within user management. However, there seems to be lot of limitations/usability issues. Specifically I cannot find an exact permission subset for managing user lifecycle, password, profile and assign/unassign their roles.

**How to reproduce:**
I tried giving all the permissions that I can logically relate to user management, but then I was able to manage roles and permissions for roles as well.
Then I tried removing permissions one by one that I can logically relate role management, but then I was not able to assign/unassign roles to users as well.

**Expected behavior:**
My requirement is to give identity administrators full permission to manage user lifecycle, password, profile and assign/unassign their roles. But the identity administrators must not be able to manage roles (create/delete/update) or manage permissions for roles.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
