### ISSUE TITLE
[IMPROVEMENT] Unable to set properties to authentication context from adaptive authentication script

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8177]
**Describe the improvement**
Unable to set properties to authentication context from adaptive authentication script.

**Additional context**
This improvement is vital in order to reduce the amount of customizations we need to do for unique business use cases. If there is no way to set properties to authentication context from adaptive authentication script to be used in a custom claim handler, we have to resort to writing a custom authenticator.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Should be covered with https://github.com/wso2-enterprise/iam-product-management/issues/284
