### ISSUE TITLE
[IMPROVEMENT] Unable to force a particular authentication step from adaptive authentication script

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8178]
**Describe the improvement**
Need the ability to force a particular authentication step from adaptive authentication script, even if SSO logic passes.

**Additional context**
There are unique business requirements we come across where we need to be able to force a particular authentication step, even if SSO logic passes. This of a scenario where username/password authentication has to be done twice in order to get access to a certain part of the application. E.g. in a checkout portal, the cashier logs in first and does his/her routine tasks. But for a very specific function of the portal, needs elevated login by manager. The manager comes in and authenticates with his/her username/password and provides a one-time access to the cashier. Currently this cannot be done unless we write a custom authenticator.

This improvements becomes even more powerful when coupled with the improvement suggested in #8177.

**Comment by rksk** [comment]
This is done with https://github.com/wso2/carbon-identity-framework/pull/2961, but not documented yet. Created a doc issue https://github.com/wso2/product-is/issues/10973.
