### ISSUE TITLE
[IMPROVEMENT] Unable to set transient local claims or local roles to the authentication context from adaptive authentication script

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8179]
**Describe the improvement**
Unable to set transient local claims or local roles (claims or roles that don't get stored in the userstore) to the authentication context from adaptive authentication script.

**Additional context**
Transient claims or roles can only be set for remote claims or remote roles. However, in local authentication scenarios remote claims or remote roles are not even considered. So there is no way to set a transient local claim or local roles and use it in OAuth2  ResponseTypeHandler, AuthorizationGrantHandler, IDTokenGenerator or AccessTokenIssuer. This means that if we are to achieve this today we have to write a custom ClaimHandler. But then again we can't pass contextual information to the claim handler due to limitation in #8177. So we are stuck with implementing a custom LocalAuthenticator.

This ultimately means that, for a requirement I could have been done with implementing a OAuth2 level customization only (e.g. custom AccessTokenIssuer), now I have to implement a custom LocalAuthenticator and a custom ClaimHandler.

These limitations in combination heavily curtails the ability of WSO2 IS to be implemented for unique business use cases.

**Comment by senthalan** [comment]
This is done with https://github.com/wso2/product-is/issues/9293. Hence closing it.
