### ISSUE TITLE
[ISSUE] Transaction log details getting duplicated in carbon console. 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#8184]
**Describe the issue:**

`INFO {TRANSACTION_LOGGER} - Type: OAUTH TOKEN | Info: {"expires_in_seconds":2527,"grant_type":"password","success":true,"scope":"openid","time_taken_in_millis":133,"type":"oauth","issued_time":1587962210000,"user":"admin@carbon.super","client_id":"7QU6udkxOwhrMWbNUk8xi128dCga"}`

Above log should be print as a transaction log from transaction appender and transaction logger

```
logger.TRANSACTION_LOGGER.name=TRANSACTION_LOGGER
logger.TRANSACTION_LOGGER.level=INFO
logger.TRANSACTION_LOGGER.appenderRef.TRANSACTION_LOGFILE.ref = TRANSACTION_LOGFILE
```

But this appears in carbon console using console appender. 

**Suggested Fix **
Add the following line to transaction logger 

logger.TRANSACTION_LOGGER.additivity = false

This happens because since additivity is default enabled this root logger will log a duplicate of child logger by disabling additivity this can be fixed

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
