### ISSUE TITLE
[ISSUE]Application rest api is not sending the correct inbound protocols

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8185]
**Describe the issue:**
When we call the GET request `api/server/v1/applications/<app-id>` for the specific application, it not sending the correct inboundProtocols. 

**How to reproduce:**
1.  Create a SAML or OIDC application
2.  Send GET request `api/server/v1/applications/<app-id>` for that app and check the  inboundProtocols section

**Comment by mevan-karu** [comment]
For 5.11.0-m16 pack following issue wasn't reproduced as given. But following behavior was observed;
- After enabling CAS inbound connector, every application gets a CAS inbound configuration with dummy values. 

### How to reproduce
1. Get the CAS inbound connector from the store and add to the IS server.
2. Create a SAML webapp.
3. View inbound configurations of the created webapp using `api/server/v1/applications/{application_id}/inbound-protocols`
