### ISSUE TITLE
[ISSUE] The subject of the public certificate generated for the tenant has no comma separating the Organization and Locality attributes 

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8193]
**Describe the issue:**
The subject of the public certificate generated for the tenant has no comma separating the Organization and Locality attributes.

```C=None,O=None L=None,OU=None,CN=tenant1.com```

This causes problems when importing the tenant public certificate to other entities which have strict verification[1]

[1]https://knowledge.digicert.com/solution/SO19408.html

**Cause:**
https://github.com/wso2/carbon-multitenancy/blob/master/components/tenant-mgt/org.wso2.carbon.tenant.keystore.mgt/src/main/java/org/wso2/carbon/keystore/mgt/KeyStoreGenerator.java#L160

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
