### ISSUE TITLE
Introduce a service url builder utility 

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#8194]
**Describe the improvement**
Need to incorporate a central utility that can be used to build service url using, server host, port, proxy host, proxy port and proxy context path configurations.
The utility should be able to build the internal service url and public service url given a service context path relative to tenant

**Comment by mefarazath** [comment]
@malithie Can we close this issue and open a new one for the pending improvements of the  service url builder?

Or keep this issue open until all the improvements related to the service URL builder are addressed?

**Comment by malithie** [comment]
Should link all service url builder improvements here and keep until we address the requirement fully

**Comment by malithie** [comment]
Planned improvements incorporated. Closing the issue.
