### ISSUE TITLE
[FEATURE] Need to add relevant metadata to tenant REST API

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#8202]
**Is your feature request related to a problem? Please describe.**

Currently created date is available in tenant API but we need to support the modified date as well. There will be more metadata attributes expected from the tenant API. This issue is to track the metadata attributes and support them through tenant API

**Describe the solution you would prefer**
Tenant API should give metadata attributes

**Comment by nilasini** [comment]
Related to https://github.com/wso2/product-is/issues/8047

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
