### ISSUE TITLE
[IMPROVEMENT] Supporting Display Name for supported grant types from identity.xml

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#8207]
**Is your suggestion related to an experience ? Please describe.**
This is related to this https://github.com/wso2/product-is/issues/7451 and here we have a hardcoded mapping in the API layer to define display name for supported grant types. Since the supported grant types are read from identity.xml, we can have another property in identity.xml to configure the displayName. So that if a new grant type is introduced, we don't need to change the API instead we can set the display name from the identity.xml file.

**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
