### ISSUE TITLE
Tenant qualify response content from /api/server and /api/user

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#8208]
**Description**

API response content includes relative URL endpoints and absolute URL endpoints of the references, in 'Location' header or in response body
Those needs to be tenant qualified, by adding the tenant domain as a path parameter in the URL. 

Please refer the following examples for tenant qualified relative URLs and tenant qualified absolute URLs in API response content.

Tenant domain : carbon.super
Relative URL : /api/server/v1/endpoint
Absolute URL : https://<HOST>:<PORT>/api/server/v1/endpoint

Tenant domain : test.com
Relative URL : /t/test.com/api/server/v1/endpoint
Absolute URL : https://<HOST>:<PORT>/t/test.com/api/server/v1/endpoint

- [x] /api/server
- [x] /api/user

**Comment by malithie** [comment]
Done
