### ISSUE TITLE
Decouple the authentication framework logic from the transport layer

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#8216]
**Is your feature request related to a problem? Please describe.**
Currently authentication framework logic coupled to http servlet requests, this limits its capabilities to work with other transports.

Also authentication framework is coupled with the need of browser involvement. Need to separate the need of the UI interaction with the authentication framework execution.

This need new architecture design.

This will also helps on centralizing current capabilities like,
- claim-transformation
- role-transformation
- jit-provisioning
- consent-handling
also be centralized and available (as applicable) for pure back channel flows such as password grant.

**Tasks**

- [ ] API for decoupled backchannel authentication - https://github.com/wso2/product-is/issues/8986

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
