### ISSUE TITLE
[ISSUE] Internal roles and Application roles not returned by SCIM group filter request

### ISSUE THREAD

**Issue by Manukam** [wso2/product-is#8223]
**Describe the issue:**
When retrieving Internal and Application roles via SCIM groups endpoint by using a filter they are not returned. This is working properly in IS 5.8.0. The following checks [1] are missing in 5.7.0 which leads to the issue.

[1] - https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3413

**How to reproduce:**
Execute the following SCIM requests after creating an SP role
`https://localhost:9443/scim2/Groups?filter=displayName+eq+Application/SP`
`https://localhost:9443/scim2/Groups?filter=displayName+eq+SP1`
`https://localhost:9443/scim2/Groups?filter=displayName+eq+Internal/system`

**Expected behavior:**
Application/SP role should be returned
Internal/system role should be returned

**Actual behavior:**
Empty result set

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.7.0
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mevan-karu** [comment]
**WUM Update : WSO2-CARBON-UPDATE-4.4.0 - 6497**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
