### ISSUE TITLE
PATCH request to the userstores endpoint fails/is slow to update properties.

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8231]
**Describe the issue:**
- A patch request sent to the `/userstores/{userstore-domain-id}` endpoint [1] takes some time to update the patched property.
- When an array of 
```json
{
  "operation":"REPLACE",  
  "path":"/properties/disabled", 
  "value":"true"
}
```
objects is sent, only the first object actually performs the update.

**How to reproduce:**
The below `PATCH` request was sent.
![image](https://user-images.githubusercontent.com/20745428/80795766-14109e00-8bbb-11ea-83cd-59a4c6d1b97c.png)

The response returned by the above request is as follows. As you can see, it shows an updated `driverName`.
![image](https://user-images.githubusercontent.com/20745428/80795841-47ebc380-8bbb-11ea-9f7b-cffe22a67182.png)
At the same time, the second property `url` has not been updated.
![image](https://user-images.githubusercontent.com/20745428/80796129-10c9e200-8bbc-11ea-8ed3-1f8b13b9f9e7.png)

But a `GET` request sent to retrieve the userstore details soon after the `PATCH` request returns the following:
![image](https://user-images.githubusercontent.com/20745428/80795796-2ab6f500-8bbb-11ea-9af2-0e7b7488946a.png)

The same request sent after a few seconds returns the updated data.
![image](https://user-images.githubusercontent.com/20745428/80795948-96995d80-8bbb-11ea-816c-f9ff6078b770.png)
But the `url` property has not still been updated.
![image](https://user-images.githubusercontent.com/20745428/80796187-31923780-8bbc-11ea-99a2-cc33519b737b.png)

OS: Mac Catalina
WSO2 IS version: wso2is-5.11.0-m17

[1] [Secondary Userstore Patch Request schema](https://is.docs.wso2.com/en/5.11.0/develop/userstore-rest-api/#/User%20Store/patchUserStore)

**Comment by janakamarasena** [comment]
For the delayed change happening. It should be caused because we depend on a file change. I think we need to change the API response from 200 ok to 201 accepted. Similar to the userstore create request.
