### ISSUE TITLE
[IMPROVEMENT] PIPAttributeFinder.getAttributeValues() return type is limited to "String" and can be improved "Object"

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8237]
**Is your suggestion related to an experience ? Please describe.**
Developers implementing a custom PIPAttributeFinder have to limit themselves to returning Strings. They cannot return native XACML 3.0 data types or custom data types.

**Describe the improvement**
Developers should be able to return any native data type supported by XACML 3.0 or custom data types. The custom data types can be handled by custom functions specifically written for them.

For example, a developer should be able to return a JSON object and then handle the JSON object using custom functions.

In the current implementation developers have to return a String representation of the JSON object, and then convert the String again into JSON objects to process within the custom functions. Doing this operations over many authorization operations will increase the processing time significantly.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
