### ISSUE TITLE
Support scope validators at server level

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#8245]
**Describe the issue:**

There are three places where scope validation should engage.
- at authorization (AuthorizationHandlerManager)
- at token issuance (AccessTokenIssuer)
- at introspection (TokenValidationHandler)

Right now, implementations of 'OAuth2ScopeValidator' that are picked for the application are invoked iteratively at scope validation in each point above, at a grant or response type handler layer.
Additionally, 'OAuth2ScopeValidator' implementations registered are available at the service layer for application meta.

Thus, going forward we need another level of scope validation that can be enforced at the server level.
Similar to validators engaged at app level, it should have the possibility to register multiple validators and execute the chain.

Therefore 

- [x] [Have a new interface for global level ScopeValidator](https://github.com/wso2/product-is/issues/8248)
- [x] Engage it after application-level validators at response type handler level or grant level
- [ ] Docs https://github.com/wso2/product-is/issues/10130

**Comment by mefarazath** [comment]
As part of this task, we also need to provide first class support to access token related information through the [OAuth2TokenValidationMessageContext](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/OAuth2TokenValidationMessageContext.java) used during scope validating in the token validation phase

**Comment by IsuraD** [comment]
Docs will be tracked with https://github.com/wso2/product-is/issues/10130

**Comment by malithie** [comment]
Re-opening to capture doc impact and close off
