### ISSUE TITLE
Sample Documentation for Android Sample

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8266]

**Comment by darshanasbg** [comment]
@sherenewso2 @gomathyk will help on reviewing final content.

**Comment by piraveena** [comment]
Refer
Quick-start quide docs:
https://github.com/wso2/docs-is/blob/new_restructure/en/docs/quick-starts/java-sample.md
Side-panel docs:
https://github.com/wso2/docs-is/blob/new_restructure/en/docs/quick-starts/java-sample.md
