### ISSUE TITLE
Developer Documentation for Javascript SDK

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8273]
**Problem description**
There should be a way for guide users on how to integrate Javascript SDK and use it.

**Preferred Solution**
Have a documentation README within the project repository. And optionally have a comprehensive guide within WSO2 Identity Sever public docs.

**Comment by jeradrutnam** [comment]
This is available now. 

https://is.docs.wso2.com/en/next/integrations/
https://github.com/asgardeo/asgardeo-auth-spa-sdk
