### ISSUE TITLE
React App Template

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8276]
**Problem definition**
Currently there is no entry point for developers to start creating an application. If there to build an application user will have to build everything from the scratch.

**Preferred Solution**
Create a react boiler template with minimal dependencies for developers to start building a SPA

**Tasks**
- [ ] Build a boiler template
- [ ] Publish to NPM registry

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
