### ISSUE TITLE
VS Code extension to debug IS SAML authentication flows

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8285]
Intercept entry point and exit point of the SAML requests in the IS.

**Comment by Sathiyakugan** [comment]
https://github.com/wso2-extensions/identity-tools-plugin-vscode/pull/1
https://github.com/wso2-extensions/identity-tools-debugger/pull/1

**Comment by Sathiyakugan** [comment]
The following Works will give support 
debug the SAML request, Http Request details, SAML responses. HTTP responses
Shows Visual diagram where the user could easily visualize the SAML request, SAML responses along with the flow.
