### ISSUE TITLE
VS Code extension to debug IS OIDC authentication flows

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8286]
Intercept entry point and exit point of the OIDC requests in the IS.

ie. User should be able to trace,
- Authorization request sent by the RP
- Authorization response generated by the IS (OP)
- Token requested sent by the RP
- Token response generated by the IS (OP)

**Comment by Sathiyakugan** [comment]
https://github.com/wso2-extensions/identity-tools-plugin-vscode/pull/3
https://github.com/wso2-extensions/identity-tools-debugger/pull/8

**Comment by Sathiyakugan** [comment]
The following Works will give support
debug the OIDC authorization request, OIDC authorization response, token request. token responses
Shows Visual diagram where the user could easily visualize the IDC authorization request, OIDC authorization response, token request. token responses along with the flow.
