### ISSUE TITLE
[ISSUE] Remove public client option from Windows app template. 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8289]
**Describe the issue:**
In the Windows app template, a public client checkbox is available to tick. This should not be available for Desktop applications as it isn't a SPA.

**How to reproduce:**
Visible in the Staging environment. 

**Expected behavior:**
There should be such an option. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

Cloud staging environment. 

---

**Related Issues**
https://github.com/wso2/product-is/issues/8103

**Comment by darshanasbg** [comment]
It was decided remove Windows application template.. Hence this issue is invalid.
