### ISSUE TITLE
[ISSUE] .NET Sample is not visible in the Windows App template.

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8291]
**Describe the issue:**
After creating an app using the Windows app template, Windows samples should be visible in the side panel and better to remove other samples from the side panel as they are not directly required.

**How to reproduce:**
Visible in the cloud staging environment. 

**Expected behavior:**
As mentioned in the issue. 

---

**Related issues:**
https://github.com/wso2/product-is/issues/8103

**Comment by brionmario** [comment]
We recently migrated from a hardcoded doc structure to pulling the structure directly from the `docs-is` repo. The structure and content in the docs repo is still evolving and we will have support to differentiate samples and SDKs based on the template in the future.

We'll keep track of this issue and will update once the feature is merged to product.

**Comment by darshanasbg** [comment]
It was decided remove Windows application template.. Hence closing this issue as invalid.
