### ISSUE TITLE
[ISSUE] Unable add extra tomcat connector with deployment.toml

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8306]
**Describe the issue:**
As described in the doc [1], we need to add an extra tomcat connector for x509 certificate authenticator. But this is not yet allowed from `deployment.toml` yet since it is not templated in `catalina-server.xml.j2` [2]

**Environment information**
 - Product Version: IS 5.9.0 upwards

**Related Issues**
- https://github.com/wso2/docs-is/issues/986
- https://stackoverflow.com/questions/61629890
- https://github.com/wso2/product-is/issues/8307

[1] https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator
[2] https://github.com/wso2/product-is/blob/master/modules/distribution/src/repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2

**Comment by ruwanta** [comment]
We need to find a correct way to do X509 authenticator. adding a new connector should not be required, as we should not deeply rely on Tomcat features on identity server.

**Comment by denuwanthi** [comment]
Seems like this issue still there in IS 5.11.0 wum update.

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/product-is/pull/11751 hence closing the issue
