### ISSUE TITLE
[IMPROVEMENT] "x509-certificate-servlet" in x509 certificate authenticator

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8307]
**Is your suggestion related to experience? Please describe.**
"x509-certificate-servlet" [1] in x509 certificate authenticator is just there for TLS level certificate validation, but it doesn't do the actual authentication. For that, we redirect back the user to `commonauth` where it again reads the client certificate and authenticates the user.

There is a usecase where we need to expose the general endpoints via AWS ALB which does not support passing the client cert to the backend. Because ALB is required to enable session affinity. Hence we have to use an NLB for that purpose and expose a specific endpoint via NLB for x509 certificate authentication only. 

Also, the other use case is having x509 authentication along with multiple other options. But the client cert is requested in the first request to WSO2 IS itself since clientAuth=want is in 9443 connector.  

In both of the cases, we can add a new tomcat connector as explained in the document [2]. Here, we need to avoid 9443 requesting the certificate and use clientAuth=want only for the new connector added and keep clientAuth=false for 9443 connector.

Here comes the issue, now "x509-certificate-servlet" [1] on port 8443 does nothing but certificate verifications at TLS level. Then, we direct userback to `commonauth` and it also read the client certificate again for authentication. It works with the suggested configuration in the doc because the redirection to `commonauth`  also happens in 8443 now. Because we added the 8443 new connector in top of the connector list and it is picked as the HTTPS transport port.

We can avoid this by adding the new connector after the existing one. But then, `commonauth` will not receive the client cert and authentication will fail. (Because clientAuth is set to false in 9443 connector)

**Describe the improvement**
Remove `x509-certificate-servlet`
Instead of `8443/x509-certificate-servlet`, we can redirect the user to `8443/commonauth` and do the authentication there. Then redirect back to IS hostname and port (9443) to continue the flow. 
Still, we have to remember that session cookies have to be created on IS hostname since there might be instances where we expose 8443 via a separate hostname (like ALB & NLB usecase).

[1] https://github.com/wso2-extensions/identity-outbound-auth-x509/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/x509Certificate/X509CertificateServlet.java
[2] https://docs.wso2.com/display/ISCONNECTORS/Configuring+X509Certificate+Authenticator

**Comment by ruwanta** [comment]
We do not want to redirect to different port. This will require another port to be opened in order to function, which makes complexity in deployment. We should be able to do certificate validation in a different path on the same primary port (here 9443).

**Comment by rksk** [comment]
If we are to do client cert validation over the same port, we have to find a way to deal with clientAuth tomcat property. Because we are depending on tomcat to validate the certificate and if we add clientAuth "want" or "true", it will prompt for client certificate to access any page on IS. If clientAuth is false, this validation will not happen at all. 

This is more crucial when it comes to multiple authentications options and one of them is x509. In that case, the client cert request prompt should come only if we select the x509 option.

Also, another issue is using AWS ALB with session affinity (some people use this without clustering/session persistence and also we have some other places that require sticky sessions). But ALB does not allow us to pass the client-cert and we have to use NLB for that endpoint only.

[1] https://stackoverflow.com/questions/21135264/prompt-for-any-client-certificate-only-from-a-specific-servlet

**Comment by ruwanta** [comment]
@rksk 
Yes, we need to use proper Local Authenticator to perform the "clientAuth" : "want". We can not rely on Tomcat to do this.

AWS issue is not related to product. It is a deployment choice, and some functionalities may not be available on chosen deployments. This limitation can not be considered a product issue.

**Comment by rksk** [comment]
This concern is addressed with https://github.com/wso2/product-is/issues/18437.
