### ISSUE TITLE
[ISSUE] Secondary JDBCUserstore users cannot be filtered using SCIM2 users endpoint

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#8308]
**Describe the issue:**
Secondary JDBCUserstore (not unique ID JDBCUserstore) users are not returned when trying to filter using SCIM2 users endpoint.

**How to reproduce:**
1. Configure a secondary JDBC Userstore (JDBCUserStoreManager). 
2. Add users to secondary userstore.
3. Try to list users with command - **curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users?domain=**<secondary_userstore_domain_name>'
4. The following response will be received (in this particular scenario there were 2 users in the secondary userstore)
**{"totalResults":2,"startIndex":1,"itemsPerPage":0,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"]}**

**Expected behavior:**
A list of users should be returned in the response body

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: H2
 - Userstore: LDAP/Unique ID JDBC 
 - Secondary Userstore - JDBC MySQL (not unique ID)

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
