### ISSUE TITLE
application_role_permission_required_to_view config does not work with IS-KM-5.9

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#8311]
**Describe the issue:**
The config `application_role_permission_required_to_view` allow any user to view service providers created. This works with IS-5.9.0 but does not work with IS-KM-5.9.0.

**How to reproduce:**
Set the config `application_role_permission_required_to_view` to false and check if a non-priviledge users can view applications created by others.

**Expected behavior:**
n/a

**Comment by madurangasiriwardena** [comment]
Issue is not observed in the latest build.
