### ISSUE TITLE
Rotated refresh token must not extend initial lifetime

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#8312]
**Is your suggestion related to an experience ? Please describe.**
According to the OAuth 2.0 for Browser-Based Apps (draft-ietf-oauth-browser-based-apps-06),
```
      upon issuing a rotated refresh token, MUST NOT extend the lifetime
      of the new refresh token beyond the lifetime of the initial
      refresh token if the refresh token has a preestablished expiration
      time
```
https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-06#section-8

But in the current IS behaviour the refresh token expiry time is extended when using the rotational refresh token. 
https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/c573159a6f4ea733f7ba41766f71dee30ed386c8/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java#L563

**Describe the improvement**
We can have a server-level configuration to keep the expiry time as the inital refresh token when using the rotational refresh token.

**Comment by rksk** [comment]
Doc update; https://github.com/wso2/product-is/issues/15018
