### ISSUE TITLE
[FEATURE] Account Lock Handler using function library

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#8316]
**Is your feature request related to a problem? Please describe.**
More customizable account lock logic using the functional libraries. Currently, we need to add java code Extention to customize the account lock behaviour.

**Describe the solution you would prefer**
We use our function library, and make a predefined function library "AccountLockHandler". Then with a new Java extension can we execute that function?
This way, we can give flexibility to the identity developer to develop their own Account lock logic.

**Additional context**
This is the next level use cases we planned for the functional library. But It could be great if we divide the functions library into two with this feature to avoid confusion. One set of functions for the adaptive functions and other for the server function.

Also, we need to decide on how much we are going to allow to be controlled in the function library. We can allow all the logic to the function library because of the account lock implementation based on the claim values. Or we can allow only the decision logic for the account lock to the function and maintain the claim update in the java.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
