### ISSUE TITLE
Add ability to pick the username from a cookie for identifier first/basic authenticator

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#8322]
Modify the **identifier first** and **basic authenticators** to pick the username/identifier from a cookie if its available. When a user is authenticated we could set a long-lived cookie(with the user consent) with the username or a mapped identifier and this can be used by the authenticators.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
