### ISSUE TITLE
HTTP request params get dropped in the middle of a flow after enabling product observability

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#8329]
### Description
HTTP request params get dropped in the middle of a flow after enabling product observability.
Encountered this behaviour while trying out the FIDO Device Registration Flow.

### Steps to reproduce
- Enable observability correlation logs in the product as per[1].
- Configure FIDO as per [2]
- Try the FIDO device registration flow or simply execute the following request.
`
curl -kv -d "appId=test" -H "Authorization: Basic akdjashjdhajshdasd=" "https://localhost:9443/api/users/v1/me/webauthn/start-registration"
`

### Observed IS Version
5.7

[1] https://docs.wso2.com/display/IS570/Working+with+Product+Observability
[2] https://docs.wso2.com/display/IS530/Multi-factor+Authentication+using+FIDO

**Comment by tharindu-bandara** [comment]
Related issue: https://github.com/wso2/product-is/issues/6392
