### ISSUE TITLE
Need to add migration for tenants

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#8332]
**Describe the issue:**
We need to add the following queries in the migration to support tenant management APIs with UUID. A new column has been introduced in UM_TENANT table.

> ALTER TABLE UM_TENANT ADD UM_TENANT_UUID VARCHAR(36) NOT NULL 
ALTER TABLE UM_TENANT ADD UNIQUE (UM_TENANT_UUID)
UPDATE UM_TENANT SET UM_TENANT_UUID = UUID();

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DMHP** [comment]
https://github.com/wso2-extensions/identity-migration-resources/pull/161/files
