### ISSUE TITLE
Sending OTP as the password while user creation

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#8340]
**Is your feature request related to a problem? Please describe.**
The use case is as below.

For first log in, the user should be able to login using the One Time Password. But we should only send one  POST user creation request. With adminforcepassword reset  always we should do two request POST and PATCH

**Describe the solution you would prefer**
We should have a way to send the OTP during the preAddUser operation

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
