### ISSUE TITLE
Can't turn of connectors in catalina-server.xml and remove transport receivers in axis2.xml

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#8364]
**Describe the issue:**
Can't turn of connectors in catalina-server.xml and remove transport receivers in axis2.xml

**Comment by hasinthaindrajee** [comment]
Part of this has been done with https://github.com/wso2/product-is/pull/8362

**Comment by hasinthaindrajee** [comment]
We need to turn of http transport listners from catalina.xml . For an example we need to remove the below config from catalina-server.xml

<Connector protocol="org.apache.coyote.http11.Http11NioProtocol"
                  maxHttpHeaderSize="8192"
                  acceptorThreadCount="2"
                  compressionMinSize="2048"
                  compressibleMimeType="text/html,text/javascript,application/x-javascript,application/javascript,application/xml,text/css,application/xslt+xml,text/xsl,image/gif,image/jpg,image/jpeg"
                  minSpareThreads="50"
                  compression="on"
                  connectionUploadTimeout="120000"
                  URIEncoding="UTF-8"
                  maxKeepAliveRequests="200"
                  disableUploadTimeout="false"
                  redirectPort="9443"
                  server="WSO2 Carbon Server"
                  port="9763"
                  noCompressionUserAgents="gozilla, traviata"
                  acceptCount="200"
                  bindOnInit="false"
                  maxThreads="250"
       >
       </Connector>

**Comment by piraveena** [comment]
By adding below config in the deployment.toml file, we can disable the tomcat connectors. Similarly, we can turn off https connector too.

```
[transport.http]
enabled=false
```

But axis config needs to be templated. That is still not fixed
