### ISSUE TITLE
Thrift authentication service can't be turned off.

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#8365]
**Describe the issue:**
 
We can't turn off ThriftAuthenticationService (port 10711)  in product. This is not required to be open in a case if we don't need it. Hence as a security best practice we should provide a way to turn this off.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
