### ISSUE TITLE
Bug in "TenantContextsToRewrite" config templating

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#8369]
The current `TenantContextsToRewrite` config is templated in the identity.xml.j2 like below;

```
    <TenantContextsToRewrite>
        <WebApp>
            {% for webapp in tenant_context.rewrite.webapps %}
            <Context>{{webapp}}</Context>
            {% endfor %}
        </WebApp>
        <Servlet>
            {% for servlet in tenant_context.rewrite.servlets %}
            <Context>{{servlet}}</Context>
            {% endfor %}
        </Servlet>
        <OverwriteDispatch>
            {% for context in tenant_context.rewrite.overwrite.dispatch %}
            <Context>{{context}}</Context>
            {% endfor %}
        </OverwriteDispatch>
    </TenantContextsToRewrite>
```

And the values are added to the identity.xml through default.json file.

The issue here is if even one `TenantContextsToRewrite` config is given from the deployment.toml file the default values will not be added. We will miss mandatory configurations due to this.

### How to reproduce

Start the IS once and make note of the configs in the `TenantContextsToRewrite` tag in identity.xml.
Then add the following config to the deployment.toml file and restart the server and recheck the config in the identity.xml
```
[tenant_context.rewrite]
webapps=["/api/identity/user/v1.0/"]
```

### Possible fix
Add the mandatory configs for `TenantContextsToRewrite` directly to the identity.xml.j2 file.

**Comment by Sathiyakugan** [comment]
@janakamarasena 
Being make it easy to add external non feature  war files added to the product is not good. This will make easy path to  add new app to the Product IS.  From the client,  if they add unwanted war file  it will cause some memory and performance issues. As long as limiting the addition of  external war, It  will be good for the product.
