### ISSUE TITLE
Application filter operation with operator 'eq' using Application Management Server REST API gives status code 505

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#8375]
**Suggested Labels**
Affected/IS 5.11.0 Milestone 18

**Environment**
IS 5.11.0 Milestone 18
Dev Cloud

**Steps to Reproduce**
1. Create a Tenant as iam.com
2. Try to filter the Applications using the Application management server API using filter operator eq.

**Observation**
Request

`curl -X GET --user test@iam.com:test"https://localhost:9443/t/iam.com/api/server/v1/applications?filter=name+eq+User Portal" -H "accept: application/json" -i -k 
`
Response
```
HTTP/1.1 505 
Content-Length: 0
Date: Wed, 20 May 2020 07:31:43 GMT
Server: WSO2 Carbon Server
```

Request

curl -X GET --user test@iam.com:test"https://localhost:9443/t/iam.com/api/server/v1/applications?filter=name+eq+UserPortal" -H "accept: application/json" -i -k

Response 

```
HTTP/1.1 200 
Date: Wed, 20 May 2020 07:31:52 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Server: WSO2 Carbon Server

{"totalResults":0,"startIndex":1,"count":0,"applications":[],"links":[]}


```
correct scim name is User Portal as in 1st request but it gives 505 for that request and gives 200 for wrong name UserPortal. Even with the 200 it does not list any results in the response.

**Comment by mefarazath** [comment]
I think the second behaviour is correct (ie. not returning the results since the name did not match any)

The first request there seems to be a bug in the filter parsing logic.

**Comment by mefarazath** [comment]
Also when I tried the search using the User Portal. Search the full string "User Portal"
![image](https://user-images.githubusercontent.com/5237653/82424895-6d296e80-9aa3-11ea-823c-cd9bcbef02f2.png)

Started seeing errors like,
![image](https://user-images.githubusercontent.com/5237653/82424996-8e8a5a80-9aa3-11ea-8d03-2e1c6c2313a8.png)

with

```{"code":"APP-60004","message":"Invalid format user for filtering.","description":"Filter needs to be in the format <attribute>+<operation>+<value>. Eg: name+eq+john","traceId":"77bd7715-a1ae-4218-9766-5be1d103e8fd"}```

Looks like we need to fix the filter parsing login in the applications API to handle " " in the query string.

**Comment by mefarazath** [comment]
So two things to fix,

1. Application API to handle filters with spaces in the query value.
2. Fix Developer portal to display the correct message ("Application Create Error" is not the correct message for errors happen during listing..)
