### ISSUE TITLE
Support for JWT SSO in inbound authentication protocols.

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8379]
Some of the applications use JWT as the SSO protocol instead of OIDC or SAML such as Thinkific LMS [1].
Hence, implementing JWT SSO as an inbound authentication protocol in WSO2 IS will let us configure the applications which require JWT as the source of authentication.

[1] https://support.thinkific.com/hc/en-us/articles/360030718713-SSO-Automatically-Sign-in-From-Your-Own-Website

**Comment by mifrazmurthaja** [comment]
The implementation architecture can be found at the [blog](https://medium.com/@mifrazmurthaja/jwt-sso-with-wso2-identity-server-cf486ffba1bf).

**Comment by mefarazath** [comment]
@mifrazmurthaja what are the pending items to close off this issue?

**Comment by mifrazmurthaja** [comment]
@mefarazath This can be closed.
