### ISSUE TITLE
OTP based forced password reset fails when OAuth redirect_url is a custom URL sheme

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8388]
**Describe the issue:**
When using code grant flow for native mobile apps, it is common to use custom URL schemes for OAuth redirect_url so the mobile app will automatically be opened when IS responds with the auth code.

When we are doing OTP based offline admin forced password reset, it uses the OAuth redirect_url as the callback due to the fix [1]. But we are trying to decode that URI as a URL at [2] and fails with a `MalformedURLException`.

The fix done in [1] to use the OAuth redirect_url as the callback is also questionable. After password reset, the user should end up in login page and should not be redirected back to OAuth redirect_url without an authz code.

**How to reproduce:**
* Configure an OAuth SP with redirect URL as `com.wso2.test://login`
* Enable offline admin forced password mode [1]
* Use above SP with the forced password reset flow
* You will get the following error on browser
```
Invalid callback URL found in the request.
```

**Environment information**
 - Product Version: IS 5.9.0

[1] https://github.com/wso2/carbon-identity-framework/pull/2030/files
[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/IdentityManagementEndpointUtil.java#L455
[3] https://is.docs.wso2.com/en/5.9.0/learn/forced-password-reset/

**Comment by dewniMW** [comment]
created a separate git issue [1] to track the following suggestion mentioned in the git issue description.

> The fix done in [1] to use the OAuth redirect_url as the callback is also questionable. After password reset, the user should end up in login page and should not be redirected back to OAuth redirect_url without an authz code.

**Comment by dewniMW** [comment]
The git issue is removed from Identity Server 5.12.0 project board as the issue is not there in the latest pack (the method called in IS 5.9.0 WUM pack is different from the one used in the lastest pack).
