### ISSUE TITLE
Support for existing FIDO devices before IS 5.9.0 through FIDO2

### ISSUE THREAD

**Issue by mostafahussein** [wso2/product-is#8390]
**Describe the issue:**
We use IS 5.8.0 where users can list the FIDO Devices that they have added in the past and login with these devices. After migrating to IS 5.9.0 users cannot list the FIDO Devices anymore thus they cannot use the devices in the login process so devices must be re-enrolled.

Any device that was added before IS 5.9.0 won't be listed in the dashboard through **WSO2 DASHBOARD** > **MY PROFILE** > **Manage FIDO Devices** and that's because IS 5.9.0 will look for the devices which have been added using FIDO2 unless you disabled WebAuthn globally which prevents you from adding more devices in the future using FIDO2 which is the newer and has support with new versions of the modern browsers e.g. chrome and firefox.

I would like to be able to log in with old fido devices while having the ability to add new devices based on fido2.

**Notes:**
- WebAuthn provides drawback compatibility for FIDO U2F as per this explanation: [Migrating From U2F](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Migrating_from_U2F.html)
- The specifications under FIDO2 support existing passwordless FIDO UAF and FIDO U2F use cases and expand the availability of FIDO Authentication. Users that already have external FIDO-compliant devices, such as FIDO security keys, will be able to continue to use these devices with web applications that support WebAuthn. Existing FIDO UAF devices can still be used with pre-existing services as well as new service offerings based on the FIDO UAF protocols. — [FIDO2: WebAuthn & CTAP](https://fidoalliance.org/fido2/)

**How to reproduce:**
Add FIDO token using IS 5.8.0 and then migrate to 5.9.0 expected to be sufficient.

**Expected behavior:**

Users can use their current tokens or add new tokens

**Environment information:**
 - Product Version: IS 5.9.0
 - OS: Linux
 - Database: MySQL
 - Userstore: JDBC

**Suggested labels:**
Priority/Highest
Severity/Critical

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
