### ISSUE TITLE
5.10.0 Consent table missing error is not logged

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#8391]
5.10.0 June 20 WUM
Start a pack without executing the consent DB script.
Setup an SSO app and try to login.
No errors in the logs.
No way to know what the error is.

Please improve login in the **ConsentMgtPostAuthnHandler.handlePreConsent()** method to print the log.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
