### ISSUE TITLE
SP to inform the IDP on the subject to be authenticated.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8399]
**Is your feature request related to a problem? Please describe.**
If the application is aware of the user it wants to get authenticated via the IDP, it is useful to give this information to the IDP along with the authentication request. So that the IDP will authenticate the particular subject and provide the response. 
If user experience wise also this provides a smooth experience if user has already given the subject information at the SP.

**Describe the solution you would prefer**
Honoring the below attribute from SAML spec[1](optional param)

3.4.1 Element <AuthnRequest>
<saml:Subject> [Optional]
Specifies the requested subject of the resulting assertion(s). This may include one or more
<saml:SubjectConfirmation> elements to indicate how and/or by whom the resulting assertions
can be confirmed. For more information on this element, see Section 2.4.

[1] - https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf

**Additional Context**
**While we been able to send this parameter in the authentication request, it will also be important that WSO2 IS as an IDP is ready to honor this parameter as well.**

**Comment by mefarazath** [comment]
This will be some sort of a login_hint i guess. Are we only focusing on SAML in this issue?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
