### ISSUE TITLE
Secondry userstores in tenants are being tried to deploy twice

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8400]
**How to reproduce:**
* Create a tenant and create a secondary userstore on the tenant
* Restart IS to unload the tenant
* Log in to tenant's management console
* Following WARN is logged though there is no effect on the functionalities
```
WARN {org.wso2.carbon.user.core.common.UserStoreDeploymentManager} -  Could not initialize new user store manager : INT.BP Duplicate domain names not allowed.
```

**Environment information**
 - Product Version: IS 5.8.0

**Related issues:**
https://github.com/wso2/product-is/issues/4683
https://github.com/wso2/product-is/issues/6542

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
