### ISSUE TITLE
Update tomcat max thread count  fails 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#8410]
**Describe the issue:**

Default tomcat thread count is 250.  Update the thread count did not apply to the server.

**How to reproduce:**

Step 01. Update the thread count with toml configurations as below 

[transport.https.properties]
maxThreads = "10"

Step 02. and check the <IS_Home>/repository/conf/tomcat/catalina-server.xml, maxThreads count .

Step 03. Get NMT record to check the number of thread 

- To get the NMT report with Oracl java 11
- Add following on wso2server.sh file under  'JVM_MEM_OPTS'
                -XX:NativeMemoryTracking=summary
- Once the server start get the carbon pid and execute the commad 
- jcmd (pid) VM.native_memory summary

**Expected behavior:** 

Thread count should be update with the new configuration. 

**Actual behavior:** 
Thread count did not update according to the new configurations .Compare with the NMT report.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0 and 5.10.11
 - OS: Linux
 - Database: Postgres
 - Userstore:  JDBC

Sample NMT report

Total: reserved=2101866KB, committed=729334KB
--
-                 Java Heap (reserved=262144KB, committed=262144KB)
(mmap: reserved=262144KB, committed=262144KB)
 
-                     Class (reserved=1252687KB, committed=230899KB)
(classes #34684)
(  instance classes #32809, array classes #1875)
(malloc=5455KB #121553)
(mmap: reserved=1247232KB, committed=225444KB)
(  Metadata:   )
(    reserved=198656KB, committed=197796KB)
(    used=183633KB)
(    free=14163KB)
(    waste=0KB =0.00%)
(  Class space:)
(    reserved=1048576KB, committed=27648KB)
(    used=23084KB)
(    free=4564KB)
(    waste=0KB =0.00%)
 
-                    Thread (reserved=214792KB, committed=23948KB)
(thread #208)
(stack: reserved=213772KB, committed=22928KB)
(malloc=748KB #1060)
(arena=272KB #416)
 
-                      Code (reserved=255102KB, committed=95202KB)
(malloc=7414KB #24740)
(mmap: reserved=247688KB, committed=87788KB)
 
-                        GC (reserved=57809KB, committed=57809KB)
(malloc=15277KB #56689)
(mmap: reserved=42532KB, committed=42532KB)
 
-                  Compiler (reserved=1237KB, committed=1237KB)
(malloc=1133KB #1972)
(arena=104KB #5)
 
-                  Internal (reserved=5799KB, committed=5799KB)
(malloc=5759KB #5937)
(mmap: reserved=40KB, committed=40KB)
 
-                     Other (reserved=1267KB, committed=1267KB)
(malloc=1267KB #87)
 
-                    Symbol (reserved=34095KB, committed=34095KB)
(malloc=31146KB #473236)
(arena=2949KB #1)
 
-    Native Memory Tracking (reserved=11547KB, committed=11547KB)
(malloc=577KB #8140)
(tracking overhead=10970KB)
 
-               Arena Chunk (reserved=4286KB, committed=4286KB)
(malloc=4286KB)
 
-                   Logging (reserved=4KB, committed=4KB)
(malloc=4KB #189)
 
-                 Arguments (reserved=25KB, committed=25KB)
(malloc=25KB #572)
 
-                    Module (reserved=1073KB, committed=1073KB)
(malloc=1073KB #7261)

**Comment by ruwanta** [comment]
Running this low is not critical or is a bug. The recommended  resource limit is 1GB heap.

Low memory like this is not supported with current architecture.
