### ISSUE TITLE
Have claim attribute mapping for a subset of userstores only

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8411]
**Is your suggestion related to an experience ? Please describe.**
Let's say I have a secondary userstore and a user attribute that exists on the secondary userstore only. I add a local claim and add a mapped attribute for the secondary userstore. But I don't have an attribute to map for this claim in the primary userstore.

Now if we invoke the `getUserClaimValues()` method of the userstore manager for a user on the primary userstore, it tries to search for mapped attributes for all the local claims and fails at the above claim I added.

```
Cannot find suitable mapped attribute for local claim http://wso2.org/claims/test
```

One example of breaking the scenario is email notifications. That component calls the user store and requests all the claims of the user to fill the place holders of the email template. Hence those flows break entirely if we do not have a mapped attribute for the primary userstore.

**Describe the improvement**
Either we have to handle this error gracefully and avoid failures. We might be able to avoid returning a key for this attribute missing claim from the `getUserClaimValues()` method. But have to consider all the scenarios.

OR we will have to mandate adding a mapped attribute for the primary userstore if we are unable to handle gracefully.

**Comment by rksk** [comment]
Related: https://github.com/wso2/product-is/issues/7002

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
