### ISSUE TITLE
Possible NPE Error when BackupCode is not enabled in EMailOTP

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#8412]
There is a possible NPE here https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L435 

 if otp token is expired or user entered a invalid token, Backup flow will be executed. If the `BackupCode` is not added as a config, then it may throw a NPE

**Comment by DinikaSen** [comment]
This has been fixed with the PR wso2-extensions/identity-outbound-auth-email-otp#79
