### ISSUE TITLE
Missing Key-mapping for default.notification.sender

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#8413]
Need to add key-mapping for the following properties in default.json file

```
"identity_mgt.events.schemes.\u0027default.notification.sender\u0027.subscriptions": [
    "TRIGGER_SMS_NOTIFICATION",
  ],
  
  "identity_mgt.events.schemes.\u0027default.notification.sender\u0027.properties.\u0027subscription.TRIGGER_SMS_NOTIFICATION.stream\u0027": "id_gov_sms_notify_stream:1.0.0",
  "identity_mgt.events.schemes.\u0027default.notification.sender\u0027.properties.\u0027subscription.TRIGGER_SMS_NOTIFICATION.claim.mobile\u0027": "http://wso2.org/claims/mobile",

```

**Comment by piraveena** [comment]
If we want to add the configs to toml file for the above, then we have to add as below:


[identity_mgt.events.schemes.'default.notification.sender'.properties]
'subscription.TRIGGER_SMS_NOTIFICATION.stream' = "testDelete"

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
