### ISSUE TITLE
XML declaration in SAML Authentication Requests

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#8414]
**Describe the issue:**
I am using WSO2IS v.5.9.0 and it is configured with ADFS as federated IDP. When creating the authentication request to ADFS, WSO2IS adds the XML declaration in the request (<?xml version="1.0" encoding="UTF-8"?>). This can cause an error on ADFS discovery service, how can the XML declaration can be removed?
 
**How to reproduce:**
Configure WSO2IS v.5.9.0 with a SAML federated IdP and trace the authentication request from WSO2IS.

**Expected behavior:**
A clean authentication request without the XML declaration.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.9.0
 - OS: CentOS
 - Database: PostgreSQL
 - Userstore: LDAP

**Comment by ruwanta** [comment]
Hi @hefesita 
Would you mind providing reference that XML declaration cause issue (as you mentioned) in ADFS discovery.

Ideally any service consumes XML s supposed to able to handle XML declaration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
