### ISSUE TITLE
Sending Email for TOTP is not working

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#8419]
Version: 5.10.0
When we try send email with TOTP as mentioned here https://is.docs.wso2.com/en/latest/learn/configuring-totp/ is not working

**Comment by piraveena** [comment]
**Workaround**: 
If we want to send an email for totp, Need to make two changes. 

- Need to remove ‘&’ character infront of sessiondataKey in https://github.com/wso2/identity-apps/blob/master/apps/totp-authentication-portal/src/main/webapp/js/scripts.js#L50

- Need to change the TOTP template in management-console
     Change **{{user.claim.givenname}}** to **{{user-name}}**

**Comment by kiwinesian** [comment]
hi @piraveena 

I think step 2 only is sufficient on WSO2 5.10.0

Thank you for the tips!

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
