### ISSUE TITLE
If invalid tenant domain is qualified in the URL, 200 OK is returned (/t/foo.com/oauth2/token)

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#8422]
Send a request to the token endpoint with invalid tenant name  (say foo.com)  /t/foo.com/oauth2/token. 
Error is generated in logs & 200 OK is returned.  

It must be 400 or 500.

This must be verified & fixed with https://github.com/wso2/product-is/issues/7902 once feature is done.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
