### ISSUE TITLE
Invalid behavior for SCIM Enterprise schema filters with Identity claims

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8427]
**Describe the issue:**
If we use multiple SCIM filters with Enterprise schema it does not gives the expected result.
Ex:
`https://localhost:9443/scim2/Users?filter=EnterpriseUser.accLock+eq+true+and+emails+eq+user2@mail.com`
**How to reproduce:**
1. Create an Enterprise schema for SCIM
2. Point it to an identity claim
3. Use SCIM filter as above (multiple filters along with the Enterprise schema)
4. It'll always return an empty response.

**Expected behavior:**
It should return the response for the acc lock claim is set to true and the email is user2@mail.com.

**Environment information**
 - Product Version: IS 5.7.0
 - Database: MySQL
 - Userstore: JDBC

**Comment by DinikaSen** [comment]
This needs to be fixed in 5.10.0 as well. The filter request above should be changed as `https://localhost:9443/scim2/Users?filter=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.accLock+eq+true+and+emails+eq+user2@mail.com` when used with 5.10.0.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
