### ISSUE TITLE
Mandatory claims does not works as expected with OIDC apps

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#8438]
**Describe the issue:**
$subject happens when having mandatory claims which are not mapped with OIDC dialect.

**How to reproduce:**
1. Setup OIDC SP
2. Set mobile number claim  as mandatory
3. Login to SP first time prompt to enter mobile number claim (which is ok).
Profile also 
4. Re-login to SP, still its prompt to enter mobile number

**Expected behavior:**
Shouldn't prompt for claim update for the 4.

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by janakamarasena** [comment]
Were you using a custom claim dialect? and was the claims also marked as requested claims?

**Comment by darshanasbg** [comment]
@janakamarasena 
No, using default claims. So option to select requested claim is not shown. 

Following just the steps mentioned above should reproduce the issue.

Have you followed that and got different result?

**Comment by IsuraD** [comment]
This is happening due to http://wso2.org/claims/mobile claims is not mapped to any of the OIDC claim in the OIDC dialect. However, it is wrong to re popup and asking the claim value again while authentication. Fixed it with wso2/carbon-identity-framework#3094.
