### ISSUE TITLE
Adding service provider context information on force challenge question page

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#8440]
**Is your suggestion related to experience? Please describe.**
Current force challenge question page(add-security-questions.jsp) not having any service provider context information. Ideally, it should have the service provider information(sp query parameter) which helps to load theming on those pages if we have customized authenticationendpoint based on the service provider.

**Describe the improvement** 
The service provider information(sp query parameter) which includes in the login request.  can retrieve from login request & embed the service provider context information ("sp" param in URL) to the login request from the "identity-governance" component level. Then it can be redirected to the "add-security-questions.jsp" page.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2-extensions/identity-governance/pull/392
