### ISSUE TITLE
[Migration]Behaviour change in sending additional params in error url

### ISSUE THREAD

**Issue by Ashi1993** [wso2/product-is#8446]
**Describe the issue:**
 Added a configuration to remove the additional parameters sp and tenant domain from error URL.
`<AllowAdditionalParamsFromErrorUrl></AllowAdditionalParamsFromErrorUrl>`

Config in deployment tmol file
[oauth.allow_additional_params_from_error_url]
enable = true

From this config by default appending additional parameters to the Error URL will be set to false. If any one need to enable additional parameters they have to set this config to true. Parameters that will be appending if the config is true are sp and tenant_domain. 

For migration this config needs to enabled by setting the value to true.

For IS 5.7.0 default value for config is true
For master default value for config is false

Related issue  wso2/product-is#8326

**Comment by janakamarasena** [comment]
Config PR: https://github.com/wso2/carbon-identity-framework/pull/2940
