### ISSUE TITLE
Rest API to Revoke OAuth 2.0 Access Token by Administrator

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8451]
**Describe the improvement**
WSO2 IS doesn't have a Rest API exposed to revoke an OAuth 2.0 access token by an administrator.

**Additional context**
In general all the end-user related operations, where end-users are acting on their data, should have a corresponding Rest API for administrators to do the same on behalf of users.
E.g. session termination (having), account linking (don't have), enrolling 2nd factor devices (don't have), etc.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by johannnallathamby** [comment]
Account linking is going to be provided with https://github.com/wso2-enterprise/iam-product-management/issues/328
