### ISSUE TITLE
Provide Login option in after-logout page.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8454]
**Describe the improvement**
Providing a link to attempt re-login on the same page after logout.

![dew](https://user-images.githubusercontent.com/791850/83686373-ba5f2180-a607-11ea-8a30-4510bb20016a.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
