### ISSUE TITLE
Extend configuration templating to management console

### ISSUE THREAD

**Issue by gdiamond** [wso2/product-is#8457]
**Situation**

Before I was able to track down the documentation for changing the session timeout for the Management Console I found a reference to `tomcat.management_console.session_timeout` in `<IS_HOME>/repository/resources/conf/default.json`.  I tried setting a new value by adding the property to `<IS_HOME>/repository/conf/deployment.toml` and letting the templating handle updating the appropriate XML file.  It turns out the property is not used in any of the configuration templates.

**Improvement**

Add management of `<IS_HOME>/repository/conf/tomcat/carbon/WEB-INF/web.xml` to `<IS_HOME>/repository/conf/deployment.toml` and its templating process.

**Additional context**

* The manual process for configuring the session timeout for the Management Console can be found in [Running the Product](https://is.docs.wso2.com/en/5.10.0/setup/running-the-product/#accessing-the-management-console).  
* The documentation should be updated to reflect that relevant configuration can be done in `deployment.toml`.  
* IMHO, this change should be backported to when configuration via `deployment.toml` was introduced.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
