### ISSUE TITLE
Need to support answering multiple questions from single question set for account recovery 

### ISSUE THREAD

**Issue by ruwanta** [wso2/product-is#8458]
**Is your suggestion related to an experience ? Please describe.**
Current user recovery functions by having to select one question from a question set and answer it by user. Admin can define multiple question sets.
We need to improve this logic to have single question set, and allow answering unique questions from this set by the user.
This allows admin to configure set of questions, and user select any minimal number of questions among it to be filled to get account recovery.

**Describe the improvement**
Currently the answers are saved as an independent claim value having the question and answer.  This works well in proposed improvement as well.
However we need a tenant wise flag to virtually duplicate a single question set to multiple sets and display accordingly on the UIs.
The recovery logic will function without modification.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
