### ISSUE TITLE
Error in property name 'inactive_account_suspention' in key-mappings.json

### ISSUE THREAD

**Issue by dzaslavskiy** [wso2/product-is#8459]
**Describe the issue:**
key-mappings.json contains the line:
  "identity_mgt.inactive_account_suspention.enable_account_suspension": "identity_mgt.events.schemes.\u0027suspension.notification\u0027.properties.enable",

It seems the word suspention is a misspelling of suspension

**How to reproduce:**
This error become evident when trying to set these values in deployment.toml because the settings are not picked up if they are misspelled.

**Expected behavior:**
No typos

**Environment information** 
 - Product Version: IS 5.10.0
 - OS: Linux

**Comment by dzaslavskiy** [comment]
Any plan to address this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
