### ISSUE TITLE
Allow branding of SP login page as a part of SP configuration, dynamically.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8460]
**Is your feature request related to a problem? Please describe.**
We can onboard SPs dynamically. So they also can have a requirement to have a branded login page. At the moment this involves a deployment task that does not align well with the user story.

**Describe the solution you would prefer**
Allow theming and branding in the UI itself similar to how we dynamically create the SPs. This can be writing a simple UI and letting the users upload relevant css files, icons, images and make a sub-theme for SP based on that.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
