### ISSUE TITLE
Move sample identity event handler to samples-is repo 

### ISSUE THREAD

**Issue by sherenem** [wso2/product-is#8462]
More [1] to samples-is repo or any other official wso2 repo so that we can link to it from the docs.

[1] https://github.com/IsuraD/sample-extensions/tree/master/custom-identity-event-handler

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
