### ISSUE TITLE
Scope API is not consistent when registering OIDC scopes as OAuth 

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8465]
**Describe the issue:**
With https://github.com/wso2/product-is/issues/7130, we have merged the two tables IDN_OAUTH2_SCOPE and IDN_OIDC_SCOPE into one table and made the scope name unique across the tenant. Hence now it is not possible to create OAuth scopes with existing OIDC scope names.

But the REST APIs [1,2] seem to be not consistent with this expected behavior. If we try to create a scope with an existing OIDC scope name, it says the scope already exists. But if we try to fetch the scope, the scope does not exist.

**Environment information**
 - Product Version: IS 5.10.0

[1] https://is.docs.wso2.com/en/latest/develop/oauth2-scope-management-rest-apis/
[2] https://docs.wso2.com/display/IS580/apidocs/OAuth2-scope-endpoint/index.html

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
