### ISSUE TITLE
Support for account de-registration via self care portal

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#8466]
Account de-registration operation can have several options, but not limited to below.

- Users delete the account without any intervention from an administrator of the system.
- Users delete the account after an approval process.

When supporting this, we need to modify the permission for delete operation. Currently, the permission is 

```
<Permissions>/permission/admin/manage/identity/usermgt/delete</Permissions>
<Scopes>internal_user_mgt_delete</Scopes>
```
The user need to have these permission and scope. Else we can modify it via the config
sub Tasks:

- [ ] [UI feature for delete me feature](https://github.com/wso2/product-is/issues/9769)

**Comment by thivi** [comment]
The relevant UX feature is tracked here. https://github.com/wso2/product-is/issues/9769
