### ISSUE TITLE
Remove all the references to blacklist/whitelist from the docs and the code

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#8470]
Inspired by the tweet (https://twitter.com/leahculver/status/1269109776983547904) by Leah Culver (@leahculver), we need to start cleaning all our docs and code.

Let's rename all the references to whitelist to **allowlist** and blacklist to **denylist**.

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/1789
