### ISSUE TITLE
Handle Account Locking From Identity Framework Level

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#8472]
**Is your feature request related to a problem? Please describe.**

User account locking is implemented at the authenticator level. Each authenticator will consume account locking service, handle storing login fail count, and engage account locking. Because of this, for each authenticator implemented with the Identity Server, the developer needs to handle the account locking scenario as well, which is in fact a general requirement.

**Describe the solution you would prefer**

Move account locking to the Identity Framework level. The developer of an authenticator should be able to enable account locking, as preferred. Then the framework will identify any authenticator which requires account locking and engage the locking service appropriately.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
