### ISSUE TITLE
Enabling CORS for OAuth2 webapp

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8473]
**Is your suggestion related to an experience ? Please describe.**
If someone is using WSO2 IS docker images wants to enable CORS for oauth2 endpoints, the webapp gets extracted after starting the container and we are not able to update the web.xml before that. Therefore, he/she has to go through a long process to add an extracted webapp to the docker image (custom-built one) with updated web.xml.

**Describe the improvement**
We have two options to improve the developer experience.
1. Ship all the webapps as exploded directories, so we can easily update the web.xml file
2. Enable CORS by default for oauth2 like webapps

**Comment by rksk** [comment]
Might be a duplicate of https://github.com/wso2/product-is/issues/5957

**Comment by cpesch** [comment]
I disagree. Please double check this again. It's a major hinderance when working with Docker images in all deployments that are not naive.

**Comment by cpesch** [comment]
This might be the solution: https://github.com/wso2/product-is/issues/8337

**Comment by rksk** [comment]
@cpesch yes it is https://github.com/wso2/product-is/issues/8337, previously I have added a wrong link.
