### ISSUE TITLE
Add analytics support to track the logins for client credentials grant type

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8482]
**Is your feature request related to a problem? Please describe.**
We did not support to track the logins for the non-browser-based grant types. We have provided analytics event publishing for password grant in https://github.com/wso2/product-is/issues/5065. But still, the client credentials grant type is not supported.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
