### ISSUE TITLE
Remove stale code related to PKCE feature

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#8484]
**Is your suggestion related to an experience ? Please describe.**
We have some stale code related to PKCE that checks whether the DB column is available to decide whether PKCE can be supported.

This is was added in 5.2.0, when the feature was introduced. Now since all the latest versions have this column the code and its usages seemed to be stale and could be cleaned up...

Refer https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/22c02ed21461a1deee2dfa9b872b02b5285c16ce/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuth2ServiceComponent.java#L290

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
