### ISSUE TITLE
Incorrect user roles from external LDAP Userstore

### ISSUE THREAD

**Issue by Pooky** [wso2/product-is#8486]
Hi guys,

we are currently using WSO2 Identity Sever 5.7.0 to manage our user base and it has worked fine but currently there has been some problems with fetching user roles from LDAP userstore.

See screenshots below - there is user SJS0028. This user if fetched from LDAP userstore and WSO2 Admin says he should have two roles - VEBR_MAND and VEBR_USER.

![WSO2_Bug1](https://user-images.githubusercontent.com/316359/84382390-d3a93480-abea-11ea-977c-c3670f48c7b1.PNG)

If you click on this role "VEBR_MAND" and search for this user - there are no results:

![image](https://user-images.githubusercontent.com/316359/84382524-0ce1a480-abeb-11ea-8062-26e1eba3a475.png)

This role is incorrectly displayed and assigned to this user. There is also another role "VEBR_PROJ", which this user should have assigned but it is not shown in his profile:

![WSO2_MissinRole](https://user-images.githubusercontent.com/316359/84382630-37336200-abeb-11ea-86a4-204eadee1a7d.PNG)

I am suspecting it's some kind of cache which probably cause this issue - after user is manually updated in carbon admin, the role is showed correctly also whole restart of server works. How can I prevent this in future? Is there someway, how to make LDAP user-store to fetch correct roles and show them for users?

Thanks very much for help or guidance!

**Comment by Pooky** [comment]
I dig into this and there seems to be option "Cache users roles" in LDAP userstore settings -> under advanced tab. I have removed this option and roles are now not cached at all, also this situation could be due to performance issue on the server and after server restart, it seems to help.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
