### ISSUE TITLE
Userinfo end point only return sub claim

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#8488]
**Describe the issue:**
When the user info endpoint calls with the password grant from a secondary user store user it returned only subject claim

**How to reproduce:**
1. Get the latest WUM updated IS-KM 5.7.0
2. Configure an LDAP secondary user store
3. With the secondary users, user info endpoint calls with the password grant from a secondary user store user it returned only subject claim when the opened scope is used.

**Expected behavior:**
All requested claims should return

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.7.0
 - OS: Linux
 - Database: H2
 - Userstore: Sec LDAP

**Comment by LahiruLS** [comment]
It seems to be introduced to this.
https://github.com/wso2-support/identity-inbound-auth-oauth/pull/653/files

**Comment by pamodaaw** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1396
