### ISSUE TITLE
Management console does not allow the search users to contain the "&" in their user name.

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#8489]
**Describe the issue:**
Management console does not allow the search users to contain the "&" in their user name.

The same issue for the apostrophe is mentioned here[1]
[1] - https://github.com/wso2/product-is/issues/7174

**Comment by ShanChathusanda93** [comment]
Linking a related issue : https://github.com/wso2/product-is/issues/8490

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
