### ISSUE TITLE
When the username contains the "&" character the dashboard application breaks to load widgets.

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#8490]
**Describe the issue:**
Create a user with the user name which contains "&" and then try to load the user profile from the dashboard.

**Comment by ShanChathusanda93** [comment]
Linking a related issue : https://github.com/wso2/product-is/issues/8489

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
