### ISSUE TITLE
Add new identity claims

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#8492]
**Describe the issue:**

For the users who migrating to IS-5.11 should get added the following new identity via the migration client because  IS-5.11 onwards following identity claims need to be available by default in the product.

```
http://wso2.org/claims/identity/failedSmsOtpAttempts
http://wso2.org/claims/identity/failedEmailOtpAttempts
http://wso2.org/claims/identity/failedTotpAttempts
```
**Related PRs for Changes:**
https://github.com/wso2/carbon-identity-framework/pull/2965
https://github.com/wso2/carbon-identity-framework/pull/2969

**Comment by malithie** [comment]
@AnuradhaSK can we close this issue ?

**Comment by AnuradhaSK** [comment]
@malithie This is added to consider the migration impact. I updated the description accordingly.
