### ISSUE TITLE
Invalid behavior in introspection endpoint signature validation

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8494]
**Describe the issue:**
When the UseSPTenantDomain property is disabled in identity.xml (By default it is disabled), the self-contained access token will be signed by the user's tenant in the Saas application on a multi-tenanted environment. However, during the introspection process, it validates the signature of the token with the certificate of SP's tenant. This should be corrected with, as it is signed by the user's tenant, it must be validated by the user's tenant itself. It should validate the token with the SP's tenant only if the `UseSPTenantDomain` is enabled.

However, we'll have to include the user's tenant in the JWT token as a realm to identify the user's tenant in the token introspection process as similar to the logic used in the ID token [1]. During the introspection process, we'll have to retrieve the user's tenant from the realm if the `UseSPTenantDomain` is disabled.

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java#L880

[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oidc.session/src/main/java/org/wso2/carbon/identity/oidc/session/servlet/OIDCLogoutServlet.java#L535

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
