### ISSUE TITLE
Performance issue in SCIM2 Groups filter with excludedAttributes

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8498]
**Describe the issue:**
There is a performance issue on SCIM group filters when we obtain the id of the role using the below request.
````
curl -k --user admin:admin 'https://localhost:9443/scim2/Groups?filter=displayName+eq+RolDemo&excludedAttributes=members'
````
However, even though the members attribute is marked as an excluded attribute, it retrieves the member list of the group first, and then it removes the members from the obtained list to generate the output. This logic affects the performance of the request when we're having a large number of users in a group as it tries to retrieve all the members.
As a suggestion, we can eliminate retrieving the excluded attributes instead of retrieving those attributes and filtering out.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
