### ISSUE TITLE
Support Access Requests for Discoverable Applications in User-Portal

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8504]
**Is your feature request related to a problem? Please describe.**
In the latest milestone of IS 5.11.0, there is no capability for end users to request access to a specific application.

**Describe the solution you would prefer**
End users must have the ability to request access to a specific discoverable application from the user-portal.

**Additional context**
Related issue: #6794 
Related blog: [https://medium.com/@johann_nallathamby/how-to-access-requests-approvals-in-wso2-identity-server-913868f896a](https://medium.com/@johann_nallathamby/how-to-access-requests-approvals-in-wso2-identity-server-913868f896a)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
