### ISSUE TITLE
Validate self-registration using function library

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#8513]
**Is your feature request related to a problem? Please describe.**
More customizable logic during the self-registration validation using the functional libraries. 

In CIAM, there can be many rules to create an account. Like age must be greater than 21. Should be from a specific country. 

**Describe the solution you would prefer**
We can make this easily customizable by invoking a functional library in the self-registration flow exposing all the claims to the script. Then the script can validate those and allow or fail the registration flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
