### ISSUE TITLE
No conditional function for failing auth flow and redirect to the redirect URL

### ISSUE THREAD

**Issue by Akila94** [wso2/product-is#8515]
**Description:**

The [sendError function](https://docs.wso2.com/display/IS570/Adaptive+Authentication+JS+API+Reference#AdaptiveAuthenticationJSAPIReference-sendError(url,parameters)) only ends the authentication and redirects to an error page. A function is required to end the authentication flow as failed and to redirect to a redirect URL.

1. Using sendError function to redirect to a desired redirect URI is not the intended purpose of the function.

2. sendError function is used to redirect to an error page other than a redirect URL.

3. According to [OIDC specification](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.6), any extra parameter other than the parameters specified in [oAuth specification](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) should not be appended to the redirect URL when the authentication is failed.

4. But when using sendError method is used to redirect to a redirect URL (which is not the standard practice), two extra parameters named "sp" and "tenantDomain" are appended, violating the above specs. The purpose of passing the tenant domain and SP in the error URL generated by this method would be to pass information to custom error pages that are themed based on tenant or application. So we cannot remove appending those parameters from sendError function.

5. There is no function in the framework to end the authentication flow as failed and redirect to a redirect URL with required parameters appended to the URL. 

**Steps to reproduce:**
1. In adaptive authentication script, use the sendError function to redirect to a redirect URL.
2. The "sp" and "tenantDomain" parameters will be appended to the redirect URL.

**Comment by mefarazath** [comment]
Docs https://github.com/wso2/docs-is/issues/1821
