### ISSUE TITLE
Terminate session option in Active IDP sessions in user-portal does not work

### ISSUE THREAD

**Issue by yuniet87** [wso2/product-is#8519]
**Describe the issue:**
When accessing the `Terminate session` or `Terminate All` option the session does not really close even though it displays the message "No active IDP sessions"

**How to reproduce:**
1. Login to the user-portal.
2. Go to Security->Active IDP sessions->Terminate All or Show more->Terminate
3. It show `No active IDP sessions` but you can still modify Personal Info without asking to authenticate again.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Docker 19.03.9
 - Database: PostgreSQL 12.2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
