### ISSUE TITLE
Check SAML session existance, using session index

### ISSUE THREAD

**Issue by VIKRAMAS** [wso2/product-is#8522]
I am trying to query whether the SAML session exists for a session index using the following code mentioned document https://is.docs.wso2.com/en/5.9.0/learn/querying-saml-assertions/. Even after logout also, if I query using session index it is giving success response.  If I check database even after logout that particular session for the session index exists.  So, is there any way I can query a SAML session using session index.

For reproducing the issue:
After login use the saml tracer to get session index. Once login you can check in db the session index will be persisted. But if you logout or time expiry happens then also the session index exists in db.

**Comment by Vladamson** [comment]
Has this question been answered?  I'm having a similar problem..  Is there an easy way to check to see if a session is valid using the Session Index...

**Comment by VIKRAMAS** [comment]
@Vladamson this question is still not answered.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
