### ISSUE TITLE
Revoked access tokens are issued with 2FA

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8529]
**Describe the issue:**
When an OIDC SP is configured with 2FA (particularly SMS OTP), it returns revoked tokens when a cache is having a token which is obtained from the DB when the token is active.

**How to reproduce:**
1. Configure an SP with 2FA (1st: Basic, 2nd: SMS OTP)
2. Login to the application and the application receives an access token.
3. Restart the server (To clear the cache).
4. Logout from the application and login again.
5. The application should receive the same access token which obtained earlier since the access token is still valid (Please do this step before the token get expired).
7. Revoke the token (/ouath2/revoke)
8. Logout from the application and login again.
9. The application receives the same access token which obtained earlier - Which we revoke in the previous step.

**Expected behavior:**
It should return a new access token in step 9.

**Comment by mefarazath** [comment]
Does this mean in the revoke flow the token does not get cleared from the cache properly?

**Comment by mifrazmurthaja** [comment]
Yes due to the name mismatching.
