### ISSUE TITLE
Email body for AccountUnlockTimeBased template is misleading.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#8531]
**Description**

Account Unlock Time Based [1] email is received only upon successful authentication after the unlock time is exceeded which is the expected behavior. However, in the email body, it is mentioned as **unlocked automatically as the locked time exceeded** which gives the wrong understanding hinting that the mail should be received as soon as the account lock time has exceeded. Therefore the email body needs to be modified to avoid this confusion.

<img width="682" alt="Screenshot 2020-06-19 at 09 02 53" src="https://user-images.githubusercontent.com/24982871/85097854-7890c680-b216-11ea-8220-64c5d5c7682a.png">

**Environment information**

 - Product Version: IS 5.10.0

[1] https://is.docs.wso2.com/en/latest/learn/account-locking-by-failed-login-attempts/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
