### ISSUE TITLE
Handle userstore failures gracefully without affecting other userstores

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8535]
**Describe the issue:**
When we are having multiple secondary user stores if any of them fails (eg: network issue) during the iteration, the whole flow breaks.

Some example flows which breaks
- Authentication flow
- Listing users on the management console

**How to reproduce:**
- Add two secondary userstores and shutdown the first one in the set
- Then try to login with a user on the working userstore or list the users from the management console

**Expected behavior:**
If one of the userstores fails, it should skip the failing userstore and continue to search on others.

**Comment by darshanasbg** [comment]
This has to be done without generating\implying any incorrect results.

ie.
- Successfully authenticating a user who resides in a healthy\active user store shouldn't be interrupted by having a faulty user store in the system at that moment.

But in a case like user listing, sharing the list successfully **without any indication mentioning this is a partial result** will lead to incorrect business flows.

**Comment by darshanasbg** [comment]
Thus,
- Improve circuit breaker implementation to allowing to decide continuing or breaking based on the operation
- Impl the circuit breaker for all user store types
- Improve external facing APIs to share the indication that this is a partial result
- Improve (tenant) health-check API to share the status of the availability of its configured resources (userstores).

**Comment by LahiruLS** [comment]
To track the error in the authentication flow, I have created the https://github.com/wso2/product-is/issues/9518

**Comment by tharakawijekoon** [comment]
Issues with the OIDC flow[1] and SCIM2[2] related to this.
[1]https://github.com/wso2/product-is/issues/9479
[2]https://github.com/wso2/product-is/issues/9522

**Comment by rksk** [comment]
Regarding @darshanasbg's comment on partial results for listing flows, it seems the implementation is done for some flows to return the partial result without any indication. The following references, there are more places which does the same by iterating the user stores list in `userStoreManagerHolder` and skip exceptions within the loop.

[1] https://github.com/wso2/carbon-kernel/blob/adeeb84630ccd8ee6fd0334279a5215e704b79d2/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L6468
[2] https://github.com/wso2/carbon-kernel/blob/adeeb84630ccd8ee6fd0334279a5215e704b79d2/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L6696
[3] https://github.com/wso2/carbon-kernel/blob/adeeb84630ccd8ee6fd0334279a5215e704b79d2/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L8093

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by SujanSanjula96** [comment]
This is fixed with https://github.com/wso2/carbon-kernel/pull/3632
