### ISSUE TITLE
XACML Policy Name with Colon is not Displayed Correctly 

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-is#8548]
**Describe the issue:**

The Policy View incorrectly displays any policies with a colon in their name (they appear correctly under Policy Administration)

![image001 (1)](https://user-images.githubusercontent.com/525801/85342161-c91a5500-b49e-11ea-83bc-df9ffbff8bba.png)

![image002 (3)](https://user-images.githubusercontent.com/525801/85342163-c9b2eb80-b49e-11ea-894e-1754fb604376.png)

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
