### ISSUE TITLE
Allow dynamic query param values to be resolved from adaptive scripts in SAML outbound authenticator

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#8552]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/wso2/product-is/issues/8149 for SAML outbound flows

**Comment by Kanapriya** [comment]
Verified the config in SAML flow with wso2is-7.0.0-pre-RC.zip and its working as expected.


https://github.com/wso2/product-is/assets/13362482/1dfe25b9-2fed-43c0-ba08-c778304882f5
