### ISSUE TITLE
Configuration Management API throws ConfigurationManagementClientException on resource not found

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8555]
**Describe the issue:**
At its current state, the Configuration Management API throws a `ConfigurationManagementClientException` when `getResourceType` is called for an unknown resource type. The only way to check the presence of a particular resource type is to allow the exception to be thrown and check whether its code is equal to `ERROR_CODE_RESOURCE_TYPE_DOES_NOT_EXISTS`. 

**Expected behavior:**
As the above solution in the issue description is basically a workaround, it is better to throw a `NotFoundException`.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
