### ISSUE TITLE
REST API for managing CORS at SP config level

### ISSUE THREAD

**Issue by abhi4u1947** [wso2/product-is#8560]
**Is your feature request related to a problem? Please describe.**
REST API for managing CORS at SP config level

**Describe the solution you would prefer**
Suggestion: Instead of offering CORS only at Tenant Level, it should be offered at SP level config as well for better tracking and alignment.

**Additional context**
Reference : Implement a REST API for managing CORS #8550

**Comment by ruwanta** [comment]
Could you please explain why SP level CORS configuration is needed. 

For the current design, I do not think having the SP level config has much use. All use cases can be achived with tenant level configuration.

**Comment by abhi4u1947** [comment]
Let's assume following use case: 
- We have Tenant for ABC Corp
- ABC Corp has multiple Micro Services Public APIs SPs created.
- ABC Corp has many clients which use its Public APIs in their SPA Apps.
- ABC Corp was to support for CORS for those Public APIs related third party client SPAs
- With CORS support at Tenant Level all this can be achieved.
- Now, ABC Corp add more SPs for other APIs but they don't want to have CORS support for those.

Adding that at Tenant level make it applicable to all, at the same time there is no tracking possible that we have added CORS support for which SPs.

Hope it clarifies.

BTW, i have created this feature after getting +1 from @prabath on slack channel.

**Comment by ruwanta** [comment]
Initial thought for the Application level CORS processing and tenant level processing.

![CORS](https://user-images.githubusercontent.com/1294542/85652502-92c01e00-b6c8-11ea-9d36-9e5682256e23.png)

**Comment by abhi4u1947** [comment]
One question, does config service support the SP level configuration ?

**Comment by ruwanta** [comment]
@abhi4u1947 
No, it does not. We do not have plans to add SP wise config in near term releases. Tenant wise config is only planned on next release. 
Yes, this feature request will be kept open, as it is going to be a valuable feature in mid term.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
