### ISSUE TITLE
Configurations management feature is not available in IS KM 5.7

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#8561]
**Describe the issue:**
Configurations management feature[1] is available in the IS 5.7.0 but not available in IS 5.7.0 km. 

**How to reproduce:**
Try the feature[1] in IS km 5.7.0 product.

**Expected behavior:**
IS and IS-KM both should have the same feature.

[1] https://docs.wso2.com/display/IS570/Using+the+Configuration+Management+REST+APIs

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
