### ISSUE TITLE
Introduce a new REST API to manage access tokens

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#8570]
**Description**

Similar to the session API that we have at the moment, WSO2 should have a REST API to retrieve the token information. 
We should have the following functionalities from the API. 
* Retrieve all active token information
* The token information should have the binding details. 
* If the binding is common-auth cookie, the session information also could be retrieved. 
* Revoke tokens by giving the binding

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
