### ISSUE TITLE
Claims not returned for users with email as username - userinfo endpoint

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8573]
**Describe the issue:**
After the fix provided by the [PR](https://github.com/wso2-support/identity-inbound-auth-oauth/pull/653), the username will be obtained as follows.
````
username = accessTokenDO.getAuthzUser().getUserName();
````
The returned username will be a tenant aware username. (It will return user1@mail.com for the user, user1@mail.com@dom.com). Then the user claims will be retrieved as follows.
````
Map<String, String> userClaims = userstore.getUserClaimValues(MultitenantUtils.getTenantAwareUsername
                (username), claimURIList.toArray(new String[claimURIList.size()]), null);
````
However, since the above username is already a tenant aware username, when we invoke the MultitenantUtils.getTenantAwareUsername for the returned username (user1@mail.com), it will consider mail.com as a tenant domain and will return the username: user1.
Since there is no such user with the username user1, the userClaims will be empty.

 - Product Version: IS 5.7.0

**Comment by pamodaaw** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1405
