### ISSUE TITLE
Add a better claim support for the new WS-Federation implementation

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#8575]
**Is your suggestion related to an experience ? Please describe.**

The new implementation of WS-Federation introduced with https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/94 does not have a proper claim support. In the current process the claims requested will be set into the response and straight away sent back to the client. 

**Describe the improvement**

The implementation should be able support claims in the same way as the previous/old implementation or better.

**Additional context**

I have tried the process at https://github.com/deshankoswatte/identity-inbound-auth-sts/tree/new-passive-sts-claim-support which uses the same method as the previous implementation but unfortunately due to some issues and the time being had to left it out.

**Related Issues**

https://github.com/wso2/product-is/issues/8557

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
