### ISSUE TITLE
Remove embedded dependencies in the new WS-Federation implementation

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#8576]
**Is your suggestion related to an experience ? Please describe.**

The new implementation of WS-Federation introduced with https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/94 has all the cxf, wss4j and other dependencies embedded. This should be ideally removed and exposed to the product eventually. 

**Describe the improvement**

The dependencies should be exposed to the product. Some of those dependencies can be straight away bundled into the product as they are already in the form of OSGi and some of them may need orbits.

**Additional context**

Even if the task seems to be easy on the top there will be a lot of errors that can occur while providing this improvement and the assumption is based on what I have tried to expose those dependencies.

**Related Issues**

https://github.com/wso2/product-is/issues/8557

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
