### ISSUE TITLE
Reimplement WS-Trust functionality using newer OpenSAML version

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#8577]
**Is your suggestion related to an experience ? Please describe.**

WS-Federation implementation was re implemented using OpenSAML3 with https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/94 and with that PR WS-Trust functionality was provided as a connector because it uses old versions of opensaml, wss4j and rampart. Since the WS-Trust functionality is not in the default product it is a bad user experience to attach the connector each time a new release is released.

**Describe the improvement**

WS-Trust functionality should be re implemented using newer OpenSAML version and should be provided with the default product rather than a connector also we should avoid using both wso2-wss4j and wso2-rampart because those do not get updated with the new dependencies. 

**Additional context**

An available option would be the alternative implementation for WS-Trust has been implemented for GSoC 2017[1][2][3][4] using msf4j and CXF. I tried to test this out with the product. But since this implementation was based on C5, without major changes, we could not add it to the product. If that option does not work then we will have to redo the task in a different method.

[1] - [Architecture] [Dev] [IS] GSoC 2017 - WS-Trust Implementation for IS6
[2] - [Dev] [IS] GSoC 2017 - WS-Trust Implementation for IS 6.0.0 using Apache CXF Library
[3] - [wso2-incubator/mss4j-ws-trust#1](wso2-incubator/mss4j-ws-trust#1)
[4] - [https://github.com/IsurangaPerera/mss4j-ws-trust](https://github.com/IsurangaPerera/mss4j-ws-trust)

**Related Issues**

https://github.com/wso2/product-is/issues/8557

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
