### ISSUE TITLE
Provide iwa as a connector due to the STS changes

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#8578]
**Is your suggestion related to an experience ? Please describe.**

With [https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/94](https://github.com/wso2-extensions/identity-inbound-auth-sts/pull/94) we have provided the WS-Trust functionality as a connector and because of this some of the [https://github.com/wso2-extensions/identity-carbon-auth-iwa](https://github.com/wso2-extensions/identity-carbon-auth-iwa) required packages will only be visible when the WS-Trust connector is added. So if the iwa jars are added then we should also add the WS-Trust connector to it else it will not work.

**Describe the improvement**

We can provide this as a connector where the WS-Trust functionality will be added with the iwa connector which will be easier for user.

**Related Issues**

https://github.com/wso2/product-is/issues/8557

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
