### ISSUE TITLE
Resend confirmation code doesn't work for ASK_PASSWORD scenario

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#8587]
**Describe the issue:**
Resend confirmation code doesn't work for the ASK_PASSWORD recover scenario after the WUM update.

**How to reproduce:**
- Configure the ask password option [1].
- Create a user from the management console from the ask password option.
- Try to resend the confirmation code request with the ask password option [2].
- First request will be successful and it'll send the email and also in that flow, it'll update the IDN_RECOVERY_DATA for the same user and it causes the issue.
- Send the resend confirmation code again and it'll fail.

**Sample Request**
<pre style="color:#000020;background:#f6f8ff;">curl -k -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '<span style="color:#406080; ">{</span><span style="color:#1060b6; ">"user"</span><span style="color:#308080; ">:</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"username"</span><span style="color:#308080; ">:</span> <span style="color:#1060b6; ">"isuru"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"realm"</span><span style="color:#308080; ">:</span> <span style="color:#1060b6; ">"PRIMARY"</span><span style="color:#406080; ">}</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"properties"</span><span style="color:#308080; ">:</span> <span style="color:#308080; ">[</span><span style="color:#406080; ">{</span><span style="color:#1060b6; ">"key"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"RecoveryScenario"</span><span style="color:#308080; ">,</span><span style="color:#1060b6; ">"value"</span><span style="color:#308080; ">:</span><span style="color:#1060b6; ">"ASK_PASSWORD"</span><span style="color:#406080; ">}</span><span style="color:#308080; ">]</span><span style="color:#406080; ">}</span>' "https:<span style="color:#595979; ">//localhost:9443/api/identity/user/v1.0/resend-code"</span>
</pre>

**Environment information**  **:**
 - Product Version: [IS-5.7.0+1593096174544]

[1] - https://docs.wso2.com/display/IS570/Creating+Users+Using+the+Ask+Password+Option
[2] - https://docs.wso2.com/display/IS570/apidocs/self-registration/#!/operations#ResendConfirmation#resendCodePost

**Comment by tharindu-bandara** [comment]
Configure resend confirmation code for ask password: https://docs.wso2.com/display/IS570/Resending+Account+Recovery+Confirmation+Emails

**Comment by tharindu-bandara** [comment]
Already fixed in the code base with https://github.com/wso2-support/carbon-identity-framework/commit/17cc17cea90e962db4bacf4e71d7ae069419976f.
