### ISSUE TITLE
Fixing ambiguity in OAuth consent page "Approve once" and "Approve Always" words

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#8588]
**Is your suggestion related to an experience ? Please describe.**
Fixing ambiguity in OAuth consent page "Approve once" and "Approve Always" words
**Describe the improvement**
Current behaviour
**Approve once** -  User needs to approve all time if clicks on approve once.
**Approve Always** - User needs to approve only one time.

**Comment by nirmal070125** [comment]
We can use something similar to following;
- Always prompt
- Prompt once and remember

**Comment by IsuraD** [comment]
we can have two buttons - **Approve** and **Deny**
- **Deny** button covers Deny approval
- **Approve** button covers approve current session only
- Checking the "**Remember my approval**" checkbox covers  approve all sessions
