### ISSUE TITLE
Implement SCIM 2.0 Role API

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#8591]
**Description:**

A new role management API needs to be implemented via SCIM 2.0 along with the separated group and role concepts. This role should be able to assign to a user or a group. Also, the relevant permissions can be added to the role.

**Role:** Roles within IAM solution. That binds with permissions defined for resources within the IAM solution. This can be mapped to present hybrid roles

**Comment by pulasthi7** [comment]
@ashensw Is the migration also covered for this feature?

**Comment by ashensw** [comment]
> @ashensw Is the migration also covered for this feature?

Not yet. It will be covered as a separate task. the Main git issue can be found here: https://github.com/wso2/product-is/issues/8123
