### ISSUE TITLE
Host the WS-Trust connector to the connector store

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#8597]
**Is your suggestion related to an experience ? Please describe.**

Currently any user using the connector should build it from the repository https://github.com/wso2-extensions/identity-inbound-auth-sts/tree/master/components/org.wso2.carbon.sts.connector and then configure the connector.

**Describe the improvement**

A better approach would be hosting the WS-Trust connector in the connector store for the user's ease of use.

**Related Issues**

https://github.com/wso2/product-is/issues/8557

**Comment by sachiniWettasinghe** [comment]
This task is completed and the connector can be accessed from [1]. Hence closing the issue.

[1] https://store.wso2.com/store/assets/isconnector/details/417e7ef2-76fb-424f-92b3-d5eb58e2efe6
