### ISSUE TITLE
Service Provider Adaptive Script is disabled when created using REST API

### ISSUE THREAD

**Issue by gkaran** [wso2/product-is#8602]
**Describe the issue:**
I' ve been trying to create a Service Provider using an adaptive authentication script using the REST API that is documented [here](https://is.docs.wso2.com/en/latest/develop/application-rest-api/#/Applications/createApplication). Once I create the Service Provider through and add my keys to my application to authenticate (using Oauth2/OpenID) it seems as the script is completely ignored. Indeed, after looking in the database I found out that the `is_enabled` column on `sp_auth_script` table is false (0) for the newly created script. After some source code investigation, it seems that `UpdateAuthenticationSequence::updateAdaptiveAuthenticationScript` (from identity-api-server module), never sets the `enabled` property of `AuthenticationScriptConfig` and as a result, since it has no default value it evaluates to `false` meaning that all scripts created via the REST API will never be enabled (unless you just visit the admin console and "update" them just to set the flag to true).

**How to reproduce:**
1. Create a Service Provider with the API stated [here](https://is.docs.wso2.com/en/latest/develop/application-rest-api/#/Applications/createApplication) using an adaptive authentication script.
2. Query `sp_auth_script` table to verify that the newly created script is marked as disabled.
3. From the admin console, go to the service provide and open the adaptive authentication script editor. Without touching it, click update and then once more to "save" the Service Provider changes. 
4. Query again `sp_auth_script` and now you should see that the script is enabled.

**Expected behavior:**
Having the adaptive authentication script enabled when created via the REST API.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: PostgreSQL
 - Userstore: JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by senthalan** [comment]
@mefarazath

**Comment by NipuniBhagya** [comment]
@gkaran We couldn't reproduce the issue you have reported. Can you please share your API request with us, so that we can look into it further?

**Comment by gkaran** [comment]
Sure thing. Here is an example with some sensitive information "hidden":

```shell
curl --insecure --location --request POST 'https://localhost:9443/api/server/v1/applications' \
--user admin@wso2.com:admin \
--header 'Content-Type: application/json' \
--data-raw '{ 
    "name": "Foo Bar", 
    "description": "Demonstration example for disabled adaptive authentication script.", 
    "accessUrl": "https://localhost:6443/login", 
    "inboundProtocolConfiguration": { 
    "oidc": { 
        "grantTypes": ["authorization_code", "refresh_token"],  
        "callbackURLs": ["regexp=(https://localhost:6443/oauth2client|https://localhost:6443/logout)"],  
        "publicClient": false,  
        "pkce": { 
            "mandatory": true,  
            "supportPlainTransformAlgorithm": true 
        },  
        "accessToken": { 
            "type": "Default",  
            "userAccessTokenExpiryInSeconds": 3600,  
            "applicationAccessTokenExpiryInSeconds": 3600 
        },  
        "refreshToken": { 
            "expiryInSeconds": 86400,  
            "renewRefreshToken": true 
        },  
        "idToken": { 
            "expiryInSeconds": 3600,  
            "encryption": {"enabled": false, "algorithm": "RSA-OAEP", "method": "A128CBC+HS256"} 
        },  
        "logout": { 
            "backChannelLogoutUrl": "https://localhost.com:6443/backchannel/logout",  
            "frontChannelLogoutUrl": "https://localhost:6443/logout" 
        },  
        "validateRequestObjectSignature": false 
        } 
    },  
    "authenticationSequence": { 
        "type": "USER_DEFINED",  
        "steps": [ 
            { 
                "id": 1,  
                "options": [ 
                    {"idp": "LOCAL", "authenticator": "BasicAuthenticator"} 
                ] 
            } 
        ],  
        "script": "// This script will step up authentication for any user belonging\n// to one of the given roles\n// If the user has any of the below roles, authentication will be stepped up\n\nvar rolesToStepUp = [\"foobar-user\"];\nvar domain = '\''https://localhost:6443'\'';\n\nvar onLoginRequest = function(context) {\n  executeStep(1, {\n    onSuccess: function (context) {\n      // Extracting authenticated subject from the first step\n      var user = context.currentKnownSubject;\n      // Checking if the user is assigned to one of the given roles\n      var hasRole = hasAnyOfTheRoles(user, rolesToStepUp);\n      if (hasRole) {\n        Log.info(user.username + \" Has one of Roles: \" + rolesToStepUp.toString());\n      } else {\n        sendError(domain + '\''/error'\'', {'\''errorcode'\'':'\''000403'\'','\''errorMsg'\'':'\''You are not allowed to login to this app.'\''});\n      }\n    },\n  });\n};",  
        "subjectStepId": 1,  
        "attributeStepId": 1 
    },  
    "advancedConfigurations": { 
        "saas": true,  
        "discoverableByEndUsers": false,  
        "certificate": { 
            "type": "PEM", 
            "value": "-----BEGIN CERTIFICATE-----\n******\n-----END CERTIFICATE-----\n" 
        },  
        "skipConsent": true,  
        "returnAuthenticatedIdpList": false,  
        "enableAuthorization": false 
    }, 
    "provisioningConfigurations": { 
        "inboundProvisioning": { 
            "proxyMode": false,  
            "provisioningUserstoreDomain": "PRIMARY" 
        } 
    } 
} '
```

**Comment by brionmario** [comment]
The same issue can be observed when configuring adaptive authentication using the [Console](https://localhost:9443/console) [1]. Once the API is fixed, https://github.com/wso2/product-is/issues/10000 should be automatically resolved.

[1] https://github.com/wso2/product-is/issues/10000

**Comment by rksk** [comment]
As per my understanding, this happens only when we create an app with a script that causes a warning. In the carbon console, we can skip the warning. But not from APIs.

example; (when there is no 3rd step)
```
var onLoginRequest = function(context) {   executeStep(3);};
```
