### ISSUE TITLE
Introduce Description to Identity Connector Config

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#8603]
### Descriprion
As a part of the new UI designs in portals, we need to show a description or a tag line for each connector. At the moment, the ConnectorConfig [1] interface doesn't include such a method. Either we could add a new method to pass description and implement all our existing connectors, or we can just add a method and read the content from the governance API.

[1] - https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/ConnectorConfig.java

Refers: https://github.com/wso2/identity-apps/issues/1007

**Comment by thanujalk** [comment]
This is fixed now.
