### ISSUE TITLE
Introduce Category Order to Identity Governance Connectors

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#8604]
### Description
At the moment, all governance connectors are grouped into categories and the Governance RESP API returns these categories without a specific order. We've made the UI side dynamic and display the categories as it is, and to be meaningful and user friendly, an order is required.

Refers: https://github.com/wso2/identity-apps/issues/1007

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
