### ISSUE TITLE
ReStructure Identity Governance Connectors

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#8605]
### Description
There are a number of governance connectors that we ship with the product and these were added periodically for different requirements. Now we're at a point where some of the functionalities depend on each other and some have rather complex behavior. I believe it's high time that we have a look at them in general and restructure them. 

One major problem with the connectors is that user account locking is handled from multiple points. And also the admin locking user accounts via claim change only works if the lock idle accounts feature is enabled, even though the one has nothing to do with the other. We could have a general connector to handle account locking based on the lock claim and all other connectors could just change the claim value and be done with it.

Refers: https://github.com/wso2/identity-apps/issues/1007

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
