### ISSUE TITLE
Introduce Property Type for Identity Connector Property

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#8606]
### Description
At the moment the connector config interface doesn't allow to provide a type of the property field, which is important when we display the property in the UI. We've been using few hacks to change the UI forms such as adding __secrete__ to the property name to denote secret fields and _url_ for URL input fields. If we could introduce a type to each property, we can overcome this issue and display the properties without a hassle.

Refers: https://github.com/wso2/identity-apps/issues/1007

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
