### ISSUE TITLE
Improve DCR Endpoint Error Handling

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#8615]
Currently for building the HTTP error response, we have to append the HTTP Status message to the internal error code.  https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth.dcr.endpoint/src/main/java/org/wso2/carbon/identity/oauth2/dcr/endpoint/util/DCRMUtils.java#L98

This needs to be improved to be able to properly define API error codes and generating error responses based on the error codes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
