### ISSUE TITLE
Unable to set tokenexpirytime for sms otp.

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#8620]
**Describe the issue:**
By default, we didn't provide config to set property for token expiry time, there is no default value also. For version 5.10 setting this property via deployment.toml throws Class conversion error. But later this bug was fixed. So there is need  to provide a WUM update on this requirement. 

**How to reproduce:**
Download 5.10 pack
Configure sms otp
Add following in deployment toml file
```
[authentication.authenticator.sms_otp.parameters]
TokenExpiryTime="60"
```

**Expected behavior:**
Token expiry time configured in appicaiton-authentication.xml file.

**Environment information** **:**
 - Product Version: [S 5.10.0]
 - OS: [Linux]

**Comment by omarbahrin83** [comment]
can you guide how to update using wum for this particular update?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
