### ISSUE TITLE
SOAP API method publishToPDP does not work

### ISSUE THREAD

**Issue by ThiNepo** [wso2/product-is#8628]
**Describe the issue:**
We are trying to use the SOAP Policy Administration API to publish a policy to PDP. We tried using SOAP and REST but nothing works. In SOAP we don't receive any response back, using REST we receive status code 200, but the policy is not published (we are trying to see the change in the management GUI, but nothing changes there).

```python
from requests.auth import HTTPBasicAuth 
from requests import Session
from zeep import Client
from zeep.transports import Transport

session = Session()
session.verify = False
session.auth = HTTPBasicAuth("rsuser", "rsuser123")
client = Client(
    "https://BASE_URL:9443/services/EntitlementPolicyAdminService?wsdl",
    transport=Transport(session=session),
)

data = {
    "policyIds": ["UMApolicy_Test"],
    "version": "1",
    "enabled": True,
    "order": 30,
}

response = client.service.publishToPDP(**data)
print(response)
```

**How to reproduce:**
Try to use the publishToPDP as described in https://is.docs.wso2.com/en/latest/develop/entitlement-with-apis/#publishtopdp

**Expected behavior:**
The policy should be published.

**Environment information**
 - Product Version: 5.10.0
 - OS: Linux (Docker)
 - Database: H2

**Comment by mrderban** [comment]
Hi ! I'm encountering the exact same issue, were you able to find a solution ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
