### ISSUE TITLE
Missing toml configs/templates for embedded-ldap.xml, certificate-validation.xml, identity-mgt.properties files

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8632]
**Describe the issue:**
Missing toml configs/templates for following files:

- certificate-validation.xml
- embedded-ldap.xml - https://github.com/wso2/product-is/issues/6896
- identity-mgt.properties files - https://github.com/wso2/product-is/issues/6169, "Custom Password Validators"[1] are read from the identity-mgt.properties[2]

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]

[1]https://docs.wso2.com/display/IS580/Writing+a+Custom+Password+Validator
[2]https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/IdentityMgtConfig.java#L651

**Comment by sachiniWettasinghe** [comment]
identity-mgt.properties file will not be templated as it is decided to deprecate this file from the product.

**Comment by BradNut** [comment]
@sachiniWettasinghe The above comment provides no insight into what is replacing those properties when converting to a deployment.toml file. How would one implement password policy extensions in the deployment.toml if the file they currently exist in, identity-mgt.properties, is being deprecated with no clear path of migration.

For example [Writing a Custom Password Validator](https://is.docs.wso2.com/en/latest/develop/writing-a-custom-password-validator/#writing-the-custom-password-policy) just states at the top "These instructions will be deprecated.".

Deprecated and replaced with what?
