### ISSUE TITLE
It is forced the SSL when "ssl_certificate_validation_enabled" is set to false

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#8645]
Refer code here [1]. 

It forced for SSL (create SSL socket factory) when the above property is set to false. It means that even for LDAP connections (non-SSL), it tries for SSL

[1] https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/ldap/LDAPConnectionContext.java#L221

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
