### ISSUE TITLE
Issue in assigning the custom role of Primary Userstore to user of Secondary Userstore

### ISSUE THREAD

**Issue by SwatiNEC** [wso2/product-is#8649]
Hi 

I am using WSO2 IS 5.7.0 and  I am facing below issues:
1.	When I login with admin user of primary userstore, the role “testManager” is displayed for both tenants but the “Login” permission is not enabled for tenants of both secondary userstore. This issue is reproduced in Step 3(c)
2.	When I login with admin user of any secondary userstore, I am not able to view custom roles of primary user store in both tenant i.e swati@test.com and swati1@test1.com. This issue is reproduced in Step 6.

Below are the steps to reproduce this issue:
1.	The user of primary user store i.e. Admin can creates two tenants (test.com and test1.com), using the multi-tenant function. Please find below screenshot:
 
![1](https://user-images.githubusercontent.com/38689838/86789736-404a0e80-c085-11ea-9d98-f2c7e84a4700.png)

2.	Admin can creates two user store i.e. test(using test.com) and test1 (using test1.com). Please find below screenshot:
![2](https://user-images.githubusercontent.com/38689838/86789801-55bf3880-c085-11ea-9341-90eabfe1ca11.png)

 
Configuration used for user store are as below:
 
![3](https://user-images.githubusercontent.com/38689838/86790423-09282d00-c086-11ea-8347-b50487717e89.png)

3.	Admin can grants the administrator of test.com and test1.com the custom role(i.e. testManager) of primary user store.
For this below steps can be performed:
a)	Create a new role under “Primary” domain i.e. testManager.
b)	Assign “Login” permissions to that role.
c)	Then this role will be displayed for both tenant but the “Login” permission is not enabled for both tenants.

4.	Now Login to the WSO2 Identity Server management console with tenant i.e.(swati@test.com) account.
5.	“swati@test.com” can creates user “demo” in user store “test.com”.
6.	“swati@test.com” can assign custom roles i.e. testManager of primary user store to newly created user.

There are no exception in the logs.

**Comment by SakshiSharma-India** [comment]
Hi @JKAUSHALYA , @sherenewso2 , @tharindu-bandara ,
Could you please share your opinion on this issue as mentioned by Swati as we need to implement this use case in our project?
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA ,
I request you to please confirm and  share your opinion on this issue as it is very urgent and we need to implement this use case in our project.
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA , @rmsamitha ,
Could you please look into this issue as it is very urgent and we need to implement this use case in our project?
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA , @rmsamitha ,
Could you please confirm on your query/issue? Or could you please confirm whom I can connect with from WSO2 team to discuss on this issue? It would be a great help.
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA , @rmsamitha , @omindu 
Could you please confirm on your query/issue? Or could you please confirm whom I can connect with from WSO2 team to discuss on this issue? It would be a great help.
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA , @rmsamitha , @omindu
Could you please confirm on your query/issue? Or could you please confirm whom I can connect with from WSO2 team to discuss on this issue? It would be a great help.
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA , @rmsamitha , @omindu
Could you please confirm on your query/issue? Or could you please confirm whom I can connect with from WSO2 team to discuss on this issue? It would be a great help.
Thanks in advance.

**Comment by SakshiSharma-India** [comment]
Hi @thanujalk , @madurangasiriwardena, @mefarazath , @JKAUSHALYA , @rmsamitha , @omindu
Could you please confirm on your query/issue? Or could you please confirm whom I can connect with from WSO2 team to discuss on this issue? It would be a great help.
Thanks in advance.

**Comment by madurangasiriwardena** [comment]
Hi @SakshiSharma-India / @SwatiNEC,

Not sure if I understood your "bug". I don't see the relationship between the tenants and the user store in your description. Are you saying you want to assign the roles in test.com user store to users in test1.com?

If you have a WSO2 support subscription please raise a support ticket. If you are a community user, please raise this in our [slack channel](https://wso2.com/identity-and-access-management/community/#Slack) to get more tracktion.

Regards,
Maduranga

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
