### ISSUE TITLE
OAuth2.0 ROLE scope binding type does not work as espected.

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#8651]
Although the scope is created through this curl command, the scope binding validation fails giving a error scope

`curl --location --request POST 'https://localhost:9443/api/identity/oauth2/v1.0/scopes' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--header 'Cookie: commonAuthId=8b824cea-e1a0-43cf-9dc5-08930a267021' \
--data-raw '{
        "name": "write_scope",
        "displayName": "Write scope for",
        "description": null,
        "bindings": [],
        "scopeBindings": [
            {
                "bindingType": "ROLE",
                "binding": [
                    "manger"
                ]
            }
        ]
    }'`

If this does not work the API documentation also should change: https://is.docs.wso2.com/en/5.9.0/develop/using-oauth2-scopes-rest-apis/

**Comment by mxm-tr** [comment]
What workaround would your recommend to perform RBAC with OAuth2 on 5.10.0 if this function is not available?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
