### ISSUE TITLE
The consent page should not come after OAuth2.0 scope validation fails

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#8654]
When try out Role based scope binding, the consent page comes even after scope validation fails. Please refer the video attach for the bug.

https://github.com/GDRDABARERA/IdentityIn15/issues/1#issue-651632736

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
