### ISSUE TITLE
Error when handling event : PRE_AUTHENTICATION

### ISSUE THREAD

**Issue by prasad4491** [wso2/product-is#8655]
**Describe the issue:**
Did migration from 2.6.0 to 3.1.0. After that try to generate token. Got below issue
{
    "error_description": "Error when handling event : PRE_AUTHENTICATION",
    "error": "invalid_grant"
}

audit logs
`TID: [-1234] [2020-07-08 19:03:12,499]  WARN {AUDIT_LOG} - Initiator=wso2.system.user Action=Authentication Target=owner Data=null Outcome=Failure Error={"Error Message":"Un-expected error while pre-authenticating, Error when handling event : PRE_AUTHENTICATION","Error Code":"31002"}

TID: [-1234] [2020-07-08 19:03:12,501]  INFO {AUDIT_LOG} - Initiator : owner@test.com | Action : PostTokenIssue | Target : PasswordGrantAuditLogger | Data : { "AuthenticatedUser" : "N/A","AuthenticatedUserStoreDomain" : "N/A","AuthenticatedUserTenantDomain" : "N/A","ServiceProvider" : "admin_62587_DefaultApplication_PRODUCTION","RequestType" : "oauth2","RelyingParty" : "cgPH2StCCpoeP2FKvPQiFDmhPHwa" } | Result : Failed `
**How to reproduce:**
https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310/#step-2-upgrade-api-manager-to-310
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - OS: [Windows]
 - Database: [POSTGRES 9.6]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by mefarazath** [comment]
Can you add more details?

For example,

- Which grant type was used?
- Any stacktraces

**Comment by prasad4491** [comment]
I am using **password** as grant types. Didn't see  any error logs. I can find above things in audit.log only.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
