### ISSUE TITLE
Increase the space between Update button and danger zone

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#8669]
In Local Attribute Edit view of the admin-portal, it's better there's a bit more separation between the **Update Button** and the **Danger Zone**

![image](https://user-images.githubusercontent.com/12439288/87140923-e08b7780-c2bf-11ea-9623-d9a779dca02e.png)

**Comment by thanujalk** [comment]
This is fixed now.

<img width="520" alt="Screenshot 2020-10-28 at 19 44 31" src="https://user-images.githubusercontent.com/1498339/97447889-0b283b80-1956-11eb-90c0-be0dc2594d52.png">
