### ISSUE TITLE
Update Username and Password in one Transaction

### ISSUE THREAD

**Issue by johannnallathamby** [wso2/product-is#8671]
**Describe the improvement**
Currently we don't have a method in our UserStoreManager to update the username and password in one transaction. In scenarios where we want customers to update their usernames and passwords, there needs to be a method to do this in one transaction. Otherwise the user entry will go to an inconsistent state where user's username might have been updated and password might have not been updated.

**Additional context**
This issue was encountered when we had to do a migration of user base for a customer. For some customers their existing usernames and passwords had to be updated because they were not compliant with the new policies.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
