### ISSUE TITLE
Pagination support for config management search API

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#8673]
**Problem**
Search API takes a lot of time and load balancer timesout if there are many matching resources for the search query.

**Solution**
Introducing pagination and sorting for search API of configuration management.

**Product version**
5.7.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
