### ISSUE TITLE
Error when updating email address with verification enabled

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8686]
Steps to reproduce,

1. Enable `Trigger a verification notification when user's email address is updated.` from Resident IDP.
![email-update-verification](https://user-images.githubusercontent.com/5061791/76929456-3354b400-690a-11ea-8327-7c3f3e354796.png)
2. Login to https://localhost:9443/user-portal
3. Update `Email` under `Personal info`.

Following error notification is shown in the portal. Email is not updated, neither any information displayed informing the user about the verification steps.

![image](https://user-images.githubusercontent.com/5061791/76929599-9e9e8600-690a-11ea-9e6a-ae19a0dc589d.png)

**Comment by rksk** [comment]
Fixed with https://github.com/wso2/product-is/issues/9046
