### ISSUE TITLE
Inconsistency in username when viewing user sessions of super tenant.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8688]
Steps to reproduce
1. Setup an OIDC application (pickup manager) and login as super.tenant user
2. In the same browser login to user-portal 
3. carbon.super is appended to the username only for user-portal view as in below image.
![user-sessions](https://user-images.githubusercontent.com/5061791/75417763-ce83ea80-5957-11ea-9c8b-de5fa68dde2b.png)

**Comment by jeradrutnam** [comment]
This will be needed for tenant level my account app. Where this app will use by end users of that tenant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
