### ISSUE TITLE
There is no proper error message or server log, that inform user to account is locked

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8690]
**Is your feature request related to a problem**
There is no proper error message or server log, that informs the user to that account is locked

**Describe the solution**
It is better we can popup an error message and 
e.g server log-> "ERROR {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} - System error while Authenticating/Authorizing User : Account is locked for user admin in user store PRIMARY in tenant wso2.com. Cannot login until the account is unlocked."

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
