### ISSUE TITLE
Inconsistency in UX when using tenanted URLs in user-portal

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8692]
Steps to reproduce
1. Create a tenant wso2.com in the WSO2 IS.
2. access https://localhost:9443/user-portal
3. login as super.tenant user 'admin:admin'
4. In the same browser access 'https://localhost:9443/t/wso2.com/user-portal'
5. Following error page is displayed
![tenant-sign-in](https://user-images.githubusercontent.com/5061791/75416943-cc209100-5955-11ea-8d40-4bee8025f9f6.png)

6. In the same browser access 'https://localhost:9443/t/wso2.com1/user-portal', with a non-existing tenant.
7. A blank page is displayed

In both cases, user experience can be improved.

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/8695
