### ISSUE TITLE
Showing SP logo in authenticationendpoint

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#8694]
**Is your feature request related to a problem? Please describe.**
For an example, in the consent page currently looks like this,
<img width="481" alt="Screen Shot 2019-12-15 at 10 48 22 AM" src="https://user-images.githubusercontent.com/1617810/70858470-952b0980-1f28-11ea-9290-2d99b1eafead.png">

It's better if we can show the SP image logo along with the SP name.

Similarly we can think of adding the SP image in places like login page if its appropriate.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
