### ISSUE TITLE
Display specific error messages instead of a generic one where a specific error message is available

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8696]
API request failures show a generic error message even when specific error messages accurately describing the cause is available. For example, when trying to link a user account belonging to a different tenant domain, a generic error message displayed though the network request returns an error message saying that cross tenant association is not allowed. 
![image](https://user-images.githubusercontent.com/20745428/74600666-ade7a500-50ba-11ea-9564-9d6de5567e8b.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
