### ISSUE TITLE
Buttons are not accessible using shortcuts

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8698]
A user should be able to access buttons using shortcuts. Right now, the shortcuts don't work and the user has to click on buttons to access them.

**Comment by nilasini** [comment]
@DimalChandrasiri are u working on this?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
