### ISSUE TITLE
Add a place to view information about Authentication Script templates

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8703]
**Description:**
In the WSO2 IS Management Console, authentication script templates has an option to view information related to the corresponding template. But in the new Developer Portal, that feature is missing.

<img width="1914" alt="Screen Shot 2020-06-25 at 10 37 03 AM" src="https://user-images.githubusercontent.com/25959096/85658508-f51d1c80-b6d0-11ea-9f3d-2ff8ffbb1aa9.png">

**Comment by thanujalk** [comment]
Fixed
