### ISSUE TITLE
Add UI component to display the idle user logout warning.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#8704]
### Description

- With the OIDC session management implementation, we've introduced idle user logout functionality, where the user is automatically logged out from the portal if he/she is idle. Before logging the user out, we issue a warning stating that he/she will be logged out after n seconds. ATM this is just a console log and we need a proper UI component to display the warning.

**Comment by thanujalk** [comment]
Fixed

**Comment by brionmario** [comment]
Duplicate of https://github.com/wso2/product-is/issues/9317
