### ISSUE TITLE
[Usability enhancement] It is comfortable, if app required to enter email address twice in Personal info 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8708]
**Is your feature request related to a problem? Please describe.**
After enable, "Enable user email verification on update" via Management console, the newly created user does not allow to add an email address in "personal info" before confirming the email confirmation.

But the issue is here, 
the user has to add the same email address in the same place twice, without any information. 

Once user login to the user portal and add an email address in "Personal info" > email, but it will not appear, and system send an email confirmation to the provided email, once user confirms and have to re-enter the email then it will.

 **Describe the solution you'd like**
This is should be an improve, 
1. In the initial step when the user adds email, there should be any information that email confirmation has been sent, and the user has to confirm and this will expired in <expire-time >.

2. And once the user confirms the confirmation via email, then automatically the email should be displayed in profile info, instead add it twice. 

**Preconditions:**
Should enable "Enable user email verification on update" via Management console

**Comment by jeradrutnam** [comment]
This experience will be override by fix on this issue: https://github.com/wso2/product-is/issues/9046
