### ISSUE TITLE
Give a disclaimer to users when trying to navigate away from unsaved forms

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8709]
**Is your feature request related to a problem? Please describe.**
In Developer/Admin portals edit views, different sections have individual submit buttons to save the changes. If a user accidentally switches to a different tab or a page, all the changes will be lost.

**Describe the solution you'd like**
It would be better to show a disclaimer message when the forms are not pristine to improve UX.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
