### ISSUE TITLE
Implement advance search options for the applications list (attributes other than name)

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8711]
**Feature Description**
The application list should be searchable by entering manual search queries and also user's should be able to add search options and build their own search query.

The API currently only supports Searching by name and it was implemented in wso2/identity-apps#493.

**Component**
Application Management.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
