### ISSUE TITLE
Should be able to remove the profile picture

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8712]
**Describe the bug**
There is no way to remove the current profile picture if a user is in need to. 

**To Reproduce**
1. Upload the profile picture
2. Try to remove it.

**Expected behavior**
There should be a method to remove the current profile picture to a default avatar.

**Comment by thivi** [comment]
The following PR allows users to select the default system-generated initials as the avatar.
https://github.com/wso2/identity-apps/pull/1169
