### ISSUE TITLE
Dynamically generate adaptive script when adding steps

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#8714]
**Describe the Issue:**
In the management console. For a service provider if we added authentication steps the adaptive auth script also got updated according to the number of steps. But in the development-portal this doesn't happen.

This will be very confusing for a user transitioning from the management console to the developer-portal.

Also if we write a script with two steps and we have added only 1 step shouldn't this be validated as well?
```
var onLoginRequest = function(context) {
    executeStep(0);
    executeStep(1);
};
```

**Comment by thanujalk** [comment]
Until the user edits the script, we can keep adding steps to the script.
