### ISSUE TITLE
Listing all applications in the list view

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#8716]
### Description
At the moment we list all the available applications in the list view, yet the user will not be able to delete or update the application if he/she didn't have the application role. We have two questions to answer.
1. Should we list all the apps in the list view or only the ones that are accessible to the user?
   1. If we decided to list all apps, should we introduce an order of listing based on the permissions?
2. If we do list all the apps, we need to disable/hide edit, delete buttons.

**Comment by thanujalk** [comment]
@mefarazath any thoughts?

**Comment by thanujalk** [comment]
There should be an option to request attributes - readOnly and applicationType
