### ISSUE TITLE
Improve UX to handle the userstore operations delay

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#8725]
#### Description
The CRUD operations to the userstores get delayed to be reflected in the UI. So in order to handle this, it's better to implement a web worker which will be polling the userstore API and will notify the admin portal whenever a the changes that are made can be displayed in the UI.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
