### ISSUE TITLE
Improve add template type flow

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8728]
**Describe the Issue:**
Currently the adding an email template type will redirect the user to a blank listing view of the locales listing of the newly created email template type. As an improvement this flow could have steps such as adding an initial `locale` template with boilerplate template while creating the template type.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
