### ISSUE TITLE
Issue with accessing the Github API to retrieve help panel documentation.

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8732]
**Is your feature request related to a problem? Please describe.**
In the current implementation, we are accessing the Github API to retrieve data for the help side panel and doing so without any authenticator results in a 60 request limit per hour [1].

**Describe the solution you'd like**
A better approach would be to have an API that will retrieve the document structure on behalf of the portals which might enable caching opportunities.
Or there should be a mechanism to authenticate with Github API which will allow 5000 requests per hour.

**Describe alternatives you've considered**
If above is not possible, at least there should be a mechanism to authenticate with Github API which will allow 5000 requests per hour.

[1] https://developer.github.com/v3/#rate-limiting

**Comment by thanujalk** [comment]
This is no longer available in the portal
