### ISSUE TITLE
Display order is not shown even when checked

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8735]
**Describe the Issue:**
display order value is not shown in local claim edit view even if the tick is added.

<img width="795" alt="Screenshot 2020-04-30 at 18 40 39" src="https://user-images.githubusercontent.com/11191791/80714225-3bf7f700-8b12-11ea-9334-5c26d7e39685.png">

**How To Reproduce:**
Edit an attribute with display order property is added.

**Expected behavior:**
Should show the display order value.

**Comment by thivi** [comment]
This issue is not reproducible in the latest pack. I am closing this issue but please free to reopen this issue if you are able to reproduce this one with the latest pack.
