### ISSUE TITLE
user-portal empty in edge and ie

### ISSUE THREAD

**Issue by svenzimmermann** [wso2/product-is#8746]
The WSO2 IS 5.10 (release) user portal /user-portal/login is not shown under MS Edge and IE11 or there is no forwarding to /authenticationendpoint. There is only a white screen.

![image](https://user-images.githubusercontent.com/27544406/83977721-08736e00-a903-11ea-862f-50bba2614341.png)

**How To Reproduce:**
Install WSO2 IS 5.10 (release)
open user portal in Browser (https://localhost:9443/user-portal/login)

**Expected behavior:**
There shoud be a token generated and redirected to https://localhost:9443/authenticationendpoint... (see screenshot Chrome and Firefox)

**Device Information** 
 - Device: PC
 - OS: Windows 10, 1809, 
 - Browser + Version, IE11 x64 or Edge

**Related Issues:**
Windows 10 Users can't login to user portal with pre-installed browsers.

**Comment by brionmario** [comment]
We need to verify if this issue is fixed with https://github.com/wso2/identity-apps/pull/400.

**Comment by svenzimmermann** [comment]
In the productive system an test system with wso2v5.10 we still have v1.0.72. If you send me the jar file and update instructions, can I test it briefly.

**Comment by LahiruLS** [comment]
It is working fine in the latest Microsoft Edge version. 84.0.522.61
![Screenshot from 2020-08-20 18-45-27](https://user-images.githubusercontent.com/19922157/90775062-fb68f700-e315-11ea-97c0-54f0984b5a45.png)
Check the screenshot below,
![Screenshot from 2020-08-20 18-48-12](https://user-images.githubusercontent.com/19922157/90774982-e5f3cd00-e315-11ea-9ebf-1ea93a4e28a5.png)

**Comment by svenzimmermann** [comment]
I know. New Chrome is Cromium based. Thats the reason. 
But most users in the corporate and education environment still use the IE-based Edge.
