### ISSUE TITLE
Cannot remove 'Approve Always' consent given to authorized apps

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#8748]
**Describe the Issue:**
When login to an OIDC/OAuth app, a user can select 'Approve Always' at the consent prompt.

![image](https://user-images.githubusercontent.com/5237653/80119443-5a587280-85a7-11ea-9a3e-c980758db6f1.png)

Once the 'Approve Always' is given, in the subsequent logins the user will not be prompted to give consent for that app.

At the moment there is no way for the user to revoke the consent by himself. 

**How To Reproduce:**
Try OAuth2/OIDC login and Click 'Approve Always' in the consent prompt.

**Expected behavior:**

But a user should be able to revoke this 'Approve Always' consent ideally by visiting the user-portal. In the user portal, he should be able to view the authorized apps and then revoke the approved consents.

**Comment by piraveena** [comment]
We can use the Authorized Apps Rest API and revoke the consent given https://is.docs.wso2.com/en/latest/develop/authorized-apps-v2-rest-api/.

So authorized-apps api can list down (GET) the approved scopes for each authorized application. https://is.docs.wso2.com/en/5.12.0/develop/authorized-apps-v2-rest-api/#/me/listLoggedInUserAuthorizedApps

When you delete the provided authorization using the delete api(DELETE), it will revoke the scopes and tokens issued. We can revoke consents provided for a specifc application or we can revoke for all applications

This needs to be added to MyAccount

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
