### ISSUE TITLE
when minimizing the browser, Selecting the Received &  Ready options is wrong with the system behaviour

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8750]
Affected : wso2is-5.10.0-rc1

**Describe the Issue:**
when minimizing the browser, Selecting the Received &  Ready options is wrong with the system behavior (User-portal > Operations)

Please refer screenshots

![image](https://user-images.githubusercontent.com/39120228/76057074-4bd5dd80-5f9e-11ea-9da4-df07dbd8dead.png)

![image](https://user-images.githubusercontent.com/39120228/76057083-53958200-5f9e-11ea-92e4-df7a58e6bf2c.png)

**Comment by thanujalk** [comment]
This UI component is moved to console with the improvements.
