### ISSUE TITLE
Inconsistent behaviour in change password from user-portal

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8754]
01. Login to user-portal
02. Goto `Change password` view under the `Security` section
03. Provide `Current password`, `New password` and `Confirm password` fields and hit `enter' from the keyboard. Make sure you don't click `submit` button, instead press `Enter` from the keyboard.
04. Following message is displayed.
![change-password-enter](https://user-images.githubusercontent.com/5061791/75775717-8e1dd580-5d78-11ea-8dea-dcfae9db383d.png)

05. Some times it doesn't happen when some other place in the page is clicked and then enter.

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-apps/pull/1250
