### ISSUE TITLE
Failed attempts are not logged in server logs

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8759]
Affected version: wso2is-5.10.0-beta2

**Is your feature request related to a problem**
If a user tries with incorrect credentials or any failed attempt does not log in server logs

**Describe the solution**
All those failed attempts should be logged in server logs

This may help the user to track the number of a failed attempt

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
