### ISSUE TITLE
Phone number field accepts negative number.

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8777]
**Describe the Issue:**
$title.

![Screenshot 2020-02-15 at 15 47 46](https://user-images.githubusercontent.com/11191791/74586131-8933f480-500a-11ea-91c1-16bba0e356d3.png)

**How To Reproduce:**
Add a negative number to phone number and save.

**Expected behavior:**
Shouldn't accept negative numbers as phone numbers.

**Related Issues:**
https://github.com/wso2/identity-apps/issues/437

**Comment by thivi** [comment]
This has been fixed.
![image](https://user-images.githubusercontent.com/20745428/96959965-cef07780-151e-11eb-91b0-675263edaa90.png)
