### ISSUE TITLE
Extra long username will result in page break

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8779]
**Describe the Issue:**
The entire `user-portal` looks as if broken when and extra long user name is present.

![Screenshot 2020-02-15 at 15 40 24](https://user-images.githubusercontent.com/11191791/74586055-9bf9f980-5009-11ea-8992-f5a528eb8766.png)

**How To Reproduce:**
Add an extra long name for the username in `user-portal`

**Expected behavior:**
Should either concatenate the name or disallow to enter long names.

**Comment by thivi** [comment]
The maximum length of the name was restricted with this PR: https://github.com/wso2/identity-apps/pull/1294
