### ISSUE TITLE
The server start up takes around 25min, when 350 XACML policies are being loaded during the initial startup.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8784]
**Describe the issue:**
The server startup takes around 25 minutes when 350 XACML policies are being loaded during the initial startup.

**How to reproduce:**

- Add around 350 XACML policies to the <IS-HOME>/repository/resources/identity/policies/xacml/ directory so that they will be published to the PDP during initial server startup.
- Start the server.

**Expected behavior:**
In IS-5.8.0 the server startup takes around 4min with the same policies.

**Environment information** **:**
 - Product Version: [IS 5.10.0]
 - Database: [Postgres]
 - Userstore: [JDBC]

---

In IS-5.8.0 the following properties in the <IS-HOME>/repository/conf/registry.xml were set to true by default.
```
    <staticConfiguration>
        <versioningProperties>true</versioningProperties>
        <versioningComments>true</versioningComments>
        <versioningTags>true</versioningTags>
        <versioningRatings>true</versioningRatings>
    </staticConfiguration>
```
But in IS-5.10.0, the above properties are set to false to avoid registry buildup related issues. with this set to false in IS-5.10.0, there is an additional delete query executed which gets captured as a slow query.

DELETE FROM REG_RESOURCE_PROPERTY WHERE REG_PROPERTY_ID= ? AND REG_TENANT_ID=?; 

When the above "versioningProperties" is set to true, the server starts up in 5 min.

The startup time of 5min is also too slow and needs to be improved.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
