### ISSUE TITLE
Phone number accepts any number as Phone number

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#8785]
**Describe the bug**
User phone number field accepts any number as a phone number without validation.

**To Reproduce**
1. Go to personal information page.
2. Add a single number as phone number
3. Save the number.

**Expected behavior**
Should validate as a valid number.

**Screenshots**
![Screenshot 2020-02-15 at 14 19 46](https://user-images.githubusercontent.com/11191791/74584995-3d7b4e00-4ffe-11ea-8657-88514156be61.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
