### ISSUE TITLE
MySQL Script creates indexes that are too big 

### ISSUE THREAD

**Issue by NCMEC-daavendasora** [wso2/product-is#8786]
**Describe the issue:**
MySQL SQL script for creating the WSO2_IDENTITY_DB  fails when character set is UTF8.

**How to reproduce:**
1. `mysql --protocol=tcp -u username -p -e "CREATE SCHEMA IDENTITY_DB DEFAULT CHARACTER SET utf8mb4;"`
1. `mysql --protocol=tcp -u username -p -D IDENTITY_DB < dbscripts/identity/mysql.sql`

**Observed behavior:**
`ERROR 1071 (42000) at line 1020: Specified key was too long; max key length is 3072 bytes`

**Expected behavior:**
Script executes successfully

**Environment information:**
 - Product Version: 5.10.0
 - OS: Docker Linux (wso2/wso2is:latest)
 - Database: Docker MySQL 8.0.17-1debian9 (mysql:latest)
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
[product-is 4255](https://github.com/wso2/product-is/issues/4255)
[product-apim 3736](https://github.com/wso2/product-apim/issues/3736)

**Comment by NCMEC-daavendasora** [comment]
Since creating this Issue, I found the following in the setup documentation:
[WSO2 Identity Server supports the following DBMSs](https://is.docs.wso2.com/en/latest/setup/environment-compatibility/#tested-dbmss) which explicitly states that WSO2 Identity Server only supports the `latin1` character set.

Based on it being the documented limitation for MySQL, I don't believe that this can be considered a "Bug".

**Comment by senthalan** [comment]
@NCMEC-daavendasora , As this is a known limitation for MySQL, we can close this.
