### ISSUE TITLE
Cannot associate federated user accounts through user portal

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#8793]
**Describe the bug**
Although the external login section in the user portal is present through the user-portal we cannot add the associate federated user accounts

**To Reproduce**
1. Add a federated IDP
2. Go to https://localhost:9443/user-portal/personal-info
2. Try to associate the federated user account

**Expected behavior**
Federated user account should be able to associate after authenticating with the federated IDP

**Desktop (please complete the following information):**
 - OS: Mac Mojave
 - Browser Chrome

**Comment by thanujalk** [comment]
There should be a way to associate with an authentication flow.

Improvement: There should be a way to identify whether the authenticator can provide a subect.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
