### ISSUE TITLE
User unable to view if user roles that  along with permissions Login, Workflow Management and HumanTask

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8796]
Tested Environments
Identity -app version : 1.0.1-SNAPSHOT
produs-is : wso2is-5.10.0-alpha3
H2 databse, Postgress, MSSQL
User store: read_write_ldap_unique_id and jdbc unique id

**Describe the bug**
User unable to view if user roles that  along with permissions Login, Workflow Management and HumanTask

![image](https://user-images.githubusercontent.com/39120228/73959125-ea830600-492e-11ea-9c56-e7dc945a1c9d.png)

![image](https://user-images.githubusercontent.com/39120228/73959170-fd95d600-492e-11ea-8077-fbab4d7d562b.png)

![image](https://user-images.githubusercontent.com/39120228/73959194-04bce400-492f-11ea-9752-338fcd387977.png)

**To Reproduce**
1. Go to 'management console'
2. Create user
3. Create Role, select permissions Login, Workflow Management, and HumanTask (as above screenshots)
4. Assign the role to the user created.
5.Log into the User portal with the user-created

**Comment by ayshsandu** [comment]
Need to verify this in console app now.

**Comment by ayshsandu** [comment]
Now the workflow management feature is moved to the console app and created the https://github.com/wso2/product-is/issues/10594 to track a similar issue in the console.
