### ISSUE TITLE
Page  will be redirected to an empty Sign In page when click on the Confirm button in the respective Account Confirmation

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8800]
Affected: wso2is-5.10.0-alpha3
Identity app: 0.9.24-SNAPSHOT

**Describe the bug**
When a user is created by the Self Registration via REST API, and click on the Confirm button in the respective Account Confirmation and it will be redirected to an empty Sign In page.
provided ""properties": [{"key":"callback","value": "https://localhost:9443/authenticationendpoint/login.do"}]}" with REST API

**To Reproduce**
1. Hit Self Sign-Up REST API-> Register user
`curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"user": {"username": "kim","realm": "PRIMARY", "password": "Password12!","claims": [{"uri": "http://wso2.org/claims/givenname","value": "kim" },{"uri": "http://wso2.org/claims/emailaddress","value": "kim.anderson@gmail.com"},{"uri": "http://wso2.org/claims/lastname","value": "Anderson"},{"uri": "http://wso2.org/claims/mobile","value": "+947721584558"} ] },"properties": [{"key":"callback","value": "https://localhost:9443/authenticationendpoint/login.do"}]}' "https://localhost:9443/api/identity/user/v1.0/me"`

2. click on the Confirm button in the respective Account Confirmation

Then it will,  navigate to https://localhost:9443/authenticationendpoint/login.do

![image](https://user-images.githubusercontent.com/39120228/73916632-d8c84100-48e3-11ea-99f2-05f0fae8947e.png)

**Comment by NipuniBhagya** [comment]
Related to https://github.com/wso2/product-is/issues/10504

**Comment by ayshsandu** [comment]
Ideally, the `callback` URL should be the client application that the user should be redirected once the confirmation is done. Need to update the document as in #10504.
Ex: 
```
curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{"user": {"username": "kim1","realm": "PRIMARY", "password": "Password12!","claims": [{"uri": "http://wso2.org/claims/givenname","value": "kim" },{"uri": "http://wso2.org/claims/emailaddress","value": "kim.anderson@gmail.com"},{"uri": "http://wso2.org/claims/lastname","value": "Anderson"},{"uri": "http://wso2.org/claims/mobile","value": "+947721584558"} ] },"properties": [{"key":"callback","value": "https://localhost:9443/myaccount"}]}' "https://localhost:9443/api/identity/user/v1.0/me"
```
