### ISSUE TITLE
Empty page - Internet Explorer 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8803]
**Description**
There is an empty page- when trying with access user portal via "Internet Explorer " browser

**Screenshot** 
![image](https://user-images.githubusercontent.com/39120228/69409838-c81a1d00-0d2f-11ea-90f1-4f9656c24991.png)

**Comment by jeradrutnam** [comment]
Not valid anymore. User Portal is renamed as My Account and it is not reproducible now.
