### ISSUE TITLE
User preferences structure for browser persistence needs to be refactored.

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8807]
**Is your feature request related to a problem? Please describe.**
In the current implementation, we are keeping the interface of the user preferences structure in the `wso2is/core` module and it doesn't accept dynamic entries. This results in hardcoding the portal names in the interface which will result in complications if the portal name changes in the future.

And also the current structure persists all the settings under `identityAppsSettings`. And different settings in unrelated portals might conflict.

**Describe the solution you'd like**
Modify the interface to accept a generic portal settings type.

Proposed interface

```ts
export interface StorageIdentityUserPreferencesInterface<T> {
    [ portal: string ]: T
}
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
