### ISSUE TITLE
Add the ability to simply configure user input forms like self-registration

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#8808]
**Describe the Issue:**
It would be great to have a simple way to configure what fields should be displays for user input forms such as the self-registration form. Currently, if we mark a claim as supported by default it will show up in the self-registration form.

**Comment by abhi4u1947** [comment]
Supported by default is getting messy over the time.

1. Configuring it will show fileds in Management Console under user profile but not on admin portals which uses SCIM2 schemas.
2. Configuring it to see more fields which user will fill later but it force all fields to appear on Registration. In 2020, who use so many fields on registration.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
