### ISSUE TITLE
Developer docs on the user portal

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#8810]
In a scenario somebody deploying user portal, it should have what are the possible\recommended modifications can be done on the user portal and how to do those.

For example,
- Customizing theming
- Disable existing component
- Add new component

Persona: App Developer

**Comment by sherenewso2** [comment]
Documented in [1] and [2] 

[1] https://is.docs.wso2.com/en/5.11.0/develop/configure-my-account/
[2] https://is.docs.wso2.com/en/5.11.0/develop/customizing-my-account-ui/
