### ISSUE TITLE
Deployment docs on the user portal 

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#8815]
Need to update on IS deployment docs, how to deploy IS (what are the new deployment options available) with the introduction of the user portal.

Persona: Architect - On deployment patterns and architecture
Persona: Dev-ops - On deployment instructions

**Comment by sherenewso2** [comment]
Add instructions to docs about deploying MyAccount on an external server from here: https://github.com/wso2/identity-apps#deployment

Content for 'deploying in a basic http-server setup' - pending

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
