### ISSUE TITLE
It is better if there is brief summary for each feature

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#8816]
Even the new user, can get a better idea of ​​what each of the features is expected to offer.

Developer-portal > 
1. Add new Application 
2. Select SAML web application and complete application creation
3. Edit application > Access Tab
4. Scroll down > Encryption section 
5. It is better to add a brief description of each feature.

![image](https://user-images.githubusercontent.com/39120228/83243888-2f6fc880-a1bc-11ea-931e-7b801e221ae7.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
