### ISSUE TITLE
Merging SMS OTP, TOTP, Email OTP and X509 Certificate authentication portals with the authentication portal

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8825]
Currently, there are five different authentication portals, viz.:
1. sms-otp-authentication-portal
2. totp-authentication-portal
3. email-otp-authentication-portal
4. x509-certificate-authentication-portal
5. authentication-portal
6. account-recovery-portal

All of these portals can be merged into one. To that end, changes have to be made in both the identity apps and product is. 
In the identity apps, the portals will have to be merged.
In the product is, the URLs of various endpoints should point to the authentication endpoint.

**Comment by abhi4u1947** [comment]
Yes, this will greatly simplify many things like startup performance, duplication, configuration, theming etc.

A must thing for 5.11 and also 5.10 backporting.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
