### ISSUE TITLE
Role Management feature in Console Application needs integration tests.

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#8864]
**Is your feature request related to a problem? Please describe.**
Role management feature in Console application does not have any integration tests.

**Describe the solution you would prefer**
Implement the tests for the necessary integration scenarios.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
