### ISSUE TITLE
Moving the cache classes to a core component

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8871]
**Description**
Currently the base classes for caching are located in the _org.wso2.carbon.identity.application.common_.
- [BaseCache](https://github.com/wso2/carbon-identity-framework/blob/29b18c8fbc5121eae06860c84e9b95a2228b71c4/components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/cache/BaseCache.java#L46) 
- [CacheKey](https://github.com/ivantha/carbon-identity-framework/blob/de510362e3ef42845293e803a0c0060db3fe1864/components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/cache/CacheKey.java#L29)
- [CacheEntry](https://github.com/ivantha/carbon-identity-framework/blob/38208eb81045064c91225d144495a0274a88c90d/components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/cache/CacheEntry.java#L27) 

It is better to move these classes to a core component such as _org.wso2.carbon.identity.core_.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
