### ISSUE TITLE
Allow the Configuration Management API to be called without manually triggering the tenant flow

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8872]
**Description**
As of the current implementation of the Configuration Management API, tenant flow has to be started and ended manually before and after the operation as the API depends on retrieving the tenant from the context. This design could be more error-prone as it can be forgotten to manually start/end the tenant flow. Therefore it would be better to have an API that takes the tenant domain as a parameter and start and end the tenant flow within the API itself.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
