### ISSUE TITLE
Unable to access the Admin Portal from bookmarked URL

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#8874]
**Describe the issue:**
I created a tenant and I bookmarked the authentication endpoint URL of Admin Portal for future works. But when I tried to login again from the bookmarked URL an authentication error is thrown in the UI.

Authentication endpoint URL : /t/tenant-domain/authenticationendpoint/login.do?client_id=ADMIN_PORTAL_tenant-domain&code_challenge=BmB_g8pYcUHLVu4pbEN6xKWieKYC1IKnew4676fy9dI&code_challenge_method=S256&commonAuthCallerPath=%2Ft%2Ftenant-domain%2Foauth2%2Fauthorize&forceAuth=false&passiveAuth=false&redirect_uri=https%3A%2F%2Fdev.io%2Ft%2Ftenant-domain%2Fadmin-portal%2Flogin&response_mode=form_post&response_type=code&scope=SYSTEM+openid&sessionDataKey=9d2a8fc0-9214-4438-9003-4a16a4b57f42&relyingParty=ADMIN_PORTAL_tenant-domain&type=oidc&sp=Admin+Portal&isSaaSApp=false&authenticators=BasicAuthenticator%3ALOCAL

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-M28
 - OS: Mac

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
