### ISSUE TITLE
Remove duplicate .jars from the accountrecoveryendpoint

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8875]
**Describe the issue:**
In IS-5.10.0, `repository/deployment/server/webapps/accountrecoveryendpoint/WEB-INF/lib/` has following .jar files which are also available in `repository/components/plugins` also.

**How to reproduce:**
Open `repository/deployment/server/webapps/accountrecoveryendpoint/WEB-INF/lib/`, you can observe 5.16.73 version of following jars.
 - org.wso2.carbon.identity.mgt.endpoint.util-5.x.x.jar
 - org.wso2.carbon.idp.mgt.stub-5.x.x.jar

Open `repository/deployment/server/webapps/accountrecoveryendpoint/WEB-INF/lib/`, you can observe 5.17.5 version of following jars.
 - org.wso2.carbon.identity.mgt.endpoint.util-5.x.x.jar
 - org.wso2.carbon.idp.mgt.stub-5.x.x.jar

**Expected behavior:**
These .jar files do not need to be available in the reapplication. Dependencies can be resolved from the plugins folder.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
