### ISSUE TITLE
The MaxUserNameListLength Property Is Not Honored - SCIM Groups Endpoint

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#8876]
**Describe the issue:**
All the requests below results in 504 timeout, when we're having a large number of members (Around 50k) in a group as it tries to retrieve all the members of the group at once since it doesn't honor the property MaxUserNameListLength available in the user store configuration.
````
/scim2/Groups/{id_group}
/scim2/Groups
/scim2/Groups/?filter=displayName+Eq+{groupName}
````
This issue occurs in IS 5.9 and it's already fixed in 5.8 and the later versions with the similar git issues mentioned below.

**Related issues:**
#6511
#6573

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
