### ISSUE TITLE
Make Tenant wise email sender configurable for SaaS enabled service providers

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8879]
If email OTP is configured for a SaaS enabled service provider and Tenant wise email senders are configured for tenants. Currently, the SaaS-enabled service provider's tenant email sender is being used for sending mails. 

It would be better to have a configuration to select which email sender needs to be used for sending emails (the service provider's tenant email sender, or the user's tenant email sender) when configuring a SaaS enabled service provider.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
