### ISSUE TITLE
In script based authentication, unable to access claims of the user in step 2 with local claim URIs when we skip the step 1 in the adaptive script

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#8880]
**Describe the issue:**
> In script based authentication, a NPE is thrown when trying to access claims of the user in step 2 with local claim URIs, when we skip the step 1 in the adaptive script.

**How to reproduce:**
1. Configure facebook as federated IDP.
2. Create a sample application and configure script based authentication for the application.
- For step 1 configure identifier-first.
- For step 2 configure facebook as federated IDP.
- Add the following adaptive script.
```
var onLoginRequest = function(context) {
    executeStep(2, {
                authenticationOptions: [{
                    idp: 'facebook'
                }]
            }, {
                onSuccess: function (context) {
                    var user = context.steps[2].subject;
                    Log.info("email : " + user.localClaims['http://wso2.org/claims/emailaddress']);

                }
            });
};
```
3. Add the following claim mapping to facebook IDP.
- email -> http://wso2.org/claims/emailaddress

**Expected behavior:**
> Should return null or the claim related to local claim URI.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
