### ISSUE TITLE
Optimizing the permission tree loading for the first time. 

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#8884]
Currently, when the identity server starts and the user login and the load the permissions for a role it loads the permissions from the database. We have analyzed the correlation log and found that there are nearly 1500 queries running but none of the queries didn't take more than 10ms. However, it is possible to observe a slowness with the number of queries executing. This actually depends on the database performance. We need to investigate for the possibilities for improvements.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
