### ISSUE TITLE
During outbound provisioning user and role not able to sync in another store

### ISSUE THREAD

**Issue by soniavarshney** [wso2/product-is#8885]
Hi Team

I setup two wso2 identity server 5.10. It wso2-is-1 have store1 and another wso2-is-2 have store2. I configured both user store for outbound provisioning. Its working fine. Now when I stop the store2 server and create some users and group in store1 now I up the store2 server but those users and group which i created while store 2 was down not got synced in store2. How we can do ? second thing when any store1's user update his password how it will synced in store 2 server?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
