### ISSUE TITLE
Calling the token endpoint through an LB with two way SSL connection with server returns "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8890]
**Describe the issue:**
Calling the token endpoint through an LB with two way SSL connection with server returns "java.lang.NullPointerException" in the response as shown below.
```
<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat">
    <ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">java.lang.NullPointerException</ns1:faultstring>
</ns1:XMLFault>
```

**How to reproduce:**
Configure LB with IS so that mutual SSL connection will be established. 
Use the authorization code grant to get the code and call the token endpoint.
```
curl --location --request POST 'https://wso2is.net/oauth2/token?code=9a1b78c1-a072-3244-b7af-3af17e2ff969&grant_type=authorization_code&client_id=dTP45AShWByQEx3nsqnf3LW3Bx0a&client_secret=lqj17sSXeh9YrzgJy0uNdBEvBn4a&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug' \
--header 'Content-Type: application/x-www-form-urlencoded'
```

The above issue occurs because the MutualTLSClientAuthenticator configuration is not available in the identity.xml. Once the configuration is added the following error will be observed.

```
{"error_description":"The client MUST NOT use more than one authentication method in each","error":"invalid_request"}
```
To use client id and client secret to call the token endpoint, the MutualTLSClientAuthenticator needs to be disabled in identity.xml. It cannot be configured from the deployment.toml file.

This is already templated but not available in the pack.
https://github.com/wso2/carbon-identity-framework/pull/2336

**Environment information** **:**
 - Product Version: [IS 5.9.0]

**Comment by piraveena** [comment]
We have multiple client authenticators in IS and they enabled by default. According to the spec, A client should not use multiple authenticators to authenticate. Here client secret and certificate are sent in the request. If client secret is used for client authentication with POST request to the token endpoint, then its not required to send the certificate. 

Refer this mail thread "Issue with configuring Identity Server is a OIDC provider"

**Comment by tharakawijekoon** [comment]
To use client id and client secret to call the token endpoint, the MutualTLSClientAuthenticator needs to be disabled in identity.xml. It cannot be configured from the deployment.toml file.

**Comment by vithu30** [comment]
Observed the similar error when configuring IS 5.10.0 as external IdP with API Manager - `The client MUST NOT use more than one authentication method in each`. To resolve that, as mentioned in this issue, the MutualTLSClientAuthenticator needs to be disabled in identity.xml. 

It cannot be disabled as the config is not templated in identity.xml.j2 file in IS 5.10.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
