### ISSUE TITLE
Unable to access custom claims configured for a federated IDP using local claim URIs through an adaptive script

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#8892]
**Describe the issue:**
> When using an OpenID federated IDP, unable to access defined custom user claims through an adaptive script using local claim URIs, 

**How to reproduce:**
1. Configure a federated OpenID IDP. (ie. Can use another instance of WSO2 IS as the federated IDP).
2. Enable **Define Custom Claim Dialect** radio button under **Claim Configuration -> Basic Claim Configuration**.
3. Define a custom claim mapping that is not available in IS OIDC claim dialect. (ex : `abc -> http://wso2.org/claims/department`) (Note : This claim mapping should be available OIDC claim dialect of the federated IDP.)
4. Create a user with a value for the above claim in the federated IDP.
5. Configure a OIDC sample app. (Can use pickup-manager sample app).
6. Configure Local and Outbound Authentication of the sample app. to use the following adaptive script to retrieve and log the user claim value. 
- Configure step 1 federated authenticator as the configured federated IDP in 1.
- Use following script.
```
var onLoginRequest = function(context) {
    executeStep(1, {
                authenticationOptions: [{
                    idp: 'OIDC-WSO2IS'
                }]
            }, {
                onSuccess: function (context) {
                    var user = context.steps[1].subject;
                    Log.info("login success for idp :" + step.idp);
                    Log.info("abc_remote : " + user.remoteClaims['abc']);
                    Log.info("abc_local : " + user.remoteClaims[' http://wso2.org/claims/department']);
                }
            });
};
```
7. Login to the sample app. and view the server logs to check the logged values.
6. You can observe that the remote claim value returned by remote claim URI is present while claim value returned by the local claim URI is null. 

**Expected behavior:**
> Claim value returned by using both remote and local claim URIs should be same.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
