### ISSUE TITLE
Modify the placeholder in email-admin-config.xml file. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#8894]
**Is your suggestion related to an experience ? Please describe.**
Currently uses {{}} as the placeholder for claims in email templates. This conflicts with the helm configurations. Better to use a different type of placeholders.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
