### ISSUE TITLE
SCIM2 Schema Extensions at tenant level

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#8896]
**Is your feature request related to a problem? Please describe.**
Atm SCIM2 Schema extensions are configured in a configuration file that is global to the environment. In a multi-tenanted environment, this needs to be done at the tenant level.

**Comment by AnuradhaSK** [comment]
- [ ] Backend Implementation is done : https://github.com/wso2/product-is/issues/11705
- [ ] UI Implementation

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
