### ISSUE TITLE
Multi attribute login

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#8899]
This feature is to allow users to login with preferred attributes such as email, username, mobile etc. without restricting the login attribute to the username.

Initially, we’ve identified the following authentication types.

1. The user explicitly provides the login attribute.
2. The user does not explicitly provide the login attribute.
3. The user explicitly provides a set of login attributes.

From the above authentication types, we’ve selected the second option assuming that we can support the following requirements.

- Set of allowed login attributes defined at the tenant level
- A user is uniquely identifiable with an individual login attribute

The possible solutions suggested are as follows.

1. Do a user lookup before calling user core APIs to authenticate

- Do a user lookup based on the login identifiers one by one.
- If a user is found for the login identifier, then use authenticate with preferred username API in the user core. ( <login attribute, login identifier, password> )

2. Do a user lookup at with user core APIs passing to all allowed login identifiers
LDAP mobile=? | mail=?
JDBC mobile=? OR mail=? 

- Pass the login attributes, login identifier to user core and find a user (OR lookup).
- Underlying user stores do the search for the user based on multiple attributes.
- Similar to what LDAP multi attribute-based login approach.
- If a user is found proceed with authenticating as the above option.

3. Identify the login attribute before calling the user core APIs based on regex.

- Each login attribute defines a regex that uniquely identifies itself among other allowed attributes.
  - At the authenticator layer, we find the login attribute used by the user based on regex. 
  - Call user core APIs with login attribute, login identifier, password.

**Comment by pulasthi7** [comment]
Based on the discussion with Darshana, Isura, Asela, and SajithE:

Possible affected paths:

- SSO
- Recovery
- Password Grant
- Mgt Console

Possible other approaches other than the ones mentioned in the description:
- Client needs to send the login attribute type as an additional parameter. This may be provided by the user him/her self, or resolved by the client app/login portal. At product, we do the lookup for the username matching that attribute type and value and authenticate the user. This may require major changes when supporting all the affected areas mentioned above.
- Resolve username within an extension - Provide an extension point in the user store manager level which will resolve the user id from the provided username type. This will not require the user/client to send any additional attributes, or will have any major changes at affected areas, but will need user core changes.

Also, we need to consider how these configurations can be exposed tenant-wise.

**Comment by mefarazath** [comment]
@pulasthi7 
Should we consider basic authentication to APIs also as a possible affected path?

**Comment by darshanasbg** [comment]
Need to have a way to system (tenant wise) to indicate qualified attributes for the login identifiers.
Need to have extensions to guarantee the uniqueness of those qualified attributes during updates.

**Comment by AnuradhaSK** [comment]
Reopening the issue since there are unmerged PRs

**Comment by ShanikaWickramasinghe** [comment]
@sumedhe @nilasini We are going to start a testing round for this new feature. I found doc [1] related to this feature. Can you pls double check and confirm whether all the usecases related to this feature are covered in [1]. Is there any thing missing. Could you pls check and confirm as the doc is still in WIP state.

[1]. https://is.docs.wso2.com/en/5.12.0/learn/multi-attribute-login/
