### ISSUE TITLE
Onboard unique userID support

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#8901]
**Description of the Feature**

Username is used as the user identifier within the product, including the codebase and data storage. We need to remove username as the identifier in all places and onboard support for unique userID.
Remove using the username as the identifier in all places, below are some known places.

- OAuth2 token table
- Account associations
- Hybrid roles
- Identity governance data

Below sub tasks were identified so far.

- [x] Add support to authentication framework
- [x] Add support to basic authenticator
- [ ] Use unique userID for the user references in the database tables in carbon-identity-framework
- [ ] Use unique userID from inbound authentication components
- [ ] Allowing login with multiple attributes and allowing to rename the username.
- [ ] Use User UID, for logs, APIs, Apps

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
