### ISSUE TITLE
Skip returning the challenge question recovery option, if the user doesn't have challenge questions answer.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#8905]
Initiate password recovery API returns recovery information for password recovery with challenge questions and password recovery with notifications. If `password recovery with challenge questions` feature is enabled then the response will contain `recoverWithChallengeQuestions` mode. It was observed in the response from this API that `recoverWithChallengeQuestions` mode will be returned even if the user doesn't have challenge questions answer set for the minimum no. of questions required for recovery.

sample curl request:
`curl --location --request POST 'https://localhost:9443/api/users/v1/recovery/password/init' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4='  --data '{"claims": [{"uri": "http://wso2.org/claims/username","value": "dewni"},{ "uri": "http://wso2.org/claims/emailaddress","value": "dewni@gmail.com"} ], "properties": []}' -k -v`

response body (even if the user 'dewni' doesn't have answers set for challenge questions):
`[{"mode":"recoverWithChallengeQuestions","links":[{"rel":"next","href":"/t/carbon.superidentity/recovery/v0.9/security-question?username=dewni","type":"GET"}]}]`

Improvement:
Challenge question recovery option should not be returned in the response if the user doesn't have the minimum no. of challenge questions answer already set.

**Comment by mefarazath** [comment]
@dewniMW What are the pending items to close off the issue?

**Comment by dewniMW** [comment]
All the PRs required for the improvement are merged now. Hence closing the issue
