### ISSUE TITLE
Let users request access to applications discoverable in user portal

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8906]
Even though applications may be discoverable in the app dashboard as authorized, still users may not have access to applications based on runtime authorization engaged by IdP or the application. So, let end users request access for them and applications admins to grant access

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
