### ISSUE TITLE
Theming templates for the WSO2 IS login portal

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#8907]
### Requirement

Currently, WSO2 IS has the capability to theme the user portal using j2 templates, and also user portal has the capability to customize [1].

Even though we have theming in the user-portal, they do not apply to the login portal. Currently, we have [2] to customize the login pages. It would be a good feature to have a template to theme the login portal.

[1] - https://is.docs.wso2.com/en/latest/develop/customizing-user-portal-ui/
[2] - https://is.docs.wso2.com/en/latest/develop/customizing-login-pages-for-service-providers/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
