### ISSUE TITLE
Let an end user to link a federated account from the self care portal

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#8908]
**Is your feature request related to a problem? Please describe.**
From the self-care portal, a user should able to associate a federated user account.

A probable option would be to verify the federated account by triggering an authentication flow

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
