### ISSUE TITLE
SCIM Performance

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#8912]
**Description of the Feature**

- [ ] [Performance Improvement to SCIM Group PATCH operation](https://github.com/wso2/product-is/issues/9120)
- [ ] [Identify the performance bottlenecks](https://github.com/wso2/product-is/issues/9039)
- [ ] Improve the current SCIM performance

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
