### ISSUE TITLE
Let end user to tag applications based on user preference

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8915]
The following APIs should be made available to allow a user to manage their applications in the user-portal.

- [ ] [Make an API available for managing favourite applications in the user-portal](https://github.com/wso2/product-is/issues/8911)
- [ ] [Make an API available for managing application tags](https://github.com/wso2/product-is/issues/8913)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
