### ISSUE TITLE
Git Integration - Templated resource definitions

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8925]
**Problem definition**
Current way of introducing an update in templates (like application templates or IDP templates), or adding a new template to a particular environment is by doing that change manually through the management console or calling the APIs

This is an error prone approach and make the configuration changes propagated through environments.

**Preferred Solution**
Having Identity Server capable of pulling template artifacts through its representation stored in a VCS like Github solve this. This will allow to automate configuration changes automatically propagated through different environments, with correct CI\CD pipelines and test suits in place.

Retrieving the configuration updates can be done with both pull (periodic pulling), and push (with GitHub Webhook) models

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
