### ISSUE TITLE
Run portals as SaaS apps outside the IS server

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#8926]
**Is your feature request related to a problem? Please describe.**
Identity Server runtime and portal applications needs to be scaled in different factors. So portal apps need to be able to host outside the Identity Server distribution.

**Comment by brionmario** [comment]
Duplicate of https://github.com/wso2/product-is/issues/9441.

Fixed with https://github.com/wso2/identity-apps/pull/1188
