### ISSUE TITLE
In depth integration with prioritized application/service providers - phase 1

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8929]
Please see the prioritized SPs below based on https://github.com/wso2/product-is/issues/8928,

- Salesforce - https://github.com/wso2/product-is/issues/10602
- Google Workspace - https://github.com/wso2/product-is/issues/10601
- Office 365 - https://github.com/wso2/product-is/issues/10604
- Zoom
- AWS - https://github.com/wso2/product-is/issues/10605
- Slack
- Github - https://github.com/wso2/product-is/issues/10817
- Dropbox Business  
- Box
- Atlassian cloud

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
