### ISSUE TITLE
Stabilize/Improve mandatory (OOB or otherwise) connectors

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#8930]
**Describe the improvement**

Stabilized or improve the following list of pre prioritized connectors.

**Authentication Options**
- SMS OTP
- Email OTP
- [TOTP](https://github.com/wso2/product-is/issues/11006)
- X509
- DUO
- CAS

**Social Logins**
- Facebook
- Twitter

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
