### ISSUE TITLE
Integration with Key management/rotation solutions

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#8931]
Integration with Key management/rotation solutions
- AWS secret manager
- HashiCorp (Configuration aspect [through secure vault])
- SPIFFE/Istio

The following types of keys should be considered
- File config keys - #9150
- External keys (IDP, Analytics server credentials)
- Internal keys (signing certs, TLS certs)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
