### ISSUE TITLE
Integration with IDV systems

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#8935]
**Describe the improvement**

Integration with IDV systems

- Evident ID - https://github.com/wso2/product-is/issues/10525
- IDEMIA - https://github.com/wso2/product-is/issues/9720
- Socure
- Jumio

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
