### ISSUE TITLE
Integration with IGA vendors

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#8945]
**Describe the improvement**

Integration with IGA vendors

- SailPoint
- Saviynt

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!

**Comment by OussamaNairi** [comment]
Hi team 👋

I’d like to reopen this discussion, as integration with modern IGA (Identity Governance and Administration) vendors is becoming increasingly critical for enterprise IAM ecosystems.

In addition to SailPoint and Saviynt, it would be valuable for WSO2 Identity Server to support integration with other major IGA platforms such as One Identity Manager.

This would enable organizations to:

Centralize identity lifecycle and governance processes (joiner–mover–leaver flows)

Ensure compliance through unified policy enforcement

Automate provisioning/deprovisioning across complex hybrid environments

Given WSO2’s roadmap evolution toward ecosystem expansion (PAM, IGA, Web3 & CMS integrations), such capability would align perfectly with these strategic goals.

Could this enhancement be reconsidered for a future milestone?

Thanks for your great work on continuously improving WSO2 Identity Server! 🙏
