### ISSUE TITLE
Integration with consent and preference managment systems

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8948]
**Describe the improvement**
Integrate with external vendors who support consent and preference mgt systems.

- Consent Systems
- Didomi
- KnowNow Information
- Tealium
- TrustArc
- SAP
- Secure Privacy
- OneTrust

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
