### ISSUE TITLE
Improve prioritized connectors

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8950]
**Describe the improvement**
Based on the identification done at https://github.com/wso2/product-is/issues/8928, improve the connectors set.

**Comment by omindu** [comment]
From https://github.com/wso2/product-is/issues/8928, following connectors can be considered for improvements

| IDP | MFA
| -------------- | :--------- |
| Google | SMS OTP
| Facebook | Email OTP
| Salesforce | TOTP
| LinkedIn | Fido 2.0
| Twitter| DUO

**Comment by omindu** [comment]
Addressed with https://github.com/wso2/product-is/issues/8930
