### ISSUE TITLE
Implementation of missing prioritized connectors

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8952]
Based on https://github.com/wso2/product-is/issues/8928, implement the missing ones.

**Comment by omindu** [comment]
From https://github.com/wso2/product-is/issues/8928, following connectors/templates can be considered for implementation

| IDP | SP
| -------------- | :---------
| Github | Salesforce
| Azure | G Suite
| Apple | Office 365
| | Zoom
| | AWS
| | Slack
| | Github |  
| | Dropbox Business |  
  | Box |  
  | Atlassian cloud |

**Comment by malithie** [comment]
Closing as this is captured in https://github.com/wso2/product-is/issues/8929
