### ISSUE TITLE
Group and roles assign failed

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#8954]
**Describe the issue:**
Fail group and roles assign to user

**How to reproduce:**
1. Login to the admin portal
2.Click create user and while creating add groups, roles
3. finish user creation

**Expected behavior:**
Assign roles and groups to created user

**Actual behavior:**
Once created user "user created successfully" message pop up, but after error message pop up like below and once navigate to the edit user assign roles and groups not display

Request payload:
{"Operations":[{"op":"add","value":{"members":[{"display":"hello","value":"40b361c3-e1e7-4d93-9003-d88c8229e3bc"}]}}],"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"]}

Response:
![Selection_999(870)](https://user-images.githubusercontent.com/39077751/88052267-a2bc0800-cb77-11ea-831b-f172dd264992.png)

![image](https://user-images.githubusercontent.com/39077751/88043649-5f5b9c80-cb6b-11ea-9927-854caf3c97da.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS cloud M28 ]

**Comment by NipuniBhagya** [comment]
Closing this issue since it was fixed with the PR: https://github.com/wso2/identity-apps/pull/1167
