### ISSUE TITLE
SAML Issuer field length not enough 100

### ISSUE THREAD

**Issue by dmxunlimit** [wso2/product-is#8955]
**Describe the issue:**

SAML issuer input field has max limit of 100 [1], which is not enough for some cases. This has to be increesed.

**How to reproduce:**

Used WSO2IS-5.7.0
Create Service Provider
Create SMAL inbound configuration with issuer name lenth longer than 100 characters. 
Input field does not allow to enter more than 100 characters.

**Expected behavior:**

Issuer name can be longer than 100.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.7.0]

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/a00addd7eee04455c73df2117c0347f3306abd3a/components/org.wso2.carbon.identity.sso.saml.ui/src/main/resources/web/sso-saml/add_service_provider.jsp#L773
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
