### ISSUE TITLE
Java Authentication (SAML) SDK

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#8956]
**Problem description**

As of now, Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate JAVA application with IS.

Having an official SDK, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on

1. Selecting and applying best practices on different authentication protocols
2. Selecting correct libraries to implement
3. Make that client-side implementation to integrated with IS

etc.

**Preferred Solution**
Have JAVA SDK, sample, and needed guides for integrating the application with Identity Server.

**Tasks**

- [x] Cleanup identity sso agent library
- [x] Create SAML based SDK

**Comment by darshanasbg** [comment]
Java OIDC SDK and the Tomcat filter is tracked with: https://github.com/wso2/product-is/issues/9671

**Comment by darshanasbg** [comment]
The Tomcat filter that use this Java SAML SDK is tracked with: https://github.com/wso2/product-is/issues/8971

**Comment by ChamathNS** [comment]
Java OIDC SDK/ OIDC Tomcat Agent and the Java SAML SDK/ SAML Tomcat Agent are implemented in the following repositories.

- https://github.com/asgardeo/asgardio-java-oidc-sdk
- https://github.com/asgardeo/asgardio-tomcat-oidc-agent


- https://github.com/asgardeo/asgardio-java-saml-sdk
- https://github.com/asgardeo/asgardio-tomcat-saml-agent
