### ISSUE TITLE
Add unit tests for Console app

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#8959]
**Problem Description**

Currently, we don't have unit test coverage for the `Console` app. 

**Preferred Solution**

Add unit tests coverage. Can use the react-testing library.

**For the first phase, lets give the priority to,**
Effort FE::40
- [ ] User Management
- [ ] Application Management
- [ ] IDP Management 

**During the next phases, the rest of the components will be covered.**

**Comment by darshanasbg** [comment]
For the first phase lets give the priority to,
> user-mgt
> application
> idp
components.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
