### ISSUE TITLE
Increase portal apps loading speed/performance

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#8961]
This is to track performance improvement tasks continuation from the 5.11.0 release

- [ ] Add minimal loading skeleton for the app initial load entry point
- [ ] Externalize theme images
- [ ] Convert possible icons to a font file

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
