### ISSUE TITLE
Change existing custom form elements to Redux forms

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#8965]
**Problem Description**
Since formik library didn't support React Hooks at the beginning of the portal apps development, we have used a custom form library developed by us form elements. But since it is not covering all the required state management aspects and the features its been difficult to manage it on going forward.

**Preferred Solution**
Since we are using Redux in our apps environment now, we can replace this with Redux Forms. Which is more easy to use and have more feature out of the box. So this will reduce overhead of maintaining the custom module.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
