### ISSUE TITLE
Go Authentication (OIDC) SDK for IS

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#8970]
**Problem description**

As of now, Identity Server don't have any client side tools like SDKs or official guides on how to integrate a Go application with IS.

Having an official SDK, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on

1. Selecting and applying best practices on different authentication protocols
2. Selecting correct libraries to implement
3. Make that client-side implementation to be integrated with IS

etc.

**Preferred Solution**
Have Go SDK, sample, and needed guides to integrate the application with Identity Server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
