### ISSUE TITLE
Tomcat Authentication Agent using Java SAML SDK

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#8971]
Create a Tomcat agent(Filter) to use the JAVA SDK to integrate with a Tomcat based web applications to easily secure those applications.

Depends on:  https://github.com/wso2/product-is/issues/8956

Effort BE::34

**Comment by ChamathNS** [comment]
Implemented in https://github.com/asgardeo/asgardio-java-saml-sdk.
