### ISSUE TITLE
OPA support for adaptive authentication

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#8972]
**Additional context**
Integrate OPA support for adaptive authentication scripts.

**Comment by omindu** [comment]
@emswbandara What's the status of this integration ? Are we in a position to close this issue ?

**Comment by emswbandara** [comment]
Yes this can be done using the OPA connector https://store.wso2.com/store/assets/isconnector/details/767617c4-1303-441b-83da-f21fb09a278a
