### ISSUE TITLE
Flutter Authentication (OIDC) SDK for IS

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8974]
**Problem description**

As of now, Identity Server don't have any developer tools like SDKs or official guides on integrating a Flutter application with IS.

Having an official SDK, samples and guides will save a ton of time for the developers and also will help improve DX. These will help the app developer to avoid spending time on:

1. Selecting and applying best practices on different authentication protocols.
2. Choosing the most appropriate libraries for the application.
3. Connecting the application with the IS to configure the authentication flow.

etc.

**Preferred Solution**

Have a Flutter SDK, sample, and needed guides to easily integrate an application with the WSO2 Identity Server.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
