### ISSUE TITLE
Qualify session cookies for tenant path

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#8975]
**Problem**
Since the current commonauthId cookie is not qualified for a tenant path, we cannot log in to two tenants within the same browser.

**Possible Solution**
Qualify session cookies for tenant path

Effort::40

**Comment by pulasthi7** [comment]
Update:

Locally modified the code to set the session cookies in the tenant path with tenant qualified URL enabled and following problems were observed.

* When the apps are hosted in a different domain from IS's domain, the OIDC app keep polling the session state continuously. 
  * The reason for that is, the cookies are not set with samesite attribute. 
  * Added samesite cookie valve configuration manually and still the problem didn't get resolved
  * When further debugging found out that the context rewrite valve is skipping the rest of the filter chain for tenanted URLs, This issue and adding samesite cookie valve by default should be addressed separately
  * As a temp solution, modified the template files to get this working
* When the apps are hosted in same domain as in IS's domain (where samesite restrictions doesn't get affected), only the first login was working fine and the rest of the login attempts kept ending at applicatons' login pages.
  * The reason for this is, the application (which is hosted in HTTP) can't set the jsessionid cookie as it would override the same named cookie set by IS (which is using HTTPS). And hence the application's request to home page can't detect any session attributes resulting in a redirect back to login page.
  * This should get fixed if the app is hosted in HTTPS, as the rest of the flow seem to work without an issue
* Furthermore, for super tenant applications, the cookies needs to be set to the root domain, as the authentication flows work without tenanted URLs. There will be a overlap of matching cookies for tenaned paths (as both "/t/tenant" and "/" will match if there is a ST session and tenant session), but this should not be a problem as the priority is given to the best match

ToDo:
* Setup the proposed approach for SAAS apps and get this working
