### ISSUE TITLE
Product Performance - 5.11.0

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8976]
Get the product performance numbers for IS 5.11.0

Sub Tasks related to this issue: 
- https://github.com/wso2/product-is/issues/9257 
- https://github.com/wso2/product-is/issues/7418
- https://github.com/wso2/product-is/issues/9334 
- https://github.com/wso2/product-is/issues/9139 
- https://github.com/wso2/product-is/issues/9402
- https://github.com/wso2/product-is/issues/8595

**Comment by Buddhimah** [comment]
I have got the performance numbers for IS 5.11 m 32

**Comment by Buddhimah** [comment]
Identified a performance issue and fixed the issue with https://github.com/wso2/carbon-kernel/pull/2752

**Comment by Buddhimah** [comment]
Released kernel with the new performance fix and released the product m34- SNAPSHOT with the fix

**Comment by Buddhimah** [comment]
Currently running performance tests for newly released product

**Comment by Buddhimah** [comment]
Since the performance numbers for 5.11 Released I have started backporting fix https://github.com/wso2/product-is/issues/9334 for this issue to 5.10 Currently this is in staging

**Comment by Buddhimah** [comment]
Sub Tasks related to this issue: https://github.com/wso2/product-is/issues/9257 , https://github.com/wso2/product-is/issues/7418, https://github.com/wso2/product-is/issues/9334, https://github.com/wso2/product-is/issues/9139

**Comment by Buddhimah** [comment]
Outcomes from this task: 

- 5.10 Product Performance numbers should be released.

- After releasing the wum 5.10 WUM performance numbers should be released

- 5.11 Alpha performance numbers should be released

**Comment by pulasthi7** [comment]
Reopening as the above fix addresses only the 5.10.0 numbers
