### ISSUE TITLE
 Support 'Client Initiated Backchannel Authentication' specification

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8977]
Specification:
https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0-ID1.html

The following improvements are pending for the completion of the implementation of the above.

**CIBA grant**
- [ ] https://github.com/wso2/product-is/issues/7022 - Minor improvements to be done
- [ ] https://github.com/wso2/product-is/issues/8471 - Need to override isAuthorizedClient method in ciba and device flow 
response type handlers
- [ ] https://github.com/wso2/product-is/issues/9012 - Sample application

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
