### ISSUE TITLE
Optimize the product for cloud native deployments

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8978]
Need to optimize the product so that it will be cloud native friendly. Following are some of the points we may need to consider and work on.
- Low image size 
- Low startup time 
- Low memory footprint 
- Independently scalable immutable distributions  
- Evaluate the usage of local database (local registry). 
- Reduce tenant memory footprint

The following will be the sub tasks associated with this.
- [ ] Evaluate the required tasks https://github.com/wso2/product-is/issues/9030

**Comment by senthalan** [comment]
This will improve the start-up time and memory footprint 
- [ ] https://github.com/wso2/product-is/issues/6393

**Comment by senthalan** [comment]
Reducing product startup time will be covered with https://github.com/wso2/product-is/issues/11410

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
