### ISSUE TITLE
SSO consent configuration at tenant level

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8980]
**Problem Definition.** 
Currently, we can skip the user consent in SSO flows globally through a configuration file. I

Need to provide,
- Tenant wise consent
- Support app wise consent enable/disable for non oauth (SAML, STS) apps 

Effort BE::15

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
