### ISSUE TITLE
Allow defining tenant UI preferences

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8982]
**Problem Definition** 
The tenant admin should have the capability to define preferences for account management actions such as self signup, password recovery or username recovery.
So that if the tenant admin disables self signup and username recovery, tenant signup and username recovery should be hidden when a user tries to login to the system.

**Tasks**
- Allow tenant admins to defined preferences
- Utilize the preferences to populate the UI

**Comment by IsuraD** [comment]
This will be tracked with https://github.com/wso2/product-is/issues/9717
