### ISSUE TITLE
Provide first class support for multiple callbacks in OAuth

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8983]
**Problem Definition**
As of now, we support a regex as Oauth call back URL. However, this might lead to misconfigurations and hence possible security vulnerabilities. The [OAuth 2.0 Security Best Current Practice](https://tools.ietf.org/html/draft-ietf-oauth-security-topics) also mentions about this in [section 4.1](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-4.1); the usage of regex callback URLs are prohibited due to security reasons. 

**Possible Solution**
Provide first-class support for multiple callback URLs in OAuth and deprecate regex support.

**Comment by senthalan** [comment]
@Ruchira2k is working on it.

**Comment by Ruchira2k** [comment]
The above PRs add provisioning for creating, retrieving and updating OAuth Applications with first-class Mutli-callback URL support. 
* This should complete the basic back-end and DB components related to this issue.
To-Do:
* Update the front end components to provide 1st class support for multiple callback URLs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
