### ISSUE TITLE
Adhere to security best practices related to refresh tokens for public clients

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8985]
**Problem Definition**
According to the OAuth browser-based apps spec[1], we need to take some additional precautions related to refresh tokens in browser-based apps.

>    In particular, authorization servers:
> 
>    o  MUST rotate refresh tokens on each use, in order to be able to
>       detect a stolen refresh token if one is replayed (described in
>       [oauth-security-topics] section 4.12)
> 
>    o  MUST either set a maximum lifetime on refresh tokens OR expire if
>       the refresh token has not been used within some amount of time
> 
>    o  upon issuing a rotated refresh token, MUST NOT extend the lifetime
>       of the new refresh token beyond the lifetime of the initial
>       refresh token if the refresh token has a preestablished expiration
>       time

**Proposed Solution**

- Rotate refresh tokens on each refresh token request (already available feature)
- Expire refresh tokens if they are not used within a specific time interval
- For public clients, do not extend the lifetime of the original refresh token (first refresh token received via login).

[1] https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-06#section-8

**Comment by janakamarasena** [comment]
We need to look at this as well https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16#section-4.13

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
