### ISSUE TITLE
Support Single use access tokens

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8987]

**Comment by piraveena** [comment]
- From the IS side, we can't enforce that this is a one-time token. IS can only indicate it. Only the gateway can enforce it. So it will be a normal token, and enforcement needs to be done at the resource server. 

- But revocation time, the application will send the client-id and client-secret to Gateway and Gateway will use it to revoke the token. But in this usecase, when applications will access some endpoint, gateway can’t get the client-id and client-secret. So GW can’t use the Client-Authentication mechanism at that moment to call the revoke API for Single usage access tokens usecase.

1. Implement a separate authorization level for revocation api to support it. 
2. Authenticate with high-privileged user with some user permission

Issue for a privileged user authenticator  to support revoke api authentication: https://github.com/wso2/product-is/issues/9026
