### ISSUE TITLE
Selectively terminate sessions on password update

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8988]
**Problem description**

When updating passwords using a portal with an existing session avoid terminating the existing logged in sessions but terminate all other sessions

It is required to get the user consent to logout from other applications. (Other devices)

- [x] [Backend Support](https://github.com/wso2/product-is/issues/9461)
- [ ] Change in Portals (Blocked on https://github.com/wso2/product-is/issues/10014)

Effort BE::20

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
