### ISSUE TITLE
 Revoke the latest refresh token when the same refresh token is used twice

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8989]
**Problem Description**
When it comes to SPAs since they are public clients the refresh token requires additional protection from being stolen or misused. Therefore, Authorization server MUST utilize additional mechanisms to detect refresh token replay by malicious actors for public clients:

According to OAuth Security Best Practices Spec[1], it recommends few mechanisms to prevent refresh token replay.

>  Authorization server MUST utilize one of these methods to detect
>    refresh token replay by malicious actors for public clients:
> 
>    *  Sender-constrained refresh tokens: the authorization server
>       cryptographically binds the refresh token to a certain client
>       instance by utilizing [I-D.ietf-oauth-token-binding] or [RFC8705].
> 
>    *  Refresh token rotation: the authorization server issues a new
>       refresh token with every access token refresh response.  The
>       previous refresh token is invalidated but information about the
>       relationship is retained by the authorization server.  If a
>       refresh token is compromised and subsequently used by both the
>       attacker and the legitimate client, one of them will present an
>       invalidated refresh token, which will inform the authorization
>       server of the breach.  The authorization server cannot determine
>       which party submitted the invalid refresh token, but it will
>       revoke the active refresh token.  This stops the attack at the
>       cost of forcing the legitimate client to obtain a fresh
>       authorization grant.

This feature is related to the second mechanism,

> If a refresh token is compromised and subsequently used by both the
>       attacker and the legitimate client, one of them will present an
>       invalidated refresh token, which will inform the authorization
>       server of the breach.  The authorization server cannot determine
>       which party submitted the invalid refresh token, but it will
>       revoke the active refresh token.  This stops the attack at the
>       cost of forcing the legitimate client to obtain a fresh
>       authorization grant.

[1] https://tools.ietf.org/html/draft-ietf-oauth-security-topics-15#section-4.12.2

**Proposed Solution**

- Rotate refresh tokens with each refresh token request
- Maintain a link between previous refresh token and the new refresh token
- If an old/invalidated refresh token is used, then revoke the latest refresh token obtained via the link

**Comment by janakamarasena** [comment]
Better to also consider the refresh token rotation mentioned in [rfc6819](https://datatracker.ietf.org/doc/html/rfc6819#section-5.2.2.3) apart from the above this additionally states
```
in case of such an access
   attempt the valid refresh token and the access authorization
   associated with it are both revoke
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
