### ISSUE TITLE
If PKCE is enabled we can avoid revoking access token when same authorization code is used

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8990]
**Problem Definition**

According to the OAuth2 spec[1], if an invalid authorization code is replayed, then we need to revoke all access tokens issued for that authorization code when possible

> If an authorization code is used more than
>          once, the authorization server MUST deny the request and SHOULD
>          revoke (when possible) all tokens previously issued based on
>          that authorization code.  The authorization code is bound to
>          the client identifier and redirection URI.

This is to avoid authorization code interception attacks at the cost of the legitimate user having to get the access token again by doing an authentication.

With PKCE[2], even if someone intercepts the authorization code, they will not be able to use the code to get an access token unless they are the legitimate user.

However, with the behaviour of revoking access tokens on authorization code reuse as explained above, an attacker could replay intercepted authorization code launch a DDoS (ie. The legitimate user cannot obtain a token or keep using the obtained access token).

**Proposed Solution**

- When PKCE is enabled and mandatory for an application, do not revoke the access tokens for a replayed authorization code.
- We should check the behaviour of how the authorization code will be invalidated if used without PKCE for a PKCE mandatory application (ie. Check whether we simply invalidate authorization code even when the PKCE params are not present, if we do then we need to fix that behaviour to not do that)

[1] https://tools.ietf.org/html/rfc6749#section-4.1.2
[2] https://tools.ietf.org/html/rfc7636

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
