### ISSUE TITLE
Identity runtime and product API seperation

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8991]
**Problem Definition**

Currently, the identity server consists of a single distribution that contains both Product APIs and the core runtime. With the current architecture, it is not possible to scale the runtime component of IS independent of the product APIs.

**Possible Solution**
- Separate the core runtime and product APIs to make it possible to have two distributions and scale each of them independent of the other (mostly we would be scaling the runtime)

This would be the first step to building the core runtime as a separate identity gateway.
Need to analyze the core improvements required to decouple the runtime and product APIs and breakdown the tasks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
