### ISSUE TITLE
Improve logging (audit, activity, transaction, trace, access)

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8992]
**Problem description**

Understand the requirements of each log type and properly categorize types. Currently, supported Audit, debug and access logs. Need to differentiate the above logs types and implement them.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
