### ISSUE TITLE
Let developers decide signup/self services options for their applications

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8993]
- If the self-services are enabled at the tenant level, developer should be able to decide to show self-services options in the application login page. 

Few use cases,
- Allow self signups or not
- Allow recovery options or not

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
