### ISSUE TITLE
Symmetric key rotation

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#8999]
**Problem Definition** 

The product has the facility to encrypt internal data with a symmetric key. Yet, upon a key rotation requirement, there is no straight forward process to follow for key rotation.

**Describe the improvement**
Provide the capability to rotate the symmetric keys. As a data migration is required this will have the same complexity of product version migration.
The migration process may involve,
- A blue-green migration with zero downtime
- Limited management operations allowing only end-user flows

**Comment by DMHP** [comment]
https://github.com/wso2/identity-tools/pull/13
https://github.com/wso2/identity-tools/pull/14

**Comment by DMHP** [comment]
https://github.com/wso2/identity-tools/pull/14 needs to be reviewed and merged.

**Comment by chamathns** [comment]
addressed with https://github.com/wso2/identity-tools/pull/22
