### ISSUE TITLE
Proxy-based federation support with the Gateway (App Gateway)

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9001]
**Problem Definition**

In some scenarios, there can be legacy apps that cannot be modified drastically to talk to the identity server in a standard protocol. These apps usually rely on a proxy layer to do the authentication for them and consume the authenticated users' information via headers or a JWT pushed from the proxy layer.

**Possible Solution**
- Have an App Gateway that can allow legacy apps to be proxied with. 
- This gateway will do the authentication using a standard protocol and pass the consumable information to the application in a header or a JWT.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
