### ISSUE TITLE
Issuing multiple narrowly scoped tokens for a SPA instead of having over-scoped one token

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9007]
**Problem Definition.**
Issuing multiple narrowly scoped tokens for a SPA instead of having over-scoped one token+ need to indroduce the scope collections and allow apps to request set of collections(Ex: application_manage scope collection will have all scopes releated to application management, app will recieve the actual scopes instead of collections) + specially consider the concurrency issues with the refresh_token grant as we have multiple tokens.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
