### ISSUE TITLE
Support using MariaDB driver to connect with AWS Aurora DB

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9010]
- [x]  Driver support https://github.com/wso2/product-is/issues/9700
 - [x] Queries to be updated https://github.com/wso2/product-is/issues/8053

**Comment by pulasthi7** [comment]
The example configurations are available at https://github.com/wso2/product-is/issues/10274

**Comment by gomathyk** [comment]
https://github.com/wso2/docs-is/pull/2358

**Comment by yasirjanjua** [comment]
@ pulasthi7 does wso2 identity server work with AWS Aurora ??
