### ISSUE TITLE
Permission management for resources (api resources, application resources)

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9016]
**SUMMARY**
A permission is defined as a combination of a resource and one of its corresponding actions.
Permissions are a fundamental element of any authorization decision.

In IAM permissions can be used in two types of scenarios:
Authorizing users to application level resources (application bound permissions)
Authorizing users to API resources (API bound permissions)

In IAM, roles are designated to represent collections of permissions, for easier assignment and administration of users.

Traditionally in web applications these two types were clearly distinct. However, with modern applications such as single page applications (SPA), this distinction is blurring. Today the best practices for authorization in SPAs, promote the use of JWT tokens which can contain authorization information of a user, which can be consistently used to authorize a user at the frontend as well as the backend. This makes application development way more standardized and easier.

More specifically OAuth2 protocol defines “scopes” as a way of clients requesting for authorization levels and the OAuth2 authorization server responding with the granted authorization levels. The mapping of scopes to permissions are implementation dependent. For example, the scopes themselves can be considered as permissions. A more scalable way of doing this would be to map scopes to a collection of permissions. Therefore mapping scopes to user roles would also be a good option.

However, if we consider traditional web applications or SAML2 SSO compliant web applications, there is no standard way to include permissions in the responses. Therefore we will need to fall back to the ability to include permissions in the SAML2 response or JWT.

In IAM, groups are defined as a collection of users. Groups are generally managed in the userstore and express the organization structure. Groups are used to make user management easier.

Typically, users or groups can be assigned to roles.

    
**USE CASES**
USE CASE 1: Permission Management for Custom Web Applications
Requirements
 
Permissions need to be expressed as resource + action.
Permissions need to support hierarchy to express hierarchical entitlements.
Permissions need to be grouped as roles for easier administration.
Permissions need to be returned in the authentication response for application side authorization.
Permissions returned to an application must include only permissions for the respective application and not anything else. If not, in case of external applications, this can be considered unnecessary information leakage.
There needs to be an option to send administrative permissions in WSO2 Identity Server, if the application consuming the authentication response is an admin portal that is consuming admin services of WSO2 Identity Server.
Comprehensive permission management Rest API to manage bespoke permissions.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
