### ISSUE TITLE
Improve CLI commands & structure

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#9021]
**Problem description**
Having a CLI to invoke IS product APIs is important for many cases.
- This can be used to generate necessary base artefacts in IS side when a developer generates client side project (app)
- Will be useful for dev-ops experience when resource definitions needed to propagate across environments.

**Preferred Solution**
We have a basic CLI which is capable of generating IS service provider definitions. It better to refactor it to centralize all the commands in one tool and structure them in a proper manner. Define main cli commands thats capable of handling with any product APIs.

**Sub Tasks**
- [ ] create a structure for CLI commands
- [ ] centralize all the CLI commands in tool
- [ ] Document usages and extendability.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
