### ISSUE TITLE
Standardize enterprise User extension schema

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#9022]
**Is your feature request related to a problem? Please describe.**
At the moment, custom/additional user attributes are configured through the Enterprise user schema. But Enterprise user schema is a standard schema and is not supposed to add any custom attributes. For the custom attributes, we need to introduce a separate schema.
- Remove non-standard attributes from enterprise user schema
- Introduce additional user schema for custom attributes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
