### ISSUE TITLE
Atom Plugin support for debug authentication flows

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#9023]
**Problem description**
Atom is one of the vastly used editors among users. Although WSO2 IS have a debugger plugin for authentication flow in VS Code, some of the developers are getting affected by not having plugins for Atom.

**Preferred Solution**
Create an Atom plugin to debug authentication flow with the capabilities of the VS code plugin.

**Sub Tasks**
- [ ] Create Atom plugin
- [ ] Document usages

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
