### ISSUE TITLE
Improve VS Code plugin debugger experience

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#9025]
**Problem definition**

Need to refactor VS Code plugin debugging feature UI, so that it can gives a better experience by giving a detail view of the authentication flow. And change the views dynamically. Further we can improve the UI design a bit that can give a VS Code UI feeling.

And as a part of this improvements Templated resource definitions are introduced in the latest products. Most of the latest flow depends on this templates to initiate. There are efforts to improve the plugins to plugins for each template definition thus plugin UI need to be improved to accommodate them.

**Preferred Solution**
Revamp the UI to support templates in UI.

**Tasks**
- [ ] Identify the templates definitions
- [ ] Revamp the plugin UI

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
