### ISSUE TITLE
REST API for user functionality management

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#9028]
**Is your suggestion related to an experience ? Please describe.**
This is to implement a REST API for User Functionality Management. We implemented a generic UserFunctionalityManager OSGi service[2] to lock and unlock a specific feature.

This API will include the following functions

- lock
- unlock
- getLockStatus 

This has UserId API and Me API

[1]https://github.com/wso2/carbon-identity-framework/pull/2972
[2]https://github.com/wso2-support/carbon-identity-framework/pull/1118

**Comment by mefarazath** [comment]
@piraveena Have we captured the API related information in the docs?
