### ISSUE TITLE
React Native Authentication (OIDC) SDK for IS

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9031]
**Problem description**

As of now, Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate react native application with IS.

Having an official SDKs, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on

1. Selecting and applying best practices on different authentication protocols
2. Selecting correct libraries to implement
3. Make that client-side implementation to integrated with IS

**Preferred Solution**
Have React Native SDK, sample, and needed guides to integrate the application with Identity Server.

Effort FE::119

**Comment by Abira16** [comment]
Assign "Abira16"

**Comment by xavieregrove** [comment]
@Abira16 @ayshsandu @thanujalk 
Let me know if this SDK / Guide for React Native integration is available now.

**Comment by NipuniBhagya** [comment]
Closing this issue as the initial implementation of the React native authentication OIDC SDK is completed (https://github.com/asgardeo/asgardeo-react-native-oidc-sdk)
