### ISSUE TITLE
Python Authentication (OIDC) SDK for IS

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#9033]
**Problem description**

As of now, Identity Server don't have any client side tools like SDKs or official guides on how to integrate a Python application with IS.

Having an official SDK, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on

1. Selecting and applying best practices on different authentication protocols
2. Selecting correct libraries to implement
3. Make that client-side implementation to be integrated with IS

etc.

**Preferred Solution**
Have Python SDK, sample, and needed guides to integrate the application with Identity Server.

**Comment by Sathiyakugan** [comment]
Hi all,  

Please find the relevant details for  implemented python authentication sdk 

**Repo**
https://github.com/asgardeo/asgardeo-auth-python-sdk

**Docs** 
https://github.com/asgardeo/asgardeo-auth-python-sdk/blob/main/README.md

**PyPI Library** 
https://pypi.org/project/asgardeo-auth-python-sdk/
