### ISSUE TITLE
Check for limitations in the compliancy with the SCIM2 specification

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#9038]
At the moment Identity Server supports operations are required for common use cases. However, there can be operations that are still not supported.

This task is to identify the missing capabilities (and if there are inconsistencies from the spec)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
