### ISSUE TITLE
Check for performance bottlenecks in SCIM 2 implementation

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#9039]
We have already identified a [performance bottleneck in the group patch operation](https://github.com/wso2/product-is/issues/9120) and working on fixing it.

Similarly, we need to profile all the operations and identify if there are performance bottlenecks that can be fixed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
