### ISSUE TITLE
Obsolete and Remove Yahoo connector from product

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#9052]
Obsolete and Remove Yahoo connector from product and add it to connector store.

Effort BE::5

**Comment by piraveena** [comment]
We have removed the yahoo connector from IS distribution. Since Yahoo authenticator is an extension of OIDC authenticator, we can use the standard OIDC authenticator.   OIDC authenticator needs to be configured with the relevant endpoints of Yahoo.
