### ISSUE TITLE
Add config to check if Media Service connector is installed.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#9057]
**Description:**
Media Service API is implemented in the connector mode and therefore it will not be shipped with the default product. When the connector is manually installed in the product, there should be a configuration to check if the media service is actually installed before performing operations such as deciding whether to enable/disable profile image uploading in user portal.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
