### ISSUE TITLE
Fix opensaml bundle not resolving issue in the CAS authenticator

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#9061]
### Description
With the commons-codec upgrade https://github.com/wso2/product-is/issues/8042
The opensaml bundle used in CAS authenticator is not getting resolved at the server startup.
This needs to be fixed.

**Comment by IsuraD** [comment]
upgrade the codec version. Didn't observe any issue. 

https://github.com/wso2-extensions/identity-inbound-auth-cas/
