### ISSUE TITLE
Migration impact of OpenSAML 3.0 upgrade

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#9062]
The OpenSAML dependency upgrade might have an impact on custom extensions written related to SAML.

The reason is that we will be removing opensaml2 dependencies from the runtime.

Few examples would be,

- Custom SAML assertion builders
- Authenticators that use opensaml 2 dependencies (like CAS)

Related to https://github.com/wso2/product-is/issues/8557

Task

- [x] [Host the WS-Trust connector to the connector store](https://github.com/wso2/product-is/issues/8597)

- [x] [Update the WS-Trust Documentation](https://github.com/wso2/docs-is/issues/1985)

- [ ] Test passive sts with Office365 
- [ ] Provide guidelines to migrate opensaml 2 based connectors

**Comment by DMHP** [comment]
Updated the doc https://is.docs.wso2.com/en/5.11.0/setup/migrating-what-has-changed/#upgrade-from-opensaml2-to-opensaml3
