### ISSUE TITLE
Document Migration Impact on Tenant Qualify URL feature

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9068]
Migration guide should track the following points relavant to this feature.

- If the tenant qualify URL feature is enabled, the API clients/Applications should be updated to invoke the tenant qualified URLs

- If hostname configured is the proxy host, move it to proxy host config
   Configure ‘localhost’ or server hostname as ‘hostname’

- Account recovery endpoint: identity.server.service.contextURL configuration in the RecoveryEndpointConfig.properties file needs to configure only the server URL without /services part.

- OAuth:Tenant domain of the application will be validated against the tenant domain sent in the path.

- SAML: Tenant domain will be picked from the tenant domain in the path and not from the query param.

- Removal of web context root and alternative solution

- Access to super tenant via /t/carbon.super will be restricted. Clients should be updated to call the server base path instead.

- Callback/Redirect URL of Identity Server (commonauth) configured in third-party entities e.g. IdentityProviders should be updated to tenant qualified format.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
