### ISSUE TITLE
Add unit tests for IdentityProcessor getCallbackPath method

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9070]
We need to handle a few cases here

    tenant qualified mode with absolute callback path

    tenant qualified mode with relative callback path without /t/

    tenant qualified mode with relative callback path with /t/ (already tenant qualified)

    non-tenant qualified mode with absolute callback path

    non-tenant qualified mode with relative callback path without /t/

    non-tenant qualified mode with relative callback path with /t/ (already tenant qualified)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
