### ISSUE TITLE
SMS OTP: Does user provising and authentication can be done with only mobile number and otp

### ISSUE THREAD

**Issue by adityamajeti** [wso2/product-is#9077]
### Description:
    When i configure SMS OTP of WSO2 3.1.0. I'm able to see two steps of authentication like first step with username and password and second step  with OTP.

But I need authentication in one step with otp: 
      List Of APIS required  for Provining
            1) API to Register with mobile number - It will generate OTP.
            2) API to Verify OTP - It will verify the otp,  provide token as response and save the user to user store
     
      List of APIS required for authentication
            1) API to generate OTP - It will take mobile number as input and generates an OTP
            2) API to verify OTP - It will verify otp and provide token as response. 

### Steps to reproduce:
        Followed WSO2 3.1.0 Configuring SMS OTP documentation (https://is.docs.wso2.com/en/latest/learn/configuring-sms-otp/#configuring-backup-codes-for-smsotp)

### Environment details (with versions): 
- OS: Ubuntu 16
- Client: 
- Env (Docker/K8s):

---

**Comment by ruwanta** [comment]
Hi @adityamajeti 
Better to ask this question on APIM slack channel or the APIM developer list, as it is related to API Manager.

However, the theoretical answer is that , SMS OTP or email OTP are second factor. Someone needs to present the first factor, and then the second factor is presented to further safeguard the login process.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
