### ISSUE TITLE
Unable to view profile of PRIMARY users if a secondary userstore is having a connectivity issue

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9080]
**Description**
When we request attributes, it searches through all the user stores with the given user id. If one of the userstores is having some issue, the users on other user stores even won't work. This might be addressed by gracefully handling errors than breaking the full iterative search.

**How to reproduce:**
* Configure primary userstore as database_unique_id and a secondary userstore with read_write_ldap_unique_id
* Shutdown the ldap userstore
* Try to view the user profile of a user on the primary userstore from the management console.
* It will show an error on the UI and carbon logs will show the connectivity error to LDAP.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by somindatommy** [comment]
The same issue is reported in the following.
- https://github.com/wso2/product-is/issues/9907
- https://github.com/wso2/product-is/issues/9522

This issue is resolved by the https://github.com/wso2/carbon-kernel/pull/2812

**Comment by ShanikaWickramasinghe** [comment]
Got the issue reproduced with IS 5.11.0 Beta6 snapshot

**Comment by somindatommy** [comment]
This issue is resolved. Some additional steps for this will reproduce the error. https://github.com/wso2/product-is/issues/10447 is created to track the scenario
