### ISSUE TITLE
OPA integration with WSO2 Identity Server - Phase 2 (building WSO2 Authentication Sequence)

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9093]
**Is your feature request related to a problem? Please describe.**

OPA (Open Policy Agent) is a free, open source, general-purpose policy engine that unifies policy enforcement across the stack. In phase 1 of this project we implemented a WSO2 adaptive authentication script function to invoke OPA and enforce policies during the authentication flow. In phase 2 of this project we will design and implement delegating the entire authentication sequence construction to OPA based on the rules defined.

Deliverables

1. Authentication sequence building module for OPA
2. Unit/Integration Tests
3. Documentation
4. Article/Blogs/Screencasts

Skills Needed

- Java
- OPA knowledge/Rego language (additional)
- Knowledge of cloud native technologies - Kubernetes, docker (additional)

**Describe the solution you would prefer**

**Additional context**
References
[1] https://www.openpolicyagent.org/docs/latest/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
