### ISSUE TITLE
Support for OAuth 2.0 Token Exchange Specification

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9096]
**Is your feature request related to a problem? Please describe.**
This specification defines a protocol for an HTTP- and JSON- based Security Token Service (STS) by defining how to request and obtain security tokens from OAuth 2.0 authorization servers, including security tokens employing impersonation and delegation. We can implement a new token grant type to facilitate delegation and impersonation as new features for Identity Server. 

Deliverables

- WSO2 IS compliance for token exchange Specification
- Unit/Integration Tests
- Documentation
- Article/Blogs/Screencasts

**Describe the solution you would prefer**

**Additional context**
References
[1] https://tools.ietf.org/html/rfc8693

**Comment by ajanthan** [comment]
Any plans to implement it in the future?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
