### ISSUE TITLE
WSO2 IS integration with an Open Source IoT

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9097]
**Is your feature request related to a problem? Please describe.**
This project is to build a real-world IoT device integrated with WSO2 IS for delegated access control using OAuth2. We should decide on a problem to be solved with a IoT solution and choose a open source IoT server(not WSO2 IoT server) or framework to build the device. The proposed device should have some actions and preferably solve a real-world problem. 

Deliverables

1. Select an open source third party IoT Server or Framework
2. Get/Build some real IoT device, have API to do real work (Turn a light off/on)
3. Delegate access with WSO2 IS. OAuth2
4. Documentation
5. Demo
6. Articles

**Describe the solution you would prefer**

**Additional context**
References
[1] https://docs.wso2.com/display/IS570/Delegated+Access+Control
[2] https://tools.ietf.org/html/rfc6749

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
