### ISSUE TITLE
Add workflow management support

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#9099]
**Description**

Currently we don't have a place to manage workflows in the Developer Portal. We need to bring that feature from the carbon console to developer portal in order to take out carbon console dependency.

**Comment by malithie** [comment]
Should think about the approach that we should take related to https://github.com/wso2/product-is/issues/9326 when implementing this

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
