### ISSUE TITLE
Angular Authentication (OIDC) SDK

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#9107]
**Problem description**

As of now, Identity Server doesn't have any client-side tools like SDKs or official guides on how to integrate angular application with IS.

Having an official SDKs, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on

1. Selecting and applying best practices on different authentication protocols
2. Selecting correct libraries to implement
3. Make that client-side implementation to integrated with IS

**Preferred Solution**
Have an Angular SDK, sample, and needed guides to integrate the application with Identity Server.

Effort FE::119

**Comment by JanithGan** [comment]
Assign [JanithGan](https://github.com/JanithGan)

**Comment by thivi** [comment]
The development of the SDK was completed around March and it has been released. The SDK can be found here https://github.com/asgardeo/asgardeo-auth-angular-sdk

**Comment by malithie** [comment]
Can we close this issue now ?
