### ISSUE TITLE
Extend the debugging points of Authentication flow 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#9108]
Currently, there are only a limited amount of debuggable points in the authentication flow (Start and end of the protocol). Adding more debuggable locations such as processes inside the authentication framework would give a developer much more understanding of the flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
