### ISSUE TITLE
Extend the debugging capabilities of authentication flow to other components (Connectors/Extension)

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#9109]
Related to: https://github.com/wso2/product-is/issues/8287

Currently, only the authentication flow is debuggable using the plugins(VS Code). Providing the capability to debug other components like connectors or extensions that are plugged to the identity server will give more flexibility to the developer.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
