### ISSUE TITLE
Support the OAuth2.0 PAR specification

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9110]
**Problem Definition**
Authorization request URLs can become quite large, especially in scenarios requiring fine-grained authorization data. And also sending these through browser redirects has the possibility of confidentiality violations.

**Possible Solution**
The OAuth 2.0 Pushed Authorization Requests(PAR) specification defines the pushed authorization request endpoint, which allows clients to push the payload of an OAuth 2.0 authorization request to the authorization server via a direct request and provides them with a request URI that is used as reference to the data in a subsequent authorization request.
Spec: https://tools.ietf.org/html/draft-ietf-oauth-par

**Comment by chamathns** [comment]
Closing this since the core implementation was delivered with the 6.2-alpha milestone. Improvements will be tracked with https://github.com/wso2/product-is/issues/16013
