### ISSUE TITLE
Support the OAuth2.0 RAR specification

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9111]
**Problem Definition**
According to the RAR spec; the OAuth 2.0 authorization framework [RFC6749] defines the parameter "scope" that allows OAuth clients to specify the requested scope, i.e., the permission, of an access token.  This mechanism is sufficient to implement static scenarios and coarse-grained authorization requests, such as "give me read access to the resource owner's profile" but it is not sufficient to specify fine-grained authorization requirements, such as "please let me make a payment with the amount of 45 Euros" or "please give me read access to folder A and write access to file X".

**Possible Solution**
This OAuth 2.0 Rich Authorization Requests(RAR) introduces a new parameter "authorization_details" that allows clients to specify their fine-grained authorization requirements using the expressiveness of JSON data structures.

Spec: https://tools.ietf.org/html/draft-ietf-oauth-rar

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
