### ISSUE TITLE
Support the OAuth2.0 JAR specification

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9112]
**Problem Definition**
According to the JAR spec; the Authorization Request in OAuth 2.0 [RFC6749] utilizes query parameter serialization and is typically sent through user agents such as web browsers.

While it is easy to implement, the encoding in the URI does not allow application layer security to be used to provide confidentiality and integrity protection.  While TLS is used to offer communication security between the Client and the user-agent as well as the user-agent and the Authorization Server, TLS sessions are terminated in the user-agent.  In addition, TLS sessions may be terminated prematurely at some middlebox (such as a load balancer).

As the result, the Authorization Request of [RFC6749] has shortcomings in that:
- The communication through the user agents are not integrity protected and thus the parameters can be tainted (integrity protection failure)

- The source of the communication is not authenticated (source authentication failure)

- The communication through the user agents can be monitored (containment / confidentiality failure).

**Possible Solution**
This OAuth 2.0 Authorization Framework: JWT Secured Authorization Request(JAR) specification introduces the ability to send request parameters in a JSON Web Token (JWT) instead, which allows the request to be signed with JSON Web Signature (JWS) and encrypted with JSON Web Encryption (JWE) so that the integrity, source authentication and confidentiality property of the Authorization Request is attained. The request can be sent by value or by reference.

Spec: https://tools.ietf.org/html/draft-ietf-oauth-jwsreq

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
