### ISSUE TITLE
JWT access token validation failed when calling userinfo endpoint in cluster environment

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#9116]
**Describe the issue:**

Consider there are two nodes in the cluster as node_1 and node_2. Get a JWT access token from node_1 and try to call the the userinfo endpoint from node_2 with the JWT access token of the node_1. Here an error is prompted mentioning that the token is invalid.

**How to reproduce:**

1. Create a two node cluster (Can be achieved by sharing the databases only) and enable JWT access token issuer.
2. Create a OAuth2 SP and get the JWT token with openID scope.
3. Use that token to call the userinfo endpoint (Same behavior can be observed in introspection).

**Expected behavior:**

Expected behavior is to return the user info when calling the userinfo endpoint.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

 - Product Version: IS 5.5.0
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

A related issue can be found in https://github.com/wso2/product-is/issues/4913

**Notes:**

We can resolve this issue by applying the fix mentioned in https://github.com/wso2/product-is/issues/4913. However there are some caching problems occurred when applying the fix.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
