### ISSUE TITLE
SAML Session index/assertion query gives success even after logout

### ISSUE THREAD

**Issue by rahul123-dotcom** [wso2/product-is#9117]
**SAML Sessinindex/assertion query gives success even after logout:**
Wso2 identity server SAML session index/assertion query woeks even after logout. Because even after logout or session timeout the session index or the record which persisted in the DB won't delete. So, every time if we query for session existance it will check for session as even after session expiry/logout also record is present every time it will give sucess.

**How to reproduce:**
I have followed the following ink for configuring and querying SAML session existance https://is.docs.wso2.com/en/5.11.0/learn/querying-saml-assertions/

**Expected behavior:**
In database even after logout session will be available

**Environment information:** 
 - Product Version: IS 5.8.0, IS 5.10.0
 - OS: Ubuntu16
 - Database: H2, MSSQL
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
