### ISSUE TITLE
Improvements identified for OIDC Frontchannel Logout support 

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#9118]
The following is a list of tasks that need to be completed to implement OIDC Frontchannel logout support in WSO2 IS.

- [ ] Identify latest updates made to the [spec](https://openid.net/specs/openid-connect-frontchannel-1_0.html) in the newest draft.
- [x] Refactor Backchannel logout package to a common logout package for both logouts
- [ ] Implement core logic
- [ ] Update the OAuth SP registration UI
- [ ] Add Frontchannel logout feature to OIDC Discovery
- [ ] Enable frontchannel logout configurations with OIDC DCR
- [ ] Add Frontchannel logout to Application REST API definition
- [ ] Write integration tests
- [x] Add Frontchannel logout to Playground 2 sample app to test functionality
- [ ] Add Frontchannel and Backchannel logout support to Pickup Dispatch sample apps

**Comment by ashendes** [comment]
I am working on this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
