### ISSUE TITLE
Add new Audit Loggers

### ISSUE THREAD

**Issue by Manukam** [wso2/product-is#9119]
Need the following events to be logged in the audit log file.

Feature | Event
-- | --
Login | LoggedIn
Login | Failed Login Attempt
Login | Success Login after failure
Forgot Username | Username recovery
Forgot Password | Password recovery by email
Forgot Password | Password recovery by sms
Forgot Password | Password recovery by security questions
Edit Profile | Change password
Edit Profile | Security Questions - Insert
Edit Profile | Security Questions - Edit
Edit Profile | Preference
Edit Profile | Email Change
Edit Profile | Email change > confirm email
Edit Profile | Phone change
Edit Profile | Phone change -> confirm phone?
Edit Profile | Address change
Signup | Account signup
Signup | Account activation

 - Also the application name (SP name) should be logged along with the events, as appropriate. For example, login event should log SP name as well.

**Comment by vihanga-liyanage** [comment]
We have some new requirements, improvements that are needed to be done.


Unlock | New requirement : Missing audit log | -
-- | -- | --
Password reset | - Missing userstore domain of the user- Data JSON object is invalid, has extra parenthesis- User agent value is wrong. It has to be the browser. | TID: [-1234] [2020-08-21 02:33:34,698] [6bc35b40-be2a-4e79-a28c-7e3ed0fb6711]  INFO {AUDIT_LOG} - Initiator : wso2.system.user@carbon.super \| Action : Password reset \| Target : john \| Data : { {"RemoteAddress":"127.0.0.1","User Agent":"Java/1.8.0_252"} } \| Result : Success
Failed login | - Missing remote IP and user agent (are we expected to get it with context identifier?)- Missing userstore domain of the user | TID: [-1234] [2020-08-21 01:32:43,261] [df27cc3f-dec5-4599-b49b-130fe15388f1]  INFO {AUDIT_LOG} - Initiator : somapala \| Action : Login \| Target : ApplicationAuthenticationFramework \| Data : { "ContextIdentifier" : "885d2aca-bd59-4165-8811-b01f0dd30510","ServiceProviderName" : "test-oauth","RequestType" : "oidc","RelyingParty" : "YooxECZR_PcgJk34xgptnie1eHoa","StepNo" : "1" } \| Result : Failed
Locked | New requirement : Missing audit log | -
Success Login | - Missing remote IP and user agent- what is context identifier in the log?- Missing userstore domain of the user | Initiator : somapala \| Action : Login \| Target : ApplicationAuthenticationFramework \| Data : { "ContextIdentifier" : "75832458-787c-422e-bf78-71e6c5c4436e","AuthenticatedUser" : "somapala","AuthenticatedUserTenantDomain" : "carbon.super","ServiceProviderName" : "test-oauth","RequestType" : "oidc","RelyingParty" : "YooxECZR_PcgJk34xgptnie1eHoa","AuthenticatedIdPs" : "eyJ0eXAiOiJKV1QiLCAiYWxnIjoiSFMyNTYifQ==.eyJpc3MiOiJ3c28yIiwiZXhwIjoxNTk3OTQ1MjQ0Nzg2MzAwMCwiaWF0IjoxNTk3OTQ1MjQ0Nzg2LCJpZHBzIjpbeyJpZHAiOiJMT0NBTCIsImF1dGhlbnRpY2F0b3IiOiJTSFJTU0ZpcnN0VGltZUF1dGhlbnRpY2F0b3IifV19.itgyxUPfUrmRVYmEEt+38LATQF8=" } \| Result : Success
Account_Password_Reset_Request | - Missing userstore domain of the user- Data JSON object is invalid, has extra parenthesis- User agent value is wrong. It has to be the browser.Why cant we get service provider name/client id here? | TID: [-1234] [2020-08-25 03:05:16,851] [50a1474d-d793-497f-8150-af73eea3fb72]  INFO {AUDIT_LOG} - Initiator : wso2.system.user@carbon.super \| Action : Password recovery \| Target : asanka \| Data : { {"RemoteAddress":"127.0.0.1","User Agent":"Java/1.8.0_252","Notification Channel":"EMAIL"} } \| Result : Success
Account_Forgot_Username | Missing promised log | -
