### ISSUE TITLE
Support OpenID RISC Profile for security events

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#9121]
**Problem Statement**

A lot of security events happen at an IDP. For example, 
- a user account being locked
- a user resetting his password
- a user terminating his sessions

There may be interested parties that would like to subscribe to these events and take some action based on the event. Therefore it would be ideal to have a solution, where we can push these events to interested parties.

**Proposed Solution**
[OpenID RISC Profile of IETF Security Events 1.0](https://openid.net/specs/openid-risc-profile-1_0-ID1.html) is an upcoming standard for building an interoperable way to push and receive security events.

There is also [OpenID RISC Event Types 1.0](http://openid.net/specs/openid-risc-event-types-1_0-ID1.html) and [OAuth Event Types 1.0](http://openid.net/specs/oauth-event-types-1_0-ID1.html) spec that provides a standard way to encapsulate the security event information in a standard way.

**References**
https://openid.net/wg/sse/
https://bitbucket.org/openid/risc/src/master/
https://openid.net/2018/07/09/three-risc-implementers-drafts-approved/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
