### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of commons-codec:commons-codec:jar

### ISSUE THREAD

**Issue by Bing-ok** [wso2/product-is#9128]
## Issue description
Hi, there are multiple versions of **_commons-codec:commons-codec_** in **_carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util_**. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only **_commons-codec:commons-codec:1.2_** can be loaded, **_commons-codec:commons-codec:1.10_** will be shadowed.

However, one method defined in shadowed version **_commons-codec:commons-codec:1.10_** is referenced by client project via **_org.wso2.carbon.identity.framework:org.wso2.carbon.identity.core:5.18.34-SNAPSHOT_**, but missing in the actually loaded version **_commons-codec:commons-codec:1.2_**.

For instance, the following missing method(defined in **_commons-codec:commons-codec:1.10_**) is actually referenced by **_carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util_**.

**_Missing method: org.apache.commons.codec.binary.Base64: void init (int)_** is invoked by **_carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util_** via the following path:
<pre><code>
paths------
&lt;org.wso2.carbon.identity.application.authentication.endpoint.util.client.AuthAPIServiceClient: org.wso2.carbon.identity.application.authentication.endpoint.util.client.model.AuthenticationResponse authenticate(java.lang.String,java.lang.Object)&gt; carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util\target\classes
&lt;org.apache.http.impl.client.CloseableHttpClient: org.apache.http.client.methods.CloseableHttpResponse execute(org.apache.http.client.methods.HttpUriRequest)&gt; Repositories\org\wso2\orbit\org\apache\httpcomponents\httpclient\4.3.1.wso2v2\httpclient-4.3.1.wso2v2.jar
&lt;org.apache.http.impl.client.CloseableHttpClient: org.apache.http.client.methods.CloseableHttpResponse execute(org.apache.http.client.methods.HttpUriRequest,org.apache.http.protocol.HttpContext)&gt; Repositories\org\wso2\orbit\org\apache\httpcomponents\httpclient\4.3.1.wso2v2\httpclient-4.3.1.wso2v2.jar
&lt;org.apache.http.impl.client.AbstractHttpClient: org.apache.http.client.methods.CloseableHttpResponse doExecute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)&gt; Repositories\org\wso2\orbit\org\apache\httpcomponents\httpclient\4.3.1.wso2v2\httpclient-4.3.1.wso2v2.jar
&lt;org.apache.http.impl.client.DefaultRequestDirector: org.apache.http.HttpResponse execute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)&gt; Repositories\org\wso2\orbit\org\apache\httpcomponents\httpclient\4.3.1.wso2v2\httpclient-4.3.1.wso2v2.jar
&lt;org.apache.http.impl.auth.BasicScheme: void init ()&gt; Repositories\org\wso2\orbit\org\apache\httpcomponents\httpclient\4.3.1.wso2v2\httpclient-4.3.1.wso2v2.jar
&lt;org.apache.http.impl.auth.BasicScheme: void init (java.nio.charset.Charset)&gt; Repositories\org\wso2\orbit\org\apache\httpcomponents\httpclient\4.3.1.wso2v2\httpclient-4.3.1.wso2v2.jar
&lt;org.apache.commons.codec.binary.Base64: void init (int)&gt;
</code></pre>

## Suggested fixing solutions
1. Declare a direct dependency **_commons-codec:commons-codec:1.10_** in the pom file of **_carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util_** to upgrade version from **_1.2_** to **_1.10_**.
2. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library <b><i>commons-codec:commons-codec</i></b> to be <b><i>1.10</i></b> in carbon-identity-framework-master\components\authentication-framework\org.wso2.carbon.identity.application.authentication.endpoint.util's pom file.
3. Use &lt;exclude&gt; to exclude <b><i>commons-codec:commons-codec:1.2</i></b> from the dependency tree, so that version **_1.10_** will be loaded.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] org.wso2.carbon.identity.framework:org.wso2.carbon.identity.application.authentication.endpoint.util:bundle:5.18.34-SNAPSHOT
[INFO] +- org.wso2.carbon.identity.framework:org.wso2.carbon.identity.core:jar:5.18.34-SNAPSHOT:provided
[INFO] |  \- org.wso2.orbit.org.opensaml:opensaml:jar:3.3.1.wso2v1:provided
[INFO] |     \- <b>(commons-codec:commons-codec:jar:1.10:provided - omitted for conflict with 1.2)</b>
[INFO] \- org.wso2.securevault:org.wso2.securevault:jar:1.1.3:compile
[INFO]    \- <b>commons-codec:commons-codec:jar:1.2:compile</b>
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @wso2-jenkins-bot

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @gayashanbc

**Comment by Bing-ok** [comment]
@gayashanbc Could you please help me review this issue? Thank you very much.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
