### ISSUE TITLE
Using a URL for the federated IDP name breaks the multi-option login page.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9129]
**Describe the issue:**
Using a URL for the federated IDP name breaks the multi-option login page. 

<img width="637" alt="Screenshot 2020-08-04 at 1 00 55 PM" src="https://user-images.githubusercontent.com/47600906/89265799-aa3ce000-d652-11ea-835e-34b5c1c1c78f.png">

**How to reproduce:**

- Configure federated authentication with another IDP, when creating the federated IDP in Identity Server provide a URL as the IDP name. (eg- https://www.idp.com)
- Configure a Service provider and configure the basic authenticator and the federated authenticator in a single step, so the multi-option page would shown to the user.

**Environment information** **:**
 - Product Version: [e.g., IS 5.10.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
