### ISSUE TITLE
Set dynamic Session/Token expiration time from Adaptive Authentication Script

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9130]
**Is your feature request related to a problem? Please describe.**
It is nice to have the ability to set dynamic session timeout and token (Oauth/OIDC) expiration time depending on criteria in the Adaptive Authentication.

Example use case:
 - As an employee, I can access to the service provider for 1h (Session/Token) by default.
 - The timeout has to be extended to 12h if the computer is connected in the internal LAN

A limitation is there when implementing this since grant types like password grant and refresh grant are not evaluating adaptive script.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
