### ISSUE TITLE
Anticlickjacking Support for Multiple Domains

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#9135]
**Is your feature request related to a problem? Please describe.**

 To render authentication endpoint in other websites:

Currently, we can use x-frame-options for a single domain but if we want to allow multiple domains, we can't use x-frame-options since we can't bring all the sites under the same origin, so X-Frame-Options: SAMEORIGIN or ALLOW-FROM don't help here and x-frame-options: ALLOW-FROM is not supported by most of the browsers [1], but this can be resorted by using the CSP: frame-ancestors directive [2]. 

What should be the recommended way to achieve such a requirement? Please let me know your opinion on this.

[1] - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Browser_compatibility
[2] - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

**Describe the solution you would prefer**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
