### ISSUE TITLE
[Developer-portal] IDP creation allows to proceed without JWKS endpoint which is a mandatory filed

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9138]
**Describe the issue:**
In developer portal, IDP creation allows to proceed without JWKS endpoint which is a mandatory filed once you select the JWKS as the IDP certificate type. 

**How to reproduce:**
1. Navigate to the developer portal
2. Click "add new IDP" button
3. In general setting phase select the certificate type as JWKS
4. Click next button

**Expected behavior:**
Error or warning massage  should display to add JWKS endpoint

**Environment information**
- Product Version: [e.g., IS 5.11.0-m29]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by thivi** [comment]
We decided to remove the certificate type part from the wizard. So, this issue is no more relevant. On the edit page, the validation works fine for the JWKS endpoint input field.
