### ISSUE TITLE
Integration with Business messaging platforms

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9144]
Integrate with business messaging platforms such as,

- Slack
- MS Teams
- Cisco Jabber
- Yammer
- SF chatter
- RocketChat
- Google Meet
- Workplace by Facebook

**Comment by Namjoofar** [comment]
Because of my need, I made an implementation in Rocket Chat(5.0.1) so that I can get service to wso2-Identity-Server(5.11.0) as SSO via SAML2.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
