### ISSUE TITLE
Integration with Biometric authentication systems

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#9145]
**Describe the improvement**

Integration with Biometric authentication systems

- Veridium
- Imprivata
- BioID
- Typing DNA (behavioural typing biometrics): https://github.com/wso2/product-is/issues/10179
- BehavioSec

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
