### ISSUE TITLE
k8s CRD for WSO2 IS

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/product-is#9151]
Deploying Identity Server in K8s cluster has multiple steps involved and there are multiple artifacts to be deployed which are involved with multiple resource definitions. For example, the deployment definition, services , ingresses (in case of cloud providers), volumes / mounts and configurations. 

We should be able to write a CRD which provisions all required resources by reading required information from a single k8s artifact definition. 

After creating the product deployment CRD, we can implement CRDs to support IS related configurations such as secondary user store, IdP, SP and connectors.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
