### ISSUE TITLE
Improve existing audit logs with attributes and Add new audit logs for missing events.

### ISSUE THREAD

**Issue by UmenR** [wso2/product-is#9167]
**Is your suggestion related to an experience ? Please describe.**
The current audit log entries do not contain the SP name, IP, and User-agent information.  And for some events, the audit logs do not exist. 

**Describe the improvement**

Following are the list of events that either need new entries(SP name etc) or Events that do not contain entries in the audit log.

Feature | Event
-- | --
Login | LoggedIn
Login | Failed Login Attempt
Login | Success Login after failure
Forgot Username | Username recovery
Forgot Password | Password recovery by email
Forgot Password | Password recovery by sms
Forgot Password | Password recovery by security questions
Edit Profile | Change password
Edit Profile | Security Questions - Insert
Edit Profile | Security Questions - Edit
Edit Profile | Preference
Edit Profile | Email Change
Edit Profile | Email change > confirm email
Edit Profile | Phone change
Edit Profile | Phone change -> confirm phone?
Edit Profile | Address change
Signup | Account signup
Signup | Account activation
Edit Profile | Enable/Disable Account
Edit Profile | Password Reset - request

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
