### ISSUE TITLE
Blank wizard step if a default outbound connector isn't configured

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9172]
**Describe the issue:**
The connector details wizard step appears empty if an outbound connector is not configured as default. 

**How to reproduce:**
1. Create an IDP in console application.
2. In the edit view go to the Outbound Provisioning tab.
3. Add a new connector. (Google)
4. Try to add another new connector (SCIM).
5. Check the second step of the wizard.

<img width="1873" alt="Screen Shot 2020-08-10 at 4 35 57 PM" src="https://user-images.githubusercontent.com/25959096/89776468-99dfa600-db27-11ea-9474-e35484450af2.png">

**Expected behavior:**
Wizard step should not appear blank.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-M30
 - OS: Mac

**Comment by aaujayasena** [comment]
Duplicate with issue, https://github.com/wso2/product-is/issues/9140
