### ISSUE TITLE
Failed login attempts claim gets updated only when account lock is enabled

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#9173]
**Describe the issue:**
Currently, the failed login attempts claim gets updated only if the account lock feature has been enabled. This makes other unrelated features, such as reCaptcha, dependent on the account lock function as they require the failed login attempts claim. 

**Related issues:**
https://github.com/wso2/product-is/issues/8605

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
