### ISSUE TITLE
Issues in Salesforce & SCIM Outbound Connector wizard forms

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9174]
**Describe the issue:**
1. In Salesforce Outbound Connector wizard form,  the **Password** field is not clickable & the input type of the **Client Secret** field has to be `password` rather than `text`.
2. In SCIM Outbound Connector wizard form, **Enable Password Provisioning** field is not clickable.

**How to reproduce:**
1. Create an IDP in console application.
2. In the edit view go to the Outbound Provisioning tab.
3. Click on new connector button.
4. Check the SCIM & Salesforce wizard forms.

<img width="805" alt="Screen Shot 2020-08-10 at 4 37 24 PM" src="https://user-images.githubusercontent.com/25959096/89776589-d90df700-db27-11ea-8607-16a57e48ea77.png">

**Expected behavior:**
The fields should be clickable and if they are intended to be disabled, the UI should give some feedback to the users explaining the reasons. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-M30
 - OS: Mac

**Comment by aaujayasena** [comment]
Duplicated with issue, https://github.com/wso2/product-is/issues/9132
