### ISSUE TITLE
SCIM 2.0 Role API not retrieve the  meta attribute  "resourceType"

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9177]
**Describe the issue:**
when 'GET' and 'POST' methods retrieve the meta attribute "resource type". 
For endpoint "/Users" will set "resourceType" to "User", and "/Groups" will set "resourceType" to "Group". Therefore for Role this should be retried as Role. But this attribute is missing in Role API. 

https://tools.ietf.org/html/rfc7644#section-3.3.1

**How to reproduce:**
Request:

`curl -v -k --user admin:admin --data '{  "schemas": [    "urn:ietf:params:scim:schemas:extension:2.0:Role"  ],  "displayName": "Internal/loginRole7",  "users": [    {      "value": "008bba85-451d-414b-87de-c03b5a1f4217",      "display": "kim"    }  ],  "groups": [    {      "value": "7bac6a86-1f21-4937-9fb1-5be4a93ef469",      "display": "PRIMARY/manager"    }  ],  "permissions": [    "/permission/admin/login"  ]}' --header "Content-Type:application/scim+json" "accept:application/scim+json"  https://localhost:9443/scim2/Roles`

**Expected behavior:**
Retrieve the resource type attribute

```
{
    "meta": {
        "location": "https://localhost:9443/scim2/Roles/2859e51d-7679-478b-9d78-014b4a2e5a17"
    },
    "displayName": "loginRole7",
    "schemas": [
        "urn:ietf:params:scim:schemas:extension:2.0:Role"
    ],
    "id": "2859e51d-7679-478b-9d78-014b4a2e5a17"
}
```

**Environment information** 
 - Product Version: [e.g., IS 5.11.0-M30]

**Comment by AnuradhaSK** [comment]
Metadata such as `created` , `lastModified` also missing.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
