### ISSUE TITLE
Make multiple WSO2 crypto service providers configurable within a product.

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9188]
**Is your suggestion related to an experience ? Please describe.**
In current WSO2 products, you can configure only one WSO2 internal crypto service provider (SymmetricKeyInternalProvider/KeyStorebasedInternalProvider). But, there may be situations where we would want to use symmetric key encryption in some components and keystorebased encryption in some 
components.
We need to provide support for a configuration that would allow such capability
**Describe the improvement**

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
