### ISSUE TITLE
Challenge Question Set gets passed as a query param in forced challenge questions feature

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9189]
Enable forced challenge questions feature in the login, challenge question sets are passed as query params to the add-security-questions.jsp in authentication endpoint. As it is not a best practice to send huge data over query params, the correct approach should be to use APIs to access the relevant information.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
