### ISSUE TITLE
No email field validation at user edit phase

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9191]
**Describe the issue:**
Email input filed is not validate at user edit phase.

**How to reproduce:**
1. Login to the console
2. Navigate to the Admin portal
3. Create user 
4. Navigate to the user edit 
5. Update user profile with invalid email format
6. Click update button

**Expected behavior:**
There should be warning message for invalid invalid email format

**Environment information** 
 - Product Version: [e.g., IS 5.11.0-m31]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by IsuraD** [comment]
This is already fixed in 5.11.0 beta 4.
