### ISSUE TITLE
[DEVELOPER-PORTAL-APPLICATION] The app is allowed to delete even the name of the app that does not match the given application name

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9198]
Affected version : wso2is-5.11.0-m31-SNAPSHOT

1. Create 2 web applications:
EX:
I. SAML 
ii. OIDC

2. Initially delete SAML web application 

3. Now try to delete OIDC application

4. By default model display given application name as previously deleted application name.(**This also we have to fix**)
![image](https://user-images.githubusercontent.com/39120228/90096250-63d13a80-dd50-11ea-83e9-09c677643d2e.png)

5. Then confirm
6. Issue : Even if the two application names do not match, the user can delete the application without any error message.

![image](https://user-images.githubusercontent.com/39120228/90096403-c9bdc200-dd50-11ea-86ad-8d4704cb2edb.png)

**Comment by thivi** [comment]
I am unable to reproduce this issue in the beta2 SNAPSHOT pack. I am closing this issue and if this issue arises again, please reopen it.
