### ISSUE TITLE
Identity claims are missing in the SCIM2 Enterprise User schema for secondary userstore users

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9199]
## How to reproduce:

Set non-identity claim in the enterprise user schema as supported by default(you need to do this to the corresponding local claim)
        I used costCenter and organization.
Set identity claim in the enterprise user schema as supported by default(you need to do this to the corresponding local claim)
        I used verifyEmail and organization.
Create a secondary user store(let's call it SECONDARY)
Create a user in the secondary user store
Add values to the above 2 claims in the secondary userstore user's profile
Now call the following SCIM2 API to filter our user.

curl --location --request GET 'https://localhost:9443/scim2/Users?filter=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User.costCenter+eq+test'
In the response JSON, observe that the identity claim: verifyEmail is missing in the urn:ietf:params:scim:schemas:extension:enterprise:2.0:User sub-section.

What should be there,
...
"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                "verifyEmail": true,
                "costCenter": "test",
            }
...

What comes instead,

 "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
                "costCenter": "test",
            }

Note that this works correctly for a PRIMARY userstore user.

## Cause:

IdentityStoreEventListener is responsible for populating identity claims for the response. It uses the username available in the usernameCacheEntry to identify the user's identity claims [1].

From 5.10.0 onward, we use the IdentityUserNameResolverListener to call old userstore operation methods [2]. Here, the userNamesList is having the correct domain appended usernames.
        List<String> userNamesList = ((AbstractUserStoreManager) userStoreManager).getUserNamesFromUserIDs(userIDs);
But the username available in the userClaimSearchEntries are domain-free.

## Possible Solution:
Update the usernames in userClaimSearchEntries, to be domain aware from IdentityUserNameResolverListener.

[1] https://github.com/wso2-support/identity-governance/blob/support-1.4.1/components/org.wso2.carbon.identity.governance/src/main/java/org/wso2/carbon/identity/governance/listener/IdentityStoreEventListener.java#L466
[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/listener/IdentityUserNameResolverListener.java#L1015

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
