### ISSUE TITLE
[SCIM2] Get Group call fails when the user list of the role is large

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#9201]
### Description
Get Group call fails (timeout) when the user list of the role is large.
Following error can be also observed in the carbon log in IS 5.9.0.

`[2020-08-13 11:36:29,788] []  WARN {org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve} - Thread [https-jsse-nio-9443-exec-4] (id=[{6}]) has been active for [600,906] milliseconds (since [8/13/20 11:26 AM]) to serve the same request for [https://localhost:9443/scim2/Groups/9cb38827-ede0-43c6-9568-98d29071da66] and may be stuck (configured threshold for this StuckThreadDetectionValve is [600] seconds). There is/are [1] thread(s) in total that are monitored by this Valve and may be stuck., tenantDomain=carbon.super java.lang.Throwable`

### Root Cause
The reason is  that after the usernames are taken from carbon kernel via getUserListOfRole(roleName) API, at SCIM level it calls getUserClaimValue for each username to get the respective userId.

### Steps to Reproduce
1. Assign over 1000 users to a role
2. Set the MaxUserLimit property to 1000
3. Call the SCIM2 getGroup API for the respective groupId

### Reproduced IS Versions
- 5.7
- 5.9

### Reproduced User Store
- Active Directory

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
