### ISSUE TITLE
[console- Developer > Application] Receive an error message after completing the web application registration.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9203]
Latest Product IS
Developer > Select Application Type >  General Applications> 
Web application > 
provide Name for application > select protocol > provide Redirect URLs
Click on Register
 The page will navigate to Application Edit page with "Create application successfully"
**But after few second Receive an error message**

![image](https://user-images.githubusercontent.com/39120228/90114715-c2a6ac00-dd70-11ea-8674-e97da625db1c.png)

![image](https://user-images.githubusercontent.com/39120228/90114741-c89c8d00-dd70-11ea-891c-7fb7eb354aa3.png)

**Comment by thivi** [comment]
This is due to an error thrown when requesting OIDC protocol configurations. This seems to have been resolved now. Reopen this issue if you can reproduce this once again.
