### ISSUE TITLE
[Developer> Application] Once the SAML application is created, "OIDC" displays it as the default protocol in the protocol section of the edit.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9206]
1. Navigate to Developer> the create an application > Select Application Type > General Applications > Web application

2. in web application wizard provide necessary details and select **SAML as the protocol** 

![image](https://user-images.githubusercontent.com/39120228/90121779-0a7e0100-dd7a-11ea-8bc0-7aacabd41e72.png)

**3. Then navigate to Edit section > Access Tab**

![image](https://user-images.githubusercontent.com/39120228/90121933-39947280-dd7a-11ea-92f1-6df91a085dfe.png)

**Comment by NipuniBhagya** [comment]
Closing this as this fixed in the latest release.
