### ISSUE TITLE
Identification of primary attribute for SCIM 2.0 multi valued complex attributes

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9208]
In the current design, we do not have a way to store the primary identifier of a complex multi-valued attribute. Also, we have been using the http://wso2.org/claims/emailaddress claim to store simple multi-valued email addresses, as well as complex attributes without a type identifier.

Simple Attributes: ["sathya@wso2.com", "sathya@test.com"]
Complex Attributes: [{"value": "sathya@wso2.com", "primary": true}, {"value": "sathya@test.com", "primary":false}]

Therefore we have decided to continue using http://wso2.org/claims/emailaddress claim to store simple multi-valued attributes.
We will introduce a new claim http://wso2.org/claims/emails.unspecified to store complex email attributes without type identifiers.

The primary flag can be set for complex attributes with type identifier [1] or without type identifier [2].

[1] {"type": "work", "value": "sathya@wso2.com", "primary": true}
[2] {"value": "sathya@wso2.com", "primary": true}

Therefore we need to introduce a new claim e.g. http://wso2.org/claims/emails.primary to store the reference to the primary email address of the user if specified in the request.

When processing the SCIM request and also when generating the SCIM response, SCIMUserManager should be modified to update/read the above additional claims.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
