### ISSUE TITLE
[developer Portal > OIDC SCOPE] unable to add new OIDC Scope

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9209]
1. Navigate Console > Developer Portal > OIDC SCOPES
2. New OIDC SCOPES
3. Provide basic details and attributes
4. Finish

Unable to finish the task and getting an Error message

![image](https://user-images.githubusercontent.com/39120228/90163568-e50de900-ddb3-11ea-95a5-e85965585f8c.png)

![image](https://user-images.githubusercontent.com/39120228/90163658-01118a80-ddb4-11ea-8f7c-36cdbc66fb8c.png)

**Comment by NipuniBhagya** [comment]
Closing this issue as it was fixed with PR: https://github.com/wso2/identity-apps/pull/1171
