### ISSUE TITLE
[Developer-portal- Identity Provider] Unable to add new certificates while creating new Identity provider

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9210]
Description: 
1. Navigate to Console > Developer > Identity Provider >Select Identity Provider Type > Quick start 

2. Try to add a new Identity provider ex: Google
3. Then Identity Provider creation wizard > General Settings > Certificates 
4. select Proivide certifiacte > New Certificate

**Navigate to empty page**

Please refer screenshots: 
![image](https://user-images.githubusercontent.com/39120228/90169442-35894480-ddbc-11ea-9ee6-ce3dacb56ccd.png)

Tested Environment :
Mac OS, firefox  79.0 (64-bit)

**Comment by AnuradhaSK** [comment]
This issue can be reproduced in 5.11.0-alpha3 as well.
