### ISSUE TITLE
OIDC Scopes with no claims added in a particular tenant can be viewed from all tenants.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9212]
**Describe the issue:**
OIDC Scopes with no claims added in a particular tenant can be viewed from all tenants.

**How to reproduce:**
Create new tenant eg- tenant1.com
login to the tenant1.com management console and add OIDC scope with no claim eg scopeone.
Create another new tenant eg- tenant2.com
login to the tenant2.com management console and add OIDC scope with no claim eg scopetwo.
In the list of scopes after the scopetwo is added the scopeone(tenant1.com scope) would also be shown.

**Expected behavior:**
Scopes belonging to a particular tenant should not be shown in other tenants.

**Environment information**  **:**
 - Product Version: [IS 5.7.0]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
