### ISSUE TITLE
Mysql identity DB script issue, Incorrect prefix key

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9235]
**Describe the issue:**
Following error observed at the mysql 5.7 database source scripts

![image](https://user-images.githubusercontent.com/39077751/90375737-fba59000-e092-11ea-923d-411eae347a60.png)

**How to reproduce:**
1. Source mysql identity  script to the database

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11-0-m30]

---

**Comment by Buddhimah** [comment]
Duplicate issue: https://github.com/wso2/product-is/issues/9139
