### ISSUE TITLE
SCIM Performance: Support pagination for SCIM2.0 Groups endpoint.

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9237]
**Is your suggestion related to an experience ? Please describe.**
The SCIM2 Groups endpoint faces performance issues, due to not having pagination support.
Since both Users and Roles(newly introduced for Groups/Roles seperation)already  support pagination, its high time we have the same for Groups endpoint as well.

**Describe the improvement**

**Additional context**

**Comment by ruwanta** [comment]
REST API should not have pagination. It breaks the fundamental of pagination. 
Pagination is not a user friendly too. No human look at the second page of a paginated list.
We need to allow proper and advanced filtering. Also a maximum number limit of the list.

**Comment by sahandilshan** [comment]
https://github.com/wso2-enterprise/asgardeo-product/issues/15447#issuecomment-1451256331

Based on the above comment, we should introduce a way to get group details if an org has more than 100 groups.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
