### ISSUE TITLE
Add support for 'Identity Provider's Issuer Name' IDP configuration in REST API and Portal UI

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9251]
The 'Identity Provider's Issuer Name' in the IDP configuration was introduced in https://github.com/wso2/carbon-identity-framework/pull/3061 to help resolve https://github.com/wso2/product-is/issues/4672 (JWT Bearer Grant is using the IDP name for issuer validation). 
This is an optional property which can be used mentioned the IDP Issuer Name when it is different from the IDP Name. And the jwt-bearer grant type has been modified with https://github.com/wso2-extensions/identity-oauth2-grant-jwt/pull/40 to check for the trusted IDP 1st using this property.

**TODO**
Currently, this attribute is not supported through the Identity Provider Management REST API, we need to add it. And then provide the capability to configure this property through the new portal.

**Comment by Kanapriya** [comment]
Re-open this issue as need to provide this (support for defining IDP Issuer Name) capability to configure this property through the new portal.

**Comment by nilasini** [comment]
@Kanapriya can we close this issue? Anything pending to be done?

**Comment by Kanapriya** [comment]
@nilasini : If we can configure this property through the new portal then we can close this issue. Please refer to this comment [1]

[1] https://github.com/wso2/product-is/issues/9251#issuecomment-891122707

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
