### ISSUE TITLE
Federated IDP Initiated OIDC Back-Channel Logout

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9254]
**Is your feature request related to a problem? Please describe.**

When it comes to OIDC identity federation in Identity Server, WSO2 IS acts as an RP to the federated identity provider. However currently there is no mechanism to terminate the sessions and revoke tokens in WSO2 IS (RP), whenever there is a session update in the federated IDP (OP) side. 

**Describe the solution you would prefer**

The OIDC Back Channel Logout v1.0 spec defines a mechanism for communicating logout requests to all RPs that have established sessions with an OP. This mechanism relies upon direct communication of such requests between OP and RPs — bypassing the User-Agent. It imposes new requirements that RPs have a logout endpoint that is reachable by the OP. This improvement needs to be introduced to our OIDC Federated Authenticator.

**Additional context**

https://openid.net/specs/openid-connect-backchannel-1_0.html
https://ldapwiki.com/wiki/OpenID%20Connect%20Back-Channel%20Logout

**Comment by ThaminduR** [comment]
- **WSO2 IS is currently supporting only the RP initiated logout. Following diagram shows the existing logout flow.**
![RP Initiated Logout Flow](https://user-images.githubusercontent.com/45028707/99217703-bc581e00-27fe-11eb-9594-d25fa4f9b5c1.png)

- **In order to achieve the Federated Identity Provider initiated logout, following flow is suggested.**
![Federated IdP initiated Logout Flow](https://user-images.githubusercontent.com/45028707/99217531-36d46e00-27fe-11eb-8d4e-32f155c202a7.jpg)

**Comment by piraveena** [comment]
The tasks of this project can be divided as follows:
- [ ] Verify back-channel logout flow in WSO2 Identity server and check the flow against the back-channel logout specs. Fix the bugs
- [ ] Add the session mapping to sid claim from the id_tokn and persist that in a store
- [ ] validate the back-channel logout token in the outbound component
- [ ] Do the session termination using the sid claim from the logout token
- [ ] Unit tests for the component
- [ ] Integration test for the flow
- [ ] Documentation

**Comment by ThaminduR** [comment]
>     * [ ]  Add the session mapping to sid claim from the id_token and persist that in a store 

Git Issue - https://github.com/wso2/product-is/issues/10714

**Comment by ThaminduR** [comment]
> Back-channel logout token validation in the outbound component

Git Issue - https://github.com/wso2/product-is/issues/10726

**Comment by piraveena** [comment]
- [ ] Implementation
- [ ] [Integration test](https://github.com/wso2/product-is/pull/11553)
- [ ] [ Doc](https://github.com/wso2/docs-is/pull/2502)
