### ISSUE TITLE
Issue in database scripts for the table IDN_REMOTE_FETCH_REVISIONS

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9257]
**Describe the issue:**

When creating the latest db scripts in IS - 5.11 -  IDN_REMOTE_FETCH_REVISIONS table creation fails due to the following error

`Error Code: 1067. Invalid default value for 'LAST_SYNC_TIME'`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS - 5.11 m 31]
 - Database: [MySQL 5.7]

**Comment by Thumimku** [comment]
Can we try and replace 
`	DEPLOYED_DATE TIMESTAMP,`
	`LAST_SYNC_TIME TIMESTAMP,`

with

`	DEPLOYED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`
	`LAST_SYNC_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`
