### ISSUE TITLE
Error due to specified key is was too long on Mysql DB scripts 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9258]
**Describe the issue:**
Issue : specified key is was too long  observed at following tables at Mysql DB scripts.

Error occurred during SQL script execution
Reason:
SQL Error [1071] [42000]: Specified key was too long; max key length is 3072 bytes

Affected DB script and query

**DB script: Identity db script**
**Query:**
1. 
```
CREATE TABLE IF NOT EXISTS IDN_PASSWORD_HISTORY_DATA (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_NAME   VARCHAR(255) NOT NULL,
  USER_DOMAIN VARCHAR(127) NOT NULL,
  TENANT_ID   INTEGER DEFAULT -1,
  SALT_VALUE  VARCHAR(255),
  HASH        VARCHAR(255) NOT NULL,
  TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID),
  UNIQUE (USER_NAME,USER_DOMAIN,TENANT_ID,SALT_VALUE,HASH)
)ENGINE INNODB;
```
2.
```
CREATE TABLE IF NOT EXISTS IDN_CORS_ORIGIN (
    ID                INT           NOT NULL AUTO_INCREMENT,
    TENANT_ID         INT           NOT NULL,
    ORIGIN            VARCHAR(2048) NOT NULL,
    UUID              CHAR(36)      NOT NULL,

    PRIMARY KEY (ID),
    UNIQUE (TENANT_ID, ORIGIN),
    UNIQUE (UUID)
) ENGINE INNODB;
```
3. 
```
CREATE INDEX IDX_AT_AT ON IDN_OAUTH2_ACCESS_TOKEN(ACCESS_TOKEN);
CREATE INDEX IDX_AT_RTH ON IDN_OAUTH2_ACCESS_TOKEN(REFRESH_TOKEN_HASH);
CREATE INDEX IDX_AC_AC_CKID ON IDN_OAUTH2_AUTHORIZATION_CODE(AUTHORIZATION_CODE, CONSUMER_KEY_ID);

```

**DB script : uma
query:**
1.
 `CREATE INDEX IDX_USER_RID ON IDN_UMA_RESOURCE (RESOURCE_ID, RESOURCE_OWNER_NAME, USER_DOMAIN, CLIENT_ID);
`

**How to reproduce:**
1. Configure Mysql 8
2. Source data scripts to mysql 8 database

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0-m32-snapshot]
 - Database: [e.g., MySQL 8]

**Related issues:**
https://github.com/wso2/product-is/issues/9139

**Comment by Buddhimah** [comment]
Have you tried using character set latin1;

**Comment by aaujayasena** [comment]
Yes This isue resolve with using character set latin1. Therefor close the issue.

**Comment by vfraga** [comment]
Setting the charset to `latin1` is not a solution, but a workaround. Some use cases might require to use Unicode characters outside the 256 available in ISO-8859-1, such as multi-attribute values separated by a Unicode character.
