### ISSUE TITLE
Hierarchical organization management support

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#9263]
**Problem**
WSO2 currently support tenancy model, which provides full virtual isolation of data among different tenants. There is no any relationship between these tenants. However, some use cases require to have further division of organizations within a tenant. These organizations may share a relationship between one another. Then the users will be created within these organizations.

**Solution**

1. Will only be supported for LDAP based user stores.
2. REST APIs to manage an organization(metadata) model in the Identity Server.
3. Each organization may have one parent and multiple child organizations.
4. each organization may have their own sub context under the base LDAP directory.
5. ROOT organization represents the base directory of the LDAP.
6. Users will be provisioned into the respective LDAP DN as per their organization.

**Comment by dmxunlimit** [comment]
This feature has to improve the support for JDBC as well and the organizations support within the tenants.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
