### ISSUE TITLE
Provide OOTB support to  assign default roles during JIT provissioning

### ISSUE THREAD

**Issue by GDRDABARERA** [wso2/product-is#9268]
During JIT provisioning we can only assign roles to provisioned user is by role mapping: Federated to internal role mapping

But in a situation where IDPs not sending roles from their side, we have no way to map our internal roles and assign those roles to the provisioned user.

Eg: When JIT provision a user from Facebook there is no way to assign a default role to the provisioned user.

So better to give this support as a OOTB feature to the product.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
