### ISSUE TITLE
SCIM 2 role API patch fail at remove operation

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#9283]
**Describe the issue:**
When try to delete one user or one role all groups or users were removed.

Response:

**How to reproduce:**
1. Create users
2. create groups
3. Create role with assign groups and roles
4. Remove a group or a users using scim2 'PATCH' method

**Expected behavior:**
Only the added user or group from the ID should remove from the role

**Environment information** 
 - Product Version: [e.g., IS 5.11.0-m32]

**Comment by ashensw** [comment]
@aaujayasena 
This issue is not reproducible in the IS 5.11.0-m35. Tried with the below request for both users and groups.

`PATCH https://localhost:9443/t/{{tenant-domain}}/scim2/Roles/:id
`
```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "remove",
      "path":"groups[value eq \"2a81cacd-200e-40c4-ba22-4475c2173fd0\"]"
    }
  ]
}
```

```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "remove",
      "path":"users[value eq \"76d5909d-195d-4653-bf75-3611bfd0366b\"]"
    }
  ]
}
```
