### ISSUE TITLE
When workflows are enabled and users are added to secondary userstores, unable to access the user-portal properly.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9297]
**Describe the issue:**
$Subject 

**How to reproduce:**
Steps to reproduce:
- Create a WF for add user
- Enable self-sign up for the tenant
- configure a secondary user store
- self sign-up via login page to a secondary userstore (ex: <secondary>/testUsername)
- approve the workflow
- Click the confirmation
- now login to user portal as the new user
- although the user is able to log in, non of the functions works for the user
- the following error get appeared in the portal
![image](https://user-images.githubusercontent.com/5061791/91150621-439f6500-e6da-11ea-9a4b-decdc3a191a7.png)

**Expected behaviour:**
User should be able to access portal functions.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0-Snapshot]
 - OS: [e.g.,  Mac]
 - Database: [e.g., MySQL]
 - Userstore: [e.g., JDBC]
- Testing migration

---

**Comment by ayshsandu** [comment]
https://github.com/wso2/product-is/issues/9157 could be the reason. The [fix](https://github.com/wso2/carbon-kernel/pull/2749) is merged to the carbon-kernel, but not yet incorporated in the product-is.

**Comment by NipuniBhagya** [comment]
Closing this issue as we have moved the workflow approvals feature to the console @ayshsandu.
