### ISSUE TITLE
Allows origins cannot be set for an application at the time of the creation

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#9302]
**Describe the issue:**
Currently, the application-wise CORS origins are managed by, GET, PUT and DELETE REST API endpoints in the Inbound Protocols - OAuth / OIDC. However, the CORS origins must be allowed to be added at the time of the application creation through _[POST] /applications_.

**References:**
https://github.com/wso2/product-is/issues/8337

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
