### ISSUE TITLE
Receiving an empty page while trying to move to Roles tab in user Edit section

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9311]
**Describe the issue:**
While a user creates without a role in the initial stage(user creation), then in the edit section trying to add a role for the created user. But   Receiving an empty page when clicking on the Roles tab in the user Edit section

**How to reproduce:**
Login /console/manage/users
2.Create a new user without adding a role
3. Move Edit, then click on Roles tab 

**Environment information**  **:**
 - Product Version: [ IS 5.11 m33 ]
 - OS: [Mac]
 - Database: [H2 & Postgre]
 - Userstore: [ LDAP, JDBC]
- Browser: Firefox

![image](https://user-images.githubusercontent.com/39120228/91276292-f46f3800-e79e-11ea-9818-5628a4cb9465.png)

**Comment by NipuniBhagya** [comment]
Closing this issue as this was fixed with the PR: https://github.com/wso2/identity-apps/pull/1167
