### ISSUE TITLE
Support for revoking access tokens bound to a session expired due to idle time out

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#9312]
**Is your suggestion related to an experience? Please describe.**
With the solution in https://github.com/wso2/product-is/issues/8569, the access tokens bound to the session can be revoked after the user is logged out. But when the user tries to SSO, log in again or log out after a session expires due to a session idle timeout, then we don't have a way to revoke the tokens issued for the expired session. 

**Describe the improvement**
When we get the session from the SessionCache[1], we can fire a SESSION_EXPIRE event if an expired session is found. So whenever the session expiry is detected by the server, we can revoke the tokens bound to that session.

**Tasks**
- Introduce a new event called SESSION_EXPIRE and fire this event when a timed-out session is found.
- Subscribe the `TokenBindingExpiryEventHandler` event handler to the SESSION_EXPIRE event, so that when a SESSION_EXPIRE event is fired it will revoke the tokens bound to that expired session.

[1] https://github.com/wso2/carbon-identity-framework/blob/2e71d8231cefcb21f2a30b8bba5e57775f3dd4d3/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/cache/SessionContextCache.java#L95

**Comment by mefarazath** [comment]
@sachiniWettasinghe Will this have any doc impact? ie. any information that needs to go to docs?
