### ISSUE TITLE
Group name is missing in "Create Group" wizard >  Summary section

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9314]
**Describe the issue:**
After providing necessary information, in the Group creation process, the Group name does not display in the summary section in the Group creation wizard.

**How to reproduce:**
Login to console and select mange 
2. Click on Group in the side menu
3. Provide necessary inputs

![image](https://user-images.githubusercontent.com/39120228/91293694-07413700-e7b6-11ea-8fdc-f44c71f138e7.png)

**Environment information** 
 - Product Version:5.11 .0m33]
 - OS: [Mac]
 - Database: [Postgres, H2]
 - Userstore: [LDAP, JDBC]
-Browser: Firefox

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
