### ISSUE TITLE
Unable to add a Role for a Group

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9315]
**Describe the issue:**
1. Trying to add a role for the **created group**, via console, if it displays update successfully message, but does not assign the selected role to the specific group.

2. The same issue does not assign the selected role to the specific group while **group creation.**

**How to reproduce:**
1. Login to console > Manage
2. Click on Group in the side menu
3. Provide necessary details and  Assign Roles in group creation wizard.
Finish

Issue 1: 
The added role does not assign while group creation 
Issue 2:
Trying to add role in group edit section, even successfully messaged displayed, it does not assign.

**Environment information** 
 - Product Version: 5.11 m33
 - OS: Mac
 - Database: Postgres, H2
 - Userstore: LDAP, JDBC]

![image](https://user-images.githubusercontent.com/39120228/91296714-aff19580-e7ba-11ea-8e49-3f5e1c37f61f.png)

**Comment by NipuniBhagya** [comment]
Closing this issue as this was fixed with the PR: https://github.com/wso2/identity-apps/pull/1167
