### ISSUE TITLE
Add a DAO layer implementation to retrive user name for a user from UM_USER_ATTRIBUTE table without using LIKE operator

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9323]
**Describe the issue:**

Currently, to retrieve  the user name from UM_USER_ATTRIBUTE table we consider user-id as an attribute and use the `LIKE` operator from the query to get the value. But in the unique id case this is not nessary we can have a DAO implementation without the 'LIKE` keyword to get the USER NAME from USER ID from same table. SInce this `LIKE` operation is costly in performance this needs to be changed in the future.

```
"SELECT DISTINCT UM_USER.UM_USER_ID FROM UM_USER, "
            + "UM_USER_ATTRIBUTE WHERE UM_USER_ATTRIBUTE.UM_USER_ID = UM_USER.UM_ID AND UM_USER_ATTRIBUTE.UM_ATTR_NAME =? " +
            "AND UM_USER_ATTRIBUTE.UM_ATTR_VALUE LIKE ? AND UM_USER_ATTRIBUTE.UM_PROFILE_ID=? " +
            "AND UM_USER_ATTRIBUTE.UM_TENANT_ID=? AND UM_USER.UM_TENANT_ID=?";
```

https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCRealmConstants.java#L279
https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L2256

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
