### ISSUE TITLE
Push Notification Based Authenticator

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9325]
Implement an authenticator which can be used as a second factor verification method based on a push notification sent to user's mobile device

Flow would be,

- User register his/her mobile phone
- When authenticating, user provide username (and password) as the initial step
- At that point user receives a push notification to the mobile to verify
- User authorize the request at mobile
- User is authenticated to the app

**Comment by jvkassi** [comment]
Hello,

This is killer feature we need.
We are currently using DUO. Is it possible to implement this q1 of January ?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
