### ISSUE TITLE
Sign in button in self signup page redirects to an invalid URL

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9328]
**Describe the issue:**
Since User Portal has been replaced [1] , the **Sign In** button in self signup page redirects to the old `/user-portal` path resulting in a broken page.

**How to reproduce:**
1. Click on `Create Account` button in `authenticationendpoint`.
2. Give a username and press "Proceed to Self Register".
3. At the bottom of the Create New Account form, click on the **Sign in** button.
4. Observe the broken page.

<img width="1907" alt="Screen Shot 2020-08-27 at 6 51 32 PM" src="https://user-images.githubusercontent.com/25959096/91448108-19df6d00-e897-11ea-87c4-38114cefeb1a.png">

<img width="1914" alt="Screen Shot 2020-08-27 at 6 57 15 PM" src="https://user-images.githubusercontent.com/25959096/91448210-38456880-e897-11ea-8274-38b57efecc13.png">

`
**Expected behavior:**
Users should be navigated to "My Account" portal.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: S 5.11.0 M33
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

[1] https://github.com/wso2/identity-apps/pull/1155

**Comment by IsuraD** [comment]
Users will be redirected to user-portal URL once the recovery flows are done. Ideally it should be myaccount. This heppes due to accountrecovery portal contains the old org.wso2.carbon.identity.mgt.endpoint.util jar file

**Comment by pulasthi7** [comment]
@brionmario 
Framework version was updated in Identity apps. Please check if this can be closed?

**Comment by brionmario** [comment]
> @brionmario
> Framework version was updated in Identity apps. Please check if this can be closed?

Tested the latest IS pack(5.11.0-alpha4) with `identity-apps` `v1.0.444` and the issues seems to be resolved. Hence we can close this issue.
