### ISSUE TITLE
MyAccount and Console is not accessible for tenant users in a migrated setup

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9337]
**Describe the issue:**
$SUbject is observed after migrating from 5.10.0 to 5.11.0

**How to reproduce:**
1. Create an IS-5.10.0 deployment
2. Create a tenant `abc.com`
3. Migrate the deployment to IS-5.11.0
4. Access below URLs and attached error pages are observers correspondingly
      - https://localhost:9443/t/abc.com/myaccount
![image](https://user-images.githubusercontent.com/5061791/91554038-f9251f00-e94b-11ea-89c6-91ef083f5d4a.png)

      - https://localhost:9443/t/abc.com/console
![image](https://user-images.githubusercontent.com/5061791/91554160-35587f80-e94c-11ea-8d15-6e704093e425.png)

**Expected behavior:**
- Users should be able to access these portals with their current credentials.
- Migration should populate the necessary application data

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.10.0 to IS 5.11.0]
 - OS: [Mac]
 - Database: [MySQL]
 - Userstore: [LDAP, JDBC]

---

### Optional Fields

**Notes:**
- For newly created tenants in the setup, users are able to access portals without any issue.
- Super tenant users are able to access the portal without an issue

**Comment by pamodaaw** [comment]
This fixed with the improvement in the migration client from PR, https://github.com/wso2-extensions/identity-migration-resources/pull/142
