### ISSUE TITLE
Improve claim handling in askPassword and verifyEmail flows in UserEmailVerificationHandler

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9356]
**Is your suggestion related to an experience ? Please describe.**
In the [UserEmailVerificationHandler.java](https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/UserEmailVerificationHandler.java#L113:L125)checks that identity/verifyEmail claim is present as condition for enabling or not AccountConfirmation notification, regardless of claim's value.

**Describe the improvement**

1. Check for the actual claim values
2. Provide UI level restriction to enable only one feature
3. Improve the [code block](https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/UserEmailVerificationHandler.java#L113:L125)checks that identity/verifyEmail claim is present as condition for enabling or not AccountConfirmation notification, regardless of claim's value.

**Additional context**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
