### ISSUE TITLE
SCIM create request without username returns invalid status code

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9361]
**Describe the issue:**
SCIM Create User return Internal Server Error (500) for Empty username

**How to reproduce:**
Invoke SCIM create request without specifying a value for the username. Identity Server returns 500 Internal Server error.

**Expected behavior:**
It should return 400 Bad Request status code

**Comment by LahiruLS** [comment]
We need to improve the response when the case of an empty username.
Currently below is returned,
{ "schemas": ["urn:ietf:params:scim:api:messages:2.0:Error"], "detail": "Error in adding the user:  to the user store. ", "status": "400" }
