### ISSUE TITLE
Mounting configuration in registry.xml causes slowness in XACML policy loading from filesystem when the number of policies is high.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9371]
**Describe the issue:**
In the XACML code there are places where the entire resource collections(PAP and PDP) are retrieved from the registry when adding a single policy from the filesystem. (this is ok if the registry is not mounted its only a single JDBC call).

However if the registry is mounted, when retrieving these collections, the mounting handler, after getting the collection checks whether each resource in the collection exists in the registry[1]. a single resource exists check takes two additional JDBC calls.

When policies are added, they are added to both PAP and PDP collections. With the build up of policies in these collections, retrieving the collections to add a new policy triggers the individual resource checks for already existing resources in the collections.

For example if there are 500 policies already added to the PAP and PDP collections. 

loading the 501st policy would trigger, resource checks on the existing resources in the collections which is 2 x 500 jdbc calls for loading collection PAP + 2 x 500 jdbc calls for loading collection PDP = 1000 jdbc calls

loading 502nd policy - 2 x 501 + 2 x 501 = 1004 jdbc calls

loading 503rd polcy -  1008 jdbc calls

loading nth policy - 4(n-1) jdbc calls ~ 4n

when the registry is not mounted its just constant number of JDBC calls each time.

**How to reproduce:**
Load 500 XACML polcies from the filesystem with registry mounting, note the time taken.
```
<currentDBConfig>wso2registry</currentDBConfig>
    <readOnly>false</readOnly>
    <enableCache>true</enableCache>
    <registryRoot>/</registryRoot>
    <dbConfig name="wso2registry">
        <dataSource>jdbc/SHARED_DB</dataSource>
    </dbConfig>
    <!--<handler class="org.wso2.carbon.registry.extensions.handlers.SynapseRepositoryHandler">
        <filter class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher">
            <property name="mediaType">application/vnd.apache.synapse</property>
        </filter>
    </handler>
```
Clear the db and Try load 500 policies from the file system with registry mount present

```
<currentDBConfig>wso2registry</currentDBConfig>
    <readOnly>false</readOnly>
    <enableCache>true</enableCache>
    <registryRoot>/</registryRoot>
    <dbConfig name="wso2registry">
        <dataSource>jdbc/WSO2CarbonDB</dataSource>
    </dbConfig>
    <dbConfig name="govregistry">
        <dataSource>jdbc/SHARED_DB</dataSource>
    </dbConfig>
    <dbConfig name="configregistry">
        <dataSource>jdbc/SHARED_DB</dataSource>
    </dbConfig>
    <remoteInstance url="https://localhost">
        <id>gov</id>
        <cacheId>postgres@jdbc:postgresql://localhost:5432/wso2db</cacheId>
        <dbConfig>govregistry</dbConfig>
        <readOnly>false</readOnly>
        <enableCache>true</enableCache>
        <registryRoot>/</registryRoot>
    </remoteInstance>
    <remoteInstance url="https://localhost">
        <id>conf</id>
        <cacheId>postgres@jdbc:postgresql://localhost:5432/wso2db</cacheId>
        <dbConfig>configregistry</dbConfig>
        <readOnly>false</readOnly>
        <enableCache>true</enableCache>
        <registryRoot>/</registryRoot>
    </remoteInstance>
    <mount overwrite="true" path="/_system/governance">
        <instanceId>gov</instanceId>
        <targetPath>/_system/governance</targetPath>
    </mount>
    <mount overwrite="true" path="/_system/config">
        <instanceId>conf</instanceId>
        <targetPath>/_system/config</targetPath>
    </mount>
    <!--<handler class="org.wso2.carbon.registry.extensions.handlers.SynapseRepositoryHandler">
        <filter class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher">
            <property name="mediaType">application/vnd.apache.synapse</property>
        </filter>
    </handler>
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0]
 - Database: [Posgress]

[1]https://github.com/yasassri/carbon4-kernel/blob/master/core/org.wso2.carbon.registry.core/src/main/java/org/wso2/carbon/registry/core/jdbc/handlers/builtin/MountHandler.java#L429

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
