### ISSUE TITLE
SAML SLO infinite loop while IdP Initiated logout after 300 seconds

### ISSUE THREAD

**Issue by slawomirkisiel** [wso2/product-is#9376]
**Describe the issue:**
We have configured 2 SPs with SLO enabled. After login using SSO we work for a while in our application (at least 5 minutes). After this time starting IdP Initiated Logout cause infinite LogoutRequest/LogoutResponse loop.

**How to reproduce:**
1. configure 2 SPs with IdP Initiated SLO enabled,
2. Log in to SP (does not matter if single or both),
3. Wait for more than 5 minutes
4. Start IdP initiated logout

**Expected behavior:**
Logout subsequently SPs that are active for current IdP session.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.8.0
 - OS: Windows
 - Database: SQL Server
 - Userstore: JDBC

---

### Optional Fields

**Suggested labels:**
SAML SLO loop

**Comment by slawomirkisiel** [comment]
Committed change contains my proposition to fix this bug and additionally some minor changes for consistency.

During login process SAMLSSOParticipantCacheEntry is put into cache and into DataStore as well inside SAMLSSOParticipantCache.addToCache method.
Particular cache entry is invalidated after 300 seconds (default value in identity.xml configuration file entry for SAMLSSOParticipantCache cache). 

During IdP initiated logout process we have this process flow:
1. Identity Server fetches logged in SPs list,
2. If (and onlu if) cache is valid (which is true for 300 seconds since log in) SAMLSSOParticipantCacheEntry is fetched from cache (not in our case). In this case cache is expired thus data is fetched from persistent data store in SAMLSSOParticipantCache.getValueFromCache method,
3. DataStore keeps list of all SPs logged into IdP and this list is never updated during the logout process (which causes this issue),
4. IdP sends LogoutRequest to first SP,
5. SP returns LogoutResponse with positive status,
6. IdP fetches SAMLSSOParticipantCacheEntry object, but cache is already empty thus data is fetched from persistent data store again and IdP keeps it only as local variable created in SAMLSSOParticipantCache.getValueFromCache,
7. IdP removes current SP from list but it is still only inside local variable in removeSPFromSession method which is forgotten in a moment,
8. IdP fetches SPs list like in (3). Cache is still empty so list is fetched from datastore again and is intact. 

Solution:
* store updated SAMLSSOParticipantCacheEntry while it is changed in SAMLSSOProviderServlet.removeSPFromSession method by adding `SAMLSSOParticipantCache.getInstance().addToCache(cacheKey, cacheEntry);`
* put cache entry into cache after fetching it from persistent data store in SAMLSSOParticipantCache.getValueFromCache method as it could be used soon again by adding `addToCache(key, cacheEntry);`,
* consequently add the same behaviour to SAMLSSOSessionIndexCache and SessionDataCache classes (although it is not required to fix this issue).

**Comment by Yasara-Y** [comment]
This issue is already fixed in public master with [1]. Hence resolving the git issue.

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/339
