### ISSUE TITLE
Can't upload picture in user portal (CORS)

### ISSUE THREAD

**Issue by svenzimmermann** [wso2/product-is#9378]
Issue:
In the user portal it is not possible to upload an image via an image url located on external servers.
(An upload from the client is also not possible because the function is not implemented.)

![image](https://user-images.githubusercontent.com/27544406/85931732-cbc5e180-b8c6-11ea-83bf-baf692a4afd6.png)

How To Reproduce:
Install WSO2 IS 5.10
Login to user portal
try to upload a profile image from  external url

Expected behavior:
In the basic setting of the upload routine, the header should be set so that CORS is permitted from all sources. 
If this is not feasible without significant security losses, an function for an image upload from client to a secure storage space should be implemented. I would like to consider also that normal users usually do not have a web server to store an image there that is publicly accessible.

Device Information
- CentOS 8
- WSO2 IS 5.10 (release)
- current Chrome/Safari/Firefox

**Comment by brionmario** [comment]
Hi @svenzimmermann,

We have made some improvements to the profile picture uploading process[1] and once that PR is merged, the issue you've mentioned will be resolved.

[1] https://github.com/wso2/identity-apps/pull/1169
