### ISSUE TITLE
Improve IDP secret storage in configurations

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9384]
**Is your suggestion related to an experience ? Please describe.**
Currently, the product does not support product level encryption mechanisms, to encrypt IDP credentials stored when configuring IDPs. The product relies on database level encryption mechanisms.

**Describe the improvement**
Provide the ability to encrypt and store any IDP secrets.

Effort BE::15

**Comment by ZiyamSanthosh** [comment]
Closing this issue since the implementation has been done with the below given PR:
- https://github.com/wso2/carbon-identity-framework/pull/4430
