### ISSUE TITLE
Improve secret storage in User claims

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9385]
**Is your suggestion related to an experience ? Please describe.**
Currently, the product does not support product level encryption mechanisms or hashing mechanisms for storing sensitive user claims such as OTP backup codes. The product relies on database level encryption mechanisms.

**Describe the improvement**
Provide the ability to hash and store these secrets.

Effort BE::15

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
