### ISSUE TITLE
Make enable property of Event Listener config configurable

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#9388]
**Describe the improvement**

Currently, the event listener config is by default enabled. The following config is the currently existing template for the event listener config in "identity.xml.j2" file. 
```
        <EventListener id="{{listener.id}}"
                       type="{{listener.type}}"
                       name="{{listener.name}}"
                       orderId="{{listener.order}}"
                       enable="true">
            {% for key,value in listener.properties.items() %}
            <Property name="{{key}}">{{value}}</Property>
            {% endfor %}
        </EventListener>
```

In case if there is a requirement to disable an event listener, the event listener config should be configurable to set it to disable in deployment.toml file. Therefore that config should make configurable as follows.
```
        <EventListener id="{{listener.id}}"
                       type="{{listener.type}}"
                       name="{{listener.name}}"
                       orderId="{{listener.order}}"
                       enable="{{listener.enable}}">
            {% for key,value in listener.properties.items() %}
            <Property name="{{key}}">{{value}}</Property>
            {% endfor %}
        </EventListener>
```

**Comment by pulasthi7** [comment]
The custom event listeners don't need an enable flag. If you need to disable it you can simply delete or comment out the event listener and restart the server. That is the recommended way. Eg. In the following, 'foo' is enabled and 'bar' is disabled.

```
[event_listener]
name=foo

#[event_listener]
#name=bar
```
The enable flag is only intended for OOTB event listeners which are enabled by default and which won't have a specific config at the deployment.toml by default.

**Comment by rksk** [comment]
There are real-world requirements of this like https://github.com/wso2/product-is/issues/11604
