### ISSUE TITLE
OAuth tenant-specific endpoint - Redundant tenant domain in username

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#9393]
In the OAuth tenant-specific token endpoint (/t/{tenant-domain), we have to provide the tenant domain along with the username as well in the password grant. However, in the other grants such as code (Basic authentication), it is not required to provide the user tenant domain in the username. Hence, requiring the tenant domain to be appended on the username when using the tenant-specific endpoint when the domain is specified by the endpoint itself is redundant and should be fixed.

**Comment by omindu** [comment]
Will be addressed with https://github.com/wso2/product-is/issues/9526
