### ISSUE TITLE
The redirect screen shown during the authentication flow should be themed

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9395]
The redirect page that is shown when the user agent is redirected back to callback URL is currently plain and doesn't align with our overall theme. This page should be styled to be in consistent with the overall look and feel of our apps. 

![image](https://user-images.githubusercontent.com/20745428/92477391-256b5600-f1fe-11ea-9c58-5315a116af7d.png)

**Comment by kanchanagodage** [comment]
Fixed with [PR 1506](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1506)

**Comment by madurangasiriwardena** [comment]
A similar page is available for saml in [1] samlsso_response.html

Additionally, there are 2 more pages (samlsso_federate.html and sts_response.html) available in the product distribution.

[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/v5.8.20/features/org.wso2.carbon.identity.sso.saml.server.feature/resources/samlsso_response.html
