### ISSUE TITLE
Incomplete port configuration provided via deployment.toml

### ISSUE THREAD

**Issue by jbennett2091** [wso2/product-is#9399]
**Describe the issue:**
We have existing custom configuration in carbon.xml that we are trying to shift to deployment.toml around:
Ports.EmbeddedLDAP.LDapServerPort,
Ports.EmbeddedLDAP.KDCServerPort, and
Ports.ThriftEntitlementReceiverPort.   None of these appear to be configurable via properties as they appear to be hard-coded in carbon.xml.j2

**How to reproduce:**
Open the carbon.xml.j2 file and observe that no mapping exists
![image](https://user-images.githubusercontent.com/16721671/92562724-6dad6700-f244-11ea-91f3-7c5cd4265cd2.png)

**Expected behavior:**
Mapping should be provided so that these can be set via deployment.toml

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0

**Comment by ruwanta** [comment]
Embedded LDAP should be disabled for any real deployment. That is provided as a convenience feature to test and evaluate the downloaded pack. Hence there is no real reason to template that.

**Comment by jbennett2091** [comment]
What about thrift entitlement receiver port?

**Comment by jbennett2091** [comment]
I am satisfied with ruwanta's answer, and we have rationalized that we no longer need to configure thrift entitlement port as we do not use Apache Thrift.   Thank you.   issue closed
