### ISSUE TITLE
Identity Server 5.1.0 release date

### ISSUE THREAD

**Issue by tapas4java** [wso2/product-is#94]
Is there any tentative date for IDentity Server 5.1.0 release?

**Comment by jermookie** [comment]
I am wondering this too.

**Comment by tapas4java** [comment]
When you guys are going to release the `GA`?. It's more than 8 months now without any update. At least can we expect a `Beta 2` anytime soon??

**Comment by darshanasbg** [comment]
Hi @tapas4java,

Identity Server 5.1.0 RC will be released within this year. Currently there ain't any plans for Beta 2.

Thanks

**Comment by tapas4java** [comment]
Thanks @darshanasbg
