### ISSUE TITLE
IS doesn't support request_uri resolving

### ISSUE THREAD

**Issue by thiloshon** [wso2/product-is#9401]
**Describe the issue:**

IS has an extension to resolve request object. But `request_uri` object resolving requires `redirect_uri` to be an optional parameter as per PAR [1] spec. Currently any the authorization request without `redirect_uri` fails. This is incompatible with PAR spec.

[1] https://tools.ietf.org/html/draft-ietf-oauth-par-03#section-4

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by Pushpalanka** [comment]
This needs to have test cases in order to keep current test coverage ratio as it is.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
