### ISSUE TITLE
Invalid file name condition in authentication endpoint to include custom header.jsp

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#9419]
**Describe the issue:**
In multiple JSP files in the authentication endpoint, the code segment similar to below is found.
```
<head>
    <!-- header -->
    <%
        File headerFile = new File(getServletContext().getRealPath("extensions/product-title.jsp"));
        if (headerFile.exists()) {
    %>
        <jsp:include page="extensions/header.jsp"/>
    <% } else { %>
        <jsp:directive.include file="includes/header.jsp"/>
    <% } %>
</head>
```
However, theoratically, it should validate the existence of extensions/header.jsp to include the extensions/header.jsp file and not the extensions/product-title.jsp.

**Environment information**
 - Product Version: IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
