### ISSUE TITLE
When secure vault is enabled, deployment toml configs get cleared

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#9421]
**Describe the issue:**
When secure vault is enabled, we are adding a section in the deployment.toml file for secretes. This section start with the tag `[secrets]`. Now say we want to add a new config. If we add anything below the `[secrets]` section, during server startup they will be cleared, so the added changes are removed. Adding the config above to the secrets section will not create this issue.

**How to reproduce:**
Steps are described in the above section.

**Expected behavior:**
The place where we add any new config should not be relevant.

**Comment by pulasthi7** [comment]
IIRC, this was done due to a known limitation. So, for the moment we'll mention this in the docs and deprioritize

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
