### ISSUE TITLE
[wso2is-5.10.0] SCIM2 REST API access fails when using OAuth2 JWT token

### ISSUE THREAD

**Issue by ravihansa3000** [wso2/product-is#9431]
**Describe the issue:**
When accessing SCIM2 REST API in wso2is-5.10.0 using OAuth2 JWT token, a 403 response is returned. However, the same flow works fine in wso2is-5.9. 

**How to reproduce:**
1. Configure wso2is5.10.0 with HAProxy 
2. Enable SCIM API and configure LB access URL

```
[server]
hostname = "identity.mydomain.com"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}"

[transport.http]
port = "80"

[transport.https]
proxyPort = "443"

[user_store]
type = "read_write_ldap_unique_id"
connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated
scim_enabled=true

...

```

3. Register playground as a SP
4. Configure OAuth2 and set Token Issuer as `JWT`
5. Try to access `GET https://identity.mydomain.com/scim2/Users` with the header `Authorization: Bearer <token>` 

**Observations**
HTTP error response code returned: `HTTP/1.1 403 ` without any response body. No errors logged in `wso2carbon.log`

**Expected behavior:**
List of users for `GET /scim2/Users` 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:IS 5.10.0
 - OS: Linux/Ubuntu 20.04
 - Database: H2
 - Userstore: H2 Embedded LDAP

**Comment by ravihansa3000** [comment]
@Pushpalanka could you please confirm whether OAuth2 JTW tokens are supported for SCIM2 REST API in wso2is-5.10.0?

**Comment by mefarazath** [comment]
@ravihansa3000 Ideally it shouldn't matter what type of access token is used as long as the token has the required scopes. 
I suspect the token does not have the required scopes for the tried operation. Have you tried the same operation with an opaque token?

According to the identity.xml the endpoint is secured with the scope `internal_user_mgt_list` and the required permission to get that scope is `/permission/admin/manage/identity/usermgt/list`

```
        <Resource context="(.*)/scim2/Users" secured="true" http-method="GET">
            <Permissions>/permission/admin/manage/identity/usermgt/list</Permissions>
            <Scopes>internal_user_mgt_list</Scopes>
        </Resource>
```

Can you try with a token having scope **internal_user_mgt_list**?

**Comment by ravihansa3000** [comment]
@mefarazath Thanks for the response. I think the required scope is set since I'm trying to access using the super admin user. I'm able to access this endpoint if I use the basic auth method `curl --user admin:admin ....` 

As you suggested, I've enabled `usermgt/*` perms in this SP's role but still facing the same issue. But it shouldn't matter much since the super admin user should already have those perms. Appreciate if you can look into this.

**Comment by mefarazath** [comment]
Here's how i tried it out,

1. Use password grant and obtain a JWT access token using the password grant with the scope `internal_user_mgt_list`

```
curl --location --request POST 'https://localhost:9443/oauth2/token' \
--header 'Authorization: Basic NTE3QVRKTmFqZm14Z29sOUF0QnI0ZUJkV0NvYTpwcm15Z3ZDNVRxcUVTQjNSWTA3Nk05TTNPZ3Nh' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=admin_jdbc' \
--data-urlencode 'password=admin' \
--data-urlencode 'scope=internal_user_mgt_list'
```

2. Use the JWT token as the bearer token and call the /Users endpoint
```
curl --location --request GET 'https://localhost:9443/scim2/Users' \
--header 'Authorization: Bearer <access_token>'
```

I was able to invoke the /Users endpoint successfully as long as the JWT token had the required scope which was 'internal_user_mgt_list'. As soon as I obtained a token with that particular scope I got a 403

I tried this one a WUM updated pack with timestamp 1597088133056

Can we check whether the token you used to invoke the API has the scope?
We can easily do this by decoding the JWT and checking the 'scope' claim within the JWT

**Comment by ravihansa3000** [comment]
@mefarazath Thank you for the clarification! The scim2 endpoint responds as expected when the scope is set.

**Comment by mefarazath** [comment]
@ravihansa3000 Glad to know it worked!
I realized we are missing the required scope information for each operation in the swagger. Opened https://github.com/wso2/docs-is/issues/2048 to fix it.
