### ISSUE TITLE
The dashboard link mention in the readme file does not work 

### ISSUE THREAD

**Issue by Achsuthan** [wso2/product-is#9435]
**Describe the issue:**
The [readme](https://github.com/wso2/product-is/blob/master/README.md) document has the following link [https://localhost:9443/dashboard](https://localhost:9443/dashboard). However, this is not working.

**How to reproduce:**
I cloned the master branch and built the app. Though the carbon link [https://localhost:9443/carbon/](https://localhost:9443/carbon/) is working, the dashboard link [https://localhost:9443/dashboard](https://localhost:9443/dashboard) is not working. Then I downloaded the 5.10 release and tried it as well but the link is not working there also.

**Comment by ruwanta** [comment]
Thank you @Achsuthan 

The product has an updated end user portal named "myaccount". The previous dashboard is retired in favour of modern UI technology.
I updated the Readme files with the correct URL
https://github.com/wso2/product-is/pull/9438

**Comment by Achsuthan** [comment]
Thanks for the information @ruwanta

**Comment by ruwanta** [comment]
Closing this as the information is updated with pull request
https://github.com/wso2/product-is/pull/9438
