### ISSUE TITLE
MySQL error when executing provided dbscript

### ISSUE THREAD

**Issue by Hareendran7** [wso2/product-is#9439]
**Describe the issue:**
Creating the Identity_DB by following ( https://is.docs.wso2.com/en/latest/setup/changing-to-mysql/), gives a MySQL error  when executing the provided db script  <IS-HOME>/dbscripts/identity/mysql.sql

**How to reproduce:**
- Create an empty database in MySQL
- Execute script <IS-HOME>/dbscripts/identity/mysql.sql

**Following error is given,**
ERROR 1089 (HY000) at line 1059: Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys

**Suggested approaches to overcome the issue,** 
I hope the following SQL syntax in mysql.sql gives the error when trying to create an index prefix that is longer than the actual column being indexed

CREATE TABLE IF NOT EXISTS IDN_CONFIG_ATTRIBUTE (
    ID VARCHAR(255) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    **ATTR_KEY VARCHAR(255) NOT NULL,**
    ATTR_VALUE VARCHAR(1023) NULL,
    PRIMARY KEY (ID),
    CONSTRAINT RESOURCE_KEY_VAL_CONSTRAINT UNIQUE (RESOURCE_ID(64), **ATTR_KEY(703)**)
)ENGINE INNODB;
ALTER TABLE IDN_CONFIG_ATTRIBUTE ADD CONSTRAINT RESOURCE_ID_ATTRIBUTE_FOREIGN_CONSTRAINT FOREIGN KEY (RESOURCE_ID)
REFERENCES IDN_CONFIG_RESOURCE (ID) ON DELETE CASCADE ON UPDATE CASCADE;

**Environment information** 
 - Product Version: [ IS 5.10.0]
 - OS: [Linux]
 - Database: [MySQL]
 - Userstore: [JDBC]

---

**Comment by senthalan** [comment]
This is already fixed in the master with https://github.com/wso2/carbon-identity-framework/pull/3075.
