### ISSUE TITLE
[Test] SAML WEB Application management in develop section [UI] 

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9443]
Describe the Issue:
"SAML WEB Application management in develop section [UI] " test outdated and should update according to the latest changes

Test description
Scenario:
SAML WEB Application management in develop section

Sub scenarios:

Create a web application
Update with SAML configuration with the test data
List Web Application
Delete Created web Application.
Update SAML Application general settings
Update SAML Application Advanced settings(SAML configurations)
Update SAML Application Attribute settings
Update SAML Application provisioning settings
Update SAML Application Authentication-Sign-on Method settings

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
