### ISSUE TITLE
[Test] Update outdated test in "Users in manage section [UI]

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9444]
Describe the Issue:
"Users in manage section [UI] " test outdated and should update according to the latest changes

Test description

Scenario:
Users

Sub scenarios:

Add users
List users
Remove users
Update users general setting
Update users groups
Update users roles
Delete users

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
