### ISSUE TITLE
SCIM 2.0 User endpoint API return Unique ID difference ID user in user store

### ISSUE THREAD

**Issue by hieuhn2802** [wso2/product-is#9445]
**Describe the issue:**
I used User endpoint RestAPI SCIM2 create user and return Unique ID. But when i search Users, i get that users but the id is diferent. So i can't use delete user API or get user by id. Please help me. Thanks!

Picture1: create new user
Pic2: search list user and get user created

![image](https://user-images.githubusercontent.com/71259896/93072995-6c4cc600-f6ac-11ea-9651-49293d5b73d0.png)

![image](https://user-images.githubusercontent.com/71259896/93073054-825a8680-f6ac-11ea-8841-ec0af8bbf73c.png)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
