### ISSUE TITLE
[Test] Update outdated test in "Identity provider Facebook in develop section [UI] "

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9446]
Describe the Issue:
"Identity provider Facebook in develop section [UI] " test outdated and should update according to the latest changes

Test description

Scenario:

Identity provider Facebook
Sub scenarios:

Create identity provider Facebook
List Identity provider
Remove identity provider
Update identity provider Facebook general settings
Update identity provider Facebook Advanced settings
Update identity provider Facebook Attribute settings
Update identity provider Facebook Outbound provisioning settings
Update identity provider Facebook Authentication settings
Update identity provider Facebook Just-in-Time provisioning settings

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
