### ISSUE TITLE
[Test] Add cypress test for connection management and token management [Rest API]

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9447]
Is test automation request to which product feature? Please describe.
Request, automated test for Rest API for connection management and token management

Describe the solution you would prefer
Add cypress test script for the getting started page under API test category

Approach
Step_01 - Identify the scenarios, sub scenarios and test cases
Step_02 - Manual test on identified test cases
Step_03 -Implement the test scripts
Step_04 -Review the implemented test scripts
Step_05 -Test on-board to cypress cloud test suite

User stories
[TBD]

Test cases and validation criteria
[TBD]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
