### ISSUE TITLE
Update outdated test in "Identity provider Google in develop section [UI] "

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9448]
Describe the Issue:
"Identity provider Google in develop section [UI] " test outdated and should update according to the latest changes

Test description

Scenario:
Identity provider google

Sub scenarios:

Create identity provider Google
List Identity provider
Remove identity provider
Update identity provider google general settings
Update identity provider google Advanced settings
Update identity provider google Attribute settings
Update identity provider google Outbound provisioning settings
Update identity provider google Authentication settings
Update identity provider google Just-in-Time provisioning settings

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
