### ISSUE TITLE
[Test] Role API

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9449]
Describe the Issue:
Role API test scripting and on board to test suite

Test description

Scenario:

Role API
Sub scenarios:

POST/Role Create Roles
GET/Role Filter roles
GET/ role by ID
POST/.search
GET ​/Get Role by ID
PUT/Update Role - PUT
DELETE/Delete Role
PATCH/Update Role - PATCH

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
