### ISSUE TITLE
Could not find mapping from deployment.toml to default.xml authentication steps

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#9452]
**Is your suggestion related to an experience ? Please describe.**
I have found that authentication steps can be added to default authentication sequence by adding authentication steps to 
<IS_HOME>/repository/conf/identity/service-providers/default.xml. 

But I could not find a way to include those configurations to deployment.toml

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
