### ISSUE TITLE
Test migration client for symmetric key encryption BPS password and Kerberos security policy password

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9455]
**Description:**
Refer original task https://github.com/wso2/product-is/issues/9275 for details.

Need to test the following  Admin flows
    

- [ ] BPS profile password - **Fix when following fixes are merged to the product** (https://github.com/wso2/carbon-kernel/pull/2758 and https://github.com/wso2/carbon-crypto-service/pull/21)

- [ ] Kerberos security policy password - _when the active STS connector is released_

**Comment by DMHP** [comment]
BPS profile password  flow tested and verified.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
