### ISSUE TITLE
How To: Login to Microsoft Exchange using the Identity Server

### ISSUE THREAD

**Issue by krishnilak** [wso2/product-is#9457]
Please add below topic to IS 5.10 documentation as well. 
https://docs.wso2.com/display/IS510/How+To%3A+Login+to+Microsoft+Exchange+using+the+Identity+Server

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
