### ISSUE TITLE
Add support to skip current session and token from being terminated/revoked when updating the password

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#9461]
**Is your suggestion related to an experience ? Please describe.**
Currently, when the password is updated by the user, all the sessions are terminated, and all the tokens are revoked. Hence, the user is logged out from the current session, and will have to log in again with the new password.

**Describe the improvement**
With this improvement, it is possible to skip the current session/token from being terminated/revoked, which stops the user from being logged out from the current session.

**Comment by mefarazath** [comment]
Related to https://github.com/wso2/product-is/issues/8988
