### ISSUE TITLE
When click on "Myaccount" > "Already have an account? Sign in" then page will navigate to  "/user-portal"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9464]
**Describe the issue:**
After enabling self Registration, when trying to create a new account through "myaccount", 
Then click on the "Already have an account? Sign in" link on the "Create a new account" page.
The page will then navigate to "/ user-portal"

**How to reproduce:**
Login to console & Enable self Registration
2. Navigate to myaccount
3. click on Create Account
4. The page will navigate to "Create a new account" page.
5. Click on Already have an account? Sign in

**Expected behavior:**
The page should navigate to myaccount login page

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 m36. snapshot
 - OS: Mac
 - Database: H2
 - Userstore: LDAP
-Browser Firefox

Please refer screenshots attached:
![image](https://user-images.githubusercontent.com/39120228/93247408-e44de580-f7ab-11ea-94c7-9f1d62cc419a.png)

Then Page will navigate to 
![image](https://user-images.githubusercontent.com/39120228/93247472-f4fe5b80-f7ab-11ea-9284-e9e036ad1279.png)

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by brionmario** [comment]
This issue was fixed with https://github.com/wso2/carbon-identity-framework/pull/3086 & https://github.com/wso2/identity-apps/pull/1199.
