### ISSUE TITLE
"Attributes > Local Dialect > Local Attributes " modification does not affect in "Console > mange > user profile"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9465]
**Describe the issue:**
When doing any update "Show this attribute on user profile and user registration page" function in  "Attributes > Local Dialect > Local Attributes " those modifications do not affect  in "Console > mange > user profile"

**How to reproduce:**
Login to Console > Mange 
1. Navigate to Attribute Dialects > Local Dialects > 
2. select any Local Attribute
3. ex: Country and check > Show this attribute on user profile and user registration page option
4. Update
5. Verify that attribute displaying in the user profile, when new user creation 

![image](https://user-images.githubusercontent.com/39120228/93249613-36dcd100-f7af-11ea-83bb-e156ac6d6275.png)

Verify user profile after attribute update & while new user creation
![image](https://user-images.githubusercontent.com/39120228/93250139-fb8ed200-f7af-11ea-9c1e-272fe1d261ee.png)

**Expected behavior:**
The modification should be affected in the user profile as well as the User registration page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 m36 snapshot
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

---

**Comment by NipuniBhagya** [comment]
The local attribute country doesn't have a corresponding SCIM attribute and that's specifically it's not displayed in the profile. So creates an issue to track this https://github.com/wso2/product-is/issues/10434.
