### ISSUE TITLE
[UI] Role type is missing in Role creation wizard

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9470]
**Describe the issue:**
Role type is missing in Role creation wizard > summery 
And there is no any input field to provide /select Role type

**How to reproduce:**
Login to console > manage
2. Create a new Role 
3. Provide name > add permissions > assign Group /user > vew summary section 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:5.11 m36 snapshot
 - OS:  Mac
 - Database: H2
 - Userstore:LDAP
- Browser: Firefox 80.0.1 (64-bit)

Please refer attached screenshot:
![image](https://user-images.githubusercontent.com/39120228/93306812-fa948980-f81d-11ea-9d73-d13f711046cc.png)

**Comment by IsuraD** [comment]
Also, the permissin deselection won't work properly.
