### ISSUE TITLE
The token revocation implementation needs to be refactored

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#9472]
**Is your suggestion related to an experience ? Please describe.**
We are having more than one place where the tokens are revoked.
1. From token revoke endpoint
2. From the system listeners. (User password update, session termination)

There cache clearing and involving listeners are duplicated in al these places. So when doing some improvements to the revoke logic miss some places.

**Describe the improvement**
We need to have a single place for the complete revoke implementation and it should be used in all the places.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
