### ISSUE TITLE
Go Back button does not work

### ISSUE THREAD

**Issue by kanchanagodage** [wso2/product-is#9473]
Go Back button does not work in the user self-registration flow.
![Screenshot (362)](https://user-images.githubusercontent.com/29212717/93576102-1895f180-f9b8-11ea-917f-19fe79627663.png)

**Comment by inthirakumaaran** [comment]
The same issue can be observed for link expiry as well. The reason for this issue is we are not handling the error code: `EXPIRED_CODE`
