### ISSUE TITLE
Allow user to select preferred recovery channel in the user portal

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#9482]
**Is your suggestion related to experience? Please describe.**
Currently, Identity Server is capable of supporting multiple recovery channels such as email, SMS, etc. However, currently, there is no way for a user to say which of the recovery channels is his/her preferred one.

**Describe the improvement**
Allow users to set the preferred recovery channel from the user portal (store this as a user's claim or attribute) and use it in recovery APIs.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
