### ISSUE TITLE
Unable to create workflow definitions

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9490]
**Describe the issue:**
Unable to create WF definitions from the management console.

**How to reproduce:**

1. Login to the management console
2. Click **Add** under **Workflow Engagements**
3. Provide a **Workflow Name** and click **Next**
4. **Add Approval Step**
5. **Roles** or **Users** are not getting listed, and in the browser console following error is displayed.
![image](https://user-images.githubusercontent.com/5061791/93555243-0d7c9a80-f993-11ea-918c-f26ab3e11240.png)

  
**Expected behaviour:**
Should be able to add **Roles** or **Users** for the approval step.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0-M36-SNAPSHOT]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [LDAP]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pulasthi7** [comment]
Not Reproducible with Alpha 2 with and without secondary user stores. Hence closing.

Please re-open if you still find the issue.
