### ISSUE TITLE
OIDC sample application keeps reloading for latest chrome versions

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#9491]
**Describe the issue:**
When WSO2 IS and OIDC sample application provided in the samples-is repo is hosted locally in different domains, OIDC sample app keeps reloading indefinitely once the user sign-in to the application.

**How to reproduce:**
1. Host IS and OIDC sample application two different domains.
2. Configure OIDC sample application as a service provider in IS.
3. Login to the OIDC sample application in latest version of chrome.

**Expected behavior:**
User should be able to login successfully and OIDC application should logout automatically when an SLO is initiated by another application.

**Notes**
This issue is occurring because latest chrome browser blocks third-party cookies that doesn't have `SameSite=None` and `Secure` attributes set.

**Comment by janakamarasena** [comment]
https://www.searchenginejournal.com/chrome-84-3rd-party-cookies/374529/

**Comment by deshankoswatte** [comment]
I experienced the same issue with Firefox when I used the pickup-dispatch from samples 4.3.0 release. @janakamarasena with the latest samples release this issue was resolved.

**Comment by minolih** [comment]
This issue is now resolved in the latest sample release as back channel logout has been enabled. 

Tested with sample 4.4.0 and IS 5.12.0 Alpha 16.
