### ISSUE TITLE
samples-is: custom-jdbc-user-store-manager does not work in WSO2 IS 5.10.0

### ISSUE THREAD

**Issue by danijelt** [wso2/product-is#9492]
**Describe the issue:**
Project custom-jdbc-user-store-manager from samples-is repository does not work by default in IS (or IS-KM) 5.10.0.

The project has dependencies on WSO2 Carbon components v4.6.0. The package, when placed in `repository/components/dropins`, is never recognized and loaded. There are no indications of problem in info or debug logs.

Lowering the wso2.carbon packages versions to 4.4.40 allows it to be loaded by WSO2 on startup. Anything 4.5.x and above breaks the sample.

As a result, custom-jdbc-user-store-manager can't be used to extend UniqueIDJDBCUserStoreManager and must be modified to extend the old JDBCUserStoreManager.

**How to reproduce:**
- Extract and configure IS 5.10.0 or IS-KM 5.10.0 (on a Linux machine)
- Build custom-jdbc-user-store-manager from samples-is with `mvn clean install`
- Place the resulting *.jar to `repository/components/dropins`
- Restart WSO2 IS. The custom manager will never load with no indications in INFO or DEBUG logs about why it isn't working.
- Set the target WSO2 Carbon version to 4.4.40, modify code to extend JDBCUserStoreManager and recompile. The manager will now work.

**Expected behavior:**
- custom-jdbc-user-store-manager working out of the box according to the documentation ("This user store is compatible with IS 5.10.0 and have the custom unique user id jdbc user store implementation.")

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0, IS-KM 5.10.0
 - OS: Linux
 - Database: does not apply
 - Userstore: does not apply
 - Java: tested with both Java 8 and Java 11
 - Maven: 3.6.3

**Comment by danijelt** [comment]
Still not working in IS 5.11.0. In addition, v5.11 requires explicit whitelisting of custom JDBC user store in deployment.toml:
```
[user_store_mgt]
allowed_user_stores=...
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
