### ISSUE TITLE
Unexpected behaviour when switching users in the browser

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9509]
**Describe the Issue:**

**How To Reproduce:**
1. Create a new user "userA", but do not assign any permissions
2. Now in a new browser, try to login to dev portal as the userA
3. UserA is unable to login and get a warning saying "You are not authorized" which is expected.
![continue](https://user-images.githubusercontent.com/5061791/82322050-7b1fb680-99f3-11ea-876b-abc60825cbd0.png)

4. Then, continue to logout using the button on the same page, and you will get the login page
5. Try login as a privileged user(tenant admin) in the same tab.
6. Still, the same screen on step wso2/identity-apps#3 is observed, which is not expected.
7. If you try in a different browser as an admin user, then able to log in as expected.

**Expected behavior:**
- Step 6 should be a successful login.

**Device Information** (_Please complete the following information_) **:**
 - chrome

**Comment by pulasthi7** [comment]
@brionmario Can we close this issue?

**Comment by brionmario** [comment]
> @brionmario Can we close this issue?

Yes we can. Had a concern with the fix not working with the new Worker integration, but upon testing with the latest pack (5.11.0 ALPHA), the fixes seems to be working fine. Hence, closing this issue.
