### ISSUE TITLE
Unable to interpret the Geo Location based statistics of Korea in the Map Widget

### ISSUE THREAD

**Issue by janithcmw** [wso2/product-is#9521]
**Description of the issue:**

Geo Location-based data will be captured based on the IP and stored in the relevant database tables. In the storing process the country name used as "Republic of Korea" but in the mapping of MAP widget, the name, "Korea, Republic of" was used instead of "Republic of Korea" for the same country. Because of this, the data will not be highlighted on the top of the county in the MAP.

**How to reproduce:**

This can be reproduced by invoking sample data by manipulating the IP which relevant to the county "Republic of Korea". 

**Expected behaviour:**

It is expected to view the statistics as follows, but the statistics will not be appearing.
<img width="1920" alt="Screenshot 2020-09-22 at 09 09 10" src="https://user-images.githubusercontent.com/47592448/93842115-614cf380-fcb3-11ea-8b6d-98302b19cee7.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.8.0 - Analytics

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
