### ISSUE TITLE
Application Template management API Delete operation is not working

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#9529]
**Description**

Application Template management API delete operation [1] is not working. It gives the following 404 error response.
```
{
    "code": "TMM_00021",
    "message": "Template not found",
    "description": "A template with the given id t565e11e-fc78-484b-9bec-015d2472008 is not found in the tenant carbon.super.",
    "traceId": "38aefcd9-c9dc-4bba-9699-6bc36ff90f13"
}
``` 

**Environment information** 
 - Product Version: wso2is-5.11.0-alpha

[1] https://is.docs.wso2.com/en/5.11.0/develop/application-rest-api/#/Application%20Templates/deleteApplicationTemplate

**Comment by somindatommy** [comment]
This issue cannot be reproduced with IS 5.11.0-Beta3

**Comment by somindatommy** [comment]
This can be reproduced for any template that is there is the product OOTB.
