### ISSUE TITLE
Invoking an admin service

### ISSUE THREAD

**Issue by maghibus** [wso2/product-is#9533]
**Describe the issue:**
Invoking admin services with session cookies gives HTTP 401 error

**How to reproduce:**
log in to the Web application using WSO2 Identity Server and copy yours cookie
![image](https://user-images.githubusercontent.com/21333465/93901954-574ce400-fcf7-11ea-83e6-712a8e78736c.png)

insert cookies in the call to the web service

``` java 
 SSLContext sslContext = SSLContext.getInstance("TLS");
    sslContext.init(null, new TrustManager[] {new TrustAllTrustManager()}, null);
    String serviceEndPoint = wso2url +"/services/RemoteUserStoreManagerService";
    adminStub = new RemoteUserStoreManagerServiceStub(serviceEndPoint);
    ServiceClient client = adminStub._getServiceClient();
    Options option = client.getOptions();
    option.setProperty(HTTPConstants.COOKIE_STRING, "route=1600762628.789.330.799271; Path=/; Secure=null; HttpOnly=null;JSESSIONID=59FBBDE6F3FF5847C1591CDD2B2F2446; Path=/; Secure=null; HttpOnly=null");
    option.setProperty(HTTPConstants.CUSTOM_PROTOCOL_HANDLER,new Protocol("https", (ProtocolSocketFactory) new SSLProtocolSocketFactory(sslContext), 443));
    option.setManageSession(true);
``` 

**Expected behavior:**
The user list 
`Login Successful
route=1600783574.582.332.933103; Path=/; Secure=null; HttpOnly=null;JSESSIONID=B3B3B7B213FD1A89D72DFE9FA5598A7C; Path=/; Secure=null; HttpOnly=null
Listing user names of Carbon server...... 
User Name : admin`
**Environment information:**
 - Product Version:  IS 5.9.0

**Comment by pulasthi7** [comment]
Hi @maghibus ,

These cookies are only for front-end session. So, you won't be able to use those to authenticate to the (backend) admin services directly.

To get a cookie which you can use to invoke an admin service, you can use the 'AuthenticationAdmin' SOAP service first with the correct credentials and get the cookies in that response (given that you are correctly authenticated) to invoke the other admin services.

**Comment by pulasthi7** [comment]
Closing as answered. Please feel free to re-open if you have any further details on this.
