### ISSUE TITLE
Userstore connection password appears empty always

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9540]
**Describe the issue:**
Userstore connection password appears empty from the console, it gives wrong impression that password is not set.

**How to reproduce:**

1. Create a new JDBC userstore from the console with all the relevant fields
2. Goto edit view of the created user-store
3. Password field is empty regardless it was setup in the previous step.

![user-store-pass](https://user-images.githubusercontent.com/5061791/93978549-ca0e9b80-fd99-11ea-8514-8ea99a3f51eb.png)

This gives the impression that userstore connection password is not provided. *Test Connection* functionality also not working as the password is not provided.

**Expected behavior:**
Show Masked value of userstore password as ******. Test connection should be able to work without typing the password again.

**Comment by tharindu-bandara** [comment]
Looks like in the management console password value is retrieved thus test connection also works. Need to investigate how the password value is retrieved here: https://github.com/wso2/carbon-identity-framework/blob/592d79f56b9eb181eca3fa7896f13ae301deee9c/components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/userstore-config.jsp#L156. That will provide a clue to fix this issue.

**Comment by tharindu-bandara** [comment]
I have fixed this issue in the following manner. First, we need to wait until #10670 resolves. It updates the testing RDBMS API in the user store management REST API.

Then use the String value `ENCRYPTED PROPERTY` in the password field. Make sure this text is masked with *** since it's a password(UI peeps, you know how to handle this better than me!). What I guarantee is if you make the API call with the password as  `ENCRYPTED PROPERTY` and the newly added attribute `domain` as the correct user store manager domain, testing the connection will work.

I'm assigning this back to you @NipuniBhagya. Once #10670 resolved, please kindly add the needful UI changes.

**Comment by tharindu-bandara** [comment]
@NipuniBhagya #10670 is resolved. We can proceed with the UI fix.

**Comment by tharindu-bandara** [comment]
Adding further information on top of https://github.com/wso2/product-is/issues/9540#issuecomment-747328673,

- Initial requirement is to make the test connection button work when the connection details screen loads. To do that,
   - Use reserved string `ENCRYPTED PROPERTY` as password and set user store domain name as the `domain` parameter. 
```
curl --location --request POST 'https://localhost:9443/api/server/v1/userstores/test-connection' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
    "driverName": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
    "connectionURL": "jdbc:sqlserver://localhost:1433;databaseName=test",
    "username": "sa",
    "connectionPassword": "ENCRYPTED PROPERTY",
    "domain":"SECONDARY"
}'
```

Now there could be a scenario where the user can change the password field intentionally to the `ENCRYPTED PROPERTY`. Therefore I would suggest including the `domain` parameter in the above payload at all times.

Another thing is, for all the test connection failures(credentials are wrong, or DB call failed etc.) API will respond with `false` status. Therefore indicating test connection failed in a generic manner(without specifically handling each case such as invalid credentials) should be enough.

**Comment by rksk** [comment]
This is addressed by adding a new checkbox for password update; as shown in the video attached to https://github.com/wso2/product-is/issues/18747.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
