### ISSUE TITLE
When a user-store is created with type JDBCUserStoreManager, console breaks

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9546]
**Describe the issue:**
- User-store management REST API allows creating user-store of type JDBCUserStoreManager
- but when browsing the user-store from the console, it gives an error
- User list page also not showing results

**How to reproduce:**
1. Start a fresh IS-5.11.0-Alpha instance 
2. Use following curl to create a user-store, this is the sample request content in the documentation as well.
```
curl --location --request POST 'https://localhost:9443/t/carbon.super/api/server/v1/userstores' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 1e53959e-fc9a-3ce8-973f-b8f421ae828e' \
--header 'Cookie: opbs=32e5034a-0efc-471c-987c-6f7c1d662095; commonAuthId=a961236f-d72a-4991-a4f3-507159d464c6' \
--data-raw '{
  "typeId": "SkRCQ1VzZXJTdG9yZU1hbmFnZXI",
  "description": "Sample JDBC user store to add.",
  "name": "JDBCUserStore",
  "properties": [
    {
      "name": "userName",
      "value": "wso2automation"
    },
    {
      "name": "password",
      "value": "wso2automation"
    },
    {"name": "driverName",
      "value": "org.h2.Driver"
    },
    {
      "name":"url",
      "value":"jdbc:h2:./repository/database/JDBC_H2_DB"
    },
    {
      "name":"disabled",
      "value":"true"
    }
  ]
}'
```
3. API return *201 Created* as response
4. Login to the console and brows the created user-store, *Resource not found error* is observed
5. In the network following was observed for the request 
```
Request URL: https://localhost:9443/api/server/v1/userstores/meta/types/SkRCQ1VzZXJTdG9yZU1hbmFnZXI
Request Method: GET
Status Code: 404 

Response: 
{"code":"SUS-60003","message":"Resource not found.","description":"Unable to find a required resource for this request","traceId":"2b35941d-de6b-4770-8fe1-b3878aa38a72"}
```

6. Also when browsing users for that user-store from the management console following error is observed
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Error while retrieving users for the domain: JDBC-1 with limit: 9 and offset: 1.","status":"500"}
```

**Expected behavior:**
- user should not be able to add user-store of unsupported types.
- the sample request content in the documentation should be a valid one.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.11.0-Alpha]
 - OS: [Mac]
 - Database: [MySQL 5.7]

**Comment by sachiniWettasinghe** [comment]
Ideally, the user should be able to add a userstore of any type (regardless of the supported userstore type) using the REST APIs. 
But in order to support such a userstore type from the management console or the console application, the following configuration should be added to the <PRODUCT_HOME>/repository/conf/deployment.toml file.

**Sample configuration:**
```
[[allowed_user_stores]]
class = "org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager"
```
