### ISSUE TITLE
'Resend code' API returns status code as 201 even at failure case.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9550]
**Describe the issue:**
Even if the resend code API failed to send the code in an attempt it returns 201 as the HTTP status code. Expected it will indicate a failure.

**How to reproduce:**
Call the resend API for an unsupported scenario.

**Expected behavior:**
Provide an indication of the error status in the HTTP status code.

Code - https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.user.endpoint/src/main/java/org/wso2/carbon/identity/user/endpoint/impl/ResendCodeApiServiceImpl.java#L66-L67

**Comment by Pushpalanka** [comment]
Fixed with https://github.com/wso2-extensions/identity-governance/pull/431
Need to improve to identify and address the 400 bad request case separately.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
