### ISSUE TITLE
Getting User from username giving wrong tenant when userStoreDomain is empty

### ISSUE THREAD

**Issue by geve82** [wso2/product-is#9554]
**Describe the issue:**

In https://github.com/wso2/carbon-identity-framework/blob/6ec2ea235d479b933e9e0a0b2e94741fad6a9a02/components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/User.java#L196

There is a small bug `setTenantDomain` is used but it must be changed to `setUserStoreDomain`

`
            if (StringUtils.isNotEmpty(userStoreDomain)) {
                user.setUserStoreDomain(userStoreDomain);
            } else {
                user.setTenantDomain(UserCoreConstants.PRIMARY_DEFAULT_DOMAIN_NAME);
            }
`

**How to reproduce:**
N/A

**Expected behavior:**
N/A

---

### Optional Fields

**Related issues:**

**Suggested labels:**
Identity Framework

**Comment by mefarazath** [comment]
@geve82 Good catch!
