### ISSUE TITLE
Inconsistent audit log pattern

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#9557]
**Describe the issue:**

The audit logs of the product IS are inconsistent. On some actions such as login and create, the log pattern is like
"..... Action : Login | Target : ...... "

But on some other actions, it goes as 
"......Action=Get-User-Claim-Values Target=......"

**Expected behavior:**
All should have a consistent pattern

**Comment by tharindu-bandara** [comment]
I have observed most of the audit logs have the semicolon to separate out key and value(`Action : Login`). Examples are password reset, account lock, etc. Therefore, its good to follow the same pattern for Get-User-Claim-Values audit log.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
