### ISSUE TITLE
Windows MSI for IS 5.10.0 fails to install correctly

### ISSUE THREAD

**Issue by robbla** [wso2/product-is#9559]
When installing via the MSI for Windows the JAVA_HOME and path are not set correctly. 

![is msi](https://user-images.githubusercontent.com/11582659/94111705-b704d580-fe44-11ea-927b-1487cda762f0.JPG)

**Comment by senthalan** [comment]
Make sure you have followed https://is.docs.wso2.com/en/latest/setup/installing-on-windows/#setting-up-java_home and set up the JAVA_HOME correctly.

For questions and discussions, I would encourage you to join our slack group. You can join through, https://is-slack.wso2.com

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
