### ISSUE TITLE
Add localization to the Console App

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9562]
The Console app currently supports only English. The app should be localized to support

- [ ] Portuguese
- [x] Sinhala
- [ ] Tamil

**Comment by kanchanagodage** [comment]
Translated the content of the console app to Sinhala, Tamil, and Portuguese using Google Translator and added to a sheet. Here is the document. [View Document](https://docs.google.com/spreadsheets/d/1P7037b3zFrGwKs1RAwjrPTKpURcXw4oxomw3H4tTqMY/edit?usp=sharing)

Will start implementation once the content finalized.

**Comment by DimalChandrasiri** [comment]
Reopening this issue since `Portuguese` and `Tamil` language support is still in progress.

**Comment by ayshsandu** [comment]
Prioritizing Portuguese and Tamil language support.
