### ISSUE TITLE
Data dictionary documentation does not contain all the tables shipped with the product

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#9570]
[Data dictionary](https://is.docs.wso2.com/en/latest/administer/data-dictionary/) documentation does not contain a list of all the tables shipped with the product. Some newly added tables are missing in the list.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
