### ISSUE TITLE
Add application specific session timeouts

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#9571]
**Is your feature request related to a problem? Please describe.**
At the moment, when a user logs in to an application using Identity Server as the IDP, an SSO session is created with the user agent and any application that is using the same user agent and has the same authentication factors can use the session until the session timeout happens, which can be configured as a tenant-specific configuration.

However, if the admin wants to configure different timeouts to different applications in a tenant there is no way. This requirement can come when there are different security levels for different applications. For example, a payment app vs an information app (such as an email app) may need different timeouts.

**Describe the solution you would prefer**
There are different aspects we need to consider here. Some points are as below.
- Can this be achieved with a concept of the circle of trust?
- Can we introduce a way to reduce the tenant's SSO timeout at the application level?
- How the SSO user experience behave?
- How the single logout works?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
