### ISSUE TITLE
Update My Account app overview page design

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#9572]
**Is your suggestion related to an experience ? Please describe.**

Suggested by: Sergiy

Visualize "Complete your profile", this is a good practice - graphical elements does system more clear. But in this case, more important information would be level of security. What if we show security level. In the same way based on steps user has done already. For users, their avatar isn't so important. Or even phone number if it hasn't to do with the safety. It isn't a social media, where he/she want to show his person. Avatar - is not very important for your service too. But concern about user's security and reminder about all available features is important.

![image](https://user-images.githubusercontent.com/7569427/94226328-f995e300-ff14-11ea-8db2-1fd9e12dae68.png)

**Describe the improvement**

Show security level information instead. And show profile completion may be within profile page it self.

![image](https://user-images.githubusercontent.com/7569427/94226489-57c2c600-ff15-11ea-82d5-dd93ce8965f9.png)

Effort::BE: 10
Effort::FE: 5

**Comment by thanujalk** [comment]
Related https://github.com/wso2-enterprise/asgardeo-product/issues/3941

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
