### ISSUE TITLE
SCIM username filter doesn't work for JDBC userstore

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#9576]
**Describe the issue:**
The request, `https://localhost:9443/scim2/Users?filter=userName+eq+user1` doesn't return the user user1. However, the request `https://localhost:9443/scim2/Users` returns the expected results and it confirms that the user1 exists on the user store.
````
{
            "meta": {
                "created": "2020-09-25T05:17:35.476Z",
                "location": "https://localhost:9443/scim2/Users/bc932540-2551-404b-9da4-cccea3dac1bf",
                "lastModified": "2020-09-25T05:17:35.476Z",
                "resourceType": "User"
            },
            "id": "bc932540-2551-404b-9da4-cccea3dac1bf",
            "userName": "US1/user1"
        }
````
The same behavior for `https://localhost:9443/scim2/Users?filter=userName+eq+user1&domain=US1` and `https://localhost:9443/scim2/Users?filter=userName+eq+US1/user1`.

It occurs since the uid claim (http://wso2.org/claims/username) is not populated for JDBC user stores in IS 5.10.

**Environment information** 
 - Product Version: IS 5.10.0

**Suggested labels:**
Severity/Blocker

**Comment by rksk** [comment]
The following query can be used to fill the uid claim for existing users
```
INSERT INTO UM_USER_ATTRIBUTE (UM_USER_ID, UM_ATTR_NAME, UM_ATTR_VALUE, UM_PROFILE_ID, UM_TENANT_ID)
SELECT t1.UM_ID, 'uid', t1.UM_USER_NAME, 'default', t1.UM_TENANT_ID
FROM UM_USER t1
LEFT JOIN 
    (SELECT DISTINCT(t8.UM_ID), t8.UM_USER_NAME
    FROM UM_USER t8
    LEFT JOIN UM_USER_ATTRIBUTE t9
    ON t8.UM_ID = t9.UM_USER_ID
    WHERE t9.UM_ATTR_NAME='uid') t2
ON t1.UM_ID = t2.UM_ID
WHERE t2.UM_ID IS NULL;
```
