### ISSUE TITLE
/validate-username and /claims endpoints are not tenant qualified in the self registration flow

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#9578]
**Describe the issue:**
In the self-registration flow, the rest API calls from the UI that was made from the account recovery web app is not called the tenanted endpoints. Below are the identified endpoints.

/api/identity/user/v1.0/validate-username
/api/identity/recovery/v0.9/claims

**How to reproduce:**
Try the self-registration flow with an email username with the tenant domain.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by somindatommy** [comment]
Reopening the issue since the public fix was reverted
