### ISSUE TITLE
Inconsistent SP description length limit in tables provokes crash at consent step

### ISSUE THREAD

**Issue by lemoinem** [wso2/product-is#9581]
Apologies if this is the wrong repo to report this issue.

**Describe the issue:**
SP description is expected to have max length 1023 in the HTML UI.

However, if the SP has claims configured, at consent step, the information is copied in table `CM_RECEIPT_SP_ASSOC`. This table has a 255 max length for the description. The copy fails and this triggers an Internal Server Error on WSO2 IS' part.

**How to reproduce:**
- Create a new SP in WSO2 IS
- Configure at least one claim
- Enter a description above 255 characters in length but below 1023
- Make sure whatever the protocol used (tested with OpenID Connect & SAML2), the claims/attributes are to be provided to the SP. This might require additional configuration for the given SSO/Auth Protocol.
- Configure a client SP to use this configuration
- Login:
   - Enter valid WSO2 IS credentials
   - Approve consent to share info (if possible, choose "Approve once" so the issue is easier to reproduce later)
=> Bug (500 Internal Server Error or some other error message), the user agent isn't returned to the client SP

Debugging this required to enable DEBUG logging and TRACE level 3 in the identity database.

**Expected behavior:**
Either the UI should limit input at 255 characters, or the table's definition should be updated to allow for longer descriptions.
The second option would be more flexible.

**Environment information**
 - Product Version: IS 5.10.0
 - OS: Windows
 - Database: H2

**Comment by pulasthi7** [comment]
Hi @lemoinem 

Thanks for reporting the issue. We'll check further on this and update here with the progress.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
