### ISSUE TITLE
Internal server error during the password recovery when user does not have an email

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9587]
**Describe the issue:**
At [1], we consider both the email missing scenario and template loading error as similar errors. Down the line, we return a 500 response code without any specific error description for both of them.
```
        if(StringUtils.isEmpty(sendTo)) {
            if (userClaims.containsKey(NotificationConstants.EmailNotification.CLAIM_URI_EMAIL)) {
                sendTo = userClaims.get(NotificationConstants.EmailNotification.CLAIM_URI_EMAIL);
            }
            if (StringUtils.isEmpty(sendTo)) {
                throw NotificationRuntimeException.error(
                        "Email notification sending failed. Sending email address is not configured for the user.");
            }
        }

        EmailTemplate emailTemplate;
        try {
            emailTemplate = NotificationHandlerDataHolder.getInstance().getEmailTemplateManager().getEmailTemplate(notificationEvent, locale, tenantDomain);
        } catch (I18nEmailMgtException e) {
            String message = "Error when retrieving template from tenant registry.";
            throw NotificationRuntimeException.error(message, e);
        }
```

Hence, the API invoker or a user who tries account recovery from default UIs, are unable to know that the error is occurred not because of an internal server error, but due to a missing claim.

**How to reproduce:**
- Enable email-based account recovery
- Create a user without filling the email claim
- Try the password recovery flow
- The following message is displayed on the UI

```
"The server encountered an internal error. Please contact administrator.
```

**Expected behavior:**
It should show a meaningful error message instead of a generic internal error.

**Environment information**
 - Product Version: IS 5.10.0

[1] https://github.com/wso2-extensions/identity-event-handler-notification/blob/master/components/event-handler-notification/org.wso2.carbon.identity.event.handler.notification/src/main/java/org/wso2/carbon/identity/event/handler/notification/util/NotificationUtil.java#L266-L282

**Comment by ayshsandu** [comment]
@pamodaaw @GANGANI Are we good to close this issue?

**Comment by GANGANI** [comment]
> @pamodaaw @GANGANI Are we good to close this issue?

This issue was resolve with https://github.com/wso2-extensions/identity-governance/pull/454. Hence we can close this issue.
