### ISSUE TITLE
Configuration for role-claim URL is missing in the console

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9589]
**How to reproduce:**

1. Create a IDP from the console
2. Goto **Attributes** section of the IDP
3. Unable to find a configuration which is used to specify the role claim
4. But when IDP is created via the REST API, it allows input for the role claim

![image](https://user-images.githubusercontent.com/5061791/94407746-76cd8c00-0191-11eb-90a2-b939bc5ed8d5.png)

**Expected behavior:**
Need to input to configure role claim for IDP.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**

**Comment by IsuraD** [comment]
Role claim attribute is required only when custom claim mappings are configured. It is already there. 

![Screenshot 2020-10-23 at 13 00 53](https://user-images.githubusercontent.com/8455535/96969270-d8361000-152f-11eb-8e76-960a05b9c654.png)
