### ISSUE TITLE
Add missing cleanup scripts

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#9591]
**Description**
Add missing session & registry clean up scripts

- [x] Add missing session cleanup scripts. refer https://github.com/wso2/product-is/issues/9397
- [ ] Add missing confirmation code cleanup scripts

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
