### ISSUE TITLE
Concurrency issue in getPrimaryUserstore method

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9617]
There is a concurrency issue when we make the variable static in https://github.com/wso2/identity-api-server/commit/1d5dbb15744d1f917e9e668af96b3ceed07b91d5#diff-c5de1d97283bba0d2bf432e1bc08b045R81

As a possible solution we can invoke the getPrimaryUserstore method during class loading as follows.

private static UserStoreConfigurationsRes primaryUserstoreConfigs = getPrimaryUserstore()

**Comment by emswbandara** [comment]
Can we prioritize this? It is not possible to run findbugs in api-server repo due to this issue.
@thanujalk @ayshsandu @pulasthi7

**Comment by pulasthi7** [comment]
@emswbandara Can we close this issue based on the above PR?

**Comment by emswbandara** [comment]
Yes we can.
