### ISSUE TITLE
Unable to associate members to group when creating groups using SCIM 2 API

### ISSUE THREAD

**Issue by darsham3** [wso2/product-is#9619]
**Describe the issue:**
Unable to associate members to group when creating groups using SCIM 2 API, using the following request:

```
{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ],
  "displayName": "APPLICATION/test role",
  "members": [
    {
      "display": "admin"
    }
  ]
}
```

Following response is received:

```
{
    "displayName": "Application/test role",
    "meta": {
        "created": "2020-09-30T04:55:52.917Z",
        "location": "https://wso2.is.com:9443/scim2/Groups/308ff545-28ee-4b95-a3ed-d5389da5bd71",
        "lastModified": "2020-09-30T04:55:52.917Z",
        "resourceType": "Group"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ],
    "members": [
        {
            "display": "admin"
        }
    ],
    "id": "308ff545-28ee-4b95-a3ed-d5389da5bd71"
}

```
Even though the response contains `admin` as a member, the group is not associated to admin. Verified it via Management console as well as retrieving the group by calling `GET /scim2/Groups/{groupId}` endpoint.

Following response is received for GET /scim2/Groups/308ff545-28ee-4b95-a3ed-d5389da5bd71 API call:

```
{
    "displayName": "Application/test role",
    "meta": {
        "created": "2020-09-30T04:55:52.917Z",
        "location": "https://wso2.is.com:9443/scim2/Groups/308ff545-28ee-4b95-a3ed-d5389da5bd71",
        "lastModified": "2020-09-30T04:55:52.917Z"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ],
    "id": "308ff545-28ee-4b95-a3ed-d5389da5bd71"
}
```

If we cannot associate groups with any users while creating the groups, the swagger definition needs to be updated accordingly.

Appreciate your inputs on this.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Ubuntu
 - Database: MySQL8
 - Userstore: JDBC

**Comment by mefarazath** [comment]
@emswbandara Is this an expected behaviour?

**Comment by NipuniBhagya** [comment]
Hi @darsham3 when assigning the members to a group you need to add the user id along with the display name. Please try creating the group with the following payload format.

```
{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ],
  "displayName": "APPLICATION/test role",
  "members": [
    {
      "display": "admin",
      "value": "USER_ID"
    }
  ]
}
```

**Comment by mefarazath** [comment]
@NipuniBhagya If the request is wrong shouldn't it fail?
The response received is misleading as it indicates the group contains the "admin" user as a member

```
{
    "displayName": "Application/test role",
    "meta": {
        "created": "2020-09-30T04:55:52.917Z",
        "location": "https://wso2.is.com:9443/scim2/Groups/308ff545-28ee-4b95-a3ed-d5389da5bd71",
        "lastModified": "2020-09-30T04:55:52.917Z",
        "resourceType": "Group"
    },
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:Group"
    ],
    "members": [
        {
            "display": "admin"
        }
    ],
    "id": "308ff545-28ee-4b95-a3ed-d5389da5bd71"
}
```

**Comment by IsuraD** [comment]
@nilasini @NipuniBhagya is the value mandatory according to the specification?

**Comment by AnuradhaSK** [comment]
According to the Group resource schema, members attribute is optional as well as all sub-attributes of the members attribute is optional. https://tools.ietf.org/html/rfc7643#section-8.7.1

According to the description of https://tools.ietf.org/html/rfc7643#page-26,
```
members
     A list of members of the Group.  While values MAY be added or
      removed, sub-attributes of members are "immutable".  The "value"
      sub-attribute contains the value of an "id" attribute of a SCIM
      resource, and the "$ref" sub-attribute must be the URI of a SCIM
      resource such as a "User", or a "Group".  The intention of the
      "Group" type is to allow the service provider to support nested
      groups.  Service providers MAY require clients to provide a
      non-empty value by setting the "required" attribute characteristic
      of a sub-attribute of the "members" attribute in the "Group"
```
Even though **Service providers MAY require clients to provide a
      non-empty value by setting the "required" attribute characteristic
      of a sub-attribute of the "members" attribute in the "Group"** state is there, non of the su attriute of members attribute is required according to the schema.

This has been discussed in the SCIM mailing list as well:
https://mailarchive.ietf.org/arch/msg/scim/MDNLyLWWLd9BzOX5TETpw3ow8To/

Since "value" is the only attribute to uniquely identify the resource, IMO considering "value" as a required sub-attribute of members attribute is better.
