### ISSUE TITLE
User claims cannot be viewed when trying to approve or deny a workflow task.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9634]
**Describe the issue:**
User claims cannot be viewed when trying to approve or deny a workflow task.
<img width="957" alt="Screenshot 2020-10-01 at 16 03 20" src="https://user-images.githubusercontent.com/47600906/94799104-40e20f00-0400-11eb-809c-698fd05bdfcb.png">

**How to reproduce:**

- Setup Workflow for user addition[1]
- Self-register/add a user.
- login to approving person's account and view the claims under "Pending approvals"

**Expected behavior:**
Claims of the user are propagated to the UI, however, are not displayed.(a side scroll bar would be nice there)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]

[1]https://is.docs.wso2.com/en/latest/learn/adding-a-new-workflow-definition/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
