### ISSUE TITLE
Improve OIDC sample app to demonstrate backchannel logout

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9645]
Improve one of the OIDC sample apps to demonstrate OIDC backchannel logout capability.

**Comment by darshanasbg** [comment]
@janakamarasena AFAIR, the playground application is capable of doing this.
@piraveena @ashendes Please correct me if im wrong.

Thanks,

**Comment by ashendes** [comment]
Yes, the Playground application has the backchannel logout functionality.

**Comment by piraveena** [comment]
This is implemented for pickup dispatch and manager as well. https://github.com/wso2/samples-is/pull/267.

**Comment by piraveena** [comment]
Hence closing this issue.

**Comment by janakamarasena** [comment]
@piraveena we have to do a refresh to the browser for the logout to be reflected right?
