### ISSUE TITLE
Client Credential OAuth 

### ISSUE THREAD

**Issue by gunjanvarshney** [wso2/product-is#9653]
**Describe the issue:**
I am trying https://is.docs.wso2.com/en/latest/learn/client-credentials-grant/ on a local install of IS. To test I use 

curl -v -X POST -H "Authorization: Basic TnFfQ1hONmpzdDlDZzNUUG9YN3dXWV9HOVljYTp2Smw5d0dVcWtrekpzV0xzQlRsaHBlNDVieTBhCg==" -k -d "grant_type=client_credentials" -H "Content-Type:application/x-www-form-urlencoded" https://localhost.com:9443/oauth2/token

I always get following error:

> POST /oauth2/token HTTP/1.1
> Host: localhost.com:9443
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Basic TnFfQ1hONmpzdDlDZzNUUG9YN3dXWV9HOVljYTp2Smw5d0dVcWtrekpzV0xzQlRsaHBlNDVieTBhCg==
> Content-Type:application/x-www-form-urlencoded
> Content-Length: 29
>
* upload completely sent off: 29 out of 29 bytes
< HTTP/1.1 401
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< WWW-Authenticate: Basic realm=localhost.com
< Date: Sat, 03 Oct 2020 00:45:20 GMT
< Content-Type: application/json
< Content-Length: 78
< Server: WSO2 Carbon Server
<
* Connection #0 to host localhost.com left intact
{"error_description":"Client Authentication failed.","error":"invalid_client"}* Closing connection 0

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - IS 5.10.0
 - OS: Mac
 - Database: H2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by prabath** [comment]
Can you please check the client_id and client_secret you copied from the service provider configuration are correct. Sometimes you may miss the last letter.

According to the cURL command you shared, your client_id is Nq_CXN6jst9Cg3TPoX7wWY_G9Yca and client_secret is vJl9wGUqkkzJsWLsBTlhpe45by0a

Thanks!
-Prabath

**Comment by pulasthi7** [comment]
hi @gunjanvarshney 

Were you able to check the client id and client secret as mentioned by Prabath in the above comment?

**Comment by prabath** [comment]
We can close this issue. Had a call and sorted out. The generated base64 encoded string was not correct.
