### ISSUE TITLE
Claims configured to be "Supported by Default" not show at myaccount

### ISSUE THREAD

**Issue by jvitor83** [wso2/product-is#9654]
**Describe the issue:**
Claims configured to be "Supported by Default" at my account profile, not showing when in SCIM extension schema `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`

This image show the SCIM schema request responded with `department`, `organization` and `cpf` (a custom claim), but not showing at the page/form 
![image](https://user-images.githubusercontent.com/3493339/94985764-4b4af880-0527-11eb-8407-c76611d5aa35.png)

**How to reproduce:**
Configure any claim that are in [SCIM schema `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`](https://localhost:9443/carbon/identity-claim-mgt/list-external-claims.jsp?externalClaimDialectURI=urn%3Aietf%3Aparams%3Ascim%3Aschemas%3Aextension%3Aenterprise%3A2.0%3AUser) to be ["Supported by Default" at wso2 local claims](https://localhost:9443/carbon/identity-claim-mgt/list-local-claims.jsp) and go to [Profile](https://localhost:9443/myaccount/personal-info)

**Expected behavior:**
Show the "Supported by Default" claims that are in SCIM schema `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`, like `Organization`, `Department`.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0-alpha3]
 - OS: Windows (using Docker)
 - Database: H2
 - Userstore: Active Directory (Primary only)

---

### Optional Fields

**Related issues:**
https://github.com/wso2/identity-apps/issues/261

**Suggested labels:**
SCIM MyAccount

**Comment by thanujalk** [comment]
Related https://github.com/wso2/product-is/issues/8681
