### ISSUE TITLE
Unable to update sameSite attribute of a cookie through the adaptive script.

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#9656]
**Describe the issue:**
> Through an adaptive script, we can set cookies in the response using the method [setCookie](https://is.docs.wso2.com/en/5.9.0/references/adaptive-authentication-js-api-reference/#setcookieresponse-name-value-properties). Also this method permits to set properties of the cookie such as secure, httpOnly, domain etc. But `sameSite` attribute can't be set through the script.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0

**Comment by rksk** [comment]
This is not documented.

**Comment by nilasini** [comment]
@mevan-karu shall we close this issue and create a documentation issue?

**Comment by mevan-karu** [comment]
Doc issue to track this improvement https://github.com/wso2/product-is/issues/13222.
