### ISSUE TITLE
Verify the content of the oidc discovery endpoint

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9660]
We need to verify whether the content in the discovery endpoint is accurate. 

- Check whether non-supported feature metadata are listed

- Check whether supported feature metadata are not listed

ex: https://github.com/wso2/product-is/issues/6749

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
