### ISSUE TITLE
IdP REST API shouldn't allow the creation of an IdP with invalid parameters

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9669]
See https://github.com/wso2/product-is/issues/9588 for more details.

The IdP API allows users to create IdPs with invalid parameters. Ideally, an error message should be thrown disallowing the creation of IdPs with invalid parameters.

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/identity-api-server/pull/244

Tests are added in https://github.com/wso2/product-is/pull/10698
