### ISSUE TITLE
Scope management REST API response is wrong

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9674]
**Describe the issue:**
When registering a scope with name profile getting "scope already existing" response but when listing the scope with profile getting "scope doesn't exist". 

**How to reproduce:**
1. Send the following scope registering request.
`curl -X POST -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type: application/json" -d '{"name": "profile", "displayName": "profile", "description": "get all profile information", "bindings": ["role1", "role2"]}' "https://localhost:9443/t/wso2.com/api/identity/oauth2/v1.0/scopes" -v -k`

Response will be
`{"code":"41004","message":"Conflict","description":"Scope with the name profile already exists in the system. Please use a different scope name."}`

2. Send the following scope listing request.
`curl -X GET -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type: application/json" "https://localhost:9443/t/wso2.com/api/identity/oauth2/v1.0/scopes/name/profile" -v -k`

Response will be
`{"code":"41003","message":"Not Found","description":"Scope profile is not found."}
`
[1] https://is.docs.wso2.com/en/latest/develop/oauth2-scope-management-rest-apis/

**Expected behavior:**
The existing scope should be returned for the request 2.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-5.11.0-alpha]
 - OS: [Linux]
 - Database: [Postgres]
 - Userstore: [JDBC]

---

**Comment by janakamarasena** [comment]
Possible reason. "profile" is a OIDC scope. IIRC from IS-5.10.0 onwards we cannot have the same scope name for oidc and oauth scopes. Chances are if you use oidc scope API to retrieve the "profile" scope you will get it. It could be that the oauth scope API is sending the error response because of the mentioned constraint.
