### ISSUE TITLE
Error during the server startup in windows environment

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9675]
**Describe the issue:**

The following error occurs during the WSO2-5.11.0-alpha3 server startup in the Windows environment.
<img width="1280" alt="Capture3" src="https://user-images.githubusercontent.com/25483865/95168289-b538fb80-07ce-11eb-9dec-771df782cc2f.PNG">

```
[2020-10-05 21:58:40,105] [] ERROR {org.wso2.carbon.identity.remotefetch.core.internal.RemoteFetchServiceComponent} - Error parsing RemoteFetchCoreConfiguration, Core disabled org.wso2.carbon.identity.remotefetch.common.exceptions.RemoteFetchCoreException: Not a valid WorkingDirectory for RemoteFetchCore
```
**How to reproduce:**

1. Get wso2 IS- 5.11.0 -alpah3 pack.
2. Start the server in windows environment using `wso2server.bat` command

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 - alpha3
 - OS: Windows
 - Database:  H2, postgres
 - Userstore: LDAP, JDBC

**Comment by gurupriyat** [comment]
Is the issue sorted? Having this issue in server start up would cause any issue while using wso2 IS?

**Comment by ashendes** [comment]
> Is the issue sorted? Having this issue in server start up would cause any issue while using wso2 IS?

We are still looking into this issue. We'll update you soon regarding its status.
