### ISSUE TITLE
Improve the Postman collection for IDP Rest API

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9677]
**Is your suggestion related to a missing or misleading document? Please describe.**
The samples are incomplete in the existing [postman collection](https://is.docs.wso2.com/en/5.11.0/develop/idp-rest-api/) and misleading.

ex: Some sample values are not defined, defined sample values are not meaningful
![image](https://user-images.githubusercontent.com/5061791/95172039-655d3300-07d4-11eb-91e9-d117bab9eb5c.png)

**Describe the improvement**
- Update the postman collection with proper sample values.
---

**Comment by sherenewso2** [comment]
Closing this since templates mgt has been deprecated now. Please reopen if necessary.
