### ISSUE TITLE
User association REST API throws an error when a linked user account is removed

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9679]
**Describe the issue:**
When a user account is linked to an account and then removed, the `api/users/v1/me/associations` API is throwing an error saying `Error while getting associations of user: admin@carbon.super`.

**How to reproduce:**
1. Create a user account (User A).
2. Link that user account to another user account. (User A -> User B)
3. Delete User A. 
4. Try querying the `api/users/v1/me/associations` endpoint for User B.

You get an error.
**Expected behavior:**
When a user account is removed, the associations should also be removed. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 alpha2

**Not removing the associations can also result in a new user account created with the same username being automatically linked to a previously linked account. This can be a security issue.**

**Comment by sachiniWettasinghe** [comment]
Tested with IS 5.11.0 Beta 2 and cannot reproduce the issue. Hence closing the issue.
