### ISSUE TITLE
Account recovery and MFA features in the My Account app should be rendered based on the tenant preference

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9684]
**Is your feature request related to a problem? Please describe.**
Right now, the security questions section is shown to the users irrespective of whether or not security questions have been enabled by the admin. In case of this feature being disabled by the admin, showing this section in the UI is redundant. 

In addition, the Multi-factor Authentication section is also shown to the user even if it is disabled by the admin.

Ideally, these sections should be shown to the user only if these are enabled by the administrator. Currently, there is no API to get such information from. 

**Describe the solution you would prefer**

- [ ] There should be a meta endpoint that the My Account app can query to see if security questions, TOTP, FIDO, and SMS/Email recovery are enabled. 
- [ ] Configuration for Security questions in the My account should be only visible when it's enabled for the tenant
- [ ] TOTP Set-up wizard should be only visible when it's enabled for the tenant for its applications that are accessible by the user
- [ ] FIDO Set-up wizard should be only visible when it's enabled for the tenant for its applications that are accessible by the user
- [ ] SMS and Email recovery options Set-up wizard should be only visible when it's enabled for the tenant 

Related to #9572

**Comment by nilasini** [comment]
API to retrieve information related to account recovery has been done. Progress can be seen through \[1]
\[1] https://github.com/wso2/product-is/issues/9895

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
