### ISSUE TITLE
An API endpoint to get information regarding the age of a user's password

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9685]
**Is your feature request related to a problem? Please describe.**
Related to #9572 

To improve the UX of the My Account app, it is important that we let the user know how secure their account is on the overview page. Since it is a good practice to change the user password frequently, it will be better if we can remind the user to change their password after a certain amount of time. 

To that end, we need to know how long it has been since the password was updated. 

**Describe the solution you would prefer**
There should be an API endpoint to give details such as when the password was last updated.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
