### ISSUE TITLE
Consents purpose at authentication is not working

### ISSUE THREAD

**Issue by geve82** [wso2/product-is#9688]
**Describe the issue:**
Consent purpose during authentication is not displayed.

**How to reproduce:**
1. Configure Consent purposes in carbon console
2. add an application with ask consents enabled and claims needed (optional or mandatory)

only the traditional oidc scope consent screen is displayed.

**Expected behavior:**
Display the consent screen with purposes for the user to be compliant with GDPR, CCPA, etc.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.10.0, IS 5.11.0-alpha3

---

### Optional Fields

**Related issues:**
N/A
**Suggested labels:**
N/A

**Comment by omindu** [comment]
Hi @geve82 

The consent purposes defined from carbon console are for consent capturing during user registration scenarios. Identity server currently do not have the support for managing application-side consent requirement. If this is to be implemented at the identity server side, it will require customizing the authentication flow. You also have the option to handle it at the application side and can use the product's rest API to manage application side consents
