### ISSUE TITLE
Incorrect Certificate thumbprint algorithm used in OAuth2Util in identity-inbound-auth-oauth

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-is#9689]
**Describe the issue:**
SHA-1 algorithm has been used in IS 5.7.0 and older versions for calculating the certificate thumbprint in oauth related components. This has been changed to SHA-256 in newest IS releases ( 5.10.0 etc). In IS 5.11.0, this has changed back to SHA-1 mistakenly

**How to reproduce:**
Start the server and check the JWKS URL (https://localhost:9443/oauth2/jwks)

**Expected behavior:**
SHA-256 thumbprint in KID and other places

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0

**Comment by pulasthi7** [comment]
Hi @dimuthnc 

Can we close this issue now?
