### ISSUE TITLE
Improve the Postman collection for Script Libraries REST API

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9690]
**Is your suggestion related to a missing or misleading document? Please describe.**

The samples are incomplete in the existing [postman collection](https://is.docs.wso2.com/en/latest/develop/script-library-rest-api/#/Script%20Libraries/).

eg: No sample values given. Only data type (eg: <string>) is mentioned as values. 
<img width="955" alt="sample_not_configured" src="https://user-images.githubusercontent.com/25483865/95214236-8c037580-07a4-11eb-8f03-9dce6e670b70.PNG">

**Describe the improvement:**
Update the postman collection with proper sample values.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
