### ISSUE TITLE
Unwanted permissions and scopes to retrieve public certificcate

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9691]
**Is your suggestion related to a missing or misleading document? Please describe.**
To retrieve the public certificate no permissions/ scope required. (i.e : GET request to /keystores/certs/public endpoint doesn't need to authenticated or authorized)
Relevant config in identity.xml:
`<Resource http-method="GET" secured="false" context="(.*)/api/server/v1/keystores/certs/public(.*)"/>` 
  
but the documentation says some permissions and scopes are required. https://is.docs.wso2.com/en/latest/develop/keystore-rest-api/#/Certificates/getPublicCertificate

**Describe the improvement**
Mention no permission/ scope required for GET request to /keystores/certs/public endpoint

---

**Comment by sherenewso2** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2144
