### ISSUE TITLE
SMS OTP page not loading with tenant qualified url

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9696]
**Describe the issue:**

Enable enable_tenant_qualified_urls to true through deployment.toml file.
1. Once configured the sms otp after the basic authentication redirecting to the following page.
![smsotp](https://user-images.githubusercontent.com/20336761/95295342-85ecc200-0894-11eb-92fe-a027d9bdfda4.png)

**How to reproduce:**
1. Configure SMS OTP as an identity provider
2. Create a service provider and configure OIDC protocol with a basic authenticator as 1st step and SMS OTP as the second step
3. Call the URL https://localhost:9443/t/wso2.com/oauth2/authorize?response_type=code&client_id=3JFfniMvG4b5SsebzMoFXb0ftLoa&redirect_uri=http://wso2is.local:8080/playground2/oauth2client&scope=openid. You should change the parameters according to your configuration.
4. Basic authentication will be shown. Once enter the correct credential you will be redirected to the above page mentioned in the description. 

**Expected behavior:**
Successfully redirected to the SMS OTP page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0-alpha]
 - OS: [Linux]
 - Database: [Postgres]
 - Userstore: [JDBC]

---

**Comment by mefarazath** [comment]
The initial issue of not redirecting to the SMS OTP page is fixed. There are few more improvements to make the SMS OTP connector fully functional with the tenant-qualified URL mode. 

These are tracked with https://github.com/wso2/product-is/issues/10947
