### ISSUE TITLE
IdentityManagementEndpointUtil.encodeURL() error

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#9707]
**Description:**
if the callbackURL contains # the mechanism does not work correctly and parameters are lost from the callback resulting in errors on the frontend

**Affected Product Version:**
WSO2IS 5.9.0

**Steps to reproduce:**
Configure a SAML SP that signs the authentication request, go to the service and instead of a login do a self-registration, after the confirmation the user is redirected to an empty login form. The information from the callback URL is lost, remaining values until # .
login.do?SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more&RelayState=ss%3Amem%3A00e50efd94477382c506d2f88bb114316364caaacb3d825dce3a15729b949d28
instead of
login.do?
RelayState=ss%3Amem%3A00e50efd94477382c506d2f88bb114316364caaacb3d825dce3a15729b949d28&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=COACyAz6E1wYo4CvIJk3PrkwglkGuplBfpPkD6xxUe1y8cmHbWtuVKL%2FtSrqrazxGYeUw4pQjYsIUut%2BxfkfuoCzyM4vY9OKCMasjay4a8qykkZR%2BtYwSbXiT%2Felqivbx7AYn407172GdE6OQUSV94YL8qJnJPjBJBEhlElOBtr8xhU3CiW1Re2XXkDUribK7dbhX%2FzHHH5bLCoayDX1VRwR4XRZX62LRoza%2BJW9YoMJQYEybWooLNp9jzbQj2e5UJqlr1q6dJ4c2bPdEYqbx%2BDmpEwfP73YCIxVcQlr3UzQBfbxSPCu%2BECo0RTeLwcdO49Svb%2B%2FtgjwEklnJ%2B8aTA%3D%3D&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=4ebb3118-653f-4591-bbd0-072c9feada72&relyingParty=https%3A%2F%2Ftest%2Fshibboleth&type=samlsso&sp=test&isSaaSApp=false&
authenticators=BasicAuthenticator%3ALOCAL%3ALOCAL

if the Signature is removed the workflow looks correctly

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
