### ISSUE TITLE
Getting an Error Message and missing element when configure Primary user store as DB2

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9709]
**Describe the issue:**
There is an Error message retrieve when try to click on "Users" in side panel Console > Manage
Also, there are UI elements are missing when configuring DB2 as a Primary User store. 

The same error received while accessing Role in the left side panel in Console > Manage. (5.11.0 beta2 Snapshot)> Only issue get with superuser, there is no. issue with the role, in tenant admin

**How to reproduce:**
Configure deployment.toml and put JDBC driver for the version <IS_HOME>/repository/components/lib folder 
Start the IS server

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 alpha4 Snapshot
 - OS: Windows & Mac
 - Database: DB2 (DB2 v11.5.4.0)
 - Userstore: JDBC

```[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:db2://localhost:50000/alpha33"
username = "db2inst1"
password = "wso2carbon"
driver = "com.ibm.db2.jcc.DB2Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1 FROM SYSIBM.SYSDUMMY1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]

url = "jdbc:db2://localhost:50000/alpha33"
username = "db2inst1"
password = "wso2carbon"
driver = "com.ibm.db2.jcc.DB2Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1 FROM SYSIBM.SYSDUMMY1"
validationInterval="30000"
defaultAutoCommit=false
```

![image](https://user-images.githubusercontent.com/39120228/95387572-8629a380-090e-11eb-9656-b08dc4132c69.png)

![image](https://user-images.githubusercontent.com/39120228/95387895-0c45ea00-090f-11eb-9b47-c7896a792a2d.png)

Identified in beta2 SNAPSHOT
![image](https://user-images.githubusercontent.com/39120228/95714637-23c20180-0c86-11eb-9736-28ea1667a975.png)

**Comment by somindatommy** [comment]
Will be fixed with https://github.com/wso2/carbon-kernel/pull/2818
