### ISSUE TITLE
Review console content

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#9713]
We need to review the content in the new console so that we can avoid grammar and spelling mistakes in the application. Following are the sections that need to be reviewed.

**Develop View**

- [ ] Application management

- [ ] IDP management

**Manage View**

- [ ] Users/Groups/Roles management

- [ ] Userstore management

- [ ] Certificate management

- [ ] Attribute management

- [ ] Server configurations

**Comment by NipuniBhagya** [comment]
Hi @gomathyk, @sherenewso2 we would really appreciate it if you can help us out to review the content in these sections.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
