### ISSUE TITLE
Need an expert mode Application Template in Console

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9715]
**Is your feature request related to a problem? Please describe.**
If a user needs to add a protocol like Passive STS & WS-Trust, they have to create an Application with an unrelated protocol and then add the desired protocol at the edit page.

**Describe the solution you would prefer**
Create an expert mode application template that has no protocol configured so that user's are free to add whatever the protocol at the edit page.

**Additional context**
This template was previously there and would be able to retrieve if an older git tag is inspected.

**Comment by pulasthi7** [comment]
@brionmario ,

Framework version was updated in Identity apps. Please check if this can be closed?
