### ISSUE TITLE
Error while storing Application session data in the database.

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#9716]
**Describe the issue:**
Error while storing Application session data in the database. 
Error in performing Database query: '%s'INSERT INTO IDN_AUTH_SESSION_APP_INFO(SESSION_ID,SUBJECT,APP_ID,INBOUND_AUTH_TYPE)VALUES (?,?,?,?) 
org.postgresql.util.PSQLException: ERROR: value too long for type character varying(100)

**How to reproduce:**
The Shibboleth IdP has been configured as a federated authenticator and trying a login the above error happens.

**Expected behavior:**
A successful authentication

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.9.0
 - OS: Linux, Mac
 - Database: PostgreSQL 11

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
