### ISSUE TITLE
custom claims not return in userinfo endpoint

### ISSUE THREAD

**Issue by Kanapriya** [wso2/product-is#9718]
**Describe the issue:**
In the wso2 identity server, 5.10.0 WUM updated pack, the added custom claims to the JWT token using the Default Token Issuer is returned in the response of token endpoint but not in userinfo endpoint.

In the fresh pack, it is working as expected.

**How to reproduce:**

- Create a secondary user store  (UniqueIdJDBC)
- Create a custom local claim called http://wso2.org/claims/nationality.
- Create a custom OIDC claim (Add External Claim) by mapped the above created local claim. Give External Claim Uri as 'nationality'
- Add a custom claim to ID token (Select the claim 'nationality' from the drop-down menu while Add OIDC Claim)
- Configure OAuth/OpenID Connect and configure the claim configurations with the created local claim as Requested Claims and mark it as Mandatory Claim
- Create a user in secondary user store and have value for the custom claim.
- Invoke the token endpoint with created OIDC scope (say sample)

> curl -u <client id>:<client secret> -k -d "grant_type=password&username=<username>&password=<password>" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/oauth2/token?scope=openid+sample
- Invoke the userinfo endpoint

> curl --location --request GET 'https://localhost:944/oauth2/userinfo?scope=openid+sample' \
> --header 'Authorization: Bearer access_token'

This will return the response as follows:
{
    "sub": "MYSQL/alex123@carbon.super"
}

**Expected behavior:**

It should return the custom claim as well
{
    "nationality": "SL",
    "sub": "MYSQL/alex123@carbon.super"
}

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
5.10.0 latest wum pack
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by rksk** [comment]
This issue has been introduced with the fix for https://github.com/wso2/product-is/issues/8217

```
username = accessTokenDO.getAuthzUser().getUserName();
...
Map<String, String> userClaims = userstore.getUserClaimValues(MultitenantUtils.getTenantAwareUsername
                (username), claimURIList.toArray(new String[claimURIList.size()]), null);
```
We have not used the fully qualified username here and it always tired to fetch user claims from the primary domain.

**Comment by pamodaaw** [comment]
Fixed with 
* https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1396
* https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1405
