### ISSUE TITLE
Updated information are not saved in OIDC Application > Access Tab > Protocol

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9719]
**Describe the issue:**
After creating an OIDC application and updating any details in the Access tab> Protocol, those updated values ​​will not be saved.
Ex: checked password grant type or add Redirect URLs, even update those values, will not be saved.
Issue 2: After updating the information in the Accessibility tab> Protocol, there is no success or error message while clicking the "Update" button

**How to reproduce:**
Login to Console
2. Create an OIDC application 
3. Update information  Access tab> Protocol

**Expected behavior:**
Updated information should be saved

There should be a proper message that the user can get information was saved.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 alpha4 Snapshot
 - OS: Windows,  Mac
 - Database:DB2, H2
 - Userstore:  LDAP, JDBC
- Browser- Google chrome, Firefox
---

**Comment by thivi** [comment]
This may be due to the `Allowed Origins` field not being filled. When you try to update without filling this field, a validation error is shown and update won't take place. Can you check if this is the case?
