### ISSUE TITLE
Identity Verification with Idemia

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#9720]
### Description
Identity verification has become more and more important with online systems, especially with the new normal of working from home. The main goal of identity verification is to make sure the online users who interact with a system, are actually who they claim to be. There are multinational companies in the world that provide identity verification as a service and the goal of this project is to integrate two of those highly recognized companies with WSO2 Identity Server. These companies have a strong base on biometric-based identity verification and capabilities to verify on government-issued identities being trendsetters in the domain. We already have a working [connector](https://store.wso2.com/store/assets/isconnector/details/1a85a226-177c-4a90-8da3-b142c46ae658) that verifies the identity of self-registered users using [EvidentID](https://www.evidentid.com/) verification services. Similarly, we need to develop another connector that can verify user identities with [Idemia](https://www.idemia.com).

![image](https://user-images.githubusercontent.com/9441136/95444450-71cfc000-097b-11eb-8e54-405c046f14bd.png)

### Deliverables
- [x] Connector for IDEMIA Identity Verification.
- [ ] Connector for IDEMIA based Biometric Authentication.
- [x] Documentation.
- [ ] Article/Blogs/Screencasts.

### Learning Materials: 
- https://www.evidentid.com/
- https://www.idemia.com 
- https://is.docs.wso2.com/en/5.10.0/learn/self-registration-and-account-confirmation/
- https://is.docs.wso2.com/en/5.10.0/learn/creating-users-using-the-ask-password-option/
- https://everything1know.wordpress.com/2020/06/03/identity-verification-with-wso2-identity-server-and-evident-id/
- https://github.com/wso2-extensions/identity-verification-evident/tree/v1.0.0/docs

**Comment by EANimesha** [comment]
I'm working on this

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
