### ISSUE TITLE
[SCIM2][Search Users] Unable to retrieve users with uppercase character in userName when CaseInsensitiveUsername is enabled

### ISSUE THREAD

**Issue by numxgi** [wso2/product-is#9724]
**Describe the issue:**
Call to SCIM2 Search Users endpoint (/Users/.search) does not return users that contain uppercase characters in the userName when a filter is set on the userName with the following configuration :
- User Store : org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager
- CaseInsensitiveUsername enabled (in the user store configuration)

(https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/#/Users%20Endpoint/getUsersByPost)

This behavior seems to be due to the method org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.getQueryString() which applies the LOWER function only on the searched value but not on the UM_USER_NAME field in the query.

https://github.com/wso2/carbon-kernel/blob/9b1a0081d325bc7c509108ca24c83484f9b4835b/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L3447

**How to reproduce:**
- Configure a JDBC user store with CaseInsensitiveUsername enabled
- Create a user "UserTest" on this domain that containing uppercase characters in its username
- Search for users that contain "Test" in the username via SCIM2 API.

Ex : 
POST https://<wso2_url>/t/<tenant_id>/scim2/Users/.search (with Authorization header info)
Request body :
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "attributes": [
        "userName"
    ],
    "filter": "userName co Test",
    "domain": "TST",
    "startIndex": 1,
    "count": 100
}
```

**Expected behavior:**
The user "UserTest" should be retrieved by this search.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: PostgreSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
