### ISSUE TITLE
Requirement to add seperate store for approved scope and requested Scope in TokenRequestMessageContext.

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/product-is#9734]
A new config is been introduced to pass set of scopes as approved/allowed scopes which will be provided based on the request without any validation. The above scopes should not be validated by any scope validators and it will be directly set into the approved scopes list without any validation. But the absence of a separate store for approved scopes in the token request message context is an issue which prevents doing it. Even though there are many other alternatives to do the same , they were avoided due to various other issues.

So for now after discussion with the team IS , we have decided to the reading and setting of allowed scopes in the implementation level of global scope validators and set it to the request message context at the global scope validation level. The reading and setting of approved scopes will be moved to identity component level once this issue is fix.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
