### ISSUE TITLE
Error while retreiving the certificate with an alias which contains "#" symbol

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9736]
**Describe the issue:**
It is allowed to add a certificate with an alias which contains "#" symbol, via console app / REST API (`/keystores/certs`) successfully. It will return in the certificate list also, but viewing the particular certificate gives an error as follows. `GET /keystores/certs/{alias} `request doesn't take the correct alias because "#" is considered as a termination in the URI. 
In the following image, I have added a cert with the alias "b#$2", when click on that eye icon to view the certificate it gives an error as "There exists no certificate with alias: b".
<img width="1069" alt="certname with #" src="https://user-images.githubusercontent.com/25483865/95546205-d2c7ba00-09b4-11eb-9810-a9cb4a1b49e1.PNG">

**How to reproduce:**

1. Add a new certificate with an alias which contains "#"symbol via console app or REST API (`/keystores/certs`) (for non super tenant).
2.  Retrieve all certificates `GET /keystores/certs` or list out all certificate using console app.
3. Try to get the added certificate.

- in postman:  `GET /keystores/certs/{alias} `
- in console app: click on the eye icon of the specific cert

**Expected behavior:**
Validate the alias before adding a certificate. 
If special characters are allowed use URL encoded alias name when retrieving the cert by alias.
If the certificate is listed and unable to view the certificate is not expected.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.)-Alpha3
 - OS: Windows
 - Database: Postgresql
 - Userstore: JDBC

**Comment by DinikaSen** [comment]
The special characters such as # should be allowed in the alias because when adding a cert from the management console, the alias will the the file name. Hence this need to be handled from the console side by encoding the alias so that it is safe in URL.
