### ISSUE TITLE
Wrong postman collection is exporting for claim management

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9737]
**Is your suggestion related to a missing or misleading document? Please describe.**
Click on the button "Run in postman" in https://is.docs.wso2.com/en/latest/develop/claim-management-rest-api/ page. It gives the "Challenge Question"postman collection.

![imageedit_5_4746084671](https://user-images.githubusercontent.com/25483865/95548982-1b827180-09bb-11eb-8036-08c1724d6f61.png)

**Describe the improvement**
Do required changes to get the correct postman collection.

**Comment by nilminiwso2** [comment]
Will handle this from https://github.com/wso2/product-is/issues/10885
