### ISSUE TITLE
The token binding validating configuration should be checked before validation

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#9739]
**Describe the issue:**
Currently, an improvement has been done for configuring token binding validation per service provider.
But before validating the token binding value, it should check whether the token binding validation configuration is enabled in the SP.

**Environment information**
 - Product Version: IS 5.10.0

**Related issues:**
#9355

**Comment by emswbandara** [comment]
@pamodaaw can we close this since the public PR is merged?
