### ISSUE TITLE
getting 201 status code for Element Already Exists  - Challenge Questions /me/challenge-answers/{challenge-set-id}

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9740]
**Describe the issue:**
Obtain status Code 201 for POST Request - Answers a specific new challenge that already exists. (Challenge Questions /me/challenge-answers/{challenge-set-id})

**How to reproduce:**

curl -X POST "https://localhost:9443/t/carbon.super/api/users/v1/me/challenge-answers/challengeQuestion2" -H "accept: application/json" -H "authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d "{ \"challengeQuestion\": { \"locale\": \"en_US\", \"question\": \"Favorite sport ?\", \"questionId\": \"question4\" }, \"answer\": \"Cycling\"}"
**Expected behavior:**
Status  Code should be  409 for POST Request - Answers a specific new challenge that already exists.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11. alpha4 Snapshot
 - OS: Windows, Mac
 - Database: DB2, H2
 - Userstore: LDAP, JDBC

---

**Comment by sachiniWettasinghe** [comment]
Tested with a wso2is-5.11.0-beta4-SNAPSHOT and the issue could not be reproduced. @NilukaSripalim could you please verify?

**Comment by NilukaSripalim** [comment]
Re-test with 5.11  Beta4, it works as expected ,

![image](https://user-images.githubusercontent.com/39120228/97981455-56c86280-1df8-11eb-8c55-518025e34a6f.png)
