### ISSUE TITLE
The `required` meta attribute of some of the userstore attributes are set to false even though they are required

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9741]
**Describe the issue:**
Some of the userstore properties' `required` meta attribute is set to `false` though these properties are required. This is producing issues such as this #9627.

Here, the membership attribute property's `required` attribute is set to false but when sending a request without this attribute causes an error in the backend.

**Comment by thanujalk** [comment]
@thivi do you have a list of those?

**Comment by thivi** [comment]
I don't have a list of those. But membership attribute is one of those attributes.  https://github.com/wso2/product-is/issues/9627#issuecomment-702593180

**Comment by ChamathNS** [comment]
Migara is working on this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
