### ISSUE TITLE
Kerberos grant always add the userstore and tenant domain to the subject identifier

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9745]
**Describe the issue:**
The following configurations of the service provider are not honored in the Kerberos grant. It always adds the userstore and tenant domain to the subject identifier
- Use tenant domain in local subject identifier
- Use user store domain in local subject identifier

This can be fixed by setting the AuthenticatedSubjectIdentifier as below at [1]. setAuthenticatedSubjectIdentifier() will set the subject by considering the above two configurations.
```
kerberosUser.setAuthenticatedSubjectIdentifier(kerberosUser.getUserName(), serviceProvider);
```

[1] https://github.com/wso2-extensions/identity-oauth2-grant-kerberos/blob/master/src/main/java/org/wso2/carbon/identity/oauth2/grant/kerberos/KerberosGrant.java#L230-L232

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
