### ISSUE TITLE
ClientIdValidationRegex is not configurable via deployment.toml

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9746]
**Describe the issue:**
ClientIdValidationRegex can be defined under the OAuth tag in the identity.xml. This is useful when defining own client-ids via DCR endpoint.

The current default value is `[a-zA-Z0-9_]{15,30}` and if we pass a client id which is not matching with this regex, we get the following response for DCR.
```
{"error":"invalid_client_metadata","error_description":"Provided client id is not adhering to the provided regex [a-zA-Z0-9_]{15,30}"}
```

**Environment information**
 - Product Version: IS 5.10.0

**Comment by emswbandara** [comment]
@mevan-karu let's link the docs-is PRs to this issue.

**Comment by mifrazmurthaja** [comment]
This issue exists on IS 5.11 as well.
