### ISSUE TITLE
Avoid internal calls being routed through LB

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9752]
**Is your suggestion related to a missing or misleading document? Please describe.**
The following note in the document [1] about $subject is incomplete.
```
This hostname is used by the WSO2 Identity Server cluster and therefore it must be specified in the /etc/hosts file in each node so that internal calls will not be routed through the Load Balancer.

Example: 192.168.2.1 wso2.is
```
If we just do this only, all the internal calls will start to break because it will call internal calls via port 443 which is wrong/

**Describe the improvement**
We have to configure all the web apps (including the dashboard in 5.9.0) to use 9443 port for internal calls.

[1] https://is.docs.wso2.com/en/latest/setup/deployment-guide/

**Comment by rksk** [comment]
Goto {IS_HOME}/repository/conf/deployment.toml and add following lines.
```
[identity.auth_framework.endpoint]
identity_server_service_url = "https://$ref{server.hostname}:9443/services"
```

For 5.9.0, the following changes are also required.
```
"serviceOrigin" : "${carbon.protocol}://${carbon.host}:9443"
```
Change the "serviceOrigin" value as above in the following two files.
{IS_HOME}/repository/deployment/server/jaggeryapps/dashboard/conf/site.json
{IS_HOME}/repository/deployment/server/jaggeryapps/portal/conf/site.json

**Comment by rksk** [comment]
This depends on https://github.com/wso2/product-is/issues/9778, the doc can not be updated until it is fixed

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
