### ISSUE TITLE
Develop a SCIM JavaScript SDK to parse, validate and update user profile information

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9753]
Since SCIM is a standard, developing a JavaScript SDK will help deal with user profile information in frontend applications. Even in our My Account and Console application, we have the code for the profile duplicated. If we can develop an SDK, then we can use it across our applications to handle user profile information. This will also be beneficial to customers who use our products.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
