### ISSUE TITLE
Multiple Notification Channel Support for User Account Suspension

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9756]
# Description
The system can be configured to lock a user account after a user account being idle for a predefined period of time. In this scenario, the user will be notified via the preferred communication channel for that user.

# Requirement
According to the current implementation, the Identity server can only send email notifications. But there can be a requirement, where the user prefers to receive a notification via an SMS.

## User Narrative

- User registers an account.
- No login activity for a defined period of time.
- User account gets locked after the allowed idle account timeout.
- The user will be notified via the preferred communication channel if available.
   - If only the email is available for the user, notify over email.
   - If only the mobile is available for the user, notify over SMS.
   - If both the email and the mobile is available, 
     - and if a preferred communication channel is set, notify over the preferred communication channel.
     - and if a preferred communication channel is not set, notify over the server default notification channel.

Related to https://github.com/wso2/product-is/issues/9754

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
