### ISSUE TITLE
Multiple Notification Channel Support for onboarding users with Email/SMS-based account verification and ask password

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9757]
# Description
In enterprises, the Identity/IT admin can manually create and add users to the system. For enterprise scenarios, the most preferred approach is to create a user by an IT admin with the ask password option. In this scenario, the identity admin will initiate a verification link for the user's enterprise email so that the user can set his password at some point later by clicking the verification link received to his enterprise email.

# Requirement
Allow IT admin to send the account confirmation link via an SMS or EMAIL. According to the current capabilities, this is only available via Email.

## User Narrative
- Identity/IT Admin navigate to the management console.
- Click **Add** in the Main tab under **User and Roles** and select **Add New User**. 
- Identity/IT Admin selects the Ask Password option.
- Enter the enterprise email address of the user.
- User will be notified with a verification link.
- The user clicks the link.
- System verifies the user and prompts for a password reset.
- The user sets the password.

Related to https://github.com/wso2/product-is/issues/9754

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
