### ISSUE TITLE
Multiple Notification Channel Support for Forced Password Reset with OTP

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9758]
# Description
The Identity/IT admin can initiate a password reset for all the users or a particular user if there is a specific need. Following two scenarios are available for the IT Admin.
- Password Reset via Recovery Email
- Password Reset via OTP > via SMS is not supported.

# **Requirement for Password Reset via OTP**
When this option is selected the IT admin should have the capability to select the notification send channel. Admin should have the following options.

- Notify with SMS
- Notify with Email
- Notify according to user preference.

If admin selects 3rd option, the recovery OTP will be sent via the preferred communication channel of the user.i.e,

- If only email is available for the user, send an email OTP.
- If only mobile is available for the user, send an SMS OTP.
- If both email and mobile is available, check if user has a notification preference set and use that preference to send the    - If both the email and the mobile is available, 
     - and if a preferred communication channel is set, notify over the preferred communication channel.
     - and if a preferred communication channel is not set, notify over the server default notification channel.

## User Narrative

- Identity/IT admin sets **_http://wso2.org/claims/identity/adminForcedPasswordReset_** of the user.
- The User receives an OTP (a temporary password) via email or SMS based on the communication channel preferred.
- Then the user uses the OTP in the login flow and reset the user account password.

Related to https://github.com/wso2/product-is/issues/9754

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
