### ISSUE TITLE
Multiple Notification Channel Support for admin initiated account lock.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9759]
# Description
The IT administrator can lock the account for security reasons and enterprise policies. In this case, a notification will be sent to the user via the preferred communication channel.

This requirement can be similar to https://github.com/wso2/product-is/issues/9755 and same solution might resolve the issue. 

# Requirement
According to the current implementation, the Identity server can only send email notifications. But there can be a requirement, where the user prefers to receive a notification via an SMS.

## User Narrative

- Identity/IT Admin sets **_http://wso2.org/claims/identity/accountLocked_** of the user.
- The user will be notified via the preferred communication channel if available.
   - If only the email is available for the user, notify over email.
   - If only the mobile is available for the user, notify over SMS.
   - If both the email and the mobile is available, 
     - and if a preferred communication channel is set, notify over the preferred communication channel.
     - and if a preferred communication channel is not set, notify over the server default notification channel.

Related to https://github.com/wso2/product-is/issues/9754

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
