### ISSUE TITLE
UI support for account recovery via multiple notification channels.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9761]
# Requirement 
The backend support for this requirement is already available and tracked in https://github.com/wso2/product-is/issues/6343. However, the front-end support is not available in the current product.

# Improvements needed
- Allow user to select the notification channel
- In the current product, during password recovery, only the username is requested as a claim to identify the user. There can be a requirement in to add additional claims such as ID, Birthday, mobile as additional claims.

# User Narrative
- A user navigates to the login page and click on forgot password.
- Then enters the required claims and click get notification.
- The user will be notified via the preferred communication channel if available.
   - If only the email is available for the user, notify over email.
   - If only the mobile is available for the user, notify over SMS.
   - If both the email and the mobile is available, 
     - and if a preferred communication channel is set, notify over the preferred communication channel.
     - and if a preferred communication channel is not set, notify over the server default notification channel.

Related to https://github.com/wso2/product-is/issues/9754

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
