### ISSUE TITLE
Scenario Tests Failing Single Sign on IS - 5.11.0 

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9764]
**Describe the issue:**

Test Case : ApplicationManagementTestCase#atEnd 

Error Log: java.lang.NullPointerException at org.wso2.identity.scenarios.test.ApplicationManagementTestCase.atEnd(ApplicationManagementTestCase.java:92)

Test Case: OIDCSSOTestCase#atEnd, OIDCSSOTestCase#testInit, DCRTestCase#registerOAuth2Application

Error Log: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | OIDCSSOTestCase#testInit

Test Case: TestPassiveSTS#atEnd

Error Log: 

java.lang.NullPointerException at org.wso2.identity.scenarios.sso.test.ws.fed.sts.TestPassiveSTS.atEnd(TestPassiveSTS.java:133)

Test Case: ApplicationManagementTestCase#testInit
Error Log: peer not authenticated

--

**Expected behavior:**
Tests should Pass 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS - 5.11 Beta ]
 - DBEngine: MySQL-5.7JDK: ADOPT_OPEN_JDK11OS: CentOS-7.5

---

**Comment by sachiniWettasinghe** [comment]
Resolved with https://github.com/wso2/product-is/pull/10494
