### ISSUE TITLE
Scenario Tests failing IS 5.11.0 access-delegation

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9765]
**Describe the issue:**
Test Case : OAuth2RefreshTokenAuthorizationGrantTest#atEnd

Error Log : 

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Test Case: OAuth2SelfContainedTokenPasswordGrantTest#atEnd

Error Log: 
java.lang.NullPointerException at org.wso2.identity.scenarios.access.delegation.oauth2.selfcontainedtoken.OAuth2SelfContainedTokenPasswordGrantTest.atEnd(OAuth2SelfContainedTokenPasswordGrantTest.java:127)

--

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS - 5.11.0 Beta ]
    DBEngine: MySQL-5.7JDK: ADOPT_OPEN_JDK11OS: CentOS-7.5
---

**Comment by sachiniWettasinghe** [comment]
Resolved with https://github.com/wso2/product-is/pull/10461
