### ISSUE TITLE
Scenario Tests failing IS - 5.11.0  manage-users-and-roles

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9766]
**Describe the issue:**

Test Case : ProvisionUserWithAllAttributesTestCase#cleanUp

Error Log: java.lang.NullPointerException at org.wso2.identity.scenarios.commons.util.IdentityScenarioUtil.getJSONFromResponse(IdentityScenarioUtil.java:207) at org.wso2.identity.scenarios.test.scim2.ProvisionUserWithAllAttributesTestCase.cleanUp(ProvisionUserWithAllAttributesTestCase.java:98)

Test Case: ProvisionUserSCIM2FullRequestTestCase#cleanUp

Error Log: java.lang.NullPointerException at org.wso2.identity.scenarios.commons.util.IdentityScenarioUtil.getJSONFromResponse(IdentityScenarioUtil.java:207) at org.wso2.identity.scenarios.test.scim2.ProvisionUserSCIM2FullRequestTestCase.cleanUp(ProvisionUserSCIM2FullRequestTestCase.java:206)

Test Case: UserProvisionWithInsufficientPrivilegesSCIM2TestCase#testInit

Error Log: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Test Case: ManageInternalRolesWithPermissionTestCase#testInit

Error Log: 

peer not authenticated

--

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
DBEngine: MySQL-5.7JDK: ADOPT_OPEN_JDK11OS: CentOS-7.5

---

**Comment by sachiniWettasinghe** [comment]
Resolved with https://github.com/wso2/product-is/pull/10461
