### ISSUE TITLE
Improve the user experience during userstore creation

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#9767]
It takes time after creating a userstore for the list to get updated. This leads to poor user experience. To improve it, a notification should be fired when the list gets updated. Also, a placeholder should be shown to let the user know that a userstore is being created.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
