### ISSUE TITLE
UUID generator and SMS OTP generator needs to be Configurable

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9773]
# Issue
In the current implementation, the OTP generation is hardcoded. The OTP patterns generated in EMAIL OTP, UUID, SMS OTP are hardcoded at the movement.

# Requirement
- [ ] Make the OTP patterns configurable by the Identity admin.
- [ ] Make to UUID generator and SMS OTP generator extended : https://github.com/wso2/product-is/issues/6446

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
