### ISSUE TITLE
Getting  DB2 SQL error in wso2is-5.11.0-beta2-SNAPSHOT/dbscripts/identity/db2.sql

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9774]
**Describe the issue:**
Error occurred during SQL script execution

Reason:
SQL Error [42831]: The column named "PROPERTY_NAME" cannot be a column of a primary key or unique key constraint because it can contain null values.. SQLCODE=-542, SQLSTATE=42831, DRIVER=4.9.78

```
CREATE TABLE IDN_USER_FUNCTIONALITY_PROPERTY (
	ID VARCHAR(255) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	TENANT_ID INTEGER NOT NULL,
	FUNCTIONALITY_ID VARCHAR(255) NOT NULL,
	PROPERTY_NAME VARCHAR(255),
	PROPERTY_VALUE VARCHAR(255),
	PRIMARY KEY (ID),
	CONSTRAINT IDN_USER_FUNCTIONALITY_PROPERTY_CONSTRAINT UNIQUE (USER_ID, TENANT_ID, FUNCTIONALITY_ID, PROPERTY_NAME)
)
;
```

**Comment by ChamathNS** [comment]
Duplicate of https://github.com/wso2/product-is/issues/9644.
