### ISSUE TITLE
Document support for account locking on invalid challenge question answer attempts

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9775]
**Is your suggestion related to a missing or misleading document? Please describe.**

Eventhough we mention about password recovery with challenge questions[1], we don't mention about the  account locking on invalid challenge question answer attempts

[1]https://is.docs.wso2.com/en/latest/learn/configuring-password-reset-with-challenge/#configuring-password-reset-with-challenge-questions

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
