### ISSUE TITLE
Redirect to a blank page when accessing Manage tab in Console

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9777]
**Describe the issue:**
When Manage tab in console app is clicked, it redirects to a blank page. `https://localhost:9443/console/manage/users` request makes the following error and it causes for the blank page.
This issue is produced when userstore is JDBC (postgres) and other DBs are also postreges. This issue is **not reproduced** in the 5.11.0-alpha3 milestone.
This issue is **not reproduced** in the default IS pack (userstore-LDAP and H2 DBs).

<img width="1280" alt="empty-page-users" src="https://user-images.githubusercontent.com/25483865/95716014-9b107a80-0c1f-11eb-8e7e-b845e59fdee9.PNG">
 

**How to reproduce:**

1. Log in to https://localhost:9443/console
2. Click on `Manage` Tab

**Expected behavior:**
View list of users.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta
 - OS: Windows, Linux
 - Database: Postgres
 - Userstore: JDBC

**Comment by Buddhimah** [comment]
Reproduced after migration in mysql https://github.com/wso2/product-is/issues/9790

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/product-is/issues/9790

**Comment by Buddhimah** [comment]
Closing as per above comment
