### ISSUE TITLE
Fitering users in some userstores cause to crash the page

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9779]
**Describe the issue:**
 Console app crashes and goes blank when listing users in some userstores

**How to reproduce:**
1. Refer to the attached [TEST.txt](https://github.com/wso2/product-is/files/5363660/TEST.txt)
2. Deploy it in a tenant as a secondary userstore
2. Login to console and browse users in this userstore

<img width="1440" alt="Screen Shot 2020-10-12 at 1 03 02 PM" src="https://user-images.githubusercontent.com/5061791/95719055-eb71f180-0c8c-11eb-9dd3-53224a5ca38e.png">
<img width="1440" alt="Screen Shot 2020-10-12 at 12 52 53 PM" src="https://user-images.githubusercontent.com/5061791/95719066-ee6ce200-0c8c-11eb-97ad-9d991a0b54c4.png">
- As shown in above images, user list is returned from the API

**Expected behavior:**
- users should be listed
- If there's an error, proper error message must be displayed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - OS: [Mac]
 - Database: [MySQL]
 - Userstore: [JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**
- This error could be user not having all the mandatory marked attributed in the profile.
- But there is a possibility that there are users in the system with minimum information such as username only, where the user is created from the management console.

**Comment by thivi** [comment]
Fixed by https://github.com/wso2/identity-apps/pull/1241
