### ISSUE TITLE
Missing information Add JDBC Userstore  wizard >  Summary secetion

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9780]
**Describe the issue:**
Missing information Add JDBC User store  wizard >  Summary section,  while creating Secondary JDBC user store there few added information is missing in the summary section, 

**How to reproduce:**
Login to Console > manage
Add user store > JDBC
Provide necessary information

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 Beta2 SNAPSHOT
 - OS:Windows, Mac]
 - Database: DB2
 - Userstore: JDBC

---
![image](https://user-images.githubusercontent.com/39120228/95721323-0bef7b00-0c90-11eb-8255-963350be0ccb.png)

**Comment by thivi** [comment]
Similar issue: https://github.com/wso2/product-is/issues/9881
Fixed by https://github.com/wso2/identity-apps/pull/1250
