### ISSUE TITLE
On board MySQL 8 to TestGrid

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9781]
**Is your suggestion related to an experience ? Please describe.**
Currently, Testgrid supports only MYSQL 5.7 but we are providing Mysql 8 as a compatible database type we should be able to onboard that to TestGrid.

**Comment by gnudeep** [comment]
IS 5.11 document already listed MySQL 8 as a supported database.

https://is.docs.wso2.com/en/5.11.0/setup/environment-compatibility/

**Comment by RidmiR** [comment]
This task is done and without any infrastructure failures, Tesgrid job is running successfully. But there are scenarios tests are getting failed from two scenarios. Should re-triggered the scenarios tests against MySQL 8 once those test issues got fixed. 

Linked Git issues as for reference. 
https://github.com/wso2/product-is/issues/9765
https://github.com/wso2/product-is/issues/9766
