### ISSUE TITLE
Onboard PostgreSQL 10.11 with IS 5.6.0 to Testgrid

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9783]
**Is your suggestion related to experience? Please describe.**
This is to check the compatibility of PostgreSQL 10.11 with IS 5.6.0. PostgreSQL 10.11 should be onboarded to Test grid. Currently, only Postgresql 10.5 is supported by Testgrid

**Comment by ashensw** [comment]
This task is completed.
