### ISSUE TITLE
Error messages is not prominent when an error occured while managing attribute dialects

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9789]
**Describe the issue:**
When a new attribute dialect is added with an existing Dialect name, user get stuck at the creation and error message is not prominent.

**How to reproduce:**
1. Create a new Attribute Dialect from the console with an existing dialect name.
![image](https://user-images.githubusercontent.com/5061791/95741896-bbd2e180-0cac-11eb-9576-c5a13650c6de.png)

**Expected behavior:**
2. User should be given an error that the dialect already exists.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - OS: [Mac]
- Database: [MySQL]
- Userstore: [JDBC]

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-apps/pull/1212
