### ISSUE TITLE
[Doc]Validate username API response code is wrong

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9793]
**Is your suggestion related to a missing or misleading document? Please describe.**
In doc [1] we have mentioned that validateusername response statuscode should be 0 if the username is available but the following username validation request returns 60000.

**Request**
`curl -k -v -X POST -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type: application/json" -d '{ "username": "mathu2222@wso2.com","properties": []}' "https://localhost:9443/t/wso2.com/api/identity/user/v1.0/validate-username`

**Response**
`{"statusCode":60000}
`

**Describe the improvement**
The response status code should be changed in the doc[1].

[1] https://docs.wso2.com/display/IS510/apidocs/self-registration/#!/operations#SelfRegister#validateUsernamePost

---

**Comment by gomathyk** [comment]
Modified-
https://docs.wso2.com/display/IS511/apidocs/self-registration/#!/operations#SelfRegister#validateUsernamePost
https://docs.wso2.com/display/IS510/apidocs/self-registration/#!/operations#SelfRegister#validateUsernamePost
