### ISSUE TITLE
Validate input fields when creating new claims

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9799]
**Describe the issue:**
It allows to create local claims without **displayName** or **Description** via REST APIs as well as Conole App.

**How to reproduce:**

**- Using Console**

1. Log into console and Navigate to `Manage` tab.
2. Click on Attribute Dialects , then click on the arrow to view Local Dialtect.
3. Click on new Local attribute.

- Name -> space
- Description -> space
- Attribute ID -> give a value

![Screenshot from 2020-10-12 15-45-39](https://user-images.githubusercontent.com/25483865/95758067-96060680-0cc5-11eb-9c94-d02e2935055a.png)

- Add suitable map attributes and Finish the process.

![Screenshot from 2020-10-12 15-45-46](https://user-images.githubusercontent.com/25483865/95758073-97373380-0cc5-11eb-9985-4d2ba0f48ab0.png)
![Screenshot from 2020-10-12 15-45-49](https://user-images.githubusercontent.com/25483865/95758079-98686080-0cc5-11eb-8711-89ff7aec9233.png)

- **Using REST API**

Either remove the displayName. description fields from the body or keep them empty.

`POST https://localhost:9443/t/{{tenant-domain}}/api/server/v1/claim-dialects/local/claims`
```
{
  "claimURI": "http://wso2.org/claims/test",
  "displayOrder": 10,
  "readOnly": true,
  "regEx": "^([a-zA-Z)$",
  "required": true,
  "supportedByDefault": true,
  "attributeMapping": [
    {
      "mappedAttribute": "username",
      "userstore": "PRIMARY"
    }
  ],
  "properties": [
    {
      "key": "string",
      "value": "string"
    }
  ]
}
```

**Expected behavior:**
Validate the claim name, and description (API/backend and UI level) before adding a new claim since they are marked as required in the UI.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta
 - OS: Windows, Linux
 - Database: H2, Postgres
 - Userstore: LDAP, JDBC

**Sub Issues**

- [ ] [Validate input fields when updating claims](https://github.com/wso2/product-is/issues/9810)

**Comment by thivi** [comment]
The UX issue has been resolved by https://github.com/wso2/identity-apps/pull/1250
