### ISSUE TITLE
Creating a new user with groups and roles assigned in one go fails

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9800]
**Describe the issue:**
![Screenshot from 2020-10-12 19-06-20](https://user-images.githubusercontent.com/791850/95761858-89d07800-0cca-11eb-973a-fe3817334862.png)

$subject generates an issue in the UI as in the above screen.
The issue is not reproducible in a local environment but in a cloud environment.

It seems a slight delay in user creation can fail the role or group assignment. 
No errors are logged.

@DimalChandrasiri please add if you have more information.

**Comment by brionmario** [comment]
Group assignment to an existing user is also not working properly in remotely hosted environments.

<img width="1580" alt="Screen Shot 2020-12-11 at 12 37 45 PM" src="https://user-images.githubusercontent.com/25959096/101873837-b2cb9700-3bad-11eb-9ba7-a898c54ffafa.png">

Even though no errors are shown the group is not assigned to the user in the UI.

/cc @DimalChandrasiri

**Comment by nilasini** [comment]
For scim group patch operation in the network tab, ccould see the response as the user is not in the user store. But when listing could able to see the user. This is not reproducible in 5.12.0 latest milestones. Only could able to reproduce in cloud environment.
