### ISSUE TITLE
501 not implemented response when search user ID by username

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9804]
**Describe the issue:**
In the document [1] we have mentioned the request and response for search user ID by username. But the following request gives 501 not implemented as the response.

`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json"  "https://localhost:9443/api/identity/user/v1.0/pi-info?username=admin" -v -k
`

[1] https://docs.wso2.com/display/IS510/apidocs/self-registration/#!/operations#UserExport#searchUserByName

**How to reproduce:**
Invoke the following request

`curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json"  "https://localhost:9443/api/identity/user/v1.0/pi-info?username=admin" -v -k
`

**Expected behavior:**
If the API not implemented the doc should be changed, if the API has been implemented need to check why 501 is returned and fixed it.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [5.11.0-alpha]
 - OS: [Linux]
 - Database: [Postgre]
 - Userstore: [JDBC]

---

**Comment by ayshsandu** [comment]
Will be implemented in the future.

**Comment by nilasini** [comment]
Created a doc issue[1] to fix the existing versions.

[1] https://github.com/wso2/product-is/issues/10720
