### ISSUE TITLE
Doc Feedback: Verify Permission of SCIM2 /Users endpoint POST method

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#9805]
Location : https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/

User Endpoint, Create User (POST /Users)  has Permission as 
   ` /permission/admin/manage/identity/usermgt/view`
But It need to be change as
`
    /permission/admin/manage/identity/usermgt/create
`

**Comment by sherenewso2** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2148
