### ISSUE TITLE
Doc Feedback:401 occured while using POST /Me endpoint of SCIM2 with scope internal_user_mgt_create

### ISSUE THREAD

**Issue by Thumimku** [wso2/product-is#9807]
Location : https://is.docs.wso2.com/en/latest/develop/scim2-rest-apis/
Steps to Reproduce:

- Get a JWT token using code grant with scope internal_user_mgt_create
- Use it to call POST /Me endpoint of SCIM2

Response :
- 401unauthorised but in doc says 
```
Permission required:
* /permission/admin/manage/identity/usermgt/create
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
