### ISSUE TITLE
Passive sts sample has some issue

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9812]
**Describe the issue:**
Once deploy the passivists sample and navigate to http://localhost:8080/PassiveSTSSampleApp?samlv=2-0 following screen has been shown.

![2](https://user-images.githubusercontent.com/20336761/95823593-83ceab80-0d4b-11eb-9e35-6754711ac61f.png)

**How to reproduce:**
Deploy passivestst as mentioned in [1] then navigate to http://localhost:8080/PassiveSTSSampleApp?samlv=2-0 as mentioned in [2]

[1] https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-passivestssampleapp-webapp
[2] https://is.docs.wso2.com/en/latest/learn/configuring-single-sign-on-wsfed/

You will see the above login page
**Expected behavior:**
Successfully redirected to the login page without console logs printed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
