### ISSUE TITLE
Regex is not getting validated for claims in SCIM API

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#9816]
In current implementation we cannot use regex validation with SCIM API. Regex validation will be only applied when doing operations via management console or user store level. Therefore we can perform operations on users via SCIM API with claim values which do not match regex validation we have defined in claim configurations.

**Comment by madurangasiriwardena** [comment]
There are 2 approaches to implement this functionality.

1. Add the validation of the claim with regex at the SCIM 2 API level
2. Add the validation at a lower level (before the user store manager) to have generic validators and propagate the validation errors to the SCIM API layers

From the above 2 approaches, the 2nd approach is the preferred one.

**Comment by AnuradhaSK** [comment]
Related issues: https://github.com/wso2/product-is/issues/9997

**Comment by rksk** [comment]
Addressed with https://github.com/wso2/product-is/issues/13174

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
