### ISSUE TITLE
User Templates for the console

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#9817]
**Describe the solution you would prefer**
- When the admin creates we can improve the user experience by letting him/her by having pre-defined user templates, template can include,
-- Groups
-- Roles
-- Common attributes (Ex: company, country)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
