### ISSUE TITLE
Carbon Console Deprication

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9820]
**Is your feature request related to a problem? Please describe.**
All the features available in the carbon console need to be catered by the new portals in order to deprecate the carbon console.

**Describe the solution you would prefer**
This issue tracks the remaining features we need to onboard to the new portals.

- [OIDC scope management](https://github.com/wso2/product-is/issues/9837)
- Adaptive Fn library
- Application-based permission management
- [XACML policy management UI + REST API](https://github.com/wso2/product-is/issues/9098)
- [Workflow Management UI + REST API](https://github.com/wso2/product-is/issues/9099)
- Consent Purpose Management
- Tenant Management
- [Handling browser back button and bookmarked login page (currently registry involved)](https://github.com/wso2/product-is/issues/5311)
- Force Password Reset
- Resident SP
- Resident IDP config

**REST API improvements**
- [Capability to update userstore domain name in /userstores API ](https://github.com/wso2/product-is/issues/7968)
- API to retrieve server realm Info in UserAdmin Service

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
