### ISSUE TITLE
Users are gving the "Recover with Security Questions" option in UI level, even if its disabled in  IDP Settings.

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#9822]
**Describe the issue:**
An user is seeing the "Recover with Security Questions" option, even if its disable in settings and if user click on it then as a result, user sees the error describing "Security questions based recovery is not enabled".
**How to reproduce:**

-  Goto Resident IDP, "Account Management Policies" -> "Account Recovery"

    

- Then set "Enable Security Question Based Password Recovery" to "False (UnChecked)"

   

-  Then try login to User-Portal and from login page click on "Forgot Password".

    

- This will open the "Recover Password" page with options for recovery ("Recover with Mail" and "Recover with Security Questions").

**Expected behavior:**
After disabling the option in resident IDP  configurations this option need not to be seen in the UI level. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0]

**Comment by mifrazmurthaja** [comment]
Related #10357

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
