### ISSUE TITLE
SAML federation with tenant qualified url not working roperly

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9823]
**Describe the issue:**
When using tenant qualified saml endpoints, during saml federation scenario secondary IS redirecting to non tenant qualified url as below.
![1](https://user-images.githubusercontent.com/20336761/95851251-98bd3600-0d6f-11eb-9063-8ec913a661b6.png)

**How to reproduce:**
1. Configure SAML SSO between two IS as mentioned in [1]. Duirng the configuration use all the saml and commonauth related urls as tenant qualified urls
2. Navigate to travelocity.com
3. You will be redirected to the URL mentioned in description

[1] https://docs.wso2.com/display/IS510/Login+to+the+Identity+Server+using+another+Identity+Server+-+SAML2#LogintotheIdentityServerusinganotherIdentityServer-SAML2-ConfiguringtheprimaryISasanSPinthesecondaryIS

**Expected behavior:** 
Users should be redirected to tenant qualified authentication endpoint.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0-alpha]
 - OS: [Linux]
 - Database: [Postgres]
 - Userstore: [JDBC]

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
