### ISSUE TITLE
Username recovery page is prompted in UI level even though Username recovery is not enabled in resident IDP configurations.

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#9825]
Users are prompted the "Recover Username" option, even if its disabled in resident IDP configurations and  if user click on it, let the user to fill everything as submit then as a result, user sees the error Username Recovery in not enabled.
**How to reproduce:**

    

- Goto Resident IDP, "Account Management Policies" -> "Account Recovery"

-  Then set "Enable Username Recovery" to "False (UnChecked)"

-  Then try login to User-Portal and from login page click on "Forgot Username".

-   This will open the "Recover Username" page with some user input fields to fill.

- Once user fills all fields and click submit, then it gives following error:
Error!
Username recovery is not enabled

**Expected behavior:**
When  disabled the username recovery option users should not prompted the username recovery page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0]

**Comment by mifrazmurthaja** [comment]
Related #10357

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
