### ISSUE TITLE
Last password update value is stored as a timestamp

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#9826]
**Describe the issue:**
The last password update identity claim is stored as a timestamp. But this should be in UTC format. https://github.com/wso2-support/identity-governance/pull/223/files#diff-691b8bd032a3997b497815f0de32e3bb5355fc0b2a3c168b8546348136b926ebR82.
Another thing to notice is that this claim was also used in the password policy authenticator. There also the value is stored as a timestamp. Need to fix both.

**How to reproduce:**
Perform a password update and observe the claim value.

**Expected behavior:**
The value should be in UTC format.

**Comment by ayshsandu** [comment]
@tharindu-bandara does this break any runtime flows?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
