### ISSUE TITLE
Git Integration for Adaptive Authentication Scripts

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9834]
**Problem definition**
The current way of adding or updating of the Adaptive Script for outbound authentication configuration for SP, to a particular environment is by doing that change manually through the `management console` or `console`. Most of the time the same Adaptive authentication script is used across multiple SPs in different tenants as well.

This is an error-prone approach and makes the configuration changes propagated through environments harder.

**Preferred Solution**
Having Identity Server capable of pulling Adaptive Authentication Scripts for an SP through its representation stored in a VCS like Github solve this. This will allow automating configuration changes automatically propagated through different environments, with correct CI\CD pipelines and test suits in place, similar to SPs.

Retrieving the configuration updates can be done with both pull (periodic pulling), and push (with GitHub Webhook) models

Effort BE::47

**Tasks**
-  [ ] Add module for handling updating adaptive scripts in the remote fetch module
-  [ ] Add UI manage git configuration and do changes for the application edit page
-  [ ] Integration test
-  [ ] Documentation

**Comment by madurangasiriwardena** [comment]
Can be implemented with https://github.com/wso2/product-is/issues/15461. Hence closing.
