### ISSUE TITLE
Rename "Renew Refresh Token" config to "Rotate Refresh Token"

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#9835]
Rename "Renew Refresh Token" config in OAuth2/OIDC app configuration to some wording similar to "Rotate Refresh Token" as it seems to be the standard term that is being used for the functionality provided by the config.

**Comment by jonasheinisch** [comment]
This request and it's implementation is a real critical mistake. "Refresh Token Rotation" is a fixed wording from this RFC: https://datatracker.ietf.org/doc/html/rfc6819#section-5.2.2.3
Renewing Refresh Tokens is not sufficient for "Refresh Token Rotation", but requires also a detection of the usage of old refresh tokens and as an effect of that invalidate all refresh tokens granted from that! This will fool people and consider them to comply to security recommendations, while they don't!
