### ISSUE TITLE
Validate OAuth2 token binding behaviour

### ISSUE THREAD

**Issue by thanujalk** [wso2/product-is#9838]
TODOs:

- Validate the behavior and document it
- Token revocation during session termination through the session API
- UI behavior between console and management console with regard to token revocation and binding
- SSO binding vs Cookie-based binding - document the behavior difference

**Comment by thanujalk** [comment]
Code changes are done.. Need to work on the document.

**Comment by pulasthi7** [comment]
@thanujalk Can we close this now?
