### ISSUE TITLE
Provide the ability to give a timeout to adaptive auth script evaluation

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#9842]
**Describe the improvement**
As of now, during the adaptive authentication, we execute the provided script and wait for the completion. However, this may be problematic if,

- Script is calling a slow endpoint and wait for response frequently
- Script has infinite loops/recursions added mistakenly

**Additional context**

To fix this, we would need to setup a reasonable timeout for the script execution and terminate the execution forcefully after the timeout.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
