### ISSUE TITLE
Couldn't login to the user after creating the user in the console

### ISSUE THREAD

**Issue by Sathiyakugan** [wso2/product-is#9844]
**Describe the issue:**
After creating the tenant when we add the user using the admin user of the tenant, couldn't log in using the created user.
Creating the user using the management console for that tenant could be able to login using the console.

**How to reproduce:**
1. Go to the console. https://localhost:9443/console login using the tenant admin
2. Go to Manage-> Users -> New user and create a new user with the admin role
3. Logout the tenant admin user and try to login using the newly created user

**Expected behaviour:**
The user should be able to log in

**Environment information** 
Product Version: IS 5.11.0-Beta2
OS: Linux
Database: Postgres
User store: JDBC

---
### Optional Fields

**Suggested labels:**
bug

**Comment by thanujalk** [comment]
Happens in the H2 as well
