### ISSUE TITLE
reCaptcha for SSO Login not shown on the console page.

### ISSUE THREAD

**Issue by Sathiyakugan** [wso2/product-is#9848]
**Describe the issue:**
After enabling the reCaptcha SSO Login could be able to login using the pickup dispatch app but could not able to login using the console. 
The error msg prompted was `reCaptcha validation is required for user.`

**How to reproduce:**
1. Follow this step to enable  reCaptcha  https://is.docs.wso2.com/en/latest/learn/configuring-recaptcha-for-self-registration/#configuring-recaptcha-for-self-registration and skip step `6` and use the console to enable the reCaptcha for SSO Login
2. logout and try to log in 

**Expected behaviour:**

Recaptcha should be shown when the user tries to log in using the console as well.

**Environment information** 
Product Version: IS 5.11.0-Beta2
OS: Linux
Database: Postgres
User store: JDBC

---

### Optional Fields

**Suggested labels:**
bug

**Comment by janakamarasena** [comment]
There is a limitation when using saas apps. When redirecting to the authentication page we don't have the tenant domain information of the user.

**Comment by tharindu-bandara** [comment]
`reCaptcha validation is required for the user.` This error message comes when the g-recaptcha-response header is missing in the request made to the server. If the Recaptcha is not configured properly(Recaptcha widget must be shown in the authentication page), this header will not be sent. How I tried this flow is,

1. Enabled re-captcha for both tenant and super tenant.
2. authenticated as the tenant admin to the console app

Couldn't observe the mentioned error. However, I was able to reproduce this issue by disabling the ReCaptcha for the super tenant where it made the ReCaptcha widget not available in the login portal.

**Comment by tharindu-bandara** [comment]
After having an offline discussion with @Sathiyakugan I have further verified this scenario. The authentication portal at the moment is not tenant qualified. So even if we enable Recaptcha in the tenant, the authentication portal will not load the Recaptcha widget thus causing this error due to the missing captcha response header. Therefore, the ongoing tenant qualifying URLs effort should resolve this issue eventually.

CC: @ayshsandu

**Comment by tharindu-bandara** [comment]
This issue needs to be covered with the effort: https://github.com/wso2/product-is/issues/9051.
