### ISSUE TITLE
Couldn't able to view users through console App

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9865]
**Describe the issue:**
Couldn't able to view users through console App in tenant mode

**How to reproduce:**
1. Created a tenant through the management console
2. Login to console app using the created tenant
4. Created a secondary user store.
5. Go to users tab.
6. Again go to list user store tab
7. Now again Navigate to users tab blank page is shown. No error logs in the back end
8. Saml tracer is as below.
9. Restart the server solves this issue.

[SAML-tracer.txt](https://github.com/wso2/product-is/files/5382716/SAML-tracer.txt)

**Expected behavior:**
Navigation should happen successfully.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-5.11.0-beta2-SNAPSHOT]
 - OS: [Linux]
 - Database: [H2]
 - Userstore: [JDBC]

---

**Comment by nilasini** [comment]
Seems https://github.com/wso2/product-is/issues/9790 fixed this issue. Need to verify after the release and close the issue

**Comment by thanujalk** [comment]
@thivi please verify and close.

**Comment by thivi** [comment]
I verified this issue in 5.11.0-beta3-SNAPSHOT and it is working fine.
