### ISSUE TITLE
[Console APP]Summary of user store addition missing some fields

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9866]
**Describe the issue:**
When adding user store through console app, the summary of the user store doesn't contain connection url and some other details.

**How to reproduce:**
1. Create a user store through the console app.
2. Check the summary tab you will see below details which missing some details.
![summary](https://user-images.githubusercontent.com/20336761/96083523-ed30f480-0eda-11eb-863f-29449c3d4970.png)

**Expected behavior:**
All details should be filled

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-5.11.0-beta2-SNAPSHOT]
 - OS: [Linux]
 - Database: [H2]
 - Userstore: [LDAP]

---

**Comment by thivi** [comment]
Similar issue: https://github.com/wso2/product-is/issues/9881
Duplicate issue: https://github.com/wso2/product-is/issues/9780
Fixed by https://github.com/wso2/identity-apps/pull/1250
