### ISSUE TITLE
Userstore is not redeployed when updated from the console

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9868]
**Describe the issue:**
When a userstore config is updated via the console, userstore is not reloaded.

**How to reproduce:**
1. Add a new userstore and make sure it's loaded
2. update the userstore from console
3. Userstore is not loaded to memory and unable to see the relevant logs in the wso2carbon.log.

**Expected behavior:**
Userstore must be loaded.

**Environment**

- OS: [Mac]
- Database: [MySQL]
- Userstore: [JDBC]
- Product [IS-5.11.0-Beta]

---

### Optional Fields

**Related issues:**
- Might be related to https://github.com/wso2/product-is/issues/9621

**Comment by janakamarasena** [comment]
This issue is happening due to the tenant not being loaded. If the tenant is loaded then this cannot be seen. Also same issue is reproducible through the management console after the tenant is unloaded. This the same cause for #9621 as well.
