### ISSUE TITLE
Deleted user stores are listed in management console/console app in tenant mode

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9869]
**Describe the issue:**
Deleted user stores are listed in management console/console app in tenant mode

**How to reproduce:**
1. Create two user stores through console app
2. Delete one of the user store xml file.
3. check user store list in MC/CA
4. Still deleted user store listed

**Expected behavior:**
delete user store shouldn't be listed

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-5.11.0-beta2-anashot]
 - OS: [Linux]
 - Database: [POSTGRE]
 - Userstore: [JDBC]

---

**Comment by janakamarasena** [comment]
Cannot reproduce in wso2is-5.11.0-beta3-SNAPSHOT
