### ISSUE TITLE
The console don't alert when the state set by user and switch to another page

### ISSUE THREAD

**Issue by Sathiyakugan** [wso2/product-is#9876]
**Describe the issue:**
Switching from one page another while changing the enable/disable button doesn't show any prompt to the user that the switching will lose the settings the user created.

**How to reproduce:**
1. Go to the console. https://localhost:9443/console
2. Go to Manage-> Account Management -> Account Disable -> Enable account disabling (don't click update)
3. Switch to  Account Recovery

**Expected behaviour:**
it should prompt the user that "whether he wants to save the changes"

**Environment information** 
Product Version: IS 5.11.0-Beta2
OS: Linux
Database: Postgres
User store: JDBC

---

**Suggested labels:**
Priority/Normal,   Severity/Minor, bug

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
