### ISSUE TITLE
Add documentation for SLO with SAML2

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#9878]
**Is your suggestion related to a missing or misleading document? Please describe.**
For SAML2 SLO, currently we have following document [1]. It only covers scenario where SLO is initiated from fed idp.

We need to have proper documentation explaining SLO with SAML, like in OIDC SLO docs.

[1]https://is.docs.wso2.com/en/5.11.0/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
