### ISSUE TITLE
[IS 5.10] Slowness in Filtering Users with Email Claim Using SCIM 2.0 API

### ISSUE THREAD

**Issue by darsham3** [wso2/product-is#9882]
**Describe the issue:**

There is a slowness observed when filtering users with email claim using SCIM API . This has been tested with a user base which has 200K plus users.

Please find the observations with different indexes:

INDEX | User Creation | User Search
-- | -- | --
UM_USER_ATTRIBUTE(UM_USER_ID, UM_ATTR_NAME, UM_ATTR_VALUE, UM_TENANT_ID); | 6 sec | 9 sec
UM_USER_ATTRIBUTE(UM_USER_ID, UM_ATTR_NAME, UM_ATTR_VALUE, UM_PROFILE_ID, UM_TENANT_ID); | 1 sec | 11 sec
UM_USER_ATTRIBUTE(UM_ATTR_NAME, UM_ATTR_VALUE); | 370ms | 127 ms

**Environment information:**
 - Product Version: IS 5.10.0
 - Database: MySql
 - Userstore:  JDBC

---

**Comment by NilukaSripalim** [comment]
Validate with the index below lsted DB versions:
Oracle 12c- 12.2.0.1.0
Oracle 19c - 19.3.0.0.0
Postgres 13, Postgress 12
MySQL 8 & 5.7 
Mssql 2017 & 2019 
Maria DB 10.4
DB2 11.5.4
