### ISSUE TITLE
Enabled status of userstores should be displayed in the userstore list page in the Console

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#9891]
**Describe the improvement**
The enabled status of the userstore being displayed in the userstore list could improve the user experience. Currently, no other information regarding the userstore except its name and description are shown in the list.

**Additional context**
![Screenshot from 2020-10-15 18-03-58](https://user-images.githubusercontent.com/25567263/96129505-541ecf80-0f14-11eb-80f7-81f2e4be4248.png)

**Comment by thivi** [comment]
To display this status, the userstores endpoint needs to be queried for each and every userstore in the list, which is a wasteful process. A better solution would be is to have this status returned with the list of userstores. The relevant backend issue can be tracked here: https://github.com/wso2/product-is/issues/10158
