### ISSUE TITLE
Missing instructions related to CORS configuration in 5.10.0 and 5.9.0

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9902]
**Is your suggestion related to a missing or misleading document? Please describe.**

Following documentation has the configuration related to IS versions before IS - 5.9.0 This needs to be updated after templating the cors configurations in web.xml 
https://is.docs.wso2.com/en/latest/administer/invoking-an-endpoint-from-a-different-domain/#applying-cors-filter-to-another-web-application

**Comment by Buddhimah** [comment]
Related configuration issue: https://github.com/wso2/product-is/issues/9917

**Comment by DinikaSen** [comment]
The configurations are now available in IS version 5.10
The steps on how to add the configuration are available in : https://github.com/wso2-support/carbon-kernel/pull/1127

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
