### ISSUE TITLE
Description field is named as Type in the userstore creation wizard

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9904]
**Describe the issue:**

The userstore description field is titled "Type" instead of "**Description**". The placeholder of the input field is correct.

![imageedit_19_3474609220](https://user-images.githubusercontent.com/25483865/96218552-97c01a80-0fa2-11eb-981c-19c42ee9aa9e.png)

**How to reproduce:**

1. Login to console.
2. Navigate to Manage Tab > User stores. Click on Add new user store and select one userstore type.

**Expected behavior:**
The above-marked input field should be titled as "Description".

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0-Beta
 - OS: Linux
 - Database: H2
 - Userstore:LDAP
---

**Comment by thivi** [comment]
Resolved by https://github.com/wso2/identity-apps/pull/1212
