### ISSUE TITLE
Can't add a group in to one userstore domain if the name is already used by another domain

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9908]
**Describe the issue:**
Can't use the a group name which is used in another userstore domain, when creating a group in a userstore domain via console app.

<img width="540" alt="admin_role in secondary us" src="https://user-images.githubusercontent.com/25483865/96221508-93164a80-0f3f-11eb-90d0-deccd1adfdd7.PNG">

**How to reproduce:**

1. Log into Console App 
2. Add a secondary userstore
3. Navigate to Manage Tab > Groups tab 
4. Since there is a PRIMARY/admin group, try to add a group named **admin** in the secondary userstore domain

**Expected behavior:**
Allow to use the group names which are even used in another userstore domains.
If it is not required to support -> give a proper error message

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0 - Beta
 - OS: Windows
 - Database: Postgres
 - Userstore: JDBC

**Comment by janakamarasena** [comment]
The search filter in the console is incorrect. It does not include the userstore domain name in the filter. Ideally if the group name is not from the PRIMARY userstore then the userstore domain should be appended in the filter.

it uses something like this
```
{
    "filter": "displayName eq <group_name>",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "startIndex": 1
}

ex: for group 'admin'
{
    "filter": "displayName eq admin",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "startIndex": 1
}
```

The filter should be like below when the usertore is NOT primary.

```
{
    "filter": "displayName eq <userstore_domain>/<group_name>",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "startIndex": 1
}

ex: for group name 'admin' in userstore 'AAAA'

{
    "filter": "displayName eq AAAA/admin",
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:SearchRequest"
    ],
    "startIndex": 1
}
```
