### ISSUE TITLE
[Migration] Config related docs are outdated for migration

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#9909]
**Is your suggestion related to a missing or misleading document? Please describe.**
Few minor changes need to be made in the configuration model doc for migration 

version

https://is.docs.wso2.com/en/5.11.0/references/new-configuration-model/

**Comment by sherenewso2** [comment]
Relevant links for migrating configurations have been provided at the top of this page:
https://is.docs.wso2.com/en/5.11.0/setup/migrating-what-has-changed/

Please reopen if needed.
