### ISSUE TITLE
Misleading description in Account disable setting

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9910]
**Is your suggestion related to an experience ? Please describe.**
Under Account Disable setting, there is a config to enable the feature and the description says `Allow an administrative user to disable user accounts`.

However, regardless of the feature is enabled or not, administrators are able to disable the account by management console or via API.

However, the configuration is taken into consideration for sending the account disable notifications to the user. 

**Describe the improvement**
Some suggestions,
- Change the label/description of the configuration to a more meaningful one
- Prevent allowing the administrators to disable accounts as the configuration explains

**Additional context**
- if the labels/description is changed it must be coming from the underneath governance connector implementation

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
