### ISSUE TITLE
Restructure doc space for a more developer focused documentation

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#9912]
**Is your suggestion related to a missing or misleading document? Please describe.**
Present documentation content is not well organized and at many points, doc talks about how to some configuration and set it up in the product without discussing the use case and the application, which makes hard to be followed by someone who is not well aware of the product and the domain

**Describe the improvement**
Restructure the document space to discuss use cases, applications, and then to move into how aspect.

Effort::120

**Comment by nilminiwso2** [comment]
Done for IS 6.0.0: https://is.docs.wso2.com/en/latest/
