### ISSUE TITLE
Can't save an OAuth config without providing a value for "AllowedOrigins" in the console

### ISSUE THREAD

**Issue by gayashanbc** [wso2/product-is#9918]
### Description
Can't save an OAuth config without providing a value for "AllowedOrigins"

### Reproduced On
5.11-beta

**Comment by pulasthi7** [comment]
Closing as duplicate of #9933

**Comment by NipuniBhagya** [comment]
Reopening issue to track the UI changes that need to be made along with the fix https://github.com/wso2/carbon-identity-framework/pull/3228
