### ISSUE TITLE
Missing tables in session cleanup scripts

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9929]
**Describe the issue:**
We have added the following two tables to the product recently and the session cleanup scripts are not improved to clean data in those tables.
- IDN_AUTH_SESSION_APP_INFO_TABLE
- IDN_AUTH_SESSION_META_DATA

Since we are recommending to disable internal cleanup and use stored procedures, all the stale data must be cleaned up in the stored procedures.

**Note** Since these tables are not available in previous versions it is better to check the existence of the table before cleanup. Because we use the script in the master branch for all the versions.

**Environment information** 
 - Product Version:  IS 5.10.0, IS 5.9.0

**Related issues:**
https://github.com/wso2/product-is/issues/5287
https://github.com/wso2/product-is/issues/7774

**Comment by madurangasiriwardena** [comment]
Cleanup script introduced above is not correct.

Current process
1. Check expired entries in the IDN_AUTH_SESSION_STORE table.
2. Clean the expired entries in IDN_AUTH_SESSION_STORE and get the session id for them.
3. Clean the entries from IDN_AUTH_USER_SESSION_MAPPING, IDN_AUTH_SESSION_APP_INFO, IDN_AUTH_SESSION_META_DATA tables related to the session ids identified in the above step.

However, the IDN_AUTH_SESSION_STORE table can have multiple entries with the same session id (when the user logs in to different apps in the same session or sends login requests from the same app multiple times in the same session).
So there can be active session ids, in the cleared entries in the IDN_AUTH_SESSION_STORE table.

**Comment by DinikaSen** [comment]
> Cleanup script introduced above is not correct.
> 
> Current process
> 
>     1. Check expired entries in the IDN_AUTH_SESSION_STORE table.
> 
>     2. Clean the expired entries in IDN_AUTH_SESSION_STORE and get the session id for them.
> 
>     3. Clean the entries from IDN_AUTH_USER_SESSION_MAPPING, IDN_AUTH_SESSION_APP_INFO, IDN_AUTH_SESSION_META_DATA tables related to the session ids identified in the above step.
> 
> 
> However, the IDN_AUTH_SESSION_STORE table can have multiple entries with the same session id (when the user logs in to different apps in the same session or sends login requests from the same app multiple times in the same session).
> So there can be active session ids, in the cleared entries in the IDN_AUTH_SESSION_STORE table.

The issue exists in the IDN_AUTH_SESSION_STORE table clean up logic as well.
This is captured in - https://github.com/wso2/product-is/issues/10912

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
