### ISSUE TITLE
Could not create service provider after delete application role

### ISSUE THREAD

**Issue by dachuylinux** [wso2/product-is#9931]
**Describe the issue:**
1. Create new service provider with name localhost8080.com, Application/localhost8080.com role will be create
2. Delete role Application/localhost8080.com
3. Show list Service Provider, you not see the service provider. Then, create new service provider name localhost8080.com again. A dialog will be show "**An application with name: 'localhost8080.com' already exists in tenantDomain: carbon.super**"

**Environment information:**
 - Product Version: IS wso2is-5.11.0-alpha3
 - OS: Linux mint
 - Database: H2(default
 - Userstore: Primary (default)

**Comment by ruwanta** [comment]
Looks like expected behaviour.
The user does not have necessary permission to view the SP, after removing the role. 
But the application is still there.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
