### ISSUE TITLE
Allow creating users with username 50 characters

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-is#9947]
**Describe the issue:**
Currently, there are issues when a tenant admin user having more than 50 characters in the username.
Mainly the issues occur related to registry access logs and workflows.

This is much critical in using email as a username.

The error has occurred in batch inserting set of registry-logs, where the log record's username is lengthy. This username is of the user who tried to access a registry resource. As the error occurs at a batch insert, the specific error can be unrelated to tenant 'hasintha.org', but the user who tried to access the registry at this tenant creation.

Few challenging tables are here.

CREATE TABLE IF NOT EXISTS REG_LOG (
REG_LOG_ID INTEGER AUTO_INCREMENT,
REG_PATH VARCHAR (750),
**REG_USER_ID VARCHAR (31) NOT NULL,**
REG_LOGGED_TIME TIMESTAMP NOT NULL,
REG_ACTION INTEGER NOT NULL,
REG_ACTION_DATA VARCHAR (500),
REG_TENANT_ID INTEGER DEFAULT 0,
PRIMARY KEY (REG_LOG_ID, REG_TENANT_ID)
)ENGINE INNODB;

Relevant table schema
CREATE TABLE IF NOT EXISTS WF_BPS_PROFILE (
PROFILE_NAME VARCHAR(45),
HOST_URL_MANAGER VARCHAR(255),
HOST_URL_WORKER VARCHAR(255),
**USERNAME VARCHAR(45),**
PASSWORD VARCHAR(1023),
CALLBACK_HOST VARCHAR (45),
CALLBACK_USERNAME VARCHAR (45),
CALLBACK_PASSWORD VARCHAR (255),
TENANT_ID INTEGER DEFAULT -1,
PRIMARY KEY (PROFILE_NAME, TENANT_ID)
)ENGINE INNODB;

**Comment by janakamarasena** [comment]
Related issue https://github.com/wso2/product-is/issues/5460

**Comment by ayshsandu** [comment]
Following queries may give a hint on some of the tables that needs alterations.

```
ALTER TABLE REG_RESOURCE ALTER COLUMN REG_CREATOR TYPE VARCHAR(255);
ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_CREATOR TYPE VARCHAR(255);
ALTER TABLE REG_RESOURCE ALTER COLUMN REG_LAST_UPDATOR TYPE VARCHAR(255);
ALTER TABLE REG_COMMENT ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_RATING ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_TAG ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_LOG ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
```

**Comment by ayshsandu** [comment]
Fixed in:
https://github.com/wso2-extensions/identity-workflow-impl-bps/pull/52
https://github.com/wso2/carbon-identity-framework/pull/3271
https://github.com/wso2/carbon-kernel/pull/2855

**Comment by ayshsandu** [comment]
Created https://github.com/wso2/carbon-kernel/issues/2856 to track the changes in the carbon-kernel. Once, carbon-kernel is released with the above changes, need to bump the version in product-is to include updated dbscripts.
