### ISSUE TITLE
Fail user assigning to a newly added roles. Works fine for default roles

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9951]
**Describe the issue:**
Failed to assign users to a newly created role, but there is no issue when assigning users for the default role such as admin, system, Application/Console, Application/My Account.

It gives the error message as **an error updating the selected group**. 
![Screenshot from 2020-10-19 14-40-49](https://user-images.githubusercontent.com/25483865/96429660-d2ce8200-121e-11eb-8a17-ee4efae6580d.png)

If you look at the failing request, it is` PATCH request to /Groups endpoint` using the role id. Actually, it should be PATCH to` /Roles/{role-id}  `. However, assigning users to default roles won't fail even the request is made to /Groups endpoint

![Screenshot from 2020-10-19 14-41-13](https://user-images.githubusercontent.com/25483865/96429733-eaa60600-121e-11eb-9c94-52ffe2837cc3.png)

**How to reproduce:**

- Login to Console (https://localhost:9443/console/login)
- Navigate to Manage tab-> Roles . Click on `+ New Role`.
- Provide a role name and click on the Next button to proceed further. Don't assign any permission/ user/groups.
- Then, go to the created role's users tab. Click on Assign User and try to assign some users. That request will fail.

**Expected behavior:**
Successful user assignment to the role. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0-Beta3-SNAPSHOT
 - OS:  Linux
 - Database:  H2
 - Userstore: LDAP

**Comment by janakamarasena** [comment]
Similar https://github.com/wso2/product-is/issues/10037
