### ISSUE TITLE
Add localization support for password policy violation errors.

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#9955]
**Description:**
Currently, we don't have any entries maintained at Resources.properties file [1] for error messages related to password policy violations such as history violations and pattern violations. As per the current implementation logic available at [2] we can define an error description in the Resources.properties file by having the error code as the key. For example by including an entry as `22001=custom error message for password history violation` in the Resources.properties file. This approach can be followed for password history violation error.

However when it comes to pattern violations such as:

- Password must have at least 6 characters
- 'Password pattern policy violated. Password should contain a digit[0-9], a lower case letter[a-z], an upper case letter[A-Z], one of !@#$%&* characters'
- Cannot use the username as the password

the same error code (20035) is maintained. Therefore we can't distinguish the 3 scenarios separately via the error code to follow the approach which I have mentioned above for password history violation. Also with password pattern violations the error message is not static. It will depend on the policy we have configured. Therefore going forward we need to add  parameterized support for localization to handle such cases. Another point to be considered is to support localization of these error messages in a tenant-specific manner as the policies can defined in the tenant level and it should be reflected in the error message shown in the UI properly.

[1] https://github.com/wso2/identity-apps/blob/master/apps/recovery-portal/src/main/resources/org/wso2/carbon/identity/mgt/recovery/endpoint/i18n/Resources.properties
[2] https://github.com/wso2/identity-apps/blob/master/apps/recovery-portal/src/main/webapp/password-reset-complete.jsp#L109

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
