### ISSUE TITLE
Having Brackets in the username not supported

### ISSUE THREAD

**Issue by tharindu-b-hewage** [wso2/product-is#9958]
**Describe the issue:**
When a username contains brackets(ex: `smith[test]john`), functionalities of the server does not work. Some of them are, searching users in the management console, invoking username/password recovery APIs, etc.  This is happening since, during some flows, the DB query executed at the end will have the brackets in the LIKE query value. 

This is the query executed for initiating password recovery. The underneath DB layer does not support having brackets in the value for the LIKE operator(Code line: https://github.com/wso2/carbon-kernel/blob/3740b55a5b37b4cbbc328f91f807e3a50043c8b8/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L2328).
```
SELECT DISTINCT UM_USER.UM_USER_ID
FROM UM_USER,
     UM_USER_ATTRIBUTE
WHERE UM_USER_ATTRIBUTE.UM_USER_ID = UM_USER.UM_ID
  AND UM_USER_ATTRIBUTE.UM_ATTR_NAME = 'uid'
  AND UM_USER_ATTRIBUTE.UM_ATTR_VALUE LIKE 'tharindu[SLASH]bandara'
  AND UM_USER_ATTRIBUTE.UM_PROFILE_ID = 'default'
  AND UM_USER_ATTRIBUTE.UM_TENANT_ID = -1234
  AND UM_USER.UM_TENANT_ID = -1234
```
There may be some other DB related reserved characters, which could lead to such scenarios.

**How to reproduce:**
Create a user with the name, `tharindu[SLASH]bandara`. Make sure to fill in the email claim value. Then initiate a password recovery request. It will fail with no user exist. Also, go to the management console and search by `tharindu[SLASH]bandara`, it will return zero users.

**Expected behavior:**
Having `[` should be supported in the username, or should be documented if it's not supported.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.10.0
 - OS: OSX
 - Database: MsSQL
 - Userstore: UniqueID JDBC + MSSQL 
---

**Comment by pulasthi7** [comment]
We can escape the '[' character to get this supported. However, I feel it would make things complicated and may have an impact on performance as well. So I'm +1 to document and restrict the usage of these characters. @thanujalk WDYT?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
