### ISSUE TITLE
Add saml sp through console app gives wrong error messages

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9962]
**Describe the issue:**
when adding a saml sp through console app, for a successfull case getting "issuer name is mandatory". But issuer name was there and got success full message for s addition as well.

**How to reproduce:**
Add saml sp through console app.

**Expected behavior:**
No error message.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by brionmario** [comment]
This issue is not reproducible with the `5.11.0-BETA4`, hence closing the issue.
