### ISSUE TITLE
[IS-5.10.0] [UX] Pop-up messages are not displayed during user creation in management console

### ISSUE THREAD

**Issue by darsham3** [wso2/product-is#9964]
**Describe the issue:**
Pop-up messages are not shown in UI for following scenarios:

1. User creation with weak password - No error message displayed in UI as a popup. There are errors logged in carbon log.
2. Successful user creation - No info is shown in UI even though the user is created successfully. 

**How to reproduce:**
1. Enable the password complexity
2. Create a user with weak password (with correct length and w/o special characters)
3. Create user with strong password

**Expected behavior:**
Display proper INFO / ERROR popup messages.

**Environment information** 
 - Product Version:  IS 5.10.0
 - WUM: 1602263472692
 - OS: Linux
 - Database: Oracle 11g

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
