### ISSUE TITLE
Does not alert that a user cannot use a already registered issuer for a saml application 

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#9967]
**Describe the issue:**
When a user tries to register a saml application with an already registered issuer name there's no indication that a user cannot use an already registered issuer

**How to reproduce:**
1. Access https://localhost:9443/console
2. Login as super admin
3. Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4. Register an SP with issuer name travelocity.com
5. Try to add another sp with the same issuer name travelocity.com

**Observation**
Even though UI should prompt a warning or error message for the user that a duplicate issuer name cannot be used. There's no such indication. Once click on the Register button nothing will happen and there's no any guide for the user that he cannot use the same issuer.

**Expected behavior:**
The user needs to be given an alert that he cant use an already registered issuer

**Environment information**

Mssql 2019
uniqueid jdbc
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121

**Comment by brionmario** [comment]
Tested the above scenario and couldn't recreate the error. I'm seeing the error message as expected when trying to add an application with the same issuer.

@ShanikaWickramasinghe Please verify.

<img width="1051" alt="Screen Shot 2020-10-23 at 6 19 14 PM" src="https://user-images.githubusercontent.com/25959096/97005589-485a8b00-155c-11eb-8361-2dd1f284383d.png">

**Comment by ShanikaWickramasinghe** [comment]
Verified with latest 5.11.0 beta3 and does not get reproduce against beta3, therefore, closing the issue.
