### ISSUE TITLE
SCIM Ask password account does not get locked until user reset the password

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#9969]
When creating a user with the AskPassword option using SCIM, the user account is not getting locked until the user resets their password. However, it's expected to have a random password created from the application when creating the user with the AskPassword option, so that the user won't be able to login to the application. As an improvement, we can lock the user until the user resets their password.

Relared to #5651

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
