### ISSUE TITLE
Cannot load UserInfo Details with Myaccount getting a error as Error: Cannot read property 'department' of undefined

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#9973]
**Describe the issue:**
Cannot load the Personal Info from the user account for the super admin and tenant admin user on MSSQL 2019

**How to reproduce:**
1. Login to myaccount (https://localhost:9443/myaccount) as super admin user
2. Create a tenant user with management console and login as that user for the myaccount (https://localhost:9443/myaccount)
3. Observed the error against both mssql 2019 and mariadb 10.4 

**Expected behavior:**
Should load the personal info whe clicked on that option

**Environment information** 

Mssql 2019 and Maria DB 10.4
uniqueid jdbc as primary userstore
IS 5.11.0 beta3 snapshot
ubuntu 16.04
Chrome Version 85.0.4183.121
 
![console5](https://user-images.githubusercontent.com/31848014/96563652-cf4eff80-12df-11eb-88e4-bceb69e61fa4.png)

**Comment by NilukaSripalim** [comment]
The same behavior when configuring the primary user store with  (JDBC)  DB2 and Oracle
