### ISSUE TITLE
Inaccurate active sessions count in analytics dashboard

### ISSUE THREAD

**Issue by Avarjana** [wso2/product-is#9974]
**Describe the issue:**
Active sessions count in analytics dashboard does not change on session termination via myaccount -> security -> Active IDP sessions.

**How to reproduce:**
- Login to sample application (pickup-dispatch) or myaccount.
- Terminate the session using myaccount -> security -> Active IDP sessions

**Expected behavior:**
When login -> Active session count += 1
When terminated -> Active session count -= 1

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-beta2 
 - OS: Ubuntu 18.04 LTS
 - Database: H2
 - Userstore: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
