### ISSUE TITLE
Handling SAML Single Logout Requests from Federated identity Providers section has wrong image

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9978]
**Is your suggestion related to a missing or misleading document? Please describe.**
In the doc[1] under the section "Handling SAML Single Logout Requests from Federated identity Providers", "Configuring Identity Provider(Secondary IS) in the Primary IS" point 6 has below lines

`Expand the SAML2 Web SSO Configuration section and fill the required details. ![saml-slo-federated-idp-config](../assets/img/tutorials/saml-slo-federated-idp-config.png `

Ideally, it should point to the image.

[1] https://is.docs.wso2.com/en/5.11.0/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2224
