### ISSUE TITLE
Wrong link pointed for Configuring Pickup Dispatch application in the Primary IS  

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9979]
**Is your suggestion related to a missing or misleading document? Please describe.**
In doc[1] under "Configuring Primary IS(Service Provider) in the Secondary IS" the third step mentioned as below.

**Follow the steps in Configuring Pickup Dispatch application in the Primary IS and configure the service provider with the details given below.**

Here the hyperlink redirect to a non exsting page

[1] https://is.docs.wso2.com/en/5.11.0/learn/handling-saml-single-logout-requests-from-federated-identity-providers/

**Comment by gomathyk** [comment]
Resolved with https://github.com/wso2/docs-is/pull/2224
