### ISSUE TITLE
Validate HEAD requests properly when clicking on account confirmation link received via an email

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#9983]
**Describe the issue:**
A user creates an account via self-registration. The user uses Microsoft outlook email service and receives the account confirmation mail to this account. The user clicks on the confirmation link and encounters an error similar to given below:
`"Error! Invalid Code '3c9615b6-ee82-47ad-83fb-0335ee2f61ff.'"` 
However, the user account gets confirmed.

**How to reproduce:**
In WSO2 IS enable self-registration and account lock on creation properties. Then try out the self-registration flow by providing a Microsoft Outlook email address where "Office 365 Advanced Threat Protection" is enabled. Upon receiving the mail click on the confirmation link.

**Expected behavior:**
The end-user should not get an invalid code error.

This behavior occurs due to the safelink protection of Outlook/ Office 365, as it sends a HEAD request to the original link before redirecting on the browser. When WSO2 IS receives the HEAD request, it completes the account verification flow since it has to do all processing in order to respond back to a HEAD request. Therefore, as the WSO2 IS already processed the account confirmation request, the user account will be confirmed and the confirmation code will be invalidated. Hence Invalid Code error message will be displayed when the user clicks on the account confirmation link.

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by rksk** [comment]
The same needs to be fixed for password recovery flow as well.
