### ISSUE TITLE
Couldn't get role claim through SAML 2.0 supported IDP

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9992]
**Describe the issue:**
SSO with SAML 2.0 supported SP with SAML 2.0 supported IDP where IDP role values couldn't be obtained.

**How to reproduce:**
1. Configure SAML federation
2. Try to get the role claim in the saml response by configuring the requested claim as role.
3. Couldn't able to get it but emailaddress can able to be retireved.

**Expected behavior:**
Roles int eh saml response

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
  - Product Version:IS-5.11.0-beta2
 - OS: Linux
 - Database: POSTGRE
 - Userstore: JDBC

---

**Comment by thanujalk** [comment]
Tested with the 5.11.0-Beta3 pack and able to get the role claim from federated IdP.
