### ISSUE TITLE
Add Application, IDP, User image upload capability

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#9996]
**Problem definition**
Currently we don't have a way to upload user image or Application logo or IDP image from the console app.

**Preferred Solution**
We have to consume Media API [1] and develop this feature in console app. As well as in My account app profile image update section.

Related issues: https://github.com/wso2/product-is/issues/8694

Also we need to update where we show this image. Authentication endpoint and listing + detail pages in console app etc.

[1] https://github.com/wso2/product-is/issues/8499

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
