### ISSUE TITLE
Email addresses are not getting validated in SCIM API

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#9997]
When signing up a new user via SCIM API, email validation doesn't apply. Currently its possible to sign up a user by putting any value for the email field. Please check with the following request

**How to re-produce** 
Send a HTTP request as follows
```
curl --location --request POST 'https://localhost:9443/wso2/scim/Users' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "schemas": [],
    "name": {
        "familyName": "Suresh",
        "givenName": "Peiris"
    },
    "userName": "suresh",
    "password": "suresh1234",
    "emails": [
        {
            "primary": true,
            "value": "anything",
            "type": "home"
        },
        {
            "value": "anything",
            "type": "work"
        }
    ]
}'
```
**Environment information** (Please complete the following information; remove any unnecessary fields) :

Product Version: 5.11.0 Beta2 SNAPSHOT
OS: Ubuntu 18.04
Database: MySQL
Primary User store: JDBC
Secondary User store: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
