### ISSUE TITLE
Username not getting validated in SCIM API

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#9999]
When signing up a new user via SCIM API, username validation doesn't apply. Currently its possible to sign up a user by putting any random value for username field even special characters are allowed. Please check with the following request

**How to re-produce**
Send a HTTP request as follows

**Request**
```
curl --location --request POST 'https://localhost:9443/wso2/scim/Users' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "schemas": [],
    "name": {
        "familyName": "Suresh",
        "givenName": "Peiris"
    },
    "userName": "'\''$#",
    "password": "suresh1234",
    "emails": [
        {
            "primary": true,
            "value": "anything",
            "type": "home"
        },
        {
            "value": "anything",
            "type": "work"
        }
    ]
}'
```

**Environment information**

Product Version: 5.11.0 Beta2 SNAPSHOT
OS: Ubuntu 18.04
Database: MySQL
Primary User store: JDBC
Secondary User store: LDAP

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
